CUBRID Engine: src/base/adjustable_array.h File Reference
adjustable_array.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include "porting.h"
Classes
struct adj_array
Macros
#define ADJ_AR_EOA -1
Typedefs
typedef enum adj_err_code ADJ_ERR_CODE
typedef struct adj_array ADJ_ARRAY
Enumerations
enum adj_err_code {
ADJ_NOERROR = 0, ADJ_ERR_BAD_START = -1, ADJ_ERR_BAD_END = -2, ADJ_ERR_BAD_NFROM = -3,
ADJ_ERR_BAD_ALLOC = -4, ADJ_ERR_BAD_ELEMENT = -5, ADJ_ERR_BAD_MIN = -6, ADJ_ERR_BAD_RATE = -7,
ADJ_ERR_BAD_INIT = -8, ADJ_ERR_BAD_INITIAL = -9, ADJ_ERR_BAD_LENGTH = -10, ADJ_ERR_BAD_ADJ_ARR_PTR = -99
}
Functions
const char * adj_ar_concat_strings (const char *string1, const char *string2,...)
ADJ_ARRAY * adj_ar_new (int element_size, int min, float growth_rate)
void adj_ar_free (ADJ_ARRAY *adj_array_p)
int adj_ar_reset (ADJ_ARRAY *adj_array_p, int element_size, int min, float growth_rate)
int adj_ar_initialize (ADJ_ARRAY *adj_array_p, const void *initial, int initial_length)
int adj_ar_replace (ADJ_ARRAY *adj_array_p, const void *src, int src_length, int start, int end)
int adj_ar_remove (ADJ_ARRAY *adj_array_p, int start, int end)
int adj_ar_insert (ADJ_ARRAY *adj_array_p, const void *src, int src_length, int start)
int adj_ar_append (ADJ_ARRAY *adj_array_p, const void *src, int src_length)
void * adj_ar_get_buffer (const ADJ_ARRAY *adj_array_p)
int adj_ar_length (const ADJ_ARRAY *adj_array_p)
Macro Definition Documentation
#define ADJ_AR_EOA -1
Definition at line 35 of file adjustable_array.h.
Referenced by adj_ar_append(), adj_ar_initialize(), adj_ar_replace(), bifmt_numeric_value(), cnv_get_value_string_buffer(), cnv_valid_currency(), cnv_wcs(), co_conversion_spec(), co_find_conversion(), co_signal(), co_signalv(), fmt_fractional_value(), and tfmt_new().
Typedef Documentation
typedef struct adj_array ADJ_ARRAY
Definition at line 54 of file adjustable_array.h.
typedef enum adj_err_code ADJ_ERR_CODE
Definition at line 52 of file adjustable_array.h.
Enumeration Type Documentation
enum adj_err_code
Enumerator
ADJ_NOERROR
ADJ_ERR_BAD_START
ADJ_ERR_BAD_END
ADJ_ERR_BAD_NFROM
ADJ_ERR_BAD_ALLOC
ADJ_ERR_BAD_ELEMENT
ADJ_ERR_BAD_MIN
ADJ_ERR_BAD_RATE
ADJ_ERR_BAD_INIT
ADJ_ERR_BAD_INITIAL
ADJ_ERR_BAD_LENGTH
ADJ_ERR_BAD_ADJ_ARR_PTR
Definition at line 37 of file adjustable_array.h.
Function Documentation
int adj_ar_append (ADJ_ARRAY * adj_array_p, const void * src, int src_length)
Definition at line 349 of file adjustable_array.c.
References ADJ_AR_EOA, adj_ar_replace(), assert, and NULL.
Referenced by adj_ar_concat_strings(), adj_ar_initialize(), co_conversion_spec(), co_signalv(), db_datetime_string(), db_string_date(), db_time_string(), db_timestamp_string(), and tfmt_new().
const char* adj_ar_concat_strings (const char * string1, const char * string2, ...)
Definition at line 48 of file adjustable_array.c.
References adj_ar_append(), adj_ar_get_buffer(), adj_ar_new(), adj_ar_reset(), NULL, and strlen.
Referenced by bifmt_numeric_value(), ffmt_value(), and mfmt_value().
void adj_ar_free (ADJ_ARRAY * adj_array_p)
Definition at line 122 of file adjustable_array.c.
References adj_array::buffer.
Referenced by cubthread::entry::clear_resources(), cnvutil_cleanup(), and co_final().
void* adj_ar_get_buffer (const ADJ_ARRAY * adj_array_p)
Definition at line 362 of file adjustable_array.c.
References assert, adj_array::buffer, and NULL.
Referenced by adj_ar_concat_strings(), bifmt_numeric_value(), cnv_wcs(), co_conversion_spec(), co_signal(), co_signalv(), db_datetime_string(), db_string_date(), db_time_string(), db_timestamp_string(), ffmt_value(), fmt_fractional_value(), mfmt_value(), num_fmt_print(), and tfmt_new().
int adj_ar_initialize (ADJ_ARRAY * adj_array_p, const void * initial, int initial_length)
Definition at line 177 of file adjustable_array.c.
References adj_ar_append(), ADJ_AR_EOA, adj_ar_remove(), ADJ_ERR_BAD_INIT, ADJ_ERR_BAD_LENGTH, ADJ_NOERROR, assert, adj_array::buffer, adj_array::cur_length, adj_array::element_size, adj_array::min_length, NULL, and p.
Referenced by co_signalv().
int adj_ar_insert (ADJ_ARRAY * adj_array_p, const void * src, int src_length, int start)
Definition at line 334 of file adjustable_array.c.
References adj_ar_replace(), assert, and NULL.
Referenced by bifmt_numeric_value(), ffmt_value(), fmt_fractional_value(), mfmt_value(), and num_fmt_print().
int adj_ar_length (const ADJ_ARRAY * adj_array_p)
Definition at line 375 of file adjustable_array.c.
References assert, adj_array::buffer, adj_array::cur_length, adj_array::element_size, and NULL.
Referenced by cnv_wcs(), and co_signalv().
ADJ_ARRAY* adj_ar_new (int element_size, int min, float growth_rate)
Definition at line 95 of file adjustable_array.c.
References adj_ar_reset(), ADJ_NOERROR, adj_array::buffer, adj_array::element_size, adj_array::max_length, and NULL.
Referenced by adj_ar_concat_strings(), cnv_get_value_string_buffer(), cnv_valid_currency(), cnv_wcs(), co_conversion_spec(), co_signalv(), and tfmt_new().
int adj_ar_remove (ADJ_ARRAY * adj_array_p, int start, int end)
Definition at line 318 of file adjustable_array.c.
References adj_ar_replace(), assert, and NULL.
Referenced by adj_ar_initialize(), bifmt_numeric_value(), co_conversion_spec(), co_signalv(), ffmt_value(), fmt_fractional_value(), mfmt_value(), num_fmt_print(), and tfmt_new().
int adj_ar_replace (ADJ_ARRAY * adj_array_p, const void * src, int src_length, int start, int end)
Definition at line 231 of file adjustable_array.c.
References ADJ_AR_EOA, ADJ_ERR_BAD_ALLOC, ADJ_ERR_BAD_END, ADJ_ERR_BAD_NFROM, ADJ_ERR_BAD_START, ADJ_NOERROR, assert, adj_array::buffer, adj_array::cur_length, adj_array::element_size, adj_array::max_length, adj_array::min_length, NULL, and adj_array::rate.
Referenced by adj_ar_append(), adj_ar_insert(), adj_ar_remove(), bifmt_numeric_value(), cnv_get_value_string_buffer(), cnv_valid_currency(), cnv_wcs(), co_conversion_spec(), co_signal(), and co_signalv().
int adj_ar_reset (ADJ_ARRAY * adj_array_p, int element_size, int min, float growth_rate)
Definition at line 143 of file adjustable_array.c.
References ADJ_ERR_BAD_ELEMENT, ADJ_ERR_BAD_MIN, ADJ_ERR_BAD_RATE, ADJ_NOERROR, assert, adj_array::cur_length, adj_array::element_size, adj_array::max_length, min, adj_array::min_length, NULL, and adj_array::rate.
Referenced by adj_ar_concat_strings(), and adj_ar_new().