CUBRID Engine: src/api/api_common.h File Reference
api_common.h File Reference
#include "api_handle.h"
Classes
struct common_api_structure_s
struct api_resultset_meta_s
struct api_resultset_meta_ifs_s
struct api_resultset_s
struct api_resultset_ifs_s
struct api_object_resultset_pool_s
struct value_indexer_s
struct value_indexer_ifs_s
struct value_bind_table_s
struct value_bind_table_ifs_s
struct api_collection_s
struct api_collection_ifs_s
struct cubrid_api_function_table_s
Macros
#define COMMON_API_STRUCTURE_HEADER
#define COMMON_RESULTSET_META_HEADER
#define COMMON_RESULTSET_HEADER
Typedefs
typedef struct common_api_structure_s COMMON_API_STRUCTURE
typedef struct api_resultset_meta_s API_RESULTSET_META
typedef struct api_resultset_meta_ifs_s API_RESULTSET_META_IFS
typedef struct api_resultset_s API_RESULTSET
typedef struct api_resultset_ifs_s API_RESULTSET_IFS
typedef struct api_object_resultset_pool_s API_OBJECT_RESULTSET_POOL
typedef struct VALUE_AREA VALUE_AREA
typedef struct API_VALUE API_VALUE
typedef struct value_indexer_s VALUE_INDEXER
typedef struct value_indexer_ifs_s VALUE_INDEXER_IFS
typedef struct value_bind_table_s VALUE_BIND_TABLE
typedef struct value_bind_table_ifs_s VALUE_BIND_TABLE_IFS
typedef struct api_collection_s API_COLLECTION
typedef struct api_collection_ifs_s API_COLLECTION_IFS
typedef struct cubrid_api_function_table_s CUBRID_API_FUNCTION_TABLE
typedef enum handle_type CI_HANDLE_TYPE
typedef enum ci_conn_status CI_CONN_STATUS
typedef enum ci_stmt_status CI_STMT_STATUS
typedef enum check_purpose_s CHECK_PURPOSE
Enumerations
enum handle_type {
HANDLE_TYPE_INVALID = 0, HANDLE_TYPE_CONNECTION = 1, HANDLE_TYPE_STATEMENT, HANDLE_TYPE_RESULTSET,
HANDLE_TYPE_PMETA, HANDLE_TYPE_RMETA, HANDLE_TYPE_BATCH_RESULT
}
enum ci_conn_status { CI_CONN_STATUS_INITIALIZED = 0, CI_CONN_STATUS_CONNECTED = 1, CI_CONN_STATUS_DISCONNECTED = 2 }
enum ci_stmt_status {
CI_STMT_STATUS_INITIALIZED = 0x01, CI_STMT_STATUS_PREPARED = 0x02, CI_STMT_STATUS_EXECUTED = 0x04, CI_STMT_STATUS_BATCH_ADDED = 0x08,
CI_STMT_STATUS_CLOSED = 0x10
}
enum check_purpose_s { CHECK_FOR_GET = 0x1, CHECK_FOR_SET = 0x2, CHECK_FOR_INSERT = 0x4, CHECK_FOR_DELETE = 0x8 }
Functions
int array_indexer_create (int nvalue, VALUE_INDEXER **rvi)
int list_indexer_create (VALUE_INDEXER **rvi)
Variables
CUBRID_API_FUNCTION_TABLE Cubrid_api_function_table
Macro Definition Documentation
#define COMMON_API_STRUCTURE_HEADER
Value:
BH_BIND bind; \
  CI_HANDLE_TYPE handle_type
Definition at line 94 of file api_common.h.
#define COMMON_RESULTSET_HEADER
Value:
COMMON_API_STRUCTURE_HEADER; \
  API_RESULTSET_IFS *ifs
Definition at line 130 of file api_common.h.
#define COMMON_RESULTSET_META_HEADER
Value:
COMMON_API_STRUCTURE_HEADER; \
  API_RESULTSET_META_IFS *ifs
Definition at line 107 of file api_common.h.
Typedef Documentation
typedef struct api_collection_s API_COLLECTION
Definition at line 50 of file api_common.h.
typedef struct api_collection_ifs_s API_COLLECTION_IFS
Definition at line 51 of file api_common.h.
typedef struct api_object_resultset_pool_s API_OBJECT_RESULTSET_POOL
Definition at line 40 of file api_common.h.
typedef struct api_resultset_s API_RESULTSET
Definition at line 38 of file api_common.h.
typedef struct api_resultset_ifs_s API_RESULTSET_IFS
Definition at line 39 of file api_common.h.
typedef struct api_resultset_meta_s API_RESULTSET_META
Definition at line 36 of file api_common.h.
typedef struct api_resultset_meta_ifs_s API_RESULTSET_META_IFS
Definition at line 37 of file api_common.h.
typedef struct API_VALUE API_VALUE
Definition at line 43 of file api_common.h.
typedef enum check_purpose_s CHECK_PURPOSE
typedef enum ci_conn_status CI_CONN_STATUS
Definition at line 79 of file api_common.h.
typedef enum handle_type CI_HANDLE_TYPE
Definition at line 68 of file api_common.h.
typedef enum ci_stmt_status CI_STMT_STATUS
Definition at line 92 of file api_common.h.
typedef struct common_api_structure_s COMMON_API_STRUCTURE
Definition at line 35 of file api_common.h.
typedef struct cubrid_api_function_table_s CUBRID_API_FUNCTION_TABLE
Definition at line 53 of file api_common.h.
typedef struct VALUE_AREA VALUE_AREA
Definition at line 42 of file api_common.h.
typedef struct value_bind_table_s VALUE_BIND_TABLE
Definition at line 47 of file api_common.h.
typedef struct value_bind_table_ifs_s VALUE_BIND_TABLE_IFS
Definition at line 48 of file api_common.h.
typedef struct value_indexer_s VALUE_INDEXER
Definition at line 44 of file api_common.h.
typedef struct value_indexer_ifs_s VALUE_INDEXER_IFS
Definition at line 45 of file api_common.h.
Enumeration Type Documentation
enum check_purpose_s
Enumerator
CHECK_FOR_GET
CHECK_FOR_SET
CHECK_FOR_INSERT
CHECK_FOR_DELETE
Definition at line 195 of file api_common.h.
enum ci_conn_status
Enumerator
CI_CONN_STATUS_INITIALIZED
CI_CONN_STATUS_CONNECTED
CI_CONN_STATUS_DISCONNECTED
Definition at line 73 of file api_common.h.
enum ci_stmt_status
Enumerator
CI_STMT_STATUS_INITIALIZED
CI_STMT_STATUS_PREPARED
CI_STMT_STATUS_EXECUTED
CI_STMT_STATUS_BATCH_ADDED
CI_STMT_STATUS_CLOSED
Definition at line 84 of file api_common.h.
enum handle_type
Enumerator
HANDLE_TYPE_INVALID
HANDLE_TYPE_CONNECTION
HANDLE_TYPE_STATEMENT
HANDLE_TYPE_RESULTSET
HANDLE_TYPE_PMETA
HANDLE_TYPE_RMETA
HANDLE_TYPE_BATCH_RESULT
Definition at line 58 of file api_common.h.
Function Documentation
int array_indexer_create (int nvalue, VALUE_INDEXER ** rvi)
Definition at line 642 of file api_value_indexer.c.
References API_CALLOC, API_FREE, API_MALLOC, ARRAY_INDEXER_IFS_, assert, ER_INTERFACE_NO_MORE_MEMORY, value_indexer_s::ifs, array_indexer_s::indexer, NO_ERROR, NULL, array_indexer_s::nvalue, array_indexer_s::values, and array_indexer_s::vs_map.
Referenced by api_qres_update_value(), ci_stmt_set_parameter_impl(), and create_db_value_bind_table().
int list_indexer_create (VALUE_INDEXER ** rvi)
Definition at line 676 of file api_value_indexer.c.
References API_MALLOC, assert, list_indexer_s::cache_elem, list_indexer_s::cache_idx, dlisth_init, list_indexer_s::elems, ER_INTERFACE_NO_MORE_MEMORY, value_indexer_s::ifs, list_indexer_s::indexer, LIST_INDEXER_IFS_, list_indexer_s::nelems, NO_ERROR, and NULL.
Referenced by apif_collection_create(), and xcol_create().
Variable Documentation
CUBRID_API_FUNCTION_TABLE Cubrid_api_function_table
Definition at line 5491 of file cci_stub.c.