CUBRID Engine: src/api/api_value_indexer.c File Reference
api_value_indexer.c File Reference
#include "config.h"
#include <string.h>
#include <assert.h>
#include "api_util.h"
#include "api_common.h"
Classes
struct array_indexer_s
struct list_indexer_elem_s
struct list_indexer_s
struct li_mapf_arg
Typedefs
typedef struct array_indexer_s ARRAY_INDEXER
typedef struct list_indexer_elem_s LIST_INDEXER_ELEM
typedef struct list_indexer_s LIST_INDEXER
Functions
static int ai_api_check (VALUE_INDEXER *indexer, int index, CHECK_PURPOSE pup)
static int ai_api_length (VALUE_INDEXER *indexer, int *len)
static int ai_api_get (VALUE_INDEXER *indexer, int index, VALUE_AREA **rva, API_VALUE **rv)
static int ai_api_set (VALUE_INDEXER *indexer, int index, VALUE_AREA *va, API_VALUE *dv)
static int ai_api_map (VALUE_INDEXER *indexer, int(*mapf)(void *, int, VALUE_AREA *, API_VALUE *), void *arg)
static int ai_api_insert (VALUE_INDEXER *indexer, int index, VALUE_AREA *va, API_VALUE *dval)
static int ai_api_delete (VALUE_INDEXER *indexer, int index, VALUE_AREA **rva, API_VALUE **dbval)
static void ai_api_destroy (VALUE_INDEXER *indexer, void(*df)(VALUE_AREA *va, API_VALUE *db))
static int li_api_check (VALUE_INDEXER *indexer, int index, CHECK_PURPOSE pup)
static int li_api_length (VALUE_INDEXER *indexer, int *len)
static int li_api_get (VALUE_INDEXER *indexer, int index, VALUE_AREA **rva, API_VALUE **rv)
static int li_api_set (VALUE_INDEXER *indexer, int index, VALUE_AREA *va, API_VALUE *val)
static int li_api_map (VALUE_INDEXER *indexer, int(*mapf)(void *, int, VALUE_AREA *, API_VALUE *), void *arg)
static int li_api_insert (VALUE_INDEXER *indexer, int index, VALUE_AREA *va, API_VALUE *dval)
static int li_api_delete (VALUE_INDEXER *indexer, int index, VALUE_AREA **rva, API_VALUE **dbval)
static void li_api_destroy (VALUE_INDEXER *indexer, void(*df)(VALUE_AREA *va, API_VALUE *db))
static LIST_INDEXER_ELEM * li_getf (LIST_INDEXER *li, int index)
static int li_mapf (dlisth *h, void *arg, int *cont)
int array_indexer_create (int nvalue, VALUE_INDEXER **rvi)
int list_indexer_create (VALUE_INDEXER **rvi)
Variables
static VALUE_INDEXER_IFS ARRAY_INDEXER_IFS_
static VALUE_INDEXER_IFS LIST_INDEXER_IFS_
Typedef Documentation
typedef struct array_indexer_s ARRAY_INDEXER
Definition at line 29 of file api_value_indexer.c.
typedef struct list_indexer_s LIST_INDEXER
Definition at line 31 of file api_value_indexer.c.
typedef struct list_indexer_elem_s LIST_INDEXER_ELEM
Definition at line 30 of file api_value_indexer.c.
Function Documentation
static int ai_api_check (VALUE_INDEXER * indexer, int index, CHECK_PURPOSE pup) static
Definition at line 91 of file api_value_indexer.c.
References assert, ER_INTERFACE_GENERIC, NO_ERROR, NULL, and array_indexer_s::nvalue.
static int ai_api_delete (VALUE_INDEXER * indexer, int index, VALUE_AREA ** rva, API_VALUE ** dbval) static
Definition at line 208 of file api_value_indexer.c.
References ER_INTERFACE_NOT_SUPPORTED_OPERATION.
static void ai_api_destroy (VALUE_INDEXER * indexer, void(*)(VALUE_AREA *va, API_VALUE *db) df) static
Definition at line 221 of file api_value_indexer.c.
References API_FREE, assert, i, NULL, array_indexer_s::nvalue, array_indexer_s::values, and array_indexer_s::vs_map.
static int ai_api_get (VALUE_INDEXER * indexer, int index, VALUE_AREA ** rva, API_VALUE ** rv) static
Definition at line 130 of file api_value_indexer.c.
References assert, NO_ERROR, NULL, array_indexer_s::values, and array_indexer_s::vs_map.
static int ai_api_insert (VALUE_INDEXER * indexer, int index, VALUE_AREA * va, API_VALUE * dval) static
Definition at line 194 of file api_value_indexer.c.
References ER_INTERFACE_NOT_SUPPORTED_OPERATION.
static int ai_api_length (VALUE_INDEXER * indexer, int * len) static
Definition at line 112 of file api_value_indexer.c.
References assert, NO_ERROR, NULL, and array_indexer_s::nvalue.
static int ai_api_map (VALUE_INDEXER * indexer, int(*)(void *, int, VALUE_AREA *, API_VALUE *) mapf, void * arg) static
Definition at line 168 of file api_value_indexer.c.
References assert, i, NO_ERROR, NULL, array_indexer_s::nvalue, array_indexer_s::values, and array_indexer_s::vs_map.
static int ai_api_set (VALUE_INDEXER * indexer, int index, VALUE_AREA * va, API_VALUE * dv) static
Definition at line 151 of file api_value_indexer.c.
References assert, NO_ERROR, NULL, array_indexer_s::values, and array_indexer_s::vs_map.
int array_indexer_create (int nvalue, VALUE_INDEXER ** rvi)
Definition at line 642 of file api_value_indexer.c.
References API_CALLOC, API_FREE, API_MALLOC, ARRAY_INDEXER_IFS_, assert, ER_INTERFACE_NO_MORE_MEMORY, value_indexer_s::ifs, array_indexer_s::indexer, NO_ERROR, NULL, array_indexer_s::nvalue, array_indexer_s::values, and array_indexer_s::vs_map.
Referenced by api_qres_update_value(), ci_stmt_set_parameter_impl(), and create_db_value_bind_table().
static int li_api_check (VALUE_INDEXER * indexer, int index, CHECK_PURPOSE pup) static
Definition at line 264 of file api_value_indexer.c.
References assert, CHECK_FOR_INSERT, ER_INTERFACE_GENERIC, list_indexer_s::nelems, NO_ERROR, and NULL.
static int li_api_delete (VALUE_INDEXER * indexer, int index, VALUE_AREA ** rva, API_VALUE ** dbval) static
Definition at line 501 of file api_value_indexer.c.
References API_FREE, assert, list_indexer_s::cache_elem, list_indexer_s::cache_idx, dlisth_delete, li_getf(), list_indexer_s::nelems, NO_ERROR, NULL, list_indexer_elem_s::va, and list_indexer_elem_s::value.
static void li_api_destroy (VALUE_INDEXER * indexer, void(*)(VALUE_AREA *va, API_VALUE *db) df) static
Definition at line 602 of file api_value_indexer.c.
References API_FREE, assert, dlisth_delete, dlisth_is_empty, list_indexer_s::elems, if(), dlisth_s::next, NULL, list_indexer_elem_s::va, and list_indexer_elem_s::value.
static int li_api_get (VALUE_INDEXER * indexer, int index, VALUE_AREA ** rva, API_VALUE ** rv) static
Definition at line 394 of file api_value_indexer.c.
References assert, li_getf(), NO_ERROR, NULL, list_indexer_elem_s::va, and list_indexer_elem_s::value.
static int li_api_insert (VALUE_INDEXER * indexer, int index, VALUE_AREA * va, API_VALUE * dval) static
Definition at line 560 of file api_value_indexer.c.
References API_MALLOC, assert, list_indexer_s::cache_elem, list_indexer_s::cache_idx, dlisth_init, dlisth_insert_after, list_indexer_s::elems, ER_INTERFACE_NO_MORE_MEMORY, list_indexer_elem_s::header, li_getf(), list_indexer_s::nelems, NO_ERROR, NULL, list_indexer_elem_s::va, and list_indexer_elem_s::value.
static int li_api_length (VALUE_INDEXER * indexer, int * len) static
Definition at line 287 of file api_value_indexer.c.
References assert, list_indexer_s::nelems, NO_ERROR, and NULL.
static int li_api_map (VALUE_INDEXER * indexer, int(*)(void *, int, VALUE_AREA *, API_VALUE *) mapf, void * arg) static
Definition at line 476 of file api_value_indexer.c.
References li_mapf_arg::arg, assert, dlisth_map(), list_indexer_s::elems, li_mapf_arg::index, li_mapf(), li_mapf_arg::mapf, and NULL.
static int li_api_set (VALUE_INDEXER * indexer, int index, VALUE_AREA * va, API_VALUE * val) static
Definition at line 420 of file api_value_indexer.c.
References assert, li_getf(), NO_ERROR, NULL, list_indexer_elem_s::va, and list_indexer_elem_s::value.
static LIST_INDEXER_ELEM* li_getf (LIST_INDEXER * li, int index) static
Definition at line 305 of file api_value_indexer.c.
References assert, list_indexer_s::cache_elem, list_indexer_s::cache_idx, list_indexer_s::elems, i, list_indexer_s::nelems, dlisth_s::next, NULL, and dlisth_s::prev.
Referenced by li_api_delete(), li_api_get(), li_api_insert(), and li_api_set().
static int li_mapf (dlisth * h, void * arg, int * cont) static
Definition at line 450 of file api_value_indexer.c.
References li_mapf_arg::arg, assert, li_mapf_arg::index, li_mapf_arg::mapf, NO_ERROR, NULL, list_indexer_elem_s::va, and list_indexer_elem_s::value.
Referenced by li_api_map().
int list_indexer_create (VALUE_INDEXER ** rvi)
Definition at line 676 of file api_value_indexer.c.
References API_MALLOC, assert, list_indexer_s::cache_elem, list_indexer_s::cache_idx, dlisth_init, list_indexer_s::elems, ER_INTERFACE_NO_MORE_MEMORY, value_indexer_s::ifs, list_indexer_s::indexer, LIST_INDEXER_IFS_, list_indexer_s::nelems, NO_ERROR, and NULL.
Referenced by apif_collection_create(), and xcol_create().
Variable Documentation
VALUE_INDEXER_IFS ARRAY_INDEXER_IFS_ static
Initial value:
= {
  ai_api_check,
  ai_api_length,
  ai_api_get,
  ai_api_set,
  ai_api_map,
  ai_api_insert,
  ai_api_delete,
  ai_api_destroy
}
Definition at line 240 of file api_value_indexer.c.
Referenced by array_indexer_create().
VALUE_INDEXER_IFS LIST_INDEXER_IFS_ static
Initial value:
= {
  li_api_check,
  li_api_length,
  li_api_get,
  li_api_set,
  li_api_map,
  li_api_insert,
  li_api_delete,
  li_api_destroy
}
Definition at line 618 of file api_value_indexer.c.
Referenced by list_indexer_create().