CUBRID Engine: src/query/arithmetic.c File Reference
arithmetic.c File Reference
#include "arithmetic.h"
#include "config.h"
#include "crypt_opfunc.h"
#include "db_date.h"
#include "db_json.hpp"
#include "db_json_path.hpp"
#include "dbtype.h"
#include "error_manager.h"
#include "memory_private_allocator.hpp"
#include "memory_reference_store.hpp"
#include "numeric_opfunc.h"
#include "object_primitive.h"
#include "object_representation.h"
#include "string_opfunc.h"
#include "tz_support.h"
#include <algorithm>
#include <assert.h>
#include <cctype>
#include <float.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Macros
#define RETURN_ERROR(err)
#define RETURN_ERROR_WITH_ARG(err, arg)
#define MAX_DOMAIN_NAME_SIZE 150
Functions
static int db_mod_short (DB_VALUE *value, DB_VALUE *value1, DB_VALUE *value2)
static int db_mod_int (DB_VALUE *value, DB_VALUE *value1, DB_VALUE *value2)
static int db_mod_bigint (DB_VALUE *value, DB_VALUE *value1, DB_VALUE *value2)
static int db_mod_float (DB_VALUE *value, DB_VALUE *value1, DB_VALUE *value2)
static int db_mod_double (DB_VALUE *value, DB_VALUE *value1, DB_VALUE *value2)
static int db_mod_string (DB_VALUE *value, DB_VALUE *value1, DB_VALUE *value2)
static int db_mod_numeric (DB_VALUE *value, DB_VALUE *value1, DB_VALUE *value2)
static int db_mod_monetary (DB_VALUE *value, DB_VALUE *value1, DB_VALUE *value2)
static double round_double (double num, double integer)
static int move_n_days (int *monthp, int *dayp, int *yearp, const int interval)
static int round_date (DB_VALUE *result, DB_VALUE *value1, DB_VALUE *value2)
static double truncate_double (double num, double integer)
static DB_BIGINT truncate_bigint (DB_BIGINT num, DB_BIGINT integer)
static int truncate_date (DB_DATE *date, const DB_VALUE *format_str)
static int get_number_dbval_as_double (double *d, const DB_VALUE *value)
static int get_number_dbval_as_long_double (long double *ld, const DB_VALUE *value)
static int db_width_bucket_calculate_numeric (double *result, const DB_VALUE *value1, const DB_VALUE *value2, const DB_VALUE *value3, const DB_VALUE *value4)
static int is_str_find_all (DB_VALUE *val, bool &find_all)
static bool is_any_arg_null (DB_VALUE *const *args, int num_args)
int db_floor_dbval (DB_VALUE *result, DB_VALUE *value)
int db_ceil_dbval (DB_VALUE *result, DB_VALUE *value)
int db_sign_dbval (DB_VALUE *result, DB_VALUE *value)
int db_abs_dbval (DB_VALUE *result, DB_VALUE *value)
int db_exp_dbval (DB_VALUE *result, DB_VALUE *value)
int db_sqrt_dbval (DB_VALUE *result, DB_VALUE *value)
int db_power_dbval (DB_VALUE *result, DB_VALUE *value1, DB_VALUE *value2)
int db_mod_dbval (DB_VALUE *result, DB_VALUE *value1, DB_VALUE *value2)
int db_round_dbval (DB_VALUE *result, DB_VALUE *value1, DB_VALUE *value2)
int db_log_dbval (DB_VALUE *result, DB_VALUE *value1, DB_VALUE *value2)
int db_trunc_dbval (DB_VALUE *result, DB_VALUE *value1, DB_VALUE *value2)
int db_random_dbval (DB_VALUE *result)
int db_drandom_dbval (DB_VALUE *result)
int db_cos_dbval (DB_VALUE *result, DB_VALUE *value)
int db_sin_dbval (DB_VALUE *result, DB_VALUE *value)
int db_tan_dbval (DB_VALUE *result, DB_VALUE *value)
int db_cot_dbval (DB_VALUE *result, DB_VALUE *value)
int db_acos_dbval (DB_VALUE *result, DB_VALUE *value)
int db_asin_dbval (DB_VALUE *result, DB_VALUE *value)
int db_atan_dbval (DB_VALUE *result, DB_VALUE *value)
int db_atan2_dbval (DB_VALUE *result, DB_VALUE *value, DB_VALUE *value2)
int db_degrees_dbval (DB_VALUE *result, DB_VALUE *value)
int db_radians_dbval (DB_VALUE *result, DB_VALUE *value)
int db_log_generic_dbval (DB_VALUE *result, DB_VALUE *value, long b)
int db_bit_count_dbval (DB_VALUE *result, DB_VALUE *value)
int db_typeof_dbval (DB_VALUE *result, DB_VALUE *value)
int db_width_bucket (DB_VALUE *result, const DB_VALUE *value1, const DB_VALUE *value2, const DB_VALUE *value3, const DB_VALUE *value4)
int db_sleep (DB_VALUE *result, DB_VALUE *value)
int db_crc32_dbval (DB_VALUE *result, DB_VALUE *value)
int db_evaluate_json_contains (DB_VALUE *result, DB_VALUE *const *arg, int const num_args)
int db_evaluate_json_type_dbval (DB_VALUE *result, DB_VALUE *const *arg, int const num_args)
int db_evaluate_json_valid (DB_VALUE *result, DB_VALUE *const *arg, int const num_args)
int db_evaluate_json_length (DB_VALUE *result, DB_VALUE *const *arg, int const num_args)
int db_evaluate_json_depth (DB_VALUE *result, DB_VALUE *const *arg, int const num_args)
int db_evaluate_json_quote (DB_VALUE *result, DB_VALUE *const *arg, int const num_args)
int db_evaluate_json_unquote (DB_VALUE *result, DB_VALUE *const *arg, int const num_args)
int db_evaluate_json_pretty (DB_VALUE *result, DB_VALUE *const *arg, int const num_args)
int db_accumulate_json_arrayagg (const DB_VALUE *json_db_val, DB_VALUE *json_res)
int db_accumulate_json_objectagg (const DB_VALUE *json_key, const DB_VALUE *json_db_val, DB_VALUE *json_res)
int db_evaluate_json_extract (DB_VALUE *result, DB_VALUE *const *args, int num_args)
int db_evaluate_json_object (DB_VALUE *result, DB_VALUE *const *arg, int const num_args)
int db_evaluate_json_array (DB_VALUE *result, DB_VALUE *const *arg, int const num_args)
int db_evaluate_json_insert (DB_VALUE *result, DB_VALUE *const *arg, int const num_args)
int db_evaluate_json_replace (DB_VALUE *result, DB_VALUE *const *arg, int const num_args)
int db_evaluate_json_set (DB_VALUE *result, DB_VALUE *const *arg, int const num_args)
int db_evaluate_json_keys (DB_VALUE *result, DB_VALUE *const *arg, int const num_args)
int db_evaluate_json_remove (DB_VALUE *result, DB_VALUE *const *arg, int const num_args)
int db_evaluate_json_array_append (DB_VALUE *result, DB_VALUE *const *arg, int const num_args)
int db_evaluate_json_array_insert (DB_VALUE *result, DB_VALUE *const *arg, int const num_args)
int db_evaluate_json_contains_path (DB_VALUE *result, DB_VALUE *const *arg, const int num_args)
int db_evaluate_json_merge_preserve (DB_VALUE *result, DB_VALUE *const *arg, const int num_args)
int db_evaluate_json_merge_patch (DB_VALUE *result, DB_VALUE *const *arg, const int num_args)
int db_evaluate_json_search (DB_VALUE *result, DB_VALUE *const *args, const int num_args)
int db_evaluate_json_get_all_paths (DB_VALUE *result, DB_VALUE *const *arg, int const num_args)
int db_least_or_greatest (DB_VALUE *arg1, DB_VALUE *arg2, DB_VALUE *result, bool least)
Macro Definition Documentation
#define MAX_DOMAIN_NAME_SIZE 150
Referenced by db_width_bucket().
#define RETURN_ERROR (err)
Value:
do \
    { \
      if (prm_get_bool_value (PRM_ID_RETURN_NULL_ON_FUNCTION_ERRORS) == true) \
    { \
      db_make_null (result); \
      er_clear (); \
      return NO_ERROR; \
    } \
      else \
    { \
      er_set (ER_ERROR_SEVERITY, ARG_FILE_LINE, (err), 0); \
      return (err); \
    } \
    } \
  while (0)
Referenced by db_width_bucket().
#define RETURN_ERROR_WITH_ARG (err, arg)
Value:
do \
    { \
      if (prm_get_bool_value (PRM_ID_RETURN_NULL_ON_FUNCTION_ERRORS) == true) \
        { \
          db_make_null (result); \
          er_clear (); \
          return NO_ERROR; \
        } \
      else \
        { \
          er_set (ER_ERROR_SEVERITY, ARG_FILE_LINE, (err), 1, (arg)); \
          return (err); \
        } \
    } \
  while (0)
Referenced by db_width_bucket().
Function Documentation
int db_abs_dbval (DB_VALUE * result, DB_VALUE * value)
Definition at line 565 of file arithmetic.c.
References ARG_FILE_LINE, assert, db_get_bigint(), db_get_double(), db_get_float(), db_get_int(), db_get_monetary(), db_get_short(), DB_IS_NULL, db_locate_numeric, db_make_bigint(), db_make_double(), db_make_float(), db_make_int(), db_make_monetary(), db_make_null(), db_make_numeric(), db_make_short(), DB_NUMERIC_BUF_SIZE, DB_TYPE_BIGINT, DB_TYPE_CHAR, DB_TYPE_DOUBLE, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_MONETARY, DB_TYPE_NCHAR, DB_TYPE_NULL, DB_TYPE_NUMERIC, DB_TYPE_SHORT, DB_TYPE_VARCHAR, DB_TYPE_VARNCHAR, DB_VALUE_DOMAIN_TYPE, DB_VALUE_PRECISION, DB_VALUE_SCALE, ER_ERROR_SEVERITY, ER_QPROC_INVALID_DATATYPE, er_set(), NO_ERROR, numeric_db_value_abs(), prm_get_bool_value(), PRM_ID_RETURN_NULL_ON_FUNCTION_ERRORS, and tp_value_str_auto_cast_to_number().
Referenced by do_alter_serial(), do_create_serial(), fetch_peek_arith(), and pt_evaluate_db_value_expr().
int db_accumulate_json_arrayagg (const DB_VALUE * json_db_val, DB_VALUE * json_res)
Definition at line 5383 of file arithmetic.c.
References assert, ASSERT_ERROR, db_get_json_document(), DB_IS_NULL, db_json_add_element_to_array(), db_make_json_from_doc_store_and_release(), db_make_null(), db_value_to_json_value(), ER_FAILED, NO_ERROR, and NULL.
Referenced by qdata_aggregate_value_to_accumulator().
int db_accumulate_json_objectagg (const DB_VALUE * json_key, const DB_VALUE * json_db_val, DB_VALUE * json_res)
Definition at line 5437 of file arithmetic.c.
References assert, ASSERT_ERROR, db_get_json_document(), DB_IS_NULL, db_json_add_member_to_object(), db_make_json_from_doc_store_and_release(), db_make_null(), db_value_to_json_key(), db_value_to_json_value(), er_clear(), ER_FAILED, ER_JSON_DUPLICATE_KEY, NO_ERROR, and NULL.
Referenced by qdata_aggregate_multiple_values_to_accumulator().
int db_acos_dbval (DB_VALUE * result, DB_VALUE * value)
Definition at line 3872 of file arithmetic.c.
References ARG_FILE_LINE, COMPAT_MYSQL, DB_IS_NULL, db_make_double(), db_make_null(), DB_TYPE_NULL, DB_VALUE_DOMAIN_TYPE, ER_ERROR_SEVERITY, ER_QPROC_FUNCTION_ARG_ERROR, er_set(), err, error(), get_number_dbval_as_double(), NO_ERROR, prm_get_integer_value(), and PRM_ID_COMPAT_MODE.
Referenced by fetch_peek_arith(), and pt_evaluate_db_value_expr().
int db_asin_dbval (DB_VALUE * result, DB_VALUE * value)
Definition at line 3921 of file arithmetic.c.
References ARG_FILE_LINE, COMPAT_MYSQL, DB_IS_NULL, db_make_double(), db_make_null(), DB_TYPE_NULL, DB_VALUE_DOMAIN_TYPE, ER_ERROR_SEVERITY, ER_QPROC_FUNCTION_ARG_ERROR, er_set(), err, error(), get_number_dbval_as_double(), NO_ERROR, prm_get_integer_value(), and PRM_ID_COMPAT_MODE.
Referenced by fetch_peek_arith(), and pt_evaluate_db_value_expr().
int db_atan2_dbval (DB_VALUE * result, DB_VALUE * value, DB_VALUE * value2)
Definition at line 4006 of file arithmetic.c.
References DB_IS_NULL, db_make_double(), db_make_null(), DB_TYPE_NULL, DB_VALUE_DOMAIN_TYPE, err, get_number_dbval_as_double(), and NO_ERROR.
Referenced by fetch_peek_arith(), and pt_evaluate_db_value_expr().
int db_atan_dbval (DB_VALUE * result, DB_VALUE * value)
Definition at line 3970 of file arithmetic.c.
References DB_IS_NULL, db_make_double(), db_make_null(), DB_TYPE_NULL, DB_VALUE_DOMAIN_TYPE, err, get_number_dbval_as_double(), and NO_ERROR.
Referenced by fetch_peek_arith(), and pt_evaluate_db_value_expr().
int db_bit_count_dbval (DB_VALUE * result, DB_VALUE * value)
Definition at line 4178 of file arithmetic.c.
References ARG_FILE_LINE, db_get_bigint(), db_get_double(), db_get_float(), db_get_int(), db_get_monetary(), db_get_short(), DB_IS_NULL, db_make_int(), db_make_null(), DB_TYPE_BIGINT, DB_TYPE_DOUBLE, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_MONETARY, DB_TYPE_NUMERIC, DB_TYPE_SHORT, DB_VALUE_DOMAIN_TYPE, DOMAIN_COMPATIBLE, ER_ERROR_SEVERITY, ER_FAILED, ER_QPROC_INVALID_DATATYPE, er_set(), i, NO_ERROR, NULL, tp_Double_domain, and tp_value_cast().
Referenced by fetch_peek_arith(), and pt_evaluate_db_value_expr().
int db_ceil_dbval (DB_VALUE * result, DB_VALUE * value)
Definition at line 254 of file arithmetic.c.
References ARG_FILE_LINE, assert, db_get_bigint(), db_get_double(), db_get_float(), db_get_int(), db_get_monetary(), db_get_short(), DB_IS_NULL, db_locate_numeric, db_make_bigint(), db_make_double(), db_make_float(), db_make_int(), db_make_monetary(), db_make_null(), db_make_numeric(), db_make_short(), DB_MAX_NUMERIC_PRECISION, DB_NUMERIC_BUF_SIZE, DB_TYPE_BIGINT, DB_TYPE_CHAR, DB_TYPE_DOUBLE, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_MONETARY, DB_TYPE_NCHAR, DB_TYPE_NULL, DB_TYPE_NUMERIC, DB_TYPE_SHORT, DB_TYPE_VARCHAR, DB_TYPE_VARNCHAR, DB_VALUE_DOMAIN_TYPE, DB_VALUE_PRECISION, DB_VALUE_SCALE, ER_ERROR_SEVERITY, ER_QPROC_INVALID_DATATYPE, er_set(), NO_ERROR, numeric_coerce_dec_str_to_num(), numeric_coerce_num_to_dec_str(), p, prm_get_bool_value(), PRM_ID_RETURN_NULL_ON_FUNCTION_ERRORS, strlen, and tp_value_str_auto_cast_to_number().
Referenced by fetch_peek_arith(), and pt_evaluate_db_value_expr().
int db_cos_dbval (DB_VALUE * result, DB_VALUE * value)
Definition at line 3737 of file arithmetic.c.
References DB_IS_NULL, db_make_double(), db_make_null(), DB_TYPE_NULL, DB_VALUE_DOMAIN_TYPE, err, get_number_dbval_as_double(), and NO_ERROR.
Referenced by fetch_peek_arith(), and pt_evaluate_db_value_expr().
int db_cot_dbval (DB_VALUE * result, DB_VALUE * value)
Definition at line 3833 of file arithmetic.c.
References DB_IS_NULL, db_make_double(), db_make_null(), DB_TYPE_NULL, DB_VALUE_DOMAIN_TYPE, err, get_number_dbval_as_double(), and NO_ERROR.
Referenced by fetch_peek_arith(), and pt_evaluate_db_value_expr().
int db_crc32_dbval (DB_VALUE * result, DB_VALUE * value)
Definition at line 5020 of file arithmetic.c.
References ARG_FILE_LINE, assert, crypt_crc32(), db_get_string(), db_get_string_size(), DB_IS_NULL, db_make_int(), DB_VALUE_DOMAIN_TYPE, er_clear(), er_errid(), ER_ERROR_SEVERITY, ER_QSTR_INVALID_DATA_TYPE, er_set(), error(), NO_ERROR, NULL, PRIM_SET_NULL(), prm_get_bool_value(), PRM_ID_RETURN_NULL_ON_FUNCTION_ERRORS, and QSTR_IS_ANY_CHAR.
Referenced by fetch_peek_arith(), and pt_evaluate_db_value_expr().
int db_degrees_dbval (DB_VALUE * result, DB_VALUE * value)
Definition at line 4054 of file arithmetic.c.
References DB_IS_NULL, db_make_double(), db_make_null(), DB_TYPE_NULL, DB_VALUE_DOMAIN_TYPE, err, get_number_dbval_as_double(), and NO_ERROR.
Referenced by fetch_peek_arith(), and pt_evaluate_db_value_expr().
int db_drandom_dbval (DB_VALUE * result)
Definition at line 3672 of file arithmetic.c.
References db_make_double(), and NO_ERROR.
int db_evaluate_json_array (DB_VALUE * result, DB_VALUE *const * arg, int const num_args)
Definition at line 5626 of file arithmetic.c.
References ASSERT_ERROR, db_json_add_element_to_array(), db_json_make_json_array(), db_make_json_from_doc_store_and_release(), db_make_null(), db_value_to_json_value(), i, and NO_ERROR.
Referenced by pt_evaluate_function_w_args(), and qdata_evaluate_function().
int db_evaluate_json_array_append (DB_VALUE * result, DB_VALUE *const * arg, int const num_args)
Definition at line 5964 of file arithmetic.c.
References ARG_FILE_LINE, assert, ASSERT_ERROR, DB_IS_NULL, db_json_array_append_func(), db_make_json_from_doc_store_and_release(), db_make_null(), db_value_to_json_doc(), db_value_to_json_path(), db_value_to_json_value(), ER_ERROR_SEVERITY, ER_FAILED, ER_OBJ_INVALID_ARGUMENTS, er_set(), F_JSON_ARRAY_APPEND, i, and NO_ERROR.
Referenced by pt_evaluate_function_w_args(), and qdata_evaluate_function().
int db_evaluate_json_array_insert (DB_VALUE * result, DB_VALUE *const * arg, int const num_args)
Definition at line 6032 of file arithmetic.c.
References ARG_FILE_LINE, assert, ASSERT_ERROR, DB_IS_NULL, db_json_array_insert_func(), db_make_json_from_doc_store_and_release(), db_make_null(), db_value_to_json_doc(), db_value_to_json_path(), db_value_to_json_value(), ER_ERROR_SEVERITY, ER_FAILED, ER_OBJ_INVALID_ARGUMENTS, er_set(), F_JSON_ARRAY_INSERT, i, and NO_ERROR.
Referenced by pt_evaluate_function_w_args(), and qdata_evaluate_function().
int db_evaluate_json_contains (DB_VALUE * result, DB_VALUE *const * arg, int const num_args)
Definition at line 5069 of file arithmetic.c.
References assert, ASSERT_ERROR, db_json_extract_document_from_path(), db_json_value_is_contained_in_doc(), db_make_int(), db_make_null(), db_value_to_json_doc(), db_value_to_json_path(), ER_FAILED, F_JSON_CONTAINS, is_any_arg_null(), NO_ERROR, and NULL.
Referenced by pt_evaluate_function_w_args(), and qdata_evaluate_function().
int db_evaluate_json_contains_path (DB_VALUE * result, DB_VALUE *const * arg, const int num_args)
Definition at line 6100 of file arithmetic.c.
References ASSERT_ERROR, db_json_contains_path(), db_make_int(), db_make_null(), db_value_to_json_doc(), db_value_to_json_path(), F_JSON_CONTAINS_PATH, i, is_any_arg_null(), is_str_find_all(), and NO_ERROR.
Referenced by pt_evaluate_function_w_args(), and qdata_evaluate_function().
int db_evaluate_json_depth (DB_VALUE * result, DB_VALUE *const * arg, int const num_args)
Definition at line 5269 of file arithmetic.c.
References assert, DB_IS_NULL, db_json_get_depth(), db_make_int(), db_make_null(), db_value_to_json_doc(), ER_FAILED, and NO_ERROR.
Referenced by pt_evaluate_function_w_args(), and qdata_evaluate_function().
int db_evaluate_json_extract (DB_VALUE * result, DB_VALUE *const * args, int num_args)
Definition at line 5511 of file arithmetic.c.
References assert, ASSERT_ERROR, db_json_extract_document_from_path(), db_json_get_type(), db_make_json_from_doc_store_and_release(), db_make_null(), db_value_to_json_doc(), db_value_to_json_path(), ER_FAILED, F_JSON_EXTRACT, is_any_arg_null(), and NO_ERROR.
Referenced by pt_evaluate_function_w_args(), and qdata_evaluate_function().
int db_evaluate_json_get_all_paths (DB_VALUE * result, DB_VALUE *const * arg, int const num_args)
Definition at line 6419 of file arithmetic.c.
References ARG_FILE_LINE, assert, ASSERT_ERROR, DB_IS_NULL, db_json_allocate_doc(), db_json_get_all_paths_func(), db_make_json(), db_make_null(), db_value_to_json_doc(), ER_ERROR_SEVERITY, ER_FAILED, ER_OBJ_INVALID_ARGUMENTS, er_set(), and NO_ERROR.
Referenced by pt_evaluate_function_w_args(), and qdata_evaluate_function().
int db_evaluate_json_insert (DB_VALUE * result, DB_VALUE *const * arg, int const num_args)
Definition at line 5653 of file arithmetic.c.
References ARG_FILE_LINE, assert, ASSERT_ERROR, DB_IS_NULL, db_json_insert_func(), db_make_json_from_doc_store_and_release(), db_make_null(), db_value_to_json_doc(), db_value_to_json_path(), db_value_to_json_value(), ER_ERROR_SEVERITY, ER_FAILED, ER_OBJ_INVALID_ARGUMENTS, er_set(), F_JSON_INSERT, i, and NO_ERROR.
Referenced by pt_evaluate_function_w_args(), and qdata_evaluate_function().
int db_evaluate_json_keys (DB_VALUE * result, DB_VALUE *const * arg, int const num_args)
Definition at line 5855 of file arithmetic.c.
References ARG_FILE_LINE, ASSERT_ERROR, assert_release, db_json_keys_func(), db_make_json_from_doc_store_and_release(), db_make_null(), db_value_to_json_doc(), db_value_to_json_path(), ER_ERROR_SEVERITY, ER_FAILED, ER_OBJ_INVALID_ARGUMENTS, er_set(), F_JSON_KEYS, is_any_arg_null(), and NO_ERROR.
Referenced by pt_evaluate_function_w_args(), and qdata_evaluate_function().
int db_evaluate_json_length (DB_VALUE * result, DB_VALUE *const * arg, int const num_args)
Definition at line 5212 of file arithmetic.c.
References assert, ASSERT_ERROR, db_json_extract_document_from_path(), db_json_get_length(), db_make_int(), db_make_null(), db_value_to_json_doc(), db_value_to_json_path(), ER_FAILED, F_JSON_LENGTH, is_any_arg_null(), NO_ERROR, and NULL.
Referenced by pt_evaluate_function_w_args(), and qdata_evaluate_function().
int db_evaluate_json_merge_patch (DB_VALUE * result, DB_VALUE *const * arg, const int num_args)
Definition at line 6215 of file arithmetic.c.
References db_json_merge_patch_func(), db_make_json_from_doc_store_and_release(), db_make_null(), db_value_to_json_doc(), i, is_any_arg_null(), and NO_ERROR.
Referenced by pt_evaluate_function_w_args(), and qdata_evaluate_function().
int db_evaluate_json_merge_preserve (DB_VALUE * result, DB_VALUE *const * arg, const int num_args)
Definition at line 6163 of file arithmetic.c.
References ASSERT_ERROR, db_json_merge_preserve_func(), db_make_json_from_doc_store_and_release(), db_make_null(), db_value_to_json_doc(), i, is_any_arg_null(), and NO_ERROR.
Referenced by pt_evaluate_function_w_args(), qdata_aggregate_accumulator_to_accumulator(), and qdata_evaluate_function().
int db_evaluate_json_object (DB_VALUE * result, DB_VALUE *const * arg, int const num_args)
Definition at line 5569 of file arithmetic.c.
References ARG_FILE_LINE, assert, ASSERT_ERROR, DB_IS_NULL, db_json_add_member_to_object(), db_json_make_json_object(), db_make_json_from_doc_store_and_release(), db_make_null(), db_value_to_json_key(), db_value_to_json_value(), ER_ERROR_SEVERITY, ER_FAILED, ER_JSON_OBJECT_NAME_IS_NULL, ER_OBJ_INVALID_ARGUMENTS, er_set(), i, and NO_ERROR.
Referenced by pt_evaluate_function_w_args(), and qdata_evaluate_function().
int db_evaluate_json_pretty (DB_VALUE * result, DB_VALUE *const * arg, int const num_args)
Definition at line 5345 of file arithmetic.c.
References assert, ASSERT_ERROR, DB_IS_NULL, db_json_pretty_func(), db_make_null(), db_make_string(), db_value_to_json_doc(), ER_FAILED, db_value::need_clear, NO_ERROR, and NULL.
Referenced by pt_evaluate_function_w_args(), and qdata_evaluate_function().
int db_evaluate_json_quote (DB_VALUE * result, DB_VALUE *const * arg, int const num_args)
Definition at line 5294 of file arithmetic.c.
References assert, db_string_quote(), and ER_FAILED.
Referenced by pt_evaluate_function_w_args(), and qdata_evaluate_function().
int db_evaluate_json_remove (DB_VALUE * result, DB_VALUE *const * arg, int const num_args)
Definition at line 5912 of file arithmetic.c.
References ARG_FILE_LINE, assert, ASSERT_ERROR, db_json_remove_func(), db_make_json_from_doc_store_and_release(), db_make_null(), db_value_to_json_doc(), db_value_to_json_path(), ER_ERROR_SEVERITY, ER_FAILED, ER_OBJ_INVALID_ARGUMENTS, er_set(), F_JSON_REMOVE, i, is_any_arg_null(), and NO_ERROR.
Referenced by pt_evaluate_function_w_args(), and qdata_evaluate_function().
int db_evaluate_json_replace (DB_VALUE * result, DB_VALUE *const * arg, int const num_args)
Definition at line 5721 of file arithmetic.c.
References ARG_FILE_LINE, ASSERT_ERROR, assert_release, DB_IS_NULL, db_json_replace_func(), db_make_json_from_doc_store_and_release(), db_make_null(), db_value_to_json_doc(), db_value_to_json_path(), db_value_to_json_value(), ER_ERROR_SEVERITY, ER_FAILED, ER_OBJ_INVALID_ARGUMENTS, er_set(), F_JSON_REPLACE, i, and NO_ERROR.
Referenced by pt_evaluate_function_w_args(), and qdata_evaluate_function().
int db_evaluate_json_search (DB_VALUE * result, DB_VALUE *const * args, const int num_args)
Definition at line 6268 of file arithmetic.c.
References ARG_FILE_LINE, ASSERT_ERROR, DB_IS_NULL, db_json_add_element_to_array(), db_json_get_json_from_str(), db_json_path_unquote_object_keys_external(), db_json_search_func(), db_make_json(), db_make_json_from_doc_store_and_release(), db_make_null(), db_make_string(), db_string_escape_str(), db_value_to_json_doc(), db_value_to_json_path(), ER_ERROR_SEVERITY, ER_FAILED, ER_OBJ_INVALID_ARGUMENTS, er_set(), F_JSON_SEARCH, i, is_str_find_all(), NO_ERROR, NULL, prm_get_bool_value(), and PRM_ID_NO_BACKSLASH_ESCAPES.
Referenced by pt_evaluate_function_w_args(), and qdata_evaluate_function().
int db_evaluate_json_set (DB_VALUE * result, DB_VALUE *const * arg, int const num_args)
Definition at line 5788 of file arithmetic.c.
References ARG_FILE_LINE, ASSERT_ERROR, assert_release, DB_IS_NULL, db_json_set_func(), db_make_json_from_doc_store_and_release(), db_make_null(), db_value_to_json_doc(), db_value_to_json_path(), db_value_to_json_value(), ER_ERROR_SEVERITY, ER_FAILED, ER_OBJ_INVALID_ARGUMENTS, er_set(), F_JSON_SET, i, and NO_ERROR.
Referenced by pt_evaluate_function_w_args(), and qdata_evaluate_function().
int db_evaluate_json_type_dbval (DB_VALUE * result, DB_VALUE *const * arg, int const num_args)
Definition at line 5145 of file arithmetic.c.
References assert, DB_IS_NULL, db_json_get_type_as_str(), db_make_null(), db_make_varchar(), db_value_to_json_doc(), ER_FAILED, LANG_COERCIBLE_CODESET, LANG_COERCIBLE_COLL, NO_ERROR, and strlen.
Referenced by pt_evaluate_function_w_args(), and qdata_evaluate_function().
int db_evaluate_json_unquote (DB_VALUE * result, DB_VALUE *const * arg, int const num_args)
Definition at line 5305 of file arithmetic.c.
References assert, ASSERT_ERROR, DB_IS_NULL, db_json_unquote(), db_make_null(), db_make_string(), db_value_to_json_doc(), ER_FAILED, db_value::need_clear, NO_ERROR, and NULL.
Referenced by pt_evaluate_function_w_args(), and qdata_evaluate_function().
int db_evaluate_json_valid (DB_VALUE * result, DB_VALUE *const * arg, int const num_args)
Definition at line 5178 of file arithmetic.c.
References assert, db_get_string(), db_get_string_size(), DB_IS_NULL, db_json_is_valid(), db_make_int(), db_make_null(), DB_TYPE_JSON, db_value_domain_type(), ER_FAILED, NO_ERROR, and TP_IS_CHAR_TYPE.
Referenced by pt_evaluate_function_w_args(), and qdata_evaluate_function().
int db_exp_dbval (DB_VALUE * result, DB_VALUE * value)
Definition at line 659 of file arithmetic.c.
References ARG_FILE_LINE, db_get_bigint(), db_get_double(), db_get_float(), db_get_int(), db_get_monetary(), db_get_short(), DB_IS_NULL, db_locate_numeric, db_make_double(), DB_TYPE_BIGINT, DB_TYPE_DOUBLE, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_MONETARY, DB_TYPE_NULL, DB_TYPE_NUMERIC, DB_TYPE_SHORT, DB_VALUE_DOMAIN_TYPE, DB_VALUE_SCALE, ER_ERROR_SEVERITY, ER_FAILED, ER_QPROC_INVALID_DATATYPE, ER_QPROC_OVERFLOW_EXP, er_set(), i, NO_ERROR, numeric_coerce_num_to_double(), and OR_CHECK_DOUBLE_OVERFLOW.
Referenced by fetch_peek_arith(), and pt_evaluate_db_value_expr().
int db_floor_dbval (DB_VALUE * result, DB_VALUE * value)
Definition at line 87 of file arithmetic.c.
References ARG_FILE_LINE, assert, db_get_bigint(), db_get_double(), db_get_float(), db_get_int(), db_get_monetary(), db_get_numeric(), db_get_short(), DB_IS_NULL, db_make_bigint(), db_make_double(), db_make_float(), db_make_int(), db_make_monetary(), db_make_null(), db_make_numeric(), db_make_short(), DB_MAX_NUMERIC_PRECISION, DB_NUMERIC_BUF_SIZE, DB_TYPE_BIGINT, DB_TYPE_CHAR, DB_TYPE_DOUBLE, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_MONETARY, DB_TYPE_NCHAR, DB_TYPE_NULL, DB_TYPE_NUMERIC, DB_TYPE_SHORT, DB_TYPE_VARCHAR, DB_TYPE_VARNCHAR, DB_VALUE_DOMAIN_TYPE, DB_VALUE_PRECISION, DB_VALUE_SCALE, ER_ERROR_SEVERITY, ER_QPROC_INVALID_DATATYPE, er_set(), NO_ERROR, numeric_coerce_dec_str_to_num(), numeric_coerce_num_to_dec_str(), p, prm_get_bool_value(), PRM_ID_RETURN_NULL_ON_FUNCTION_ERRORS, strlen, and tp_value_str_auto_cast_to_number().
Referenced by fetch_peek_arith(), and pt_evaluate_db_value_expr().
int db_least_or_greatest (DB_VALUE * arg1, DB_VALUE * arg2, DB_VALUE * result, bool least)
Definition at line 6454 of file arithmetic.c.
References assert_release, DB_EQ, DB_GT, DB_IS_NULL, DB_LT, db_make_null(), DB_UNK, ER_FAILED, NO_ERROR, pr_clone_value(), and tp_value_compare_with_error().
Referenced by fetch_peek_arith(), and pt_evaluate_db_value_expr().
int db_log_dbval (DB_VALUE * result, DB_VALUE * value1, DB_VALUE * value2)
Definition at line 2603 of file arithmetic.c.
References ARG_FILE_LINE, d1, db_get_bigint(), db_get_double(), db_get_float(), db_get_int(), db_get_monetary(), db_get_short(), DB_IS_NULL, db_locate_numeric, db_make_double(), DB_TYPE_BIGINT, DB_TYPE_DOUBLE, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_MONETARY, DB_TYPE_NUMERIC, DB_TYPE_SHORT, DB_VALUE_DOMAIN_TYPE, DB_VALUE_SCALE, ER_ERROR_SEVERITY, ER_FAILED, ER_QPROC_FUNCTION_ARG_ERROR, ER_QPROC_INVALID_DATATYPE, er_set(), NO_ERROR, and numeric_coerce_num_to_double().
Referenced by fetch_peek_arith(), and pt_evaluate_db_value_expr().
int db_log_generic_dbval (DB_VALUE * result, DB_VALUE * value, long b)
Definition at line 4118 of file arithmetic.c.
References ARG_FILE_LINE, assert, DB_IS_NULL, db_make_double(), db_make_null(), DB_TYPE_NULL, DB_VALUE_DOMAIN_TYPE, ER_ERROR_SEVERITY, ER_QPROC_FUNCTION_ARG_ERROR, er_set(), err, get_number_dbval_as_double(), and NO_ERROR.
Referenced by fetch_peek_arith(), and pt_evaluate_db_value_expr().
static int db_mod_bigint (DB_VALUE * value, DB_VALUE * value1, DB_VALUE * value2) static
Definition at line 1205 of file arithmetic.c.
References ARG_FILE_LINE, assert, db_get_bigint(), db_get_double(), db_get_float(), db_get_int(), db_get_monetary(), db_get_short(), db_locate_numeric, db_make_bigint(), db_make_double(), db_make_float(), db_make_monetary(), db_make_null(), db_make_numeric(), DB_NUMERIC_BUF_SIZE, DB_TYPE_BIGINT, DB_TYPE_CHAR, DB_TYPE_DOUBLE, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_MONETARY, DB_TYPE_NCHAR, DB_TYPE_NUMERIC, DB_TYPE_SHORT, DB_TYPE_VARCHAR, DB_TYPE_VARNCHAR, DB_VALUE_DOMAIN_TYPE, DB_VALUE_SCALE, ER_ERROR_SEVERITY, ER_QPROC_INVALID_DATATYPE, er_set(), NO_ERROR, NULL, numeric_coerce_num_to_double(), numeric_db_value_coerce_to_num(), numeric_internal_double_to_num(), p, prm_get_bool_value(), PRM_ID_RETURN_NULL_ON_FUNCTION_ERRORS, and tp_value_str_auto_cast_to_number().
Referenced by db_mod_dbval().
int db_mod_dbval (DB_VALUE * result, DB_VALUE * value1, DB_VALUE * value2)
Definition at line 1928 of file arithmetic.c.
References ARG_FILE_LINE, DB_IS_NULL, db_mod_bigint(), db_mod_double(), db_mod_float(), db_mod_int(), db_mod_monetary(), db_mod_numeric(), db_mod_short(), db_mod_string(), DB_TYPE_BIGINT, DB_TYPE_CHAR, DB_TYPE_DOUBLE, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_MONETARY, DB_TYPE_NCHAR, DB_TYPE_NUMERIC, DB_TYPE_SHORT, DB_TYPE_VARCHAR, DB_TYPE_VARNCHAR, DB_VALUE_DOMAIN_TYPE, ER_ERROR_SEVERITY, ER_QPROC_INVALID_DATATYPE, er_set(), NO_ERROR, prm_get_bool_value(), and PRM_ID_RETURN_NULL_ON_FUNCTION_ERRORS.
Referenced by fetch_peek_arith(), and pt_evaluate_db_value_expr().
static int db_mod_double (DB_VALUE * value, DB_VALUE * value1, DB_VALUE * value2) static
Definition at line 1498 of file arithmetic.c.
References ARG_FILE_LINE, assert, d1, db_get_bigint(), db_get_double(), db_get_float(), db_get_int(), db_get_monetary(), db_get_short(), db_locate_numeric, db_make_double(), db_make_monetary(), db_make_null(), DB_TYPE_BIGINT, DB_TYPE_CHAR, DB_TYPE_DOUBLE, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_MONETARY, DB_TYPE_NCHAR, DB_TYPE_NUMERIC, DB_TYPE_SHORT, DB_TYPE_VARCHAR, DB_TYPE_VARNCHAR, DB_VALUE_DOMAIN_TYPE, DB_VALUE_SCALE, ER_ERROR_SEVERITY, ER_QPROC_INVALID_DATATYPE, er_set(), NO_ERROR, NULL, numeric_coerce_num_to_double(), prm_get_bool_value(), PRM_ID_RETURN_NULL_ON_FUNCTION_ERRORS, and tp_value_str_auto_cast_to_number().
Referenced by db_mod_dbval(), and db_mod_string().
static int db_mod_float (DB_VALUE * value, DB_VALUE * value1, DB_VALUE * value2) static
Definition at line 1354 of file arithmetic.c.
References ARG_FILE_LINE, assert, db_get_bigint(), db_get_double(), db_get_float(), db_get_int(), db_get_monetary(), db_get_short(), db_locate_numeric, db_make_double(), db_make_float(), db_make_monetary(), db_make_null(), DB_TYPE_BIGINT, DB_TYPE_CHAR, DB_TYPE_DOUBLE, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_MONETARY, DB_TYPE_NCHAR, DB_TYPE_NUMERIC, DB_TYPE_SHORT, DB_TYPE_VARCHAR, DB_TYPE_VARNCHAR, DB_VALUE_DOMAIN_TYPE, DB_VALUE_SCALE, ER_ERROR_SEVERITY, ER_QPROC_INVALID_DATATYPE, er_set(), NO_ERROR, NULL, numeric_coerce_num_to_double(), prm_get_bool_value(), PRM_ID_RETURN_NULL_ON_FUNCTION_ERRORS, and tp_value_str_auto_cast_to_number().
Referenced by db_mod_dbval().
static int db_mod_int (DB_VALUE * value, DB_VALUE * value1, DB_VALUE * value2) static
Definition at line 1056 of file arithmetic.c.
References ARG_FILE_LINE, assert, db_get_bigint(), db_get_double(), db_get_float(), db_get_int(), db_get_monetary(), db_get_short(), db_locate_numeric, db_make_bigint(), db_make_double(), db_make_float(), db_make_int(), db_make_monetary(), db_make_null(), db_make_numeric(), DB_NUMERIC_BUF_SIZE, DB_TYPE_BIGINT, DB_TYPE_CHAR, DB_TYPE_DOUBLE, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_MONETARY, DB_TYPE_NCHAR, DB_TYPE_NUMERIC, DB_TYPE_SHORT, DB_TYPE_VARCHAR, DB_TYPE_VARNCHAR, DB_VALUE_DOMAIN_TYPE, DB_VALUE_SCALE, ER_ERROR_SEVERITY, ER_QPROC_INVALID_DATATYPE, er_set(), NO_ERROR, NULL, numeric_coerce_num_to_double(), numeric_db_value_coerce_to_num(), numeric_internal_double_to_num(), p, prm_get_bool_value(), PRM_ID_RETURN_NULL_ON_FUNCTION_ERRORS, and tp_value_str_auto_cast_to_number().
Referenced by db_mod_dbval().
static int db_mod_monetary (DB_VALUE * value, DB_VALUE * value1, DB_VALUE * value2) static
Definition at line 1835 of file arithmetic.c.
References ARG_FILE_LINE, assert, d1, db_get_bigint(), db_get_double(), db_get_float(), db_get_int(), db_get_monetary(), db_get_short(), db_locate_numeric, db_make_monetary(), db_make_null(), DB_TYPE_BIGINT, DB_TYPE_CHAR, DB_TYPE_DOUBLE, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_MONETARY, DB_TYPE_NCHAR, DB_TYPE_NUMERIC, DB_TYPE_SHORT, DB_TYPE_VARCHAR, DB_TYPE_VARNCHAR, DB_VALUE_DOMAIN_TYPE, DB_VALUE_SCALE, ER_ERROR_SEVERITY, ER_QPROC_INVALID_DATATYPE, er_set(), NO_ERROR, NULL, numeric_coerce_num_to_double(), prm_get_bool_value(), PRM_ID_RETURN_NULL_ON_FUNCTION_ERRORS, and tp_value_str_auto_cast_to_number().
Referenced by db_mod_dbval().
static int db_mod_numeric (DB_VALUE * value, DB_VALUE * value1, DB_VALUE * value2) static
Definition at line 1678 of file arithmetic.c.
References ARG_FILE_LINE, assert, d1, db_get_bigint(), db_get_double(), db_get_float(), db_get_int(), db_get_monetary(), db_get_short(), db_locate_numeric, db_make_double(), db_make_monetary(), db_make_null(), db_make_numeric(), DB_NUMERIC_BUF_SIZE, DB_TYPE_BIGINT, DB_TYPE_CHAR, DB_TYPE_DOUBLE, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_MONETARY, DB_TYPE_NCHAR, DB_TYPE_NUMERIC, DB_TYPE_SHORT, DB_TYPE_VARCHAR, DB_TYPE_VARNCHAR, DB_VALUE_DOMAIN_TYPE, DB_VALUE_SCALE, ER_ERROR_SEVERITY, ER_QPROC_INVALID_DATATYPE, er_set(), NO_ERROR, NULL, numeric_coerce_num_to_double(), numeric_db_value_coerce_to_num(), numeric_internal_double_to_num(), p, prm_get_bool_value(), PRM_ID_RETURN_NULL_ON_FUNCTION_ERRORS, and tp_value_str_auto_cast_to_number().
Referenced by db_mod_dbval().
static int db_mod_short (DB_VALUE * value, DB_VALUE * value1, DB_VALUE * value2) static
Definition at line 907 of file arithmetic.c.
References ARG_FILE_LINE, assert, db_get_bigint(), db_get_double(), db_get_float(), db_get_int(), db_get_monetary(), db_get_short(), db_locate_numeric, db_make_bigint(), db_make_double(), db_make_float(), db_make_int(), db_make_monetary(), db_make_null(), db_make_numeric(), db_make_short(), DB_NUMERIC_BUF_SIZE, DB_TYPE_BIGINT, DB_TYPE_CHAR, DB_TYPE_DOUBLE, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_MONETARY, DB_TYPE_NCHAR, DB_TYPE_NUMERIC, DB_TYPE_SHORT, DB_TYPE_VARCHAR, DB_TYPE_VARNCHAR, DB_VALUE_DOMAIN_TYPE, DB_VALUE_SCALE, ER_ERROR_SEVERITY, ER_QPROC_INVALID_DATATYPE, er_set(), NO_ERROR, NULL, numeric_coerce_num_to_double(), numeric_db_value_coerce_to_num(), numeric_internal_double_to_num(), p, prm_get_bool_value(), PRM_ID_RETURN_NULL_ON_FUNCTION_ERRORS, and tp_value_str_auto_cast_to_number().
Referenced by db_mod_dbval().
static int db_mod_string (DB_VALUE * value, DB_VALUE * value1, DB_VALUE * value2) static
Definition at line 1641 of file arithmetic.c.
References assert, db_make_null(), db_mod_double(), DB_TYPE_DOUBLE, DB_VALUE_DOMAIN_TYPE, NO_ERROR, NULL, prm_get_bool_value(), PRM_ID_RETURN_NULL_ON_FUNCTION_ERRORS, TP_IS_CHAR_TYPE, and tp_value_str_auto_cast_to_number().
Referenced by db_mod_dbval().
int db_power_dbval (DB_VALUE * result, DB_VALUE * value1, DB_VALUE * value2)
Definition at line 836 of file arithmetic.c.
References ARG_FILE_LINE, COMPAT_MYSQL, d1, DB_IS_NULL, db_make_double(), db_make_null(), ER_ERROR_SEVERITY, ER_FAILED, ER_QPROC_OVERFLOW_POWER, ER_QPROC_POWER_ERROR, er_set(), error(), get_number_dbval_as_double(), NO_ERROR, OR_CHECK_DOUBLE_OVERFLOW, prm_get_integer_value(), and PRM_ID_COMPAT_MODE.
Referenced by fetch_peek_arith(), and pt_evaluate_db_value_expr().
int db_radians_dbval (DB_VALUE * result, DB_VALUE * value)
Definition at line 4086 of file arithmetic.c.
References DB_IS_NULL, db_make_double(), db_make_null(), DB_TYPE_NULL, DB_VALUE_DOMAIN_TYPE, err, get_number_dbval_as_double(), and NO_ERROR.
Referenced by fetch_peek_arith(), and pt_evaluate_db_value_expr().
int db_random_dbval (DB_VALUE * result)
Definition at line 3659 of file arithmetic.c.
References db_make_int(), and NO_ERROR.
int db_round_dbval (DB_VALUE * result, DB_VALUE * value1, DB_VALUE * value2)
Definition at line 2315 of file arithmetic.c.
References ARG_FILE_LINE, assert, d1, DB_BIGINT_MAX, DB_BIGINT_MIN, db_get_bigint(), db_get_double(), db_get_float(), db_get_int(), db_get_monetary(), db_get_short(), DB_GET_STRING_SAFE, DB_IS_NULL, db_locate_numeric, db_make_bigint(), db_make_double(), db_make_float(), db_make_int(), db_make_monetary(), db_make_null(), db_make_numeric(), db_make_short(), db_make_string(), DB_MAX_NUMERIC_PRECISION, DB_NUMERIC_BUF_SIZE, DB_TYPE_BIGINT, DB_TYPE_CHAR, DB_TYPE_DATE, DB_TYPE_DATETIME, DB_TYPE_DATETIMELTZ, DB_TYPE_DATETIMETZ, DB_TYPE_DOUBLE, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_MONETARY, DB_TYPE_NCHAR, DB_TYPE_NUMERIC, DB_TYPE_SHORT, DB_TYPE_TIMESTAMP, DB_TYPE_TIMESTAMPLTZ, DB_TYPE_TIMESTAMPTZ, DB_TYPE_UNKNOWN, DB_TYPE_VARCHAR, DB_TYPE_VARNCHAR, DB_VALUE_DOMAIN_TYPE, DB_VALUE_PRECISION, DB_VALUE_SCALE, DOMAIN_COMPATIBLE, er_clear(), er_errid(), ER_ERROR_SEVERITY, ER_IT_DATA_OVERFLOW, ER_QPROC_INVALID_DATATYPE, er_set(), NO_ERROR, NULL, numeric_coerce_dec_str_to_num(), numeric_coerce_num_to_dec_str(), p, pr_type_name(), prm_get_bool_value(), PRM_ID_RETURN_NULL_ON_FUNCTION_ERRORS, QSTR_IS_ANY_CHAR, round_date(), round_double(), strlen, tp_domain_resolve_default(), TP_DOMAIN_TYPE, TP_IS_NUMERIC_TYPE, tp_value_coerce(), and tp_value_str_auto_cast_to_number().
Referenced by fetch_peek_arith(), and pt_evaluate_db_value_expr().
int db_sign_dbval (DB_VALUE * result, DB_VALUE * value)
Definition at line 429 of file arithmetic.c.
References db_get_bigint(), db_get_double(), db_get_float(), db_get_int(), db_get_monetary(), db_get_short(), DB_IS_NULL, db_locate_numeric, db_make_int(), DB_TYPE_BIGINT, DB_TYPE_DOUBLE, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_MONETARY, DB_TYPE_NULL, DB_TYPE_NUMERIC, DB_TYPE_SHORT, DB_VALUE_DOMAIN_TYPE, DB_VALUE_SCALE, NO_ERROR, and numeric_coerce_num_to_double().
Referenced by fetch_peek_arith(), and pt_evaluate_db_value_expr().
int db_sin_dbval (DB_VALUE * result, DB_VALUE * value)
Definition at line 3769 of file arithmetic.c.
References DB_IS_NULL, db_make_double(), db_make_null(), DB_TYPE_NULL, DB_VALUE_DOMAIN_TYPE, err, get_number_dbval_as_double(), and NO_ERROR.
Referenced by fetch_peek_arith(), and pt_evaluate_db_value_expr().
int db_sleep (DB_VALUE * result, DB_VALUE * value)
Definition at line 4976 of file arithmetic.c.
References ARG_FILE_LINE, assert, db_get_double(), DB_IS_NULL, db_make_int(), db_make_null(), DB_TYPE_DOUBLE, DB_TYPE_NULL, DB_VALUE_DOMAIN_TYPE, ER_ERROR_SEVERITY, ER_OBJ_INVALID_ARGUMENTS, er_set(), error(), msleep(), NO_ERROR, and NULL.
Referenced by fetch_peek_arith(), and pt_evaluate_db_value_expr().
int db_sqrt_dbval (DB_VALUE * result, DB_VALUE * value)
Definition at line 731 of file arithmetic.c.
References ARG_FILE_LINE, COMPAT_MYSQL, db_get_bigint(), db_get_double(), db_get_float(), db_get_int(), db_get_monetary(), db_get_short(), DB_IS_NULL, db_locate_numeric, db_make_double(), db_make_null(), DB_TYPE_BIGINT, DB_TYPE_DOUBLE, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_MONETARY, DB_TYPE_NULL, DB_TYPE_NUMERIC, DB_TYPE_SHORT, DB_VALUE_DOMAIN_TYPE, DB_VALUE_SCALE, ER_ERROR_SEVERITY, ER_FAILED, ER_QPROC_FUNCTION_ARG_ERROR, ER_QPROC_INVALID_DATATYPE, er_set(), i, NO_ERROR, numeric_coerce_num_to_double(), prm_get_integer_value(), and PRM_ID_COMPAT_MODE.
Referenced by fetch_peek_arith(), and pt_evaluate_db_value_expr().
int db_tan_dbval (DB_VALUE * result, DB_VALUE * value)
Definition at line 3801 of file arithmetic.c.
References DB_IS_NULL, db_make_double(), db_make_null(), DB_TYPE_NULL, DB_VALUE_DOMAIN_TYPE, err, get_number_dbval_as_double(), and NO_ERROR.
Referenced by fetch_peek_arith(), and pt_evaluate_db_value_expr().
int db_trunc_dbval (DB_VALUE * result, DB_VALUE * value1, DB_VALUE * value2)
Definition at line 3311 of file arithmetic.c.
References ARG_FILE_LINE, assert, d1, db_datetime::date, db_datetimetz::datetime, db_get_bigint(), db_get_date(), db_get_datetime(), db_get_datetimetz(), db_get_double(), db_get_float(), db_get_int(), db_get_monetary(), db_get_short(), db_get_string(), db_get_timestamp(), db_get_timestamptz(), DB_IS_NULL, db_locate_numeric, db_make_bigint(), db_make_double(), db_make_float(), db_make_int(), db_make_monetary(), db_make_null(), db_make_numeric(), db_make_short(), db_make_string(), DB_MAX_NUMERIC_PRECISION, DB_NUMERIC_BUF_SIZE, db_timestamp_decode_ses(), db_timestamp_decode_w_tz_id(), DB_TYPE_BIGINT, DB_TYPE_CHAR, DB_TYPE_DATE, DB_TYPE_DATETIME, DB_TYPE_DATETIMELTZ, DB_TYPE_DATETIMETZ, DB_TYPE_DOUBLE, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_MONETARY, DB_TYPE_NUMERIC, DB_TYPE_SHORT, DB_TYPE_TIMESTAMP, DB_TYPE_TIMESTAMPLTZ, DB_TYPE_TIMESTAMPTZ, DB_TYPE_UNKNOWN, DB_VALUE_DOMAIN_TYPE, DB_VALUE_PRECISION, db_value_put_encoded_date(), DB_VALUE_SCALE, DOMAIN_COMPATIBLE, er_clear(), ER_ERROR_SEVERITY, ER_QPROC_INVALID_DATATYPE, ER_QSTR_INVALID_FORMAT, er_set(), NO_ERROR, NULL, numeric_coerce_dec_str_to_num(), numeric_coerce_num_to_dec_str(), p, pr_clear_value(), prm_get_bool_value(), PRM_ID_RETURN_NULL_ON_FUNCTION_ERRORS, QSTR_IS_ANY_CHAR, strlen, db_timestamptz::timestamp, tp_domain_resolve_default(), TP_IS_DATE_TYPE, tp_value_coerce(), truncate_bigint(), truncate_date(), truncate_double(), tz_datetimeltz_to_local(), db_timestamptz::tz_id, db_datetimetz::tz_id, and tz_utc_datetimetz_to_local().
Referenced by fetch_peek_arith(), and pt_evaluate_db_value_expr().
int db_typeof_dbval (DB_VALUE * result, DB_VALUE * value)
Definition at line 4302 of file arithmetic.c.
References ARG_FILE_LINE, db_domain_info::char_info, db_make_null(), db_make_string(), db_private_alloc, DB_TYPE_BIT, DB_TYPE_CHAR, DB_TYPE_NCHAR, DB_TYPE_NUMERIC, DB_TYPE_VARBIT, DB_TYPE_VARCHAR, DB_TYPE_VARNCHAR, DB_VALUE_TYPE, db_value::domain, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), db_domain_info::char_info::length, db_value::need_clear, NO_ERROR, NULL, db_domain_info::numeric_info, pr_type_name(), db_domain_info::numeric_info::precision, and db_domain_info::numeric_info::scale.
Referenced by fetch_peek_arith(), and pt_evaluate_db_value_expr().
int db_width_bucket (DB_VALUE * result, const DB_VALUE * value1, const DB_VALUE * value2, const DB_VALUE * value3, const DB_VALUE * value4)
Definition at line 4598 of file arithmetic.c.
References assert, d1, db_datetime::date, db_datetimetz::datetime, DB_BIGINT_PRECISION, DB_FLOAT_DECIMAL_PRECISION, db_get_date(), db_get_datetime(), db_get_datetimetz(), db_get_double(), db_get_time(), db_get_timestamp(), db_get_timestamptz(), DB_INT32_MAX, DB_INTEGER_PRECISION, db_make_int(), db_make_null(), DB_TYPE_BIGINT, DB_TYPE_CHAR, DB_TYPE_DATE, DB_TYPE_DATETIME, DB_TYPE_DATETIMELTZ, DB_TYPE_DATETIMETZ, DB_TYPE_DOUBLE, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_MONETARY, DB_TYPE_NCHAR, DB_TYPE_NULL, DB_TYPE_NUMERIC, DB_TYPE_SHORT, DB_TYPE_TIME, DB_TYPE_TIMESTAMP, DB_TYPE_TIMESTAMPLTZ, DB_TYPE_TIMESTAMPTZ, DB_TYPE_UNKNOWN, DB_TYPE_VARCHAR, DB_TYPE_VARNCHAR, DB_VALUE_DOMAIN_TYPE, DB_VALUE_TYPE, db_width_bucket_calculate_numeric(), DOMAIN_COMPATIBLE, er_clear(), er_errid(), ER_IT_DATA_OVERFLOW, ER_PROC_WIDTH_BUCKET_COUNT, ER_QPROC_INVALID_DATATYPE, ER_QPROC_OVERFLOW_ADDITION, ER_QPROC_OVERFLOW_DIVISION, ER_QPROC_OVERFLOW_SUBTRACTION, get_number_dbval_as_double(), MAX_DOMAIN_NAME_SIZE, MILLISECONDS_OF_ONE_DAY, NO_ERROR, NULL, OR_CHECK_DOUBLE_OVERFLOW, OR_CHECK_INT_OVERFLOW, tp_domain::precision, RETURN_ERROR, RETURN_ERROR_WITH_ARG, tp_domain::scale, db_datetime::time, db_timestamptz::timestamp, tp_domain_free(), tp_domain_name(), tp_domain_new(), tp_domain_resolve_default(), and tp_value_coerce().
Referenced by fetch_peek_arith(), and pt_evaluate_db_value_expr().
static int db_width_bucket_calculate_numeric (double * result, const DB_VALUE * value1, const DB_VALUE * value2, const DB_VALUE * value3, const DB_VALUE * value4) static
Definition at line 4426 of file arithmetic.c.
References assert, db_get_int(), db_get_numeric(), db_make_null(), DB_TYPE_NUMERIC, DB_VALUE_SCALE, DB_VALUE_TYPE, ER_IT_DATA_OVERFLOW, ER_QPROC_OVERFLOW_ADDITION, NO_ERROR, NULL, numeric_coerce_num_to_double(), numeric_db_value_compare(), numeric_db_value_div(), numeric_db_value_sub(), and OR_CHECK_DOUBLE_OVERFLOW.
Referenced by db_width_bucket().
static int get_number_dbval_as_double (double * d, const DB_VALUE * value) static
Definition at line 3686 of file arithmetic.c.
References ARG_FILE_LINE, db_get_bigint(), db_get_double(), db_get_float(), db_get_int(), db_get_monetary(), db_get_short(), db_locate_numeric, DB_TYPE_BIGINT, DB_TYPE_DOUBLE, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_MONETARY, DB_TYPE_NUMERIC, DB_TYPE_SHORT, DB_VALUE_DOMAIN_TYPE, DB_VALUE_SCALE, ER_ERROR_SEVERITY, ER_QPROC_INVALID_DATATYPE, er_set(), i, NO_ERROR, and numeric_coerce_num_to_double().
Referenced by db_acos_dbval(), db_asin_dbval(), db_atan2_dbval(), db_atan_dbval(), db_cos_dbval(), db_cot_dbval(), db_degrees_dbval(), db_log_generic_dbval(), db_power_dbval(), db_radians_dbval(), db_sin_dbval(), db_tan_dbval(), and db_width_bucket().
static int get_number_dbval_as_long_double (long double * ld, const DB_VALUE * value) static
Definition at line 4360 of file arithmetic.c.
References ARG_FILE_LINE, assert, db_get_bigint(), db_get_double(), db_get_float(), db_get_int(), db_get_monetary(), db_get_short(), db_locate_numeric, DB_MAX_NUMERIC_PRECISION, DB_TYPE_BIGINT, DB_TYPE_DOUBLE, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_MONETARY, DB_TYPE_NUMERIC, DB_TYPE_SHORT, DB_VALUE_DOMAIN_TYPE, DB_VALUE_SCALE, ER_ERROR_SEVERITY, ER_QPROC_INVALID_DATATYPE, er_set(), i, NO_ERROR, NULL, and numeric_coerce_num_to_dec_str().
static bool is_any_arg_null (DB_VALUE *const * args, int num_args) static
Definition at line 6539 of file arithmetic.c.
References DB_IS_NULL, and i.
Referenced by db_evaluate_json_contains(), db_evaluate_json_contains_path(), db_evaluate_json_extract(), db_evaluate_json_keys(), db_evaluate_json_length(), db_evaluate_json_merge_patch(), db_evaluate_json_merge_preserve(), and db_evaluate_json_remove().
static int is_str_find_all (DB_VALUE * val, bool & find_all) static
Definition at line 6503 of file arithmetic.c.
References ARG_FILE_LINE, db_get_string(), db_get_string_size(), DB_IS_NULL, DB_IS_STRING, ER_ERROR_SEVERITY, ER_INVALID_ONE_ALL_ARGUMENT, er_set(), and NO_ERROR.
Referenced by db_evaluate_json_contains_path(), and db_evaluate_json_search().
static int move_n_days (int * monthp, int * dayp, int * yearp, const int interval) static
Definition at line 2022 of file arithmetic.c.
References db_date_decode(), db_date_encode(), error(), and NO_ERROR.
Referenced by round_date().
static int round_date (DB_VALUE * result, DB_VALUE * value1, DB_VALUE * value2) static
Definition at line 2049 of file arithmetic.c.
References ARG_FILE_LINE, db_datetimetz::datetime, day_of_week(), db_date_decode(), db_datetime_decode(), db_get_date(), db_get_date_format(), db_get_datetime(), db_get_datetimetz(), db_get_timestamp(), db_get_timestamptz(), db_make_date(), db_make_null(), db_time_decode(), db_timestamp_decode_ses(), db_timestamp_decode_w_tz_id(), DB_TYPE_DATE, DB_TYPE_DATETIME, DB_TYPE_DATETIMELTZ, DB_TYPE_DATETIMETZ, DB_TYPE_TIMESTAMP, DB_TYPE_TIMESTAMPLTZ, DB_TYPE_TIMESTAMPTZ, DB_VALUE_DOMAIN_TYPE, DT_CC, DT_D, DT_DAY, DT_DD, DT_DY, DT_H, DT_HH, DT_HH12, DT_HH24, DT_MI, DT_MM, DT_MON, DT_MONTH, DT_MS, DT_Q, DT_SS, DT_YY, DT_YYYY, er_clear(), ER_ERROR_SEVERITY, ER_IT_DATA_OVERFLOW, ER_QPROC_INVALID_DATATYPE, ER_QSTR_INVALID_FORMAT, er_set(), error(), julian_encode(), move_n_days(), pr_type::name, NO_ERROR, prm_get_bool_value(), PRM_ID_RETURN_NULL_ON_FUNCTION_ERRORS, db_timestamptz::timestamp, tp_Date_domain, tp_domain::type, tz_datetimeltz_to_local(), db_timestamptz::tz_id, db_datetimetz::tz_id, and tz_utc_datetimetz_to_local().
Referenced by db_round_dbval().
static double round_double (double num, double integer) static
Definition at line 1987 of file arithmetic.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_IT_DATA_OVERFLOW, er_set(), FINITE, pr_type::name, tp_Double_domain, and tp_domain::type.
Referenced by db_round_dbval().
static DB_BIGINT truncate_bigint (DB_BIGINT num, DB_BIGINT integer) static
Definition at line 3183 of file arithmetic.c.
Referenced by db_trunc_dbval().
static int truncate_date (DB_DATE * date, const DB_VALUE * format_str) static
Definition at line 3203 of file arithmetic.c.
References ARG_FILE_LINE, assert, day_of_week(), db_date_decode(), db_date_encode(), db_get_date_format(), DT_CC, DT_D, DT_DAY, DT_DD, DT_DY, DT_H, DT_HH, DT_HH12, DT_HH24, DT_INVALID, DT_MI, DT_MM, DT_MON, DT_MONTH, DT_MS, DT_Q, DT_SS, DT_YY, DT_YYYY, ER_ERROR_SEVERITY, ER_QSTR_INVALID_FORMAT, er_set(), error(), NO_ERROR, and NULL.
Referenced by db_trunc_dbval().
static double truncate_double (double num, double integer) static
Definition at line 3140 of file arithmetic.c.
Referenced by db_trunc_dbval().