CUBRID Engine: src/base/base64.h File Reference
base64.h File Reference
Enumerations
enum { BASE64_EMPTY_INPUT = 1, BASE64_INVALID_INPUT = 2 }
Functions
int base64_encode (const unsigned char *src, int src_len, unsigned char **dest, int *dest_len)
int base64_decode (const unsigned char *src, int src_len, unsigned char **dest, int *dest_len)
Enumeration Type Documentation
anonymous enum
Enumerator
BASE64_EMPTY_INPUT
BASE64_INVALID_INPUT
Definition at line 29 of file base64.h.
Function Documentation
int base64_decode (const unsigned char * src, int src_len, unsigned char ** dest, int * dest_len)
Definition at line 387 of file base64.c.
References assert, base64_decode_chunk(), BASE64_EMPTY_INPUT, base64_partition_into_chunk(), base64_remove_space(), db_private_alloc, db_private_free_and_init, ER_OUT_OF_VIRTUAL_MEMORY, free_base64_chunk(), NO_ERROR, and NULL.
Referenced by db_string_from_base64().
int base64_encode (const unsigned char * src, int src_len, unsigned char ** dest, int * dest_len)
Definition at line 502 of file base64.c.
References assert, base64_encode_local(), db_private_alloc, db_private_free_and_init, ER_OUT_OF_VIRTUAL_MEMORY, get_base64_encode_len(), NO_ERROR, and NULL.
Referenced by db_string_to_base64().