CUBRID Engine: src/broker/broker_shm.h File Reference
broker_shm.h File Reference
#include <sys/types.h>
#include <semaphore.h>
#include "porting.h"
#include "broker_env_def.h"
#include "broker_config.h"
#include "broker_max_heap.h"
#include "cas_protocol.h"
Classes
struct ip_info
struct access_list
struct t_shard_conn_info
struct t_shard_user
struct t_shm_shard_user
struct t_shard_key_range
struct t_shard_key
struct t_shm_shard_key
struct t_shard_conn
struct t_shm_shard_conn
struct t_appl_server_info
struct t_client_info
struct t_shard_info
struct t_shm_shard_conn_stat
struct t_shm_shard_key_range_stat
struct t_shm_shard_key_stat
struct t_proxy_info
struct t_shm_proxy
struct t_db_server
struct t_shm_appl_server
struct t_shm_broker
Macros
#define STATE_KEEP_TRUE 1
#define STATE_KEEP_FALSE 0
#define UTS_STATUS_BUSY 1
#define UTS_STATUS_IDLE 0
#define UTS_STATUS_RESTART 2
#define UTS_STATUS_START 3
#define UTS_STATUS_CON_WAIT 5
#define UTS_STATUS_STOP 6
#define PROXY_STATUS_BUSY 1
#define PROXY_STATUS_RESTART 2
#define PROXY_STATUS_START 3
#define MAX_NUM_UTS_ADMIN 10
#define DEFAULT_SHM_KEY 0x3f5d1c0a
#define SHM_APPL_SERVER 0
#define SHM_BROKER 1
#define SHM_PROXY 2
#define SHM_MUTEX_BROKER 0
#define SHM_MUTEX_ADMIN 1
#define CON_STATUS_LOCK_BROKER 0
#define CON_STATUS_LOCK_CAS 1
#define CON_STATUS_LOCK_INIT(AS_INFO) uw_sem_init (&((AS_INFO)->con_status_sem));
#define CON_STATUS_LOCK_DESTROY(AS_INFO) uw_sem_destroy (&((AS_INFO)->con_status_sem));
#define CON_STATUS_LOCK(AS_INFO, LOCK_OWNER) uw_sem_wait (&(AS_INFO)->con_status_sem);
#define CON_STATUS_UNLOCK(AS_INFO, LOCK_OWNER) uw_sem_post (&(AS_INFO)->con_status_sem);
#define SHM_LOG_MSG_SIZE 256
#define APPL_NAME_LENGTH 128
#define JOB_QUEUE_MAX_SIZE 2048
#define MAX_CRYPT_STR_LENGTH 32
#define APPL_SERVER_NAME_MAX_SIZE 32
#define CAS_LOG_RESET_REOPEN 0x01
#define CAS_LOG_RESET_REMOVE 0x02
#define PROXY_LOG_RESET_REOPEN 0x01
#define MAX_DBNAME_LENGTH (64) /* maximum length of mysql database name and '\0' */
#define MAX_CONN_INFO_LENGTH ((CUB_MAXHOSTNAMELEN + 1) * 2) /* host1:host2 */
#define IP_BYTE_COUNT 5
#define ACL_MAX_ITEM_COUNT 50
#define ACL_MAX_IP_COUNT 256
#define ACL_MAX_DBNAME_LENGTH (SRV_CON_DBNAME_SIZE)
#define ACL_MAX_DBUSER_LENGTH (SRV_CON_DBUSER_SIZE)
#define MAX_PROXY_NUM 8
#define APPL_SERVER_NUM_LIMIT 4096
#define SHM_BROKER_PATH_MAX (PATH_MAX)
#define SHM_PROXY_NAME_MAX (SHM_BROKER_PATH_MAX)
#define SHM_APPL_SERVER_NAME_MAX (SHM_BROKER_PATH_MAX)
#define MAX_SHARD_USER (4)
#define MAX_SHARD_KEY (2)
#define MAX_SHARD_CONN (256)
#define SHARD_KEY_COLUMN_LEN (32)
#define SHARD_KEY_RANGE_MAX (256)
#define UNUSABLE_DATABASE_MAX (200)
#define PAIR_LIST (2)
#define PROXY_RESERVED_FD (128)
#define MAX_QUERY_TIMEOUT_LIMIT 86400 /* seconds; 1 day */
#define LONG_QUERY_TIME_LIMIT (MAX_QUERY_TIMEOUT_LIMIT)
#define LONG_TRANSACTION_TIME_LIMIT (MAX_QUERY_TIMEOUT_LIMIT)
#define MAX_PROXY_TIMEOUT_LIMIT (MAX_QUERY_TIMEOUT_LIMIT)
#define MIN_MYSQL_KEEPALIVE_INTERVAL 60 /* 60s */
#define SEQ_NUMBER 1
#define MAGIC_NUMBER (MAJOR_VERSION * 1000000 + MINOR_VERSION * 10000 + SEQ_NUMBER)
Typedefs
typedef enum t_con_status T_CON_STATUS
typedef struct ip_info IP_INFO
typedef struct access_list ACCESS_INFO
typedef struct t_shard_conn_info T_SHARD_CONN_INFO
typedef struct t_shard_user T_SHARD_USER
typedef struct t_shm_shard_user T_SHM_SHARD_USER
typedef struct t_shard_key_range T_SHARD_KEY_RANGE
typedef struct t_shard_key T_SHARD_KEY
typedef struct t_shm_shard_key T_SHM_SHARD_KEY
typedef struct t_shard_conn T_SHARD_CONN
typedef struct t_shm_shard_conn T_SHM_SHARD_CONN
typedef struct t_appl_server_info T_APPL_SERVER_INFO
typedef struct t_client_info T_CLIENT_INFO
typedef struct t_shard_info T_SHARD_INFO
typedef struct t_shm_shard_conn_stat T_SHM_SHARD_CONN_STAT
typedef struct t_shm_shard_key_range_stat T_SHM_SHARD_KEY_RANGE_STAT
typedef struct t_shm_shard_key_stat T_SHM_SHARD_KEY_STAT
typedef struct t_proxy_info T_PROXY_INFO
typedef struct t_shm_proxy T_SHM_PROXY
typedef struct t_db_server T_DB_SERVER
typedef struct t_shm_appl_server T_SHM_APPL_SERVER
typedef struct t_shm_broker T_SHM_BROKER
typedef enum t_shm_mode T_SHM_MODE
Enumerations
enum T_BROKER_SERVICE_STATUS { SERVICE_OFF = 0, SERVICE_ON = 1, SERVICE_OFF_ACK = 2, SERVICE_UNKNOWN = 3 }
enum t_con_status { CON_STATUS_OUT_TRAN = 0, CON_STATUS_IN_TRAN = 1, CON_STATUS_CLOSE = 2, CON_STATUS_CLOSE_AND_CONNECT = 3 }
enum t_shm_mode { SHM_MODE_ADMIN = 0, SHM_MODE_MONITOR = 1 }
Functions
void * uw_shm_open (int shm_key, int which_shm, T_SHM_MODE shm_mode)
void * uw_shm_create (int shm_key, int size, int which_shm)
int uw_shm_destroy (int shm_key)
void uw_shm_detach (void *)
int uw_sem_init (sem_t *sem_t)
int uw_sem_wait (sem_t *sem_t)
int uw_sem_post (sem_t *sem_t)
int uw_sem_destroy (sem_t *sem_t)
T_SHM_BROKER * broker_shm_initialize_shm_broker (int master_shm_id, T_BROKER_INFO *br_info, int br_num, int acl_flag, char *acl_file)
T_SHM_APPL_SERVER * broker_shm_initialize_shm_as (T_BROKER_INFO *br_info_p, T_SHM_PROXY *shm_proxy_p)
Macro Definition Documentation
#define ACL_MAX_DBNAME_LENGTH (SRV_CON_DBNAME_SIZE)
Definition at line 132 of file broker_shm.h.
Referenced by access_control_check_right_internal(), and access_control_read_config_file().
#define ACL_MAX_DBUSER_LENGTH (SRV_CON_DBUSER_SIZE)
Definition at line 133 of file broker_shm.h.
Referenced by access_control_check_right_internal(), and access_control_read_config_file().
#define ACL_MAX_IP_COUNT 256
Definition at line 131 of file broker_shm.h.
Referenced by access_control_read_ip_info().
#define ACL_MAX_ITEM_COUNT 50
Definition at line 130 of file broker_shm.h.
Referenced by access_control_read_config_file().
#define APPL_NAME_LENGTH 128
Definition at line 114 of file broker_shm.h.
#define APPL_SERVER_NAME_MAX_SIZE 32
Definition at line 120 of file broker_shm.h.
Referenced by admin_restart_cmd(), as_activate(), run_appl_server(), and run_proxy_server().
#define APPL_SERVER_NUM_LIMIT 4096
Definition at line 137 of file broker_shm.h.
Referenced by admin_conf_change(), admin_reset_cmd(), br_activate(), and broker_config_read_internal().
#define CAS_LOG_RESET_REMOVE 0x02
Definition at line 123 of file broker_shm.h.
Referenced by admin_del_cas_log(), cas_log_reset(), and cas_slow_log_reset().
#define CAS_LOG_RESET_REOPEN 0x01
Definition at line 122 of file broker_shm.h.
Referenced by admin_conf_change(), cas_log_open(), cas_main(), cas_slow_log_open(), check_cas_log(), and shard_shm_set_param_as_internal().
#define CON_STATUS_LOCK (AS_INFO, LOCK_OWNER) uw_sem_wait (&(AS_INFO)->con_status_sem);
Definition at line 106 of file broker_shm.h.
Referenced by broker_drop_one_cas_by_time_to_kill(), find_idle_cas(), net_read_int_keep_con_auto(), net_read_process(), and process_request().
#define CON_STATUS_LOCK_BROKER 0
Definition at line 72 of file broker_shm.h.
Referenced by broker_drop_one_cas_by_time_to_kill(), and find_idle_cas().
#define CON_STATUS_LOCK_CAS 1
Definition at line 73 of file broker_shm.h.
Referenced by net_read_int_keep_con_auto(), net_read_process(), and process_request().
#define CON_STATUS_LOCK_DESTROY (AS_INFO) uw_sem_destroy (&((AS_INFO)->con_status_sem));
Definition at line 103 of file broker_shm.h.
Referenced by as_inactivate(), cas_monitor_worker(), and run_appl_server().
#define CON_STATUS_LOCK_INIT (AS_INFO) uw_sem_init (&((AS_INFO)->con_status_sem));
Definition at line 100 of file broker_shm.h.
Referenced by as_activate(), br_activate(), and run_appl_server().
#define CON_STATUS_UNLOCK (AS_INFO, LOCK_OWNER) uw_sem_post (&(AS_INFO)->con_status_sem);
Definition at line 109 of file broker_shm.h.
Referenced by broker_drop_one_cas_by_time_to_kill(), find_idle_cas(), net_read_int_keep_con_auto(), net_read_process(), and process_request().
#define DEFAULT_SHM_KEY 0x3f5d1c0a
Definition at line 61 of file broker_shm.h.
#define IP_BYTE_COUNT 5
Definition at line 129 of file broker_shm.h.
Referenced by access_control_check_ip(), access_control_read_ip_info(), admin_acl_status_cmd(), css_notify_ha_log_applier_state(), and css_register_server_timeout_fn().
#define JOB_QUEUE_MAX_SIZE 2048
Definition at line 116 of file broker_shm.h.
Referenced by appl_monitor(), broker_config_read_internal(), and uc_as_info().
#define LONG_QUERY_TIME_LIMIT (MAX_QUERY_TIMEOUT_LIMIT)
Definition at line 164 of file broker_shm.h.
Referenced by admin_conf_change(), and broker_config_read_internal().
#define LONG_TRANSACTION_TIME_LIMIT (MAX_QUERY_TIMEOUT_LIMIT)
Definition at line 165 of file broker_shm.h.
Referenced by admin_conf_change(), and broker_config_read_internal().
#define MAGIC_NUMBER (MAJOR_VERSION * 1000000 + MINOR_VERSION * 10000 + SEQ_NUMBER)
Definition at line 176 of file broker_shm.h.
Referenced by uw_shm_create(), uw_shm_detach(), and uw_shm_open().
#define MAX_CONN_INFO_LENGTH ((CUB_MAXHOSTNAMELEN + 1) * 2) /* host1:host2 */
Definition at line 127 of file broker_shm.h.
#define MAX_CRYPT_STR_LENGTH 32
Definition at line 118 of file broker_shm.h.
#define MAX_DBNAME_LENGTH (64) /* maximum length of mysql database name and '\0' */
Definition at line 126 of file broker_shm.h.
#define MAX_NUM_UTS_ADMIN 10
Definition at line 59 of file broker_shm.h.
#define MAX_PROXY_NUM 8
Definition at line 135 of file broker_shm.h.
Referenced by brief_monitor(), broker_config_read_internal(), check_shard_conn(), and metadata_monitor().
#define MAX_PROXY_TIMEOUT_LIMIT (MAX_QUERY_TIMEOUT_LIMIT)
Definition at line 166 of file broker_shm.h.
Referenced by broker_config_read_internal().
#define MAX_QUERY_TIMEOUT_LIMIT 86400 /* seconds; 1 day */
Definition at line 163 of file broker_shm.h.
Referenced by admin_conf_change(), and broker_config_read_internal().
#define MAX_SHARD_CONN (256)
Definition at line 145 of file broker_shm.h.
Referenced by brief_monitor(), metadata_monitor(), proxy_get_shard_id(), proxy_update_shard_stats(), and shard_metadata_read_conn().
#define MAX_SHARD_KEY (2)
Definition at line 144 of file broker_shm.h.
Referenced by metadata_monitor().
#define MAX_SHARD_USER (4)
Definition at line 143 of file broker_shm.h.
#define MIN_MYSQL_KEEPALIVE_INTERVAL 60 /* 60s */
Definition at line 173 of file broker_shm.h.
Referenced by admin_conf_change(), and broker_config_read_internal().
#define PAIR_LIST (2)
Definition at line 151 of file broker_shm.h.
#define PROXY_LOG_RESET_REOPEN 0x01
Definition at line 124 of file broker_shm.h.
Referenced by check_proxy_access_log(), and check_proxy_log().
#define PROXY_RESERVED_FD (128)
Definition at line 160 of file broker_shm.h.
Referenced by proxy_io_initialize(), shard_shm_check_max_file_open_limit(), shard_shm_get_max_context(), and shard_shm_init_shard_stat().
#define PROXY_STATUS_BUSY 1
Definition at line 55 of file broker_shm.h.
#define PROXY_STATUS_RESTART 2
Definition at line 56 of file broker_shm.h.
Referenced by proxy_monitor_worker().
#define PROXY_STATUS_START 3
Definition at line 57 of file broker_shm.h.
Referenced by proxy_monitor_worker(), and shard_shm_initialize_shm_proxy().
#define SEQ_NUMBER 1
Definition at line 175 of file broker_shm.h.
#define SHARD_KEY_COLUMN_LEN (32)
Definition at line 147 of file broker_shm.h.
Referenced by shard_metadata_read_key().
#define SHARD_KEY_RANGE_MAX (256)
Definition at line 148 of file broker_shm.h.
Referenced by shard_metadata_read_key().
#define SHM_APPL_SERVER 0
Definition at line 63 of file broker_shm.h.
Referenced by admin_acl_reload_cmd(), admin_acl_status_cmd(), admin_add_cmd(), admin_conf_change(), admin_del_cas_log(), admin_drop_cmd(), admin_reset_cmd(), admin_restart_cmd(), appl_monitor(), br_activate(), br_inactivate(), brief_monitor(), broker_init_shm(), broker_shm_initialize_shm_as(), cas_init_shm(), proxy_shm_initialize(), shard_shm_dump_proxy_info(), shard_shm_set_param_as(), shard_shm_set_param_proxy_internal(), uc_as_info(), uc_as_shm_open(), uc_br_info(), unusable_databases_monitor(), uw_shm_create(), and uw_shm_open().
#define SHM_APPL_SERVER_NAME_MAX (SHM_BROKER_PATH_MAX)
Definition at line 141 of file broker_shm.h.
Referenced by admin_conf_change().
#define SHM_BROKER 1
Definition at line 64 of file broker_shm.h.
Referenced by admin_acl_reload_cmd(), admin_acl_status_cmd(), admin_add_cmd(), admin_conf_change(), admin_del_cas_log(), admin_drop_cmd(), admin_getid_cmd(), admin_info_cmd(), admin_off_cmd(), admin_on_cmd(), admin_reset_cmd(), admin_restart_cmd(), admin_stop_cmd(), broker_create_dir(), broker_init_shm(), broker_shm_initialize_shm_broker(), init_tester_info(), main(), uc_as_info(), uc_br_info(), uc_broker_shm_open(), uw_shm_create(), and uw_shm_open().
#define SHM_BROKER_PATH_MAX (PATH_MAX)
Definition at line 139 of file broker_shm.h.
#define SHM_LOG_MSG_SIZE 256
Definition at line 112 of file broker_shm.h.
Referenced by fn_execute_internal(), and fn_prepare_internal().
#define SHM_MUTEX_ADMIN 1
Definition at line 69 of file broker_shm.h.
Referenced by admin_restart_cmd(), as_activate(), and broker_shm_set_as_info().
#define SHM_MUTEX_BROKER 0
Definition at line 68 of file broker_shm.h.
Referenced by admin_restart_cmd(), as_activate(), and broker_shm_set_as_info().
#define SHM_PROXY 2
Definition at line 65 of file broker_shm.h.
Referenced by admin_conf_change(), admin_getid_cmd(), admin_reset_cmd(), br_activate(), br_inactivate(), brief_monitor(), broker_init_shm(), client_monitor(), init_tester_info(), metadata_monitor(), proxy_shm_initialize(), shard_metadata_dump(), shard_shm_dump_appl_server(), shard_shm_initialize_shm_proxy(), uw_shm_create(), and uw_shm_open().
#define SHM_PROXY_NAME_MAX (SHM_BROKER_PATH_MAX)
Definition at line 140 of file broker_shm.h.
Referenced by broker_shm_initialize_shm_as(), and proxy_activate_internal().
#define STATE_KEEP_FALSE 0
Definition at line 43 of file broker_shm.h.
#define STATE_KEEP_TRUE 1
Definition at line 42 of file broker_shm.h.
#define UNUSABLE_DATABASE_MAX (200)
Definition at line 150 of file broker_shm.h.
Referenced by insert_db_server_check_list(), and server_monitor_thr_f().
#define UTS_STATUS_BUSY 1
Definition at line 45 of file broker_shm.h.
Referenced by admin_restart_cmd(), appl_info_display(), broker_drop_one_cas_by_time_to_kill(), cas_main(), cas_monitor_worker(), find_drop_as_index(), find_idle_cas(), get_status_string(), process_request(), receiver_thr_f(), server_monitor_thr_f(), set_monitor_items(), shard_cas_main(), and uc_as_info().
#define UTS_STATUS_CON_WAIT 5
Definition at line 52 of file broker_shm.h.
Referenced by as_activate(), check_shard_as_conn(), get_status_string(), run_appl_server(), and shard_cas_main().
#define UTS_STATUS_IDLE 0
Definition at line 46 of file broker_shm.h.
Referenced by admin_restart_cmd(), as_activate(), as_inactivate(), broker_add_new_cas(), broker_drop_one_cas_by_time_to_kill(), cas_main(), cas_monitor_worker(), dispatch_thr_f(), find_drop_as_index(), find_idle_cas(), process_request(), and shard_cas_main().
#define UTS_STATUS_RESTART 2
Definition at line 47 of file broker_shm.h.
Referenced by cas_final(), cas_monitor_worker(), cas_sig_handler(), find_idle_cas(), get_status_string(), shard_cas_main(), and uc_as_info().
#define UTS_STATUS_START 3
Definition at line 48 of file broker_shm.h.
Referenced by as_activate(), cas_monitor_worker(), and shard_broker_process().
#define UTS_STATUS_STOP 6
Definition at line 53 of file broker_shm.h.
Referenced by cas_monitor_worker(), and shard_cas_main().
Typedef Documentation
typedef struct access_list ACCESS_INFO
Definition at line 207 of file broker_shm.h.
typedef struct ip_info IP_INFO
Definition at line 199 of file broker_shm.h.
typedef struct t_appl_server_info T_APPL_SERVER_INFO
Definition at line 290 of file broker_shm.h.
typedef struct t_client_info T_CLIENT_INFO
Definition at line 385 of file broker_shm.h.
typedef enum t_con_status T_CON_STATUS
Definition at line 193 of file broker_shm.h.
typedef struct t_db_server T_DB_SERVER
Definition at line 549 of file broker_shm.h.
typedef struct t_proxy_info T_PROXY_INFO
Definition at line 457 of file broker_shm.h.
typedef struct t_shard_conn T_SHARD_CONN
Definition at line 274 of file broker_shm.h.
typedef struct t_shard_conn_info T_SHARD_CONN_INFO
Definition at line 216 of file broker_shm.h.
typedef struct t_shard_info T_SHARD_INFO
Definition at line 410 of file broker_shm.h.
typedef struct t_shard_key T_SHARD_KEY
Definition at line 258 of file broker_shm.h.
typedef struct t_shard_key_range T_SHARD_KEY_RANGE
Definition at line 247 of file broker_shm.h.
typedef struct t_shard_user T_SHARD_USER
Definition at line 231 of file broker_shm.h.
typedef struct t_shm_appl_server T_SHM_APPL_SERVER
Definition at line 557 of file broker_shm.h.
typedef struct t_shm_broker T_SHM_BROKER
Definition at line 647 of file broker_shm.h.
typedef enum t_shm_mode T_SHM_MODE
Definition at line 669 of file broker_shm.h.
typedef struct t_shm_proxy T_SHM_PROXY
Definition at line 524 of file broker_shm.h.
typedef struct t_shm_shard_conn T_SHM_SHARD_CONN
Definition at line 282 of file broker_shm.h.
typedef struct t_shm_shard_conn_stat T_SHM_SHARD_CONN_STAT
Definition at line 425 of file broker_shm.h.
typedef struct t_shm_shard_key T_SHM_SHARD_KEY
Definition at line 266 of file broker_shm.h.
typedef struct t_shm_shard_key_range_stat T_SHM_SHARD_KEY_RANGE_STAT
Definition at line 435 of file broker_shm.h.
typedef struct t_shm_shard_key_stat T_SHM_SHARD_KEY_STAT
Definition at line 445 of file broker_shm.h.
typedef struct t_shm_shard_user T_SHM_SHARD_USER
Definition at line 239 of file broker_shm.h.
Enumeration Type Documentation
enum T_BROKER_SERVICE_STATUS
Enumerator
SERVICE_OFF
SERVICE_ON
SERVICE_OFF_ACK
SERVICE_UNKNOWN
Definition at line 178 of file broker_shm.h.
enum t_con_status
Enumerator
CON_STATUS_OUT_TRAN
CON_STATUS_IN_TRAN
CON_STATUS_CLOSE
CON_STATUS_CLOSE_AND_CONNECT
Definition at line 186 of file broker_shm.h.
enum t_shm_mode
Enumerator
SHM_MODE_ADMIN
SHM_MODE_MONITOR
Definition at line 664 of file broker_shm.h.
Function Documentation
T_SHM_APPL_SERVER* broker_shm_initialize_shm_as (T_BROKER_INFO * br_info_p, T_SHM_PROXY * shm_proxy_p)
Definition at line 471 of file broker_shm.c.
References t_broker_info::access_log, t_shm_appl_server::access_log, t_broker_info::access_log_file, t_shm_appl_server::access_log_file, t_broker_info::access_log_max_size, t_shm_appl_server::access_log_max_size, t_broker_info::access_mode, t_shm_appl_server::access_mode, t_appl_server_info::advance_activate_flag, t_broker_info::appl_server, t_broker_info::appl_server_hard_limit, t_shm_appl_server::appl_server_hard_limit, t_broker_info::appl_server_max_num, t_broker_info::appl_server_max_size, t_shm_appl_server::appl_server_max_size, t_shm_appl_server::appl_server_name, t_broker_info::appl_server_num, t_broker_info::appl_server_shm_id, t_shm_appl_server::as_info, t_shard_info::as_info_index_base, assert, t_shm_appl_server::broker_name, t_shm_appl_server::broker_port, broker_shm_set_as_info(), t_broker_info::cache_user_info, t_shm_appl_server::cache_user_info, t_broker_info::cas_rctime, t_shm_appl_server::cas_rctime, t_broker_info::cci_default_autocommit, t_shm_appl_server::cci_default_autocommit, t_broker_info::cci_pconnect, t_shm_appl_server::cci_pconnect, t_broker_info::connect_order, t_shm_appl_server::connect_order, t_appl_server_info::database_passwd, t_appl_server_info::database_user, t_broker_info::db_connection_file, t_shm_appl_server::db_connection_file, t_shard_conn_info::db_password, t_shard_conn_info::db_user, t_broker_info::err_log_dir, t_shm_appl_server::err_log_dir, t_broker_info::error_log_file, t_shm_appl_server::error_log_file, t_appl_server_info::fixed_shard_user, t_proxy_info::fixed_shard_user, t_appl_server_info::force_reconnect, get_appl_server_name(), t_max_heap_node::id, t_broker_info::jdbc_cache, t_shm_appl_server::jdbc_cache, t_broker_info::jdbc_cache_life_time, t_shm_appl_server::jdbc_cache_life_time, t_broker_info::jdbc_cache_only_hint, t_shm_appl_server::jdbc_cache_only_hint, t_shm_appl_server::job_queue, t_broker_info::job_queue_size, t_shm_appl_server::job_queue_size, t_broker_info::keep_connection, t_shm_appl_server::keep_connection, t_broker_info::log_dir, t_shm_appl_server::log_dir, t_broker_info::long_query_time, t_shm_appl_server::long_query_time, t_broker_info::long_transaction_time, t_shm_appl_server::long_transaction_time, t_shard_info::max_appl_server, t_broker_info::max_num_delayed_hosts_lookup, t_shm_appl_server::max_num_delayed_hosts_lookup, t_broker_info::max_prepared_stmt_count, t_shm_appl_server::max_prepared_stmt_count, t_broker_info::max_string_length, t_shm_appl_server::max_string_length, t_broker_info::monitor_hang_flag, t_shm_appl_server::monitor_hang_flag, t_broker_info::monitor_server_flag, t_shm_appl_server::monitor_server_flag, t_broker_info::mysql_keepalive_interval, t_shm_appl_server::mysql_keepalive_interval, t_broker_info::mysql_read_timeout, t_shm_appl_server::mysql_read_timeout, t_broker_info::name, NULL, t_shm_appl_server::num_appl_server, t_shm_proxy::num_proxy, t_proxy_info::num_shard_conn, OFF, t_broker_info::port, t_shm_appl_server::port_name, t_broker_info::preferred_hosts, t_shm_appl_server::preferred_hosts, t_broker_info::proxy_conn_wait_timeout, t_appl_server_info::proxy_conn_wait_timeout, proxy_id, t_appl_server_info::proxy_id, t_shm_proxy::proxy_info, proxy_info_p, t_broker_info::proxy_log_dir, t_shm_appl_server::proxy_log_dir, t_broker_info::proxy_log_max_size, t_shm_appl_server::proxy_log_max_size, t_broker_info::query_timeout, t_shm_appl_server::query_timeout, t_broker_info::replica_only_flag, t_shm_appl_server::replica_only_flag, t_broker_info::session_timeout, t_shm_appl_server::session_timeout, t_appl_server_info::shard_cas_id, t_shm_appl_server::shard_conn_info, t_broker_info::shard_flag, t_shm_appl_server::shard_flag, t_appl_server_info::shard_id, t_proxy_info::shard_info, shard_shm_set_shard_conn_info(), SHM_APPL_SERVER, shm_as_p, SHM_PROXY_NAME_MAX, t_broker_info::slow_log_dir, t_shm_appl_server::slow_log_dir, t_broker_info::slow_log_mode, t_shm_appl_server::slow_log_mode, t_broker_info::sql_log2, t_shm_appl_server::sql_log2, t_broker_info::sql_log_max_size, t_shm_appl_server::sql_log_max_size, t_broker_info::sql_log_mode, t_shm_appl_server::sql_log_mode, t_broker_info::statement_pooling, t_shm_appl_server::statement_pooling, t_broker_info::stripped_column_name, t_shm_appl_server::stripped_column_name, strncpy_bufsize, t_broker_info::trigger_action_flag, t_shm_appl_server::trigger_action_flag, t_shm_appl_server::unusable_databases_cnt, ut_get_broker_port_name(), and uw_shm_create().
Referenced by admin_on_cmd(), and admin_start_cmd().
T_SHM_BROKER* broker_shm_initialize_shm_broker (int master_shm_id, T_BROKER_INFO * br_info, int br_num, int acl_flag, char * acl_file)
Definition at line 416 of file broker_shm.c.
References t_shm_broker::access_control, t_shm_broker::access_control_file, t_broker_info::access_log_file, t_shm_broker::br_info, CONF_LOG_FILE_LEN, t_broker_info::error_log_file, get_access_log_file_name(), get_error_log_file_name(), get_host_ip(), i, t_shm_broker::magic, t_shm_broker::my_ip_addr, t_broker_info::name, NULL, t_shm_broker::num_broker, OFF, t_shm_broker::owner_uid, shm_br, SHM_BROKER, and uw_shm_create().
Referenced by admin_start_cmd().
int uw_sem_destroy (sem_t * sem_t)
Definition at line 919 of file broker_shm.c.
Referenced by br_inactivate(), and uw_sem_post().
int uw_sem_init (sem_t * sem_t)
Definition at line 834 of file broker_shm.c.
References uw_sem_wait().
Referenced by access_control_set_shm(), and get_host_ip().
int uw_sem_post (sem_t * sem_t)
Definition at line 893 of file broker_shm.c.
References NULL, and uw_sem_destroy().
Referenced by access_control_check_right(), access_control_read_config_file(), record_ip_access_time(), and uw_sem_wait().
int uw_sem_wait (sem_t * sem_t)
Definition at line 867 of file broker_shm.c.
References uw_sem_post().
Referenced by access_control_check_right(), access_control_read_config_file(), record_ip_access_time(), and uw_sem_init().
void* uw_shm_create (int shm_key, int size, int which_shm)
Definition at line 334 of file broker_shm.c.
References MAGIC_NUMBER, NULL, p, SHM_APPL_SERVER, SHM_BROKER, SHM_PROXY, and SHMODE.
Referenced by broker_shm_initialize_shm_as(), broker_shm_initialize_shm_broker(), shard_shm_initialize_shm_proxy(), and uw_shm_open().
int uw_shm_destroy (int shm_key)
Definition at line 391 of file broker_shm.c.
References SHMODE.
Referenced by admin_off_cmd(), admin_on_cmd(), admin_start_cmd(), admin_stop_cmd(), and shard_shm_initialize_shm_proxy().
void uw_shm_detach (void *)
Definition at line 700 of file broker_shm.c.
References list_tag::key, MAGIC_NUMBER, and list_tag::value.
Referenced by admin_acl_reload_cmd(), admin_acl_status_cmd(), admin_add_cmd(), admin_conf_change(), admin_del_cas_log(), admin_drop_cmd(), admin_getid_cmd(), admin_info_cmd(), admin_off_cmd(), admin_on_cmd(), admin_reset_cmd(), admin_restart_cmd(), admin_start_cmd(), admin_stop_cmd(), appl_monitor(), as_activate(), br_activate(), br_inactivate(), brief_monitor(), broker_create_dir(), cas_init_shm(), client_monitor(), init_tester_info(), main(), metadata_monitor(), shard_metadata_dump(), shard_shm_dump_appl_server(), shard_shm_dump_proxy_info(), shard_shm_set_param_as(), shard_shm_set_param_proxy_internal(), shard_shm_set_shard_conn_info(), uc_as_info(), uc_br_info(), uc_shm_detach(), and unusable_databases_monitor().
void* uw_shm_open (int shm_key, int which_shm, T_SHM_MODE shm_mode)
Definition at line 139 of file broker_shm.c.
References FALSE, link_list_add(), MAGIC_NUMBER, NULL, p, SHM_APPL_SERVER, SHM_BROKER, SHM_MODE_ADMIN, SHM_PROXY, SHMODE, TRUE, UW_ER_SHM_OPEN, UW_ER_SHM_OPEN_MAGIC, UW_SET_ERROR_CODE, and uw_shm_create().
Referenced by admin_acl_reload_cmd(), admin_acl_status_cmd(), admin_add_cmd(), admin_conf_change(), admin_del_cas_log(), admin_drop_cmd(), admin_getid_cmd(), admin_info_cmd(), admin_off_cmd(), admin_on_cmd(), admin_reset_cmd(), admin_restart_cmd(), admin_stop_cmd(), appl_monitor(), br_activate(), br_inactivate(), brief_monitor(), broker_create_dir(), broker_init_shm(), cas_init_shm(), client_monitor(), init_tester_info(), main(), metadata_monitor(), proxy_shm_initialize(), shard_metadata_dump(), shard_shm_dump_appl_server(), shard_shm_dump_proxy_info(), shard_shm_set_param_as(), shard_shm_set_param_proxy_internal(), uc_as_info(), uc_as_shm_open(), uc_br_info(), uc_broker_shm_open(), and unusable_databases_monitor().