CUBRID Engine: src/broker/broker_log_sql_list.h File Reference
broker_log_sql_list.h File Reference
Classes
struct t_sql_info
Typedefs
typedef struct t_sql_info T_SQL_INFO
Functions
int sql_list_make (char *list_file)
int sql_info_write (char *sql_org, char *q_name, FILE *fp)
Typedef Documentation
typedef struct t_sql_info T_SQL_INFO
Definition at line 29 of file broker_log_sql_list.h.
Function Documentation
int sql_info_write (char * sql_org, char * q_name, FILE * fp)
Definition at line 136 of file broker_log_sql_list.c.
References comp_func(), t_sql_info::filename, FREE_MEM, i, NULL, t_sql_info::num_file, num_sql_list, t_sql_info::sql, sql_change_comp_form(), and strdup().
Referenced by query_info_print().
int sql_list_make (char * list_file)
Definition at line 51 of file broker_log_sql_list.c.
References comp_func(), error(), IS_NEXT_QUERY, LINE_BUF_SIZE, NULL, num_sql_list, sql_change_comp_form(), sql_info_add(), strlen, t_string_add(), t_string_clear(), t_string_free(), t_string_make(), t_string_str(), and ut_get_line().
Referenced by log_top_query().