CUBRID Engine: src/broker/broker_log_converter.c File Reference
broker_log_converter.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include "cubrid_getopt.h"
#include "cas_common.h"
#include "cas_cci.h"
#include "broker_log_util.h"
Functions
static int get_args (int argc, char *argv[])
static int open_file (char *infilename, char *outfilename, FILE **infp, FILE **outfp)
static int log_converter (FILE *infp, FILE *outfp)
static void close_file (FILE *infp, FILE *outfp)
static int log_bind_value (char *str, int bind_len, int lineno, FILE *outfp)
int main (int argc, char *argv[])
Variables
static char add_query_info = 0
static char add_query_id = 0
static char * infilename = NULL
Function Documentation
static void close_file (FILE * infp, FILE * outfp) static
Definition at line 223 of file broker_log_converter.c.
Referenced by main().
static int get_args (int argc, char * argv[]) static
Definition at line 419 of file broker_log_converter.c.
References add_query_id, add_query_info, getopt(), optind, and usage().
Referenced by main().
static int log_bind_value (char * str, int bind_len, int lineno, FILE * outfp) static
Definition at line 234 of file broker_log_converter.c.
References NULL, and p.
Referenced by log_converter().
static int log_converter (FILE * infp, FILE * outfp) static
Definition at line 73 of file broker_log_converter.c.
References add_query_id, add_query_info, CAS_RUN_NEW_LINE_CHAR, error(), FREE_MEM, get_msg_start_ptr(), infilename, is_cas_log(), log_bind_value(), NULL, str_to_int32(), strlen, t_string_bind_len(), t_string_len(), t_string_make(), t_string_str(), ut_get_execute_type(), and ut_get_line().
Referenced by main().
int main (int argc, char * argv[])
Definition at line 49 of file broker_log_converter.c.
References close_file(), get_args(), infilename, log_converter(), NULL, and open_file().
static int open_file (char * infilename, char * outfilename, FILE ** infp, FILE ** outfp) static
Definition at line 189 of file broker_log_converter.c.
References NULL.
Referenced by main().
Variable Documentation
char add_query_id = 0 static
Definition at line 45 of file broker_log_converter.c.
Referenced by get_args(), and log_converter().
char add_query_info = 0 static
Definition at line 44 of file broker_log_converter.c.
Referenced by get_args(), and log_converter().
char* infilename = NULL static
Definition at line 46 of file broker_log_converter.c.
Referenced by log_converter(), and main().