CUBRID Engine: src/broker/broker_log_util.h File Reference
broker_log_util.h File Reference
#include <sys/time.h>
#include "cas_common.h"
#include "log_top_string.h"
Macros
#define CAS_LOG_BEGIN_WITH_YEAR 1
#define CAS_LOG_BEGIN_WITH_MONTH 2
#define CAS_LOG_MSG_INDEX 22
#define CAS_RUN_NEW_LINE_CHAR 1
#define DATE_STR_LEN 21
#define GET_CUR_DATE_STR(BUF, LINEBUF)
Functions
char * ut_trim (char *)
void ut_tolower (char *str)
int ut_get_line (FILE *fp, T_STRING *t_str, char **out_str, int *lineno)
int is_cas_log (char *str)
char * get_msg_start_ptr (char *linebuf)
int str_to_log_date_format (char *str, char *date_format_str)
char * ut_get_execute_type (char *msg_p, int *prepare_flag, int *execute_flag)
int ut_check_log_valid_time (const char *log_date, const char *from_date, const char *to_date)
double ut_diff_time (struct timeval *begin, struct timeval *end)
Macro Definition Documentation
#define CAS_LOG_BEGIN_WITH_MONTH 2
Definition at line 39 of file broker_log_util.h.
Referenced by is_cas_log(), and log_top().
#define CAS_LOG_BEGIN_WITH_YEAR 1
Definition at line 38 of file broker_log_util.h.
Referenced by get_msg_start_ptr(), is_cas_log(), log_top(), read_bind_value(), read_multi_line_sql(), and search_offset().
#define CAS_LOG_MSG_INDEX 22
Definition at line 41 of file broker_log_util.h.
Referenced by get_msg_start_ptr(), and is_cas_log().
#define CAS_RUN_NEW_LINE_CHAR 1
Definition at line 42 of file broker_log_util.h.
Referenced by log_converter().
#define DATE_STR_LEN 21
Definition at line 44 of file broker_log_util.h.
Referenced by check_log_time(), log_replay(), log_top(), search_offset(), and ut_check_log_valid_time().
#define GET_CUR_DATE_STR (BUF, LINEBUF)
Value:
do  {                           \
          strncpy(BUF, LINEBUF, DATE_STR_LEN);  \
          BUF[DATE_STR_LEN] = '\0';             \
        } while (0)
Definition at line 46 of file broker_log_util.h.
Referenced by log_replay(), and log_top().
Function Documentation
char* get_msg_start_ptr (char * linebuf)
Definition at line 379 of file broker_log_util.c.
References CAS_LOG_BEGIN_WITH_YEAR, CAS_LOG_MSG_INDEX, is_cas_log(), and NULL.
Referenced by is_bind_with_size(), log_converter(), log_replay(), log_top(), and read_bind_value().
int is_cas_log (char * str)
Definition at line 359 of file broker_log_util.c.
References CAS_LOG_BEGIN_WITH_MONTH, CAS_LOG_BEGIN_WITH_YEAR, CAS_LOG_MSG_INDEX, and strlen.
Referenced by get_msg_start_ptr(), log_converter(), log_replay(), log_top(), read_bind_value(), read_multi_line_sql(), and search_offset().
int str_to_log_date_format (char * str, char * date_format_str)
Definition at line 405 of file broker_log_util.c.
References DATE_VALUE_COUNT, error(), i, and str_to_int32().
Referenced by get_args().
int ut_check_log_valid_time (const char * log_date, const char * from_date, const char * to_date)
Definition at line 480 of file broker_log_util.c.
References DATE_STR_LEN.
Referenced by log_replay().
double ut_diff_time (struct timeval * begin, struct timeval * end)
Definition at line 497 of file broker_log_util.c.
Referenced by cas_runner(), log_execute(), log_replay(), process_endtran(), and process_execute().
char* ut_get_execute_type (char * msg_p, int * prepare_flag, int * execute_flag)
Definition at line 453 of file broker_log_util.c.
References NULL.
Referenced by log_converter(), log_execute(), and log_prepare().
int ut_get_line (FILE * fp, T_STRING * t_str, char ** out_str, int * lineno)
Definition at line 283 of file broker_log_util.c.
References FREE_MEM, is_bind_with_size(), MALLOC, NULL, strlen, t_bind_string_add(), t_string_add(), t_string_clear(), t_string_len(), and t_string_str().
Referenced by cas_runner(), get_next_log_line(), log_converter(), log_top(), read_bind_value(), read_multi_line_sql(), search_offset(), and sql_list_make().
void ut_tolower (char * str)
Definition at line 73 of file broker_log_util.c.
char* ut_trim (char *)
Definition at line 43 of file broker_log_util.c.