CUBRID Engine: src/broker/broker_acl.h File Reference
broker_acl.h File Reference
#include "broker_shm.h"
Functions
int access_control_set_shm (T_SHM_APPL_SERVER *shm_as_cp, T_BROKER_INFO *br_info_p, T_SHM_BROKER *shm_br, char *admin_err_msg)
int access_control_read_config_file (T_SHM_APPL_SERVER *shm_appl, char *filename, char *admin_err_msg)
int access_control_check_right (T_SHM_APPL_SERVER *shm_as_p, char *dbname, char *dbuser, unsigned char *address)
Function Documentation
int access_control_check_right (T_SHM_APPL_SERVER * shm_as_p, char * dbname, char * dbuser, unsigned char * address)
Definition at line 401 of file broker_acl.c.
References access_control_check_right_internal(), t_shm_appl_server::access_info, access_info_changed, t_shm_appl_server::acl_chn, t_shm_appl_server::acl_sem, t_shm_appl_server::broker_name, BROKER_NAME_LEN, num_access_info, t_shm_appl_server::num_access_info, uw_sem_post(), and uw_sem_wait().
Referenced by cas_main(), and proxy_process_client_register().
int access_control_read_config_file (T_SHM_APPL_SERVER * shm_appl, char * filename, char * admin_err_msg)
Definition at line 112 of file broker_acl.c.
References access_control_find_access_info(), access_control_read_ip_info(), access_control_repath_file(), ACCESS_FILE_DELIMITER, access_info, t_shm_appl_server::access_info, t_shm_appl_server::acl_chn, ACL_MAX_DBNAME_LENGTH, ACL_MAX_DBUSER_LENGTH, ACL_MAX_ITEM_COUNT, t_shm_appl_server::acl_sem, ADMIN_ERR_MSG_SIZE, t_shm_appl_server::broker_name, BROKER_NAME_LEN, BROKER_PATH_MAX, dbname, access_list::dbname, dbuser, access_list::dbuser, error(), IP_FILE_DELIMITER, access_list::ip_files, access_list::ip_info, NULL, t_shm_appl_server::num_access_info, p, strlen, trim(), uw_sem_post(), and uw_sem_wait().
Referenced by access_control_set_shm(), and admin_acl_reload_cmd().
int access_control_set_shm (T_SHM_APPL_SERVER * shm_as_cp, T_BROKER_INFO * br_info_p, T_SHM_BROKER * shm_br, char * admin_err_msg)
Definition at line 53 of file broker_acl.c.
References t_shm_appl_server::access_control, t_shm_broker::access_control, t_shm_broker::access_control_file, access_control_read_config_file(), t_shm_appl_server::acl_chn, t_shm_appl_server::acl_sem, BROKER_NAME_LEN, FID_ACCESS_CONTROL_FILE, get_cubrid_file_ptr(), t_shm_appl_server::local_ip_addr, t_shm_broker::my_ip_addr, t_broker_info::name, set_cubrid_file(), and uw_sem_init().
Referenced by admin_on_cmd(), and admin_start_cmd().