CUBRID Engine: src/broker/broker_error.h File Reference
broker_error.h File Reference
Macros
#define UW_ER_NO_ERROR 0
#define UW_ER_NO_REQUEST_METHOD -11001
#define UW_ER_NOT_SUPPORTED_REQUEST_METHOD -11002
#define UW_ER_NO_APPL_NAME -11003
#define UW_ER_CANT_CREATE_SOCKET -11004
#define UW_ER_CANT_CONNECT -11005
#define UW_ER_CANT_BIND -11006
#define UW_ER_SOCKET_NOT_INITIALIZED -11007
#define UW_ER_CANT_ACCEPT -11008
#define UW_ER_NO_MORE_MEMORY -11009
#define UW_ER_NO_FREE_UTS -11010
#define UW_ER_NO_SESSION_UTS -11011
#define UW_ER_SESSION_NOT_FOUND -11012
#define UW_ER_SHM_OPEN -11013
#define UW_ER_SCRIPT_FILE -11014
#define UW_ER_UNKNOWN_FILE_C -11015
#define UW_ER_UNKNOWN_FILE_W -11016
#define UW_ER_DB_NOT_INITIALIZED -11017
#define UW_ER_SQL_HANDLE_NOT_FOUND -11018
#define UW_ER_INVALID_OBJECT -11019
#define UW_ER_INVALID_BIT -11020
#define UW_ER_INVALID_CHAR -11021
#define UW_ER_INVALID_DOUBLE -11022
#define UW_ER_INVALID_FLOAT -11023
#define UW_ER_INVALID_INT -11024
#define UW_ER_INVALID_MONETARY -11025
#define UW_ER_INVALID_NUMERIC -11026
#define UW_ER_INVALID_SET -11027
#define UW_ER_INVALID_SET_DOM -11028
#define UW_ER_INVALID_DOMAIN -11029
#define UW_ER_CMD_ARGS -11030
#define UW_ER_NOT_SUPPORT_SH_CMD -11031
#define UW_ER_COMMUNICATION -11032
#define UW_ER_DOMAIN_NON_SET -11033
#define UW_ER_DIVIDE_BY_ZERO -11034
#define UW_ER_FILE_MNG -11035
#define UW_ER_FILE_REMOVE -11036
#define UW_ER_FILE_COPY -11037
#define UW_ER_FILE_MOVE -11038
#define UW_ER_DIR_REMOVE -11039
#define UW_ER_DIR_MAKE -11040
#define UW_ER_FILE_CREATE -11041
#define UW_ER_FCNTL -11042
#define UW_ER_POST_DATA -11043
#define UW_ER_OPEN_TEMP_FILE -11044
#define UW_ER_FILE_UPLOAD -11045
#define UW_ER_FILE_WRITE -11046
#define UW_ER_SERVER_INFO -11047
#define UW_ER_DISP_WORK_DIR -11048
#define UW_ER_WIN_SERVER_CONF -11049
#define UW_ER_INVALID_CLIENT -11050
#define UW_ER_SHM_OPEN_MAGIC -11051
#define UW_MIN_ERROR_CODE -11000
#define UW_MAX_ERROR_CODE -11051
#define UW_SET_ERROR_CODE(code, os_errno) uw_set_error_code(__FILE__, __LINE__, (code), (os_errno))
Functions
void uw_set_error_code (const char *file_name, int line_no, int error_code, int os_errno)
int uw_get_error_code (void)
int uw_get_os_error_code (void)
const char * uw_get_error_message (int error_code, int os_errno)
Macro Definition Documentation
#define UW_ER_CANT_ACCEPT -11008
Definition at line 39 of file broker_error.h.
#define UW_ER_CANT_BIND -11006
Definition at line 37 of file broker_error.h.
Referenced by init_env().
#define UW_ER_CANT_CONNECT -11005
Definition at line 36 of file broker_error.h.
#define UW_ER_CANT_CREATE_SOCKET -11004
Definition at line 35 of file broker_error.h.
Referenced by broker_init_shm(), init_env(), and main().
#define UW_ER_CMD_ARGS -11030
Definition at line 61 of file broker_error.h.
#define UW_ER_COMMUNICATION -11032
Definition at line 63 of file broker_error.h.
#define UW_ER_DB_NOT_INITIALIZED -11017
Definition at line 48 of file broker_error.h.
#define UW_ER_DIR_MAKE -11040
Definition at line 71 of file broker_error.h.
#define UW_ER_DIR_REMOVE -11039
Definition at line 70 of file broker_error.h.
#define UW_ER_DISP_WORK_DIR -11048
Definition at line 79 of file broker_error.h.
#define UW_ER_DIVIDE_BY_ZERO -11034
Definition at line 65 of file broker_error.h.
#define UW_ER_DOMAIN_NON_SET -11033
Definition at line 64 of file broker_error.h.
#define UW_ER_FCNTL -11042
Definition at line 73 of file broker_error.h.
#define UW_ER_FILE_COPY -11037
Definition at line 68 of file broker_error.h.
#define UW_ER_FILE_CREATE -11041
Definition at line 72 of file broker_error.h.
#define UW_ER_FILE_MNG -11035
Definition at line 66 of file broker_error.h.
#define UW_ER_FILE_MOVE -11038
Definition at line 69 of file broker_error.h.
#define UW_ER_FILE_REMOVE -11036
Definition at line 67 of file broker_error.h.
#define UW_ER_FILE_UPLOAD -11045
Definition at line 76 of file broker_error.h.
#define UW_ER_FILE_WRITE -11046
Definition at line 77 of file broker_error.h.
#define UW_ER_INVALID_BIT -11020
Definition at line 51 of file broker_error.h.
#define UW_ER_INVALID_CHAR -11021
Definition at line 52 of file broker_error.h.
#define UW_ER_INVALID_CLIENT -11050
Definition at line 81 of file broker_error.h.
#define UW_ER_INVALID_DOMAIN -11029
Definition at line 60 of file broker_error.h.
#define UW_ER_INVALID_DOUBLE -11022
Definition at line 53 of file broker_error.h.
#define UW_ER_INVALID_FLOAT -11023
Definition at line 54 of file broker_error.h.
#define UW_ER_INVALID_INT -11024
Definition at line 55 of file broker_error.h.
#define UW_ER_INVALID_MONETARY -11025
Definition at line 56 of file broker_error.h.
#define UW_ER_INVALID_NUMERIC -11026
Definition at line 57 of file broker_error.h.
#define UW_ER_INVALID_OBJECT -11019
Definition at line 50 of file broker_error.h.
#define UW_ER_INVALID_SET -11027
Definition at line 58 of file broker_error.h.
#define UW_ER_INVALID_SET_DOM -11028
Definition at line 59 of file broker_error.h.
#define UW_ER_NO_APPL_NAME -11003
Definition at line 34 of file broker_error.h.
#define UW_ER_NO_ERROR 0
Definition at line 31 of file broker_error.h.
Referenced by br_activate().
#define UW_ER_NO_FREE_UTS -11010
Definition at line 41 of file broker_error.h.
#define UW_ER_NO_MORE_MEMORY -11009
Definition at line 40 of file broker_error.h.
Referenced by main(), and uw_acl_make().
#define UW_ER_NO_REQUEST_METHOD -11001
Definition at line 32 of file broker_error.h.
#define UW_ER_NO_SESSION_UTS -11011
Definition at line 42 of file broker_error.h.
#define UW_ER_NOT_SUPPORT_SH_CMD -11031
Definition at line 62 of file broker_error.h.
#define UW_ER_NOT_SUPPORTED_REQUEST_METHOD -11002
Definition at line 33 of file broker_error.h.
#define UW_ER_OPEN_TEMP_FILE -11044
Definition at line 75 of file broker_error.h.
#define UW_ER_POST_DATA -11043
Definition at line 74 of file broker_error.h.
#define UW_ER_SCRIPT_FILE -11014
Definition at line 45 of file broker_error.h.
#define UW_ER_SERVER_INFO -11047
Definition at line 78 of file broker_error.h.
#define UW_ER_SESSION_NOT_FOUND -11012
Definition at line 43 of file broker_error.h.
#define UW_ER_SHM_OPEN -11013
Definition at line 44 of file broker_error.h.
Referenced by broker_init_shm(), and uw_shm_open().
#define UW_ER_SHM_OPEN_MAGIC -11051
Definition at line 82 of file broker_error.h.
Referenced by main(), and uw_shm_open().
#define UW_ER_SOCKET_NOT_INITIALIZED -11007
Definition at line 38 of file broker_error.h.
#define UW_ER_SQL_HANDLE_NOT_FOUND -11018
Definition at line 49 of file broker_error.h.
#define UW_ER_UNKNOWN_FILE_C -11015
Definition at line 46 of file broker_error.h.
#define UW_ER_UNKNOWN_FILE_W -11016
Definition at line 47 of file broker_error.h.
#define UW_ER_WIN_SERVER_CONF -11049
Definition at line 80 of file broker_error.h.
#define UW_MAX_ERROR_CODE -11051
Definition at line 85 of file broker_error.h.
Referenced by uw_get_error_message().
#define UW_MIN_ERROR_CODE -11000
Definition at line 84 of file broker_error.h.
Referenced by get_error_msg().
#define UW_SET_ERROR_CODE (code, os_errno) uw_set_error_code(__FILE__, __LINE__, (code), (os_errno))
Definition at line 87 of file broker_error.h.
Referenced by broker_init_shm(), init_env(), main(), uw_acl_make(), and uw_shm_open().
Function Documentation
int uw_get_error_code (void)
Definition at line 83 of file broker_error.c.
References cur_error_code.
Referenced by admin_acl_reload_cmd(), admin_acl_status_cmd(), admin_add_cmd(), admin_conf_change(), admin_drop_cmd(), admin_info_cmd(), admin_off_cmd(), admin_on_cmd(), admin_reset_cmd(), admin_restart_cmd(), admin_stop_cmd(), br_inactivate(), and main().
const char* uw_get_error_message (int error_code, int os_errno)
Definition at line 109 of file broker_error.c.
References get_error_msg(), NULL, p, and UW_MAX_ERROR_CODE.
Referenced by br_activate().
int uw_get_os_error_code (void)
Definition at line 89 of file broker_error.c.
References cur_os_errno.
Referenced by admin_acl_reload_cmd(), admin_acl_status_cmd(), admin_add_cmd(), admin_conf_change(), admin_drop_cmd(), admin_info_cmd(), admin_off_cmd(), admin_on_cmd(), admin_reset_cmd(), admin_restart_cmd(), admin_stop_cmd(), and br_inactivate().
void uw_set_error_code (const char * file_name, int line_no, int error_code, int os_errno)
Definition at line 62 of file broker_error.c.
References cur_error_code, and cur_os_errno.