CUBRID Engine: src/broker/broker_max_heap.h File Reference
broker_max_heap.h File Reference
#include <time.h>
#include "cas_common.h"
#include "broker_msg.h"
#include "cas_protocol.h"
Classes
struct t_max_heap_node
Typedefs
typedef struct t_max_heap_node T_MAX_HEAP_NODE
Functions
int max_heap_insert (T_MAX_HEAP_NODE *max_heap, int max_heap_size, T_MAX_HEAP_NODE *item)
int max_heap_delete (T_MAX_HEAP_NODE *max_heap, T_MAX_HEAP_NODE *ret)
int max_heap_change_priority (T_MAX_HEAP_NODE *max_heap, int id, int new_priority)
void max_heap_incr_priority (T_MAX_HEAP_NODE *max_heap)
Typedef Documentation
typedef struct t_max_heap_node T_MAX_HEAP_NODE
Definition at line 35 of file broker_max_heap.h.
Function Documentation
int max_heap_change_priority (T_MAX_HEAP_NODE * max_heap, int id, int new_priority)
Definition at line 49 of file broker_max_heap.c.
References i, t_max_heap_node::id, and t_max_heap_node::priority.
int max_heap_delete (T_MAX_HEAP_NODE * max_heap, T_MAX_HEAP_NODE * ret)
Definition at line 78 of file broker_max_heap.c.
References t_max_heap_node::id, and t_max_heap_node::priority.
Referenced by copy_job_info(), dispatch_thr_f(), print_job_queue(), and shard_dispatch_thr_f().
void max_heap_incr_priority (T_MAX_HEAP_NODE * max_heap)
Definition at line 107 of file broker_max_heap.c.
References i, t_max_heap_node::id, and t_max_heap_node::priority.
Referenced by dispatch_thr_f(), and shard_dispatch_thr_f().
int max_heap_insert (T_MAX_HEAP_NODE * max_heap, int max_heap_size, T_MAX_HEAP_NODE * item)
Definition at line 29 of file broker_max_heap.c.
References i, t_max_heap_node::id, and t_max_heap_node::priority.
Referenced by receiver_thr_f().