CUBRID Engine: src/broker/broker_wsa_init.c File Reference
broker_wsa_init.c File Reference
#include <winsock2.h>
#include <windows.h>
#include <winsock.h>
Functions
int wsa_initialize ()
Function Documentation
int wsa_initialize ()
Definition at line 31 of file broker_wsa_init.c.
References err.
Referenced by admin_common(), main(), net_connect_proxy(), and net_init_env().