CUBRID Engine: src/broker/broker_error.c File Reference
broker_error.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "broker_error.h"
#include "broker_filename.h"
Functions
static int get_error_msg (int err_code, char *msg_buf)
void uw_set_error_code (const char *file_name, int line_no, int error_code, int os_errno)
int uw_get_error_code (void)
int uw_get_os_error_code (void)
const char * uw_get_error_message (int error_code, int os_error_code)
Variables
static int cur_error_code = UW_ER_NO_ERROR
static int cur_os_errno = 0
Function Documentation
static int get_error_msg (int err_code, char * msg_buf) static
Definition at line 166 of file broker_error.c.
References BROKER_PATH_MAX, FID_UV_ERR_MSG, get_cubrid_file(), i, NULL, p, and UW_MIN_ERROR_CODE.
Referenced by uw_get_error_message().
int uw_get_error_code (void)
Definition at line 83 of file broker_error.c.
References cur_error_code.
Referenced by admin_acl_reload_cmd(), admin_acl_status_cmd(), admin_add_cmd(), admin_conf_change(), admin_drop_cmd(), admin_info_cmd(), admin_off_cmd(), admin_on_cmd(), admin_reset_cmd(), admin_restart_cmd(), admin_stop_cmd(), br_inactivate(), and main().
const char* uw_get_error_message (int error_code, int os_error_code)
Definition at line 109 of file broker_error.c.
References get_error_msg(), NULL, p, and UW_MAX_ERROR_CODE.
Referenced by br_activate().
int uw_get_os_error_code (void)
Definition at line 89 of file broker_error.c.
References cur_os_errno.
Referenced by admin_acl_reload_cmd(), admin_acl_status_cmd(), admin_add_cmd(), admin_conf_change(), admin_drop_cmd(), admin_info_cmd(), admin_off_cmd(), admin_on_cmd(), admin_reset_cmd(), admin_restart_cmd(), admin_stop_cmd(), and br_inactivate().
void uw_set_error_code (const char * file_name, int line_no, int error_code, int os_errno)
Definition at line 62 of file broker_error.c.
References cur_error_code, and cur_os_errno.
Variable Documentation
int cur_error_code = UW_ER_NO_ERROR static
Definition at line 41 of file broker_error.c.
Referenced by uw_get_error_code(), and uw_set_error_code().
int cur_os_errno = 0 static
Definition at line 42 of file broker_error.c.
Referenced by uw_get_os_error_code(), and uw_set_error_code().