CUBRID Engine: src/broker/broker_process_info.c File Reference
broker_process_info.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <string.h>
#include <unistd.h>
#include "cas_common.h"
#include "broker_process_info.h"
Functions
int get_psinfo (int pid, T_PSINFO *ps)
Function Documentation
int get_psinfo (int pid, T_PSINFO * ps)
Definition at line 123 of file broker_process_info.c.
Referenced by appl_info_display(), print_monitor_items(), uc_as_info(), and uc_br_info().