CUBRID Engine: src/broker/broker_process_size.h File Reference
broker_process_size.h File Reference
Functions
int getsize (int pid)
Function Documentation
int getsize (int pid)
Definition at line 596 of file broker_process_size.c.
References GETSIZE_PATH, i, and NULL.
Referenced by admin_restart_cmd(), appl_info_display(), as_activate(), broker_add_new_cas(), cas_main(), print_monitor_items(), psize_check_worker(), restart_appl_server(), shard_broker_process(), shard_cas_main(), and uc_as_info().