CUBRID Engine: src/broker/broker_filename.h File Reference
broker_filename.h File Reference
#include "porting.h"
Classes
struct t_cubrid_file_info
Macros
#define APPL_SERVER_CAS_NAME "cub_cas"
#define APPL_SERVER_CAS_ORACLE_NAME "cub_cas_oracle"
#define APPL_SERVER_CAS_MYSQL51_NAME "cub_cas_mysql51"
#define APPL_SERVER_CAS_MYSQL_NAME "cub_cas_mysql"
#define NAME_BROKER "Tbroker"
#define NAME_PROXY "cub_proxy"
#define NAME_CAS_BROKER "cub_broker"
#define CUBRID_BASE_DIR "log/broker/"
#define BROKER_PATH_MAX (PATH_MAX)
#define DEFAULT_LOG_DIR "log/broker/sql_log/"
#define DEFAULT_SLOW_LOG_DIR DEFAULT_LOG_DIR
#define DEFAULT_ERR_DIR "log/broker/error_log/"
#define DEFAULT_SHARD_PROXY_LOG_DIR "log/broker/proxy_log/"
#define DEFAULT_ACCESS_LOG_DIR "log/broker/"
#define ACCESS_LOG_DENIED_FILENAME_POSTFIX ".denied"
Typedefs
typedef enum t_cubrid_file_id T_CUBRID_FILE_ID
typedef struct t_cubrid_file_info T_CUBRID_FILE_INFO
Enumerations
enum t_cubrid_file_id {
FID_CUBRID_BROKER_CONF, FID_UV_ERR_MSG, FID_V3_OUTFILE_DIR, FID_CAS_TMPGLO_DIR,
FID_CAS_TMP_DIR, FID_VAR_DIR, FID_SOCK_DIR, FID_AS_PID_DIR,
FID_ADMIND_PID, FID_SQL_LOG_DIR, FID_SQL_LOG2_DIR, FID_ADMIND_LOG,
FID_MONITORD_LOG, FID_ER_HTML, FID_CUBRID_ERR_DIR, FID_CAS_FOR_ORACLE_DBINFO,
FID_CAS_FOR_MYSQL_DBINFO, FID_ACCESS_CONTROL_FILE, FID_SLOW_LOG_DIR, FID_SHARD_DBINFO,
FID_SHARD_PROXY_LOG_DIR, MAX_CUBRID_FILE
}
Functions
void set_cubrid_home (void)
void set_cubrid_file (T_CUBRID_FILE_ID fid, char *value)
char * get_cubrid_file (T_CUBRID_FILE_ID fid, char *buf, size_t len)
char * get_cubrid_file_ptr (T_CUBRID_FILE_ID fid)
char * get_cubrid_home (void)
const char * getenv_cubrid_broker (void)
Macro Definition Documentation
#define ACCESS_LOG_DENIED_FILENAME_POSTFIX ".denied"
Definition at line 59 of file broker_filename.h.
Referenced by cas_access_log().
#define APPL_SERVER_CAS_MYSQL51_NAME "cub_cas_mysql51"
Definition at line 33 of file broker_filename.h.
Referenced by get_appl_server_name().
#define APPL_SERVER_CAS_MYSQL_NAME "cub_cas_mysql"
Definition at line 34 of file broker_filename.h.
Referenced by get_appl_server_name(), and main().
#define APPL_SERVER_CAS_NAME "cub_cas"
Definition at line 31 of file broker_filename.h.
Referenced by get_appl_server_name(), and main().
#define APPL_SERVER_CAS_ORACLE_NAME "cub_cas_oracle"
Definition at line 32 of file broker_filename.h.
Referenced by get_appl_server_name(), and main().
#define BROKER_PATH_MAX (PATH_MAX)
Definition at line 50 of file broker_filename.h.
#define CUBRID_BASE_DIR "log/broker/"
Definition at line 44 of file broker_filename.h.
Referenced by broker_config_read_internal(), and proxy_activate().
#define DEFAULT_ACCESS_LOG_DIR "log/broker/"
Definition at line 57 of file broker_filename.h.
Referenced by broker_config_read_internal().
#define DEFAULT_ERR_DIR "log/broker/error_log/"
Definition at line 55 of file broker_filename.h.
Referenced by broker_config_read_internal().
#define DEFAULT_LOG_DIR "log/broker/sql_log/"
Definition at line 53 of file broker_filename.h.
Referenced by broker_config_read_internal(), and uc_conf_broker_add().
#define DEFAULT_SHARD_PROXY_LOG_DIR "log/broker/proxy_log/"
Definition at line 56 of file broker_filename.h.
Referenced by broker_config_read_internal().
#define DEFAULT_SLOW_LOG_DIR DEFAULT_LOG_DIR
Definition at line 54 of file broker_filename.h.
Referenced by broker_config_read_internal().
#define NAME_BROKER "Tbroker"
Definition at line 36 of file broker_filename.h.
Referenced by br_activate().
#define NAME_CAS_BROKER "cub_broker"
Definition at line 38 of file broker_filename.h.
Referenced by br_activate().
#define NAME_PROXY "cub_proxy"
Definition at line 37 of file broker_filename.h.
Referenced by proxy_activate_internal(), and run_proxy_server().
Typedef Documentation
typedef enum t_cubrid_file_id T_CUBRID_FILE_ID
Definition at line 86 of file broker_filename.h.
typedef struct t_cubrid_file_info T_CUBRID_FILE_INFO
Definition at line 88 of file broker_filename.h.
Enumeration Type Documentation
enum t_cubrid_file_id
Enumerator
FID_CUBRID_BROKER_CONF
FID_UV_ERR_MSG
FID_V3_OUTFILE_DIR
FID_CAS_TMPGLO_DIR
FID_CAS_TMP_DIR
FID_VAR_DIR
FID_SOCK_DIR
FID_AS_PID_DIR
FID_ADMIND_PID
FID_SQL_LOG_DIR
FID_SQL_LOG2_DIR
FID_ADMIND_LOG
FID_MONITORD_LOG
FID_ER_HTML
FID_CUBRID_ERR_DIR
FID_CAS_FOR_ORACLE_DBINFO
FID_CAS_FOR_MYSQL_DBINFO
FID_ACCESS_CONTROL_FILE
FID_SLOW_LOG_DIR
FID_SHARD_DBINFO
FID_SHARD_PROXY_LOG_DIR
MAX_CUBRID_FILE
Definition at line 61 of file broker_filename.h.
Function Documentation
char* get_cubrid_file (T_CUBRID_FILE_ID fid, char * buf, size_t len)
Definition at line 195 of file broker_filename.c.
References assert, BROKER_PATH_MAX, cubrid_Dir, envvar_confdir_file(), envvar_get(), envvar_logdir_file(), envvar_tmpdir_file(), envvar_vardir_file(), FID_ADMIND_LOG, FID_ADMIND_PID, FID_AS_PID_DIR, FID_CAS_FOR_MYSQL_DBINFO, FID_CAS_FOR_ORACLE_DBINFO, FID_CAS_TMP_DIR, FID_CAS_TMPGLO_DIR, FID_CUBRID_BROKER_CONF, FID_CUBRID_ERR_DIR, FID_ER_HTML, FID_MONITORD_LOG, FID_SHARD_DBINFO, FID_SHARD_PROXY_LOG_DIR, FID_SLOW_LOG_DIR, FID_SOCK_DIR, FID_SQL_LOG2_DIR, FID_SQL_LOG_DIR, FID_UV_ERR_MSG, FID_V3_OUTFILE_DIR, FID_VAR_DIR, NULL, set_cubrid_home(), and strlen.
Referenced by admin_start_cmd(), as_db_err_log_set(), broker_config_read(), cas_log_query_plan_file(), cfg_get_dbinfo(), cfg_read_dbinfo(), get_as_slow_log_filename(), get_as_sql_log_filename(), get_error_msg(), get_master_shm_id(), make_error_log_filename(), make_sql_log_filename(), sql_log2_init(), ut_get_as_pid_name(), ut_get_as_port_name(), ut_get_broker_port_name(), and ut_get_proxy_port_name().
char* get_cubrid_file_ptr (T_CUBRID_FILE_ID fid)
Definition at line 189 of file broker_filename.c.
References t_cubrid_file_info::file_name.
Referenced by access_control_set_shm(), and admin_acl_reload_cmd().
char* get_cubrid_home (void)
Definition at line 92 of file broker_filename.c.
References cubrid_Dir, and set_cubrid_home().
Referenced by dir_repath(), and set_cubrid_file().
const char* getenv_cubrid_broker (void)
Definition at line 313 of file broker_filename.c.
References envvar_root(), and p.
Referenced by set_cubrid_home().
void set_cubrid_file (T_CUBRID_FILE_ID fid, char * value)
Definition at line 103 of file broker_filename.c.
References assert, BROKER_PATH_MAX, envvar_confdir_file(), FID_ACCESS_CONTROL_FILE, FID_AS_PID_DIR, FID_CAS_TMP_DIR, FID_CAS_TMPGLO_DIR, FID_CUBRID_ERR_DIR, FID_SLOW_LOG_DIR, FID_SOCK_DIR, FID_SQL_LOG2_DIR, FID_SQL_LOG_DIR, FID_V3_OUTFILE_DIR, FID_VAR_DIR, t_cubrid_file_info::file_name, get_cubrid_home(), IS_ABS_PATH, NULL, and strlen.
Referenced by access_control_set_shm(), admin_acl_reload_cmd(), cas_init(), cas_log_open(), cas_main(), cas_slow_log_open(), and main().
void set_cubrid_home (void)
Definition at line 72 of file broker_filename.c.
References assert, BROKER_PATH_MAX, cubrid_Dir, dirname(), getenv_cubrid_broker(), and p.
Referenced by get_cubrid_file(), get_cubrid_home(), and main().