CUBRID Engine: src/broker/broker_access_list.c File Reference
broker_access_list.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "broker_access_list.h"
#include "broker_error.h"
#include "broker_util.h"
Functions
static int ip_comp (const void *arg1, const void *arg2)
static int convert_ip (char *str, T_IP *ip_addr)
static int ipstr2int (char *str, char **endp, char next_char)
int uw_acl_make (char *acl_file)
int uw_acl_check (unsigned char *ip_addr)
Variables
T_ACL * v3_acl = NULL
Function Documentation
static int convert_ip (char * str, T_IP * ip_addr) static
Definition at line 149 of file broker_access_list.c.
References i, t_ip::ip, t_ip::ip_length, and ipstr2int().
Referenced by uw_acl_make().
static int ip_comp (const void * arg1, const void * arg2) static
Definition at line 140 of file broker_access_list.c.
References t_ip::ip_length.
Referenced by uw_acl_make().
static int ipstr2int (char * str, char ** endp, char next_char) static
Definition at line 188 of file broker_access_list.c.
References str_to_int32().
Referenced by convert_ip().
int uw_acl_check (unsigned char * ip_addr)
Definition at line 114 of file broker_access_list.c.
References t_acl::acl, i, t_ip::ip, t_ip::ip_length, IPV4_LENGTH_MAX, and t_acl::num_acl.
Referenced by receiver_thr_f().
int uw_acl_make (char * acl_file)
Definition at line 41 of file broker_access_list.c.
References t_acl::acl, convert_ip(), ip_comp(), NULL, t_acl::num_acl, p, trim(), UW_ER_NO_MORE_MEMORY, and UW_SET_ERROR_CODE.
Referenced by main().
Variable Documentation
T_ACL* v3_acl = NULL
Definition at line 38 of file broker_access_list.c.
Referenced by receiver_thr_f().