CUBRID Engine: src/broker/broker_list.c File Reference
broker_list.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "cas_common.h"
#include "broker_list.h"
Functions
static T_LIST * delete_node (T_LIST *head, T_LIST *del_node, void(*node_dealloc)(T_LIST *))
static int true_func (void *key, void *value)
static void swap_node (T_LIST *node1, T_LIST *node2)
int link_list_add (T_LIST **cur_head, void *add_key, void *add_val, int(*assign_func)(T_LIST *, void *, void *))
T_LIST * link_list_find (T_LIST *head, void *key, void *val, int(*key_cmp_func)(void *, void *), int(*val_cmp_func)(void *, void *))
int link_list_node_delete (T_LIST **cur_head, void *key, int(*cmp_func)(void *, void *), void(*node_dealloc)(T_LIST *))
int link_list_node_delete2 (T_LIST **cur_head, void *key, void *value, int(*key_cmp_func)(void *, void *), int(*val_cmp_func)(void *, void *), void(*node_dealloc)(T_LIST *))
int link_list_delete (T_LIST **cur_head, void(*node_dealloc)(T_LIST *))
void * link_list_traverse (T_LIST *head, void *(*traverse_func)(T_LIST *, void *))
int link_list_default_assign_func (T_LIST *node, void *key, void *value)
int link_list_default_compare_func (void *key, void *value)
Function Documentation
static T_LIST * delete_node (T_LIST * head, T_LIST * del_node, void(*)(T_LIST *) node_dealloc) static
Definition at line 280 of file broker_list.c.
References FREE_MEM, free_node(), list_tag::next, NULL, and swap_node().
Referenced by link_list_delete(), link_list_node_delete(), and link_list_node_delete2().
int link_list_add (T_LIST ** cur_head, void * add_key, void * add_val, int(*)(T_LIST *, void *, void *) assign_func)
Definition at line 63 of file broker_list.c.
References error(), FREE_MEM, and NULL.
Referenced by uw_shm_open().
int link_list_default_assign_func (T_LIST * node, void * key, void * value)
Definition at line 263 of file broker_list.c.
References list_tag::key, and list_tag::value.
int link_list_default_compare_func (void * key, void * value)
Definition at line 271 of file broker_list.c.
int link_list_delete (T_LIST ** cur_head, void(*)(T_LIST *) node_dealloc)
Definition at line 230 of file broker_list.c.
References delete_node(), and NULL.
T_LIST* link_list_find (T_LIST * head, void * key, void * val, int(*)(void *, void *) key_cmp_func, int(*)(void *, void *) val_cmp_func)
Definition at line 112 of file broker_list.c.
References list_tag::key, list_tag::next, NULL, true_func(), and list_tag::value.
Referenced by link_list_node_delete(), and link_list_node_delete2().
int link_list_node_delete (T_LIST ** cur_head, void * key, int(*)(void *, void *) cmp_func, void(*)(T_LIST *) node_dealloc)
Definition at line 156 of file broker_list.c.
References delete_node(), link_list_find(), and NULL.
Referenced by shard_shm_set_shard_conn_info().
int link_list_node_delete2 (T_LIST ** cur_head, void * key, void * value, int(*)(void *, void *) key_cmp_func, int(*)(void *, void *) val_cmp_func, void(*)(T_LIST *) node_dealloc)
Definition at line 197 of file broker_list.c.
References delete_node(), link_list_find(), and NULL.
void* link_list_traverse (T_LIST * head, void *(*)(T_LIST *, void *) traverse_func)
Definition at line 244 of file broker_list.c.
References list_tag::next, and NULL.
static void swap_node (T_LIST * node1, T_LIST * node2) static
Definition at line 323 of file broker_list.c.
Referenced by delete_node(), and qo_analyze_term().
static int true_func (void * key, void * value) static
Definition at line 317 of file broker_list.c.
Referenced by link_list_find().