CUBRID Engine: src/broker/broker_admin_so.h File Reference
broker_admin_so.h File Reference
#include "porting.h"
#include <time.h>
Classes
struct t_job_info
struct t_as_info
struct t_br_info
struct t_uc_conf_item
struct t_br_conf
struct t_uc_conf
Macros
#define DLL_EXPORT
#define FLAG_ON 1
#define FLAG_OFF 0
#define FLAG_SUSPEND 2
#define FLAG_READ_WRITE 0
#define FLAG_READ_ONLY 1
#define FLAG_SLAVE_ONLY 2
#define SRV_CON_DBNAME_SIZE 32
Typedefs
typedef enum t_as_status T_AS_STATUS
typedef struct t_job_info T_JOB_INFO
typedef struct t_as_info T_AS_INFO
typedef struct t_br_info T_BR_INFO
typedef struct t_uc_conf_item T_UC_CONF_ITEM
typedef struct t_br_conf T_BR_CONF
typedef struct t_uc_conf T_UC_CONF
typedef char *(* T_UC_VERSION_F) (void)
typedef int(* T_UC_START_F) (char *)
typedef int(* T_UC_STOP_F) (char *)
typedef int(* T_UC_ADD_F) (char *, char *)
typedef int(* T_UC_RESTART_F) (char *, int, char *)
typedef int(* T_UC_DROP_F) (char *, char *)
typedef int(* T_UC_ON_F) (char *, char *)
typedef int(* T_UC_OFF_F) (char *, char *)
typedef int(* T_UC_SUSPEND_F) (char *, char *)
typedef int(* T_UC_RESUME_F) (char *, char *)
typedef int(* T_UC_JOB_FIRST_F) (char *, int, char *)
typedef int(* T_UC_JOB_QUEUE_F) (char *, char *)
typedef int(* T_UC_AS_INFO_F) (char *, T_AS_INFO **, T_JOB_INFO **, int *, char *)
typedef int(* T_UC_BR_INFO_F) (T_BR_INFO **, char *)
typedef void(* T_UC_INFO_FREE_F) (void *)
typedef int(* T_UC_UNICAS_CONF_F) (T_UC_CONF *, int *, char *)
typedef void(* T_UC_UNICAS_CONF_FREE_F) (T_UC_CONF *)
typedef int(* T_UC_CONF_BROKER_ADD_F) (T_UC_CONF *, char *, char *)
typedef void(* T_UC_CHANGE_CONFIG_F) (T_UC_CONF *, const char *, const char *, const char *)
typedef int(* T_UC_CHANGER_F) (char *, char *, char *, char *)
typedef int(* T_UC_DEL_CAS_LOG_F) (char *, int, char *)
typedef int(* T_UC_GET_ACTIVE_SESSION_WITH_OPENED_SHM) (void *, char *)
typedef void *(* T_UCA_BROKER_SHM_OPEN) (char *err_msg)
typedef int(* T_UCA_GET_BR_NUM_WITH_OPENED_SHM) (void *shm_br, char *err_msg)
typedef int(* T_UCA_GET_BR_NAME_WITH_OPENED_SHM) (void *shm_br, int br_index, char *name, int buffer_size, char *err_msg)
typedef void *(* T_UCA_AS_SHM_OPEN) (void *shm_br, int br_index, char *err_msg)
typedef int(* T_UCA_GET_AS_NUM_WITH_OPENED_SHM) (void *shm_br, int br_index, char *err_msg)
typedef int(* T_UCA_GET_AS_REQS_RECEIVED_WITH_OPENED_SHM) (void *shm_as, long long array[], int array_size, char *err_msg)
typedef int(* T_UCA_GET_AS_TRAN_PROCESSED_WITH_OPENED_SHM) (void *shm_as, long long array[], int array_size, char *err_msg)
typedef int(* T_UCA_GET_AS_QUERY_PROCESSED_WITH_OPENED_SHM) (void *shm_as, long long array[], int array_size, char *err_msg)
typedef int(* T_UCA_SHM_DETACH) (void *p)
Enumerations
enum t_as_status {
AS_STATUS_IDLE, AS_STATUS_BUSY, AS_STATUS_RESTART, AS_STATUS_CLIENT_WAIT,
AS_STATUS_CLOSE_WAIT
}
Functions
DLL_EXPORT const char * uc_version (void)
DLL_EXPORT int uc_start (char *err_msg)
DLL_EXPORT int uc_stop (char *err_msg)
DLL_EXPORT int uc_add (const char *br_name, char *err_msg)
DLL_EXPORT int uc_restart (const char *br_name, int as_index, char *err_msg)
DLL_EXPORT int uc_drop (const char *br_name, char *err_msg)
DLL_EXPORT int uc_on (const char *br_name, char *err_msg)
DLL_EXPORT int uc_off (const char *br_name, char *err_msg)
DLL_EXPORT int uc_as_info (const char *br_name, T_AS_INFO **ret_as_info, T_JOB_INFO **job_info, int *num_job, char *err_msg)
DLL_EXPORT void uc_info_free (void *info)
DLL_EXPORT int uc_br_info (T_BR_INFO **ret_br_info, char *err_msg)
DLL_EXPORT int uc_unicas_conf (T_UC_CONF *unicas_conf, int *ret_mst_shmid, char *err_msg)
DLL_EXPORT void uc_unicas_conf_free (T_UC_CONF *unicas_conf)
DLL_EXPORT int uc_conf_broker_add (T_UC_CONF *unicas_conf, const char *br_name, char *err_msg)
DLL_EXPORT void uc_change_config (T_UC_CONF *unicas_conf, const char *br_name, const char *name, const char *value)
DLL_EXPORT int uc_changer (const char *br_name, const char *name, const char *value, char *err_msg)
DLL_EXPORT int uc_cas_changer (const char *br_name, const char *name, const char *value, int as_number, char *err_msg)
DLL_EXPORT int uc_del_cas_log (const char *br_name, int asid, char *errmsg)
DLL_EXPORT int uc_get_active_session_with_opened_shm (void *, char *)
DLL_EXPORT void * uc_broker_shm_open (char *err_msg)
DLL_EXPORT int uc_get_br_num_with_opened_shm (void *shm_br, char *err_msg)
DLL_EXPORT int uc_get_br_name_with_opened_shm (void *shm_br, int br_index, char *name, int buffer_size, char *err_msg)
DLL_EXPORT void * uc_as_shm_open (void *shm_br, int br_index, char *err_msg)
DLL_EXPORT int uc_get_as_num_with_opened_shm (void *shm_br, int br_index, char *err_msg)
DLL_EXPORT int uc_get_as_reqs_received_with_opened_shm (void *shm_as, long long array[], int array_size, char *err_msg)
DLL_EXPORT int uc_get_as_tran_processed_with_opened_shm (void *shm_as, long long array[], int array_size, char *err_msg)
DLL_EXPORT int uc_get_as_query_processed_with_opened_shm (void *shm_as, long long array[], int array_size, char *err_msg)
DLL_EXPORT void uc_shm_detach (void *p)
Macro Definition Documentation
#define DLL_EXPORT
Definition at line 36 of file broker_admin_so.h.
Referenced by uc_add(), uc_as_info(), uc_as_shm_open(), uc_br_info(), uc_broker_shm_open(), uc_cas_changer(), uc_change_config(), uc_changer(), uc_conf_broker_add(), uc_drop(), uc_get_active_session_with_opened_shm(), uc_get_as_num_with_opened_shm(), uc_get_as_query_processed_with_opened_shm(), uc_get_as_reqs_received_with_opened_shm(), uc_get_as_tran_processed_with_opened_shm(), uc_get_br_name_with_opened_shm(), uc_get_br_num_with_opened_shm(), uc_info_free(), uc_off(), uc_on(), uc_restart(), uc_shm_detach(), uc_start(), uc_stop(), uc_unicas_conf(), uc_unicas_conf_free(), and uc_version().
#define FLAG_OFF 0
Definition at line 40 of file broker_admin_so.h.
#define FLAG_ON 1
Definition at line 39 of file broker_admin_so.h.
#define FLAG_READ_ONLY 1
Definition at line 44 of file broker_admin_so.h.
#define FLAG_READ_WRITE 0
Definition at line 43 of file broker_admin_so.h.
#define FLAG_SLAVE_ONLY 2
Definition at line 45 of file broker_admin_so.h.
#define FLAG_SUSPEND 2
Definition at line 41 of file broker_admin_so.h.
#define SRV_CON_DBNAME_SIZE 32
Definition at line 48 of file broker_admin_so.h.
Referenced by cas_main(), proxy_process_client_register(), and server_monitor_thr_f().
Typedef Documentation
typedef struct t_as_info T_AS_INFO
Definition at line 72 of file broker_admin_so.h.
typedef enum t_as_status T_AS_STATUS
Definition at line 59 of file broker_admin_so.h.
typedef struct t_br_conf T_BR_CONF
Definition at line 150 of file broker_admin_so.h.
typedef struct t_br_info T_BR_INFO
Definition at line 101 of file broker_admin_so.h.
typedef struct t_job_info T_JOB_INFO
Definition at line 61 of file broker_admin_so.h.
typedef int(* T_UC_ADD_F) (char *, char *)
Definition at line 169 of file broker_admin_so.h.
typedef int(* T_UC_AS_INFO_F) (char *, T_AS_INFO **, T_JOB_INFO **, int *, char *)
Definition at line 178 of file broker_admin_so.h.
typedef int(* T_UC_BR_INFO_F) (T_BR_INFO **, char *)
Definition at line 179 of file broker_admin_so.h.
typedef void(* T_UC_CHANGE_CONFIG_F) (T_UC_CONF *, const char *, const char *, const char *)
Definition at line 184 of file broker_admin_so.h.
typedef int(* T_UC_CHANGER_F) (char *, char *, char *, char *)
Definition at line 185 of file broker_admin_so.h.
typedef struct t_uc_conf T_UC_CONF
Definition at line 157 of file broker_admin_so.h.
typedef int(* T_UC_CONF_BROKER_ADD_F) (T_UC_CONF *, char *, char *)
Definition at line 183 of file broker_admin_so.h.
typedef struct t_uc_conf_item T_UC_CONF_ITEM
Definition at line 143 of file broker_admin_so.h.
typedef int(* T_UC_DEL_CAS_LOG_F) (char *, int, char *)
Definition at line 186 of file broker_admin_so.h.
typedef int(* T_UC_DROP_F) (char *, char *)
Definition at line 171 of file broker_admin_so.h.
typedef int(* T_UC_GET_ACTIVE_SESSION_WITH_OPENED_SHM) (void *, char *)
Definition at line 187 of file broker_admin_so.h.
typedef void(* T_UC_INFO_FREE_F) (void *)
Definition at line 180 of file broker_admin_so.h.
typedef int(* T_UC_JOB_FIRST_F) (char *, int, char *)
Definition at line 176 of file broker_admin_so.h.
typedef int(* T_UC_JOB_QUEUE_F) (char *, char *)
Definition at line 177 of file broker_admin_so.h.
typedef int(* T_UC_OFF_F) (char *, char *)
Definition at line 173 of file broker_admin_so.h.
typedef int(* T_UC_ON_F) (char *, char *)
Definition at line 172 of file broker_admin_so.h.
typedef int(* T_UC_RESTART_F) (char *, int, char *)
Definition at line 170 of file broker_admin_so.h.
typedef int(* T_UC_RESUME_F) (char *, char *)
Definition at line 175 of file broker_admin_so.h.
typedef int(* T_UC_START_F) (char *)
Definition at line 167 of file broker_admin_so.h.
typedef int(* T_UC_STOP_F) (char *)
Definition at line 168 of file broker_admin_so.h.
typedef int(* T_UC_SUSPEND_F) (char *, char *)
Definition at line 174 of file broker_admin_so.h.
typedef int(* T_UC_UNICAS_CONF_F) (T_UC_CONF *, int *, char *)
Definition at line 181 of file broker_admin_so.h.
typedef void(* T_UC_UNICAS_CONF_FREE_F) (T_UC_CONF *)
Definition at line 182 of file broker_admin_so.h.
typedef char*(* T_UC_VERSION_F) (void)
Definition at line 166 of file broker_admin_so.h.
typedef void*(* T_UCA_AS_SHM_OPEN) (void *shm_br, int br_index, char *err_msg)
Definition at line 192 of file broker_admin_so.h.
typedef void*(* T_UCA_BROKER_SHM_OPEN) (char *err_msg)
Definition at line 188 of file broker_admin_so.h.
typedef int(* T_UCA_GET_AS_NUM_WITH_OPENED_SHM) (void *shm_br, int br_index, char *err_msg)
Definition at line 193 of file broker_admin_so.h.
typedef int(* T_UCA_GET_AS_QUERY_PROCESSED_WITH_OPENED_SHM) (void *shm_as, long long array[], int array_size, char *err_msg)
Definition at line 198 of file broker_admin_so.h.
typedef int(* T_UCA_GET_AS_REQS_RECEIVED_WITH_OPENED_SHM) (void *shm_as, long long array[], int array_size, char *err_msg)
Definition at line 194 of file broker_admin_so.h.
typedef int(* T_UCA_GET_AS_TRAN_PROCESSED_WITH_OPENED_SHM) (void *shm_as, long long array[], int array_size, char *err_msg)
Definition at line 196 of file broker_admin_so.h.
typedef int(* T_UCA_GET_BR_NAME_WITH_OPENED_SHM) (void *shm_br, int br_index, char *name, int buffer_size, char *err_msg)
Definition at line 190 of file broker_admin_so.h.
typedef int(* T_UCA_GET_BR_NUM_WITH_OPENED_SHM) (void *shm_br, char *err_msg)
Definition at line 189 of file broker_admin_so.h.
typedef int(* T_UCA_SHM_DETACH) (void *p)
Definition at line 200 of file broker_admin_so.h.
Enumeration Type Documentation
enum t_as_status
Enumerator
AS_STATUS_IDLE
AS_STATUS_BUSY
AS_STATUS_RESTART
AS_STATUS_CLIENT_WAIT
AS_STATUS_CLOSE_WAIT
Definition at line 51 of file broker_admin_so.h.
Function Documentation
DLL_EXPORT int uc_add (const char * br_name, char * err_msg)
Definition at line 369 of file broker_admin_so.c.
References admin_add_cmd(), admin_common(), admin_log_write(), BROKER_PATH_MAX, CP_ADMIN_ERR_MSG, DLL_EXPORT, MAX_BROKER_NUM, and NULL.
DLL_EXPORT int uc_as_info (const char * br_name, T_AS_INFO ** ret_as_info, T_JOB_INFO ** job_info, int * num_job, char * err_msg)
Definition at line 494 of file broker_admin_so.c.
References admin_common(), t_broker_info::appl_server, t_broker_info::appl_server_max_num, t_broker_info::appl_server_shm_id, as_info, t_shm_appl_server::as_info, t_as_info::as_port, AS_STATUS_BUSY, AS_STATUS_CLIENT_WAIT, AS_STATUS_CLOSE_WAIT, AS_STATUS_IDLE, AS_STATUS_RESTART, br_index, t_shm_broker::br_info, BROKER_PATH_MAX, t_appl_server_info::cas_clt_ip, t_appl_server_info::clt_appl_name, t_appl_server_info::clt_req_path_info, t_appl_server_info::con_status, CON_STATUS_OUT_TRAN, copy_job_info(), t_psinfo::cpu_time, t_as_info::cpu_time, t_appl_server_info::database_host, t_appl_server_info::database_name, database_name, DLL_EXPORT, get_psinfo(), getsize(), i, t_max_heap_node::id, IS_APPL_SERVER_TYPE_CAS, t_shm_appl_server::job_queue, JOB_QUEUE_MAX_SIZE, t_as_info::last_access_time, t_appl_server_info::last_access_time, t_as_info::last_connect_time, t_appl_server_info::last_connect_time, t_appl_server_info::log_msg, MAX_BROKER_NUM, t_broker_info::name, NULL, t_shm_broker::num_broker, t_as_info::num_error_queries, t_appl_server_info::num_error_queries, t_as_info::num_interrupts, t_appl_server_info::num_interrupts, t_as_info::num_long_queries, t_appl_server_info::num_long_queries, t_as_info::num_long_transactions, t_appl_server_info::num_long_transactions, t_as_info::num_queries_processed, t_appl_server_info::num_queries_processed, t_as_info::num_request, t_appl_server_info::num_request, t_as_info::num_requests_received, t_appl_server_info::num_requests_received, t_psinfo::num_thr, t_as_info::num_thr, t_as_info::num_transactions_processed, t_appl_server_info::num_transactions_processed, t_psinfo::pcpu, t_as_info::pcpu, t_as_info::pid, t_appl_server_info::pid, pid, t_as_info::psize, t_as_info::service_flag, t_appl_server_info::service_flag, SERVICE_ON, shm_appl, SHM_APPL_SERVER, shm_br, SHM_BROKER, SHM_MODE_ADMIN, t_as_info::status, TRUE, uc_info_free(), ut_get_ipv4_string(), t_appl_server_info::uts_status, UTS_STATUS_BUSY, UTS_STATUS_RESTART, uw_shm_detach(), and uw_shm_open().
DLL_EXPORT void* uc_as_shm_open (void * shm_br, int br_index, char * err_msg)
Definition at line 208 of file broker_admin_so.c.
References appl_server_shm_id, DLL_EXPORT, NULL, SHM_APPL_SERVER, SHM_MODE_MONITOR, and uw_shm_open().
DLL_EXPORT int uc_br_info (T_BR_INFO ** ret_br_info, char * err_msg)
Definition at line 682 of file broker_admin_so.c.
References t_br_info::access_list_flag, t_broker_info::access_log_file, t_br_info::access_mode, t_broker_info::access_mode, t_broker_info::acl_file, admin_common(), t_broker_info::appl_server, t_broker_info::appl_server_hard_limit, t_broker_info::appl_server_max_num, t_broker_info::appl_server_max_size, t_broker_info::appl_server_min_num, t_broker_info::appl_server_num, t_broker_info::appl_server_shm_id, t_br_info::as_hard_limit, t_shm_appl_server::as_info, t_br_info::as_max_size, t_broker_info::auto_add_appl_server, t_br_info::auto_add_flag, t_shm_broker::br_info, BROKER_PATH_MAX, t_psinfo::cpu_time, t_br_info::cpu_time, DLL_EXPORT, get_as_type_str(), get_psinfo(), i, t_max_heap_node::id, t_shm_appl_server::job_queue, t_br_info::keep_connection, t_shm_appl_server::keep_connection, t_broker_info::log_backup, t_br_info::log_backup_flag, t_br_info::long_query_time, t_broker_info::long_query_time, t_br_info::long_transaction_time, t_broker_info::long_transaction_time, t_br_info::max_as, MAX_BROKER_NUM, t_br_info::min_as, t_broker_info::name, NULL, t_br_info::num_as, t_shm_broker::num_broker, t_br_info::num_busy_count, t_broker_info::num_busy_count, t_appl_server_info::num_error_queries, t_br_info::num_error_query, t_br_info::num_interrupts, t_appl_server_info::num_interrupts, t_br_info::num_job_q, t_appl_server_info::num_long_queries, t_br_info::num_long_query, t_br_info::num_long_tran, t_appl_server_info::num_long_transactions, t_appl_server_info::num_queries_processed, t_br_info::num_query, t_br_info::num_req, t_appl_server_info::num_request, t_psinfo::num_thr, t_br_info::num_thr, t_br_info::num_tran, t_appl_server_info::num_transactions_processed, ON, p, t_psinfo::pcpu, t_br_info::pcpu, t_br_info::pid, t_broker_info::pid, pid, t_br_info::port, t_broker_info::port, t_broker_info::service_flag, t_br_info::session_timeout, t_broker_info::session_timeout, SET_FLAG, shm_appl, SHM_APPL_SERVER, shm_br, SHM_BROKER, t_br_info::shm_id, SHM_MODE_ADMIN, t_br_info::slow_log_mode, t_broker_info::slow_log_mode, t_broker_info::source_env, t_br_info::source_env_flag, t_br_info::sql_log_mode, t_broker_info::sql_log_mode, t_br_info::status, t_br_info::time_to_kill, t_broker_info::time_to_kill, uc_info_free(), uw_shm_detach(), and uw_shm_open().
DLL_EXPORT void* uc_broker_shm_open (char * err_msg)
Definition at line 164 of file broker_admin_so.c.
References admin_common(), BROKER_PATH_MAX, DLL_EXPORT, MAX_BROKER_NUM, NULL, SHM_BROKER, SHM_MODE_ADMIN, and uw_shm_open().
DLL_EXPORT int uc_cas_changer (const char * br_name, const char * name, const char * value, int as_number, char * err_msg)
Definition at line 983 of file broker_admin_so.c.
References DLL_EXPORT, and uc_changer_internal().
DLL_EXPORT void uc_change_config (T_UC_CONF * unicas_conf, const char * br_name, const char * name, const char * value)
Definition at line 942 of file broker_admin_so.c.
References t_uc_conf::br_conf, change_conf_as_type(), DLL_EXPORT, FREE_MEM, get_as_type(), get_broker_name(), i, t_br_conf::item, t_uc_conf_item::name, NULL, t_br_conf::num, t_uc_conf::num_broker, strdup(), UC_CONF_PARAM_APPL_SERVER, and t_uc_conf_item::value.
DLL_EXPORT int uc_changer (const char * br_name, const char * name, const char * value, char * err_msg)
Definition at line 977 of file broker_admin_so.c.
References DLL_EXPORT, and uc_changer_internal().
DLL_EXPORT int uc_conf_broker_add (T_UC_CONF * unicas_conf, const char * br_name, char * err_msg)
Definition at line 887 of file broker_admin_so.c.
References APPL_SERVER_CAS, t_uc_conf::br_conf, DEFAULT_LOG_DIR, DEFAULT_LONG_QUERY_TIME, DEFAULT_LONG_TRANSACTION_TIME, DEFAULT_SERVER_MAX_SIZE, DEFAULT_SQL_LOG_MAX_SIZE, DEFAULT_TIME_TO_KILL, DLL_EXPORT, FMT_D, FMT_X, get_as_type_str(), t_br_conf::item, KEEP_CON_DEFAULT, MAX_NUM_CONF, NULL, t_br_conf::num, t_uc_conf::num_broker, OFF, ON, SET_CONF_ITEM_INT, SET_CONF_ITEM_KEEP_CON, SET_CONF_ITEM_ONOFF, SET_CONF_ITEM_SQL_LOG_MODE, SET_CONF_ITEM_STR, SQL_LOG_MODE_ERROR, UC_CONF_PARAM_ACCESS_LIST, UC_CONF_PARAM_ACCESS_LOG, UC_CONF_PARAM_APPL_SERVER, UC_CONF_PARAM_APPL_SERVER_MAX_SIZE, UC_CONF_PARAM_APPL_SERVER_SHM_ID, UC_CONF_PARAM_AUTO_ADD_APPL_SERVER, UC_CONF_PARAM_BROKER_NAME, UC_CONF_PARAM_BROKER_PORT, UC_CONF_PARAM_JOB_QUEUE_SIZE, UC_CONF_PARAM_KEEP_CONNECTION, UC_CONF_PARAM_LOG_BACKUP, UC_CONF_PARAM_LOG_DIR, UC_CONF_PARAM_LONG_QUERY_TIME, UC_CONF_PARAM_LONG_TRANSACTION_TIME, UC_CONF_PARAM_MAX_NUM_APPL_SERVER, UC_CONF_PARAM_MAX_STRING_LENGTH, UC_CONF_PARAM_MIN_NUM_APPL_SERVER, UC_CONF_PARAM_SERVICE, UC_CONF_PARAM_SESSION_TIMEOUT, UC_CONF_PARAM_SOURCE_ENV, UC_CONF_PARAM_SQL_LOG, UC_CONF_PARAM_SQL_LOG_MAX_SIZE, UC_CONF_PARAM_STRIPPED_COLUMN_NAME, and UC_CONF_PARAM_TIME_TO_KILL.
DLL_EXPORT int uc_del_cas_log (const char * br_name, int asid, char * errmsg)
Definition at line 989 of file broker_admin_so.c.
References admin_common(), admin_del_cas_log(), BROKER_PATH_MAX, MAX_BROKER_NUM, and NULL.
DLL_EXPORT int uc_drop (const char * br_name, char * err_msg)
Definition at line 419 of file broker_admin_so.c.
References admin_common(), admin_drop_cmd(), admin_log_write(), CP_ADMIN_ERR_MSG, DLL_EXPORT, MAX_BROKER_NUM, and NULL.
DLL_EXPORT int uc_get_active_session_with_opened_shm (void * , char *)
Definition at line 260 of file broker_admin_so.c.
References t_shm_broker::br_info, CHECK_SHARED_MEMORY, DLL_EXPORT, i, t_shm_broker::num_broker, t_broker_info::num_busy_count, ON, t_broker_info::service_flag, and shm_br.
DLL_EXPORT int uc_get_as_num_with_opened_shm (void * shm_br, int br_index, char * err_msg)
Definition at line 231 of file broker_admin_so.c.
References br_index, CHECK_SHARED_MEMORY, and DLL_EXPORT.
DLL_EXPORT int uc_get_as_query_processed_with_opened_shm (void * shm_as, long long array[], int array_size, char * err_msg)
Definition at line 294 of file broker_admin_so.c.
References CHECK_SHARED_MEMORY, DLL_EXPORT, and i.
DLL_EXPORT int uc_get_as_reqs_received_with_opened_shm (void * shm_as, long long array[], int array_size, char * err_msg)
Definition at line 238 of file broker_admin_so.c.
References CHECK_SHARED_MEMORY, DLL_EXPORT, and i.
DLL_EXPORT int uc_get_as_tran_processed_with_opened_shm (void * shm_as, long long array[], int array_size, char * err_msg)
Definition at line 279 of file broker_admin_so.c.
References CHECK_SHARED_MEMORY, DLL_EXPORT, and i.
DLL_EXPORT int uc_get_br_name_with_opened_shm (void * shm_br, int br_index, char * name, int buffer_size, char * err_msg)
Definition at line 191 of file broker_admin_so.c.
References CHECK_SHARED_MEMORY, DLL_EXPORT, and NULL.
DLL_EXPORT int uc_get_br_num_with_opened_shm (void * shm_br, char * err_msg)
Definition at line 184 of file broker_admin_so.c.
References CHECK_SHARED_MEMORY, and DLL_EXPORT.
DLL_EXPORT void uc_info_free (void * info)
Definition at line 676 of file broker_admin_so.c.
References DLL_EXPORT, and FREE_MEM.
Referenced by uc_as_info(), and uc_br_info().
DLL_EXPORT int uc_off (const char * br_name, char * err_msg)
Definition at line 469 of file broker_admin_so.c.
References admin_common(), admin_log_write(), admin_off_cmd(), BROKER_PATH_MAX, CP_ADMIN_ERR_MSG, DLL_EXPORT, MAX_BROKER_NUM, and NULL.
DLL_EXPORT int uc_on (const char * br_name, char * err_msg)
Definition at line 444 of file broker_admin_so.c.
References admin_common(), admin_log_write(), admin_on_cmd(), BROKER_PATH_MAX, CP_ADMIN_ERR_MSG, DLL_EXPORT, MAX_BROKER_NUM, and NULL.
DLL_EXPORT int uc_restart (const char * br_name, int as_index, char * err_msg)
Definition at line 394 of file broker_admin_so.c.
References admin_common(), admin_log_write(), admin_restart_cmd(), BROKER_PATH_MAX, CP_ADMIN_ERR_MSG, DLL_EXPORT, MAX_BROKER_NUM, and NULL.
DLL_EXPORT void uc_shm_detach (void * p)
Definition at line 309 of file broker_admin_so.c.
References DLL_EXPORT, and uw_shm_detach().
DLL_EXPORT int uc_start (char * err_msg)
Definition at line 321 of file broker_admin_so.c.
References admin_common(), admin_log_write(), admin_start_cmd(), BROKER_PATH_MAX, CP_ADMIN_ERR_MSG, DLL_EXPORT, and MAX_BROKER_NUM.
DLL_EXPORT int uc_stop (char * err_msg)
Definition at line 346 of file broker_admin_so.c.
References admin_common(), admin_log_write(), admin_stop_cmd(), BROKER_PATH_MAX, CP_ADMIN_ERR_MSG, DLL_EXPORT, MAX_BROKER_NUM, and NULL.
DLL_EXPORT int uc_unicas_conf (T_UC_CONF * unicas_conf, int * ret_mst_shmid, char * err_msg)
Definition at line 840 of file broker_admin_so.c.
References admin_common(), BROKER_PATH_MAX, conf_copy_broker(), conf_copy_header(), DLL_EXPORT, MAX_BROKER_NUM, and NULL.
DLL_EXPORT void uc_unicas_conf_free (T_UC_CONF * unicas_conf)
Definition at line 870 of file broker_admin_so.c.
References t_uc_conf::br_conf, conf_item_free(), DLL_EXPORT, FREE_MEM, t_uc_conf::header_conf, i, t_br_conf::item, t_br_conf::num, t_uc_conf::num_broker, and t_uc_conf::num_header.
DLL_EXPORT const char* uc_version (void)
Definition at line 315 of file broker_admin_so.c.
References DLL_EXPORT, and makestring.