CUBRID Engine: src/broker/broker_changer.c File Reference
broker_changer.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include "broker_admin_pub.h"
#include "broker_config.h"
#include "broker_util.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 45 of file broker_changer.c.
References admin_conf_change(), admin_err_msg, broker_config_read(), makestring, MAX_BROKER_NUM, NULL, parse_int(), ut_cd_work_dir(), and wsa_initialize().