CUBRID Engine: src/broker/broker_list.h File Reference
broker_list.h File Reference
Classes
struct list_tag
Macros
#define LINK_LIST_DEFAULT_ASSIGN_FUNC link_list_default_assign_func
#define LINK_LIST_DEFAULT_COMPARE_FUNC link_list_default_compare_func
#define LINK_LIST_FIND_VALUE(VALUE, HEAD, KEY, KEY_CMP_FUNC)
Typedefs
typedef struct list_tag T_LIST
Functions
int link_list_add (T_LIST **, void *, void *, int(*)(T_LIST *, void *, void *))
T_LIST * link_list_find (T_LIST *, void *, void *, int(*)(void *, void *), int(*)(void *, void *))
int link_list_node_delete2 (T_LIST **, void *, void *, int(*)(void *, void *), int(*)(void *, void *), void(*)(T_LIST *))
int link_list_delete (T_LIST **, void(*)(T_LIST *))
int link_list_node_delete (T_LIST **, void *, int(*)(void *, void *), void(*)(T_LIST *))
int link_list_default_assign_func (T_LIST *node, void *key, void *value)
int link_list_default_compare_func (void *key, void *value)
void * link_list_traverse (T_LIST *head, void *(*traverse_func)(T_LIST *, void *))
Macro Definition Documentation
#define LINK_LIST_DEFAULT_ASSIGN_FUNC link_list_default_assign_func
Definition at line 31 of file broker_list.h.
#define LINK_LIST_DEFAULT_COMPARE_FUNC link_list_default_compare_func
Definition at line 32 of file broker_list.h.
#define LINK_LIST_FIND_VALUE (VALUE, HEAD, KEY, KEY_CMP_FUNC)
Value:
do {                            \
      T_LIST   *node;                  \
      node = link_list_find(HEAD, KEY, NULL, KEY_CMP_FUNC, NULL);   \
      if (node == NULL)                    \
        VALUE = NULL;                   \
      else                          \
        VALUE = node->value;                \
    } while (0)
Definition at line 34 of file broker_list.h.
Referenced by shard_shm_set_shard_conn_info().
Typedef Documentation
typedef struct list_tag T_LIST
Definition at line 45 of file broker_list.h.
Function Documentation
int link_list_add (T_LIST ** , void * , void * , int(*)(T_LIST *, void *, void *))
Definition at line 63 of file broker_list.c.
References error(), FREE_MEM, and NULL.
Referenced by uw_shm_open().
int link_list_default_assign_func (T_LIST * node, void * key, void * value)
Definition at line 263 of file broker_list.c.
References list_tag::key, and list_tag::value.
int link_list_default_compare_func (void * key, void * value)
Definition at line 271 of file broker_list.c.
int link_list_delete (T_LIST ** , void(*)(T_LIST *))
Definition at line 230 of file broker_list.c.
References delete_node(), and NULL.
T_LIST* link_list_find (T_LIST * , void * , void * , int(*)(void *, void *) , int(*)(void *, void *))
Definition at line 112 of file broker_list.c.
References list_tag::key, list_tag::next, NULL, true_func(), and list_tag::value.
Referenced by link_list_node_delete(), and link_list_node_delete2().
int link_list_node_delete (T_LIST ** , void * , int(*)(void *, void *) , void(*)(T_LIST *))
Definition at line 156 of file broker_list.c.
References delete_node(), link_list_find(), and NULL.
Referenced by shard_shm_set_shard_conn_info().
int link_list_node_delete2 (T_LIST ** , void * , void * , int(*)(void *, void *) , int(*)(void *, void *) , void(*)(T_LIST *))
Definition at line 197 of file broker_list.c.
References delete_node(), link_list_find(), and NULL.
void* link_list_traverse (T_LIST * head, void *(*)(T_LIST *, void *) traverse_func)
Definition at line 244 of file broker_list.c.
References list_tag::next, and NULL.