CUBRID Engine: src/broker/broker_log_top.h File Reference
broker_log_top.h File Reference
Macros
#define LINE_BUF_SIZE 30000
Typedefs
typedef enum t_log_top_mode T_LOG_TOP_MODE
Enumerations
enum t_log_top_mode { MODE_PROC_TIME = 0, MODE_MAX_HANDLE = 1 }
enum log_top_error_code { LT_NO_ERROR = 0, LT_INVAILD_VERSION = -1, LT_OTHER_ERROR = -2 }
Functions
int check_log_time (char *start_date, char *end_date)
int log_top_tran (int argc, char *argv[], int arg_start)
int get_file_offset (char *filename, long *start_offset, long *end_offset)
Variables
T_LOG_TOP_MODE log_top_mode
Macro Definition Documentation
#define LINE_BUF_SIZE 30000
Definition at line 29 of file broker_log_top.h.
Typedef Documentation
typedef enum t_log_top_mode T_LOG_TOP_MODE
Definition at line 36 of file broker_log_top.h.
Enumeration Type Documentation
enum log_top_error_code
Enumerator
LT_NO_ERROR
LT_INVAILD_VERSION
LT_OTHER_ERROR
Definition at line 38 of file broker_log_top.h.
enum t_log_top_mode
Enumerator
MODE_PROC_TIME
MODE_MAX_HANDLE
Definition at line 31 of file broker_log_top.h.
Function Documentation
int check_log_time (char * start_date, char * end_date)
Definition at line 330 of file broker_log_top.c.
References DATE_STR_LEN, from_date, and to_date.
Referenced by info_add(), query_info_add(), and query_info_add_ne().
int get_file_offset (char * filename, long * start_offset, long * end_offset)
Definition at line 300 of file broker_log_top.c.
References from_date, NULL, search_offset(), and to_date.
Referenced by log_top_query(), and log_top_tran().
int log_top_tran (int argc, char * argv[], int arg_start)
Definition at line 56 of file broker_log_top_tran.c.
References argc, error(), get_file_offset(), i, info_arr_size, log_top(), LT_INVAILD_VERSION, NULL, and print_result().
Referenced by main().
Variable Documentation
T_LOG_TOP_MODE log_top_mode
Definition at line 85 of file broker_log_top.c.
Referenced by get_args(), log_top(), and query_info_print().