CUBRID Engine: src/broker/broker_process_info.h File Reference
broker_process_info.h File Reference
Classes
struct t_psinfo
Typedefs
typedef struct t_psinfo T_PSINFO
Functions
int get_psinfo (int pid, T_PSINFO *ps_info)
Typedef Documentation
typedef struct t_psinfo T_PSINFO
Definition at line 35 of file broker_process_info.h.
Function Documentation
int get_psinfo (int pid, T_PSINFO * ps_info)
Definition at line 123 of file broker_process_info.c.
Referenced by appl_info_display(), print_monitor_items(), uc_as_info(), and uc_br_info().