CUBRID Engine: src/broker/broker_log_util.c File Reference
broker_log_util.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <sys/time.h>
#include "cas_common.h"
#include "broker_log_util.h"
#include "cas_cci.h"
Macros
#define DATE_VALUE_COUNT 7
Functions
static bool is_bind_with_size (char *buf, int *tot_val_size, int *info_size)
char * ut_trim (char *str)
void ut_tolower (char *str)
int ut_get_line (FILE *fp, T_STRING *t_str, char **out_str, int *lineno)
int is_cas_log (char *str)
char * get_msg_start_ptr (char *linebuf)
int str_to_log_date_format (char *str, char *date_format_str)
char * ut_get_execute_type (char *msg_p, int *prepare_flag, int *execute_flag)
int ut_check_log_valid_time (const char *log_date, const char *from_date, const char *to_date)
double ut_diff_time (struct timeval *begin, struct timeval *end)
Macro Definition Documentation
#define DATE_VALUE_COUNT 7
Definition at line 403 of file broker_log_util.c.
Referenced by str_to_log_date_format().
Function Documentation
char* get_msg_start_ptr (char * linebuf)
Definition at line 379 of file broker_log_util.c.
References CAS_LOG_BEGIN_WITH_YEAR, CAS_LOG_MSG_INDEX, is_cas_log(), and NULL.
Referenced by is_bind_with_size(), log_converter(), log_replay(), log_top(), and read_bind_value().
static bool is_bind_with_size (char * buf, int * tot_val_size, int * info_size) static
Definition at line 175 of file broker_log_util.c.
References get_msg_start_ptr(), NULL, p, and strlen.
Referenced by ut_get_line(), and ut_tolower().
int is_cas_log (char * str)
Definition at line 359 of file broker_log_util.c.
References CAS_LOG_BEGIN_WITH_MONTH, CAS_LOG_BEGIN_WITH_YEAR, CAS_LOG_MSG_INDEX, and strlen.
Referenced by get_msg_start_ptr(), log_converter(), log_replay(), log_top(), read_bind_value(), read_multi_line_sql(), and search_offset().
int str_to_log_date_format (char * str, char * date_format_str)
Definition at line 405 of file broker_log_util.c.
References DATE_VALUE_COUNT, error(), i, and str_to_int32().
Referenced by get_args().
int ut_check_log_valid_time (const char * log_date, const char * from_date, const char * to_date)
Definition at line 480 of file broker_log_util.c.
References DATE_STR_LEN.
Referenced by log_replay().
double ut_diff_time (struct timeval * begin, struct timeval * end)
Definition at line 497 of file broker_log_util.c.
Referenced by cas_runner(), log_execute(), log_replay(), process_endtran(), and process_execute().
char* ut_get_execute_type (char * msg_p, int * prepare_flag, int * execute_flag)
Definition at line 453 of file broker_log_util.c.
References NULL.
Referenced by log_converter(), log_execute(), and log_prepare().
int ut_get_line (FILE * fp, T_STRING * t_str, char ** out_str, int * lineno)
Definition at line 283 of file broker_log_util.c.
References FREE_MEM, is_bind_with_size(), MALLOC, NULL, strlen, t_bind_string_add(), t_string_add(), t_string_clear(), t_string_len(), and t_string_str().
Referenced by cas_runner(), get_next_log_line(), log_converter(), log_top(), read_bind_value(), read_multi_line_sql(), search_offset(), and sql_list_make().
void ut_tolower (char * str)
Definition at line 73 of file broker_log_util.c.
Referenced by sch_attr_info(), sch_class_info(), sch_direct_super_class(), sch_primary_key(), sch_queryspec(), and str_like().
char* ut_trim (char * str)
Definition at line 43 of file broker_log_util.c.
Referenced by dbval_to_net_buf(), fn_prepare_internal(), log_top(), net_buf_column_info_set(), netval_to_dbval(), sql_change_comp_form(), and ux_prepare().