CUBRID Engine: src/broker/broker_filename.c File Reference
broker_filename.c File Reference
#include "config.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "broker_admin_pub.h"
#include "broker_filename.h"
#include "environment_variable.h"
#include "error_manager.h"
#include "system_parameter.h"
Macros
#define NUM_CUBRID_FILE MAX_CUBRID_FILE
Functions
void set_cubrid_home ()
char * get_cubrid_home ()
void set_cubrid_file (T_CUBRID_FILE_ID fid, char *value)
char * get_cubrid_file_ptr (T_CUBRID_FILE_ID fid)
char * get_cubrid_file (T_CUBRID_FILE_ID fid, char *buf, size_t len)
const char * getenv_cubrid_broker ()
Variables
static char cubrid_Dir [BROKER_PATH_MAX] = ""
static T_CUBRID_FILE_INFO cubrid_file [NUM_CUBRID_FILE]
Macro Definition Documentation
#define NUM_CUBRID_FILE MAX_CUBRID_FILE
Definition at line 46 of file broker_filename.c.
Function Documentation
char* get_cubrid_file (T_CUBRID_FILE_ID fid, char * buf, size_t len)
Definition at line 195 of file broker_filename.c.
References assert, BROKER_PATH_MAX, cubrid_Dir, envvar_confdir_file(), envvar_get(), envvar_logdir_file(), envvar_tmpdir_file(), envvar_vardir_file(), FID_ADMIND_LOG, FID_ADMIND_PID, FID_AS_PID_DIR, FID_CAS_FOR_MYSQL_DBINFO, FID_CAS_FOR_ORACLE_DBINFO, FID_CAS_TMP_DIR, FID_CAS_TMPGLO_DIR, FID_CUBRID_BROKER_CONF, FID_CUBRID_ERR_DIR, FID_ER_HTML, FID_MONITORD_LOG, FID_SHARD_DBINFO, FID_SHARD_PROXY_LOG_DIR, FID_SLOW_LOG_DIR, FID_SOCK_DIR, FID_SQL_LOG2_DIR, FID_SQL_LOG_DIR, FID_UV_ERR_MSG, FID_V3_OUTFILE_DIR, FID_VAR_DIR, NULL, set_cubrid_home(), and strlen.
Referenced by admin_start_cmd(), as_db_err_log_set(), broker_config_read(), cas_log_query_plan_file(), cfg_get_dbinfo(), cfg_read_dbinfo(), get_as_slow_log_filename(), get_as_sql_log_filename(), get_error_msg(), get_master_shm_id(), make_error_log_filename(), make_sql_log_filename(), sql_log2_init(), ut_get_as_pid_name(), ut_get_as_port_name(), ut_get_broker_port_name(), and ut_get_proxy_port_name().
char* get_cubrid_file_ptr (T_CUBRID_FILE_ID fid)
Definition at line 189 of file broker_filename.c.
References t_cubrid_file_info::file_name.
Referenced by access_control_set_shm(), and admin_acl_reload_cmd().
char* get_cubrid_home (void)
Definition at line 92 of file broker_filename.c.
References cubrid_Dir, and set_cubrid_home().
Referenced by dir_repath(), and set_cubrid_file().
const char* getenv_cubrid_broker (void)
Definition at line 313 of file broker_filename.c.
References envvar_root(), and p.
Referenced by set_cubrid_home().
void set_cubrid_file (T_CUBRID_FILE_ID fid, char * value)
Definition at line 103 of file broker_filename.c.
References assert, BROKER_PATH_MAX, envvar_confdir_file(), FID_ACCESS_CONTROL_FILE, FID_AS_PID_DIR, FID_CAS_TMP_DIR, FID_CAS_TMPGLO_DIR, FID_CUBRID_ERR_DIR, FID_SLOW_LOG_DIR, FID_SOCK_DIR, FID_SQL_LOG2_DIR, FID_SQL_LOG_DIR, FID_V3_OUTFILE_DIR, FID_VAR_DIR, t_cubrid_file_info::file_name, get_cubrid_home(), IS_ABS_PATH, NULL, and strlen.
Referenced by access_control_set_shm(), admin_acl_reload_cmd(), cas_init(), cas_log_open(), cas_main(), cas_slow_log_open(), and main().
void set_cubrid_home (void)
Definition at line 72 of file broker_filename.c.
References assert, BROKER_PATH_MAX, cubrid_Dir, dirname(), getenv_cubrid_broker(), and p.
Referenced by get_cubrid_file(), get_cubrid_home(), and main().
Variable Documentation
char cubrid_Dir[BROKER_PATH_MAX] = "" static
Definition at line 44 of file broker_filename.c.
Referenced by get_cubrid_file(), get_cubrid_home(), and set_cubrid_home().
T_CUBRID_FILE_INFO cubrid_file[NUM_CUBRID_FILE] static
Initial value:
= {
  {FID_CUBRID_BROKER_CONF, ""},
  {FID_UV_ERR_MSG, ""},
  {FID_V3_OUTFILE_DIR, ""},
  {FID_CAS_TMPGLO_DIR, ""},
  {FID_CAS_TMP_DIR, ""},
  {FID_VAR_DIR, ""},
  {FID_SOCK_DIR, ""},
  {FID_AS_PID_DIR, ""},
  {FID_ADMIND_PID, ""},
  {FID_SQL_LOG_DIR, ""},
  {FID_SQL_LOG2_DIR, ""},
  {FID_ADMIND_LOG, ""},
  {FID_MONITORD_LOG, ""},
  {FID_ER_HTML, ""},
  {FID_CUBRID_ERR_DIR, ""},
  {FID_CAS_FOR_ORACLE_DBINFO, ""},
  {FID_CAS_FOR_MYSQL_DBINFO, ""},
  {FID_ACCESS_CONTROL_FILE, ""},
  {FID_SLOW_LOG_DIR, ""},
  {FID_SHARD_DBINFO, ""},
  {FID_SHARD_PROXY_LOG_DIR, ""}
}
Definition at line 47 of file broker_filename.c.