CUBRID Engine: src/broker/broker_access_list.h File Reference
broker_access_list.h File Reference
Classes
struct t_ip
struct t_acl
Macros
#define IPV4_LENGTH_MAX 4
Typedefs
typedef struct t_ip T_IP
typedef struct t_acl T_ACL
Functions
int uw_acl_make (char *acl_file)
int uw_acl_check (unsigned char *ip_addr)
Variables
T_ACL * v3_acl
Macro Definition Documentation
#define IPV4_LENGTH_MAX 4
Definition at line 29 of file broker_access_list.h.
Referenced by uw_acl_check().
Typedef Documentation
typedef struct t_acl T_ACL
Definition at line 38 of file broker_access_list.h.
typedef struct t_ip T_IP
Definition at line 31 of file broker_access_list.h.
Function Documentation
int uw_acl_check (unsigned char * ip_addr)
Definition at line 114 of file broker_access_list.c.
References t_acl::acl, i, t_ip::ip, t_ip::ip_length, IPV4_LENGTH_MAX, and t_acl::num_acl.
Referenced by receiver_thr_f().
int uw_acl_make (char * acl_file)
Definition at line 41 of file broker_access_list.c.
References t_acl::acl, convert_ip(), ip_comp(), NULL, t_acl::num_acl, p, trim(), UW_ER_NO_MORE_MEMORY, and UW_SET_ERROR_CODE.
Referenced by main().
Variable Documentation
T_ACL* v3_acl
Definition at line 38 of file broker_access_list.c.
Referenced by receiver_thr_f().