CUBRID Engine: src/storage/byte_order.h File Reference
byte_order.h File Reference
#include "system.h"
Classes
union moving_van
Macros
#define OR_LITTLE_ENDIAN 1234
#define OR_BIG_ENDIAN 4321
#define OR_BYTE_ORDER OR_LITTLE_ENDIAN /* WINDOWS, LINUX, x86_SOLARIS */
#define OR_MOVE_DOUBLE(src, dst) (((MOVING_VAN *)(dst))->bits = ((MOVING_VAN *)(src))->bits)
Typedefs
typedef union moving_van MOVING_VAN
Functions
unsigned short ntohs (unsigned short)
unsigned int ntohl (unsigned int)
UINT64 ntohi64 (UINT64)
float ntohf (UINT32 from)
double ntohd (UINT64 from)
unsigned short htons (unsigned short)
unsigned int htonl (unsigned int)
UINT64 htoni64 (UINT64)
UINT32 htonf (float)
UINT64 htond (double)
Macro Definition Documentation
#define OR_BIG_ENDIAN 4321
Definition at line 61 of file byte_order.h.
#define OR_BYTE_ORDER OR_LITTLE_ENDIAN /* WINDOWS, LINUX, x86_SOLARIS */
Definition at line 66 of file byte_order.h.
#define OR_LITTLE_ENDIAN 1234
Definition at line 60 of file byte_order.h.
#define OR_MOVE_DOUBLE (src, dst) (((MOVING_VAN *)(dst))->bits = ((MOVING_VAN *)(src))->bits)
Definition at line 89 of file byte_order.h.
Referenced by db_value_printer::describe_data(), ehash_apply_each(), ehash_compare_key(), ehash_dump_bucket(), ehash_rv_init_dir_new_page_redo(), ehash_write_key_to_record(), mr_data_readmem_double(), mr_data_writemem_double(), mr_getmem_double(), mr_getmem_money(), mr_initmem_double(), mr_initmem_money(), mr_setmem_double(), mr_setmem_money(), and valcnv_convert_data_to_string().
Typedef Documentation
typedef union moving_van MOVING_VAN
Definition at line 78 of file byte_order.h.
Function Documentation
UINT64 htond (double)
Definition at line 7806 of file object_representation.c.
References p.
Referenced by OR_PUT_DOUBLE().
UINT32 htonf (float)
Definition at line 7787 of file object_representation.c.
References p.
Referenced by OR_PUT_FLOAT().
UINT64 htoni64 (UINT64)
Definition at line 7780 of file object_representation.c.
References ntohi64().
unsigned int htonl (unsigned int)
Definition at line 7773 of file object_representation.c.
References ntohl().
Referenced by cas_make_session_for_driver(), cas_send_connect_reply_to_driver(), css_abort_request(), css_accept_server_request(), css_connect_to_master_server(), css_open_server_connection_socket(), css_process_all_count_info(), css_process_change_server_ha_mode_request(), css_process_get_server_ha_mode(), css_process_get_server_ha_mode_request(), css_process_request_count_info(), css_process_server_count_info(), css_process_server_state(), css_reject_client_request(), css_reject_server_request(), css_send_close_request(), css_send_command_to_server(), css_send_heartbeat_request(), css_send_reply_to_new_client_request(), css_send_to_existing_server(), css_set_io_vector(), css_set_net_header(), css_tcp_master_open(), css_transfer_fd(), dispatch_thr_f(), ehash_hash_eight_bytes_type(), fn_proxy_cas_prepare(), fn_proxy_cas_prepare_and_execute(), fn_proxy_cas_schema_info(), hb_cluster_initialize(), hb_deregister_from_master(), hb_make_set_hbp_register(), hb_resource_send_changemode(), hb_set_net_header(), MCWriteCat(), net_arg_put_int(), net_buf_cp_int(), net_buf_overwrite_int(), net_write_header(), net_write_int(), process_ha_deregister_by_pid(), process_master_shutdown(), process_request(), process_slave_kill(), proxy_init_net_buf(), proxy_io_make_client_dbinfo_ok(), proxy_io_register_to_broker(), proxy_listener_thr_f(), send_error_to_driver(), set_data_length(), and shard_stmt_save_prepare_request().
unsigned short htons (unsigned short)
Definition at line 7765 of file object_representation.c.
References ntohs().
Referenced by connect_srv(), css_abort_request(), css_peer_alive(), css_set_net_header(), css_sockaddr(), css_tcp_client_open_with_retry(), css_tcp_master_open(), css_transfer_fd(), hb_cluster_initialize(), hb_cluster_receive_heartbeat(), hb_hostname_n_port_to_sockaddr(), hb_set_net_header(), in_cksum(), init_env(), jsp_connect_server(), net_buf_cp_short(), net_connect_proxy(), net_init_env(), and proxy_io_register_to_broker().
double ntohd (UINT64 from)
Definition at line 7723 of file object_representation.c.
float ntohf (UINT32 from)
Definition at line 7705 of file object_representation.c.
UINT64 ntohi64 (UINT64)
Definition at line 328 of file cas_dbms_util.c.
Referenced by htoni64(), net_arg_get_bigint(), net_arg_get_lob_handle(), and net_arg_get_size().
unsigned int ntohl (unsigned int)
Definition at line 7687 of file object_representation.c.
Referenced by cas_set_session_id(), check_cas_log(), css_check_magic_with_socket(), css_connect_to_cubrid_server(), css_connect_to_master_server(), css_get_master_request(), css_is_shutdown_timeout_expired(), css_net_recv(), css_net_send8(), css_process_deregister_ha_process(), css_process_ha_deregister_by_pid(), css_process_kill_slave(), css_process_shutdown(), css_queue_command_packet(), css_queue_data_packet(), css_queue_error_packet(), css_queue_packet(), css_queue_unexpected_packet(), css_read_and_queue(), css_read_header(), css_read_one_request(), css_receive_data(), css_receive_error(), css_receive_heartbeat_request(), css_register_new_server2(), css_return_queued_request(), css_server_connect_part_two(), cub_catgets(), dispatch_thr_f(), get_data_length(), get_server_state_from_master(), hb_cluster_receive_heartbeat(), hb_register_new_process(), hb_resource_receive_changemode(), htonl(), javasp_ping_server(), javasp_status_server(), jsp_alloc_response(), jsp_receive_response(), jsp_send_destroy_request(), load_msgcat(), MCReadCat(), net_arg_get_cache_time(), net_arg_get_cci_object(), net_arg_get_datetimetz(), net_arg_get_int(), net_arg_get_lob_handle(), net_arg_get_object(), net_arg_get_size(), net_arg_get_str(), net_arg_get_timestamptz(), net_arg_get_xid(), net_decode_str(), net_read_header(), net_read_int(), proxy_check_cas_error(), proxy_get_cas_error_code(), proxy_process_cas_register(), receiver_thr_f(), and return_integer_data().
unsigned short ntohs (unsigned short)
Definition at line 7671 of file object_representation.c.
Referenced by css_is_shutdown_timeout_expired(), css_open_new_socket_from_master(), css_open_server_connection_socket(), css_queue_packet(), css_queue_unexpected_packet(), css_read_header(), css_read_one_request(), css_return_queued_request(), css_send_close_request(), ehash_hash_eight_bytes_type(), hb_cluster_receive_heartbeat(), htons(), in_cksum(), net_arg_get_cci_object(), net_arg_get_date(), net_arg_get_datetime(), net_arg_get_object(), net_arg_get_short(), net_arg_get_time(), net_arg_get_timestamp(), net_init_env(), and receiver_thr_f().