CUBRID Engine: src/broker/cas_function.h File Reference
cas_function.h File Reference
#include "cas_net_buf.h"
Typedefs
typedef FN_RETURN(* T_SERVER_FUNC) (SOCKET, int, void **, T_NET_BUF *, T_REQ_INFO *)
Enumerations
enum FN_RETURN { FN_KEEP_CONN = 0, FN_CLOSE_CONN = -1, FN_KEEP_SESS = -2, FN_GRACEFUL_DOWN = -3 }
Functions
FN_RETURN fn_end_tran (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_end_session (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_get_row_count (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_get_last_insert_id (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_prepare (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_execute (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_get_db_parameter (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_set_db_parameter (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_set_cas_change_mode (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_close_req_handle (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_cursor (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_fetch (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_schema_info (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_get_db_version (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_next_result (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_execute_batch (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_execute_array (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_get_attr_type_str (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_xa_prepare (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_xa_recover (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_xa_end_tran (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_con_close (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_check_cas (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_make_out_rs (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_get_generated_keys (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_oid_get (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_oid_put (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_get_class_num_objs (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_oid (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_collection (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_cursor_close (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_cursor_update (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_get_query_info (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_savepoint (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_parameter_info (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_not_supported (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_lob_new (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_lob_write (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_lob_read (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_deprecated (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_prepare_and_execute (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
Typedef Documentation
typedef FN_RETURN(* T_SERVER_FUNC) (SOCKET, int, void **, T_NET_BUF *, T_REQ_INFO *)
Definition at line 39 of file cas_function.h.
Enumeration Type Documentation
enum FN_RETURN
Enumerator
FN_KEEP_CONN
FN_CLOSE_CONN
FN_KEEP_SESS
FN_GRACEFUL_DOWN
Definition at line 31 of file cas_function.h.
Function Documentation
FN_RETURN fn_check_cas (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 2045 of file cas_function.c.
References CAS_ERROR_INDICATOR, cas_log_write(), ERROR_INFO_SET, FN_KEEP_CONN, FN_KEEP_SESS, net_arg_get_str(), NET_BUF_ERR_SET, and ux_check_connection().
FN_RETURN fn_close_req_handle (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1018 of file cas_function.c.
References CAS_ER_ARGS, CAS_ERROR_INDICATOR, cas_log_write(), ERROR_INFO_SET, FALSE, FN_KEEP_CONN, hm_find_srv_handle(), hm_srv_handle_free(), t_req_info::need_auto_commit, net_arg_get_char, net_arg_get_int(), net_buf_cp_int(), NET_BUF_ERR_SET, NULL, SRV_HANDLE_QUERY_SEQ_NUM, TRAN_AUTOCOMMIT, and TRUE.
FN_RETURN fn_collection (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1383 of file cas_function.c.
References CAS_ER_ARGS, CAS_ER_COLLECTION_DOMAIN, CAS_ER_INTERNAL, CAS_ER_NOT_COLLECTION, CAS_ERROR_INDICATOR, db_attribute_domain(), db_col_free(), db_domain_set(), db_error_code(), db_get(), db_get_attribute(), db_get_collection, db_put(), DB_TYPE_NULL, db_value_clear(), db_value_type(), DBMS_ERROR_INDICATOR, ERROR_INFO_SET, FN_KEEP_CONN, FREE_MEM, get_set_domain(), make_bind_value(), net_arg_get_char, net_arg_get_dbobject(), net_arg_get_int(), net_arg_get_str(), NET_BUF_ERR_SET, NULL, TP_DOMAIN_TYPE, ux_check_object(), ux_col_get(), ux_col_seq_drop(), ux_col_seq_insert(), ux_col_seq_put(), ux_col_set_add(), ux_col_set_drop(), ux_col_size(), and ux_db_type_to_cas_type().
FN_RETURN fn_con_close (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 2031 of file cas_function.c.
References CAS_CLIENT_SERVER_SIDE_JDBC, cas_log_write(), t_req_info::driver_info, DRIVER_INFO_CLIENT_TYPE, FN_CLOSE_CONN, logddl_free(), net_buf_cp_int(), and NULL.
FN_RETURN fn_cursor (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1060 of file cas_function.c.
References CAS_ER_ARGS, CAS_ERROR_INDICATOR, ERROR_INFO_SET, FN_KEEP_CONN, net_arg_get_char, net_arg_get_int(), NET_BUF_ERR_SET, and ux_cursor().
FN_RETURN fn_cursor_close (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1830 of file cas_function.c.
References cas_log_write(), FN_KEEP_CONN, hm_find_srv_handle(), net_arg_get_int(), NULL, t_srv_handle::num_q_result, SRV_HANDLE_QUERY_SEQ_NUM, and ux_cursor_close().
FN_RETURN fn_cursor_update (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1803 of file cas_function.c.
References CAS_ER_ARGS, CAS_ERROR_INDICATOR, cas_log_write(), ERROR_INFO_SET, FN_KEEP_CONN, hm_find_srv_handle(), net_arg_get_int(), NET_BUF_ERR_SET, SRV_HANDLE_QUERY_SEQ_NUM, and ux_cursor_update().
FN_RETURN fn_deprecated (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 2626 of file cas_function.c.
References CAS_ER_NOT_IMPLEMENTED, CAS_ERROR_INDICATOR, ERROR_INFO_SET, FN_KEEP_CONN, net_buf_cp_int(), NET_BUF_ERR_SET, and NULL.
FN_RETURN fn_end_session (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 278 of file cas_function.c.
References FN_KEEP_CONN, net_buf_cp_int(), NO_ERROR, and NULL.
FN_RETURN fn_end_tran (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 155 of file cas_function.c.
References ARG_FILE_LINE, as_info, assert, broker_name, CAS_ER_ARGS, CAS_ER_TRAN_TYPE, CAS_ERROR_INDICATOR, cas_log_debug(), cas_log_end(), cas_log_reset(), t_appl_server_info::cas_log_reset, cas_log_write(), CAS_MAKE_VER, cas_send_result_flag, t_appl_server_info::cas_slow_log_reset, cas_slow_log_reset(), t_req_info::client_version, t_appl_server_info::con_status, CON_STATUS_IN_TRAN, CON_STATUS_OUT_TRAN, t_appl_server_info::cur_sql_log2, err_info, t_error_info::err_number, ERROR_INFO_SET, errors_in_transaction, FALSE, FN_CLOSE_CONN, FN_KEEP_CONN, FN_KEEP_SESS, get_error_log_eids(), get_tran_type_str(), logddl_write_tran_str(), t_shm_appl_server::long_transaction_time, MAX_DIAG_DATA_VALUE, t_req_info::need_rollback, net_arg_get_char, net_buf_cp_int(), NET_BUF_ERR_SET, NULL, t_appl_server_info::num_long_transactions, query_start_time, query_timeout, t_appl_server_info::reset_flag, restart_is_needed(), shm_appl, shm_as_index, t_shm_appl_server::sql_log2, sql_log2_end(), sql_log2_init(), SQL_LOG_MODE_ERROR, SQL_LOG_MODE_NONE, SQL_LOG_MODE_TIMEOUT, tran_start_time, tran_timeout, t_appl_server_info::transaction_start_time, TRUE, ut_check_timeout(), ut_timeval_diff(), ux_end_tran(), and ux_is_database_connected().
FN_RETURN fn_execute (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 415 of file cas_function.c.
References fn_execute_internal(), and NULL.
FN_RETURN fn_execute_array (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1653 of file cas_function.c.
References as_info, t_srv_handle::auto_commit_mode, bind_value_log(), CAS_ER_ARGS, cas_log_write(), cas_log_write_nonl(), cas_log_write_query_string(), cas_slow_log_end(), cas_slow_log_write(), cas_slow_log_write_query_string(), t_req_info::client_version, t_appl_server_info::cur_slow_log_mode, t_appl_server_info::cur_sql_log_mode, db_get_execution_plan(), db_set_execution_plan(), DOES_CLIENT_UNDERSTAND_THE_PROTOCOL, err_info, t_error_info::err_number, FN_KEEP_CONN, get_error_log_eids(), get_tuple_count(), hm_find_srv_handle(), t_srv_handle::is_pooled, logddl_set_sql_text(), t_shm_appl_server::long_query_time, MAX_DIAG_DATA_VALUE, t_req_info::need_auto_commit, net_arg_get_char, net_arg_get_int(), net_buf_cp_int(), NULL, t_appl_server_info::num_long_queries, PROTOCOL_V4, query_start_time, query_timeout, set_query_timeout(), shm_appl, SLOW_LOG_MODE_ON, SQL_LOG_MODE_NONE, t_srv_handle::sql_stmt, SRV_HANDLE_QUERY_SEQ_NUM, strlen, TRAN_AUTOCOMMIT, TRUE, update_error_query_count(), t_srv_handle::use_query_cache, ut_check_timeout(), ut_timeval_diff(), and ux_execute_array().
FN_RETURN fn_execute_batch (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1617 of file cas_function.c.
References cas_log_write(), t_req_info::client_version, DOES_CLIENT_UNDERSTAND_THE_PROTOCOL, FN_KEEP_CONN, logddl_set_commit_mode(), net_arg_get_char, net_arg_get_int(), NULL, PROTOCOL_V4, query_timeout, set_query_timeout(), and ux_execute_batch().
FN_RETURN fn_fetch (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1084 of file cas_function.c.
References CAS_ER_ARGS, CAS_ER_SRV_HANDLE, CAS_ERROR_INDICATOR, cas_log_write(), ERROR_INFO_SET, FN_KEEP_CONN, hm_find_srv_handle(), net_arg_get_char, net_arg_get_int(), NET_BUF_ERR_SET, NULL, SRV_HANDLE_QUERY_SEQ_NUM, and ux_fetch().
FN_RETURN fn_get_attr_type_str (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1852 of file cas_function.c.
References CAS_ER_ARGS, CAS_ERROR_INDICATOR, ERROR_INFO_SET, FN_KEEP_CONN, net_arg_get_str(), NET_BUF_ERR_SET, and ux_get_attr_type_str().
FN_RETURN fn_get_class_num_objs (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1237 of file cas_function.c.
References CAS_ER_ARGS, CAS_ERROR_INDICATOR, cas_log_write(), ERROR_INFO_SET, FN_KEEP_CONN, net_arg_get_char, net_arg_get_str(), NET_BUF_ERR_SET, and ux_get_class_num_objs().
FN_RETURN fn_get_db_parameter (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 804 of file cas_function.c.
References cas_default_no_backslash_escapes, CAS_ER_ARGS, CAS_ER_PARAM_NAME, CAS_ERROR_INDICATOR, cas_log_write(), t_req_info::client_version, DB_MAX_STRING_LENGTH, DOES_CLIENT_UNDERSTAND_THE_PROTOCOL, ERROR_INFO_SET, FN_KEEP_CONN, t_shm_appl_server::max_string_length, net_arg_get_int(), net_buf_cp_int(), NET_BUF_ERR_SET, NULL, PROTOCOL_V2, shm_appl, and ux_get_tran_setting().
FN_RETURN fn_get_db_version (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1209 of file cas_function.c.
References CAS_ER_ARGS, CAS_ERROR_INDICATOR, cas_log_write(), ERROR_INFO_SET, FN_KEEP_CONN, t_req_info::need_auto_commit, net_arg_get_char, NET_BUF_ERR_SET, TRAN_AUTOCOMMIT, TRUE, and ux_get_db_version().
FN_RETURN fn_get_generated_keys (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 2102 of file cas_function.c.
References CAS_ER_ARGS, CAS_ER_SRV_HANDLE, CAS_ERROR_INDICATOR, cas_log_write(), ERROR_INFO_SET, FN_KEEP_CONN, hm_find_srv_handle(), net_arg_get_int(), NET_BUF_ERR_SET, NULL, SRV_HANDLE_QUERY_SEQ_NUM, and ux_get_generated_keys().
FN_RETURN fn_get_last_insert_id (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 294 of file cas_function.c.
References FN_KEEP_CONN, and ux_get_last_insert_id().
FN_RETURN fn_get_query_info (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1874 of file cas_function.c.
References CAS_ER_ARGS, CAS_ERROR_INDICATOR, cas_log_query_info_init(), db_close_session(), db_compile_statement(), db_error_code(), db_execute_statement(), db_open_buffer(), db_query_end(), DBMS_ERROR_INDICATOR, ER_UCI_TOO_FEW_HOST_VARS, err, ERROR_INFO_SET, FN_KEEP_CONN, hm_new_srv_handle(), hm_srv_handle_free(), net_arg_get_char, net_arg_get_int(), net_arg_get_str(), net_buf_cp_byte(), NET_BUF_ERR_SET, NULL, t_srv_handle::query_info_flag, query_seq_num_next_value(), reset_optimization_level_as_saved(), TRUE, and ux_get_query_info().
FN_RETURN fn_get_row_count (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 287 of file cas_function.c.
References FN_KEEP_CONN, and ux_get_row_count().
FN_RETURN fn_lob_new (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 2499 of file cas_function.c.
References CAS_ER_ARGS, CAS_ERROR_INDICATOR, cas_log_write(), err_info, t_error_info::err_number, ERROR_INFO_SET, FN_KEEP_CONN, get_error_log_eids(), net_arg_get_int(), net_buf_cp_int(), NET_BUF_ERR_SET, NULL, ut_timeval_diff(), and ux_lob_new().
FN_RETURN fn_lob_read (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 2585 of file cas_function.c.
References CAS_ER_ARGS, CAS_ERROR_INDICATOR, cas_log_write(), db_get_elo(), db_value_clear(), err_info, t_error_info::err_number, ERROR_INFO_SET, FN_KEEP_CONN, get_error_log_eids(), net_arg_get_bigint(), net_arg_get_int(), net_arg_get_lob_value(), net_buf_cp_int(), NET_BUF_ERR_SET, NULL, ut_timeval_diff(), and ux_lob_read().
FN_RETURN fn_lob_write (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 2543 of file cas_function.c.
References CAS_ER_ARGS, CAS_ERROR_INDICATOR, cas_log_write(), db_get_elo(), db_value_clear(), err_info, t_error_info::err_number, ERROR_INFO_SET, FN_KEEP_CONN, get_error_log_eids(), net_arg_get_bigint(), net_arg_get_lob_value(), net_arg_get_str(), net_buf_cp_int(), NET_BUF_ERR_SET, NULL, ut_timeval_diff(), and ux_lob_write().
FN_RETURN fn_make_out_rs (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 2076 of file cas_function.c.
References argc, argv, CAS_ER_ARGS, CAS_ERROR_INDICATOR, ERROR_INFO_SET, FN_KEEP_CONN, fn_make_out_rs(), fn_not_supported(), net_arg_get_int(), NET_BUF_ERR_SET, req_info, sock_fd, and ux_make_out_rs().
Referenced by fn_make_out_rs().
FN_RETURN fn_next_result (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1581 of file cas_function.c.
References CAS_ER_ARGS, CAS_ER_SRV_HANDLE, CAS_ERROR_INDICATOR, cas_log_write(), ERROR_INFO_SET, FN_KEEP_CONN, hm_find_srv_handle(), net_arg_get_char, net_arg_get_int(), NET_BUF_ERR_SET, NULL, SRV_HANDLE_QUERY_SEQ_NUM, t_srv_handle::use_query_cache, and ux_next_result().
FN_RETURN fn_not_supported (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 2639 of file cas_function.c.
References CAS_ER_NOT_IMPLEMENTED, CAS_ERROR_INDICATOR, ERROR_INFO_SET, FN_KEEP_CONN, and NET_BUF_ERR_SET.
Referenced by fn_make_out_rs().
FN_RETURN fn_oid (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1261 of file cas_function.c.
References CAS_ER_ARGS, CAS_ER_INTERNAL, CAS_ER_OBJECT, CAS_ERROR_INDICATOR, cas_log_write(), db_drop(), db_error_code(), db_get_class_name(), db_is_instance(), db_lock_read(), db_lock_write(), DBMS_ERROR_INDICATOR, er_clear(), ERROR_INFO_SET, FN_KEEP_CONN, net_arg_get_char, net_arg_get_dbobject(), net_buf_cp_int(), net_buf_cp_str(), NET_BUF_ERR_SET, NULL, strlen, and ux_check_object().
FN_RETURN fn_oid_get (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1168 of file cas_function.c.
References CAS_ER_ARGS, CAS_ERROR_INDICATOR, cas_log_write(), ERROR_INFO_SET, FN_KEEP_CONN, net_arg_get_cci_object(), NET_BUF_ERR_SET, and ux_oid_get().
FN_RETURN fn_oid_put (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1190 of file cas_function.c.
References CAS_ER_ARGS, CAS_ERROR_INDICATOR, cas_log_write(), ERROR_INFO_SET, FN_KEEP_CONN, NET_BUF_ERR_SET, and ux_oid_put().
FN_RETURN fn_parameter_info (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 2010 of file cas_function.c.
References CAS_ER_ARGS, CAS_ERROR_INDICATOR, ERROR_INFO_SET, FN_KEEP_CONN, net_arg_get_int(), NET_BUF_ERR_SET, and ux_get_parameter_info().
FN_RETURN fn_prepare (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 302 of file cas_function.c.
References fn_prepare_internal(), and NULL.
FN_RETURN fn_prepare_and_execute (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 776 of file cas_function.c.
References cas_log_write(), fn_execute_internal(), FN_KEEP_CONN, fn_prepare_internal(), hm_find_srv_handle(), hm_srv_handle_free(), IS_ERROR_INFO_SET, net_arg_get_int(), and SRV_HANDLE_QUERY_SEQ_NUM.
FN_RETURN fn_savepoint (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1960 of file cas_function.c.
References CAS_ER_ARGS, CAS_ER_INTERNAL, CAS_ERROR_INDICATOR, cas_log_write(), db_abort_to_savepoint(), db_savepoint_transaction(), DBMS_ERROR_INDICATOR, ERROR_INFO_SET, FN_KEEP_CONN, net_arg_get_char, net_arg_get_str(), net_buf_cp_int(), NET_BUF_ERR_SET, and NULL.
FN_RETURN fn_schema_info (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1128 of file cas_function.c.
References CAS_ER_ARGS, CAS_ERROR_INDICATOR, cas_log_write(), t_req_info::client_version, DOES_CLIENT_UNDERSTAND_THE_PROTOCOL, ERROR_INFO_SET, FN_KEEP_CONN, get_schema_type_str(), net_arg_get_char, net_arg_get_int(), net_arg_get_str(), NET_BUF_ERR_SET, PROTOCOL_V5, query_seq_num_current_value(), query_seq_num_next_value(), and ux_schema_info().
FN_RETURN fn_set_cas_change_mode (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 989 of file cas_function.c.
References CAS_CHANGE_MODE_AUTO, CAS_CHANGE_MODE_KEEP, CAS_ER_ARGS, CAS_ERROR_INDICATOR, cas_log_write(), ERROR_INFO_SET, FN_KEEP_CONN, mode, net_arg_get_int(), NET_BUF_ERR_SET, and ux_set_cas_change_mode().
FN_RETURN fn_set_db_parameter (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 897 of file cas_function.c.
References as_info, t_appl_server_info::auto_commit_mode, cas_default_lock_timeout, CAS_ER_ARGS, CAS_ER_PARAM_NAME, CAS_ERROR_INDICATOR, cas_log_write(), ERROR_INFO_SET, FALSE, FN_KEEP_CONN, net_arg_get_int(), net_buf_cp_int(), NET_BUF_ERR_SET, NULL, TRUE, ux_set_isolation_level(), and ux_set_lock_timeout().
FN_RETURN fn_xa_end_tran (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 143 of file cas_xa.c.
References CAS_ER_ARGS, CAS_ER_NOT_IMPLEMENTED, CAS_ER_TRAN_TYPE, CAS_ERROR_INDICATOR, cas_log_write(), compare_xid(), cubregex::count(), db_2pc_attach_transaction(), db_2pc_prepared_transactions(), db_get_global_transaction_info(), DBMS_ERROR_INDICATOR, ERROR_INFO_SET, FN_CLOSE_CONN, FN_KEEP_CONN, i, MAX_GTRIDS, net_arg_get_char, net_arg_get_xid(), net_buf_cp_int(), NET_BUF_ERR_SET, NULL, set_xa_prepare_flag(), and ux_end_tran().
FN_RETURN fn_xa_prepare (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 54 of file cas_xa.c.
References CAS_ER_ARGS, CAS_ER_NOT_IMPLEMENTED, CAS_ERROR_INDICATOR, cas_log_write(), db_2pc_prepare_transaction(), db_2pc_start_transaction(), db_set_global_transaction_info(), DBMS_ERROR_INDICATOR, ERROR_INFO_SET, FN_KEEP_CONN, net_arg_get_xid(), net_buf_cp_int(), NET_BUF_ERR_SET, NULL, and set_xa_prepare_flag().
FN_RETURN fn_xa_recover (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 104 of file cas_xa.c.
References CAS_ER_NOT_IMPLEMENTED, CAS_ERROR_INDICATOR, cas_log_write(), cubregex::count(), db_2pc_prepared_transactions(), db_get_global_transaction_info(), DBMS_ERROR_INDICATOR, ERROR_INFO_SET, FN_KEEP_CONN, i, MAX_GTRIDS, net_buf_cp_int(), net_buf_cp_xid(), NET_BUF_ERR_SET, and NULL.