CUBRID Engine: src/broker/cas_log.c File Reference
cas_log.c File Reference
#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
#include <time.h>
#include <string.h>
#include <errno.h>
#include <unistd.h>
#include <sys/time.h>
#include <assert.h>
#include "porting.h"
#include "cas_common.h"
#include "cas_log.h"
#include "cas_util.h"
#include "broker_config.h"
#include "cas.h"
#include "cas_execute.h"
#include "broker_env_def.h"
#include "broker_filename.h"
#include "broker_util.h"
#include "dbi.h"
#include "cas_db_inc.h"
Macros
#define CAS_LOG_BUFFER_SIZE (8192)
#define SQL_LOG_BUFFER_SIZE 163840
#define ACCESS_LOG_IS_DENIED_TYPE(T) ((T)==ACL_REJECTED)
Functions
static const char * get_access_log_type_string (ACCESS_LOG_TYPE type)
static char * make_sql_log_filename (T_CUBRID_FILE_ID fid, char *filename_buf, size_t buf_size, const char *br_name)
static void cas_log_backup (T_CUBRID_FILE_ID fid)
static void cas_log_write_and_set_savedpos (FILE *log_fp, const char *fmt,...)
static void cas_log_write_internal (FILE *fp, struct timeval *log_time, unsigned int seq_num, bool do_flush, const char *fmt, va_list ap)
static void cas_log_write2_internal (FILE *fp, bool do_flush, const char *fmt, va_list ap)
static FILE * access_log_open (char *log_file_name)
static bool cas_log_begin_hang_check_time (void)
static void cas_log_end_hang_check_time (bool is_prev_time_set)
static void cas_log_write_query_string_internal (char *query, int size, bool newline)
static size_t cas_fwrite (const void *ptr, size_t size, size_t nmemb, FILE *stream)
static INT64 cas_ftell (FILE *stream)
static int cas_fseek (FILE *stream, INT64 offset, int whence)
static FILE * cas_fopen (const char *path, const char *mode)
static int cas_fclose (FILE *fp)
static int cas_ftruncate (int fd, off_t length)
static int cas_fflush (FILE *stream)
static int cas_fileno (FILE *stream)
static int cas_fprintf (FILE *stream, const char *format,...)
static int cas_fputc (int c, FILE *stream)
static int cas_unlink (const char *pathname)
static int cas_rename (const char *oldpath, const char *newpath)
static int cas_mkdir (const char *pathname, mode_t mode)
static void access_log_backup (char *access_log_file, struct tm *ct)
void cas_log_open (char *br_name)
void cas_log_reset (char *br_name)
void cas_log_close (bool flag)
void cas_log_end (int mode, int run_time_sec, int run_time_msec)
void cas_log_write_nonl (unsigned int seq_num, bool unit_start, const char *fmt,...)
static void cas_log_query_cancel (int dummy,...)
void cas_log_write (unsigned int seq_num, bool unit_start, const char *fmt,...)
void cas_log_write_and_end (unsigned int seq_num, bool unit_start, const char *fmt,...)
void cas_log_write2_nonl (const char *fmt,...)
void cas_log_write2 (const char *fmt,...)
void cas_log_write_value_string (char *value, int size)
void cas_log_write_query_string_nonl (char *query, int size)
void cas_log_write_query_string (char *query, int size)
void cas_log_write_client_ip (const unsigned char *ip_addr)
void cas_log_debug (const char *file_name, const int line_no, const char *fmt,...)
int cas_access_log (struct timeval *start_time, int as_index, int client_ip_addr, char *dbname, char *dbuser, ACCESS_LOG_TYPE log_type)
void cas_log_query_info_init (int id, char is_only_query_plan)
char * cas_log_query_plan_file (int id)
void cas_slow_log_open (char *br_name)
void cas_slow_log_reset (char *br_name)
void cas_slow_log_close ()
void cas_slow_log_end ()
void cas_slow_log_write_and_end (struct timeval *log_time, unsigned int seq_num, const char *fmt,...)
void cas_slow_log_write (struct timeval *log_time, unsigned int seq_num, bool unit_start, const char *fmt,...)
void cas_slow_log_write2 (const char *fmt,...)
void cas_slow_log_write_value_string (char *value, int size)
void cas_slow_log_write_query_string (char *query, int size)
Variables
static char cas_log_buffer [CAS_LOG_BUFFER_SIZE]
static char sql_log_buffer [SQL_LOG_BUFFER_SIZE]
static FILE * log_fp = NULL
static FILE * slow_log_fp = NULL
static char log_filepath [BROKER_PATH_MAX]
static char slow_log_filepath [BROKER_PATH_MAX]
static INT64 saved_log_fpos = 0
Macro Definition Documentation
#define ACCESS_LOG_IS_DENIED_TYPE (T) ((T)==ACL_REJECTED)
Definition at line 64 of file cas_log.c.
Referenced by cas_access_log().
#define CAS_LOG_BUFFER_SIZE (8192)
Definition at line 62 of file cas_log.c.
Referenced by cas_log_write2_internal(), and cas_log_write_internal().
#define SQL_LOG_BUFFER_SIZE 163840
Definition at line 63 of file cas_log.c.
Referenced by cas_log_open().
Function Documentation
static void access_log_backup (char * access_log_file, struct tm * ct) static
Definition at line 1407 of file cas_log.c.
Referenced by cas_access_log().
static FILE * access_log_open (char * log_file_name) static
Definition at line 910 of file cas_log.c.
References cas_fopen(), cas_mkdir(), dirname(), NULL, and strdup().
Referenced by cas_access_log(), and cas_log_debug().
int cas_access_log (struct timeval * start_time, int as_index, int client_ip_addr, char * dbname, char * dbuser, ACCESS_LOG_TYPE log_type)
Definition at line 784 of file cas_log.c.
References access_log_backup(), ACCESS_LOG_DENIED_FILENAME_POSTFIX, t_shm_appl_server::access_log_file, ACCESS_LOG_IS_DENIED_TYPE, t_shm_appl_server::access_log_max_size, access_log_open(), cas_fclose(), cas_fprintf(), db_get_session_id(), get_access_log_type_string(), NULL, ONE_K, shm_appl, and ut_get_ipv4_string().
Referenced by cas_main().
static int cas_fclose (FILE * fp) static
Definition at line 1284 of file cas_log.c.
References cas_log_begin_hang_check_time(), and cas_log_end_hang_check_time().
Referenced by cas_access_log(), cas_log_close(), cas_log_debug(), and cas_slow_log_close().
static int cas_fflush (FILE * stream) static
Definition at line 1310 of file cas_log.c.
References cas_log_begin_hang_check_time(), and cas_log_end_hang_check_time().
Referenced by cas_log_write2_internal(), cas_log_write_internal(), and cas_slow_log_end().
static int cas_fileno (FILE * stream) static
Definition at line 1324 of file cas_log.c.
References cas_log_begin_hang_check_time(), and cas_log_end_hang_check_time().
Referenced by cas_log_close().
static FILE * cas_fopen (const char * path, const char * mode) static
Definition at line 1237 of file cas_log.c.
References cas_log_begin_hang_check_time(), cas_log_end_hang_check_time(), MAX_RETRY_COUNT, mode, NULL, and SLEEP_MILISEC.
Referenced by access_log_open(), cas_log_open(), and cas_slow_log_open().
static int cas_fprintf (FILE * stream, const char * format, ...) static
Definition at line 1337 of file cas_log.c.
References cas_log_begin_hang_check_time(), and cas_log_end_hang_check_time().
Referenced by cas_access_log(), and cas_log_debug().
static int cas_fputc (int c, FILE * stream) static
Definition at line 1355 of file cas_log.c.
References cas_log_begin_hang_check_time(), and cas_log_end_hang_check_time().
Referenced by cas_log_debug(), cas_log_query_cancel(), cas_log_write(), cas_log_write2(), cas_log_write_and_end(), cas_log_write_query_string_internal(), cas_slow_log_end(), and cas_slow_log_write_query_string().
static int cas_fseek (FILE * stream, INT64 offset, int whence) static
Definition at line 1224 of file cas_log.c.
References cas_log_begin_hang_check_time(), and cas_log_end_hang_check_time().
Referenced by cas_log_close(), cas_log_open(), and cas_log_write_and_set_savedpos().
static INT64 cas_ftell (FILE * stream) static
Definition at line 1218 of file cas_log.c.
Referenced by cas_log_debug(), cas_log_end(), cas_log_open(), cas_log_write(), cas_log_write_and_end(), cas_log_write_nonl(), and cas_slow_log_end().
static int cas_ftruncate (int fd, off_t length) static
Definition at line 1297 of file cas_log.c.
References cas_log_begin_hang_check_time(), and cas_log_end_hang_check_time().
Referenced by cas_log_close().
static size_t cas_fwrite (const void * ptr, size_t size, size_t nmemb, FILE * stream) static
Definition at line 1205 of file cas_log.c.
References cas_log_begin_hang_check_time(), and cas_log_end_hang_check_time().
Referenced by cas_log_debug(), cas_log_write2_internal(), cas_log_write_internal(), cas_log_write_value_string(), and cas_slow_log_write_value_string().
static void cas_log_backup (T_CUBRID_FILE_ID fid) static
Definition at line 252 of file cas_log.c.
References assert, BROKER_PATH_MAX, cas_rename(), cas_unlink(), FID_SLOW_LOG_DIR, FID_SQL_LOG_DIR, log_filepath, NULL, and slow_log_filepath.
Referenced by cas_log_end(), and cas_slow_log_end().
static bool cas_log_begin_hang_check_time (void) static
Definition at line 1170 of file cas_log.c.
References as_info, cas_shard_flag, t_appl_server_info::claimed_alive_time, OFF, and set_hang_check_time().
Referenced by cas_fclose(), cas_fflush(), cas_fileno(), cas_fopen(), cas_fprintf(), cas_fputc(), cas_fseek(), cas_ftruncate(), cas_fwrite(), cas_mkdir(), cas_rename(), and cas_unlink().
void cas_log_close (bool flag)
Definition at line 234 of file cas_log.c.
References cas_fclose(), cas_fileno(), cas_fseek(), cas_ftruncate(), log_fp, NULL, and saved_log_fpos.
Referenced by cas_free(), cas_log_end(), cas_log_open(), cas_log_reset(), cas_main(), and shard_cas_main().
void cas_log_debug (const char * file_name, const int line_no, const char * fmt, ...)
Definition at line 701 of file cas_log.c.
References access_log_open(), cas_fclose(), cas_fprintf(), cas_fputc(), cas_ftell(), cas_fwrite(), t_shm_appl_server::error_log_file, log_fp, NULL, p, PATH_INFO_ENV_STR, shm_appl, strlen, ut_time_string(), and ut_uchar2ipstr().
Referenced by cas_free(), cas_main(), err_msg_set(), error_info_set_with_msg(), fn_end_tran(), fn_execute_internal(), net_read_int_keep_con_auto(), net_read_process(), process_request(), set_db_connection_info(), shard_cas_main(), ux_check_connection(), ux_database_connect(), ux_database_shutdown(), ux_end_tran(), ux_lob_new(), ux_lob_read(), and ux_lob_write().
void cas_log_end (int mode, int run_time_sec, int run_time_msec)
Definition at line 319 of file cas_log.c.
References as_info, t_shm_appl_server::broker_name, cas_ftell(), cas_log_backup(), cas_log_close(), cas_log_open(), cas_log_write(), cas_log_write_and_set_savedpos(), t_appl_server_info::cur_sql_log_mode, FID_SQL_LOG_DIR, log_fp, t_shm_appl_server::long_transaction_time, NULL, saved_log_fpos, shm_appl, t_shm_appl_server::sql_log_max_size, SQL_LOG_MODE_ALL, SQL_LOG_MODE_ERROR, SQL_LOG_MODE_NONE, SQL_LOG_MODE_NOTICE, and SQL_LOG_MODE_TIMEOUT.
Referenced by cas_log_write_and_end(), fn_end_tran(), and ux_auto_commit().
static void cas_log_end_hang_check_time (bool is_prev_time_set) static
Definition at line 1189 of file cas_log.c.
References cas_shard_flag, OFF, and unset_hang_check_time().
Referenced by cas_fclose(), cas_fflush(), cas_fileno(), cas_fopen(), cas_fprintf(), cas_fputc(), cas_fseek(), cas_ftruncate(), cas_fwrite(), cas_mkdir(), cas_rename(), and cas_unlink().
void cas_log_open (char * br_name)
Definition at line 163 of file cas_log.c.
References as_info, BROKER_PATH_MAX, cas_fopen(), cas_fseek(), cas_ftell(), cas_log_close(), t_appl_server_info::cas_log_reset, CAS_LOG_RESET_REOPEN, t_appl_server_info::cur_sql_log_mode, FID_SQL_LOG_DIR, t_shm_appl_server::log_dir, log_filepath, log_fp, make_sql_log_filename(), NULL, saved_log_fpos, set_cubrid_file(), shm_appl, sql_log_buffer, SQL_LOG_BUFFER_SIZE, and SQL_LOG_MODE_NONE.
Referenced by cas_log_end(), cas_log_reset(), cas_log_write(), cas_log_write2(), cas_log_write2_nonl(), cas_log_write_and_end(), cas_log_write_nonl(), cas_log_write_query_string_internal(), cas_log_write_value_string(), cas_main(), and shard_cas_main().
static void cas_log_query_cancel (int dummy, ...) static
Definition at line 466 of file cas_log.c.
References as_info, t_appl_server_info::cas_clt_ip, t_appl_server_info::cas_clt_port, cas_fputc(), cas_log_write_internal(), CAS_PROTO_MAKE_VER, t_appl_server_info::clt_version, t_appl_server_info::cur_sql_log_mode, log_fp, NULL, PROTOCOL_V1, query_cancel_flag, query_cancel_time, SQL_LOG_MODE_ALL, and ut_get_ipv4_string().
Referenced by cas_log_write().
void cas_log_query_info_init (int id, char is_only_query_plan)
Definition at line 871 of file cas_log.c.
References cas_log_query_plan_file(), cas_unlink(), db_query_plan_dump_file(), and set_optimization_level().
Referenced by fn_get_query_info(), ux_execute(), and ux_prepare().
char* cas_log_query_plan_file (int id)
Definition at line 892 of file cas_log.c.
References assert, BROKER_PATH_MAX, dirname(), FID_CAS_TMP_DIR, get_cubrid_file(), and NULL.
Referenced by cas_log_query_info_init(), srv_handle_rm_tmp_file(), ux_execute(), and ux_get_query_info().
void cas_log_reset (char * br_name)
Definition at line 211 of file cas_log.c.
References as_info, cas_log_close(), cas_log_open(), t_appl_server_info::cas_log_reset, CAS_LOG_RESET_REMOVE, cas_unlink(), t_appl_server_info::cur_sql_log_mode, log_filepath, log_fp, NULL, and SQL_LOG_MODE_NONE.
Referenced by fn_end_tran(), net_read_int_keep_con_auto(), net_read_process(), and process_request().
void cas_log_write (unsigned int seq_num, bool unit_start, const char * fmt, ...)
Definition at line 506 of file cas_log.c.
References as_info, t_shm_appl_server::broker_name, cas_fputc(), cas_ftell(), cas_log_open(), cas_log_query_cancel(), cas_log_write_internal(), t_appl_server_info::cur_sql_log_mode, log_fp, NULL, saved_log_fpos, shm_appl, SQL_LOG_MODE_ALL, and SQL_LOG_MODE_NONE.
Referenced by cas_init_ssl(), cas_log_end(), fn_check_cas(), fn_close_req_handle(), fn_con_close(), fn_cursor_close(), fn_cursor_update(), fn_end_tran(), fn_execute_array(), fn_execute_batch(), fn_execute_internal(), fn_fetch(), fn_get_class_num_objs(), fn_get_db_parameter(), fn_get_db_version(), fn_get_generated_keys(), fn_lob_new(), fn_lob_read(), fn_lob_write(), fn_next_result(), fn_oid(), fn_oid_get(), fn_oid_put(), fn_prepare_and_execute(), fn_prepare_internal(), fn_savepoint(), fn_schema_info(), fn_set_cas_change_mode(), fn_set_db_parameter(), fn_xa_end_tran(), fn_xa_prepare(), fn_xa_recover(), set_query_timeout(), and ux_auto_commit().
void cas_log_write2 (const char * fmt, ...)
Definition at line 604 of file cas_log.c.
References as_info, t_shm_appl_server::broker_name, cas_fputc(), cas_log_open(), cas_log_write2_internal(), t_appl_server_info::cur_sql_log_mode, log_fp, NULL, shm_appl, SQL_LOG_MODE_ALL, and SQL_LOG_MODE_NONE.
Referenced by cas_main(), shard_cas_main(), and ux_execute_batch().
static void cas_log_write2_internal (FILE * fp, bool do_flush, const char * fmt, va_list ap) static
Definition at line 559 of file cas_log.c.
References cas_fflush(), cas_fwrite(), cas_log_buffer, CAS_LOG_BUFFER_SIZE, and p.
Referenced by cas_log_write2(), cas_log_write2_nonl(), and cas_slow_log_write2().
void cas_log_write2_nonl (const char * fmt, ...)
Definition at line 584 of file cas_log.c.
References as_info, t_shm_appl_server::broker_name, cas_log_open(), cas_log_write2_internal(), t_appl_server_info::cur_sql_log_mode, log_fp, NULL, shm_appl, SQL_LOG_MODE_ALL, and SQL_LOG_MODE_NONE.
Referenced by bind_value_log(), bind_value_print(), and ux_execute_batch().
void cas_log_write_and_end (unsigned int seq_num, bool unit_start, const char * fmt, ...)
Definition at line 533 of file cas_log.c.
References as_info, t_shm_appl_server::broker_name, cas_fputc(), cas_ftell(), cas_log_end(), cas_log_open(), cas_log_write_internal(), t_appl_server_info::cur_sql_log_mode, log_fp, NULL, saved_log_fpos, shm_appl, SQL_LOG_MODE_ALL, and SQL_LOG_MODE_NONE.
Referenced by cas_free(), cas_init_ssl(), cas_log_write_client_ip(), cas_main(), cas_register_to_proxy(), cas_set_session_id(), cas_ssl_read(), cas_ssl_write(), err_msg_set(), net_read_process(), process_request(), report_abnormal_host_status(), set_db_parameter(), shard_cas_main(), and ux_check_connection().
static void cas_log_write_and_set_savedpos (FILE * log_fp, const char * fmt, ...) static
Definition at line 282 of file cas_log.c.
References assert, BROKER_PATH_MAX, cas_fseek(), cas_log_write_internal(), cas_rename(), log_filepath, NULL, and saved_log_fpos.
Referenced by cas_log_end().
void cas_log_write_client_ip (const unsigned char * ip_addr)
Definition at line 686 of file cas_log.c.
References cas_log_write_and_end(), NULL, and ut_get_ipv4_string().
Referenced by net_read_process().
static void cas_log_write_internal (FILE * fp, struct timeval * log_time, unsigned int seq_num, bool do_flush, const char * fmt, va_list ap) static
Definition at line 403 of file cas_log.c.
References cas_fflush(), cas_fwrite(), cas_log_buffer, CAS_LOG_BUFFER_SIZE, p, and ut_time_string().
Referenced by cas_log_query_cancel(), cas_log_write(), cas_log_write_and_end(), cas_log_write_and_set_savedpos(), cas_log_write_nonl(), cas_slow_log_write(), and cas_slow_log_write_and_end().
void cas_log_write_nonl (unsigned int seq_num, bool unit_start, const char * fmt, ...)
Definition at line 442 of file cas_log.c.
References as_info, t_shm_appl_server::broker_name, cas_ftell(), cas_log_open(), cas_log_write_internal(), t_appl_server_info::cur_sql_log_mode, log_fp, NULL, saved_log_fpos, shm_appl, SQL_LOG_MODE_ALL, and SQL_LOG_MODE_NONE.
Referenced by bind_value_log(), fn_execute_array(), fn_execute_internal(), fn_prepare_internal(), and ux_execute_batch().
void cas_log_write_query_string (char * query, int size)
Definition at line 647 of file cas_log.c.
References cas_log_write_query_string_internal().
Referenced by fn_execute_array(), fn_execute_internal(), and fn_prepare_internal().
static void cas_log_write_query_string_internal (char * query, int size, bool newline) static
Definition at line 653 of file cas_log.c.
References as_info, t_shm_appl_server::broker_name, cas_fputc(), cas_log_open(), t_appl_server_info::cur_sql_log_mode, log_fp, NULL, shm_appl, and SQL_LOG_MODE_NONE.
Referenced by cas_log_write_query_string(), and cas_log_write_query_string_nonl().
void cas_log_write_query_string_nonl (char * query, int size)
Definition at line 641 of file cas_log.c.
References cas_log_write_query_string_internal().
Referenced by ux_execute_batch().
void cas_log_write_value_string (char * value, int size)
Definition at line 625 of file cas_log.c.
References as_info, t_shm_appl_server::broker_name, cas_fwrite(), cas_log_open(), t_appl_server_info::cur_sql_log_mode, log_fp, NULL, shm_appl, and SQL_LOG_MODE_NONE.
Referenced by bind_value_print().
static int cas_mkdir (const char * pathname, mode_t mode) static
Definition at line 1394 of file cas_log.c.
References cas_log_begin_hang_check_time(), and cas_log_end_hang_check_time().
Referenced by access_log_open().
static int cas_rename (const char * oldpath, const char * newpath) static
Definition at line 1381 of file cas_log.c.
References cas_log_begin_hang_check_time(), and cas_log_end_hang_check_time().
Referenced by cas_log_backup(), and cas_log_write_and_set_savedpos().
void cas_slow_log_close (void)
Definition at line 1021 of file cas_log.c.
References cas_fclose(), NULL, and slow_log_fp.
Referenced by cas_free(), cas_main(), cas_slow_log_end(), cas_slow_log_open(), cas_slow_log_reset(), and shard_cas_main().
void cas_slow_log_end (void)
Definition at line 1033 of file cas_log.c.
References as_info, t_shm_appl_server::broker_name, cas_fflush(), cas_fputc(), cas_ftell(), cas_log_backup(), cas_slow_log_close(), cas_slow_log_open(), t_appl_server_info::cur_slow_log_mode, FID_SLOW_LOG_DIR, NULL, shm_appl, slow_log_fp, SLOW_LOG_MODE_OFF, and t_shm_appl_server::sql_log_max_size.
Referenced by cas_slow_log_write_and_end(), fn_execute_array(), and fn_execute_internal().
void cas_slow_log_open (char * br_name)
Definition at line 966 of file cas_log.c.
References as_info, BROKER_PATH_MAX, cas_fopen(), CAS_LOG_RESET_REOPEN, cas_slow_log_close(), t_appl_server_info::cas_slow_log_reset, t_appl_server_info::cur_slow_log_mode, FID_SLOW_LOG_DIR, make_sql_log_filename(), NULL, set_cubrid_file(), shm_appl, t_shm_appl_server::slow_log_dir, slow_log_filepath, slow_log_fp, and SLOW_LOG_MODE_OFF.
Referenced by cas_main(), cas_slow_log_end(), cas_slow_log_reset(), cas_slow_log_write(), cas_slow_log_write2(), cas_slow_log_write_and_end(), cas_slow_log_write_query_string(), cas_slow_log_write_value_string(), and shard_cas_main().
void cas_slow_log_reset (char * br_name)
Definition at line 998 of file cas_log.c.
References as_info, CAS_LOG_RESET_REMOVE, cas_slow_log_close(), cas_slow_log_open(), t_appl_server_info::cas_slow_log_reset, cas_unlink(), t_appl_server_info::cur_slow_log_mode, NULL, slow_log_filepath, slow_log_fp, and SLOW_LOG_MODE_OFF.
Referenced by fn_end_tran(), net_read_int_keep_con_auto(), and process_request().
void cas_slow_log_write (struct timeval * log_time, unsigned int seq_num, bool unit_start, const char * fmt, ...)
Definition at line 1085 of file cas_log.c.
References as_info, t_shm_appl_server::broker_name, cas_log_write_internal(), cas_slow_log_open(), t_appl_server_info::cur_slow_log_mode, NULL, shm_appl, slow_log_fp, and SLOW_LOG_MODE_OFF.
Referenced by bind_value_log(), fn_execute_array(), and fn_execute_internal().
void cas_slow_log_write2 (const char * fmt, ...)
Definition at line 1105 of file cas_log.c.
References as_info, t_shm_appl_server::broker_name, cas_log_write2_internal(), cas_slow_log_open(), t_appl_server_info::cur_slow_log_mode, NULL, shm_appl, slow_log_fp, and SLOW_LOG_MODE_OFF.
Referenced by bind_value_log(), and bind_value_print().
void cas_slow_log_write_and_end (struct timeval * log_time, unsigned int seq_num, const char * fmt, ...)
Definition at line 1062 of file cas_log.c.
References as_info, t_shm_appl_server::broker_name, cas_log_write_internal(), cas_slow_log_end(), cas_slow_log_open(), t_appl_server_info::cur_slow_log_mode, NULL, shm_appl, slow_log_fp, and SLOW_LOG_MODE_OFF.
Referenced by cas_main().
void cas_slow_log_write_query_string (char * query, int size)
Definition at line 1141 of file cas_log.c.
References as_info, t_shm_appl_server::broker_name, cas_fputc(), cas_slow_log_open(), t_appl_server_info::cur_slow_log_mode, NULL, shm_appl, slow_log_fp, and SLOW_LOG_MODE_OFF.
Referenced by fn_execute_array(), and fn_execute_internal().
void cas_slow_log_write_value_string (char * value, int size)
Definition at line 1125 of file cas_log.c.
References as_info, t_shm_appl_server::broker_name, cas_fwrite(), cas_slow_log_open(), t_appl_server_info::cur_slow_log_mode, NULL, shm_appl, slow_log_fp, and SLOW_LOG_MODE_OFF.
Referenced by bind_value_print().
static int cas_unlink (const char * pathname) static
Definition at line 1368 of file cas_log.c.
References cas_log_begin_hang_check_time(), and cas_log_end_hang_check_time().
Referenced by cas_log_backup(), cas_log_query_info_init(), cas_log_reset(), and cas_slow_log_reset().
static const char * get_access_log_type_string (ACCESS_LOG_TYPE type) static
Definition at line 1417 of file cas_log.c.
References ACL_REJECTED, assert, CLIENT_CHANGED, and NEW_CONNECTION.
Referenced by cas_access_log().
static char * make_sql_log_filename (T_CUBRID_FILE_ID fid, char * filename_buf, size_t buf_size, const char * br_name) static
Definition at line 114 of file cas_log.c.
References assert, BROKER_PATH_MAX, cas_shard_flag, dirname(), FID_SLOW_LOG_DIR, FID_SQL_LOG_DIR, get_cubrid_file(), NULL, ON, shm_as_index, shm_proxy_id, shm_shard_cas_id, and shm_shard_id.
Referenced by cas_log_open(), and cas_slow_log_open().
Variable Documentation
char cas_log_buffer[CAS_LOG_BUFFER_SIZE] static
Definition at line 67 of file cas_log.c.
Referenced by cas_log_write2_internal(), and cas_log_write_internal().
char log_filepath[BROKER_PATH_MAX] static
Definition at line 92 of file cas_log.c.
Referenced by cas_log_backup(), cas_log_open(), cas_log_reset(), cas_log_write_and_set_savedpos(), and check_proxy_log().
FILE* log_fp = NULL static
Definition at line 91 of file cas_log.c.
Referenced by cas_log_close(), cas_log_debug(), cas_log_end(), cas_log_open(), cas_log_query_cancel(), cas_log_reset(), cas_log_write(), cas_log_write2(), cas_log_write2_nonl(), cas_log_write_and_end(), cas_log_write_nonl(), cas_log_write_query_string_internal(), cas_log_write_value_string(), event_log_log_flush_thr_wait(), event_log_many_ioreads(), event_log_slow_query(), event_log_temp_expand_pages(), lock_detect_local_deadlock(), and lock_wait_state_to_string().
INT64 saved_log_fpos = 0 static
Definition at line 93 of file cas_log.c.
Referenced by cas_log_close(), cas_log_end(), cas_log_open(), cas_log_write(), cas_log_write_and_end(), cas_log_write_and_set_savedpos(), and cas_log_write_nonl().
char slow_log_filepath[BROKER_PATH_MAX] static
Definition at line 92 of file cas_log.c.
Referenced by cas_log_backup(), cas_slow_log_open(), and cas_slow_log_reset().
FILE * slow_log_fp = NULL static
Definition at line 91 of file cas_log.c.
Referenced by cas_slow_log_close(), cas_slow_log_end(), cas_slow_log_open(), cas_slow_log_reset(), cas_slow_log_write(), cas_slow_log_write2(), cas_slow_log_write_and_end(), cas_slow_log_write_query_string(), and cas_slow_log_write_value_string().
char sql_log_buffer[SQL_LOG_BUFFER_SIZE] static
Definition at line 68 of file cas_log.c.
Referenced by cas_log_open().