CUBRID Engine: src/broker/cas_meta.c File Reference
cas_meta.c File Reference
#include <assert.h>
#include "porting.h"
#include "cas_protocol.h"
Macros
#define SET_BIT(C, B) ((C) |= (B))
#define CLEAR_BIT(C, B) ((C) &= ~(B))
#define IS_SET_BIT(C, B) (((C) & (B)) == (B))
Enumerations
enum BI_FUNCTION_CODE { BI_FUNC_ERROR_CODE, BI_FUNC_SUPPORT_HOLDABLE_RESULT }
Functions
const char * cas_bi_get_broker_info (void)
void cas_bi_set_dbms_type (const char dbms_type)
char cas_bi_get_dbms_type (void)
void cas_bi_set_keep_connection (const char keep_connection)
char cas_bi_get_keep_connection (void)
void cas_bi_set_statement_pooling (const char statement_pooling)
char cas_bi_get_statement_pooling (void)
void cas_bi_set_cci_pconnect (const char cci_pconnect)
char cas_bi_get_cci_pconnect (void)
void cas_bi_set_protocol_version (const char protocol_version)
char cas_bi_get_protocol_version (void)
static void cas_bi_set_function_enable (BI_FUNCTION_CODE function_code)
static void cas_bi_set_function_disable (BI_FUNCTION_CODE function_code)
static bool cas_bi_is_enabled_function (BI_FUNCTION_CODE function_code)
void cas_bi_set_renewed_error_code (const bool renewed_error_code)
bool cas_bi_get_renewed_error_code (void)
bool cas_di_understand_renewed_error_code (const char *driver_info)
void cas_bi_make_broker_info (char *broker_info, char dbms_type, char statement_pooling, char cci_pconnect)
Variables
static char broker_info [BROKER_INFO_SIZE]
Macro Definition Documentation
#define CLEAR_BIT (C, B) ((C) &= ~(B))
Definition at line 31 of file cas_meta.c.
Referenced by cas_bi_set_function_disable().
#define IS_SET_BIT (C, B) (((C) & (B)) == (B))
Definition at line 32 of file cas_meta.c.
Referenced by cas_bi_is_enabled_function(), and cas_di_understand_renewed_error_code().
#define SET_BIT (C, B) ((C) |= (B))
Definition at line 30 of file cas_meta.c.
Referenced by cas_bi_set_function_enable().
Enumeration Type Documentation
enum BI_FUNCTION_CODE
Enumerator
BI_FUNC_ERROR_CODE
BI_FUNC_SUPPORT_HOLDABLE_RESULT
Definition at line 45 of file cas_meta.c.
Function Documentation
const char* cas_bi_get_broker_info (void)
Definition at line 52 of file cas_meta.c.
References broker_info.
Referenced by cas_send_connect_reply_to_driver().
char cas_bi_get_cci_pconnect (void)
Definition at line 118 of file cas_meta.c.
References broker_info, and BROKER_INFO_CCI_PCONNECT.
char cas_bi_get_dbms_type (void)
Definition at line 64 of file cas_meta.c.
References broker_info, and BROKER_INFO_DBMS_TYPE.
char cas_bi_get_keep_connection (void)
Definition at line 76 of file cas_meta.c.
References broker_info, and BROKER_INFO_KEEP_CONNECTION.
char cas_bi_get_protocol_version (void)
Definition at line 130 of file cas_meta.c.
References broker_info, and BROKER_INFO_PROTO_VERSION.
bool cas_bi_get_renewed_error_code (void)
Definition at line 197 of file cas_meta.c.
References BI_FUNC_ERROR_CODE, and cas_bi_is_enabled_function().
char cas_bi_get_statement_pooling (void)
Definition at line 97 of file cas_meta.c.
References broker_info, and BROKER_INFO_STATEMENT_POOLING.
static bool cas_bi_is_enabled_function (BI_FUNCTION_CODE function_code) static
Definition at line 170 of file cas_meta.c.
References BI_FUNC_ERROR_CODE, BI_FUNC_SUPPORT_HOLDABLE_RESULT, broker_info, BROKER_INFO_FUNCTION_FLAG, BROKER_RENEWED_ERROR_CODE, BROKER_SUPPORT_HOLDABLE_RESULT, and IS_SET_BIT.
Referenced by cas_bi_get_renewed_error_code().
void cas_bi_make_broker_info (char * broker_info, char dbms_type, char statement_pooling, char cci_pconnect)
Definition at line 214 of file cas_meta.c.
References BROKER_INFO_CCI_PCONNECT, BROKER_INFO_DBMS_TYPE, BROKER_INFO_FUNCTION_FLAG, BROKER_INFO_KEEP_CONNECTION, BROKER_INFO_PROTO_VERSION, BROKER_INFO_RESERVED2, BROKER_INFO_RESERVED3, BROKER_INFO_STATEMENT_POOLING, BROKER_RENEWED_ERROR_CODE, BROKER_SUPPORT_HOLDABLE_RESULT, CAS_KEEP_CONNECTION_ON, CAS_PROTO_PACK_CURRENT_NET_VER, CAS_STATEMENT_POOLING_OFF, CAS_STATEMENT_POOLING_ON, CCI_PCONNECT_OFF, and CCI_PCONNECT_ON.
Referenced by proxy_io_make_client_dbinfo_ok().
void cas_bi_set_cci_pconnect (const char cci_pconnect)
Definition at line 103 of file cas_meta.c.
References assert, broker_info, BROKER_INFO_CCI_PCONNECT, CCI_PCONNECT_OFF, and CCI_PCONNECT_ON.
Referenced by cas_main().
void cas_bi_set_dbms_type (const char dbms_type)
Definition at line 58 of file cas_meta.c.
References broker_info, and BROKER_INFO_DBMS_TYPE.
Referenced by cas_main().
static void cas_bi_set_function_disable (BI_FUNCTION_CODE function_code) static
Definition at line 153 of file cas_meta.c.
References assert, BI_FUNC_ERROR_CODE, BI_FUNC_SUPPORT_HOLDABLE_RESULT, broker_info, BROKER_INFO_FUNCTION_FLAG, BROKER_RENEWED_ERROR_CODE, BROKER_SUPPORT_HOLDABLE_RESULT, and CLEAR_BIT.
Referenced by cas_bi_set_renewed_error_code().
static void cas_bi_set_function_enable (BI_FUNCTION_CODE function_code) static
Definition at line 136 of file cas_meta.c.
References assert, BI_FUNC_ERROR_CODE, BI_FUNC_SUPPORT_HOLDABLE_RESULT, broker_info, BROKER_INFO_FUNCTION_FLAG, BROKER_RENEWED_ERROR_CODE, BROKER_SUPPORT_HOLDABLE_RESULT, and SET_BIT.
Referenced by cas_bi_set_renewed_error_code().
void cas_bi_set_keep_connection (const char keep_connection)
Definition at line 70 of file cas_meta.c.
References broker_info, and BROKER_INFO_KEEP_CONNECTION.
void cas_bi_set_protocol_version (const char protocol_version)
Definition at line 124 of file cas_meta.c.
References broker_info, and BROKER_INFO_PROTO_VERSION.
void cas_bi_set_renewed_error_code (const bool renewed_error_code)
Definition at line 184 of file cas_meta.c.
References BI_FUNC_ERROR_CODE, cas_bi_set_function_disable(), and cas_bi_set_function_enable().
void cas_bi_set_statement_pooling (const char statement_pooling)
Definition at line 82 of file cas_meta.c.
References assert, broker_info, BROKER_INFO_STATEMENT_POOLING, CAS_STATEMENT_POOLING_OFF, and CAS_STATEMENT_POOLING_ON.
Referenced by cas_main().
bool cas_di_understand_renewed_error_code (const char * driver_info)
Definition at line 203 of file cas_meta.c.
References BROKER_RENEWED_ERROR_CODE, CAS_PROTO_INDICATOR, DRIVER_INFO_FUNCTION_FLAG, IS_SET_BIT, and SRV_CON_MSG_IDX_PROTO_VERSION.
Referenced by net_buf_error_msg_set(), net_write_error(), proxy_convert_error_code(), and send_error_to_driver().
Variable Documentation
char broker_info[BROKER_INFO_SIZE] static
Initial value:
= {
  CAS_DBMS_CUBRID,
  CAS_KEEP_CONNECTION_ON,
  CAS_STATEMENT_POOLING_ON,
  CCI_PCONNECT_ON,
  CAS_PROTO_PACK_CURRENT_NET_VER,
  (char) BROKER_RENEWED_ERROR_CODE | (char) BROKER_SUPPORT_HOLDABLE_RESULT,
  0,
  0
}
Definition at line 34 of file cas_meta.c.
Referenced by cas_bi_get_broker_info(), cas_bi_get_cci_pconnect(), cas_bi_get_dbms_type(), cas_bi_get_keep_connection(), cas_bi_get_protocol_version(), cas_bi_get_statement_pooling(), cas_bi_is_enabled_function(), cas_bi_set_cci_pconnect(), cas_bi_set_dbms_type(), cas_bi_set_function_disable(), cas_bi_set_function_enable(), cas_bi_set_keep_connection(), cas_bi_set_protocol_version(), cas_bi_set_statement_pooling(), and proxy_io_make_client_dbinfo_ok().