CUBRID Engine: src/broker/cas_schema_info.c File Reference
cas_schema_info.c File Reference
#include <stdio.h>
#include "cas.h"
#include "cas_schema_info.h"
#include "cas_common.h"
#include "cas_net_buf.h"
#include "language_support.h"
Functions
void schema_table_meta (T_NET_BUF *net_buf)
void schema_query_spec_meta (T_NET_BUF *net_buf)
void schema_attr_meta (T_NET_BUF *net_buf)
void schema_method_meta (T_NET_BUF *net_buf)
void schema_methodfile_meta (T_NET_BUF *net_buf)
void schema_superclasss_meta (T_NET_BUF *net_buf)
void schema_constraint_meta (T_NET_BUF *net_buf)
void schema_trigger_meta (T_NET_BUF *net_buf)
void schema_classpriv_meta (T_NET_BUF *net_buf)
void schema_attrpriv_meta (T_NET_BUF *net_buf)
void schema_directsuper_meta (T_NET_BUF *net_buf)
void schema_primarykey_meta (T_NET_BUF *net_buf)
void schema_fk_info_meta (T_NET_BUF *net_buf)
Function Documentation
void schema_attr_meta (T_NET_BUF * net_buf)
Definition at line 56 of file cas_schema_info.c.
References CAS_SCHEMA_DEFAULT_CHARSET, net_buf_column_info_set(), net_buf_cp_int(), NULL, SCH_REMARKS_STR_LEN, and SCH_STR_LEN.
Referenced by sch_attr_info().
void schema_attrpriv_meta (T_NET_BUF * net_buf)
Definition at line 140 of file cas_schema_info.c.
References CAS_SCHEMA_DEFAULT_CHARSET, net_buf_column_info_set(), net_buf_cp_int(), NULL, and SCH_STR_LEN.
Referenced by sch_attr_priv().
void schema_classpriv_meta (T_NET_BUF * net_buf)
Definition at line 131 of file cas_schema_info.c.
References CAS_SCHEMA_DEFAULT_CHARSET, net_buf_column_info_set(), net_buf_cp_int(), NULL, and SCH_STR_LEN.
Referenced by sch_class_priv().
void schema_constraint_meta (T_NET_BUF * net_buf)
Definition at line 100 of file cas_schema_info.c.
References CAS_SCHEMA_DEFAULT_CHARSET, net_buf_column_info_set(), net_buf_cp_int(), NULL, and SCH_STR_LEN.
Referenced by sch_constraint().
void schema_directsuper_meta (T_NET_BUF * net_buf)
Definition at line 149 of file cas_schema_info.c.
References CAS_SCHEMA_DEFAULT_CHARSET, net_buf_column_info_set(), net_buf_cp_int(), NULL, and SCH_STR_LEN.
Referenced by sch_direct_super_class().
void schema_fk_info_meta (T_NET_BUF * net_buf)
Definition at line 167 of file cas_schema_info.c.
References CAS_SCHEMA_DEFAULT_CHARSET, net_buf_column_info_set(), net_buf_cp_int(), NULL, and SCH_STR_LEN.
Referenced by sch_exported_keys_or_cross_reference(), and sch_imported_keys().
void schema_method_meta (T_NET_BUF * net_buf)
Definition at line 76 of file cas_schema_info.c.
References CAS_SCHEMA_DEFAULT_CHARSET, net_buf_column_info_set(), net_buf_cp_int(), NULL, and SCH_STR_LEN.
Referenced by sch_method_info().
void schema_methodfile_meta (T_NET_BUF * net_buf)
Definition at line 85 of file cas_schema_info.c.
References CAS_SCHEMA_DEFAULT_CHARSET, net_buf_column_info_set(), net_buf_cp_int(), NULL, and SCH_STR_LEN.
Referenced by sch_methfile_info().
void schema_primarykey_meta (T_NET_BUF * net_buf)
Definition at line 157 of file cas_schema_info.c.
References CAS_SCHEMA_DEFAULT_CHARSET, net_buf_column_info_set(), net_buf_cp_int(), NULL, and SCH_STR_LEN.
Referenced by sch_primary_key().
void schema_query_spec_meta (T_NET_BUF * net_buf)
Definition at line 49 of file cas_schema_info.c.
References CAS_SCHEMA_DEFAULT_CHARSET, net_buf_column_info_set(), net_buf_cp_int(), NULL, and SCH_STR_LEN.
Referenced by sch_queryspec().
void schema_superclasss_meta (T_NET_BUF * net_buf)
Definition at line 92 of file cas_schema_info.c.
References CAS_SCHEMA_DEFAULT_CHARSET, net_buf_column_info_set(), net_buf_cp_int(), NULL, and SCH_STR_LEN.
Referenced by sch_superclass().
void schema_table_meta (T_NET_BUF * net_buf)
Definition at line 39 of file cas_schema_info.c.
References CAS_SCHEMA_DEFAULT_CHARSET, net_buf_column_info_set(), net_buf_cp_int(), NULL, SCH_CLASS_REMARKS_STR_LEN, and SCH_STR_LEN.
Referenced by sch_class_info().
void schema_trigger_meta (T_NET_BUF * net_buf)
Definition at line 114 of file cas_schema_info.c.
References CAS_SCHEMA_DEFAULT_CHARSET, net_buf_column_info_set(), net_buf_cp_int(), NULL, SCH_REMARKS_STR_LEN, and SCH_STR_LEN.
Referenced by sch_trigger().