CUBRID Engine: src/broker/cas_dbms_util.c File Reference
cas_dbms_util.c File Reference
#include "assert.h"
#include "porting.h"
#include "environment_variable.h"
#include "cas.h"
#include "cas_execute.h"
#include "cas_error.h"
#include "broker_filename.h"
Macros
#define _ENVVAR_MAX_LENGTH 255
Functions
static char * cfg_pop_token (char *str_p, char **token_p)
void cfg_free_dbinfo_all (DB_INFO *databases)
int cfg_get_dbinfo (char *alias, char *dbinfo)
int cfg_read_dbinfo (DB_INFO **db_info_p)
DB_INFO * cfg_find_db_list (DB_INFO *db_info_list_p, const char *name)
int char_is_delim (int c, int delim)
char * char_get_next (char *str_p)
UINT64 ntohi64 (UINT64 from)
int char_islower (int c)
int char_isupper (int c)
int char_isalpha (int c)
int char_tolower (int c)
Variables
static const char envvar_Prefix_name [] = "CUBRID"
static const char * envvar_Prefix = NULL
static const char * envvar_Root = NULL
Macro Definition Documentation
#define _ENVVAR_MAX_LENGTH 255
Definition at line 46 of file cas_dbms_util.c.
Function Documentation
DB_INFO* cfg_find_db_list (DB_INFO * db_info_list_p, const char * name)
Definition at line 231 of file cas_dbms_util.c.
References database_info::alias, database_info::name, database_info::next, and NULL.
void cfg_free_dbinfo_all (DB_INFO * databases)
Definition at line 51 of file cas_dbms_util.c.
References database_info::alias, database_info::dbinfo, free_and_init, database_info::next, and NULL.
Referenced by cfg_read_dbinfo().
int cfg_get_dbinfo (char * alias, char * dbinfo)
Definition at line 72 of file cas_dbms_util.c.
References BROKER_PATH_MAX, CAS_ER_ARGS, CAS_ER_OPEN_FILE, CAS_ERROR_INDICATOR, t_shm_appl_server::db_connection_file, DBINFO_MAX_LENGTH, envvar_confdir_file(), ERROR_INFO_SET, FID_CAS_FOR_MYSQL_DBINFO, FID_CAS_FOR_ORACLE_DBINFO, get_cubrid_file(), IS_ABS_PATH, NULL, and shm_appl.
static char * cfg_pop_token (char * str_p, char ** token_p) static
Definition at line 295 of file cas_dbms_util.c.
References char_is_delim(), NULL, and p.
Referenced by cfg_read_dbinfo().
int cfg_read_dbinfo (DB_INFO ** db_info_p)
Definition at line 133 of file cas_dbms_util.c.
References database_info::alias, BROKER_PATH_MAX, CAS_ER_ARGS, CAS_ER_NO_MORE_MEMORY, CAS_ER_OPEN_FILE, CAS_ERROR_INDICATOR, cfg_free_dbinfo_all(), cfg_pop_token(), char_get_next(), t_shm_appl_server::db_connection_file, database_info::dbinfo, DBINFO_MAX_LENGTH, envvar_confdir_file(), ERROR_INFO_SET, FID_CAS_FOR_MYSQL_DBINFO, FID_CAS_FOR_ORACLE_DBINFO, get_cubrid_file(), IS_ABS_PATH, database_info::next, NULL, and shm_appl.
char* char_get_next (char * str_p)
Definition at line 268 of file cas_dbms_util.c.
References char_is_delim(), and p.
Referenced by cfg_read_dbinfo().
int char_is_delim (int c, int delim)
Definition at line 255 of file cas_dbms_util.c.
Referenced by cfg_pop_token(), and char_get_next().
int char_isalpha (int c)
Definition at line 378 of file cas_dbms_util.c.
References char_islower(), and char_isupper().
int char_islower (int c)
Definition at line 354 of file cas_dbms_util.c.
Referenced by char_isalpha().
int char_isupper (int c)
Definition at line 366 of file cas_dbms_util.c.
Referenced by char_isalpha(), and char_tolower().
int char_tolower (int c)
Definition at line 389 of file cas_dbms_util.c.
References char_isupper().
UINT64 ntohi64 (UINT64 from)
Definition at line 328 of file cas_dbms_util.c.
Referenced by net_arg_get_bigint(), net_arg_get_lob_handle(), and net_arg_get_size().
Variable Documentation
const char* envvar_Prefix = NULL static
Definition at line 43 of file cas_dbms_util.c.
const char envvar_Prefix_name[] = "CUBRID" static
Definition at line 42 of file cas_dbms_util.c.
const char* envvar_Root = NULL static
Definition at line 44 of file cas_dbms_util.c.