CUBRID Engine: src/broker/cas.c File Reference
cas.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include <assert.h>
#include <unistd.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <sys/socket.h>
#include <sys/time.h>
#include "cas_common.h"
#include "cas.h"
#include "cas_network.h"
#include "cas_function.h"
#include "cas_net_buf.h"
#include "cas_log.h"
#include "cas_util.h"
#include "broker_filename.h"
#include "cas_execute.h"
#include "connection_support.h"
#include "perf_monitor.h"
#include "broker_recv_fd.h"
#include "broker_shm.h"
#include "broker_util.h"
#include "broker_env_def.h"
#include "broker_process_size.h"
#include "cas_sql_log2.h"
#include "broker_acl.h"
#include "dbtype.h"
#include "environment_variable.h"
#include "error_manager.h"
#include "ddl_log.h"
Macros
#define FUNC_NEEDS_RESTORING_CON_STATUS(func_code)
Functions
static FN_RETURN process_request (SOCKET sock_fd, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
static int cas_main (void)
static int shard_cas_main (void)
static void cas_sig_handler (int signo)
static int cas_init (void)
static void cas_final (void)
static void cas_free (bool from_sighandler)
static void query_cancel (int signo)
static int cas_init_shm (void)
static int cas_register_to_proxy (SOCKET proxy_sock_fd)
static int net_read_process (SOCKET proxy_sock_fd, MSG_HEADER *client_msg_header, T_REQ_INFO *req_info)
static int get_graceful_down_timeout (void)
static void set_db_parameter (void)
static int net_read_int_keep_con_auto (SOCKET clt_sock_fd, MSG_HEADER *client_msg_header, T_REQ_INFO *req_info)
static int net_read_header_keep_con_on (SOCKET clt_sock_fd, MSG_HEADER *client_msg_header)
static void set_db_connection_info (void)
static void clear_db_connection_info (void)
static bool need_database_reconnect (void)
int cas_init_ssl (int)
void cas_ssl_close (int client_sock_fd)
static void set_cas_info_size (void)
static void cas_make_session_for_driver (char *out)
static void cas_set_session_id (T_CAS_PROTOCOL protocol, char *session)
static void cas_send_connect_reply_to_driver (T_CAS_PROTOCOL protocol, SOCKET client_sock_fd, char *cas_info)
int main (int argc, char *argv[])
void set_hang_check_time (void)
void unset_hang_check_time (void)
bool check_server_alive (const char *db_name, const char *db_host)
int restart_is_needed (void)
int query_seq_num_next_value (void)
int query_seq_num_current_value (void)
T_BROKER_VERSION cas_get_client_version (void)
Variables
static const int DEFAULT_CHECK_INTERVAL = 1
bool ssl_client
static char cas_db_name [MAX_HA_DBINFO_LENGTH]
static char cas_db_user [SRV_CON_DBUSER_SIZE]
static char cas_db_passwd [SRV_CON_DBPASSWD_SIZE]
static int query_sequence_num = 0
int cas_shard_flag = OFF
int shm_shard_id = SHARD_ID_UNSUPPORTED
const char * program_name
char broker_name [BROKER_NAME_LEN]
int psize_at_start
int shm_as_index
T_SHM_APPL_SERVER * shm_appl
T_APPL_SERVER_INFO * as_info
int shm_proxy_id = -1
int shm_shard_cas_id = -1
struct timeval tran_start_time
struct timeval query_start_time
int tran_timeout = 0
int query_timeout = 0
INT64 query_cancel_time
char query_cancel_flag
bool autocommit_deferred = false
int errors_in_transaction = 0
char stripped_column_name
char cas_client_type
int con_status_before_check_cas
bool is_first_request
SOCKET new_req_sock_fd = INVALID_SOCKET
int cas_default_isolation_level = 0
int cas_default_lock_timeout = -1
bool cas_default_ansi_quotes = true
bool cas_default_no_backslash_escapes = true
int cas_send_result_flag = TRUE
int cas_info_size = CAS_INFO_SIZE
char prev_cas_info [CAS_INFO_SIZE]
T_ERROR_INFO err_info
static T_SERVER_FUNC server_fn_table []
static const char * server_func_name []
static T_REQ_INFO req_info
static SOCKET srv_sock_fd
static int cas_req_count = 0
Macro Definition Documentation
#define FUNC_NEEDS_RESTORING_CON_STATUS (func_code)
Value:
(((func_code) == CAS_FC_GET_DB_PARAMETER) \
   ||((func_code) == CAS_FC_SET_DB_PARAMETER) \
   ||((func_code) == CAS_FC_CLOSE_REQ_HANDLE) \
   ||((func_code) == CAS_FC_GET_DB_VERSION) \
   ||((func_code) == CAS_FC_GET_ATTR_TYPE_STR) \
   ||((func_code) == CAS_FC_CURSOR_CLOSE) \
   ||((func_code) == CAS_FC_END_SESSION)  \
   ||((func_code) == CAS_FC_CAS_CHANGE_MODE))
Definition at line 87 of file cas.c.
Referenced by process_request().
Function Documentation
static void cas_final (void) static
Definition at line 1572 of file cas.c.
References cas_free(), ER_ALL_FINAL, er_final(), t_appl_server_info::pid, t_appl_server_info::uts_status, and UTS_STATUS_RESTART.
Referenced by cas_main(), and shard_cas_main().
static void cas_free (bool from_sighandler) static
Definition at line 1584 of file cas.c.
References t_shm_appl_server::appl_server_hard_limit, t_shm_appl_server::appl_server_max_size, ARG_FILE_LINE, cas_error_log_close(), cas_log_close(), cas_log_debug(), cas_log_write_and_end(), cas_req_count, cas_slow_log_close(), t_appl_server_info::cur_statement_pooling, t_appl_server_info::database_host, t_appl_server_info::database_name, t_appl_server_info::database_passwd, t_appl_server_info::database_user, hm_srv_handle_free_all(), t_appl_server_info::last_connect_time, logddl_destroy(), ONE_K, t_appl_server_info::pid, t_appl_server_info::psize, psize_at_start, and ux_database_shutdown().
Referenced by cas_final(), and cas_sig_handler().
T_BROKER_VERSION cas_get_client_version (void)
Definition at line 2947 of file cas.c.
References t_req_info::client_version.
Referenced by cas_main(), shard_cas_main(), and ux_get_generated_keys_server_insert().
static int cas_init (void) static
Definition at line 2244 of file cas.c.
References as_db_err_log_set(), t_appl_server_info::as_id, as_pid_file_create(), broker_name, t_shm_appl_server::broker_name, BROKER_NAME_LEN, cas_init_shm(), cas_shard_flag, check_server_alive(), css_register_check_server_alive_fn(), css_register_server_timeout_fn(), t_shm_appl_server::err_log_dir, FID_CUBRID_ERR_DIR, FID_SLOW_LOG_DIR, FID_SQL_LOG_DIR, t_shm_appl_server::log_dir, OFF, set_cubrid_file(), set_hang_check_time(), shm_as_index, shm_proxy_id, shm_shard_cas_id, shm_shard_id, and t_shm_appl_server::slow_log_dir.
Referenced by main().
static int cas_init_shm (void) static
Definition at line 2815 of file cas.c.
References APPL_SERVER_SHM_KEY_STR, AS_ID_ENV_STR, t_shm_appl_server::as_info, cas_shard_flag, t_appl_server_info::cur_keep_con, NULL, OFF, p, parse_int(), t_appl_server_info::proxy_id, t_appl_server_info::shard_cas_id, SHARD_ERR, t_shm_appl_server::shard_flag, t_appl_server_info::shard_id, SHM_APPL_SERVER, shm_as_index, SHM_MODE_ADMIN, shm_proxy_id, shm_shard_cas_id, shm_shard_id, uw_shm_detach(), and uw_shm_open().
Referenced by cas_init().
int cas_init_ssl (int)
Definition at line 86 of file cas_ssl.c.
References cas_log_write(), cas_log_write_and_end(), cas_ssl_validity_check(), CERT_FILENAME_LEN, CERTF, ER_CERT_COPPUPTED, ER_CERT_EXPIRED, ER_SSL_GENERAL, err, KEYF, NULL, SOCKET_BLOCK, SOCKET_NONBLOCK, ssl, and ssl_client.
Referenced by cas_main().
static int cas_main (void) static
Definition at line 785 of file cas.c.
References t_shm_appl_server::access_control, access_control_check_right(), t_shm_appl_server::access_log, ACL_REJECTED, t_net_buf::alloc_size, APP_NAME_CAS, t_shm_appl_server::appl_server_hard_limit, t_shm_appl_server::appl_server_max_size, ARG_FILE_LINE, as_db_err_log_set(), assert, t_appl_server_info::auto_commit_mode, broker_name, t_shm_appl_server::broker_name, BROKER_PATH_MAX, BROKER_RENEWED_ERROR_CODE, BROKER_SUPPORT_HOLDABLE_RESULT, cas_access_log(), cas_bi_set_cci_pconnect(), cas_bi_set_dbms_type(), cas_bi_set_statement_pooling(), CAS_CLIENT_SERVER_SIDE_JDBC, cas_client_type, t_appl_server_info::cas_client_type, t_appl_server_info::cas_clt_ip, t_appl_server_info::cas_clt_port, CAS_DBMS_MYSQL, CAS_DBMS_ORACLE, cas_default_isolation_level, cas_default_lock_timeout, CAS_ER_COMMUNICATION, CAS_ER_NOT_AUTHORIZED_CLIENT, t_appl_server_info::cas_err_log_reset, CAS_ERROR_INDICATOR, cas_error_log_close(), cas_error_log_open(), cas_final(), cas_get_client_version(), CAS_INFO_RESERVED_DEFAULT, CAS_INFO_SIZE, cas_info_size, CAS_INFO_STATUS, CAS_INFO_STATUS_ACTIVE, CAS_INFO_STATUS_INACTIVE, cas_init_ssl(), cas_log_close(), cas_log_debug(), cas_log_error_handler_begin(), cas_log_error_handler_clear(), cas_log_error_handler_end(), cas_log_open(), CAS_LOG_RESET_REOPEN, cas_log_write2(), cas_log_write_and_end(), CAS_MAKE_VER, CAS_PROTO_CURRENT_VER, CAS_PROTO_TO_VER_STR, CAS_PROTO_VER_MASK, cas_req_count, cas_send_connect_reply_to_driver(), cas_set_db_connect_status(), cas_set_session_id(), cas_shard_flag, cas_slow_log_close(), cas_slow_log_open(), cas_slow_log_write_and_end(), cas_ssl_close(), CAS_VER_TO_MAJOR, CAS_VER_TO_MINOR, CAS_VER_TO_PATCH, t_appl_server_info::cci_default_autocommit, t_shm_appl_server::cci_default_autocommit, t_shm_appl_server::cci_pconnect, CLIENT_CHANGED, t_req_info::client_version, CLOSE_SOCKET, t_appl_server_info::clt_version, t_appl_server_info::con_status, con_status_before_check_cas, CON_STATUS_CLOSE_AND_CONNECT, CON_STATUS_IN_TRAN, t_appl_server_info::cur_keep_con, t_srv_handle::cur_result, t_appl_server_info::cur_sql_log2, t_appl_server_info::cur_statement_pooling, t_net_buf::data, t_appl_server_info::database_host, t_appl_server_info::database_name, DB_EMPTY_SESSION, db_get_session_id(), db_name, DBMS_ERROR_INDICATOR, DOES_CLIENT_UNDERSTAND_THE_PROTOCOL, t_req_info::driver_info, t_appl_server_info::driver_info, DRIVER_INFO_CLIENT_TYPE, DRIVER_INFO_FUNCTION_FLAG, t_appl_server_info::driver_version, ER_ALL_FINAL, er_final(), er_init(), ER_NEVER_EXIT, t_error_info::err_indicator, t_shm_appl_server::err_log_dir, t_error_info::err_number, error_info_clear(), errors_in_transaction, FALSE, FID_CUBRID_ERR_DIR, FN_CLOSE_CONN, FN_KEEP_CONN, FN_KEEP_SESS, t_appl_server_info::fn_status, FN_STATUS_BUSY, FN_STATUS_CONN, FN_STATUS_DONE, FN_STATUS_IDLE, FREE_MEM, getsize(), HEALTH_CHECK_DUMMY_DB, hm_find_srv_handle(), hm_srv_handle_free(), hm_srv_handle_free_all(), is_first_request, IS_INVALID_SOCKET, is_server_aborted(), IS_SSL_CLIENT, is_xa_prepared(), KEEP_CON_AUTO, KEEP_CON_DEFAULT, t_shm_appl_server::keep_connection, t_appl_server_info::last_access_time, libcas_get_db_result_set(), libcas_main(), libcas_srv_handle_free(), logddl_init(), logddl_set_app_name(), logddl_set_br_index(), logddl_set_br_name(), logddl_set_db_name(), logddl_set_ip(), logddl_set_jsp_mode(), logddl_set_logging_enabled(), logddl_set_pid(), logddl_set_start_time(), logddl_set_user_name(), MALLOC, t_req_info::need_rollback, NET_BUF_ALLOC_SIZE, net_buf_clear(), net_buf_destroy(), net_buf_init(), net_connect_client(), NET_DEFAULT_TIMEOUT, net_init_env(), NET_MIN_TIMEOUT, net_read_int(), net_read_stream(), net_timeout_set(), net_write_error(), net_write_int(), net_write_stream(), NEW_CONNECTION, NULL, t_appl_server_info::num_connect_rejected, OFF, ON, ONE_K, prev_cas_info, prm_get_bool_value(), PRM_ID_DDL_AUDIT_LOG, process_request(), PROTOCOL_V1, PROTOCOL_V5, t_appl_server_info::psize, psize_at_start, query_cancel(), query_cancel_flag, query_start_time, query_timeout, recv_fd(), t_appl_server_info::reset_flag, restart_is_needed(), t_appl_server_info::service_ready_flag, t_appl_server_info::session_id, set_cas_info_size(), set_cubrid_file(), set_hang_check_time(), shm_as_index, shm_proxy_id, shm_shard_cas_id, shm_shard_id, t_shm_appl_server::sql_log2, sql_log2_end(), sql_log2_get_filename(), sql_log2_init(), SRV_CON_CLIENT_INFO_SIZE, SRV_CON_DB_INFO_SIZE, SRV_CON_DB_INFO_SIZE_PRIOR_8_2_0, SRV_CON_DB_INFO_SIZE_PRIOR_8_4_0, SRV_CON_DBNAME_SIZE, SRV_CON_DBPASSWD_SIZE, SRV_CON_DBSESS_ID_SIZE, SRV_CON_DBUSER_SIZE, SRV_CON_URL_SIZE, SRV_CON_VER_STR_MAX_SIZE, srv_sock_fd, ssl_client, t_shm_appl_server::statement_pooling, stripped_column_name, t_shm_appl_server::stripped_column_name, strlen, strncpy_bufsize, tran_start_time, tran_timeout, t_appl_server_info::transaction_start_time, TRUE, unset_hang_check_time(), ut_get_as_port_name(), ut_get_ipv4_string(), ut_set_keepalive(), t_appl_server_info::uts_status, UTS_STATUS_BUSY, UTS_STATUS_IDLE, ux_database_connect(), ux_database_shutdown(), ux_end_session(), ux_end_tran(), and ux_set_default_setting().
Referenced by main().
static void cas_make_session_for_driver (char * out) static
Definition at line 342 of file cas.c.
References db_get_server_session_key(), db_get_session_id(), DRIVER_SESSION_SIZE, htonl(), and SERVER_SESSION_KEY_SIZE.
Referenced by cas_send_connect_reply_to_driver().
static int cas_register_to_proxy (SOCKET proxy_sock_fd) static
Definition at line 2775 of file cas.c.
References cas_log_write_and_end(), init_msg_header(), MSG_HEADER::msg_body_size_ptr, net_write_header(), net_write_int(), net_write_stream(), shm_shard_cas_id, and shm_shard_id.
Referenced by shard_cas_main().
static void cas_send_connect_reply_to_driver (T_CAS_PROTOCOL protocol, SOCKET client_sock_fd, char * cas_info) static
Definition at line 384 of file cas.c.
References BROKER_INFO_SIZE, cas_bi_get_broker_info(), CAS_CONNECTION_REPLY_SIZE, CAS_CONNECTION_REPLY_SIZE_PRIOR_PROTOCOL_V3, CAS_CONNECTION_REPLY_SIZE_V3, cas_info_size, cas_make_session_for_driver(), CAS_PID_SIZE, db_get_session_id(), DOES_CLIENT_UNDERSTAND_THE_PROTOCOL, DRIVER_SESSION_SIZE, htonl(), net_write_stream(), p, PROTOCOL_V3, PROTOCOL_V4, SESSION_ID_SIZE, and shm_as_index.
Referenced by cas_main().
static void cas_set_session_id (T_CAS_PROTOCOL protocol, char * session) static
Definition at line 358 of file cas.c.
References cas_log_write_and_end(), DB_EMPTY_SESSION, db_set_server_session_key(), db_set_session_id(), DOES_CLIENT_UNDERSTAND_THE_PROTOCOL, ntohl(), and PROTOCOL_V3.
Referenced by cas_main().
static void cas_sig_handler (int signo) static
Definition at line 1562 of file cas.c.
References _exit(), cas_free(), t_appl_server_info::pid, t_appl_server_info::uts_status, and UTS_STATUS_RESTART.
Referenced by main().
void cas_ssl_close (int client_sock_fd)
Definition at line 265 of file cas_ssl.c.
References NULL, and ssl.
Referenced by cas_main().
bool check_server_alive (const char * db_name, const char * db_host)
Definition at line 1517 of file cas.c.
References cas_shard_flag, t_appl_server_info::database_host, t_db_server::database_host, t_appl_server_info::database_name, t_db_server::database_name, db_name, i, t_shm_appl_server::monitor_server_flag, NULL, OFF, t_shm_appl_server::unusable_databases, t_shm_appl_server::unusable_databases_cnt, and t_shm_appl_server::unusable_databases_seq.
Referenced by cas_init().
static void clear_db_connection_info (void) static
Definition at line 2629 of file cas.c.
References cas_db_passwd, cas_db_user, t_appl_server_info::database_passwd, t_appl_server_info::database_user, and t_appl_server_info::fixed_shard_user.
Referenced by process_request(), and shard_cas_main().
static int get_graceful_down_timeout (void) static
Definition at line 2887 of file cas.c.
References t_appl_server_info::advance_activate_flag.
Referenced by net_read_process(), and process_request().
int main (int argc, char * argv[])
Definition at line 454 of file cas.c.
References APPL_SERVER_CAS_MYSQL_NAME, APPL_SERVER_CAS_NAME, APPL_SERVER_CAS_ORACLE_NAME, cas_init(), cas_main(), cas_shard_flag, cas_sig_handler(), makestring, ON, program_name, set_cubrid_home(), and shard_cas_main().
static bool need_database_reconnect (void) static
Definition at line 2643 of file cas.c.
References cas_db_passwd, cas_db_user, t_appl_server_info::database_passwd, t_appl_server_info::database_user, and t_appl_server_info::force_reconnect.
Referenced by process_request().
static int net_read_header_keep_con_on (SOCKET clt_sock_fd, MSG_HEADER * client_msg_header) static
Definition at line 2549 of file cas.c.
References t_appl_server_info::con_status, CON_STATUS_IN_TRAN, CON_STATUS_OUT_TRAN, DEFAULT_CHECK_INTERVAL, is_net_timed_out(), net_read_header(), net_timeout_set(), t_appl_server_info::reset_flag, t_shm_appl_server::session_timeout, and TRUE.
Referenced by process_request().
static int net_read_int_keep_con_auto (SOCKET clt_sock_fd, MSG_HEADER * client_msg_header, T_REQ_INFO * req_info) static
Definition at line 2420 of file cas.c.
References ARG_FILE_LINE, t_shm_appl_server::as_info, broker_name, cas_log_debug(), cas_log_reset(), t_appl_server_info::cas_log_reset, t_appl_server_info::cas_slow_log_reset, cas_slow_log_reset(), t_appl_server_info::con_status, CON_STATUS_CLOSE, CON_STATUS_CLOSE_AND_CONNECT, CON_STATUS_IN_TRAN, CON_STATUS_LOCK, CON_STATUS_LOCK_CAS, CON_STATUS_OUT_TRAN, CON_STATUS_UNLOCK, DEFAULT_CHECK_INTERVAL, errors_in_transaction, INVALID_SOCKET, is_net_timed_out(), logddl_set_start_time(), net_read_header(), net_timeout_set(), new_req_sock_fd, NULL, t_appl_server_info::num_request, t_appl_server_info::reset_flag, restart_is_needed(), t_shm_appl_server::session_timeout, shm_as_index, srv_sock_fd, tran_start_time, t_appl_server_info::transaction_start_time, and TRUE.
Referenced by process_request().
static int net_read_process (SOCKET proxy_sock_fd, MSG_HEADER * client_msg_header, T_REQ_INFO * req_info) static
Definition at line 2271 of file cas.c.
References ARG_FILE_LINE, broker_name, t_appl_server_info::cas_clt_ip, cas_log_debug(), cas_log_reset(), t_appl_server_info::cas_log_reset, cas_log_write_and_end(), cas_log_write_client_ip(), t_req_info::client_version, t_appl_server_info::clt_version, t_appl_server_info::con_status, CON_STATUS_CLOSE, CON_STATUS_IN_TRAN, CON_STATUS_LOCK, CON_STATUS_LOCK_CAS, CON_STATUS_OUT_TRAN, CON_STATUS_UNLOCK, t_appl_server_info::database_passwd, t_appl_server_info::database_user, database_user, DEFAULT_CHECK_INTERVAL, t_req_info::driver_info, t_appl_server_info::driver_info, t_appl_server_info::driver_version, errors_in_transaction, get_graceful_down_timeout(), is_net_timed_out(), logddl_set_start_time(), net_read_header(), net_timeout_set(), NULL, t_appl_server_info::num_request, t_appl_server_info::proxy_conn_wait_timeout, t_appl_server_info::reset_flag, restart_is_needed(), t_shm_appl_server::session_timeout, SRV_CON_CLIENT_INFO_SIZE, tran_start_time, and TRUE.
Referenced by process_request().
static FN_RETURN process_request (SOCKET sock_fd, T_NET_BUF * net_buf, T_REQ_INFO * req_info) static
Definition at line 1700 of file cas.c.
References ARG_FILE_LINE, argc, argv, assert, broker_name, t_appl_server_info::cas_change_mode, CAS_CHANGE_MODE_AUTO, cas_db_name, cas_db_passwd, cas_db_user, CAS_ER_COMMUNICATION, CAS_ER_NO_MORE_MEMORY, CAS_ER_STMT_POOLING, CAS_ERROR_INDICATOR, CAS_FC_CHECK_CAS, CAS_FC_CURSOR_CLOSE, CAS_FC_CURSOR_CLOSE_FOR_PROTO_V2, CAS_FC_END_TRAN, CAS_FC_EXECUTE, CAS_FC_MAX, CAS_FC_PREPARE, CAS_FC_PREPARE_AND_EXECUTE, CAS_FC_PREPARE_AND_EXECUTE_FOR_PROTO_V2, CAS_FC_SCHEMA_INFO, cas_get_db_connect_status(), CAS_INFO_ADDITIONAL_FLAG, CAS_INFO_FLAG_MASK_AUTOCOMMIT, CAS_INFO_FLAG_MASK_FORCE_OUT_TRAN, CAS_INFO_RESERVED_1, CAS_INFO_RESERVED_2, CAS_INFO_RESERVED_DEFAULT, cas_info_size, CAS_INFO_STATUS, CAS_INFO_STATUS_ACTIVE, CAS_INFO_STATUS_INACTIVE, cas_log_debug(), cas_log_reset(), t_appl_server_info::cas_log_reset, cas_log_write_and_end(), CAS_PROTO_CURRENT_VER, cas_send_result_flag, cas_shard_flag, t_appl_server_info::cas_slow_log_reset, cas_slow_log_reset(), t_appl_server_info::cci_default_autocommit, clear_db_connection_info(), t_req_info::client_version, t_net_buf::client_version, t_appl_server_info::con_status, con_status_before_check_cas, CON_STATUS_CLOSE_AND_CONNECT, CON_STATUS_IN_TRAN, CON_STATUS_LOCK, CON_STATUS_LOCK_CAS, CON_STATUS_OUT_TRAN, CON_STATUS_UNLOCK, t_appl_server_info::cur_keep_con, t_appl_server_info::cur_sql_log2, db_set_interrupt(), DOES_CLIENT_MATCH_THE_PROTOCOL, DOES_CLIENT_UNDERSTAND_THE_PROTOCOL, t_req_info::driver_info, t_error_info::err_indicator, t_error_info::err_number, t_error_info::err_string, error_info_clear(), errors_in_transaction, t_appl_server_info::fixed_shard_user, FN_CLOSE_CONN, FN_GRACEFUL_DOWN, FN_KEEP_CONN, FN_KEEP_SESS, t_appl_server_info::fn_status, FN_STATUS_BUSY, FREE_MEM, FUNC_NEEDS_RESTORING_CON_STATUS, get_graceful_down_timeout(), htonl(), MSG_HEADER::info_ptr, init_msg_header(), is_first_request, is_net_timed_out(), KEEP_CON_AUTO, KEEP_CON_ON, t_appl_server_info::log_msg, logddl_get_jsp_mode(), logddl_write_end(), MALLOC, MAX_DIAG_DATA_VALUE, MSG_HEADER::msg_body_size_ptr, t_req_info::need_auto_commit, need_database_reconnect(), net_buf_clear(), NET_BUF_CURR_SIZE, NET_BUF_HEADER_MSG_SIZE, net_decode_str(), NET_DEFAULT_TIMEOUT, net_read_header(), net_read_header_keep_con_on(), net_read_int_keep_con_auto(), net_read_process(), net_read_stream(), net_timeout_set(), net_write_error(), net_write_from_file(), net_write_stream(), NULL, t_appl_server_info::num_holdable_results, t_appl_server_info::num_requests_received, t_appl_server_info::num_transactions_processed, OFF, ON, prev_cas_info, PROTOCOL_V2, PROTOCOL_V7, PROTOCOL_V8, req_info, t_appl_server_info::reset_flag, restart_is_needed(), server_fn_table, server_func_name, t_shm_appl_server::session_timeout, set_db_connection_info(), set_db_parameter(), set_hang_check_time(), shm_as_index, sock_fd, t_shm_appl_server::sql_log2, sql_log2_end(), sql_log2_init(), TRAN_AUTOROLLBACK, TRAN_NOT_AUTOCOMMIT, t_appl_server_info::transaction_start_time, TRUE, unset_hang_check_time(), t_appl_server_info::uts_status, UTS_STATUS_BUSY, UTS_STATUS_IDLE, ux_auto_commit(), ux_database_connect(), ux_is_database_connected(), ux_set_default_setting(), ux_set_utype_for_datetimeltz(), ux_set_utype_for_datetimetz(), ux_set_utype_for_enum(), ux_set_utype_for_json(), ux_set_utype_for_timestampltz(), and ux_set_utype_for_timestamptz().
Referenced by cas_main(), and shard_cas_main().
static void query_cancel (int signo) static
Definition at line 1674 of file cas.c.
References assert, db_set_interrupt(), MAX_DIAG_DATA_VALUE, t_appl_server_info::num_interrupts, query_cancel_flag, and query_cancel_time.
Referenced by cas_main(), and shard_cas_main().
int query_seq_num_current_value (void)
Definition at line 2941 of file cas.c.
References query_sequence_num.
Referenced by fn_prepare_internal(), and fn_schema_info().
int query_seq_num_next_value (void)
Definition at line 2935 of file cas.c.
References query_sequence_num.
Referenced by fn_get_query_info(), fn_prepare_internal(), and fn_schema_info().
int restart_is_needed (void)
Definition at line 2684 of file cas.c.
References t_shm_appl_server::appl_server_max_size, t_appl_server_info::cas_change_mode, CAS_CHANGE_MODE_KEEP, cas_req_count, envvar_bindir_file(), FALSE, NULL, t_appl_server_info::num_holdable_results, ONE_K, t_appl_server_info::pid, t_appl_server_info::psize, psize_at_start, TRUE, and ux_database_shutdown().
Referenced by cas_main(), fn_end_tran(), net_read_int_keep_con_auto(), net_read_process(), process_request(), and shard_cas_main().
static void set_cas_info_size (void) static
Definition at line 2668 of file cas.c.
References CAS_INFO_SIZE, cas_info_size, CAS_MAKE_VER, cas_shard_flag, t_appl_server_info::clt_version, and OFF.
Referenced by cas_main(), and shard_cas_main().
static void set_db_connection_info (void) static
Definition at line 2607 of file cas.c.
References ARG_FILE_LINE, cas_db_name, cas_db_passwd, cas_db_user, cas_log_debug(), t_appl_server_info::database_passwd, t_appl_server_info::database_user, t_shard_conn_info::db_password, t_shard_conn_info::db_user, t_appl_server_info::fixed_shard_user, t_shm_appl_server::shard_conn_info, shm_shard_id, SRV_CON_DBPASSWD_SIZE, and SRV_CON_DBUSER_SIZE.
Referenced by process_request(), and shard_cas_main().
static void set_db_parameter (void) static
Definition at line 2899 of file cas.c.
References cas_default_isolation_level, cas_default_lock_timeout, cas_log_write_and_end(), CAS_USE_DEFAULT_DB_PARAM, t_appl_server_info::isolation_level, t_appl_server_info::lock_timeout, NULL, ux_get_tran_setting(), ux_set_isolation_level(), and ux_set_lock_timeout().
Referenced by process_request().
void set_hang_check_time (void)
Definition at line 1488 of file cas.c.
References cas_shard_flag, t_appl_server_info::claimed_alive_time, t_shm_appl_server::monitor_hang_flag, NULL, and OFF.
Referenced by cas_init(), cas_log_begin_hang_check_time(), cas_main(), and process_request().
static int shard_cas_main (void) static
Definition at line 504 of file cas.c.
References t_net_buf::alloc_size, ARG_FILE_LINE, assert, t_appl_server_info::auto_commit_mode, broker_name, cas_db_name, cas_db_passwd, cas_db_user, cas_default_isolation_level, cas_default_lock_timeout, cas_error_log_close(), cas_error_log_open(), cas_final(), cas_get_client_version(), CAS_INFO_RESERVED_DEFAULT, CAS_INFO_STATUS, cas_log_close(), cas_log_debug(), cas_log_error_handler_begin(), cas_log_error_handler_clear(), cas_log_error_handler_end(), cas_log_open(), cas_log_write2(), cas_log_write_and_end(), CAS_PROTO_CURRENT_VER, cas_register_to_proxy(), cas_req_count, cas_set_db_connect_status(), cas_slow_log_close(), cas_slow_log_open(), t_appl_server_info::cci_default_autocommit, t_shm_appl_server::cci_default_autocommit, clear_db_connection_info(), t_req_info::client_version, CLOSE_SOCKET, t_appl_server_info::con_status, CON_STATUS_IN_TRAN, CON_STATUS_OUT_TRAN, t_appl_server_info::cur_keep_con, t_appl_server_info::cur_sql_log2, t_appl_server_info::cur_statement_pooling, t_net_buf::data, t_shard_conn_info::db_host, t_shard_conn_info::db_name, error(), errors_in_transaction, FALSE, FN_CLOSE_CONN, FN_GRACEFUL_DOWN, FN_KEEP_CONN, FN_KEEP_SESS, FREE, getsize(), hm_srv_handle_free_all(), hm_srv_handle_get_current_count(), INVALID_SOCKET, IS_INVALID_SOCKET, is_xa_prepared(), KEEP_CON_DEFAULT, KEEP_CON_ON, t_appl_server_info::last_access_time, MALLOC, MAX_HA_DBINFO_LENGTH, t_shm_appl_server::max_prepared_stmt_count, t_req_info::need_rollback, net_buf_init(), net_connect_proxy(), NET_DEFAULT_TIMEOUT, net_timeout_set(), NULL, OFF, ON, prev_cas_info, process_request(), proxy_sock_fd, t_appl_server_info::psize, psize_at_start, query_cancel(), query_start_time, query_timeout, t_appl_server_info::reset_flag, restart_is_needed(), t_appl_server_info::service_ready_flag, set_cas_info_size(), set_db_connection_info(), t_shm_appl_server::shard_conn_info, SHARD_NET_BUF_ALLOC_SIZE, shm_as_index, shm_proxy_id, shm_shard_id, SLEEP_SEC, t_shm_appl_server::sql_log2, sql_log2_end(), sql_log2_get_filename(), sql_log2_init(), t_shm_appl_server::statement_pooling, stripped_column_name, t_shm_appl_server::stripped_column_name, tran_start_time, tran_timeout, TRUE, t_appl_server_info::uts_status, UTS_STATUS_BUSY, UTS_STATUS_CON_WAIT, UTS_STATUS_IDLE, UTS_STATUS_RESTART, UTS_STATUS_STOP, ux_database_connect(), ux_database_shutdown(), ux_end_session(), ux_end_tran(), and ux_set_default_setting().
Referenced by main().
void unset_hang_check_time (void)
Definition at line 1505 of file cas.c.
References cas_shard_flag, t_appl_server_info::claimed_alive_time, t_shm_appl_server::monitor_hang_flag, NULL, and OFF.
Referenced by cas_log_end_hang_check_time(), cas_main(), and process_request().
Variable Documentation
T_APPL_SERVER_INFO* as_info
Definition at line 153 of file cas.c.
Referenced by cas_log_begin_hang_check_time(), cas_log_end(), cas_log_open(), cas_log_query_cancel(), cas_log_reset(), cas_log_write(), cas_log_write2(), cas_log_write2_nonl(), cas_log_write_and_end(), cas_log_write_nonl(), cas_log_write_query_string_internal(), cas_log_write_value_string(), cas_slow_log_end(), cas_slow_log_open(), cas_slow_log_reset(), cas_slow_log_write(), cas_slow_log_write2(), cas_slow_log_write_and_end(), cas_slow_log_write_query_string(), cas_slow_log_write_value_string(), err_msg_set(), fn_end_tran(), fn_execute_array(), fn_execute_internal(), fn_prepare_internal(), fn_set_db_parameter(), hm_new_srv_handle(), hm_qresult_end(), hm_srv_handle_free_all(), need_reconnect_on_rctime(), net_buf_error_msg_set(), net_connect_proxy(), proxy_handler_is_cas_in_tran(), sch_query_execute(), uc_as_info(), ux_auto_commit(), ux_check_connection(), ux_cursor_close(), ux_database_connect(), ux_database_shutdown(), ux_end_tran(), ux_execute(), ux_execute_all(), ux_execute_array(), ux_execute_batch(), ux_execute_call(), and ux_set_cas_change_mode().
bool autocommit_deferred = false
Definition at line 164 of file cas.c.
char broker_name[BROKER_NAME_LEN]
Definition at line 148 of file cas.c.
Referenced by admin_getid_cmd(), brief_monitor(), cas_init(), cas_main(), fn_end_tran(), main(), net_read_int_keep_con_auto(), net_read_process(), process_request(), and shard_cas_main().
char cas_client_type
Definition at line 169 of file cas.c.
Referenced by cas_main(), receiver_thr_f(), and sch_class_info().
char cas_db_name[MAX_HA_DBINFO_LENGTH] static
Definition at line 138 of file cas.c.
Referenced by process_request(), set_db_connection_info(), and shard_cas_main().
char cas_db_passwd[SRV_CON_DBPASSWD_SIZE] static
Definition at line 140 of file cas.c.
Referenced by clear_db_connection_info(), need_database_reconnect(), process_request(), set_db_connection_info(), and shard_cas_main().
char cas_db_user[SRV_CON_DBUSER_SIZE] static
Definition at line 139 of file cas.c.
Referenced by clear_db_connection_info(), need_database_reconnect(), process_request(), set_db_connection_info(), and shard_cas_main().
bool cas_default_ansi_quotes = true
Definition at line 178 of file cas.c.
Referenced by get_num_markers(), and ux_get_default_setting().
int cas_default_isolation_level = 0
Definition at line 176 of file cas.c.
Referenced by cas_main(), get_client_result_cache_lifetime(), set_db_parameter(), shard_cas_main(), ux_database_shutdown(), ux_get_default_setting(), and ux_set_default_setting().
int cas_default_lock_timeout = -1
Definition at line 177 of file cas.c.
Referenced by cas_main(), fn_set_db_parameter(), set_db_parameter(), shard_cas_main(), ux_database_shutdown(), ux_get_default_setting(), and ux_set_default_setting().
bool cas_default_no_backslash_escapes = true
Definition at line 180 of file cas.c.
Referenced by consume_tokens(), fn_get_db_parameter(), and ux_get_default_setting().
int cas_info_size = CAS_INFO_SIZE
Definition at line 183 of file cas.c.
Referenced by cas_main(), cas_send_connect_reply_to_driver(), net_read_header(), process_request(), and set_cas_info_size().
int cas_req_count = 0 static
Definition at line 336 of file cas.c.
Referenced by cas_free(), cas_main(), restart_is_needed(), and shard_cas_main().
int cas_send_result_flag = TRUE
Definition at line 182 of file cas.c.
Referenced by fn_end_tran(), and process_request().
int cas_shard_flag = OFF
Definition at line 143 of file cas.c.
Referenced by cas_init(), cas_init_shm(), cas_log_begin_hang_check_time(), cas_log_end_hang_check_time(), cas_main(), check_server_alive(), fetch_result(), fn_prepare_internal(), hm_new_srv_handle(), main(), make_error_log_filename(), make_sql_log_filename(), net_error_append_shard_info(), process_request(), read_buffer(), set_cas_info_size(), set_hang_check_time(), unset_hang_check_time(), and ux_fetch().
int con_status_before_check_cas
Definition at line 172 of file cas.c.
Referenced by cas_main(), and process_request().
const int DEFAULT_CHECK_INTERVAL = 1 static
Definition at line 85 of file cas.c.
Referenced by net_read_header_keep_con_on(), net_read_int_keep_con_auto(), and net_read_process().
T_ERROR_INFO err_info
Definition at line 186 of file cas.c.
Referenced by ci_stmt_get_next_error_impl(), err_msg_set(), error_info_clear(), error_info_set_with_msg(), fn_end_tran(), fn_execute_array(), fn_execute_internal(), fn_lob_new(), fn_lob_read(), fn_lob_write(), fn_prepare_internal(), is_error_info_set(), stmt_make_error_info(), stmt_remove_error_info(), and stmt_reset_session_and_parse().
int errors_in_transaction = 0
Definition at line 167 of file cas.c.
Referenced by cas_main(), fn_end_tran(), net_read_int_keep_con_auto(), net_read_process(), process_request(), shard_cas_main(), ux_auto_commit(), ux_col_seq_drop(), ux_col_seq_insert(), ux_col_seq_put(), ux_col_set_add(), ux_col_set_drop(), ux_cursor(), ux_cursor_update(), ux_end_tran(), ux_execute(), ux_execute_all(), ux_execute_array(), ux_execute_batch(), ux_fetch(), ux_get_attr_type_str(), ux_get_class_num_objs(), ux_get_last_insert_id(), ux_get_parameter_info(), ux_get_query_info(), ux_get_row_count(), ux_lob_new(), ux_lob_read(), ux_lob_write(), ux_oid_get(), ux_oid_put(), ux_prepare(), ux_schema_info(), and ux_set_isolation_level().
bool is_first_request
Definition at line 173 of file cas.c.
Referenced by cas_main(), and process_request().
SOCKET new_req_sock_fd = INVALID_SOCKET
Definition at line 174 of file cas.c.
Referenced by net_read_int_keep_con_auto(), net_timeout_set(), and read_buffer().
char prev_cas_info[CAS_INFO_SIZE]
Definition at line 184 of file cas.c.
Referenced by cas_main(), process_request(), and shard_cas_main().
const char* program_name
Definition at line 147 of file cas.c.
Referenced by createdb(), main(), ssession_find_or_create_session(), tzc_compute_timezone_checksum(), and ux_database_connect().
int psize_at_start
Definition at line 149 of file cas.c.
Referenced by cas_free(), cas_main(), restart_is_needed(), and shard_cas_main().
char query_cancel_flag
Definition at line 162 of file cas.c.
Referenced by cas_log_query_cancel(), cas_main(), and query_cancel().
INT64 query_cancel_time
Definition at line 161 of file cas.c.
Referenced by cas_log_query_cancel(), and query_cancel().
int query_sequence_num = 0 static
Definition at line 141 of file cas.c.
Referenced by query_seq_num_current_value(), and query_seq_num_next_value().
struct timeval query_start_time
Definition at line 158 of file cas.c.
Referenced by cas_main(), fn_end_tran(), fn_execute_array(), fn_execute_internal(), fn_prepare_internal(), shard_cas_main(), and ux_auto_commit().
int query_timeout = 0
Definition at line 160 of file cas.c.
Referenced by broker_config_dump(), broker_config_read_internal(), cas_main(), execute_query(), fn_end_tran(), fn_execute_array(), fn_execute_batch(), fn_execute_internal(), fn_prepare_internal(), fn_proxy_client_execute(), fn_proxy_client_execute_array(), fn_proxy_client_prepare_and_execute(), prepare_and_execute_query(), qmgr_get_temp_file_membuf_pages(), shard_cas_main(), sqmgr_execute_query(), sqmgr_prepare_and_execute_query(), tran_set_query_timeout(), and ux_auto_commit().
T_REQ_INFO req_info static
Definition at line 333 of file cas.c.
Referenced by fn_execute_internal(), fn_make_out_rs(), process_request(), and ux_fetch().
T_SERVER_FUNC server_fn_table[] static
Definition at line 236 of file cas.c.
Referenced by process_request().
const char* server_func_name[] static
Definition at line 285 of file cas.c.
Referenced by process_request().
T_SHM_APPL_SERVER* shm_appl
Definition at line 152 of file cas.c.
int shm_as_index
Definition at line 151 of file cas.c.
Referenced by cas_init(), cas_init_shm(), cas_main(), cas_send_connect_reply_to_driver(), fn_end_tran(), make_error_log_filename(), make_sql_log_filename(), net_read_int_keep_con_auto(), process_request(), and shard_cas_main().
int shm_proxy_id = -1
Definition at line 154 of file cas.c.
Referenced by cas_init(), cas_init_shm(), cas_main(), make_error_log_filename(), make_sql_log_filename(), and shard_cas_main().
int shm_shard_cas_id = -1
Definition at line 155 of file cas.c.
Referenced by cas_init(), cas_init_shm(), cas_main(), cas_register_to_proxy(), make_error_log_filename(), make_sql_log_filename(), and net_error_append_shard_info().
int shm_shard_id = SHARD_ID_UNSUPPORTED
Definition at line 144 of file cas.c.
Referenced by cas_init(), cas_init_shm(), cas_main(), cas_register_to_proxy(), make_error_log_filename(), make_sql_log_filename(), net_error_append_shard_info(), set_db_connection_info(), shard_cas_main(), ux_execute(), ux_execute_all(), ux_execute_array(), ux_execute_batch(), and ux_execute_call().
SOCKET srv_sock_fd static
Definition at line 335 of file cas.c.
Referenced by cas_main(), check_cas_log(), connect_srv(), dispatch_thr_f(), and net_read_int_keep_con_auto().
bool ssl_client
Definition at line 81 of file cas_ssl.c.
Referenced by cas_main().
char stripped_column_name
Definition at line 168 of file cas.c.
Referenced by broker_config_dump(), broker_config_read_internal(), cas_main(), conf_copy_broker(), prepare_column_list_info_set(), shard_cas_main(), and ux_make_out_rs().
struct timeval tran_start_time
Definition at line 157 of file cas.c.
Referenced by appl_info_display(), cas_main(), fn_end_tran(), net_read_int_keep_con_auto(), net_read_process(), shard_cas_main(), and ux_auto_commit().
int tran_timeout = 0
Definition at line 159 of file cas.c.
Referenced by cas_main(), fn_end_tran(), shard_cas_main(), and ux_auto_commit().