CUBRID Engine: src/broker/cas_dbms_util.h File Reference
cas_dbms_util.h File Reference
Classes
struct database_info
struct cache_time
Macros
#define free_and_init(ptr)
#define MAX_DIAG_DATA_VALUE 0xfffffffffffffLL
#define DBINFO_MAX_LENGTH 8192
Typedefs
typedef struct database_info DB_INFO
typedef struct cache_time CACHE_TIME
Enumerations
enum CUBRID_STMT_TYPE {
CUBRID_STMT_NONE = -1, CUBRID_STMT_ALTER_CLASS, CUBRID_STMT_ALTER_SERIAL, CUBRID_STMT_COMMIT_WORK,
CUBRID_STMT_REGISTER_DATABASE, CUBRID_STMT_CREATE_CLASS, CUBRID_STMT_CREATE_INDEX, CUBRID_STMT_CREATE_TRIGGER,
CUBRID_STMT_CREATE_SERIAL, CUBRID_STMT_DROP_DATABASE, CUBRID_STMT_DROP_CLASS, CUBRID_STMT_DROP_INDEX,
CUBRID_STMT_DROP_LABEL, CUBRID_STMT_DROP_TRIGGER, CUBRID_STMT_DROP_SERIAL, CUBRID_STMT_EVALUATE,
CUBRID_STMT_RENAME_CLASS, CUBRID_STMT_ROLLBACK_WORK, CUBRID_STMT_GRANT, CUBRID_STMT_REVOKE,
CUBRID_STMT_UPDATE_STATS, CUBRID_STMT_INSERT, CUBRID_STMT_SELECT, CUBRID_STMT_UPDATE,
CUBRID_STMT_DELETE, CUBRID_STMT_CALL, CUBRID_STMT_GET_ISO_LVL, CUBRID_STMT_GET_TIMEOUT,
CUBRID_STMT_GET_OPT_LVL, CUBRID_STMT_SET_OPT_LVL, CUBRID_STMT_SCOPE, CUBRID_STMT_GET_TRIGGER,
CUBRID_STMT_SET_TRIGGER, CUBRID_STMT_SAVEPOINT, CUBRID_STMT_PREPARE, CUBRID_STMT_ATTACH,
CUBRID_STMT_USE, CUBRID_STMT_REMOVE_TRIGGER, CUBRID_STMT_RENAME_TRIGGER, CUBRID_STMT_ON_LDB,
CUBRID_STMT_GET_LDB, CUBRID_STMT_SET_LDB, CUBRID_STMT_GET_STATS, CUBRID_STMT_CREATE_USER,
CUBRID_STMT_DROP_USER, CUBRID_STMT_ALTER_USER, CUBRID_STMT_SET_SYS_PARAMS, CUBRID_STMT_ALTER_INDEX,
CUBRID_STMT_CREATE_STORED_PROCEDURE, CUBRID_STMT_DROP_STORED_PROCEDURE, CUBRID_STMT_SELECT_UPDATE, CUBRID_STMT_ALTER_STORED_PROCEDURE,
CUBRID_STMT_ALTER_STORED_PROCEDURE_OWNER = CUBRID_STMT_ALTER_STORED_PROCEDURE, CUBRID_MAX_STMT_TYPE, CUBRID_STMT_NONE = -1, CUBRID_STMT_ALTER_CLASS,
CUBRID_STMT_ALTER_SERIAL, CUBRID_STMT_COMMIT_WORK, CUBRID_STMT_REGISTER_DATABASE, CUBRID_STMT_CREATE_CLASS,
CUBRID_STMT_CREATE_INDEX, CUBRID_STMT_CREATE_TRIGGER, CUBRID_STMT_CREATE_SERIAL, CUBRID_STMT_DROP_DATABASE,
CUBRID_STMT_DROP_CLASS, CUBRID_STMT_DROP_INDEX, CUBRID_STMT_DROP_LABEL, CUBRID_STMT_DROP_TRIGGER,
CUBRID_STMT_DROP_SERIAL, CUBRID_STMT_EVALUATE, CUBRID_STMT_RENAME_CLASS, CUBRID_STMT_ROLLBACK_WORK,
CUBRID_STMT_GRANT, CUBRID_STMT_REVOKE, CUBRID_STMT_UPDATE_STATS, CUBRID_STMT_INSERT,
CUBRID_STMT_SELECT, CUBRID_STMT_UPDATE, CUBRID_STMT_DELETE, CUBRID_STMT_CALL,
CUBRID_STMT_GET_ISO_LVL, CUBRID_STMT_GET_TIMEOUT, CUBRID_STMT_GET_OPT_LVL, CUBRID_STMT_SET_OPT_LVL,
CUBRID_STMT_SCOPE, CUBRID_STMT_GET_TRIGGER, CUBRID_STMT_SET_TRIGGER, CUBRID_STMT_SAVEPOINT,
CUBRID_STMT_PREPARE, CUBRID_STMT_ATTACH, CUBRID_STMT_USE, CUBRID_STMT_REMOVE_TRIGGER,
CUBRID_STMT_RENAME_TRIGGER, CUBRID_STMT_ON_LDB, CUBRID_STMT_GET_LDB, CUBRID_STMT_SET_LDB,
CUBRID_STMT_GET_STATS, CUBRID_STMT_CREATE_USER, CUBRID_STMT_DROP_USER, CUBRID_STMT_ALTER_USER,
CUBRID_STMT_SET_SYS_PARAMS, CUBRID_STMT_ALTER_INDEX, CUBRID_STMT_CREATE_STORED_PROCEDURE, CUBRID_STMT_DROP_STORED_PROCEDURE,
CUBRID_STMT_PREPARE_STATEMENT, CUBRID_STMT_EXECUTE_PREPARE, CUBRID_STMT_DEALLOCATE_PREPARE, CUBRID_STMT_TRUNCATE,
CUBRID_STMT_DO, CUBRID_STMT_SELECT_UPDATE, CUBRID_STMT_SET_SESSION_VARIABLES, CUBRID_STMT_DROP_SESSION_VARIABLES,
CUBRID_STMT_MERGE, CUBRID_STMT_SET_NAMES, CUBRID_STMT_ALTER_STORED_PROCEDURE, CUBRID_STMT_ALTER_STORED_PROCEDURE_OWNER = CUBRID_STMT_ALTER_STORED_PROCEDURE,
CUBRID_STMT_KILL, CUBRID_STMT_VACUUM, CUBRID_STMT_SET_TIMEZONE, CUBRID_MAX_STMT_TYPE
}
Functions
int cfg_get_dbinfo (char *alias, char *dbinfo)
void cfg_free_dbinfo_all (DB_INFO *databases)
int cfg_read_dbinfo (DB_INFO **db_info_p)
DB_INFO * cfg_find_db_list (DB_INFO *db_info_list_p, const char *name)
int char_is_delim (int c, int delim)
char * char_get_next (char *str_p)
UINT64 ntohi64 (UINT64 from)
int char_islower (int c)
int char_isupper (int c)
int char_isalpha (int c)
int char_tolower (int c)
Macro Definition Documentation
#define DBINFO_MAX_LENGTH 8192
Definition at line 38 of file cas_dbms_util.h.
Referenced by cfg_get_dbinfo(), and cfg_read_dbinfo().
#define free_and_init (ptr)
Value:
do { \
          if ((ptr)) { \
            free ((ptr)); \
            (ptr) = NULL; \
          } \
        } while (0)
Definition at line 29 of file cas_dbms_util.h.
#define MAX_DIAG_DATA_VALUE 0xfffffffffffffLL
Definition at line 36 of file cas_dbms_util.h.
Typedef Documentation
typedef struct cache_time CACHE_TIME
Definition at line 110 of file cas_dbms_util.h.
typedef struct database_info DB_INFO
Definition at line 100 of file cas_dbms_util.h.
Enumeration Type Documentation
enum CUBRID_STMT_TYPE
Enumerator
CUBRID_STMT_NONE
CUBRID_STMT_ALTER_CLASS
CUBRID_STMT_ALTER_SERIAL
CUBRID_STMT_COMMIT_WORK
CUBRID_STMT_REGISTER_DATABASE
CUBRID_STMT_CREATE_CLASS
CUBRID_STMT_CREATE_INDEX
CUBRID_STMT_CREATE_TRIGGER
CUBRID_STMT_CREATE_SERIAL
CUBRID_STMT_DROP_DATABASE
CUBRID_STMT_DROP_CLASS
CUBRID_STMT_DROP_INDEX
CUBRID_STMT_DROP_LABEL
CUBRID_STMT_DROP_TRIGGER
CUBRID_STMT_DROP_SERIAL
CUBRID_STMT_EVALUATE
CUBRID_STMT_RENAME_CLASS
CUBRID_STMT_ROLLBACK_WORK
CUBRID_STMT_GRANT
CUBRID_STMT_REVOKE
CUBRID_STMT_UPDATE_STATS
CUBRID_STMT_INSERT
CUBRID_STMT_SELECT
CUBRID_STMT_UPDATE
CUBRID_STMT_DELETE
CUBRID_STMT_CALL
CUBRID_STMT_GET_ISO_LVL
CUBRID_STMT_GET_TIMEOUT
CUBRID_STMT_GET_OPT_LVL
CUBRID_STMT_SET_OPT_LVL
CUBRID_STMT_SCOPE
CUBRID_STMT_GET_TRIGGER
CUBRID_STMT_SET_TRIGGER
CUBRID_STMT_SAVEPOINT
CUBRID_STMT_PREPARE
CUBRID_STMT_ATTACH
CUBRID_STMT_USE
CUBRID_STMT_REMOVE_TRIGGER
CUBRID_STMT_RENAME_TRIGGER
CUBRID_STMT_ON_LDB
CUBRID_STMT_GET_LDB
CUBRID_STMT_SET_LDB
CUBRID_STMT_GET_STATS
CUBRID_STMT_CREATE_USER
CUBRID_STMT_DROP_USER
CUBRID_STMT_ALTER_USER
CUBRID_STMT_SET_SYS_PARAMS
CUBRID_STMT_ALTER_INDEX
CUBRID_STMT_CREATE_STORED_PROCEDURE
CUBRID_STMT_DROP_STORED_PROCEDURE
CUBRID_STMT_SELECT_UPDATE
CUBRID_STMT_ALTER_STORED_PROCEDURE
CUBRID_STMT_ALTER_STORED_PROCEDURE_OWNER
CUBRID_MAX_STMT_TYPE
CUBRID_STMT_NONE
CUBRID_STMT_ALTER_CLASS
CUBRID_STMT_ALTER_SERIAL
CUBRID_STMT_COMMIT_WORK
CUBRID_STMT_REGISTER_DATABASE
CUBRID_STMT_CREATE_CLASS
CUBRID_STMT_CREATE_INDEX
CUBRID_STMT_CREATE_TRIGGER
CUBRID_STMT_CREATE_SERIAL
CUBRID_STMT_DROP_DATABASE
CUBRID_STMT_DROP_CLASS
CUBRID_STMT_DROP_INDEX
CUBRID_STMT_DROP_LABEL
CUBRID_STMT_DROP_TRIGGER
CUBRID_STMT_DROP_SERIAL
CUBRID_STMT_EVALUATE
CUBRID_STMT_RENAME_CLASS
CUBRID_STMT_ROLLBACK_WORK
CUBRID_STMT_GRANT
CUBRID_STMT_REVOKE
CUBRID_STMT_UPDATE_STATS
CUBRID_STMT_INSERT
CUBRID_STMT_SELECT
CUBRID_STMT_UPDATE
CUBRID_STMT_DELETE
CUBRID_STMT_CALL
CUBRID_STMT_GET_ISO_LVL
CUBRID_STMT_GET_TIMEOUT
CUBRID_STMT_GET_OPT_LVL
CUBRID_STMT_SET_OPT_LVL
CUBRID_STMT_SCOPE
CUBRID_STMT_GET_TRIGGER
CUBRID_STMT_SET_TRIGGER
CUBRID_STMT_SAVEPOINT
CUBRID_STMT_PREPARE
CUBRID_STMT_ATTACH
CUBRID_STMT_USE
CUBRID_STMT_REMOVE_TRIGGER
CUBRID_STMT_RENAME_TRIGGER
CUBRID_STMT_ON_LDB
CUBRID_STMT_GET_LDB
CUBRID_STMT_SET_LDB
CUBRID_STMT_GET_STATS
CUBRID_STMT_CREATE_USER
CUBRID_STMT_DROP_USER
CUBRID_STMT_ALTER_USER
CUBRID_STMT_SET_SYS_PARAMS
CUBRID_STMT_ALTER_INDEX
CUBRID_STMT_CREATE_STORED_PROCEDURE
CUBRID_STMT_DROP_STORED_PROCEDURE
CUBRID_STMT_PREPARE_STATEMENT
CUBRID_STMT_EXECUTE_PREPARE
CUBRID_STMT_DEALLOCATE_PREPARE
CUBRID_STMT_TRUNCATE
CUBRID_STMT_DO
CUBRID_STMT_SELECT_UPDATE
CUBRID_STMT_SET_SESSION_VARIABLES
CUBRID_STMT_DROP_SESSION_VARIABLES
CUBRID_STMT_MERGE
CUBRID_STMT_SET_NAMES
CUBRID_STMT_ALTER_STORED_PROCEDURE
CUBRID_STMT_ALTER_STORED_PROCEDURE_OWNER
CUBRID_STMT_KILL
CUBRID_STMT_VACUUM
CUBRID_STMT_SET_TIMEZONE
CUBRID_MAX_STMT_TYPE
Definition at line 40 of file cas_dbms_util.h.
Function Documentation
DB_INFO* cfg_find_db_list (DB_INFO * db_info_list_p, const char * name)
Definition at line 1008 of file databases_file.c.
References database_info::alias, database_info::name, database_info::next, and NULL.
Referenced by alterdbhost(), boot_restart_server(), cfg_find_db(), get_db_path(), print_backup_info(), xboot_copy(), xboot_delete(), xboot_emergency_patch(), xboot_initialize_server(), and xboot_soft_rename().
void cfg_free_dbinfo_all (DB_INFO * databases)
Definition at line 51 of file cas_dbms_util.c.
References database_info::alias, database_info::dbinfo, free_and_init, database_info::next, and NULL.
Referenced by cfg_read_dbinfo().
int cfg_get_dbinfo (char * alias, char * dbinfo)
Definition at line 72 of file cas_dbms_util.c.
References BROKER_PATH_MAX, CAS_ER_ARGS, CAS_ER_OPEN_FILE, CAS_ERROR_INDICATOR, t_shm_appl_server::db_connection_file, DBINFO_MAX_LENGTH, envvar_confdir_file(), ERROR_INFO_SET, FID_CAS_FOR_MYSQL_DBINFO, FID_CAS_FOR_ORACLE_DBINFO, get_cubrid_file(), IS_ABS_PATH, NULL, and shm_appl.
int cfg_read_dbinfo (DB_INFO ** db_info_p)
Definition at line 133 of file cas_dbms_util.c.
References database_info::alias, BROKER_PATH_MAX, CAS_ER_ARGS, CAS_ER_NO_MORE_MEMORY, CAS_ER_OPEN_FILE, CAS_ERROR_INDICATOR, cfg_free_dbinfo_all(), cfg_pop_token(), char_get_next(), t_shm_appl_server::db_connection_file, database_info::dbinfo, DBINFO_MAX_LENGTH, envvar_confdir_file(), ERROR_INFO_SET, FID_CAS_FOR_MYSQL_DBINFO, FID_CAS_FOR_ORACLE_DBINFO, get_cubrid_file(), IS_ABS_PATH, database_info::next, NULL, and shm_appl.
char* char_get_next (char * str_p)
Definition at line 268 of file cas_dbms_util.c.
References char_is_delim(), and p.
Referenced by cfg_read_dbinfo().
int char_is_delim (int c, int delim)
Definition at line 255 of file cas_dbms_util.c.
Referenced by cfg_pop_token(), and char_get_next().
int char_isalpha (int c)
Definition at line 61 of file chartype.c.
References char_islower(), and char_isupper().
Referenced by calc_unix_timestamp(), char_isalnum(), db_date_parse_datetime_parts(), db_date_parse_time(), lang_check_identifier(), parse_date_separated(), parse_explicit_mtime_compact(), parse_explicit_mtime_separated(), parse_mtime_separated(), parse_timedate_separated(), parse_timestamp_compact(), and rel_compare().
int char_islower (int c)
Definition at line 37 of file chartype.c.
Referenced by char_isalpha(), char_islower_iso8859(), and char_toupper().
int char_isupper (int c)
Definition at line 49 of file chartype.c.
Referenced by char_isalpha(), char_isupper_iso8859(), char_tolower(), and locale_alloc_collation_id().
int char_tolower (int c)
Definition at line 146 of file chartype.c.
References char_isupper().
Referenced by fileio_request_user_response(), get_next_format(), get_number_token(), ini_str_lower(), intl_identifier_lower(), intl_identifier_mht_1strlowerhash(), intl_mbs_ncpy(), intl_tolower_euc(), is_valid_ip_slice(), make_number(), make_number_to_char(), mht_1strlowerhash(), net_client_request_with_callback(), pp_generic_case_hash(), and to_number_next_state().
UINT64 ntohi64 (UINT64 from)
Definition at line 328 of file cas_dbms_util.c.