CUBRID Engine: src/broker/cas_function.c File Reference
cas_function.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/time.h>
#include <assert.h>
#include "error_manager.h"
#include "cas_common.h"
#include "cas.h"
#include "cas_function.h"
#include "cas_network.h"
#include "cas_net_buf.h"
#include "cas_log.h"
#include "cas_handle.h"
#include "cas_util.h"
#include "cas_execute.h"
#include "perf_monitor.h"
#include "broker_filename.h"
#include "cas_sql_log2.h"
#include "dbtype.h"
#include "object_primitive.h"
#include "ddl_log.h"
Functions
static FN_RETURN fn_prepare_internal (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info, int *ret_srv_h_id)
static FN_RETURN fn_execute_internal (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info, int *prepared_srv_h_id)
static const char * get_schema_type_str (int schema_type)
static const char * get_tran_type_str (int tran_type)
static void bind_value_print (char type, void *net_value, bool slow_log)
static char * get_error_log_eids (int err)
static void bind_value_log (struct timeval *log_time, int start, int argc, void **argv, int param_size, char *param_mode, unsigned int query_seq_num, bool slow_log)
void set_query_timeout (T_SRV_HANDLE *srv_handle, int query_timeout)
int jsp_send_destroy_request_all ()
void tran_set_query_timeout (int)
bool tran_is_in_libcas (void)
static void update_error_query_count (T_APPL_SERVER_INFO *as_info_p, const T_ERROR_INFO *err_info_p)
static char logddl_is_exist_ddl_stmt (T_SRV_HANDLE *srv_handle)
FN_RETURN fn_end_tran (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_end_session (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_get_row_count (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_get_last_insert_id (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_prepare (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_execute (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_prepare_and_execute (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_get_db_parameter (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_set_db_parameter (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_set_cas_change_mode (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_close_req_handle (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_cursor (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_fetch (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_schema_info (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_oid_get (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_oid_put (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_get_db_version (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_get_class_num_objs (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_oid (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_collection (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_next_result (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_execute_batch (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_execute_array (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_cursor_update (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_cursor_close (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_get_attr_type_str (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_get_query_info (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_savepoint (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_parameter_info (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_con_close (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_check_cas (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_make_out_rs (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_get_generated_keys (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_lob_new (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_lob_write (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_lob_read (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_deprecated (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
FN_RETURN fn_not_supported (SOCKET sock_fd, int argc, void **argv, T_NET_BUF *net_buf, T_REQ_INFO *req_info)
Variables
static const char * tran_type_str [] = { "COMMIT", "ROLLBACK" }
static const char * schema_type_str []
static const char * type_str_tbl []
Function Documentation
static void bind_value_log (struct timeval * log_time, int start, int argc, void ** argv, int param_size, char * param_mode, unsigned int query_seq_num, bool slow_log) static
Definition at line 2156 of file cas_function.c.
References bind_value_print(), cas_log_write2_nonl(), cas_log_write_nonl(), cas_slow_log_write(), cas_slow_log_write2(), net_arg_get_char, NULL, and type_str_tbl.
Referenced by fn_execute_array(), and fn_execute_internal().
static void bind_value_print (char type, void * net_value, bool slow_log) static
Definition at line 2218 of file cas_function.c.
References cas_log_write2_nonl(), cas_log_write_value_string(), CAS_SCHEMA_DEFAULT_CHARSET, cas_slow_log_write2(), cas_slow_log_write_value_string(), db_get_elo(), db_value_clear(), intl_char_count(), db_elo::locator, db_elo::meta_data, net_arg_get_bigint(), net_arg_get_cci_object(), net_arg_get_datetime(), net_arg_get_datetimetz(), net_arg_get_double(), net_arg_get_float(), net_arg_get_int(), net_arg_get_lob_value(), net_arg_get_short(), net_arg_get_size(), net_arg_get_str(), db_elo::size, db_elo::type, and type_str_tbl.
Referenced by bind_value_log().
FN_RETURN fn_check_cas (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 2045 of file cas_function.c.
References CAS_ERROR_INDICATOR, cas_log_write(), ERROR_INFO_SET, FN_KEEP_CONN, FN_KEEP_SESS, net_arg_get_str(), NET_BUF_ERR_SET, and ux_check_connection().
FN_RETURN fn_close_req_handle (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1018 of file cas_function.c.
References CAS_ER_ARGS, CAS_ERROR_INDICATOR, cas_log_write(), ERROR_INFO_SET, FALSE, FN_KEEP_CONN, hm_find_srv_handle(), hm_srv_handle_free(), t_req_info::need_auto_commit, net_arg_get_char, net_arg_get_int(), net_buf_cp_int(), NET_BUF_ERR_SET, NULL, SRV_HANDLE_QUERY_SEQ_NUM, TRAN_AUTOCOMMIT, and TRUE.
FN_RETURN fn_collection (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1383 of file cas_function.c.
References CAS_ER_ARGS, CAS_ER_COLLECTION_DOMAIN, CAS_ER_INTERNAL, CAS_ER_NOT_COLLECTION, CAS_ERROR_INDICATOR, db_attribute_domain(), db_col_free(), db_domain_set(), db_error_code(), db_get(), db_get_attribute(), db_get_collection, db_put(), DB_TYPE_NULL, db_value_clear(), db_value_type(), DBMS_ERROR_INDICATOR, ERROR_INFO_SET, FN_KEEP_CONN, FREE_MEM, get_set_domain(), make_bind_value(), net_arg_get_char, net_arg_get_dbobject(), net_arg_get_int(), net_arg_get_str(), NET_BUF_ERR_SET, NULL, TP_DOMAIN_TYPE, ux_check_object(), ux_col_get(), ux_col_seq_drop(), ux_col_seq_insert(), ux_col_seq_put(), ux_col_set_add(), ux_col_set_drop(), ux_col_size(), and ux_db_type_to_cas_type().
FN_RETURN fn_con_close (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 2031 of file cas_function.c.
References CAS_CLIENT_SERVER_SIDE_JDBC, cas_log_write(), t_req_info::driver_info, DRIVER_INFO_CLIENT_TYPE, FN_CLOSE_CONN, logddl_free(), net_buf_cp_int(), and NULL.
FN_RETURN fn_cursor (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1060 of file cas_function.c.
References CAS_ER_ARGS, CAS_ERROR_INDICATOR, ERROR_INFO_SET, FN_KEEP_CONN, net_arg_get_char, net_arg_get_int(), NET_BUF_ERR_SET, and ux_cursor().
FN_RETURN fn_cursor_close (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1830 of file cas_function.c.
References cas_log_write(), FN_KEEP_CONN, hm_find_srv_handle(), net_arg_get_int(), NULL, t_srv_handle::num_q_result, SRV_HANDLE_QUERY_SEQ_NUM, and ux_cursor_close().
FN_RETURN fn_cursor_update (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1803 of file cas_function.c.
References CAS_ER_ARGS, CAS_ERROR_INDICATOR, cas_log_write(), ERROR_INFO_SET, FN_KEEP_CONN, hm_find_srv_handle(), net_arg_get_int(), NET_BUF_ERR_SET, SRV_HANDLE_QUERY_SEQ_NUM, and ux_cursor_update().
FN_RETURN fn_deprecated (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 2626 of file cas_function.c.
References CAS_ER_NOT_IMPLEMENTED, CAS_ERROR_INDICATOR, ERROR_INFO_SET, FN_KEEP_CONN, net_buf_cp_int(), NET_BUF_ERR_SET, and NULL.
FN_RETURN fn_end_session (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 278 of file cas_function.c.
References FN_KEEP_CONN, net_buf_cp_int(), NO_ERROR, and NULL.
FN_RETURN fn_end_tran (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 155 of file cas_function.c.
References ARG_FILE_LINE, as_info, assert, broker_name, CAS_ER_ARGS, CAS_ER_TRAN_TYPE, CAS_ERROR_INDICATOR, cas_log_debug(), cas_log_end(), cas_log_reset(), t_appl_server_info::cas_log_reset, cas_log_write(), CAS_MAKE_VER, cas_send_result_flag, t_appl_server_info::cas_slow_log_reset, cas_slow_log_reset(), t_req_info::client_version, t_appl_server_info::con_status, CON_STATUS_IN_TRAN, CON_STATUS_OUT_TRAN, t_appl_server_info::cur_sql_log2, err_info, t_error_info::err_number, ERROR_INFO_SET, errors_in_transaction, FALSE, FN_CLOSE_CONN, FN_KEEP_CONN, FN_KEEP_SESS, get_error_log_eids(), get_tran_type_str(), logddl_write_tran_str(), t_shm_appl_server::long_transaction_time, MAX_DIAG_DATA_VALUE, t_req_info::need_rollback, net_arg_get_char, net_buf_cp_int(), NET_BUF_ERR_SET, NULL, t_appl_server_info::num_long_transactions, query_start_time, query_timeout, t_appl_server_info::reset_flag, restart_is_needed(), shm_appl, shm_as_index, t_shm_appl_server::sql_log2, sql_log2_end(), sql_log2_init(), SQL_LOG_MODE_ERROR, SQL_LOG_MODE_NONE, SQL_LOG_MODE_TIMEOUT, tran_start_time, tran_timeout, t_appl_server_info::transaction_start_time, TRUE, ut_check_timeout(), ut_timeval_diff(), ux_end_tran(), and ux_is_database_connected().
FN_RETURN fn_execute (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 415 of file cas_function.c.
References fn_execute_internal(), and NULL.
FN_RETURN fn_execute_array (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1653 of file cas_function.c.
References as_info, t_srv_handle::auto_commit_mode, bind_value_log(), CAS_ER_ARGS, cas_log_write(), cas_log_write_nonl(), cas_log_write_query_string(), cas_slow_log_end(), cas_slow_log_write(), cas_slow_log_write_query_string(), t_req_info::client_version, t_appl_server_info::cur_slow_log_mode, t_appl_server_info::cur_sql_log_mode, db_get_execution_plan(), db_set_execution_plan(), DOES_CLIENT_UNDERSTAND_THE_PROTOCOL, err_info, t_error_info::err_number, FN_KEEP_CONN, get_error_log_eids(), get_tuple_count(), hm_find_srv_handle(), t_srv_handle::is_pooled, logddl_set_sql_text(), t_shm_appl_server::long_query_time, MAX_DIAG_DATA_VALUE, t_req_info::need_auto_commit, net_arg_get_char, net_arg_get_int(), net_buf_cp_int(), NULL, t_appl_server_info::num_long_queries, PROTOCOL_V4, query_start_time, query_timeout, set_query_timeout(), shm_appl, SLOW_LOG_MODE_ON, SQL_LOG_MODE_NONE, t_srv_handle::sql_stmt, SRV_HANDLE_QUERY_SEQ_NUM, strlen, TRAN_AUTOCOMMIT, TRUE, update_error_query_count(), t_srv_handle::use_query_cache, ut_check_timeout(), ut_timeval_diff(), and ux_execute_array().
FN_RETURN fn_execute_batch (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1617 of file cas_function.c.
References cas_log_write(), t_req_info::client_version, DOES_CLIENT_UNDERSTAND_THE_PROTOCOL, FN_KEEP_CONN, logddl_set_commit_mode(), net_arg_get_char, net_arg_get_int(), NULL, PROTOCOL_V4, query_timeout, set_query_timeout(), and ux_execute_batch().
static FN_RETURN fn_execute_internal (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info, int * prepared_srv_h_id) static
Definition at line 423 of file cas_function.c.
References ARG_FILE_LINE, as_info, t_srv_handle::auto_commit_mode, bind_value_log(), CAS_CLIENT_SERVER_SIDE_JDBC, CAS_ER_ARGS, CAS_ER_SRV_HANDLE, CAS_ERROR_INDICATOR, cas_log_debug(), cas_log_write(), cas_log_write_nonl(), cas_log_write_query_string(), CAS_PROTO_MAKE_VER, cas_slow_log_end(), cas_slow_log_write(), cas_slow_log_write_query_string(), t_req_info::client_version, CUBRID_STMT_SELECT, t_appl_server_info::cur_slow_log_mode, t_appl_server_info::cur_sql_log_mode, t_appl_server_info::cur_statement_pooling, db_get_execution_plan(), db_set_execution_plan(), DOES_CLIENT_MATCH_THE_PROTOCOL, DOES_CLIENT_UNDERSTAND_THE_PROTOCOL, DRIVER_INFO_CLIENT_TYPE, err_info, t_error_info::err_number, ERROR_INFO_SET, FALSE, FN_KEEP_CONN, t_srv_handle::forward_only_cursor, get_error_log_eids(), get_tuple_count(), hm_find_srv_handle(), t_srv_handle::is_pooled, jsp_send_destroy_request_all(), t_appl_server_info::log_msg, logddl_is_exist_ddl_stmt(), logddl_set_commit_mode(), logddl_set_err_code(), logddl_set_sql_text(), logddl_set_stmt_type(), t_shm_appl_server::long_query_time, MAX_DIAG_DATA_VALUE, t_shm_appl_server::max_string_length, net_arg_get_cache_time(), net_arg_get_char, net_arg_get_int(), net_arg_get_str(), NET_BUF_ERR_SET, NULL, t_appl_server_info::num_long_queries, t_srv_handle::prepare_flag, PROTOCOL_V1, PROTOCOL_V2, t_srv_handle::q_result, query_start_time, query_timeout, req_info, t_srv_handle::schema_type, set_query_timeout(), shm_appl, SHM_LOG_MSG_SIZE, SLOW_LOG_MODE_ON, SQL_LOG_MODE_NONE, t_srv_handle::sql_stmt, SRV_HANDLE_QUERY_SEQ_NUM, t_query_result::stmt_type, strlen, TRUE, update_error_query_count(), ut_check_timeout(), ut_timeval_diff(), ux_call_info_cp_param_mode(), ux_execute(), ux_execute_all(), ux_execute_call(), and ux_fetch().
Referenced by fn_execute(), and fn_prepare_and_execute().
FN_RETURN fn_fetch (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1084 of file cas_function.c.
References CAS_ER_ARGS, CAS_ER_SRV_HANDLE, CAS_ERROR_INDICATOR, cas_log_write(), ERROR_INFO_SET, FN_KEEP_CONN, hm_find_srv_handle(), net_arg_get_char, net_arg_get_int(), NET_BUF_ERR_SET, NULL, SRV_HANDLE_QUERY_SEQ_NUM, and ux_fetch().
FN_RETURN fn_get_attr_type_str (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1852 of file cas_function.c.
References CAS_ER_ARGS, CAS_ERROR_INDICATOR, ERROR_INFO_SET, FN_KEEP_CONN, net_arg_get_str(), NET_BUF_ERR_SET, and ux_get_attr_type_str().
FN_RETURN fn_get_class_num_objs (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1237 of file cas_function.c.
References CAS_ER_ARGS, CAS_ERROR_INDICATOR, cas_log_write(), ERROR_INFO_SET, FN_KEEP_CONN, net_arg_get_char, net_arg_get_str(), NET_BUF_ERR_SET, and ux_get_class_num_objs().
FN_RETURN fn_get_db_parameter (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 804 of file cas_function.c.
References cas_default_no_backslash_escapes, CAS_ER_ARGS, CAS_ER_PARAM_NAME, CAS_ERROR_INDICATOR, cas_log_write(), t_req_info::client_version, DB_MAX_STRING_LENGTH, DOES_CLIENT_UNDERSTAND_THE_PROTOCOL, ERROR_INFO_SET, FN_KEEP_CONN, t_shm_appl_server::max_string_length, net_arg_get_int(), net_buf_cp_int(), NET_BUF_ERR_SET, NULL, PROTOCOL_V2, shm_appl, and ux_get_tran_setting().
FN_RETURN fn_get_db_version (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1209 of file cas_function.c.
References CAS_ER_ARGS, CAS_ERROR_INDICATOR, cas_log_write(), ERROR_INFO_SET, FN_KEEP_CONN, t_req_info::need_auto_commit, net_arg_get_char, NET_BUF_ERR_SET, TRAN_AUTOCOMMIT, TRUE, and ux_get_db_version().
FN_RETURN fn_get_generated_keys (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 2102 of file cas_function.c.
References CAS_ER_ARGS, CAS_ER_SRV_HANDLE, CAS_ERROR_INDICATOR, cas_log_write(), ERROR_INFO_SET, FN_KEEP_CONN, hm_find_srv_handle(), net_arg_get_int(), NET_BUF_ERR_SET, NULL, SRV_HANDLE_QUERY_SEQ_NUM, and ux_get_generated_keys().
FN_RETURN fn_get_last_insert_id (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 294 of file cas_function.c.
References FN_KEEP_CONN, and ux_get_last_insert_id().
FN_RETURN fn_get_query_info (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1874 of file cas_function.c.
References CAS_ER_ARGS, CAS_ERROR_INDICATOR, cas_log_query_info_init(), db_close_session(), db_compile_statement(), db_error_code(), db_execute_statement(), db_open_buffer(), db_query_end(), DBMS_ERROR_INDICATOR, ER_UCI_TOO_FEW_HOST_VARS, err, ERROR_INFO_SET, FN_KEEP_CONN, hm_new_srv_handle(), hm_srv_handle_free(), net_arg_get_char, net_arg_get_int(), net_arg_get_str(), net_buf_cp_byte(), NET_BUF_ERR_SET, NULL, t_srv_handle::query_info_flag, query_seq_num_next_value(), reset_optimization_level_as_saved(), TRUE, and ux_get_query_info().
FN_RETURN fn_get_row_count (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 287 of file cas_function.c.
References FN_KEEP_CONN, and ux_get_row_count().
FN_RETURN fn_lob_new (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 2499 of file cas_function.c.
References CAS_ER_ARGS, CAS_ERROR_INDICATOR, cas_log_write(), err_info, t_error_info::err_number, ERROR_INFO_SET, FN_KEEP_CONN, get_error_log_eids(), net_arg_get_int(), net_buf_cp_int(), NET_BUF_ERR_SET, NULL, ut_timeval_diff(), and ux_lob_new().
FN_RETURN fn_lob_read (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 2585 of file cas_function.c.
References CAS_ER_ARGS, CAS_ERROR_INDICATOR, cas_log_write(), db_get_elo(), db_value_clear(), err_info, t_error_info::err_number, ERROR_INFO_SET, FN_KEEP_CONN, get_error_log_eids(), net_arg_get_bigint(), net_arg_get_int(), net_arg_get_lob_value(), net_buf_cp_int(), NET_BUF_ERR_SET, NULL, ut_timeval_diff(), and ux_lob_read().
FN_RETURN fn_lob_write (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 2543 of file cas_function.c.
References CAS_ER_ARGS, CAS_ERROR_INDICATOR, cas_log_write(), db_get_elo(), db_value_clear(), err_info, t_error_info::err_number, ERROR_INFO_SET, FN_KEEP_CONN, get_error_log_eids(), net_arg_get_bigint(), net_arg_get_lob_value(), net_arg_get_str(), net_buf_cp_int(), NET_BUF_ERR_SET, NULL, ut_timeval_diff(), and ux_lob_write().
FN_RETURN fn_make_out_rs (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 2076 of file cas_function.c.
References argc, argv, CAS_ER_ARGS, CAS_ERROR_INDICATOR, ERROR_INFO_SET, FN_KEEP_CONN, fn_make_out_rs(), fn_not_supported(), net_arg_get_int(), NET_BUF_ERR_SET, req_info, sock_fd, and ux_make_out_rs().
Referenced by fn_make_out_rs().
FN_RETURN fn_next_result (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1581 of file cas_function.c.
References CAS_ER_ARGS, CAS_ER_SRV_HANDLE, CAS_ERROR_INDICATOR, cas_log_write(), ERROR_INFO_SET, FN_KEEP_CONN, hm_find_srv_handle(), net_arg_get_char, net_arg_get_int(), NET_BUF_ERR_SET, NULL, SRV_HANDLE_QUERY_SEQ_NUM, t_srv_handle::use_query_cache, and ux_next_result().
FN_RETURN fn_not_supported (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 2639 of file cas_function.c.
References CAS_ER_NOT_IMPLEMENTED, CAS_ERROR_INDICATOR, ERROR_INFO_SET, FN_KEEP_CONN, and NET_BUF_ERR_SET.
Referenced by fn_make_out_rs().
FN_RETURN fn_oid (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1261 of file cas_function.c.
References CAS_ER_ARGS, CAS_ER_INTERNAL, CAS_ER_OBJECT, CAS_ERROR_INDICATOR, cas_log_write(), db_drop(), db_error_code(), db_get_class_name(), db_is_instance(), db_lock_read(), db_lock_write(), DBMS_ERROR_INDICATOR, er_clear(), ERROR_INFO_SET, FN_KEEP_CONN, net_arg_get_char, net_arg_get_dbobject(), net_buf_cp_int(), net_buf_cp_str(), NET_BUF_ERR_SET, NULL, strlen, and ux_check_object().
FN_RETURN fn_oid_get (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1168 of file cas_function.c.
References CAS_ER_ARGS, CAS_ERROR_INDICATOR, cas_log_write(), ERROR_INFO_SET, FN_KEEP_CONN, net_arg_get_cci_object(), NET_BUF_ERR_SET, and ux_oid_get().
FN_RETURN fn_oid_put (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1190 of file cas_function.c.
References CAS_ER_ARGS, CAS_ERROR_INDICATOR, cas_log_write(), ERROR_INFO_SET, FN_KEEP_CONN, NET_BUF_ERR_SET, and ux_oid_put().
FN_RETURN fn_parameter_info (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 2010 of file cas_function.c.
References CAS_ER_ARGS, CAS_ERROR_INDICATOR, ERROR_INFO_SET, FN_KEEP_CONN, net_arg_get_int(), NET_BUF_ERR_SET, and ux_get_parameter_info().
FN_RETURN fn_prepare (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 302 of file cas_function.c.
References fn_prepare_internal(), and NULL.
FN_RETURN fn_prepare_and_execute (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 776 of file cas_function.c.
References cas_log_write(), fn_execute_internal(), FN_KEEP_CONN, fn_prepare_internal(), hm_find_srv_handle(), hm_srv_handle_free(), IS_ERROR_INFO_SET, net_arg_get_int(), and SRV_HANDLE_QUERY_SEQ_NUM.
static FN_RETURN fn_prepare_internal (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info, int * ret_srv_h_id) static
Definition at line 309 of file cas_function.c.
References argc, as_info, CAS_ER_ARGS, CAS_ERROR_INDICATOR, cas_log_write(), cas_log_write_nonl(), cas_log_write_query_string(), cas_shard_flag, t_appl_server_info::cur_sql_log2, err_info, t_error_info::err_number, ERROR_INFO_SET, FALSE, FN_KEEP_CONN, get_error_log_eids(), hm_find_srv_handle(), hm_srv_handle_free(), i, t_appl_server_info::log_msg, logddl_set_commit_mode(), logddl_set_err_code(), logddl_set_sql_text(), net_arg_get_char, net_arg_get_int(), net_arg_get_str(), NET_BUF_ERR_SET, NULL, OFF, query_seq_num_current_value(), query_seq_num_next_value(), query_start_time, query_timeout, SHM_LOG_MSG_SIZE, SQL_LOG2_COMPILE_BEGIN, strlen, update_error_query_count(), t_srv_handle::use_plan_cache, ut_trim(), and ux_prepare().
Referenced by fn_prepare(), and fn_prepare_and_execute().
FN_RETURN fn_savepoint (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1960 of file cas_function.c.
References CAS_ER_ARGS, CAS_ER_INTERNAL, CAS_ERROR_INDICATOR, cas_log_write(), db_abort_to_savepoint(), db_savepoint_transaction(), DBMS_ERROR_INDICATOR, ERROR_INFO_SET, FN_KEEP_CONN, net_arg_get_char, net_arg_get_str(), net_buf_cp_int(), NET_BUF_ERR_SET, and NULL.
FN_RETURN fn_schema_info (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 1128 of file cas_function.c.
References CAS_ER_ARGS, CAS_ERROR_INDICATOR, cas_log_write(), t_req_info::client_version, DOES_CLIENT_UNDERSTAND_THE_PROTOCOL, ERROR_INFO_SET, FN_KEEP_CONN, get_schema_type_str(), net_arg_get_char, net_arg_get_int(), net_arg_get_str(), NET_BUF_ERR_SET, PROTOCOL_V5, query_seq_num_current_value(), query_seq_num_next_value(), and ux_schema_info().
FN_RETURN fn_set_cas_change_mode (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 989 of file cas_function.c.
References CAS_CHANGE_MODE_AUTO, CAS_CHANGE_MODE_KEEP, CAS_ER_ARGS, CAS_ERROR_INDICATOR, cas_log_write(), ERROR_INFO_SET, FN_KEEP_CONN, mode, net_arg_get_int(), NET_BUF_ERR_SET, and ux_set_cas_change_mode().
FN_RETURN fn_set_db_parameter (SOCKET sock_fd, int argc, void ** argv, T_NET_BUF * net_buf, T_REQ_INFO * req_info)
Definition at line 897 of file cas_function.c.
References as_info, t_appl_server_info::auto_commit_mode, cas_default_lock_timeout, CAS_ER_ARGS, CAS_ER_PARAM_NAME, CAS_ERROR_INDICATOR, cas_log_write(), ERROR_INFO_SET, FALSE, FN_KEEP_CONN, net_arg_get_int(), net_buf_cp_int(), NET_BUF_ERR_SET, NULL, TRUE, ux_set_isolation_level(), and ux_set_lock_timeout().
static char * get_error_log_eids (int err) static
Definition at line 2460 of file cas_function.c.
References cas_error_log_get_eid(), cas_log_error_handler_asprint(), and NULL.
Referenced by fn_end_tran(), fn_execute_array(), fn_execute_internal(), fn_lob_new(), fn_lob_read(), fn_lob_write(), and fn_prepare_internal().
static const char * get_schema_type_str (int schema_type) static
Definition at line 2133 of file cas_function.c.
References schema_type_str.
Referenced by fn_schema_info().
static const char * get_tran_type_str (int tran_type) static
Definition at line 2144 of file cas_function.c.
References tran_type_str.
Referenced by fn_end_tran().
int jsp_send_destroy_request_all ()
Definition at line 1963 of file jsp_cl.c.
Referenced by csql_execute_statements(), and fn_execute_internal().
static char logddl_is_exist_ddl_stmt (T_SRV_HANDLE * srv_handle) static
Definition at line 2711 of file cas_function.c.
References i, logddl_is_ddl_type(), t_srv_handle::num_q_result, t_srv_handle::q_result, and t_query_result::stmt_type.
Referenced by fn_execute_internal().
void set_query_timeout (T_SRV_HANDLE * srv_handle, int query_timeout)
Definition at line 2648 of file cas_function.c.
References cas_log_write(), t_shm_appl_server::query_timeout, shm_appl, SRV_HANDLE_QUERY_SEQ_NUM, tran_is_in_libcas(), and tran_set_query_timeout().
Referenced by fn_execute_array(), fn_execute_batch(), and fn_execute_internal().
bool tran_is_in_libcas (void)
Definition at line 1335 of file transaction_cl.c.
Referenced by set_query_timeout().
void tran_set_query_timeout (int)
Definition at line 1279 of file transaction_cl.c.
Referenced by chksum_start(), and set_query_timeout().
static void update_error_query_count (T_APPL_SERVER_INFO * as_info_p, const T_ERROR_INFO * err_info_p) static
Definition at line 2689 of file cas_function.c.
References assert, DBMS_ERROR_INDICATOR, ER_BTREE_UNIQUE_FAILED, ER_QPROC_INVALID_XASLNODE, ER_UNIQUE_VIOLATION_WITHKEY, t_error_info::err_indicator, t_error_info::err_number, MAX_DIAG_DATA_VALUE, NULL, t_appl_server_info::num_error_queries, and t_appl_server_info::num_unique_error_queries.
Referenced by fn_execute_array(), fn_execute_internal(), and fn_prepare_internal().
Variable Documentation
const char* schema_type_str[] static
Initial value:
= {
  "CLASS",
  "VCLASS",
  "QUERY_SPEC",
  "ATTRIBUTE",
  "CLASS_ATTRIBUTE",
  "METHOD",
  "CLASS_METHOD",
  "METHOD_FILE",
  "SUPERCLASS",
  "SUBCLASS",
  "CONSTRAINT",
  "TRIGGER",
  "CLASS_PRIVILEGE",
  "ATTR_PRIVILEGE",
  "DIRECT_SUPER_CLASS",
  "PRIMARY_KEY",
  "IMPORTED_KEYS",
  "EXPORTED_KEYS",
  "CROSS_REFERENCE"
}
Definition at line 94 of file cas_function.c.
Referenced by get_schema_type_str().
const char* tran_type_str[] = { "COMMIT", "ROLLBACK" } static
Definition at line 90 of file cas_function.c.
Referenced by get_tran_type_str().
const char* type_str_tbl[] static
Definition at line 116 of file cas_function.c.
Referenced by bind_value_log(), and bind_value_print().