CUBRID Engine: src/broker/cas_error_log.h File Reference
cas_error_log.h File Reference
Functions
void cas_error_log_open (char *br_name)
void cas_error_log_close (bool flag)
void cas_error_log_write (int dbms_errno, const char *dbms_errmsg)
char * cas_error_log_get_eid (char *buf, size_t bufsz)
Function Documentation
void cas_error_log_close (bool flag)
Definition at line 113 of file cas_error_log.c.
References error_log_fp, NULL, and saved_error_log_fpos.
Referenced by cas_error_log_open(), cas_error_log_write(), cas_free(), cas_main(), and shard_cas_main().
char* cas_error_log_get_eid (char * buf, size_t bufsz)
Definition at line 193 of file cas_error_log.c.
References eid, and NULL.
Referenced by get_error_log_eids().
void cas_error_log_open (char * br_name)
Definition at line 86 of file cas_error_log.c.
References BROKER_PATH_MAX, cas_error_log_close(), error_log_filepath, error_log_fp, make_error_log_filename(), NULL, and saved_error_log_fpos.
Referenced by cas_error_log_write(), cas_main(), and shard_cas_main().
void cas_error_log_write (int dbms_errno, const char * dbms_errmsg)
Definition at line 167 of file cas_error_log.c.
References cas_error_log_backup(), cas_error_log_close(), cas_error_log_open(), cas_log_write_internal(), eid, error_log_fp, NULL, saved_error_log_fpos, shm_appl, and t_shm_appl_server::sql_log_max_size.