CUBRID Engine: src/broker/cas_util.h File Reference
cas_util.h File Reference
Functions
char * ut_uchar2ipstr (unsigned char *ip_addr)
char * ut_trim (char *)
void ut_tolower (char *str)
void ut_timeval_diff (struct timeval *start, struct timeval *end, int *res_sec, int *res_msec)
int ut_check_timeout (struct timeval *start_time, struct timeval *end_time, int timeout_msec, int *res_sec, int *res_msec)
Function Documentation
int ut_check_timeout (struct timeval * start_time, struct timeval * end_time, int timeout_msec, int * res_sec, int * res_msec)
Definition at line 119 of file cas_util.c.
References assert, NULL, and ut_timeval_diff().
Referenced by fn_end_tran(), fn_execute_array(), fn_execute_internal(), and ux_auto_commit().
void ut_timeval_diff (struct timeval * start, struct timeval * end, int * res_sec, int * res_msec)
Definition at line 101 of file cas_util.c.
References assert, and NULL.
Referenced by fn_end_tran(), fn_execute_array(), fn_execute_internal(), fn_lob_new(), fn_lob_read(), fn_lob_write(), and ut_check_timeout().
void ut_tolower (char * str)
Definition at line 73 of file broker_log_util.c.
References is_bind_with_size(), NULL, p, and strlen.
Referenced by sch_attr_info(), sch_class_info(), sch_direct_super_class(), sch_primary_key(), sch_queryspec(), and str_like().
char* ut_trim (char *)
Definition at line 43 of file broker_log_util.c.
References NULL, p, and strlen.
Referenced by dbval_to_net_buf(), fn_prepare_internal(), log_top(), net_buf_column_info_set(), netval_to_dbval(), sql_change_comp_form(), and ux_prepare().
char* ut_uchar2ipstr (unsigned char * ip_addr)
Definition at line 43 of file cas_util.c.
References assert, and NULL.
Referenced by cas_log_debug(), client_monitor(), and proxy_access_log().