CUBRID Engine: src/broker/cas_str_like.h File Reference
cas_str_like.h File Reference
Functions
int str_like (char *src, char *pattern, char esc_char)
Function Documentation
int str_like (char * src, char * pattern, char esc_char)
Definition at line 72 of file cas_str_like.c.
References ALLOC_COPY, B_FALSE, FREE_MEM, NULL, str_eval_like(), and ut_tolower().
Referenced by sch_attr_priv(), sch_class_priv(), and sch_trigger().