CUBRID Engine: src/broker/cas_error.c File Reference
cas_error.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/time.h>
#include "cas.h"
#include "cas_common.h"
#include "cas_execute.h"
#include "cas_network.h"
#include "cas_util.h"
#include "cas_schema_info.h"
#include "cas_log.h"
#include "cas_str_like.h"
#include "broker_filename.h"
#include "cas_sql_log2.h"
Functions
void err_msg_set (T_NET_BUF *net_buf, const char *file, int line)
int error_info_set (int err_number, int err_indicator, const char *file, int line)
int error_info_set_force (int err_number, int err_indicator, const char *file, int line)
int error_info_set_with_msg (int err_number, int err_indicator, const char *err_msg, bool force, const char *file, int line)
int is_error_info_set (void)
void error_info_clear (void)
void set_server_aborted (bool is_aborted)
bool is_server_aborted (void)
Variables
static bool server_aborted = false
Function Documentation
void err_msg_set (T_NET_BUF * net_buf, const char * file, int line)
Definition at line 58 of file cas_error.c.
References ARG_FILE_LINE, as_info, CAS_ERROR_INDICATOR, cas_log_debug(), cas_log_write_and_end(), cas_set_db_connect_status(), DB_CONNECTION_STATUS_NOT_CONNECTED, DBMS_ERROR_INDICATOR, ER_BO_CONNECT_FAILED, ER_NET_SERVER_CRASHED, ER_OBJ_NO_CONNECT, ER_TM_SERVER_DOWN_UNILATERALLY_ABORTED, t_error_info::err_file, t_error_info::err_indicator, err_info, t_error_info::err_line, t_error_info::err_number, t_error_info::err_string, FALSE, net_buf_error_msg_set(), NULL, t_appl_server_info::reset_flag, set_server_aborted(), and TRUE.
void error_info_clear (void)
Definition at line 217 of file cas_error.c.
References CAS_NO_ERROR, t_error_info::err_file, ERR_FILE_LENGTH, t_error_info::err_indicator, err_info, t_error_info::err_line, ERR_MSG_LENGTH, t_error_info::err_number, t_error_info::err_string, and ERROR_INDICATOR_UNSET.
Referenced by cas_main(), and process_request().
int error_info_set (int err_number, int err_indicator, const char * file, int line)
Definition at line 146 of file cas_error.c.
References error_info_set_with_msg(), and NULL.
int error_info_set_force (int err_number, int err_indicator, const char * file, int line)
Definition at line 152 of file cas_error.c.
References error_info_set_with_msg(), and NULL.
int error_info_set_with_msg (int err_number, int err_indicator, const char * err_msg, bool force, const char * file, int line)
Definition at line 158 of file cas_error.c.
References ARG_FILE_LINE, assert, CAS_ERROR_INDICATOR, cas_log_debug(), db_error_string(), DBMS_ERROR_INDICATOR, er_errid(), t_error_info::err_file, ERR_FILE_LENGTH, t_error_info::err_indicator, err_info, t_error_info::err_line, ERR_MSG_LENGTH, t_error_info::err_number, t_error_info::err_string, ERROR_INDICATOR_UNSET, NO_ERROR, and NULL.
Referenced by error_info_set(), and error_info_set_force().
int is_error_info_set (void)
Definition at line 211 of file cas_error.c.
References t_error_info::err_indicator, err_info, and ERROR_INDICATOR_UNSET.
bool is_server_aborted (void)
Definition at line 234 of file cas_error.c.
References server_aborted.
Referenced by cas_main().
void set_server_aborted (bool is_aborted)
Definition at line 228 of file cas_error.c.
References server_aborted.
Referenced by err_msg_set().
Variable Documentation
bool server_aborted = false static
Definition at line 55 of file cas_error.c.
Referenced by is_server_aborted(), and set_server_aborted().