CUBRID Engine: src/broker/cas_str_like.c File Reference
cas_str_like.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "cas_common.h"
#include "cas_util.h"
#include "cas_str_like.h"
Macros
#define STK_SIZE 100
#define B_ERROR -1
#define B_TRUE 1
#define B_FALSE 0
Functions
static int str_eval_like (const unsigned char *tar, const unsigned char *expr, unsigned char escape)
static int is_korean (unsigned char ch)
int str_like (char *src, char *pattern, char esc_char)
Macro Definition Documentation
#define B_ERROR -1
Definition at line 61 of file cas_str_like.c.
Referenced by str_eval_like().
#define B_FALSE 0
Definition at line 63 of file cas_str_like.c.
Referenced by str_eval_like(), and str_like().
#define B_TRUE 1
Definition at line 62 of file cas_str_like.c.
Referenced by str_eval_like().
#define STK_SIZE 100
Definition at line 60 of file cas_str_like.c.
Referenced by str_eval_like().
Function Documentation
static int is_korean (unsigned char ch) static
Definition at line 480 of file cas_str_like.c.
References p.
Referenced by str_eval_like().
static int str_eval_like (const unsigned char * tar, const unsigned char * expr, unsigned char escape) static
Definition at line 102 of file cas_str_like.c.
References B_ERROR, B_FALSE, B_TRUE, is_korean(), and STK_SIZE.
Referenced by str_like().
int str_like (char * src, char * pattern, char esc_char)
Definition at line 72 of file cas_str_like.c.
References ALLOC_COPY, B_FALSE, FREE_MEM, NULL, str_eval_like(), and ut_tolower().
Referenced by sch_attr_priv(), sch_class_priv(), and sch_trigger().