CUBRID Engine: src/broker/cas_schema_info.h File Reference
cas_schema_info.h File Reference
#include "dbtype_def.h"
#include "cas_net_buf.h"
Macros
#define SCH_STR_LEN DB_MAX_IDENTIFIER_LENGTH
#define SCH_CLASS_REMARKS_STR_LEN DB_MAX_CLASS_COMMENT_LENGTH
#define SCH_REMARKS_STR_LEN DB_MAX_COMMENT_LENGTH
Typedefs
typedef void(* T_SCHEMA_META_F) (T_NET_BUF *)
Functions
void schema_table_meta (T_NET_BUF *net_buf)
void schema_query_spec_meta (T_NET_BUF *net_buf)
void schema_attr_meta (T_NET_BUF *net_buf)
void schema_method_meta (T_NET_BUF *net_buf)
void schema_methodfile_meta (T_NET_BUF *net_buf)
void schema_superclasss_meta (T_NET_BUF *net_buf)
void schema_constraint_meta (T_NET_BUF *net_buf)
void schema_trigger_meta (T_NET_BUF *net_buf)
void schema_classpriv_meta (T_NET_BUF *net_buf)
void schema_attrpriv_meta (T_NET_BUF *net_buf)
void schema_directsuper_meta (T_NET_BUF *net_buf)
void schema_primarykey_meta (T_NET_BUF *net_buf)
void schema_fk_info_meta (T_NET_BUF *net_buf)
Macro Definition Documentation
#define SCH_CLASS_REMARKS_STR_LEN DB_MAX_CLASS_COMMENT_LENGTH
Definition at line 40 of file cas_schema_info.h.
Referenced by schema_table_meta().
#define SCH_REMARKS_STR_LEN DB_MAX_COMMENT_LENGTH
Definition at line 41 of file cas_schema_info.h.
Referenced by schema_attr_meta(), and schema_trigger_meta().
#define SCH_STR_LEN DB_MAX_IDENTIFIER_LENGTH
Definition at line 39 of file cas_schema_info.h.
Referenced by schema_attr_meta(), schema_attrpriv_meta(), schema_classpriv_meta(), schema_constraint_meta(), schema_directsuper_meta(), schema_fk_info_meta(), schema_method_meta(), schema_methodfile_meta(), schema_primarykey_meta(), schema_query_spec_meta(), schema_superclasss_meta(), schema_table_meta(), and schema_trigger_meta().
Typedef Documentation
typedef void(* T_SCHEMA_META_F) (T_NET_BUF *)
Definition at line 44 of file cas_schema_info.h.
Function Documentation
void schema_attr_meta (T_NET_BUF * net_buf)
Definition at line 56 of file cas_schema_info.c.
References CAS_SCHEMA_DEFAULT_CHARSET, net_buf_column_info_set(), net_buf_cp_int(), NULL, SCH_REMARKS_STR_LEN, and SCH_STR_LEN.
Referenced by sch_attr_info().
void schema_attrpriv_meta (T_NET_BUF * net_buf)
Definition at line 140 of file cas_schema_info.c.
References CAS_SCHEMA_DEFAULT_CHARSET, net_buf_column_info_set(), net_buf_cp_int(), NULL, and SCH_STR_LEN.
Referenced by sch_attr_priv().
void schema_classpriv_meta (T_NET_BUF * net_buf)
Definition at line 131 of file cas_schema_info.c.
References CAS_SCHEMA_DEFAULT_CHARSET, net_buf_column_info_set(), net_buf_cp_int(), NULL, and SCH_STR_LEN.
Referenced by sch_class_priv().
void schema_constraint_meta (T_NET_BUF * net_buf)
Definition at line 100 of file cas_schema_info.c.
References CAS_SCHEMA_DEFAULT_CHARSET, net_buf_column_info_set(), net_buf_cp_int(), NULL, and SCH_STR_LEN.
Referenced by sch_constraint().
void schema_directsuper_meta (T_NET_BUF * net_buf)
Definition at line 149 of file cas_schema_info.c.
References CAS_SCHEMA_DEFAULT_CHARSET, net_buf_column_info_set(), net_buf_cp_int(), NULL, and SCH_STR_LEN.
Referenced by sch_direct_super_class().
void schema_fk_info_meta (T_NET_BUF * net_buf)
Definition at line 167 of file cas_schema_info.c.
References CAS_SCHEMA_DEFAULT_CHARSET, net_buf_column_info_set(), net_buf_cp_int(), NULL, and SCH_STR_LEN.
Referenced by sch_exported_keys_or_cross_reference(), and sch_imported_keys().
void schema_method_meta (T_NET_BUF * net_buf)
Definition at line 76 of file cas_schema_info.c.
References CAS_SCHEMA_DEFAULT_CHARSET, net_buf_column_info_set(), net_buf_cp_int(), NULL, and SCH_STR_LEN.
Referenced by sch_method_info().
void schema_methodfile_meta (T_NET_BUF * net_buf)
Definition at line 85 of file cas_schema_info.c.
References CAS_SCHEMA_DEFAULT_CHARSET, net_buf_column_info_set(), net_buf_cp_int(), NULL, and SCH_STR_LEN.
Referenced by sch_methfile_info().
void schema_primarykey_meta (T_NET_BUF * net_buf)
Definition at line 157 of file cas_schema_info.c.
References CAS_SCHEMA_DEFAULT_CHARSET, net_buf_column_info_set(), net_buf_cp_int(), NULL, and SCH_STR_LEN.
Referenced by sch_primary_key().
void schema_query_spec_meta (T_NET_BUF * net_buf)
Definition at line 49 of file cas_schema_info.c.
References CAS_SCHEMA_DEFAULT_CHARSET, net_buf_column_info_set(), net_buf_cp_int(), NULL, and SCH_STR_LEN.
Referenced by sch_queryspec().
void schema_superclasss_meta (T_NET_BUF * net_buf)
Definition at line 92 of file cas_schema_info.c.
References CAS_SCHEMA_DEFAULT_CHARSET, net_buf_column_info_set(), net_buf_cp_int(), NULL, and SCH_STR_LEN.
Referenced by sch_superclass().
void schema_table_meta (T_NET_BUF * net_buf)
Definition at line 39 of file cas_schema_info.c.
References CAS_SCHEMA_DEFAULT_CHARSET, net_buf_column_info_set(), net_buf_cp_int(), NULL, SCH_CLASS_REMARKS_STR_LEN, and SCH_STR_LEN.
Referenced by sch_class_info().
void schema_trigger_meta (T_NET_BUF * net_buf)
Definition at line 114 of file cas_schema_info.c.
References CAS_SCHEMA_DEFAULT_CHARSET, net_buf_column_info_set(), net_buf_cp_int(), NULL, SCH_REMARKS_STR_LEN, and SCH_STR_LEN.
Referenced by sch_trigger().