CUBRID Engine: src/api/cci_stub.c File Reference
cci_stub.c File Reference
#include "config.h"
#include <string.h>
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include "api_util.h"
#include "api_common.h"
#include "cas_cci.h"
Classes
struct connection_impl_s
struct parameter_meta_impl_s
struct batch_result_impl_s
struct batch_sql_item_s
struct batch_ary_item_s
struct statement_impl_s
struct resultset_meta_impl_s
struct resultset_impl_s
struct api_val_s
struct api_val_cci_bind_s
struct cci_object_s
struct cci_object_pool_s
struct cci_collection_s
struct add_batch_params_arg
struct ores_nvt_s
struct ores_apply_updatef_s
Macros
#define DBDEF_HEADER_
#define API_VAL_CCI_BIND_FLAG_GET 0x01
#define API_VAL_CCI_BIND_FLAG_SET 0x02
#define API_EXEC_PRE()
#define API_EXEC_POST(has_result)
Typedefs
typedef enum impl_handle_type IMPL_HANDLE_TYPE
typedef struct connection_impl_s CONNECTION_IMPL
typedef struct parameter_meta_impl_s PARAMETER_META_IMPL
typedef struct batch_sql_item_s BATCH_SQL_ITEM
typedef struct batch_ary_item_s BATCH_ARY_ITEM
typedef struct batch_result_impl_s BATCH_RESULT_IMPL
typedef struct statement_impl_s STATEMENT_IMPL
typedef struct resultset_meta_impl_s RESULTSET_META_IMPL
typedef struct resultset_impl_s RESULTSET_IMPL
typedef struct api_val_s API_VAL
typedef struct api_val_cci_bind_s API_VAL_CCI_BIND
typedef struct cci_object_s CCI_OBJECT
typedef struct cci_object_pool_s CCI_OBJECT_POOL
typedef struct cci_collection_s CCI_COLLECTION
Functions
static int bind_api_structure (BH_INTERFACE *bh, COMMON_API_STRUCTURE *s, COMMON_API_STRUCTURE *parent, BIND_HANDLE *handle)
static int err_from_cci (int err)
static void connection_impl_dtor (BH_BIND *bind)
static void init_connection_impl (CONNECTION_IMPL *impl, int rid, CI_CONNECTION conn, BH_INTERFACE *bh, int conn_handle, CCI_OBJECT_POOL *pool)
static int complete_connection (CONNECTION_IMPL *impl)
static void api_val_dtor (VALUE_AREA *va, API_VALUE *val)
static CI_TYPE cci_u_type_to_type (T_CCI_U_TYPE utype)
static T_CCI_U_TYPE type_to_cci_u_type (CI_TYPE type)
static int get_value_from_api_val (const API_VAL *pv, CI_TYPE type, void *addr, size_t len, size_t *outlen, bool *isnull)
static int set_value_to_api_val (API_VAL *pv, CI_TYPE type, void *addr, size_t len)
static int get_type_value_size (CI_TYPE type, int *len)
static void api_val_cci_bind_init (API_VAL_CCI_BIND *bind, CI_CONNECTION conn, int flag)
static int api_val_cci_bind_bind (CI_TYPE type, void *ptr, int len, API_VAL_CCI_BIND *bind)
static void api_val_cci_bind_clear (API_VAL_CCI_BIND *bind)
static int api_val_bind_param (CI_CONNECTION conn, int req_handle, API_VAL *pv, int index)
static int get_value_from_req_handle (CI_CONNECTION conn, int req_handle, int index, CI_TYPE type, void *addr, size_t len, size_t *outlen, bool *is_null)
static int get_value_from_tset (T_CCI_U_TYPE utype, T_CCI_SET tset, CI_TYPE type, CI_CONNECTION conn, int i, API_VAL **pv)
static int api_val_cursor_update (CI_CONNECTION conn, int req_handle, int offset, int index, API_VAL *av, T_CCI_ERROR *err_buf)
static int lazy_bind_qres_rmeta (RESULTSET_IMPL *pres)
static int api_qres_get_resultset_metadata (API_RESULTSET *res, API_RESULTSET_META **rimpl)
static int api_qres_fetch (API_RESULTSET *res, int offset, CI_FETCH_POSITION pos)
static int api_qres_tell (API_RESULTSET *res, int *offset)
static int api_qres_clear_updates (API_RESULTSET *res)
static int api_qres_delete_row (API_RESULTSET *res)
static int api_qres_get_value (API_RESULTSET *res, int index, CI_TYPE type, void *addr, size_t len, size_t *outlen, bool *is_null)
static int api_qres_get_value_by_name (API_RESULTSET *res, const char *name, CI_TYPE type, void *addr, size_t len, size_t *outlen, bool *isnull)
static int api_qres_update_value (API_RESULTSET *res, int index, CI_TYPE type, void *addr, size_t len)
static int api_qres_apply_update (API_RESULTSET *res)
static void api_qres_destroy (API_RESULTSET *res)
static int create_resultset_impl (CI_CONNECTION conn, BH_INTERFACE *bh, int req_handle, T_CCI_ERROR *err_buf, COMMON_API_STRUCTURE *parent, bool updatable, void *arg, void(*on_close)(RESULTSET_IMPL *, void *), API_RESULTSET_IFS *resifs, API_RESULTSET_META_IFS *rmifs, RESULTSET_IMPL **rpres)
static void resultset_impl_dtor (BH_BIND *bind)
static int api_qrmeta_get_count (API_RESULTSET_META *rm, int *count)
static int api_qrmeta_get_info (API_RESULTSET_META *rm, int index, CI_RMETA_INFO_TYPE type, void *arg, size_t size)
static int lazy_bind_pstmt_pmeta (STATEMENT_IMPL *pstmt)
static void statement_impl_dtor (BH_BIND *bind)
static void init_statement_impl (STATEMENT_IMPL *pstmt, CONNECTION_IMPL *pconn)
static int statement_execute (STATEMENT_IMPL *pstmt, T_CCI_ERROR *err_buf)
static int statement_get_reshandle_or_affectedrows (BH_INTERFACE *bh, STATEMENT_IMPL *pstmt)
static int complete_statement (STATEMENT_IMPL *pstmt)
static void on_close_statement_res (RESULTSET_IMPL *impl, void *arg)
static int add_batch_params_restore_mapf (void *arg, int index, VALUE_AREA *va, API_VALUE *val)
static int add_batch_params_mapf (void *arg, int index, VALUE_AREA *va, API_VALUE *val)
static int stmt_execute_batch_sql (STATEMENT_IMPL *pstmt)
static int stmt_execute_batch_array (STATEMENT_IMPL *pstmt)
static int stmt_complete_batch (STATEMENT_IMPL *pstmt)
static int api_ormeta_get_count (API_RESULTSET_META *rm, int *count)
static int api_ormeta_get_info (API_RESULTSET_META *rm, int index, CI_RMETA_INFO_TYPE type, void *arg, size_t size)
static int api_ores_get_resultset_metadata (API_RESULTSET *res, API_RESULTSET_META **rimpl)
static int api_ores_fetch (API_RESULTSET *res, int offset, CI_FETCH_POSITION pos)
static int api_ores_tell (API_RESULTSET *res, int *offset)
static int api_ores_clear_updates (API_RESULTSET *res)
static int api_ores_delete_row (API_RESULTSET *res)
static int api_ores_get_value (API_RESULTSET *res, int index, CI_TYPE type, void *addr, size_t len, size_t *outlen, bool *is_null)
static int api_ores_get_value_by_name (API_RESULTSET *res, const char *name, CI_TYPE type, void *addr, size_t len, size_t *outlen, bool *isnull)
static int api_ores_update_value (API_RESULTSET *res, int index, CI_TYPE type, void *addr, size_t len)
static int api_ores_apply_update (API_RESULTSET *res)
static void api_ores_destroy (API_RESULTSET *res)
static int opool_get_object_resultset (API_OBJECT_RESULTSET_POOL *poo, CI_OID *oid, API_RESULTSET **rres)
static int opool_oid_delete (API_OBJECT_RESULTSET_POOL *poo, CI_OID *oid)
static int opool_oid_get_classname (API_OBJECT_RESULTSET_POOL *pool, CI_OID *oid, char *name, size_t size)
static void opool_destroy (API_OBJECT_RESULTSET_POOL *poo)
static int create_cci_object (CCI_OBJECT_POOL *pool, CI_OID *oid, CCI_OBJECT **cobj)
static void destroy_cci_object (CCI_OBJECT *obj)
static void on_close_opool_res (RESULTSET_IMPL *impl, void *arg)
static void xoid2oidstr (const CI_OID *xoid, char *oidbuf)
static int oidstr2xoid (const char *oidstr, CI_CONNECTION conn, CI_OID *xoid)
static int opool_ht_comparef (void *key1, void *key2, int *r)
static int opool_ht_hashf (void *key, unsigned int *rv)
static int opool_ht_keyf (void *elem, void **rk)
static void opool_ht_elem_dtor (void *elem)
static int opool_ght_keyf (void *elem, void **rk)
static void opool_ght_elem_dtor (void *elem)
static int opool_create (CONNECTION_IMPL *pconn, CCI_OBJECT_POOL **rpool)
static int api_col_length (API_COLLECTION *col, int *len)
static int api_col_insert (API_COLLECTION *col, long pos, CI_TYPE type, void *ptr, size_t size)
static int api_col_update (API_COLLECTION *col, long pos, CI_TYPE type, void *ptr, size_t size)
static int api_col_delete (API_COLLECTION *col, long pos)
static int api_col_get_elem_domain_info (API_COLLECTION *col, long pos, CI_TYPE *type, int *precision, int *scale)
static int api_col_get_elem (API_COLLECTION *col, long pos, CI_TYPE type, void *addr, size_t len, size_t *outlen, bool *isnull)
static void api_col_destroy (API_COLLECTION *col)
static void xcol_elem_dtor (VALUE_AREA *va, API_VALUE *av)
static int xcol_create (CI_TYPE type, CI_CONNECTION conn, CI_COLLECTION *rcol)
static void xcol_destroy (CI_COLLECTION col)
static int xcol_elem_cci_bind_mapf (void *arg, int index, VALUE_AREA *va, API_VALUE *av)
static int xcol_to_cci_set (CI_COLLECTION col, T_CCI_SET *tset)
static int cci_set_to_xcol (CI_CONNECTION conn, T_CCI_SET tset, CI_COLLECTION *col)
static int xcol_copy (CI_COLLECTION col, CI_COLLECTION *rcol)
static int qres_apply_updatef (void *arg, int index, VALUE_AREA *va, API_VALUE *v)
static int ores_apply_updatef (void *arg, int index, VALUE_AREA *va, API_VALUE *v)
static int ci_create_connection_impl (CI_CONNECTION *conn)
static int ci_err_set_impl (int err_code)
static int ci_conn_connect_impl (COMMON_API_STRUCTURE *conn, const char *host, unsigned short port, const char *databasename, const char *user_name, const char *password)
static int ci_conn_close_impl (COMMON_API_STRUCTURE *conn)
static int ci_conn_create_statement_impl (COMMON_API_STRUCTURE *conn, CI_STATEMENT *stmt)
static int ci_conn_set_option_impl (COMMON_API_STRUCTURE *conn, CI_CONNECTION_OPTION option, void *arg, size_t size)
static int ci_conn_get_option_impl (COMMON_API_STRUCTURE *conn, CI_CONNECTION_OPTION option, void *arg, size_t size)
static int ci_conn_commit_impl (COMMON_API_STRUCTURE *conn)
static int ci_conn_rollback_impl (COMMON_API_STRUCTURE *conn)
static int ci_conn_get_error_impl (COMMON_API_STRUCTURE *conn, int *err, char *msg, size_t size)
static int ci_stmt_add_batch_query_impl (COMMON_API_STRUCTURE *stmt, const char *sql, size_t len)
static int ci_stmt_add_batch_impl (COMMON_API_STRUCTURE *stmt)
static int ci_stmt_clear_batch_impl (COMMON_API_STRUCTURE *stmt)
static int ci_stmt_execute_immediate_impl (COMMON_API_STRUCTURE *stmt, char *sql, size_t len, CI_RESULTSET *rs, int *r)
static int ci_stmt_execute_impl (COMMON_API_STRUCTURE *stmt, CI_RESULTSET *rs, int *r)
static int ci_stmt_execute_batch_impl (COMMON_API_STRUCTURE *stmt, CI_BATCH_RESULT *br)
static int ci_stmt_get_option_impl (COMMON_API_STRUCTURE *stmt, CI_STATEMENT_OPTION option, void *arg, size_t size)
static int ci_stmt_set_option_impl (COMMON_API_STRUCTURE *stmt, CI_STATEMENT_OPTION option, void *arg, size_t size)
static int ci_stmt_prepare_impl (COMMON_API_STRUCTURE *stmt, const char *sql, size_t len)
static int ci_stmt_register_out_parameter_impl (COMMON_API_STRUCTURE *stmt, int index)
static int ci_stmt_get_resultset_metadata_impl (COMMON_API_STRUCTURE *stmt, CI_RESULTSET_METADATA *r)
static int ci_stmt_get_parameter_metadata_impl (COMMON_API_STRUCTURE *stmt, CI_PARAMETER_METADATA *r)
static int ci_stmt_get_parameter_impl (COMMON_API_STRUCTURE *stmt, int index, CI_TYPE type, void *addr, size_t len, size_t *outlen, bool *isnull)
static int ci_stmt_set_parameter_impl (COMMON_API_STRUCTURE *stmt, int index, CI_TYPE type, void *val, size_t size)
static int ci_stmt_get_resultset_impl (COMMON_API_STRUCTURE *stmt, CI_RESULTSET *r)
static int ci_stmt_affected_rows_impl (COMMON_API_STRUCTURE *stmt, int *out)
static int ci_stmt_next_result_impl (COMMON_API_STRUCTURE *stmt, bool *exist_result)
static int ci_stmt_get_first_error_impl (COMMON_API_STRUCTURE *stmt, int *line, int *col, int *errcode, char *err_msg, size_t size)
static int ci_stmt_get_next_error_impl (COMMON_API_STRUCTURE *stmt, int *line, int *col, int *errcode, char *err_msg, size_t size)
static int ci_stmt_get_query_type_impl (COMMON_API_STRUCTURE *stmt, CUBRID_STMT_TYPE *type)
static int ci_stmt_get_start_line_impl (COMMON_API_STRUCTURE *stmt, int *line)
static int ci_batch_res_query_count_impl (COMMON_API_STRUCTURE *br, int *count)
static int ci_batch_res_get_result_impl (COMMON_API_STRUCTURE *br, int index, int *ret, int *nr)
static int ci_batch_res_get_error_impl (COMMON_API_STRUCTURE *br, int index, int *err_code, char *err_msg, size_t buf_size)
static int ci_pmeta_get_count_impl (COMMON_API_STRUCTURE *pmeta, int *count)
static int ci_pmeta_get_info_impl (COMMON_API_STRUCTURE *pmeta, int index, CI_PMETA_INFO_TYPE type, void *arg, size_t size)
static int ci_get_connection_opool_impl (COMMON_API_STRUCTURE *pst, API_OBJECT_RESULTSET_POOL **rpool)
static int ci_collection_new_impl (CI_CONNECTION conn, CI_COLLECTION *coll)
Variables
static API_RESULTSET_IFS QRES_IFS_
static API_RESULTSET_META_IFS QRMETA_IFS_
static API_RESULTSET_META_IFS ORMETA_IFS_
static API_RESULTSET_IFS ORES_IFS_
static API_COLLECTION_IFS COL_IFS_
CUBRID_API_FUNCTION_TABLE Cubrid_api_function_table
Macro Definition Documentation
#define API_EXEC_POST (has_result)
Value:
do {                                                                  \
  if (pstmt->pconn->autocommit && !(has_result))                      \
    {                                                                 \
      res =                                                           \
        cci_end_tran (pstmt->pconn->conn_handle, CCI_TRAN_COMMIT,     \
                      &pstmt->pconn->err_buf);                        \
      if (r != 0)                                                     \
        return err_from_cci (res);                              \
    }                                                                 \
} while (0)
Definition at line 4577 of file cci_stub.c.
Referenced by ci_stmt_execute_immediate_impl(), and ci_stmt_execute_impl().
#define API_EXEC_PRE ()
Value:
do {                                                                  \
  if (pstmt->status & CI_STMT_STATUS_EXECUTED)                     \
    {                                                                 \
      res = complete_statement (pstmt);                               \
      if (res != NO_ERROR)                                            \
        return res;                                             \
      pstmt->status &= ~CI_STMT_STATUS_EXECUTED;                   \
    }                                                                 \
                                                                      \
  if (pstmt->pconn->autocommit && pstmt->pconn->n_need_complete > 0)  \
    {                                                                 \
      res = complete_connection (pstmt->pconn);                       \
      if (res != NO_ERROR)                                            \
        return res;                                             \
      assert (pstmt->pconn->n_need_complete == 0);                    \
    }                                                                 \
} while (0)
Definition at line 4558 of file cci_stub.c.
Referenced by ci_stmt_execute_immediate_impl(), and ci_stmt_execute_impl().
#define API_VAL_CCI_BIND_FLAG_GET 0x01
Definition at line 209 of file cci_stub.c.
Referenced by get_value_from_req_handle(), and get_value_from_tset().
#define API_VAL_CCI_BIND_FLAG_SET 0x02
Definition at line 210 of file cci_stub.c.
Referenced by api_ores_apply_update(), api_val_bind_param(), api_val_cci_bind_bind(), api_val_cursor_update(), and xcol_elem_cci_bind_mapf().
#define DBDEF_HEADER_
Definition at line 32 of file cci_stub.c.
Typedef Documentation
typedef struct api_val_s API_VAL
Definition at line 49 of file cci_stub.c.
typedef struct api_val_cci_bind_s API_VAL_CCI_BIND
Definition at line 50 of file cci_stub.c.
typedef struct batch_ary_item_s BATCH_ARY_ITEM
Definition at line 44 of file cci_stub.c.
typedef struct batch_result_impl_s BATCH_RESULT_IMPL
Definition at line 45 of file cci_stub.c.
typedef struct batch_sql_item_s BATCH_SQL_ITEM
Definition at line 43 of file cci_stub.c.
typedef struct cci_collection_s CCI_COLLECTION
Definition at line 53 of file cci_stub.c.
typedef struct cci_object_s CCI_OBJECT
Definition at line 51 of file cci_stub.c.
typedef struct cci_object_pool_s CCI_OBJECT_POOL
Definition at line 52 of file cci_stub.c.
typedef struct connection_impl_s CONNECTION_IMPL
Definition at line 41 of file cci_stub.c.
typedef enum impl_handle_type IMPL_HANDLE_TYPE
Definition at line 40 of file cci_stub.c.
typedef struct parameter_meta_impl_s PARAMETER_META_IMPL
Definition at line 42 of file cci_stub.c.
typedef struct resultset_impl_s RESULTSET_IMPL
Definition at line 48 of file cci_stub.c.
typedef struct resultset_meta_impl_s RESULTSET_META_IMPL
Definition at line 47 of file cci_stub.c.
typedef struct statement_impl_s STATEMENT_IMPL
Definition at line 46 of file cci_stub.c.
Function Documentation
static int add_batch_params_mapf (void * arg, int index, VALUE_AREA * va, API_VALUE * val) static
Definition at line 2474 of file cci_stub.c.
References batch_ary_item_s::ary, add_batch_params_arg::bai, ER_INTERFACE_PARAM_IS_NOT_SET, value_indexer_s::ifs, add_batch_params_arg::indexer, add_batch_params_arg::nadded, NO_ERROR, NULL, and value_indexer_ifs_s::set.
Referenced by ci_stmt_add_batch_impl().
static int add_batch_params_restore_mapf (void * arg, int index, VALUE_AREA * va, API_VALUE * val) static
Definition at line 2452 of file cci_stub.c.
References batch_ary_item_s::ary, add_batch_params_arg::bai, value_indexer_s::ifs, add_batch_params_arg::indexer, add_batch_params_arg::nadded, NO_ERROR, NULL, and value_indexer_ifs_s::set.
Referenced by ci_stmt_add_batch_impl().
static int api_col_delete (API_COLLECTION * col, long pos) static
Definition at line 3668 of file cci_stub.c.
References value_indexer_ifs_s::check, CHECK_FOR_DELETE, value_indexer_ifs_s::delete, value_indexer_s::ifs, cci_collection_s::indexer, NO_ERROR, and xcol_elem_dtor().
static void api_col_destroy (API_COLLECTION * col) static
Definition at line 3776 of file cci_stub.c.
References xcol_destroy().
static int api_col_get_elem (API_COLLECTION * col, long pos, CI_TYPE type, void * addr, size_t len, size_t * outlen, bool * isnull) static
Definition at line 3746 of file cci_stub.c.
References value_indexer_ifs_s::check, CHECK_FOR_GET, value_indexer_ifs_s::get, get_value_from_api_val(), value_indexer_s::ifs, cci_collection_s::indexer, and NO_ERROR.
static int api_col_get_elem_domain_info (API_COLLECTION * col, long pos, CI_TYPE * type, int * precision, int * scale) static
Definition at line 3701 of file cci_stub.c.
References value_indexer_ifs_s::check, CHECK_FOR_GET, value_indexer_ifs_s::get, value_indexer_s::ifs, cci_collection_s::indexer, NO_ERROR, and api_val_s::type.
static int api_col_insert (API_COLLECTION * col, long pos, CI_TYPE type, void * ptr, size_t size) static
Definition at line 3579 of file cci_stub.c.
References API_CALLOC, API_FREE, api_val_dtor(), value_indexer_ifs_s::check, CHECK_FOR_INSERT, ER_INTERFACE_INVALID_ARGUMENT, ER_INTERFACE_NO_MORE_MEMORY, value_indexer_s::ifs, cci_collection_s::indexer, value_indexer_ifs_s::insert, NO_ERROR, NULL, set_value_to_api_val(), and cci_collection_s::type.
static int api_col_length (API_COLLECTION * col, int * len) static
Definition at line 3558 of file cci_stub.c.
References value_indexer_s::ifs, cci_collection_s::indexer, value_indexer_ifs_s::length, and NO_ERROR.
static int api_col_update (API_COLLECTION * col, long pos, CI_TYPE type, void * ptr, size_t size) static
Definition at line 3633 of file cci_stub.c.
References value_indexer_ifs_s::check, CHECK_FOR_GET, CHECK_FOR_SET, ER_INTERFACE_INVALID_ARGUMENT, value_indexer_ifs_s::get, value_indexer_s::ifs, cci_collection_s::indexer, NO_ERROR, set_value_to_api_val(), and cci_collection_s::type.
static int api_ores_apply_update (API_RESULTSET * res) static
Definition at line 2976 of file cci_stub.c.
References API_CALLOC, API_FREE, API_MALLOC, api_val_cci_bind_clear(), API_VAL_CCI_BIND_FLAG_SET, api_val_cci_bind_init(), resultset_impl_s::arg, api_val_cci_bind_s::atype, ores_apply_updatef_s::binds, resultset_impl_s::conn, connection_impl_s::conn_handle, cci_object_s::deleted, ER_INTERFACE_NO_MORE_MEMORY, ER_INTERFACE_RESULTSET_CLOSED, connection_impl_s::err_buf, i, if(), value_indexer_s::ifs, value_indexer_ifs_s::map, ores_apply_updatef_s::names, ores_apply_updatef_s::nattrs, NO_ERROR, NULL, resultset_impl_s::num_col, ores_apply_updatef_s::nupdates, ores_apply_updatef(), cci_object_pool_s::pconn, cci_object_s::pool, ores_apply_updatef_s::pres, resultset_impl_s::updated_values, api_val_cci_bind_s::value, cci_object_s::xoid, and xoid2oidstr().
static int api_ores_clear_updates (API_RESULTSET * res) static
Definition at line 2783 of file cci_stub.c.
References api_qres_clear_updates(), resultset_impl_s::arg, assert, cci_object_s::deleted, ER_INTERFACE_RESULTSET_CLOSED, if(), and NULL.
static int api_ores_delete_row (API_RESULTSET * res) static
Definition at line 2805 of file cci_stub.c.
References resultset_impl_s::arg, assert, connection_impl_s::conn_handle, cci_object_s::deleted, ER_INTERFACE_GENERIC, connection_impl_s::err_buf, err_from_cci(), NO_ERROR, NULL, cci_object_pool_s::pconn, cci_object_s::pool, cci_object_s::xoid, and xoid2oidstr().
static void api_ores_destroy (API_RESULTSET * res) static
Definition at line 3073 of file cci_stub.c.
References assert.
static int api_ores_fetch (API_RESULTSET * res, int offset, CI_FETCH_POSITION pos) static
Definition at line 2738 of file cci_stub.c.
References api_qres_fetch(), resultset_impl_s::arg, assert, cci_object_s::deleted, ER_INTERFACE_RESULTSET_CLOSED, if(), and NULL.
static int api_ores_get_resultset_metadata (API_RESULTSET * res, API_RESULTSET_META ** rimpl) static
Definition at line 2714 of file cci_stub.c.
References api_qres_get_resultset_metadata(), resultset_impl_s::arg, assert, cci_object_s::deleted, ER_INTERFACE_RESULTSET_CLOSED, if(), and NULL.
static int api_ores_get_value (API_RESULTSET * res, int index, CI_TYPE type, void * addr, size_t len, size_t * outlen, bool * is_null) static
Definition at line 2844 of file cci_stub.c.
References api_qres_get_value(), resultset_impl_s::arg, assert, cci_object_s::deleted, ER_INTERFACE_RESULTSET_CLOSED, if(), and NULL.
static int api_ores_get_value_by_name (API_RESULTSET * res, const char * name, CI_TYPE type, void * addr, size_t len, size_t * outlen, bool * isnull) static
Definition at line 2873 of file cci_stub.c.
References api_qres_get_value_by_name(), resultset_impl_s::arg, assert, cci_object_s::deleted, ER_INTERFACE_RESULTSET_CLOSED, if(), and NULL.
static int api_ores_tell (API_RESULTSET * res, int * offset) static
Definition at line 2761 of file cci_stub.c.
References api_qres_tell(), resultset_impl_s::arg, assert, cci_object_s::deleted, ER_INTERFACE_RESULTSET_CLOSED, if(), and NULL.
static int api_ores_update_value (API_RESULTSET * res, int index, CI_TYPE type, void * addr, size_t len) static
Definition at line 2900 of file cci_stub.c.
References api_qres_update_value(), resultset_impl_s::arg, cci_object_s::deleted, ER_INTERFACE_RESULTSET_CLOSED, ER_INTERFACE_RESULTSET_NOT_UPDATABLE, if(), and resultset_impl_s::updatable.
static int api_ormeta_get_count (API_RESULTSET_META * rm, int * count) static
Definition at line 2660 of file cci_stub.c.
References api_qrmeta_get_count(), resultset_impl_s::arg, assert, resultset_meta_impl_s::bp, cci_object_s::deleted, ER_INTERFACE_RESULTSET_CLOSED, if(), and NULL.
static int api_ormeta_get_info (API_RESULTSET_META * rm, int index, CI_RMETA_INFO_TYPE type, void * arg, size_t size) static
Definition at line 2686 of file cci_stub.c.
References api_qrmeta_get_info(), resultset_impl_s::arg, assert, resultset_meta_impl_s::bp, cci_object_s::deleted, ER_INTERFACE_RESULTSET_CLOSED, if(), and NULL.
static int api_qres_apply_update (API_RESULTSET * res) static
Definition at line 1867 of file cci_stub.c.
References value_indexer_s::ifs, value_indexer_ifs_s::map, NO_ERROR, NULL, qres_apply_updatef(), and resultset_impl_s::updated_values.
static int api_qres_clear_updates (API_RESULTSET * res) static
Definition at line 1593 of file cci_stub.c.
References api_val_dtor(), assert, value_indexer_ifs_s::check, CHECK_FOR_GET, CHECK_FOR_SET, value_indexer_ifs_s::get, i, value_indexer_s::ifs, value_indexer_ifs_s::length, NO_ERROR, NULL, value_indexer_ifs_s::set, and resultset_impl_s::updated_values.
Referenced by api_ores_clear_updates().
static int api_qres_delete_row (API_RESULTSET * res) static
Definition at line 1652 of file cci_stub.c.
References ER_INTERFACE_NOT_SUPPORTED_OPERATION.
static void api_qres_destroy (API_RESULTSET * res) static
Definition at line 1888 of file cci_stub.c.
static int api_qres_fetch (API_RESULTSET * res, int offset, CI_FETCH_POSITION pos) static
Definition at line 1532 of file cci_stub.c.
References assert, ER_INTERFACE_INVALID_ARGUMENT, ER_INTERFACE_NOT_SUPPORTED_OPERATION, resultset_impl_s::err_buf, err_from_cci(), resultset_impl_s::fetched, NO_ERROR, NULL, resultset_impl_s::offset, and resultset_impl_s::req_handle.
Referenced by api_ores_fetch().
static int api_qres_get_resultset_metadata (API_RESULTSET * res, API_RESULTSET_META ** rimpl) static
Definition at line 1501 of file cci_stub.c.
References assert, resultset_impl_s::got_rm_handle, lazy_bind_qres_rmeta(), NO_ERROR, NULL, and resultset_impl_s::RM.
Referenced by api_ores_get_resultset_metadata().
static int api_qres_get_value (API_RESULTSET * res, int index, CI_TYPE type, void * addr, size_t len, size_t * outlen, bool * is_null) static
Definition at line 1670 of file cci_stub.c.
References assert, value_indexer_ifs_s::check, CHECK_FOR_GET, CHECK_FOR_SET, resultset_impl_s::conn, resultset_impl_s::err_buf, err_from_cci(), resultset_impl_s::fetched, value_indexer_ifs_s::get, get_value_from_api_val(), get_value_from_req_handle(), value_indexer_s::ifs, NO_ERROR, NULL, resultset_impl_s::req_handle, and resultset_impl_s::updated_values.
Referenced by api_ores_get_value(), and api_qres_get_value_by_name().
static int api_qres_get_value_by_name (API_RESULTSET * res, const char * name, CI_TYPE type, void * addr, size_t len, size_t * outlen, bool * isnull) static
Definition at line 1738 of file cci_stub.c.
References api_qres_get_value(), assert, resultset_impl_s::col_info, ER_INTERFACE_INVALID_NAME, i, NULL, and resultset_impl_s::num_col.
Referenced by api_ores_get_value_by_name().
static int api_qres_tell (API_RESULTSET * res, int * offset) static
Definition at line 1577 of file cci_stub.c.
References NO_ERROR, and resultset_impl_s::offset.
Referenced by api_ores_tell().
static int api_qres_update_value (API_RESULTSET * res, int index, CI_TYPE type, void * addr, size_t len) static
Definition at line 1768 of file cci_stub.c.
References API_CALLOC, api_val_dtor(), array_indexer_create(), assert, value_indexer_ifs_s::check, CHECK_FOR_GET, CHECK_FOR_SET, ER_INTERFACE_NO_MORE_MEMORY, ER_INTERFACE_RESULTSET_NOT_UPDATABLE, value_indexer_ifs_s::get, value_indexer_s::ifs, NO_ERROR, NULL, resultset_impl_s::num_col, value_indexer_ifs_s::set, set_value_to_api_val(), resultset_impl_s::updatable, and resultset_impl_s::updated_values.
Referenced by api_ores_update_value().
static int api_qrmeta_get_count (API_RESULTSET_META * rm, int * count) static
Definition at line 2014 of file cci_stub.c.
References assert, resultset_meta_impl_s::bp, NO_ERROR, NULL, and resultset_impl_s::num_col.
Referenced by api_ormeta_get_count().
static int api_qrmeta_get_info (API_RESULTSET_META * rm, int index, CI_RMETA_INFO_TYPE type, void * arg, size_t size) static
Definition at line 2036 of file cci_stub.c.
References assert, resultset_meta_impl_s::bp, cci_u_type_to_type(), resultset_impl_s::col_info, ER_INTERFACE_INVALID_ARGUMENT, ER_INTERFACE_NOT_ENOUGH_DATA_SIZE, ER_INTERFACE_NOT_SUPPORTED_OPERATION, NO_ERROR, NULL, resultset_impl_s::num_col, p, strlen, and resultset_impl_s::updatable.
Referenced by api_ormeta_get_info().
static int api_val_bind_param (CI_CONNECTION conn, int req_handle, API_VAL * pv, int index) static
Definition at line 1143 of file cci_stub.c.
References api_val_cci_bind_bind(), api_val_cci_bind_clear(), API_VAL_CCI_BIND_FLAG_SET, api_val_cci_bind_init(), api_val_cci_bind_s::atype, err_from_cci(), api_val_s::len, NO_ERROR, api_val_s::ptr, api_val_s::type, type_to_cci_u_type(), and api_val_cci_bind_s::value.
Referenced by ci_stmt_execute_impl(), and stmt_execute_batch_array().
static int api_val_cci_bind_bind (CI_TYPE type, void * ptr, int len, API_VAL_CCI_BIND * bind) static
Definition at line 899 of file cci_stub.c.
References API_VAL_CCI_BIND_FLAG_SET, assert, api_val_cci_bind_s::atype, api_val_cci_bind_s::bit_val, api_val_cci_bind_s::cp, ER_INTERFACE_INVALID_ARGUMENT, ER_INTERFACE_NOT_ENOUGH_DATA_SIZE, api_val_cci_bind_s::flag, api_val_cci_bind_s::int_val, NO_ERROR, NULL, api_val_cci_bind_s::oid_buf, api_val_cci_bind_s::redirect, api_val_cci_bind_s::redirected, api_val_cci_bind_s::tset, api_val_cci_bind_s::value, xcol_to_cci_set(), and xoid2oidstr().
Referenced by api_val_bind_param(), api_val_cursor_update(), get_value_from_req_handle(), get_value_from_tset(), ores_apply_updatef(), and xcol_elem_cci_bind_mapf().
static void api_val_cci_bind_clear (API_VAL_CCI_BIND * bind) static
Definition at line 1120 of file cci_stub.c.
References api_val_cci_bind_s::atype, api_val_cci_bind_s::flag, NULL, api_val_cci_bind_s::redirect, api_val_cci_bind_s::redirected, and api_val_cci_bind_s::tset.
Referenced by api_ores_apply_update(), api_val_bind_param(), api_val_cursor_update(), get_value_from_req_handle(), get_value_from_tset(), and xcol_to_cci_set().
static void api_val_cci_bind_init (API_VAL_CCI_BIND * bind, CI_CONNECTION conn, int flag) static
Definition at line 1107 of file cci_stub.c.
References connection_impl_s::conn, api_val_cci_bind_s::conn, and api_val_cci_bind_s::flag.
Referenced by api_ores_apply_update(), api_val_bind_param(), api_val_cursor_update(), get_value_from_req_handle(), get_value_from_tset(), and xcol_elem_cci_bind_mapf().
static int api_val_cursor_update (CI_CONNECTION conn, int req_handle, int offset, int index, API_VAL * av, T_CCI_ERROR * err_buf) static
Definition at line 1441 of file cci_stub.c.
References api_val_cci_bind_bind(), api_val_cci_bind_clear(), API_VAL_CCI_BIND_FLAG_SET, api_val_cci_bind_init(), api_val_cci_bind_s::atype, err_from_cci(), api_val_s::len, NO_ERROR, api_val_s::ptr, api_val_s::type, and api_val_cci_bind_s::value.
Referenced by qres_apply_updatef().
static void api_val_dtor (VALUE_AREA * va, API_VALUE * val) static
Definition at line 586 of file cci_stub.c.
References API_FREE, NULL, api_val_s::ptr, api_val_s::type, and xcol_destroy().
Referenced by api_col_insert(), api_qres_clear_updates(), api_qres_update_value(), cci_set_to_xcol(), ci_stmt_set_parameter_impl(), complete_statement(), resultset_impl_dtor(), statement_impl_dtor(), stmt_complete_batch(), xcol_copy(), and xcol_elem_dtor().
static int bind_api_structure (BH_INTERFACE * bh, COMMON_API_STRUCTURE * s, COMMON_API_STRUCTURE * parent, BIND_HANDLE * handle) static
Definition at line 380 of file cci_stub.c.
References bh_interface_s::alloc_handle, assert, bh_interface_s::bind_graft, bh_interface_s::destroy_handle, NO_ERROR, and NULL.
Referenced by ci_conn_create_statement_impl(), ci_create_connection_impl(), ci_stmt_execute_batch_impl(), create_resultset_impl(), lazy_bind_pstmt_pmeta(), and lazy_bind_qres_rmeta().
static int cci_set_to_xcol (CI_CONNECTION conn, T_CCI_SET tset, CI_COLLECTION * col) static
Definition at line 3998 of file cci_stub.c.
References api_val_dtor(), assert, cci_u_type_to_type(), get_value_from_tset(), i, value_indexer_s::ifs, cci_collection_s::indexer, value_indexer_ifs_s::insert, NO_ERROR, NULL, xcol_create(), and xcol_destroy().
Referenced by get_value_from_req_handle(), and get_value_from_tset().
static CI_TYPE cci_u_type_to_type (T_CCI_U_TYPE utype) static
Definition at line 612 of file cci_stub.c.
Referenced by api_qrmeta_get_info(), cci_set_to_xcol(), and ci_pmeta_get_info_impl().
static int ci_batch_res_get_error_impl (COMMON_API_STRUCTURE * br, int index, int * err_code, char * err_msg, size_t buf_size) static
Definition at line 5348 of file cci_stub.c.
References batch_result_impl_s::bptr, ER_INTERFACE_INVALID_ARGUMENT, err_from_cci(), NO_ERROR, NULL, statement_impl_s::num_query, and statement_impl_s::query_result.
static int ci_batch_res_get_result_impl (COMMON_API_STRUCTURE * br, int index, int * ret, int * nr) static
Definition at line 5318 of file cci_stub.c.
References batch_result_impl_s::bptr, ER_INTERFACE_INVALID_ARGUMENT, err_from_cci(), NO_ERROR, statement_impl_s::num_query, and statement_impl_s::query_result.
static int ci_batch_res_query_count_impl (COMMON_API_STRUCTURE * br, int * count) static
Definition at line 5301 of file cci_stub.c.
References batch_result_impl_s::bptr, NO_ERROR, and statement_impl_s::num_query.
static int ci_collection_new_impl (CI_CONNECTION conn, CI_COLLECTION * coll) static
Definition at line 5485 of file cci_stub.c.
References xcol_create().
static int ci_conn_close_impl (COMMON_API_STRUCTURE * conn) static
Definition at line 4224 of file cci_stub.c.
References connection_impl_s::conn_handle, connection_impl_s::err_buf, and NO_ERROR.
static int ci_conn_commit_impl (COMMON_API_STRUCTURE * conn) static
Definition at line 4394 of file cci_stub.c.
References complete_connection(), connection_impl_s::conn_handle, connection_impl_s::err_buf, and err_from_cci().
static int ci_conn_connect_impl (COMMON_API_STRUCTURE * conn, const char * host, unsigned short port, const char * databasename, const char * user_name, const char * password) static
Definition at line 4202 of file cci_stub.c.
References connection_impl_s::conn_handle, err_from_cci(), and NO_ERROR.
static int ci_conn_create_statement_impl (COMMON_API_STRUCTURE * conn, CI_STATEMENT * stmt) static
Definition at line 4239 of file cci_stub.c.
References API_FREE, API_MALLOC, connection_impl_s::bh, bind_api_structure(), ER_INTERFACE_NO_MORE_MEMORY, init_statement_impl(), NO_ERROR, and NULL.
static int ci_conn_get_error_impl (COMMON_API_STRUCTURE * conn, int * err, char * msg, size_t size) static
Definition at line 4441 of file cci_stub.c.
References connection_impl_s::err_buf, err_from_cci(), and NO_ERROR.
static int ci_conn_get_option_impl (COMMON_API_STRUCTURE * conn, CI_CONNECTION_OPTION option, void * arg, size_t size) static
Definition at line 4330 of file cci_stub.c.
References connection_impl_s::conn_handle, ER_INTERFACE_INVALID_ARGUMENT, connection_impl_s::err_buf, err_from_cci(), and NO_ERROR.
static int ci_conn_rollback_impl (COMMON_API_STRUCTURE * conn) static
Definition at line 4416 of file cci_stub.c.
References complete_connection(), connection_impl_s::conn_handle, connection_impl_s::err_buf, and err_from_cci().
static int ci_conn_set_option_impl (COMMON_API_STRUCTURE * conn, CI_CONNECTION_OPTION option, void * arg, size_t size) static
Definition at line 4272 of file cci_stub.c.
References connection_impl_s::autocommit, connection_impl_s::conn_handle, ER_INTERFACE_INVALID_ARGUMENT, connection_impl_s::err_buf, err_from_cci(), and NO_ERROR.
static int ci_create_connection_impl (CI_CONNECTION * conn) static
Definition at line 4129 of file cci_stub.c.
References API_CALLOC, API_FREE, connection_impl_s::bh, bh_root_acquire(), bh_root_lock(), bh_root_release(), BH_ROOT_TYPE_STATIC_HASH_64, bh_root_unlock(), bind_api_structure(), ER_INTERFACE_NO_MORE_MEMORY, init_connection_impl(), NO_ERROR, NULL, opool_create(), opool_destroy(), and connection_impl_s::rid.
static int ci_err_set_impl (int err_code) static
Definition at line 4186 of file cci_stub.c.
References NO_ERROR.
static int ci_get_connection_opool_impl (COMMON_API_STRUCTURE * pst, API_OBJECT_RESULTSET_POOL ** rpool) static
Definition at line 5470 of file cci_stub.c.
References NO_ERROR, and connection_impl_s::opool.
static int ci_pmeta_get_count_impl (COMMON_API_STRUCTURE * pmeta, int * count) static
Definition at line 5385 of file cci_stub.c.
References parameter_meta_impl_s::bptr, NO_ERROR, and statement_impl_s::num_col.
static int ci_pmeta_get_info_impl (COMMON_API_STRUCTURE * pmeta, int index, CI_PMETA_INFO_TYPE type, void * arg, size_t size) static
Definition at line 5404 of file cci_stub.c.
References parameter_meta_impl_s::bptr, cci_u_type_to_type(), statement_impl_s::col_info, ER_INTERFACE_INVALID_ARGUMENT, ER_INTERFACE_NOT_ENOUGH_DATA_SIZE, if(), and NO_ERROR.
static int ci_stmt_add_batch_impl (COMMON_API_STRUCTURE * stmt) static
Definition at line 4495 of file cci_stub.c.
References add_batch_params_mapf(), add_batch_params_restore_mapf(), API_FREE, API_MALLOC, add_batch_params_arg::bai, statement_impl_s::batch, CI_STMT_STATUS_BATCH_ADDED, CI_STMT_STATUS_EXECUTED, CI_STMT_STATUS_PREPARED, dlisth_init, dlisth_insert_before, ER_INTERFACE_IS_NOT_BATCH_STATEMENT, ER_INTERFACE_IS_NOT_PREPARED_STATEMENT, ER_INTERFACE_NO_MORE_MEMORY, batch_ary_item_s::h, value_indexer_s::ifs, add_batch_params_arg::indexer, value_indexer_ifs_s::map, add_batch_params_arg::nadded, NO_ERROR, NULL, statement_impl_s::num_batch, statement_impl_s::num_col, statement_impl_s::params, and statement_impl_s::status.
static int ci_stmt_add_batch_query_impl (COMMON_API_STRUCTURE * stmt, const char * sql, size_t len) static
Definition at line 4459 of file cci_stub.c.
References API_MALLOC, statement_impl_s::batch, CI_STMT_STATUS_BATCH_ADDED, CI_STMT_STATUS_EXECUTED, CI_STMT_STATUS_PREPARED, dlisth_init, dlisth_insert_before, ER_INTERFACE_IS_NOT_BATCH_STATEMENT, ER_INTERFACE_IS_PREPARED_STATEMENT, ER_INTERFACE_NO_MORE_MEMORY, batch_sql_item_s::h, NO_ERROR, NULL, statement_impl_s::num_batch, batch_sql_item_s::sql, and statement_impl_s::status.
static int ci_stmt_affected_rows_impl (COMMON_API_STRUCTURE * stmt, int * out) static
Definition at line 5175 of file cci_stub.c.
References statement_impl_s::affected_rows, CI_STMT_STATUS_EXECUTED, ER_INTERFACE_NOT_EXECUTED, NO_ERROR, and statement_impl_s::status.
static int ci_stmt_clear_batch_impl (COMMON_API_STRUCTURE * stmt) static
Definition at line 4543 of file cci_stub.c.
References CI_STMT_STATUS_BATCH_ADDED, CI_STMT_STATUS_EXECUTED, ER_INTERFACE_CANNOT_CLEAR_BATCH, statement_impl_s::status, and stmt_complete_batch().
static int ci_stmt_execute_batch_impl (COMMON_API_STRUCTURE * stmt, CI_BATCH_RESULT * br) static
Definition at line 4749 of file cci_stub.c.
References connection_impl_s::bh, bind_api_structure(), statement_impl_s::BR, statement_impl_s::bres_handle, CI_STMT_STATUS_BATCH_ADDED, CI_STMT_STATUS_PREPARED, bh_interface_s::destroy_handle, ER_INTERFACE_CANNOT_BATCH_EXECUTE, handle, NO_ERROR, statement_impl_s::pconn, statement_impl_s::status, stmt_execute_batch_array(), and stmt_execute_batch_sql().
static int ci_stmt_execute_immediate_impl (COMMON_API_STRUCTURE * stmt, char * sql, size_t len, CI_RESULTSET * rs, int * r) static
Definition at line 4599 of file cci_stub.c.
References statement_impl_s::affected_rows, API_EXEC_POST, API_EXEC_PRE, connection_impl_s::bh, CI_STMT_STATUS_BATCH_ADDED, CI_STMT_STATUS_EXECUTED, CI_STMT_STATUS_PREPARED, connection_impl_s::conn_handle, ER_INTERFACE_IS_BATCH_STATEMENT, ER_INTERFACE_IS_PREPARED_STATEMENT, connection_impl_s::err_buf, err_from_cci(), statement_impl_s::has_resultset, connection_impl_s::n_need_complete, NO_ERROR, statement_impl_s::opt_updatable_result, statement_impl_s::pconn, statement_impl_s::req_handle, statement_impl_s::res_handle, statement_execute(), statement_get_reshandle_or_affectedrows(), and statement_impl_s::status.
static int ci_stmt_execute_impl (COMMON_API_STRUCTURE * stmt, CI_RESULTSET * rs, int * r) static
Definition at line 4672 of file cci_stub.c.
References statement_impl_s::affected_rows, API_EXEC_POST, API_EXEC_PRE, api_val_bind_param(), connection_impl_s::bh, value_indexer_ifs_s::check, CHECK_FOR_GET, CI_STMT_STATUS_EXECUTED, CI_STMT_STATUS_PREPARED, connection_impl_s::conn, ER_INTERFACE_IS_NOT_PREPARED_STATEMENT, ER_INTERFACE_PARAM_IS_NOT_SET, connection_impl_s::err_buf, value_indexer_ifs_s::get, statement_impl_s::has_resultset, i, value_indexer_s::ifs, connection_impl_s::n_need_complete, NO_ERROR, NULL, statement_impl_s::num_col, statement_impl_s::params, statement_impl_s::pconn, statement_impl_s::req_handle, statement_impl_s::res_handle, statement_execute(), statement_get_reshandle_or_affectedrows(), and statement_impl_s::status.
static int ci_stmt_get_first_error_impl (COMMON_API_STRUCTURE * stmt, int * line, int * col, int * errcode, char * err_msg, size_t size) static
Definition at line 5248 of file cci_stub.c.
References ER_INTERFACE_NOT_SUPPORTED_OPERATION.
static int ci_stmt_get_next_error_impl (COMMON_API_STRUCTURE * stmt, int * line, int * col, int * errcode, char * err_msg, size_t size) static
Definition at line 5265 of file cci_stub.c.
References ER_INTERFACE_NOT_SUPPORTED_OPERATION.
static int ci_stmt_get_option_impl (COMMON_API_STRUCTURE * stmt, CI_STATEMENT_OPTION option, void * arg, size_t size) static
Definition at line 4798 of file cci_stub.c.
References ER_INTERFACE_INVALID_ARGUMENT, NO_ERROR, and statement_impl_s::opt_updatable_result.
static int ci_stmt_get_parameter_impl (COMMON_API_STRUCTURE * stmt, int index, CI_TYPE type, void * addr, size_t len, size_t * outlen, bool * isnull) static
Definition at line 5023 of file cci_stub.c.
References value_indexer_ifs_s::check, CHECK_FOR_GET, CI_STMT_STATUS_PREPARED, ER_INTERFACE_IS_NOT_PREPARED_STATEMENT, ER_INTERFACE_PARAM_IS_NOT_SET, value_indexer_ifs_s::get, get_value_from_api_val(), value_indexer_s::ifs, NO_ERROR, NULL, statement_impl_s::params, and statement_impl_s::status.
static int ci_stmt_get_parameter_metadata_impl (COMMON_API_STRUCTURE * stmt, CI_PARAMETER_METADATA * r) static
Definition at line 4992 of file cci_stub.c.
References CI_STMT_STATUS_PREPARED, ER_INTERFACE_IS_NOT_PREPARED_STATEMENT, lazy_bind_pstmt_pmeta(), NO_ERROR, statement_impl_s::pm_handle, and statement_impl_s::status.
static int ci_stmt_get_query_type_impl (COMMON_API_STRUCTURE * stmt, CUBRID_STMT_TYPE * type) static
Definition at line 5277 of file cci_stub.c.
References ER_INTERFACE_NOT_SUPPORTED_OPERATION.
static int ci_stmt_get_resultset_impl (COMMON_API_STRUCTURE * stmt, CI_RESULTSET * r) static
Definition at line 5149 of file cci_stub.c.
References CI_STMT_STATUS_EXECUTED, ER_INTERFACE_HAS_NO_RESULT_SET, ER_INTERFACE_NOT_EXECUTED, statement_impl_s::has_resultset, NO_ERROR, statement_impl_s::res_handle, and statement_impl_s::status.
static int ci_stmt_get_resultset_metadata_impl (COMMON_API_STRUCTURE * stmt, CI_RESULTSET_METADATA * r) static
Definition at line 4945 of file cci_stub.c.
References assert, connection_impl_s::bh, CI_STMT_STATUS_EXECUTED, ER_INTERFACE_GENERIC, ER_INTERFACE_HAS_NO_RESULT_SET, ER_INTERFACE_NOT_EXECUTED, statement_impl_s::has_resultset, lazy_bind_qres_rmeta(), bh_interface_s::lookup, NO_ERROR, NULL, statement_impl_s::pconn, statement_impl_s::res_handle, resultset_impl_s::rm_handle, and statement_impl_s::status.
static int ci_stmt_get_start_line_impl (COMMON_API_STRUCTURE * stmt, int * line) static
Definition at line 5289 of file cci_stub.c.
References ER_INTERFACE_NOT_SUPPORTED_OPERATION.
static int ci_stmt_next_result_impl (COMMON_API_STRUCTURE * stmt, bool * exist_result) static
Definition at line 5195 of file cci_stub.c.
References connection_impl_s::bh, CAS_ER_NO_MORE_RESULT_SET, CI_STMT_STATUS_EXECUTED, statement_impl_s::curr_query_result_index, bh_interface_s::destroy_handle, ER_INTERFACE_NO_MORE_RESULT, ER_INTERFACE_NOT_EXECUTED, connection_impl_s::err_buf, err_from_cci(), statement_impl_s::has_resultset, NO_ERROR, statement_impl_s::num_query, statement_impl_s::pconn, statement_impl_s::req_handle, statement_impl_s::res_handle, statement_get_reshandle_or_affectedrows(), and statement_impl_s::status.
static int ci_stmt_prepare_impl (COMMON_API_STRUCTURE * stmt, const char * sql, size_t len) static
Definition at line 4876 of file cci_stub.c.
References CI_STMT_STATUS_EXECUTED, CI_STMT_STATUS_PREPARED, statement_impl_s::cmd_type, statement_impl_s::col_info, connection_impl_s::conn_handle, ER_INTERFACE_GENERIC, ER_INTERFACE_IS_NOT_PREPARED_STATEMENT, connection_impl_s::err_buf, err_from_cci(), statement_impl_s::got_pm_handle, NO_ERROR, NULL, statement_impl_s::num_col, statement_impl_s::opt_updatable_result, statement_impl_s::pconn, statement_impl_s::pm_handle, statement_impl_s::req_handle, and statement_impl_s::status.
static int ci_stmt_register_out_parameter_impl (COMMON_API_STRUCTURE * stmt, int index) static
Definition at line 4933 of file cci_stub.c.
References ER_INTERFACE_NOT_SUPPORTED_OPERATION.
static int ci_stmt_set_option_impl (COMMON_API_STRUCTURE * stmt, CI_STATEMENT_OPTION option, void * arg, size_t size) static
Definition at line 4842 of file cci_stub.c.
References ER_INTERFACE_INVALID_ARGUMENT, ER_INTERFACE_NOT_SUPPORTED_OPERATION, NO_ERROR, and statement_impl_s::opt_updatable_result.
static int ci_stmt_set_parameter_impl (COMMON_API_STRUCTURE * stmt, int index, CI_TYPE type, void * val, size_t size) static
Definition at line 5074 of file cci_stub.c.
References API_CALLOC, api_val_dtor(), array_indexer_create(), assert, value_indexer_ifs_s::check, CHECK_FOR_GET, CHECK_FOR_SET, CI_STMT_STATUS_PREPARED, ER_INTERFACE_IS_NOT_PREPARED_STATEMENT, ER_INTERFACE_NO_MORE_MEMORY, value_indexer_ifs_s::get, value_indexer_s::ifs, NO_ERROR, NULL, statement_impl_s::num_col, statement_impl_s::params, value_indexer_ifs_s::set, set_value_to_api_val(), statement_impl_s::status, and api_val_s::type.
static int complete_connection (CONNECTION_IMPL * impl) static
Definition at line 547 of file cci_stub.c.
References connection_impl_s::bh, bh_interface_s::bind_get_first_child, bh_interface_s::bind_get_next_sibling, complete_statement(), HANDLE_TYPE_STATEMENT, NO_ERROR, and NULL.
Referenced by ci_conn_commit_impl(), and ci_conn_rollback_impl().
static int complete_statement (STATEMENT_IMPL * pstmt) static
Definition at line 2347 of file cci_stub.c.
References api_val_dtor(), assert, connection_impl_s::bh, value_indexer_ifs_s::check, CHECK_FOR_GET, CHECK_FOR_SET, CI_STMT_STATUS_BATCH_ADDED, CI_STMT_STATUS_EXECUTED, CI_STMT_STATUS_PREPARED, statement_impl_s::curr_query_result_index, bh_interface_s::destroy_handle, value_indexer_ifs_s::get, statement_impl_s::has_resultset, i, value_indexer_s::ifs, NO_ERROR, NULL, statement_impl_s::num_col, statement_impl_s::num_query, statement_impl_s::params, statement_impl_s::pconn, statement_impl_s::query_result, statement_impl_s::res_handle, value_indexer_ifs_s::set, statement_impl_s::status, and stmt_complete_batch().
Referenced by complete_connection().
static void connection_impl_dtor (BH_BIND * bind) static
Definition at line 491 of file cci_stub.c.
References API_FREE, connection_impl_s::conn_handle, connection_impl_s::err_buf, connection_impl_s::opool, and opool_destroy().
Referenced by init_connection_impl().
static int create_cci_object (CCI_OBJECT_POOL * pool, CI_OID * oid, CCI_OBJECT ** cobj) static
Definition at line 3215 of file cci_stub.c.
References API_FREE, API_MALLOC, connection_impl_s::bh, connection_impl_s::conn, connection_impl_s::conn_handle, create_resultset_impl(), cci_object_s::deleted, ER_INTERFACE_NO_MORE_MEMORY, connection_impl_s::err_buf, err_from_cci(), NO_ERROR, NULL, on_close_opool_res(), cci_object_pool_s::pconn, cci_object_s::pool, cci_object_s::pres, ores_apply_updatef_s::pres, cci_object_s::req_handle, cci_object_s::xoid, and xoid2oidstr().
Referenced by opool_get_object_resultset().
static int create_resultset_impl (CI_CONNECTION conn, BH_INTERFACE * bh, int req_handle, T_CCI_ERROR * err_buf, COMMON_API_STRUCTURE * parent, bool updatable, void * arg, void(*)(RESULTSET_IMPL *, void *) on_close, API_RESULTSET_IFS * resifs, API_RESULTSET_META_IFS * rmifs, RESULTSET_IMPL ** rpres) static
Definition at line 1923 of file cci_stub.c.
References API_CALLOC, API_FREE, resultset_impl_s::arg, connection_impl_s::bh, resultset_impl_s::bh, bind_api_structure(), resultset_meta_impl_s::bp, resultset_impl_s::cmd_type, resultset_impl_s::col_info, connection_impl_s::conn, resultset_impl_s::conn, ER_INTERFACE_GENERIC, ER_INTERFACE_NO_MORE_MEMORY, connection_impl_s::err_buf, resultset_impl_s::err_buf, resultset_impl_s::fetched, resultset_impl_s::got_rm_handle, handle, HANDLE_TYPE_RESULTSET, HANDLE_TYPE_RMETA, NO_ERROR, NULL, resultset_impl_s::num_col, resultset_impl_s::offset, resultset_impl_s::on_close, resultset_impl_s::parent, resultset_impl_s::req_handle, resultset_impl_dtor(), resultset_impl_s::RM, resultset_impl_s::rm_handle, and resultset_impl_s::updatable.
Referenced by create_cci_object(), and statement_get_reshandle_or_affectedrows().
static void destroy_cci_object (CCI_OBJECT * obj) static
Definition at line 3264 of file cci_stub.c.
References API_FREE, cci_object_s::pres, and resultset_impl_dtor().
Referenced by opool_get_object_resultset(), opool_ht_elem_dtor(), and opool_oid_delete().
static int err_from_cci (int err) static
Definition at line 415 of file cci_stub.c.
References CAS_ER_ARGS, CAS_ER_COLLECTION_DOMAIN, CAS_ER_COMMUNICATION, CAS_ER_DB_VALUE, CAS_ER_DBSERVER_DISCONNECTED, CAS_ER_FREE_SERVER, CAS_ER_INTERNAL, CAS_ER_INVALID_CALL_STMT, CAS_ER_IS, CAS_ER_MAX_CLIENT_EXCEEDED, CAS_ER_NO_MORE_DATA, CAS_ER_NO_MORE_MEMORY, CAS_ER_NO_MORE_RESULT_SET, CAS_ER_NOT_AUTHORIZED_CLIENT, CAS_ER_NOT_COLLECTION, CAS_ER_NUM_BIND, CAS_ER_OBJECT, CAS_ER_OPEN_FILE, CAS_ER_PARAM_NAME, CAS_ER_QUERY_CANCEL, CAS_ER_SCHEMA_TYPE, CAS_ER_SRV_HANDLE, CAS_ER_STMT_POOLING, CAS_ER_TRAN_TYPE, CAS_ER_TYPE_CONVERSION, CAS_ER_UNKNOWN_U_TYPE, CAS_ER_VERSION, ER_INTERFACE_BROKER, ER_INTERFACE_DBMS, ER_INTERFACE_GENERIC, and NO_ERROR.
Referenced by api_ores_delete_row(), api_qres_fetch(), api_qres_get_value(), api_val_bind_param(), api_val_cursor_update(), ci_batch_res_get_error_impl(), ci_batch_res_get_result_impl(), ci_conn_commit_impl(), ci_conn_connect_impl(), ci_conn_get_error_impl(), ci_conn_get_option_impl(), ci_conn_rollback_impl(), ci_conn_set_option_impl(), ci_stmt_execute_immediate_impl(), ci_stmt_next_result_impl(), ci_stmt_prepare_impl(), create_cci_object(), get_value_from_req_handle(), get_value_from_tset(), opool_oid_delete(), statement_execute(), statement_get_reshandle_or_affectedrows(), stmt_complete_batch(), stmt_execute_batch_array(), stmt_execute_batch_sql(), and xcol_to_cci_set().
static int get_type_value_size (CI_TYPE type, int * len) static
Definition at line 828 of file cci_stub.c.
References assert, ER_INTERFACE_GENERIC, NO_ERROR, and NULL.
Referenced by get_value_from_tset().
static int get_value_from_api_val (const API_VAL * pv, CI_TYPE type, void * addr, size_t len, size_t * outlen, bool * isnull) static
Definition at line 739 of file cci_stub.c.
References ER_INTERFACE_NOT_ENOUGH_DATA_SIZE, ER_INTERFACE_NOT_SUPPORTED_OPERATION, api_val_s::len, NO_ERROR, api_val_s::ptr, api_val_s::type, and xcol_copy().
Referenced by api_col_get_elem(), api_qres_get_value(), and ci_stmt_get_parameter_impl().
static int get_value_from_req_handle (CI_CONNECTION conn, int req_handle, int index, CI_TYPE type, void * addr, size_t len, size_t * outlen, bool * is_null) static
Definition at line 1183 of file cci_stub.c.
References api_val_cci_bind_bind(), api_val_cci_bind_clear(), API_VAL_CCI_BIND_FLAG_GET, api_val_cci_bind_init(), assert, api_val_cci_bind_s::atype, api_val_cci_bind_s::bit_val, cci_set_to_xcol(), api_val_cci_bind_s::conn, api_val_cci_bind_s::cp, ER_INTERFACE_GENERIC, ER_INTERFACE_NOT_ENOUGH_DATA_SIZE, err_from_cci(), NO_ERROR, api_val_cci_bind_s::oid_buf, oidstr2xoid(), api_val_cci_bind_s::redirect, api_val_cci_bind_s::redirected, api_val_cci_bind_s::tset, and api_val_cci_bind_s::value.
Referenced by api_qres_get_value().
static int get_value_from_tset (T_CCI_U_TYPE utype, T_CCI_SET tset, CI_TYPE type, CI_CONNECTION conn, int i, API_VAL ** pv) static
Definition at line 1283 of file cci_stub.c.
References API_FREE, API_MALLOC, api_val_cci_bind_bind(), api_val_cci_bind_clear(), API_VAL_CCI_BIND_FLAG_GET, api_val_cci_bind_init(), assert, api_val_cci_bind_s::atype, api_val_cci_bind_s::bit_val, cci_set_to_xcol(), api_val_cci_bind_s::cp, ER_INTERFACE_GENERIC, ER_INTERFACE_NO_MORE_MEMORY, err_from_cci(), get_type_value_size(), api_val_s::len, NO_ERROR, NULL, api_val_cci_bind_s::oid_buf, oidstr2xoid(), api_val_s::ptr, api_val_cci_bind_s::redirect, api_val_cci_bind_s::redirected, api_val_cci_bind_s::tset, api_val_s::type, and api_val_cci_bind_s::value.
Referenced by cci_set_to_xcol().
static void init_connection_impl (CONNECTION_IMPL * impl, int rid, CI_CONNECTION conn, BH_INTERFACE * bh, int conn_handle, CCI_OBJECT_POOL * pool) static
Definition at line 521 of file cci_stub.c.
References connection_impl_s::autocommit, connection_impl_s::bh, connection_impl_s::conn, connection_impl_s::conn_handle, connection_impl_dtor(), connection_impl_s::err_buf, HANDLE_TYPE_CONNECTION, connection_impl_s::n_need_complete, connection_impl_s::opool, and connection_impl_s::rid.
Referenced by ci_create_connection_impl().
static void init_statement_impl (STATEMENT_IMPL * pstmt, CONNECTION_IMPL * pconn) static
Definition at line 2216 of file cci_stub.c.
References statement_impl_s::batch, parameter_meta_impl_s::bptr, batch_result_impl_s::bptr, statement_impl_s::BR, CI_STMT_STATUS_INITIALIZED, dlisth_init, HANDLE_TYPE_BATCH_RESULT, HANDLE_TYPE_PMETA, HANDLE_TYPE_STATEMENT, NULL, statement_impl_s::num_batch, statement_impl_s::pconn, statement_impl_s::PM, statement_impl_s::req_handle, statement_impl_dtor(), and statement_impl_s::status.
Referenced by ci_conn_create_statement_impl().
static int lazy_bind_pstmt_pmeta (STATEMENT_IMPL * pstmt) static
Definition at line 2163 of file cci_stub.c.
References connection_impl_s::bh, bind_api_structure(), statement_impl_s::got_pm_handle, handle, NO_ERROR, statement_impl_s::pconn, statement_impl_s::PM, and statement_impl_s::pm_handle.
Referenced by ci_stmt_get_parameter_metadata_impl().
static int lazy_bind_qres_rmeta (RESULTSET_IMPL * pres) static
Definition at line 1471 of file cci_stub.c.
References resultset_impl_s::bh, bind_api_structure(), resultset_impl_s::got_rm_handle, handle, NO_ERROR, resultset_impl_s::RM, and resultset_impl_s::rm_handle.
Referenced by api_qres_get_resultset_metadata(), and ci_stmt_get_resultset_metadata_impl().
static int oidstr2xoid (const char * oidstr, CI_CONNECTION conn, CI_OID * xoid) static
Definition at line 3326 of file cci_stub.c.
References connection_impl_s::conn, ER_INTERFACE_GENERIC, NO_ERROR, NULL, p, and str_to_int32().
Referenced by get_value_from_req_handle(), and get_value_from_tset().
static void on_close_opool_res (RESULTSET_IMPL * impl, void * arg) static
Definition at line 3283 of file cci_stub.c.
References NULL, cci_object_s::pres, and cci_object_s::req_handle.
Referenced by create_cci_object().
static void on_close_statement_res (RESULTSET_IMPL * impl, void * arg) static
Definition at line 2427 of file cci_stub.c.
References statement_impl_s::affected_rows, statement_impl_s::has_resultset, and statement_impl_s::res_handle.
Referenced by statement_get_reshandle_or_affectedrows().
static int opool_create (CONNECTION_IMPL * pconn, CCI_OBJECT_POOL ** rpool) static
Definition at line 3506 of file cci_stub.c.
References API_FREE, API_MALLOC, assert, api_object_resultset_pool_s::destroy, ER_INTERFACE_NO_MORE_MEMORY, api_object_resultset_pool_s::get_object_resultset, cci_object_pool_s::ght, hash_destroy(), hash_new(), cci_object_pool_s::ht, cci_object_pool_s::ifs, NO_ERROR, NULL, api_object_resultset_pool_s::oid_delete, api_object_resultset_pool_s::oid_get_classname, opool_destroy(), opool_get_object_resultset(), opool_ght_keyf(), opool_ht_comparef(), opool_ht_hashf(), opool_ht_keyf(), opool_oid_delete(), opool_oid_get_classname(), and cci_object_pool_s::pconn.
Referenced by ci_create_connection_impl().
static void opool_destroy (API_OBJECT_RESULTSET_POOL * poo) static
Definition at line 3193 of file cci_stub.c.
References API_FREE, assert, cci_object_pool_s::ght, hash_destroy(), cci_object_pool_s::ht, NULL, opool_ght_elem_dtor(), and opool_ht_elem_dtor().
Referenced by ci_create_connection_impl(), connection_impl_dtor(), and opool_create().
static int opool_get_object_resultset (API_OBJECT_RESULTSET_POOL * poo, CI_OID * oid, API_RESULTSET ** rres) static
Definition at line 3100 of file cci_stub.c.
References assert, create_cci_object(), destroy_cci_object(), hash_insert(), hash_lookup(), cci_object_pool_s::ht, NO_ERROR, NULL, and cci_object_s::pres.
Referenced by opool_create().
static void opool_ght_elem_dtor (void * elem) static
Definition at line 3492 of file cci_stub.c.
References API_FREE.
Referenced by opool_destroy().
static int opool_ght_keyf (void * elem, void ** rk) static
Definition at line 3474 of file cci_stub.c.
References assert, NO_ERROR, and NULL.
Referenced by opool_create().
static int opool_ht_comparef (void * key1, void * key2, int * r) static
Definition at line 3378 of file cci_stub.c.
References assert, NO_ERROR, and NULL.
Referenced by opool_create().
static void opool_ht_elem_dtor (void * elem) static
Definition at line 3460 of file cci_stub.c.
References destroy_cci_object().
Referenced by opool_destroy().
static int opool_ht_hashf (void * key, unsigned int * rv) static
Definition at line 3423 of file cci_stub.c.
References assert, NO_ERROR, and NULL.
Referenced by opool_create().
static int opool_ht_keyf (void * elem, void ** rk) static
Definition at line 3442 of file cci_stub.c.
References assert, NO_ERROR, NULL, and cci_object_s::xoid.
Referenced by opool_create().
static int opool_oid_delete (API_OBJECT_RESULTSET_POOL * poo, CI_OID * oid) static
Definition at line 3148 of file cci_stub.c.
References assert, connection_impl_s::conn_handle, destroy_cci_object(), connection_impl_s::err_buf, err_from_cci(), hash_delete(), cci_object_pool_s::ht, NO_ERROR, NULL, cci_object_pool_s::pconn, and xoid2oidstr().
Referenced by opool_create().
static int opool_oid_get_classname (API_OBJECT_RESULTSET_POOL * pool, CI_OID * oid, char * name, size_t size) static
Definition at line 3182 of file cci_stub.c.
References ER_INTERFACE_NOT_SUPPORTED_OPERATION.
Referenced by opool_create().
static int ores_apply_updatef (void * arg, int index, VALUE_AREA * va, API_VALUE * v) static
Definition at line 2944 of file cci_stub.c.
References api_val_cci_bind_bind(), ores_apply_updatef_s::binds, resultset_impl_s::col_info, api_val_s::len, ores_apply_updatef_s::names, NO_ERROR, NULL, ores_apply_updatef_s::nupdates, ores_apply_updatef_s::pres, api_val_s::ptr, and api_val_s::type.
Referenced by api_ores_apply_update().
static int qres_apply_updatef (void * arg, int index, VALUE_AREA * va, API_VALUE * v) static
Definition at line 1845 of file cci_stub.c.
References api_val_cursor_update(), resultset_impl_s::conn, resultset_impl_s::err_buf, NO_ERROR, NULL, resultset_impl_s::offset, and resultset_impl_s::req_handle.
Referenced by api_qres_apply_update().
static void resultset_impl_dtor (BH_BIND * bind) static
Definition at line 1986 of file cci_stub.c.
References API_FREE, api_val_dtor(), resultset_impl_s::arg, value_indexer_ifs_s::destroy, value_indexer_s::ifs, NULL, resultset_impl_s::on_close, and resultset_impl_s::updated_values.
Referenced by create_resultset_impl(), and destroy_cci_object().
static int set_value_to_api_val (API_VAL * pv, CI_TYPE type, void * addr, size_t len) static
Definition at line 782 of file cci_stub.c.
References API_FREE, API_MALLOC, ER_INTERFACE_NO_MORE_MEMORY, if(), api_val_s::len, NO_ERROR, NULL, api_val_s::ptr, api_val_s::type, and xcol_destroy().
Referenced by api_col_insert(), api_col_update(), api_qres_update_value(), ci_stmt_set_parameter_impl(), and xcol_copy().
static int statement_execute (STATEMENT_IMPL * pstmt, T_CCI_ERROR * err_buf) static
Definition at line 2242 of file cci_stub.c.
References statement_impl_s::affected_rows, statement_impl_s::curr_query_result_index, err_from_cci(), statement_impl_s::has_resultset, NO_ERROR, NULL, statement_impl_s::num_query, statement_impl_s::query_result, statement_impl_s::req_handle, and statement_impl_s::res_handle.
Referenced by ci_stmt_execute_immediate_impl(), and ci_stmt_execute_impl().
static int statement_get_reshandle_or_affectedrows (BH_INTERFACE * bh, STATEMENT_IMPL * pstmt) static
Definition at line 2292 of file cci_stub.c.
References statement_impl_s::affected_rows, assert, connection_impl_s::bh, bh_interface_s::bind_to_handle, connection_impl_s::conn, create_resultset_impl(), statement_impl_s::curr_query_result_index, ER_INTERFACE_GENERIC, connection_impl_s::err_buf, err_from_cci(), statement_impl_s::has_resultset, NO_ERROR, statement_impl_s::num_query, on_close_statement_res(), statement_impl_s::opt_updatable_result, statement_impl_s::pconn, statement_impl_s::query_result, statement_impl_s::req_handle, and statement_impl_s::res_handle.
Referenced by ci_stmt_execute_immediate_impl(), ci_stmt_execute_impl(), and ci_stmt_next_result_impl().
static void statement_impl_dtor (BH_BIND * bind) static
Definition at line 2189 of file cci_stub.c.
References API_FREE, api_val_dtor(), value_indexer_ifs_s::destroy, value_indexer_s::ifs, NULL, statement_impl_s::params, and statement_impl_s::req_handle.
Referenced by init_statement_impl().
static int stmt_complete_batch (STATEMENT_IMPL * pstmt) static
Definition at line 2595 of file cci_stub.c.
References API_FREE, api_val_dtor(), batch_ary_item_s::ary, assert, statement_impl_s::batch, CI_STMT_STATUS_PREPARED, dlisth_delete, dlisth_init, dlisth_insert_after, dlisth_is_empty, err_from_cci(), i, dlisth_s::next, NO_ERROR, NULL, statement_impl_s::num_batch, statement_impl_s::num_col, statement_impl_s::num_query, statement_impl_s::query_result, and statement_impl_s::status.
Referenced by ci_stmt_clear_batch_impl(), and complete_statement().
static int stmt_execute_batch_array (STATEMENT_IMPL * pstmt) static
Definition at line 2551 of file cci_stub.c.
References api_val_bind_param(), batch_ary_item_s::ary, statement_impl_s::batch, connection_impl_s::conn, connection_impl_s::err_buf, err_from_cci(), i, dlisth_s::next, NO_ERROR, statement_impl_s::num_col, statement_impl_s::num_query, statement_impl_s::pconn, statement_impl_s::query_result, and statement_impl_s::req_handle.
Referenced by ci_stmt_execute_batch_impl().
static int stmt_execute_batch_sql (STATEMENT_IMPL * pstmt) static
Definition at line 2503 of file cci_stub.c.
References API_FREE, API_MALLOC, assert, statement_impl_s::batch, connection_impl_s::conn_handle, ER_INTERFACE_NO_MORE_MEMORY, connection_impl_s::err_buf, err_from_cci(), i, dlisth_s::next, NO_ERROR, NULL, statement_impl_s::num_batch, statement_impl_s::num_query, statement_impl_s::pconn, statement_impl_s::query_result, and batch_sql_item_s::sql.
Referenced by ci_stmt_execute_batch_impl().
static T_CCI_U_TYPE type_to_cci_u_type (CI_TYPE type) static
Definition at line 675 of file cci_stub.c.
Referenced by api_val_bind_param(), and xcol_to_cci_set().
static int xcol_copy (CI_COLLECTION col, CI_COLLECTION * rcol) static
Definition at line 4057 of file cci_stub.c.
References API_CALLOC, API_FREE, api_val_dtor(), assert, cci_collection_s::col, api_collection_s::conn, ER_INTERFACE_NO_MORE_MEMORY, value_indexer_ifs_s::get, i, value_indexer_s::ifs, cci_collection_s::indexer, value_indexer_ifs_s::insert, api_val_s::len, value_indexer_ifs_s::length, NO_ERROR, NULL, api_val_s::ptr, rc, set_value_to_api_val(), api_val_s::type, cci_collection_s::type, xcol_create(), and xcol_destroy().
Referenced by get_value_from_api_val().
static int xcol_create (CI_TYPE type, CI_CONNECTION conn, CI_COLLECTION * rcol) static
Definition at line 3818 of file cci_stub.c.
References API_FREE, API_MALLOC, cci_collection_s::col, COL_IFS_, connection_impl_s::conn, api_collection_s::conn, ER_INTERFACE_NO_MORE_MEMORY, api_collection_s::ifs, cci_collection_s::indexer, list_indexer_create(), NO_ERROR, NULL, and cci_collection_s::type.
Referenced by cci_set_to_xcol(), ci_collection_new_impl(), and xcol_copy().
static void xcol_destroy (CI_COLLECTION col) static
Definition at line 3851 of file cci_stub.c.
References API_FREE, value_indexer_ifs_s::destroy, value_indexer_s::ifs, cci_collection_s::indexer, and xcol_elem_dtor().
Referenced by api_col_destroy(), api_val_dtor(), cci_set_to_xcol(), set_value_to_api_val(), and xcol_copy().
static int xcol_elem_cci_bind_mapf (void * arg, int index, VALUE_AREA * va, API_VALUE * av) static
Definition at line 3871 of file cci_stub.c.
References api_val_cci_bind_bind(), API_VAL_CCI_BIND_FLAG_SET, api_val_cci_bind_init(), assert, ores_apply_updatef_s::binds, api_val_s::len, NULL, api_val_s::ptr, and api_val_s::type.
Referenced by xcol_to_cci_set().
static void xcol_elem_dtor (VALUE_AREA * va, API_VALUE * av) static
Definition at line 3800 of file cci_stub.c.
References api_val_dtor().
Referenced by api_col_delete(), and xcol_destroy().
static int xcol_to_cci_set (CI_COLLECTION col, T_CCI_SET * tset) static
Definition at line 3898 of file cci_stub.c.
References API_CALLOC, API_FREE, api_val_cci_bind_clear(), assert, api_val_cci_bind_s::atype, ores_apply_updatef_s::binds, ER_INTERFACE_NO_MORE_MEMORY, err_from_cci(), i, value_indexer_s::ifs, cci_collection_s::indexer, value_indexer_ifs_s::length, value_indexer_ifs_s::map, NO_ERROR, NULL, cci_collection_s::type, type_to_cci_u_type(), api_val_cci_bind_s::value, and xcol_elem_cci_bind_mapf().
Referenced by api_val_cci_bind_bind().
static void xoid2oidstr (const CI_OID * xoid, char * oidbuf) static
Definition at line 3302 of file cci_stub.c.
References assert, and NULL.
Referenced by api_ores_apply_update(), api_ores_delete_row(), api_val_cci_bind_bind(), create_cci_object(), and opool_oid_delete().
Variable Documentation
API_COLLECTION_IFS COL_IFS_ static
Initial value:
= {
  api_col_length,
  api_col_insert,
  api_col_update,
  api_col_delete,
  api_col_get_elem_domain_info,
  api_col_get_elem,
  api_col_destroy
}
Definition at line 3783 of file cci_stub.c.
Referenced by xcol_create().
CUBRID_API_FUNCTION_TABLE Cubrid_api_function_table
Definition at line 5491 of file cci_stub.c.
API_RESULTSET_IFS ORES_IFS_ static
Initial value:
= {
  api_ores_get_resultset_metadata,
  api_ores_fetch,
  api_ores_tell,
  api_ores_clear_updates,
  api_ores_delete_row,
  api_ores_get_value,
  api_ores_get_value_by_name,
  api_ores_update_value,
  api_ores_apply_update,
  api_ores_destroy
}
Definition at line 3079 of file cci_stub.c.
API_RESULTSET_META_IFS ORMETA_IFS_ static
Initial value:
= {
  api_ormeta_get_count,
  api_ormeta_get_info
}
Definition at line 2702 of file cci_stub.c.
API_RESULTSET_IFS QRES_IFS_ static
Initial value:
= {
  api_qres_get_resultset_metadata,
  api_qres_fetch,
  api_qres_tell,
  api_qres_clear_updates,
  api_qres_delete_row,
  api_qres_get_value,
  api_qres_get_value_by_name,
  api_qres_update_value,
  api_qres_apply_update,
  api_qres_destroy
}
Definition at line 1893 of file cci_stub.c.
API_RESULTSET_META_IFS QRMETA_IFS_ static
Initial value:
= {
  api_qrmeta_get_count,
  api_qrmeta_get_info
}
Definition at line 2152 of file cci_stub.c.