CUBRID Engine: src/base/chartype.c File Reference
chartype.c File Reference
#include "config.h"
#include "chartype.h"
Functions
int char_islower (int c)
int char_isupper (int c)
int char_isalpha (int c)
int char_isdigit (int c)
int char_isxdigit (int c)
int char_isalnum (int c)
int char_isspace (int c)
int char_iseol (int c)
int char_tolower (int c)
int char_toupper (int c)
int char_isupper_iso8859 (int c)
int char_islower_iso8859 (int c)
int char_tolower_iso8859 (int c)
int char_toupper_iso8859 (int c)
Variables
static const int A_GRAVE_ACCENT = 192
static const int MULT_ISO8859 = 215
static const int CAPITAL_THORN = 222
static const int a_GRAVE_ACCENT = 224
static const int DIV_ISO8859 = 247
static const int SMALL_THORN = 254
Function Documentation
int char_isalnum (int c)
Definition at line 97 of file chartype.c.
References char_isalpha(), and char_isdigit().
Referenced by lang_check_identifier(), and parse_tzd().
int char_isalpha (int c)
Definition at line 61 of file chartype.c.
Referenced by calc_unix_timestamp(), char_isalnum(), db_date_parse_datetime_parts(), db_date_parse_time(), lang_check_identifier(), parse_date_separated(), parse_explicit_mtime_compact(), parse_explicit_mtime_separated(), parse_mtime_separated(), parse_timedate_separated(), parse_timestamp_compact(), and rel_compare().
int char_isdigit (int c)
Definition at line 73 of file chartype.c.
Referenced by adjust_precision(), calc_unix_timestamp(), char_isalnum(), char_isxdigit(), createdb(), db_date_parse_datetime_parts(), db_date_parse_time(), db_format(), db_str_to_date(), db_to_datetime(), er_study_spec(), er_vsprintf(), is_valid_ip_slice(), key_isdigit(), ldr_get_start_line_no(), make_number(), make_number_to_char(), obj_get_path(), parse_date(), parse_date_separated(), parse_explicit_mtime_compact(), parse_explicit_mtime_separated(), parse_mtime(), parse_mtime_separated(), parse_time_string(), parse_timedate_separated(), parse_timestamp_compact(), scientific_to_decimal_string(), tp_atobi(), tp_digit_number_str_to_bi(), tp_hex_str_to_bi(), tp_scientific_str_to_bi(), and tz_str_read_number().
int char_iseol (int c)
Definition at line 121 of file chartype.c.
Referenced by cfg_next_line(), and cfg_pop_linetoken().
int char_islower (int c)
Definition at line 37 of file chartype.c.
Referenced by char_isalpha(), char_islower_iso8859(), and char_toupper().
int char_islower_iso8859 (int c)
Definition at line 189 of file chartype.c.
References a_GRAVE_ACCENT, char_islower(), DIV_ISO8859, and SMALL_THORN.
Referenced by char_toupper_iso8859(), and intl_toupper_iso8859().
int char_isspace (int c)
Definition at line 109 of file chartype.c.
Referenced by adjust_precision(), boot_parse_add_volume_extensions(), cfg_next_char(), cfg_pop_host(), cfg_pop_linetoken(), cfg_pop_token(), db_date_parse_datetime_parts(), db_date_parse_time(), db_get_date_quarter(), db_string_check_explicit_date(), db_string_to_date_ex(), db_string_to_datetime_ex(), db_string_to_datetimetz_ex(), db_string_to_time_ex(), db_string_to_timestamp_ex(), db_string_to_timestamptz_ex(), ehash_hash_string_type(), heap_object_upgrade_domain(), ini_parser_load(), ini_str_trim(), intl_backskip_spaces(), intl_is_space(), intl_skip_spaces(), load_console_conv_data(), locale_get_cfg_locales(), obj_get_path(), obj_print_next_token(), parse_date(), parse_date_separated(), parse_explicit_mtime_compact(), parse_explicit_mtime_separated(), parse_mtime(), parse_mtime_separated(), parse_timedate_separated(), parse_timestamp_compact(), prm_get_next_param_value(), pt_chop_trailing_dots(), scientific_to_decimal_string(), sm_count_tokens(), sm_split_loader_commands(), start_collations(), str_day_to_int(), str_month_to_int(), str_pop_token(), sysprm_obtain_parameters(), tp_atobi(), tp_atof(), trim_comments_whitespaces(), tz_get_timezone_offset(), tz_str_timezone_decode(), and tz_str_to_region().
int char_isupper (int c)
Definition at line 49 of file chartype.c.
Referenced by char_isalpha(), char_isupper_iso8859(), char_tolower(), and locale_alloc_collation_id().
int char_isupper_iso8859 (int c)
Definition at line 177 of file chartype.c.
References A_GRAVE_ACCENT, CAPITAL_THORN, char_isupper(), and MULT_ISO8859.
Referenced by char_tolower_iso8859(), intl_identifier_mht_1strlowerhash(), and intl_tolower_iso8859().
int char_isxdigit (int c)
Definition at line 85 of file chartype.c.
References char_isdigit().
Referenced by is_valid_ip_slice(), and tp_hex_str_to_bi().
int char_tolower (int c)
Definition at line 146 of file chartype.c.
Referenced by fileio_request_user_response(), get_next_format(), get_number_token(), ini_str_lower(), intl_identifier_lower(), intl_identifier_mht_1strlowerhash(), intl_mbs_ncpy(), intl_tolower_euc(), is_valid_ip_slice(), make_number(), make_number_to_char(), mht_1strlowerhash(), net_client_request_with_callback(), pp_generic_case_hash(), and to_number_next_state().
int char_tolower_iso8859 (int c)
Definition at line 200 of file chartype.c.
References char_isupper_iso8859().
Referenced by intl_case_match_tok(), intl_identifier_casecmp_w_size(), intl_identifier_lower(), intl_identifier_mht_1strlowerhash(), and intl_lower_string().
int char_toupper (int c)
Definition at line 157 of file chartype.c.
References char_islower().
Referenced by intl_identifier_upper(), intl_mbs_ncpy(), intl_toupper_euc(), and pt_find_keyword().
int char_toupper_iso8859 (int c)
Definition at line 211 of file chartype.c.
References char_islower_iso8859().
Referenced by intl_identifier_upper(), and intl_upper_string().
Variable Documentation
const int A_GRAVE_ACCENT = 192 static
Definition at line 163 of file chartype.c.
Referenced by char_isupper_iso8859().
const int a_GRAVE_ACCENT = 224 static
Definition at line 167 of file chartype.c.
Referenced by char_islower_iso8859().
const int CAPITAL_THORN = 222 static
Definition at line 165 of file chartype.c.
Referenced by char_isupper_iso8859().
const int DIV_ISO8859 = 247 static
Definition at line 168 of file chartype.c.
Referenced by char_islower_iso8859().
const int MULT_ISO8859 = 215 static
Definition at line 164 of file chartype.c.
Referenced by char_isupper_iso8859().
const int SMALL_THORN = 254 static
Definition at line 169 of file chartype.c.
Referenced by char_islower_iso8859().