CUBRID Engine: db_value_printer Class Reference
db_value_printer Class Reference
#include <db_value_printer.hpp>
Public Member Functions
db_value_printer (string_buffer &buf, bool padding=false)
void describe_money (const db_monetary *value)
void describe_value (const db_value *value)
void describe_data (const db_value *value)
Static Public Attributes
static const char DECIMAL_FORMAT [] = "%#.*g"
Protected Member Functions
void describe_midxkey (const db_midxkey *midxkey, int help_Max_set_elements=20)
void describe_set (const db_set *set, int help_Max_set_elements=20)
Private Attributes
string_buffer & m_buf
bool m_padding
Detailed Description
Definition at line 38 of file db_value_printer.hpp.
Constructor & Destructor Documentation
db_value_printer::db_value_printer (string_buffer & buf, bool padding = false) inline
Definition at line 46 of file db_value_printer.hpp.
References db_fprint_value(), db_print_value(), db_sprint_value(), describe_data(), describe_midxkey(), describe_money(), describe_set(), and describe_value().
Member Function Documentation
void db_value_printer::describe_data (const db_value * value)
Definition at line 238 of file db_value_printer.cpp.
References string_buffer::add_bytes(), db_monetary::amount, assert, db_datetimetz::datetime, db_date_to_string(), db_datetime_to_string(), db_datetimeltz_to_string(), db_datetimetz_to_string(), DB_DOUBLE_DECIMAL_PRECISION, DB_FLOAT_DECIMAL_PRECISION, db_get_bigint(), db_get_date(), db_get_datetime(), db_get_datetimetz(), db_get_double(), db_get_elo(), db_get_error(), db_get_float(), db_get_int(), db_get_json_raw_body(), db_get_midxkey(), db_get_monetary(), db_get_object(), db_get_oid(), db_get_pointer(), db_get_set(), db_get_short(), db_get_string(), db_get_string_size(), db_get_time(), db_get_timestamp(), db_get_timestamptz(), DB_IS_NULL, db_private_free, db_time_to_string(), db_timestampltz_to_string(), db_timestamptz_to_string(), DB_TYPE_BIGINT, DB_TYPE_BIT, DB_TYPE_BLOB, DB_TYPE_CHAR, DB_TYPE_CLOB, DB_TYPE_DATE, DB_TYPE_DATETIME, DB_TYPE_DATETIMELTZ, DB_TYPE_DATETIMETZ, DB_TYPE_DB_VALUE, DB_TYPE_DOUBLE, DB_TYPE_ERROR, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_JSON, DB_TYPE_MIDXKEY, DB_TYPE_MONETARY, DB_TYPE_MULTISET, DB_TYPE_NCHAR, DB_TYPE_NULL, DB_TYPE_NUMERIC, DB_TYPE_OBJECT, DB_TYPE_OID, DB_TYPE_POINTER, DB_TYPE_SEQUENCE, DB_TYPE_SET, DB_TYPE_SHORT, DB_TYPE_SUB, DB_TYPE_TIME, DB_TYPE_TIMESTAMP, DB_TYPE_TIMESTAMPLTZ, DB_TYPE_TIMESTAMPTZ, DB_TYPE_VARBIT, DB_TYPE_VARCHAR, DB_TYPE_VARIABLE, DB_TYPE_VARNCHAR, DB_TYPE_VOBJ, db_utime_to_string, DB_VALUE_TYPE, describe_midxkey(), describe_money(), describe_set(), describe_value(), ELO_FBO, db_object::is_vid, db_elo::locator, m_buf, m_padding, NULL, numeric_db_value_print(), OR_MOVE_DOUBLE, db_identifier::pageid, db_identifier::slotid, db_timestamptz::timestamp, TOO_BIG_TO_MATTER, db_elo::type, db_timestamptz::tz_id, db_datetimetz::tz_id, vid_object_to_vobj(), db_identifier::volid, and WS_OID.
Referenced by db_value_printer(), describe_value(), and object_description::init().
void db_value_printer::describe_midxkey (const db_midxkey * midxkey, int help_Max_set_elements = 20) protected
Definition at line 500 of file db_value_printer.cpp.
References assert, DB_IS_NULL, describe_value(), i, m_buf, db_midxkey::ncolumns, db_value::need_clear, NULL, pr_clear_value(), pr_midxkey_get_element_nocopy(), and setobj::size.
Referenced by db_value_printer(), and describe_data().
void db_value_printer::describe_money (const db_monetary * value)
Definition at line 96 of file db_value_printer.cpp.
References db_monetary::amount, assert, string_buffer::get_buffer(), intl_get_money_esc_ISO_symbol(), m_buf, NULL, and db_monetary::type.
Referenced by db_value_printer(), describe_data(), and pt_print_db_value().
void db_value_printer::describe_set (const db_set * set, int help_Max_set_elements = 20) protected
Definition at line 543 of file db_value_printer.cpp.
References assert, db_value_clear(), describe_value(), i, m_buf, NULL, set_get_element(), set_size(), and setobj::size.
Referenced by db_value_printer(), and describe_data().
void db_value_printer::describe_value (const db_value * value)
Definition at line 108 of file db_value_printer.cpp.
References assert, db_get_enum_codeset(), db_get_enum_short(), db_get_enum_string(), db_get_string_codeset(), DB_IS_NULL, DB_TYPE_BIT, DB_TYPE_BLOB, DB_TYPE_CHAR, DB_TYPE_CLOB, DB_TYPE_DATE, DB_TYPE_DATETIME, DB_TYPE_DATETIMELTZ, DB_TYPE_DATETIMETZ, DB_TYPE_ENUMERATION, DB_TYPE_JSON, DB_TYPE_NCHAR, DB_TYPE_TIME, DB_TYPE_TIMESTAMP, DB_TYPE_TIMESTAMPLTZ, DB_TYPE_TIMESTAMPTZ, DB_TYPE_VARBIT, DB_TYPE_VARCHAR, DB_TYPE_VARNCHAR, DB_VALUE_TYPE, describe_data(), INTL_CODESET_NONE, lang_charset_introducer(), LANG_SYS_CODESET, m_buf, NO_ERROR, NULL, and tp_enumeration_to_varchar().
Referenced by chksum_print_lower_bound_string(), db_fprint_value(), db_print_value(), db_sprint_value(), db_value_printer(), object_printer::describe_attribute(), object_printer::describe_class(), object_printer::describe_comment(), describe_data(), describe_midxkey(), object_printer::describe_partition_parts(), describe_set(), object_description::init(), log_repl_data_dump(), pt_print_db_value(), sl_print_att_value(), sl_print_insert_att_values(), sl_print_midxkey(), sl_print_pk(), and sl_print_update_att_set().
Member Data Documentation
const char db_value_printer::DECIMAL_FORMAT = "%#.*g" static
Definition at line 44 of file db_value_printer.hpp.
Referenced by pt_print_value().
string_buffer& db_value_printer::m_buf private
Definition at line 41 of file db_value_printer.hpp.
Referenced by describe_data(), describe_midxkey(), describe_money(), describe_set(), and describe_value().
bool db_value_printer::m_padding private
Definition at line 42 of file db_value_printer.hpp.
Referenced by describe_data().
The documentation for this class was generated from the following files:
src/compat/db_value_printer.hpp
src/compat/db_value_printer.cpp