CUBRID Engine: cubmonitor::counter_timer_max_statistic< A, T, M > Class Template Reference
cubmonitor::counter_timer_max_statistic< A, T, M > Class Template Reference
#include <monitor_collect.hpp>
Public Member Functions
counter_timer_max_statistic (void)
void time_and_increment (const time_rep &d, const amount_rep &a=1)
void time_and_increment (const amount_rep &a=1)
std::size_t get_statistics_count (void) const
void fetch (statistic_value *destination, fetch_mode mode=FETCH_GLOBAL) const
amount_rep get_count (fetch_mode mode=FETCH_GLOBAL) const
time_rep get_time (fetch_mode mode=FETCH_GLOBAL) const
time_rep get_average_time (fetch_mode mode=FETCH_GLOBAL) const
time_rep get_max_time (fetch_mode mode=FETCH_GLOBAL) const
void register_to_monitor (monitor &mon, const char *basename) const
Private Attributes
timer m_timer
A m_amount_statistic
T m_total_time_statistic
M m_max_time_statistic
Detailed Description
template<class A = amount_accumulator_statistic, class T = time_accumulator_statistic, class M = time_max_statistic>
class cubmonitor::counter_timer_max_statistic< A, T, M >
Definition at line 194 of file monitor_collect.hpp.
Constructor & Destructor Documentation
template<class A , class T , class M > cubmonitor::counter_timer_max_statistic< A, T, M >::counter_timer_max_statistic (void) inline
Definition at line 437 of file monitor_collect.hpp.
Member Function Documentation
template<class A , class T , class M > void cubmonitor::counter_timer_max_statistic< A, T, M >::fetch (statistic_value * destination, fetch_mode mode = FETCH_GLOBAL) const inline
Definition at line 473 of file monitor_collect.hpp.
References assert, cubmonitor::counter_timer_max_statistic< A, T, M >::get_statistics_count(), cubmonitor::counter_timer_max_statistic< A, T, M >::m_amount_statistic, cubmonitor::counter_timer_max_statistic< A, T, M >::m_max_time_statistic, and cubmonitor::counter_timer_max_statistic< A, T, M >::m_total_time_statistic.
Referenced by cubmonitor::counter_timer_max_statistic< A, T, M >::register_to_monitor().
template<class A , class T , class M > time_rep cubmonitor::counter_timer_max_statistic< A, T, M >::get_average_time (fetch_mode mode = FETCH_GLOBAL) const inline
Definition at line 513 of file monitor_collect.hpp.
References cubmonitor::counter_timer_max_statistic< A, T, M >::get_count(), and cubmonitor::counter_timer_max_statistic< A, T, M >::get_time().
Referenced by cubmonitor::counter_timer_max_statistic< A, T, M >::register_to_monitor().
template<class A , class T , class M > amount_rep cubmonitor::counter_timer_max_statistic< A, T, M >::get_count (fetch_mode mode = FETCH_GLOBAL) const inline
Definition at line 492 of file monitor_collect.hpp.
References cubmonitor::counter_timer_max_statistic< A, T, M >::m_amount_statistic.
Referenced by cubmonitor::counter_timer_max_statistic< A, T, M >::get_average_time().
template<class A , class T , class M > time_rep cubmonitor::counter_timer_max_statistic< A, T, M >::get_max_time (fetch_mode mode = FETCH_GLOBAL) const inline
Definition at line 506 of file monitor_collect.hpp.
References cubmonitor::counter_timer_max_statistic< A, T, M >::m_max_time_statistic.
template<class A , class T , class M > std::size_t cubmonitor::counter_timer_max_statistic< A, T, M >::get_statistics_count (void) const inline
Definition at line 464 of file monitor_collect.hpp.
References cubmonitor::counter_timer_max_statistic< A, T, M >::m_amount_statistic, cubmonitor::counter_timer_max_statistic< A, T, M >::m_max_time_statistic, and cubmonitor::counter_timer_max_statistic< A, T, M >::m_total_time_statistic.
Referenced by cubmonitor::counter_timer_max_statistic< A, T, M >::fetch(), and cubmonitor::counter_timer_max_statistic< A, T, M >::register_to_monitor().
template<class A , class T , class M > time_rep cubmonitor::counter_timer_max_statistic< A, T, M >::get_time (fetch_mode mode = FETCH_GLOBAL) const inline
Definition at line 499 of file monitor_collect.hpp.
References cubmonitor::counter_timer_max_statistic< A, T, M >::m_total_time_statistic.
Referenced by cubmonitor::counter_timer_max_statistic< A, T, M >::get_average_time().
template<class A , class T , class M > void cubmonitor::counter_timer_max_statistic< A, T, M >::register_to_monitor (monitor & mon, const char * basename) const
Definition at line 520 of file monitor_collect.hpp.
References assert, cubmonitor::build_name_vector(), cubmonitor::counter_timer_max_statistic< A, T, M >::fetch(), fetch_func, cubmonitor::counter_timer_max_statistic< A, T, M >::get_average_time(), cubmonitor::counter_timer_max_statistic< A, T, M >::get_statistics_count(), mode, cubmonitor::monitor::register_statistics(), and cubmonitor::statistic_value_cast().
template<class A , class T , class M > void cubmonitor::counter_timer_max_statistic< A, T, M >::time_and_increment (const time_rep & d, const amount_rep & a = 1) inline
Definition at line 448 of file monitor_collect.hpp.
References cubmonitor::counter_timer_max_statistic< A, T, M >::m_amount_statistic, cubmonitor::counter_timer_max_statistic< A, T, M >::m_max_time_statistic, and cubmonitor::counter_timer_max_statistic< A, T, M >::m_total_time_statistic.
Referenced by cubmonitor::counter_timer_max_statistic< A, T, M >::time_and_increment().
template<class A , class T , class M > void cubmonitor::counter_timer_max_statistic< A, T, M >::time_and_increment (const amount_rep & a = 1) inline
Definition at line 457 of file monitor_collect.hpp.
References cubmonitor::counter_timer_max_statistic< A, T, M >::m_timer, cubmonitor::timer::time(), and cubmonitor::counter_timer_max_statistic< A, T, M >::time_and_increment().
Member Data Documentation
template<class A = amount_accumulator_statistic, class T = time_accumulator_statistic, class M = time_max_statistic> A cubmonitor::counter_timer_max_statistic< A, T, M >::m_amount_statistic private
Definition at line 218 of file monitor_collect.hpp.
Referenced by cubmonitor::counter_timer_max_statistic< A, T, M >::fetch(), cubmonitor::counter_timer_max_statistic< A, T, M >::get_count(), cubmonitor::counter_timer_max_statistic< A, T, M >::get_statistics_count(), and cubmonitor::counter_timer_max_statistic< A, T, M >::time_and_increment().
template<class A = amount_accumulator_statistic, class T = time_accumulator_statistic, class M = time_max_statistic> M cubmonitor::counter_timer_max_statistic< A, T, M >::m_max_time_statistic private
Definition at line 220 of file monitor_collect.hpp.
Referenced by cubmonitor::counter_timer_max_statistic< A, T, M >::fetch(), cubmonitor::counter_timer_max_statistic< A, T, M >::get_max_time(), cubmonitor::counter_timer_max_statistic< A, T, M >::get_statistics_count(), and cubmonitor::counter_timer_max_statistic< A, T, M >::time_and_increment().
template<class A = amount_accumulator_statistic, class T = time_accumulator_statistic, class M = time_max_statistic> timer cubmonitor::counter_timer_max_statistic< A, T, M >::m_timer private
Definition at line 217 of file monitor_collect.hpp.
Referenced by cubmonitor::counter_timer_max_statistic< A, T, M >::time_and_increment().
template<class A = amount_accumulator_statistic, class T = time_accumulator_statistic, class M = time_max_statistic> T cubmonitor::counter_timer_max_statistic< A, T, M >::m_total_time_statistic private
Definition at line 219 of file monitor_collect.hpp.
Referenced by cubmonitor::counter_timer_max_statistic< A, T, M >::fetch(), cubmonitor::counter_timer_max_statistic< A, T, M >::get_statistics_count(), cubmonitor::counter_timer_max_statistic< A, T, M >::get_time(), and cubmonitor::counter_timer_max_statistic< A, T, M >::time_and_increment().
The documentation for this class was generated from the following file:
src/monitor/monitor_collect.hpp