CUBRID Engine: cubload::driver Class Reference
cubload::driver Class Reference
#include <load_driver.hpp>
Public Member Functions
driver ()
driver (const driver &copy)=delete
driver & operator= (const driver &other)=delete
~driver ()
void initialize (class_installer *cls_installer, object_loader *obj_loader, error_handler *error_handler)
bool is_initialized ()
void clear ()
int parse (std::istream &iss, int line_offset=0)
class_installer & get_class_installer ()
object_loader & get_object_loader ()
semantic_helper & get_semantic_helper ()
error_handler & get_error_handler ()
scanner & get_scanner ()
void update_start_line ()
int get_start_line ()
Private Attributes
scanner * m_scanner
class_installer * m_class_installer
object_loader * m_object_loader
error_handler * m_error_handler
semantic_helper m_semantic_helper
int m_start_line_no
bool m_is_initialized
Detailed Description
Definition at line 64 of file load_driver.hpp.
Constructor & Destructor Documentation
cubload::driver::driver ()
Definition at line 30 of file load_driver.cpp.
cubload::driver::driver (const driver & copy) delete
cubload::driver::~driver ()
Definition at line 59 of file load_driver.cpp.
References clear().
Member Function Documentation
void cubload::driver::clear (void)
Definition at line 42 of file load_driver.cpp.
References m_class_installer, m_error_handler, m_is_initialized, m_object_loader, m_scanner, and NULL.
Referenced by cubload::load_task::execute(), cubload::worker_context_manager::on_retire(), and ~driver().
class_installer & cubload::driver::get_class_installer ()
Definition at line 96 of file load_driver.cpp.
References m_class_installer.
Referenced by cubload::invoke_parser(), ldr_sa_load(), and cubload::session::session().
error_handler & cubload::driver::get_error_handler ()
Definition at line 114 of file load_driver.cpp.
References m_error_handler.
Referenced by cubload::load_task::execute(), and cubload::session::session().
object_loader & cubload::driver::get_object_loader ()
Definition at line 102 of file load_driver.cpp.
References m_object_loader.
Referenced by cubload::load_task::execute(), and cubload::invoke_parser().
scanner & cubload::driver::get_scanner ()
Definition at line 120 of file load_driver.cpp.
References m_scanner.
Referenced by check_commit(), display_error_line(), cubload::load_task::execute(), cubload::server_object_loader::finish_line(), cubload::error_handler::get_scanner_lineno(), and update_start_line().
semantic_helper & cubload::driver::get_semantic_helper ()
Definition at line 108 of file load_driver.cpp.
References m_semantic_helper.
int cubload::driver::get_start_line ()
Definition at line 132 of file load_driver.cpp.
References m_start_line_no.
Referenced by display_error_line(), and cubload::error_handler::get_driver_lineno().
void cubload::driver::initialize (class_installer * cls_installer, object_loader * obj_loader, error_handler * error_handler)
Definition at line 65 of file load_driver.cpp.
References assert, m_class_installer, m_error_handler, m_is_initialized, m_object_loader, m_scanner, and m_semantic_helper.
Referenced by cubload::init_driver(), and ldr_init_driver().
bool cubload::driver::is_initialized ()
Definition at line 77 of file load_driver.cpp.
References m_is_initialized.
Referenced by cubload::load_task::execute(), cubload::init_driver(), and cubload::invoke_parser().
driver& cubload::driver::operator= (const driver & other) delete
int cubload::driver::parse (std::istream & iss, int line_offset = 0)
Definition at line 83 of file load_driver.cpp.
References assert, m_class_installer, m_object_loader, m_scanner, m_semantic_helper, NULL, parser, cubload::semantic_helper::reset_after_batch(), and cubload::scanner::set_lineno().
Referenced by cubload::invoke_parser(), and ldr_sa_load().
void cubload::driver::update_start_line ()
Definition at line 126 of file load_driver.cpp.
References get_scanner(), and m_start_line_no.
Member Data Documentation
class_installer* cubload::driver::m_class_installer private
Definition at line 96 of file load_driver.hpp.
Referenced by clear(), get_class_installer(), initialize(), and parse().
error_handler* cubload::driver::m_error_handler private
Definition at line 98 of file load_driver.hpp.
Referenced by clear(), get_error_handler(), and initialize().
bool cubload::driver::m_is_initialized private
Definition at line 102 of file load_driver.hpp.
Referenced by clear(), initialize(), and is_initialized().
object_loader* cubload::driver::m_object_loader private
Definition at line 97 of file load_driver.hpp.
Referenced by clear(), get_object_loader(), initialize(), and parse().
scanner* cubload::driver::m_scanner private
Definition at line 95 of file load_driver.hpp.
Referenced by clear(), get_scanner(), initialize(), and parse().
semantic_helper cubload::driver::m_semantic_helper private
Definition at line 99 of file load_driver.hpp.
Referenced by get_semantic_helper(), initialize(), and parse().
int cubload::driver::m_start_line_no private
Definition at line 100 of file load_driver.hpp.
Referenced by get_start_line(), and update_start_line().
The documentation for this class was generated from the following files:
src/loaddb/load_driver.hpp
src/loaddb/load_driver.cpp