CUBRID Engine: cubmonitor::atomic_primitive< Rep > Class Template Reference
cubmonitor::atomic_primitive< Rep > Class Template Reference
#include <monitor_statistic.hpp>
Public Types
using rep = Rep
Public Member Functions
atomic_primitive (Rep value=Rep())
atomic_primitive & operator= (const atomic_primitive &other)
void fetch (statistic_value *destination, fetch_mode mode=FETCH_GLOBAL) const
std::size_t get_statistics_count (void) const
Rep get_value (fetch_mode mode=FETCH_GLOBAL) const
Protected Member Functions
void set_value (const Rep &value)
void fetch_add (const Rep &value)
bool compare_exchange (Rep &compare_value, const Rep &replace_value)
Protected Attributes
std::atomic< Rep > m_value
Detailed Description
template<typename Rep>
class cubmonitor::atomic_primitive< Rep >
Definition at line 170 of file monitor_statistic.hpp.
Member Typedef Documentation
template<typename Rep > using cubmonitor::atomic_primitive< Rep >::rep = Rep
Definition at line 173 of file monitor_statistic.hpp.
Constructor & Destructor Documentation
template<typename Rep > cubmonitor::atomic_primitive< Rep >::atomic_primitive (Rep value = Rep ()) inline
Definition at line 175 of file monitor_statistic.hpp.
Member Function Documentation
template<typename Rep > bool cubmonitor::atomic_primitive< Rep >::compare_exchange (Rep & compare_value, const Rep & replace_value) inline protected
Definition at line 210 of file monitor_statistic.hpp.
References cubmonitor::primitive< Rep >::m_value.
template<typename Rep > void cubmonitor::atomic_primitive< Rep >::fetch (statistic_value * destination, fetch_mode mode = FETCH_GLOBAL) const inline
Definition at line 451 of file monitor_statistic.hpp.
References cubmonitor::atomic_primitive< Rep >::fetch_add(), cubmonitor::FETCH_TRANSACTION_SHEET, cubmonitor::primitive< Rep >::get_value(), cubmonitor::primitive< Rep >::m_value, and cubmonitor::statistic_value_cast().
template<typename Rep > void cubmonitor::atomic_primitive< Rep >::fetch_add (const Rep & value) protected
Definition at line 478 of file monitor_statistic.hpp.
References cubmonitor::primitive< Rep >::m_value.
Referenced by cubmonitor::atomic_primitive< Rep >::fetch().
template<typename Rep > std::size_t cubmonitor::atomic_primitive< Rep >::get_statistics_count (void) const inline
Definition at line 189 of file monitor_statistic.hpp.
template<typename Rep > Rep cubmonitor::atomic_primitive< Rep >::get_value (fetch_mode mode = FETCH_GLOBAL) const inline
Definition at line 195 of file monitor_statistic.hpp.
References cubmonitor::primitive< Rep >::m_value.
template<typename Rep > atomic_primitive& cubmonitor::atomic_primitive< Rep >::operator= (const atomic_primitive< Rep > & other) inline
Definition at line 181 of file monitor_statistic.hpp.
References cubmonitor::primitive< Rep >::fetch(), cubmonitor::FETCH_GLOBAL, cubmonitor::primitive< Rep >::m_value, cubmonitor::atomic_primitive< Rep >::m_value, and mode.
template<typename Rep > void cubmonitor::atomic_primitive< Rep >::set_value (const Rep & value) inline protected
Definition at line 202 of file monitor_statistic.hpp.
References cubmonitor::primitive< Rep >::m_value.
Member Data Documentation
template<typename Rep > std::atomic<Rep> cubmonitor::atomic_primitive< Rep >::m_value protected
Definition at line 215 of file monitor_statistic.hpp.
Referenced by cubmonitor::accumulator_atomic_statistic< Rep >::collect(), cubmonitor::atomic_primitive< Rep >::operator=(), and cubmonitor::atomic_primitive< time_rep >::operator=().
The documentation for this class was generated from the following file:
src/monitor/monitor_statistic.hpp