CUBRID Engine: cubmonitor::atomic_primitive< time_rep > Class Template Reference
cubmonitor::atomic_primitive< time_rep > Class Template Reference
#include <monitor_statistic.hpp>
Public Types
using rep = time_rep
Public Member Functions
atomic_primitive (time_rep value=time_rep())
atomic_primitive & operator= (const atomic_primitive &other)
void fetch (statistic_value *destination, fetch_mode mode=FETCH_GLOBAL) const
std::size_t get_statistics_count (void) const
time_rep get_value (fetch_mode mode=FETCH_GLOBAL) const
Protected Member Functions
void set_value (const time_rep &value)
void fetch_add (const time_rep &value)
bool compare_exchange (time_rep &compare_value, const time_rep &replace_value)
Protected Attributes
std::atomic< time_rep::rep > m_value
Detailed Description
template<>
class cubmonitor::atomic_primitive< time_rep >
Definition at line 221 of file monitor_statistic.hpp.
Member Typedef Documentation
using cubmonitor::atomic_primitive< time_rep >::rep = time_rep
Definition at line 224 of file monitor_statistic.hpp.
Constructor & Destructor Documentation
cubmonitor::atomic_primitive< time_rep >::atomic_primitive (time_rep value = time_rep ()) inline
Definition at line 226 of file monitor_statistic.hpp.
Member Function Documentation
bool cubmonitor::atomic_primitive< time_rep >::compare_exchange (time_rep & compare_value, const time_rep & replace_value) inline protected
Definition at line 271 of file monitor_statistic.hpp.
References cubmonitor::primitive< Rep >::m_value.
void cubmonitor::atomic_primitive< time_rep >::fetch (statistic_value * destination, fetch_mode mode = FETCH_GLOBAL) const inline
Definition at line 484 of file monitor_statistic.hpp.
References cubmonitor::FETCH_TRANSACTION_SHEET, cubmonitor::primitive< Rep >::get_value(), and cubmonitor::statistic_value_cast().
void cubmonitor::atomic_primitive< time_rep >::fetch_add (const time_rep & value) inline protected
Definition at line 265 of file monitor_statistic.hpp.
References cubmonitor::primitive< Rep >::m_value.
std::size_t cubmonitor::atomic_primitive< time_rep >::get_statistics_count (void) const inline
Definition at line 240 of file monitor_statistic.hpp.
time_rep cubmonitor::atomic_primitive< time_rep >::get_value (fetch_mode mode = FETCH_GLOBAL) const inline
Definition at line 246 of file monitor_statistic.hpp.
References cubmonitor::FETCH_GLOBAL, cubmonitor::primitive< Rep >::m_value, and mode.
atomic_primitive& cubmonitor::atomic_primitive< time_rep >::operator= (const atomic_primitive< time_rep > & other) inline
Definition at line 232 of file monitor_statistic.hpp.
References cubmonitor::primitive< Rep >::fetch(), cubmonitor::FETCH_GLOBAL, cubmonitor::primitive< Rep >::m_value, cubmonitor::atomic_primitive< Rep >::m_value, and mode.
void cubmonitor::atomic_primitive< time_rep >::set_value (const time_rep & value) inline protected
Definition at line 260 of file monitor_statistic.hpp.
References cubmonitor::primitive< Rep >::m_value.
Member Data Documentation
std::atomic<time_rep::rep> cubmonitor::atomic_primitive< time_rep >::m_value protected
Definition at line 277 of file monitor_statistic.hpp.
The documentation for this class was generated from the following file:
src/monitor/monitor_statistic.hpp