CUBRID Engine: cubmem::appendible_block< Size > Class Template Reference
cubmem::appendible_block< Size > Class Template Reference
#include <extensible_array.hpp>
Public Member Functions
appendible_block ()
appendible_block (const block_allocator &alloc)
void append (const char *source, size_t length)
void copy (const char *source, size_t length)
template<typename T >
void append (const T &obj)
std::size_t get_size () const
Public Member Functions inherited from cubmem::extensible_stack_block< Size >
extensible_stack_block ()
extensible_stack_block (const block_allocator &alloc)
void extend_by (size_t additional_bytes)
void extend_to (size_t total_bytes)
char * get_ptr ()
const char * get_read_ptr () const
Private Types
using base_type = cubmem::extensible_stack_block< Size >
Private Member Functions
void reset ()
Private Attributes
size_t m_size
Detailed Description
template<size_t Size>
class cubmem::appendible_block< Size >
Definition at line 34 of file extensible_array.hpp.
Member Typedef Documentation
template<size_t Size> using cubmem::appendible_block< Size >::base_type = cubmem::extensible_stack_block<Size> private
Definition at line 37 of file extensible_array.hpp.
Constructor & Destructor Documentation
template<size_t Size> cubmem::appendible_block< Size >::appendible_block ()
Definition at line 117 of file extensible_array.hpp.
template<size_t Size> cubmem::appendible_block< Size >::appendible_block (const block_allocator & alloc)
Definition at line 124 of file extensible_array.hpp.
Member Function Documentation
template<size_t Size> void cubmem::appendible_block< Size >::append (const char * source, size_t length) inline
Definition at line 146 of file extensible_array.hpp.
References cubmem::extensible_stack_block< Size >::extend_to(), cubmem::extensible_stack_block< Size >::get_ptr(), and cubmem::appendible_block< Size >::m_size.
Referenced by cubmem::appendible_block< Size >::append(), and cubmem::appendible_block< Size >::copy().
template<size_t Size> template<typename T > void cubmem::appendible_block< Size >::append (const T & obj) inline
Definition at line 156 of file extensible_array.hpp.
References cubmem::appendible_block< Size >::append().
template<size_t Size> void cubmem::appendible_block< Size >::copy (const char * source, size_t length) inline
Definition at line 163 of file extensible_array.hpp.
References cubmem::appendible_block< Size >::append(), and cubmem::appendible_block< Size >::reset().
template<size_t Size> std::size_t cubmem::appendible_block< Size >::get_size () const inline
Definition at line 132 of file extensible_array.hpp.
References cubmem::appendible_block< Size >::m_size.
template<size_t Size> void cubmem::appendible_block< Size >::reset () inline private
Definition at line 139 of file extensible_array.hpp.
References cubmem::appendible_block< Size >::m_size.
Referenced by cubmem::appendible_block< Size >::copy().
Member Data Documentation
template<size_t Size> size_t cubmem::appendible_block< Size >::m_size private
Definition at line 55 of file extensible_array.hpp.
Referenced by cubmem::appendible_block< Size >::append(), cubmem::appendible_block< Size >::get_size(), and cubmem::appendible_block< Size >::reset().
The documentation for this class was generated from the following file:
src/base/extensible_array.hpp