CUBRID Engine: cubmem::reference_store< T > Class Template Reference
cubmem::reference_store< T > Class Template Reference
#include <memory_reference_store.hpp>
Public Member Functions
reference_store ()
reference_store & operator= (reference_store &&)
reference_store (reference_store &)=delete
reference_store & operator= (reference_store &)=delete
const T * get_immutable () const
bool is_null () const
bool is_mutable () const
T * get_mutable () const
T * release_mutable_reference ()
void create_mutable_reference ()
void set_immutable_reference (T *ptr)
void set_mutable_reference (T *ptr)
void clear ()
~reference_store ()
Private Member Functions
void delete_mutable ()
Private Attributes
const T * m_immutable_reference
T * m_mutable_reference
Detailed Description
template<typename T>
class cubmem::reference_store< T >
Definition at line 31 of file memory_reference_store.hpp.
Constructor & Destructor Documentation
template<class T > cubmem::reference_store< T >::reference_store ()
Definition at line 63 of file memory_reference_store.hpp.
template<typename T > cubmem::reference_store< T >::reference_store (reference_store< T > &) delete
template<class T > cubmem::reference_store< T >::~reference_store ()
Definition at line 159 of file memory_reference_store.hpp.
References cubmem::reference_store< T >::clear().
Member Function Documentation
template<class T > void cubmem::reference_store< T >::clear ()
Definition at line 148 of file memory_reference_store.hpp.
References cubmem::reference_store< T >::delete_mutable(), cubmem::reference_store< T >::is_mutable(), cubmem::reference_store< T >::m_immutable_reference, and cubmem::reference_store< T >::m_mutable_reference.
Referenced by cubmem::reference_store< T >::set_immutable_reference(), cubmem::reference_store< T >::set_mutable_reference(), and cubmem::reference_store< T >::~reference_store().
template<typename T > void cubmem::reference_store< T >::create_mutable_reference ()
template<typename T > void cubmem::reference_store< T >::delete_mutable () private
Referenced by cubmem::reference_store< T >::clear().
template<class T > const T * cubmem::reference_store< T >::get_immutable () const
Definition at line 84 of file memory_reference_store.hpp.
References cubmem::reference_store< T >::m_immutable_reference.
template<class T > T * cubmem::reference_store< T >::get_mutable () const
Definition at line 105 of file memory_reference_store.hpp.
References assert, cubmem::reference_store< T >::is_mutable(), and cubmem::reference_store< T >::m_mutable_reference.
template<class T > bool cubmem::reference_store< T >::is_mutable () const
Definition at line 98 of file memory_reference_store.hpp.
References cubmem::reference_store< T >::m_mutable_reference.
Referenced by cubmem::reference_store< T >::clear(), cubmem::reference_store< T >::get_mutable(), and cubmem::reference_store< T >::release_mutable_reference().
template<class T > bool cubmem::reference_store< T >::is_null () const
Definition at line 91 of file memory_reference_store.hpp.
References cubmem::reference_store< T >::m_immutable_reference.
template<class T > reference_store< T > & cubmem::reference_store< T >::operator= (reference_store< T > && other)
Definition at line 72 of file memory_reference_store.hpp.
References cubmem::reference_store< T >::m_immutable_reference, and cubmem::reference_store< T >::m_mutable_reference.
template<typename T > reference_store& cubmem::reference_store< T >::operator= (reference_store< T > &) delete
template<class T > T * cubmem::reference_store< T >::release_mutable_reference ()
Definition at line 113 of file memory_reference_store.hpp.
References assert, cubmem::reference_store< T >::is_mutable(), cubmem::reference_store< T >::m_immutable_reference, and cubmem::reference_store< T >::m_mutable_reference.
template<class T > void cubmem::reference_store< T >::set_immutable_reference (T * ptr)
Definition at line 123 of file memory_reference_store.hpp.
References cubmem::reference_store< T >::clear(), cubmem::reference_store< T >::m_immutable_reference, and cubmem::reference_store< T >::m_mutable_reference.
template<class T > void cubmem::reference_store< T >::set_mutable_reference (T * ptr)
Definition at line 137 of file memory_reference_store.hpp.
References cubmem::reference_store< T >::clear(), cubmem::reference_store< T >::m_immutable_reference, and cubmem::reference_store< T >::m_mutable_reference.
Member Data Documentation
template<typename T > const T* cubmem::reference_store< T >::m_immutable_reference private
Definition at line 55 of file memory_reference_store.hpp.
Referenced by cubmem::reference_store< T >::clear(), cubmem::reference_store< T >::get_immutable(), cubmem::reference_store< T >::is_null(), cubmem::reference_store< T >::operator=(), cubmem::reference_store< T >::release_mutable_reference(), cubmem::reference_store< T >::set_immutable_reference(), and cubmem::reference_store< T >::set_mutable_reference().
template<typename T > T* cubmem::reference_store< T >::m_mutable_reference private
Definition at line 56 of file memory_reference_store.hpp.
Referenced by cubmem::reference_store< T >::clear(), cubmem::reference_store< T >::get_mutable(), cubmem::reference_store< T >::is_mutable(), cubmem::reference_store< T >::operator=(), cubmem::reference_store< T >::release_mutable_reference(), cubmem::reference_store< T >::set_immutable_reference(), and cubmem::reference_store< T >::set_mutable_reference().
The documentation for this class was generated from the following file:
src/base/memory_reference_store.hpp