CUBRID Engine: vacuum_master_task Class Reference
vacuum_master_task Class Reference
Public Member Functions
vacuum_master_task ()=default
void execute (cubthread::entry &thread_ref) final
Public Member Functions inherited from cubthread::task< Context >
task (void)=default
virtual ~task (void)=default
virtual void execute (context_type &)=0
virtual void retire (void)
Private Member Functions
bool check_shutdown () const
bool is_task_queue_full () const
bool should_interrupt_iteration () const
bool is_cursor_entry_ready_to_vacuum () const
bool is_cursor_entry_available () const
void start_job_on_cursor_entry () const
bool should_force_data_update () const
Private Attributes
vacuum_job_cursor m_cursor
MVCCID m_oldest_visible_mvccid
Additional Inherited Members
Public Types inherited from cubthread::task< Context >
using context_type = Context
Detailed Description
Definition at line 801 of file vacuum.c.
Constructor & Destructor Documentation
vacuum_master_task::vacuum_master_task () default
Member Function Documentation
bool vacuum_master_task::check_shutdown () const private
Referenced by vacuum_data_unload_first_and_last_page().
void vacuum_master_task::execute (cubthread::entry & thread_ref) final
Referenced by vacuum_data_unload_first_and_last_page().
bool vacuum_master_task::is_cursor_entry_available () const private
Referenced by vacuum_data_unload_first_and_last_page().
bool vacuum_master_task::is_cursor_entry_ready_to_vacuum () const private
Referenced by vacuum_data_unload_first_and_last_page().
bool vacuum_master_task::is_task_queue_full () const private
Referenced by vacuum_data_unload_first_and_last_page().
bool vacuum_master_task::should_force_data_update () const private
Referenced by vacuum_data_unload_first_and_last_page().
bool vacuum_master_task::should_interrupt_iteration () const private
Referenced by vacuum_data_unload_first_and_last_page().
void vacuum_master_task::start_job_on_cursor_entry () const private
Referenced by vacuum_data_unload_first_and_last_page().
Member Data Documentation
vacuum_job_cursor vacuum_master_task::m_cursor private
Definition at line 817 of file vacuum.c.
MVCCID vacuum_master_task::m_oldest_visible_mvccid private
Definition at line 818 of file vacuum.c.
The documentation for this class was generated from the following file:
src/query/vacuum.c