CUBRID Engine: cubmonitor::primitive< Rep > Class Template Reference
cubmonitor::primitive< Rep > Class Template Reference
#include <monitor_statistic.hpp>
Public Types
using rep = Rep
Public Member Functions
primitive (Rep value=Rep())
primitive & operator= (const primitive &other)
void fetch (statistic_value *destination, fetch_mode mode=FETCH_GLOBAL) const
std::size_t get_statistics_count (void) const
Rep get_value (fetch_mode mode=FETCH_GLOBAL) const
Protected Member Functions
void set_value (const Rep &value)
Protected Attributes
Rep m_value
Detailed Description
template<typename Rep>
class cubmonitor::primitive< Rep >
Definition at line 128 of file monitor_statistic.hpp.
Member Typedef Documentation
template<typename Rep > using cubmonitor::primitive< Rep >::rep = Rep
Definition at line 131 of file monitor_statistic.hpp.
Constructor & Destructor Documentation
template<typename Rep > cubmonitor::primitive< Rep >::primitive (Rep value = Rep ()) inline
Definition at line 133 of file monitor_statistic.hpp.
Member Function Documentation
template<typename Rep > void cubmonitor::primitive< Rep >::fetch (statistic_value * destination, fetch_mode mode = FETCH_GLOBAL) const inline
Definition at line 439 of file monitor_statistic.hpp.
References cubmonitor::FETCH_TRANSACTION_SHEET, cubmonitor::primitive< Rep >::m_value, and cubmonitor::statistic_value_cast().
Referenced by cubmonitor::primitive< Rep >::operator=(), cubmonitor::atomic_primitive< Rep >::operator=(), and cubmonitor::atomic_primitive< time_rep >::operator=().
template<typename Rep > std::size_t cubmonitor::primitive< Rep >::get_statistics_count (void) const inline
Definition at line 147 of file monitor_statistic.hpp.
template<typename Rep > Rep cubmonitor::primitive< Rep >::get_value (fetch_mode mode = FETCH_GLOBAL) const inline
Definition at line 154 of file monitor_statistic.hpp.
References cubmonitor::primitive< Rep >::m_value.
Referenced by cubmonitor::max_statistic< Rep >::collect(), cubmonitor::max_atomic_statistic< Rep >::collect(), cubmonitor::min_statistic< Rep >::collect(), cubmonitor::min_atomic_statistic< Rep >::collect(), cubmonitor::atomic_primitive< Rep >::fetch(), and cubmonitor::atomic_primitive< time_rep >::fetch().
template<typename Rep > primitive& cubmonitor::primitive< Rep >::operator= (const primitive< Rep > & other) inline
Definition at line 139 of file monitor_statistic.hpp.
References cubmonitor::primitive< Rep >::fetch(), cubmonitor::FETCH_GLOBAL, cubmonitor::primitive< Rep >::m_value, and mode.
template<typename Rep > void cubmonitor::primitive< Rep >::set_value (const Rep & value) inline protected
Definition at line 161 of file monitor_statistic.hpp.
References cubmonitor::primitive< Rep >::m_value.
Referenced by cubmonitor::gauge_statistic< Rep >::collect(), cubmonitor::gauge_atomic_statistic< Rep >::collect(), cubmonitor::max_statistic< Rep >::collect(), and cubmonitor::min_statistic< Rep >::collect().
Member Data Documentation
template<typename Rep > Rep cubmonitor::primitive< Rep >::m_value protected
Definition at line 166 of file monitor_statistic.hpp.
Referenced by cubmonitor::accumulator_statistic< Rep >::collect(), cubmonitor::accumulator_atomic_statistic< Rep >::collect(), cubmonitor::atomic_primitive< Rep >::compare_exchange(), cubmonitor::atomic_primitive< time_rep >::compare_exchange(), cubmonitor::primitive< Rep >::fetch(), cubmonitor::atomic_primitive< Rep >::fetch(), cubmonitor::atomic_primitive< Rep >::fetch_add(), cubmonitor::atomic_primitive< time_rep >::fetch_add(), cubmonitor::primitive< Rep >::get_value(), cubmonitor::atomic_primitive< Rep >::get_value(), cubmonitor::atomic_primitive< time_rep >::get_value(), cubmonitor::primitive< Rep >::operator=(), cubmonitor::atomic_primitive< Rep >::operator=(), cubmonitor::atomic_primitive< time_rep >::operator=(), cubmonitor::primitive< Rep >::set_value(), cubmonitor::atomic_primitive< Rep >::set_value(), and cubmonitor::atomic_primitive< time_rep >::set_value().
The documentation for this class was generated from the following file:
src/monitor/monitor_statistic.hpp