CUBRID Engine: cubload::sa_object_loader Class Reference
cubload::sa_object_loader Class Reference
#include <load_sa_loader.hpp>
Public Member Functions
sa_object_loader ()=default
~sa_object_loader () override=default
void init (class_id clsid) override
void destroy () override
void start_line (int object_id) override
void process_line (constant_type *cons) override
void finish_line () override
void flush_records () override
std::size_t get_rows_number () override
Public Member Functions inherited from cubload::object_loader
virtual ~object_loader ()=default
Detailed Description
Definition at line 44 of file load_sa_loader.hpp.
Constructor & Destructor Documentation
cubload::sa_object_loader::sa_object_loader () default
cubload::sa_object_loader::~sa_object_loader () override default
Member Function Documentation
void cubload::sa_object_loader::destroy () override virtual
Implements cubload::object_loader.
Definition at line 755 of file load_sa_loader.cpp.
References display_error(), er_filter_errid(), err, ldr_destroy(), and NO_ERROR.
void cubload::sa_object_loader::finish_line () override virtual
Implements cubload::object_loader.
Definition at line 931 of file load_sa_loader.cpp.
References ldr_context::arg_count, ARG_FILE_LINE, ldr_context::arg_index, ldr_context::attr_type, CHECK_ERR, CHECK_SKIP, ldr_context::cls, ldr_context::constructor, er_errid(), ER_ERROR_SEVERITY, er_filter_errid(), ER_LDR_MISSING_ARGUMENT, ER_LDR_MISSING_ATTRIBUTES, er_set(), err, ldr_context::err_count, ldr_context::flush_interval, insert_instance(), insert_meth_instance(), ldr_context::inst_count, ldr_context::instance_started, ldr_abort(), ldr_assign_all_perm_oids(), cubload::LDR_ATTRIBUTE_ANY, ldr_flush(), ldr_increment_err_count(), ldr_restore_pin_and_drop_obj(), ldr_context::next_attr, NO_ERROR, ldr_context::num_attrs, skip_current_instance, ldr_context::valid, ldr_context::validation_only, and ws_decache_all_instances().
void cubload::sa_object_loader::flush_records () override virtual
Implements cubload::object_loader.
Definition at line 766 of file load_sa_loader.cpp.
std::size_t cubload::sa_object_loader::get_rows_number () override virtual
Implements cubload::object_loader.
Definition at line 772 of file load_sa_loader.cpp.
References assert.
void cubload::sa_object_loader::init (class_id clsid) override virtual
Implements cubload::object_loader.
Definition at line 748 of file load_sa_loader.cpp.
void cubload::sa_object_loader::process_line (constant_type * cons) override virtual
Implements cubload::object_loader.
Definition at line 809 of file load_sa_loader.cpp.
References cubload::monetary_type::amount, ARG_FILE_LINE, CHECK_CONTEXT_VALIDITY, CHECK_SKIP, cubload::monetary_type::currency_type, display_error(), er_errid(), ER_ERROR_SEVERITY, ER_LDR_NO_CLASS_OR_NO_ATTRIBUTE, er_set(), intl_get_money_esc_ISO_symbol(), ldr_abort(), ldr_act, ldr_act_attr(), cubload::LDR_BSTR, cubload::LDR_CLASS_OID, cubload::LDR_COLLECTION, ldr_Current_context, cubload::LDR_DATE, cubload::LDR_DATETIME, cubload::LDR_DATETIMELTZ, cubload::LDR_DATETIMETZ, cubload::LDR_DOUBLE, cubload::LDR_ELO_EXT, cubload::LDR_ELO_INT, cubload::LDR_FLOAT, cubload::LDR_INT, cubload::LDR_MONETARY, cubload::LDR_NSTR, cubload::LDR_NULL, cubload::LDR_NUMERIC, cubload::LDR_OID, ldr_process_object_ref(), cubload::LDR_STR, cubload::LDR_SYS_CLASS, cubload::LDR_SYS_USER, cubload::LDR_TIME, cubload::LDR_TIMESTAMP, cubload::LDR_TIMESTAMPLTZ, cubload::LDR_TIMESTAMPTZ, cubload::LDR_XSTR, NO_ERROR, NULL, ldr_context::num_attrs, NUM_BUF_SIZE, cubload::string_type::size, strlen, cubload::string_type::val, and ldr_context::valid.
void cubload::sa_object_loader::start_line (int object_id) override virtual
Implements cubload::object_loader.
Definition at line 788 of file load_sa_loader.cpp.
References CHECK_SKIP, display_error(), ldr_context::inst_num, ldr_context::instance_started, ldr_reset_context(), NO_ERROR, skip_current_instance, and ldr_context::valid.
The documentation for this class was generated from the following files:
src/loaddb/load_sa_loader.hpp
src/loaddb/load_sa_loader.cpp