CUBRID Engine: cubthread::entry_manager Class Reference
cubthread::entry_manager Class Reference
#include <thread_entry_task.hpp>
Public Member Functions
entry_manager (void)=default
entry & create_context (void) final
void retire_context (entry &context) final
void recycle_context (entry &context) final
void stop_execution (entry &context) override
Public Member Functions inherited from cubthread::context_manager< entry >
virtual ~context_manager ()=default
Protected Member Functions
virtual void on_create (context_type &)
virtual void on_retire (context_type &)
virtual void on_recycle (context_type &)
Additional Inherited Members
Public Types inherited from cubthread::context_manager< entry >
using context_type = entry
Detailed Description
Definition at line 72 of file thread_entry_task.hpp.
Constructor & Destructor Documentation
cubthread::entry_manager::entry_manager (void) default
Member Function Documentation
entry & cubthread::entry_manager::create_context (void) final virtual
Implements cubthread::context_manager< entry >.
Definition at line 37 of file thread_entry_task.cpp.
References cubthread::manager::claim_entry(), cubthread::entry::get_error_context(), cubthread::get_manager(), cubthread::entry::m_status, on_create(), cubthread::entry::register_id(), cuberr::context::register_thread_local(), cubthread::entry::shutdown, cubthread::entry::TS_RUN, TT_WORKER, and cubthread::entry::type.
virtual void cubthread::entry_manager::on_create (context_type &) inline protected virtual
Reimplemented in vacuum_worker_context_manager, index_builder_loader_context, cubthread::daemon_entry_manager, and cubload::worker_context_manager.
Definition at line 84 of file thread_entry_task.hpp.
Referenced by create_context(), and cubthread::daemon_entry_manager::on_daemon_create().
virtual void cubthread::entry_manager::on_recycle (context_type &) inline protected virtual
Reimplemented in vacuum_worker_context_manager, index_builder_loader_context, and cubthread::daemon_entry_manager.
Definition at line 92 of file thread_entry_task.hpp.
Referenced by recycle_context().
virtual void cubthread::entry_manager::on_retire (context_type &) inline protected virtual
Reimplemented in vacuum_worker_context_manager, index_builder_loader_context, cubthread::daemon_entry_manager, and cubload::worker_context_manager.
Definition at line 88 of file thread_entry_task.hpp.
Referenced by cubthread::daemon_entry_manager::on_daemon_retire(), and retire_context().
void cubthread::entry_manager::recycle_context (entry & context) final virtual
Reimplemented from cubthread::context_manager< entry >.
Definition at line 79 of file thread_entry_task.cpp.
References cubthread::entry::end_resource_tracks(), er_clear(), cubthread::entry::event_stats, NULL_TRAN_INDEX, on_recycle(), cubthread::entry::private_lru_index, cubthread::entry::resume_status, cubthread::entry::shutdown, THREAD_RESUME_NONE, and cubthread::entry::tran_index.
void cubthread::entry_manager::retire_context (entry & context) final virtual
Implements cubthread::context_manager< entry >.
Definition at line 56 of file thread_entry_task.cpp.
References cubthread::entry::check_interrupt, cuberr::context::deregister_thread_local(), cubthread::entry::end_resource_tracks(), cubthread::entry::get_error_context(), cubthread::get_manager(), cubthread::entry::m_status, NULL_TRAN_INDEX, on_retire(), cubthread::entry::private_lru_index, cubthread::entry::resume_status, cubthread::manager::retire_entry(), THREAD_RESUME_NONE, cubthread::entry::tran_index, cubthread::entry::TS_FREE, and cubthread::entry::unregister_id().
void cubthread::entry_manager::stop_execution (entry & context) override virtual
Reimplemented from cubthread::context_manager< entry >.
Definition at line 95 of file thread_entry_task.cpp.
References cubthread::entry::shutdown.
The documentation for this class was generated from the following files:
src/thread/thread_entry_task.hpp
src/thread/thread_entry_task.cpp