CUBRID Engine: JSON_ITERATOR Class Reference
JSON_ITERATOR Class Reference abstract
Public Member Functions
JSON_ITERATOR ()
virtual ~JSON_ITERATOR ()
virtual void next ()=0
virtual bool has_next ()=0
virtual const JSON_VALUE * get ()=0
virtual void set (const JSON_DOC &new_doc)=0
const JSON_DOC * get_value_to_doc ()
void reset ()
bool is_empty () const
void clear_content ()
Protected Attributes
const JSON_DOC * m_input_doc
JSON_DOC * m_value_doc
Detailed Description
Definition at line 111 of file db_json.cpp.
Constructor & Destructor Documentation
JSON_ITERATOR::JSON_ITERATOR () inline
Definition at line 115 of file db_json.cpp.
virtual JSON_ITERATOR::~JSON_ITERATOR () inline virtual
Definition at line 121 of file db_json.cpp.
Member Function Documentation
void JSON_ITERATOR::clear_content () inline
Definition at line 167 of file db_json.cpp.
References db_json_delete_doc().
Referenced by db_json_clear_json_iterator().
virtual const JSON_VALUE* JSON_ITERATOR::get () pure virtual
Implemented in JSON_ARRAY_ITERATOR, and JSON_OBJECT_ITERATOR.
const JSON_DOC* JSON_ITERATOR::get_value_to_doc () inline
Definition at line 137 of file db_json.cpp.
References db_json_allocate_doc().
Referenced by db_json_iterator_get_document().
virtual bool JSON_ITERATOR::has_next () pure virtual
Implemented in JSON_ARRAY_ITERATOR, and JSON_OBJECT_ITERATOR.
Referenced by db_json_iterator_has_next().
bool JSON_ITERATOR::is_empty () const inline
Definition at line 161 of file db_json.cpp.
Referenced by db_json_iterator_is_empty().
virtual void JSON_ITERATOR::next () pure virtual
Implemented in JSON_ARRAY_ITERATOR, and JSON_OBJECT_ITERATOR.
Referenced by db_json_iterator_next().
void JSON_ITERATOR::reset (void) inline
Definition at line 156 of file db_json.cpp.
Referenced by db_json_reset_iterator().
virtual void JSON_ITERATOR::set (const JSON_DOC & new_doc) pure virtual
Implemented in JSON_ARRAY_ITERATOR, and JSON_OBJECT_ITERATOR.
Referenced by db_json_set_iterator().
Member Data Documentation
const JSON_DOC* JSON_ITERATOR::m_input_doc protected
Definition at line 176 of file db_json.cpp.
JSON_DOC* JSON_ITERATOR::m_value_doc protected
Definition at line 177 of file db_json.cpp.
The documentation for this class was generated from the following file:
src/compat/db_json.cpp