CUBRID Engine: multi_index_unique_stats Class Reference
multi_index_unique_stats Class Reference
#include <btree_unique.hpp>
Classes
struct btid_comparator
Public Types
using container_type = std::map< BTID, btree_unique_stats, btid_comparator >
Public Member Functions
multi_index_unique_stats ()=default
~multi_index_unique_stats ()=default
void construct ()
void destruct ()
void add_index_stats (const BTID &index, const btree_unique_stats &us)
void add_empty (const BTID &index)
void clear ()
const container_type & get_map () const
bool empty () const
btree_unique_stats & get_stats_of (const BTID &index)
void to_string (string_buffer &strbuf) const
multi_index_unique_stats & operator= (multi_index_unique_stats &&other)
multi_index_unique_stats & operator= (const multi_index_unique_stats &other)=delete
void operator+= (const multi_index_unique_stats &other)
Private Attributes
container_type m_stats_map
Detailed Description
Definition at line 69 of file btree_unique.hpp.
Member Typedef Documentation
using multi_index_unique_stats::container_type = std::map<BTID, btree_unique_stats, btid_comparator>
Definition at line 84 of file btree_unique.hpp.
Constructor & Destructor Documentation
multi_index_unique_stats::multi_index_unique_stats () default
multi_index_unique_stats::~multi_index_unique_stats () default
Member Function Documentation
void multi_index_unique_stats::add_empty (const BTID & index)
Definition at line 163 of file btree_unique.cpp.
References assert, BTID_IS_NULL, and btree_unique_stats::btree_unique_stats().
Referenced by heap_scancache_start_modify().
void multi_index_unique_stats::add_index_stats (const BTID & index, const btree_unique_stats & us)
Definition at line 156 of file btree_unique.cpp.
References assert, and BTID_IS_NULL.
void multi_index_unique_stats::clear (void)
Definition at line 170 of file btree_unique.cpp.
Referenced by locator_force_for_multi_update(), log_abort(), log_commit(), logtb_clear_tdes(), and qexec_clear_internal_classes().
void multi_index_unique_stats::construct ()
Definition at line 144 of file btree_unique.cpp.
Referenced by logtb_initialize_tdes(), and qexec_create_internal_classes().
void multi_index_unique_stats::destruct ()
Definition at line 150 of file btree_unique.cpp.
Referenced by qexec_clear_internal_classes().
bool multi_index_unique_stats::empty () const
Definition at line 182 of file btree_unique.cpp.
Referenced by locator_force_for_multi_update(), and logtb_descriptors_start_scan().
const multi_index_unique_stats::container_type & multi_index_unique_stats::get_map () const
Definition at line 176 of file btree_unique.cpp.
Referenced by locator_force_for_multi_update(), logtb_tran_update_unique_stats(), qexec_execute_insert(), qexec_process_partition_unique_stats(), qexec_process_unique_stats(), and cubload::server_object_loader::stop_scancache().
btree_unique_stats & multi_index_unique_stats::get_stats_of (const BTID & index)
Definition at line 188 of file btree_unique.cpp.
References assert, and BTID_IS_NULL.
Referenced by locator_add_or_remove_index_internal(), and locator_update_index().
void multi_index_unique_stats::operator+= (const multi_index_unique_stats & other)
Definition at line 219 of file btree_unique.cpp.
References m_stats_map.
multi_index_unique_stats & multi_index_unique_stats::operator= (multi_index_unique_stats && other)
Definition at line 212 of file btree_unique.cpp.
multi_index_unique_stats& multi_index_unique_stats::operator= (const multi_index_unique_stats & other) delete
void multi_index_unique_stats::to_string (string_buffer & strbuf) const
Definition at line 195 of file btree_unique.cpp.
Referenced by logtb_descriptors_start_scan().
Member Data Documentation
container_type multi_index_unique_stats::m_stats_map private
Definition at line 105 of file btree_unique.hpp.
Referenced by operator+=().
The documentation for this class was generated from the following files:
src/storage/btree_unique.hpp
src/storage/btree_unique.cpp