CUBRID Engine: JSON_PATH_MAPPER Class Reference
JSON_PATH_MAPPER Class Reference
Public Member Functions
JSON_PATH_MAPPER (map_func_type func)
JSON_PATH_MAPPER (JSON_PATH_MAPPER &)=delete
~JSON_PATH_MAPPER () override=default
Public Member Functions inherited from JSON_WALKER
int WalkDocument (const JSON_DOC &document)
Private Member Functions
int CallBefore (const JSON_VALUE &value) override
int CallAfter (const JSON_VALUE &value) override
int CallOnArrayIterate () override
int CallOnKeyIterate (const JSON_VALUE &key) override
Private Attributes
map_func_type m_producer
std::stack< unsigned int > m_index
JSON_PATH m_current_path
Additional Inherited Members
Protected Member Functions inherited from JSON_WALKER
virtual ~JSON_WALKER ()=default
Protected Attributes inherited from JSON_WALKER
bool m_stop
Detailed Description
Definition at line 452 of file db_json.cpp.
Constructor & Destructor Documentation
JSON_PATH_MAPPER::JSON_PATH_MAPPER (map_func_type func)
Definition at line 714 of file db_json.cpp.
JSON_PATH_MAPPER::JSON_PATH_MAPPER (JSON_PATH_MAPPER &) delete
JSON_PATH_MAPPER::~JSON_PATH_MAPPER () override default
Member Function Documentation
int JSON_PATH_MAPPER::CallAfter (const JSON_VALUE & value) override private virtual
Reimplemented from JSON_WALKER.
Definition at line 740 of file db_json.cpp.
References m_current_path, m_index, m_producer, JSON_WALKER::m_stop, and JSON_PATH::pop().
int JSON_PATH_MAPPER::CallBefore (const JSON_VALUE & value) override private virtual
Reimplemented from JSON_WALKER.
Definition at line 722 of file db_json.cpp.
References m_current_path, m_index, NO_ERROR, and JSON_PATH::push_array_index().
int JSON_PATH_MAPPER::CallOnArrayIterate () override private virtual
Reimplemented from JSON_WALKER.
Definition at line 755 of file db_json.cpp.
References m_current_path, m_index, NO_ERROR, JSON_PATH::pop(), and JSON_PATH::push_array_index().
int JSON_PATH_MAPPER::CallOnKeyIterate (const JSON_VALUE & key) override private virtual
Reimplemented from JSON_WALKER.
Definition at line 766 of file db_json.cpp.
References m_current_path, NO_ERROR, JSON_PATH::pop(), and JSON_PATH::push_object_key().
Member Data Documentation
JSON_PATH JSON_PATH_MAPPER::m_current_path private
Definition at line 467 of file db_json.cpp.
Referenced by CallAfter(), CallBefore(), CallOnArrayIterate(), and CallOnKeyIterate().
std::stack<unsigned int> JSON_PATH_MAPPER::m_index private
Definition at line 466 of file db_json.cpp.
Referenced by CallAfter(), CallBefore(), and CallOnArrayIterate().
map_func_type JSON_PATH_MAPPER::m_producer private
Definition at line 465 of file db_json.cpp.
Referenced by CallAfter().
The documentation for this class was generated from the following file:
src/compat/db_json.cpp