CUBRID Engine: HL::ObstackHeap< ChunkSize, SuperHeap > Class Template Reference
HL::ObstackHeap< ChunkSize, SuperHeap > Class Template Reference
#include <obstackheap.h>
Classes
class ChunkHeader
Public Types
enum { Alignment = sizeof(double) }
Public Member Functions
ObstackHeap ()
~ObstackHeap ()
void reset (const int chkSize)
void * grow (size_t sz)
void * malloc (size_t sz)
void free (void *ptr)
void * getObjectBase ()
void finalize ()
Private Member Functions
int objectSize ()
int isValid ()
ChunkHeader * makeChunk (ChunkHeader *ch, size_t sz)
ChunkHeader * copyToNew (size_t sz)
Private Attributes
int m_chkSize
char * currentBase
char * nextPos
ChunkHeader * currentChunk
Detailed Description
template<int ChunkSize, class SuperHeap>
class HL::ObstackHeap< ChunkSize, SuperHeap >
Definition at line 31 of file obstackheap.h.
Member Enumeration Documentation
template<int ChunkSize, class SuperHeap> anonymous enum
Enumerator
Alignment
Definition at line 38 of file obstackheap.h.
Constructor & Destructor Documentation
template<int ChunkSize, class SuperHeap> HL::ObstackHeap< ChunkSize, SuperHeap >::ObstackHeap () inline
Definition at line 40 of file obstackheap.h.
template<int ChunkSize, class SuperHeap> HL::ObstackHeap< ChunkSize, SuperHeap >::~ObstackHeap () inline
Definition at line 54 of file obstackheap.h.
Member Function Documentation
template<int ChunkSize, class SuperHeap> ChunkHeader* HL::ObstackHeap< ChunkSize, SuperHeap >::copyToNew (size_t sz) inline private
Definition at line 250 of file obstackheap.h.
Referenced by HL::ObstackHeap< 0, MallocHeap >::grow().
template<int ChunkSize, class SuperHeap> void HL::ObstackHeap< ChunkSize, SuperHeap >::finalize () inline
Definition at line 171 of file obstackheap.h.
Referenced by HL::ObstackHeap< 0, MallocHeap >::malloc().
template<int ChunkSize, class SuperHeap> void HL::ObstackHeap< ChunkSize, SuperHeap >::free (void * ptr) inline
Definition at line 136 of file obstackheap.h.
template<int ChunkSize, class SuperHeap> void* HL::ObstackHeap< ChunkSize, SuperHeap >::getObjectBase () inline
Definition at line 165 of file obstackheap.h.
template<int ChunkSize, class SuperHeap> void* HL::ObstackHeap< ChunkSize, SuperHeap >::grow (size_t sz) inline
Definition at line 80 of file obstackheap.h.
template<int ChunkSize, class SuperHeap> int HL::ObstackHeap< ChunkSize, SuperHeap >::isValid () inline private
Definition at line 189 of file obstackheap.h.
Referenced by HL::ObstackHeap< 0, MallocHeap >::finalize(), HL::ObstackHeap< 0, MallocHeap >::free(), HL::ObstackHeap< 0, MallocHeap >::getObjectBase(), HL::ObstackHeap< 0, MallocHeap >::grow(), HL::ObstackHeap< 0, MallocHeap >::malloc(), HL::ObstackHeap< 0, MallocHeap >::ObstackHeap(), HL::ObstackHeap< 0, MallocHeap >::reset(), and HL::ObstackHeap< 0, MallocHeap >::~ObstackHeap().
template<int ChunkSize, class SuperHeap> ChunkHeader* HL::ObstackHeap< ChunkSize, SuperHeap >::makeChunk (ChunkHeader * ch, size_t sz) inline private
Definition at line 233 of file obstackheap.h.
Referenced by HL::ObstackHeap< 0, MallocHeap >::copyToNew(), HL::ObstackHeap< 0, MallocHeap >::free(), HL::ObstackHeap< 0, MallocHeap >::malloc(), HL::ObstackHeap< 0, MallocHeap >::ObstackHeap(), and HL::ObstackHeap< 0, MallocHeap >::reset().
template<int ChunkSize, class SuperHeap> void* HL::ObstackHeap< ChunkSize, SuperHeap >::malloc (size_t sz) inline
Definition at line 106 of file obstackheap.h.
template<int ChunkSize, class SuperHeap> int HL::ObstackHeap< ChunkSize, SuperHeap >::objectSize () inline private
Definition at line 182 of file obstackheap.h.
Referenced by HL::ObstackHeap< 0, MallocHeap >::copyToNew(), and HL::ObstackHeap< 0, MallocHeap >::isValid().
template<int ChunkSize, class SuperHeap> void HL::ObstackHeap< ChunkSize, SuperHeap >::reset (const int chkSize) inline
Definition at line 66 of file obstackheap.h.
Referenced by hl_register_ostk_heap().
Member Data Documentation
template<int ChunkSize, class SuperHeap> char* HL::ObstackHeap< ChunkSize, SuperHeap >::currentBase private
Definition at line 288 of file obstackheap.h.
Referenced by HL::ObstackHeap< 0, MallocHeap >::copyToNew(), HL::ObstackHeap< 0, MallocHeap >::finalize(), HL::ObstackHeap< 0, MallocHeap >::free(), HL::ObstackHeap< 0, MallocHeap >::getObjectBase(), HL::ObstackHeap< 0, MallocHeap >::isValid(), HL::ObstackHeap< 0, MallocHeap >::malloc(), HL::ObstackHeap< 0, MallocHeap >::objectSize(), HL::ObstackHeap< 0, MallocHeap >::ObstackHeap(), and HL::ObstackHeap< 0, MallocHeap >::reset().
template<int ChunkSize, class SuperHeap> ChunkHeader* HL::ObstackHeap< ChunkSize, SuperHeap >::currentChunk private
Definition at line 294 of file obstackheap.h.
Referenced by HL::ObstackHeap< 0, MallocHeap >::copyToNew(), HL::ObstackHeap< 0, MallocHeap >::free(), HL::ObstackHeap< 0, MallocHeap >::grow(), HL::ObstackHeap< 0, MallocHeap >::isValid(), HL::ObstackHeap< 0, MallocHeap >::malloc(), HL::ObstackHeap< 0, MallocHeap >::ObstackHeap(), HL::ObstackHeap< 0, MallocHeap >::reset(), and HL::ObstackHeap< 0, MallocHeap >::~ObstackHeap().
template<int ChunkSize, class SuperHeap> int HL::ObstackHeap< ChunkSize, SuperHeap >::m_chkSize private
Definition at line 34 of file obstackheap.h.
template<int ChunkSize, class SuperHeap> char* HL::ObstackHeap< ChunkSize, SuperHeap >::nextPos private
Definition at line 291 of file obstackheap.h.
Referenced by HL::ObstackHeap< 0, MallocHeap >::copyToNew(), HL::ObstackHeap< 0, MallocHeap >::finalize(), HL::ObstackHeap< 0, MallocHeap >::free(), HL::ObstackHeap< 0, MallocHeap >::grow(), HL::ObstackHeap< 0, MallocHeap >::isValid(), HL::ObstackHeap< 0, MallocHeap >::malloc(), HL::ObstackHeap< 0, MallocHeap >::objectSize(), HL::ObstackHeap< 0, MallocHeap >::ObstackHeap(), and HL::ObstackHeap< 0, MallocHeap >::reset().
The documentation for this class was generated from the following file:
src/heaplayers/heaps/special/obstackheap.h