CUBRID Engine: cubload::object_loader Class Reference
cubload::object_loader Class Reference abstract
#include <load_common.hpp>
Public Member Functions
virtual ~object_loader ()=default
virtual void init (class_id clsid)=0
virtual void destroy ()=0
virtual void start_line (int object_id)=0
virtual void process_line (constant_type *cons)=0
virtual void finish_line ()=0
virtual void flush_records ()=0
virtual std::size_t get_rows_number ()=0
Detailed Description
Definition at line 368 of file load_common.hpp.
Constructor & Destructor Documentation
virtual cubload::object_loader::~object_loader () virtual default
Member Function Documentation
virtual void cubload::object_loader::destroy () pure virtual
Implemented in cubload::server_object_loader, and cubload::sa_object_loader.
Referenced by cubload::invoke_parser().
virtual void cubload::object_loader::finish_line () pure virtual
Implemented in cubload::server_object_loader, and cubload::sa_object_loader.
virtual void cubload::object_loader::flush_records () pure virtual
Implemented in cubload::server_object_loader, and cubload::sa_object_loader.
virtual std::size_t cubload::object_loader::get_rows_number () pure virtual
Implemented in cubload::server_object_loader, and cubload::sa_object_loader.
Referenced by cubload::load_task::execute().
virtual void cubload::object_loader::init (class_id clsid) pure virtual
Implemented in cubload::server_object_loader, and cubload::sa_object_loader.
Referenced by cubload::invoke_parser().
virtual void cubload::object_loader::process_line (constant_type * cons) pure virtual
Implemented in cubload::server_object_loader, and cubload::sa_object_loader.
virtual void cubload::object_loader::start_line (int object_id) pure virtual
Implemented in cubload::server_object_loader, and cubload::sa_object_loader.
The documentation for this class was generated from the following file:
src/loaddb/load_common.hpp