CUBRID Engine: flag< T > Class Template Reference
flag< T > Class Template Reference
#include <base_flag.hpp>
Public Member Functions
flag ()
flag (const flag< T > &other)
flag (const T &init_flags)
flag & operator= (const flag< T > &other)
flag & operator= (const T &flags)
flag & set (const T &flags)
flag & clear (const T &flags)
bool is_set (const T &flags)
bool is_all_set (const T &flags)
bool is_any_set (const T &flags)
T get_flags (void)
Static Public Member Functions
static void set_flag (T &where_to_set, const T &what_to_set)
static void clear_flag (T &where_to_clear, const T &what_to_clear)
static bool is_flag_set (const T &where_to_check, const T &what_to_check)
static bool is_flag_all_set (const T &where_to_check, const T &what_to_check)
static bool is_flag_any_set (const T &where_to_check, const T &what_to_check)
Private Attributes
T m_flags
Detailed Description
template<typename T>
class flag< T >
Definition at line 27 of file base_flag.hpp.
Constructor & Destructor Documentation
template<typename T > flag< T >::flag () inline
Definition at line 56 of file base_flag.hpp.
References flag< T >::m_flags.
template<typename T > flag< T >::flag (const flag< T > & other) inline
Definition at line 62 of file base_flag.hpp.
References flag< T >::m_flags.
template<typename T > flag< T >::flag (const T & init_flags) inline
Definition at line 69 of file base_flag.hpp.
References flag< T >::m_flags.
Member Function Documentation
template<typename T > flag< T > & flag< T >::clear (const T & flags) inline
Definition at line 100 of file base_flag.hpp.
References flag< T >::m_flags.
Referenced by lockfree::circular_queue< T >::unblock().
template<typename T > void flag< T >::clear_flag (T & where_to_clear, const T & what_to_clear) inline static
Definition at line 142 of file base_flag.hpp.
template<typename T > T flag< T >::get_flags (void) inline
Definition at line 128 of file base_flag.hpp.
References flag< T >::m_flags.
Referenced by lockfree::circular_queue< T >::block(), and lockfree::circular_queue< T >::unblock().
template<typename T > bool flag< T >::is_all_set (const T & flags) inline
Definition at line 115 of file base_flag.hpp.
References flag< T >::m_flags.
template<typename T > bool flag< T >::is_any_set (const T & flags) inline
Definition at line 121 of file base_flag.hpp.
References flag< T >::m_flags.
Referenced by flag< T >::is_set().
template<typename T > bool flag< T >::is_flag_all_set (const T & where_to_check, const T & what_to_check) inline static
Definition at line 156 of file base_flag.hpp.
template<typename T > bool flag< T >::is_flag_any_set (const T & where_to_check, const T & what_to_check) inline static
Definition at line 162 of file base_flag.hpp.
Referenced by flag< T >::is_flag_set().
template<typename T > bool flag< T >::is_flag_set (const T & where_to_check, const T & what_to_check) inline static
Definition at line 149 of file base_flag.hpp.
References flag< T >::is_flag_any_set().
Referenced by lockfree::circular_queue< T >::is_blocked(), cubthread::is_logging_configured(), and vacuum_boot().
template<typename T > bool flag< T >::is_set (const T & flags) inline
Definition at line 108 of file base_flag.hpp.
References flag< T >::is_any_set().
Referenced by lockfree::circular_queue< T >::unblock().
template<typename T > flag< T > & flag< T >::operator= (const flag< T > & other) inline
Definition at line 76 of file base_flag.hpp.
References flag< T >::m_flags.
template<typename T > flag< T > & flag< T >::operator= (const T & flags) inline
Definition at line 84 of file base_flag.hpp.
References flag< T >::m_flags.
template<typename T > flag< T > & flag< T >::set (const T & flags) inline
Definition at line 92 of file base_flag.hpp.
References flag< T >::m_flags.
template<typename T > void flag< T >::set_flag (T & where_to_set, const T & what_to_set) inline static
Definition at line 135 of file base_flag.hpp.
Member Data Documentation
template<typename T> T flag< T >::m_flags private
Definition at line 51 of file base_flag.hpp.
Referenced by flag< T >::clear(), flag< T >::flag(), flag< T >::get_flags(), flag< T >::is_all_set(), flag< T >::is_any_set(), flag< T >::operator=(), and flag< T >::set().
The documentation for this class was generated from the following file:
src/base/base_flag.hpp