CUBRID Engine: file_print_output Class Reference
file_print_output Class Reference
#include <printer.hpp>
Public Member Functions
file_print_output (FILE *fp)
~file_print_output ()
int flush (void)
Public Member Functions inherited from print_output
print_output ()
~print_output ()
string_buffer * grab_string_buffer (void)
void operator+= (const char ch)
template<typename... Args>
int operator() (Args &&...args)
Static Public Member Functions
static file_print_output & std_output (void)
Private Attributes
FILE * output_file
Additional Inherited Members
Protected Attributes inherited from print_output
string_buffer m_sb
Detailed Description
Definition at line 72 of file printer.hpp.
Constructor & Destructor Documentation
file_print_output::file_print_output (FILE * fp)
Definition at line 31 of file printer.cpp.
file_print_output::~file_print_output () inline
Definition at line 79 of file printer.hpp.
References print_output::flush().
Member Function Documentation
int file_print_output::flush (void) virtual
Implements print_output.
Definition at line 42 of file printer.cpp.
References string_buffer::clear(), string_buffer::get_buffer(), string_buffer::len(), print_output::m_sb, and output_file.
file_print_output & file_print_output::std_output (void) static
Definition at line 36 of file printer.cpp.
Referenced by db_print().
Member Data Documentation
FILE* file_print_output::output_file private
Definition at line 75 of file printer.hpp.
Referenced by flush().
The documentation for this class was generated from the following files:
src/base/printer.hpp
src/base/printer.cpp