CUBRID Engine: cubbase::pinner Class Reference
cubbase::pinner Class Reference
#include <pinning.hpp>
Public Member Functions
int pin (pinnable *reference)
int unpin (pinnable *reference)
int unpin_all (void)
bool check_references (void)
~pinner ()
Private Attributes
std::set< pinnable * > references
Detailed Description
Definition at line 37 of file pinning.hpp.
Constructor & Destructor Documentation
cubbase::pinner::~pinner () inline
Definition at line 50 of file pinning.hpp.
References assert, and check_references().
Member Function Documentation
bool cubbase::pinner::check_references (void) inline
Definition at line 45 of file pinning.hpp.
References references.
Referenced by ~pinner().
int cubbase::pinner::pin (pinnable * reference)
Definition at line 29 of file pinning.cpp.
References cubbase::pinnable::add_pinner(), NO_ERROR, NULL, and references.
Referenced by cubmem::pinnable_buffer::init().
int cubbase::pinner::unpin (pinnable * reference)
Definition at line 41 of file pinning.cpp.
References NO_ERROR, references, and cubbase::pinnable::remove_pinner().
Referenced by unpin_all().
int cubbase::pinner::unpin_all (void)
Definition at line 52 of file pinning.cpp.
References NO_ERROR, references, and unpin().
Member Data Documentation
std::set<pinnable *> cubbase::pinner::references private
Definition at line 53 of file pinning.hpp.
Referenced by check_references(), pin(), unpin(), and unpin_all().
The documentation for this class was generated from the following files:
src/base/pinning.hpp
src/base/pinning.cpp