CUBRID Engine: cubload::class_installer Class Reference
cubload::class_installer Class Reference abstract
#include <load_common.hpp>
Public Member Functions
virtual ~class_installer ()=default
virtual void set_class_id (class_id clsid)=0
virtual void check_class (const char *class_name, int class_id)=0
virtual int install_class (const char *class_name)=0
virtual void install_class (string_type *class_name, class_command_spec_type *cmd_spec)=0
Detailed Description
Definition at line 309 of file load_common.hpp.
Constructor & Destructor Documentation
virtual cubload::class_installer::~class_installer () virtual default
Member Function Documentation
virtual void cubload::class_installer::check_class (const char * class_name, int class_id) pure virtual
Implemented in cubload::server_class_installer, and cubload::sa_class_installer.
virtual int cubload::class_installer::install_class (const char * class_name) pure virtual
Implemented in cubload::server_class_installer, and cubload::sa_class_installer.
Referenced by ldr_sa_load(), and cubload::session::session().
virtual void cubload::class_installer::install_class (string_type * class_name, class_command_spec_type * cmd_spec) pure virtual
Implemented in cubload::server_class_installer, and cubload::sa_class_installer.
virtual void cubload::class_installer::set_class_id (class_id clsid) pure virtual
Implemented in cubload::server_class_installer, and cubload::sa_class_installer.
Referenced by cubload::invoke_parser(), and cubload::session::session().
The documentation for this class was generated from the following file:
src/loaddb/load_common.hpp