CUBRID Engine: print_output Class Reference
print_output Class Reference abstract
#include <printer.hpp>
Public Member Functions
print_output ()
~print_output ()
virtual int flush (void)=0
string_buffer * grab_string_buffer (void)
void operator+= (const char ch)
template<typename... Args>
int operator() (Args &&...args)
Protected Attributes
string_buffer m_sb
Detailed Description
Definition at line 34 of file printer.hpp.
Constructor & Destructor Documentation
print_output::print_output () inline
Definition at line 40 of file printer.hpp.
print_output::~print_output () inline
Definition at line 42 of file printer.hpp.
References assert, flush(), and string_buffer::len().
Member Function Documentation
virtual int print_output::flush (void) pure virtual
Implemented in string_print_output, and file_print_output.
Referenced by operator()(), operator+=(), file_print_output::~file_print_output(), ~print_output(), and string_print_output::~string_print_output().
string_buffer* print_output::grab_string_buffer (void) inline
Definition at line 49 of file printer.hpp.
References m_sb, operator()(), and operator+=().
Referenced by db_print_value().
template<typename... Args> int print_output::operator() (Args &&... args) inline
Definition at line 60 of file printer.hpp.
References flush(), and m_sb.
Referenced by grab_string_buffer().
void print_output::operator+= (const char ch)
Definition at line 25 of file printer.cpp.
References flush(), and m_sb.
Referenced by grab_string_buffer().
Member Data Documentation
string_buffer print_output::m_sb protected
Definition at line 37 of file printer.hpp.
Referenced by string_print_output::clear(), file_print_output::flush(), string_print_output::flush(), string_print_output::get_buffer(), grab_string_buffer(), operator()(), and operator+=().
The documentation for this class was generated from the following files:
src/base/printer.hpp
src/base/printer.cpp