CUBRID Engine: vacuum_shutdown_sequence Class Reference
vacuum_shutdown_sequence Class Reference
Public Member Functions
vacuum_shutdown_sequence ()
void request_shutdown ()
bool is_shutdown_requested ()
bool check_shutdown_request ()
Private Types
enum state { NO_SHUTDOWN, SHUTDOWN_REGISTERED }
Private Attributes
state m_state
Detailed Description
Definition at line 329 of file vacuum.c.
Member Enumeration Documentation
enum vacuum_shutdown_sequence::state private
Enumerator
NO_SHUTDOWN
SHUTDOWN_REGISTERED
Definition at line 339 of file vacuum.c.
Constructor & Destructor Documentation
vacuum_shutdown_sequence::vacuum_shutdown_sequence ()
Definition at line 8347 of file vacuum.c.
Member Function Documentation
bool vacuum_shutdown_sequence::check_shutdown_request ()
Definition at line 8390 of file vacuum.c.
References assert, m_state, NO_SHUTDOWN, and SHUTDOWN_REGISTERED.
Referenced by vacuum_data_unload_first_and_last_page().
bool vacuum_shutdown_sequence::is_shutdown_requested ()
Definition at line 8384 of file vacuum.c.
References m_state, and NO_SHUTDOWN.
Referenced by vacuum_finished_block_vacuum().
void vacuum_shutdown_sequence::request_shutdown ()
Definition at line 8357 of file vacuum.c.
References assert, m_state, NO_SHUTDOWN, NULL, and SHUTDOWN_REGISTERED.
Referenced by vacuum_notify_server_shutdown().
Member Data Documentation
state vacuum_shutdown_sequence::m_state private
Definition at line 347 of file vacuum.c.
Referenced by check_shutdown_request(), is_shutdown_requested(), and request_shutdown().
The documentation for this class was generated from the following file:
src/query/vacuum.c