CUBRID Engine: cubmonitor::transaction_sheet_manager Class Reference
cubmonitor::transaction_sheet_manager Class Reference
#include <monitor_transaction.hpp>
Static Public Member Functions
static bool start_watch (void)
static void end_watch (bool end_all=false)
static transaction_sheet get_sheet (void)
Static Public Attributes
static const transaction_sheet INVALID_TRANSACTION_SHEET = std::numeric_limits<std::size_t>::max ()
static const std::size_t MAX_SHEETS = 1024
Private Member Functions
transaction_sheet_manager (void)=delete
Static Private Member Functions
static void static_init (void)
Static Private Attributes
static std::size_t s_current_sheet_count = 0
static unsigned s_sheet_start_count [MAX_SHEETS] = { 0 }
static std::size_t s_transaction_count = 0
static transaction_sheet * s_transaction_sheets = NULL
static std::mutex s_sheets_mutex = {}
Detailed Description
Definition at line 54 of file monitor_transaction.hpp.
Constructor & Destructor Documentation
cubmonitor::transaction_sheet_manager::transaction_sheet_manager (void) private delete
Member Function Documentation
void cubmonitor::transaction_sheet_manager::end_watch (bool end_all = false) static
Definition at line 126 of file monitor_transaction.cpp.
References assert, INVALID_TRANSACTION_SHEET, logtb_get_current_tran_index(), s_current_sheet_count, s_sheet_start_count, s_sheets_mutex, s_transaction_count, s_transaction_sheets, and static_init().
transaction_sheet cubmonitor::transaction_sheet_manager::get_sheet (void) static
Definition at line 178 of file monitor_transaction.cpp.
References assert, INVALID_TRANSACTION_SHEET, logtb_get_current_tran_index(), NULL, s_current_sheet_count, s_transaction_count, and s_transaction_sheets.
Referenced by cubmonitor::transaction_statistic< S >::collect(), cubmonitor::transaction_statistic< S >::fetch(), cubmonitor::monitor::fetch_transaction_statistics(), and cubmonitor::transaction_statistic< S >::get_value().
bool cubmonitor::transaction_sheet_manager::start_watch (void) static
Definition at line 69 of file monitor_transaction.cpp.
References assert, INVALID_TRANSACTION_SHEET, logtb_get_current_tran_index(), MAX_SHEETS, s_current_sheet_count, s_sheet_start_count, s_sheets_mutex, s_transaction_count, s_transaction_sheets, and static_init().
void cubmonitor::transaction_sheet_manager::static_init (void) static private
Definition at line 44 of file monitor_transaction.cpp.
References INVALID_TRANSACTION_SHEET, NULL, NUM_NORMAL_TRANS, s_transaction_count, and s_transaction_sheets.
Referenced by end_watch(), and start_watch().
Member Data Documentation
const transaction_sheet cubmonitor::transaction_sheet_manager::INVALID_TRANSACTION_SHEET = std::numeric_limits<std::size_t>::max () static
Definition at line 58 of file monitor_transaction.hpp.
Referenced by cubmonitor::transaction_statistic< S >::collect(), end_watch(), cubmonitor::transaction_statistic< S >::fetch(), cubmonitor::monitor::fetch_transaction_statistics(), get_sheet(), cubmonitor::transaction_statistic< S >::get_value(), start_watch(), and static_init().
const std::size_t cubmonitor::transaction_sheet_manager::MAX_SHEETS = 1024 static
Definition at line 59 of file monitor_transaction.hpp.
Referenced by cubmonitor::transaction_statistic< S >::extend(), and start_watch().
std::size_t cubmonitor::transaction_sheet_manager::s_current_sheet_count = 0 static private
Definition at line 81 of file monitor_transaction.hpp.
Referenced by end_watch(), get_sheet(), and start_watch().
unsigned cubmonitor::transaction_sheet_manager::s_sheet_start_count = { 0 } static private
Definition at line 82 of file monitor_transaction.hpp.
Referenced by end_watch(), and start_watch().
std::mutex cubmonitor::transaction_sheet_manager::s_sheets_mutex = {} static private
Definition at line 87 of file monitor_transaction.hpp.
Referenced by end_watch(), and start_watch().
std::size_t cubmonitor::transaction_sheet_manager::s_transaction_count = 0 static private
Definition at line 84 of file monitor_transaction.hpp.
Referenced by end_watch(), get_sheet(), start_watch(), and static_init().
transaction_sheet * cubmonitor::transaction_sheet_manager::s_transaction_sheets = NULL static private
Definition at line 85 of file monitor_transaction.hpp.
Referenced by end_watch(), get_sheet(), start_watch(), and static_init().
The documentation for this class was generated from the following files:
src/monitor/monitor_transaction.hpp
src/monitor/monitor_transaction.cpp