CUBRID Engine: string_buffer Class Reference
string_buffer Class Reference
#include <string_buffer.hpp>
Public Member Functions
string_buffer ()
~string_buffer ()
string_buffer (const cubmem::block_allocator &alloc)
string_buffer (const cubmem::block_allocator &alloc, size_t initial_size)
const char * get_buffer () const
void clear ()
size_t len () const
char * release_ptr ()
void operator+= (const char ch)
void add_bytes (size_t len, const char *bytes)
template<typename... Args>
int operator() (Args &&...args)
void hex_dump (const string_buffer &in, const size_t max_to_dump, const size_t line_size=16, const bool print_ascii=true)
void hex_dump (const char *ptr, const size_t length, const size_t line_size=16, const bool print_ascii=true)
Private Member Functions
string_buffer (const string_buffer &)=delete
string_buffer (string_buffer &&)=delete
void operator= (const string_buffer &)=delete
void operator= (string_buffer &&)=delete
Private Attributes
size_t m_len
cubmem::extensible_block m_ext_block
Detailed Description
Definition at line 46 of file string_buffer.hpp.
Constructor & Destructor Documentation
string_buffer::string_buffer () inline
Definition at line 49 of file string_buffer.hpp.
Referenced by release_ptr().
string_buffer::~string_buffer () inline
Definition at line 55 of file string_buffer.hpp.
References m_len.
string_buffer::string_buffer (const cubmem::block_allocator & alloc) inline
Definition at line 60 of file string_buffer.hpp.
References m_ext_block.
string_buffer::string_buffer (const cubmem::block_allocator & alloc, size_t initial_size) inline
Definition at line 66 of file string_buffer.hpp.
References cubmem::extensible_block::extend_to(), cubmem::extensible_block::get_ptr(), m_ext_block, and m_len.
string_buffer::string_buffer (const string_buffer &) private delete
string_buffer::string_buffer (string_buffer &&) private delete
Member Function Documentation
void string_buffer::add_bytes (size_t len, const char * bytes)
Definition at line 28 of file string_buffer.cpp.
References assert, cubmem::extensible_block::extend_to(), cubmem::extensible_block::get_ptr(), len(), m_ext_block, m_len, and NULL.
Referenced by db_value_printer::describe_data(), object_printer::describe_domain(), and release_ptr().
void string_buffer::clear (void) inline
Definition at line 78 of file string_buffer.hpp.
References cubmem::extensible_block::get_ptr(), m_ext_block, m_len, and NULL.
Referenced by chksum_print_lower_bound_string(), string_print_output::clear(), object_printer::describe_class(), file_print_output::flush(), object_description::init(), class_description::init(), la_apply_delete_log(), la_apply_insert_log(), la_apply_repl_log(), la_apply_update_log(), la_flush_repl_items(), and sl_write_statement_sql().
const char* string_buffer::get_buffer () const inline
Definition at line 73 of file string_buffer.hpp.
References cubmem::extensible_block::get_read_ptr(), and m_ext_block.
Referenced by chksum_print_lower_bound_string(), db_fprint_value(), db_get_schema_def_dbval(), db_print_value(), db_value_printer::describe_money(), file_print_output::flush(), string_print_output::get_buffer(), func_type::Node::get_types(), heap_classrepr_logging_template(), heap_rv_dump_append_pages_to_heap(), help_print_describe_comment(), hex_dump(), class_description::init(), func_type::Node::invalid_arg_count_error(), func_type::Node::invalid_arg_error(), func_type::Node::invalid_coll_error(), la_apply_delete_log(), la_apply_insert_log(), la_apply_repl_log(), la_apply_update_log(), la_flush_repl_items(), log_repl_data_dump(), pt_arg_type_to_string_buffer(), pt_make_query_show_create_table(), pt_print_db_value(), sl_write_sql(), and sl_write_update_sql().
void string_buffer::hex_dump (const string_buffer & in, const size_t max_to_dump, const size_t line_size = 16, const bool print_ascii = true)
Definition at line 46 of file string_buffer.cpp.
References get_buffer(), len(), and min.
Referenced by release_ptr().
void string_buffer::hex_dump (const char * ptr, const size_t length, const size_t line_size = 16, const bool print_ascii = true)
Definition at line 56 of file string_buffer.cpp.
References i, and operator()().
size_t string_buffer::len () const inline
Definition at line 87 of file string_buffer.hpp.
References m_len.
Referenced by add_bytes(), db_fprint_value(), db_print_value(), file_print_output::flush(), string_print_output::flush(), help_print_describe_comment(), hex_dump(), class_description::init(), operator()(), pt_help_show_create_table(), pt_make_query_show_create_table(), release_ptr(), sl_write_sql(), sl_write_update_sql(), and print_output::~print_output().
template<typename... Args> int string_buffer::operator() (Args &&... args) inline
Definition at line 138 of file string_buffer.hpp.
References assert, cubmem::extensible_block::extend_to(), cubmem::extensible_block::get_ptr(), cubmem::extensible_block::get_size(), len(), m_ext_block, m_len, and NULL.
Referenced by hex_dump(), and release_ptr().
void string_buffer::operator+= (const char ch) inline
Definition at line 120 of file string_buffer.hpp.
References assert, cubmem::extensible_block::extend_to(), cubmem::extensible_block::get_ptr(), cubmem::extensible_block::get_size(), m_ext_block, and m_len.
Referenced by release_ptr().
void string_buffer::operator= (const string_buffer &) private delete
Referenced by release_ptr().
void string_buffer::operator= (string_buffer &&) private delete
char* string_buffer::release_ptr () inline
Definition at line 93 of file string_buffer.hpp.
References add_bytes(), hex_dump(), len(), m_ext_block, operator()(), operator+=(), operator=(), cubmem::extensible_block::release_ptr(), and string_buffer().
Referenced by object_description::init(), logtb_descriptors_start_scan(), and pr_valstring().
Member Data Documentation
cubmem::extensible_block string_buffer::m_ext_block private
Definition at line 115 of file string_buffer.hpp.
Referenced by add_bytes(), clear(), get_buffer(), operator()(), operator+=(), release_ptr(), and string_buffer().
size_t string_buffer::m_len private
Definition at line 114 of file string_buffer.hpp.
Referenced by add_bytes(), clear(), len(), operator()(), operator+=(), string_buffer(), and ~string_buffer().
The documentation for this class was generated from the following files:
src/base/string_buffer.hpp
src/base/string_buffer.cpp