CUBRID Engine: cubbase::pinnable Class Reference
cubbase::pinnable Class Reference
#include <pinning.hpp>
Public Member Functions
int add_pinner (pinner *referencer)
int remove_pinner (pinner *referencer)
int get_pin_count (void)
~pinnable ()
Private Attributes
std::set< pinner * > pinners
Detailed Description
Definition at line 59 of file pinning.hpp.
Constructor & Destructor Documentation
cubbase::pinnable::~pinnable () inline
Definition at line 79 of file pinning.hpp.
References assert.
Member Function Documentation
int cubbase::pinnable::add_pinner (pinner * referencer) inline
Definition at line 62 of file pinning.hpp.
References NO_ERROR.
Referenced by cubbase::pinner::pin().
int cubbase::pinnable::get_pin_count (void) inline
Definition at line 74 of file pinning.hpp.
Referenced by cubmem::pinnable_buffer::~pinnable_buffer().
int cubbase::pinnable::remove_pinner (pinner * referencer) inline
Definition at line 68 of file pinning.hpp.
References NO_ERROR.
Referenced by cubbase::pinner::unpin().
Member Data Documentation
std::set<pinner *> cubbase::pinnable::pinners private
Definition at line 85 of file pinning.hpp.
The documentation for this class was generated from the following file:
src/base/pinning.hpp