CUBRID Engine: vacuum_job_cursor Class Reference
vacuum_job_cursor Class Reference
Public Member Functions
vacuum_job_cursor ()
~vacuum_job_cursor ()
bool is_valid () const
bool is_loaded () const
void increment_blockid ()
void set_on_vacuum_data_start ()
void readjust_to_vacuum_data_changes ()
VACUUM_LOG_BLOCKID get_blockid () const
const VPID & get_page_vpid () const
vacuum_data_page * get_page () const
INT16 get_index () const
const vacuum_data_entry & get_current_entry () const
void start_job_on_current_entry () const
void force_data_update ()
void unload ()
void load ()
Private Member Functions
void change_blockid (VACUUM_LOG_BLOCKID blockid)
void reload ()
void search ()
Private Attributes
VACUUM_LOG_BLOCKID m_blockid
VACUUM_DATA_PAGE * m_page
INT16 m_index
Detailed Description
Definition at line 287 of file vacuum.c.
Constructor & Destructor Documentation
vacuum_job_cursor::vacuum_job_cursor ()
Definition at line 8131 of file vacuum.c.
vacuum_job_cursor::~vacuum_job_cursor ()
Definition at line 8138 of file vacuum.c.
References assert, m_page, and NULL.
Member Function Documentation
void vacuum_job_cursor::change_blockid (VACUUM_LOG_BLOCKID blockid) private
Definition at line 8219 of file vacuum.c.
References assert, vacuum_data::get_first_blockid(), vacuum_data::get_last_blockid(), m_blockid, reload(), and unload().
Referenced by increment_blockid().
void vacuum_job_cursor::force_data_update ()
Definition at line 8210 of file vacuum.c.
References load(), readjust_to_vacuum_data_changes(), unload(), and vacuum_data::update().
Referenced by xvacuum().
VACUUM_LOG_BLOCKID vacuum_job_cursor::get_blockid () const
Definition at line 8158 of file vacuum.c.
References m_blockid.
const vacuum_data_entry & vacuum_job_cursor::get_current_entry () const
Definition at line 8183 of file vacuum.c.
References assert, vacuum_data_page::data, is_valid(), m_index, and m_page.
Referenced by xvacuum().
INT16 vacuum_job_cursor::get_index () const
Definition at line 8177 of file vacuum.c.
References m_index.
vacuum_data_page * vacuum_job_cursor::get_page () const
Definition at line 8170 of file vacuum.c.
References assert, m_page, and NULL.
const VPID & vacuum_job_cursor::get_page_vpid () const
Definition at line 8164 of file vacuum.c.
References m_page, NULL, pgbuf_get_vpid_ptr(), and vpid_Null_vpid.
void vacuum_job_cursor::increment_blockid ()
Definition at line 8241 of file vacuum.c.
References change_blockid(), m_blockid, vacuum_er_log, VACUUM_ER_LOG_JOBS, vacuum_job_cursor_print_args, and vacuum_job_cursor_print_format.
Referenced by xvacuum().
bool vacuum_job_cursor::is_loaded () const
Definition at line 8151 of file vacuum.c.
References assert, vacuum_data_page::is_index_valid(), m_index, m_page, and NULL.
Referenced by is_valid(), load(), and xvacuum().
bool vacuum_job_cursor::is_valid () const
Definition at line 8145 of file vacuum.c.
References is_loaded().
Referenced by get_current_entry(), start_job_on_current_entry(), and xvacuum().
void vacuum_job_cursor::load ()
Definition at line 8285 of file vacuum.c.
References assert, is_loaded(), search(), vacuum_er_log, VACUUM_ER_LOG_JOBS, vacuum_job_cursor_print_args, and vacuum_job_cursor_print_format.
Referenced by force_data_update(), and xvacuum().
void vacuum_job_cursor::readjust_to_vacuum_data_changes ()
Definition at line 8255 of file vacuum.c.
References vacuum_data::get_first_blockid(), vacuum_data::is_empty(), m_blockid, vacuum_er_log, and VACUUM_ER_LOG_JOBS.
Referenced by force_data_update().
void vacuum_job_cursor::reload () private
Definition at line 8294 of file vacuum.c.
References vacuum_data_page::get_index_of_blockid(), vacuum_data_page::INDEX_NOT_FOUND, m_blockid, m_index, m_page, NULL, search(), and unload().
Referenced by change_blockid().
void vacuum_job_cursor::search () private
Definition at line 8316 of file vacuum.c.
References assert, vacuum_data::first_page, cubthread::get_entry(), vacuum_data_page::get_index_of_blockid(), vacuum_data_page::INDEX_NOT_FOUND, m_blockid, m_index, m_page, vacuum_data_page::next_page, NULL, vacuum_fix_data_page, vacuum_unfix_data_page, and VPID_ISNULL.
Referenced by load(), and reload().
void vacuum_job_cursor::set_on_vacuum_data_start ()
Definition at line 8249 of file vacuum.c.
References vacuum_data::get_first_blockid(), and m_blockid.
Referenced by xvacuum().
void vacuum_job_cursor::start_job_on_current_entry () const
Definition at line 8191 of file vacuum.c.
References assert, vacuum_data_page::data, cubthread::get_entry(), is_valid(), log_append_redo_data(), m_index, m_page, NULL, RVVAC_START_JOB, vacuum_data_entry::set_job_in_progress(), vacuum_set_dirty_data_page_dont_free(), and vacuum_data_entry::was_interrupted().
Referenced by xvacuum().
void vacuum_job_cursor::unload ()
Definition at line 8274 of file vacuum.c.
References cubthread::get_entry(), vacuum_data_page::INDEX_NOT_FOUND, m_index, m_page, NULL, vacuum_er_log, VACUUM_ER_LOG_JOBS, vacuum_job_cursor_print_args, vacuum_job_cursor_print_format, and vacuum_unfix_data_page.
Referenced by change_blockid(), force_data_update(), reload(), and xvacuum().
Member Data Documentation
VACUUM_LOG_BLOCKID vacuum_job_cursor::m_blockid private
Definition at line 319 of file vacuum.c.
Referenced by change_blockid(), get_blockid(), increment_blockid(), readjust_to_vacuum_data_changes(), reload(), search(), and set_on_vacuum_data_start().
INT16 vacuum_job_cursor::m_index private
Definition at line 321 of file vacuum.c.
Referenced by get_current_entry(), get_index(), is_loaded(), reload(), search(), start_job_on_current_entry(), and unload().
VACUUM_DATA_PAGE* vacuum_job_cursor::m_page private
Definition at line 320 of file vacuum.c.
Referenced by get_current_entry(), get_page(), get_page_vpid(), is_loaded(), reload(), search(), start_job_on_current_entry(), unload(), and ~vacuum_job_cursor().
The documentation for this class was generated from the following file:
src/query/vacuum.c