CUBRID Engine: lockfree::address_marker< T > Class Template Reference
lockfree::address_marker< T > Class Template Reference
#include <lockfree_address_marker.hpp>
Public Member Functions
address_marker ()
address_marker (T *addr)
bool is_marked () const
T * get_address () const
T * get_address_no_strip () const
Static Public Member Functions
static T * set_adress_mark (T *addr)
static T * strip_address_mark (T *addr)
static bool is_address_marked (T *addr)
static T * atomic_strip_address_mark (T *addr)
Private Types
using convert_type = std::uint64_t
Static Private Member Functions
static convert_type to_cnv_type (T *addr)
static T * to_addr (convert_type ct)
static bool is_ct_marked (convert_type ct)
static convert_type set_ct_mark (convert_type ct)
static convert_type strip_ct_mark (convert_type ct)
Private Attributes
std::atomic< T * > m_addr
Static Private Attributes
static const convert_type MARK = 0x1
Detailed Description
template<class T>
class lockfree::address_marker< T >
Definition at line 32 of file lockfree_address_marker.hpp.
Member Typedef Documentation
template<class T> using lockfree::address_marker< T >::convert_type = std::uint64_t private
Definition at line 35 of file lockfree_address_marker.hpp.
Constructor & Destructor Documentation
template<class T > lockfree::address_marker< T >::address_marker ()
Definition at line 74 of file lockfree_address_marker.hpp.
References NULL.
Referenced by lockfree::address_marker< T >::atomic_strip_address_mark().
template<class T> lockfree::address_marker< T >::address_marker (T * addr)
Definition at line 80 of file lockfree_address_marker.hpp.
Member Function Documentation
template<class T> T * lockfree::address_marker< T >::atomic_strip_address_mark (T * addr) static
Definition at line 164 of file lockfree_address_marker.hpp.
References lockfree::address_marker< T >::address_marker().
Referenced by lockfree::hashmap< Key, T >::iterator::iterate(), lockfree::hashmap< Key, T >::list_delete(), lockfree::hashmap< Key, T >::list_find(), and lockfree::hashmap< Key, T >::list_insert_internal().
template<class T > T * lockfree::address_marker< T >::get_address () const
Definition at line 108 of file lockfree_address_marker.hpp.
References lockfree::address_marker< T >::m_addr, and lockfree::address_marker< T >::strip_address_mark().
template<class T > T * lockfree::address_marker< T >::get_address_no_strip () const
Definition at line 115 of file lockfree_address_marker.hpp.
References lockfree::address_marker< T >::m_addr.
template<class T> bool lockfree::address_marker< T >::is_address_marked (T * addr) static
Definition at line 157 of file lockfree_address_marker.hpp.
References lockfree::address_marker< T >::is_ct_marked(), and lockfree::address_marker< T >::to_cnv_type().
Referenced by lockfree::hashmap< Key, T >::destroy(), lockfree::hashmap< Key, T >::get_ptr(), lockfree::hashmap< Key, T >::get_ref(), lockfree::address_marker< T >::is_marked(), lockfree::hashmap< Key, T >::iterator::iterate(), lockfree::hashmap< Key, T >::list_find(), and lockfree::hashmap< Key, T >::list_insert_internal().
template<class T > bool lockfree::address_marker< T >::is_ct_marked (convert_type ct) static private
Definition at line 122 of file lockfree_address_marker.hpp.
References lockfree::address_marker< T >::MARK.
Referenced by lockfree::address_marker< T >::is_address_marked().
template<class T > bool lockfree::address_marker< T >::is_marked () const
Definition at line 101 of file lockfree_address_marker.hpp.
References lockfree::address_marker< T >::is_address_marked(), and lockfree::address_marker< T >::m_addr.
template<class T> T * lockfree::address_marker< T >::set_adress_mark (T * addr) static
Definition at line 143 of file lockfree_address_marker.hpp.
References lockfree::address_marker< T >::set_ct_mark(), lockfree::address_marker< T >::to_addr(), and lockfree::address_marker< T >::to_cnv_type().
Referenced by lockfree::hashmap< Key, T >::clear(), lockfree::hashmap< Key, T >::init(), and lockfree::hashmap< Key, T >::list_delete().
template<class T > address_marker< T >::convert_type lockfree::address_marker< T >::set_ct_mark (convert_type ct) static private
Definition at line 129 of file lockfree_address_marker.hpp.
References lockfree::address_marker< T >::MARK.
Referenced by lockfree::address_marker< T >::set_adress_mark().
template<class T> T * lockfree::address_marker< T >::strip_address_mark (T * addr) static
Definition at line 150 of file lockfree_address_marker.hpp.
References lockfree::address_marker< T >::strip_ct_mark(), lockfree::address_marker< T >::to_addr(), and lockfree::address_marker< T >::to_cnv_type().
Referenced by lockfree::hashmap< Key, T >::clear(), lockfree::address_marker< T >::get_address(), lockfree::hashmap< Key, T >::iterator::iterate(), lockfree::hashmap< Key, T >::list_delete(), lockfree::hashmap< Key, T >::list_find(), and lockfree::hashmap< Key, T >::list_insert_internal().
template<class T > address_marker< T >::convert_type lockfree::address_marker< T >::strip_ct_mark (convert_type ct) static private
Definition at line 136 of file lockfree_address_marker.hpp.
References lockfree::address_marker< T >::MARK.
Referenced by lockfree::address_marker< T >::strip_address_mark().
template<class T > T * lockfree::address_marker< T >::to_addr (convert_type ct) static private
Definition at line 94 of file lockfree_address_marker.hpp.
Referenced by lockfree::address_marker< T >::set_adress_mark(), and lockfree::address_marker< T >::strip_address_mark().
template<class T> address_marker< T >::convert_type lockfree::address_marker< T >::to_cnv_type (T * addr) static private
Definition at line 87 of file lockfree_address_marker.hpp.
Referenced by lockfree::address_marker< T >::is_address_marked(), lockfree::address_marker< T >::set_adress_mark(), and lockfree::address_marker< T >::strip_address_mark().
Member Data Documentation
template<class T> std::atomic<T *> lockfree::address_marker< T >::m_addr private
Definition at line 60 of file lockfree_address_marker.hpp.
Referenced by lockfree::address_marker< T >::get_address(), lockfree::address_marker< T >::get_address_no_strip(), and lockfree::address_marker< T >::is_marked().
template<class T> const convert_type lockfree::address_marker< T >::MARK = 0x1 static private
Definition at line 36 of file lockfree_address_marker.hpp.
Referenced by lockfree::address_marker< T >::is_ct_marked(), lockfree::address_marker< T >::set_ct_mark(), and lockfree::address_marker< T >::strip_ct_mark().
The documentation for this class was generated from the following file:
src/base/lockfree_address_marker.hpp