CUBRID Engine: log_system_tdes Class Reference
log_system_tdes Class Reference
#include <log_system_tran.hpp>
Public Types
using map_func = std::function< void(log_tdes &)>
using rv_delete_if_func = std::function< bool(const log_tdes &)>
Public Member Functions
log_system_tdes ()
log_system_tdes (log_tdes *tdes)
log_system_tdes (const log_system_tdes &o)=delete
~log_system_tdes ()
log_tdes * get_tdes ()
void on_sysop_start ()
void on_sysop_end ()
Static Public Member Functions
static void init_system_transations ()
static void destroy_system_transactions ()
static log_tdes * rv_get_or_alloc_tdes (TRANID trid)
static log_tdes * rv_get_tdes (TRANID trid)
static void map_all_tdes (const map_func &func)
static void rv_delete_all_tdes_if (const rv_delete_if_func &func)
static void rv_delete_tdes (TRANID trid)
static void rv_simulate_system_tdes (TRANID trid)
static void rv_end_simulation ()
static void rv_final ()
Private Attributes
log_tdes * m_tdes
Detailed Description
Definition at line 33 of file log_system_tran.hpp.
Member Typedef Documentation
using log_system_tdes::map_func = std::function<void (log_tdes &)>
Definition at line 50 of file log_system_tran.hpp.
using log_system_tdes::rv_delete_if_func = std::function<bool (const log_tdes &)>
Definition at line 51 of file log_system_tran.hpp.
Constructor & Destructor Documentation
log_system_tdes::log_system_tdes ()
Definition at line 102 of file log_system_tran.cpp.
References LOG_ISRESTARTED, m_tdes, systdes_claim_tdes(), and systdes_create_tdes().
log_system_tdes::log_system_tdes (log_tdes * tdes)
Definition at line 129 of file log_system_tran.cpp.
log_system_tdes::log_system_tdes (const log_system_tdes & o) delete
log_system_tdes::~log_system_tdes ()
Definition at line 115 of file log_system_tran.cpp.
References LOG_ISRESTARTED, logtb_finalize_tdes(), m_tdes, NULL, and systdes_retire_tdes().
Member Function Documentation
void log_system_tdes::destroy_system_transactions () static
Definition at line 200 of file log_system_tran.cpp.
References assert, logtb_finalize_tdes(), NULL, systb_Free_tdes_list, systb_Mutex, and systb_System_tdes.
Referenced by log_final(), and rv_final().
log_tdes * log_system_tdes::get_tdes ()
Definition at line 136 of file log_system_tran.cpp.
References m_tdes.
void log_system_tdes::init_system_transations () static
Definition at line 194 of file log_system_tran.cpp.
void log_system_tdes::map_all_tdes (const map_func & func) static
Definition at line 250 of file log_system_tran.cpp.
References assert, NULL, systb_Mutex, and systb_System_tdes.
Referenced by log_find_unilaterally_largest_undo_lsa(), log_recovery_abort_all_atomic_sysops(), log_recovery_finish_all_postpone(), and logpb_checkpoint().
void log_system_tdes::on_sysop_end ()
Definition at line 158 of file log_system_tran.cpp.
References assert, log_tdes::head_lsa, log_topops_stack::last, LSA_SET_NULL(), m_tdes, NULL, log_tdes::tail_lsa, log_tdes::tail_topresult_lsa, log_tdes::topops, and log_tdes::undo_nxlsa.
void log_system_tdes::on_sysop_start ()
Definition at line 142 of file log_system_tran.cpp.
References assert, log_tdes::head_lsa, log_topops_stack::last, LSA_SET_NULL(), m_tdes, NULL, log_tdes::rcv, log_rcv_tdes::sysop_start_postpone_lsa, log_tdes::tail_lsa, log_tdes::tail_topresult_lsa, log_tdes::topops, log_rcv_tdes::tran_start_postpone_lsa, and log_tdes::undo_nxlsa.
void log_system_tdes::rv_delete_all_tdes_if (const rv_delete_if_func & func) static
Definition at line 262 of file log_system_tran.cpp.
References systb_System_tdes.
Referenced by log_recovery_undo().
void log_system_tdes::rv_delete_tdes (TRANID trid) static
Definition at line 278 of file log_system_tran.cpp.
References assert, and systb_System_tdes.
Referenced by log_recovery_undo().
void log_system_tdes::rv_end_simulation () static
Definition at line 187 of file log_system_tran.cpp.
References cubthread::get_entry(), and cubthread::entry::reset_system_tdes().
void log_system_tdes::rv_final () static
Definition at line 292 of file log_system_tran.cpp.
References assert, destroy_system_transactions(), and systb_System_tdes.
Referenced by log_recovery().
log_tdes * log_system_tdes::rv_get_or_alloc_tdes (TRANID trid) static
Definition at line 231 of file log_system_tran.cpp.
References assert, NULL, rv_get_tdes(), log_tdes::state, systb_System_tdes, systdes_create_tdes(), TRAN_UNACTIVE_UNILATERALLY_ABORTED, and log_tdes::trid.
Referenced by logtb_rv_find_allocate_tran_index().
log_tdes * log_system_tdes::rv_get_tdes (TRANID trid) static
Definition at line 217 of file log_system_tran.cpp.
References NULL, and systb_System_tdes.
Referenced by log_recovery_undo(), and rv_get_or_alloc_tdes().
void log_system_tdes::rv_simulate_system_tdes (TRANID trid) static
Definition at line 172 of file log_system_tran.cpp.
References assert, cubthread::get_entry(), cubthread::entry::set_system_tdes(), and systb_System_tdes.
Referenced by log_rv_simulate_runtime_worker().
Member Data Documentation
log_tdes* log_system_tdes::m_tdes private
Definition at line 64 of file log_system_tran.hpp.
Referenced by get_tdes(), log_system_tdes(), on_sysop_end(), on_sysop_start(), and ~log_system_tdes().
The documentation for this class was generated from the following files:
src/transaction/log_system_tran.hpp
src/transaction/log_system_tran.cpp