CUBRID Engine: cubthread::worker_pool_task_capper< Context >::capped_task Class Reference
cubthread::worker_pool_task_capper< Context >::capped_task Class Reference
#include <thread_worker_pool_taskcap.hpp>
Public Member Functions
capped_task ()=delete
capped_task (worker_pool_task_capper &capper, task_type *task)
~capped_task ()
void execute (context_type &ctx) override
Public Member Functions inherited from cubthread::task< Context >
task (void)=default
virtual ~task (void)=default
virtual void retire (void)
Private Attributes
worker_pool_task_capper & m_capper
task_type * m_nested_task
Additional Inherited Members
Public Types inherited from cubthread::task< Context >
using context_type = Context
Detailed Description
template<typename Context>
class cubthread::worker_pool_task_capper< Context >::capped_task
Definition at line 62 of file thread_worker_pool_taskcap.hpp.
Constructor & Destructor Documentation
template<typename Context> cubthread::worker_pool_task_capper< Context >::capped_task::capped_task () delete
template<typename Context > cubthread::worker_pool_task_capper< Context >::capped_task::capped_task (worker_pool_task_capper & capper, task_type * task)
Definition at line 155 of file thread_worker_pool_taskcap.hpp.
template<typename Context > cubthread::worker_pool_task_capper< Context >::capped_task::~capped_task ()
Definition at line 162 of file thread_worker_pool_taskcap.hpp.
References cubthread::worker_pool_task_capper< Context >::capped_task::m_nested_task, and cubthread::task< Context >::retire().
Member Function Documentation
template<typename Context > void cubthread::worker_pool_task_capper< Context >::capped_task::execute (context_type & ctx) override virtual
Implements cubthread::task< Context >.
Definition at line 169 of file thread_worker_pool_taskcap.hpp.
References cubthread::worker_pool_task_capper< Context >::end_task(), cubthread::task< Context >::execute(), cubthread::worker_pool_task_capper< Context >::capped_task::m_capper, and cubthread::worker_pool_task_capper< Context >::capped_task::m_nested_task.
Member Data Documentation
template<typename Context> worker_pool_task_capper& cubthread::worker_pool_task_capper< Context >::capped_task::m_capper private
Definition at line 72 of file thread_worker_pool_taskcap.hpp.
Referenced by cubthread::worker_pool_task_capper< Context >::capped_task::execute().
template<typename Context> task_type* cubthread::worker_pool_task_capper< Context >::capped_task::m_nested_task private
Definition at line 73 of file thread_worker_pool_taskcap.hpp.
Referenced by cubthread::worker_pool_task_capper< Context >::capped_task::execute(), and cubthread::worker_pool_task_capper< Context >::capped_task::~capped_task().
The documentation for this class was generated from the following file:
src/thread/thread_worker_pool_taskcap.hpp