CUBRID Engine: tx_transient_class_registry Class Reference
tx_transient_class_registry Class Reference
#include <transaction_transient.hpp>
Public Types
using map_func_type = std::function< void(const tx_transient_class_entry &, bool &)>
Public Member Functions
tx_transient_class_registry ()=default
~tx_transient_class_registry ()=default
bool empty () const
bool has_class (const OID &class_oid) const
void map (const map_func_type &func) const
char * to_string () const
void add (const char *classname, const OID &class_oid, const LOG_LSA &lsa)
void decache_heap_repr (const LOG_LSA &downto_lsa)
void clear ()
Private Types
using list_type = std::forward_list< tx_transient_class_entry >
Private Attributes
list_type m_list
Detailed Description
Definition at line 55 of file transaction_transient.hpp.
Member Typedef Documentation
using tx_transient_class_registry::list_type = std::forward_list<tx_transient_class_entry> private
Definition at line 58 of file transaction_transient.hpp.
using tx_transient_class_registry::map_func_type = std::function<void (const tx_transient_class_entry &, bool &)>
Definition at line 62 of file transaction_transient.hpp.
Constructor & Destructor Documentation
tx_transient_class_registry::tx_transient_class_registry () default
tx_transient_class_registry::~tx_transient_class_registry () default
Member Function Documentation
void tx_transient_class_registry::add (const char * classname, const OID & class_oid, const LOG_LSA & lsa)
Definition at line 54 of file transaction_transient.cpp.
References assert, NULL, OID_EQ, OID_ISNULL, and db_identifier::volid.
Referenced by log_add_to_modified_class_list().
void tx_transient_class_registry::clear (void)
Definition at line 138 of file transaction_transient.cpp.
Referenced by log_cleanup_modified_class_list(), logtb_clear_tdes(), and logtb_set_tdes().
void tx_transient_class_registry::decache_heap_repr (const LOG_LSA & downto_lsa)
Definition at line 125 of file transaction_transient.cpp.
References assert, heap_classrepr_decache(), log_lsa::is_null(), and NULL.
Referenced by log_cleanup_modified_class_list(), and log_sysop_abort().
bool tx_transient_class_registry::empty () const
Definition at line 119 of file transaction_transient.cpp.
Referenced by locator_savepoint_transient_class_name_entries(), and logtb_descriptors_start_scan().
bool tx_transient_class_registry::has_class (const OID & class_oid) const
Definition at line 72 of file transaction_transient.cpp.
References OID_EQ.
Referenced by log_is_class_being_modified().
void tx_transient_class_registry::map (const map_func_type & func) const
Definition at line 105 of file transaction_transient.cpp.
Referenced by locator_drop_transient_class_name_entries(), locator_savepoint_transient_class_name_entries(), and log_cleanup_modified_class_list().
char * tx_transient_class_registry::to_string () const
Definition at line 85 of file transaction_transient.cpp.
References LSA_AS_ARGS, OID_AS_ARGS, and cubmem::PRIVATE_BLOCK_ALLOCATOR.
Referenced by logtb_descriptors_start_scan().
Member Data Documentation
list_type tx_transient_class_registry::m_list private
Definition at line 59 of file transaction_transient.hpp.
The documentation for this class was generated from the following files:
src/transaction/transaction_transient.hpp
src/transaction/transaction_transient.cpp