CUBRID Engine: cubmem::pinnable_buffer Class Reference
cubmem::pinnable_buffer Class Reference
#include <pinnable_buffer.hpp>
Public Member Functions
pinnable_buffer ()
pinnable_buffer (char *ptr, const size_t buf_size)
~pinnable_buffer ()
char * get_buffer (void)
size_t get_buffer_size (void)
int init (char *ptr, const size_t buf_size, cubbase::pinner *referencer)
Public Member Functions inherited from cubbase::pinnable
int add_pinner (pinner *referencer)
int remove_pinner (pinner *referencer)
int get_pin_count (void)
~pinnable ()
Protected Attributes
char * m_storage
char * m_end_ptr
Detailed Description
Definition at line 41 of file pinnable_buffer.hpp.
Constructor & Destructor Documentation
cubmem::pinnable_buffer::pinnable_buffer () inline
Definition at line 44 of file pinnable_buffer.hpp.
References m_end_ptr, m_storage, and NULL.
cubmem::pinnable_buffer::pinnable_buffer (char * ptr, const size_t buf_size) inline
Definition at line 50 of file pinnable_buffer.hpp.
References init(), and NULL.
cubmem::pinnable_buffer::~pinnable_buffer () inline
Definition at line 55 of file pinnable_buffer.hpp.
References assert, and cubbase::pinnable::get_pin_count().
Member Function Documentation
char* cubmem::pinnable_buffer::get_buffer (void) inline
Definition at line 60 of file pinnable_buffer.hpp.
References m_storage.
size_t cubmem::pinnable_buffer::get_buffer_size (void) inline
Definition at line 65 of file pinnable_buffer.hpp.
References init(), m_end_ptr, and m_storage.
int cubmem::pinnable_buffer::init (char * ptr, const size_t buf_size, cubbase::pinner * referencer)
Definition at line 31 of file pinnable_buffer.cpp.
References m_end_ptr, m_storage, NO_ERROR, NULL, and cubbase::pinner::pin().
Referenced by get_buffer_size(), and pinnable_buffer().
Member Data Documentation
char* cubmem::pinnable_buffer::m_end_ptr protected
Definition at line 77 of file pinnable_buffer.hpp.
Referenced by get_buffer_size(), init(), and pinnable_buffer().
char* cubmem::pinnable_buffer::m_storage protected
Definition at line 75 of file pinnable_buffer.hpp.
Referenced by get_buffer(), get_buffer_size(), init(), and pinnable_buffer().
The documentation for this class was generated from the following files:
src/base/pinnable_buffer.hpp
src/base/pinnable_buffer.cpp