CUBRID Engine: cubload::sa_class_installer Class Reference
cubload::sa_class_installer Class Reference
#include <load_sa_loader.hpp>
Public Member Functions
sa_class_installer ()=default
~sa_class_installer () override=default
void set_class_id (class_id clsid) override
void check_class (const char *class_name, int class_id) override
int install_class (const char *class_name) override
void install_class (string_type *class_name, class_command_spec_type *cmd_spec) override
Public Member Functions inherited from cubload::class_installer
virtual ~class_installer ()=default
Detailed Description
Definition at line 31 of file load_sa_loader.hpp.
Constructor & Destructor Documentation
cubload::sa_class_installer::sa_class_installer () default
cubload::sa_class_installer::~sa_class_installer () override default
Member Function Documentation
void cubload::sa_class_installer::check_class (const char * class_name, int class_id) override virtual
Implements cubload::class_installer.
Definition at line 646 of file load_sa_loader.cpp.
References CHECK_CONTEXT_VALIDITY, CHECK_ERR, display_error(), er_clear(), er_errid(), ER_LC_UNKNOWN_CLASSNAME, err, ldr_context::id_class, ldr_context::inst_num, ldr_assign_class_id(), ldr_find_class(), ldr_is_ignore_class(), NO_ERROR, NULL, skip_current_class, strlen, and ldr_context::validation_only.
int cubload::sa_class_installer::install_class (const char * class_name) override virtual
Implements cubload::class_installer.
Definition at line 689 of file load_sa_loader.cpp.
References ldr_act_add_class_all_attrs(), ldr_act_init_context(), and strlen.
void cubload::sa_class_installer::install_class (string_type * class_name, class_command_spec_type * cmd_spec) override virtual
Implements cubload::class_installer.
Definition at line 701 of file load_sa_loader.cpp.
References cubload::constructor_spec_type::arg_list, cubload::class_command_spec_type::attr_list, cubload::class_command_spec_type::attr_type, cubload::class_command_spec_type::ctor_spec, cubload::constructor_spec_type::id_name, ldr_act_add_argument(), ldr_act_add_attr(), ldr_act_check_missing_non_null_attrs(), ldr_act_init_context(), ldr_act_restrict_attributes(), ldr_act_set_constructor(), ldr_act_set_skip_current_class(), cubload::LDR_ATTRIBUTE_ANY, cubload::string_type::next, NULL, cubload::string_type::size, and cubload::string_type::val.
void cubload::sa_class_installer::set_class_id (class_id clsid) override virtual
Implements cubload::class_installer.
Definition at line 639 of file load_sa_loader.cpp.
The documentation for this class was generated from the following files:
src/loaddb/load_sa_loader.hpp
src/loaddb/load_sa_loader.cpp