CUBRID Engine: cubthread::daemon_entry_manager Class Reference
cubthread::daemon_entry_manager Class Reference
#include <thread_entry_task.hpp>
Public Member Functions
daemon_entry_manager ()=default
~daemon_entry_manager ()=default
Public Member Functions inherited from cubthread::entry_manager
entry_manager (void)=default
entry & create_context (void) final
void retire_context (entry &context) final
void recycle_context (entry &context) final
void stop_execution (entry &context) override
Public Member Functions inherited from cubthread::context_manager< entry >
virtual ~context_manager ()=default
Protected Member Functions
virtual void on_daemon_create (entry &)
void on_create (entry &) final
virtual void on_daemon_retire (entry &)
void on_retire (entry &) final
void on_recycle (entry &) final
Additional Inherited Members
Public Types inherited from cubthread::context_manager< entry >
using context_type = entry
Detailed Description
Definition at line 109 of file thread_entry_task.hpp.
Constructor & Destructor Documentation
cubthread::daemon_entry_manager::daemon_entry_manager () default
cubthread::daemon_entry_manager::~daemon_entry_manager () default
Member Function Documentation
void cubthread::daemon_entry_manager::on_create (entry & context) final protected virtual
Reimplemented from cubthread::entry_manager.
Definition at line 101 of file thread_entry_task.cpp.
References LOG_SYSTEM_TRAN_INDEX, cubthread::entry::tran_index, TT_DAEMON, and cubthread::entry::type.
virtual void cubthread::daemon_entry_manager::on_daemon_create (entry &) inline protected virtual
Reimplemented in vacuum_master_context_manager.
Definition at line 116 of file thread_entry_task.hpp.
References cubthread::entry_manager::on_create().
virtual void cubthread::daemon_entry_manager::on_daemon_retire (entry &) inline protected virtual
Reimplemented in vacuum_master_context_manager.
Definition at line 123 of file thread_entry_task.hpp.
References cubthread::entry_manager::on_retire().
void cubthread::daemon_entry_manager::on_recycle (entry &) inline final protected virtual
Reimplemented from cubthread::entry_manager.
Definition at line 130 of file thread_entry_task.hpp.
void cubthread::daemon_entry_manager::on_retire (entry & context) final protected virtual
Reimplemented from cubthread::entry_manager.
Definition at line 110 of file thread_entry_task.cpp.
References cubthread::entry::m_status, cubthread::entry::TS_DEAD, and cubthread::entry::unregister_id().
The documentation for this class was generated from the following files:
src/thread/thread_entry_task.hpp
src/thread/thread_entry_task.cpp