CUBRID Engine: HL::ObstackHeap< ChunkSize, SuperHeap >::ChunkHeader Class Reference
HL::ObstackHeap< ChunkSize, SuperHeap >::ChunkHeader Class Reference
Public Member Functions
ChunkHeader (ChunkHeader *prev, size_t sz)
char * getLimit ()
ChunkHeader * getPrevChunk ()
Private Attributes
char * _pastEnd
ChunkHeader * _prevChunk
Detailed Description
template<int ChunkSize, class SuperHeap>
class HL::ObstackHeap< ChunkSize, SuperHeap >::ChunkHeader
Definition at line 211 of file obstackheap.h.
Constructor & Destructor Documentation
template<int ChunkSize, class SuperHeap> HL::ObstackHeap< ChunkSize, SuperHeap >::ChunkHeader::ChunkHeader (ChunkHeader * prev, size_t sz) inline
Definition at line 213 of file obstackheap.h.
Referenced by HL::ObstackHeap< 0, MallocHeap >::copyToNew(), and HL::ObstackHeap< 0, MallocHeap >::makeChunk().
Member Function Documentation
template<int ChunkSize, class SuperHeap> char* HL::ObstackHeap< ChunkSize, SuperHeap >::ChunkHeader::getLimit () inline
Definition at line 219 of file obstackheap.h.
References HL::ObstackHeap< ChunkSize, SuperHeap >::ChunkHeader::_pastEnd.
Referenced by HL::ObstackHeap< 0, MallocHeap >::free(), HL::ObstackHeap< 0, MallocHeap >::grow(), HL::ObstackHeap< 0, MallocHeap >::isValid(), and HL::ObstackHeap< 0, MallocHeap >::malloc().
template<int ChunkSize, class SuperHeap> ChunkHeader* HL::ObstackHeap< ChunkSize, SuperHeap >::ChunkHeader::getPrevChunk () inline
Definition at line 222 of file obstackheap.h.
References HL::ObstackHeap< ChunkSize, SuperHeap >::ChunkHeader::_prevChunk.
Referenced by HL::ObstackHeap< 0, MallocHeap >::copyToNew(), HL::ObstackHeap< 0, MallocHeap >::free(), HL::ObstackHeap< 0, MallocHeap >::isValid(), and HL::ObstackHeap< 0, MallocHeap >::~ObstackHeap().
Member Data Documentation
template<int ChunkSize, class SuperHeap> char* HL::ObstackHeap< ChunkSize, SuperHeap >::ChunkHeader::_pastEnd private
Definition at line 226 of file obstackheap.h.
Referenced by HL::ObstackHeap< ChunkSize, SuperHeap >::ChunkHeader::getLimit().
template<int ChunkSize, class SuperHeap> ChunkHeader* HL::ObstackHeap< ChunkSize, SuperHeap >::ChunkHeader::_prevChunk private
Definition at line 229 of file obstackheap.h.
Referenced by HL::ObstackHeap< ChunkSize, SuperHeap >::ChunkHeader::getPrevChunk().
The documentation for this class was generated from the following file:
src/heaplayers/heaps/special/obstackheap.h