CUBRID Engine: cubmonitor::timer_statistic< T > Class Template Reference
cubmonitor::timer_statistic< T > Class Template Reference
#include <monitor_collect.hpp>
Classes
class autotimer
Public Member Functions
timer_statistic (void)
void time (const time_rep &d)
void time (void)
void fetch (statistic_value *destination, fetch_mode mode=FETCH_GLOBAL) const
std::size_t get_statistics_count (void) const
time_rep get_time (fetch_mode mode=FETCH_GLOBAL) const
void reset_timer ()
Private Attributes
timer m_timer
T m_statistic
Detailed Description
template<typename T = time_accumulator_statistic>
class cubmonitor::timer_statistic< T >
Definition at line 80 of file monitor_collect.hpp.
Constructor & Destructor Documentation
template<typename T > cubmonitor::timer_statistic< T >::timer_statistic (void)
Definition at line 241 of file monitor_collect.hpp.
Member Function Documentation
template<class T > void cubmonitor::timer_statistic< T >::fetch (statistic_value * destination, fetch_mode mode = FETCH_GLOBAL) const inline
Definition at line 271 of file monitor_collect.hpp.
References cubmonitor::timer_statistic< T >::m_statistic.
template<class T > std::size_t cubmonitor::timer_statistic< T >::get_statistics_count (void) const inline
Definition at line 264 of file monitor_collect.hpp.
References cubmonitor::timer_statistic< T >::m_statistic.
template<class T > time_rep cubmonitor::timer_statistic< T >::get_time (fetch_mode mode = FETCH_GLOBAL) const inline
Definition at line 278 of file monitor_collect.hpp.
References cubmonitor::timer_statistic< T >::m_statistic.
template<class T > void cubmonitor::timer_statistic< T >::reset_timer () inline
Definition at line 285 of file monitor_collect.hpp.
References cubmonitor::timer_statistic< T >::m_timer, and cubmonitor::timer::reset().
Referenced by cubmonitor::timer_statistic< T >::autotimer::autotimer().
template<class T > void cubmonitor::timer_statistic< T >::time (const time_rep & d) inline
Definition at line 250 of file monitor_collect.hpp.
References cubmonitor::timer_statistic< T >::m_statistic.
Referenced by cubmonitor::timer_statistic< T >::autotimer::~autotimer().
template<class T > void cubmonitor::timer_statistic< T >::time (void) inline
Definition at line 257 of file monitor_collect.hpp.
References cubmonitor::timer_statistic< T >::m_statistic, cubmonitor::timer_statistic< T >::m_timer, and cubmonitor::timer::time().
Member Data Documentation
template<typename T = time_accumulator_statistic> T cubmonitor::timer_statistic< T >::m_statistic private
Definition at line 110 of file monitor_collect.hpp.
Referenced by cubmonitor::timer_statistic< T >::fetch(), cubmonitor::timer_statistic< T >::get_statistics_count(), cubmonitor::timer_statistic< T >::get_time(), and cubmonitor::timer_statistic< T >::time().
template<typename T = time_accumulator_statistic> timer cubmonitor::timer_statistic< T >::m_timer private
Definition at line 109 of file monitor_collect.hpp.
Referenced by cubmonitor::timer_statistic< T >::reset_timer(), and cubmonitor::timer_statistic< T >::time().
The documentation for this class was generated from the following file:
src/monitor/monitor_collect.hpp