CUBRID Engine: cubload::batch Class Reference
cubload::batch Class Reference
#include <load_common.hpp>
Public Member Functions
batch ()
batch (batch_id id, class_id clsid, std::string &content, int64_t line_offset, int64_t rows)
batch (batch &&other) noexcept
batch & operator= (batch &&other) noexcept
batch (const batch &copy)=delete
batch & operator= (const batch &copy)=delete
batch_id get_id () const
class_id get_class_id () const
int64_t get_line_offset () const
const std::string & get_content () const
int64_t get_rows_number () const
void pack (cubpacking::packer &serializator) const override
void unpack (cubpacking::unpacker &deserializator) override
size_t get_packed_size (cubpacking::packer &serializator, std::size_t start_offset) const override
Public Member Functions inherited from cubpacking::packable_object
virtual ~packable_object ()
virtual bool is_equal (const packable_object *other)
Private Attributes
batch_id m_id
class_id m_clsid
std::string m_content
int64_t m_line_offset
int64_t m_rows
Detailed Description
Definition at line 47 of file load_common.hpp.
Constructor & Destructor Documentation
cubload::batch::batch ()
Definition at line 61 of file load_common.cpp.
cubload::batch::batch (batch_id id, class_id clsid, std::string & content, int64_t line_offset, int64_t rows)
Definition at line 71 of file load_common.cpp.
cubload::batch::batch (batch && other) noexcept
Definition at line 81 of file load_common.cpp.
cubload::batch::batch (const batch & copy) delete
Member Function Documentation
class_id cubload::batch::get_class_id () const
Definition at line 110 of file load_common.cpp.
References m_clsid.
Referenced by cubload::load_task::execute(), cubload::session::install_class(), and cubload::invoke_parser().
const std::string & cubload::batch::get_content () const
Definition at line 122 of file load_common.cpp.
References m_content.
Referenced by cubload::invoke_parser(), and cubload::session::load_batch().
batch_id cubload::batch::get_id () const
Definition at line 104 of file load_common.cpp.
References m_id.
Referenced by cubload::load_task::execute(), cubload::session::load_batch(), cubload::load_task::notify_done(), and cubload::load_task::notify_done_and_tran_end().
int64_t cubload::batch::get_line_offset () const
Definition at line 116 of file load_common.cpp.
References m_line_offset.
Referenced by cubload::invoke_parser().
size_t cubload::batch::get_packed_size (cubpacking::packer & serializator, std::size_t start_offset) const override virtual
Implements cubpacking::packable_object.
Definition at line 154 of file load_common.cpp.
References cubpacking::packer::get_packed_bigint_size(), cubpacking::packer::get_packed_int_size(), cubpacking::packer::get_packed_string_size(), and m_content.
int64_t cubload::batch::get_rows_number () const
Definition at line 128 of file load_common.cpp.
References m_rows.
batch & cubload::batch::operator= (batch && other) noexcept
Definition at line 92 of file load_common.cpp.
References m_clsid, m_content, m_id, m_line_offset, and m_rows.
batch& cubload::batch::operator= (const batch & copy) delete
void cubload::batch::pack (cubpacking::packer & serializator) const override virtual
Implements cubpacking::packable_object.
Definition at line 134 of file load_common.cpp.
References m_clsid, m_content, m_id, m_line_offset, m_rows, cubpacking::packer::pack_bigint(), cubpacking::packer::pack_int(), and cubpacking::packer::pack_string().
void cubload::batch::unpack (cubpacking::unpacker & deserializator) override virtual
Implements cubpacking::packable_object.
Definition at line 144 of file load_common.cpp.
References m_clsid, m_content, m_id, m_line_offset, m_rows, cubpacking::unpacker::unpack_bigint(), cubpacking::unpacker::unpack_int(), and cubpacking::unpacker::unpack_string().
Referenced by sloaddb_install_class(), and sloaddb_load_batch().
Member Data Documentation
class_id cubload::batch::m_clsid private
Definition at line 71 of file load_common.hpp.
Referenced by get_class_id(), operator=(), pack(), and unpack().
std::string cubload::batch::m_content private
Definition at line 72 of file load_common.hpp.
Referenced by get_content(), get_packed_size(), operator=(), pack(), and unpack().
batch_id cubload::batch::m_id private
Definition at line 70 of file load_common.hpp.
Referenced by get_id(), operator=(), pack(), and unpack().
int64_t cubload::batch::m_line_offset private
Definition at line 73 of file load_common.hpp.
Referenced by get_line_offset(), operator=(), pack(), and unpack().
int64_t cubload::batch::m_rows private
Definition at line 74 of file load_common.hpp.
Referenced by get_rows_number(), operator=(), pack(), and unpack().
The documentation for this class was generated from the following files:
src/loaddb/load_common.hpp
src/loaddb/load_common.cpp