CUBRID Engine: cubmem::private_allocator< T > Class Template Reference
cubmem::private_allocator< T > Class Template Reference
#include <memory_private_allocator.hpp>
Classes
struct rebind
Public Types
typedef T value_type
typedef value_type * pointer
typedef const value_type * const_pointer
typedef value_type & reference
typedef const value_type & const_reference
typedef size_t size_type
typedef ptrdiff_t difference_type
Public Member Functions
private_allocator (cubthread::entry *thread_p=NULL)
~private_allocator ()
private_allocator (const private_allocator &other)
template<typename U >
private_allocator (const private_allocator< U > &other)
pointer address (reference r)
const_pointer address (const_reference r)
pointer allocate (size_type count)
void deallocate (pointer p, size_type ignored=0)
size_type max_size () const
void construct (pointer p, const_reference t)
void destroy (pointer p)
cubthread::entry * get_thread_entry () const
HL_HEAPID get_heapid () const
Private Attributes
cubthread::entry * m_thread_p
HL_HEAPID m_heapid
Detailed Description
template<typename T>
class cubmem::private_allocator< T >
Definition at line 58 of file memory_private_allocator.hpp.
Member Typedef Documentation
template<typename T> typedef const value_type* cubmem::private_allocator< T >::const_pointer
Definition at line 64 of file memory_private_allocator.hpp.
template<typename T> typedef const value_type& cubmem::private_allocator< T >::const_reference
Definition at line 66 of file memory_private_allocator.hpp.
template<typename T> typedef ptrdiff_t cubmem::private_allocator< T >::difference_type
Definition at line 68 of file memory_private_allocator.hpp.
template<typename T> typedef value_type* cubmem::private_allocator< T >::pointer
Definition at line 63 of file memory_private_allocator.hpp.
template<typename T> typedef value_type& cubmem::private_allocator< T >::reference
Definition at line 65 of file memory_private_allocator.hpp.
template<typename T> typedef size_t cubmem::private_allocator< T >::size_type
Definition at line 67 of file memory_private_allocator.hpp.
template<typename T> typedef T cubmem::private_allocator< T >::value_type
Definition at line 62 of file memory_private_allocator.hpp.
Constructor & Destructor Documentation
template<typename T > cubmem::private_allocator< T >::private_allocator (cubthread::entry * thread_p = NULL) inline explicit
Definition at line 193 of file memory_private_allocator.hpp.
References cubmem::get_private_heapid(), cubmem::private_allocator< T >::m_heapid, cubmem::private_allocator< T >::m_thread_p, and cubmem::register_private_allocator().
template<typename T > cubmem::private_allocator< T >::~private_allocator () inline
Definition at line 218 of file memory_private_allocator.hpp.
References cubmem::deregister_private_allocator(), and cubmem::private_allocator< T >::m_thread_p.
template<typename T > cubmem::private_allocator< T >::private_allocator (const private_allocator< T > & other) inline explicit
Definition at line 201 of file memory_private_allocator.hpp.
References cubmem::private_allocator< T >::m_heapid, cubmem::private_allocator< T >::m_thread_p, and cubmem::register_private_allocator().
template<typename T > template<typename U > cubmem::private_allocator< T >::private_allocator (const private_allocator< U > & other) inline explicit
Definition at line 210 of file memory_private_allocator.hpp.
References cubmem::private_allocator< T >::get_heapid(), cubmem::private_allocator< T >::get_thread_entry(), cubmem::private_allocator< T >::m_heapid, cubmem::private_allocator< T >::m_thread_p, and cubmem::register_private_allocator().
Member Function Documentation
template<typename T> pointer cubmem::private_allocator< T >::address (reference r) inline
Definition at line 84 of file memory_private_allocator.hpp.
template<typename T> const_pointer cubmem::private_allocator< T >::address (const_reference r) inline
Definition at line 88 of file memory_private_allocator.hpp.
References cubregex::count(), and p.
template<typename T > private_allocator< T >::pointer cubmem::private_allocator< T >::allocate (size_type count) inline
Definition at line 225 of file memory_private_allocator.hpp.
References cubmem::private_allocator< T >::m_heapid, cubmem::private_allocator< T >::m_thread_p, and cubmem::private_heap_allocate().
template<typename T > void cubmem::private_allocator< T >::construct (pointer p, const_reference t) inline
Definition at line 248 of file memory_private_allocator.hpp.
References p.
template<typename T > void cubmem::private_allocator< T >::deallocate (pointer p, size_type ignored = 0) inline
Definition at line 232 of file memory_private_allocator.hpp.
References cubmem::private_allocator< T >::m_heapid, cubmem::private_allocator< T >::m_thread_p, and cubmem::private_heap_deallocate().
template<typename T > void cubmem::private_allocator< T >::destroy (pointer p) inline
Definition at line 255 of file memory_private_allocator.hpp.
template<typename T > HL_HEAPID cubmem::private_allocator< T >::get_heapid () const
Definition at line 269 of file memory_private_allocator.hpp.
References cubmem::private_allocator< T >::m_heapid.
Referenced by cubmem::private_allocator< T >::private_allocator().
template<typename T > cubthread::entry * cubmem::private_allocator< T >::get_thread_entry () const
Definition at line 262 of file memory_private_allocator.hpp.
References cubmem::private_allocator< T >::m_thread_p.
Referenced by cubmem::private_allocator< T >::private_allocator().
template<typename T > private_allocator< T >::size_type cubmem::private_allocator< T >::max_size () const
Definition at line 240 of file memory_private_allocator.hpp.
Member Data Documentation
template<typename T> HL_HEAPID cubmem::private_allocator< T >::m_heapid private
Definition at line 111 of file memory_private_allocator.hpp.
Referenced by cubmem::private_allocator< T >::allocate(), cubmem::private_allocator< T >::deallocate(), cubmem::private_allocator< T >::get_heapid(), and cubmem::private_allocator< T >::private_allocator().
template<typename T> cubthread::entry* cubmem::private_allocator< T >::m_thread_p private
Definition at line 110 of file memory_private_allocator.hpp.
Referenced by cubmem::private_allocator< T >::allocate(), cubmem::private_allocator< T >::deallocate(), cubmem::private_allocator< T >::get_thread_entry(), cubmem::private_allocator< T >::private_allocator(), and cubmem::private_allocator< T >::~private_allocator().
The documentation for this class was generated from the following file:
src/base/memory_private_allocator.hpp