CUBRID Engine: cubload::attribute Class Reference
cubload::attribute Class Reference
#include <load_class_registry.hpp>
Public Member Functions
attribute ()=delete
attribute (const std::string &name, std::size_t index, or_attribute *repr)
attribute (attribute &&other)=delete
attribute (const attribute &copy)=delete
attribute & operator= (attribute &&other)=delete
attribute & operator= (const attribute &copy)=delete
const char * get_name () const
std::size_t get_index () const
const or_attribute & get_repr () const
const tp_domain & get_domain () const
Private Attributes
const std::string m_name
const std::size_t m_index
const or_attribute * m_repr
Detailed Description
Definition at line 37 of file load_class_registry.hpp.
Constructor & Destructor Documentation
cubload::attribute::attribute () delete
cubload::attribute::attribute (const std::string & name, std::size_t index, or_attribute * repr)
Definition at line 31 of file load_class_registry.cpp.
cubload::attribute::attribute (attribute && other) delete
cubload::attribute::attribute (const attribute & copy) delete
Member Function Documentation
const tp_domain & cubload::attribute::get_domain () const
Definition at line 58 of file load_class_registry.cpp.
References or_attribute::domain, and m_repr.
Referenced by cubload::server_object_loader::process_collection_constant(), cubload::server_object_loader::process_generic_constant(), cubload::server_object_loader::process_monetary_constant(), cubload::to_db_double(), cubload::to_db_float(), cubload::to_db_generic_char(), cubload::to_db_varbit_from_bin_str(), and cubload::to_db_varbit_from_hex_str().
std::size_t cubload::attribute::get_index () const
Definition at line 46 of file load_class_registry.cpp.
References m_index.
Referenced by cubload::server_object_loader::process_collection_constant(), cubload::server_object_loader::process_generic_constant(), cubload::server_object_loader::process_monetary_constant(), and cubload::server_class_installer::register_class_with_attributes().
const char * cubload::attribute::get_name (void) const
Definition at line 40 of file load_class_registry.cpp.
References m_name.
Referenced by cubload::mismatch(), cubload::server_object_loader::process_collection_constant(), cubload::server_object_loader::process_generic_constant(), cubload::server_object_loader::process_monetary_constant(), cubload::to_db_varbit_from_bin_str(), and cubload::to_db_varbit_from_hex_str().
const or_attribute & cubload::attribute::get_repr () const
Definition at line 52 of file load_class_registry.cpp.
References m_repr.
Referenced by cubload::server_object_loader::process_line(), and cubload::to_db_null().
attribute& cubload::attribute::operator= (attribute && other) delete
attribute& cubload::attribute::operator= (const attribute & copy) delete
Member Data Documentation
const std::size_t cubload::attribute::m_index private
Definition at line 56 of file load_class_registry.hpp.
Referenced by get_index().
const std::string cubload::attribute::m_name private
Definition at line 55 of file load_class_registry.hpp.
Referenced by get_name().
const or_attribute* cubload::attribute::m_repr private
Definition at line 57 of file load_class_registry.hpp.
Referenced by get_domain(), and get_repr().
The documentation for this class was generated from the following files:
src/loaddb/load_class_registry.hpp
src/loaddb/load_class_registry.cpp