CUBRID Engine: cubload::load_status Class Reference
cubload::load_status Class Reference
#include <load_common.hpp>
Public Member Functions
load_status ()
load_status (bool is_load_completed, bool is_session_failed, std::vector< stats > &load_stats)
load_status (load_status &&other) noexcept
load_status & operator= (load_status &&other) noexcept
load_status (const load_status &copy)=delete
load_status & operator= (const load_status &copy)=delete
bool is_load_completed ()
bool is_load_failed ()
std::vector< stats > & get_load_stats ()
void pack (cubpacking::packer &serializator) const override
void unpack (cubpacking::unpacker &deserializator) override
size_t get_packed_size (cubpacking::packer &serializator, std::size_t start_offset) const override
Public Member Functions inherited from cubpacking::packable_object
virtual ~packable_object ()
virtual bool is_equal (const packable_object *other)
Private Attributes
bool m_load_completed
bool m_load_failed
std::vector< stats > m_load_stats
Detailed Description
Definition at line 276 of file load_common.hpp.
Constructor & Destructor Documentation
cubload::load_status::load_status ()
Definition at line 529 of file load_common.cpp.
cubload::load_status::load_status (bool is_load_completed, bool is_session_failed, std::vector< stats > & load_stats)
Definition at line 536 of file load_common.cpp.
cubload::load_status::load_status (load_status && other) noexcept
Definition at line 543 of file load_common.cpp.
cubload::load_status::load_status (const load_status & copy) delete
Member Function Documentation
std::vector< stats > & cubload::load_status::get_load_stats ()
Definition at line 573 of file load_common.cpp.
References m_load_stats.
Referenced by ldr_server_load(), and load_object_file().
size_t cubload::load_status::get_packed_size (cubpacking::packer & serializator, std::size_t start_offset) const override virtual
Implements cubpacking::packable_object.
Definition at line 608 of file load_common.cpp.
References cubpacking::packer::get_packed_bigint_size(), cubpacking::packer::get_packed_bool_size(), and m_load_stats.
bool cubload::load_status::is_load_completed ()
Definition at line 561 of file load_common.cpp.
References m_load_completed.
Referenced by ldr_server_load().
bool cubload::load_status::is_load_failed ()
Definition at line 567 of file load_common.cpp.
References m_load_failed.
Referenced by ldr_server_load().
load_status & cubload::load_status::operator= (load_status && other) noexcept
Definition at line 551 of file load_common.cpp.
References m_load_completed, m_load_failed, and m_load_stats.
load_status& cubload::load_status::operator= (const load_status & copy) delete
void cubload::load_status::pack (cubpacking::packer & serializator) const override virtual
Implements cubpacking::packable_object.
Definition at line 579 of file load_common.cpp.
References m_load_completed, m_load_failed, m_load_stats, cubpacking::packer::pack_bigint(), and cubpacking::packer::pack_bool().
void cubload::load_status::unpack (cubpacking::unpacker & deserializator) override virtual
Implements cubpacking::packable_object.
Definition at line 592 of file load_common.cpp.
References i, m_load_completed, m_load_failed, m_load_stats, cubpacking::unpacker::unpack_bigint(), and cubpacking::unpacker::unpack_bool().
Referenced by loaddb_fetch_status(), and loaddb_load_batch().
Member Data Documentation
bool cubload::load_status::m_load_completed private
Definition at line 297 of file load_common.hpp.
Referenced by is_load_completed(), operator=(), pack(), and unpack().
bool cubload::load_status::m_load_failed private
Definition at line 298 of file load_common.hpp.
Referenced by is_load_failed(), operator=(), pack(), and unpack().
std::vector<stats> cubload::load_status::m_load_stats private
Definition at line 299 of file load_common.hpp.
Referenced by get_load_stats(), get_packed_size(), operator=(), pack(), and unpack().
The documentation for this class was generated from the following files:
src/loaddb/load_common.hpp
src/loaddb/load_common.cpp