CUBRID Engine: cubmonitor::timer Class Reference
cubmonitor::timer Class Reference
#include <monitor_collect.hpp>
Public Member Functions
timer (void)
void reset (void)
duration time (void)
Private Attributes
time_point m_timept
Detailed Description
Definition at line 37 of file monitor_collect.hpp.
Constructor & Destructor Documentation
cubmonitor::timer::timer (void) inline
Definition at line 545 of file monitor_collect.hpp.
Member Function Documentation
void cubmonitor::timer::reset (void) inline
Definition at line 552 of file monitor_collect.hpp.
References m_timept.
Referenced by cubmonitor::timer_statistic< T >::reset_timer(), and cubmonitor::counter_timer_statistic< A, T >::reset_timer().
duration cubmonitor::timer::time (void) inline
Definition at line 558 of file monitor_collect.hpp.
References m_timept.
Referenced by cubmonitor::timer_statistic< T >::time(), cubmonitor::counter_timer_statistic< A, T >::time_and_increment(), and cubmonitor::counter_timer_max_statistic< A, T, M >::time_and_increment().
Member Data Documentation
time_point cubmonitor::timer::m_timept private
Definition at line 46 of file monitor_collect.hpp.
Referenced by reset(), and time().
The documentation for this class was generated from the following file:
src/monitor/monitor_collect.hpp