CUBRID Engine: cubthread::task< Context > Class Template Reference
cubthread::task< Context > Class Template Reference abstract
#include <thread_task.hpp>
Public Types
using context_type = Context
Public Member Functions
task (void)=default
virtual ~task (void)=default
virtual void execute (context_type &)=0
virtual void retire (void)
Detailed Description
template<typename Context>
class cubthread::task< Context >
Definition at line 61 of file thread_task.hpp.
Member Typedef Documentation
template<typename Context> using cubthread::task< Context >::context_type = Context
Definition at line 64 of file thread_task.hpp.
Constructor & Destructor Documentation
template<typename Context> cubthread::task< Context >::task (void) default
template<typename Context> virtual cubthread::task< Context >::~task (void) virtual default
Member Function Documentation
template<typename Context> virtual void cubthread::task< Context >::execute (context_type &) pure virtual
Implemented in css_connection_task, css_server_external_task, css_server_task, cubthread::callable_task< Context >, and cubthread::worker_pool_task_capper< Context >::capped_task.
Referenced by cubthread::worker_pool_task_capper< Context >::capped_task::execute(), cubthread::worker_pool< Context >::core::worker::execute_current_task(), cubthread::daemon::loop_with_context(), cubthread::manager::push_task(), cubthread::manager::push_task_on_core(), and cubthread::manager::try_task().
template<typename Context> virtual void cubthread::task< Context >::retire (void) inline virtual
Reimplemented in cubthread::callable_task< Context >.
Definition at line 75 of file thread_task.hpp.
Referenced by cubthread::worker_pool< Context >::core::execute_task(), cubthread::daemon::loop_with_context(), cubthread::manager::push_task(), cubthread::manager::push_task_on_core(), cubthread::worker_pool< Context >::core::worker::retire_current_task(), cubthread::manager::try_task(), and cubthread::worker_pool_task_capper< Context >::capped_task::~capped_task().
The documentation for this class was generated from the following file:
src/thread/thread_task.hpp