CUBRID Engine: cubload::class_entry Class Reference
cubload::class_entry Class Reference
#include <load_class_registry.hpp>
Public Member Functions
class_entry ()=delete
class_entry (std::string &class_name, OID &class_oid, class_id clsid, std::vector< const attribute * > &attributes)
class_entry (std::string &class_name, class_id clsid, bool is_ignored)
~class_entry ()
class_entry (class_entry &&other)=delete
class_entry (const class_entry &copy)=delete
class_entry & operator= (class_entry &&other)=delete
class_entry & operator= (const class_entry &copy)=delete
const OID & get_class_oid () const
const char * get_class_name () const
const attribute & get_attribute (std::size_t index) const
size_t get_attributes_size () const
bool is_ignored () const
Private Attributes
class_id m_clsid
OID m_class_oid
std::string m_class_name
std::vector< const attribute * > m_attributes
const bool m_is_ignored
Detailed Description
Definition at line 60 of file load_class_registry.hpp.
Constructor & Destructor Documentation
cubload::class_entry::class_entry () delete
cubload::class_entry::class_entry (std::string & class_name, OID & class_oid, class_id clsid, std::vector< const attribute * > & attributes)
Definition at line 64 of file load_class_registry.cpp.
References m_attributes.
cubload::class_entry::class_entry (std::string & class_name, class_id clsid, bool is_ignored)
Definition at line 75 of file load_class_registry.cpp.
cubload::class_entry::~class_entry ()
Definition at line 83 of file load_class_registry.cpp.
References m_attributes.
cubload::class_entry::class_entry (class_entry && other) delete
cubload::class_entry::class_entry (const class_entry & copy) delete
Member Function Documentation
const attribute & cubload::class_entry::get_attribute (std::size_t index) const
Definition at line 105 of file load_class_registry.cpp.
References assert, and m_attributes.
Referenced by cubload::server_object_loader::process_line().
size_t cubload::class_entry::get_attributes_size () const
Definition at line 114 of file load_class_registry.cpp.
References m_attributes.
Referenced by cubload::server_object_loader::process_line().
const char * cubload::class_entry::get_class_name () const
Definition at line 99 of file load_class_registry.cpp.
References m_class_name.
Referenced by cubload::load_task::execute(), cubload::server_object_loader::flush_records(), cubload::session::install_class(), cubload::server_object_loader::process_collection_constant(), cubload::server_object_loader::process_generic_constant(), cubload::server_object_loader::process_monetary_constant(), and cubload::session::update_class_statistics().
const OID & cubload::class_entry::get_class_oid () const
Definition at line 93 of file load_class_registry.cpp.
References m_class_oid.
Referenced by cubload::server_object_loader::init(), cubload::server_object_loader::process_line(), cubload::server_object_loader::stop_scancache(), and cubload::session::update_class_statistics().
bool cubload::class_entry::is_ignored () const
Definition at line 120 of file load_class_registry.cpp.
References m_is_ignored.
Referenced by cubload::session::install_class(), cubload::class_registry::register_ignored_class(), and cubload::session::update_class_statistics().
class_entry& cubload::class_entry::operator= (class_entry && other) delete
class_entry& cubload::class_entry::operator= (const class_entry & copy) delete
Member Data Documentation
std::vector<const attribute *> cubload::class_entry::m_attributes private
Definition at line 83 of file load_class_registry.hpp.
Referenced by class_entry(), get_attribute(), get_attributes_size(), and ~class_entry().
std::string cubload::class_entry::m_class_name private
Definition at line 82 of file load_class_registry.hpp.
Referenced by get_class_name().
OID cubload::class_entry::m_class_oid private
Definition at line 81 of file load_class_registry.hpp.
Referenced by get_class_oid().
class_id cubload::class_entry::m_clsid private
Definition at line 80 of file load_class_registry.hpp.
const bool cubload::class_entry::m_is_ignored private
Definition at line 84 of file load_class_registry.hpp.
Referenced by is_ignored().
The documentation for this class was generated from the following files:
src/loaddb/load_class_registry.hpp
src/loaddb/load_class_registry.cpp