CUBRID Engine: cubload::scanner Class Reference
cubload::scanner Class Reference
#include <load_scanner.hpp>
Public Member Functions
scanner (semantic_helper &semantic_helper, error_handler &error_handler)
~scanner () override=default
void set_lineno (int line_offset)
virtual int yylex (parser::semantic_type *yylval, parser::location_type *yylloc)
void LexerError (const char *msg) override
Private Attributes
semantic_helper & m_semantic_helper
error_handler & m_error_handler
Detailed Description
Definition at line 39 of file load_scanner.hpp.
Constructor & Destructor Documentation
cubload::scanner::scanner (semantic_helper & semantic_helper, error_handler & error_handler) inline
Definition at line 42 of file load_scanner.hpp.
References ~scanner().
cubload::scanner::~scanner () override default
Referenced by scanner().
Member Function Documentation
void cubload::scanner::LexerError (const char * msg) inline override
Definition at line 67 of file load_scanner.hpp.
References cubload::error_handler::get_scanner_lineno(), LOADDB_MSG_LEX_ERROR, m_error_handler, cubload::error_handler::on_error_with_line(), and cubload::error_handler::on_syntax_failure().
void cubload::scanner::set_lineno (int line_offset) inline
Definition at line 52 of file load_scanner.hpp.
References yylex().
Referenced by cubload::driver::parse().
virtual int cubload::scanner::yylex (parser::semantic_type * yylval, parser::location_type * yylloc) virtual
Referenced by set_lineno().
Member Data Documentation
error_handler& cubload::scanner::m_error_handler private
Definition at line 82 of file load_scanner.hpp.
Referenced by LexerError().
semantic_helper& cubload::scanner::m_semantic_helper private
Definition at line 81 of file load_scanner.hpp.
The documentation for this class was generated from the following file:
src/loaddb/load_scanner.hpp