CUBRID Engine: btree_unique_stats Class Reference
btree_unique_stats Class Reference
#include <btree_unique.hpp>
Public Types
using stat_type = std::int64_t
Public Member Functions
btree_unique_stats ()
btree_unique_stats (stat_type keys, stat_type nulls=0)
stat_type get_key_count () const
stat_type get_row_count () const
stat_type get_null_count () const
void insert_key_and_row ()
void insert_null_and_row ()
void add_row ()
void delete_key_and_row ()
void delete_null_and_row ()
void delete_row ()
bool is_zero () const
bool is_unique () const
btree_unique_stats & operator= (const btree_unique_stats &us)
void operator+= (const btree_unique_stats &us)
void operator-= (const btree_unique_stats &us)
void to_string (string_buffer &strbuf) const
Private Attributes
stat_type m_rows
stat_type m_keys
stat_type m_nulls
Detailed Description
Definition at line 34 of file btree_unique.hpp.
Member Typedef Documentation
using btree_unique_stats::stat_type = std::int64_t
Definition at line 37 of file btree_unique.hpp.
Constructor & Destructor Documentation
btree_unique_stats::btree_unique_stats ()
Definition at line 36 of file btree_unique.cpp.
Referenced by multi_index_unique_stats::add_empty().
btree_unique_stats::btree_unique_stats (stat_type keys, stat_type nulls = 0)
Definition at line 29 of file btree_unique.cpp.
Member Function Documentation
void btree_unique_stats::add_row ()
Definition at line 74 of file btree_unique.cpp.
References m_rows.
Referenced by btree_insert_internal().
void btree_unique_stats::delete_key_and_row ()
Definition at line 80 of file btree_unique.cpp.
References m_keys, and m_rows.
Referenced by btree_fix_root_for_delete(), btree_fix_root_for_insert(), and btree_insert_internal().
void btree_unique_stats::delete_null_and_row ()
Definition at line 87 of file btree_unique.cpp.
References m_nulls, and m_rows.
Referenced by btree_fix_root_for_delete(), and btree_fix_root_for_insert().
void btree_unique_stats::delete_row ()
Definition at line 94 of file btree_unique.cpp.
References m_rows.
Referenced by btree_delete_internal(), and btree_insert_internal().
btree_unique_stats::stat_type btree_unique_stats::get_key_count () const
Definition at line 42 of file btree_unique.cpp.
References m_keys.
Referenced by btree_insert_internal(), and logtb_tran_update_unique_stats().
btree_unique_stats::stat_type btree_unique_stats::get_null_count () const
Definition at line 54 of file btree_unique.cpp.
References m_nulls.
Referenced by btree_insert_internal(), and logtb_tran_update_unique_stats().
btree_unique_stats::stat_type btree_unique_stats::get_row_count () const
Definition at line 48 of file btree_unique.cpp.
References m_rows.
Referenced by btree_insert_internal(), and logtb_tran_update_unique_stats().
void btree_unique_stats::insert_key_and_row ()
Definition at line 60 of file btree_unique.cpp.
References m_keys, and m_rows.
Referenced by btree_delete_internal(), btree_fix_root_for_insert(), and btree_insert_internal().
void btree_unique_stats::insert_null_and_row ()
Definition at line 67 of file btree_unique.cpp.
References m_nulls, and m_rows.
Referenced by btree_fix_root_for_insert().
bool btree_unique_stats::is_unique () const
Definition at line 106 of file btree_unique.cpp.
References m_keys, m_nulls, and m_rows.
bool btree_unique_stats::is_zero () const
Definition at line 100 of file btree_unique.cpp.
References m_keys, and m_nulls.
Referenced by logtb_tran_update_unique_stats().
void btree_unique_stats::operator+= (const btree_unique_stats & us)
Definition at line 122 of file btree_unique.cpp.
References m_keys, m_nulls, and m_rows.
void btree_unique_stats::operator-= (const btree_unique_stats & us)
Definition at line 130 of file btree_unique.cpp.
References m_keys, m_nulls, and m_rows.
btree_unique_stats & btree_unique_stats::operator= (const btree_unique_stats & us)
Definition at line 112 of file btree_unique.cpp.
References m_keys, m_nulls, and m_rows.
void btree_unique_stats::to_string (string_buffer & strbuf) const
Definition at line 138 of file btree_unique.cpp.
References m_keys, m_nulls, and m_rows.
Member Data Documentation
stat_type btree_unique_stats::m_keys private
Definition at line 65 of file btree_unique.hpp.
Referenced by delete_key_and_row(), get_key_count(), insert_key_and_row(), is_unique(), is_zero(), operator+=(), operator-=(), operator=(), and to_string().
stat_type btree_unique_stats::m_nulls private
Definition at line 66 of file btree_unique.hpp.
Referenced by delete_null_and_row(), get_null_count(), insert_null_and_row(), is_unique(), is_zero(), operator+=(), operator-=(), operator=(), and to_string().
stat_type btree_unique_stats::m_rows private
Definition at line 64 of file btree_unique.hpp.
Referenced by add_row(), delete_key_and_row(), delete_null_and_row(), delete_row(), get_row_count(), insert_key_and_row(), insert_null_and_row(), is_unique(), operator+=(), operator-=(), operator=(), and to_string().
The documentation for this class was generated from the following files:
src/storage/btree_unique.hpp
src/storage/btree_unique.cpp