CUBRID Engine: HL::AddHeap< Add, SuperHeap > Class Template Reference
HL::AddHeap< Add, SuperHeap > Class Template Reference
#include <addheap.h>
Public Member Functions
void * malloc (size_t sz)
void free (void *ptr)
size_t getSize (void *ptr)
Private Types
enum { HeaderSize = lcm<(int) SuperHeap::Alignment, sizeof(Add)>::value }
Private Member Functions
void * getOriginal (void *ptr)
Detailed Description
template<class Add, class SuperHeap>
class HL::AddHeap< Add, SuperHeap >
Definition at line 29 of file addheap.h.
Member Enumeration Documentation
template<class Add , class SuperHeap > anonymous enum private
Enumerator
HeaderSize
Definition at line 55 of file addheap.h.
Member Function Documentation
template<class Add , class SuperHeap > void HL::AddHeap< Add, SuperHeap >::free (void * ptr) inline
Definition at line 38 of file addheap.h.
References HL::AddHeap< Add, SuperHeap >::getOriginal().
template<class Add , class SuperHeap > void* HL::AddHeap< Add, SuperHeap >::getOriginal (void * ptr) inline private
Definition at line 48 of file addheap.h.
References HL::AddHeap< Add, SuperHeap >::HeaderSize.
Referenced by HL::AddHeap< Add, SuperHeap >::free(), and HL::AddHeap< Add, SuperHeap >::getSize().
template<class Add , class SuperHeap > size_t HL::AddHeap< Add, SuperHeap >::getSize (void * ptr) inline
Definition at line 42 of file addheap.h.
References HL::AddHeap< Add, SuperHeap >::getOriginal().
template<class Add , class SuperHeap > void* HL::AddHeap< Add, SuperHeap >::malloc (size_t sz) inline
Definition at line 32 of file addheap.h.
References HL::AddHeap< Add, SuperHeap >::HeaderSize.
The documentation for this class was generated from the following file:
src/heaplayers/heaps/objectrep/addheap.h