CUBRID Engine: lockfree::tran::system Class Reference
lockfree::tran::system Class Reference
#include <lockfree_transaction_system.hpp>
Public Member Functions
system ()=delete
system (size_t max_tran_count)
~system ()=default
index assign_index ()
void free_index (index idx)
size_t get_max_transaction_count () const
Private Attributes
size_t m_max_tran_per_table
bitmap m_tran_idx_map
Detailed Description
Definition at line 76 of file lockfree_transaction_system.hpp.
Constructor & Destructor Documentation
lockfree::tran::system::system () delete
lockfree::tran::system::system (size_t max_tran_count)
Definition at line 27 of file lockfree_transaction_system.cpp.
References assert, lockfree::bitmap::FULL_USAGE_RATIO, lockfree::bitmap::init(), m_max_tran_per_table, and m_tran_idx_map.
lockfree::tran::system::~system () default
Member Function Documentation
index lockfree::tran::system::assign_index ()
Definition at line 37 of file lockfree_transaction_system.cpp.
References assert, lockfree::bitmap::get_entry(), lockfree::tran::INVALID_INDEX, and m_tran_idx_map.
Referenced by cubthread::manager::init_entries(), and cubthread::initialize_thread_entries().
void lockfree::tran::system::free_index (index idx)
Definition at line 49 of file lockfree_transaction_system.cpp.
References assert, lockfree::bitmap::free_entry(), lockfree::tran::INVALID_INDEX, and m_tran_idx_map.
Referenced by cubthread::manager::return_lock_free_transaction_entries().
size_t lockfree::tran::system::get_max_transaction_count () const
Definition at line 60 of file lockfree_transaction_system.cpp.
References m_max_tran_per_table.
Referenced by lockfree::tran::table::compute_min_active_tranid(), lockfree::tran::table::get_current_retire_count(), lockfree::tran::table::get_descriptor(), lockfree::tran::table::get_total_reclaim_count(), lockfree::tran::table::get_total_retire_count(), and lockfree::tran::table::table().
Member Data Documentation
size_t lockfree::tran::system::m_max_tran_per_table private
Definition at line 88 of file lockfree_transaction_system.hpp.
Referenced by get_max_transaction_count(), and system().
bitmap lockfree::tran::system::m_tran_idx_map private
Definition at line 89 of file lockfree_transaction_system.hpp.
Referenced by assign_index(), free_index(), and system().
The documentation for this class was generated from the following files:
src/base/lockfree_transaction_system.hpp
src/base/lockfree_transaction_system.cpp