CUBRID Engine: JSON_WALKER Class Reference
JSON_WALKER Class Reference
Public Member Functions
int WalkDocument (const JSON_DOC &document)
Protected Member Functions
virtual ~JSON_WALKER ()=default
virtual int CallBefore (const JSON_VALUE &value)
virtual int CallAfter (const JSON_VALUE &value)
virtual int CallOnArrayIterate ()
virtual int CallOnKeyIterate (const JSON_VALUE &key)
Protected Attributes
bool m_stop
Private Member Functions
int WalkValue (const JSON_VALUE &value)
Detailed Description
Definition at line 391 of file db_json.cpp.
Constructor & Destructor Documentation
virtual JSON_WALKER::~JSON_WALKER () protected virtual default
Member Function Documentation
virtual int JSON_WALKER::CallAfter (const JSON_VALUE & value) inline protected virtual
Reimplemented in JSON_PATH_MAPPER.
Definition at line 408 of file db_json.cpp.
References NO_ERROR.
virtual int JSON_WALKER::CallBefore (const JSON_VALUE & value) inline protected virtual
Reimplemented in JSON_PATH_MAPPER, and JSON_DUPLICATE_KEYS_CHECKER.
Definition at line 401 of file db_json.cpp.
References NO_ERROR.
virtual int JSON_WALKER::CallOnArrayIterate () inline protected virtual
Reimplemented in JSON_PATH_MAPPER.
Definition at line 415 of file db_json.cpp.
References NO_ERROR.
virtual int JSON_WALKER::CallOnKeyIterate (const JSON_VALUE & key) inline protected virtual
Reimplemented in JSON_PATH_MAPPER.
Definition at line 422 of file db_json.cpp.
References NO_ERROR.
int JSON_WALKER::WalkDocument (const JSON_DOC & document)
Definition at line 3354 of file db_json.cpp.
References db_json_doc_to_value().
Referenced by db_json_contains_duplicate_keys(), db_json_contains_path(), and db_json_search_func().
int JSON_WALKER::WalkValue (const JSON_VALUE & value) private
Definition at line 3361 of file db_json.cpp.
References ASSERT_ERROR, and NO_ERROR.
Member Data Documentation
bool JSON_WALKER::m_stop protected
Definition at line 432 of file db_json.cpp.
Referenced by JSON_PATH_MAPPER::CallAfter().
The documentation for this class was generated from the following file:
src/compat/db_json.cpp