CUBRID Engine: cubthread::lockfree_hashmap< Key, T >::iterator Class Reference
cubthread::lockfree_hashmap< Key, T >::iterator Class Reference
#include <thread_lockfree_hash_map.hpp>
Public Member Functions
iterator (cubthread::entry *thread_p, lockfree_hashmap &map)
~iterator ()=default
T * iterate ()
void restart ()
Private Attributes
lockfree_hashmap & m_map
lf_hash_table_cpp< Key, T >::iterator m_old_iter
lockfree::hashmap< Key, T >::iterator m_new_iter
Detailed Description
template<class Key, class T>
class cubthread::lockfree_hashmap< Key, T >::iterator
Definition at line 89 of file thread_lockfree_hash_map.hpp.
Constructor & Destructor Documentation
template<class Key , class T > cubthread::lockfree_hashmap< Key, T >::iterator::iterator (cubthread::entry * thread_p, lockfree_hashmap & map)
Definition at line 309 of file thread_lockfree_hash_map.hpp.
References cubthread::entry::get_lf_tran_index(), cubthread::lockfree_hashmap< Key, T >::get_tran_entry(), cubthread::lockfree_hashmap< Key, T >::is_old_type(), cubthread::lockfree_hashmap< Key, T >::iterator::m_map, cubthread::lockfree_hashmap< Key, T >::m_new_hash, cubthread::lockfree_hashmap< Key, T >::iterator::m_new_iter, cubthread::lockfree_hashmap< Key, T >::m_old_hash, and cubthread::lockfree_hashmap< Key, T >::iterator::m_old_iter.
template<class Key, class T> cubthread::lockfree_hashmap< Key, T >::iterator::~iterator () default
Member Function Documentation
template<class Key , class T > T * cubthread::lockfree_hashmap< Key, T >::iterator::iterate ()
Definition at line 326 of file thread_lockfree_hash_map.hpp.
References cubthread::lockfree_hashmap< Key, T >::is_old_type(), cubthread::lockfree_hashmap< Key, T >::iterator::iterate(), cubthread::lockfree_hashmap< Key, T >::iterator::m_map, cubthread::lockfree_hashmap< Key, T >::iterator::m_new_iter, and cubthread::lockfree_hashmap< Key, T >::iterator::m_old_iter.
Referenced by fpcache_cleanup(), fpcache_dump(), and cubthread::lockfree_hashmap< Key, T >::iterator::iterate().
template<class Key , class T > void cubthread::lockfree_hashmap< Key, T >::iterator::restart ()
Definition at line 340 of file thread_lockfree_hash_map.hpp.
References cubthread::lockfree_hashmap< Key, T >::is_old_type(), cubthread::lockfree_hashmap< Key, T >::iterator::m_map, cubthread::lockfree_hashmap< Key, T >::iterator::m_new_iter, cubthread::lockfree_hashmap< Key, T >::iterator::m_old_iter, and cubthread::lockfree_hashmap< Key, T >::iterator::restart().
Referenced by cubthread::lockfree_hashmap< Key, T >::iterator::restart().
Member Data Documentation
template<class Key, class T> lockfree_hashmap& cubthread::lockfree_hashmap< Key, T >::iterator::m_map private
Definition at line 101 of file thread_lockfree_hash_map.hpp.
Referenced by cubthread::lockfree_hashmap< Key, T >::iterator::iterate(), cubthread::lockfree_hashmap< Key, T >::iterator::iterator(), and cubthread::lockfree_hashmap< Key, T >::iterator::restart().
template<class Key, class T> lockfree::hashmap<Key, T>::iterator cubthread::lockfree_hashmap< Key, T >::iterator::m_new_iter private
Definition at line 103 of file thread_lockfree_hash_map.hpp.
Referenced by cubthread::lockfree_hashmap< Key, T >::iterator::iterate(), cubthread::lockfree_hashmap< Key, T >::iterator::iterator(), and cubthread::lockfree_hashmap< Key, T >::iterator::restart().
template<class Key, class T> lf_hash_table_cpp<Key, T>::iterator cubthread::lockfree_hashmap< Key, T >::iterator::m_old_iter private
Definition at line 102 of file thread_lockfree_hash_map.hpp.
Referenced by cubthread::lockfree_hashmap< Key, T >::iterator::iterate(), cubthread::lockfree_hashmap< Key, T >::iterator::iterator(), and cubthread::lockfree_hashmap< Key, T >::iterator::restart().
The documentation for this class was generated from the following file:
src/thread/thread_lockfree_hash_map.hpp