CUBRID Engine: FreeSLList Class Reference
FreeSLList Class Reference
A "memory neutral" singly-linked list,.
#include <freesllist.h>
Classes
class Entry
Public Member Functions
void clear (void)
Entry * get (void)
Get the head of the list.
Entry * remove (void)
void insert (void *e)
Private Attributes
Entry head
Detailed Description
A "memory neutral" singly-linked list,.
Uses the free space in objects to store the pointers.
Definition at line 17 of file freesllist.h.
Member Function Documentation
void FreeSLList::clear (void) inline
Definition at line 20 of file freesllist.h.
References head, FreeSLList::Entry::next, and NULL.
Entry* FreeSLList::get (void) inline
Get the head of the list.
Definition at line 27 of file freesllist.h.
References head, FreeSLList::Entry::next, and NULL.
Referenced by HL::FreelistHeap< ZoneHeap< MallocHeap, 0 > >::clear(), and HL::FreelistHeap< ZoneHeap< MallocHeap, 0 > >::malloc().
void FreeSLList::insert (void * e) inline
Definition at line 45 of file freesllist.h.
References head, and FreeSLList::Entry::next.
Referenced by HL::FreelistHeap< ZoneHeap< MallocHeap, 0 > >::free().
Entry* FreeSLList::remove (void) inline
Definition at line 36 of file freesllist.h.
References head, FreeSLList::Entry::next, and NULL.
Member Data Documentation
Entry FreeSLList::head private
Definition at line 63 of file freesllist.h.
Referenced by clear(), get(), insert(), and remove().
The documentation for this class was generated from the following file:
src/heaplayers/utility/freesllist.h