CUBRID Engine: string_print_output Class Reference
string_print_output Class Reference
#include <printer.hpp>
Public Member Functions
string_print_output ()
~string_print_output ()
int flush (void)
const char * get_buffer () const
void clear (void)
Public Member Functions inherited from print_output
print_output ()
~print_output ()
string_buffer * grab_string_buffer (void)
void operator+= (const char ch)
template<typename... Args>
int operator() (Args &&...args)
Additional Inherited Members
Protected Attributes inherited from print_output
string_buffer m_sb
Detailed Description
Definition at line 90 of file printer.hpp.
Constructor & Destructor Documentation
string_print_output::string_print_output ()
Definition at line 50 of file printer.cpp.
string_print_output::~string_print_output () inline
Definition at line 94 of file printer.hpp.
References print_output::flush().
Member Function Documentation
void string_print_output::clear (void) inline
Definition at line 103 of file printer.hpp.
References string_buffer::clear(), and print_output::m_sb.
Referenced by er_dump_call_stack_to_string().
int string_print_output::flush (void) virtual
Implements print_output.
Definition at line 54 of file printer.cpp.
References string_buffer::len(), and print_output::m_sb.
const char* string_print_output::get_buffer () const inline
Definition at line 98 of file printer.hpp.
References string_buffer::get_buffer(), and print_output::m_sb.
Referenced by er_dump_call_stack_to_string().
The documentation for this class was generated from the following files:
src/base/printer.hpp
src/base/printer.cpp