CUBRID Engine: cubload::load_task Class Reference
cubload::load_task Class Reference
Public Member Functions
load_task ()=delete
~load_task () override
load_task (const batch &batch, session &session, css_conn_entry &conn_entry)
void execute (cubthread::entry &thread_ref) final
Public Member Functions inherited from cubthread::task< Context >
task (void)=default
virtual ~task (void)=default
virtual void execute (context_type &)=0
virtual void retire (void)
Private Member Functions
void notify_done ()
void notify_done_and_tran_end (int tran_index)
Private Attributes
const batch & m_batch
session & m_session
css_conn_entry & m_conn_entry
bool m_was_session_notified
Additional Inherited Members
Public Types inherited from cubthread::task< Context >
using context_type = Context
Detailed Description
Definition at line 95 of file load_session.cpp.
Constructor & Destructor Documentation
cubload::load_task::load_task () delete
cubload::load_task::~load_task () inline override
Definition at line 100 of file load_session.cpp.
References m_batch, m_was_session_notified, and notify_done().
cubload::load_task::load_task (const batch & batch, session & session, css_conn_entry & conn_entry) inline
Definition at line 109 of file load_session.cpp.
Member Function Documentation
void cubload::load_task::execute (cubthread::entry & thread_ref) inline final
Definition at line 118 of file load_session.cpp.
References trantable::all_tdes, cubload::session::append_log_msg(), assert, cubload::driver::clear(), log_tdes::client, er_has_error(), cubload::session::fail(), cubload::session::get_args(), cubload::class_registry::get_class_entry(), cubload::batch::get_class_id(), cubload::class_entry::get_class_name(), cubload::session::get_class_registry(), cubload::driver::get_error_handler(), cubload::batch::get_id(), cubload::driver::get_object_loader(), cubload::object_loader::get_rows_number(), cubload::driver::get_scanner(), cubload::init_driver(), cubload::invoke_parser(), cubload::session::is_failed(), cubload::driver::is_initialized(), LOADDB_MSG_COMMITTED_INSTANCES, LOADDB_MSG_INSTANCE_COUNT, LOADDB_MSG_TABLE_IS_MISSING, log_Gl, logtb_assign_tran_index(), m_batch, m_conn_entry, m_session, notify_done(), notify_done_and_tran_end(), NULL, NULL_TRANID, cubload::error_handler::on_error_with_line(), cubload::error_handler::on_failure_with_line(), cubload::session::register_tran_start(), clientids::reset(), clientids::set_ids(), cubload::session::stats_update_last_committed_line(), cubload::session::stats_update_rows_committed(), cubload::load_args::syntax_check, TRAN_ACTIVE, TRAN_DEFAULT_ISOLATION_LEVEL, TRAN_LOCK_INFINITE_WAIT, log_global::trantable, cubload::session::wait_for_previous_batch(), xtran_server_abort(), and xtran_server_commit().
void cubload::load_task::notify_done () inline private
Definition at line 212 of file load_session.cpp.
References assert, cubload::batch::get_id(), m_batch, m_session, m_was_session_notified, and cubload::session::notify_batch_done().
Referenced by execute(), and ~load_task().
void cubload::load_task::notify_done_and_tran_end (int tran_index) inline private
Definition at line 219 of file load_session.cpp.
References assert, cubload::batch::get_id(), m_batch, m_session, m_was_session_notified, and cubload::session::notify_batch_done_and_register_tran_end().
Referenced by execute().
Member Data Documentation
const batch& cubload::load_task::m_batch private
Definition at line 226 of file load_session.cpp.
Referenced by execute(), notify_done(), notify_done_and_tran_end(), and ~load_task().
css_conn_entry& cubload::load_task::m_conn_entry private
Definition at line 228 of file load_session.cpp.
Referenced by execute().
session& cubload::load_task::m_session private
Definition at line 227 of file load_session.cpp.
Referenced by execute(), notify_done(), and notify_done_and_tran_end().
bool cubload::load_task::m_was_session_notified private
Definition at line 229 of file load_session.cpp.
Referenced by notify_done(), notify_done_and_tran_end(), and ~load_task().
The documentation for this class was generated from the following file:
src/loaddb/load_session.cpp