CUBRID Engine: cubmem::extensible_array< T, Size > Class Template Reference
cubmem::extensible_array< T, Size > Class Template Reference
#include <extensible_array.hpp>
Public Member Functions
void extend_by (size_t count)
void extend_to (size_t count)
const T * get_array (void) const
Protected Member Functions
T * get_data_ptr ()
size_t get_memsize_for_count (size_t count) const
Protected Member Functions inherited from cubmem::extensible_stack_block< sizeof(T)*Size >
extensible_stack_block ()
extensible_stack_block (const block_allocator &alloc)
void extend_by (size_t additional_bytes)
void extend_to (size_t total_bytes)
char * get_ptr ()
const char * get_read_ptr () const
Private Types
using base_type = extensible_stack_block< sizeof(T)*Size >
Detailed Description
template<typename T, size_t Size>
class cubmem::extensible_array< T, Size >
Definition at line 59 of file extensible_array.hpp.
Member Typedef Documentation
template<typename T, size_t Size> using cubmem::extensible_array< T, Size >::base_type = extensible_stack_block<sizeof (T) * Size> private
Definition at line 62 of file extensible_array.hpp.
Member Function Documentation
template<typename T , size_t Size> void cubmem::extensible_array< T, Size >::extend_by (size_t count)
Definition at line 174 of file extensible_array.hpp.
References cubmem::extensible_stack_block< Size >::extend_by().
template<typename T , size_t Size> void cubmem::extensible_array< T, Size >::extend_to (size_t count)
Definition at line 181 of file extensible_array.hpp.
References cubmem::extensible_stack_block< Size >::extend_to().
template<typename T , size_t Size> const T * cubmem::extensible_array< T, Size >::get_array (void) const
Definition at line 188 of file extensible_array.hpp.
References cubmem::extensible_stack_block< Size >::get_read_ptr().
template<typename T , size_t Size> T * cubmem::extensible_array< T, Size >::get_data_ptr () protected
Definition at line 195 of file extensible_array.hpp.
References cubmem::extensible_stack_block< Size >::get_ptr().
template<typename T , size_t Size> size_t cubmem::extensible_array< T, Size >::get_memsize_for_count (size_t count) const protected
Definition at line 202 of file extensible_array.hpp.
The documentation for this class was generated from the following file:
src/base/extensible_array.hpp