CUBRID Engine: JSON_PRIVATE_ALLOCATOR Class Reference
JSON_PRIVATE_ALLOCATOR Class Reference
#include <db_json_allocator.hpp>
Public Member Functions
void * Malloc (size_t size)
void * Realloc (void *originalPtr, size_t originalSize, size_t newSize)
Static Public Member Functions
static void Free (void *ptr)
Static Public Attributes
static const bool kNeedFree = true
Detailed Description
Definition at line 24 of file db_json_allocator.hpp.
Member Function Documentation
void JSON_PRIVATE_ALLOCATOR::Free (void * ptr) static
Definition at line 62 of file db_json_allocator.cpp.
References db_private_free, kNeedFree, and NULL.
void * JSON_PRIVATE_ALLOCATOR::Malloc (size_t size)
Definition at line 26 of file db_json_allocator.cpp.
References ARG_FILE_LINE, db_private_alloc, er_print_callstack(), NULL, p, prm_get_bool_value(), and PRM_ID_JSON_LOG_ALLOCATIONS.
void * JSON_PRIVATE_ALLOCATOR::Realloc (void * originalPtr, size_t originalSize, size_t newSize)
Definition at line 44 of file db_json_allocator.cpp.
References ARG_FILE_LINE, db_private_free, db_private_realloc, er_print_callstack(), NULL, p, prm_get_bool_value(), and PRM_ID_JSON_LOG_ALLOCATIONS.
Member Data Documentation
const bool JSON_PRIVATE_ALLOCATOR::kNeedFree = true static
Definition at line 27 of file db_json_allocator.hpp.
Referenced by Free().
The documentation for this class was generated from the following files:
src/compat/db_json_allocator.hpp
src/compat/db_json_allocator.cpp