CUBRID Engine: object_printer Class Reference
object_printer Class Reference
#include <object_printer.hpp>
Public Member Functions
object_printer (string_buffer &buf)
void describe_comment (const char *comment)
void describe_partition_parts (const sm_partition &parts, class_description::type prt_type)
void describe_identifier (const char *identifier, class_description::type prt_type)
void describe_domain (tp_domain &domain, class_description::type prt_type, bool force_print_collation)
void describe_argument (const sm_method_argument &argument, class_description::type prt_type)
void describe_method (const struct db_object &op, const sm_method &method_p, class_description::type prt_type)
void describe_signature (const sm_method_signature &signature_p, class_description::type prt_type)
void describe_attribute (const struct db_object &class_p, const sm_attribute &attribute_p, bool is_inherited, class_description::type prt_type, bool force_print_collation)
void describe_constraint (const sm_class &class_p, const sm_class_constraint &constraint_p, class_description::type prt_type)
void describe_resolution (const sm_resolution &resolution, class_description::type prt_type)
void describe_method_file (const struct db_object &obj, const sm_method_file &file)
void describe_class_trigger (const tr_trigger &trigger)
void describe_class (struct db_object *class_op)
void describe_partition_info (const sm_partition &partinfo)
Static Public Member Functions
static const char * describe_trigger_condition_time (const tr_trigger &trigger)
static const char * describe_trigger_action_time (const tr_trigger &trigger)
Private Attributes
string_buffer & m_buf
Detailed Description
Definition at line 52 of file object_printer.hpp.
Constructor & Destructor Documentation
object_printer::object_printer (string_buffer & buf) inline
Definition at line 57 of file object_printer.hpp.
Member Function Documentation
void object_printer::describe_argument (const sm_method_argument & argument, class_description::type prt_type)
Definition at line 334 of file object_printer.cpp.
References describe_domain(), sm_method_argument::domain, m_buf, pr_type::name, NULL, and sm_method_argument::type.
Referenced by describe_method(), and describe_signature().
void object_printer::describe_attribute (const struct db_object & class_p, const sm_attribute & attribute_p, bool is_inherited, class_description::type prt_type, bool force_print_collation)
Definition at line 453 of file object_printer.cpp.
References assert, sm_attribute::auto_increment, sm_attribute::class_mop, sm_attribute::comment, class_description::CSQL_SCHEMA_COMMAND, db_default_expression_string(), DB_DEFAULT_NONE, db_get(), DB_IS_NULL, db_make_null(), DB_MAX_NUMERIC_PRECISION, sm_default_value::default_expr, db_default_expr::default_expr_format, db_default_expr::default_expr_op, db_default_expr::default_expr_type, sm_attribute::default_value, describe_comment(), describe_domain(), describe_identifier(), db_value_printer::describe_value(), sm_attribute::domain, sm_attribute::flags, sm_attribute::header, ID_ATTRIBUTE, ID_CLASS_ATTRIBUTE, ID_SHARED_ATTRIBUTE, m_buf, sm_component::name, sm_component::name_space, NO_ERROR, NULL, NULL_DEFAULT_EXPRESSION_OPERATOR, numeric_db_value_print(), NUMERIC_MAX_STRING_SIZE, sm_attribute::on_update_default_expr, pr_clear_value(), class_description::SHOW_CREATE_TABLE, SM_ATTFLAG_AUTO_INCREMENT, SM_ATTFLAG_NON_NULL, sm_get_ch_name(), T_TO_CHAR, and sm_default_value::value.
Referenced by class_description::init().
void object_printer::describe_class (struct db_object * class_op)
Definition at line 949 of file object_printer.cpp.
References assert, class_description::attributes, class_description::class_attributes, class_description::class_methods, string_buffer::clear(), class_description::collation, class_description::comment, class_description::constraints, db_get_class_name(), db_make_null(), db_make_string(), db_value_printer::describe_value(), ER_AU_SELECT_FAILURE, er_errid(), er_msg(), error(), i, class_description::init(), m_buf, class_description::method_files, class_description::methods, MSGCAT_RUNTIME_IS_NOT_AUTHORIZED_ON, MSGCAT_SET_PARSER_RUNTIME, class_description::name, NO_ERROR, NULL, parser, class_description::partition, pr_clear_value(), PT_ERRORc, PT_ERRORmf2, class_description::resolutions, class_description::SHOW_CREATE_TABLE, sm_get_class_tde_algorithm(), sm_is_reuse_oid_class(), class_description::supers, TDE_ALGORITHM_NONE, and tde_get_algorithm_name().
Referenced by db_get_schema_def_dbval(), and pt_help_show_create_table().
void object_printer::describe_class_trigger (const tr_trigger & trigger)
Definition at line 885 of file object_printer.cpp.
References tr_trigger::attribute, tr_trigger::comment, describe_comment(), describe_trigger_condition_time(), tr_trigger::event, m_buf, tr_trigger::name, NULL, and tr_event_as_string().
void object_printer::describe_comment (const char * comment)
Definition at line 47 of file object_printer.cpp.
References assert, db_make_null(), db_make_string(), db_value_printer::describe_value(), m_buf, NULL, and pr_clear_value().
Referenced by describe_attribute(), describe_class_trigger(), describe_constraint(), describe_partition_parts(), help_print_describe_comment(), and class_description::init().
void object_printer::describe_constraint (const sm_class & class_p, const sm_class_constraint & constraint_p, class_description::type prt_type)
Definition at line 602 of file object_printer.cpp.
References sm_class_constraint::asc_desc, assert, sm_function_info::attr_index_start, sm_class_constraint::attributes, sm_class_constraint::attrs_prefix_length, au_fetch_class_force(), AU_FETCH_READ, classobj_describe_foreign_key_action(), sm_function_info::col_id, sm_class_constraint::comment, class_description::CSQL_SCHEMA_COMMAND, sm_foreign_key_info::delete_action, describe_comment(), describe_identifier(), sm_function_info::expr_str, sm_function_info::fi_domain, sm_class_constraint::filter_predicate, sm_class_constraint::fk_info, sm_class_constraint::func_index_info, sm_attribute::header, sm_class_constraint::index_status, tp_domain::is_desc, m_buf, sm_component::name, sm_class_constraint::name, sm_class_constraint::next, NO_ERROR, NULL, sm_predicate_info::pred_string, sm_foreign_key_info::ref_class_oid, class_description::SHOW_CREATE_TABLE, sm_ch_name(), SM_CONSTRAINT_FOREIGN_KEY, SM_CONSTRAINT_INDEX, SM_CONSTRAINT_PRIMARY_KEY, SM_CONSTRAINT_REVERSE_INDEX, SM_CONSTRAINT_REVERSE_UNIQUE, SM_CONSTRAINT_UNIQUE, SM_INVISIBLE_INDEX, SM_IS_CONSTRAINT_REVERSE_INDEX_FAMILY, SM_ONLINE_INDEX_BUILDING_IN_PROGRESS, sm_class_constraint::type, sm_foreign_key_info::update_action, and ws_mop().
Referenced by class_description::init().
void object_printer::describe_domain (tp_domain & domain, class_description::type prt_type, bool force_print_collation)
Definition at line 169 of file object_printer.cpp.
References string_buffer::add_bytes(), tp_domain::class_mop, tp_domain::collation_id, cubregex::count(), DB_GET_ENUM_ELEM_STRING, DB_GET_ENUM_ELEM_STRING_SIZE, db_json_get_schema_raw_from_validator(), DB_MAX_STRING_LENGTH, DB_TYPE_BIGINT, DB_TYPE_BIT, DB_TYPE_BLOB, DB_TYPE_CHAR, DB_TYPE_CLOB, DB_TYPE_DATE, DB_TYPE_DATETIME, DB_TYPE_DATETIMELTZ, DB_TYPE_DATETIMETZ, DB_TYPE_DB_VALUE, DB_TYPE_DOUBLE, DB_TYPE_ENUMERATION, DB_TYPE_ERROR, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_JSON, DB_TYPE_MONETARY, DB_TYPE_MULTISET, DB_TYPE_NCHAR, DB_TYPE_NULL, DB_TYPE_NUMERIC, DB_TYPE_OBJECT, DB_TYPE_OID, DB_TYPE_POINTER, DB_TYPE_SEQUENCE, DB_TYPE_SET, DB_TYPE_SHORT, DB_TYPE_SUB, DB_TYPE_TIME, DB_TYPE_TIMESTAMP, DB_TYPE_TIMESTAMPLTZ, DB_TYPE_TIMESTAMPTZ, DB_TYPE_VARBIT, DB_TYPE_VARCHAR, DB_TYPE_VARIABLE, DB_TYPE_VARNCHAR, DB_TYPE_VOBJ, describe_identifier(), DOM_GET_ENUM_ELEM, DOM_GET_ENUM_ELEMS_COUNT, tp_domain::json_validator, lang_get_collation_name(), LANG_SYS_COLLATION, m_buf, pr_type::name, tp_domain::next, NULL, tp_domain::precision, tp_domain::scale, tp_domain::setdomain, class_description::SHOW_CREATE_TABLE, sm_filter_domain(), sm_get_ch_name(), TP_DOMAIN_TYPE, TP_FLOATING_PRECISION_VALUE, tp_domain::type, and ustr_upper().
Referenced by describe_argument(), and describe_attribute().
void object_printer::describe_identifier (const char * identifier, class_description::type prt_type)
Definition at line 142 of file object_printer.cpp.
References class_description::CSQL_SCHEMA_COMMAND, and m_buf.
Referenced by describe_attribute(), describe_constraint(), describe_domain(), describe_method(), describe_partition_parts(), and describe_resolution().
void object_printer::describe_method (const struct db_object & op, const sm_method & method_p, class_description::type prt_type)
Definition at line 361 of file object_printer.cpp.
References sm_method::class_mop, describe_argument(), describe_identifier(), describe_signature(), sm_method_signature::function_name, sm_method::header, m_buf, sm_component::name, NULL, sm_method::signatures, sm_get_ch_name(), and sm_method_signature::value.
Referenced by class_description::init().
void object_printer::describe_method_file (const struct db_object & obj, const sm_method_file & file)
Definition at line 865 of file object_printer.cpp.
References sm_method_file::class_mop, m_buf, sm_method_file::name, NULL, and sm_get_ch_name().
Referenced by class_description::init().
void object_printer::describe_partition_info (const sm_partition & partinfo)
Definition at line 1175 of file object_printer.cpp.
References assert, CAST_STRLEN, db_get_int(), DB_MAX_IDENTIFIER_LENGTH, sm_partition::expr, m_buf, NO_ERROR, NULL, sm_partition::partition_type, PT_PARTITION_HASH, PT_PARTITION_LIST, PT_PARTITION_RANGE, set_get_element(), and sm_partition::values.
Referenced by class_description::init().
void object_printer::describe_partition_parts (const sm_partition & parts, class_description::type prt_type)
Definition at line 71 of file object_printer.cpp.
References sm_partition::comment, DB_IS_NULL, db_make_null(), describe_comment(), describe_identifier(), db_value_printer::describe_value(), i, m_buf, NO_ERROR, NULL, sm_partition::partition_type, sm_partition::pname, pr_clear_value(), PT_PARTITION_HASH, PT_PARTITION_LIST, PT_PARTITION_RANGE, set_get_element(), set_size(), and sm_partition::values.
Referenced by class_description::init().
void object_printer::describe_resolution (const sm_resolution & resolution, class_description::type prt_type)
Definition at line 830 of file object_printer.cpp.
References sm_resolution::alias, sm_resolution::class_mop, describe_identifier(), ID_CLASS, m_buf, sm_resolution::name, sm_resolution::name_space, NULL, class_description::SHOW_CREATE_TABLE, and sm_get_ch_name().
Referenced by class_description::init().
void object_printer::describe_signature (const sm_method_signature & signature_p, class_description::type prt_type)
Definition at line 412 of file object_printer.cpp.
References sm_method_signature::args, describe_argument(), i, sm_method_argument::index, m_buf, sm_method_argument::next, NULL, and sm_method_signature::num_args.
Referenced by describe_method().
const char * object_printer::describe_trigger_action_time (const tr_trigger & trigger) static
Definition at line 929 of file object_printer.cpp.
References tr_trigger::action, NULL, tr_activity::time, tr_time_as_string(), and TR_TIME_NULL.
Referenced by trigger_description::init().
const char * object_printer::describe_trigger_condition_time (const tr_trigger & trigger) static
Definition at line 907 of file object_printer.cpp.
References tr_trigger::action, tr_trigger::condition, NULL, tr_activity::time, tr_time_as_string(), and TR_TIME_NULL.
Referenced by describe_class_trigger(), and trigger_description::init().
Member Data Documentation
string_buffer& object_printer::m_buf private
Definition at line 55 of file object_printer.hpp.
Referenced by describe_argument(), describe_attribute(), describe_class(), describe_class_trigger(), describe_comment(), describe_constraint(), describe_domain(), describe_identifier(), describe_method(), describe_method_file(), describe_partition_info(), describe_partition_parts(), describe_resolution(), and describe_signature().
The documentation for this class was generated from the following files:
src/object/object_printer.hpp
src/object/object_printer.cpp