CUBRID Engine: cubmonitor::counter_timer_statistic< A, T > Class Template Reference
cubmonitor::counter_timer_statistic< A, T > Class Template Reference
#include <monitor_collect.hpp>
Classes
class autotimer
Public Member Functions
counter_timer_statistic (void)
void time_and_increment (const time_rep &d, const amount_rep &a=1)
void time_and_increment (const amount_rep &a=1)
void reset_timer ()
std::size_t get_statistics_count (void) const
void fetch (statistic_value *destination, fetch_mode mode=FETCH_GLOBAL) const
amount_rep get_count (fetch_mode mode=FETCH_GLOBAL) const
time_rep get_time (fetch_mode mode=FETCH_GLOBAL) const
time_rep get_average_time (fetch_mode mode=FETCH_GLOBAL) const
void register_to_monitor (monitor &mon, const char *basename) const
Private Attributes
timer m_timer
A m_amount_statistic
T m_time_statistic
Detailed Description
template<class A = amount_accumulator_statistic, class T = time_accumulator_statistic>
class cubmonitor::counter_timer_statistic< A, T >
Definition at line 132 of file monitor_collect.hpp.
Constructor & Destructor Documentation
template<class A , class T > cubmonitor::counter_timer_statistic< A, T >::counter_timer_statistic (void) inline
Definition at line 315 of file monitor_collect.hpp.
Member Function Documentation
template<class A , class T > void cubmonitor::counter_timer_statistic< A, T >::fetch (statistic_value * destination, fetch_mode mode = FETCH_GLOBAL) const inline
Definition at line 354 of file monitor_collect.hpp.
References assert, cubmonitor::counter_timer_statistic< A, T >::get_statistics_count(), cubmonitor::counter_timer_statistic< A, T >::m_amount_statistic, and cubmonitor::counter_timer_statistic< A, T >::m_time_statistic.
Referenced by cubmonitor::counter_timer_statistic< A, T >::register_to_monitor().
template<class A , class T > time_rep cubmonitor::counter_timer_statistic< A, T >::get_average_time (fetch_mode mode = FETCH_GLOBAL) const inline
Definition at line 383 of file monitor_collect.hpp.
References cubmonitor::counter_timer_statistic< A, T >::get_count(), and cubmonitor::counter_timer_statistic< A, T >::get_time().
Referenced by cubmonitor::counter_timer_statistic< A, T >::register_to_monitor().
template<class A , class T > amount_rep cubmonitor::counter_timer_statistic< A, T >::get_count (fetch_mode mode = FETCH_GLOBAL) const inline
Definition at line 369 of file monitor_collect.hpp.
References cubmonitor::counter_timer_statistic< A, T >::m_amount_statistic.
Referenced by lockfree::hashmap< Key, T >::dump_stat(), and cubmonitor::counter_timer_statistic< A, T >::get_average_time().
template<class A , class T > std::size_t cubmonitor::counter_timer_statistic< A, T >::get_statistics_count (void) const inline
Definition at line 347 of file monitor_collect.hpp.
References cubmonitor::counter_timer_statistic< A, T >::m_amount_statistic, and cubmonitor::counter_timer_statistic< A, T >::m_time_statistic.
Referenced by cubmonitor::counter_timer_statistic< A, T >::fetch(), and cubmonitor::counter_timer_statistic< A, T >::register_to_monitor().
template<class A , class T > time_rep cubmonitor::counter_timer_statistic< A, T >::get_time (fetch_mode mode = FETCH_GLOBAL) const inline
Definition at line 376 of file monitor_collect.hpp.
References cubmonitor::counter_timer_statistic< A, T >::m_time_statistic.
Referenced by lockfree::hashmap< Key, T >::dump_stat(), and cubmonitor::counter_timer_statistic< A, T >::get_average_time().
template<class A , class T > void cubmonitor::counter_timer_statistic< A, T >::register_to_monitor (monitor & mon, const char * basename) const
Definition at line 390 of file monitor_collect.hpp.
References assert, cubmonitor::build_name_vector(), cubmonitor::counter_timer_statistic< A, T >::fetch(), fetch_func, cubmonitor::counter_timer_statistic< A, T >::get_average_time(), cubmonitor::counter_timer_statistic< A, T >::get_statistics_count(), mode, cubmonitor::monitor::register_statistics(), and cubmonitor::statistic_value_cast().
template<class A , class T > void cubmonitor::counter_timer_statistic< A, T >::reset_timer () inline
Definition at line 340 of file monitor_collect.hpp.
References cubmonitor::counter_timer_statistic< A, T >::m_timer, and cubmonitor::timer::reset().
Referenced by cubmonitor::counter_timer_statistic< A, T >::autotimer::autotimer().
template<class A , class T > void cubmonitor::counter_timer_statistic< A, T >::time_and_increment (const time_rep & d, const amount_rep & a = 1) inline
Definition at line 325 of file monitor_collect.hpp.
References cubmonitor::counter_timer_statistic< A, T >::m_amount_statistic, and cubmonitor::counter_timer_statistic< A, T >::m_time_statistic.
Referenced by cubmonitor::counter_timer_statistic< A, T >::time_and_increment(), and cubmonitor::counter_timer_statistic< A, T >::autotimer::~autotimer().
template<class A , class T > void cubmonitor::counter_timer_statistic< A, T >::time_and_increment (const amount_rep & a = 1) inline
Definition at line 333 of file monitor_collect.hpp.
References cubmonitor::counter_timer_statistic< A, T >::m_timer, cubmonitor::timer::time(), and cubmonitor::counter_timer_statistic< A, T >::time_and_increment().
Member Data Documentation
template<class A = amount_accumulator_statistic, class T = time_accumulator_statistic> A cubmonitor::counter_timer_statistic< A, T >::m_amount_statistic private
Definition at line 169 of file monitor_collect.hpp.
Referenced by cubmonitor::counter_timer_statistic< A, T >::fetch(), cubmonitor::counter_timer_statistic< A, T >::get_count(), cubmonitor::counter_timer_statistic< A, T >::get_statistics_count(), and cubmonitor::counter_timer_statistic< A, T >::time_and_increment().
template<class A = amount_accumulator_statistic, class T = time_accumulator_statistic> T cubmonitor::counter_timer_statistic< A, T >::m_time_statistic private
Definition at line 170 of file monitor_collect.hpp.
Referenced by cubmonitor::counter_timer_statistic< A, T >::fetch(), cubmonitor::counter_timer_statistic< A, T >::get_statistics_count(), cubmonitor::counter_timer_statistic< A, T >::get_time(), and cubmonitor::counter_timer_statistic< A, T >::time_and_increment().
template<class A = amount_accumulator_statistic, class T = time_accumulator_statistic> timer cubmonitor::counter_timer_statistic< A, T >::m_timer private
Definition at line 168 of file monitor_collect.hpp.
Referenced by cubmonitor::counter_timer_statistic< A, T >::reset_timer(), and cubmonitor::counter_timer_statistic< A, T >::time_and_increment().
The documentation for this class was generated from the following file:
src/monitor/monitor_collect.hpp