CUBRID Engine: cubperf::statset_definition Class Reference
cubperf::statset_definition Class Reference
#include <perf.hpp>
Public Member Functions
statset_definition (void)=delete
statset_definition (std::initializer_list< stat_definition > defs)
~statset_definition (void)
statset * create_statset (void) const
atomic_statset * create_atomic_statset (void) const
void increment (statset &statsetr, stat_id id, stat_value incr=1) const
void increment (atomic_statset &statsetr, stat_id id, stat_value incr=1) const
void time (statset &statsetr, stat_id id, duration d) const
void time (statset &statsetr, stat_id id) const
void time (atomic_statset &statsetr, stat_id id, duration d) const
void time (atomic_statset &statsetr, stat_id id) const
void time_and_increment (statset &statsetr, stat_id id, duration d, stat_value incr=1) const
void time_and_increment (statset &statsetr, stat_id id, stat_value incr=1) const
void time_and_increment (atomic_statset &statsetr, stat_id id, duration d, stat_value incr=1) const
void time_and_increment (atomic_statset &statsetr, stat_id id, stat_value incr=1) const
void get_stat_values (const statset &statsetr, stat_value *output_stats) const
void get_stat_values (const atomic_statset &statsetr, stat_value *output_stats) const
void add_stat_values (const statset &statsetr, stat_value *output_stats) const
void add_stat_values (const atomic_statset &statsetr, stat_value *output_stats) const
template<typename Duration >
void get_stat_values_with_converted_timers (const statset &statsetr, stat_value *output_stats) const
template<typename Duration >
void get_stat_values_with_converted_timers (const atomic_statset &statsetr, stat_value *output_stats) const
template<typename Duration >
void add_stat_values_with_converted_timers (const statset &statsetr, stat_value *output_stats) const
template<typename Duration >
void add_stat_values_with_converted_timers (const atomic_statset &statsetr, stat_value *output_stats) const
std::size_t get_stat_count () const
std::size_t get_value_count () const
const char * get_value_name (std::size_t value_index) const
std::size_t get_values_memsize (void) const
Private Member Functions
template<bool IsAtomic>
void generic_increment (generic_statset< IsAtomic > &statsetr, stat_id id, stat_value incr) const
template<bool IsAtomic>
void generic_time (generic_statset< IsAtomic > &statsetr, stat_id id, duration d) const
template<bool IsAtomic>
void generic_time (generic_statset< IsAtomic > &statsetr, stat_id id) const
template<bool IsAtomic>
void generic_time_and_increment (generic_statset< IsAtomic > &statsetr, stat_id id, stat_value incr, duration d) const
template<bool IsAtomic>
void generic_time_and_increment (generic_statset< IsAtomic > &statsetr, stat_id id, stat_value incr) const
template<typename Duration >
stat_value convert_timeval (stat_value nanosecs) const
template<bool IsAtomic, typename Duration >
void generic_get_stat_values_with_converted_timers (const generic_statset< IsAtomic > &statsetr, stat_value *output_stats) const
template<bool IsAtomic, typename Duration >
void generic_add_stat_values_with_converted_timers (const generic_statset< IsAtomic > &statsetr, stat_value *output_stats) const
Private Attributes
std::size_t m_stat_count
std::size_t m_value_count
stat_definition * m_stat_defs
std::string * m_value_names
Detailed Description
Definition at line 143 of file perf.hpp.
Constructor & Destructor Documentation
cubperf::statset_definition::statset_definition (void) delete
cubperf::statset_definition::statset_definition (std::initializer_list< stat_definition > defs)
Definition at line 84 of file perf.cpp.
References assert, cubperf::stat_definition::get_value_count(), cubperf::stat_definition::m_names, cubperf::stat_definition::m_offset, m_stat_count, m_stat_defs, m_value_count, and m_value_names.
cubperf::statset_definition::~statset_definition (void)
Definition at line 124 of file perf.cpp.
References m_stat_defs, and m_value_names.
Member Function Documentation
void cubperf::statset_definition::add_stat_values (const statset & statsetr, stat_value * output_stats) const
Definition at line 182 of file perf.cpp.
References get_value_count(), and cubperf::generic_statset< IsAtomic >::m_values.
void cubperf::statset_definition::add_stat_values (const atomic_statset & statsetr, stat_value * output_stats) const
Definition at line 191 of file perf.cpp.
References get_value_count(), and cubperf::generic_statset< IsAtomic >::m_values.
template<typename Duration > void cubperf::statset_definition::add_stat_values_with_converted_timers (const statset & statsetr, stat_value * output_stats) const
Definition at line 446 of file perf.hpp.
Referenced by cubthread::wp_worker_statset_accumulate().
template<typename Duration > void cubperf::statset_definition::add_stat_values_with_converted_timers (const atomic_statset & statsetr, stat_value * output_stats) const
Definition at line 453 of file perf.hpp.
template<typename Duration > stat_value cubperf::statset_definition::convert_timeval (stat_value nanosecs) const private
Definition at line 366 of file perf.hpp.
atomic_statset * cubperf::statset_definition::create_atomic_statset (void) const
Definition at line 137 of file perf.cpp.
References get_value_count().
statset * cubperf::statset_definition::create_statset (void) const
Definition at line 131 of file perf.cpp.
References get_value_count().
Referenced by cubthread::daemon::create_statset(), and cubthread::wp_worker_statset_create().
template<bool IsAtomic, typename Duration > void cubperf::statset_definition::generic_add_stat_values_with_converted_timers (const generic_statset< IsAtomic > & statsetr, stat_value * output_stats) const private
Definition at line 418 of file perf.hpp.
References assert, cubperf::stat_definition::COUNTER, cubperf::stat_definition::COUNTER_AND_TIMER, cubperf::stat_definition::m_type, cubperf::generic_statset< IsAtomic >::m_values, and cubperf::stat_definition::TIMER.
template<bool IsAtomic, typename Duration > void cubperf::statset_definition::generic_get_stat_values_with_converted_timers (const generic_statset< IsAtomic > & statsetr, stat_value * output_stats) const private
Definition at line 375 of file perf.hpp.
References assert, cubperf::stat_definition::COUNTER, cubperf::stat_definition::COUNTER_AND_TIMER, cubperf::stat_definition::m_type, cubperf::generic_statset< IsAtomic >::m_values, and cubperf::stat_definition::TIMER.
template<bool IsAtomic> void cubperf::statset_definition::generic_increment (generic_statset< IsAtomic > & statsetr, stat_id id, stat_value incr) const inline private
Definition at line 251 of file perf.hpp.
References assert, cubperf::stat_definition::m_type, and cubperf::generic_statset< IsAtomic >::m_values.
template<bool IsAtomic> void cubperf::statset_definition::generic_time (generic_statset< IsAtomic > & statsetr, stat_id id, duration d) const inline private
Definition at line 274 of file perf.hpp.
References assert, cubperf::stat_definition::m_type, and cubperf::generic_statset< IsAtomic >::m_values.
template<bool IsAtomic> void cubperf::statset_definition::generic_time (generic_statset< IsAtomic > & statsetr, stat_id id) const inline private
Definition at line 285 of file perf.hpp.
References cubperf::generic_statset< IsAtomic >::m_timept.
template<bool IsAtomic> void cubperf::statset_definition::generic_time_and_increment (generic_statset< IsAtomic > & statsetr, stat_id id, stat_value incr, duration d) const inline private
Definition at line 318 of file perf.hpp.
References assert, cubperf::stat_definition::m_type, and cubperf::generic_statset< IsAtomic >::m_values.
template<bool IsAtomic> void cubperf::statset_definition::generic_time_and_increment (generic_statset< IsAtomic > & statsetr, stat_id id, stat_value incr) const inline private
Definition at line 332 of file perf.hpp.
References cubperf::generic_statset< IsAtomic >::m_timept.
std::size_t cubperf::statset_definition::get_stat_count () const
Definition at line 143 of file perf.cpp.
References m_stat_count.
void cubperf::statset_definition::get_stat_values (const statset & statsetr, stat_value * output_stats) const
Definition at line 167 of file perf.cpp.
References get_values_memsize(), and cubperf::generic_statset< IsAtomic >::m_values.
void cubperf::statset_definition::get_stat_values (const atomic_statset & statsetr, stat_value * output_stats) const
Definition at line 173 of file perf.cpp.
References get_value_count(), and cubperf::generic_statset< IsAtomic >::m_values.
template<typename Duration > void cubperf::statset_definition::get_stat_values_with_converted_timers (const statset & statsetr, stat_value * output_stats) const
Definition at line 403 of file perf.hpp.
Referenced by cubthread::waiter::get_stats(), cubthread::daemon::get_stats(), and cubthread::looper::get_stats().
template<typename Duration > void cubperf::statset_definition::get_stat_values_with_converted_timers (const atomic_statset & statsetr, stat_value * output_stats) const
Definition at line 410 of file perf.hpp.
std::size_t cubperf::statset_definition::get_value_count (void) const
Definition at line 149 of file perf.cpp.
References m_value_count.
Referenced by add_stat_values(), create_atomic_statset(), create_statset(), cubthread::daemon::get_stat_name(), get_stat_values(), cubthread::daemon::get_stats(), cubthread::waiter::get_stats_value_count(), cubthread::daemon::get_stats_value_count(), cubthread::looper::get_stats_value_count(), get_values_memsize(), cubthread::wp_er_log_stats(), and cubthread::wp_worker_statset_get_count().
const char * cubperf::statset_definition::get_value_name (std::size_t value_index) const
Definition at line 155 of file perf.cpp.
References m_value_names.
Referenced by cubthread::waiter::get_stat_name(), cubthread::daemon::get_stat_name(), cubthread::looper::get_stat_name(), cubthread::wp_er_log_stats(), and cubthread::wp_worker_statset_get_name().
std::size_t cubperf::statset_definition::get_values_memsize (void) const
Definition at line 161 of file perf.cpp.
References get_value_count().
Referenced by get_stat_values().
void cubperf::statset_definition::increment (statset & statsetr, stat_id id, stat_value incr = 1) const inline
Definition at line 261 of file perf.hpp.
Referenced by cubthread::waiter::goto_sleep(), cubthread::looper::reset(), cubthread::waiter::wait_for(), cubthread::waiter::wait_until(), and cubthread::waiter::wakeup().
void cubperf::statset_definition::increment (atomic_statset & statsetr, stat_id id, stat_value incr = 1) const inline
Definition at line 267 of file perf.hpp.
void cubperf::statset_definition::time (statset & statsetr, stat_id id, duration d) const inline
Definition at line 293 of file perf.hpp.
Referenced by cubthread::daemon::register_stat_pause().
void cubperf::statset_definition::time (statset & statsetr, stat_id id) const inline
Definition at line 299 of file perf.hpp.
void cubperf::statset_definition::time (atomic_statset & statsetr, stat_id id, duration d) const inline
Definition at line 305 of file perf.hpp.
void cubperf::statset_definition::time (atomic_statset & statsetr, stat_id id) const inline
Definition at line 311 of file perf.hpp.
void cubperf::statset_definition::time_and_increment (statset & statsetr, stat_id id, duration d, stat_value incr = 1) const inline
Definition at line 340 of file perf.hpp.
Referenced by cubthread::looper::put_to_sleep(), cubthread::daemon::register_stat_execute(), cubthread::waiter::run(), and cubthread::wp_worker_statset_time_and_increment().
void cubperf::statset_definition::time_and_increment (statset & statsetr, stat_id id, stat_value incr = 1) const inline
Definition at line 346 of file perf.hpp.
void cubperf::statset_definition::time_and_increment (atomic_statset & statsetr, stat_id id, duration d, stat_value incr = 1) const inline
Definition at line 352 of file perf.hpp.
void cubperf::statset_definition::time_and_increment (atomic_statset & statsetr, stat_id id, stat_value incr = 1) const inline
Definition at line 359 of file perf.hpp.
Member Data Documentation
std::size_t cubperf::statset_definition::m_stat_count private
Definition at line 229 of file perf.hpp.
Referenced by get_stat_count(), and statset_definition().
stat_definition* cubperf::statset_definition::m_stat_defs private
Definition at line 231 of file perf.hpp.
Referenced by statset_definition(), and ~statset_definition().
std::size_t cubperf::statset_definition::m_value_count private
Definition at line 230 of file perf.hpp.
Referenced by get_value_count(), and statset_definition().
std::string* cubperf::statset_definition::m_value_names private
Definition at line 232 of file perf.hpp.
Referenced by get_value_name(), statset_definition(), and ~statset_definition().
The documentation for this class was generated from the following files:
src/base/perf.hpp
src/base/perf.cpp