CUBRID Engine: HL::SizeHeap< SuperHeap > Class Template Reference
HL::SizeHeap< SuperHeap > Class Template Reference
Allocates extra room for the size of an object.
#include <sizeheap.h>
Classes
struct freeObject
Public Types
enum { Alignment }
Public Member Functions
virtual ~SizeHeap (void)
void * malloc (size_t sz)
void free (void *ptr)
Static Public Member Functions
static size_t getSize (const void *ptr)
Private Types
enum { MAGIC_NUMBER = 0xCAFEBABE }
Static Private Member Functions
static void setSize (void *ptr, size_t sz)
static freeObject * getHeader (const void *ptr)
Detailed Description
template<class SuperHeap>
class HL::SizeHeap< SuperHeap >
Allocates extra room for the size of an object.
Definition at line 40 of file sizeheap.h.
Member Enumeration Documentation
template<class SuperHeap> anonymous enum private
Enumerator
MAGIC_NUMBER
Definition at line 49 of file sizeheap.h.
template<class SuperHeap> anonymous enum
Enumerator
Alignment
Definition at line 53 of file sizeheap.h.
Constructor & Destructor Documentation
template<class SuperHeap> virtual HL::SizeHeap< SuperHeap >::~SizeHeap (void) inline virtual
Definition at line 56 of file sizeheap.h.
Member Function Documentation
template<class SuperHeap> void HL::SizeHeap< SuperHeap >::free (void * ptr) inline
Definition at line 65 of file sizeheap.h.
Referenced by hl_ostk_free().
template<class SuperHeap> static freeObject* HL::SizeHeap< SuperHeap >::getHeader (const void * ptr) inline static private
Definition at line 89 of file sizeheap.h.
Referenced by HL::SizeHeap< ObstackHeap< 0, MallocHeap > >::free(), HL::SizeHeap< ObstackHeap< 0, MallocHeap > >::getSize(), and HL::SizeHeap< ObstackHeap< 0, MallocHeap > >::setSize().
template<class SuperHeap> static size_t HL::SizeHeap< SuperHeap >::getSize (const void * ptr) inline static
Definition at line 72 of file sizeheap.h.
template<class SuperHeap> void* HL::SizeHeap< SuperHeap >::malloc (size_t sz) inline
Definition at line 58 of file sizeheap.h.
Referenced by hl_ostk_alloc().
template<class SuperHeap> static void HL::SizeHeap< SuperHeap >::setSize (void * ptr, size_t sz) inline static private
Definition at line 84 of file sizeheap.h.
The documentation for this class was generated from the following file:
src/heaplayers/heaps/objectrep/sizeheap.h