CUBRID Engine: cubpacking::packable_object Class Reference
cubpacking::packable_object Class Reference abstract
#include <packable_object.hpp>
Public Member Functions
virtual ~packable_object ()
virtual size_t get_packed_size (packer &serializator, std::size_t start_offset=0) const =0
virtual void pack (packer &serializator) const =0
virtual void unpack (unpacker &deserializator)=0
virtual bool is_equal (const packable_object *other)
Detailed Description
Definition at line 33 of file packable_object.hpp.
Constructor & Destructor Documentation
virtual cubpacking::packable_object::~packable_object () inline virtual
Definition at line 36 of file packable_object.hpp.
References get_packed_size(), pack(), and unpack().
Member Function Documentation
virtual size_t cubpacking::packable_object::get_packed_size (packer & serializator, std::size_t start_offset = 0) const pure virtual
Implemented in cubload::load_status, cubload::stats, record_descriptor, boot_client_credential, cubload::load_args, clientids, and cubload::batch.
Referenced by cubpacking::packer::get_packed_size_overloaded(), and ~packable_object().
virtual bool cubpacking::packable_object::is_equal (const packable_object * other) inline virtual
Definition at line 43 of file packable_object.hpp.
virtual void cubpacking::packable_object::pack (packer & serializator) const pure virtual
Implemented in cubload::load_status, cubload::stats, record_descriptor, boot_client_credential, cubload::load_args, clientids, and cubload::batch.
Referenced by cubpacking::packer::pack_overloaded(), and ~packable_object().
virtual void cubpacking::packable_object::unpack (unpacker & deserializator) pure virtual
Implemented in cubload::load_status, cubload::stats, record_descriptor, boot_client_credential, cubload::load_args, clientids, and cubload::batch.
Referenced by cubpacking::unpacker::unpack_overloaded(), and ~packable_object().
The documentation for this class was generated from the following file:
src/base/packable_object.hpp