CUBRID Engine: cubsync::event_semaphore Class Reference
cubsync::event_semaphore Class Reference
#include <semaphore.hpp>
Public Member Functions
event_semaphore ()
void set ()
void clear ()
void wait ()
Private Attributes
semaphore< bool > m_semaphore
Detailed Description
Definition at line 78 of file semaphore.hpp.
Constructor & Destructor Documentation
cubsync::event_semaphore::event_semaphore () inline
Definition at line 85 of file semaphore.hpp.
Member Function Documentation
void cubsync::event_semaphore::clear (void) inline
Definition at line 95 of file semaphore.hpp.
References cubsync::semaphore< T >::signal().
void cubsync::event_semaphore::set () inline
Definition at line 90 of file semaphore.hpp.
References cubsync::semaphore< T >::signal().
void cubsync::event_semaphore::wait () inline
Definition at line 100 of file semaphore.hpp.
References cubsync::semaphore< T >::wait().
Member Data Documentation
semaphore<bool> cubsync::event_semaphore::m_semaphore private
Definition at line 81 of file semaphore.hpp.
The documentation for this class was generated from the following file:
src/base/semaphore.hpp