CUBRID Engine: src/transaction/client_credentials.cpp File Reference
client_credentials.cpp File Reference
#include "client_credentials.hpp"
#include "porting.h"
#include <algorithm>
Macros
#define CLIENTID_PACKER_ARGS(client_type_as_int) client_type_as_int, client_info, db_user, program_name, login_name, host_name, process_id
#define BOOTCLCRED_PACKER_ARGS db_name, db_password
Functions
static void string_ncopy (std::string &dest, const char *src, size_t max_size)
Macro Definition Documentation
#define BOOTCLCRED_PACKER_ARGS db_name, db_password
Definition at line 227 of file client_credentials.cpp.
Referenced by boot_client_credential::get_packed_size(), boot_client_credential::pack(), and boot_client_credential::unpack().
#define CLIENTID_PACKER_ARGS (client_type_as_int) client_type_as_int, client_info, db_user, program_name, login_name, host_name, process_id
Definition at line 171 of file client_credentials.cpp.
Referenced by clientids::get_packed_size(), clientids::pack(), and clientids::unpack().
Function Documentation
static void string_ncopy (std::string & dest, const char * src, size_t max_size) static
Definition at line 26 of file client_credentials.cpp.
References clientids::UNKNOWN_ID.
Referenced by clientids::set_client_info(), clientids::set_host_name(), clientids::set_login_name(), clientids::set_program_name(), and clientids::set_user().