CUBRID Engine: src/compat/cnv.h File Reference
cnv.h File Reference
#include "dbtype_def.h"
#include "condition_handler.h"
Functions
const char * db_string_value (const char *string, int str_size, const char *format, DB_VALUE *value)
const char * db_string_date (const char *date_string, const char *date_format, DB_DATE *the_date)
const char * db_string_double (const char *double_string, const char *double_format, double *the_double)
const char * db_string_float (const char *float_string, const char *float_format, float *the_float)
const char * db_string_integer (const char *integer_string, const char *integer_format, int *the_integer)
const char * db_string_bigint (const char *bitint_string, const char *bigint_format, DB_BIGINT *the_bigint)
const char * db_string_monetary (const char *monetary_string, const char *monetary_format, DB_MONETARY *the_monetary)
const char * db_string_short (const char *short_string, const char *short_format, short *the_short)
const char * db_string_time (const char *time_string, const char *time_format, DB_TIME *the_time)
int db_time_string (const DB_TIME *the_time, const char *time_format, char *string, int max_size)
const char * db_string_timestamp (const char *timestamp_string, const char *timestamp_format, DB_TIMESTAMP *the_time)
int db_timestamp_string (const DB_TIMESTAMP *the_timestamp, const char *timestamp_format, char *string, int max_size)
const char * db_string_datetime (const char *datetime_string, const char *datetime_format, DB_DATETIME *the_datetime)
int db_datetime_string (const DB_DATETIME *the_datetime, const char *datetime_format, char *string, int max_size)
const char * db_string_bit (const char *string, const char *bit_format, DB_VALUE *the_db_bit)
int db_bit_string (const DB_VALUE *the_db_bit, const char *bit_format, char *string, int max_size)
const char * db_string_numeric (const char *string, const char *numeric_format, DB_VALUE *the_numeric)
int db_numeric_string (const DB_VALUE *the_numeric, const char *numeric_format, char *string, int max_size)
void cnv_cleanup (void)
Function Documentation
void cnv_cleanup (void)
Definition at line 8692 of file cnv.c.
References assert, cnv_fmt_exit(), cnvutil_cleanup(), NULL, and thread_get_thread_entry_info().
Referenced by boot_client_all_finalize().
int db_bit_string (const DB_VALUE * the_db_bit, const char * bit_format, char * string, int max_size)
Definition at line 8575 of file cnv.c.
References assert, bfmt_new(), bfmt_print(), CNV_ER_FMT_BAD_TYPE, CNV_ERR_BAD_TYPE, co_signal(), CSECT_CNV_FMT_LEXER, csect_enter, csect_exit, DB_TYPE_BIGINT, DB_TYPE_BIT, DB_TYPE_BLOB, DB_TYPE_CHAR, DB_TYPE_CLOB, DB_TYPE_DATE, DB_TYPE_DATETIME, DB_TYPE_DB_VALUE, DB_TYPE_DOUBLE, DB_TYPE_ERROR, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_MONETARY, DB_TYPE_MULTISET, DB_TYPE_NCHAR, DB_TYPE_NULL, DB_TYPE_NUMERIC, DB_TYPE_OBJECT, DB_TYPE_OID, DB_TYPE_POINTER, DB_TYPE_SEQUENCE, DB_TYPE_SET, DB_TYPE_SHORT, DB_TYPE_STRING, DB_TYPE_SUB, DB_TYPE_TIME, DB_TYPE_TIMESTAMP, DB_TYPE_VARBIT, DB_TYPE_VARCHAR, DB_TYPE_VARIABLE, DB_TYPE_VARNCHAR, DB_TYPE_VOBJ, error(), FL_VALIDATE_BIT_STRING_FORMAT, FL_VALIDATE_DATE_FORMAT, FL_VALIDATE_FLOAT_FORMAT, FL_VALIDATE_INTEGER_FORMAT, FL_VALIDATE_MONETARY_FORMAT, FL_VALIDATE_TIME_FORMAT, FL_VALIDATE_TIMESTAMP_FORMAT, FT_BIT_STRING_FORMAT, FT_DATE_FORMAT, FT_FLOAT_FORMAT, FT_INTEGER_FORMAT, FT_MONETARY_FORMAT, FT_TIME_FORMAT, FT_TIMESTAMP_FORMAT, INF_WAIT, NO_ERROR, NULL, and pr_type_name().
Referenced by bit_to_string(), db_string_value(), and pt_dbval_to_value().
int db_datetime_string (const DB_DATETIME * the_datetime, const char * datetime_format, char * string, int max_size)
Definition at line 8425 of file cnv.c.
References adj_ar_append(), adj_ar_get_buffer(), assert, CNV_ER_FMT_STRING_TOO_LONG, CNV_ERR_STRING_TOO_LONG, cnv_fmt_analyze(), cnv_fmt_lex(), cnv_get_value_string_buffer(), co_signal(), CSECT_CNV_FMT_LEXER, csect_enter, csect_exit, db_date_encode(), db_date_weekday(), db_datetime_decode(), db_time_encode(), db_timestamp_encode_ses(), error(), FL_TIME_FORMAT, fmt_date_string(), fmt_time_string(), fmt_timestamp_string(), FT_AM_PM, FT_DATE, FT_HOUR, FT_MILLISECOND, FT_MINUTE, FT_MONTH, FT_MONTHDAY, FT_NONE, FT_PATTERN, FT_SECOND, FT_TIME, FT_TIMESTAMP, FT_WEEKDAY, FT_YEAR, FT_ZONE, INF_WAIT, local_am_pm_string(), NO_ERROR, NULL, strlen, and fmt_token::text.
Referenced by coerce_datetime_to_dbvalue(), and db_string_value().
int db_numeric_string (const DB_VALUE * the_numeric, const char * numeric_format, char * string, int max_size)
Definition at line 7317 of file cnv.c.
References assert, CSECT_CNV_FMT_LEXER, csect_enter, csect_exit, ffmt_new(), INF_WAIT, NO_ERROR, NULL, and num_fmt_print().
Referenced by db_string_value().
const char* db_string_bigint (const char * bitint_string, const char * bigint_format, DB_BIGINT * the_bigint)
Definition at line 7503 of file cnv.c.
References assert, bifmt_value(), CSECT_CNV_FMT_LEXER, csect_enter, csect_exit, ifmt_new(), INF_WAIT, NO_ERROR, and NULL.
Referenced by db_string_value().
const char* db_string_bit (const char * string, const char * bit_format, DB_VALUE * the_db_bit)
Definition at line 8549 of file cnv.c.
References assert, bfmt_new(), bfmt_value(), and NULL.
Referenced by db_string_value().
const char* db_string_date (const char * date_string, const char * date_format, DB_DATE * the_date)
Definition at line 7019 of file cnv.c.
References adj_ar_append(), adj_ar_get_buffer(), assert, CNV_ER_FMT_BAD_PATTERN, CNV_ER_FMT_STRING_TOO_LONG, CNV_ER_FMT_UNKNOWN_DATE, CNV_ERR_BAD_PATTERN, CNV_ERR_STRING_TOO_LONG, CNV_ERR_UNKNOWN_DATE, cnv_fmt_analyze(), cnv_fmt_lex(), cnv_fmt_next_token(), cnv_get_value_string_buffer(), co_signal(), CSECT_CNV_FMT_LEXER, csect_enter, csect_exit, db_date_decode(), db_date_encode(), db_date_weekday(), error(), FL_LOCAL_TIME, FL_TIME_FORMAT, fmt_date_string(), fmt_date_value(), FT_DATE, FT_MONTH, FT_MONTHDAY, FT_NONE, FT_PATTERN, FT_WEEKDAY, FT_YEAR, i, INF_WAIT, fmt_token::length, local_date_string(), NO_ERROR, NULL, strlen, fmt_token::text, tfmt_new(), and fmt_token::type.
const char* db_string_datetime (const char * datetime_string, const char * datetime_format, DB_DATETIME * the_datetime)
Definition at line 8273 of file cnv.c.
References assert, CNV_ER_FMT_BAD_HOUR, CNV_ER_FMT_BAD_PATTERN, CNV_ER_FMT_UNKNOWN_DATE, CNV_ERR_BAD_HOUR, CNV_ERR_BAD_PATTERN, CNV_ERR_UNKNOWN_DATE, cnv_fmt_analyze(), cnv_fmt_next_token(), co_signal(), db_date_decode(), db_datetime_decode(), db_datetime_encode(), error(), FL_LOCAL_TIME, fmt_date_value(), fmt_minute_value(), fmt_second_value(), fmt_time_value(), fmt_timestamp_value(), FT_AM_PM, FT_DATE, FT_HOUR, FT_MINUTE, FT_MONTH, FT_MONTHDAY, FT_NONE, FT_PATTERN, FT_SECOND, FT_TIME, FT_TIMESTAMP, FT_WEEKDAY, FT_YEAR, FT_ZONE, i, fmt_token::length, local_am_pm_value(), local_date_string(), min, NULL, strlen, fmt_token::text, tfmt_new(), and fmt_token::type.
const char* db_string_double (const char * double_string, const char * double_format, double * the_double)
Definition at line 7223 of file cnv.c.
References assert, CSECT_CNV_FMT_LEXER, csect_enter, csect_exit, db_string_numeric(), float_format_s::decimal, ffmt_new(), ffmt_value(), INF_WAIT, NO_ERROR, and NULL.
Referenced by db_string_value().
const char* db_string_float (const char * float_string, const char * float_format, float * the_float)
Definition at line 7357 of file cnv.c.
References assert, CNV_ER_FMT_FLOAT_OVERFLOW, CNV_ER_FMT_FLOAT_UNDERFLOW, CNV_ERR_FLOAT_OVERFLOW, CNV_ERR_FLOAT_UNDERFLOW, co_signal(), CSECT_CNV_FMT_LEXER, csect_enter, csect_exit, float_format_s::decimal, ffmt_new(), ffmt_value(), INF_WAIT, NO_ERROR, and NULL.
Referenced by db_string_value().
const char* db_string_integer (const char * integer_string, const char * integer_format, int * the_integer)
Definition at line 7443 of file cnv.c.
References assert, CSECT_CNV_FMT_LEXER, csect_enter, csect_exit, ifmt_new(), ifmt_value(), INF_WAIT, NO_ERROR, and NULL.
Referenced by db_string_value().
const char* db_string_monetary (const char * monetary_string, const char * monetary_format, DB_MONETARY * the_monetary)
Definition at line 7572 of file cnv.c.
References db_monetary::amount, assert, cnv_valid_currency(), CSECT_CNV_FMT_LEXER, csect_enter, csect_exit, INF_WAIT, mfmt_new(), mfmt_value(), NO_ERROR, NULL, and db_monetary::type.
Referenced by db_string_value().
const char* db_string_numeric (const char * string, const char * numeric_format, DB_VALUE * the_numeric)
Referenced by db_string_double(), and db_string_value().
const char* db_string_short (const char * short_string, const char * short_format, short * the_short)
Definition at line 7641 of file cnv.c.
References assert, CNV_ER_FMT_INTEGER_OVERFLOW, CNV_ER_FMT_INTEGER_UNDERFLOW, CNV_ERR_INTEGER_OVERFLOW, CNV_ERR_INTEGER_UNDERFLOW, co_signal(), CSECT_CNV_FMT_LEXER, csect_enter, csect_exit, DB_INT16_MAX, DB_INT16_MIN, ifmt_new(), ifmt_value(), INF_WAIT, NO_ERROR, and NULL.
Referenced by db_string_value().
const char* db_string_time (const char * time_string, const char * time_format, DB_TIME * the_time)
Definition at line 7730 of file cnv.c.
References assert, CNV_ER_FMT_BAD_HOUR, CNV_ER_FMT_BAD_PATTERN, CNV_ERR_BAD_HOUR, CNV_ERR_BAD_PATTERN, cnv_fmt_analyze(), cnv_fmt_next_token(), co_signal(), db_time_decode(), db_time_encode(), error(), FL_LOCAL_TIME, fmt_minute_value(), fmt_second_value(), fmt_time_value(), FT_AM_PM, FT_HOUR, FT_MINUTE, FT_NONE, FT_PATTERN, FT_SECOND, FT_TIME, FT_ZONE, i, fmt_token::length, local_am_pm_value(), min, NULL, strlen, fmt_token::text, tfmt_new(), and fmt_token::type.
const char* db_string_timestamp (const char * timestamp_string, const char * timestamp_format, DB_TIMESTAMP * the_time)
Definition at line 7950 of file cnv.c.
References assert, CNV_ER_FMT_BAD_HOUR, CNV_ER_FMT_BAD_PATTERN, CNV_ER_FMT_UNKNOWN_DATE, CNV_ERR_BAD_HOUR, CNV_ERR_BAD_PATTERN, CNV_ERR_UNKNOWN_DATE, cnv_fmt_analyze(), cnv_fmt_next_token(), co_signal(), db_date_decode(), db_date_encode(), db_time_decode(), db_time_encode(), db_timestamp_decode_ses(), db_timestamp_encode_ses(), error(), FL_LOCAL_TIME, fmt_date_value(), fmt_minute_value(), fmt_second_value(), fmt_time_value(), fmt_timestamp_value(), FT_AM_PM, FT_DATE, FT_HOUR, FT_MINUTE, FT_MONTH, FT_MONTHDAY, FT_NONE, FT_PATTERN, FT_SECOND, FT_TIME, FT_TIMESTAMP, FT_WEEKDAY, FT_YEAR, FT_ZONE, i, fmt_token::length, local_am_pm_value(), local_date_string(), min, NO_ERROR, NULL, strlen, fmt_token::text, tfmt_new(), and fmt_token::type.
const char* db_string_value (const char * string, int str_size, const char * format, DB_VALUE * value)
Definition at line 6501 of file cnv.c.
References assert, CNV_ER_FMT_BAD_NULL, CNV_ER_FMT_BAD_TYPE, CNV_ER_FMT_STRING_TOO_LONG, CNV_ERR_BAD_NULL, CNV_ERR_BAD_TYPE, CNV_ERR_STRING_TOO_LONG, cnv_valid_currency(), co_signal(), CSECT_CNV_FMT_LEXER, csect_enter, csect_exit, db_bit_string(), DB_CURRENCY_DEFAULT, db_datetime_string(), DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_get_bigint(), db_get_char(), db_get_date(), db_get_datetime(), db_get_double(), db_get_float(), db_get_int(), db_get_monetary(), db_get_nchar(), db_get_short(), db_get_time(), db_get_timestamp(), db_make_bigint(), db_make_char(), db_make_datetime(), db_make_double(), db_make_float(), db_make_int(), db_make_monetary(), db_make_nchar(), db_make_short(), db_make_timestamp(), db_make_varchar(), db_make_varnchar(), db_numeric_string(), db_string_bigint(), db_string_bit(), db_string_double(), db_string_float(), db_string_integer(), db_string_monetary(), db_string_numeric(), db_string_short(), db_string_to_date(), db_string_to_datetime(), db_string_to_time(), db_string_to_timestamp(), db_string_value(), db_time_string(), db_timestamp_string(), DB_TYPE_BIGINT, DB_TYPE_BIT, DB_TYPE_BLOB, DB_TYPE_CHAR, DB_TYPE_CLOB, DB_TYPE_DATE, DB_TYPE_DATETIME, DB_TYPE_DB_VALUE, DB_TYPE_DOUBLE, DB_TYPE_ERROR, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_MONETARY, DB_TYPE_MULTISET, DB_TYPE_NCHAR, DB_TYPE_NULL, DB_TYPE_NUMERIC, DB_TYPE_OBJECT, DB_TYPE_OID, DB_TYPE_POINTER, DB_TYPE_SEQUENCE, DB_TYPE_SET, DB_TYPE_SHORT, DB_TYPE_SUB, DB_TYPE_TIME, DB_TYPE_TIMESTAMP, DB_TYPE_VARBIT, DB_TYPE_VARCHAR, DB_TYPE_VARIABLE, DB_TYPE_VARNCHAR, DB_TYPE_VOBJ, db_value_domain_init(), DB_VALUE_DOMAIN_TYPE, db_value_get_monetary_currency(), db_value_put_encoded_date(), db_value_put_encoded_time(), DB_VALUE_TYPE, error(), INF_WAIT, intl_char_count(), LANG_SYS_CODESET, LANG_SYS_COLLATION, NO_ERROR, NULL, p, pr_type_name(), and strlen.
Referenced by coerce_char_to_dbvalue(), and db_string_value().
int db_time_string (const DB_TIME * the_time, const char * time_format, char * string, int max_size)
Definition at line 7847 of file cnv.c.
References adj_ar_append(), adj_ar_get_buffer(), assert, CNV_ER_FMT_STRING_TOO_LONG, CNV_ERR_STRING_TOO_LONG, cnv_fmt_analyze(), cnv_fmt_lex(), cnv_get_value_string_buffer(), co_signal(), CSECT_CNV_FMT_LEXER, csect_enter, csect_exit, error(), FL_TIME_FORMAT, fmt_time_string(), FT_AM_PM, FT_HOUR, FT_MINUTE, FT_NONE, FT_PATTERN, FT_SECOND, FT_TIME, FT_ZONE, INF_WAIT, local_am_pm_string(), NO_ERROR, NULL, strlen, and fmt_token::text.
Referenced by coerce_time_to_dbvalue(), and db_string_value().
int db_timestamp_string (const DB_TIMESTAMP * the_timestamp, const char * timestamp_format, char * string, int max_size)
Definition at line 8138 of file cnv.c.
References adj_ar_append(), adj_ar_get_buffer(), assert, CNV_ER_FMT_STRING_TOO_LONG, CNV_ERR_STRING_TOO_LONG, cnv_fmt_analyze(), cnv_fmt_lex(), cnv_get_value_string_buffer(), co_signal(), CSECT_CNV_FMT_LEXER, csect_enter, csect_exit, db_date_decode(), db_date_weekday(), db_time_decode(), db_timestamp_decode_ses(), error(), FL_TIME_FORMAT, fmt_date_string(), fmt_time_string(), fmt_timestamp_string(), FT_AM_PM, FT_DATE, FT_HOUR, FT_MINUTE, FT_MONTH, FT_MONTHDAY, FT_NONE, FT_PATTERN, FT_SECOND, FT_TIME, FT_TIMESTAMP, FT_WEEKDAY, FT_YEAR, FT_ZONE, INF_WAIT, local_am_pm_string(), NO_ERROR, NULL, strlen, and fmt_token::text.
Referenced by cnv_valid_currency(), coerce_timestamp_to_dbvalue(), and db_string_value().