CUBRID Engine: src/compat/cnvlex.c File Reference
cnvlex.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include "config.h"
#include "cnvlex.h"
#include "util_func.h"
Classes
struct yy_buffer_state
Macros
#define FLEX_SCANNER
#define const
#define YY_READ_BUF_SIZE 8192
#define YY_END_TOK 0
#define ECHO (void) fwrite((char *) yytext, yyleng, 1, yyout)
#define YY_INPUT(buf, result, max_size)
#define YY_NULL 0
#define yyterminate() return ((FMT_TOKEN_TYPE) YY_NULL)
#define YY_FATAL_ERROR(msg)
#define yywrap() 1
#define BEGIN yy_start = 1 + 2 *
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
#define YY_NEW_FILE
#define YY_DECL int yylex YY_PROTO((void))
#define YY_BREAK break;
#define YY_END_OF_BUFFER_CHAR 0
#define YY_BUF_SIZE (YY_READ_BUF_SIZE * 2) /* size of default input buffer */
#define YY_CHAR unsigned char
#define INITIAL 0
#define YY_PREFIX dbcnv
#define YY_READ_BUF_SIZE 512
#define YY_DECL FMT_TOKEN_TYPE cnv_fmt_lex(FMT_TOKEN *token)
#define YY_INPUT(buf, result, max) result = (*(buf) = *cnv_fmt__input)? (cnv_fmt__input++, 1) : YY_NULL;
#define YY_USER_ACTION
#define YY_USER_INIT
#define DB_FMT_LEX_RETURN(t)
#define SC_US_ENG_NUMBER 1
#define SC_KO_KR_NUMBER 3
#define SC_US_ENG_TIME 4
#define SC_KO_KR_TIME 6
#define SC_BIT_STRING 7
#define SC_INTEGER_FORMAT 8
#define SC_TIME_FORMAT 9
#define SC_BIT_STRING_FORMAT 10
#define SC_VALIDATE_DATE_FORMAT 11
#define SC_VALIDATE_FLOAT_FORMAT 12
#define SC_VALIDATE_INTEGER_FORMAT 13
#define SC_VALIDATE_MONETARY_FORMAT 14
#define SC_VALIDATE_TIME_FORMAT 15
#define SC_VALIDATE_TIMESTAMP_FORMAT 16
#define SC_VALIDATE_BIT_STRING_FORMAT 17
#define YY_RENAME(a) YY_GLUE(YY_PREFIX,a)
#define YY_GLUE(a, b) a ## b
#define yy_create_buffer YY_RENAME(create_buffer)
#define yy_delete_buffer YY_RENAME(delete_buffer)
#define yy_init_buffer YY_RENAME(init_buffer)
#define yy_load_buffer_state YY_RENAME(load_buffer_state)
#define yy_switch_to_buffer YY_RENAME(switch_to_buffer)
#define yy_empty_file YY_RENAME(empty_file)
#define yyin YY_RENAME(in)
#define yyleng YY_RENAME(leng)
#define yyout YY_RENAME(out)
#define yyrestart YY_RENAME(restart)
#define yytext YY_RENAME(text)
#define yyunput YY_RENAME(unput)
#define yy_flex_debug YY_RENAME(flex_debug)
#define yylex YY_RENAME(lex)
#define YY_DO_BEFORE_ACTION
#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
#define yyless(n)
#define unput(c) yyunput(c, yytext)
#define EOF_NOT_SEEN 0
#define EOF_PENDING 1
#define EOF_DONE 2
#define YY_CURRENT_BUFFER yy_current_buffer
#define YY_END_OF_BUFFER 98
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define yy_new_buffer yy_create_buffer
Typedefs
typedef struct yy_buffer_state * YY_BUFFER_STATE
typedef int yy_state_type
Functions
static int cnv_fmt_lex_start (FMT_LEX_MODE mode)
static yy_state_type yy_get_previous_state YY_PROTO ((void))
static yy_state_type yy_try_NUL_trans YY_PROTO ((yy_state_type current_state))
static void yyunput YY_PROTO ((YY_CHAR c, YY_CHAR *buf_ptr))
void yyrestart YY_PROTO ((FILE *input_file))
void yy_switch_to_buffer YY_PROTO ((YY_BUFFER_STATE new_buffer))
YY_BUFFER_STATE yy_create_buffer YY_PROTO ((FILE *file, int size))
void yy_delete_buffer YY_PROTO ((YY_BUFFER_STATE b))
void yy_init_buffer YY_PROTO ((YY_BUFFER_STATE b, FILE *file))
if (cnv_fmt__unlex &&yy_current_buffer->yy_eof_status!=EOF_DONE)
if (yy_init)
while (1)
static int yy_get_next_buffer ()
static yy_state_type yy_get_previous_state ()
static yy_state_type yy_try_NUL_trans (yy_state_type yy_current_state)
static void yyunput (YY_CHAR c, YY_CHAR *yy_bp)
static int input ()
void yyrestart (FILE *input_file)
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer)
void yy_load_buffer_state ()
YY_BUFFER_STATE yy_create_buffer (FILE *file, int size)
void yy_delete_buffer (YY_BUFFER_STATE b)
void yy_init_buffer (YY_BUFFER_STATE b, FILE *file)
void cnv_fmt_analyze (const char *instring, FMT_LEX_MODE mode)
void cnv_fmt_unlex ()
const char * cnv_fmt_next_token ()
FMT_LEX_MODE cnv_fmt_number_mode (INTL_ZONE zone)
FMT_LEX_MODE cnv_fmt_time_mode (INTL_ZONE zone)
void cnv_fmt_exit (void)
Variables
static int cnv_fmt__init = 0
static const char * cnv_fmt__input = NULL
static const char * cnv_fmt__next = NULL
static int cnv_fmt__unlex = 0
static FMT_LEX_MODE cnv_fmt__mode = FL_LOCAL_NUMBER
static YY_BUFFER_STATE yy_current_buffer
static YY_CHAR yy_hold_char
static int yy_n_chars
YY_CHAR * yytext
int yyleng
FILE * yyin
FILE * yyout
static const short int yy_accept [353]
static const YY_CHAR yy_ec [256]
static const YY_CHAR yy_meta [82]
static const short int yy_base [373]
static const short int yy_def [373]
static const short int yy_nxt [954]
static const short int yy_chk [954]
static yy_state_type yy_last_accepting_state
static YY_CHAR * yy_last_accepting_cpos
static YY_CHAR * yy_c_buf_p = (YY_CHAR *) 0
static int yy_init = 1
static int yy_start = 0
static int yy_did_buffer_switch_on_eof
YY_DECL
YY_CHAR * yy_cp
YY_CHAR * yy_bp
int yy_act
Macro Definition Documentation
#define BEGIN yy_start = 1 + 2 *
Definition at line 132 of file cnvlex.c.
#define const
Definition at line 77 of file cnvlex.c.
#define DB_FMT_LEX_RETURN (t)
Value:
token->type   = t; \
cnv_fmt__next  += yyleng; \
return t;
Definition at line 209 of file cnvlex.c.
Referenced by while().
#define ECHO (void) fwrite((char *) yytext, yyleng, 1, yyout)
Definition at line 98 of file cnvlex.c.
Referenced by while().
#define EOB_ACT_CONTINUE_SCAN 0
Definition at line 269 of file cnvlex.c.
Referenced by input(), while(), and yy_get_next_buffer().
#define EOB_ACT_END_OF_FILE 1
Definition at line 270 of file cnvlex.c.
Referenced by input(), while(), and yy_get_next_buffer().
#define EOB_ACT_LAST_MATCH 2
Definition at line 271 of file cnvlex.c.
Referenced by input(), while(), and yy_get_next_buffer().
#define EOF_DONE 2
Definition at line 304 of file cnvlex.c.
Referenced by yy_get_next_buffer().
#define EOF_NOT_SEEN 0
Definition at line 301 of file cnvlex.c.
Referenced by yy_get_next_buffer(), and yy_init_buffer().
#define EOF_PENDING 1
Definition at line 303 of file cnvlex.c.
Referenced by yy_get_next_buffer().
#define FLEX_SCANNER
Definition at line 26 of file cnvlex.c.
#define INITIAL 0
Definition at line 163 of file cnvlex.c.
Referenced by cnv_fmt_lex_start(), and while().
#define REJECT reject_used_but_not_detected
Definition at line 732 of file cnvlex.c.
#define SC_BIT_STRING 7
Definition at line 218 of file cnvlex.c.
Referenced by cnv_fmt_lex_start(), and while().
#define SC_BIT_STRING_FORMAT 10
Definition at line 221 of file cnvlex.c.
Referenced by cnv_fmt_lex_start(), and while().
#define SC_INTEGER_FORMAT 8
Definition at line 219 of file cnvlex.c.
Referenced by cnv_fmt_lex_start(), and while().
#define SC_KO_KR_NUMBER 3
Definition at line 215 of file cnvlex.c.
Referenced by cnv_fmt_lex_start(), and while().
#define SC_KO_KR_TIME 6
Definition at line 217 of file cnvlex.c.
Referenced by cnv_fmt_lex_start(), and while().
#define SC_TIME_FORMAT 9
Definition at line 220 of file cnvlex.c.
Referenced by cnv_fmt_lex_start(), and while().
#define SC_US_ENG_NUMBER 1
Definition at line 214 of file cnvlex.c.
Referenced by cnv_fmt_lex_start(), and while().
#define SC_US_ENG_TIME 4
Definition at line 216 of file cnvlex.c.
Referenced by cnv_fmt_lex_start(), and while().
#define SC_VALIDATE_BIT_STRING_FORMAT 17
Definition at line 228 of file cnvlex.c.
Referenced by cnv_fmt_lex_start(), and while().
#define SC_VALIDATE_DATE_FORMAT 11
Definition at line 222 of file cnvlex.c.
Referenced by cnv_fmt_lex_start(), and while().
#define SC_VALIDATE_FLOAT_FORMAT 12
Definition at line 223 of file cnvlex.c.
Referenced by cnv_fmt_lex_start(), and while().
#define SC_VALIDATE_INTEGER_FORMAT 13
Definition at line 224 of file cnvlex.c.
Referenced by cnv_fmt_lex_start(), and while().
#define SC_VALIDATE_MONETARY_FORMAT 14
Definition at line 225 of file cnvlex.c.
Referenced by cnv_fmt_lex_start(), and while().
#define SC_VALIDATE_TIME_FORMAT 15
Definition at line 226 of file cnvlex.c.
Referenced by cnv_fmt_lex_start(), and while().
#define SC_VALIDATE_TIMESTAMP_FORMAT 16
Definition at line 227 of file cnvlex.c.
Referenced by cnv_fmt_lex_start(), and while().
#define unput (c) yyunput(c, yytext)
Definition at line 284 of file cnvlex.c.
Referenced by if().
#define YY_BREAK break;
Definition at line 152 of file cnvlex.c.
Referenced by while().
#define YY_BUF_SIZE (YY_READ_BUF_SIZE * 2) /* size of default input buffer */
Definition at line 157 of file cnvlex.c.
Referenced by if().
#define YY_CHAR unsigned char
Definition at line 162 of file cnvlex.c.
Referenced by input(), while(), yy_create_buffer(), yy_get_next_buffer(), yy_get_previous_state(), yy_try_NUL_trans(), and yyunput().
#define yy_create_buffer YY_RENAME(create_buffer)
Definition at line 243 of file cnvlex.c.
Referenced by if(), and yy_load_buffer_state().
#define YY_CURRENT_BUFFER yy_current_buffer
Definition at line 313 of file cnvlex.c.
Referenced by cnv_fmt_exit().
#define YY_DECL int yylex YY_PROTO((void))
Definition at line 188 of file cnvlex.c.
#define YY_DECL FMT_TOKEN_TYPE cnv_fmt_lex(FMT_TOKEN *token)
Definition at line 188 of file cnvlex.c.
#define yy_delete_buffer YY_RENAME(delete_buffer)
Definition at line 244 of file cnvlex.c.
Referenced by cnv_fmt_exit(), and yy_create_buffer().
#define YY_DO_BEFORE_ACTION
Value:
yytext = yy_bp; \
    yyleng = (int)(yy_cp - yy_bp); \
    yy_hold_char = *yy_cp; \
    *yy_cp = '\0'; \
    yy_c_buf_p = yy_cp;
Definition at line 262 of file cnvlex.c.
Referenced by while(), and yyunput().
#define yy_empty_file YY_RENAME(empty_file)
Definition at line 248 of file cnvlex.c.
#define YY_END_OF_BUFFER 98
Definition at line 335 of file cnvlex.c.
Referenced by while().
#define YY_END_OF_BUFFER_CHAR 0
Definition at line 154 of file cnvlex.c.
Referenced by input(), yy_get_next_buffer(), and yy_init_buffer().
#define YY_END_TOK 0
Definition at line 90 of file cnvlex.c.
#define YY_FATAL_ERROR (msg)
Value:
do                  \
          {                 \
        (void) fputs( msg, stderr ); \
        (void) putc( '\n', stderr ); \
        exit( 1 );  \
      }                 \
    while ( 0 )
Definition at line 116 of file cnvlex.c.
Referenced by input(), while(), yy_create_buffer(), yy_get_next_buffer(), and yyunput().
#define yy_flex_debug YY_RENAME(flex_debug)
Definition at line 255 of file cnvlex.c.
#define YY_GLUE (a, b) a ## b
Definition at line 240 of file cnvlex.c.
#define yy_init_buffer YY_RENAME(init_buffer)
Definition at line 245 of file cnvlex.c.
Referenced by if(), yy_create_buffer(), yy_delete_buffer(), and yyrestart().
#define YY_INPUT (buf, result, max_size)
Value:
if ((result = read(fileno(yyin), (char *) buf, max_size)) < 0) \
        YY_FATAL_ERROR( "read() in flex scanner failed" );
Definition at line 192 of file cnvlex.c.
Referenced by yy_get_next_buffer().
#define YY_INPUT (buf, result, max) result = (*(buf) = *cnv_fmt__input)? (cnv_fmt__input++, 1) : YY_NULL;
Definition at line 192 of file cnvlex.c.
#define yy_load_buffer_state YY_RENAME(load_buffer_state)
Definition at line 246 of file cnvlex.c.
Referenced by if(), yy_switch_to_buffer(), and yyrestart().
#define YY_MORE_ADJ 0
Definition at line 734 of file cnvlex.c.
Referenced by input(), while(), and yy_get_previous_state().
#define yy_new_buffer yy_create_buffer
Definition at line 760 of file cnvlex.c.
#define YY_NEW_FILE
Value:
do          \
      {         \
        yy_init_buffer( yy_current_buffer, yyin ); \
        yy_load_buffer_state();                    \
      }         \
    while ( 0 )
Definition at line 138 of file cnvlex.c.
Referenced by input(), and while().
#define YY_NULL 0
Definition at line 106 of file cnvlex.c.
#define YY_PREFIX dbcnv
Definition at line 171 of file cnvlex.c.
#define YY_READ_BUF_SIZE 8192
Definition at line 185 of file cnvlex.c.
Referenced by yy_get_next_buffer().
#define YY_READ_BUF_SIZE 512
Definition at line 185 of file cnvlex.c.
#define YY_RENAME (a) YY_GLUE(YY_PREFIX,a)
Definition at line 239 of file cnvlex.c.
#define YY_STATE_EOF (state) (YY_END_OF_BUFFER + state + 1)
Definition at line 135 of file cnvlex.c.
Referenced by while().
#define yy_switch_to_buffer YY_RENAME(switch_to_buffer)
Definition at line 247 of file cnvlex.c.
Referenced by yyrestart().
#define YY_USER_ACTION
Value:
token->text   = token->raw_text = (const char *)yytext; \
token->length = yyleng;
Definition at line 196 of file cnvlex.c.
Referenced by while().
#define YY_USER_INIT
Value:
if(!cnv_fmt__init) { \
  atexit( cnv_fmt_exit); \
  cnv_fmt__init = 1; \
  } \
BEGIN(cnv_fmt_lex_start(cnv_fmt__mode));
Definition at line 201 of file cnvlex.c.
Referenced by if().
#define yyin YY_RENAME(in)
Definition at line 249 of file cnvlex.c.
Referenced by if(), and yy_load_buffer_state().
#define yyleng YY_RENAME(leng)
Definition at line 250 of file cnvlex.c.
Referenced by if().
#define yyless (n)
Value:
do        \
          {       \
        /* undo effects of setting up yytext */ \
        *yy_cp = yy_hold_char;                  \
        yy_c_buf_p = yy_cp = yy_bp + n;         \
        YY_DO_BEFORE_ACTION; /* set up yytext again */ \
          }       \
    while ( 0 )
Definition at line 274 of file cnvlex.c.
#define yylex YY_RENAME(lex)
Definition at line 256 of file cnvlex.c.
#define yymore () yymore_used_but_not_detected
Definition at line 733 of file cnvlex.c.
#define yyout YY_RENAME(out)
Definition at line 251 of file cnvlex.c.
Referenced by if().
#define yyrestart YY_RENAME(restart)
Definition at line 252 of file cnvlex.c.
Referenced by input().
#define yyterminate () return ((FMT_TOKEN_TYPE) YY_NULL)
Definition at line 112 of file cnvlex.c.
Referenced by while().
#define yytext YY_RENAME(text)
Definition at line 253 of file cnvlex.c.
Referenced by if(), input(), while(), yy_get_next_buffer(), yy_get_previous_state(), and yy_load_buffer_state().
#define yyunput YY_RENAME(unput)
Definition at line 254 of file cnvlex.c.
Referenced by yy_try_NUL_trans().
#define yywrap () 1
Definition at line 126 of file cnvlex.c.
Referenced by input(), and while().
Typedef Documentation
typedef struct yy_buffer_state* YY_BUFFER_STATE
Definition at line 160 of file cnvlex.c.
typedef int yy_state_type
Definition at line 336 of file cnvlex.c.
Function Documentation
void cnv_fmt_analyze (const char * instring, FMT_LEX_MODE mode)
Definition at line 1869 of file cnvlex.c.
References assert, cnv_fmt__input, cnv_fmt__mode, cnv_fmt__next, cnv_fmt__unlex, mode, and yy_init.
Referenced by bfmt_new(), bfmt_print(), bfmt_value(), bifmt_numeric_value(), cnv_bad_char(), db_datetime_string(), db_string_date(), db_string_datetime(), db_string_time(), db_string_timestamp(), db_time_string(), db_timestamp_string(), ffmt_value(), fmt_fractional_value(), fmt_time_value(), fmt_timestamp_value(), ifmt_new(), ifmt_numeric_value(), ko_time_value(), mfmt_value(), num_fmt_print(), tfmt_new(), and us_time_value().
void cnv_fmt_exit (void)
Definition at line 1995 of file cnvlex.c.
References NULL, YY_CURRENT_BUFFER, and yy_delete_buffer.
Referenced by cnv_cleanup().
static int cnv_fmt_lex_start (FMT_LEX_MODE mode) static
Definition at line 1904 of file cnvlex.c.
References cnv_fmt_number_mode(), cnv_fmt_time_mode(), FL_BIT_STRING, FL_BIT_STRING_FORMAT, FL_INTEGER_FORMAT, FL_KO_KR_NUMBER, FL_KO_KR_TIME, FL_LOCAL_NUMBER, FL_LOCAL_TIME, FL_TIME_FORMAT, FL_US_ENG_NUMBER, FL_US_ENG_TIME, FL_VALIDATE_BIT_STRING_FORMAT, FL_VALIDATE_DATE_FORMAT, FL_VALIDATE_FLOAT_FORMAT, FL_VALIDATE_INTEGER_FORMAT, FL_VALIDATE_MONETARY_FORMAT, FL_VALIDATE_TIME_FORMAT, FL_VALIDATE_TIMESTAMP_FORMAT, INITIAL, SC_BIT_STRING, SC_BIT_STRING_FORMAT, SC_INTEGER_FORMAT, SC_KO_KR_NUMBER, SC_KO_KR_TIME, SC_TIME_FORMAT, SC_US_ENG_NUMBER, SC_US_ENG_TIME, SC_VALIDATE_BIT_STRING_FORMAT, SC_VALIDATE_DATE_FORMAT, SC_VALIDATE_FLOAT_FORMAT, SC_VALIDATE_INTEGER_FORMAT, SC_VALIDATE_MONETARY_FORMAT, SC_VALIDATE_TIME_FORMAT, and SC_VALIDATE_TIMESTAMP_FORMAT.
const char* cnv_fmt_next_token (void)
Definition at line 1893 of file cnvlex.c.
References cnv_fmt__next.
Referenced by bfmt_print(), bfmt_value(), bifmt_numeric_value(), db_string_date(), db_string_datetime(), db_string_time(), db_string_timestamp(), ffmt_value(), fmt_fractional_value(), fmt_time_value(), fmt_timestamp_value(), ifmt_numeric_value(), ko_time_value(), mfmt_value(), num_fmt_print(), and us_time_value().
FMT_LEX_MODE cnv_fmt_number_mode (INTL_ZONE zone)
Definition at line 1928 of file cnvlex.c.
References assert, FL_KO_KR_NUMBER, FL_US_ENG_NUMBER, INTL_ZONE_KR, INTL_ZONE_US, and mode.
Referenced by cnv_fmt_lex_start(), and mfmt_new().
FMT_LEX_MODE cnv_fmt_time_mode (INTL_ZONE zone)
Definition at line 1962 of file cnvlex.c.
References assert, FL_KO_KR_TIME, FL_US_ENG_TIME, INTL_ZONE_KR, INTL_ZONE_US, and mode.
Referenced by cnv_fmt_lex_start().
void cnv_fmt_unlex (void)
Definition at line 1883 of file cnvlex.c.
References cnv_fmt__unlex.
Referenced by bfmt_print(), fmt_fractional_digits(), and fmt_integral_digits().
if (cnv_fmt__unlex &&yy_current_buffer->yy_eof_status! = EOF_DONE)
Definition at line 776 of file cnvlex.c.
References cnv_fmt__next, cnv_fmt__unlex, i, unput, yyleng, and yytext.
if (yy_init)
Definition at line 793 of file cnvlex.c.
References YY_BUF_SIZE, yy_create_buffer, yy_init, yy_init_buffer, yy_load_buffer_state, yy_start, YY_USER_INIT, yyin, and yyout.
static int input () static
Definition at line 1661 of file cnvlex.c.
References EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, yy_c_buf_p, yy_buffer_state::yy_ch_buf, YY_CHAR, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, yy_get_next_buffer(), yy_hold_char, YY_MORE_ADJ, yy_buffer_state::yy_n_chars, YY_NEW_FILE, yyrestart, yytext, and yywrap.
Referenced by check_server(), is_javasp_running(), is_manager_running(), and process_master().
while (1)
Definition at line 816 of file cnvlex.c.
References cnv_fmt__input, cnv_fmt__next, DB_FMT_LEX_RETURN, ECHO, EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, FT_AM_PM, FT_BINARY_DIGITS, FT_BIT_STRING_FORMAT, FT_CURRENCY, FT_DATE, FT_DATE_FORMAT, FT_DATE_SEPARATOR, FT_DECIMAL, FT_FLOAT_FORMAT, FT_HEX_DIGITS, FT_HOUR, FT_INTEGER_FORMAT, FT_LOCAL_DATE_SEPARATOR, FT_MINUS, FT_MINUTE, FT_MONETARY_FORMAT, FT_MONTH, FT_MONTH_LONG, FT_MONTHDAY, FT_NONE, FT_NUMBER, FT_PATTERN, FT_PLUS, FT_SECOND, FT_STARS, FT_THOUSANDS, FT_TIME, FT_TIME_DIGITS, FT_TIME_DIGITS_0, FT_TIME_DIGITS_ANY, FT_TIME_DIGITS_BLANK, FT_TIME_FORMAT, FT_TIME_SEPARATOR, FT_TIMESTAMP, FT_TIMESTAMP_FORMAT, FT_UNKNOWN, FT_WEEKDAY, FT_WEEKDAY_LONG, FT_YEAR, FT_ZEROES, FT_ZONE, INITIAL, SC_BIT_STRING, SC_BIT_STRING_FORMAT, SC_INTEGER_FORMAT, SC_KO_KR_NUMBER, SC_KO_KR_TIME, SC_TIME_FORMAT, SC_US_ENG_NUMBER, SC_US_ENG_TIME, SC_VALIDATE_BIT_STRING_FORMAT, SC_VALIDATE_DATE_FORMAT, SC_VALIDATE_FLOAT_FORMAT, SC_VALIDATE_INTEGER_FORMAT, SC_VALIDATE_MONETARY_FORMAT, SC_VALIDATE_TIME_FORMAT, SC_VALIDATE_TIMESTAMP_FORMAT, yy_accept, yy_base, YY_BREAK, yy_c_buf_p, yy_buffer_state::yy_ch_buf, YY_CHAR, yy_chk, yy_cp, yy_def, yy_did_buffer_switch_on_eof, YY_DO_BEFORE_ACTION, yy_ec, YY_END_OF_BUFFER, YY_FATAL_ERROR, yy_get_next_buffer(), yy_get_previous_state(), yy_hold_char, yy_last_accepting_cpos, yy_last_accepting_state, yy_meta, YY_MORE_ADJ, yy_buffer_state::yy_n_chars, YY_NEW_FILE, yy_nxt, yy_start, YY_STATE_EOF, yy_try_NUL_trans(), YY_USER_ACTION, yyterminate, yytext, and yywrap.
Referenced by do_prepare_delete(), es_ht_find_symbol(), fileio_read_backup(), fileio_read_restore(), fileio_write_backup(), lang_str_utf8_trail_zero_weights(), overflow_get_capacity(), overflow_get_nbytes(), sp_get_int_bind_value(), and sp_get_string_bind_value().
YY_BUFFER_STATE yy_create_buffer (FILE * file, int size)
Definition at line 1788 of file cnvlex.c.
References yy_buffer_state::yy_buf_size, yy_buffer_state::yy_ch_buf, YY_CHAR, yy_delete_buffer, YY_FATAL_ERROR, and yy_init_buffer.
void yy_delete_buffer (YY_BUFFER_STATE b)
Definition at line 1820 of file cnvlex.c.
References yy_init_buffer.
static int yy_get_next_buffer () static
Definition at line 1472 of file cnvlex.c.
References EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, EOF_DONE, EOF_NOT_SEEN, EOF_PENDING, i, yy_buffer_state::yy_buf_size, yy_c_buf_p, yy_buffer_state::yy_ch_buf, YY_CHAR, YY_END_OF_BUFFER_CHAR, yy_buffer_state::yy_eof_status, YY_FATAL_ERROR, YY_INPUT, yy_buffer_state::yy_n_chars, YY_READ_BUF_SIZE, and yytext.
Referenced by input(), and while().
static yy_state_type yy_get_previous_state () static
Definition at line 1547 of file cnvlex.c.
References yy_accept, yy_base, yy_c_buf_p, YY_CHAR, yy_chk, yy_cp, yy_def, yy_ec, yy_last_accepting_cpos, yy_last_accepting_state, yy_meta, YY_MORE_ADJ, yy_nxt, yy_start, yy_try_NUL_trans(), and yytext.
Referenced by while().
void yy_init_buffer (YY_BUFFER_STATE b, FILE * file)
Definition at line 1838 of file cnvlex.c.
References EOF_NOT_SEEN, YY_END_OF_BUFFER_CHAR, and yy_buffer_state::yy_input_file.
void yy_load_buffer_state ()
Definition at line 1773 of file cnvlex.c.
References yy_buffer_state::yy_buf_pos, yy_c_buf_p, yy_create_buffer, yy_hold_char, yy_buffer_state::yy_input_file, yy_buffer_state::yy_n_chars, yyin, and yytext.
static int input YY_PROTO ((void)) static
static yy_state_type yy_try_NUL_trans YY_PROTO ((yy_state_type current_state)) static
static void yyunput YY_PROTO ((YY_CHAR c, YY_CHAR *buf_ptr)) static
void yyrestart YY_PROTO ((FILE *input_file))
void yy_switch_to_buffer YY_PROTO ((YY_BUFFER_STATE new_buffer))
YY_BUFFER_STATE yy_create_buffer YY_PROTO ((FILE *file, int size))
void yy_delete_buffer YY_PROTO ((YY_BUFFER_STATE b))
void yy_init_buffer YY_PROTO ((YY_BUFFER_STATE b, FILE *file))
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer)
Definition at line 1743 of file cnvlex.c.
References yy_buffer_state::yy_buf_pos, yy_c_buf_p, yy_did_buffer_switch_on_eof, yy_hold_char, yy_load_buffer_state, and yy_buffer_state::yy_n_chars.
static yy_state_type yy_try_NUL_trans (yy_state_type yy_current_state) static
Definition at line 1586 of file cnvlex.c.
References yy_accept, yy_base, yy_c_buf_p, YY_CHAR, yy_chk, yy_cp, yy_def, yy_last_accepting_cpos, yy_last_accepting_state, yy_meta, yy_nxt, and yyunput.
Referenced by while(), and yy_get_previous_state().
void yyrestart (FILE * input_file)
Definition at line 1728 of file cnvlex.c.
References yy_init_buffer, yy_load_buffer_state, and yy_switch_to_buffer.
static void yyunput (YY_CHAR c, YY_CHAR * yy_bp) static
Definition at line 1618 of file cnvlex.c.
References yy_buffer_state::yy_buf_size, yy_c_buf_p, yy_buffer_state::yy_ch_buf, YY_CHAR, YY_DO_BEFORE_ACTION, YY_FATAL_ERROR, yy_hold_char, and yy_buffer_state::yy_n_chars.
Variable Documentation
int cnv_fmt__init = 0 static
Definition at line 178 of file cnvlex.c.
const char* cnv_fmt__input = NULL static
Definition at line 179 of file cnvlex.c.
Referenced by cnv_fmt_analyze(), and while().
FMT_LEX_MODE cnv_fmt__mode = FL_LOCAL_NUMBER static
Definition at line 182 of file cnvlex.c.
Referenced by cnv_fmt_analyze().
const char* cnv_fmt__next = NULL static
Definition at line 180 of file cnvlex.c.
Referenced by cnv_fmt_analyze(), cnv_fmt_next_token(), if(), and while().
int cnv_fmt__unlex = 0 static
Definition at line 181 of file cnvlex.c.
Referenced by cnv_fmt_analyze(), cnv_fmt_unlex(), and if().
const short int yy_accept[353] static
Definition at line 337 of file cnvlex.c.
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
int yy_act
Definition at line 772 of file cnvlex.c.
const short int yy_base[373] static
Definition at line 422 of file cnvlex.c.
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
YY_CHAR * yy_bp
Definition at line 771 of file cnvlex.c.
YY_CHAR* yy_c_buf_p = (YY_CHAR *) 0 static
Definition at line 740 of file cnvlex.c.
Referenced by input(), while(), yy_get_next_buffer(), yy_get_previous_state(), yy_load_buffer_state(), yy_switch_to_buffer(), yy_try_NUL_trans(), and yyunput().
const short int yy_chk[954] static
Definition at line 618 of file cnvlex.c.
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
YY_CHAR* yy_cp
Definition at line 771 of file cnvlex.c.
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
YY_BUFFER_STATE yy_current_buffer static
Definition at line 307 of file cnvlex.c.
YY_DECL
Initial value:
{
  yy_state_type yy_current_state
Definition at line 769 of file cnvlex.c.
const short int yy_def[373] static
Definition at line 466 of file cnvlex.c.
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
int yy_did_buffer_switch_on_eof static
Definition at line 747 of file cnvlex.c.
Referenced by while(), and yy_switch_to_buffer().
const YY_CHAR yy_ec[256] static
Initial value:
= { 0,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 3, 1, 1, 1, 4, 5, 1, 1, 6,
  7, 8, 9, 10, 11, 12, 13, 14, 15, 16,
  16, 16, 16, 16, 16, 16, 17, 18, 1, 1,
  1, 1, 1, 1, 19, 20, 21, 22, 23, 24,
  1, 25, 26, 27, 1, 1, 28, 29, 30, 31,
  1, 32, 33, 34, 1, 1, 35, 36, 37, 38,
  1, 39, 1, 1, 1, 1, 40, 41, 42, 43,
  44, 45, 46, 47, 48, 1, 26, 49, 50, 51,
  52, 53, 1, 54, 55, 56, 57, 58, 59, 60,
  61, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 62, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 63, 1, 1, 1, 64, 1, 65, 1,
  1, 1, 1, 66, 1, 1, 1, 67, 1, 1,
  68, 69, 1, 1, 1, 70, 71, 1, 1, 72,
  1, 1, 1, 1, 1, 1, 73, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 74,
  75, 1, 1, 1, 1, 76, 1, 77, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  78, 1, 1, 1, 1, 79, 1, 1, 80, 1,
  1, 81, 1, 1, 1
}
Definition at line 379 of file cnvlex.c.
Referenced by while(), and yy_get_previous_state().
YY_CHAR yy_hold_char static
Definition at line 317 of file cnvlex.c.
Referenced by input(), while(), yy_load_buffer_state(), yy_switch_to_buffer(), and yyunput().
int yy_init = 1 static
Definition at line 741 of file cnvlex.c.
Referenced by cnv_fmt_analyze(), and if().
YY_CHAR* yy_last_accepting_cpos static
Definition at line 727 of file cnvlex.c.
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
yy_state_type yy_last_accepting_state static
Definition at line 726 of file cnvlex.c.
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
const YY_CHAR yy_meta[82] static
Initial value:
= { 0,
  1, 1, 1, 1, 2, 1, 1, 1, 1, 1,
  1, 1, 1, 3, 3, 3, 3, 1, 4, 4,
  5, 4, 4, 3, 6, 6, 1, 6, 1, 1,
  1, 6, 6, 6, 1, 7, 8, 6, 9, 4,
  4, 5, 4, 4, 3, 1, 1, 1, 6, 8,
  1, 1, 6, 6, 1, 1, 1, 1, 8, 8,
  8, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1
}
Definition at line 410 of file cnvlex.c.
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
int yy_n_chars static
Definition at line 319 of file cnvlex.c.
const short int yy_nxt[954] static
Definition at line 510 of file cnvlex.c.
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
int yy_start = 0 static
Definition at line 742 of file cnvlex.c.
Referenced by if(), while(), and yy_get_previous_state().
FILE* yyin
Definition at line 333 of file cnvlex.c.
int yyleng
Definition at line 332 of file cnvlex.c.
FILE * yyout
Definition at line 333 of file cnvlex.c.
YY_CHAR* yytext
Definition at line 331 of file cnvlex.c.