CUBRID Engine: src/compat/cnvlex.h File Reference
cnvlex.h File Reference
#include "intl_support.h"
Classes
struct fmt_token
Typedefs
typedef struct fmt_token FMT_TOKEN
Enumerations
enum FMT_LEX_MODE {
FL_LOCAL_NUMBER = 0, FL_US_ENG_NUMBER = 1, FL_KO_KR_NUMBER = 2, FL_LOCAL_TIME = 3,
FL_US_ENG_TIME = 4, FL_KO_KR_TIME = 5, FL_INTEGER_FORMAT = 6, FL_TIME_FORMAT = 7,
FL_BIT_STRING_FORMAT = 8, FL_BIT_STRING = 9, FL_VALIDATE_DATE_FORMAT = 10, FL_VALIDATE_FLOAT_FORMAT = 11,
FL_VALIDATE_INTEGER_FORMAT = 12, FL_VALIDATE_MONETARY_FORMAT = 13, FL_VALIDATE_TIME_FORMAT = 14, FL_VALIDATE_TIMESTAMP_FORMAT = 15,
FL_VALIDATE_BIT_STRING_FORMAT = 16
}
enum FMT_TOKEN_TYPE {
FT_NONE = 0, FT_AM_PM = 1, FT_BLANKS = 2, FT_BINARY_DIGITS = 3,
FT_BIT_STRING_FORMAT = 4, FT_CURRENCY = 5, FT_DATE = 6, FT_DATE_FORMAT = 7,
FT_DATE_SEPARATOR = 8, FT_LOCAL_DATE_SEPARATOR = 9, FT_DECIMAL = 10, FT_FLOAT_FORMAT = 11,
FT_HOUR = 12, FT_HEX_DIGITS = 13, FT_INTEGER_FORMAT = 14, FT_MINUS = 15,
FT_MINUTE = 16, FT_MONETARY_FORMAT = 17, FT_MONTH = 18, FT_MONTHDAY = 19,
FT_MONTH_LONG = 20, FT_NUMBER = 21, FT_PATTERN = 22, FT_PLUS = 23,
FT_SECOND = 24, FT_SPACES = 25, FT_STARS = 26, FT_THOUSANDS = 27,
FT_TIME = 28, FT_TIME_DIGITS = 29, FT_TIME_DIGITS_ANY = 30, FT_TIME_DIGITS_0 = 31,
FT_TIME_DIGITS_BLANK = 32, FT_TIME_FORMAT = 33, FT_TIME_SEPARATOR = 34, FT_LOCAL_TIME_SEPARATOR = 35,
FT_UNKNOWN = 36, FT_TIMESTAMP = 37, FT_TIMESTAMP_FORMAT = 38, FT_WEEKDAY = 39,
FT_WEEKDAY_LONG = 40, FT_YEAR = 41, FT_ZEROES = 42, FT_ZONE = 43,
FT_MILLISECOND = 44
}
Functions
void cnv_fmt_analyze (const char *instring, FMT_LEX_MODE mode)
FMT_TOKEN_TYPE cnv_fmt_lex (FMT_TOKEN *token)
void cnv_fmt_unlex (void)
const char * cnv_fmt_next_token (void)
FMT_LEX_MODE cnv_fmt_number_mode (INTL_ZONE zone)
FMT_LEX_MODE cnv_fmt_time_mode (INTL_ZONE zone)
void cnv_fmt_exit (void)
Typedef Documentation
typedef struct fmt_token FMT_TOKEN
Definition at line 108 of file cnvlex.h.
Enumeration Type Documentation
enum FMT_LEX_MODE
Enumerator
FL_LOCAL_NUMBER
FL_US_ENG_NUMBER
FL_KO_KR_NUMBER
FL_LOCAL_TIME
FL_US_ENG_TIME
FL_KO_KR_TIME
FL_INTEGER_FORMAT
FL_TIME_FORMAT
FL_BIT_STRING_FORMAT
FL_BIT_STRING
FL_VALIDATE_DATE_FORMAT
FL_VALIDATE_FLOAT_FORMAT
FL_VALIDATE_INTEGER_FORMAT
FL_VALIDATE_MONETARY_FORMAT
FL_VALIDATE_TIME_FORMAT
FL_VALIDATE_TIMESTAMP_FORMAT
FL_VALIDATE_BIT_STRING_FORMAT
Definition at line 37 of file cnvlex.h.
enum FMT_TOKEN_TYPE
Enumerator
FT_NONE
FT_AM_PM
FT_BLANKS
FT_BINARY_DIGITS
FT_BIT_STRING_FORMAT
FT_CURRENCY
FT_DATE
FT_DATE_FORMAT
FT_DATE_SEPARATOR
FT_LOCAL_DATE_SEPARATOR
FT_DECIMAL
FT_FLOAT_FORMAT
FT_HOUR
FT_HEX_DIGITS
FT_INTEGER_FORMAT
FT_MINUS
FT_MINUTE
FT_MONETARY_FORMAT
FT_MONTH
FT_MONTHDAY
FT_MONTH_LONG
FT_NUMBER
FT_PATTERN
FT_PLUS
FT_SECOND
FT_SPACES
FT_STARS
FT_THOUSANDS
FT_TIME
FT_TIME_DIGITS
FT_TIME_DIGITS_ANY
FT_TIME_DIGITS_0
FT_TIME_DIGITS_BLANK
FT_TIME_FORMAT
FT_TIME_SEPARATOR
FT_LOCAL_TIME_SEPARATOR
FT_UNKNOWN
FT_TIMESTAMP
FT_TIMESTAMP_FORMAT
FT_WEEKDAY
FT_WEEKDAY_LONG
FT_YEAR
FT_ZEROES
FT_ZONE
FT_MILLISECOND
Definition at line 59 of file cnvlex.h.
Function Documentation
void cnv_fmt_analyze (const char * instring, FMT_LEX_MODE mode)
Definition at line 1869 of file cnvlex.c.
References assert, cnv_fmt__input, cnv_fmt__mode, cnv_fmt__next, cnv_fmt__unlex, mode, and yy_init.
Referenced by bfmt_new(), bfmt_print(), bfmt_value(), bifmt_numeric_value(), cnv_bad_char(), db_datetime_string(), db_string_date(), db_string_datetime(), db_string_time(), db_string_timestamp(), db_time_string(), db_timestamp_string(), ffmt_value(), fmt_fractional_value(), fmt_time_value(), fmt_timestamp_value(), ifmt_new(), ifmt_numeric_value(), ko_time_value(), mfmt_value(), num_fmt_print(), tfmt_new(), and us_time_value().
void cnv_fmt_exit (void)
Definition at line 1995 of file cnvlex.c.
References NULL, YY_CURRENT_BUFFER, and yy_delete_buffer.
Referenced by cnv_cleanup().
FMT_TOKEN_TYPE cnv_fmt_lex (FMT_TOKEN * token)
Referenced by bfmt_new(), bfmt_print(), bfmt_value(), bifmt_numeric_value(), cnv_bad_char(), db_datetime_string(), db_string_date(), db_time_string(), db_timestamp_string(), ffmt_value(), fmt_date_value(), fmt_fractional_digits(), fmt_fractional_value(), fmt_integral_digits(), fmt_minute_value(), fmt_second_value(), fmt_time_value(), ifmt_new(), ifmt_numeric_value(), ko_date_value(), ko_time_value(), local_am_pm_value(), mfmt_value(), num_fmt_print(), tfmt_new(), us_date_value(), and us_time_value().
const char* cnv_fmt_next_token (void)
Definition at line 1893 of file cnvlex.c.
References cnv_fmt__next.
Referenced by bfmt_print(), bfmt_value(), bifmt_numeric_value(), db_string_date(), db_string_datetime(), db_string_time(), db_string_timestamp(), ffmt_value(), fmt_fractional_value(), fmt_time_value(), fmt_timestamp_value(), ifmt_numeric_value(), ko_time_value(), mfmt_value(), num_fmt_print(), and us_time_value().
FMT_LEX_MODE cnv_fmt_number_mode (INTL_ZONE zone)
Definition at line 1928 of file cnvlex.c.
References assert, FL_KO_KR_NUMBER, FL_US_ENG_NUMBER, INTL_ZONE_KR, INTL_ZONE_US, and mode.
Referenced by cnv_fmt_lex_start(), and mfmt_new().
FMT_LEX_MODE cnv_fmt_time_mode (INTL_ZONE zone)
Definition at line 1962 of file cnvlex.c.
References assert, FL_KO_KR_TIME, FL_US_ENG_TIME, INTL_ZONE_KR, INTL_ZONE_US, and mode.
Referenced by cnv_fmt_lex_start().
void cnv_fmt_unlex (void)
Definition at line 1883 of file cnvlex.c.
References cnv_fmt__unlex.
Referenced by bfmt_print(), fmt_fractional_digits(), and fmt_integral_digits().