CUBRID Engine: src/executables/compactdb_common.c File Reference
compactdb_common.c File Reference
#include "config.h"
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <assert.h>
#include "porting.h"
#include "dbtype.h"
#include "load_object.h"
#include "db.h"
#include "locator_cl.h"
#include "schema_manager.h"
#include "object_accessor.h"
#include "set_object.h"
#include "message_catalog.h"
#include "network_interface_cl.h"
#include "server_interface.h"
#include "system_parameter.h"
#include "utility.h"
#include "authenticate.h"
#include "transaction_cl.h"
#include "execute_schema.h"
#include "object_primitive.h"
Functions
int get_class_mops (char **class_names, int num_class, MOP **class_list, int *num_class_list)
int get_class_mops_from_file (const char *input_filename, MOP **class_list, int *num_class_mops)
static int get_num_requested_class (const char *input_filename, int *num_class)
Function Documentation
int get_class_mops (char ** class_names, int num_class, MOP ** class_list, int * num_class_list)
Definition at line 93 of file compactdb_common.c.
References COMPACTDB_MSG_CLASS, COMPACTDB_MSG_INVALID_CLASS, DB_SIZEOF, ER_FAILED, error(), i, locator_find_class(), MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_SET_COMPACTDB, NO_ERROR, NULL, sm_downcase_name(), SM_MAX_IDENTIFIER_LENGTH, and strlen.
Referenced by compactdb_start(), and get_class_mops_from_file().
int get_class_mops_from_file (const char * input_filename, MOP ** class_list, int * num_class_mops)
Definition at line 165 of file compactdb_common.c.
References CAST_BUFLEN, DB_MAX_IDENTIFIER_LENGTH, DB_SIZEOF, ER_FAILED, free_and_init, get_class_mops(), get_num_requested_class(), i, NO_ERROR, NULL, and strlen.
Referenced by compactdb_start().
static int get_num_requested_class (const char * input_filename, int * num_class) static
Definition at line 56 of file compactdb_common.c.
References DB_MAX_IDENTIFIER_LENGTH, ER_FAILED, NO_ERROR, and NULL.
Referenced by get_class_mops_from_file().