CUBRID Engine: src/base/condition_handler.h File Reference
condition_handler.h File Reference
#include <stdio.h>
#include <stdarg.h>
Enumerations
enum CO_SEVERITY { CO_ERROR_SEVERITY, CO_FATAL_SEVERITY, CO_WARNING_SEVERITY }
enum CO_DETAIL { CO_DETAIL_USER = 1, CO_DETAIL_DBA, CO_DETAIL_DEBUG, CO_DETAIL_MAX }
Functions
int co_signal (int code, const char *format,...)
int co_code (void)
void co_final (void)
Enumeration Type Documentation
enum CO_DETAIL
Enumerator
CO_DETAIL_USER
CO_DETAIL_DBA
CO_DETAIL_DEBUG
CO_DETAIL_MAX
Definition at line 45 of file condition_handler.h.
enum CO_SEVERITY
Enumerator
CO_ERROR_SEVERITY
CO_FATAL_SEVERITY
CO_WARNING_SEVERITY
Definition at line 34 of file condition_handler.h.
Function Documentation
int co_code (void)
Definition at line 367 of file condition_handler.c.
References co_Current_code, co_Current_detail, CO_DETAIL_MAX, CO_ER_FMT_BAD_DETAIL, CO_ERR_BAD_DETAIL, co_signal(), and error().
Referenced by bifmt_numeric_value(), co_signal(), ffmt_value(), and mfmt_value().
void co_final (void)
Definition at line 411 of file condition_handler.c.
References adj_ar_free(), and NULL.
Referenced by boot_client_all_finalize().
int co_signal (int code, const char * format, ...)
Definition at line 136 of file condition_handler.c.
References ADJ_AR_EOA, adj_ar_get_buffer(), adj_ar_replace(), assert, co_code(), co_conversion_spec(), CO_ERROR_SEVERITY, CO_FATAL_SEVERITY, co_find_conversion(), CO_MAX_CODE, co_Message_completed, co_signalv(), error(), FORMAT_LITERAL, intl_mbs_len(), intl_mbs_nth(), intl_mbs_spn(), MB_LEN_MAX, NULL, REPORT_LINE_INDENT, REPORT_LINE_WIDTH, SPACE, and strlen.
Referenced by bfmt_print(), bifmt_numeric_value(), cnv_bad_char(), cnv_valid_currency(), co_code(), co_signalv(), db_bit_string(), db_datetime_string(), db_string_date(), db_string_datetime(), db_string_float(), db_string_short(), db_string_time(), db_string_timestamp(), db_string_value(), db_time_string(), db_timestamp_string(), ffmt_value(), fmt_date_value(), fmt_fractional_digits(), fmt_fractional_value(), fmt_integral_digits(), fmt_integral_value(), fmt_minute_value(), fmt_second_value(), fmt_time_value(), fmt_timestamp_value(), ifmt_numeric_value(), ko_date_value(), ko_time_value(), local_am_pm_value(), mfmt_value(), num_fmt_print(), us_date_value(), and us_time_value().