CUBRID Engine: src/connection/connection_list_sr.c File Reference
connection_list_sr.c File Reference
#include "config.h"
#include <stdio.h>
#include <netinet/in.h>
#include <poll.h>
#include <string.h>
#include <malloc.h>
#include <memory.h>
#include <errno.h>
#include <assert.h>
#include "connection_list_sr.h"
#include "connection_error.h"
Functions
int css_initialize_list (CSS_LIST *list, int free_count)
int css_finalize_list (CSS_LIST *list)
int css_add_list (CSS_LIST *list, void *item)
void * css_remove_list_from_head (CSS_LIST *list)
int css_traverse_list (CSS_LIST *list, int(*func)(void *, void *), void *arg)
Function Documentation
int css_add_list (CSS_LIST * list, void * item)
Definition at line 161 of file connection_list_sr.c.
References assert, css_list::back, css_list::count, css_traverse_list(), css_list_entry::data, ER_CSS_ALLOC, css_list::free_count, css_list::free_list, css_list::front, css_list_entry::next, NO_ERROR, NULL, TRAV_CONT, and TRAV_STOP_DELETE.
Referenced by css_add_queue_entry(), and css_add_wait_queue_entry().
int css_finalize_list (CSS_LIST * list)
Definition at line 121 of file connection_list_sr.c.
References assert, css_list::count, free_and_init, css_list::free_count, css_list::free_list, css_list_entry::next, NO_ERROR, and NULL.
Referenced by css_shutdown_conn().
int css_initialize_list (CSS_LIST * list, int free_count)
Definition at line 83 of file connection_list_sr.c.
References assert, css_list::back, css_list::count, ER_CSS_ALLOC, css_list::free_count, free_count, css_list::free_list, css_list::front, i, css_list_entry::next, NO_ERROR, and NULL.
Referenced by css_initialize_conn().
void* css_remove_list_from_head (CSS_LIST * list)
Definition at line 277 of file connection_list_sr.c.
References css_list::back, css_list::count, css_list_entry::data, css_list::free_count, css_list::free_list, css_list::front, css_list_entry::next, and NULL.
Referenced by css_return_queued_request().
int css_traverse_list (CSS_LIST * list, int(*)(void *, void *) func, void * arg)
Definition at line 311 of file connection_list_sr.c.
References css_list::back, css_list::count, css_list_entry::data, ER_CSS_INVALID_RETURN_VALUE, css_list::free_count, css_list::free_list, css_list::front, css_list_entry::next, NO_ERROR, NULL, TRAV_CONT, TRAV_CONT_DELETE, TRAV_STOP, and TRAV_STOP_DELETE.
Referenced by css_add_list(), css_find_and_remove_queue_entry(), css_find_and_remove_wait_queue_entry(), css_find_queue_entry(), and css_remove_all_unexpected_packets().