CUBRID Engine: src/connection/connection_globals.c File Reference
connection_globals.c File Reference
#include "config.h"
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include "porting.h"
#include "memory_alloc.h"
#include "boot.h"
#include "connection_globals.h"
#include "utility.h"
#include "system_parameter.h"
Functions
static int css_get_normal_client_max_conn (void)
static int css_get_admin_client_max_conn (void)
static int css_get_ha_client_max_conn (void)
static bool css_is_normal_client (BOOT_CLIENT_TYPE client_type)
static bool css_is_admin_client (BOOT_CLIENT_TYPE client_type)
static bool css_is_ha_client (BOOT_CLIENT_TYPE client_type)
static int css_get_required_conn_num_for_ha (void)
void css_init_conn_rules (void)
int css_get_max_conn (void)
Variables
const char * css_Service_name = "cubrid"
int css_Service_id = 1523
SOCKET css_Pipe_to_master = INVALID_SOCKET
int css_Server_inhibit_connection_socket = 0
SOCKET css_Server_connection_socket = INVALID_SOCKET
int css_Server_use_new_connection_protocol = 0
char css_Net_magic [CSS_NET_MAGIC_SIZE] = { 0x00, 0x00, 0x00, 0x01, 0x20, 0x08, 0x11, 0x22 }
static bool css_Is_conn_rules_initialized = false
CSS_CONN_RULE_INFO css_Conn_rules []
const int css_Conn_rules_size = DIM (css_Conn_rules)
Function Documentation
static int css_get_admin_client_max_conn (void) static
Definition at line 95 of file connection_globals.c.
static int css_get_ha_client_max_conn (void) static
Definition at line 105 of file connection_globals.c.
References css_get_required_conn_num_for_ha().
int css_get_max_conn (void)
Definition at line 224 of file connection_globals.c.
References css_Conn_rules_size, css_init_conn_rules(), css_Is_conn_rules_initialized, i, and css_conn_rule_info::max_num_conn.
Referenced by css_init(), and css_init_conn_list().
static int css_get_normal_client_max_conn (void) static
Definition at line 85 of file connection_globals.c.
References prm_get_integer_value(), and PRM_ID_CSS_MAX_CLIENTS.
static int css_get_required_conn_num_for_ha (void) static
Definition at line 160 of file connection_globals.c.
References HA_GET_MODE, HA_MODE_OFF, HA_MODE_REPLICA, NULL, prm_get_string_value(), PRM_ID_HA_NODE_LIST, PRM_ID_HA_REPLICA_LIST, util_get_ha_mode_for_sa_utils(), and util_get_num_of_ha_nodes().
Referenced by css_get_ha_client_max_conn().
void css_init_conn_rules (void)
Definition at line 203 of file connection_globals.c.
References assert, css_Conn_rules_size, css_Is_conn_rules_initialized, css_conn_rule_info::get_max_conn_num_fn, i, css_conn_rule_info::max_num_conn, and NULL.
Referenced by css_get_max_conn(), and css_init_conn_list().
static bool css_is_admin_client (BOOT_CLIENT_TYPE client_type) static
Definition at line 139 of file connection_globals.c.
References BOOT_ADMIN_CLIENT_TYPE.
static bool css_is_ha_client (BOOT_CLIENT_TYPE client_type) static
Definition at line 149 of file connection_globals.c.
References BOOT_LOG_REPLICATOR_TYPE.
static bool css_is_normal_client (BOOT_CLIENT_TYPE client_type) static
Definition at line 115 of file connection_globals.c.
References css_Conn_rules_size, CSS_CR_NORMAL_ONLY_IDX, and i.
Variable Documentation
CSS_CONN_RULE_INFO css_Conn_rules[]
Initial value:
= {
  {css_is_normal_client, css_get_normal_client_max_conn, CR_NORMAL_ONLY, 0, 0},
  {css_is_admin_client, css_get_admin_client_max_conn, CR_NORMAL_FIRST, 0, 0},
  {css_is_ha_client, css_get_ha_client_max_conn, CR_RESERVED_FIRST, 0, 0}
}
Definition at line 72 of file connection_globals.c.
Referenced by css_decrement_num_conn(), css_decrement_num_conn_internal(), css_increment_num_conn(), and css_increment_num_conn_internal().
const int css_Conn_rules_size = DIM (css_Conn_rules)
Definition at line 78 of file connection_globals.c.
Referenced by css_decrement_num_conn(), css_decrement_num_conn_internal(), css_get_max_conn(), css_increment_num_conn(), css_init_conn_rules(), and css_is_normal_client().
bool css_Is_conn_rules_initialized = false static
Definition at line 60 of file connection_globals.c.
Referenced by css_get_max_conn(), and css_init_conn_rules().
char css_Net_magic[CSS_NET_MAGIC_SIZE] = { 0x00, 0x00, 0x00, 0x01, 0x20, 0x08, 0x11, 0x22 }
Definition at line 58 of file connection_globals.c.
Referenced by css_check_magic_with_socket(), and css_send_magic_with_socket().
SOCKET css_Pipe_to_master = INVALID_SOCKET
Definition at line 44 of file connection_globals.c.
Referenced by css_block_all_active_conn(), css_close_connection_to_master(), css_init(), css_master_thread(), css_reestablish_connection_to_master(), and css_setup_server_loop().
SOCKET css_Server_connection_socket = INVALID_SOCKET
Definition at line 48 of file connection_globals.c.
Referenced by css_close_server_connection_socket(), css_init(), css_is_shutdown_timeout_expired(), css_master_thread(), and css_open_server_connection_socket().
int css_Server_inhibit_connection_socket = 0
Definition at line 47 of file connection_globals.c.
Referenced by css_connect_to_master_server().
int css_Server_use_new_connection_protocol = 0
Definition at line 54 of file connection_globals.c.
Referenced by css_connect_to_master_server().
int css_Service_id = 1523
Definition at line 42 of file connection_globals.c.
Referenced by css_client_init(), css_connect_to_master_server(), and css_server_connect().
const char* css_Service_name = "cubrid"
Definition at line 41 of file connection_globals.c.