CUBRID Engine: src/connection/connection_list_cl.h File Reference
connection_list_cl.h File Reference
#include "connection_defs.h"
Functions
void css_queue_unexpected_data_packet (CSS_CONN_ENTRY *conn, unsigned short request_id, char *header, int size, int rc)
void css_queue_unexpected_error_packet (CSS_CONN_ENTRY *conn, unsigned short request_id, char *header, int size, int rc)
void css_queue_unexpected_packet (int type, CSS_CONN_ENTRY *conn, unsigned short request_id, NET_HEADER *header, int size)
int css_queue_user_data_buffer (CSS_CONN_ENTRY *conn, unsigned short request_id, int size, char *buffer)
CSS_QUEUE_ENTRY * css_find_queue_entry (CSS_QUEUE_ENTRY *header, unsigned int key)
void css_queue_remove_header_entry_ptr (CSS_QUEUE_ENTRY **anchor, CSS_QUEUE_ENTRY *entry)
void css_queue_remove_header_entry (CSS_QUEUE_ENTRY **anchor, unsigned short request_id)
void css_queue_remove_header (CSS_QUEUE_ENTRY **anchor)
Function Documentation
CSS_QUEUE_ENTRY* css_find_queue_entry (CSS_QUEUE_ENTRY * header, unsigned int key)
Definition at line 117 of file connection_list_cl.c.
References css_queue_entry::key, css_queue_entry::next, and NULL.
Referenced by css_connect_to_cubrid_server(), css_is_request_aborted(), css_is_valid_request_id(), css_process_abort_packet(), css_return_data_buffer(), css_return_queued_data(), and css_return_queued_error().
void css_queue_remove_header (CSS_QUEUE_ENTRY ** anchor)
Definition at line 183 of file connection_list_cl.c.
References css_free_queue_entry(), css_queue_entry::next, and NULL.
Referenced by css_remove_all_unexpected_packets().
void css_queue_remove_header_entry (CSS_QUEUE_ENTRY ** anchor, unsigned short request_id)
Definition at line 220 of file connection_list_cl.c.
References css_free_queue_entry(), css_queue_entry::key, css_queue_entry::next, and NULL.
Referenced by css_process_abort_packet(), and css_return_queued_request().
void css_queue_remove_header_entry_ptr (CSS_QUEUE_ENTRY ** anchor, CSS_QUEUE_ENTRY * entry)
Definition at line 261 of file connection_list_cl.c.
References assert, css_free_queue_entry(), css_queue_entry::next, and NULL.
Referenced by css_connect_to_cubrid_server(), css_return_data_buffer(), css_return_queued_data(), and css_return_queued_error().
void css_queue_unexpected_data_packet (CSS_CONN_ENTRY * conn, unsigned short request_id, char * header, int size, int rc)
Definition at line 385 of file connection_list_cl.c.
References css_queue_packet(), and css_conn_entry::data_queue.
Referenced by css_queue_data_packet(), and css_receive_data().
void css_queue_unexpected_error_packet (CSS_CONN_ENTRY * conn, unsigned short request_id, char * header, int size, int rc)
Definition at line 435 of file connection_list_cl.c.
References css_queue_packet(), and css_conn_entry::error_queue.
Referenced by css_queue_error_packet(), and css_receive_error().
void css_queue_unexpected_packet (int type, CSS_CONN_ENTRY * conn, unsigned short request_id, NET_HEADER * header, int size)
Definition at line 551 of file connection_list_cl.c.
References ABORT_TYPE, CLOSE_TYPE, COMMAND_TYPE, css_process_abort_packet(), css_process_close_packet(), css_queue_command_packet(), css_queue_data_packet(), css_queue_error_packet(), DATA_TYPE, packet_header::db_error, css_conn_entry::db_error, ERROR_TYPE, packet_header::flags, css_conn_entry::invalidate_snapshot, NET_HEADER_FLAG_INVALIDATE_SNAPSHOT, ntohl(), ntohs(), TPRINTF, and packet_header::transaction_id.
Referenced by css_read_one_request(), css_receive_data(), and css_receive_error().
int css_queue_user_data_buffer (CSS_CONN_ENTRY * conn, unsigned short request_id, int size, char * buffer)
Definition at line 342 of file connection_list_cl.c.