CUBRID Engine: src/connection/connection_sr.h File Reference
connection_sr.h File Reference
#include "connection_defs.h"
#include "connection_support.h"
#include "critical_section.h"
#include "error_manager.h"
#include "porting.h"
#include "thread_compat.hpp"
#include <assert.h>
#include <pthread.h>
Classes
struct ip_info
Macros
#define IP_BYTE_COUNT 5
#define CSS_RWLOCK_ACTIVE_CONN_ANCHOR (&css_Rwlock_active_conn_anchor)
#define CSS_RWLOCK_ACTIVE_CONN_ANCHOR_NAME "CSS_RWLOCK_ACTIVE_CONN_ANCHOR"
#define START_EXCLUSIVE_ACCESS_ACTIVE_CONN_ANCHOR(r)
#define END_EXCLUSIVE_ACCESS_ACTIVE_CONN_ANCHOR(r)
#define START_SHARED_ACCESS_ACTIVE_CONN_ANCHOR(r)
#define END_SHARED_ACCESS_ACTIVE_CONN_ANCHOR(r)
#define CSS_RWLOCK_FREE_CONN_ANCHOR (&css_Rwlock_free_conn_anchor)
#define CSS_RWLOCK_FREE_CONN_ANCHOR_NAME "CSS_RWLOCK_FREE_CONN_ANCHOR"
#define START_EXCLUSIVE_ACCESS_FREE_CONN_ANCHOR(r)
#define END_EXCLUSIVE_ACCESS_FREE_CONN_ANCHOR(r)
#define START_SHARED_ACCESS_FREE_CONN_ANCHOR(r)
#define END_SHARED_ACCESS_FREE_CONN_ANCHOR(r)
#define CSS_LOG(msg_arg, ...) if (prm_get_bool_value (PRM_ID_CONNECTION_LOGGING)) _er_log_debug (ARG_FILE_LINE, msg_arg "\n", __VA_ARGS__)
#define CSS_LOG_STACK(msg_arg, ...) if (prm_get_bool_value (PRM_ID_CONNECTION_LOGGING)) er_print_callstack (ARG_FILE_LINE, msg_arg "\n", __VA_ARGS__)
Typedefs
typedef struct ip_info IP_INFO
typedef void * CSS_THREAD_ARG
typedef int(* CSS_THREAD_FN) (THREAD_ENTRY *thrd, CSS_THREAD_ARG)
Functions
int css_initialize_conn (CSS_CONN_ENTRY *conn, SOCKET fd)
void css_shutdown_conn (CSS_CONN_ENTRY *conn)
int css_init_conn_list (void)
void css_final_conn_list (void)
CSS_CONN_ENTRY * css_make_conn (SOCKET fd)
void css_insert_into_active_conn_list (CSS_CONN_ENTRY *conn)
void css_dealloc_conn_rmutex (CSS_CONN_ENTRY *conn)
int css_get_num_free_conn (void)
int css_increment_num_conn (BOOT_CLIENT_TYPE client_type)
void css_decrement_num_conn (BOOT_CLIENT_TYPE client_type)
void css_free_conn (CSS_CONN_ENTRY *conn)
void css_print_conn_entry_info (CSS_CONN_ENTRY *p)
void css_print_conn_list (void)
void css_print_free_conn_list (void)
CSS_CONN_ENTRY * css_connect_to_master_server (int master_port_id, const char *server_name, int name_length)
void css_register_handler_routines (css_error_code(*connect_handler)(CSS_CONN_ENTRY *conn), CSS_THREAD_FN request_handler, CSS_THREAD_FN connection_error_handler)
CSS_CONN_ENTRY * css_find_conn_by_tran_index (int tran_index)
CSS_CONN_ENTRY * css_find_conn_from_fd (SOCKET fd)
int css_get_session_ids_for_active_connections (SESSION_ID **ids, int *count)
void css_shutdown_conn_by_tran_index (int tran_index)
int css_send_abort_request (CSS_CONN_ENTRY *conn, unsigned short request_id)
int css_read_header (CSS_CONN_ENTRY *conn, const NET_HEADER *local_header)
int css_receive_request (CSS_CONN_ENTRY *conn, unsigned short *rid, int *request, int *buffer_size)
int css_read_and_queue (CSS_CONN_ENTRY *conn, int *type)
int css_receive_data (CSS_CONN_ENTRY *conn, unsigned short req_id, char **buffer, int *buffer_size, int timeout)
unsigned int css_return_eid_from_conn (CSS_CONN_ENTRY *conn, unsigned short rid)
int css_return_queued_data (CSS_CONN_ENTRY *conn, unsigned short rid, char **buffer, int *bufsize, int *rc)
int css_return_queued_error (CSS_CONN_ENTRY *conn, unsigned short request_id, char **buffer, int *buffer_size, int *rc)
int css_return_queued_request (CSS_CONN_ENTRY *conn, unsigned short *rid, int *request, int *buffer_size)
void css_remove_all_unexpected_packets (CSS_CONN_ENTRY *conn)
int css_queue_user_data_buffer (CSS_CONN_ENTRY *conn, unsigned short request_id, int size, char *buffer)
unsigned short css_get_request_id (CSS_CONN_ENTRY *conn)
int css_set_accessible_ip_info (void)
int css_free_accessible_ip_info (void)
int css_free_ip_info (IP_INFO *ip_info)
int css_read_ip_info (IP_INFO **out_ip_info, char *filename)
int css_check_ip (IP_INFO *ip_info, unsigned char *address)
void css_set_user_access_status (const char *db_user, const char *host, const char *program_name)
void css_get_user_access_status (int num_user, LAST_ACCESS_STATUS **access_status_array)
void css_free_user_access_status (void)
Variables
CSS_CONN_ENTRY * css_Conn_array
CSS_CONN_ENTRY * css_Active_conn_anchor
SYNC_RWLOCK css_Rwlock_active_conn_anchor
SYNC_RWLOCK css_Rwlock_free_conn_anchor
int css_Num_access_user
css_error_code(* css_Connect_handler)(CSS_CONN_ENTRY *)
CSS_THREAD_FN css_Request_handler
CSS_THREAD_FN css_Connection_error_handler
Macro Definition Documentation
#define CSS_LOG (msg_arg, ...) if (prm_get_bool_value (PRM_ID_CONNECTION_LOGGING)) _er_log_debug (ARG_FILE_LINE, msg_arg "\n", __VA_ARGS__)
Definition at line 136 of file connection_sr.h.
#define CSS_LOG_STACK (msg_arg, ...) if (prm_get_bool_value (PRM_ID_CONNECTION_LOGGING)) er_print_callstack (ARG_FILE_LINE, msg_arg "\n", __VA_ARGS__)
Definition at line 138 of file connection_sr.h.
Referenced by css_dealloc_conn(), css_free_conn(), css_insert_into_active_conn_list(), and css_make_conn().
#define CSS_RWLOCK_ACTIVE_CONN_ANCHOR (&css_Rwlock_active_conn_anchor)
Definition at line 55 of file connection_sr.h.
Referenced by css_final_conn_list(), and css_init_conn_list().
#define CSS_RWLOCK_ACTIVE_CONN_ANCHOR_NAME "CSS_RWLOCK_ACTIVE_CONN_ANCHOR"
Definition at line 56 of file connection_sr.h.
Referenced by css_init_conn_list().
#define CSS_RWLOCK_FREE_CONN_ANCHOR (&css_Rwlock_free_conn_anchor)
Definition at line 92 of file connection_sr.h.
Referenced by css_final_conn_list(), and css_init_conn_list().
#define CSS_RWLOCK_FREE_CONN_ANCHOR_NAME "CSS_RWLOCK_FREE_CONN_ANCHOR"
Definition at line 93 of file connection_sr.h.
Referenced by css_init_conn_list().
#define END_EXCLUSIVE_ACCESS_ACTIVE_CONN_ANCHOR (r)
Value:
do \
    { \
      (r) = rwlock_write_unlock (CSS_RWLOCK_ACTIVE_CONN_ANCHOR); \
      assert ((r) == NO_ERROR); \
    } \
  while (0)
Definition at line 66 of file connection_sr.h.
Referenced by css_block_all_active_conn(), css_free_conn(), css_insert_into_active_conn_list(), and css_shutdown_conn_by_tran_index().
#define END_EXCLUSIVE_ACCESS_FREE_CONN_ANCHOR (r)
Value:
do \
    { \
      (r) = rwlock_write_unlock (CSS_RWLOCK_FREE_CONN_ANCHOR); \
      assert ((r) == NO_ERROR); \
    } \
  while (0)
Definition at line 103 of file connection_sr.h.
Referenced by css_dealloc_conn(), and css_make_conn().
#define END_SHARED_ACCESS_ACTIVE_CONN_ANCHOR (r)
Value:
do \
    { \
      (r) = rwlock_read_unlock (CSS_RWLOCK_ACTIVE_CONN_ANCHOR); \
      assert ((r) == NO_ERROR); \
    } \
  while (0)
Definition at line 82 of file connection_sr.h.
Referenced by css_find_conn_by_tran_index(), css_find_conn_from_fd(), css_get_session_ids_for_active_connections(), css_print_conn_list(), and session_get_session_tz_region().
#define END_SHARED_ACCESS_FREE_CONN_ANCHOR (r)
Value:
do \
    { \
      (r) = rwlock_read_unlock (CSS_RWLOCK_FREE_CONN_ANCHOR); \
      assert ((r) == NO_ERROR); \
    } \
  while (0)
Definition at line 119 of file connection_sr.h.
Referenced by css_print_free_conn_list().
#define IP_BYTE_COUNT 5
Definition at line 41 of file connection_sr.h.
#define START_EXCLUSIVE_ACCESS_ACTIVE_CONN_ANCHOR (r)
Value:
do \
    { \
      (r) = rwlock_write_lock (CSS_RWLOCK_ACTIVE_CONN_ANCHOR); \
      assert ((r) == NO_ERROR); \
    } \
  while (0)
Definition at line 58 of file connection_sr.h.
Referenced by css_block_all_active_conn(), css_free_conn(), css_insert_into_active_conn_list(), and css_shutdown_conn_by_tran_index().
#define START_EXCLUSIVE_ACCESS_FREE_CONN_ANCHOR (r)
Value:
do \
    { \
      (r) = rwlock_write_lock (CSS_RWLOCK_FREE_CONN_ANCHOR); \
      assert ((r) == NO_ERROR); \
    } \
  while (0)
Definition at line 95 of file connection_sr.h.
Referenced by css_dealloc_conn(), and css_make_conn().
#define START_SHARED_ACCESS_ACTIVE_CONN_ANCHOR (r)
Value:
do \
    { \
      (r) = rwlock_read_lock (CSS_RWLOCK_ACTIVE_CONN_ANCHOR); \
      assert ((r) == NO_ERROR); \
    } \
  while (0)
Definition at line 74 of file connection_sr.h.
Referenced by css_find_conn_by_tran_index(), css_find_conn_from_fd(), css_get_session_ids_for_active_connections(), css_print_conn_list(), and session_get_session_tz_region().
#define START_SHARED_ACCESS_FREE_CONN_ANCHOR (r)
Value:
do \
    { \
      (r) = rwlock_read_lock (CSS_RWLOCK_FREE_CONN_ANCHOR); \
      assert ((r) == NO_ERROR); \
    } \
  while (0)
Definition at line 111 of file connection_sr.h.
Referenced by css_print_free_conn_list().
Typedef Documentation
typedef void* CSS_THREAD_ARG
Definition at line 129 of file connection_sr.h.
typedef int(* CSS_THREAD_FN) (THREAD_ENTRY *thrd, CSS_THREAD_ARG)
Definition at line 130 of file connection_sr.h.
typedef struct ip_info IP_INFO
Definition at line 43 of file connection_sr.h.
Function Documentation
int css_check_ip (IP_INFO * ip_info, unsigned char * address)
Referenced by css_notify_ha_log_applier_state(), and css_register_server_timeout_fn().
CSS_CONN_ENTRY* css_connect_to_master_server (int master_port_id, const char * server_name, int name_length)
Definition at line 861 of file connection_cl.c.
void css_dealloc_conn_rmutex (CSS_CONN_ENTRY * conn)
Definition at line 640 of file connection_sr.c.
References rmutex_finalize.
Referenced by css_refuse_connection_request().
void css_decrement_num_conn (BOOT_CLIENT_TYPE client_type)
Definition at line 843 of file connection_sr.c.
References css_Conn_rule_lock, css_Conn_rules, css_Conn_rules_size, css_decrement_num_conn_internal(), DB_CLIENT_TYPE_UNKNOWN, i, pthread_mutex_lock, and pthread_mutex_unlock.
Referenced by css_free_conn().
void css_final_conn_list (void)
Definition at line 525 of file connection_sr.c.
References assert, css_dealloc_conn(), css_Num_active_conn, css_Num_max_conn, CSS_RWLOCK_ACTIVE_CONN_ANCHOR, CSS_RWLOCK_FREE_CONN_ANCHOR, css_shutdown_conn(), free_and_init, i, css_wait_queue_entry::next, css_conn_entry::next, NULL, rmutex_finalize, and rwlock_finalize.
Referenced by boot_restart_server(), and net_server_start().
CSS_CONN_ENTRY* css_find_conn_by_tran_index (int tran_index)
Definition at line 1210 of file connection_sr.c.
References END_SHARED_ACCESS_ACTIVE_CONN_ANCHOR, css_wait_queue_entry::next, css_conn_entry::next, NULL, and START_SHARED_ACCESS_ACTIVE_CONN_ANCHOR.
Referenced by log_abort_all_active_transaction().
CSS_CONN_ENTRY* css_find_conn_from_fd (SOCKET fd)
Definition at line 256 of file connection_cl.c.
References END_SHARED_ACCESS_ACTIVE_CONN_ANCHOR, css_conn_entry::fd, css_wait_queue_entry::next, css_conn_entry::next, NULL, p, and START_SHARED_ACCESS_ACTIVE_CONN_ANCHOR.
Referenced by css_default_server_timeout_fn(), and css_sprintf_conn_infoids().
int css_free_accessible_ip_info (void)
Referenced by boot_server_all_finalize(), and css_notify_ha_log_applier_state().
void css_free_conn (CSS_CONN_ENTRY * conn)
Definition at line 234 of file connection_cl.c.
References assert, CSS_ACTIVE_CONN_ARGS, CSS_ACTIVE_CONN_MSG, css_close_conn(), CSS_CONN_IDX, css_dealloc_conn(), css_decrement_num_conn(), CSS_LOG_STACK, css_Num_active_conn, css_Num_max_conn, css_shutdown_conn(), END_EXCLUSIVE_ACCESS_ACTIVE_CONN_ANCHOR, css_wait_queue_entry::next, css_conn_entry::next, NULL, p, and START_EXCLUSIVE_ACCESS_ACTIVE_CONN_ANCHOR.
Referenced by css_accept_old_request(), css_connect_to_cubrid_server(), css_connect_to_master_server(), css_free_entry(), css_is_shutdown_timeout_expired(), css_process_new_connection(), css_reestablish_connection_to_master(), css_register_new_server(), css_register_new_server2(), css_send_to_existing_server(), net_server_conn_down(), and server_monitor_thr_f().
int css_free_ip_info (IP_INFO * ip_info)
Referenced by css_notify_ha_log_applier_state(), and css_register_server_timeout_fn().
void css_free_user_access_status (void)
Definition at line 3082 of file connection_sr.c.
References CSECT_ACCESS_STATUS, csect_enter, csect_exit, css_Access_status_anchor, css_Num_access_user, free_and_init, INF_WAIT, last_access_status::next, and NULL.
Referenced by net_server_start().
int css_get_num_free_conn (void)
Definition at line 674 of file connection_sr.c.
References css_Num_free_conn.
unsigned short css_get_request_id (CSS_CONN_ENTRY * conn)
Definition at line 277 of file connection_cl.c.
References ARG_FILE_LINE, assert, css_is_valid_request_id(), er_set(), ER_WARNING_SEVERITY, ERR_CSS_REQUEST_ID_FAILURE, NO_ERROR, NULL, css_conn_entry::request_id, rmutex_lock, and rmutex_unlock.
Referenced by css_send_request_with_data_buffer().
int css_get_session_ids_for_active_connections (SESSION_ID ** ids, int * count)
Definition at line 1270 of file connection_sr.c.
References ARG_FILE_LINE, assert, css_Num_active_conn, END_SHARED_ACCESS_ACTIVE_CONN_ANCHOR, ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, i, css_wait_queue_entry::next, css_conn_entry::next, NO_ERROR, NULL, css_conn_entry::session_id, and START_SHARED_ACCESS_ACTIVE_CONN_ANCHOR.
Referenced by session_check_timeout().
void css_get_user_access_status (int num_user, LAST_ACCESS_STATUS ** access_status_array)
Definition at line 3060 of file connection_sr.c.
References CSECT_ACCESS_STATUS, csect_enter_as_reader, csect_exit, i, INF_WAIT, last_access_status::next, and NULL.
Referenced by css_user_access_status_start_scan().
int css_increment_num_conn (BOOT_CLIENT_TYPE client_type)
Definition at line 817 of file connection_sr.c.
References css_Conn_rule_lock, css_Conn_rules, css_Conn_rules_size, css_increment_num_conn_internal(), error(), i, NO_ERROR, pthread_mutex_lock, and pthread_mutex_unlock.
Referenced by server_ping_with_handshake().
int css_init_conn_list (void)
Definition at line 428 of file connection_sr.c.
References ARG_FILE_LINE, ASSERT_ERROR, css_get_max_conn(), css_init_conn_rules(), css_initialize_conn(), css_Num_free_conn, css_Num_max_conn, CSS_RWLOCK_ACTIVE_CONN_ANCHOR, CSS_RWLOCK_ACTIVE_CONN_ANCHOR_NAME, CSS_RWLOCK_FREE_CONN_ANCHOR, CSS_RWLOCK_FREE_CONN_ANCHOR_NAME, ER_CSS_CONN_INIT, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), er_set_with_oserror(), err, error(), free_and_init, i, css_conn_entry::next, NO_ERROR, NULL, NUM_MASTER_CHANNEL, rmutex_initialize, RMUTEX_NAME_CONN_ENTRY, rwlock_finalize, and rwlock_initialize.
Referenced by boot_restart_server().
int css_initialize_conn (CSS_CONN_ENTRY * conn, SOCKET fd)
Definition at line 279 of file connection_sr.c.
References css_conn_entry::abort_queue, css_conn_entry::buffer_queue, css_conn_entry::client_id, CONN_OPEN, css_get_next_client_id(), css_initialize_list(), css_conn_entry::data_queue, DB_CLIENT_TYPE_UNKNOWN, DB_EMPTY_SESSION, css_conn_entry::db_error, ER_CSS_CONN_INIT, err, css_conn_entry::error_queue, css_conn_entry::fd, css_conn_entry::in_transaction, css_conn_entry::invalidate_snapshot, NO_ERROR, NULL, NULL_TRAN_INDEX, css_conn_entry::request_id, css_conn_entry::request_queue, css_conn_entry::reset_on_commit, css_conn_entry::session_id, css_conn_entry::status, and THREAD_STOP_WORKERS_EXCEPT_LOGWR.
Referenced by css_init_conn_list(), and css_make_conn().
void css_insert_into_active_conn_list (CSS_CONN_ENTRY * conn)
Definition at line 614 of file connection_sr.c.
References assert, css_Active_conn_anchor, CSS_ACTIVE_CONN_ARGS, CSS_ACTIVE_CONN_MSG, CSS_CONN_IDX, CSS_LOG_STACK, css_Num_active_conn, css_Num_max_conn, END_EXCLUSIVE_ACCESS_ACTIVE_CONN_ANCHOR, css_conn_entry::next, and START_EXCLUSIVE_ACCESS_ACTIVE_CONN_ANCHOR.
Referenced by css_init(), and css_internal_connection_handler().
CSS_CONN_ENTRY* css_make_conn (SOCKET fd)
Definition at line 167 of file connection_cl.c.
References ARG_FILE_LINE, assert, css_Conn_anchor, CSS_CONN_IDX, css_Free_conn_anchor, CSS_FREE_CONN_ARGS, CSS_FREE_CONN_MSG, css_initialize_conn(), CSS_LOG_STACK, css_Num_free_conn, END_EXCLUSIVE_ACCESS_FREE_CONN_ANCHOR, ER_CSS_CONN_INIT, ER_ERROR_SEVERITY, er_set_with_oserror(), css_conn_entry::next, NO_ERROR, NULL, and START_EXCLUSIVE_ACCESS_FREE_CONN_ANCHOR.
Referenced by css_accept_new_request(), css_accept_old_request(), css_connect_to_cubrid_server(), css_connect_to_master_server(), css_connect_to_master_timeout(), css_is_shutdown_timeout_expired(), css_process_new_client(), css_process_new_connection(), and main().
void css_print_conn_entry_info (CSS_CONN_ENTRY * p)
Definition at line 928 of file connection_sr.c.
References css_conn_entry::client_id, css_conn_entry::fd, css_conn_entry::next, and css_conn_entry::request_id.
Referenced by css_print_conn_list(), and css_print_free_conn_list().
void css_print_conn_list (void)
Definition at line 941 of file connection_sr.c.
References assert, css_Num_active_conn, css_print_conn_entry_info(), END_SHARED_ACCESS_ACTIVE_CONN_ANCHOR, i, css_wait_queue_entry::next, css_conn_entry::next, NULL, and START_SHARED_ACCESS_ACTIVE_CONN_ANCHOR.
void css_print_free_conn_list (void)
Definition at line 969 of file connection_sr.c.
References assert, css_Num_free_conn, css_print_conn_entry_info(), END_SHARED_ACCESS_FREE_CONN_ANCHOR, i, css_wait_queue_entry::next, css_conn_entry::next, NULL, and START_SHARED_ACCESS_FREE_CONN_ANCHOR.
int css_queue_user_data_buffer (CSS_CONN_ENTRY * conn, unsigned short request_id, int size, char * buffer)
Definition at line 342 of file connection_list_cl.c.
References assert, css_conn_entry::buffer_queue, css_add_queue_entry(), css_is_request_aborted(), css_queue_packet(), css_conn_entry::db_error, css_conn_entry::invalidate_snapshot, NO_ERROR, NO_ERRORS, NULL, css_wait_queue_entry::rc, rmutex_lock, and rmutex_unlock.
Referenced by css_connect_to_cubrid_server(), css_queue_receive_data_buffer(), css_send_request_with_data_buffer(), and css_server_connect_part_two().
int css_read_and_queue (CSS_CONN_ENTRY * conn, int * type)
Definition at line 1531 of file connection_sr.c.
References CONN_OPEN, CONNECTION_CLOSED, css_queue_packet(), css_read_header(), DEFAULT_HEADER_DATA, ERROR_ON_READ, NO_ERRORS, ntohl(), css_wait_queue_entry::rc, packet_header::request_id, css_conn_entry::status, and packet_header::type.
Referenced by css_connection_handler_thread().
int css_read_header (CSS_CONN_ENTRY * conn, const NET_HEADER * local_header)
Definition at line 1478 of file connection_sr.c.
References CLOSE_TYPE, CONNECTION_CLOSED, css_net_read_header(), packet_header::db_error, css_conn_entry::db_error, css_conn_entry::fd, packet_header::flags, css_conn_entry::invalidate_snapshot, NET_HEADER_FLAG_INVALIDATE_SNAPSHOT, NO_ERRORS, ntohl(), ntohs(), css_wait_queue_entry::rc, RECORD_TRUNCATED, packet_header::transaction_id, and packet_header::type.
Referenced by css_queue_command_packet(), and css_read_and_queue().
int css_read_ip_info (IP_INFO ** out_ip_info, char * filename)
Referenced by css_notify_ha_log_applier_state(), and css_register_server_timeout_fn().
int css_receive_data (CSS_CONN_ENTRY * conn, unsigned short req_id, char ** buffer, int * buffer_size, int timeout)
Definition at line 482 of file connection_cl.c.
References ABORT_TYPE, assert, begin(), packet_header::buffer_size, CANT_ALLOC_BUFFER, CONN_OPEN, CONNECTION_CLOSED, css_net_read_header(), css_net_recv(), css_queue_unexpected_data_packet(), css_queue_unexpected_packet(), css_read_remaining_bytes(), css_return_data_buffer(), css_return_queued_data(), css_return_queued_data_timeout(), DATA_TYPE, packet_header::db_error, css_conn_entry::db_error, DEFAULT_HEADER_DATA, css_conn_entry::fd, free_and_init, NO_DATA_AVAILABLE, NO_ERRORS, ntohl(), NULL, rc, css_wait_queue_entry::rc, RECORD_TRUNCATED, packet_header::request_id, SERVER_ABORTED, css_conn_entry::status, TRACE, packet_header::transaction_id, and packet_header::type.
Referenced by css_accept_new_request(), css_accept_old_request(), css_connect_to_cubrid_server(), css_internal_request_handler(), css_process_info_request(), css_process_kill_slave(), css_receive_data_from_client_with_timeout(), css_receive_data_from_server_with_timeout(), css_register_new_server(), css_register_new_server2(), css_send_to_existing_server(), css_server_connect_part_two(), get_server_state_from_master(), return_integer_data(), and return_string().
int css_receive_request (CSS_CONN_ENTRY * conn, unsigned short * rid, int * request, int * buffer_size)
Definition at line 455 of file connection_cl.c.
References css_read_one_request(), css_return_queued_request(), rc, TRACE, and WRONG_PACKET_TYPE.
Referenced by css_internal_request_handler(), css_process_info_request(), and css_process_new_connection().
void css_register_handler_routines (css_error_code(*)(CSS_CONN_ENTRY *conn) connect_handler, CSS_THREAD_FN request_handler, CSS_THREAD_FN connection_error_handler)
Definition at line 1022 of file connection_sr.c.
References css_Connect_handler, css_Connection_error_handler, and css_Request_handler.
Referenced by css_initialize_server_interfaces().
void css_remove_all_unexpected_packets (CSS_CONN_ENTRY * conn)
Definition at line 1467 of file connection_cl.c.
References css_conn_entry::abort_queue, assert, css_queue_remove_header(), css_remove_and_free_queue_entry(), css_remove_and_free_wait_queue_entry(), css_traverse_list(), css_conn_entry::data_queue, css_conn_entry::error_queue, NO_ERROR, NULL, css_conn_entry::request_queue, rmutex_lock, and rmutex_unlock.
Referenced by css_cleanup_client_queues(), css_cleanup_server_queues(), css_end_server_request(), css_send_close_request(), and css_shutdown_conn().
unsigned int css_return_eid_from_conn (CSS_CONN_ENTRY * conn, unsigned short rid)
Definition at line 1596 of file connection_sr.c.
References css_make_eid().
int css_return_queued_data (CSS_CONN_ENTRY * conn, unsigned short rid, char ** buffer, int * bufsize, int * rc)
Definition at line 2832 of file connection_sr.c.
References css_return_queued_data_timeout().
int css_return_queued_error (CSS_CONN_ENTRY * conn, unsigned short request_id, char ** buffer, int * buffer_size, int * rc)
Definition at line 1364 of file connection_cl.c.
References assert, css_queue_entry::buffer, css_find_and_remove_queue_entry(), css_find_queue_entry(), css_free_queue_entry(), css_queue_remove_header_entry_ptr(), css_queue_entry::db_error, ER_LK_UNILATERALLY_ABORTED, css_conn_entry::error_queue, free_and_init, css_queue_entry::next, NO_ERROR, NULL, p, rc, rmutex_lock, rmutex_unlock, and css_queue_entry::size.
Referenced by css_receive_error(), css_test_for_client_errors(), and css_test_for_server_errors().
int css_return_queued_request (CSS_CONN_ENTRY * conn, unsigned short * rid, int * request, int * buffer_size)
Definition at line 2558 of file connection_sr.c.
References assert, css_wait_queue_entry::buffer, css_queue_entry::buffer, packet_header::buffer_size, CONN_CLOSED, CONN_OPEN, css_free_queue_entry(), css_remove_list_from_head(), css_retire_net_header_entry(), css_queue_entry::db_error, css_conn_entry::db_error, packet_header::function_code, css_queue_entry::invalidate_snapshot, css_conn_entry::invalidate_snapshot, css_queue_entry::key, NO_DATA_AVAILABLE, NO_ERROR, NO_ERRORS, ntohl(), ntohs(), NULL, p, css_wait_queue_entry::rc, css_conn_entry::request_queue, rmutex_lock, rmutex_unlock, css_conn_entry::status, and css_queue_entry::transaction_id.
Referenced by css_receive_request().
int css_send_abort_request (CSS_CONN_ENTRY * conn, unsigned short request_id)
Definition at line 1448 of file connection_sr.c.
References assert, CONN_OPEN, CONNECTION_CLOSED, css_abort_request(), css_remove_unexpected_packets(), NO_ERROR, NULL, css_wait_queue_entry::rc, rmutex_lock, rmutex_unlock, and css_conn_entry::status.
Referenced by css_send_abort_to_client().
int css_set_accessible_ip_info (void)
Referenced by boot_restart_server(), css_notify_ha_log_applier_state(), and sysprm_change_parameter_values().
void css_set_user_access_status (const char * db_user, const char * host, const char * program_name)
Definition at line 3007 of file connection_sr.c.
References assert, CSECT_ACCESS_STATUS, csect_enter, csect_exit, css_Access_status_anchor, css_Num_access_user, last_access_status::db_user, last_access_status::host, INF_WAIT, last_access_status::next, NULL, last_access_status::program_name, and last_access_status::time.
Referenced by ssession_find_or_create_session().
void css_shutdown_conn (CSS_CONN_ENTRY * conn)
Definition at line 127 of file connection_cl.c.
void css_shutdown_conn_by_tran_index (int tran_index)
Definition at line 1336 of file connection_sr.c.
References CONN_CLOSING, CONN_OPEN, END_EXCLUSIVE_ACCESS_ACTIVE_CONN_ANCHOR, css_conn_entry::next, NULL, START_EXCLUSIVE_ACCESS_ACTIVE_CONN_ANCHOR, and css_conn_entry::status.
Referenced by logtb_slam_transaction(), and xlogtb_kill_or_interrupt_tran().
Variable Documentation
CSS_CONN_ENTRY* css_Active_conn_anchor
Definition at line 134 of file connection_sr.c.
Referenced by css_block_all_active_conn(), css_insert_into_active_conn_list(), and session_get_session_tz_region().
CSS_CONN_ENTRY* css_Conn_array
Definition at line 133 of file connection_sr.c.
Referenced by css_cleanup_server_queues(), and css_send_reply_and_data_to_client().
css_error_code(* css_Connect_handler) (CSS_CONN_ENTRY *)
Definition at line 144 of file connection_sr.c.
Referenced by css_is_shutdown_timeout_expired(), css_process_new_client(), and css_register_handler_routines().
CSS_THREAD_FN css_Connection_error_handler
Definition at line 150 of file connection_sr.c.
Referenced by css_register_handler_routines().
int css_Num_access_user
Definition at line 141 of file connection_sr.c.
Referenced by css_free_user_access_status(), css_set_user_access_status(), and css_user_access_status_start_scan().
CSS_THREAD_FN css_Request_handler
Definition at line 147 of file connection_sr.c.
Referenced by css_register_handler_routines().
SYNC_RWLOCK css_Rwlock_active_conn_anchor
Definition at line 137 of file connection_sr.c.
SYNC_RWLOCK css_Rwlock_free_conn_anchor
Definition at line 138 of file connection_sr.c.