CUBRID Engine: src/connection/connection_less.h File Reference
connection_less.h File Reference
#include "connection_defs.h"
Functions
unsigned int css_make_eid (unsigned short host_id, unsigned short rid)
CSS_MAP_ENTRY * css_queue_connection (CSS_CONN_ENTRY *conn, const char *host, CSS_MAP_ENTRY **anchor)
CSS_MAP_ENTRY * css_return_entry_from_eid (unsigned int eid, CSS_MAP_ENTRY *anchor)
void css_remove_queued_connection_by_entry (CSS_MAP_ENTRY *entry, CSS_MAP_ENTRY **anchor)
CSS_MAP_ENTRY * css_return_open_entry (char *host, CSS_MAP_ENTRY **anchor)
unsigned int css_return_eid_from_conn (CSS_CONN_ENTRY *conn, CSS_MAP_ENTRY **anchor, unsigned short rid)
CSS_MAP_ENTRY * css_return_entry_from_conn (CSS_CONN_ENTRY *conn, CSS_MAP_ENTRY *anchor)
Function Documentation
unsigned int css_make_eid (unsigned short host_id, unsigned short rid)
Definition at line 44 of file connection_less.c.
Referenced by css_client_init(), css_return_eid_from_conn(), css_send_req_to_server(), css_send_req_to_server_2_data(), css_send_req_to_server_no_reply(), and css_send_request_to_server_with_buffer().
CSS_MAP_ENTRY* css_queue_connection (CSS_CONN_ENTRY * conn, const char * host, CSS_MAP_ENTRY ** anchor)
Definition at line 119 of file connection_less.c.
References css_mapping_entry::conn, css_make_entry_id(), css_mapping_entry::id, css_mapping_entry::key, css_mapping_entry::next, NULL, and strlen.
Referenced by css_client_init(), and css_return_eid_from_conn().
void css_remove_queued_connection_by_entry (CSS_MAP_ENTRY * entry, CSS_MAP_ENTRY ** anchor)
Definition at line 185 of file connection_less.c.
References free_and_init, css_mapping_entry::next, and NULL.
Referenced by css_client_init(), css_handle_pipe_shutdown(), css_receive_data_from_server_with_timeout(), css_send_data_to_server(), css_send_error_to_server(), css_send_req_to_server(), css_send_req_to_server_2_data(), css_send_req_to_server_no_reply(), css_send_request_to_server_with_buffer(), and css_terminate().
unsigned int css_return_eid_from_conn (CSS_CONN_ENTRY * conn, CSS_MAP_ENTRY ** anchor, unsigned short rid)
Definition at line 274 of file connection_less.c.
References css_make_eid(), css_queue_connection(), css_return_entry_from_conn(), css_mapping_entry::id, and NULL.
Referenced by css_internal_request_handler().
CSS_MAP_ENTRY* css_return_entry_from_conn (CSS_CONN_ENTRY * conn, CSS_MAP_ENTRY * anchor)
Definition at line 248 of file connection_less.c.
References css_mapping_entry::conn, css_mapping_entry::next, and NULL.
Referenced by css_handle_pipe_shutdown(), and css_return_eid_from_conn().
CSS_MAP_ENTRY* css_return_entry_from_eid (unsigned int eid, CSS_MAP_ENTRY * anchor)
Definition at line 59 of file connection_less.c.
References CSS_ENTRYID_FROM_EID, css_mapping_entry::id, css_mapping_entry::next, and NULL.
Referenced by css_queue_receive_data_buffer(), and css_receive_data_from_server_with_timeout().
CSS_MAP_ENTRY* css_return_open_entry (char * host, CSS_MAP_ENTRY ** anchor)
Definition at line 225 of file connection_less.c.
References css_mapping_entry::conn, css_get_queued_entry(), css_test_for_open_conn(), and NULL.
Referenced by css_cleanup_client_queues(), css_client_init(), css_send_data_to_server(), css_send_error_to_server(), css_send_req_to_server(), css_send_req_to_server_2_data(), css_send_req_to_server_no_reply(), and css_send_request_to_server_with_buffer().