CUBRID Engine: src/connection/connection_support.c File Reference
connection_support.c File Reference
#include "config.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <sys/types.h>
#include <assert.h>
#include <sys/time.h>
#include <sys/ioctl.h>
#include <sys/uio.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <unistd.h>
#include <fcntl.h>
#include <poll.h>
#include "porting.h"
#include "error_manager.h"
#include "connection_globals.h"
#include "memory_alloc.h"
#include "environment_variable.h"
#include "system_parameter.h"
#include "boot_sr.h"
#include "tcp.h"
#include "connection_list_cl.h"
#include "connection_cl.h"
#include "storage_common.h"
#include "dbtype.h"
#include "tz_support.h"
#include "db_date.h"
#include "show_scan.h"
Macros
#define pthread_mutex_init(a, b)
#define pthread_mutex_destroy(a)
#define pthread_mutex_lock(b) 0
#define pthread_mutex_unlock(a)
#define INITIAL_IP_NUM 16
#define CSS_TRUNCATE_BUFFER_SIZE 512
Functions
static void css_default_server_timeout_fn (void)
static bool css_default_check_server_alive_fn (const char *db_name, const char *db_host)
static int css_sprintf_conn_infoids (SOCKET fd, const char **client_user_name, const char **client_host_name, int *client_pid)
static int css_send_io_vector (CSS_CONN_ENTRY *conn, struct iovec *vec_p, ssize_t total_len, int vector_length, int timeout)
static int css_net_send2 (CSS_CONN_ENTRY *conn, const char *buff1, int len1, const char *buff2, int len2)
static int css_net_send3 (CSS_CONN_ENTRY *conn, const char *buff1, int len1, const char *buff2, int len2, const char *buff3, int len3)
static int css_net_send4 (CSS_CONN_ENTRY *conn, const char *buff1, int len1, const char *buff2, int len2, const char *buff3, int len3, const char *buff4, int len4)
static int css_net_send5 (CSS_CONN_ENTRY *conn, const char *buff1, int len1, const char *buff2, int len2, const char *buff3, int len3, const char *buff4, int len4, const char *buff5, int len5)
static int css_net_send6 (CSS_CONN_ENTRY *conn, const char *buff1, int len1, const char *buff2, int len2, const char *buff3, int len3, const char *buff4, int len4, const char *buff5, int len5, const char *buff6, int len6)
static int css_net_send7 (CSS_CONN_ENTRY *conn, const char *buff1, int len1, const char *buff2, int len2, const char *buff3, int len3, const char *buff4, int len4, const char *buff5, int len5, const char *buff6, int len6, const char *buff7, int len7)
static int css_net_send8 (CSS_CONN_ENTRY *conn, const char *buff1, int len1, const char *buff2, int len2, const char *buff3, int len3, const char *buff4, int len4, const char *buff5, int len5, const char *buff6, int len6, const char *buff7, int len7, const char *buff8, int len8)
static int css_make_access_status_exist_user (THREAD_ENTRY *thread_p, OID *class_oid, LAST_ACCESS_STATUS **access_status_array, int num_user, SHOWSTMT_ARRAY_CONTEXT *ctx)
static LAST_ACCESS_STATUS * css_get_access_status_with_name (LAST_ACCESS_STATUS **access_status_array, int num_user, const char *user_name)
static LAST_ACCESS_STATUS * css_get_unused_access_status (LAST_ACCESS_STATUS **access_status_array, int num_user)
static void css_set_networking_error (SOCKET fd)
int css_readn (SOCKET fd, char *ptr, int nbytes, int timeout)
void css_read_remaining_bytes (SOCKET fd, int len)
int css_net_recv (SOCKET fd, char *buffer, int *maxlen, int timeout)
int css_vector_send (SOCKET fd, struct iovec *vec[], int *len, int bytes_written, int timeout)
void css_set_io_vector (struct iovec *vec1_p, struct iovec *vec2_p, const char *buff, int len, int *templen)
int css_send_io_vector_with_socket (SOCKET &socket, struct iovec *vec_p, ssize_t total_len, int vector_length, int timeout)
int css_net_send (CSS_CONN_ENTRY *conn, const char *buff, int len, int timeout)
int css_net_send_with_socket (SOCKET &socket, const char *buff, int len, int timeout)
int css_net_send3_with_socket (SOCKET &socket, const char *buff1, int len1, const char *buff2, int len2, const char *buff3, int len3)
int css_net_send_buffer_only (CSS_CONN_ENTRY *conn, const char *buff, int len, int timeout)
int css_net_read_header (SOCKET fd, char *buffer, int *maxlen, int timeout)
void css_set_net_header (NET_HEADER *header_p, int type, short function_code, int request_id, int buffer_size, int transaction_id, int invalidate_snapshot, int db_error)
int css_send_request_with_data_buffer (CSS_CONN_ENTRY *conn, int request, unsigned short *request_id, const char *arg_buffer, int arg_size, char *reply_buffer, int reply_size)
int css_send_request (CSS_CONN_ENTRY *conn, int command, unsigned short *request_id, const char *arg_buffer, int arg_buffer_size)
int css_send_request_with_socket (SOCKET &socket, int command, unsigned short *request_id, const char *arg_buffer, int arg_buffer_size)
int css_send_data (CSS_CONN_ENTRY *conn, unsigned short rid, const char *buffer, int buffer_size)
int css_send_error (CSS_CONN_ENTRY *conn, unsigned short rid, const char *buffer, int buffer_size)
void css_register_check_server_alive_fn (CSS_CHECK_SERVER_ALIVE_FN callback_fn)
const char * css_ha_server_state_string (HA_SERVER_STATE state)
const char * css_ha_applier_state_string (HA_LOG_APPLIER_STATE state)
const char * css_ha_mode_string (HA_MODE mode)
void css_register_server_timeout_fn (CSS_SERVER_TIMEOUT_FN callback_fn)
int css_send_magic (CSS_CONN_ENTRY *conn)
int css_send_magic_with_socket (SOCKET &socket)
int css_check_magic (CSS_CONN_ENTRY *conn)
int css_check_magic_with_socket (SOCKET fd)
int css_user_access_status_start_scan (THREAD_ENTRY *thread_p, int type, DB_VALUE **arg_values, int arg_cnt, void **ptr)
int css_platform_independent_poll (POLL_FD *fds, int num_of_fds, int timeout)
Variables
static int rv
static const int CSS_TCP_MIN_NUM_RETRIES = 3
static CSS_SERVER_TIMEOUT_FN css_server_timeout_fn = css_default_server_timeout_fn
CSS_CHECK_SERVER_ALIVE_FN css_check_server_alive_fn = css_default_check_server_alive_fn
Macro Definition Documentation
#define CSS_TRUNCATE_BUFFER_SIZE 512
Definition at line 103 of file connection_support.c.
Referenced by css_read_remaining_bytes().
#define INITIAL_IP_NUM 16
Definition at line 96 of file connection_support.c.
Referenced by css_register_server_timeout_fn().
#define pthread_mutex_destroy (a)
Definition at line 90 of file connection_support.c.
#define pthread_mutex_init (a, b)
Definition at line 89 of file connection_support.c.
#define pthread_mutex_lock (b) 0
Definition at line 91 of file connection_support.c.
Referenced by css_net_recv().
#define pthread_mutex_unlock (a)
Definition at line 92 of file connection_support.c.
Referenced by css_net_recv().
Function Documentation
int css_check_magic (CSS_CONN_ENTRY * conn)
Definition at line 2483 of file connection_support.c.
References css_check_magic_with_socket(), and css_conn_entry::fd.
Referenced by css_process_new_connection().
int css_check_magic_with_socket (SOCKET fd)
Definition at line 2489 of file connection_support.c.
References css_Net_magic, css_readn(), ERROR_ON_READ, ERROR_WHEN_READING_SIZE, i, NO_ERRORS, ntohl(), p, prm_get_integer_value(), PRM_ID_TCP_CONNECTION_TIMEOUT, and WRONG_PACKET_TYPE.
Referenced by css_check_magic().
static bool css_default_check_server_alive_fn (const char * db_name, const char * db_host) static
Definition at line 2119 of file connection_support.c.
static void css_default_server_timeout_fn (void) static
Definition at line 208 of file connection_support.c.
References css_find_conn_from_fd(), css_sprintf_conn_infoids(), error(), logtb_find_client_name_host_pid(), NO_ERROR, and NULL.
static LAST_ACCESS_STATUS * css_get_access_status_with_name (LAST_ACCESS_STATUS ** access_status_array, int num_user, const char * user_name) static
Definition at line 2831 of file connection_support.c.
References assert, i, and NULL.
Referenced by css_make_access_status_exist_user().
static LAST_ACCESS_STATUS * css_get_unused_access_status (LAST_ACCESS_STATUS ** access_status_array, int num_user) static
Definition at line 2865 of file connection_support.c.
References i, and NULL.
Referenced by css_user_access_status_start_scan().
const char* css_ha_applier_state_string (HA_LOG_APPLIER_STATE state)
Definition at line 2169 of file connection_support.c.
References HA_LOG_APPLIER_STATE_DONE, HA_LOG_APPLIER_STATE_DONE_STR, HA_LOG_APPLIER_STATE_ERROR, HA_LOG_APPLIER_STATE_ERROR_STR, HA_LOG_APPLIER_STATE_NA, HA_LOG_APPLIER_STATE_RECOVERING, HA_LOG_APPLIER_STATE_RECOVERING_STR, HA_LOG_APPLIER_STATE_UNREGISTERED, HA_LOG_APPLIER_STATE_UNREGISTERED_STR, HA_LOG_APPLIER_STATE_WORKING, and HA_LOG_APPLIER_STATE_WORKING_STR.
Referenced by css_notify_ha_log_applier_state(), and la_change_state().
const char* css_ha_mode_string (HA_MODE mode)
Definition at line 2193 of file connection_support.c.
References HA_MODE_FAIL_BACK, HA_MODE_FAIL_OVER, HA_MODE_LAZY_BACK, HA_MODE_OFF, HA_MODE_OFF_STR, HA_MODE_ON_STR, HA_MODE_REPLICA, HA_MODE_REPLICA_STR, and HA_MODE_ROLE_CHANGE.
Referenced by boot_restart_server().
const char* css_ha_server_state_string (HA_SERVER_STATE state)
Definition at line 2141 of file connection_support.c.
References HA_SERVER_STATE_ACTIVE, HA_SERVER_STATE_ACTIVE_STR, HA_SERVER_STATE_DEAD, HA_SERVER_STATE_DEAD_STR, HA_SERVER_STATE_IDLE, HA_SERVER_STATE_IDLE_STR, HA_SERVER_STATE_MAINTENANCE, HA_SERVER_STATE_MAINTENANCE_STR, HA_SERVER_STATE_NA, HA_SERVER_STATE_STANDBY, HA_SERVER_STATE_STANDBY_STR, HA_SERVER_STATE_TO_BE_ACTIVE, HA_SERVER_STATE_TO_BE_ACTIVE_STR, HA_SERVER_STATE_TO_BE_STANDBY, and HA_SERVER_STATE_TO_BE_STANDBY_STR.
Referenced by checksumdb(), chksum_report_header(), css_change_ha_server_state(), css_process_get_server_ha_mode(), css_transit_ha_server_state(), db_get_ha_server_state(), hb_resource_receive_changemode(), hb_resource_send_changemode(), la_change_state(), la_log_record_process(), la_print_log_header(), and log_active_log_header_next_scan().
static int css_make_access_status_exist_user (THREAD_ENTRY * thread_p, OID * class_oid, LAST_ACCESS_STATUS ** access_status_array, int num_user, SHOWSTMT_ARRAY_CONTEXT * ctx) static
Definition at line 2647 of file connection_support.c.
References assert, ASSERT_ERROR, css_get_access_status_with_name(), db_get_string(), db_localdatetime(), db_make_datetime(), db_make_null(), db_make_string_copy(), db_private_free_and_init, er_errid(), ER_FAILED, error(), heap_attrinfo_end(), heap_attrinfo_read_dbvalues(), heap_attrinfo_start(), heap_get_class_info(), heap_get_class_record(), heap_next(), heap_scancache_end(), heap_scancache_quick_start_root_hfid(), heap_scancache_start(), HFID_IS_NULL, last_access_status::host, i, logtb_get_mvcc_snapshot(), NO_ERROR, NULL, OID_SET_NULL, or_get_attrname(), PEEK, last_access_status::program_name, S_END, S_SUCCESS, showstmt_alloc_tuple_in_context(), and last_access_status::time.
Referenced by css_user_access_status_start_scan().
int css_net_read_header (SOCKET fd, char * buffer, int * maxlen, int timeout)
Definition at line 1472 of file connection_support.c.
References css_net_recv().
Referenced by css_read_header(), css_receive_data(), and css_receive_error().
int css_net_recv (SOCKET fd, char * buffer, int * maxlen, int timeout)
Definition at line 532 of file connection_support.c.
References ARG_FILE_LINE, CHECK_SERVER_IS_ALIVE, css_check_server_alive_fn, css_peer_alive(), css_read_remaining_bytes(), css_readn(), css_set_networking_error(), css_vector_send(), ER_ERROR_SEVERITY, er_log_debug, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), ERROR_ON_READ, ERROR_WHEN_READING_SIZE, i, NO_ERRORS, ntohl(), NULL, pthread_mutex_lock, pthread_mutex_unlock, rc, READ_LENGTH_MISMATCH, and RECORD_TRUNCATED.
Referenced by css_net_read_header(), css_queue_data_packet(), css_queue_error_packet(), css_receive_data(), css_receive_error(), css_recv_and_queue_packet(), and css_register_new_server2().
int css_net_send (CSS_CONN_ENTRY * conn, const char * buff, int len, int timeout)
Definition at line 1062 of file connection_support.c.
References css_net_send_with_socket(), and css_conn_entry::fd.
Referenced by css_abort_request(), css_connect_to_master_server(), css_send_close_request(), and css_send_request_with_data_buffer().
static int css_net_send2 (CSS_CONN_ENTRY * conn, const char * buff1, int len1, const char * buff2, int len2) static
Definition at line 1093 of file connection_support.c.
References css_send_io_vector(), and css_set_io_vector().
Referenced by css_send_data(), and css_send_error().
static int css_net_send3 (CSS_CONN_ENTRY * conn, const char * buff1, int len1, const char * buff2, int len2, const char * buff3, int len3) static
Definition at line 1123 of file connection_support.c.
References css_net_send3_with_socket(), and css_conn_entry::fd.
Referenced by css_send_request_with_data_buffer().
int css_net_send3_with_socket (SOCKET & socket, const char * buff1, int len1, const char * buff2, int len2, const char * buff3, int len3)
Definition at line 1130 of file connection_support.c.
References css_send_io_vector_with_socket(), and css_set_io_vector().
Referenced by css_net_send3(), and css_send_request_with_socket().
static int css_net_send4 (CSS_CONN_ENTRY * conn, const char * buff1, int len1, const char * buff2, int len2, const char * buff3, int len3, const char * buff4, int len4) static
Definition at line 1164 of file connection_support.c.
References css_net_send5(), css_send_io_vector(), and css_set_io_vector().
Referenced by css_send_data().
static int css_net_send5 (CSS_CONN_ENTRY * conn, const char * buff1, int len1, const char * buff2, int len2, const char * buff3, int len3, const char * buff4, int len4, const char * buff5, int len5) static
Referenced by css_net_send4(), and css_send_request_with_data_buffer().
static int css_net_send6 (CSS_CONN_ENTRY * conn, const char * buff1, int len1, const char * buff2, int len2, const char * buff3, int len3, const char * buff4, int len4, const char * buff5, int len5, const char * buff6, int len6) static
Definition at line 1232 of file connection_support.c.
References css_net_send7(), css_send_io_vector(), and css_set_io_vector().
Referenced by css_send_data().
static int css_net_send7 (CSS_CONN_ENTRY * conn, const char * buff1, int len1, const char * buff2, int len2, const char * buff3, int len3, const char * buff4, int len4, const char * buff5, int len5, const char * buff6, int len6, const char * buff7, int len7) static
Referenced by css_net_send6(), and css_send_request_with_data_buffer().
static int css_net_send8 (CSS_CONN_ENTRY * conn, const char * buff1, int len1, const char * buff2, int len2, const char * buff3, int len3, const char * buff4, int len4, const char * buff5, int len5, const char * buff6, int len6, const char * buff7, int len7, const char * buff8, int len8) static
Definition at line 1309 of file connection_support.c.
References CANT_ALLOC_BUFFER, css_send_io_vector(), css_set_io_vector(), i, ntohl(), NULL, and rc.
Referenced by css_send_data().
int css_net_send_buffer_only (CSS_CONN_ENTRY * conn, const char * buff, int len, int timeout)
Definition at line 1453 of file connection_support.c.
References css_send_io_vector().
int css_net_send_with_socket (SOCKET & socket, const char * buff, int len, int timeout)
Definition at line 1068 of file connection_support.c.
References css_send_io_vector_with_socket(), and css_set_io_vector().
Referenced by css_net_send(), css_send_magic_with_socket(), and css_send_request_with_socket().
int css_platform_independent_poll (POLL_FD * fds, int num_of_fds, int timeout)
Definition at line 2891 of file connection_support.c.
References assert, LOG_SYSTEM_TRAN_INDEX, NULL_TRAN_INDEX, rc, and css_conn_entry::transaction_id.
Referenced by hb_process_master_request().
void css_read_remaining_bytes (SOCKET fd, int len)
Definition at line 489 of file connection_support.c.
References css_readn(), and CSS_TRUNCATE_BUFFER_SIZE.
Referenced by css_net_recv(), css_queue_data_packet(), css_queue_error_packet(), css_receive_data(), and css_receive_error().
int css_readn (SOCKET fd, char * ptr, int nbytes, int timeout)
Definition at line 364 of file connection_support.c.
References ARG_FILE_LINE, css_server_timeout_fn, css_set_networking_error(), er_log_debug, and NULL.
Referenced by css_check_magic_with_socket(), css_connect_to_master_server(), css_get_master_request(), css_net_recv(), css_process_get_server_ha_mode(), css_process_shutdown_request(), css_read_remaining_bytes(), css_receive_heartbeat_data(), and css_receive_heartbeat_request().
void css_register_check_server_alive_fn (CSS_CHECK_SERVER_ALIVE_FN callback_fn)
Definition at line 2131 of file connection_support.c.
References css_check_server_alive_fn.
Referenced by cas_init().
void css_register_server_timeout_fn (CSS_SERVER_TIMEOUT_FN callback_fn)
Definition at line 2212 of file connection_support.c.
References ip_info::address_list, ARG_FILE_LINE, assert, boot_db_name(), css_check_ip(), css_free_ip_info(), css_read_ip_info(), css_server_timeout_fn, dbname, er_errid(), ER_ERROR_SEVERITY, ER_FAILED, ER_INACCESSIBLE_IP, ER_INVALID_ACCESS_IP_CONTROL_FILE_FORMAT, ER_OPEN_ACCESS_LIST_FILE, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), er_set_with_oserror(), error(), free_and_init, i, INITIAL_IP_NUM, IP_BYTE_COUNT, NO_ERROR, NULL, ip_info::num_list, p, parse_int(), and strlen.
Referenced by cas_init().
int css_send_data (CSS_CONN_ENTRY * conn, unsigned short rid, const char * buffer, int buffer_size)
Definition at line 1852 of file connection_support.c.
References CANT_ALLOC_BUFFER, CONN_CLOSED, CONN_OPEN, CONNECTION_CLOSED, css_net_send2(), css_net_send4(), css_net_send6(), css_net_send8(), css_set_net_header(), DATA_TYPE, css_conn_entry::db_error, DEFAULT_HEADER_DATA, free_and_init, i, css_conn_entry::invalidate_snapshot, NULL, rc, and css_conn_entry::status.
Referenced by css_connect_to_master_server(), css_process_activate_heartbeat(), css_process_all_count_info(), css_process_all_list_info(), css_process_deact_confirm_no_server(), css_process_deact_confirm_stop_all(), css_process_deact_stop_all(), css_process_deactivate_heartbeat(), css_process_get_server_ha_mode(), css_process_ha_admin_info(), css_process_ha_deregister_by_args(), css_process_ha_deregister_by_pid(), css_process_ha_node_list_info(), css_process_ha_ping_host_info(), css_process_ha_process_list_info(), css_process_ha_start_util_process(), css_process_is_registered_ha_proc(), css_process_kill_all_ha_process(), css_process_kill_immediate(), css_process_kill_slave(), css_process_reconfig_heartbeat(), css_process_request_count_info(), css_process_server_count_info(), css_process_server_list_info(), css_process_server_state(), css_process_shutdown_time_info(), css_process_start_time_info(), css_reject_client_request(), css_send_data_to_client(), css_send_data_to_server(), css_send_reply_and_data_to_client(), css_send_reply_to_new_client_request(), css_send_to_existing_server(), and send_request_two_args().
int css_send_error (CSS_CONN_ENTRY * conn, unsigned short rid, const char * buffer, int buffer_size)
Definition at line 2041 of file connection_support.c.
References CONN_CLOSED, CONN_OPEN, CONNECTION_CLOSED, css_get_peer_name(), css_get_sock_name(), css_net_send2(), css_set_net_header(), css_conn_entry::db_error, DEFAULT_HEADER_DATA, ERROR_TYPE, css_conn_entry::fd, css_conn_entry::invalidate_snapshot, IS_INVALID_SOCKET, NO_ERRORS, OS_ERROR, and css_conn_entry::status.
Referenced by css_refuse_connection_request(), css_send_error_to_client(), and css_send_error_to_server().
static int css_send_io_vector (CSS_CONN_ENTRY * conn, struct iovec * vec_p, ssize_t total_len, int vector_length, int timeout) static
Definition at line 1013 of file connection_support.c.
References css_send_io_vector_with_socket(), css_shutdown_conn(), css_conn_entry::fd, NO_ERRORS, and rc.
Referenced by css_net_send2(), css_net_send4(), css_net_send6(), css_net_send8(), and css_net_send_buffer_only().
int css_send_io_vector_with_socket (SOCKET & socket, struct iovec * vec_p, ssize_t total_len, int vector_length, int timeout)
Definition at line 1027 of file connection_support.c.
References css_shutdown_socket(), css_vector_send(), ERROR_ON_WRITE, INVALID_SOCKET, IS_INVALID_SOCKET, NO_ERRORS, and rc.
Referenced by css_net_send3_with_socket(), css_net_send_with_socket(), and css_send_io_vector().
int css_send_magic (CSS_CONN_ENTRY * conn)
Definition at line 2460 of file connection_support.c.
References css_send_magic_with_socket(), and css_conn_entry::fd.
Referenced by css_common_connect().
int css_send_magic_with_socket (SOCKET & socket)
Definition at line 2466 of file connection_support.c.
References css_Net_magic, and css_net_send_with_socket().
Referenced by css_send_magic().
int css_send_request (CSS_CONN_ENTRY * conn, int command, unsigned short * request_id, const char * arg_buffer, int arg_buffer_size)
Definition at line 1803 of file connection_support.c.
References css_send_request_with_data_buffer().
Referenced by css_client_init(), css_common_connect(), get_server_state_from_master(), send_request_no_args(), send_request_one_arg(), and send_request_two_args().
int css_send_request_with_data_buffer (CSS_CONN_ENTRY * conn, int request, unsigned short * request_id, const char * arg_buffer, int arg_size, char * reply_buffer, int reply_size)
Definition at line 1510 of file connection_support.c.
References CANT_ALLOC_BUFFER, COMMAND_TYPE, CONN_OPEN, CONNECTION_CLOSED, css_get_request_id(), css_net_send(), css_net_send3(), css_net_send5(), css_net_send7(), css_queue_user_data_buffer(), css_send_request_with_data_buffer(), css_set_net_header(), DATA_TYPE, css_conn_entry::db_error, DEFAULT_HEADER_DATA, ERROR_ON_WRITE, free_and_init, i, css_conn_entry::invalidate_snapshot, NO_ERRORS, NULL, rc, and css_conn_entry::status.
Referenced by css_send_request(), css_send_request_to_server_with_buffer(), and css_send_request_with_data_buffer().
int css_send_request_with_socket (SOCKET & socket, int command, unsigned short * request_id, const char * arg_buffer, int arg_buffer_size)
Definition at line 1810 of file connection_support.c.
References COMMAND_TYPE, CONNECTION_CLOSED, css_net_send3_with_socket(), css_net_send_with_socket(), css_set_net_header(), DATA_TYPE, DEFAULT_HEADER_DATA, ERROR_ON_WRITE, IS_INVALID_SOCKET, NO_ERRORS, NULL, and NULL_TRAN_INDEX.
void css_set_io_vector (struct iovec * vec1_p, struct iovec * vec2_p, const char * buff, int len, int * templen)
Definition at line 994 of file connection_support.c.
References htonl().
Referenced by css_net_send2(), css_net_send3_with_socket(), css_net_send4(), css_net_send6(), css_net_send8(), and css_net_send_with_socket().
void css_set_net_header (NET_HEADER * header_p, int type, short function_code, int request_id, int buffer_size, int transaction_id, int invalidate_snapshot, int db_error)
Definition at line 1478 of file connection_support.c.
References packet_header::buffer_size, packet_header::db_error, packet_header::flags, packet_header::function_code, htonl(), htons(), NET_HEADER_FLAG_INVALIDATE_SNAPSHOT, packet_header::request_id, packet_header::transaction_id, and packet_header::type.
Referenced by css_send_data(), css_send_error(), css_send_request_with_data_buffer(), and css_send_request_with_socket().
static void css_set_networking_error (SOCKET fd) static
Definition at line 249 of file connection_support.c.
References ARG_FILE_LINE, css_sprintf_conn_infoids(), ER_CSS_RECV_OR_SEND, ER_ERROR_SEVERITY, er_set_with_oserror(), ERROR_ON_WRITE, NO_ERRORS, and rc.
Referenced by css_net_recv(), css_readn(), and css_vector_send().
static int css_sprintf_conn_infoids (SOCKET fd, const char ** client_user_name, const char ** client_host_name, int * client_pid) static
Definition at line 173 of file connection_support.c.
References css_find_conn_from_fd(), CUB_MAXHOSTNAMELEN, GETHOSTNAME, getuserid(), L_cuserid, NULL, and pid.
Referenced by css_default_server_timeout_fn(), and css_set_networking_error().
int css_user_access_status_start_scan (THREAD_ENTRY * thread_p, int type, DB_VALUE ** arg_values, int arg_cnt, void ** ptr)
Definition at line 2538 of file connection_support.c.
References ARG_FILE_LINE, assert, css_get_unused_access_status(), css_get_user_access_status(), css_make_access_status_exist_user(), css_Num_access_user, db_get_oid(), db_localdatetime(), db_make_datetime(), db_make_string_copy(), last_access_status::db_user, er_errid(), ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, last_access_status::host, NO_ERROR, NULL, last_access_status::program_name, showstmt_alloc_array_context(), showstmt_alloc_tuple_in_context(), showstmt_free_array_context(), and last_access_status::time.
Referenced by showstmt_scan_init().
int css_vector_send (SOCKET fd, struct iovec * vec[], int * len, int bytes_written, int timeout)
Definition at line 893 of file connection_support.c.
References ARG_FILE_LINE, css_set_networking_error(), er_log_debug, and i.
Referenced by css_net_recv(), and css_send_io_vector_with_socket().
Variable Documentation
CSS_CHECK_SERVER_ALIVE_FN css_check_server_alive_fn = css_default_check_server_alive_fn
Definition at line 109 of file connection_support.c.
Referenced by boot_client_all_finalize(), css_net_recv(), and css_register_check_server_alive_fn().
CSS_SERVER_TIMEOUT_FN css_server_timeout_fn = css_default_server_timeout_fn static
Definition at line 107 of file connection_support.c.
Referenced by css_readn(), and css_register_server_timeout_fn().
const int CSS_TCP_MIN_NUM_RETRIES = 3 static
Definition at line 102 of file connection_support.c.
int rv static
Definition at line 93 of file connection_support.c.