CUBRID Engine: src/executables/csql_launcher.c File Reference
csql_launcher.c File Reference
#include <stdio.h>
#include <stdarg.h>
#include "csql.h"
#include "message_catalog.h"
#include "environment_variable.h"
#include "intl_support.h"
#include "utility.h"
#include "util_support.h"
#include "cubrid_getopt.h"
Typedefs
typedef const char *(* CSQL_GET_MESSAGE) (int message_index)
typedef int(* CSQL) (const char *argv0, CSQL_ARGUMENT *csql_arg)
Functions
static void utility_csql_usage (void)
static void utility_csql_print (void)
static void utility_csql_print (int message_num,...)
int main (int argc, char *argv[])
Typedef Documentation
typedef int(* CSQL) (const char *argv0, CSQL_ARGUMENT *csql_arg)
Definition at line 37 of file csql_launcher.c.
typedef const char*(* CSQL_GET_MESSAGE) (int message_index)
Definition at line 36 of file csql_launcher.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 114 of file csql_launcher.c.
References CSQL_ARGUMENT::auto_commit, CSQL_ARGUMENT::column_delimiter, CSQL_ARGUMENT::column_enclosure, CSQL_ARGUMENT::command, CSQL_ARGUMENT::continue_on_error, CSQL_ARGUMENT::cs_mode, csql(), CSQL_COMMAND_L, CSQL_COMMAND_S, CSQL_CS_MODE_L, CSQL_CS_MODE_S, CSQL_ERROR_CONTINUE_L, CSQL_ERROR_CONTINUE_S, CSQL_INPUT_FILE_L, CSQL_INPUT_FILE_S, CSQL_LINE_OUTPUT_L, CSQL_LINE_OUTPUT_S, CSQL_LOADDB_OUTPUT_L, CSQL_LOADDB_OUTPUT_S, CSQL_NO_AUTO_COMMIT_L, CSQL_NO_AUTO_COMMIT_S, CSQL_NO_PAGER_L, CSQL_NO_PAGER_S, CSQL_NO_SINGLE_LINE_L, CSQL_NO_SINGLE_LINE_S, CSQL_NO_TRIGGER_ACTION_L, CSQL_NO_TRIGGER_ACTION_S, CSQL_OUTPUT_FILE_L, CSQL_OUTPUT_FILE_S, CSQL_PASSWORD_L, CSQL_PASSWORD_S, CSQL_PLAIN_OUTPUT_L, CSQL_PLAIN_OUTPUT_S, CSQL_QUERY_COLUMN_DELIMITER_L, CSQL_QUERY_COLUMN_DELIMITER_S, CSQL_QUERY_COLUMN_ENCLOSURE_L, CSQL_QUERY_COLUMN_ENCLOSURE_S, CSQL_QUERY_OUTPUT_L, CSQL_QUERY_OUTPUT_S, CSQL_READ_ONLY_L, CSQL_READ_ONLY_S, CSQL_SA_MODE_L, CSQL_SA_MODE_S, CSQL_SINGLE_LINE_L, CSQL_SINGLE_LINE_S, CSQL_SKIP_COL_NAMES_L, CSQL_SKIP_COL_NAMES_S, CSQL_SKIP_VACUUM_L, CSQL_SKIP_VACUUM_S, CSQL_STRING_WIDTH_L, CSQL_STRING_WIDTH_S, CSQL_SYSADM_L, CSQL_SYSADM_S, CSQL_USER_L, CSQL_USER_S, CSQL_WRITE_ON_STANDBY_L, CSQL_WRITE_ON_STANDBY_S, CSQL_ARGUMENT::db_name, ER_GENERIC_ERROR, error(), getopt_long(), CSQL_ARGUMENT::in_file_name, LIB_UTIL_CS_NAME, LIB_UTIL_SA_NAME, CSQL_ARGUMENT::line_output, CSQL_ARGUMENT::loaddb_output, MSGCAT_UTIL_GENERIC_ARGS_OVER, MSGCAT_UTIL_GENERIC_MISS_DBNAME, MSGCAT_UTIL_GENERIC_VERSION, CSQL_ARGUMENT::nopager, NULL, optarg, optind, CSQL_ARGUMENT::out_file_name, parse_int(), CSQL_ARGUMENT::passwd, CSQL_ARGUMENT::plain_output, print_usage(), CSQL_ARGUMENT::query_output, CSQL_ARGUMENT::read_only, CSQL_ARGUMENT::sa_mode, CSQL_ARGUMENT::single_line_execution, CSQL_ARGUMENT::skip_column_names, CSQL_ARGUMENT::skip_vacuum, strdup(), CSQL_ARGUMENT::string_width, strlen, CSQL_ARGUMENT::sysadm, CSQL_ARGUMENT::trigger_action_flag, CSQL_ARGUMENT::user_name, UTIL_CSQL_NAME, util_hide_password(), utility_csql_print(), utility_csql_usage(), utility_load_library(), utility_load_print_error(), utility_load_symbol(), utility_make_getopt_optstring(), VERSION_L, VERSION_S, and CSQL_ARGUMENT::write_on_standby.
static void utility_csql_print (void) static
Referenced by main().
static void utility_csql_print (int message_num, ...) static
Definition at line 76 of file csql_launcher.c.
References LIB_UTIL_SA_NAME, NULL, UTILITY_GENERIC_MSG_FUNC_NAME, utility_load_library(), utility_load_print_error(), and utility_load_symbol().
static void utility_csql_usage (void) static
Definition at line 46 of file csql_launcher.c.
References csql_get_message(), CSQL_MSG_USAGE, LIB_UTIL_SA_NAME, NULL, UTIL_CSQL_NAME, utility_load_library(), utility_load_print_error(), and utility_load_symbol().
Referenced by main().