CUBRID Engine: src/base/cubrid_getopt.h File Reference
cubrid_getopt.h File Reference
#include "config.h"
#include <sys/cdefs.h>
Classes
struct option
Macros
#define DllImport
#define no_argument 0
#define required_argument 1
#define optional_argument 2
Typedefs
typedef struct option GETOPT_LONG
Functions
int getopt (int, char *const *, const char *)
int getopt_long (int, char *const *, const char *, const struct option *, int *)
Variables
DllImport int optreset
DllImport char * optarg
DllImport int opterr
DllImport int optind
DllImport int optopt
Macro Definition Documentation
#define DllImport
Definition at line 41 of file cubrid_getopt.h.
#define no_argument 0
Definition at line 49 of file cubrid_getopt.h.
Referenced by getopt_long().
#define optional_argument 2
Definition at line 51 of file cubrid_getopt.h.
Referenced by getopt_long().
#define required_argument 1
Definition at line 50 of file cubrid_getopt.h.
Referenced by getopt_long().
Typedef Documentation
typedef struct option GETOPT_LONG
Definition at line 88 of file cubrid_getopt.h.
Function Documentation
int getopt (int , char *const * , const char *)
Definition at line 331 of file cubrid_getopt_long.c.
References getopt_internal(), nonopt_start, optind, and permute_args().
Referenced by admin_getid_cmd(), get_args(), and main().
int getopt_long (int , char *const * , const char * , const struct option * , int *)
Definition at line 361 of file cubrid_getopt_long.c.
References _DIAGASSERT, BADARG, BADCH, EMSG, option::flag, getopt_internal(), option::has_arg, i, option::name, no_argument, nonopt_start, NULL, optind, optional_argument, permute_args(), place, PRINT_ERROR, required_argument, strlen, option::val, and xwarnx().
Referenced by main(), us_hb_status_get_options(), us_hb_stop_get_options(), us_hb_util_get_options(), and util_parse_argument().
Variable Documentation
DllImport char* optarg
Definition at line 55 of file cubrid_getopt_long.c.
Referenced by admin_getid_cmd(), get_args(), main(), us_hb_status_get_options(), us_hb_stop_get_options(), us_hb_util_get_options(), and util_parse_argument().
DllImport int opterr
Definition at line 51 of file cubrid_getopt_long.c.
DllImport int optind
Definition at line 52 of file cubrid_getopt_long.c.
Referenced by get_args(), getopt(), getopt_internal(), getopt_long(), main(), us_hb_status_get_options(), us_hb_stop_get_options(), us_hb_util_get_options(), and util_parse_argument().
DllImport int optopt
Definition at line 53 of file cubrid_getopt_long.c.
DllImport int optreset
Definition at line 54 of file cubrid_getopt_long.c.