CUBRID Engine: src/query/cursor.h File Reference
cursor.h File Reference
#include "config.h"
#include "error_manager.h"
#include "query_list.h"
#include "storage_common.h"
Classes
struct cursor_id
Macros
#define cursor_free_list_id(list_id)
#define cursor_free_self_list_id(list_id)
Typedefs
typedef struct cursor_id CURSOR_ID
Enumerations
enum { DB_CURSOR_SEEK_SET = 1, DB_CURSOR_SEEK_CUR, DB_CURSOR_SEEK_END }
enum CURSOR_POSITION { C_BEFORE = 1, C_ON, C_AFTER }
Functions
int cursor_copy_list_id (QFILE_LIST_ID *dest_list_id, const QFILE_LIST_ID *src_list_id)
int cursor_copy_vobj_to_dbvalue (struct or_buf *buf, DB_VALUE *db_value)
int cursor_fetch_page_having_tuple (CURSOR_ID *cursor_id, VPID *vpid, int position, int offset)
bool cursor_open (CURSOR_ID *cursor_id, QFILE_LIST_ID *list_id, bool updatable, bool oid_included)
int cursor_next_tuple (CURSOR_ID *cursor_id)
int cursor_get_tuple_value_list (CURSOR_ID *cursor_id, int size, DB_VALUE *value_list)
void cursor_close (CURSOR_ID *cursor_id)
DB_FETCH_MODE cursor_set_prefetch_lock_mode (CURSOR_ID *cursor_id, DB_FETCH_MODE mode)
bool cursor_set_copy_tuple_value (CURSOR_ID *cursor_id, bool copy)
int cursor_set_oid_columns (CURSOR_ID *cursor_id, int *oid_col_no, int oid_col_no_cnt)
void cursor_free (CURSOR_ID *cursor_id)
int cursor_get_current_oid (CURSOR_ID *cursor_id, DB_VALUE *crs_value)
int cursor_prev_tuple (CURSOR_ID *cursor_id)
int cursor_first_tuple (CURSOR_ID *cursor_id)
int cursor_last_tuple (CURSOR_ID *cursor_id)
int cursor_get_tuple_value (CURSOR_ID *result, int index, DB_VALUE *value)
Macro Definition Documentation
#define cursor_free_list_id (list_id)
Value:
do { \
          QFILE_LIST_ID *list_id_p = (QFILE_LIST_ID *) (list_id); \
          if (list_id_p != NULL) { \
            if (list_id_p->last_pgptr) { \
              free_and_init (list_id_p->last_pgptr); \
            } \
            if (list_id_p->tpl_descr.f_valp) { \
              free_and_init (list_id_p->tpl_descr.f_valp); \
            } \
            if (list_id_p->tpl_descr.clear_f_val_at_clone_decache) { \
              free_and_init (list_id_p->tpl_descr.clear_f_val_at_clone_decache); \
            } \
            if (list_id_p->sort_list) { \
              free_and_init (list_id_p->sort_list); \
            } \
            if (list_id_p->type_list.domp) { \
              free_and_init (list_id_p->type_list.domp); \
            } \
          } \
        } while (0)
Definition at line 86 of file cursor.h.
Referenced by cursor_free().
#define cursor_free_self_list_id (list_id)
Value:
do { \
          cursor_free_list_id (list_id); \
          free_and_init (list_id); \
        } while (0)
Definition at line 108 of file cursor.h.
Referenced by build_xasl_for_server_delete(), delete_real_class(), do_execute_delete(), do_execute_insert(), do_execute_merge(), do_execute_update(), do_insert_at_server(), do_merge(), insert_subquery_results(), net_client_request_with_callback(), pt_evaluate_tree_internal(), pt_free_query_etc_area(), pt_new_query_result_descriptor(), pt_set_table_to_db(), update_at_server(), and update_real_class().
Typedef Documentation
typedef struct cursor_id CURSOR_ID
Definition at line 51 of file cursor.h.
Enumeration Type Documentation
anonymous enum
Enumerator
DB_CURSOR_SEEK_SET
DB_CURSOR_SEEK_CUR
DB_CURSOR_SEEK_END
Definition at line 37 of file cursor.h.
enum CURSOR_POSITION
Enumerator
C_BEFORE
C_ON
C_AFTER
Definition at line 44 of file cursor.h.
Function Documentation
void cursor_close (CURSOR_ID * cursor_id)
Definition at line 1381 of file cursor.c.
References assert, cursor_id::buffer_tuple_count, C_BEFORE, cursor_id::current_tuple_length, cursor_id::current_tuple_no, cursor_id::current_tuple_offset, cursor_id::current_tuple_p, cursor_id::current_vpid, cursor_free(), cursor_initialize_current_tuple_value_position(), cursor_id::header_vpid, cursor_id::is_updatable, cursor_id::next_vpid, NULL, NULL_PAGEID, cursor_id::oid_col_no, cursor_id::oid_col_no_cnt, cursor_id::oid_ent_count, vpid::pageid, cursor_id::position, cursor_id::query_id, and cursor_id::tuple_no.
Referenced by cursor_fetch_page_having_tuple(), db_query_end_internal(), delete_list_by_oids(), do_execute_session_statement(), insert_subquery_results(), method_clear_scan_buffer(), method_invoke_for_server(), pt_get_one_tuple_from_list_id(), pt_set_table_to_db(), and update_objs_for_list_file().
int cursor_copy_list_id (QFILE_LIST_ID * dest_list_id, const QFILE_LIST_ID * src_list_id)
Definition at line 105 of file cursor.c.
References qfile_tuple_descriptor::clear_f_val_at_clone_decache, CURSOR_BUFFER_SIZE, DB_SIZEOF, qfile_tuple_value_type_list::domp, ER_FAILED, qfile_tuple_descriptor::f_valp, qfile_list_id::last_pgptr, NO_ERROR, NULL, qfile_list_id::sort_list, qfile_list_id::tpl_descr, qfile_tuple_value_type_list::type_cnt, and qfile_list_id::type_list.
Referenced by cursor_open().
int cursor_copy_vobj_to_dbvalue (struct or_buf * buf, DB_VALUE * db_value)
Definition at line 334 of file cursor.c.
References pr_type::data_readval(), DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_make_object(), DB_TYPE_VOBJ, db_value_domain_init(), ER_FAILED, pr_type::id, NO_ERROR, NULL, pr_clear_value(), pr_type_from_id(), rc, and vid_vobj_to_object().
Referenced by cursor_get_oid_from_vobj(), cursor_get_tuple_value_to_dbvalue(), and vid_decode_object().
int cursor_fetch_page_having_tuple (CURSOR_ID * cursor_id, VPID * vpid, int position, int offset)
Definition at line 992 of file cursor.c.
References assert, cursor_id::buffer, cursor_id::buffer_tuple_count, cleanup(), cubregex::count(), cursor_id::current_tuple_offset, cursor_id::current_tuple_p, cursor_id::current_vpid, cursor_buffer_last_page(), cursor_close(), cursor_construct_tuple_from_overflow_pages(), cursor_get_tuple_value_list(), cursor_has_first_hidden_oid(), cursor_initialize_current_tuple_value_position(), cursor_next_tuple(), cursor_open(), cursor_point_current_tuple(), cursor_prefetch_column_oids(), cursor_prefetch_first_hidden_oid(), DB_CURSOR_SUCCESS, db_get_set(), db_set_print(), DB_TYPE_VOBJ, db_value_clear(), db_value_print(), DB_VALUE_TYPE, ER_FAILED, free_and_init, i, NO_ERROR, NULL, NULL_PAGEID, cursor_id::oid_col_no, cursor_id::oid_col_no_cnt, QFILE_GET_OVERFLOW_PAGE_ID, cursor_id::query_id, TP_IS_SET_TYPE, qfile_tuple_value_type_list::type_cnt, qfile_list_id::type_list, and VPID_EQ.
Referenced by cursor_first_tuple(), cursor_last_tuple(), cursor_next_tuple(), cursor_prev_tuple(), and db_query_set_tplpos().
int cursor_first_tuple (CURSOR_ID * cursor_id)
Definition at line 1652 of file cursor.c.
References assert, cursor_id::buffer_tuple_count, C_AFTER, C_ON, cursor_id::current_vpid, cursor_fetch_page_having_tuple(), DB_CURSOR_END, DB_CURSOR_ERROR, DB_CURSOR_SUCCESS, FIRST_TPL, qfile_list_id::first_vpid, cursor_id::list_id, NO_ERROR, NULL, cursor_id::position, QFILE_COPY_VPID, qfile_list_id::tuple_cnt, cursor_id::tuple_no, and VPID_ISNULL.
Referenced by db_query_first_tuple().
void cursor_free (CURSOR_ID * cursor_id)
Definition at line 1342 of file cursor.c.
References assert, cursor_id::buffer, cursor_id::buffer_area, cursor_id::buffer_filled_size, cursor_free_list_id, free_and_init, i, cursor_id::list_id, cursor_id::mop_set, NULL, cursor_id::oid_ent_count, cursor_id::oid_set, qfile_tuple_record::tpl, and cursor_id::tuple_record.
Referenced by cursor_close().
int cursor_get_current_oid (CURSOR_ID * cursor_id, DB_VALUE * crs_value)
Definition at line 1449 of file cursor.c.
References assert, cursor_get_first_tuple_value(), cursor_peek_tuple(), ER_FAILED, cursor_id::is_copy_tuple_value, cursor_id::is_oid_included, cursor_id::list_id, NULL, and qfile_list_id::type_list.
Referenced by db_query_get_tuple_oid(), res_delete_row_internal(), and rs_set_db_value().
int cursor_get_tuple_value (CURSOR_ID * result, int index, DB_VALUE * value)
Definition at line 1734 of file cursor.c.
References ARG_FILE_LINE, assert, cursor_get_tuple_value_from_list(), cursor_peek_tuple(), ER_ERROR_SEVERITY, ER_FAILED, ER_QPROC_INVALID_TPLVAL_INDEX, er_set(), cursor_id::is_oid_included, cursor_id::list_id, NULL, qfile_tuple_value_type_list::type_cnt, and qfile_list_id::type_list.
Referenced by cursor_get_tuple_value_list(), db_query_get_tuple_value(), and pt_evaluate_tree_internal().
int cursor_get_tuple_value_list (CURSOR_ID * cursor_id, int size, DB_VALUE * value_list)
Definition at line 1778 of file cursor.c.
References assert, cursor_get_tuple_value(), ER_FAILED, NO_ERROR, and NULL.
Referenced by cursor_fetch_page_having_tuple(), db_query_get_tuple_valuelist(), delete_list_by_oids(), do_execute_session_statement(), insert_subquery_results(), method_invoke_for_server(), method_receive_results_for_stand_alone(), pt_get_one_tuple_from_list_id(), pt_set_table_to_db(), and update_objs_for_list_file().
int cursor_last_tuple (CURSOR_ID * cursor_id)
Definition at line 1696 of file cursor.c.
References assert, C_ON, cursor_id::current_vpid, cursor_fetch_page_having_tuple(), DB_CURSOR_END, DB_CURSOR_ERROR, DB_CURSOR_SUCCESS, qfile_list_id::first_vpid, LAST_TPL, qfile_list_id::last_vpid, cursor_id::list_id, NO_ERROR, NULL, cursor_id::position, QFILE_COPY_VPID, qfile_list_id::tuple_cnt, cursor_id::tuple_no, and VPID_ISNULL.
Referenced by db_query_last_tuple().
int cursor_next_tuple (CURSOR_ID * cursor_id)
Definition at line 1482 of file cursor.c.
References ARG_FILE_LINE, assert, cursor_id::buffer, cursor_id::buffer_tuple_count, C_AFTER, C_BEFORE, C_ON, cursor_id::current_tuple_length, cursor_id::current_tuple_no, cursor_id::current_tuple_offset, cursor_id::current_tuple_p, cursor_id::current_vpid, cursor_fetch_page_having_tuple(), cursor_initialize_current_tuple_value_position(), DB_CURSOR_END, DB_CURSOR_ERROR, DB_CURSOR_SUCCESS, ER_ERROR_SEVERITY, ER_QPROC_UNKNOWN_CRSPOS, er_set(), FIRST_TPL, qfile_list_id::first_vpid, cursor_id::list_id, NO_ERROR, NULL, NULL_PAGEID, cursor_id::position, QFILE_COPY_VPID, QFILE_GET_NEXT_PAGE_ID, QFILE_GET_NEXT_VPID, QFILE_GET_TUPLE_LENGTH, cursor_id::query_id, qfile_list_id::tuple_cnt, cursor_id::tuple_no, and VPID_ISNULL.
Referenced by cursor_fetch_page_having_tuple(), db_query_next_tuple(), delete_list_by_oids(), do_execute_session_statement(), insert_subquery_results(), method_invoke_for_server(), method_receive_results_for_stand_alone(), pt_get_one_tuple_from_list_id(), pt_set_table_to_db(), and update_objs_for_list_file().
bool cursor_open (CURSOR_ID * cursor_id, QFILE_LIST_ID * list_id, bool updatable, bool oid_included)
Definition at line 1194 of file cursor.c.
References assert, cursor_id::buffer, cursor_id::buffer_area, cursor_id::buffer_filled_size, cursor_id::buffer_tuple_count, C_BEFORE, cursor_id::current_tuple_length, cursor_id::current_tuple_no, cursor_id::current_tuple_offset, cursor_id::current_tuple_p, cursor_id::current_vpid, cursor_allocate_oid_buffer(), CURSOR_BUFFER_AREA_SIZE, cursor_copy_list_id(), cursor_initialize_current_tuple_value_position(), DB_FETCH_READ, cursor_id::header_vpid, cursor_id::is_copy_tuple_value, cursor_id::is_oid_included, cursor_id::is_updatable, cursor_id::list_id, cursor_id::mop_set, cursor_id::next_vpid, NO_ERROR, NULL, cursor_id::oid_col_no, cursor_id::oid_col_no_cnt, cursor_id::oid_ent_count, cursor_id::oid_set, cursor_id::on_overflow, cursor_id::position, cursor_id::prefetch_lock_mode, QFILE_CLEAR_LIST_ID, cursor_id::query_id, qfile_list_id::query_id, qfile_tuple_record::size, qfile_tuple_record::tpl, cursor_id::tuple_no, cursor_id::tuple_record, qfile_tuple_value_type_list::type_cnt, qfile_list_id::type_list, and VPID_SET_NULL.
Referenced by cursor_fetch_page_having_tuple(), delete_list_by_oids(), do_execute_session_statement(), insert_subquery_results(), method_invoke_for_server(), method_invoke_from_stand_alone(), pt_get_one_tuple_from_list_id(), pt_new_query_result_descriptor(), pt_set_table_to_db(), and update_objs_for_list_file().
int cursor_prev_tuple (CURSOR_ID * cursor_id)
Definition at line 1568 of file cursor.c.
References ARG_FILE_LINE, assert, cursor_id::buffer, C_AFTER, C_BEFORE, C_ON, cursor_id::current_tuple_length, cursor_id::current_tuple_no, cursor_id::current_tuple_offset, cursor_id::current_tuple_p, cursor_id::current_vpid, cursor_fetch_page_having_tuple(), cursor_initialize_current_tuple_value_position(), DB_CURSOR_END, DB_CURSOR_ERROR, DB_CURSOR_SUCCESS, ER_ERROR_SEVERITY, ER_QPROC_UNKNOWN_CRSPOS, er_set(), qfile_list_id::first_vpid, LAST_TPL, qfile_list_id::last_vpid, cursor_id::list_id, NO_ERROR, NULL, NULL_PAGEID, cursor_id::position, QFILE_COPY_VPID, QFILE_GET_PREV_PAGE_ID, QFILE_GET_PREV_TUPLE_LENGTH, QFILE_GET_PREV_VPID, QFILE_GET_TUPLE_LENGTH, cursor_id::tuple_no, and VPID_ISNULL.
Referenced by db_query_prev_tuple().
bool cursor_set_copy_tuple_value (CURSOR_ID * cursor_id, bool copy)
Definition at line 1291 of file cursor.c.
References assert, cursor_id::is_copy_tuple_value, and NULL.
Referenced by db_query_set_copy_tplvalue().
int cursor_set_oid_columns (CURSOR_ID * cursor_id, int * oid_col_no, int oid_col_no_cnt)
Definition at line 1322 of file cursor.c.
References cursor_allocate_oid_buffer(), ER_FAILED, cursor_id::is_oid_included, cursor_id::is_updatable, NO_ERROR, NULL, cursor_id::oid_col_no, and cursor_id::oid_col_no_cnt.
Referenced by db_query_prefetch_columns(), method_invoke_for_server(), and method_invoke_from_stand_alone().
DB_FETCH_MODE cursor_set_prefetch_lock_mode (CURSOR_ID * cursor_id, DB_FETCH_MODE mode)
Definition at line 1267 of file cursor.c.
References assert, mode, NULL, and cursor_id::prefetch_lock_mode.
Referenced by update_objs_for_list_file().