CUBRID Engine: src/heaplayers/customheaps.h File Reference
customheaps.h File Reference
#include "config.h"
Functions
UINTPTR hl_register_fixed_heap (int chunk_size)
void hl_unregister_fixed_heap (UINTPTR heap_id)
void * hl_fixed_alloc (UINTPTR heap_id, size_t sz)
void hl_fixed_free (UINTPTR heap_id, void *ptr)
UINTPTR hl_register_ostk_heap (int chunk_size)
void hl_unregister_ostk_heap (UINTPTR heap_id)
void * hl_ostk_alloc (UINTPTR heap_id, size_t sz)
void hl_ostk_free (UINTPTR heap_id, void *ptr)
UINTPTR hl_register_lea_heap (void)
void hl_unregister_lea_heap (UINTPTR heap_id)
void * hl_lea_alloc (UINTPTR heap_id, size_t sz)
void * hl_lea_realloc (UINTPTR heap_id, void *ptr, size_t sz)
void hl_lea_free (UINTPTR heap_id, void *ptr)
void hl_clear_lea_heap (UINTPTR heap_id)
Function Documentation
void hl_clear_lea_heap (UINTPTR heap_id)
Definition at line 272 of file lea_heap.c.
References assert, hl_mspace_s::base, hl_mspace_s::base_size, destroy_mspace_internal(), MOCK_LEA_HEAP_ID, hl_mspace_s::ms, NULL, prm_get_bool_value(), and PRM_ID_USE_SYSTEM_MALLOC.
Referenced by db_clear_private_heap().
void* hl_fixed_alloc (UINTPTR heap_id, size_t sz)
Definition at line 66 of file customheaps.cpp.
References HL::LockedHeap< LockType, Super >::malloc(), and NULL.
Referenced by db_fixed_alloc().
void hl_fixed_free (UINTPTR heap_id, void * ptr)
Definition at line 77 of file customheaps.cpp.
References HL::LockedHeap< LockType, Super >::free().
Referenced by db_fixed_free().
void* hl_lea_alloc (UINTPTR heap_id, size_t sz)
Definition at line 326 of file lea_heap.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), hl_mspace_s::ms, NULL, p, prm_get_bool_value(), and PRM_ID_USE_SYSTEM_MALLOC.
Referenced by db_private_alloc_debug(), and db_ws_alloc().
void hl_lea_free (UINTPTR heap_id, void * ptr)
Definition at line 395 of file lea_heap.c.
References hl_mspace_s::ms, NULL, prm_get_bool_value(), and PRM_ID_USE_SYSTEM_MALLOC.
Referenced by db_private_free_debug(), and db_ws_free().
void* hl_lea_realloc (UINTPTR heap_id, void * ptr, size_t sz)
Definition at line 361 of file lea_heap.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), hl_mspace_s::ms, NULL, p, prm_get_bool_value(), and PRM_ID_USE_SYSTEM_MALLOC.
Referenced by db_private_realloc_debug(), and db_ws_realloc().
void* hl_ostk_alloc (UINTPTR heap_id, size_t sz)
Definition at line 119 of file customheaps.cpp.
References HL::SizeHeap< SuperHeap >::malloc(), and NULL.
Referenced by db_ostk_alloc().
void hl_ostk_free (UINTPTR heap_id, void * ptr)
Definition at line 130 of file customheaps.cpp.
References HL::SizeHeap< SuperHeap >::free().
Referenced by db_ostk_alloc().
UINTPTR hl_register_fixed_heap (int chunk_size)
Definition at line 43 of file customheaps.cpp.
References HL::ZoneHeap< SuperHeap, ChunkSize >::reset().
Referenced by db_create_fixed_heap().
UINTPTR hl_register_lea_heap (void)
Definition at line 213 of file lea_heap.c.
References hl_mspace_s::base, hl_mspace_s::base_size, hl_mspace_s::header, LEA_HEAP_BASE_SIZE, MMAP_TRACE_H_INIT, MOCK_LEA_HEAP_ID, hl_mspace_s::ms, NULL, prm_get_bool_value(), and PRM_ID_USE_SYSTEM_MALLOC.
Referenced by db_create_private_heap(), and db_create_workspace_heap().
UINTPTR hl_register_ostk_heap (int chunk_size)
Definition at line 96 of file customheaps.cpp.
References HL::ObstackHeap< ChunkSize, SuperHeap >::reset().
Referenced by db_create_ostk_heap().
void hl_unregister_fixed_heap (UINTPTR heap_id)
Definition at line 55 of file customheaps.cpp.
Referenced by db_destroy_fixed_heap().
void hl_unregister_lea_heap (UINTPTR heap_id)
Definition at line 299 of file lea_heap.c.
References assert, destroy_mspace_internal(), MOCK_LEA_HEAP_ID, NULL, prm_get_bool_value(), and PRM_ID_USE_SYSTEM_MALLOC.
Referenced by db_destroy_private_heap(), and db_destroy_workspace_heap().
void hl_unregister_ostk_heap (UINTPTR heap_id)
Definition at line 108 of file customheaps.cpp.
Referenced by db_destroy_ostk_heap().