CUBRID Engine: src/heaplayers/customheaps.cpp File Reference
customheaps.cpp File Reference
#include <stdlib.h>
#include <new>
#include "porting_inline.hpp"
#include "system.h"
#include "heaplayers.h"
Classes
class TheFixedHeapType
class TheObstackHeapType
Functions
UINTPTR hl_register_fixed_heap (int chunk_size)
void hl_unregister_fixed_heap (UINTPTR heap_id)
void * hl_fixed_alloc (UINTPTR heap_id, size_t sz)
void hl_fixed_free (UINTPTR heap_id, void *ptr)
UINTPTR hl_register_ostk_heap (int chunk_size)
void hl_unregister_ostk_heap (UINTPTR heap_id)
void * hl_ostk_alloc (UINTPTR heap_id, size_t sz)
void hl_ostk_free (UINTPTR heap_id, void *ptr)
Variables
volatile int anyThreadCreatedInHL = 1
Function Documentation
void* hl_fixed_alloc (UINTPTR heap_id, size_t sz)
Definition at line 66 of file customheaps.cpp.
References HL::LockedHeap< LockType, Super >::malloc(), and NULL.
Referenced by db_fixed_alloc().
void hl_fixed_free (UINTPTR heap_id, void * ptr)
Definition at line 77 of file customheaps.cpp.
References HL::LockedHeap< LockType, Super >::free().
Referenced by db_fixed_free().
void* hl_ostk_alloc (UINTPTR heap_id, size_t sz)
Definition at line 119 of file customheaps.cpp.
References HL::SizeHeap< SuperHeap >::malloc(), and NULL.
Referenced by db_ostk_alloc().
void hl_ostk_free (UINTPTR heap_id, void * ptr)
Definition at line 130 of file customheaps.cpp.
References HL::SizeHeap< SuperHeap >::free().
Referenced by db_ostk_alloc().
UINTPTR hl_register_fixed_heap (int chunk_size)
Definition at line 43 of file customheaps.cpp.
References HL::ZoneHeap< SuperHeap, ChunkSize >::reset().
Referenced by db_create_fixed_heap().
UINTPTR hl_register_ostk_heap (int chunk_size)
Definition at line 96 of file customheaps.cpp.
References HL::ObstackHeap< ChunkSize, SuperHeap >::reset().
Referenced by db_create_ostk_heap().
void hl_unregister_fixed_heap (UINTPTR heap_id)
Definition at line 55 of file customheaps.cpp.
Referenced by db_destroy_fixed_heap().
void hl_unregister_ostk_heap (UINTPTR heap_id)
Definition at line 108 of file customheaps.cpp.
Referenced by db_destroy_ostk_heap().
Variable Documentation
volatile int anyThreadCreatedInHL = 1
Definition at line 31 of file customheaps.cpp.