CUBRID Engine: src/compat/db_old.c File Reference
db_old.c File Reference
#include "config.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <ctype.h>
#include <assert.h>
#include "authenticate.h"
#include "system_parameter.h"
#include "storage_common.h"
#include "db.h"
#include "class_object.h"
#include "object_print.h"
#include "server_interface.h"
#include "boot_cl.h"
#include "locator_cl.h"
#include "schema_manager.h"
#include "schema_template.h"
#include "object_accessor.h"
#include "set_object.h"
#include "virtual_object.h"
#include "parser.h"
Functions
int db_list_length (DB_LIST *list)
DB_OBJECT * db_objlist_get (DB_OBJLIST *list, int index)
void db_objlist_print (DB_OBJLIST *list)
DB_NAMELIST * db_namelist_copy (DB_NAMELIST *list)
DB_NAMELIST * db_namelist_sort (DB_NAMELIST *names)
void db_namelist_remove (DB_NAMELIST **list, const char *name)
void db_namelist_print (DB_NAMELIST *list)
DB_NAMELIST * db_get_attribute_names (MOP obj)
DB_NAMELIST * db_get_shared_attribute_names (MOP obj)
DB_NAMELIST * db_get_class_attribute_names (MOP obj)
DB_NAMELIST * db_get_ordered_attribute_names (MOP obj)
DB_NAMELIST * db_get_method_names (MOP obj)
DB_NAMELIST * db_get_class_method_names (MOP obj)
DB_NAMELIST * db_get_superclass_names (MOP obj)
DB_NAMELIST * db_get_subclass_names (MOP obj)
DB_NAMELIST * db_get_method_file_names (MOP obj)
const char * db_get_method_function (MOP obj, const char *name)
DB_DOMAIN * db_get_attribute_domain (MOP obj, const char *name)
DB_TYPE db_get_attribute_type (MOP obj, const char *name)
DB_OBJECT * db_get_attribute_class (MOP obj, const char *name)
int db_is_indexed (MOP classmop, const char *attname)
int db_print_mop (DB_OBJECT *obj, char *buffer, int maxlen)
char * db_get_method_source_file (MOP obj, const char *name)
Function Documentation
DB_OBJECT* db_get_attribute_class (MOP obj, const char * name)
Definition at line 675 of file db_old.c.
References ARG_FILE_LINE, CHECK_CONNECT_NULL, ER_ERROR_SEVERITY, ER_OBJ_INVALID_ARGUMENTS, er_set(), NULL, and sm_att_class().
DB_DOMAIN* db_get_attribute_domain (MOP obj, const char * name)
Definition at line 615 of file db_old.c.
References au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_CONNECT_NULL, classobj_find_attribute(), sm_attribute::domain, NO_ERROR, NULL, and sm_filter_domain().
DB_NAMELIST* db_get_attribute_names (MOP obj)
Definition at line 257 of file db_old.c.
References sm_class::attributes, au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_CONNECT_NULL, db_namelist_sort(), sm_attribute::header, sm_component::name, sm_component::next, nlist_append(), nlist_free(), NO_ERROR, and NULL.
DB_TYPE db_get_attribute_type (MOP obj, const char * name)
Definition at line 647 of file db_old.c.
References ARG_FILE_LINE, CHECK_CONNECT_ZERO_TYPE, DB_TYPE_NULL, ER_ERROR_SEVERITY, ER_OBJ_INVALID_ARGUMENTS, er_set(), NULL, and sm_att_type_id().
Referenced by db_is_updatable_attribute().
DB_NAMELIST* db_get_class_attribute_names (MOP obj)
Definition at line 331 of file db_old.c.
References au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_CONNECT_NULL, sm_class::class_attributes, db_namelist_sort(), sm_attribute::header, sm_component::name, sm_component::next, nlist_append(), nlist_free(), NO_ERROR, and NULL.
DB_NAMELIST* db_get_class_method_names (MOP obj)
Definition at line 431 of file db_old.c.
References au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_CONNECT_NULL, sm_class::class_methods, db_namelist_sort(), sm_method::header, sm_component::name, sm_component::next, nlist_append(), nlist_free(), NO_ERROR, and NULL.
DB_NAMELIST* db_get_method_file_names (MOP obj)
Definition at line 548 of file db_old.c.
References au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_CONNECT_NULL, db_namelist_sort(), sm_class::method_files, sm_method_file::name, sm_method_file::next, nlist_append(), nlist_free(), NO_ERROR, and NULL.
const char* db_get_method_function (MOP obj, const char * name)
Definition at line 582 of file db_old.c.
References au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_CONNECT_NULL, classobj_find_method(), sm_method_signature::function_name, NO_ERROR, NULL, and sm_method::signatures.
DB_NAMELIST* db_get_method_names (MOP obj)
Definition at line 398 of file db_old.c.
References au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_CONNECT_NULL, db_namelist_sort(), sm_method::header, sm_class::methods, sm_component::name, sm_component::next, nlist_append(), nlist_free(), NO_ERROR, and NULL.
char* db_get_method_source_file (MOP obj, const char * name)
Definition at line 761 of file db_old.c.
References CHECK_2ARGS_NULL, CHECK_CONNECT_NULL, and sm_get_method_source_file().
DB_NAMELIST* db_get_ordered_attribute_names (MOP obj)
Definition at line 366 of file db_old.c.
References au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_CONNECT_NULL, sm_attribute::header, sm_component::name, nlist_append(), nlist_free(), NO_ERROR, NULL, sm_attribute::order_link, and sm_class::ordered_attributes.
DB_NAMELIST* db_get_shared_attribute_names (MOP obj)
Definition at line 295 of file db_old.c.
References au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_CONNECT_NULL, db_namelist_sort(), sm_attribute::header, sm_component::name, sm_component::next, nlist_append(), nlist_free(), NO_ERROR, NULL, and sm_class::shared.
DB_NAMELIST* db_get_subclass_names (MOP obj)
Definition at line 506 of file db_old.c.
References assert, au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_CONNECT_NULL, db_namelist_sort(), er_errid(), db_objlist::next, nlist_append(), nlist_free(), NO_ERROR, NULL, db_objlist::op, sm_get_ch_name(), and sm_class::users.
DB_NAMELIST* db_get_superclass_names (MOP obj)
Definition at line 464 of file db_old.c.
References assert, au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_CONNECT_NULL, db_namelist_sort(), er_errid(), sm_class::inheritance, db_objlist::next, nlist_append(), nlist_free(), NO_ERROR, NULL, db_objlist::op, and sm_get_ch_name().
int db_is_indexed (MOP classmop, const char * attname)
Definition at line 705 of file db_old.c.
References CHECK_2ARGS_ZERO, CHECK_CONNECT_FALSE, NO_ERROR, and sm_get_index().
int db_list_length (DB_LIST * list)
Definition at line 69 of file db_old.c.
References ws_list_length().
Referenced by db_fetch_list(), and sch_trigger().
DB_NAMELIST* db_namelist_copy (DB_NAMELIST * list)
Definition at line 148 of file db_old.c.
References CHECK_CONNECT_NULL, and nlist_copy().
void db_namelist_print (DB_NAMELIST * list)
Definition at line 233 of file db_old.c.
References db_namelist::name, db_namelist::next, and NULL.
void db_namelist_remove (DB_NAMELIST ** list, const char * name)
Definition at line 213 of file db_old.c.
References db_namelist::next, nlist_free(), nlist_remove(), and NULL.
DB_NAMELIST* db_namelist_sort (DB_NAMELIST * names)
Definition at line 170 of file db_old.c.
References db_namelist::name, db_namelist::next, and NULL.
Referenced by db_get_attribute_names(), db_get_class_attribute_names(), db_get_class_method_names(), db_get_method_file_names(), db_get_method_names(), db_get_shared_attribute_names(), db_get_subclass_names(), and db_get_superclass_names().
DB_OBJECT* db_objlist_get (DB_OBJLIST * list, int index)
Definition at line 96 of file db_old.c.
References i, db_objlist::next, and NULL.
void db_objlist_print (DB_OBJLIST * list)
Definition at line 121 of file db_old.c.
References db_objlist::next, NULL, db_objlist::op, db_identifier::pageid, db_identifier::slotid, db_identifier::volid, and WS_OID.
int db_print_mop (DB_OBJECT * obj, char * buffer, int maxlen)
Definition at line 733 of file db_old.c.
References CHECK_2ARGS_ZERO, CHECK_CONNECT_ZERO, and help_describe_mop().
Referenced by object_to_string().