CUBRID Engine: src/compat/db_obj.c File Reference
db_obj.c File Reference
#include "config.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <ctype.h>
#include <assert.h>
#include "system_parameter.h"
#include "storage_common.h"
#include "db.h"
#include "class_object.h"
#include "object_print.h"
#include "server_interface.h"
#include "boot_cl.h"
#include "locator_cl.h"
#include "schema_manager.h"
#include "schema_template.h"
#include "object_accessor.h"
#include "set_object.h"
#include "virtual_object.h"
#include "execute_schema.h"
#include "execute_statement.h"
#include "parser.h"
#include "view_transform.h"
#include "network_interface_cl.h"
#include "transform.h"
#include "dbtype.h"
#include "printer.hpp"
Functions
DB_OBJECT * db_create (DB_OBJECT *obj)
DB_OBJECT * db_create_internal (DB_OBJECT *obj)
DB_OBJECT * db_create_by_name (const char *name)
DB_OBJECT * db_create_by_name_internal (const char *name)
DB_OBJECT * db_copy (MOP sourcemop)
int db_drop (DB_OBJECT *obj)
int db_get (DB_OBJECT *object, const char *attpath, DB_VALUE *value)
int db_get_shared (DB_OBJECT *object, const char *attname, DB_VALUE *value)
int db_get_expression (DB_OBJECT *object, const char *expression, DB_VALUE *value)
int db_put (DB_OBJECT *obj, const char *name, DB_VALUE *value)
int db_put_internal (DB_OBJECT *obj, const char *name, DB_VALUE *value)
int db_send (MOP obj, const char *name, DB_VALUE *returnval,...)
int db_send_arglist (MOP obj, const char *name, DB_VALUE *returnval, DB_VALUE_LIST *args)
int db_send_argarray (MOP obj, const char *name, DB_VALUE *returnval, DB_VALUE **args)
DB_OTMPL * dbt_create_object (MOP classobj)
DB_OTMPL * dbt_create_object_internal (MOP classobj)
DB_OTMPL * dbt_edit_object (MOP object)
DB_OBJECT * dbt_finish_object (DB_OTMPL *def)
DB_OBJECT * dbt_finish_object_and_decache_when_failure (DB_OTMPL *def)
void dbt_abort_object (DB_OTMPL *def)
int dbt_put (DB_OTMPL *def, const char *name, DB_VALUE *value)
int dbt_put_internal (DB_OTMPL *def, const char *name, DB_VALUE *value)
int dbt_set_label (DB_OTMPL *def, DB_VALUE *label)
int db_get_attribute_descriptor (DB_OBJECT *obj, const char *attname, int class_attribute, int for_update, DB_ATTDESC **descriptor)
DB_DOMAIN * db_attdesc_domain (DB_ATTDESC *desc)
void db_free_attribute_descriptor (DB_ATTDESC *descriptor)
int db_get_method_descriptor (DB_OBJECT *obj, const char *methname, int class_method, DB_METHDESC **descriptor)
void db_free_method_descriptor (DB_ATTDESC *descriptor)
int db_dget (DB_OBJECT *obj, DB_ATTDESC *attribute, DB_VALUE *value)
int db_dput (DB_OBJECT *obj, DB_ATTDESC *attribute, DB_VALUE *value)
int db_dput_internal (DB_OBJECT *obj, DB_ATTDESC *attribute, DB_VALUE *value)
int dbt_dput (DB_OTMPL *def, DB_ATTDESC *attribute, DB_VALUE *value)
int dbt_dput_internal (DB_OTMPL *def, DB_ATTDESC *attribute, DB_VALUE *value)
int db_dsend (DB_OBJECT *obj, DB_METHDESC *method, DB_VALUE *returnval,...)
int db_dsend_arglist (DB_OBJECT *obj, DB_METHDESC *method, DB_VALUE *returnval, DB_VALUE_LIST *args)
int db_dsend_argarray (DB_OBJECT *obj, DB_METHDESC *method, DB_VALUE *returnval, DB_VALUE **args)
int db_dsend_quick (DB_OBJECT *obj, DB_METHDESC *method, DB_VALUE *returnval, int nargs, DB_VALUE **args)
DB_OBJECT * db_find_unique (MOP classmop, const char *attname, DB_VALUE *value)
DB_OBJECT * db_find_unique_write_mode (MOP classmop, const char *attname, DB_VALUE *value)
DB_OBJECT * db_find_primary_key (MOP classmop, const DB_VALUE **values, int size, DB_FETCH_MODE purpose)
DB_OBJECT * db_find_multi_unique (MOP classmop, int size, char *attr_names[], DB_VALUE *values[], DB_FETCH_MODE purpose)
DB_OBJECT * db_dfind_unique (MOP classmop, DB_ATTDESC *attdesc, DB_VALUE *value, DB_FETCH_MODE purpose)
DB_OBJECT * db_dfind_multi_unique (MOP classmop, int size, DB_ATTDESC *attdesc[], DB_VALUE *values[], DB_FETCH_MODE purpose)
void db_print (DB_OBJECT *obj)
void db_fprint (FILE *fp, DB_OBJECT *obj)
DB_OBJECT * db_create_trigger (const char *name, DB_TRIGGER_STATUS status, double priority, DB_TRIGGER_EVENT event, DB_OBJECT *class_, const char *attr, DB_TRIGGER_TIME cond_time, const char *cond_source, DB_TRIGGER_TIME action_time, DB_TRIGGER_ACTION action_type, const char *action_source)
int db_drop_trigger (DB_OBJECT *obj)
int db_rename_trigger (DB_OBJECT *obj, const char *newname)
DB_OBJECT * db_find_trigger (const char *name)
int db_find_all_triggers (DB_OBJLIST **list)
int db_find_event_triggers (DB_TRIGGER_EVENT event, DB_OBJECT *class_, const char *attr, DB_OBJLIST **list)
int db_alter_trigger_priority (DB_OBJECT *trobj, double priority)
int db_alter_trigger_status (DB_OBJECT *trobj, DB_TRIGGER_STATUS status)
int db_execute_deferred_activities (DB_OBJECT *trigger_obj, DB_OBJECT *target)
int db_drop_deferred_activities (DB_OBJECT *trigger_obj, DB_OBJECT *target)
int db_trigger_name (DB_OBJECT *trobj, char **name)
int db_trigger_status (DB_OBJECT *trobj, DB_TRIGGER_STATUS *status)
int db_trigger_priority (DB_OBJECT *trobj, double *priority)
int db_trigger_event (DB_OBJECT *trobj, DB_TRIGGER_EVENT *event)
int db_trigger_class (DB_OBJECT *trobj, DB_OBJECT **class_)
int db_trigger_attribute (DB_OBJECT *trobj, char **attr)
int db_trigger_condition (DB_OBJECT *trobj, char **condition)
int db_trigger_condition_time (DB_OBJECT *trobj, DB_TRIGGER_TIME *tr_time)
int db_trigger_action_type (DB_OBJECT *trobj, DB_TRIGGER_ACTION *type)
int db_trigger_action_time (DB_OBJECT *trobj, DB_TRIGGER_TIME *tr_time)
int db_trigger_action (DB_OBJECT *trobj, char **action)
int db_trigger_comment (DB_OBJECT *trobj, char **comment)
int db_encode_object (DB_OBJECT *object, char *string, int allocated_length, int *actual_length)
int db_decode_object (const char *string, DB_OBJECT **object)
int db_get_serial_current_value (const char *serial_name, DB_VALUE *serial_value)
int db_get_serial_next_value (const char *serial_name, DB_VALUE *serial_value)
int db_get_serial_next_value_ex (const char *serial_name, DB_VALUE *serial_value, int num_alloc)
Function Documentation
int db_alter_trigger_priority (DB_OBJECT * trobj, double priority)
Definition at line 1438 of file db_obj.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, and tr_set_priority().
int db_alter_trigger_status (DB_OBJECT * trobj, DB_TRIGGER_STATUS status)
Definition at line 1462 of file db_obj.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, and tr_set_status().
DB_DOMAIN* db_attdesc_domain (DB_ATTDESC * desc)
Definition at line 790 of file db_obj.c.
References ARG_FILE_LINE, CHECK_1ARG_NULL, CHECK_CONNECT_NULL, sm_descriptor::class_mop, db_attribute_domain(), db_get_attribute(), db_get_class_attribute(), ER_ERROR_SEVERITY, ER_GENERIC_ERROR, er_set(), ID_CLASS_ATTRIBUTE, sm_descriptor::name, sm_descriptor::name_space, NULL, and sm_filter_domain().
Referenced by db_gadget_bind().
DB_OBJECT* db_copy (MOP sourcemop)
Definition at line 171 of file db_obj.c.
References CHECK_CONNECT_NULL, and obj_copy().
DB_OBJECT* db_create (DB_OBJECT * obj)
Definition at line 69 of file db_obj.c.
References CHECK_1ARG_NULL, CHECK_CONNECT_NULL, CHECK_MODIFICATION_NULL, CHECK_PARTITION_PARENT, CHECK_PARTITION_SUBS, db_create_internal(), do_check_partitioned_class(), error(), NO_ERROR, and NULL.
DB_OBJECT* db_create_by_name (const char * name)
Definition at line 115 of file db_obj.c.
References ARG_FILE_LINE, CHECK_1ARG_NULL, CHECK_CONNECT_NULL, CHECK_MODIFICATION_NULL, db_create_by_name_internal(), do_is_partitioned_subclass(), ER_ERROR_SEVERITY, ER_NOT_ALLOWED_ACCESS_TO_PARTITION, er_set(), and NULL.
DB_OBJECT* db_create_by_name_internal (const char * name)
Definition at line 145 of file db_obj.c.
References CHECK_1ARG_NULL, CHECK_CONNECT_NULL, CHECK_MODIFICATION_NULL, and obj_create_by_name().
Referenced by db_create_by_name().
DB_OBJECT* db_create_internal (DB_OBJECT * obj)
Definition at line 93 of file db_obj.c.
References CHECK_1ARG_NULL, CHECK_CONNECT_NULL, CHECK_MODIFICATION_NULL, and obj_create().
Referenced by au_set_new_auth(), boot_add_charsets(), boot_add_collations(), boot_add_data_type(), boot_define_dual(), db_create(), find_instance(), and ldr_reset_context().
DB_OBJECT* db_create_trigger (const char * name, DB_TRIGGER_STATUS status, double priority, DB_TRIGGER_EVENT event, DB_OBJECT * class_, const char * attr, DB_TRIGGER_TIME cond_time, const char * cond_source, DB_TRIGGER_TIME action_time, DB_TRIGGER_ACTION action_type, const char * action_source)
Definition at line 1301 of file db_obj.c.
References CHECK_CONNECT_NULL, CHECK_MODIFICATION_NULL, NULL, and tr_create_trigger().
int db_decode_object (const char * string, DB_OBJECT ** object)
Definition at line 1805 of file db_obj.c.
References NO_ERROR, and vid_decode_object().
DB_OBJECT* db_dfind_multi_unique (MOP classmop, int size, DB_ATTDESC * attdesc[], DB_VALUE * values[], DB_FETCH_MODE purpose)
Definition at line 1224 of file db_obj.c.
References ARG_FILE_LINE, AU_FETCH_READ, AU_FETCH_UPDATE, CHECK_3ARGS_NULL, CHECK_CONNECT_NULL, DB_FETCH_WRITE, ER_OBJ_INVALID_ARGUMENTS, er_set(), ER_WARNING_SEVERITY, NULL, and obj_find_multi_desc().
DB_OBJECT* db_dfind_unique (MOP classmop, DB_ATTDESC * attdesc, DB_VALUE * value, DB_FETCH_MODE purpose)
Definition at line 1200 of file db_obj.c.
References AU_FETCH_READ, AU_FETCH_UPDATE, CHECK_3ARGS_NULL, CHECK_CONNECT_NULL, DB_FETCH_WRITE, and obj_desc_find_unique().
int db_dget (DB_OBJECT * obj, DB_ATTDESC * attribute, DB_VALUE * value)
Definition at line 889 of file db_obj.c.
References CHECK_CONNECT_ERROR, and obj_desc_get().
Referenced by mq_get_expression().
int db_dput (DB_OBJECT * obj, DB_ATTDESC * attribute, DB_VALUE * value)
Definition at line 908 of file db_obj.c.
References CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, CHECK_PARTITION_NONE, db_dput_internal(), db_get_class(), do_check_partitioned_class(), error(), sm_descriptor::name, and NO_ERROR.
int db_dput_internal (DB_OBJECT * obj, DB_ATTDESC * attribute, DB_VALUE * value)
Definition at line 933 of file db_obj.c.
References CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, and obj_desc_set().
Referenced by db_dput().
int db_drop (DB_OBJECT * obj)
Definition at line 190 of file db_obj.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, and obj_delete().
Referenced by delete_object_tuple(), do_drop_serial(), fn_oid(), ldr_restore_pin_and_drop_obj(), orp_oid_delete(), res_api_delete_row(), tr_drop_trigger_internal(), and uci_delete_cs().
int db_drop_deferred_activities (DB_OBJECT * trigger_obj, DB_OBJECT * target)
Definition at line 1527 of file db_obj.c.
References CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, and tr_drop_deferred_activities().
int db_drop_trigger (DB_OBJECT * obj)
Definition at line 1325 of file db_obj.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, and tr_drop_trigger().
int db_dsend (DB_OBJECT * obj, DB_METHDESC * method, DB_VALUE * returnval, ...)
Definition at line 999 of file db_obj.c.
References CHECK_CONNECT_ERROR, error(), NO_ERROR, and obj_desc_send_va().
int db_dsend_argarray (DB_OBJECT * obj, DB_METHDESC * method, DB_VALUE * returnval, DB_VALUE ** args)
Definition at line 1042 of file db_obj.c.
References CHECK_CONNECT_ERROR, and obj_desc_send_array().
int db_dsend_arglist (DB_OBJECT * obj, DB_METHDESC * method, DB_VALUE * returnval, DB_VALUE_LIST * args)
Definition at line 1022 of file db_obj.c.
References CHECK_CONNECT_ERROR, and obj_desc_send_list().
int db_dsend_quick (DB_OBJECT * obj, DB_METHDESC * method, DB_VALUE * returnval, int nargs, DB_VALUE ** args)
Definition at line 1067 of file db_obj.c.
References CHECK_CONNECT_ERROR, and obj_desc_send_array_quick().
int db_encode_object (DB_OBJECT * object, char * string, int allocated_length, int * actual_length)
Definition at line 1787 of file db_obj.c.
References NO_ERROR, and vid_encode_object().
int db_execute_deferred_activities (DB_OBJECT * trigger_obj, DB_OBJECT * target)
Definition at line 1496 of file db_obj.c.
References CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, and tr_execute_deferred_activities().
int db_find_all_triggers (DB_OBJLIST ** list)
Definition at line 1394 of file db_obj.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, and tr_find_all_triggers().
Referenced by sch_trigger().
int db_find_event_triggers (DB_TRIGGER_EVENT event, DB_OBJECT * class_, const char * attr, DB_OBJLIST ** list)
Definition at line 1421 of file db_obj.c.
References CHECK_CONNECT_ERROR, and tr_find_event_triggers().
DB_OBJECT* db_find_multi_unique (MOP classmop, int size, char * attr_names[], DB_VALUE * values[], DB_FETCH_MODE purpose)
Definition at line 1169 of file db_obj.c.
References ARG_FILE_LINE, AU_FETCH_READ, AU_FETCH_UPDATE, CHECK_3ARGS_NULL, CHECK_CONNECT_NULL, DB_FETCH_WRITE, ER_OBJ_INVALID_ARGUMENTS, er_set(), ER_WARNING_SEVERITY, NULL, and obj_find_multi_attr().
DB_OBJECT* db_find_primary_key (MOP classmop, const DB_VALUE ** values, int size, DB_FETCH_MODE purpose)
Definition at line 1138 of file db_obj.c.
References ARG_FILE_LINE, AU_FETCH_READ, AU_FETCH_UPDATE, CHECK_2ARGS_NULL, CHECK_CONNECT_NULL, DB_FETCH_WRITE, ER_OBJ_INVALID_ARGUMENTS, er_set(), ER_WARNING_SEVERITY, NULL, and obj_find_primary_key().
DB_OBJECT* db_find_trigger (const char * name)
Definition at line 1370 of file db_obj.c.
References CHECK_1ARG_NULL, CHECK_CONNECT_NULL, and tr_find_trigger().
DB_OBJECT* db_find_unique (MOP classmop, const char * attname, DB_VALUE * value)
Definition at line 1092 of file db_obj.c.
References AU_FETCH_READ, CHECK_3ARGS_NULL, CHECK_CONNECT_NULL, and obj_find_unique().
Referenced by do_get_serial_obj_id(), and jsp_find_stored_procedure().
DB_OBJECT* db_find_unique_write_mode (MOP classmop, const char * attname, DB_VALUE * value)
Definition at line 1115 of file db_obj.c.
References AU_FETCH_UPDATE, CHECK_3ARGS_NULL, CHECK_CONNECT_NULL, and obj_find_unique().
void db_fprint (FILE * fp, DB_OBJECT * obj)
Definition at line 1268 of file db_obj.c.
References CHECK_CONNECT_VOID, help_print_obj(), and NULL.
void db_free_attribute_descriptor (DB_ATTDESC * descriptor)
Definition at line 835 of file db_obj.c.
References sm_free_descriptor().
Referenced by db_gadget_destroy(), do_insert_template(), init_update_data(), insert_subquery_results(), ldr_clear_and_free_context(), ldr_refresh_attrs(), update_class_attributes(), update_object_by_oid(), and update_objs_for_list_file().
void db_free_method_descriptor (DB_ATTDESC * descriptor)
Definition at line 875 of file db_obj.c.
References sm_free_descriptor().
int db_get (DB_OBJECT * object, const char * attpath, DB_VALUE * value)
Definition at line 233 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and obj_get_path().
Referenced by au_add_member_internal(), au_check_serial_authorization(), au_drop_member(), cur_tuple(), delete_object_tuple(), object_printer::describe_attribute(), do_alter_serial(), do_change_auto_increment_serial(), do_drop_serial(), do_get_serial_cached_num(), do_reset_auto_increment_serial(), do_update_maxvalue_of_auto_increment_serial(), drop_stored_procedure(), emit_autoincrement_def(), emit_class_owner(), emit_instance_attributes(), emit_stored_procedure(), emit_stored_procedure_args(), fn_collection(), get_user_name(), help_class_names(), object_description::init(), jsp_alter_stored_procedure(), jsp_do_call_stored_procedure(), jsp_get_return_type(), object_to_trigger(), oid_attr_info_set(), oid_data_set(), pt_eval_path_expr(), sm_delete_class_mop(), sm_rename_class(), ux_get_generated_keys_client_insert(), ux_get_generated_keys_server_insert(), vid_encode_object(), and vt_api_get_db_value().
int db_get_attribute_descriptor (DB_OBJECT * obj, const char * attname, int class_attribute, int for_update, DB_ATTDESC ** descriptor)
Definition at line 763 of file db_obj.c.
References CHECK_3ARGS_ERROR, CHECK_CONNECT_ERROR, and sm_get_attribute_descriptor().
Referenced by db_gadget_create(), do_insert_template(), insert_subquery_results(), ldr_act_add_attr(), ldr_refresh_attrs(), mq_get_expression(), and update_object_tuple().
int db_get_expression (DB_OBJECT * object, const char * expression, DB_VALUE * value)
Definition at line 296 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and mq_get_expression().
int db_get_method_descriptor (DB_OBJECT * obj, const char * methname, int class_method, DB_METHDESC ** descriptor)
Definition at line 857 of file db_obj.c.
References CHECK_3ARGS_ERROR, CHECK_CONNECT_ERROR, and sm_get_method_descriptor().
int db_get_serial_current_value (const char * serial_name, DB_VALUE * serial_value)
Definition at line 1820 of file db_obj.c.
References ARG_FILE_LINE, assert, CT_SERIAL_NAME, do_get_serial_cached_num(), do_get_serial_obj_id(), er_errid(), ER_ERROR_SEVERITY, ER_QPROC_INVALID_PARAMETER, ER_QPROC_SERIAL_NOT_FOUND, er_set(), NO_ERROR, NULL, serial_get_current_value(), and sm_find_class().
int db_get_serial_next_value (const char * serial_name, DB_VALUE * serial_value)
Definition at line 1866 of file db_obj.c.
References db_get_serial_next_value_ex().
int db_get_serial_next_value_ex (const char * serial_name, DB_VALUE * serial_value, int num_alloc)
Definition at line 1878 of file db_obj.c.
References ARG_FILE_LINE, assert, CT_CLASS_NAME, do_get_serial_cached_num(), do_get_serial_obj_id(), er_errid(), ER_ERROR_SEVERITY, ER_QPROC_INVALID_PARAMETER, ER_QPROC_SERIAL_NOT_FOUND, er_set(), GENERATE_SERIAL, NO_ERROR, NULL, serial_get_next_value(), and sm_find_class().
Referenced by db_get_serial_next_value().
int db_get_shared (DB_OBJECT * object, const char * attname, DB_VALUE * value)
Definition at line 255 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and obj_get_shared().
void db_print (DB_OBJECT * obj)
Definition at line 1251 of file db_obj.c.
References CHECK_CONNECT_VOID, help_print_obj(), NULL, and file_print_output::std_output().
int db_put (DB_OBJECT * obj, const char * name, DB_VALUE * value)
Definition at line 318 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, CHECK_PARTITION_NONE, db_get_class(), db_put_internal(), do_check_partitioned_class(), error(), and NO_ERROR.
Referenced by fn_collection(), ux_cursor_update(), and vt_api_set_db_value().
int db_put_internal (DB_OBJECT * obj, const char * name, DB_VALUE * value)
Definition at line 347 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, and obj_set().
Referenced by boot_add_charsets(), boot_add_collations(), boot_add_data_type(), boot_define_dual(), db_put(), lang_db_put_charset(), put_timezone_checksum(), tr_delete_schema_cache(), tr_rename_trigger(), tr_set_comment(), tr_set_priority(), and tr_set_status().
int db_rename_trigger (DB_OBJECT * obj, const char * newname)
Definition at line 1346 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, and tr_rename_trigger().
int db_send (MOP obj, const char * name, DB_VALUE * returnval, ...)
Definition at line 381 of file db_obj.c.
References CHECK_CONNECT_ERROR, error(), NO_ERROR, NULL, and obj_send_va().
Referenced by apif_last_pos(), and apif_tell().
int db_send_argarray (MOP obj, const char * name, DB_VALUE * returnval, DB_VALUE ** args)
Definition at line 444 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and obj_send_array().
Referenced by construct_instance().
int db_send_arglist (MOP obj, const char * name, DB_VALUE * returnval, DB_VALUE_LIST * args)
Definition at line 417 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and obj_send_list().
Referenced by call_method().
int db_trigger_action (DB_OBJECT * trobj, char ** action)
Definition at line 1742 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and tr_trigger_action().
Referenced by fetch_trigger(), and trigger_description::init().
int db_trigger_action_time (DB_OBJECT * trobj, DB_TRIGGER_TIME * tr_time)
Definition at line 1724 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and tr_trigger_action_time().
Referenced by fetch_trigger().
int db_trigger_action_type (DB_OBJECT * trobj, DB_TRIGGER_ACTION * type)
Definition at line 1705 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and tr_trigger_action_type().
int db_trigger_attribute (DB_OBJECT * trobj, char ** attr)
Definition at line 1643 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and tr_trigger_attribute().
Referenced by fetch_trigger().
int db_trigger_class (DB_OBJECT * trobj, DB_OBJECT ** class_)
Definition at line 1623 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and tr_trigger_class().
Referenced by fetch_trigger().
int db_trigger_comment (DB_OBJECT * trobj, char ** comment)
Definition at line 1763 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and tr_trigger_comment().
Referenced by fetch_trigger().
int db_trigger_condition (DB_OBJECT * trobj, char ** condition)
Definition at line 1663 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and tr_trigger_condition().
Referenced by fetch_trigger(), and trigger_description::init().
int db_trigger_condition_time (DB_OBJECT * trobj, DB_TRIGGER_TIME * tr_time)
Definition at line 1683 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and tr_trigger_condition_time().
Referenced by fetch_trigger().
int db_trigger_event (DB_OBJECT * trobj, DB_TRIGGER_EVENT * event)
Definition at line 1603 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and tr_trigger_event().
Referenced by fetch_trigger().
int db_trigger_name (DB_OBJECT * trobj, char ** name)
Definition at line 1548 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and tr_trigger_name().
Referenced by fetch_trigger().
int db_trigger_priority (DB_OBJECT * trobj, double * priority)
Definition at line 1585 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and tr_trigger_priority().
Referenced by fetch_trigger().
int db_trigger_status (DB_OBJECT * trobj, DB_TRIGGER_STATUS * status)
Definition at line 1567 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and tr_trigger_status().
Referenced by fetch_trigger().
void dbt_abort_object (DB_OTMPL * def)
Definition at line 616 of file db_obj.c.
References NULL, and obt_quit().
Referenced by au_change_serial_owner(), db_gadget_exec(), do_alter_serial(), do_change_auto_increment_serial(), do_create_serial_internal(), do_insert_template(), do_reset_auto_increment_serial(), do_update_auto_increment_serial_on_rename(), do_update_maxvalue_of_auto_increment_serial(), insert_subquery_results(), jsp_add_stored_procedure(), jsp_add_stored_procedure_argument(), la_apply_insert_log(), la_apply_update_log(), trigger_to_object(), update_class_attributes(), update_object_tuple(), and ux_oid_put().
DB_OTMPL* dbt_create_object (MOP classobj)
Definition at line 468 of file db_obj.c.
References CHECK_1ARG_NULL, CHECK_CONNECT_NULL, CHECK_MODIFICATION_NULL, CHECK_PARTITION_PARENT, CHECK_PARTITION_SUBS, dbt_create_object_internal(), do_check_partitioned_class(), and NULL.
DB_OTMPL* dbt_create_object_internal (MOP classobj)
Definition at line 501 of file db_obj.c.
References CHECK_1ARG_NULL, CHECK_CONNECT_NULL, CHECK_MODIFICATION_NULL, NULL, and obt_def_object().
Referenced by dbt_create_object().
int dbt_dput (DB_OTMPL * def, DB_ATTDESC * attribute, DB_VALUE * value)
Definition at line 953 of file db_obj.c.
References CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, CHECK_PARTITION_NONE, obj_template::classobj, dbt_dput_internal(), do_check_partitioned_class(), error(), sm_descriptor::name, and NO_ERROR.
int dbt_dput_internal (DB_OTMPL * def, DB_ATTDESC * attribute, DB_VALUE * value)
Definition at line 977 of file db_obj.c.
References CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, and obt_desc_set().
Referenced by db_gadget_exec(), dbt_dput(), insert_object_attr(), and update_object_attribute().
DB_OTMPL* dbt_edit_object (MOP object)
Definition at line 533 of file db_obj.c.
References CHECK_1ARG_NULL, CHECK_CONNECT_NULL, CHECK_MODIFICATION_NULL, NULL, and obt_edit_object().
Referenced by au_change_serial_owner(), do_alter_serial(), do_change_auto_increment_serial(), do_reset_auto_increment_serial(), do_update_auto_increment_serial_on_rename(), do_update_maxvalue_of_auto_increment_serial(), update_class_attributes(), update_object_tuple(), and ux_oid_put().
DB_OBJECT* dbt_finish_object (DB_OTMPL * def)
Definition at line 560 of file db_obj.c.
References CHECK_1ARG_NULL, CHECK_CONNECT_NULL, CHECK_MODIFICATION_NULL, NO_ERROR, NULL, and obt_update().
Referenced by au_change_serial_owner(), db_gadget_exec(), do_alter_serial(), do_change_auto_increment_serial(), do_create_serial_internal(), do_insert_template(), do_reset_auto_increment_serial(), do_update_auto_increment_serial_on_rename(), do_update_maxvalue_of_auto_increment_serial(), insert_subquery_results(), jsp_add_stored_procedure(), jsp_add_stored_procedure_argument(), trigger_to_object(), update_class_attributes(), update_object_tuple(), and ux_oid_put().
DB_OBJECT* dbt_finish_object_and_decache_when_failure (DB_OTMPL * def)
Definition at line 583 of file db_obj.c.
References CHECK_1ARG_NULL, CHECK_CONNECT_NULL, CHECK_MODIFICATION_NULL, NO_ERROR, NULL, obj_template::object, obt_update(), and ws_decache().
int dbt_put (DB_OTMPL * def, const char * name, DB_VALUE * value)
Definition at line 635 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, CHECK_PARTITION_NONE, obj_template::classobj, dbt_put_internal(), do_check_partitioned_class(), error(), and NO_ERROR.
Referenced by ux_oid_put().
int dbt_put_internal (DB_OTMPL * def, const char * name, DB_VALUE * value)
Definition at line 670 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, db_get_pointer(), DB_TYPE_POINTER, DB_VALUE_TYPE, error(), NO_ERROR, NULL, obt_set(), and obt_set_obt().
Referenced by au_change_serial_owner(), dbt_put(), do_alter_serial(), do_change_auto_increment_serial(), do_create_serial_internal(), do_reset_auto_increment_serial(), do_update_auto_increment_serial_on_rename(), do_update_maxvalue_of_auto_increment_serial(), jsp_add_stored_procedure(), jsp_add_stored_procedure_argument(), la_get_current(), trigger_to_object(), and update_class_attributes().
int dbt_set_label (DB_OTMPL * def, DB_VALUE * label)
Definition at line 713 of file db_obj.c.
References ARG_FILE_LINE, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, obj_template::classobj, DB_TYPE_OBJECT, DB_VALUE_DOMAIN_TYPE, ER_ERROR_SEVERITY, ER_REFERENCE_TO_NON_REFERABLE_NOT_ALLOWED, er_set(), NO_ERROR, NULL, obt_set_label(), and sm_is_reuse_oid_class().
Referenced by do_insert_template().