CUBRID Engine: src/compat/db_json_path.hpp File Reference
db_json_path.hpp File Reference
#include "db_json_allocator.hpp"
#include "db_json_types_internal.hpp"
#include "db_rapidjson.hpp"
#include <string>
#include <unordered_set>
#include <vector>
Classes
struct PATH_TOKEN
class JSON_PATH
Functions
int db_json_path_unquote_object_keys (std::string &sql_path)
Function Documentation
int db_json_path_unquote_object_keys (std::string & sql_path)
Definition at line 554 of file db_json_path.cpp.
References assert, ASSERT_ERROR, db_json_path_is_token_valid_unquoted_object_key(), db_json_split_path_by_delimiters(), i, and NO_ERROR.
Referenced by db_json_path_unquote_object_keys_external().