CUBRID Engine: src/compat/db_json_types_internal.hpp File Reference
db_json_types_internal.hpp File Reference
#include "db_json_allocator.hpp"
#include "db_rapidjson.hpp"
Classes
class JSON_DOC
Typedefs
typedef rapidjson::UTF8 JSON_ENCODING
typedef rapidjson::GenericValue< JSON_ENCODING, JSON_PRIVATE_MEMPOOL > JSON_VALUE
Functions
JSON_VALUE & db_json_doc_to_value (JSON_DOC &doc)
const JSON_VALUE & db_json_doc_to_value (const JSON_DOC &doc)
Typedef Documentation
typedef rapidjson::UTF8 JSON_ENCODING
Definition at line 30 of file db_json_types_internal.hpp.
typedef rapidjson::GenericValue<JSON_ENCODING, JSON_PRIVATE_MEMPOOL> JSON_VALUE
Definition at line 31 of file db_json_types_internal.hpp.
Function Documentation
JSON_VALUE& db_json_doc_to_value (JSON_DOC & doc)
Definition at line 37 of file db_json_types_internal.cpp.
Referenced by db_json_deserialize(), db_json_get_type_as_str(), db_json_merge_patch_func(), db_json_merge_preserve_func(), JSON_PATH::extract(), JSON_PATH::get(), JSON_PATH::set(), and JSON_WALKER::WalkDocument().
const JSON_VALUE& db_json_doc_to_value (const JSON_DOC & doc)
Definition at line 43 of file db_json_types_internal.cpp.