CUBRID Engine: src/compat/db_elo.h File Reference
db_elo.h File Reference
#include <sys/types.h>
#include "dbtype_def.h"
Functions
int db_create_fbo (DB_VALUE *value, DB_TYPE type)
int db_elo_copy_structure (const DB_ELO *src, DB_ELO *dest)
void db_elo_free_structure (DB_ELO *elo)
int db_elo_copy (DB_ELO *src, DB_ELO *dest)
int db_elo_delete (DB_ELO *elo)
DB_BIGINT db_elo_size (DB_ELO *elo)
int db_elo_read (const DB_ELO *elo, off_t pos, void *buf, size_t count, DB_BIGINT *read_bytes)
int db_elo_write (DB_ELO *elo, off_t pos, const void *buf, size_t count, DB_BIGINT *written_bytes)
Function Documentation
int db_create_fbo (DB_VALUE * value, DB_TYPE type)
Definition at line 47 of file db_elo.c.
References CHECK_1ARG_ERROR, db_make_elo(), elo_create(), db_value::need_clear, and NO_ERROR.
Referenced by db_bit_to_blob(), db_char_to_blob(), db_char_to_clob(), lob_from_file(), and ux_lob_new().
int db_elo_copy (DB_ELO * src, DB_ELO * dest)
Definition at line 102 of file db_elo.c.
References CHECK_2ARGS_ERROR, and elo_copy().
Referenced by heap_attrinfo_transform_to_disk_internal(), and obt_apply_assignments().
int db_elo_copy_structure (const DB_ELO * src, DB_ELO * dest)
Definition at line 74 of file db_elo.c.
References CHECK_2ARGS_ERROR, and elo_copy_structure().
Referenced by pt_dbval_to_value().
int db_elo_delete (DB_ELO * elo)
Definition at line 115 of file db_elo.c.
References CHECK_1ARG_ERROR, and elo_delete().
Referenced by delete_object_tuple(), heap_attrinfo_delete_lob(), heap_attrinfo_set_uninitialized(), obt_apply_assignments(), qexec_execute_delete(), and qexec_execute_update().
void db_elo_free_structure (DB_ELO * elo)
Definition at line 87 of file db_elo.c.
References elo_free_structure(), and NULL.
int db_elo_read (const DB_ELO * elo, off_t pos, void * buf, size_t count, DB_BIGINT * read_bytes)
Definition at line 145 of file db_elo.c.
References ARG_FILE_LINE, elo_read(), ER_OBJ_INVALID_ARGUMENTS, er_set(), ER_WARNING_SEVERITY, NO_ERROR, and NULL.
Referenced by lob_from_file(), lob_to_bit_char(), and ux_lob_read().
DB_BIGINT db_elo_size (DB_ELO * elo)
Definition at line 128 of file db_elo.c.
References CHECK_1ARG_ERROR, and elo_size().
Referenced by lob_from_file(), lob_length(), and lob_to_bit_char().
int db_elo_write (DB_ELO * elo, off_t pos, const void * buf, size_t count, DB_BIGINT * written_bytes)
Definition at line 177 of file db_elo.c.
References ARG_FILE_LINE, elo_write(), ER_OBJ_INVALID_ARGUMENTS, er_set(), ER_WARNING_SEVERITY, NO_ERROR, and NULL.
Referenced by db_bit_to_blob(), db_char_to_blob(), db_char_to_clob(), lob_from_file(), and ux_lob_write().