CUBRID Engine: src/compat/db_value_printer.cpp File Reference
db_value_printer.cpp File Reference
#include "db_value_printer.hpp"
#include "db_date.h"
#include "dbtype.h"
#include "memory_private_allocator.hpp"
#include "object_primitive.h"
#include "object_representation.h"
#include "printer.hpp"
#include "set_object.h"
#include "string_buffer.hpp"
#include "string_opfunc.h"
#include "tz_support.h"
#include "virtual_object.h"
Macros
#define TOO_BIG_TO_MATTER 1024
Functions
void db_fprint_value (FILE *fp, const db_value *value)
void db_print_value (print_output &output_ctx, const db_value *value)
void db_sprint_value (const db_value *value, string_buffer &sb)
Macro Definition Documentation
#define TOO_BIG_TO_MATTER 1024
Referenced by db_value_printer::describe_data().
Function Documentation
void db_fprint_value (FILE * fp, const db_value * value)
Definition at line 586 of file db_value_printer.cpp.
References BUFFER_SIZE, db_value_printer::describe_value(), string_buffer::get_buffer(), string_buffer::len(), and cubmem::PRIVATE_BLOCK_ALLOCATOR.
Referenced by btree_dump_key(), db_value_fprint(), db_value_print(), db_value_printer::db_value_printer(), heap_attrinfo_dump(), heap_classrepr_dump(), qfile_locate_tuple_next_value(), qfile_print_list_cache_entry(), and setobj_print().
void db_print_value (print_output & output_ctx, const db_value * value)
Definition at line 604 of file db_value_printer.cpp.
References BUFFER_SIZE, db_value_printer::describe_value(), string_buffer::get_buffer(), print_output::grab_string_buffer(), string_buffer::len(), NULL, and cubmem::PRIVATE_BLOCK_ALLOCATOR.
Referenced by db_value_printer::db_value_printer(), and desc_value_print().
void db_sprint_value (const db_value * value, string_buffer & sb)
Definition at line 633 of file db_value_printer.cpp.
References db_value_printer::describe_value().
Referenced by db_value_printer::db_value_printer(), la_apply_delete_log(), la_apply_insert_log(), la_apply_repl_log(), la_apply_update_log(), la_flush_repl_items(), and pr_valstring().