CUBRID Engine: src/api/db_collection.c File Reference
db_collection.c File Reference
#include <assert.h>
#include "db_stub.h"
#include "api_util.h"
#include "dbi.h"
Classes
struct collection_s_
Typedefs
typedef struct collection_s_ COLLECTION_
Functions
static int col_api_length (API_COLLECTION *col, int *len)
static int col_api_insert (API_COLLECTION *col, long pos, CI_TYPE type, void *ptr, size_t size)
static int col_api_update (API_COLLECTION *col, long pos, CI_TYPE type, void *ptr, size_t size)
static int col_api_delete (API_COLLECTION *col, long pos)
static int col_api_get_elem_domain_info (API_COLLECTION *col, long pos, CI_TYPE *type, int *precision, int *scale)
static int col_api_get_elem (API_COLLECTION *col, long pos, CI_TYPE type, void *addr, size_t len, size_t *outlen, bool *isnull)
static void col_dtorf (VALUE_AREA *va, API_VALUE *val)
static void col_api_destroy (API_COLLECTION *col)
static int apif_collection_create (BIND_HANDLE conn, COLLECTION_ **rc)
static int fill_collection (COLLECTION_ *co, DB_SET *set)
int api_collection_create_from_db_value (BIND_HANDLE conn, const DB_VALUE *val, API_COLLECTION **rc)
static int set_to_db_value_mapf (void *arg, int idx, VALUE_AREA *va, API_VALUE *aval)
int api_collection_set_to_db_value (API_COLLECTION *col, DB_VALUE *val)
int api_collection_create (BIND_HANDLE conn, API_COLLECTION **rc)
Variables
static API_COLLECTION_IFS COL_IFS_
Typedef Documentation
typedef struct collection_s_ COLLECTION_
Definition at line 28 of file db_collection.c.
Function Documentation
int api_collection_create (BIND_HANDLE conn, API_COLLECTION ** rc)
Definition at line 467 of file db_collection.c.
References apif_collection_create(), ER_INTERFACE_INVALID_ARGUMENT, NO_ERROR, and NULL.
Referenced by ci_collection_new_impl().
int api_collection_create_from_db_value (BIND_HANDLE conn, const DB_VALUE * val, API_COLLECTION ** rc)
Definition at line 353 of file db_collection.c.
References apif_collection_create(), collection_s_::col, db_get_set(), DB_VALUE_DOMAIN_TYPE, api_collection_ifs_s::destroy, collection_s_::dt, ER_INTERFACE_INVALID_ARGUMENT, fill_collection(), api_collection_s::ifs, NO_ERROR, NULL, and TP_IS_SET_TYPE.
Referenced by db_value_to_value().
int api_collection_set_to_db_value (API_COLLECTION * col, DB_VALUE * val)
Definition at line 417 of file db_collection.c.
References db_col_create(), db_col_free(), DB_TYPE_C_SET, DB_VALUE_DOMAIN_TYPE, db_value_put(), collection_s_::dt, ER_INTERFACE_GENERIC, ER_INTERFACE_INVALID_ARGUMENT, value_indexer_s::ifs, collection_s_::indexer, value_indexer_ifs_s::length, value_indexer_ifs_s::map, NO_ERROR, NULL, set_to_db_value_mapf(), and TP_IS_SET_TYPE.
Referenced by value_to_db_value().
static int apif_collection_create (BIND_HANDLE conn, COLLECTION_ ** rc) static
Definition at line 280 of file db_collection.c.
References API_FREE, API_MALLOC, assert, collection_s_::col, COL_IFS_, api_collection_s::conn, ER_INTERFACE_NO_MORE_MEMORY, api_collection_s::ifs, collection_s_::indexer, list_indexer_create(), NO_ERROR, and NULL.
Referenced by api_collection_create(), and api_collection_create_from_db_value().
static int col_api_delete (API_COLLECTION * col, long pos) static
Definition at line 144 of file db_collection.c.
References assert, value_indexer_ifs_s::check, CHECK_FOR_DELETE, db_value_free(), value_indexer_ifs_s::delete, value_indexer_s::ifs, collection_s_::indexer, NO_ERROR, and NULL.
static void col_api_destroy (API_COLLECTION * col) static
Definition at line 255 of file db_collection.c.
References API_FREE, assert, col_dtorf(), value_indexer_ifs_s::destroy, value_indexer_s::ifs, collection_s_::indexer, and NULL.
static int col_api_get_elem (API_COLLECTION * col, long pos, CI_TYPE type, void * addr, size_t len, size_t * outlen, bool * isnull) static
Definition at line 215 of file db_collection.c.
References assert, value_indexer_ifs_s::check, CHECK_FOR_GET, coerce_db_value_to_value(), collection_s_::col, api_collection_s::conn, value_indexer_ifs_s::get, value_indexer_s::ifs, collection_s_::indexer, NO_ERROR, and NULL.
static int col_api_get_elem_domain_info (API_COLLECTION * col, long pos, CI_TYPE * type, int * precision, int * scale) static
Definition at line 172 of file db_collection.c.
References assert, value_indexer_ifs_s::check, CHECK_FOR_GET, db_type_to_type(), DB_VALUE_DOMAIN_TYPE, db_value_precision(), db_value_scale(), value_indexer_ifs_s::get, value_indexer_s::ifs, collection_s_::indexer, NO_ERROR, and NULL.
static int col_api_insert (API_COLLECTION * col, long pos, CI_TYPE type, void * ptr, size_t size) static
Definition at line 77 of file db_collection.c.
References assert, value_indexer_ifs_s::check, CHECK_FOR_INSERT, coerce_value_to_db_value(), db_value_create(), db_value_free(), ER_INTERFACE_NO_MORE_MEMORY, value_indexer_s::ifs, collection_s_::indexer, value_indexer_ifs_s::insert, NO_ERROR, and NULL.
static int col_api_length (API_COLLECTION * col, int * len) static
Definition at line 57 of file db_collection.c.
References assert, value_indexer_s::ifs, collection_s_::indexer, value_indexer_ifs_s::length, and NULL.
static int col_api_update (API_COLLECTION * col, long pos, CI_TYPE type, void * ptr, size_t size) static
Definition at line 117 of file db_collection.c.
References assert, value_indexer_ifs_s::check, CHECK_FOR_GET, CHECK_FOR_SET, coerce_value_to_db_value(), value_indexer_ifs_s::get, value_indexer_s::ifs, collection_s_::indexer, NO_ERROR, and NULL.
static void col_dtorf (VALUE_AREA * va, API_VALUE * val) static
Definition at line 241 of file db_collection.c.
References assert, db_value_free(), and NULL.
Referenced by col_api_destroy().
static int fill_collection (COLLECTION_ * co, DB_SET * set) static
Definition at line 306 of file db_collection.c.
References assert, value_indexer_ifs_s::check, CHECK_FOR_INSERT, db_col_get(), db_col_size(), db_value_create(), db_value_free(), ER_INTERFACE_GENERIC, ER_INTERFACE_INVALID_ARGUMENT, ER_INTERFACE_NO_MORE_MEMORY, i, value_indexer_s::ifs, collection_s_::indexer, value_indexer_ifs_s::insert, NO_ERROR, NULL, and set_size().
Referenced by api_collection_create_from_db_value().
static int set_to_db_value_mapf (void * arg, int idx, VALUE_AREA * va, API_VALUE * aval) static
Definition at line 393 of file db_collection.c.
References assert, collection_s_::col, db_col_put(), ER_INTERFACE_GENERIC, NO_ERROR, and NULL.
Referenced by api_collection_set_to_db_value().
Variable Documentation
API_COLLECTION_IFS COL_IFS_ static
Initial value:
= {
  col_api_length,
  col_api_insert,
  col_api_update,
  col_api_delete,
  col_api_get_elem_domain_info,
  col_api_get_elem,
  col_api_destroy
}
Definition at line 263 of file db_collection.c.
Referenced by apif_collection_create().