CUBRID Engine: src/compat/db_set.c File Reference
db_set.c File Reference
#include "db_set.h"
#include "db_set_function.h"
#include "authenticate.h"
#include "class_object.h"
#include "db.h"
#include "dbtype.h"
#include "error_manager.h"
#include "object_primitive.h"
#include "set_object.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <ctype.h>
#include <string.h>
Macros
#define ERROR_SET(error, code)
#define ERROR_SET1(error, code, arg1)
Functions
DB_SET * db_set_create (MOP classop, const char *name)
DB_SET * db_set_create_basic (MOP classop, const char *name)
DB_SET * db_set_create_multi (MOP classop, const char *name)
DB_SET * db_seq_create (MOP classop, const char *name, int size)
int db_set_free (DB_SET *set)
int db_seq_free (DB_SEQ *seq)
int db_set_filter (DB_SET *set)
int db_seq_filter (DB_SET *set)
DB_SET * db_set_copy (DB_SET *source)
DB_SEQ * db_seq_copy (DB_SEQ *source)
int db_set_add (DB_SET *set, DB_VALUE *value)
int db_set_get (DB_SET *set, int index, DB_VALUE *value)
int db_set_drop (DB_SET *set, DB_VALUE *value)
int db_set_size (DB_SET *set)
int db_set_cardinality (DB_SET *set)
int db_set_ismember (DB_SET *set, DB_VALUE *value)
int db_set_isempty (DB_SET *set)
int db_set_has_null (DB_COLLECTION *set)
int db_set_print (DB_SET *set)
DB_TYPE db_set_type (DB_SET *set)
int db_seq_get (DB_SET *set, int index, DB_VALUE *value)
int db_seq_put (DB_SET *set, int index, DB_VALUE *value)
int db_seq_insert (DB_SET *set, int index, DB_VALUE *value)
int db_seq_drop (DB_SET *set, int index)
int db_seq_size (DB_SET *set)
int db_seq_cardinality (DB_SET *set)
int db_seq_print (DB_SET *set)
int db_seq_find (DB_SET *set, DB_VALUE *value, int index)
DB_COLLECTION * db_col_create (DB_TYPE type, int size, DB_DOMAIN *domain)
DB_COLLECTION * db_col_copy (DB_COLLECTION *col)
int db_col_free (DB_COLLECTION *col)
int db_col_filter (DB_COLLECTION *col)
int db_col_add (DB_COLLECTION *col, DB_VALUE *value)
int db_col_drop (DB_COLLECTION *col, DB_VALUE *value, int all)
int db_col_drop_element (DB_COLLECTION *col, int element_index)
int db_col_drop_nulls (DB_COLLECTION *col)
int db_col_size (DB_COLLECTION *col)
int db_col_cardinality (DB_COLLECTION *col)
int db_col_get (DB_COLLECTION *col, int element_index, DB_VALUE *value)
int db_col_put (DB_COLLECTION *col, int element_index, DB_VALUE *value)
int db_col_insert (DB_COLLECTION *col, int element_index, DB_VALUE *value)
int db_col_ismember (DB_COLLECTION *col, DB_VALUE *value)
int db_col_find (DB_COLLECTION *col, DB_VALUE *value, int starting_index, int *found_index)
DB_TYPE db_col_type (DB_COLLECTION *col)
DB_DOMAIN * db_col_domain (DB_COLLECTION *col)
int db_col_fprint (FILE *fp, DB_COLLECTION *col)
int db_col_print (DB_COLLECTION *col)
int db_col_optimize (DB_COLLECTION *col)
Macro Definition Documentation
#define ERROR_SET (error, code)
Value:
do {                     \
    error =  code;         \
    er_set (ER_WARNING_SEVERITY, ARG_FILE_LINE, code, 0); \
  } while (0)
Definition at line 44 of file db_set.c.
Referenced by db_seq_insert(), db_seq_put(), and db_set_add().
#define ERROR_SET1 (error, code, arg1)
Value:
do {                            \
    error = code;                 \
    er_set (ER_WARNING_SEVERITY, ARG_FILE_LINE, code, 1, arg1); \
  } while (0)
Definition at line 50 of file db_set.c.
Referenced by db_seq_create(), db_set_create(), db_set_create_basic(), and db_set_create_multi().
Function Documentation
int db_col_add (DB_COLLECTION * col, DB_VALUE * value)
Definition at line 1057 of file db_set.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, error(), NO_ERROR, NULL, db_set::owner, and set_add_element().
int db_col_cardinality (DB_COLLECTION * col)
Definition at line 1192 of file db_set.c.
References CHECK_1ARG_MINUSONE, CHECK_CONNECT_MINUSONE, and set_cardinality().
DB_COLLECTION* db_col_copy (DB_COLLECTION * col)
Definition at line 975 of file db_set.c.
References CHECK_CONNECT_NULL, NULL, and set_copy().
DB_COLLECTION* db_col_create (DB_TYPE type, int size, DB_DOMAIN * domain)
Definition at line 949 of file db_set.c.
References CHECK_CONNECT_NULL, NULL, set_create(), and set_create_with_domain().
Referenced by api_collection_set_to_db_value(), and ldr_collection_db_collection().
DB_DOMAIN* db_col_domain (DB_COLLECTION * col)
Definition at line 1421 of file db_set.c.
References CHECK_1ARG_NULL, CHECK_CONNECT_NULL, NULL, and set_get_domain().
Referenced by dbval_to_net_buf().
int db_col_drop (DB_COLLECTION * col, DB_VALUE * value, int all)
Definition at line 1084 of file db_set.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, error(), NULL, db_set::owner, and set_drop_element().
int db_col_drop_element (DB_COLLECTION * col, int element_index)
Definition at line 1112 of file db_set.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, error(), NULL, db_set::owner, and set_drop_seq_element().
int db_col_drop_nulls (DB_COLLECTION * col)
Definition at line 1139 of file db_set.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, db_make_null(), error(), NULL, db_set::owner, and set_drop_element().
int db_col_filter (DB_COLLECTION * col)
Definition at line 1024 of file db_set.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, error(), NULL, db_set::owner, and set_filter().
int db_col_find (DB_COLLECTION * col, DB_VALUE * value, int starting_index, int * found_index)
Definition at line 1367 of file db_set.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, error(), NO_ERROR, NULL, and set_find_seq_element().
int db_col_fprint (FILE * fp, DB_COLLECTION * col)
Definition at line 1444 of file db_set.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, NO_ERROR, NULL, and set_fprint().
Referenced by db_col_print().
int db_col_free (DB_COLLECTION * col)
Definition at line 998 of file db_set.c.
References NO_ERROR, NULL, and set_free().
Referenced by api_collection_set_to_db_value(), and fn_collection().
int db_col_get (DB_COLLECTION * col, int element_index, DB_VALUE * value)
Definition at line 1222 of file db_set.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, error(), and set_get_element().
Referenced by execute_info_set(), fill_collection(), pt_to_list_key(), ux_col_get(), and ux_get_generated_keys_client_insert().
int db_col_insert (DB_COLLECTION * col, int element_index, DB_VALUE * value)
Definition at line 1289 of file db_set.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, DB_TYPE_SEQUENCE, error(), NO_ERROR, NULL, db_set::owner, set_add_element(), set_get_type(), and set_insert_element().
int db_col_ismember (DB_COLLECTION * col, DB_VALUE * value)
Definition at line 1327 of file db_set.c.
References CHECK_1ARG_MINUSONE, CHECK_CONNECT_MINUSONE, and set_ismember().
int db_col_optimize (DB_COLLECTION * col)
Definition at line 1478 of file db_set.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, error(), NO_ERROR, and set_optimize().
int db_col_print (DB_COLLECTION * col)
Definition at line 1466 of file db_set.c.
References db_col_fprint().
int db_col_put (DB_COLLECTION * col, int element_index, DB_VALUE * value)
Definition at line 1249 of file db_set.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, DB_TYPE_SEQUENCE, error(), NO_ERROR, NULL, db_set::owner, set_add_element(), set_get_type(), and set_put_element().
Referenced by set_to_db_value_mapf().
int db_col_size (DB_COLLECTION * col)
Definition at line 1167 of file db_set.c.
References CHECK_1ARG_MINUSONE, CHECK_CONNECT_MINUSONE, and set_size().
Referenced by execute_info_set(), fill_collection(), pt_to_list_key(), qo_analyze_term(), ux_col_get(), ux_col_size(), and ux_get_generated_keys_client_insert().
DB_TYPE db_col_type (DB_COLLECTION * col)
Definition at line 1402 of file db_set.c.
References CHECK_1ARG_ERROR_WITH_TYPE, CHECK_CONNECT_ERROR, DB_TYPE_NULL, and set_get_type().
int db_seq_cardinality (DB_SET * set)
Definition at line 867 of file db_set.c.
References CHECK_1ARG_MINUSONE, CHECK_CONNECT_MINUSONE, and set_cardinality().
DB_SEQ* db_seq_copy (DB_SEQ * source)
Definition at line 428 of file db_set.c.
References CHECK_CONNECT_NULL, NULL, and set_copy().
Referenced by adjust_partition_range(), classobj_copy_partition_info(), disk_to_partition_info(), or_class_get_partition_info(), partition_pruning_context_to_cache_entry(), and pt_node_to_partition_info().
DB_SET* db_seq_create (MOP classop, const char * name, int size)
Definition at line 252 of file db_set.c.
References au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_CONNECT_NULL, classobj_find_attribute(), DB_TYPE_SEQUENCE, ER_OBJ_DOMAIN_CONFLICT, ER_OBJ_INVALID_ATTRIBUTE, error(), ERROR_SET1, pr_type::id, NO_ERROR, NULL, set_create_sequence(), and sm_attribute::type.
Referenced by cursor_fixup_set_vobjs(), db_value_domain_default(), netval_to_dbval(), pt_db_value_initialize(), pt_evaluate_tree_internal(), qdata_convert_dbvals_to_set(), qdata_convert_table_to_set(), regu_make_constant_vid(), setof_mop_to_setof_vobj(), tp_value_cast_internal(), vid_encode_object(), and vid_make_vid().
int db_seq_drop (DB_SET * set, int index)
Definition at line 823 of file db_set.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, NULL, and set_drop_seq_element().
Referenced by ux_col_seq_drop().
int db_seq_filter (DB_SET * set)
Definition at line 372 of file db_set.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, NULL, and set_filter().
int db_seq_find (DB_SET * set, DB_VALUE * value, int index)
Definition at line 908 of file db_set.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and set_find_seq_element().
int db_seq_free (DB_SEQ * seq)
Definition at line 323 of file db_set.c.
References NO_ERROR, NULL, and set_free().
Referenced by heap_clear_partition_info(), heap_get_partitions_from_subclasses(), partition_free_cache_entry(), and partition_pruning_context_to_cache_entry().
int db_seq_get (DB_SET * set, int index, DB_VALUE * value)
Definition at line 712 of file db_set.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and set_get_element().
Referenced by ex_contains_object_reference(), obj_get_path(), qdata_add_sequence_to_dbval(), qdata_get_class_of_function(), qexec_add_composite_lock(), qexec_upddel_add_unique_oid_to_ehid(), vid_build_non_upd_object(), and vid_fetch_instance().
int db_seq_insert (DB_SET * set, int index, DB_VALUE * value)
Definition at line 786 of file db_set.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, DB_TYPE_LAST, DB_VALUE_TYPE, ER_OBJ_INVALID_ARGUMENTS, error(), ERROR_SET, NO_ERROR, NULL, and set_insert_element().
Referenced by netval_to_dbval(), and ux_col_seq_insert().
int db_seq_print (DB_SET * set)
Definition at line 886 of file db_set.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, NO_ERROR, and set_print().
int db_seq_put (DB_SET * set, int index, DB_VALUE * value)
Definition at line 745 of file db_set.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, DB_TYPE_LAST, DB_VALUE_TYPE, ER_OBJ_INVALID_ARGUMENTS, error(), ERROR_SET, NO_ERROR, NULL, and set_put_element().
Referenced by cursor_fixup_set_vobjs(), pt_seq_value_to_db(), pt_set_table_to_db(), qdata_add_sequence_to_dbval(), regu_make_constant_vid(), setof_mop_to_setof_vobj(), tp_value_cast_internal(), ux_col_seq_put(), vid_encode_object(), vid_fetch_instance(), and vid_make_vid().
int db_seq_size (DB_SET * set)
Definition at line 848 of file db_set.c.
References CHECK_1ARG_MINUSONE, CHECK_CONNECT_MINUSONE, and set_size().
Referenced by qdata_add_sequence_to_dbval(), set_has_objs(), setof_mop_to_setof_vobj(), and vid_fetch_instance().
int db_set_add (DB_SET * set, DB_VALUE * value)
Definition at line 465 of file db_set.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, DB_TYPE_LAST, DB_VALUE_TYPE, ER_OBJ_INVALID_ARGUMENTS, error(), ERROR_SET, NO_ERROR, NULL, and set_add_element().
Referenced by au_add_direct_groups(), au_add_member_internal(), au_add_user(), au_drop_user(), cursor_fixup_set_vobjs(), netval_to_dbval(), pt_set_table_to_db(), pt_set_value_to_db(), setof_mop_to_setof_vobj(), ux_col_set_add(), and vid_fetch_instance().
int db_set_cardinality (DB_SET * set)
Definition at line 578 of file db_set.c.
References CHECK_1ARG_MINUSONE, CHECK_CONNECT_MINUSONE, and set_cardinality().
Referenced by vid_fetch_instance().
DB_SET* db_set_copy (DB_SET * source)
Definition at line 402 of file db_set.c.
References CHECK_CONNECT_NULL, NULL, and set_copy().
DB_SET* db_set_create (MOP classop, const char * name)
Definition at line 72 of file db_set.c.
References au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_CONNECT_NULL, classobj_find_attribute(), DB_TYPE_MULTISET, DB_TYPE_SEQUENCE, DB_TYPE_SET, ER_OBJ_DOMAIN_CONFLICT, ER_OBJ_INVALID_ATTRIBUTE, error(), ERROR_SET1, pr_type::id, NO_ERROR, NULL, set_create_basic(), set_create_multi(), set_create_sequence(), and sm_attribute::type.
DB_SET* db_set_create_basic (MOP classop, const char * name)
Definition at line 134 of file db_set.c.
References au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_CONNECT_NULL, classobj_find_attribute(), DB_TYPE_SET, ER_OBJ_DOMAIN_CONFLICT, ER_OBJ_INVALID_ATTRIBUTE, error(), ERROR_SET1, pr_type::id, NO_ERROR, NULL, set_create_basic(), and sm_attribute::type.
Referenced by cursor_fixup_set_vobjs(), db_value_domain_default(), netval_to_dbval(), pt_check_union_type_compatibility_of_values_query(), pt_db_value_initialize(), pt_evaluate_tree_internal(), qdata_convert_dbvals_to_set(), qdata_convert_table_to_set(), and setof_mop_to_setof_vobj().
DB_SET* db_set_create_multi (MOP classop, const char * name)
Definition at line 192 of file db_set.c.
References au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_CONNECT_NULL, classobj_find_attribute(), DB_TYPE_MULTISET, ER_OBJ_DOMAIN_CONFLICT, ER_OBJ_INVALID_ATTRIBUTE, error(), ERROR_SET1, pr_type::id, NO_ERROR, NULL, set_create_multi(), and sm_attribute::type.
Referenced by cursor_fixup_set_vobjs(), db_value_domain_default(), netval_to_dbval(), pt_db_value_initialize(), pt_evaluate_tree_internal(), qdata_convert_dbvals_to_set(), qdata_convert_table_to_set(), and setof_mop_to_setof_vobj().
int db_set_drop (DB_SET * set, DB_VALUE * value)
Definition at line 530 of file db_set.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, NULL, and set_drop_element().
Referenced by au_drop_member(), and ux_col_set_drop().
int db_set_filter (DB_SET * set)
Definition at line 344 of file db_set.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, NULL, and set_filter().
int db_set_free (DB_SET * set)
Definition at line 306 of file db_set.c.
References NO_ERROR, NULL, and set_free().
Referenced by cursor_fixup_set_vobjs(), dbval_to_net_buf(), or_get_all_representation(), or_get_current_representation(), and or_get_old_representation().
int db_set_get (DB_SET * set, int index, DB_VALUE * value)
Definition at line 508 of file db_set.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and set_get_element().
Referenced by cursor_fixup_set_vobjs(), cursor_has_set_vobjs(), dbval_to_net_buf(), ex_contains_object_reference(), heap_get_referenced_by(), obj_get_path(), partition_load_partition_predicate(), partition_prune_hash(), partition_prune_list(), partition_prune_range(), pt_print_db_value(), pt_set_elements_to_value(), qexec_collection_has_null(), qexec_execute_obj_fetch(), qproc_next_set_scan(), serialize_collection_as_string(), set_has_objs(), set_to_string(), setof_mop_to_setof_vobj(), vid_fetch_instance(), and vid_vobj_to_object().
int db_set_has_null (DB_COLLECTION * set)
Definition at line 644 of file db_set.c.
References CHECK_1ARG_FALSE, CHECK_CONNECT_FALSE, and set_has_null().
Referenced by partition_prune_list().
int db_set_isempty (DB_SET * set)
Definition at line 621 of file db_set.c.
References CHECK_1ARG_FALSE, CHECK_CONNECT_FALSE, and set_isempty().
int db_set_ismember (DB_SET * set, DB_VALUE * value)
Definition at line 598 of file db_set.c.
References CHECK_1ARG_FALSE, CHECK_CONNECT_FALSE, and set_ismember().
Referenced by partition_prune_list().
int db_set_print (DB_SET * set)
Definition at line 664 of file db_set.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, NO_ERROR, and set_print().
Referenced by cursor_fetch_page_having_tuple().
int db_set_size (DB_SET * set)
Definition at line 557 of file db_set.c.
References CHECK_1ARG_MINUSONE, CHECK_CONNECT_MINUSONE, and set_size().
Referenced by cursor_fixup_set_vobjs(), cursor_has_set_vobjs(), dbval_to_net_buf(), eval_pred(), ex_contains_object_reference(), heap_get_referenced_by(), partition_load_partition_predicate(), partition_prune_hash(), partition_prune_list(), pt_evaluate_db_value_expr(), pt_print_db_value(), pt_set_elements_to_value(), qexec_collection_has_null(), qexec_execute_obj_fetch(), qproc_next_set_scan(), serialize_collection_as_string(), set_to_string(), and vid_vobj_to_object().
DB_TYPE db_set_type (DB_SET * set)
Definition at line 683 of file db_set.c.
References DB_TYPE_NULL, NULL, and set_get_type().
Referenced by ex_contains_object_reference(), and setof_mop_to_setof_vobj().