CUBRID Engine: src/api/db_stub.c File Reference
db_stub.c File Reference
#include "config.h"
#include <string.h>
#include <stdlib.h>
#include <assert.h>
#include "api_handle.h"
#include "db_stub.h"
#include "db.h"
#include "parser.h"
#include "schema_manager.h"
#include "execute_schema.h"
#include "execute_statement.h"
#include "boot_cl.h"
#include "system_parameter.h"
#include "authenticate.h"
#include "object_accessor.h"
#include "jsp_sr.h"
Macros
#define API_PROGRAM_NAME "CUBRID C API"
#define ER_SET_AND_RETURN(X)
Functions
static int conn_end_tran (BH_INTERFACE *bh_interface, CI_CONN_STRUCTURE *pconn, bool commit)
static int stmt_release_children (BH_INTERFACE *bh_interface, CI_STMT_STRUCTURE *pstmt, bool resultset_only)
static int stmt_bind_pmeta_handle (BH_INTERFACE *bh_interface, CI_STMT_STRUCTURE *pstmt, CI_PARAM_META_STRUCTURE **outmeta)
static int api_rmeta_get_count (API_RESULTSET_META *impl, int *count)
static int api_rmeta_get_info (API_RESULTSET_META *impl, int index, CI_RMETA_INFO_TYPE type, void *arg, size_t size)
static int api_rs_get_resultset_metadata (API_RESULTSET *res, API_RESULTSET_META **rimpl)
static int api_rs_fetch (API_RESULTSET *res, int offset, CI_FETCH_POSITION pos)
static int api_rs_fetch_tell (API_RESULTSET *res, int *offset)
static int api_rs_clear_updates (API_RESULTSET *res)
static int api_rs_delete_row (API_RESULTSET *res)
static int api_rs_get_value (API_RESULTSET *res, int index, CI_TYPE type, void *addr, size_t len, size_t *outlen, bool *is_null)
static int api_rs_get_value_by_name (API_RESULTSET *res, const char *name, CI_TYPE type, void *addr, size_t len, size_t *outlen, bool *isnull)
static int api_rs_update_value (API_RESULTSET *res, int index, CI_TYPE type, void *addr, size_t len)
static int api_rs_apply_row (API_RESULTSET *res)
static void api_rs_destroy (API_RESULTSET *res)
static int get_col_count (DB_QUERY_TYPE *query_type)
static int create_resultset_value_table (int num_col, BIND_HANDLE conn, CI_RESULTSET_STRUCTURE *prs, VALUE_BIND_TABLE **value_table)
static void conn_destroyf (BH_BIND *ptr)
static void stmt_destroyf (BH_BIND *ptr)
static void rs_destroyf (BH_BIND *ptr)
static void rs_meta_destroyf (BH_BIND *ptr)
static void pmeta_destroyf (BH_BIND *ptr)
static void batch_res_destroyf (BH_BIND *ptr)
static int init_conn_structure (CI_CONN_STRUCTURE *pconn)
static int init_stmt_structure (CI_STMT_STRUCTURE *pstmt)
static int init_resultset_structure (CI_RESULTSET_STRUCTURE *prs)
static int init_rmeta_structure (CI_RESULTSET_META_STRUCTURE *prmeta)
static int init_pmeta_structure (CI_PARAM_META_STRUCTURE *ppmeta)
static int init_batch_rs_structure (CI_BATCH_RESULT_STRUCTURE *pbrs)
static int stmt_exec_immediate_internal (BH_INTERFACE *bh_interface, CI_STMT_STRUCTURE *pstmt, char *sql, size_t len, CI_RESULTSET *rs, int *r)
static int stmt_prepare_internal (BH_INTERFACE *bh_interface, CI_STMT_STRUCTURE *pstmt, const char *sql, size_t len)
static int stmt_get_parameter_internal (BH_INTERFACE *bh_interface, CI_STMT_STRUCTURE *pstmt, int index, CI_TYPE type, void *addr, size_t len, size_t *outlen, bool *isnull)
static int stmt_set_parameter_internal (BH_INTERFACE *bh_interface, CI_STMT_STRUCTURE *pstmt, int index, CI_TYPE type, void *val, size_t size)
static int stmt_reset_session_and_parse (CI_STMT_STRUCTURE *pstmt, const char *sql, size_t len)
static int stmt_exec_internal (BH_INTERFACE *bh_interface, CI_STMT_STRUCTURE *pstmt, CI_RESULTSET *rs, int *r)
static int stmt_get_resultset_metadata_internal (BH_INTERFACE *bh_interface, CI_STMT_STRUCTURE *pstmt, CI_RESULTSET_METADATA *r)
static API_RESULTSET_META_IFS * get_query_rmeta_ifs (void)
static API_RESULTSET_IFS * get_query_rs_ifs (void)
static int stmt_bind_resultset_meta_handle (BH_INTERFACE *bh_interface, CI_STMT_STRUCTURE *pstmt, int stmt_idx, CI_RESULTSET_META_STRUCTURE **outmeta)
static int res_fetch_internal (BH_INTERFACE *bh_interface, CI_RESULTSET_STRUCTURE *prs, int offset, CI_FETCH_POSITION pos)
static int res_delete_row_internal (BH_INTERFACE *bh_interface, CI_RESULTSET_STRUCTURE *prs)
static int rs_get_index_by_name (void *impl, const char *name, int *ri)
static int rs_get_db_value (void *impl, int index, DB_VALUE *val)
static int rs_set_db_value (void *impl, int index, DB_VALUE *val)
static int rs_init_domain (void *impl, int index, DB_VALUE *val)
static int pmeta_get_info_internal (BH_INTERFACE *bh_interface, CI_PARAM_META_STRUCTURE *ppmeta, int index, CI_PMETA_INFO_TYPE type, void *arg, size_t size)
static int stmt_add_batch_param (CI_STMT_STRUCTURE *pstmt, DB_VALUE *val, int num_val)
static int stmt_exec_prepared_batch_internal (BH_INTERFACE *bh_interface, CI_STMT_STRUCTURE *pstmt, CI_BATCH_RESULT *br)
static int stmt_exec_batch_query_internal (BH_INTERFACE *bh_interface, CI_STMT_STRUCTURE *pstmt, CI_BATCH_RESULT *br)
static int conn_restart_client (CI_CONN_STRUCTURE *pconn, const char *program, int print_version, const char *volume, short port)
static int get_connection_opool (COMMON_API_STRUCTURE *pst, API_OBJECT_RESULTSET_POOL **opool)
static int stmt_batch_alloc_and_bind_new_result (BH_INTERFACE *bh_interface, CI_STMT_STRUCTURE *pstmt, CI_BATCH_RESULT_STRUCTURE **out_pbrs, CI_BATCH_RESULT *outhbr)
static int stmt_batch_result_free (BH_INTERFACE *bh_interface, CI_STMT_STRUCTURE *pstmt)
static int stmt_add_batch_string (CI_STMT_STRUCTURE *pstmt, const char *sql, size_t len)
static int stmt_make_error_info (CI_STMT_STRUCTURE *pstmt, int statement_id)
static int stmt_remove_error_info (CI_STMT_STRUCTURE *pstmt)
static int stmt_exec_one_statement (BH_INTERFACE *bh_interface, int stmt_idx, CI_STMT_STRUCTURE *pstmt, CI_RESULTSET *rs, int *r)
int ci_err_set (int error_code)
static int ci_create_connection_impl (CI_CONNECTION *conn)
static int ci_conn_connect_impl (COMMON_API_STRUCTURE *pst, const char *host, unsigned short port, const char *databasename, const char *user_name, const char *password)
static int ci_conn_close_impl (COMMON_API_STRUCTURE *pst)
static int ci_conn_create_statement_impl (COMMON_API_STRUCTURE *pst, CI_STATEMENT *stmt)
static int ci_conn_set_option_impl (COMMON_API_STRUCTURE *pst, CI_CONNECTION_OPTION option, void *arg, size_t size)
static int ci_conn_get_option_impl (COMMON_API_STRUCTURE *pst, CI_CONNECTION_OPTION option, void *arg, size_t size)
static int ci_conn_commit_impl (COMMON_API_STRUCTURE *pst)
static int ci_conn_rollback_impl (COMMON_API_STRUCTURE *pst)
static int ci_conn_get_error_impl (COMMON_API_STRUCTURE *pst, int *err, char *msg, size_t size)
static int ci_stmt_add_batch_query_impl (COMMON_API_STRUCTURE *pst, const char *sql, size_t len)
static int ci_stmt_add_batch_impl (COMMON_API_STRUCTURE *pst)
static int ci_stmt_clear_batch_impl (COMMON_API_STRUCTURE *pst)
static int ci_stmt_execute_immediate_impl (COMMON_API_STRUCTURE *pst, char *sql, size_t len, CI_RESULTSET *rs, int *r)
static int ci_stmt_execute_impl (COMMON_API_STRUCTURE *pst, CI_RESULTSET *rs, int *r)
static int ci_stmt_execute_batch_impl (COMMON_API_STRUCTURE *pst, CI_BATCH_RESULT *br)
static int ci_stmt_get_option_impl (COMMON_API_STRUCTURE *pst, CI_STATEMENT_OPTION option, void *arg, size_t size)
static int ci_stmt_set_option_impl (COMMON_API_STRUCTURE *pst, CI_STATEMENT_OPTION option, void *arg, size_t size)
static int ci_stmt_prepare_impl (COMMON_API_STRUCTURE *pst, const char *sql, size_t len)
static int ci_stmt_register_out_parameter_impl (COMMON_API_STRUCTURE *pst, int index)
static int ci_stmt_get_resultset_metadata_impl (COMMON_API_STRUCTURE *pst, CI_RESULTSET_METADATA *r)
static int ci_stmt_get_parameter_metadata_impl (COMMON_API_STRUCTURE *pst, CI_PARAMETER_METADATA *r)
static int ci_stmt_get_parameter_impl (COMMON_API_STRUCTURE *pst, int index, CI_TYPE type, void *addr, size_t len, size_t *outlen, bool *isnull)
static int ci_stmt_set_parameter_impl (COMMON_API_STRUCTURE *pst, int index, CI_TYPE type, void *val, size_t size)
static int ci_stmt_get_resultset_impl (COMMON_API_STRUCTURE *pst, CI_RESULTSET *res)
static int ci_stmt_affected_rows_impl (COMMON_API_STRUCTURE *pst, int *out)
static int ci_stmt_next_result_impl (COMMON_API_STRUCTURE *pst, bool *exist_result)
static int ci_batch_res_query_count_impl (COMMON_API_STRUCTURE *pst, int *count)
static int ci_batch_res_get_result_impl (COMMON_API_STRUCTURE *pst, int index, int *ret, int *nr)
static int ci_batch_res_get_error_impl (COMMON_API_STRUCTURE *pst, int index, int *err_code, char *err_msg, size_t buf_size)
static int ci_pmeta_get_count_impl (COMMON_API_STRUCTURE *pst, int *count)
static int ci_pmeta_get_info_impl (COMMON_API_STRUCTURE *pst, int index, CI_PMETA_INFO_TYPE type, void *arg, size_t size)
static int ci_stmt_get_first_error_impl (COMMON_API_STRUCTURE *pst, int *line, int *col, int *errcode, char *err_msg, size_t size)
static int ci_stmt_get_next_error_impl (COMMON_API_STRUCTURE *pst, int *line, int *col, int *errcode, char *err_msg, size_t size)
static int ci_stmt_get_query_type_impl (COMMON_API_STRUCTURE *pst, CUBRID_STMT_TYPE *type)
static int ci_stmt_get_start_line_impl (COMMON_API_STRUCTURE *pst, int *line)
static int ci_collection_new_impl (CI_CONNECTION conn, CI_COLLECTION *coll)
Variables
static API_RESULTSET_META_IFS RMETA_IFS_
static API_RESULTSET_IFS RS_IFS_
CUBRID_API_FUNCTION_TABLE Cubrid_api_function_table
Macro Definition Documentation
#define API_PROGRAM_NAME "CUBRID C API"
Definition at line 41 of file db_stub.c.
Referenced by ci_conn_connect_impl().
#define ER_SET_AND_RETURN (X)
Value:
do {                                     \
    if (X != NO_ERROR) {                   \
      ci_err_set(X);                    \
      return X;                            \
    }                                      \
  } while(0)
Definition at line 43 of file db_stub.c.
Referenced by api_rmeta_get_info(), api_rs_apply_row(), api_rs_clear_updates(), api_rs_delete_row(), api_rs_get_resultset_metadata(), api_rs_get_value(), api_rs_get_value_by_name(), api_rs_update_value(), ci_batch_res_get_error_impl(), ci_batch_res_get_result_impl(), ci_conn_create_statement_impl(), ci_conn_get_option_impl(), ci_conn_set_option_impl(), ci_create_connection_impl(), ci_stmt_add_batch_impl(), ci_stmt_add_batch_query_impl(), ci_stmt_affected_rows_impl(), ci_stmt_clear_batch_impl(), ci_stmt_execute_batch_impl(), ci_stmt_execute_immediate_impl(), ci_stmt_execute_impl(), ci_stmt_get_first_error_impl(), ci_stmt_get_next_error_impl(), ci_stmt_get_option_impl(), ci_stmt_get_parameter_impl(), ci_stmt_get_parameter_metadata_impl(), ci_stmt_get_query_type_impl(), ci_stmt_get_resultset_impl(), ci_stmt_get_resultset_metadata_impl(), ci_stmt_get_start_line_impl(), ci_stmt_next_result_impl(), ci_stmt_prepare_impl(), ci_stmt_register_out_parameter_impl(), ci_stmt_set_option_impl(), ci_stmt_set_parameter_impl(), conn_end_tran(), pmeta_get_info_internal(), res_delete_row_internal(), rs_get_index_by_name(), rs_init_domain(), rs_set_db_value(), stmt_add_batch_param(), stmt_add_batch_string(), stmt_batch_alloc_and_bind_new_result(), stmt_batch_result_free(), stmt_bind_pmeta_handle(), stmt_bind_resultset_meta_handle(), stmt_exec_batch_query_internal(), stmt_exec_immediate_internal(), stmt_exec_internal(), stmt_exec_one_statement(), stmt_get_parameter_internal(), stmt_get_resultset_metadata_internal(), stmt_prepare_internal(), stmt_release_children(), stmt_reset_session_and_parse(), and stmt_set_parameter_internal().
Function Documentation
static int api_rmeta_get_count (API_RESULTSET_META * impl, int * count) static
Definition at line 982 of file db_stub.c.
References assert, ci_resultset_meta_s::col_count, and NO_ERROR.
static int api_rmeta_get_info (API_RESULTSET_META * impl, int index, CI_RMETA_INFO_TYPE type, void * arg, size_t size) static
Definition at line 1005 of file db_stub.c.
References au_fetch_class(), AU_FETCH_READ, AU_SELECT, ci_resultset_meta_s::bh_interface, bh_interface_s::bind_get_parent, tp_domain::class_mop, classobj_find_attribute(), db_query_type::db_type, db_type_to_type(), db_query_type::domain, ER_INTERFACE_INVALID_ARGUMENT, ER_INTERFACE_NOT_ENOUGH_DATA_SIZE, ER_INTERFACE_RESULTSET_CLOSED, ER_SET_AND_RETURN, sm_attribute::flags, i, db_query_type::name, db_query_type::next, NO_ERROR, NULL, ci_stmt_s::opt, db_query_type::original_name, tp_domain::precision, ci_resultset_meta_s::query_type, tp_domain::scale, SM_ATTFLAG_AUTO_INCREMENT, SM_ATTFLAG_NON_NULL, sm_get_ch_name(), db_query_type::src_domain, strlen, and ci_stmt_option_s::updatable_result.
static int api_rs_apply_row (API_RESULTSET * res) static
Definition at line 927 of file db_stub.c.
References value_bind_table_ifs_s::apply_updates, assert, ci_resultset_s::bh_interface, bh_interface_s::bind_get_parent, ci_resultset_s::current_row_isdeleted, ci_resultset_s::current_row_isupdated, ER_INTERFACE_RESULTSET_NOT_UPDATABLE, ER_INTERFACE_ROW_IS_DELETED, ER_SET_AND_RETURN, value_bind_table_s::ifs, NO_ERROR, ci_stmt_s::opt, ci_stmt_option_s::updatable_result, and ci_resultset_s::value_table.
static int api_rs_clear_updates (API_RESULTSET * res) static
Definition at line 724 of file db_stub.c.
References assert, ci_resultset_s::bh_interface, bh_interface_s::bind_get_parent, ci_resultset_s::current_row_isdeleted, ci_resultset_s::current_row_isupdated, ER_INTERFACE_RESULTSET_NOT_UPDATABLE, ER_INTERFACE_ROW_IS_DELETED, ER_SET_AND_RETURN, value_bind_table_s::ifs, NO_ERROR, ci_stmt_s::opt, value_bind_table_ifs_s::reset, ci_stmt_option_s::updatable_result, and ci_resultset_s::value_table.
static int api_rs_delete_row (API_RESULTSET * res) static
Definition at line 768 of file db_stub.c.
References assert, ci_resultset_s::bh_interface, bh_interface_s::bind_get_parent, ci_resultset_s::current_row_isdeleted, ER_INTERFACE_RESULTSET_NOT_UPDATABLE, ER_INTERFACE_ROW_IS_DELETED, ER_SET_AND_RETURN, NO_ERROR, ci_stmt_s::opt, res_delete_row_internal(), and ci_stmt_option_s::updatable_result.
static void api_rs_destroy (API_RESULTSET * res) static
Definition at line 970 of file db_stub.c.
static int api_rs_fetch (API_RESULTSET * res, int offset, CI_FETCH_POSITION pos) static
Definition at line 665 of file db_stub.c.
References assert, ci_resultset_s::bh_interface, ci_resultset_s::current_row_isdeleted, ci_resultset_s::current_row_isupdated, value_bind_table_s::ifs, NO_ERROR, res_fetch_internal(), value_bind_table_ifs_s::reset, and ci_resultset_s::value_table.
static int api_rs_fetch_tell (API_RESULTSET * res, int * offset) static
Definition at line 691 of file db_stub.c.
References db_select_result::cursor_id, db_query_result::g, NO_ERROR, db_query_result::res, ci_resultset_s::result, db_query_result::s, T_CALL, T_GET, T_OBJFETCH, T_SELECT, db_get_result::tpl_idx, cursor_id::tuple_no, and db_query_result::type.
static int api_rs_get_resultset_metadata (API_RESULTSET * res, API_RESULTSET_META ** rimpl) static
Definition at line 601 of file db_stub.c.
References assert, ci_resultset_s::bh_interface, bh_interface_s::bind_get_parent, ER_INTERFACE_INVALID_HANDLE, ER_SET_AND_RETURN, HANDLE_TYPE_STATEMENT, NO_ERROR, NULL, ci_resultset_s::prsmeta, ci_stmt_s::rs_info, stmt_result_info_s::rsmeta, stmt_bind_resultset_meta_handle(), and ci_resultset_s::stmt_idx.
static int api_rs_get_value (API_RESULTSET * res, int index, CI_TYPE type, void * addr, size_t len, size_t * outlen, bool * is_null) static
Definition at line 817 of file db_stub.c.
References assert, ci_resultset_s::current_row_isdeleted, ER_INTERFACE_ROW_IS_DELETED, ER_SET_AND_RETURN, value_bind_table_ifs_s::get_value, value_bind_table_s::ifs, and ci_resultset_s::value_table.
static int api_rs_get_value_by_name (API_RESULTSET * res, const char * name, CI_TYPE type, void * addr, size_t len, size_t * outlen, bool * isnull) static
Definition at line 851 of file db_stub.c.
References assert, ci_resultset_s::current_row_isdeleted, ER_INTERFACE_ROW_IS_DELETED, ER_SET_AND_RETURN, value_bind_table_ifs_s::get_value_by_name, value_bind_table_s::ifs, and ci_resultset_s::value_table.
static int api_rs_update_value (API_RESULTSET * res, int index, CI_TYPE type, void * addr, size_t len) static
Definition at line 881 of file db_stub.c.
References assert, ci_resultset_s::bh_interface, bh_interface_s::bind_get_parent, ci_resultset_s::current_row_isdeleted, ci_resultset_s::current_row_isupdated, ER_INTERFACE_RESULTSET_NOT_UPDATABLE, ER_INTERFACE_ROW_IS_DELETED, ER_SET_AND_RETURN, value_bind_table_s::ifs, NO_ERROR, ci_stmt_s::opt, value_bind_table_ifs_s::set_value, ci_stmt_option_s::updatable_result, and ci_resultset_s::value_table.
static void batch_res_destroyf (BH_BIND * ptr) static
Definition at line 457 of file db_stub.c.
References assert, ci_batch_result_info_s::err_msg, HANDLE_TYPE_BATCH_RESULT, i, NULL, ci_batch_result_s::rs_count, and ci_batch_result_s::rs_info.
Referenced by init_batch_rs_structure().
static int ci_batch_res_get_error_impl (COMMON_API_STRUCTURE * pst, int index, int * err_code, char * err_msg, size_t buf_size) static
Definition at line 4314 of file db_stub.c.
References ER_INTERFACE_INVALID_ARGUMENT, ER_SET_AND_RETURN, ci_batch_result_info_s::err_code, ci_batch_result_info_s::err_msg, NO_ERROR, NULL, ci_batch_result_s::rs_count, and ci_batch_result_s::rs_info.
static int ci_batch_res_get_result_impl (COMMON_API_STRUCTURE * pst, int index, int * ret, int * nr) static
Definition at line 4286 of file db_stub.c.
References rs_meta_info::affected_row, ER_INTERFACE_INVALID_ARGUMENT, ER_SET_AND_RETURN, ci_batch_result_info_s::err_code, ci_batch_result_info_s::metainfo, NO_ERROR, ci_batch_result_s::rs_count, and ci_batch_result_s::rs_info.
static int ci_batch_res_query_count_impl (COMMON_API_STRUCTURE * pst, int * count) static
Definition at line 4266 of file db_stub.c.
References NO_ERROR, and ci_batch_result_s::rs_count.
static int ci_collection_new_impl (CI_CONNECTION conn, CI_COLLECTION * coll) static
Definition at line 4545 of file db_stub.c.
References api_collection_create(), and NO_ERROR.
static int ci_conn_close_impl (COMMON_API_STRUCTURE * pst) static
Definition at line 3176 of file db_stub.c.
References boot_shutdown_client(), NO_ERROR, os_set_signal_handler(), and prev_sigfpe_handler.
static int ci_conn_commit_impl (COMMON_API_STRUCTURE * pst) static
Definition at line 3368 of file db_stub.c.
References ci_conn_s::bh_interface, and conn_end_tran().
static int ci_conn_connect_impl (COMMON_API_STRUCTURE * pst, const char * host, unsigned short port, const char * databasename, const char * user_name, const char * password) static
Definition at line 3133 of file db_stub.c.
References API_PROGRAM_NAME, au_login(), CI_CONN_STATUS_CONNECTED, conn_restart_client(), ci_conn_s::conn_status, NO_ERROR, and NULL.
static int ci_conn_create_statement_impl (COMMON_API_STRUCTURE * pst, CI_STATEMENT * stmt) static
Definition at line 3197 of file db_stub.c.
References bh_interface_s::alloc_handle, ci_conn_s::bh_interface, bh_interface_s::bind_graft, ER_INTERFACE_NO_MORE_MEMORY, ER_SET_AND_RETURN, init_stmt_structure(), NO_ERROR, NULL, and ci_stmt_s::pconn.
static int ci_conn_get_error_impl (COMMON_API_STRUCTURE * pst, int * err, char * msg, size_t size) static
Definition at line 3407 of file db_stub.c.
References api_get_errid, api_get_errmsg, assert, and NO_ERROR.
static int ci_conn_get_option_impl (COMMON_API_STRUCTURE * pst, CI_CONNECTION_OPTION option, void * arg, size_t size) static
Definition at line 3301 of file db_stub.c.
References ci_conn_option_s::autocommit, ci_conn_option_s::cli_version, ER_INTERFACE_INVALID_ARGUMENT, ER_SET_AND_RETURN, ci_conn_option_s::isolation, NO_ERROR, ci_conn_s::opt, ci_conn_option_s::srv_version, tran_get_tran_settings(), and VERSION_LENGTH.
static int ci_conn_rollback_impl (COMMON_API_STRUCTURE * pst) static
Definition at line 3386 of file db_stub.c.
References ci_conn_s::bh_interface, and conn_end_tran().
static int ci_conn_set_option_impl (COMMON_API_STRUCTURE * pst, CI_CONNECTION_OPTION option, void * arg, size_t size) static
Definition at line 3243 of file db_stub.c.
References ci_conn_option_s::autocommit, ER_INTERFACE_INVALID_ARGUMENT, ER_INTERFACE_NOT_SUPPORTED_OPERATION, ER_SET_AND_RETURN, ci_conn_option_s::isolation, NO_ERROR, ci_conn_s::opt, TM_TRAN_ASYNC_WS, tran_reset_isolation(), and tran_reset_wait_times().
static int ci_create_connection_impl (CI_CONNECTION * conn) static
Definition at line 3076 of file db_stub.c.
References bh_interface_s::alloc_handle, api_object_resultset_pool_create(), ci_conn_s::bh_interface, bh_root_acquire(), bh_root_lock(), BH_ROOT_TYPE_STATIC_HASH_64, bh_root_unlock(), ER_INTERFACE_NO_MORE_MEMORY, ER_SET_AND_RETURN, init_conn_structure(), NO_ERROR, NULL, and ci_conn_s::opool.
int ci_err_set (int error_code)
Definition at line 3064 of file db_stub.c.
References api_er_set, ARG_FILE_LINE, ER_ERROR_SEVERITY, and NO_ERROR.
Referenced by stmt_reset_session_and_parse().
static int ci_pmeta_get_count_impl (COMMON_API_STRUCTURE * pst, int * count) static
Definition at line 4342 of file db_stub.c.
References NO_ERROR, and ci_parater_meta_s::param_count.
static int ci_pmeta_get_info_impl (COMMON_API_STRUCTURE * pst, int index, CI_PMETA_INFO_TYPE type, void * arg, size_t size) static
Definition at line 4363 of file db_stub.c.
References ci_parater_meta_s::bh_interface, and pmeta_get_info_internal().
static int ci_stmt_add_batch_impl (COMMON_API_STRUCTURE * pst) static
Definition at line 3507 of file db_stub.c.
References ci_stmt_s::batch_count, CI_STMT_STATUS_BATCH_ADDED, CI_STMT_STATUS_EXECUTED, CI_STMT_STATUS_PREPARED, ER_INTERFACE_IS_NOT_BATCH_STATEMENT, ER_INTERFACE_IS_NOT_PREPARED_STATEMENT, ER_INTERFACE_PARAM_IS_NOT_SET, ER_SET_AND_RETURN, parser_context::host_var_count, i, NO_ERROR, ci_stmt_s::param_val, ci_stmt_s::param_value_is_set, db_session::parser, ci_stmt_s::session, stmt_add_batch_param(), and ci_stmt_s::stmt_status.
static int ci_stmt_add_batch_query_impl (COMMON_API_STRUCTURE * pst, const char * sql, size_t len) static
Definition at line 3424 of file db_stub.c.
References ci_stmt_s::batch_count, CI_STMT_STATUS_BATCH_ADDED, CI_STMT_STATUS_EXECUTED, CI_STMT_STATUS_PREPARED, ER_INTERFACE_IS_NOT_BATCH_STATEMENT, ER_INTERFACE_IS_PREPARED_STATEMENT, ER_SET_AND_RETURN, NO_ERROR, stmt_add_batch_string(), and ci_stmt_s::stmt_status.
static int ci_stmt_affected_rows_impl (COMMON_API_STRUCTURE * pst, int * out) static
Definition at line 4169 of file db_stub.c.
References rs_meta_info::affected_row, CI_STMT_STATUS_EXECUTED, ci_stmt_s::current_rs_idx, ER_INTERFACE_NOT_EXECUTED, ER_SET_AND_RETURN, stmt_result_info_s::metainfo, NO_ERROR, ci_stmt_s::rs_info, and ci_stmt_s::stmt_status.
static int ci_stmt_clear_batch_impl (COMMON_API_STRUCTURE * pst) static
Definition at line 3555 of file db_stub.c.
References ci_stmt_s::batch_count, ci_stmt_s::batch_data, CI_STMT_STATUS_BATCH_ADDED, CI_STMT_STATUS_EXECUTED, CI_STMT_STATUS_PREPARED, ci_batch_data::data, ER_INTERFACE_CANNOT_CLEAR_BATCH, ER_SET_AND_RETURN, parser_context::host_var_count, ci_batch_data::next, NO_ERROR, NULL, db_session::parser, ci_batch_data::_data::query_string, ci_stmt_s::session, ci_stmt_s::stmt_status, and ci_batch_data::_data::val.
static int ci_stmt_execute_batch_impl (COMMON_API_STRUCTURE * pst, CI_BATCH_RESULT * br) static
Definition at line 3746 of file db_stub.c.
References ci_conn_option_s::autocommit, ci_conn_s::bh_interface, CI_STMT_STATUS_BATCH_ADDED, CI_STMT_STATUS_PREPARED, conn_end_tran(), ER_INTERFACE_CANNOT_BATCH_EXECUTE, ER_SET_AND_RETURN, NO_ERROR, ci_conn_s::opt, ci_stmt_s::pconn, stmt_exec_batch_query_internal(), stmt_exec_prepared_batch_internal(), and ci_stmt_s::stmt_status.
static int ci_stmt_execute_immediate_impl (COMMON_API_STRUCTURE * pst, char * sql, size_t len, CI_RESULTSET * rs, int * r) static
Definition at line 3603 of file db_stub.c.
References ci_conn_option_s::autocommit, ci_conn_s::bh_interface, CI_STMT_STATUS_BATCH_ADDED, CI_STMT_STATUS_EXECUTED, CI_STMT_STATUS_PREPARED, conn_end_tran(), ER_INTERFACE_IS_BATCH_STATEMENT, ER_INTERFACE_IS_PREPARED_STATEMENT, ER_SET_AND_RETURN, ci_conn_s::need_defered_commit, ci_conn_s::need_immediate_commit, NO_ERROR, ci_conn_s::opt, ci_stmt_s::pconn, stmt_exec_immediate_internal(), stmt_release_children(), and ci_stmt_s::stmt_status.
static int ci_stmt_execute_impl (COMMON_API_STRUCTURE * pst, CI_RESULTSET * rs, int * r) static
Definition at line 3675 of file db_stub.c.
References ci_conn_option_s::autocommit, ci_conn_s::bh_interface, CI_STMT_STATUS_BATCH_ADDED, CI_STMT_STATUS_EXECUTED, CI_STMT_STATUS_PREPARED, conn_end_tran(), ER_INTERFACE_IS_BATCH_STATEMENT, ER_INTERFACE_NOT_PREPARED, ER_SET_AND_RETURN, ci_conn_s::need_defered_commit, ci_conn_s::need_immediate_commit, NO_ERROR, ci_conn_s::opt, ci_stmt_s::pconn, stmt_exec_internal(), stmt_release_children(), and ci_stmt_s::stmt_status.
static int ci_stmt_get_first_error_impl (COMMON_API_STRUCTURE * pst, int * line, int * col, int * errcode, char * err_msg, size_t size) static
Definition at line 4387 of file db_stub.c.
References CI_STMT_STATUS_BATCH_ADDED, ci_stmt_error_info_s::column, ci_stmt_s::current_err_idx, ER_INTERFACE_IS_BATCH_STATEMENT, ER_INTERFACE_NO_MORE_ERROR, ER_SET_AND_RETURN, ci_stmt_error_info_s::err_code, ci_stmt_s::err_info, ci_stmt_error_info_s::err_msg, ci_stmt_error_info_s::line, NO_ERROR, NULL, and ci_stmt_s::stmt_status.
static int ci_stmt_get_next_error_impl (COMMON_API_STRUCTURE * pst, int * line, int * col, int * errcode, char * err_msg, size_t size) static
Definition at line 4432 of file db_stub.c.
References CI_STMT_STATUS_BATCH_ADDED, ci_stmt_error_info_s::column, ci_stmt_s::current_err_idx, ER_INTERFACE_IS_BATCH_STATEMENT, ER_INTERFACE_NO_MORE_ERROR, ER_SET_AND_RETURN, ci_stmt_error_info_s::err_code, ci_stmt_s::err_info, err_info, ci_stmt_error_info_s::err_msg, i, ci_stmt_error_info_s::line, ci_stmt_error_info_s::next, NO_ERROR, NULL, and ci_stmt_s::stmt_status.
static int ci_stmt_get_option_impl (COMMON_API_STRUCTURE * pst, CI_STATEMENT_OPTION option, void * arg, size_t size) static
Definition at line 3796 of file db_stub.c.
References ci_stmt_option_s::async_query, ER_INTERFACE_INVALID_ARGUMENT, ER_SET_AND_RETURN, ci_stmt_option_s::exec_continue_on_error, ci_stmt_option_s::lazy_exec, NO_ERROR, ci_stmt_s::opt, and ci_stmt_option_s::updatable_result.
static int ci_stmt_get_parameter_impl (COMMON_API_STRUCTURE * pst, int index, CI_TYPE type, void * addr, size_t len, size_t * outlen, bool * isnull) static
Definition at line 4070 of file db_stub.c.
References ci_conn_s::bh_interface, CI_STMT_STATUS_PREPARED, ER_INTERFACE_NOT_PREPARED, ER_SET_AND_RETURN, ci_stmt_s::pconn, stmt_get_parameter_internal(), and ci_stmt_s::stmt_status.
static int ci_stmt_get_parameter_metadata_impl (COMMON_API_STRUCTURE * pst, CI_PARAMETER_METADATA * r) static
Definition at line 4025 of file db_stub.c.
References ci_conn_s::bh_interface, bh_interface_s::bind_to_handle, CI_STMT_STATUS_PREPARED, ER_INTERFACE_NOT_PREPARED, ER_SET_AND_RETURN, NO_ERROR, NULL, ci_stmt_s::pconn, ci_stmt_s::ppmeta, stmt_bind_pmeta_handle(), and ci_stmt_s::stmt_status.
static int ci_stmt_get_query_type_impl (COMMON_API_STRUCTURE * pst, CUBRID_STMT_TYPE * type) static
Definition at line 4483 of file db_stub.c.
References CI_STMT_STATUS_BATCH_ADDED, CI_STMT_STATUS_EXECUTED, CI_STMT_STATUS_PREPARED, ci_stmt_s::current_rs_idx, ER_INTERFACE_IS_BATCH_STATEMENT, ER_INTERFACE_NOT_EXECUTED, ER_SET_AND_RETURN, stmt_result_info_s::metainfo, NO_ERROR, ci_stmt_s::rs_info, rs_meta_info::sql_type, and ci_stmt_s::stmt_status.
static int ci_stmt_get_resultset_impl (COMMON_API_STRUCTURE * pst, CI_RESULTSET * res) static
Definition at line 4126 of file db_stub.c.
References ci_conn_s::bh_interface, bh_interface_s::bind_to_handle, CI_STMT_STATUS_EXECUTED, ci_stmt_s::current_rs_idx, ER_INTERFACE_HAS_NO_RESULT_SET, ER_INTERFACE_NOT_EXECUTED, ER_INTERFACE_RESULTSET_CLOSED, ER_SET_AND_RETURN, rs_meta_info::has_result, stmt_result_info_s::metainfo, NO_ERROR, NULL, ci_stmt_s::pconn, stmt_result_info_s::rs, ci_stmt_s::rs_info, and ci_stmt_s::stmt_status.
static int ci_stmt_get_resultset_metadata_impl (COMMON_API_STRUCTURE * pst, CI_RESULTSET_METADATA * r) static
Definition at line 3994 of file db_stub.c.
References ci_conn_s::bh_interface, CI_STMT_STATUS_EXECUTED, CI_STMT_STATUS_PREPARED, ER_INTERFACE_NOT_PREPARED, ER_SET_AND_RETURN, NO_ERROR, ci_stmt_s::pconn, stmt_get_resultset_metadata_internal(), and ci_stmt_s::stmt_status.
static int ci_stmt_get_start_line_impl (COMMON_API_STRUCTURE * pst, int * line) static
Definition at line 4514 of file db_stub.c.
References CI_STMT_STATUS_BATCH_ADDED, CI_STMT_STATUS_EXECUTED, CI_STMT_STATUS_PREPARED, ci_stmt_s::current_rs_idx, db_get_start_line(), ER_INTERFACE_IS_BATCH_STATEMENT, ER_INTERFACE_NOT_EXECUTED, ER_SET_AND_RETURN, NO_ERROR, ci_stmt_s::session, and ci_stmt_s::stmt_status.
static int ci_stmt_next_result_impl (COMMON_API_STRUCTURE * pst, bool * exist_result) static
Definition at line 4195 of file db_stub.c.
References ci_conn_option_s::autocommit, ci_conn_s::bh_interface, CI_STMT_STATUS_EXECUTED, conn_end_tran(), ci_stmt_s::current_rs_idx, db_session::dimension, ER_INTERFACE_NOT_EXECUTED, ER_SET_AND_RETURN, ci_stmt_option_s::lazy_exec, ci_conn_s::need_defered_commit, ci_conn_s::need_immediate_commit, NO_ERROR, ci_conn_s::opt, ci_stmt_s::opt, ci_stmt_s::pconn, ci_stmt_s::session, stmt_exec_one_statement(), and ci_stmt_s::stmt_status.
static int ci_stmt_prepare_impl (COMMON_API_STRUCTURE * pst, const char * sql, size_t len) static
Definition at line 3896 of file db_stub.c.
References ci_conn_s::bh_interface, CI_STMT_STATUS_EXECUTED, CI_STMT_STATUS_PREPARED, ER_INTERFACE_NOT_SUPPORTED_OPERATION, ER_SET_AND_RETURN, NO_ERROR, ci_stmt_s::pconn, stmt_prepare_internal(), stmt_release_children(), and ci_stmt_s::stmt_status.
static int ci_stmt_register_out_parameter_impl (COMMON_API_STRUCTURE * pst, int index) static
Definition at line 3942 of file db_stub.c.
References ci_conn_s::bh_interface, CI_STMT_STATUS_PREPARED, ER_INTERFACE_INVALID_ARGUMENT, ER_INTERFACE_NOT_PREPARED, ER_SET_AND_RETURN, ci_parater_meta_s::is_out_param, NO_ERROR, NULL, ci_parater_meta_s::param_count, ci_stmt_s::param_value_is_set, ci_stmt_s::pconn, ci_stmt_s::ppmeta, stmt_bind_pmeta_handle(), stmt_set_parameter_internal(), and ci_stmt_s::stmt_status.
static int ci_stmt_set_option_impl (COMMON_API_STRUCTURE * pst, CI_STATEMENT_OPTION option, void * arg, size_t size) static
Definition at line 3846 of file db_stub.c.
References ci_stmt_option_s::async_query, ER_INTERFACE_INVALID_ARGUMENT, ER_INTERFACE_NOT_SUPPORTED_OPERATION, ER_SET_AND_RETURN, ci_stmt_option_s::exec_continue_on_error, ci_stmt_option_s::lazy_exec, NO_ERROR, ci_stmt_s::opt, and ci_stmt_option_s::updatable_result.
static int ci_stmt_set_parameter_impl (COMMON_API_STRUCTURE * pst, int index, CI_TYPE type, void * val, size_t size) static
Definition at line 4100 of file db_stub.c.
References ci_conn_s::bh_interface, CI_STMT_STATUS_PREPARED, ER_INTERFACE_NOT_PREPARED, ER_SET_AND_RETURN, ci_stmt_s::pconn, stmt_set_parameter_internal(), and ci_stmt_s::stmt_status.
static void conn_destroyf (BH_BIND * ptr) static
Definition at line 225 of file db_stub.c.
References assert, api_object_resultset_pool_s::destroy, HANDLE_TYPE_CONNECTION, and ci_conn_s::opool.
Referenced by init_conn_structure().
static int conn_end_tran (BH_INTERFACE * bh_interface, CI_CONN_STRUCTURE * pconn, bool commit) static
Definition at line 2732 of file db_stub.c.
References assert, bh_interface_s::bind_get_first_child, bh_interface_s::bind_get_next_sibling, db_session::dimension, ER_SET_AND_RETURN, i, NO_ERROR, NULL, stmt_result_info_s::rs, ci_stmt_s::rs_info, stmt_result_info_s::rsmeta, ci_stmt_s::session, stmt_release_children(), tran_abort(), and tran_commit().
Referenced by ci_conn_commit_impl(), ci_conn_rollback_impl(), ci_stmt_execute_batch_impl(), ci_stmt_execute_immediate_impl(), ci_stmt_execute_impl(), ci_stmt_next_result_impl(), and rs_destroyf().
static int conn_restart_client (CI_CONN_STRUCTURE * pconn, const char * program, int print_version, const char * volume, short port) static
Definition at line 2671 of file db_stub.c.
References au_link_static_methods(), boot_restart_client(), clientids::client_info, clientids::client_type, boot_client_credential::connect_order, DB_CLIENT_TYPE_DEFAULT, DB_CONNECT_ORDER_SEQ, db_Connect_status, DB_CONNECTION_STATUS_CONNECTED, DB_CONNECTION_STATUS_NOT_CONNECTED, db_Database_name, db_get_user_name(), boot_client_credential::db_name, boot_client_credential::db_password, db_Program_name, clientids::db_user, error(), clientids::host_name, jsp_jvm_is_loaded(), clientids::login_name, NO_ERROR, NULL, os_set_signal_handler(), prev_sigfpe_handler, clientids::process_id, clientids::program_name, sigfpe_handler(), and sysprm_set_force().
Referenced by ci_conn_connect_impl().
static int create_resultset_value_table (int num_col, BIND_HANDLE conn, CI_RESULTSET_STRUCTURE * prs, VALUE_BIND_TABLE ** value_table) static
Definition at line 2291 of file db_stub.c.
References create_db_value_bind_table(), rs_get_db_value(), rs_get_index_by_name(), rs_init_domain(), rs_set_db_value(), and ci_resultset_s::value_table.
Referenced by stmt_exec_internal(), and stmt_exec_one_statement().
static int get_col_count (DB_QUERY_TYPE * query_type) static
Definition at line 2058 of file db_stub.c.
References cubregex::count(), and db_query_type::next.
Referenced by stmt_bind_resultset_meta_handle().
static int get_connection_opool (COMMON_API_STRUCTURE * pst, API_OBJECT_RESULTSET_POOL ** opool) static
Definition at line 3041 of file db_stub.c.
References NO_ERROR, and ci_conn_s::opool.
static API_RESULTSET_META_IFS * get_query_rmeta_ifs (void) static
Definition at line 1910 of file db_stub.c.
References RMETA_IFS_.
Referenced by init_rmeta_structure().
static API_RESULTSET_IFS * get_query_rs_ifs (void) static
Definition at line 1920 of file db_stub.c.
References RS_IFS_.
Referenced by init_resultset_structure().
static int init_batch_rs_structure (CI_BATCH_RESULT_STRUCTURE * pbrs) static
Definition at line 583 of file db_stub.c.
References assert, batch_res_destroyf(), HANDLE_TYPE_BATCH_RESULT, NO_ERROR, and ci_batch_result_s::rs_count.
Referenced by stmt_batch_alloc_and_bind_new_result().
static int init_conn_structure (CI_CONN_STRUCTURE * pconn) static
Definition at line 492 of file db_stub.c.
References assert, conn_destroyf(), HANDLE_TYPE_CONNECTION, and NO_ERROR.
Referenced by ci_create_connection_impl().
static int init_pmeta_structure (CI_PARAM_META_STRUCTURE * ppmeta) static
Definition at line 566 of file db_stub.c.
References assert, HANDLE_TYPE_PMETA, NO_ERROR, and pmeta_destroyf().
Referenced by stmt_bind_pmeta_handle().
static int init_resultset_structure (CI_RESULTSET_STRUCTURE * prs) static
Definition at line 530 of file db_stub.c.
References assert, get_query_rs_ifs(), HANDLE_TYPE_RESULTSET, NO_ERROR, and rs_destroyf().
Referenced by stmt_exec_internal(), and stmt_exec_one_statement().
static int init_rmeta_structure (CI_RESULTSET_META_STRUCTURE * prmeta) static
Definition at line 548 of file db_stub.c.
References assert, get_query_rmeta_ifs(), HANDLE_TYPE_RMETA, NO_ERROR, and rs_meta_destroyf().
Referenced by stmt_bind_resultset_meta_handle().
static int init_stmt_structure (CI_STMT_STRUCTURE * pstmt) static
Definition at line 510 of file db_stub.c.
References assert, HANDLE_TYPE_STATEMENT, NO_ERROR, and stmt_destroyf().
Referenced by ci_conn_create_statement_impl().
static void pmeta_destroyf (BH_BIND * ptr) static
Definition at line 435 of file db_stub.c.
References assert, and HANDLE_TYPE_PMETA.
Referenced by init_pmeta_structure().
static int pmeta_get_info_internal (BH_INTERFACE * bh_interface, CI_PARAM_META_STRUCTURE * ppmeta, int index, CI_PMETA_INFO_TYPE type, void * arg, size_t size) static
Definition at line 2309 of file db_stub.c.
References assert, db_type_to_type(), ER_INTERFACE_GENERIC, ER_INTERFACE_INVALID_ARGUMENT, ER_INTERFACE_NO_AVAILABLE_INFORMATION, ER_SET_AND_RETURN, parser_node::expected_domain, i, ci_parater_meta_s::is_out_param, ci_parater_meta_s::marker, NO_ERROR, NULL, ci_parater_meta_s::param_count, tp_domain::precision, pt_node_next(), pt_type_enum_to_db(), tp_domain::scale, and parser_node::type_enum.
Referenced by ci_pmeta_get_info_impl().
static int res_delete_row_internal (BH_INTERFACE * bh_interface, CI_RESULTSET_STRUCTURE * prs) static
Definition at line 2024 of file db_stub.c.
References assert, cursor_get_current_oid(), db_select_result::cursor_id, db_value::data, DB_TYPE_OBJECT, db_value::domain, er_errid(), ER_INTERFACE_GENERIC, ER_SET_AND_RETURN, db_domain_info::general_info, db_domain_info::general_info::is_null, NO_ERROR, obj_delete(), db_data::op, db_query_result::res, ci_resultset_s::result, db_query_result::s, and db_domain_info::general_info::type.
Referenced by api_rs_delete_row().
static int res_fetch_internal (BH_INTERFACE * bh_interface, CI_RESULTSET_STRUCTURE * prs, int offset, CI_FETCH_POSITION pos) static
Definition at line 1992 of file db_stub.c.
References assert, DB_CURSOR_END, DB_CURSOR_SUCCESS, db_query_seek_tuple(), er_errid(), ER_INTERFACE_END_OF_CURSOR, NO_ERROR, and ci_resultset_s::result.
Referenced by api_rs_fetch().
static void rs_destroyf (BH_BIND * ptr) static
Definition at line 332 of file db_stub.c.
References assert, ci_conn_option_s::autocommit, ci_resultset_s::bh_interface, bh_interface_s::bind_get_parent, bh_interface_s::bind_to_handle, CI_STMT_STATUS_PREPARED, conn_end_tran(), db_query_end(), value_bind_table_ifs_s::destroy, bh_interface_s::destroy_handle, db_session::dimension, HANDLE_TYPE_RESULTSET, i, value_bind_table_s::ifs, ci_conn_s::need_defered_commit, NO_ERROR, NULL, ci_conn_s::opt, ci_stmt_s::pconn, ci_resultset_s::result, stmt_result_info_s::rs, ci_stmt_s::rs_info, stmt_result_info_s::rsmeta, ci_stmt_s::session, ci_resultset_s::stmt_idx, ci_stmt_s::stmt_status, and ci_resultset_s::value_table.
Referenced by init_resultset_structure().
static int rs_get_db_value (void * impl, int index, DB_VALUE * val) static
Definition at line 2127 of file db_stub.c.
References assert, db_query_get_tuple_value(), and ci_resultset_s::result.
Referenced by create_resultset_value_table().
static int rs_get_index_by_name (void * impl, const char * name, int * ri) static
Definition at line 2083 of file db_stub.c.
References assert, db_query_type::attr_name, db_query_result::col_cnt, ER_QPROC_INVALID_COLNAME, ER_SET_AND_RETURN, i, db_query_type::next, NO_ERROR, NULL, db_query_result::query_type, and ci_resultset_s::result.
Referenced by create_resultset_value_table().
static int rs_init_domain (void * impl, int index, DB_VALUE * val) static
Definition at line 2229 of file db_stub.c.
References assert, db_query_result::col_cnt, DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_query_type::db_type, db_value_domain_init(), db_query_type::domain, ER_INTERFACE_GENERIC, ER_INTERFACE_INVALID_ARGUMENT, ER_SET_AND_RETURN, HANDLE_TYPE_RESULTSET, i, db_query_type::next, NULL, tp_domain::precision, ci_resultset_s::prsmeta, db_query_result::query_type, ci_resultset_meta_s::query_type, ci_resultset_s::result, and tp_domain::scale.
Referenced by create_resultset_value_table().
static void rs_meta_destroyf (BH_BIND * ptr) static
Definition at line 413 of file db_stub.c.
References assert, and HANDLE_TYPE_RMETA.
Referenced by init_rmeta_structure().
static int rs_set_db_value (void * impl, int index, DB_VALUE * val) static
Definition at line 2149 of file db_stub.c.
References assert, db_query_type::attr_name, CHECK_PARTITION_NONE, db_query_result::col_cnt, cursor_get_current_oid(), db_select_result::cursor_id, db_value::data, db_get_class(), DB_TYPE_OBJECT, do_check_partitioned_class(), db_value::domain, er_errid(), ER_INTERFACE_GENERIC, ER_INTERFACE_INVALID_ARGUMENT, ER_INTERFACE_NO_AVAILABLE_INFORMATION, ER_SET_AND_RETURN, db_domain_info::general_info, HANDLE_TYPE_RESULTSET, i, db_domain_info::general_info::is_null, db_query_type::next, NO_ERROR, NULL, obj_set(), db_data::op, ci_resultset_s::prsmeta, db_query_result::query_type, ci_resultset_meta_s::query_type, db_query_result::res, ci_resultset_s::result, db_query_result::s, and db_domain_info::general_info::type.
Referenced by create_resultset_value_table().
static int stmt_add_batch_param (CI_STMT_STRUCTURE * pstmt, DB_VALUE * val, int num_val) static
Definition at line 2406 of file db_stub.c.
References ci_stmt_s::batch_data, ci_batch_data::data, ER_INTERFACE_NO_MORE_MEMORY, ER_SET_AND_RETURN, i, ci_batch_data::next, NO_ERROR, NULL, ci_stmt_s::param_val, pr_clone_value(), and ci_batch_data::_data::val.
Referenced by ci_stmt_add_batch_impl().
static int stmt_add_batch_string (CI_STMT_STRUCTURE * pstmt, const char * sql, size_t len) static
Definition at line 3459 of file db_stub.c.
References assert, ci_stmt_s::batch_data, ci_batch_data::data, ER_INTERFACE_NO_MORE_MEMORY, ER_SET_AND_RETURN, ci_batch_data::next, NO_ERROR, NULL, ci_batch_data::query_length, and ci_batch_data::_data::query_string.
Referenced by ci_stmt_add_batch_query_impl().
static int stmt_batch_alloc_and_bind_new_result (BH_INTERFACE * bh_interface, CI_STMT_STRUCTURE * pstmt, CI_BATCH_RESULT_STRUCTURE ** out_pbrs, CI_BATCH_RESULT * outhbr) static
Definition at line 2981 of file db_stub.c.
References bh_interface_s::alloc_handle, ci_stmt_s::batch_count, bh_interface_s::bind_graft, ER_INTERFACE_NO_MORE_MEMORY, ER_SET_AND_RETURN, init_batch_rs_structure(), NO_ERROR, NULL, ci_batch_result_s::rs_count, and ci_batch_result_s::rs_info.
Referenced by stmt_exec_batch_query_internal(), and stmt_exec_prepared_batch_internal().
static int stmt_batch_result_free (BH_INTERFACE * bh_interface, CI_STMT_STRUCTURE * pstmt) static
Definition at line 2934 of file db_stub.c.
References bh_interface_s::bind_get_first_child, bh_interface_s::bind_get_next_sibling, bh_interface_s::bind_to_handle, bh_interface_s::destroy_handle, ER_SET_AND_RETURN, HANDLE_TYPE_BATCH_RESULT, NO_ERROR, and NULL.
Referenced by stmt_exec_batch_query_internal(), and stmt_exec_prepared_batch_internal().
static int stmt_bind_pmeta_handle (BH_INTERFACE * bh_interface, CI_STMT_STRUCTURE * pstmt, CI_PARAM_META_STRUCTURE ** outmeta) static
Definition at line 2865 of file db_stub.c.
References bh_interface_s::alloc_handle, assert, ci_parater_meta_s::bh_interface, bh_interface_s::bind_graft, db_get_input_markers(), er_errid(), ER_INTERFACE_NO_MORE_MEMORY, ER_SET_AND_RETURN, parser_context::host_var_count, init_pmeta_structure(), ci_parater_meta_s::is_out_param, ci_parater_meta_s::marker, NO_ERROR, NULL, ci_parater_meta_s::param_count, db_session::parser, and ci_stmt_s::session.
Referenced by ci_stmt_get_parameter_metadata_impl(), and ci_stmt_register_out_parameter_impl().
static int stmt_bind_resultset_meta_handle (BH_INTERFACE * bh_interface, CI_STMT_STRUCTURE * pstmt, int stmt_idx, CI_RESULTSET_META_STRUCTURE ** outmeta) static
Definition at line 1934 of file db_stub.c.
References bh_interface_s::alloc_handle, ci_resultset_meta_s::bh_interface, bh_interface_s::bind_graft, ci_resultset_meta_s::col_count, db_get_query_type_list(), bh_interface_s::destroy_handle, ER_INTERFACE_NO_MORE_MEMORY, ER_SET_AND_RETURN, get_col_count(), init_rmeta_structure(), NO_ERROR, NULL, ci_resultset_s::prsmeta, db_query_result::query_type, ci_resultset_meta_s::query_type, ci_resultset_s::result, stmt_result_info_s::rs, ci_stmt_s::rs_info, stmt_result_info_s::rsmeta, ci_stmt_s::session, and ci_resultset_meta_s::stmt_idx.
Referenced by api_rs_get_resultset_metadata(), and stmt_get_resultset_metadata_internal().
static void stmt_destroyf (BH_BIND * ptr) static
Definition at line 252 of file db_stub.c.
References assert, ci_stmt_s::batch_count, ci_stmt_s::batch_data, CI_STMT_STATUS_PREPARED, ci_batch_data::data, db_close_session_local(), HANDLE_TYPE_STATEMENT, parser_context::host_var_count, i, ci_batch_data::next, NULL, ci_stmt_s::param_val, db_session::parser, pr_clear_value(), ci_batch_data::_data::query_string, ci_stmt_s::rs_info, ci_stmt_s::session, stmt_remove_error_info(), ci_stmt_s::stmt_status, and ci_batch_data::_data::val.
Referenced by init_stmt_structure().
static int stmt_exec_batch_query_internal (BH_INTERFACE * bh_interface, CI_STMT_STRUCTURE * pstmt, CI_BATCH_RESULT * br) static
Definition at line 2531 of file db_stub.c.
References rs_meta_info::affected_row, api_get_errid, api_get_errmsg, ci_stmt_s::batch_count, ci_stmt_s::batch_data, ci_batch_data::data, db_close_session_local(), db_compile_statement_local(), db_execute_statement_local(), db_get_next_error(), DB_NO_OIDS, db_query_end(), db_session::dimension, ER_INTERFACE_NO_MORE_MEMORY, ER_SET_AND_RETURN, err, ci_batch_result_info_s::err_code, ci_batch_result_info_s::err_msg, i, db_session::include_oid, ci_batch_result_info_s::metainfo, ci_batch_data::next, NO_ERROR, NULL, db_session::parser, parser_create_parser(), pt_get_errors(), ci_batch_data::query_length, ci_batch_data::_data::query_string, ci_batch_result_s::rs_info, ci_stmt_s::session, db_session::statements, stmt_batch_alloc_and_bind_new_result(), stmt_batch_result_free(), and strdup().
Referenced by ci_stmt_execute_batch_impl().
static int stmt_exec_immediate_internal (BH_INTERFACE * bh_interface, CI_STMT_STRUCTURE * pstmt, char * sql, size_t len, CI_RESULTSET * rs, int * r) static
Definition at line 1355 of file db_stub.c.
References assert, ci_conn_option_s::autocommit, ci_stmt_s::current_rs_idx, db_session::dimension, ER_INTERFACE_NO_MORE_MEMORY, ER_SET_AND_RETURN, rs_meta_info::has_result, i, ci_stmt_option_s::lazy_exec, stmt_result_info_s::metainfo, ci_conn_s::need_defered_commit, ci_conn_s::need_immediate_commit, NO_ERROR, NULL, ci_conn_s::opt, ci_stmt_s::opt, ci_stmt_s::pconn, ci_stmt_s::rs_info, ci_stmt_s::session, stmt_exec_one_statement(), and stmt_reset_session_and_parse().
Referenced by ci_stmt_execute_immediate_impl().
static int stmt_exec_internal (BH_INTERFACE * bh_interface, CI_STMT_STRUCTURE * pstmt, CI_RESULTSET * rs, int * r) static
Definition at line 1723 of file db_stub.c.
References rs_meta_info::affected_row, bh_interface_s::alloc_handle, assert, ci_resultset_s::bh_interface, bh_interface_s::bind_get_first_child, bh_interface_s::bind_get_next_sibling, bh_interface_s::bind_graft, bh_interface_s::bind_to_handle, db_query_result::col_cnt, create_resultset_value_table(), ci_stmt_s::current_rs_idx, db_execute_and_keep_statement(), db_push_values(), bh_interface_s::destroy_handle, db_session::dimension, ER_INTERFACE_NO_MORE_MEMORY, ER_SET_AND_RETURN, ER_UCI_TOO_FEW_HOST_VARS, ci_stmt_option_s::exec_continue_on_error, HANDLE_TYPE_RMETA, rs_meta_info::has_result, parser_context::host_var_count, i, init_resultset_structure(), stmt_result_info_s::metainfo, ci_conn_s::need_defered_commit, ci_conn_s::need_immediate_commit, NO_ERROR, NULL, ci_stmt_s::opt, ci_stmt_s::param_val, ci_stmt_s::param_value_is_set, db_session::parser, ci_stmt_s::pconn, ci_resultset_s::prsmeta, ci_resultset_s::result, stmt_result_info_s::rs, ci_stmt_s::rs_info, ci_stmt_s::session, ci_resultset_s::stmt_idx, ci_resultset_meta_s::stmt_idx, stmt_make_error_info(), stmt_remove_error_info(), and ci_resultset_s::value_table.
Referenced by ci_stmt_execute_impl().
static int stmt_exec_one_statement (BH_INTERFACE * bh_interface, int stmt_idx, CI_STMT_STRUCTURE * pstmt, CI_RESULTSET * rs, int * r) static
Definition at line 1220 of file db_stub.c.
References rs_meta_info::affected_row, bh_interface_s::alloc_handle, ci_resultset_s::bh_interface, bh_interface_s::bind_graft, bh_interface_s::bind_to_handle, db_query_result::col_cnt, create_resultset_value_table(), db_compile_statement_local(), db_execute_and_keep_statement(), db_get_statement_type(), bh_interface_s::destroy_handle, ER_INTERFACE_NO_MORE_MEMORY, ER_IT_EMPTY_STATEMENT, ER_SET_AND_RETURN, ci_stmt_option_s::exec_continue_on_error, HAS_RESULT, rs_meta_info::has_result, init_resultset_structure(), stmt_result_info_s::metainfo, ci_conn_s::need_defered_commit, ci_conn_s::need_immediate_commit, NO_ERROR, NULL, ci_stmt_s::opt, ci_stmt_s::pconn, ci_resultset_s::result, stmt_result_info_s::rs, ci_stmt_s::rs_info, ci_stmt_s::session, rs_meta_info::sql_type, ci_resultset_s::stmt_idx, stmt_make_error_info(), stmt_remove_error_info(), and ci_resultset_s::value_table.
Referenced by ci_stmt_next_result_impl(), and stmt_exec_immediate_internal().
static int stmt_exec_prepared_batch_internal (BH_INTERFACE * bh_interface, CI_STMT_STRUCTURE * pstmt, CI_BATCH_RESULT * br) static
Definition at line 2459 of file db_stub.c.
References rs_meta_info::affected_row, api_get_errmsg, ci_stmt_s::batch_count, ci_stmt_s::batch_data, ci_batch_data::data, db_execute_and_keep_statement(), db_get_statement_type(), db_push_values(), db_query_end(), ci_batch_result_info_s::err_code, ci_batch_result_info_s::err_msg, HAS_RESULT, parser_context::host_var_count, i, ci_batch_result_info_s::metainfo, ci_batch_data::next, NO_ERROR, NULL, db_session::parser, ci_batch_data::_data::query_string, ci_batch_result_s::rs_info, ci_stmt_s::session, stmt_batch_alloc_and_bind_new_result(), stmt_batch_result_free(), strdup(), and ci_batch_data::_data::val.
Referenced by ci_stmt_execute_batch_impl().
static int stmt_get_parameter_internal (BH_INTERFACE * bh_interface, CI_STMT_STRUCTURE * pstmt, int index, CI_TYPE type, void * addr, size_t len, size_t * outlen, bool * isnull) static
Definition at line 1533 of file db_stub.c.
References CI_STMT_STATUS_EXECUTED, CI_STMT_STATUS_PREPARED, coerce_db_value_to_value(), ER_INTERFACE_INVALID_ARGUMENT, ER_INTERFACE_NOT_PREPARED, ER_INTERFACE_PARAM_IS_NOT_SET, ER_SET_AND_RETURN, parser_context::host_var_count, parser_context::host_variables, NULL, ci_stmt_s::param_val, ci_stmt_s::param_value_is_set, db_session::parser, ci_stmt_s::session, and ci_stmt_s::stmt_status.
Referenced by ci_stmt_get_parameter_impl().
static int stmt_get_resultset_metadata_internal (BH_INTERFACE * bh_interface, CI_STMT_STRUCTURE * pstmt, CI_RESULTSET_METADATA * r) static
Definition at line 1864 of file db_stub.c.
References assert, bh_interface_s::bind_to_handle, ci_stmt_s::current_rs_idx, ER_INTERFACE_HAS_NO_RESULT_SET, ER_SET_AND_RETURN, rs_meta_info::has_result, stmt_result_info_s::metainfo, NO_ERROR, NULL, ci_stmt_s::rs_info, stmt_result_info_s::rsmeta, and stmt_bind_resultset_meta_handle().
Referenced by ci_stmt_get_resultset_metadata_impl().
static int stmt_make_error_info (CI_STMT_STRUCTURE * pstmt, int statement_id) static
Definition at line 124 of file db_stub.c.
References api_get_errmsg, ci_stmt_error_info_s::column, db_get_errors(), db_get_next_error(), ci_stmt_error_info_s::err_code, ci_stmt_s::err_info, err_info, ci_stmt_error_info_s::err_msg, ci_stmt_error_info_s::line, ci_stmt_error_info_s::next, NO_ERROR, NULL, ci_stmt_s::session, and strdup().
Referenced by stmt_exec_internal(), stmt_exec_one_statement(), stmt_prepare_internal(), and stmt_reset_session_and_parse().
static int stmt_prepare_internal (BH_INTERFACE * bh_interface, CI_STMT_STRUCTURE * pstmt, const char * sql, size_t len) static
Definition at line 1437 of file db_stub.c.
References assert, ci_stmt_s::current_rs_idx, db_compile_statement_local(), db_get_statement_type(), db_session::dimension, ER_INTERFACE_NO_MORE_MEMORY, ER_SET_AND_RETURN, HAS_RESULT, rs_meta_info::has_result, parser_context::host_var_count, i, stmt_result_info_s::metainfo, NO_ERROR, NULL, ci_stmt_s::param_val, ci_stmt_s::param_value_is_set, db_session::parser, pr_clear_value(), ci_stmt_s::rs_info, ci_stmt_s::session, rs_meta_info::sql_type, stmt_make_error_info(), stmt_remove_error_info(), and stmt_reset_session_and_parse().
Referenced by ci_stmt_prepare_impl().
static int stmt_release_children (BH_INTERFACE * bh_interface, CI_STMT_STRUCTURE * pstmt, bool resultset_only) static
Definition at line 2785 of file db_stub.c.
References assert, bh_interface_s::bind_get_first_child, bh_interface_s::bind_get_next_sibling, bh_interface_s::bind_to_handle, bh_interface_s::destroy_handle, ER_SET_AND_RETURN, HANDLE_TYPE_RESULTSET, HANDLE_TYPE_RMETA, NO_ERROR, and NULL.
Referenced by ci_stmt_execute_immediate_impl(), ci_stmt_execute_impl(), ci_stmt_prepare_impl(), and conn_end_tran().
static int stmt_remove_error_info (CI_STMT_STRUCTURE * pstmt) static
Definition at line 200 of file db_stub.c.
References ci_stmt_s::err_info, err_info, ci_stmt_error_info_s::err_msg, ci_stmt_error_info_s::next, NO_ERROR, and NULL.
Referenced by stmt_destroyf(), stmt_exec_internal(), stmt_exec_one_statement(), and stmt_prepare_internal().
static int stmt_reset_session_and_parse (CI_STMT_STRUCTURE * pstmt, const char * sql, size_t len) static
Definition at line 1615 of file db_stub.c.
References api_get_errid, api_get_errmsg, ci_err_set(), ci_stmt_error_info_s::column, db_close_session_local(), DB_NO_OIDS, DB_ROW_OIDS, db_session::dimension, ER_INTERFACE_NO_MORE_MEMORY, ER_IT_EMPTY_STATEMENT, ER_SET_AND_RETURN, ci_stmt_error_info_s::err_code, ci_stmt_s::err_info, err_info, ci_stmt_error_info_s::err_msg, db_session::include_oid, ci_stmt_error_info_s::line, ci_stmt_error_info_s::next, NO_ERROR, NULL, ci_stmt_s::opt, db_session::parser, parser_create_parser(), pt_get_errors(), ci_stmt_s::session, db_session::statements, stmt_make_error_info(), strdup(), and ci_stmt_option_s::updatable_result.
Referenced by stmt_exec_immediate_internal(), and stmt_prepare_internal().
static int stmt_set_parameter_internal (BH_INTERFACE * bh_interface, CI_STMT_STRUCTURE * pstmt, int index, CI_TYPE type, void * val, size_t size) static
Definition at line 1582 of file db_stub.c.
References coerce_value_to_db_value(), ER_INTERFACE_INVALID_ARGUMENT, ER_SET_AND_RETURN, parser_context::host_var_count, i, NO_ERROR, ci_stmt_s::param_val, ci_stmt_s::param_value_is_set, db_session::parser, and ci_stmt_s::session.
Referenced by ci_stmt_register_out_parameter_impl(), and ci_stmt_set_parameter_impl().
Variable Documentation
CUBRID_API_FUNCTION_TABLE Cubrid_api_function_table
Definition at line 4559 of file db_stub.c.
API_RESULTSET_META_IFS RMETA_IFS_ static
Initial value:
= {
  api_rmeta_get_count,
  api_rmeta_get_info
}
Definition at line 176 of file db_stub.c.
Referenced by get_query_rmeta_ifs().
API_RESULTSET_IFS RS_IFS_ static
Initial value:
= {
  api_rs_get_resultset_metadata,
  api_rs_fetch,
  api_rs_fetch_tell,
  api_rs_clear_updates,
  api_rs_delete_row,
  api_rs_get_value,
  api_rs_get_value_by_name,
  api_rs_update_value,
  api_rs_apply_row,
  api_rs_destroy
}
Definition at line 181 of file db_stub.c.
Referenced by get_query_rs_ifs().