CUBRID Engine: src/compat/dbi.h File Reference
dbi.h File Reference
#include <stdio.h>
#include <time.h>
#include "dbtran_def.h"
#include "dbtype_def.h"
#include "db_date.h"
#include "db_elo.h"
#include "db_query.h"
#include "databases_file.h"
#include "error_code.h"
Macros
#define db_utime_to_string db_timestamp_to_string
#define db_string_to_utime db_string_to_timestamp
Typedefs
typedef void(* db_error_log_handler_t) (unsigned int)
Enumerations
enum { DB_NO_OIDS, DB_ROW_OIDS, DB_COLUMN_OIDS }
Functions
void db_objlist_free (DB_OBJLIST *list)
void db_string_free (char *string)
int db_auth_login (char *signed_data, int len)
int db_auth_logout (void)
int db_login (const char *name, const char *password)
int db_restart (const char *program, int print_version, const char *volume)
int db_restart_ex (const char *program, const char *db_name, const char *db_user, const char *db_password, const char *preferred_hosts, int client_type)
void db_set_server_session_key (const char *key)
char * db_get_server_session_key (void)
SESSION_ID db_get_session_id (void)
void db_set_session_id (const SESSION_ID session_id)
int db_end_session (void)
int db_find_or_create_session (const char *db_user, const char *program_name)
int db_get_row_count_cache (void)
void db_update_row_count_cache (const int row_count)
int db_get_row_count (int *row_count)
int db_get_last_insert_id (DB_VALUE *value)
int db_get_variable (DB_VALUE *name, DB_VALUE *value)
int db_shutdown (void)
int db_ping_server (int client_val, int *server_val)
int db_disable_modification (void)
int db_enable_modification (void)
int db_commit_transaction (void)
int db_abort_transaction (void)
int db_reset_latest_query_status (void)
int db_commit_is_needed (void)
int db_savepoint_transaction (const char *savepoint_name)
int db_abort_to_savepoint (const char *savepoint_name)
int db_set_global_transaction_info (int gtrid, void *info, int size)
int db_get_global_transaction_info (int gtrid, void *buffer, int size)
int db_2pc_start_transaction (void)
int db_2pc_prepare_transaction (void)
int db_2pc_prepared_transactions (int gtrids[], int size)
int db_2pc_prepare_to_commit_transaction (int gtrid)
int db_2pc_attach_transaction (int gtrid)
void db_set_interrupt (int set)
int db_set_suppress_repl_on_transaction (int set)
int db_checkpoint (void)
int db_freepgs (const char *vlabel)
int db_totalpgs (const char *vlabel)
char * db_vol_label (int volid, char *vol_fullname)
void db_warnspace (const char *vlabel)
int db_add_volume (const char *ext_path, const char *ext_name, const char *ext_comments, const int ext_npages, const DB_VOLPURPOSE ext_purpose)
int db_add_volume_ex (DBDEF_VOL_EXT_INFO *ext_info)
int db_num_volumes (void)
int db_last_volume (void)
void db_print_stats (void)
void db_preload_classes (const char *name1,...)
void db_link_static_methods (DB_METHOD_LINK *methods)
void db_unlink_static_methods (DB_METHOD_LINK *methods)
void db_flush_static_methods (void)
const char * db_error_string (int level)
int db_error_code (void)
int db_error_init (const char *logfile)
db_error_log_handler_t db_register_error_log_handler (db_error_log_handler_t f)
int db_set_lock_timeout (int seconds)
int db_set_isolation (DB_TRAN_ISOLATION isolation)
void db_synchronize_cache (void)
void db_get_tran_settings (int *lock_wait, DB_TRAN_ISOLATION *tran_isolation)
DB_OBJECT * db_get_user (void)
DB_OBJECT * db_get_owner (DB_OBJECT *classobj)
char * db_get_user_name (void)
char * db_get_user_and_host_name (void)
DB_OBJECT * db_find_user (const char *name)
int db_find_user_to_drop (const char *name, DB_OBJECT **user)
DB_OBJECT * db_add_user (const char *name, int *exists)
int db_drop_user (DB_OBJECT *user)
int db_add_member (DB_OBJECT *user, DB_OBJECT *member)
int db_drop_member (DB_OBJECT *user, DB_OBJECT *member)
int db_set_password (DB_OBJECT *user, const char *oldpass, const char *newpass)
int db_set_user_comment (DB_OBJECT *user, const char *comment)
int db_grant (DB_OBJECT *user, DB_OBJECT *classobj, DB_AUTH auth, int grant_option)
int db_revoke (DB_OBJECT *user, DB_OBJECT *classobj, DB_AUTH auth)
int db_check_authorization (DB_OBJECT *op, DB_AUTH auth)
int db_check_authorization_and_grant_option (MOP op, DB_AUTH auth)
int db_get_class_privilege (DB_OBJECT *op, unsigned int *auth)
int db_get_serial_current_value (const char *serial_name, DB_VALUE *serial_value)
int db_get_serial_next_value (const char *serial_name, DB_VALUE *serial_value)
int db_get_serial_next_value_ex (const char *serial_name, DB_VALUE *serial_value, int num_alloc)
DB_OBJECT * db_create (DB_OBJECT *obj)
DB_OBJECT * db_create_by_name (const char *name)
int db_get (DB_OBJECT *object, const char *attpath, DB_VALUE *value)
int db_put (DB_OBJECT *obj, const char *name, DB_VALUE *value)
int db_drop (DB_OBJECT *obj)
int db_get_expression (DB_OBJECT *object, const char *expression, DB_VALUE *value)
void db_print (DB_OBJECT *obj)
void db_fprint (FILE *fp, DB_OBJECT *obj)
DB_OBJECT * db_find_unique (DB_OBJECT *classobj, const char *attname, DB_VALUE *value)
DB_OBJECT * db_find_unique_write_mode (DB_OBJECT *classobj, const char *attname, DB_VALUE *value)
DB_OBJECT * db_find_multi_unique (DB_OBJECT *classobj, int size, char *attnames[], DB_VALUE *values[], DB_FETCH_MODE purpose)
DB_OBJECT * db_dfind_unique (DB_OBJECT *classobj, DB_ATTDESC *attdesc, DB_VALUE *value, DB_FETCH_MODE purpose)
DB_OBJECT * db_dfind_multi_unique (DB_OBJECT *classobj, int size, DB_ATTDESC *attdesc[], DB_VALUE *values[], DB_FETCH_MODE purpose)
DB_OBJECT * db_find_primary_key (MOP classmop, const DB_VALUE **values, int size, DB_FETCH_MODE purpose)
int db_send (DB_OBJECT *obj, const char *name, DB_VALUE *returnval,...)
int db_send_arglist (DB_OBJECT *obj, const char *name, DB_VALUE *returnval, DB_VALUE_LIST *args)
int db_send_argarray (DB_OBJECT *obj, const char *name, DB_VALUE *returnval, DB_VALUE **args)
int db_lock_read (DB_OBJECT *op)
int db_lock_write (DB_OBJECT *op)
int db_fetch_array (DB_OBJECT **objects, DB_FETCH_MODE mode, int quit_on_error)
int db_fetch_list (DB_OBJLIST *objects, DB_FETCH_MODE mode, int quit_on_error)
int db_fetch_set (DB_COLLECTION *set, DB_FETCH_MODE mode, int quit_on_error)
int db_fetch_seq (DB_SEQ *set, DB_FETCH_MODE mode, int quit_on_error)
int db_fetch_composition (DB_OBJECT *object, DB_FETCH_MODE mode, int max_level, int quit_on_error)
DB_OBJECT * db_create_class (const char *name)
DB_OBJECT * db_create_vclass (const char *name)
int db_drop_class (DB_OBJECT *classobj)
int db_drop_class_ex (DB_OBJECT *classobj, bool is_cascade_constraints)
int db_rename_class (DB_OBJECT *classobj, const char *new_name)
int db_truncate_class (DB_OBJECT *classobj)
int db_add_index (DB_OBJECT *classobj, const char *attname)
int db_drop_index (DB_OBJECT *classobj, const char *attname)
int db_add_super (DB_OBJECT *classobj, DB_OBJECT *super)
int db_drop_super (DB_OBJECT *classobj, DB_OBJECT *super)
int db_drop_super_connect (DB_OBJECT *classobj, DB_OBJECT *super)
int db_rename (DB_OBJECT *classobj, const char *name, int class_namespace, const char *newname)
int db_add_attribute (DB_OBJECT *obj, const char *name, const char *domain, DB_VALUE *default_value)
int db_add_shared_attribute (DB_OBJECT *obj, const char *name, const char *domain, DB_VALUE *default_value)
int db_add_class_attribute (DB_OBJECT *obj, const char *name, const char *domain, DB_VALUE *default_value)
int db_add_set_attribute_domain (DB_OBJECT *classobj, const char *name, int class_attribute, const char *domain)
int db_drop_attribute (DB_OBJECT *classobj, const char *name)
int db_drop_class_attribute (DB_OBJECT *classobj, const char *name)
int db_change_default (DB_OBJECT *classobj, const char *name, DB_VALUE *value)
int db_constrain_non_null (DB_OBJECT *classobj, const char *name, int class_attribute, int on_or_off)
int db_constrain_unique (DB_OBJECT *classobj, const char *name, int on_or_off)
int db_add_method (DB_OBJECT *classobj, const char *name, const char *implementation)
int db_add_class_method (DB_OBJECT *classobj, const char *name, const char *implementation)
int db_drop_method (DB_OBJECT *classobj, const char *name)
int db_drop_class_method (DB_OBJECT *classobj, const char *name)
int db_add_argument (DB_OBJECT *classobj, const char *name, int class_method, int arg_index, const char *domain)
int db_add_set_argument_domain (DB_OBJECT *classobj, const char *name, int class_method, int arg_index, const char *domain)
int db_change_method_implementation (DB_OBJECT *classobj, const char *name, int class_method, const char *newname)
int db_set_loader_commands (DB_OBJECT *classobj, const char *commands)
int db_add_method_file (DB_OBJECT *classobj, const char *name)
int db_drop_method_file (DB_OBJECT *classobj, const char *name)
int db_drop_method_files (DB_OBJECT *classobj)
int db_add_resolution (DB_OBJECT *classobj, DB_OBJECT *super, const char *name, const char *alias)
int db_add_class_resolution (DB_OBJECT *classobj, DB_OBJECT *super, const char *name, const char *alias)
int db_drop_resolution (DB_OBJECT *classobj, DB_OBJECT *super, const char *name)
int db_drop_class_resolution (DB_OBJECT *classobj, DB_OBJECT *super, const char *name)
int db_add_constraint (MOP classmop, DB_CONSTRAINT_TYPE constraint_type, const char *constraint_name, const char **att_names, int class_attributes)
int db_drop_constraint (MOP classmop, DB_CONSTRAINT_TYPE constraint_type, const char *constraint_name, const char **att_names, int class_attributes)
char * db_get_database_name (void)
const char * db_get_database_comments (void)
void db_set_client_type (int client_type)
void db_set_preferred_hosts (const char *hosts)
void db_set_connect_order (int connect_order)
int db_get_client_type (void)
const char * db_get_type_name (DB_TYPE type_id)
DB_TYPE db_type_from_string (const char *name)
int db_get_schema_def_dbval (DB_VALUE *result, DB_VALUE *name_val)
void db_clear_host_status (void)
void db_set_host_status (char *hostname, int status)
void db_set_connected_host_status (char *host_connected)
bool db_need_reconnect (void)
bool db_need_ignore_repl_delay (void)
bool db_does_connected_host_have_status (int status)
int db_get_host_list_with_given_status (char **hostlist, int list_size, int status)
int db_get_delayed_hosts_count (void)
void db_clear_delayed_hosts_count (void)
void db_set_max_num_delayed_hosts_lookup (int max_num_delayed_hosts_lookup)
int db_get_max_num_delayed_hosts_lookup (void)
bool db_enable_trigger (void)
bool db_disable_trigger (void)
DB_OBJECT * db_find_class_of_index (const char *const index, const DB_CONSTRAINT_TYPE type)
DB_OBJECT * db_find_class (const char *name)
DB_OBJECT * db_find_class_with_purpose (const char *name, bool for_update)
DB_OBJECT * db_get_class (DB_OBJECT *obj)
DB_OBJLIST * db_get_all_objects (DB_OBJECT *classobj)
DB_OBJLIST * db_get_all_classes (void)
DB_OBJLIST * db_get_base_classes (void)
DB_OBJLIST * db_fetch_all_objects (DB_OBJECT *op, DB_FETCH_MODE mode)
DB_OBJLIST * db_fetch_all_classes (DB_FETCH_MODE mode)
DB_OBJLIST * db_fetch_base_classes (DB_FETCH_MODE mode)
int db_is_class (DB_OBJECT *obj)
int db_is_any_class (DB_OBJECT *obj)
int db_is_instance (DB_OBJECT *obj)
int db_is_instance_of (DB_OBJECT *obj, DB_OBJECT *classobj)
int db_is_subclass (DB_OBJECT *classobj, DB_OBJECT *supermop)
int db_is_superclass (DB_OBJECT *supermop, DB_OBJECT *classobj)
int db_is_partition (DB_OBJECT *classobj, DB_OBJECT *superobj)
int db_is_system_class (DB_OBJECT *op)
int db_is_deleted (DB_OBJECT *obj)
int db_class_has_instance (DB_OBJECT *classobj)
const char * db_get_class_name (DB_OBJECT *classobj)
DB_OBJLIST * db_get_superclasses (DB_OBJECT *obj)
DB_OBJLIST * db_get_subclasses (DB_OBJECT *obj)
DB_ATTRIBUTE * db_get_attribute (DB_OBJECT *obj, const char *name)
DB_ATTRIBUTE * db_get_attribute_by_name (const char *class_name, const char *attribute_name)
DB_ATTRIBUTE * db_get_attributes (DB_OBJECT *obj)
DB_ATTRIBUTE * db_get_class_attribute (DB_OBJECT *obj, const char *name)
DB_ATTRIBUTE * db_get_class_attributes (DB_OBJECT *obj)
DB_METHOD * db_get_method (DB_OBJECT *obj, const char *name)
DB_METHOD * db_get_class_method (DB_OBJECT *obj, const char *name)
DB_METHOD * db_get_methods (DB_OBJECT *obj)
DB_METHOD * db_get_class_methods (DB_OBJECT *obj)
DB_RESOLUTION * db_get_resolutions (DB_OBJECT *obj)
DB_RESOLUTION * db_get_class_resolutions (DB_OBJECT *obj)
DB_METHFILE * db_get_method_files (DB_OBJECT *obj)
const char * db_get_loader_commands (DB_OBJECT *obj)
DB_TYPE db_attribute_type (DB_ATTRIBUTE *attribute)
DB_ATTRIBUTE * db_attribute_next (DB_ATTRIBUTE *attribute)
const char * db_attribute_name (DB_ATTRIBUTE *attribute)
const char * db_attribute_comment (DB_ATTRIBUTE *attribute)
int db_attribute_id (DB_ATTRIBUTE *attribute)
int db_attribute_order (DB_ATTRIBUTE *attribute)
DB_DOMAIN * db_attribute_domain (DB_ATTRIBUTE *attribute)
DB_OBJECT * db_attribute_class (DB_ATTRIBUTE *attribute)
DB_VALUE * db_attribute_default (DB_ATTRIBUTE *attribute)
int db_attribute_is_unique (DB_ATTRIBUTE *attribute)
int db_attribute_is_primary_key (DB_ATTRIBUTE *attribute)
int db_attribute_is_foreign_key (DB_ATTRIBUTE *attribute)
int db_attribute_is_auto_increment (DB_ATTRIBUTE *attribute)
int db_attribute_is_reverse_unique (DB_ATTRIBUTE *attribute)
int db_attribute_is_non_null (DB_ATTRIBUTE *attribute)
int db_attribute_is_indexed (DB_ATTRIBUTE *attribute)
int db_attribute_is_reverse_indexed (DB_ATTRIBUTE *attribute)
int db_attribute_is_shared (DB_ATTRIBUTE *attribute)
int db_attribute_length (DB_ATTRIBUTE *attribute)
DB_DOMAIN * db_domain_next (const DB_DOMAIN *domain)
DB_TYPE db_domain_type (const DB_DOMAIN *domain)
DB_OBJECT * db_domain_class (const DB_DOMAIN *domain)
DB_DOMAIN * db_domain_set (const DB_DOMAIN *domain)
int db_domain_precision (const DB_DOMAIN *domain)
int db_domain_scale (const DB_DOMAIN *domain)
int db_domain_codeset (const DB_DOMAIN *domain)
int db_domain_collation_id (const DB_DOMAIN *domain)
const char * db_domain_raw_json_schema (const DB_DOMAIN *domain)
DB_METHOD * db_method_next (DB_METHOD *method)
const char * db_method_name (DB_METHOD *method)
const char * db_method_function (DB_METHOD *method)
DB_OBJECT * db_method_class (DB_METHOD *method)
DB_DOMAIN * db_method_return_domain (DB_METHOD *method)
DB_DOMAIN * db_method_arg_domain (DB_METHOD *method, int arg)
int db_method_arg_count (DB_METHOD *method)
DB_RESOLUTION * db_resolution_next (DB_RESOLUTION *resolution)
DB_OBJECT * db_resolution_class (DB_RESOLUTION *resolution)
const char * db_resolution_name (DB_RESOLUTION *resolution)
const char * db_resolution_alias (DB_RESOLUTION *resolution)
int db_resolution_isclass (DB_RESOLUTION *resolution)
DB_METHFILE * db_methfile_next (DB_METHFILE *methfile)
const char * db_methfile_name (DB_METHFILE *methfile)
DB_OBJLIST * db_objlist_next (DB_OBJLIST *link)
DB_OBJECT * db_objlist_object (DB_OBJLIST *link)
int db_get_class_num_objs_and_pages (DB_OBJECT *classmop, int approximation, int *nobjs, int *npages)
int db_get_btree_statistics (DB_CONSTRAINT *cons, int *num_leaf_pages, int *num_total_pages, int *num_keys, int *height)
DB_CONSTRAINT * db_get_constraints (DB_OBJECT *obj)
DB_CONSTRAINT * db_constraint_next (DB_CONSTRAINT *constraint)
DB_CONSTRAINT * db_constraint_find_primary_key (DB_CONSTRAINT *constraint)
DB_CONSTRAINT_TYPE db_constraint_type (const DB_CONSTRAINT *constraint)
const char * db_constraint_name (DB_CONSTRAINT *constraint)
DB_ATTRIBUTE ** db_constraint_attributes (DB_CONSTRAINT *constraint)
const int * db_constraint_asc_desc (DB_CONSTRAINT *constraint)
const int * db_constraint_prefix_length (DB_CONSTRAINT *constraint)
const char * db_get_foreign_key_action (DB_CONSTRAINT *constraint, DB_FK_ACTION_TYPE type)
DB_OBJECT * db_get_foreign_key_ref_class (DB_CONSTRAINT *constraint)
DB_OBJECT * db_create_trigger (const char *name, DB_TRIGGER_STATUS status, double priority, DB_TRIGGER_EVENT event, DB_OBJECT *class_obj, const char *attr, DB_TRIGGER_TIME cond_time, const char *cond_source, DB_TRIGGER_TIME action_time, DB_TRIGGER_ACTION action_type, const char *action_source)
int db_drop_trigger (DB_OBJECT *obj)
int db_rename_trigger (DB_OBJECT *obj, const char *newname)
DB_OBJECT * db_find_trigger (const char *name)
int db_find_all_triggers (DB_OBJLIST **list)
int db_find_event_triggers (DB_TRIGGER_EVENT event, DB_OBJECT *class_obj, const char *attr, DB_OBJLIST **list)
int db_alter_trigger_priority (DB_OBJECT *trobj, double priority)
int db_alter_trigger_status (DB_OBJECT *trobj, DB_TRIGGER_STATUS status)
int db_execute_deferred_activities (DB_OBJECT *trigger_obj, DB_OBJECT *target)
int db_drop_deferred_activities (DB_OBJECT *trigger_obj, DB_OBJECT *target)
int db_trigger_name (DB_OBJECT *trobj, char **name)
int db_trigger_status (DB_OBJECT *trobj, DB_TRIGGER_STATUS *status)
int db_trigger_priority (DB_OBJECT *trobj, double *priority)
int db_trigger_event (DB_OBJECT *trobj, DB_TRIGGER_EVENT *event)
int db_trigger_class (DB_OBJECT *trobj, DB_OBJECT **class_obj)
int db_trigger_attribute (DB_OBJECT *trobj, char **attr)
int db_trigger_condition (DB_OBJECT *trobj, char **condition)
int db_trigger_condition_time (DB_OBJECT *trobj, DB_TRIGGER_TIME *tr_time)
int db_trigger_action_type (DB_OBJECT *trobj, DB_TRIGGER_ACTION *type)
int db_trigger_action_time (DB_OBJECT *trobj, DB_TRIGGER_TIME *tr_time)
int db_trigger_action (DB_OBJECT *trobj, char **action)
int db_trigger_comment (DB_OBJECT *trobj, char **comment)
DB_CTMPL * dbt_create_class (const char *name)
DB_CTMPL * dbt_create_vclass (const char *name)
DB_CTMPL * dbt_edit_class (DB_OBJECT *classobj)
DB_CTMPL * dbt_copy_class (const char *new_name, const char *existing_name, SM_CLASS **class_)
DB_OBJECT * dbt_finish_class (DB_CTMPL *def)
void dbt_abort_class (DB_CTMPL *def)
int dbt_add_attribute (DB_CTMPL *def, const char *name, const char *domain, DB_VALUE *default_value)
int dbt_add_shared_attribute (DB_CTMPL *def, const char *name, const char *domain, DB_VALUE *default_value)
int dbt_add_class_attribute (DB_CTMPL *def, const char *name, const char *domain, DB_VALUE *default_value)
int dbt_constrain_non_null (DB_CTMPL *def, const char *name, int class_attribute, int on_or_off)
int dbt_constrain_unique (DB_CTMPL *def, const char *name, int on_or_off)
int dbt_add_constraint (DB_CTMPL *def, DB_CONSTRAINT_TYPE constraint_type, const char *constraint_name, const char **attnames, int class_attributes, const char *comment)
int dbt_drop_constraint (DB_CTMPL *def, DB_CONSTRAINT_TYPE constraint_type, const char *constraint_name, const char **attnames, int class_attributes)
int dbt_add_set_attribute_domain (DB_CTMPL *def, const char *name, int class_attribute, const char *domain)
int dbt_change_domain (DB_CTMPL *def, const char *name, int class_attribute, const char *domain)
int dbt_change_default (DB_CTMPL *def, const char *name, int class_attribute, DB_VALUE *value)
int dbt_drop_set_attribute_domain (DB_CTMPL *def, const char *name, int class_attribute, const char *domain)
int dbt_drop_attribute (DB_CTMPL *def, const char *name)
int dbt_drop_shared_attribute (DB_CTMPL *def, const char *name)
int dbt_drop_class_attribute (DB_CTMPL *def, const char *name)
int dbt_add_method (DB_CTMPL *def, const char *name, const char *implementation)
int dbt_add_class_method (DB_CTMPL *def, const char *name, const char *implementation)
int dbt_add_argument (DB_CTMPL *def, const char *name, int class_method, int arg_index, const char *domain)
int dbt_add_set_argument_domain (DB_CTMPL *def, const char *name, int class_method, int arg_index, const char *domain)
int dbt_change_method_implementation (DB_CTMPL *def, const char *name, int class_method, const char *newname)
int dbt_drop_method (DB_CTMPL *def, const char *name)
int dbt_drop_class_method (DB_CTMPL *def, const char *name)
int dbt_add_super (DB_CTMPL *def, DB_OBJECT *super)
int dbt_drop_super (DB_CTMPL *def, DB_OBJECT *super)
int dbt_drop_super_connect (DB_CTMPL *def, DB_OBJECT *super)
int dbt_rename (DB_CTMPL *def, const char *name, int class_namespace, const char *newname)
int dbt_add_method_file (DB_CTMPL *def, const char *name)
int dbt_drop_method_file (DB_CTMPL *def, const char *name)
int dbt_drop_method_files (DB_CTMPL *def)
int dbt_rename_method_file (DB_CTMPL *def, const char *new_name, const char *old_name)
int dbt_set_loader_commands (DB_CTMPL *def, const char *commands)
int dbt_add_resolution (DB_CTMPL *def, DB_OBJECT *super, const char *name, const char *alias)
int dbt_add_class_resolution (DB_CTMPL *def, DB_OBJECT *super, const char *name, const char *alias)
int dbt_drop_resolution (DB_CTMPL *def, DB_OBJECT *super, const char *name)
int dbt_drop_class_resolution (DB_CTMPL *def, DB_OBJECT *super, const char *name)
int dbt_add_query_spec (DB_CTMPL *def, const char *query)
int dbt_drop_query_spec (DB_CTMPL *def, const int query_no)
int dbt_reset_query_spec (DB_CTMPL *def)
int dbt_change_query_spec (DB_CTMPL *def, const char *new_query, const int query_no)
int dbt_set_object_id (DB_CTMPL *def, DB_NAMELIST *id_list)
int dbt_add_foreign_key (DB_CTMPL *def, const char *constraint_name, const char **attnames, const char *ref_class, const char **ref_attrs, int del_action, int upd_action, const char *comment)
DB_OTMPL * dbt_create_object (DB_OBJECT *classobj)
DB_OTMPL * dbt_edit_object (DB_OBJECT *object)
DB_OBJECT * dbt_finish_object (DB_OTMPL *def)
DB_OBJECT * dbt_finish_object_and_decache_when_failure (DB_OTMPL *def)
void dbt_abort_object (DB_OTMPL *def)
int dbt_put (DB_OTMPL *def, const char *name, DB_VALUE *value)
int dbt_set_label (DB_OTMPL *def, DB_VALUE *label)
int db_get_attribute_descriptor (DB_OBJECT *obj, const char *attname, int class_attribute, int for_update, DB_ATTDESC **descriptor)
void db_free_attribute_descriptor (DB_ATTDESC *descriptor)
int db_get_method_descriptor (DB_OBJECT *obj, const char *methname, int class_method, DB_METHDESC **descriptor)
void db_free_method_descriptor (DB_METHDESC *descriptor)
int db_dget (DB_OBJECT *obj, DB_ATTDESC *attribute, DB_VALUE *value)
int db_dput (DB_OBJECT *obj, DB_ATTDESC *attribute, DB_VALUE *value)
int db_dsend (DB_OBJECT *obj, DB_METHDESC *method, DB_VALUE *returnval,...)
int db_dsend_arglist (DB_OBJECT *obj, DB_METHDESC *method, DB_VALUE *returnval, DB_VALUE_LIST *args)
int db_dsend_argarray (DB_OBJECT *obj, DB_METHDESC *method, DB_VALUE *returnval, DB_VALUE **args)
int db_dsend_quick (DB_OBJECT *obj, DB_METHDESC *method, DB_VALUE *returnval, int nargs, DB_VALUE **args)
int dbt_dput (DB_OTMPL *def, DB_ATTDESC *attribute, DB_VALUE *value)
char * db_get_vclass_ldb_name (DB_OBJECT *op)
int db_add_query_spec (DB_OBJECT *vclass, const char *query)
int db_drop_query_spec (DB_OBJECT *vclass, const int query_no)
DB_NAMELIST * db_get_object_id (DB_OBJECT *vclass)
int db_namelist_add (DB_NAMELIST **list, const char *name)
int db_namelist_append (DB_NAMELIST **list, const char *name)
void db_namelist_free (DB_NAMELIST *list)
int db_is_vclass (DB_OBJECT *op)
DB_OBJLIST * db_get_all_vclasses_on_ldb (void)
DB_OBJLIST * db_get_all_vclasses (void)
DB_QUERY_SPEC * db_get_query_specs (DB_OBJECT *obj)
DB_QUERY_SPEC * db_query_spec_next (DB_QUERY_SPEC *query_spec)
const char * db_query_spec_string (DB_QUERY_SPEC *query_spec)
int db_change_query_spec (DB_OBJECT *vclass, const char *new_query, const int query_no)
int db_validate (DB_OBJECT *vclass)
int db_validate_query_spec (DB_OBJECT *vclass, const char *query_spec)
int db_is_real_instance (DB_OBJECT *obj)
DB_OBJECT * db_real_instance (DB_OBJECT *obj)
int db_instance_equal (DB_OBJECT *obj1, DB_OBJECT *obj2)
int db_is_updatable_object (DB_OBJECT *obj)
int db_is_updatable_attribute (DB_OBJECT *obj, const char *attr_name)
int db_check_single_query (DB_SESSION *session)
int db_get_query_format (const char *CSQL_query, DB_QUERY_TYPE **type_list, DB_QUERY_ERROR *query_error)
DB_QUERY_TYPE * db_query_format_next (DB_QUERY_TYPE *query_type)
DB_COL_TYPE db_query_format_col_type (DB_QUERY_TYPE *query_type)
char * db_query_format_name (DB_QUERY_TYPE *query_type)
DB_TYPE db_query_format_type (DB_QUERY_TYPE *query_type)
void db_query_format_free (DB_QUERY_TYPE *query_type)
DB_DOMAIN * db_query_format_domain (DB_QUERY_TYPE *query_type)
char * db_query_format_attr_name (DB_QUERY_TYPE *query_type)
char * db_query_format_spec_name (DB_QUERY_TYPE *query_type)
char * db_query_format_original_name (DB_QUERY_TYPE *query_type)
const char * db_query_format_class_name (DB_QUERY_TYPE *query_type)
int db_query_format_is_non_null (DB_QUERY_TYPE *query_type)
int db_get_query_result_format (DB_QUERY_RESULT *result, DB_QUERY_TYPE **type_list)
int db_query_next_tuple (DB_QUERY_RESULT *result)
int db_query_prev_tuple (DB_QUERY_RESULT *result)
int db_query_first_tuple (DB_QUERY_RESULT *result)
int db_query_last_tuple (DB_QUERY_RESULT *result)
int db_query_get_tuple_value_by_name (DB_QUERY_RESULT *result, char *column_name, DB_VALUE *value)
int db_query_get_tuple_value (DB_QUERY_RESULT *result, int tuple_index, DB_VALUE *value)
int db_query_get_tuple_oid (DB_QUERY_RESULT *result, DB_VALUE *db_value)
int db_query_get_tuple_valuelist (DB_QUERY_RESULT *result, int size, DB_VALUE *value_list)
int db_query_tuple_count (DB_QUERY_RESULT *result)
int db_query_column_count (DB_QUERY_RESULT *result)
int db_query_prefetch_columns (DB_QUERY_RESULT *result, int *columns, int col_count)
int db_query_format_size (DB_QUERY_TYPE *query_type)
int db_query_plan_dump_file (char *filename)
DB_SESSION * db_open_buffer (const char *buffer)
DB_SESSION * db_open_file (FILE *file)
DB_SESSION * db_open_file_name (const char *name)
int db_statement_count (DB_SESSION *session)
int db_compile_statement (DB_SESSION *session)
void db_rewind_statement (DB_SESSION *session)
int db_session_is_last_statement (DB_SESSION *session)
DB_SESSION_ERROR * db_get_errors (DB_SESSION *session)
DB_SESSION_ERROR * db_get_next_error (DB_SESSION_ERROR *errors, int *linenumber, int *columnnumber)
DB_SESSION_ERROR * db_get_warnings (DB_SESSION *session)
DB_SESSION_ERROR * db_get_next_warning (DB_SESSION_WARNING *errors, int *linenumber, int *columnnumber)
void db_session_set_holdable (DB_SESSION *session, bool holdable)
void db_session_set_xasl_cache_pinned (DB_SESSION *session, bool is_pinned, bool recompile)
void db_session_set_return_generated_keys (DB_SESSION *session, bool return_generated_keys)
DB_PARAMETER * db_get_parameters (DB_SESSION *session, int statement_id)
DB_PARAMETER * db_parameter_next (DB_PARAMETER *param)
const char * db_parameter_name (DB_PARAMETER *param)
int db_bind_parameter_name (const char *name, DB_VALUE *value)
DB_QUERY_TYPE * db_get_query_type_list (DB_SESSION *session, int stmt)
int db_number_of_input_markers (DB_SESSION *session, int stmt)
int db_number_of_output_markers (DB_SESSION *session, int stmt)
DB_MARKER * db_get_input_markers (DB_SESSION *session, int stmt)
DB_MARKER * db_get_output_markers (DB_SESSION *session, int stmt)
DB_MARKER * db_marker_next (DB_MARKER *marker)
int db_marker_index (DB_MARKER *marker)
DB_DOMAIN * db_marker_domain (DB_MARKER *marker)
bool db_is_input_marker (DB_MARKER *marker)
bool db_is_output_marker (DB_MARKER *marker)
int db_get_start_line (DB_SESSION *session, int stmt)
int db_get_statement_type (DB_SESSION *session, int stmt)
void db_include_oid (DB_SESSION *session, int include_oid)
int db_push_values (DB_SESSION *session, int count, DB_VALUE *in_values)
int db_execute (const char *CSQL_query, DB_QUERY_RESULT **result, DB_QUERY_ERROR *query_error)
int db_execute_oid (const char *CSQL_query, DB_QUERY_RESULT **result, DB_QUERY_ERROR *query_error)
int db_query_produce_updatable_result (DB_SESSION *session, int stmtid)
int db_execute_statement (DB_SESSION *session, int stmt, DB_QUERY_RESULT **result)
int db_execute_and_keep_statement (DB_SESSION *session, int stmt, DB_QUERY_RESULT **result)
DB_CLASS_MODIFICATION_STATUS db_has_modified_class (DB_SESSION *session, int stmt_id)
void db_invalidate_mvcc_snapshot_before_statement (void)
void db_set_read_fetch_instance_version (LC_FETCH_VERSION_TYPE read_Fetch_Instance_Version)
int db_set_statement_auto_commit (DB_SESSION *session, bool auto_commit)
int db_query_set_copy_tplvalue (DB_QUERY_RESULT *result, int copy)
void db_close_session (DB_SESSION *session)
void db_drop_statement (DB_SESSION *session, int stmt_id)
int db_object_describe (DB_OBJECT *obj, int num_attrs, const char **attrs, DB_QUERY_TYPE **col_spec)
int db_object_fetch (DB_OBJECT *obj, int num_attrs, const char **attrs, DB_QUERY_RESULT **result)
int db_set_client_cache_time (DB_SESSION *session, int stmt_ndx, CACHE_TIME *cache_time)
bool db_get_jdbccachehint (DB_SESSION *session, int stmt_ndx, int *life_time)
bool db_get_cacheinfo (DB_SESSION *session, int stmt_ndx, bool *use_plan_cache, bool *use_query_cache)
void db_free_query (DB_SESSION *session)
DB_QUERY_TYPE * db_get_query_type_ptr (DB_QUERY_RESULT *result)
int db_query_execute (const char *CSQL_query, DB_QUERY_RESULT **result, DB_QUERY_ERROR *query_error)
int db_list_length (DB_LIST *list)
DB_NAMELIST * db_namelist_copy (DB_NAMELIST *list)
int db_drop_shared_attribute (DB_OBJECT *classobj, const char *name)
int db_add_element_domain (DB_OBJECT *classobj, const char *name, const char *domain)
int db_drop_element_domain (DB_OBJECT *classobj, const char *name, const char *domain)
int db_rename_attribute (DB_OBJECT *classobj, const char *name, int class_attribute, const char *newname)
int db_rename_method (DB_OBJECT *classobj, const char *name, int class_method, const char *newname)
int db_set_argument_domain (DB_OBJECT *classobj, const char *name, int class_method, int arg_index, const char *domain)
int db_set_method_arg_domain (DB_OBJECT *classobj, const char *name, int arg_index, const char *domain)
int db_set_class_method_arg_domain (DB_OBJECT *classobj, const char *name, int arg_index, const char *domain)
DB_NAMELIST * db_namelist_sort (DB_NAMELIST *names)
void db_namelist_remove (DB_NAMELIST **list, const char *name)
DB_OBJECT * db_objlist_get (DB_OBJLIST *list, int psn)
void db_namelist_print (DB_NAMELIST *list)
void db_objlist_print (DB_OBJLIST *list)
DB_NAMELIST * db_get_attribute_names (DB_OBJECT *obj)
DB_NAMELIST * db_get_shared_attribute_names (DB_OBJECT *obj)
DB_NAMELIST * db_get_ordered_attribute_names (DB_OBJECT *obj)
DB_NAMELIST * db_get_class_attribute_names (DB_OBJECT *obj)
DB_NAMELIST * db_get_method_names (DB_OBJECT *obj)
DB_NAMELIST * db_get_class_method_names (DB_OBJECT *obj)
DB_NAMELIST * db_get_superclass_names (DB_OBJECT *obj)
DB_NAMELIST * db_get_subclass_names (DB_OBJECT *obj)
DB_NAMELIST * db_get_method_file_names (DB_OBJECT *obj)
const char * db_get_method_function (DB_OBJECT *obj, const char *name)
DB_DOMAIN * db_get_attribute_domain (DB_OBJECT *obj, const char *name)
DB_TYPE db_get_attribute_type (DB_OBJECT *obj, const char *name)
DB_OBJECT * db_get_attribute_class (DB_OBJECT *obj, const char *name)
void db_force_method_reload (DB_OBJECT *obj)
DB_ATTRIBUTE * db_get_shared_attribute (DB_OBJECT *obj, const char *name)
DB_ATTRIBUTE * db_get_ordered_attributes (DB_OBJECT *obj)
DB_ATTRIBUTE * db_attribute_ordered_next (DB_ATTRIBUTE *attribute)
int db_print_mop (DB_OBJECT *obj, char *buffer, int maxlen)
int db_get_shared (DB_OBJECT *object, const char *attpath, DB_VALUE *value)
DB_OBJECT * db_copy (DB_OBJECT *sourcemop)
char * db_get_method_source_file (DB_OBJECT *obj, const char *name)
int db_is_indexed (DB_OBJECT *classobj, const char *attname)
DB_IDENTIFIER * db_identifier (DB_OBJECT *obj)
DB_OBJECT * db_object (DB_IDENTIFIER *oid)
int db_chn (DB_OBJECT *obj, DB_FETCH_MODE purpose)
int db_encode_object (DB_OBJECT *object, char *string, int allocated_length, int *actual_length)
int db_decode_object (const char *string, DB_OBJECT **object)
int db_set_system_parameters (const char *data)
int db_set_system_parameters_for_ha_repl (const char *data)
int db_reset_system_parameters_from_assignments (const char *data)
int db_get_system_parameters (char *data, int len)
char * db_get_host_connected (void)
int db_get_ha_server_state (char *buffer, int maxlen)
void db_clear_host_connected (void)
char * db_get_database_version (void)
Macro Definition Documentation
#define db_string_to_utime db_string_to_timestamp
Definition at line 51 of file dbi.h.
#define db_utime_to_string db_timestamp_to_string
Definition at line 50 of file dbi.h.
Typedef Documentation
typedef void(* db_error_log_handler_t) (unsigned int)
Definition at line 125 of file dbi.h.
Enumeration Type Documentation
anonymous enum
Enumerator
DB_NO_OIDS
DB_ROW_OIDS
DB_COLUMN_OIDS
Definition at line 56 of file dbi.h.
Function Documentation
int db_2pc_attach_transaction (int gtrid)
Definition at line 1403 of file db_admin.c.
int db_2pc_prepare_to_commit_transaction (int gtrid)
Definition at line 1426 of file db_admin.c.
int db_2pc_prepare_transaction (void)
Definition at line 1351 of file db_admin.c.
int db_2pc_prepared_transactions (int gtrids[], int size)
Definition at line 1373 of file db_admin.c.
int db_2pc_start_transaction (void)
Definition at line 1327 of file db_admin.c.
int db_abort_to_savepoint (const char * savepoint_name)
Definition at line 1237 of file db_admin.c.
int db_abort_transaction (void)
Definition at line 1114 of file db_admin.c.
int db_add_argument (DB_OBJECT * classobj, const char * name, int class_method, int arg_index, const char * domain)
Definition at line 988 of file db_class.c.
int db_add_attribute (DB_OBJECT * obj, const char * name, const char * domain, DB_VALUE * default_value)
int db_add_class_attribute (DB_OBJECT * obj, const char * name, const char * domain, DB_VALUE * default_value)
int db_add_class_method (DB_OBJECT * classobj, const char * name, const char * implementation)
int db_add_class_resolution (DB_OBJECT * classobj, DB_OBJECT * super, const char * name, const char * alias)
int db_add_constraint (MOP classmop, DB_CONSTRAINT_TYPE constraint_type, const char * constraint_name, const char ** att_names, int class_attributes)
Definition at line 1777 of file db_class.c.
int db_add_element_domain (DB_OBJECT * classobj, const char * name, const char * domain)
int db_add_index (DB_OBJECT * classobj, const char * attname)
int db_add_member (DB_OBJECT * user, DB_OBJECT * member)
Definition at line 1694 of file db_admin.c.
int db_add_method (DB_OBJECT * classobj, const char * name, const char * implementation)
int db_add_method_file (DB_OBJECT * classobj, const char * name)
int db_add_query_spec (DB_OBJECT * vclass, const char * query)
int db_add_resolution (DB_OBJECT * classobj, DB_OBJECT * super, const char * name, const char * alias)
int db_add_set_argument_domain (DB_OBJECT * classobj, const char * name, int class_method, int arg_index, const char * domain)
Definition at line 1049 of file db_class.c.
int db_add_set_attribute_domain (DB_OBJECT * classobj, const char * name, int class_attribute, const char * domain)
int db_add_shared_attribute (DB_OBJECT * obj, const char * name, const char * domain, DB_VALUE * default_value)
int db_add_super (DB_OBJECT * classobj, DB_OBJECT * super)
DB_OBJECT* db_add_user (const char * name, int * exists)
Definition at line 1646 of file db_admin.c.
int db_add_volume (const char * ext_path, const char * ext_name, const char * ext_comments, const int ext_npages, const DB_VOLPURPOSE ext_purpose)
Definition at line 314 of file db_admin.c.
int db_add_volume_ex (DBDEF_VOL_EXT_INFO * ext_info)
Definition at line 342 of file db_admin.c.
References ARG_FILE_LINE, assert, Au_dba_user, au_is_dba_group_member(), Au_user, boot_add_volume_extension(), CHECK_CONNECT_ERROR, ER_AU_DBA_ONLY, er_errid(), ER_ERROR_SEVERITY, er_set(), error(), NO_ERROR, NULL, NULL_VOLID, and dbdef_vol_ext_info::overwrite.
Referenced by addvoldb(), and db_add_volume().
int db_alter_trigger_priority (DB_OBJECT * trobj, double priority)
Definition at line 1438 of file db_obj.c.
int db_alter_trigger_status (DB_OBJECT * trobj, DB_TRIGGER_STATUS status)
Definition at line 1462 of file db_obj.c.
DB_OBJECT* db_attribute_class (DB_ATTRIBUTE * attribute)
Definition at line 1189 of file db_info.c.
const char* db_attribute_comment (DB_ATTRIBUTE * attribute)
Definition at line 1083 of file db_info.c.
References sm_attribute::comment, and NULL.
Referenced by class_attr_info().
DB_VALUE* db_attribute_default (DB_ATTRIBUTE * attribute)
Definition at line 1209 of file db_info.c.
DB_DOMAIN* db_attribute_domain (DB_ATTRIBUTE * attribute)
Definition at line 1165 of file db_info.c.
int db_attribute_id (DB_ATTRIBUTE * attribute)
Definition at line 1124 of file db_info.c.
int db_attribute_is_auto_increment (DB_ATTRIBUTE * attribute)
Definition at line 1309 of file db_info.c.
int db_attribute_is_foreign_key (DB_ATTRIBUTE * attribute)
Definition at line 1282 of file db_info.c.
int db_attribute_is_indexed (DB_ATTRIBUTE * attribute)
Definition at line 1375 of file db_info.c.
int db_attribute_is_non_null (DB_ATTRIBUTE * attribute)
Definition at line 1355 of file db_info.c.
int db_attribute_is_primary_key (DB_ATTRIBUTE * attribute)
Definition at line 1255 of file db_info.c.
int db_attribute_is_reverse_indexed (DB_ATTRIBUTE * attribute)
Definition at line 1402 of file db_info.c.
int db_attribute_is_reverse_unique (DB_ATTRIBUTE * attribute)
Definition at line 1328 of file db_info.c.
int db_attribute_is_shared (DB_ATTRIBUTE * attribute)
Definition at line 1429 of file db_info.c.
int db_attribute_is_unique (DB_ATTRIBUTE * attribute)
Definition at line 1228 of file db_info.c.
int db_attribute_length (DB_ATTRIBUTE * attribute)
Definition at line 1102 of file db_info.c.
const char* db_attribute_name (DB_ATTRIBUTE * attribute)
Definition at line 1065 of file db_info.c.
DB_ATTRIBUTE* db_attribute_next (DB_ATTRIBUTE * attribute)
Definition at line 1020 of file db_info.c.
int db_attribute_order (DB_ATTRIBUTE * attribute)
Definition at line 1144 of file db_info.c.
DB_ATTRIBUTE* db_attribute_ordered_next (DB_ATTRIBUTE * attribute)
Definition at line 1047 of file db_info.c.
DB_TYPE db_attribute_type (DB_ATTRIBUTE * attribute)
Definition at line 1000 of file db_info.c.
int db_auth_login (char * signed_data, int len)
int db_auth_logout (void)
int db_bind_parameter_name (const char * name, DB_VALUE * value)
Definition at line 3813 of file db_vdb.c.
int db_change_default (DB_OBJECT * classobj, const char * name, DB_VALUE * value)
int db_change_method_implementation (DB_OBJECT * classobj, const char * name, int class_method, const char * newname)
int db_change_query_spec (DB_OBJECT * vclass, const char * new_query, const int query_no)
Definition at line 558 of file db_virt.c.
int db_check_authorization (DB_OBJECT * op, DB_AUTH auth)
int db_check_authorization_and_grant_option (MOP op, DB_AUTH auth)
Definition at line 1872 of file db_admin.c.
int db_check_single_query (DB_SESSION * session)
Definition at line 3695 of file db_vdb.c.
int db_checkpoint (void)
Definition at line 1473 of file db_admin.c.
References CHECK_CONNECT_ERROR, and log_checkpoint().
Referenced by csql_do_session_cmd().
int db_chn (DB_OBJECT * obj, DB_FETCH_MODE purpose)
Definition at line 2660 of file db_admin.c.
int db_class_has_instance (DB_OBJECT * classobj)
Definition at line 686 of file db_info.c.
References db_class_has_instance(), db_get_subclasses(), heap_has_instance(), db_objlist::next, db_objlist::op, sm_get_ch_heap(), and WS_OID.
Referenced by db_class_has_instance(), do_update_new_cols_with_default_expression(), and do_update_new_notnull_cols_without_default().
void db_clear_delayed_hosts_count (void)
Definition at line 546 of file db_admin.c.
References db_Delayed_hosts_count.
Referenced by boot_client_all_finalize().
void db_clear_host_connected (void)
Definition at line 851 of file db_admin.c.
void db_clear_host_status (void)
Definition at line 580 of file db_admin.c.
void db_close_session (DB_SESSION * session)
Definition at line 3319 of file db_vdb.c.
int db_commit_is_needed (void)
Definition at line 1154 of file db_admin.c.
int db_commit_transaction (void)
Definition at line 1091 of file db_admin.c.
int db_compile_statement (DB_SESSION * session)
Definition at line 766 of file db_vdb.c.
int db_constrain_non_null (DB_OBJECT * classobj, const char * name, int class_attribute, int on_or_off)
int db_constrain_unique (DB_OBJECT * classobj, const char * name, int on_or_off)
const int* db_constraint_asc_desc (DB_CONSTRAINT * constraint)
Definition at line 2070 of file db_info.c.
DB_ATTRIBUTE** db_constraint_attributes (DB_CONSTRAINT * constraint)
Definition at line 2052 of file db_info.c.
DB_CONSTRAINT* db_constraint_find_primary_key (DB_CONSTRAINT * constraint)
Definition at line 1956 of file db_info.c.
const char* db_constraint_name (DB_CONSTRAINT * constraint)
Definition at line 2031 of file db_info.c.
DB_CONSTRAINT* db_constraint_next (DB_CONSTRAINT * constraint)
Definition at line 1938 of file db_info.c.
const int* db_constraint_prefix_length (DB_CONSTRAINT * constraint)
Definition at line 2089 of file db_info.c.
References sm_class_constraint::attrs_prefix_length, and NULL.
Referenced by emit_index_def().
DB_CONSTRAINT_TYPE db_constraint_type (const DB_CONSTRAINT * constraint)
Definition at line 1978 of file db_info.c.
References DB_CONSTRAINT_FOREIGN_KEY, DB_CONSTRAINT_INDEX, DB_CONSTRAINT_NOT_NULL, DB_CONSTRAINT_PRIMARY_KEY, DB_CONSTRAINT_REVERSE_INDEX, DB_CONSTRAINT_REVERSE_UNIQUE, DB_CONSTRAINT_UNIQUE, NULL, prm_get_bool_value(), PRM_ID_COMPAT_PRIMARY_KEY, SM_CONSTRAINT_FOREIGN_KEY, SM_CONSTRAINT_INDEX, SM_CONSTRAINT_NOT_NULL, SM_CONSTRAINT_PRIMARY_KEY, SM_CONSTRAINT_REVERSE_INDEX, SM_CONSTRAINT_REVERSE_UNIQUE, SM_CONSTRAINT_UNIQUE, and sm_class_constraint::type.
Referenced by classobj_copy_constraint_like(), db_get_btree_statistics(), do_alter_index_rebuild(), do_alter_one_clause_with_template(), do_copy_indexes(), do_create_partition_constraint(), emit_foreign_key(), emit_index_def(), emit_reverse_unique_def(), emit_unique_def(), fetch_constraint(), sch_constraint(), sch_exported_keys_or_cross_reference(), sch_imported_keys(), sm_drop_constraint(), sm_exist_index(), sm_save_constraint_info(), and smt_rename_any().
DB_OBJECT* db_copy (DB_OBJECT * sourcemop)
DB_OBJECT* db_create (DB_OBJECT * obj)
Definition at line 69 of file db_obj.c.
DB_OBJECT* db_create_by_name (const char * name)
Definition at line 115 of file db_obj.c.
DB_OBJECT* db_create_class (const char * name)
Definition at line 70 of file db_class.c.
DB_OBJECT* db_create_trigger (const char * name, DB_TRIGGER_STATUS status, double priority, DB_TRIGGER_EVENT event, DB_OBJECT * class_obj, const char * attr, DB_TRIGGER_TIME cond_time, const char * cond_source, DB_TRIGGER_TIME action_time, DB_TRIGGER_ACTION action_type, const char * action_source)
Definition at line 1301 of file db_obj.c.
DB_OBJECT* db_create_vclass (const char * name)
Definition at line 140 of file db_virt.c.
int db_decode_object (const char * string, DB_OBJECT ** object)
Definition at line 1805 of file db_obj.c.
DB_OBJECT* db_dfind_multi_unique (DB_OBJECT * classobj, int size, DB_ATTDESC * attdesc[], DB_VALUE * values[], DB_FETCH_MODE purpose)
DB_OBJECT* db_dfind_unique (DB_OBJECT * classobj, DB_ATTDESC * attdesc, DB_VALUE * value, DB_FETCH_MODE purpose)
int db_dget (DB_OBJECT * obj, DB_ATTDESC * attribute, DB_VALUE * value)
Definition at line 889 of file db_obj.c.
int db_disable_modification (void)
Definition at line 1001 of file db_admin.c.
bool db_disable_trigger (void)
Definition at line 570 of file db_admin.c.
bool db_does_connected_host_have_status (int status)
Definition at line 755 of file db_admin.c.
DB_OBJECT* db_domain_class (const DB_DOMAIN * domain)
Definition at line 4030 of file db_macro.c.
int db_domain_codeset (const DB_DOMAIN * domain)
Definition at line 4116 of file db_macro.c.
int db_domain_collation_id (const DB_DOMAIN * domain)
Definition at line 4134 of file db_macro.c.
References tp_domain::collation_id, and NULL.
Referenced by pt_domain_to_data_type().
DB_DOMAIN* db_domain_next (const DB_DOMAIN * domain)
Definition at line 3974 of file db_macro.c.
int db_domain_precision (const DB_DOMAIN * domain)
Definition at line 4079 of file db_macro.c.
const char* db_domain_raw_json_schema (const DB_DOMAIN * domain)
Definition at line 4147 of file db_macro.c.
int db_domain_scale (const DB_DOMAIN * domain)
Definition at line 4098 of file db_macro.c.
DB_DOMAIN* db_domain_set (const DB_DOMAIN * domain)
Definition at line 4060 of file db_macro.c.
DB_TYPE db_domain_type (const DB_DOMAIN * domain)
Definition at line 4006 of file db_macro.c.
int db_dput (DB_OBJECT * obj, DB_ATTDESC * attribute, DB_VALUE * value)
Definition at line 908 of file db_obj.c.
int db_drop (DB_OBJECT * obj)
Definition at line 190 of file db_obj.c.
int db_drop_attribute (DB_OBJECT * classobj, const char * name)
int db_drop_class (DB_OBJECT * classobj)
int db_drop_class_attribute (DB_OBJECT * classobj, const char * name)
int db_drop_class_ex (DB_OBJECT * classobj, bool is_cascade_constraints)
int db_drop_class_method (DB_OBJECT * classobj, const char * name)
int db_drop_class_resolution (DB_OBJECT * classobj, DB_OBJECT * super, const char * name)
int db_drop_constraint (MOP classmop, DB_CONSTRAINT_TYPE constraint_type, const char * constraint_name, const char ** att_names, int class_attributes)
Definition at line 1826 of file db_class.c.
int db_drop_deferred_activities (DB_OBJECT * trigger_obj, DB_OBJECT * target)
Definition at line 1527 of file db_obj.c.
int db_drop_element_domain (DB_OBJECT * classobj, const char * name, const char * domain)
int db_drop_index (DB_OBJECT * classobj, const char * attname)
int db_drop_member (DB_OBJECT * user, DB_OBJECT * member)
Definition at line 1719 of file db_admin.c.
int db_drop_method (DB_OBJECT * classobj, const char * name)
int db_drop_method_file (DB_OBJECT * classobj, const char * name)
int db_drop_method_files (DB_OBJECT * classobj)
int db_drop_query_spec (DB_OBJECT * vclass, const int query_no)
Definition at line 507 of file db_virt.c.
int db_drop_resolution (DB_OBJECT * classobj, DB_OBJECT * super, const char * name)
int db_drop_shared_attribute (DB_OBJECT * classobj, const char * name)
void db_drop_statement (DB_SESSION * session, int stmt_id)
Definition at line 3196 of file db_vdb.c.
int db_drop_super (DB_OBJECT * classobj, DB_OBJECT * super)
int db_drop_super_connect (DB_OBJECT * classobj, DB_OBJECT * super)
int db_drop_trigger (DB_OBJECT * obj)
Definition at line 1325 of file db_obj.c.
int db_drop_user (DB_OBJECT * user)
Definition at line 1668 of file db_admin.c.
int db_dsend (DB_OBJECT * obj, DB_METHDESC * method, DB_VALUE * returnval, ...)
Definition at line 999 of file db_obj.c.
int db_dsend_argarray (DB_OBJECT * obj, DB_METHDESC * method, DB_VALUE * returnval, DB_VALUE ** args)
Definition at line 1042 of file db_obj.c.
int db_dsend_arglist (DB_OBJECT * obj, DB_METHDESC * method, DB_VALUE * returnval, DB_VALUE_LIST * args)
Definition at line 1022 of file db_obj.c.
int db_dsend_quick (DB_OBJECT * obj, DB_METHDESC * method, DB_VALUE * returnval, int nargs, DB_VALUE ** args)
Definition at line 1067 of file db_obj.c.
int db_enable_modification (void)
Definition at line 1015 of file db_admin.c.
bool db_enable_trigger (void)
Definition at line 558 of file db_admin.c.
int db_encode_object (DB_OBJECT * object, char * string, int allocated_length, int * actual_length)
Definition at line 1787 of file db_obj.c.
int db_end_session (void)
Definition at line 1029 of file db_admin.c.
int db_error_code (void)
Definition at line 2143 of file db_admin.c.
int db_error_init (const char * logfile)
Definition at line 2164 of file db_admin.c.
const char* db_error_string (int level)
Definition at line 2116 of file db_admin.c.
int db_execute (const char * CSQL_query, DB_QUERY_RESULT ** result, DB_QUERY_ERROR * query_error)
Definition at line 1836 of file db_query.c.
int db_execute_and_keep_statement (DB_SESSION * session, int stmt, DB_QUERY_RESULT ** result)
Definition at line 2906 of file db_vdb.c.
int db_execute_deferred_activities (DB_OBJECT * trigger_obj, DB_OBJECT * target)
Definition at line 1496 of file db_obj.c.
int db_execute_oid (const char * CSQL_query, DB_QUERY_RESULT ** result, DB_QUERY_ERROR * query_error)
Definition at line 1852 of file db_query.c.
int db_execute_statement (DB_SESSION * session, int stmt, DB_QUERY_RESULT ** result)
Definition at line 2978 of file db_vdb.c.
DB_OBJLIST* db_fetch_all_classes (DB_FETCH_MODE mode)
Definition at line 203 of file db_info.c.
DB_OBJLIST* db_fetch_all_objects (DB_OBJECT * op, DB_FETCH_MODE mode)
Definition at line 178 of file db_info.c.
int db_fetch_array (DB_OBJECT ** objects, DB_FETCH_MODE mode, int quit_on_error)
Definition at line 2216 of file db_admin.c.
DB_OBJLIST* db_fetch_base_classes (DB_FETCH_MODE mode)
Definition at line 223 of file db_info.c.
int db_fetch_composition (DB_OBJECT * object, DB_FETCH_MODE mode, int max_level, int quit_on_error)
Definition at line 2407 of file db_admin.c.
int db_fetch_list (DB_OBJLIST * objects, DB_FETCH_MODE mode, int quit_on_error)
Definition at line 2254 of file db_admin.c.
int db_fetch_seq (DB_SEQ * set, DB_FETCH_MODE mode, int quit_on_error)
Definition at line 2388 of file db_admin.c.
int db_fetch_set (DB_COLLECTION * set, DB_FETCH_MODE mode, int quit_on_error)
Definition at line 2372 of file db_admin.c.
int db_find_all_triggers (DB_OBJLIST ** list)
Definition at line 1394 of file db_obj.c.
DB_OBJECT* db_find_class (const char * name)
Definition at line 133 of file db_info.c.
DB_OBJECT* db_find_class_of_index (const char *const index, const DB_CONSTRAINT_TYPE type)
Definition at line 74 of file db_info.c.
DB_OBJECT* db_find_class_with_purpose (const char * name, bool for_update)
Definition at line 153 of file db_info.c.
References CHECK_1ARG_NULL, CHECK_CONNECT_NULL, and sm_find_class_with_purpose().
Referenced by pt_check_drop(), pt_find_class(), pt_make_flat_name_list(), and pt_resolve_partition_spec().
int db_find_event_triggers (DB_TRIGGER_EVENT event, DB_OBJECT * class_obj, const char * attr, DB_OBJLIST ** list)
Definition at line 1421 of file db_obj.c.
DB_OBJECT* db_find_multi_unique (DB_OBJECT * classobj, int size, char * attnames[], DB_VALUE * values[], DB_FETCH_MODE purpose)
int db_find_or_create_session (const char * db_user, const char * program_name)
Definition at line 2885 of file db_admin.c.
DB_OBJECT* db_find_primary_key (MOP classmop, const DB_VALUE ** values, int size, DB_FETCH_MODE purpose)
Definition at line 1138 of file db_obj.c.
DB_OBJECT* db_find_trigger (const char * name)
Definition at line 1370 of file db_obj.c.
DB_OBJECT* db_find_unique (DB_OBJECT * classobj, const char * attname, DB_VALUE * value)
DB_OBJECT* db_find_unique_write_mode (DB_OBJECT * classobj, const char * attname, DB_VALUE * value)
DB_OBJECT* db_find_user (const char * name)
Definition at line 1606 of file db_admin.c.
int db_find_user_to_drop (const char * name, DB_OBJECT ** user)
Definition at line 1626 of file db_admin.c.
void db_flush_static_methods (void)
Definition at line 2564 of file db_admin.c.
void db_force_method_reload (DB_OBJECT * obj)
void db_fprint (FILE * fp, DB_OBJECT * obj)
Definition at line 1268 of file db_obj.c.
void db_free_attribute_descriptor (DB_ATTDESC * descriptor)
Definition at line 835 of file db_obj.c.
void db_free_method_descriptor (DB_METHDESC * descriptor)
Definition at line 875 of file db_obj.c.
void db_free_query (DB_SESSION * session)
Definition at line 3683 of file db_vdb.c.
int db_freepgs (const char * vlabel)
Definition at line 2054 of file db_admin.c.
int db_get (DB_OBJECT * object, const char * attpath, DB_VALUE * value)
Definition at line 233 of file db_obj.c.
DB_OBJLIST* db_get_all_classes (void)
Definition at line 267 of file db_info.c.
DB_OBJLIST* db_get_all_objects (DB_OBJECT * classobj)
Definition at line 246 of file db_info.c.
DB_OBJLIST* db_get_all_vclasses (void)
Definition at line 3423 of file db_vdb.c.
DB_OBJLIST* db_get_all_vclasses_on_ldb (void)
Definition at line 3412 of file db_vdb.c.
DB_ATTRIBUTE* db_get_attribute (DB_OBJECT * obj, const char * name)
Definition at line 791 of file db_info.c.
DB_ATTRIBUTE* db_get_attribute_by_name (const char * class_name, const char * attribute_name)
Definition at line 823 of file db_info.c.
DB_OBJECT* db_get_attribute_class (DB_OBJECT * obj, const char * name)
int db_get_attribute_descriptor (DB_OBJECT * obj, const char * attname, int class_attribute, int for_update, DB_ATTDESC ** descriptor)
Definition at line 763 of file db_obj.c.
DB_DOMAIN* db_get_attribute_domain (DB_OBJECT * obj, const char * name)
DB_NAMELIST* db_get_attribute_names (DB_OBJECT * obj)
DB_TYPE db_get_attribute_type (DB_OBJECT * obj, const char * name)
DB_ATTRIBUTE* db_get_attributes (DB_OBJECT * obj)
Definition at line 908 of file db_info.c.
DB_OBJLIST* db_get_base_classes (void)
Definition at line 284 of file db_info.c.
int db_get_btree_statistics (DB_CONSTRAINT * cons, int * num_leaf_pages, int * num_total_pages, int * num_keys, int * height)
Definition at line 2365 of file db_info.c.
bool db_get_cacheinfo (DB_SESSION * session, int stmt_ndx, bool * use_plan_cache, bool * use_query_cache)
Definition at line 878 of file db_vdb.c.
DB_OBJECT* db_get_class (DB_OBJECT * obj)
DB_ATTRIBUTE* db_get_class_attribute (DB_OBJECT * obj, const char * name)
Definition at line 878 of file db_info.c.
DB_NAMELIST* db_get_class_attribute_names (DB_OBJECT * obj)
DB_ATTRIBUTE* db_get_class_attributes (DB_OBJECT * obj)
Definition at line 939 of file db_info.c.
DB_METHOD* db_get_class_method (DB_OBJECT * obj, const char * name)
Definition at line 1484 of file db_info.c.
DB_NAMELIST* db_get_class_method_names (DB_OBJECT * obj)
DB_METHOD* db_get_class_methods (DB_OBJECT * obj)
Definition at line 1542 of file db_info.c.
const char* db_get_class_name (DB_OBJECT * classobj)
Definition at line 608 of file db_info.c.
int db_get_class_num_objs_and_pages (DB_OBJECT * classmop, int approximation, int * nobjs, int * npages)
Definition at line 2311 of file db_info.c.
int db_get_class_privilege (DB_OBJECT * op, unsigned int * auth)
Definition at line 2346 of file db_info.c.
DB_RESOLUTION* db_get_class_resolutions (DB_OBJECT * obj)
Definition at line 1767 of file db_info.c.
int db_get_client_type (void)
Definition at line 489 of file db_admin.c.
DB_CONSTRAINT* db_get_constraints (DB_OBJECT * obj)
Definition at line 1909 of file db_info.c.
const char* db_get_database_comments (void)
Definition at line 471 of file db_admin.c.
char* db_get_database_name (void)
Definition at line 432 of file db_admin.c.
char* db_get_database_version (void)
Definition at line 455 of file db_admin.c.
int db_get_delayed_hosts_count (void)
Definition at line 540 of file db_admin.c.
References db_Delayed_hosts_count.
Referenced by boot_client_all_finalize().
DB_SESSION_ERROR* db_get_errors (DB_SESSION * session)
Definition at line 926 of file db_vdb.c.
int db_get_expression (DB_OBJECT * object, const char * expression, DB_VALUE * value)
Definition at line 296 of file db_obj.c.
const char* db_get_foreign_key_action (DB_CONSTRAINT * constraint, DB_FK_ACTION_TYPE type)
Definition at line 2143 of file db_info.c.
DB_OBJECT* db_get_foreign_key_ref_class (DB_CONSTRAINT * constraint)
Definition at line 2124 of file db_info.c.
int db_get_global_transaction_info (int gtrid, void * buffer, int size)
Definition at line 1295 of file db_admin.c.
int db_get_ha_server_state (char * buffer, int maxlen)
Definition at line 2824 of file db_admin.c.
char* db_get_host_connected (void)
Definition at line 2806 of file db_admin.c.
int db_get_host_list_with_given_status (char ** hostlist, int list_size, int status)
Definition at line 776 of file db_admin.c.
References db_host_status_list::hostlist, db_host_status::hostname, i, db_host_status_list::last_host_idx, NULL, and db_host_status::status.
Referenced by report_abnormal_host_status().
DB_MARKER* db_get_input_markers (DB_SESSION * session, int stmt)
Definition at line 1179 of file db_vdb.c.
bool db_get_jdbccachehint (DB_SESSION * session, int stmt_ndx, int * life_time)
Definition at line 844 of file db_vdb.c.
int db_get_last_insert_id (DB_VALUE * value)
Definition at line 1058 of file db_admin.c.
const char* db_get_loader_commands (DB_OBJECT * obj)
Definition at line 2239 of file db_info.c.
int db_get_max_num_delayed_hosts_lookup (void)
Definition at line 534 of file db_admin.c.
References db_Max_num_delayed_hosts_lookup.
Referenced by boot_client_all_finalize().
DB_METHOD* db_get_method (DB_OBJECT * obj, const char * name)
Definition at line 1454 of file db_info.c.
int db_get_method_descriptor (DB_OBJECT * obj, const char * methname, int class_method, DB_METHDESC ** descriptor)
Definition at line 857 of file db_obj.c.
DB_NAMELIST* db_get_method_file_names (DB_OBJECT * obj)
DB_METHFILE* db_get_method_files (DB_OBJECT * obj)
Definition at line 2173 of file db_info.c.
const char* db_get_method_function (DB_OBJECT * obj, const char * name)
DB_NAMELIST* db_get_method_names (DB_OBJECT * obj)
char* db_get_method_source_file (DB_OBJECT * obj, const char * name)
DB_METHOD* db_get_methods (DB_OBJECT * obj)
Definition at line 1513 of file db_info.c.
DB_SESSION_ERROR* db_get_next_error (DB_SESSION_ERROR * errors, int * linenumber, int * columnnumber)
Definition at line 953 of file db_vdb.c.
DB_SESSION_ERROR* db_get_next_warning (DB_SESSION_WARNING * errors, int * linenumber, int * columnnumber)
Definition at line 1013 of file db_vdb.c.
DB_NAMELIST* db_get_object_id (DB_OBJECT * vclass)
DB_NAMELIST* db_get_ordered_attribute_names (DB_OBJECT * obj)
DB_ATTRIBUTE* db_get_ordered_attributes (DB_OBJECT * obj)
Definition at line 971 of file db_info.c.
DB_MARKER* db_get_output_markers (DB_SESSION * session, int stmt)
Definition at line 1209 of file db_vdb.c.
DB_OBJECT* db_get_owner (DB_OBJECT * classobj)
Definition at line 1892 of file db_admin.c.
DB_PARAMETER* db_get_parameters (DB_SESSION * session, int statement_id)
Definition at line 3744 of file db_vdb.c.
int db_get_query_format (const char * CSQL_query, DB_QUERY_TYPE ** type_list, DB_QUERY_ERROR * query_error)
Definition at line 1558 of file db_query.c.
int db_get_query_result_format (DB_QUERY_RESULT * result, DB_QUERY_TYPE ** type_list)
Definition at line 2055 of file db_query.c.
DB_QUERY_SPEC* db_get_query_specs (DB_OBJECT * obj)
Definition at line 608 of file db_virt.c.
DB_QUERY_TYPE* db_get_query_type_list (DB_SESSION * session, int stmt)
Definition at line 1341 of file db_vdb.c.
DB_QUERY_TYPE* db_get_query_type_ptr (DB_QUERY_RESULT * result)
Definition at line 1431 of file db_vdb.c.
DB_RESOLUTION* db_get_resolutions (DB_OBJECT * obj)
Definition at line 1735 of file db_info.c.
int db_get_row_count (int * row_count)
Definition at line 1046 of file db_admin.c.
int db_get_row_count_cache (void)
Definition at line 2914 of file db_admin.c.
int db_get_schema_def_dbval (DB_VALUE * result, DB_VALUE * name_val)
Definition at line 2407 of file db_info.c.
int db_get_serial_current_value (const char * serial_name, DB_VALUE * serial_value)
Definition at line 1820 of file db_obj.c.
int db_get_serial_next_value (const char * serial_name, DB_VALUE * serial_value)
Definition at line 1866 of file db_obj.c.
int db_get_serial_next_value_ex (const char * serial_name, DB_VALUE * serial_value, int num_alloc)
Definition at line 1878 of file db_obj.c.
char* db_get_server_session_key (void)
Definition at line 2849 of file db_admin.c.
References boot_get_server_session_key().
Referenced by cas_make_session_for_driver(), and db_find_or_create_session().
SESSION_ID db_get_session_id (void)
Definition at line 2859 of file db_admin.c.
int db_get_shared (DB_OBJECT * object, const char * attpath, DB_VALUE * value)
Definition at line 255 of file db_obj.c.
DB_ATTRIBUTE* db_get_shared_attribute (DB_OBJECT * obj, const char * name)
Definition at line 849 of file db_info.c.
DB_NAMELIST* db_get_shared_attribute_names (DB_OBJECT * obj)
int db_get_start_line (DB_SESSION * session, int stmt)
Definition at line 1444 of file db_vdb.c.
int db_get_statement_type (DB_SESSION * session, int stmt)
Definition at line 1473 of file db_vdb.c.
DB_NAMELIST* db_get_subclass_names (DB_OBJECT * obj)
DB_OBJLIST* db_get_subclasses (DB_OBJECT * obj)
Definition at line 659 of file db_info.c.
DB_NAMELIST* db_get_superclass_names (DB_OBJECT * obj)
DB_OBJLIST* db_get_superclasses (DB_OBJECT * obj)
Definition at line 630 of file db_info.c.
int db_get_system_parameters (char * data, int len)
Definition at line 2770 of file db_admin.c.
void db_get_tran_settings (int * lock_wait, DB_TRAN_ISOLATION * tran_isolation)
Definition at line 1554 of file db_admin.c.
const char* db_get_type_name (DB_TYPE type_id)
Definition at line 722 of file db_info.c.
DB_OBJECT* db_get_user (void)
Definition at line 1974 of file db_admin.c.
char* db_get_user_and_host_name (void)
Definition at line 1932 of file db_admin.c.
char* db_get_user_name (void)
Definition at line 1911 of file db_admin.c.
int db_get_variable (DB_VALUE * name, DB_VALUE * value)
Definition at line 1072 of file db_admin.c.
char* db_get_vclass_ldb_name (DB_OBJECT * op)
Definition at line 199 of file db_virt.c.
DB_SESSION_ERROR* db_get_warnings (DB_SESSION * session)
Definition at line 985 of file db_vdb.c.
int db_grant (DB_OBJECT * user, DB_OBJECT * classobj, DB_AUTH auth, int grant_option)
DB_CLASS_MODIFICATION_STATUS db_has_modified_class (DB_SESSION * session, int stmt_id)
Definition at line 2874 of file db_vdb.c.
DB_IDENTIFIER* db_identifier (DB_OBJECT * obj)
Definition at line 2629 of file db_admin.c.
void db_include_oid (DB_SESSION * session, int include_oid)
Definition at line 1508 of file db_vdb.c.
int db_instance_equal (DB_OBJECT * obj1, DB_OBJECT * obj2)
Definition at line 281 of file db_virt.c.
void db_invalidate_mvcc_snapshot_before_statement (void)
Definition at line 3881 of file db_vdb.c.
References tm_Tran_invalidate_snapshot, TM_TRAN_ISOLATION, TRAN_REPEATABLE_READ, and ws_increment_mvcc_snapshot_version().
Referenced by db_compile_and_execute_queries_internal(), db_execute_and_keep_statement(), and db_execute_statement().
int db_is_any_class (DB_OBJECT * obj)
int db_is_class (DB_OBJECT * obj)
int db_is_deleted (DB_OBJECT * obj)
Definition at line 531 of file db_info.c.
int db_is_indexed (DB_OBJECT * classobj, const char * attname)
bool db_is_input_marker (DB_MARKER * marker)
Definition at line 1299 of file db_vdb.c.
int db_is_instance (DB_OBJECT * obj)
int db_is_instance_of (DB_OBJECT * obj, DB_OBJECT * classobj)
bool db_is_output_marker (DB_MARKER * marker)
Definition at line 1318 of file db_vdb.c.
int db_is_partition (DB_OBJECT * classobj, DB_OBJECT * superobj)
Definition at line 483 of file db_info.c.
int db_is_real_instance (DB_OBJECT * obj)
Definition at line 213 of file db_virt.c.
int db_is_subclass (DB_OBJECT * classobj, DB_OBJECT * supermop)
int db_is_superclass (DB_OBJECT * supermop, DB_OBJECT * classobj)
int db_is_system_class (DB_OBJECT * op)
int db_is_updatable_attribute (DB_OBJECT * obj, const char * attr_name)
Definition at line 395 of file db_virt.c.
int db_is_updatable_object (DB_OBJECT * obj)
Definition at line 342 of file db_virt.c.
int db_is_vclass (DB_OBJECT * op)
Definition at line 681 of file db_virt.c.
int db_last_volume (void)
Definition at line 391 of file db_admin.c.
References boot_find_last_permanent(), and CHECK_CONNECT_ZERO.
void db_link_static_methods (DB_METHOD_LINK * methods)
Definition at line 2523 of file db_admin.c.
int db_list_length (DB_LIST * list)
Definition at line 69 of file db_old.c.
int db_lock_read (DB_OBJECT * op)
Definition at line 2001 of file db_admin.c.
int db_lock_write (DB_OBJECT * op)
Definition at line 2030 of file db_admin.c.
int db_login (const char * name, const char * password)
Definition at line 804 of file db_admin.c.
DB_DOMAIN* db_marker_domain (DB_MARKER * marker)
Definition at line 1276 of file db_vdb.c.
int db_marker_index (DB_MARKER * marker)
Definition at line 1257 of file db_vdb.c.
DB_MARKER* db_marker_next (DB_MARKER * marker)
Definition at line 1238 of file db_vdb.c.
const char* db_methfile_name (DB_METHFILE * methfile)
Definition at line 2219 of file db_info.c.
DB_METHFILE* db_methfile_next (DB_METHFILE * methfile)
Definition at line 2201 of file db_info.c.
int db_method_arg_count (DB_METHOD * method)
Definition at line 1710 of file db_info.c.
DB_DOMAIN* db_method_arg_domain (DB_METHOD * method, int arg)
Definition at line 1671 of file db_info.c.
DB_OBJECT* db_method_class (DB_METHOD * method)
Definition at line 1626 of file db_info.c.
const char* db_method_function (DB_METHOD * method)
Definition at line 1606 of file db_info.c.
const char* db_method_name (DB_METHOD * method)
Definition at line 1587 of file db_info.c.
DB_METHOD* db_method_next (DB_METHOD * method)
Definition at line 1569 of file db_info.c.
DB_DOMAIN* db_method_return_domain (DB_METHOD * method)
Definition at line 1646 of file db_info.c.
int db_namelist_add (DB_NAMELIST ** list, const char * name)
Definition at line 84 of file db_virt.c.
int db_namelist_append (DB_NAMELIST ** list, const char * name)
Definition at line 108 of file db_virt.c.
DB_NAMELIST* db_namelist_copy (DB_NAMELIST * list)
Definition at line 148 of file db_old.c.
void db_namelist_free (DB_NAMELIST * list)
Definition at line 71 of file db_virt.c.
void db_namelist_print (DB_NAMELIST * list)
Definition at line 233 of file db_old.c.
void db_namelist_remove (DB_NAMELIST ** list, const char * name)
Definition at line 213 of file db_old.c.
DB_NAMELIST* db_namelist_sort (DB_NAMELIST * names)
Definition at line 170 of file db_old.c.
bool db_need_ignore_repl_delay (void)
Definition at line 743 of file db_admin.c.
bool db_need_reconnect (void)
Definition at line 709 of file db_admin.c.
int db_num_volumes (void)
Definition at line 374 of file db_admin.c.
int db_number_of_input_markers (DB_SESSION * session, int stmt)
Definition at line 1125 of file db_vdb.c.
int db_number_of_output_markers (DB_SESSION * session, int stmt)
Definition at line 1152 of file db_vdb.c.
DB_OBJECT* db_object (DB_IDENTIFIER * oid)
Definition at line 2641 of file db_admin.c.
int db_object_describe (DB_OBJECT * obj, int num_attrs, const char ** attrs, DB_QUERY_TYPE ** col_spec)
Definition at line 1200 of file query_result.c.
Referenced by uci_object_describe().
int db_object_fetch (DB_OBJECT * obj, int num_attrs, const char ** attrs, DB_QUERY_RESULT ** result)
Definition at line 1273 of file query_result.c.
Referenced by uci_object_fetch().
void db_objlist_free (DB_OBJLIST * list)
Definition at line 2612 of file db_admin.c.
DB_OBJECT* db_objlist_get (DB_OBJLIST * list, int psn)
Definition at line 96 of file db_old.c.
DB_OBJLIST* db_objlist_next (DB_OBJLIST * link)
Definition at line 2271 of file db_info.c.
DB_OBJECT* db_objlist_object (DB_OBJLIST * link)
Definition at line 2290 of file db_info.c.
void db_objlist_print (DB_OBJLIST * list)
Definition at line 121 of file db_old.c.
DB_SESSION* db_open_buffer (const char * buffer)
Definition at line 232 of file db_vdb.c.
DB_SESSION* db_open_file (FILE * file)
Definition at line 251 of file db_vdb.c.
DB_SESSION* db_open_file_name (const char * name)
Definition at line 376 of file db_vdb.c.
const char* db_parameter_name (DB_PARAMETER * param)
Definition at line 3791 of file db_vdb.c.
DB_PARAMETER* db_parameter_next (DB_PARAMETER * param)
Definition at line 3772 of file db_vdb.c.
int db_ping_server (int client_val, int * server_val)
Definition at line 983 of file db_admin.c.
void db_preload_classes (const char * name1, ...)
Definition at line 2476 of file db_admin.c.
void db_print (DB_OBJECT * obj)
Definition at line 1251 of file db_obj.c.
int db_print_mop (DB_OBJECT * obj, char * buffer, int maxlen)
Definition at line 733 of file db_old.c.
void db_print_stats (void)
Definition at line 1985 of file db_admin.c.
int db_push_values (DB_SESSION * session, int count, DB_VALUE * in_values)
Definition at line 1527 of file db_vdb.c.
int db_put (DB_OBJECT * obj, const char * name, DB_VALUE * value)
Definition at line 318 of file db_obj.c.
int db_query_column_count (DB_QUERY_RESULT * result)
Definition at line 3134 of file db_query.c.
int db_query_execute (const char * CSQL_query, DB_QUERY_RESULT ** result, DB_QUERY_ERROR * query_error)
Definition at line 1808 of file db_query.c.
int db_query_first_tuple (DB_QUERY_RESULT * result)
Definition at line 2309 of file db_query.c.
char* db_query_format_attr_name (DB_QUERY_TYPE * query_type)
Definition at line 1622 of file db_query.c.
const char* db_query_format_class_name (DB_QUERY_TYPE * query_type)
Definition at line 1740 of file db_query.c.
DB_COL_TYPE db_query_format_col_type (DB_QUERY_TYPE * query_type)
Definition at line 1590 of file db_query.c.
DB_DOMAIN* db_query_format_domain (DB_QUERY_TYPE * query_type)
Definition at line 1661 of file db_query.c.
void db_query_format_free (DB_QUERY_TYPE * query_type)
Definition at line 1723 of file db_query.c.
int db_query_format_is_non_null (DB_QUERY_TYPE * query_type)
Definition at line 1766 of file db_query.c.
char* db_query_format_name (DB_QUERY_TYPE * query_type)
Definition at line 1609 of file db_query.c.
DB_QUERY_TYPE* db_query_format_next (DB_QUERY_TYPE * query_type)
Definition at line 1577 of file db_query.c.
char* db_query_format_original_name (DB_QUERY_TYPE * query_type)
Definition at line 1648 of file db_query.c.
int db_query_format_size (DB_QUERY_TYPE * query_type)
Definition at line 1704 of file db_query.c.
char* db_query_format_spec_name (DB_QUERY_TYPE * query_type)
Definition at line 1635 of file db_query.c.
DB_TYPE db_query_format_type (DB_QUERY_TYPE * query_type)
Definition at line 1690 of file db_query.c.
int db_query_get_tuple_oid (DB_QUERY_RESULT * result, DB_VALUE * db_value)
Definition at line 3195 of file db_query.c.
int db_query_get_tuple_value (DB_QUERY_RESULT * result, int tuple_index, DB_VALUE * value)
Definition at line 2873 of file db_query.c.
int db_query_get_tuple_value_by_name (DB_QUERY_RESULT * result, char * column_name, DB_VALUE * value)
Definition at line 2959 of file db_query.c.
int db_query_get_tuple_valuelist (DB_QUERY_RESULT * result, int size, DB_VALUE * value_list)
Definition at line 3025 of file db_query.c.
int db_query_last_tuple (DB_QUERY_RESULT * result)
Definition at line 2374 of file db_query.c.
int db_query_next_tuple (DB_QUERY_RESULT * result)
Definition at line 2088 of file db_query.c.
int db_query_plan_dump_file (char * filename)
Definition at line 3541 of file db_query.c.
int db_query_prefetch_columns (DB_QUERY_RESULT * result, int * columns, int col_count)
Definition at line 3520 of file db_query.c.
int db_query_prev_tuple (DB_QUERY_RESULT * result)
Definition at line 2196 of file db_query.c.
int db_query_produce_updatable_result (DB_SESSION * session, int stmtid)
Definition at line 3825 of file db_vdb.c.
int db_query_set_copy_tplvalue (DB_QUERY_RESULT * result, int copy)
Definition at line 3386 of file db_query.c.
DB_QUERY_SPEC* db_query_spec_next (DB_QUERY_SPEC * query_spec)
Definition at line 632 of file db_virt.c.
const char* db_query_spec_string (DB_QUERY_SPEC * query_spec)
Definition at line 651 of file db_virt.c.
int db_query_tuple_count (DB_QUERY_RESULT * result)
Definition at line 3089 of file db_query.c.
DB_OBJECT* db_real_instance (DB_OBJECT * obj)
Definition at line 247 of file db_virt.c.
db_error_log_handler_t db_register_error_log_handler (db_error_log_handler_t f)
Definition at line 2183 of file db_admin.c.
References er_register_log_handler().
Referenced by cas_log_error_handler_begin(), and cas_log_error_handler_end().
int db_rename (DB_OBJECT * classobj, const char * name, int class_namespace, const char * newname)
int db_rename_attribute (DB_OBJECT * classobj, const char * name, int class_attribute, const char * newname)
int db_rename_class (DB_OBJECT * classobj, const char * new_name)
int db_rename_method (DB_OBJECT * classobj, const char * name, int class_method, const char * newname)
int db_rename_trigger (DB_OBJECT * obj, const char * newname)
Definition at line 1346 of file db_obj.c.
int db_reset_latest_query_status (void)
Definition at line 1132 of file db_admin.c.
int db_reset_system_parameters_from_assignments (const char * data)
Definition at line 2742 of file db_admin.c.
References db_set_system_parameters(), error(), NO_ERROR, PRM_ERR_NO_ERROR, rc, sysprm_make_default_values(), and sysprm_set_error().
Referenced by la_apply_statement_log().
const char* db_resolution_alias (DB_RESOLUTION * resolution)
Definition at line 1862 of file db_info.c.
DB_OBJECT* db_resolution_class (DB_RESOLUTION * resolution)
Definition at line 1823 of file db_info.c.
int db_resolution_isclass (DB_RESOLUTION * resolution)
Definition at line 1882 of file db_info.c.
const char* db_resolution_name (DB_RESOLUTION * resolution)
Definition at line 1843 of file db_info.c.
DB_RESOLUTION* db_resolution_next (DB_RESOLUTION * resolution)
Definition at line 1799 of file db_info.c.
int db_restart (const char * program, int print_version, const char * volume)
Definition at line 868 of file db_admin.c.
int db_restart_ex (const char * program, const char * db_name, const char * db_user, const char * db_password, const char * preferred_hosts, int client_type)
Definition at line 934 of file db_admin.c.
int db_revoke (DB_OBJECT * user, DB_OBJECT * classobj, DB_AUTH auth)
void db_rewind_statement (DB_SESSION * session)
Definition at line 785 of file db_vdb.c.
int db_savepoint_transaction (const char * savepoint_name)
Definition at line 1198 of file db_admin.c.
int db_send (DB_OBJECT * obj, const char * name, DB_VALUE * returnval, ...)
int db_send_argarray (DB_OBJECT * obj, const char * name, DB_VALUE * returnval, DB_VALUE ** args)
int db_send_arglist (DB_OBJECT * obj, const char * name, DB_VALUE * returnval, DB_VALUE_LIST * args)
int db_session_is_last_statement (DB_SESSION * session)
Definition at line 799 of file db_vdb.c.
References assert, db_session::dimension, and db_session::stmt_ndx.
Referenced by db_set_statement_auto_commit().
void db_session_set_holdable (DB_SESSION * session, bool holdable)
Definition at line 1040 of file db_vdb.c.
References parser_context::flag, parser_context::is_holdable, NULL, and db_session::parser.
Referenced by ux_execute(), and ux_execute_all().
void db_session_set_return_generated_keys (DB_SESSION * session, bool return_generated_keys)
Definition at line 1075 of file db_vdb.c.
References parser_context::flag, NULL, db_session::parser, and parser_context::return_generated_keys.
Referenced by ux_execute(), and ux_execute_all().
void db_session_set_xasl_cache_pinned (DB_SESSION * session, bool is_pinned, bool recompile)
Definition at line 1057 of file db_vdb.c.
References parser_context::flag, parser_context::is_xasl_pinned_reference, NULL, db_session::parser, and parser_context::recompile_xasl_pinned.
Referenced by ux_execute(), ux_execute_all(), ux_execute_array(), and ux_prepare().
int db_set_argument_domain (DB_OBJECT * classobj, const char * name, int class_method, int arg_index, const char * domain)
int db_set_class_method_arg_domain (DB_OBJECT * classobj, const char * name, int arg_index, const char * domain)
Definition at line 1024 of file db_class.c.
int db_set_client_cache_time (DB_SESSION * session, int stmt_ndx, CACHE_TIME * cache_time)
Definition at line 813 of file db_vdb.c.
void db_set_client_type (int client_type)
Definition at line 495 of file db_admin.c.
void db_set_connect_order (int connect_order)
Definition at line 522 of file db_admin.c.
References db_Connect_order.
Referenced by ux_database_connect().
void db_set_connected_host_status (char * host_connected)
Definition at line 681 of file db_admin.c.
int db_set_global_transaction_info (int gtrid, void * info, int size)
Definition at line 1262 of file db_admin.c.
void db_set_host_status (char * hostname, int status)
Definition at line 649 of file db_admin.c.
void db_set_interrupt (int set)
Definition at line 1445 of file db_admin.c.
int db_set_isolation (DB_TRAN_ISOLATION isolation)
Definition at line 1535 of file db_admin.c.
int db_set_loader_commands (DB_OBJECT * classobj, const char * commands)
int db_set_lock_timeout (int seconds)
Definition at line 1496 of file db_admin.c.
void db_set_max_num_delayed_hosts_lookup (int max_num_delayed_hosts_lookup)
Definition at line 528 of file db_admin.c.
References db_Max_num_delayed_hosts_lookup.
Referenced by ux_database_connect().
int db_set_method_arg_domain (DB_OBJECT * classobj, const char * name, int arg_index, const char * domain)
Definition at line 1006 of file db_class.c.
int db_set_password (DB_OBJECT * user, const char * oldpass, const char * newpass)
Definition at line 1743 of file db_admin.c.
void db_set_preferred_hosts (const char * hosts)
Definition at line 508 of file db_admin.c.
void db_set_read_fetch_instance_version (LC_FETCH_VERSION_TYPE read_Fetch_Instance_Version)
Definition at line 3904 of file db_vdb.c.
References tm_Tran_read_fetch_instance_version.
Referenced by au_is_dba_group_member(), csql_help_trigger(), db_compile_and_execute_queries_internal(), db_execute_and_keep_statement(), db_execute_statement(), do_execute_statement(), do_statement(), and sm_active_triggers().
void db_set_server_session_key (const char * key)
Definition at line 2843 of file db_admin.c.
References boot_set_server_session_key().
Referenced by cas_set_session_id().
void db_set_session_id (const SESSION_ID session_id)
Definition at line 2870 of file db_admin.c.
int db_set_statement_auto_commit (DB_SESSION * session, bool auto_commit)
Definition at line 4030 of file db_vdb.c.
References ARG_FILE_LINE, assert, db_can_execute_statement_with_autocommit(), db_session_is_last_statement(), db_session::dimension, er_errid(), ER_IT_EMPTY_STATEMENT, ER_IT_INVALID_SESSION, ER_OBJ_INVALID_ARGUMENTS, er_set(), ER_WARNING_SEVERITY, parser_node::flag, parser_context::flag, i, parser_context::is_auto_commit, parser_context::is_holdable, NO_ERROR, parser_node::node_type, NULL, db_session::parser, PT_IS_QUERY_NODE_TYPE, db_session::stage, StatementPreparedStage, db_session::statements, db_session::stmt_ndx, tr_has_user_trigger(), and parser_node::use_auto_commit.
Referenced by csql_execute_statements(), ux_execute(), ux_execute_all(), ux_execute_array(), and ux_execute_batch().
int db_set_suppress_repl_on_transaction (int set)
Definition at line 1460 of file db_admin.c.
int db_set_system_parameters (const char * data)
Definition at line 2682 of file db_admin.c.
int db_set_system_parameters_for_ha_repl (const char * data)
Definition at line 2727 of file db_admin.c.
References db_set_system_parameters().
Referenced by la_apply_statement_log().
int db_set_user_comment (DB_OBJECT * user, const char * comment)
Definition at line 1765 of file db_admin.c.
int db_shutdown (void)
Definition at line 964 of file db_admin.c.
int db_statement_count (DB_SESSION * session)
Definition at line 132 of file db_vdb.c.
void db_string_free (char * string)
Definition at line 2596 of file db_admin.c.
void db_synchronize_cache (void)
Definition at line 1586 of file db_admin.c.
int db_totalpgs (const char * vlabel)
Definition at line 2073 of file db_admin.c.
int db_trigger_action (DB_OBJECT * trobj, char ** action)
Definition at line 1742 of file db_obj.c.
int db_trigger_action_time (DB_OBJECT * trobj, DB_TRIGGER_TIME * tr_time)
Definition at line 1724 of file db_obj.c.
int db_trigger_action_type (DB_OBJECT * trobj, DB_TRIGGER_ACTION * type)
Definition at line 1705 of file db_obj.c.
int db_trigger_attribute (DB_OBJECT * trobj, char ** attr)
Definition at line 1643 of file db_obj.c.
int db_trigger_class (DB_OBJECT * trobj, DB_OBJECT ** class_obj)
Definition at line 1623 of file db_obj.c.
int db_trigger_comment (DB_OBJECT * trobj, char ** comment)
Definition at line 1763 of file db_obj.c.
int db_trigger_condition (DB_OBJECT * trobj, char ** condition)
Definition at line 1663 of file db_obj.c.
int db_trigger_condition_time (DB_OBJECT * trobj, DB_TRIGGER_TIME * tr_time)
Definition at line 1683 of file db_obj.c.
int db_trigger_event (DB_OBJECT * trobj, DB_TRIGGER_EVENT * event)
Definition at line 1603 of file db_obj.c.
int db_trigger_name (DB_OBJECT * trobj, char ** name)
Definition at line 1548 of file db_obj.c.
int db_trigger_priority (DB_OBJECT * trobj, double * priority)
Definition at line 1585 of file db_obj.c.
int db_trigger_status (DB_OBJECT * trobj, DB_TRIGGER_STATUS * status)
Definition at line 1567 of file db_obj.c.
int db_truncate_class (DB_OBJECT * classobj)
Definition at line 1859 of file db_class.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, NO_ERROR, and sm_truncate_class().
Referenced by synccoll_force(), and truncate_class_name().
DB_TYPE db_type_from_string (const char * name)
Definition at line 742 of file db_info.c.
void db_unlink_static_methods (DB_METHOD_LINK * methods)
Definition at line 2546 of file db_admin.c.
void db_update_row_count_cache (const int row_count)
Definition at line 2924 of file db_admin.c.
int db_validate (DB_OBJECT * vclass)
Definition at line 3573 of file db_vdb.c.
int db_validate_query_spec (DB_OBJECT * vclass, const char * query_spec)
Definition at line 3441 of file db_vdb.c.
char* db_vol_label (int volid, char * vol_fullname)
Definition at line 412 of file db_admin.c.
void db_warnspace (const char * vlabel)
Definition at line 2452 of file db_admin.c.
void dbt_abort_class (DB_CTMPL * def)
Definition at line 249 of file db_temp.c.
void dbt_abort_object (DB_OTMPL * def)
Definition at line 616 of file db_obj.c.
int dbt_add_argument (DB_CTMPL * def, const char * name, int class_method, int arg_index, const char * domain)
Definition at line 800 of file db_temp.c.
int dbt_add_attribute (DB_CTMPL * def, const char * name, const char * domain, DB_VALUE * default_value)
Definition at line 272 of file db_temp.c.
int dbt_add_class_attribute (DB_CTMPL * def, const char * name, const char * domain, DB_VALUE * default_value)
Definition at line 317 of file db_temp.c.
int dbt_add_class_method (DB_CTMPL * def, const char * name, const char * implementation)
Definition at line 777 of file db_temp.c.
int dbt_add_class_resolution (DB_CTMPL * def, DB_OBJECT * super, const char * name, const char * alias)
int dbt_add_constraint (DB_CTMPL * def, DB_CONSTRAINT_TYPE constraint_type, const char * constraint_name, const char ** attnames, int class_attributes, const char * comment)
Definition at line 423 of file db_temp.c.
int dbt_add_foreign_key (DB_CTMPL * def, const char * constraint_name, const char ** attnames, const char * ref_class, const char ** ref_attrs, int del_action, int upd_action, const char * comment)
Definition at line 524 of file db_temp.c.
int dbt_add_method (DB_CTMPL * def, const char * name, const char * implementation)
Definition at line 756 of file db_temp.c.
int dbt_add_method_file (DB_CTMPL * def, const char * name)
Definition at line 1015 of file db_temp.c.
int dbt_add_query_spec (DB_CTMPL * def, const char * query)
Definition at line 1201 of file db_temp.c.
int dbt_add_resolution (DB_CTMPL * def, DB_OBJECT * super, const char * name, const char * alias)
int dbt_add_set_argument_domain (DB_CTMPL * def, const char * name, int class_method, int arg_index, const char * domain)
Definition at line 823 of file db_temp.c.
int dbt_add_set_attribute_domain (DB_CTMPL * def, const char * name, int class_attribute, const char * domain)
Definition at line 569 of file db_temp.c.
int dbt_add_shared_attribute (DB_CTMPL * def, const char * name, const char * domain, DB_VALUE * default_value)
Definition at line 294 of file db_temp.c.
int dbt_add_super (DB_CTMPL * def, DB_OBJECT * super)
int dbt_change_default (DB_CTMPL * def, const char * name, int class_attribute, DB_VALUE * value)
Definition at line 611 of file db_temp.c.
int dbt_change_domain (DB_CTMPL * def, const char * name, int class_attribute, const char * domain)
Definition at line 591 of file db_temp.c.
int dbt_change_method_implementation (DB_CTMPL * def, const char * name, int class_method, const char * newname)
Definition at line 845 of file db_temp.c.
int dbt_change_query_spec (DB_CTMPL * def, const char * new_query, const int query_no)
Definition at line 1261 of file db_temp.c.
int dbt_constrain_non_null (DB_CTMPL * def, const char * name, int class_attribute, int on_or_off)
Definition at line 344 of file db_temp.c.
int dbt_constrain_unique (DB_CTMPL * def, const char * name, int on_or_off)
Definition at line 382 of file db_temp.c.
DB_CTMPL* dbt_copy_class (const char * new_name, const char * existing_name, SM_CLASS ** class_)
Definition at line 160 of file db_temp.c.
References CHECK_2ARGS_NULL, CHECK_CONNECT_NULL, CHECK_MODIFICATION_NULL, dbt_reserve_name(), NULL, and smt_copy_class().
Referenced by do_create_entity().
DB_CTMPL* dbt_create_class (const char * name)
Definition at line 76 of file db_temp.c.
DB_OTMPL* dbt_create_object (DB_OBJECT * classobj)
DB_CTMPL* dbt_create_vclass (const char * name)
Definition at line 104 of file db_temp.c.
int dbt_dput (DB_OTMPL * def, DB_ATTDESC * attribute, DB_VALUE * value)
Definition at line 953 of file db_obj.c.
int dbt_drop_attribute (DB_CTMPL * def, const char * name)
Definition at line 653 of file db_temp.c.
int dbt_drop_class_attribute (DB_CTMPL * def, const char * name)
Definition at line 734 of file db_temp.c.
int dbt_drop_class_method (DB_CTMPL * def, const char * name)
Definition at line 885 of file db_temp.c.
int dbt_drop_class_resolution (DB_CTMPL * def, DB_OBJECT * super, const char * name)
int dbt_drop_constraint (DB_CTMPL * def, DB_CONSTRAINT_TYPE constraint_type, const char * constraint_name, const char ** attnames, int class_attributes)
Definition at line 473 of file db_temp.c.
int dbt_drop_method (DB_CTMPL * def, const char * name)
Definition at line 865 of file db_temp.c.
int dbt_drop_method_file (DB_CTMPL * def, const char * name)
Definition at line 1035 of file db_temp.c.
int dbt_drop_method_files (DB_CTMPL * def)
Definition at line 1054 of file db_temp.c.
int dbt_drop_query_spec (DB_CTMPL * def, const int query_no)
Definition at line 1221 of file db_temp.c.
int dbt_drop_resolution (DB_CTMPL * def, DB_OBJECT * super, const char * name)
int dbt_drop_set_attribute_domain (DB_CTMPL * def, const char * name, int class_attribute, const char * domain)
Definition at line 633 of file db_temp.c.
int dbt_drop_shared_attribute (DB_CTMPL * def, const char * name)
Definition at line 714 of file db_temp.c.
int dbt_drop_super (DB_CTMPL * def, DB_OBJECT * super)
int dbt_drop_super_connect (DB_CTMPL * def, DB_OBJECT * super)
DB_CTMPL* dbt_edit_class (DB_OBJECT * classobj)
DB_OTMPL* dbt_edit_object (DB_OBJECT * object)
DB_OBJECT* dbt_finish_class (DB_CTMPL * def)
Definition at line 226 of file db_temp.c.
DB_OBJECT* dbt_finish_object (DB_OTMPL * def)
Definition at line 560 of file db_obj.c.
DB_OBJECT* dbt_finish_object_and_decache_when_failure (DB_OTMPL * def)
Definition at line 583 of file db_obj.c.
int dbt_put (DB_OTMPL * def, const char * name, DB_VALUE * value)
Definition at line 635 of file db_obj.c.
int dbt_rename (DB_CTMPL * def, const char * name, int class_namespace, const char * newname)
Definition at line 967 of file db_temp.c.
int dbt_rename_method_file (DB_CTMPL * def, const char * new_name, const char * old_name)
Definition at line 1075 of file db_temp.c.
int dbt_reset_query_spec (DB_CTMPL * def)
Definition at line 1240 of file db_temp.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, error(), NO_ERROR, and smt_reset_query_spec().
Referenced by do_alter_one_clause_with_template().
int dbt_set_label (DB_OTMPL * def, DB_VALUE * label)
Definition at line 713 of file db_obj.c.
int dbt_set_loader_commands (DB_CTMPL * def, const char * commands)
Definition at line 1095 of file db_temp.c.
int dbt_set_object_id (DB_CTMPL * def, DB_NAMELIST * id_list)
Definition at line 1281 of file db_temp.c.