CUBRID Engine: src/compat/dbi_compat.h File Reference
dbi_compat.h File Reference
#include <stdio.h>
#include <time.h>
#include <sys/types.h>
#include "dbtran_def.h"
#include "dbtype_def.h"
#include "error_code.h"
#include "dbtype_function.h"
#include "db_date.h"
#include "db_elo.h"
#include "cache_time.h"
Macros
#define bool char
#define DB_TRUE 1
#define DB_FALSE 0
#define SQLX_CMD_TYPE CUBRID_STMT_TYPE
#define SQLX_CMD_ALTER_CLASS CUBRID_STMT_ALTER_CLASS
#define SQLX_CMD_ALTER_SERIAL CUBRID_STMT_ALTER_SERIAL
#define SQLX_CMD_COMMIT_WORK CUBRID_STMT_COMMIT_WORK
#define SQLX_CMD_REGISTER_DATABASE CUBRID_STMT_REGISTER_DATABASE
#define SQLX_CMD_CREATE_CLASS CUBRID_STMT_CREATE_CLASS
#define SQLX_CMD_CREATE_INDEX CUBRID_STMT_CREATE_INDEX
#define SQLX_CMD_CREATE_TRIGGER CUBRID_STMT_CREATE_TRIGGER
#define SQLX_CMD_CREATE_SERIAL CUBRID_STMT_CREATE_SERIAL
#define SQLX_CMD_DROP_DATABASE CUBRID_STMT_DROP_DATABASE
#define SQLX_CMD_DROP_CLASS CUBRID_STMT_DROP_CLASS
#define SQLX_CMD_DROP_INDEX CUBRID_STMT_DROP_INDEX
#define SQLX_CMD_DROP_LABEL CUBRID_STMT_DROP_LABEL
#define SQLX_CMD_DROP_TRIGGER CUBRID_STMT_DROP_TRIGGER
#define SQLX_CMD_DROP_SERIAL CUBRID_STMT_DROP_SERIAL
#define SQLX_CMD_EVALUATE CUBRID_STMT_EVALUATE
#define SQLX_CMD_RENAME_CLASS CUBRID_STMT_RENAME_CLASS
#define SQLX_CMD_ROLLBACK_WORK CUBRID_STMT_ROLLBACK_WORK
#define SQLX_CMD_GRANT CUBRID_STMT_GRANT
#define SQLX_CMD_REVOKE CUBRID_STMT_REVOKE
#define SQLX_CMD_UPDATE_STATS CUBRID_STMT_UPDATE_STATS
#define SQLX_CMD_INSERT CUBRID_STMT_INSERT
#define SQLX_CMD_SELECT CUBRID_STMT_SELECT
#define SQLX_CMD_UPDATE CUBRID_STMT_UPDATE
#define SQLX_CMD_DELETE CUBRID_STMT_DELETE
#define SQLX_CMD_CALL CUBRID_STMT_CALL
#define SQLX_CMD_GET_ISO_LVL CUBRID_STMT_GET_ISO_LVL
#define SQLX_CMD_GET_TIMEOUT CUBRID_STMT_GET_TIMEOUT
#define SQLX_CMD_GET_OPT_LVL CUBRID_STMT_GET_OPT_LVL
#define SQLX_CMD_SET_OPT_LVL CUBRID_STMT_SET_OPT_LVL
#define SQLX_CMD_SCOPE CUBRID_STMT_SCOPE
#define SQLX_CMD_GET_TRIGGER CUBRID_STMT_GET_TRIGGER
#define SQLX_CMD_SET_TRIGGER CUBRID_STMT_SET_TRIGGER
#define SQLX_CMD_SAVEPOINT CUBRID_STMT_SAVEPOINT
#define SQLX_CMD_PREPARE CUBRID_STMT_PREPARE
#define SQLX_CMD_ATTACH CUBRID_STMT_ATTACH
#define SQLX_CMD_USE CUBRID_STMT_USE
#define SQLX_CMD_REMOVE_TRIGGER CUBRID_STMT_REMOVE_TRIGGER
#define SQLX_CMD_RENMAE_TRIGGER CUBRID_STMT_RENAME_TRIGGER
#define SQLX_CMD_ON_LDB CUBRID_STMT_ON_LDB
#define SQLX_CMD_GET_LDB CUBRID_STMT_GET_LDB
#define SQLX_CMD_SET_LDB CUBRID_STMT_SET_LDB
#define SQLX_CMD_GET_STATS CUBRID_STMT_GET_STATS
#define SQLX_CMD_CREATE_USER CUBRID_STMT_CREATE_USER
#define SQLX_CMD_DROP_USER CUBRID_STMT_DROP_USER
#define SQLX_CMD_ALTER_USER CUBRID_STMT_ALTER_USER
#define SQLX_CMD_SET_SYS_PARAMS CUBRID_STMT_SET_SYS_PARAMS
#define SQLX_CMD_ALTER_INDEX CUBRID_STMT_ALTER_INDEX
#define SQLX_CMD_CREATE_STORED_PROCEDURE CUBRID_STMT_CREATE_STORED_PROCEDURE
#define SQLX_CMD_DROP_STORED_PROCEDURE CUBRID_STMT_DROP_STORED_PROCEDURE
#define SQLX_CMD_PREPARE_STATEMENT CUBRID_STMT_PREPARE_STATEMENT
#define SQLX_CMD_EXECUTE_PREPARE CUBRID_STMT_EXECUTE_PREPARE
#define SQLX_CMD_DEALLOCATE_PREPARE CUBRID_STMT_DEALLOCATE_PREPARE
#define SQLX_CMD_TRUNCATE CUBRID_STMT_TRUNCATE
#define SQLX_CMD_DO CUBRID_STMT_DO
#define SQLX_CMD_SELECT_UPDATE CUBRID_STMT_SELECT_UPDATE
#define SQLX_CMD_SET_SESSION_VARIABLES CUBRID_STMT_SET_SESSION_VARIABLES
#define SQLX_CMD_DROP_SESSION_VARIABLES CUBRID_STMT_DROP_SESSION_VARIABLES
#define SQLX_CMD_STMT_MERGE CUBRID_STMT_MERGE
#define SQLX_CMD_SET_NAMES CUBRID_STMT_SET_NAMES
#define SQLX_CMD_ALTER_STORED_PROCEDURE CUBRID_STMT_ALTER_STORED_PROCEDURE
#define SQLX_CMD_ALTER_STORED_PROCEDURE_OWNER CUBRID_STMT_ALTER_STORED_PROCEDURE
#define SQLX_MAX_CMD_TYPE CUBRID_MAX_STMT_TYPE
#define SQLX_CMD_CALL_SP CUBRID_STMT_CALL_SP
#define SQLX_CMD_UNKNOWN CUBRID_STMT_UNKNOWN
Enumerations
enum { DB_NO_OIDS, DB_ROW_OIDS, DB_COLUMN_OIDS }
Functions
bool db_is_client_cache_reusable (DB_QUERY_RESULT *result)
int db_query_seek_tuple (DB_QUERY_RESULT *result, int offset, int seek_mode)
int db_query_get_cache_time (DB_QUERY_RESULT *result, CACHE_TIME *cache_time)
void db_objlist_free (DB_OBJLIST *list)
void db_string_free (char *string)
int db_auth_login (char *signed_data, int len)
int db_auth_logout (void)
int db_login (const char *name, const char *password)
int db_restart (const char *program, int print_version, const char *volume)
int db_restart_ex (const char *program, const char *db_name, const char *db_user, const char *db_password, const char *preferred_hosts, int client_type)
SESSION_ID db_get_session_id (void)
void db_set_session_id (const SESSION_ID session_id)
int db_end_session (void)
int db_find_or_create_session (const char *db_user, const char *program_name)
int db_get_row_count_cache (void)
void db_update_row_count_cache (const int row_count)
int db_get_row_count (int *row_count)
int db_get_last_insert_id (DB_VALUE *value)
int db_get_variable (DB_VALUE *name, DB_VALUE *value)
int db_shutdown (void)
int db_ping_server (int client_val, int *server_val)
int db_disable_modification (void)
int db_enable_modification (void)
int db_commit_transaction (void)
int db_abort_transaction (void)
int db_reset_latest_query_status (void)
int db_commit_is_needed (void)
int db_savepoint_transaction (const char *savepoint_name)
int db_abort_to_savepoint (const char *savepoint_name)
int db_set_global_transaction_info (int gtrid, void *info, int size)
int db_get_global_transaction_info (int gtrid, void *buffer, int size)
int db_2pc_start_transaction (void)
int db_2pc_prepare_transaction (void)
int db_2pc_prepared_transactions (int gtrids[], int size)
int db_2pc_prepare_to_commit_transaction (int gtrid)
int db_2pc_attach_transaction (int gtrid)
void db_set_interrupt (int set)
int db_set_suppress_repl_on_transaction (int set)
int db_freepgs (const char *vlabel)
int db_totalpgs (const char *vlabel)
char * db_vol_label (int volid, char *vol_fullname)
void db_warnspace (const char *vlabel)
int db_add_volume (const char *ext_path, const char *ext_name, const char *ext_comments, const int ext_npages, const DB_VOLPURPOSE ext_purpose)
int db_num_volumes (void)
void db_print_stats (void)
void db_preload_classes (const char *name1,...)
void db_link_static_methods (DB_METHOD_LINK *methods)
void db_unlink_static_methods (DB_METHOD_LINK *methods)
void db_flush_static_methods (void)
const char * db_error_string (int level)
int db_error_code (void)
int db_error_init (const char *logfile)
int db_set_lock_timeout (int seconds)
int db_set_isolation (DB_TRAN_ISOLATION isolation)
void db_synchronize_cache (void)
void db_get_tran_settings (int *lock_wait, DB_TRAN_ISOLATION *tran_isolation)
DB_OBJECT * db_get_user (void)
DB_OBJECT * db_get_owner (DB_OBJECT *classobj)
char * db_get_user_name (void)
char * db_get_user_and_host_name (void)
DB_OBJECT * db_find_user (const char *name)
int db_find_user_to_drop (const char *name, DB_OBJECT **user)
DB_OBJECT * db_add_user (const char *name, int *exists)
int db_drop_user (DB_OBJECT *user)
int db_add_member (DB_OBJECT *user, DB_OBJECT *member)
int db_drop_member (DB_OBJECT *user, DB_OBJECT *member)
int db_set_password (DB_OBJECT *user, const char *oldpass, const char *newpass)
int db_set_user_comment (DB_OBJECT *user, const char *comment)
int db_grant (DB_OBJECT *user, DB_OBJECT *classobj, DB_AUTH auth, int grant_option)
int db_revoke (DB_OBJECT *user, DB_OBJECT *classobj, DB_AUTH auth)
int db_check_authorization (DB_OBJECT *op, DB_AUTH auth)
int db_check_authorization_and_grant_option (MOP op, DB_AUTH auth)
int db_get_class_privilege (DB_OBJECT *op, unsigned int *auth)
int db_get_serial_current_value (const char *serial_name, DB_VALUE *serial_value)
int db_get_serial_next_value (const char *serial_name, DB_VALUE *serial_value)
int db_get_serial_next_value_ex (const char *serial_name, DB_VALUE *serial_value, int num_alloc)
DB_OBJECT * db_create (DB_OBJECT *obj)
DB_OBJECT * db_create_by_name (const char *name)
int db_get (DB_OBJECT *object, const char *attpath, DB_VALUE *value)
int db_put (DB_OBJECT *obj, const char *name, DB_VALUE *value)
int db_drop (DB_OBJECT *obj)
int db_get_expression (DB_OBJECT *object, const char *expression, DB_VALUE *value)
void db_print (DB_OBJECT *obj)
void db_fprint (FILE *fp, DB_OBJECT *obj)
DB_OBJECT * db_find_unique (DB_OBJECT *classobj, const char *attname, DB_VALUE *value)
DB_OBJECT * db_find_unique_write_mode (DB_OBJECT *classobj, const char *attname, DB_VALUE *value)
DB_OBJECT * db_find_multi_unique (DB_OBJECT *classobj, int size, char *attnames[], DB_VALUE *values[], DB_FETCH_MODE purpose)
DB_OBJECT * db_dfind_unique (DB_OBJECT *classobj, DB_ATTDESC *attdesc, DB_VALUE *value, DB_FETCH_MODE purpose)
DB_OBJECT * db_dfind_multi_unique (DB_OBJECT *classobj, int size, DB_ATTDESC *attdesc[], DB_VALUE *values[], DB_FETCH_MODE purpose)
DB_OBJECT * db_find_primary_key (MOP classmop, const DB_VALUE **values, int size, DB_FETCH_MODE purpose)
int db_send (DB_OBJECT *obj, const char *name, DB_VALUE *returnval,...)
int db_send_arglist (DB_OBJECT *obj, const char *name, DB_VALUE *returnval, DB_VALUE_LIST *args)
int db_send_argarray (DB_OBJECT *obj, const char *name, DB_VALUE *returnval, DB_VALUE **args)
int db_lock_read (DB_OBJECT *op)
int db_lock_write (DB_OBJECT *op)
int db_fetch_array (DB_OBJECT **objects, DB_FETCH_MODE mode, int quit_on_error)
int db_fetch_list (DB_OBJLIST *objects, DB_FETCH_MODE mode, int quit_on_error)
int db_fetch_set (DB_COLLECTION *set, DB_FETCH_MODE mode, int quit_on_error)
int db_fetch_seq (DB_SEQ *set, DB_FETCH_MODE mode, int quit_on_error)
int db_fetch_composition (DB_OBJECT *object, DB_FETCH_MODE mode, int max_level, int quit_on_error)
DB_OBJECT * db_create_class (const char *name)
DB_OBJECT * db_create_vclass (const char *name)
int db_drop_class (DB_OBJECT *classobj)
int db_drop_class_ex (DB_OBJECT *classobj, bool is_cascade_constraints)
int db_rename_class (DB_OBJECT *classobj, const char *new_name)
int db_add_index (DB_OBJECT *classobj, const char *attname)
int db_drop_index (DB_OBJECT *classobj, const char *attname)
int db_add_super (DB_OBJECT *classobj, DB_OBJECT *super)
int db_drop_super (DB_OBJECT *classobj, DB_OBJECT *super)
int db_drop_super_connect (DB_OBJECT *classobj, DB_OBJECT *super)
int db_rename (DB_OBJECT *classobj, const char *name, int class_namespace, const char *newname)
int db_add_attribute (DB_OBJECT *obj, const char *name, const char *domain, DB_VALUE *default_value)
int db_add_shared_attribute (DB_OBJECT *obj, const char *name, const char *domain, DB_VALUE *default_value)
int db_add_class_attribute (DB_OBJECT *obj, const char *name, const char *domain, DB_VALUE *default_value)
int db_add_set_attribute_domain (DB_OBJECT *classobj, const char *name, int class_attribute, const char *domain)
int db_drop_attribute (DB_OBJECT *classobj, const char *name)
int db_drop_class_attribute (DB_OBJECT *classobj, const char *name)
int db_change_default (DB_OBJECT *classobj, const char *name, DB_VALUE *value)
int db_constrain_non_null (DB_OBJECT *classobj, const char *name, int class_attribute, int on_or_off)
int db_constrain_unique (DB_OBJECT *classobj, const char *name, int on_or_off)
int db_add_method (DB_OBJECT *classobj, const char *name, const char *implementation)
int db_add_class_method (DB_OBJECT *classobj, const char *name, const char *implementation)
int db_drop_method (DB_OBJECT *classobj, const char *name)
int db_drop_class_method (DB_OBJECT *classobj, const char *name)
int db_add_argument (DB_OBJECT *classobj, const char *name, int class_method, int arg_index, const char *domain)
int db_add_set_argument_domain (DB_OBJECT *classobj, const char *name, int class_method, int arg_index, const char *domain)
int db_change_method_implementation (DB_OBJECT *classobj, const char *name, int class_method, const char *newname)
int db_set_loader_commands (DB_OBJECT *classobj, const char *commands)
int db_add_method_file (DB_OBJECT *classobj, const char *name)
int db_drop_method_file (DB_OBJECT *classobj, const char *name)
int db_drop_method_files (DB_OBJECT *classobj)
int db_add_resolution (DB_OBJECT *classobj, DB_OBJECT *super, const char *name, const char *alias)
int db_add_class_resolution (DB_OBJECT *classobj, DB_OBJECT *super, const char *name, const char *alias)
int db_drop_resolution (DB_OBJECT *classobj, DB_OBJECT *super, const char *name)
int db_drop_class_resolution (DB_OBJECT *classobj, DB_OBJECT *super, const char *name)
int db_add_constraint (MOP classmop, DB_CONSTRAINT_TYPE constraint_type, const char *constraint_name, const char **att_names, int class_attributes)
int db_drop_constraint (MOP classmop, DB_CONSTRAINT_TYPE constraint_type, const char *constraint_name, const char **att_names, int class_attributes)
char * db_get_database_name (void)
const char * db_get_database_comments (void)
void db_set_client_type (int client_type)
void db_set_preferred_hosts (const char *hosts)
int db_get_client_type (void)
const char * db_get_type_name (DB_TYPE type_id)
DB_TYPE db_type_from_string (const char *name)
int db_get_schema_def_dbval (DB_VALUE *result, DB_VALUE *name_val)
const char * db_default_expression_string (DB_DEFAULT_EXPR_TYPE default_expr_type)
DB_OBJECT * db_find_class_of_index (const char *index, DB_CONSTRAINT_TYPE type)
DB_OBJECT * db_find_class (const char *name)
DB_OBJECT * db_get_class (DB_OBJECT *obj)
DB_OBJLIST * db_get_all_objects (DB_OBJECT *classobj)
DB_OBJLIST * db_get_all_classes (void)
DB_OBJLIST * db_get_base_classes (void)
DB_OBJLIST * db_fetch_all_objects (DB_OBJECT *op, DB_FETCH_MODE mode)
DB_OBJLIST * db_fetch_all_classes (DB_FETCH_MODE mode)
DB_OBJLIST * db_fetch_base_classes (DB_FETCH_MODE mode)
int db_is_class (DB_OBJECT *obj)
int db_is_any_class (DB_OBJECT *obj)
int db_is_instance (DB_OBJECT *obj)
int db_is_instance_of (DB_OBJECT *obj, DB_OBJECT *classobj)
int db_is_subclass (DB_OBJECT *classobj, DB_OBJECT *supermop)
int db_is_superclass (DB_OBJECT *supermop, DB_OBJECT *classobj)
int db_is_partition (DB_OBJECT *classobj, DB_OBJECT *superobj)
int db_is_system_class (DB_OBJECT *op)
int db_is_deleted (DB_OBJECT *obj)
const char * db_get_class_name (DB_OBJECT *classobj)
DB_OBJLIST * db_get_superclasses (DB_OBJECT *obj)
DB_OBJLIST * db_get_subclasses (DB_OBJECT *obj)
DB_ATTRIBUTE * db_get_attribute (DB_OBJECT *obj, const char *name)
DB_ATTRIBUTE * db_get_attribute_by_name (const char *class_name, const char *attribute_name)
DB_ATTRIBUTE * db_get_attributes (DB_OBJECT *obj)
DB_ATTRIBUTE * db_get_class_attribute (DB_OBJECT *obj, const char *name)
DB_ATTRIBUTE * db_get_class_attributes (DB_OBJECT *obj)
DB_METHOD * db_get_method (DB_OBJECT *obj, const char *name)
DB_METHOD * db_get_class_method (DB_OBJECT *obj, const char *name)
DB_METHOD * db_get_methods (DB_OBJECT *obj)
DB_METHOD * db_get_class_methods (DB_OBJECT *obj)
DB_RESOLUTION * db_get_resolutions (DB_OBJECT *obj)
DB_RESOLUTION * db_get_class_resolutions (DB_OBJECT *obj)
DB_METHFILE * db_get_method_files (DB_OBJECT *obj)
const char * db_get_loader_commands (DB_OBJECT *obj)
DB_TYPE db_attribute_type (DB_ATTRIBUTE *attribute)
DB_ATTRIBUTE * db_attribute_next (DB_ATTRIBUTE *attribute)
const char * db_attribute_name (DB_ATTRIBUTE *attribute)
int db_attribute_id (DB_ATTRIBUTE *attribute)
int db_attribute_order (DB_ATTRIBUTE *attribute)
DB_DOMAIN * db_attribute_domain (DB_ATTRIBUTE *attribute)
DB_OBJECT * db_attribute_class (DB_ATTRIBUTE *attribute)
DB_VALUE * db_attribute_default (DB_ATTRIBUTE *attribute)
int db_attribute_is_unique (DB_ATTRIBUTE *attribute)
int db_attribute_is_primary_key (DB_ATTRIBUTE *attribute)
int db_attribute_is_foreign_key (DB_ATTRIBUTE *attribute)
int db_attribute_is_auto_increment (DB_ATTRIBUTE *attribute)
int db_attribute_is_reverse_unique (DB_ATTRIBUTE *attribute)
int db_attribute_is_non_null (DB_ATTRIBUTE *attribute)
int db_attribute_is_indexed (DB_ATTRIBUTE *attribute)
int db_attribute_is_reverse_indexed (DB_ATTRIBUTE *attribute)
int db_attribute_is_shared (DB_ATTRIBUTE *attribute)
int db_attribute_length (DB_ATTRIBUTE *attribute)
DB_DOMAIN * db_type_to_db_domain (DB_TYPE type)
DB_DOMAIN * db_domain_next (const DB_DOMAIN *domain)
DB_TYPE db_domain_type (const DB_DOMAIN *domain)
DB_OBJECT * db_domain_class (const DB_DOMAIN *domain)
DB_DOMAIN * db_domain_set (const DB_DOMAIN *domain)
int db_domain_precision (const DB_DOMAIN *domain)
int db_domain_scale (const DB_DOMAIN *domain)
int db_domain_codeset (const DB_DOMAIN *domain)
const char * db_domain_raw_json_schema (const DB_DOMAIN *domain)
DB_METHOD * db_method_next (DB_METHOD *method)
const char * db_method_name (DB_METHOD *method)
const char * db_method_function (DB_METHOD *method)
DB_OBJECT * db_method_class (DB_METHOD *method)
DB_DOMAIN * db_method_return_domain (DB_METHOD *method)
DB_DOMAIN * db_method_arg_domain (DB_METHOD *method, int arg)
int db_method_arg_count (DB_METHOD *method)
DB_RESOLUTION * db_resolution_next (DB_RESOLUTION *resolution)
DB_OBJECT * db_resolution_class (DB_RESOLUTION *resolution)
const char * db_resolution_name (DB_RESOLUTION *resolution)
const char * db_resolution_alias (DB_RESOLUTION *resolution)
int db_resolution_isclass (DB_RESOLUTION *resolution)
DB_METHFILE * db_methfile_next (DB_METHFILE *methfile)
const char * db_methfile_name (DB_METHFILE *methfile)
DB_OBJLIST * db_objlist_next (DB_OBJLIST *link)
DB_OBJECT * db_objlist_object (DB_OBJLIST *link)
int db_get_class_num_objs_and_pages (DB_OBJECT *classmop, int approximation, int *nobjs, int *npages)
int db_get_btree_statistics (DB_CONSTRAINT *cons, int *num_leaf_pages, int *num_total_pages, int *num_keys, int *height)
DB_CONSTRAINT * db_get_constraints (DB_OBJECT *obj)
DB_CONSTRAINT * db_constraint_next (DB_CONSTRAINT *constraint)
DB_CONSTRAINT * db_constraint_find_primary_key (DB_CONSTRAINT *constraint)
DB_CONSTRAINT_TYPE db_constraint_type (DB_CONSTRAINT *constraint)
const char * db_constraint_name (DB_CONSTRAINT *constraint)
DB_ATTRIBUTE ** db_constraint_attributes (DB_CONSTRAINT *constraint)
const int * db_constraint_asc_desc (DB_CONSTRAINT *constraint)
const char * db_get_foreign_key_action (DB_CONSTRAINT *constraint, DB_FK_ACTION_TYPE type)
DB_OBJECT * db_get_foreign_key_ref_class (DB_CONSTRAINT *constraint)
DB_OBJECT * db_create_trigger (const char *name, DB_TRIGGER_STATUS status, double priority, DB_TRIGGER_EVENT event, DB_OBJECT *class_obj, const char *attr, DB_TRIGGER_TIME cond_time, const char *cond_source, DB_TRIGGER_TIME action_time, DB_TRIGGER_ACTION action_type, const char *action_source)
int db_drop_trigger (DB_OBJECT *obj)
int db_rename_trigger (DB_OBJECT *obj, const char *newname)
DB_OBJECT * db_find_trigger (const char *name)
int db_find_all_triggers (DB_OBJLIST **list)
int db_find_event_triggers (DB_TRIGGER_EVENT event, DB_OBJECT *class_obj, const char *attr, DB_OBJLIST **list)
int db_alter_trigger_priority (DB_OBJECT *trobj, double priority)
int db_alter_trigger_status (DB_OBJECT *trobj, DB_TRIGGER_STATUS status)
int db_execute_deferred_activities (DB_OBJECT *trigger_obj, DB_OBJECT *target)
int db_drop_deferred_activities (DB_OBJECT *trigger_obj, DB_OBJECT *target)
int db_trigger_name (DB_OBJECT *trobj, char **name)
int db_trigger_status (DB_OBJECT *trobj, DB_TRIGGER_STATUS *status)
int db_trigger_priority (DB_OBJECT *trobj, double *priority)
int db_trigger_event (DB_OBJECT *trobj, DB_TRIGGER_EVENT *event)
int db_trigger_class (DB_OBJECT *trobj, DB_OBJECT **class_obj)
int db_trigger_attribute (DB_OBJECT *trobj, char **attr)
int db_trigger_condition (DB_OBJECT *trobj, char **condition)
int db_trigger_condition_time (DB_OBJECT *trobj, DB_TRIGGER_TIME *tr_time)
int db_trigger_action_type (DB_OBJECT *trobj, DB_TRIGGER_ACTION *type)
int db_trigger_action_time (DB_OBJECT *trobj, DB_TRIGGER_TIME *tr_time)
int db_trigger_action (DB_OBJECT *trobj, char **action)
int db_trigger_comment (DB_OBJECT *trobj, char **comment)
DB_CTMPL * dbt_create_class (const char *name)
DB_CTMPL * dbt_create_vclass (const char *name)
DB_CTMPL * dbt_edit_class (DB_OBJECT *classobj)
DB_OBJECT * dbt_finish_class (DB_CTMPL *def)
void dbt_abort_class (DB_CTMPL *def)
int dbt_add_attribute (DB_CTMPL *def, const char *name, const char *domain, DB_VALUE *default_value)
int dbt_add_shared_attribute (DB_CTMPL *def, const char *name, const char *domain, DB_VALUE *default_value)
int dbt_add_class_attribute (DB_CTMPL *def, const char *name, const char *domain, DB_VALUE *default_value)
int dbt_constrain_non_null (DB_CTMPL *def, const char *name, int class_attribute, int on_or_off)
int dbt_constrain_unique (DB_CTMPL *def, const char *name, int on_or_off)
int dbt_add_constraint (DB_CTMPL *def, DB_CONSTRAINT_TYPE constraint_type, const char *constraint_name, const char **attnames, int class_attributes, const char *comment)
int dbt_drop_constraint (DB_CTMPL *def, DB_CONSTRAINT_TYPE constraint_type, const char *constraint_name, const char **attnames, int class_attributes)
int dbt_add_set_attribute_domain (DB_CTMPL *def, const char *name, int class_attribute, const char *domain)
int dbt_change_domain (DB_CTMPL *def, const char *name, int class_attribute, const char *domain)
int dbt_change_default (DB_CTMPL *def, const char *name, int class_attribute, DB_VALUE *value)
int dbt_drop_set_attribute_domain (DB_CTMPL *def, const char *name, int class_attribute, const char *domain)
int dbt_drop_attribute (DB_CTMPL *def, const char *name)
int dbt_drop_shared_attribute (DB_CTMPL *def, const char *name)
int dbt_drop_class_attribute (DB_CTMPL *def, const char *name)
int dbt_add_method (DB_CTMPL *def, const char *name, const char *implementation)
int dbt_add_class_method (DB_CTMPL *def, const char *name, const char *implementation)
int dbt_add_argument (DB_CTMPL *def, const char *name, int class_method, int arg_index, const char *domain)
int dbt_add_set_argument_domain (DB_CTMPL *def, const char *name, int class_method, int arg_index, const char *domain)
int dbt_change_method_implementation (DB_CTMPL *def, const char *name, int class_method, const char *newname)
int dbt_drop_method (DB_CTMPL *def, const char *name)
int dbt_drop_class_method (DB_CTMPL *def, const char *name)
int dbt_add_super (DB_CTMPL *def, DB_OBJECT *super)
int dbt_drop_super (DB_CTMPL *def, DB_OBJECT *super)
int dbt_drop_super_connect (DB_CTMPL *def, DB_OBJECT *super)
int dbt_rename (DB_CTMPL *def, const char *name, int class_namespace, const char *newname)
int dbt_add_method_file (DB_CTMPL *def, const char *name)
int dbt_drop_method_file (DB_CTMPL *def, const char *name)
int dbt_drop_method_files (DB_CTMPL *def)
int dbt_rename_method_file (DB_CTMPL *def, const char *new_name, const char *old_name)
int dbt_set_loader_commands (DB_CTMPL *def, const char *commands)
int dbt_add_resolution (DB_CTMPL *def, DB_OBJECT *super, const char *name, const char *alias)
int dbt_add_class_resolution (DB_CTMPL *def, DB_OBJECT *super, const char *name, const char *alias)
int dbt_drop_resolution (DB_CTMPL *def, DB_OBJECT *super, const char *name)
int dbt_drop_class_resolution (DB_CTMPL *def, DB_OBJECT *super, const char *name)
int dbt_add_query_spec (DB_CTMPL *def, const char *query)
int dbt_drop_query_spec (DB_CTMPL *def, const int query_no)
int dbt_change_query_spec (DB_CTMPL *def, const char *new_query, const int query_no)
int dbt_set_object_id (DB_CTMPL *def, DB_NAMELIST *id_list)
int dbt_add_foreign_key (DB_CTMPL *def, const char *constraint_name, const char **attnames, const char *ref_class, const char **ref_attrs, int del_action, int upd_action, const char *comment)
DB_OTMPL * dbt_create_object (DB_OBJECT *classobj)
DB_OTMPL * dbt_edit_object (DB_OBJECT *object)
DB_OBJECT * dbt_finish_object (DB_OTMPL *def)
DB_OBJECT * dbt_finish_object_and_decache_when_failure (DB_OTMPL *def)
void dbt_abort_object (DB_OTMPL *def)
int dbt_put (DB_OTMPL *def, const char *name, DB_VALUE *value)
int dbt_set_label (DB_OTMPL *def, DB_VALUE *label)
int db_get_attribute_descriptor (DB_OBJECT *obj, const char *attname, int class_attribute, int for_update, DB_ATTDESC **descriptor)
void db_free_attribute_descriptor (DB_ATTDESC *descriptor)
int db_get_method_descriptor (DB_OBJECT *obj, const char *methname, int class_method, DB_METHDESC **descriptor)
void db_free_method_descriptor (DB_METHDESC *descriptor)
int db_dget (DB_OBJECT *obj, DB_ATTDESC *attribute, DB_VALUE *value)
int db_dput (DB_OBJECT *obj, DB_ATTDESC *attribute, DB_VALUE *value)
int db_dsend (DB_OBJECT *obj, DB_METHDESC *method, DB_VALUE *returnval,...)
int db_dsend_arglist (DB_OBJECT *obj, DB_METHDESC *method, DB_VALUE *returnval, DB_VALUE_LIST *args)
int db_dsend_argarray (DB_OBJECT *obj, DB_METHDESC *method, DB_VALUE *returnval, DB_VALUE **args)
int db_dsend_quick (DB_OBJECT *obj, DB_METHDESC *method, DB_VALUE *returnval, int nargs, DB_VALUE **args)
int dbt_dput (DB_OTMPL *def, DB_ATTDESC *attribute, DB_VALUE *value)
char * db_get_vclass_ldb_name (DB_OBJECT *op)
int db_add_query_spec (DB_OBJECT *vclass, const char *query)
int db_drop_query_spec (DB_OBJECT *vclass, const int query_no)
DB_NAMELIST * db_get_object_id (DB_OBJECT *vclass)
int db_namelist_add (DB_NAMELIST **list, const char *name)
int db_namelist_append (DB_NAMELIST **list, const char *name)
void db_namelist_free (DB_NAMELIST *list)
int db_is_vclass (DB_OBJECT *op)
DB_OBJLIST * db_get_all_vclasses_on_ldb (void)
DB_OBJLIST * db_get_all_vclasses (void)
DB_QUERY_SPEC * db_get_query_specs (DB_OBJECT *obj)
DB_QUERY_SPEC * db_query_spec_next (DB_QUERY_SPEC *query_spec)
const char * db_query_spec_string (DB_QUERY_SPEC *query_spec)
int db_change_query_spec (DB_OBJECT *vclass, const char *new_query, const int query_no)
int db_validate (DB_OBJECT *vclass)
int db_validate_query_spec (DB_OBJECT *vclass, const char *query_spec)
int db_is_real_instance (DB_OBJECT *obj)
DB_OBJECT * db_real_instance (DB_OBJECT *obj)
int db_instance_equal (DB_OBJECT *obj1, DB_OBJECT *obj2)
int db_is_updatable_object (DB_OBJECT *obj)
int db_is_updatable_attribute (DB_OBJECT *obj, const char *attr_name)
int db_check_single_query (DB_SESSION *session)
int db_get_query_format (const char *CSQL_query, DB_QUERY_TYPE **type_list, DB_QUERY_ERROR *query_error)
DB_QUERY_TYPE * db_query_format_next (DB_QUERY_TYPE *query_type)
DB_COL_TYPE db_query_format_col_type (DB_QUERY_TYPE *query_type)
char * db_query_format_name (DB_QUERY_TYPE *query_type)
DB_TYPE db_query_format_type (DB_QUERY_TYPE *query_type)
void db_query_format_free (DB_QUERY_TYPE *query_type)
DB_DOMAIN * db_query_format_domain (DB_QUERY_TYPE *query_type)
char * db_query_format_attr_name (DB_QUERY_TYPE *query_type)
char * db_query_format_spec_name (DB_QUERY_TYPE *query_type)
char * db_query_format_original_name (DB_QUERY_TYPE *query_type)
const char * db_query_format_class_name (DB_QUERY_TYPE *query_type)
int db_query_format_is_non_null (DB_QUERY_TYPE *query_type)
int db_get_query_result_format (DB_QUERY_RESULT *result, DB_QUERY_TYPE **type_list)
int db_query_next_tuple (DB_QUERY_RESULT *result)
int db_query_prev_tuple (DB_QUERY_RESULT *result)
int db_query_first_tuple (DB_QUERY_RESULT *result)
int db_query_last_tuple (DB_QUERY_RESULT *result)
int db_query_get_tuple_value_by_name (DB_QUERY_RESULT *result, char *column_name, DB_VALUE *value)
int db_query_get_tuple_value (DB_QUERY_RESULT *result, int tuple_index, DB_VALUE *value)
int db_query_get_tuple_oid (DB_QUERY_RESULT *result, DB_VALUE *db_value)
int db_query_get_tuple_valuelist (DB_QUERY_RESULT *result, int size, DB_VALUE *value_list)
int db_query_tuple_count (DB_QUERY_RESULT *result)
int db_query_column_count (DB_QUERY_RESULT *result)
int db_query_prefetch_columns (DB_QUERY_RESULT *result, int *columns, int col_count)
int db_query_format_size (DB_QUERY_TYPE *query_type)
int db_query_end (DB_QUERY_RESULT *result)
int db_query_plan_dump_file (char *filename)
DB_SESSION * db_open_buffer (const char *buffer)
DB_SESSION * db_open_file (FILE *file)
DB_SESSION * db_open_file_name (const char *name)
int db_statement_count (DB_SESSION *session)
int db_compile_statement (DB_SESSION *session)
void db_rewind_statement (DB_SESSION *session)
DB_SESSION_ERROR * db_get_errors (DB_SESSION *session)
DB_SESSION_ERROR * db_get_next_error (DB_SESSION_ERROR *errors, int *linenumber, int *columnnumber)
DB_SESSION_ERROR * db_get_warnings (DB_SESSION *session)
DB_SESSION_ERROR * db_get_next_warning (DB_SESSION_WARNING *errors, int *linenumber, int *columnnumber)
DB_PARAMETER * db_get_parameters (DB_SESSION *session, int statement_id)
DB_PARAMETER * db_parameter_next (DB_PARAMETER *param)
const char * db_parameter_name (DB_PARAMETER *param)
int db_bind_parameter_name (const char *name, DB_VALUE *value)
DB_QUERY_TYPE * db_get_query_type_list (DB_SESSION *session, int stmt)
int db_number_of_input_markers (DB_SESSION *session, int stmt)
int db_number_of_output_markers (DB_SESSION *session, int stmt)
DB_MARKER * db_get_input_markers (DB_SESSION *session, int stmt)
DB_MARKER * db_get_output_markers (DB_SESSION *session, int stmt)
DB_MARKER * db_marker_next (DB_MARKER *marker)
int db_marker_index (DB_MARKER *marker)
DB_DOMAIN * db_marker_domain (DB_MARKER *marker)
bool db_is_input_marker (DB_MARKER *marker)
bool db_is_output_marker (DB_MARKER *marker)
int db_get_start_line (DB_SESSION *session, int stmt)
int db_get_statement_type (DB_SESSION *session, int stmt)
void db_include_oid (DB_SESSION *session, int include_oid)
int db_push_values (DB_SESSION *session, int count, DB_VALUE *in_values)
int db_execute (const char *CSQL_query, DB_QUERY_RESULT **result, DB_QUERY_ERROR *query_error)
int db_execute_oid (const char *CSQL_query, DB_QUERY_RESULT **result, DB_QUERY_ERROR *query_error)
int db_query_produce_updatable_result (DB_SESSION *session, int stmtid)
int db_execute_statement (DB_SESSION *session, int stmt, DB_QUERY_RESULT **result)
int db_execute_and_keep_statement (DB_SESSION *session, int stmt, DB_QUERY_RESULT **result)
DB_CLASS_MODIFICATION_STATUS db_has_modified_class (DB_SESSION *session, int stmt_id)
int db_query_set_copy_tplvalue (DB_QUERY_RESULT *result, int copy)
void db_close_session (DB_SESSION *session)
void db_drop_statement (DB_SESSION *session, int stmt_id)
int db_object_describe (DB_OBJECT *obj, int num_attrs, const char **attrs, DB_QUERY_TYPE **col_spec)
int db_object_fetch (DB_OBJECT *obj, int num_attrs, const char **attrs, DB_QUERY_RESULT **result)
int db_set_client_cache_time (DB_SESSION *session, int stmt_ndx, CACHE_TIME *cache_time)
bool db_get_jdbccachehint (DB_SESSION *session, int stmt_ndx, int *life_time)
bool db_get_cacheinfo (DB_SESSION *session, int stmt_ndx, bool *use_plan_cache, bool *use_query_cache)
void db_free_query (DB_SESSION *session)
DB_QUERY_TYPE * db_get_query_type_ptr (DB_QUERY_RESULT *result)
int db_query_execute (const char *CSQL_query, DB_QUERY_RESULT **result, DB_QUERY_ERROR *query_error)
int db_list_length (DB_LIST *list)
DB_NAMELIST * db_namelist_copy (DB_NAMELIST *list)
int db_drop_shared_attribute (DB_OBJECT *classobj, const char *name)
int db_add_element_domain (DB_OBJECT *classobj, const char *name, const char *domain)
int db_drop_element_domain (DB_OBJECT *classobj, const char *name, const char *domain)
int db_rename_attribute (DB_OBJECT *classobj, const char *name, int class_attribute, const char *newname)
int db_rename_method (DB_OBJECT *classobj, const char *name, int class_method, const char *newname)
int db_set_argument_domain (DB_OBJECT *classobj, const char *name, int class_method, int arg_index, const char *domain)
int db_set_method_arg_domain (DB_OBJECT *classobj, const char *name, int arg_index, const char *domain)
int db_set_class_method_arg_domain (DB_OBJECT *classobj, const char *name, int arg_index, const char *domain)
DB_NAMELIST * db_namelist_sort (DB_NAMELIST *names)
void db_namelist_remove (DB_NAMELIST **list, const char *name)
DB_OBJECT * db_objlist_get (DB_OBJLIST *list, int psn)
void db_namelist_print (DB_NAMELIST *list)
void db_objlist_print (DB_OBJLIST *list)
DB_NAMELIST * db_get_attribute_names (DB_OBJECT *obj)
DB_NAMELIST * db_get_shared_attribute_names (DB_OBJECT *obj)
DB_NAMELIST * db_get_ordered_attribute_names (DB_OBJECT *obj)
DB_NAMELIST * db_get_class_attribute_names (DB_OBJECT *obj)
DB_NAMELIST * db_get_method_names (DB_OBJECT *obj)
DB_NAMELIST * db_get_class_method_names (DB_OBJECT *obj)
DB_NAMELIST * db_get_superclass_names (DB_OBJECT *obj)
DB_NAMELIST * db_get_subclass_names (DB_OBJECT *obj)
DB_NAMELIST * db_get_method_file_names (DB_OBJECT *obj)
const char * db_get_method_function (DB_OBJECT *obj, const char *name)
DB_DOMAIN * db_get_attribute_domain (DB_OBJECT *obj, const char *name)
DB_TYPE db_get_attribute_type (DB_OBJECT *obj, const char *name)
DB_OBJECT * db_get_attribute_class (DB_OBJECT *obj, const char *name)
void db_force_method_reload (DB_OBJECT *obj)
DB_ATTRIBUTE * db_get_shared_attribute (DB_OBJECT *obj, const char *name)
DB_ATTRIBUTE * db_get_ordered_attributes (DB_OBJECT *obj)
DB_ATTRIBUTE * db_attribute_ordered_next (DB_ATTRIBUTE *attribute)
int db_print_mop (DB_OBJECT *obj, char *buffer, int maxlen)
int db_get_shared (DB_OBJECT *object, const char *attpath, DB_VALUE *value)
DB_OBJECT * db_copy (DB_OBJECT *sourcemop)
char * db_get_method_source_file (DB_OBJECT *obj, const char *name)
int db_is_indexed (DB_OBJECT *classobj, const char *attname)
DB_IDENTIFIER * db_identifier (DB_OBJECT *obj)
DB_OBJECT * db_object (DB_IDENTIFIER *oid)
int db_chn (DB_OBJECT *obj, DB_FETCH_MODE purpose)
int db_encode_object (DB_OBJECT *object, char *string, int allocated_length, int *actual_length)
int db_decode_object (const char *string, DB_OBJECT **object)
int db_set_system_parameters (const char *data)
int db_get_system_parameters (char *data, int len)
char * db_get_host_connected (void)
int db_get_ha_server_state (char *buffer, int maxlen)
void db_clear_host_connected (void)
char * db_get_database_version (void)
bool db_enable_trigger (void)
bool db_disable_trigger (void)
void db_clear_host_status (void)
void db_set_host_status (char *hostname, int status)
void db_set_connected_host_status (char *host_connected)
bool db_does_connected_host_have_status (int status)
bool db_need_reconnect (void)
bool db_need_ignore_repl_delay (void)
Macro Definition Documentation
#define bool char
Definition at line 31 of file dbi_compat.h.
Referenced by do_prepare_update(), init_compile_context(), lang_load_coll_from_lib(), local_am_pm_value(), lock_initialize(), logpb_is_dirty(), os_send_signal(), perfmon_initialize(), qexec_execute_delete(), qexec_execute_insert(), qexec_execute_update(), qexec_generate_tuple_descriptor(), sboot_add_volume_extension(), sqmgr_prepare_query(), stran_server_commit(), stx_build(), stx_build_analytic_type(), stx_build_connectby_proc(), stx_build_fetch_proc(), stx_build_key_info(), stx_build_merge_proc(), stx_build_xasl_node(), and sysprm_generate_new_value().
#define DB_FALSE 0
Definition at line 56 of file dbi_compat.h.
#define DB_TRUE 1
Definition at line 55 of file dbi_compat.h.
#define SQLX_CMD_ALTER_CLASS CUBRID_STMT_ALTER_CLASS
Definition at line 60 of file dbi_compat.h.
#define SQLX_CMD_ALTER_INDEX CUBRID_STMT_ALTER_INDEX
Definition at line 106 of file dbi_compat.h.
#define SQLX_CMD_ALTER_SERIAL CUBRID_STMT_ALTER_SERIAL
Definition at line 61 of file dbi_compat.h.
#define SQLX_CMD_ALTER_STORED_PROCEDURE CUBRID_STMT_ALTER_STORED_PROCEDURE
Definition at line 120 of file dbi_compat.h.
#define SQLX_CMD_ALTER_STORED_PROCEDURE_OWNER CUBRID_STMT_ALTER_STORED_PROCEDURE
Definition at line 121 of file dbi_compat.h.
#define SQLX_CMD_ALTER_USER CUBRID_STMT_ALTER_USER
Definition at line 104 of file dbi_compat.h.
#define SQLX_CMD_ATTACH CUBRID_STMT_ATTACH
Definition at line 94 of file dbi_compat.h.
#define SQLX_CMD_CALL CUBRID_STMT_CALL
Definition at line 84 of file dbi_compat.h.
#define SQLX_CMD_CALL_SP CUBRID_STMT_CALL_SP
Definition at line 125 of file dbi_compat.h.
#define SQLX_CMD_COMMIT_WORK CUBRID_STMT_COMMIT_WORK
Definition at line 62 of file dbi_compat.h.
#define SQLX_CMD_CREATE_CLASS CUBRID_STMT_CREATE_CLASS
Definition at line 64 of file dbi_compat.h.
#define SQLX_CMD_CREATE_INDEX CUBRID_STMT_CREATE_INDEX
Definition at line 65 of file dbi_compat.h.
#define SQLX_CMD_CREATE_SERIAL CUBRID_STMT_CREATE_SERIAL
Definition at line 67 of file dbi_compat.h.
#define SQLX_CMD_CREATE_STORED_PROCEDURE CUBRID_STMT_CREATE_STORED_PROCEDURE
Definition at line 108 of file dbi_compat.h.
#define SQLX_CMD_CREATE_TRIGGER CUBRID_STMT_CREATE_TRIGGER
Definition at line 66 of file dbi_compat.h.
#define SQLX_CMD_CREATE_USER CUBRID_STMT_CREATE_USER
Definition at line 102 of file dbi_compat.h.
#define SQLX_CMD_DEALLOCATE_PREPARE CUBRID_STMT_DEALLOCATE_PREPARE
Definition at line 112 of file dbi_compat.h.
#define SQLX_CMD_DELETE CUBRID_STMT_DELETE
Definition at line 83 of file dbi_compat.h.
#define SQLX_CMD_DO CUBRID_STMT_DO
Definition at line 114 of file dbi_compat.h.
#define SQLX_CMD_DROP_CLASS CUBRID_STMT_DROP_CLASS
Definition at line 69 of file dbi_compat.h.
#define SQLX_CMD_DROP_DATABASE CUBRID_STMT_DROP_DATABASE
Definition at line 68 of file dbi_compat.h.
#define SQLX_CMD_DROP_INDEX CUBRID_STMT_DROP_INDEX
Definition at line 70 of file dbi_compat.h.
#define SQLX_CMD_DROP_LABEL CUBRID_STMT_DROP_LABEL
Definition at line 71 of file dbi_compat.h.
#define SQLX_CMD_DROP_SERIAL CUBRID_STMT_DROP_SERIAL
Definition at line 73 of file dbi_compat.h.
#define SQLX_CMD_DROP_SESSION_VARIABLES CUBRID_STMT_DROP_SESSION_VARIABLES
Definition at line 117 of file dbi_compat.h.
#define SQLX_CMD_DROP_STORED_PROCEDURE CUBRID_STMT_DROP_STORED_PROCEDURE
Definition at line 109 of file dbi_compat.h.
#define SQLX_CMD_DROP_TRIGGER CUBRID_STMT_DROP_TRIGGER
Definition at line 72 of file dbi_compat.h.
#define SQLX_CMD_DROP_USER CUBRID_STMT_DROP_USER
Definition at line 103 of file dbi_compat.h.
#define SQLX_CMD_EVALUATE CUBRID_STMT_EVALUATE
Definition at line 74 of file dbi_compat.h.
#define SQLX_CMD_EXECUTE_PREPARE CUBRID_STMT_EXECUTE_PREPARE
Definition at line 111 of file dbi_compat.h.
#define SQLX_CMD_GET_ISO_LVL CUBRID_STMT_GET_ISO_LVL
Definition at line 85 of file dbi_compat.h.
#define SQLX_CMD_GET_LDB CUBRID_STMT_GET_LDB
Definition at line 99 of file dbi_compat.h.
#define SQLX_CMD_GET_OPT_LVL CUBRID_STMT_GET_OPT_LVL
Definition at line 87 of file dbi_compat.h.
#define SQLX_CMD_GET_STATS CUBRID_STMT_GET_STATS
Definition at line 101 of file dbi_compat.h.
#define SQLX_CMD_GET_TIMEOUT CUBRID_STMT_GET_TIMEOUT
Definition at line 86 of file dbi_compat.h.
#define SQLX_CMD_GET_TRIGGER CUBRID_STMT_GET_TRIGGER
Definition at line 90 of file dbi_compat.h.
#define SQLX_CMD_GRANT CUBRID_STMT_GRANT
Definition at line 77 of file dbi_compat.h.
#define SQLX_CMD_INSERT CUBRID_STMT_INSERT
Definition at line 80 of file dbi_compat.h.
#define SQLX_CMD_ON_LDB CUBRID_STMT_ON_LDB
Definition at line 98 of file dbi_compat.h.
#define SQLX_CMD_PREPARE CUBRID_STMT_PREPARE
Definition at line 93 of file dbi_compat.h.
#define SQLX_CMD_PREPARE_STATEMENT CUBRID_STMT_PREPARE_STATEMENT
Definition at line 110 of file dbi_compat.h.
#define SQLX_CMD_REGISTER_DATABASE CUBRID_STMT_REGISTER_DATABASE
Definition at line 63 of file dbi_compat.h.
#define SQLX_CMD_REMOVE_TRIGGER CUBRID_STMT_REMOVE_TRIGGER
Definition at line 96 of file dbi_compat.h.
#define SQLX_CMD_RENAME_CLASS CUBRID_STMT_RENAME_CLASS
Definition at line 75 of file dbi_compat.h.
#define SQLX_CMD_RENMAE_TRIGGER CUBRID_STMT_RENAME_TRIGGER
Definition at line 97 of file dbi_compat.h.
#define SQLX_CMD_REVOKE CUBRID_STMT_REVOKE
Definition at line 78 of file dbi_compat.h.
#define SQLX_CMD_ROLLBACK_WORK CUBRID_STMT_ROLLBACK_WORK
Definition at line 76 of file dbi_compat.h.
#define SQLX_CMD_SAVEPOINT CUBRID_STMT_SAVEPOINT
Definition at line 92 of file dbi_compat.h.
#define SQLX_CMD_SCOPE CUBRID_STMT_SCOPE
Definition at line 89 of file dbi_compat.h.
#define SQLX_CMD_SELECT CUBRID_STMT_SELECT
Definition at line 81 of file dbi_compat.h.
#define SQLX_CMD_SELECT_UPDATE CUBRID_STMT_SELECT_UPDATE
Definition at line 115 of file dbi_compat.h.
#define SQLX_CMD_SET_LDB CUBRID_STMT_SET_LDB
Definition at line 100 of file dbi_compat.h.
#define SQLX_CMD_SET_NAMES CUBRID_STMT_SET_NAMES
Definition at line 119 of file dbi_compat.h.
#define SQLX_CMD_SET_OPT_LVL CUBRID_STMT_SET_OPT_LVL
Definition at line 88 of file dbi_compat.h.
#define SQLX_CMD_SET_SESSION_VARIABLES CUBRID_STMT_SET_SESSION_VARIABLES
Definition at line 116 of file dbi_compat.h.
#define SQLX_CMD_SET_SYS_PARAMS CUBRID_STMT_SET_SYS_PARAMS
Definition at line 105 of file dbi_compat.h.
#define SQLX_CMD_SET_TRIGGER CUBRID_STMT_SET_TRIGGER
Definition at line 91 of file dbi_compat.h.
#define SQLX_CMD_STMT_MERGE CUBRID_STMT_MERGE
Definition at line 118 of file dbi_compat.h.
#define SQLX_CMD_TRUNCATE CUBRID_STMT_TRUNCATE
Definition at line 113 of file dbi_compat.h.
#define SQLX_CMD_TYPE CUBRID_STMT_TYPE
Definition at line 58 of file dbi_compat.h.
#define SQLX_CMD_UNKNOWN CUBRID_STMT_UNKNOWN
Definition at line 126 of file dbi_compat.h.
#define SQLX_CMD_UPDATE CUBRID_STMT_UPDATE
Definition at line 82 of file dbi_compat.h.
#define SQLX_CMD_UPDATE_STATS CUBRID_STMT_UPDATE_STATS
Definition at line 79 of file dbi_compat.h.
#define SQLX_CMD_USE CUBRID_STMT_USE
Definition at line 95 of file dbi_compat.h.
#define SQLX_MAX_CMD_TYPE CUBRID_MAX_STMT_TYPE
Definition at line 123 of file dbi_compat.h.
Enumeration Type Documentation
anonymous enum
Enumerator
DB_NO_OIDS
DB_ROW_OIDS
DB_COLUMN_OIDS
Definition at line 649 of file dbi_compat.h.
Function Documentation
int db_2pc_attach_transaction (int gtrid)
Definition at line 1403 of file db_admin.c.
References CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, and tran_2pc_attach_global_tran().
Referenced by do_attach(), and fn_xa_end_tran().
int db_2pc_prepare_to_commit_transaction (int gtrid)
Definition at line 1426 of file db_admin.c.
References CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, and tran_2pc_prepare_global_tran().
Referenced by do_prepare_to_commit().
int db_2pc_prepare_transaction (void)
Definition at line 1351 of file db_admin.c.
References CHECK_CONNECT_MINUSONE, CHECK_MODIFICATION_MINUSONE, and tran_2pc_prepare().
Referenced by fn_xa_prepare().
int db_2pc_prepared_transactions (int gtrids[], int size)
Definition at line 1373 of file db_admin.c.
References ARG_FILE_LINE, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, cubregex::count(), ER_OBJ_INVALID_ARGUMENTS, er_set(), ER_WARNING_SEVERITY, NULL, and tran_2pc_recovery_prepared().
Referenced by fn_xa_end_tran(), and fn_xa_recover().
int db_2pc_start_transaction (void)
Definition at line 1327 of file db_admin.c.
References CHECK_CONNECT_MINUSONE, CHECK_MODIFICATION_MINUSONE, and tran_2pc_start().
Referenced by fn_xa_prepare().
int db_abort_to_savepoint (const char * savepoint_name)
Definition at line 1237 of file db_admin.c.
References CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, db_abort_to_savepoint_internal(), and error().
Referenced by do_delete(), do_execute_delete(), do_execute_merge(), do_execute_update(), do_merge(), do_update(), fn_savepoint(), and ux_execute_all().
int db_abort_transaction (void)
Definition at line 1114 of file db_admin.c.
References CHECK_CONNECT_ERROR, error(), and tran_abort().
Referenced by check_commit(), chksum_start(), compactdb_start(), csql_do_session_cmd(), csql_execute_statements(), csql_exit_session(), db_abort_to_savepoint_internal(), do_reclaim_class_addresses(), gen_tz(), ldr_abort(), ldr_exec_query_from_file(), ldr_sa_load(), main(), synccolldb(), tzc_compute_timezone_checksum(), uci_rollback(), ux_end_tran(), ux_execute_array(), and ux_execute_batch().
int db_add_argument (DB_OBJECT * classobj, const char * name, int class_method, int arg_index, const char * domain)
Definition at line 988 of file db_class.c.
References add_arg_domain().
int db_add_attribute (DB_OBJECT * obj, const char * name, const char * domain, DB_VALUE * default_value)
int db_add_class_attribute (DB_OBJECT * obj, const char * name, const char * domain, DB_VALUE * default_value)
int db_add_class_method (DB_OBJECT * classobj, const char * name, const char * implementation)
int db_add_class_resolution (DB_OBJECT * classobj, DB_OBJECT * super, const char * name, const char * alias)
int db_add_constraint (MOP classmop, DB_CONSTRAINT_TYPE constraint_type, const char * constraint_name, const char ** att_names, int class_attributes)
Definition at line 1777 of file db_class.c.
References assert, CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, er_errid(), free_and_init, NO_ERROR, NULL, sm_add_constraint(), SM_NORMAL_INDEX, and sm_produce_constraint_name_mop().
Referenced by au_install(), boot_define_attribute(), boot_define_class(), boot_define_class_authorization(), boot_define_domain(), boot_define_ha_apply_info(), boot_define_index(), boot_define_index_key(), boot_define_meth_argument(), boot_define_meth_file(), boot_define_meth_sig(), boot_define_method(), boot_define_partition(), boot_define_query_spec(), boot_define_serial(), boot_define_stored_procedure(), boot_define_stored_procedure_arguments(), db_add_index(), db_constrain_non_null(), db_constrain_unique(), and do_alter_clause_change_attribute().
int db_add_element_domain (DB_OBJECT * classobj, const char * name, const char * domain)
int db_add_index (DB_OBJECT * classobj, const char * attname)
int db_add_member (DB_OBJECT * user, DB_OBJECT * member)
Definition at line 1694 of file db_admin.c.
References au_add_member(), CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and CHECK_MODIFICATION_ERROR.
Referenced by do_create_user().
int db_add_method (DB_OBJECT * classobj, const char * name, const char * implementation)
int db_add_method_file (DB_OBJECT * classobj, const char * name)
int db_add_query_spec (DB_OBJECT * vclass, const char * query)
int db_add_resolution (DB_OBJECT * classobj, DB_OBJECT * super, const char * name, const char * alias)
int db_add_set_argument_domain (DB_OBJECT * classobj, const char * name, int class_method, int arg_index, const char * domain)
Definition at line 1049 of file db_class.c.
References add_arg_domain().
int db_add_set_attribute_domain (DB_OBJECT * classobj, const char * name, int class_attribute, const char * domain)
int db_add_shared_attribute (DB_OBJECT * obj, const char * name, const char * domain, DB_VALUE * default_value)
int db_add_super (DB_OBJECT * classobj, DB_OBJECT * super)
DB_OBJECT* db_add_user (const char * name, int * exists)
Definition at line 1646 of file db_admin.c.
References au_add_user(), CHECK_1ARG_NULL, CHECK_CONNECT_NULL, and CHECK_MODIFICATION_NULL.
Referenced by do_create_user().
int db_add_volume (const char * ext_path, const char * ext_name, const char * ext_comments, const int ext_npages, const DB_VOLPURPOSE ext_purpose)
Definition at line 314 of file db_admin.c.
References dbdef_vol_ext_info::comments, db_add_volume_ex(), dbdef_vol_ext_info::max_npages, dbdef_vol_ext_info::max_writesize_in_sec, dbdef_vol_ext_info::name, dbdef_vol_ext_info::overwrite, dbdef_vol_ext_info::path, and dbdef_vol_ext_info::purpose.
int db_alter_trigger_priority (DB_OBJECT * trobj, double priority)
Definition at line 1438 of file db_obj.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, and tr_set_priority().
int db_alter_trigger_status (DB_OBJECT * trobj, DB_TRIGGER_STATUS status)
Definition at line 1462 of file db_obj.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, and tr_set_status().
DB_OBJECT* db_attribute_class (DB_ATTRIBUTE * attribute)
Definition at line 1189 of file db_info.c.
References sm_attribute::class_mop, and NULL.
Referenced by class_attr_info(), emit_class_attributes(), emit_class_meta(), emit_foreign_key(), emit_instance_attributes(), emit_reverse_unique_def(), emit_unique_def(), ldr_compare_storage_order(), pt_check_alter(), and pt_check_mutable_attributes().
DB_VALUE* db_attribute_default (DB_ATTRIBUTE * attribute)
Definition at line 1209 of file db_info.c.
References sm_attribute::default_value, NULL, and sm_default_value::value.
Referenced by check_missing_non_null_attrs(), class_attr_info(), emit_attribute_def(), get_column_default_as_string(), pt_check_union_type_compatibility_of_values_query(), and pt_eval_path_expr().
DB_DOMAIN* db_attribute_domain (DB_ATTRIBUTE * attribute)
Definition at line 1165 of file db_info.c.
References sm_attribute::domain, NULL, and sm_filter_domain().
Referenced by class_attr_info(), db_attdesc_domain(), do_alter_one_clause_with_template(), emit_attribute_def(), fn_collection(), get_attr_type(), has_dependencies(), oid_attr_info_set(), pt_check_alter(), pt_check_drop(), pt_get_attr_data_type(), pt_get_attributes(), pt_to_merge_update_xasl(), pt_to_odku_info(), pt_to_update_xasl(), rm_api_get_info(), sm_get_descriptor_component(), ux_get_attr_type_str(), ux_get_generated_keys_client_insert(), ux_get_generated_keys_server_insert(), and vt_api_init_domain().
int db_attribute_id (DB_ATTRIBUTE * attribute)
Definition at line 1124 of file db_info.c.
References sm_attribute::id, and NULL.
int db_attribute_is_auto_increment (DB_ATTRIBUTE * attribute)
Definition at line 1309 of file db_info.c.
References sm_attribute::flags, NULL, and SM_ATTFLAG_AUTO_INCREMENT.
Referenced by pt_check_defaultf(), rm_api_get_info(), set_column_info(), ux_get_generated_keys_client_insert(), and ux_get_generated_keys_server_insert().
int db_attribute_is_foreign_key (DB_ATTRIBUTE * attribute)
Definition at line 1282 of file db_info.c.
References sm_attribute::constraints, sm_constraint::next, NULL, SM_CONSTRAINT_FOREIGN_KEY, and sm_constraint::type.
Referenced by set_column_info(), and sm_att_fk_constrained().
int db_attribute_is_indexed (DB_ATTRIBUTE * attribute)
Definition at line 1375 of file db_info.c.
References sm_attribute::constraints, sm_constraint::next, NULL, SM_IS_CONSTRAINT_INDEX_FAMILY, and sm_constraint::type.
Referenced by class_attr_info(), and emit_instance_attributes().
int db_attribute_is_non_null (DB_ATTRIBUTE * attribute)
Definition at line 1355 of file db_info.c.
References sm_attribute::flags, NULL, and SM_ATTFLAG_NON_NULL.
Referenced by check_missing_non_null_attrs(), class_attr_info(), db_query_format_is_non_null(), do_check_fk_constraints_internal(), emit_attribute_def(), pt_check_defaultf(), pt_check_filter_index_expr(), and rm_api_get_info().
int db_attribute_is_primary_key (DB_ATTRIBUTE * attribute)
Definition at line 1255 of file db_info.c.
References sm_attribute::constraints, sm_constraint::next, NULL, SM_CONSTRAINT_PRIMARY_KEY, and sm_constraint::type.
Referenced by class_attr_info(), is_attribute_primary_key(), pt_check_defaultf(), and set_column_info().
int db_attribute_is_reverse_indexed (DB_ATTRIBUTE * attribute)
Definition at line 1402 of file db_info.c.
References sm_attribute::constraints, sm_constraint::next, NULL, SM_IS_CONSTRAINT_REVERSE_INDEX_FAMILY, and sm_constraint::type.
Referenced by set_column_info().
int db_attribute_is_reverse_unique (DB_ATTRIBUTE * attribute)
Definition at line 1328 of file db_info.c.
References sm_attribute::constraints, sm_constraint::next, NULL, SM_CONSTRAINT_REVERSE_UNIQUE, and sm_constraint::type.
Referenced by class_attr_info(), emit_instance_attributes(), and set_column_info().
int db_attribute_is_shared (DB_ATTRIBUTE * attribute)
Definition at line 1429 of file db_info.c.
References sm_attribute::header, ID_SHARED_ATTRIBUTE, sm_component::name_space, and NULL.
Referenced by class_attr_info(), do_check_fk_constraints_internal(), emit_class_meta(), emit_instance_attributes(), generate_natural_join_attrs_from_db_attrs(), get_reasonable_predicate(), ldr_compare_attribute_with_meta(), pt_get_attr_data_type(), pt_get_attributes(), and set_column_info().
int db_attribute_is_unique (DB_ATTRIBUTE * attribute)
Definition at line 1228 of file db_info.c.
References sm_attribute::constraints, sm_constraint::next, NULL, SM_CONSTRAINT_PRIMARY_KEY, SM_CONSTRAINT_UNIQUE, and sm_constraint::type.
Referenced by class_attr_info(), emit_instance_attributes(), and set_column_info().
int db_attribute_length (DB_ATTRIBUTE * attribute)
Definition at line 1102 of file db_info.c.
References sm_attribute::domain, and tp_domain::precision.
const char* db_attribute_name (DB_ATTRIBUTE * attribute)
Definition at line 1065 of file db_info.c.
References sm_attribute::header, sm_component::name, and NULL.
Referenced by check_missing_non_null_attrs(), chksum_print_attribute_list(), chksum_print_lower_bound_string(), chksum_print_pk_list(), class_attr_info(), db_gadget_create(), emit_attribute_def(), emit_class_meta(), emit_foreign_key(), emit_index_def(), emit_instance_attributes(), emit_reverse_unique_def(), emit_unique_def(), extract_objects(), fetch_constraint(), generate_natural_join_attrs_from_db_attrs(), get_attr_name(), get_reasonable_predicate(), ldr_compare_attribute_with_meta(), pt_check_union_type_compatibility_of_values_query(), pt_get_all_attributes_and_types(), pt_get_all_showstmt_attributes_and_types(), pt_get_attributes(), rm_api_get_info(), sch_attr_priv(), sch_exported_keys_or_cross_reference(), sch_imported_keys(), ux_get_generated_keys_client_insert(), ux_get_generated_keys_server_insert(), vid_encode_object(), and vt_api_get_index_by_name().
DB_ATTRIBUTE* db_attribute_next (DB_ATTRIBUTE * attribute)
Definition at line 1020 of file db_info.c.
References sm_attribute::header, ID_CLASS_ATTRIBUTE, sm_component::name_space, sm_component::next, NULL, and sm_attribute::order_link.
Referenced by check_missing_non_null_attrs(), chksum_print_attribute_list(), db_gadget_create(), db_validate(), delete_object_tuple(), do_alter_change_auto_increment(), do_alter_one_clause_with_template(), emit_class_attributes(), emit_class_meta(), emit_instance_attributes(), generate_natural_join_attrs_from_db_attrs(), get_attr_name(), has_dependencies(), ldr_compare_storage_order(), or_create(), pt_check_drop(), pt_check_union_type_compatibility_of_values_query(), pt_get_all_attributes_and_types(), pt_get_all_showstmt_attributes_and_types(), pt_get_attributes(), pt_resolve_vclass_args(), pt_to_delete_xasl(), sch_attr_priv(), sm_get_descriptor_component(), sm_truncate_class(), ux_get_generated_keys_client_insert(), ux_get_generated_keys_server_insert(), and vid_encode_object().
int db_attribute_order (DB_ATTRIBUTE * attribute)
Definition at line 1144 of file db_info.c.
References NULL, and sm_attribute::order.
Referenced by class_attr_info(), emit_class_meta(), and ldr_compare_attribute_with_meta().
DB_ATTRIBUTE* db_attribute_ordered_next (DB_ATTRIBUTE * attribute)
Definition at line 1047 of file db_info.c.
References NULL, and sm_attribute::order_link.
DB_TYPE db_attribute_type (DB_ATTRIBUTE * attribute)
Definition at line 1000 of file db_info.c.
References DB_TYPE_NULL, pr_type::id, NULL, and sm_attribute::type.
Referenced by emit_class_meta(), generate_natural_join_attrs_from_db_attrs(), get_reasonable_predicate(), ldr_compare_attribute_with_meta(), pt_check_drop(), pt_get_attributes(), and sm_get_descriptor_component().
int db_auth_login (char * signed_data, int len)
int db_auth_logout (void)
int db_bind_parameter_name (const char * name, DB_VALUE * value)
Definition at line 3813 of file db_vdb.c.
References pt_associate_label_with_value_check_reference().
int db_change_default (DB_OBJECT * classobj, const char * name, DB_VALUE * value)
int db_change_method_implementation (DB_OBJECT * classobj, const char * name, int class_method, const char * newname)
int db_change_query_spec (DB_OBJECT * vclass, const char * new_query, const int query_no)
Definition at line 558 of file db_virt.c.
References assert, AU_ALTER, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, er_errid(), ER_OBJ_INVALID_ARGUMENTS, error(), ERROR_SET, NO_ERROR, NULL, sm_update_class(), smt_change_query_spec(), smt_edit_class_mop(), and smt_quit().
int db_check_authorization (DB_OBJECT * op, DB_AUTH auth)
int db_check_authorization_and_grant_option (MOP op, DB_AUTH auth)
Definition at line 1872 of file db_admin.c.
References au_fetch_class(), AU_FETCH_READ, AU_GRANT_SHIFT, CHECK_1ARG_ERROR, and CHECK_CONNECT_ERROR.
int db_check_single_query (DB_SESSION * session)
Definition at line 3695 of file db_vdb.c.
References db_session::dimension, ER_IT_MULTIPLE_STATEMENT, and NO_ERROR.
Referenced by do_process_prepare_statement(), ux_execute(), ux_execute_all(), and ux_execute_call().
int db_chn (DB_OBJECT * obj, DB_FETCH_MODE purpose)
Definition at line 2660 of file db_admin.c.
References DB_FETCH_READ, DB_FETCH_WRITE, and locator_get_cache_coherency_number().
void db_clear_host_connected (void)
Definition at line 851 of file db_admin.c.
References boot_clear_host_connected().
Referenced by applyinfo(), and ux_database_connect().
void db_clear_host_status (void)
Definition at line 580 of file db_admin.c.
References db_host_status_list::connected_host_status, DB_HS_NORMAL, db_host_status_list::hostlist, db_host_status::hostname, i, db_host_status_list::last_host_idx, NULL, and db_host_status::status.
Referenced by boot_restart_client().
void db_close_session (DB_SESSION * session)
Definition at line 3319 of file db_vdb.c.
References db_close_session_local().
Referenced by alloc_dynamic(), au_compute_groups(), au_delete_auth_of_dropping_table(), au_drop_user(), au_get_new_auth(), csql_display_trace(), csql_execute_statements(), db_check_limit_need_recompile(), do_check_rows_for_null(), do_run_update_query_for_class(), fn_get_query_info(), free_cursor(), free_dynamic(), free_repetitive(), hm_session_free(), ldr_exec_query_from_file(), sch_query_execute(), sm_truncate_using_delete(), tzc_compute_timezone_checksum(), uci_execute_immediate(), uci_open_cs(), uci_prepare(), uci_static(), ux_execute_array(), ux_execute_batch(), and ux_prepare().
int db_commit_is_needed (void)
Definition at line 1154 of file db_admin.c.
References CHECK_CONNECT_FALSE, and tran_has_updated().
Referenced by csql_exit_session().
int db_commit_transaction (void)
Definition at line 1091 of file db_admin.c.
References CHECK_CONNECT_ERROR, and tran_commit().
Referenced by addvoldb(), backupdb(), check_commit(), checkdb(), chksum_drop_and_create_checksum_table(), chksum_start(), compactdb_start(), createdb(), csql_do_session_cmd(), csql_execute_statements(), csql_exit_session(), csql_help_info(), do_reclaim_class_addresses(), gen_tz(), installdb(), la_commit_transaction(), la_delete_ha_apply_info(), la_get_last_ha_applied_info(), ldr_exec_query_from_file(), ldr_sa_load(), loaddb_internal(), main(), optimizedb(), renamedb(), restoreslave(), synccolldb(), tde(), tzc_compute_timezone_checksum(), uci_commit(), ux_end_tran(), ux_execute_array(), and ux_execute_batch().
int db_compile_statement (DB_SESSION * session)
Definition at line 766 of file db_vdb.c.
References CHECK_CONNECT_MINUSONE, db_compile_statement_local(), and er_clear().
Referenced by au_compute_groups(), au_drop_user(), au_get_new_auth(), csql_display_trace(), csql_execute_statements(), do_check_rows_for_null(), do_recompile_and_execute_prepared_statement(), do_run_update_query_for_class(), fn_get_query_info(), ldr_exec_query_from_file(), sch_query_execute(), sm_truncate_using_delete(), tzc_compute_timezone_checksum(), uci_execute_immediate(), uci_open_cs(), uci_prepare(), uci_static(), ux_execute(), ux_execute_all(), ux_execute_array(), ux_execute_batch(), and ux_prepare().
int db_constrain_non_null (DB_OBJECT * classobj, const char * name, int class_attribute, int on_or_off)
int db_constrain_unique (DB_OBJECT * classobj, const char * name, int on_or_off)
const int* db_constraint_asc_desc (DB_CONSTRAINT * constraint)
Definition at line 2070 of file db_info.c.
References sm_class_constraint::asc_desc, and NULL.
Referenced by chksum_print_lower_bound_string(), chksum_print_pk_list(), do_create_midxkey_for_constraint(), and emit_index_def().
DB_ATTRIBUTE** db_constraint_attributes (DB_CONSTRAINT * constraint)
Definition at line 2052 of file db_info.c.
References sm_class_constraint::attributes, and NULL.
Referenced by chksum_print_lower_bound_string(), chksum_print_pk_list(), emit_foreign_key(), emit_index_def(), emit_reverse_unique_def(), emit_unique_def(), fetch_constraint(), sch_constraint(), sch_exported_keys_or_cross_reference(), and sch_imported_keys().
DB_CONSTRAINT* db_constraint_find_primary_key (DB_CONSTRAINT * constraint)
Definition at line 1956 of file db_info.c.
References db_constraint_next(), NULL, SM_CONSTRAINT_PRIMARY_KEY, and sm_class_constraint::type.
Referenced by chksum_start(), sch_exported_keys_or_cross_reference(), and sch_imported_keys().
const char* db_constraint_name (DB_CONSTRAINT * constraint)
Definition at line 2031 of file db_info.c.
References sm_class_constraint::name, and NULL.
Referenced by fetch_constraint(), sch_exported_keys_or_cross_reference(), and sch_imported_keys().
DB_CONSTRAINT* db_constraint_next (DB_CONSTRAINT * constraint)
Definition at line 1938 of file db_info.c.
References sm_class_constraint::next, and NULL.
Referenced by db_constraint_find_primary_key(), emit_foreign_key(), emit_index_def(), emit_reverse_unique_def(), emit_unique_def(), fetch_constraint(), sch_constraint(), sch_exported_keys_or_cross_reference(), and sch_imported_keys().
DB_CONSTRAINT_TYPE db_constraint_type (DB_CONSTRAINT * constraint)
DB_OBJECT* db_copy (DB_OBJECT * sourcemop)
DB_OBJECT* db_create (DB_OBJECT * obj)
Definition at line 69 of file db_obj.c.
References CHECK_1ARG_NULL, CHECK_CONNECT_NULL, CHECK_MODIFICATION_NULL, CHECK_PARTITION_PARENT, CHECK_PARTITION_SUBS, db_create_internal(), do_check_partitioned_class(), error(), NO_ERROR, and NULL.
DB_OBJECT* db_create_by_name (const char * name)
Definition at line 115 of file db_obj.c.
References ARG_FILE_LINE, CHECK_1ARG_NULL, CHECK_CONNECT_NULL, CHECK_MODIFICATION_NULL, db_create_by_name_internal(), do_is_partitioned_subclass(), ER_ERROR_SEVERITY, ER_NOT_ALLOWED_ACCESS_TO_PARTITION, er_set(), and NULL.
DB_OBJECT* db_create_class (const char * name)
Definition at line 70 of file db_class.c.
References assert_release, CHECK_1ARG_NULL, CHECK_CONNECT_NULL, CHECK_MODIFICATION_NULL, LC_CLASSNAME_RESERVED, locator_reserve_class_name(), sm_template::name, NO_ERROR, NULL, OID_INITIALIZER, sm_update_class(), smt_def_class(), and smt_quit().
Referenced by au_install(), and catcls_class_install().
DB_OBJECT* db_create_trigger (const char * name, DB_TRIGGER_STATUS status, double priority, DB_TRIGGER_EVENT event, DB_OBJECT * class_obj, const char * attr, DB_TRIGGER_TIME cond_time, const char * cond_source, DB_TRIGGER_TIME action_time, DB_TRIGGER_ACTION action_type, const char * action_source)
Definition at line 1301 of file db_obj.c.
References CHECK_CONNECT_NULL, CHECK_MODIFICATION_NULL, NULL, and tr_create_trigger().
DB_OBJECT* db_create_vclass (const char * name)
Definition at line 140 of file db_virt.c.
References ARG_FILE_LINE, assert, assert_release, CHECK_CONNECT_NULL, CHECK_MODIFICATION_NULL, er_errid(), ER_ERROR_SEVERITY, er_set(), ER_SM_CLASS_WITH_PRIM_NAME, error(), LC_CLASSNAME_RESERVED, locator_reserve_class_name(), sm_template::name, NO_ERROR, NULL, OID_INITIALIZER, pr_find_type(), pt_is_reserved_word(), sm_update_class(), SM_VCLASS_CT, smt_def_typed_class(), and smt_quit().
Referenced by boot_define_view_attribute(), boot_define_view_attribute_set_domain(), boot_define_view_authorization(), boot_define_view_class(), boot_define_view_db_charset(), boot_define_view_db_collation(), boot_define_view_index(), boot_define_view_index_key(), boot_define_view_method(), boot_define_view_method_argument(), boot_define_view_method_argument_set_domain(), boot_define_view_method_file(), boot_define_view_partition(), boot_define_view_stored_procedure(), boot_define_view_stored_procedure_arguments(), boot_define_view_super_class(), boot_define_view_trigger(), and boot_define_view_vclass().
int db_decode_object (const char * string, DB_OBJECT ** object)
Definition at line 1805 of file db_obj.c.
References NO_ERROR, and vid_decode_object().
const char* db_default_expression_string (DB_DEFAULT_EXPR_TYPE default_expr_type)
Definition at line 4947 of file db_macro.c.
DB_OBJECT* db_dfind_multi_unique (DB_OBJECT * classobj, int size, DB_ATTDESC * attdesc[], DB_VALUE * values[], DB_FETCH_MODE purpose)
DB_OBJECT* db_dfind_unique (DB_OBJECT * classobj, DB_ATTDESC * attdesc, DB_VALUE * value, DB_FETCH_MODE purpose)
int db_dget (DB_OBJECT * obj, DB_ATTDESC * attribute, DB_VALUE * value)
Definition at line 889 of file db_obj.c.
References CHECK_CONNECT_ERROR, and obj_desc_get().
Referenced by mq_get_expression().
int db_disable_modification (void)
Definition at line 1001 of file db_admin.c.
References db_Disable_modifications, and NO_ERROR.
Referenced by boot_restart_client(), method_invoke_for_server(), and method_receive_results_for_stand_alone().
bool db_disable_trigger (void)
Definition at line 570 of file db_admin.c.
References tr_set_execution_state().
Referenced by applylogdb(), csql(), csql_do_session_cmd(), loaddb_internal(), and ux_database_connect().
bool db_does_connected_host_have_status (int status)
Definition at line 755 of file db_admin.c.
References db_host_status_list::connected_host_status, NULL, and db_host_status::status.
Referenced by db_need_reconnect(), and report_abnormal_host_status().
DB_OBJECT* db_domain_class (const DB_DOMAIN * domain)
Definition at line 4030 of file db_macro.c.
References tp_domain::class_mop, NULL, tp_Type_object, and tp_domain::type.
Referenced by check_domain_dependencies(), check_referenced_domain(), class_referenced_by_domain(), emit_domain_def(), get_domain_str(), pt_check_alter(), pt_check_drop(), pt_domain_to_data_type(), pt_get_attributes(), and sm_get_descriptor_component().
int db_domain_codeset (const DB_DOMAIN * domain)
Definition at line 4116 of file db_macro.c.
References tp_domain::codeset, and NULL.
Referenced by get_set_domain(), oid_attr_info_set(), prepare_column_list_info_set(), pt_domain_to_data_type(), ux_col_get(), ux_get_parameter_info(), and ux_make_out_rs().
DB_DOMAIN* db_domain_next (const DB_DOMAIN * domain)
Definition at line 3974 of file db_macro.c.
References tp_domain::next, and NULL.
Referenced by check_domain_dependencies(), check_referenced_domain(), class_referenced_by_domain(), emit_domain_def(), get_domain_str(), get_set_domain(), pt_domain_to_data_type(), and pt_get_attributes().
int db_domain_precision (const DB_DOMAIN * domain)
Definition at line 4079 of file db_macro.c.
References NULL, and tp_domain::precision.
Referenced by class_attr_info(), copy_column_spec_to_sqlda(), emit_domain_def(), get_domain_str(), get_set_domain(), oid_attr_info_set(), prepare_column_list_info_set(), pt_domain_to_data_type(), rm_api_get_info(), ux_col_get(), ux_get_generated_keys_client_insert(), ux_get_generated_keys_server_insert(), ux_get_parameter_info(), ux_make_out_rs(), value_to_db_value(), and vt_api_init_domain().
const char* db_domain_raw_json_schema (const DB_DOMAIN * domain)
Definition at line 4147 of file db_macro.c.
References db_json_get_schema_raw_from_validator(), tp_domain::json_validator, and NULL.
Referenced by emit_domain_def().
int db_domain_scale (const DB_DOMAIN * domain)
Definition at line 4098 of file db_macro.c.
References NULL, and tp_domain::scale.
Referenced by class_attr_info(), copy_column_spec_to_sqlda(), emit_domain_def(), get_domain_str(), get_set_domain(), oid_attr_info_set(), prepare_column_list_info_set(), pt_domain_to_data_type(), rm_api_get_info(), ux_col_get(), ux_get_generated_keys_client_insert(), ux_get_generated_keys_server_insert(), ux_get_parameter_info(), ux_make_out_rs(), value_to_db_value(), and vt_api_init_domain().
DB_DOMAIN* db_domain_set (const DB_DOMAIN * domain)
Definition at line 4060 of file db_macro.c.
References DB_TYPE_MIDXKEY, NULL, pr_is_set_type(), tp_domain::setdomain, and TP_DOMAIN_TYPE.
Referenced by check_domain_dependencies(), check_referenced_domain(), class_referenced_by_domain(), emit_domain_def(), fn_collection(), get_domain_str(), get_set_domain(), pt_domain_to_data_type(), and pt_get_attributes().
DB_TYPE db_domain_type (const DB_DOMAIN * domain)
Definition at line 4006 of file db_macro.c.
References TP_DOMAIN_TYPE.
int db_dput (DB_OBJECT * obj, DB_ATTDESC * attribute, DB_VALUE * value)
Definition at line 908 of file db_obj.c.
References CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, CHECK_PARTITION_NONE, db_dput_internal(), db_get_class(), do_check_partitioned_class(), error(), sm_descriptor::name, and NO_ERROR.
int db_drop (DB_OBJECT * obj)
Definition at line 190 of file db_obj.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, and obj_delete().
Referenced by delete_object_tuple(), do_drop_serial(), fn_oid(), ldr_restore_pin_and_drop_obj(), orp_oid_delete(), res_api_delete_row(), tr_drop_trigger_internal(), and uci_delete_cs().
int db_drop_attribute (DB_OBJECT * classobj, const char * name)
int db_drop_class (DB_OBJECT * classobj)
int db_drop_class_attribute (DB_OBJECT * classobj, const char * name)
int db_drop_class_ex (DB_OBJECT * classobj, bool is_cascade_constraints)
int db_drop_class_method (DB_OBJECT * classobj, const char * name)
int db_drop_class_resolution (DB_OBJECT * classobj, DB_OBJECT * super, const char * name)
int db_drop_constraint (MOP classmop, DB_CONSTRAINT_TYPE constraint_type, const char * constraint_name, const char ** att_names, int class_attributes)
Definition at line 1826 of file db_class.c.
References assert, CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, er_errid(), free_and_init, NO_ERROR, NULL, sm_drop_constraint(), and sm_produce_constraint_name_mop().
Referenced by db_constrain_non_null(), db_constrain_unique(), and db_drop_index().
int db_drop_deferred_activities (DB_OBJECT * trigger_obj, DB_OBJECT * target)
Definition at line 1527 of file db_obj.c.
References CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, and tr_drop_deferred_activities().
int db_drop_element_domain (DB_OBJECT * classobj, const char * name, const char * domain)
int db_drop_index (DB_OBJECT * classobj, const char * attname)
int db_drop_member (DB_OBJECT * user, DB_OBJECT * member)
Definition at line 1719 of file db_admin.c.
References au_drop_member(), CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and CHECK_MODIFICATION_ERROR.
int db_drop_method (DB_OBJECT * classobj, const char * name)
int db_drop_method_file (DB_OBJECT * classobj, const char * name)
int db_drop_method_files (DB_OBJECT * classobj)
int db_drop_query_spec (DB_OBJECT * vclass, const int query_no)
Definition at line 507 of file db_virt.c.
References assert, AU_ALTER, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, er_errid(), ER_OBJ_INVALID_ARGUMENTS, error(), ERROR_SET, NO_ERROR, NULL, sm_update_class(), smt_drop_query_spec(), smt_edit_class_mop(), and smt_quit().
int db_drop_resolution (DB_OBJECT * classobj, DB_OBJECT * super, const char * name)
int db_drop_shared_attribute (DB_OBJECT * classobj, const char * name)
void db_drop_statement (DB_SESSION * session, int stmt_id)
Definition at line 3196 of file db_vdb.c.
References NULL, db_session::parser, parser_free_tree(), pt_free_statement_xasl_id(), db_session::stage, StatementInitialStage, and db_session::statements.
Referenced by csql_execute_statements().
int db_drop_super (DB_OBJECT * classobj, DB_OBJECT * super)
int db_drop_super_connect (DB_OBJECT * classobj, DB_OBJECT * super)
int db_drop_trigger (DB_OBJECT * obj)
Definition at line 1325 of file db_obj.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, and tr_drop_trigger().
int db_drop_user (DB_OBJECT * user)
Definition at line 1668 of file db_admin.c.
References au_drop_user(), CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, and CHECK_MODIFICATION_ERROR.
Referenced by do_drop_user().
int db_dsend (DB_OBJECT * obj, DB_METHDESC * method, DB_VALUE * returnval, ...)
Definition at line 999 of file db_obj.c.
References CHECK_CONNECT_ERROR, error(), NO_ERROR, and obj_desc_send_va().
int db_dsend_argarray (DB_OBJECT * obj, DB_METHDESC * method, DB_VALUE * returnval, DB_VALUE ** args)
Definition at line 1042 of file db_obj.c.
References CHECK_CONNECT_ERROR, and obj_desc_send_array().
int db_dsend_arglist (DB_OBJECT * obj, DB_METHDESC * method, DB_VALUE * returnval, DB_VALUE_LIST * args)
Definition at line 1022 of file db_obj.c.
References CHECK_CONNECT_ERROR, and obj_desc_send_list().
int db_dsend_quick (DB_OBJECT * obj, DB_METHDESC * method, DB_VALUE * returnval, int nargs, DB_VALUE ** args)
Definition at line 1067 of file db_obj.c.
References CHECK_CONNECT_ERROR, and obj_desc_send_array_quick().
int db_enable_modification (void)
Definition at line 1015 of file db_admin.c.
References db_Disable_modifications, and NO_ERROR.
Referenced by method_invoke_for_server(), and method_receive_results_for_stand_alone().
bool db_enable_trigger (void)
Definition at line 558 of file db_admin.c.
References tr_set_execution_state().
Referenced by ux_database_connect().
int db_encode_object (DB_OBJECT * object, char * string, int allocated_length, int * actual_length)
Definition at line 1787 of file db_obj.c.
References NO_ERROR, and vid_encode_object().
int db_end_session (void)
Definition at line 1029 of file db_admin.c.
References CHECK_CONNECT_ERROR, csession_end_session(), and db_get_session_id().
Referenced by csql_do_session_cmd(), csql_exit_cleanup(), csql_exit_session(), loaddb_internal(), start_csql(), and ux_end_session().
int db_error_code (void)
Definition at line 2143 of file db_admin.c.
References er_errid().
Referenced by csql(), csql_check_server_down(), csql_execute_statements(), db_error_code_test(), extract_classes(), fetch_attribute(), fetch_result(), fn_collection(), fn_get_query_info(), fn_oid(), oid_attr_info_set(), prepare_column_list_info_set(), sch_exported_keys_or_cross_reference(), sch_imported_keys(), sch_query_execute(), unloaddb(), ux_check_object(), ux_execute(), ux_execute_all(), ux_execute_array(), ux_execute_batch(), ux_get_attr_type_str(), ux_get_class_num_objs(), ux_oid_put(), and ux_prepare().
int db_error_init (const char * logfile)
Definition at line 2164 of file db_admin.c.
References er_init(), prm_get_integer_value(), and PRM_ID_ER_EXIT_ASK.
const char* db_error_string (int level)
Definition at line 2116 of file db_admin.c.
References er_msg().
Referenced by acldb(), addvoldb(), alterdbhost(), applyinfo(), applylogdb(), backupdb(), changemode(), check_commit(), checkdb(), checksumdb(), compactdb(), copydb(), copylogdb(), createdb(), csql_errmsg(), db_error_string_test(), deletedb(), diagdb(), display_error(), do_insert_template(), error_info_set_with_msg(), extract_classes(), gen_tz(), genlocale(), hb_master_init(), installdb(), kill_transactions(), killtran(), la_apply_repl_log(), la_log_page_check(), ldr_exec_query_from_file(), ldr_sa_load(), loaddb_internal(), lockdb(), main(), mq_get_expression(), optimizedb(), paramdump(), patchdb(), plandump(), pt_check_sub_insert(), pt_check_with_info(), pt_class_pre_fetch(), pt_difference_sets(), pt_evaluate_tree_internal(), pt_make_flat_name_list(), pt_product_sets(), pt_semantic_check_local(), pt_seq_value_to_db(), pt_set_table_to_db(), pt_set_value_to_db(), pt_union_sets(), renamedb(), restoredb(), restoreslave(), spacedb(), statdump(), synccolldb(), tde(), tranlist(), unloaddb(), ux_database_connect(), ux_execute_array(), ux_execute_batch(), and vacuumdb().
int db_execute (const char * CSQL_query, DB_QUERY_RESULT ** result, DB_QUERY_ERROR * query_error)
Definition at line 1836 of file db_query.c.
References db_compile_and_execute_queries_internal(), and DB_NO_OIDS.
Referenced by chksum_calculate_checksum(), chksum_drop_and_create_checksum_table(), chksum_get_next_lower_bound(), chksum_get_prev_checksum_results(), chksum_insert_schema_definition(), chksum_report_diff(), chksum_report_schema_diff(), chksum_report_summary(), chksum_update_current_schema_definition(), chksum_update_master_checksum(), delete_all_ha_apply_info(), get_codeset_from_db_root(), and la_update_query_execute().
int db_execute_and_keep_statement (DB_SESSION * session, int stmt, DB_QUERY_RESULT ** result)
Definition at line 2906 of file db_vdb.c.
References CHECK_CONNECT_MINUSONE, db_execute_and_keep_statement_local(), db_invalidate_mvcc_snapshot_before_statement(), db_set_read_fetch_instance_version(), err, and LC_FETCH_MVCC_VERSION.
Referenced by stmt_exec_internal(), stmt_exec_one_statement(), stmt_exec_prepared_batch_internal(), uci_execute(), uci_open_cs(), ux_execute(), ux_execute_all(), ux_execute_array(), and ux_execute_call().
int db_execute_deferred_activities (DB_OBJECT * trigger_obj, DB_OBJECT * target)
Definition at line 1496 of file db_obj.c.
References CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, and tr_execute_deferred_activities().
int db_execute_oid (const char * CSQL_query, DB_QUERY_RESULT ** result, DB_QUERY_ERROR * query_error)
Definition at line 1852 of file db_query.c.
References ARG_FILE_LINE, db_query_type::attr_name, C_BEFORE, CHECK_1ARG_NULL, CHECK_CONNECT_NULL, db_query_result::col_cnt, db_objfetch_result::crs_pos, db_alloc_query_format(), db_alloc_query_result(), db_compile_and_execute_queries_internal(), db_free_query_result(), db_init_query_result(), DB_NO_OIDS, DB_ROW_OIDS, db_query_type::db_type, db_value_copy(), DB_VALUE_TYPE, db_query_type::domain, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), db_query_type::name, NULL, db_query_result::o, db_query_result::oid_included, db_query_type::original_name, db_query_result::query_type, db_query_result::res, db_query_type::size, db_query_type::spec_name, db_query_type::src_domain, strlen, T_OBJFETCH, db_query_result::type, db_query_result::type_cnt, and db_objfetch_result::valptr_list.
int db_execute_statement (DB_SESSION * session, int stmt, DB_QUERY_RESULT ** result)
Definition at line 2978 of file db_vdb.c.
References CHECK_CONNECT_MINUSONE, db_execute_statement_local(), db_invalidate_mvcc_snapshot_before_statement(), db_set_read_fetch_instance_version(), err, and LC_FETCH_MVCC_VERSION.
Referenced by csql_display_trace(), csql_execute_statements(), fn_get_query_info(), ldr_exec_query_from_file(), sch_query_execute(), uci_execute_immediate(), uci_static(), and ux_execute_batch().
DB_OBJLIST* db_fetch_all_classes (DB_FETCH_MODE mode)
Definition at line 203 of file db_info.c.
References CHECK_CONNECT_NULL, and sm_fetch_all_classes().
Referenced by chksum_start(), db_find_class_of_index(), and help_class_names().
DB_OBJLIST* db_fetch_all_objects (DB_OBJECT * op, DB_FETCH_MODE mode)
Definition at line 178 of file db_info.c.
References CHECK_1ARG_NULL, CHECK_CONNECT_NULL, DB_FETCH_QUERY_READ, DB_FETCH_QUERY_WRITE, DB_FETCH_READ, DB_FETCH_WRITE, and sm_fetch_all_objects().
int db_fetch_array (DB_OBJECT ** objects, DB_FETCH_MODE mode, int quit_on_error)
Definition at line 2216 of file db_admin.c.
References assert, CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, cubregex::count(), DB_FETCH_READ, DB_FETCH_WRITE, er_errid(), error(), locator_fetch_set(), NO_ERROR, and NULL.
Referenced by db_fetch_list().
DB_OBJLIST* db_fetch_base_classes (DB_FETCH_MODE mode)
Definition at line 223 of file db_info.c.
References CHECK_CONNECT_NULL, and sm_fetch_all_base_classes().
int db_fetch_composition (DB_OBJECT * object, DB_FETCH_MODE mode, int max_level, int quit_on_error)
Definition at line 2407 of file db_admin.c.
References ARG_FILE_LINE, assert, CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, DB_FETCH_READ, DB_FETCH_WRITE, db_real_instance(), er_errid(), ER_OBJ_INVALID_ARGUMENTS, er_set(), ER_WARNING_SEVERITY, error(), locator_fetch_nested(), NO_ERROR, NULL, and WS_ISVID.
int db_fetch_list (DB_OBJLIST * objects, DB_FETCH_MODE mode, int quit_on_error)
Definition at line 2254 of file db_admin.c.
References db_fetch_array(), db_list_length(), error(), free_and_init, i, db_objlist::next, NO_ERROR, NULL, and db_objlist::op.
Referenced by vid_getall_mops().
int db_fetch_seq (DB_SEQ * set, DB_FETCH_MODE mode, int quit_on_error)
Definition at line 2388 of file db_admin.c.
References fetch_set_internal().
int db_fetch_set (DB_COLLECTION * set, DB_FETCH_MODE mode, int quit_on_error)
Definition at line 2372 of file db_admin.c.
References fetch_set_internal().
Referenced by au_get_set(), and set_to_string().
int db_find_all_triggers (DB_OBJLIST ** list)
Definition at line 1394 of file db_obj.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, and tr_find_all_triggers().
Referenced by sch_trigger().
DB_OBJECT* db_find_class (const char * name)
Definition at line 133 of file db_info.c.
References CHECK_1ARG_NULL, CHECK_CONNECT_NULL, and sm_find_class().
Referenced by au_add_method_check_authorization(), au_find_user(), au_find_user_to_drop(), chksum_init_checksum_tables(), chksum_report(), clist_init(), convert_speclist_to_objlist(), db_gadget_create(), db_get_attribute_by_name(), do_add_resolutions(), do_add_supers(), do_alter_change_auto_increment(), do_alter_change_col_comment(), do_alter_change_default_cs_coll(), do_alter_change_tbl_comment(), do_alter_clause_change_attribute(), do_alter_clause_drop_index(), do_alter_index_comment(), do_alter_index_rebuild(), do_alter_index_status(), do_alter_one_clause_with_template(), do_create_entity(), do_create_index(), do_create_trigger(), do_drop_index(), do_get_stats(), do_grant(), do_is_partitioned_subclass(), do_recreate_renamed_class_indexes(), do_rename_internal(), do_revoke(), do_update_stats(), drop_class_name(), emit_stored_procedure(), fetch_attribute(), help_print_info(), jsp_add_stored_procedure(), jsp_add_stored_procedure_argument(), jsp_find_stored_procedure(), la_apply_delete_log(), la_apply_insert_log(), la_apply_update_log(), la_get_ha_apply_info(), ldr_act_set_ref_class(), ldr_compare_storage_order(), ldr_find_class(), load_has_authorization(), optimizedb(), pt_attr_refers_to_self(), pt_check_attribute_domain(), pt_check_create_index(), pt_check_cume_dist_percent_rank_order_by(), pt_check_drop(), pt_check_truncate(), pt_check_union_type_compatibility_of_values_query(), pt_check_with_info(), pt_data_type_to_db_domain(), pt_find_users_class(), pt_fold_const_expr(), pt_node_data_type_to_db_domain(), pt_resolve_default_external(), pt_resolve_using_index(), pt_semantic_check_local(), pt_set_domain_class(), pt_type_assignable(), pt_vclass_compatible(), sch_attr_priv(), sch_class_priv(), sch_constraint(), sch_exported_keys_or_cross_reference(), sch_imported_keys(), sch_methfile_info(), sch_method_info(), sch_primary_key(), sch_superclass(), set_column_info(), sm_update_catalog_statistics(), synccoll_force(), trigger_to_object(), truncate_class_name(), truncate_need_repl_log(), update_locksets_for_multiple_rename(), ux_get_attr_type_str(), and ux_get_class_num_objs().
DB_OBJECT* db_find_class_of_index (const char * index, DB_CONSTRAINT_TYPE type)
Definition at line 74 of file db_info.c.
References ARG_FILE_LINE, au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_1ARG_NULL, CHECK_CONNECT_NULL, classobj_find_class_constraint(), sm_class::constraints, db_fetch_all_classes(), DB_FETCH_READ, DB_IS_CONSTRAINT_INDEX_FAMILY, ER_OBJ_INVALID_ARGUMENTS, er_set(), ER_SM_INDEX_AMBIGUOUS, ER_SM_NO_INDEX, ER_WARNING_SEVERITY, db_objlist::next, NO_ERROR, NULL, db_objlist::op, and SM_MAP_DB_INDEX_CONSTRAINT_TO_SM_CONSTRAINT.
Referenced by pt_find_class_of_index().
int db_find_event_triggers (DB_TRIGGER_EVENT event, DB_OBJECT * class_obj, const char * attr, DB_OBJLIST ** list)
Definition at line 1421 of file db_obj.c.
References CHECK_CONNECT_ERROR, and tr_find_event_triggers().
DB_OBJECT* db_find_multi_unique (DB_OBJECT * classobj, int size, char * attnames[], DB_VALUE * values[], DB_FETCH_MODE purpose)
int db_find_or_create_session (const char * db_user, const char * program_name)
Definition at line 2885 of file db_admin.c.
References boot_get_host_name(), csession_find_or_create_session(), DB_EMPTY_SESSION, db_get_server_session_key(), db_get_session_id(), DB_ROW_COUNT_NOT_SET, db_set_session_id(), db_update_row_count_cache(), err, and NO_ERROR.
Referenced by boot_initialize_client(), boot_restart_client(), and ux_database_connect().
DB_OBJECT* db_find_primary_key (MOP classmop, const DB_VALUE ** values, int size, DB_FETCH_MODE purpose)
Definition at line 1138 of file db_obj.c.
References ARG_FILE_LINE, AU_FETCH_READ, AU_FETCH_UPDATE, CHECK_2ARGS_NULL, CHECK_CONNECT_NULL, DB_FETCH_WRITE, ER_OBJ_INVALID_ARGUMENTS, er_set(), ER_WARNING_SEVERITY, NULL, and obj_find_primary_key().
DB_OBJECT* db_find_trigger (const char * name)
Definition at line 1370 of file db_obj.c.
References CHECK_1ARG_NULL, CHECK_CONNECT_NULL, and tr_find_trigger().
DB_OBJECT* db_find_unique (DB_OBJECT * classobj, const char * attname, DB_VALUE * value)
DB_OBJECT* db_find_unique_write_mode (DB_OBJECT * classobj, const char * attname, DB_VALUE * value)
DB_OBJECT* db_find_user (const char * name)
Definition at line 1606 of file db_admin.c.
References au_find_user(), CHECK_1ARG_NULL, and CHECK_CONNECT_NULL.
Referenced by do_alter_user(), do_create_user(), do_grant(), do_revoke(), help_class_names(), jsp_alter_stored_procedure(), pt_check_grant_revoke(), and pt_check_user_exists().
int db_find_user_to_drop (const char * name, DB_OBJECT ** user)
Definition at line 1626 of file db_admin.c.
References au_find_user_to_drop(), CHECK_1ARG_ERROR, and CHECK_CONNECT_ERROR.
Referenced by do_drop_user().
void db_flush_static_methods (void)
Definition at line 2564 of file db_admin.c.
References sm_flush_static_methods().
void db_force_method_reload (DB_OBJECT * obj)
void db_fprint (FILE * fp, DB_OBJECT * obj)
Definition at line 1268 of file db_obj.c.
References CHECK_CONNECT_VOID, help_print_obj(), and NULL.
void db_free_attribute_descriptor (DB_ATTDESC * descriptor)
Definition at line 835 of file db_obj.c.
References sm_free_descriptor().
Referenced by db_gadget_destroy(), do_insert_template(), init_update_data(), insert_subquery_results(), ldr_clear_and_free_context(), ldr_refresh_attrs(), update_class_attributes(), update_object_by_oid(), and update_objs_for_list_file().
void db_free_method_descriptor (DB_METHDESC * descriptor)
Definition at line 875 of file db_obj.c.
References sm_free_descriptor().
void db_free_query (DB_SESSION * session)
Definition at line 3683 of file db_vdb.c.
References db_session::parser, and pt_end_query().
Referenced by csql_execute_statements(), do_run_update_query_for_class(), and sm_truncate_using_delete().
int db_freepgs (const char * vlabel)
Definition at line 2054 of file db_admin.c.
References CHECK_CONNECT_ZERO, disk_get_free_numpages(), and NULL_VOLID.
int db_get (DB_OBJECT * object, const char * attpath, DB_VALUE * value)
Definition at line 233 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and obj_get_path().
Referenced by au_add_member_internal(), au_check_serial_authorization(), au_drop_member(), cur_tuple(), delete_object_tuple(), object_printer::describe_attribute(), do_alter_serial(), do_change_auto_increment_serial(), do_drop_serial(), do_get_serial_cached_num(), do_reset_auto_increment_serial(), do_update_maxvalue_of_auto_increment_serial(), drop_stored_procedure(), emit_autoincrement_def(), emit_class_owner(), emit_instance_attributes(), emit_stored_procedure(), emit_stored_procedure_args(), fn_collection(), get_user_name(), help_class_names(), object_description::init(), jsp_alter_stored_procedure(), jsp_do_call_stored_procedure(), jsp_get_return_type(), object_to_trigger(), oid_attr_info_set(), oid_data_set(), pt_eval_path_expr(), sm_delete_class_mop(), sm_rename_class(), ux_get_generated_keys_client_insert(), ux_get_generated_keys_server_insert(), vid_encode_object(), and vt_api_get_db_value().
DB_OBJLIST* db_get_all_classes (void)
Definition at line 267 of file db_info.c.
References CHECK_CONNECT_NULL, DB_FETCH_QUERY_READ, and sm_fetch_all_classes().
Referenced by sch_class_priv().
DB_OBJLIST* db_get_all_objects (DB_OBJECT * classobj)
Definition at line 246 of file db_info.c.
References CHECK_1ARG_NULL, CHECK_CONNECT_NULL, DB_FETCH_QUERY_READ, and sm_fetch_all_objects().
Referenced by au_start(), and emit_stored_procedure().
DB_OBJLIST* db_get_all_vclasses (void)
Definition at line 3423 of file db_vdb.c.
References db_get_all_chosen_classes(), and is_vclass_object().
DB_OBJLIST* db_get_all_vclasses_on_ldb (void)
Definition at line 3412 of file db_vdb.c.
References NULL.
DB_ATTRIBUTE* db_get_attribute (DB_OBJECT * obj, const char * name)
Definition at line 791 of file db_info.c.
References ARG_FILE_LINE, au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_2ARGS_NULL, CHECK_CONNECT_NULL, classobj_find_attribute(), ER_OBJ_INVALID_ATTRIBUTE, er_set(), ER_WARNING_SEVERITY, NO_ERROR, and NULL.
Referenced by check_target(), chksum_init_checksum_tables(), db_attdesc_domain(), db_get_attribute_by_name(), db_query_format_is_non_null(), do_alter_one_clause_with_template(), fetch_attribute(), fn_collection(), get_attr_type(), insert_object_attr(), oid_attr_info_set(), pt_check_cume_dist_percent_rank_order_by(), pt_check_union_type_compatibility_of_values_query(), pt_resolve_default_external(), pt_resolve_star(), pt_to_merge_update_xasl(), pt_to_odku_info(), pt_to_update_xasl(), set_column_info(), and ux_get_attr_type_str().
DB_ATTRIBUTE* db_get_attribute_by_name (const char * class_name, const char * attribute_name)
Definition at line 823 of file db_info.c.
References db_find_class(), db_get_attribute(), and NULL.
Referenced by is_attribute_primary_key(), pt_check_defaultf(), and pt_resolve_default_value().
DB_OBJECT* db_get_attribute_class (DB_OBJECT * obj, const char * name)
int db_get_attribute_descriptor (DB_OBJECT * obj, const char * attname, int class_attribute, int for_update, DB_ATTDESC ** descriptor)
Definition at line 763 of file db_obj.c.
References CHECK_3ARGS_ERROR, CHECK_CONNECT_ERROR, and sm_get_attribute_descriptor().
Referenced by db_gadget_create(), do_insert_template(), insert_subquery_results(), ldr_act_add_attr(), ldr_refresh_attrs(), mq_get_expression(), and update_object_tuple().
DB_DOMAIN* db_get_attribute_domain (DB_OBJECT * obj, const char * name)
DB_NAMELIST* db_get_attribute_names (DB_OBJECT * obj)
DB_TYPE db_get_attribute_type (DB_OBJECT * obj, const char * name)
DB_ATTRIBUTE* db_get_attributes (DB_OBJECT * obj)
Definition at line 908 of file db_info.c.
References ARG_FILE_LINE, au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_1ARG_NULL, CHECK_CONNECT_NULL, ER_OBJ_NO_COMPONENTS, er_set(), ER_WARNING_SEVERITY, NO_ERROR, NULL, and sm_class::ordered_attributes.
Referenced by check_missing_non_null_attrs(), chksum_start(), db_gadget_create(), db_validate(), delete_object_tuple(), do_alter_change_auto_increment(), do_alter_one_clause_with_template(), do_create_trigger(), emit_class_meta(), emit_instance_attributes(), get_attr_name(), get_natural_join_attrs_from_pt_spec(), has_dependencies(), ldr_compare_storage_order(), or_create(), pt_check_alter(), pt_check_create_entity(), pt_get_attributes(), pt_to_delete_xasl(), sch_attr_priv(), sm_rename_class(), sm_truncate_class(), ux_get_generated_keys_client_insert(), ux_get_generated_keys_server_insert(), and vid_encode_object().
DB_OBJLIST* db_get_base_classes (void)
Definition at line 284 of file db_info.c.
References CHECK_CONNECT_NULL, DB_FETCH_QUERY_READ, and sm_fetch_all_base_classes().
int db_get_btree_statistics (DB_CONSTRAINT * cons, int * num_leaf_pages, int * num_total_pages, int * num_keys, int * height)
Definition at line 2365 of file db_info.c.
References ARG_FILE_LINE, assert_release, BTID_IS_NULL, btree_get_statistics(), db_constraint_type(), DB_IS_CONSTRAINT_INDEX_FAMILY, ER_OBJ_INVALID_ARGUMENTS, er_set(), ER_WARNING_SEVERITY, btree_stats::height, sm_class_constraint::index_btid, btree_stats::keys, btree_stats::leafs, NO_ERROR, NULL, btree_stats::pages, btree_stats::pkeys, and btree_stats::pkeys_size.
bool db_get_cacheinfo (DB_SESSION * session, int stmt_ndx, bool * use_plan_cache, bool * use_query_cache)
Definition at line 878 of file db_vdb.c.
References db_session::dimension, parser_node::flag, db_session::parser, db_session::statements, parser_node::use_plan_cache, and parser_node::use_query_cache.
Referenced by ux_execute(), ux_execute_all(), ux_execute_array(), ux_execute_batch(), and ux_prepare().
DB_OBJECT* db_get_class (DB_OBJECT * obj)
DB_ATTRIBUTE* db_get_class_attribute (DB_OBJECT * obj, const char * name)
Definition at line 878 of file db_info.c.
References ARG_FILE_LINE, au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_2ARGS_NULL, CHECK_CONNECT_NULL, classobj_find_attribute(), ER_OBJ_INVALID_ATTRIBUTE, er_set(), ER_WARNING_SEVERITY, NO_ERROR, and NULL.
Referenced by db_attdesc_domain(), do_alter_one_clause_with_template(), fetch_attribute(), pt_check_alter(), and pt_find_class_attribute().
DB_NAMELIST* db_get_class_attribute_names (DB_OBJECT * obj)
DB_ATTRIBUTE* db_get_class_attributes (DB_OBJECT * obj)
Definition at line 939 of file db_info.c.
References ARG_FILE_LINE, au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_1ARG_NULL, CHECK_CONNECT_NULL, sm_class::class_attributes, ER_OBJ_NO_COMPONENTS, er_set(), ER_WARNING_SEVERITY, NO_ERROR, and NULL.
Referenced by emit_class_attributes(), and pt_get_all_attributes_and_types().
DB_METHOD* db_get_class_method (DB_OBJECT * obj, const char * name)
Definition at line 1484 of file db_info.c.
References ARG_FILE_LINE, au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_2ARGS_NULL, CHECK_CONNECT_NULL, classobj_find_method(), ER_OBJ_INVALID_METHOD, er_set(), ER_WARNING_SEVERITY, NO_ERROR, and NULL.
Referenced by do_alter_one_clause_with_template(), ldr_act_set_constructor(), pt_check_alter(), pt_check_method(), pt_eval_method_call_type(), and pt_resolve_method_type().
DB_NAMELIST* db_get_class_method_names (DB_OBJECT * obj)
DB_METHOD* db_get_class_methods (DB_OBJECT * obj)
Definition at line 1542 of file db_info.c.
References ARG_FILE_LINE, au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_1ARG_NULL, CHECK_CONNECT_NULL, sm_class::class_methods, ER_OBJ_NO_COMPONENTS, er_set(), ER_WARNING_SEVERITY, NO_ERROR, and NULL.
Referenced by emit_methods(), and sch_method_info().
const char* db_get_class_name (DB_OBJECT * classobj)
Definition at line 608 of file db_info.c.
References CHECK_1ARG_NULL, CHECK_CONNECT_NULL, and sm_get_ch_name().
Referenced by au_get_new_auth(), check_object_domain(), chksum_start(), class_attr_info(), db_gadget_bind(), db_query_format_class_name(), db_validate(), db_validate_query_spec(), dbmeth_class_name(), object_printer::describe_class(), do_alter_clause_change_attribute(), do_check_rows_for_null(), emit_class_attributes(), emit_class_meta(), emit_class_owner(), emit_domain_def(), emit_foreign_key(), emit_index_def(), emit_instance_attributes(), emit_methods(), emit_partition_info(), emit_query_specs(), emit_query_specs_has_using_index(), emit_resolution_def(), emit_resolutions(), emit_reverse_unique_def(), emit_schema(), emit_superclasses(), emit_unique_def(), fetch_trigger(), find_instance(), fn_oid(), get_domain_str(), get_name_from_class_oid(), help_class_names(), ldr_class_name(), ldr_process_object_ref(), mq_check_authorization_path_entities(), mq_check_non_updatable_vclass_oid(), mq_evaluate_check_option(), mq_fetch_expression_for_real_class_update(), mq_fetch_one_real_class_get_cache(), mq_fetch_subqueries(), mq_fetch_subqueries_for_update_local(), mq_get_expression(), mq_set_non_updatable_oid(), mq_set_types(), mq_substitute_path(), mq_translate_tree(), mq_translate_value(), mq_virtual_queries(), object_to_string(), orp_oid_get_classname(), otable_insert(), otable_reserve(), pt_add_type_to_set(), pt_check_alter(), pt_check_drop(), pt_check_mutable_attributes(), pt_compile_trigger_stmt(), pt_copy_data_type_entity(), pt_eval_path_expr(), pt_find_class_of_index(), pt_get_attributes(), pt_get_object_data_type(), pt_help_show_create_table(), pt_make_subclass_list(), pt_resolve_object(), pt_to_method_sig_list(), pt_validate_query_spec(), rm_api_get_info(), sch_class_priv(), sch_exported_keys_or_cross_reference(), sch_imported_keys(), sch_superclass(), show_statistics(), sm_get_descriptor_component(), sm_truncate_using_delete(), smt_add_super(), tp_check_value_size(), tr_create_trigger(), tr_dump_trigger(), ux_oid_get(), and vid_getall_mops().
int db_get_class_num_objs_and_pages (DB_OBJECT * classmop, int approximation, int * nobjs, int * npages)
Definition at line 2311 of file db_info.c.
References ER_FAILED, error(), heap_get_class_num_objects_pages(), HFID_IS_NULL, NO_ERROR, NULL, and sm_get_ch_heap().
Referenced by ux_get_class_num_objs().
int db_get_class_privilege (DB_OBJECT * op, unsigned int * auth)
Definition at line 2346 of file db_info.c.
References au_get_class_privilege(), ER_FAILED, and NULL.
Referenced by sch_attr_priv(), and sch_class_priv().
DB_RESOLUTION* db_get_class_resolutions (DB_OBJECT * obj)
Definition at line 1767 of file db_info.c.
References ARG_FILE_LINE, au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_1ARG_NULL, CHECK_CONNECT_NULL, ER_OBJ_NO_COMPONENTS, er_set(), ER_WARNING_SEVERITY, ID_CLASS, sm_resolution::name_space, sm_resolution::next, NO_ERROR, NULL, and sm_class::resolutions.
int db_get_client_type (void)
Definition at line 489 of file db_admin.c.
References db_Client_type.
Referenced by csql_do_session_cmd(), la_init(), la_shutdown(), log_does_allow_replication(), obt_apply_assignments(), and obt_update_internal().
DB_CONSTRAINT* db_get_constraints (DB_OBJECT * obj)
Definition at line 1909 of file db_info.c.
References ARG_FILE_LINE, au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_1ARG_NULL, CHECK_CONNECT_NULL, sm_class::constraints, ER_OBJ_NO_COMPONENTS, er_set(), ER_WARNING_SEVERITY, NO_ERROR, and NULL.
Referenced by chksum_start(), emit_foreign_key(), emit_index_def(), emit_reverse_unique_def(), emit_unique_def(), has_unique_constraint(), sch_constraint(), sch_exported_keys_or_cross_reference(), and sch_imported_keys().
const char* db_get_database_comments (void)
Definition at line 471 of file db_admin.c.
References CHECK_CONNECT_NULL, disk_get_remarks(), free_and_init, NULL, and ws_copy_string().
char* db_get_database_name (void)
Definition at line 432 of file db_admin.c.
References CHECK_CONNECT_NULL, db_Database_name, NULL, strlen, and ws_copy_string().
Referenced by csql_print_database(), pt_evaluate_db_value_expr(), pt_make_query_show_table(), and pt_to_regu_variable().
char* db_get_database_version (void)
Definition at line 455 of file db_admin.c.
References NULL, rel_build_number(), and ws_copy_string().
Referenced by pt_evaluate_db_value_expr(), and pt_to_regu_variable().
DB_SESSION_ERROR* db_get_errors (DB_SESSION * session)
Definition at line 926 of file db_vdb.c.
References NULL, db_session::parser, and pt_get_errors().
Referenced by csql_display_session_err(), csql_execute_statements(), db_open_buffer_and_compile_first_statement(), do_check_rows_for_null(), do_run_update_query_for_class(), ldr_exec_query_from_file(), sm_truncate_using_delete(), and stmt_make_error_info().
int db_get_expression (DB_OBJECT * object, const char * expression, DB_VALUE * value)
Definition at line 296 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and mq_get_expression().
const char* db_get_foreign_key_action (DB_CONSTRAINT * constraint, DB_FK_ACTION_TYPE type)
Definition at line 2143 of file db_info.c.
References classobj_describe_foreign_key_action(), DB_FK_DELETE, DB_FK_UPDATE, sm_foreign_key_info::delete_action, sm_class_constraint::fk_info, NULL, SM_CONSTRAINT_FOREIGN_KEY, sm_class_constraint::type, and sm_foreign_key_info::update_action.
DB_OBJECT* db_get_foreign_key_ref_class (DB_CONSTRAINT * constraint)
Definition at line 2124 of file db_info.c.
References sm_class_constraint::fk_info, NULL, sm_foreign_key_info::ref_class_oid, SM_CONSTRAINT_FOREIGN_KEY, sm_class_constraint::type, and ws_mop().
Referenced by sch_imported_keys().
int db_get_global_transaction_info (int gtrid, void * buffer, int size)
Definition at line 1295 of file db_admin.c.
References ARG_FILE_LINE, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, ER_OBJ_INVALID_ARGUMENTS, er_set(), ER_WARNING_SEVERITY, NULL, and tran_get_global_tran_info().
Referenced by fn_xa_end_tran(), and fn_xa_recover().
int db_get_ha_server_state (char * buffer, int maxlen)
Definition at line 2824 of file db_admin.c.
References CHECK_CONNECT_ERROR, css_ha_server_state_string(), and HA_SERVER_STATE_NA.
Referenced by csql_print_database().
char* db_get_host_connected (void)
Definition at line 2806 of file db_admin.c.
Referenced by csql_print_database(), and ux_database_connect().
DB_MARKER* db_get_input_markers (DB_SESSION * session, int stmt)
Definition at line 1179 of file db_vdb.c.
References ARG_FILE_LINE, db_session::dimension, ER_OBJ_INVALID_ARGUMENTS, er_set(), ER_WARNING_SEVERITY, NULL, db_session::parser, parser, pt_free_host_info(), pt_get_input_host_vars(), pt_has_error, pt_host_info(), and db_session::statements.
Referenced by stmt_bind_pmeta_handle(), and ux_get_parameter_info().
bool db_get_jdbccachehint (DB_SESSION * session, int stmt_ndx, int * life_time)
Definition at line 844 of file db_vdb.c.
References db_session::dimension, pt_select_info::hint, parser_node::info, pt_select_info::jdbc_life_time, pt_statement_info::name, NULL, pt_name_info::original, db_session::parser, PT_HINT_JDBC_CACHE, pt_query_info::q, pt_statement_info::query, pt_query_info::select, and db_session::statements.
Referenced by get_client_result_cache_lifetime().
int db_get_last_insert_id (DB_VALUE * value)
Definition at line 1058 of file db_admin.c.
References CHECK_CONNECT_ERROR, and csession_get_last_insert_id().
Referenced by ux_get_last_insert_id().
const char* db_get_loader_commands (DB_OBJECT * obj)
Definition at line 2239 of file db_info.c.
References ARG_FILE_LINE, au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_1ARG_NULL, CHECK_CONNECT_NULL, ER_OBJ_NO_COMPONENTS, er_set(), ER_WARNING_SEVERITY, sm_class::loader_commands, NO_ERROR, and NULL.
DB_METHOD* db_get_method (DB_OBJECT * obj, const char * name)
Definition at line 1454 of file db_info.c.
References ARG_FILE_LINE, au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_2ARGS_NULL, CHECK_CONNECT_NULL, classobj_find_method(), ER_OBJ_INVALID_METHOD, er_set(), ER_WARNING_SEVERITY, NO_ERROR, and NULL.
Referenced by do_alter_one_clause_with_template(), pt_check_alter(), pt_check_method(), pt_eval_method_call_type(), and pt_resolve_method_type().
int db_get_method_descriptor (DB_OBJECT * obj, const char * methname, int class_method, DB_METHDESC ** descriptor)
Definition at line 857 of file db_obj.c.
References CHECK_3ARGS_ERROR, CHECK_CONNECT_ERROR, and sm_get_method_descriptor().
DB_NAMELIST* db_get_method_file_names (DB_OBJECT * obj)
DB_METHFILE* db_get_method_files (DB_OBJECT * obj)
Definition at line 2173 of file db_info.c.
References ARG_FILE_LINE, au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_1ARG_NULL, CHECK_CONNECT_NULL, ER_OBJ_NO_COMPONENTS, er_set(), ER_WARNING_SEVERITY, sm_class::method_files, NO_ERROR, and NULL.
Referenced by emit_method_files(), and sch_methfile_info().
const char* db_get_method_function (DB_OBJECT * obj, const char * name)
DB_NAMELIST* db_get_method_names (DB_OBJECT * obj)
char* db_get_method_source_file (DB_OBJECT * obj, const char * name)
DB_METHOD* db_get_methods (DB_OBJECT * obj)
Definition at line 1513 of file db_info.c.
References ARG_FILE_LINE, au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_1ARG_NULL, CHECK_CONNECT_NULL, ER_OBJ_NO_COMPONENTS, er_set(), ER_WARNING_SEVERITY, sm_class::methods, NO_ERROR, and NULL.
Referenced by emit_methods(), and sch_method_info().
DB_SESSION_ERROR* db_get_next_error (DB_SESSION_ERROR * errors, int * linenumber, int * columnnumber)
Definition at line 953 of file db_vdb.c.
References ARG_FILE_LINE, ER_PT_ERROR, er_set(), ER_SYNTAX_ERROR_SEVERITY, NULL, and pt_get_next_error().
Referenced by csql_display_session_err(), db_open_buffer_and_compile_first_statement(), ldr_exec_query_from_file(), stmt_exec_batch_query_internal(), and stmt_make_error_info().
DB_SESSION_ERROR* db_get_next_warning (DB_SESSION_WARNING * errors, int * linenumber, int * columnnumber)
Definition at line 1013 of file db_vdb.c.
References ARG_FILE_LINE, ER_PT_ERROR, er_set(), ER_WARNING_SEVERITY, NULL, and pt_get_next_error().
DB_NAMELIST* db_get_object_id (DB_OBJECT * vclass)
DB_NAMELIST* db_get_ordered_attribute_names (DB_OBJECT * obj)
DB_ATTRIBUTE* db_get_ordered_attributes (DB_OBJECT * obj)
Definition at line 971 of file db_info.c.
References ARG_FILE_LINE, au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_1ARG_NULL, CHECK_CONNECT_NULL, ER_OBJ_NO_COMPONENTS, er_set(), ER_WARNING_SEVERITY, NO_ERROR, NULL, and sm_class::ordered_attributes.
DB_MARKER* db_get_output_markers (DB_SESSION * session, int stmt)
Definition at line 1209 of file db_vdb.c.
References ARG_FILE_LINE, db_session::dimension, ER_OBJ_INVALID_ARGUMENTS, er_set(), ER_WARNING_SEVERITY, NULL, db_session::parser, parser, pt_free_host_info(), pt_get_output_host_vars(), pt_has_error, pt_host_info(), and db_session::statements.
DB_OBJECT* db_get_owner (DB_OBJECT * classobj)
Definition at line 1892 of file db_admin.c.
References au_get_class_owner(), CHECK_1ARG_NULL, and CHECK_CONNECT_NULL.
Referenced by help_class_names(), load_has_authorization(), mq_virtual_queries(), and pt_check_user_owns_class().
DB_PARAMETER* db_get_parameters (DB_SESSION * session, int statement_id)
Definition at line 3744 of file db_vdb.c.
References ARG_FILE_LINE, db_session::dimension, ER_OBJ_INVALID_ARGUMENTS, er_set(), ER_WARNING_SEVERITY, NULL, db_session::parser, pt_get_parameters(), pt_has_error, and db_session::statements.
int db_get_query_format (const char * CSQL_query, DB_QUERY_TYPE ** type_list, DB_QUERY_ERROR * query_error)
Definition at line 1558 of file db_query.c.
References db_compile_and_execute_queries_internal(), DB_NO_OIDS, error(), and NO_ERROR.
int db_get_query_result_format (DB_QUERY_RESULT * result, DB_QUERY_TYPE ** type_list)
Definition at line 2055 of file db_query.c.
References ARG_FILE_LINE, assert, CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, db_cp_query_type(), er_errid(), ER_ERROR_SEVERITY, ER_QPROC_OPR_ON_CLOSED_QRES, er_set(), NO_ERROR, NULL, db_query_result::query_type, db_query_result::status, and T_CLOSED.
DB_QUERY_SPEC* db_get_query_specs (DB_OBJECT * obj)
Definition at line 608 of file db_virt.c.
References au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_CONNECT_NULL, NO_ERROR, NULL, and sm_class::query_spec.
Referenced by db_validate(), emit_query_specs(), emit_query_specs_has_using_index(), mq_translate_subqueries(), pt_check_cyclic_reference_in_view_spec(), and pt_vclass_compatible().
DB_QUERY_TYPE* db_get_query_type_list (DB_SESSION * session, int stmt)
Definition at line 1341 of file db_vdb.c.
References ARG_FILE_LINE, CUBRID_STMT_CALL, CUBRID_STMT_GET_ISO_LVL, CUBRID_STMT_GET_OPT_LVL, CUBRID_STMT_GET_TIMEOUT, CUBRID_STMT_GET_TRIGGER, CUBRID_STMT_INSERT, CUBRID_STMT_SELECT, db_alloc_query_format(), db_cp_query_type(), db_query_type::db_type, DB_TYPE_INTEGER, DB_TYPE_OBJECT, db_session::dimension, ER_IT_EMPTY_STATEMENT, ER_IT_INVALID_SESSION, ER_OBJ_INVALID_ARGUMENTS, er_set(), ER_WARNING_SEVERITY, EXCLUDE_HIDDEN_COLUMNS, parser_node::node_type, NULL, db_session::parser, PT_EXECUTE_PREPARE, pt_get_select_list(), pt_length_of_select_list(), pt_node_to_cmd_type(), pt_node_to_db_type(), db_session::stage, StatementPreparedStage, db_session::statements, and db_session::type_list.
Referenced by csql_execute_statements(), db_compile_and_execute_queries_internal(), prepare_column_list_info_set(), stmt_bind_resultset_meta_handle(), uci_prepare(), and ux_use_sp_out().
DB_QUERY_TYPE* db_get_query_type_ptr (DB_QUERY_RESULT * result)
Definition at line 1431 of file db_vdb.c.
References db_query_result::query_type.
Referenced by csql_execute_statements().
DB_RESOLUTION* db_get_resolutions (DB_OBJECT * obj)
Definition at line 1735 of file db_info.c.
References ARG_FILE_LINE, au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_1ARG_NULL, CHECK_CONNECT_NULL, ER_OBJ_NO_COMPONENTS, er_set(), ER_WARNING_SEVERITY, ID_CLASS, sm_resolution::name_space, sm_resolution::next, NO_ERROR, NULL, and sm_class::resolutions.
Referenced by emit_resolutions().
int db_get_row_count (int * row_count)
Definition at line 1046 of file db_admin.c.
References CHECK_CONNECT_ERROR, and csession_get_row_count().
Referenced by pt_evaluate_db_value_expr(), pt_fold_const_expr(), and ux_get_row_count().
int db_get_row_count_cache (void)
Definition at line 2914 of file db_admin.c.
References db_Row_count.
Referenced by csql_display_trace(), pt_evaluate_db_value_expr(), pt_fold_const_expr(), tran_server_commit(), and ux_get_row_count().
int db_get_schema_def_dbval (DB_VALUE * result, DB_VALUE * name_val)
Definition at line 2407 of file db_info.c.
References assert, db_get_string(), db_is_class(), DB_IS_NULL, db_make_string_copy(), DB_VALUE_DOMAIN_TYPE, object_printer::describe_class(), er_errid(), ER_OBJ_NOT_A_CLASS, ER_QSTR_INVALID_DATA_TYPE, error(), string_buffer::get_buffer(), NO_ERROR, NULL, PRIM_SET_NULL(), prm_get_bool_value(), PRM_ID_RETURN_NULL_ON_FUNCTION_ERRORS, QSTR_IS_ANY_CHAR, and sm_find_class().
Referenced by pt_evaluate_db_value_expr().
int db_get_serial_current_value (const char * serial_name, DB_VALUE * serial_value)
Definition at line 1820 of file db_obj.c.
References ARG_FILE_LINE, assert, CT_SERIAL_NAME, do_get_serial_cached_num(), do_get_serial_obj_id(), er_errid(), ER_ERROR_SEVERITY, ER_QPROC_INVALID_PARAMETER, ER_QPROC_SERIAL_NOT_FOUND, er_set(), NO_ERROR, NULL, serial_get_current_value(), and sm_find_class().
int db_get_serial_next_value (const char * serial_name, DB_VALUE * serial_value)
Definition at line 1866 of file db_obj.c.
References db_get_serial_next_value_ex().
int db_get_serial_next_value_ex (const char * serial_name, DB_VALUE * serial_value, int num_alloc)
Definition at line 1878 of file db_obj.c.
References ARG_FILE_LINE, assert, CT_CLASS_NAME, do_get_serial_cached_num(), do_get_serial_obj_id(), er_errid(), ER_ERROR_SEVERITY, ER_QPROC_INVALID_PARAMETER, ER_QPROC_SERIAL_NOT_FOUND, er_set(), GENERATE_SERIAL, NO_ERROR, NULL, serial_get_next_value(), and sm_find_class().
Referenced by db_get_serial_next_value().
SESSION_ID db_get_session_id (void)
Definition at line 2859 of file db_admin.c.
References db_Session_id.
Referenced by cas_access_log(), cas_main(), cas_make_session_for_driver(), cas_send_connect_reply_to_driver(), db_end_session(), db_find_or_create_session(), and ux_get_session_id().
int db_get_shared (DB_OBJECT * object, const char * attpath, DB_VALUE * value)
Definition at line 255 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and obj_get_shared().
DB_ATTRIBUTE* db_get_shared_attribute (DB_OBJECT * obj, const char * name)
Definition at line 849 of file db_info.c.
References ARG_FILE_LINE, au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_2ARGS_NULL, CHECK_CONNECT_NULL, classobj_find_attribute(), ER_OBJ_INVALID_ATTRIBUTE, er_set(), ER_WARNING_SEVERITY, sm_attribute::header, ID_SHARED_ATTRIBUTE, sm_component::name_space, NO_ERROR, and NULL.
Referenced by pt_eval_path_expr().
DB_NAMELIST* db_get_shared_attribute_names (DB_OBJECT * obj)
int db_get_start_line (DB_SESSION * session, int stmt)
Definition at line 1444 of file db_vdb.c.
References ARG_FILE_LINE, db_session::dimension, er_errid(), ER_OBJ_INVALID_ARGUMENTS, er_set(), ER_WARNING_SEVERITY, db_session::parser, parser, pt_statement_line_number(), and db_session::statements.
Referenced by ci_stmt_get_start_line_impl(), and csql_execute_statements().
int db_get_statement_type (DB_SESSION * session, int stmt)
Definition at line 1473 of file db_vdb.c.
References ARG_FILE_LINE, db_session::dimension, er_errid(), ER_OBJ_INVALID_ARGUMENTS, er_set(), ER_WARNING_SEVERITY, pt_statement_info::execute, parser_node::info, parser_node::node_type, NULL, db_session::parser, parser, PT_EXECUTE_PREPARE, pt_node_to_cmd_type(), db_session::statements, and pt_execute_info::stmt_type.
Referenced by csql_execute_statements(), get_client_result_cache_lifetime(), ldr_exec_query_from_file(), sch_query_execute(), stmt_exec_one_statement(), stmt_exec_prepared_batch_internal(), stmt_prepare_internal(), uci_execute_immediate(), uci_open_cs(), uci_prepare(), uci_static(), ux_execute(), ux_execute_all(), ux_execute_array(), ux_execute_batch(), ux_execute_call(), and ux_prepare().
DB_NAMELIST* db_get_subclass_names (DB_OBJECT * obj)
DB_OBJLIST* db_get_subclasses (DB_OBJECT * obj)
Definition at line 659 of file db_info.c.
References ARG_FILE_LINE, au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_1ARG_NULL, CHECK_CONNECT_NULL, ER_OBJ_NO_COMPONENTS, er_set(), ER_WARNING_SEVERITY, NO_ERROR, NULL, and sm_class::users.
Referenced by db_class_has_instance(), do_alter_one_clause_with_template(), pt_check_alter(), pt_make_subclass_list(), and sch_superclass().
DB_NAMELIST* db_get_superclass_names (DB_OBJECT * obj)
DB_OBJLIST* db_get_superclasses (DB_OBJECT * obj)
Definition at line 630 of file db_info.c.
References ARG_FILE_LINE, au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_1ARG_NULL, CHECK_CONNECT_NULL, ER_OBJ_NO_COMPONENTS, er_set(), ER_WARNING_SEVERITY, sm_class::inheritance, NO_ERROR, and NULL.
Referenced by do_alter_one_clause_with_template(), emit_superclasses(), has_dependencies(), pt_check_alter(), sch_superclass(), and sm_get_descriptor_component().
int db_get_system_parameters (char * data, int len)
Definition at line 2770 of file db_admin.c.
References er_clear(), error(), NO_ERROR, NULL, PRM_ERR_NOT_FOR_CLIENT, rc, sysprm_free_assign_values(), sysprm_obtain_parameters(), sysprm_obtain_server_parameters(), sysprm_print_assign_values(), and sysprm_set_error().
Referenced by csql_get_sys_param(), statdump(), ux_get_default_setting(), and ux_get_system_parameter().
void db_get_tran_settings (int * lock_wait, DB_TRAN_ISOLATION * tran_isolation)
Definition at line 1554 of file db_admin.c.
References CHECK_CONNECT_VOID, and tran_get_tran_settings().
Referenced by pt_check_isolation_lvl().
const char* db_get_type_name (DB_TYPE type_id)
Definition at line 722 of file db_info.c.
References NULL, and pr_type_name().
Referenced by csql_db_value_as_string(), emit_stored_procedure(), emit_stored_procedure_args(), get_domain_str(), ldr_act_elem(), ldr_date_time_conversion_error(), ldr_double_elem(), ldr_float_elem(), ldr_int_db_bigint(), ldr_int_db_int(), ldr_int_db_short(), ldr_int_elem(), ldr_monetary_elem(), ldr_real_db_double(), ldr_real_db_float(), ldr_str_db_char(), ldr_str_db_varchar(), parse_error(), and select_set_domain().
DB_OBJECT* db_get_user (void)
Definition at line 1974 of file db_admin.c.
References Au_user.
Referenced by load_has_authorization(), mq_virtual_queries(), parser_generate_do_stmt_xasl(), parser_generate_xasl(), parser_print_user(), pt_to_delete_xasl(), pt_to_insert_xasl(), pt_to_merge_insert_xasl(), pt_to_merge_update_xasl(), pt_to_merge_xasl(), and pt_to_update_xasl().
char* db_get_user_and_host_name (void)
Definition at line 1932 of file db_admin.c.
References ARG_FILE_LINE, CUB_MAXHOSTNAMELEN, db_get_user_name(), db_private_alloc, db_string_free(), ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), GETHOSTNAME, db_host_status::hostname, NULL, and strlen.
Referenced by do_evaluate_default_expr(), pt_evaluate_db_value_expr(), and pt_to_regu_variable().
char* db_get_user_name (void)
Definition at line 1911 of file db_admin.c.
References au_user_name(), and CHECK_CONNECT_NULL.
Referenced by au_login_method(), chksum_set_repl_info_and_demote_table_lock(), conn_restart_client(), db_get_user_and_host_name(), do_evaluate_default_expr(), and do_replicate_statement().
int db_get_variable (DB_VALUE * name, DB_VALUE * value)
Definition at line 1072 of file db_admin.c.
References CHECK_CONNECT_ERROR, and csession_get_variable().
Referenced by pt_evaluate_db_value_expr(), and values_list_to_values_array().
char* db_get_vclass_ldb_name (DB_OBJECT * op)
Definition at line 199 of file db_virt.c.
References NULL.
DB_SESSION_ERROR* db_get_warnings (DB_SESSION * session)
Definition at line 985 of file db_vdb.c.
References NULL, db_session::parser, and pt_get_warnings().
int db_grant (DB_OBJECT * user, DB_OBJECT * classobj, DB_AUTH auth, int grant_option)
DB_CLASS_MODIFICATION_STATUS db_has_modified_class (DB_SESSION * session, int stmt_id)
Definition at line 2874 of file db_vdb.c.
References assert, DB_CLASS_NOT_MODIFIED, NULL, db_session::parser, pt_has_modified_class(), and db_session::statements.
Referenced by set_host_variables().
DB_IDENTIFIER* db_identifier (DB_OBJECT * obj)
Definition at line 2629 of file db_admin.c.
References ws_identifier_with_check().
Referenced by db_value_to_value(), dbobj_to_casobj(), pt_evaluate_tree_internal(), pt_make_regu_constant(), pt_make_vid(), pt_serial_to_xasl_class_oid_list(), and setof_mop_to_setof_vobj().
void db_include_oid (DB_SESSION * session, int include_oid)
Definition at line 1508 of file db_vdb.c.
References db_session::include_oid.
Referenced by db_open_buffer_and_compile_first_statement(), uci_open_cs(), and ux_prepare().
int db_instance_equal (DB_OBJECT * obj1, DB_OBJECT * obj2)
Definition at line 281 of file db_virt.c.
References CHECK_2ARGS_ZERO, CHECK_CONNECT_ZERO, DB_FETCH_READ, db_is_updatable_object(), db_real_instance(), is_class(), locator_is_class(), and vid_compare_non_updatable_objects().
int db_is_any_class (DB_OBJECT * obj)
int db_is_class (DB_OBJECT * obj)
bool db_is_client_cache_reusable (DB_QUERY_RESULT * result)
Definition at line 3432 of file db_query.c.
References T_CACHE_HIT, and db_query_result::type.
Referenced by ux_execute(), and ux_execute_all().
int db_is_deleted (DB_OBJECT * obj)
Definition at line 531 of file db_info.c.
References CHECK_1ARG_ERROR, ER_HEAP_UNKNOWN_OBJECT, error(), db_object::lock, obj_lock(), WS_IS_DELETED, and X_LOCK.
Referenced by delete_list_by_oids(), do_replace_into(), and update_object_tuple().
int db_is_indexed (DB_OBJECT * classobj, const char * attname)
bool db_is_input_marker (DB_MARKER * marker)
Definition at line 1299 of file db_vdb.c.
References pt_is_input_hostvar.
int db_is_instance (DB_OBJECT * obj)
int db_is_instance_of (DB_OBJECT * obj, DB_OBJECT * classobj)
bool db_is_output_marker (DB_MARKER * marker)
Definition at line 1318 of file db_vdb.c.
References pt_is_output_hostvar.
int db_is_partition (DB_OBJECT * classobj, DB_OBJECT * superobj)
Definition at line 483 of file db_info.c.
References CHECK_1ARG_MINUSONE, CHECK_CONNECT_ZERO, and sm_is_partition().
Referenced by mq_fetch_select_for_real_class_update().
int db_is_real_instance (DB_OBJECT * obj)
Definition at line 213 of file db_virt.c.
References CHECK_1ARG_ZERO, CHECK_CONNECT_ZERO, DB_FETCH_READ, db_object::is_vid, locator_is_class(), and vid_is_base_instance().
Referenced by db_real_instance().
int db_is_subclass (DB_OBJECT * classobj, DB_OBJECT * supermop)
int db_is_superclass (DB_OBJECT * supermop, DB_OBJECT * classobj)
int db_is_system_class (DB_OBJECT * op)
int db_is_updatable_attribute (DB_OBJECT * obj, const char * attr_name)
Definition at line 395 of file db_virt.c.
References au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_1ARG_ZERO, CHECK_CONNECT_ZERO, sm_class::class_type, DB_FETCH_WRITE, db_get_attribute_type(), db_get_class(), db_real_instance(), DB_TYPE_NULL, ER_OBJ_INVALID_ARGUMENTS, ER_WS_NO_CLASS_FOR_INSTANCE, error(), ERROR_SET, locator_is_class(), mq_is_updatable_attribute(), NO_ERROR, NULL, SM_CLASS_CT, and SM_VCLASS_CT.
Referenced by obj_set_att().
int db_is_updatable_object (DB_OBJECT * obj)
Definition at line 342 of file db_virt.c.
References au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_1ARG_ZERO, CHECK_CONNECT_ZERO, sm_class::class_type, DB_FETCH_READ, ER_WS_NO_CLASS_FOR_INSTANCE, error(), ERROR_SET, db_object::is_vid, locator_is_class(), mq_is_updatable(), NO_ERROR, SM_CLASS_CT, SM_VCLASS_CT, and vid_is_updatable().
Referenced by db_instance_equal(), mr_cmpval_object(), and vid_encode_object().
int db_is_vclass (DB_OBJECT * op)
Definition at line 681 of file db_virt.c.
References au_fetch_class_force(), AU_FETCH_READ, CHECK_CONNECT_ZERO, DB_FETCH_READ, error(), locator_is_class(), NULL, sm_get_class_type(), and SM_VCLASS_CT.
Referenced by catcls_vclass_install(), chksum_start(), class_type(), db_gadget_create(), db_validate_query_spec(), do_execute_delete(), do_execute_merge(), do_execute_update(), do_insert_template(), do_merge(), do_prepare_merge(), emit_indexes(), emit_query_specs(), emit_query_specs_has_using_index(), emit_schema(), insert_object_attr(), insert_subquery_results(), mq_fix_derived(), mq_push_paths_select(), mq_set_types(), mq_set_virt_object(), mq_translatable_class(), mq_translate_paths(), mq_translate_value(), pt_check_alter(), pt_check_attribute_domain(), pt_check_create_entity(), pt_check_cyclic_reference_in_view_spec(), pt_check_drop(), pt_flush_class_and_null_xasl(), pt_get_class_type(), pt_get_object_data_type(), pt_resolve_vclass_args(), pt_semantic_check_local(), pt_validate_query_spec(), regu_make_constant_vid(), smt_add_super(), tp_value_cast_internal(), tr_create_trigger(), update_object_attribute(), update_object_tuple(), and ws_vmop().
void db_link_static_methods (DB_METHOD_LINK * methods)
Definition at line 2523 of file db_admin.c.
References db_method_link::function, db_method_link::method, NULL, and sm_add_static_method().
Referenced by au_link_static_methods().
int db_list_length (DB_LIST * list)
Definition at line 69 of file db_old.c.
References ws_list_length().
Referenced by db_fetch_list(), and sch_trigger().
int db_lock_read (DB_OBJECT * op)
Definition at line 2001 of file db_admin.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, and obj_lock().
Referenced by fn_oid().
int db_lock_write (DB_OBJECT * op)
Definition at line 2030 of file db_admin.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, and obj_lock().
Referenced by fn_oid().
int db_login (const char * name, const char * password)
Definition at line 804 of file db_admin.c.
References au_login().
Referenced by acldb(), addvoldb(), applyinfo(), applylogdb(), backupdb(), changemode(), checkdb(), checksumdb(), compactdb(), copydb(), copylogdb(), createdb(), deletedb(), diagdb(), gen_tz(), installdb(), killtran(), loaddb_internal(), lockdb(), main(), optimizedb(), paramdump(), plandump(), renamedb(), restoredb(), restoreslave(), spacedb(), statdump(), synccolldb(), tde(), tranlist(), tzc_compute_timezone_checksum(), uci_connect(), and vacuumdb().
DB_DOMAIN* db_marker_domain (DB_MARKER * marker)
Definition at line 1276 of file db_vdb.c.
References parser_node::expected_domain, NULL, and pt_node_to_db_domain().
Referenced by ux_get_parameter_info().
int db_marker_index (DB_MARKER * marker)
Definition at line 1257 of file db_vdb.c.
References pt_host_var_index().
DB_MARKER* db_marker_next (DB_MARKER * marker)
Definition at line 1238 of file db_vdb.c.
References NULL, and pt_node_next().
Referenced by ux_get_parameter_info().
const char* db_methfile_name (DB_METHFILE * methfile)
Definition at line 2219 of file db_info.c.
References sm_method_file::name, and NULL.
Referenced by emit_methfile_def(), and fetch_methfile().
DB_METHFILE* db_methfile_next (DB_METHFILE * methfile)
Definition at line 2201 of file db_info.c.
References sm_method_file::next, and NULL.
Referenced by emit_method_files(), fetch_methfile(), and sch_methfile_info().
int db_method_arg_count (DB_METHOD * method)
Definition at line 1710 of file db_info.c.
References cubregex::count(), NULL, sm_method_signature::num_args, and sm_method::signatures.
Referenced by emit_method_def(), fetch_method(), and pt_check_method().
DB_DOMAIN* db_method_arg_domain (DB_METHOD * method, int arg)
Definition at line 1671 of file db_info.c.
References sm_method_signature::args, sm_method_argument::domain, sm_method_argument::index, sm_method_argument::next, NULL, sm_method::signatures, sm_filter_domain(), and sm_method_signature::value.
Referenced by emit_method_def(), fetch_method(), and pt_resolve_method_type().
DB_OBJECT* db_method_class (DB_METHOD * method)
Definition at line 1626 of file db_info.c.
References sm_method::class_mop, and NULL.
Referenced by emit_methods().
const char* db_method_function (DB_METHOD * method)
Definition at line 1606 of file db_info.c.
References sm_method_signature::function_name, NULL, and sm_method::signatures.
Referenced by emit_method_def().
const char* db_method_name (DB_METHOD * method)
Definition at line 1587 of file db_info.c.
References sm_method::header, sm_component::name, and NULL.
Referenced by emit_method_def(), and fetch_method().
DB_METHOD* db_method_next (DB_METHOD * method)
Definition at line 1569 of file db_info.c.
References sm_method::header, sm_component::next, and NULL.
Referenced by emit_methods(), fetch_method(), and sch_method_info().
DB_DOMAIN* db_method_return_domain (DB_METHOD * method)
Definition at line 1646 of file db_info.c.
References sm_method_argument::domain, NULL, sm_method::signatures, sm_filter_domain(), and sm_method_signature::value.
Referenced by emit_method_def(), and pt_eval_method_call_type().
int db_namelist_add (DB_NAMELIST ** list, const char * name)
Definition at line 84 of file db_virt.c.
References CHECK_2ARGS_ZERO, CHECK_CONNECT_FALSE, error(), nlist_add(), and NULL.
int db_namelist_append (DB_NAMELIST ** list, const char * name)
Definition at line 108 of file db_virt.c.
References CHECK_2ARGS_ZERO, CHECK_CONNECT_FALSE, error(), nlist_append(), and NULL.
Referenced by do_set_object_id().
DB_NAMELIST* db_namelist_copy (DB_NAMELIST * list)
Definition at line 148 of file db_old.c.
References CHECK_CONNECT_NULL, and nlist_copy().
void db_namelist_free (DB_NAMELIST * list)
Definition at line 71 of file db_virt.c.
References nlist_free().
Referenced by do_set_object_id().
void db_namelist_print (DB_NAMELIST * list)
Definition at line 233 of file db_old.c.
References db_namelist::name, db_namelist::next, and NULL.
void db_namelist_remove (DB_NAMELIST ** list, const char * name)
Definition at line 213 of file db_old.c.
References db_namelist::next, nlist_free(), nlist_remove(), and NULL.
DB_NAMELIST* db_namelist_sort (DB_NAMELIST * names)
Definition at line 170 of file db_old.c.
References db_namelist::name, db_namelist::next, and NULL.
Referenced by db_get_attribute_names(), db_get_class_attribute_names(), db_get_class_method_names(), db_get_method_file_names(), db_get_method_names(), db_get_shared_attribute_names(), db_get_subclass_names(), and db_get_superclass_names().
bool db_need_ignore_repl_delay (void)
Definition at line 743 of file db_admin.c.
References db_host_status_list::connected_host_status, DB_HS_HA_DELAYED, NULL, and db_host_status::status.
Referenced by client_capabilities().
bool db_need_reconnect (void)
Definition at line 709 of file db_admin.c.
References db_does_connected_host_have_status(), DB_HS_HA_DELAYED, DB_HS_RECONNECT_INDICATOR, db_host_status_list::hostlist, i, db_host_status_list::last_host_idx, and db_host_status::status.
Referenced by need_reconnect_on_rctime(), and report_abnormal_host_status().
int db_num_volumes (void)
Definition at line 374 of file db_admin.c.
References boot_find_number_permanent_volumes(), and CHECK_CONNECT_ZERO.
int db_number_of_input_markers (DB_SESSION * session, int stmt)
Definition at line 1125 of file db_vdb.c.
References ARG_FILE_LINE, db_session::dimension, er_errid(), ER_OBJ_INVALID_ARGUMENTS, er_set(), ER_WARNING_SEVERITY, parser_context::host_var_count, db_session::parser, parser, and db_session::statements.
Referenced by uci_execute_immediate(), uci_open_cs(), and uci_prepare().
int db_number_of_output_markers (DB_SESSION * session, int stmt)
Definition at line 1152 of file db_vdb.c.
References ARG_FILE_LINE, db_session::dimension, er_errid(), ER_OBJ_INVALID_ARGUMENTS, er_set(), ER_WARNING_SEVERITY, NULL, db_session::parser, parser, parser_walk_tree(), pt_count_output_markers(), and db_session::statements.
DB_OBJECT* db_object (DB_IDENTIFIER * oid)
Definition at line 2641 of file db_admin.c.
References NULL, and ws_mop().
Referenced by casobj_to_dbobj(), do_reclaim_class_addresses(), get_name_from_class_oid(), net_arg_get_dbobject(), or_create(), show_statistics(), ux_str_to_obj(), and value_to_db_value().
int db_object_describe (DB_OBJECT * obj, int num_attrs, const char ** attrs, DB_QUERY_TYPE ** col_spec)
Definition at line 1200 of file query_result.c.
References ARG_FILE_LINE, CHECK_CONNECT_ERROR, db_alloc_query_format(), db_free_query_format(), ER_ERROR_SEVERITY, ER_OBJ_INVALID_ARGUMENTS, er_set(), err, i, db_query_type::next, NO_ERROR, NULL, pt_find_size_from_dbtype(), sm_att_info(), sm_att_type_id(), sm_domain_copy(), strlen, and WS_CLASS_MOP.
int db_object_fetch (DB_OBJECT * obj, int num_attrs, const char ** attrs, DB_QUERY_RESULT ** result)
Definition at line 1273 of file query_result.c.
References ARG_FILE_LINE, C_BEFORE, CHECK_CONNECT_ERROR, db_query_result::col_cnt, db_objfetch_result::crs_pos, db_alloc_query_format(), db_alloc_query_result(), db_free_query_result(), db_init_query_result(), db_query_type::db_type, ER_ERROR_SEVERITY, ER_OBJ_INVALID_ARGUMENTS, er_set(), err, db_query_type::name, NO_ERROR, NULL, db_query_result::o, obj_get(), db_query_result::oid_included, pr_make_ext_value(), pt_find_size_from_dbtype(), db_query_result::query_type, db_query_result::res, db_query_type::size, sm_att_type_id(), sm_get_class(), strlen, T_OBJFETCH, db_query_result::type, db_query_result::type_cnt, and db_objfetch_result::valptr_list.
void db_objlist_free (DB_OBJLIST * list)
Definition at line 2612 of file db_admin.c.
References ml_ext_free(), and NULL.
Referenced by au_start(), chksum_start(), extract_context::clear_schema_workspace(), emit_stored_procedure(), help_class_names(), help_trigger_names(), sch_class_priv(), sch_superclass(), and srv_handle_content_free().
DB_OBJECT* db_objlist_get (DB_OBJLIST * list, int psn)
Definition at line 96 of file db_old.c.
References i, db_objlist::next, and NULL.
DB_OBJLIST* db_objlist_next (DB_OBJLIST * link)
Definition at line 2271 of file db_info.c.
References db_objlist::next, and NULL.
DB_OBJECT* db_objlist_object (DB_OBJLIST * link)
Definition at line 2290 of file db_info.c.
References NULL, and db_objlist::op.
void db_objlist_print (DB_OBJLIST * list)
Definition at line 121 of file db_old.c.
References db_objlist::next, NULL, db_objlist::op, db_identifier::pageid, db_identifier::slotid, db_identifier::volid, and WS_OID.
DB_SESSION* db_open_buffer (const char * buffer)
Definition at line 232 of file db_vdb.c.
References CHECK_1ARG_NULL, CHECK_CONNECT_NULL, and db_open_buffer_local().
Referenced by au_compute_groups(), au_drop_user(), au_get_new_auth(), csql_display_trace(), csql_execute_statements(), do_check_rows_for_null(), do_run_update_query_for_class(), fn_get_query_info(), sch_query_execute(), sm_truncate_using_delete(), tzc_compute_timezone_checksum(), uci_execute_immediate(), uci_open_cs(), uci_prepare(), uci_static(), ux_execute(), ux_execute_all(), ux_execute_array(), ux_execute_batch(), and ux_prepare().
DB_SESSION* db_open_file (FILE * file)
Definition at line 251 of file db_vdb.c.
References CHECK_CONNECT_NULL, db_open_local(), initialize_session(), db_session::parser, parser_parse_file(), and db_session::statements.
Referenced by csql_execute_statements().
DB_SESSION* db_open_file_name (const char * name)
Definition at line 376 of file db_vdb.c.
References CHECK_CONNECT_NULL, db_open_local(), initialize_session(), NULL, db_session::parser, parser_parse_file(), and db_session::statements.
const char* db_parameter_name (DB_PARAMETER * param)
Definition at line 3791 of file db_vdb.c.
References NULL, and pt_string_part().
DB_PARAMETER* db_parameter_next (DB_PARAMETER * param)
Definition at line 3772 of file db_vdb.c.
References NULL, and pt_node_next().
int db_ping_server (int client_val, int * server_val)
Definition at line 983 of file db_admin.c.
References CHECK_CONNECT_ERROR, error(), net_client_ping_server(), and NO_ERROR.
Referenced by la_check_time_commit(), and ux_check_connection().
void db_preload_classes (const char * name1, ...)
Definition at line 2476 of file db_admin.c.
References CHECK_CONNECT_VOID, ml_add(), NULL, sm_find_class(), and sm_prelink_methods().
void db_print (DB_OBJECT * obj)
Definition at line 1251 of file db_obj.c.
References CHECK_CONNECT_VOID, help_print_obj(), NULL, and file_print_output::std_output().
int db_print_mop (DB_OBJECT * obj, char * buffer, int maxlen)
Definition at line 733 of file db_old.c.
References CHECK_2ARGS_ZERO, CHECK_CONNECT_ZERO, and help_describe_mop().
Referenced by object_to_string().
void db_print_stats (void)
Definition at line 1985 of file db_admin.c.
References ws_dump().
int db_push_values (DB_SESSION * session, int count, DB_VALUE * in_values)
Definition at line 1527 of file db_vdb.c.
References ER_PT_SEMANTIC, parser_context::flag, parser_context::host_var_count, NO_ERROR, db_session::parser, parser, pt_has_error, pt_report_to_ersys(), pt_reset_error(), PT_SEMANTIC, pt_set_host_variables(), and parser_context::set_host_var.
Referenced by au_compute_groups(), au_delete_auth_of_dropping_table(), au_drop_user(), au_get_new_auth(), db_execute_with_values(), do_set_user_host_variables(), set_host_variables(), stmt_exec_internal(), stmt_exec_prepared_batch_internal(), uci_execute(), uci_execute_immediate(), uci_open_cs(), and uci_static().
int db_put (DB_OBJECT * obj, const char * name, DB_VALUE * value)
Definition at line 318 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, CHECK_PARTITION_NONE, db_get_class(), db_put_internal(), do_check_partitioned_class(), error(), and NO_ERROR.
Referenced by fn_collection(), ux_cursor_update(), and vt_api_set_db_value().
int db_query_column_count (DB_QUERY_RESULT * result)
Definition at line 3134 of file db_query.c.
References ARG_FILE_LINE, CHECK_1ARG_MINUSONE, db_query_result::col_cnt, DB_INVALID_RESTYPE, DB_OID_INCLUDED, ER_ERROR_SEVERITY, ER_QPROC_INVALID_RESTYPE, ER_QPROC_OPR_ON_CLOSED_QRES, er_set(), db_query_result::res, db_query_result::s, db_query_result::status, db_select_result::stmt_id, T_CLOSED, and db_query_result::type.
Referenced by chksum_get_next_lower_bound(), cur_tuple(), la_get_ha_apply_info(), uci_execute(), uci_fetch_cs(), uci_object_fetch(), and uci_static().
int db_query_end (DB_QUERY_RESULT * result)
Definition at line 3362 of file db_query.c.
References db_query_end_internal(), and tran_was_latest_query_ended().
Referenced by au_compute_groups(), au_delete_auth_of_dropping_table(), au_drop_user(), au_dump_auth(), au_dump_to_file(), au_dump_user(), au_export_users(), au_find_user(), au_get_new_auth(), build_class_grant_list(), chksum_calculate_checksum(), chksum_drop_and_create_checksum_table(), chksum_get_next_lower_bound(), chksum_get_prev_checksum_results(), chksum_insert_schema_definition(), chksum_report_diff(), chksum_report_schema_diff(), chksum_report_summary(), chksum_update_current_schema_definition(), chksum_update_master_checksum(), collect_class_grants(), csql_display_trace(), csql_execute_statements(), db_validate(), delete_all_ha_apply_info(), delete_all_slave_ha_apply_info(), do_check_rows_for_null(), do_redistribute_partitions_data(), export_serial(), fn_get_query_info(), free_cursor(), get_codeset_from_db_root(), insert_ha_apply_info(), la_get_ha_apply_info(), la_update_query_execute(), la_update_query_execute_with_values(), ldr_exec_query_from_file(), rs_destroyf(), sch_query_execute(), stmt_exec_batch_query_internal(), stmt_exec_prepared_batch_internal(), synccoll_check(), tzc_compute_timezone_checksum(), uci_end(), uci_execute_immediate(), ux_execute_all(), ux_execute_array(), ux_execute_batch(), ux_free_result(), ux_next_result(), and vid_getall_mops().
int db_query_execute (const char * CSQL_query, DB_QUERY_RESULT ** result, DB_QUERY_ERROR * query_error)
Definition at line 1808 of file db_query.c.
References db_compile_and_execute_queries_internal(), DB_NO_OIDS, error(), and NO_ERROR.
int db_query_first_tuple (DB_QUERY_RESULT * result)
Definition at line 2309 of file db_query.c.
References ARG_FILE_LINE, db_query_result::c, C_ON, CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, db_call_result::crs_pos, db_objfetch_result::crs_pos, db_get_result::crs_pos, cursor_first_tuple(), db_select_result::cursor_id, DB_CURSOR_END, DB_CURSOR_SUCCESS, ER_ERROR_SEVERITY, ER_QPROC_INVALID_RESTYPE, ER_QPROC_OPR_ON_CLOSED_QRES, er_set(), db_query_result::g, db_get_result::n_tuple, db_query_result::o, db_query_result::res, db_query_result::s, db_query_result::status, T_CALL, T_CLOSED, T_GET, T_OBJFETCH, T_SELECT, db_get_result::tpl_idx, and db_query_result::type.
Referenced by au_drop_user(), au_dump_to_file(), au_export_users(), au_find_user(), au_get_new_auth(), chksum_get_prev_checksum_results(), chksum_report_diff(), chksum_report_schema_diff(), chksum_report_summary(), chksum_update_master_checksum(), csql_display_trace(), csql_results(), db_query_seek_tuple(), do_check_rows_for_null(), export_serial(), fetch_result(), la_get_ha_apply_info(), uci_execute(), uci_object_fetch(), uci_static(), and write_results_to_stream().
char* db_query_format_attr_name (DB_QUERY_TYPE * query_type)
Definition at line 1622 of file db_query.c.
References db_query_type::attr_name, and CHECK_1ARG_NULL.
Referenced by prepare_column_list_info_set().
const char* db_query_format_class_name (DB_QUERY_TYPE * query_type)
Definition at line 1740 of file db_query.c.
References CHECK_1ARG_NULL, tp_domain::class_mop, db_get_class_name(), db_query_format_src_domain(), and NULL.
Referenced by prepare_column_list_info_set(), and ux_make_out_rs().
DB_COL_TYPE db_query_format_col_type (DB_QUERY_TYPE * query_type)
Definition at line 1590 of file db_query.c.
References CHECK_1ARG_RETURN_EXPR, db_query_type::col_type, and DB_COL_OTHER.
Referenced by prepare_column_list_info_set().
DB_DOMAIN* db_query_format_domain (DB_QUERY_TYPE * query_type)
Definition at line 1661 of file db_query.c.
References CHECK_1ARG_NULL, and db_query_type::domain.
Referenced by copy_column_spec_to_sqlda(), prepare_column_list_info_set(), and ux_make_out_rs().
void db_query_format_free (DB_QUERY_TYPE * query_type)
Definition at line 1723 of file db_query.c.
References db_free_query_format(), and NULL.
Referenced by alloc_dynamic(), free_attr_spec(), free_dynamic(), hm_qresult_end(), prepare_column_list_info_set(), uci_object_describe(), and uci_prepare().
int db_query_format_is_non_null (DB_QUERY_TYPE * query_type)
Definition at line 1766 of file db_query.c.
References db_query_type::attr_name, CHECK_1ARG_RETURN_EXPR, tp_domain::class_mop, db_attribute_is_non_null(), db_get_attribute(), db_query_format_src_domain(), ER_OBJ_INVALID_ARGUMENT, and NULL.
Referenced by prepare_column_list_info_set(), and ux_make_out_rs().
char* db_query_format_name (DB_QUERY_TYPE * query_type)
Definition at line 1609 of file db_query.c.
References CHECK_1ARG_NULL, and db_query_type::name.
Referenced by copy_column_spec_to_sqlda(), create_select_to_insert_into(), csql_results(), do_add_attribute_from_select_column(), do_add_attributes(), prepare_column_list_info_set(), query_get_column_with_name(), and ux_make_out_rs().
DB_QUERY_TYPE* db_query_format_next (DB_QUERY_TYPE * query_type)
Definition at line 1577 of file db_query.c.
References CHECK_1ARG_NULL, and db_query_type::next.
Referenced by copy_column_spec_to_sqlda(), create_select_to_insert_into(), csql_results(), do_add_attributes(), do_create_entity(), prepare_column_list_info_set(), pt_check_partitions(), query_get_column_with_name(), and ux_make_out_rs().
char* db_query_format_original_name (DB_QUERY_TYPE * query_type)
Definition at line 1648 of file db_query.c.
References CHECK_1ARG_NULL, and db_query_type::original_name.
Referenced by prepare_column_list_info_set(), and ux_make_out_rs().
int db_query_format_size (DB_QUERY_TYPE * query_type)
Definition at line 1704 of file db_query.c.
References CHECK_1ARG_MINUSONE, and db_query_type::size.
Referenced by copy_column_spec_to_sqlda().
char* db_query_format_spec_name (DB_QUERY_TYPE * query_type)
Definition at line 1635 of file db_query.c.
References CHECK_1ARG_NULL, and db_query_type::spec_name.
DB_TYPE db_query_format_type (DB_QUERY_TYPE * query_type)
Definition at line 1690 of file db_query.c.
References CHECK_1ARG_RETURN_EXPR, db_query_type::db_type, and DB_TYPE_NULL.
Referenced by csql_results().
int db_query_get_cache_time (DB_QUERY_RESULT * result, CACHE_TIME * cache_time)
Definition at line 3451 of file db_query.c.
References db_select_result::cache_time, CACHE_TIME_RESET, NO_ERROR, NULL, db_query_result::res, db_query_result::s, db_query_result::status, T_CLOSED, T_SELECT, and db_query_result::type.
Referenced by execute_info_set().
int db_query_get_tuple_oid (DB_QUERY_RESULT * result, DB_VALUE * db_value)
Definition at line 3195 of file db_query.c.
References ARG_FILE_LINE, db_query_result::c, CHECK_1ARG_MINUSONE, CHECK_1ARG_RETURN_EXPR, CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, cursor_get_current_oid(), db_select_result::cursor_id, DB_INVALID_INDEX, DB_INVALID_RESTYPE, DB_OID_INCLUDED, db_query_type::db_type, DB_TYPE_NULL, db_value_print(), ER_ERROR_SEVERITY, ER_QPROC_INVALID_CRSOPR, ER_QPROC_INVALID_RESTYPE, ER_QPROC_INVALID_TPLVAL_INDEX, ER_QPROC_OPR_ON_CLOSED_QRES, er_set(), ER_WARNING_SEVERITY, cursor_id::list_id, NULL, db_select_result::query_id, db_query_result::query_type, db_query_result::res, db_query_result::s, db_query_type::size, db_query_result::status, T_CALL, T_CLOSED, T_SELECT, db_query_result::type, db_query_result::type_cnt, and db_call_result::val_ptr.
Referenced by fetch_result(), uci_delete_cs(), uci_psh_curr_csr_oid(), and ux_cursor_update().
int db_query_get_tuple_value (DB_QUERY_RESULT * result, int tuple_index, DB_VALUE * value)
Definition at line 2873 of file db_query.c.
References ARG_FILE_LINE, db_query_result::c, CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, db_query_result::col_cnt, cursor_get_tuple_value(), db_select_result::cursor_id, DB_INVALID_INDEX, DB_OID_INCLUDED, ER_ERROR_SEVERITY, ER_QPROC_INVALID_RESTYPE, ER_QPROC_INVALID_TPLVAL_INDEX, ER_QPROC_OPR_ON_CLOSED_QRES, er_set(), db_query_result::g, NO_ERROR, db_query_result::o, pr_clone_value(), db_query_result::res, db_query_result::s, db_query_result::status, T_CALL, T_CLOSED, T_GET, T_OBJFETCH, T_SELECT, db_get_result::tpl_idx, db_get_result::tpl_list, db_query_result::type, db_call_result::val_ptr, and db_objfetch_result::valptr_list.
Referenced by au_compute_groups(), au_drop_user(), au_dump_auth(), au_dump_to_file(), au_dump_user(), au_export_users(), au_find_user(), au_get_new_auth(), build_class_grant_list(), chksum_get_prev_checksum_results(), chksum_report_diff(), chksum_report_schema_diff(), chksum_report_summary(), chksum_update_master_checksum(), collect_class_grants(), csql_display_trace(), cur_tuple(), db_query_get_tuple_value_by_name(), db_query_get_tuple_valuelist(), do_check_rows_for_null(), execute_info_set(), export_serial(), fetch_attribute(), get_codeset_from_db_root(), get_current_result(), rs_get_db_value(), synccoll_check(), tzc_compute_timezone_checksum(), uci_get_db_value(), uci_get_next_column(), ux_execute_array(), ux_execute_batch(), ux_execute_call(), and ux_get_generated_keys_server_insert().
int db_query_get_tuple_value_by_name (DB_QUERY_RESULT * result, char * column_name, DB_VALUE * value)
Definition at line 2959 of file db_query.c.
References ansisql_strcasecmp(), ARG_FILE_LINE, CHECK_3ARGS_ERROR, CHECK_CONNECT_ERROR, db_query_get_tuple_value(), ER_ERROR_SEVERITY, ER_QPROC_INVALID_COLNAME, ER_QPROC_INVALID_RESTYPE, ER_QPROC_OPR_ON_CLOSED_QRES, er_set(), db_query_type::next, NULL, db_query_result::query_type, db_query_result::status, T_CALL, T_CLOSED, T_GET, T_OBJFETCH, T_SELECT, and db_query_result::type.
Referenced by vid_getall_mops().
int db_query_get_tuple_valuelist (DB_QUERY_RESULT * result, int size, DB_VALUE * value_list)
Definition at line 3025 of file db_query.c.
References ARG_FILE_LINE, assert, CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, db_query_result::col_cnt, cursor_get_tuple_value_list(), db_select_result::cursor_id, DB_INVALID_INDEX, DB_OID_INCLUDED, db_query_get_tuple_value(), er_errid(), ER_ERROR_SEVERITY, ER_QPROC_INVALID_RESTYPE, ER_QPROC_INVALID_TPLVAL_INDEX, ER_QPROC_OPR_ON_CLOSED_QRES, er_set(), NO_ERROR, db_query_result::res, db_query_result::s, db_query_result::status, T_CALL, T_CLOSED, T_GET, T_OBJFETCH, T_SELECT, and db_query_result::type.
Referenced by chksum_get_next_lower_bound(), and la_get_ha_apply_info().
int db_query_last_tuple (DB_QUERY_RESULT * result)
Definition at line 2374 of file db_query.c.
References ARG_FILE_LINE, db_query_result::c, C_ON, CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, db_query_result::col_cnt, db_call_result::crs_pos, db_objfetch_result::crs_pos, db_get_result::crs_pos, db_select_result::cursor_id, cursor_last_tuple(), DB_CURSOR_END, DB_CURSOR_SUCCESS, ER_ERROR_SEVERITY, ER_QPROC_INVALID_RESTYPE, ER_QPROC_OPR_ON_CLOSED_QRES, er_set(), db_query_result::g, db_get_result::n_tuple, db_query_result::o, db_query_result::res, db_query_result::s, db_query_result::status, T_CALL, T_CLOSED, T_GET, T_OBJFETCH, T_SELECT, db_get_result::tpl_idx, and db_query_result::type.
Referenced by chksum_get_next_lower_bound(), and db_query_seek_tuple().
int db_query_next_tuple (DB_QUERY_RESULT * result)
Definition at line 2088 of file db_query.c.
References ARG_FILE_LINE, db_query_result::c, C_AFTER, C_BEFORE, C_ON, CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, db_query_result::col_cnt, db_call_result::crs_pos, db_objfetch_result::crs_pos, db_get_result::crs_pos, db_select_result::cursor_id, cursor_next_tuple(), DB_CURSOR_END, DB_CURSOR_SUCCESS, ER_ERROR_SEVERITY, ER_QPROC_INVALID_RESTYPE, ER_QPROC_OPR_ON_CLOSED_QRES, ER_QPROC_UNKNOWN_CRSPOS, er_set(), db_query_result::g, db_get_result::n_tuple, db_query_result::o, db_query_result::res, db_query_result::s, db_query_result::status, T_CALL, T_CLOSED, T_GET, T_OBJFETCH, T_SELECT, db_get_result::tpl_idx, and db_query_result::type.
Referenced by au_compute_groups(), au_drop_user(), au_dump_auth(), au_dump_to_file(), au_dump_user(), au_export_users(), au_get_new_auth(), build_class_grant_list(), chksum_get_prev_checksum_results(), chksum_report_diff(), chksum_report_schema_diff(), chksum_report_summary(), collect_class_grants(), db_query_seek_tuple(), export_serial(), fetch_attribute(), fetch_result(), get_codeset_from_db_root(), synccoll_check(), tzc_compute_timezone_checksum(), uci_fetch_cs(), ux_get_generated_keys_server_insert(), vid_getall_mops(), and write_results_to_stream().
int db_query_plan_dump_file (char * filename)
Definition at line 3541 of file db_query.c.
References NO_ERROR, NULL, query_Plan_dump_filename, and strdup().
Referenced by cas_log_query_info_init().
int db_query_prefetch_columns (DB_QUERY_RESULT * result, int * columns, int col_count)
Definition at line 3520 of file db_query.c.
References db_select_result::cursor_id, cursor_set_oid_columns(), ER_GENERIC_ERROR, error(), NO_ERROR, db_query_result::res, and db_query_result::s.
int db_query_prev_tuple (DB_QUERY_RESULT * result)
Definition at line 2196 of file db_query.c.
References ARG_FILE_LINE, db_query_result::c, C_AFTER, C_BEFORE, C_ON, CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, db_query_result::col_cnt, db_call_result::crs_pos, db_objfetch_result::crs_pos, db_get_result::crs_pos, db_select_result::cursor_id, cursor_prev_tuple(), DB_CURSOR_END, DB_CURSOR_SUCCESS, ER_ERROR_SEVERITY, ER_QPROC_INVALID_RESTYPE, ER_QPROC_OPR_ON_CLOSED_QRES, ER_QPROC_UNKNOWN_CRSPOS, er_set(), db_query_result::g, db_get_result::n_tuple, db_query_result::o, db_query_result::res, db_query_result::s, db_query_result::status, T_CALL, T_CLOSED, T_GET, T_OBJFETCH, T_SELECT, db_get_result::tpl_idx, and db_query_result::type.
Referenced by db_query_seek_tuple().
int db_query_produce_updatable_result (DB_SESSION * session, int stmtid)
Definition at line 3825 of file db_vdb.c.
References ARG_FILE_LINE, db_session::dimension, er_errid(), ER_IT_EMPTY_STATEMENT, ER_IT_INVALID_SESSION, ER_OBJ_INVALID_ARGUMENTS, er_set(), ER_WARNING_SEVERITY, parser_node::info, parser_node::node_type, pt_query_info::oids_included, db_session::parser, PT_SELECT, PT_UNION, pt_statement_info::query, db_session::stage, StatementPreparedStage, and db_session::statements.
Referenced by prepare_column_list_info_set().
int db_query_seek_tuple (DB_QUERY_RESULT * result, int offset, int seek_mode)
Definition at line 2455 of file db_query.c.
References ARG_FILE_LINE, assert, db_query_result::c, C_AFTER, C_BEFORE, C_ON, CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, db_query_result::col_cnt, db_call_result::crs_pos, db_objfetch_result::crs_pos, db_get_result::crs_pos, db_select_result::cursor_id, DB_CURSOR_END, DB_CURSOR_SEEK_CUR, DB_CURSOR_SEEK_END, DB_CURSOR_SEEK_SET, DB_CURSOR_SUCCESS, db_query_first_tuple(), db_query_free_tplpos(), db_query_get_tplpos(), db_query_last_tuple(), db_query_next_tuple(), db_query_prev_tuple(), db_query_set_tplpos(), er_errid(), ER_ERROR_SEVERITY, ER_GENERIC_ERROR, ER_QPROC_INVALID_RESTYPE, ER_QPROC_OPR_ON_CLOSED_QRES, er_set(), db_query_result::g, cursor_id::list_id, db_get_result::n_tuple, NO_ERROR, NULL, db_query_result::o, db_query_result::res, db_query_result::s, db_query_result::status, T_CALL, T_CLOSED, T_GET, T_OBJFETCH, T_SELECT, db_get_result::tpl_idx, qfile_list_id::tuple_cnt, cursor_id::tuple_no, and db_query_result::type.
Referenced by fetch_attribute(), fetch_result(), res_fetch_internal(), ux_cursor_update(), ux_execute(), and ux_execute_all().
int db_query_set_copy_tplvalue (DB_QUERY_RESULT * result, int copy)
Definition at line 3386 of file db_query.c.
References ARG_FILE_LINE, CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, db_select_result::cursor_id, cursor_set_copy_tuple_value(), ER_ERROR_SEVERITY, ER_QPROC_INVALID_RESTYPE, ER_QPROC_OPR_ON_CLOSED_QRES, er_set(), NO_ERROR, db_query_result::res, db_query_result::s, db_query_result::status, T_CALL, T_CLOSED, T_GET, T_OBJFETCH, T_SELECT, and db_query_result::type.
Referenced by csql_display_trace(), do_check_rows_for_null(), get_current_result(), sch_query_execute(), ux_execute(), ux_execute_all(), ux_execute_array(), ux_execute_batch(), and ux_execute_call().
DB_QUERY_SPEC* db_query_spec_next (DB_QUERY_SPEC * query_spec)
Definition at line 632 of file db_virt.c.
References sm_query_spec::next, and NULL.
Referenced by db_validate(), emit_query_specs(), emit_query_specs_has_using_index(), mq_translate_subqueries(), pt_check_cyclic_reference_in_view_spec(), and pt_vclass_compatible().
const char* db_query_spec_string (DB_QUERY_SPEC * query_spec)
Definition at line 651 of file db_virt.c.
References NULL, and sm_query_spec::specification.
Referenced by db_validate(), emit_query_specs(), emit_query_specs_has_using_index(), mq_translate_subqueries(), pt_check_cyclic_reference_in_view_spec(), and pt_vclass_compatible().
int db_query_tuple_count (DB_QUERY_RESULT * result)
Definition at line 3089 of file db_query.c.
References ARG_FILE_LINE, CHECK_1ARG_MINUSONE, db_select_result::cursor_id, ER_ERROR_SEVERITY, ER_QPROC_INVALID_RESTYPE, ER_QPROC_OPR_ON_CLOSED_QRES, er_set(), db_query_result::g, cursor_id::list_id, db_get_result::n_tuple, db_query_result::res, db_query_result::s, db_query_result::status, T_CALL, T_CLOSED, T_GET, T_OBJFETCH, T_SELECT, qfile_list_id::tuple_cnt, and db_query_result::type.
Referenced by create_srv_handle_with_query_result(), db_execute_and_keep_statement_local(), uci_execute(), uci_static(), ux_execute(), ux_execute_all(), and vid_getall_mops().
DB_OBJECT* db_real_instance (DB_OBJECT * obj)
Definition at line 247 of file db_virt.c.
References CHECK_1ARG_NULL, CHECK_CONNECT_NULL, db_is_real_instance(), db_object::is_vid, and vid_base_instance().
Referenced by db_fetch_composition(), db_instance_equal(), db_is_updatable_attribute(), do_replace_names_for_insert_values_pre(), insert_object_attr(), locator_fetch_set(), locator_lock_and_doesexist(), locator_lock_set(), mq_replace_virtual_oid_with_real_oid(), mq_translate_value(), mr_cmpval_object(), regu_make_constant_vid(), tp_value_cast_internal(), update_object_tuple(), vid_encode_object(), vid_object_to_vobj(), ws_identifier_with_check(), and ws_vmop().
int db_rename (DB_OBJECT * classobj, const char * name, int class_namespace, const char * newname)
int db_rename_attribute (DB_OBJECT * classobj, const char * name, int class_attribute, const char * newname)
int db_rename_class (DB_OBJECT * classobj, const char * new_name)
int db_rename_method (DB_OBJECT * classobj, const char * name, int class_method, const char * newname)
int db_rename_trigger (DB_OBJECT * obj, const char * newname)
Definition at line 1346 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, and tr_rename_trigger().
int db_reset_latest_query_status (void)
Definition at line 1132 of file db_admin.c.
References CHECK_CONNECT_ERROR, NO_ERROR, and tran_reset_latest_query_status().
Referenced by csql_execute_statements().
const char* db_resolution_alias (DB_RESOLUTION * resolution)
Definition at line 1862 of file db_info.c.
References sm_resolution::alias, and NULL.
Referenced by emit_resolution_def().
DB_OBJECT* db_resolution_class (DB_RESOLUTION * resolution)
Definition at line 1823 of file db_info.c.
References sm_resolution::class_mop, and NULL.
Referenced by emit_resolution_def().
int db_resolution_isclass (DB_RESOLUTION * resolution)
Definition at line 1882 of file db_info.c.
References ID_CLASS, sm_resolution::name_space, and NULL.
Referenced by emit_resolutions().
const char* db_resolution_name (DB_RESOLUTION * resolution)
Definition at line 1843 of file db_info.c.
References sm_resolution::name, and NULL.
Referenced by emit_resolution_def().
DB_RESOLUTION* db_resolution_next (DB_RESOLUTION * resolution)
Definition at line 1799 of file db_info.c.
References sm_resolution::name_space, sm_resolution::next, and NULL.
Referenced by emit_resolutions().
int db_restart (const char * program, int print_version, const char * volume)
Definition at line 868 of file db_admin.c.
References ARG_FILE_LINE, boot_restart_client(), clientids::client_type, boot_client_credential::connect_order, db_Client_type, db_Connect_order, db_Connect_status, DB_CONNECTION_STATUS_CONNECTED, DB_CONNECTION_STATUS_NOT_CONNECTED, db_Database_name, DB_MAX_IDENTIFIER_LENGTH, boot_client_credential::db_name, db_Preferred_hosts, db_Program_name, ER_OBJ_INVALID_ARGUMENTS, er_set(), ER_WARNING_SEVERITY, error(), install_static_methods(), jsp_jvm_is_loaded(), NO_ERROR, NULL, os_set_signal_handler(), boot_client_credential::preferred_hosts, prev_sigfpe_handler, clientids::process_id, clientids::program_name, sigfpe_handler(), and strncpy_bufsize.
Referenced by acldb(), addvoldb(), applyinfo(), applylogdb(), backupdb(), changemode(), checkdb(), checksumdb(), compactdb(), copydb(), copylogdb(), db_restart_ex(), diagdb(), gen_tz(), installdb(), killtran(), loaddb_internal(), lockdb(), main(), optimizedb(), paramdump(), plandump(), renamedb(), restoreslave(), spacedb(), statdump(), synccolldb(), tde(), tranlist(), tzc_compute_timezone_checksum(), uci_connect(), and vacuumdb().
int db_restart_ex (const char * program, const char * db_name, const char * db_user, const char * db_password, const char * preferred_hosts, int client_type)
Definition at line 934 of file db_admin.c.
References au_login(), db_restart(), db_set_client_type(), db_set_preferred_hosts(), NO_ERROR, and NULL.
Referenced by csql(), csql_do_session_cmd(), tranlist(), unloaddb(), and ux_database_connect().
int db_revoke (DB_OBJECT * user, DB_OBJECT * classobj, DB_AUTH auth)
void db_rewind_statement (DB_SESSION * session)
Definition at line 785 of file db_vdb.c.
References db_session::dimension, and db_session::stmt_ndx.
Referenced by ux_execute_all().
int db_savepoint_transaction (const char * savepoint_name)
Definition at line 1198 of file db_admin.c.
References CHECK_CONNECT_ERROR, and db_savepoint_transaction_internal().
Referenced by fn_savepoint(), and ux_execute_all().
int db_send (DB_OBJECT * obj, const char * name, DB_VALUE * returnval, ...)
int db_send_argarray (DB_OBJECT * obj, const char * name, DB_VALUE * returnval, DB_VALUE ** args)
int db_send_arglist (DB_OBJECT * obj, const char * name, DB_VALUE * returnval, DB_VALUE_LIST * args)
int db_set_argument_domain (DB_OBJECT * classobj, const char * name, int class_method, int arg_index, const char * domain)
int db_set_class_method_arg_domain (DB_OBJECT * classobj, const char * name, int arg_index, const char * domain)
Definition at line 1024 of file db_class.c.
References add_arg_domain().
int db_set_client_cache_time (DB_SESSION * session, int stmt_ndx, CACHE_TIME * cache_time)
Definition at line 813 of file db_vdb.c.
References ARG_FILE_LINE, parser_node::cache_time, parser_node::clt_cache_check, db_session::dimension, er_errid(), ER_OBJ_INVALID_ARGUMENTS, er_set(), ER_WARNING_SEVERITY, parser_node::flag, NO_ERROR, db_session::parser, and db_session::statements.
Referenced by ux_execute(), and ux_execute_all().
void db_set_client_type (int client_type)
Definition at line 495 of file db_admin.c.
References db_Client_type, DB_CLIENT_TYPE_DEFAULT, and DB_CLIENT_TYPE_MAX.
Referenced by acldb(), addvoldb(), applyinfo(), applylogdb(), backupdb(), changemode(), checkdb(), checksumdb(), compactdb(), copydb(), copylogdb(), createdb(), db_restart_ex(), deletedb(), diagdb(), gen_tz(), installdb(), killtran(), loaddb_internal(), lockdb(), main(), optimizedb(), paramdump(), plandump(), renamedb(), restoredb(), restoreslave(), spacedb(), statdump(), synccolldb(), tde(), tranlist(), tzc_compute_timezone_checksum(), and vacuumdb().
void db_set_connected_host_status (char * host_connected)
Definition at line 681 of file db_admin.c.
References db_host_status_list::connected_host_status, db_add_host_status(), db_find_host_status(), DB_HS_NORMAL, and NULL.
Referenced by boot_client_all_finalize().
int db_set_global_transaction_info (int gtrid, void * info, int size)
Definition at line 1262 of file db_admin.c.
References ARG_FILE_LINE, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, ER_OBJ_INVALID_ARGUMENTS, er_set(), ER_WARNING_SEVERITY, NULL, and tran_set_global_tran_info().
Referenced by fn_xa_prepare().
void db_set_host_status (char * hostname, int status)
Definition at line 649 of file db_admin.c.
References db_add_host_status(), db_Delayed_hosts_count, db_find_host_status(), DB_HS_HA_DELAYED, NULL, and db_host_status::status.
Referenced by boot_client_all_finalize(), boot_restart_client(), and check_server_capabilities().
void db_set_interrupt (int set)
Definition at line 1445 of file db_admin.c.
References CHECK_CONNECT_VOID, and locator_set_sig_interrupt().
Referenced by backupdb_sig_interrupt_handler(), csql_display_trace(), csql_execute_statements(), process_request(), query_cancel(), and signal_intr().
int db_set_isolation (DB_TRAN_ISOLATION isolation)
Definition at line 1535 of file db_admin.c.
References CHECK_CONNECT_MINUSONE, TM_TRAN_ASYNC_WS, and tran_reset_isolation().
Referenced by backupdb(), checkdb(), checksumdb(), compactdb(), compactdb_start(), do_reclaim_class_addresses(), lockdb(), ux_set_isolation_level(), and vacuumdb().
int db_set_loader_commands (DB_OBJECT * classobj, const char * commands)
int db_set_lock_timeout (int seconds)
Definition at line 1496 of file db_admin.c.
References CHECK_CONNECT_MINUSONE, CHECK_MODIFICATION_MINUSONE, and tran_reset_wait_times().
Referenced by applylogdb(), checksumdb(), and unloaddb().
int db_set_method_arg_domain (DB_OBJECT * classobj, const char * name, int arg_index, const char * domain)
Definition at line 1006 of file db_class.c.
References add_arg_domain().
int db_set_password (DB_OBJECT * user, const char * oldpass, const char * newpass)
Definition at line 1743 of file db_admin.c.
References au_set_password(), CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, and CHECK_MODIFICATION_ERROR.
void db_set_preferred_hosts (const char * hosts)
Definition at line 508 of file db_admin.c.
References db_Preferred_hosts, free_and_init, and strdup().
Referenced by db_restart_ex(), and ux_database_connect().
void db_set_session_id (const SESSION_ID session_id)
Definition at line 2870 of file db_admin.c.
References db_Session_id.
Referenced by cas_set_session_id(), db_find_or_create_session(), and ux_set_session_id().
int db_set_suppress_repl_on_transaction (int set)
Definition at line 1460 of file db_admin.c.
References CHECK_CONNECT_ERROR, and log_set_suppress_repl_on_transaction().
Referenced by do_execute_statement(), and do_statement().
int db_set_system_parameters (const char * data)
Definition at line 2682 of file db_admin.c.
References ARG_FILE_LINE, Au_dba_user, au_is_dba_group_member(), Au_user, cleanup(), ER_AU_DBA_ONLY, ER_ERROR_SEVERITY, er_set(), error(), NO_ERROR, NULL, PRM_ERR_NO_ERROR, PRM_ERR_NOT_FOR_CLIENT, PRM_ERR_NOT_FOR_CLIENT_NO_AUTH, rc, sysprm_change_parameter_values(), sysprm_change_server_parameters(), sysprm_free_assign_values(), sysprm_set_error(), and sysprm_validate_change_parameters().
Referenced by csql_set_sys_param(), db_reset_system_parameters_from_assignments(), db_set_system_parameters_for_ha_repl(), do_set_names(), do_set_sys_params(), do_set_timezone(), and ux_set_default_setting().
int db_set_user_comment (DB_OBJECT * user, const char * comment)
Definition at line 1765 of file db_admin.c.
References au_set_user_comment(), CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, and CHECK_MODIFICATION_ERROR.
int db_shutdown (void)
Definition at line 964 of file db_admin.c.
References boot_shutdown_client(), db_Connect_status, DB_CONNECTION_STATUS_NOT_CONNECTED, db_Database_name, db_Disable_modifications, db_free_execution_plan(), db_Program_name, error(), NO_ERROR, os_set_signal_handler(), and prev_sigfpe_handler.
Referenced by acldb(), addvoldb(), applyinfo(), applylogdb(), backupdb(), changemode(), checkdb(), checksumdb(), compactdb(), copylogdb(), createdb(), csql_do_session_cmd(), csql_exit_cleanup(), csql_exit_session(), diagdb(), gen_tz(), installdb(), killtran(), loaddb_internal(), lockdb(), main(), optimizedb(), paramdump(), plandump(), renamedb(), restoreslave(), spacedb(), start_csql(), statdump(), synccolldb(), tde(), tranlist(), tzc_compute_timezone_checksum(), uci_disconnect(), unloaddb(), ux_database_shutdown(), and vacuumdb().
int db_statement_count (DB_SESSION * session)
Definition at line 132 of file db_vdb.c.
References get_dimension_of(), NULL, and db_session::statements.
Referenced by csql_execute_statements(), do_check_rows_for_null(), do_run_update_query_for_class(), set_host_variables(), sm_truncate_using_delete(), and ux_execute_all().
void db_string_free (char * string)
Definition at line 2596 of file db_admin.c.
References db_ws_free(), and NULL.
Referenced by au_login_method(), db_get_user_and_host_name(), do_replicate_statement(), fetch_trigger(), pt_evaluate_db_value_expr(), pt_make_query_show_grants_curr_usr(), pt_make_query_show_table(), and pt_to_regu_variable().
void db_synchronize_cache (void)
Definition at line 1586 of file db_admin.c.
References CHECK_CONNECT_VOID, and locator_synch_isolation_incons().
Referenced by fetch_result().
int db_totalpgs (const char * vlabel)
Definition at line 2073 of file db_admin.c.
References CHECK_CONNECT_ZERO, disk_get_total_numpages(), and NULL_VOLID.
int db_trigger_action (DB_OBJECT * trobj, char ** action)
Definition at line 1742 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and tr_trigger_action().
Referenced by fetch_trigger(), and trigger_description::init().
int db_trigger_action_time (DB_OBJECT * trobj, DB_TRIGGER_TIME * tr_time)
Definition at line 1724 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and tr_trigger_action_time().
Referenced by fetch_trigger().
int db_trigger_action_type (DB_OBJECT * trobj, DB_TRIGGER_ACTION * type)
Definition at line 1705 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and tr_trigger_action_type().
int db_trigger_attribute (DB_OBJECT * trobj, char ** attr)
Definition at line 1643 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and tr_trigger_attribute().
Referenced by fetch_trigger().
int db_trigger_class (DB_OBJECT * trobj, DB_OBJECT ** class_obj)
Definition at line 1623 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and tr_trigger_class().
Referenced by fetch_trigger().
int db_trigger_comment (DB_OBJECT * trobj, char ** comment)
Definition at line 1763 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and tr_trigger_comment().
Referenced by fetch_trigger().
int db_trigger_condition (DB_OBJECT * trobj, char ** condition)
Definition at line 1663 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and tr_trigger_condition().
Referenced by fetch_trigger(), and trigger_description::init().
int db_trigger_condition_time (DB_OBJECT * trobj, DB_TRIGGER_TIME * tr_time)
Definition at line 1683 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and tr_trigger_condition_time().
Referenced by fetch_trigger().
int db_trigger_event (DB_OBJECT * trobj, DB_TRIGGER_EVENT * event)
Definition at line 1603 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and tr_trigger_event().
Referenced by fetch_trigger().
int db_trigger_name (DB_OBJECT * trobj, char ** name)
Definition at line 1548 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and tr_trigger_name().
Referenced by fetch_trigger().
int db_trigger_priority (DB_OBJECT * trobj, double * priority)
Definition at line 1585 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and tr_trigger_priority().
Referenced by fetch_trigger().
int db_trigger_status (DB_OBJECT * trobj, DB_TRIGGER_STATUS * status)
Definition at line 1567 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, and tr_trigger_status().
Referenced by fetch_trigger().
DB_TYPE db_type_from_string (const char * name)
Definition at line 742 of file db_info.c.
References db_Connect_status, DB_CONNECTION_STATUS_CONNECTED, DB_TYPE_SUB, DB_TYPE_UNKNOWN, DB_TYPE_VARIABLE, pr_type::id, NULL, pr_find_type(), pt_string_to_db_domain(), tp_domain_free(), and tp_domain::type.
DB_DOMAIN* db_type_to_db_domain (DB_TYPE type)
Definition at line 1710 of file db_macro.c.
void db_unlink_static_methods (DB_METHOD_LINK * methods)
Definition at line 2546 of file db_admin.c.
References db_method_link::method, NULL, and sm_delete_static_method().
void db_update_row_count_cache (const int row_count)
Definition at line 2924 of file db_admin.c.
References db_Row_count.
Referenced by csql_display_trace(), db_find_or_create_session(), do_commit(), pt_evaluate_db_value_expr(), pt_fold_const_expr(), and update_execution_values().
int db_validate (DB_OBJECT * vclass)
Definition at line 3573 of file db_vdb.c.
References ARG_FILE_LINE, BUF_SIZE, CHECK_CONNECT_ERROR, db_attribute_next(), db_compile_and_execute_local(), db_get_attributes(), db_get_class_name(), db_get_query_specs(), db_is_any_class(), db_query_end(), db_query_spec_next(), db_query_spec_string(), db_validate_query_spec(), er_errid(), ER_ERROR_SEVERITY, ER_OBJ_INVALID_ARGUMENTS, ER_OBJ_NOT_A_CLASS, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), ER_WARNING_SEVERITY, free_and_init, get_reasonable_predicate(), NO_ERROR, NULL, and strlen.
int db_validate_query_spec (DB_OBJECT * vclass, const char * query_spec)
Definition at line 3441 of file db_vdb.c.
References ARG_FILE_LINE, db_get_class_name(), db_is_vclass(), er_errid(), ER_ERROR_SEVERITY, ER_GENERIC_ERROR, ER_OBJ_INVALID_ARGUMENTS, er_set(), ER_SM_NOT_A_VIRTUAL_CLASS, NO_ERROR, NULL, parser_create_parser(), parser_free_parser(), parser_parse_string_use_sys_charset(), pt_has_error, pt_report_to_ersys(), PT_SYNTAX, pt_validate_query_spec(), and rc.
Referenced by db_validate().
char* db_vol_label (int volid, char * vol_fullname)
Definition at line 412 of file db_admin.c.
References CHECK_CONNECT_ZERO_TYPE, and disk_get_fullname().
void db_warnspace (const char * vlabel)
Definition at line 2452 of file db_admin.c.
References CHECK_CONNECT_VOID, fileio_find_volume_id_with_label(), and NULL.
void dbt_abort_class (DB_CTMPL * def)
Definition at line 249 of file db_temp.c.
References NULL, and smt_quit().
Referenced by adjust_partition_range(), define_trigger_classes(), do_alter_change_col_comment(), do_alter_change_default_cs_coll(), do_alter_change_tbl_comment(), do_alter_clause_change_attribute(), do_alter_one_clause_with_template(), do_create_entity(), do_create_partition(), do_promote_partition(), drop_foreign_key_ref_internal(), sm_drop_cascade_foreign_key(), sm_touch_class(), sm_truncate_class(), and update_foreign_key_ref().
void dbt_abort_object (DB_OTMPL * def)
Definition at line 616 of file db_obj.c.
References NULL, and obt_quit().
Referenced by au_change_serial_owner(), db_gadget_exec(), do_alter_serial(), do_change_auto_increment_serial(), do_create_serial_internal(), do_insert_template(), do_reset_auto_increment_serial(), do_update_auto_increment_serial_on_rename(), do_update_maxvalue_of_auto_increment_serial(), insert_subquery_results(), jsp_add_stored_procedure(), jsp_add_stored_procedure_argument(), la_apply_insert_log(), la_apply_update_log(), trigger_to_object(), update_class_attributes(), update_object_tuple(), and ux_oid_put().
int dbt_add_argument (DB_CTMPL * def, const char * name, int class_method, int arg_index, const char * domain)
Definition at line 800 of file db_temp.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, error(), NO_ERROR, NULL, and smt_assign_argument_domain().
int dbt_add_attribute (DB_CTMPL * def, const char * name, const char * domain, DB_VALUE * default_value)
Definition at line 272 of file db_temp.c.
References CHECK_3ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, error(), ID_ATTRIBUTE, NO_ERROR, NULL, and smt_add_attribute_w_dflt().
Referenced by define_trigger_classes().
int dbt_add_class_attribute (DB_CTMPL * def, const char * name, const char * domain, DB_VALUE * default_value)
Definition at line 317 of file db_temp.c.
References CHECK_3ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, error(), ID_CLASS_ATTRIBUTE, NO_ERROR, NULL, and smt_add_attribute_w_dflt().
int dbt_add_class_method (DB_CTMPL * def, const char * name, const char * implementation)
Definition at line 777 of file db_temp.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, error(), ID_CLASS_METHOD, NO_ERROR, and smt_add_method_any().
Referenced by do_add_methods().
int dbt_add_class_resolution (DB_CTMPL * def, DB_OBJECT * super, const char * name, const char * alias)
int dbt_add_constraint (DB_CTMPL * def, DB_CONSTRAINT_TYPE constraint_type, const char * constraint_name, const char ** attnames, int class_attributes, const char * comment)
Definition at line 423 of file db_temp.c.
References assert, CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, DB_CONSTRAINT_NOT_NULL, DB_IS_CONSTRAINT_UNIQUE_FAMILY, er_errid(), ER_SM_INVALID_CONSTRAINT, error(), ERROR_SET, free_and_init, NO_ERROR, NULL, SM_NORMAL_INDEX, sm_produce_constraint_name_tmpl(), and smt_add_constraint().
Referenced by classobj_copy_attribute_like(), dbt_constrain_non_null(), and dbt_constrain_unique().
int dbt_add_foreign_key (DB_CTMPL * def, const char * constraint_name, const char ** attnames, const char * ref_class, const char ** ref_attrs, int del_action, int upd_action, const char * comment)
Definition at line 524 of file db_temp.c.
References assert, classobj_free_class_constraints(), DB_CONSTRAINT_FOREIGN_KEY, sm_foreign_key_info::delete_action, er_errid(), error(), free_and_init, sm_foreign_key_info::is_dropped, NO_ERROR, NULL, sm_template::op, sm_foreign_key_info::ref_attrs, sm_foreign_key_info::ref_class, SM_NORMAL_INDEX, sm_produce_constraint_name_tmpl(), smt_add_constraint(), and sm_foreign_key_info::update_action.
Referenced by add_foreign_key(), classobj_copy_constraint_like(), and sm_truncate_class().
int dbt_add_method (DB_CTMPL * def, const char * name, const char * implementation)
Definition at line 756 of file db_temp.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, error(), ID_METHOD, NO_ERROR, and smt_add_method_any().
Referenced by do_add_methods().
int dbt_add_method_file (DB_CTMPL * def, const char * name)
Definition at line 1015 of file db_temp.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, error(), NO_ERROR, and smt_add_method_file().
Referenced by do_add_method_files().
int dbt_add_query_spec (DB_CTMPL * def, const char * query)
Definition at line 1201 of file db_temp.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, error(), NO_ERROR, and smt_add_query_spec().
Referenced by add_query_to_virtual_class().
int dbt_add_resolution (DB_CTMPL * def, DB_OBJECT * super, const char * name, const char * alias)
int dbt_add_set_argument_domain (DB_CTMPL * def, const char * name, int class_method, int arg_index, const char * domain)
Definition at line 823 of file db_temp.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, error(), NO_ERROR, NULL, and smt_add_set_argument_domain().
int dbt_add_set_attribute_domain (DB_CTMPL * def, const char * name, int class_attribute, const char * domain)
Definition at line 569 of file db_temp.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, error(), NO_ERROR, and smt_add_set_attribute_domain().
Referenced by do_alter_one_clause_with_template().
int dbt_add_shared_attribute (DB_CTMPL * def, const char * name, const char * domain, DB_VALUE * default_value)
Definition at line 294 of file db_temp.c.
References CHECK_3ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, error(), ID_SHARED_ATTRIBUTE, NO_ERROR, NULL, and smt_add_attribute_w_dflt().
int dbt_add_super (DB_CTMPL * def, DB_OBJECT * super)
int dbt_change_default (DB_CTMPL * def, const char * name, int class_attribute, DB_VALUE * value)
Definition at line 611 of file db_temp.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, error(), NO_ERROR, NULL, and smt_set_attribute_default().
Referenced by do_alter_one_clause_with_template().
int dbt_change_domain (DB_CTMPL * def, const char * name, int class_attribute, const char * domain)
Definition at line 591 of file db_temp.c.
References ARG_FILE_LINE, CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, ER_DB_NO_DOMAIN_CHANGE, ER_ERROR_SEVERITY, and er_set().
Referenced by do_alter_one_clause_with_template().
int dbt_change_method_implementation (DB_CTMPL * def, const char * name, int class_method, const char * newname)
Definition at line 845 of file db_temp.c.
References CHECK_3ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, error(), NO_ERROR, and smt_change_method_implementation().
Referenced by do_alter_one_clause_with_template().
int dbt_change_query_spec (DB_CTMPL * def, const char * new_query, const int query_no)
Definition at line 1261 of file db_temp.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, error(), NO_ERROR, and smt_change_query_spec().
Referenced by do_alter_one_clause_with_template().
int dbt_constrain_non_null (DB_CTMPL * def, const char * name, int class_attribute, int on_or_off)
Definition at line 344 of file db_temp.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, DB_CONSTRAINT_NOT_NULL, dbt_add_constraint(), dbt_drop_constraint(), do_check_fk_constraints(), error(), NO_ERROR, and NULL.
Referenced by do_add_attribute(), do_add_attribute_from_select_column(), and do_change_att_schema_only().
int dbt_constrain_unique (DB_CTMPL * def, const char * name, int on_or_off)
Definition at line 382 of file db_temp.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, DB_CONSTRAINT_UNIQUE, dbt_add_constraint(), dbt_drop_constraint(), error(), NO_ERROR, and NULL.
DB_CTMPL* dbt_create_class (const char * name)
Definition at line 76 of file db_temp.c.
References CHECK_1ARG_NULL, CHECK_CONNECT_NULL, CHECK_MODIFICATION_NULL, dbt_reserve_name(), NULL, and smt_def_class().
Referenced by define_trigger_classes(), do_create_entity(), and do_create_partition().
DB_OTMPL* dbt_create_object (DB_OBJECT * classobj)
DB_CTMPL* dbt_create_vclass (const char * name)
Definition at line 104 of file db_temp.c.
References CHECK_1ARG_NULL, CHECK_CONNECT_NULL, CHECK_MODIFICATION_NULL, dbt_reserve_name(), NULL, SM_VCLASS_CT, and smt_def_typed_class().
Referenced by do_create_entity().
int dbt_dput (DB_OTMPL * def, DB_ATTDESC * attribute, DB_VALUE * value)
Definition at line 953 of file db_obj.c.
References CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, CHECK_PARTITION_NONE, obj_template::classobj, dbt_dput_internal(), do_check_partitioned_class(), error(), sm_descriptor::name, and NO_ERROR.
int dbt_drop_attribute (DB_CTMPL * def, const char * name)
Definition at line 653 of file db_temp.c.
References au_check_serial_authorization(), AU_DISABLE, AU_ENABLE, sm_attribute::auto_increment, CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, COPY_OID, ER_SM_ATTRIBUTE_NOT_FOUND, error(), ID_ATTRIBUTE, ID_SHARED_ATTRIBUTE, NO_ERROR, NULL, obj_delete(), serial_decache(), smt_delete_any(), smt_find_attribute(), and ws_identifier().
Referenced by do_alter_one_clause_with_template().
int dbt_drop_class_attribute (DB_CTMPL * def, const char * name)
Definition at line 734 of file db_temp.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, error(), ID_CLASS_ATTRIBUTE, NO_ERROR, and smt_delete_any().
Referenced by do_alter_one_clause_with_template().
int dbt_drop_class_method (DB_CTMPL * def, const char * name)
Definition at line 885 of file db_temp.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, error(), ID_CLASS_METHOD, NO_ERROR, and smt_delete_any().
Referenced by do_alter_one_clause_with_template().
int dbt_drop_class_resolution (DB_CTMPL * def, DB_OBJECT * super, const char * name)
int dbt_drop_constraint (DB_CTMPL * def, DB_CONSTRAINT_TYPE constraint_type, const char * constraint_name, const char ** attnames, int class_attributes)
Definition at line 473 of file db_temp.c.
References assert, CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, DB_IS_CONSTRAINT_FAMILY, er_errid(), ER_SM_INVALID_CONSTRAINT, error(), ERROR_SET, free_and_init, NO_ERROR, NULL, SM_ATTFLAG_UNIQUE, SM_MAP_CONSTRAINT_TO_ATTFLAG, sm_produce_constraint_name_tmpl(), and smt_drop_constraint().
Referenced by dbt_constrain_non_null(), dbt_constrain_unique(), do_alter_one_clause_with_template(), sm_drop_cascade_foreign_key(), and sm_truncate_class().
int dbt_drop_method (DB_CTMPL * def, const char * name)
Definition at line 865 of file db_temp.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, error(), ID_METHOD, NO_ERROR, and smt_delete_any().
Referenced by do_alter_one_clause_with_template().
int dbt_drop_method_file (DB_CTMPL * def, const char * name)
Definition at line 1035 of file db_temp.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, error(), NO_ERROR, and smt_drop_method_file().
Referenced by do_alter_one_clause_with_template().
int dbt_drop_method_files (DB_CTMPL * def)
Definition at line 1054 of file db_temp.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, error(), NO_ERROR, and smt_reset_method_files().
int dbt_drop_query_spec (DB_CTMPL * def, const int query_no)
Definition at line 1221 of file db_temp.c.
References CHECK_1ARG_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, error(), NO_ERROR, and smt_drop_query_spec().
Referenced by do_alter_one_clause_with_template().
int dbt_drop_resolution (DB_CTMPL * def, DB_OBJECT * super, const char * name)
int dbt_drop_set_attribute_domain (DB_CTMPL * def, const char * name, int class_attribute, const char * domain)
Definition at line 633 of file db_temp.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, error(), NO_ERROR, and smt_delete_set_attribute_domain().
int dbt_drop_shared_attribute (DB_CTMPL * def, const char * name)
Definition at line 714 of file db_temp.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, error(), ID_SHARED_ATTRIBUTE, NO_ERROR, and smt_delete_any().
int dbt_drop_super (DB_CTMPL * def, DB_OBJECT * super)
int dbt_drop_super_connect (DB_CTMPL * def, DB_OBJECT * super)
DB_CTMPL* dbt_edit_class (DB_OBJECT * classobj)
DB_OTMPL* dbt_edit_object (DB_OBJECT * object)
DB_OBJECT* dbt_finish_class (DB_CTMPL * def)
Definition at line 226 of file db_temp.c.
References CHECK_1ARG_NULL, CHECK_CONNECT_NULL, CHECK_MODIFICATION_NULL, NO_ERROR, NULL, and sm_finish_class().
Referenced by adjust_partition_range(), define_trigger_classes(), do_alter_change_col_comment(), do_alter_change_default_cs_coll(), do_alter_change_tbl_comment(), do_alter_clause_change_attribute(), do_alter_one_clause_with_template(), do_create_entity(), do_create_partition(), do_promote_partition(), drop_foreign_key_ref_internal(), sm_drop_cascade_foreign_key(), sm_touch_class(), sm_truncate_class(), and update_foreign_key_ref().
DB_OBJECT* dbt_finish_object (DB_OTMPL * def)
Definition at line 560 of file db_obj.c.
References CHECK_1ARG_NULL, CHECK_CONNECT_NULL, CHECK_MODIFICATION_NULL, NO_ERROR, NULL, and obt_update().
Referenced by au_change_serial_owner(), db_gadget_exec(), do_alter_serial(), do_change_auto_increment_serial(), do_create_serial_internal(), do_insert_template(), do_reset_auto_increment_serial(), do_update_auto_increment_serial_on_rename(), do_update_maxvalue_of_auto_increment_serial(), insert_subquery_results(), jsp_add_stored_procedure(), jsp_add_stored_procedure_argument(), trigger_to_object(), update_class_attributes(), update_object_tuple(), and ux_oid_put().
DB_OBJECT* dbt_finish_object_and_decache_when_failure (DB_OTMPL * def)
Definition at line 583 of file db_obj.c.
References CHECK_1ARG_NULL, CHECK_CONNECT_NULL, CHECK_MODIFICATION_NULL, NO_ERROR, NULL, obj_template::object, obt_update(), and ws_decache().
int dbt_put (DB_OTMPL * def, const char * name, DB_VALUE * value)
Definition at line 635 of file db_obj.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, CHECK_PARTITION_NONE, obj_template::classobj, dbt_put_internal(), do_check_partitioned_class(), error(), and NO_ERROR.
Referenced by ux_oid_put().
int dbt_rename (DB_CTMPL * def, const char * name, int class_namespace, const char * newname)
Definition at line 967 of file db_temp.c.
References ATTR_RENAME_SAVEPOINT, sm_template::attributes, sm_attribute::auto_increment, CHECK_3ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, do_update_auto_increment_serial_on_rename(), error(), sm_template::name, NO_ERROR, NULL, SM_FIND_NAME_IN_COMPONENT_LIST, smt_rename_any(), tran_abort_upto_system_savepoint(), and tran_system_savepoint().
Referenced by do_alter_one_clause_with_template().
int dbt_rename_method_file (DB_CTMPL * def, const char * new_name, const char * old_name)
Definition at line 1075 of file db_temp.c.
References CHECK_3ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, error(), NO_ERROR, and smt_rename_method_file().
Referenced by do_alter_one_clause_with_template().
int dbt_set_label (DB_OTMPL * def, DB_VALUE * label)
Definition at line 713 of file db_obj.c.
References ARG_FILE_LINE, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, obj_template::classobj, DB_TYPE_OBJECT, DB_VALUE_DOMAIN_TYPE, ER_ERROR_SEVERITY, ER_REFERENCE_TO_NON_REFERABLE_NOT_ALLOWED, er_set(), NO_ERROR, NULL, obt_set_label(), and sm_is_reuse_oid_class().
Referenced by do_insert_template().
int dbt_set_loader_commands (DB_CTMPL * def, const char * commands)
Definition at line 1095 of file db_temp.c.
References CHECK_2ARGS_ERROR, CHECK_CONNECT_ERROR, CHECK_MODIFICATION_ERROR, error(), NO_ERROR, and smt_set_loader_commands().
int dbt_set_object_id (DB_CTMPL * def, DB_NAMELIST * id_list)
Definition at line 1281 of file db_temp.c.
References NO_ERROR.
Referenced by do_set_object_id().