CUBRID Engine: src/compat/dbtype_function.h File Reference
dbtype_function.h File Reference
#include <stdio.h>
#include "db_set_function.h"
#include "dbtype_def.h"
Macros
#define DB_CURRENCY_DEFAULT db_get_currency_default()
#define db_collection db_set
#define db_make_utime db_make_timestamp
#define DB_MAKE_NULL(value) db_make_null(value)
#define DB_VALUE_CLONE_AS_NULL(src_value, dest_value)
#define DB_MAKE_INTEGER(value, num) db_make_int(value, num)
#define DB_MAKE_INT DB_MAKE_INTEGER
#define DB_MAKE_BIGINT(value, num) db_make_bigint(value, num)
#define DB_MAKE_BIGINTEGER DB_MAKE_BIGINT
#define DB_MAKE_FLOAT(value, num) db_make_float(value, num)
#define DB_MAKE_DOUBLE(value, num) db_make_double(value, num)
#define DB_MAKE_OBJECT(value, obj) db_make_object(value, obj)
#define DB_MAKE_OBJ DB_MAKE_OBJECT
#define DB_MAKE_SET(value, set) db_make_set(value, set)
#define DB_MAKE_MULTISET(value, set) db_make_multiset(value, set)
#define DB_MAKE_MULTI_SET DB_MAKE_MULTISET
#define DB_MAKE_SEQUENCE(value, set) db_make_sequence(value, set)
#define DB_MAKE_LIST DB_MAKE_SEQUENCE
#define DB_MAKE_SEQ DB_MAKE_SEQUENCE
#define DB_MAKE_OID(value, oid)
#define DB_GET_OID(value) (db_get_oid(value))
#define DB_MAKE_COLLECTION(value, col) db_make_collection(value, col)
#define DB_MAKE_MIDXKEY(value, midxkey) db_make_midxkey(value, midxkey)
#define DB_MAKE_ELO(value, type, elo) db_make_elo(value, type, elo)
#define DB_MAKE_TIME(value, hour, minute, second) db_make_time(value, hour, minute, second)
#define DB_MAKE_ENCODED_TIME(value, time_value) db_value_put_encoded_time(value, time_value)
#define DB_MAKE_DATE(value, month, day, year) db_make_date(value, month, day, year)
#define DB_MAKE_ENCODED_DATE(value, date_value) db_value_put_encoded_date(value, date_value)
#define DB_MAKE_TIMESTAMP(value, timeval) db_make_timestamp(value, timeval)
#define DB_MAKE_UTIME DB_MAKE_TIMESTAMP
#define DB_MAKE_TIMESTAMPTZ(value, ts_tz) db_make_timestamptz(value, ts_tz)
#define DB_MAKE_TIMESTAMPLTZ(value, timeval) db_make_timestampltz(value, timeval)
#define DB_MAKE_MONETARY_AMOUNT(value, amount) db_make_monetary(value, DB_CURRENCY_DEFAULT, amount)
#define DB_MAKE_DATETIME(value, datetime_value) db_make_datetime(value, datetime_value)
#define DB_MAKE_DATETIMETZ(value, datetimetz_value) db_make_datetimetz(value, datetimetz_value)
#define DB_MAKE_DATETIMELTZ(value, datetime_value) db_make_datetimeltz(value, datetime_value)
#define DB_MAKE_MONETARY DB_MAKE_MONETARY_AMOUNT
#define DB_MAKE_MONETARY_TYPE_AMOUNT(value, type, amount) db_make_monetary(value, type, amount)
#define DB_MAKE_POINTER(value, ptr) db_make_pointer(value, ptr)
#define DB_MAKE_ERROR(value, errcode) db_make_error(value, errcode)
#define DB_MAKE_METHOD_ERROR(value, errcode, errmsg) db_make_method_error(value, errcode, errmsg)
#define DB_MAKE_SMALLINT(value, num) db_make_short(value, num)
#define DB_MAKE_SHORT DB_MAKE_SMALLINT
#define DB_MAKE_NUMERIC(value, num, precision, scale) db_make_numeric(value, num, precision, scale)
#define DB_MAKE_BIT(value, bit_length, bit_str, bit_str_bit_size) db_make_bit(value, bit_length, bit_str, bit_str_bit_size)
#define DB_MAKE_VARBIT(value, max_bit_length, bit_str, bit_str_bit_size) db_make_varbit(value, max_bit_length, bit_str, bit_str_bit_size)
#define DB_MAKE_CHAR(value, char_length, str, char_str_byte_size, codeset, collation) db_make_char(value, char_length, str, char_str_byte_size, codeset, collation)
#define DB_MAKE_VARCHAR(value, max_char_length, str, char_str_byte_size, codeset, collation) db_make_varchar(value, max_char_length, str, char_str_byte_size, codeset, collation)
#define DB_MAKE_STRING(value, str) db_make_string(value, str)
#define DB_MAKE_NCHAR(value, nchar_length, str, nchar_str_byte_size, codeset, collation) db_make_nchar(value, nchar_length, str, nchar_str_byte_size, codeset, collation)
#define DB_MAKE_VARNCHAR(value, max_nchar_length, str, nchar_str_byte_size, codeset, collation) db_make_varnchar(value, max_nchar_length, str, nchar_str_byte_size, codeset, collation)
#define DB_MAKE_ENUMERATION(value, index, str, size, codeset, collation) db_make_enumeration(value, index, str, size, codeset, collation)
#define DB_MAKE_RESULTSET(value, handle) db_make_resultset(value, handle)
#define db_get_collection db_get_set
#define db_get_utime db_get_timestamp
#define DB_IS_NULL(value) db_value_is_null(value)
#define DB_VALUE_DOMAIN_TYPE(value) db_value_domain_type(value)
#define DB_GET_INT(v) db_get_int(v)
#define DB_GET_SHORT(v) db_get_short(v)
#define DB_GET_BIGINT(v) db_get_bigint(v)
#define DB_GET_FLOAT(v) db_get_float(v)
#define DB_GET_STRING(v) db_get_string(v)
#define DB_GET_STRING_LENGTH(v) db_get_string_length(v)
#define DB_GET_DOUBLE(v) db_get_double(v)
#define DB_GET_OBJECT(v) db_get_object(v)
#define DB_GET_SET(v) db_get_set(v)
#define DB_GET_MIDXKEY(v) db_get_midxkey(v)
#define DB_GET_POINTER(v) db_get_pointer(v)
#define DB_GET_TIME(v) db_get_time(v)
#define DB_GET_TIMESTAMP(v) db_get_timestamp(v)
#define DB_GET_TIMESTAMPTZ(v) db_get_timestamptz(v)
#define DB_GET_DATETIME(v) db_get_datetime(v)
#define DB_GET_DATETIMETZ(v) db_get_datetimetz(v)
#define DB_GET_DATE(v) db_get_date(v)
#define DB_GET_MONETARY(v) db_get_monetary(v)
#define DB_GET_ERROR(v) db_get_error(v)
#define DB_GET_ELO(v) db_get_elo(v)
#define DB_GET_NUMERIC(v) db_get_numeric(v)
#define DB_GET_BIT(v, l) db_get_bit(v, l)
#define DB_GET_CHAR(v, l) db_get_char(v, l)
#define DB_GET_NCHAR(v, l) db_get_nchar(v, l)
#define DB_GET_STRING_SIZE(v) db_get_string_size(v)
#define DB_GET_ENUM_SHORT(v) db_get_enum_short(v)
#define DB_GET_ENUM_STRING(v) db_get_enum_string(v)
#define DB_GET_ENUM_STRING_SIZE(v) db_get_enum_string_size(v)
#define DB_GET_METHOD_ERROR_MSG() db_get_method_error_msg()
#define DB_GET_RESULTSET(v) db_get_resultset(v)
#define DB_GET_STRING_CODESET(v) ((INTL_CODESET) db_get_string_codeset(v))
#define DB_GET_STRING_COLLATION(v) db_get_string_collation(v)
#define DB_GET_ENUM_CODESET(v) db_get_enum_codeset(v)
#define DB_GET_ENUM_COLLATION(v) db_get_enum_collation(v)
#define DB_VALUE_TYPE(value) db_value_type(value)
#define DB_VALUE_PRECISION(value) db_value_precision(value)
#define DB_VALUE_SCALE(value) db_value_scale(value)
#define DB_GET_INTEGER(value) db_get_int(value)
#define DB_GET_BIGINTEGER DB_GET_BIGINT
#define DB_GET_OBJ DB_GET_OBJECT
#define DB_GET_MULTISET(value) db_get_set(value)
#define DB_GET_LIST(value) db_get_set(value)
#define DB_GET_SEQUENCE DB_GET_LIST
#define DB_GET_COLLECTION(value) db_get_set(value)
#define DB_GET_UTIME DB_GET_TIMESTAMP
#define DB_GET_SMALLINT(value) db_get_short(value)
#define DB_GET_COMPRESSED_SIZE(value) db_get_compressed_size(value)
#define DB_GET_JSON_DOCUMENT(value) db_get_json_document(value)
#define DB_GET_SEQ DB_GET_SEQUENCE
#define DB_SET_COMPRESSED_STRING(value, compressed_string, compressed_size, compressed_need_clear) db_set_compressed_string(value, compressed_string, compressed_size, compressed_need_clear)
#define DB_TRIED_COMPRESSION(value) (DB_GET_COMPRESSED_SIZE(value) != DB_NOT_YET_COMPRESSED)
Functions
int db_date_encode (DB_DATE *date, int month, int day, int year)
int db_time_encode (DB_TIME *timeval, int hour, int minute, int second)
void db_date_decode (const DB_DATE *date, int *monthp, int *dayp, int *yearp)
void db_time_decode (DB_TIME *timeval, int *hourp, int *minutep, int *secondp)
DB_VALUE * db_value_create (void)
DB_VALUE * db_value_copy (DB_VALUE *value)
int db_value_clone (DB_VALUE *src, DB_VALUE *dest)
int db_value_clear (DB_VALUE *value)
int db_value_free (DB_VALUE *value)
int db_value_clear_array (DB_VALUE_ARRAY *value_array)
void db_value_print (const DB_VALUE *value)
void db_value_fprint (FILE *fp, const DB_VALUE *value)
int db_value_coerce (const DB_VALUE *src, DB_VALUE *dest, const DB_DOMAIN *desired_domain)
int db_value_equal (const DB_VALUE *value1, const DB_VALUE *value2)
int db_value_compare (const DB_VALUE *value1, const DB_VALUE *value2)
int db_value_domain_init (DB_VALUE *value, DB_TYPE type, const int precision, const int scale)
int db_value_domain_min (DB_VALUE *value, DB_TYPE type, const int precision, const int scale, const int codeset, const int collation_id, const DB_ENUMERATION *enumeration)
int db_value_domain_max (DB_VALUE *value, DB_TYPE type, const int precision, const int scale, const int codeset, const int collation_id, const DB_ENUMERATION *enumeration)
int db_value_domain_default (DB_VALUE *value, const DB_TYPE type, const int precision, const int scale, const int codeset, const int collation_id, DB_ENUMERATION *enumeration)
int db_value_domain_zero (DB_VALUE *value, const DB_TYPE type, const int precision, const int scale)
int db_string_truncate (DB_VALUE *value, const int max_precision)
DB_TYPE db_value_domain_type (const DB_VALUE *value)
int db_value_put_null (DB_VALUE *value)
int db_value_put (DB_VALUE *value, const DB_TYPE_C c_type, void *input, const int input_length)
bool db_value_type_is_collection (const DB_VALUE *value)
bool db_value_is_null (const DB_VALUE *value)
int db_value_get (DB_VALUE *value, const DB_TYPE_C type, void *buf, const int buflen, int *transferlen, int *outputlen)
DB_CURRENCY db_value_get_monetary_currency (const DB_VALUE *value)
double db_value_get_monetary_amount_as_double (const DB_VALUE *value)
int db_value_put_monetary_currency (DB_VALUE *value, const DB_CURRENCY type)
int db_value_put_monetary_amount_as_double (DB_VALUE *value, const double amount)
int db_value_alter_type (DB_VALUE *value, DB_TYPE type)
int db_value_put_encoded_time (DB_VALUE *value, const DB_TIME *time_value)
int db_value_put_encoded_date (DB_VALUE *value, const DB_DATE *date_value)
DB_CURRENCY db_get_currency_default (void)
DB_DOMAIN * db_type_to_db_domain (DB_TYPE type)
const char * db_default_expression_string (DB_DEFAULT_EXPR_TYPE default_expr_type)
int db_get_deep_copy_of_json (const DB_JSON *src, DB_JSON *dst)
int db_init_db_json_pointers (DB_JSON *val)
int db_convert_json_into_scalar (const DB_VALUE *src, DB_VALUE *dest)
bool db_is_json_value_type (DB_TYPE type)
bool db_is_json_doc_type (DB_TYPE type)
int db_get_int (const DB_VALUE *value)
DB_C_SHORT db_get_short (const DB_VALUE *value)
DB_BIGINT db_get_bigint (const DB_VALUE *value)
DB_CONST_C_CHAR db_get_string (const DB_VALUE *value)
DB_C_FLOAT db_get_float (const DB_VALUE *value)
DB_C_DOUBLE db_get_double (const DB_VALUE *value)
DB_OBJECT * db_get_object (const DB_VALUE *value)
DB_COLLECTION * db_get_set (const DB_VALUE *value)
DB_MIDXKEY * db_get_midxkey (const DB_VALUE *value)
DB_C_POINTER db_get_pointer (const DB_VALUE *value)
DB_TIME * db_get_time (const DB_VALUE *value)
DB_TIMESTAMP * db_get_timestamp (const DB_VALUE *value)
DB_TIMESTAMPTZ * db_get_timestamptz (const DB_VALUE *value)
DB_DATETIME * db_get_datetime (const DB_VALUE *value)
DB_DATETIMETZ * db_get_datetimetz (const DB_VALUE *value)
DB_DATE * db_get_date (const DB_VALUE *value)
DB_MONETARY * db_get_monetary (const DB_VALUE *value)
int db_get_error (const DB_VALUE *value)
DB_ELO * db_get_elo (const DB_VALUE *value)
DB_C_NUMERIC db_get_numeric (const DB_VALUE *value)
DB_CONST_C_BIT db_get_bit (const DB_VALUE *value, int *length)
DB_CONST_C_CHAR db_get_char (const DB_VALUE *value, int *length)
DB_CONST_C_NCHAR db_get_nchar (const DB_VALUE *value, int *length)
int db_get_string_size (const DB_VALUE *value)
unsigned short db_get_enum_short (const DB_VALUE *value)
DB_CONST_C_CHAR db_get_enum_string (const DB_VALUE *value)
int db_get_enum_string_size (const DB_VALUE *value)
DB_C_CHAR db_get_method_error_msg (void)
DB_RESULTSET db_get_resultset (const DB_VALUE *value)
int db_get_string_codeset (const DB_VALUE *value)
int db_get_string_collation (const DB_VALUE *value)
int db_get_enum_codeset (const DB_VALUE *value)
int db_get_enum_collation (const DB_VALUE *value)
OID * db_get_oid (const DB_VALUE *value)
DB_TYPE db_value_type (const DB_VALUE *value)
int db_value_precision (const DB_VALUE *value)
int db_value_scale (const DB_VALUE *value)
JSON_DOC * db_get_json_document (const DB_VALUE *value)
int db_make_null (DB_VALUE *value)
int db_make_int (DB_VALUE *value, const int num)
int db_make_float (DB_VALUE *value, const DB_C_FLOAT num)
int db_make_double (DB_VALUE *value, const DB_C_DOUBLE num)
int db_make_object (DB_VALUE *value, DB_C_OBJECT *obj)
int db_make_midxkey (DB_VALUE *value, DB_MIDXKEY *midxkey)
int db_make_timestamp (DB_VALUE *value, const DB_C_TIMESTAMP timeval)
int db_make_timestampltz (DB_VALUE *value, const DB_C_TIMESTAMP ts_val)
int db_make_timestamptz (DB_VALUE *value, const DB_C_TIMESTAMPTZ *ts_tz_val)
int db_make_datetime (DB_VALUE *value, const DB_DATETIME *datetime)
int db_make_datetimeltz (DB_VALUE *value, const DB_DATETIME *datetime)
int db_make_datetimetz (DB_VALUE *value, const DB_DATETIMETZ *datetimetz)
int db_make_monetary (DB_VALUE *value, const DB_CURRENCY type, const double amount)
int db_make_pointer (DB_VALUE *value, DB_C_POINTER ptr)
int db_make_error (DB_VALUE *value, const int errcode)
int db_make_method_error (DB_VALUE *value, const int errcode, const char *errmsg)
int db_make_short (DB_VALUE *value, const DB_C_SHORT num)
int db_make_bigint (DB_VALUE *value, const DB_BIGINT num)
int db_make_numeric (DB_VALUE *value, const DB_C_NUMERIC num, const int precision, const int scale)
int db_make_bit (DB_VALUE *value, const int bit_length, DB_CONST_C_BIT bit_str, const int bit_str_bit_size)
int db_make_varbit (DB_VALUE *value, const int max_bit_length, DB_CONST_C_BIT bit_str, const int bit_str_bit_size)
int db_make_char (DB_VALUE *value, const int char_length, DB_CONST_C_CHAR str, const int char_str_byte_size, const int codeset, const int collation_id)
int db_make_varchar (DB_VALUE *value, const int max_char_length, DB_CONST_C_CHAR str, const int char_str_byte_size, const int codeset, const int collation_id)
int db_make_nchar (DB_VALUE *value, const int nchar_length, DB_CONST_C_NCHAR str, const int nchar_str_byte_size, const int codeset, const int collation_id)
int db_make_varnchar (DB_VALUE *value, const int max_nchar_length, DB_CONST_C_NCHAR str, const int nchar_str_byte_size, const int codeset, const int collation_id)
int db_make_enumeration (DB_VALUE *value, unsigned short index, DB_CONST_C_CHAR str, int size, unsigned char codeset, const int collation_id)
int db_make_resultset (DB_VALUE *value, const DB_RESULTSET handle)
int db_make_string (DB_VALUE *value, DB_CONST_C_CHAR str)
int db_make_string_copy (DB_VALUE *value, DB_CONST_C_CHAR str)
int db_make_oid (DB_VALUE *value, const OID *oid)
int db_make_set (DB_VALUE *value, DB_C_SET *set)
int db_make_multiset (DB_VALUE *value, DB_C_SET *set)
int db_make_sequence (DB_VALUE *value, DB_C_SET *set)
int db_make_collection (DB_VALUE *value, DB_C_SET *set)
int db_make_elo (DB_VALUE *value, DB_TYPE type, const DB_ELO *elo)
int db_make_time (DB_VALUE *value, const int hour, const int minute, const int second)
int db_make_date (DB_VALUE *value, const int month, const int day, const int year)
int db_get_compressed_size (DB_VALUE *value)
void db_set_compressed_string (DB_VALUE *value, char *compressed_string, int compressed_size, bool compressed_need_clear)
int db_make_json (DB_VALUE *value, JSON_DOC *json_document, bool need_clear)
Macro Definition Documentation
#define db_collection db_set
Definition at line 34 of file dbtype_function.h.
#define DB_CURRENCY_DEFAULT db_get_currency_default()
Definition at line 31 of file dbtype_function.h.
#define DB_GET_BIGINT (v) db_get_bigint(v)
Definition at line 185 of file dbtype_function.h.
#define DB_GET_BIGINTEGER DB_GET_BIGINT
Definition at line 222 of file dbtype_function.h.
#define DB_GET_BIT (v, l) db_get_bit(v, l)
Definition at line 204 of file dbtype_function.h.
#define DB_GET_CHAR (v, l) db_get_char(v, l)
Definition at line 205 of file dbtype_function.h.
#define db_get_collection db_get_set
Definition at line 175 of file dbtype_function.h.
#define DB_GET_COLLECTION (value) db_get_set(value)
Definition at line 227 of file dbtype_function.h.
#define DB_GET_COMPRESSED_SIZE (value) db_get_compressed_size(value)
Definition at line 231 of file dbtype_function.h.
#define DB_GET_DATE (v) db_get_date(v)
Definition at line 199 of file dbtype_function.h.
#define DB_GET_DATETIME (v) db_get_datetime(v)
Definition at line 197 of file dbtype_function.h.
#define DB_GET_DATETIMETZ (v) db_get_datetimetz(v)
Definition at line 198 of file dbtype_function.h.
#define DB_GET_DOUBLE (v) db_get_double(v)
Definition at line 189 of file dbtype_function.h.
#define DB_GET_ELO (v) db_get_elo(v)
Definition at line 202 of file dbtype_function.h.
#define DB_GET_ENUM_CODESET (v) db_get_enum_codeset(v)
Definition at line 215 of file dbtype_function.h.
#define DB_GET_ENUM_COLLATION (v) db_get_enum_collation(v)
Definition at line 216 of file dbtype_function.h.
#define DB_GET_ENUM_SHORT (v) db_get_enum_short(v)
Definition at line 208 of file dbtype_function.h.
#define DB_GET_ENUM_STRING (v) db_get_enum_string(v)
Definition at line 209 of file dbtype_function.h.
#define DB_GET_ENUM_STRING_SIZE (v) db_get_enum_string_size(v)
Definition at line 210 of file dbtype_function.h.
#define DB_GET_ERROR (v) db_get_error(v)
Definition at line 201 of file dbtype_function.h.
#define DB_GET_FLOAT (v) db_get_float(v)
Definition at line 186 of file dbtype_function.h.
#define DB_GET_INT (v) db_get_int(v)
Definition at line 183 of file dbtype_function.h.
#define DB_GET_INTEGER (value) db_get_int(value)
Definition at line 221 of file dbtype_function.h.
#define DB_GET_JSON_DOCUMENT (value) db_get_json_document(value)
Definition at line 233 of file dbtype_function.h.
#define DB_GET_LIST (value) db_get_set(value)
Definition at line 225 of file dbtype_function.h.
#define DB_GET_METHOD_ERROR_MSG () db_get_method_error_msg()
Definition at line 211 of file dbtype_function.h.
#define DB_GET_MIDXKEY (v) db_get_midxkey(v)
Definition at line 192 of file dbtype_function.h.
#define DB_GET_MONETARY (v) db_get_monetary(v)
Definition at line 200 of file dbtype_function.h.
#define DB_GET_MULTISET (value) db_get_set(value)
Definition at line 224 of file dbtype_function.h.
#define DB_GET_NCHAR (v, l) db_get_nchar(v, l)
Definition at line 206 of file dbtype_function.h.
#define DB_GET_NUMERIC (v) db_get_numeric(v)
Definition at line 203 of file dbtype_function.h.
#define DB_GET_OBJ DB_GET_OBJECT
Definition at line 223 of file dbtype_function.h.
#define DB_GET_OBJECT (v) db_get_object(v)
Definition at line 190 of file dbtype_function.h.
#define DB_GET_OID (value) (db_get_oid(value))
Definition at line 89 of file dbtype_function.h.
#define DB_GET_POINTER (v) db_get_pointer(v)
Definition at line 193 of file dbtype_function.h.
#define DB_GET_RESULTSET (v) db_get_resultset(v)
Definition at line 212 of file dbtype_function.h.
#define DB_GET_SEQ DB_GET_SEQUENCE
Definition at line 235 of file dbtype_function.h.
#define DB_GET_SEQUENCE DB_GET_LIST
Definition at line 226 of file dbtype_function.h.
#define DB_GET_SET (v) db_get_set(v)
Definition at line 191 of file dbtype_function.h.
#define DB_GET_SHORT (v) db_get_short(v)
Definition at line 184 of file dbtype_function.h.
#define DB_GET_SMALLINT (value) db_get_short(value)
Definition at line 229 of file dbtype_function.h.
#define DB_GET_STRING (v) db_get_string(v)
Definition at line 187 of file dbtype_function.h.
#define DB_GET_STRING_CODESET (v) ((INTL_CODESET) db_get_string_codeset(v))
Definition at line 213 of file dbtype_function.h.
#define DB_GET_STRING_COLLATION (v) db_get_string_collation(v)
Definition at line 214 of file dbtype_function.h.
#define DB_GET_STRING_LENGTH (v) db_get_string_length(v)
Definition at line 188 of file dbtype_function.h.
#define DB_GET_STRING_SIZE (v) db_get_string_size(v)
Definition at line 207 of file dbtype_function.h.
#define DB_GET_TIME (v) db_get_time(v)
Definition at line 194 of file dbtype_function.h.
#define DB_GET_TIMESTAMP (v) db_get_timestamp(v)
Definition at line 195 of file dbtype_function.h.
#define DB_GET_TIMESTAMPTZ (v) db_get_timestamptz(v)
Definition at line 196 of file dbtype_function.h.
#define db_get_utime db_get_timestamp
Definition at line 176 of file dbtype_function.h.
#define DB_GET_UTIME DB_GET_TIMESTAMP
Definition at line 228 of file dbtype_function.h.
#define DB_IS_NULL (value) db_value_is_null(value)
Definition at line 178 of file dbtype_function.h.
#define DB_MAKE_BIGINT (value, num) db_make_bigint(value, num)
Definition at line 54 of file dbtype_function.h.
#define DB_MAKE_BIGINTEGER DB_MAKE_BIGINT
Definition at line 56 of file dbtype_function.h.
#define DB_MAKE_BIT (value, bit_length, bit_str, bit_str_bit_size) db_make_bit(value, bit_length, bit_str, bit_str_bit_size)
Definition at line 150 of file dbtype_function.h.
#define DB_MAKE_CHAR (value, char_length, str, char_str_byte_size, codeset, collation) db_make_char(value, char_length, str, char_str_byte_size, codeset, collation)
Definition at line 156 of file dbtype_function.h.
#define DB_MAKE_COLLECTION (value, col) db_make_collection(value, col)
Definition at line 90 of file dbtype_function.h.
#define DB_MAKE_DATE (value, month, day, year) db_make_date(value, month, day, year)
Definition at line 102 of file dbtype_function.h.
#define DB_MAKE_DATETIME (value, datetime_value) db_make_datetime(value, datetime_value)
Definition at line 122 of file dbtype_function.h.
#define DB_MAKE_DATETIMELTZ (value, datetime_value) db_make_datetimeltz(value, datetime_value)
Definition at line 128 of file dbtype_function.h.
#define DB_MAKE_DATETIMETZ (value, datetimetz_value) db_make_datetimetz(value, datetimetz_value)
Definition at line 125 of file dbtype_function.h.
#define DB_MAKE_DOUBLE (value, num) db_make_double(value, num)
Definition at line 60 of file dbtype_function.h.
#define DB_MAKE_ELO (value, type, elo) db_make_elo(value, type, elo)
Definition at line 94 of file dbtype_function.h.
#define DB_MAKE_ENCODED_DATE (value, date_value) db_value_put_encoded_date(value, date_value)
Definition at line 105 of file dbtype_function.h.
#define DB_MAKE_ENCODED_TIME (value, time_value) db_value_put_encoded_time(value, time_value)
Definition at line 99 of file dbtype_function.h.
#define DB_MAKE_ENUMERATION (value, index, str, size, codeset, collation) db_make_enumeration(value, index, str, size, codeset, collation)
Definition at line 170 of file dbtype_function.h.
#define DB_MAKE_ERROR (value, errcode) db_make_error(value, errcode)
Definition at line 138 of file dbtype_function.h.
#define DB_MAKE_FLOAT (value, num) db_make_float(value, num)
Definition at line 58 of file dbtype_function.h.
#define DB_MAKE_INT DB_MAKE_INTEGER
Definition at line 52 of file dbtype_function.h.
#define DB_MAKE_INTEGER (value, num) db_make_int(value, num)
Definition at line 50 of file dbtype_function.h.
#define DB_MAKE_LIST DB_MAKE_SEQUENCE
Definition at line 75 of file dbtype_function.h.
#define DB_MAKE_METHOD_ERROR (value, errcode, errmsg) db_make_method_error(value, errcode, errmsg)
Definition at line 140 of file dbtype_function.h.
#define DB_MAKE_MIDXKEY (value, midxkey) db_make_midxkey(value, midxkey)
Definition at line 92 of file dbtype_function.h.
#define DB_MAKE_MONETARY DB_MAKE_MONETARY_AMOUNT
Definition at line 131 of file dbtype_function.h.
#define DB_MAKE_MONETARY_AMOUNT (value, amount) db_make_monetary(value, DB_CURRENCY_DEFAULT, amount)
Definition at line 119 of file dbtype_function.h.
#define DB_MAKE_MONETARY_TYPE_AMOUNT (value, type, amount) db_make_monetary(value, type, amount)
Definition at line 133 of file dbtype_function.h.
#define DB_MAKE_MULTI_SET DB_MAKE_MULTISET
Definition at line 71 of file dbtype_function.h.
#define DB_MAKE_MULTISET (value, set) db_make_multiset(value, set)
Definition at line 68 of file dbtype_function.h.
#define DB_MAKE_NCHAR (value, nchar_length, str, nchar_str_byte_size, codeset, collation) db_make_nchar(value, nchar_length, str, nchar_str_byte_size, codeset, collation)
Definition at line 164 of file dbtype_function.h.
#define DB_MAKE_NULL (value) db_make_null(value)
Definition at line 38 of file dbtype_function.h.
#define DB_MAKE_NUMERIC (value, num, precision, scale) db_make_numeric(value, num, precision, scale)
Definition at line 147 of file dbtype_function.h.
#define DB_MAKE_OBJ DB_MAKE_OBJECT
Definition at line 64 of file dbtype_function.h.
#define DB_MAKE_OBJECT (value, obj) db_make_object(value, obj)
Definition at line 62 of file dbtype_function.h.
#define DB_MAKE_OID (value, oid)
Value:
(((oid) == NULL) ? ((value)->domain.general_info.is_null = 1, NO_ERROR) : \
          db_make_oid((value), (oid)))
Definition at line 85 of file dbtype_function.h.
#define DB_MAKE_POINTER (value, ptr) db_make_pointer(value, ptr)
Definition at line 136 of file dbtype_function.h.
#define DB_MAKE_RESULTSET (value, handle) db_make_resultset(value, handle)
Definition at line 173 of file dbtype_function.h.
#define DB_MAKE_SEQ DB_MAKE_SEQUENCE
Definition at line 78 of file dbtype_function.h.
#define DB_MAKE_SEQUENCE (value, set) db_make_sequence(value, set)
Definition at line 73 of file dbtype_function.h.
#define DB_MAKE_SET (value, set) db_make_set(value, set)
Definition at line 66 of file dbtype_function.h.
#define DB_MAKE_SHORT DB_MAKE_SMALLINT
Definition at line 145 of file dbtype_function.h.
#define DB_MAKE_SMALLINT (value, num) db_make_short(value, num)
Definition at line 143 of file dbtype_function.h.
#define DB_MAKE_STRING (value, str) db_make_string(value, str)
Definition at line 162 of file dbtype_function.h.
#define DB_MAKE_TIME (value, hour, minute, second) db_make_time(value, hour, minute, second)
Definition at line 96 of file dbtype_function.h.
#define DB_MAKE_TIMESTAMP (value, timeval) db_make_timestamp(value, timeval)
Definition at line 108 of file dbtype_function.h.
#define DB_MAKE_TIMESTAMPLTZ (value, timeval) db_make_timestampltz(value, timeval)
Definition at line 116 of file dbtype_function.h.
#define DB_MAKE_TIMESTAMPTZ (value, ts_tz) db_make_timestamptz(value, ts_tz)
Definition at line 113 of file dbtype_function.h.
#define db_make_utime db_make_timestamp
Definition at line 36 of file dbtype_function.h.
#define DB_MAKE_UTIME DB_MAKE_TIMESTAMP
Definition at line 111 of file dbtype_function.h.
#define DB_MAKE_VARBIT (value, max_bit_length, bit_str, bit_str_bit_size) db_make_varbit(value, max_bit_length, bit_str, bit_str_bit_size)
Definition at line 153 of file dbtype_function.h.
#define DB_MAKE_VARCHAR (value, max_char_length, str, char_str_byte_size, codeset, collation) db_make_varchar(value, max_char_length, str, char_str_byte_size, codeset, collation)
Definition at line 159 of file dbtype_function.h.
#define DB_MAKE_VARNCHAR (value, max_nchar_length, str, nchar_str_byte_size, codeset, collation) db_make_varnchar(value, max_nchar_length, str, nchar_str_byte_size, codeset, collation)
Definition at line 167 of file dbtype_function.h.
#define DB_SET_COMPRESSED_STRING (value, compressed_string, compressed_size, compressed_need_clear) db_set_compressed_string(value, compressed_string, compressed_size, compressed_need_clear)
Definition at line 237 of file dbtype_function.h.
#define DB_TRIED_COMPRESSION (value) (DB_GET_COMPRESSED_SIZE(value) != DB_NOT_YET_COMPRESSED)
Definition at line 240 of file dbtype_function.h.
#define DB_VALUE_CLONE_AS_NULL (src_value, dest_value)
Value:
do {                                                                  \
    if ((db_value_domain_init(dest_value,                               \
                              db_value_domain_type(src_value),          \
                              db_value_precision(src_value),            \
                              db_value_scale(src_value)))               \
        == NO_ERROR)                                                    \
      (void)db_value_put_null(dest_value);                              \
  } while (0)
Definition at line 40 of file dbtype_function.h.
#define DB_VALUE_DOMAIN_TYPE (value) db_value_domain_type(value)
Definition at line 180 of file dbtype_function.h.
#define DB_VALUE_PRECISION (value) db_value_precision(value)
Definition at line 218 of file dbtype_function.h.
#define DB_VALUE_SCALE (value) db_value_scale(value)
Definition at line 219 of file dbtype_function.h.
#define DB_VALUE_TYPE (value) db_value_type(value)
Definition at line 217 of file dbtype_function.h.
Function Documentation
int db_convert_json_into_scalar (const DB_VALUE * src, DB_VALUE * dest)
Definition at line 4981 of file db_macro.c.
References assert, ASSERT_ERROR, CHECK_2ARGS_ERROR, db_get_json_document(), db_json_get_bigint_from_document(), db_json_get_bool_as_str_from_document(), db_json_get_double_from_document(), db_json_get_int_from_document(), db_json_get_string_from_document(), db_json_get_type(), db_make_bigint(), db_make_double(), db_make_int(), db_make_null(), db_make_string(), ER_FAILED, db_value::need_clear, NO_ERROR, and NULL.
Referenced by mr_cmpval_json().
void db_date_decode (const DB_DATE * date, int * monthp, int * dayp, int * yearp)
Definition at line 338 of file db_date.c.
References julian_decode(), and NULL.
Referenced by date_as_string(), date_to_char(), db_add_months(), db_date_add_sub_interval_days(), db_date_add_sub_interval_expr(), db_date_format(), db_date_to_string(), db_datetime_decode(), db_get_datetime_from_dbvalue(), db_last_day(), db_months_between(), db_new_time(), db_print_data(), db_string_date(), db_string_datetime(), db_string_extract_dbval(), db_string_timestamp(), db_timestamp_string(), db_value_to_value(), dbval_to_net_buf(), ehash_dump_bucket(), ehash_rv_init_dir_new_page_redo(), fmt_date_string(), jsp_pack_date_argument(), jsp_pack_timestamp_argument(), ko_time_value(), move_n_days(), numeric_db_value_coerce_from_num(), pt_evaluate_db_value_expr(), qdata_add_bigint_to_date(), qdata_add_bigint_to_timestamptz(), qdata_add_bigint_to_utime(), qdata_add_int_to_date(), qdata_add_int_to_timestamptz(), qdata_add_int_to_utime(), qdata_add_short_to_date(), qdata_add_short_to_timestamptz(), qdata_add_short_to_utime(), qdata_subtract_bigint_to_dbval(), qdata_subtract_date_to_dbval(), qdata_subtract_int_to_dbval(), round_date(), tp_value_cast_internal(), truncate_date(), and us_time_value().
int db_date_encode (DB_DATE * date, int month, int day, int year)
Definition at line 275 of file db_date.c.
References ARG_FILE_LINE, ER_DATE_CONVERSION, ER_ERROR_SEVERITY, er_set(), julian_decode(), julian_encode(), NO_ERROR, and NULL.
Referenced by coerce_date_to_dbvalue(), db_date_add_sub_interval_days(), db_date_add_sub_interval_expr(), db_datetime_encode(), db_datetime_string(), db_string_date(), db_string_timestamp(), db_to_timestamp(), fmt_date_value(), move_n_days(), netval_to_dbval(), pt_xasl_data_type_to_domain(), and truncate_date().
const char* db_default_expression_string (DB_DEFAULT_EXPR_TYPE default_expr_type)
Definition at line 4947 of file db_macro.c.
References DB_DEFAULT_CURR_USER, DB_DEFAULT_CURRENTDATE, DB_DEFAULT_CURRENTDATETIME, DB_DEFAULT_CURRENTTIME, DB_DEFAULT_CURRENTTIMESTAMP, DB_DEFAULT_NONE, DB_DEFAULT_SYSDATE, DB_DEFAULT_SYSDATETIME, DB_DEFAULT_SYSTIME, DB_DEFAULT_SYSTIMESTAMP, DB_DEFAULT_UNIX_TIMESTAMP, DB_DEFAULT_USER, and NULL.
Referenced by catcls_get_or_value_from_attribute(), object_printer::describe_attribute(), emit_attribute_def(), get_column_default_as_string(), pt_print_attr_def(), and qexec_execute_build_columns().
DB_BIGINT db_get_bigint (const DB_VALUE * value)
Referenced by csql_db_value_as_string(), db_abs_dbval(), db_bigint_to_binary_string(), db_bit_count_dbval(), db_ceil_dbval(), db_conv(), db_date_add_sub_interval_expr(), db_exp_dbval(), db_floor_dbval(), db_format(), db_hex(), db_inet_ntoa(), db_log_dbval(), db_mod_bigint(), db_mod_double(), db_mod_float(), db_mod_int(), db_mod_monetary(), db_mod_numeric(), db_mod_short(), db_round_dbval(), db_round_dbvalue_to_int(), db_sign_dbval(), db_sqrt_dbval(), db_string_chr(), db_string_elt(), db_string_sha_two(), db_string_space(), db_string_value(), db_timestamp(), db_trunc_dbval(), db_value_get(), dbval_to_net_buf(), db_value_printer::describe_data(), fetch_peek_dbval(), fprint_special_strings(), get_number_dbval_as_double(), get_number_dbval_as_long_double(), heap_object_upgrade_domain(), jsp_pack_bigint_argument(), la_get_ha_apply_info(), mht_get_hash_number(), mht_valhash(), mr_cmpval_bigint(), mr_data_writeval_bigint(), mr_index_writeval_bigint(), mr_setmem_bigint(), mr_setval_bigint(), number_to_char(), numeric_db_value_coerce_to_num(), pt_check_const_fold_op_w_args(), pt_check_ordby_num_for_multi_range_opt(), pt_compare_bounds_to_value(), pt_dbval_to_value(), pt_evaluate_db_value_expr(), pt_get_query_limit_from_limit(), pt_get_query_limit_from_orderby_for(), pt_recompile_for_limit_optimizations(), qdata_add_bigint_to_dbval(), qdata_add_date_to_dbval(), qdata_add_datetime_to_dbval(), qdata_add_double_to_dbval(), qdata_add_float_to_dbval(), qdata_add_int_to_dbval(), qdata_add_monetary_to_dbval(), qdata_add_short_to_dbval(), qdata_add_time_to_dbval(), qdata_add_timestamptz_to_dbval(), qdata_add_utime_to_dbval(), qdata_apply_interpolation_function_coercion(), qdata_benchmark(), qdata_bit_and_dbval(), qdata_bit_not_dbval(), qdata_bit_or_dbval(), qdata_bit_shift_dbval(), qdata_bit_xor_dbval(), qdata_divide_bigint_to_dbval(), qdata_divide_double_to_dbval(), qdata_divide_float_to_dbval(), qdata_divide_int_to_dbval(), qdata_divide_monetary_to_dbval(), qdata_divide_short_to_dbval(), qdata_divmod_dbval(), qdata_elt(), qdata_increment_dbval(), qdata_interpolation_function_values(), qdata_is_divided_zero(), qdata_multiply_bigint(), qdata_multiply_bigint_to_dbval(), qdata_multiply_double_to_dbval(), qdata_multiply_float_to_dbval(), qdata_multiply_monetary_to_dbval(), qdata_subtract_bigint_to_dbval(), qdata_subtract_date_to_dbval(), qdata_subtract_datetime_to_dbval(), qdata_subtract_double_to_dbval(), qdata_subtract_float_to_dbval(), qdata_subtract_int_to_dbval(), qdata_subtract_monetary_to_dbval(), qdata_subtract_short_to_dbval(), qdata_subtract_time_to_dbval(), qdata_subtract_timestamptz_to_dbval(), qdata_subtract_utime_to_dbval(), qdata_unary_minus_dbval(), qo_discover_sort_limit_nodes(), qo_mjoin_cost(), qo_nljoin_cost(), scan_init_index_key_limit(), tp_value_cast_internal(), tp_value_coerce_strict(), valcnv_convert_data_to_string(), and value_as_boolean().
DB_CONST_C_BIT db_get_bit (const DB_VALUE * value, int * length)
Referenced by bfmt_print(), db_ascii(), db_bit_to_blob(), db_conv(), db_hex(), db_string_truncate(), dbval_to_net_buf(), fetch_peek_arith(), mht_valhash(), mr_setval_bit(), pt_dbval_to_value(), pt_evaluate_db_value_expr(), qdata_evaluate_connect_by_root(), qdata_evaluate_qprior(), qdata_evaluate_sys_connect_by_path(), and qexec_check_for_cycle().
DB_CONST_C_CHAR db_get_char (const DB_VALUE * value, int * length)
Referenced by convert_db_value_to_string(), csql_db_value_as_string(), csql_display_trace(), db_inet_aton(), db_string_truncate(), db_string_value(), and dbval_to_net_buf().
int db_get_compressed_size (DB_VALUE * value)
Referenced by mr_lengthval_string_internal(), mr_lengthval_varnchar_internal(), mr_writeval_string_internal(), and mr_writeval_varnchar_internal().
DB_CURRENCY db_get_currency_default (void)
Definition at line 1870 of file db_macro.c.
References lang_currency().
Referenced by netval_to_dbval().
DB_DATE* db_get_date (const DB_VALUE * value)
Referenced by csql_db_value_as_string(), date_to_char(), db_add_months(), db_add_time(), db_date_add_sub_interval_days(), db_date_add_sub_interval_expr(), db_date_format(), db_get_datetime_from_dbvalue(), db_months_between(), db_string_extract_dbval(), db_string_value(), db_to_date(), db_trunc_dbval(), db_unix_timestamp(), db_value_get(), db_width_bucket(), dbval_to_net_buf(), db_value_printer::describe_data(), fprint_special_strings(), jsp_pack_date_argument(), mht_valhash(), mr_cmpval_date(), mr_data_writeval_date(), mr_index_writeval_date(), mr_setmem_date(), mr_setval_date(), pt_dbval_to_value(), pt_evaluate_db_value_expr(), qdata_add_bigint_to_date(), qdata_add_int_to_date(), qdata_add_short_to_date(), qdata_interpolation_function_values(), qdata_is_zero_value_date(), qdata_subtract_bigint_to_dbval(), qdata_subtract_date_to_dbval(), qdata_subtract_datetime_to_dbval(), qdata_subtract_datetimetz_to_dbval(), qdata_subtract_int_to_dbval(), qdata_subtract_short_to_dbval(), round_date(), tp_value_cast_internal(), tp_value_coerce_strict(), valcnv_convert_data_to_string(), value_as_boolean(), and value_to_db_value().
DB_DATETIME* db_get_datetime (const DB_VALUE * value)
Referenced by catcls_get_apply_info_log_record_time(), chksum_report_schema_diff(), csql_db_value_as_string(), date_to_char(), db_add_time(), db_conv_tz(), db_date_add_sub_interval_days(), db_date_add_sub_interval_expr(), db_date_format(), db_datetime_to_timestamp(), db_from_tz(), db_get_datetime_from_dbvalue(), db_get_time_from_dbvalue(), db_new_time(), db_set_base_server_time(), db_string_extract_dbval(), db_string_value(), db_time_format(), db_trunc_dbval(), db_unix_timestamp(), db_value_get(), db_width_bucket(), dbval_to_net_buf(), db_value_printer::describe_data(), do_evaluate_default_expr(), fprint_special_strings(), jsp_pack_datetime_argument(), la_get_ha_apply_info(), mht_valhash(), mr_cmpval_datetime(), mr_data_writeval_datetime(), mr_index_writeval_datetime(), mr_setmem_datetime(), mr_setval_datetime(), mr_setval_datetimeltz(), pt_dbval_to_value(), pt_evaluate_db_value_expr(), qdata_add_bigint_to_datetime(), qdata_add_bigint_to_dbval(), qdata_add_datetimetz_to_dbval(), qdata_add_dbval(), qdata_add_int_to_datetime(), qdata_add_int_to_dbval(), qdata_add_short_to_datetime(), qdata_add_short_to_dbval(), qdata_interpolation_function_values(), qdata_is_zero_value_date(), qdata_strcat_dbval(), qdata_subtract_datetime_to_dbval(), qdata_subtract_datetimetz_to_dbval(), qdata_subtract_dbval(), qdata_subtract_int_to_dbval(), qdata_subtract_timestamptz_to_dbval(), qdata_subtract_utime_to_dbval(), round_date(), tp_value_cast_internal(), tp_value_coerce_strict(), valcnv_convert_data_to_string(), and value_as_boolean().
DB_DATETIMETZ* db_get_datetimetz (const DB_VALUE * value)
Referenced by csql_db_value_as_string(), date_to_char(), db_add_time(), db_conv_tz(), db_date_add_sub_interval_days(), db_date_add_sub_interval_expr(), db_date_format(), db_get_datetime_from_dbvalue(), db_get_time_from_dbvalue(), db_string_extract_dbval(), db_time_format(), db_trunc_dbval(), db_unix_timestamp(), db_width_bucket(), dbval_to_net_buf(), db_value_printer::describe_data(), fprint_special_strings(), mht_valhash(), mr_cmpval_datetimetz(), mr_data_writeval_datetimetz(), mr_index_writeval_datetimetz(), mr_setmem_datetimetz(), mr_setval_datetimetz(), pt_dbval_to_value(), pt_evaluate_db_value_expr(), qdata_add_datetimetz_to_dbval(), qdata_interpolation_function_values(), qdata_is_zero_value_date(), qdata_subtract_datetime_to_dbval(), qdata_subtract_datetimetz_to_dbval(), qdata_subtract_int_to_dbval(), qdata_subtract_timestamptz_to_dbval(), qdata_subtract_utime_to_dbval(), round_date(), tp_value_cast_internal(), tp_value_coerce_strict(), valcnv_convert_data_to_string(), and value_as_boolean().
int db_get_deep_copy_of_json (const DB_JSON * src, DB_JSON * dst)
Definition at line 2022 of file db_macro.c.
References assert, CHECK_2ARGS_ERROR, db_json_get_copy_of_doc(), db_private_strdup(), db_json::document, NO_ERROR, NULL, and db_json::schema_raw.
Referenced by mr_getmem_json(), and mr_setmem_json().
DB_C_DOUBLE db_get_double (const DB_VALUE * value)
Referenced by csql_db_value_as_string(), db_abs_dbval(), db_bit_count_dbval(), db_ceil_dbval(), db_conv(), db_date_add_sub_interval_expr(), db_exp_dbval(), db_floor_dbval(), db_log_dbval(), db_mod_bigint(), db_mod_double(), db_mod_float(), db_mod_int(), db_mod_monetary(), db_mod_numeric(), db_mod_short(), db_round_dbval(), db_round_dbvalue_to_int(), db_sign_dbval(), db_sleep(), db_sqrt_dbval(), db_string_chr(), db_string_value(), db_timestamp(), db_trunc_dbval(), db_value_get(), db_width_bucket(), dbval_to_net_buf(), db_value_printer::describe_data(), fprint_special_strings(), get_number_dbval_as_double(), get_number_dbval_as_long_double(), get_priority(), heap_object_upgrade_domain(), jsp_pack_double_argument(), mht_valhash(), mr_cmpval_double(), mr_data_writeval_double(), mr_index_writeval_double(), mr_setmem_double(), mr_setval_double(), number_to_char(), numeric_db_value_coerce_to_num(), object_to_trigger(), pt_compare_bounds_to_value(), pt_dbval_to_value(), pt_evaluate_db_value_expr(), qdata_add_bigint_to_dbval(), qdata_add_double_to_dbval(), qdata_add_float_to_dbval(), qdata_add_int_to_dbval(), qdata_add_monetary_to_dbval(), qdata_add_numeric_to_dbval(), qdata_add_short_to_dbval(), qdata_apply_interpolation_function_coercion(), qdata_coerce_numeric_to_double(), qdata_divide_bigint_to_dbval(), qdata_divide_double_to_dbval(), qdata_divide_float_to_dbval(), qdata_divide_int_to_dbval(), qdata_divide_monetary_to_dbval(), qdata_divide_numeric_to_dbval(), qdata_divide_short_to_dbval(), qdata_evaluate_aggregate_list(), qdata_evaluate_analytic_func(), qdata_finalize_aggregate_list(), qdata_finalize_analytic_func(), qdata_interpolation_function_values(), qdata_is_divided_zero(), qdata_multiply_bigint_to_dbval(), qdata_multiply_double_to_dbval(), qdata_multiply_float_to_dbval(), qdata_multiply_int_to_dbval(), qdata_multiply_monetary_to_dbval(), qdata_multiply_numeric_to_dbval(), qdata_multiply_short_to_dbval(), qdata_subtract_bigint_to_dbval(), qdata_subtract_double_to_dbval(), qdata_subtract_float_to_dbval(), qdata_subtract_int_to_dbval(), qdata_subtract_monetary_to_dbval(), qdata_subtract_numeric_to_dbval(), qdata_subtract_short_to_dbval(), qdata_unary_minus_dbval(), qexec_analytic_evaluate_interpolation_function(), qexec_analytic_evaluate_offset_function(), tp_dtoa(), tp_value_cast_internal(), tp_value_coerce_strict(), valcnv_convert_data_to_string(), and value_as_boolean().
DB_ELO* db_get_elo (const DB_VALUE * value)
Referenced by bind_value_print(), csql_db_value_as_string(), db_bit_to_blob(), db_char_to_blob(), db_char_to_clob(), dblob_to_caslob(), delete_object_tuple(), db_value_printer::describe_data(), fn_lob_read(), fn_lob_write(), heap_attrinfo_delete_lob(), heap_attrinfo_set_uninitialized(), heap_attrinfo_transform_to_disk_internal(), lob_from_file(), lob_length(), lob_to_bit_char(), mr_cmpval_elo(), mr_data_lengthval_elo(), mr_data_writeval_elo(), mr_setmem_elo(), obt_apply_assignments(), pr_clear_value(), process_value(), pt_dbval_to_value(), qexec_execute_delete(), qexec_execute_update(), setobj_get_element(), setval_elo_with_type(), ux_lob_new(), ux_lob_read(), ux_lob_write(), and valcnv_convert_data_to_string().
int db_get_enum_codeset (const DB_VALUE * value)
Referenced by catcls_get_or_value_from_attribute(), csql_db_value_as_string(), db_get_cs_coll_info(), dbval_to_net_buf(), db_value_printer::describe_value(), fetch_peek_arith(), fetch_peek_dbval(), mr_setval_enumeration(), pr_clear_value(), tp_enumeration_to_varchar(), tp_value_cast_internal(), and tp_value_compare_with_error().
int db_get_enum_collation (const DB_VALUE * value)
Referenced by catcls_get_or_value_from_attribute(), db_get_cs_coll_info(), mr_setval_enumeration(), pr_clear_value(), pr_complete_enum_value(), tp_domain_select(), tp_enumeration_to_varchar(), tp_value_cast_internal(), and tp_value_compare_with_error().
unsigned short db_get_enum_short (const DB_VALUE * value)
Referenced by catcls_get_or_value_from_attribute(), csql_db_value_as_string(), db_value_printer::describe_value(), fprint_special_strings(), mr_cmpval_enumeration(), mr_data_writeval_enumeration(), mr_index_writeval_enumeration(), mr_setmem_enumeration(), mr_setval_enumeration(), numeric_db_value_coerce_to_num(), pr_complete_enum_value(), pt_dbval_to_value(), pt_evaluate_db_value_expr(), pt_fix_enumeration_comparison(), tp_domain_select(), tp_value_cast_internal(), and valcnv_convert_data_to_string().
DB_CONST_C_CHAR db_get_enum_string (const DB_VALUE * value)
Referenced by csql_db_value_as_string(), db_value_to_json_value(), dbval_to_net_buf(), db_value_printer::describe_value(), mr_setval_enumeration(), pr_clear_value(), pr_complete_enum_value(), pt_dbval_to_value(), pt_fix_enumeration_comparison(), tp_domain_select(), tp_enumeration_to_varchar(), tp_value_cast_internal(), and valcnv_convert_data_to_string().
int db_get_enum_string_size (const DB_VALUE * value)
Referenced by csql_db_value_as_string(), db_value_to_json_value(), dbval_to_net_buf(), mr_setval_enumeration(), pr_complete_enum_value(), pt_dbval_to_value(), tp_domain_select(), tp_enumeration_to_varchar(), tp_value_cast_internal(), and valcnv_convert_data_to_string().
int db_get_error (const DB_VALUE * value)
Referenced by call_method(), db_value_printer::describe_data(), do_alter_change_owner(), do_alter_trigger(), fprint_special_strings(), get_current_result(), mr_cmpval_error(), mr_data_lengthval_error(), mr_setmem_error(), and mr_setval_error().
DB_C_FLOAT db_get_float (const DB_VALUE * value)
Referenced by check_timeout_value(), csql_db_value_as_string(), db_abs_dbval(), db_bit_count_dbval(), db_ceil_dbval(), db_conv(), db_date_add_sub_interval_expr(), db_exp_dbval(), db_floor_dbval(), db_log_dbval(), db_mod_bigint(), db_mod_double(), db_mod_float(), db_mod_int(), db_mod_monetary(), db_mod_numeric(), db_mod_short(), db_round_dbval(), db_round_dbvalue_to_int(), db_sign_dbval(), db_sqrt_dbval(), db_string_chr(), db_string_value(), db_timestamp(), db_trunc_dbval(), db_value_get(), dbval_to_net_buf(), db_value_printer::describe_data(), do_set_xaction(), fprint_special_strings(), get_current_result(), get_number_dbval_as_double(), get_number_dbval_as_long_double(), heap_object_upgrade_domain(), jsp_pack_float_argument(), mht_valhash(), mr_cmpval_float(), mr_data_writeval_float(), mr_index_writeval_float(), mr_setmem_float(), mr_setval_float(), number_to_char(), numeric_db_value_coerce_to_num(), pt_compare_bounds_to_value(), pt_dbval_to_value(), pt_evaluate_db_value_expr(), qdata_add_bigint_to_dbval(), qdata_add_double_to_dbval(), qdata_add_float_to_dbval(), qdata_add_int_to_dbval(), qdata_add_monetary_to_dbval(), qdata_add_numeric_to_dbval(), qdata_add_short_to_dbval(), qdata_apply_interpolation_function_coercion(), qdata_divide_bigint_to_dbval(), qdata_divide_double_to_dbval(), qdata_divide_float_to_dbval(), qdata_divide_int_to_dbval(), qdata_divide_monetary_to_dbval(), qdata_divide_numeric_to_dbval(), qdata_divide_short_to_dbval(), qdata_interpolation_function_values(), qdata_is_divided_zero(), qdata_multiply_double_to_dbval(), qdata_multiply_float(), qdata_multiply_float_to_dbval(), qdata_multiply_monetary_to_dbval(), qdata_multiply_numeric_to_dbval(), qdata_subtract_bigint_to_dbval(), qdata_subtract_double_to_dbval(), qdata_subtract_float_to_dbval(), qdata_subtract_int_to_dbval(), qdata_subtract_monetary_to_dbval(), qdata_subtract_numeric_to_dbval(), qdata_subtract_short_to_dbval(), qdata_unary_minus_dbval(), tp_ftoa(), tp_value_cast_internal(), tp_value_coerce_strict(), valcnv_convert_data_to_string(), and value_as_boolean().
int db_get_int (const DB_VALUE * value)
Referenced by apif_last_pos(), apif_tell(), apply_grants(), au_check_authorization_method(), au_drop_user(), au_force_write_new_auth(), au_grant(), au_print_grant_entry(), au_propagate_del_new_auth(), au_revoke(), btree_index_start_scan(), build_class_grant_list(), catcls_apply_resolutions(), catcls_convert_attr_id_to_name(), catcls_get_db_collation(), catcls_get_or_value_from_attribute(), catcls_get_or_value_from_indexes(), catcls_get_server_compat_info(), check_serial_invariants(), chksum_get_prev_checksum_results(), chksum_report_diff(), chksum_report_summary(), chksum_update_master_checksum(), classobj_cache_constraint_entry(), classobj_make_class_constraints(), classobj_make_foreign_key_info(), classobj_make_foreign_key_ref(), classobj_make_function_index_info(), classobj_make_index_filter_pred_info(), classobj_make_index_prefix_info(), collect_class_grants(), csql_db_value_as_string(), date_to_char(), db_abs_dbval(), db_add_months(), db_bit_count_dbval(), db_blob_to_bit(), db_ceil_dbval(), db_clob_to_char(), db_conv(), db_date_add_sub_interval_days(), db_date_add_sub_interval_expr(), db_date_format(), db_exp_dbval(), db_floor_dbval(), db_format(), db_from_unixtime(), db_log_dbval(), db_mod_bigint(), db_mod_double(), db_mod_float(), db_mod_int(), db_mod_monetary(), db_mod_numeric(), db_mod_short(), db_round_dbval(), db_round_dbvalue_to_int(), db_sign_dbval(), db_sqrt_dbval(), db_str_to_date(), db_string_chr(), db_string_elt(), db_string_index_prefix(), db_string_insert_substring(), db_string_instr(), db_string_pad(), db_string_regexp_count(), db_string_regexp_instr(), db_string_regexp_replace(), db_string_regexp_substr(), db_string_repeat(), db_string_sha_two(), db_string_space(), db_string_substring(), db_string_substring_index(), db_string_unique_prefix(), db_string_value(), db_time_format(), db_timestamp(), db_to_date(), db_to_datetime(), db_to_number(), db_to_time(), db_to_timestamp(), db_trunc_dbval(), db_value_get(), db_width_bucket_calculate_numeric(), dbval_to_net_buf(), db_value_printer::describe_data(), object_printer::describe_partition_info(), disk_to_attribute(), disk_volume_header_start_scan(), do_alter_serial(), do_change_auto_increment_serial(), do_check_rows_for_null(), do_create_auto_increment_serial(), do_create_serial(), do_get_serial_cached_num(), do_set_optimization_param(), do_set_trigger(), drop_stored_procedure(), emit_instance_attributes(), emit_partition_info(), emit_stored_procedure(), emit_stored_procedure_args(), export_serial(), fetch_peek_arith(), fetch_peek_dbval(), fprint_special_strings(), get_codeset_from_db_root(), get_current_result(), get_grants(), get_number_dbval_as_double(), get_number_dbval_as_long_double(), heap_header_capacity_start_scan(), heap_object_upgrade_domain(), jsp_alter_stored_procedure(), jsp_do_call_stored_procedure(), jsp_get_return_type(), jsp_pack_int_argument(), la_get_ha_apply_info(), mht_valhash(), mq_evaluate_check_option(), mr_cmpval_int(), mr_cmpval_numeric(), mr_data_cmpdisk_numeric(), mr_data_writeval_int(), mr_index_writeval_int(), mr_setmem_int(), mr_setval_int(), number_to_char(), numeric_db_value_coerce_to_num(), object_to_trigger(), or_get_current_representation(), or_install_btids_class(), or_install_btids_constraint(), or_install_btids_foreign_key(), or_install_btids_foreign_key_ref(), or_install_btids_function_info(), or_install_btids_prefix_length(), propagate_revoke(), pt_check_const_fold_op_w_args(), pt_check_filter_index_expr_pre(), pt_compare_bounds_to_value(), pt_dbval_to_value(), pt_evaluate_db_value_expr(), pt_evaluate_tree_internal(), pt_fold_const_expr(), qdata_add_bigint_to_dbval(), qdata_add_date_to_dbval(), qdata_add_datetime_to_dbval(), qdata_add_double_to_dbval(), qdata_add_float_to_dbval(), qdata_add_int_to_dbval(), qdata_add_monetary_to_dbval(), qdata_add_short_to_dbval(), qdata_add_time_to_dbval(), qdata_add_timestamptz_to_dbval(), qdata_add_utime_to_dbval(), qdata_aggregate_value_to_accumulator(), qdata_apply_interpolation_function_coercion(), qdata_benchmark(), qdata_bit_and_dbval(), qdata_bit_not_dbval(), qdata_bit_or_dbval(), qdata_bit_shift_dbval(), qdata_bit_xor_dbval(), qdata_divide_bigint_to_dbval(), qdata_divide_double_to_dbval(), qdata_divide_float_to_dbval(), qdata_divide_int_to_dbval(), qdata_divide_monetary_to_dbval(), qdata_divide_short_to_dbval(), qdata_divmod_dbval(), qdata_elt(), qdata_evaluate_analytic_func(), qdata_get_cardinality(), qdata_increment_dbval(), qdata_interpolation_function_values(), qdata_is_divided_zero(), qdata_multiply_bigint_to_dbval(), qdata_multiply_double_to_dbval(), qdata_multiply_float_to_dbval(), qdata_multiply_int(), qdata_multiply_int_to_dbval(), qdata_multiply_monetary_to_dbval(), qdata_subtract_bigint_to_dbval(), qdata_subtract_date_to_dbval(), qdata_subtract_datetime_to_dbval(), qdata_subtract_double_to_dbval(), qdata_subtract_float_to_dbval(), qdata_subtract_int_to_dbval(), qdata_subtract_monetary_to_dbval(), qdata_subtract_short_to_dbval(), qdata_subtract_time_to_dbval(), qdata_subtract_timestamptz_to_dbval(), qdata_subtract_utime_to_dbval(), qdata_unary_minus_dbval(), qexec_execute_selupd_list(), qexec_execute_update(), qexec_fill_sort_limit(), qexec_recalc_tuples_parent_pos_in_list(), qexec_setup_topn_proc(), serial_get_next_cached_value(), serial_get_nth_value(), session_add_variable(), set_iso_level(), spage_header_start_scan(), spage_slots_start_scan(), stran_get_local_transaction_id(), synccoll_check(), tp_value_cast_internal(), tp_value_coerce_strict(), tzc_compute_timezone_checksum(), update_objs_for_list_file(), valcnv_convert_data_to_string(), value_as_boolean(), ws_rehash_vmop(), and xserial_get_next_value_internal().
JSON_DOC* db_get_json_document (const DB_VALUE * value)
Referenced by db_accumulate_json_arrayagg(), db_accumulate_json_objectagg(), db_convert_json_into_scalar(), db_value_to_json_value(), mr_cmpval_json(), mr_data_writeval_json(), mr_setmem_json(), cubscan::json_table::scanner::open(), and tp_value_cast_internal().
DB_C_CHAR db_get_method_error_msg (void)
DB_MIDXKEY* db_get_midxkey (const DB_VALUE * value)
Referenced by btree_apply_key_range_and_filter(), btree_attrinfo_read_dbvalues(), btree_coerce_key(), btree_compare_key(), btree_get_stats_key(), btree_get_unique_statistics(), btree_multicol_key_has_null(), btree_multicol_key_is_null(), btree_node_size_uncompressed(), btree_prepare_bts(), btree_range_opt_check_add_index_key(), btree_scan_update_range(), btree_top_n_items_binary_search(), db_value_printer::describe_data(), eval_key_filter(), mht_valhash(), mr_cmpval_midxkey(), mr_index_writeval_midxkey(), mr_setval_midxkey(), pr_midxkey_add_elements(), pr_midxkey_add_prefix(), pr_midxkey_common_prefix(), pr_midxkey_remove_prefix(), pr_midxkey_unique_prefix(), scan_key_compare(), sl_print_pk(), and tp_domain_resolve_value().
DB_MONETARY* db_get_monetary (const DB_VALUE * value)
Referenced by csql_db_value_as_string(), db_abs_dbval(), db_bit_count_dbval(), db_ceil_dbval(), db_exp_dbval(), db_floor_dbval(), db_log_dbval(), db_mod_bigint(), db_mod_double(), db_mod_float(), db_mod_int(), db_mod_monetary(), db_mod_numeric(), db_mod_short(), db_round_dbval(), db_round_dbvalue_to_int(), db_sign_dbval(), db_sqrt_dbval(), db_string_chr(), db_string_value(), db_trunc_dbval(), db_value_get(), db_value_printer::describe_data(), fprint_special_strings(), get_number_dbval_as_double(), get_number_dbval_as_long_double(), heap_object_upgrade_domain(), jsp_pack_monetary_argument(), mht_valhash(), mr_cmpval_money(), mr_data_writeval_money(), mr_index_writeval_money(), mr_setmem_money(), mr_setval_money(), number_to_char(), pt_compare_bounds_to_value(), pt_dbval_to_value(), pt_evaluate_db_value_expr(), pt_print_db_value(), qdata_add_bigint_to_dbval(), qdata_add_double_to_dbval(), qdata_add_float_to_dbval(), qdata_add_int_to_dbval(), qdata_add_monetary_to_dbval(), qdata_add_numeric_to_monetary(), qdata_add_short_to_dbval(), qdata_apply_interpolation_function_coercion(), qdata_divide_bigint_to_dbval(), qdata_divide_double_to_dbval(), qdata_divide_float_to_dbval(), qdata_divide_int_to_dbval(), qdata_divide_monetary_to_dbval(), qdata_divide_numeric_to_dbval(), qdata_divide_short_to_dbval(), qdata_interpolation_function_values(), qdata_is_divided_zero(), qdata_multiply_monetary(), qdata_multiply_monetary_to_dbval(), qdata_subtract_bigint_to_dbval(), qdata_subtract_double_to_dbval(), qdata_subtract_float_to_dbval(), qdata_subtract_int_to_dbval(), qdata_subtract_monetary_to_dbval(), qdata_subtract_numeric_to_dbval(), qdata_subtract_short_to_dbval(), qdata_unary_minus_dbval(), tp_value_cast_internal(), tp_value_coerce_strict(), valcnv_convert_data_to_string(), and value_as_boolean().
DB_CONST_C_NCHAR db_get_nchar (const DB_VALUE * value, int * length)
Referenced by convert_db_value_to_string(), db_string_convert_to(), db_string_truncate(), db_string_value(), dbval_to_net_buf(), mr_readval_nchar_internal(), and mr_readval_varnchar_internal().
DB_C_NUMERIC db_get_numeric (const DB_VALUE * value)
Referenced by coerce_char_to_dbvalue(), db_floor_dbval(), db_width_bucket_calculate_numeric(), mht_valhash(), mr_data_writeval_numeric(), mr_setmem_numeric(), mr_setval_numeric(), numeric_db_value_increase(), numeric_db_value_is_zero(), numeric_db_value_print(), pt_evaluate_db_value_expr(), and qdata_unary_minus_dbval().
DB_OBJECT* db_get_object (const DB_VALUE * value)
Referenced by apply_grants(), au_add_direct_groups(), au_add_member_method(), au_check_serial_authorization(), au_compute_groups(), au_drop_member_method(), au_drop_user(), au_dump_auth(), au_dump_to_file(), au_dump_user(), au_export_users(), au_find_user(), au_force_write_new_auth(), au_get_new_auth(), au_get_object(), au_perform_login(), au_print_auth(), au_print_grant_entry(), au_propagate_del_new_auth(), au_set_get_obj(), au_set_password_internal(), build_class_grant_list(), cache_validation(), call_method(), check_constraints(), check_set_object(), col_find(), col_insert(), col_permanent_oids(), col_put(), collect_class_grants(), construct_instance(), csql_db_value_as_string(), cursor_get_oid_from_vobj(), db_value_get(), db_value_to_value(), db_value_type_is_collection(), dbval_to_net_buf(), delete_list_by_oids(), db_value_printer::describe_data(), disk_to_attribute(), disk_to_class(), disk_to_methfile(), disk_to_method(), disk_to_resolution(), do_insert_template(), do_replace_names_for_insert_values_pre(), drop_stored_procedure(), emit_stored_procedure(), emit_stored_procedure_args(), ex_contains_object_reference(), execute_info_set(), fetch_result(), fetch_set_internal(), find_all_triggers(), find_grant_entry(), flush_temporary_OID(), get_grants(), get_object_set(), get_object_value(), get_user_trigger_objects(), insert_object_attr(), jsp_do_call_stored_procedure(), jsp_pack_object_argument(), make_vmops(), method_invoke_for_server(), method_receive_results_for_stand_alone(), mht_valhash(), mq_replace_virtual_oid_with_real_oid(), mr_cmpval_object(), mr_data_lengthval_object(), mr_data_readval_object(), mr_data_writeval_object(), mr_setmem_object(), mr_setval_object(), obj_assign_value(), obj_find_object_by_pkey(), obj_get_path(), object_to_trigger(), oid_attr_info_set(), process_value(), pt_associate_label_with_value(), pt_bind_parameter(), pt_check_method(), pt_dbval_to_value(), pt_eval_path_expr(), pt_free_label(), pt_get_object_data_type(), pt_is_reference_to_reusable_oid(), pt_make_regu_constant(), pt_print_node_value(), pt_resolve_object(), qmgr_execute_query(), quick_validate(), regu_make_constant_vid(), setobj_get_element(), setobj_sort(), setof_mop_to_setof_vobj(), tp_domain_resolve_value(), tp_domain_select(), tp_value_cast_internal(), tp_value_compare_with_error(), tr_dump_selective_triggers(), tr_status_as_string(), tr_update_user_cache(), trigger_table_find(), trigger_table_rename(), uci_delete_cs(), update_object_tuple(), ux_cursor_update(), ux_execute_array(), ux_execute_batch(), ux_get_generated_keys_client_insert(), ux_get_generated_keys_server_insert(), vid_compare_non_updatable_objects(), vid_decode_object(), vid_fetch_instance(), vid_flush_and_rehash_lbl(), vid_get_referenced_mop(), vid_getall_mops(), vid_vobj_to_object(), and ws_vmop().
OID* db_get_oid (const DB_VALUE * value)
Referenced by catcls_convert_class_oid_to_oid(), catcls_delete_subset(), catcls_expand_or_value_by_subset(), catcls_insert_instance(), catcls_update_instance(), catcls_update_subset(), css_user_access_status_start_scan(), db_value_to_value(), db_value_printer::describe_data(), eval_pred_comp1(), fetch_peek_arith(), heap_get_referenced_by(), mht_valhash(), mr_cmpval_object(), mr_cmpval_oid(), mr_data_writeval_object(), mr_data_writeval_oid(), mr_index_writeval_oid(), mr_setmem_oid(), mr_setval_object(), mr_setval_oid(), process_value(), qdata_get_class_of_function(), qexec_add_composite_lock(), qexec_execute_delete(), qexec_execute_obj_fetch(), qexec_execute_selupd_list(), qexec_execute_update(), qexec_upddel_add_unique_oid_to_ehid(), swizzle_value(), tp_domain_select(), tp_value_compare_with_error(), valcnv_convert_data_to_string(), and vid_oid_to_object().
DB_C_POINTER db_get_pointer (const DB_VALUE * value)
Referenced by dbt_put_internal(), db_value_printer::describe_data(), fprint_special_strings(), get_current_result(), mht_valhash(), mr_cmpval_ptr(), mr_data_lengthval_ptr(), mr_setmem_ptr(), mr_setval_ptr(), obt_convert_set_templates(), obt_desc_set(), obt_final_check_set(), obt_free_assignment(), obt_set(), pt_is_reference_to_reusable_oid(), pt_set_value_to_db(), tp_domain_select(), and tp_value_cast_internal().
DB_RESULTSET db_get_resultset (const DB_VALUE * value)
Referenced by dbval_to_net_buf(), mr_cmpval_resultset(), mr_data_writeval_resultset(), mr_setmem_resultset(), and mr_setval_resultset().
DB_COLLECTION* db_get_set (const DB_VALUE * value)
Referenced by api_collection_create_from_db_value(), assign_set_value(), au_force_write_new_auth(), au_get_set(), cache_validation(), catcls_delete_subset(), catcls_expand_or_value_by_subset(), catcls_get_or_value_from_attribute(), catcls_get_or_value_from_indexes(), catcls_get_property_set(), catcls_update_subset(), classobj_cache_constraint_list(), classobj_cache_constraints(), classobj_change_constraint_comment(), classobj_change_constraint_status(), classobj_check_function_constraint_info(), classobj_clear_attribute_value(), classobj_drop_foreign_key_ref(), classobj_find_prop_constraint(), classobj_make_class_constraints(), classobj_make_foreign_key_ref_list(), classobj_make_index_filter_pred_info(), classobj_put_foreign_key_ref(), classobj_put_index(), col_permanent_oids(), cursor_fetch_page_having_tuple(), cursor_fixup_set_vobjs(), db_value_get(), dbval_to_net_buf(), desc_value_print(), desc_value_special_fprint(), db_value_printer::describe_data(), disk_to_attribute(), disk_to_partition_info(), drop_stored_procedure(), emit_stored_procedure(), eval_pred(), eval_pred_alsm4(), eval_pred_comp2(), eval_set_list_cmp(), ex_contains_object_reference(), execute_info_set(), filter_local_constraints(), find_all_triggers(), flatten_properties(), get_grants(), get_property_list(), get_set_value(), get_user_trigger_objects(), heap_get_referenced_by(), jsp_do_call_stored_procedure(), jsp_get_value_size(), jsp_pack_set_argument(), mht_valhash(), mr_cmpval_sequence(), mr_cmpval_set(), mr_cmpval_vobj(), mr_data_lengthval_set(), mr_data_writeval_set(), mr_setmem_set(), mr_setval_set_internal(), obj_assign_value(), obj_find_object_by_cons_and_key(), obj_get_path(), obt_apply_assignment(), obt_final_check(), obt_free_assignment(), or_class_get_partition_info(), or_get_constraint_comment(), or_get_current_representation(), or_install_btids(), or_install_btids_class(), or_install_btids_foreign_key_ref(), partition_prune_hash(), partition_prune_list(), pr_clear_value(), process_value(), pt_bind_set_type(), pt_coerce_node_collation(), pt_difference_sets(), pt_evaluate_db_value_expr(), pt_evaluate_tree_internal(), pt_make_regu_constant(), pt_print_db_value(), pt_print_node_value(), pt_product_sets(), pt_seq_value_to_db(), pt_set_elements_to_value(), pt_set_table_to_db(), pt_set_value_to_db(), pt_union_sets(), qdata_add_sequence_to_dbval(), qdata_get_class_of_function(), qdata_multiply_sequence_to_dbval(), qdata_subtract_sequence_to_dbval(), qexec_add_composite_lock(), qexec_collection_has_null(), qexec_execute_obj_fetch(), qexec_upddel_add_unique_oid_to_ehid(), qproc_next_set_scan(), quick_validate(), register_user_trigger(), set_to_string(), setobj_convert_oids_to_objects(), setobj_get_element(), setobj_sort(), smt_drop_constraint_from_property(), tp_domain_resolve_value(), tp_domain_select(), tp_set_compare(), tp_value_cast_internal(), tr_dump_selective_triggers(), tr_status_as_string(), tr_update_user_cache(), trigger_table_add(), trigger_table_drop(), trigger_table_find(), trigger_table_rename(), unregister_user_trigger(), ux_get_generated_keys_client_insert(), valcnv_convert_data_to_string(), vid_build_non_upd_object(), vid_compare_non_updatable_objects(), vid_fetch_instance(), vid_oid_to_object(), vid_vobj_to_object(), and ws_rehash_vmop().
DB_C_SHORT db_get_short (const DB_VALUE * value)
Referenced by csql_db_value_as_string(), db_abs_dbval(), db_bit_count_dbval(), db_ceil_dbval(), db_conv(), db_date_add_sub_interval_expr(), db_exp_dbval(), db_floor_dbval(), db_format(), db_log_dbval(), db_mod_bigint(), db_mod_double(), db_mod_float(), db_mod_int(), db_mod_monetary(), db_mod_numeric(), db_mod_short(), db_round_dbval(), db_round_dbvalue_to_int(), db_sign_dbval(), db_sqrt_dbval(), db_string_chr(), db_string_elt(), db_string_sha_two(), db_string_space(), db_string_value(), db_timestamp(), db_trunc_dbval(), db_value_get(), dbval_to_net_buf(), db_value_printer::describe_data(), fetch_peek_dbval(), fprint_special_strings(), get_number_dbval_as_double(), get_number_dbval_as_long_double(), heap_object_upgrade_domain(), jsp_pack_short_argument(), mht_valhash(), mr_cmpval_short(), mr_data_writeval_short(), mr_index_writeval_short(), mr_setmem_short(), mr_setval_short(), number_to_char(), numeric_db_value_coerce_to_num(), pt_check_const_fold_op_w_args(), pt_dbval_to_value(), pt_evaluate_db_value_expr(), qdata_add_bigint_to_dbval(), qdata_add_date_to_dbval(), qdata_add_datetime_to_dbval(), qdata_add_double_to_dbval(), qdata_add_float_to_dbval(), qdata_add_int_to_dbval(), qdata_add_monetary_to_dbval(), qdata_add_short(), qdata_add_short_to_dbval(), qdata_add_time_to_dbval(), qdata_add_timestamptz_to_dbval(), qdata_add_utime_to_dbval(), qdata_apply_interpolation_function_coercion(), qdata_benchmark(), qdata_bit_and_dbval(), qdata_bit_not_dbval(), qdata_bit_or_dbval(), qdata_bit_shift_dbval(), qdata_bit_xor_dbval(), qdata_divide_bigint_to_dbval(), qdata_divide_double_to_dbval(), qdata_divide_float_to_dbval(), qdata_divide_int_to_dbval(), qdata_divide_monetary_to_dbval(), qdata_divide_short_to_dbval(), qdata_divmod_dbval(), qdata_elt(), qdata_increment_dbval(), qdata_interpolation_function_values(), qdata_is_divided_zero(), qdata_multiply_bigint_to_dbval(), qdata_multiply_double_to_dbval(), qdata_multiply_float_to_dbval(), qdata_multiply_int_to_dbval(), qdata_multiply_monetary_to_dbval(), qdata_multiply_short(), qdata_multiply_short_to_dbval(), qdata_subtract_bigint_to_dbval(), qdata_subtract_date_to_dbval(), qdata_subtract_datetime_to_dbval(), qdata_subtract_double_to_dbval(), qdata_subtract_float_to_dbval(), qdata_subtract_int_to_dbval(), qdata_subtract_monetary_to_dbval(), qdata_subtract_short_to_dbval(), qdata_subtract_time_to_dbval(), qdata_subtract_timestamptz_to_dbval(), qdata_subtract_utime_to_dbval(), qdata_unary_minus_dbval(), tp_value_cast_internal(), tp_value_coerce_strict(), valcnv_convert_data_to_string(), and value_as_boolean().
DB_CONST_C_CHAR db_get_string (const DB_VALUE * value)
Referenced by au_add_member_internal(), au_add_member_method(), au_add_user_method(), au_change_owner_method(), au_change_serial_owner_method(), au_change_sp_owner_method(), au_change_trigger_owner_method(), au_check_authorization_method(), au_drop_member(), au_drop_member_method(), au_drop_user(), au_drop_user_method(), au_dump_to_file(), au_dump_user(), au_export_users(), au_find_user_method(), au_get_new_auth(), au_get_owner_method(), au_get_user_name(), au_info_method(), au_login_method(), au_perform_login(), au_print_auth(), au_print_grant_entry(), au_set_password_encoded_method(), au_set_password_encoded_sha1_method(), au_set_password_method(), au_user_name(), bf2df_str_cmpval(), btree_index_start_scan(), catcls_get_db_collation(), catcls_get_or_value_from_attribute(), catcls_get_or_value_from_class(), catcls_get_or_value_from_indexes(), catcls_get_server_compat_info(), chksum_get_prev_checksum_results(), chksum_report_diff(), chksum_report_schema_diff(), chksum_report_summary(), classobj_btid_from_property_value(), classobj_cache_constraint_entry(), classobj_cache_constraint_list(), classobj_check_function_constraint_info(), classobj_drop_foreign_key_ref(), classobj_drop_prop(), classobj_get_prop(), classobj_make_class_constraints(), classobj_make_foreign_key_ref(), classobj_make_function_index_info(), classobj_make_index_filter_pred_info(), classobj_oid_from_property_value(), classobj_put_foreign_key_ref(), classobj_put_prop(), css_make_access_status_exist_user(), db_add_time(), db_ascii(), db_blob_from_file(), db_char_to_blob(), db_char_to_clob(), db_check_or_create_null_term_string(), db_clob_from_file(), db_compress_like_pattern(), db_conv(), db_crc32_dbval(), db_date_add_sub_interval_days(), db_date_add_sub_interval_expr(), db_date_format(), db_evaluate_json_valid(), db_find_string_in_in_set(), db_format(), db_from_tz(), db_get_datetime_from_dbvalue(), db_get_info_for_like_optimization(), db_get_like_optimization_bounds(), db_get_schema_def_dbval(), db_get_time_from_dbvalue(), db_hex(), db_json_search_func(), db_like_bound(), db_new_time(), db_str_to_date(), db_string_aes_decrypt(), db_string_aes_encrypt(), db_string_extract_dbval(), db_string_fix_string_size(), db_string_index_prefix(), db_string_insert_substring(), db_string_instr(), db_string_like(), db_string_limit_size_string(), db_string_md5(), db_string_position(), db_string_quote(), db_string_regexp_count(), db_string_regexp_instr(), db_string_regexp_like(), db_string_regexp_replace(), db_string_regexp_substr(), db_string_repeat(), db_string_rlike(), db_string_sha_one(), db_string_sha_two(), db_string_substring_index(), db_string_truncate(), db_string_unique_prefix(), db_time_format(), db_timestamp(), db_trunc_dbval(), db_tz_offset(), db_value_alloc_and_copy(), db_value_get(), db_value_to_json_doc(), db_value_to_json_key(), db_value_to_json_path(), db_value_to_json_value(), db_value_to_value(), db_value_type_is_collection(), db_value_printer::describe_data(), disk_to_attribute(), do_get_optimization_param(), do_get_partition_keycol(), do_get_stats(), do_is_partitioned_subclass(), do_set_optimization_param(), do_set_sys_params(), emit_class_owner(), emit_instance_attributes(), emit_stored_procedure(), emit_stored_procedure_args(), export_serial(), fetch_attribute(), fprint_special_strings(), get_attribute_number(), get_column_default_as_string(), get_savepoint_name_from_db_value(), get_string(), get_user_name(), heap_header_capacity_start_scan(), heap_object_upgrade_domain(), help_class_names(), is_str_find_all(), jsp_do_call_stored_procedure(), jsp_get_value_size(), jsp_pack_string_argument(), jsp_receive_error(), la_apply_statement_log(), lob_from_file(), log_active_log_header_start_scan(), log_archive_log_header_start_scan(), mht_get_hash_number(), mht_valhash(), mr_cmpval_bit(), mr_cmpval_bit2(), mr_cmpval_char(), mr_cmpval_nchar(), mr_cmpval_string(), mr_cmpval_varbit(), mr_cmpval_varbit2(), mr_cmpval_varnchar(), mr_data_lengthval_bit(), mr_data_lengthval_char(), mr_data_lengthval_nchar(), mr_lengthval_varbit_internal(), mr_lengthval_varnchar_internal(), mr_setmem_bit(), mr_setmem_char(), mr_setmem_nchar(), mr_setmem_string(), mr_setmem_varbit(), mr_setmem_varnchar(), mr_setval_char(), mr_setval_nchar(), mr_setval_string(), mr_setval_varbit(), mr_setval_varnchar(), mr_writeval_bit_internal(), mr_writeval_char_internal(), mr_writeval_nchar_internal(), mr_writeval_string_internal(), mr_writeval_varbit_internal(), mr_writeval_varnchar_internal(), obj_get_value(), object_to_trigger(), or_cl_get_prop_nocopy(), or_get_constraint_comment(), or_get_current_representation(), or_get_enumeration(), or_get_json_schema(), or_install_btids(), or_install_btids_class(), or_install_btids_constraint(), or_install_btids_filter_pred(), or_install_btids_foreign_key(), or_install_btids_foreign_key_ref(), or_install_btids_function_info(), partition_load_partition_predicate(), pr_do_db_value_string_compression(), pr_get_size_and_write_string_to_buffer(), pt_check_and_coerce_to_date(), pt_check_and_coerce_to_time(), pt_check_union_type_compatibility_of_values_query(), pt_dbval_to_value(), pt_evaluate_db_value_expr(), pt_get_default_expression_from_data_default_node(), pt_json_str_codeset_normalization(), qdata_concatenate_dbval(), qdata_get_cardinality(), qexec_execute_build_columns(), qo_find_like_rewrite_bound(), qo_rewrite_one_like_term(), qo_set_cost(), qstr_grow_string(), session_add_variable(), session_drop_variable(), session_dump_session(), session_dump_variable(), session_get_exec_stats_and_clear(), session_get_variable(), session_get_variable_no_copy(), setobj_get_element(), sm_delete_class_mop(), sm_partitioned_class_type(), sm_rename_class(), synccoll_check(), tp_atobi(), tp_atodate(), tp_atodatetimetz(), tp_atof(), tp_atonumeric(), tp_atotime(), tp_atotimestamptz(), tp_atoudatetime(), tp_atoutime(), tp_can_steal_string(), tp_check_value_size(), tp_value_cast_internal(), tr_get_class_name(), transfer_bit_string(), trigger_table_drop(), trigger_table_find(), tzc_compute_timezone_checksum(), uci_get_value_indirect(), valcnv_convert_bit_to_string(), valcnv_convert_data_to_string(), and ws_rehash_vmop().
int db_get_string_codeset (const DB_VALUE * value)
Referenced by csql_db_value_as_string(), date_to_char(), db_ascii(), db_char_string_coerce(), db_compress_like_pattern(), db_conv(), db_date_dbval(), db_date_format(), db_find_string_in_in_set(), db_format(), db_get_cs_coll_info(), db_get_date_format(), db_get_info_for_like_optimization(), db_get_like_optimization_bounds(), db_hex(), db_json_convert_to_utf8(), db_json_copy_and_convert_to_utf8(), db_str_to_date(), db_string_aes_decrypt(), db_string_aes_encrypt(), db_string_compare(), db_string_concatenate(), db_string_convert_to(), db_string_fix_string_size(), db_string_from_base64(), db_string_index_prefix(), db_string_insert_substring(), db_string_instr(), db_string_like(), db_string_limit_size_string(), db_string_lower(), db_string_md5(), db_string_pad(), db_string_position(), db_string_prefix_compare(), db_string_quote(), db_string_regexp_count(), db_string_regexp_instr(), db_string_regexp_like(), db_string_regexp_replace(), db_string_regexp_substr(), db_string_repeat(), db_string_replace(), db_string_reverse(), db_string_rlike(), db_string_sha_one(), db_string_sha_two(), db_string_substring(), db_string_substring_index(), db_string_to_base64(), db_string_translate(), db_string_trim(), db_string_truncate(), db_string_unique_prefix(), db_string_upper(), db_time_dbval(), db_time_format(), db_to_date(), db_to_datetime(), db_to_number(), db_to_time(), db_to_timestamp(), db_value_alloc_and_copy(), dbval_to_net_buf(), db_value_printer::describe_value(), fetch_peek_arith(), fetch_peek_dbval(), jsp_pack_string_argument(), mr_cmpval_char(), mr_cmpval_nchar(), mr_cmpval_string(), mr_cmpval_varnchar(), mr_data_lengthval_bit(), mr_data_lengthval_char(), mr_data_lengthval_nchar(), mr_lengthval_varnchar_internal(), mr_setval_char(), mr_setval_nchar(), mr_setval_string(), mr_setval_varnchar(), mr_writeval_bit_internal(), mr_writeval_char_internal(), mr_writeval_nchar_internal(), mr_writeval_varnchar_internal(), pt_bind_helper(), pt_dbval_to_value(), pt_evaluate_db_value_expr(), pt_evaluate_tree_internal(), pt_make_regu_hostvar(), qdata_concatenate_dbval(), qo_find_like_rewrite_bound(), qo_rewrite_one_like_term(), qstr_grow_string(), tp_atobi(), tp_atof(), tp_atonumeric(), tp_can_steal_string(), tp_domain_resolve_value(), tp_dtoa(), tp_ftoa(), tp_value_cast_internal(), tp_value_change_coll_and_codeset(), and tp_value_compare_with_error().
int db_get_string_collation (const DB_VALUE * value)
Referenced by btree_compare_key(), db_char_string_coerce(), db_compress_like_pattern(), db_date_dbval(), db_date_format(), db_find_string_in_in_set(), db_get_cs_coll_info(), db_get_like_optimization_bounds(), db_string_aes_decrypt(), db_string_aes_encrypt(), db_string_compare(), db_string_concatenate(), db_string_fix_string_size(), db_string_from_base64(), db_string_insert_substring(), db_string_instr(), db_string_like(), db_string_limit_size_string(), db_string_lower(), db_string_md5(), db_string_pad(), db_string_position(), db_string_prefix_compare(), db_string_quote(), db_string_regexp_count(), db_string_regexp_instr(), db_string_regexp_like(), db_string_regexp_replace(), db_string_regexp_substr(), db_string_repeat(), db_string_replace(), db_string_reverse(), db_string_rlike(), db_string_sha_one(), db_string_sha_two(), db_string_substring(), db_string_substring_index(), db_string_to_base64(), db_string_translate(), db_string_trim(), db_string_truncate(), db_string_unique_prefix(), db_string_upper(), db_time_dbval(), db_time_format(), db_value_alloc_and_copy(), fetch_peek_arith(), mht_get_hash_number(), mr_setval_char(), mr_setval_nchar(), mr_setval_string(), mr_setval_varnchar(), pt_bind_helper(), pt_dbval_to_value(), pt_evaluate_db_value_expr(), pt_evaluate_tree_internal(), pt_make_regu_hostvar(), qdata_concatenate_dbval(), qo_find_like_rewrite_bound(), qo_rewrite_one_like_term(), qstr_grow_string(), tp_can_steal_string(), tp_domain_resolve_value(), tp_dtoa(), tp_ftoa(), tp_value_cast_internal(), tp_value_change_coll_and_codeset(), and tp_value_compare_with_error().
int db_get_string_size (const DB_VALUE * value)
Referenced by bf2df_str_cmpval(), catcls_get_or_value_from_attribute(), classobj_make_function_index_info(), classobj_make_index_filter_pred_info(), csql_db_value_as_string(), date_to_char(), db_add_time(), db_ascii(), db_blob_from_file(), db_char_to_blob(), db_char_to_clob(), db_check_or_create_null_term_string(), db_clob_from_file(), db_compress_like_pattern(), db_conv(), db_crc32_dbval(), db_date_add_sub_interval_days(), db_date_add_sub_interval_expr(), db_date_format(), db_evaluate_json_valid(), db_find_string_in_in_set(), db_from_tz(), db_get_date_format(), db_get_datetime_from_dbvalue(), db_get_info_for_like_optimization(), db_get_like_optimization_bounds(), db_get_time_from_dbvalue(), db_hex(), db_new_time(), db_str_to_date(), db_string_bit_length(), db_string_compare(), db_string_elt(), db_string_extract_dbval(), db_string_fix_string_size(), db_string_from_base64(), db_string_insert_substring(), db_string_instr(), db_string_like(), db_string_limit_size_string(), db_string_lower(), db_string_pad(), db_string_position(), db_string_prefix_compare(), db_string_quote(), db_string_regexp_count(), db_string_regexp_instr(), db_string_regexp_like(), db_string_regexp_replace(), db_string_regexp_substr(), db_string_repeat(), db_string_replace(), db_string_reverse(), db_string_rlike(), db_string_sha_one(), db_string_substring_index(), db_string_to_base64(), db_string_translate(), db_string_trim(), db_string_truncate(), db_string_unique_prefix(), db_string_upper(), db_time_format(), db_timestamp(), db_to_date(), db_to_datetime(), db_to_number(), db_to_time(), db_to_timestamp(), db_tz_offset(), db_value_alloc_and_copy(), db_value_get(), db_value_to_json_doc(), db_value_to_json_key(), db_value_to_json_path(), db_value_to_json_value(), dbval_to_net_buf(), db_value_printer::describe_data(), fetch_peek_arith(), fprint_special_strings(), get_column_default_as_string(), heap_object_upgrade_domain(), is_str_find_all(), mht_get_hash_number(), mht_valhash(), mr_cmpval_bit(), mr_cmpval_bit2(), mr_cmpval_char(), mr_cmpval_nchar(), mr_cmpval_string(), mr_cmpval_varbit(), mr_cmpval_varbit2(), mr_cmpval_varnchar(), mr_data_lengthval_bit(), mr_data_lengthval_char(), mr_data_lengthval_nchar(), mr_lengthval_varnchar_internal(), mr_setmem_bit(), mr_setmem_char(), mr_setmem_nchar(), mr_setmem_string(), mr_setmem_varbit(), mr_setmem_varnchar(), mr_setval_bit(), mr_setval_char(), mr_setval_nchar(), mr_setval_string(), mr_setval_varbit(), mr_setval_varnchar(), mr_writeval_bit_internal(), mr_writeval_char_internal(), mr_writeval_nchar_internal(), mr_writeval_string_internal(), mr_writeval_varnchar_internal(), number_to_char(), or_get_enumeration(), or_get_json_schema(), or_install_btids_filter_pred(), or_install_btids_function_info(), partition_load_partition_predicate(), pr_do_db_value_string_compression(), pr_get_size_and_write_string_to_buffer(), pt_attr_check_default_cs_coll(), pt_check_and_coerce_to_date(), pt_check_and_coerce_to_time(), pt_check_const_fold_op_w_args(), pt_coerce_node_collation(), pt_dbval_to_value(), pt_evaluate_db_value_expr(), pt_json_str_codeset_normalization(), qdata_concatenate_dbval(), qdata_evaluate_sys_connect_by_path(), qdata_get_cardinality(), qo_find_like_rewrite_bound(), qo_rewrite_one_like_term(), qstr_grow_string(), session_add_variable(), synccoll_check(), tp_atobi(), tp_atodate(), tp_atodatetimetz(), tp_atof(), tp_atonumeric(), tp_atotime(), tp_atotimestamptz(), tp_atoudatetime(), tp_atoutime(), tp_can_steal_string(), tp_check_value_size(), tp_value_cast_internal(), transfer_bit_string(), uci_get_value_indirect(), and valcnv_convert_data_to_string().
DB_TIME* db_get_time (const DB_VALUE * value)
Referenced by csql_db_value_as_string(), date_to_char(), db_add_time(), db_get_time_from_dbvalue(), db_new_time(), db_string_extract_dbval(), db_string_value(), db_time_diff(), db_time_format(), db_timestamp(), db_value_get(), db_width_bucket(), dbval_to_net_buf(), db_value_printer::describe_data(), fprint_special_strings(), jsp_pack_time_argument(), mht_valhash(), mr_cmpval_time(), mr_data_writeval_time(), mr_index_writeval_time(), mr_setmem_time(), mr_setval_time(), pt_dbval_to_value(), pt_evaluate_db_value_expr(), qdata_add_bigint_to_time(), qdata_add_monetary(), qdata_interpolation_function_values(), qdata_subtract_bigint_to_dbval(), qdata_subtract_short_to_dbval(), qdata_subtract_time_to_dbval(), tp_value_cast_internal(), valcnv_convert_data_to_string(), value_as_boolean(), and value_to_db_value().
DB_TIMESTAMP* db_get_timestamp (const DB_VALUE * value)
Referenced by csql_db_value_as_string(), date_to_char(), db_add_time(), db_conv_tz(), db_date_add_sub_interval_days(), db_date_add_sub_interval_expr(), db_date_format(), db_get_datetime_from_dbvalue(), db_get_time_from_dbvalue(), db_string_extract_dbval(), db_string_value(), db_time_format(), db_trunc_dbval(), db_unix_timestamp(), db_value_get(), db_width_bucket(), dbval_to_net_buf(), db_value_printer::describe_data(), fprint_special_strings(), jsp_pack_timestamp_argument(), mht_valhash(), mr_cmpval_utime(), mr_data_writeval_utime(), mr_index_writeval_utime(), mr_setmem_utime(), mr_setval_timestampltz(), mr_setval_utime(), pt_dbval_to_value(), pt_evaluate_db_value_expr(), qdata_add_bigint_to_dbval(), qdata_add_bigint_to_timestamptz(), qdata_add_bigint_to_utime(), qdata_add_dbval(), qdata_add_int_to_dbval(), qdata_add_int_to_timestamptz(), qdata_add_int_to_utime(), qdata_add_short_to_dbval(), qdata_add_short_to_timestamptz(), qdata_add_short_to_utime(), qdata_interpolation_function_values(), qdata_is_zero_value_date(), qdata_strcat_dbval(), qdata_subtract_bigint_to_dbval(), qdata_subtract_datetime_to_dbval(), qdata_subtract_datetimetz_to_dbval(), qdata_subtract_timestampltz_to_dbval(), qdata_subtract_timestamptz_to_dbval(), qdata_subtract_utime_to_dbval(), round_date(), sqp_get_sys_timestamp(), tp_value_cast_internal(), tp_value_coerce_strict(), valcnv_convert_data_to_string(), and value_as_boolean().
DB_TIMESTAMPTZ* db_get_timestamptz (const DB_VALUE * value)
Referenced by csql_db_value_as_string(), date_to_char(), db_add_time(), db_conv_tz(), db_date_add_sub_interval_days(), db_date_add_sub_interval_expr(), db_date_format(), db_get_datetime_from_dbvalue(), db_get_time_from_dbvalue(), db_string_extract_dbval(), db_time_format(), db_trunc_dbval(), db_unix_timestamp(), db_width_bucket(), dbval_to_net_buf(), db_value_printer::describe_data(), fprint_special_strings(), mht_valhash(), mr_cmpval_timestamptz(), mr_data_writeval_timestamptz(), mr_index_writeval_timestamptz(), mr_setmem_timestamptz(), mr_setval_timestamptz(), pt_dbval_to_value(), pt_evaluate_db_value_expr(), qdata_add_bigint_to_dbval(), qdata_add_bigint_to_timestamptz(), qdata_add_dbval(), qdata_add_int_to_dbval(), qdata_add_int_to_timestamptz(), qdata_add_short_to_dbval(), qdata_add_short_to_timestamptz(), qdata_interpolation_function_values(), qdata_is_zero_value_date(), qdata_subtract_bigint_to_dbval(), qdata_subtract_datetime_to_dbval(), qdata_subtract_datetimetz_to_dbval(), qdata_subtract_timestamptz_to_dbval(), qdata_subtract_utime_to_dbval(), round_date(), tp_value_cast_internal(), tp_value_coerce_strict(), valcnv_convert_data_to_string(), and value_as_boolean().
int db_init_db_json_pointers (DB_JSON * val)
Definition at line 2042 of file db_macro.c.
References CHECK_1ARG_ERROR, db_json::document, NO_ERROR, NULL, and db_json::schema_raw.
Referenced by mr_getmem_json().
bool db_is_json_doc_type (DB_TYPE type)
Definition at line 5066 of file db_macro.c.
References DB_TYPE_CHAR, DB_TYPE_JSON, DB_TYPE_NCHAR, DB_TYPE_VARCHAR, and DB_TYPE_VARNCHAR.
Referenced by pt_is_json_doc_type().
bool db_is_json_value_type (DB_TYPE type)
Definition at line 5043 of file db_macro.c.
References DB_TYPE_BIGINT, DB_TYPE_CHAR, DB_TYPE_DOUBLE, DB_TYPE_ENUMERATION, DB_TYPE_INTEGER, DB_TYPE_JSON, DB_TYPE_NCHAR, DB_TYPE_NULL, DB_TYPE_NUMERIC, DB_TYPE_SHORT, DB_TYPE_VARCHAR, and DB_TYPE_VARNCHAR.
Referenced by pt_is_json_value_type().
int db_make_bigint (DB_VALUE * value, const DB_BIGINT num)
Referenced by coerce_binary_to_dbvalue(), coerce_numeric_to_dbvalue(), csect_start_scan(), db_abs_dbval(), db_ceil_dbval(), db_convert_json_into_scalar(), db_floor_dbval(), db_inet_aton(), db_mod_bigint(), db_mod_int(), db_mod_short(), db_round_dbval(), db_string_value(), db_trunc_dbval(), do_create_auto_increment_serial(), do_update_maxvalue_of_auto_increment_serial(), heap_capacity_next_scan(), heap_get_record_info(), heap_header_next_scan(), insert_ha_apply_info(), jsp_unpack_bigint_value(), la_insert_ha_apply_info(), la_update_ha_last_applied_info(), ldr_init_loader(), lob_length(), log_active_log_header_next_scan(), log_archive_log_header_next_scan(), mr_data_readval_bigint(), mr_getmem_bigint(), mr_index_readval_bigint(), mr_initval_bigint(), mr_setval_bigint(), netval_to_dbval(), numeric_db_value_coerce_from_num(), numeric_db_value_coerce_from_num_strict(), pgbuf_start_scan(), pt_db_value_initialize(), pt_evaluate_db_value_expr(), pt_get_query_limit_from_limit(), pt_get_query_limit_from_orderby_for(), qdata_add_bigint(), qdata_add_bigint_to_date(), qdata_add_bigint_to_dbval(), qdata_add_bigint_to_time(), qdata_add_bigint_to_timestamptz(), qdata_add_bigint_to_utime(), qdata_add_bigint_to_utime_asymmetry(), qdata_add_int_to_timestamptz(), qdata_add_int_to_utime(), qdata_add_short_to_timestamptz(), qdata_add_short_to_utime(), qdata_aggregate_value_to_accumulator(), qdata_bit_and_dbval(), qdata_bit_not_dbval(), qdata_bit_or_dbval(), qdata_bit_shift_dbval(), qdata_bit_xor_dbval(), qdata_divide_bigint(), qdata_divmod_dbval(), qdata_increment_dbval(), qdata_multiply_bigint(), qdata_subtract_bigint(), qdata_subtract_datetime(), qdata_subtract_datetime_to_dbval(), qdata_subtract_datetime_to_int_asymmetry(), qdata_subtract_datetimetz_to_dbval(), qdata_subtract_int_to_dbval(), qdata_subtract_short_to_dbval(), qdata_subtract_utime_to_bigint_asymmetry(), qdata_unary_minus_dbval(), qexec_execute_analytic(), qexec_gby_finalize_group(), qexec_groupby(), qexec_init_instnum_val(), qexec_ordby_put_next(), qexec_start_mainblock_iterations(), qexec_topn_tuples_to_list_id(), session_get_exec_stats_and_clear(), showstmt_array_end_scan(), cubload::to_db_bigint(), cubload::to_int_generic(), tp_value_cast_internal(), and tp_value_coerce_strict().
int db_make_bit (DB_VALUE * value, const int bit_length, DB_CONST_C_BIT bit_str, const int bit_str_bit_size)
Referenced by bfmt_value(), db_string_truncate(), db_value_alloc_and_copy(), db_value_domain_default(), ldr_init_loader(), mr_getmem_bit(), mr_readval_bit_internal(), mr_setval_bit(), netval_to_dbval(), pt_db_value_initialize(), qexec_execute_connect_by(), qexec_recalc_tuples_parent_pos_in_list(), qstr_make_typed_string(), and tp_value_cast_internal().
int db_make_char (DB_VALUE * value, const int char_length, DB_CONST_C_CHAR str, const int char_str_byte_size, const int codeset, const int collation_id)
Referenced by classobj_make_function_index_info_seq(), classobj_make_index_filter_pred_seq(), db_string_truncate(), db_string_value(), db_to_date(), db_to_datetime(), db_to_time(), db_to_timestamp(), db_value_alloc_and_copy(), do_send_plan_trace_to_session(), ldr_init_loader(), make_desired_string_db_value(), mr_getmem_char(), mr_readval_char_internal(), mr_setval_char(), numeric_db_value_coerce_from_num(), pt_db_value_initialize(), pt_evaluate_db_value_expr(), pt_node_to_partition_info(), qstr_make_typed_string(), tp_dtoa(), and tp_ftoa().
int db_make_collection (DB_VALUE * value, DB_C_SET * set)
Referenced by ldr_collection_db_collection(), and cubload::server_object_loader::process_collection_constant().
int db_make_date (DB_VALUE * value, const int month, const int day, const int year)
Referenced by coerce_date_to_dbvalue(), db_add_days_to_year(), db_add_months(), db_date_add_sub_interval_days(), db_date_add_sub_interval_expr(), db_get_date_from_days(), db_last_day(), db_str_to_date(), db_sys_date(), db_to_date(), ldr_init_loader(), netval_to_dbval(), numeric_db_value_coerce_from_num(), pt_evaluate_db_value_expr(), qdata_add_bigint_to_date(), qdata_add_int_to_date(), qdata_add_short_to_date(), qdata_subtract_bigint_to_dbval(), qdata_subtract_date_to_dbval(), qdata_subtract_int_to_dbval(), qexec_execute_insert(), round_date(), cubload::to_db_date(), tp_value_cast_internal(), and value_to_db_value().
int db_make_datetime (DB_VALUE * value, const DB_DATETIME * datetime)
Referenced by coerce_binary_to_dbvalue(), coerce_datetime_to_dbvalue(), coerce_timestamp_to_dbvalue(), css_make_access_status_exist_user(), css_user_access_status_start_scan(), db_add_time(), db_calculate_current_server_time(), db_date_add_sub_interval_days(), db_date_add_sub_interval_expr(), db_new_time(), db_str_to_date(), db_string_value(), db_sys_date_and_epoch_time(), db_sys_datetime(), db_timestamp(), db_to_datetime(), disk_volume_header_next_scan(), do_evaluate_default_expr(), fetch_peek_arith(), insert_ha_apply_info(), jsp_unpack_datetime_value(), la_insert_ha_apply_info(), la_update_ha_apply_info_log_record_time(), la_update_ha_last_applied_info(), ldr_init_loader(), log_active_log_header_next_scan(), log_archive_log_header_next_scan(), logtb_descriptors_start_scan(), mr_data_readval_datetime(), mr_getmem_datetime(), mr_index_readval_datetime(), mr_initval_datetime(), mr_setval_datetime(), netval_to_dbval(), numeric_db_value_coerce_from_num(), pt_db_value_initialize(), pt_evaluate_db_value_expr(), qdata_add_bigint_to_datetime(), qdata_add_datetimetz_to_dbval(), qdata_add_int_to_datetime(), qdata_add_short_to_datetime(), qdata_interpolation_function_values(), qdata_subtract_datetime_to_int(), qdata_subtract_datetimetz_to_dbval(), qexec_execute_insert(), showstmt_array_end_scan(), cubload::to_db_datetime(), tp_value_cast_internal(), and tp_value_coerce_strict().
int db_make_datetimeltz (DB_VALUE * value, const DB_DATETIME * datetime)
Referenced by db_add_time(), db_conv_tz(), db_date_add_sub_interval_days(), db_date_add_sub_interval_expr(), ldr_init_loader(), mr_data_readval_datetimeltz(), mr_getmem_datetimeltz(), mr_index_readval_datetimeltz(), mr_initval_datetimeltz(), mr_setval_datetimeltz(), pt_db_value_initialize(), pt_evaluate_db_value_expr(), qdata_add_bigint_to_dbval(), qdata_add_dbval(), qdata_add_int_to_dbval(), qdata_add_short_to_dbval(), qdata_interpolation_function_values(), qdata_strcat_dbval(), cubload::to_db_datetimeltz(), tp_value_cast_internal(), and tp_value_coerce_strict().
int db_make_datetimetz (DB_VALUE * value, const DB_DATETIMETZ * datetimetz)
Referenced by db_add_time(), db_conv_tz(), db_date_add_sub_interval_days(), db_date_add_sub_interval_expr(), db_from_tz(), db_str_to_date(), db_to_datetime(), ldr_init_loader(), mr_data_readval_datetimetz(), mr_getmem_datetimetz(), mr_index_readval_datetimetz(), mr_initval_datetimetz(), mr_setval_datetimetz(), netval_to_dbval(), pt_db_value_initialize(), pt_evaluate_db_value_expr(), qdata_add_datetimetz_to_dbval(), qdata_interpolation_function_values(), qdata_subtract_datetimetz_to_dbval(), qdata_subtract_dbval(), cubload::to_db_datetimetz(), tp_value_cast_internal(), and tp_value_coerce_strict().
int db_make_double (DB_VALUE * value, const DB_C_DOUBLE num)
Referenced by coerce_binary_to_dbvalue(), coerce_numeric_to_dbvalue(), csect_start_scan(), db_abs_dbval(), db_acos_dbval(), db_asin_dbval(), db_atan2_dbval(), db_atan_dbval(), db_ceil_dbval(), db_convert_json_into_scalar(), db_cos_dbval(), db_cot_dbval(), db_degrees_dbval(), db_drandom_dbval(), db_exp_dbval(), db_floor_dbval(), db_format(), db_log_dbval(), db_log_generic_dbval(), db_mod_bigint(), db_mod_double(), db_mod_float(), db_mod_int(), db_mod_numeric(), db_mod_short(), db_months_between(), db_power_dbval(), db_radians_dbval(), db_round_dbval(), db_sin_dbval(), db_sqrt_dbval(), db_string_value(), db_tan_dbval(), db_trunc_dbval(), fetch_peek_arith(), jsp_unpack_double_value(), ldr_init_loader(), mr_data_readval_double(), mr_getmem_double(), mr_index_readval_double(), mr_initval_double(), mr_setval_double(), netval_to_dbval(), numeric_db_value_coerce_from_num(), numeric_db_value_coerce_from_num_strict(), pgbuf_start_scan(), pt_db_value_initialize(), pt_evaluate_db_value_expr(), qdata_add_double(), qdata_apply_interpolation_function_coercion(), qdata_benchmark(), qdata_divide_double(), qdata_finalize_aggregate_list(), qdata_finalize_analytic_func(), qdata_interpolation_function_values(), qdata_multiply_double(), qdata_subtract_double(), qdata_unary_minus_dbval(), qexec_analytic_evaluate_cume_dist_percent_rank_function(), qexec_resolve_domains_for_aggregation(), cubload::to_db_double(), tp_value_cast_internal(), tp_value_coerce_strict(), tp_value_string_to_double(), and tr_set_priority().
int db_make_elo (DB_VALUE * value, DB_TYPE type, const DB_ELO * elo)
Referenced by caslob_to_dblob(), db_create_fbo(), getmem_elo_with_type(), heap_attrinfo_transform_to_disk_internal(), ldr_elo_ext_elem(), ldr_init_loader(), mr_initval_blob(), mr_initval_clob(), net_arg_get_lob_value(), obt_apply_assignments(), pt_db_value_initialize(), readval_elo_with_type(), setval_elo_with_type(), and cubload::to_db_elo_ext().
int db_make_enumeration (DB_VALUE * value, unsigned short index, DB_CONST_C_CHAR str, int size, unsigned char codeset, const int collation_id)
Referenced by catcls_get_or_value_from_attribute(), db_value_domain_default(), db_value_domain_max(), db_value_domain_min(), db_value_to_enumeration_value(), mr_initval_enumeration(), mr_setval_enumeration(), mr_setval_enumeration_internal(), pr_clear_value(), pr_complete_enum_value(), and tp_value_cast_internal().
int db_make_error (DB_VALUE * value, const int errcode)
Referenced by au_add_member_method(), au_add_user_method(), au_change_owner_method(), au_change_serial_owner_method(), au_change_sp_owner_method(), au_change_trigger_owner_method(), au_drop_member_method(), au_drop_user_method(), au_find_user_method(), au_get_owner_method(), au_login_method(), au_set_password_encoded_method(), au_set_password_encoded_sha1_method(), au_set_password_method(), mr_data_readval_error(), mr_getmem_error(), mr_initval_error(), mr_setval_error(), and qo_set_cost().
int db_make_float (DB_VALUE * value, const DB_C_FLOAT num)
Referenced by coerce_binary_to_dbvalue(), coerce_numeric_to_dbvalue(), db_abs_dbval(), db_ceil_dbval(), db_floor_dbval(), db_mod_bigint(), db_mod_float(), db_mod_int(), db_mod_short(), db_round_dbval(), db_string_value(), db_trunc_dbval(), define_trigger_classes(), do_get_xaction(), jsp_unpack_float_value(), ldr_init_loader(), mr_data_readval_float(), mr_getmem_float(), mr_index_readval_float(), mr_initval_float(), mr_setval_float(), netval_to_dbval(), numeric_db_value_coerce_from_num(), numeric_db_value_coerce_from_num_strict(), pt_db_value_initialize(), pt_evaluate_db_value_expr(), qdata_add_float(), qdata_divide_float(), qdata_multiply_float(), qdata_subtract_float(), qdata_unary_minus_dbval(), cubload::to_db_float(), tp_value_cast_internal(), tp_value_coerce_strict(), and trigger_to_object().
int db_make_int (DB_VALUE * value, const int num)
Referenced by add_grant_entry(), au_check_authorization_method(), au_drop_user(), au_grant(), au_revoke(), au_set_new_auth(), boot_add_charsets(), boot_add_collations(), boot_add_data_type(), boot_define_index_key(), boot_define_serial(), btree_get_next_key_info(), btree_get_next_node_info(), btree_scan_for_show_index_capacity(), btree_scan_for_show_index_header(), catcls_apply_component_type(), catcls_get_or_value_from_attribute(), catcls_get_or_value_from_indexes(), classobj_change_constraint_status(), classobj_make_foreign_key_info_seq(), classobj_make_foreign_key_ref_seq(), classobj_make_function_index_info_seq(), classobj_make_index_attr_prefix_seq(), classobj_make_index_filter_pred_seq(), classobj_put_index(), coerce_binary_to_dbvalue(), coerce_numeric_to_dbvalue(), csect_start_scan(), css_wp_core_job_scan_mapper(), db_abs_dbval(), db_bit_count_dbval(), db_ceil_dbval(), db_convert_json_into_scalar(), db_convert_time_to_sec(), db_crc32_dbval(), db_date_diff(), db_evaluate_json_contains(), db_evaluate_json_contains_path(), db_evaluate_json_depth(), db_evaluate_json_length(), db_evaluate_json_valid(), db_find_string_in_in_set(), db_floor_dbval(), db_from_unixtime(), db_get_date_dayofyear(), db_get_date_item(), db_get_date_quarter(), db_get_date_totaldays(), db_get_date_week(), db_get_date_weekday(), db_get_time_item(), db_local_transaction_id(), db_mod_int(), db_mod_short(), db_random_dbval(), db_round_dbval(), db_sign_dbval(), db_sleep(), db_string_bit_length(), db_string_char_length(), db_string_compare(), db_string_elt(), db_string_extract_dbval(), db_string_insert_substring(), db_string_instr(), db_string_position(), db_string_prefix_compare(), db_string_regexp_count(), db_string_regexp_instr(), db_string_regexp_like(), db_string_substring_index(), db_string_value(), db_sys_timezone(), db_trunc_dbval(), db_unix_timestamp(), db_width_bucket(), define_trigger_classes(), disk_volume_header_next_scan(), do_alter_serial(), do_change_auto_increment_serial(), do_create_auto_increment_serial(), do_create_partition(), do_create_serial(), do_create_serial_internal(), do_evaluate_default_expr(), do_get_optimization_param(), do_get_trigger(), do_get_xaction(), do_reset_auto_increment_serial(), do_update_maxvalue_of_auto_increment_serial(), cubxasl::json_table::column::evaluate_ordinality(), fetch_peek_arith(), get_attribute_number(), get_date_weekday(), get_grants(), get_hour_minute_or_second(), get_year_month_or_day(), heap_capacity_next_scan(), heap_get_page_info(), heap_get_record_info(), heap_header_next_scan(), insert_ha_apply_info(), jsp_add_stored_procedure(), jsp_add_stored_procedure_argument(), jsp_unpack_int_value(), la_insert_ha_apply_info(), la_update_ha_last_applied_info(), lang_db_put_charset(), ldr_init_loader(), log_active_log_header_next_scan(), log_archive_log_header_next_scan(), logtb_descriptors_start_scan(), make_cst_item_value(), meth_translate_spec(), mr_data_readval_int(), mr_getmem_int(), mr_index_readval_int(), mr_initval_int(), mr_setval_int(), netval_to_dbval(), numeric_db_value_coerce_from_num(), numeric_db_value_coerce_from_num_strict(), numeric_db_value_compare(), pgbuf_start_scan(), propagate_revoke(), pt_db_value_initialize(), pt_eval_expr_type(), pt_evaluate_db_value_expr(), pt_fold_const_expr(), pt_make_query_show_columns(), pt_make_query_show_index(), pt_to_regu_variable(), qdata_add_bigint_to_time(), qdata_add_int(), qdata_add_int_to_date(), qdata_add_int_to_dbval(), qdata_add_int_to_utime_asymmetry(), qdata_add_monetary(), qdata_aggregate_value_to_accumulator(), qdata_alloc_agg_hvalue(), qdata_divide_int(), qdata_divmod_dbval(), qdata_evaluate_aggregate_optimize(), qdata_evaluate_analytic_func(), qdata_finalize_aggregate_list(), qdata_finalize_analytic_func(), qdata_get_cardinality(), qdata_increment_dbval(), qdata_initialize_aggregate_list(), qdata_initialize_analytic_func(), qdata_load_agg_hentry_from_tuple(), qdata_multiply_int(), qdata_save_agg_hentry_to_list(), qdata_subtract_date_to_dbval(), qdata_subtract_int(), qdata_subtract_short_to_dbval(), qdata_subtract_time_to_dbval(), qdata_subtract_timestamptz_to_dbval(), qdata_subtract_utime_to_dbval(), qdata_subtract_utime_to_int_asymmetry(), qdata_unary_minus_dbval(), qexec_analytic_evaluate_ntile_function(), qexec_analytic_finalize_group(), qexec_check_limit_clause(), qexec_execute_build_columns(), qexec_execute_build_indexes(), qexec_execute_connect_by(), qexec_execute_insert(), qexec_get_orderbynum_upper_bound(), qexec_schema_get_type_desc(), qexec_set_pseudocolumns_val_pointers(), qexec_start_mainblock_iterations(), qo_convert_to_range(), qo_fold_is_and_not_null(), showstmt_array_end_scan(), spage_get_page_header_info(), spage_header_next_scan(), spage_slots_next_scan(), tf_attribute_default_expr_to_property(), cubload::to_db_int(), cubload::to_int_generic(), tp_value_cast_internal(), tp_value_coerce_strict(), tr_delete_schema_cache(), tr_set_status(), trigger_to_object(), vid_att_in_obj_id(), xserial_get_next_value_internal(), and xtran_get_local_transaction_id().
int db_make_json (DB_VALUE * value, JSON_DOC * json_document, bool need_clear)
Referenced by db_evaluate_json_get_all_paths(), db_evaluate_json_search(), db_json_val_from_str(), db_make_json_from_doc_store_and_release(), ldr_init_loader(), ldr_json_elem(), mr_data_cmpdisk_json(), mr_data_readval_json(), mr_getmem_json(), qdata_evaluate_aggregate_list(), cubload::to_db_json(), and tp_value_cast_internal().
int db_make_method_error (DB_VALUE * value, const int errcode, const char * errmsg)
int db_make_midxkey (DB_VALUE * value, DB_MIDXKEY * midxkey)
Referenced by btree_ils_adjust_range(), do_create_midxkey_for_constraint(), heap_attrinfo_generate_key(), heap_attrvalue_get_key(), mr_index_readval_midxkey(), mr_initval_midxkey(), mr_setval_midxkey(), pr_midxkey_add_prefix(), pr_midxkey_unique_prefix(), and scan_dbvals_to_midxkey().
int db_make_monetary (DB_VALUE * value, const DB_CURRENCY type, const double amount)
Referenced by coerce_numeric_to_dbvalue(), db_abs_dbval(), db_ceil_dbval(), db_floor_dbval(), db_mod_bigint(), db_mod_double(), db_mod_float(), db_mod_int(), db_mod_monetary(), db_mod_numeric(), db_mod_short(), db_round_dbval(), db_string_value(), db_trunc_dbval(), jsp_unpack_monetary_value(), ldr_monetary_elem(), mr_data_readval_money(), mr_getmem_money(), mr_index_readval_money(), mr_initval_money(), mr_setval_money(), netval_to_dbval(), numeric_db_value_coerce_from_num(), numeric_db_value_coerce_from_num_strict(), pt_db_value_initialize(), pt_evaluate_db_value_expr(), qdata_add_monetary(), qdata_add_numeric_to_monetary(), qdata_divide_monetary(), qdata_multiply_monetary(), qdata_subtract_monetary(), qdata_unary_minus_dbval(), cubload::to_db_monetary(), tp_value_cast_internal(), tp_value_coerce_strict(), and value_to_db_value().
int db_make_multiset (DB_VALUE * value, DB_C_SET * set)
Referenced by assign_set_value(), cursor_fixup_set_vobjs(), db_value_domain_default(), db_value_put(), get_set_value(), jsp_unpack_set_value(), mr_data_readval_set(), mr_getmem_multiset(), mr_initval_multiset(), mr_setval_set_internal(), pt_db_value_initialize(), pt_evaluate_tree_internal(), setof_mop_to_setof_vobj(), and tp_value_cast_internal().
int db_make_nchar (DB_VALUE * value, const int nchar_length, DB_CONST_C_NCHAR str, const int nchar_str_byte_size, const int codeset, const int collation_id)
Referenced by db_string_convert_to(), db_string_truncate(), db_string_value(), db_value_alloc_and_copy(), make_desired_string_db_value(), mr_getmem_nchar(), mr_readval_nchar_internal(), mr_setval_nchar(), netval_to_dbval(), numeric_db_value_coerce_from_num(), pt_db_value_initialize(), pt_evaluate_db_value_expr(), qstr_make_typed_string(), tp_dtoa(), and tp_ftoa().
int db_make_null (DB_VALUE * value)
Referenced by btree_insert_list::add_key(), adjust_partition_range(), adjust_partition_size(), assign_set_value(), au_add_member_method(), au_change_owner_method(), au_change_serial_owner_method(), au_change_sp_owner_method(), au_change_trigger_owner_method(), au_check_authorization_method(), au_delete_auth_of_dropping_table(), au_describe_root_method(), au_describe_user_method(), au_drop_member_method(), au_drop_user(), au_drop_user_method(), au_find_user_method(), au_get_new_auth(), au_get_owner_method(), au_get_user_name(), au_info_method(), au_login_method(), au_make_user(), au_set_password_encoded_method(), au_set_password_encoded_sha1_method(), au_set_password_internal(), au_set_password_method(), btree_build_nleafs(), btree_check_foreign_key(), btree_check_valid_record(), btree_clear_key_value(), btree_coerce_key(), btree_delete_internal(), btree_find_min_or_max_key(), btree_get_next_node_info(), btree_get_stats(), btree_ils_adjust_range(), btree_init_temp_key_value(), btree_key_insert_new_key(), btree_prepare_bts(), btree_range_opt_check_add_index_key(), btree_read_record_without_decompression(), btree_recompress_record(), btree_sort_get_next(), btree_top_n_items_binary_search(), btree_verify_leaf_node(), btree_verify_subtree(), call_method(), catcls_convert_class_oid_to_oid(), catcls_get_or_value_from_attribute(), catcls_get_or_value_from_domain(), catcls_get_or_value_from_indexes(), check_change_attribute(), check_default_on_update_clause(), check_set_object(), classobj_cache_constraint_list(), classobj_change_constraint_comment(), classobj_change_constraint_status(), classobj_check_function_constraint_info(), classobj_drop_foreign_key_ref(), classobj_find_prop_constraint(), classobj_make_attribute(), classobj_make_class_constraints(), classobj_make_index_filter_pred_info(), classobj_make_index_filter_pred_seq(), classobj_put_index(), cubscan::json_table::scanner::clear_node_columns(), cubxasl::json_table::column::clear_xasl(), coerce_date_to_dbvalue(), coerce_datetime_to_dbvalue(), coerce_time_to_dbvalue(), coerce_timestamp_to_dbvalue(), csect_start_scan(), csession_get_last_insert_id(), csession_get_variable(), csql_display_trace(), css_make_access_status_exist_user(), cur_tuple(), cursor_get_oid_from_vobj(), date_to_char(), db_abs_dbval(), db_accumulate_json_arrayagg(), db_accumulate_json_objectagg(), db_acos_dbval(), db_add_days_to_year(), db_add_months(), db_add_time(), db_alloc_query_result(), db_ascii(), db_asin_dbval(), db_atan2_dbval(), db_atan_dbval(), db_bigint_to_binary_string(), db_bit_count_dbval(), db_bit_to_blob(), db_blob_from_file(), db_blob_length(), db_blob_to_bit(), db_ceil_dbval(), db_char_to_blob(), db_char_to_clob(), db_clob_from_file(), db_clob_length(), db_clob_to_char(), db_col_drop_nulls(), db_compress_like_pattern(), db_conv(), db_conv_tz(), db_convert_json_into_scalar(), db_convert_sec_to_time(), db_convert_time_to_sec(), db_convert_to_time(), db_cos_dbval(), db_cot_dbval(), db_date_add_sub_interval_days(), db_date_add_sub_interval_expr(), db_date_dbval(), db_date_diff(), db_date_format(), db_datetime_to_timestamp(), db_degrees_dbval(), db_evaluate_json_array(), db_evaluate_json_array_append(), db_evaluate_json_array_insert(), db_evaluate_json_contains(), db_evaluate_json_contains_path(), db_evaluate_json_depth(), db_evaluate_json_extract(), db_evaluate_json_get_all_paths(), db_evaluate_json_insert(), db_evaluate_json_keys(), db_evaluate_json_length(), db_evaluate_json_merge_patch(), db_evaluate_json_merge_preserve(), db_evaluate_json_object(), db_evaluate_json_pretty(), db_evaluate_json_remove(), db_evaluate_json_replace(), db_evaluate_json_search(), db_evaluate_json_set(), db_evaluate_json_type_dbval(), db_evaluate_json_unquote(), db_evaluate_json_valid(), db_execute_and_keep_statement_local(), db_find_string_in_in_set(), db_floor_dbval(), db_format(), db_from_tz(), db_from_unixtime(), db_get_cs_coll_info(), db_get_date_dayofyear(), db_get_date_from_days(), db_get_date_item(), db_get_date_quarter(), db_get_date_totaldays(), db_get_date_week(), db_get_date_weekday(), db_get_like_optimization_bounds(), db_get_time_item(), db_guid(), db_hex(), db_inet_aton(), db_inet_ntoa(), db_json_copy_and_convert_to_utf8(), db_last_day(), db_least_or_greatest(), db_like_bound(), db_log_generic_dbval(), db_mod_bigint(), db_mod_double(), db_mod_float(), db_mod_int(), db_mod_monetary(), db_mod_numeric(), db_mod_short(), db_mod_string(), db_months_between(), db_new_time(), db_power_dbval(), db_radians_dbval(), db_round_dbval(), db_sin_dbval(), db_sleep(), db_sqrt_dbval(), db_str_to_date(), db_string_aes_decrypt(), db_string_aes_encrypt(), db_string_chr(), db_string_concatenate(), db_string_elt(), db_string_from_base64(), db_string_insert_substring(), db_string_instr(), db_string_lower(), db_string_md5(), db_string_position(), db_string_quote(), db_string_regexp_count(), db_string_regexp_instr(), db_string_regexp_like(), db_string_regexp_replace(), db_string_regexp_substr(), db_string_repeat(), db_string_replace(), db_string_reverse(), db_string_sha_one(), db_string_sha_two(), db_string_space(), db_string_substring(), db_string_substring_index(), db_string_to_base64(), db_string_unique_prefix(), db_string_upper(), db_tan_dbval(), db_time_dbval(), db_time_diff(), db_time_format(), db_timestamp(), db_to_date(), db_to_datetime(), db_to_number(), db_to_time(), db_to_timestamp(), db_trunc_dbval(), db_typeof_dbval(), db_tz_offset(), db_unix_timestamp(), db_value_alloc_and_copy(), db_value_list_add(), db_value_list_find(), db_value_list_finddel(), db_value_put(), db_value_to_enumeration_value(), db_value_to_json_key(), db_value_to_value(), db_width_bucket(), db_width_bucket_calculate_numeric(), dbmeth_print(), object_printer::describe_attribute(), object_printer::describe_class(), object_printer::describe_comment(), object_printer::describe_partition_parts(), do_add_attribute(), do_add_attribute_from_select_column(), do_alter_change_owner(), do_alter_one_clause_with_template(), do_alter_serial(), do_alter_trigger(), do_change_att_schema_only(), do_change_auto_increment_serial(), do_check_rows_for_null(), do_clear_insert_values(), do_create_auto_increment_serial(), do_create_serial(), do_create_serial_internal(), do_drop_serial(), do_evaluate(), do_evaluate_default_expr(), do_evaluate_insert_values(), do_find_unique_constraint_violations(), do_get_optimization_param(), do_get_partition_keycol(), do_get_partition_size(), do_get_stats(), do_get_trigger(), do_insert_template(), do_reset_auto_increment_serial(), do_rollback(), do_savepoint(), do_set_optimization_param(), do_set_session_variables(), do_set_sys_params(), do_set_trigger(), do_set_xaction(), do_update_auto_increment_serial_on_rename(), do_update_maxvalue_of_auto_increment_serial(), drop_stored_procedure(), emit_autoincrement_def(), emit_instance_attributes(), eval_key_filter(), cubxasl::json_table::column::evaluate(), export_serial(), fetch_call(), fetch_copy_dbval(), fetch_peek_arith(), fill_in_insert_default_function_arguments(), filter_local_constraints(), flatten_properties(), get_att_default_from_def(), get_attribute_number(), get_current_result(), get_date_weekday(), get_hour_minute_or_second(), get_object_value(), get_set_value(), get_string(), get_year_month_or_day(), getmem_elo_with_type(), heap_attrinfo_set(), heap_get_page_info(), heap_get_record_info(), heap_midxkey_get_value(), heap_object_upgrade_domain(), object_description::init(), cubxasl::analytic_list_node::init(), init_update_data(), insert_subquery_results(), jsp_alter_stored_procedure(), jsp_call_stored_procedure(), jsp_do_call_stored_procedure(), jsp_receive_error(), jsp_unpack_value(), la_get_current(), la_new_repl_item(), la_update_ha_last_applied_info(), ldr_elo_ext_db_elo(), ldr_json_db_json(), ldr_null_elem(), ldr_oid_elem(), ldr_xstr_elem(), lob_length(), lob_to_bit_char(), locator_add_or_remove_index_internal(), locator_check_btree_entries(), locator_check_foreign_key(), locator_check_primary_key_delete(), locator_check_primary_key_update(), locator_check_unique_btree_entries(), locator_update_index(), log_active_log_header_next_scan(), logtb_descriptors_start_scan(), make_cst_item_value(), make_desc_obj(), make_prepare_call_info(), merge_key_ranges(), method_invoke(), method_invoke_for_server(), method_invoke_from_stand_alone(), method_receive_results_for_stand_alone(), mht_valhash(), mq_evaluate_check_option(), mq_update_attribute(), mr_cmpval_json(), mr_data_readval_json(), mr_data_readval_null(), mr_getmem_json(), mr_getmem_null(), mr_setval_error(), mr_setval_object(), mr_setval_oid(), mr_setval_ptr(), mr_setval_set_internal(), netval_to_dbval(), number_to_char(), numeric_db_value_add(), numeric_db_value_compare(), numeric_db_value_div(), numeric_db_value_mul(), numeric_db_value_sub(), obj_copy(), obj_find_multi_attr(), obj_find_multi_desc(), obj_get_temp(), obj_get_value(), obj_set_att(), obt_assign(), obt_assign_obt(), oid_data_set(), online_index_builder(), or_get_current_representation(), or_get_enumeration(), or_get_set(), or_get_value(), or_install_btids_class(), or_unpack_mem_value(), page_key_boundary::page_key_boundary(), parser_create_parser(), partition_get_value_from_inarith(), partition_get_value_from_key(), partition_get_value_from_regu_var(), partition_prune(), partition_prune_hash(), partition_prune_range(), partition_range_min_max(), populate_auto_increment(), populate_defaults(), pr_clone_value(), pr_midxkey_compare_element(), pr_midxkey_get_element_internal(), prepare_call_info_dbval_clear(), pt_check_alter_partition(), pt_check_method(), pt_check_ordby_num_for_multi_range_opt(), pt_check_range_partition_strict_increasing(), pt_coerce_value_internal(), pt_create_iss_range(), pt_data_type_init_value(), pt_db_value_initialize(), pt_eval_path_expr(), pt_eval_value_path(), pt_evaluate_db_value_expr(), pt_evaluate_function(), pt_evaluate_tree_internal(), pt_exec_trigger_stmt(), pt_find_name_in_spec(), pt_fix_first_term_expr_for_iss(), pt_fix_first_term_func_index_for_iss(), pt_fold_const_expr(), pt_fold_const_function(), pt_get_query_limit_from_limit(), pt_get_query_limit_from_orderby_for(), pt_get_query_limit_value(), pt_get_select_list(), pt_init_insert_value(), pt_limit_to_numbering_expr(), pt_make_query_show_index(), pt_make_regu_constant(), pt_node_to_partition_info(), pt_rewrite_to_auto_param(), pt_seq_value_to_db(), pt_set_elements_to_value(), pt_set_table_to_db(), pt_set_value_to_db(), pt_to_aggregate_node(), pt_to_analytic_node(), qdata_add_dbval(), qdata_add_sequence_to_dbval(), qdata_benchmark(), qdata_bit_and_dbval(), qdata_bit_not_dbval(), qdata_bit_or_dbval(), qdata_bit_shift_dbval(), qdata_bit_xor_dbval(), qdata_concatenate_dbval(), qdata_convert_dbvals_to_set(), qdata_convert_table_to_set(), qdata_divide_dbval(), qdata_divmod_dbval(), qdata_elt(), qdata_evaluate_aggregate_hierarchy(), qdata_evaluate_analytic_func(), qdata_evaluate_qprior(), qdata_evaluate_sys_connect_by_path(), qdata_finalize_aggregate_list(), qdata_finalize_analytic_func(), qdata_get_cardinality(), qdata_get_class_of_function(), qdata_get_interpolation_function_result(), qdata_group_concat_first_value(), qdata_group_concat_value(), qdata_initialize_analytic_func(), qdata_list_dbs(), qdata_load_agg_hentry_from_tuple(), qdata_multiply_dbval(), qdata_strcat_dbval(), qdata_subtract_dbval(), qexec_analytic_evaluate_interpolation_function(), qexec_analytic_evaluate_ntile_function(), qexec_analytic_sort_key_header_load(), qexec_compare_valptr_with_tuple(), qexec_execute_build_columns(), qexec_execute_build_indexes(), qexec_execute_insert(), qexec_gby_finalize_group_val_list(), qexec_get_attr_default(), qexec_get_orderbynum_upper_bound(), qexec_get_tuple_column_value(), qexec_groupby_index(), qexec_initialize_analytic_function_state(), qexec_oid_of_duplicate_key_update(), qexec_remove_duplicates_for_replace(), qexec_schema_get_type_desc(), qexec_setup_topn_proc(), qfile_compare_tuple_values(), qfile_compare_with_interpolation_domain(), qfile_locate_tuple_next_value(), qmgr_execute_query(), qo_env_new(), qo_find_like_rewrite_bound(), qo_reduce_equality_terms(), qo_rewrite_one_like_term(), qstr_grow_string(), qstr_make_typed_string(), round_date(), scan_dbvals_to_midxkey(), scan_get_index_oidset(), scan_get_next_iss_value(), scan_init_iss(), scan_open_index_scan(), scan_start_scan(), serial_update_cur_val_of_serial(), session_define_variable(), session_get_trace_stats(), session_state_init(), page_key_boundary::set_value(), setobj_add_element(), setobj_get_element(), setobj_put_element(), setval_elo_with_type(), showstmt_alloc_tuple_in_context(), showstmt_array_end_scan(), sm_partitioned_class_type(), smt_add_constraint_to_property(), smt_drop_constraint_from_property(), ssession_get_session_variable(), tf_attribute_default_expr_to_property(), cubload::to_db_null(), cubload::to_db_varbit_from_hex_str(), tp_domain_select(), tp_dtoa(), tp_ftoa(), tp_set_compare(), tp_value_auto_cast(), tp_value_cast_internal(), tp_value_coerce_strict(), tp_value_compare_with_error(), tp_value_str_auto_cast_to_number(), cubxasl::json_table::column::trigger_on_empty(), cubxasl::json_table::column::trigger_on_error(), tz_full_timezones_start_scan(), uci_put_value(), ux_col_get(), ux_execute_array(), ux_execute_batch(), ux_get_last_insert_id(), value_to_db_value(), values_list_to_values_array(), vid_fetch_instance(), ws_rehash_vmop(), ws_vmop(), xbtree_load_index(), xlocator_check_fk_validity(), xlocator_remove_class_from_index(), xserial_get_next_value_internal(), and xsession_get_last_insert_id().
int db_make_numeric (DB_VALUE * value, const DB_C_NUMERIC num, const int precision, const int scale)
Referenced by bfmt_print(), boot_define_serial(), coerce_char_to_dbvalue(), db_abs_dbval(), db_ceil_dbval(), db_floor_dbval(), db_mod_bigint(), db_mod_int(), db_mod_numeric(), db_mod_short(), db_round_dbval(), db_trunc_dbval(), mr_data_readval_numeric(), mr_getmem_numeric(), mr_setval_numeric(), numeric_coerce_string_to_num(), numeric_common_prec_scale(), numeric_db_value_add(), numeric_db_value_coerce_to_num(), numeric_db_value_div(), numeric_db_value_mul(), numeric_db_value_sub(), numeric_prec_scale_when_overflow(), pt_evaluate_db_value_expr(), qdata_unary_minus_dbval(), and serial_get_nth_value().
int db_make_object (DB_VALUE * value, DB_C_OBJECT * obj)
Referenced by add_grant_entry(), au_add_member_internal(), au_add_user(), au_add_user_method(), au_change_serial_owner(), au_change_sp_owner(), au_change_trigger_owner(), au_compute_groups(), au_drop_member(), au_drop_user(), au_find_user_method(), au_get_owner_method(), au_is_dba_group_member(), au_make_user(), au_set_new_auth(), au_set_password_internal(), create_template_object(), cursor_copy_vobj_to_dbvalue(), cursor_fixup_vobjs(), db_execute_and_keep_statement_local(), db_value_put(), do_create_serial_internal(), do_create_trigger(), do_insert_template(), do_replace_names_for_insert_values_pre(), get_grants(), get_object_value(), object_description::init(), insert_object_attr(), insert_subquery_results(), jsp_add_stored_procedure(), jsp_alter_stored_procedure(), jsp_unpack_object_value(), ldr_class_oid_elem(), ldr_oid_elem(), make_vmops(), mq_replace_virtual_oid_with_real_oid(), mq_translate_value(), mr_data_readval_object(), mr_getmem_object(), mr_initval_object(), mr_setval_object(), netval_to_dbval(), obj_get_path(), obt_apply_assignments(), obt_convert_set_templates(), or_pack_mop(), pt_db_value_initialize(), pt_dbval_to_value(), pt_eval_path_expr(), pt_make_regu_constant(), register_user_trigger(), setobj_convert_oids_to_objects(), setof_mop_to_setof_vobj(), swizzle_value(), tp_domain_select(), tp_value_cast_internal(), trigger_table_add(), trigger_to_object(), uci_static(), unregister_user_trigger(), update_cache(), update_object_by_oid(), ux_get_generated_keys_client_insert(), vid_build_non_upd_object(), vid_build_virtual_mop(), vid_encode_object(), vid_fetch_instance(), vid_vobj_to_object(), and ws_vmop().
int db_make_oid (DB_VALUE * value, const OID * oid)
Referenced by btree_get_next_key_info(), catcls_convert_class_oid_to_oid(), catcls_get_or_value_from_class(), catcls_insert_instance(), catcls_insert_subset(), catcls_update_instance(), catcls_update_subset(), fetch_peek_dbval(), heap_get_page_info(), method_receive_results_for_stand_alone(), mr_data_readval_object(), mr_data_readval_oid(), mr_getmem_oid(), mr_index_readval_oid(), mr_initval_object(), mr_initval_oid(), mr_setval_object(), mr_setval_oid(), pt_check_access_status(), pt_fold_const_expr(), pt_make_vid(), pt_to_outlist(), qdata_get_class_of_function(), qexec_execute_insert(), qmgr_execute_query(), regu_make_constant_vid(), tp_value_cast_internal(), value_to_db_value(), vid_get_keys(), vid_make_vid(), and vid_make_vobj().
int db_make_pointer (DB_VALUE * value, DB_C_POINTER ptr)
Referenced by mr_getmem_ptr(), mr_initval_ptr(), mr_setval_ptr(), obt_free_assignment(), obt_set_obt(), and tp_value_cast_internal().
int db_make_resultset (DB_VALUE * value, const DB_RESULTSET handle)
Referenced by jsp_unpack_resultset(), mr_data_readval_resultset(), mr_getmem_resultset(), mr_initval_resultset(), and mr_setval_resultset().
int db_make_sequence (DB_VALUE * value, DB_C_SET * set)
Referenced by adjust_partition_range(), assign_set_value(), au_make_user(), catcls_get_object_set(), catcls_insert_subset(), catcls_update_subset(), classobj_change_constraint_comment(), classobj_change_constraint_status(), classobj_make_index_filter_pred_seq(), classobj_partition_info_size(), classobj_put_foreign_key_ref(), classobj_put_index(), classobj_put_seq_and_iterate(), cursor_fixup_set_vobjs(), db_value_domain_default(), db_value_put(), do_insert_template(), filter_local_constraints(), get_set_value(), insert_subquery_results(), jsp_add_stored_procedure(), jsp_unpack_set_value(), mr_data_readval_set(), mr_getmem_sequence(), mr_initval_sequence(), mr_setval_set_internal(), netval_to_dbval(), obj_find_primary_key(), obj_make_key_value(), partition_info_size(), partition_info_to_disk(), property_list_size(), pt_db_value_initialize(), pt_evaluate_tree_internal(), put_property_list(), register_user_trigger(), regu_make_constant_vid(), setof_mop_to_setof_vobj(), smt_drop_constraint_from_property(), tf_attribute_default_expr_to_property(), tp_value_cast_internal(), trigger_table_add(), vid_encode_object(), vid_make_vid(), vid_make_vobj(), and ws_rehash_vmop().
int db_make_set (DB_VALUE * value, DB_C_SET * set)
Referenced by assign_set_value(), au_compute_groups(), au_drop_user(), au_make_user(), cursor_fixup_set_vobjs(), db_value_domain_default(), db_value_put(), get_set_value(), jsp_unpack_set_value(), mr_data_readval_set(), mr_getmem_set(), mr_initval_set(), mr_setval_set_internal(), netval_to_dbval(), pt_check_union_type_compatibility_of_values_query(), pt_db_value_initialize(), pt_evaluate_tree_internal(), setof_mop_to_setof_vobj(), tf_attribute_default_expr_to_property(), and tp_value_cast_internal().
int db_make_short (DB_VALUE * value, const DB_C_SHORT num)
Referenced by coerce_binary_to_dbvalue(), coerce_numeric_to_dbvalue(), db_abs_dbval(), db_ascii(), db_ceil_dbval(), db_floor_dbval(), db_mod_short(), db_round_dbval(), db_string_value(), db_trunc_dbval(), cubxasl::json_table::column::evaluate_exists(), jsp_unpack_short_value(), ldr_init_loader(), mr_data_readval_short(), mr_getmem_short(), mr_index_readval_short(), mr_initval_short(), mr_setval_short(), netval_to_dbval(), numeric_db_value_coerce_from_num(), numeric_db_value_coerce_from_num_strict(), pt_db_value_initialize(), pt_evaluate_db_value_expr(), qdata_add_monetary(), qdata_add_short(), qdata_add_short_to_date(), qdata_add_short_to_dbval(), qdata_add_short_to_utime_asymmetry(), qdata_divide_short(), qdata_divmod_dbval(), qdata_increment_dbval(), qdata_multiply_short(), qdata_subtract_short(), qdata_subtract_utime_to_short_asymmetry(), qdata_unary_minus_dbval(), cubload::to_db_short(), tp_value_cast_internal(), and tp_value_coerce_strict().
int db_make_string (DB_VALUE * value, DB_CONST_C_CHAR str)
Referenced by au_compute_groups(), au_delete_auth_of_dropping_table(), au_find_user(), au_find_user_to_drop(), au_get_new_auth(), au_make_user(), au_set_new_auth(), au_set_password_internal(), au_set_user_comment(), btree_get_next_key_info(), btree_get_next_node_info(), catcls_get_or_value_from_attribute(), catcls_get_or_value_from_domain(), classobj_change_constraint_comment(), classobj_find_prop_constraint(), classobj_make_foreign_key_info_seq(), classobj_make_foreign_key_ref_seq(), classobj_make_function_index_info_seq(), classobj_make_index_filter_pred_seq(), classobj_put_foreign_key_ref(), classobj_put_index(), classobj_put_prop(), classobj_put_seq_with_name_and_iterate(), csect_start_scan(), db_conv(), db_convert_json_into_scalar(), db_date_add_sub_interval_days(), db_date_add_sub_interval_expr(), db_date_dbval(), db_date_format(), db_evaluate_json_pretty(), db_evaluate_json_search(), db_evaluate_json_unquote(), db_format(), db_get_cs_coll_info(), db_guid(), db_hex(), db_inet_ntoa(), db_json_search_func(), db_round_dbval(), db_time_dbval(), db_time_format(), db_trunc_dbval(), db_typeof_dbval(), dbmeth_class_name(), object_printer::describe_class(), object_printer::describe_comment(), disk_volume_header_next_scan(), do_alter_change_owner(), do_alter_serial(), do_alter_trigger(), do_create_serial_internal(), do_evaluate_default_expr(), do_get_optimization_param(), do_get_serial_obj_id(), do_send_plan_trace_to_session(), do_update_auto_increment_serial_on_rename(), domain_to_disk(), export_serial(), fetch_peek_arith(), jsp_add_stored_procedure(), jsp_add_stored_procedure_argument(), jsp_alter_stored_procedure(), jsp_find_stored_procedure(), jsp_unpack_string_value(), la_make_repl_item(), lang_db_put_charset(), ldr_str_db_generic(), ldr_str_elem(), log_active_log_header_next_scan(), logtb_descriptors_start_scan(), mq_set_non_updatable_oid(), mr_cmpval_json(), or_packed_json_schema_length(), or_put_json_schema(), pt_evaluate_db_value_expr(), pt_json_str_codeset_normalization(), put_timezone_checksum(), qdata_evaluate_sys_connect_by_path(), qdata_list_dbs(), qexec_execute_build_columns(), qexec_execute_build_indexes(), qexec_execute_connect_by(), qexec_execute_insert(), qexec_schema_get_type_desc(), qo_set_cost(), session_get_trace_stats(), showstmt_array_end_scan(), spage_header_next_scan(), spage_slots_next_scan(), tf_attribute_default_expr_to_property(), cubload::to_db_string(), tp_value_cast_internal(), tr_rename_trigger(), trigger_to_object(), tz_full_timezones_start_scan(), tz_timezones_start_scan(), and valcnv_convert_data_to_string().
int db_make_string_copy (DB_VALUE * value, DB_CONST_C_CHAR str)
Referenced by btree_scan_for_show_index_capacity(), btree_scan_for_show_index_header(), csect_start_scan(), css_make_access_status_exist_user(), css_user_access_status_start_scan(), db_get_schema_def_dbval(), disk_volume_header_next_scan(), heap_capacity_next_scan(), heap_header_next_scan(), log_active_log_header_next_scan(), log_archive_log_header_next_scan(), logtb_descriptors_start_scan(), pt_evaluate_db_value_expr(), showstmt_array_end_scan(), tp_value_cast_internal(), tr_set_comment(), trigger_table_add(), trigger_table_rename(), trigger_to_object(), and tz_full_timezones_start_scan().
int db_make_time (DB_VALUE * value, const int hour, const int minute, const int second)
Referenced by coerce_time_to_dbvalue(), db_add_time(), db_convert_sec_to_time(), db_convert_to_time(), db_new_time(), db_str_to_date(), db_sys_time(), db_time_diff(), db_to_time(), do_evaluate_default_expr(), ldr_init_loader(), netval_to_dbval(), numeric_db_value_coerce_from_num(), pt_evaluate_db_value_expr(), qdata_add_bigint_to_time(), qdata_add_monetary(), qdata_subtract_short_to_dbval(), qdata_subtract_time(), qexec_execute_insert(), cubload::to_db_time(), tp_value_cast_internal(), and value_to_db_value().
int db_make_timestamp (DB_VALUE * value, const DB_C_TIMESTAMP timeval)
Referenced by coerce_binary_to_dbvalue(), coerce_datetime_to_dbvalue(), coerce_timestamp_to_dbvalue(), db_calculate_current_server_time(), db_datetime_to_timestamp(), db_from_unixtime(), db_string_value(), db_sys_date_and_epoch_time(), db_sys_timestamp(), db_to_timestamp(), do_evaluate_default_expr(), fetch_peek_arith(), jsp_unpack_timestamp_value(), ldr_init_loader(), netval_to_dbval(), numeric_db_value_coerce_from_num(), pt_db_value_initialize(), pt_evaluate_db_value_expr(), qdata_add_bigint_to_timestamptz(), qdata_add_bigint_to_utime(), qdata_add_int_to_timestamptz(), qdata_add_int_to_utime(), qdata_add_short_to_timestamptz(), qdata_add_short_to_utime(), qdata_interpolation_function_values(), qdata_subtract_timestampltz_to_dbval(), qdata_subtract_utime(), qexec_execute_insert(), qmgr_dump_query_cache(), cubload::to_db_timestamp(), tp_value_cast_internal(), and tp_value_coerce_strict().
int db_make_timestampltz (DB_VALUE * value, const DB_C_TIMESTAMP ts_val)
Referenced by db_conv_tz(), ldr_init_loader(), mr_data_readval_timestampltz(), mr_getmem_timestampltz(), mr_index_readval_timestampltz(), mr_initval_timestampltz(), mr_setval_timestampltz(), pt_db_value_initialize(), pt_evaluate_db_value_expr(), qdata_add_bigint_to_dbval(), qdata_add_dbval(), qdata_add_int_to_dbval(), qdata_add_short_to_dbval(), qdata_interpolation_function_values(), qdata_strcat_dbval(), qdata_subtract_bigint_to_dbval(), qdata_subtract_timestampltz_to_dbval(), cubload::to_db_timestampltz(), tp_value_cast_internal(), and tp_value_coerce_strict().
int db_make_timestamptz (DB_VALUE * value, const DB_C_TIMESTAMPTZ * ts_tz_val)
Referenced by db_conv_tz(), db_to_timestamp(), ldr_init_loader(), mr_data_readval_timestamptz(), mr_getmem_timestamptz(), mr_index_readval_timestamptz(), mr_initval_timestamptz(), mr_setval_timestamptz(), netval_to_dbval(), pt_db_value_initialize(), pt_evaluate_db_value_expr(), qdata_add_bigint_to_dbval(), qdata_add_bigint_to_timestamptz(), qdata_add_dbval(), qdata_add_int_to_dbval(), qdata_add_int_to_timestamptz(), qdata_add_short_to_dbval(), qdata_add_short_to_timestamptz(), qdata_interpolation_function_values(), qdata_subtract_bigint_to_dbval(), qdata_subtract_timestamptz_to_dbval(), cubload::to_db_timestamptz(), tp_value_cast_internal(), and tp_value_coerce_strict().
int db_make_varbit (DB_VALUE * value, const int max_bit_length, DB_CONST_C_BIT bit_str, const int bit_str_bit_size)
Referenced by db_string_truncate(), db_value_alloc_and_copy(), ldr_bstr_elem(), ldr_xstr_elem(), lob_to_bit_char(), mr_getmem_varbit(), mr_initval_varbit(), mr_readval_varbit_internal(), mr_setval_varbit(), qstr_make_typed_string(), cubload::to_db_varbit_from_bin_str(), and cubload::to_db_varbit_from_hex_str().
int db_make_varchar (DB_VALUE * value, const int max_char_length, DB_CONST_C_CHAR str, const int char_str_byte_size, const int codeset, const int collation_id)
Referenced by au_set_new_auth(), boot_add_charsets(), boot_add_collations(), boot_add_data_type(), boot_define_dual(), catcls_find_oid_by_class_name(), coerce_binary_to_dbvalue(), date_to_char(), db_add_time(), db_bigint_to_binary_string(), db_compress_like_pattern(), db_evaluate_json_type_dbval(), db_string_chr(), db_string_reverse(), db_string_truncate(), db_string_value(), db_time_dbval(), db_tz_offset(), db_value_alloc_and_copy(), delete_all_slave_ha_apply_info(), heap_set_autoincrement_value(), insert_ha_apply_info(), la_delete_ha_apply_info(), la_get_ha_apply_info(), la_insert_ha_apply_info(), la_update_ha_apply_info_log_record_time(), la_update_ha_apply_info_start_time(), la_update_ha_last_applied_info(), ldr_init_loader(), lob_to_bit_char(), make_desired_string_db_value(), mr_getmem_string(), mr_initval_string(), mr_readval_string_internal(), mr_setval_string(), netval_to_dbval(), number_to_char(), numeric_db_value_coerce_from_num(), or_packed_enumeration_size(), or_put_enumeration(), pt_db_value_initialize(), pt_evaluate_tree_internal(), pt_make_query_show_index(), pt_node_to_partition_info(), qstr_make_typed_string(), tp_dtoa(), tp_enumeration_to_varchar(), tp_ftoa(), tp_value_cast_internal(), and valcnv_convert_value_to_string().
int db_make_varnchar (DB_VALUE * value, const int max_nchar_length, DB_CONST_C_NCHAR str, const int nchar_str_byte_size, const int codeset, const int collation_id)
Referenced by coerce_binary_to_dbvalue(), db_date_dbval(), db_string_convert_to(), db_string_reverse(), db_string_truncate(), db_string_value(), db_time_dbval(), db_value_alloc_and_copy(), ldr_nstr_elem(), make_desired_string_db_value(), mr_getmem_varnchar(), mr_initval_varnchar(), mr_readval_varnchar_internal(), mr_setval_varnchar(), numeric_db_value_coerce_from_num(), pt_db_value_initialize(), pt_evaluate_tree_internal(), put_string(), qstr_make_typed_string(), string_disk_size(), tp_dtoa(), and tp_ftoa().
void db_set_compressed_string (DB_VALUE * value, char * compressed_string, int compressed_size, bool compressed_need_clear)
Referenced by mr_readval_string_internal(), mr_readval_varnchar_internal(), pr_clear_compressed_string(), pr_clear_value(), and pr_do_db_value_string_compression().
int db_string_truncate (DB_VALUE * value, const int max_precision)
Definition at line 962 of file db_macro.c.
References ARG_FILE_LINE, assert, db_get_bit(), db_get_char(), db_get_nchar(), db_get_string(), db_get_string_codeset(), db_get_string_collation(), db_get_string_length(), db_get_string_size(), db_make_bit(), db_make_char(), db_make_nchar(), db_make_varbit(), db_make_varchar(), db_make_varnchar(), db_private_alloc, db_private_free, DB_TYPE_BIT, DB_TYPE_CHAR, DB_TYPE_NCHAR, DB_TYPE_NULL, DB_TYPE_STRING, DB_TYPE_VARBIT, DB_TYPE_VARNCHAR, DB_VALUE_TYPE, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), ER_UCI_INVALID_DATA_TYPE, ER_WARNING_SEVERITY, error(), intl_char_size(), valcnv_buffer::length, NO_ERROR, NULL, pr_clear_value(), pr_type::setval(), tp_Bit, tp_Char, tp_NChar, tp_String, tp_VarBit, and tp_VarNChar.
Referenced by catcls_get_or_value_from_attribute(), catcls_get_or_value_from_attrid(), catcls_get_or_value_from_class(), catcls_get_or_value_from_indexes(), catcls_get_or_value_from_method(), catcls_get_or_value_from_method_file(), catcls_get_or_value_from_method_signiture(), catcls_get_or_value_from_partition(), catcls_get_or_value_from_query_spec(), catcls_get_or_value_from_resolution(), heap_attrinfo_generate_key(), heap_attrvalue_get_key(), qdata_get_tuple_value_size_from_dbval(), and scan_regu_key_to_index_key().
void db_time_decode (DB_TIME * timeval, int * hourp, int * minutep, int * secondp)
Definition at line 432 of file db_date.c.
References decode_time().
Referenced by date_to_char(), db_add_time(), db_date_add_sub_interval_days(), db_date_add_sub_interval_expr(), db_date_format(), db_get_datetime_from_dbvalue(), db_get_time_from_dbvalue(), db_new_time(), db_print_data(), db_string_extract_dbval(), db_string_time(), db_string_timestamp(), db_time_format(), db_time_to_string(), db_timestamp(), db_timestamp_string(), db_value_to_value(), dbval_to_net_buf(), ehash_dump_bucket(), ehash_rv_init_dir_new_page_redo(), fmt_minute_value(), fmt_time_value(), jsp_pack_time_argument(), jsp_pack_timestamp_argument(), ko_time_string(), local_am_pm_string(), numeric_db_value_coerce_from_num(), pt_evaluate_db_value_expr(), qdata_add_bigint_to_time(), qdata_add_bigint_to_timestamptz(), qdata_add_bigint_to_utime(), qdata_add_int_to_timestamptz(), qdata_add_int_to_utime(), qdata_add_monetary(), qdata_add_short_to_timestamptz(), qdata_add_short_to_utime(), qdata_subtract_short_to_dbval(), qdata_subtract_time(), round_date(), tp_value_cast_internal(), tz_explain_tz_id(), tz_zone_info_to_str(), and us_time_string().
int db_time_encode (DB_TIME * timeval, int hour, int minute, int second)
Definition at line 370 of file db_date.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, er_set(), ER_TIME_CONVERSION, NO_ERROR, and NULL.
Referenced by coerce_time_to_dbvalue(), db_add_time(), db_datetime_string(), db_string_time(), db_string_timestamp(), db_to_timestamp(), fetch_peek_arith(), netval_to_dbval(), pt_evaluate_db_value_expr(), tp_value_cast_internal(), and tp_value_coerce_strict().
DB_DOMAIN* db_type_to_db_domain (DB_TYPE type)
Definition at line 1710 of file db_macro.c.
References assert, DB_TYPE_BIGINT, DB_TYPE_BIT, DB_TYPE_BLOB, DB_TYPE_CHAR, DB_TYPE_CLOB, DB_TYPE_DATE, DB_TYPE_DATETIME, DB_TYPE_DATETIMELTZ, DB_TYPE_DATETIMETZ, DB_TYPE_DB_VALUE, DB_TYPE_DOUBLE, DB_TYPE_ELO, DB_TYPE_ENUMERATION, DB_TYPE_ERROR, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_JSON, DB_TYPE_MIDXKEY, DB_TYPE_MONETARY, DB_TYPE_MULTISET, DB_TYPE_NCHAR, DB_TYPE_NULL, DB_TYPE_NUMERIC, DB_TYPE_OBJECT, DB_TYPE_OID, DB_TYPE_POINTER, DB_TYPE_RESULTSET, DB_TYPE_SEQUENCE, DB_TYPE_SET, DB_TYPE_SHORT, DB_TYPE_SUB, DB_TYPE_TABLE, DB_TYPE_TIME, DB_TYPE_TIMESTAMP, DB_TYPE_TIMESTAMPLTZ, DB_TYPE_TIMESTAMPTZ, DB_TYPE_VARBIT, DB_TYPE_VARCHAR, DB_TYPE_VARIABLE, DB_TYPE_VARNCHAR, DB_TYPE_VOBJ, NULL, and tp_domain_resolve_default().
Referenced by convert_db_value_to_string(), db_date_format(), db_time_format(), db_unix_timestamp(), db_value_alloc_and_copy(), dbval_to_net_buf(), get_column_default_as_string(), netval_to_dbval(), qexec_execute_build_columns(), session_dump_session(), session_dump_variable(), tp_infer_common_domain(), tp_value_cast_internal(), and value_to_db_value().
int db_value_alter_type (DB_VALUE * value, DB_TYPE type)
Definition at line 1225 of file db_macro.c.
References CHECK_1ARG_ERROR, db_value::domain, db_domain_info::general_info, NO_ERROR, and db_domain_info::general_info::type.
Referenced by mr_data_readval_vobj(), mr_setval_vobj(), pt_db_value_initialize(), qdata_convert_dbvals_to_set(), regu_make_constant_vid(), tp_value_cast_internal(), vid_make_vid(), and vid_make_vobj().
int db_value_clear (DB_VALUE * value)
Definition at line 1588 of file db_macro.c.
References error(), NO_ERROR, NULL, and pr_clear_value().
Referenced by au_add_member_internal(), au_drop_member(), au_get_new_auth(), au_get_user_name(), bind_value_print(), call_method(), check_change_attribute(), chksum_get_next_lower_bound(), chksum_get_prev_checksum_results(), chksum_report_diff(), chksum_report_schema_diff(), chksum_report_summary(), chksum_update_master_checksum(), cubload::server_object_loader::clear_db_values(), coerce_binary_to_dbvalue(), coerce_char_to_dbvalue(), coerce_date_to_dbvalue(), coerce_datetime_to_dbvalue(), coerce_time_to_dbvalue(), coerce_timestamp_to_dbvalue(), cur_tuple(), cursor_fetch_page_having_tuple(), cursor_fixup_vobjs(), db_close_session_local(), db_free_query_result(), db_gadget_bind(), db_gadget_destroy(), db_value_to_value(), dbval_to_net_buf(), delete_object_tuple(), db_value_printer::describe_set(), do_add_attribute(), do_add_attribute_from_select_column(), do_alter_one_clause_with_template(), do_change_att_schema_only(), do_change_auto_increment_serial(), do_check_rows_for_null(), do_clear_insert_values(), do_evaluate_default_expr(), do_evaluate_insert_values(), do_execute_select(), do_execute_session_statement(), do_reset_auto_increment_serial(), do_rollback(), do_savepoint(), do_select_internal(), do_set_trigger(), emit_class_owner(), emit_stored_procedure(), ex_contains_object_reference(), execute_info_set(), export_serial(), fetch_attribute(), fetch_result(), fetch_set_internal(), fn_collection(), fn_lob_read(), fn_lob_write(), free_db_values(), free_pointers(), get_att_default_from_def(), get_column_default_as_string(), get_desc_old(), get_string(), get_user_name(), help_class_names(), object_description::init(), insert_ha_apply_info(), insert_subquery_results(), jsp_call_stored_procedure(), jsp_receive_error(), jsp_receive_result(), la_delete_ha_apply_info(), la_get_ha_apply_info(), la_insert_ha_apply_info(), la_update_ha_apply_info_log_record_time(), la_update_ha_apply_info_start_time(), la_update_ha_last_applied_info(), ldr_bstr_db_varbit(), ldr_bstr_elem(), ldr_elo_ext_db_elo(), ldr_json_db_json(), ldr_xstr_db_varbit(), ldr_xstr_elem(), logtb_clear_tdes(), make_bind_value(), method_clear_scan_buffer(), method_invoke(), mr_readval_nchar_internal(), mr_readval_varnchar_internal(), netval_to_dbval(), object_to_trigger(), obt_apply_assignments(), oid_attr_info_set(), oid_data_set(), parser_free_node_resources(), parser_free_parser(), prepare_call_info_dbval_clear(), pt_evaluate_tree_internal(), pt_set_elements_to_value(), qmgr_execute_query(), qo_find_like_rewrite_bound(), qo_rewrite_one_like_term(), qproc_next_set_scan(), serialize_collection_as_string(), session_dump_session(), session_dump_variable(), set_has_objs(), set_to_string(), setof_mop_to_setof_vobj(), sm_att_default_value(), sm_delete_class_mop(), sm_rename_class(), sserial_get_current_value(), sserial_get_next_value(), cubload::to_db_varbit_from_bin_str(), cubload::to_db_varbit_from_hex_str(), transfer_bit_string(), uci_start(), update_object_tuple(), ux_col_get(), ux_cursor_update(), ux_execute(), ux_execute_all(), ux_execute_array(), ux_execute_batch(), ux_execute_call(), ux_get_generated_keys_client_insert(), ux_get_last_insert_id(), ux_lob_new(), ux_oid_put(), value_to_db_value(), vid_pack_vobj(), and ws_free_repl_flush_error().
int db_value_clear_array (DB_VALUE_ARRAY * value_array)
Definition at line 1633 of file db_macro.c.
References assert, error(), i, NO_ERROR, NULL, pr_clear_value(), db_value_array::size, and db_value_array::vals.
Referenced by db_unpack_prepare_info(), do_set_user_host_variables(), and values_list_to_values_array().
int db_value_clone (DB_VALUE * src, DB_VALUE * dest)
Definition at line 1564 of file db_macro.c.
References CHECK_CONNECT_ERROR, error(), NO_ERROR, NULL, and pr_clone_value().
Referenced by copy_node_in_tree_pre(), do_alter_serial(), do_create_auto_increment_serial(), do_create_serial(), do_evaluate_insert_values(), do_update_maxvalue_of_auto_increment_serial(), jsp_receive_result(), method_receive_results_for_stand_alone(), netval_to_dbval(), pt_dbval_to_value(), pt_eval_path_expr(), pt_evaluate_db_value_expr(), pt_evaluate_tree_internal(), pt_make_regu_constant(), qmgr_execute_query(), sm_att_default_value(), tp_value_cast_internal(), and uci_put_value().
int db_value_coerce (const DB_VALUE * src, DB_VALUE * dest, const DB_DOMAIN * desired_domain)
Definition at line 1779 of file db_macro.c.
References ARG_FILE_LINE, DOMAIN_COMPATIBLE, err, NO_ERROR, tp_domain_status_er_set(), and tp_value_cast_force().
Referenced by check_timeout_value(), convert_db_value_to_string(), db_to_char(), dbval_to_net_buf(), get_column_default_as_string(), netval_to_dbval(), pt_check_cume_dist_percent_rank_order_by(), qdata_aggregate_value_to_accumulator(), qdata_apply_interpolation_function_coercion(), qdata_calculate_aggregate_cume_dist_percent_rank(), qdata_evaluate_analytic_func(), qdata_finalize_aggregate_list(), qdata_interpolation_function_values(), qdata_update_agg_interpolation_func_value_and_domain(), qexec_execute_build_columns(), session_dump_session(), session_dump_variable(), smt_change_attribute_w_dflt_w_order(), and tp_value_cast_internal().
int db_value_compare (const DB_VALUE * value1, const DB_VALUE * value2)
Definition at line 1855 of file db_macro.c.
References tp_value_compare().
Referenced by adjust_partition_range(), db_value_list_find(), db_value_list_finddel(), do_create_partition(), partition_range_min_max(), pt_check_alter_partition(), pt_check_range_partition_strict_increasing(), pt_evaluate_db_value_expr(), pt_value_links_add(), and qo_reduce_comp_pair_terms().
DB_VALUE* db_value_copy (DB_VALUE * value)
Definition at line 1537 of file db_macro.c.
References CHECK_CONNECT_NULL, NULL, pr_clone_value(), and pr_make_ext_value().
Referenced by adjust_partition_range(), call_method(), catcls_get_or_value_from_indexes(), copy_node_in_tree_pre(), db_execute_oid(), db_get_db_value_query_result(), db_value_list_add(), do_evaluate(), do_execute_select(), do_execute_session_statement(), do_get_optimization_param(), do_get_stats(), do_get_trigger(), do_select_internal(), heap_attrinfo_set_uninitialized(), jsp_call_stored_procedure(), partition_range_min_max(), pt_copy_val_list(), qdata_evaluate_sys_connect_by_path(), and qexec_gby_init_group_dim().
DB_VALUE* db_value_create (void)
Definition at line 1517 of file db_macro.c.
References CHECK_CONNECT_NULL, and pr_make_ext_value().
Referenced by col_api_insert(), db_execute_and_keep_statement_local(), do_create_trigger(), do_get_optimization_param(), do_get_stats(), do_get_trigger(), do_get_xaction(), do_insert_template(), fill_collection(), insert_subquery_results(), pt_check_union_type_compatibility_of_values_query(), pt_make_regu_insert(), and vbt_lazy_init_db_value().
int db_value_domain_default (DB_VALUE * value, const DB_TYPE type, const int precision, const int scale, const int codeset, const int collation_id, DB_ENUMERATION * enumeration)
Definition at line 756 of file db_macro.c.
References ARG_FILE_LINE, assert, db_char::buf, db_data::ch, db_domain_info::char_info, db_char::codeset, db_domain_info::char_info::collation_id, db_char::compressed_buf, db_char::compressed_need_clear, db_char::compressed_size, db_value::data, db_datetime::date, db_data::date, db_datetimetz::datetime, db_data::datetime, db_data::datetimetz, DB_DATE_MIN, db_make_bit(), db_make_enumeration(), db_make_multiset(), db_make_sequence(), db_make_set(), db_seq_create(), db_set_create_basic(), db_set_create_multi(), DB_TIME_MIN, DB_TYPE_BIGINT, DB_TYPE_BIT, DB_TYPE_BLOB, DB_TYPE_CHAR, DB_TYPE_CLOB, DB_TYPE_DATE, DB_TYPE_DATETIME, DB_TYPE_DATETIMELTZ, DB_TYPE_DATETIMETZ, DB_TYPE_DOUBLE, DB_TYPE_ENUMERATION, DB_TYPE_ERROR, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_MIDXKEY, DB_TYPE_MONETARY, DB_TYPE_MULTISET, DB_TYPE_NCHAR, DB_TYPE_NULL, DB_TYPE_NUMERIC, DB_TYPE_OBJECT, DB_TYPE_OID, DB_TYPE_POINTER, DB_TYPE_SEQUENCE, DB_TYPE_SET, DB_TYPE_SHORT, DB_TYPE_SUB, DB_TYPE_TIME, DB_TYPE_TIMESTAMP, DB_TYPE_TIMESTAMPLTZ, DB_TYPE_TIMESTAMPTZ, DB_TYPE_VARBIT, DB_TYPE_VARCHAR, DB_TYPE_VARIABLE, DB_TYPE_VARNCHAR, DB_TYPE_VOBJ, DB_UTIME_MIN, db_value_domain_init(), db_value_domain_zero(), db_value::domain, db_data::elo, ELO_NULL, ER_ERROR_SEVERITY, er_set(), ER_UCI_INVALID_DATA_TYPE, error(), db_domain_info::general_info, db_char::info, db_char::is_max_string, db_domain_info::general_info::is_null, db_char::medium, MEDIUM_STRING, NO_ERROR, NULL, NULL_PAGEID, db_data::oid, db_identifier::pageid, db_char::size, db_identifier::slotid, db_char::style, db_datetime::time, db_data::time, db_timestamptz::timestamp, db_data::timestamptz, TP_IS_NUMERIC_TYPE, db_elo::type, tz_get_utc_tz_id(), db_timestamptz::tz_id, db_datetimetz::tz_id, db_data::utime, and db_identifier::volid.
Referenced by heap_object_upgrade_domain(), pt_make_query_show_columns(), pt_make_query_show_index(), pt_to_upd_del_query(), and valcnv_convert_data_to_string().
int db_value_domain_init (DB_VALUE * value, DB_TYPE type, const int precision, const int scale)
Definition at line 153 of file db_macro.c.
References ARG_FILE_LINE, db_data::ch, db_domain_info::char_info, CHECK_1ARG_ERROR, db_char::codeset, db_domain_info::char_info::collation_id, db_value::data, DB_DEFAULT_NUMERIC_PRECISION, DB_DEFAULT_NUMERIC_SCALE, DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, DB_MAX_BIT_PRECISION, DB_MAX_CHAR_PRECISION, DB_MAX_NCHAR_PRECISION, DB_MAX_NUMERIC_PRECISION, DB_MAX_VARBIT_PRECISION, DB_MAX_VARCHAR_PRECISION, DB_MAX_VARNCHAR_PRECISION, DB_TYPE_BIGINT, DB_TYPE_BIT, DB_TYPE_BLOB, DB_TYPE_CHAR, DB_TYPE_CLOB, DB_TYPE_DATE, DB_TYPE_DATETIME, DB_TYPE_DATETIMELTZ, DB_TYPE_DATETIMETZ, DB_TYPE_DOUBLE, DB_TYPE_ENUMERATION, DB_TYPE_ERROR, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_JSON, DB_TYPE_MIDXKEY, DB_TYPE_MONETARY, DB_TYPE_MULTISET, DB_TYPE_NCHAR, DB_TYPE_NULL, DB_TYPE_NUMERIC, DB_TYPE_OBJECT, DB_TYPE_OID, DB_TYPE_POINTER, DB_TYPE_SEQUENCE, DB_TYPE_SET, DB_TYPE_SHORT, DB_TYPE_SUB, DB_TYPE_TIME, DB_TYPE_TIMESTAMP, DB_TYPE_TIMESTAMPLTZ, DB_TYPE_TIMESTAMPTZ, DB_TYPE_VARBIT, DB_TYPE_VARCHAR, DB_TYPE_VARIABLE, DB_TYPE_VARNCHAR, DB_TYPE_VOBJ, db_json::document, db_value::domain, db_data::enumeration, ER_INVALID_PRECISION, er_set(), ER_UCI_INVALID_DATA_TYPE, ER_WARNING_SEVERITY, error(), db_domain_info::general_info, db_char::info, INTL_CODESET_RAW_BITS, IS_INVALID_PRECISION(), db_domain_info::general_info::is_null, db_data::json, LANG_SYS_CODESET, LANG_SYS_COLLATION, db_domain_info::char_info::length, db_value::need_clear, NO_ERROR, NULL, db_domain_info::numeric_info, db_domain_info::numeric_info::precision, db_domain_info::numeric_info::scale, db_json::schema_raw, db_enum_element::str_val, TP_FLOATING_PRECISION_VALUE, and db_domain_info::general_info::type.
Referenced by catcls_expand_or_value_by_def(), catcls_expand_or_value_by_repr(), catcls_get_or_value_from_domain(), coerce_binary_to_dbvalue(), coerce_char_to_dbvalue(), coerce_date_to_dbvalue(), coerce_datetime_to_dbvalue(), coerce_time_to_dbvalue(), coerce_timestamp_to_dbvalue(), csect_start_scan(), cursor_copy_vobj_to_dbvalue(), cursor_fixup_vobjs(), cursor_get_tuple_value_to_dbvalue(), db_add_months(), db_bit_string_coerce(), db_char_string_coerce(), db_datetime_to_timestamp(), db_string_bit_length(), db_string_char_length(), db_string_concatenate(), db_string_convert_to(), db_string_elt(), db_string_index_prefix(), db_string_make_empty_typed_string(), db_string_pad(), db_string_replace(), db_string_translate(), db_string_trim(), db_string_unique_prefix(), db_string_value(), db_sys_date(), db_sys_datetime(), db_sys_time(), db_sys_timestamp(), db_sys_timezone(), db_timestamp(), db_value_alloc_and_copy(), db_value_domain_default(), db_value_domain_init_default(), db_value_domain_max(), db_value_domain_min(), db_value_domain_zero(), db_value_get(), do_alter_serial(), do_cast_host_variables_to_expected_domain(), do_change_auto_increment_serial(), do_create_auto_increment_serial(), do_create_serial(), do_update_maxvalue_of_auto_increment_serial(), get_set_value(), heap_attrinfo_recache_attrepr(), heap_attrinfo_set(), heap_attrinfo_start(), heap_attrinfo_transform_to_disk_internal(), heap_attrvalue_read(), heap_eval_function_index(), ldr_act_class_attr(), ldr_bstr_elem(), ldr_int_elem(), ldr_numeric_elem(), ldr_xstr_elem(), method_receive_results_for_stand_alone(), mr_data_readval_error(), mr_data_readval_object(), mr_data_readval_oid(), mr_data_readval_ptr(), mr_data_readval_set(), mr_getmem_json(), mr_getmem_string(), mr_getmem_varbit(), mr_getmem_varnchar(), mr_index_readval_midxkey(), mr_index_readval_oid(), mr_initval_bigint(), mr_initval_bit(), mr_initval_blob(), mr_initval_clob(), mr_initval_double(), mr_initval_enumeration(), mr_initval_error(), mr_initval_int(), mr_initval_json(), mr_initval_midxkey(), mr_initval_multiset(), mr_initval_nchar(), mr_initval_null(), mr_initval_numeric(), mr_initval_object(), mr_initval_oid(), mr_initval_ptr(), mr_initval_resultset(), mr_initval_sequence(), mr_initval_set(), mr_initval_short(), mr_initval_sub(), mr_initval_vobj(), mr_readval_bit_internal(), mr_readval_char_internal(), mr_readval_nchar_internal(), mr_readval_string_internal(), mr_readval_varbit_internal(), mr_readval_varnchar_internal(), mr_setval_bigint(), mr_setval_bit(), mr_setval_date(), mr_setval_datetime(), mr_setval_datetimeltz(), mr_setval_datetimetz(), mr_setval_double(), mr_setval_enumeration(), mr_setval_float(), mr_setval_int(), mr_setval_json(), mr_setval_midxkey(), mr_setval_money(), mr_setval_nchar(), mr_setval_numeric(), mr_setval_object(), mr_setval_resultset(), mr_setval_set_internal(), mr_setval_short(), mr_setval_string(), mr_setval_time(), mr_setval_timestampltz(), mr_setval_timestamptz(), mr_setval_utime(), mr_setval_varbit(), mr_setval_varnchar(), netval_to_dbval(), numeric_coerce_string_to_num(), numeric_db_value_add(), numeric_db_value_compare(), numeric_db_value_div(), numeric_db_value_mul(), numeric_db_value_sub(), obt_apply_assignments(), or_get_set(), pgbuf_start_scan(), populate_auto_increment(), pr_clone_value(), pr_make_ext_value(), pr_make_value(), pt_db_value_initialize(), pt_evaluate_db_value_expr(), pt_make_regu_hostvar(), pt_to_regu_variable(), qdata_aggregate_accumulator_to_accumulator(), qdata_coerce_dbval_to_numeric(), qdata_coerce_numeric_to_double(), qdata_evaluate_analytic_func(), qdata_finalize_aggregate_list(), qdata_finalize_analytic_func(), qdata_get_single_tuple_from_list_id(), qdata_group_concat_first_value(), qdata_initialize_aggregate_list(), qdata_initialize_analytic_func(), qdata_set_valptr_list_unbound(), qexec_resolve_domains_for_aggregation(), qexec_resolve_domains_for_group_by(), qexec_set_pseudocolumns_val_pointers(), regu_dbval_type_init(), rs_init_domain(), setobj_convert_oids_to_objects(), setof_mop_to_setof_vobj(), swizzle_value(), cubload::to_db_generic_char(), cubload::to_db_numeric(), cubload::to_db_varbit_from_bin_str(), cubload::to_db_varbit_from_hex_str(), cubload::to_int_generic(), tp_init_value_domain(), tp_value_cast_internal(), tp_value_coerce_strict(), tp_value_compare_with_error(), transfer_bit_string(), uci_put_value(), value_to_db_value(), vid_build_non_upd_object(), vid_compare_non_updatable_objects(), vid_fetch_instance(), vid_make_vid(), vt_api_init_domain(), ws_rehash_vmop(), and xtran_get_local_transaction_id().
int db_value_domain_max (DB_VALUE * value, DB_TYPE type, const int precision, const int scale, const int codeset, const int collation_id, const DB_ENUMERATION * enumeration)
Definition at line 581 of file db_macro.c.
References db_monetary::amount, ARG_FILE_LINE, db_data::bigint, db_numeric::buf, db_char::buf, db_data::ch, db_domain_info::char_info, db_char::codeset, db_domain_info::char_info::collation_id, db_char::compressed_buf, db_char::compressed_need_clear, db_char::compressed_size, db_enumeration::count, db_numeric::d, db_data::d, db_value::data, db_datetime::date, db_data::date, db_datetimetz::datetime, db_data::datetime, db_data::datetimetz, DB_BIGINT_MAX, DB_CURRENCY_DEFAULT, DB_DATE_MAX, DB_ENUM_ELEMENTS_MAX, DB_INT16_MAX, DB_INT32_MAX, db_make_enumeration(), DB_MAX_NUMERIC_PRECISION, DB_TIME_MAX, DB_TYPE_BIGINT, DB_TYPE_BIT, DB_TYPE_BLOB, DB_TYPE_CHAR, DB_TYPE_CLOB, DB_TYPE_DATE, DB_TYPE_DATETIME, DB_TYPE_DATETIMELTZ, DB_TYPE_DATETIMETZ, DB_TYPE_DOUBLE, DB_TYPE_ENUMERATION, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_JSON, DB_TYPE_MONETARY, DB_TYPE_MULTISET, DB_TYPE_NCHAR, DB_TYPE_NULL, DB_TYPE_NUMERIC, DB_TYPE_OID, DB_TYPE_SEQUENCE, DB_TYPE_SET, DB_TYPE_SHORT, DB_TYPE_TIME, DB_TYPE_TIMESTAMP, DB_TYPE_TIMESTAMPLTZ, DB_TYPE_TIMESTAMPTZ, DB_TYPE_VARBIT, DB_TYPE_VARCHAR, DB_TYPE_VARNCHAR, DB_UTIME_MAX, db_value_domain_init(), db_value::domain, db_enumeration::elements, db_data::elo, elo_init_structure(), er_set(), ER_UCI_INVALID_DATA_TYPE, ER_WARNING_SEVERITY, error(), db_data::f, db_domain_info::general_info, db_data::i, db_char::info, INTL_CODESET_RAW_BITS, db_char::is_max_string, db_domain_info::general_info::is_null, db_char::medium, MEDIUM_STRING, db_data::money, db_value::need_clear, NO_ERROR, NULL, db_data::num, numeric_coerce_dec_str_to_num(), db_domain_info::numeric_info, db_data::oid, db_identifier::pageid, db_domain_info::numeric_info::precision, db_data::set, db_data::sh, db_char::size, db_identifier::slotid, db_enum_element::str_val, db_char::style, db_datetime::time, db_data::time, db_timestamptz::timestamp, db_data::timestamptz, db_monetary::type, tz_get_utc_tz_id(), db_timestamptz::tz_id, db_datetimetz::tz_id, db_data::utime, and db_identifier::volid.
Referenced by db_get_like_optimization_bounds(), and heap_object_upgrade_domain().
int db_value_domain_min (DB_VALUE * value, DB_TYPE type, const int precision, const int scale, const int codeset, const int collation_id, const DB_ENUMERATION * enumeration)
Definition at line 413 of file db_macro.c.
References db_monetary::amount, ARG_FILE_LINE, db_data::bigint, db_numeric::buf, db_char::buf, db_data::ch, db_domain_info::char_info, db_char::codeset, db_domain_info::char_info::collation_id, db_char::compressed_buf, db_char::compressed_need_clear, db_char::compressed_size, db_numeric::d, db_data::d, db_value::data, db_datetime::date, db_data::date, db_datetimetz::datetime, db_data::datetime, db_data::datetimetz, DB_BIGINT_MIN, DB_CURRENCY_DEFAULT, DB_DATE_MIN, DB_INT16_MIN, DB_INT32_MIN, db_make_enumeration(), DB_MAX_NUMERIC_PRECISION, DB_TIME_MIN, DB_TYPE_BIGINT, DB_TYPE_BIT, DB_TYPE_BLOB, DB_TYPE_CHAR, DB_TYPE_CLOB, DB_TYPE_DATE, DB_TYPE_DATETIME, DB_TYPE_DATETIMELTZ, DB_TYPE_DATETIMETZ, DB_TYPE_DOUBLE, DB_TYPE_ENUMERATION, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_JSON, DB_TYPE_MONETARY, DB_TYPE_MULTISET, DB_TYPE_NCHAR, DB_TYPE_NULL, DB_TYPE_NUMERIC, DB_TYPE_OID, DB_TYPE_SEQUENCE, DB_TYPE_SET, DB_TYPE_SHORT, DB_TYPE_TIME, DB_TYPE_TIMESTAMP, DB_TYPE_TIMESTAMPLTZ, DB_TYPE_TIMESTAMPTZ, DB_TYPE_VARBIT, DB_TYPE_VARCHAR, DB_TYPE_VARNCHAR, DB_UTIME_MIN, db_value_domain_init(), db_value::domain, db_data::elo, elo_init_structure(), er_set(), ER_UCI_INVALID_DATA_TYPE, ER_WARNING_SEVERITY, error(), db_data::f, db_domain_info::general_info, db_data::i, db_char::info, INTL_CODESET_RAW_BITS, db_char::is_max_string, db_domain_info::general_info::is_null, db_char::medium, MEDIUM_STRING, db_data::money, db_value::need_clear, NO_ERROR, NULL, NULL_PAGEID, db_data::num, numeric_coerce_dec_str_to_num(), db_domain_info::numeric_info, db_data::oid, db_identifier::pageid, db_domain_info::numeric_info::precision, db_data::set, db_data::sh, db_char::size, db_identifier::slotid, db_char::style, db_datetime::time, db_data::time, db_timestamptz::timestamp, db_data::timestamptz, db_monetary::type, tz_get_utc_tz_id(), db_timestamptz::tz_id, db_datetimetz::tz_id, db_data::utime, and db_identifier::volid.
Referenced by db_get_like_optimization_bounds(), and heap_object_upgrade_domain().
DB_TYPE db_value_domain_type (const DB_VALUE * value)
Referenced by db_evaluate_json_valid(), db_value_to_json_doc(), db_value_to_json_path(), and qdata_benchmark().
int db_value_domain_zero (DB_VALUE * value, const DB_TYPE type, const int precision, const int scale)
Definition at line 903 of file db_macro.c.
References db_monetary::amount, ARG_FILE_LINE, assert, db_data::bigint, db_numeric::buf, db_numeric::d, db_data::d, db_value::data, DB_CURRENCY_DEFAULT, DB_NUMBER_ZERO, DB_TYPE_BIGINT, DB_TYPE_DOUBLE, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_MONETARY, DB_TYPE_NUMERIC, DB_TYPE_SHORT, db_value_domain_init(), db_value::domain, er_set(), ER_UCI_INVALID_DATA_TYPE, ER_WARNING_SEVERITY, error(), db_data::f, db_domain_info::general_info, db_data::i, db_domain_info::general_info::is_null, db_data::money, NO_ERROR, db_data::num, numeric_coerce_dec_str_to_num(), db_data::sh, TP_IS_NUMERIC_TYPE, and db_monetary::type.
Referenced by db_value_domain_default().
int db_value_equal (const DB_VALUE * value1, const DB_VALUE * value2)
Definition at line 1803 of file db_macro.c.
References CHECK_CONNECT_ZERO, and tp_value_equal().
void db_value_fprint (FILE * fp, const DB_VALUE * value)
Definition at line 1681 of file db_macro.c.
References CHECK_CONNECT_VOID, db_fprint_value(), and NULL.
int db_value_free (DB_VALUE * value)
Definition at line 1610 of file db_macro.c.
References error(), NO_ERROR, NULL, and pr_free_ext_value().
Referenced by adjust_partition_range(), col_api_delete(), col_api_insert(), col_dtorf(), db_execute_and_keep_statement_local(), db_free_query_result(), fill_collection(), pt_associate_label_with_value(), pt_evaluate_tree_internal(), pt_exec_trigger_stmt(), pt_free_label(), qexec_gby_clear_group_dim(), vbt_dtor(), vbt_lazy_init_db_value(), and vbt_resetf_map().
int db_value_get (DB_VALUE * value, const DB_TYPE_C type, void * buf, const int buflen, int * transferlen, int * outputlen)
Definition at line 2077 of file db_macro.c.
References db_monetary::amount, ARG_FILE_LINE, DATE_BUF_SIZE, DATETIME_BUF_SIZE, db_date_to_string(), db_datetime_to_string(), DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_get_bigint(), db_get_date(), db_get_datetime(), db_get_double(), db_get_float(), db_get_int(), db_get_monetary(), db_get_object(), db_get_set(), db_get_short(), db_get_string(), db_get_string_length(), db_get_string_size(), db_get_time(), db_get_timestamp(), DB_IS_NULL, db_time_to_string(), db_timestamp_to_string(), DB_TYPE_BIGINT, DB_TYPE_BIT, DB_TYPE_BLOB, DB_TYPE_C_BIGINT, DB_TYPE_C_BIT, DB_TYPE_C_CHAR, DB_TYPE_C_DATE, DB_TYPE_C_DATETIME, DB_TYPE_C_DOUBLE, DB_TYPE_C_FLOAT, DB_TYPE_C_INT, DB_TYPE_C_LONG, DB_TYPE_C_MONETARY, DB_TYPE_C_NCHAR, DB_TYPE_C_OBJECT, DB_TYPE_C_SET, DB_TYPE_C_SHORT, DB_TYPE_C_TIME, DB_TYPE_C_TIMESTAMP, DB_TYPE_C_VARBIT, DB_TYPE_C_VARCHAR, DB_TYPE_C_VARNCHAR, DB_TYPE_CHAR, DB_TYPE_CLOB, DB_TYPE_DATE, DB_TYPE_DATETIME, DB_TYPE_DB_VALUE, DB_TYPE_DOUBLE, DB_TYPE_ENUMERATION, DB_TYPE_ERROR, DB_TYPE_FIRST, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_MIDXKEY, DB_TYPE_MONETARY, DB_TYPE_MULTISET, DB_TYPE_NCHAR, DB_TYPE_NUMERIC, DB_TYPE_OBJECT, DB_TYPE_OID, DB_TYPE_POINTER, DB_TYPE_RESULTSET, DB_TYPE_SEQUENCE, DB_TYPE_SET, DB_TYPE_SMALLINT, DB_TYPE_SUB, DB_TYPE_TABLE, DB_TYPE_TIME, DB_TYPE_TIMESTAMP, DB_TYPE_VARBIT, DB_TYPE_VARCHAR, DB_TYPE_VARIABLE, DB_TYPE_VARNCHAR, DB_TYPE_VOBJ, db_value_domain_init(), db_value_get(), DB_VALUE_TYPE, ER_DB_UNSUPPORTED_CONVERSION, ER_ERROR_SEVERITY, ER_OBJ_INVALID_ARGUMENTS, er_set(), ER_UCI_NULL_IND_NEEDED, i, LANG_SYS_CODESET, NO_ERROR, NULL, NUM_BUF_SIZE, numeric_db_value_coerce_from_num(), pr_clear_value(), qstr_bit_to_hex_coerce(), strlen, TIME_BUF_SIZE, TIMESTAMP_BUF_SIZE, transfer_bit_string(), and transfer_string().
Referenced by db_value_get(), db_value_to_value(), and uci_get_value().
double db_value_get_monetary_amount_as_double (const DB_VALUE * value)
Definition at line 1505 of file db_macro.c.
References db_monetary::amount, CHECK_1ARG_ZERO, db_value::data, and db_data::money.
Referenced by db_conv(), db_format(), db_timestamp(), dbval_to_net_buf(), and numeric_db_value_coerce_to_num().
DB_CURRENCY db_value_get_monetary_currency (const DB_VALUE * value)
Definition at line 1492 of file db_macro.c.
References CHECK_1ARG_ZERO_WITH_TYPE, db_value::data, db_data::money, and db_monetary::type.
Referenced by db_string_value(), pt_bind_helper(), and pt_dbval_to_value().
bool db_value_is_null (const DB_VALUE * value)
Referenced by catcls_get_or_value_from_attribute(), check_missing_non_null_attrs(), db_value_to_json_doc(), db_value_to_json_value(), dbval_to_net_buf(), disk_to_attribute(), eval_item_card_set(), eval_key_filter(), eval_pred(), eval_pred_alsm4(), eval_pred_alsm5(), eval_pred_comp0(), eval_pred_comp1(), eval_pred_comp2(), eval_pred_comp3(), eval_pred_like6(), eval_pred_rlike7(), eval_sub_multi_set_to_sort_list(), cubxasl::json_table::column::evaluate_exists(), cubxasl::json_table::column::evaluate_extract(), get_att_default_from_def(), get_column_default_as_string(), heap_attrinfo_delete_lob(), heap_attrinfo_set_uninitialized(), heap_attrinfo_transform_to_disk_internal(), heap_get_referenced_by(), heap_midxkey_key_generate(), heap_midxkey_key_get(), locator_check_btree_entries(), locator_check_unique_btree_entries(), locator_update_index(), mq_evaluate_check_option(), obt_apply_assignments(), oid_attr_info_set(), cubscan::json_table::scanner::open(), or_get_current_representation(), partition_find_partition_for_record(), qdata_benchmark(), qexec_execute_delete(), qexec_execute_update(), qexec_get_index_pseudocolumn_value_from_tuple(), setobj_filter(), stx_build_aggregate_type(), stx_build_update_assignment(), stx_unpack_regu_variable_value(), and xbtree_find_unique().
int db_value_precision (const DB_VALUE * value)
Referenced by cache_validation(), col_api_get_elem_domain_info(), db_string_lower(), db_string_upper(), db_value_alloc_and_copy(), do_cast_host_variables_to_expected_domain(), mr_data_lengthval_bit(), mr_data_lengthval_char(), mr_data_lengthval_nchar(), mr_data_lengthval_numeric(), mr_data_writeval_numeric(), mr_setmem_bit(), mr_setmem_nchar(), mr_setmem_numeric(), mr_setmem_varbit(), mr_setmem_varnchar(), mr_setval_bit(), mr_setval_midxkey(), mr_setval_nchar(), mr_setval_numeric(), mr_setval_string(), mr_setval_varbit(), mr_setval_varnchar(), mr_writeval_bit_internal(), mr_writeval_char_internal(), mr_writeval_nchar_internal(), pt_dbval_to_value(), pt_make_regu_hostvar(), tp_check_value_size(), tp_domain_resolve_value(), and tp_value_cast_internal().
void db_value_print (const DB_VALUE * value)
Definition at line 1663 of file db_macro.c.
References CHECK_CONNECT_VOID, db_fprint_value(), and NULL.
Referenced by btree_key_insert_new_key(), btree_verify_leaf_node(), cursor_fetch_page_having_tuple(), db_query_get_tuple_oid(), dbmeth_print(), and qdump_print_db_value().
int db_value_put (DB_VALUE * value, const DB_TYPE_C c_type, void * input, const int input_length)
Definition at line 1256 of file db_macro.c.
References ARG_FILE_LINE, C_TO_VALUE_CONVERSION_ERROR, C_TO_VALUE_NOERROR, C_TO_VALUE_UNSUPPORTED_CONVERSION, coerce_binary_to_dbvalue(), coerce_char_to_dbvalue(), coerce_date_to_dbvalue(), coerce_datetime_to_dbvalue(), coerce_numeric_to_dbvalue(), coerce_time_to_dbvalue(), coerce_timestamp_to_dbvalue(), db_make_multiset(), db_make_null(), db_make_object(), db_make_sequence(), db_make_set(), DB_TYPE_C_BIT, DB_TYPE_C_CHAR, DB_TYPE_C_DATE, DB_TYPE_C_DATETIME, DB_TYPE_C_DOUBLE, DB_TYPE_C_FLOAT, DB_TYPE_C_INT, DB_TYPE_C_LONG, DB_TYPE_C_MONETARY, DB_TYPE_C_NCHAR, DB_TYPE_C_OBJECT, DB_TYPE_C_SET, DB_TYPE_C_SHORT, DB_TYPE_C_TIME, DB_TYPE_C_TIMESTAMP, DB_TYPE_C_VARBIT, DB_TYPE_C_VARCHAR, DB_TYPE_C_VARNCHAR, DB_TYPE_MULTISET, DB_TYPE_OBJECT, DB_TYPE_SEQUENCE, DB_TYPE_SET, DB_VALUE_DOMAIN_TYPE, ER_DB_UNSUPPORTED_CONVERSION, ER_ERROR_SEVERITY, ER_OBJ_INVALID_ARGUMENTS, er_set(), NO_ERROR, and NULL.
Referenced by api_collection_set_to_db_value(), ldr_int_elem(), ldr_numeric_elem(), netval_to_dbval(), cubload::to_db_numeric(), cubload::to_int_generic(), uci_put_value(), and value_to_db_value().
int db_value_put_encoded_date (DB_VALUE * value, const DB_DATE * date_value)
Definition at line 1383 of file db_macro.c.
References CHECK_1ARG_ERROR, db_value::data, db_data::date, DB_TYPE_DATE, db_value::domain, db_domain_info::general_info, db_domain_info::general_info::is_null, db_value::need_clear, NO_ERROR, and db_domain_info::general_info::type.
Referenced by coerce_binary_to_dbvalue(), coerce_datetime_to_dbvalue(), coerce_timestamp_to_dbvalue(), db_string_value(), db_to_date(), db_trunc_dbval(), do_evaluate_default_expr(), fetch_peek_arith(), jsp_unpack_date_value(), mr_data_readval_date(), mr_getmem_date(), mr_index_readval_date(), mr_initval_date(), mr_setval_date(), pt_db_value_initialize(), pt_evaluate_db_value_expr(), qdata_interpolation_function_values(), qexec_execute_insert(), and tp_value_coerce_strict().
int db_value_put_encoded_time (DB_VALUE * value, const DB_TIME * time_value)
Definition at line 1357 of file db_macro.c.
References CHECK_1ARG_ERROR, db_value::data, DB_TYPE_TIME, db_value::domain, db_domain_info::general_info, db_domain_info::general_info::is_null, db_value::need_clear, NO_ERROR, db_data::time, and db_domain_info::general_info::type.
Referenced by coerce_binary_to_dbvalue(), coerce_datetime_to_dbvalue(), coerce_timestamp_to_dbvalue(), db_string_value(), db_to_time(), do_evaluate_default_expr(), fetch_peek_arith(), jsp_unpack_time_value(), mr_data_readval_time(), mr_getmem_time(), mr_index_readval_time(), mr_initval_time(), mr_setval_time(), pt_db_value_initialize(), pt_evaluate_db_value_expr(), qdata_interpolation_function_values(), qexec_execute_insert(), tp_value_cast_internal(), and tp_value_coerce_strict().
int db_value_put_monetary_amount_as_double (DB_VALUE * value, const double amount)
Definition at line 1470 of file db_macro.c.
References db_monetary::amount, CHECK_1ARG_ERROR, db_value::data, DB_TYPE_MONETARY, db_value::domain, db_domain_info::general_info, db_domain_info::general_info::is_null, db_data::money, db_value::need_clear, NO_ERROR, and db_domain_info::general_info::type.
int db_value_put_monetary_currency (DB_VALUE * value, const DB_CURRENCY type)
Definition at line 1409 of file db_macro.c.
References ARG_FILE_LINE, CHECK_1ARG_ERROR, db_value::data, DB_CURRENCY_AUSTRALIAN_DOLLAR, DB_CURRENCY_BRASILIAN_REAL, DB_CURRENCY_BRITISH_POUND, DB_CURRENCY_BULGARIAN_LEV, DB_CURRENCY_CAMBODIAN_RIEL, DB_CURRENCY_CANADIAN_DOLLAR, DB_CURRENCY_CHINESE_RENMINBI, DB_CURRENCY_CROATIAN_KUNA, DB_CURRENCY_CZECH_KORUNA, DB_CURRENCY_DANISH_KRONE, DB_CURRENCY_DOLLAR, DB_CURRENCY_EURO, DB_CURRENCY_INDIAN_RUPEE, DB_CURRENCY_NORWEGIAN_KRONE, DB_CURRENCY_POLISH_ZLOTY, DB_CURRENCY_ROMANIAN_LEU, DB_CURRENCY_RUSSIAN_RUBLE, DB_CURRENCY_SERBIAN_DINAR, DB_CURRENCY_SWEDISH_KRONA, DB_CURRENCY_SWISS_FRANC, DB_CURRENCY_TL, DB_CURRENCY_VIETNAMESE_DONG, DB_CURRENCY_WON, DB_CURRENCY_YEN, DB_TYPE_MONETARY, db_value::domain, ER_INVALID_CURRENCY_TYPE, er_set(), ER_WARNING_SEVERITY, error(), db_domain_info::general_info, db_data::money, db_value::need_clear, NO_ERROR, db_domain_info::general_info::type, and db_monetary::type.
int db_value_put_null (DB_VALUE * value)
Definition at line 122 of file db_macro.c.
References CHECK_1ARG_ERROR, db_value::domain, db_domain_info::general_info, db_domain_info::general_info::is_null, db_value::need_clear, and NO_ERROR.
Referenced by assign_set_value(), catcls_allocate_or_value(), catcls_get_or_value_from_buffer(), catcls_get_or_value_from_indexes(), catcls_get_property_set(), catcls_insert_instance(), catcls_update_instance(), classobj_init_attribute(), classobj_initialize_attributes(), disk_to_attribute(), get_desc_current(), get_desc_old(), get_set_value(), or_get_value(), or_unpack_mem_value(), pt_make_regu_constant(), swizzle_value(), tp_value_cast_internal(), vid_compare_non_updatable_objects(), and xlocator_repl_force().
int db_value_scale (const DB_VALUE * value)
Referenced by cache_validation(), col_api_get_elem_domain_info(), mr_setmem_numeric(), mr_setval_numeric(), numeric_db_value_print(), pt_dbval_to_value(), pt_make_regu_hostvar(), and tp_domain_resolve_value().
DB_TYPE db_value_type (const DB_VALUE * value)
Referenced by catcls_get_or_value_from_attribute(), convert_db_value_to_string(), db_value_to_value(), db_value_type_is_collection(), dblob_to_caslob(), dbval_to_net_buf(), delete_object_tuple(), disk_to_attribute(), do_cast_host_variables_to_expected_domain(), fetch_result(), fn_collection(), get_column_default_as_string(), heap_attrinfo_delete_lob(), heap_attrinfo_set_uninitialized(), heap_attrinfo_transform_to_disk_internal(), heap_get_referenced_by(), ldr_act_elem(), mht_get_hash_number(), mht_valhash(), obt_apply_assignments(), cubscan::json_table::scanner::open(), or_get_current_representation(), process_value(), pt_check_and_replace_hostvar(), pt_get_object_data_type(), pt_set_host_variables(), qdata_apply_interpolation_function_coercion(), qdata_interpolation_function_values(), qexec_execute_delete(), qexec_execute_update(), and serialize_collection_as_string().
bool db_value_type_is_collection (const DB_VALUE * value)
Definition at line 1144 of file db_macro.c.
References CHECK_1ARG_FALSE, CHECK_1ARG_NULL, CHECK_2ARGS_ERROR, db_value::data, db_get_object(), db_get_string(), DB_TYPE_OBJECT, DB_TYPE_STRING, DB_TYPE_VOBJ, db_value_type(), db_value::domain, db_domain_info::general_info, NO_ERROR, NULL, TP_IS_SET_TYPE, db_domain_info::general_info::type, and WS_OID.
Referenced by partition_prune_hash(), partition_prune_list(), and qo_analyze_term().