CUBRID Engine: src/compat/dbtype_function.c File Reference
dbtype_function.c File Reference
#include <stdio.h>
#include "db.h"
#include "dbtype_function.h"
#include "db_set.h"
#include "error_manager.h"
#include "elo.h"
#include "intl_support.h"
#include "language_support.h"
#include "memory_alloc.h"
#include "oid.h"
#include "set_object.h"
#include "system_parameter.h"
#include "dbtype_function.i"
Macros
#define API_ACTIVE_CHECKS
Functions
int db_make_db_char (DB_VALUE *value, const INTL_CODESET codeset, const int collation_id, const char *str, const int size)
DB_TYPE setobj_type (struct setobj *set)
Macro Definition Documentation
#define API_ACTIVE_CHECKS
Definition at line 21 of file dbtype_function.c.
Function Documentation
int db_make_db_char (DB_VALUE * value, const INTL_CODESET codeset, const int collation_id, const char * str, const int size)
Referenced by db_string_make_empty_typed_string(), db_string_unique_prefix(), and cubload::to_db_generic_char().
DB_TYPE setobj_type (struct setobj * set)
Definition at line 6158 of file set_object.c.
References DB_TYPE_NULL.
Referenced by set_make_collection().