var dir_483b32a6ce93291d0160e24fe223c96c =
[
    [ "boot.h", "boot_8h.html", "boot_8h" ],
    [ "boot_cl.c", "boot__cl_8c.html", "boot__cl_8c" ],
    [ "boot_cl.h", "boot__cl_8h.html", "boot__cl_8h" ],
    [ "boot_sr.c", "boot__sr_8c.html", "boot__sr_8c" ],
    [ "boot_sr.h", "boot__sr_8h.html", "boot__sr_8h" ],
    [ "client_credentials.cpp", "client__credentials_8cpp.html", "client__credentials_8cpp" ],
    [ "client_credentials.hpp", "client__credentials_8hpp.html", "client__credentials_8hpp" ],
    [ "locator.c", "locator_8c.html", "locator_8c" ],
    [ "locator.h", "locator_8h.html", "locator_8h" ],
    [ "locator_cl.c", "locator__cl_8c.html", "locator__cl_8c" ],
    [ "locator_cl.h", "locator__cl_8h.html", "locator__cl_8h" ],
    [ "locator_sr.c", "locator__sr_8c.html", "locator__sr_8c" ],
    [ "locator_sr.h", "locator__sr_8h.html", "locator__sr_8h" ],
    [ "lock_manager.c", "lock__manager_8c.html", "lock__manager_8c" ],
    [ "lock_manager.h", "lock__manager_8h.html", "lock__manager_8h" ],
    [ "lock_table.c", "lock__table_8c.html", "lock__table_8c" ],
    [ "log_2pc.c", "log__2pc_8c.html", "log__2pc_8c" ],
    [ "log_2pc.h", "log__2pc_8h.html", "log__2pc_8h" ],
    [ "log_append.cpp", "log__append_8cpp.html", "log__append_8cpp" ],
    [ "log_append.hpp", "log__append_8hpp.html", "log__append_8hpp" ],
    [ "log_applier.c", "log__applier_8c.html", "log__applier_8c" ],
    [ "log_applier.h", "log__applier_8h.html", "log__applier_8h" ],
    [ "log_applier_sql_log.c", "log__applier__sql__log_8c.html", "log__applier__sql__log_8c" ],
    [ "log_applier_sql_log.h", "log__applier__sql__log_8h.html", "log__applier__sql__log_8h" ],
    [ "log_archives.hpp", "log__archives_8hpp.html", "log__archives_8hpp" ],
    [ "log_comm.c", "log__comm_8c.html", "log__comm_8c" ],
    [ "log_comm.h", "log__comm_8h.html", "log__comm_8h" ],
    [ "log_common_impl.h", "log__common__impl_8h.html", "log__common__impl_8h" ],
    [ "log_compress.c", "log__compress_8c.html", "log__compress_8c" ],
    [ "log_compress.h", "log__compress_8h.html", "log__compress_8h" ],
    [ "log_global.c", "log__global_8c.html", "log__global_8c" ],
    [ "log_impl.h", "log__impl_8h.html", "log__impl_8h" ],
    [ "log_lsa.cpp", "log__lsa_8cpp.html", "log__lsa_8cpp" ],
    [ "log_lsa.hpp", "log__lsa_8hpp.html", "log__lsa_8hpp" ],
    [ "log_manager.c", "log__manager_8c.html", "log__manager_8c" ],
    [ "log_manager.h", "log__manager_8h.html", "log__manager_8h" ],
    [ "log_page_buffer.c", "log__page__buffer_8c.html", "log__page__buffer_8c" ],
    [ "log_postpone_cache.cpp", "log__postpone__cache_8cpp.html", null ],
    [ "log_postpone_cache.hpp", "log__postpone__cache_8hpp.html", [
      [ "log_postpone_cache", "classlog__postpone__cache.html", "classlog__postpone__cache" ],
      [ "cache_entry", "classlog__postpone__cache_1_1cache__entry.html", "classlog__postpone__cache_1_1cache__entry" ]
    ] ],
    [ "log_record.hpp", "log__record_8hpp.html", "log__record_8hpp" ],
    [ "log_recovery.c", "log__recovery_8c.html", "log__recovery_8c" ],
    [ "log_storage.hpp", "log__storage_8hpp.html", "log__storage_8hpp" ],
    [ "log_system_tran.cpp", "log__system__tran_8cpp.html", "log__system__tran_8cpp" ],
    [ "log_system_tran.hpp", "log__system__tran_8hpp.html", [
      [ "log_system_tdes", "classlog__system__tdes.html", "classlog__system__tdes" ]
    ] ],
    [ "log_tran_table.c", "log__tran__table_8c.html", "log__tran__table_8c" ],
    [ "log_volids.hpp", "log__volids_8hpp.html", "log__volids_8hpp" ],
    [ "log_writer.c", "log__writer_8c.html", "log__writer_8c" ],
    [ "log_writer.h", "log__writer_8h.html", "log__writer_8h" ],
    [ "mvcc.c", "mvcc_8c.html", "mvcc_8c" ],
    [ "mvcc.h", "mvcc_8h.html", "mvcc_8h" ],
    [ "mvcc_active_tran.cpp", "mvcc__active__tran_8cpp.html", null ],
    [ "mvcc_active_tran.hpp", "mvcc__active__tran_8hpp.html", [
      [ "mvcc_active_tran", "structmvcc__active__tran.html", "structmvcc__active__tran" ]
    ] ],
    [ "mvcc_table.cpp", "mvcc__table_8cpp.html", "mvcc__table_8cpp" ],
    [ "mvcc_table.hpp", "mvcc__table_8hpp.html", [
      [ "mvcc_trans_status", "structmvcc__trans__status.html", "structmvcc__trans__status" ],
      [ "mvcctable", "classmvcctable.html", "classmvcctable" ]
    ] ],
    [ "recovery.c", "recovery_8c.html", "recovery_8c" ],
    [ "recovery.h", "recovery_8h.html", "recovery_8h" ],
    [ "replication.c", "replication_8c.html", "replication_8c" ],
    [ "replication.h", "replication_8h.html", "replication_8h" ],
    [ "transaction_cl.c", "transaction__cl_8c.html", "transaction__cl_8c" ],
    [ "transaction_cl.h", "transaction__cl_8h.html", "transaction__cl_8h" ],
    [ "transaction_global.hpp", "transaction__global_8hpp.html", "transaction__global_8hpp" ],
    [ "transaction_sr.c", "transaction__sr_8c.html", "transaction__sr_8c" ],
    [ "transaction_sr.h", "transaction__sr_8h.html", "transaction__sr_8h" ],
    [ "transaction_transient.cpp", "transaction__transient_8cpp.html", "transaction__transient_8cpp" ],
    [ "transaction_transient.hpp", "transaction__transient_8hpp.html", "transaction__transient_8hpp" ],
    [ "wait_for_graph.c", "wait__for__graph_8c.html", null ],
    [ "wait_for_graph.h", "wait__for__graph_8h.html", null ]
];