CUBRID Engine: src/base/dl_daemon.c File Reference
dl_daemon.c File Reference
#include "config.h"
#include <stdlib.h>
#include <sys/param.h>
#include <errno.h>
#include <unistd.h>
#include "porting.h"
Functions
static void dynload_install_handlers (void)
static void dynload_remove_temporary_file (void)
void main (void)
Variables
static char dynload_Temporary_filename [PATH_MAX] = ""
Function Documentation
static void dynload_install_handlers (void) static
Definition at line 67 of file dl_daemon.c.
References os_set_signal_handler().
Referenced by main().
static void dynload_remove_temporary_file (void) static
Definition at line 49 of file dl_daemon.c.
References dynload_Temporary_filename.
Referenced by main().
void main (void)
Definition at line 91 of file dl_daemon.c.
References dynload_install_handlers(), dynload_remove_temporary_file(), and dynload_Temporary_filename.
Variable Documentation
char dynload_Temporary_filename[PATH_MAX] = "" static
Definition at line 39 of file dl_daemon.c.
Referenced by dynload_remove_temporary_file(), and main().