CUBRID Engine: src/base/dtoa.c File Reference
dtoa.c File Reference
#include <string.h>
#include <stdlib.h>
#include "mprec.h"
Functions
void free_Bigints (struct _Jv_Bigint *p)
static int _DEFUN (quorem,(b, S), _Jv_Bigint *b _AND _Jv_Bigint *S)
char * _DEFUN (_dtoa_r,(ptr, _d, mode, ndigits, decpt, sign, rve, float_type), struct _Jv_reent *ptr _AND double _d _AND int mode _AND int ndigits _AND int *decpt _AND int *sign _AND char **rve _AND int float_type)
_VOID _DEFUN (_dtoa,(_d, mode, ndigits, decpt, sign, rve, buf, float_type), double _d _AND int mode _AND int ndigits _AND int *decpt _AND int *sign _AND char **rve _AND char *buf _AND int float_type)
Function Documentation
static int _DEFUN (quorem , (b, S) , _Jv_Bigint *b _AND _Jv_Bigint * S) static
Definition at line 37 of file dtoa.c.
References _Jv_Bigint::_wds, _Jv_Bigint::_x, cmp, i, Sign_Extend, and Storeinc.
char* _DEFUN (_dtoa_r , (ptr, _d, mode, ndigits, decpt, sign, rve, float_type) , struct _Jv_reent *ptr _AND double _d _AND int mode _AND int ndigits _AND int *decpt _AND int *sign _AND char **rve _AND int float_type)
Definition at line 200 of file dtoa.c.
References _Jv_Bigint::_sign, Balloc, Bcopy, Bfree, Bias, bigtens, Bletch, Bndry_mask, cmp, double_union::d, d2b, diff, Exp_11, Exp_mask, Exp_msk1, Exp_shift1, Frac_mask, Frac_mask1, hi0bits, i, i2b, if(), Int_max, Log2P, lshift, mode, mult, multadd, n_bigtens, NULL, pow5mult, PREC, Quick_max, ROUND_BIASED, roundoff(), Sign_bit, Sudden_Underflow, Ten_pmax, tens, word0, and word1.
_VOID _DEFUN (_dtoa , (_d, mode, ndigits, decpt, sign, rve, buf, float_type) , double _d _AND int mode _AND int ndigits _AND int *decpt _AND int *sign _AND char **rve _AND char *buf _AND int float_type)
Definition at line 851 of file dtoa.c.
References _dtoa_r, _Jv_reent::_freelist, _Jv_reent::_max_k, _Jv_reent::_p5s, _Jv_reent::_result, free_Bigints(), i, mode, and p.
void free_Bigints (struct _Jv_Bigint * p)
Definition at line 839 of file dtoa.c.
References _Jv_Bigint::_next, _VOID, and p.
Referenced by _DEFUN().