CUBRID Engine: src/base/dynamic_load.h File Reference
dynamic_load.h File Reference
Enumerations
enum dl_estimate_mode { DL_RELATIVE, DL_ABSOLUTE }
Functions
int nlist (char *, struct nlist *)
int dl_initiate_module (const char *)
int dl_destroy_module (void)
Variables
int dl_Errno
const char * sys_errlist []
Enumeration Type Documentation
enum dl_estimate_mode
Enumerator
DL_RELATIVE
DL_ABSOLUTE
Definition at line 75 of file dynamic_load.h.
Function Documentation
int dl_destroy_module (void)
Definition at line 1776 of file dynamic_load.c.
References dl_Debug, dl_destroy_dynamic_loader(), dl_Errno, dl_is_valid_image_file(), DL_RELATIVE, dl_resolve_symbol(), DL_SET_ERROR_WITH_CODE, ER_DL_ABSENT, ER_DL_INVALID, ER_FAILED, free_and_init, nlist(), NO_ERROR, and NULL.
Referenced by boot_client_all_finalize(), boot_initialize_client(), and boot_restart_client().
int dl_initiate_module (const char *)
Definition at line 1725 of file dynamic_load.c.
References dl_Debug, dl_initiate_dynamic_loader(), dl_is_valid_image_file(), DL_SET_ERROR_SYSTEM_MSG, DL_SET_ERROR_WITH_CODE, DL_SET_ERROR_WITH_CODE_ONE_ARG, ER_DL_EXISTS, ER_DL_IMAGE, ER_DL_INVALID, ER_FAILED, NO_ERROR, and NULL.
Referenced by boot_initialize_client(), and boot_restart_client().
int nlist (char * , struct nlist *)
Referenced by dl_destroy_module(), dl_resolve_symbol(), sm_build_function_nlist(), sm_free_function_nlist(), and sm_locate_method_file().
Variable Documentation
int dl_Errno
Definition at line 189 of file dynamic_load.c.
Referenced by dl_decipher_waitval(), dl_destroy_module(), dl_initiate_dynamic_loader(), dl_is_valid_image_file(), dl_validate_candidates(), and dl_validate_file_entry().
const char* sys_errlist[]