CUBRID Engine: src/base/dynamic_array.h File Reference
dynamic_array.h File Reference
Classes
struct dynamic_array_t
Typedefs
typedef struct dynamic_array_t dynamic_array
Functions
dynamic_array * da_create (int count, size_t len)
int da_add (dynamic_array *da, void *data)
int da_put (dynamic_array *da, int pos, void *data)
int da_get (dynamic_array *da, int pos, void *data)
int da_size (dynamic_array *da)
int da_destroy (dynamic_array *da)
Typedef Documentation
typedef struct dynamic_array_t dynamic_array
Definition at line 26 of file dynamic_array.h.
Function Documentation
int da_add (dynamic_array * da, void * data)
Definition at line 82 of file dynamic_array.c.
References da_put(), and dynamic_array_t::max.
Referenced by checkdb(), us_hb_applylogdb_start(), us_hb_copylogdb_start(), and util_get_table_list_from_file().
dynamic_array* da_create (int count, size_t len)
Definition at line 30 of file dynamic_array.c.
References dynamic_array_t::array, dynamic_array_t::count, cubregex::count(), dynamic_array_t::len, dynamic_array_t::max, and NULL.
Referenced by checkdb(), checksumdb(), us_hb_process_applylogdb(), us_hb_process_copylogdb(), and us_hb_process_start().
int da_destroy (dynamic_array * da)
Definition at line 129 of file dynamic_array.c.
References dynamic_array_t::array, and NO_ERROR.
Referenced by checkdb(), checksumdb(), us_hb_process_applylogdb(), us_hb_process_copylogdb(), and us_hb_process_start().
int da_get (dynamic_array * da, int pos, void * data)
Definition at line 106 of file dynamic_array.c.
References dynamic_array_t::array, ER_FAILED, dynamic_array_t::len, dynamic_array_t::max, and NO_ERROR.
Referenced by chksum_need_skip_table(), us_hb_process_applylogdb(), us_hb_process_copylogdb(), us_hb_process_start(), and util_get_class_oids_and_index_btid().
int da_put (dynamic_array * da, int pos, void * data)
Definition at line 89 of file dynamic_array.c.
References dynamic_array_t::array, dynamic_array_t::count, da_expand(), ER_FAILED, dynamic_array_t::len, dynamic_array_t::max, and NO_ERROR.
Referenced by da_add().
int da_size (dynamic_array * da)
Definition at line 118 of file dynamic_array.c.
References dynamic_array_t::max, and NULL.
Referenced by checkdb(), chksum_need_skip_table(), us_hb_process_applylogdb(), us_hb_process_copylogdb(), us_hb_process_start(), and util_get_class_oids_and_index_btid().