CUBRID Engine: src/base/encryption.h File Reference
encryption.h File Reference
#include "porting.h"
Functions
void crypt_seed (const char *seed)
int crypt_encrypt_printable (const char *line, char *crypt, int maxlen)
int crypt_encrypt_sha1_printable (const char *line, char *crypt, int maxlen)
Function Documentation
int crypt_encrypt_printable (const char * line, char * crypt, int maxlen)
Definition at line 91 of file encryption.c.
References crypt_default_encrypt(), crypt_Key, db_private_free_and_init, DES_ECB, i, NO_ERROR, NULL, strlen, and TRUE.
Referenced by encrypt_password().
int crypt_encrypt_sha1_printable (const char * line, char * crypt, int maxlen)
Definition at line 200 of file encryption.c.
References i, SHA1Context::Message_Digest, SHA1Input(), SHA1Reset(), SHA1Result(), and strlen.
Referenced by encrypt_password_sha1().
void crypt_seed (const char * seed)
Definition at line 62 of file encryption.c.
References crypt_Key, and NULL.
Referenced by encrypt_password().