CUBRID Engine: src/base/encryption.c File Reference
encryption.c File Reference
#include "config.h"
#include "crypt_opfunc.h"
#include "error_code.h"
#include "encryption.h"
#include "memory_alloc.h"
#include "sha1.h"
Functions
void crypt_seed (const char *key)
int crypt_encrypt_printable (const char *line, char *crypt, int maxlen)
int crypt_encrypt_sha1_printable (const char *line, char *crypt, int maxlen)
Variables
static char crypt_Key [8]
Function Documentation
int crypt_encrypt_printable (const char * line, char * crypt, int maxlen)
Definition at line 91 of file encryption.c.
References crypt_default_encrypt(), crypt_Key, db_private_free_and_init, DES_ECB, i, NO_ERROR, NULL, strlen, and TRUE.
Referenced by encrypt_password().
int crypt_encrypt_sha1_printable (const char * line, char * crypt, int maxlen)
Definition at line 200 of file encryption.c.
References i, SHA1Context::Message_Digest, SHA1Input(), SHA1Reset(), SHA1Result(), and strlen.
Referenced by encrypt_password_sha1().
void crypt_seed (const char * key)
Definition at line 62 of file encryption.c.
References crypt_Key, and NULL.
Referenced by encrypt_password().
Variable Documentation
char crypt_Key[8] static
Definition at line 48 of file encryption.c.
Referenced by crypt_encrypt_printable(), and crypt_seed().