CUBRID Engine: src/base/environment_variable.h File Reference
environment_variable.h File Reference
Functions
const char * envvar_prefix (void)
const char * envvar_root (void)
const char * envvar_name (char *, size_t, const char *)
const char * envvar_get (const char *)
int envvar_set (const char *, const char *)
int envvar_expand (const char *, char *, size_t)
char * envvar_bindir_file (char *path, size_t size, const char *filename)
char * envvar_libdir_file (char *path, size_t size, const char *filename)
char * envvar_javadir_file (char *path, size_t size, const char *filename)
char * envvar_localedir_file (char *path, size_t size, const char *langpath, const char *filename)
char * envvar_confdir_file (char *path, size_t size, const char *filename)
char * envvar_vardir_file (char *path, size_t size, const char *filename)
char * envvar_tmpdir_file (char *path, size_t size, const char *filename)
char * envvar_logdir_file (char *path, size_t size, const char *filename)
void envvar_trim_char (char *var, const int c)
char * envvar_ldmldir_file (char *path, size_t size, const char *filename)
char * envvar_codepagedir_file (char *path, size_t size, const char *filename)
char * envvar_localedatadir_file (char *path, size_t size, const char *filename)
char * envvar_loclib_dir_file (char *path, size_t size, const char *filename)
char * envvar_cubrid_dir (char *path, size_t size)
char * envvar_tzdata_dir_file (char *path, size_t size, const char *filename)
Function Documentation
char* envvar_bindir_file (char * path, size_t size, const char * filename)
Definition at line 362 of file environment_variable.c.
References assert, envvar_Root, envvar_root(), and NULL.
Referenced by admin_start_cmd(), applylogdb(), copylogdb(), dl_find_daemon(), hb_start_util_process(), is_javasp_running(), is_manager_running(), main(), make_exec_abspath(), proc_execute_hide_cmd_args(), proc_execute_internal(), process_manager(), register_abort_signal_handler(), restart_is_needed(), and ut_cd_work_dir().
char* envvar_codepagedir_file (char * path, size_t size, const char * filename)
Definition at line 560 of file environment_variable.c.
References assert, envvar_Root, envvar_root(), and NULL.
Referenced by load_console_conv_data().
char* envvar_confdir_file (char * path, size_t size, const char * filename)
Definition at line 438 of file environment_variable.c.
References assert, envvar_Root, envvar_root(), and NULL.
Referenced by access_control_repath_file(), cfg_get_dbinfo(), cfg_read_dbinfo(), css_notify_ha_log_applier_state(), get_cubrid_file(), la_create_repl_filter(), locale_get_cfg_locales(), set_cubrid_file(), shard_metadata_read_conn(), shard_metadata_read_key(), and sysprm_load_and_init_internal().
char* envvar_cubrid_dir (char * path, size_t size)
Definition at line 617 of file environment_variable.c.
References envvar_Root, envvar_root(), and NULL.
Referenced by tzc_get_timezones_dot_c_filepath().
int envvar_expand (const char * , char * , size_t)
Definition at line 239 of file environment_variable.c.
References _ENVVAR_MAX_EXPANSION, _ENVVAR_MAX_LENGTH, ER_FAILED, NO_ERROR, NULL, strlcpy(), and strlen.
Referenced by sm_expand_method_files().
const char* envvar_get (const char *)
Definition at line 189 of file environment_variable.c.
References _ENVVAR_MAX_LENGTH, and envvar_name().
Referenced by broker_config_read(), cfg_get_directory_filename(), css_get_master_domain_path(), db_init(), delete_all_slave_ha_apply_info(), envvar_check_environment(), fileio_initialize_backup_info(), get_cubrid_file(), get_master_shm_id(), insert_ha_apply_info(), ldr_finish_context(), lock_initialize(), log_initialize_internal(), logpb_flush_all_append_pages(), main(), prm_check_environment(), qexec_execute_query(), session_states_finalize(), set_msg_lang_from_env(), sysprm_load_and_init_internal(), util_get_ha_parameters(), util_log_header(), and xboot_unregister_client().
char* envvar_javadir_file (char * path, size_t size, const char * filename)
Definition at line 400 of file environment_variable.c.
References assert, envvar_Root, envvar_root(), and NULL.
Referenced by jsp_start_server().
char* envvar_ldmldir_file (char * path, size_t size, const char * filename)
Definition at line 541 of file environment_variable.c.
References assert, envvar_Root, envvar_root(), and NULL.
Referenced by locale_check_and_set_default_files(), and start_include_collation().
char* envvar_libdir_file (char * path, size_t size, const char * filename)
Definition at line 381 of file environment_variable.c.
References assert, envvar_Root, envvar_root(), and NULL.
Referenced by broker_config_read_internal(), init_tz_name(), locale_check_and_set_default_files(), and tz_load().
char* envvar_localedatadir_file (char * path, size_t size, const char * filename)
Definition at line 579 of file environment_variable.c.
References assert, envvar_Root, envvar_root(), and NULL.
Referenced by init_uca_instance(), load_unicode_data(), and unicode_process_alphabet().
char* envvar_localedir_file (char * path, size_t size, const char * langpath, const char * filename)
Definition at line 419 of file environment_variable.c.
References assert, envvar_Root, envvar_root(), and NULL.
Referenced by msgcat_open(), and msgcat_open_file().
char* envvar_loclib_dir_file (char * path, size_t size, const char * filename)
Definition at line 598 of file environment_variable.c.
References assert, envvar_Root, envvar_root(), and NULL.
Referenced by locale_prepare_C_file(), and locale_save_to_C_file().
char* envvar_logdir_file (char * path, size_t size, const char * filename)
Definition at line 495 of file environment_variable.c.
References assert, envvar_Root, envvar_root(), and NULL.
Referenced by chksum_report_open_file(), er_init(), event_log_init(), get_cubrid_file(), javasp_get_error_file(), javasp_get_log_file(), and util_log_write_internal().
const char* envvar_name (char * , size_t , const char *)
Definition at line 153 of file environment_variable.c.
References envvar_prefix().
Referenced by envvar_check_environment(), envvar_get(), and envvar_set().
const char* envvar_prefix (void)
Definition at line 95 of file environment_variable.c.
References ENV_DONT_EXISTS_ROOT, ENV_INVALID_DIR, env_msg, envvar_check_environment(), envvar_Prefix, envvar_Prefix_name, envvar_Root, and NULL.
Referenced by css_get_master_domain_path(), envvar_name(), envvar_root(), and main().
const char* envvar_root (void)
Definition at line 135 of file environment_variable.c.
References envvar_prefix(), envvar_Root, and NULL.
Referenced by css_pack_server_name(), envvar_bindir_file(), envvar_codepagedir_file(), envvar_confdir_file(), envvar_cubrid_dir(), envvar_javadir_file(), envvar_ldmldir_file(), envvar_libdir_file(), envvar_localedatadir_file(), envvar_localedir_file(), envvar_loclib_dir_file(), envvar_logdir_file(), envvar_tmpdir_file(), envvar_tzdata_dir_file(), envvar_vardir_file(), getenv_cubrid_broker(), hb_pack_server_name(), jsp_start_server(), logddl_make_copy_dir(), logddl_make_copy_filename(), logddl_make_filename(), main(), and ut_cd_root_dir().
int envvar_set (const char * , const char *)
Definition at line 205 of file environment_variable.c.
References _ENVVAR_MAX_LENGTH, envvar_name(), ER_FAILED, and NO_ERROR.
Referenced by main(), and process_master().
char* envvar_tmpdir_file (char * path, size_t size, const char * filename)
Definition at line 476 of file environment_variable.c.
References assert, envvar_Root, envvar_root(), and NULL.
Referenced by get_cubrid_file().
void envvar_trim_char (char * var, const int c)
Definition at line 514 of file environment_variable.c.
References NULL, and strlen.
Referenced by check_env_lang_val().
char* envvar_tzdata_dir_file (char * path, size_t size, const char * filename)
Definition at line 634 of file environment_variable.c.
References assert, envvar_Root, envvar_root(), and NULL.
Referenced by gen_tz().
char* envvar_vardir_file (char * path, size_t size, const char * filename)
Definition at line 457 of file environment_variable.c.
References assert, envvar_Root, envvar_root(), and NULL.
Referenced by cfg_get_directory_filename(), fileio_lock_la_dbname(), fileio_unlock_la_dbname(), get_cubrid_file(), javasp_get_info_file(), javasp_open_info(), javasp_open_info_dir(), and main().