CUBRID Engine: src/base/error_manager.c File Reference
error_manager.c File Reference
#include "error_manager.h"
#include "chartype.h"
#include "error_context.hpp"
#include "environment_variable.h"
#include "memory_alloc.h"
#include "message_catalog.h"
#include "object_representation.h"
#include "release_string.h"
#include "system_parameter.h"
#include "stack_dump.h"
#include "transaction_cl.h"
#include <cassert>
#include <cstddef>
#include <cstring>
#include <errno.h>
#include <setjmp.h>
#include <signal.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/types.h>
#include <syslog.h>
#include <time.h>
#include <unistd.h>
#include <mutex>
Classes
struct er_copy_area
struct er_spec
struct er_fmt
Namespaces
cuberr
Macros
#define ER_SEVERITY_STRING(severity)
#define ER_ERROR_WARNING_STRING(severity)
#define ER_MSG_SET 1
#define ER_INTERNAL_MSG_SET 2
#define PRM_ER_MSGLEVEL 0
#define ER_MALLOC(size) er_malloc_helper ((size), __FILE__, __LINE__)
#define SPEC_CODE_LONGLONG ((char)0x88)
#define SPEC_CODE_SIZE_T ((char)0x89)
#define MAX_LINE 4096
#define ER_MSG_LOG_FILE_SUFFIX ".err"
#define ER_ACCESS_LOG_FILE_SUFFIX ".access"
#define MAX_INT_WIDTH 20
#define MAX_DOUBLE_WIDTH 32
Typedefs
typedef struct er_copy_area ER_COPY_AREA
typedef struct er_spec ER_SPEC
typedef struct er_fmt ER_FMT
Enumerations
enum er_msg_no {
ER_ER_HEADER = 1, ER_ER_MISSING_MSG, ER_ER_OUT_OF_MEMORY, ER_ER_NO_CATALOG,
ER_ER_LOG_MISSING_MSG, ER_ER_EXIT, ER_ER_ASK, ER_ER_UNKNOWN_FILE,
ER_ER_SUBSTITUTE_MSG, ER_LOG_ASK_VALUE, ER_LOG_MSGLOG_WARNING, ER_LOG_SUSPECT_FMT,
ER_LOG_UNKNOWN_CODE, ER_LOG_WRAPAROUND, ER_LOG_MSG_WRAPPER, ER_LOG_SYSLOG_WRAPPER,
ER_LOG_MSG_WRAPPER_D, ER_LOG_SYSLOG_WRAPPER_D, ER_LOG_LAST_MSG, ER_LOG_DEBUG_NOTIFY,
ER_STOP_MAIL_SUBJECT, ER_STOP_MAIL_BODY, ER_STOP_SYSLOG, ER_EVENT_HANDLER
}
Functions
static void er_event_sigpipe_handler (int sig)
static void er_event (void)
static int er_event_init (void)
static void er_event_final (void)
static FILE * er_file_open (const char *path)
static bool er_file_isa_null_device (const char *path)
static FILE * er_file_backup (FILE *fp, const char *path)
static void er_call_stack_dump_on_error (int severity, int err_id)
static void er_notify_event_on_error (int err_id)
static int er_set_internal (int severity, const char *file_name, const int line_no, int err_id, int num_args, bool include_os_error, FILE *fp, va_list *ap_ptr)
static void er_log (int err_id)
static void er_stop_on_error (void)
static int er_study_spec (const char *conversion_spec, char *simple_spec, int *position, int *width, int *va_class)
static void er_study_fmt (ER_FMT *fmt)
static size_t er_estimate_size (ER_FMT *fmt, va_list *ap)
static ER_FMT * er_find_fmt (int err_id, int num_args)
static void er_init_fmt (ER_FMT *fmt)
static ER_FMT * er_create_fmt_msg (ER_FMT *fmt, int err_id, const char *msg)
static void er_clear_fmt (ER_FMT *fmt)
static void er_internal_msg (ER_FMT *fmt, int code, int msg_num)
static void * er_malloc_helper (std::size_t size, const char *file, int line)
static void er_emergency (const char *file, int line, const char *fmt,...)
static int er_vsprintf (er_message *er_entry_p, ER_FMT *fmt, va_list *ap)
static int er_call_stack_init (void)
static int er_fname_free (const void *key, void *data, void *args)
static void er_call_stack_final (void)
static void _er_log_debug_internal (const char *file_name, const int line_no, const char *fmt, va_list *ap)
static bool er_is_error_severity (er_severity severity)
const char * er_get_msglog_filename (void)
int er_init (const char *msglog_filename, int exit_ask)
bool er_is_initialized (void)
void er_set_print_property (int print_console)
void er_final (ER_FINAL_CODE do_global_final)
void er_clear (void)
void er_set (int severity, const char *file_name, const int line_no, int err_id, int num_args,...)
void er_set_with_file (int severity, const char *file_name, const int line_no, int err_id, FILE *fp, int num_args,...)
void er_set_with_oserror (int severity, const char *file_name, const int line_no, int err_id, int num_args,...)
void er_print_callstack (const char *file_name, const int line_no, const char *fmt,...)
er_log_handler_t er_register_log_handler (er_log_handler_t handler)
int er_errid (void)
int er_errid_if_has_error (void)
void er_clearid (void)
void er_setid (int err_id)
int er_get_severity (void)
bool er_has_error (void)
const char * er_msg (void)
void er_all (int *err_id, int *severity, int *n_levels, int *line_no, const char **file_name, const char **error_msg)
void _er_log_debug (const char *file_name, const int line_no, const char *fmt,...)
char * er_get_ermsg_from_area_error (char *buffer)
char * er_get_area_error (char *buffer, int *length)
int er_set_area_error (char *server_area)
void er_stack_push (void)
void er_stack_push_if_exists (void)
void er_stack_pop (void)
void er_stack_pop_and_keep_error (void)
void er_restore_last_error (void)
void er_stack_clearall (void)
Variables
std::mutex er_Log_file_mutex
std::mutex er_Message_cache_mutex
static const char * er_severity_string [] = { "FATAL ERROR", "ERROR", "SYNTAX ERROR", "WARNING", "NOTIFICATION" }
static const char * er_unknown_severity = "Unknown severity level"
static const char * er_Builtin_msg []
static char * er_Cached_msg [sizeof(er_Builtin_msg)/sizeof(const char *)]
static bool er_Is_cached_msg = false
static char er_Msglog_filename_buff [PATH_MAX]
static const char * er_Msglog_filename = NULL
static FILE * er_Msglog_fh = NULL
static char er_Accesslog_filename_buff [PATH_MAX]
static const char * er_Accesslog_filename = NULL
static FILE * er_Accesslog_fh = NULL
static ER_FMT er_Fmt_list [(-ER_LAST_ERROR)+1]
static int er_Fmt_msg_fail_count = -ER_LAST_ERROR
static int er_Errid_not_initialized = 0
static er_log_handler_t er_Handler = NULL
static unsigned int er_Eid = 0
static FILE * er_Event_pipe = NULL
static bool er_Event_started = false
static jmp_buf er_Event_jmp_buf
static SIGNAL_HANDLER_FUNCTION saved_Sig_handler
static bool er_Logfile_opened = false
static bool er_Hasalready_initiated = false
static bool er_Has_sticky_init = false
static bool er_Isa_null_device = false
static int er_Exit_ask = ER_EXIT_DEFAULT
static int er_Print_to_console = ER_DO_NOT_PRINT
static context * er_Singleton_context_p
static PTR_FNERLOG er_Fnlog [ER_MAX_SEVERITY+1]
Macro Definition Documentation
#define ER_ACCESS_LOG_FILE_SUFFIX ".access"
Definition at line 291 of file error_manager.c.
Referenced by er_fname_free(), er_init(), and er_log().
#define ER_ERROR_WARNING_STRING (severity)
Value:
(((severity) >= ER_FATAL_ERROR_SEVERITY && (severity) < ER_WARNING_SEVERITY) \
   ? er_severity_string[ER_ERROR_SEVERITY] : "")
Definition at line 158 of file error_manager.c.
Referenced by er_log().
#define ER_INTERNAL_MSG_SET 2
Definition at line 169 of file error_manager.c.
#define ER_MALLOC (size) er_malloc_helper ((size), __FILE__, __LINE__)
Definition at line 173 of file error_manager.c.
Referenced by er_create_fmt_msg(), er_study_fmt(), and er_vsprintf().
#define ER_MSG_LOG_FILE_SUFFIX ".err"
Definition at line 285 of file error_manager.c.
Referenced by er_fname_free(), er_init(), and er_log().
#define ER_MSG_SET 1
Definition at line 168 of file error_manager.c.
#define ER_SEVERITY_STRING (severity)
Value:
(((severity) >= ER_FATAL_ERROR_SEVERITY && (severity) <= ER_MAX_SEVERITY) \
   ? er_severity_string[severity] : er_unknown_severity)
Definition at line 154 of file error_manager.c.
Referenced by er_event(), er_event_final(), er_event_init(), and er_log().
#define MAX_DOUBLE_WIDTH 32
Definition at line 2612 of file error_manager.c.
Referenced by er_estimate_size().
#define MAX_INT_WIDTH 20
Definition at line 2611 of file error_manager.c.
Referenced by er_estimate_size().
#define MAX_LINE 4096
Definition at line 178 of file error_manager.c.
Referenced by er_set_internal().
#define PRM_ER_MSGLEVEL 0
Definition at line 171 of file error_manager.c.
#define SPEC_CODE_LONGLONG ((char)0x88)
Definition at line 175 of file error_manager.c.
Referenced by er_estimate_size(), er_study_spec(), and er_vsprintf().
#define SPEC_CODE_SIZE_T ((char)0x89)
Definition at line 176 of file error_manager.c.
Referenced by er_estimate_size(), er_study_spec(), and er_vsprintf().
Typedef Documentation
typedef struct er_copy_area ER_COPY_AREA
Definition at line 100 of file error_manager.c.
typedef struct er_fmt ER_FMT
Definition at line 117 of file error_manager.c.
typedef struct er_spec ER_SPEC
Definition at line 109 of file error_manager.c.
Enumeration Type Documentation
enum er_msg_no
Enumerator
ER_ER_HEADER
ER_ER_MISSING_MSG
ER_ER_OUT_OF_MEMORY
ER_ER_NO_CATALOG
ER_ER_LOG_MISSING_MSG
ER_ER_EXIT
ER_ER_ASK
ER_ER_UNKNOWN_FILE
ER_ER_SUBSTITUTE_MSG
ER_LOG_ASK_VALUE
ER_LOG_MSGLOG_WARNING
ER_LOG_SUSPECT_FMT
ER_LOG_UNKNOWN_CODE
ER_LOG_WRAPAROUND
ER_LOG_MSG_WRAPPER
ER_LOG_SYSLOG_WRAPPER
ER_LOG_MSG_WRAPPER_D
ER_LOG_SYSLOG_WRAPPER_D
ER_LOG_LAST_MSG
ER_LOG_DEBUG_NOTIFY
ER_STOP_MAIL_SUBJECT
ER_STOP_MAIL_BODY
ER_STOP_SYSLOG
ER_EVENT_HANDLER
Definition at line 190 of file error_manager.c.
Function Documentation
void _er_log_debug (const char * file_name, const int line_no, const char * fmt, ...)
Definition at line 1992 of file error_manager.c.
References _er_log_debug_internal(), assert, and er_Log_file_mutex.
Referenced by btree_construct_leafs(), btree_delete_postponed(), btree_insert(), btree_mvcc_delete(), btree_physical_delete(), btree_reflect_global_unique_statistics(), btree_rv_record_modify_internal(), btree_rv_redo_global_unique_stats_commit(), btree_rv_undo_global_unique_stats_commit(), btree_sort_get_next(), btree_undo_delete_physical(), btree_undo_insert_object(), btree_undo_insert_object_unique_multiupd(), btree_undo_mvcc_delete(), btree_vacuum_insert_mvccid(), btree_vacuum_object(), disk_reserve_sectors(), index_builder_loader_task::execute(), log_recovery_analysis(), log_recovery_redo(), log_rollback_record(), log_rv_undo_record(), logpb_remove_archive_logs(), logpb_remove_archive_logs_exceed_limit(), logtb_rv_update_global_unique_stats_by_abs(), logtb_update_global_unique_stats_by_delta(), logwr_check_page_checksum(), net_server_request(), perfmon_per_daemon_stat_count(), perfmon_stat_dump_in_buffer_thread_daemon_stats(), pgbuf_flush_page_and_neighbors_fb(), pgbuf_flush_victim_candidates(), pgbuf_get_victim_candidates_from_lru(), pgbuf_ordered_fix_debug(), cubbase::restrack_log(), stran_server_auto_commit_or_abort(), cubthread::wp_er_log_stats(), xbtree_load_index(), and xbtree_load_online_index().
static void _er_log_debug_internal (const char * file_name, const int line_no, const char * fmt, va_list * ap) static
Definition at line 2027 of file error_manager.c.
References ER_LOG_DEBUG_NOTIFY, and NULL.
Referenced by _er_log_debug(), and er_print_callstack().
void er_all (int * err_id, int * severity, int * n_levels, int * line_no, const char ** file_name, const char ** error_msg)
Definition at line 1968 of file error_manager.c.
References er_msg(), cuberr::er_message::err_id, cuberr::er_message::file_name, cuberr::er_message::line_no, and cuberr::er_message::severity.
Referenced by er_event(), and er_log().
static void er_call_stack_dump_on_error (int severity, int err_id) static
Definition at line 1347 of file error_manager.c.
References assert, er_dump_call_stack(), ER_FATAL_ERROR_SEVERITY, NO_ERROR, prm_get_bool_value(), PRM_ID_CALL_STACK_DUMP_ACTIVATION, PRM_ID_CALL_STACK_DUMP_DEACTIVATION, PRM_ID_CALL_STACK_DUMP_ON_ERROR, and sysprm_find_err_in_integer_list().
Referenced by er_set_internal().
static void er_call_stack_final (void) static
Definition at line 586 of file error_manager.c.
References er_fname_free(), mht_destroy(), mht_map(), and NULL.
Referenced by er_final().
static int er_call_stack_init (void) static
Definition at line 568 of file error_manager.c.
References ER_FAILED, mht_5strhash(), mht_compare_strings_are_equal(), mht_create(), NO_ERROR, and NULL.
Referenced by er_init().
void er_clear (void)
Definition at line 1201 of file error_manager.c.
References er_is_initialized().
Referenced by au_add_user(), boot_client_all_finalize(), boot_initialize_client(), boot_remove_all_volumes(), boot_restart_client(), boot_restart_server(), btree_create_file(), btree_merge_node_and_advance(), btree_set_error(), catalog_start_access_with_dir_oid(), catcls_expand_or_value_by_subset(), catcls_get_or_value_from_domain(), cubload::sa_class_installer::check_class(), csql_display_trace(), csql_do_session_cmd(), csql_execute_statements(), css_refuse_connection_request(), db_accumulate_json_objectagg(), db_add_days_to_year(), db_add_time(), db_ascii(), db_bigint_to_binary_string(), db_compile_statement(), db_compile_statement_local(), db_conv(), db_convert_sec_to_time(), db_convert_time_to_sec(), db_convert_to_time(), db_crc32_dbval(), db_date_add_sub_interval_days(), db_date_add_sub_interval_expr(), db_date_dbval(), db_date_diff(), db_date_format(), db_date_parse_date(), db_date_parse_datetime_parts(), db_date_parse_timestamp(), db_datetimetz_to_string(), db_execute_and_keep_statement_local(), db_find_string_in_in_set(), db_from_unixtime(), db_get_cs_coll_info(), db_get_date_dayofyear(), db_get_date_item(), db_get_date_quarter(), db_get_date_totaldays(), db_get_date_week(), db_get_date_weekday(), db_get_datetime_from_dbvalue(), db_get_system_parameters(), db_get_time_from_dbvalue(), db_get_time_item(), db_guid(), db_hex(), db_inet_aton(), db_inet_ntoa(), db_json_split_path_by_delimiters(), db_last_day(), db_round_dbval(), db_round_dbvalue_to_int(), db_str_to_date(), db_string_aes_decrypt(), db_string_aes_encrypt(), db_string_chr(), db_string_from_base64(), db_string_regexp_count(), db_string_regexp_instr(), db_string_regexp_like(), db_string_regexp_replace(), db_string_regexp_substr(), db_string_rlike(), db_string_sha_one(), db_string_sha_two(), db_string_to_base64(), db_time_dbval(), db_time_diff(), db_time_format(), db_trunc_dbval(), db_unix_timestamp(), db_value_to_enumeration_value(), db_width_bucket(), dbval_to_net_buf(), delete_list_by_oids(), disk_reserve_sectors(), do_alter_serial(), do_create_entity(), do_create_partition(), do_create_serial(), do_get_serial_obj_id(), do_insert_template(), emit_instance_attributes(), er_set_area_error(), eval_action(), export_serial(), fetch_result(), file_print_name_of_class(), fn_oid(), get_date_weekday(), get_year_month_or_day(), heap_classrepr_dump_all(), heap_get_class_name_alloc_if_diff(), heap_object_upgrade_domain(), heap_stats_find_page_in_bestspace(), cubload::error_handler::is_last_error_filtered(), javasp_start_server(), jsp_execute_stored_procedure(), jsp_find_stored_procedure(), jsp_is_exist_stored_procedure(), la_update_ha_apply_info_log_record_time(), la_update_ha_last_applied_info(), ldr_act_init_context(), lob_length(), lob_to_bit_char(), locator_all_reference_lockset(), locator_attribute_info_force(), locator_check_btree_entries(), locator_check_unique_btree_entries(), locator_delete_force_internal(), locator_filter_errid(), locator_guess_sub_classes(), locator_update_force(), lock_demote_class_lock(), log_rv_redo_fix_page(), logpb_delete(), logpb_remove_all_in_log_path(), net_client_request_with_callback(), cubload::session::notify_batch_done(), cubload::session::notify_batch_done_and_register_tran_end(), numeric_db_value_add(), numeric_db_value_compare(), numeric_db_value_sub(), cubload::error_handler::on_syntax_failure(), partition_prune_hash(), pgbuf_fix_if_not_deallocated_with_caller(), pgbuf_rv_flush_page(), pgbuf_unlatch_bcb_upon_unfix(), process_object(), pt_check_create_entity(), pt_check_method(), pt_eval_method_call_type(), pt_evaluate_db_value_expr(), pt_fold_const_expr(), pt_resolve_method_type(), qdump_print_xasl(), qexec_execute_duplicate_key_update(), qexec_execute_obj_fetch(), qexec_execute_query(), qexec_execute_selupd_list(), qexec_execute_update(), qo_rewrite_like_for_index_scan(), cubthread::entry_manager::recycle_context(), round_date(), scan_next_heap_scan(), scan_next_index_lookup_heap(), smt_add_constraint(), ssession_find_or_create_session(), cubload::to_db_int_set(), tp_value_auto_cast(), tp_value_coerce_strict(), tp_value_compare_with_error(), cubxasl::json_table::column::trigger_on_error(), update_object_tuple(), ux_check_object(), ux_database_connect(), vacuum_heap(), vacuum_heap_get_hfid_and_file_type(), vacuum_process_log_block(), xboot_delete(), xboot_initialize_server(), xbtree_load_online_index(), xlocator_repl_force(), xstats_get_statistics_from_server(), and xstats_update_all_statistics().
static void er_clear_fmt (ER_FMT * fmt) static
Definition at line 2836 of file error_manager.c.
References er_fmt::fmt, er_fmt::fmt_length, free_and_init, er_fmt::must_free, er_fmt::nspecs, NULL, er_fmt::spec, er_fmt::spec_buf, and er_fmt::spec_top.
Referenced by er_final(), and er_internal_msg().
void er_clearid (void)
Definition at line 1860 of file error_manager.c.
References assert, and NO_ERROR.
Referenced by er_filter_errid().
static ER_FMT * er_create_fmt_msg (ER_FMT * fmt, int err_id, const char * msg) static
Definition at line 2786 of file error_manager.c.
References ER_ER_MISSING_MSG, er_internal_msg(), ER_MALLOC, er_study_fmt(), er_copy_area::err_id, er_fmt::err_id, er_fmt::fmt, er_fmt::fmt_length, er_fmt::must_free, NULL, and strlen.
Referenced by er_find_fmt(), and er_init().
static void er_emergency (const char * file, int line, const char * fmt, ...) static
Definition at line 2907 of file error_manager.c.
References CAST_STRLEN, ER_ER_HEADER, ER_ERROR_SEVERITY, ER_GENERIC_ERROR, er_log(), cuberr::er_message::err_id, cuberr::er_message::file_name, cuberr::er_message::line_no, cuberr::er_message::msg_area, cuberr::er_message::msg_area_size, NULL, p, cuberr::er_message::severity, and strlen.
Referenced by er_init(), er_malloc_helper(), and er_vsprintf().
int er_errid (void)
Definition at line 1820 of file error_manager.c.
References assert, and er_Errid_not_initialized.
Referenced by access_object(), add_arg_domain(), add_class_grant(), add_deferred_activities(), add_method_internal(), add_resolution(), allocate_disk_structures(), allocate_foreign_key(), allocate_unique_constraint(), alter_trigger_cache(), annotate_method_files(), applylogdb(), area_insert_block(), assign_null_value(), assign_set_value(), au_add_member_method(), au_add_user(), au_add_user_method(), au_change_owner_method(), au_change_serial_owner(), au_change_serial_owner_method(), au_change_sp_owner_method(), au_change_trigger_owner_method(), au_compute_groups(), au_delete_new_auth(), au_drop_member_method(), au_drop_user(), au_extend_class_caches(), au_find_user(), au_find_user_cache_index(), au_find_user_to_drop(), au_get_class_privilege(), au_get_new_auth(), au_get_owner_method(), au_install(), au_perform_login(), au_set_new_auth(), au_set_password_internal(), au_start(), au_update_new_auth(), boot_add_charsets(), boot_add_collations(), boot_add_data_type(), boot_client_find_and_cache_class_oids(), boot_define_attribute(), boot_define_charsets(), boot_define_class(), boot_define_class_authorization(), boot_define_collations(), boot_define_data_type(), boot_define_domain(), boot_define_dual(), boot_define_ha_apply_info(), boot_define_index(), boot_define_index_key(), boot_define_meth_argument(), boot_define_meth_file(), boot_define_meth_sig(), boot_define_method(), boot_define_partition(), boot_define_query_spec(), boot_define_serial(), boot_define_stored_procedure(), boot_define_stored_procedure_arguments(), boot_define_view_attribute(), boot_define_view_attribute_set_domain(), boot_define_view_authorization(), boot_define_view_class(), boot_define_view_db_charset(), boot_define_view_db_collation(), boot_define_view_index(), boot_define_view_index_key(), boot_define_view_method(), boot_define_view_method_argument(), boot_define_view_method_argument_set_domain(), boot_define_view_method_file(), boot_define_view_partition(), boot_define_view_stored_procedure(), boot_define_view_stored_procedure_arguments(), boot_define_view_super_class(), boot_define_view_trigger(), boot_define_view_vclass(), boot_initialize_client(), boot_reset_mk_after_restart_from_backup(), boot_restart_client(), boot_restart_server(), btree_add_index(), btree_apply_key_range_and_filter(), btree_check_by_btid(), btree_check_by_class_oid(), btree_check_foreign_key(), btree_construct_leafs(), btree_delete_meta_record(), btree_delete_overflow_key(), btree_find_foreign_key(), btree_find_lower_bound_leaf(), btree_find_min_or_max_key(), btree_find_next_index_record_holding_current(), btree_find_next_index_record_holding_current_helper(), btree_fk_object_does_exist(), btree_get_asc_desc(), btree_get_num_visible_oids_from_all_ovf(), btree_get_stats(), btree_get_stats_key(), btree_get_stats_midxkey(), btree_get_stats_with_AR_sampling(), btree_get_subtree_capacity(), btree_get_unique_statistics(), btree_index_capacity(), btree_key_process_objects(), btree_load_index(), btree_load_overflow_key(), btree_merge_node_and_advance(), btree_merge_root(), btree_pack_root_header(), btree_rv_nodehdr_redo_insert(), btree_rv_nodehdr_undoredo_update(), btree_rv_noderec_redo_insert(), btree_rv_noderec_undoredo_update(), btree_rv_pagerec_delete(), btree_rv_pagerec_insert(), btree_rv_util_save_page_records(), btree_save_last_leafrec(), btree_split_node_and_advance(), btree_split_root(), btree_store_overflow_key(), btree_update(), build_attr_change_map(), build_xasl_for_server_delete(), call_method(), catalog_check_class_consistency(), catalog_delete(), catalog_drop_all(), catalog_drop_representation_class_from_page(), catalog_drop_representation_helper(), catalog_get_cardinality(), catalog_get_class_info(), catalog_get_dir_oid_from_cache(), catalog_get_last_representation_id(), catalog_get_rep_dir(), catalog_get_representation(), catalog_get_representation_directory(), catalog_get_representation_record(), catalog_get_representation_record_after_search(), catalog_insert(), catalog_rv_insert_redo(), catalog_rv_new_page_redo(), catalog_rv_update(), catalog_update(), catalog_update_class_info(), catcls_class_install(), catcls_convert_class_oid_to_oid(), catcls_delete_instance(), catcls_delete_subset(), catcls_expand_or_value_by_subset(), catcls_find_btid_of_class_name(), catcls_find_oid_by_class_name(), catcls_get_object_set(), catcls_get_or_value_from_class(), catcls_get_or_value_from_domain(), catcls_get_or_value_from_record(), catcls_insert_instance(), catcls_insert_subset(), catcls_put_or_value_into_record(), catcls_reorder_attributes_by_repr(), catcls_update_instance(), catcls_update_subset(), change_constraints_comment_partitioned_class(), check_args(), check_att_domain(), check_authorization(), cubload::sa_class_installer::check_class(), check_default_on_update_clause(), check_fk_validity(), check_grant_option(), check_semantics(), chksum_init_checksum_tables(), chksum_report(), chksum_start(), class_referenced_by_class(), classobj_area_init(), classobj_btid_from_property_value(), classobj_cache_not_null_constraints(), classobj_check_function_constraint_info(), classobj_copy_attlist(), classobj_copy_attribute_like(), classobj_copy_constraint_like(), classobj_copy_methfiles(), classobj_copy_methlist(), classobj_copy_props(), classobj_copy_reslist(), classobj_drop_foreign_key_ref(), classobj_init_attribute(), classobj_init_method(), classobj_install_template(), classobj_make_class_constraints(), classobj_oid_from_property_value(), classobj_populate_class_properties(), classobj_put_foreign_key_ref(), clean_up(), clist_init(), col_expand_blocks(), col_permanent_oids(), col_successive_merge(), collect_class_grants(), collect_hier_class_info(), compile_trigger_activity(), convert_speclist_to_objlist(), copylogdb(), create_or_drop_index_helper(), csect_start_scan(), csession_find_or_create_session(), csql_do_session_cmd(), csql_execute_statements(), css_client_init(), css_make_access_status_exist_user(), css_register_server_timeout_fn(), css_send_error_to_server(), css_user_access_status_start_scan(), cursor_fetch_oids(), db_add_attribute_internal(), db_add_class_resolution(), db_add_constraint(), db_add_method_file(), db_add_query_spec(), db_add_resolution(), db_add_set_attribute_domain(), db_add_super_internal(), db_add_volume_ex(), db_change_default(), db_change_method_implementation(), db_change_query_spec(), db_compile_statement_local(), db_compress_like_pattern(), db_conv(), db_crc32_dbval(), db_create_vclass(), db_date_format(), db_drop_class_resolution(), db_drop_constraint(), db_drop_method_file(), db_drop_method_files(), db_drop_query_spec(), db_drop_resolution(), db_drop_set_attribute_domain(), db_drop_super(), db_drop_super_connect(), db_error_code(), db_execute_and_keep_statement_local(), db_fetch_array(), db_fetch_composition(), db_from_unixtime(), db_get_like_optimization_bounds(), db_get_query_result_format(), db_get_schema_def_dbval(), db_get_serial_current_value(), db_get_serial_next_value_ex(), db_get_start_line(), db_get_statement_type(), db_get_subclass_names(), db_get_superclass_names(), db_guid(), db_hex(), db_number_of_input_markers(), db_number_of_output_markers(), db_open_buffer_and_compile_first_statement(), db_query_end_internal(), db_query_get_tuple_valuelist(), db_query_produce_updatable_result(), db_query_seek_tuple(), db_rename_internal(), db_round_dbval(), db_set_client_cache_time(), db_set_loader_commands(), db_set_statement_auto_commit(), db_string_aes_decrypt(), db_string_aes_encrypt(), db_string_convert_to(), db_string_from_base64(), db_string_limit_size_string(), db_string_sha_one(), db_string_sha_two(), db_string_space(), db_string_unique_prefix(), db_time_format(), db_validate(), db_validate_query_spec(), db_width_bucket(), dbt_add_constraint(), dbt_add_foreign_key(), dbt_drop_constraint(), define_trigger_classes(), delete_list_by_oids(), delete_real_class(), object_printer::describe_class(), disk_to_attribute(), do_add_attribute(), do_add_constraints(), do_add_methods(), do_add_resolutions(), do_add_supers(), do_alter(), do_alter_change_auto_increment(), do_alter_change_col_comment(), do_alter_change_default_cs_coll(), do_alter_change_tbl_comment(), do_alter_clause_change_attribute(), do_alter_clause_drop_index(), do_alter_index_comment(), do_alter_index_rebuild(), do_alter_index_status(), do_alter_one_clause_with_template(), do_alter_serial(), do_alter_trigger(), do_alter_user(), do_call_method(), do_change_att_schema_only(), do_change_auto_increment_serial(), do_check_for_empty_classes_in_delete(), do_check_rows_for_null(), do_coalesce_partition_post(), do_coalesce_partition_pre(), do_copy_indexes(), do_create_auto_increment_serial(), do_create_entity(), do_create_index(), do_create_partition(), do_create_partition_constraint(), do_create_partition_constraints(), do_create_serial(), do_create_serial_internal(), do_create_trigger(), do_create_user(), do_drop(), do_drop_index(), do_drop_partition_list(), do_drop_trigger(), do_evaluate_insert_values(), do_execute_do(), do_execute_merge(), do_execute_select(), do_execute_session_statement(), do_execute_statement(), do_execute_update(), do_get_optimization_param(), do_get_serial_obj_id(), do_get_stats(), do_get_trigger(), do_get_xaction(), do_grant(), do_insert(), do_insert_at_server(), do_insert_template(), do_merge(), do_prepare_delete(), do_prepare_insert_internal(), do_prepare_merge(), do_prepare_select(), do_prepare_statement(), do_prepare_update(), do_process_prepare_statement(), do_promote_partition(), do_promote_partition_by_name(), do_promote_partition_list(), do_reclaim_class_addresses(), do_recompile_and_execute_prepared_statement(), do_recreate_filter_index_constr(), do_recreate_renamed_class_indexes(), do_redistribute_partitions_data(), do_remove_partition_post(), do_rename_internal(), do_rename_trigger(), do_reorganize_partition_post(), do_reset_auto_increment_serial(), do_revoke(), do_rollback(), do_run_update_query_for_class(), do_savepoint(), do_select_internal(), do_set_session_variables(), do_set_trigger(), do_set_user_host_variables(), do_statement(), do_update(), do_update_auto_increment_serial_on_rename(), do_update_maxvalue_of_auto_increment_serial(), drop_class_name(), drop_foreign_key_ref_internal(), drop_internal(), drop_stored_procedure(), dwb_write_block(), ehash_fix_old_page(), ehash_rv_delete(), ehash_rv_delete_undo(), ehash_rv_init_bucket_redo(), ehash_rv_insert_redo(), ehash_rv_insert_undo(), elo_copy(), elo_delete(), er_filter_errid(), er_stop_on_error(), error_info_set_with_msg(), execute_create_select_query(), execute_query(), extract_classes(), fetch_class(), fetch_instance(), fetch_peek_min_max_value_of_width_bucket_func(), fetch_set_internal(), fileio_format(), fileio_list_restore(), fileio_synchronize_all(), fileio_write_backup_node(), filter_local_constraints(), filter_resolutions(), find_argument(), find_attribute_op(), find_instance(), find_unique(), cubload::sa_object_loader::finish_line(), flatten_components(), flatten_method_files(), flatten_partition_info(), flatten_properties(), flatten_query_spec_lists(), flatten_subclasses(), flatten_template(), flatten_trigger_cache(), genlocale(), get_att_default_from_def(), get_domain_internal(), get_grants(), get_schema_trigger_objects(), get_set_value(), heap_attrinfo_check(), heap_attrinfo_check_unique_index(), heap_attrinfo_delete_lob(), heap_attrinfo_read_dbvalues(), heap_attrinfo_read_dbvalues_without_oid(), heap_attrinfo_recache(), heap_attrinfo_recache_attrepr(), heap_attrinfo_set(), heap_attrinfo_set_uninitialized(), heap_attrinfo_start(), heap_attrvalue_read(), heap_chnguess_realloc(), heap_delete_bigone(), heap_delete_home(), heap_does_exist(), heap_fix_forward_page(), heap_fix_header_page(), heap_flush(), heap_get_btid_from_index_name(), heap_get_capacity(), heap_get_class_partitions(), heap_get_indexinfo_of_btid(), heap_get_record_location(), heap_header_capacity_start_scan(), heap_header_next_scan(), heap_next_internal(), heap_prefetch(), heap_prepare_get_context(), heap_prepare_object_page(), heap_rv_redo_insert(), heap_rv_redo_newpage(), heap_rv_redo_reuse_page(), heap_rv_redo_reuse_page_reuse_oid(), heap_rv_undoredo_pagehdr(), heap_scancache_start_internal(), heap_scancache_start_modify(), heap_scanrange_start(), heap_stats_find_best_page(), heap_stats_find_page_in_bestspace(), class_description::init(), init_db_attribute_list(), insert_meth_instance(), insert_subquery_results(), insert_trigger_list(), install_new_representation(), cubload::error_handler::is_last_error_filtered(), javasp_ping_server(), javasp_status_server(), javasp_stop_server(), jsp_add_stored_procedure(), jsp_add_stored_procedure_argument(), jsp_alter_stored_procedure(), jsp_call_stored_procedure(), jsp_create_stored_procedure(), jsp_do_call_stored_procedure(), jsp_drop_stored_procedure(), jsp_execute_stored_procedure(), jsp_find_stored_procedure(), jsp_get_return_type(), jsp_receive_error(), jsp_receive_result(), jsp_send_call_request(), jsp_send_destroy_request(), jsp_start_server(), kill_transactions(), la_apply_delete_log(), la_apply_insert_log(), la_apply_log_file(), la_apply_repl_log(), la_apply_statement_log(), la_apply_update_log(), la_get_ha_apply_info(), la_get_log_data(), la_get_next_update_log(), la_log_io_read_with_max_retries(), la_log_record_process(), ldr_assign_all_perm_oids(), ldr_collection_db_collection(), ldr_exec_query_from_file(), ldr_finish_context(), ldr_init(), ldr_oid_elem(), ldr_update_statistics(), list_add(), loaddb_internal(), lob_length(), lob_to_bit_char(), locator_add_or_remove_index_internal(), locator_all_reference_lockset(), locator_assign_oidset(), locator_assign_permanent_oid(), locator_attribute_info_force(), locator_cache_have_object(), locator_cache_not_have_object(), locator_cache_object_class(), locator_cache_object_instance(), locator_check_btree_entries(), locator_check_class_on_heap(), locator_check_primary_key_delete(), locator_check_primary_key_update(), locator_check_unique_btree_entries(), locator_delete_force_internal(), locator_filter_errid(), locator_find_class_by_oid(), locator_flush_class(), locator_force_for_multi_update(), locator_fun_get_all_mops(), locator_guess_sub_classes(), locator_insert_force(), locator_internal_flush_instance(), locator_is_class(), locator_lock(), locator_lock_and_doesexist(), locator_lock_and_get_object_with_evaluation(), locator_lock_class_of_instance(), locator_lock_nested(), locator_lock_set(), locator_lockhint_classes(), locator_move_record(), locator_repl_force(), locator_repl_prepare_force(), locator_update_force(), locator_update_index(), lock_demote_class_lock(), lock_scan(), lock_subclasses_internal(), lockhint_subclasses(), log_active_log_header_start_scan(), log_archive_log_header_start_scan(), log_does_active_user_exist(), cubload::error_handler::log_error_message(), log_get_charset_from_header_page(), log_get_io_page_size(), log_recovery_analysis(), log_rv_redo_fix_page(), logpb_background_archiving(), logpb_backup(), logpb_delete(), logpb_restore(), logpb_write_page_to_disk(), logpb_writev_append_pages(), logtb_create_unique_stats_from_repr(), logtb_descriptors_start_scan(), logtb_get_pack_tran_table(), make_cst_item_value(), method_invoke_for_server(), method_receive_results_for_stand_alone(), method_send_error_to_server(), ml_add(), ml_append(), ml_ext_add(), mq_evaluate_check_option(), mq_get_attribute(), mq_get_expression(), mq_is_union_translation(), mq_update_attribute(), mr_getmem_bit(), mr_getmem_char(), mr_getmem_multiset(), mr_getmem_nchar(), mr_getmem_object(), mr_getmem_sequence(), mr_getmem_set(), mr_getmem_string(), mr_getmem_varbit(), mr_getmem_varnchar(), mr_setmem_elo(), mr_setmem_string(), mr_setmem_varbit(), mr_setmem_varnchar(), mr_setval_bit(), mr_setval_char(), mr_setval_enumeration(), mr_setval_midxkey(), mr_setval_nchar(), mr_setval_set_internal(), mr_setval_string(), mr_setval_varbit(), mr_setval_varnchar(), need_to_abort_tran(), net_client_ping_server_with_handshake(), net_client_request_with_callback(), net_server_start(), nlist_add(), nlist_append(), number_to_char(), numeric_coerce_num_to_num(), numeric_coerce_string_to_num(), numeric_db_value_add(), numeric_db_value_coerce_from_num(), numeric_db_value_coerce_to_num(), numeric_db_value_div(), numeric_db_value_mul(), numeric_db_value_sub(), obj_desc_get(), obj_desc_set(), obj_get_att(), obj_set_att(), obj_set_shared(), object_to_trigger(), obt_apply_assignments(), obt_area_init(), obt_assign(), obt_assign_obt(), obt_desc_set(), obt_final_check(), obt_populate_known_arguments(), obt_set(), obt_update_internal(), or_abort(), or_get_hierarchy_helper(), or_mvcc_add_header(), or_mvcc_get_header(), or_mvcc_set_header(), overflow_delete_internal(), overflow_flush_internal(), overflow_get_capacity(), parser_generate_do_stmt_xasl(), parser_generate_xasl_post(), parser_generate_xasl_pre(), pgbuf_allocate_bcb(), pgbuf_claim_bcb_for_fix(), pgbuf_copy_from_area(), pgbuf_copy_to_area(), pgbuf_fix_with_retry(), pgbuf_ordered_fix_debug(), pgbuf_start_scan(), populate_auto_increment(), populate_defaults(), pr_area_init(), pr_midxkey_unique_prefix(), prepare_and_execute_query(), cubload::server_object_loader::process_collection_constant(), cubload::sa_object_loader::process_line(), process_object(), pt_associate_label_with_value(), pt_bind_name_or_path_in_scope(), pt_bind_parameter(), pt_check_access_status(), pt_check_alter_partition(), pt_check_create_entity(), pt_check_method(), pt_check_with_info(), pt_class_pre_fetch(), pt_coerce_value_internal(), pt_copy_upddel_hints_to_select(), pt_end_query(), pt_eval_method_call_type(), pt_evaluate_db_value_expr(), pt_evaluate_tree_internal(), pt_exec_trigger_stmt(), pt_find_attr_in_class_list(), pt_find_class_attribute(), pt_find_value_of_label(), pt_get_select_query_columns(), pt_help_show_create_table(), pt_node_to_db_domain(), pt_node_to_partition_info(), pt_report_to_ersys(), pt_report_to_ersys_with_statement(), pt_resolve_method_type(), pt_resolve_using_index(), pt_to_delete_xasl(), pt_to_merge_insert_xasl(), pt_to_merge_update_xasl(), pt_to_merge_xasl(), pt_to_odku_info(), pt_to_regu_variable(), pt_to_update_xasl(), pt_validate_query_spec(), px_sort_myself(), qdata_evaluate_aggregate_list(), qdata_evaluate_analytic_func(), qdata_list_dbs(), qexec_add_composite_lock(), qexec_alloc_agg_hash_context(), qexec_analytic_add_tuple(), qexec_analytic_evaluate_interpolation_function(), qexec_analytic_put_next(), qexec_analytic_start_group(), qexec_create_internal_classes(), qexec_end_one_iteration(), qexec_evaluate_aggregates_optimize(), qexec_execute_build_columns(), qexec_execute_build_indexes(), qexec_execute_duplicate_key_update(), qexec_execute_insert(), qexec_execute_mainblock_internal(), qexec_execute_obj_fetch(), qexec_execute_query(), qexec_execute_selupd_list(), qexec_execute_selupd_list_find_class(), qexec_for_update_set_class_locks(), qexec_gby_agg_tuple(), qexec_gby_put_next(), qexec_gby_start_group(), qexec_groupby(), qexec_hash_gby_agg_tuple(), qexec_oid_of_duplicate_key_update(), qexec_ordby_put_next(), qexec_remove_duplicates_for_replace(), qexec_set_class_locks(), qexec_upddel_add_unique_oid_to_ehid(), qfile_put_next_sort_item(), qmgr_get_new_page(), qmgr_set_query_error(), qo_rewrite_like_for_index_scan(), qstr_bit_coerce(), qstr_bit_concatenate(), qstr_bit_position(), qstr_bit_substring(), qstr_coerce(), qstr_concatenate(), qstr_grow_string(), qstr_pad(), qstr_substring(), qstr_translate(), qstr_trim(), realloc_instance_table(), remove_deferred_context(), res_delete_row_internal(), res_fetch_internal(), rs_set_db_value(), sbtree_add_index(), sbtree_get_key_type(), scan_dbvals_to_midxkey(), scan_get_index_oidset(), scan_next_heap_scan(), scan_next_index_lookup_heap(), scan_open_index_key_info_scan(), scan_open_index_scan(), scan_start_scan(), sch_trigger(), select_delete_list(), serial_update_cur_val_of_serial(), set_area_init(), set_get_setobj(), set_host_variables(), set_op(), set_server_error(), set_sqlca_err(), set_tform_disk_set(), setobj_sort(), setof_mop_to_setof_vobj(), showstmt_array_end_scan(), signal_evaluation_error(), sloaddb_destroy(), sloaddb_fetch_status(), sloaddb_install_class(), sloaddb_load_batch(), sloaddb_update_stats(), slocator_check_fk_validity(), sm_build_function_nlist(), sm_check_catalog_rep_dir(), sm_class_check_uniques(), sm_class_has_triggers(), sm_delete_class_mop(), sm_drop_cascade_foreign_key(), sm_drop_constraint(), sm_drop_index(), sm_dynamic_link_class(), sm_exist_index(), sm_expand_method_files(), sm_flush_for_multi_update(), sm_force_write_all_classes(), sm_free_function_nlist(), sm_get_attribute_descriptor(), sm_get_class_repid(), sm_get_descriptor_component(), sm_get_method_descriptor(), sm_get_trigger_cache(), sm_is_subclass(), sm_link_static_method(), sm_prelink_methods(), sm_rename_class(), sm_save_constraint_info(), sm_set_class_comment(), sm_split_loader_commands(), sm_touch_class(), sm_truncate_class(), sm_truncate_using_delete(), sm_update_all_statistics(), sm_update_catalog_statistics(), sm_update_statistics(), sm_virtual_queries(), smt_add_attribute_any(), smt_add_method_file(), smt_add_query_spec(), smt_add_set_attribute_domain(), smt_change_attribute(), smt_change_query_spec(), smt_drop_constraint(), smt_rename_any(), smt_rename_method_file(), smt_set_attribute_default(), sort_exphase_merge(), sort_exphase_merge_elim_dup(), sort_inphase_sort(), spage_header_start_scan(), spage_slots_start_scan(), sprm_server_get_force_parameters(), sqmgr_prepare_and_execute_query(), sserial_get_current_value(), stats_update_partitioned_statistics(), stmt_bind_pmeta_handle(), sysprm_set_error(), tde_cipher_initialize(), tde_copy_keys_file(), tde_initialize(), tf_add_fixup(), tf_attribute_default_expr_to_property(), tf_mem_to_disk(), tf_need_permanent_oid(), cubload::to_db_elo_ext(), cubload::to_db_varbit_from_bin_str(), cubload::to_db_varbit_from_hex_str(), tp_domain_check_class(), tp_domain_status_er_set(), tp_init(), tp_value_cast_internal(), tr_create_trigger(), tr_drop_cache_trigger(), tr_drop_trigger(), tr_prepare_class(), tr_prepare_statement(), tr_set_comment(), tr_status_as_string(), tr_update_user_cache(), tr_validate_schema_cache(), tran_2pc_attach_global_tran(), tran_2pc_prepare(), tran_2pc_prepare_global_tran(), tran_add_savepoint(), tran_get_global_tran_info(), tran_internal_abort_upto_savepoint(), tran_savepoint_internal(), tran_set_global_tran_info(), trigger_table_add(), trigger_table_rename(), truncate_class_name(), tz_full_timezones_start_scan(), tz_load(), tz_load_with_library_path(), tz_timezones_start_scan(), tzc_compute_timezone_checksum(), uci_execute_immediate(), uci_open_cs(), uci_prepare(), uci_static(), unpack_domain(), update_at_server(), update_cache(), update_class(), update_class_attributes(), update_fk_ref_partitioned_class(), update_foreign_key_ref(), update_locksets_for_multiple_rename(), update_object_by_oid(), update_object_tuple(), update_objs_for_list_file(), update_real_class(), vacuum_finished_block_vacuum(), validate_trigger(), values_list_to_values_array(), vid_att_in_obj_id(), vid_build_non_upd_object(), vid_encode_object(), vid_flush_and_rehash(), vid_make_vobj(), vid_vobj_to_object(), ws_abort_transaction(), ws_add_label_value_to_mop(), ws_area_init(), ws_dirty(), ws_init(), xboot_emergency_patch(), xboot_initialize_server(), xboot_restart_from_backup(), xbtree_delete_index(), xbtree_load_online_index(), xcatalog_check_rep_dir(), xheap_get_class_num_objects_pages(), xheap_reclaim_addresses(), xlocator_check_fk_validity(), xlocator_fetch(), xlocator_fetch_all(), xlocator_fetch_lockset(), xlocator_force(), xlocator_remove_class_from_index(), xlocator_repl_force(), xqfile_get_list_file_page(), xserial_get_current_value_internal(), xserial_get_next_value(), xserial_get_next_value_internal(), and xstats_update_statistics().
int er_errid_if_has_error (void)
Definition at line 1846 of file error_manager.c.
References er_is_error_severity(), cuberr::er_message::err_id, NO_ERROR, and cuberr::er_message::severity.
Referenced by do_create_partition(), heap_stats_find_page_in_bestspace(), cubload::session::install_class(), mq_substitute_subquery_list_in_statement(), mq_translate_tree(), and pgbuf_ordered_fix_debug().
static size_t er_estimate_size (ER_FMT * fmt, va_list * ap) static
Definition at line 2630 of file error_manager.c.
References ARG_FILE_LINE, er_spec::code, ER_ER_SUBSTITUTE_MSG, er_log_debug, ER_LOG_UNKNOWN_CODE, er_fmt::fmt, er_fmt::fmt_length, i, MAX_DOUBLE_WIDTH, MAX_INT_WIDTH, er_fmt::nspecs, NULL, er_fmt::spec, SPEC_CODE_LONGLONG, SPEC_CODE_SIZE_T, strlen, and er_spec::width.
Referenced by er_set_internal().
static void er_event (void) static
Definition at line 404 of file error_manager.c.
References ARG_FILE_LINE, er_all(), ER_ERROR_SEVERITY, ER_EV_BROKEN_PIPE, er_event_sigpipe_handler(), er_set(), ER_SEVERITY_STRING, er_copy_area::err_id, NULL, os_set_signal_handler(), prm_get_string_value(), PRM_ID_EVENT_HANDLER, and er_copy_area::severity.
Referenced by er_notify_event_on_error().
static void er_event_final (void) static
Definition at line 521 of file error_manager.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_EV_BROKEN_PIPE, ER_EV_STOPPED, er_event_sigpipe_handler(), ER_NOTIFICATION_SEVERITY, er_set(), ER_SEVERITY_STRING, MSGCAT_CATALOG_CUBRID, msgcat_message(), MSGCAT_SET_ERROR, NULL, os_set_signal_handler(), prm_get_string_value(), and PRM_ID_EVENT_HANDLER.
Referenced by er_final().
static int er_event_init (void) static
Definition at line 447 of file error_manager.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_EV_BROKEN_PIPE, ER_EV_CONNECT_HANDLER, ER_EV_STARTED, ER_EV_STOPPED, er_event_sigpipe_handler(), ER_NOTIFICATION_SEVERITY, er_set(), ER_SEVERITY_STRING, error(), MSGCAT_CATALOG_CUBRID, msgcat_message(), MSGCAT_SET_ERROR, NO_ERROR, NULL, os_set_signal_handler(), prm_get_string_value(), and PRM_ID_EVENT_HANDLER.
Referenced by er_init().
static void er_event_sigpipe_handler (int sig) static
Definition at line 394 of file error_manager.c.
Referenced by er_event(), er_event_final(), and er_event_init().
static FILE * er_file_backup (FILE * fp, const char * path) static
Definition at line 1064 of file error_manager.c.
References assert, boot_db_name(), cub_dirname_r(), db_name, NULL, and PATH_SEPARATOR.
Referenced by er_file_open(), and er_log().
static bool er_file_isa_null_device (const char * path) static
Definition at line 1045 of file error_manager.c.
References NULL.
Referenced by er_init().
static FILE * er_file_open (const char * path) static
Definition at line 998 of file error_manager.c.
References assert, cub_dirname_r(), er_file_backup(), free_and_init, NULL, prm_get_integer_value(), PRM_ID_ER_LOG_SIZE, and strdup().
Referenced by er_init(), and er_log().
void er_final (ER_FINAL_CODE do_global_final)
Definition at line 1126 of file error_manager.c.
References cuberr::context::deregister_thread_local(), er_Accesslog_fh, ER_ALL_FINAL, er_Builtin_msg, er_call_stack_final(), er_clear_fmt(), er_event_final(), er_Fmt_list, er_Log_file_mutex, er_Msglog_fh, er_Singleton_context_p, free_and_init, i, and NULL.
Referenced by boot_client_all_finalize(), boot_server_all_finalize(), cas_final(), cas_main(), copydb(), csql(), css_process_kill_master(), deletedb(), er_init(), er_log(), gen_tz(), main(), net_server_start(), patchdb(), server_monitor_thr_f(), and cubthread::manager::~manager().
static ER_FMT * er_find_fmt (int err_id, int num_args) static
Definition at line 2723 of file error_manager.c.
References ARG_FILE_LINE, assert, er_create_fmt_msg(), ER_ER_LOG_MISSING_MSG, ER_ER_MISSING_MSG, ER_ER_SUBSTITUTE_MSG, ER_FAILED, er_Fmt_list, er_internal_msg(), ER_LAST_ERROR, er_log_debug, ER_LOG_SUSPECT_FMT, er_Message_cache_mutex, er_copy_area::err_id, er_fmt::fmt, MSGCAT_CATALOG_CUBRID, msgcat_message(), MSGCAT_SET_ERROR, er_fmt::nspecs, and NULL.
Referenced by er_set_internal().
static int er_fname_free (const void * key, void * data, void * args) static
Definition at line 605 of file error_manager.c.
References ER_ACCESS_LOG_FILE_SUFFIX, er_Accesslog_filename_buff, ER_MSG_LOG_FILE_SUFFIX, NO_ERROR, NULL, and strlen.
Referenced by er_call_stack_final().
char* er_get_area_error (char * buffer, int * length)
Definition at line 2086 of file error_manager.c.
References assert, ASSERT_ALIGN, cuberr::er_message::err_id, INT_ALIGNMENT, cuberr::er_message::msg_area, OR_INT_SIZE, OR_PUT_INT, cuberr::er_message::severity, and strlen.
Referenced by css_refuse_connection_request(), return_error_to_client(), return_error_to_server(), and showstmt_array_end_scan().
char* er_get_ermsg_from_area_error (char * buffer)
Definition at line 2071 of file error_manager.c.
References assert, NULL, and OR_INT_SIZE.
Referenced by showstmt_array_end_scan().
const char* er_get_msglog_filename (void)
Definition at line 385 of file error_manager.c.
References er_Msglog_filename.
Referenced by backupdb(), checkdb(), logpb_fatal_error_internal(), tde_create_keys_file(), vacuumdb(), xboot_initialize_server(), and xboot_unregister_client().
int er_get_severity (void)
Definition at line 1901 of file error_manager.c.
Referenced by do_create_entity(), er_filter_errid(), cubload::error_handler::log_error_message(), log_rv_redo_fix_page(), and pt_check_create_entity().
bool er_has_error (void)
Definition at line 1912 of file error_manager.c.
References er_is_error_severity(), and er_copy_area::severity.
Referenced by cubload::load_task::execute(), cubload::server_object_loader::flush_records(), cubload::session::install_class(), jsp_start_server(), cubload::error_handler::log_error_message(), main(), mq_is_union_translation(), mq_push_paths(), mq_rewrite_vclass_spec_as_derived(), mq_translate_select(), print_er_msg(), qdata_finalize_aggregate_list(), sloaddb_destroy(), sloaddb_fetch_status(), sloaddb_install_class(), sloaddb_load_batch(), sloaddb_update_stats(), and sm_virtual_queries().
int er_init (const char * msglog_filename, int exit_ask)
Definition at line 678 of file error_manager.c.
References ARG_FILE_LINE, assert, envvar_logdir_file(), ER_ABORT, ER_ACCESS_LOG_FILE_SUFFIX, er_Accesslog_filename, ER_ALL_FINAL, er_Builtin_msg, er_call_stack_init(), er_create_fmt_msg(), er_emergency(), ER_ER_NO_CATALOG, ER_EVENT_HANDLER, er_event_init(), ER_EXIT_ASK, ER_EXIT_DEFAULT, ER_EXIT_DONT_ASK, ER_FAILED, er_file_isa_null_device(), er_file_open(), er_final(), er_Fmt_list, er_init_fmt(), ER_LAST_ERROR, ER_LOG_ASK_VALUE, er_log_debug, er_Log_file_mutex, ER_LOG_MSGLOG_WARNING, ER_MSG_LOG_FILE_SUFFIX, er_Msglog_filename, er_Msglog_filename_buff, ER_NEVER_EXIT, free_and_init, i, IS_ABS_PATH, MSGCAT_CATALOG_CUBRID, msgcat_get_descriptor(), msgcat_gets(), msgcat_init(), msgcat_message(), MSGCAT_SET_ERROR, MSGCAT_SET_INTERNAL, NO_ERROR, NULL, PATH_CURRENT, prm_get_bool_value(), prm_get_string_value(), PRM_ID_ER_LOG_FILE, PRM_ID_ER_PRODUCTION_MODE, PRM_ID_EVENT_HANDLER, cuberr::context::register_thread_local(), and strlen.
Referenced by acldb(), addvoldb(), alterdbhost(), applyinfo(), applylogdb(), backupdb(), boot_restart_client(), boot_restart_server(), boot_shutdown_client_at_exit(), cas_main(), changemode(), checkdb(), checksumdb(), copydb(), copylogdb(), createdb(), csql(), csql_do_session_cmd(), db_error_init(), deletedb(), diagdb(), gen_tz(), genlocale(), installdb(), killtran(), loaddb_internal(), lockdb(), main(), cubthread::manager::manager(), net_server_start(), optimizedb(), paramdump(), patchdb(), plandump(), renamedb(), restoredb(), restoreslave(), server_monitor_thr_f(), spacedb(), statdump(), synccolldb(), tde(), tranlist(), unloaddb(), utility_initialize(), and vacuumdb().
static void er_init_fmt (ER_FMT * fmt) static
Definition at line 2819 of file error_manager.c.
References er_fmt::err_id, er_fmt::fmt, er_fmt::fmt_length, er_fmt::must_free, er_fmt::nspecs, NULL, er_fmt::spec, er_fmt::spec_buf, and er_fmt::spec_top.
Referenced by er_init().
static void er_internal_msg (ER_FMT * fmt, int code, int msg_num) static
Definition at line 2863 of file error_manager.c.
References er_clear_fmt(), er_fmt::err_id, er_fmt::fmt, er_fmt::fmt_length, er_fmt::must_free, and strlen.
Referenced by er_create_fmt_msg(), er_find_fmt(), and er_study_fmt().
static bool er_is_error_severity (er_severity severity) static
Definition at line 3219 of file error_manager.c.
References assert, ER_ERROR_SEVERITY, ER_FATAL_ERROR_SEVERITY, ER_NOTIFICATION_SEVERITY, ER_SYNTAX_ERROR_SEVERITY, and ER_WARNING_SEVERITY.
Referenced by er_errid_if_has_error(), and er_has_error().
bool er_is_initialized (void)
Definition at line 976 of file error_manager.c.
References er_Hasalready_initiated.
Referenced by boot_shutdown_client_at_exit(), and er_clear().
void er_log (int err_id) static
Definition at line 1596 of file error_manager.c.
References ARG_FILE_LINE, CUB_MAXHOSTNAMELEN, ER_ABORT, ER_ACCESS_LOG_FILE_SUFFIX, er_Accesslog_fh, er_Accesslog_filename, er_all(), ER_ALL_FINAL, ER_BO_CLIENT_CONNECTED, er_Eid, ER_ER_EXIT, ER_ERROR_WARNING_STRING, ER_EXIT_ASK, ER_EXIT_DONT_ASK, ER_FATAL_ERROR_SEVERITY, er_file_backup(), er_file_open(), er_final(), er_log_debug, ER_LOG_LAST_MSG, ER_LOG_MSG_WRAPPER_D, ER_LOG_MSGLOG_WARNING, ER_LOG_WRAPAROUND, ER_MSG_LOG_FILE_SUFFIX, er_Msglog_fh, er_Msglog_filename, ER_NEVER_EXIT, ER_SEVERITY_STRING, er_stop_on_error(), NO_ERROR, NULL, pid, prm_get_integer_value(), PRM_ID_ER_LOG_SIZE, prog_name, er_copy_area::severity, and TM_TRAN_INDEX.
Referenced by er_emergency().
static void * er_malloc_helper (std::size_t size, const char * file, int line) static
Definition at line 2881 of file error_manager.c.
References er_emergency(), ER_ER_OUT_OF_MEMORY, and NULL.
const char* er_msg (void)
Definition at line 1926 of file error_manager.c.
References assert, ER_ER_MISSING_MSG, cuberr::er_message::msg_area, and cuberr::er_message::msg_area_size.
Referenced by apply_tailoring_rules(), boot_restart_server(), copy_node_in_tree_pre(), db_error_string(), object_printer::describe_class(), do_alter_change_col_comment(), do_alter_change_default_cs_coll(), do_alter_change_tbl_comment(), do_alter_clause_change_attribute(), do_alter_one_clause_with_template(), do_execute_merge(), do_execute_update(), do_merge(), do_prepare_delete(), do_prepare_merge(), do_prepare_update(), do_update(), er_all(), fileio_continue_restore(), fileio_get_next_backup_volume(), fileio_initialize_restore(), la_apply_delete_log(), la_apply_insert_log(), la_apply_statement_log(), la_apply_update_log(), cubload::error_handler::log_error_message(), logpb_fatal_error_internal(), logpb_fetch_from_archive(), main(), mq_fetch_select_for_real_class_update(), mq_is_union_translation(), mq_push_paths(), mq_replace_virtual_oid_with_real_oid(), mq_translate_select(), net_server_start(), cubload::error_handler::on_syntax_failure(), print_er_msg(), pt_bind_name_or_path_in_scope(), pt_check_access_status(), pt_check_alter(), pt_check_alter_partition(), pt_check_attribute_domain(), pt_check_create_entity(), pt_check_create_index(), pt_check_defaultf(), pt_check_partition_values(), pt_check_show_index(), pt_check_table_in_show_heap(), pt_evaluate_db_value_expr(), pt_evaluate_function_w_args(), pt_evaluate_tree_internal(), pt_find_attr_in_class_list(), pt_find_class_attribute(), pt_flush_classes(), pt_fold_const_expr(), pt_help_show_create_table(), pt_make_class_access_spec(), pt_make_subclass_list(), pt_no_double_insert_assignments(), pt_print_node_value(), pt_resolve_partition_spec(), pt_resolve_using_index(), pt_resolve_vclass_args(), pt_semantic_check_local(), pt_set_class_chn(), pt_set_host_variables(), pt_to_delete_xasl(), pt_to_insert_xasl(), pt_to_regu_variable(), pt_xasl_node_to_domain(), qmgr_free_list_temp_file(), qmgr_set_query_error(), qo_to_xasl(), set_sqlca_err(), signal_evaluation_error(), tr_check_correlation(), tran_savepoint_internal(), xboot_emergency_patch(), and xlocator_repl_force().
static void er_notify_event_on_error (int err_id) static
Definition at line 1300 of file error_manager.c.
References assert, er_event(), NO_ERROR, PRM_ID_EVENT_ACTIVATION, and sysprm_find_err_in_integer_list().
Referenced by er_set_internal().
void er_print_callstack (const char * file_name, const int line_no, const char * fmt, ...)
Definition at line 1322 of file error_manager.c.
References _er_log_debug_internal(), er_dump_call_stack(), er_Log_file_mutex, and NULL.
Referenced by boot_server_die_or_changed(), fi_handler_random_exit(), JSON_PRIVATE_ALLOCATOR::Malloc(), pwrite_with_injected_fault(), qexec_execute_query(), qfile_update_qlist_count(), JSON_PRIVATE_ALLOCATOR::Realloc(), cubthread::wp_handle_system_error(), ws_cache(), ws_clear_hints(), ws_decache(), and ws_set_lock().
er_log_handler_t er_register_log_handler (er_log_handler_t handler)
Definition at line 1795 of file error_manager.c.
References assert, er_Handler, and NULL.
Referenced by db_register_error_log_handler().
void er_restore_last_error (void)
Definition at line 2300 of file error_manager.c.
References er_stack_pop_and_keep_error(), and cuberr::context::has_error_stack().
void er_set (int severity, const char * file_name, const int line_no, int err_id, int num_args, ...)
Definition at line 1228 of file error_manager.c.
References er_set_internal(), and NULL.
Referenced by acquire_locks_for_multiple_rename(), add_class_object(), add_deferred_activity_context(), add_element(), add_foreign_key(), add_local_subquery(), add_using_index(), adjust_partition_range(), adjust_partition_size(), allocate_disk_structures(), allocate_foreign_key(), allocate_index(), allocate_query_result(), allocate_unique_constraint(), alterdbhost(), area_alloc_block(), area_alloc_blockset(), area_create(), area_find_block(), area_free(), area_init(), area_validate(), assign_set_value(), attribute_to_disk(), au_add_member_internal(), au_add_member_method(), au_add_user(), au_add_user_method(), au_change_owner(), au_change_owner_method(), au_change_serial_owner(), au_change_serial_owner_method(), au_change_sp_owner(), au_change_sp_owner_method(), au_change_trigger_owner(), au_change_trigger_owner_method(), au_check_authorization_method(), au_check_serial_authorization(), au_check_user(), au_drop_member(), au_drop_member_method(), au_drop_user(), au_drop_user_method(), au_export_grants(), au_export_users(), au_fetch_class_internal(), au_fetch_instance(), au_find_user(), au_find_user_cache_index(), au_find_user_method(), au_find_user_to_drop(), au_force_write_new_auth(), au_get_new_auth(), au_get_owner_method(), au_grant(), au_login(), au_login_method(), au_make_class_cache(), au_make_user(), au_perform_login(), au_revoke(), au_set_new_auth(), au_set_password_encoded_method(), au_set_password_encoded_sha1_method(), au_set_password_internal(), au_set_password_method(), au_set_user_comment(), au_start(), au_user_name(), backupdb(), bf2df_str_cmpdisk(), bh_add(), bh_create(), bh_insert(), bitset_extend(), boot_add_volume_extension(), boot_backup(), boot_change_ha_mode(), boot_check_db_consistency(), boot_check_permanent_volumes(), boot_client_all_finalize(), boot_client_find_and_cache_class_oids(), boot_compact_classes(), boot_copy(), boot_delete(), boot_emergency_patch(), boot_find_new_db_path(), boot_find_rest_permanent_volumes(), boot_get_new_volume_name_and_id(), boot_get_server_locales(), boot_initialize_client(), boot_mount(), boot_notify_ha_log_applier_state(), boot_parse_add_volume_extensions(), boot_remove_all_volumes(), boot_remove_temp_volume(), boot_remove_unknown_temp_volumes(), boot_reset_mk_after_restart_from_backup(), boot_restart_client(), boot_restart_server(), boot_server_status(), boot_shutdown_server(), boot_soft_rename(), boot_volume_info_log_path(), btree_add_index(), btree_build_nleafs(), btree_check_by_class_oid(), btree_check_foreign_key(), btree_check_page_key(), btree_coerce_key(), btree_compare_key(), btree_construct_leafs(), btree_find_multi_uniques(), btree_find_next_index_record_holding_current_helper(), btree_find_unique(), btree_fk_object_does_exist(), btree_get_next_key_info(), btree_get_next_node_info(), btree_get_pkey_btid(), btree_ils_adjust_range(), btree_index_next_scan(), btree_index_start_scan(), btree_iss_set_key(), btree_key_find_and_lock_unique_of_unique(), btree_key_lock_and_append_object_unique(), btree_keyoid_checkscan_start(), btree_load_check_fk(), btree_load_index(), btree_load_overflow_key(), btree_pack_root_header(), btree_prepare_bts(), btree_range_opt_check_add_index_key(), btree_record_satisfies_snapshot(), btree_repair_prev_link_by_btid(), btree_rv_nodehdr_redo_insert(), btree_rv_nodehdr_undoredo_update(), btree_rv_noderec_redo_insert(), btree_rv_noderec_undoredo_update(), btree_rv_ovfid_undoredo_update(), btree_rv_pagerec_insert(), btree_rv_redo_global_unique_stats_commit(), btree_rv_roothdr_undo_update(), btree_rv_undo_global_unique_stats_commit(), btree_rv_update_tran_stats(), btree_scan_update_range(), btree_set_error(), btree_set_unknown_key_error(), btree_sort_get_next(), btree_store_overflow_key(), btree_verify_subtree(), build_attr_change_map(), build_class_grant_list(), mvcctable::build_mvcc_info(), build_query_graph_function_index(), call_method(), JSON_DUPLICATE_KEYS_CHECKER::CallBefore(), catalog_add_class_info(), catalog_add_representation(), catalog_check_class_consistency(), catalog_drop_all(), catalog_drop_all_representation_and_class(), catalog_drop_old_representations(), catalog_drop_representation_class_from_page(), catalog_drop_representation_item(), catalog_get_cardinality(), catalog_get_cardinality_by_name(), catalog_get_representation(), catalog_get_representation_directory(), catalog_get_representation_item(), catalog_get_representation_record(), catalog_initialize_new_page(), catalog_insert(), catalog_reclaim_space(), catalog_rv_insert_redo(), catalog_rv_new_page_redo(), catalog_start_access_with_dir_oid(), catalog_update(), catcls_allocate_entry(), catcls_allocate_or_value(), catcls_convert_attr_id_to_name(), catcls_delete_catalog_classes(), catcls_find_btid_of_class_name(), catcls_find_class_oid_by_class_name(), catcls_get_apply_info_log_record_time(), catcls_get_db_collation(), catcls_get_or_value_from_attribute(), catcls_get_or_value_from_attrid(), catcls_get_or_value_from_buffer(), catcls_get_or_value_from_class(), catcls_get_or_value_from_domain(), catcls_get_or_value_from_indexes(), catcls_get_or_value_from_method(), catcls_get_or_value_from_method_argument(), catcls_get_or_value_from_method_file(), catcls_get_or_value_from_method_signiture(), catcls_get_or_value_from_partition(), catcls_get_or_value_from_query_spec(), catcls_get_or_value_from_resolution(), catcls_get_server_compat_info(), catcls_insert_instance(), catcls_put_or_value_into_buffer(), catcls_update_instance(), cfg_copy_hosts(), cfg_find_db(), cfg_read_directory(), cfg_read_directory_ex(), change_constraints_comment_partitioned_class(), change_constraints_status_partitioned_class(), check_args(), check_att_chg_allowed(), check_att_domain(), check_authorization(), check_change_attribute(), check_class_domain(), check_fk_validity(), check_grant_option(), check_merge_xasl(), check_missing_non_null_attrs(), check_object_domain(), check_semantics(), check_server_capabilities(), check_target(), check_timezone_compat(), check_trigger(), chksum_calculate_checksum(), chksum_get_next_lower_bound(), chksum_get_prev_checksum_results(), chksum_init_checksum_tables(), chksum_insert_repl_log_and_demote_table_lock(), chksum_report(), chksum_start(), chksum_update_master_checksum(), class_to_disk(), classobj_btid_from_property_value(), classobj_change_constraint_comment(), classobj_change_constraint_status(), classobj_check_function_constraint_info(), classobj_copy_attribute_like(), classobj_copy_constraint_like(), classobj_copy_default_expr(), classobj_copy_partition_info(), classobj_copy_props(), classobj_drop_foreign_key_ref(), classobj_drop_prop(), classobj_find_prop_constraint(), classobj_get_prop(), classobj_make_class_constraints(), classobj_make_descriptor(), classobj_make_function_index_info(), classobj_make_function_index_info_seq(), classobj_make_index_filter_pred_info(), classobj_make_template_like(), classobj_map_constraint_to_property(), classobj_oid_from_property_value(), classobj_point_at_att_names(), classobj_populate_class_properties(), classobj_put_foreign_key_ref(), classobj_put_index(), classobj_put_prop(), clogin_user(), col_new(), collect_class_grants(), collect_hier_class_info(), compactdb_start(), compare_size_and_buffer(), cubregex::compile(), compile_partition_expression(), compile_trigger_activity(), conv_tz(), copy_bind_value_to_tdes(), cubregex::count(), create_or_drop_index_helper(), crypt_default_decrypt(), crypt_default_encrypt(), crypt_generate_random_bytes(), crypt_md5_buffer_binary(), crypt_sha_functions(), csect_demote_critical_section(), csect_enter_critical_section(), csect_enter_critical_section_as_reader(), csect_exit_critical_section(), csect_promote_critical_section(), csession_create_prepared_statement(), csession_delete_prepared_statement(), csession_drop_session_variables(), csession_find_or_create_session(), csession_get_prepared_statement(), csession_get_variable(), csession_set_session_variables(), csql_get_session_cmd_no(), css_accept(), css_add_client_version_string(), css_change_ha_server_state(), css_check_ha_server_state_for_client(), css_connect_to_master_server(), css_get_request_id(), css_get_session_ids_for_active_connections(), css_gethostid(), css_gethostname(), css_hostname_to_ip(), css_init(), css_init_conn_list(), css_is_shutdown_timeout_expired(), css_make_entry_id(), css_master_thread(), css_net_recv(), css_notify_ha_log_applier_state(), css_open_server_connection_socket(), css_pack_server_name(), css_process_change_server_ha_mode_request(), css_process_new_client(), css_register_server_timeout_fn(), css_send_reply_and_data_to_client(), css_tcp_client_open_with_retry(), css_tcp_master_open(), css_transit_ha_server_state(), css_user_access_status_start_scan(), css_windows_startup(), cursor_get_tuple_value(), cursor_next_tuple(), cursor_peek_tuple(), cursor_prev_tuple(), date_to_char(), db_2pc_prepared_transactions(), db_abs_dbval(), db_acos_dbval(), db_add_days_to_year(), db_add_int_to_datetime(), db_add_months(), db_add_time(), db_add_volume_ex(), db_alloc_query_format(), db_alloc_query_result(), db_ascii(), db_asin_dbval(), db_attdesc_domain(), db_bigint_to_binary_string(), db_bit_count_dbval(), db_bit_string_coerce(), db_bit_to_blob(), db_blob_from_file(), db_blob_length(), db_blob_to_bit(), db_ceil_dbval(), db_char_string_coerce(), db_char_to_blob(), db_char_to_clob(), db_clob_from_file(), db_clob_length(), db_clob_to_char(), db_compile_statement_local(), db_compress_like_pattern(), db_constrain_non_null(), db_conv(), db_conv_tz(), db_convert_sec_to_time(), db_convert_time_to_sec(), db_convert_to_time(), db_cp_query_type(), db_cp_query_type_helper(), db_crc32_dbval(), db_create_by_name(), db_create_vclass(), db_date_add_sub_interval_days(), db_date_add_sub_interval_expr(), db_date_dbval(), db_date_diff(), db_date_encode(), db_date_format(), db_date_parse_date(), db_date_parse_datetime_parts(), db_date_parse_time(), db_date_parse_timestamp(), db_dfind_multi_unique(), db_elo_read(), db_elo_write(), db_enum_put_cs_and_collation(), db_evaluate_json_array_append(), db_evaluate_json_array_insert(), db_evaluate_json_get_all_paths(), db_evaluate_json_insert(), db_evaluate_json_keys(), db_evaluate_json_object(), db_evaluate_json_remove(), db_evaluate_json_replace(), db_evaluate_json_search(), db_evaluate_json_set(), db_execute_and_keep_statement_local(), db_execute_oid(), db_execute_statement_local(), db_exp_dbval(), db_fetch_composition(), db_find_class_of_index(), db_find_multi_unique(), db_find_primary_key(), db_find_string_in_in_set(), db_floor_dbval(), db_format(), db_from_tz(), db_from_unixtime(), db_gadget_bind(), db_gadget_create(), db_gadget_exec(), db_get_attribute(), db_get_attribute_class(), db_get_attribute_force(), db_get_attribute_type(), db_get_attributes(), db_get_attributes_force(), db_get_btree_statistics(), db_get_class_attribute(), db_get_class_attributes(), db_get_class_method(), db_get_class_methods(), db_get_class_resolutions(), db_get_constraints(), db_get_cs_coll_info(), db_get_date_dayofyear(), db_get_date_format(), db_get_date_item(), db_get_date_quarter(), db_get_date_totaldays(), db_get_date_week(), db_get_date_weekday(), db_get_global_transaction_info(), db_get_info_for_like_optimization(), db_get_input_markers(), db_get_like_optimization_bounds(), db_get_loader_commands(), db_get_method(), db_get_method_files(), db_get_methods(), db_get_next_error(), db_get_next_like_pattern_character(), db_get_next_warning(), db_get_ordered_attributes(), db_get_output_markers(), db_get_parameters(), db_get_query_result_format(), db_get_query_type_list(), db_get_resolutions(), db_get_serial_current_value(), db_get_serial_next_value_ex(), db_get_shared_attribute(), db_get_start_line(), db_get_statement_type(), db_get_subclasses(), db_get_superclasses(), db_get_time_item(), db_get_user_and_host_name(), db_guid(), db_hex(), db_inet_aton(), db_inet_ntoa(), db_init_query_result(), db_json_add_json_value_to_object(), db_json_array_insert_func(), db_json_er_set_expected_other_type(), db_json_er_set_path_does_not_exist(), db_json_extract_document_from_path(), db_json_get_json_from_str(), db_json_object_contains_key(), db_json_path_is_token_valid_array_index(), db_json_remove_func(), db_json_serialize(), db_json_split_path_by_delimiters(), db_json_unpack_array_to_value(), db_json_unpack_bigint_to_value(), db_json_unpack_bool_to_value(), db_json_unpack_double_to_value(), db_json_unpack_int_to_value(), db_json_unpack_object_to_value(), db_json_unpack_string_to_value(), db_json_validate_json(), db_last_day(), db_like_bound(), db_log_dbval(), db_log_generic_dbval(), db_mod_bigint(), db_mod_dbval(), db_mod_double(), db_mod_float(), db_mod_int(), db_mod_monetary(), db_mod_numeric(), db_mod_short(), db_new_time(), db_number_of_input_markers(), db_number_of_output_markers(), db_object_describe(), db_object_fetch(), db_open_local(), db_pack_prepare_info(), db_power_dbval(), db_private_alloc_debug(), db_private_realloc_debug(), db_private_realloc_external(), db_query_column_count(), db_query_end_internal(), db_query_first_tuple(), db_query_get_tplpos(), db_query_get_tuple_oid(), db_query_get_tuple_value(), db_query_get_tuple_value_by_name(), db_query_get_tuple_valuelist(), db_query_last_tuple(), db_query_next_tuple(), db_query_prev_tuple(), db_query_produce_updatable_result(), db_query_seek_tuple(), db_query_set_copy_tplvalue(), db_query_set_tplpos(), db_query_tuple_count(), db_restart(), db_round_dbval(), db_set_client_cache_time(), db_set_execution_plan(), db_set_global_transaction_info(), db_set_statement_auto_commit(), db_set_system_generated_statement(), db_set_system_parameters(), db_sleep(), db_sqrt_dbval(), db_str_to_date(), db_string_aes_decrypt(), db_string_aes_encrypt(), db_string_chr(), db_string_compare(), db_string_concatenate(), db_string_elt(), db_string_extract_dbval(), db_string_from_base64(), db_string_index_prefix(), db_string_insert_substring(), db_string_instr(), db_string_like(), db_string_pad(), db_string_position(), db_string_prefix_compare(), db_string_put_cs_and_collation(), db_string_regexp_count(), db_string_regexp_instr(), db_string_regexp_like(), db_string_regexp_replace(), db_string_regexp_substr(), db_string_repeat(), db_string_replace(), db_string_rlike(), db_string_sha_one(), db_string_sha_two(), db_string_space(), db_string_substring(), db_string_substring_index(), db_string_to_base64(), db_string_to_date_ex(), db_string_to_datetime_ex(), db_string_to_datetimetz_ex(), db_string_to_time_ex(), db_string_to_timestamp_ex(), db_string_to_timestampltz_ex(), db_string_to_timestamptz_ex(), db_string_translate(), db_string_trim(), db_string_truncate(), db_string_unique_prefix(), db_subtract_int_from_datetime(), db_sys_date(), db_sys_date_and_epoch_time(), db_sys_datetime(), db_sys_time(), db_sys_timestamp(), db_time_dbval(), db_time_diff(), db_time_encode(), db_time_format(), db_timestamp(), db_timestamp_encode_utc(), db_to_char(), db_to_date(), db_to_datetime(), db_to_number(), db_to_time(), db_to_timestamp(), db_trunc_dbval(), db_typeof_dbval(), db_tz_offset(), db_unix_timestamp(), db_unpack_prepare_info(), db_validate(), db_validate_query_spec(), db_value_alloc_and_copy(), db_value_domain_default(), db_value_domain_init(), db_value_domain_max(), db_value_domain_min(), db_value_domain_zero(), db_value_get(), db_value_put(), db_value_put_monetary_currency(), db_value_to_enumeration_value(), db_value_to_json_doc(), db_value_to_json_key(), db_value_to_json_path(), db_value_to_json_value(), dbt_change_domain(), dbt_reserve_name(), dbt_set_label(), def_class_internal(), delete_object_tuple(), desc_disk_to_obj(), disk_add_volume(), disk_cache_init(), disk_check(), disk_check_volume(), disk_extend(), disk_format(), disk_reserve_from_cache(), disk_reserve_sectors(), disk_set_creation(), disk_set_link(), disk_spacedb(), disk_to_class(), disk_to_domain2(), disk_to_root(), disk_volume_expand(), disk_volume_header_start_scan(), dl_find_daemon(), dl_is_valid_image_file(), dl_resolve_symbol(), do_add_attribute(), do_add_attribute_from_select_column(), do_add_constraints(), do_alter_change_col_comment(), do_alter_change_default_cs_coll(), do_alter_change_tbl_comment(), do_alter_clause_change_attribute(), do_alter_index_rebuild(), do_alter_one_clause_with_template(), do_alter_partitioning_pre(), do_alter_serial(), do_alter_user(), do_call_method(), do_change_att_schema_only(), do_check_delete_trigger(), do_check_merge_trigger(), do_check_partitioned_class(), do_check_rows_for_null(), do_check_update_trigger(), do_coalesce_partition_post(), do_coalesce_partition_pre(), do_create_auto_increment_serial(), do_create_entity(), do_create_partition(), do_create_partition_constraint(), do_create_serial(), do_create_serial_internal(), do_create_trigger(), do_create_user(), do_drop(), do_drop_partition_list(), do_drop_partitioned_class(), do_drop_serial(), do_drop_session_variables(), do_drop_user(), do_execute_session_statement(), do_execute_statement(), do_find_auto_increment_serial(), do_get_partition_keycol(), do_get_partition_size(), do_get_serial_obj_id(), do_insert_checks(), do_insert_template(), do_kill(), do_prepare_delete(), do_prepare_merge(), do_prepare_select(), do_prepare_session_statement(), do_prepare_update(), do_process_prepare_statement(), do_promote_partition(), do_promote_partition_by_name(), do_promote_partition_list(), do_recreate_filter_index_constr(), do_recreate_func_index_constr(), do_redistribute_partitions_data(), do_remove_partition_pre(), do_rename_internal(), do_rename_partition(), do_reorganize_partition_pre(), do_set_optimization_param(), do_set_session_variables(), do_set_trigger(), do_set_user_host_variables(), do_statement(), do_truncate(), do_update_auto_increment_serial_on_rename(), do_update_maxvalue_of_auto_increment_serial(), do_update_stats(), domain_to_disk(), drop_foreign_key_ref(), drop_foreign_key_ref_internal(), drop_stored_procedure(), dump_tz(), dwb_acquire_next_slot(), dwb_block_create_ordered_slots(), dwb_create_blocks(), dwb_make_wait_queue_entry(), dwb_slots_hash_entry_alloc(), dwb_wait_for_block_completion(), dwb_wait_for_strucure_modification(), ehash_allocate_recdes(), ehash_apply_each(), ehash_binary_search_bucket(), ehash_check_merge_possible(), ehash_compare_key(), ehash_delete(), ehash_distribute_records_into_two_bucket(), ehash_dump(), ehash_dump_bucket(), ehash_expand_directory(), ehash_find_first_bit_position(), ehash_fix_old_page(), ehash_get_key_size(), ehash_hash(), ehash_initialize_bucket_new_page(), ehash_insert_to_bucket(), ehash_insert_to_bucket_after_create(), ehash_locate_slot(), ehash_merge(), ehash_merge_permanent(), ehash_rv_delete(), ehash_rv_init_bucket_redo(), ehash_rv_init_dir_new_page_redo(), ehash_rv_insert_redo(), ehash_shrink_directory(), ehash_split_bucket(), ehash_write_key_to_record(), elo_create(), er_event(), er_event_final(), er_event_init(), er_log_slow_query(), es_copy_file(), es_create_file(), es_delete_file(), es_final(), es_get_file_size(), es_init(), es_owfs_copy_file(), es_owfs_create_file(), es_owfs_delete_file(), es_owfs_final(), es_owfs_get_file_size(), es_owfs_init(), es_owfs_read_file(), es_owfs_rename_file(), es_owfs_write_file(), es_posix_copy_file(), es_posix_delete_file(), es_posix_final(), es_posix_get_file_size(), es_posix_read_file(), es_posix_rename_file(), es_posix_write_file(), es_read_file(), es_rename_file(), es_write_file(), eval_action(), eval_condition(), eval_pred(), eval_pred_alsm4(), eval_pred_comp2(), event_file_open(), event_log_start(), export_serial(), fetch_instance(), fetch_peek_arith(), fetch_peek_dbval(), fetch_peek_min_max_value_of_width_bucket_func(), fetch_set_internal(), fi_handler_random_exit(), fi_handler_random_fail(), fi_thread_init(), file_create(), file_destroy(), file_perm_expand(), file_set_tde_algorithm(), file_table_collect_all_vsids(), file_table_collect_ftab_pages(), file_tempcache_alloc_entry(), file_tempcache_init(), file_tracker_get_and_protect(), fileio_allocate_and_initialize_volume_info(), fileio_allocate_backup_info(), fileio_allocate_node(), fileio_cache(), fileio_compress_backup_node(), fileio_continue_restore(), fileio_copy_volume(), fileio_create_backup_volume(), fileio_decompress_restore_volume(), fileio_expand_to(), fileio_fill_hole_during_restore(), fileio_finalize_backup_thread(), fileio_find_restore_volume(), fileio_finish_backup(), fileio_format(), fileio_get_backup_volume(), fileio_get_next_backup_volume(), fileio_get_next_restore_file(), fileio_get_volume_label(), fileio_initialize_backup(), fileio_initialize_backup_thread(), fileio_initialize_volume_info_cache(), fileio_is_formatted_page(), fileio_list_restore(), fileio_lock(), fileio_lock_la_dbname(), fileio_lock_la_log_path(), fileio_make_error_message(), fileio_page_bitmap_create(), fileio_read(), fileio_read_pages(), fileio_request_user_response(), fileio_reset_volume(), fileio_restore_volume(), fileio_skip_restore_volume(), fileio_symlink(), fileio_synchronize(), fileio_synchronize_all(), fileio_unformat_and_rename(), fileio_unlock_la_dbname(), fileio_write(), fileio_write_backup_header(), fileio_write_backup_node(), fileio_write_pages(), filter_local_constraints(), find_instance(), find_unique(), find_valid_page_size(), cubload::sa_object_loader::finish_line(), flatten_properties(), fpcache_entry_init(), fprint_special_strings(), JSON_PATH::from_json_pointer(), gen_outer(), gen_tz(), genlocale(), get_date_weekday(), get_desc_old(), get_grants(), get_hour_minute_or_second(), get_index_type_qualifiers(), get_number_dbval_as_double(), get_number_dbval_as_long_double(), get_old(), get_ordered_classes(), get_set_value(), get_string_date_token_id(), get_year_month_or_day(), grok_classes(), hb_make_set_hbp_register(), hb_pack_server_name(), heap_attrinfo_access(), heap_attrinfo_check(), heap_attrinfo_check_unique_index(), heap_attrinfo_recache_attrepr(), heap_attrinfo_start_refoids(), heap_attrinfo_start_with_btid(), heap_attrinfo_start_with_index(), heap_capacity_next_scan(), heap_check_all_pages(), heap_check_all_pages_by_heapchain(), heap_chkreloc_end(), heap_chkreloc_next(), heap_chkreloc_print_notfound(), heap_chkreloc_start(), heap_chnguess_initialize(), heap_chnguess_realloc(), heap_classrepr_entry_reset(), heap_classrepr_get(), heap_classrepr_initialize_cache(), heap_create_internal(), heap_delete_bigone(), heap_delete_logical(), heap_does_exist(), heap_eval_function_index(), heap_find_location_and_insert_rec_newhome(), heap_fix_forward_page(), heap_fix_header_page(), heap_flush(), heap_get_btid_from_index_name(), heap_get_class_name_alloc_if_diff(), heap_get_class_oid_from_page(), heap_get_class_partitions(), heap_get_partition_attributes(), heap_get_record_location(), heap_get_referenced_by(), heap_get_visible_version_from_log(), heap_header_capacity_start_scan(), heap_header_next_scan(), heap_init_func_pred_unpack_info(), heap_insert_physical(), heap_is_reusable_oid(), heap_is_valid_oid(), heap_next_internal(), heap_object_upgrade_domain(), heap_prefetch(), heap_prepare_get_context(), heap_prepare_object_page(), heap_reinitialize_page(), heap_reuse(), heap_rv_redo_insert(), heap_rv_redo_newpage(), heap_rv_redo_reuse_page(), heap_rv_redo_reuse_page_reuse_oid(), heap_rv_undoredo_pagehdr(), heap_scancache_add_partition_node(), heap_scancache_quick_end(), heap_stats_add_bestspace(), heap_update_logical(), heap_update_physical(), heap_vacuum_all_objects(), heap_vpid_init_new(), heap_vpid_remove(), help_class_names(), help_trigger_names(), hl_lea_alloc(), hl_lea_realloc(), idmap_grow(), inherit_constraint(), object_description::init(), class_description::init(), init_tz_name(), init_user_locales(), insert_meth_instance(), insert_subquery_results(), cubload::server_class_installer::install_class(), installdb(), cubregex::instr(), intl_text_dbcs_to_utf8_ext(), intl_text_single_byte_to_utf8_ext(), intl_text_utf8_to_dbcs(), intl_text_utf8_to_single_byte(), is_str_find_all(), cubload::semantic_helper::is_utf8_valid(), javasp_ping_server(), javasp_start_server(), javasp_status_server(), javasp_stop_server(), jsp_add_stored_procedure(), jsp_alloc_response(), jsp_alter_stored_procedure(), jsp_call_from_server(), jsp_call_stored_procedure(), jsp_connect_server(), jsp_create_java_vm(), jsp_create_stored_procedure(), jsp_do_call_stored_procedure(), jsp_drop_stored_procedure(), jsp_execute_stored_procedure(), jsp_find_stored_procedure(), jsp_readn(), jsp_receive_error(), jsp_receive_response(), jsp_send_call_request(), jsp_send_destroy_request(), jsp_start_server(), jsp_unpack_string_value(), la_add_node_into_la_commit_list(), la_add_repl_filter(), la_apply_delete_log(), la_apply_insert_log(), la_apply_log_file(), la_apply_pre(), la_apply_repl_log(), la_apply_statement_log(), la_apply_update_log(), la_change_state(), la_check_mem_size(), la_create_repl_filter(), la_delay_replica(), la_expand_cache_log_buffer(), la_fetch_log_hdr(), la_find_archive_num(), la_find_log_pagesize(), la_flush_repl_items(), la_get_current(), la_get_last_ha_applied_info(), la_get_log_data(), la_get_next_update_log(), la_get_overflow_recdes(), la_get_range_of_archive(), la_get_relocation_recdes(), la_get_undoredo_diff(), la_get_zipped_data(), la_init_cache_log_buffer(), la_init_cache_pb(), la_init_recdes_pool(), la_init_repl_lists(), la_insert_ha_apply_info(), la_log_commit(), la_log_fetch(), la_log_fetch_from_archive(), la_log_io_read_with_max_retries(), la_log_page_check(), la_log_record_process(), la_make_repl_item(), la_new_repl_item(), la_print_repl_filter_info(), la_realloc_recdes_data(), lang_locale_data_load_from_lib(), lang_set_charset(), lang_set_charset_lang(), lang_set_language(), ldr_act_add_argument(), ldr_act_add_attr(), ldr_act_attr(), ldr_act_check_missing_non_null_attrs(), ldr_act_class_attr(), ldr_act_elem(), ldr_act_init_context(), ldr_act_meth(), ldr_act_set_constructor(), ldr_add_mop_tempoid_map(), ldr_bstr_elem(), ldr_collection_elem(), ldr_double_elem(), ldr_elo_ext_db_elo(), ldr_elo_ext_elem(), ldr_exec_query_from_file(), ldr_find_class(), ldr_float_elem(), ldr_int_db_bigint(), ldr_int_db_int(), ldr_int_db_short(), ldr_int_elem(), ldr_mismatch(), ldr_monetary_elem(), ldr_mop_tempoid_maps_init(), ldr_null_db_generic(), ldr_oid_elem(), ldr_real_db_double(), ldr_real_db_float(), ldr_str_db_char(), ldr_str_db_varchar(), ldr_sys_user_db_generic(), ldr_xstr_elem(), lf_freelist_alloc_block(), lf_hash_init(), lf_tran_system_init(), JSON_VALIDATOR::load(), load_has_authorization(), load_properties(), lob_from_file(), lob_to_bit_char(), locator_add_class(), locator_add_oid_set(), locator_all_reference_lockset(), locator_allocate_copy_area_by_length(), locator_assign_oid(), locator_assign_oid_batch(), locator_assign_permanent_oid(), locator_attribute_info_force(), locator_cache_have_object(), locator_cache_not_have_object(), locator_cache_object_class(), locator_cache_object_instance(), locator_check_btree_entries(), locator_check_class(), locator_check_class_names(), locator_check_class_on_heap(), locator_check_fk_validity(), locator_check_foreign_key(), locator_check_object_and_get_class(), locator_check_primary_key_delete(), locator_check_primary_key_update(), locator_check_unique_btree_entries(), locator_delete_class_name(), locator_find_class_by_name(), locator_find_class_by_oid(), locator_find_class_oid(), locator_find_lockhint_class_oids(), locator_find_lockset_missing_class_oids(), locator_flush_class(), locator_force(), locator_force_for_multi_update(), locator_fun_get_all_mops(), locator_get_reserved_class_name_oid(), locator_get_rest_objects_classes(), locator_guess_sub_classes(), locator_initialize(), locator_internal_flush_instance(), locator_lock(), locator_lock_and_get_object_internal(), locator_lock_class_of_instance(), locator_lock_nested(), locator_lock_set(), locator_lockhint_classes(), locator_log_force_nologging(), locator_mflush(), locator_permoid_class_name(), locator_prepare_rename_class(), locator_redistribute_partition_data(), locator_rename_class_name(), locator_repl_prepare_force(), locator_reserve_class_names(), locator_save_nested_mops(), locator_unpack_oid_set_to_exist(), locator_update_force(), lock_classes_lock_hint(), lock_demote_class_lock(), lock_detect_local_deadlock(), lock_force_thread_timeout_lock(), lock_force_timeout_expired_wait_transactions(), lock_get_class_lock(), lock_get_lock_holder_tran_index(), lock_get_object_lock(), lock_has_lock_on_object(), lock_hold_object_instant(), lock_is_waiting_transaction(), lock_object(), lock_reacquire_crash_locks(), lock_scan(), lock_subclass(), lock_unlock_all_shared_get_all_exclusive(), lock_unlock_classes_lock_hint(), lock_unlock_object(), lock_unlock_objects_lock_set(), lock_victimize_first_thread_mapfunc(), log_2pc_attach_global_tran(), log_2pc_get_global_tran_info(), log_2pc_prepare(), log_2pc_prepare_global_tran(), log_2pc_recovery(), log_2pc_recovery_analysis_record(), log_2pc_set_global_tran_info(), log_2pc_start(), log_abort(), log_abort_all_active_transaction(), log_abort_partial(), log_active_log_header_start_scan(), log_append_compensate_internal(), log_append_dboutside_redo(), log_append_get_data_ptr(), log_append_init_zip(), log_append_postpone(), log_append_realloc_data_ptr(), log_append_redo_crumbs(), log_append_run_postpone(), log_append_savepoint(), log_append_undo_crumbs(), log_append_undoredo_crumbs(), log_archive_log_header_start_scan(), log_checkpoint(), log_commit(), log_does_active_user_exist(), log_dump_data(), log_dump_log_info(), log_execute_run_postpone(), log_get_charset_from_header_page(), log_get_io_page_size(), log_get_parent_lsa_system_op(), log_get_undo_record(), log_initialize_internal(), log_is_log_flush_daemon_available(), log_is_tran_in_system_op(), log_read_sysop_start_postpone(), log_recovery(), log_recovery_redo(), log_recovery_undo(), log_rollback(), log_rollback_record(), log_rv_analysis_record(), log_rv_undo_record(), log_set_no_logging(), log_set_suppress_repl_on_transaction(), log_skip_logging(), log_sysop_end_begin(), log_sysop_start(), log_unzip(), log_zip(), log_zip_alloc(), logpb_archive_active_log(), logpb_backup(), logpb_check_if_exists(), logpb_check_stop_at_time(), logpb_checkpoint(), logpb_copy_database(), logpb_copy_page(), logpb_fatal_error_internal(), logpb_fetch_from_archive(), logpb_fetch_header_from_active_log(), logpb_find_header_parameters(), logpb_find_oldest_available_page_id(), logpb_flush_header(), logpb_flush_page(), logpb_initialize_flush_info(), logpb_initialize_header(), logpb_initialize_pool(), logpb_locate_page(), logpb_next_where_path(), logpb_peek_header_of_active_log_from_backup(), logpb_read_page_from_active_log(), logpb_read_page_from_file(), logpb_remote_ask_user_before_delete_volumes(), logpb_remove_archive_logs_exceed_limit(), logpb_rename_all_volumes_files(), logpb_restore(), logpb_scan_volume_info(), logpb_set_dirty(), logpb_verify_length(), logpb_write_page_to_disk(), logpb_write_toflush_pages_to_archive(), logpb_writev_append_pages(), logtb_allocate_tdes_area(), logtb_allocate_tran_index(), logtb_define_trantable_log_latch(), logtb_expand_trantable(), logtb_get_trans_info(), logtb_global_unique_stat_alloc(), logtb_initialize_system_tdes(), logtb_realloc_topops_stack(), logtb_set_tran_index_interrupt(), logtb_slam_transaction(), logtb_tran_create_btid_unique_stats(), logtb_tran_create_class_cos(), logwr_get_log_pages(), logwr_log_ha_filestat_to_string(), main(), make_activity(), make_cst_item_value(), make_mergelist_proc(), make_state(), make_temp_object(), make_template(), metharg_to_disk(), methfile_to_disk(), method_clear_scan_buffer(), method_initialize_vacomm_buffer(), method_invoke_for_server(), method_receive_results_for_stand_alone(), method_send_value_to_server(), method_to_disk(), methsig_to_disk(), mht_create(), mht_create_hls(), mht_rehash(), cubload::mismatch(), mr_data_cmpdisk_string(), mr_data_cmpdisk_varnchar(), mr_data_readmem_bit(), mr_data_readmem_char(), mr_data_readmem_nchar(), mr_data_readmem_numeric(), mr_data_writemem_object(), mr_readval_bit_internal(), mr_readval_char_internal(), mr_readval_nchar_internal(), mr_readval_string_internal(), mr_readval_varnchar_internal(), mr_setmem_bit(), mr_setmem_char(), mr_setmem_nchar(), mr_setmem_numeric(), msgcat_open(), need_to_abort_tran(), net_client_check_log_header(), net_client_get_next_log_pages(), net_client_init(), net_client_ping_server(), net_client_ping_server_with_handshake(), net_client_receive_action(), net_client_recv_copyarea(), net_client_request(), net_client_request2(), net_client_request2_no_malloc(), net_client_request_2recv_copyarea(), net_client_request_3_data(), net_client_request_3_data_recv_copyarea(), net_client_request_3recv_copyarea(), net_client_request_internal(), net_client_request_no_reply(), net_client_request_recv_copyarea(), net_client_request_recv_stream(), net_client_request_with_callback(), net_client_request_with_logwr_context(), net_server_request(), net_server_start(), net_set_alloc_err_if_not_set(), number_to_char(), numeric_coerce_string_to_num(), numeric_common_prec_scale(), numeric_db_value_add(), numeric_db_value_div(), numeric_db_value_sub(), obj_assign_value(), obj_copy(), obj_desc_find_unique(), obj_find_multi_attr(), obj_find_multi_desc(), obj_find_object_by_cons_and_key(), obj_find_object_by_pkey(), obj_find_primary_key(), obj_find_unique(), obj_get_att(), obj_get_value(), obj_inst_lock(), obj_make_key_value(), obj_set_att(), obt_def_object(), obt_edit_object(), obt_find_attribute(), online_index_builder(), or_chn(), or_cl_get_prop_nocopy(), or_class_tde_algorithm(), or_get_all_representation(), or_get_attr_string(), or_get_current_representation(), or_get_enumeration(), or_get_hierarchy_helper(), or_get_old_representation(), or_get_unique_hierarchy(), or_get_value(), or_install_btids(), or_install_btids_class(), or_install_btids_filter_pred(), or_install_btids_function_info(), or_install_btids_prefix_length(), or_put_monetary(), or_put_oid(), or_put_varchar_internal(), or_rep_id(), or_set_rep_id(), or_underflow(), or_unpack_query_format(), or_unpack_recdes(), or_unpack_spacedb(), or_unpack_string_alloc(), or_unpack_unbound_listid(), orc_class_info_from_record(), orc_diskrep_from_record(), orc_subclasses_from_record(), orc_superclasses_from_record(), otable_find_class(), overflow_get_capacity(), overflow_get_nbytes(), overflow_insert(), parser_create_node_block(), parser_create_parser(), parser_create_string_block(), partition_cache_entry_to_pruning_context(), partition_find_inherited_btid(), partition_find_partition_for_record(), partition_get_value_from_key(), partition_info_to_disk(), partition_load_partition_predicate(), partition_prune_insert(), partition_prune_spec(), partition_prune_update(), partition_pruning_context_to_cache_entry(), perfmon_allocate_packed_values_buffer(), perfmon_allocate_values(), perfmon_initialize(), perfmon_server_copy_global_stats(), perfmon_server_copy_stats(), pgbuf_allocate_bcb(), pgbuf_allocate_thrd_holder_entry(), pgbuf_block_bcb(), pgbuf_copy_to_area(), pgbuf_fix_debug(), pgbuf_fix_with_retry(), pgbuf_flush_checkpoint(), pgbuf_flush_victim_candidates(), pgbuf_get_groupid_and_unfix(), pgbuf_initialize(), pgbuf_initialize_aout_list(), pgbuf_initialize_bcb_table(), pgbuf_initialize_hash_table(), pgbuf_initialize_lock_table(), pgbuf_initialize_lru_list(), pgbuf_initialize_page_monitor(), pgbuf_initialize_page_quota(), pgbuf_initialize_seq_flusher(), pgbuf_initialize_thrd_holder(), pgbuf_is_log_check_for_interrupts(), pgbuf_is_valid_page(), pgbuf_is_valid_page_ptr(), pgbuf_latch_bcb_upon_fix(), pgbuf_ordered_fix_debug(), pgbuf_promote_read_latch_debug(), pgbuf_set_lsa(), pgbuf_unlatch_bcb_upon_unfix(), pgbuf_unlatch_thrd_holder(), populate_auto_increment(), pr_data_compress_string(), pr_do_db_value_string_compression(), pr_get_compressed_data_from_buffer(), pr_get_compression_length(), pr_get_size_and_write_string_to_buffer(), pr_midxkey_compare(), prepare_query(), print_backup_info(), print_string_date_token(), prior_lsa_alloc_and_copy_crumbs(), prior_lsa_alloc_and_copy_data(), prior_lsa_copy_redo_crumbs_to_node(), prior_lsa_copy_redo_data_to_node(), prior_lsa_copy_undo_crumbs_to_node(), prior_lsa_copy_undo_data_to_node(), prior_lsa_gen_2pc_prepare_record(), prior_lsa_gen_dbout_redo_record(), prior_lsa_gen_end_chkpt_record(), prior_lsa_gen_postpone_record(), prior_lsa_gen_record(), prior_lsa_gen_undoredo_record_from_crumbs(), prior_set_tde_encrypted(), prm_report_bad_entry(), prm_set_force(), cubload::server_object_loader::process_collection_constant(), cubload::server_object_loader::process_generic_constant(), cubload::sa_object_loader::process_line(), cubload::server_object_loader::process_line(), cubload::server_object_loader::process_monetary_constant(), propagate_revoke(), pt_alloc_packing_buf(), pt_append_odku_references(), pt_associate_label_with_value_check_reference(), pt_check_alter(), pt_check_attribute_domain(), pt_check_create_entity(), pt_check_defaultf(), pt_check_sub_insert(), pt_copy_upddel_hints_to_select(), pt_create_iss_range(), pt_data_type_to_db_domain(), pt_evaluate_db_value_expr(), pt_evaluate_tree_internal(), pt_fold_const_expr(), pt_get_enumeration_from_data_type(), pt_make_query_showstmt(), pt_node_data_type_to_db_domain(), pt_node_to_function_index(), pt_node_to_partition_info(), pt_print_value(), pt_register_parser(), pt_report_to_ersys(), pt_report_to_ersys_with_statement(), pt_resolve_serial(), pt_semantic_check_local(), pt_serial_to_xasl_class_oid_list(), pt_split_delete_stmt(), pt_string_to_db_domain(), pt_to_constraint_pred(), pt_to_delete_xasl(), pt_to_merge_insert_xasl(), pt_to_merge_update_xasl(), pt_to_merge_xasl(), pt_to_odku_info(), pt_to_regu_variable(), pt_to_spec_list(), pt_to_update_xasl(), pt_validate_query_spec(), put_attributes(), pwrite_with_injected_fault(), qdata_add_bigint(), qdata_add_bigint_to_date(), qdata_add_bigint_to_timestamptz(), qdata_add_bigint_to_utime(), qdata_add_bigint_to_utime_asymmetry(), qdata_add_date_to_dbval(), qdata_add_dbval(), qdata_add_double(), qdata_add_float(), qdata_add_int(), qdata_add_int_to_date(), qdata_add_int_to_timestamptz(), qdata_add_int_to_utime(), qdata_add_int_to_utime_asymmetry(), qdata_add_monetary(), qdata_add_numeric(), qdata_add_numeric_to_dbval(), qdata_add_short(), qdata_add_short_to_date(), qdata_add_short_to_timestamptz(), qdata_add_short_to_utime(), qdata_add_short_to_utime_asymmetry(), qdata_aggregate_accumulator_to_accumulator(), qdata_aggregate_multiple_values_to_accumulator(), qdata_aggregate_value_to_accumulator(), qdata_alloc_agg_hkey(), qdata_alloc_agg_hvalue(), qdata_alloc_hscan_key(), qdata_alloc_hscan_value(), qdata_alloc_hscan_value_OID(), qdata_apply_interpolation_function_coercion(), qdata_benchmark(), qdata_bit_and_dbval(), qdata_bit_not_dbval(), qdata_bit_or_dbval(), qdata_bit_shift_dbval(), qdata_bit_xor_dbval(), qdata_concatenate_dbval(), qdata_copy_hscan_key(), qdata_copy_hscan_key_without_alloc(), qdata_divide_bigint_to_dbval(), qdata_divide_dbval(), qdata_divide_double(), qdata_divide_float(), qdata_divide_int_to_dbval(), qdata_divide_monetary(), qdata_divide_numeric_to_dbval(), qdata_divide_short_to_dbval(), qdata_divmod_dbval(), qdata_elt(), qdata_evaluate_aggregate_list(), qdata_evaluate_analytic_func(), qdata_evaluate_function(), qdata_evaluate_generic_function(), qdata_finalize_aggregate_list(), qdata_get_cardinality(), qdata_get_interpolation_function_result(), qdata_get_single_tuple_from_list_id(), qdata_get_tuple_value_size_from_dbval(), qdata_get_valptr_type_list(), qdata_increment_dbval(), qdata_insert_substring_function(), qdata_interpolation_function_values(), qdata_list_dbs(), qdata_multiply_bigint(), qdata_multiply_dbval(), qdata_multiply_double(), qdata_multiply_float(), qdata_multiply_int(), qdata_multiply_monetary(), qdata_multiply_numeric(), qdata_multiply_numeric_to_dbval(), qdata_multiply_short(), qdata_strcat_dbval(), qdata_subtract_bigint(), qdata_subtract_bigint_to_dbval(), qdata_subtract_date_to_dbval(), qdata_subtract_datetime(), qdata_subtract_dbval(), qdata_subtract_double(), qdata_subtract_float(), qdata_subtract_int(), qdata_subtract_int_to_dbval(), qdata_subtract_monetary(), qdata_subtract_numeric_to_dbval(), qdata_subtract_short(), qdata_subtract_short_to_dbval(), qdata_subtract_utime(), qdata_subtract_utime_to_bigint_asymmetry(), qdata_subtract_utime_to_int_asymmetry(), qdata_subtract_utime_to_short_asymmetry(), qdata_unary_minus_dbval(), qdata_update_agg_interpolation_func_value_and_domain(), qentry_to_sentry(), qexec_alloc_agg_hash_context(), qexec_analytic_evaluate_offset_function(), qexec_check_limit_clause(), qexec_clear_mainblock_iterations(), qexec_end_mainblock_iterations(), qexec_end_one_iteration(), qexec_execute_analytic(), qexec_execute_build_indexes(), qexec_execute_connect_by(), qexec_execute_cte(), qexec_execute_duplicate_key_update(), qexec_execute_insert(), qexec_execute_mainblock(), qexec_execute_mainblock_internal(), qexec_execute_query(), qexec_execute_selupd_list_find_class(), qexec_execute_update(), qexec_fill_sort_limit(), qexec_generate_tuple_descriptor(), qexec_groupby(), qexec_groupby_index(), qexec_hash_gby_agg_tuple(), qexec_init_agg_hierarchy_helpers(), qexec_init_instnum_val(), qexec_initialize_analytic_function_state(), qexec_intprt_fnc(), qexec_oid_of_duplicate_key_update(), qexec_open_scan(), qexec_resolve_domains_for_aggregation(), qexec_setup_list_id(), qexec_start_mainblock_iterations(), qexec_topn_tuples_to_list_id(), qfile_allocate_new_page(), qfile_initialize_sort_key_info(), qfile_jump_scan_tuple_position(), qfile_scan_next(), qfile_scan_prev(), qfile_unify_types(), qfile_update_domains_on_type_list(), qmgr_add_modified_class(), qmgr_allocate_query_entry(), qmgr_allocate_tempfile_with_buffer(), qmgr_allocate_tran_entries(), qmgr_create_new_temp_file(), qmgr_create_result_file(), qmgr_execute_query(), qmgr_free_list_temp_file(), qmgr_get_new_page(), qmgr_get_old_page(), qmgr_get_sql_id(), qmgr_prepare_and_execute_query(), qmgr_prepare_query(), qmgr_process_query(), qo_abort(), qo_alloc_index(), qo_alloc_info(), qo_alloc_planner(), qo_assign_eq_classes(), qo_discover_partitions(), qo_env_init(), qo_env_new(), qo_expr_segs(), qo_find_node_indexes(), qo_get_attr_info(), qo_get_attr_info_func_index(), qo_get_class_info(), qo_get_index_info(), qo_get_xasl_index_info(), qo_optimize_query(), qo_plan_malloc(), qo_reduce_order_by(), qo_reduce_order_by_for(), qo_search_planner(), qo_set_cost(), qo_to_xasl(), qproc_next_set_scan(), qstr_bit_concatenate(), qstr_concatenate(), qstr_grow_string(), qstr_replace(), qstr_translate(), query_multi_range_opt_check_set_sort_col(), query_spec_to_disk(), realloc_instance_table(), cubload::server_class_installer::register_class_with_attributes(), regu_set_error_with_zero_args(), repattribute_to_disk(), repl_set_info(), cubregex::replace(), representation_to_disk(), resolution_to_disk(), root_to_disk(), round_date(), round_double(), run_user_triggers(), rv_check_rvfuns(), save_constraint_info_from_pt_node(), sboot_change_ha_mode(), sboot_get_locales_info(), sboot_get_timezone_checksum(), sboot_notify_ha_log_applier_state(), sbtree_get_key_type(), sbtree_load_index(), scan_alloc_oid_list(), scan_get_index_oidset(), scan_get_next_iss_value(), scan_hash_probe_next(), scan_init_index_key_limit(), scan_init_iss(), scan_next_index_lookup_heap(), scan_next_index_scan(), scan_next_method_scan(), scan_next_scan_block(), scan_next_scan_local(), scan_next_showstmt_scan(), scan_next_value_scan(), scan_prev_scan_local(), scan_reset_scan_block(), scan_start_scan(), cubregex::search(), select_set_domain(), serial_alloc_cache_area(), serial_get_nth_value(), serial_update_cur_val_of_serial(), serial_update_serial_object(), server_ping_with_handshake(), ses_posix_write_file(), session_add_variable(), session_check_session(), session_create_prepared_statement(), session_delete_prepared_statement(), session_get_prepared_statement(), session_get_session_state(), session_get_variable(), session_get_variable_no_copy(), session_state_destroy(), set_change_owner(), set_iterate(), set_msg_lang_from_env(), set_prepare_info_into_list(), set_server_error(), setobj_cardinality(), setobj_copy(), setobj_create(), setobj_drop_seq_element(), setobj_find_seq_element(), setobj_get_domain(), setobj_get_element_ptr(), setobj_insert_element(), setobj_put_element(), setobj_size(), setvobj_compare(), SHA1Compute(), signal_evaluation_error(), sloaddb_fetch_status(), sloaddb_install_class(), sloaddb_load_batch(), slocator_fetch_lockhint_classes(), slocator_fetch_lockset(), slocator_find_lockhint_class_oids(), slocator_force(), slocator_redistribute_partition_data(), slocator_repl_force(), sm_add_constraint(), sm_add_secondary_index_on_partition(), sm_add_static_method(), sm_check_name(), sm_class_check_uniques(), sm_class_has_triggers(), sm_default_constraint_name(), sm_exist_index(), sm_expand_method_files(), sm_free_function_nlist(), sm_get_method_source_file(), sm_get_trigger_cache(), sm_load_online_index(), sm_locate_method_file(), sm_partitioned_class_type(), sm_produce_constraint_name(), sm_save_constraint_info(), sm_save_filter_index_info(), sm_save_function_index_info(), sm_save_nested_view_versions(), smt_add_attribute_to_list(), smt_add_constraint(), smt_add_query_spec(), smt_change_query_spec(), smt_copy_class_mop(), smt_drop_method_file(), smt_drop_query_spec(), smt_edit_class_mop(), smt_find_constraint(), smt_is_change_status_allowed(), smt_rename_any(), smt_rename_method_file(), sort_exphase_merge(), sort_exphase_merge_elim_dup(), sort_inphase_sort(), sort_listfile(), sort_return_used_resources(), sort_run_flush(), sort_run_sort(), sort_spage_compact(), spage_check(), spage_check_mvcc_updatable(), spage_check_slot_owner(), spage_check_updatable(), spage_compact(), spage_delete(), spage_find_empty_slot(), spage_find_empty_slot_at(), spage_find_free_slot(), spage_get_free_space_without_saving(), spage_get_record(), spage_get_record_data(), spage_get_record_length(), spage_get_record_offset(), spage_get_space_for_record(), spage_header_start_scan(), spage_insert_at(), spage_insert_data(), spage_insert_for_recovery(), spage_mark_deleted_slot_as_reusable(), spage_merge(), spage_overwrite(), spage_put_helper(), spage_slots_start_scan(), spage_split(), spage_take_out(), spage_take_slot_in_use(), spage_update(), spage_update_record_after_compact(), spage_update_record_in_place(), spage_update_record_type(), spage_verify_header(), sprm_server_get_force_parameters(), sprm_server_obtain_parameters(), sqmgr_execute_query(), sqmgr_prepare_and_execute_query(), sqmgr_prepare_query(), ssession_create_prepared_statement(), ssession_drop_session_variables(), ssession_find_or_create_session(), ssession_get_prepared_statement(), ssession_get_session_variable(), ssession_set_session_variables(), start_state(), stats_find_inherited_index_stats(), stran_server_set_global_tran_info(), cubregex::substr(), sync_allocate_sync_stats_chunk(), sysprm_alloc_session_parameters(), sysprm_change_server_parameters(), sysprm_final(), sysprm_generate_new_value(), sysprm_obtain_parameters(), sysprm_obtain_server_parameters(), sysprm_print_parameters_for_ha_repl(), sysprm_print_parameters_for_qry_string(), sysprm_set_error(), sysprm_set_sysprm_value_from_parameter(), sysprm_set_value(), sysprm_unpack_assign_values(), sysprm_unpack_session_parameters(), sysprm_unpack_sysprm_value(), sysprm_validate_change_parameters(), tde_add_mk(), tde_change_mk(), tde_cipher_initialize(), tde_copy_keys_file(), tde_create_dk(), tde_create_keys_file(), tde_create_mk(), tde_decrypt_data_page(), tde_decrypt_internal(), tde_decrypt_log_page(), tde_delete_mk(), tde_encrypt_data_page(), tde_encrypt_internal(), tde_encrypt_log_page(), tde_find_first_mk(), tde_find_mk(), tde_initialize(), tde_load_mk(), tf_add_fixup(), tf_attribute_default_expr_to_property(), tf_class_to_disk(), tf_compile_meta_classes(), tf_mem_to_disk(), tf_need_permanent_oid(), thread_kill_or_interrupt_tran(), thread_kill_tran_index(), tm_encode(), cubload::to_db_bigint(), cubload::to_db_double(), cubload::to_db_elo_ext(), cubload::to_db_float(), cubload::to_db_generic_char(), cubload::to_db_int(), cubload::to_db_monetary(), cubload::to_db_short(), cubload::to_db_varbit_from_bin_str(), cubload::to_db_varbit_from_hex_str(), cubload::to_int_generic(), tp_atof(), tp_can_steal_string(), tp_domain_copy_enumeration(), tp_domain_select(), tp_domain_status_er_set(), tp_dtoa(), tp_ftoa(), tp_ltoa(), tp_value_compare_with_error(), tr_check_commit_triggers(), tr_create_trigger(), tr_drop_deferred_activities(), tr_drop_trigger(), tr_execute_activities(), tr_find_trigger(), tr_make_trigger(), tr_prepare_statement(), tr_rename_trigger(), tr_set_comment(), tr_set_depth(), tr_set_priority(), tr_set_status(), tran_abort_only_client(), tran_reset_isolation(), tran_server_2pc_recovery_prepared(), tran_server_partial_abort(), tran_server_savepoint(), tran_unilaterally_abort(), transfer_disk_structures(), transfer_string(), cubxasl::json_table::column::trigger_on_empty(), cubxasl::json_table::column::trigger_on_error(), trigger_table_add(), trigger_table_drop(), trigger_table_rename(), truncate_date(), tz_check_geographic_tz(), tz_check_session_has_geographic_tz(), tz_create_datetimetz_from_offset(), tz_create_datetimetz_from_zoneid_and_tzd(), tz_create_timestamptz_from_offset(), tz_create_timestamptz_from_zoneid_and_tzd(), tz_datetime_utc_conv(), tz_explain_tz_id(), tz_get_ds_change_julian_date_diff(), tz_get_timezone_offset(), tz_load(), tz_load_data_from_lib(), tz_load_library(), tz_load_with_library_path(), tz_str_timezone_decode(), tz_str_to_region(), tz_utc_datetimetz_to_local(), tzc_compute_timezone_checksum(), tzc_index_data(), tzc_log_error(), update_cache(), update_fk_ref_partitioned_class(), update_foreign_key_ref(), update_locksets_for_multiple_rename(), update_objs_for_list_file(), vacuum_add_dropped_file(), vacuum_collect_heap_objects(), vacuum_finalize(), vacuum_load_dropped_files_from_disk(), vacuum_process_log_block(), vacuum_process_log_record(), valcnv_append_bytes(), JSON_VALIDATOR::validate(), JSON_PATH::validate_and_create_from_json_path(), validate_template(), values_list_to_values_array(), vid_add_virtual_instance(), vid_att_in_obj_id(), vid_base_instance(), vid_build_non_upd_object(), vid_build_virtual_mop(), vid_compare_non_updatable_objects(), vid_decode_object(), vid_encode_object(), vid_fetch_instance(), vid_flush_and_rehash(), vid_get_class_object(), vid_object_to_vobj(), vid_pack_vobj(), vid_vobj_to_object(), vs_new(), ws_abort_transaction(), ws_add_to_repl_obj_list(), ws_cache(), ws_cull_mops(), ws_decache(), ws_dirty(), ws_disconnect_deleted_instances(), ws_init(), ws_make_mop(), ws_mop(), ws_new_mop(), ws_set_repl_error_into_error_link(), ws_update_oid(), ws_vmop(), xboot_copy(), xboot_delete(), xboot_emergency_patch(), xboot_initialize_server(), xboot_register_client(), xboot_restart_from_backup(), xboot_soft_rename(), xboot_unregister_client(), xbtree_find_multi_uniques(), xbtree_load_index(), xbtree_load_online_index(), xcache_entry_mark_deleted(), xcache_find_xasl_id_for_execute(), xcache_initialize(), xcache_insert(), xcache_retire_clone(), xcache_unfix(), xcallback_console_print(), xcatalog_check_rep_dir(), xchksum_insert_repl_log_and_demote_table_lock(), xdisk_get_fullname(), xlocator_delete_class_name(), xlocator_fetch(), xlocator_find_lockhint_class_oids(), xlocator_force(), xlocator_get_reserved_class_name_oid(), xlocator_remove_class_from_index(), xlocator_repl_force(), xlocator_reserve_class_name(), xlocator_upgrade_instances_domain(), xlogtb_get_pack_tran_table(), xlogtb_kill_or_interrupt_tran(), xlogtb_kill_tran_index(), xlogtb_reset_isolation(), xlogtb_reset_wait_msecs(), xqmgr_end_query(), xqmgr_execute_query(), xqmgr_prepare_and_execute_query(), xqmgr_prepare_query(), xrepl_set_info(), xs_receive_data_from_client_with_timeout(), xs_send_action_to_client(), xserial_get_current_value_internal(), xserial_get_next_value(), xserial_get_next_value_internal(), xstats_get_statistics_from_server(), xstats_update_statistics(), xsysprm_get_force_server_parameters(), xtde_get_mk_info(), xtran_server_abort(), xtran_server_end_topop(), xts_save_odku_info(), xtx_add_lob_locator(), xtx_change_state_of_locator(), xtx_drop_lob_locator(), and xvacuum().
int er_set_area_error (char * server_area)
Definition at line 2133 of file error_manager.c.
References assert, ASSERT_ALIGN, er_clear(), ER_ERROR_SEVERITY, ER_FATAL_ERROR_SEVERITY, ER_LAST_ERROR, er_Log_file_mutex, ER_MAX_SEVERITY, ER_WARNING_SEVERITY, cuberr::er_message::err_id, er_copy_area::err_id, cuberr::er_message::file_name, INT_ALIGNMENT, cuberr::er_message::line_no, cuberr::er_message::msg_area, NO_ERROR, NULL, OR_GET_INT, OR_INT_SIZE, prm_get_bool_value(), prm_get_integer_value(), PRM_ID_ER_LOG_LEVEL, PRM_ID_ER_LOG_WARNING, cuberr::er_message::reserve_message_area(), cuberr::er_message::severity, er_copy_area::severity, and strlen.
Referenced by css_connect_to_cubrid_server(), css_test_for_client_errors(), css_test_for_server_errors(), and qmgr_free_list_temp_file().
static int er_set_internal (int severity, const char * file_name, const int line_no, int err_id, int num_args, bool include_os_error, FILE * fp, va_list * ap_ptr) static
Definition at line 1386 of file error_manager.c.
References assert, cuberr::er_message::clear_error(), er_call_stack_dump_on_error(), ER_CT_REPRCNT_OVERFLOW, ER_CT_UNKNOWN_CLASSID, ER_ERROR_SEVERITY, er_estimate_size(), ER_FAILED, er_find_fmt(), ER_FK_CANT_ASSIGN_CACHE_ATTR, ER_FK_CANT_DROP_CACHE_ATTR, ER_INTERRUPTED, ER_LAST_ERROR, er_Log_file_mutex, ER_NOTIFICATION_SEVERITY, er_notify_event_on_error(), ER_NUM_OVERFLOW, ER_QPROC_OVERFLOW_COERCION, ER_SM_CATALOG_SPACE, er_stop_on_error(), ER_TP_INCOMPATIBLE_DOMAINS, er_vsprintf(), ER_WARNING_SEVERITY, cuberr::er_message::err_id, er_copy_area::err_id, cuberr::context::get_current_error_level(), MAX_LINE, cuberr::er_message::msg_area, NO_ERROR, NULL, cuberr::context::pop_error_stack_and_destroy(), prm_get_bool_value(), prm_get_integer_value(), PRM_ID_ER_LOG_LEVEL, PRM_ID_ER_LOG_WARNING, PRM_ID_ER_STOP_ON_ERROR, cuberr::context::push_error_stack(), cuberr::er_message::reserve_message_area(), cuberr::er_message::set_error(), er_copy_area::severity, and strlen.
Referenced by er_set(), er_set_with_file(), and er_set_with_oserror().
void er_set_print_property (int print_console)
Definition at line 987 of file error_manager.c.
Referenced by csql().
void er_set_with_file (int severity, const char * file_name, const int line_no, int err_id, FILE * fp, int num_args, ...)
Definition at line 1256 of file error_manager.c.
References er_set_internal().
void er_set_with_oserror (int severity, const char * file_name, const int line_no, int err_id, int num_args, ...)
Definition at line 1285 of file error_manager.c.
References er_set_internal(), and NULL.
Referenced by alterdbhost(), boot_find_new_db_path(), boot_initialize_client(), boot_parse_add_volume_extensions(), cfg_ensure_directory_write(), cfg_maycreate_get_directory_filename(), cfg_open_directory_file(), csect_check_own_critical_section(), csect_demote_critical_section(), csect_enter_critical_section(), csect_enter_critical_section_as_reader(), csect_exit_critical_section(), csect_finalize_critical_section(), csect_initialize_critical_section(), csect_promote_critical_section(), css_common_connect(), css_connect_to_master_server(), css_get_next_client_id(), css_init_conn_list(), css_make_conn(), css_master_accept(), css_open_new_socket_from_master(), css_process_get_server_ha_mode_request(), css_process_shutdown_request(), css_register_server_timeout_fn(), css_set_networking_error(), css_setup_server_loop(), css_shutdown_socket(), css_sockaddr(), css_tcp_client_open(), css_tcp_client_open_with_retry(), css_tcp_client_open_with_timeout(), css_tcp_listen_server_datagram(), css_tcp_master_datagram(), css_tcp_master_open(), css_tcp_setup_server_datagram(), css_transfer_fd(), es_local_get_file_size(), es_local_read_file(), es_posix_final(), es_posix_init(), fileio_backup_volume(), fileio_close(), fileio_continue_restore(), fileio_create(), fileio_create_backup_volume(), fileio_expand_to(), fileio_flush_backup(), fileio_flush_control_initialize(), fileio_format(), fileio_get_directory_path(), fileio_get_lock(), fileio_get_next_backup_volume(), fileio_get_number_of_partition_free_pages(), fileio_get_number_of_partition_free_sectors(), fileio_initialize_backup(), fileio_initialize_restore(), fileio_lock(), fileio_lock_la_dbname(), fileio_lock_la_log_path(), fileio_mount(), fileio_os_read(), fileio_os_write(), fileio_read(), fileio_read_backup(), fileio_read_pages(), fileio_read_restore(), fileio_read_restore_header(), fileio_release_lock(), fileio_rename(), fileio_set_permission(), fileio_synchronize(), fileio_synchronize_all(), fileio_unformat_and_rename(), fileio_unlock_la_dbname(), fileio_write(), fileio_write_backup_end_time_to_header(), fileio_write_backup_header(), fileio_write_pages(), hb_create_master_reader(), heap_classrepr_decache_guessed_last(), heap_classrepr_get(), jsp_connect_server(), la_check_duplicated(), la_create_repl_filter(), la_delay_replica(), la_disk_to_obj(), la_find_log_pagesize(), la_log_fetch_from_archive(), la_log_io_read_with_max_retries(), la_log_page_check(), log_active_log_header_start_scan(), log_archive_log_header_start_scan(), logpb_backup(), logpb_create_volume_info(), logpb_rename_all_volumes_files(), logpb_start_where_path(), logpb_update_backup_volume_info(), logpb_write_page_to_disk(), logpb_writev_append_pages(), pgbuf_add_fixed_at(), pgbuf_block_bcb(), pgbuf_search_hash_chain(), rmutex_finalize(), rmutex_initialize(), rmutex_lock(), rwlock_finalize(), rwlock_initialize(), rwlock_read_lock(), rwlock_read_unlock(), rwlock_write_lock(), rwlock_write_unlock(), sacl_dump(), set_server_error(), slock_dump(), slogpb_dump_stat(), slogtb_dump_trantable(), sprm_server_dump_parameters(), sqmgr_dump_query_cache(), sqmgr_dump_query_plans(), sthread_dump_cs_stat(), svacuum_dump(), sync_finalize_sync_stats(), sync_initialize_sync_stats(), tde_add_mk(), tde_copy_keys_file(), tde_find_first_mk(), thread_suspend_timeout_wakeup_and_unlock_entry(), thread_suspend_with_other_mutex(), xboot_copy(), xboot_initialize_server(), xboot_soft_rename(), and xtde_change_mk_without_flock().
void er_setid (int err_id)
Definition at line 1881 of file error_manager.c.
References assert, and er_copy_area::err_id.
void er_stack_clearall (void)
Definition at line 2320 of file error_manager.c.
References er_stack_pop_and_keep_error(), and cuberr::context::has_error_stack().
Referenced by tran_2pc_prepare(), tran_2pc_prepare_global_tran(), tran_abort(), and tran_commit().
void er_stack_pop (void)
Definition at line 2251 of file error_manager.c.
Referenced by boot_create_all_volumes(), boot_restart_server(), disk_rv_undo_format(), do_process_prepare_statement(), file_header_sanity_check(), fileio_synchronize_all(), get_grants(), heap_is_object_not_null(), heap_object_upgrade_domain(), la_apply_delete_log(), la_apply_insert_log(), la_apply_log_file(), la_apply_statement_log(), la_apply_update_log(), la_create_repl_filter(), la_flush_repl_items(), la_print_repl_filter_info(), locator_is_class(), lock_wait_state_to_string(), pgbuf_flush_checkpoint(), pgbuf_set_lsa(), pt_bind_name_or_path_in_scope(), return_error_to_client(), sm_virtual_queries(), update_cache(), xboot_delete(), xboot_initialize_server(), xboot_shutdown_server(), and xtran_server_end_topop().
void er_stack_pop_and_keep_error (void)
Definition at line 2262 of file error_manager.c.
References assert, cuberr::context::get_logging(), cuberr::context::get_thread_local_error(), cuberr::context::has_error_stack(), NO_ERROR, and cuberr::context::pop_error_stack().
Referenced by er_restore_last_error(), er_stack_clearall(), get_grants(), locator_is_class(), and update_cache().
void er_stack_push (void)
Definition at line 2212 of file error_manager.c.
Referenced by boot_create_all_volumes(), boot_restart_server(), disk_rv_undo_format(), do_process_prepare_statement(), file_header_sanity_check(), fileio_synchronize_all(), get_grants(), heap_is_object_not_null(), heap_object_upgrade_domain(), la_apply_delete_log(), la_apply_insert_log(), la_apply_log_file(), la_apply_statement_log(), la_apply_update_log(), la_create_repl_filter(), la_flush_repl_items(), la_print_repl_filter_info(), locator_is_class(), lock_wait_state_to_string(), pgbuf_flush_checkpoint(), pgbuf_set_lsa(), pt_bind_name_or_path_in_scope(), return_error_to_client(), sm_virtual_queries(), update_cache(), xboot_delete(), xboot_initialize_server(), xboot_shutdown_server(), and xtran_server_end_topop().
void er_stack_push_if_exists (void)
Definition at line 2225 of file error_manager.c.
References cuberr::er_message::err_id, cuberr::context::get_current_error_level(), cuberr::context::has_error_stack(), NO_ERROR, and cuberr::context::push_error_stack().
static void er_stop_on_error (void) static
Definition at line 1566 of file error_manager.c.
References ER_ER_ASK, er_errid(), ER_STOP_SYSLOG, NULL, rel_name(), and TRUE.
Referenced by er_log(), and er_set_internal().
static void er_study_fmt (ER_FMT * fmt) static
Definition at line 2531 of file error_manager.c.
References ARG_FILE_LINE, er_spec::code, ER_ER_SUBSTITUTE_MSG, er_internal_msg(), er_log_debug, ER_LOG_SUSPECT_FMT, ER_MALLOC, er_study_spec(), er_fmt::err_id, er_fmt::fmt, free_and_init, i, er_fmt::nspecs, NULL, p, er_spec::spec, er_fmt::spec, er_fmt::spec_buf, er_fmt::spec_top, and er_spec::width.
Referenced by er_create_fmt_msg().
static int er_study_spec (const char * conversion_spec, char * simple_spec, int * position, int * width, int * va_class) static
Definition at line 2350 of file error_manager.c.
References ARG_FILE_LINE, assert, CAST_STRLEN, char_isdigit(), er_log_debug, ER_LOG_UNKNOWN_CODE, p, SPEC_CODE_LONGLONG, and SPEC_CODE_SIZE_T.
Referenced by er_study_fmt().
static int er_vsprintf (er_message * er_entry_p, ER_FMT * fmt, va_list * ap) static
Definition at line 3002 of file error_manager.c.
References cuberr::er_message::args, assert, char_isdigit(), cuberr::er_message::clear_args(), er_spec::code, cuberr::er_va_arg::double_value, er_emergency(), ER_ER_SUBSTITUTE_MSG, ER_FAILED, ER_LOG_UNKNOWN_CODE, ER_MALLOC, er_fmt::fmt, i, cuberr::er_va_arg::int_value, cuberr::er_va_arg::longdouble_value, cuberr::er_va_arg::longlong_value, cuberr::er_message::msg_area, cuberr::er_message::msg_area_size, cuberr::er_message::nargs, NO_ERROR, er_fmt::nspecs, NULL, p, cuberr::er_va_arg::pointer_value, er_spec::spec, er_fmt::spec, SPEC_CODE_LONGLONG, SPEC_CODE_SIZE_T, cuberr::er_va_arg::string_value, and strlen.
Referenced by er_set_internal().
Variable Documentation
FILE* er_Accesslog_fh = NULL static
Definition at line 294 of file error_manager.c.
Referenced by er_final(), and er_log().
const char* er_Accesslog_filename = NULL static
Definition at line 293 of file error_manager.c.
Referenced by er_init(), and er_log().
char er_Accesslog_filename_buff[PATH_MAX] static
Definition at line 292 of file error_manager.c.
Referenced by er_fname_free().
const char* er_Builtin_msg[] static
Definition at line 219 of file error_manager.c.
Referenced by er_final(), and er_init().
char* er_Cached_msg[sizeof(er_Builtin_msg)/sizeof(const char *)] static
Definition at line 281 of file error_manager.c.
unsigned int er_Eid = 0 static
Definition at line 303 of file error_manager.c.
Referenced by er_log().
int er_Errid_not_initialized = 0 static
Definition at line 299 of file error_manager.c.
Referenced by er_errid().
jmp_buf er_Event_jmp_buf static
Definition at line 308 of file error_manager.c.
FILE* er_Event_pipe = NULL static
Definition at line 306 of file error_manager.c.
bool er_Event_started = false static
Definition at line 307 of file error_manager.c.
int er_Exit_ask = ER_EXIT_DEFAULT static
Definition at line 316 of file error_manager.c.
ER_FMT er_Fmt_list[(-ER_LAST_ERROR)+1] static
Definition at line 297 of file error_manager.c.
Referenced by er_final(), er_find_fmt(), and er_init().
int er_Fmt_msg_fail_count = -ER_LAST_ERROR static
Definition at line 298 of file error_manager.c.
PTR_FNERLOG er_Fnlog[ER_MAX_SEVERITY+1] static
Initial value:
= {
  er_log,
  er_log,
  er_log,
  er_log,
  er_log
}
Definition at line 372 of file error_manager.c.
er_log_handler_t er_Handler = NULL static
Definition at line 301 of file error_manager.c.
Referenced by er_register_log_handler().
bool er_Has_sticky_init = false static
Definition at line 314 of file error_manager.c.
bool er_Hasalready_initiated = false static
Definition at line 313 of file error_manager.c.
Referenced by er_is_initialized().
bool er_Is_cached_msg = false static
Definition at line 282 of file error_manager.c.
bool er_Isa_null_device = false static
Definition at line 315 of file error_manager.c.
std::mutex er_Log_file_mutex
Definition at line 142 of file error_manager.c.
Referenced by _er_log_debug(), er_final(), er_init(), er_print_callstack(), er_set_area_error(), and er_set_internal().
bool er_Logfile_opened = false static
Definition at line 312 of file error_manager.c.
std::mutex er_Message_cache_mutex
Definition at line 143 of file error_manager.c.
Referenced by er_find_fmt().
FILE* er_Msglog_fh = NULL static
Definition at line 288 of file error_manager.c.
Referenced by er_final(), and er_log().
const char* er_Msglog_filename = NULL static
Definition at line 287 of file error_manager.c.
Referenced by er_get_msglog_filename(), er_init(), and er_log().
char er_Msglog_filename_buff[PATH_MAX] static
Definition at line 286 of file error_manager.c.
Referenced by er_init().
int er_Print_to_console = ER_DO_NOT_PRINT static
Definition at line 317 of file error_manager.c.
const char* er_severity_string[] = { "FATAL ERROR", "ERROR", "SYNTAX ERROR", "WARNING", "NOTIFICATION" } static
Definition at line 150 of file error_manager.c.
context* er_Singleton_context_p static
Definition at line 328 of file error_manager.c.
Referenced by er_final().
const char* er_unknown_severity = "Unknown severity level" static
Definition at line 152 of file error_manager.c.
SIGNAL_HANDLER_FUNCTION saved_Sig_handler static
Definition at line 309 of file error_manager.c.