CUBRID Engine: src/storage/es.c File Reference
es.c File Reference
#include "config.h"
#include <assert.h>
#include "es.h"
#include "system_parameter.h"
#include "error_manager.h"
#include "es_posix.h"
#include "es_owfs.h"
#include "network_interface_cl.h"
Functions
int es_init (const char *uri)
void es_final (void)
int es_create_file (char *out_uri)
ssize_t es_write_file (const char *uri, const void *buf, size_t count, off_t offset)
ssize_t es_read_file (const char *uri, void *buf, size_t count, off_t offset)
int es_delete_file (const char *uri)
int es_copy_file (const char *in_uri, const char *metaname, char *out_uri)
int es_rename_file (const char *in_uri, const char *metaname, char *out_uri)
off_t es_get_file_size (const char *uri)
Variables
static ES_TYPE es_initialized_type = ES_NONE
Function Documentation
int es_copy_file (const char * in_uri, const char * metaname, char * out_uri)
Definition at line 353 of file es.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_ES_COPY_TO_DIFFERENT_TYPE, ER_ES_GENERAL, ER_ES_INVALID_PATH, ER_ES_NO_LOB_PATH, er_set(), es_get_type(), es_get_type_string(), es_initialized_type, es_log, ES_NONE, ES_OWFS, es_owfs_copy_file(), ES_OWFS_PATH_POS, ES_OWFS_PATH_PREFIX, ES_POSIX, es_posix_copy_file(), ES_POSIX_PATH_POS, ES_POSIX_PATH_PREFIX, and NULL.
Referenced by elo_copy().
int es_create_file (char * out_uri)
Definition at line 140 of file es.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_ES_GENERAL, ER_ES_NO_LOB_PATH, er_set(), es_initialized_type, es_log, ES_OWFS, es_owfs_create_file(), ES_OWFS_PATH_POS, ES_OWFS_PATH_PREFIX, ES_POSIX, es_posix_create_file(), ES_POSIX_PATH_POS, ES_POSIX_PATH_PREFIX, and NULL.
Referenced by elo_create().
int es_delete_file (const char * uri)
Definition at line 301 of file es.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_ES_GENERAL, ER_ES_INVALID_PATH, ER_ES_NO_LOB_PATH, er_set(), es_get_type(), es_initialized_type, es_log, ES_NONE, ES_OWFS, es_owfs_delete_file(), ES_OWFS_PATH_POS, ES_POSIX, es_posix_delete_file(), ES_POSIX_PATH_POS, and NULL.
Referenced by elo_copy(), elo_delete(), tx_lob_locator_clear(), and vacuum_process_log_block().
void es_final (void)
Definition at line 116 of file es.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_ES_GENERAL, er_set(), es_initialized_type, ES_NONE, ES_OWFS, es_owfs_final(), ES_POSIX, and es_posix_final().
Referenced by boot_client_all_finalize(), boot_initialize_client(), boot_restart_client(), boot_server_all_finalize(), and es_init().
off_t es_get_file_size (const char * uri)
Definition at line 479 of file es.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_ES_GENERAL, ER_ES_INVALID_PATH, ER_ES_NO_LOB_PATH, er_set(), es_get_type(), es_initialized_type, ES_LOCAL, es_local_get_file_size(), ES_LOCAL_PATH_POS, es_log, ES_NONE, ES_OWFS, es_owfs_get_file_size(), ES_OWFS_PATH_POS, ES_POSIX, es_posix_get_file_size(), ES_POSIX_PATH_POS, and NULL.
Referenced by elo_size().
int es_init (const char * uri)
Definition at line 53 of file es.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_ES_GENERAL, ER_ES_INVALID_PATH, er_set(), es_final(), es_get_type(), es_initialized_type, ES_NONE, ES_OWFS, es_owfs_init(), ES_POSIX, es_posix_init(), ES_POSIX_PATH_POS, NO_ERROR, and NULL.
Referenced by boot_restart_client(), and boot_restart_server().
ssize_t es_read_file (const char * uri, void * buf, size_t count, off_t offset)
Definition at line 243 of file es.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_ES_GENERAL, ER_ES_INVALID_PATH, ER_ES_NO_LOB_PATH, er_set(), es_get_type(), es_initialized_type, ES_LOCAL, ES_LOCAL_PATH_POS, es_local_read_file(), es_log, ES_NONE, ES_OWFS, ES_OWFS_PATH_POS, es_owfs_read_file(), ES_POSIX, ES_POSIX_PATH_POS, es_posix_read_file(), and NULL.
Referenced by elo_read().
int es_rename_file (const char * in_uri, const char * metaname, char * out_uri)
Definition at line 417 of file es.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_ES_COPY_TO_DIFFERENT_TYPE, ER_ES_GENERAL, ER_ES_INVALID_PATH, ER_ES_NO_LOB_PATH, er_set(), es_get_type(), es_get_type_string(), es_initialized_type, es_log, ES_NONE, ES_OWFS, ES_OWFS_PATH_POS, ES_OWFS_PATH_PREFIX, es_owfs_rename_file(), ES_POSIX, ES_POSIX_PATH_POS, ES_POSIX_PATH_PREFIX, es_posix_rename_file(), and NULL.
Referenced by elo_copy(), and tx_lob_locator_clear().
ssize_t es_write_file (const char * uri, const void * buf, size_t count, off_t offset)
Definition at line 187 of file es.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_ES_GENERAL, ER_ES_INVALID_PATH, ER_ES_NO_LOB_PATH, er_set(), es_get_type(), es_initialized_type, es_log, ES_NONE, ES_OWFS, ES_OWFS_PATH_POS, es_owfs_write_file(), ES_POSIX, ES_POSIX_PATH_POS, es_posix_write_file(), and NULL.
Referenced by elo_write().
Variable Documentation
ES_TYPE es_initialized_type = ES_NONE static
Definition at line 45 of file es.c.
Referenced by es_copy_file(), es_create_file(), es_delete_file(), es_final(), es_get_file_size(), es_init(), es_read_file(), es_rename_file(), and es_write_file().