CUBRID Engine: src/storage/es_posix.c File Reference
es_posix.c File Reference
#include "config.h"
#include <stdio.h>
#include <errno.h>
#include <fcntl.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <assert.h>
#include <unistd.h>
#include <sys/vfs.h>
#include <string.h>
#include "porting.h"
#include "thread_compat.hpp"
#include "error_manager.h"
#include "system_parameter.h"
#include "error_code.h"
#include "es_posix.h"
Functions
int es_posix_init (const char *base_path)
void es_posix_final (void)
int es_local_read_file (const char *path, void *buf, size_t count, off_t offset)
off_t es_local_get_file_size (const char *path)
Function Documentation
off_t es_local_get_file_size (const char * path)
Definition at line 713 of file es_posix.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_ES_GENERAL, er_set_with_oserror(), and es_log.
Referenced by es_get_file_size().
int es_local_read_file (const char * path, void * buf, size_t count, off_t offset)
Definition at line 647 of file es_posix.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_ES_GENERAL, er_set_with_oserror(), and es_log.
Referenced by es_read_file().
void es_posix_final (void)
Definition at line 232 of file es_posix.c.
References ARG_FILE_LINE, assert, cubregex::count(), ER_ERROR_SEVERITY, ER_ES_FILE_NOT_FOUND, ER_ES_GENERAL, ER_ES_INVALID_PATH, er_set(), er_set_with_oserror(), es_log, NO_ERROR, os_rename_file(), and PATH_SEPARATOR.
Referenced by es_final().
int es_posix_init (const char * base_path)
Definition at line 204 of file es_posix.c.
References ARG_FILE_LINE, ER_ES_GENERAL, ER_NOTIFICATION_SEVERITY, er_set_with_oserror(), NO_ERROR, and strlcpy().
Referenced by es_init().