CUBRID Engine: src/storage/es_owfs.c File Reference
es_owfs.c File Reference
#include "config.h"
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include "porting.h"
#include "error_code.h"
#include "error_manager.h"
#include "es_owfs.h"
Functions
int es_owfs_init (const char *base_path)
void es_owfs_final (void)
int es_owfs_create_file (char *new_path)
ssize_t es_owfs_write_file (const char *path, const void *buf, size_t count, off_t offset)
ssize_t es_owfs_read_file (const char *path, void *buf, size_t count, off_t offset)
int es_owfs_delete_file (const char *path)
int es_owfs_copy_file (const char *src_path, const char *metaname, char *new_path)
int es_owfs_rename_file (const char *src_path, const char *metaname, char *new_path)
off_t es_owfs_get_file_size (const char *path)
Function Documentation
int es_owfs_copy_file (const char * src_path, const char * metaname, char * new_path)
Definition at line 901 of file es_owfs.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_ES_GENERAL, and er_set().
Referenced by es_copy_file().
int es_owfs_create_file (char * new_path)
Definition at line 873 of file es_owfs.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_ES_GENERAL, and er_set().
Referenced by es_create_file().
int es_owfs_delete_file (const char * path)
Definition at line 894 of file es_owfs.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_ES_GENERAL, and er_set().
Referenced by es_delete_file().
void es_owfs_final (void)
Definition at line 867 of file es_owfs.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_ES_GENERAL, and er_set().
Referenced by es_final().
off_t es_owfs_get_file_size (const char * path)
Definition at line 915 of file es_owfs.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_ES_GENERAL, and er_set().
Referenced by es_get_file_size().
int es_owfs_init (const char * base_path)
Definition at line 860 of file es_owfs.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_ES_GENERAL, and er_set().
Referenced by es_init().
ssize_t es_owfs_read_file (const char * path, void * buf, size_t count, off_t offset)
Definition at line 887 of file es_owfs.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_ES_GENERAL, and er_set().
Referenced by es_read_file().
int es_owfs_rename_file (const char * src_path, const char * metaname, char * new_path)
Definition at line 908 of file es_owfs.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_ES_GENERAL, and er_set().
Referenced by es_rename_file().
ssize_t es_owfs_write_file (const char * path, const void * buf, size_t count, off_t offset)
Definition at line 880 of file es_owfs.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_ES_GENERAL, and er_set().
Referenced by es_write_file().