CUBRID Engine: src/storage/es_posix.h File Reference
es_posix.h File Reference
#include <sys/types.h>
#include "es_common.h"
Macros
#define ES_PATH_SEPARATOR "/"
#define ES_POSIX_HASH1 (769)
#define ES_POSIX_HASH2 (381)
Functions
int es_posix_init (const char *base_path)
void es_posix_final (void)
int es_local_read_file (const char *path, void *buf, size_t count, off_t offset)
off_t es_local_get_file_size (const char *path)
Macro Definition Documentation
#define ES_PATH_SEPARATOR "/"
Definition at line 33 of file es_posix.h.
#define ES_POSIX_HASH1 (769)
Definition at line 36 of file es_posix.h.
#define ES_POSIX_HASH2 (381)
Definition at line 37 of file es_posix.h.
Function Documentation
off_t es_local_get_file_size (const char * path)
Definition at line 713 of file es_posix.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_ES_GENERAL, er_set_with_oserror(), and es_log.
Referenced by es_get_file_size().
int es_local_read_file (const char * path, void * buf, size_t count, off_t offset)
Definition at line 647 of file es_posix.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_ES_GENERAL, er_set_with_oserror(), and es_log.
Referenced by es_read_file().
void es_posix_final (void)
Definition at line 232 of file es_posix.c.
References ARG_FILE_LINE, assert, cubregex::count(), ER_ERROR_SEVERITY, ER_ES_FILE_NOT_FOUND, ER_ES_GENERAL, ER_ES_INVALID_PATH, er_set(), er_set_with_oserror(), es_log, NO_ERROR, os_rename_file(), and PATH_SEPARATOR.
Referenced by es_final().
int es_posix_init (const char * base_path)
Definition at line 204 of file es_posix.c.
References ARG_FILE_LINE, ER_ES_GENERAL, ER_NOTIFICATION_SEVERITY, er_set_with_oserror(), NO_ERROR, and strlcpy().
Referenced by es_init().