CUBRID Engine: src/storage/es_common.c File Reference
es_common.c File Reference
#include "config.h"
#include <string.h>
#include <sys/types.h>
#include <assert.h>
#include <sys/time.h>
#include "porting.h"
#include "memory_hash.h"
#include "es_common.h"
Functions
ES_TYPE es_get_type (const char *uri)
const char * es_get_type_string (ES_TYPE type)
unsigned int es_name_hash_func (int size, const char *name)
UINT64 es_get_unique_num (void)
Function Documentation
ES_TYPE es_get_type (const char * uri)
Definition at line 43 of file es_common.c.
References ES_LOCAL, ES_LOCAL_PATH_PREFIX, ES_NONE, ES_OWFS, ES_OWFS_PATH_PREFIX, ES_POSIX, and ES_POSIX_PATH_PREFIX.
Referenced by boot_initialize_client(), db_blob_from_file(), db_clob_from_file(), elo_copy(), elo_create(), elo_delete(), es_copy_file(), es_delete_file(), es_get_file_size(), es_init(), es_read_file(), es_rename_file(), es_write_file(), xboot_copy(), and xboot_initialize_server().
const char* es_get_type_string (ES_TYPE type)
Definition at line 67 of file es_common.c.
References ES_LOCAL, ES_LOCAL_PATH_PREFIX, ES_OWFS, ES_OWFS_PATH_PREFIX, ES_POSIX, and ES_POSIX_PATH_PREFIX.
Referenced by es_copy_file(), and es_rename_file().
UINT64 es_get_unique_num (void)
Definition at line 102 of file es_common.c.
References NULL.
unsigned int es_name_hash_func (int size, const char * name)
Definition at line 92 of file es_common.c.
References assert, and mht_5strhash().