CUBRID Engine: src/executables/esql_hash.h File Reference
esql_hash.h File Reference
Classes
struct hash_tab_s
Typedefs
typedef unsigned(* HT_HASH_FN) (void *)
typedef int(* HT_CMP_FN) (void *, void *)
typedef void(* HT_FREE_FN) (void *)
typedef struct hash_tab_s HASH_TAB
Functions
HASH_TAB * es_ht_make_table (unsigned maxsym, HT_HASH_FN hash, HT_CMP_FN cmp)
void * es_ht_alloc_new_symbol (int size)
void es_ht_free_symbol (void *sym)
Typedef Documentation
typedef struct hash_tab_s HASH_TAB
Definition at line 33 of file esql_hash.h.
typedef int(* HT_CMP_FN) (void *, void *)
Definition at line 30 of file esql_hash.h.
typedef void(* HT_FREE_FN) (void *)
Definition at line 31 of file esql_hash.h.
typedef unsigned(* HT_HASH_FN) (void *)
Definition at line 29 of file esql_hash.h.
Function Documentation
void* es_ht_alloc_new_symbol (int size)
Definition at line 351 of file esql_hash.c.
References NULL, and pp_malloc().
Referenced by pp_new_cursor(), pp_new_stmt(), pp_new_structdef(), and pp_new_symbol().
void es_ht_free_symbol (void * sym)
Definition at line 369 of file esql_hash.c.
References free_and_init.
Referenced by pp_discard_structdef(), pp_discard_symbol(), pp_free_cursor(), pp_free_stmt(), and pp_symbol_finish().
HASH_TAB* es_ht_make_table (unsigned maxsym, HT_HASH_FN hash, HT_CMP_FN cmp)
Definition at line 383 of file esql_hash.c.
References hash_tab_s::add_symbol, hash_tab_impl::cmp, es_ht_add_symbol(), es_ht_find_symbol(), es_ht_free_table(), es_ht_get_symbol_count(), es_ht_next_symbol(), es_ht_print_table(), es_ht_remove_symbol(), hash_tab_s::find_symbol, hash_tab_s::free_table, hash_tab_s::get_symbol_count, hash_tab_impl::hash, hash_tab_impl::ifs, hash_tab_s::next_symbol, hash_tab_impl::numsyms, p, pp_malloc(), hash_tab_s::print_table, hash_tab_s::remove_symbol, and hash_tab_impl::size.
Referenced by pp_cursor_init(), and pp_new_symtab().