CUBRID Engine: src/executables/esql_misc.c File Reference
esql_misc.c File Reference
#include "config.h"
#include <stdlib.h>
#include <stdio.h>
#include "chartype.h"
#include "util_func.h"
#include "misc_string.h"
#include "memory_alloc.h"
#include "intl_support.h"
#include "esql_misc.h"
#include "esql_translate.h"
Classes
struct generic
Typedefs
typedef struct generic GENERIC
Functions
static void tr_prelude (void)
static void grow_ptr_vec (PTR_VEC *vec)
unsigned int pp_generic_case_hash (void *p)
unsigned int pp_generic_hash (void *p)
int pp_generic_case_cmp (void *p1, void *p2)
int pp_generic_cmp (void *p1, void *p2)
void pp_startup (void)
void pp_finish (void)
PTR_VEC * pp_new_ptr_vec (PTR_VEC *vec)
void pp_free_ptr_vec (PTR_VEC *vec)
PTR_VEC * pp_add_ptr (PTR_VEC *vec, void *new_elem)
int pp_ptr_vec_n_elems (PTR_VEC *vec)
void ** pp_ptr_vec_elems (PTR_VEC *vec)
void * pp_malloc (int n)
char * pp_strdup (const char *str)
Variables
FILE * esql_yyout
varstring pp_subscript_buf
varstring pp_host_var_buf
Typedef Documentation
typedef struct generic GENERIC
Definition at line 50 of file esql_misc.c.
Function Documentation
static void grow_ptr_vec (PTR_VEC * vec) static
Definition at line 260 of file esql_misc.c.
References ptr_vec::chunk_size, ptr_vec::elems, esql_yyverror(), EX_MISC_SET, ptr_vec::inline_elems, ptr_vec::max_elems, MSG_OUT_OF_MEMORY, ptr_vec::n_elems, NULL, pp_get_msg(), and pp_malloc().
Referenced by pp_add_ptr().
PTR_VEC* pp_add_ptr (PTR_VEC * vec, void * new_elem)
Definition at line 294 of file esql_misc.c.
References ptr_vec::elems, grow_ptr_vec(), ptr_vec::max_elems, ptr_vec::n_elems, and NULL.
void pp_finish (void)
Definition at line 163 of file esql_misc.c.
References esql_yyout, pp_cursor_finish(), pp_decl_finish(), pp_hv_finish(), pp_symbol_finish(), pp_symbol_stats(), and vs_free().
void pp_free_ptr_vec (PTR_VEC * vec)
Definition at line 231 of file esql_misc.c.
References ptr_vec::elems, free_and_init, ptr_vec::heap_allocated, i, ptr_vec::inline_elems, ptr_vec::n_elems, and NULL.
int pp_generic_case_cmp (void * p1, void * p2)
Definition at line 115 of file esql_misc.c.
References intl_mbs_casecmp(), and generic::name.
Referenced by pp_cursor_init().
unsigned int pp_generic_case_hash (void * p)
Definition at line 70 of file esql_misc.c.
References char_tolower(), hashpjw(), i, and generic::name.
Referenced by pp_cursor_init().
int pp_generic_cmp (void * p1, void * p2)
Definition at line 132 of file esql_misc.c.
References generic::name.
Referenced by pp_new_symtab().
unsigned int pp_generic_hash (void * p)
Definition at line 99 of file esql_misc.c.
References hashpjw(), and generic::name.
Referenced by pp_new_symtab().
void* pp_malloc (int n)
Definition at line 353 of file esql_misc.c.
References EX_MISC_SET, MSG_OUT_OF_MEMORY, NULL, pp_get_msg(), and prog_name.
Referenced by emit_put_db_value(), es_ht_alloc_new_symbol(), es_ht_make_table(), es_ht_print_table(), escape_string(), grow_ptr_vec(), pp_add_host_ref(), pp_decl_init(), and pp_strdup().
PTR_VEC* pp_new_ptr_vec (PTR_VEC * vec)
Definition at line 197 of file esql_misc.c.
References ptr_vec::chunk_size, ptr_vec::elems, esql_yyverror(), EX_MISC_SET, FALSE, ptr_vec::heap_allocated, ptr_vec::inline_elems, ptr_vec::max_elems, MSG_OUT_OF_MEMORY, ptr_vec::n_elems, NULL, pp_get_msg(), PTR_VEC_CHUNK_SIZE, and TRUE.
void** pp_ptr_vec_elems (PTR_VEC * vec)
Definition at line 335 of file esql_misc.c.
References ptr_vec::elems, ptr_vec::n_elems, and NULL.
int pp_ptr_vec_n_elems (PTR_VEC * vec)
Definition at line 316 of file esql_misc.c.
References ptr_vec::n_elems, and NULL.
void pp_startup (void)
Definition at line 145 of file esql_misc.c.
References esql_Translate_table, esql_yyout, pp_cursor_init(), pp_decl_init(), pp_hv_init(), pp_symbol_init(), tr_prelude(), esql_translate_table_s::tr_set_line_terminator, esql_translate_table_s::tr_set_out_stream, and vs_new().
char* pp_strdup (const char * str)
Definition at line 372 of file esql_misc.c.
References NULL, pp_malloc(), and strlen.
Referenced by es_write_log(), pp_check_type(), pp_clone_type(), and pp_new_pseudo_def().
static void tr_prelude (void) static
Definition at line 180 of file esql_misc.c.
References esql_yyout, pp_include_file, and pp_varchar2.
Referenced by pp_startup().
Variable Documentation
FILE* esql_yyout
Referenced by pp_finish(), pp_startup(), and tr_prelude().
varstring pp_host_var_buf
Definition at line 58 of file esql_misc.c.
varstring pp_subscript_buf
Definition at line 57 of file esql_misc.c.