CUBRID Engine: src/executables/esql_whenever.c File Reference
esql_whenever.c File Reference
#include <stdlib.h>
#include "misc_string.h"
#include "esql_misc.h"
#include "memory_alloc.h"
#include "esql_translate.h"
Macros
#define LAST_REF(condition)
Functions
static void free_last_referenced_name (WHENEVER_SCOPE *scope, WHENEVER_SCOPE *new_scope)
void pp_init_whenever_scope (WHENEVER_SCOPE *scope, WHENEVER_SCOPE *old_scope)
void pp_finish_whenever_scope (WHENEVER_SCOPE *scope, WHENEVER_SCOPE *new_scope)
Variables
static WHENEVER_SCOPE default_whenever_scope_initializer = { {{CONTINUE, NULL}, {CONTINUE, NULL}, {CONTINUE, NULL}} }
Macro Definition Documentation
#define LAST_REF (condition)
Value:
((name = scope->cond[condition].name) != NULL                       \
     && (new_scope == NULL || name != new_scope->cond[condition].name))
Definition at line 36 of file esql_whenever.c.
Referenced by free_last_referenced_name().
Function Documentation
static void free_last_referenced_name (WHENEVER_SCOPE * scope, WHENEVER_SCOPE * new_scope) static
Definition at line 41 of file esql_whenever.c.
References free_and_init, LAST_REF, NOT_FOUND, SQLERROR, and SQLWARNING.
Referenced by pp_finish_whenever_scope().
void pp_finish_whenever_scope (WHENEVER_SCOPE * scope, WHENEVER_SCOPE * new_scope)
Definition at line 89 of file esql_whenever.c.
References whenever_action::action, whenever_scope::cond, default_whenever_scope_initializer, esql_Translate_table, free_last_referenced_name(), whenever_action::name, NOT_FOUND, NULL, SQLERROR, SQLWARNING, and esql_translate_table_s::tr_whenever.
Referenced by pp_pop_name_scope().
void pp_init_whenever_scope (WHENEVER_SCOPE * scope, WHENEVER_SCOPE * old_scope)
Definition at line 67 of file esql_whenever.c.
References default_whenever_scope_initializer, and NULL.
Referenced by pp_push_name_scope().
Variable Documentation
WHENEVER_SCOPE default_whenever_scope_initializer = { {{CONTINUE, NULL}, {CONTINUE, NULL}, {CONTINUE, NULL}} } static
Definition at line 34 of file esql_whenever.c.
Referenced by pp_finish_whenever_scope(), and pp_init_whenever_scope().