CUBRID Engine: src/executables/esql_gadget.h File Reference
esql_gadget.h File Reference
#include "config.h"
#include "dbtype_def.h"
Classes
struct attr_val
struct db_gadget
Typedefs
typedef struct db_gadget DB_GADGET
typedef struct attr_val ATTR_VAL
Functions
DB_GADGET * db_gadget_create (const char *class_name, const char *attribute_names[])
void db_gadget_destroy (DB_GADGET *gadget)
int db_gadget_bind (DB_GADGET *gadget, const char *attribute_name, DB_VALUE *dbval)
DB_OBJECT * db_gadget_exec (DB_GADGET *gadget, int num_dbvals, DB_VALUE dbvals[])
Typedef Documentation
typedef struct attr_val ATTR_VAL
Definition at line 34 of file esql_gadget.h.
typedef struct db_gadget DB_GADGET
Definition at line 33 of file esql_gadget.h.
Function Documentation
int db_gadget_bind (DB_GADGET * gadget, const char * attribute_name, DB_VALUE * dbval)
Definition at line 205 of file esql_gadget.c.
References ARG_FILE_LINE, attr_val::attr_desc, db_gadget::attrs, db_gadget::class_, db_attdesc_domain(), db_get_class_name(), db_value_clear(), ER_ERROR_SEVERITY, ER_GADGET_INVALID, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), ER_SM_UNKNOWN_ATTRIBUTE, free_and_init, gadget_attr_index(), i, NO_ERROR, NOT_FOUND, NULL, tp_value_coerce(), and attr_val::value.
Referenced by uci_static().
DB_GADGET* db_gadget_create (const char * class_name, const char * attribute_names[])
Definition at line 51 of file esql_gadget.c.
References ARG_FILE_LINE, attr_val::attr_desc, db_gadget::attrs, db_gadget::class_, db_attribute_name(), db_attribute_next(), db_find_class(), db_gadget_destroy(), db_get_attribute_descriptor(), db_get_attributes(), db_is_vclass(), ER_ERROR_SEVERITY, ER_GADGET_NO_VCLASSES, ER_LC_UNKNOWN_CLASSNAME, ER_OBJ_DUPLICATE_ASSIGNMENT, er_set(), error(), gadget_attr_index(), i, NOT_FOUND, NULL, db_gadget::num_attrs, and attr_val::value.
Referenced by uci_static().
void db_gadget_destroy (DB_GADGET * gadget)
Definition at line 163 of file esql_gadget.c.
References attr_val::attr_desc, db_gadget::attrs, db_free_attribute_descriptor(), db_value_clear(), free_and_init, i, NULL, db_gadget::num_attrs, and attr_val::value.
Referenced by db_gadget_create(), free_repetitive(), and uci_static().
DB_OBJECT* db_gadget_exec (DB_GADGET * gadget, int num_dbvals, DB_VALUE dbvals[])
Definition at line 255 of file esql_gadget.c.
References ARG_FILE_LINE, attr_val::attr_desc, db_gadget::attrs, db_gadget::class_, dbt_abort_object(), dbt_create_object_internal(), dbt_dput_internal(), dbt_finish_object(), ER_ERROR_SEVERITY, ER_GADGET_ATTRS_VALS_NE, ER_GADGET_INVALID, er_set(), error(), i, NO_ERROR, NULL, db_gadget::num_attrs, and attr_val::value.
Referenced by uci_static().