CUBRID Engine: src/query/execute_schema.h File Reference
execute_schema.h File Reference
#include "dbi.h"
#include "schema_manager.h"
Classes
struct client_update_class_info
struct client_update_info
Macros
#define UNIQUE_PARTITION_SAVEPOINT_GRANT "pARTITIONgRANT"
#define UNIQUE_PARTITION_SAVEPOINT_REVOKE "pARTITIONrEVOKE"
#define UNIQUE_PARTITION_SAVEPOINT_RENAME "pARTITIONrENAME"
#define UNIQUE_PARTITION_SAVEPOINT_DROP "pARTITIONdROP"
#define UNIQUE_PARTITION_SAVEPOINT_OWNER "pARTITIONoWNER"
#define UNIQUE_PARTITION_SAVEPOINT_INDEX "pARTITIONiNDEX"
#define UNIQUE_PARTITION_SAVEPOINT_ALTER "pARTITIONaLTER"
#define PARTITION_CATALOG_CLASS "_db_partition"
#define PARTITION_VARCHAR_LEN (DB_MAX_IDENTIFIER_LENGTH)
#define CLASS_ATT_NAME "class_name"
#define CLASS_IS_PARTITION "partition_of"
#define CHECK_PARTITION_NONE 0x0000
#define CHECK_PARTITION_PARENT 0x0001
#define CHECK_PARTITION_SUBS 0x0010
Typedefs
typedef struct client_update_info CLIENT_UPDATE_INFO
typedef struct client_update_class_info CLIENT_UPDATE_CLASS_INFO
Functions
int do_drop_partitioned_class (MOP class_, int drop_sub_flag, bool is_cascade_constraints)
int do_is_partitioned_subclass (int *is_partitioned, const char *classname, char *keyattr)
int do_get_partition_parent (DB_OBJECT *const classop, MOP *const parentop)
int do_rename_partition (MOP old_class, const char *newname)
int do_check_partitioned_class (DB_OBJECT *classop, int check_map, char *keyattr)
int do_get_partition_keycol (char *keycol, MOP class_)
int do_get_partition_size (MOP class_)
int do_drop_partition_list (MOP class_, PT_NODE *name_list, DB_CTMPL *tmpl)
int do_add_queries (PARSER_CONTEXT *parser, DB_CTMPL *ctemplate, const PT_NODE *queries)
int do_add_attributes (PARSER_CONTEXT *parser, DB_CTMPL *ctemplate, PT_NODE *atts, PT_NODE *constraints, DB_QUERY_TYPE *create_select_columns)
int do_add_constraints (DB_CTMPL *ctemplate, PT_NODE *constraints)
int do_check_fk_constraints (DB_CTMPL *ctemplate, PT_NODE *constraints)
int do_add_methods (PARSER_CONTEXT *parser, DB_CTMPL *ctemplate, PT_NODE *methods)
int do_add_method_files (const PARSER_CONTEXT *parser, DB_CTMPL *ctemplate, PT_NODE *method_files)
int do_add_resolutions (const PARSER_CONTEXT *parser, DB_CTMPL *ctemplate, const PT_NODE *resolution)
int do_add_supers (const PARSER_CONTEXT *parser, DB_CTMPL *ctemplate, const PT_NODE *supers)
int do_set_object_id (const PARSER_CONTEXT *parser, DB_CTMPL *ctemplate, PT_NODE *object_id_list)
int do_create_local (PARSER_CONTEXT *parser, DB_CTMPL *ctemplate, PT_NODE *pt_node, DB_QUERY_TYPE *create_select_columns)
int do_create_entity (PARSER_CONTEXT *parser, PT_NODE *node)
int do_check_rows_for_null (MOP class_mop, const char *att_name, bool *has_nulls)
int do_recreate_func_index_constr (PARSER_CONTEXT *parser, SM_CONSTRAINT_INFO *constr, SM_FUNCTION_INFO *func_index_info, PT_NODE *alter, const char *src_cls_name, const char *new_cls_name)
int do_recreate_filter_index_constr (PARSER_CONTEXT *parser, SM_PREDICATE_INFO *filter_index_info, PT_NODE *alter, const char *src_cls_name, const char *new_cls_name)
Macro Definition Documentation
#define CHECK_PARTITION_NONE 0x0000
Definition at line 48 of file execute_schema.h.
Referenced by db_dput(), db_put(), dbt_dput(), dbt_put(), and rs_set_db_value().
#define CHECK_PARTITION_PARENT 0x0001
Definition at line 49 of file execute_schema.h.
Referenced by db_create(), dbt_create_object(), and do_check_partitioned_class().
#define CHECK_PARTITION_SUBS 0x0010
Definition at line 50 of file execute_schema.h.
Referenced by db_add_super(), db_create(), db_drop_attribute(), db_drop_class_ex(), db_drop_super(), db_drop_super_connect(), db_grant(), db_rename(), db_rename_attribute(), db_rename_class(), db_revoke(), dbt_create_object(), and do_check_partitioned_class().
#define CLASS_ATT_NAME "class_name"
Definition at line 45 of file execute_schema.h.
#define CLASS_IS_PARTITION "partition_of"
Definition at line 46 of file execute_schema.h.
#define PARTITION_CATALOG_CLASS "_db_partition"
Definition at line 43 of file execute_schema.h.
#define PARTITION_VARCHAR_LEN (DB_MAX_IDENTIFIER_LENGTH)
Definition at line 44 of file execute_schema.h.
Referenced by do_create_partition(), do_rename_partition(), and pt_node_to_partition_info().
#define UNIQUE_PARTITION_SAVEPOINT_ALTER "pARTITIONaLTER"
Definition at line 42 of file execute_schema.h.
Referenced by do_alter_one_clause_with_template().
#define UNIQUE_PARTITION_SAVEPOINT_DROP "pARTITIONdROP"
Definition at line 39 of file execute_schema.h.
Referenced by sm_delete_class_mop().
#define UNIQUE_PARTITION_SAVEPOINT_GRANT "pARTITIONgRANT"
Definition at line 36 of file execute_schema.h.
Referenced by au_grant().
#define UNIQUE_PARTITION_SAVEPOINT_INDEX "pARTITIONiNDEX"
Definition at line 41 of file execute_schema.h.
Referenced by sm_add_secondary_index_on_partition(), sm_drop_index(), and sm_exist_index().
#define UNIQUE_PARTITION_SAVEPOINT_OWNER "pARTITIONoWNER"
Definition at line 40 of file execute_schema.h.
Referenced by au_change_owner_method().
#define UNIQUE_PARTITION_SAVEPOINT_RENAME "pARTITIONrENAME"
Definition at line 38 of file execute_schema.h.
Referenced by sm_rename_class().
#define UNIQUE_PARTITION_SAVEPOINT_REVOKE "pARTITIONrEVOKE"
Definition at line 37 of file execute_schema.h.
Referenced by au_revoke().
Typedef Documentation
typedef struct client_update_class_info CLIENT_UPDATE_CLASS_INFO
Definition at line 53 of file execute_schema.h.
typedef struct client_update_info CLIENT_UPDATE_INFO
Definition at line 52 of file execute_schema.h.
Function Documentation
int do_add_attributes (PARSER_CONTEXT * parser, DB_CTMPL * ctemplate, PT_NODE * atts, PT_NODE * constraints, DB_QUERY_TYPE * create_select_columns)
Definition at line 7332 of file execute_schema.c.
References db_query_format_name(), db_query_format_next(), do_add_attribute(), do_add_attribute_from_select_column(), error(), get_attr_name(), get_attribute_with_name(), parser_node::next, NO_ERROR, NULL, and query_get_column_with_name().
Referenced by do_alter_one_clause_with_template(), and do_create_local().
int do_add_constraints (DB_CTMPL * ctemplate, PT_NODE * constraints)
Definition at line 7494 of file execute_schema.c.
References add_foreign_key(), ARG_FILE_LINE, assert, pt_foreign_key_info::attrs, pt_constraint_info::comment, pt_statement_info::constraint, DB_CONSTRAINT_PRIMARY_KEY, DB_CONSTRAINT_REVERSE_UNIQUE, DB_CONSTRAINT_UNIQUE, er_errid(), ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), pt_constraint_info::foreign_key, free_and_init, i, if(), parser_node::info, pt_name_info::meta_class, pt_constraint_info::name, pt_statement_info::name, parser_node::next, NO_ERROR, parser_node::node_type, NULL, pt_name_info::original, sm_attr_properties_chg::p, pt_constraint_info::primary_key, PT_CONSTRAIN_FOREIGN_KEY, PT_CONSTRAIN_PRIMARY_KEY, PT_CONSTRAIN_UNIQUE, pt_length_of_list(), PT_META_ATTR, PT_NAME_INFO_DESC, PT_NAME_INFO_IS_FLAGED, PT_VALUE, PT_VALUE_GET_BYTES, SM_NORMAL_INDEX, sm_produce_constraint_name_tmpl(), smt_add_constraint(), pt_constraint_info::type, pt_constraint_info::un, and pt_constraint_info::unique.
Referenced by do_alter_one_clause_with_template(), and do_create_local().
int do_add_method_files (const PARSER_CONTEXT * parser, DB_CTMPL * ctemplate, PT_NODE * method_files)
Definition at line 8047 of file execute_schema.c.
References parser_varchar::bytes, pt_value_info::data_value, dbt_add_method_file(), error(), pt_statement_info::file_path, parser_node::info, parser_node::next, NO_ERROR, parser_node::node_type, NULL, PT_FILE_PATH, PT_TYPE_CHAR, PT_TYPE_NCHAR, PT_TYPE_VARCHAR, PT_TYPE_VARNCHAR, PT_VALUE, pt_data_value::str, pt_file_path_info::string, parser_node::type_enum, and pt_statement_info::value.
Referenced by do_alter_one_clause_with_template(), and do_create_local().
int do_add_methods (PARSER_CONTEXT * parser, DB_CTMPL * ctemplate, PT_NODE * methods)
Definition at line 7872 of file execute_schema.c.
References assert, parser_node::data_type, dbt_add_class_method(), dbt_add_method(), er_errid(), ER_GENERIC_ERROR, error(), pt_method_def_info::function_name, parser_node::info, pt_method_def_info::method_args_list, pt_statement_info::method_def, pt_method_def_info::method_name, pt_method_def_info::mthd_type, sm_template::name, pt_statement_info::name, parser_node::next, NO_ERROR, NULL, pt_name_info::original, pt_data_type_to_db_domain(), PT_IS_COLLECTION_TYPE, PT_META_ATTR, pt_node_to_db_domain(), PT_TYPE_NONE, smt_add_set_argument_domain(), smt_assign_argument_domain(), parser_node::type_enum, and validate_attribute_domain().
Referenced by do_alter_one_clause_with_template(), and do_create_local().
int do_add_queries (PARSER_CONTEXT * parser, DB_CTMPL * ctemplate, const PT_NODE * queries)
Definition at line 8242 of file execute_schema.c.
References add_union_query(), error(), parser_node::next, and NO_ERROR.
Referenced by do_alter_one_clause_with_template(), and do_create_local().
int do_add_resolutions (const PARSER_CONTEXT * parser, DB_CTMPL * ctemplate, const PT_NODE * resolution)
Definition at line 8121 of file execute_schema.c.
References pt_resolution_info::as_attr_mthd_name, assert, pt_resolution_info::attr_mthd_name, pt_resolution_info::attr_type, db_find_class(), dbt_add_class_resolution(), dbt_add_resolution(), er_errid(), error(), parser_node::info, pt_statement_info::name, parser_node::next, NO_ERROR, NULL, pt_resolution_info::of_sup_class_name, pt_name_info::original, PT_META_ATTR, and pt_statement_info::resolution.
Referenced by do_alter_one_clause_with_template(), and do_create_local().
int do_add_supers (const PARSER_CONTEXT * parser, DB_CTMPL * ctemplate, const PT_NODE * supers)
Definition at line 8083 of file execute_schema.c.
References assert, db_find_class(), dbt_add_super(), er_errid(), error(), parser_node::info, pt_statement_info::name, parser_node::next, NO_ERROR, NULL, and pt_name_info::original.
Referenced by do_alter_one_clause_with_template(), and do_create_local().
int do_check_fk_constraints (DB_CTMPL * ctemplate, PT_NODE * constraints)
Definition at line 7844 of file execute_schema.c.
References assert_release, do_check_fk_constraints_internal(), ER_FAILED, NULL, and sm_template::partition.
Referenced by dbt_constrain_non_null(), do_alter_clause_change_attribute(), do_alter_one_clause_with_template(), do_alter_partitioning_pre(), do_create_local(), and sm_add_constraint().
int do_check_partitioned_class (DB_OBJECT * classop, int check_map, char * keyattr)
Definition at line 4294 of file execute_schema.c.
References ARG_FILE_LINE, CHECK_PARTITION_PARENT, CHECK_PARTITION_SUBS, DB_MAX_IDENTIFIER_LENGTH, ER_ERROR_SEVERITY, ER_NOT_ALLOWED_ACCESS_TO_PARTITION, er_set(), error(), intl_identifier_casecmp(), NO_ERROR, NULL, and sm_partitioned_class_type().
Referenced by db_add_super(), db_create(), db_dput(), db_drop_attribute(), db_drop_class_ex(), db_drop_super(), db_drop_super_connect(), db_grant(), db_put(), db_rename(), db_rename_attribute(), db_rename_class(), db_revoke(), dbt_create_object(), dbt_dput(), dbt_put(), and rs_set_db_value().
int do_check_rows_for_null (MOP class_mop, const char * att_name, bool * has_nulls)
Definition at line 14022 of file execute_schema.c.
References ARG_FILE_LINE, assert, cubregex::count(), db_close_session(), db_compile_statement(), db_execute_statement_local(), db_get_class_name(), db_get_errors(), db_get_int(), DB_IS_NULL, db_make_null(), db_open_buffer(), db_query_end(), db_query_first_tuple(), db_query_get_tuple_value(), db_query_set_copy_tplvalue(), db_statement_count(), db_query_type::db_type, DB_TYPE_INTEGER, db_value_clear(), DB_VALUE_DOMAIN_TYPE, er_errid(), ER_ERROR_SEVERITY, er_set(), ER_UNEXPECTED, error(), NO_ERROR, NULL, db_query_result::query_type, and SM_MAX_IDENTIFIER_LENGTH.
Referenced by db_constrain_non_null(), and smt_add_constraint().
int do_create_entity (PARSER_CONTEXT * parser, PT_NODE * node)
Definition at line 8566 of file execute_schema.c.
References ARG_FILE_LINE, assert, parser_varchar::bytes, CHECK_MODIFICATION_ERROR, db_value_slist::class_obj, sm_class::collation_id, sm_class::comment, pt_statement_info::create_entity, pt_create_entity_info::create_index, pt_create_entity_info::create_like, pt_create_entity_info::create_select, pt_create_entity_info::create_select_action, pt_value_info::data_value, DB_DEFAULT_PRECISION, db_find_class(), db_free_query_format(), DB_MAX_VARCHAR_PRECISION, DB_MAX_VARNCHAR_PRECISION, db_query_format_next(), DB_TYPE_VARCHAR, DB_TYPE_VARNCHAR, dbt_abort_class(), dbt_copy_class(), dbt_create_class(), dbt_create_vclass(), dbt_finish_class(), do_copy_indexes(), do_create_index(), do_create_local(), do_create_partition(), do_is_partitioned_subclass(), db_query_type::domain, drop_class_name(), pt_create_entity_info::entity_name, pt_create_entity_info::entity_type, er_clear(), er_errid(), ER_ERROR_SEVERITY, ER_FAILED, ER_GENERIC_ERROR, er_get_severity(), ER_INHERIT_FROM_PARTITION_TABLE, ER_INVALID_PARTITION_REQUEST, ER_LC_UNKNOWN_CLASSNAME, ER_LK_UNILATERALLY_ABORTED, er_set(), ER_WARNING_SEVERITY, error(), execute_create_select_query(), file_apply_tde_to_class_files(), sm_class::flags, pt_data_value::i, pr_type::id, if(), pt_create_entity_info::if_not_exists, pt_statement_info::index, pt_index_info::indexed_class, parser_node::info, sm_partition_alter_info::keycol, LANG_SYS_CODESET, LANG_SYS_COLLATION, locator_create_heap_if_needed(), locator_flush_class(), pt_statement_info::name, parser_node::next, NO_ERROR, parser_node::node_type, NULL, vid_oid::oid, db_object::oid_info, pt_table_option_info::option, pt_create_entity_info::or_replace, pt_name_info::original, pt_create_entity_info::partition_info, tp_domain::precision, prm_get_bool_value(), prm_get_integer_value(), PRM_ID_TB_DEFAULT_REUSE_OID, PRM_ID_TDE_DEFAULT_ALGORITHM, sm_partition_alter_info::promoted_count, sm_partition_alter_info::promoted_names, PT_CASCADED, pt_check_grammar_charset_collation(), PT_CLASS, pt_entity(), pt_get_select_query_columns(), pt_get_varchar_bytes(), pt_has_error, PT_LOCAL, pt_report_to_ersys(), PT_SEMANTIC, pt_semantic_check(), PT_TABLE_OPTION, PT_TABLE_OPTION_CHARSET, PT_TABLE_OPTION_COLLATION, PT_TABLE_OPTION_COMMENT, PT_TABLE_OPTION_DONT_REUSE_OID, PT_TABLE_OPTION_ENCRYPT, PT_TABLE_OPTION_REUSE_OID, PT_TYPE_INTEGER, PT_VALUE, PT_VCLASS, sm_partition_alter_info::root_op, sm_partition_alter_info::root_tmpl, SM_CLASSFLAG_LOCALCHECKOPTION, SM_CLASSFLAG_REUSE_OID, SM_CLASSFLAG_WITHCHECKOPTION, sm_is_partitioned_class(), sm_set_class_collation(), sm_set_class_comment(), sm_set_class_flag(), sm_set_class_tde_algorithm(), pt_data_value::str, pt_create_entity_info::supclass_list, pt_statement_info::table_option, pt_create_entity_info::table_option_list, sm_class::tde_algorithm, TDE_ALGORITHM_NONE, tran_abort_upto_system_savepoint(), tran_system_savepoint(), tp_domain::type, parser_node::type_enum, UNIQUE_SAVEPOINT_CREATE_ENTITY, UNIQUE_SAVEPOINT_REPLACE_VIEW, pt_table_option_info::val, pt_statement_info::value, pt_create_entity_info::vclass_comment, and pt_create_entity_info::with_check_option.
Referenced by do_execute_statement(), and do_statement().
int do_create_local (PARSER_CONTEXT * parser, DB_CTMPL * ctemplate, PT_NODE * pt_node, DB_QUERY_TYPE * create_select_columns)
Definition at line 8308 of file execute_schema.c.
References pt_create_entity_info::as_query_list, pt_create_entity_info::attr_def_list, sm_template::attributes, pt_create_entity_info::class_attr_def_list, pt_create_entity_info::constraint_list, pt_statement_info::create_entity, do_add_attributes(), do_add_constraints(), do_add_method_files(), do_add_methods(), do_add_queries(), do_add_resolutions(), do_add_supers(), do_check_fk_constraints(), do_set_object_id(), error(), sm_attribute::flags, sm_attribute::header, parser_node::info, pt_partition_info::keycol, pt_create_entity_info::method_def_list, pt_create_entity_info::method_file_list, sm_component::name, pt_statement_info::name, sm_component::next, NO_ERROR, NULL, pt_create_entity_info::object_id_list, pt_name_info::original, pt_statement_info::partition, pt_create_entity_info::partition_info, pt_create_entity_info::resolution_list, SM_ATTFLAG_PARTITION_KEY, SM_COMPARE_NAMES, and pt_create_entity_info::supclass_list.
Referenced by do_create_entity(), and do_create_partition().
int do_drop_partition_list (MOP class_, PT_NODE * name_list, DB_CTMPL * tmpl)
Definition at line 5172 of file execute_schema.c.
References adjust_partition_range(), adjust_partition_size(), ARG_FILE_LINE, assert, au_fetch_class(), AU_FETCH_READ, AU_SELECT, sm_class_header::ch_name, COPY_OID, DB_MAX_IDENTIFIER_LENGTH, er_errid(), ER_ERROR_SEVERITY, ER_FAILED, ER_INVALID_PARTITION_REQUEST, ER_OUT_OF_VIRTUAL_MEMORY, ER_PARTITION_NOT_EXIST, er_set(), error(), free_and_init, sm_class::header, i, parser_node::info, pt_statement_info::name, parser_node::next, NO_ERROR, NULL, vid_oid::oid, db_object::oid_info, pt_name_info::original, sm_class::partition, PARTITIONED_SUB_CLASS_TAG, sm_ch_name(), sm_delete_class_mop(), sm_find_class(), and sm_class::users.
Referenced by do_alter_partitioning_pre().
int do_drop_partitioned_class (MOP class_, int drop_sub_flag, bool is_cascade_constraints)
Definition at line 4488 of file execute_schema.c.
References ARG_FILE_LINE, au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_MODIFICATION_ERROR, ER_ERROR_SEVERITY, ER_FAILED, ER_NOT_ALLOWED_ACCESS_TO_PARTITION, er_set(), error(), db_objlist::next, NO_ERROR, NULL, db_objlist::op, sm_class::partition, sm_delete_class_mop(), and sm_class::users.
Referenced by sm_delete_class_mop().
int do_get_partition_keycol (char * keycol, MOP class_)
Definition at line 5113 of file execute_schema.c.
References ARG_FILE_LINE, au_fetch_class(), AU_FETCH_READ, AU_SELECT, db_get_string(), DB_IS_NULL, db_make_null(), DB_MAX_IDENTIFIER_LENGTH, ER_ERROR_SEVERITY, ER_INVALID_PARTITION_REQUEST, er_set(), error(), NO_ERROR, NULL, sm_class::partition, set_get_element_nocopy(), and sm_partition::values.
Referenced by build_attr_change_map(), do_alter_partitioning_post(), and do_alter_partitioning_pre().
int do_get_partition_parent (DB_OBJECT *const classop, MOP *const parentop)
Definition at line 4345 of file execute_schema.c.
References assert, assert_release, AU_DISABLE, AU_ENABLE, au_fetch_class(), AU_FETCH_READ, AU_SELECT, ER_FAILED, error(), sm_class::inheritance, db_objlist::next, NO_ERROR, NULL, db_objlist::op, sm_class::partition, and sm_class::users.
Referenced by do_reclaim_class_addresses(), emit_index_def(), and sm_partitioned_class_type().
int do_get_partition_size (MOP class_)
Definition at line 5065 of file execute_schema.c.
References ARG_FILE_LINE, au_fetch_class(), AU_FETCH_READ, AU_SELECT, db_value::data, db_make_null(), ER_ERROR_SEVERITY, ER_FAILED, ER_INVALID_PARTITION_REQUEST, er_set(), error(), db_data::i, NO_ERROR, NULL, sm_class::partition, set_get_element_nocopy(), and sm_partition::values.
Referenced by do_coalesce_partition_pre(), and do_create_partition().
int do_is_partitioned_subclass (int * is_partitioned, const char * classname, char * keyattr)
Definition at line 4415 of file execute_schema.c.
References au_fetch_class(), AU_FETCH_READ, AU_SELECT, db_find_class(), db_get_string(), DB_IS_NULL, DB_MAX_IDENTIFIER_LENGTH, NO_ERROR, NULL, sm_attr_properties_chg::p, sm_class::partition, sm_partition::pname, set_get_element_nocopy(), strlen, and sm_partition::values.
Referenced by db_create_by_name(), do_create_entity(), do_drop(), do_rename_internal(), do_truncate(), emit_index_def(), emit_schema(), emit_superclasses(), and pt_check_alter().
int do_recreate_filter_index_constr (PARSER_CONTEXT * parser, SM_PREDICATE_INFO * filter_index_info, PT_NODE * alter, const char * src_cls_name, const char * new_cls_name)
Definition at line 14536 of file execute_schema.c.
References pt_statement_info::alter, ARG_FILE_LINE, assert, sm_predicate_info::att_ids, pred_expr_with_context::attrids_pred, parser_varchar::bytes, parser_context::custom_print, pt_alter_info::entity_name, pt_spec_info::entity_name, er_errid(), ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), ER_SM_INVALID_FILTER_PREDICATE_LENGTH, error(), pt_statement_info::expr, free_and_init, pt_select_info::from, i, parser_node::info, MAX_FILTER_PREDICATE_STRING_LENGTH, MSGCAT_RUNTIME_RESOURCES_EXHAUSTED, MSGCAT_SET_ERROR, MSGCAT_SET_PARSER_RUNTIME, pt_statement_info::name, parser_node::next, NO_ERROR, parser_node::node_type, NULL, sm_predicate_info::num_attrs, pred_expr_with_context::num_attrs_pred, pt_name_info::original, pt_expr_info::paren_type, parser_create_parser(), parser_free_parser(), parser_free_tree(), parser_parse_string_use_sys_charset(), parser_walk_tree(), sm_predicate_info::pred_stream, sm_predicate_info::pred_stream_size, sm_predicate_info::pred_string, PT_ALTER, PT_CHARSET_COLLATE_FULL, pt_enter_packing_buf(), PT_ERRORm, PT_ERRORmf, pt_exit_packing_buf(), pt_has_error, pt_name(), pt_print_bytes(), pt_replace_names_index_expr(), pt_resolve_names(), pt_semantic_type(), pt_to_pred_with_context(), pt_query_info::q, pt_statement_info::query, replace_names_alter_chg_attr(), pt_query_info::select, pt_statement_info::spec, strlen, pt_select_info::where, and xts_map_filter_pred_to_stream().
Referenced by do_alter_clause_change_attribute(), do_copy_indexes(), do_recreate_renamed_class_indexes(), sm_add_secondary_index_on_partition(), and sm_exist_index().
int do_recreate_func_index_constr (PARSER_CONTEXT * parser, SM_CONSTRAINT_INFO * constr, SM_FUNCTION_INFO * func_index_info, PT_NODE * alter, const char * src_cls_name, const char * new_cls_name)
Definition at line 14335 of file execute_schema.c.
References pt_statement_info::alter, ARG_FILE_LINE, sm_function_info::attr_index_start, sm_function_info::col_id, db_ws_free(), DO_INDEX_CREATE, pt_alter_info::entity_name, pt_spec_info::entity_name, ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), sm_function_info::expr_str, free_and_init, pt_select_info::from, sm_constraint_info::func_index_info, parser_node::info, pt_select_info::list, pt_statement_info::name, parser_node::next, NO_ERROR, parser_node::node_type, NULL, pt_name_info::original, parser_create_parser(), parser_free_parser(), parser_free_tree(), parser_parse_string_use_sys_charset(), parser_walk_tree(), PT_ALTER, pt_enter_packing_buf(), pt_exit_packing_buf(), pt_has_error, pt_is_function_index_expr(), pt_name(), pt_node_to_function_index(), pt_replace_names_index_expr(), pt_resolve_names(), pt_semantic_type(), pt_query_info::q, pt_statement_info::query, replace_names_alter_chg_attr(), pt_query_info::select, sm_free_function_index_info(), pt_statement_info::spec, and strlen.
Referenced by do_alter_clause_change_attribute(), do_copy_indexes(), do_create_partition_constraint(), do_recreate_renamed_class_indexes(), sm_add_secondary_index_on_partition(), and sm_exist_index().
int do_rename_partition (MOP old_class, const char * newname)
Definition at line 4561 of file execute_schema.c.
References ARG_FILE_LINE, au_fetch_class(), AU_FETCH_READ, AU_SELECT, ER_ERROR_SEVERITY, ER_FAILED, ER_PARTITION_WORK_FAILED, er_set(), error(), db_objlist::next, NO_ERROR, NULL, db_objlist::op, sm_class::partition, PARTITION_VARCHAR_LEN, PARTITIONED_SUB_CLASS_TAG, sm_ch_name(), sm_rename_class(), strlen, and sm_class::users.
Referenced by sm_rename_class().
int do_set_object_id (const PARSER_CONTEXT * parser, DB_CTMPL * ctemplate, PT_NODE * object_id_list)
Definition at line 8266 of file execute_schema.c.
References db_namelist_append(), db_namelist_free(), dbt_set_object_id(), error(), parser_node::info, pt_statement_info::name, parser_node::next, NO_ERROR, NULL, and pt_name_info::original.
Referenced by do_create_local().