CUBRID Engine: src/base/fault_injection.c File Reference
fault_injection.c File Reference
#include "fault_injection.h"
#include "porting.h"
#include "system_parameter.h"
#include <assert.h>
Functions
static int fi_handler_exit (THREAD_ENTRY *thread_p, void *arg, const char *caller_file, const int caller_line)
static int fi_handler_random_exit (THREAD_ENTRY *thread_p, void *arg, const char *caller_file, const int caller_line)
static int fi_handler_random_fail (THREAD_ENTRY *thread_p, void *arg, const char *caller_file, const int caller_line)
static int fi_handler_hang (THREAD_ENTRY *thread_p, void *arg, const char *caller_file, const int caller_line)
static FI_TEST_ITEM * fi_code_item (THREAD_ENTRY *thread_p, FI_TEST_CODE code)
int fi_thread_init (THREAD_ENTRY *thread_p)
int fi_thread_final (THREAD_ENTRY *thread_p)
int fi_set (THREAD_ENTRY *thread_p, FI_TEST_CODE code, int state)
int fi_set_force (THREAD_ENTRY *thread_p, FI_TEST_CODE code, int state)
void fi_reset (THREAD_ENTRY *thread_p, FI_TEST_CODE code)
int fi_test (THREAD_ENTRY *thread_p, FI_TEST_CODE code, void *arg, int state, const char *caller_file, const int caller_line)
int fi_state (THREAD_ENTRY *thread_p, FI_TEST_CODE code)
bool fi_test_on (FI_TEST_CODE code)
Variables
FI_TEST_ITEM fi_Test_array []
FI_TEST_CODE fi_Group_none []
FI_TEST_CODE fi_Group_recovery []
FI_TEST_CODE * fi_Groups [FI_GROUP_MAX+1]
Function Documentation
static FI_TEST_ITEM * fi_code_item (THREAD_ENTRY * thread_p, FI_TEST_CODE code) static
Definition at line 178 of file fault_injection.c.
References assert, fi_Test_array, i, NULL, and thread_get_thread_entry_info().
Referenced by fi_reset(), fi_set(), fi_set_force(), fi_state(), and fi_test().
static int fi_handler_exit (THREAD_ENTRY * thread_p, void * arg, const char * caller_file, const int caller_line) static
Definition at line 375 of file fault_injection.c.
References NO_ERROR.
static int fi_handler_hang (THREAD_ENTRY * thread_p, void * arg, const char * caller_file, const int caller_line) static
Definition at line 390 of file fault_injection.c.
References NO_ERROR.
static int fi_handler_random_exit (THREAD_ENTRY * thread_p, void * arg, const char * caller_file, const int caller_line) static
Definition at line 401 of file fault_injection.c.
References _exit(), ARG_FILE_LINE, ER_FAILED_ASSERTION, ER_NOTIFICATION_SEVERITY, er_print_callstack(), er_set(), LOG_CS_ENTER(), LOG_CS_EXIT(), logpb_flush_pages_direct(), NO_ERROR, NULL, prm_get_bool_value(), and PRM_ID_FAULT_INJECTION_ACTION_PREFER_ABORT_TO_EXIT.
static int fi_handler_random_fail (THREAD_ENTRY * thread_p, void * arg, const char * caller_file, const int caller_line) static
Definition at line 452 of file fault_injection.c.
References ER_FAILED, ER_FAILED_ASSERTION, ER_NOTIFICATION_SEVERITY, er_set(), NO_ERROR, and NULL.
void fi_reset (THREAD_ENTRY * thread_p, FI_TEST_CODE code)
Definition at line 287 of file fault_injection.c.
References fi_code_item(), FI_INIT_STATE, NULL, and fi_test_item::state.
int fi_set (THREAD_ENTRY * thread_p, FI_TEST_CODE code, int state)
Definition at line 224 of file fault_injection.c.
References assert, ER_FAILED, fi_code_item(), NO_ERROR, NULL, PRM_ID_FAULT_INJECTION_IDS, fi_test_item::state, and sysprm_find_fi_code_in_integer_list().
int fi_set_force (THREAD_ENTRY * thread_p, FI_TEST_CODE code, int state)
Definition at line 258 of file fault_injection.c.
References assert, ER_FAILED, fi_code_item(), NO_ERROR, NULL, PRM_ID_FAULT_INJECTION_IDS, fi_test_item::state, and sysprm_find_fi_code_in_integer_list().
int fi_state (THREAD_ENTRY * thread_p, FI_TEST_CODE code)
Definition at line 338 of file fault_injection.c.
References assert, fi_code_item(), FI_INIT_STATE, NULL, PRM_ID_FAULT_INJECTION_IDS, fi_test_item::state, and sysprm_find_fi_code_in_integer_list().
int fi_test (THREAD_ENTRY * thread_p, FI_TEST_CODE code, void * arg, int state, const char * caller_file, const int caller_line)
Definition at line 305 of file fault_injection.c.
References assert, ER_FAILED, fi_code_item(), fi_test_item::func, NO_ERROR, NULL, PRM_ID_FAULT_INJECTION_IDS, fi_test_item::state, and sysprm_find_fi_code_in_integer_list().
bool fi_test_on (FI_TEST_CODE code)
Definition at line 361 of file fault_injection.c.
References PRM_ID_FAULT_INJECTION_IDS, and sysprm_find_fi_code_in_integer_list().
int fi_thread_final (THREAD_ENTRY * thread_p)
Definition at line 146 of file fault_injection.c.
References assert, ER_FAILED, free_and_init, NO_ERROR, NULL, and thread_get_thread_entry_info().
Referenced by cubthread::entry::clear_resources().
int fi_thread_init (THREAD_ENTRY * thread_p)
Definition at line 94 of file fault_injection.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), FI_INIT_STATE, fi_Test_array, i, NO_ERROR, NULL, fi_test_item::state, and thread_get_thread_entry_info().
Referenced by cubthread::entry::entry().
Variable Documentation
FI_TEST_CODE fi_Group_none[]
Initial value:
= {
  FI_TEST_NONE
}
Definition at line 69 of file fault_injection.c.
FI_TEST_CODE fi_Group_recovery[]
Initial value:
= {
  FI_TEST_LOG_MANAGER_RANDOM_EXIT_AT_RUN_POSTPONE,
  FI_TEST_LOG_MANAGER_RANDOM_EXIT_AT_END_SYSTEMOP,
  FI_TEST_BTREE_MANAGER_RANDOM_EXIT,
  FI_TEST_BTREE_MANAGER_PAGE_DEALLOC_FAIL,
  FI_TEST_NONE
}
Definition at line 73 of file fault_injection.c.
FI_TEST_CODE* fi_Groups[FI_GROUP_MAX+1]
Initial value:
= {
  fi_Group_none,
  fi_Group_recovery
}
Definition at line 81 of file fault_injection.c.
Referenced by sysprm_final().
FI_TEST_ITEM fi_Test_array[]
Initial value:
= {
  {FI_TEST_HANG, fi_handler_hang, FI_INIT_STATE},
  {FI_TEST_FILE_IO_FORMAT, fi_handler_random_exit, FI_INIT_STATE},
  {FI_TEST_DISK_MANAGER_VOLUME_ADD, fi_handler_random_exit, FI_INIT_STATE},
  {FI_TEST_DISK_MANAGER_VOLUME_EXPAND, fi_handler_random_exit, FI_INIT_STATE},
  {FI_TEST_FILE_IO_WRITE_PARTS1, fi_handler_random_exit, FI_INIT_STATE},
  {FI_TEST_FILE_IO_WRITE_PARTS2, fi_handler_random_exit, FI_INIT_STATE},
  {FI_TEST_FILE_MANAGER_UNDO_TRACKER_REGISTER, fi_handler_exit, FI_INIT_STATE},
  {FI_TEST_BTREE_MANAGER_RANDOM_EXIT, fi_handler_random_exit, FI_INIT_STATE},
  {FI_TEST_LOG_MANAGER_RANDOM_EXIT_AT_RUN_POSTPONE, fi_handler_random_exit, FI_INIT_STATE},
  {FI_TEST_LOG_MANAGER_RANDOM_EXIT_AT_END_SYSTEMOP, fi_handler_random_exit, FI_INIT_STATE},
  {FI_TEST_BTREE_MANAGER_PAGE_DEALLOC_FAIL, fi_handler_random_fail, FI_INIT_STATE}
}
Definition at line 55 of file fault_injection.c.
Referenced by fi_code_item(), and fi_thread_init().