CUBRID Engine: src/query/fetch.h File Reference
fetch.h File Reference
#include "storage_common.h"
#include "oid.h"
#include "query_evaluator.h"
#include "query_list.h"
Functions
int fetch_peek_dbval (THREAD_ENTRY *thread_p, regu_variable_node *regu_var, val_descr *vd, OID *class_oid, OID *obj_oid, QFILE_TUPLE tpl, DB_VALUE **peek_dbval)
int fetch_copy_dbval (THREAD_ENTRY *thread_p, regu_variable_node *regu_var, val_descr *vd, OID *class_oid, OID *obj_oid, QFILE_TUPLE tpl, DB_VALUE *dbval)
int fetch_val_list (THREAD_ENTRY *thread_p, regu_variable_list_node *regu_list, val_descr *vd, OID *class_oid, OID *obj_oid, QFILE_TUPLE tpl, int peek)
void fetch_init_val_list (regu_variable_list_node *regu_list)
void fetch_force_not_const_recursive (regu_variable_node &reguvar)
Function Documentation
int fetch_copy_dbval (THREAD_ENTRY * thread_p, regu_variable_node * regu_var, val_descr * vd, OID * class_oid, OID * obj_oid, QFILE_TUPLE tpl, DB_VALUE * dbval)
void fetch_force_not_const_recursive (regu_variable_node & reguvar)
void fetch_init_val_list (regu_variable_list_node * regu_list)
Definition at line 4605 of file fetch.c.
References regu_variable_list_node::next, NULL, and regu_variable_list_node::value.
Referenced by qexec_execute_obj_fetch().
int fetch_peek_dbval (THREAD_ENTRY * thread_p, regu_variable_node * regu_var, val_descr * vd, OID * class_oid, OID * obj_oid, QFILE_TUPLE tpl, DB_VALUE ** peek_dbval)
int fetch_val_list (THREAD_ENTRY * thread_p, regu_variable_list_node * regu_list, val_descr * vd, OID * class_oid, OID * obj_oid, QFILE_TUPLE tpl, int peek)
Definition at line 4526 of file fetch.c.
References DB_VALUE_DOMAIN_TYPE, ER_FAILED, fetch_copy_dbval(), fetch_peek_dbval(), fetch_peek_dbval_pos(), regu_variable_list_node::next, NO_ERROR, NULL, pr_clear_value(), pr_is_set_type(), QFILE_TUPLE_LENGTH_SIZE, rc, TYPE_POSITION, and regu_variable_list_node::value.
Referenced by btree_dump_curr_key(), eval_data_filter(), locator_mvcc_reeval_scan_filters(), qdata_evaluate_qprior(), qdata_evaluate_sys_connect_by_path(), qexec_analytic_add_tuple(), qexec_analytic_update_group_result(), qexec_execute_connect_by(), qexec_execute_obj_fetch(), qexec_gby_agg_tuple(), qexec_hash_gby_agg_tuple(), qexec_iterate_connect_by_results(), qexec_resolve_domains_for_aggregation(), scan_build_hash_list_scan(), scan_dump_key_into_tuple(), scan_jump_scan_pos(), scan_next_class_attr_scan(), scan_next_hash_list_scan(), scan_next_heap_page_scan(), scan_next_heap_scan(), scan_next_index_key_info_scan(), scan_next_index_lookup_heap(), scan_next_index_node_info_scan(), scan_next_index_scan(), scan_next_list_scan(), and scan_prev_scan_local().