CUBRID Engine: src/storage/file_io.c File Reference
file_io.c File Reference
#include "config.h"
#include <stdlib.h>
#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include <fcntl.h>
#include <errno.h>
#include <time.h>
#include <limits.h>
#include <sys/stat.h>
#include <assert.h>
#include <signal.h>
#include <unistd.h>
#include <sys/time.h>
#include <sys/param.h>
#include <sys/types.h>
#include <sys/uio.h>
#include <sys/vfs.h>
#include "porting.h"
#include "chartype.h"
#include "connection_globals.h"
#include "file_io.h"
#include "storage_common.h"
#include "memory_alloc.h"
#include "error_manager.h"
#include "system_parameter.h"
#include "message_catalog.h"
#include "msgcat_set_log.hpp"
#include "object_representation.h"
#include "util_func.h"
#include "perf_monitor.h"
#include "environment_variable.h"
#include "connection_error.h"
#include "release_string.h"
#include "log_common_impl.h"
#include "log_volids.hpp"
#include "fault_injection.h"
#include "crypt_opfunc.h"
#include "tcp.h"
#include "double_write_buffer.h"
#include "page_buffer.h"
#include "xserver_interface.h"
#include "intl_support.h"
#include "tsc_timer.h"
Classes
struct fileio_backup_file_header
struct fileio_bkvinf_entry
struct fileio_bkvinf_queues
struct fileio_sys_volinfo
struct fileio_sys_volinfo_header
struct fileio_volinfo
union fileio_apply_function_arg
struct fileio_volinfo_header
Macros
#define MSGCAT_FILEIO_STARTS 1
#define MSGCAT_FILEIO_BKUP_NEEDED 2
#define MSGCAT_FILEIO_BKUP_HDR 3
#define MSGCAT_FILEIO_BKUP_HDR_MAGICID 4
#define MSGCAT_FILEIO_BKUP_HDR_RELEASES 5
#define MSGCAT_FILEIO_BKUP_HDR_DBINFO 6
#define MSGCAT_FILEIO_BKUP_HDR_LEVEL 7
#define MSGCAT_FILEIO_BKUP_HDR_TIME 8
#define MSGCAT_FILEIO_BKUP_FILE 9
#define MSGCAT_FILEIO_REST_RELO_NEEDED 10
#define MSGCAT_FILEIO_REST_RELO_OPTIONS 11
#define MSGCAT_FILEIO_NEWLOCATION 12
#define MSGCAT_FILEIO_INPUT_RANGE_ERROR 13
#define MSGCAT_FILEIO_INCORRECT_BKVOLUME 14
#define MSGCAT_FILEIO_LEVEL_MISMATCH 15
#define MSGCAT_FILEIO_MAGIC_MISMATCH 16
#define MSGCAT_FILEIO_DB_MISMATCH 17
#define MSGCAT_FILEIO_UNIT_NUM_MISMATCH 18
#define MSGCAT_FILEIO_BACKUP_TIME_MISMATCH 19
#define MSGCAT_FILEIO_BACKUP_VINF_ERROR 20
#define MSGCAT_FILEIO_BACKUP_LABEL_INFO 21
#define MSGCAT_FILEIO_BKUP_HDR_LX_LSA 22
#define MSGCAT_FILEIO_RESTORE_FIND_REASON 23
#define MSGCAT_FILEIO_BKUP_FIND_REASON 24
#define MSGCAT_FILEIO_BKUP_PREV_BKVOL 25
#define MSGCAT_FILEIO_BKUP_NEXT_BKVOL 26
#define MSGCAT_FILEIO_BKUP_HDR_BKUP_PAGESIZE 27
#define MSGCAT_FILEIO_BKUP_HDR_ZIP_INFO 28
#define MSGCAT_FILEIO_BKUP_HDR_INC_ACTIVELOG 29
#define FILEIO_USER_NAME_SIZE 9
#define GETPID() getpid()
#define FILEIO_DISK_FORMAT_MODE (O_RDWR | O_CREAT)
#define FILEIO_DISK_PROTECTION_MODE 0600
#define FILEIO_MAX_WAIT_DBTXT 300
#define FILEIO_FULL_LEVEL_EXP 32
#define GET_NEXT_1K_SIZE(s) (((((s) - 1) / 1024) + 1) * 1024)
#define FILEIO_BACKUP_HEADER_IO_SIZE GET_NEXT_1K_SIZE(sizeof(FILEIO_BACKUP_HEADER))
#define FILEIO_GET_FILE_SIZE(pagesize, npages) (((off_t)(pagesize)) * ((off_t)(npages)))
#define FILEIO_BACKUP_NO_ZIP_HEADER_VERSION 1
#define FILEIO_BACKUP_CURRENT_HEADER_VERSION 2
#define FILEIO_CHECK_FOR_INTERRUPT_INTERVAL 100
#define FILEIO_PAGE_SIZE_FULL_LEVEL (IO_PAGESIZE * FILEIO_FULL_LEVEL_EXP)
#define FILEIO_BACKUP_PAGE_OVERHEAD (offsetof(FILEIO_BACKUP_PAGE, iopage) + sizeof(PAGEID))
#define FILEIO_BACKUP_DBVOLS_IO_PAGE_SIZE (IO_PAGESIZE + FILEIO_BACKUP_PAGE_OVERHEAD)
#define FILEIO_BACKUP_DBVOLS_IO_PAGE_SIZE_FULL_LEVEL (FILEIO_PAGE_SIZE_FULL_LEVEL + FILEIO_BACKUP_PAGE_OVERHEAD)
#define FILEIO_RESTORE_DBVOLS_IO_PAGE_SIZE(sess) ((sess)->bkup.bkuphdr->bkpagesize + FILEIO_BACKUP_PAGE_OVERHEAD)
#define FILEIO_DBVOLS_IO_PAGE_SIZE(backup_header_p) ((backup_header_p)->bkpagesize + FILEIO_BACKUP_PAGE_OVERHEAD)
#define FILEIO_BACKUP_FILE_HEADER_PAGE_SIZE (sizeof(FILEIO_BACKUP_FILE_HEADER) + offsetof(FILEIO_BACKUP_PAGE, iopage))
#define FILEIO_SET_BACKUP_PAGE_ID_COPY(area, pageid, psize)
#define FILEIO_SET_BACKUP_PAGE_ID(area, pageid, psize)
#define FILEIO_GET_BACKUP_PAGE_ID(area) (((FILEIO_BACKUP_PAGE *)(area))->iopageid)
#define FILEIO_CHECK_RESTORE_PAGE_ID(area, pagesz)
#define FILEIO_BACKUP_MINIMUM_NUM_PAGES
#define FILEIO_BACKUP_MINIMUM_NUM_PAGES_FULL_LEVEL
#define FILEIO_CHECK_AND_INITIALIZE_VOLUME_HEADER_CACHE(rtn)
#define FILEIO_BACKUP_START_PAGE_ID (-2)
#define FILEIO_BACKUP_END_PAGE_ID (-3)
#define FILEIO_BACKUP_FILE_START_PAGE_ID (-4)
#define FILEIO_BACKUP_FILE_END_PAGE_ID (-5)
#define FILEIO_BACKUP_VOL_CONT_PAGE_ID (-6)
#define FILEIO_END_OF_FILE (1)
#define FILEIO_MIN_FLUSH_PAGES_PER_SEC (41943040 / IO_PAGESIZE)
#define FILEIO_PAGE_FLUSH_GROW_RATE 0.5
#define FILEIO_PAGE_FLUSH_DROP_RATE 0.1
#define fileio_lock_file_read(fd, offset, whence, len) fileio_lock_region(fd, F_SETLK, F_RDLCK, offset, whence, len)
#define fileio_lock_file_readw(fd, offset, whence, len) fileio_lock_region(fd, F_SETLKW, F_RDLCK, offset, whence, len)
#define fileio_lock_file_write(fd, offset, whence, len) fileio_lock_region(fd, F_SETLK, F_WRLCK, offset, whence, len)
#define fileio_lock_file_writew(fd, offset, whence, len) fileio_lock_region(fd, F_SETLKW, F_WRLCK, offset, whence, len)
#define fileio_unlock_file(fd, offset, whence, len) fileio_lock_region(fd, F_SETLK, F_UNLCK, offset, whence, len)
#define FILEIO_VOLINFO_INCREMENT 32
#define pthread_mutex_init(a, b)
#define pthread_mutex_destroy(a)
#define pthread_mutex_lock(a) 0
#define pthread_mutex_unlock(a)
Typedefs
typedef struct fileio_backup_file_header FILEIO_BACKUP_FILE_HEADER
typedef struct fileio_bkvinf_entry FILEIO_BACKUP_INFO_ENTRY
typedef struct fileio_bkvinf_queues FILEIO_BACKUP_INFO_QUEUE
typedef struct fileio_sys_volinfo FILEIO_SYSTEM_VOLUME_INFO
typedef struct fileio_sys_volinfo_header FILEIO_SYSTEM_VOLUME_HEADER
typedef struct fileio_volinfo FILEIO_VOLUME_INFO
typedef struct fileio_volinfo_header FILEIO_VOLUME_HEADER
typedef union fileio_apply_function_arg APPLY_ARG
typedef bool(* VOLINFO_APPLY_FN) (THREAD_ENTRY *thread_p, FILEIO_VOLUME_INFO *vol_info_p, APPLY_ARG *arg)
typedef bool(* SYS_VOLINFO_APPLY_FN) (THREAD_ENTRY *thread_p, FILEIO_SYSTEM_VOLUME_INFO *sys_vol_info_p, APPLY_ARG *arg)
Enumerations
enum FILEIO_RELOCATION_VOLUME {
FILEIO_RELOCATION_FIRST = 0, FILEIO_RELOCATION_QUIT = FILEIO_RELOCATION_FIRST, FILEIO_RELOCATION_RETRY, FILEIO_RELOCATION_ALTERNATE,
FILEIO_RELOCATION_LAST = FILEIO_RELOCATION_ALTERNATE
}
Functions
static int fileio_initialize_volume_info_cache (void)
static void fileio_make_volume_lock_name (char *vol_lockname, const char *vol_fullname)
static int fileio_create (THREAD_ENTRY *thread_p, const char *db_fullname, const char *vlabel, VOLID volid, bool dolock, bool dosync)
static int fileio_create_backup_volume (THREAD_ENTRY *thread_p, const char *db_fullname, const char *vlabel, VOLID volid, bool dolock, bool dosync, int atleast_pages)
static int fileio_max_permanent_volumes (int index, int num_permanent_volums)
static int fileio_min_temporary_volumes (int index, int num_temp_volums, int num_volinfo_array)
static FILEIO_SYSTEM_VOLUME_INFO * fileio_traverse_system_volume (THREAD_ENTRY *thread_p, SYS_VOLINFO_APPLY_FN apply_function, APPLY_ARG *arg)
static FILEIO_VOLUME_INFO * fileio_traverse_permanent_volume (THREAD_ENTRY *thread_p, VOLINFO_APPLY_FN apply_function, APPLY_ARG *arg)
static FILEIO_VOLUME_INFO * fileio_reverse_traverse_permanent_volume (THREAD_ENTRY *thread_p, VOLINFO_APPLY_FN apply_function, APPLY_ARG *arg)
static FILEIO_VOLUME_INFO * fileio_traverse_temporary_volume (THREAD_ENTRY *thread_p, VOLINFO_APPLY_FN apply_function, APPLY_ARG *arg)
static FILEIO_VOLUME_INFO * fileio_reverse_traverse_temporary_volume (THREAD_ENTRY *thread_p, VOLINFO_APPLY_FN apply_function, APPLY_ARG *arg)
static bool fileio_dismount_volume (THREAD_ENTRY *thread_p, FILEIO_VOLUME_INFO *vol_info_p, APPLY_ARG *ignore_arg)
static bool fileio_is_volume_descriptor_equal (THREAD_ENTRY *thread_p, FILEIO_VOLUME_INFO *vol_info_p, APPLY_ARG *arg)
static bool fileio_is_volume_id_gt (THREAD_ENTRY *thread_p, FILEIO_VOLUME_INFO *vol_info_p, APPLY_ARG *arg)
static bool fileio_is_volume_id_lt (THREAD_ENTRY *thread_p, FILEIO_VOLUME_INFO *vol_info_p, APPLY_ARG *arg)
static FILEIO_SYSTEM_VOLUME_INFO * fileio_find_system_volume (THREAD_ENTRY *thread_p, SYS_VOLINFO_APPLY_FN apply_function, APPLY_ARG *arg)
static bool fileio_is_system_volume_descriptor_equal (THREAD_ENTRY *thread_p, FILEIO_SYSTEM_VOLUME_INFO *sys_vol_info_p, APPLY_ARG *arg)
static bool fileio_is_system_volume_id_equal (THREAD_ENTRY *thread_p, FILEIO_SYSTEM_VOLUME_INFO *sys_vol_info_p, APPLY_ARG *arg)
static bool fileio_is_system_volume_label_equal (THREAD_ENTRY *thread_p, FILEIO_SYSTEM_VOLUME_INFO *sys_vol_info_p, APPLY_ARG *arg)
static bool fileio_synchronize_sys_volume (THREAD_ENTRY *thread_p, FILEIO_SYSTEM_VOLUME_INFO *vol_sys_info_p, APPLY_ARG *arg)
static bool fileio_synchronize_volume (THREAD_ENTRY *thread_p, FILEIO_VOLUME_INFO *vol_info_p, APPLY_ARG *arg)
static int fileio_cache (VOLID volid, const char *vlabel, int vdes, FILEIO_LOCKF_TYPE lockf_type)
static void fileio_decache (THREAD_ENTRY *thread_p, int vdes)
static VOLID fileio_get_volume_id (int vdes)
static bool fileio_is_volume_label_equal (THREAD_ENTRY *thread_p, FILEIO_VOLUME_INFO *vol_info_p, APPLY_ARG *arg)
static int fileio_expand_permanent_volume_info (FILEIO_VOLUME_HEADER *header, int volid)
static int fileio_expand_temporary_volume_info (FILEIO_VOLUME_HEADER *header, int volid)
static bool fileio_is_terminated_process (int pid)
static ssize_t fileio_os_read (THREAD_ENTRY *thread_p, int vol_fd, void *io_page_p, size_t count, off_t offset)
static ssize_t fileio_os_write (THREAD_ENTRY *thread_p, int vol_fd, void *io_page_p, size_t count, off_t offset)
static ssize_t pwrite_with_injected_fault (THREAD_ENTRY *thread_p, int fd, const void *buf, size_t count, off_t offset)
static FILEIO_LOCKF_TYPE fileio_lock (const char *db_fullname, const char *vlabel, int vdes, bool dowait)
static void fileio_unlock (const char *vlabel, int vdes, FILEIO_LOCKF_TYPE lockf_type)
static FILEIO_LOCKF_TYPE fileio_get_lockf_type (int vdes)
static int fileio_get_primitive_way_max (const char *path, long int *filename_max, long int *pathname_max)
static int fileio_flush_backup (THREAD_ENTRY *thread_p, FILEIO_BACKUP_SESSION *session)
static ssize_t fileio_read_backup (THREAD_ENTRY *thread_p, FILEIO_BACKUP_SESSION *session, int pageid)
static int fileio_write_backup (THREAD_ENTRY *thread_p, FILEIO_BACKUP_SESSION *session, ssize_t towrite_nbytes)
static int fileio_write_backup_header (FILEIO_BACKUP_SESSION *session)
static FILEIO_BACKUP_SESSION * fileio_initialize_restore (THREAD_ENTRY *thread_p, const char *db_fullname, char *backup_src, FILEIO_BACKUP_SESSION *session, FILEIO_BACKUP_LEVEL level, const char *restore_verbose_file_path, bool newvolpath)
static int fileio_read_restore (THREAD_ENTRY *thread_p, FILEIO_BACKUP_SESSION *session, int toread_nbytes)
static void * fileio_write_restore (THREAD_ENTRY *thread_p, FILEIO_RESTORE_PAGE_BITMAP *page_bitmap, int vdes, void *io_pgptr, VOLID vol_id, PAGEID page_id, FILEIO_BACKUP_LEVEL level)
static int fileio_read_restore_header (FILEIO_BACKUP_SESSION *session)
static FILEIO_RELOCATION_VOLUME fileio_find_restore_volume (THREAD_ENTRY *thread_p, const char *dbname, char *to_volname, int unit_num, FILEIO_BACKUP_LEVEL level, int reason)
static int fileio_get_next_backup_volume (THREAD_ENTRY *thread_p, FILEIO_BACKUP_SESSION *session, bool user_new)
static int fileio_initialize_backup_info (int which_bkvinf)
static FILEIO_BACKUP_INFO_ENTRY * fileio_allocate_backup_info (int which_bkvinf)
static FILEIO_BACKUP_SESSION * fileio_continue_restore (THREAD_ENTRY *thread_p, const char *db_fullname, INT64 db_creation, FILEIO_BACKUP_SESSION *session, bool first_time, bool authenticate, INT64 match_bkupcreation)
static int fileio_fill_hole_during_restore (THREAD_ENTRY *thread_p, int *next_pageid, int stop_pageid, FILEIO_BACKUP_SESSION *session, FILEIO_RESTORE_PAGE_BITMAP *page_bitmap)
static int fileio_decompress_restore_volume (THREAD_ENTRY *thread_p, FILEIO_BACKUP_SESSION *session, int nbytes)
static FILEIO_NODE * fileio_allocate_node (FILEIO_QUEUE *qp, FILEIO_BACKUP_HEADER *backup_hdr)
static FILEIO_NODE * fileio_free_node (FILEIO_QUEUE *qp, FILEIO_NODE *node)
static FILEIO_NODE * fileio_delete_queue_head (FILEIO_QUEUE *qp)
static int fileio_compress_backup_node (FILEIO_NODE *node, FILEIO_BACKUP_HEADER *backup_hdr)
static int fileio_write_backup_node (THREAD_ENTRY *thread_p, FILEIO_BACKUP_SESSION *session, FILEIO_NODE *node, FILEIO_BACKUP_HEADER *backup_hdr)
static char * fileio_ctime (INT64 *clock, char *buf)
static const char * fileio_get_backup_level_string (FILEIO_BACKUP_LEVEL level)
static int fileio_initialize_backup_thread (FILEIO_BACKUP_SESSION *session_p, int num_threads)
static void fileio_finalize_backup_thread (FILEIO_BACKUP_SESSION *session_p, FILEIO_ZIP_METHOD zip_method)
static int fileio_write_backup_end_time_to_header (FILEIO_BACKUP_SESSION *session_p, INT64 end_time)
static void fileio_write_backup_end_time_to_last_page (FILEIO_BACKUP_SESSION *session_p, INT64 end_time)
static void fileio_read_backup_end_time_from_last_page (FILEIO_BACKUP_SESSION *session_p)
static int fileio_get_lock (int fd, const char *vlabel)
static int fileio_release_lock (int fd)
static int fileio_lock_region (int fd, int cmd, int type, off_t offset, int whence, off_t len)
static void fileio_compensate_flush (THREAD_ENTRY *thread_p, int fd, int npage)
static int fileio_increase_flushed_page_count (int npages)
static int fileio_flush_control_get_token (THREAD_ENTRY *thread_p, int ntoken)
static int fileio_flush_control_get_desired_rate (TOKEN_BUCKET *tb)
static int fileio_synchronize_bg_archive_volume (THREAD_ENTRY *thread_p)
static void fileio_page_bitmap_set (FILEIO_RESTORE_PAGE_BITMAP *page_bitmap, int page_id)
static bool fileio_page_bitmap_is_set (FILEIO_RESTORE_PAGE_BITMAP *page_bitmap, int page_id)
static void fileio_page_bitmap_dump (FILE *out_fp, const FILEIO_RESTORE_PAGE_BITMAP *page_bitmap)
int fileio_flush_control_initialize (void)
void fileio_flush_control_finalize (void)
int fileio_flush_control_add_tokens (THREAD_ENTRY *thread_p, INT64 diff_usec, int *token_gen, int *token_consumed)
static int fileio_allocate_and_initialize_volume_info (FILEIO_VOLUME_HEADER *header_p, int idx)
FILEIO_LOCKF_TYPE fileio_lock_la_log_path (const char *db_full_name_p, const char *lock_path_p, int vol_fd, int *last_deleted_arv_num)
FILEIO_LOCKF_TYPE fileio_lock_la_dbname (int *lockf_vdes, char *db_name, char *log_path)
FILEIO_LOCKF_TYPE fileio_unlock_la_dbname (int *lockf_vdes, char *db_name, bool clear_owner)
static void fileio_check_lockby_file (char *name_info_lock_p)
void * fileio_initialize_pages (THREAD_ENTRY *thread_p, int vol_fd, FILEIO_PAGE *io_page_p, DKNPAGES start_pageid, DKNPAGES npages, size_t page_size, int kbytes_to_be_written_per_sec)
int fileio_open (const char *vol_label_p, int flags, int mode)
int fileio_set_permission (const char *vol_label_p)
void fileio_close (int vol_fd)
int fileio_format (THREAD_ENTRY *thread_p, const char *db_full_name_p, const char *vol_label_p, VOLID vol_id, DKNPAGES npages, bool is_sweep_clean, bool is_do_lock, bool is_do_sync, size_t page_size, int kbytes_to_be_written_per_sec, bool reuse_file)
int fileio_expand_to (THREAD_ENTRY *thread_p, VOLID vol_id, DKNPAGES size_npages, DB_VOLTYPE voltype)
void fileio_unformat (THREAD_ENTRY *thread_p, const char *vol_label_p)
void fileio_unformat_and_rename (THREAD_ENTRY *thread_p, const char *vol_label_p, const char *new_label_p)
int fileio_copy_volume (THREAD_ENTRY *thread_p, int from_vol_desc, DKNPAGES npages, const char *to_vol_label_p, VOLID to_vol_id, bool is_reset_recovery_info)
int fileio_reset_volume (THREAD_ENTRY *thread_p, int vol_fd, const char *vlabel, DKNPAGES npages, const LOG_LSA *reset_lsa_p)
int fileio_mount (THREAD_ENTRY *thread_p, const char *db_full_name_p, const char *vol_label_p, VOLID vol_id, int lock_wait, bool is_do_sync)
void fileio_dismount (THREAD_ENTRY *thread_p, int vol_fd)
void fileio_dismount_without_fsync (THREAD_ENTRY *thread_p, int vol_fd)
void fileio_dismount_all (THREAD_ENTRY *thread_p)
bool fileio_map_mounted (THREAD_ENTRY *thread_p, bool(*fun)(THREAD_ENTRY *thread_p, VOLID vol_id, void *args), void *args)
static bool fileio_is_volume_id_equal (THREAD_ENTRY *thread_p, FILEIO_VOLUME_INFO *vol_info_p, APPLY_ARG *arg)
void fileio_page_hexa_dump (const char *src_data, int length)
void * fileio_read (THREAD_ENTRY *thread_p, int vol_fd, void *io_page_p, PAGEID page_id, size_t page_size)
void * fileio_write_or_add_to_dwb (THREAD_ENTRY *thread_p, int vol_fd, FILEIO_PAGE *io_page_p, PAGEID page_id, size_t page_size)
void * fileio_write (THREAD_ENTRY *thread_p, int vol_fd, void *io_page_p, PAGEID page_id, size_t page_size, FILEIO_WRITE_MODE write_mode)
void * fileio_read_pages (THREAD_ENTRY *thread_p, int vol_fd, char *io_pages_p, PAGEID page_id, int num_pages, size_t page_size)
void * fileio_write_pages (THREAD_ENTRY *thread_p, int vol_fd, char *io_pages_p, PAGEID page_id, int num_pages, size_t page_size, FILEIO_WRITE_MODE write_mode)
void * fileio_writev (THREAD_ENTRY *thread_p, int vol_fd, void **io_page_array, PAGEID start_page_id, DKNPAGES npages, size_t page_size)
int fileio_synchronize (THREAD_ENTRY *thread_p, int vol_fd, const char *vlabel, FILEIO_SYNC_OPTION sync_dwb)
int fileio_synchronize_all (THREAD_ENTRY *thread_p, bool is_include)
DKNPAGES fileio_get_number_of_volume_pages (int vol_fd, size_t page_size)
int fileio_get_number_of_partition_free_pages (const char *path_p, size_t page_size)
DKNSECTS fileio_get_number_of_partition_free_sectors (const char *path_p)
const char * fileio_rename (VOLID vol_id, const char *old_label_p, const char *new_label_p)
bool fileio_is_volume_exist (const char *vol_label_p)
bool fileio_is_volume_exist_and_file (const char *vol_label_p)
static char * fileio_check_file_exist (char *name_p, char *new_guess_path_p, int check_size, int *max_name_size_p)
static char * fileio_check_file_is_same (char *name_p, char *new_guess_path_p, int check_size, int *max_name_size_p, struct stat *buf)
int fileio_get_max_name (const char *given_path_p, long int *file_name_max_p, long int *path_name_max_p)
const char * fileio_get_base_file_name (const char *full_name_p)
char * fileio_get_directory_path (char *path_p, const char *full_name_p)
int fileio_get_volume_max_suffix (void)
void fileio_make_volume_info_name (char *vol_info_name_p, const char *db_full_name_p)
void fileio_make_volume_ext_name (char *vol_ext_full_name_p, const char *ext_path_p, const char *ext_name_p, VOLID vol_id)
void fileio_make_volume_ext_given_name (char *vol_ext_full_name_p, const char *ext_path_p, const char *ext_name_p)
void fileio_make_volume_temp_name (char *vol_tmp_full_name_p, const char *tmp_path_p, const char *tmp_name_p, VOLID vol_id)
void fileio_make_log_active_name (char *log_active_name_p, const char *log_path_p, const char *db_name_p)
void fileio_make_temp_log_files_from_backup (char *temp_log_name, VOLID to_volid, FILEIO_BACKUP_LEVEL level, const char *base_log_name)
void fileio_make_log_archive_name (char *log_archive_name_p, const char *log_path_p, const char *db_name_p, int archive_number)
void fileio_make_removed_log_archive_name (char *log_archive_name_p, const char *log_path_p, const char *db_name_p)
void fileio_make_log_archive_temp_name (char *log_archive_temp_name_p, const char *log_path_p, const char *db_name_p)
void fileio_make_log_info_name (char *log_info_name_p, const char *log_path_p, const char *db_name_p)
void fileio_make_backup_volume_info_name (char *backup_volinfo_name_p, const char *backup_info_path_p, const char *db_name_p)
void fileio_make_backup_name (char *backup_name_p, const char *no_path_vol_name_p, const char *backup_path_p, FILEIO_BACKUP_LEVEL level, int unit_num)
void fileio_make_dwb_name (char *dwb_name_p, const char *dwb_path_p, const char *db_name_p)
void fileio_make_keys_name (char *keys_name_p, const char *db_full_name_p)
void fileio_make_keys_name_given_path (char *keys_name_p, const char *keys_path_p, const char *db_name_p)
char * fileio_get_volume_label (VOLID vol_id, bool is_peek)
char * fileio_get_volume_label_by_fd (int vol_fd, bool is_peek)
VOLID fileio_find_volume_id_with_label (THREAD_ENTRY *thread_p, const char *vol_label_p)
bool fileio_is_temp_volume (THREAD_ENTRY *thread_p, VOLID volid)
bool fileio_is_permanent_volume_descriptor (THREAD_ENTRY *thread_p, int vol_fd)
VOLID fileio_find_next_perm_volume (THREAD_ENTRY *thread_p, VOLID volid)
VOLID fileio_find_previous_perm_volume (THREAD_ENTRY *thread_p, VOLID volid)
VOLID fileio_find_previous_temp_volume (THREAD_ENTRY *thread_p, VOLID volid)
int fileio_get_volume_descriptor (VOLID vol_id)
int fileio_find_volume_descriptor_with_label (const char *vol_label_p)
FILEIO_BACKUP_SESSION * fileio_initialize_backup (const char *db_full_name_p, const char *backup_destination_p, FILEIO_BACKUP_SESSION *session_p, FILEIO_BACKUP_LEVEL level, const char *verbose_file_path, int num_threads, int sleep_msecs)
void fileio_abort_backup (THREAD_ENTRY *thread_p, FILEIO_BACKUP_SESSION *session_p, bool does_unformat_bk)
FILEIO_BACKUP_SESSION * fileio_start_backup (THREAD_ENTRY *thread_p, const char *db_full_name_p, INT64 *db_creation_time_p, FILEIO_BACKUP_LEVEL backup_level, LOG_LSA *backup_start_lsa_p, LOG_LSA *backup_checkpoint_lsa_p, FILEIO_BACKUP_RECORD_INFO *all_levels_info_p, FILEIO_BACKUP_SESSION *session_p, FILEIO_ZIP_METHOD zip_method, FILEIO_ZIP_LEVEL zip_level)
FILEIO_BACKUP_SESSION * fileio_finish_backup (THREAD_ENTRY *thread_p, FILEIO_BACKUP_SESSION *session_p)
void fileio_remove_all_backup (THREAD_ENTRY *thread_p, int start_level)
int fileio_backup_volume (THREAD_ENTRY *thread_p, FILEIO_BACKUP_SESSION *session_p, const char *from_vol_label_p, VOLID from_vol_id, PAGEID last_page, bool is_only_updated_pages)
void fileio_abort_restore (THREAD_ENTRY *thread_p, FILEIO_BACKUP_SESSION *session_p)
FILEIO_BACKUP_SESSION * fileio_start_restore (THREAD_ENTRY *thread_p, const char *db_full_name_p, char *backup_source_p, INT64 match_db_creation_time, PGLENGTH *db_io_page_size_p, float *db_compatibility_p, FILEIO_BACKUP_SESSION *session_p, FILEIO_BACKUP_LEVEL level, bool is_authenticate, INT64 match_backup_creation_time, const char *restore_verbose_file_path, bool is_new_vol_path)
static int fileio_make_error_message (THREAD_ENTRY *thread_p, char *error_message_p)
int fileio_finish_restore (THREAD_ENTRY *thread_p, FILEIO_BACKUP_SESSION *session_p)
int fileio_list_restore (THREAD_ENTRY *thread_p, const char *db_full_name_p, char *backup_source_p, FILEIO_BACKUP_LEVEL level, bool is_new_vol_path)
int fileio_get_backup_volume (THREAD_ENTRY *thread_p, const char *db_fullname, const char *logpath, const char *user_backuppath, int try_level, char *from_volbackup)
int fileio_get_next_restore_file (THREAD_ENTRY *thread_p, FILEIO_BACKUP_SESSION *session_p, char *file_name_p, VOLID *vol_id_p)
int fileio_restore_volume (THREAD_ENTRY *thread_p, FILEIO_BACKUP_SESSION *session_p, char *to_vol_label_p, char *verbose_to_vol_label_p, char *prev_vol_label_p, FILEIO_RESTORE_PAGE_BITMAP *page_bitmap, bool is_remember_pages)
int fileio_skip_restore_volume (THREAD_ENTRY *thread_p, FILEIO_BACKUP_SESSION *session_p)
const char * fileio_get_zip_method_string (FILEIO_ZIP_METHOD zip_method)
const char * fileio_get_zip_level_string (FILEIO_ZIP_LEVEL zip_level)
int fileio_add_volume_to_backup_info (const char *name_p, FILEIO_BACKUP_LEVEL level, int unit_num, int which_bkvinf)
int fileio_write_backup_info_entries (FILE *fp, int which_bkvinf)
int fileio_read_backup_info_entries (FILE *fp, int which_bkvinf)
const char * fileio_get_backup_info_volume_name (FILEIO_BACKUP_LEVEL level, int unit_num, int which_bkvinf)
void fileio_finalize_backup_info (int which_bkvinf)
int fileio_clear_backup_info_level (int level, bool is_dealloc, int which_bkvinf)
int fileio_request_user_response (THREAD_ENTRY *thread_p, FILEIO_REMOTE_PROMPT_TYPE prompt_id, const char *prompt_p, char *response_p, const char *failure_prompt_p, int range_low, int range_high, const char *secondary_prompt_p, int reprompt_value)
int fileio_symlink (const char *src_p, const char *dest_p, int overwrite)
void fileio_initialize_res (THREAD_ENTRY *thread_p, FILEIO_PAGE *io_page, PGLENGTH page_size)
void fileio_page_bitmap_list_init (FILEIO_RESTORE_PAGE_BITMAP_LIST *page_bitmap_list)
FILEIO_RESTORE_PAGE_BITMAP * fileio_page_bitmap_create (int vol_id, int total_pages)
FILEIO_RESTORE_PAGE_BITMAP * fileio_page_bitmap_list_find (FILEIO_RESTORE_PAGE_BITMAP_LIST *page_bitmap_list, int vol_id)
void fileio_page_bitmap_list_add (FILEIO_RESTORE_PAGE_BITMAP_LIST *page_bitmap_list, FILEIO_RESTORE_PAGE_BITMAP *page_bitmap)
void fileio_page_bitmap_list_destroy (FILEIO_RESTORE_PAGE_BITMAP_LIST *page_bitmap_list)
int fileio_page_check_corruption (THREAD_ENTRY *thread_p, FILEIO_PAGE *io_page, bool *is_page_corrupted)
bool fileio_is_formatted_page (THREAD_ENTRY *thread_p, const char *io_page)
Variables
static int rv
static FILEIO_SYSTEM_VOLUME_HEADER fileio_Sys_vol_info_header
static FILEIO_VOLUME_HEADER fileio_Vol_info_header
static FILEIO_BACKUP_INFO_QUEUE fileio_Backup_vol_info_data [2]
static pthread_mutex_t fileio_Flushed_page_counter_mutex = PTHREAD_MUTEX_INITIALIZER
static int fileio_Flushed_page_count = 0
static TOKEN_BUCKET fc_Token_bucket_s
static TOKEN_BUCKET * fc_Token_bucket = NULL
static FLUSH_STATS fc_Stats
Macro Definition Documentation
#define FILEIO_BACKUP_CURRENT_HEADER_VERSION 2
Definition at line 189 of file file_io.c.
Referenced by fileio_initialize_backup().
#define FILEIO_BACKUP_DBVOLS_IO_PAGE_SIZE (IO_PAGESIZE + FILEIO_BACKUP_PAGE_OVERHEAD)
Definition at line 195 of file file_io.c.
#define FILEIO_BACKUP_DBVOLS_IO_PAGE_SIZE_FULL_LEVEL (FILEIO_PAGE_SIZE_FULL_LEVEL + FILEIO_BACKUP_PAGE_OVERHEAD)
Definition at line 197 of file file_io.c.
#define FILEIO_BACKUP_END_PAGE_ID (-3)
Definition at line 253 of file file_io.c.
Referenced by fileio_finish_backup(), fileio_get_next_restore_file(), fileio_list_restore(), and fileio_read_restore().
#define FILEIO_BACKUP_FILE_END_PAGE_ID (-5)
Definition at line 255 of file file_io.c.
Referenced by fileio_backup_volume(), fileio_restore_volume(), and fileio_skip_restore_volume().
#define FILEIO_BACKUP_FILE_HEADER_PAGE_SIZE (sizeof(FILEIO_BACKUP_FILE_HEADER) + offsetof(FILEIO_BACKUP_PAGE, iopage))
Definition at line 206 of file file_io.c.
Referenced by fileio_backup_volume(), fileio_continue_restore(), fileio_get_lockf_type(), fileio_get_next_restore_file(), fileio_initialize_backup(), and fileio_list_restore().
#define FILEIO_BACKUP_FILE_START_PAGE_ID (-4)
Definition at line 254 of file file_io.c.
Referenced by fileio_backup_volume(), fileio_get_next_restore_file(), and fileio_list_restore().
#define FILEIO_BACKUP_HEADER_IO_SIZE GET_NEXT_1K_SIZE(sizeof(FILEIO_BACKUP_HEADER))
Definition at line 184 of file file_io.c.
Referenced by fileio_get_lockf_type(), fileio_initialize_backup(), fileio_read_restore_header(), and fileio_write_backup_header().
#define FILEIO_BACKUP_MINIMUM_NUM_PAGES
Value:
CEIL_PTVDIV((FILEIO_BACKUP_HEADER_IO_SIZE +   \
              (FILEIO_BACKUP_DBVOLS_IO_PAGE_SIZE) * 4), IO_PAGESIZE)
Definition at line 237 of file file_io.c.
Referenced by fileio_get_next_backup_volume(), and fileio_start_backup().
#define FILEIO_BACKUP_MINIMUM_NUM_PAGES_FULL_LEVEL
Value:
CEIL_PTVDIV((FILEIO_BACKUP_HEADER_IO_SIZE +   \
              (FILEIO_BACKUP_DBVOLS_IO_PAGE_SIZE_FULL_LEVEL) * 4), IO_PAGESIZE)
Definition at line 240 of file file_io.c.
Referenced by fileio_get_next_backup_volume(), and fileio_start_backup().
#define FILEIO_BACKUP_NO_ZIP_HEADER_VERSION 1
Definition at line 188 of file file_io.c.
Referenced by fileio_read_restore_header().
#define FILEIO_BACKUP_PAGE_OVERHEAD (offsetof(FILEIO_BACKUP_PAGE, iopage) + sizeof(PAGEID))
Definition at line 193 of file file_io.c.
Referenced by fileio_backup_volume(), fileio_continue_restore(), fileio_initialize_backup(), and fileio_write_backup_node().
#define FILEIO_BACKUP_START_PAGE_ID (-2)
Definition at line 252 of file file_io.c.
Referenced by fileio_continue_restore(), fileio_list_restore(), and fileio_start_backup().
#define FILEIO_BACKUP_VOL_CONT_PAGE_ID (-6)
Definition at line 256 of file file_io.c.
Referenced by fileio_continue_restore(), fileio_get_next_backup_volume(), and fileio_list_restore().
#define FILEIO_CHECK_AND_INITIALIZE_VOLUME_HEADER_CACHE (rtn)
Value:
do { \
    if (fileio_Vol_info_header.volinfo == NULL \
        && fileio_initialize_volume_info_cache () < 0) \
      return (rtn); \
  } while (0)
Definition at line 244 of file file_io.c.
Referenced by fileio_cache(), fileio_find_next_perm_volume(), fileio_find_previous_perm_volume(), fileio_find_previous_temp_volume(), fileio_find_volume_descriptor_with_label(), fileio_find_volume_id_with_label(), fileio_get_lockf_type(), fileio_get_volume_descriptor(), fileio_get_volume_id(), fileio_get_volume_label(), fileio_is_permanent_volume_descriptor(), fileio_is_temp_volume(), fileio_map_mounted(), fileio_mount(), fileio_write_or_add_to_dwb(), and pwrite_with_injected_fault().
#define FILEIO_CHECK_FOR_INTERRUPT_INTERVAL 100
Definition at line 190 of file file_io.c.
Referenced by fileio_backup_volume(), fileio_initialize_pages(), and fileio_write_backup_node().
#define FILEIO_CHECK_RESTORE_PAGE_ID (area, pagesz)
Value:
(((FILEIO_BACKUP_PAGE *)(area))->iopageid == \
    *(PAGEID *)(((char *)(area)) + offsetof(FILEIO_BACKUP_PAGE, iopage) + pagesz))
Definition at line 231 of file file_io.c.
Referenced by fileio_restore_volume(), and fileio_skip_restore_volume().
#define FILEIO_DBVOLS_IO_PAGE_SIZE (backup_header_p) ((backup_header_p)->bkpagesize + FILEIO_BACKUP_PAGE_OVERHEAD)
Definition at line 203 of file file_io.c.
Referenced by fileio_allocate_node(), fileio_backup_volume(), and fileio_start_backup().
#define FILEIO_DISK_FORMAT_MODE (O_RDWR | O_CREAT)
Definition at line 173 of file file_io.c.
Referenced by fileio_check_file_exist(), fileio_create(), fileio_get_number_of_partition_free_pages(), fileio_get_number_of_partition_free_sectors(), fileio_get_primitive_way_max(), and fileio_initialize_backup().
#define FILEIO_DISK_PROTECTION_MODE 0600
Definition at line 174 of file file_io.c.
Referenced by fileio_check_file_exist(), fileio_create(), fileio_get_number_of_partition_free_pages(), fileio_get_number_of_partition_free_sectors(), fileio_get_primitive_way_max(), and fileio_initialize_backup().
#define FILEIO_END_OF_FILE (1)
Definition at line 258 of file file_io.c.
#define FILEIO_FULL_LEVEL_EXP 32
Definition at line 176 of file file_io.c.
Referenced by fileio_continue_restore(), fileio_initialize_backup(), and fileio_start_backup().
#define FILEIO_GET_BACKUP_PAGE_ID (area) (((FILEIO_BACKUP_PAGE *)(area))->iopageid)
Definition at line 223 of file file_io.c.
Referenced by fileio_get_next_restore_file(), fileio_list_restore(), fileio_read_backup(), fileio_read_restore(), fileio_restore_volume(), and fileio_skip_restore_volume().
#define FILEIO_GET_FILE_SIZE (pagesize, npages) (((off_t)(pagesize)) * ((off_t)(npages)))
Definition at line 185 of file file_io.c.
Referenced by fileio_expand_to(), fileio_format(), fileio_read(), fileio_read_backup(), fileio_read_pages(), fileio_synchronize_all(), fileio_write(), and fileio_write_pages().
#define fileio_lock_file_read (fd, offset, whence, len) fileio_lock_region(fd, F_SETLK, F_RDLCK, offset, whence, len)
Definition at line 290 of file file_io.c.
Referenced by fileio_get_lock().
#define fileio_lock_file_readw (fd, offset, whence, len) fileio_lock_region(fd, F_SETLKW, F_RDLCK, offset, whence, len)
Definition at line 292 of file file_io.c.
#define fileio_lock_file_write (fd, offset, whence, len) fileio_lock_region(fd, F_SETLK, F_WRLCK, offset, whence, len)
Definition at line 294 of file file_io.c.
Referenced by fileio_lock(), fileio_lock_la_dbname(), and fileio_lock_la_log_path().
#define fileio_lock_file_writew (fd, offset, whence, len) fileio_lock_region(fd, F_SETLKW, F_WRLCK, offset, whence, len)
Definition at line 296 of file file_io.c.
#define FILEIO_MAX_WAIT_DBTXT 300
Definition at line 175 of file file_io.c.
Referenced by fileio_lock().
#define FILEIO_MIN_FLUSH_PAGES_PER_SEC (41943040 / IO_PAGESIZE)
Definition at line 261 of file file_io.c.
Referenced by fileio_flush_control_add_tokens().
#define FILEIO_PAGE_FLUSH_DROP_RATE 0.1
Definition at line 276 of file file_io.c.
Referenced by fileio_flush_control_get_desired_rate().
#define FILEIO_PAGE_FLUSH_GROW_RATE 0.5
Definition at line 274 of file file_io.c.
Referenced by fileio_flush_control_get_desired_rate().
#define FILEIO_PAGE_SIZE_FULL_LEVEL (IO_PAGESIZE * FILEIO_FULL_LEVEL_EXP)
Definition at line 192 of file file_io.c.
#define FILEIO_RESTORE_DBVOLS_IO_PAGE_SIZE (sess) ((sess)->bkup.bkuphdr->bkpagesize + FILEIO_BACKUP_PAGE_OVERHEAD)
Definition at line 200 of file file_io.c.
Referenced by fileio_restore_volume(), and fileio_skip_restore_volume().
#define FILEIO_SET_BACKUP_PAGE_ID (area, pageid, psize)
Value:
do { \
      ((FILEIO_BACKUP_PAGE *)(area))->iopageid = pageid; \
      /* set the redundant copy of the pageid, alignment is important */ \
      FILEIO_SET_BACKUP_PAGE_ID_COPY(area, pageid, psize); \
  } while (false);
Definition at line 215 of file file_io.c.
Referenced by fileio_backup_volume(), fileio_initialize_backup(), and fileio_read_backup().
#define FILEIO_SET_BACKUP_PAGE_ID_COPY (area, pageid, psize)
Value:
*(PAGEID *)(((char *)(area)) + \
  (offsetof(FILEIO_BACKUP_PAGE, iopage) + psize)) = pageid
Definition at line 210 of file file_io.c.
Referenced by fileio_backup_volume(), and fileio_write_backup_node().
#define fileio_unlock_file (fd, offset, whence, len) fileio_lock_region(fd, F_SETLK, F_UNLCK, offset, whence, len)
Definition at line 298 of file file_io.c.
Referenced by fileio_release_lock(), and fileio_unlock().
#define FILEIO_USER_NAME_SIZE 9
Definition at line 164 of file file_io.c.
Referenced by fileio_check_lockby_file(), fileio_lock(), and fileio_lock_la_log_path().
#define FILEIO_VOLINFO_INCREMENT 32
Definition at line 302 of file file_io.c.
Referenced by fileio_allocate_and_initialize_volume_info(), fileio_cache(), fileio_dismount_all(), fileio_expand_permanent_volume_info(), fileio_expand_temporary_volume_info(), fileio_get_volume_descriptor(), fileio_get_volume_label(), fileio_initialize_volume_info_cache(), fileio_map_mounted(), fileio_max_permanent_volumes(), fileio_min_temporary_volumes(), fileio_reverse_traverse_permanent_volume(), fileio_reverse_traverse_temporary_volume(), fileio_traverse_permanent_volume(), and fileio_traverse_temporary_volume().
#define GET_NEXT_1K_SIZE (s) (((((s) - 1) / 1024) + 1) * 1024)
Definition at line 183 of file file_io.c.
#define GETPID () getpid()
Definition at line 170 of file file_io.c.
Referenced by fileio_check_lockby_file(), fileio_lock(), and fileio_lock_la_log_path().
#define MSGCAT_FILEIO_BACKUP_LABEL_INFO 21
Definition at line 151 of file file_io.c.
Referenced by fileio_finish_backup(), and fileio_get_next_backup_volume().
#define MSGCAT_FILEIO_BACKUP_TIME_MISMATCH 19
Definition at line 149 of file file_io.c.
Referenced by fileio_continue_restore().
#define MSGCAT_FILEIO_BACKUP_VINF_ERROR 20
Definition at line 150 of file file_io.c.
Referenced by fileio_read_backup_info_entries().
#define MSGCAT_FILEIO_BKUP_FILE 9
Definition at line 139 of file file_io.c.
Referenced by fileio_backup_volume(), fileio_list_restore(), and fileio_restore_volume().
#define MSGCAT_FILEIO_BKUP_FIND_REASON 24
Definition at line 154 of file file_io.c.
Referenced by fileio_get_next_backup_volume().
#define MSGCAT_FILEIO_BKUP_HDR 3
Definition at line 133 of file file_io.c.
Referenced by fileio_list_restore().
#define MSGCAT_FILEIO_BKUP_HDR_BKUP_PAGESIZE 27
Definition at line 157 of file file_io.c.
Referenced by fileio_list_restore().
#define MSGCAT_FILEIO_BKUP_HDR_DBINFO 6
Definition at line 136 of file file_io.c.
Referenced by fileio_list_restore().
#define MSGCAT_FILEIO_BKUP_HDR_INC_ACTIVELOG 29
Definition at line 159 of file file_io.c.
Referenced by fileio_list_restore().
#define MSGCAT_FILEIO_BKUP_HDR_LEVEL 7
Definition at line 137 of file file_io.c.
Referenced by fileio_list_restore().
#define MSGCAT_FILEIO_BKUP_HDR_LX_LSA 22
Definition at line 152 of file file_io.c.
Referenced by fileio_list_restore().
#define MSGCAT_FILEIO_BKUP_HDR_MAGICID 4
Definition at line 134 of file file_io.c.
#define MSGCAT_FILEIO_BKUP_HDR_RELEASES 5
Definition at line 135 of file file_io.c.
Referenced by fileio_list_restore().
#define MSGCAT_FILEIO_BKUP_HDR_TIME 8
Definition at line 138 of file file_io.c.
Referenced by fileio_list_restore().
#define MSGCAT_FILEIO_BKUP_HDR_ZIP_INFO 28
Definition at line 158 of file file_io.c.
Referenced by fileio_list_restore().
#define MSGCAT_FILEIO_BKUP_NEEDED 2
Definition at line 132 of file file_io.c.
#define MSGCAT_FILEIO_BKUP_NEXT_BKVOL 26
Definition at line 156 of file file_io.c.
Referenced by fileio_list_restore().
#define MSGCAT_FILEIO_BKUP_PREV_BKVOL 25
Definition at line 155 of file file_io.c.
Referenced by fileio_list_restore().
#define MSGCAT_FILEIO_DB_MISMATCH 17
Definition at line 147 of file file_io.c.
Referenced by fileio_continue_restore().
#define MSGCAT_FILEIO_INCORRECT_BKVOLUME 14
Definition at line 144 of file file_io.c.
Referenced by fileio_make_error_message().
#define MSGCAT_FILEIO_INPUT_RANGE_ERROR 13
Definition at line 143 of file file_io.c.
Referenced by fileio_find_restore_volume().
#define MSGCAT_FILEIO_LEVEL_MISMATCH 15
Definition at line 145 of file file_io.c.
Referenced by fileio_continue_restore().
#define MSGCAT_FILEIO_MAGIC_MISMATCH 16
Definition at line 146 of file file_io.c.
Referenced by fileio_continue_restore().
#define MSGCAT_FILEIO_NEWLOCATION 12
Definition at line 142 of file file_io.c.
Referenced by fileio_find_restore_volume().
#define MSGCAT_FILEIO_REST_RELO_NEEDED 10
Definition at line 140 of file file_io.c.
Referenced by fileio_find_restore_volume().
#define MSGCAT_FILEIO_REST_RELO_OPTIONS 11
Definition at line 141 of file file_io.c.
Referenced by fileio_find_restore_volume().
#define MSGCAT_FILEIO_RESTORE_FIND_REASON 23
Definition at line 153 of file file_io.c.
Referenced by fileio_continue_restore(), fileio_initialize_restore(), and fileio_read_restore().
#define MSGCAT_FILEIO_STARTS 1
Definition at line 131 of file file_io.c.
Referenced by fileio_find_restore_volume().
#define MSGCAT_FILEIO_UNIT_NUM_MISMATCH 18
Definition at line 148 of file file_io.c.
Referenced by fileio_continue_restore().
#define pthread_mutex_destroy (a)
Definition at line 306 of file file_io.c.
Referenced by fileio_decache(), fileio_dismount_all(), fileio_dismount_volume(), fileio_finalize_backup_thread(), fileio_flush_control_finalize(), and fileio_initialize_volume_info_cache().
#define pthread_mutex_init (a, b)
Definition at line 305 of file file_io.c.
Referenced by fileio_allocate_and_initialize_volume_info(), fileio_cache(), fileio_flush_control_initialize(), and fileio_initialize_backup_thread().
#define pthread_mutex_lock (a) 0
Definition at line 307 of file file_io.c.
Referenced by fileio_cache(), fileio_decache(), fileio_dismount_all(), fileio_expand_permanent_volume_info(), fileio_expand_temporary_volume_info(), fileio_expand_to(), fileio_find_volume_descriptor_with_label(), fileio_find_volume_id_with_label(), fileio_flush_control_add_tokens(), fileio_flush_control_get_token(), fileio_get_lockf_type(), fileio_get_volume_descriptor(), fileio_get_volume_id(), fileio_get_volume_label(), fileio_increase_flushed_page_count(), fileio_initialize_volume_info_cache(), fileio_os_read(), fileio_os_write(), fileio_synchronize(), fileio_synchronize_all(), fileio_traverse_system_volume(), fileio_write_backup_node(), and pwrite_with_injected_fault().
#define pthread_mutex_unlock (a)
Definition at line 308 of file file_io.c.
Referenced by fileio_cache(), fileio_decache(), fileio_dismount_all(), fileio_expand_permanent_volume_info(), fileio_expand_temporary_volume_info(), fileio_expand_to(), fileio_find_volume_descriptor_with_label(), fileio_find_volume_id_with_label(), fileio_flush_control_add_tokens(), fileio_flush_control_get_token(), fileio_get_lockf_type(), fileio_get_volume_descriptor(), fileio_get_volume_id(), fileio_get_volume_label(), fileio_increase_flushed_page_count(), fileio_initialize_volume_info_cache(), fileio_os_read(), fileio_os_write(), fileio_synchronize(), fileio_synchronize_all(), fileio_traverse_system_volume(), fileio_write_backup_node(), and pwrite_with_injected_fault().
Typedef Documentation
typedef union fileio_apply_function_arg APPLY_ARG
typedef struct fileio_backup_file_header FILEIO_BACKUP_FILE_HEADER
Definition at line 322 of file file_io.c.
typedef struct fileio_bkvinf_entry FILEIO_BACKUP_INFO_ENTRY
Definition at line 323 of file file_io.c.
typedef struct fileio_bkvinf_queues FILEIO_BACKUP_INFO_QUEUE
Definition at line 324 of file file_io.c.
typedef struct fileio_sys_volinfo_header FILEIO_SYSTEM_VOLUME_HEADER
Definition at line 326 of file file_io.c.
typedef struct fileio_sys_volinfo FILEIO_SYSTEM_VOLUME_INFO
Definition at line 325 of file file_io.c.
typedef struct fileio_volinfo_header FILEIO_VOLUME_HEADER
Definition at line 328 of file file_io.c.
typedef struct fileio_volinfo FILEIO_VOLUME_INFO
Definition at line 327 of file file_io.c.
typedef bool(* SYS_VOLINFO_APPLY_FN) (THREAD_ENTRY *thread_p, FILEIO_SYSTEM_VOLUME_INFO *sys_vol_info_p, APPLY_ARG *arg)
Definition at line 418 of file file_io.c.
typedef bool(* VOLINFO_APPLY_FN) (THREAD_ENTRY *thread_p, FILEIO_VOLUME_INFO *vol_info_p, APPLY_ARG *arg)
Definition at line 417 of file file_io.c.
Enumeration Type Documentation
enum FILEIO_RELOCATION_VOLUME
Enumerator
FILEIO_RELOCATION_FIRST
FILEIO_RELOCATION_QUIT
FILEIO_RELOCATION_RETRY
FILEIO_RELOCATION_ALTERNATE
FILEIO_RELOCATION_LAST
Definition at line 313 of file file_io.c.
Function Documentation
void fileio_abort_backup (THREAD_ENTRY * thread_p, FILEIO_BACKUP_SESSION * session_p, bool does_unformat_bk)
Definition at line 7052 of file file_io.c.
References fileio_backup_buffer::alltotalio, fileio_backup_db_buffer::area, io_backup_session::bkup, fileio_backup_buffer::bkuphdr, fileio_backup_buffer::buffer, fileio_backup_buffer::count, io_backup_session::dbfile, fileio_backup_buffer::dtype, FILEIO_BACKUP_READ, FILEIO_BACKUP_UNDEFINED_LEVEL, FILEIO_BACKUP_VOL_DIRECTORY, fileio_dismount(), fileio_dismount_without_fsync(), fileio_finalize_backup_info(), fileio_finalize_backup_thread(), FILEIO_FIRST_BACKUP_VOL_INFO, fileio_is_volume_exist_and_file(), fileio_remove_all_backup(), fileio_unformat(), FILEIO_ZIP_NONE_METHOD, free_and_init, fileio_backup_buffer::iosize, fileio_backup_header::level, fileio_backup_db_buffer::level, fileio_backup_db_buffer::lsa, LSA_SET_NULL(), fileio_backup_db_buffer::nbytes, NULL, NULL_VOLDES, NULL_VOLID, fileio_backup_buffer::ptr, io_backup_session::type, fileio_backup_buffer::vdes, fileio_backup_db_buffer::vdes, io_backup_session::verbose_fp, fileio_backup_buffer::vlabel, fileio_backup_db_buffer::vlabel, fileio_backup_db_buffer::volid, fileio_backup_buffer::voltotalio, and fileio_backup_header::zip_method.
Referenced by fileio_abort_restore(), fileio_start_backup(), and logpb_backup().
void fileio_abort_restore (THREAD_ENTRY * thread_p, FILEIO_BACKUP_SESSION * session_p)
Definition at line 8980 of file file_io.c.
References fileio_abort_backup().
Referenced by fileio_finish_restore(), fileio_list_restore(), and logpb_restore().
int fileio_add_volume_to_backup_info (const char * name_p, FILEIO_BACKUP_LEVEL level, int unit_num, int which_bkvinf)
Definition at line 10954 of file file_io.c.
References ARG_FILE_LINE, fileio_bkvinf_entry::bkvol_name, ER_FAILED, er_log_debug, fileio_allocate_backup_info(), fileio_initialize_backup_info(), fileio_bkvinf_entry::link, NO_ERROR, NULL, and fileio_bkvinf_entry::unit_num.
Referenced by fileio_get_next_backup_volume(), fileio_read_backup_info_entries(), fileio_read_restore(), fileio_start_backup(), and logpb_restore().
static int fileio_allocate_and_initialize_volume_info (FILEIO_VOLUME_HEADER * header_p, int idx) static
Definition at line 988 of file file_io.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), FILEIO_NOT_LOCKF, FILEIO_VOLINFO_INCREMENT, i, fileio_volinfo::lockf_type, NO_ERROR, NULL, NULL_VOLDES, NULL_VOLID, pthread_mutex_init, fileio_volinfo::vdes, fileio_volinfo::vlabel, fileio_volinfo::volid, and fileio_volinfo_header::volinfo.
Referenced by fileio_expand_permanent_volume_info(), and fileio_expand_temporary_volume_info().
static FILEIO_BACKUP_INFO_ENTRY * fileio_allocate_backup_info (int which_bkvinf) static
Definition at line 11197 of file file_io.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), fileio_bkvinf_entry::link, and NULL.
Referenced by fileio_add_volume_to_backup_info().
static FILEIO_NODE * fileio_allocate_node (FILEIO_QUEUE * qp, FILEIO_BACKUP_HEADER * backup_hdr) static
Definition at line 7495 of file file_io.c.
References fileio_node::area, ARG_FILE_LINE, assert, file_zip_info::buf_size, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), FILEIO_DBVOLS_IO_PAGE_SIZE, FILEIO_ZIP_LZ4_METHOD, FILEIO_ZIP_LZO1X_METHOD, FILEIO_ZIP_ZLIB_METHOD, free_and_init, fileio_queue::free_list, fileio_node::next, NULL, fileio_node::zip_info, and fileio_backup_header::zip_method.
Referenced by fileio_backup_volume(), fileio_decompress_restore_volume(), and fileio_write_backup_node().
int fileio_backup_volume (THREAD_ENTRY * thread_p, FILEIO_BACKUP_SESSION * session_p, const char * from_vol_label_p, VOLID from_vol_id, PAGEID last_page, bool is_only_updated_pages)
Definition at line 8215 of file file_io.c.
References fileio_thread_info::act_r_threads, fileio_backup_db_buffer::area, fileio_node::area, ARG_FILE_LINE, fileio_backup_header::bkpagesize, io_backup_session::bkup, fileio_backup_buffer::bkuphdr, CEIL_PTVDIV, fileio_thread_info::check_ratio, io_backup_session::dbfile, ER_ERROR_SEVERITY, ER_FAILED, ER_IO_MOUNT_FAIL, ER_IO_READ, er_set_with_oserror(), error(), fileio_allocate_node(), FILEIO_BACKUP_FILE_END_PAGE_ID, FILEIO_BACKUP_FILE_HEADER_PAGE_SIZE, FILEIO_BACKUP_FILE_START_PAGE_ID, FILEIO_BACKUP_PAGE_OVERHEAD, FILEIO_CHECK_FOR_INTERRUPT_INTERVAL, fileio_close(), fileio_compress_backup_node(), FILEIO_DBVOLS_IO_PAGE_SIZE, fileio_free_node(), fileio_get_base_file_name(), fileio_get_volume_descriptor(), fileio_open(), fileio_read_backup(), FILEIO_SET_BACKUP_PAGE_ID, FILEIO_SET_BACKUP_PAGE_ID_COPY, fileio_write_backup(), fileio_write_backup_node(), FILEIO_ZIP_NONE_METHOD, IO_PAGESIZE, fileio_thread_info::io_queue, fileio_backup_page::iopage, fileio_backup_page::iopageid, LOG_DBLOG_ACTIVE_VOLID, fileio_page_reserved::lsa, fileio_backup_db_buffer::lsa, LSA_ISNULL(), LSA_LT(), MSGCAT_CATALOG_CUBRID, MSGCAT_FILEIO_BKUP_FILE, msgcat_message(), MSGCAT_SET_IO, fileio_backup_file_header::nbytes, fileio_backup_db_buffer::nbytes, NO_ERROR, fileio_node::nread, NULL, NULL_VOLDES, NULL_VOLID, fileio_thread_info::num_threads, fileio_node::pageid, pgbuf_is_log_check_for_interrupts(), fileio_page::prv, io_backup_session::read_thread_info, rv, fileio_backup_db_buffer::vdes, io_backup_session::verbose_fp, fileio_backup_file_header::vlabel, fileio_backup_db_buffer::vlabel, fileio_backup_file_header::volid, fileio_backup_db_buffer::volid, fileio_backup_buffer::voltotalio, xdisk_get_total_numpages(), and fileio_backup_header::zip_method.
Referenced by logpb_backup(), logpb_backup_for_volume(), and logpb_fatal_error_internal().
static int fileio_cache (VOLID volid, const char * vlabel, int vdes, FILEIO_LOCKF_TYPE lockf_type) static
Definition at line 5946 of file file_io.c.
References fileio_sys_volinfo_header::anchor, ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), FILEIO_CHECK_AND_INITIALIZE_VOLUME_HEADER_CACHE, fileio_expand_permanent_volume_info(), fileio_expand_temporary_volume_info(), FILEIO_VOLINFO_INCREMENT, i, fileio_sys_volinfo::lockf_type, fileio_volinfo::lockf_type, LOG_DBDWB_VOLID, LOG_MAX_DBVOLID, fileio_volinfo_header::max_perm_vols, fileio_volinfo_header::max_temp_vols, fileio_sys_volinfo::next, fileio_volinfo_header::next_perm_volid, fileio_volinfo_header::next_temp_volid, NULL, NULL_VOLDES, NULL_VOLID, fileio_volinfo_header::num_volinfo_array, fileio_sys_volinfo_header::num_vols, pthread_mutex_init, pthread_mutex_lock, pthread_mutex_unlock, rv, strncpy_bufsize, fileio_sys_volinfo::vdes, fileio_volinfo::vdes, fileio_sys_volinfo::vlabel, fileio_volinfo::vlabel, fileio_sys_volinfo::volid, fileio_volinfo::volid, and fileio_volinfo_header::volinfo.
Referenced by fileio_create(), and fileio_mount().
static char* fileio_check_file_exist (char * name_p, char * new_guess_path_p, int check_size, int * max_name_size_p) static
Definition at line 5153 of file file_io.c.
References fileio_close(), FILEIO_DISK_FORMAT_MODE, FILEIO_DISK_PROTECTION_MODE, fileio_open(), and NULL_VOLDES.
Referenced by fileio_get_primitive_way_max().
static char* fileio_check_file_is_same (char * name_p, char * new_guess_path_p, int check_size, int * max_name_size_p, struct stat * buf) static
Definition at line 5193 of file file_io.c.
Referenced by fileio_get_primitive_way_max().
static void fileio_check_lockby_file (char * name_info_lock_p) static
Definition at line 1763 of file file_io.c.
References CUB_MAXHOSTNAMELEN, FILEIO_USER_NAME_SIZE, GETHOSTNAME, GETPID, getuserid(), host, NULL, and pid.
Referenced by fileio_unlock().
int fileio_clear_backup_info_level (int level, bool is_dealloc, int which_bkvinf)
Definition at line 11245 of file file_io.c.
References FILEIO_BACKUP_FULL_LEVEL, FILEIO_BACKUP_UNDEFINED_LEVEL, free_and_init, i, fileio_bkvinf_entry::link, NO_ERROR, and NULL.
Referenced by fileio_finalize_backup_info(), fileio_remove_all_backup(), logpb_backup(), and logpb_restore().
void fileio_close (int vol_fd)
Definition at line 2078 of file file_io.c.
References ARG_FILE_LINE, ER_IO_DISMOUNT_FAIL, er_set_with_oserror(), ER_WARNING_SEVERITY, fileio_get_volume_label_by_fd(), fileio_release_lock(), PEEK, prm_get_bool_value(), and PRM_ID_DBFILES_PROTECT.
Referenced by boot_reset_mk_after_restart_from_backup(), disk_can_overwrite_data_volume(), fileio_backup_volume(), fileio_check_file_exist(), fileio_continue_restore(), fileio_create(), fileio_dismount(), fileio_dismount_all(), fileio_dismount_volume(), fileio_dismount_without_fsync(), fileio_get_number_of_partition_free_pages(), fileio_get_number_of_partition_free_sectors(), fileio_get_primitive_way_max(), fileio_initialize_backup(), fileio_is_volume_exist(), fileio_lock_la_dbname(), fileio_mount(), fileio_unlock_la_dbname(), fileio_write_backup_end_time_to_header(), la_check_duplicated(), la_find_last_deleted_arv_num(), la_get_range_of_archive(), la_log_fetch_from_archive(), la_shutdown(), logpb_peek_header_of_active_log_from_backup(), tde_create_keys_file(), and xtde_change_mk_without_flock().
static void fileio_compensate_flush (THREAD_ENTRY * thread_p, int fd, int npage) static
Definition at line 607 of file file_io.c.
References assert, fileio_flush_control_get_token(), fileio_Flushed_page_count, fileio_increase_flushed_page_count(), fileio_synchronize_all(), NO_ERROR, NULL, prm_get_integer_value(), PRM_ID_PB_SYNC_ON_NFLUSH, rv, and thread_get_thread_entry_info().
Referenced by fileio_synchronize_all(), fileio_write(), and fileio_write_pages().
static int fileio_compress_backup_node (FILEIO_NODE * node, FILEIO_BACKUP_HEADER * backup_hdr) static
Definition at line 7660 of file file_io.c.
References fileio_node::area, ARG_FILE_LINE, assert, file_zip_page::buf, file_zip_page::buf_len, file_zip_info::buf_size, ER_ERROR_SEVERITY, ER_FAILED, ER_IO_LZ4_COMPRESS_FAIL, ER_LOG_DBBACKUP_FAIL, er_set(), error(), fileio_get_zip_level_string(), fileio_get_zip_method_string(), FILEIO_ZIP_LZ4_METHOD, FILEIO_ZIP_LZO1X_METHOD, FILEIO_ZIP_ZLIB_METHOD, NO_ERROR, fileio_node::nread, fileio_node::pageid, fileio_node::zip_info, fileio_backup_header::zip_level, fileio_backup_header::zip_method, and file_zip_info::zip_page.
Referenced by fileio_backup_volume(), and fileio_write_backup_node().
static FILEIO_BACKUP_SESSION * fileio_continue_restore (THREAD_ENTRY * thread_p, const char * db_fullname, INT64 db_creation, FILEIO_BACKUP_SESSION * session, bool first_time, bool authenticate, INT64 match_bkupcreation) static
Definition at line 9335 of file file_io.c.
References fileio_backup_db_buffer::area, ARG_FILE_LINE, asprintf(), io_backup_session::bkup, fileio_backup_header::bkup_iosize, fileio_backup_buffer::bkuphdr, fileio_backup_buffer::buffer, CTIME_MAX, CUBRID_MAGIC_DATABASE_BACKUP, CUBRID_MAGIC_DATABASE_BACKUP_OLD, fileio_backup_header::db_creation, fileio_backup_header::db_fullname, fileio_backup_header::db_iopagesize, fileio_backup_header::db_release, io_backup_session::dbfile, fileio_backup_buffer::dtype, ER_ERROR_SEVERITY, ER_FATAL_ERROR_SEVERITY, ER_GENERIC_ERROR, ER_IO_MOUNT_FAIL, ER_IO_NOT_A_BACKUP, ER_IO_NOT_A_BACKUP_OF_GIVEN_DATABASE, ER_LOG_BKUP_INCOMPATIBLE, ER_LOG_CANNOT_ACCESS_BACKUP, ER_LOG_RECOVER_ON_OLD_RELEASE, er_msg(), ER_OUT_OF_VIRTUAL_MEMORY, er_set(), er_set_with_oserror(), FILEIO_BACKUP_FILE_HEADER_PAGE_SIZE, FILEIO_BACKUP_FULL_LEVEL, FILEIO_BACKUP_PAGE_OVERHEAD, FILEIO_BACKUP_START_PAGE_ID, FILEIO_BACKUP_VOL_CONT_PAGE_ID, FILEIO_BACKUP_VOL_DEVICE, fileio_close(), fileio_ctime(), fileio_find_restore_volume(), FILEIO_FULL_LEVEL_EXP, fileio_get_base_file_name(), FILEIO_INITIAL_BACKUP_UNITS, fileio_make_backup_name(), fileio_make_error_message(), fileio_open(), fileio_read_restore_header(), FILEIO_RELOCATION_QUIT, free_and_init, IO_PAGESIZE, fileio_backup_header::iopageid, fileio_backup_buffer::iosize, fileio_backup_header::level, fileio_backup_db_buffer::level, fileio_backup_buffer::loc_db_fullname, fileio_backup_db_buffer::lsa, LSA_COPY(), fileio_backup_header::magic, MSGCAT_CATALOG_CUBRID, MSGCAT_FILEIO_BACKUP_TIME_MISMATCH, MSGCAT_FILEIO_DB_MISMATCH, MSGCAT_FILEIO_LEVEL_MISMATCH, MSGCAT_FILEIO_MAGIC_MISMATCH, MSGCAT_FILEIO_RESTORE_FIND_REASON, MSGCAT_FILEIO_UNIT_NUM_MISMATCH, msgcat_message(), MSGCAT_SET_IO, fileio_backup_buffer::name, NO_ERROR, NULL, NULL_VOLDES, fileio_backup_buffer::ptr, rel_is_log_compatible(), rel_name(), rel_release_string(), fileio_backup_header::start_lsa, fileio_backup_header::start_time, fileio_backup_header::unit_num, fileio_backup_buffer::vdes, and fileio_backup_buffer::vlabel.
Referenced by fileio_read_restore(), and fileio_start_restore().
int fileio_copy_volume (THREAD_ENTRY * thread_p, int from_vol_desc, DKNPAGES npages, const char * to_vol_label_p, VOLID to_vol_id, bool is_reset_recovery_info)
Definition at line 2809 of file file_io.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), fileio_create(), fileio_dismount(), fileio_format(), fileio_read(), fileio_reset_page_lsa(), FILEIO_SYNC_ALSO_FLUSH_DWB, fileio_synchronize(), fileio_unformat(), fileio_write_or_add_to_dwb(), free_and_init, IO_PAGESIZE, NULL, and NULL_VOLDES.
Referenced by logpb_copy_volume().
static int fileio_create (THREAD_ENTRY * thread_p, const char * db_fullname, const char * vlabel, VOLID volid, bool dolock, bool dosync) static
Definition at line 2104 of file file_io.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_IO_FORMAT_FAIL, ER_IO_MOUNT_LOCKED, er_log_debug, er_set_with_oserror(), fileio_cache(), fileio_close(), FILEIO_DISK_FORMAT_MODE, FILEIO_DISK_PROTECTION_MODE, fileio_dismount(), fileio_find_volume_descriptor_with_label(), fileio_lock(), FILEIO_NOT_LOCKF, fileio_open(), fileio_unformat(), fileio_unlock(), NULL_VOLDES, perfmon_inc_stat(), and PSTAT_FILE_NUM_CREATES.
Referenced by fileio_copy_volume(), fileio_create_backup_volume(), and fileio_format().
static int fileio_create_backup_volume (THREAD_ENTRY * thread_p, const char * db_fullname, const char * vlabel, VOLID volid, bool dolock, bool dosync, int atleast_pages) static
Definition at line 2236 of file file_io.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_IO_FORMAT_FAIL, ER_IO_FORMAT_OUT_OF_SPACE, er_set(), er_set_with_oserror(), fileio_create(), fileio_get_number_of_partition_free_pages(), fileio_open(), IO_PAGESIZE, NULL, NULL_VOLDES, and pgbuf_is_log_check_for_interrupts().
Referenced by fileio_get_next_backup_volume(), and fileio_start_backup().
static char * fileio_ctime (INT64 * clock, char * buf) static
Definition at line 1118 of file file_io.c.
References p.
Referenced by fileio_continue_restore(), fileio_finish_backup(), fileio_get_next_backup_volume(), fileio_lock(), and fileio_lock_la_log_path().
static void fileio_decache (THREAD_ENTRY * thread_p, int vdes) static
Definition at line 6065 of file file_io.c.
References fileio_sys_volinfo_header::anchor, fileio_find_previous_perm_volume(), fileio_find_previous_temp_volume(), fileio_is_volume_descriptor_equal(), FILEIO_NOT_LOCKF, fileio_traverse_permanent_volume(), fileio_traverse_temporary_volume(), free_and_init, fileio_sys_volinfo::lockf_type, fileio_volinfo::lockf_type, LOG_MAX_DBVOLID, fileio_sys_volinfo::next, fileio_volinfo_header::next_perm_volid, fileio_volinfo_header::next_temp_volid, NULL, NULL_VOLDES, NULL_VOLID, fileio_sys_volinfo_header::num_vols, pthread_mutex_destroy, pthread_mutex_lock, pthread_mutex_unlock, rv, fileio_sys_volinfo::vdes, fileio_volinfo::vdes, fileio_apply_function_arg::vdes, fileio_sys_volinfo::vlabel, fileio_volinfo::vlabel, fileio_sys_volinfo::volid, and fileio_volinfo::volid.
Referenced by fileio_dismount(), and fileio_dismount_without_fsync().
static int fileio_decompress_restore_volume (THREAD_ENTRY * thread_p, FILEIO_BACKUP_SESSION * session, int nbytes) static
Definition at line 10084 of file file_io.c.
References fileio_backup_db_buffer::area, ARG_FILE_LINE, assert, io_backup_session::bkup, fileio_backup_buffer::bkuphdr, file_zip_page::buf, file_zip_page::buf_len, io_backup_session::dbfile, ER_ERROR_SEVERITY, ER_FAILED, ER_IO_LZ4_COMPRESS_FAIL, ER_IO_LZ4_DECOMPRESS_FAIL, ER_IO_RESTORE_READ_ERROR, er_set(), error(), fileio_allocate_node(), fileio_free_node(), fileio_get_zip_level_string(), fileio_get_zip_method_string(), fileio_read_restore(), FILEIO_ZIP_LZ4_METHOD, FILEIO_ZIP_LZO1X_METHOD, FILEIO_ZIP_NONE_METHOD, FILEIO_ZIP_ZLIB_METHOD, fileio_thread_info::io_queue, NO_ERROR, NULL, io_backup_session::read_thread_info, rv, fileio_backup_header::unit_num, fileio_node::zip_info, fileio_backup_header::zip_level, fileio_backup_header::zip_method, and file_zip_info::zip_page.
Referenced by fileio_restore_volume(), and fileio_skip_restore_volume().
static FILEIO_NODE * fileio_delete_queue_head (FILEIO_QUEUE * qp) static
Definition at line 7630 of file file_io.c.
References fileio_queue::head, fileio_node::next, NULL, fileio_node::prev, fileio_queue::size, and fileio_queue::tail.
Referenced by fileio_finalize_backup_thread(), and fileio_write_backup_node().
void fileio_dismount (THREAD_ENTRY * thread_p, int vol_fd)
Definition at line 3134 of file file_io.c.
References fileio_close(), fileio_decache(), fileio_get_lockf_type(), fileio_get_volume_label_by_fd(), FILEIO_NOT_LOCKF, FILEIO_SYNC_ALSO_FLUSH_DWB, fileio_synchronize(), fileio_unlock(), PEEK, and fileio_backup_file_header::vlabel.
Referenced by alterdbhost(), boot_mount(), boot_reset_mk_after_restart_from_backup(), boot_restart_server(), dwb_create_internal(), dwb_destroy_internal(), dwb_load_and_recover_pages(), fileio_abort_backup(), fileio_copy_volume(), fileio_create(), fileio_format(), fileio_get_next_backup_volume(), fileio_mount(), fileio_restore_volume(), fileio_unformat_and_rename(), log_create_internal(), log_final(), log_initialize_internal(), log_recovery_notpartof_volumes(), logpb_archive_active_log(), logpb_background_archiving(), logpb_backup(), logpb_copy_database(), logpb_copy_volume(), logpb_delete(), logpb_dismount_log_archive(), logpb_fetch_from_archive(), logpb_find_oldest_available_page_id(), logpb_remove_all_in_log_path(), logpb_rename_all_volumes_files(), logpb_restore(), logpb_write_toflush_pages_to_archive(), tde_cipher_initialize(), tde_copy_keys_file(), tde_initialize(), xboot_copy(), xboot_delete(), xboot_emergency_patch(), xboot_initialize_server(), and xboot_soft_rename().
void fileio_dismount_all (THREAD_ENTRY * thread_p)
Definition at line 3374 of file file_io.c.
References fileio_sys_volinfo_header::anchor, fileio_close(), fileio_dismount_volume(), FILEIO_NOT_LOCKF, FILEIO_SYNC_ONLY, fileio_synchronize(), fileio_Sys_vol_info_header, fileio_traverse_permanent_volume(), fileio_traverse_temporary_volume(), fileio_unlock(), fileio_Vol_info_header, FILEIO_VOLINFO_INCREMENT, free_and_init, i, fileio_sys_volinfo::lockf_type, LOG_MAX_DBVOLID, fileio_volinfo_header::max_perm_vols, fileio_volinfo_header::max_temp_vols, fileio_sys_volinfo::next, fileio_volinfo_header::next_perm_volid, fileio_volinfo_header::next_temp_volid, NULL, NULL_VOLDES, pthread_mutex_destroy, pthread_mutex_lock, pthread_mutex_unlock, rv, fileio_sys_volinfo::vdes, fileio_sys_volinfo::vlabel, VOLID_MAX, and fileio_volinfo_header::volinfo.
Referenced by boot_server_all_finalize().
static bool fileio_dismount_volume (THREAD_ENTRY * thread_p, FILEIO_VOLUME_INFO * vol_info_p, APPLY_ARG * ignore_arg) static
Definition at line 3346 of file file_io.c.
References fileio_close(), FILEIO_NOT_LOCKF, FILEIO_SYNC_ALSO_FLUSH_DWB, fileio_synchronize(), fileio_unlock(), fileio_volinfo::lockf_type, NULL_VOLDES, pthread_mutex_destroy, fileio_volinfo::vdes, and fileio_volinfo::vlabel.
Referenced by fileio_dismount_all().
void fileio_dismount_without_fsync (THREAD_ENTRY * thread_p, int vol_fd)
Definition at line 3170 of file file_io.c.
References fileio_close(), fileio_decache(), fileio_get_lockf_type(), fileio_get_volume_label_by_fd(), FILEIO_NOT_LOCKF, fileio_unlock(), and PEEK.
Referenced by fileio_abort_backup(), fileio_get_next_backup_volume(), and fileio_read_restore().
static int fileio_expand_permanent_volume_info (FILEIO_VOLUME_HEADER * header, int volid) static
Definition at line 1029 of file file_io.c.
References fileio_allocate_and_initialize_volume_info(), FILEIO_VOLINFO_INCREMENT, fileio_volinfo_header::max_perm_vols, fileio_volinfo_header::max_temp_vols, NO_ERROR, fileio_volinfo_header::num_volinfo_array, pthread_mutex_lock, pthread_mutex_unlock, and rv.
Referenced by fileio_cache().
static int fileio_expand_temporary_volume_info (FILEIO_VOLUME_HEADER * header, int volid) static
Definition at line 1074 of file file_io.c.
References fileio_allocate_and_initialize_volume_info(), FILEIO_VOLINFO_INCREMENT, LOG_MAX_DBVOLID, fileio_volinfo_header::max_perm_vols, fileio_volinfo_header::max_temp_vols, NO_ERROR, fileio_volinfo_header::num_volinfo_array, pthread_mutex_lock, pthread_mutex_unlock, rv, and fileio_backup_file_header::volid.
Referenced by fileio_cache().
int fileio_expand_to (THREAD_ENTRY * thread_p, VOLID vol_id, DKNPAGES size_npages, DB_VOLTYPE voltype)
Definition at line 2512 of file file_io.c.
References ARG_FILE_LINE, assert, ASSERT_ERROR_AND_SET, assert_release, DB_PERMANENT_VOLTYPE, db_private_alloc, db_private_free, DB_TEMPORARY_VOLTYPE, ER_ERROR_SEVERITY, ER_FAILED, ER_GENERIC_ERROR, ER_INTERRUPTED, ER_IO_EXPAND_OUT_OF_SPACE, ER_IO_FORMAT_BAD_NPAGES, ER_IO_TRUNCATE, er_log_debug, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), er_set_with_oserror(), FILEIO_GET_FILE_SIZE, fileio_get_number_of_partition_free_pages(), fileio_get_volume_descriptor(), fileio_get_volume_label(), fileio_get_volume_label_by_fd(), fileio_initialize_pages(), fileio_initialize_res(), fileio_write_or_add_to_dwb(), IO_PAGESIZE, LOG_ISRESTARTED, NO_ERROR, NULL, NULL_VOLDES, PEEK, pthread_mutex_lock, pthread_mutex_unlock, rv, and VOL_MAX_NPAGES.
Referenced by disk_rv_redo_volume_expand(), and disk_volume_expand().
static int fileio_fill_hole_during_restore (THREAD_ENTRY * thread_p, int * next_pageid, int stop_pageid, FILEIO_BACKUP_SESSION * session, FILEIO_RESTORE_PAGE_BITMAP * page_bitmap) static
Definition at line 10035 of file file_io.c.
References ARG_FILE_LINE, io_backup_session::bkup, fileio_backup_buffer::bkuphdr, io_backup_session::dbfile, ER_ERROR_SEVERITY, ER_FAILED, ER_IO_RESTORE_READ_ERROR, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), fileio_initialize_res(), fileio_write_restore(), free_and_init, IO_PAGESIZE, fileio_backup_db_buffer::level, NO_ERROR, NULL, fileio_backup_header::unit_num, fileio_backup_db_buffer::vdes, and fileio_backup_db_buffer::volid.
Referenced by fileio_restore_volume().
void fileio_finalize_backup_info (int which_bkvinf)
Definition at line 11143 of file file_io.c.
References FILEIO_BACKUP_FULL_LEVEL, and fileio_clear_backup_info_level().
Referenced by fileio_abort_backup(), fileio_read_backup_info_entries(), logpb_backup(), logpb_delete(), logpb_rename_all_volumes_files(), and logpb_restore().
static void fileio_finalize_backup_thread (FILEIO_BACKUP_SESSION * session_p, FILEIO_ZIP_METHOD zip_method) static
Definition at line 6963 of file file_io.c.
References fileio_node::area, ARG_FILE_LINE, ER_CSS_PTHREAD_COND_DESTROY, ER_CSS_PTHREAD_MUTEX_DESTROY, ER_ERROR_SEVERITY, er_set(), fileio_delete_queue_head(), fileio_free_node(), FILEIO_ZIP_LZ4_METHOD, FILEIO_ZIP_LZO1X_METHOD, FILEIO_ZIP_ZLIB_METHOD, free_and_init, fileio_queue::free_list, fileio_thread_info::initialized, fileio_thread_info::io_queue, fileio_node::next, NULL, pthread_mutex_destroy, io_backup_session::read_thread_info, rv, fileio_queue::size, and fileio_node::zip_info.
Referenced by fileio_abort_backup().
VOLID fileio_find_next_perm_volume (THREAD_ENTRY * thread_p, VOLID volid)
Definition at line 6410 of file file_io.c.
References assert, FILEIO_CHECK_AND_INITIALIZE_VOLUME_HEADER_CACHE, fileio_get_volume_descriptor(), fileio_is_volume_id_gt(), fileio_traverse_permanent_volume(), NULL_VOLDES, NULL_VOLID, fileio_apply_function_arg::vol_id, fileio_backup_file_header::volid, and fileio_volinfo::volid.
Referenced by log_recreate(), logpb_backup(), logpb_checkpoint(), logpb_copy_database(), logpb_delete(), and logpb_rename_all_volumes_files().
VOLID fileio_find_previous_perm_volume (THREAD_ENTRY * thread_p, VOLID volid)
Definition at line 6434 of file file_io.c.
References assert, FILEIO_CHECK_AND_INITIALIZE_VOLUME_HEADER_CACHE, fileio_get_volume_descriptor(), fileio_is_volume_id_lt(), fileio_reverse_traverse_permanent_volume(), NULL_VOLDES, NULL_VOLID, fileio_apply_function_arg::vol_id, fileio_backup_file_header::volid, and fileio_volinfo::volid.
Referenced by disk_format(), fileio_decache(), fileio_restore_volume(), and logpb_rename_all_volumes_files().
VOLID fileio_find_previous_temp_volume (THREAD_ENTRY * thread_p, VOLID volid)
Definition at line 6458 of file file_io.c.
References assert, FILEIO_CHECK_AND_INITIALIZE_VOLUME_HEADER_CACHE, fileio_get_volume_descriptor(), fileio_is_volume_id_gt(), fileio_reverse_traverse_temporary_volume(), NULL_VOLDES, NULL_VOLID, fileio_apply_function_arg::vol_id, fileio_backup_file_header::volid, and fileio_volinfo::volid.
Referenced by fileio_decache().
static FILEIO_RELOCATION_VOLUME fileio_find_restore_volume (THREAD_ENTRY * thread_p, const char * dbname, char * to_volname, int unit_num, FILEIO_BACKUP_LEVEL level, int reason) static
Definition at line 10622 of file file_io.c.
References ARG_FILE_LINE, asprintf(), ER_ERROR_SEVERITY, ER_GENERIC_ERROR, er_set(), fileio_get_backup_level_string(), FILEIO_MAX_USER_RESPONSE_SIZE, FILEIO_PROMPT_RANGE_WITH_SECONDARY_STRING_TYPE, FILEIO_RELOCATION_ALTERNATE, FILEIO_RELOCATION_FIRST, FILEIO_RELOCATION_LAST, FILEIO_RELOCATION_QUIT, FILEIO_RELOCATION_RETRY, fileio_request_user_response(), MSGCAT_CATALOG_CUBRID, MSGCAT_FILEIO_INPUT_RANGE_ERROR, MSGCAT_FILEIO_NEWLOCATION, MSGCAT_FILEIO_REST_RELO_NEEDED, MSGCAT_FILEIO_REST_RELO_OPTIONS, MSGCAT_FILEIO_STARTS, msgcat_message(), MSGCAT_SET_IO, NO_ERROR, and NULL.
Referenced by fileio_continue_restore(), fileio_get_next_backup_volume(), fileio_initialize_restore(), and fileio_read_restore().
static FILEIO_SYSTEM_VOLUME_INFO * fileio_find_system_volume (THREAD_ENTRY * thread_p, SYS_VOLINFO_APPLY_FN apply_function, APPLY_ARG * arg) static
Definition at line 3554 of file file_io.c.
References fileio_sys_volinfo_header::anchor, fileio_sys_volinfo::next, NULL, NULL_VOLDES, and fileio_sys_volinfo::vdes.
Referenced by fileio_find_volume_descriptor_with_label(), fileio_find_volume_id_with_label(), fileio_get_lockf_type(), fileio_get_volume_descriptor(), fileio_get_volume_id(), fileio_get_volume_label(), and pwrite_with_injected_fault().
int fileio_find_volume_descriptor_with_label (const char * vol_label_p)
Definition at line 6544 of file file_io.c.
References FILEIO_CHECK_AND_INITIALIZE_VOLUME_HEADER_CACHE, fileio_find_system_volume(), fileio_is_system_volume_label_equal(), fileio_is_volume_label_equal(), fileio_traverse_permanent_volume(), fileio_traverse_temporary_volume(), NULL, NULL_VOLDES, pthread_mutex_lock, pthread_mutex_unlock, rv, fileio_sys_volinfo::vdes, fileio_volinfo::vdes, and fileio_apply_function_arg::vol_label.
Referenced by disk_can_overwrite_data_volume(), disk_rv_redo_dboutside_newvol(), fileio_create(), fileio_is_volume_exist(), fileio_is_volume_exist_and_file(), fileio_mount(), and fileio_unformat_and_rename().
VOLID fileio_find_volume_id_with_label (THREAD_ENTRY * thread_p, const char * vol_label_p)
Definition at line 6319 of file file_io.c.
References FILEIO_CHECK_AND_INITIALIZE_VOLUME_HEADER_CACHE, fileio_find_system_volume(), fileio_is_system_volume_label_equal(), fileio_is_volume_label_equal(), fileio_traverse_permanent_volume(), fileio_traverse_temporary_volume(), NULL_VOLID, pthread_mutex_lock, pthread_mutex_unlock, rv, fileio_apply_function_arg::vol_label, fileio_sys_volinfo::volid, and fileio_volinfo::volid.
Referenced by db_warnspace(), and disk_unformat().
FILEIO_BACKUP_SESSION* fileio_finish_backup (THREAD_ENTRY * thread_p, FILEIO_BACKUP_SESSION * session_p)
Definition at line 7336 of file file_io.c.
References fileio_backup_db_buffer::area, ARG_FILE_LINE, asprintf(), io_backup_session::bkup, fileio_backup_buffer::bkuphdr, CAST_BUFLEN, fileio_backup_buffer::count, CTIME_MAX, fileio_backup_header::db_fullname, io_backup_session::dbfile, fileio_backup_buffer::dtype, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), FILEIO_BACKUP_END_PAGE_ID, FILEIO_BACKUP_VOL_DEVICE, FILEIO_BACKUP_VOL_DIRECTORY, fileio_ctime(), fileio_flush_backup(), fileio_get_base_file_name(), FILEIO_MAX_USER_RESPONSE_SIZE, FILEIO_PROMPT_DISPLAY_ONLY, fileio_request_user_response(), FILEIO_SYNC_ONLY, fileio_synchronize(), fileio_write_backup(), fileio_write_backup_end_time_to_header(), fileio_write_backup_end_time_to_last_page(), fileio_backup_page::iopageid, fileio_backup_buffer::iosize, fileio_backup_header::level, MSGCAT_CATALOG_CUBRID, MSGCAT_FILEIO_BACKUP_LABEL_INFO, msgcat_message(), MSGCAT_SET_IO, fileio_backup_buffer::name, fileio_backup_file_header::nbytes, NO_ERROR, NULL, fileio_backup_buffer::ptr, fileio_backup_header::start_time, fileio_backup_header::unit_num, fileio_backup_buffer::vdes, and fileio_backup_buffer::voltotalio.
Referenced by logpb_backup().
int fileio_finish_restore (THREAD_ENTRY * thread_p, FILEIO_BACKUP_SESSION * session_p)
Definition at line 9683 of file file_io.c.
References fileio_abort_restore(), fileio_synchronize_all(), and success().
Referenced by fileio_list_restore(), and logpb_restore().
static int fileio_flush_backup (THREAD_ENTRY * thread_p, FILEIO_BACKUP_SESSION * session) static
Definition at line 8577 of file file_io.c.
References ARG_FILE_LINE, io_backup_session::bkup, fileio_backup_buffer::buffer, CEIL_PTVDIV, cubregex::count(), fileio_backup_buffer::count, fileio_backup_buffer::dtype, ER_ERROR_SEVERITY, ER_FAILED, ER_IO_WRITE, er_log_debug, er_set_with_oserror(), FILEIO_BACKUP_VOL_DIRECTORY, fileio_get_next_backup_volume(), fileio_write_backup_header(), IO_PAGESIZE, fileio_backup_file_header::nbytes, NO_ERROR, OFF_T_MAX, prm_get_bigint_value(), PRM_ID_IO_BACKUP_MAX_VOLUME_SIZE, fileio_backup_buffer::ptr, fileio_backup_buffer::vdes, fileio_backup_buffer::vlabel, and fileio_backup_buffer::voltotalio.
Referenced by fileio_finish_backup(), and fileio_write_backup().
int fileio_flush_control_add_tokens (THREAD_ENTRY * thread_p, INT64 diff_usec, int * token_gen, int * token_consumed)
Definition at line 819 of file file_io.c.
References assert, fc_Token_bucket, fileio_flush_control_get_desired_rate(), FILEIO_MIN_FLUSH_PAGES_PER_SEC, NO_ERROR, NULL, flush_stats::num_log_pages, flush_stats::num_pages, flush_stats::num_tokens, perfmon_add_stat(), prm_get_bool_value(), prm_get_integer_value(), PRM_ID_ADAPTIVE_FLUSH_CONTROL, PRM_ID_MAX_FLUSH_PAGES_PER_SECOND, PSTAT_FC_NUM_LOG_PAGES, PSTAT_FC_NUM_PAGES, PSTAT_FC_TOKENS, pthread_mutex_lock, pthread_mutex_unlock, rv, token_bucket::token_consumed, token_bucket::token_mutex, token_bucket::tokens, and token_bucket::waiter_cond.
Referenced by pgbuf_get_page_flush_interval().
void fileio_flush_control_finalize (void)
Definition at line 702 of file file_io.c.
References assert, fc_Token_bucket, NULL, pthread_mutex_destroy, token_bucket::token_mutex, and token_bucket::waiter_cond.
Referenced by pgbuf_get_page_flush_interval().
static int fileio_flush_control_get_desired_rate (TOKEN_BUCKET * tb) static
Definition at line 881 of file file_io.c.
References FILEIO_PAGE_FLUSH_DROP_RATE, FILEIO_PAGE_FLUSH_GROW_RATE, flush_stats::num_tokens, pgbuf_flush_control_from_dirty_ratio(), and token_bucket::tokens.
Referenced by fileio_flush_control_add_tokens().
static int fileio_flush_control_get_token (THREAD_ENTRY * thread_p, int ntoken) static
Definition at line 731 of file file_io.c.
References ARG_FILE_LINE, assert, er_log_debug, fc_Token_bucket, LOG_CS_OWN(), NO_ERROR, NULL, flush_stats::num_log_pages, flush_stats::num_pages, PSTAT_PB_COMPENSATE_FLUSH, pthread_mutex_lock, pthread_mutex_unlock, rv, token_bucket::token_consumed, token_bucket::token_mutex, token_bucket::tokens, and token_bucket::waiter_cond.
Referenced by fileio_compensate_flush().
int fileio_flush_control_initialize (void)
Definition at line 658 of file file_io.c.
References ARG_FILE_LINE, assert, ER_CSS_PTHREAD_COND_INIT, ER_CSS_PTHREAD_MUTEX_INIT, ER_ERROR_SEVERITY, er_set_with_oserror(), fc_Token_bucket_s, NO_ERROR, NULL, flush_stats::num_log_pages, flush_stats::num_pages, flush_stats::num_tokens, pthread_mutex_init, rv, token_bucket::token_consumed, token_bucket::token_mutex, token_bucket::tokens, and token_bucket::waiter_cond.
Referenced by pgbuf_get_page_flush_interval().
int fileio_format (THREAD_ENTRY * thread_p, const char * db_full_name_p, const char * vol_label_p, VOLID vol_id, DKNPAGES npages, bool is_sweep_clean, bool is_do_lock, bool is_do_sync, size_t page_size, int kbytes_to_be_written_per_sec, bool reuse_file)
Definition at line 2314 of file file_io.c.
References ARG_FILE_LINE, ER_BO_CANNOT_CREATE_VOL, er_errid(), ER_ERROR_SEVERITY, ER_INTERRUPTED, ER_IO_FORMAT_BAD_NPAGES, ER_IO_FORMAT_OUT_OF_SPACE, ER_IO_MOUNT_FAIL, ER_IO_WRITE, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), er_set_with_oserror(), FI_TEST, FI_TEST_FILE_IO_FORMAT, fileio_create(), fileio_dismount(), FILEIO_GET_FILE_SIZE, fileio_get_number_of_partition_free_pages(), fileio_initialize_pages(), fileio_initialize_res(), fileio_is_volume_exist(), fileio_mount(), fileio_unformat(), fileio_write(), FILEIO_WRITE_DEFAULT_WRITE, fileio_write_or_add_to_dwb(), free_and_init, NULL, NULL_VOLDES, page_size, and VOL_MAX_NPAGES.
Referenced by disk_format(), disk_rv_redo_dboutside_newvol(), dwb_create_internal(), fileio_copy_volume(), fileio_restore_volume(), log_create_internal(), log_initialize_internal(), log_recovery_resetlog(), logpb_archive_active_log(), and logpb_copy_database().
static FILEIO_NODE * fileio_free_node (FILEIO_QUEUE * qp, FILEIO_NODE * node) static
Definition at line 7580 of file file_io.c.
References fileio_queue::free_list, fileio_queue::head, fileio_node::next, NULL, fileio_node::prev, fileio_queue::size, and fileio_queue::tail.
Referenced by fileio_backup_volume(), fileio_decompress_restore_volume(), fileio_finalize_backup_thread(), and fileio_write_backup_node().
const char* fileio_get_backup_info_volume_name (FILEIO_BACKUP_LEVEL level, int unit_num, int which_bkvinf)
Definition at line 11118 of file file_io.c.
References fileio_bkvinf_entry::bkvol_name, fileio_bkvinf_entry::link, NULL, and fileio_bkvinf_entry::unit_num.
Referenced by fileio_get_backup_volume(), fileio_read_restore(), fileio_remove_all_backup(), fileio_write_backup_end_time_to_header(), and logpb_backup().
static const char * fileio_get_backup_level_string (FILEIO_BACKUP_LEVEL level) static
Definition at line 10723 of file file_io.c.
References FILEIO_BACKUP_BIG_INCREMENT_LEVEL, FILEIO_BACKUP_FULL_LEVEL, and FILEIO_BACKUP_SMALL_INCREMENT_LEVEL.
Referenced by fileio_find_restore_volume(), and fileio_list_restore().
int fileio_get_backup_volume (THREAD_ENTRY * thread_p, const char * db_fullname, const char * logpath, const char * user_backuppath, int try_level, char * from_volbackup)
Definition at line 9846 of file file_io.c.
References ARG_FILE_LINE, ER_FAILED, ER_FATAL_ERROR_SEVERITY, ER_LOG_CANNOT_ACCESS_BACKUP, er_set(), FILEIO_FIRST_BACKUP_VOL_INFO, fileio_get_backup_info_volume_name(), fileio_get_base_file_name(), FILEIO_INITIAL_BACKUP_UNITS, fileio_make_backup_name(), fileio_make_backup_volume_info_name(), fileio_read_backup_info_entries(), MSGCAT_CATALOG_CUBRID, MSGCAT_LOG_BACKUPINFO_NEEDED, MSGCAT_LOG_NEWLOCATION, MSGCAT_LOG_STARTS, msgcat_message(), MSGCAT_SET_LOG, NO_ERROR, and NULL.
Referenced by logpb_restore(), and print_backup_info().
const char* fileio_get_base_file_name (const char * full_name_p)
Definition at line 5533 of file file_io.c.
References NULL, and PATH_SEPARATOR.
Referenced by alterdbhost(), boot_db_name(), boot_find_rest_temp_volumes(), boot_get_new_volume_name_and_id(), boot_make_temp_volume_fullname(), boot_restart_server(), disk_add_volume(), fileio_backup_volume(), fileio_continue_restore(), fileio_finish_backup(), fileio_get_backup_volume(), fileio_get_directory_path(), fileio_get_next_backup_volume(), fileio_get_next_restore_file(), fileio_initialize_backup(), fileio_restore_volume(), fileio_write_backup_node(), log_recovery_notpartof_volumes(), logpb_backup(), logpb_is_log_active_from_backup_useful(), logpb_restore(), logpb_start_where_path(), logpb_verify_length(), tde_make_keys_file_fullname(), xboot_copy(), xboot_delete(), xboot_emergency_patch(), xboot_initialize_server(), xboot_soft_rename(), and xvacuum_dump().
char* fileio_get_directory_path (char * path_p, const char * full_name_p)
Definition at line 5567 of file file_io.c.
References ARG_FILE_LINE, assert, ER_BO_CWD_FAIL, ER_ERROR_SEVERITY, er_set_with_oserror(), fileio_get_base_file_name(), and NULL.
Referenced by boot_find_rest_temp_volumes(), boot_get_new_volume_name_and_id(), boot_make_temp_volume_fullname(), disk_add_volume(), fileio_get_next_backup_volume(), fileio_get_next_restore_file(), fileio_initialize_backup(), fileio_read_restore(), log_recovery_notpartof_volumes(), logpb_backup(), logpb_is_log_active_from_backup_useful(), logpb_next_where_path(), logpb_restore(), and xboot_soft_rename().
static int fileio_get_lock (int fd, const char * vlabel) static
Definition at line 2039 of file file_io.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_IO_GET_LOCK_FAIL, er_set_with_oserror(), error(), fileio_lock_file_read, and NO_ERROR.
Referenced by fileio_open().
static FILEIO_LOCKF_TYPE fileio_get_lockf_type (int vdes) static
Definition at line 6588 of file file_io.c.
References io_backup_session::bkup, DB_INT32_MAX, FILEIO_BACKUP_FILE_HEADER_PAGE_SIZE, FILEIO_BACKUP_HEADER_IO_SIZE, FILEIO_CHECK_AND_INITIALIZE_VOLUME_HEADER_CACHE, fileio_find_system_volume(), fileio_is_system_volume_descriptor_equal(), fileio_is_volume_descriptor_equal(), FILEIO_NOT_LOCKF, fileio_traverse_permanent_volume(), fileio_traverse_temporary_volume(), fileio_backup_buffer::iosize, fileio_sys_volinfo::lockf_type, fileio_volinfo::lockf_type, NULL, prm_get_bigint_value(), prm_get_integer_value(), PRM_ID_IO_BACKUP_MAX_VOLUME_SIZE, PRM_ID_IO_BACKUP_NBUFFERS, pthread_mutex_lock, pthread_mutex_unlock, rv, and fileio_apply_function_arg::vdes.
Referenced by fileio_dismount(), and fileio_dismount_without_fsync().
int fileio_get_max_name (const char * given_path_p, long int * file_name_max_p, long int * path_name_max_p)
Definition at line 5459 of file file_io.c.
References fileio_get_primitive_way_max(), NULL, and strncpy_bufsize.
Referenced by logpb_verify_length().
static int fileio_get_next_backup_volume (THREAD_ENTRY * thread_p, FILEIO_BACKUP_SESSION * session, bool user_new) static
Definition at line 10803 of file file_io.c.
References fileio_backup_buffer::alltotalio, ARG_FILE_LINE, asprintf(), io_backup_session::bkup, fileio_backup_buffer::bkuphdr, CTIME_MAX, fileio_backup_header::db_fullname, fileio_backup_header::db_next_bkvolname, fileio_backup_header::db_prec_bkvolname, io_backup_session::dbfile, fileio_backup_buffer::dtype, ER_ERROR_SEVERITY, ER_FAILED, ER_FATAL_ERROR_SEVERITY, ER_IO_MOUNT_FAIL, ER_LOG_CANNOT_ACCESS_BACKUP, er_msg(), ER_OUT_OF_VIRTUAL_MEMORY, er_set(), er_set_with_oserror(), fileio_add_volume_to_backup_info(), FILEIO_BACKUP_FULL_LEVEL, FILEIO_BACKUP_MINIMUM_NUM_PAGES, FILEIO_BACKUP_MINIMUM_NUM_PAGES_FULL_LEVEL, FILEIO_BACKUP_VOL_CONT_PAGE_ID, FILEIO_BACKUP_VOL_DEVICE, FILEIO_BACKUP_VOL_DIRECTORY, fileio_create_backup_volume(), fileio_ctime(), fileio_dismount(), fileio_dismount_without_fsync(), fileio_find_restore_volume(), FILEIO_FIRST_BACKUP_VOL_INFO, fileio_get_base_file_name(), fileio_get_directory_path(), fileio_make_backup_name(), FILEIO_MAX_USER_RESPONSE_SIZE, FILEIO_PROMPT_DISPLAY_ONLY, FILEIO_RELOCATION_QUIT, fileio_request_user_response(), fileio_backup_header::iopageid, fileio_backup_header::level, fileio_backup_db_buffer::level, LOG_DBCOPY_VOLID, MSGCAT_CATALOG_CUBRID, MSGCAT_FILEIO_BACKUP_LABEL_INFO, MSGCAT_FILEIO_BKUP_FIND_REASON, msgcat_message(), MSGCAT_SET_IO, fileio_backup_buffer::name, NO_ERROR, NULL, NULL_VOLDES, fileio_backup_header::start_time, fileio_backup_header::unit_num, fileio_backup_buffer::vdes, fileio_backup_buffer::vlabel, and fileio_backup_buffer::voltotalio.
Referenced by fileio_flush_backup().
int fileio_get_next_restore_file (THREAD_ENTRY * thread_p, FILEIO_BACKUP_SESSION * session_p, char * file_name_p, VOLID * vol_id_p)
Definition at line 9960 of file file_io.c.
References fileio_backup_db_buffer::area, ARG_FILE_LINE, io_backup_session::bkup, fileio_backup_buffer::bkuphdr, io_backup_session::dbfile, fileio_backup_buffer::dtype, ER_ERROR_SEVERITY, ER_IO_RESTORE_READ_ERROR, er_set(), FILEIO_BACKUP_END_PAGE_ID, FILEIO_BACKUP_FILE_HEADER_PAGE_SIZE, FILEIO_BACKUP_FILE_START_PAGE_ID, FILEIO_BACKUP_VOL_DEVICE, FILEIO_GET_BACKUP_PAGE_ID, fileio_get_base_file_name(), fileio_get_directory_path(), fileio_read_backup_end_time_from_last_page(), fileio_read_restore(), fileio_backup_page::iopage, fileio_backup_header::level, fileio_backup_db_buffer::level, fileio_backup_buffer::loc_db_fullname, LOG_DBLOG_ACTIVE_VOLID, LOG_DBLOG_ARCHIVE_VOLID, LOG_DBLOG_BKUPINFO_VOLID, LOG_DBLOG_INFO_VOLID, fileio_backup_buffer::log_path, fileio_backup_file_header::nbytes, fileio_backup_db_buffer::nbytes, NO_ERROR, PATH_SEPARATOR, fileio_backup_header::unit_num, fileio_backup_file_header::vlabel, fileio_backup_file_header::volid, and fileio_backup_db_buffer::volid.
Referenced by logpb_restore().
int fileio_get_number_of_partition_free_pages (const char * path_p, size_t page_size)
Definition at line 4937 of file file_io.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_IO_MOUNT_FAIL, er_set_with_oserror(), fileio_close(), FILEIO_DISK_FORMAT_MODE, FILEIO_DISK_PROTECTION_MODE, fileio_get_number_of_partition_free_pages(), fileio_open(), IO_PAGESIZE, NULL_VOLDES, and page_size.
Referenced by fileio_create_backup_volume(), fileio_expand_to(), fileio_format(), and fileio_get_number_of_partition_free_pages().
DKNSECTS fileio_get_number_of_partition_free_sectors (const char * path_p)
Definition at line 5003 of file file_io.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_IO_MOUNT_FAIL, er_set_with_oserror(), fileio_close(), FILEIO_DISK_FORMAT_MODE, FILEIO_DISK_PROTECTION_MODE, fileio_get_number_of_partition_free_sectors(), fileio_open(), IO_SECTORSIZE, and NULL_VOLDES.
Referenced by disk_add_volume(), and fileio_get_number_of_partition_free_sectors().
DKNPAGES fileio_get_number_of_volume_pages (int vol_fd, size_t page_size)
Definition at line 4918 of file file_io.c.
References page_size.
Referenced by dwb_check_data_page_is_sane(), dwb_load_and_recover_pages(), and log_get_num_pages_for_creation().
static int fileio_get_primitive_way_max (const char * path, long int * filename_max, long int * pathname_max) static
Definition at line 5227 of file file_io.c.
References error(), fileio_check_file_exist(), fileio_check_file_is_same(), fileio_close(), FILEIO_DISK_FORMAT_MODE, FILEIO_DISK_PROTECTION_MODE, fileio_open(), i, NULL, NULL_VOLDES, strlen, strncpy_bufsize, and success().
Referenced by fileio_get_max_name().
int fileio_get_volume_descriptor (VOLID vol_id)
Definition at line 6488 of file file_io.c.
References FILEIO_CHECK_AND_INITIALIZE_VOLUME_HEADER_CACHE, fileio_find_system_volume(), fileio_is_system_volume_id_equal(), FILEIO_VOLINFO_INCREMENT, i, LOG_MAX_DBVOLID, fileio_volinfo_header::max_perm_vols, fileio_volinfo_header::max_temp_vols, fileio_volinfo_header::next_temp_volid, NULL, NULL_VOLDES, NULL_VOLID, fileio_volinfo_header::num_volinfo_array, pthread_mutex_lock, pthread_mutex_unlock, rv, fileio_sys_volinfo::vdes, fileio_volinfo::vdes, fileio_apply_function_arg::vol_id, and fileio_volinfo_header::volinfo.
Referenced by boot_dbparm_save_volume(), disk_is_page_sector_reserved_with_debug_crash(), dwb_check_data_page_is_sane(), dwb_write_block(), fileio_backup_volume(), fileio_expand_to(), fileio_find_next_perm_volume(), fileio_find_previous_perm_volume(), fileio_find_previous_temp_volume(), fileio_is_temp_volume(), fileio_rename(), log_get_num_pages_for_creation(), log_recreate(), logpb_backup_for_volume(), logpb_checkpoint(), logpb_copy_volume(), logpb_delete(), logpb_rename_all_volumes_files(), pgbuf_bcb_flush_with_wal(), pgbuf_check_bcb_page_vpid(), pgbuf_claim_bcb_for_fix(), pgbuf_copy_from_area(), and pgbuf_copy_to_area().
static VOLID fileio_get_volume_id (int vdes) static
Definition at line 6267 of file file_io.c.
References FILEIO_CHECK_AND_INITIALIZE_VOLUME_HEADER_CACHE, fileio_find_system_volume(), fileio_is_system_volume_descriptor_equal(), fileio_is_volume_descriptor_equal(), fileio_traverse_permanent_volume(), fileio_traverse_temporary_volume(), NULL, NULL_VOLID, pthread_mutex_lock, pthread_mutex_unlock, rv, fileio_apply_function_arg::vdes, fileio_sys_volinfo::volid, and fileio_volinfo::volid.
Referenced by fileio_get_volume_label_by_fd(), and fileio_synchronize_all().
char* fileio_get_volume_label (VOLID vol_id, bool is_peek)
Definition at line 6182 of file file_io.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), FILEIO_CHECK_AND_INITIALIZE_VOLUME_HEADER_CACHE, fileio_find_system_volume(), fileio_is_system_volume_id_equal(), FILEIO_VOLINFO_INCREMENT, i, LOG_MAX_DBVOLID, fileio_volinfo_header::max_perm_vols, fileio_volinfo_header::max_temp_vols, fileio_volinfo_header::next_temp_volid, NULL, NULL_VOLID, fileio_volinfo_header::num_volinfo_array, pthread_mutex_lock, pthread_mutex_unlock, rv, strdup(), strlen, fileio_sys_volinfo::vlabel, fileio_volinfo::vlabel, fileio_apply_function_arg::vol_id, and fileio_volinfo_header::volinfo.
Referenced by boot_check_permanent_volumes(), boot_remove_temp_volume(), disk_check_volume(), fileio_expand_to(), fileio_get_volume_label_by_fd(), fileio_synchronize_all(), heap_create_internal(), heap_header_next_scan(), log_execute_run_postpone(), log_recreate(), log_rollback_record(), log_rv_undo_record(), log_unformat_ahead_volumes(), logpb_backup(), logpb_backup_for_volume(), logpb_checkpoint(), logpb_copy_volume(), logpb_delete(), logpb_next_where_path(), logpb_rename_all_volumes_files(), pgbuf_fix_debug(), pgbuf_flush_checkpoint(), pgbuf_get_volume_label(), pgbuf_is_valid_page(), pgbuf_is_valid_page_ptr(), pgbuf_set_lsa(), pgbuf_unfix_debug(), pgbuf_unlatch_bcb_upon_unfix(), pgbuf_unlatch_thrd_holder(), spage_compact(), and spage_verify_header().
char* fileio_get_volume_label_by_fd (int vol_fd, bool is_peek)
Definition at line 6254 of file file_io.c.
References fileio_get_volume_id(), and fileio_get_volume_label().
Referenced by fileio_close(), fileio_dismount(), fileio_dismount_without_fsync(), fileio_expand_to(), fileio_read(), fileio_read_pages(), fileio_synchronize_all(), fileio_write(), fileio_write_backup_header(), fileio_write_pages(), logpb_fetch_from_archive(), pwrite_with_injected_fault(), tde_add_mk(), and tde_find_first_mk().
int fileio_get_volume_max_suffix (void)
Definition at line 5604 of file file_io.c.
References FILEIO_MAX_SUFFIX_LENGTH.
Referenced by logpb_verify_length().
const char* fileio_get_zip_level_string (FILEIO_ZIP_LEVEL zip_level)
Definition at line 10774 of file file_io.c.
References FILEIO_ZIP_1_LEVEL, and FILEIO_ZIP_NONE_LEVEL.
Referenced by fileio_compress_backup_node(), fileio_decompress_restore_volume(), fileio_list_restore(), fileio_write_backup_node(), logpb_backup(), or_put_varchar_internal(), pr_data_compress_string(), pr_get_compression_length(), and pr_get_size_and_write_string_to_buffer().
const char* fileio_get_zip_method_string (FILEIO_ZIP_METHOD zip_method)
Definition at line 10747 of file file_io.c.
References FILEIO_ZIP_LZ4_METHOD, FILEIO_ZIP_LZO1X_METHOD, FILEIO_ZIP_NONE_METHOD, and FILEIO_ZIP_ZLIB_METHOD.
Referenced by fileio_compress_backup_node(), fileio_decompress_restore_volume(), fileio_list_restore(), fileio_write_backup_node(), logpb_backup(), or_put_varchar_internal(), pr_data_compress_string(), pr_get_compression_length(), and pr_get_size_and_write_string_to_buffer().
static int fileio_increase_flushed_page_count (int npages) static
Definition at line 590 of file file_io.c.
References fileio_Flushed_page_count, fileio_Flushed_page_counter_mutex, pthread_mutex_lock, and pthread_mutex_unlock.
Referenced by fileio_compensate_flush().
FILEIO_BACKUP_SESSION* fileio_initialize_backup (const char * db_full_name_p, const char * backup_destination_p, FILEIO_BACKUP_SESSION * session_p, FILEIO_BACKUP_LEVEL level, const char * verbose_file_path, int num_threads, int sleep_msecs)
Definition at line 6729 of file file_io.c.
References fileio_backup_buffer::alltotalio, fileio_backup_db_buffer::area, ARG_FILE_LINE, fileio_backup_header::bk_hdr_version, io_backup_session::bkup, fileio_backup_header::bkup_iosize, fileio_backup_buffer::bkuphdr, fileio_backup_buffer::buffer, fileio_backup_buffer::count, fileio_backup_buffer::current_path, DB_INT32_MAX, fileio_backup_header::db_next_bkvolname, fileio_backup_header::db_prec_bkvolname, io_backup_session::dbfile, fileio_backup_buffer::dtype, fileio_backup_header::end_time, ER_ERROR_SEVERITY, ER_IO_CANNOT_OPEN_VERBOSE_FILE, ER_IO_MOUNT_FAIL, er_log_debug, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), er_set_with_oserror(), error(), FILEIO_BACKUP_CURRENT_HEADER_VERSION, FILEIO_BACKUP_FILE_HEADER_PAGE_SIZE, FILEIO_BACKUP_FULL_LEVEL, FILEIO_BACKUP_HEADER_IO_SIZE, FILEIO_BACKUP_PAGE_OVERHEAD, FILEIO_BACKUP_VOL_DEVICE, FILEIO_BACKUP_VOL_DIRECTORY, FILEIO_BACKUP_VOL_UNKNOWN, FILEIO_BACKUP_WRITE, fileio_close(), FILEIO_DISK_FORMAT_MODE, FILEIO_DISK_PROTECTION_MODE, FILEIO_FULL_LEVEL_EXP, fileio_get_base_file_name(), fileio_get_directory_path(), FILEIO_INITIAL_BACKUP_UNITS, fileio_initialize_backup_thread(), fileio_make_backup_name(), fileio_open(), FILEIO_SET_BACKUP_PAGE_ID, FILEIO_ZIP_NONE_LEVEL, FILEIO_ZIP_NONE_METHOD, free_and_init, IO_PAGESIZE, fileio_backup_buffer::iosize, fileio_backup_header::level, fileio_backup_db_buffer::level, fileio_backup_db_buffer::lsa, LSA_SET_NULL(), fileio_backup_buffer::name, fileio_backup_db_buffer::nbytes, NO_ERROR, NULL, NULL_PAGEID, NULL_VOLDES, NULL_VOLID, prm_get_bigint_value(), prm_get_integer_value(), PRM_ID_IO_BACKUP_MAX_VOLUME_SIZE, PRM_ID_IO_BACKUP_NBUFFERS, fileio_backup_buffer::ptr, io_backup_session::sleep_msecs, fileio_backup_header::start_time, strncpy_bufsize, io_backup_session::type, fileio_backup_header::unit_num, fileio_backup_buffer::vdes, fileio_backup_db_buffer::vdes, io_backup_session::verbose_fp, fileio_backup_buffer::vlabel, fileio_backup_db_buffer::vlabel, fileio_backup_db_buffer::volid, fileio_backup_buffer::voltotalio, fileio_backup_header::zip_level, and fileio_backup_header::zip_method.
Referenced by fileio_initialize_restore(), and logpb_backup().
static int fileio_initialize_backup_info (int which_bkvinf) static
Definition at line 11164 of file file_io.c.
References envvar_get(), fileio_bkvinf_queues::free, NO_ERROR, and NULL.
Referenced by fileio_add_volume_to_backup_info(), and fileio_read_backup_info_entries().
static int fileio_initialize_backup_thread (FILEIO_BACKUP_SESSION * session_p, int num_threads) static
Definition at line 6653 of file file_io.c.
References ARG_FILE_LINE, ER_CSS_PTHREAD_COND_INIT, ER_CSS_PTHREAD_MUTEX_INIT, ER_ERROR_SEVERITY, er_set(), FILEIO_BACKUP_NUM_THREADS_AUTO, fileio_queue::free_list, fileio_queue::head, fileio_thread_info::initialized, fileio_thread_info::io_queue, NO_ERROR, NULL, NUM_NORMAL_TRANS, fileio_thread_info::num_threads, prm_get_integer_value(), PRM_ID_CSS_MAX_CLIENTS, pthread_mutex_init, io_backup_session::read_thread_info, rv, fileio_queue::size, and fileio_queue::tail.
Referenced by fileio_initialize_backup().
void* fileio_initialize_pages (THREAD_ENTRY * thread_p, int vol_fd, FILEIO_PAGE * io_page_p, DKNPAGES start_pageid, DKNPAGES npages, size_t page_size, int kbytes_to_be_written_per_sec)
Definition at line 1864 of file file_io.c.
References dwb_is_created(), FILEIO_CHECK_FOR_INTERRUPT_INTERVAL, fileio_write_or_add_to_dwb(), IO_PAGESIZE, logtb_get_check_interrupt(), NULL, ONE_K, pgbuf_is_log_check_for_interrupts(), thread_sleep(), tsc_elapsed_time_usec(), and tsc_getticks().
Referenced by fileio_expand_to(), and fileio_format().
void fileio_initialize_res (THREAD_ENTRY * thread_p, FILEIO_PAGE * io_page, PGLENGTH page_size)
Definition at line 11577 of file file_io.c.
References fileio_init_lsa_of_page(), fileio_page_reserved::p_reserve_1, fileio_page_reserved::p_reserve_2, fileio_page_reserved::pageid, fileio_page_reserved::pflag, fileio_page::prv, fileio_page_reserved::ptype, fileio_page_reserved::tde_nonce, and fileio_page_reserved::volid.
Referenced by dwb_add_page(), dwb_check_data_page_is_sane(), dwb_create_blocks(), dwb_flush_block(), dwb_flush_force(), dwb_set_slot_data(), dwb_slots_hash_insert(), fileio_expand_to(), fileio_fill_hole_during_restore(), fileio_format(), fileio_is_formatted_page(), and fileio_synchronize_all().
static FILEIO_BACKUP_SESSION * fileio_initialize_restore (THREAD_ENTRY * thread_p, const char * db_fullname, char * backup_src, FILEIO_BACKUP_SESSION * session, FILEIO_BACKUP_LEVEL level, const char * restore_verbose_file_path, bool newvolpath) static
Definition at line 8944 of file file_io.c.
References ARG_FILE_LINE, io_backup_session::bkup, ER_ERROR_SEVERITY, ER_IO_MOUNT_FAIL, er_msg(), er_set_with_oserror(), FILEIO_BACKUP_READ, fileio_find_restore_volume(), FILEIO_INITIAL_BACKUP_UNITS, fileio_initialize_backup(), fileio_is_volume_exist(), FILEIO_RELOCATION_QUIT, fileio_backup_buffer::loc_db_fullname, MSGCAT_FILEIO_RESTORE_FIND_REASON, NULL, strncpy_bufsize, and io_backup_session::type.
Referenced by fileio_start_restore().
static int fileio_initialize_volume_info_cache (void) static
Definition at line 922 of file file_io.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), FILEIO_VOLINFO_INCREMENT, free_and_init, i, NULL, fileio_volinfo_header::num_volinfo_array, pthread_mutex_destroy, pthread_mutex_lock, pthread_mutex_unlock, rv, VOLID_MAX, and fileio_volinfo_header::volinfo.
bool fileio_is_formatted_page (THREAD_ENTRY * thread_p, const char * io_page)
Definition at line 11841 of file file_io.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), fileio_initialize_res(), free_and_init, IO_PAGESIZE, and NULL.
bool fileio_is_permanent_volume_descriptor (THREAD_ENTRY * thread_p, int vol_fd)
Definition at line 6387 of file file_io.c.
References FILEIO_CHECK_AND_INITIALIZE_VOLUME_HEADER_CACHE, fileio_is_volume_descriptor_equal(), fileio_traverse_permanent_volume(), NULL_VOLDES, and fileio_apply_function_arg::vdes.
Referenced by fileio_synchronize(), and pwrite_with_injected_fault().
static bool fileio_is_system_volume_descriptor_equal (THREAD_ENTRY * thread_p, FILEIO_SYSTEM_VOLUME_INFO * sys_vol_info_p, APPLY_ARG * arg) static
Definition at line 3571 of file file_io.c.
References fileio_sys_volinfo::vdes, and fileio_apply_function_arg::vdes.
Referenced by fileio_get_lockf_type(), fileio_get_volume_id(), and pwrite_with_injected_fault().
static bool fileio_is_system_volume_id_equal (THREAD_ENTRY * thread_p, FILEIO_SYSTEM_VOLUME_INFO * sys_vol_info_p, APPLY_ARG * arg) static
Definition at line 3578 of file file_io.c.
References fileio_apply_function_arg::vol_id, and fileio_sys_volinfo::volid.
Referenced by fileio_get_volume_descriptor(), and fileio_get_volume_label().
static bool fileio_is_system_volume_label_equal (THREAD_ENTRY * thread_p, FILEIO_SYSTEM_VOLUME_INFO * sys_vol_info_p, APPLY_ARG * arg) static
Definition at line 3584 of file file_io.c.
References util_compare_filepath(), fileio_sys_volinfo::vlabel, and fileio_apply_function_arg::vol_label.
Referenced by fileio_find_volume_descriptor_with_label(), and fileio_find_volume_id_with_label().
bool fileio_is_temp_volume (THREAD_ENTRY * thread_p, VOLID volid)
Definition at line 6358 of file file_io.c.
References assert, FILEIO_CHECK_AND_INITIALIZE_VOLUME_HEADER_CACHE, fileio_get_volume_descriptor(), fileio_is_volume_id_equal(), fileio_traverse_temporary_volume(), NULL_VOLDES, NULL_VOLID, fileio_apply_function_arg::vol_id, and fileio_backup_file_header::volid.
static bool fileio_is_terminated_process (int pid) static
Definition at line 1141 of file file_io.c.
References FALSE, and NULL.
Referenced by fileio_lock().
static bool fileio_is_volume_descriptor_equal (THREAD_ENTRY * thread_p, FILEIO_VOLUME_INFO * vol_info_p, APPLY_ARG * arg) static
Definition at line 3514 of file file_io.c.
References NULL_VOLDES, fileio_volinfo::vdes, and fileio_apply_function_arg::vdes.
Referenced by fileio_decache(), fileio_get_lockf_type(), fileio_get_volume_id(), fileio_is_permanent_volume_descriptor(), fileio_write_or_add_to_dwb(), and pwrite_with_injected_fault().
bool fileio_is_volume_exist (const char * vol_label_p)
Definition at line 5094 of file file_io.c.
References fileio_close(), fileio_find_volume_descriptor_with_label(), fileio_open(), and NULL_VOLDES.
Referenced by alterdbhost(), boot_find_rest_temp_volumes(), boot_remove_all_volumes(), boot_remove_unknown_temp_volumes(), disk_add_volume(), dwb_load_and_recover_pages(), fileio_format(), fileio_initialize_restore(), fileio_lock(), fileio_read_restore(), fileio_restore_volume(), fileio_symlink(), la_log_page_check(), log_recovery_notpartof_archives(), log_recovery_notpartof_volumes(), logpb_backup(), logpb_delete(), logpb_exist_log(), logpb_fetch_from_archive(), logpb_fetch_header_from_active_log(), logpb_find_oldest_available_arv_num(), logpb_find_volume_info_exist(), logpb_is_log_active_from_backup_useful(), logpb_peek_header_of_active_log_from_backup(), logpb_remove_all_in_log_path(), logpb_rename_all_volumes_files(), logpb_restore(), tde_copy_keys_file(), and tde_create_keys_file().
bool fileio_is_volume_exist_and_file (const char * vol_label_p)
Definition at line 5132 of file file_io.c.
References fileio_find_volume_descriptor_with_label(), and NULL_VOLDES.
Referenced by fileio_abort_backup(), fileio_remove_all_backup(), and logpb_backup().
static bool fileio_is_volume_id_equal (THREAD_ENTRY * thread_p, FILEIO_VOLUME_INFO * vol_info_p, APPLY_ARG * arg) static
Definition at line 3524 of file file_io.c.
References NULL_VOLID, fileio_apply_function_arg::vol_id, and fileio_volinfo::volid.
Referenced by fileio_is_temp_volume().
static bool fileio_is_volume_id_gt (THREAD_ENTRY * thread_p, FILEIO_VOLUME_INFO * vol_info_p, APPLY_ARG * arg) static
Definition at line 3534 of file file_io.c.
References NULL_VOLID, fileio_apply_function_arg::vol_id, and fileio_volinfo::volid.
Referenced by fileio_find_next_perm_volume(), and fileio_find_previous_temp_volume().
static bool fileio_is_volume_id_lt (THREAD_ENTRY * thread_p, FILEIO_VOLUME_INFO * vol_info_p, APPLY_ARG * arg) static
Definition at line 3544 of file file_io.c.
References NULL_VOLID, fileio_apply_function_arg::vol_id, and fileio_volinfo::volid.
Referenced by fileio_find_previous_perm_volume().
static bool fileio_is_volume_label_equal (THREAD_ENTRY * thread_p, FILEIO_VOLUME_INFO * vol_info_p, APPLY_ARG * arg) static
Definition at line 6307 of file file_io.c.
References util_compare_filepath(), fileio_volinfo::vlabel, and fileio_apply_function_arg::vol_label.
Referenced by fileio_find_volume_descriptor_with_label(), and fileio_find_volume_id_with_label().
int fileio_list_restore (THREAD_ENTRY * thread_p, const char * db_full_name_p, char * backup_source_p, FILEIO_BACKUP_LEVEL level, bool is_new_vol_path)
Definition at line 9703 of file file_io.c.
References fileio_backup_db_buffer::area, ARG_FILE_LINE, fileio_backup_record_info::at_time, fileio_backup_header::bkpagesize, io_backup_session::bkup, fileio_backup_buffer::bkuphdr, CEIL_PTVDIV, fileio_backup_header::chkpt_lsa, CTIME_MAX, fileio_backup_header::db_compatibility, fileio_backup_header::db_creation, fileio_backup_header::db_fullname, fileio_backup_header::db_iopagesize, fileio_backup_header::db_next_bkvolname, fileio_backup_header::db_prec_bkvolname, fileio_backup_header::db_release, io_backup_session::dbfile, er_errid(), ER_ERROR_SEVERITY, ER_FAILED, ER_FATAL_ERROR_SEVERITY, ER_GENERIC_ERROR, ER_IO_BKUP_DATABASE_VOLUME_OR_FILE_EXPECTED, ER_IO_NOT_A_BACKUP, ER_IO_RESTORE_READ_ERROR, ER_LOG_CANNOT_ACCESS_BACKUP, er_set(), error(), fileio_abort_restore(), FILEIO_BACKUP_END_PAGE_ID, FILEIO_BACKUP_FILE_HEADER_PAGE_SIZE, FILEIO_BACKUP_FILE_START_PAGE_ID, FILEIO_BACKUP_FULL_LEVEL, FILEIO_BACKUP_START_PAGE_ID, FILEIO_BACKUP_UNDEFINED_LEVEL, FILEIO_BACKUP_VOL_CONT_PAGE_ID, fileio_finish_restore(), fileio_get_backup_level_string(), FILEIO_GET_BACKUP_PAGE_ID, fileio_get_zip_level_string(), fileio_get_zip_method_string(), FILEIO_INITIAL_BACKUP_UNITS, fileio_read_restore(), fileio_skip_restore_volume(), fileio_start_restore(), i, IO_PAGESIZE, fileio_backup_page::iopage, fileio_backup_header::iopageid, fileio_backup_header::level, fileio_backup_record_info::lsa, MSGCAT_CATALOG_CUBRID, MSGCAT_FILEIO_BKUP_FILE, MSGCAT_FILEIO_BKUP_HDR, MSGCAT_FILEIO_BKUP_HDR_BKUP_PAGESIZE, MSGCAT_FILEIO_BKUP_HDR_DBINFO, MSGCAT_FILEIO_BKUP_HDR_INC_ACTIVELOG, MSGCAT_FILEIO_BKUP_HDR_LEVEL, MSGCAT_FILEIO_BKUP_HDR_LX_LSA, MSGCAT_FILEIO_BKUP_HDR_RELEASES, MSGCAT_FILEIO_BKUP_HDR_TIME, MSGCAT_FILEIO_BKUP_HDR_ZIP_INFO, MSGCAT_FILEIO_BKUP_NEXT_BKVOL, MSGCAT_FILEIO_BKUP_PREV_BKVOL, msgcat_message(), MSGCAT_SET_IO, fileio_backup_file_header::nbytes, fileio_backup_db_buffer::nbytes, NO_ERROR, NULL, log_lsa::offset, log_lsa::pageid, fileio_backup_header::previnfo, fileio_backup_header::skip_activelog, fileio_backup_header::start_lsa, fileio_backup_header::start_time, strlen, fileio_backup_header::unit_num, fileio_backup_buffer::vlabel, fileio_backup_file_header::vlabel, fileio_backup_db_buffer::vlabel, fileio_backup_file_header::volid, fileio_backup_db_buffer::volid, fileio_backup_header::zip_level, and fileio_backup_header::zip_method.
Referenced by print_backup_info().
static FILEIO_LOCKF_TYPE fileio_lock (const char * db_fullname, const char * vlabel, int vdes, bool dowait) static
Definition at line 1179 of file file_io.c.
References ARG_FILE_LINE, CTIME_MAX, CUB_MAXHOSTNAMELEN, ER_ERROR_SEVERITY, ER_IO_MOUNT_FAIL, ER_IO_MOUNT_LOCKED, er_log_debug, er_set(), er_set_with_oserror(), fileio_ctime(), fileio_is_terminated_process(), fileio_is_volume_exist(), fileio_lock_file_write, FILEIO_LOCKF, fileio_make_volume_lock_name(), FILEIO_MAX_WAIT_DBTXT, FILEIO_NOT_LOCKF, fileio_unlock(), FILEIO_USER_NAME_SIZE, GETHOSTNAME, GETPID, getuserid(), host, NULL, pid, prm_get_bool_value(), and PRM_ID_IO_LOCKF_ENABLE.
Referenced by fileio_create(), and fileio_mount().
FILEIO_LOCKF_TYPE fileio_lock_la_dbname (int * lockf_vdes, char * db_name, char * log_path)
Definition at line 1545 of file file_io.c.
References ARG_FILE_LINE, assert, assert_release, cub_dirname_r(), DB_MAX_IDENTIFIER_LENGTH, envvar_vardir_file(), ER_BO_DIRECTORY_DOESNOT_EXIST, ER_ERROR_SEVERITY, ER_IO_MOUNT_FAIL, ER_IO_MOUNT_LOCKED, er_log_debug, er_set(), er_set_with_oserror(), error(), fileio_close(), fileio_lock_file_write, FILEIO_LOCKF, FILEIO_NOT_LOCKF, fileio_open(), fileio_release_lock(), NO_ERROR, NULL, NULL_VOLDES, and pid.
Referenced by la_lock_dbname().
FILEIO_LOCKF_TYPE fileio_lock_la_log_path (const char * db_full_name_p, const char * lock_path_p, int vol_fd, int * last_deleted_arv_num)
Definition at line 1392 of file file_io.c.
References ARG_FILE_LINE, CUB_MAXHOSTNAMELEN, ER_ERROR_SEVERITY, ER_IO_MOUNT_FAIL, ER_IO_MOUNT_LOCKED, er_log_debug, er_set(), er_set_with_oserror(), fileio_ctime(), fileio_lock_file_write, FILEIO_LOCKF, FILEIO_NOT_LOCKF, FILEIO_USER_NAME_SIZE, GETHOSTNAME, GETPID, getuserid(), host, NULL, and pid.
Referenced by la_check_duplicated().
static int fileio_lock_region (int fd, int cmd, int type, off_t offset, int whence, off_t len) static
Definition at line 11530 of file file_io.c.
void fileio_make_backup_name (char * backup_name_p, const char * no_path_vol_name_p, const char * backup_path_p, FILEIO_BACKUP_LEVEL level, int unit_num)
Definition at line 5853 of file file_io.c.
References FILEIO_SUFFIX_BACKUP, and PATH_SEPARATOR.
Referenced by fileio_continue_restore(), fileio_get_backup_volume(), fileio_get_next_backup_volume(), fileio_initialize_backup(), logpb_backup(), and logpb_restore().
void fileio_make_backup_volume_info_name (char * backup_volinfo_name_p, const char * backup_info_path_p, const char * db_name_p)
Definition at line 5833 of file file_io.c.
References FILEIO_PATH_SEPARATOR, and FILEIO_SUFFIX_BACKUP_VOLINFO.
Referenced by fileio_get_backup_volume(), logpb_copy_database(), logpb_initialize_log_names(), logpb_rename_all_volumes_files(), and logpb_restore().
void fileio_make_dwb_name (char * dwb_name_p, const char * dwb_path_p, const char * db_name_p)
Definition at line 5881 of file file_io.c.
References FILEIO_PATH_SEPARATOR, and FILEIO_SUFFIX_DWB.
Referenced by dwb_create(), dwb_load_and_recover_pages(), and logpb_delete().
static int fileio_make_error_message (THREAD_ENTRY * thread_p, char * error_message_p) static
Definition at line 9291 of file file_io.c.
References ARG_FILE_LINE, asprintf(), ER_ERROR_SEVERITY, ER_FAILED, ER_GENERIC_ERROR, er_set(), FILEIO_PROMPT_DISPLAY_ONLY, fileio_request_user_response(), MSGCAT_CATALOG_CUBRID, MSGCAT_FILEIO_INCORRECT_BKVOLUME, msgcat_message(), MSGCAT_SET_IO, NO_ERROR, and NULL.
Referenced by fileio_continue_restore().
void fileio_make_keys_name (char * keys_name_p, const char * db_full_name_p)
Definition at line 5897 of file file_io.c.
References FILEIO_SUFFIX_KEYS.
Referenced by tde_make_keys_file_fullname().
void fileio_make_keys_name_given_path (char * keys_name_p, const char * keys_path_p, const char * db_name_p)
Definition at line 5914 of file file_io.c.
References FILEIO_PATH_SEPARATOR, and FILEIO_SUFFIX_KEYS.
Referenced by tde_make_keys_file_fullname().
void fileio_make_log_active_name (char * log_active_name_p, const char * log_path_p, const char * db_name_p)
Definition at line 5707 of file file_io.c.
References FILEIO_PATH_SEPARATOR, and FILEIO_SUFFIX_LOGACTIVE.
Referenced by la_find_log_pagesize(), la_log_page_check(), logpb_copy_database(), logpb_initialize_log_names(), and logpb_rename_all_volumes_files().
void fileio_make_log_archive_name (char * log_archive_name_p, const char * log_path_p, const char * db_name_p, int archive_number)
Definition at line 5758 of file file_io.c.
References FILEIO_PATH_SEPARATOR, and FILEIO_SUFFIX_LOGARCHIVE.
Referenced by la_find_archive_num(), la_find_last_deleted_arv_num(), la_get_range_of_archive(), la_log_fetch_from_archive(), la_remove_archive_logs(), log_recovery_notpartof_archives(), logpb_append_archives_removed_to_log_info(), logpb_archive_active_log(), logpb_checkpoint(), logpb_delete(), logpb_fatal_error_internal(), logpb_fetch_from_archive(), logpb_find_oldest_available_arv_num(), logpb_find_oldest_available_page_id(), logpb_is_log_active_from_backup_useful(), logpb_remove_all_in_log_path(), logpb_remove_archive_logs_internal(), and logpb_rename_all_volumes_files().
void fileio_make_log_archive_temp_name (char * log_archive_temp_name_p, const char * log_path_p, const char * db_name_p)
Definition at line 5793 of file file_io.c.
References FILEIO_PATH_SEPARATOR, and FILEIO_SUFFIX_TMP_LOGARCHIVE.
Referenced by logpb_initialize_log_names().
void fileio_make_log_info_name (char * log_info_name_p, const char * log_path_p, const char * db_name_p)
Definition at line 5815 of file file_io.c.
References FILEIO_PATH_SEPARATOR, and FILEIO_SUFFIX_LOGINFO.
Referenced by la_apply_log_file(), logpb_copy_database(), logpb_initialize_log_names(), and logpb_rename_all_volumes_files().
void fileio_make_removed_log_archive_name (char * log_archive_name_p, const char * log_path_p, const char * db_name_p)
Definition at line 5777 of file file_io.c.
References FILEIO_PATH_SEPARATOR, and FILEIO_SUFFIX_LOGARCHIVE.
Referenced by logpb_initialize_log_names().
void fileio_make_temp_log_files_from_backup (char * temp_log_name, VOLID to_volid, FILEIO_BACKUP_LEVEL level, const char * base_log_name)
Definition at line 5726 of file file_io.c.
References LOG_DBLOG_ACTIVE_VOLID, LOG_DBLOG_ARCHIVE_VOLID, and LOG_DBLOG_INFO_VOLID.
Referenced by logpb_restore().
void fileio_make_volume_ext_given_name (char * vol_ext_full_name_p, const char * ext_path_p, const char * ext_name_p)
Definition at line 5672 of file file_io.c.
References FILEIO_PATH_SEPARATOR.
Referenced by boot_get_new_volume_name_and_id().
void fileio_make_volume_ext_name (char * vol_ext_full_name_p, const char * ext_path_p, const char * ext_name_p, VOLID vol_id)
Definition at line 5654 of file file_io.c.
References FILEIO_PATH_SEPARATOR, and FILEIO_VOLEXT_PREFIX.
Referenced by boot_get_new_volume_name_and_id(), disk_add_volume(), log_recovery_notpartof_volumes(), and logpb_next_where_path().
void fileio_make_volume_info_name (char * vol_info_name_p, const char * db_full_name_p)
Definition at line 5636 of file file_io.c.
References FILEIO_VOLINFO_SUFFIX.
Referenced by boot_volume_info_log_path(), fix_all_volume_header(), get_active_log_vol_path(), logpb_add_volume(), logpb_backup(), logpb_copy_database(), logpb_create_volume_info(), logpb_delete(), logpb_initialize_log_names(), and logpb_scan_volume_info().
static void fileio_make_volume_lock_name (char * vol_lockname, const char * vol_fullname) static
Definition at line 5620 of file file_io.c.
References FILEIO_VOLLOCK_SUFFIX.
Referenced by fileio_lock(), and fileio_unlock().
void fileio_make_volume_temp_name (char * vol_tmp_full_name_p, const char * tmp_path_p, const char * tmp_name_p, VOLID vol_id)
Definition at line 5690 of file file_io.c.
References FILEIO_VOLTMP_PREFIX, and PATH_SEPARATOR.
Referenced by boot_find_rest_temp_volumes(), boot_get_new_volume_name_and_id(), and boot_make_temp_volume_fullname().
bool fileio_map_mounted (THREAD_ENTRY * thread_p, bool(*)(THREAD_ENTRY *thread_p, VOLID vol_id, void *args) fun, void * args)
Definition at line 3463 of file file_io.c.
References FILEIO_CHECK_AND_INITIALIZE_VOLUME_HEADER_CACHE, fileio_max_permanent_volumes(), fileio_min_temporary_volumes(), fileio_Vol_info_header, FILEIO_VOLINFO_INCREMENT, i, LOG_MAX_DBVOLID, fileio_volinfo_header::next_perm_volid, fileio_volinfo_header::next_temp_volid, NULL_VOLDES, fileio_volinfo_header::num_volinfo_array, fileio_volinfo::vdes, fileio_volinfo::volid, and fileio_volinfo_header::volinfo.
Referenced by disk_cache_load_all_volumes(), disk_dump_all(), log_initialize_internal(), log_recovery(), log_recovery_notpartof_volumes(), and xdisk_is_volume_exist().
static int fileio_max_permanent_volumes (int index, int num_permanent_volums) static
Definition at line 3189 of file file_io.c.
References FILEIO_VOLINFO_INCREMENT.
Referenced by fileio_map_mounted(), fileio_reverse_traverse_permanent_volume(), and fileio_traverse_permanent_volume().
static int fileio_min_temporary_volumes (int index, int num_temp_volums, int num_volinfo_array) static
Definition at line 3202 of file file_io.c.
References FILEIO_VOLINFO_INCREMENT.
Referenced by fileio_map_mounted(), fileio_reverse_traverse_temporary_volume(), and fileio_traverse_temporary_volume().
int fileio_mount (THREAD_ENTRY * thread_p, const char * db_full_name_p, const char * vol_label_p, VOLID vol_id, int lock_wait, bool is_do_sync)
Definition at line 2957 of file file_io.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_IO_MOUNT_FAIL, ER_IO_MOUNT_LOCKED, er_set_with_oserror(), fileio_cache(), FILEIO_CHECK_AND_INITIALIZE_VOLUME_HEADER_CACHE, fileio_close(), fileio_dismount(), fileio_find_volume_descriptor_with_label(), fileio_lock(), FILEIO_LOCKF, FILEIO_NOT_LOCKF, fileio_open(), fileio_set_permission(), LOG_DBFIRST_VOLID, NULL_VOLDES, prm_get_bool_value(), prm_get_integer_value(), PRM_ID_DATA_FILE_ADVISE, and PRM_ID_DBFILES_PROTECT.
Referenced by alterdbhost(), boot_mount(), boot_reset_mk_after_restart_from_backup(), boot_restart_server(), dwb_load_and_recover_pages(), fileio_format(), fileio_restore_volume(), log_initialize_internal(), log_recovery_notpartof_volumes(), logpb_archive_active_log(), logpb_backup(), logpb_copy_database(), logpb_delete(), logpb_fetch_from_archive(), logpb_fetch_header_from_active_log(), logpb_find_oldest_available_page_id(), logpb_remove_all_in_log_path(), logpb_rename_all_volumes_files(), logpb_restore(), tde(), tde_cipher_initialize(), tde_copy_keys_file(), tde_initialize(), xboot_copy(), xboot_delete(), xboot_emergency_patch(), xboot_initialize_server(), and xboot_soft_rename().
int fileio_open (const char * vol_label_p, int flags, int mode)
Definition at line 1957 of file file_io.c.
References fileio_get_lock(), MAX_NTRANS, NULL_VOLDES, prm_get_bool_value(), and PRM_ID_DBFILES_PROTECT.
Referenced by boot_reset_mk_after_restart_from_backup(), disk_can_overwrite_data_volume(), fileio_backup_volume(), fileio_check_file_exist(), fileio_continue_restore(), fileio_create(), fileio_create_backup_volume(), fileio_get_number_of_partition_free_pages(), fileio_get_number_of_partition_free_sectors(), fileio_get_primitive_way_max(), fileio_initialize_backup(), fileio_is_volume_exist(), fileio_lock_la_dbname(), fileio_mount(), fileio_write_backup_end_time_to_header(), la_check_duplicated(), la_find_last_deleted_arv_num(), la_find_log_pagesize(), la_get_range_of_archive(), la_log_fetch_from_archive(), log_active_log_header_start_scan(), log_archive_log_header_start_scan(), logpb_peek_header_of_active_log_from_backup(), tde_create_keys_file(), and xtde_change_mk_without_flock().
static ssize_t fileio_os_read (THREAD_ENTRY * thread_p, int vol_fd, void * io_page_p, size_t count, off_t offset) static
Definition at line 3885 of file file_io.c.
References ARG_FILE_LINE, ER_CSS_PTHREAD_MUTEX_LOCK, ER_CSS_PTHREAD_MUTEX_UNLOCK, ER_ERROR_SEVERITY, ER_FAILED, er_set_with_oserror(), fileio_backup_file_header::nbytes, NULL, pthread_mutex_lock, pthread_mutex_unlock, and rv.
Referenced by fileio_read(), and fileio_read_pages().
static ssize_t fileio_os_write (THREAD_ENTRY * thread_p, int vol_fd, void * io_page_p, size_t count, off_t offset) static
Definition at line 4087 of file file_io.c.
References ARG_FILE_LINE, ER_CSS_PTHREAD_MUTEX_LOCK, ER_ERROR_SEVERITY, ER_FAILED, er_set_with_oserror(), fileio_backup_file_header::nbytes, NULL, pthread_mutex_lock, pthread_mutex_unlock, pwrite_with_injected_fault(), and rv.
Referenced by fileio_synchronize_all(), fileio_write(), and fileio_write_pages().
FILEIO_RESTORE_PAGE_BITMAP* fileio_page_bitmap_create (int vol_id, int total_pages)
Definition at line 11615 of file file_io.c.
References ARG_FILE_LINE, page_bitmap::bitmap, CEIL_PTVDIV, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, page_bitmap::next, NULL, page_bitmap::size, and page_bitmap::vol_id.
Referenced by logpb_restore().
static void fileio_page_bitmap_dump (FILE * out_fp, const FILEIO_RESTORE_PAGE_BITMAP * page_bitmap) static
Definition at line 11791 of file file_io.c.
References assert, page_bitmap::bitmap, i, NULL, page_bitmap::size, and page_bitmap::vol_id.
Referenced by fileio_restore_volume().
static bool fileio_page_bitmap_is_set (FILEIO_RESTORE_PAGE_BITMAP * page_bitmap, int page_id) static
Definition at line 11772 of file file_io.c.
References assert, page_bitmap::bitmap, NULL, and page_bitmap::size.
Referenced by fileio_write_restore().
void fileio_page_bitmap_list_add (FILEIO_RESTORE_PAGE_BITMAP_LIST * page_bitmap_list, FILEIO_RESTORE_PAGE_BITMAP * page_bitmap)
Definition at line 11684 of file file_io.c.
References assert, page_bitmap_list::head, page_bitmap::next, NULL, page_bitmap_list::tail, and page_bitmap::vol_id.
Referenced by logpb_restore().
void fileio_page_bitmap_list_destroy (FILEIO_RESTORE_PAGE_BITMAP_LIST * page_bitmap_list)
Definition at line 11726 of file file_io.c.
References assert, page_bitmap::bitmap, free_and_init, page_bitmap_list::head, page_bitmap::next, NULL, page_bitmap::size, page_bitmap_list::tail, and page_bitmap::vol_id.
Referenced by logpb_restore().
FILEIO_RESTORE_PAGE_BITMAP* fileio_page_bitmap_list_find (FILEIO_RESTORE_PAGE_BITMAP_LIST * page_bitmap_list, int vol_id)
Definition at line 11653 of file file_io.c.
References assert, page_bitmap_list::head, page_bitmap::next, NULL, page_bitmap_list::tail, and page_bitmap::vol_id.
Referenced by logpb_restore().
void fileio_page_bitmap_list_init (FILEIO_RESTORE_PAGE_BITMAP_LIST * page_bitmap_list)
Definition at line 11601 of file file_io.c.
References assert, page_bitmap_list::head, NULL, and page_bitmap_list::tail.
Referenced by logpb_restore().
static void fileio_page_bitmap_set (FILEIO_RESTORE_PAGE_BITMAP * page_bitmap, int page_id) static
Definition at line 11757 of file file_io.c.
References assert, page_bitmap::bitmap, NULL, and page_bitmap::size.
Referenced by fileio_write_restore().
int fileio_page_check_corruption (THREAD_ENTRY * thread_p, FILEIO_PAGE * io_page, bool * is_page_corrupted)
Definition at line 11831 of file file_io.c.
References assert, fileio_is_page_sane(), IO_PAGESIZE, NO_ERROR, and NULL.
Referenced by dwb_check_data_page_is_sane(), dwb_debug_check_dwb(), pgbuf_check_bcb_page_vpid(), and pwrite_with_injected_fault().
void fileio_page_hexa_dump (const char * src_data, int length)
Definition at line 3597 of file file_io.c.
References ARG_FILE_LINE, assert, er_log_debug, free_and_init, i, and NULL.
Referenced by log_recovery_analysis(), and pwrite_with_injected_fault().
void* fileio_read (THREAD_ENTRY * thread_p, int vol_fd, void * io_page_p, PAGEID page_id, size_t page_size)
Definition at line 3950 of file file_io.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_FATAL_ERROR_SEVERITY, ER_IO_READ, er_log_debug, ER_MNT_WAITING_THREAD, ER_NOTIFICATION_SEVERITY, ER_PB_BAD_PAGEID, er_set(), er_set_with_oserror(), FILEIO_GET_FILE_SIZE, fileio_get_volume_label_by_fd(), fileio_os_read(), MONITOR_WAITING_THREAD, fileio_backup_file_header::nbytes, NULL, PEEK, perfmon_inc_stat(), prm_get_integer_value(), PRM_ID_MNT_WAITING_THREAD, PSTAT_FILE_NUM_IOREADS, tsc_elapsed_time_usec(), and tsc_getticks().
Referenced by disk_can_overwrite_data_volume(), dwb_check_data_page_is_sane(), fileio_copy_volume(), fileio_reset_volume(), logpb_fetch_from_archive(), logpb_fetch_header_from_active_log(), logpb_find_oldest_available_page_id(), logpb_peek_header_of_active_log_from_backup(), logpb_read_page_from_file(), pgbuf_check_bcb_page_vpid(), and pgbuf_claim_bcb_for_fix().
static ssize_t fileio_read_backup (THREAD_ENTRY * thread_p, FILEIO_BACKUP_SESSION * session, int pageid) static
Definition at line 8723 of file file_io.c.
References fileio_backup_db_buffer::area, ARG_FILE_LINE, fileio_backup_header::bkpagesize, io_backup_session::bkup, fileio_backup_buffer::bkuphdr, io_backup_session::dbfile, ER_ERROR_SEVERITY, ER_IO_READ, er_set_with_oserror(), FILEIO_GET_BACKUP_PAGE_ID, FILEIO_GET_FILE_SIZE, FILEIO_SET_BACKUP_PAGE_ID, fileio_backup_page::iopage, LOG_CS_OWN_WRITE_MODE(), LOG_DBLOG_ACTIVE_VOLID, LOG_DBLOG_ARCHIVE_VOLID, fileio_backup_file_header::nbytes, ONE_M, prm_get_integer_value(), PRM_ID_IO_BACKUP_SLEEP_MSECS, io_backup_session::sleep_msecs, thread_sleep(), fileio_backup_db_buffer::vdes, fileio_backup_db_buffer::vlabel, fileio_backup_db_buffer::volid, fileio_backup_buffer::voltotalio, and while().
Referenced by fileio_backup_volume(), and fileio_write_backup_node().
static void fileio_read_backup_end_time_from_last_page (FILEIO_BACKUP_SESSION * session_p) static
Definition at line 7322 of file file_io.c.
References fileio_backup_db_buffer::area, io_backup_session::bkup, fileio_backup_buffer::bkuphdr, io_backup_session::dbfile, fileio_backup_header::end_time, and fileio_backup_page::iopageid.
Referenced by fileio_get_next_restore_file().
int fileio_read_backup_info_entries (FILE * fp, int which_bkvinf)
Definition at line 11065 of file file_io.c.
References ER_FAILED, fileio_add_volume_to_backup_info(), FILEIO_BACKUP_UNDEFINED_LEVEL, fileio_finalize_backup_info(), FILEIO_INITIAL_BACKUP_UNITS, fileio_initialize_backup_info(), MSGCAT_CATALOG_CUBRID, MSGCAT_FILEIO_BACKUP_VINF_ERROR, msgcat_message(), MSGCAT_SET_IO, NO_ERROR, and NULL.
Referenced by fileio_get_backup_volume(), logpb_backup(), logpb_delete(), and logpb_rename_all_volumes_files().
void* fileio_read_pages (THREAD_ENTRY * thread_p, int vol_fd, char * io_pages_p, PAGEID page_id, int num_pages, size_t page_size)
Definition at line 4227 of file file_io.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_IO_READ, er_log_debug, ER_MNT_WAITING_THREAD, ER_NOTIFICATION_SEVERITY, er_set(), er_set_with_oserror(), FILEIO_GET_FILE_SIZE, fileio_get_volume_label_by_fd(), fileio_os_read(), MONITOR_WAITING_THREAD, NULL, PEEK, perfmon_inc_stat(), prm_get_integer_value(), PRM_ID_MNT_WAITING_THREAD, PSTAT_FILE_NUM_IOREADS, tsc_elapsed_time_usec(), and tsc_getticks().
Referenced by dwb_load_and_recover_pages(), and logpb_read_page_from_active_log().
static int fileio_read_restore (THREAD_ENTRY * thread_p, FILEIO_BACKUP_SESSION * session, int toread_nbytes) static
Definition at line 8996 of file file_io.c.
References fileio_backup_buffer::alltotalio, fileio_backup_db_buffer::area, ARG_FILE_LINE, io_backup_session::bkup, fileio_backup_buffer::bkuphdr, fileio_backup_buffer::buffer, CEIL_PTVDIV, fileio_backup_buffer::count, fileio_backup_buffer::current_path, fileio_backup_header::db_creation, fileio_backup_header::db_fullname, io_backup_session::dbfile, fileio_backup_buffer::dtype, ER_ERROR_SEVERITY, ER_FAILED, ER_IO_READ, er_set_with_oserror(), fileio_add_volume_to_backup_info(), FILEIO_BACKUP_END_PAGE_ID, FILEIO_BACKUP_VOL_DEVICE, fileio_continue_restore(), fileio_dismount_without_fsync(), fileio_find_restore_volume(), FILEIO_FIRST_BACKUP_VOL_INFO, fileio_get_backup_info_volume_name(), FILEIO_GET_BACKUP_PAGE_ID, fileio_get_directory_path(), fileio_is_volume_exist(), FILEIO_RELOCATION_QUIT, FILEIO_SECOND_BACKUP_VOL_INFO, IO_PAGESIZE, fileio_backup_buffer::iosize, fileio_backup_header::level, MSGCAT_FILEIO_RESTORE_FIND_REASON, fileio_backup_buffer::name, fileio_backup_file_header::nbytes, NO_ERROR, NULL, NULL_VOLDES, fileio_backup_buffer::ptr, fileio_backup_header::start_time, strlen, fileio_backup_header::unit_num, fileio_backup_buffer::vdes, fileio_backup_buffer::vlabel, fileio_backup_buffer::voltotalio, and while().
Referenced by fileio_decompress_restore_volume(), fileio_get_next_restore_file(), and fileio_list_restore().
static int fileio_read_restore_header (FILEIO_BACKUP_SESSION * session) static
Definition at line 9191 of file file_io.c.
References ARG_FILE_LINE, fileio_backup_header::bk_hdr_version, fileio_backup_header::bkpagesize, io_backup_session::bkup, fileio_backup_buffer::bkuphdr, CEIL_PTVDIV, fileio_backup_header::db_iopagesize, ER_ERROR_SEVERITY, ER_FAILED, ER_IO_READ, er_set_with_oserror(), FILEIO_BACKUP_HEADER_IO_SIZE, FILEIO_BACKUP_NO_ZIP_HEADER_VERSION, FILEIO_ZIP_NONE_LEVEL, FILEIO_ZIP_NONE_METHOD, IO_PAGESIZE, fileio_backup_file_header::nbytes, NO_ERROR, fileio_backup_buffer::vdes, fileio_backup_buffer::vlabel, fileio_backup_buffer::voltotalio, fileio_backup_header::zip_level, and fileio_backup_header::zip_method.
Referenced by fileio_continue_restore().
static int fileio_release_lock (int fd) static
Definition at line 2058 of file file_io.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_IO_RELEASE_LOCK_FAIL, er_set_with_oserror(), error(), fileio_unlock_file, and NO_ERROR.
Referenced by fileio_close(), fileio_lock_la_dbname(), and fileio_unlock_la_dbname().
void fileio_remove_all_backup (THREAD_ENTRY * thread_p, int start_level)
Definition at line 7446 of file file_io.c.
References FILEIO_BACKUP_FULL_LEVEL, FILEIO_BACKUP_UNDEFINED_LEVEL, fileio_clear_backup_info_level(), FILEIO_FIRST_BACKUP_VOL_INFO, fileio_get_backup_info_volume_name(), FILEIO_INITIAL_BACKUP_UNITS, fileio_is_volume_exist_and_file(), fileio_unformat(), and NULL.
Referenced by fileio_abort_backup(), logpb_backup(), logpb_delete(), and logpb_rename_all_volumes_files().
const char* fileio_rename (VOLID vol_id, const char * old_label_p, const char * new_label_p)
Definition at line 5070 of file file_io.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_IO_RENAME_FAIL, er_log_debug, er_set_with_oserror(), fileio_get_volume_descriptor(), NO_ERROR, NULL, NULL_VOLDES, and os_rename_file().
Referenced by logpb_archive_active_log(), and logpb_rename_all_volumes_files().
int fileio_request_user_response (THREAD_ENTRY * thread_p, FILEIO_REMOTE_PROMPT_TYPE prompt_id, const char * prompt_p, char * response_p, const char * failure_prompt_p, int range_low, int range_high, const char * secondary_prompt_p, int reprompt_value)
Definition at line 11304 of file file_io.c.
References ARG_FILE_LINE, char_tolower(), db_on_server, ER_FAILED, ER_FATAL_ERROR_SEVERITY, ER_NET_DATA_TRUNCATED, er_set(), FILEIO_MAX_USER_RESPONSE_SIZE, FILEIO_PROMPT_BOOLEAN_TYPE, FILEIO_PROMPT_DISPLAY_ONLY, FILEIO_PROMPT_RANGE_TYPE, FILEIO_PROMPT_RANGE_WITH_SECONDARY_STRING_TYPE, FILEIO_PROMPT_STRING_TYPE, free_and_init, intl_mbs_casecmp(), intl_mbs_len(), NO_ERROR, NULL, OR_INT_SIZE, or_unpack_int(), or_unpack_string_nocopy(), parse_int(), rc, xio_send_user_prompt_to_client(), and xs_receive_data_from_client().
Referenced by fileio_find_restore_volume(), fileio_finish_backup(), fileio_get_next_backup_volume(), fileio_make_error_message(), logpb_backup(), and logpb_remote_ask_user_before_delete_volumes().
int fileio_reset_volume (THREAD_ENTRY * thread_p, int vol_fd, const char * vlabel, DKNPAGES npages, const LOG_LSA * reset_lsa_p)
Definition at line 2903 of file file_io.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), fileio_read(), fileio_set_page_lsa(), FILEIO_SYNC_ALSO_FLUSH_DWB, fileio_synchronize(), fileio_write_or_add_to_dwb(), free_and_init, IO_PAGESIZE, NO_ERROR, NULL, and success().
Referenced by disk_format(), and log_recreate().
int fileio_restore_volume (THREAD_ENTRY * thread_p, FILEIO_BACKUP_SESSION * session_p, char * to_vol_label_p, char * verbose_to_vol_label_p, char * prev_vol_label_p, FILEIO_RESTORE_PAGE_BITMAP * page_bitmap, bool is_remember_pages)
Definition at line 10235 of file file_io.c.
References fileio_backup_db_buffer::area, ARG_FILE_LINE, fileio_backup_header::bkpagesize, io_backup_session::bkup, fileio_backup_buffer::bkuphdr, CEIL_PTVDIV, fileio_backup_header::db_creation, io_backup_session::dbfile, DISK_FLUSH_AND_INVALIDATE, disk_set_creation(), disk_set_link(), DISK_VOLHEADER_PAGE, ER_ERROR_SEVERITY, ER_FAILED, ER_IO_RESTORE_PAGEID_OUTOF_BOUNDS, ER_IO_RESTORE_READ_ERROR, er_set(), error(), FILEIO_BACKUP_FILE_END_PAGE_ID, FILEIO_BACKUP_FULL_LEVEL, FILEIO_CHECK_RESTORE_PAGE_ID, fileio_decompress_restore_volume(), fileio_dismount(), fileio_fill_hole_during_restore(), fileio_find_previous_perm_volume(), fileio_format(), FILEIO_GET_BACKUP_PAGE_ID, fileio_get_base_file_name(), fileio_is_volume_exist(), fileio_mount(), fileio_page_bitmap_dump(), FILEIO_RESTORE_DBVOLS_IO_PAGE_SIZE, fileio_write_restore(), for(), i, IO_PAGESIZE, fileio_backup_page::iopage, fileio_backup_page::iopageid, fileio_backup_buffer::last_chkpt_lsa, fileio_backup_db_buffer::level, fileio_backup_buffer::loc_db_fullname, LOG_DBFIRST_VOLID, MSGCAT_CATALOG_CUBRID, MSGCAT_FILEIO_BKUP_FILE, msgcat_message(), MSGCAT_SET_IO, fileio_backup_file_header::nbytes, fileio_backup_db_buffer::nbytes, NO_ERROR, NULL, NULL_VOLDES, NULL_VOLID, fileio_backup_header::unit_num, fileio_backup_db_buffer::vdes, io_backup_session::verbose_fp, fileio_backup_db_buffer::vlabel, fileio_backup_file_header::volid, and fileio_backup_db_buffer::volid.
Referenced by logpb_restore().
static FILEIO_VOLUME_INFO * fileio_reverse_traverse_permanent_volume (THREAD_ENTRY * thread_p, VOLINFO_APPLY_FN apply_function, APPLY_ARG * arg) static
Definition at line 3263 of file file_io.c.
References fileio_max_permanent_volumes(), fileio_Vol_info_header, FILEIO_VOLINFO_INCREMENT, i, fileio_volinfo_header::next_perm_volid, NULL, and fileio_volinfo_header::volinfo.
Referenced by fileio_find_previous_perm_volume().
static FILEIO_VOLUME_INFO * fileio_reverse_traverse_temporary_volume (THREAD_ENTRY * thread_p, VOLINFO_APPLY_FN apply_function, APPLY_ARG * arg) static
Definition at line 3318 of file file_io.c.
References fileio_min_temporary_volumes(), fileio_Vol_info_header, FILEIO_VOLINFO_INCREMENT, for(), i, LOG_MAX_DBVOLID, fileio_volinfo_header::next_temp_volid, NULL, fileio_volinfo_header::num_volinfo_array, and fileio_volinfo_header::volinfo.
Referenced by fileio_find_previous_temp_volume().
int fileio_set_permission (const char * vol_label_p)
Definition at line 2002 of file file_io.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_IO_CANNOT_CHANGE_PERMISSION, ER_IO_CANNOT_GET_PERMISSION, er_set_with_oserror(), error(), mode, and NO_ERROR.
Referenced by fileio_mount().
int fileio_skip_restore_volume (THREAD_ENTRY * thread_p, FILEIO_BACKUP_SESSION * session_p)
Definition at line 10559 of file file_io.c.
References fileio_backup_db_buffer::area, ARG_FILE_LINE, fileio_backup_header::bkpagesize, io_backup_session::bkup, fileio_backup_buffer::bkuphdr, io_backup_session::dbfile, ER_ERROR_SEVERITY, ER_FAILED, ER_IO_RESTORE_READ_ERROR, er_set(), error(), FILEIO_BACKUP_FILE_END_PAGE_ID, FILEIO_CHECK_RESTORE_PAGE_ID, fileio_decompress_restore_volume(), FILEIO_GET_BACKUP_PAGE_ID, FILEIO_RESTORE_DBVOLS_IO_PAGE_SIZE, fileio_backup_file_header::nbytes, NO_ERROR, NULL, NULL_VOLDES, NULL_VOLID, fileio_backup_header::unit_num, fileio_backup_db_buffer::vdes, fileio_backup_db_buffer::vlabel, and fileio_backup_db_buffer::volid.
Referenced by fileio_list_restore(), and logpb_restore().
FILEIO_BACKUP_SESSION* fileio_start_backup (THREAD_ENTRY * thread_p, const char * db_full_name_p, INT64 * db_creation_time_p, FILEIO_BACKUP_LEVEL backup_level, LOG_LSA * backup_start_lsa_p, LOG_LSA * backup_checkpoint_lsa_p, FILEIO_BACKUP_RECORD_INFO * all_levels_info_p, FILEIO_BACKUP_SESSION * session_p, FILEIO_ZIP_METHOD zip_method, FILEIO_ZIP_LEVEL zip_level)
Definition at line 7155 of file file_io.c.
References fileio_backup_record_info::at_time, fileio_backup_header::bkpagesize, io_backup_session::bkup, fileio_backup_buffer::bkuphdr, fileio_backup_header::chkpt_lsa, CUBRID_MAGIC_DATABASE_BACKUP, CUBRID_MAGIC_MAX_LENGTH, fileio_backup_header::db_compatibility, fileio_backup_header::db_creation, fileio_backup_header::db_fullname, fileio_backup_header::db_iopagesize, fileio_backup_header::db_release, io_backup_session::dbfile, error(), fileio_abort_backup(), fileio_add_volume_to_backup_info(), FILEIO_BACKUP_FULL_LEVEL, FILEIO_BACKUP_MINIMUM_NUM_PAGES, FILEIO_BACKUP_MINIMUM_NUM_PAGES_FULL_LEVEL, FILEIO_BACKUP_START_PAGE_ID, FILEIO_BACKUP_UNDEFINED_LEVEL, fileio_create_backup_volume(), FILEIO_DBVOLS_IO_PAGE_SIZE, FILEIO_FIRST_BACKUP_VOL_INFO, FILEIO_FULL_LEVEL_EXP, FILEIO_INITIAL_BACKUP_UNITS, fileio_write_backup_header(), FILEIO_ZIP_LZ4_METHOD, i, IO_PAGESIZE, fileio_backup_header::iopageid, fileio_backup_header::level, fileio_backup_db_buffer::level, LOG_DBCOPY_VOLID, fileio_backup_record_info::lsa, fileio_backup_db_buffer::lsa, LSA_COPY(), LSA_SET_NULL(), fileio_backup_header::magic, fileio_backup_buffer::name, NO_ERROR, NULL, NULL_VOLDES, fileio_backup_header::previnfo, rel_disk_compatible(), rel_release_string(), fileio_backup_header::start_lsa, fileio_backup_header::start_time, strncpy_bufsize, fileio_backup_header::unit_num, fileio_backup_buffer::vdes, fileio_backup_buffer::vlabel, fileio_backup_header::zip_level, and fileio_backup_header::zip_method.
Referenced by logpb_backup().
FILEIO_BACKUP_SESSION* fileio_start_restore (THREAD_ENTRY * thread_p, const char * db_full_name_p, char * backup_source_p, INT64 match_db_creation_time, PGLENGTH * db_io_page_size_p, float * db_compatibility_p, FILEIO_BACKUP_SESSION * session_p, FILEIO_BACKUP_LEVEL level, bool is_authenticate, INT64 match_backup_creation_time, const char * restore_verbose_file_path, bool is_new_vol_path)
Definition at line 9264 of file file_io.c.
References io_backup_session::bkup, fileio_backup_buffer::bkuphdr, fileio_backup_header::db_compatibility, fileio_backup_header::db_iopagesize, fileio_continue_restore(), fileio_initialize_restore(), and NULL.
Referenced by fileio_list_restore(), and logpb_restore().
int fileio_symlink (const char * src_p, const char * dest_p, int overwrite)
Definition at line 11503 of file file_io.c.
References ARG_FILE_LINE, ER_BO_CANNOT_CREATE_LINK, ER_ERROR_SEVERITY, ER_FAILED, er_set(), fileio_is_volume_exist(), and NO_ERROR.
Referenced by logpb_next_where_path().
int fileio_synchronize (THREAD_ENTRY * thread_p, int vol_fd, const char * vlabel, FILEIO_SYNC_OPTION sync_dwb)
Definition at line 4441 of file file_io.c.
References ARG_FILE_LINE, dwb_flush_force(), ER_FATAL_ERROR_SEVERITY, ER_IO_SYNC, er_log_debug, ER_MNT_WAITING_THREAD, ER_NOTIFICATION_SEVERITY, er_set(), er_set_with_oserror(), fileio_is_permanent_volume_descriptor(), FILEIO_SYNC_ALSO_FLUSH_DWB, MONITOR_WAITING_THREAD, NO_ERROR, NULL_VOLDES, perfmon_inc_stat(), prm_get_integer_value(), PRM_ID_MNT_WAITING_THREAD, PRM_ID_SUPPRESS_FSYNC, PSTAT_FILE_NUM_IOSYNCHES, pthread_mutex_lock, pthread_mutex_unlock, tsc_elapsed_time_usec(), and tsc_getticks().
Referenced by boot_dbparm_save_volume(), disk_format(), dwb_file_sync_helper(), dwb_flush_block(), dwb_load_and_recover_pages(), fileio_copy_volume(), fileio_dismount(), fileio_dismount_all(), fileio_dismount_volume(), fileio_finish_backup(), fileio_reset_volume(), fileio_synchronize_sys_volume(), fileio_synchronize_volume(), logpb_archive_active_log(), logpb_backup_for_volume(), logpb_checkpoint(), logpb_copy_database(), logpb_copy_volume(), logpb_flush_all_append_pages(), logpb_rename_all_volumes_files(), logpb_write_toflush_pages_to_archive(), and pwrite_with_injected_fault().
int fileio_synchronize_all (THREAD_ENTRY * thread_p, bool is_include)
Definition at line 4618 of file file_io.c.
References ARG_FILE_LINE, DB_PAGESIZE, dwb_flush_force(), ER_CSS_PTHREAD_MUTEX_UNLOCK, er_errid(), ER_ERROR_SEVERITY, ER_FAILED, ER_IO_READ, ER_IO_SYNC, ER_IO_WRITE, ER_IO_WRITE_OUT_OF_SPACE, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), er_set_with_oserror(), er_stack_pop(), er_stack_push(), error(), fileio_compensate_flush(), FILEIO_GET_FILE_SIZE, fileio_get_volume_id(), fileio_get_volume_label(), fileio_get_volume_label_by_fd(), fileio_initialize_res(), fileio_os_write(), fileio_synchronize_sys_volume(), fileio_synchronize_volume(), fileio_traverse_permanent_volume(), fileio_traverse_system_volume(), free_and_init, IO_PAGESIZE, NO_ERROR, NULL, NULL_VOLID, fileio_page::page, PEEK, perfmon_inc_stat(), PSTAT_FILE_IOSYNC_ALL, PSTAT_FILE_NUM_IOREADS, PSTAT_FILE_NUM_IOWRITES, pthread_mutex_lock, pthread_mutex_unlock, rv, success(), and fileio_apply_function_arg::vol_id.
Referenced by boot_create_all_volumes(), dwb_create_internal(), fileio_compensate_flush(), fileio_finish_restore(), log_final(), log_recovery(), log_recreate(), log_rv_outside_noop_redo(), logpb_checkpoint(), logpb_fatal_error_internal(), and logpb_remove_archive_logs().
static int fileio_synchronize_bg_archive_volume (THREAD_ENTRY * thread_p) static
Definition at line 4531 of file file_io.c.
References fileio_synchronize_sys_volume(), fileio_traverse_system_volume(), LOG_DBLOG_BG_ARCHIVE_VOLID, NO_ERROR, and fileio_apply_function_arg::vol_id.
static bool fileio_synchronize_sys_volume (THREAD_ENTRY * thread_p, FILEIO_SYSTEM_VOLUME_INFO * vol_sys_info_p, APPLY_ARG * arg) static
Definition at line 4546 of file file_io.c.
References FILEIO_SYNC_ONLY, fileio_synchronize(), NULL_VOLDES, NULL_VOLID, fileio_sys_volinfo::vdes, fileio_sys_volinfo::vlabel, fileio_apply_function_arg::vol_id, and fileio_sys_volinfo::volid.
Referenced by fileio_synchronize_all(), and fileio_synchronize_bg_archive_volume().
static bool fileio_synchronize_volume (THREAD_ENTRY * thread_p, FILEIO_VOLUME_INFO * vol_info_p, APPLY_ARG * arg) static
Definition at line 4584 of file file_io.c.
References FILEIO_SYNC_ONLY, fileio_synchronize(), NULL_VOLDES, NULL_VOLID, fileio_volinfo::vdes, fileio_volinfo::vlabel, fileio_apply_function_arg::vol_id, and fileio_volinfo::volid.
Referenced by fileio_synchronize_all().
static FILEIO_VOLUME_INFO * fileio_traverse_permanent_volume (THREAD_ENTRY * thread_p, VOLINFO_APPLY_FN apply_function, APPLY_ARG * arg) static
Definition at line 3237 of file file_io.c.
References fileio_max_permanent_volumes(), fileio_Vol_info_header, FILEIO_VOLINFO_INCREMENT, i, fileio_volinfo_header::next_perm_volid, NULL, and fileio_volinfo_header::volinfo.
Referenced by fileio_decache(), fileio_dismount_all(), fileio_find_next_perm_volume(), fileio_find_volume_descriptor_with_label(), fileio_find_volume_id_with_label(), fileio_get_lockf_type(), fileio_get_volume_id(), fileio_is_permanent_volume_descriptor(), fileio_synchronize_all(), fileio_write_or_add_to_dwb(), and pwrite_with_injected_fault().
static FILEIO_SYSTEM_VOLUME_INFO * fileio_traverse_system_volume (THREAD_ENTRY * thread_p, SYS_VOLINFO_APPLY_FN apply_function, APPLY_ARG * arg) static
Definition at line 3215 of file file_io.c.
References fileio_sys_volinfo_header::anchor, fileio_sys_volinfo::next, NULL, NULL_VOLDES, pthread_mutex_lock, pthread_mutex_unlock, rv, and fileio_sys_volinfo::vdes.
Referenced by fileio_synchronize_all(), and fileio_synchronize_bg_archive_volume().
static FILEIO_VOLUME_INFO * fileio_traverse_temporary_volume (THREAD_ENTRY * thread_p, VOLINFO_APPLY_FN apply_function, APPLY_ARG * arg) static
Definition at line 3289 of file file_io.c.
References fileio_min_temporary_volumes(), fileio_Vol_info_header, FILEIO_VOLINFO_INCREMENT, i, LOG_MAX_DBVOLID, fileio_volinfo_header::next_temp_volid, NULL, fileio_volinfo_header::num_volinfo_array, and fileio_volinfo_header::volinfo.
Referenced by fileio_decache(), fileio_dismount_all(), fileio_find_volume_descriptor_with_label(), fileio_find_volume_id_with_label(), fileio_get_lockf_type(), fileio_get_volume_id(), fileio_is_temp_volume(), and pwrite_with_injected_fault().
void fileio_unformat (THREAD_ENTRY * thread_p, const char * vol_label_p)
Definition at line 2721 of file file_io.c.
References fileio_unformat_and_rename(), and NULL.
Referenced by boot_remove_temp_volume(), boot_remove_unknown_temp_volumes(), disk_unformat(), dwb_create_internal(), dwb_destroy_internal(), dwb_load_and_recover_pages(), fileio_abort_backup(), fileio_copy_volume(), fileio_create(), fileio_format(), fileio_remove_all_backup(), la_remove_archive_logs(), log_recovery_notpartof_archives(), log_recovery_notpartof_volumes(), log_unformat_ahead_volumes(), logpb_archive_active_log(), logpb_copy_database(), logpb_delete(), logpb_remove_all_in_log_path(), logpb_remove_archive_logs_internal(), and logpb_rename_all_volumes_files().
void fileio_unformat_and_rename (THREAD_ENTRY * thread_p, const char * vol_label_p, const char * new_label_p)
Definition at line 2736 of file file_io.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_IO_RENAME_FAIL, er_log_debug, ER_MNT_WAITING_THREAD, ER_NOTIFICATION_SEVERITY, er_set(), er_set_with_oserror(), fileio_dismount(), fileio_find_volume_descriptor_with_label(), MONITOR_WAITING_THREAD, NO_ERROR, NULL, NULL_VOLDES, os_rename_file(), prm_get_integer_value(), PRM_ID_MNT_WAITING_THREAD, tsc_elapsed_time_usec(), and tsc_getticks().
Referenced by boot_reset_mk_after_restart_from_backup(), fileio_unformat(), logpb_remove_archive_logs_internal(), and tde_copy_keys_file().
static void fileio_unlock (const char * vlabel, int vdes, FILEIO_LOCKF_TYPE lockf_type) static
Definition at line 1821 of file file_io.c.
References fileio_check_lockby_file(), FILEIO_LOCKF, fileio_make_volume_lock_name(), fileio_unlock_file, NULL, prm_get_bool_value(), and PRM_ID_IO_LOCKF_ENABLE.
Referenced by fileio_create(), fileio_dismount(), fileio_dismount_all(), fileio_dismount_volume(), fileio_dismount_without_fsync(), and fileio_lock().
FILEIO_LOCKF_TYPE fileio_unlock_la_dbname (int * lockf_vdes, char * db_name, bool clear_owner)
Definition at line 1691 of file file_io.c.
References ARG_FILE_LINE, assert, assert_release, envvar_vardir_file(), ER_BO_DIRECTORY_DOESNOT_EXIST, ER_ERROR_SEVERITY, ER_IO_MOUNT_FAIL, er_log_debug, er_set(), er_set_with_oserror(), error(), fileio_close(), FILEIO_LOCKF, FILEIO_NOT_LOCKF, fileio_release_lock(), NO_ERROR, NULL, and NULL_VOLDES.
Referenced by la_unlock_dbname().
void* fileio_write (THREAD_ENTRY * thread_p, int vol_fd, void * io_page_p, PAGEID page_id, size_t page_size, FILEIO_WRITE_MODE write_mode)
Definition at line 4150 of file file_io.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_IO_WRITE, ER_IO_WRITE_OUT_OF_SPACE, er_log_debug, ER_MNT_WAITING_THREAD, ER_NOTIFICATION_SEVERITY, er_set(), er_set_with_oserror(), fileio_compensate_flush(), FILEIO_GET_FILE_SIZE, fileio_get_volume_label_by_fd(), fileio_os_write(), FILEIO_WRITE_DEFAULT_WRITE, MONITOR_WAITING_THREAD, NULL, PEEK, perfmon_inc_stat(), prm_get_integer_value(), PRM_ID_MNT_WAITING_THREAD, PSTAT_FILE_NUM_IOWRITES, tsc_elapsed_time_usec(), and tsc_getticks().
Referenced by dwb_write_block(), fileio_format(), fileio_write_or_add_to_dwb(), fileio_write_restore(), fileio_writev(), logpb_archive_active_log(), logpb_copy_database(), logpb_write_page_to_disk(), logpb_write_toflush_pages_to_archive(), logpb_writev_append_pages(), and pgbuf_bcb_flush_with_wal().
static int fileio_write_backup (THREAD_ENTRY * thread_p, FILEIO_BACKUP_SESSION * session, ssize_t towrite_nbytes) static
Definition at line 8834 of file file_io.c.
References fileio_backup_db_buffer::area, io_backup_session::bkup, CAST_BUFLEN, fileio_backup_buffer::count, io_backup_session::dbfile, ER_FAILED, fileio_flush_backup(), fileio_backup_buffer::iosize, fileio_backup_file_header::nbytes, NO_ERROR, fileio_backup_buffer::ptr, and while().
Referenced by fileio_backup_volume(), fileio_finish_backup(), and fileio_write_backup_node().
static int fileio_write_backup_end_time_to_header (FILEIO_BACKUP_SESSION * session_p, INT64 end_time) static
Definition at line 7255 of file file_io.c.
References ARG_FILE_LINE, io_backup_session::bkup, fileio_backup_buffer::bkuphdr, io_backup_session::dbfile, fileio_backup_header::end_time, ER_ERROR_SEVERITY, ER_IO_MOUNT_FAIL, ER_IO_WRITE, er_set_with_oserror(), fileio_close(), FILEIO_FIRST_BACKUP_VOL_INFO, fileio_get_backup_info_volume_name(), FILEIO_INITIAL_BACKUP_UNITS, fileio_open(), fileio_write_backup_header(), fileio_backup_db_buffer::level, fileio_backup_file_header::nbytes, NO_ERROR, NULL, NULL_VOLDES, fileio_backup_buffer::vdes, and fileio_backup_buffer::vlabel.
Referenced by fileio_finish_backup().
static void fileio_write_backup_end_time_to_last_page (FILEIO_BACKUP_SESSION * session_p, INT64 end_time) static
Definition at line 7307 of file file_io.c.
References fileio_backup_db_buffer::area, io_backup_session::dbfile, and fileio_backup_page::iopageid.
Referenced by fileio_finish_backup().
static int fileio_write_backup_header (FILEIO_BACKUP_SESSION * session) static
Definition at line 8887 of file file_io.c.
References ARG_FILE_LINE, io_backup_session::bkup, fileio_backup_buffer::bkuphdr, CEIL_PTVDIV, cubregex::count(), ER_ERROR_SEVERITY, ER_FAILED, ER_IO_WRITE, ER_IO_WRITE_OUT_OF_SPACE, er_set(), er_set_with_oserror(), FILEIO_BACKUP_HEADER_IO_SIZE, fileio_get_volume_label_by_fd(), IO_PAGESIZE, fileio_backup_file_header::nbytes, NO_ERROR, PEEK, fileio_backup_buffer::vdes, fileio_backup_buffer::vlabel, and fileio_backup_buffer::voltotalio.
Referenced by fileio_flush_backup(), fileio_start_backup(), and fileio_write_backup_end_time_to_header().
int fileio_write_backup_info_entries (FILE * fp, int which_bkvinf)
Definition at line 11030 of file file_io.c.
References fileio_bkvinf_entry::bkvol_name, ER_FAILED, FILEIO_BACKUP_FULL_LEVEL, FILEIO_BACKUP_UNDEFINED_LEVEL, fileio_bkvinf_entry::link, NO_ERROR, NULL, and fileio_bkvinf_entry::unit_num.
Referenced by logpb_restore(), and logpb_update_backup_volume_info().
static int fileio_write_backup_node (THREAD_ENTRY * thread_p, FILEIO_BACKUP_SESSION * session, FILEIO_NODE * node, FILEIO_BACKUP_HEADER * backup_hdr) static
Definition at line 7743 of file file_io.c.
References fileio_thread_info::act_r_threads, fileio_backup_db_buffer::area, fileio_node::area, ARG_FILE_LINE, assert, fileio_backup_header::bkpagesize, io_backup_session::bkup, fileio_backup_buffer::bkuphdr, file_zip_page::buf_len, fileio_thread_info::check_npages, fileio_thread_info::check_ratio, css_get_current_conn_entry(), css_push_external_task(), fileio_backup_header::db_fullname, io_backup_session::dbfile, fileio_thread_info::end_r_threads, er_errid(), ER_ERROR_SEVERITY, ER_FAILED, ER_GENERIC_ERROR, ER_INTERRUPTED, ER_LOG_DBBACKUP_FAIL, er_set(), fileio_thread_info::errid, error(), fileio_allocate_node(), FILEIO_BACKUP_PAGE_OVERHEAD, FILEIO_CHECK_FOR_INTERRUPT_INTERVAL, fileio_compress_backup_node(), fileio_delete_queue_head(), FILEIO_ERROR_INTERRUPT, fileio_free_node(), fileio_get_base_file_name(), fileio_get_zip_level_string(), fileio_get_zip_method_string(), FILEIO_READ, fileio_read_backup(), FILEIO_SET_BACKUP_PAGE_ID_COPY, FILEIO_WRITE, fileio_write_backup(), FILEIO_ZIP_LZ4_METHOD, FILEIO_ZIP_LZO1X_METHOD, FILEIO_ZIP_NONE_METHOD, FILEIO_ZIP_ZLIB_METHOD, fileio_thread_info::from_npages, fileio_queue::head, i, fileio_thread_info::io_queue, fileio_thread_info::io_type, fileio_backup_page::iopage, LOG_FIND_THREAD_TRAN_INDEX, fileio_page_reserved::lsa, fileio_backup_db_buffer::lsa, LSA_ISNULL(), LSA_LT(), NO_ERROR, fileio_node::nread, NULL, fileio_thread_info::only_updated_pages, fileio_node::pageid, fileio_thread_info::pageid, pgbuf_is_log_check_for_interrupts(), fileio_page::prv, pthread_mutex_lock, pthread_mutex_unlock, io_backup_session::read_thread_info, rv, fileio_queue::size, thread_get_thread_entry_info(), fileio_thread_info::tran_index, io_backup_session::verbose_fp, fileio_node::writeable, fileio_node::zip_info, fileio_backup_header::zip_level, fileio_backup_header::zip_method, and file_zip_info::zip_page.
Referenced by fileio_backup_volume().
void* fileio_write_or_add_to_dwb (THREAD_ENTRY * thread_p, int vol_fd, FILEIO_PAGE * io_page_p, PAGEID page_id, size_t page_size)
Definition at line 4024 of file file_io.c.
References assert, dwb_add_page(), dwb_is_created(), FILEIO_CHECK_AND_INITIALIZE_VOLUME_HEADER_CACHE, fileio_is_volume_descriptor_equal(), fileio_traverse_permanent_volume(), fileio_write(), FILEIO_WRITE_DEFAULT_WRITE, FILEIO_WRITE_NO_COMPENSATE_WRITE, NO_ERROR, NULL, NULL_VOLDES, fileio_page_reserved::pageid, fileio_page::prv, fileio_apply_function_arg::vdes, fileio_page_reserved::volid, fileio_volinfo::volid, and VPID_SET.
Referenced by fileio_copy_volume(), fileio_expand_to(), fileio_format(), fileio_initialize_pages(), and fileio_reset_volume().
void* fileio_write_pages (THREAD_ENTRY * thread_p, int vol_fd, char * io_pages_p, PAGEID page_id, int num_pages, size_t page_size, FILEIO_WRITE_MODE write_mode)
Definition at line 4314 of file file_io.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_IO_WRITE, er_log_debug, ER_MNT_WAITING_THREAD, ER_NOTIFICATION_SEVERITY, er_set(), er_set_with_oserror(), fileio_compensate_flush(), FILEIO_GET_FILE_SIZE, fileio_get_volume_label_by_fd(), fileio_os_write(), FILEIO_WRITE_DEFAULT_WRITE, MONITOR_WAITING_THREAD, NULL, PEEK, perfmon_add_stat(), prm_get_integer_value(), PRM_ID_MNT_WAITING_THREAD, PSTAT_FILE_NUM_IOWRITES, tsc_elapsed_time_usec(), and tsc_getticks().
Referenced by dwb_flush_block(), logpb_archive_active_log(), and logpb_background_archiving().
static void * fileio_write_restore (THREAD_ENTRY * thread_p, FILEIO_RESTORE_PAGE_BITMAP * page_bitmap, int vdes, void * io_pgptr, VOLID vol_id, PAGEID page_id, FILEIO_BACKUP_LEVEL level) static
Definition at line 10506 of file file_io.c.
References assert, dwb_is_created(), FILEIO_BACKUP_FULL_LEVEL, fileio_page_bitmap_is_set(), fileio_page_bitmap_set(), fileio_write(), FILEIO_WRITE_DEFAULT_WRITE, FILEIO_WRITE_NO_COMPENSATE_WRITE, IO_PAGESIZE, NULL, and page_bitmap::vol_id.
Referenced by fileio_fill_hole_during_restore(), and fileio_restore_volume().
void* fileio_writev (THREAD_ENTRY * thread_p, int vol_fd, void ** io_page_array, PAGEID start_page_id, DKNPAGES npages, size_t page_size)
Definition at line 4412 of file file_io.c.
References dwb_is_created(), fileio_write(), FILEIO_WRITE_DEFAULT_WRITE, FILEIO_WRITE_NO_COMPENSATE_WRITE, i, and NULL.
static ssize_t pwrite_with_injected_fault (THREAD_ENTRY * thread_p, int fd, const void * buf, size_t count, off_t offset) static
Definition at line 3639 of file file_io.c.
References _exit(), ARG_FILE_LINE, assert, ER_FAILED_ASSERTION, ER_NOTIFICATION_SEVERITY, er_print_callstack(), er_set(), err, FI_INSERTED, FI_TEST_FILE_IO_WRITE_PARTS1, FI_TEST_FILE_IO_WRITE_PARTS2, FILEIO_CHECK_AND_INITIALIZE_VOLUME_HEADER_CACHE, fileio_find_system_volume(), fileio_get_volume_label_by_fd(), fileio_is_permanent_volume_descriptor(), fileio_is_system_volume_descriptor_equal(), fileio_is_volume_descriptor_equal(), fileio_page_check_corruption(), fileio_page_hexa_dump(), FILEIO_SYNC_ONLY, fileio_synchronize(), fileio_traverse_permanent_volume(), fileio_traverse_temporary_volume(), i, logpb_debug_check_log_page(), fileio_backup_file_header::nbytes, NO_ERROR, NULL, PEEK, prm_get_bool_value(), PRM_ID_ER_LOG_DEBUG, pthread_mutex_lock, pthread_mutex_unlock, rv, fileio_apply_function_arg::vdes, and fileio_backup_file_header::vlabel.
Referenced by fileio_os_write().
Variable Documentation
FLUSH_STATS fc_Stats static
Definition at line 453 of file file_io.c.
TOKEN_BUCKET* fc_Token_bucket = NULL static
Definition at line 452 of file file_io.c.
Referenced by fileio_flush_control_add_tokens(), fileio_flush_control_finalize(), and fileio_flush_control_get_token().
TOKEN_BUCKET fc_Token_bucket_s static
Definition at line 451 of file file_io.c.
Referenced by fileio_flush_control_initialize().
FILEIO_BACKUP_INFO_QUEUE fileio_Backup_vol_info_data[2] static
Initial value:
=
  { {false, {NULL, NULL, NULL}, NULL}, {false, {NULL, NULL, NULL}, NULL} }
Definition at line 442 of file file_io.c.
int fileio_Flushed_page_count = 0 static
Definition at line 449 of file file_io.c.
Referenced by fileio_compensate_flush(), and fileio_increase_flushed_page_count().
pthread_mutex_t fileio_Flushed_page_counter_mutex = PTHREAD_MUTEX_INITIALIZER static
Definition at line 447 of file file_io.c.
Referenced by fileio_increase_flushed_page_count().
FILEIO_SYSTEM_VOLUME_HEADER fileio_Sys_vol_info_header static
Initial value:
= {
  0,
  {
   NULL_VOLID, NULL_VOLDES, FILEIO_NOT_LOCKF, "",
   NULL}
}
Definition at line 421 of file file_io.c.
Referenced by fileio_dismount_all().
FILEIO_VOLUME_HEADER fileio_Vol_info_header static
Initial value:
= {
  0, 0, 0, LOG_MAX_DBVOLID, 0, NULL
}
Definition at line 434 of file file_io.c.
Referenced by fileio_dismount_all(), fileio_map_mounted(), fileio_reverse_traverse_permanent_volume(), fileio_reverse_traverse_temporary_volume(), fileio_traverse_permanent_volume(), and fileio_traverse_temporary_volume().
int rv static
Definition at line 309 of file file_io.c.
Referenced by fileio_backup_volume(), fileio_cache(), fileio_compensate_flush(), fileio_decache(), fileio_decompress_restore_volume(), fileio_dismount_all(), fileio_expand_permanent_volume_info(), fileio_expand_temporary_volume_info(), fileio_expand_to(), fileio_finalize_backup_thread(), fileio_find_volume_descriptor_with_label(), fileio_find_volume_id_with_label(), fileio_flush_control_add_tokens(), fileio_flush_control_get_token(), fileio_flush_control_initialize(), fileio_get_lockf_type(), fileio_get_volume_descriptor(), fileio_get_volume_id(), fileio_get_volume_label(), fileio_initialize_backup_thread(), fileio_initialize_volume_info_cache(), fileio_os_read(), fileio_os_write(), fileio_synchronize_all(), fileio_traverse_system_volume(), fileio_write_backup_node(), and pwrite_with_injected_fault().