CUBRID Engine: src/query/filter_pred_cache.h File Reference
filter_pred_cache.h File Reference
#include "storage_common.h"
#include "thread_compat.hpp"
#include <cstdio>
Functions
int fpcache_initialize (THREAD_ENTRY *thread_p)
void fpcache_finalize (THREAD_ENTRY *thread_p)
int fpcache_claim (THREAD_ENTRY *thread_p, BTID *btid, or_predicate *or_pred, pred_expr_with_context **pred_expr)
int fpcache_retire (THREAD_ENTRY *thread_p, OID *class_oid, BTID *btid, pred_expr_with_context *filter_pred)
void fpcache_remove_by_class (THREAD_ENTRY *thread_p, const OID *class_oid)
void fpcache_drop_all (THREAD_ENTRY *thread_p)
void fpcache_dump (THREAD_ENTRY *thread_p, FILE *fp)
Function Documentation
int fpcache_claim (THREAD_ENTRY * thread_p, BTID * btid, or_predicate * or_pred, pred_expr_with_context ** pred_expr)
Definition at line 359 of file filter_pred_cache.c.
References assert, ASSERT_ERROR, fpcache_ent::clone_stack, fpcache_ent::clone_stack_head, db_change_private_heap(), cubthread::lockfree_hashmap< Key, T >::find(), fpcache_Clone_counter, fpcache_Clone_stack_size, fpcache_Enabled, fpcache_Stat_clone_hit, fpcache_Stat_clone_miss, fpcache_Stat_hit, fpcache_Stat_lookup, fpcache_Stat_miss, fpcache_ent::mutex, NO_ERROR, NULL, or_predicate::pred_stream, or_predicate::pred_stream_size, pthread_mutex_unlock, and stx_map_stream_to_filter_pred().
Referenced by locator_eval_filter_predicate().
void fpcache_drop_all (THREAD_ENTRY * thread_p)
Definition at line 757 of file filter_pred_cache.c.
References cubthread::lockfree_hashmap< Key, T >::clear(), fpcache_Clone_counter, fpcache_Entry_counter, fpcache_Stat_clone_discard, and fpcache_Stat_discard.
Referenced by xqmgr_drop_all_query_plans().
void fpcache_dump (THREAD_ENTRY * thread_p, FILE * fp)
Definition at line 591 of file filter_pred_cache.c.
References assert, fpcache_ent::btid, fpcache_ent::clone_stack_head, vfid::fileid, fpcache_Clone_counter, fpcache_Enabled, fpcache_Entry_counter, fpcache_Soft_capacity, fpcache_Stat_add, fpcache_Stat_cleanup, fpcache_Stat_cleanup_entry, fpcache_Stat_clone_add, fpcache_Stat_clone_discard, fpcache_Stat_clone_hit, fpcache_Stat_clone_miss, fpcache_Stat_discard, fpcache_Stat_hit, fpcache_Stat_lookup, fpcache_Stat_miss, cubthread::lockfree_hashmap< Key, T >::iterator::iterate(), NULL, btid::root_pageid, btid::vfid, and vfid::volid.
Referenced by xqmgr_dump_query_plans().
void fpcache_finalize (THREAD_ENTRY * thread_p)
Definition at line 206 of file filter_pred_cache.c.
References bh_destroy(), db_change_private_heap(), cubthread::lockfree_hashmap< Key, T >::destroy(), fpcache_Enabled, and NULL.
Referenced by boot_restart_server(), and xboot_shutdown_server().
int fpcache_initialize (THREAD_ENTRY * thread_p)
Definition at line 143 of file filter_pred_cache.c.
References ASSERT_ERROR_AND_SET, bh_create(), db_change_private_heap(), fpcache_Cleanup_flag, FPCACHE_CLEANUP_RATIO, fpcache_Clone_counter, fpcache_Clone_stack_size, fpcache_compare_cleanup_candidates(), fpcache_Enabled, fpcache_Entry_counter, fpcache_Soft_capacity, fpcache_Stat_add, fpcache_Stat_cleanup, fpcache_Stat_cleanup_entry, fpcache_Stat_clone_discard, fpcache_Stat_clone_hit, fpcache_Stat_clone_miss, fpcache_Stat_discard, fpcache_Stat_hit, fpcache_Stat_lookup, fpcache_Stat_miss, fpcache_Ts, cubthread::lockfree_hashmap< Key, T >::init(), lf_freelist_destroy(), lf_hash_destroy(), max, NO_ERROR, NULL, prm_get_integer_value(), PRM_ID_FILTER_PRED_MAX_CACHE_CLONES, PRM_ID_FILTER_PRED_MAX_CACHE_ENTRIES, and THREAD_TS_FPCACHE.
Referenced by boot_restart_server().
void fpcache_remove_by_class (THREAD_ENTRY * thread_p, const OID * class_oid)
Definition at line 503 of file filter_pred_cache.c.
References assert, fpcache_ent::btid, fpcache_ent::class_oid, FPCACHE_DELETE_BTIDS_SIZE, fpcache_Enabled, fpcache_Entry_counter, fpcache_Stat_discard, fpcache_ent::mutex, NULL, OID_EQ, pthread_mutex_unlock, and success().
Referenced by locator_delete_force_internal(), locator_update_force(), and log_cleanup_modified_class().
int fpcache_retire (THREAD_ENTRY * thread_p, OID * class_oid, BTID * btid, pred_expr_with_context * filter_pred)
Definition at line 427 of file filter_pred_cache.c.
References assert, fpcache_ent::class_oid, fpcache_ent::clone_stack, fpcache_ent::clone_stack_head, COPY_OID, db_change_private_heap(), db_private_free_and_init, ER_FAILED, cubthread::lockfree_hashmap< Key, T >::find_or_insert(), fpcache_cleanup(), fpcache_Clone_counter, fpcache_Clone_stack_size, fpcache_Enabled, fpcache_Entry_counter, fpcache_Soft_capacity, fpcache_Stat_add, fpcache_Stat_clone_add, fpcache_Stat_clone_discard, free_xasl_unpack_info(), fpcache_ent::mutex, NO_ERROR, NULL, OID_EQ, pthread_mutex_unlock, fpcache_ent::time_last_used, and pred_expr_with_context::unpack_info.
Referenced by locator_eval_filter_predicate().