CUBRID Engine: src/base/fixed_alloc.c File Reference
fixed_alloc.c File Reference
#include "config.h"
#include <stdlib.h>
#include <stdio.h>
#include <errno.h>
#include "memory_alloc.h"
#include "customheaps.h"
Classes
struct rec_link
Typedefs
typedef struct rec_link REC_LINK
Functions
static int compute_rec_size (int nominal_size)
HL_HEAPID db_create_fixed_heap (int req_size, int recs_per_chunk)
void db_destroy_fixed_heap (HL_HEAPID heap_id)
void * db_fixed_alloc (HL_HEAPID heap_id, size_t size)
void db_fixed_free (HL_HEAPID heap_id, void *ptr)
Typedef Documentation
typedef struct rec_link REC_LINK
Definition at line 38 of file fixed_alloc.c.
Function Documentation
static int compute_rec_size (int nominal_size) static
Definition at line 51 of file fixed_alloc.c.
References db_align_to(), and db_alignment().
Referenced by db_create_fixed_heap().
HL_HEAPID db_create_fixed_heap (int req_size, int recs_per_chunk)
Definition at line 64 of file fixed_alloc.c.
References compute_rec_size(), and hl_register_fixed_heap().
Referenced by locator_all_reference_lockset(), mht_create(), and mht_create_hls().
void db_destroy_fixed_heap (HL_HEAPID heap_id)
Definition at line 80 of file fixed_alloc.c.
References hl_unregister_fixed_heap().
Referenced by locator_all_reference_lockset(), mht_create(), mht_create_hls(), mht_destroy(), and mht_destroy_hls().
void* db_fixed_alloc (HL_HEAPID heap_id, size_t size)
Definition at line 92 of file fixed_alloc.c.
References hl_fixed_alloc(), and NULL.
Referenced by locator_all_reference_lockset(), mht_put2_internal(), mht_put_hls_internal(), and mht_put_internal().
void db_fixed_free (HL_HEAPID heap_id, void * ptr)
Definition at line 109 of file fixed_alloc.c.
References hl_fixed_free().