CUBRID Engine: src/executables/gencat.c File Reference
gencat.c File Reference
#include <sys/cdefs.h>
#include <sys/types.h>
#include <sys/queue.h>
#include <arpa/inet.h>
#include <ctype.h>
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "porting.h"
#include "cubrid_getopt.h"
Classes
struct _msgT
struct _setT
struct _nls_cat_hdr
struct _nls_set_hdr
struct _nls_msg_hdr
Macros
#define _NLS_PRIVATE
#define NL_SETMAX 255
#define NL_MSGMAX 2048
#define _NLS_MAGIC 0xff88ff89
#define NL_SETD 0
#define NL_CAT_LOCALE 1
#define CORRUPT "corrupt message catalog"
#define NOMEMORY "out of memory"
Functions
LIST_HEAD (static void warning(const char *, _setT)
int main (int argc, char *argv[])
static void warning (const char *cptr, const char *msg)
static void error (const char *msg)
static void * xmalloc (size_t len)
static void * xrealloc (void *ptr, size_t size)
static char * xstrdup (const char *str)
static char * get_line (int fd)
static char * wskip (char *cptr)
static char * cskip (char *cptr)
static char * getmsg (int fd, char *cptr, char quote)
void MCParse (int fd)
void MCReadCat (int fd)
void MCWriteCat (int fd)
void MCAddSet (int setId)
void MCAddMsg (int msgId, const char *str)
void MCDelSet (int setId)
void MCDelMsg (int msgId)
Macro Definition Documentation
#define _NLS_MAGIC 0xff88ff89
Definition at line 138 of file gencat.c.
Referenced by MCReadCat(), and MCWriteCat().
#define _NLS_PRIVATE
Definition at line 77 of file gencat.c.
#define CORRUPT "corrupt message catalog"
Referenced by MCReadCat().
#define NL_CAT_LOCALE 1
Definition at line 164 of file gencat.c.
#define NL_MSGMAX 2048
Definition at line 121 of file gencat.c.
Referenced by MCAddMsg().
#define NL_SETD 0
Definition at line 163 of file gencat.c.
Referenced by MCParse().
#define NL_SETMAX 255
Definition at line 118 of file gencat.c.
Referenced by MCAddSet(), and MCDelSet().
#define NOMEMORY "out of memory"
Referenced by xmalloc(), xrealloc(), and xstrdup().
Function Documentation
static char* cskip (char * cptr) static
Definition at line 485 of file gencat.c.
References warning().
Referenced by MCParse().
static void error (const char * msg) static
Definition at line 331 of file gencat.c.
References warning().
Referenced by access_control_read_config_file(), access_control_read_ip_info(), access_object(), acl_reload(), acquire_locks_for_multiple_rename(), add_arg_domain(), add_class_object(), add_foreign_key(), add_method_internal(), add_query_to_virtual_class(), add_resolution(), add_union_query(), adjust_partition_range(), adjust_partition_size(), admin_del_cas_log(), admin_getid_cmd(), allocate_disk_structures_index(), allocate_index(), alter_trigger_cache(), alter_trigger_hierarchy(), alterdbhost(), apply_grants(), applyinfo(), applylogdb(), appropriate_error(), area_create(), area_validate(), assign_set_value(), au_add_direct_groups(), au_add_member_internal(), au_add_member_method(), au_add_user_method(), au_change_owner(), au_change_owner_method(), au_change_serial_owner(), au_change_serial_owner_method(), au_change_sp_owner(), au_change_sp_owner_method(), au_change_trigger_owner(), au_change_trigger_owner_method(), au_check_authorization(), au_check_authorization_method(), au_check_user(), au_compute_groups(), au_delete_auth_of_dropping_table(), au_delete_new_auth(), au_drop_member(), au_drop_member_method(), au_drop_user(), au_drop_user_method(), au_dump_auth(), au_dump_to_file(), au_dump_user(), au_export_grants(), au_export_users(), au_extend_class_caches(), au_fetch_class_internal(), au_fetch_instance(), au_find_user(), au_find_user_cache_index(), au_find_user_method(), au_find_user_to_drop(), au_force_write_new_auth(), au_get_class_privilege(), au_get_new_auth(), au_get_object(), au_get_owner_method(), au_get_set(), au_get_user_name(), au_grant(), au_insert_new_auth(), au_login(), au_login_method(), au_make_user(), au_perform_login(), au_print_auth(), au_propagate_del_new_auth(), au_revoke(), au_set_get_obj(), au_set_new_auth(), au_set_password_encoded_method(), au_set_password_encoded_sha1_method(), au_set_password_internal(), au_set_password_method(), au_set_user(), au_set_user_comment(), au_start(), au_update_new_auth(), bfmt_print(), bfmt_value(), bifmt_numeric_value(), boot_client_all_finalize(), boot_client_find_and_cache_class_oids(), boot_create_all_volumes(), boot_get_server_locales(), boot_get_server_timezone_checksum(), boot_restart_client(), boot_restart_server(), brief_monitor(), btree_add_index(), btree_attrinfo_read_dbvalues(), btree_check_page_key(), btree_check_pages(), btree_check_tree(), btree_compress_node(), btree_construct_leafs(), btree_dump_curr_key(), btree_dump_leaf_record(), btree_dump_non_leaf_record(), btree_find_AR_sampling_leaf(), btree_find_boundary_leaf(), btree_find_next_index_record(), btree_find_oid_and_its_page(), btree_find_oid_from_leaf(), btree_find_split_point(), btree_first_oid(), btree_fix_root_for_insert(), btree_get_index_key_type(), btree_get_next_key_info(), btree_get_next_node_info(), btree_get_num_visible_oids_from_all_ovf(), btree_get_pkey_btid(), btree_index_start_scan(), btree_key_append_object_as_new_overflow(), btree_key_find_and_lock_unique_of_non_unique(), btree_key_find_first_visible_row(), btree_key_find_first_visible_row_from_all_ovf(), btree_key_insert_new_key(), btree_key_insert_new_object(), btree_load_index(), btree_locate_key(), btree_merge_node_and_advance(), btree_node_common_prefix(), btree_node_size_uncompressed(), btree_overflow_remove_object(), btree_range_opt_check_add_index_key(), btree_read_record(), btree_rv_ovfid_undoredo_update(), btree_rv_pagerec_insert(), btree_rv_read_keyval_info_nocopy(), btree_rv_redo_global_unique_stats_commit(), btree_rv_roothdr_undo_update(), btree_rv_undo_global_unique_stats_commit(), btree_rv_update_tran_stats(), btree_scan_for_show_index_capacity(), btree_scan_for_show_index_header(), btree_search_key_and_apply_functions(), btree_search_leaf_page(), btree_split_node_and_advance(), btree_top_n_items_binary_search(), btree_verify_leaf_node(), btree_verify_nonleaf_node(), btree_verify_subtree(), btree_verify_tree(), build_att_type_change_map(), build_attr_change_map(), build_class_grant_list(), build_xasl_for_server_delete(), call_method(), cas_runner(), catalog_create(), catalog_drop_all(), catalog_get_cardinality(), catalog_get_cardinality_by_name(), catalog_get_dir_oid_from_cache(), catalog_get_representation(), catalog_start_access_with_dir_oid(), catcls_compile_catalog_classes(), catcls_convert_attr_id_to_name(), catcls_delete_catalog_classes(), catcls_delete_instance(), catcls_delete_subset(), catcls_expand_or_value_by_def(), catcls_expand_or_value_by_repr(), catcls_find_btid_of_class_name(), catcls_find_oid_by_class_name(), catcls_get_apply_info_log_record_time(), catcls_get_db_collation(), catcls_get_object_set(), catcls_get_or_value_from_attribute(), catcls_get_or_value_from_attrid(), catcls_get_or_value_from_buffer(), catcls_get_or_value_from_class(), catcls_get_or_value_from_domain(), catcls_get_or_value_from_indexes(), catcls_get_or_value_from_method(), catcls_get_or_value_from_method_argument(), catcls_get_or_value_from_method_file(), catcls_get_or_value_from_method_signiture(), catcls_get_or_value_from_partition(), catcls_get_or_value_from_query_spec(), catcls_get_or_value_from_record(), catcls_get_or_value_from_resolution(), catcls_get_property_set(), catcls_get_server_compat_info(), catcls_get_subset(), catcls_insert_catalog_classes(), catcls_insert_instance(), catcls_insert_subset(), catcls_put_or_value_into_buffer(), catcls_put_or_value_into_record(), catcls_reorder_attributes_by_repr(), catcls_update_catalog_classes(), catcls_update_instance(), catcls_update_subset(), cfg_new_db(), change_constraints_comment_partitioned_class(), change_constraints_status_partitioned_class(), changemode(), check_alias_conflict(), check_alias_delete(), check_alias_domains(), check_args(), check_att_chg_allowed(), check_attribute_method_overlap(), check_authorization(), check_change_attribute(), check_change_class_collation(), check_constraints(), check_default_on_update_clause(), check_domain_class_type(), check_fk_validity(), check_grant_option(), check_invalid_resolutions(), check_local_definition(), check_missing_non_null_attrs(), check_namespace(), check_reinit_copylog(), check_resolution_target(), check_semantics(), check_serial_invariants(), check_set_object(), checksumdb(), chksum_calculate_checksum(), chksum_drop_and_create_checksum_table(), chksum_get_next_lower_bound(), chksum_get_prev_checksum_results(), chksum_init_checksum_tables(), chksum_insert_schema_definition(), chksum_report(), chksum_report_diff(), chksum_report_schema_diff(), chksum_report_summary(), chksum_set_initial_chunk_id_and_lower_bound(), chksum_start(), chksum_update_current_schema_definition(), chksum_update_master_checksum(), class_type(), classobj_cache_class_constraints(), classobj_cache_constraint_entry(), classobj_cache_constraint_list(), classobj_change_constraint_comment(), classobj_change_constraint_status(), classobj_check_index_exist(), classobj_copy_attribute_like(), classobj_copy_constraint_like(), classobj_copy_partition_info(), classobj_copy_props(), classobj_drop_prop(), classobj_find_prop_constraint(), classobj_get_prop(), classobj_init_attribute(), classobj_init_method(), classobj_is_exist_foreign_key_ref(), classobj_make_foreign_key_info(), classobj_make_foreign_key_ref(), classobj_make_foreign_key_ref_list(), classobj_make_function_index_info(), classobj_make_index_filter_pred_info(), classobj_make_template(), classobj_populate_class_properties(), classobj_put_index(), classobj_put_prop(), cnv_bad_char(), co_code(), co_signal(), co_signalv(), coerce_binary_to_dbvalue(), coerce_char_to_dbvalue(), col_add(), col_delete(), col_drop(), col_drop_nulls(), col_insert(), col_permanent_oids(), col_put(), col_sort(), collect_class_grants(), collect_hier_class_info(), compactdb(), compactdb_start(), compile_trigger_activity(), conn_restart_client(), convert_speclist_to_objlist(), copylogdb(), create_or_drop_index_helper(), create_srv_handle_with_query_result(), csect_start_scan(), csession_create_prepared_statement(), csession_find_or_create_session(), csession_get_prepared_statement(), csql(), csql_execute_statements(), csql_help_info(), csql_help_menu(), csql_help_schema(), csql_help_trigger(), csql_killtran(), csql_read_file(), csql_results(), csql_write_file(), css_accept(), css_client_init(), css_default_server_timeout_fn(), css_get_session_ids_for_active_connections(), css_increment_num_conn(), css_increment_num_conn_internal(), css_init_conn_list(), css_is_shutdown_timeout_expired(), css_make_access_status_exist_user(), css_net_recv(), css_open_server_connection_socket(), css_process_activate_heartbeat(), css_process_deact_confirm_no_server(), css_process_deact_confirm_stop_all(), css_process_deactivate_heartbeat(), css_process_ha_start_util_process(), css_process_heartbeat_request(), css_process_new_client(), css_refuse_connection_request(), css_register_server_timeout_fn(), css_user_access_status_start_scan(), cur_tuple(), db_abort_to_savepoint(), db_abort_to_savepoint_internal(), db_abort_transaction(), db_acos_dbval(), db_add_attribute_internal(), db_add_class_resolution(), db_add_days_to_year(), db_add_method_file(), db_add_query_spec(), db_add_resolution(), db_add_set_attribute_domain(), db_add_super(), db_add_super_internal(), db_add_time(), db_add_volume_ex(), db_ascii(), db_asin_dbval(), db_bigint_to_binary_string(), db_bit_string(), db_change_default(), db_change_method_implementation(), db_change_query_spec(), db_col_add(), db_col_drop(), db_col_drop_element(), db_col_drop_nulls(), db_col_filter(), db_col_find(), db_col_get(), db_col_insert(), db_col_optimize(), db_col_put(), db_compile_and_execute_queries_internal(), db_conv(), db_conv_tz(), db_convert_sec_to_time(), db_convert_to_time(), db_crc32_dbval(), db_create(), db_create_vclass(), db_date_add_sub_interval_days(), db_date_add_sub_interval_expr(), db_date_diff(), db_date_format(), db_datetime_string(), db_datetime_to_timestamp(), db_dput(), db_drop_attribute(), db_drop_attribute_internal(), db_drop_class_resolution(), db_drop_method_file(), db_drop_method_files(), db_drop_query_spec(), db_drop_resolution(), db_drop_set_attribute_domain(), db_drop_super(), db_drop_super_connect(), db_dsend(), db_enum_put_cs_and_collation(), db_execute_with_values(), db_fetch_array(), db_fetch_composition(), db_fetch_list(), db_format(), db_from_tz(), db_from_unixtime(), db_gadget_create(), db_gadget_exec(), db_get_class_num_objs_and_pages(), db_get_date_format(), db_get_query_format(), db_get_schema_def_dbval(), db_get_system_parameters(), db_guid(), db_hex(), db_inet_aton(), db_inet_ntoa(), db_init(), db_is_deleted(), db_is_updatable_attribute(), db_is_updatable_object(), db_is_vclass(), db_json_is_valid(), db_namelist_add(), db_namelist_append(), db_new_time(), db_open_buffer_and_compile_first_statement(), db_ping_server(), db_power_dbval(), db_put(), db_query_end_internal(), db_query_execute(), db_query_prefetch_columns(), db_rename(), db_rename_attribute(), db_rename_internal(), db_reset_system_parameters_from_assignments(), db_restart(), db_send(), db_seq_create(), db_seq_insert(), db_seq_put(), db_set_add(), db_set_create(), db_set_create_basic(), db_set_create_multi(), db_set_loader_commands(), db_set_system_parameters(), db_shutdown(), db_sleep(), db_str_to_date(), db_string_aes_decrypt(), db_string_aes_encrypt(), db_string_date(), db_string_datetime(), db_string_put_cs_and_collation(), db_string_sha_one(), db_string_sha_two(), db_string_time(), db_string_timestamp(), db_string_to_datetimeltz_ex(), db_string_to_timestampltz_ex(), db_string_truncate(), db_string_value(), db_time_diff(), db_time_format(), db_time_string(), db_timestamp_string(), db_unpack_prepare_info(), db_value_clear(), db_value_clear_array(), db_value_clone(), db_value_domain_default(), db_value_domain_init(), db_value_domain_max(), db_value_domain_min(), db_value_domain_zero(), db_value_free(), db_value_put_monetary_currency(), dbt_add_argument(), dbt_add_attribute(), dbt_add_class_attribute(), dbt_add_class_method(), dbt_add_class_resolution(), dbt_add_constraint(), dbt_add_foreign_key(), dbt_add_method(), dbt_add_method_file(), dbt_add_query_spec(), dbt_add_resolution(), dbt_add_set_argument_domain(), dbt_add_set_attribute_domain(), dbt_add_shared_attribute(), dbt_add_super(), dbt_change_default(), dbt_change_method_implementation(), dbt_change_query_spec(), dbt_constrain_non_null(), dbt_constrain_unique(), dbt_dput(), dbt_drop_attribute(), dbt_drop_class_attribute(), dbt_drop_class_method(), dbt_drop_class_resolution(), dbt_drop_constraint(), dbt_drop_method(), dbt_drop_method_file(), dbt_drop_method_files(), dbt_drop_query_spec(), dbt_drop_resolution(), dbt_drop_set_attribute_domain(), dbt_drop_shared_attribute(), dbt_drop_super(), dbt_drop_super_connect(), dbt_put(), dbt_put_internal(), dbt_rename(), dbt_rename_method_file(), dbt_reset_query_spec(), dbt_set_loader_commands(), deallocate_index(), delete_all_ha_apply_info(), delete_all_slave_ha_apply_info(), delete_list_by_oids(), delete_object_tuple(), delete_real_class(), delete_resolution(), desc_disk_to_obj(), desc_obj_to_disk(), desc_value_special_fprint(), object_printer::describe_class(), disk_reserve_sectors(), disk_set_creation(), disk_set_link(), disk_volume_header_next_scan(), disk_volume_header_start_scan(), do_add_attribute(), do_add_attribute_from_select_column(), do_add_attributes(), do_add_constraints(), do_add_method_files(), do_add_methods(), do_add_queries(), do_add_resolutions(), do_add_supers(), do_alter_change_auto_increment(), do_alter_change_col_comment(), do_alter_change_default_cs_coll(), do_alter_change_owner(), do_alter_change_tbl_comment(), do_alter_clause_add_index(), do_alter_clause_change_attribute(), do_alter_index(), do_alter_index_comment(), do_alter_index_rebuild(), do_alter_index_status(), do_alter_one_clause_with_template(), do_alter_partitioning_post(), do_alter_partitioning_pre(), do_alter_serial(), do_alter_trigger(), do_alter_user(), do_change_att_schema_only(), do_check_delete_trigger(), do_check_fk_constraints_internal(), do_check_for_empty_classes_in_delete(), do_check_insert_server_allowed(), do_check_internal_statements(), do_check_partitioned_class(), do_check_rows_for_null(), do_coalesce_partition_post(), do_coalesce_partition_pre(), do_copy_indexes(), do_create_auto_increment_serial(), do_create_entity(), do_create_index(), do_create_local(), do_create_midxkey_for_constraint(), do_create_partition(), do_create_partition_constraint(), do_create_partition_constraints(), do_create_serial(), do_create_serial_internal(), do_create_trigger(), do_create_user(), do_delete(), do_drop(), do_drop_att_constraints(), do_drop_partition_list(), do_drop_partitioned_class(), do_drop_saved_indexes(), do_drop_serial(), do_drop_session_variables(), do_drop_trigger(), do_drop_user(), do_evaluate(), do_evaluate_default_expr(), do_execute_do(), do_execute_merge(), do_execute_statement(), do_execute_trigger(), do_find_auto_increment_serial(), do_find_unique_constraint_violations(), do_get_optimization_param(), do_get_partition_keycol(), do_get_partition_parent(), do_get_partition_size(), do_get_serial_cached_num(), do_get_stats(), do_get_trigger(), do_get_xaction(), do_grant(), do_insert(), do_insert_at_server(), do_insert_checks(), do_insert_template(), do_kill(), do_prepare_insert(), do_prepare_insert_internal(), do_promote_partition(), do_promote_partition_by_name(), do_promote_partition_list(), do_recreate_att_constraints(), do_recreate_filter_index_constr(), do_recreate_func_index_constr(), do_recreate_renamed_class_indexes(), do_recreate_saved_indexes(), do_redistribute_partitions_data(), do_remove_partition_post(), do_remove_partition_pre(), do_remove_trigger(), do_rename(), do_rename_partition(), do_rename_trigger(), do_reorganize_partition_post(), do_reorganize_partition_pre(), do_replace_into(), do_replace_names_for_insert_values_pre(), do_replicate_statement(), do_revoke(), do_rollback(), do_run_update_query_for_class(), do_run_update_query_for_new_default_expression_fields(), do_run_update_query_for_new_notnull_fields(), do_run_upgrade_instances_domain(), do_save_all_indexes(), do_savepoint(), do_scope(), do_select_internal(), do_set_insert_server_not_allowed(), do_set_names(), do_set_object_id(), do_set_pruning_type(), do_set_session_variables(), do_set_sys_params(), do_set_timezone(), do_set_trigger(), do_set_xaction(), do_statement(), do_truncate(), do_update(), do_update_auto_increment_serial_on_rename(), do_update_maxvalue_of_auto_increment_serial(), do_update_new_cols_with_default_expression(), do_update_new_notnull_cols_without_default(), do_update_stats(), do_vacuum(), drop_foreign_key_ref(), drop_foreign_key_ref_internal(), drop_internal(), drop_stored_procedure(), dumplocale(), ehash_rv_delete(), ehash_rv_delete_undo(), ehash_rv_insert_undo(), emit_autoincrement_def(), er_event_init(), es_posix_copy_file(), es_posix_create_file(), es_posix_delete_file(), es_posix_rename_file(), eval_action(), eval_condition(), ex_contains_object_reference(), execute_create_select_query(), execute_info_set(), export_serial(), extract_objects(), fetch_class(), fetch_descriptor_class(), fetch_instance(), fetch_peek_arith(), fetch_peek_dbval(), fetch_peek_min_max_value_of_width_bucket_func(), fetch_set_internal(), ffmt_value(), file_apply_tde_to_class_files(), fileio_backup_volume(), fileio_compress_backup_node(), fileio_copy_volume(), fileio_decompress_restore_volume(), fileio_get_lock(), fileio_get_primitive_way_max(), fileio_initialize_backup(), fileio_list_restore(), fileio_lock_la_dbname(), fileio_release_lock(), fileio_restore_volume(), fileio_set_permission(), fileio_skip_restore_volume(), fileio_start_backup(), fileio_synchronize_all(), fileio_unlock_la_dbname(), fileio_write_backup_node(), filter_local_constraints(), filter_resolutions(), find_all_triggers(), find_any(), find_argument(), find_attribute(), find_attribute_op(), find_event_triggers(), find_method(), find_shared_attribute(), find_signature(), flatten_components(), flatten_properties(), flatten_subclasses(), flatten_template(), flatten_trigger_cache(), fmt_date_value(), fmt_fractional_digits(), fmt_fractional_value(), fmt_integral_digits(), fmt_integral_value(), fmt_minute_value(), fmt_second_value(), fmt_time_value(), fmt_timestamp_value(), fn_proxy_cas_check_cas(), fn_proxy_cas_end_tran(), fn_proxy_cas_fetch(), fn_proxy_cas_prepare(), fn_proxy_cas_prepare_and_execute(), fn_proxy_cas_relay_only(), fn_proxy_cas_schema_info(), fn_proxy_client_check_cas(), fn_proxy_client_close_req_handle(), fn_proxy_client_con_close(), fn_proxy_client_conn_error(), fn_proxy_client_cursor(), fn_proxy_client_cursor_close(), fn_proxy_client_end_tran(), fn_proxy_client_fetch(), fn_proxy_client_get_db_parameter(), fn_proxy_client_get_db_version(), fn_proxy_client_prepare(), fn_proxy_client_prepare_and_execute(), fn_proxy_client_schema_info(), fn_proxy_client_set_db_parameter(), fn_proxy_get_shard_info(), fprint_special_set(), fprint_special_strings(), get_att_default_from_def(), get_class_mops(), get_current_result(), get_domain_internal(), get_estimated_objs(), get_grants(), get_hour_minute_or_second(), get_query_stmt_from_plan(), get_requested_classes(), get_schema_trigger_objects(), get_server_state_from_master(), get_user_trigger_objects(), getmsg(), HL::CPUInfo::getThreadId(), hb_activate_heartbeat(), hb_check_request_eligibility(), hb_cleanup_conn_and_start_process(), hb_cluster_job_calc_score(), hb_cluster_job_check_ping(), hb_cluster_job_check_valid_ping_server(), hb_cluster_job_demote(), hb_cluster_job_failback(), hb_cluster_job_failover(), hb_cluster_job_heartbeat(), hb_cluster_job_init(), hb_cluster_job_initialize(), hb_deregister_by_args(), hb_deregister_by_pid(), hb_hostname_n_port_to_sockaddr(), hb_is_heartbeat_valid(), hb_kill_process(), hb_master_init(), hb_prepare_deactivate_heartbeat(), hb_process_init(), hb_process_master_request(), hb_reconfig_heartbeat(), hb_register_to_master(), hb_reload_config(), hb_resource_job_change_mode(), hb_resource_job_cleanup_all(), hb_resource_job_confirm_cleanup_all(), hb_resource_job_confirm_dereg(), hb_resource_job_confirm_start(), hb_resource_job_demote_confirm_shutdown(), hb_resource_job_demote_start_shutdown(), hb_resource_job_initialize(), hb_resource_job_proc_dereg(), hb_resource_job_proc_start(), hb_resource_send_changemode(), hb_thread_check_disk_failure(), hb_thread_cluster_reader(), hb_thread_master_reader(), heap_attrinfo_start_with_btid(), heap_attrinfo_start_with_index(), heap_attrinfo_transform_to_disk_internal(), heap_capacity_next_scan(), heap_class_get_partition_info(), heap_create(), heap_create_internal(), heap_delete_hfid_from_cache(), heap_delete_logical(), heap_destroy_newly_created(), heap_eval_function_index(), heap_get_btid_from_index_name(), heap_get_class_partitions(), heap_get_class_subclasses(), heap_get_class_supers(), heap_get_class_tde_algorithm(), heap_get_index_with_name(), heap_get_partition_attributes(), heap_get_partitions_from_subclasses(), heap_get_referenced_by(), heap_header_capacity_start_scan(), heap_header_next_scan(), heap_init_func_pred_unpack_info(), heap_insert_logical(), heap_midxkey_key_generate(), heap_midxkey_key_get(), heap_object_upgrade_domain(), heap_prepare_get_context(), heap_reclaim_addresses(), heap_remove_page_on_vacuum(), heap_reuse(), heap_stats_find_best_page(), heap_stats_update(), heap_vpid_alloc(), heap_vpid_remove(), help_trigger_names(), ifmt_numeric_value(), index_attrs_to_string(), inherit_constraint(), ini_table_new(), object_description::init(), init_update_data(), init_user_locales(), insert_ha_apply_info(), insert_local(), insert_object_attr(), insert_subquery_results(), install_new_representation(), is_replace_or_odku_allowed(), is_server_insert_allowed(), is_server_update_allowed(), itoa_print(), its_deleted(), jsp_add_stored_procedure(), jsp_add_stored_procedure_argument(), jsp_alter_stored_procedure(), jsp_call_from_server(), jsp_call_stored_procedure(), jsp_do_call_stored_procedure(), jsp_execute_stored_procedure(), jsp_start_server(), killtran(), ko_date_value(), ko_time_value(), la_add_node_into_la_commit_list(), la_apply_commit_list(), la_apply_delete_log(), la_apply_insert_log(), la_apply_log_file(), la_apply_repl_log(), la_apply_statement_log(), la_apply_update_log(), la_cache_buffer_replace(), la_change_state(), la_check_mem_size(), la_check_time_commit(), la_commit_transaction(), la_create_repl_filter(), la_delay_replica(), la_disk_to_obj(), la_expand_cache_log_buffer(), la_fetch_log_hdr(), la_find_archive_num(), la_find_log_pagesize(), la_find_required_lsa(), la_flush_repl_items(), la_get_current(), la_get_ha_apply_info(), la_get_ha_server_state(), la_get_log_data(), la_get_next_update_log(), la_get_overflow_recdes(), la_get_range_of_archive(), la_get_recdes(), la_get_relocation_recdes(), la_get_undoredo_diff(), la_init_cache_log_buffer(), la_init_repl_lists(), la_lock_dbname(), la_log_commit(), la_log_copy_fromlog(), la_log_fetch(), la_log_fetch_from_archive(), la_log_page_check(), la_log_record_process(), la_make_repl_item(), la_remove_archive_logs(), la_repl_add_object(), la_retrieve_eot_time(), la_shutdown(), la_unlock_dbname(), la_update_query_execute(), la_update_query_execute_with_values(), lang_init(), lang_load_library(), ldr_compare_attribute_with_meta(), ldr_compare_storage_order(), ldr_exec_query_from_file(), lf_initialize_transaction_systems(), lf_tran_system_init(), link_list_add(), load_console_conv_data(), load_unicode_data(), loaddb_internal(), local_am_pm_value(), locale_check_and_set_default_files(), locale_prepare_C_file(), locale_save_to_C_file(), locator_add_or_remove_index_internal(), locator_all_reference_lockset(), locator_assign_all_permanent_oids(), locator_check_btree_entries(), locator_check_class_names(), locator_check_class_on_heap(), locator_check_fk_validity(), locator_check_foreign_key(), locator_check_object_and_get_class(), locator_check_unique_btree_entries(), locator_delete_force_internal(), locator_delete_lob_force(), locator_find_lockset_missing_class_oids(), locator_flush_for_multi_update(), locator_force_for_multi_update(), locator_guess_sub_classes(), locator_initialize(), locator_is_class(), locator_lock(), locator_lock_and_get_object_internal(), locator_lock_set(), locator_lockhint_classes(), locator_move_record(), locator_permoid_class_name(), locator_prefetch_index_page(), locator_prefetch_index_page_internal(), locator_remove_class(), locator_repl_flush_all(), locator_repl_mflush(), locator_update_force(), locator_update_index(), locator_upgrade_instances_domain(), lock_classes_lock_hint(), lock_detect_local_deadlock(), lock_initialize(), lock_subclasses(), lock_subclasses_internal(), lock_supers(), lock_supers_drop(), lockhint_subclasses(), log_2pc_attach_global_tran(), log_active_log_header_next_scan(), log_active_log_header_start_scan(), log_archive_log_header_next_scan(), log_archive_log_header_start_scan(), log_checkpoint(), log_converter(), log_create_internal(), log_does_active_user_exist(), log_find_end_log(), log_initialize_internal(), log_startof_nxrec(), log_top(), log_top_query(), log_top_tran(), logpb_archive_active_log(), logpb_background_archiving(), logpb_backup(), logpb_copy_database(), logpb_fetch_header_from_active_log(), logpb_find_header_parameters(), logpb_flush_all_append_pages(), logpb_flush_page(), logpb_initialize_flush_info(), logpb_initialize_pool(), logpb_read_page_from_file(), logpb_recreate_volume_info(), logpb_rename_all_volumes_files(), logpb_restore(), logtb_define_trantable_log_latch(), logtb_delete_global_unique_stats(), logtb_descriptors_start_scan(), logtb_expand_trantable(), logtb_get_pack_tran_table(), logtb_get_trans_info(), logtb_initialize_mvcc_testing(), logtb_reflect_global_unique_stats_to_btree(), logtb_tran_update_unique_stats(), logwr_get_log_pages(), logwr_log_ha_filestat_to_string(), main(), make_cst_item_value(), MCAddMsg(), MCAddSet(), MCDelMsg(), MCDelSet(), MCReadCat(), merge_trigger_list(), method_clear_scan_buffer(), method_invoke_for_server(), method_open_scan(), method_receive_results_for_stand_alone(), method_send_eof_to_server(), method_send_error_to_server(), method_send_value_to_server(), mfmt_value(), ml_add(), ml_append(), ml_ext_add(), move_n_days(), mq_check_authorization_path_entities(), mq_evaluate_check_option(), mq_evaluate_expression(), mq_evaluate_expression_having_serial(), mq_fetch_select_for_real_class_update(), mq_get_attribute(), mq_get_expression(), mq_replace_virtual_oid_with_real_oid(), mq_update_attribute(), mr_data_cmpdisk_varbit(), mr_data_lengthval_error(), mr_data_lengthval_object(), mr_data_writeval_object(), mr_getmem_json(), mr_getmem_money(), mr_getmem_multiset(), mr_getmem_numeric(), mr_getmem_object(), mr_getmem_sequence(), mr_getmem_set(), mr_getmem_string(), mr_getmem_timestampltz(), mr_getmem_timestamptz(), mr_getmem_utime(), mr_getmem_varbit(), mr_getmem_varnchar(), mr_setmem_bit(), mr_setmem_char(), mr_setmem_json(), mr_setmem_nchar(), mr_setmem_numeric(), mr_setmem_set(), mr_setmem_string(), mr_setmem_varbit(), mr_setmem_varnchar(), mr_setval_bit(), mr_setval_char(), mr_setval_date(), mr_setval_datetime(), mr_setval_datetimeltz(), mr_setval_datetimetz(), mr_setval_json(), mr_setval_midxkey(), mr_setval_money(), mr_setval_nchar(), mr_setval_numeric(), mr_setval_object(), mr_setval_set_internal(), mr_setval_string(), mr_setval_time(), mr_setval_timestampltz(), mr_setval_timestamptz(), mr_setval_utime(), mr_setval_varbit(), mr_setval_varnchar(), mr_setval_vobj(), mr_writeval_nchar_internal(), msleep(), net_client_check_log_header(), net_client_get_next_log_pages(), net_client_init(), net_client_ping_server(), net_client_ping_server_with_handshake(), net_client_receive_action(), net_client_recv_copyarea(), net_client_request(), net_client_request2(), net_client_request2_no_malloc(), net_client_request_2recv_copyarea(), net_client_request_3_data(), net_client_request_3_data_recv_copyarea(), net_client_request_3recv_copyarea(), net_client_request_internal(), net_client_request_no_reply(), net_client_request_recv_copyarea(), net_client_request_recv_stream(), net_client_request_with_callback(), net_client_request_with_logwr_context(), net_client_send_data(), net_server_start(), nlist_add(), nlist_append(), num_fmt_print(), obj_assign_value(), obj_class_lock(), obj_copy(), obj_delete(), obj_desc_get(), obj_desc_send_array(), obj_desc_send_array_quick(), obj_desc_send_list(), obj_desc_send_va(), obj_desc_set(), obj_find_object_by_cons_and_key(), obj_get(), obj_get_att(), obj_get_path(), obj_get_shared(), obj_get_temp(), obj_get_value(), obj_inst_lock(), obj_locate_attribute(), obj_send_array(), obj_send_list(), obj_send_method_array(), obj_send_method_list(), obj_send_method_va(), obj_send_va(), obj_set(), obj_set_att(), obj_set_shared(), obj_set_temp(), object_to_trigger(), obt_apply_assignment(), obt_apply_assignments(), obt_area_init(), obt_assign(), obt_assign_obt(), obt_check_missing_assignments(), obt_convert_set_templates(), obt_desc_set(), obt_final_check(), obt_final_check_set(), obt_find_attribute(), obt_set(), obt_update_internal(), open_file(), optimize_sets(), or_cl_get_prop_nocopy(), or_class_tde_algorithm(), or_get_all_representation(), or_get_constraint_comment(), or_get_domain_internal(), or_get_enumeration(), or_get_hierarchy_helper(), or_get_unique_hierarchy(), or_install_btids(), or_install_btids_filter_pred(), or_install_btids_function_info(), or_mvcc_add_header(), or_mvcc_set_header(), or_packed_set_length(), or_put_monetary(), or_put_set(), or_replace_chn(), or_unpack_unbound_listid(), orc_diskrep_from_record(), orc_subclasses_from_record(), orc_superclasses_from_record(), otable_insert(), otable_map_reserved(), otable_prepare(), otable_reserve(), cubload::load_args::pack(), parse_bigint(), parse_int(), partition_attrinfo_get_key(), partition_cache_init(), partition_find_inherited_btid(), partition_find_partition_for_record(), partition_find_root_class_oid(), partition_get_partition_oids(), partition_get_position_in_key(), partition_get_value_from_inarith(), partition_get_value_from_key(), partition_get_value_from_regu_var(), partition_load_aggregate_helper(), partition_load_partition_predicate(), partition_load_pruning_context(), partition_prune_heap_scan(), partition_prune_index_scan(), partition_prune_insert(), partition_prune_partition_index(), partition_prune_range(), partition_prune_spec(), partition_prune_unique_btid(), partition_prune_update(), peekmem_elo(), perfmon_initialize(), pgbuf_bcb_flush_with_wal(), pgbuf_flush_checkpoint(), pgbuf_flush_chkpt_seq_list(), pgbuf_flush_neighbor_safe(), pgbuf_flush_page_and_neighbors_fb(), pgbuf_flush_seq_list(), pgbuf_flush_victim_candidates(), pgbuf_initialize(), pgbuf_start_scan(), populate_auto_increment(), pr_do_db_value_string_compression(), pr_free_ext_value(), pr_free_value(), pr_midxkey_add_elements(), pr_midxkey_compare_element(), pr_midxkey_get_element_internal(), pr_midxkey_get_element_offset(), print_quoted_str(), print_result_with_sort(), prior_lsa_alloc_and_copy_crumbs(), prior_lsa_gen_undoredo_record_from_crumbs(), prm_check_environment(), prm_check_range(), prm_load_by_section(), prm_print(), prm_read_and_parse_ini_file(), prm_set(), process_activate_heartbeat(), process_class(), process_deact_confirm_no_server(), process_deact_confirm_stop_all(), process_deact_stop_all(), process_deactivate_heartbeat(), process_ha_deregister_by_args(), process_ha_deregister_by_pid(), process_ha_start_util_process(), process_is_registered_proc(), process_object(), process_reconfig_heartbeat(), process_set(), process_value(), propagate_revoke(), proxy_cas_alloc_by_ctx(), proxy_cas_execute_internal(), proxy_cas_io_write(), proxy_client_add_waiter_by_shard(), proxy_client_check_waiter_and_wakeup(), proxy_client_execute_internal(), proxy_client_io_free(), proxy_client_io_initialize(), proxy_client_io_write(), proxy_context_add_stmt(), proxy_context_free(), proxy_context_initialize(), proxy_context_send_error(), proxy_convert_error_code(), proxy_handler_initialize(), proxy_handler_process_cas_conn_error(), proxy_handler_process_cas_response(), proxy_handler_process_client_conn_error(), proxy_handler_process_client_request(), proxy_io_cas_lsnr(), proxy_io_initialize(), proxy_io_make_check_cas(), proxy_io_make_client_proxy_alive(), proxy_io_make_close_req_handle_ok(), proxy_io_make_end_tran_request(), proxy_io_make_error_msg(), proxy_io_make_ex_get_int(), proxy_io_make_get_db_version(), proxy_io_make_shard_info(), proxy_io_register_to_broker(), proxy_process_cas_conn_error(), proxy_process_cas_message(), proxy_process_cas_read_error(), proxy_process_cas_response(), proxy_process_cas_write_error(), proxy_process_client_conn_error(), proxy_process_client_message(), proxy_process_client_read_error(), proxy_process_client_register(), proxy_process_client_request(), proxy_process_client_write_error(), proxy_send_prepared_stmt_to_client(), proxy_send_request_to_cas(), proxy_send_request_to_cas_with_new_event(), proxy_send_response_to_client(), proxy_send_response_to_client_with_new_event(), proxy_shard_io_initialize(), proxy_socket_io_add(), proxy_socket_io_new_client(), proxy_socket_io_read_from_cas_first(), proxy_socket_io_read_from_cas_next(), proxy_socket_io_read_from_client_first(), proxy_socket_io_read_from_client_next(), proxy_socket_io_read_internal(), proxy_socket_io_write_internal(), proxy_socket_set_write_event(), proxy_wakeup_context_by_shard(), proxy_wakeup_context_by_statement(), pruningset_to_spec_list(), pt_append_omitted_on_update_expr_assignments(), pt_bind_names_post(), pt_bind_set_type(), pt_check_alter_partition(), pt_check_constraint(), pt_check_create_entity(), pt_check_cume_dist_percent_rank_order_by(), pt_check_default_vclass_query_spec(), pt_check_expr_collation(), pt_check_group_concat_order_by(), pt_check_order_by(), pt_check_partition_values(), pt_check_partitions(), pt_check_range_partition_strict_increasing(), pt_check_recursive_expr_collation(), pt_check_show_index(), pt_check_table_in_show_heap(), pt_coerce_expr_arguments(), pt_coerce_partition_value_with_data_type(), pt_coerce_range_expr_arguments(), pt_common_collation(), pt_difference_sets(), pt_eval_expr_type(), pt_eval_path_expr(), pt_evaluate_db_value_expr(), pt_evaluate_function(), pt_evaluate_function_w_args(), pt_evaluate_tree_internal(), pt_exec_trigger_stmt(), pt_find_lck_class_from_partition(), pt_find_omitted_default_expr(), pt_find_value_of_label(), pt_fix_first_term_func_index_for_iss(), pt_gather_constraints(), pt_gen_isnull_preds(), pt_get_assignment_lists(), pt_get_collation_info_for_collection_type(), pt_get_collation_of_collection(), pt_get_enumeration_from_data_type(), pt_get_node_title(), pt_get_query_limit_from_limit(), pt_get_query_limit_from_orderby_for(), pt_get_query_limit_value(), pt_get_select_query_columns(), pt_has_modified_class_helper(), pt_help_show_create_table(), pt_make_method_call(), pt_make_outer_select_for_show_columns(), pt_make_query_show_columns(), pt_make_query_show_index(), pt_make_query_showstmt(), pt_node_data_type_to_db_domain(), pt_node_list_to_array(), pt_node_to_db_domain(), pt_print_db_value(), pt_print_node_value(), pt_product_sets(), pt_resolve_showstmt_args_named(), pt_resolve_showstmt_args_unnamed(), pt_resolve_vclass_args(), pt_semantic_quick_check_node(), pt_serial_to_xasl_class_oid_list(), pt_set_default_data_type(), pt_set_elements_to_value(), pt_set_table_to_db(), pt_spec_to_xasl_class_oid_list(), pt_to_delete_xasl(), pt_to_insert_xasl(), pt_to_key_limit(), pt_to_list_key(), pt_to_merge_insert_xasl(), pt_to_merge_update_xasl(), pt_to_merge_xasl(), pt_to_odku_info(), pt_to_pred_expr(), pt_to_pred_expr_with_arg(), pt_to_range_key(), pt_to_rangelist_key(), pt_to_single_key(), pt_to_update_xasl(), pt_union_sets(), put_attributes(), qdata_add_bigint_to_datetime(), qdata_add_bigint_to_time(), qdata_add_datetimetz_to_dbval(), qdata_add_dbval(), qdata_add_int_to_datetime(), qdata_add_short_to_datetime(), qdata_aggregate_accumulator_to_accumulator(), qdata_aggregate_interpolation(), qdata_aggregate_value_to_accumulator(), qdata_analytic_interpolation(), qdata_apply_interpolation_function_coercion(), qdata_benchmark(), qdata_cast_to_domain(), qdata_coerce_result_to_domain(), qdata_concatenate_dbval(), qdata_convert_dbvals_to_set(), qdata_convert_table_to_set(), qdata_divide_dbval(), qdata_evaluate_aggregate_hierarchy(), qdata_evaluate_aggregate_list(), qdata_evaluate_analytic_func(), qdata_evaluate_sys_connect_by_path(), qdata_finalize_aggregate_list(), qdata_finalize_analytic_func(), qdata_get_cardinality(), qdata_get_interpolation_function_result(), qdata_insert_substring_function(), qdata_interpolation_function_values(), qdata_list_dbs(), qdata_multiply_dbval(), qdata_save_agg_hentry_to_list(), qdata_strcat_dbval(), qdata_subtract_datetime_to_int(), qdata_subtract_datetime_to_int_asymmetry(), qdata_subtract_dbval(), qdata_subtract_utime_to_bigint_asymmetry(), qdata_subtract_utime_to_int_asymmetry(), qdata_subtract_utime_to_short_asymmetry(), qdata_tuple_to_values_array(), qdata_update_agg_interpolation_func_value_and_domain(), qdata_update_interpolation_func_value_and_domain(), qdump_print_arith(), qexec_add_tuple_to_topn(), qexec_analytic_evaluate_interpolation_function(), qexec_analytic_evaluate_offset_function(), qexec_analytic_start_group(), qexec_create_delete_lob_info(), qexec_create_internal_classes(), qexec_evaluate_aggregates_optimize(), qexec_evaluate_partition_aggregates(), qexec_execute_build_columns(), qexec_execute_build_indexes(), qexec_execute_delete(), qexec_execute_do_stmt(), qexec_execute_duplicate_key_update(), qexec_execute_increment(), qexec_execute_insert(), qexec_execute_mainblock(), qexec_execute_mainblock_internal(), qexec_execute_merge(), qexec_execute_update(), qexec_fill_sort_limit(), qexec_for_update_set_class_locks(), qexec_gby_start_group(), qexec_get_orderbynum_upper_bound(), qexec_init_agg_hierarchy_helpers(), qexec_init_instnum_val(), qexec_init_next_partition(), qexec_intprt_fnc(), qexec_ordby_put_next(), qexec_orderby_distinct(), qexec_orderby_distinct_by_sorting(), qexec_process_partition_unique_stats(), qexec_process_unique_stats(), qexec_prune_spec(), qexec_resolve_domains_for_aggregation(), qexec_set_class_locks(), qexec_set_pseudocolumns_val_pointers(), qexec_setup_topn_proc(), qexec_topn_tuples_to_list_id(), qexec_upddel_setup_current_class(), qfile_add_two_tuple(), qfile_combine_two_list(), qfile_compare_with_interpolation_domain(), qfile_get_list_file_page(), qfile_initialize_list_cache(), qfile_put_next_sort_item(), qfile_set_tuple_column_value(), qfile_union_list(), qmgr_prepare_query(), qo_check_iscan_for_multi_range_opt(), qo_check_join_for_multi_range_opt(), qo_check_subplans_for_multi_range_opt(), qo_env_init(), qo_find_subplan_using_multi_range_opt(), qo_get_xasl_index_info(), qo_reduce_order_by(), qo_reduce_order_by_for(), qo_set_value_to_range_list(), qstr_make_typed_string(), query_multi_range_opt_check_set_sort_col(), read_conf(), redistribute_partition_data(), register_fn_get_shard_key(), register_user_trigger(), remove_class_triggers(), resolve_candidates(), resolve_class_domain(), cubbase::restrack_set_error(), round_date(), run_user_triggers(), sacl_reload(), sbtree_find_multi_uniques(), sbtree_get_key_type(), sc_set_current_schema(), scan_dump_key_into_tuple(), scan_open_showstmt_scan(), sch_exported_keys_or_cross_reference(), sch_imported_keys(), sch_trigger(), search_offset(), serial_get_attrid(), serial_get_current_value(), serial_get_next_cached_value(), serial_get_next_value(), serial_load_attribute_info_of_db_serial(), session_add_variable(), session_check_session(), session_create_prepared_statement(), session_get_session_state(), session_state_destroy(), set_add_element(), set_area_init(), set_cardinality(), set_check_domain(), set_coerce(), set_compare(), set_compare_order(), set_convert_oids_to_objects(), set_copy(), set_disconnect(), set_drop_element(), set_drop_seq_element(), set_filter(), set_find_seq_element(), set_fprint(), set_get_domain(), set_get_element(), set_get_element_nocopy(), set_get_setobj(), set_get_type(), set_has_null(), set_insert_element(), set_isempty(), set_ismember(), set_iso_level(), set_issome(), set_iterate(), set_new_element(), set_op(), set_optimize(), set_prepare_info_into_list(), set_put_element(), set_referenced_subclasses(), set_seq_compare(), set_size(), setobj_add_element(), setobj_cardinality(), setobj_coerce(), setobj_compare(), setobj_compare_order(), setobj_convert_oids_to_objects(), setobj_copy(), setobj_difference(), setobj_drop_element(), setobj_drop_seq_element(), setobj_filter(), setobj_get_element(), setobj_get_element_ptr(), setobj_insert_element(), setobj_intersection(), setobj_put_element(), setobj_put_value(), setobj_release(), setobj_sort(), setobj_union(), sfile_apply_tde_to_class_files(), shard_cas_main(), shard_metadata_validate(), shard_metadata_validate_key(), shard_shm_check_max_file_open_limit(), shard_stmt_add_srv_h_id_for_shard_cas(), shard_stmt_change_shard_val_to_id(), shard_stmt_check_waiter_and_wakeup(), shard_stmt_new_internal(), shard_stmt_pin(), shard_stmt_rewrite_sql(), shard_stmt_unpin(), shf_create(), shf_destroy(), shf_destroy_when_new(), shf_heap_reclaim_addresses(), showstmt_array_end_scan(), showstmt_end_scan(), showstmt_metadata_init(), showstmt_start_scan(), signal_evaluation_error(), sl_write_statement_sql(), slocator_demote_class_lock(), slocator_get_reserved_class_name_oid(), slog_add_lob_locator(), slog_change_state_of_locator(), slog_checkpoint(), slog_drop_lob_locator(), slogtb_get_pack_tran_table(), slogwr_get_log_pages(), sm_add_constraint(), sm_add_secondary_index_on_partition(), sm_add_trigger(), sm_att_default_value(), sm_att_info(), sm_build_function_nlist(), sm_check_catalog_rep_dir(), sm_check_index_exist(), sm_check_reuse_oid_class(), sm_class_check_uniques(), sm_class_constraints(), sm_class_has_triggers(), sm_class_has_unique_constraint(), sm_clean_class(), sm_default_constraint_name(), sm_delete_class_mop(), sm_destroy_representations(), sm_drop_cascade_foreign_key(), sm_drop_constraint(), sm_drop_index(), sm_drop_trigger(), sm_dynamic_link_class(), sm_exist_index(), sm_expand_method_files(), sm_fetch_all_base_classes(), sm_filter_domain(), sm_find_index(), sm_find_subclass_in_hierarchy(), sm_flush_and_decache_objects(), sm_flush_and_decache_objects_internal(), sm_flush_for_multi_update(), sm_force_method_link(), sm_free_function_nlist(), sm_get_att_name(), sm_get_attribute_descriptor(), sm_get_class_collation(), sm_get_class_repid(), sm_get_class_tde_algorithm(), sm_get_descriptor_component(), sm_get_index(), sm_get_method_descriptor(), sm_get_trigger_cache(), sm_invalidate_trigger_cache(), sm_is_partition(), sm_link_method(), sm_link_methods(), sm_link_static_method(), sm_link_static_methods(), sm_load_online_index(), sm_mark_system_class(), sm_partitioned_class_type(), sm_prelink_methods(), sm_rename_class(), sm_set_class_collation(), sm_set_class_comment(), sm_set_class_flag(), sm_set_class_tde_algorithm(), sm_split_loader_commands(), sm_touch_class(), sm_truncate_class(), sm_truncate_using_delete(), sm_update_all_catalog_statistics(), sm_update_all_statistics(), sm_update_catalog_statistics(), sm_update_statistics(), sm_virtual_queries(), smt_add_attribute_w_dflt_w_order(), smt_add_constraint(), smt_add_constraint_to_property(), smt_add_method_any(), smt_add_method_file(), smt_add_query_spec(), smt_add_set_argument_domain(), smt_add_set_attribute_domain(), smt_add_super(), smt_assign_argument_domain(), smt_change_attribute_w_dflt_w_order(), smt_change_class_shared_attribute_domain(), smt_change_constraint_comment(), smt_change_constraint_status(), smt_change_method_implementation(), smt_change_query_spec(), smt_check_foreign_key(), smt_check_index_exist(), smt_delete_any(), smt_delete_set_attribute_domain(), smt_delete_super(), smt_delete_super_connect(), smt_drop_constraint(), smt_drop_constraint_from_property(), smt_drop_method_file(), smt_drop_query_spec(), smt_find_attribute(), smt_find_owner_of_constraint(), smt_is_change_status_allowed(), smt_quit(), smt_rename_any(), smt_rename_method_file(), smt_reset_method_files(), smt_reset_query_spec(), smt_set_attribute_default(), smt_set_attribute_on_update(), sort_constr_info_list(), sort_exphase_merge(), sort_exphase_merge_elim_dup(), sort_inphase_sort(), sort_listfile(), sort_run_flush(), sp_create_parser_hint(), sp_get_bind_type_and_value(), sp_parse_sql(), sp_parse_sql_internal(), sp_process_token(), spage_header_start_scan(), spage_slots_start_scan(), sqfile_get_list_file_page(), sql_list_make(), sqmgr_prepare_query(), sqst_update_all_statistics(), sqst_update_statistics(), ssession_create_prepared_statement(), ssession_find_or_create_session(), ssession_get_prepared_statement(), starts_with(), stats_get_statistics(), stats_update_all_statistics(), stats_update_partitioned_statistics(), stats_update_statistics(), stde_change_mk_on_server(), stde_get_mk_info(), cubload::server_object_loader::stop_scancache(), str_to_log_date_format(), stx_build_access_spec_type(), stx_build_aggregate_type(), stx_build_analytic_eval_type(), stx_build_analytic_type(), stx_build_arith_type(), stx_build_buildlist_proc(), stx_build_cls_spec_type(), stx_build_connectby_proc(), stx_build_cte_proc(), stx_build_delete_proc(), stx_build_filter_pred_node(), stx_build_func_pred(), stx_build_insert_proc(), stx_build_like_eval_term(), stx_build_list_id(), stx_build_list_spec_type(), stx_build_ls_merge_info(), stx_build_merge_proc(), stx_build_mergelist_proc(), stx_build_method_sig(), stx_build_method_sig_list(), stx_build_pred(), stx_build_regu_value_list(), stx_build_regu_variable(), stx_build_rlike_eval_term(), stx_build_showstmt_spec_type(), stx_build_update_proc(), stx_build_xasl_node(), stx_restore_key_range_array(), stx_unpack_regu_variable_value(), sysprm_check_range(), sysprm_generate_new_value(), sysprm_get_force_server_parameters(), sysprm_get_param_range(), sysprm_init_intl_param(), sysprm_obtain_parameters(), sysprm_print_sysprm_value(), sysprm_set_error(), sysprm_unpack_assign_values(), sysprm_unpack_session_parameters(), tde(), tde_change_mk_on_server(), tde_get_mk_file_path(), tde_get_mk_info(), test_area_proc(), test_area_proc_1(), test_area_proc_2(), text_print(), tf_attribute_default_expr_to_property(), tf_do_fixup(), thread_start_scan(), thread_suspend_timeout_wakeup_and_unlock_entry(), thread_suspend_with_other_mutex(), cubload::to_db_generic_char(), tp_domain_add(), tp_domain_attach(), tp_domain_check_class(), tp_domain_copy(), tp_domain_copy_enumeration(), tp_domain_filter_list(), tp_domain_status_er_set(), tp_enumeration_to_varchar(), tp_hex_str_to_bi(), tp_scientific_str_to_bi(), tr_add_cache_trigger(), tr_after_object(), tr_before_object(), tr_check_authorization(), tr_check_commit_triggers(), tr_create_trigger(), tr_delete_triggers_for_class(), tr_drop_cache_trigger(), tr_drop_deferred_activities(), tr_drop_trigger(), tr_drop_trigger_internal(), tr_dump_selective_triggers(), tr_dump_trigger(), tr_execute_activities(), tr_execute_deferred_activities(), tr_find_all_triggers(), tr_find_event_triggers(), tr_get_cache_objects(), tr_has_user_trigger(), tr_is_trigger(), tr_merge_schema_cache(), tr_prepare_class(), tr_prepare_statement(), tr_rename_trigger(), tr_set_comment(), tr_set_priority(), tr_set_status(), tr_status_as_string(), tr_trigger_action(), tr_trigger_action_time(), tr_trigger_action_type(), tr_trigger_attribute(), tr_trigger_class(), tr_trigger_comment(), tr_trigger_condition(), tr_trigger_condition_time(), tr_trigger_event(), tr_trigger_name(), tr_trigger_priority(), tr_trigger_status(), tr_unmap_trigger(), tr_update_user_cache(), tr_validate_schema_cache(), tranlist(), transfer_disk_structures(), trigger_table_add(), trigger_table_drop(), trigger_table_find(), trigger_table_rename(), trigger_to_object(), truncate_date(), truncate_need_repl_log(), tz_datetimeltz_to_local(), tz_full_timezones_start_scan(), tz_get_timezone_offset(), tz_load_library(), tz_timezones_start_scan(), tzc_compute_timezone_checksum(), uci_commit(), uci_connect(), uci_execute_immediate(), uci_get_db_value(), uci_get_next_column(), uci_get_value(), uci_object_describe(), uci_object_fetch(), uci_open_cs(), uci_prepare(), uci_rollback(), uci_static(), unicode_process_alphabet(), unloaddb(), unpack_domain(), unpack_domain_2(), unregister_user_trigger(), update_at_server(), page_key_boundary::update_boundary_eq(), page_key_boundary::update_boundary_gt_or_eq(), page_key_boundary::update_boundary_lt(), update_cache(), update_check_for_constraints(), update_class(), update_class_attributes(), update_fk_ref_partitioned_class(), update_foreign_key_ref(), update_hash(), update_object_attribute(), update_object_by_oid(), update_object_tuple(), update_objs_for_list_file(), update_real_class(), update_subclasses(), update_supers(), update_supers_drop(), us_date_value(), us_time_value(), util_get_ha_parameters(), util_make_ha_conf(), util_msec_to_time_string(), utility_load_print_error(), vacuum_fetch_log_page(), vacuum_find_dropped_file(), vacuum_initialize(), vacuum_log_prefetch_vacuum_block(), vacuum_rv_notify_dropped_file(), vacuum_rv_redo_remove_ovf_insid(), vacuum_worker_allocate_resources(), validate_attribute_domain(), validate_template(), validate_trigger(), vid_att_in_obj_id(), vid_build_non_upd_object(), vid_compare_non_updatable_objects(), vid_fetch_instance(), vid_getall_mops(), vid_make_vobj(), vid_vobj_to_object(), vobj_compare(), write_results_to_stream(), ws_init(), ws_update_oid_and_class(), xboot_copy(), xbtree_add_index(), xbtree_find_multi_uniques(), xbtree_load_index(), xbtree_load_online_index(), xcache_insert(), xchksum_insert_repl_log_and_demote_table_lock(), xlocator_assign_oid_batch(), xlocator_delete_class_name(), xlocator_fetch(), xlocator_fetch_all(), xlocator_fetch_lockset(), xlocator_force(), xlocator_get_reserved_class_name_oid(), xlocator_lock_and_fetch_all(), xlocator_remove_class_from_index(), xlocator_rename_class_name(), xlocator_upgrade_instances_domain(), xlog_get_page_request_with_reply(), xlogtb_get_pack_tran_table(), xlogtb_kill_or_interrupt_tran(), xmalloc(), xml_create_subparser(), xrealloc(), xsession_get_prepared_statement(), xstats_update_all_statistics(), xstats_update_statistics(), and xstrdup().
static char* get_line (int fd) static
Definition at line 389 of file gencat.c.
References xmalloc(), and xrealloc().
Referenced by getmsg(), and MCParse().
static char* getmsg (int fd, char * cptr, char quote) static
Definition at line 498 of file gencat.c.
References error(), get_line(), i, NULL, strlen, warning(), wskip(), xmalloc(), and xrealloc().
Referenced by MCParse().
LIST_HEAD (static void warning (const char * , _setT)
Definition at line 166 of file gencat.c.
int main (int argc, char * argv[])
Definition at line 205 of file gencat.c.
References argv, err, getopt(), MCParse(), MCReadCat(), MCWriteCat(), NULL, optind, and usage().
void MCAddMsg (int msgId, const char * str)
Definition at line 1028 of file gencat.c.
References error(), _msgT::msgId, NL_MSGMAX, NULL, p, xmalloc(), and xstrdup().
Referenced by MCParse(), and MCReadCat().
void MCAddSet (int setId)
Definition at line 983 of file gencat.c.
References error(), NL_SETMAX, NULL, p, _setT::setId, and xmalloc().
Referenced by MCParse(), and MCReadCat().
void MCDelMsg (int msgId)
Definition at line 1109 of file gencat.c.
References error(), _msgT::msgId, _msgT::str, and warning().
Referenced by MCParse().
void MCDelSet (int setId)
Definition at line 1074 of file gencat.c.
References error(), NL_SETMAX, _msgT::str, and warning().
Referenced by MCParse().
void MCParse (int fd)
Definition at line 623 of file gencat.c.
References cskip(), get_line(), getmsg(), MCAddMsg(), MCAddSet(), MCDelMsg(), MCDelSet(), NL_SETD, _msgT::str, warning(), and wskip().
Referenced by main().
void MCReadCat (int fd)
Definition at line 738 of file gencat.c.
References _nls_set_hdr::__index, _nls_cat_hdr::__magic, _nls_cat_hdr::__mem, _nls_cat_hdr::__msg_hdr_offset, _nls_cat_hdr::__msg_txt_offset, _nls_msg_hdr::__msgno, _nls_set_hdr::__nmsgs, _nls_cat_hdr::__nsets, _nls_msg_hdr::__offset, _nls_set_hdr::__setno, _NLS_MAGIC, CORRUPT, err, error(), errx, for(), MCAddMsg(), MCAddSet(), ntohl(), and xmalloc().
Referenced by main().
void MCWriteCat (int fd)
Definition at line 882 of file gencat.c.
References _nls_set_hdr::__index, _nls_cat_hdr::__magic, _nls_cat_hdr::__mem, _nls_cat_hdr::__msg_hdr_offset, _nls_cat_hdr::__msg_txt_offset, _nls_msg_hdr::__msglen, _nls_msg_hdr::__msgno, _nls_set_hdr::__nmsgs, _nls_cat_hdr::__nsets, _nls_msg_hdr::__offset, _nls_set_hdr::__setno, _NLS_MAGIC, htonl(), _msgT::msgId, _msgT::str, strlen, and xmalloc().
Referenced by main().
static void warning (const char * cptr, const char * msg) static
Definition at line 310 of file gencat.c.
Referenced by cskip(), error(), getmsg(), MCDelMsg(), MCDelSet(), MCParse(), pt_check_constraint(), and wskip().
static char* wskip (char * cptr) static
Definition at line 472 of file gencat.c.
References warning().
Referenced by getmsg(), and MCParse().
static void* xmalloc (size_t len) static
Definition at line 338 of file gencat.c.
References error(), errx, NOMEMORY, and p.
Referenced by get_line(), getmsg(), MCAddMsg(), MCAddSet(), MCReadCat(), and MCWriteCat().
static void* xrealloc (void * ptr, size_t size) static
Definition at line 354 of file gencat.c.
References error(), errx, NOMEMORY, and NULL.
Referenced by get_line(), and getmsg().
static char* xstrdup (const char * str) static
Definition at line 373 of file gencat.c.
References error(), errx, NOMEMORY, and strdup().
Referenced by MCAddMsg().