CUBRID Engine: src/executables/generate_timezone.cpp File Reference
generate_timezone.cpp File Reference
#include "error_manager.h"
#include "tz_compile.h"
#include <cstring>
#include <iostream>
Functions
void usage (void)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 38 of file generate_timezone.cpp.
References assert, NO_ERROR, NULL, TZ_CHECKSUM_SIZE, TZ_GEN_TYPE_NEW, and usage().
void usage (void)
Definition at line 30 of file generate_timezone.cpp.
Referenced by get_args(), and main().