CUBRID Engine: src/base/ini_parser.h File Reference
ini_parser.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
Classes
struct ini_table
Typedefs
typedef struct ini_table INI_TABLE
Functions
INI_TABLE * ini_parser_load (const char *ininame)
void ini_parser_free (INI_TABLE *ini)
int ini_findsec (INI_TABLE *ini, const char *sec)
char * ini_getsecname (INI_TABLE *ini, int n, int *lineno)
int ini_hassec (const char *key)
int ini_seccmp (const char *key1, const char *key2)
const char * ini_getstr (INI_TABLE *ini, const char *sec, const char *key, const char *def, int *lineno)
int ini_getint (INI_TABLE *ini, const char *sec, const char *key, int def, int *lineno)
int ini_getuint (INI_TABLE *ini, const char *sec, const char *key, int def, int *lineno)
int ini_getuint_max (INI_TABLE *ini, const char *sec, const char *key, int def, int max, int *lineno)
int ini_gethex (INI_TABLE *ini, const char *sec, const char *key, int def, int *lineno)
float ini_getfloat (INI_TABLE *ini, const char *sec, const char *key, float def, int *lineno)
Typedef Documentation
typedef struct ini_table INI_TABLE
Definition at line 34 of file ini_parser.h.
Function Documentation
int ini_findsec (INI_TABLE * ini, const char * sec)
Definition at line 697 of file ini_parser.c.
References i, ini_table::key, NULL, and ini_table::size.
Referenced by broker_config_read_internal(), and get_master_shm_id().
float ini_getfloat (INI_TABLE * ini, const char * sec, const char * key, float def, int * lineno)
Definition at line 1020 of file ini_parser.c.
References ini_getstr(), INI_INVALID_KEY, and NULL.
int ini_gethex (INI_TABLE * ini, const char * sec, const char * key, int def, int * lineno)
Definition at line 993 of file ini_parser.c.
References ini_getstr(), INI_INVALID_KEY, and parse_int().
Referenced by broker_config_read_internal(), and get_master_shm_id().
int ini_getint (INI_TABLE * ini, const char * sec, const char * key, int def, int * lineno)
Definition at line 885 of file ini_parser.c.
References ini_getstr(), INI_INVALID_KEY, and parse_int().
Referenced by broker_config_read_internal(), and ini_getuint().
char* ini_getsecname (INI_TABLE * ini, int n, int * lineno)
Definition at line 729 of file ini_parser.c.
References i, ini_table::key, ini_table::lineno, NULL, and ini_table::size.
Referenced by broker_config_read_internal().
const char* ini_getstr (INI_TABLE * ini, const char * sec, const char * key, const char * def, int * lineno)
Definition at line 865 of file ini_parser.c.
References INI_BUFSIZ, and ini_get_internal().
Referenced by broker_config_read_internal(), ini_getfloat(), ini_gethex(), and ini_getint().
int ini_getuint (INI_TABLE * ini, const char * sec, const char * key, int def, int * lineno)
Definition at line 912 of file ini_parser.c.
References ini_getint(), ini_getuint(), and min.
Referenced by broker_config_read_internal(), ini_getuint(), and ini_getuint_max().
int ini_getuint_max (INI_TABLE * ini, const char * sec, const char * key, int def, int max, int * lineno)
Definition at line 968 of file ini_parser.c.
References ini_getuint(), and max.
Referenced by broker_config_read_internal().
int ini_hassec (const char * key)
Definition at line 772 of file ini_parser.c.
Referenced by prm_load_by_section().
void ini_parser_free (INI_TABLE * ini)
Definition at line 683 of file ini_parser.c.
References ini_table_free().
Referenced by broker_config_read_internal(), get_master_shm_id(), and prm_read_and_parse_ini_file().
INI_TABLE* ini_parser_load (const char * ininame)
Definition at line 569 of file ini_parser.c.
References char_isspace(), INI_BUFSIZ, ini_parse_line(), ini_table_free(), ini_table_new(), ini_table_set(), LINE_COMMENT, LINE_EMPTY, LINE_ERROR, LINE_SECTION, LINE_VALUE, NULL, and strlen.
Referenced by broker_config_read_internal(), get_master_shm_id(), and prm_read_and_parse_ini_file().
int ini_seccmp (const char * key1, const char * key2)
Definition at line 786 of file ini_parser.c.
References CAST_STRLEN, and strlen.
Referenced by prm_load_by_section().