CUBRID Engine: src/base/jisx0212.h File Reference
jisx0212.h File Reference
Functions
static int jisx0212_mbtowc (ucs4_t *pwc, const unsigned char *s, int n)
static int jisx0212_wctomb (unsigned char *r, ucs4_t wc, int n)
Variables
static const unsigned short jisx0212_2uni_page22 [81]
static const unsigned short jisx0212_2uni_page26 [188]
static const unsigned short jisx0212_2uni_page29 [275]
static const unsigned short jisx0212_2uni_page30 [5801]
static const unsigned short jisx0212_2charset [6067]
static const Summary16 jisx0212_uni2indx_page00 [70]
static const Summary16 jisx0212_uni2indx_page21 [3]
static const Summary16 jisx0212_uni2indx_page4e [1307]
static const Summary16 jisx0212_uni2indx_pageff [6]
Function Documentation
static int jisx0212_mbtowc (ucs4_t * pwc, const unsigned char * s, int n) static
Definition at line 917 of file jisx0212.h.
References i, jisx0212_2uni_page22, jisx0212_2uni_page26, jisx0212_2uni_page29, jisx0212_2uni_page30, RET_ILSEQ, and RET_TOOFEW.
Referenced by intl_euckr_to_iso88591(), and intl_euckr_to_utf8().
static int jisx0212_wctomb (unsigned char * r, ucs4_t wc, int n) static
Definition at line 2188 of file jisx0212.h.
References i, s_Summary16::indx, jisx0212_2charset, NULL, RET_ILUNI, RET_TOOSMALL, and s_Summary16::used.
Referenced by intl_iso88591_to_euckr(), and intl_utf8_to_euckr().
Variable Documentation
const unsigned short jisx0212_2charset[6067] static
Definition at line 976 of file jisx0212.h.
Referenced by jisx0212_wctomb().
const unsigned short jisx0212_2uni_page22[81] static
Initial value:
= {
  0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd,
  0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0x02d8, 0x02c7,
  0x00b8, 0x02d9, 0x02dd, 0x00af, 0x02db, 0x02da, 0xff5e, 0x0384,
  0x0385, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd,
  0xfffd, 0x00a1, 0x00a6, 0x00bf, 0xfffd, 0xfffd, 0xfffd, 0xfffd,
  0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd,
  0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd,
  0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd,
  0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd,
  0xfffd, 0xfffd, 0x00ba, 0x00aa, 0x00a9, 0x00ae, 0x2122, 0x00a4,
  0x2116,
}
Definition at line 25 of file jisx0212.h.
Referenced by jisx0212_mbtowc().
const unsigned short jisx0212_2uni_page26[188] static
Initial value:
= {
  0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd,
  0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd,
  0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd,
  0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd,
  0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd,
  0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd,
  0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd,
  0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd,
  0x0386, 0x0388, 0x0389, 0x038a, 0x03aa, 0xfffd, 0x038c, 0xfffd,
  0x038e, 0x03ab, 0xfffd, 0x038f, 0xfffd, 0xfffd, 0xfffd, 0xfffd,
  0x03ac, 0x03ad, 0x03ae, 0x03af, 0x03ca, 0x0390, 0x03cc, 0x03c2,
  0x03cd, 0x03cb, 0x03b0, 0x03ce, 0xfffd, 0xfffd,
  0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd,
  0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd,
  0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd,
  0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd,
  0xfffd, 0x0402, 0x0403, 0x0404, 0x0405, 0x0406, 0x0407, 0x0408,
  0x0409, 0x040a, 0x040b, 0x040c, 0x040e, 0x040f, 0xfffd, 0xfffd,
  0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd,
  0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd,
  0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd,
  0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd, 0xfffd,
  0xfffd, 0x0452, 0x0453, 0x0454, 0x0455, 0x0456, 0x0457, 0x0458,
  0x0459, 0x045a, 0x045b, 0x045c, 0x045e, 0x045f,
}
Definition at line 40 of file jisx0212.h.
Referenced by jisx0212_mbtowc().
const unsigned short jisx0212_2uni_page29[275] static
Definition at line 69 of file jisx0212.h.
Referenced by jisx0212_mbtowc().
const unsigned short jisx0212_2uni_page30[5801] static
Definition at line 110 of file jisx0212.h.
Referenced by jisx0212_mbtowc().
const Summary16 jisx0212_uni2indx_page00[70] static
Initial value:
= {
  {0, 0x0000}, {0, 0x0000}, {0, 0x0000}, {0, 0x0000},
  {0, 0x0000}, {0, 0x0000}, {0, 0x0000}, {0, 0x0000},
  {0, 0x0000}, {0, 0x0000}, {0, 0xc652}, {7, 0x8500},
  {10, 0xffff}, {26, 0xff7e}, {40, 0xffff}, {56, 0xff7f},
  {71, 0xffff}, {87, 0xffcf}, {101, 0xcff7}, {114, 0xffff},
  {130, 0x3fff}, {144, 0xffff}, {160, 0xffff}, {176, 0x7fff},
  {191, 0x0000}, {191, 0x0000}, {191, 0x0000}, {191, 0x0000},
  {191, 0xe000}, {194, 0x1fff}, {207, 0x0000}, {207, 0x0020},
  {208, 0x0000}, {208, 0x0000}, {208, 0x0000}, {208, 0x0000},
  {208, 0x0000}, {208, 0x0000}, {208, 0x0000}, {208, 0x0000},
  {208, 0x0000}, {208, 0x0000}, {208, 0x0000}, {208, 0x0000},
  {208, 0x0080}, {209, 0x2f00}, {214, 0x0000}, {214, 0x0000},
  {214, 0x0000}, {214, 0x0000}, {214, 0x0000}, {214, 0x0000},
  {214, 0x0000}, {214, 0x0000}, {214, 0x0000}, {214, 0x0000},
  {214, 0xd770}, {223, 0x0001}, {224, 0xfc00}, {230, 0x0001},
  {231, 0x7c04}, {237, 0x0000}, {237, 0x0000}, {237, 0x0000},
  {237, 0xdffc}, {250, 0x0000}, {250, 0x0000}, {250, 0x0000},
  {250, 0x0000}, {250, 0xdffc},
}
Definition at line 1738 of file jisx0212.h.
const Summary16 jisx0212_uni2indx_page21[3] static
Initial value:
= {
  {263, 0x0000}, {263, 0x0040}, {264, 0x0004},
}
Definition at line 1764 of file jisx0212.h.
const Summary16 jisx0212_uni2indx_page4e[1307] static
Definition at line 1769 of file jisx0212.h.
const Summary16 jisx0212_uni2indx_pageff[6] static
Initial value:
= {
  {6066, 0x0000}, {6066, 0x0000}, {6066, 0x0000}, {6066, 0x0000},
  {6066, 0x0000}, {6066, 0x4000},
}
Definition at line 2181 of file jisx0212.h.