CUBRID Engine: src/jsp/jsp_comm.h File Reference
jsp_comm.h File Reference
#include <sys/socket.h>
#include <vector>
#include <string>
#include "porting.h"
Classes
struct javasp_status_info
Typedefs
typedef struct javasp_status_info JAVASP_STATUS_INFO
Enumerations
enum SP_CODE {
SP_CODE_INVOKE = 0x01, SP_CODE_RESULT = 0x02, SP_CODE_ERROR = 0x04, SP_CODE_INTERNAL_JDBC = 0x08,
SP_CODE_DESTROY = 0x10, SP_CODE_UTIL_PING = 0xDE, SP_CODE_UTIL_STATUS = 0xEE, SP_CODE_UTIL_TERMINATE_THREAD = 0xFE,
SP_CODE_UTIL_TERMINATE_SERVER = 0xFF
}
Functions
SOCKET jsp_connect_server (int server_port)
void jsp_disconnect_server (const SOCKET sockfd)
int jsp_writen (SOCKET fd, const void *vptr, int n)
int jsp_readn (SOCKET fd, void *vptr, int n)
Typedef Documentation
typedef struct javasp_status_info JAVASP_STATUS_INFO
Definition at line 56 of file jsp_comm.h.
Enumeration Type Documentation
enum SP_CODE
Enumerator
SP_CODE_INVOKE
SP_CODE_RESULT
SP_CODE_ERROR
SP_CODE_INTERNAL_JDBC
SP_CODE_DESTROY
SP_CODE_UTIL_PING
SP_CODE_UTIL_STATUS
SP_CODE_UTIL_TERMINATE_THREAD
SP_CODE_UTIL_TERMINATE_SERVER
Definition at line 42 of file jsp_comm.h.
Function Documentation
SOCKET jsp_connect_server (int server_port)
Definition at line 58 of file jsp_comm.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, er_set(), er_set_with_oserror(), ER_SP_CANNOT_CONNECT_JVM, ERR_CSS_TCP_HOST_NAME_ERROR, htons(), INADDR_NONE, INVALID_SOCKET, IS_INVALID_SOCKET, NULL, and success().
Referenced by javasp_ping_server(), javasp_status_server(), javasp_stop_server(), and jsp_execute_stored_procedure().
void jsp_disconnect_server (const SOCKET sockfd)
Definition at line 135 of file jsp_comm.c.
Referenced by javasp_ping_server(), javasp_status_server(), javasp_stop_server(), jsp_close_connection(), jsp_execute_stored_procedure(), and jsp_send_destroy_request_all().
int jsp_readn (SOCKET fd, void * vptr, int n)
Definition at line 212 of file jsp_comm.c.
References ARG_FILE_LINE, ER_CSS_WINSOCK_STARTUP, ER_ERROR_SEVERITY, er_set(), err, and NULL.
Referenced by javasp_ping_server(), javasp_status_server(), jsp_alloc_response(), jsp_receive_response(), and jsp_send_destroy_request().
int jsp_writen (SOCKET fd, const void * vptr, int n)
Definition at line 160 of file jsp_comm.c.
Referenced by javasp_ping_server(), javasp_status_server(), javasp_stop_server(), jsp_send_call_request(), and jsp_send_destroy_request().