CUBRID Engine: src/jsp/jsp_sr.h File Reference
jsp_sr.h File Reference
Functions
int jsp_start_server (const char *server_name, const char *path, int port_number)
int jsp_server_port (void)
int jsp_jvm_is_loaded (void)
Function Documentation
int jsp_jvm_is_loaded (void)
Definition at line 774 of file jsp_sr.c.
References jvm, and NULL.
Referenced by conn_restart_client(), css_setup_server_loop(), and db_restart().
int jsp_server_port (void)
Definition at line 751 of file jsp_sr.c.
References boot_db_name(), javasp_read_info(), and sp_port.
Referenced by javasp_start_server(), jsp_get_server_port(), and sjsp_get_server_port().
int jsp_start_server (const char * server_name, const char * path, int port_number)
Definition at line 536 of file jsp_sr.c.
References ARG_FILE_LINE, assert, debug_flag, envvar_javadir_file(), envvar_root(), er_errid(), ER_ERROR_SEVERITY, er_has_error(), ER_OUT_OF_VIRTUAL_MEMORY, er_set(), ER_SP_ALREADY_EXIST, ER_SP_CANNOT_START_JVM, error(), jsp_create_java_vm(), jsp_tokenize_jvm_options(), jvm, JVM_CallStaticIntMethod, JVM_ExceptionOccurred, JVM_FindClass, JVM_GetStaticMethodID, JVM_NewObjectArray, JVM_NewStringUTF, JVM_SetObjectArrayElement, NO_ERROR, NULL, prm_get_integer_value(), prm_get_string_value(), PRM_ID_JAVA_STORED_PROCEDURE_DEBUG, PRM_ID_JAVA_STORED_PROCEDURE_JVM_OPTIONS, rel_build_number(), sp_port, and strdup().
Referenced by boot_restart_server(), and javasp_start_server().