CUBRID Engine: src/jsp/jsp_comm.c File Reference
jsp_comm.c File Reference
#include "config.h"
#include <assert.h>
#include <sys/types.h>
#include <sys/param.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <arpa/inet.h>
#include <errno.h>
#include <unistd.h>
#include <netdb.h>
#include "jsp_comm.h"
#include "porting.h"
#include "error_manager.h"
Functions
SOCKET jsp_connect_server (int server_port)
void jsp_disconnect_server (const SOCKET sockfd)
int jsp_writen (SOCKET fd, const void *vptr, int n)
int jsp_readn (SOCKET fd, void *vptr, int n)
Function Documentation
SOCKET jsp_connect_server (int server_port)
Definition at line 58 of file jsp_comm.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, er_set(), er_set_with_oserror(), ER_SP_CANNOT_CONNECT_JVM, ERR_CSS_TCP_HOST_NAME_ERROR, htons(), INADDR_NONE, INVALID_SOCKET, IS_INVALID_SOCKET, NULL, and success().
Referenced by javasp_ping_server(), javasp_status_server(), javasp_stop_server(), and jsp_execute_stored_procedure().
void jsp_disconnect_server (const SOCKET sockfd)
Definition at line 135 of file jsp_comm.c.
Referenced by javasp_ping_server(), javasp_status_server(), javasp_stop_server(), jsp_close_connection(), jsp_execute_stored_procedure(), and jsp_send_destroy_request_all().
int jsp_readn (SOCKET fd, void * vptr, int n)
Definition at line 212 of file jsp_comm.c.
References ARG_FILE_LINE, ER_CSS_WINSOCK_STARTUP, ER_ERROR_SEVERITY, er_set(), err, and NULL.
Referenced by javasp_ping_server(), javasp_status_server(), jsp_alloc_response(), jsp_receive_response(), and jsp_send_destroy_request().
int jsp_writen (SOCKET fd, const void * vptr, int n)
Definition at line 160 of file jsp_comm.c.
Referenced by javasp_ping_server(), javasp_status_server(), javasp_stop_server(), jsp_send_call_request(), and jsp_send_destroy_request().