CUBRID Engine: src/jsp/jsp_file.c File Reference
jsp_file.c File Reference
#include "jsp_file.h"
#include "porting.h"
#include "environment_variable.h"
#include <assert.h>
#include <errno.h>
#include <stdlib.h>
#include <stdio.h>
Functions
bool javasp_open_info_dir ()
FILE * javasp_open_info (const char *db_name, const char *mode)
bool javasp_get_info_file (char *buf, size_t len, const char *db_name)
bool javasp_get_error_file (char *buf, size_t len, const char *db_name)
bool javasp_get_log_file (char *buf, size_t len, const char *db_name)
bool javasp_read_info (const char *db_name, JAVASP_SERVER_INFO &info)
bool javasp_write_info (const char *db_name, JAVASP_SERVER_INFO info)
bool javasp_reset_info (const char *db_name)
Function Documentation
bool javasp_get_error_file (char * buf, size_t len, const char * db_name)
Definition at line 102 of file jsp_file.c.
References assert, and envvar_logdir_file().
bool javasp_get_info_file (char * buf, size_t len, const char * db_name)
Definition at line 87 of file jsp_file.c.
References assert, and envvar_vardir_file().
Referenced by javasp_start_server(), and main().
bool javasp_get_log_file (char * buf, size_t len, const char * db_name)
Definition at line 117 of file jsp_file.c.
References assert, and envvar_logdir_file().
FILE* javasp_open_info (const char * db_name, const char * mode)
Definition at line 72 of file jsp_file.c.
References envvar_vardir_file(), and NULL.
Referenced by javasp_read_info(), and javasp_write_info().
bool javasp_open_info_dir ()
Definition at line 41 of file jsp_file.c.
References cub_dirname_r(), and envvar_vardir_file().
Referenced by javasp_get_server_info(), and javasp_start_server().
bool javasp_read_info (const char * db_name, JAVASP_SERVER_INFO & info)
Definition at line 132 of file jsp_file.c.
References javasp_open_info(), NULL, javasp_server_info::pid, and javasp_server_info::port.
Referenced by javasp_get_server_info(), and jsp_server_port().
bool javasp_reset_info (const char * db_name)
Definition at line 163 of file jsp_file.c.
References javasp_write_info().
Referenced by javasp_stop_server().
bool javasp_write_info (const char * db_name, JAVASP_SERVER_INFO info)
Definition at line 148 of file jsp_file.c.
References javasp_open_info(), NULL, javasp_server_info::pid, and javasp_server_info::port.
Referenced by javasp_reset_info(), and javasp_start_server().