CUBRID Engine: src/jsp/jsp_cl.h File Reference
jsp_cl.h File Reference
#include "parse_tree.h"
Macros
#define SP_CLASS_NAME "_db_stored_procedure"
#define SP_ARG_CLASS_NAME "_db_stored_procedure_args"
#define SP_ATTR_NAME "sp_name"
#define SP_ATTR_SP_TYPE "sp_type"
#define SP_ATTR_RETURN_TYPE "return_type"
#define SP_ATTR_ARGS "args"
#define SP_ATTR_ARG_COUNT "arg_count"
#define SP_ATTR_LANG "lang"
#define SP_ATTR_TARGET "target"
#define SP_ATTR_OWNER "owner"
#define SP_ATTR_COMMENT "comment"
#define SP_ATTR_ARG_NAME "arg_name"
#define SP_ATTR_INDEX_OF_NAME "index_of"
#define SP_ATTR_DATA_TYPE "data_type"
#define SP_ATTR_MODE "mode"
#define SP_ATTR_ARG_COMMENT "comment"
Enumerations
enum SP_TYPE_ENUM { SP_TYPE_PROCEDURE = 1, SP_TYPE_FUNCTION }
enum SP_MODE_ENUM { SP_MODE_IN = 1, SP_MODE_OUT, SP_MODE_INOUT }
enum SP_LANG_ENUM { SP_LANG_JAVA = 1 }
Functions
int jsp_create_stored_procedure (PARSER_CONTEXT *parser, PT_NODE *statement)
int jsp_alter_stored_procedure (PARSER_CONTEXT *parser, PT_NODE *statement)
int jsp_drop_stored_procedure (PARSER_CONTEXT *parser, PT_NODE *statement)
int jsp_call_stored_procedure (PARSER_CONTEXT *parser, PT_NODE *statement)
int jsp_is_exist_stored_procedure (const char *name)
int jsp_get_return_type (const char *name)
void jsp_init (void)
void jsp_close_connection (void)
MOP jsp_find_stored_procedure (const char *name)
void jsp_set_prepare_call (void)
void jsp_unset_prepare_call (void)
int jsp_call_from_server (DB_VALUE *returnval, DB_VALUE **argarray, const char *name, const int arg_cnt)
void * jsp_get_db_result_set (int h_id)
void jsp_srv_handle_free (int h_id)
int jsp_send_destroy_request_all ()
int jsp_send_destroy_request (const SOCKET sockfd)
Macro Definition Documentation
#define SP_ARG_CLASS_NAME "_db_stored_procedure_args"
Definition at line 38 of file jsp_cl.h.
Referenced by jsp_add_stored_procedure_argument().
#define SP_ATTR_ARG_COMMENT "comment"
Definition at line 54 of file jsp_cl.h.
Referenced by emit_stored_procedure_args(), and jsp_add_stored_procedure_argument().
#define SP_ATTR_ARG_COUNT "arg_count"
Definition at line 44 of file jsp_cl.h.
Referenced by drop_stored_procedure(), emit_stored_procedure(), jsp_add_stored_procedure(), and jsp_do_call_stored_procedure().
#define SP_ATTR_ARG_NAME "arg_name"
Definition at line 50 of file jsp_cl.h.
Referenced by emit_stored_procedure_args(), and jsp_add_stored_procedure_argument().
#define SP_ATTR_ARGS "args"
Definition at line 43 of file jsp_cl.h.
Referenced by drop_stored_procedure(), emit_stored_procedure(), jsp_add_stored_procedure(), and jsp_do_call_stored_procedure().
#define SP_ATTR_COMMENT "comment"
Definition at line 48 of file jsp_cl.h.
Referenced by emit_stored_procedure(), jsp_add_stored_procedure(), and jsp_alter_stored_procedure().
#define SP_ATTR_DATA_TYPE "data_type"
Definition at line 52 of file jsp_cl.h.
Referenced by emit_stored_procedure_args(), jsp_add_stored_procedure_argument(), and jsp_do_call_stored_procedure().
#define SP_ATTR_INDEX_OF_NAME "index_of"
Definition at line 51 of file jsp_cl.h.
Referenced by jsp_add_stored_procedure_argument().
#define SP_ATTR_LANG "lang"
Definition at line 45 of file jsp_cl.h.
Referenced by jsp_add_stored_procedure().
#define SP_ATTR_MODE "mode"
Definition at line 53 of file jsp_cl.h.
Referenced by emit_stored_procedure_args(), jsp_add_stored_procedure_argument(), and jsp_do_call_stored_procedure().
#define SP_ATTR_NAME "sp_name"
Definition at line 40 of file jsp_cl.h.
Referenced by emit_stored_procedure(), jsp_add_stored_procedure(), jsp_add_stored_procedure_argument(), and jsp_find_stored_procedure().
#define SP_ATTR_OWNER "owner"
Definition at line 47 of file jsp_cl.h.
Referenced by au_change_sp_owner(), drop_stored_procedure(), emit_stored_procedure(), jsp_add_stored_procedure(), and jsp_alter_stored_procedure().
#define SP_ATTR_RETURN_TYPE "return_type"
Definition at line 42 of file jsp_cl.h.
Referenced by emit_stored_procedure(), jsp_add_stored_procedure(), jsp_do_call_stored_procedure(), and jsp_get_return_type().
#define SP_ATTR_SP_TYPE "sp_type"
Definition at line 41 of file jsp_cl.h.
Referenced by drop_stored_procedure(), emit_stored_procedure(), jsp_add_stored_procedure(), and jsp_alter_stored_procedure().
#define SP_ATTR_TARGET "target"
Definition at line 46 of file jsp_cl.h.
Referenced by emit_stored_procedure(), jsp_add_stored_procedure(), and jsp_do_call_stored_procedure().
#define SP_CLASS_NAME "_db_stored_procedure"
Definition at line 37 of file jsp_cl.h.
Referenced by emit_stored_procedure(), jsp_add_stored_procedure(), and jsp_find_stored_procedure().
Enumeration Type Documentation
enum SP_LANG_ENUM
Enumerator
SP_LANG_JAVA
Definition at line 69 of file jsp_cl.h.
enum SP_MODE_ENUM
Enumerator
SP_MODE_IN
SP_MODE_OUT
SP_MODE_INOUT
Definition at line 62 of file jsp_cl.h.
enum SP_TYPE_ENUM
Enumerator
SP_TYPE_PROCEDURE
SP_TYPE_FUNCTION
Definition at line 56 of file jsp_cl.h.
Function Documentation
int jsp_alter_stored_procedure (PARSER_CONTEXT * parser, PT_NODE * statement)
Definition at line 598 of file jsp_cl.c.
References ARG_FILE_LINE, assert, AU_DISABLE, AU_ENABLE, au_is_dba_group_member(), Au_user, CHECK_MODIFICATION_ERROR, pt_stored_proc_info::comment, db_find_user(), db_get(), db_get_int(), db_make_null(), db_make_object(), db_make_string(), ER_AU_DBA_ONLY, ER_BLOCK_DDL_STMT, er_errid(), ER_ERROR_SEVERITY, ER_OBJ_OBJECT_NOT_FOUND, er_set(), ER_SP_INVALID_TYPE, err, error(), parser_node::info, jsp_find_stored_procedure(), jsp_map_pt_misc_to_sp_type(), pt_stored_proc_info::name, pt_statement_info::name, NO_ERROR, NULL, obj_set(), pt_name_info::original, pt_stored_proc_info::owner, pr_clear_value(), prm_get_bool_value(), PRM_ID_BLOCK_DDL_STATEMENT, PT_NODE_SP_COMMENT, PT_NODE_SP_TYPE, pt_statement_info::sp, SP_ATTR_COMMENT, SP_ATTR_OWNER, SP_ATTR_SP_TYPE, and SP_TYPE_FUNCTION.
Referenced by do_execute_statement(), and do_statement().
int jsp_call_from_server (DB_VALUE * returnval, DB_VALUE ** argarray, const char * name, const int arg_cnt)
Definition at line 2999 of file jsp_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, i, jsp_do_call_stored_procedure(), db_arg_list::next, NO_ERROR, and NULL.
Referenced by method_invoke_for_server(), and method_receive_results_for_stand_alone().
int jsp_call_stored_procedure (PARSER_CONTEXT * parser, PT_NODE * statement)
Definition at line 326 of file jsp_cl.c.
References ARG_FILE_LINE, pt_method_call_info::arg_list, db_make_null(), db_value_clear(), db_value_copy(), er_errid(), ER_ERROR_SEVERITY, ER_OBJ_INVALID_ARGUMENTS, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), ER_WARNING_SEVERITY, error(), parser_node::etc, free_and_init, parser_node::info, jsp_do_call_stored_procedure(), pt_statement_info::method_call, pt_method_call_info::method_name, pt_statement_info::name, db_arg_list::next, parser_node::next, NO_ERROR, parser_node::node_type, NULL, pt_name_info::original, pt_associate_label_with_value_check_reference(), pt_evaluate_tree(), pt_has_error, PT_IS_CONST, PT_NAME, pt_report_to_ersys(), PT_SEMANTIC, pt_value_to_db(), pt_method_call_info::to_return_var, and db_arg_list::val.
Referenced by do_call_method().
void jsp_close_connection (void)
Definition at line 209 of file jsp_cl.c.
References INVALID_SOCKET, IS_INVALID_SOCKET, jsp_disconnect_server(), and sock_fds.
Referenced by boot_shutdown_client(), and jsp_execute_stored_procedure().
int jsp_create_stored_procedure (PARSER_CONTEXT * parser, PT_NODE * statement)
Definition at line 500 of file jsp_cl.c.
References ARG_FILE_LINE, CHECK_MODIFICATION_ERROR, drop_stored_procedure(), ER_BLOCK_DDL_STMT, er_errid(), ER_ERROR_SEVERITY, ER_FAILED, er_set(), ER_SP_ALREADY_EXIST, ER_SP_INVALID_NAME, ER_SP_TOO_MANY_ARG_COUNT, err, parser_node::info, jsp_add_stored_procedure(), jsp_is_exist_stored_procedure(), MAX_ARG_COUNT, parser_node::next, NO_ERROR, NULL, pt_stored_proc_info::or_replace, p, pt_stored_proc_info::param_list, prm_get_bool_value(), PRM_ID_BLOCK_DDL_STATEMENT, PT_NODE_SP_COMMENT, PT_NODE_SP_JAVA_METHOD, PT_NODE_SP_NAME, PT_NODE_SP_TYPE, PT_SP_FUNCTION, PT_TYPE_NONE, pt_stored_proc_info::ret_type, SAVEPOINT_CREATE_STORED_PROC, pt_statement_info::sp, tran_abort_upto_system_savepoint(), and tran_system_savepoint().
Referenced by do_execute_statement(), and do_statement().
int jsp_drop_stored_procedure (PARSER_CONTEXT * parser, PT_NODE * statement)
Definition at line 451 of file jsp_cl.c.
References ARG_FILE_LINE, CHECK_MODIFICATION_ERROR, drop_stored_procedure(), ER_BLOCK_DDL_STMT, er_errid(), ER_ERROR_SEVERITY, er_set(), ER_SP_INVALID_NAME, err, i, if(), parser_node::info, pt_stored_proc_info::name, pt_statement_info::name, parser_node::next, NO_ERROR, NULL, pt_name_info::original, p, prm_get_bool_value(), PRM_ID_BLOCK_DDL_STATEMENT, PT_NODE_SP_TYPE, and pt_statement_info::sp.
Referenced by do_execute_statement(), and do_statement().
MOP jsp_find_stored_procedure (const char * name)
Definition at line 227 of file jsp_cl.c.
References ARG_FILE_LINE, AU_DISABLE, AU_ENABLE, db_find_class(), db_find_unique(), db_make_string(), er_clear(), er_errid(), ER_OBJ_OBJECT_NOT_FOUND, er_set(), ER_SP_NOT_EXIST, ER_WARNING_SEVERITY, free_and_init, jsp_check_stored_procedure_name(), NULL, SP_ATTR_NAME, and SP_CLASS_NAME.
Referenced by au_change_sp_owner_method(), drop_stored_procedure(), jsp_alter_stored_procedure(), jsp_do_call_stored_procedure(), jsp_get_return_type(), and jsp_is_exist_stored_procedure().
void* jsp_get_db_result_set (int h_id)
Definition at line 3075 of file jsp_cl.c.
References libcas_get_db_result_set().
int jsp_get_return_type (const char * name)
Definition at line 287 of file jsp_cl.c.
References assert, AU_DISABLE, AU_ENABLE, db_get(), db_get_int(), er_errid(), err, jsp_find_stored_procedure(), NO_ERROR, NULL, and SP_ATTR_RETURN_TYPE.
Referenced by pt_make_method_call().
void jsp_init (void)
Definition at line 185 of file jsp_cl.c.
References call_cnt, i, INVALID_SOCKET, is_prepare_call, MAX_CALL_COUNT, and sock_fds.
Referenced by boot_restart_client().
int jsp_is_exist_stored_procedure (const char * name)
Definition at line 267 of file jsp_cl.c.
References er_clear(), jsp_find_stored_procedure(), and NULL.
Referenced by jsp_create_stored_procedure(), pt_bind_names(), pt_check_method(), and pt_make_method_call().
int jsp_send_destroy_request (const SOCKET sockfd)
Definition at line 1979 of file jsp_cl.c.
References ARG_FILE_LINE, er_errid(), ER_ERROR_SEVERITY, er_set(), ER_SP_NETWORK_ERROR, jsp_readn(), jsp_writen(), libcas_main(), mode, NO_ERROR, ntohl(), OR_ALIGNED_BUF, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), SP_CODE_DESTROY, ssl_client, tran_begin_libcas_function(), and tran_end_libcas_function().
Referenced by jsp_execute_stored_procedure(), and jsp_send_destroy_request_all().
int jsp_send_destroy_request_all ()
Definition at line 1963 of file jsp_cl.c.
References i, INVALID_SOCKET, IS_INVALID_SOCKET, jsp_disconnect_server(), jsp_send_destroy_request(), MAX_CALL_COUNT, NO_ERROR, and sock_fds.
void jsp_set_prepare_call (void)
Definition at line 3048 of file jsp_cl.c.
References call_cnt, and is_prepare_call.
void jsp_srv_handle_free (int h_id)
Definition at line 3089 of file jsp_cl.c.
References libcas_srv_handle_free().
void jsp_unset_prepare_call (void)
Definition at line 3061 of file jsp_cl.c.
References call_cnt, and is_prepare_call.