CUBRID Engine: src/base/ksc5601.h File Reference
ksc5601.h File Reference
Functions
static int ksc5601_mbtowc (ucs4_t *pwc, const unsigned char *s, int n)
static int ksc5601_wctomb (unsigned char *r, ucs4_t wc, int n)
Variables
static const unsigned short ksc5601_2uni_page21 [1115]
static const unsigned short ksc5601_2uni_page30 [2350]
static const unsigned short ksc5601_2uni_page4a [4888]
static const unsigned short ksc5601_2charset [8227]
static const Summary16 ksc5601_uni2indx_page00 [70]
static const Summary16 ksc5601_uni2indx_page20 [103]
static const Summary16 ksc5601_uni2indx_page30 [62]
static const Summary16 ksc5601_uni2indx_page4e [1306]
static const Summary16 ksc5601_uni2indx_pageac [698]
static const Summary16 ksc5601_uni2indx_pagef9 [17]
static const Summary16 ksc5601_uni2indx_pageff [15]
Function Documentation
static int ksc5601_mbtowc (ucs4_t * pwc, const unsigned char * s, int n) static
Definition at line 1191 of file ksc5601.h.
References i, ksc5601_2uni_page21, ksc5601_2uni_page30, ksc5601_2uni_page4a, RET_ILSEQ, and RET_TOOFEW.
Referenced by intl_euckr_to_iso88591(), and intl_euckr_to_utf8().
static int ksc5601_wctomb (unsigned char * r, ucs4_t wc, int n) static
Definition at line 3012 of file ksc5601.h.
References i, s_Summary16::indx, ksc5601_2charset, NULL, RET_ILUNI, RET_TOOSMALL, and s_Summary16::used.
Referenced by intl_iso88591_to_euckr(), and intl_utf8_to_euckr().
Variable Documentation
const unsigned short ksc5601_2charset[8227] static
Definition at line 1242 of file ksc5601.h.
Referenced by ksc5601_wctomb().
const unsigned short ksc5601_2uni_page21[1115] static
Definition at line 25 of file ksc5601.h.
Referenced by ksc5601_mbtowc().
const unsigned short ksc5601_2uni_page30[2350] static
Definition at line 183 of file ksc5601.h.
Referenced by ksc5601_mbtowc().
const unsigned short ksc5601_2uni_page4a[4888] static
Definition at line 511 of file ksc5601.h.
Referenced by ksc5601_mbtowc().
const Summary16 ksc5601_uni2indx_page00[70] static
Initial value:
= {
  {0, 0x0000}, {0, 0x0000}, {0, 0x0000}, {0, 0x0000},
  {0, 0x0000}, {0, 0x0000}, {0, 0x0000}, {0, 0x0000},
  {0, 0x0000}, {0, 0x0000}, {0, 0x6592}, {7, 0xf7df},
  {21, 0x0040}, {22, 0xc181}, {27, 0x0040}, {28, 0x4181},
  {32, 0x0000}, {32, 0x0002}, {33, 0x00c0}, {35, 0x810e},
  {40, 0x0e07}, {46, 0x000c}, {48, 0x00c0}, {50, 0x0000},
  {50, 0x0000}, {50, 0x0000}, {50, 0x0000}, {50, 0x0000},
  {50, 0x0000}, {50, 0x0000}, {50, 0x0000}, {50, 0x0000},
  {50, 0x0000}, {50, 0x0000}, {50, 0x0000}, {50, 0x0000},
  {50, 0x0000}, {50, 0x0000}, {50, 0x0000}, {50, 0x0000},
  {50, 0x0000}, {50, 0x0000}, {50, 0x0000}, {50, 0x0000},
  {50, 0x0080}, {51, 0x2f01}, {57, 0x0000}, {57, 0x0000},
  {57, 0x0000}, {57, 0x0000}, {57, 0x0000}, {57, 0x0000},
  {57, 0x0000}, {57, 0x0000}, {57, 0x0000}, {57, 0x0000},
  {57, 0x0000}, {57, 0xfffe}, {72, 0x03fb}, {81, 0xfffe},
  {96, 0x03fb}, {105, 0x0000}, {105, 0x0000}, {105, 0x0000},
  {105, 0x0002}, {106, 0xffff}, {122, 0xffff}, {138, 0xffff},
  {154, 0xffff}, {170, 0x0002},
}
Definition at line 2274 of file ksc5601.h.
const Summary16 ksc5601_uni2indx_page20[103] static
Definition at line 2300 of file ksc5601.h.
const Summary16 ksc5601_uni2indx_page30[62] static
Initial value:
= {
  {470, 0xff0f}, {482, 0x003b}, {487, 0x0000}, {487, 0x0000},
  {487, 0xfffe}, {502, 0xffff}, {518, 0xffff}, {534, 0xffff},
  {550, 0xffff}, {566, 0x000f}, {570, 0xfffe}, {585, 0xffff},
  {601, 0xffff}, {617, 0xffff}, {633, 0xffff}, {649, 0x007f},
  {656, 0x0000}, {656, 0x0000}, {656, 0x0000}, {656, 0xfffe},
  {671, 0xffff}, {687, 0xffff}, {703, 0xffff}, {719, 0xffff},
  {735, 0x7fff}, {750, 0x0000}, {750, 0x0000}, {750, 0x0000},
  {750, 0x0000}, {750, 0x0000}, {750, 0x0000}, {750, 0x0000},
  {750, 0xffff}, {766, 0x1fff}, {779, 0x0000}, {779, 0x0000},
  {779, 0x0000}, {779, 0x0000}, {779, 0xffff}, {795, 0xcfff},
  {809, 0x0000}, {809, 0x0000}, {809, 0x0000}, {809, 0x0000},
  {809, 0x0000}, {809, 0x0000}, {809, 0x0000}, {809, 0x0000},
  {809, 0x0000}, {809, 0x0000}, {809, 0x0000}, {809, 0x0000},
  {809, 0x0000}, {809, 0x0000}, {809, 0x0000}, {809, 0x0000},
  {809, 0xff1f}, {822, 0xffff}, {838, 0xffff}, {854, 0xffff},
  {870, 0x87ff}, {882, 0x3949},
}
Definition at line 2336 of file ksc5601.h.
const Summary16 ksc5601_uni2indx_page4e[1306] static
Definition at line 2359 of file ksc5601.h.
const Summary16 ksc5601_uni2indx_pageac[698] static
Definition at line 2771 of file ksc5601.h.
const Summary16 ksc5601_uni2indx_pagef9[17] static
Initial value:
= {
  {7859, 0xffff}, {7875, 0xffff}, {7891, 0xffff}, {7907, 0xffff},
  {7923, 0xffff}, {7939, 0xffff}, {7955, 0xffff}, {7971, 0xffff},
  {7987, 0xffff}, {8003, 0xffff}, {8019, 0xffff}, {8035, 0xffff},
  {8051, 0xffff}, {8067, 0xffff}, {8083, 0xffff}, {8099, 0xffff},
  {8115, 0x0fff},
}
Definition at line 2993 of file ksc5601.h.
const Summary16 ksc5601_uni2indx_pageff[15] static
Initial value:
= {
  {8127, 0xfffe}, {8142, 0xffff}, {8158, 0xffff}, {8174, 0xffff},
  {8190, 0xffff}, {8206, 0x7fff}, {8221, 0x0000}, {8221, 0x0000},
  {8221, 0x0000}, {8221, 0x0000}, {8221, 0x0000}, {8221, 0x0000},
  {8221, 0x0000}, {8221, 0x0000}, {8221, 0x006f},
}
Definition at line 3003 of file ksc5601.h.