CUBRID Engine: src/base/language_support.h File Reference
language_support.h File Reference
#include <stddef.h>
#include "intl_support.h"
#include "locale_support.h"
Classes
struct db_charset
struct coll_opt
struct lang_collation
struct lang_locale_data
struct lang_coll_compat
struct lang_locale_compat
Macros
#define LANG_NAME_KOREAN "ko_KR"
#define LANG_NAME_ENGLISH "en_US"
#define LANG_NAME_TURKISH "tr_TR"
#define LANG_CHARSET_UTF8 "utf8"
#define LANG_CHARSET_UTF8_ALIAS1 "utf-8"
#define LANG_CHARSET_EUCKR "euckr"
#define LANG_CHARSET_EUCKR_ALIAS1 "euc-kr"
#define LANG_CHARSET_ISO88591 "iso88591"
#define LANG_CHARSET_ISO88591_ALIAS1 "iso-88591"
#define LANG_CHARSET_ISO88591_ALIAS2 "iso-8859-1"
#define LANG_NAME_DEFAULT LANG_NAME_ENGLISH
#define LANG_CHARSET_DEFAULT LANG_NAME_ENGLISH "." LANG_CHARSET_ISO88591
#define LANG_MAX_COLLATIONS 256
#define LANG_MAX_BUILTIN_COLLATIONS 32
#define LANG_MAX_LOADED_LOCALES 32
#define LANG_COERCIBLE_COLL LANG_SYS_COLLATION
#define LANG_COERCIBLE_CODESET LANG_SYS_CODESET
#define LANG_IS_COERCIBLE_COLL(c)
#define LANG_RT_COMMON_COLL(c1, c2, coll)
#define LANG_ERR_NO_CUBRID "The `%s' environment variable is not set.\n"
#define LANG_MAX_LANGNAME 256
#define LANG_VARIABLE_CHARSET(x)
#define LANG_GET_BINARY_COLLATION(c)
#define LANG_GET_COLLATION(i) lang_get_collation(i)
#define LANG_SYS_COLLATION (LANG_GET_BINARY_COLLATION(lang_charset()))
#define LANG_SYS_CODESET lang_charset()
Typedefs
typedef struct db_charset DB_CHARSET
typedef struct coll_opt COLL_OPT
typedef struct lang_locale_data LANG_LOCALE_DATA
typedef struct lang_collation LANG_COLLATION
typedef struct lang_coll_compat LANG_COLL_COMPAT
typedef struct lang_locale_compat LANG_LOCALE_COMPAT
Enumerations
enum {
LANG_COLL_ISO_BINARY = 0, LANG_COLL_UTF8_BINARY = 1, LANG_COLL_ISO_EN_CS = 2, LANG_COLL_ISO_EN_CI = 3,
LANG_COLL_UTF8_EN_CS = 4, LANG_COLL_UTF8_EN_CI = 5, LANG_COLL_UTF8_TR_CS = 6, LANG_COLL_UTF8_KO_CS = 7,
LANG_COLL_EUCKR_BINARY = 8, LANG_COLL_BINARY = 9, LANG_COLL_DEFAULT = LANG_COLL_ISO_BINARY, LANG_COLL_BUILTIN_MAX = LANG_COLL_BINARY
}
Functions
INTL_CODESET lang_charset (void)
void lang_init_builtin (void)
int lang_init (void)
void lang_init_console_txt_conv (void)
int lang_set_charset_lang (const char *lang_charset)
int lang_set_charset (const INTL_CODESET codeset)
int lang_set_language (const char *lang_str)
void lang_final (void)
int lang_locales_count (bool check_codeset)
const char * lang_get_msg_Loc_name (void)
const char * lang_get_Lang_name (void)
INTL_LANG lang_id (void)
DB_CURRENCY lang_currency (void)
DB_CURRENCY lang_locale_currency (const char *locale_str)
const char * lang_currency_symbol (DB_CURRENCY curr)
bool lang_check_identifier (const char *name, int length)
const LANG_LOCALE_DATA * lang_locale (void)
const LANG_LOCALE_DATA * lang_get_specific_locale (const INTL_LANG lang, const INTL_CODESET codeset)
const LANG_LOCALE_DATA * lang_get_first_locale_for_lang (const INTL_LANG lang)
int lang_get_lang_id_from_name (const char *lang_name, INTL_LANG *lang_id)
const char * lang_get_lang_name_from_id (const INTL_LANG lang_id)
int lang_set_flag_from_lang (const char *lang_str, bool has_user_format, bool has_user_lang, int *flag)
int lang_set_flag_from_lang_id (const INTL_LANG lang, bool has_user_format, bool has_user_lang, int *flag)
INTL_LANG lang_get_lang_id_from_flag (const int flag, bool *has_user_format, bool *has_user_lang)
const char * lang_date_format_parse (const INTL_LANG lang_id, const INTL_CODESET codeset, const DB_TYPE type, INTL_CODESET *format_codeset)
char lang_digit_grouping_symbol (const INTL_LANG lang_id)
char lang_digit_fractional_symbol (const INTL_LANG lang_id)
bool lang_is_coll_name_allowed (const char *name)
LANG_COLLATION * lang_get_collation (const int coll_id)
const char * lang_get_collation_name (const int coll_id)
LANG_COLLATION * lang_get_collation_by_name (const char *coll_name)
int lang_collation_count (void)
const char * lang_get_codeset_name (int codeset_id)
const ALPHABET_DATA * lang_user_alphabet_w_coll (const int collation_id)
TEXT_CONVERSION * lang_get_txt_conv (void)
const char * lang_charset_name (const INTL_CODESET codeset)
const char * lang_charset_cubrid_name (const INTL_CODESET codeset)
int lang_strmatch_utf8_uca_w_coll_data (const COLL_DATA *coll_data, bool is_match, const unsigned char *str1, const int size1, const unsigned char *str2, const int size2, const unsigned char *escape, const bool has_last_escape, int *str1_match_size, bool ignore_trailing_space)
int lang_get_charset_env_string (char *buf, int buf_size, const char *lang_name, const INTL_CODESET charset)
int lang_charset_name_to_id (const char *name, INTL_CODESET *codeset)
int lang_db_put_charset (void)
INTL_CODESET lang_get_client_charset (void)
int lang_get_client_collation (void)
void lang_set_parser_use_client_charset (bool use)
bool lang_get_parser_use_client_charset (void)
INTL_CODESET lang_charset_cubrid_name_to_id (const char *name)
const char * lang_charset_introducer (const INTL_CODESET codeset)
int lang_load_library (const char *lib_file, void **handle)
int lang_locale_data_load_from_lib (LANG_LOCALE_DATA *lld, void *lib_handle, const LOCALE_FILE *lf, bool is_load_for_dump)
int lang_load_count_coll_from_lib (int *count_coll, void *lib_handle, const LOCALE_FILE *lf)
int lang_load_get_coll_name_from_lib (const int coll_pos, char **coll_name, void *lib_handle, const LOCALE_FILE *lf)
int lang_load_coll_from_lib (COLL_DATA *cd, void *lib_handle, const LOCALE_FILE *lf)
UNICODE_NORMALIZATION * lang_get_generic_unicode_norm (void)
void lang_set_generic_unicode_norm (UNICODE_NORMALIZATION *norm)
int lang_check_coll_compat (const LANG_COLL_COMPAT *coll_array, const int coll_cnt, const char *client_text, const char *server_text)
int lang_check_locale_compat (const LANG_LOCALE_COMPAT *loc_array, const int loc_cnt, const char *client_text, const char *server_text)
Variables
LANG_COLLATION * lang_Collations [LANG_MAX_COLLATIONS]
INTL_CODESET lang_Loc_charset
Macro Definition Documentation
#define LANG_CHARSET_DEFAULT LANG_NAME_ENGLISH "." LANG_CHARSET_ISO88591
Definition at line 49 of file language_support.h.
#define LANG_CHARSET_EUCKR "euckr"
Definition at line 43 of file language_support.h.
Referenced by check_env_lang_val().
#define LANG_CHARSET_EUCKR_ALIAS1 "euc-kr"
Definition at line 44 of file language_support.h.
Referenced by check_env_lang_val().
#define LANG_CHARSET_ISO88591 "iso88591"
Definition at line 45 of file language_support.h.
Referenced by check_env_lang_val().
#define LANG_CHARSET_ISO88591_ALIAS1 "iso-88591"
Definition at line 46 of file language_support.h.
Referenced by check_env_lang_val().
#define LANG_CHARSET_ISO88591_ALIAS2 "iso-8859-1"
Definition at line 47 of file language_support.h.
Referenced by check_env_lang_val().
#define LANG_CHARSET_UTF8 "utf8"
Definition at line 41 of file language_support.h.
Referenced by check_env_lang_val().
#define LANG_CHARSET_UTF8_ALIAS1 "utf-8"
Definition at line 42 of file language_support.h.
Referenced by check_env_lang_val().
#define LANG_COERCIBLE_CODESET LANG_SYS_CODESET
Definition at line 56 of file language_support.h.
Referenced by db_bigint_to_binary_string(), db_evaluate_json_type_dbval(), db_string_space(), db_to_char(), do_send_plan_trace_to_session(), lob_to_bit_char(), netval_to_dbval(), pt_check_expr_collation(), pt_coerce_node_collation(), pt_coerce_node_collection_of_collection(), pt_db_value_initialize(), pt_get_collation_info(), pt_get_collation_info_for_collection_type(), pt_init_datatype(), and pt_make_prim_data_type().
#define LANG_COERCIBLE_COLL LANG_SYS_COLLATION
Definition at line 55 of file language_support.h.
Referenced by db_bigint_to_binary_string(), db_evaluate_json_type_dbval(), db_string_space(), db_to_char(), do_send_plan_trace_to_session(), lob_to_bit_char(), pt_check_expr_collation(), pt_db_value_initialize(), pt_get_collation_info(), pt_get_collation_info_for_collection_type(), pt_init_datatype(), and pt_make_prim_data_type().
#define LANG_ERR_NO_CUBRID "The `%s' environment variable is not set.\n"
Definition at line 94 of file language_support.h.
#define LANG_GET_BINARY_COLLATION (c)
Value:
(((c) == INTL_CODESET_UTF8) \
  ? LANG_COLL_UTF8_BINARY :                  \
  (((c) == INTL_CODESET_KSC5601_EUC) ? LANG_COLL_EUCKR_BINARY :  \
  (((c) == INTL_CODESET_ISO88591) ? LANG_COLL_ISO_BINARY :   \
    LANG_COLL_BINARY)))
Definition at line 119 of file language_support.h.
Referenced by boot_add_charsets(), check_change_class_collation(), db_clob_to_char(), db_string_chr(), db_to_date(), db_to_datetime(), db_to_time(), db_to_timestamp(), or_packed_enumeration_size(), pt_attr_check_default_cs_coll(), pt_upd_domain_info(), sysprm_generate_new_value(), sysprm_init_intl_param(), sysprm_make_default_values(), and sysprm_print_parameters_for_ha_repl().
#define LANG_GET_COLLATION (i) lang_get_collation(i)
Definition at line 258 of file language_support.h.
#define LANG_IS_COERCIBLE_COLL (c)
Value:
((c) == LANG_COLL_ISO_BINARY || (c) == LANG_COLL_UTF8_BINARY  \
     || (c) == LANG_COLL_EUCKR_BINARY)
Definition at line 58 of file language_support.h.
Referenced by pt_coerce_node_collation(), pt_coerce_node_collection_of_collection(), pt_get_collation_info(), pt_get_collation_info_for_collection_type(), and tp_can_steal_string().
#define LANG_MAX_BUILTIN_COLLATIONS 32
Definition at line 52 of file language_support.h.
Referenced by locale_check_collation_id(), register_collation(), and start_collation_settings().
#define LANG_MAX_COLLATIONS 256
Definition at line 51 of file language_support.h.
Referenced by boot_add_collations(), catcls_get_db_collation(), lang_check_coll_compat(), lang_free_collations(), lang_get_collation(), lang_get_collation_by_name(), lang_get_collation_name(), lang_init_builtin(), locale_check_collation_id(), main(), register_collation(), sboot_get_locales_info(), start_collation_settings(), and synccoll_check().
#define LANG_MAX_LANGNAME 256
Definition at line 96 of file language_support.h.
Referenced by boot_restart_server(), lang_load_get_coll_name_from_lib(), lang_set_language(), set_msg_lang_from_env(), and xboot_emergency_patch().
#define LANG_MAX_LOADED_LOCALES 32
Definition at line 53 of file language_support.h.
Referenced by init_user_locales(), and register_lang_locale_data().
#define LANG_NAME_DEFAULT LANG_NAME_ENGLISH
Definition at line 48 of file language_support.h.
Referenced by msgcat_open(), msgcat_open_file(), set_default_lang(), and set_msg_lang_from_env().
#define LANG_NAME_ENGLISH "en_US"
Definition at line 39 of file language_support.h.
#define LANG_NAME_KOREAN "ko_KR"
Definition at line 38 of file language_support.h.
#define LANG_NAME_TURKISH "tr_TR"
Definition at line 40 of file language_support.h.
#define LANG_RT_COMMON_COLL (c1, c2, coll)
Value:
do {                                        \
    coll = -1;                                \
    if ((c1) == (c2))                 \
      {                                       \
        coll = (c1);                  \
      }                                       \
    else if (LANG_IS_COERCIBLE_COLL (c1))     \
      {                       \
    if (!LANG_IS_COERCIBLE_COLL (c2))     \
      {                   \
        coll = (c2);              \
      }                   \
    else                     \
      {                   \
        if ((c2) == LANG_COLL_ISO_BINARY) \
          {                   \
        coll = (c2);              \
          }                   \
      }                   \
      }                       \
    else if (LANG_IS_COERCIBLE_COLL (c2))     \
      {                       \
    coll = (c1);                  \
      }                       \
  } while (0)
Definition at line 63 of file language_support.h.
Referenced by db_find_string_in_in_set(), db_string_compare(), db_string_concatenate(), db_string_instr(), db_string_like(), db_string_position(), db_string_prefix_compare(), db_string_regexp_count(), db_string_regexp_instr(), db_string_regexp_like(), db_string_regexp_replace(), db_string_regexp_substr(), db_string_replace(), db_string_rlike(), and tp_value_compare_with_error().
#define LANG_SYS_CODESET lang_charset()
Definition at line 266 of file language_support.h.
Referenced by au_set_new_auth(), boot_add_charsets(), boot_add_collations(), boot_add_data_type(), boot_define_dual(), catcls_find_oid_by_class_name(), classobj_make_function_index_info_seq(), classobj_make_index_filter_pred_seq(), coerce_binary_to_dbvalue(), coerce_char_to_dbvalue(), coerce_date_to_dbvalue(), coerce_datetime_to_dbvalue(), coerce_time_to_dbvalue(), coerce_timestamp_to_dbvalue(), csql_help_schema(), csql_help_trigger(), db_clob_to_char(), db_date_dbval(), db_string_insert_substring(), db_string_substring_index(), db_string_value(), db_tz_offset(), db_value_domain_init(), db_value_get(), delete_all_slave_ha_apply_info(), db_value_printer::describe_value(), do_create_entity(), heap_set_autoincrement_value(), insert_ha_apply_info(), cubload::semantic_helper::is_utf8_valid(), la_delete_ha_apply_info(), la_get_ha_apply_info(), la_insert_ha_apply_info(), la_update_ha_apply_info_log_record_time(), la_update_ha_apply_info_start_time(), la_update_ha_last_applied_info(), lang_get_client_charset(), ldr_init_loader(), ldr_nstr_elem(), mr_initval_enumeration(), mr_initval_string(), mr_initval_varnchar(), mr_readval_nchar_internal(), mr_readval_varnchar_internal(), numeric_db_value_coerce_from_num(), pt_attr_check_default_cs_coll(), pt_check_create_entity(), pt_check_grammar_charset_collation(), pt_check_partition_values(), pt_coerce_node_collation(), pt_coerce_range_expr_arguments(), pt_data_type_to_db_domain(), pt_eval_function_type_old(), pt_evaluate_db_value_expr(), pt_evaluate_tree_internal(), pt_get_collation_info(), pt_get_compatible_info(), pt_make_query_show_columns(), pt_make_query_show_index(), pt_node_data_type_to_db_domain(), pt_node_to_partition_info(), pt_print_expr(), pt_print_value(), pt_semantic_check_local(), pt_set_default_data_type(), pt_upd_domain_info(), pt_wrap_with_cast_op(), put_string(), string_disk_size(), sysprm_generate_new_value(), sysprm_init_intl_param(), sysprm_make_default_values(), sysprm_print_parameters_for_ha_repl(), tp_apply_sys_charset(), tp_domain_init(), valcnv_convert_data_to_string(), and valcnv_convert_value_to_string().
#define LANG_SYS_COLLATION (LANG_GET_BINARY_COLLATION(lang_charset()))
Definition at line 265 of file language_support.h.
Referenced by au_set_new_auth(), boot_add_charsets(), boot_add_collations(), boot_add_data_type(), boot_define_dual(), catcls_find_oid_by_class_name(), classobj_make_class(), classobj_make_function_index_info_seq(), classobj_make_index_filter_pred_seq(), coerce_binary_to_dbvalue(), coerce_char_to_dbvalue(), coerce_date_to_dbvalue(), coerce_datetime_to_dbvalue(), coerce_time_to_dbvalue(), coerce_timestamp_to_dbvalue(), db_date_dbval(), db_string_insert_substring(), db_string_substring_index(), db_string_value(), db_tz_offset(), db_value_domain_init(), delete_all_slave_ha_apply_info(), object_printer::describe_domain(), do_create_entity(), get_string(), heap_set_autoincrement_value(), class_description::init(), insert_ha_apply_info(), la_delete_ha_apply_info(), la_get_ha_apply_info(), la_insert_ha_apply_info(), la_update_ha_apply_info_log_record_time(), la_update_ha_apply_info_start_time(), la_update_ha_last_applied_info(), lang_get_client_collation(), ldr_init_loader(), ldr_nstr_elem(), mr_initval_enumeration(), mr_initval_string(), mr_initval_varnchar(), numeric_db_value_coerce_from_num(), pt_assignment_compatible(), pt_check_create_entity(), pt_check_grammar_charset_collation(), pt_check_partition_values(), pt_coerce_expression_argument(), pt_coerce_node_collation(), pt_coerce_range_expr_arguments(), pt_data_type_to_db_domain(), pt_eval_function_type_old(), pt_evaluate_db_value_expr(), pt_evaluate_tree_internal(), pt_get_collation_info(), pt_get_collation_info_for_collection_type(), pt_get_compatible_info(), pt_lambda_check_reduce_eq(), pt_make_query_show_columns(), pt_make_query_show_index(), pt_node_data_type_to_db_domain(), pt_node_to_partition_info(), pt_print_datatype(), pt_print_expr(), pt_print_value(), pt_semantic_check_local(), pt_set_default_data_type(), pt_upd_domain_info(), pt_wrap_with_cast_op(), put_string(), qo_collect_name_spec(), qo_plan_print_sort_spec_helper(), string_disk_size(), tp_apply_sys_charset(), tp_domain_init(), valcnv_convert_data_to_string(), and valcnv_convert_value_to_string().
#define LANG_VARIABLE_CHARSET (x)
Value:
((x) != INTL_CODESET_ASCII     && \
                  (x) != INTL_CODESET_RAW_BITS  && \
                  (x) != INTL_CODESET_RAW_BYTES && \
                  (x) != INTL_CODESET_ISO88591)
Definition at line 98 of file language_support.h.
Referenced by lang_currency_symbol(), parser_parse_file(), parser_parse_string_with_escapes(), and pt_init_one_statement_parser().
Typedef Documentation
typedef struct coll_opt COLL_OPT
Definition at line 138 of file language_support.h.
typedef struct db_charset DB_CHARSET
Definition at line 125 of file language_support.h.
typedef struct lang_coll_compat LANG_COLL_COMPAT
Definition at line 237 of file language_support.h.
typedef struct lang_collation LANG_COLLATION
Definition at line 156 of file language_support.h.
typedef struct lang_locale_compat LANG_LOCALE_COMPAT
Definition at line 246 of file language_support.h.
typedef struct lang_locale_data LANG_LOCALE_DATA
Definition at line 154 of file language_support.h.
Enumeration Type Documentation
anonymous enum
Enumerator
LANG_COLL_ISO_BINARY
LANG_COLL_UTF8_BINARY
LANG_COLL_ISO_EN_CS
LANG_COLL_ISO_EN_CI
LANG_COLL_UTF8_EN_CS
LANG_COLL_UTF8_EN_CI
LANG_COLL_UTF8_TR_CS
LANG_COLL_UTF8_KO_CS
LANG_COLL_EUCKR_BINARY
LANG_COLL_BINARY
LANG_COLL_DEFAULT
LANG_COLL_BUILTIN_MAX
Definition at line 103 of file language_support.h.
Function Documentation
INTL_CODESET lang_charset (void)
Definition at line 1976 of file language_support.c.
References assert, INTL_CODESET_NONE, lang_Charset_initialized, and lang_Loc_charset.
Referenced by disk_format(), get_set_domain(), get_string(), intl_identifier_casecmp_w_size(), intl_identifier_fix(), intl_identifier_lower(), intl_identifier_lower_string_size(), intl_identifier_mht_1strlowerhash(), intl_identifier_ncasecmp(), intl_identifier_upper(), intl_identifier_upper_string_size(), intl_mbs_ncpy(), la_find_log_pagesize(), lang_currency_symbol(), lang_db_put_charset(), lang_set_language(), logpb_initialize_header(), mr_data_lengthval_nchar(), mr_lengthval_varnchar_internal(), mr_writeval_nchar_internal(), mr_writeval_varnchar_internal(), parser_parse_file(), parser_parse_string_with_escapes(), pt_assignment_compatible(), pt_init_one_statement_parser(), start_csql(), xboot_emergency_patch(), and xboot_register_client().
const char* lang_charset_cubrid_name (const INTL_CODESET codeset)
Definition at line 2585 of file language_support.c.
References assert, db_charset::charset_cubrid_name, db_charset::charset_id, i, INTL_CODESET_BINARY, INTL_CODESET_NONE, INTL_CODESET_UTF8, and NULL.
Referenced by boot_add_charsets(), boot_restart_server(), db_get_cs_coll_info(), la_find_log_pagesize(), la_print_log_header(), lang_get_charset_env_string(), and xboot_emergency_patch().
INTL_CODESET lang_charset_cubrid_name_to_id (const char * name)
Definition at line 2775 of file language_support.c.
References INTL_CODESET_BINARY, INTL_CODESET_LAST, and INTL_CODESET_NONE.
Referenced by pt_check_grammar_charset_collation().
const char* lang_charset_introducer (const INTL_CODESET codeset)
Definition at line 2798 of file language_support.c.
References assert, db_charset::charset_id, i, INTL_CODESET_BINARY, INTL_CODESET_NONE, INTL_CODESET_UTF8, db_charset::introducer, and NULL.
Referenced by db_value_printer::describe_value(), pt_check_partition_values(), and pt_print_value().
const char* lang_charset_name (const INTL_CODESET codeset)
Definition at line 2561 of file language_support.c.
References assert, db_charset::charset_id, db_charset::charset_name, i, INTL_CODESET_BINARY, INTL_CODESET_NONE, INTL_CODESET_UTF8, and NULL.
Referenced by db_date_format(), db_str_to_date(), db_time_format(), db_to_date(), db_to_datetime(), db_to_time(), db_to_timestamp(), get_string_date_token_id(), and print_string_date_token().
int lang_charset_name_to_id (const char * name, INTL_CODESET * codeset)
Definition at line 2683 of file language_support.c.
References db_charset::charset_id, ER_FAILED, i, INTL_CODESET_NONE, and NO_ERROR.
int lang_check_coll_compat (const LANG_COLL_COMPAT * coll_array, const int coll_cnt, const char * client_text, const char * server_text)
Definition at line 7495 of file language_support.c.
References assert, lang_coll_compat::checksum, coll_data::checksum, lang_collation::codeset, lang_coll_compat::codeset, lang_collation::coll, lang_coll_compat::coll_id, coll_data::coll_id, lang_coll_compat::coll_name, coll_data::coll_name, ER_LOC_INIT, ERR_MSG_SIZE, i, lang_Count_collations, lang_get_collation(), LANG_MAX_COLLATIONS, LOG_LOCALE_ERROR, NO_ERROR, and NULL.
Referenced by boot_get_host_name(), and boot_restart_server().
bool lang_check_identifier (const char * name, int length)
Definition at line 2101 of file language_support.c.
References char_isalnum(), char_isalpha(), i, and NULL.
Referenced by pt_append_name().
int lang_check_locale_compat (const LANG_LOCALE_COMPAT * loc_array, const int loc_cnt, const char * client_text, const char * server_text)
Definition at line 7584 of file language_support.c.
References assert, lang_locale_data::checksum, lang_locale_compat::checksum, lang_locale_data::codeset, lang_locale_compat::codeset, ER_LOC_INIT, ERR_MSG_SIZE, i, lang_Count_locales, lang_locale_data::lang_name, lang_locale_compat::lang_name, LOG_LOCALE_ERROR, lang_locale_data::next_lld, NO_ERROR, and NULL.
Referenced by boot_get_host_name().
int lang_collation_count (void)
Definition at line 1704 of file language_support.c.
References lang_Count_collations.
Referenced by boot_add_charsets(), boot_add_collations(), sboot_get_locales_info(), and synccoll_check().
DB_CURRENCY lang_currency (void)
Definition at line 1935 of file language_support.c.
References assert, DB_CURRENCY_NULL, lang_Language_initialized, and lang_Loc_currency.
Referenced by db_get_currency_default(), and lang_locale_currency().
const char* lang_currency_symbol (DB_CURRENCY curr)
Definition at line 2016 of file language_support.c.
References intl_get_money_symbol_console(), lang_charset(), LANG_VARIABLE_CHARSET, and p.
Referenced by tp_value_cast_internal(), and valcnv_convert_data_to_string().
const char* lang_date_format_parse (const INTL_LANG lang_id, const INTL_CODESET codeset, const DB_TYPE type, INTL_CODESET * format_codeset)
Definition at line 2405 of file language_support.c.
References assert, lang_defaults::codeset, lang_locale_data::codeset, lang_locale_data::date_format, lang_locale_data::datetime_format, lang_locale_data::datetimetz_format, DB_TYPE_DATE, DB_TYPE_DATETIME, DB_TYPE_DATETIMETZ, DB_TYPE_TIME, DB_TYPE_TIMESTAMP, DB_TYPE_TIMESTAMPTZ, lang_Charset_initialized, lang_get_first_locale_for_lang(), lang_Language_initialized, lang_locale_data::next_lld, NULL, lang_locale_data::time_format, lang_locale_data::timestamp_format, and lang_locale_data::timestamptz_format.
Referenced by db_to_date(), db_to_datetime(), db_to_time(), and db_to_timestamp().
int lang_db_put_charset (void)
Definition at line 2643 of file language_support.c.
References assert, AU_DISABLE, AU_ENABLE, Au_root, db_make_int(), db_make_string(), db_put_internal(), lang_charset(), lang_get_lang_name_from_id(), lang_id(), NO_ERROR, and pr_clear_value().
Referenced by createdb().
char lang_digit_fractional_symbol (const INTL_LANG lang_id)
Definition at line 2535 of file language_support.c.
References assert, INTL_CODESET_NONE, lang_get_specific_locale(), NULL, and lang_locale_data::number_decimal_sym.
Referenced by convert_locale_number(), db_format(), db_to_number(), get_number_token(), make_number(), make_number_to_char(), number_to_char(), roundoff(), scientific_to_decimal_string(), and to_number_next_state().
char lang_digit_grouping_symbol (const INTL_LANG lang_id)
Definition at line 2520 of file language_support.c.
References assert, INTL_CODESET_NONE, lang_get_specific_locale(), NULL, and lang_locale_data::number_group_sym.
Referenced by convert_locale_number(), db_format(), db_to_number(), get_number_token(), make_number(), make_number_to_char(), number_to_char(), roundoff(), and to_number_next_state().
void lang_final (void)
Definition at line 1991 of file language_support.c.
References destroy_user_locales(), lang_Builtin_initialized, lang_Charset_initialized, lang_free_collations(), lang_Init_w_error, lang_Initialized, lang_Language_initialized, lang_Msg_env_initialized, lang_set_generic_unicode_norm(), lang_unload_libraries(), and NULL.
Referenced by boot_client_all_finalize(), boot_initialize_client(), boot_restart_client(), boot_server_all_finalize(), and csql_exit_cleanup().
int lang_get_charset_env_string (char * buf, int buf_size, const char * lang_name, const INTL_CODESET charset)
Definition at line 2611 of file language_support.c.
References assert_release, ER_FAILED, INTL_CODESET_ISO88591, lang_charset_cubrid_name(), NO_ERROR, and NULL.
Referenced by lang_set_language().
INTL_CODESET lang_get_client_charset (void)
Definition at line 2705 of file language_support.c.
References lang_collation::codeset, lang_get_collation_by_name(), LANG_SYS_CODESET, NULL, prm_get_string_value(), and PRM_ID_INTL_COLLATION.
Referenced by jsp_unpack_numeric_value(), jsp_unpack_string_value(), and netval_to_dbval().
int lang_get_client_collation (void)
Definition at line 2727 of file language_support.c.
References lang_collation::coll, coll_data::coll_id, lang_get_collation_by_name(), LANG_SYS_COLLATION, NULL, prm_get_string_value(), and PRM_ID_INTL_COLLATION.
Referenced by jsp_unpack_string_value(), and netval_to_dbval().
const char* lang_get_codeset_name (int codeset_id)
Definition at line 1715 of file language_support.c.
References assert, INTL_CODESET_BINARY, INTL_CODESET_ISO88591, INTL_CODESET_KSC5601_EUC, and INTL_CODESET_UTF8.
Referenced by cublocale::get_codeset_name(), pt_check_cast_op(), pt_check_expr_collation(), pt_print_alter_one_clause(), pt_print_expr(), and set_current_locale().
LANG_COLLATION* lang_get_collation (const int coll_id)
Definition at line 1653 of file language_support.c.
References assert, and LANG_MAX_COLLATIONS.
Referenced by boot_add_collations(), build_att_coll_change_map(), check_change_class_collation(), db_string_concatenate(), db_string_regexp_count(), db_string_regexp_instr(), db_string_regexp_like(), db_string_regexp_replace(), db_string_regexp_substr(), db_string_rlike(), lang_check_coll_compat(), lang_user_alphabet_w_coll(), main(), or_get_enumeration(), pt_attr_check_default_cs_coll(), pt_check_cast_op(), pt_check_create_index(), pt_check_expr_collation(), pt_eval_expr_type(), pt_get_collation_info(), pt_get_collation_info_for_collection_type(), pt_has_non_idx_sarg_coll_pre(), qo_check_coll_optimization(), qo_rewrite_one_like_term(), qstr_eval_like(), qstr_position(), sboot_get_locales_info(), synccoll_check(), tp_domain_resolve(), tp_domain_resolve_default_w_coll(), tp_value_compare_with_error(), unpack_domain(), and unpack_domain_2().
LANG_COLLATION* lang_get_collation_by_name (const char * coll_name)
Definition at line 1683 of file language_support.c.
References assert, i, LANG_MAX_COLLATIONS, and NULL.
Referenced by lang_get_client_charset(), lang_get_client_collation(), lang_locale_data_load_from_lib(), pt_check_grammar_charset_collation(), and sysprm_generate_new_value().
const char* lang_get_collation_name (const int coll_id)
Definition at line 1667 of file language_support.c.
References lang_collation::coll, coll_data::coll_name, LANG_MAX_COLLATIONS, and NULL.
Referenced by db_get_cs_coll_info(), object_printer::describe_domain(), do_set_names(), emit_domain_def(), emit_schema(), class_description::init(), pt_print_alter_one_clause(), pt_print_attr_def(), pt_print_datatype(), pt_print_expr(), pt_print_value(), qexec_execute_build_columns(), qo_plan_print_sort_spec_helper(), sysprm_generate_new_value(), sysprm_init_intl_param(), sysprm_make_default_values(), sysprm_print_parameters_for_ha_repl(), and tp_check_value_size().
const LANG_LOCALE_DATA* lang_get_first_locale_for_lang (const INTL_LANG lang)
Definition at line 2186 of file language_support.c.
References assert, lang_defaults::lang, lang_Charset_initialized, lang_Count_locales, lang_Language_initialized, and NULL.
Referenced by lang_date_format_parse(), and sboot_get_locales_info().
UNICODE_NORMALIZATION* lang_get_generic_unicode_norm (void)
Definition at line 7442 of file language_support.c.
References generic_Unicode_norm.
Referenced by csql_db_value_as_string(), csql_help_schema(), csql_help_trigger(), dbval_to_net_buf(), init_user_locales(), jsp_pack_string_argument(), jsp_unpack_string_value(), and netval_to_dbval().
INTL_LANG lang_get_lang_id_from_flag (const int flag, bool * has_user_format, bool * has_user_lang)
Definition at line 2373 of file language_support.c.
References lang_Count_locales, and lang_id().
Referenced by date_to_char(), db_date_format(), db_format(), db_str_to_date(), db_time_format(), db_to_date(), db_to_datetime(), db_to_number(), db_to_time(), db_to_timestamp(), number_to_char(), pt_eval_expr_type(), and pt_print_expr().
int lang_get_lang_id_from_name (const char * lang_name, INTL_LANG * lang_id)
Definition at line 2245 of file language_support.c.
References assert, i, INTL_LANG_ENGLISH, lang_Count_locales, lang_locale_data::lang_id, and NULL.
Referenced by lang_set_flag_from_lang(), set_current_locale(), and sysprm_generate_new_value().
const char* lang_get_Lang_name (void)
Definition at line 1905 of file language_support.c.
References assert, lang_Lang_name, lang_Language_initialized, and NULL.
Referenced by sysprm_generate_new_value(), sysprm_init_intl_param(), sysprm_make_default_values(), sysprm_print_parameters_for_ha_repl(), and xboot_register_client().
const char* lang_get_lang_name_from_id (const INTL_LANG lang_id)
Definition at line 2276 of file language_support.c.
References assert, lang_Count_locales, lang_id(), lang_locale_data::lang_name, and NULL.
Referenced by db_date_format(), db_str_to_date(), db_time_format(), db_to_date(), db_to_datetime(), db_to_time(), db_to_timestamp(), get_string_date_token_id(), lang_db_put_charset(), number_to_char(), print_string_date_token(), and pt_print_expr().
const char* lang_get_msg_Loc_name (void)
Definition at line 1889 of file language_support.c.
References lang_Msg_env_initialized, lang_Msg_loc_name, and set_msg_lang_from_env().
Referenced by msgcat_open(), and msgcat_open_file().
bool lang_get_parser_use_client_charset (void)
Definition at line 2761 of file language_support.c.
References lang_Parser_use_client_charset.
const LANG_LOCALE_DATA* lang_get_specific_locale (const INTL_LANG lang, const INTL_CODESET codeset)
Definition at line 2153 of file language_support.c.
References assert, lang_locale_data::codeset, INTL_CODESET_NONE, lang_defaults::lang, lang_Charset_initialized, lang_Count_locales, lang_Language_initialized, lang_locale_data::next_lld, and NULL.
Referenced by db_date_format(), db_str_to_date(), db_time_format(), db_to_date(), db_to_datetime(), db_to_time(), db_to_timestamp(), get_string_date_token_id(), intl_case_match_tok(), intl_identifier_casecmp_w_size(), lang_digit_fractional_symbol(), lang_digit_grouping_symbol(), and print_string_date_token().
TEXT_CONVERSION* lang_get_txt_conv (void)
Definition at line 2549 of file language_support.c.
References console_Conv.
Referenced by intl_text_dbcs_to_utf8(), intl_text_single_byte_to_utf8(), intl_text_utf8_to_dbcs(), intl_text_utf8_to_single_byte(), and start_csql().
INTL_LANG lang_id (void)
Definition at line 1920 of file language_support.c.
References assert, lang_Lang_id, and lang_Language_initialized.
Referenced by intl_identifier_casecmp(), intl_identifier_namecmp(), intl_identifier_ncasecmp(), intl_zone(), lang_db_put_charset(), lang_get_lang_id_from_flag(), lang_get_lang_name_from_id(), and pt_print_expr().
int lang_init (void)
Definition at line 906 of file language_support.c.
References assert, ER_LOC_INIT, error(), init_user_locales(), lang_Charset_initialized, lang_init_builtin(), lang_Init_w_error, lang_Initialized, lang_Language_initialized, and NO_ERROR.
Referenced by boot_initialize_client(), boot_restart_client(), boot_restart_server(), rel_build_type(), xboot_emergency_patch(), xboot_initialize_server(), and xboot_restart_from_backup().
void lang_init_builtin (void)
Definition at line 854 of file language_support.c.
References coll_Iso_binary, i, lang_Builtin_initialized, LANG_MAX_COLLATIONS, register_collation(), register_lang_locale_data(), and set_msg_lang_from_env().
Referenced by genlocale(), and lang_init().
void lang_init_console_txt_conv (void)
Definition at line 936 of file language_support.c.
References assert, text_conversion::init_conv_func, lang_Initialized, text_conversion::nl_lang_str, NULL, strlen, lang_locale_data::txt_conv, and text_conversion::win_codepages.
Referenced by csql().
bool lang_is_coll_name_allowed (const char * name)
Definition at line 1622 of file language_support.c.
References i, and NULL.
Referenced by locale_compile_locale().
int lang_load_coll_from_lib (COLL_DATA * cd, void * lib_handle, const LOCALE_FILE * lf)
Definition at line 7148 of file language_support.c.
References assert, bool, coll_data::checksum, coll_data::coll_id, coll_data::coll_name, coll_data::contr_list, coll_data::contr_min_size, coll_data::count_contr, coll_data::cp_first_contr_array, coll_data::cp_first_contr_count, coll_data::cp_first_contr_offset, ER_LOC_INIT, ERR_MSG_SIZE, locale_file::lib_file, LOC_LIB_SYMBOL_NAME_SIZE, locale_file::locale_name, LOG_LOCALE_ERROR, coll_data::next_cp, NO_ERROR, NULL, uca_options::sett_backwards, uca_options::sett_caseFirst, uca_options::sett_caseLevel, uca_options::sett_contr_policy, uca_options::sett_expansions, uca_options::sett_match_contr, uca_options::sett_strength, SHLIB_GET_ADDR, SHLIB_GET_ADDR_W_REF, SHLIB_GET_VAL, TAILOR_IDENTITY, TAILOR_QUATERNARY, TAILOR_UNDEFINED, coll_data::uca_exp_num, coll_data::uca_num, coll_data::uca_opt, coll_data::uca_w_l13, coll_data::uca_w_l4, coll_data::w_count, and coll_data::weights.
Referenced by lang_locale_data_load_from_lib(), and locale_dump_lib_collations().
int lang_load_count_coll_from_lib (int * count_coll, void * lib_handle, const LOCALE_FILE * lf)
Definition at line 7081 of file language_support.c.
References assert, ER_LOC_INIT, ERR_MSG_SIZE, locale_file::lib_file, LOC_LIB_SYMBOL_NAME_SIZE, locale_file::locale_name, LOG_LOCALE_ERROR, NO_ERROR, NULL, and SHLIB_GET_VAL.
Referenced by lang_locale_data_load_from_lib(), and locale_dump_lib_collations().
int lang_load_get_coll_name_from_lib (const int coll_pos, char ** coll_name, void * lib_handle, const LOCALE_FILE * lf)
Definition at line 7114 of file language_support.c.
References assert, COLL_NAME_SIZE, ER_LOC_INIT, ERR_MSG_SIZE, LANG_MAX_LANGNAME, locale_file::lib_file, LOC_LIB_SYMBOL_NAME_SIZE, locale_file::locale_name, LOG_LOCALE_ERROR, NO_ERROR, NULL, and SHLIB_GET_ADDR.
Referenced by lang_locale_data_load_from_lib(), and locale_dump_lib_collations().
int lang_load_library (const char * lib_file, void ** handle)
Definition at line 7315 of file language_support.c.
References assert, ER_LOC_INIT, ERR_MSG_SIZE, error(), LOG_LOCALE_ERROR, NO_ERROR, and NULL.
Referenced by dumplocale(), and init_user_locales().
const LANG_LOCALE_DATA* lang_locale (void)
Definition at line 2131 of file language_support.c.
References assert, lang_Charset_initialized, lang_Language_initialized, lang_Loc_data, and NULL.
Referenced by intl_identifier_lower(), intl_identifier_lower_string_size(), intl_identifier_mht_1strlowerhash(), intl_identifier_upper(), and intl_identifier_upper_string_size().
DB_CURRENCY lang_locale_currency (const char * locale_str)
Definition at line 1950 of file language_support.c.
References assert, DB_CURRENCY_NULL, lang_locale_data::default_currency_code, i, lang_Count_locales, lang_currency(), lang_Language_initialized, and lang_defaults::lang_name.
Referenced by number_to_char().
int lang_locale_data_load_from_lib (LANG_LOCALE_DATA * lld, void * lib_handle, const LOCALE_FILE * lf, bool is_load_for_dump)
Definition at line 6750 of file language_support.c.
References alphabet_data::a_type, coll_opt::allow_index_opt, coll_opt::allow_like_rewrite, coll_opt::allow_prefix_index, lang_locale_data::alphabet, ALPHABET_ASCII, ALPHABET_TAILORED, ALPHABET_UNICODE, lang_locale_data::am_pm, lang_locale_data::am_pm_parse_order, ARG_FILE_LINE, assert, lang_collation::built_in, text_conversion::byte_flag, CAL_AM_PM_COUNT, CAL_DAY_COUNT, CAL_MONTH_COUNT, lang_locale_data::checksum, lang_collation::codeset, lang_collation::coll, coll_data::coll_name, con_Iso_8859_1_conv, con_Iso_8859_9_conv, text_conversion::conv_type, coll_data::count_contr, lang_locale_data::date_format, lang_locale_data::datetime_format, lang_locale_data::datetimetz_format, lang_locale_data::day_name, lang_locale_data::day_parse_order, lang_locale_data::day_short_name, lang_locale_data::day_short_parse_order, lang_locale_data::default_currency_code, lang_collation::default_lang, lang_locale_data::default_lang_coll, ER_ERROR_SEVERITY, ER_LOC_INIT, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), ERR_MSG_SIZE, lang_collation::fastcmp, i, lang_locale_data::ident_alphabet, INTL_CODESET_UTF8, lang_get_collation_by_name(), lang_load_coll_from_lib(), lang_load_count_coll_from_lib(), lang_load_get_coll_name_from_lib(), lang_locale_load_alpha_from_lib(), lang_locale_load_normalization_from_lib(), lang_mht2str_utf8(), lang_mht2str_utf8_exp(), lang_locale_data::lang_name, lang_next_coll_char_utf8(), lang_next_coll_seq_utf8_w_contr(), lang_split_key_utf8(), lang_split_key_w_exp(), lang_strcmp_utf8(), lang_strcmp_utf8_uca(), lang_strcmp_utf8_w_contr(), lang_strmatch_utf8(), lang_strmatch_utf8_uca(), lang_strmatch_utf8_w_contr(), locale_file::lib_file, LOC_LIB_SYMBOL_NAME_SIZE, locale_file::locale_name, LOG_LOCALE_ERROR, lang_collation::mht2str, lang_locale_data::month_name, lang_locale_data::month_parse_order, lang_locale_data::month_short_name, lang_locale_data::month_short_parse_order, lang_collation::next_coll_seq, text_conversion::nl_lang_str, NO_ERROR, NULL, lang_locale_data::number_decimal_sym, lang_locale_data::number_group_sym, lang_collation::options, register_collation(), uca_options::sett_strength, SHLIB_GET_ADDR, SHLIB_GET_VAL, lang_collation::split_key, strlen, lang_collation::strmatch, TAILOR_QUATERNARY, TEXT_CONV_GENERIC_1BYTE, TEXT_CONV_GENERIC_2BYTE, TEXT_CONV_ISO_88591_BUILTIN, TEXT_CONV_ISO_88599_BUILTIN, TEXT_CONV_NO_CONVERSION, text_conversion::text_first_cp, text_conversion::text_last_cp, text_conversion::text_to_utf8, lang_locale_data::time_format, lang_locale_data::timestamp_format, lang_locale_data::timestamptz_format, lang_locale_data::txt_conv, coll_data::uca_exp_num, coll_data::uca_opt, lang_locale_data::unicode_norm, text_conversion::utf8_first_cp, text_conversion::utf8_last_cp, text_conversion::utf8_to_text, and text_conversion::win_codepages.
Referenced by dumplocale(), and init_user_locales().
int lang_locales_count (bool check_codeset)
Definition at line 1347 of file language_support.c.
References cubregex::count(), i, lang_Count_locales, lang_locale_data::next_lld, and NULL.
Referenced by sboot_get_locales_info().
int lang_set_charset (const INTL_CODESET codeset)
Definition at line 1208 of file language_support.c.
References ARG_FILE_LINE, lang_defaults::codeset, ER_ERROR_SEVERITY, ER_LOC_INIT, er_set(), INTL_CODESET_LAST, lang_Charset_initialized, lang_Loc_charset, NO_ERROR, and tp_apply_sys_charset().
Referenced by boot_restart_client(), boot_restart_server(), and xboot_emergency_patch().
int lang_set_charset_lang (const char * lang_charset)
Definition at line 1137 of file language_support.c.
References ARG_FILE_LINE, assert, check_env_lang_val(), ER_ERROR_SEVERITY, ER_LOC_INIT, er_set(), ERR_MSG_SIZE, INTL_CODESET_NONE, INTL_CODESET_UTF8, lang_Charset_initialized, lang_get_builtin_lang_id_from_name(), lang_get_default_codeset(), lang_Init_w_error, lang_Initialized, lang_is_codeset_allowed(), lang_Lang_id, lang_Lang_name, lang_Language_initialized, lang_Loc_charset, lang_Loc_name, NO_ERROR, NULL, set_current_locale(), set_default_lang(), strncpy_bufsize, and tp_apply_sys_charset().
Referenced by boot_initialize_client(), lang_set_language(), and xboot_emergency_patch().
int lang_set_flag_from_lang (const char * lang_str, bool has_user_format, bool has_user_lang, int * flag)
Definition at line 2303 of file language_support.c.
References assert, INTL_LANG_ENGLISH, lang_defaults::lang, lang_get_lang_id_from_name(), lang_set_flag_from_lang_id(), and NULL.
Referenced by do_evaluate_default_expr(), pt_check_default_vclass_query_spec(), pt_eval_expr_type(), pt_find_attr_in_class_list(), pt_resolve_default_value(), and qexec_execute_insert().
int lang_set_flag_from_lang_id (const INTL_LANG lang, bool has_user_format, bool has_user_lang, int * flag)
Definition at line 2341 of file language_support.c.
References INTL_LANG_ENGLISH, and lang_Count_locales.
Referenced by lang_set_flag_from_lang().
void lang_set_generic_unicode_norm (UNICODE_NORMALIZATION * norm)
Definition at line 7452 of file language_support.c.
Referenced by init_user_locales(), and lang_final().
int lang_set_language (const char * lang_str)
Definition at line 1231 of file language_support.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_LOC_INIT, er_set(), lang_charset(), lang_Charset_initialized, lang_get_charset_env_string(), LANG_MAX_LANGNAME, lang_set_charset_lang(), and NULL.
Referenced by boot_restart_client(), and boot_restart_server().
void lang_set_parser_use_client_charset (bool use)
Definition at line 2750 of file language_support.c.
References lang_Parser_use_client_charset.
Referenced by au_find_user(), do_run_update_query_for_class(), parser_parse_string_use_sys_charset(), and sch_query_execute().
int lang_strmatch_utf8_uca_w_coll_data (const COLL_DATA * coll_data, bool is_match, const unsigned char * str1, const int size1, const unsigned char * str2, const int size2, const unsigned char * escape, const bool has_last_escape, int * str1_match_size, bool ignore_trailing_space)
Definition at line 4389 of file language_support.c.
References assert, lang_back_strmatch_utf8_uca_w_level(), lang_strmatch_utf8_uca_w_level(), uca_options::sett_backwards, uca_options::sett_caseFirst, uca_options::sett_caseLevel, uca_options::sett_strength, TAILOR_PRIMARY, TAILOR_SECONDARY, TAILOR_TERTIARY, and coll_data::uca_opt.
Referenced by comp_func_coll_uca_exp(), lang_strcmp_utf8_uca(), and lang_strmatch_utf8_uca().
const ALPHABET_DATA* lang_user_alphabet_w_coll (const int collation_id)
Definition at line 1741 of file language_support.c.
References lang_locale_data::alphabet, assert, lang_collation::default_lang, lang_get_collation(), and NULL.
Referenced by db_string_lower(), and db_string_upper().
Variable Documentation
LANG_COLLATION* lang_Collations[LANG_MAX_COLLATIONS]
Definition at line 67 of file language_support.c.
INTL_CODESET lang_Loc_charset
Definition at line 66 of file language_support.c.
Referenced by lang_charset(), lang_set_charset(), lang_set_charset_lang(), set_current_locale(), and set_default_lang().