CUBRID Engine: src/base/language_support.c File Reference
language_support.c File Reference
#include "config.h"
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <langinfo.h>
#include "language_support.h"
#include "chartype.h"
#include "environment_variable.h"
#include "memory_hash.h"
#include "object_primitive.h"
#include "util_func.h"
#include <dlfcn.h>
#include "tz_support.h"
#include "db_date.h"
#include "string_opfunc.h"
#include "authenticate.h"
#include "db.h"
#include "dbtype.h"
Classes
struct lang_defaults
Macros
#define PAD ' ' /* str_pad_char(INTL_CODESET_ISO88591, pad, &pad_size) */
#define SPACE PAD /* smallest character in the collation sequence */
#define ZERO '\0' /* space is treated as zero */
#define EUC_SPACE 0xa1 /* for euckr */
#define ASCII_SPACE 0x20
#define LANG_CHAR_COUNT_EN 256
#define LANG_CHAR_COUNT_TR 352
#define LANG_COLL_GENERIC_SORT_OPT
#define LANG_COLL_NO_EXP 0, NULL, NULL, NULL
#define LANG_COLL_NO_CONTR NULL, 0, 0, NULL, 0, 0
#define LANG_NO_NORMALIZATION {NULL, 0, NULL, NULL, 0}
#define DEFAULT_COLL_OPTIONS {true, true, true}
#define CI_COLL_OPTIONS {false, false, true}
#define LOCALE_DUMMY_ALPHABET(codeset) {ALPHABET_TAILORED, (codeset), 0, 0, NULL, 0, NULL, false}
#define LOCALE_NULL_DATE_FORMATS NULL, NULL, NULL, NULL, NULL, NULL
#define LOCALE_NULL_CALENDAR_NAMES
#define LANG_W_MAP_COUNT_EN 256
#define ADD_TO_HASH(pseudo_key, w)
#define GET_UCA_WEIGHT(l, i, l13w, l4w)
#define INTL_CONTR_FOUND(v) (((v) & INTL_MASK_CONTR) == INTL_MASK_CONTR)
#define GET_SYM_ADDR(lib, sym) dlsym(lib, sym)
#define SHLIB_GET_ADDR(v, SYM_NAME, SYM_TYPE, lh, LOC_NAME)
#define SHLIB_GET_ADDR_W_REF(v, SYM_NAME, SYM_TYPE, lh, LOC_NAME)
#define SHLIB_GET_VAL(v, SYM_NAME, SYM_TYPE, lh, LOC_NAME)
Typedefs
typedef struct lang_defaults LANG_DEFAULTS
Functions
static int set_current_locale (void)
static int set_msg_lang_from_env (void)
static int check_env_lang_val (char *env_val, char *lang_name, char **charset_ptr, INTL_CODESET *codeset)
static void set_default_lang (void)
static void lang_unload_libraries (void)
static void destroy_user_locales (void)
static int init_user_locales (void)
static LANG_LOCALE_DATA * find_lang_locale_data (const char *name, const INTL_CODESET codeset, LANG_LOCALE_DATA **last_lang_locale)
static int register_lang_locale_data (LANG_LOCALE_DATA *lld)
static void free_lang_locale_data (LANG_LOCALE_DATA *lld)
static int register_collation (LANG_COLLATION *coll)
static bool lang_is_codeset_allowed (const INTL_LANG intl_id, const INTL_CODESET codeset)
static int lang_get_builtin_lang_id_from_name (const char *lang_name, INTL_LANG *lang_id)
static INTL_CODESET lang_get_default_codeset (const INTL_LANG intl_id)
static int lang_strmatch_byte (const LANG_COLLATION *lang_coll, bool is_match, const unsigned char *str1, int size1, const unsigned char *str2, int size2, const unsigned char *escape, const bool has_last_escape, int *str1_match_size, bool ignore_trailing_space)
static int lang_fastcmp_byte (const LANG_COLLATION *lang_coll, const unsigned char *string1, const int size1, const unsigned char *string2, const int size2, bool ignore_trailing_space)
static int lang_fastcmp_binary (const LANG_COLLATION *lang_coll, const unsigned char *string1, const int size1, const unsigned char *string2, const int size2, bool ignore_trailing_space)
static int lang_strmatch_binary (const LANG_COLLATION *lang_coll, bool is_match, const unsigned char *str1, int size1, const unsigned char *str2, int size2, const unsigned char *escape, const bool has_last_escape, int *str1_match_size, bool ignore_trailing_space)
static int lang_next_alpha_char_iso88591 (const LANG_COLLATION *lang_coll, const unsigned char *seq, const int size, unsigned char *next_seq, int *len_next, bool ignore_trailing_space)
static int lang_next_coll_byte (const LANG_COLLATION *lang_coll, const unsigned char *seq, const int size, unsigned char *next_seq, int *len_next, bool ignore_trailing_space)
static int lang_strcmp_utf8 (const LANG_COLLATION *lang_coll, const unsigned char *str1, const int size1, const unsigned char *str2, const int size2, bool ignore_trailing_space)
static int lang_strmatch_utf8 (const LANG_COLLATION *lang_coll, bool is_match, const unsigned char *str1, int size1, const unsigned char *str2, int size2, const unsigned char *escape, const bool has_last_escape, int *str1_match_size, bool ignore_trailing_space)
static int lang_strcmp_utf8_w_contr (const LANG_COLLATION *lang_coll, const unsigned char *str1, const int size1, const unsigned char *str2, const int size2, bool ignore_trailing_space)
static unsigned int lang_get_w_first_el (const COLL_DATA *coll, const unsigned char *str, const int str_size, unsigned char **next_char, bool ignore_trailing_space)
static int lang_strmatch_utf8_w_contr (const LANG_COLLATION *lang_coll, bool is_match, const unsigned char *str1, int size1, const unsigned char *str2, int size2, const unsigned char *escape, const bool has_last_escape, int *str1_match_size, bool ignore_trailing_space)
static COLL_CONTRACTION * lang_get_contr_for_string (const COLL_DATA *coll_data, const unsigned char *str, const int str_size, unsigned int cp)
static void lang_get_uca_w_l13 (const COLL_DATA *coll_data, const bool use_contractions, const unsigned char *str, const int size, UCA_L13_W **uca_w_l13, int *num_ce, unsigned char **str_next, unsigned int *cp_out)
static void lang_get_uca_back_weight_l13 (const COLL_DATA *coll_data, const bool use_contractions, const unsigned char *str_start, const unsigned char *str_last, UCA_L13_W **uca_w_l13, int *num_ce, unsigned char **str_prev, unsigned int *cp_out)
static void lang_get_uca_w_l4 (const COLL_DATA *coll_data, const bool use_contractions, const unsigned char *str, const int size, UCA_L4_W **uca_w_l4, int *num_ce, unsigned char **str_next, unsigned int *cp_out)
static int lang_strmatch_utf8_uca_w_level (const COLL_DATA *coll_data, const int level, bool is_match, const unsigned char *str1, const int size1, const unsigned char *str2, const int size2, const unsigned char *escape, const bool has_last_escape, int *offset_next_level, int *str1_match_size, bool ignore_trailing_space)
static int lang_back_strmatch_utf8_uca_w_level (const COLL_DATA *coll_data, bool is_match, const unsigned char *str1, const int size1, const unsigned char *str2, const int size2, const unsigned char *escape, const bool has_last_escape, int *offset_next_level, int *str1_match_size, bool ignore_trailing_space)
static int lang_strcmp_utf8_uca (const LANG_COLLATION *lang_coll, const unsigned char *str1, const int size1, const unsigned char *str2, const int size2, bool ignore_trailing_space)
static int lang_strmatch_utf8_uca (const LANG_COLLATION *lang_coll, bool is_match, const unsigned char *str1, const int size1, const unsigned char *str2, const int size2, const unsigned char *escape, const bool has_last_escape, int *str1_match_size, bool ignore_trailing_space)
static int lang_str_utf8_trail_zero_weights (const LANG_COLLATION *lang_coll, const unsigned char *str, int size)
static int lang_str_utf8_trail_zero_weights_w_exp (const COLL_DATA *coll_data, const int level, const unsigned char *str, int size)
static int lang_next_coll_char_utf8 (const LANG_COLLATION *lang_coll, const unsigned char *seq, const int size, unsigned char *next_seq, int *len_next, bool ignore_trailing_space)
static int lang_next_coll_seq_utf8_w_contr (const LANG_COLLATION *lang_coll, const unsigned char *seq, const int size, unsigned char *next_seq, int *len_next, bool ignore_trailing_space)
static int lang_split_key_iso (const LANG_COLLATION *lang_coll, const bool is_desc, const unsigned char *str1, const int size1, const unsigned char *str2, const int size2, const unsigned char **key, int *byte_size, bool ignore_trailing_space)
static int lang_split_key_byte (const LANG_COLLATION *lang_coll, const bool is_desc, const unsigned char *str1, const int size1, const unsigned char *str2, const int size2, const unsigned char **key, int *byte_size, bool ignore_trailing_space)
static int lang_split_key_binary (const LANG_COLLATION *lang_coll, const bool is_desc, const unsigned char *str1, const int size1, const unsigned char *str2, const int size2, const unsigned char **key, int *byte_size, bool ignore_trailing_space)
static int lang_split_key_utf8 (const LANG_COLLATION *lang_coll, const bool is_desc, const unsigned char *str1, const int size1, const unsigned char *str2, const int size2, const unsigned char **key, int *byte_size, bool ignore_trailing_space)
static int lang_split_key_w_exp (const LANG_COLLATION *lang_coll, const bool is_desc, const unsigned char *str1, const int size1, const unsigned char *str2, const int size2, const unsigned char **key, int *byte_size, bool ignore_trailing_space)
static int lang_split_key_euckr (const LANG_COLLATION *lang_coll, const bool is_desc, const unsigned char *str1, const int size1, const unsigned char *str2, const int size2, const unsigned char **key, int *byte_size, bool ignore_trailing_space)
static unsigned int lang_mht2str_byte (const LANG_COLLATION *lang_coll, const unsigned char *str, const int size)
static unsigned int lang_mht2str_default (const LANG_COLLATION *lang_coll, const unsigned char *str, const int size)
static unsigned int lang_mht2str_utf8 (const LANG_COLLATION *lang_coll, const unsigned char *str, const int size)
static unsigned int lang_mht2str_utf8_exp (const LANG_COLLATION *lang_coll, const unsigned char *str, const int size)
static unsigned int lang_mht2str_ko (const LANG_COLLATION *lang_coll, const unsigned char *str, const int size)
static void lang_init_coll_en_ci (LANG_COLLATION *lang_coll)
static void lang_init_coll_en_cs (LANG_COLLATION *lang_coll)
static void lang_init_coll_Utf8_tr_cs (LANG_COLLATION *lang_coll)
static int lang_fastcmp_ko (const LANG_COLLATION *lang_coll, const unsigned char *string1, int size1, const unsigned char *string2, int size2, bool ignore_trailing_space)
static int lang_strmatch_ko (const LANG_COLLATION *lang_coll, bool is_match, const unsigned char *str1, int size1, const unsigned char *str2, int size2, const unsigned char *escape, const bool has_last_escape, int *str1_match_size, bool ignore_trailing_space)
static int lang_next_alpha_char_ko (const LANG_COLLATION *lang_coll, const unsigned char *seq, const int size, unsigned char *next_seq, int *len_next, bool ignore_trailing_space)
static int lang_locale_load_alpha_from_lib (ALPHABET_DATA *a, bool load_w_identifier_name, const char *alpha_suffix, void *lib_handle, const LOCALE_FILE *lf)
static int lang_locale_load_normalization_from_lib (UNICODE_NORMALIZATION *norm, void *lib_handle, const LOCALE_FILE *lf)
static void lang_free_collations (void)
static void lang_initloc_en_iso88591 (LANG_LOCALE_DATA *ld)
static void lang_initloc_en_binary (LANG_LOCALE_DATA *ld)
static void lang_init_common_en_cs (COLL_DATA *coll_data)
static void lang_init_common_en_ci (COLL_DATA *coll_data)
static void lang_initloc_en_utf8 (LANG_LOCALE_DATA *ld)
static void lang_initloc_tr_iso (LANG_LOCALE_DATA *ld)
static void lang_initloc_ko_iso (LANG_LOCALE_DATA *ld)
static void lang_initloc_ko_utf8 (LANG_LOCALE_DATA *ld)
static void lang_initloc_ko_euc (LANG_LOCALE_DATA *ld)
static void lang_initloc_tr_utf8 (LANG_LOCALE_DATA *ld)
void lang_init_builtin (void)
int lang_init (void)
void lang_init_console_txt_conv (void)
int lang_set_charset_lang (const char *lang_charset)
int lang_set_charset (const INTL_CODESET codeset)
int lang_set_language (const char *lang_str)
int lang_locales_count (bool check_codeset)
bool lang_is_coll_name_allowed (const char *name)
LANG_COLLATION * lang_get_collation (const int coll_id)
const char * lang_get_collation_name (const int coll_id)
LANG_COLLATION * lang_get_collation_by_name (const char *coll_name)
int lang_collation_count (void)
const char * lang_get_codeset_name (int codeset_id)
const ALPHABET_DATA * lang_user_alphabet_w_coll (const int collation_id)
const char * lang_get_msg_Loc_name (void)
const char * lang_get_Lang_name (void)
INTL_LANG lang_id (void)
DB_CURRENCY lang_currency ()
DB_CURRENCY lang_locale_currency (const char *locale_str)
INTL_CODESET lang_charset (void)
void lang_final (void)
const char * lang_currency_symbol (DB_CURRENCY curr)
bool lang_check_identifier (const char *name, int length)
const LANG_LOCALE_DATA * lang_locale (void)
const LANG_LOCALE_DATA * lang_get_specific_locale (const INTL_LANG lang, const INTL_CODESET codeset)
const LANG_LOCALE_DATA * lang_get_first_locale_for_lang (const INTL_LANG lang)
int lang_get_lang_id_from_name (const char *lang_name, INTL_LANG *lang_id)
const char * lang_get_lang_name_from_id (const INTL_LANG lang_id)
int lang_set_flag_from_lang (const char *lang_str, bool has_user_format, bool has_user_lang, int *flag)
int lang_set_flag_from_lang_id (const INTL_LANG lang, bool has_user_format, bool has_user_lang, int *flag)
INTL_LANG lang_get_lang_id_from_flag (const int flag, bool *has_user_format, bool *has_user_lang)
const char * lang_date_format_parse (const INTL_LANG lang_id, const INTL_CODESET codeset, const DB_TYPE type, INTL_CODESET *format_codeset)
char lang_digit_grouping_symbol (const INTL_LANG lang_id)
char lang_digit_fractional_symbol (const INTL_LANG lang_id)
TEXT_CONVERSION * lang_get_txt_conv (void)
const char * lang_charset_name (const INTL_CODESET codeset)
const char * lang_charset_cubrid_name (const INTL_CODESET codeset)
int lang_get_charset_env_string (char *buf, int buf_size, const char *lang_name, const INTL_CODESET codeset)
int lang_db_put_charset (void)
int lang_charset_name_to_id (const char *name, INTL_CODESET *codeset)
INTL_CODESET lang_get_client_charset (void)
int lang_get_client_collation (void)
void lang_set_parser_use_client_charset (bool use)
bool lang_get_parser_use_client_charset (void)
INTL_CODESET lang_charset_cubrid_name_to_id (const char *name)
const char * lang_charset_introducer (const INTL_CODESET codeset)
int lang_strmatch_utf8_uca_w_coll_data (const COLL_DATA *coll_data, bool is_match, const unsigned char *str1, const int size1, const unsigned char *str2, const int size2, const unsigned char *escape, const bool has_last_escape, int *str1_match_size, bool ignore_trailing_space)
int lang_locale_data_load_from_lib (LANG_LOCALE_DATA *lld, void *lib_handle, const LOCALE_FILE *lf, bool is_load_for_dump)
int lang_load_count_coll_from_lib (int *count_coll, void *lib_handle, const LOCALE_FILE *lf)
int lang_load_get_coll_name_from_lib (const int coll_pos, char **coll_name, void *lib_handle, const LOCALE_FILE *lf)
int lang_load_coll_from_lib (COLL_DATA *cd, void *lib_handle, const LOCALE_FILE *lf)
int lang_load_library (const char *lib_file, void **handle)
UNICODE_NORMALIZATION * lang_get_generic_unicode_norm (void)
void lang_set_generic_unicode_norm (UNICODE_NORMALIZATION *norm)
int lang_check_coll_compat (const LANG_COLL_COMPAT *coll_array, const int coll_cnt, const char *client_text, const char *server_text)
int lang_check_locale_compat (const LANG_LOCALE_COMPAT *loc_array, const int loc_cnt, const char *client_text, const char *server_text)
Variables
static INTL_LANG lang_Lang_id = INTL_LANG_ENGLISH
static char lang_Loc_name [LANG_MAX_LANGNAME] = LANG_NAME_DEFAULT
static char lang_Msg_loc_name [LANG_MAX_LANGNAME] = LANG_NAME_DEFAULT
static char lang_Lang_name [LANG_MAX_LANGNAME] = LANG_NAME_DEFAULT
static DB_CURRENCY lang_Loc_currency = DB_CURRENCY_DOLLAR
INTL_CODESET lang_Loc_charset = INTL_CODESET_ISO88591
LANG_COLLATION * lang_Collations [LANG_MAX_COLLATIONS] = { NULL }
static unsigned int lang_Weight_EN_cs [LANG_CHAR_COUNT_EN]
static unsigned int lang_Next_alpha_char_EN_cs [LANG_CHAR_COUNT_EN]
static unsigned int lang_Weight_EN_ci [LANG_CHAR_COUNT_EN]
static unsigned int lang_Next_alpha_char_EN_ci [LANG_CHAR_COUNT_EN]
static unsigned int lang_Weight_EN_cs_ti [LANG_CHAR_COUNT_EN]
static unsigned int lang_Next_alpha_char_EN_cs_ti [LANG_CHAR_COUNT_EN]
static unsigned int lang_Weight_EN_ci_ti [LANG_CHAR_COUNT_EN]
static unsigned int lang_Next_alpha_char_EN_ci_ti [LANG_CHAR_COUNT_EN]
static unsigned int lang_Weight_TR [LANG_CHAR_COUNT_TR]
static unsigned int lang_Next_alpha_char_TR [LANG_CHAR_COUNT_TR]
static unsigned int lang_Weight_TR_ti [LANG_CHAR_COUNT_TR]
static unsigned int lang_Next_alpha_char_TR_ti [LANG_CHAR_COUNT_TR]
static bool lang_Builtin_initialized = false
static bool lang_Initialized = false
static bool lang_Init_w_error = false
static bool lang_Charset_initialized = false
static bool lang_Language_initialized = false
static bool lang_Msg_env_initialized = false
LANG_DEFAULTS builtin_Langs []
static unsigned int lang_upper_TR [LANG_CHAR_COUNT_TR]
static unsigned int lang_lower_TR [LANG_CHAR_COUNT_TR]
static unsigned int lang_upper_i_TR [LANG_CHAR_COUNT_TR]
static unsigned int lang_lower_i_TR [LANG_CHAR_COUNT_TR]
static char lang_time_format_TR [] = "HH24:MI:SS"
static char lang_date_format_TR [] = "DD.MM.YYYY"
static char lang_datetime_format_TR [] = "HH24:MI:SS.FF DD.MM.YYYY"
static char lang_timestamp_format_TR [] = "HH24:MI:SS DD.MM.YYYY"
static char lang_datetimetz_format_TR [] = "HH24:MI:SS.FF DD.MM.YYYY TZR"
static char lang_timestamptz_format_TR [] = "HH24:MI:SS DD.MM.YYYY TZR"
static void ** loclib_Handle = NULL
static int loclib_Handle_size = 0
static int loclib_Handle_count = 0
static TEXT_CONVERSION * console_Conv = NULL
TEXT_CONVERSION con_Iso_8859_1_conv
TEXT_CONVERSION con_Iso_8859_9_conv
static LANG_LOCALE_DATA * lang_Loaded_locales [LANG_MAX_LOADED_LOCALES] = { NULL }
static int lang_Count_locales = 0
static int lang_Count_collations = 0
static UNICODE_NORMALIZATION * generic_Unicode_norm = NULL
static const DB_CHARSET lang_Db_charsets []
static unsigned int lang_upper_EN [LANG_CHAR_COUNT_EN]
static unsigned int lang_lower_EN [LANG_CHAR_COUNT_EN]
static int lang_w_map_EN [LANG_W_MAP_COUNT_EN]
static LANG_COLLATION coll_Utf8_en_cs
static LANG_COLLATION coll_Iso88591_en_cs
static LANG_LOCALE_DATA lc_English_iso88591
static LANG_LOCALE_DATA lc_English_utf8
static LANG_LOCALE_DATA lc_Turkish_iso88591
static LANG_LOCALE_DATA lc_Korean_iso88591
static LANG_COLLATION coll_Utf8_ko_cs
static LANG_LOCALE_DATA lc_Korean_utf8
static LANG_COLLATION coll_Euckr_bin
static LANG_LOCALE_DATA lc_Korean_euckr
static LANG_COLLATION coll_Binary
static LANG_LOCALE_DATA lc_English_binary
static LANG_LOCALE_DATA * lang_Loc_data = &lc_English_iso88591
static LANG_COLLATION coll_Iso_binary
static LANG_COLLATION coll_Utf8_binary
static LANG_COLLATION coll_Iso88591_en_ci
static LANG_COLLATION coll_Utf8_en_ci
static LANG_COLLATION coll_Utf8_tr_cs
static LANG_LOCALE_DATA lc_Turkish_utf8
static LANG_COLLATION * built_In_collations []
static bool lang_Parser_use_client_charset = true
static UCA_L13_W uca_l13_max_weight = 0xffffffff
static UCA_L4_W uca_l4_max_weight = 0xffff
Macro Definition Documentation
#define ADD_TO_HASH (pseudo_key, w)
Value:
do {                        \
    unsigned int i;             \
    pseudo_key = (pseudo_key << 4) + w;     \
    i = pseudo_key & 0xf0000000;        \
    if (i != 0)                 \
      {                     \
    pseudo_key ^= i >> 24;          \
    pseudo_key ^= i;            \
      }                     \
  } while (0)
Definition at line 3178 of file language_support.c.
Referenced by lang_mht2str_byte(), lang_mht2str_ko(), lang_mht2str_utf8(), and lang_mht2str_utf8_exp().
#define ASCII_SPACE 0x20
Definition at line 59 of file language_support.c.
Referenced by lang_back_strmatch_utf8_uca_w_level(), lang_fastcmp_ko(), lang_get_w_first_el(), lang_mht2str_ko(), lang_split_key_euckr(), lang_split_key_w_exp(), lang_strmatch_ko(), and lang_strmatch_utf8_uca_w_level().
#define CI_COLL_OPTIONS {false, false, true}
Definition at line 101 of file language_support.c.
#define DEFAULT_COLL_OPTIONS {true, true, true}
Definition at line 100 of file language_support.c.
#define EUC_SPACE 0xa1 /* for euckr */
Definition at line 58 of file language_support.c.
Referenced by lang_fastcmp_ko(), lang_mht2str_ko(), lang_split_key_euckr(), and lang_strmatch_ko().
#define GET_SYM_ADDR (lib, sym) dlsym(lib, sym)
Definition at line 6701 of file language_support.c.
#define GET_UCA_WEIGHT (l, i, l13w, l4w)
Value:
((l == 0) ? (UCA_GET_L1_W (l13w[i])) :  \
   (l == 1) ? (UCA_GET_L2_W (l13w[i])) :    \
   (l == 2) ? (UCA_GET_L3_W (l13w[i])) : (l4w[i]))
Definition at line 3574 of file language_support.c.
Referenced by lang_mht2str_utf8_exp(), lang_str_utf8_trail_zero_weights_w_exp(), and lang_strmatch_utf8_uca_w_level().
#define INTL_CONTR_FOUND (v) (((v) & INTL_MASK_CONTR) == INTL_MASK_CONTR)
Definition at line 3579 of file language_support.c.
Referenced by lang_back_strmatch_utf8_uca_w_level(), and lang_strmatch_utf8_uca_w_level().
#define LANG_CHAR_COUNT_EN 256
Definition at line 71 of file language_support.c.
Referenced by lang_initloc_en_utf8().
#define LANG_CHAR_COUNT_TR 352
Definition at line 72 of file language_support.c.
Referenced by lang_init_coll_Utf8_tr_cs(), and lang_initloc_tr_utf8().
#define LANG_COLL_GENERIC_SORT_OPT
Value:
{TAILOR_UNDEFINED, false, false, 1, false, CONTR_IGNORE, false, \
   MATCH_CONTR_BOUND_ALLOW}
Definition at line 74 of file language_support.c.
#define LANG_COLL_NO_CONTR NULL, 0, 0, NULL, 0, 0
Definition at line 78 of file language_support.c.
#define LANG_COLL_NO_EXP 0, NULL, NULL, NULL
Definition at line 77 of file language_support.c.
#define LANG_NO_NORMALIZATION {NULL, 0, NULL, NULL, 0}
Definition at line 80 of file language_support.c.
#define LANG_W_MAP_COUNT_EN 256
Definition at line 321 of file language_support.c.
#define LOCALE_DUMMY_ALPHABET (codeset) {ALPHABET_TAILORED, (codeset), 0, 0, NULL, 0, NULL, false}
Definition at line 190 of file language_support.c.
#define LOCALE_NULL_CALENDAR_NAMES
Value:
{NULL}, {NULL}, {NULL}, {NULL}, {NULL}, \
  NULL, NULL, NULL, NULL, NULL
Definition at line 196 of file language_support.c.
#define LOCALE_NULL_DATE_FORMATS NULL, NULL, NULL, NULL, NULL, NULL
Definition at line 193 of file language_support.c.
#define PAD ' ' /* str_pad_char(INTL_CODESET_ISO88591, pad, &pad_size) */
Definition at line 54 of file language_support.c.
#define SHLIB_GET_ADDR (v, SYM_NAME, SYM_TYPE, lh, LOC_NAME)
Value:
do {                                                \
    if (snprintf (sym_name, LOC_LIB_SYMBOL_NAME_SIZE - 1, "" SYM_NAME "_%s", LOC_NAME) < 0)     \
      goto error_loading_symbol;                                        \
    v = (SYM_TYPE) GET_SYM_ADDR (lh, sym_name);                         \
    if (v == NULL)                                      \
      {                                             \
    goto error_loading_symbol;                              \
      }                                             \
  } while (0)
Definition at line 6704 of file language_support.c.
Referenced by lang_load_coll_from_lib(), lang_load_get_coll_name_from_lib(), lang_locale_data_load_from_lib(), lang_locale_load_alpha_from_lib(), and lang_locale_load_normalization_from_lib().
#define SHLIB_GET_ADDR_W_REF (v, SYM_NAME, SYM_TYPE, lh, LOC_NAME)
Value:
do {                                        \
    snprintf (sym_name, LOC_LIB_SYMBOL_NAME_SIZE, "" SYM_NAME "_ref_%s",    \
          LOC_NAME);                            \
    temp_char_sym = (char *) GET_SYM_ADDR (lh, sym_name);           \
    if (temp_char_sym == NULL)                          \
      {                                     \
    goto error_loading_symbol;                      \
      }                                     \
    strcpy (sym_name, temp_char_sym);                       \
    v = (SYM_TYPE) GET_SYM_ADDR (lh, sym_name);                 \
    if (v == NULL)                              \
      {                                     \
    goto error_loading_symbol;                      \
      }                                     \
  } while (0)
Definition at line 6715 of file language_support.c.
Referenced by lang_load_coll_from_lib().
#define SHLIB_GET_VAL (v, SYM_NAME, SYM_TYPE, lh, LOC_NAME)
Value:
do {                                \
    SYM_TYPE* aux;                      \
    SHLIB_GET_ADDR(aux, SYM_NAME, SYM_TYPE*, lh, LOC_NAME); \
    v = *aux;                           \
  } while (0);
Definition at line 6732 of file language_support.c.
Referenced by lang_load_coll_from_lib(), lang_load_count_coll_from_lib(), lang_locale_data_load_from_lib(), lang_locale_load_alpha_from_lib(), and lang_locale_load_normalization_from_lib().
#define SPACE PAD /* smallest character in the collation sequence */
Definition at line 55 of file language_support.c.
Referenced by lang_fastcmp_byte(), lang_fastcmp_ko(), lang_split_key_euckr(), lang_strmatch_byte(), and lang_strmatch_utf8().
#define ZERO '\0' /* space is treated as zero */
Definition at line 56 of file language_support.c.
Referenced by is_number(), lang_fastcmp_byte(), lang_fastcmp_ko(), lang_mht2str_ko(), lang_split_key_iso(), lang_strmatch_byte(), lang_strmatch_ko(), and lang_strmatch_utf8().
Typedef Documentation
typedef struct lang_defaults LANG_DEFAULTS
Definition at line 111 of file language_support.c.
Function Documentation
static int check_env_lang_val (char * env_val, char * lang_name, char ** charset_ptr, INTL_CODESET * codeset) static
Definition at line 1264 of file language_support.c.
References assert, envvar_trim_char(), ER_FAILED, INTL_CODESET_ISO88591, INTL_CODESET_KSC5601_EUC, INTL_CODESET_UTF8, intl_tolower_iso8859(), intl_toupper_iso8859(), LANG_CHARSET_EUCKR, LANG_CHARSET_EUCKR_ALIAS1, LANG_CHARSET_ISO88591, LANG_CHARSET_ISO88591_ALIAS1, LANG_CHARSET_ISO88591_ALIAS2, LANG_CHARSET_UTF8, LANG_CHARSET_UTF8_ALIAS1, NO_ERROR, NULL, and strlen.
Referenced by lang_set_charset_lang(), and set_msg_lang_from_env().
static void destroy_user_locales (void) static
Definition at line 7389 of file language_support.c.
References assert, free_lang_locale_data(), i, lang_Count_locales, and NULL.
Referenced by init_user_locales(), and lang_final().
static LANG_LOCALE_DATA * find_lang_locale_data (const char * name, const INTL_CODESET codeset, LANG_LOCALE_DATA ** last_lang_locale) static
Definition at line 1761 of file language_support.c.
References assert, lang_locale_data::codeset, i, lang_Count_locales, lang_defaults::lang_name, lang_locale_data::next_lld, and NULL.
Referenced by init_user_locales(), and register_lang_locale_data().
static void free_lang_locale_data (LANG_LOCALE_DATA * lld) static
Definition at line 1860 of file language_support.c.
References assert, text_conversion::init_conv_func, lang_locale_data::is_user_data, lang_locale_data::next_lld, NULL, and lang_locale_data::txt_conv.
Referenced by destroy_user_locales().
static int init_user_locales (void) static
Definition at line 1378 of file language_support.c.
References lang_locale_data::alphabet, ARG_FILE_LINE, assert, lang_locale_data::codeset, alphabet_data::codeset, text_conversion::conv_type, destroy_user_locales(), ER_ERROR_SEVERITY, ER_LOC_INIT, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), ERR_MSG_SIZE, error(), find_lang_locale_data(), free_and_init, i, lang_locale_data::ident_alphabet, text_conversion::init_conv_func, INTL_CODESET_UTF8, INTL_LANG_USER_DEF_START, intl_text_dbcs_to_utf8(), intl_text_single_byte_to_utf8(), intl_text_utf8_to_dbcs(), intl_text_utf8_to_single_byte(), lang_locale_data::is_initialized, lang_locale_data::is_user_data, lang_Count_locales, lang_free_collations(), lang_get_generic_unicode_norm(), lang_locale_data::lang_id, lang_load_library(), lang_locale_data_load_from_lib(), LANG_MAX_LOADED_LOCALES, lang_locale_data::lang_name, lang_set_generic_unicode_norm(), lang_unload_libraries(), locale_check_and_set_default_files(), locale_get_cfg_locales(), locale_file::locale_name, loclib_Handle, loclib_Handle_count, loclib_Handle_size, LOG_LOCALE_ERROR, NO_ERROR, NULL, register_lang_locale_data(), TEXT_CONV_GENERIC_1BYTE, TEXT_CONV_GENERIC_2BYTE, TEXT_CONV_ISO_88591_BUILTIN, TEXT_CONV_ISO_88599_BUILTIN, text_conversion::text_to_utf8_func, lang_locale_data::txt_conv, lang_locale_data::unicode_norm, and text_conversion::utf8_to_text_func.
Referenced by lang_init().
static int lang_back_strmatch_utf8_uca_w_level (const COLL_DATA * coll_data, bool is_match, const unsigned char * str1, const int size1, const unsigned char * str2, const int size2, const unsigned char * escape, const bool has_last_escape, int * offset_next_level, int * str1_match_size, bool ignore_trailing_space) static
Definition at line 4082 of file language_support.c.
References ASCII_SPACE, assert, CAST_BUFLEN, intl_back_utf8_to_cp(), intl_cmp_char(), INTL_CODESET_UTF8, INTL_CONTR_FOUND, INTL_MASK_CONTR, lang_get_uca_back_weight_l13(), MATCH_CONTR_BOUND_ALLOW, NULL, uca_options::sett_match_contr, UCA_GET_L2_W, and coll_data::uca_opt.
Referenced by lang_strmatch_utf8_uca_w_coll_data().
INTL_CODESET lang_charset (void)
Definition at line 1976 of file language_support.c.
References assert, INTL_CODESET_NONE, lang_Charset_initialized, and lang_Loc_charset.
Referenced by disk_format(), get_set_domain(), get_string(), intl_identifier_casecmp_w_size(), intl_identifier_fix(), intl_identifier_lower(), intl_identifier_lower_string_size(), intl_identifier_mht_1strlowerhash(), intl_identifier_ncasecmp(), intl_identifier_upper(), intl_identifier_upper_string_size(), intl_mbs_ncpy(), la_find_log_pagesize(), lang_currency_symbol(), lang_db_put_charset(), lang_set_language(), logpb_initialize_header(), mr_data_lengthval_nchar(), mr_lengthval_varnchar_internal(), mr_writeval_nchar_internal(), mr_writeval_varnchar_internal(), parser_parse_file(), parser_parse_string_with_escapes(), pt_assignment_compatible(), pt_init_one_statement_parser(), start_csql(), xboot_emergency_patch(), and xboot_register_client().
const char* lang_charset_cubrid_name (const INTL_CODESET codeset)
Definition at line 2585 of file language_support.c.
References assert, db_charset::charset_cubrid_name, db_charset::charset_id, i, INTL_CODESET_BINARY, INTL_CODESET_NONE, INTL_CODESET_UTF8, and NULL.
Referenced by boot_add_charsets(), boot_restart_server(), db_get_cs_coll_info(), la_find_log_pagesize(), la_print_log_header(), lang_get_charset_env_string(), and xboot_emergency_patch().
INTL_CODESET lang_charset_cubrid_name_to_id (const char * name)
Definition at line 2775 of file language_support.c.
References INTL_CODESET_BINARY, INTL_CODESET_LAST, and INTL_CODESET_NONE.
Referenced by pt_check_grammar_charset_collation().
const char* lang_charset_introducer (const INTL_CODESET codeset)
Definition at line 2798 of file language_support.c.
References assert, db_charset::charset_id, i, INTL_CODESET_BINARY, INTL_CODESET_NONE, INTL_CODESET_UTF8, db_charset::introducer, and NULL.
Referenced by db_value_printer::describe_value(), pt_check_partition_values(), and pt_print_value().
const char* lang_charset_name (const INTL_CODESET codeset)
Definition at line 2561 of file language_support.c.
References assert, db_charset::charset_id, db_charset::charset_name, i, INTL_CODESET_BINARY, INTL_CODESET_NONE, INTL_CODESET_UTF8, and NULL.
Referenced by db_date_format(), db_str_to_date(), db_time_format(), db_to_date(), db_to_datetime(), db_to_time(), db_to_timestamp(), get_string_date_token_id(), and print_string_date_token().
int lang_charset_name_to_id (const char * name, INTL_CODESET * codeset)
Definition at line 2683 of file language_support.c.
References db_charset::charset_id, ER_FAILED, i, INTL_CODESET_NONE, and NO_ERROR.
int lang_check_coll_compat (const LANG_COLL_COMPAT * coll_array, const int coll_cnt, const char * client_text, const char * server_text)
Definition at line 7495 of file language_support.c.
References assert, lang_coll_compat::checksum, coll_data::checksum, lang_collation::codeset, lang_coll_compat::codeset, lang_collation::coll, lang_coll_compat::coll_id, coll_data::coll_id, lang_coll_compat::coll_name, coll_data::coll_name, ER_LOC_INIT, ERR_MSG_SIZE, i, lang_Count_collations, lang_get_collation(), LANG_MAX_COLLATIONS, LOG_LOCALE_ERROR, NO_ERROR, and NULL.
Referenced by boot_get_host_name(), and boot_restart_server().
bool lang_check_identifier (const char * name, int length)
Definition at line 2101 of file language_support.c.
References char_isalnum(), char_isalpha(), i, and NULL.
Referenced by pt_append_name().
int lang_check_locale_compat (const LANG_LOCALE_COMPAT * loc_array, const int loc_cnt, const char * client_text, const char * server_text)
Definition at line 7584 of file language_support.c.
References assert, lang_locale_data::checksum, lang_locale_compat::checksum, lang_locale_data::codeset, lang_locale_compat::codeset, ER_LOC_INIT, ERR_MSG_SIZE, i, lang_Count_locales, lang_locale_data::lang_name, lang_locale_compat::lang_name, LOG_LOCALE_ERROR, lang_locale_data::next_lld, NO_ERROR, and NULL.
Referenced by boot_get_host_name().
int lang_collation_count (void)
Definition at line 1704 of file language_support.c.
References lang_Count_collations.
Referenced by boot_add_charsets(), boot_add_collations(), sboot_get_locales_info(), and synccoll_check().
DB_CURRENCY lang_currency (void)
Definition at line 1935 of file language_support.c.
References assert, DB_CURRENCY_NULL, lang_Language_initialized, and lang_Loc_currency.
Referenced by db_get_currency_default(), and lang_locale_currency().
const char* lang_currency_symbol (DB_CURRENCY curr)
Definition at line 2016 of file language_support.c.
References intl_get_money_symbol_console(), lang_charset(), LANG_VARIABLE_CHARSET, and p.
Referenced by tp_value_cast_internal(), and valcnv_convert_data_to_string().
const char* lang_date_format_parse (const INTL_LANG lang_id, const INTL_CODESET codeset, const DB_TYPE type, INTL_CODESET * format_codeset)
Definition at line 2405 of file language_support.c.
References assert, lang_defaults::codeset, lang_locale_data::codeset, lang_locale_data::date_format, lang_locale_data::datetime_format, lang_locale_data::datetimetz_format, DB_TYPE_DATE, DB_TYPE_DATETIME, DB_TYPE_DATETIMETZ, DB_TYPE_TIME, DB_TYPE_TIMESTAMP, DB_TYPE_TIMESTAMPTZ, lang_Charset_initialized, lang_get_first_locale_for_lang(), lang_Language_initialized, lang_locale_data::next_lld, NULL, lang_locale_data::time_format, lang_locale_data::timestamp_format, and lang_locale_data::timestamptz_format.
Referenced by db_to_date(), db_to_datetime(), db_to_time(), and db_to_timestamp().
int lang_db_put_charset (void)
Definition at line 2643 of file language_support.c.
References assert, AU_DISABLE, AU_ENABLE, Au_root, db_make_int(), db_make_string(), db_put_internal(), lang_charset(), lang_get_lang_name_from_id(), lang_id(), NO_ERROR, and pr_clear_value().
Referenced by createdb().
char lang_digit_fractional_symbol (const INTL_LANG lang_id)
Definition at line 2535 of file language_support.c.
References assert, INTL_CODESET_NONE, lang_get_specific_locale(), NULL, and lang_locale_data::number_decimal_sym.
Referenced by convert_locale_number(), db_format(), db_to_number(), get_number_token(), make_number(), make_number_to_char(), number_to_char(), roundoff(), scientific_to_decimal_string(), and to_number_next_state().
char lang_digit_grouping_symbol (const INTL_LANG lang_id)
Definition at line 2520 of file language_support.c.
References assert, INTL_CODESET_NONE, lang_get_specific_locale(), NULL, and lang_locale_data::number_group_sym.
Referenced by convert_locale_number(), db_format(), db_to_number(), get_number_token(), make_number(), make_number_to_char(), number_to_char(), roundoff(), and to_number_next_state().
static int lang_fastcmp_binary (const LANG_COLLATION * lang_coll, const unsigned char * string1, const int size1, const unsigned char * string2, const int size2, bool ignore_trailing_space) static
Definition at line 6458 of file language_support.c.
References i.
static int lang_fastcmp_byte (const LANG_COLLATION * lang_coll, const unsigned char * string1, const int size1, const unsigned char * string2, const int size2, bool ignore_trailing_space) static
Definition at line 5496 of file language_support.c.
References cmp, lang_collation::coll, for(), i, SPACE, coll_data::weights, coll_data::weights_ti, and ZERO.
static int lang_fastcmp_ko (const LANG_COLLATION * lang_coll, const unsigned char * string1, int size1, const unsigned char * string2, int size2, bool ignore_trailing_space) static
Definition at line 6099 of file language_support.c.
References ASCII_SPACE, assert, CAST_BUFLEN, cmp, lang_collation::coll, EUC_SPACE, SPACE, coll_data::weights, coll_data::weights_ti, and ZERO.
void lang_final (void)
Definition at line 1991 of file language_support.c.
References destroy_user_locales(), lang_Builtin_initialized, lang_Charset_initialized, lang_free_collations(), lang_Init_w_error, lang_Initialized, lang_Language_initialized, lang_Msg_env_initialized, lang_set_generic_unicode_norm(), lang_unload_libraries(), and NULL.
Referenced by boot_client_all_finalize(), boot_initialize_client(), boot_restart_client(), boot_server_all_finalize(), and csql_exit_cleanup().
static void lang_free_collations (void) static
Definition at line 7461 of file language_support.c.
References assert, i, lang_Count_collations, LANG_MAX_COLLATIONS, and NULL.
Referenced by init_user_locales(), and lang_final().
static int lang_get_builtin_lang_id_from_name (const char * lang_name, INTL_LANG * lang_id) static
Definition at line 2213 of file language_support.c.
References assert, i, INTL_LANG_ENGLISH, INTL_LANG_USER_DEF_START, lang_defaults::lang, NULL, and strlen.
Referenced by lang_set_charset_lang().
int lang_get_charset_env_string (char * buf, int buf_size, const char * lang_name, const INTL_CODESET codeset)
Definition at line 2611 of file language_support.c.
References assert_release, ER_FAILED, INTL_CODESET_ISO88591, lang_charset_cubrid_name(), NO_ERROR, and NULL.
Referenced by lang_set_language().
INTL_CODESET lang_get_client_charset (void)
Definition at line 2705 of file language_support.c.
References lang_collation::codeset, lang_get_collation_by_name(), LANG_SYS_CODESET, NULL, prm_get_string_value(), and PRM_ID_INTL_COLLATION.
Referenced by jsp_unpack_numeric_value(), jsp_unpack_string_value(), and netval_to_dbval().
int lang_get_client_collation (void)
Definition at line 2727 of file language_support.c.
References lang_collation::coll, coll_data::coll_id, lang_get_collation_by_name(), LANG_SYS_COLLATION, NULL, prm_get_string_value(), and PRM_ID_INTL_COLLATION.
Referenced by jsp_unpack_string_value(), and netval_to_dbval().
const char* lang_get_codeset_name (int codeset_id)
Definition at line 1715 of file language_support.c.
References assert, INTL_CODESET_BINARY, INTL_CODESET_ISO88591, INTL_CODESET_KSC5601_EUC, and INTL_CODESET_UTF8.
Referenced by cublocale::get_codeset_name(), pt_check_cast_op(), pt_check_expr_collation(), pt_print_alter_one_clause(), pt_print_expr(), and set_current_locale().
LANG_COLLATION* lang_get_collation (const int coll_id)
Definition at line 1653 of file language_support.c.
References assert, and LANG_MAX_COLLATIONS.
Referenced by boot_add_collations(), build_att_coll_change_map(), check_change_class_collation(), db_string_concatenate(), db_string_regexp_count(), db_string_regexp_instr(), db_string_regexp_like(), db_string_regexp_replace(), db_string_regexp_substr(), db_string_rlike(), lang_check_coll_compat(), lang_user_alphabet_w_coll(), main(), or_get_enumeration(), pt_attr_check_default_cs_coll(), pt_check_cast_op(), pt_check_create_index(), pt_check_expr_collation(), pt_eval_expr_type(), pt_get_collation_info(), pt_get_collation_info_for_collection_type(), pt_has_non_idx_sarg_coll_pre(), qo_check_coll_optimization(), qo_rewrite_one_like_term(), qstr_eval_like(), qstr_position(), sboot_get_locales_info(), synccoll_check(), tp_domain_resolve(), tp_domain_resolve_default_w_coll(), tp_value_compare_with_error(), unpack_domain(), and unpack_domain_2().
LANG_COLLATION* lang_get_collation_by_name (const char * coll_name)
Definition at line 1683 of file language_support.c.
References assert, i, LANG_MAX_COLLATIONS, and NULL.
Referenced by lang_get_client_charset(), lang_get_client_collation(), lang_locale_data_load_from_lib(), pt_check_grammar_charset_collation(), and sysprm_generate_new_value().
const char* lang_get_collation_name (const int coll_id)
Definition at line 1667 of file language_support.c.
References lang_collation::coll, coll_data::coll_name, LANG_MAX_COLLATIONS, and NULL.
Referenced by db_get_cs_coll_info(), object_printer::describe_domain(), do_set_names(), emit_domain_def(), emit_schema(), class_description::init(), pt_print_alter_one_clause(), pt_print_attr_def(), pt_print_datatype(), pt_print_expr(), pt_print_value(), qexec_execute_build_columns(), qo_plan_print_sort_spec_helper(), sysprm_generate_new_value(), sysprm_init_intl_param(), sysprm_make_default_values(), sysprm_print_parameters_for_ha_repl(), and tp_check_value_size().
static COLL_CONTRACTION * lang_get_contr_for_string (const COLL_DATA * coll_data, const unsigned char * str, const int str_size, unsigned int cp) static
Definition at line 3317 of file language_support.c.
References assert, coll_contraction::c_buf, cmp, coll_data::contr_list, coll_data::contr_min_size, coll_data::count_contr, coll_data::cp_first_contr_array, coll_data::cp_first_contr_offset, NULL, and coll_contraction::size.
Referenced by lang_get_uca_back_weight_l13(), lang_get_uca_w_l13(), lang_get_uca_w_l4(), lang_get_w_first_el(), lang_mht2str_utf8(), lang_mht2str_utf8_exp(), lang_next_coll_seq_utf8_w_contr(), and lang_strmatch_utf8_w_contr().
static INTL_CODESET lang_get_default_codeset (const INTL_LANG intl_id) static
Definition at line 2476 of file language_support.c.
References builtin_Langs, lang_defaults::codeset, i, INTL_CODESET_NONE, and lang_defaults::lang.
Referenced by lang_set_charset_lang().
const LANG_LOCALE_DATA* lang_get_first_locale_for_lang (const INTL_LANG lang)
Definition at line 2186 of file language_support.c.
References assert, lang_defaults::lang, lang_Charset_initialized, lang_Count_locales, lang_Language_initialized, and NULL.
Referenced by lang_date_format_parse(), and sboot_get_locales_info().
UNICODE_NORMALIZATION* lang_get_generic_unicode_norm (void)
Definition at line 7442 of file language_support.c.
References generic_Unicode_norm.
Referenced by csql_db_value_as_string(), csql_help_schema(), csql_help_trigger(), dbval_to_net_buf(), init_user_locales(), jsp_pack_string_argument(), jsp_unpack_string_value(), and netval_to_dbval().
INTL_LANG lang_get_lang_id_from_flag (const int flag, bool * has_user_format, bool * has_user_lang)
Definition at line 2373 of file language_support.c.
References lang_Count_locales, and lang_id().
Referenced by date_to_char(), db_date_format(), db_format(), db_str_to_date(), db_time_format(), db_to_date(), db_to_datetime(), db_to_number(), db_to_time(), db_to_timestamp(), number_to_char(), pt_eval_expr_type(), and pt_print_expr().
int lang_get_lang_id_from_name (const char * lang_name, INTL_LANG * lang_id)
Definition at line 2245 of file language_support.c.
References assert, i, INTL_LANG_ENGLISH, lang_Count_locales, lang_locale_data::lang_id, and NULL.
Referenced by lang_set_flag_from_lang(), set_current_locale(), and sysprm_generate_new_value().
const char* lang_get_Lang_name (void)
Definition at line 1905 of file language_support.c.
References assert, lang_Lang_name, lang_Language_initialized, and NULL.
Referenced by sysprm_generate_new_value(), sysprm_init_intl_param(), sysprm_make_default_values(), sysprm_print_parameters_for_ha_repl(), and xboot_register_client().
const char* lang_get_lang_name_from_id (const INTL_LANG lang_id)
Definition at line 2276 of file language_support.c.
References assert, lang_Count_locales, lang_id(), lang_locale_data::lang_name, and NULL.
Referenced by db_date_format(), db_str_to_date(), db_time_format(), db_to_date(), db_to_datetime(), db_to_time(), db_to_timestamp(), get_string_date_token_id(), lang_db_put_charset(), number_to_char(), print_string_date_token(), and pt_print_expr().
const char* lang_get_msg_Loc_name (void)
Definition at line 1889 of file language_support.c.
References lang_Msg_env_initialized, lang_Msg_loc_name, and set_msg_lang_from_env().
Referenced by msgcat_open(), and msgcat_open_file().
bool lang_get_parser_use_client_charset (void)
Definition at line 2761 of file language_support.c.
References lang_Parser_use_client_charset.
const LANG_LOCALE_DATA* lang_get_specific_locale (const INTL_LANG lang, const INTL_CODESET codeset)
Definition at line 2153 of file language_support.c.
References assert, lang_locale_data::codeset, INTL_CODESET_NONE, lang_defaults::lang, lang_Charset_initialized, lang_Count_locales, lang_Language_initialized, lang_locale_data::next_lld, and NULL.
Referenced by db_date_format(), db_str_to_date(), db_time_format(), db_to_date(), db_to_datetime(), db_to_time(), db_to_timestamp(), get_string_date_token_id(), intl_case_match_tok(), intl_identifier_casecmp_w_size(), lang_digit_fractional_symbol(), lang_digit_grouping_symbol(), and print_string_date_token().
TEXT_CONVERSION* lang_get_txt_conv (void)
Definition at line 2549 of file language_support.c.
References console_Conv.
Referenced by intl_text_dbcs_to_utf8(), intl_text_single_byte_to_utf8(), intl_text_utf8_to_dbcs(), intl_text_utf8_to_single_byte(), and start_csql().
static void lang_get_uca_back_weight_l13 (const COLL_DATA * coll_data, const bool use_contractions, const unsigned char * str_start, const unsigned char * str_last, UCA_L13_W ** uca_w_l13, int * num_ce, unsigned char ** str_prev, unsigned int * cp_out) static
Definition at line 3458 of file language_support.c.
References assert, CAST_BUFLEN, coll_data::contr_min_size, coll_data::count_contr, coll_data::cp_first_contr_count, coll_data::cp_first_contr_offset, intl_back_utf8_to_cp(), INTL_MASK_CONTR, lang_get_contr_for_string(), NULL, coll_data::uca_exp_num, uca_l13_max_weight, coll_contraction::uca_num, coll_data::uca_num, coll_contraction::uca_w_l13, coll_data::uca_w_l13, and coll_data::w_count.
Referenced by lang_back_strmatch_utf8_uca_w_level().
static void lang_get_uca_w_l13 (const COLL_DATA * coll_data, const bool use_contractions, const unsigned char * str, const int size, UCA_L13_W ** uca_w_l13, int * num_ce, unsigned char ** str_next, unsigned int * cp_out) static
Definition at line 3397 of file language_support.c.
References assert, coll_data::contr_min_size, coll_data::count_contr, coll_data::cp_first_contr_count, coll_data::cp_first_contr_offset, INTL_MASK_CONTR, intl_utf8_to_cp(), lang_get_contr_for_string(), NULL, coll_contraction::size, coll_data::uca_exp_num, uca_l13_max_weight, coll_contraction::uca_num, coll_data::uca_num, coll_contraction::uca_w_l13, coll_data::uca_w_l13, and coll_data::w_count.
Referenced by lang_split_key_w_exp(), lang_str_utf8_trail_zero_weights_w_exp(), and lang_strmatch_utf8_uca_w_level().
static void lang_get_uca_w_l4 (const COLL_DATA * coll_data, const bool use_contractions, const unsigned char * str, const int size, UCA_L4_W ** uca_w_l4, int * num_ce, unsigned char ** str_next, unsigned int * cp_out) static
Definition at line 3527 of file language_support.c.
References assert, coll_data::contr_min_size, coll_data::count_contr, coll_data::cp_first_contr_count, coll_data::cp_first_contr_offset, INTL_MASK_CONTR, intl_utf8_to_cp(), lang_get_contr_for_string(), NULL, coll_contraction::size, coll_data::uca_exp_num, uca_l4_max_weight, coll_contraction::uca_num, coll_data::uca_num, coll_contraction::uca_w_l4, coll_data::uca_w_l4, and coll_data::w_count.
Referenced by lang_str_utf8_trail_zero_weights_w_exp(), and lang_strmatch_utf8_uca_w_level().
static unsigned int lang_get_w_first_el (const COLL_DATA * coll, const unsigned char * str, const int str_size, unsigned char ** next_char, bool ignore_trailing_space) static
Definition at line 3263 of file language_support.c.
References ASCII_SPACE, assert, coll_data::contr_min_size, coll_data::count_contr, coll_data::cp_first_contr_count, coll_data::cp_first_contr_offset, intl_utf8_to_cp(), lang_get_contr_for_string(), NULL, coll_contraction::size, coll_data::uca_exp_num, coll_data::w_count, coll_data::weights, and coll_contraction::wv.
Referenced by lang_split_key_utf8().
INTL_LANG lang_id (void)
Definition at line 1920 of file language_support.c.
References assert, lang_Lang_id, and lang_Language_initialized.
Referenced by intl_identifier_casecmp(), intl_identifier_namecmp(), intl_identifier_ncasecmp(), intl_zone(), lang_db_put_charset(), lang_get_lang_id_from_flag(), lang_get_lang_name_from_id(), and pt_print_expr().
int lang_init (void)
Definition at line 906 of file language_support.c.
References assert, ER_LOC_INIT, error(), init_user_locales(), lang_Charset_initialized, lang_init_builtin(), lang_Init_w_error, lang_Initialized, lang_Language_initialized, and NO_ERROR.
Referenced by boot_initialize_client(), boot_restart_client(), boot_restart_server(), rel_build_type(), xboot_emergency_patch(), xboot_initialize_server(), and xboot_restart_from_backup().
void lang_init_builtin (void)
Definition at line 854 of file language_support.c.
References coll_Iso_binary, i, lang_Builtin_initialized, LANG_MAX_COLLATIONS, register_collation(), register_lang_locale_data(), and set_msg_lang_from_env().
Referenced by genlocale(), and lang_init().
static void lang_init_coll_en_ci (LANG_COLLATION * lang_coll) static
Definition at line 5421 of file language_support.c.
References assert, lang_collation::coll, lang_init_common_en_ci(), lang_collation::need_init, and NULL.
static void lang_init_coll_en_cs (LANG_COLLATION * lang_coll) static
Definition at line 5399 of file language_support.c.
References assert, lang_collation::coll, lang_init_common_en_cs(), lang_collation::need_init, and NULL.
static void lang_init_coll_Utf8_tr_cs (LANG_COLLATION * lang_coll) static
Definition at line 5807 of file language_support.c.
References assert, lang_collation::coll, i, LANG_CHAR_COUNT_TR, lang_Next_alpha_char_TR, lang_Next_alpha_char_TR_ti, lang_Weight_TR, lang_Weight_TR_ti, lang_collation::need_init, coll_data::next_cp, coll_data::next_cp_ti, NULL, coll_data::weights, and coll_data::weights_ti.
static void lang_init_common_en_ci (COLL_DATA * coll_data) static
Definition at line 5356 of file language_support.c.
References i, coll_data::next_cp, coll_data::next_cp_ti, coll_data::w_count, coll_data::weights, and coll_data::weights_ti.
Referenced by lang_init_coll_en_ci().
static void lang_init_common_en_cs (COLL_DATA * coll_data) static
Definition at line 5326 of file language_support.c.
References i, coll_data::next_cp, coll_data::next_cp_ti, coll_data::w_count, coll_data::weights, and coll_data::weights_ti.
Referenced by lang_init_coll_en_cs().
void lang_init_console_txt_conv (void)
Definition at line 936 of file language_support.c.
References assert, text_conversion::init_conv_func, lang_Initialized, text_conversion::nl_lang_str, NULL, strlen, lang_locale_data::txt_conv, and text_conversion::win_codepages.
Referenced by csql().
static void lang_initloc_en_binary (LANG_LOCALE_DATA * ld) static
Definition at line 5309 of file language_support.c.
References assert, lang_collation::default_lang, lang_locale_data::is_initialized, and NULL.
static void lang_initloc_en_iso88591 (LANG_LOCALE_DATA * ld) static
Definition at line 5293 of file language_support.c.
References assert, lang_collation::default_lang, lang_locale_data::is_initialized, and NULL.
static void lang_initloc_en_utf8 (LANG_LOCALE_DATA * ld) static
Definition at line 5441 of file language_support.c.
References assert, lang_collation::default_lang, lang_locale_data::default_lang_coll, i, lang_locale_data::is_initialized, LANG_CHAR_COUNT_EN, lang_lower_EN, lang_upper_EN, and NULL.
static void lang_initloc_ko_euc (LANG_LOCALE_DATA * ld) static
Definition at line 6073 of file language_support.c.
References assert, lang_collation::default_lang, lang_locale_data::is_initialized, and NULL.
static void lang_initloc_ko_iso (LANG_LOCALE_DATA * ld) static
Definition at line 6044 of file language_support.c.
References assert, lang_locale_data::is_initialized, and NULL.
static void lang_initloc_ko_utf8 (LANG_LOCALE_DATA * ld) static
Definition at line 6057 of file language_support.c.
References assert, lang_collation::default_lang, lang_locale_data::is_initialized, and NULL.
static void lang_initloc_tr_iso (LANG_LOCALE_DATA * ld) static
Definition at line 5943 of file language_support.c.
References assert, lang_locale_data::is_initialized, and NULL.
static void lang_initloc_tr_utf8 (LANG_LOCALE_DATA * ld) static
Definition at line 5956 of file language_support.c.
References assert, lang_collation::default_lang, lang_locale_data::default_lang_coll, i, lang_locale_data::is_initialized, LANG_CHAR_COUNT_TR, lang_lower_i_TR, lang_lower_TR, lang_upper_i_TR, lang_upper_TR, and NULL.
static bool lang_is_codeset_allowed (const INTL_LANG intl_id, const INTL_CODESET codeset) static
Definition at line 2500 of file language_support.c.
References builtin_Langs, i, and lang_defaults::lang.
Referenced by lang_set_charset_lang().
bool lang_is_coll_name_allowed (const char * name)
Definition at line 1622 of file language_support.c.
References i, and NULL.
Referenced by locale_compile_locale().
int lang_load_coll_from_lib (COLL_DATA * cd, void * lib_handle, const LOCALE_FILE * lf)
Definition at line 7148 of file language_support.c.
References assert, bool, coll_data::checksum, coll_data::coll_id, coll_data::coll_name, coll_data::contr_list, coll_data::contr_min_size, coll_data::count_contr, coll_data::cp_first_contr_array, coll_data::cp_first_contr_count, coll_data::cp_first_contr_offset, ER_LOC_INIT, ERR_MSG_SIZE, locale_file::lib_file, LOC_LIB_SYMBOL_NAME_SIZE, locale_file::locale_name, LOG_LOCALE_ERROR, coll_data::next_cp, NO_ERROR, NULL, uca_options::sett_backwards, uca_options::sett_caseFirst, uca_options::sett_caseLevel, uca_options::sett_contr_policy, uca_options::sett_expansions, uca_options::sett_match_contr, uca_options::sett_strength, SHLIB_GET_ADDR, SHLIB_GET_ADDR_W_REF, SHLIB_GET_VAL, TAILOR_IDENTITY, TAILOR_QUATERNARY, TAILOR_UNDEFINED, coll_data::uca_exp_num, coll_data::uca_num, coll_data::uca_opt, coll_data::uca_w_l13, coll_data::uca_w_l4, coll_data::w_count, and coll_data::weights.
Referenced by lang_locale_data_load_from_lib(), and locale_dump_lib_collations().
int lang_load_count_coll_from_lib (int * count_coll, void * lib_handle, const LOCALE_FILE * lf)
Definition at line 7081 of file language_support.c.
References assert, ER_LOC_INIT, ERR_MSG_SIZE, locale_file::lib_file, LOC_LIB_SYMBOL_NAME_SIZE, locale_file::locale_name, LOG_LOCALE_ERROR, NO_ERROR, NULL, and SHLIB_GET_VAL.
Referenced by lang_locale_data_load_from_lib(), and locale_dump_lib_collations().
int lang_load_get_coll_name_from_lib (const int coll_pos, char ** coll_name, void * lib_handle, const LOCALE_FILE * lf)
Definition at line 7114 of file language_support.c.
References assert, COLL_NAME_SIZE, ER_LOC_INIT, ERR_MSG_SIZE, LANG_MAX_LANGNAME, locale_file::lib_file, LOC_LIB_SYMBOL_NAME_SIZE, locale_file::locale_name, LOG_LOCALE_ERROR, NO_ERROR, NULL, and SHLIB_GET_ADDR.
Referenced by lang_locale_data_load_from_lib(), and locale_dump_lib_collations().
int lang_load_library (const char * lib_file, void ** handle)
Definition at line 7315 of file language_support.c.
References assert, ER_LOC_INIT, ERR_MSG_SIZE, error(), LOG_LOCALE_ERROR, NO_ERROR, and NULL.
Referenced by dumplocale(), and init_user_locales().
const LANG_LOCALE_DATA* lang_locale (void)
Definition at line 2131 of file language_support.c.
References assert, lang_Charset_initialized, lang_Language_initialized, lang_Loc_data, and NULL.
Referenced by intl_identifier_lower(), intl_identifier_lower_string_size(), intl_identifier_mht_1strlowerhash(), intl_identifier_upper(), and intl_identifier_upper_string_size().
DB_CURRENCY lang_locale_currency (const char * locale_str)
Definition at line 1950 of file language_support.c.
References assert, DB_CURRENCY_NULL, lang_locale_data::default_currency_code, i, lang_Count_locales, lang_currency(), lang_Language_initialized, and lang_defaults::lang_name.
Referenced by number_to_char().
int lang_locale_data_load_from_lib (LANG_LOCALE_DATA * lld, void * lib_handle, const LOCALE_FILE * lf, bool is_load_for_dump)
Definition at line 6750 of file language_support.c.
References alphabet_data::a_type, coll_opt::allow_index_opt, coll_opt::allow_like_rewrite, coll_opt::allow_prefix_index, lang_locale_data::alphabet, ALPHABET_ASCII, ALPHABET_TAILORED, ALPHABET_UNICODE, lang_locale_data::am_pm, lang_locale_data::am_pm_parse_order, ARG_FILE_LINE, assert, lang_collation::built_in, text_conversion::byte_flag, CAL_AM_PM_COUNT, CAL_DAY_COUNT, CAL_MONTH_COUNT, lang_locale_data::checksum, lang_collation::codeset, lang_collation::coll, coll_data::coll_name, con_Iso_8859_1_conv, con_Iso_8859_9_conv, text_conversion::conv_type, coll_data::count_contr, lang_locale_data::date_format, lang_locale_data::datetime_format, lang_locale_data::datetimetz_format, lang_locale_data::day_name, lang_locale_data::day_parse_order, lang_locale_data::day_short_name, lang_locale_data::day_short_parse_order, lang_locale_data::default_currency_code, lang_collation::default_lang, lang_locale_data::default_lang_coll, ER_ERROR_SEVERITY, ER_LOC_INIT, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), ERR_MSG_SIZE, lang_collation::fastcmp, i, lang_locale_data::ident_alphabet, INTL_CODESET_UTF8, lang_get_collation_by_name(), lang_load_coll_from_lib(), lang_load_count_coll_from_lib(), lang_load_get_coll_name_from_lib(), lang_locale_load_alpha_from_lib(), lang_locale_load_normalization_from_lib(), lang_mht2str_utf8(), lang_mht2str_utf8_exp(), lang_locale_data::lang_name, lang_next_coll_char_utf8(), lang_next_coll_seq_utf8_w_contr(), lang_split_key_utf8(), lang_split_key_w_exp(), lang_strcmp_utf8(), lang_strcmp_utf8_uca(), lang_strcmp_utf8_w_contr(), lang_strmatch_utf8(), lang_strmatch_utf8_uca(), lang_strmatch_utf8_w_contr(), locale_file::lib_file, LOC_LIB_SYMBOL_NAME_SIZE, locale_file::locale_name, LOG_LOCALE_ERROR, lang_collation::mht2str, lang_locale_data::month_name, lang_locale_data::month_parse_order, lang_locale_data::month_short_name, lang_locale_data::month_short_parse_order, lang_collation::next_coll_seq, text_conversion::nl_lang_str, NO_ERROR, NULL, lang_locale_data::number_decimal_sym, lang_locale_data::number_group_sym, lang_collation::options, register_collation(), uca_options::sett_strength, SHLIB_GET_ADDR, SHLIB_GET_VAL, lang_collation::split_key, strlen, lang_collation::strmatch, TAILOR_QUATERNARY, TEXT_CONV_GENERIC_1BYTE, TEXT_CONV_GENERIC_2BYTE, TEXT_CONV_ISO_88591_BUILTIN, TEXT_CONV_ISO_88599_BUILTIN, TEXT_CONV_NO_CONVERSION, text_conversion::text_first_cp, text_conversion::text_last_cp, text_conversion::text_to_utf8, lang_locale_data::time_format, lang_locale_data::timestamp_format, lang_locale_data::timestamptz_format, lang_locale_data::txt_conv, coll_data::uca_exp_num, coll_data::uca_opt, lang_locale_data::unicode_norm, text_conversion::utf8_first_cp, text_conversion::utf8_last_cp, text_conversion::utf8_to_text, and text_conversion::win_codepages.
Referenced by dumplocale(), and init_user_locales().
static int lang_locale_load_alpha_from_lib (ALPHABET_DATA * a, bool load_w_identifier_name, const char * alpha_suffix, void * lib_handle, const LOCALE_FILE * lf) static
Definition at line 7260 of file language_support.c.
References assert, ER_LOC_INIT, ERR_MSG_SIZE, alphabet_data::l_count, locale_file::lib_file, LOC_LIB_SYMBOL_NAME_SIZE, locale_file::locale_name, LOG_LOCALE_ERROR, alphabet_data::lower_cp, alphabet_data::lower_multiplier, NO_ERROR, NULL, SHLIB_GET_ADDR, SHLIB_GET_VAL, alphabet_data::upper_cp, and alphabet_data::upper_multiplier.
Referenced by lang_locale_data_load_from_lib().
static int lang_locale_load_normalization_from_lib (UNICODE_NORMALIZATION * norm, void * lib_handle, const LOCALE_FILE * lf) static
Definition at line 7409 of file language_support.c.
References assert, ER_LOC_INIT, ERR_MSG_SIZE, locale_file::lib_file, unicode_normalization::list_full_decomp, LOC_LIB_SYMBOL_NAME_SIZE, locale_file::locale_name, LOG_LOCALE_ERROR, NO_ERROR, NULL, SHLIB_GET_ADDR, SHLIB_GET_VAL, unicode_normalization::unicode_mapping_index, unicode_normalization::unicode_mappings, unicode_normalization::unicode_mappings_count, and UNICODE_NORMALIZATION_DECORATOR.
Referenced by lang_locale_data_load_from_lib().
int lang_locales_count (bool check_codeset)
Definition at line 1347 of file language_support.c.
References cubregex::count(), i, lang_Count_locales, lang_locale_data::next_lld, and NULL.
Referenced by sboot_get_locales_info().
static unsigned int lang_mht2str_byte (const LANG_COLLATION * lang_coll, const unsigned char * str, const int size) static
Definition at line 5714 of file language_support.c.
References ADD_TO_HASH, lang_collation::coll, and coll_data::weights.
static unsigned int lang_mht2str_default (const LANG_COLLATION * lang_coll, const unsigned char * str, const int size) static
Definition at line 5700 of file language_support.c.
References mht_2str_pseudo_key().
static unsigned int lang_mht2str_ko (const LANG_COLLATION * lang_coll, const unsigned char * str, const int size) static
Definition at line 6205 of file language_support.c.
References ADD_TO_HASH, ASCII_SPACE, assert, EUC_SPACE, and ZERO.
static unsigned int lang_mht2str_utf8 (const LANG_COLLATION * lang_coll, const unsigned char * str, const int size) static
Definition at line 3200 of file language_support.c.
References ADD_TO_HASH, assert, CAST_BUFLEN, lang_collation::coll, coll_data::contr_min_size, coll_data::count_contr, coll_data::cp_first_contr_count, coll_data::cp_first_contr_offset, intl_utf8_to_cp(), lang_get_contr_for_string(), NULL, coll_contraction::size, coll_data::w_count, coll_data::weights, and coll_contraction::wv.
Referenced by lang_locale_data_load_from_lib().
static unsigned int lang_mht2str_utf8_exp (const LANG_COLLATION * lang_coll, const unsigned char * str, const int size) static
Definition at line 3962 of file language_support.c.
References ADD_TO_HASH, assert, CAST_BUFLEN, lang_collation::coll, coll_data::contr_min_size, coll_data::count_contr, coll_data::cp_first_contr_count, coll_data::cp_first_contr_offset, GET_UCA_WEIGHT, intl_utf8_to_cp(), lang_get_contr_for_string(), NULL, uca_options::sett_strength, coll_contraction::size, TAILOR_QUATERNARY, coll_data::uca_exp_num, uca_l13_max_weight, uca_l4_max_weight, coll_contraction::uca_num, coll_data::uca_num, coll_data::uca_opt, coll_contraction::uca_w_l13, coll_data::uca_w_l13, coll_contraction::uca_w_l4, coll_data::uca_w_l4, and coll_data::w_count.
Referenced by lang_locale_data_load_from_lib().
static int lang_next_alpha_char_iso88591 (const LANG_COLLATION * lang_coll, const unsigned char * seq, const int size, unsigned char * next_seq, int * len_next, bool ignore_trailing_space) static
Definition at line 5740 of file language_support.c.
References assert, and NULL.
static int lang_next_alpha_char_ko (const LANG_COLLATION * lang_coll, const unsigned char * seq, const int size, unsigned char * next_seq, int * len_next, bool ignore_trailing_space) static
Definition at line 6422 of file language_support.c.
References assert, intl_char_size(), INTL_CODESET_KSC5601_EUC, and NULL.
static int lang_next_coll_byte (const LANG_COLLATION * lang_coll, const unsigned char * seq, const int size, unsigned char * next_seq, int * len_next, bool ignore_trailing_space) static
Definition at line 5765 of file language_support.c.
References assert, lang_collation::coll, coll_data::next_cp, coll_data::next_cp_ti, NULL, and coll_data::w_count.
static int lang_next_coll_char_utf8 (const LANG_COLLATION * lang_coll, const unsigned char * seq, const int size, unsigned char * next_seq, int * len_next, bool ignore_trailing_space) static
Definition at line 4596 of file language_support.c.
References assert, lang_collation::coll, intl_cp_to_utf8(), intl_utf8_to_cp(), coll_data::next_cp, coll_data::next_cp_ti, NULL, and coll_data::w_count.
Referenced by lang_locale_data_load_from_lib().
static int lang_next_coll_seq_utf8_w_contr (const LANG_COLLATION * lang_coll, const unsigned char * seq, const int size, unsigned char * next_seq, int * len_next, bool ignore_trailing_space) static
Definition at line 4640 of file language_support.c.
References assert, lang_collation::coll, coll_data::contr_list, coll_data::contr_min_size, coll_data::cp_first_contr_count, coll_data::cp_first_contr_offset, intl_cp_to_utf8(), INTL_GET_NEXT_CONTR_ID, INTL_IS_NEXT_CONTR, intl_utf8_to_cp(), lang_get_contr_for_string(), coll_data::next_cp, coll_data::next_cp_ti, NULL, and coll_data::w_count.
Referenced by lang_locale_data_load_from_lib().
int lang_set_charset (const INTL_CODESET codeset)
Definition at line 1208 of file language_support.c.
References ARG_FILE_LINE, lang_defaults::codeset, ER_ERROR_SEVERITY, ER_LOC_INIT, er_set(), INTL_CODESET_LAST, lang_Charset_initialized, lang_Loc_charset, NO_ERROR, and tp_apply_sys_charset().
Referenced by boot_restart_client(), boot_restart_server(), and xboot_emergency_patch().
int lang_set_charset_lang (const char * lang_charset)
Definition at line 1137 of file language_support.c.
References ARG_FILE_LINE, assert, check_env_lang_val(), ER_ERROR_SEVERITY, ER_LOC_INIT, er_set(), ERR_MSG_SIZE, INTL_CODESET_NONE, INTL_CODESET_UTF8, lang_Charset_initialized, lang_get_builtin_lang_id_from_name(), lang_get_default_codeset(), lang_Init_w_error, lang_Initialized, lang_is_codeset_allowed(), lang_Lang_id, lang_Lang_name, lang_Language_initialized, lang_Loc_charset, lang_Loc_name, NO_ERROR, NULL, set_current_locale(), set_default_lang(), strncpy_bufsize, and tp_apply_sys_charset().
Referenced by boot_initialize_client(), lang_set_language(), and xboot_emergency_patch().
int lang_set_flag_from_lang (const char * lang_str, bool has_user_format, bool has_user_lang, int * flag)
Definition at line 2303 of file language_support.c.
References assert, INTL_LANG_ENGLISH, lang_defaults::lang, lang_get_lang_id_from_name(), lang_set_flag_from_lang_id(), and NULL.
Referenced by do_evaluate_default_expr(), pt_check_default_vclass_query_spec(), pt_eval_expr_type(), pt_find_attr_in_class_list(), pt_resolve_default_value(), and qexec_execute_insert().
int lang_set_flag_from_lang_id (const INTL_LANG lang, bool has_user_format, bool has_user_lang, int * flag)
Definition at line 2341 of file language_support.c.
References INTL_LANG_ENGLISH, and lang_Count_locales.
Referenced by lang_set_flag_from_lang().
void lang_set_generic_unicode_norm (UNICODE_NORMALIZATION * norm)
Definition at line 7452 of file language_support.c.
Referenced by init_user_locales(), and lang_final().
int lang_set_language (const char * lang_str)
Definition at line 1231 of file language_support.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_LOC_INIT, er_set(), lang_charset(), lang_Charset_initialized, lang_get_charset_env_string(), LANG_MAX_LANGNAME, lang_set_charset_lang(), and NULL.
Referenced by boot_restart_client(), and boot_restart_server().
void lang_set_parser_use_client_charset (bool use)
Definition at line 2750 of file language_support.c.
References lang_Parser_use_client_charset.
Referenced by au_find_user(), do_run_update_query_for_class(), parser_parse_string_use_sys_charset(), and sch_query_execute().
static int lang_split_key_binary (const LANG_COLLATION * lang_coll, const bool is_desc, const unsigned char * str1, const int size1, const unsigned char * str2, const int size2, const unsigned char ** key, int * byte_size, bool ignore_trailing_space) static
Definition at line 6625 of file language_support.c.
References assert, CAST_BUFLEN, NO_ERROR, and NULL.
static int lang_split_key_byte (const LANG_COLLATION * lang_coll, const bool is_desc, const unsigned char * str1, const int size1, const unsigned char * str2, const int size2, const unsigned char ** key, int * byte_size, bool ignore_trailing_space) static
Definition at line 4806 of file language_support.c.
References assert, CAST_BUFLEN, lang_collation::coll, NO_ERROR, NULL, coll_data::weights, and coll_data::weights_ti.
static int lang_split_key_euckr (const LANG_COLLATION * lang_coll, const bool is_desc, const unsigned char * str1, const int size1, const unsigned char * str2, const int size2, const unsigned char ** key, int * byte_size, bool ignore_trailing_space) static
Definition at line 5189 of file language_support.c.
References ASCII_SPACE, assert, CAST_BUFLEN, lang_collation::coll, EUC_SPACE, intl_nextchar_euc(), NO_ERROR, NULL, SPACE, coll_data::weights, and coll_data::weights_ti.
static int lang_split_key_iso (const LANG_COLLATION * lang_coll, const bool is_desc, const unsigned char * str1, const int size1, const unsigned char * str2, const int size2, const unsigned char ** key, int * byte_size, bool ignore_trailing_space) static
Definition at line 4715 of file language_support.c.
References assert, CAST_BUFLEN, lang_collation::coll, NO_ERROR, NULL, coll_data::weights, coll_data::weights_ti, and ZERO.
static int lang_split_key_utf8 (const LANG_COLLATION * lang_coll, const bool is_desc, const unsigned char * str1, const int size1, const unsigned char * str2, const int size2, const unsigned char ** key, int * byte_size, bool ignore_trailing_space) static
Definition at line 4899 of file language_support.c.
References assert, CAST_BUFLEN, lang_collation::coll, lang_get_w_first_el(), NO_ERROR, and NULL.
Referenced by lang_locale_data_load_from_lib().
static int lang_split_key_w_exp (const LANG_COLLATION * lang_coll, const bool is_desc, const unsigned char * str1, const int size1, const unsigned char * str2, const int size2, const unsigned char ** key, int * byte_size, bool ignore_trailing_space) static
Definition at line 5001 of file language_support.c.
References ASCII_SPACE, assert, CAST_BUFLEN, lang_collation::coll, lang_get_uca_w_l13(), NO_ERROR, NULL, and UCA_GET_L1_W.
Referenced by lang_locale_data_load_from_lib().
static int lang_str_utf8_trail_zero_weights (const LANG_COLLATION * lang_coll, const unsigned char * str, int size) static
Definition at line 4504 of file language_support.c.
References lang_collation::built_in, CAST_BUFLEN, lang_collation::coll, intl_utf8_to_cp(), coll_data::w_count, coll_data::weights, coll_data::weights_ti, and while().
Referenced by lang_strmatch_utf8(), and lang_strmatch_utf8_w_contr().
static int lang_str_utf8_trail_zero_weights_w_exp (const COLL_DATA * coll_data, const int level, const unsigned char * str, int size) static
Definition at line 4537 of file language_support.c.
References assert, CAST_BUFLEN, GET_UCA_WEIGHT, lang_get_uca_w_l13(), lang_get_uca_w_l4(), and NULL.
Referenced by lang_strmatch_utf8_uca_w_level().
static int lang_strcmp_utf8 (const LANG_COLLATION * lang_coll, const unsigned char * str1, const int size1, const unsigned char * str2, const int size2, bool ignore_trailing_space) static
Definition at line 2828 of file language_support.c.
References lang_strmatch_utf8(), and NULL.
Referenced by lang_locale_data_load_from_lib().
static int lang_strcmp_utf8_uca (const LANG_COLLATION * lang_coll, const unsigned char * str1, const int size1, const unsigned char * str2, const int size2, bool ignore_trailing_space) static
Definition at line 4341 of file language_support.c.
References lang_collation::coll, lang_strmatch_utf8_uca_w_coll_data(), and NULL.
Referenced by lang_locale_data_load_from_lib().
static int lang_strcmp_utf8_w_contr (const LANG_COLLATION * lang_coll, const unsigned char * str1, const int size1, const unsigned char * str2, const int size2, bool ignore_trailing_space) static
Definition at line 2991 of file language_support.c.
References lang_strmatch_utf8_w_contr(), and NULL.
Referenced by lang_locale_data_load_from_lib().
static int lang_strmatch_binary (const LANG_COLLATION * lang_coll, bool is_match, const unsigned char * str1, int size1, const unsigned char * str2, int size2, const unsigned char * escape, const bool has_last_escape, int * str1_match_size, bool ignore_trailing_space) static
Definition at line 6523 of file language_support.c.
References assert, CAST_BUFLEN, and NULL.
static int lang_strmatch_byte (const LANG_COLLATION * lang_coll, bool is_match, const unsigned char * str1, int size1, const unsigned char * str2, int size2, const unsigned char * escape, const bool has_last_escape, int * str1_match_size, bool ignore_trailing_space) static
Definition at line 5580 of file language_support.c.
References assert, CAST_BUFLEN, lang_collation::coll, for(), NULL, SPACE, coll_data::w_count, coll_data::weights, coll_data::weights_ti, and ZERO.
static int lang_strmatch_ko (const LANG_COLLATION * lang_coll, bool is_match, const unsigned char * str1, int size1, const unsigned char * str2, int size2, const unsigned char * escape, const bool has_last_escape, int * str1_match_size, bool ignore_trailing_space) static
Definition at line 6271 of file language_support.c.
References ASCII_SPACE, assert, CAST_BUFLEN, cmp, EUC_SPACE, intl_nextchar_euc(), NULL, and ZERO.
static int lang_strmatch_utf8 (const LANG_COLLATION * lang_coll, bool is_match, const unsigned char * str1, int size1, const unsigned char * str2, int size2, const unsigned char * escape, const bool has_last_escape, int * str1_match_size, bool ignore_trailing_space) static
Definition at line 2851 of file language_support.c.
References assert, lang_collation::built_in, CAST_BUFLEN, lang_collation::coll, intl_utf8_to_cp(), lang_str_utf8_trail_zero_weights(), NULL, SPACE, coll_data::w_count, coll_data::weights, coll_data::weights_ti, and ZERO.
Referenced by lang_locale_data_load_from_lib(), and lang_strcmp_utf8().
static int lang_strmatch_utf8_uca (const LANG_COLLATION * lang_coll, bool is_match, const unsigned char * str1, const int size1, const unsigned char * str2, const int size2, const unsigned char * escape, const bool has_last_escape, int * str1_match_size, bool ignore_trailing_space) static
Definition at line 4363 of file language_support.c.
References lang_collation::coll, and lang_strmatch_utf8_uca_w_coll_data().
Referenced by lang_locale_data_load_from_lib().
int lang_strmatch_utf8_uca_w_coll_data (const COLL_DATA * coll_data, bool is_match, const unsigned char * str1, const int size1, const unsigned char * str2, const int size2, const unsigned char * escape, const bool has_last_escape, int * str1_match_size, bool ignore_trailing_space)
Definition at line 4389 of file language_support.c.
References assert, lang_back_strmatch_utf8_uca_w_level(), lang_strmatch_utf8_uca_w_level(), uca_options::sett_backwards, uca_options::sett_caseFirst, uca_options::sett_caseLevel, uca_options::sett_strength, TAILOR_PRIMARY, TAILOR_SECONDARY, TAILOR_TERTIARY, and coll_data::uca_opt.
Referenced by comp_func_coll_uca_exp(), lang_strcmp_utf8_uca(), and lang_strmatch_utf8_uca().
static int lang_strmatch_utf8_uca_w_level (const COLL_DATA * coll_data, const int level, bool is_match, const unsigned char * str1, const int size1, const unsigned char * str2, const int size2, const unsigned char * escape, const bool has_last_escape, int * offset_next_level, int * str1_match_size, bool ignore_trailing_space) static
Definition at line 3603 of file language_support.c.
References ASCII_SPACE, assert, CAST_BUFLEN, GET_UCA_WEIGHT, intl_cmp_char(), INTL_CODESET_UTF8, INTL_CONTR_FOUND, INTL_MASK_CONTR, lang_get_uca_w_l13(), lang_get_uca_w_l4(), lang_str_utf8_trail_zero_weights_w_exp(), MATCH_CONTR_BOUND_ALLOW, NULL, uca_options::sett_match_contr, and coll_data::uca_opt.
Referenced by lang_strmatch_utf8_uca_w_coll_data().
static int lang_strmatch_utf8_w_contr (const LANG_COLLATION * lang_coll, bool is_match, const unsigned char * str1, int size1, const unsigned char * str2, int size2, const unsigned char * escape, const bool has_last_escape, int * str1_match_size, bool ignore_trailing_space) static
Definition at line 3015 of file language_support.c.
References assert, CAST_BUFLEN, lang_collation::coll, coll_data::contr_min_size, coll_data::cp_first_contr_count, coll_data::cp_first_contr_offset, intl_Len_utf8_char, intl_utf8_to_cp(), lang_get_contr_for_string(), lang_str_utf8_trail_zero_weights(), MATCH_CONTR_BOUND_ALLOW, NULL, uca_options::sett_match_contr, coll_contraction::size, coll_data::uca_opt, coll_data::w_count, coll_data::weights, and coll_contraction::wv.
Referenced by lang_locale_data_load_from_lib(), and lang_strcmp_utf8_w_contr().
static void lang_unload_libraries (void) static
Definition at line 7365 of file language_support.c.
References assert, i, loclib_Handle, loclib_Handle_count, and NULL.
Referenced by init_user_locales(), and lang_final().
const ALPHABET_DATA* lang_user_alphabet_w_coll (const int collation_id)
Definition at line 1741 of file language_support.c.
References lang_locale_data::alphabet, assert, lang_collation::default_lang, lang_get_collation(), and NULL.
Referenced by db_string_lower(), and db_string_upper().
static int register_collation (LANG_COLLATION * coll) static
Definition at line 1572 of file language_support.c.
References assert, lang_collation::built_in, lang_collation::coll, coll_data::coll_id, coll_data::coll_name, ER_LOC_INIT, ERR_MSG_SIZE, lang_collation::init_coll, LANG_COLL_DEFAULT, lang_Count_collations, LANG_MAX_BUILTIN_COLLATIONS, LANG_MAX_COLLATIONS, LOG_LOCALE_ERROR, NO_ERROR, and NULL.
Referenced by lang_init_builtin(), and lang_locale_data_load_from_lib().
static int register_lang_locale_data (LANG_LOCALE_DATA * lld) static
Definition at line 1802 of file language_support.c.
References assert, lang_locale_data::codeset, lang_locale_data::default_lang_coll, ER_LOC_INIT, find_lang_locale_data(), init_builtin_calendar_names(), lang_collation::init_coll, lang_locale_data::initloc, INTL_LANG_USER_DEF_START, lang_locale_data::is_initialized, lang_locale_data::is_user_data, lang_Count_locales, lang_locale_data::lang_id, LANG_MAX_LOADED_LOCALES, lang_locale_data::lang_name, LOG_LOCALE_ERROR, lang_locale_data::next_lld, NO_ERROR, and NULL.
Referenced by init_user_locales(), and lang_init_builtin().
static int set_current_locale (void) static
Definition at line 1016 of file language_support.c.
References assert, lang_locale_data::codeset, db_date_locale_init(), lang_locale_data::default_currency_code, ER_LOC_INIT, ERR_MSG_SIZE, lang_get_codeset_name(), lang_get_lang_id_from_name(), lang_Init_w_error, lang_Lang_id, lang_Lang_name, lang_Loc_charset, lang_Loc_currency, lang_locale_data::lang_name, LOG_LOCALE_ERROR, lang_locale_data::next_lld, NO_ERROR, NULL, set_default_lang(), and snprintf_dots_truncate.
Referenced by lang_set_charset_lang().
static void set_default_lang (void) static
Definition at line 1332 of file language_support.c.
References lang_locale_data::codeset, lang_locale_data::default_currency_code, INTL_LANG_ENGLISH, lang_Lang_id, lang_Lang_name, lang_Loc_charset, lang_Loc_currency, lang_Loc_name, LANG_NAME_DEFAULT, and lc_English_iso88591.
Referenced by lang_set_charset_lang(), and set_current_locale().
static int set_msg_lang_from_env (void) static
Definition at line 1068 of file language_support.c.
References ARG_FILE_LINE, assert, check_env_lang_val(), envvar_get(), ER_ERROR_SEVERITY, ER_LOC_INIT, er_set(), ERR_MSG_SIZE, LANG_MAX_LANGNAME, lang_Msg_env_initialized, lang_Msg_loc_name, LANG_NAME_DEFAULT, NO_ERROR, NULL, strlen, and strncpy_bufsize.
Referenced by lang_get_msg_Loc_name(), and lang_init_builtin().
Variable Documentation
LANG_COLLATION* built_In_collations[] static
Initial value:
= {
  &coll_Iso_binary,
  &coll_Utf8_binary,
  &coll_Iso88591_en_cs,
  &coll_Iso88591_en_ci,
  &coll_Utf8_en_cs,
  &coll_Utf8_en_ci,
  &coll_Utf8_tr_cs,
  &coll_Utf8_ko_cs,
  &coll_Euckr_bin,
  &coll_Binary
}
Definition at line 833 of file language_support.c.
LANG_DEFAULTS builtin_Langs[]
Initial value:
= {
  {LANG_NAME_ENGLISH, INTL_LANG_ENGLISH, INTL_CODESET_ISO88591},
  {LANG_NAME_ENGLISH, INTL_LANG_ENGLISH, INTL_CODESET_UTF8},
  {LANG_NAME_KOREAN, INTL_LANG_KOREAN, INTL_CODESET_UTF8},
  {LANG_NAME_KOREAN, INTL_LANG_KOREAN, INTL_CODESET_KSC5601_EUC},
  {LANG_NAME_KOREAN, INTL_LANG_KOREAN, INTL_CODESET_ISO88591},
  {LANG_NAME_TURKISH, INTL_LANG_TURKISH, INTL_CODESET_UTF8},
  {LANG_NAME_TURKISH, INTL_LANG_TURKISH, INTL_CODESET_ISO88591}
}
Definition at line 121 of file language_support.c.
Referenced by lang_get_default_codeset(), and lang_is_codeset_allowed().
LANG_COLLATION coll_Binary static
Initial value:
= {
  INTL_CODESET_BINARY, 1, 0, DEFAULT_COLL_OPTIONS, NULL,
  {LANG_COLL_BINARY, "binary",
   LANG_COLL_GENERIC_SORT_OPT,
   NULL, NULL,
   NULL, NULL,
   0,
   LANG_COLL_NO_EXP,
   LANG_COLL_NO_CONTR,
   "93fbdcc87193d2783b2396c6bec068bb"},
  lang_fastcmp_binary,
  lang_strmatch_binary,
  lang_next_alpha_char_iso88591,
  lang_split_key_binary,
  lang_mht2str_default,
  NULL
}
Definition at line 657 of file language_support.c.
LANG_COLLATION coll_Euckr_bin static
Initial value:
= {
  INTL_CODESET_KSC5601_EUC, 1, 0, DEFAULT_COLL_OPTIONS, NULL,
  {LANG_COLL_EUCKR_BINARY, "euckr_bin",
   LANG_COLL_GENERIC_SORT_OPT,
   lang_Weight_EN_cs, lang_Next_alpha_char_EN_cs,
   lang_Weight_EN_cs_ti, lang_Next_alpha_char_EN_cs_ti,
   LANG_CHAR_COUNT_EN,
   LANG_COLL_NO_EXP,
   LANG_COLL_NO_CONTR,
   "18fb633e87f0a3a785ef38cf2a6a7789"},
  lang_fastcmp_ko,
  lang_strmatch_ko,
  lang_next_alpha_char_ko,
  lang_split_key_euckr,
  lang_mht2str_ko,
  lang_init_coll_en_cs
}
Definition at line 599 of file language_support.c.
LANG_COLLATION coll_Iso88591_en_ci static
Initial value:
= {
  INTL_CODESET_ISO88591, 1, 0, CI_COLL_OPTIONS, NULL,
  {LANG_COLL_ISO_EN_CI, "iso88591_en_ci",
   LANG_COLL_GENERIC_SORT_OPT,
   lang_Weight_EN_ci, lang_Next_alpha_char_EN_ci,
   lang_Weight_EN_ci_ti, lang_Next_alpha_char_EN_ci_ti,
   LANG_CHAR_COUNT_EN,
   LANG_COLL_NO_EXP,
   LANG_COLL_NO_CONTR,
   "b3fb4c073fbc76c5ec302da9128d9542"},
  lang_fastcmp_byte,
  lang_strmatch_byte,
  lang_next_coll_byte,
  lang_split_key_byte,
  lang_mht2str_byte,
  lang_init_coll_en_ci
}
Definition at line 739 of file language_support.c.
LANG_COLLATION coll_Iso88591_en_cs static
Initial value:
= {
  INTL_CODESET_ISO88591, 1, 0, DEFAULT_COLL_OPTIONS, NULL,
  {LANG_COLL_ISO_EN_CS, "iso88591_en_cs",
   LANG_COLL_GENERIC_SORT_OPT,
   lang_Weight_EN_cs, lang_Next_alpha_char_EN_cs,
   lang_Weight_EN_cs_ti, lang_Next_alpha_char_EN_cs_ti,
   LANG_CHAR_COUNT_EN,
   LANG_COLL_NO_EXP,
   LANG_COLL_NO_CONTR,
   "707cef004e58be204d999d8a2abb4cc3"},
  lang_fastcmp_byte,
  lang_strmatch_byte,
  lang_next_alpha_char_iso88591,
  lang_split_key_iso,
  lang_mht2str_default,
  NULL
}
Definition at line 366 of file language_support.c.
LANG_COLLATION coll_Iso_binary static
Initial value:
= {
  INTL_CODESET_ISO88591, 1, 0, DEFAULT_COLL_OPTIONS, NULL,
  {LANG_COLL_ISO_BINARY, "iso88591_bin",
   LANG_COLL_GENERIC_SORT_OPT,
   lang_Weight_EN_cs, lang_Next_alpha_char_EN_cs,
   lang_Weight_EN_cs_ti, lang_Next_alpha_char_EN_cs_ti,
   LANG_CHAR_COUNT_EN,
   LANG_COLL_NO_EXP,
   LANG_COLL_NO_CONTR,
   "54735f231842c3a673161fc90670989b"},
  lang_fastcmp_byte,
  lang_strmatch_byte,
  lang_next_alpha_char_iso88591,
  lang_split_key_iso,
  lang_mht2str_default,
  NULL
}
Definition at line 699 of file language_support.c.
Referenced by lang_init_builtin().
LANG_COLLATION coll_Utf8_binary static
Initial value:
= {
  INTL_CODESET_UTF8, 1, 0, DEFAULT_COLL_OPTIONS, NULL,
  {LANG_COLL_UTF8_BINARY, "utf8_bin",
   LANG_COLL_GENERIC_SORT_OPT,
   lang_Weight_EN_cs, lang_Next_alpha_char_EN_cs,
   lang_Weight_EN_cs_ti, lang_Next_alpha_char_EN_cs_ti,
   LANG_CHAR_COUNT_EN,
   LANG_COLL_NO_EXP,
   LANG_COLL_NO_CONTR,
   "d16a9a3825e263f76028c1e8c3cd043d"},
  lang_fastcmp_byte,
  lang_strmatch_utf8,
  lang_next_coll_char_utf8,
  lang_split_key_utf8,
  lang_mht2str_byte,
  NULL
}
Definition at line 718 of file language_support.c.
LANG_COLLATION coll_Utf8_en_ci static
Initial value:
= {
  INTL_CODESET_UTF8, 1, 1, CI_COLL_OPTIONS, NULL,
  {LANG_COLL_UTF8_EN_CI, "utf8_en_ci",
   LANG_COLL_GENERIC_SORT_OPT,
   lang_Weight_EN_ci, lang_Next_alpha_char_EN_ci,
   lang_Weight_EN_ci_ti, lang_Next_alpha_char_EN_ci_ti,
   LANG_CHAR_COUNT_EN,
   LANG_COLL_NO_EXP,
   LANG_COLL_NO_CONTR,
   "3050bc8e9814b196f4bbb84759aab77c"},
  lang_fastcmp_byte,
  lang_strmatch_utf8,
  lang_next_coll_char_utf8,
  lang_split_key_utf8,
  lang_mht2str_byte,
  lang_init_coll_en_ci
}
Definition at line 758 of file language_support.c.
LANG_COLLATION coll_Utf8_en_cs static
Initial value:
= {
  INTL_CODESET_UTF8, 1, 1, DEFAULT_COLL_OPTIONS, NULL,
  {LANG_COLL_UTF8_EN_CS, "utf8_en_cs",
   LANG_COLL_GENERIC_SORT_OPT,
   lang_Weight_EN_cs, lang_Next_alpha_char_EN_cs,
   lang_Weight_EN_cs_ti, lang_Next_alpha_char_EN_cs_ti,
   LANG_CHAR_COUNT_EN,
   LANG_COLL_NO_EXP,
   LANG_COLL_NO_CONTR,
   "1bdb1b1f630edc508be37f66dfdce7b0"},
  lang_fastcmp_byte,
  lang_strmatch_utf8,
  lang_next_coll_char_utf8,
  lang_split_key_utf8,
  lang_mht2str_byte,
  lang_init_coll_en_cs
}
Definition at line 333 of file language_support.c.
LANG_COLLATION coll_Utf8_ko_cs static
Initial value:
= {
  INTL_CODESET_UTF8, 1, 1, DEFAULT_COLL_OPTIONS, NULL,
  {LANG_COLL_UTF8_KO_CS, "utf8_ko_cs",
   LANG_COLL_GENERIC_SORT_OPT,
   lang_Weight_EN_cs, lang_Next_alpha_char_EN_cs,
   lang_Weight_EN_cs_ti, lang_Next_alpha_char_EN_cs_ti,
   LANG_CHAR_COUNT_EN,
   LANG_COLL_NO_EXP,
   LANG_COLL_NO_CONTR,
   "422c85ede1e265a761078763d2240c81"},
  lang_strcmp_utf8,
  lang_strmatch_utf8,
  lang_next_coll_char_utf8,
  lang_split_key_utf8,
  lang_mht2str_utf8,
  lang_init_coll_en_cs
}
Definition at line 539 of file language_support.c.
LANG_COLLATION coll_Utf8_tr_cs static
Initial value:
= {
  INTL_CODESET_UTF8, 1, 1, DEFAULT_COLL_OPTIONS, NULL,
  {LANG_COLL_UTF8_TR_CS, "utf8_tr_cs",
   LANG_COLL_GENERIC_SORT_OPT,
   lang_Weight_TR, lang_Next_alpha_char_TR,
   lang_Weight_TR_ti, lang_Next_alpha_char_TR_ti,
   LANG_CHAR_COUNT_TR,
   LANG_COLL_NO_EXP,
   LANG_COLL_NO_CONTR,
   "52f12f045d2fc90c3a818d0b334485d7"},
  lang_strcmp_utf8,
  lang_strmatch_utf8,
  lang_next_coll_char_utf8,
  lang_split_key_utf8,
  lang_mht2str_utf8,
  lang_init_coll_Utf8_tr_cs
}
Definition at line 777 of file language_support.c.
TEXT_CONVERSION con_Iso_8859_1_conv
Definition at line 128 of file intl_support.c.
Referenced by lang_locale_data_load_from_lib().
TEXT_CONVERSION con_Iso_8859_9_conv
Definition at line 116 of file intl_support.c.
Referenced by lang_locale_data_load_from_lib().
TEXT_CONVERSION* console_Conv = NULL static
Definition at line 155 of file language_support.c.
Referenced by lang_get_txt_conv().
UNICODE_NORMALIZATION* generic_Unicode_norm = NULL static
Definition at line 167 of file language_support.c.
Referenced by lang_get_generic_unicode_norm().
bool lang_Builtin_initialized = false static
Definition at line 104 of file language_support.c.
Referenced by lang_final(), and lang_init_builtin().
bool lang_Charset_initialized = false static
Definition at line 107 of file language_support.c.
Referenced by lang_charset(), lang_date_format_parse(), lang_final(), lang_get_first_locale_for_lang(), lang_get_specific_locale(), lang_init(), lang_locale(), lang_set_charset(), lang_set_charset_lang(), and lang_set_language().
LANG_COLLATION* lang_Collations[LANG_MAX_COLLATIONS] = { NULL }
Definition at line 67 of file language_support.c.
int lang_Count_collations = 0 static
Definition at line 164 of file language_support.c.
Referenced by lang_check_coll_compat(), lang_collation_count(), lang_free_collations(), and register_collation().
int lang_Count_locales = 0 static
Definition at line 162 of file language_support.c.
Referenced by destroy_user_locales(), find_lang_locale_data(), init_user_locales(), lang_check_locale_compat(), lang_get_first_locale_for_lang(), lang_get_lang_id_from_flag(), lang_get_lang_id_from_name(), lang_get_lang_name_from_id(), lang_get_specific_locale(), lang_locale_currency(), lang_locales_count(), lang_set_flag_from_lang_id(), and register_lang_locale_data().
char lang_date_format_TR[] = "DD.MM.YYYY" static
Definition at line 145 of file language_support.c.
char lang_datetime_format_TR[] = "HH24:MI:SS.FF DD.MM.YYYY" static
Definition at line 146 of file language_support.c.
char lang_datetimetz_format_TR[] = "HH24:MI:SS.FF DD.MM.YYYY TZR" static
Definition at line 148 of file language_support.c.
const DB_CHARSET lang_Db_charsets[] static
Initial value:
= {
  {"ascii", "US English charset - ASCII encoding", " ", "",
   "", INTL_CODESET_ASCII, 1},
  {"raw-bits", "Uninterpreted bits - Raw encoding", "", "",
   "", INTL_CODESET_RAW_BITS, 1},
  {"raw-bytes", "Uninterpreted bytes - Raw encoding", "", "_binary",
   "binary", INTL_CODESET_BINARY, 1},
  {"iso8859-1", "Latin 1 charset - ISO 8859 encoding", " ", "_iso88591",
   "iso88591", INTL_CODESET_ISO88591, 1},
  {"ksc-euc", "KSC 5601 1990 charset - EUC encoding", "\241\241", "_euckr",
   "euckr", INTL_CODESET_KSC5601_EUC, 2},
  {"utf-8", "UNICODE charset - UTF-8 encoding", " ", "_utf8",
   "utf8", INTL_CODESET_UTF8, 1},
  {"", "", "", "", "", INTL_CODESET_NONE, 0}
}
Definition at line 169 of file language_support.c.
bool lang_Init_w_error = false static
Definition at line 106 of file language_support.c.
Referenced by lang_final(), lang_init(), lang_set_charset_lang(), and set_current_locale().
bool lang_Initialized = false static
Definition at line 105 of file language_support.c.
Referenced by lang_final(), lang_init(), lang_init_console_txt_conv(), and lang_set_charset_lang().
INTL_LANG lang_Lang_id = INTL_LANG_ENGLISH static
Definition at line 61 of file language_support.c.
Referenced by lang_id(), lang_set_charset_lang(), set_current_locale(), and set_default_lang().
char lang_Lang_name[LANG_MAX_LANGNAME] = LANG_NAME_DEFAULT static
Definition at line 64 of file language_support.c.
Referenced by lang_get_Lang_name(), lang_set_charset_lang(), set_current_locale(), and set_default_lang().
bool lang_Language_initialized = false static
Definition at line 108 of file language_support.c.
Referenced by lang_currency(), lang_date_format_parse(), lang_final(), lang_get_first_locale_for_lang(), lang_get_Lang_name(), lang_get_specific_locale(), lang_id(), lang_init(), lang_locale(), lang_locale_currency(), and lang_set_charset_lang().
LANG_LOCALE_DATA* lang_Loaded_locales[LANG_MAX_LOADED_LOCALES] = { NULL } static
Definition at line 160 of file language_support.c.
INTL_CODESET lang_Loc_charset = INTL_CODESET_ISO88591
Definition at line 66 of file language_support.c.
Referenced by lang_charset(), lang_set_charset(), lang_set_charset_lang(), set_current_locale(), and set_default_lang().
DB_CURRENCY lang_Loc_currency = DB_CURRENCY_DOLLAR static
Definition at line 65 of file language_support.c.
Referenced by lang_currency(), set_current_locale(), and set_default_lang().
LANG_LOCALE_DATA* lang_Loc_data = &lc_English_iso88591 static
Definition at line 697 of file language_support.c.
Referenced by lang_locale().
char lang_Loc_name[LANG_MAX_LANGNAME] = LANG_NAME_DEFAULT static
Definition at line 62 of file language_support.c.
Referenced by lang_set_charset_lang(), and set_default_lang().
unsigned int lang_lower_EN[LANG_CHAR_COUNT_EN] static
Definition at line 318 of file language_support.c.
Referenced by lang_initloc_en_utf8().
unsigned int lang_lower_i_TR[LANG_CHAR_COUNT_TR] static
Definition at line 142 of file language_support.c.
Referenced by lang_initloc_tr_utf8().
unsigned int lang_lower_TR[LANG_CHAR_COUNT_TR] static
Definition at line 140 of file language_support.c.
Referenced by lang_initloc_tr_utf8().
bool lang_Msg_env_initialized = false static
Definition at line 109 of file language_support.c.
Referenced by lang_final(), lang_get_msg_Loc_name(), and set_msg_lang_from_env().
char lang_Msg_loc_name[LANG_MAX_LANGNAME] = LANG_NAME_DEFAULT static
Definition at line 63 of file language_support.c.
Referenced by lang_get_msg_Loc_name(), and set_msg_lang_from_env().
unsigned int lang_Next_alpha_char_EN_ci[LANG_CHAR_COUNT_EN] static
Definition at line 86 of file language_support.c.
unsigned int lang_Next_alpha_char_EN_ci_ti[LANG_CHAR_COUNT_EN] static
Definition at line 92 of file language_support.c.
unsigned int lang_Next_alpha_char_EN_cs[LANG_CHAR_COUNT_EN] static
Definition at line 83 of file language_support.c.
unsigned int lang_Next_alpha_char_EN_cs_ti[LANG_CHAR_COUNT_EN] static
Definition at line 89 of file language_support.c.
unsigned int lang_Next_alpha_char_TR[LANG_CHAR_COUNT_TR] static
Definition at line 95 of file language_support.c.
Referenced by lang_init_coll_Utf8_tr_cs().
unsigned int lang_Next_alpha_char_TR_ti[LANG_CHAR_COUNT_TR] static
Definition at line 98 of file language_support.c.
Referenced by lang_init_coll_Utf8_tr_cs().
bool lang_Parser_use_client_charset = true static
Definition at line 2633 of file language_support.c.
Referenced by lang_get_parser_use_client_charset(), and lang_set_parser_use_client_charset().
char lang_time_format_TR[] = "HH24:MI:SS" static
Definition at line 144 of file language_support.c.
char lang_timestamp_format_TR[] = "HH24:MI:SS DD.MM.YYYY" static
Definition at line 147 of file language_support.c.
char lang_timestamptz_format_TR[] = "HH24:MI:SS DD.MM.YYYY TZR" static
Definition at line 149 of file language_support.c.
unsigned int lang_upper_EN[LANG_CHAR_COUNT_EN] static
Definition at line 317 of file language_support.c.
Referenced by lang_initloc_en_utf8().
unsigned int lang_upper_i_TR[LANG_CHAR_COUNT_TR] static
Definition at line 141 of file language_support.c.
Referenced by lang_initloc_tr_utf8().
unsigned int lang_upper_TR[LANG_CHAR_COUNT_TR] static
Definition at line 139 of file language_support.c.
Referenced by lang_initloc_tr_utf8().
int lang_w_map_EN[LANG_W_MAP_COUNT_EN] static
Definition at line 323 of file language_support.c.
unsigned int lang_Weight_EN_ci[LANG_CHAR_COUNT_EN] static
Definition at line 85 of file language_support.c.
unsigned int lang_Weight_EN_ci_ti[LANG_CHAR_COUNT_EN] static
Definition at line 91 of file language_support.c.
unsigned int lang_Weight_EN_cs[LANG_CHAR_COUNT_EN] static
Definition at line 82 of file language_support.c.
unsigned int lang_Weight_EN_cs_ti[LANG_CHAR_COUNT_EN] static
Definition at line 88 of file language_support.c.
unsigned int lang_Weight_TR[LANG_CHAR_COUNT_TR] static
Definition at line 94 of file language_support.c.
Referenced by lang_init_coll_Utf8_tr_cs().
unsigned int lang_Weight_TR_ti[LANG_CHAR_COUNT_TR] static
Definition at line 97 of file language_support.c.
Referenced by lang_init_coll_Utf8_tr_cs().
LANG_LOCALE_DATA lc_English_binary static
Initial value:
= {
  NULL,
  LANG_NAME_ENGLISH,
  INTL_LANG_ENGLISH,
  INTL_CODESET_BINARY,
  LOCALE_DUMMY_ALPHABET (INTL_CODESET_BINARY),
  LOCALE_DUMMY_ALPHABET (INTL_CODESET_BINARY),
  &coll_Binary,
  NULL,
  false,
  LOCALE_NULL_DATE_FORMATS,
  LOCALE_NULL_CALENDAR_NAMES,
  '.',
  ',',
  DB_CURRENCY_DOLLAR,
  LANG_NO_NORMALIZATION,
  (char *) "390462b716493cbd74c77f545a77a2bf",
  lang_initloc_en_binary,
  false
}
Definition at line 676 of file language_support.c.
LANG_LOCALE_DATA lc_English_iso88591 static
Definition at line 386 of file language_support.c.
Referenced by set_default_lang().
LANG_LOCALE_DATA lc_English_utf8 static
Definition at line 424 of file language_support.c.
LANG_LOCALE_DATA lc_Korean_euckr static
Definition at line 620 of file language_support.c.
LANG_LOCALE_DATA lc_Korean_iso88591 static
Definition at line 502 of file language_support.c.
LANG_LOCALE_DATA lc_Korean_utf8 static
Definition at line 561 of file language_support.c.
LANG_LOCALE_DATA lc_Turkish_iso88591 static
Definition at line 464 of file language_support.c.
LANG_LOCALE_DATA lc_Turkish_utf8 static
Definition at line 796 of file language_support.c.
void** loclib_Handle = NULL static
Definition at line 151 of file language_support.c.
Referenced by init_user_locales(), and lang_unload_libraries().
int loclib_Handle_count = 0 static
Definition at line 153 of file language_support.c.
Referenced by init_user_locales(), and lang_unload_libraries().
int loclib_Handle_size = 0 static
Definition at line 152 of file language_support.c.
Referenced by init_user_locales().
UCA_L13_W uca_l13_max_weight = 0xffffffff static
Definition at line 3378 of file language_support.c.
Referenced by lang_get_uca_back_weight_l13(), lang_get_uca_w_l13(), and lang_mht2str_utf8_exp().
UCA_L4_W uca_l4_max_weight = 0xffff static
Definition at line 3379 of file language_support.c.
Referenced by lang_get_uca_w_l4(), and lang_mht2str_utf8_exp().