CUBRID Engine: src/loaddb/load_sa_loader.hpp File Reference
load_sa_loader.hpp File Reference
#include "load_common.hpp"
Classes
class cubload::sa_class_installer
class cubload::sa_object_loader
Namespaces
cubload
Functions
void ldr_sa_load (cubload::load_args *args, int *status, bool *interrupted)
void print_log_msg (int verbose, const char *fmt,...)
void ldr_increment_err_total ()
void ldr_increment_fails ()
Function Documentation
void ldr_increment_err_total ()
Definition at line 1024 of file load_sa_loader.cpp.
References ldr_context::err_total.
Referenced by cubload::error_handler::log_error_message().
void ldr_increment_fails ()
Definition at line 1037 of file load_sa_loader.cpp.
References Total_fails.
Referenced by cubload::error_handler::log_error_message().
void ldr_sa_load (cubload::load_args * args, int * status, bool * interrupted)
Definition at line 6204 of file load_sa_loader.cpp.
References db_abort_transaction(), db_commit_transaction(), db_error_string(), cubload::load_args::disable_statistics, errors, cubload::driver::get_class_installer(), cubthread::get_entry(), cubload::load_args::ignore_logging, cubload::class_installer::install_class(), ldr_Driver, ldr_final(), ldr_init(), ldr_init_driver(), ldr_Interrupt_type, ldr_Jmp_buf, ldr_register_post_commit_handler(), ldr_register_post_interrupt_handler(), ldr_signal_handler(), ldr_start(), ldr_stats(), cubload::LDR_STOP_AND_ABORT_INTERRUPT, cubload::LDR_STOP_AND_COMMIT_INTERRUPT, ldr_update_statistics(), cubload::load_args::load_only, LOADDB_MSG_CHECKING, LOADDB_MSG_COMMITTING, LOADDB_MSG_DEFAULT_COUNT, LOADDB_MSG_ERROR_COUNT, LOADDB_MSG_INSERT_AND_FAIL_COUNT, LOADDB_MSG_INSERTING, LOADDB_MSG_LAST_COMMITTED_LINE, LOADDB_MSG_OBJECT_COUNT, LOADDB_MSG_UPDATING_STATISTICS, locator_Dont_check_foreign_key, cubthread::entry::m_loaddb_driver, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_SET_LOADDB, NO_ERROR, NULL, cubload::load_args::object_file, cubload::driver::parse(), cubload::load_args::periodic_commit, print_log_msg(), cubload::load_args::syntax_check, cubload::load_args::table_name, Total_objects_loaded, util_arm_signal_handlers(), util_log_write_errstr(), and cubload::load_args::verbose.
Referenced by loaddb_internal().
void print_log_msg (int verbose, const char * fmt, ...)
Definition at line 82 of file load_db.c.
References assert, loaddb_log_file, and NULL.
Referenced by check_commit(), ldr_act_set_skip_current_class(), ldr_check_file(), ldr_compare_attribute_with_meta(), ldr_compare_storage_order(), ldr_exec_query_from_file(), ldr_report_num_of_commits(), ldr_sa_load(), ldr_server_load(), ldr_signal_handler(), loaddb_internal(), and print_stats().