CUBRID Engine: src/loaddb/load_object.h File Reference
load_object.h File Reference
#include "dbtype_def.h"
#include "class_object.h"
#include <vector>
Classes
struct desc_obj
struct text_output
Macros
#define CHECK_PRINT_ERROR(print_fnc)
#define CHECK_EXIT_ERROR(e)
Typedefs
typedef struct desc_obj DESC_OBJ
typedef struct text_output TEXT_OUTPUT
Functions
int text_print_flush (TEXT_OUTPUT *tout)
int text_print (TEXT_OUTPUT *tout, const char *buf, int buflen, char const *fmt,...)
DESC_OBJ * make_desc_obj (SM_CLASS *class_)
int desc_obj_to_disk (DESC_OBJ *obj, RECDES *record, bool *index_flag)
int desc_disk_to_obj (MOP classop, SM_CLASS *class_, RECDES *record, DESC_OBJ *obj)
void desc_free (DESC_OBJ *obj)
int desc_value_special_fprint (TEXT_OUTPUT *tout, DB_VALUE *value)
void desc_value_print (print_output &output_ctx, DB_VALUE *value)
int er_filter_fileset (FILE *ef)
int er_filter_errid (bool ignore_warning)
void get_ignored_errors (std::vector< int > &vec)
Macro Definition Documentation
#define CHECK_EXIT_ERROR (e)
Value:
do {                                          \
    if ((e) == NO_ERROR) {                      \
      if (((e) = er_errid()) == NO_ERROR)       \
        (e) = ER_GENERIC_ERROR;                 \
    }                                           \
  } while (0)
Definition at line 38 of file load_object.h.
Referenced by desc_value_special_fprint(), fprint_special_set(), fprint_special_strings(), itoa_print(), print_quoted_str(), process_class(), process_object(), process_set(), process_value(), set_referenced_subclasses(), and text_print().
#define CHECK_PRINT_ERROR (print_fnc)
Value:
do {                                          \
    if ((error = print_fnc) != NO_ERROR)        \
      goto exit_on_error;                       \
  } while (0)
Definition at line 32 of file load_object.h.
Referenced by desc_value_special_fprint(), fprint_special_set(), fprint_special_strings(), print_quoted_str(), process_class(), process_object(), process_set(), process_value(), and text_print().
Typedef Documentation
typedef struct desc_obj DESC_OBJ
typedef struct text_output TEXT_OUTPUT
Function Documentation
int desc_disk_to_obj (MOP classop, SM_CLASS * class_, RECDES * record, DESC_OBJ * obj)
Definition at line 930 of file load_object.c.
References ARG_FILE_LINE, desc_obj::classop, desc_obj::count, recdes::data, or_buf::env, ER_ERROR_SEVERITY, ER_FAILED, er_set(), ER_TF_BUFFER_UNDERFLOW, error(), or_buf::error_abort, get_desc_current(), get_desc_old(), i, recdes::length, NO_ERROR, NULL, or_advance(), OR_BOUND_BIT_FLAG, OR_GET_OFFSET_SIZE, or_init(), OR_INT_SIZE, OR_MVCC_FLAG_MASK, OR_MVCC_FLAG_SHIFT_BITS, OR_MVCC_FLAG_VALID_DELID, OR_MVCC_FLAG_VALID_INSID, OR_MVCC_FLAG_VALID_PREV_VERSION, or_mvcc_get_repid_and_flags(), OR_MVCC_PREV_VERSION_LSA_SIZE, OR_MVCC_REPID_MASK, OR_MVCCID_SIZE, pr_clear_value(), pr_Inhibit_oid_promotion, or_buf::ptr, rc, sm_class::repid, and desc_obj::values.
Referenced by process_class().
void desc_free (DESC_OBJ * obj)
Definition at line 138 of file load_object.c.
References desc_obj::atts, desc_obj::count, free_and_init, i, NULL, pr_clear_value(), and desc_obj::values.
Referenced by process_class().
int desc_obj_to_disk (DESC_OBJ * obj, RECDES * record, bool * index_flag)
Definition at line 532 of file load_object.c.
References recdes::area_size, assert, or_buf::buffer, desc_obj::class_, classobj_class_has_indexes(), desc_obj::classop, recdes::data, or_buf::env, error(), or_buf::error_abort, sm_class::fixed_count, recdes::length, MIGDB_MSG_TEMPORARY_CLASS_OID, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_SET_MIGDB, MVCCID_NULL, object_disk_size(), OID_ISTEMP, OR_BOUND_BIT_FLAG, or_init(), OR_MVCC_FLAG_SHIFT_BITS, OR_MVCC_FLAG_VALID_INSID, OR_MVCC_INSERT_HEADER_SIZE, OR_MVCC_MAX_HEADER_SIZE, or_put_bigint(), or_put_int(), OR_SET_VAR_OFFSET_SIZE, or_buf::ptr, put_attributes(), put_varinfo(), sm_class::repid, and WS_OID.
Referenced by disk_update_instance().
void desc_value_print (print_output & output_ctx, DB_VALUE * value)
Definition at line 1616 of file load_object.c.
References db_get_set(), db_print_value(), DB_TYPE_BLOB, DB_TYPE_CLOB, DB_TYPE_MULTISET, DB_TYPE_SEQUENCE, DB_TYPE_SET, DB_VALUE_TYPE, MIGDB_MSG_CANT_PRINT_ELO, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_SET_MIGDB, and print_set().
Referenced by emit_attribute_def(), emit_partition_parts(), emit_stored_procedure(), emit_stored_procedure_args(), export_serial(), and print_set().
int desc_value_special_fprint (TEXT_OUTPUT * tout, DB_VALUE * value)
Definition at line 1575 of file load_object.c.
References CHECK_EXIT_ERROR, CHECK_PRINT_ERROR, db_get_set(), DB_TYPE_BLOB, DB_TYPE_CLOB, DB_TYPE_MULTISET, DB_TYPE_SEQUENCE, DB_TYPE_SET, DB_VALUE_TYPE, error(), fprint_special_set(), fprint_special_strings(), MIGDB_MSG_CANT_PRINT_ELO, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_SET_MIGDB, and NO_ERROR.
Referenced by fprint_special_set(), and process_value().
int er_filter_errid (bool ignore_warning)
Definition at line 1759 of file load_object.c.
References er_clearid(), er_errid(), er_get_severity(), ER_WARNING_SEVERITY, filter_ignore_errors, filter_ignore_init, init_load_err_filter(), and NO_ERROR.
Referenced by cubload::sa_object_loader::destroy(), cubload::sa_object_loader::finish_line(), ldr_act_add_class_all_attrs(), ldr_finish_context(), ldr_refresh_attrs(), and ldr_reset_context().
int er_filter_fileset (FILE * ef)
Definition at line 1680 of file load_object.c.
References default_clear_err_filter(), ER_LAST_ERROR, filter_ignore_errors, filter_ignore_init, i, init_load_err_filter(), NULL, and ws_set_ignore_error_list_for_mflush().
Referenced by loaddb_internal().
void get_ignored_errors (std::vector< int > & vec)
Definition at line 1801 of file load_object.c.
References ER_LAST_ERROR, filter_ignore_errors, and i.
Referenced by loaddb_internal().
DESC_OBJ* make_desc_obj (SM_CLASS * class_)
Definition at line 87 of file load_object.c.
References sm_class::att_count, sm_class::attributes, desc_obj::atts, desc_obj::class_, desc_obj::classop, desc_obj::count, db_make_null(), free_and_init, sm_attribute::header, i, sm_component::next, NULL, desc_obj::updated_flag, and desc_obj::values.
Referenced by process_class().
int text_print (TEXT_OUTPUT * tout, const char * buf, int buflen, char const * fmt, ...)
Definition at line 467 of file load_object.c.
References assert, CHECK_EXIT_ERROR, CHECK_PRINT_ERROR, text_output::count, error(), text_output::iosize, NO_ERROR, NULL, text_output::ptr, and text_print_flush().
Referenced by extract_objects(), fprint_special_set(), fprint_special_strings(), print_quoted_str(), process_class(), process_object(), process_set(), and process_value().
int text_print_flush (TEXT_OUTPUT * tout)
Definition at line 442 of file load_object.c.
References text_output::buffer, text_output::count, ER_IO_WRITE, text_output::fp, NO_ERROR, and text_output::ptr.
Referenced by extract_objects(), fprint_special_strings(), and text_print().