CUBRID Engine: src/loaddb/load_sa_loader.cpp File Reference
load_sa_loader.cpp File Reference
#include "config.h"
#include <assert.h>
#include <ctype.h>
#include <errno.h>
#include <fcntl.h>
#include <fstream>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "authenticate.h"
#include "db.h"
#include "db_json.hpp"
#include "dbi.h"
#include "dbtype.h"
#include "elo.h"
#include "environment_variable.h"
#include "execute_schema.h"
#include "intl_support.h"
#include "language_support.h"
#include "load_db_value_converter.hpp"
#include "load_driver.hpp"
#include "load_error_handler.hpp"
#include "load_object.h"
#include "load_object_table.h"
#include "load_sa_loader.hpp"
#include "load_scanner.hpp"
#include "locator_cl.h"
#include "memory_alloc.h"
#include "message_catalog.h"
#include "network.h"
#include "object_accessor.h"
#include "object_primitive.h"
#include "object_representation.h"
#include "porting.h"
#include "schema_manager.h"
#include "set_object.h"
#include "system_parameter.h"
#include "thread_manager.hpp"
#include "transaction_cl.h"
#include "trigger_manager.h"
#include "utility.h"
#include "work_space.h"
Classes
struct LDR_ATTDESC
struct ldr_mop_tempoid_map
struct ldr_mop_tempoid_maps
struct ldr_context
Namespaces
cubload
Macros
#define FILTER_OUT_ERR_INTERNAL(err, expr) (err = ((expr) == NO_ERROR ? NO_ERROR : er_filter_errid(false)))
#define CHECK_ERR(err, expr)
#define CHECK_PARSE_ERR(err, expr, cont, type, str)
#define CHECK_PTR(err, expr)
#define CHECK_CONTEXT_VALIDITY(context, expr)
#define RETURN_IF_NOT_VALID(context)
#define RETURN_IF_NOT_VALID_WITH(context, ret)
#define CHECK_VALIDATION_ONLY(context)
#define GET_DOMAIN(context, domain)
#define CHECK_SKIP()
#define CHECK_SKIP_WITH(ret)
#define LDR_LOCKHINT_COUNT 1
#define MAX_DIGITS_FOR_BIGINT 19
#define MAX_DIGITS_FOR_INT 10
#define MAX_DIGITS_FOR_SHORT 5
#define ROUND(x) (int)((x) > 0 ? ((x) + .5) : ((x) - .5))
#define PARSE_ELO_STR(str, new_len)
#define LDR_MOP_TEMPOID_MAPS_PRESIZE 1000
#define LDR_ARG_GROW_SIZE 128
Typedefs
typedef struct ldr_context LDR_CONTEXT
typedef void(* LDR_POST_COMMIT_HANDLER) (int64_t)
typedef void(* LDR_POST_INTERRUPT_HANDLER) (int64_t)
typedef int(* LDR_SETTER) (LDR_CONTEXT *, const char *, size_t, SM_ATTRIBUTE *)
typedef int(* LDR_ELEM) (LDR_CONTEXT *, const char *, size_t, DB_VALUE *)
typedef struct LDR_ATTDESC LDR_ATTDESC
typedef struct ldr_mop_tempoid_map LDR_MOP_TEMPOID_MAP
typedef struct ldr_mop_tempoid_maps LDR_MOP_TEMPOID_MAPS
Functions
static int ldr_start ()
static int ldr_destroy (LDR_CONTEXT *context, int err)
static int ldr_init (load_args *args)
static void ldr_init_driver ()
static int ldr_final (void)
static void ldr_stats (int *errors, int64_t *objects, int *defaults, int64_t *lastcommit, int *fails)
static int ldr_update_statistics (void)
static void ldr_register_post_commit_handler ()
static void ldr_register_post_interrupt_handler ()
static void ldr_signal_handler (void)
static void ldr_report_num_of_commits (int64_t num_committed)
static void ldr_get_num_of_inserted_objects (int64_t num_objects)
static void ldr_act_init_context (LDR_CONTEXT *context, const char *class_name, size_t len)
static int ldr_act_check_missing_non_null_attrs (LDR_CONTEXT *context)
static void ldr_act_add_attr (LDR_CONTEXT *context, const char *attr_name, size_t len)
static void ldr_act_set_ref_class_id (LDR_CONTEXT *context, int id)
static void ldr_act_set_ref_class (LDR_CONTEXT *context, char *name)
static void ldr_act_set_instance_id (LDR_CONTEXT *context, int id)
static DB_OBJECT * ldr_act_get_ref_class (LDR_CONTEXT *context)
static void ldr_act_restrict_attributes (LDR_CONTEXT *context, attribute_type type)
static int ldr_act_set_constructor (LDR_CONTEXT *context, const char *name)
static int ldr_act_add_argument (LDR_CONTEXT *context, const char *name)
static void ldr_act_set_skip_current_class (char *class_name, size_t size)
static bool ldr_is_ignore_class (const char *class_name, size_t size)
static void ldr_increment_err_count (LDR_CONTEXT *context, int i)
static void ldr_clear_err_count (LDR_CONTEXT *context)
static void ldr_clear_err_total (LDR_CONTEXT *context)
static const char * ldr_class_name (LDR_CONTEXT *context)
static const char * ldr_attr_name (LDR_CONTEXT *context)
static int select_set_domain (LDR_CONTEXT *context, TP_DOMAIN *domain, TP_DOMAIN **set_domain_ptr)
static int check_object_domain (LDR_CONTEXT *context, DB_OBJECT *class_, DB_OBJECT **actual_class)
static int check_class_domain (LDR_CONTEXT *context)
static void idmap_init (void)
static void idmap_final (void)
static int idmap_grow (int size)
static int ldr_assign_class_id (DB_OBJECT *class_, int id)
static DB_OBJECT * ldr_find_class (const char *class_name)
static DB_OBJECT * ldr_get_class_from_id (int id)
static void ldr_clear_context (LDR_CONTEXT *context)
static void ldr_clear_and_free_context (LDR_CONTEXT *context)
static void ldr_internal_error (LDR_CONTEXT *context)
static void display_error_line (int adjust)
static void display_error (int adjust)
static void ldr_invalid_class_error (LDR_CONTEXT *context)
static void parse_error (LDR_CONTEXT *context, DB_TYPE token_type, const char *token)
static int clist_init (void)
static void clist_final (void)
static int is_internal_class (DB_OBJECT *class_)
static void ldr_act_elem (LDR_CONTEXT *context, const char *str, size_t len, data_type type)
static void ldr_act_attr (LDR_CONTEXT *context, const char *str, size_t len, data_type type)
static void ldr_act_meth (LDR_CONTEXT *context, const char *str, size_t len, data_type type)
static int ldr_mismatch (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_ignore (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_generic (LDR_CONTEXT *context, DB_VALUE *value)
static int ldr_null_elem (LDR_CONTEXT *context, const char *str, size_t len, DB_VALUE *val)
static int ldr_null_db_generic (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_class_attr_db_generic (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att, DB_VALUE *val)
static void ldr_act_class_attr (LDR_CONTEXT *context, const char *str, size_t len, data_type type)
static int ldr_sys_user_db_generic (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_sys_class_db_generic (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_int_elem (LDR_CONTEXT *context, const char *str, size_t len, DB_VALUE *val)
static int ldr_int_db_generic (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_int_db_bigint (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_int_db_int (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_int_db_short (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_str_elem (LDR_CONTEXT *context, const char *str, size_t len, DB_VALUE *val)
static int ldr_str_db_char (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_str_db_varchar (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_str_db_generic (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_bstr_elem (LDR_CONTEXT *context, const char *str, size_t len, DB_VALUE *val)
static int ldr_bstr_db_varbit (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_xstr_elem (LDR_CONTEXT *context, const char *str, size_t len, DB_VALUE *val)
static int ldr_xstr_db_varbit (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_nstr_elem (LDR_CONTEXT *context, const char *str, size_t len, DB_VALUE *val)
static int ldr_nstr_db_varnchar (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_numeric_elem (LDR_CONTEXT *context, const char *str, size_t len, DB_VALUE *val)
static int ldr_numeric_db_generic (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_double_elem (LDR_CONTEXT *context, const char *str, size_t len, DB_VALUE *val)
static int ldr_float_elem (LDR_CONTEXT *context, const char *str, size_t len, DB_VALUE *val)
static int ldr_real_db_generic (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_real_db_float (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_real_db_double (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_date_elem (LDR_CONTEXT *context, const char *str, size_t len, DB_VALUE *val)
static int ldr_date_db_date (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_time_elem (LDR_CONTEXT *context, const char *str, size_t len, DB_VALUE *val)
static int ldr_time_db_time (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_timestamp_elem (LDR_CONTEXT *context, const char *str, size_t len, DB_VALUE *val)
static int ldr_timestamp_db_timestamp (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_timestamptz_elem (LDR_CONTEXT *context, const char *str, size_t len, DB_VALUE *val)
static int ldr_timestampltz_elem (LDR_CONTEXT *context, const char *str, size_t len, DB_VALUE *val)
static int ldr_timestamptz_db_timestamptz (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_timestampltz_db_timestampltz (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_datetime_elem (LDR_CONTEXT *context, const char *str, size_t len, DB_VALUE *val)
static int ldr_datetime_db_datetime (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_datetimetz_elem (LDR_CONTEXT *context, const char *str, size_t len, DB_VALUE *val)
static int ldr_datetimeltz_elem (LDR_CONTEXT *context, const char *str, size_t len, DB_VALUE *val)
static int ldr_datetimetz_db_datetimetz (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_datetimeltz_db_datetimeltz (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static void ldr_date_time_conversion_error (const char *token, DB_TYPE type)
static int ldr_check_date_time_conversion (const char *str, data_type type)
static int ldr_elo_int_elem (LDR_CONTEXT *context, const char *str, size_t len, DB_VALUE *val)
static int ldr_elo_int_db_elo (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_elo_ext_elem (LDR_CONTEXT *context, const char *str, size_t len, DB_VALUE *val)
static int ldr_elo_ext_db_elo (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_mop_tempoid_maps_init (void)
static void ldr_mop_tempoid_maps_final (void)
static int ldr_add_mop_tempoid_map (MOP mop, CLASS_TABLE *table, int id)
static int ldr_assign_all_perm_oids (void)
static int find_instance (LDR_CONTEXT *context, DB_OBJECT *class_, OID *oid, int id)
static int ldr_class_oid_elem (LDR_CONTEXT *context, const char *str, size_t len, DB_VALUE *val)
static int ldr_class_oid_db_object (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_oid_elem (LDR_CONTEXT *context, const char *str, size_t len, DB_VALUE *val)
static int ldr_oid_db_object (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_monetary_elem (LDR_CONTEXT *context, const char *str, size_t len, DB_VALUE *val)
static int ldr_monetary_db_monetary (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_collection_elem (LDR_CONTEXT *context, const char *str, size_t len, DB_VALUE *val)
static int ldr_collection_db_collection (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
static int ldr_reset_context (LDR_CONTEXT *context)
static void ldr_flush (LDR_CONTEXT *context)
static int check_commit (LDR_CONTEXT *context)
static void ldr_restore_pin_and_drop_obj (LDR_CONTEXT *context, bool drop_obj)
static int ldr_finish_context (LDR_CONTEXT *context)
static int ldr_refresh_attrs (LDR_CONTEXT *context)
static int update_default_count (CLASS_TABLE *table, OID *oid)
static int update_default_instances_stats (LDR_CONTEXT *context)
static int insert_instance (LDR_CONTEXT *context)
static MOP construct_instance (LDR_CONTEXT *context)
static int insert_meth_instance (LDR_CONTEXT *context)
static int add_element (void ***elements, int *count, int *max, int grow)
static int add_argument (LDR_CONTEXT *context)
static void invalid_class_id_error (LDR_CONTEXT *context, int id)
static int ldr_init_loader (LDR_CONTEXT *context)
static void ldr_abort (void)
static void ldr_process_object_ref (object_ref_type *ref, int type)
static int ldr_act_add_class_all_attrs (const char *class_name)
static int ldr_json_elem (LDR_CONTEXT *context, const char *str, size_t len, DB_VALUE *val)
static int ldr_json_db_json (LDR_CONTEXT *context, const char *str, size_t len, SM_ATTRIBUTE *att)
void ldr_increment_err_total ()
void ldr_increment_fails ()
void ldr_sa_load (load_args *args, int *status, bool *interrupted)
Variables
const std::size_t LDR_MAX_ARGS = 32
static LDR_MOP_TEMPOID_MAPS * ldr_Mop_tempoid_maps = NULL
static bool skip_current_class = false
static bool skip_current_instance = false
bool locator_Dont_check_foreign_key
static LDR_CONTEXT * ldr_Current_context = NULL
static LDR_CONTEXT ldr_Context
static driver * ldr_Driver
static LOCK ldr_Hint_locks [LDR_LOCKHINT_COUNT]
static const char * ldr_Hint_class_names [LDR_LOCKHINT_COUNT]
static int ldr_Hint_subclasses [LDR_LOCKHINT_COUNT]
static LC_PREFETCH_FLAGS ldr_Hint_flags [LDR_LOCKHINT_COUNT]
static LDR_ELEM elem_converter [NUM_LDR_TYPES]
static int64_t Total_objects = 0
static int64_t Last_committed_line = 0
static int Total_fails = 0
static int64_t Total_objects_loaded = 0
static LDR_POST_COMMIT_HANDLER ldr_post_commit_handler = NULL
static LDR_POST_INTERRUPT_HANDLER ldr_post_interrupt_handler = NULL
static int ldr_Load_interrupted = LDR_NO_INTERRUPT
static int ldr_Interrupt_type = LDR_NO_INTERRUPT
static jmp_buf * ldr_Jmp_buf_ptr = NULL
static jmp_buf ldr_Jmp_buf
static DB_OBJECT ** Id_map = NULL
static int Id_map_size = 0
static DB_OBJLIST * internal_classes = NULL
static DB_VALUE ldr_short_tmpl
static DB_VALUE ldr_int_tmpl
static DB_VALUE ldr_bigint_tmpl
static DB_VALUE ldr_char_tmpl
static DB_VALUE ldr_varchar_tmpl
static DB_VALUE ldr_float_tmpl
static DB_VALUE ldr_double_tmpl
static DB_VALUE ldr_date_tmpl
static DB_VALUE ldr_time_tmpl
static DB_VALUE ldr_timestamp_tmpl
static DB_VALUE ldr_timestampltz_tmpl
static DB_VALUE ldr_timestamptz_tmpl
static DB_VALUE ldr_datetime_tmpl
static DB_VALUE ldr_datetimeltz_tmpl
static DB_VALUE ldr_datetimetz_tmpl
static DB_VALUE ldr_blob_tmpl
static DB_VALUE ldr_clob_tmpl
static DB_VALUE ldr_bit_tmpl
static DB_VALUE ldr_json_tmpl
void(* ldr_act)(LDR_CONTEXT *context, const char *str, size_t len, data_type type) = ldr_act_attr
Macro Definition Documentation
#define CHECK_CONTEXT_VALIDITY (context, expr)
Value:
do {                                                                  \
    if ((expr)) {                                                       \
      ldr_increment_err_count (context, 1);                             \
      context->valid = false;                                           \
    }                                                                   \
  } while (0)
Definition at line 126 of file load_sa_loader.cpp.
Referenced by cubload::sa_class_installer::check_class(), check_commit(), invalid_class_id_error(), ldr_act_add_argument(), ldr_act_add_attr(), ldr_act_add_class_all_attrs(), ldr_act_check_missing_non_null_attrs(), ldr_act_class_attr(), ldr_act_init_context(), ldr_act_set_constructor(), ldr_act_set_instance_id(), ldr_elo_ext_db_elo(), ldr_finish_context(), ldr_reset_context(), ldr_sys_class_db_generic(), and cubload::sa_object_loader::process_line().
#define CHECK_ERR (err, expr)
Value:
do {                                                                  \
    int inner_err = (expr);                                             \
    if (FILTER_OUT_ERR_INTERNAL(err, inner_err) != NO_ERROR) {          \
      display_error(0);                                                 \
      goto error_exit;                                                  \
    }                                                                   \
    if (inner_err != NO_ERROR && err == NO_ERROR ) {                    \
      skip_current_instance = true;                                     \
    }                                                                   \
  } while (0)
Definition at line 82 of file load_sa_loader.cpp.
Referenced by cubload::sa_class_installer::check_class(), check_commit(), construct_instance(), find_instance(), cubload::sa_object_loader::finish_line(), insert_instance(), insert_meth_instance(), ldr_act_add_argument(), ldr_act_add_attr(), ldr_act_add_class_all_attrs(), ldr_act_attr(), ldr_act_check_missing_non_null_attrs(), ldr_act_class_attr(), ldr_act_elem(), ldr_act_init_context(), ldr_act_meth(), ldr_act_set_constructor(), ldr_assign_all_perm_oids(), ldr_bstr_db_varbit(), ldr_class_attr_db_generic(), ldr_class_oid_db_object(), ldr_class_oid_elem(), ldr_date_db_date(), ldr_datetime_db_datetime(), ldr_datetimeltz_db_datetimeltz(), ldr_datetimetz_db_datetimetz(), ldr_elo_ext_db_elo(), ldr_finish_context(), ldr_generic(), ldr_int_db_bigint(), ldr_int_db_generic(), ldr_int_db_int(), ldr_int_db_short(), ldr_json_db_json(), ldr_mismatch(), ldr_monetary_db_monetary(), ldr_nstr_db_varnchar(), ldr_null_db_generic(), ldr_numeric_db_generic(), ldr_oid_db_object(), ldr_oid_elem(), ldr_real_db_double(), ldr_real_db_float(), ldr_real_db_generic(), ldr_refresh_attrs(), ldr_reset_context(), ldr_str_db_char(), ldr_str_db_varchar(), ldr_time_db_time(), ldr_timestamp_db_timestamp(), ldr_timestampltz_db_timestampltz(), ldr_timestamptz_db_timestamptz(), and ldr_xstr_db_varbit().
#define CHECK_PARSE_ERR (err, expr, cont, type, str)
Value:
do {                                                                  \
    int inner_err = (expr);                                             \
    if (FILTER_OUT_ERR_INTERNAL(err, inner_err) != NO_ERROR) {          \
      display_error(0);                                                 \
      parse_error(cont, type, str);                                     \
      goto error_exit;                                                  \
    }                                                                   \
    if (inner_err != NO_ERROR && err == NO_ERROR) {                     \
      skip_current_instance = true;                                     \
    }                                                                   \
  } while (0)
Definition at line 99 of file load_sa_loader.cpp.
Referenced by ldr_act_class_attr(), ldr_bstr_elem(), ldr_date_elem(), ldr_datetime_elem(), ldr_datetimeltz_elem(), ldr_datetimetz_elem(), ldr_double_elem(), ldr_float_elem(), ldr_int_db_bigint(), ldr_int_db_int(), ldr_int_db_short(), ldr_int_elem(), ldr_monetary_elem(), ldr_numeric_elem(), ldr_real_db_double(), ldr_real_db_float(), ldr_str_db_char(), ldr_str_db_varchar(), ldr_time_elem(), ldr_timestamp_elem(), ldr_timestampltz_elem(), ldr_timestamptz_elem(), and ldr_xstr_elem().
#define CHECK_PTR (err, expr)
Value:
do {                                                                  \
    if ((expr) == NULL) {                                               \
      display_error(0);                                                 \
      if (err == NO_ERROR) {                                            \
        if ((err = er_errid()) == NO_ERROR) { /* need to set errid */   \
          err = ER_GENERIC_ERROR;                                       \
          er_set(ER_ERROR_SEVERITY, ARG_FILE_LINE, err, 0);             \
        }                                                               \
      }                                                                 \
      goto error_exit;                                                  \
    }                                                                   \
  } while (0)
Definition at line 112 of file load_sa_loader.cpp.
Referenced by add_element(), find_instance(), insert_instance(), insert_meth_instance(), ldr_act_add_attr(), ldr_act_meth(), ldr_assign_all_perm_oids(), ldr_bstr_elem(), and ldr_xstr_elem().
#define CHECK_SKIP ()
Value:
do {                                \
           if (skip_current_class == true) { \
             return;                         \
           }                                 \
         } while (0)
Definition at line 157 of file load_sa_loader.cpp.
Referenced by cubload::sa_object_loader::finish_line(), ldr_act_add_attr(), ldr_act_attr(), ldr_act_init_context(), ldr_act_restrict_attributes(), ldr_act_set_instance_id(), ldr_act_set_ref_class(), ldr_act_set_ref_class_id(), cubload::sa_object_loader::process_line(), and cubload::sa_object_loader::start_line().
#define CHECK_SKIP_WITH (ret)
Value:
do {                                \
           if (skip_current_class == true) { \
             return (ret);                   \
           }                                 \
         } while (0)
Definition at line 164 of file load_sa_loader.cpp.
Referenced by ldr_act_add_argument(), ldr_act_check_missing_non_null_attrs(), and ldr_act_set_constructor().
#define CHECK_VALIDATION_ONLY (context)
Value:
do {                                                                  \
    if (context->validation_only) goto error_exit;                      \
  } while (0)
Definition at line 144 of file load_sa_loader.cpp.
Referenced by ldr_act_class_attr(), ldr_act_init_context(), and ldr_act_meth().
#define FILTER_OUT_ERR_INTERNAL (err, expr) (err = ((expr) == NO_ERROR ? NO_ERROR : er_filter_errid(false)))
Definition at line 79 of file load_sa_loader.cpp.
#define GET_DOMAIN (context, domain)
Value:
do {                                                         \
          if (context->collection == NULL && context->valid)         \
            domain = context->attrs[context->next_attr].att->domain; \
          else                                                       \
            domain = context->set_domain;                            \
         } while (0)
Definition at line 149 of file load_sa_loader.cpp.
Referenced by check_class_domain(), check_object_domain(), ldr_act_class_attr(), ldr_bstr_elem(), ldr_double_elem(), ldr_float_elem(), ldr_real_db_double(), ldr_real_db_float(), and ldr_xstr_elem().
#define LDR_ARG_GROW_SIZE 128
Definition at line 471 of file load_sa_loader.cpp.
Referenced by add_argument().
#define LDR_LOCKHINT_COUNT 1
Definition at line 342 of file load_sa_loader.cpp.
#define LDR_MOP_TEMPOID_MAPS_PRESIZE 1000
Definition at line 470 of file load_sa_loader.cpp.
Referenced by ldr_add_mop_tempoid_map(), and ldr_mop_tempoid_maps_init().
#define MAX_DIGITS_FOR_BIGINT 19
Definition at line 448 of file load_sa_loader.cpp.
Referenced by ldr_int_db_bigint(), and ldr_int_elem().
#define MAX_DIGITS_FOR_INT 10
Definition at line 450 of file load_sa_loader.cpp.
Referenced by ldr_int_db_int(), and ldr_int_elem().
#define MAX_DIGITS_FOR_SHORT 5
Definition at line 451 of file load_sa_loader.cpp.
Referenced by ldr_int_db_short().
#define PARSE_ELO_STR (str, new_len)
Value:
do                                            \
  {                                           \
    if (str[0] == '\"')                       \
      str++;                                  \
    new_len = (int) strlen (str);                   \
    if (new_len && str[new_len-1] == '\"')   \
      new_len--;                              \
  }                                           \
while (0)
Definition at line 455 of file load_sa_loader.cpp.
Referenced by ldr_elo_ext_db_elo(), and ldr_elo_ext_elem().
#define RETURN_IF_NOT_VALID (context)
Value:
do {                                                                  \
    if (!context->valid) return;                                        \
  } while (0)
Definition at line 134 of file load_sa_loader.cpp.
Referenced by ldr_act_add_attr(), ldr_act_attr(), ldr_act_class_attr(), ldr_act_elem(), ldr_act_meth(), ldr_act_restrict_attributes(), ldr_act_set_instance_id(), ldr_act_set_ref_class(), and ldr_act_set_ref_class_id().
#define RETURN_IF_NOT_VALID_WITH (context, ret)
Value:
do {                                                                  \
    if (!context->valid) return (ret);                                  \
  } while (0)
Definition at line 139 of file load_sa_loader.cpp.
Referenced by ldr_act_add_class_all_attrs(), ldr_act_check_missing_non_null_attrs(), and ldr_act_get_ref_class().
#define ROUND (x) (int)((x) > 0 ? ((x) + .5) : ((x) - .5))
Definition at line 453 of file load_sa_loader.cpp.
Referenced by ldr_int_db_int(), and ldr_int_db_short().
Typedef Documentation
typedef struct LDR_ATTDESC LDR_ATTDESC
typedef struct ldr_context LDR_CONTEXT
Definition at line 171 of file load_sa_loader.cpp.
typedef int(* LDR_ELEM) (LDR_CONTEXT *, const char *, size_t, DB_VALUE *)
Definition at line 177 of file load_sa_loader.cpp.
typedef struct ldr_mop_tempoid_map LDR_MOP_TEMPOID_MAP
typedef struct ldr_mop_tempoid_maps LDR_MOP_TEMPOID_MAPS
typedef void(* LDR_POST_COMMIT_HANDLER) (int64_t)
Definition at line 173 of file load_sa_loader.cpp.
typedef void(* LDR_POST_INTERRUPT_HANDLER) (int64_t)
Definition at line 174 of file load_sa_loader.cpp.
typedef int(* LDR_SETTER) (LDR_CONTEXT *, const char *, size_t, SM_ATTRIBUTE *)
Definition at line 176 of file load_sa_loader.cpp.
Function Documentation
static int add_argument (LDR_CONTEXT * context) static
Definition at line 5742 of file load_sa_loader.cpp.
References add_element(), ldr_context::arg_count, LDR_ARG_GROW_SIZE, ldr_context::max_arg, and ldr_context::method_args.
Referenced by ldr_act_add_argument().
static int add_element (void *** elements, int * count, int * max, int grow) static
Definition at line 5698 of file load_sa_loader.cpp.
References ARG_FILE_LINE, CHECK_PTR, cubregex::count(), ER_ERROR_SEVERITY, ER_LDR_MEMORY_ERROR, er_set(), err, free_and_init, i, NO_ERROR, and NULL.
Referenced by add_argument().
static int check_class_domain (LDR_CONTEXT * context) static
Definition at line 1289 of file load_sa_loader.cpp.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_LDR_CLASS_OBJECT_REFERENCE, er_set(), err, GET_DOMAIN, NO_ERROR, NULL, and tp_Type_object.
Referenced by ldr_class_oid_elem().
static int check_commit (LDR_CONTEXT * context) static
Definition at line 4594 of file load_sa_loader.cpp.
References ldr_context::args, CHECK_CONTEXT_VALIDITY, CHECK_ERR, ldr_context::cls, ldr_context::commit_counter, db_abort_transaction(), db_commit_transaction(), db_error_string(), display_error_line(), err, cubload::driver::get_scanner(), Last_committed_line, ldr_assign_all_perm_oids(), ldr_increment_err_count(), ldr_Jmp_buf_ptr, ldr_Load_interrupted, ldr_post_commit_handler, ldr_post_interrupt_handler, ldr_refresh_attrs(), cubload::LDR_STOP_AND_ABORT_INTERRUPT, LOADDB_MSG_COMMITTING, LOADDB_MSG_INTERRUPTED_ABORT, LOADDB_MSG_INTERRUPTED_COMMIT, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_SET_LOADDB, NO_ERROR, NULL, cubload::load_args::periodic_commit, print_log_msg(), Total_objects, and cubload::load_args::verbose.
Referenced by insert_instance().
static int check_object_domain (LDR_CONTEXT * context, DB_OBJECT * class_, DB_OBJECT ** actual_class) static
Definition at line 1217 of file load_sa_loader.cpp.
References ARG_FILE_LINE, db_object::class_mop, db_get_class_name(), DB_TYPE_OBJECT, ER_ERROR_SEVERITY, ER_LDR_AMBIGUOUS_DOMAIN, ER_LDR_OBJECT_DOMAIN_MISMATCH, er_set(), err, GET_DOMAIN, ldr_attr_name(), ldr_class_name(), NO_ERROR, NULL, tp_domain_select_type(), and tp_Type_object.
Referenced by ldr_oid_elem().
static void clist_final (void) static
Definition at line 1759 of file load_sa_loader.cpp.
References ml_ext_free(), and NULL.
Referenced by ldr_final().
static int clist_init (void) static
Definition at line 1709 of file load_sa_loader.cpp.
References assert, AU_AUTH_CLASS_NAME, AU_PASSWORD_CLASS_NAME, AU_ROOT_CLASS_NAME, AU_USER_CLASS_NAME, db_find_class(), er_errid(), ml_ext_add(), NO_ERROR, and NULL.
Referenced by ldr_init().
static MOP construct_instance (LDR_CONTEXT * context) static
Definition at line 5493 of file load_sa_loader.cpp.
References ldr_context::arg_index, LDR_ATTDESC::att, LDR_ATTDESC::attdesc, ldr_context::attrs, au_fetch_instance(), AU_FETCH_UPDATE, AU_UPDATE, CHECK_ERR, ldr_context::class_pin, ldr_context::cls, ldr_context::constructor, db_get_object(), db_send_argarray(), DB_TYPE_OBJECT, DB_VALUE_TYPE, elem_converter, ER_GENERIC_ERROR, err, sm_method::header, i, LC_FETCH_MVCC_VERSION, ldr_internal_error(), LDR_MAX_ARGS, ldr_context::mobj, sm_component::name, ldr_context::next_attr, NO_ERROR, NULL, ldr_context::obj, ldr_context::obj_pin, LDR_ATTDESC::parser_str, LDR_ATTDESC::parser_str_len, LDR_ATTDESC::parser_type, LDR_ATTDESC::setter, sm_get_descriptor_component(), ws_class_has_object_dependencies(), and ws_pin_instance_and_class().
Referenced by insert_meth_instance().
static void display_error (int adjust) static
Definition at line 1652 of file load_sa_loader.cpp.
References db_error_string(), and display_error_line().
Referenced by cubload::sa_class_installer::check_class(), cubload::sa_object_loader::destroy(), ldr_act_elem(), ldr_act_init_context(), ldr_add_mop_tempoid_map(), ldr_check_date_time_conversion(), ldr_collection_elem(), ldr_elo_ext_elem(), ldr_find_class(), ldr_refresh_attrs(), ldr_reset_context(), cubload::sa_object_loader::process_line(), and cubload::sa_object_loader::start_line().
static void display_error_line (int adjust) static
Definition at line 1619 of file load_sa_loader.cpp.
References cubload::driver::get_scanner(), cubload::driver::get_start_line(), LOADDB_MSG_LINE, MSGCAT_CATALOG_UTILS, msgcat_message(), and MSGCAT_UTIL_SET_LOADDB.
Referenced by check_commit(), display_error(), invalid_class_id_error(), ldr_act_add_class_all_attrs(), ldr_act_elem(), ldr_act_init_context(), ldr_date_time_conversion_error(), ldr_invalid_class_error(), ldr_sys_class_db_generic(), ldr_sys_user_db_generic(), and parse_error().
static int find_instance (LDR_CONTEXT * context, DB_OBJECT * class_, OID * oid, int id) static
Definition at line 4106 of file load_sa_loader.cpp.
References ARG_FILE_LINE, assert, ldr_context::attr_type, ldr_context::attrs, CHECK_ERR, CHECK_PTR, ldr_context::cls, COPY_OID, db_create_internal(), db_get_class_name(), er_errid(), ER_ERROR_SEVERITY, ER_LDR_INTERNAL_REFERENCE, er_set(), err, ldr_context::inst_num, is_internal_class(), ldr_add_mop_tempoid_map(), cubload::LDR_ATTRIBUTE_ANY, ldr_context::next_attr, NO_ERROR, NULL, ldr_context::obj, instance_info::oid, OID_SET_NULL, otable_class_att_ref(), otable_find(), otable_find_class(), otable_reserve(), LDR_ATTDESC::ref_class, and WS_REAL_OID.
Referenced by ldr_oid_elem().
static void idmap_final (void) static
Definition at line 1335 of file load_sa_loader.cpp.
References free_and_init, Id_map_size, and NULL.
Referenced by ldr_final().
static int idmap_grow (int size) static
Definition at line 1351 of file load_sa_loader.cpp.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_LDR_MEMORY_ERROR, er_set(), err, free_and_init, i, Id_map, Id_map_size, NO_ERROR, and NULL.
Referenced by ldr_assign_class_id().
static void idmap_init (void) static
Definition at line 1324 of file load_sa_loader.cpp.
References Id_map_size, and NULL.
Referenced by ldr_init().
static int insert_instance (LDR_CONTEXT * context) static
Definition at line 5411 of file load_sa_loader.cpp.
References ldr_context::args, check_commit(), CHECK_ERR, CHECK_PTR, err, instance_info::flags, ldr_context::inst_count, INST_FLAG_RESERVED, ldr_context::inst_num, ldr_context::inst_total, ldr_add_mop_tempoid_map(), ldr_internal_error(), LOADDB_MSG_INSTANCE_COUNT_EX, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_SET_LOADDB, NO_ERROR, cubload::load_args::no_oid_hint, NULL, ldr_context::obj, otable_find(), otable_insert(), otable_update(), ldr_context::status_count, ldr_context::status_counter, ldr_context::table, class_table::total_inserts, Total_objects, ldr_context::validation_only, cubload::load_args::verbose, and WS_REAL_OID.
Referenced by cubload::sa_object_loader::finish_line().
static int insert_meth_instance (LDR_CONTEXT * context) static
Definition at line 5561 of file load_sa_loader.cpp.
References ARG_FILE_LINE, ldr_context::args, CHECK_ERR, CHECK_PTR, construct_instance(), ldr_context::constructor, er_errid(), ER_ERROR_SEVERITY, ER_GENERIC_ERROR, ER_LDR_FORWARD_CONSTRUCTOR, er_set(), err, instance_info::flags, ldr_context::inst_count, INST_FLAG_RESERVED, ldr_context::inst_num, ldr_context::inst_total, ldr_add_mop_tempoid_map(), ldr_internal_error(), LOADDB_MSG_INSTANCE_COUNT_EX, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_SET_LOADDB, NO_ERROR, NULL, otable_find(), otable_insert(), ldr_context::status_count, ldr_context::status_counter, ldr_context::table, Total_objects, ldr_context::validation_only, cubload::load_args::verbose, WS_OID, and ws_release_instance().
Referenced by cubload::sa_object_loader::finish_line().
static void invalid_class_id_error (LDR_CONTEXT * context, int id) static
Definition at line 5831 of file load_sa_loader.cpp.
References CHECK_CONTEXT_VALIDITY, display_error_line(), ldr_attr_name(), ldr_class_name(), LOADDB_MSG_UNKNOWN_CLASS_ID, MSGCAT_CATALOG_UTILS, msgcat_message(), and MSGCAT_UTIL_SET_LOADDB.
Referenced by ldr_act_set_ref_class_id().
static int is_internal_class (DB_OBJECT * class_) static
Definition at line 1771 of file load_sa_loader.cpp.
References ml_find().
Referenced by find_instance(), and ldr_act_init_context().
static void ldr_abort (void) static
Definition at line 6489 of file load_sa_loader.cpp.
References db_abort_transaction(), ldr_Jmp_buf_ptr, ldr_post_interrupt_handler, and NULL.
Referenced by cubload::sa_object_loader::finish_line(), ldr_act_add_argument(), ldr_act_add_attr(), ldr_act_add_class_all_attrs(), ldr_act_check_missing_non_null_attrs(), ldr_act_init_context(), ldr_act_set_constructor(), ldr_elo_ext_db_elo(), ldr_finish_context(), ldr_internal_error(), and cubload::sa_object_loader::process_line().
static int ldr_act_add_argument (LDR_CONTEXT * context, const char * name) static
Definition at line 5764 of file load_sa_loader.cpp.
References add_argument(), ldr_context::arg_count, ARG_FILE_LINE, sm_method_signature::args, CHECK_CONTEXT_VALIDITY, CHECK_ERR, CHECK_SKIP_WITH, classobj_find_method_arg(), ldr_context::constructor, ER_ERROR_SEVERITY, ER_LDR_MEMORY_ERROR, ER_LDR_UNEXPECTED_ARGUMENT, er_set(), err, ldr_abort(), ldr_act_add_attr(), ldr_internal_error(), ldr_context::method_args, NO_ERROR, NULL, sm_method_signature::num_args, sm_method::signatures, strlen, ldr_context::valid, and ldr_context::validation_only.
Referenced by cubload::sa_class_installer::install_class().
static void ldr_act_add_attr (LDR_CONTEXT * context, const char * attr_name, size_t len) static
Definition at line 4995 of file load_sa_loader.cpp.
References ldr_context::arg_count, ARG_FILE_LINE, LDR_ATTDESC::att, LDR_ATTDESC::attdesc, ldr_context::attr_type, ldr_context::attrs, CHECK_CONTEXT_VALIDITY, CHECK_ERR, CHECK_PTR, CHECK_SKIP, ldr_context::cls, LDR_ATTDESC::collection_domain, ldr_context::constructor, db_get_attribute_descriptor(), DB_TYPE_BIGINT, DB_TYPE_BIT, DB_TYPE_BLOB, DB_TYPE_CHAR, DB_TYPE_CLOB, DB_TYPE_DATE, DB_TYPE_DATETIME, DB_TYPE_DATETIMELTZ, DB_TYPE_DATETIMETZ, DB_TYPE_DOUBLE, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_JSON, DB_TYPE_MONETARY, DB_TYPE_MULTISET, DB_TYPE_NCHAR, DB_TYPE_NUMERIC, DB_TYPE_OBJECT, DB_TYPE_SEQUENCE, DB_TYPE_SET, DB_TYPE_SHORT, DB_TYPE_TIME, DB_TYPE_TIMESTAMP, DB_TYPE_TIMESTAMPLTZ, DB_TYPE_TIMESTAMPTZ, DB_TYPE_VARBIT, DB_TYPE_VARCHAR, DB_TYPE_VARNCHAR, DB_TYPE_VOBJ, sm_attribute::domain, ER_ERROR_SEVERITY, ER_LDR_INVALID_CLASS_ATTR, ER_LDR_MEMORY_ERROR, ER_LDR_UNEXPECTED_ARGUMENT, er_set(), err, free_and_init, sm_attribute::header, i, ID_CLASS_ATTRIBUTE, ID_SHARED_ATTRIBUTE, ldr_abort(), ldr_attr_name(), cubload::LDR_ATTRIBUTE_ANY, cubload::LDR_ATTRIBUTE_CLASS, cubload::LDR_ATTRIBUTE_SHARED, cubload::LDR_BSTR, ldr_bstr_db_varbit(), ldr_class_name(), cubload::LDR_CLASS_OID, ldr_class_oid_db_object(), cubload::LDR_COLLECTION, ldr_collection_db_collection(), cubload::LDR_DATE, ldr_date_db_date(), cubload::LDR_DATETIME, ldr_datetime_db_datetime(), cubload::LDR_DATETIMELTZ, ldr_datetimeltz_db_datetimeltz(), cubload::LDR_DATETIMETZ, ldr_datetimetz_db_datetimetz(), cubload::LDR_DOUBLE, cubload::LDR_ELO_EXT, ldr_elo_ext_db_elo(), cubload::LDR_ELO_INT, ldr_elo_int_db_elo(), cubload::LDR_FLOAT, ldr_ignore(), cubload::LDR_INT, ldr_int_db_bigint(), ldr_int_db_generic(), ldr_int_db_int(), ldr_int_db_short(), ldr_json_db_json(), ldr_mismatch(), cubload::LDR_MONETARY, ldr_monetary_db_monetary(), cubload::LDR_NSTR, ldr_nstr_db_varnchar(), cubload::LDR_NULL, ldr_null_db_generic(), cubload::LDR_NUMERIC, ldr_numeric_db_generic(), cubload::LDR_OID, ldr_oid_db_object(), ldr_real_db_double(), ldr_real_db_float(), ldr_real_db_generic(), cubload::LDR_STR, ldr_str_db_char(), ldr_str_db_generic(), ldr_str_db_varchar(), cubload::LDR_SYS_CLASS, ldr_sys_class_db_generic(), cubload::LDR_SYS_USER, ldr_sys_user_db_generic(), cubload::LDR_TIME, ldr_time_db_time(), cubload::LDR_TIMESTAMP, ldr_timestamp_db_timestamp(), cubload::LDR_TIMESTAMPLTZ, ldr_timestampltz_db_timestampltz(), cubload::LDR_TIMESTAMPTZ, ldr_timestamptz_db_timestamptz(), cubload::LDR_XSTR, ldr_xstr_db_varbit(), sm_component::name_space, NO_ERROR, NULL, sm_method_signature::num_args, ldr_context::num_attrs, NUM_LDR_TYPES, LDR_ATTDESC::parser_buf_len, LDR_ATTDESC::parser_str, LDR_ATTDESC::parser_str_len, LDR_ATTDESC::ref_class, RETURN_IF_NOT_VALID, select_set_domain(), LDR_ATTDESC::setter, sm_method::signatures, sm_get_descriptor_component(), TP_DOMAIN_TYPE, TP_IS_SET_TYPE, and ldr_context::validation_only.
Referenced by cubload::sa_class_installer::install_class(), ldr_act_add_argument(), and ldr_act_add_class_all_attrs().
static int ldr_act_add_class_all_attrs (const char * class_name) static
Definition at line 6596 of file load_sa_loader.cpp.
References assert, au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_CONTEXT_VALIDITY, CHECK_ERR, ldr_context::cls, display_error_line(), ER_FAILED, er_filter_errid(), err, ldr_abort(), ldr_act_add_attr(), ldr_find_class(), LOADDB_MSG_UNKNOWN_CLASS, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_SET_LOADDB, NO_ERROR, NULL, sm_class::ordered_attributes, RETURN_IF_NOT_VALID_WITH, strlen, and ldr_context::validation_only.
Referenced by cubload::sa_class_installer::install_class().
static void ldr_act_attr (LDR_CONTEXT * context, const char * str, size_t len, data_type type) static
Definition at line 1797 of file load_sa_loader.cpp.
References ARG_FILE_LINE, LDR_ATTDESC::att, ldr_context::attrs, CHECK_ERR, CHECK_SKIP, ER_ERROR_SEVERITY, ER_LDR_VALUE_OVERFLOW, er_set(), err, ldr_act, ldr_act_elem(), ldr_check_date_time_conversion(), cubload::LDR_COLLECTION, cubload::LDR_DATE, cubload::LDR_DATETIME, cubload::LDR_DATETIMELTZ, cubload::LDR_DATETIMETZ, ldr_increment_err_count(), cubload::LDR_TIME, cubload::LDR_TIMESTAMP, cubload::LDR_TIMESTAMPLTZ, cubload::LDR_TIMESTAMPTZ, ldr_context::next_attr, NO_ERROR, NULL, ldr_context::num_attrs, RETURN_IF_NOT_VALID, LDR_ATTDESC::setter, ldr_context::valid, and ldr_context::validation_only.
Referenced by ldr_collection_db_collection(), ldr_finish_context(), ldr_init_loader(), and cubload::sa_object_loader::process_line().
static int ldr_act_check_missing_non_null_attrs (LDR_CONTEXT * context) static
Definition at line 4906 of file load_sa_loader.cpp.
References ARG_FILE_LINE, LDR_ATTDESC::attdesc, ldr_context::attr_type, sm_class::attributes, ldr_context::attrs, au_fetch_class(), AU_FETCH_READ, AU_SELECT, CHECK_CONTEXT_VALIDITY, CHECK_ERR, CHECK_SKIP_WITH, sm_class::class_attributes, ldr_context::class_name, ldr_context::cls, ER_ERROR_SEVERITY, ER_OBJ_ATTRIBUTE_CANT_BE_NULL, er_set(), err, sm_attribute::flags, sm_attribute::header, i, intl_identifier_casecmp(), ldr_abort(), cubload::LDR_ATTRIBUTE_ANY, cubload::LDR_ATTRIBUTE_CLASS, cubload::LDR_ATTRIBUTE_DEFAULT, cubload::LDR_ATTRIBUTE_SHARED, sm_component::name, sm_descriptor::name, sm_component::name_space, sm_descriptor::name_space, sm_component::next, NO_ERROR, NULL, ldr_context::num_attrs, RETURN_IF_NOT_VALID_WITH, sm_class::shared, SM_ATTFLAG_NON_NULL, and ldr_context::validation_only.
Referenced by cubload::sa_class_installer::install_class().
static void ldr_act_class_attr (LDR_CONTEXT * context, const char * str, size_t len, data_type type) static
Definition at line 2156 of file load_sa_loader.cpp.
References ARG_FILE_LINE, LDR_ATTDESC::att, ldr_context::attrs, CHECK_CONTEXT_VALIDITY, CHECK_ERR, CHECK_PARSE_ERR, CHECK_VALIDATION_ONLY, LDR_ATTDESC::collection_domain, DB_TYPE_OBJECT, db_value_domain_init(), elem_converter, ER_ERROR_SEVERITY, ER_LDR_VALUE_OVERFLOW, ER_OBJ_DOMAIN_CONFLICT, er_set(), err, GET_DOMAIN, sm_attribute::header, ldr_class_attr_db_generic(), cubload::LDR_CLASS_OID, cubload::LDR_COLLECTION, ldr_collection_db_collection(), ldr_increment_err_count(), cubload::LDR_OID, sm_component::name, ldr_context::next_attr, NO_ERROR, NULL, ldr_context::num_attrs, tp_domain::precision, RETURN_IF_NOT_VALID, tp_domain::scale, TP_DOMAIN_TYPE, tp_value_cast(), and ldr_context::valid.
Referenced by ldr_act_restrict_attributes(), and ldr_collection_db_collection().
static void ldr_act_elem (LDR_CONTEXT * context, const char * str, size_t len, data_type type) static
Definition at line 1880 of file load_sa_loader.cpp.
References ARG_FILE_LINE, CHECK_ERR, ldr_context::collection, db_get_type_name(), db_value_type(), display_error(), display_error_line(), elem_converter, ER_ERROR_SEVERITY, ER_LDR_NESTED_SET, er_set(), ER_SET_DOMAIN_CONFLICT, err, ldr_attr_name(), ldr_check_date_time_conversion(), ldr_class_name(), cubload::LDR_COLLECTION, cubload::LDR_DATE, cubload::LDR_DATETIME, cubload::LDR_DATETIMELTZ, cubload::LDR_DATETIMETZ, ldr_increment_err_count(), cubload::LDR_TIME, cubload::LDR_TIMESTAMP, cubload::LDR_TIMESTAMPLTZ, cubload::LDR_TIMESTAMPTZ, LOADDB_MSG_SET_DOMAIN_ERROR, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_SET_LOADDB, NO_ERROR, RETURN_IF_NOT_VALID, set_add_element(), and ldr_context::validation_only.
Referenced by ldr_act_attr(), and ldr_collection_db_collection().
static DB_OBJECT * ldr_act_get_ref_class (LDR_CONTEXT * context) static
Definition at line 5927 of file load_sa_loader.cpp.
References ldr_context::attrs, ldr_context::next_attr, NULL, LDR_ATTDESC::ref_class, RETURN_IF_NOT_VALID_WITH, and ldr_context::validation_only.
Referenced by ldr_process_object_ref().
static void ldr_act_init_context (LDR_CONTEXT * context, const char * class_name, size_t len) static
Definition at line 4796 of file load_sa_loader.cpp.
References ARG_FILE_LINE, ldr_context::args, CHECK_CONTEXT_VALIDITY, CHECK_ERR, CHECK_SKIP, CHECK_VALIDATION_ONLY, ldr_context::class_name, ldr_context::class_type, ldr_context::cls, display_error(), display_error_line(), er_clear(), ER_ERROR_SEVERITY, ER_LDR_MEMORY_ERROR, ER_LDR_SYSTEM_CLASS, er_set(), err, intl_identifier_lower_string_size(), is_internal_class(), ldr_abort(), ldr_find_class(), ldr_finish_context(), ldr_internal_error(), LOADDB_MSG_CLASS_TITLE, LOADDB_MSG_EXCEED_MAX_LEN, LOADDB_MSG_UNKNOWN_CLASS, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_SET_LOADDB, NO_ERROR, NULL, otable_find_class(), SM_MAX_IDENTIFIER_LENGTH, sm_partitioned_class_type(), ldr_context::table, ldr_context::valid, ldr_context::validation_only, and cubload::load_args::verbose.
Referenced by cubload::sa_class_installer::install_class(), and ldr_init_loader().
static void ldr_act_meth (LDR_CONTEXT * context, const char * str, size_t len, data_type type) static
Definition at line 1949 of file load_sa_loader.cpp.
References ldr_context::arg_count, ARG_FILE_LINE, ldr_context::attrs, CHECK_ERR, CHECK_PTR, CHECK_VALIDATION_ONLY, ER_ERROR_SEVERITY, ER_LDR_MEMORY_ERROR, ER_LDR_UNEXPECTED_ARGUMENT, er_set(), err, free_and_init, ldr_increment_err_count(), ldr_context::next_attr, NO_ERROR, NULL, ldr_context::num_attrs, LDR_ATTDESC::parser_buf_len, LDR_ATTDESC::parser_str, LDR_ATTDESC::parser_str_len, LDR_ATTDESC::parser_type, and RETURN_IF_NOT_VALID.
Referenced by ldr_act_set_constructor().
static void ldr_act_restrict_attributes (LDR_CONTEXT * context, attribute_type type) static
Definition at line 5323 of file load_sa_loader.cpp.
References ldr_context::attr_type, CHECK_SKIP, ldr_act, ldr_act_class_attr(), RETURN_IF_NOT_VALID, and ldr_context::validation_only.
Referenced by cubload::sa_class_installer::install_class().
static int ldr_act_set_constructor (LDR_CONTEXT * context, const char * name) static
Definition at line 5639 of file load_sa_loader.cpp.
References ARG_FILE_LINE, ldr_context::arg_index, CHECK_CONTEXT_VALIDITY, CHECK_ERR, CHECK_SKIP_WITH, ldr_context::cls, ldr_context::constructor, db_get_class_method(), ER_ERROR_SEVERITY, ER_LDR_INVALID_CONSTRUCTOR, er_set(), err, ldr_abort(), ldr_act, ldr_act_meth(), ldr_class_name(), NO_ERROR, NULL, ldr_context::num_attrs, ldr_context::valid, and ldr_context::validation_only.
Referenced by cubload::sa_class_installer::install_class().
static void ldr_act_set_instance_id (LDR_CONTEXT * context, int id) static
Definition at line 5876 of file load_sa_loader.cpp.
References ldr_context::attrs, CHECK_CONTEXT_VALIDITY, CHECK_SKIP, LDR_ATTDESC::instance_id, ldr_context::next_attr, NULL, LDR_ATTDESC::ref_class, RETURN_IF_NOT_VALID, and ldr_context::validation_only.
Referenced by ldr_process_object_ref().
static void ldr_act_set_ref_class (LDR_CONTEXT * context, char * name) static
Definition at line 5847 of file load_sa_loader.cpp.
References ldr_context::attrs, CHECK_SKIP, db_find_class(), ldr_invalid_class_error(), ldr_context::next_attr, NULL, LDR_ATTDESC::ref_class, RETURN_IF_NOT_VALID, and ldr_context::validation_only.
Referenced by ldr_process_object_ref().
static void ldr_act_set_ref_class_id (LDR_CONTEXT * context, int id) static
Definition at line 5905 of file load_sa_loader.cpp.
References ldr_context::attrs, CHECK_SKIP, invalid_class_id_error(), ldr_get_class_from_id(), ldr_context::next_attr, NULL, LDR_ATTDESC::ref_class, RETURN_IF_NOT_VALID, and ldr_context::validation_only.
Referenced by ldr_process_object_ref().
static void ldr_act_set_skip_current_class (char * class_name, size_t size) static
Definition at line 6505 of file load_sa_loader.cpp.
References ldr_is_ignore_class(), print_log_msg(), skip_current_class, and ldr_context::validation_only.
Referenced by cubload::sa_class_installer::install_class().
static int ldr_add_mop_tempoid_map (MOP mop, CLASS_TABLE * table, int id) static
Definition at line 3950 of file load_sa_loader.cpp.
References ARG_FILE_LINE, ldr_mop_tempoid_maps::count, display_error(), ER_ERROR_SEVERITY, ER_LDR_MEMORY_ERROR, er_set(), err, free_and_init, ldr_mop_tempoid_map::id, ldr_mop_tempoid_maps::index, ldr_mop_tempoid_maps_init(), LDR_MOP_TEMPOID_MAPS_PRESIZE, ldr_mop_tempoid_map::mop, ldr_mop_tempoid_maps::mop_tempoid_maps, NO_ERROR, NULL, ldr_mop_tempoid_maps::size, and ldr_mop_tempoid_map::table.
Referenced by find_instance(), insert_instance(), and insert_meth_instance().
static int ldr_assign_all_perm_oids (void) static
Definition at line 4008 of file load_sa_loader.cpp.
References ldr_context::args, assert, CHECK_ERR, CHECK_PTR, COPY_OID, ldr_mop_tempoid_maps::count, cubregex::count(), er_errid(), err, i, ldr_mop_tempoid_map::id, ldr_mop_tempoid_maps::index, locator_add_oidset_object(), locator_assign_oidset(), locator_clear_oid_set(), locator_free_oid_set(), locator_make_oid_set(), ldr_mop_tempoid_map::mop, ldr_mop_tempoid_maps::mop_tempoid_maps, NO_ERROR, cubload::load_args::no_oid_hint, NULL, instance_info::oid, OID_BATCH_SIZE, OID_ISTEMP, otable_find(), ldr_mop_tempoid_map::table, lc_oidset::total_oids, and WS_REAL_OID.
Referenced by check_commit(), cubload::sa_object_loader::finish_line(), and ldr_finish_context().
static int ldr_assign_class_id (DB_OBJECT * class_, int id) static
Definition at line 1395 of file load_sa_loader.cpp.
References err, idmap_grow(), and NO_ERROR.
Referenced by cubload::sa_class_installer::check_class().
static const char * ldr_attr_name (LDR_CONTEXT * context) static
Definition at line 1117 of file load_sa_loader.cpp.
References LDR_ATTDESC::att, ldr_context::attrs, sm_attribute::header, sm_component::name, ldr_context::next_attr, NULL, ldr_context::num_attrs, and ldr_context::valid.
Referenced by check_object_domain(), invalid_class_id_error(), ldr_act_add_attr(), ldr_act_elem(), ldr_invalid_class_error(), ldr_xstr_elem(), parse_error(), and select_set_domain().
static int ldr_bstr_db_varbit (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 2790 of file load_sa_loader.cpp.
References CHECK_ERR, db_value_clear(), err, ldr_bstr_elem(), and ldr_generic().
Referenced by ldr_act_add_attr().
static int ldr_bstr_elem (LDR_CONTEXT * context, const char * str, size_t len, DB_VALUE * val) static
Definition at line 2732 of file load_sa_loader.cpp.
References ARG_FILE_LINE, LDR_ATTDESC::att, ldr_context::attrs, CHECK_PARSE_ERR, CHECK_PTR, DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_make_varbit(), db_private_alloc, DB_TYPE_BIT, db_value_clear(), db_value_domain_init(), ER_ERROR_SEVERITY, ER_OBJ_DOMAIN_CONFLICT, er_set(), err, GET_DOMAIN, sm_attribute::header, sm_component::name, db_value::need_clear, ldr_context::next_attr, NO_ERROR, NULL, tp_domain::precision, qstr_bit_to_bin(), tp_domain::scale, tp_domain_resolve_value(), TP_DOMAIN_TYPE, TP_FLOATING_PRECISION_VALUE, and tp_value_cast().
Referenced by ldr_bstr_db_varbit(), and ldr_init_loader().
static int ldr_check_date_time_conversion (const char * str, data_type type) static
Definition at line 3560 of file load_sa_loader.cpp.
References db_string_to_date(), db_string_to_datetime(), db_string_to_datetimeltz(), db_string_to_datetimetz(), db_string_to_time(), db_string_to_timestamp(), db_string_to_timestampltz(), db_string_to_timestamptz(), DB_TYPE_DATE, DB_TYPE_DATETIME, DB_TYPE_DATETIMELTZ, DB_TYPE_DATETIMETZ, DB_TYPE_NULL, DB_TYPE_TIME, DB_TYPE_TIMESTAMP, DB_TYPE_TIMESTAMPLTZ, DB_TYPE_TIMESTAMPTZ, display_error(), ER_DATE_CONVERSION, err, cubload::LDR_DATE, ldr_date_time_conversion_error(), cubload::LDR_DATETIME, cubload::LDR_DATETIMELTZ, cubload::LDR_DATETIMETZ, cubload::LDR_TIME, cubload::LDR_TIMESTAMP, cubload::LDR_TIMESTAMPLTZ, cubload::LDR_TIMESTAMPTZ, and NO_ERROR.
Referenced by ldr_act_attr(), and ldr_act_elem().
static int ldr_class_attr_db_generic (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att, DB_VALUE * val) static
Definition at line 2126 of file load_sa_loader.cpp.
References ldr_context::attr_type, CHECK_ERR, ldr_context::cls, db_change_default(), err, sm_attribute::header, ID_CLASS_ATTRIBUTE, ID_SHARED_ATTRIBUTE, cubload::LDR_ATTRIBUTE_DEFAULT, sm_component::name, sm_component::name_space, NO_ERROR, obj_set(), and obj_set_shared().
Referenced by ldr_act_class_attr(), and ldr_collection_db_collection().
static const char * ldr_class_name (LDR_CONTEXT * context) static
Definition at line 1093 of file load_sa_loader.cpp.
References ldr_context::cls, db_get_class_name(), and NULL.
Referenced by check_object_domain(), invalid_class_id_error(), ldr_act_add_attr(), ldr_act_elem(), ldr_act_set_constructor(), ldr_finish_context(), ldr_invalid_class_error(), parse_error(), and select_set_domain().
static int ldr_class_oid_db_object (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 4221 of file load_sa_loader.cpp.
References CHECK_ERR, sm_attribute::domain, err, sm_attribute::header, ID_SHARED_ATTRIBUTE, ldr_class_oid_elem(), ldr_generic(), ldr_increment_err_count(), ldr_context::mobj, sm_component::name_space, NO_ERROR, OBJ_SET_BOUND_BIT, sm_attribute::offset, pr_type::setmem(), sm_attribute::storage_order, and tp_domain::type.
Referenced by ldr_act_add_attr().
static int ldr_class_oid_elem (LDR_CONTEXT * context, const char * str, size_t len, DB_VALUE * val) static
Definition at line 4195 of file load_sa_loader.cpp.
References ldr_context::attrs, check_class_domain(), CHECK_ERR, db_make_object(), err, ldr_internal_error(), ldr_context::next_attr, NO_ERROR, NULL, and LDR_ATTDESC::ref_class.
Referenced by ldr_class_oid_db_object(), and ldr_init_loader().
static void ldr_clear_and_free_context (LDR_CONTEXT * context) static
Definition at line 1540 of file load_sa_loader.cpp.
References ldr_context::arg_count, LDR_ATTDESC::attdesc, ldr_context::attrs, ldr_context::class_name, db_free_attribute_descriptor(), free_and_init, i, ldr_clear_context(), ldr_context::method_args, NULL, ldr_context::num_attrs, and LDR_ATTDESC::parser_str.
Referenced by ldr_destroy(), ldr_finish_context(), and ldr_internal_error().
static void ldr_clear_context (LDR_CONTEXT * context) static
Definition at line 1475 of file load_sa_loader.cpp.
References ldr_context::arg_count, ldr_context::arg_index, ldr_context::args, ldr_context::attr_type, ldr_context::attrs, ldr_context::class_name, ldr_context::class_pin, ldr_context::class_type, ldr_context::cls, ldr_context::collection, ldr_context::constructor, DB_NOT_PARTITIONED_CLASS, ldr_context::flush_interval, ldr_context::id_class, ldr_context::inst_count, ldr_context::inst_num, ldr_context::inst_total, ldr_context::instance_started, cubload::LDR_ATTRIBUTE_ANY, ldr_clear_err_count(), ldr_context::max_arg, ldr_context::method_args, ldr_context::mobj, ldr_context::next_attr, NULL, ldr_context::num_attrs, ldr_context::obj, ldr_context::obj_pin, cubload::load_args::periodic_commit, prm_get_integer_value(), PRM_ID_LOADDB_FLUSH_INTERVAL, ldr_context::set_domain, ldr_context::table, and ldr_context::valid.
Referenced by ldr_clear_and_free_context(), ldr_init_loader(), and ldr_start().
static void ldr_clear_err_count (LDR_CONTEXT * context) static
Definition at line 1063 of file load_sa_loader.cpp.
References ldr_context::err_count.
Referenced by ldr_clear_context(), and ldr_reset_context().
static void ldr_clear_err_total (LDR_CONTEXT * context) static
Definition at line 1077 of file load_sa_loader.cpp.
References ldr_context::err_total.
Referenced by ldr_init_loader().
static int ldr_collection_db_collection (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 4422 of file load_sa_loader.cpp.
References assert, LDR_ATTDESC::att, ldr_context::attr_type, ldr_context::attrs, ldr_context::collection, LDR_ATTDESC::collection_domain, db_col_create(), db_make_collection(), sm_attribute::domain, er_errid(), err, ldr_act, ldr_act_attr(), ldr_act_class_attr(), ldr_act_elem(), cubload::LDR_ATTRIBUTE_ANY, ldr_class_attr_db_generic(), ldr_generic(), ldr_context::next_attr, NO_ERROR, NULL, ldr_context::set_domain, tp_domain::setdomain, and TP_DOMAIN_TYPE.
Referenced by ldr_act_add_attr(), and ldr_act_class_attr().
static int ldr_collection_elem (LDR_CONTEXT * context, const char * str, size_t len, DB_VALUE * val) static
Definition at line 4404 of file load_sa_loader.cpp.
References ARG_FILE_LINE, display_error(), ER_ERROR_SEVERITY, ER_LDR_NESTED_SET, er_set(), err, and ldr_null_elem().
Referenced by ldr_init_loader().
static int ldr_date_db_date (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 3206 of file load_sa_loader.cpp.
References CHECK_ERR, sm_attribute::domain, err, ldr_date_elem(), ldr_context::mobj, OBJ_SET_BOUND_BIT, sm_attribute::offset, pr_type::setmem(), sm_attribute::storage_order, and tp_domain::type.
Referenced by ldr_act_add_attr().
static int ldr_date_elem (LDR_CONTEXT * context, const char * str, size_t len, DB_VALUE * val) static
Definition at line 3186 of file load_sa_loader.cpp.
References CHECK_PARSE_ERR, db_value::data, db_data::date, db_string_to_date(), DB_TYPE_DATE, db_value::domain, err, and NO_ERROR.
Referenced by ldr_date_db_date(), and ldr_init_loader().
static void ldr_date_time_conversion_error (const char * token, DB_TYPE type) static
Definition at line 3544 of file load_sa_loader.cpp.
References db_get_type_name(), display_error_line(), LOADDB_MSG_CONVERSION_ERROR, MSGCAT_CATALOG_UTILS, msgcat_message(), and MSGCAT_UTIL_SET_LOADDB.
Referenced by ldr_check_date_time_conversion().
static int ldr_datetime_db_datetime (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 3430 of file load_sa_loader.cpp.
References CHECK_ERR, sm_attribute::domain, err, ldr_datetime_elem(), ldr_context::mobj, OBJ_SET_BOUND_BIT, sm_attribute::offset, pr_type::setmem(), sm_attribute::storage_order, and tp_domain::type.
Referenced by ldr_act_add_attr().
static int ldr_datetime_elem (LDR_CONTEXT * context, const char * str, size_t len, DB_VALUE * val) static
Definition at line 3410 of file load_sa_loader.cpp.
References CHECK_PARSE_ERR, db_value::data, db_data::datetime, db_string_to_datetime(), DB_TYPE_DATETIME, db_value::domain, err, and NO_ERROR.
Referenced by ldr_datetime_db_datetime(), and ldr_init_loader().
static int ldr_datetimeltz_db_datetimeltz (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 3522 of file load_sa_loader.cpp.
References CHECK_ERR, sm_attribute::domain, err, ldr_datetimeltz_elem(), ldr_context::mobj, OBJ_SET_BOUND_BIT, sm_attribute::offset, pr_type::setmem(), sm_attribute::storage_order, and tp_domain::type.
Referenced by ldr_act_add_attr().
static int ldr_datetimeltz_elem (LDR_CONTEXT * context, const char * str, size_t len, DB_VALUE * val) static
Definition at line 3477 of file load_sa_loader.cpp.
References CHECK_PARSE_ERR, db_value::data, db_data::datetime, db_string_to_datetimeltz(), DB_TYPE_DATETIMELTZ, db_value::domain, err, and NO_ERROR.
Referenced by ldr_datetimeltz_db_datetimeltz(), and ldr_init_loader().
static int ldr_datetimetz_db_datetimetz (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 3498 of file load_sa_loader.cpp.
References CHECK_ERR, sm_attribute::domain, err, ldr_datetimetz_elem(), ldr_context::mobj, OBJ_SET_BOUND_BIT, sm_attribute::offset, pr_type::setmem(), sm_attribute::storage_order, and tp_domain::type.
Referenced by ldr_act_add_attr().
static int ldr_datetimetz_elem (LDR_CONTEXT * context, const char * str, size_t len, DB_VALUE * val) static
Definition at line 3454 of file load_sa_loader.cpp.
References CHECK_PARSE_ERR, db_value::data, db_data::datetimetz, db_string_to_datetimetz(), DB_TYPE_DATETIMETZ, db_value::domain, err, and NO_ERROR.
Referenced by ldr_datetimetz_db_datetimetz(), and ldr_init_loader().
static int ldr_destroy (LDR_CONTEXT * context, int err) static
Definition at line 5383 of file load_sa_loader.cpp.
References ldr_context::err_total, ldr_clear_and_free_context(), ldr_finish_context(), NO_ERROR, update_default_instances_stats(), and ldr_context::validation_only.
Referenced by cubload::sa_object_loader::destroy(), and ldr_final().
static int ldr_double_elem (LDR_CONTEXT * context, const char * str, size_t len, DB_VALUE * val) static
Definition at line 2993 of file load_sa_loader.cpp.
References ARG_FILE_LINE, CHECK_PARSE_ERR, db_data::d, db_value::data, db_get_type_name(), db_value::domain, ER_ERROR_SEVERITY, ER_IT_DATA_OVERFLOW, er_set(), err, GET_DOMAIN, NO_ERROR, OR_CHECK_DOUBLE_OVERFLOW, and TP_DOMAIN_TYPE.
Referenced by ldr_init_loader(), and ldr_real_db_generic().
static int ldr_elo_ext_db_elo (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 3816 of file load_sa_loader.cpp.
References ARG_FILE_LINE, CHECK_CONTEXT_VALIDITY, CHECK_ERR, db_make_null(), db_value_clear(), sm_attribute::domain, ER_ERROR_SEVERITY, ER_LDR_MEMORY_ERROR, er_set(), err, ldr_abort(), ldr_elo_ext_elem(), ldr_context::mobj, NO_ERROR, NULL, sm_attribute::offset, PARSE_ELO_STR, pr_type::setmem(), and tp_domain::type.
Referenced by ldr_act_add_attr().
static int ldr_elo_ext_elem (LDR_CONTEXT * context, const char * str, size_t len, DB_VALUE * val) static
Definition at line 3672 of file load_sa_loader.cpp.
References ARG_FILE_LINE, assert, db_make_elo(), db_private_alloc, db_private_free_and_init, DB_TYPE_BLOB, DB_TYPE_CLOB, display_error(), db_value::domain, ELO_FBO, elo_init_structure(), ER_ERROR_SEVERITY, ER_LDR_ELO_INPUT_FILE, ER_LDR_INVALID_STATE, er_set(), err, ldr_increment_err_count(), db_elo::locator, db_elo::meta_data, db_value::need_clear, NO_ERROR, NULL, PARSE_ELO_STR, db_elo::size, str_to_int64(), db_elo::type, and ldr_context::valid.
Referenced by ldr_elo_ext_db_elo(), and ldr_init_loader().
static int ldr_elo_int_db_elo (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 3656 of file load_sa_loader.cpp.
References assert, and ER_FAILED.
Referenced by ldr_act_add_attr().
static int ldr_elo_int_elem (LDR_CONTEXT * context, const char * str, size_t len, DB_VALUE * val) static
Definition at line 3640 of file load_sa_loader.cpp.
References assert, and ER_FAILED.
Referenced by ldr_init_loader().
static int ldr_final (void) static
Definition at line 6167 of file load_sa_loader.cpp.
References clist_final(), idmap_final(), ldr_Current_context, ldr_destroy(), ldr_mop_tempoid_maps_final(), NO_ERROR, and otable_final().
Referenced by ldr_sa_load().
static DB_OBJECT * ldr_find_class (const char * class_name) static
Definition at line 1418 of file load_sa_loader.cpp.
References ARG_FILE_LINE, db_find_class(), display_error(), ER_ERROR_SEVERITY, ER_GENERIC_ERROR, er_set(), LC_CLASSNAME_EXIST, ldr_Hint_class_names, ldr_Hint_flags, ldr_Hint_locks, ldr_Hint_subclasses, locator_lockhint_classes(), NULL, NULL_LOCK, sm_downcase_name(), and SM_MAX_IDENTIFIER_LENGTH.
Referenced by cubload::sa_class_installer::check_class(), ldr_act_add_class_all_attrs(), ldr_act_init_context(), and ldr_refresh_attrs().
static int ldr_finish_context (LDR_CONTEXT * context) static
Definition at line 4712 of file load_sa_loader.cpp.
References ldr_context::args, ldr_context::attr_type, CHECK_CONTEXT_VALIDITY, CHECK_ERR, ldr_context::class_name, ldr_context::cls, envvar_get(), er_errid(), er_filter_errid(), err, ldr_context::err_total, ldr_context::flush_total, ldr_context::inst_total, ldr_abort(), ldr_act, ldr_act_attr(), ldr_assign_all_perm_oids(), cubload::LDR_ATTRIBUTE_ANY, ldr_class_name(), ldr_clear_and_free_context(), ldr_flush(), LOADDB_MSG_INSTANCE_COUNT, locator_flush_class(), MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_SET_LOADDB, NO_ERROR, NULL, ldr_context::valid, ldr_context::validation_only, and cubload::load_args::verbose.
Referenced by ldr_act_init_context(), and ldr_destroy().
static int ldr_float_elem (LDR_CONTEXT * context, const char * str, size_t len, DB_VALUE * val) static
Definition at line 3031 of file load_sa_loader.cpp.
References ARG_FILE_LINE, CHECK_PARSE_ERR, db_value::data, db_get_type_name(), db_value::domain, ER_ERROR_SEVERITY, ER_IT_DATA_OVERFLOW, er_set(), err, db_data::f, GET_DOMAIN, NO_ERROR, OR_CHECK_FLOAT_OVERFLOW, and TP_DOMAIN_TYPE.
Referenced by ldr_init_loader().
static void ldr_flush (LDR_CONTEXT * context) static
Definition at line 4571 of file load_sa_loader.cpp.
References ldr_context::cls, ldr_context::flush_total, ldr_context::inst_count, and ws_intern_instances().
Referenced by cubload::sa_object_loader::finish_line(), and ldr_finish_context().
static int ldr_generic (LDR_CONTEXT * context, DB_VALUE * value) static
Definition at line 2053 of file load_sa_loader.cpp.
References LDR_ATTDESC::attdesc, ldr_context::attrs, CHECK_ERR, err, ldr_context::next_attr, ldr_context::obj, and obj_desc_set().
Referenced by ldr_bstr_db_varbit(), ldr_class_oid_db_object(), ldr_collection_db_collection(), ldr_int_db_generic(), ldr_json_db_json(), ldr_nstr_db_varnchar(), ldr_numeric_db_generic(), ldr_real_db_generic(), ldr_str_db_generic(), and ldr_xstr_db_varbit().
static DB_OBJECT * ldr_get_class_from_id (int id) static
Definition at line 1456 of file load_sa_loader.cpp.
References Id_map_size, and NULL.
Referenced by ldr_act_set_ref_class_id().
static void ldr_get_num_of_inserted_objects (int64_t num_objects) static
Definition at line 6710 of file load_sa_loader.cpp.
References Total_objects_loaded.
Referenced by ldr_register_post_interrupt_handler().
static int ldr_ignore (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 2035 of file load_sa_loader.cpp.
References ER_OBJ_DOMAIN_CONFLICT.
Referenced by ldr_act_add_attr().
static void ldr_increment_err_count (LDR_CONTEXT * context, int i) static
Definition at line 1049 of file load_sa_loader.cpp.
References ldr_context::err_count, and i.
Referenced by check_commit(), cubload::sa_object_loader::finish_line(), ldr_act_attr(), ldr_act_class_attr(), ldr_act_elem(), ldr_act_meth(), ldr_class_oid_db_object(), ldr_elo_ext_elem(), ldr_oid_elem(), ldr_sys_class_db_generic(), and ldr_sys_user_db_generic().
void ldr_increment_err_total ()
Definition at line 1024 of file load_sa_loader.cpp.
References ldr_context::err_total.
Referenced by cubload::error_handler::log_error_message().
void ldr_increment_fails ()
Definition at line 1037 of file load_sa_loader.cpp.
References Total_fails.
Referenced by cubload::error_handler::log_error_message().
static int ldr_init (load_args * args) static
Definition at line 6061 of file load_sa_loader.cpp.
References ldr_context::args, assert, clist_init(), er_errid(), idmap_init(), ldr_Context, ldr_Current_context, ldr_init_loader(), NO_ERROR, obt_enable_unique_checking(), otable_init(), ldr_context::status_count, ldr_context::status_counter, and ldr_context::validation_only.
Referenced by ldr_sa_load().
static void ldr_init_driver () static
Definition at line 6185 of file load_sa_loader.cpp.
References cubthread::get_entry(), cubload::driver::initialize(), ldr_Driver, cubthread::entry::m_loaddb_driver, and NULL.
Referenced by ldr_sa_load().
static int ldr_init_loader (LDR_CONTEXT * context) static
Definition at line 5947 of file load_sa_loader.cpp.
References db_datetimetz::datetime, db_datetime_encode(), DB_FETCH_CLREAD_INSTWRITE, db_make_bigint(), db_make_bit(), db_make_char(), db_make_date(), db_make_datetime(), db_make_datetimeltz(), db_make_datetimetz(), db_make_double(), db_make_elo(), db_make_float(), db_make_int(), db_make_json(), db_make_short(), db_make_time(), db_make_timestamp(), db_make_timestampltz(), db_make_timestamptz(), db_make_varchar(), DB_TYPE_BLOB, DB_TYPE_CLOB, elem_converter, err, ldr_context::flush_total, i, LANG_SYS_CODESET, LANG_SYS_COLLATION, LC_CLASS, LC_FETCH_CURRENT_VERSION, LC_PREF_FLAG_LOCK, ldr_act, ldr_act_attr(), ldr_act_init_context(), cubload::LDR_BSTR, ldr_bstr_elem(), cubload::LDR_CLASS_OID, ldr_class_oid_elem(), ldr_clear_context(), ldr_clear_err_total(), cubload::LDR_COLLECTION, ldr_collection_elem(), cubload::LDR_DATE, ldr_date_elem(), cubload::LDR_DATETIME, ldr_datetime_elem(), cubload::LDR_DATETIMELTZ, ldr_datetimeltz_elem(), cubload::LDR_DATETIMETZ, ldr_datetimetz_elem(), cubload::LDR_DOUBLE, ldr_double_elem(), cubload::LDR_ELO_EXT, ldr_elo_ext_elem(), cubload::LDR_ELO_INT, ldr_elo_int_elem(), cubload::LDR_FLOAT, ldr_float_elem(), ldr_Hint_class_names, ldr_Hint_flags, ldr_Hint_locks, ldr_Hint_subclasses, cubload::LDR_INT, ldr_int_elem(), cubload::LDR_JSON, ldr_json_elem(), cubload::LDR_MONETARY, ldr_monetary_elem(), cubload::LDR_NSTR, ldr_nstr_elem(), cubload::LDR_NULL, ldr_null_elem(), cubload::LDR_NUMERIC, ldr_numeric_elem(), cubload::LDR_OID, ldr_oid_elem(), cubload::LDR_STR, ldr_str_elem(), cubload::LDR_TIME, ldr_time_elem(), cubload::LDR_TIMESTAMP, ldr_timestamp_elem(), cubload::LDR_TIMESTAMPLTZ, ldr_timestampltz_elem(), cubload::LDR_TIMESTAMPTZ, ldr_timestamptz_elem(), cubload::LDR_XSTR, ldr_xstr_elem(), locator_fetch_mode_to_lock(), NO_ERROR, NULL, NUM_LDR_TYPES, db_timestamptz::timestamp, tm_Use_OID_preflush, Total_fails, Total_objects, db_timestamptz::tz_id, db_datetimetz::tz_id, ldr_context::valid, and ldr_context::validation_only.
Referenced by ldr_init().
static int ldr_int_db_bigint (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 2368 of file load_sa_loader.cpp.
References ARG_FILE_LINE, db_data::bigint, db_numeric::buf, CHECK_ERR, CHECK_PARSE_ERR, db_numeric::d, db_value::data, db_get_type_name(), DB_TYPE_BIGINT, sm_attribute::domain, db_value::domain, ER_ERROR_SEVERITY, ER_IT_DATA_OVERFLOW, er_set(), err, MAX_DIGITS_FOR_BIGINT, ldr_context::mobj, NO_ERROR, numeric_coerce_dec_str_to_num(), numeric_coerce_num_to_bigint(), OBJ_SET_BOUND_BIT, sm_attribute::offset, parse_bigint(), pr_type::setmem(), sm_attribute::storage_order, and tp_domain::type.
Referenced by ldr_act_add_attr().
static int ldr_int_db_generic (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 2347 of file load_sa_loader.cpp.
References CHECK_ERR, err, ldr_generic(), and ldr_int_elem().
Referenced by ldr_act_add_attr().
static int ldr_int_db_int (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 2423 of file load_sa_loader.cpp.
References ARG_FILE_LINE, CHECK_ERR, CHECK_PARSE_ERR, db_value::data, db_get_type_name(), DB_TYPE_INTEGER, sm_attribute::domain, db_value::domain, ER_ERROR_SEVERITY, ER_IT_DATA_OVERFLOW, er_set(), err, db_data::i, MAX_DIGITS_FOR_INT, ldr_context::mobj, OBJ_SET_BOUND_BIT, sm_attribute::offset, OR_CHECK_INT_OVERFLOW, parse_int(), ROUND, pr_type::setmem(), sm_attribute::storage_order, and tp_domain::type.
Referenced by ldr_act_add_attr().
static int ldr_int_db_short (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 2478 of file load_sa_loader.cpp.
References ARG_FILE_LINE, CHECK_ERR, CHECK_PARSE_ERR, db_value::data, db_get_type_name(), DB_TYPE_SHORT, sm_attribute::domain, db_value::domain, ER_ERROR_SEVERITY, ER_IT_DATA_OVERFLOW, er_set(), err, MAX_DIGITS_FOR_SHORT, ldr_context::mobj, OBJ_SET_BOUND_BIT, sm_attribute::offset, OR_CHECK_SHORT_OVERFLOW, parse_int(), ROUND, pr_type::setmem(), db_data::sh, sm_attribute::storage_order, and tp_domain::type.
Referenced by ldr_act_add_attr().
static int ldr_int_elem (LDR_CONTEXT * context, const char * str, size_t len, DB_VALUE * val) static
Definition at line 2283 of file load_sa_loader.cpp.
References ARG_FILE_LINE, db_data::bigint, db_numeric::buf, CHECK_PARSE_ERR, db_numeric::d, db_value::data, db_get_type_name(), DB_TYPE_BIGINT, DB_TYPE_C_CHAR, DB_TYPE_INTEGER, DB_TYPE_NUMERIC, db_value_domain_init(), db_value_put(), db_value::domain, ER_ERROR_SEVERITY, ER_IT_DATA_OVERFLOW, er_set(), err, db_data::i, MAX_DIGITS_FOR_BIGINT, MAX_DIGITS_FOR_INT, NO_ERROR, numeric_coerce_dec_str_to_num(), numeric_coerce_num_to_bigint(), parse_bigint(), and parse_int().
Referenced by ldr_init_loader(), and ldr_int_db_generic().
static void ldr_internal_error (LDR_CONTEXT * context) static
Definition at line 1601 of file load_sa_loader.cpp.
References ldr_abort(), and ldr_clear_and_free_context().
Referenced by construct_instance(), insert_instance(), insert_meth_instance(), ldr_act_add_argument(), ldr_act_init_context(), ldr_class_oid_elem(), and ldr_oid_elem().
static void ldr_invalid_class_error (LDR_CONTEXT * context) static
Definition at line 1670 of file load_sa_loader.cpp.
References display_error_line(), ldr_attr_name(), ldr_class_name(), LOADDB_MSG_UNKNOWN_ATT_CLASS, MSGCAT_CATALOG_UTILS, msgcat_message(), and MSGCAT_UTIL_SET_LOADDB.
Referenced by ldr_act_set_ref_class().
static bool ldr_is_ignore_class (const char * class_name, size_t size) static
Definition at line 6516 of file load_sa_loader.cpp.
References ldr_context::args, cubload::load_args::ignore_classes, intl_identifier_ncasecmp(), IS_OLD_GLO_CLASS, and NULL.
Referenced by cubload::sa_class_installer::check_class(), ldr_act_set_skip_current_class(), and ldr_process_object_ref().
static int ldr_json_db_json (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 6660 of file load_sa_loader.cpp.
References CHECK_ERR, db_make_null(), db_value_clear(), err, ldr_generic(), ldr_json_elem(), and NO_ERROR.
Referenced by ldr_act_add_attr().
static int ldr_json_elem (LDR_CONTEXT * context, const char * str, size_t len, DB_VALUE * val) static
Definition at line 6643 of file load_sa_loader.cpp.
References assert, db_json_get_json_from_str(), db_make_json(), NO_ERROR, and NULL.
Referenced by ldr_init_loader(), and ldr_json_db_json().
static int ldr_mismatch (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 2016 of file load_sa_loader.cpp.
References ARG_FILE_LINE, CHECK_ERR, ER_ERROR_SEVERITY, ER_OBJ_DOMAIN_CONFLICT, er_set(), err, sm_attribute::header, and sm_component::name.
Referenced by ldr_act_add_attr().
static int ldr_monetary_db_monetary (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 4380 of file load_sa_loader.cpp.
References CHECK_ERR, sm_attribute::domain, err, ldr_monetary_elem(), ldr_context::mobj, OBJ_SET_BOUND_BIT, sm_attribute::offset, pr_type::setmem(), sm_attribute::storage_order, and tp_domain::type.
Referenced by ldr_act_add_attr().
static int ldr_monetary_elem (LDR_CONTEXT * context, const char * str, size_t len, DB_VALUE * val) static
Definition at line 4333 of file load_sa_loader.cpp.
References ARG_FILE_LINE, CHECK_PARSE_ERR, CURRENCY_CHECK_MODE_ESC_ISO, CURRENCY_CHECK_MODE_GRAMMAR, DB_CURRENCY_DOLLAR, DB_CURRENCY_NULL, db_get_type_name(), db_make_monetary(), DB_TYPE_MONETARY, ER_ERROR_SEVERITY, ER_IT_DATA_OVERFLOW, er_set(), err, intl_is_currency_symbol(), NO_ERROR, OR_CHECK_DOUBLE_OVERFLOW, and p.
Referenced by ldr_init_loader(), and ldr_monetary_db_monetary().
static void ldr_mop_tempoid_maps_final (void) static
Definition at line 3925 of file load_sa_loader.cpp.
References free_and_init, and ldr_mop_tempoid_maps::mop_tempoid_maps.
Referenced by ldr_final().
static int ldr_mop_tempoid_maps_init (void) static
Definition at line 3872 of file load_sa_loader.cpp.
References ARG_FILE_LINE, ldr_mop_tempoid_maps::count, ER_ERROR_SEVERITY, ER_LDR_MEMORY_ERROR, er_set(), err, i, ldr_mop_tempoid_map::id, ldr_mop_tempoid_maps::index, LDR_MOP_TEMPOID_MAPS_PRESIZE, ldr_mop_tempoid_map::mop, ldr_mop_tempoid_maps::mop_tempoid_maps, NO_ERROR, NULL, ldr_mop_tempoid_maps::size, and ldr_mop_tempoid_map::table.
Referenced by ldr_add_mop_tempoid_map(), and ldr_start().
static int ldr_nstr_db_varnchar (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 2917 of file load_sa_loader.cpp.
References CHECK_ERR, err, ldr_generic(), ldr_nstr_elem(), and NO_ERROR.
Referenced by ldr_act_add_attr().
static int ldr_nstr_elem (LDR_CONTEXT * context, const char * str, size_t len, DB_VALUE * val) static
Definition at line 2900 of file load_sa_loader.cpp.
References db_make_varnchar(), LANG_SYS_CODESET, LANG_SYS_COLLATION, NO_ERROR, and TP_FLOATING_PRECISION_VALUE.
Referenced by ldr_init_loader(), and ldr_nstr_db_varnchar().
static int ldr_null_db_generic (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 2086 of file load_sa_loader.cpp.
References ARG_FILE_LINE, CHECK_ERR, ldr_context::class_name, sm_attribute::domain, ER_ERROR_SEVERITY, ER_OBJ_ATTRIBUTE_CANT_BE_NULL, er_set(), err, sm_attribute::flags, sm_attribute::header, ldr_context::mobj, sm_component::name, NO_ERROR, NULL, OBJ_CLEAR_BOUND_BIT, sm_attribute::offset, pr_type::setmem(), SM_ATTFLAG_NON_NULL, sm_attribute::storage_order, tp_domain::type, and pr_type::variable_p.
Referenced by ldr_act_add_attr().
static int ldr_null_elem (LDR_CONTEXT * context, const char * str, size_t len, DB_VALUE * val) static
Definition at line 2071 of file load_sa_loader.cpp.
References db_make_null(), and NO_ERROR.
Referenced by ldr_collection_elem(), and ldr_init_loader().
static int ldr_numeric_db_generic (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 2972 of file load_sa_loader.cpp.
References CHECK_ERR, err, ldr_generic(), and ldr_numeric_elem().
Referenced by ldr_act_add_attr().
static int ldr_numeric_elem (LDR_CONTEXT * context, const char * str, size_t len, DB_VALUE * val) static
Definition at line 2948 of file load_sa_loader.cpp.
References CHECK_PARSE_ERR, DB_TYPE_C_CHAR, DB_TYPE_NUMERIC, db_value_domain_init(), db_value_put(), err, and NO_ERROR.
Referenced by ldr_init_loader(), and ldr_numeric_db_generic().
static int ldr_oid_db_object (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 4307 of file load_sa_loader.cpp.
References CHECK_ERR, sm_attribute::domain, err, ldr_oid_elem(), ldr_context::mobj, NO_ERROR, OBJ_SET_BOUND_BIT, sm_attribute::offset, pr_type::setmem(), sm_attribute::storage_order, and tp_domain::type.
Referenced by ldr_act_add_attr().
static int ldr_oid_elem (LDR_CONTEXT * context, const char * str, size_t len, DB_VALUE * val) static
Definition at line 4258 of file load_sa_loader.cpp.
References ARG_FILE_LINE, ldr_context::attrs, CHECK_ERR, check_object_domain(), db_make_null(), db_make_object(), er_errid(), ER_ERROR_SEVERITY, ER_GENERIC_ERROR, ER_LDR_INTERNAL_REFERENCE, er_set(), err, find_instance(), LDR_ATTDESC::instance_id, ldr_increment_err_count(), ldr_internal_error(), ldr_context::next_attr, NO_ERROR, NULL, LDR_ATTDESC::ref_class, and ws_mop().
Referenced by ldr_init_loader(), and ldr_oid_db_object().
static void ldr_process_object_ref (object_ref_type * ref, int type) static
Definition at line 6540 of file load_sa_loader.cpp.
References cubload::object_ref_type::class_id, cubload::object_ref_type::class_name, db_get_class_name(), cubload::object_ref_type::instance_number, ldr_act_get_ref_class(), ldr_act_set_instance_id(), ldr_act_set_ref_class(), ldr_act_set_ref_class_id(), cubload::LDR_CLASS_OID, ldr_Current_context, ldr_is_ignore_class(), cubload::LDR_NULL, cubload::LDR_OID, NULL, cubload::string_type::size, strlen, and cubload::string_type::val.
Referenced by cubload::sa_object_loader::process_line().
static int ldr_real_db_double (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 3134 of file load_sa_loader.cpp.
References ARG_FILE_LINE, CHECK_ERR, CHECK_PARSE_ERR, db_data::d, db_value::data, db_get_type_name(), sm_attribute::domain, db_value::domain, ER_ERROR_SEVERITY, ER_IT_DATA_OVERFLOW, er_set(), err, GET_DOMAIN, ldr_context::mobj, OBJ_SET_BOUND_BIT, sm_attribute::offset, OR_CHECK_DOUBLE_OVERFLOW, pr_type::setmem(), sm_attribute::storage_order, TP_DOMAIN_TYPE, and tp_domain::type.
Referenced by ldr_act_add_attr().
static int ldr_real_db_float (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 3090 of file load_sa_loader.cpp.
References ARG_FILE_LINE, CHECK_ERR, CHECK_PARSE_ERR, db_value::data, db_get_type_name(), sm_attribute::domain, db_value::domain, ER_ERROR_SEVERITY, ER_IT_DATA_OVERFLOW, er_set(), err, db_data::f, GET_DOMAIN, ldr_context::mobj, OBJ_SET_BOUND_BIT, sm_attribute::offset, OR_CHECK_FLOAT_OVERFLOW, pr_type::setmem(), sm_attribute::storage_order, TP_DOMAIN_TYPE, and tp_domain::type.
Referenced by ldr_act_add_attr().
static int ldr_real_db_generic (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 3069 of file load_sa_loader.cpp.
References CHECK_ERR, err, ldr_double_elem(), and ldr_generic().
Referenced by ldr_act_add_attr().
static int ldr_refresh_attrs (LDR_CONTEXT * context) static
Definition at line 5279 of file load_sa_loader.cpp.
References LDR_ATTDESC::att, LDR_ATTDESC::attdesc, ldr_context::attr_type, ldr_context::attrs, CHECK_ERR, ldr_context::class_name, ldr_context::cls, db_free_attribute_descriptor(), db_get_attribute_descriptor(), display_error(), er_filter_errid(), err, i, cubload::LDR_ATTRIBUTE_CLASS, ldr_find_class(), sm_descriptor::name, NO_ERROR, NULL, ldr_context::num_attrs, and sm_get_descriptor_component().
Referenced by check_commit().
static void ldr_register_post_commit_handler () static
Definition at line 6407 of file load_sa_loader.cpp.
References ldr_post_commit_handler, and ldr_report_num_of_commits().
Referenced by ldr_sa_load().
static void ldr_register_post_interrupt_handler () static
Definition at line 6395 of file load_sa_loader.cpp.
References ldr_get_num_of_inserted_objects(), ldr_Jmp_buf, ldr_Jmp_buf_ptr, and ldr_post_interrupt_handler.
Referenced by ldr_sa_load().
static void ldr_report_num_of_commits (int64_t num_committed) static
Definition at line 6696 of file load_sa_loader.cpp.
References ldr_context::args, ldr_context::class_name, LOADDB_MSG_COMMITTED_INSTANCES, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_SET_LOADDB, print_log_msg(), and cubload::load_args::verbose_commit.
Referenced by ldr_register_post_commit_handler().
static int ldr_reset_context (LDR_CONTEXT * context) static
Definition at line 4494 of file load_sa_loader.cpp.
References ldr_context::attr_type, au_fetch_instance(), AU_FETCH_UPDATE, AU_UPDATE, CHECK_CONTEXT_VALIDITY, CHECK_ERR, ldr_context::class_pin, ldr_context::class_type, ldr_context::cls, ldr_context::constructor, db_create_internal(), display_error(), er_filter_errid(), err, instance_info::flags, INST_FLAG_CLASS_ATT, INST_FLAG_RESERVED, ldr_context::inst_num, LC_FETCH_MVCC_VERSION, cubload::LDR_ATTRIBUTE_ANY, ldr_clear_err_count(), ldr_context::mobj, ldr_context::next_attr, NO_ERROR, NULL, ldr_context::obj, ldr_context::obj_pin, instance_info::oid, otable_find(), db_object::pruning_type, ldr_context::table, ws_class_has_object_dependencies(), ws_mop(), ws_pin_instance_and_class(), and ws_release_instance().
Referenced by cubload::sa_object_loader::start_line().
static void ldr_restore_pin_and_drop_obj (LDR_CONTEXT * context, bool drop_obj) static
Definition at line 4693 of file load_sa_loader.cpp.
References ldr_context::class_pin, db_drop(), NULL, ldr_context::obj, ldr_context::obj_pin, and ws_restore_pin().
Referenced by cubload::sa_object_loader::finish_line().
void ldr_sa_load (load_args * args, int * status, bool * interrupted)
Definition at line 6204 of file load_sa_loader.cpp.
References db_abort_transaction(), db_commit_transaction(), db_error_string(), cubload::load_args::disable_statistics, errors, cubload::driver::get_class_installer(), cubthread::get_entry(), cubload::load_args::ignore_logging, cubload::class_installer::install_class(), ldr_Driver, ldr_final(), ldr_init(), ldr_init_driver(), ldr_Interrupt_type, ldr_Jmp_buf, ldr_register_post_commit_handler(), ldr_register_post_interrupt_handler(), ldr_signal_handler(), ldr_start(), ldr_stats(), cubload::LDR_STOP_AND_ABORT_INTERRUPT, cubload::LDR_STOP_AND_COMMIT_INTERRUPT, ldr_update_statistics(), cubload::load_args::load_only, LOADDB_MSG_CHECKING, LOADDB_MSG_COMMITTING, LOADDB_MSG_DEFAULT_COUNT, LOADDB_MSG_ERROR_COUNT, LOADDB_MSG_INSERT_AND_FAIL_COUNT, LOADDB_MSG_INSERTING, LOADDB_MSG_LAST_COMMITTED_LINE, LOADDB_MSG_OBJECT_COUNT, LOADDB_MSG_UPDATING_STATISTICS, locator_Dont_check_foreign_key, cubthread::entry::m_loaddb_driver, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_SET_LOADDB, NO_ERROR, NULL, cubload::load_args::object_file, cubload::driver::parse(), cubload::load_args::periodic_commit, print_log_msg(), cubload::load_args::syntax_check, cubload::load_args::table_name, Total_objects_loaded, util_arm_signal_handlers(), util_log_write_errstr(), and cubload::load_args::verbose.
Referenced by loaddb_internal().
static void ldr_signal_handler (void) static
Definition at line 6679 of file load_sa_loader.cpp.
References ldr_Interrupt_type, ldr_Load_interrupted, LOADDB_MSG_SIG1, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_SET_LOADDB, and print_log_msg().
Referenced by ldr_sa_load().
static int ldr_start () static
Definition at line 6114 of file load_sa_loader.cpp.
References ldr_context::args, ldr_context::commit_counter, err, ldr_clear_context(), ldr_Context, ldr_Current_context, ldr_mop_tempoid_maps_init(), NO_ERROR, cubload::load_args::periodic_commit, Total_fails, Total_objects, and ldr_context::validation_only.
Referenced by ldr_sa_load().
static void ldr_stats (int * errors, int64_t * objects, int * defaults, int64_t * lastcommit, int * fails) static
Definition at line 6422 of file load_sa_loader.cpp.
References ldr_context::default_count, ldr_context::err_total, Last_committed_line, NULL, Total_fails, and Total_objects.
Referenced by ldr_sa_load().
static int ldr_str_db_char (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 2567 of file load_sa_loader.cpp.
References ARG_FILE_LINE, db_char::buf, db_data::ch, db_domain_info::char_info, CHECK_ERR, CHECK_PARSE_ERR, tp_domain::codeset, db_char::compressed_buf, db_char::compressed_need_clear, db_char::compressed_size, db_value::data, db_get_type_name(), DB_TYPE_CHAR, sm_attribute::domain, db_value::domain, ER_ERROR_SEVERITY, ER_IT_DATA_OVERFLOW, er_set(), err, db_char::info, intl_char_count(), intl_char_size(), db_char::is_max_string, db_domain_info::char_info::length, db_char::medium, MEDIUM_STRING, ldr_context::mobj, NULL, OBJ_SET_BOUND_BIT, sm_attribute::offset, p, tp_domain::precision, pr_type::setmem(), db_char::size, sm_attribute::storage_order, db_char::style, and tp_domain::type.
Referenced by ldr_act_add_attr().
static int ldr_str_db_generic (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 2714 of file load_sa_loader.cpp.
References db_make_string(), and ldr_generic().
Referenced by ldr_act_add_attr().
static int ldr_str_db_varchar (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 2640 of file load_sa_loader.cpp.
References ARG_FILE_LINE, db_char::buf, db_data::ch, db_domain_info::char_info, CHECK_ERR, CHECK_PARSE_ERR, tp_domain::codeset, db_char::compressed_buf, db_char::compressed_need_clear, db_char::compressed_size, db_value::data, db_get_type_name(), DB_TYPE_VARCHAR, sm_attribute::domain, db_value::domain, ER_ERROR_SEVERITY, ER_IT_DATA_OVERFLOW, er_set(), err, db_char::info, intl_char_count(), intl_char_size(), db_char::is_max_string, db_domain_info::char_info::length, db_char::medium, MEDIUM_STRING, ldr_context::mobj, NULL, sm_attribute::offset, p, tp_domain::precision, pr_type::setmem(), db_char::size, db_char::style, and tp_domain::type.
Referenced by ldr_act_add_attr().
static int ldr_str_elem (LDR_CONTEXT * context, const char * str, size_t len, DB_VALUE * val) static
Definition at line 2551 of file load_sa_loader.cpp.
References db_make_string(), and NO_ERROR.
Referenced by ldr_init_loader().
static int ldr_sys_class_db_generic (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 2249 of file load_sa_loader.cpp.
References CHECK_CONTEXT_VALIDITY, display_error_line(), ldr_increment_err_count(), LOADDB_MSG_UNAUTHORIZED_CLASS, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_SET_LOADDB, and NO_ERROR.
Referenced by ldr_act_add_attr().
static int ldr_sys_user_db_generic (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 2230 of file load_sa_loader.cpp.
References ARG_FILE_LINE, display_error_line(), ER_ERROR_SEVERITY, ER_GENERIC_ERROR, er_set(), ldr_increment_err_count(), LOADDB_MSG_UNAUTHORIZED_CLASS, MSGCAT_CATALOG_UTILS, msgcat_message(), and MSGCAT_UTIL_SET_LOADDB.
Referenced by ldr_act_add_attr().
static int ldr_time_db_time (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 3250 of file load_sa_loader.cpp.
References CHECK_ERR, sm_attribute::domain, err, ldr_time_elem(), ldr_context::mobj, OBJ_SET_BOUND_BIT, sm_attribute::offset, pr_type::setmem(), sm_attribute::storage_order, and tp_domain::type.
Referenced by ldr_act_add_attr().
static int ldr_time_elem (LDR_CONTEXT * context, const char * str, size_t len, DB_VALUE * val) static
Definition at line 3230 of file load_sa_loader.cpp.
References CHECK_PARSE_ERR, db_value::data, db_string_to_time(), DB_TYPE_TIME, db_value::domain, err, NO_ERROR, and db_data::time.
Referenced by ldr_init_loader(), and ldr_time_db_time().
static int ldr_timestamp_db_timestamp (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 3294 of file load_sa_loader.cpp.
References CHECK_ERR, sm_attribute::domain, err, ldr_timestamp_elem(), ldr_context::mobj, OBJ_SET_BOUND_BIT, sm_attribute::offset, pr_type::setmem(), sm_attribute::storage_order, and tp_domain::type.
Referenced by ldr_act_add_attr().
static int ldr_timestamp_elem (LDR_CONTEXT * context, const char * str, size_t len, DB_VALUE * val) static
Definition at line 3274 of file load_sa_loader.cpp.
References CHECK_PARSE_ERR, db_value::data, db_string_to_timestamp(), DB_TYPE_TIMESTAMP, db_value::domain, err, NO_ERROR, and db_data::utime.
Referenced by ldr_init_loader(), and ldr_timestamp_db_timestamp().
static int ldr_timestampltz_db_timestampltz (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 3386 of file load_sa_loader.cpp.
References CHECK_ERR, sm_attribute::domain, err, ldr_timestampltz_elem(), ldr_context::mobj, OBJ_SET_BOUND_BIT, sm_attribute::offset, pr_type::setmem(), sm_attribute::storage_order, and tp_domain::type.
Referenced by ldr_act_add_attr().
static int ldr_timestampltz_elem (LDR_CONTEXT * context, const char * str, size_t len, DB_VALUE * val) static
Definition at line 3341 of file load_sa_loader.cpp.
References CHECK_PARSE_ERR, db_value::data, db_string_to_timestampltz(), DB_TYPE_TIMESTAMPLTZ, db_value::domain, err, NO_ERROR, and db_data::utime.
Referenced by ldr_init_loader(), and ldr_timestampltz_db_timestampltz().
static int ldr_timestamptz_db_timestamptz (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 3362 of file load_sa_loader.cpp.
References CHECK_ERR, sm_attribute::domain, err, ldr_timestamptz_elem(), ldr_context::mobj, OBJ_SET_BOUND_BIT, sm_attribute::offset, pr_type::setmem(), sm_attribute::storage_order, and tp_domain::type.
Referenced by ldr_act_add_attr().
static int ldr_timestamptz_elem (LDR_CONTEXT * context, const char * str, size_t len, DB_VALUE * val) static
Definition at line 3318 of file load_sa_loader.cpp.
References CHECK_PARSE_ERR, db_value::data, db_string_to_timestamptz(), DB_TYPE_TIMESTAMPTZ, db_value::domain, err, NO_ERROR, and db_data::timestamptz.
Referenced by ldr_init_loader(), and ldr_timestamptz_db_timestamptz().
static int ldr_update_statistics (void) static
Definition at line 6458 of file load_sa_loader.cpp.
References ldr_context::args, assert, Classes, er_errid(), err, LOADDB_MSG_CLASS_TITLE, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_SET_LOADDB, NO_ERROR, NULL, sm_get_ch_name(), sm_update_statistics(), STATS_WITH_SAMPLING, and cubload::load_args::verbose.
Referenced by ldr_sa_load().
static int ldr_xstr_db_varbit (LDR_CONTEXT * context, const char * str, size_t len, SM_ATTRIBUTE * att) static
Definition at line 2878 of file load_sa_loader.cpp.
References CHECK_ERR, db_value_clear(), err, ldr_generic(), and ldr_xstr_elem().
Referenced by ldr_act_add_attr().
static int ldr_xstr_elem (LDR_CONTEXT * context, const char * str, size_t len, DB_VALUE * val) static
Definition at line 2812 of file load_sa_loader.cpp.
References ARG_FILE_LINE, LDR_ATTDESC::att, ldr_context::attrs, CHECK_PARSE_ERR, CHECK_PTR, DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_make_null(), db_make_varbit(), db_private_alloc, db_private_free_and_init, DB_TYPE_BIT, db_value_clear(), db_value_domain_init(), ER_ERROR_SEVERITY, ER_OBJ_DOMAIN_CONFLICT, er_set(), err, GET_DOMAIN, sm_attribute::header, ldr_attr_name(), sm_component::name, db_value::need_clear, ldr_context::next_attr, NO_ERROR, NULL, tp_domain::precision, qstr_hex_to_bin(), tp_domain::scale, tp_domain_resolve_value(), TP_DOMAIN_TYPE, TP_FLOATING_PRECISION_VALUE, and tp_value_cast().
Referenced by ldr_init_loader(), and ldr_xstr_db_varbit().
static void parse_error (LDR_CONTEXT * context, DB_TYPE token_type, const char * token) static
Definition at line 1690 of file load_sa_loader.cpp.
References db_get_type_name(), display_error_line(), ldr_attr_name(), ldr_class_name(), LOADDB_MSG_PARSE_ERROR, MSGCAT_CATALOG_UTILS, msgcat_message(), and MSGCAT_UTIL_SET_LOADDB.
static int select_set_domain (LDR_CONTEXT * context, TP_DOMAIN * domain, TP_DOMAIN ** set_domain_ptr) static
Definition at line 1164 of file load_sa_loader.cpp.
References ARG_FILE_LINE, db_get_type_name(), DB_TYPE_SET, ER_ERROR_SEVERITY, ER_LDR_DOMAIN_MISMATCH, er_set(), err, ldr_attr_name(), ldr_class_name(), pr_type::name, NO_ERROR, NULL, TP_DOMAIN_TYPE, TP_IS_SET_TYPE, and tp_domain::type.
Referenced by ldr_act_add_attr().
static int update_default_count (CLASS_TABLE * table, OID * oid) static
Definition at line 5345 of file load_sa_loader.cpp.
References ldr_context::default_count, NO_ERROR, and class_table::total_inserts.
Referenced by update_default_instances_stats().
static int update_default_instances_stats (LDR_CONTEXT * context) static
Definition at line 5361 of file load_sa_loader.cpp.
References ldr_context::default_count, err, otable_map_reserved(), and update_default_count().
Referenced by ldr_destroy().
Variable Documentation
LDR_ELEM elem_converter[NUM_LDR_TYPES] static
Definition at line 353 of file load_sa_loader.cpp.
Referenced by construct_instance(), ldr_act_class_attr(), ldr_act_elem(), and ldr_init_loader().
DB_OBJECT** Id_map = NULL static
Definition at line 403 of file load_sa_loader.cpp.
Referenced by idmap_grow().
int Id_map_size = 0 static
Definition at line 404 of file load_sa_loader.cpp.
Referenced by idmap_final(), idmap_grow(), idmap_init(), and ldr_get_class_from_id().
DB_OBJLIST* internal_classes = NULL static
Definition at line 412 of file load_sa_loader.cpp.
Referenced by qexec_execute_delete(), and qexec_execute_update().
int64_t Last_committed_line = 0 static
Definition at line 360 of file load_sa_loader.cpp.
Referenced by check_commit(), and ldr_stats().
void(* ldr_act) (LDR_CONTEXT *context, const char *str, size_t len, data_type type) = ldr_act_attr
Definition at line 633 of file load_sa_loader.cpp.
Referenced by ldr_act_attr(), ldr_act_restrict_attributes(), ldr_act_set_constructor(), ldr_collection_db_collection(), ldr_finish_context(), ldr_init_loader(), and cubload::sa_object_loader::process_line().
DB_VALUE ldr_bigint_tmpl static
Definition at line 429 of file load_sa_loader.cpp.
DB_VALUE ldr_bit_tmpl static
Definition at line 444 of file load_sa_loader.cpp.
DB_VALUE ldr_blob_tmpl static
Definition at line 442 of file load_sa_loader.cpp.
DB_VALUE ldr_char_tmpl static
Definition at line 430 of file load_sa_loader.cpp.
DB_VALUE ldr_clob_tmpl static
Definition at line 443 of file load_sa_loader.cpp.
LDR_CONTEXT ldr_Context static
Definition at line 327 of file load_sa_loader.cpp.
Referenced by ldr_init(), and ldr_start().
LDR_CONTEXT* ldr_Current_context = NULL static
Definition at line 326 of file load_sa_loader.cpp.
Referenced by ldr_final(), ldr_init(), ldr_process_object_ref(), ldr_start(), and cubload::sa_object_loader::process_line().
DB_VALUE ldr_date_tmpl static
Definition at line 434 of file load_sa_loader.cpp.
DB_VALUE ldr_datetime_tmpl static
Definition at line 439 of file load_sa_loader.cpp.
DB_VALUE ldr_datetimeltz_tmpl static
Definition at line 440 of file load_sa_loader.cpp.
DB_VALUE ldr_datetimetz_tmpl static
Definition at line 441 of file load_sa_loader.cpp.
DB_VALUE ldr_double_tmpl static
Definition at line 433 of file load_sa_loader.cpp.
driver* ldr_Driver static
Definition at line 330 of file load_sa_loader.cpp.
Referenced by ldr_init_driver(), and ldr_sa_load().
DB_VALUE ldr_float_tmpl static
Definition at line 432 of file load_sa_loader.cpp.
const char* ldr_Hint_class_names[LDR_LOCKHINT_COUNT] static
Definition at line 344 of file load_sa_loader.cpp.
Referenced by ldr_find_class(), and ldr_init_loader().
LC_PREFETCH_FLAGS ldr_Hint_flags[LDR_LOCKHINT_COUNT] static
Definition at line 346 of file load_sa_loader.cpp.
Referenced by ldr_find_class(), and ldr_init_loader().
LOCK ldr_Hint_locks[LDR_LOCKHINT_COUNT] static
Definition at line 343 of file load_sa_loader.cpp.
Referenced by ldr_find_class(), and ldr_init_loader().
int ldr_Hint_subclasses[LDR_LOCKHINT_COUNT] static
Definition at line 345 of file load_sa_loader.cpp.
Referenced by ldr_find_class(), and ldr_init_loader().
DB_VALUE ldr_int_tmpl static
Definition at line 428 of file load_sa_loader.cpp.
int ldr_Interrupt_type = LDR_NO_INTERRUPT static
Definition at line 389 of file load_sa_loader.cpp.
Referenced by ldr_sa_load(), and ldr_signal_handler().
jmp_buf ldr_Jmp_buf static
Definition at line 392 of file load_sa_loader.cpp.
Referenced by ldr_register_post_interrupt_handler(), and ldr_sa_load().
jmp_buf* ldr_Jmp_buf_ptr = NULL static
Definition at line 391 of file load_sa_loader.cpp.
Referenced by check_commit(), ldr_abort(), and ldr_register_post_interrupt_handler().
DB_VALUE ldr_json_tmpl static
Definition at line 445 of file load_sa_loader.cpp.
int ldr_Load_interrupted = LDR_NO_INTERRUPT static
Definition at line 388 of file load_sa_loader.cpp.
Referenced by check_commit(), and ldr_signal_handler().
const std::size_t LDR_MAX_ARGS = 32
Definition at line 76 of file load_sa_loader.cpp.
Referenced by construct_instance().
LDR_MOP_TEMPOID_MAPS* ldr_Mop_tempoid_maps = NULL static
Definition at line 243 of file load_sa_loader.cpp.
LDR_POST_COMMIT_HANDLER ldr_post_commit_handler = NULL static
Definition at line 369 of file load_sa_loader.cpp.
Referenced by check_commit(), and ldr_register_post_commit_handler().
LDR_POST_INTERRUPT_HANDLER ldr_post_interrupt_handler = NULL static
Definition at line 377 of file load_sa_loader.cpp.
Referenced by check_commit(), ldr_abort(), and ldr_register_post_interrupt_handler().
DB_VALUE ldr_short_tmpl static
Definition at line 427 of file load_sa_loader.cpp.
DB_VALUE ldr_time_tmpl static
Definition at line 435 of file load_sa_loader.cpp.
DB_VALUE ldr_timestamp_tmpl static
Definition at line 436 of file load_sa_loader.cpp.
DB_VALUE ldr_timestampltz_tmpl static
Definition at line 437 of file load_sa_loader.cpp.
DB_VALUE ldr_timestamptz_tmpl static
Definition at line 438 of file load_sa_loader.cpp.
DB_VALUE ldr_varchar_tmpl static
Definition at line 431 of file load_sa_loader.cpp.
bool locator_Dont_check_foreign_key
Definition at line 120 of file locator_sr.c.
Referenced by ldr_sa_load().
bool skip_current_class = false static
Definition at line 315 of file load_sa_loader.cpp.
Referenced by cubload::sa_class_installer::check_class(), and ldr_act_set_skip_current_class().
bool skip_current_instance = false static
Definition at line 316 of file load_sa_loader.cpp.
Referenced by cubload::sa_object_loader::finish_line(), and cubload::sa_object_loader::start_line().
int Total_fails = 0 static
Definition at line 361 of file load_sa_loader.cpp.
Referenced by ldr_increment_fails(), ldr_init_loader(), ldr_start(), and ldr_stats().
int64_t Total_objects = 0 static
Definition at line 359 of file load_sa_loader.cpp.
Referenced by check_commit(), insert_instance(), insert_meth_instance(), ldr_init_loader(), ldr_start(), and ldr_stats().
int64_t Total_objects_loaded = 0 static
Definition at line 362 of file load_sa_loader.cpp.
Referenced by ldr_get_num_of_inserted_objects(), and ldr_sa_load().