CUBRID Engine: src/executables/loadjava.c File Reference
loadjava.c File Reference
#include "config.h"
#include <errno.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include "cubrid_getopt.h"
#include "error_code.h"
#include "message_catalog.h"
#include "utility.h"
#include "databases_file.h"
Macros
#define JAVA_DIR "java"
#define COPY_BUFFER_SIZE 1024
#define SEPERATOR '/'
#define GETMSG(msgnum) util_get_message(Msg_catalog, MSG_SET_LOADJAVA, msgnum)
Functions
static int filecopy (const char *fn_src, const char *fn_dst)
static int check_dbname (const char *name)
static void usage (void)
int main (int argc, char *argv[])
Variables
static char * Program_name = NULL
static char * Dbname = NULL
static char * Src_class = NULL
static int Force_overwrite = false
Macro Definition Documentation
#define COPY_BUFFER_SIZE 1024
Definition at line 43 of file loadjava.c.
Referenced by filecopy().
#define GETMSG (msgnum) util_get_message(Msg_catalog, MSG_SET_LOADJAVA, msgnum)
Definition at line 50 of file loadjava.c.
#define JAVA_DIR "java"
Definition at line 42 of file loadjava.c.
Referenced by main().
#define SEPERATOR '/'
Definition at line 47 of file loadjava.c.
Referenced by main().
Function Documentation
static int check_dbname (const char * name) static
Definition at line 67 of file loadjava.c.
References MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_BAD_DATABASE_NAME, MSGCAT_UTIL_SET_GENERIC, and NULL.
Referenced by main().
static int filecopy (const char * fn_src, const char * fn_dst) static
Definition at line 92 of file loadjava.c.
References COPY_BUFFER_SIZE, Force_overwrite, and NULL.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 182 of file loadjava.c.
References cfg_find_db(), check_dbname(), Dbname, error(), filecopy(), Force_overwrite, getopt_long(), i, JAVA_DIR, msgcat_final(), NO_ERROR, NULL, optind, database_info::pathname, Program_name, SEPERATOR, Src_class, strlen, usage(), and utility_initialize().
static void usage (void) static
Definition at line 170 of file loadjava.c.
References LOADJAVA_ARG_FORCE_OVERWRITE_HELP, MSGCAT_CATALOG_UTILS, msgcat_message(), and MSGCAT_UTIL_SET_LOADJAVA.
Referenced by main().
Variable Documentation
char* Dbname = NULL static
Definition at line 56 of file loadjava.c.
Referenced by main().
int Force_overwrite = false static
Definition at line 58 of file loadjava.c.
Referenced by filecopy(), and main().
char* Program_name = NULL static
Definition at line 55 of file loadjava.c.
Referenced by main().
char* Src_class = NULL static
Definition at line 57 of file loadjava.c.
Referenced by main().