CUBRID Engine: src/object/lob_locator.hpp File Reference
lob_locator.hpp File Reference
Typedefs
typedef enum lob_locator_state LOB_LOCATOR_STATE
Enumerations
enum lob_locator_state {
LOB_UNKNOWN, LOB_TRANSIENT_CREATED, LOB_TRANSIENT_DELETED, LOB_PERMANENT_CREATED,
LOB_PERMANENT_DELETED, LOB_NOT_FOUND
}
Functions
LOB_LOCATOR_STATE lob_locator_find (const char *locator, char *real_locator)
int lob_locator_add (const char *locator, LOB_LOCATOR_STATE state)
int lob_locator_change_state (const char *locator, const char *new_locator, LOB_LOCATOR_STATE state)
int lob_locator_drop (const char *locator)
bool lob_locator_is_valid (const char *locator)
const char * lob_locator_key (const char *locator)
const char * lob_locator_meta (const char *locator)
Typedef Documentation
typedef enum lob_locator_state LOB_LOCATOR_STATE
Definition at line 62 of file lob_locator.hpp.
Enumeration Type Documentation
enum lob_locator_state
Enumerator
LOB_UNKNOWN
LOB_TRANSIENT_CREATED
LOB_TRANSIENT_DELETED
LOB_PERMANENT_CREATED
LOB_PERMANENT_DELETED
LOB_NOT_FOUND
Definition at line 53 of file lob_locator.hpp.
Function Documentation
int lob_locator_add (const char * locator, LOB_LOCATOR_STATE state)
Definition at line 88 of file lob_locator.cpp.
References NULL, and xtx_add_lob_locator().
Referenced by elo_copy(), elo_create(), and elo_delete().
int lob_locator_change_state (const char * locator, const char * new_locator, LOB_LOCATOR_STATE state)
Definition at line 105 of file lob_locator.cpp.
References NULL, and xtx_change_state_of_locator().
Referenced by elo_copy(), and elo_delete().
int lob_locator_drop (const char * locator)
Definition at line 120 of file lob_locator.cpp.
References NULL, and xtx_drop_lob_locator().
Referenced by elo_copy(), and elo_delete().
LOB_LOCATOR_STATE lob_locator_find (const char * locator, char * real_locator)
Definition at line 72 of file lob_locator.cpp.
References NULL, and xtx_find_lob_locator().
Referenced by elo_copy(), and elo_delete().
bool lob_locator_is_valid (const char * locator)
Definition at line 37 of file lob_locator.cpp.
References lob_locator_key(), lob_locator_meta(), and NULL.
Referenced by tx_lob_locator_clear(), xtx_add_lob_locator(), xtx_change_state_of_locator(), xtx_drop_lob_locator(), and xtx_find_lob_locator().
const char* lob_locator_key (const char * locator)
Definition at line 54 of file lob_locator.cpp.
Referenced by lob_locator_is_valid(), lob_locator_put_meta(), xtx_add_lob_locator(), xtx_change_state_of_locator(), xtx_drop_lob_locator(), and xtx_find_lob_locator().
const char* lob_locator_meta (const char * locator)
Definition at line 60 of file lob_locator.cpp.
References PATH_SEPARATOR.
Referenced by lob_locator_is_valid(), and lob_locator_put_meta().