CUBRID Engine: src/base/locale_support.c File Reference
locale_support.c File Reference
#include "config.h"
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include "porting.h"
#include "environment_variable.h"
#include "utility.h"
#include "xml_parser.h"
#include "chartype.h"
#include "error_manager.h"
#include "release_string.h"
#include "uca_support.h"
#include "unicode_support.h"
#include "message_catalog.h"
#include "language_support.h"
#include "system_parameter.h"
#include "crypt_opfunc.h"
#include <netinet/in.h>
#include "locale_support.h"
Classes
struct TXT_CONV_ITEM
struct LOC_SHARED_DATA
Macros
#define strlen(s1) ((int) strlen(s1))
#define TXT_CONV_LINE_SIZE 512
#define TXT_CONV_ITEM_GROW_COUNT 128
#define LOC_CURRENT_COLL_TAIL(ld) (&(ld->collations[ld->coll_cnt].tail_coll))
#define COLL_SHARED_DATA_SIZE (10 + 2)
#define PRINT_DEBUG_START(d, a, m, s)
#define PRINT_DEBUG_END(d, m, s)
#define PRINT_DEBUG_DATA(d, m, s)
#define PRINT_TO_C_FILE_MAX_INT_LINE 10
#define DLL_EXPORT_PREFIX ""
#define LOCLIB_FILE_EXT "so"
#define PRINT_STRING_TO_C_FILE(fp, val, len)
#define PRINT_VAR_TO_C_FILE(fp, type, valname, val, format, d)
#define PRINT_STRING_VAR_TO_C_FILE(fp, valname, val, d)
#define PRINT_STRING_ARRAY_TO_C_FILE(fp, valname, arrcount, val, d)
#define PRINT_NUM_ARRAY_TO_C_FILE(fp, vname, vtype, intf, arrcount, val, d)
#define PRINT_UNNAMED_NUM_ARRAY_TO_C_FILE(fp, intf, tab, arrcount, val)
#define XML_COMMENT_START "<!-- "
#define XML_COMMENT_END " -->"
#define ID_PER_RANGE 8
#define START_GENERIC_RANGE LANG_MAX_BUILTIN_COLLATIONS
#define START_LANG_RANGE 47
#define PRINT_DUPLICATE_SYMBOL_NAME(symbol, dupl_coll, orig_coll, do_print)
#define DUMP_CP_BUF_SIZE 128
#define SHARED_DATA_INCR_SIZE 32
#define NORM_MAPPING_DUMP_MODE_FULL 0
#define NORM_MAPPING_DUMP_MODE_COMP 1
#define NORM_MAPPING_DUMP_MODE_DECOMP 2
#define BUF_PUT_INT16(buf, v)
#define BUF_PUT_INT32(buf, v)
#define BUF_ALIGN(buf, align)
Enumerations
enum LOC_SHARED_DATA_TYPE { LOC_SHARED_COLLATION = 0, LOC_SHARED_ALPHABET = 1, LOC_SHARED_NORMALIZATION = 2 }
Functions
static int start_element_ok (void *data, const char **attr)
static int end_element_ok (void *data, const char *el_name)
static int start_calendar (void *data, const char **attr)
static int end_dateFormatCUBRID (void *data, const char *el_name)
static int end_timeFormatCUBRID (void *data, const char *el_name)
static int end_datetimeFormatCUBRID (void *data, const char *el_name)
static int end_timestampFormatCUBRID (void *data, const char *el_name)
static int end_timetzFormatCUBRID (void *data, const char *el_name)
static int end_datetimetzFormatCUBRID (void *data, const char *el_name)
static int end_timestamptzFormatCUBRID (void *data, const char *el_name)
static int start_calendar_name_context (void *data, const char **attr)
static int start_month_day_Width (void *data, const char **attr)
static int end_month_day_Width (void *data, const char *el_name)
static int start_month (void *data, const char **attr)
static int end_month (void *data, const char *el_name)
static int start_day (void *data, const char **attr)
static int end_day (void *data, const char *el_name)
static int start_dayPeriodWidth (void *data, const char **attr)
static int start_dayPeriod (void *data, const char **attr)
static int end_dayPeriod (void *data, const char *el_name)
static int start_numbers_symbols (void *data, const char **attr)
static int start_currency (void *data, const char **attr)
static int end_number_symbol (void *data, const char *el_name)
static int start_collations (void *data, const char **attr)
static int start_one_collation (void *data, const char **attr)
static int end_one_collation (void *data, const char *el_name)
static int start_collation_settings (void *data, const char **attr)
static int start_collation_reset (void *data, const char **attr)
static int end_collation_reset (void *data, const char *el_name)
static int start_collation_rule (void *data, const char **attr)
static int start_collation_cubrid_rule (void *data, const char **attr)
static int start_collation_cubrid_rule_set_wr (void *data, const char **attr)
static int end_collation_cubrid_rule_set (void *data, const char *el_name)
static int end_collation_cubrid_rule_set_cp_ch (void *data, const char *el_name)
static int end_collation_cubrid_rule_set_ech_ecp (void *data, const char *el_name)
static int end_collation_cubrid_rule_set_w_wr (void *data, const char *el_name)
static int handle_data_collation_rule (void *data, const char *s, int len)
static int end_collation_rule (void *data, const char *el_name)
static int start_collation_x (void *data, const char **attr)
static int end_collation_x (void *data, const char *el_name)
static int end_collation_x_rule (void *data, const char *el_name)
static int end_collation_x_extend (void *data, const char *el_name)
static int end_collation_x_context (void *data, const char *el_name)
static int start_collation_logical_pos (void *data, const char **attr)
static int end_collation_logical_pos (void *data, const char *el_name)
static int start_one_alphabet (void *data, const char **attr)
static int start_upper_case_rule (void *data, const char **attr)
static int end_case_rule (void *data, const char *el_name)
static int start_lower_case_rule (void *data, const char **attr)
static int end_transform_buffer (void *data, const char *el_name)
static int start_include_collation (void *data, const char **attr)
static int start_unicode_file (void *data, const char **attr)
static int start_consoleconversion (void *data, const char **attr)
static int handle_data (void *data, const char *s, int len)
static void clear_data_buffer (XML_PARSER_DATA *pd)
static LOCALE_COLLATION * new_locale_collation (LOCALE_DATA *ld)
static TAILOR_RULE * new_collation_rule (LOCALE_DATA *ld)
static TRANSFORM_RULE * new_transform_rule (LOCALE_DATA *ld)
static CUBRID_TAILOR_RULE * new_collation_cubrid_rule (LOCALE_DATA *ld)
static void locale_alloc_collation_id (COLL_TAILORING *coll_tail)
static int locale_check_collation_id (const COLL_TAILORING *coll_tail)
static void print_debug_start_el (void *data, const char **attrs, const char *msg, const int status)
static void print_debug_end_el (void *data, const char *msg, const int status)
static void print_debug_data_content (void *data, const char *msg, const int status)
static int load_console_conv_data (LOCALE_DATA *ld, bool is_verbose)
static int locale_save_to_C_file (LOCALE_FILE lf, LOCALE_DATA *ld)
static int locale_save_calendar_to_C_file (FILE *fp, LOCALE_DATA *ld)
static int locale_save_alphabets_to_C_file (FILE *fp, LOCALE_DATA *ld)
static int locale_save_one_alphabet_to_C_file (FILE *fp, ALPHABET_DATA *a, bool save_w_identier_name, const char *alpha_suffix)
static int locale_save_collation_data_to_C_file (FILE *fp, LOCALE_COLLATION *lc)
static int locale_save_console_conv_to_C_file (FILE *fp, LOCALE_DATA *ld)
static int locale_save_normalization_to_C_file (FILE *fp, LOCALE_DATA *ld)
static void locale_destroy_collation_tailorings (const COLL_TAILORING *ct)
static void locale_destroy_collation_data (const COLL_DATA *cd)
static void locale_destroy_alphabet_tailoring (const ALPHABET_TAILORING *cd)
static void locale_destroy_console_conversion (const TEXT_CONVERSION *tc)
static int str_pop_token (char *str_p, char **token_p, char **next_p)
static int dump_locale_alphabet (ALPHABET_DATA *ad, int dl_settings, int lower_bound, int upper_bound)
static void dump_collation_key (COLL_DATA *coll, const unsigned int key, bool print_weight, bool print_key)
static void dump_collation_contr (COLL_DATA *coll, const COLL_CONTRACTION *contr, bool print_weight, bool print_contr)
static void dump_collation_codepoint (COLL_DATA *coll, const unsigned int cp, bool print_weight, bool print_cp)
static void dump_locale_normalization (UNICODE_NORMALIZATION *norm)
static void dump_unicode_mapping (UNICODE_MAPPING *um, const int mode)
static int dump_console_conversion (TEXT_CONVERSION *tc)
static int comp_func_coll_uca_exp_fo (const void *arg1, const void *arg2)
static int comp_func_coll_uca_exp (const void *arg1, const void *arg2)
static int comp_func_coll_uca_simple_weights_fo (const void *arg1, const void *arg2)
static int comp_func_coll_uca_simple_weights (const void *arg1, const void *arg2)
static int comp_func_parse_order_index (const void *arg1, const void *arg2)
static void locale_make_calendar_parse_order (LOCALE_DATA *ld)
static int locale_check_and_set_shared_data (const LOC_SHARED_DATA_TYPE lsd_type, const char *lsd_key, const void *data, LDML_CONTEXT *ldml_context, LOC_SHARED_DATA **found_entry)
static int locale_compute_coll_checksum (COLL_DATA *cd)
static int locale_alphabet_data_size (ALPHABET_DATA *a)
static int locale_alphabet_data_to_buf (ALPHABET_DATA *a, char *buf)
static int locale_compute_locale_checksum (LOCALE_DATA *ld)
static int common_collation_end_rule (void *data, LOCALE_DATA *ld, const int rule_id, TAILOR_RULE *t_rule)
static int common_collation_start_rule (void *data, const char **attr, LOCALE_DATA *ld, TAILOR_RULE *t_rule)
void locale_init_data (LOCALE_DATA *ld, const char *locale_name)
void locale_destroy_data (LOCALE_DATA *ld)
void locale_destroy_alphabet_data (const ALPHABET_DATA *a)
int locale_compile_locale (LOCALE_FILE *lf, LOCALE_DATA *ld, bool is_verbose)
void locale_mark_duplicate_collations (LOCALE_DATA **ld, int start_index, int end_index, bool is_verbose)
int locale_save_all_to_C_file (LOCALE_DATA **ld, int start_index, int end_index, LOCALE_FILE *lf)
int locale_get_cfg_locales (LOCALE_FILE **p_locale_files, int *p_num_locales, bool is_lang_init)
int locale_check_and_set_default_files (LOCALE_FILE *lf, bool is_lang_init)
static int save_contraction_to_C_file (FILE *fp, COLL_CONTRACTION *c, bool use_expansion, bool use_level_4)
int locale_prepare_C_file (void)
static int dump_locale_collation (COLL_DATA *coll, int dl_settings, int start_value, int end_value)
int locale_dump (void *data, LOCALE_FILE *lf, int dl_settings, int start_value, int end_value)
int locale_dump_lib_collations (void *lib_handle, const LOCALE_FILE *lf, int dl_settings, int start_value, int end_value)
void locale_free_shared_data (void)
void locale_destroy_normalization_data (UNICODE_NORMALIZATION *norm)
Variables
const char * ldml_ref_day_names [] = { "sun", "mon", "tue", "wed", "thu", "fri", "sat" }
const char * ldml_ref_am_pm_names []
static LOC_SHARED_DATA * shared_data = NULL
static int count_shared_data = 0
static int alloced_shared_data = 0
static COLL_DATA * dump_coll_data = NULL
static char * cmp_token_name_array = NULL
static char cmp_token_name_size = 0
XML_ELEMENT_DEF ldml_elem_ldml
XML_ELEMENT_DEF ldml_elem_dates
XML_ELEMENT_DEF ldml_elem_calendars
XML_ELEMENT_DEF ldml_elem_calendar
XML_ELEMENT_DEF ldml_elem_dateFormatCUBRID
XML_ELEMENT_DEF ldml_timeFormatCUBRID
XML_ELEMENT_DEF ldml_datetimeFormatCUBRID
XML_ELEMENT_DEF ldml_timestampFormatCUBRID
XML_ELEMENT_DEF ldml_timetzFormatCUBRID
XML_ELEMENT_DEF ldml_datetimetzFormatCUBRID
XML_ELEMENT_DEF ldml_timestamptzFormatCUBRID
XML_ELEMENT_DEF ldml_elem_months
XML_ELEMENT_DEF ldml_elem_monthContext
XML_ELEMENT_DEF ldml_elem_monthWidth
XML_ELEMENT_DEF ldml_elem_month
XML_ELEMENT_DEF ldml_elem_days
XML_ELEMENT_DEF ldml_elem_dayContext
XML_ELEMENT_DEF ldml_elem_dayWidth
XML_ELEMENT_DEF ldml_elem_day
XML_ELEMENT_DEF ldml_elem_dayPeriods
XML_ELEMENT_DEF ldml_elem_dayPeriodContext
XML_ELEMENT_DEF ldml_elem_dayPeriodWidth
XML_ELEMENT_DEF ldml_elem_dayPeriod
XML_ELEMENT_DEF ldml_elem_numbers
XML_ELEMENT_DEF ldml_elem_numbers_symbols
XML_ELEMENT_DEF ldml_elem_symbol_decimal
XML_ELEMENT_DEF ldml_elem_symbol_group
XML_ELEMENT_DEF ldml_elem_currencies
XML_ELEMENT_DEF ldml_elem_currency
XML_ELEMENT_DEF ldml_elem_collations
XML_ELEMENT_DEF ldml_elem_collation
XML_ELEMENT_DEF ldml_elem_collation_rules
XML_ELEMENT_DEF ldml_elem_collation_settings
XML_ELEMENT_DEF ldml_elem_collation_reset
XML_ELEMENT_DEF ldml_elem_collation_p
XML_ELEMENT_DEF ldml_elem_collation_s
XML_ELEMENT_DEF ldml_elem_collation_t
XML_ELEMENT_DEF ldml_elem_collation_i
XML_ELEMENT_DEF ldml_elem_collation_pc
XML_ELEMENT_DEF ldml_elem_collation_sc
XML_ELEMENT_DEF ldml_elem_collation_tc
XML_ELEMENT_DEF ldml_elem_collation_ic
XML_ELEMENT_DEF ldml_elem_collation_x
XML_ELEMENT_DEF ldml_elem_collation_x_p
XML_ELEMENT_DEF ldml_elem_collation_x_s
XML_ELEMENT_DEF ldml_elem_collation_x_t
XML_ELEMENT_DEF ldml_elem_collation_x_i
XML_ELEMENT_DEF ldml_elem_collation_x_extend
XML_ELEMENT_DEF ldml_elem_collation_x_context
XML_ELEMENT_DEF ldml_elem_collation_reset_first_variable
XML_ELEMENT_DEF ldml_elem_collation_reset_last_variable
XML_ELEMENT_DEF ldml_elem_collation_reset_first_primary_ignorable
XML_ELEMENT_DEF ldml_elem_collation_reset_last_primary_ignorable
XML_ELEMENT_DEF ldml_elem_collation_reset_first_secondary_ignorable
XML_ELEMENT_DEF ldml_elem_collation_reset_last_secondary_ignorable
XML_ELEMENT_DEF ldml_elem_collation_reset_first_tertiary_ignorable
XML_ELEMENT_DEF ldml_elem_collation_reset_last_tertiary_ignorable
XML_ELEMENT_DEF ldml_elem_collation_reset_first_non_ignorable
XML_ELEMENT_DEF ldml_elem_collation_reset_last_non_ignorable
XML_ELEMENT_DEF ldml_elem_collation_reset_first_trailing
XML_ELEMENT_DEF ldml_elem_collation_reset_last_trailing
XML_ELEMENT_DEF ldml_elem_collation_cubrid_rules
XML_ELEMENT_DEF ldml_elem_collation_cubrid_rules_set
XML_ELEMENT_DEF ldml_elem_collation_cubrid_rules_set_ch
XML_ELEMENT_DEF ldml_elem_collation_cubrid_rules_set_sch
XML_ELEMENT_DEF ldml_elem_collation_cubrid_rules_set_ech
XML_ELEMENT_DEF ldml_elem_collation_cubrid_rules_set_cp
XML_ELEMENT_DEF ldml_elem_collation_cubrid_rules_set_scp
XML_ELEMENT_DEF ldml_elem_collation_cubrid_rules_set_ecp
XML_ELEMENT_DEF ldml_elem_collation_cubrid_rules_set_w
XML_ELEMENT_DEF ldml_elem_collation_cubrid_rules_set_wr
XML_ELEMENT_DEF ldml_elem_alphabets
XML_ELEMENT_DEF ldml_elem_include_collation
XML_ELEMENT_DEF ldml_elem_alphabet
XML_ELEMENT_DEF ldml_elem_alphabet_upper
XML_ELEMENT_DEF ldml_elem_alphabet_upper_src
XML_ELEMENT_DEF ldml_elem_alphabet_upper_dest
XML_ELEMENT_DEF ldml_elem_alphabet_lower
XML_ELEMENT_DEF ldml_elem_alphabet_lower_src
XML_ELEMENT_DEF ldml_elem_alphabet_lower_dest
XML_ELEMENT_DEF ldml_elem_unicodefile
XML_ELEMENT_DEF ldml_elem_consoleconversion
XML_ELEMENT_DEF * ldml_elements []
Macro Definition Documentation
#define BUF_ALIGN (buf, align)
Value:
((char *)((((UINTPTR)(buf) + ((UINTPTR)((align)-1)))) \
                  & ~((UINTPTR)((align)-1))))
Definition at line 7413 of file locale_support.c.
Referenced by locale_compute_coll_checksum().
#define BUF_PUT_INT16 (buf, v)
Value:
do {                                 \
    unsigned short nv = htons(v);                \
    *((unsigned char *) (buf)) = ((unsigned char *) &nv)[1]; \
    buf = (char *) (buf) + 1;                    \
    *((unsigned char *) (buf)) = ((unsigned char *) &nv)[0]; \
    buf = (char *) (buf) + 1;                    \
    } while (0)
Definition at line 7391 of file locale_support.c.
Referenced by locale_compute_coll_checksum().
#define BUF_PUT_INT32 (buf, v)
Value:
do {                                 \
    unsigned int nv = htonl(v);                  \
    *((unsigned char *) (buf)) = ((unsigned char *) &nv)[3]; \
    buf = (char *) (buf) + 1;                    \
    *((unsigned char *) (buf)) = ((unsigned char *) &nv)[2]; \
    buf = (char *) (buf) + 1;                    \
    *((unsigned char *) (buf)) = ((unsigned char *) &nv)[1]; \
    buf = (char *) (buf) + 1;                    \
    *((unsigned char *) (buf)) = ((unsigned char *) &nv)[0]; \
    buf = (char *) (buf) + 1;                    \
    } while (0)
Definition at line 7400 of file locale_support.c.
Referenced by locale_alphabet_data_to_buf(), locale_compute_coll_checksum(), and locale_compute_locale_checksum().
#define COLL_SHARED_DATA_SIZE (10 + 2)
Definition at line 87 of file locale_support.c.
Referenced by locale_compile_locale().
#define DLL_EXPORT_PREFIX ""
Definition at line 230 of file locale_support.c.
Referenced by locale_save_collation_data_to_C_file(), locale_save_console_conv_to_C_file(), and locale_save_normalization_to_C_file().
#define DUMP_CP_BUF_SIZE 128
Referenced by dump_locale_alphabet().
#define ID_PER_RANGE 8
Referenced by locale_alloc_collation_id().
#define LOC_CURRENT_COLL_TAIL (ld) (&(ld->collations[ld->coll_cnt].tail_coll))
Definition at line 57 of file locale_support.c.
Referenced by end_collation_cubrid_rule_set(), end_collation_cubrid_rule_set_cp_ch(), end_collation_cubrid_rule_set_ech_ecp(), end_collation_cubrid_rule_set_w_wr(), end_collation_rule(), end_collation_x(), end_collation_x_context(), end_collation_x_extend(), end_collation_x_rule(), handle_data_collation_rule(), new_collation_cubrid_rule(), new_collation_rule(), start_collation_cubrid_rule_set_wr(), and start_collation_settings().
#define LOCLIB_FILE_EXT "so"
Definition at line 231 of file locale_support.c.
Referenced by locale_check_and_set_default_files().
#define NORM_MAPPING_DUMP_MODE_COMP 1
Definition at line 7075 of file locale_support.c.
Referenced by dump_locale_normalization(), and dump_unicode_mapping().
#define NORM_MAPPING_DUMP_MODE_DECOMP 2
Definition at line 7076 of file locale_support.c.
Referenced by dump_locale_normalization().
#define NORM_MAPPING_DUMP_MODE_FULL 0
Definition at line 7074 of file locale_support.c.
Referenced by dump_locale_normalization(), and dump_unicode_mapping().
#define PRINT_DEBUG_DATA (d, m, s)
Value:
do {                                      \
      print_debug_data_content (d, m, s);                 \
   } while (0);
Definition at line 219 of file locale_support.c.
Referenced by handle_data(), and handle_data_collation_rule().
#define PRINT_DEBUG_END (d, m, s)
Value:
do {                                      \
      print_debug_end_el (d, m, s);                   \
   } while (0);
Definition at line 214 of file locale_support.c.
Referenced by common_collation_end_rule(), end_case_rule(), end_collation_cubrid_rule_set(), end_collation_cubrid_rule_set_cp_ch(), end_collation_cubrid_rule_set_ech_ecp(), end_collation_cubrid_rule_set_w_wr(), end_collation_logical_pos(), end_collation_reset(), end_collation_rule(), end_collation_x(), end_collation_x_context(), end_collation_x_extend(), end_collation_x_rule(), end_dateFormatCUBRID(), end_datetimeFormatCUBRID(), end_datetimetzFormatCUBRID(), end_day(), end_dayPeriod(), end_element_ok(), end_month(), end_month_day_Width(), end_number_symbol(), end_one_collation(), end_timeFormatCUBRID(), end_timestampFormatCUBRID(), end_timestamptzFormatCUBRID(), end_timetzFormatCUBRID(), and end_transform_buffer().
#define PRINT_DEBUG_START (d, a, m, s)
Value:
do {                                      \
      print_debug_start_el (d, a, m, s);                  \
   } while (0);
Definition at line 209 of file locale_support.c.
Referenced by common_collation_start_rule(), start_calendar(), start_calendar_name_context(), start_collation_cubrid_rule(), start_collation_cubrid_rule_set_wr(), start_collation_logical_pos(), start_collation_reset(), start_collation_rule(), start_collation_settings(), start_collation_x(), start_collations(), start_consoleconversion(), start_currency(), start_day(), start_dayPeriod(), start_dayPeriodWidth(), start_element_ok(), start_include_collation(), start_lower_case_rule(), start_month(), start_month_day_Width(), start_numbers_symbols(), start_one_alphabet(), start_one_collation(), start_unicode_file(), and start_upper_case_rule().
#define PRINT_DUPLICATE_SYMBOL_NAME (symbol, dupl_coll, orig_coll, do_print)
Value:
if (do_print)                                   \
    {                                       \
      printf ("\n *** Duplicate array: %s in collation %s is a duplicate "  \
          "of %s from collation %s", (symbol),              \
          (dupl_coll)->opt_coll.coll_name,                  \
          (symbol), (orig_coll)->opt_coll.coll_name);           \
    }
Referenced by locale_mark_duplicate_collations().
#define PRINT_NUM_ARRAY_TO_C_FILE (fp, vname, vtype, intf, arrcount, val, d)
Value:
do {                                        \
    int i_arr, j_arr;                               \
    fprintf(fp,                                 \
        "\n" DLL_EXPORT_PREFIX "const " vtype " " vname "_%s[] = {\n", d);    \
    j_arr = 1;                                  \
    for (i_arr = 0; i_arr < arrcount; i_arr++)                  \
      {                                     \
    fprintf(fp, "\t");                          \
    fprintf(fp, intf, val[i_arr]);                      \
    if (i_arr < arrcount - 1)                      \
      {                                 \
        fprintf(fp, ",");                           \
      }                                 \
    j_arr++;                                \
    if (j_arr > PRINT_TO_C_FILE_MAX_INT_LINE)              \
      {                                 \
        j_arr = 1;                              \
        fprintf(fp, "\n");                          \
      }                                 \
      }                                     \
    fprintf(fp, "};\n");                            \
  } while (0);
Definition at line 279 of file locale_support.c.
Referenced by locale_save_calendar_to_C_file(), locale_save_collation_data_to_C_file(), locale_save_console_conv_to_C_file(), locale_save_normalization_to_C_file(), and locale_save_one_alphabet_to_C_file().
#define PRINT_STRING_ARRAY_TO_C_FILE (fp, valname, arrcount, val, d)
Value:
do {                                        \
    int istrarr;                                \
    fprintf(fp, "\n" DLL_EXPORT_PREFIX"const char* " valname "_%s[] = {\n", d);\
    for (istrarr = 0; istrarr < arrcount; istrarr++)                \
      {                                     \
    fprintf(fp, "\t");                          \
    PRINT_STRING_TO_C_FILE (fp, val[istrarr], strlen(val[istrarr]));    \
    if (istrarr < arrcount - 1)                        \
      {                                 \
        fprintf(fp, ",\n");                         \
      }                                 \
    else                                   \
      {                                 \
        fprintf(fp, "\n");                          \
      }                                 \
      }                                     \
    fprintf(fp, "};\n");                            \
  } while (0);
Definition at line 258 of file locale_support.c.
Referenced by locale_save_calendar_to_C_file().
#define PRINT_STRING_TO_C_FILE (fp, val, len)
Value:
do {                                                                \
    int istr;                                                         \
    fprintf (fp, "\"");                                               \
    for (istr = 0; istr < len; istr++)                                \
      {                                                               \
    fprintf (fp, "\\x%02X", (unsigned char) val[istr]);           \
      }                                                               \
    fprintf (fp, "\"");                           \
  } while (0);
Definition at line 234 of file locale_support.c.
Referenced by locale_save_console_conv_to_C_file(), locale_save_normalization_to_C_file(), and save_contraction_to_C_file().
#define PRINT_STRING_VAR_TO_C_FILE (fp, valname, val, d)
Value:
do {                                                                    \
    fprintf (fp, "\n" DLL_EXPORT_PREFIX "const char " valname "_%s[] = ", d); \
    PRINT_STRING_TO_C_FILE (fp, val, strlen (val));           \
    fprintf (fp, ";\n");                                                  \
  } while (0);
Definition at line 251 of file locale_support.c.
Referenced by locale_save_calendar_to_C_file(), locale_save_collation_data_to_C_file(), locale_save_console_conv_to_C_file(), and locale_save_to_C_file().
#define PRINT_TO_C_FILE_MAX_INT_LINE 10
Definition at line 224 of file locale_support.c.
#define PRINT_UNNAMED_NUM_ARRAY_TO_C_FILE (fp, intf, tab, arrcount, val)
Value:
do {                                        \
    int i_uarr, j_uarr;                             \
    fprintf(fp, tab"{\n");                          \
    j_uarr = 1;                                 \
    for (i_uarr = 0; i_uarr < arrcount; i_uarr++)               \
      {                                     \
    fprintf(fp, intf, val[i_uarr]);                     \
    if (i_uarr < arrcount - 1)                     \
      {                                 \
        fprintf(fp, ",");                           \
      }                                 \
    j_uarr++;                               \
    if (j_uarr > PRINT_TO_C_FILE_MAX_INT_LINE)             \
      {                                 \
        j_uarr = 1;                             \
        fprintf(fp, "\n" tab);                      \
      }                                 \
      }                                     \
    fprintf(fp, "\n" tab "}");                          \
  } while (0);
Definition at line 304 of file locale_support.c.
Referenced by save_contraction_to_C_file().
#define PRINT_VAR_TO_C_FILE (fp, type, valname, val, format, d)
Value:
do {                                      \
    fprintf (fp, "\n" DLL_EXPORT_PREFIX "const "                  \
         type " " valname "_%s = " format ";\n", d, val);         \
  } while (0);
Definition at line 245 of file locale_support.c.
Referenced by locale_save_alphabets_to_C_file(), locale_save_collation_data_to_C_file(), locale_save_console_conv_to_C_file(), locale_save_normalization_to_C_file(), locale_save_one_alphabet_to_C_file(), and locale_save_to_C_file().
#define SHARED_DATA_INCR_SIZE 32
Referenced by locale_check_and_set_shared_data().
#define START_GENERIC_RANGE LANG_MAX_BUILTIN_COLLATIONS
Referenced by locale_alloc_collation_id().
#define START_LANG_RANGE 47
Referenced by locale_alloc_collation_id().
#define strlen (s1) ((int) strlen(s1))
Definition at line 51 of file locale_support.c.
Referenced by common_collation_start_rule(), dump_collation_contr(), end_collation_x_context(), end_collation_x_rule(), locale_alloc_collation_id(), locale_check_and_set_default_files(), locale_compute_locale_checksum(), locale_dump_lib_collations(), locale_init_data(), save_contraction_to_C_file(), start_collation_cubrid_rule_set_wr(), start_collations(), start_consoleconversion(), start_currency(), and start_unicode_file().
#define TXT_CONV_ITEM_GROW_COUNT 128
Definition at line 55 of file locale_support.c.
Referenced by load_console_conv_data().
#define TXT_CONV_LINE_SIZE 512
Definition at line 54 of file locale_support.c.
Referenced by load_console_conv_data().
#define XML_COMMENT_END " -->"
Definition at line 328 of file locale_support.c.
Referenced by print_debug_data_content(), print_debug_end_el(), and print_debug_start_el().
#define XML_COMMENT_START "<!-- "
Definition at line 327 of file locale_support.c.
Referenced by print_debug_data_content(), print_debug_end_el(), and print_debug_start_el().
Enumeration Type Documentation
enum LOC_SHARED_DATA_TYPE
Enumerator
LOC_SHARED_COLLATION
LOC_SHARED_ALPHABET
LOC_SHARED_NORMALIZATION
Definition at line 74 of file locale_support.c.
Function Documentation
static void clear_data_buffer (XML_PARSER_DATA * pd) static
Definition at line 3469 of file locale_support.c.
References assert, locale_data::data_buf_count, locale_data::data_buffer, NULL, and XML_USER_DATA.
Referenced by end_collation_cubrid_rule_set_cp_ch(), end_collation_cubrid_rule_set_ech_ecp(), end_collation_cubrid_rule_set_w_wr(), end_collation_reset(), end_collation_x_context(), end_collation_x_extend(), end_collation_x_rule(), end_dateFormatCUBRID(), end_datetimeFormatCUBRID(), end_datetimetzFormatCUBRID(), end_day(), end_dayPeriod(), end_month(), end_number_symbol(), end_timeFormatCUBRID(), end_timestampFormatCUBRID(), end_timestamptzFormatCUBRID(), end_timetzFormatCUBRID(), end_transform_buffer(), and start_collation_cubrid_rule().
static int common_collation_end_rule (void * data, LOCALE_DATA * ld, const int rule_id, TAILOR_RULE * t_rule) static
Definition at line 7854 of file locale_support.c.
References assert, tailor_rule::direction, ERR_MSG_SIZE, locale_data::last_anchor_buf, locale_data::last_r_buf_p, locale_data::last_r_buf_size, locale_data::last_rule_dir, locale_data::last_rule_level, locale_data::last_rule_pos_type, tailor_rule::level, tailor_rule::multiple_chars, NULL, PRINT_DEBUG_END, tailor_rule::r_pos_type, RULE_POS_BUFFER, tailor_rule::t_buf, tailor_rule::t_buf_size, TAILOR_AFTER, TAILOR_UNDEFINED, xml_parser_data::verbose, XML_CUB_ERR_PARSER, xml_parser_data::xml_error, and xml_parser_data::xml_parser.
Referenced by end_collation_rule(), and end_collation_x_rule().
static int common_collation_start_rule (void * data, const char ** attr, LOCALE_DATA * ld, TAILOR_RULE * t_rule) static
Definition at line 7922 of file locale_support.c.
References tailor_rule::anchor_buf, assert, locale_data::last_anchor_buf, locale_data::last_r_buf_p, locale_data::last_r_buf_size, locale_data::last_rule_pos_type, NULL, PRINT_DEBUG_START, tailor_rule::r_buf, tailor_rule::r_buf_size, RULE_POS_BUFFER, strlen, XML_CUB_OUT_OF_MEMORY, and xml_parser_data::xml_error.
Referenced by start_collation_rule(), and start_collation_x().
static int comp_func_coll_uca_exp (const void * arg1, const void * arg2) static
Definition at line 6609 of file locale_support.c.
References assert, coll_contraction::c_buf, coll_data::contr_list, dump_coll_data, intl_cp_to_utf8(), INTL_GET_NEXT_CONTR_ID, INTL_IS_NEXT_CONTR, INTL_UTF8_MAX_CHAR_SIZE, lang_strmatch_utf8_uca_w_coll_data(), NULL, and coll_contraction::size.
Referenced by comp_func_coll_uca_exp_fo(), and dump_locale_collation().
static int comp_func_coll_uca_exp_fo (const void * arg1, const void * arg2) static
Definition at line 6585 of file locale_support.c.
References cmp, and comp_func_coll_uca_exp().
Referenced by dump_locale_collation().
static int comp_func_coll_uca_simple_weights (const void * arg1, const void * arg2) static
Definition at line 6542 of file locale_support.c.
References assert, coll_data::contr_list, dump_coll_data, INTL_GET_NEXT_CONTR_ID, INTL_IS_NEXT_CONTR, NULL, coll_data::weights, and coll_contraction::wv.
Referenced by comp_func_coll_uca_simple_weights_fo(), and dump_locale_collation().
static int comp_func_coll_uca_simple_weights_fo (const void * arg1, const void * arg2) static
Definition at line 6518 of file locale_support.c.
References cmp, and comp_func_coll_uca_simple_weights().
Referenced by dump_locale_collation().
static int comp_func_parse_order_index (const void * arg1, const void * arg2) static
Definition at line 4201 of file locale_support.c.
References cmp, cmp_token_name_array, and cmp_token_name_size.
Referenced by locale_make_calendar_parse_order().
static void dump_collation_codepoint (COLL_DATA * coll, const unsigned int cp, bool print_weight, bool print_cp) static
Definition at line 6761 of file locale_support.c.
References assert, i, intl_cp_to_utf8(), INTL_MAX_UNICODE_CP_ALLOWED, INTL_UTF8_MAX_CHAR_SIZE, MAX_UCA_EXP_CE, uca_options::sett_strength, TAILOR_QUATERNARY, coll_data::uca_exp_num, UCA_GET_L1_W, UCA_GET_L2_W, UCA_GET_L3_W, coll_data::uca_num, coll_data::uca_opt, coll_data::uca_w_l13, coll_data::uca_w_l4, and coll_data::weights.
Referenced by dump_collation_key(), and dump_locale_collation().
static void dump_collation_contr (COLL_DATA * coll, const COLL_CONTRACTION * contr, bool print_weight, bool print_contr) static
Definition at line 6688 of file locale_support.c.
References assert, coll_contraction::c_buf, coll_contraction::cp_count, i, intl_utf8_to_cp_list(), LOC_MAX_UCA_CHARS_SEQ, MAX_UCA_EXP_CE, NULL, uca_options::sett_strength, strlen, TAILOR_QUATERNARY, coll_data::uca_exp_num, UCA_GET_L1_W, UCA_GET_L2_W, UCA_GET_L3_W, coll_contraction::uca_num, coll_data::uca_opt, coll_contraction::uca_w_l13, coll_contraction::uca_w_l4, and coll_contraction::wv.
Referenced by dump_collation_key(), and dump_locale_collation().
static void dump_collation_key (COLL_DATA * coll, const unsigned int key, bool print_weight, bool print_key) static
Definition at line 6664 of file locale_support.c.
References coll_data::contr_list, dump_collation_codepoint(), dump_collation_contr(), INTL_GET_NEXT_CONTR_ID, and INTL_IS_NEXT_CONTR.
Referenced by dump_locale_collation().
static int dump_console_conversion (TEXT_CONVERSION * tc) static
Definition at line 7193 of file locale_support.c.
References assert, text_conversion::byte_flag, conv_cp_to_bytes::bytes, text_conversion::conv_type, err, intl_cp_to_dbcs(), intl_cp_to_utf8(), intl_dbcs_to_cp(), intl_text_dbcs_to_utf8_ext(), intl_text_single_byte_to_utf8_ext(), INTL_UTF8_MAX_CHAR_SIZE, intl_utf8_to_cp(), text_conversion::nl_lang_str, NO_ERROR, NULL, conv_cp_to_bytes::size, TEXT_CONV_GENERIC_1BYTE, TEXT_CONV_GENERIC_2BYTE, TEXT_CONV_ISO_88591_BUILTIN, TEXT_CONV_ISO_88599_BUILTIN, TEXT_CONV_NO_CONVERSION, text_conversion::text_first_cp, text_conversion::text_last_cp, text_conversion::text_to_utf8, text_conversion::utf8_first_cp, text_conversion::utf8_last_cp, text_conversion::utf8_to_text, and text_conversion::win_codepages.
Referenced by locale_dump().
static int dump_locale_alphabet (ALPHABET_DATA * ad, int dl_settings, int lower_bound, int upper_bound) static
Definition at line 5956 of file locale_support.c.
References alphabet_data::a_type, ALPHABET_ASCII, ALPHABET_TAILORED, ALPHABET_UNICODE, assert, DUMP_CP_BUF_SIZE, DUMPLOCALE_IS_ALPHABET_LOWER, DUMPLOCALE_IS_ALPHABET_UPPER, i, intl_cp_to_utf8(), INTL_UTF8_MAX_CHAR_SIZE, alphabet_data::l_count, alphabet_data::lower_cp, alphabet_data::lower_multiplier, NO_ERROR, NULL, alphabet_data::upper_cp, and alphabet_data::upper_multiplier.
Referenced by locale_dump().
static int dump_locale_collation (COLL_DATA * coll, int dl_settings, int start_value, int end_value) static
Definition at line 6071 of file locale_support.c.
References assert, coll_data::checksum, coll_data::coll_id, coll_data::coll_name, comp_func_coll_uca_exp(), comp_func_coll_uca_exp_fo(), comp_func_coll_uca_simple_weights(), comp_func_coll_uca_simple_weights_fo(), coll_data::contr_list, coll_data::contr_min_size, coll_data::count_contr, dump_collation_codepoint(), dump_collation_contr(), dump_collation_key(), DUMPLOCALE_IS_COLLATION_CP_ORDER, DUMPLOCALE_IS_COLLATION_WEIGHT_ORDER, DUMPLOCALE_MSG_INVALID_CP_RANGE, ER_LOC_GEN, ER_LOC_INIT, i, INTL_MASK_CONTR, LOG_LOCALE_ERROR, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_SET_DUMPLOCALE, coll_contraction::next, coll_data::next_cp, NO_ERROR, NULL, uca_options::sett_expansions, uca_options::sett_strength, coll_data::uca_exp_num, coll_data::uca_opt, and coll_data::w_count.
Referenced by locale_dump_lib_collations().
static void dump_locale_normalization (UNICODE_NORMALIZATION * norm) static
Definition at line 7084 of file locale_support.c.
References assert, CP_HAS_MAPPINGS, dump_unicode_mapping(), GET_MAPPING_OFFSET, i, unicode_normalization::list_full_decomp, MAX_UNICODE_CHARS, NORM_MAPPING_DUMP_MODE_COMP, NORM_MAPPING_DUMP_MODE_DECOMP, NORM_MAPPING_DUMP_MODE_FULL, unicode_normalization::unicode_mapping_index, unicode_normalization::unicode_mappings, and unicode_normalization::unicode_mappings_count.
Referenced by locale_dump().
static void dump_unicode_mapping (UNICODE_MAPPING * um, const int mode) static
Definition at line 7150 of file locale_support.c.
References unicode_mapping::buffer, unicode_mapping::cp, INTL_UTF8_MAX_CHAR_SIZE, intl_utf8_to_cp(), NORM_MAPPING_DUMP_MODE_COMP, NORM_MAPPING_DUMP_MODE_FULL, NULL, and unicode_mapping::size.
Referenced by dump_locale_normalization().
static int end_case_rule (void * data, const char * el_name) static
Definition at line 3146 of file locale_support.c.
References locale_data::alpha_tailoring, assert, alphabet_tailoring::count_rules, transform_rule::dest, transform_rule::dest_size, intl_utf8_to_cp(), NULL, PRINT_DEBUG_END, alphabet_tailoring::rules, transform_rule::src, transform_rule::src_size, xml_parser_data::verbose, and XML_USER_DATA.
static int end_collation_cubrid_rule_set (void * data, const char * el_name) static
Definition at line 2307 of file locale_support.c.
References assert, coll_tailoring::cub_count_rules, ERR_MSG_SIZE, LOC_CURRENT_COLL_TAIL, NULL, PRINT_DEBUG_END, xml_parser_data::verbose, and XML_USER_DATA.
static int end_collation_cubrid_rule_set_cp_ch (void * data, const char * el_name) static
Definition at line 2346 of file locale_support.c.
References assert, BUF_TYPE_CHAR, BUF_TYPE_CODE, clear_data_buffer(), coll_tailoring::cub_count_rules, coll_tailoring::cub_rules, locale_data::data_buf_count, locale_data::data_buffer, cubrid_tailor_rule::end_cp_buf, cubrid_tailor_rule::end_cp_buf_type, ER_LOC_GEN, ERR_MSG_SIZE, LOC_CURRENT_COLL_TAIL, LOC_DATA_BUFF_SIZE, LOG_LOCALE_ERROR, NO_ERROR, NULL, PRINT_DEBUG_END, cubrid_tailor_rule::start_cp_buf, cubrid_tailor_rule::start_cp_buf_type, xml_parser_data::verbose, and XML_USER_DATA.
static int end_collation_cubrid_rule_set_ech_ecp (void * data, const char * el_name) static
Definition at line 2411 of file locale_support.c.
References assert, BUF_TYPE_CHAR, BUF_TYPE_CODE, clear_data_buffer(), coll_tailoring::cub_count_rules, coll_tailoring::cub_rules, locale_data::data_buf_count, locale_data::data_buffer, cubrid_tailor_rule::end_cp_buf, cubrid_tailor_rule::end_cp_buf_type, ER_LOC_GEN, ERR_MSG_SIZE, LOC_CURRENT_COLL_TAIL, LOC_DATA_BUFF_SIZE, LOG_LOCALE_ERROR, NO_ERROR, NULL, PRINT_DEBUG_END, xml_parser_data::verbose, and XML_USER_DATA.
static int end_collation_cubrid_rule_set_w_wr (void * data, const char * el_name) static
Definition at line 2469 of file locale_support.c.
References assert, clear_data_buffer(), coll_tailoring::cub_count_rules, coll_tailoring::cub_rules, locale_data::data_buf_count, locale_data::data_buffer, ER_LOC_GEN, ERR_MSG_SIZE, LOC_CURRENT_COLL_TAIL, LOC_DATA_BUFF_SIZE, LOG_LOCALE_ERROR, NO_ERROR, NULL, PRINT_DEBUG_END, cubrid_tailor_rule::start_weight, xml_parser_data::verbose, and XML_USER_DATA.
static int end_collation_logical_pos (void * data, const char * el_name) static
Definition at line 2970 of file locale_support.c.
References assert, locale_data::last_rule_pos_type, NULL, PRINT_DEBUG_END, RULE_POS_FIRST_NON_IGN, RULE_POS_FIRST_PRI_IGN, RULE_POS_FIRST_SEC_IGN, RULE_POS_FIRST_TERT_IGN, RULE_POS_FIRST_TRAIL, RULE_POS_FIRST_VAR, RULE_POS_LAST_NON_IGN, RULE_POS_LAST_PRI_IGN, RULE_POS_LAST_SEC_IGN, RULE_POS_LAST_TERT_IGN, RULE_POS_LAST_TRAIL, RULE_POS_LAST_VAR, XML_CUB_ERR_PARSER, xml_parser_data::xml_error, and XML_USER_DATA.
static int end_collation_reset (void * data, const char * el_name) static
Definition at line 2143 of file locale_support.c.
References assert, clear_data_buffer(), locale_data::data_buf_count, locale_data::data_buffer, locale_data::last_anchor_buf, LOC_DATA_COLL_TWO_CHARS, NULL, PRINT_DEBUG_END, and XML_USER_DATA.
static int end_collation_rule (void * data, const char * el_name) static
Definition at line 2582 of file locale_support.c.
References assert, common_collation_end_rule(), coll_tailoring::count_rules, tailor_rule::level, LOC_CURRENT_COLL_TAIL, tailor_rule::multiple_chars, NULL, PRINT_DEBUG_END, coll_tailoring::rules, TAILOR_IDENTITY, TAILOR_PRIMARY, TAILOR_SECONDARY, TAILOR_TERTIARY, XML_CUB_ERR_PARSER, xml_parser_data::xml_error, and XML_USER_DATA.
static int end_collation_x (void * data, const char * el_name) static
Definition at line 2709 of file locale_support.c.
References assert, coll_tailoring::count_rules, tailor_rule::direction, ERR_MSG_SIZE, locale_data::last_rule_dir, tailor_rule::level, LOC_CURRENT_COLL_TAIL, tailor_rule::multiple_chars, NULL, PRINT_DEBUG_END, tailor_rule::r_pos_type, coll_tailoring::rules, TAILOR_AFTER, xml_parser_data::verbose, and XML_USER_DATA.
static int end_collation_x_context (void * data, const char * el_name) static
Definition at line 2879 of file locale_support.c.
References assert, clear_data_buffer(), coll_tailoring::count_rules, locale_data::data_buf_count, locale_data::data_buffer, ERR_MSG_SIZE, LOC_CURRENT_COLL_TAIL, LOC_DATA_COLL_TWO_CHARS, NULL, PRINT_DEBUG_END, coll_tailoring::rules, strlen, tailor_rule::t_buf, tailor_rule::t_buf_size, xml_parser_data::verbose, XML_CUB_ERR_PARSER, XML_CUB_OUT_OF_MEMORY, xml_parser_data::xml_error, and XML_USER_DATA.
static int end_collation_x_extend (void * data, const char * el_name) static
Definition at line 2828 of file locale_support.c.
References assert, clear_data_buffer(), coll_tailoring::count_rules, locale_data::data_buf_count, locale_data::data_buffer, LOC_CURRENT_COLL_TAIL, NULL, PRINT_DEBUG_END, tailor_rule::r_buf, tailor_rule::r_buf_size, coll_tailoring::rules, XML_CUB_OUT_OF_MEMORY, xml_parser_data::xml_error, and XML_USER_DATA.
static int end_collation_x_rule (void * data, const char * el_name) static
Definition at line 2749 of file locale_support.c.
References assert, clear_data_buffer(), common_collation_end_rule(), coll_tailoring::count_rules, locale_data::data_buf_count, locale_data::data_buffer, tailor_rule::level, LOC_CURRENT_COLL_TAIL, NULL, PRINT_DEBUG_END, coll_tailoring::rules, strlen, tailor_rule::t_buf, tailor_rule::t_buf_size, TAILOR_IDENTITY, TAILOR_PRIMARY, TAILOR_SECONDARY, TAILOR_TERTIARY, XML_CUB_ERR_PARSER, XML_CUB_OUT_OF_MEMORY, xml_parser_data::xml_error, and XML_USER_DATA.
static int end_dateFormatCUBRID (void * data, const char * el_name) static
Definition at line 947 of file locale_support.c.
References assert, clear_data_buffer(), locale_data::data_buf_count, locale_data::data_buffer, locale_data::dateFormat, NULL, PRINT_DEBUG_END, and XML_USER_DATA.
static int end_datetimeFormatCUBRID (void * data, const char * el_name) static
Definition at line 1023 of file locale_support.c.
References assert, clear_data_buffer(), locale_data::data_buf_count, locale_data::data_buffer, locale_data::datetimeFormat, NULL, PRINT_DEBUG_END, and XML_USER_DATA.
static int end_datetimetzFormatCUBRID (void * data, const char * el_name) static
Definition at line 1137 of file locale_support.c.
References assert, clear_data_buffer(), locale_data::data_buf_count, locale_data::data_buffer, locale_data::datetimetzFormat, NULL, PRINT_DEBUG_END, and XML_USER_DATA.
static int end_day (void * data, const char * el_name) static
Definition at line 1463 of file locale_support.c.
References assert, CAL_DAY_COUNT, clear_data_buffer(), locale_data::curr_period, locale_data::data_buf_count, locale_data::data_buffer, locale_data::day_names_abbreviated, locale_data::day_names_wide, LOC_DATA_DAY_ABBR_SIZE, LOC_DATA_DAY_WIDE_SIZE, locale_data::name_type, NULL, PRINT_DEBUG_END, and XML_USER_DATA.
Referenced by db_months_between().
static int end_dayPeriod (void * data, const char * el_name) static
Definition at line 1596 of file locale_support.c.
References locale_data::am_pm, assert, CAL_AM_PM_COUNT, clear_data_buffer(), locale_data::curr_period, locale_data::data_buf_count, locale_data::data_buffer, LOC_DATA_AM_PM_SIZE, NULL, PRINT_DEBUG_END, and XML_USER_DATA.
static int end_element_ok (void * data, const char * el_name) static
Definition at line 910 of file locale_support.c.
References PRINT_DEBUG_END.
static int end_month (void * data, const char * el_name) static
Definition at line 1351 of file locale_support.c.
References assert, CAL_MONTH_COUNT, clear_data_buffer(), locale_data::curr_period, locale_data::data_buf_count, locale_data::data_buffer, LOC_DATA_MONTH_ABBR_SIZE, LOC_DATA_MONTH_WIDE_SIZE, locale_data::month_names_abbreviated, locale_data::month_names_wide, locale_data::name_type, NULL, PRINT_DEBUG_END, and XML_USER_DATA.
Referenced by db_months_between().
static int end_month_day_Width (void * data, const char * el_name) static
Definition at line 1280 of file locale_support.c.
References assert, locale_data::name_type, NULL, PRINT_DEBUG_END, and XML_USER_DATA.
static int end_number_symbol (void * data, const char * el_name) static
Definition at line 1665 of file locale_support.c.
References assert, clear_data_buffer(), locale_data::data_buf_count, locale_data::data_buffer, NULL, locale_data::number_decimal_sym, locale_data::number_group_sym, PRINT_DEBUG_END, and XML_USER_DATA.
static int end_one_collation (void * data, const char * el_name) static
Definition at line 1889 of file locale_support.c.
References assert, locale_data::coll_cnt, NULL, PRINT_DEBUG_END, and XML_USER_DATA.
static int end_timeFormatCUBRID (void * data, const char * el_name) static
Definition at line 985 of file locale_support.c.
References assert, clear_data_buffer(), locale_data::data_buf_count, locale_data::data_buffer, NULL, PRINT_DEBUG_END, locale_data::timeFormat, and XML_USER_DATA.
static int end_timestampFormatCUBRID (void * data, const char * el_name) static
Definition at line 1061 of file locale_support.c.
References assert, clear_data_buffer(), locale_data::data_buf_count, locale_data::data_buffer, NULL, PRINT_DEBUG_END, locale_data::timestampFormat, and XML_USER_DATA.
static int end_timestamptzFormatCUBRID (void * data, const char * el_name) static
Definition at line 1175 of file locale_support.c.
References assert, clear_data_buffer(), locale_data::data_buf_count, locale_data::data_buffer, NULL, PRINT_DEBUG_END, locale_data::timestamptzFormat, and XML_USER_DATA.
static int end_timetzFormatCUBRID (void * data, const char * el_name) static
Definition at line 1099 of file locale_support.c.
References assert, clear_data_buffer(), locale_data::data_buf_count, locale_data::data_buffer, NULL, PRINT_DEBUG_END, locale_data::timetzFormat, and XML_USER_DATA.
static int end_transform_buffer (void * data, const char * el_name) static
Definition at line 3225 of file locale_support.c.
References locale_data::alpha_tailoring, assert, clear_data_buffer(), alphabet_tailoring::count_rules, locale_data::data_buf_count, locale_data::data_buffer, transform_rule::dest, transform_rule::dest_size, alphabet_tailoring::max_rules, NULL, PRINT_DEBUG_END, alphabet_tailoring::rules, transform_rule::src, transform_rule::src_size, TR_LOWER, TR_UPPER, transform_rule::type, XML_CUB_ERR_PARSER, XML_CUB_OUT_OF_MEMORY, xml_parser_data::xml_error, and XML_USER_DATA.
static int handle_data (void * data, const char * s, int len) static
Definition at line 3414 of file locale_support.c.
References assert, locale_data::data_buf_count, locale_data::data_buffer, LOC_DATA_BUFF_SIZE, NULL, PRINT_DEBUG_DATA, xml_parser_data::verbose, XML_CUB_ERR_PARSER, xml_parser_data::xml_error, and XML_USER_DATA.
static int handle_data_collation_rule (void * data, const char * s, int len) static
Definition at line 2519 of file locale_support.c.
References assert, coll_tailoring::count_rules, ERR_MSG_SIZE, LOC_CURRENT_COLL_TAIL, NULL, PRINT_DEBUG_DATA, coll_tailoring::rules, tailor_rule::t_buf, tailor_rule::t_buf_size, xml_parser_data::verbose, XML_CUB_OUT_OF_MEMORY, xml_parser_data::xml_error, and XML_USER_DATA.
static int load_console_conv_data (LOCALE_DATA * ld, bool is_verbose) static
Definition at line 3898 of file locale_support.c.
References assert, text_conversion::byte_flag, conv_cp_to_bytes::bytes, char_isspace(), text_conversion_prm::conv_file, text_conversion::conv_type, text_conversion_prm::conv_type, envvar_codepagedir_file(), ER_LOC_GEN, ERR_MSG_SIZE, error(), fopen_ex(), i, intl_cp_to_dbcs(), intl_cp_to_utf8(), LOG_LOCALE_ERROR, text_conversion::nl_lang_str, text_conversion_prm::nl_lang_str, NO_ERROR, NULL, conv_cp_to_bytes::size, snprintf_dots_truncate, str_to_uint32(), strdup(), TEXT_CONV_GENERIC_1BYTE, TEXT_CONV_GENERIC_2BYTE, TEXT_CONV_ISO_88591_BUILTIN, TEXT_CONV_ISO_88599_BUILTIN, TEXT_CONV_NO_CONVERSION, TXT_CONV_ITEM::text_cp, text_conversion::text_first_cp, text_conversion::text_last_cp, text_conversion::text_to_utf8, locale_data::txt_conv, TXT_CONV_ITEM_GROW_COUNT, TXT_CONV_LINE_SIZE, locale_data::txt_conv_prm, TXT_CONV_ITEM::unicode_cp, text_conversion::utf8_first_cp, text_conversion::utf8_last_cp, text_conversion::utf8_to_text, text_conversion::win_codepages, and text_conversion_prm::win_codepages.
Referenced by locale_compile_locale().
static void locale_alloc_collation_id (COLL_TAILORING * coll_tail) static
Definition at line 3797 of file locale_support.c.
References char_isupper(), coll_tailoring::coll_id, coll_tailoring::coll_name, COLL_NAME_SIZE, ID_PER_RANGE, NULL, START_GENERIC_RANGE, START_LANG_RANGE, and strlen.
Referenced by locale_compile_locale().
static int locale_alphabet_data_size (ALPHABET_DATA * a) static
Definition at line 7580 of file locale_support.c.
References alphabet_data::a_type, alphabet_data::l_count, alphabet_data::lower_cp, alphabet_data::lower_multiplier, alphabet_data::upper_cp, and alphabet_data::upper_multiplier.
Referenced by locale_compute_locale_checksum().
static int locale_alphabet_data_to_buf (ALPHABET_DATA * a, char * buf) static
Definition at line 7601 of file locale_support.c.
References alphabet_data::a_type, BUF_PUT_INT32, CAST_BUFLEN, alphabet_data::l_count, alphabet_data::lower_cp, alphabet_data::lower_multiplier, alphabet_data::upper_cp, and alphabet_data::upper_multiplier.
Referenced by locale_compute_locale_checksum().
int locale_check_and_set_default_files (LOCALE_FILE * lf, bool is_lang_init)
Definition at line 5260 of file locale_support.c.
References assert, envvar_ldmldir_file(), envvar_libdir_file(), ER_LOC_GEN, ER_LOC_INIT, error(), fopen_ex(), locale_file::ldml_file, locale_file::lib_file, LOC_LOCALE_STR_SIZE, locale_file::locale_name, LOCLIB_FILE_EXT, LOG_LOCALE_ERROR, NO_ERROR, NULL, and strlen.
Referenced by dumplocale(), genlocale(), and init_user_locales().
static int locale_check_and_set_shared_data (const LOC_SHARED_DATA_TYPE lsd_type, const char * lsd_key, const void * data, LDML_CONTEXT * ldml_context, LOC_SHARED_DATA ** found_entry) static
Definition at line 6837 of file locale_support.c.
References alloced_shared_data, assert, COLL_NAME_SIZE, count_shared_data, LOC_SHARED_DATA::data, ER_LOC_GEN, i, LOC_SHARED_DATA::ldml_context, ldml_context::ldml_file, ldml_context::line_no, LOG_LOCALE_ERROR, LOC_SHARED_DATA::lsd_key, LOC_SHARED_DATA::lsd_type, NO_ERROR, NULL, SHARED_DATA_INCR_SIZE, and strdup().
Referenced by locale_compile_locale().
static int locale_check_collation_id (const COLL_TAILORING * coll_tail) static
Definition at line 3870 of file locale_support.c.
References assert, coll_tailoring::coll_id, coll_tailoring::coll_name, ER_LOC_GEN, ERR_MSG_SIZE, LANG_MAX_BUILTIN_COLLATIONS, LANG_MAX_COLLATIONS, LOG_LOCALE_ERROR, and NO_ERROR.
Referenced by locale_compile_locale().
int locale_compile_locale (LOCALE_FILE * lf, LOCALE_DATA * ld, bool is_verbose)
Definition at line 4557 of file locale_support.c.
References alphabet_data::a_type, locale_data::alpha_tailoring, locale_data::alphabet, ALPHABET_ASCII, ALPHABET_UNICODE, assert, coll_data::checksum, locale_data::checksum, locale_data::coll_cnt, coll_data::coll_id, coll_tailoring::coll_id, coll_data::coll_name, coll_tailoring::coll_name, COLL_NAME_SIZE, COLL_SHARED_DATA_SIZE, locale_data::collations, LOC_SHARED_DATA::data, locale_data::dateFormat, locale_data::datetimeFormat, locale_data::datetimetzFormat, alphabet_data::do_not_save, unicode_normalization::do_not_save, locale_collation::do_not_save, ER_LOC_GEN, ERR_MSG_SIZE, xml_parser_data::filepath, i, locale_data::identif_alphabet, intl_cp_to_utf8(), INTL_IDENTIFIER_CASING_SIZE_MULTIPLIER, INTL_UTF8_MAX_CHAR_SIZE, alphabet_data::l_count, lang_is_coll_name_allowed(), LOC_SHARED_DATA::ldml_context, coll_tailoring::ldml_context, alphabet_tailoring::ldml_context, locale_data::ldml_context, locale_file::ldml_file, ldml_context::ldml_file, ldml_context::line_no, load_console_conv_data(), LOC_SHARED_ALPHABET, LOC_SHARED_COLLATION, LOC_SHARED_NORMALIZATION, locale_alloc_collation_id(), locale_check_and_set_shared_data(), locale_check_collation_id(), locale_compute_coll_checksum(), locale_compute_locale_checksum(), locale_init_data(), locale_make_calendar_parse_order(), locale_file::locale_name, LOG_LOCALE_ERROR, alphabet_data::lower_cp, alphabet_data::lower_multiplier, MAX_UNICODE_CHARS, NO_ERROR, NULL, locale_collation::opt_coll, coll_tailoring::sett_max_cp, alphabet_tailoring::sett_max_letters, snprintf_dots_truncate, strdup(), locale_collation::tail_coll, locale_data::timeFormat, locale_data::timestampFormat, locale_data::timestamptzFormat, locale_data::timetzFormat, uca_free_data(), uca_process_collation(), xml_parser_data::ud, unicode_free_data(), locale_data::unicode_normalization, unicode_process_alphabet(), unicode_process_normalization(), alphabet_data::upper_cp, alphabet_data::upper_multiplier, xml_parser_data::verbose, coll_data::w_count, XML_CUB_NO_ERROR, xml_destroy_parser(), xml_parser_data::xml_error, xml_parser_data::xml_error_column, xml_parser_data::xml_error_line, xml_init_parser(), xml_parser_data::xml_parser, and xml_parser_exec().
Referenced by genlocale().
static int locale_compute_coll_checksum (COLL_DATA * cd) static
Definition at line 7424 of file locale_support.c.
References assert, BUF_ALIGN, BUF_PUT_INT16, BUF_PUT_INT32, coll_contraction::c_buf, coll_data::checksum, coll_data::contr_list, coll_data::contr_min_size, coll_data::count_contr, coll_contraction::cp_count, coll_data::cp_first_contr_count, coll_data::cp_first_contr_offset, crypt_md5_buffer_hex(), ER_LOC_GEN, LOG_LOCALE_ERROR, MAX_UCA_EXP_CE, coll_contraction::next, coll_data::next_cp, NO_ERROR, NULL, uca_options::sett_backwards, uca_options::sett_caseFirst, uca_options::sett_caseLevel, uca_options::sett_contr_policy, uca_options::sett_expansions, uca_options::sett_match_contr, uca_options::sett_strength, coll_contraction::size, TAILOR_QUATERNARY, coll_data::uca_exp_num, coll_contraction::uca_num, coll_data::uca_opt, coll_contraction::uca_w_l13, coll_data::uca_w_l13, coll_contraction::uca_w_l4, coll_data::uca_w_l4, uca_options::use_only_first_ce, coll_data::w_count, coll_data::weights, and coll_contraction::wv.
Referenced by locale_compile_locale().
static int locale_compute_locale_checksum (LOCALE_DATA * ld) static
Definition at line 7634 of file locale_support.c.
References locale_data::alphabet, locale_data::am_pm, locale_data::am_pm_parse_order, assert, BUF_PUT_INT32, unicode_mapping::buffer, text_conversion::byte_flag, locale_data::checksum, text_conversion::conv_type, unicode_mapping::cp, crypt_md5_buffer_hex(), locale_data::dateFormat, locale_data::datetimeFormat, locale_data::datetimetzFormat, locale_data::day_names_abbr_parse_order, locale_data::day_names_abbreviated, locale_data::day_names_wide, locale_data::day_names_wide_parse_order, locale_data::default_currency_code, unicode_normalization::do_not_save, ER_LOC_GEN, locale_data::identif_alphabet, unicode_normalization::list_full_decomp, locale_alphabet_data_size(), locale_alphabet_data_to_buf(), LOG_LOCALE_ERROR, MAX_UNICODE_CHARS, locale_data::month_names_abbr_parse_order, locale_data::month_names_abbreviated, locale_data::month_names_wide, locale_data::month_names_wide_parse_order, text_conversion::nl_lang_str, NO_ERROR, NULL, locale_data::number_decimal_sym, locale_data::number_group_sym, unicode_mapping::size, strlen, TEXT_CONV_GENERIC_1BYTE, TEXT_CONV_GENERIC_2BYTE, text_conversion::text_first_cp, text_conversion::text_last_cp, text_conversion::text_to_utf8, locale_data::timeFormat, locale_data::timestampFormat, locale_data::timestamptzFormat, locale_data::timetzFormat, locale_data::txt_conv, unicode_normalization::unicode_mapping_index, unicode_normalization::unicode_mappings, unicode_normalization::unicode_mappings_count, locale_data::unicode_normalization, text_conversion::utf8_first_cp, text_conversion::utf8_last_cp, text_conversion::utf8_to_text, and text_conversion::win_codepages.
Referenced by locale_compile_locale().
void locale_destroy_alphabet_data (const ALPHABET_DATA * a)
Definition at line 4341 of file locale_support.c.
References assert, alphabet_data::lower_cp, NULL, and alphabet_data::upper_cp.
Referenced by locale_destroy_data().
static void locale_destroy_alphabet_tailoring (const ALPHABET_TAILORING * cd) static
Definition at line 4470 of file locale_support.c.
References assert, alphabet_tailoring::count_rules, transform_rule::dest, transform_rule::dest_size, i, alphabet_tailoring::ldml_context, ldml_context::ldml_file, alphabet_tailoring::max_rules, NULL, alphabet_tailoring::rules, transform_rule::src, and transform_rule::src_size.
Referenced by locale_destroy_data().
static void locale_destroy_collation_data (const COLL_DATA * cd) static
Definition at line 4420 of file locale_support.c.
References assert, coll_data::contr_list, coll_data::cp_first_contr_array, coll_data::next_cp, NULL, coll_data::uca_num, coll_data::uca_w_l13, coll_data::uca_w_l4, and coll_data::weights.
Referenced by locale_destroy_data().
static void locale_destroy_collation_tailorings (const COLL_TAILORING * ct) static
Definition at line 4365 of file locale_support.c.
References assert, coll_tailoring::count_rules, coll_tailoring::cub_max_rules, coll_tailoring::cub_rules, i, coll_tailoring::ldml_context, ldml_context::ldml_file, coll_tailoring::max_rules, NULL, tailor_rule::r_buf, tailor_rule::r_buf_size, coll_tailoring::rules, tailor_rule::t_buf, and tailor_rule::t_buf_size.
Referenced by locale_destroy_data().
static void locale_destroy_console_conversion (const TEXT_CONVERSION * tc) static
Definition at line 4520 of file locale_support.c.
References assert, text_conversion::nl_lang_str, NULL, text_conversion::text_to_utf8, text_conversion::utf8_to_text, and text_conversion::win_codepages.
Referenced by locale_destroy_data().
void locale_destroy_data (LOCALE_DATA * ld)
Definition at line 4298 of file locale_support.c.
References locale_data::alpha_tailoring, locale_data::alphabet, assert, locale_data::coll_cnt, locale_data::collations, i, locale_data::identif_alphabet, locale_data::ldml_context, ldml_context::ldml_file, locale_destroy_alphabet_data(), locale_destroy_alphabet_tailoring(), locale_destroy_collation_data(), locale_destroy_collation_tailorings(), locale_destroy_console_conversion(), locale_destroy_normalization_data(), NULL, locale_collation::opt_coll, locale_collation::tail_coll, locale_data::txt_conv, and locale_data::unicode_normalization.
Referenced by genlocale().
void locale_destroy_normalization_data (UNICODE_NORMALIZATION * norm)
Definition at line 7000 of file locale_support.c.
References unicode_normalization::list_full_decomp, NULL, unicode_normalization::unicode_mapping_index, and unicode_normalization::unicode_mappings.
Referenced by locale_destroy_data().
int locale_dump (void * data, LOCALE_FILE * lf, int dl_settings, int start_value, int end_value)
Definition at line 6269 of file locale_support.c.
References lang_locale_data::alphabet, lang_locale_data::am_pm, lang_locale_data::am_pm_parse_order, assert, CAL_AM_PM_COUNT, CAL_DAY_COUNT, CAL_MONTH_COUNT, lang_locale_data::checksum, lang_locale_data::date_format, lang_locale_data::datetime_format, lang_locale_data::datetimetz_format, lang_locale_data::day_name, lang_locale_data::day_parse_order, lang_locale_data::day_short_name, lang_locale_data::day_short_parse_order, lang_locale_data::default_currency_code, dump_console_conversion(), dump_locale_alphabet(), dump_locale_normalization(), DUMPLOCALE_IS_ALPHABET, DUMPLOCALE_IS_ALPHABET_LOWER, DUMPLOCALE_IS_ALPHABET_UPPER, DUMPLOCALE_IS_CALENDAR, DUMPLOCALE_IS_IDENTIFIER_ALPHABET, DUMPLOCALE_IS_IDENTIFIER_ALPHABET_LOWER, DUMPLOCALE_IS_IDENTIFIER_ALPHABET_UPPER, DUMPLOCALE_IS_NORMALIZATION, DUMPLOCALE_IS_NUMBERING, DUMPLOCALE_IS_TEXT_CONV, DUMPLOCALE_MSG_INVALID_CP_RANGE, ER_LOC_GEN, i, lang_locale_data::ident_alphabet, intl_get_money_ISO_symbol(), alphabet_data::l_count, lang_locale_data::lang_name, locale_file::lib_file, locale_file::locale_name, LOG_LOCALE_ERROR, lang_locale_data::month_name, lang_locale_data::month_parse_order, lang_locale_data::month_short_name, lang_locale_data::month_short_parse_order, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_SET_DUMPLOCALE, NO_ERROR, NULL, lang_locale_data::number_decimal_sym, lang_locale_data::number_group_sym, lang_locale_data::time_format, lang_locale_data::timestamp_format, lang_locale_data::timestamptz_format, lang_locale_data::txt_conv, and lang_locale_data::unicode_norm.
Referenced by dumplocale().
int locale_dump_lib_collations (void * lib_handle, const LOCALE_FILE * lf, int dl_settings, int start_value, int end_value)
Definition at line 6454 of file locale_support.c.
References assert, coll_data::coll_name, dump_locale_collation(), i, lang_load_coll_from_lib(), lang_load_count_coll_from_lib(), lang_load_get_coll_name_from_lib(), locale_file::locale_name, NO_ERROR, NULL, and strlen.
Referenced by dumplocale().
void locale_free_shared_data (void)
Definition at line 6921 of file locale_support.c.
References alloced_shared_data, assert, count_shared_data, LOC_SHARED_DATA::data, i, LOC_SHARED_DATA::ldml_context, ldml_context::ldml_file, and NULL.
Referenced by genlocale().
int locale_get_cfg_locales (LOCALE_FILE ** p_locale_files, int * p_num_locales, bool is_lang_init)
Definition at line 5126 of file locale_support.c.
References assert, char_isspace(), envvar_confdir_file(), ER_LOC_GEN, ER_LOC_INIT, ERR_MSG_SIZE, fopen_ex(), locale_file::ldml_file, locale_file::lib_file, locale_file::locale_name, LOG_LOCALE_ERROR, NO_ERROR, NULL, snprintf_dots_truncate, and str_pop_token().
Referenced by dumplocale(), genlocale(), and init_user_locales().
void locale_init_data (LOCALE_DATA * ld, const char * locale_name)
Definition at line 4275 of file locale_support.c.
References locale_data::alpha_tailoring, assert, locale_data::curr_period, DB_CURRENCY_NULL, locale_data::default_currency_code, locale_data::locale_name, locale_data::number_decimal_sym, locale_data::number_group_sym, alphabet_tailoring::sett_max_letters, and strlen.
Referenced by locale_compile_locale().
static void locale_make_calendar_parse_order (LOCALE_DATA * ld) static
Definition at line 4228 of file locale_support.c.
References locale_data::am_pm, locale_data::am_pm_parse_order, CAL_AM_PM_COUNT, CAL_DAY_COUNT, CAL_MONTH_COUNT, cmp_token_name_array, cmp_token_name_size, comp_func_parse_order_index(), locale_data::day_names_abbr_parse_order, locale_data::day_names_abbreviated, locale_data::day_names_wide, locale_data::day_names_wide_parse_order, i, LOC_DATA_AM_PM_SIZE, LOC_DATA_DAY_ABBR_SIZE, LOC_DATA_DAY_WIDE_SIZE, LOC_DATA_MONTH_ABBR_SIZE, LOC_DATA_MONTH_WIDE_SIZE, locale_data::month_names_abbr_parse_order, locale_data::month_names_abbreviated, locale_data::month_names_wide, and locale_data::month_names_wide_parse_order.
Referenced by locale_compile_locale().
void locale_mark_duplicate_collations (LOCALE_DATA ** ld, int start_index, int end_index, bool is_verbose)
Definition at line 4952 of file locale_support.c.
References locale_data::coll_cnt, coll_data_ref::coll_contr_list_ref, coll_data_ref::coll_cp_first_contr_array_ref, coll_data::coll_name, coll_data_ref::coll_next_cp_ref, locale_collation::coll_ref, coll_data_ref::coll_uca_num_ref, coll_data_ref::coll_uca_w_l13_ref, coll_data_ref::coll_uca_w_l4_ref, coll_data_ref::coll_weights_ref, locale_data::collations, coll_data::contr_list, coll_data::contr_min_size, coll_data::count_contr, coll_data::cp_first_contr_array, coll_data::cp_first_contr_count, coll_data::cp_first_contr_offset, coll_data::next_cp, locale_collation::opt_coll, PRINT_DUPLICATE_SYMBOL_NAME, uca_options::sett_expansions, uca_options::sett_strength, TAILOR_QUATERNARY, coll_data::uca_exp_num, coll_data::uca_num, coll_data::uca_opt, coll_data::uca_w_l13, coll_data::uca_w_l4, coll_data::w_count, and coll_data::weights.
Referenced by genlocale().
int locale_prepare_C_file (void)
Definition at line 5427 of file locale_support.c.
References envvar_loclib_dir_file(), ER_GENERIC_ERROR, ER_LOC_GEN, ERR_MSG_SIZE, error(), fopen_ex(), LOG_LOCALE_ERROR, NULL, and snprintf_dots_truncate.
Referenced by genlocale().
int locale_save_all_to_C_file (LOCALE_DATA ** ld, int start_index, int end_index, LOCALE_FILE * lf)
Definition at line 5096 of file locale_support.c.
References i, locale_save_to_C_file(), and NO_ERROR.
Referenced by genlocale().
static int locale_save_alphabets_to_C_file (FILE * fp, LOCALE_DATA * ld) static
Definition at line 5631 of file locale_support.c.
References alphabet_data::a_type, locale_data::alphabet, ALPHABET_ASCII, ALPHABET_UNICODE, assert, alphabet_data::do_not_save, locale_data::identif_alphabet, locale_data::locale_name, locale_save_one_alphabet_to_C_file(), NULL, and PRINT_VAR_TO_C_FILE.
Referenced by locale_save_to_C_file().
static int locale_save_calendar_to_C_file (FILE * fp, LOCALE_DATA * ld) static
Definition at line 5541 of file locale_support.c.
References locale_data::am_pm, locale_data::am_pm_parse_order, assert, CAL_AM_PM_COUNT, CAL_DAY_COUNT, CAL_MONTH_COUNT, locale_data::dateFormat, locale_data::datetimeFormat, locale_data::datetimetzFormat, locale_data::day_names_abbr_parse_order, locale_data::day_names_abbreviated, locale_data::day_names_wide, locale_data::day_names_wide_parse_order, locale_data::locale_name, locale_data::month_names_abbr_parse_order, locale_data::month_names_abbreviated, locale_data::month_names_wide, locale_data::month_names_wide_parse_order, NULL, PRINT_NUM_ARRAY_TO_C_FILE, PRINT_STRING_ARRAY_TO_C_FILE, PRINT_STRING_VAR_TO_C_FILE, locale_data::timeFormat, locale_data::timestampFormat, locale_data::timestamptzFormat, and locale_data::timetzFormat.
Referenced by locale_save_to_C_file().
static int locale_save_collation_data_to_C_file (FILE * fp, LOCALE_COLLATION * lc) static
Definition at line 5697 of file locale_support.c.
References assert, coll_data::checksum, coll_data_ref::coll_contr_list_ref, coll_data_ref::coll_cp_first_contr_array_ref, coll_data::coll_id, coll_data::coll_name, coll_data_ref::coll_next_cp_ref, locale_collation::coll_ref, coll_data_ref::coll_uca_num_ref, coll_data_ref::coll_uca_w_l13_ref, coll_data_ref::coll_uca_w_l4_ref, coll_data_ref::coll_weights_ref, coll_data::contr_list, coll_data::contr_min_size, coll_data::count_contr, coll_data::cp_first_contr_array, coll_data::cp_first_contr_count, coll_data::cp_first_contr_offset, DLL_EXPORT_PREFIX, i, coll_data::next_cp, NULL, locale_collation::opt_coll, PRINT_NUM_ARRAY_TO_C_FILE, PRINT_STRING_VAR_TO_C_FILE, PRINT_VAR_TO_C_FILE, save_contraction_to_C_file(), uca_options::sett_backwards, uca_options::sett_caseFirst, uca_options::sett_caseLevel, uca_options::sett_contr_policy, uca_options::sett_expansions, uca_options::sett_match_contr, uca_options::sett_strength, TAILOR_QUATERNARY, coll_data::uca_exp_num, coll_data::uca_num, coll_data::uca_opt, coll_data::uca_w_l13, coll_data::uca_w_l4, coll_data::w_count, and coll_data::weights.
Referenced by locale_save_to_C_file().
static int locale_save_console_conv_to_C_file (FILE * fp, LOCALE_DATA * ld) static
Definition at line 5827 of file locale_support.c.
References assert, text_conversion::byte_flag, conv_cp_to_bytes::bytes, text_conversion::conv_type, DLL_EXPORT_PREFIX, i, locale_data::locale_name, text_conversion::nl_lang_str, NULL, PRINT_NUM_ARRAY_TO_C_FILE, PRINT_STRING_TO_C_FILE, PRINT_STRING_VAR_TO_C_FILE, PRINT_VAR_TO_C_FILE, conv_cp_to_bytes::size, TEXT_CONV_GENERIC_1BYTE, TEXT_CONV_GENERIC_2BYTE, text_conversion::text_first_cp, text_conversion::text_last_cp, text_conversion::text_to_utf8, locale_data::txt_conv, text_conversion::utf8_first_cp, text_conversion::utf8_last_cp, text_conversion::utf8_to_text, and text_conversion::win_codepages.
Referenced by locale_save_to_C_file().
static int locale_save_normalization_to_C_file (FILE * fp, LOCALE_DATA * ld) static
Definition at line 7035 of file locale_support.c.
References assert, unicode_mapping::buffer, unicode_mapping::cp, DLL_EXPORT_PREFIX, unicode_normalization::do_not_save, i, unicode_normalization::list_full_decomp, MAX_UNICODE_CHARS, NULL, PRINT_NUM_ARRAY_TO_C_FILE, PRINT_STRING_TO_C_FILE, PRINT_VAR_TO_C_FILE, unicode_mapping::size, unicode_normalization::unicode_mapping_index, unicode_normalization::unicode_mappings, unicode_normalization::unicode_mappings_count, locale_data::unicode_normalization, and UNICODE_NORMALIZATION_DECORATOR.
Referenced by locale_save_to_C_file().
static int locale_save_one_alphabet_to_C_file (FILE * fp, ALPHABET_DATA * a, bool save_w_identier_name, const char * alpha_suffix) static
Definition at line 5591 of file locale_support.c.
References assert, alphabet_data::l_count, alphabet_data::lower_cp, alphabet_data::lower_multiplier, NULL, PRINT_NUM_ARRAY_TO_C_FILE, PRINT_VAR_TO_C_FILE, alphabet_data::upper_cp, and alphabet_data::upper_multiplier.
Referenced by locale_save_alphabets_to_C_file().
static int locale_save_to_C_file (LOCALE_FILE lf, LOCALE_DATA * ld) static
Definition at line 5466 of file locale_support.c.
References assert, locale_data::checksum, locale_data::coll_cnt, coll_data::coll_name, locale_data::collations, locale_data::default_currency_code, locale_collation::do_not_save, envvar_loclib_dir_file(), ER_GENERIC_ERROR, ER_LOC_GEN, ERR_MSG_SIZE, error(), fopen_ex(), i, locale_file::ldml_file, locale_data::locale_name, locale_save_alphabets_to_C_file(), locale_save_calendar_to_C_file(), locale_save_collation_data_to_C_file(), locale_save_console_conv_to_C_file(), locale_save_normalization_to_C_file(), LOG_LOCALE_ERROR, NULL, locale_data::number_decimal_sym, locale_data::number_group_sym, locale_collation::opt_coll, PRINT_STRING_VAR_TO_C_FILE, PRINT_VAR_TO_C_FILE, and snprintf_dots_truncate.
Referenced by locale_save_all_to_C_file().
static CUBRID_TAILOR_RULE * new_collation_cubrid_rule (LOCALE_DATA * ld) static
Definition at line 3602 of file locale_support.c.
References assert, coll_tailoring::cub_count_rules, coll_tailoring::cub_max_rules, coll_tailoring::cub_rules, LOC_CURRENT_COLL_TAIL, LOC_DATA_COLL_CUBRID_TAILOR_COUNT_GROW, coll_tailoring::max_rules, and NULL.
Referenced by start_collation_cubrid_rule().
static TAILOR_RULE * new_collation_rule (LOCALE_DATA * ld) static
Definition at line 3522 of file locale_support.c.
References assert, coll_tailoring::count_rules, LOC_CURRENT_COLL_TAIL, LOC_DATA_TAILOR_RULES_COUNT_GROW, coll_tailoring::max_rules, NULL, and coll_tailoring::rules.
Referenced by start_collation_rule(), and start_collation_x().
static LOCALE_COLLATION * new_locale_collation (LOCALE_DATA * ld) static
Definition at line 3488 of file locale_support.c.
References assert, locale_data::coll_cnt, locale_data::collations, CONTR_IGNORE, NULL, uca_options::sett_contr_policy, coll_tailoring::sett_max_cp, locale_collation::tail_coll, and coll_tailoring::uca_opt.
Referenced by start_one_collation().
static TRANSFORM_RULE * new_transform_rule (LOCALE_DATA * ld) static
Definition at line 3563 of file locale_support.c.
References locale_data::alpha_tailoring, assert, alphabet_tailoring::count_rules, LOC_DATA_TAILOR_RULES_COUNT_GROW, alphabet_tailoring::max_rules, NULL, and alphabet_tailoring::rules.
Referenced by start_lower_case_rule(), and start_upper_case_rule().
static void print_debug_data_content (void * data, const char * msg, const int status) static
Definition at line 3751 of file locale_support.c.
References assert, xml_parser_data::ce, xml_element::def, xml_element_def::depth, i, NULL, xml_parser_data::verbose, XML_COMMENT_END, and XML_COMMENT_START.
static void print_debug_end_el (void * data, const char * msg, const int status) static
Definition at line 3703 of file locale_support.c.
References assert, xml_parser_data::ce, xml_element::def, xml_element_def::depth, i, NULL, xml_element::short_name, xml_parser_data::verbose, XML_COMMENT_END, and XML_COMMENT_START.
static void print_debug_start_el (void * data, const char ** attrs, const char * msg, const int status) static
Definition at line 3645 of file locale_support.c.
References assert, xml_parser_data::ce, xml_element::def, xml_element_def::depth, i, NULL, xml_element::short_name, xml_parser_data::verbose, XML_COMMENT_END, and XML_COMMENT_START.
static int save_contraction_to_C_file (FILE * fp, COLL_CONTRACTION * c, bool use_expansion, bool use_level_4) static
Definition at line 5374 of file locale_support.c.
References assert, coll_contraction::c_buf, coll_contraction::cp_count, MAX_UCA_EXP_CE, coll_contraction::next, NULL, PRINT_STRING_TO_C_FILE, PRINT_UNNAMED_NUM_ARRAY_TO_C_FILE, coll_contraction::size, strlen, coll_contraction::uca_num, coll_contraction::uca_w_l13, coll_contraction::uca_w_l4, and coll_contraction::wv.
Referenced by locale_save_collation_data_to_C_file().
static int start_calendar (void * data, const char ** attr) static
Definition at line 926 of file locale_support.c.
References PRINT_DEBUG_START, and xml_check_att_value().
static int start_calendar_name_context (void * data, const char ** attr) static
Definition at line 1214 of file locale_support.c.
References assert, NULL, PRINT_DEBUG_START, xml_check_att_value(), and XML_USER_DATA.
static int start_collation_cubrid_rule (void * data, const char ** attr) static
Definition at line 2228 of file locale_support.c.
References assert, clear_data_buffer(), new_collation_cubrid_rule(), NULL, PRINT_DEBUG_START, XML_CUB_OUT_OF_MEMORY, xml_parser_data::xml_error, and XML_USER_DATA.
static int start_collation_cubrid_rule_set_wr (void * data, const char ** attr) static
Definition at line 2262 of file locale_support.c.
References assert, coll_tailoring::cub_count_rules, coll_tailoring::cub_rules, ER_LOC_GEN, LOC_CURRENT_COLL_TAIL, LOG_LOCALE_ERROR, MAX_STRLEN_FOR_COLLATION_ELEMENT, NO_ERROR, NULL, PRINT_DEBUG_START, cubrid_tailor_rule::step, strlen, xml_get_att_value(), and XML_USER_DATA.
static int start_collation_logical_pos (void * data, const char ** attr) static
Definition at line 2948 of file locale_support.c.
References assert, NULL, PRINT_DEBUG_START, and XML_USER_DATA.
static int start_collation_reset (void * data, const char ** attr) static
Definition at line 2083 of file locale_support.c.
References assert, locale_data::last_anchor_buf, locale_data::last_r_buf_p, locale_data::last_r_buf_size, locale_data::last_rule_dir, locale_data::last_rule_level, locale_data::last_rule_pos_type, NULL, PRINT_DEBUG_START, RULE_POS_BUFFER, TAILOR_AFTER, TAILOR_BEFORE, TAILOR_PRIMARY, TAILOR_QUATERNARY, TAILOR_SECONDARY, TAILOR_TERTIARY, TAILOR_UNDEFINED, xml_get_att_value(), and XML_USER_DATA.
static int start_collation_rule (void * data, const char ** attr) static
Definition at line 2178 of file locale_support.c.
References assert, common_collation_start_rule(), locale_data::last_rule_pos_type, new_collation_rule(), NULL, PRINT_DEBUG_START, tailor_rule::r_buf, tailor_rule::r_buf_size, RULE_POS_BUFFER, XML_CUB_OUT_OF_MEMORY, xml_parser_data::xml_error, and XML_USER_DATA.
static int start_collation_settings (void * data, const char ** attr) static
Definition at line 1914 of file locale_support.c.
References assert, coll_tailoring::coll_id, coll_tailoring::coll_name, CONTR_DUCET_USE, CONTR_TAILORING_USE, ER_LOC_GEN, ERR_MSG_SIZE, LANG_MAX_BUILTIN_COLLATIONS, LANG_MAX_COLLATIONS, locale_data::ldml_context, ldml_context::ldml_file, LOC_CURRENT_COLL_TAIL, LOG_LOCALE_ERROR, MATCH_CONTR_BOUND_ALLOW, NULL, PRINT_DEBUG_START, uca_options::sett_backwards, uca_options::sett_caseFirst, uca_options::sett_caseLevel, uca_options::sett_contr_policy, uca_options::sett_expansions, uca_options::sett_match_contr, coll_tailoring::sett_max_cp, uca_options::sett_strength, TAILOR_IDENTITY, TAILOR_PRIMARY, TAILOR_QUATERNARY, TAILOR_SECONDARY, TAILOR_TERTIARY, coll_tailoring::uca_opt, xml_get_att_value(), xml_parser_data::xml_parser, and XML_USER_DATA.
static int start_collation_x (void * data, const char ** attr) static
Definition at line 2663 of file locale_support.c.
References assert, common_collation_start_rule(), locale_data::last_rule_pos_type, new_collation_rule(), NULL, PRINT_DEBUG_START, RULE_POS_BUFFER, XML_CUB_ERR_PARSER, XML_CUB_OUT_OF_MEMORY, xml_parser_data::xml_error, and XML_USER_DATA.
static int start_collations (void * data, const char ** attr) static
Definition at line 1762 of file locale_support.c.
References assert, char_isspace(), locale_data::locale_name, NULL, PRINT_DEBUG_START, strlen, xml_get_att_value(), and XML_USER_DATA.
static int start_consoleconversion (void * data, const char ** attr) static
Definition at line 3313 of file locale_support.c.
References assert, text_conversion_prm::conv_file, text_conversion_prm::conv_type, text_conversion_prm::nl_lang_str, NULL, PRINT_DEBUG_START, strlen, TEXT_CONV_GENERIC_1BYTE, TEXT_CONV_GENERIC_2BYTE, TEXT_CONV_ISO_88591_BUILTIN, TEXT_CONV_ISO_88599_BUILTIN, locale_data::txt_conv_prm, text_conversion_prm::win_codepages, xml_get_att_value(), and XML_USER_DATA.
static int start_currency (void * data, const char ** attr) static
Definition at line 1708 of file locale_support.c.
References assert, CURRENCY_CHECK_MODE_ISO, DB_CURRENCY_NULL, locale_data::default_currency_code, intl_is_currency_symbol(), LOC_DATA_CURRENCY_ISO_CODE_LEN, NULL, PRINT_DEBUG_START, strlen, xml_get_att_value(), and XML_USER_DATA.
static int start_day (void * data, const char ** attr) static
Definition at line 1411 of file locale_support.c.
References assert, CAL_DAY_COUNT, locale_data::curr_period, i, ldml_ref_day_names, NULL, PRINT_DEBUG_START, xml_get_att_value(), and XML_USER_DATA.
Referenced by db_months_between().
static int start_dayPeriod (void * data, const char ** attr) static
Definition at line 1544 of file locale_support.c.
References assert, CAL_AM_PM_COUNT, locale_data::curr_period, i, ldml_ref_am_pm_names, NULL, PRINT_DEBUG_START, xml_get_att_value(), and XML_USER_DATA.
static int start_dayPeriodWidth (void * data, const char ** attr) static
Definition at line 1522 of file locale_support.c.
References PRINT_DEBUG_START, and xml_check_att_value().
static int start_element_ok (void * data, const char ** attr) static
Definition at line 890 of file locale_support.c.
References PRINT_DEBUG_START.
static int start_include_collation (void * data, const char ** attr) static
Definition at line 7974 of file locale_support.c.
References assert, envvar_ldmldir_file(), ER_LOC_GEN, ERR_MSG_SIZE, xml_parser_data::filepath, locale_data::ldml_context, ldml_context::ldml_file, ldml_context::line_no, LOG_LOCALE_ERROR, xml_parser_data::next, NULL, PRINT_DEBUG_START, snprintf_dots_truncate, strdup(), xml_create_subparser(), XML_CUB_ERR_FILE_MISSING, XML_CUB_ERR_INCLUDE_LOOP, XML_CUB_ERR_PARSER_INIT_FAIL, XML_CUB_NO_ERROR, XML_CUB_OUT_OF_MEMORY, xml_destroy_parser_data(), xml_parser_data::xml_error, xml_parser_data::xml_error_column, xml_parser_data::xml_error_line, xml_get_att_value(), xml_parser_data::xml_parser, xml_parser_exec(), and XML_USER_DATA.
static int start_lower_case_rule (void * data, const char ** attr) static
Definition at line 3191 of file locale_support.c.
References assert, new_transform_rule(), NULL, PRINT_DEBUG_START, TR_LOWER, transform_rule::type, XML_CUB_OUT_OF_MEMORY, xml_parser_data::xml_error, and XML_USER_DATA.
static int start_month (void * data, const char ** attr) static
Definition at line 1307 of file locale_support.c.
References assert, CAL_MONTH_COUNT, locale_data::curr_period, NULL, PRINT_DEBUG_START, xml_get_att_value(), and XML_USER_DATA.
Referenced by db_months_between().
static int start_month_day_Width (void * data, const char ** attr) static
Definition at line 1243 of file locale_support.c.
References assert, locale_data::name_type, NULL, PRINT_DEBUG_START, xml_check_att_value(), and XML_USER_DATA.
static int start_numbers_symbols (void * data, const char ** attr) static
Definition at line 1637 of file locale_support.c.
References assert, NULL, PRINT_DEBUG_START, xml_check_att_value(), and XML_USER_DATA.
static int start_one_alphabet (void * data, const char ** attr) static
Definition at line 3051 of file locale_support.c.
References locale_data::alpha_tailoring, alphabet_tailoring::alphabet_mode, assert, alphabet_tailoring::count_rules, alphabet_tailoring::ldml_context, locale_data::ldml_context, ldml_context::ldml_file, ldml_context::line_no, NULL, PRINT_DEBUG_START, alphabet_tailoring::sett_max_letters, strdup(), xml_get_att_value(), xml_parser_data::xml_parser, and XML_USER_DATA.
static int start_one_collation (void * data, const char ** attr) static
Definition at line 1839 of file locale_support.c.
References assert, coll_tailoring::coll_name, COLL_NAME_SIZE, coll_tailoring::ldml_context, locale_data::ldml_context, ldml_context::ldml_file, ldml_context::line_no, new_locale_collation(), NULL, PRINT_DEBUG_START, uca_options::sett_caseFirst, uca_options::sett_strength, strdup(), locale_collation::tail_coll, TAILOR_QUATERNARY, coll_tailoring::uca_opt, XML_CUB_OUT_OF_MEMORY, xml_parser_data::xml_error, xml_get_att_value(), xml_parser_data::xml_parser, and XML_USER_DATA.
static int start_unicode_file (void * data, const char ** attr) static
Definition at line 6961 of file locale_support.c.
References locale_data::alpha_tailoring, alphabet_tailoring::alphabet_mode, assert, NULL, PRINT_DEBUG_START, strlen, locale_data::unicode_data_file, locale_data::unicode_mode, xml_get_att_value(), and XML_USER_DATA.
static int start_upper_case_rule (void * data, const char ** attr) static
Definition at line 3112 of file locale_support.c.
References assert, new_transform_rule(), NULL, PRINT_DEBUG_START, TR_UPPER, transform_rule::type, XML_CUB_OUT_OF_MEMORY, xml_parser_data::xml_error, and XML_USER_DATA.
static int str_pop_token (char * str_p, char ** token_p, char ** next_p) static
Definition at line 5899 of file locale_support.c.
References assert, char_isspace(), ER_LOC_INIT, LOG_LOCALE_ERROR, NO_ERROR, NULL, and p.
Referenced by locale_get_cfg_locales().
Variable Documentation
int alloced_shared_data = 0 static
Definition at line 94 of file locale_support.c.
Referenced by locale_check_and_set_shared_data(), and locale_free_shared_data().
char* cmp_token_name_array = NULL static
Definition at line 332 of file locale_support.c.
Referenced by comp_func_parse_order_index(), and locale_make_calendar_parse_order().
char cmp_token_name_size = 0 static
Definition at line 333 of file locale_support.c.
Referenced by comp_func_parse_order_index(), and locale_make_calendar_parse_order().
int count_shared_data = 0 static
Definition at line 93 of file locale_support.c.
Referenced by locale_check_and_set_shared_data(), and locale_free_shared_data().
COLL_DATA* dump_coll_data = NULL static
Definition at line 330 of file locale_support.c.
Referenced by comp_func_coll_uca_exp(), and comp_func_coll_uca_simple_weights().
XML_ELEMENT_DEF ldml_datetimeFormatCUBRID
Initial value:
= { "ldml dates calendars calendar datetimeFormatCUBRID", 5,
  (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_datetimeFormatCUBRID), (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 366 of file locale_support.c.
XML_ELEMENT_DEF ldml_datetimetzFormatCUBRID
Initial value:
= { "ldml dates calendars calendar datetimetzFormatCUBRID", 5,
  (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_datetimetzFormatCUBRID),
  (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 383 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_alphabet
Initial value:
= { "ldml alphabets alphabet", 3, (ELEM_START_FUNC) (&start_one_alphabet),
  (ELEM_END_FUNC) (&end_element_ok), NULL
}
Definition at line 732 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_alphabet_lower
Initial value:
= { "ldml alphabets alphabet l", 4,
  (ELEM_START_FUNC) (&start_lower_case_rule),
  (ELEM_END_FUNC) (&end_case_rule), NULL
}
Definition at line 751 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_alphabet_lower_dest
Initial value:
=
  { "ldml alphabets alphabet l d", 5, (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_transform_buffer), (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 761 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_alphabet_lower_src
Initial value:
=
  { "ldml alphabets alphabet l s", 5, (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_transform_buffer), (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 756 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_alphabet_upper
Initial value:
= { "ldml alphabets alphabet u", 4,
  (ELEM_START_FUNC) (&start_upper_case_rule),
  (ELEM_END_FUNC) (&end_case_rule), NULL
}
Definition at line 736 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_alphabet_upper_dest
Initial value:
=
  { "ldml alphabets alphabet u d", 5, (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_transform_buffer), (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 746 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_alphabet_upper_src
Initial value:
=
  { "ldml alphabets alphabet u s", 5, (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_transform_buffer), (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 741 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_alphabets
Initial value:
= { "ldml alphabets", 2, (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_element_ok), NULL
}
Definition at line 722 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_calendar
Initial value:
= { "ldml dates calendars calendar", 4, (ELEM_START_FUNC) (&start_calendar),
  (ELEM_END_FUNC) (&end_element_ok), NULL
}
Definition at line 352 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_calendars
Initial value:
= { "ldml dates calendars", 3, (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_element_ok), NULL
}
Definition at line 348 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation
Initial value:
= { "ldml collations collation", 3, (ELEM_START_FUNC) (&start_one_collation),
  (ELEM_END_FUNC) (&end_one_collation), NULL
}
Definition at line 489 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_cubrid_rules
Initial value:
= {
  "ldml collations collation cubridrules", 4,
  (ELEM_START_FUNC) (&start_element_ok), (ELEM_END_FUNC) (&end_element_ok),
  NULL
}
Definition at line 663 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_cubrid_rules_set
Initial value:
= { "ldml collations collation cubridrules set", 5,
  (ELEM_START_FUNC) (&start_collation_cubrid_rule),
  (ELEM_END_FUNC) (&end_collation_cubrid_rule_set), NULL
}
Definition at line 669 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_cubrid_rules_set_ch
Initial value:
= { "ldml collations collation cubridrules set ch", 6,
  (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_collation_cubrid_rule_set_cp_ch),
  (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 674 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_cubrid_rules_set_cp
Initial value:
= { "ldml collations collation cubridrules set cp", 6,
  (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_collation_cubrid_rule_set_cp_ch),
  (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 692 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_cubrid_rules_set_ech
Initial value:
= { "ldml collations collation cubridrules set ech", 6,
  (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_collation_cubrid_rule_set_ech_ecp),
  (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 686 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_cubrid_rules_set_ecp
Initial value:
= { "ldml collations collation cubridrules set ecp", 6,
  (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_collation_cubrid_rule_set_ech_ecp),
  (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 704 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_cubrid_rules_set_sch
Initial value:
= { "ldml collations collation cubridrules set sch", 6,
  (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_collation_cubrid_rule_set_cp_ch),
  (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 680 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_cubrid_rules_set_scp
Initial value:
= { "ldml collations collation cubridrules set scp", 6,
  (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_collation_cubrid_rule_set_cp_ch),
  (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 698 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_cubrid_rules_set_w
Initial value:
= { "ldml collations collation cubridrules set w", 6,
  (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_collation_cubrid_rule_set_w_wr),
  (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 710 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_cubrid_rules_set_wr
Initial value:
= { "ldml collations collation cubridrules set wr", 6,
  (ELEM_START_FUNC) (&start_collation_cubrid_rule_set_wr),
  (ELEM_END_FUNC) (&end_collation_cubrid_rule_set_w_wr),
  (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 716 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_i
Initial value:
= { "ldml collations collation rules i", 5,
  (ELEM_START_FUNC) (&start_collation_rule),
  (ELEM_END_FUNC) (&end_collation_rule),
  (ELEM_DATA_FUNC) (&handle_data_collation_rule)
}
Definition at line 526 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_ic
Initial value:
= { "ldml collations collation rules ic", 5,
  (ELEM_START_FUNC) (&start_collation_rule),
  (ELEM_END_FUNC) (&end_collation_rule),
  (ELEM_DATA_FUNC) (&handle_data_collation_rule)
}
Definition at line 550 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_p
Initial value:
= { "ldml collations collation rules p", 5,
  (ELEM_START_FUNC) (&start_collation_rule),
  (ELEM_END_FUNC) (&end_collation_rule),
  (ELEM_DATA_FUNC) (&handle_data_collation_rule)
}
Definition at line 508 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_pc
Initial value:
= { "ldml collations collation rules pc", 5,
  (ELEM_START_FUNC) (&start_collation_rule),
  (ELEM_END_FUNC) (&end_collation_rule),
  (ELEM_DATA_FUNC) (&handle_data_collation_rule)
}
Definition at line 532 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_reset
Initial value:
= { "ldml collations collation rules reset", 5,
  (ELEM_START_FUNC) (&start_collation_reset),
  (ELEM_END_FUNC) (&end_collation_reset), (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 503 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_reset_first_non_ignorable
Initial value:
=
  { "ldml collations collation rules reset first_non_ignorable", 6,
  (ELEM_START_FUNC) (&start_collation_logical_pos),
  (ELEM_END_FUNC) (&end_collation_logical_pos), NULL
}
Definition at line 641 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_reset_first_primary_ignorable
Initial value:
=
  { "ldml collations collation rules reset first_primary_ignorable", 6,
  (ELEM_START_FUNC) (&start_collation_logical_pos),
  (ELEM_END_FUNC) (&end_collation_logical_pos), NULL
}
Definition at line 605 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_reset_first_secondary_ignorable
Initial value:
=
  { "ldml collations collation rules reset first_secondary_ignorable", 6,
  (ELEM_START_FUNC) (&start_collation_logical_pos),
  (ELEM_END_FUNC) (&end_collation_logical_pos), NULL
}
Definition at line 617 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_reset_first_tertiary_ignorable
Initial value:
=
  { "ldml collations collation rules reset first_tertiary_ignorable", 6,
  (ELEM_START_FUNC) (&start_collation_logical_pos),
  (ELEM_END_FUNC) (&end_collation_logical_pos), NULL
}
Definition at line 629 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_reset_first_trailing
Initial value:
= { "ldml collations collation rules reset first_trailing", 6,
  (ELEM_START_FUNC) (&start_collation_logical_pos),
  (ELEM_END_FUNC) (&end_collation_logical_pos), NULL
}
Definition at line 653 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_reset_first_variable
Initial value:
= { "ldml collations collation rules reset first_variable", 6,
  (ELEM_START_FUNC) (&start_collation_logical_pos),
  (ELEM_END_FUNC) (&end_collation_logical_pos), NULL
}
Definition at line 595 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_reset_last_non_ignorable
Initial value:
=
  { "ldml collations collation rules reset last_non_ignorable", 6,
  (ELEM_START_FUNC) (&start_collation_logical_pos),
  (ELEM_END_FUNC) (&end_collation_logical_pos), NULL
}
Definition at line 647 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_reset_last_primary_ignorable
Initial value:
=
  { "ldml collations collation rules reset last_primary_ignorable", 6,
  (ELEM_START_FUNC) (&start_collation_logical_pos),
  (ELEM_END_FUNC) (&end_collation_logical_pos), NULL
}
Definition at line 611 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_reset_last_secondary_ignorable
Initial value:
=
  { "ldml collations collation rules reset last_secondary_ignorable", 6,
  (ELEM_START_FUNC) (&start_collation_logical_pos),
  (ELEM_END_FUNC) (&end_collation_logical_pos), NULL
}
Definition at line 623 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_reset_last_tertiary_ignorable
Initial value:
=
  { "ldml collations collation rules reset last_tertiary_ignorable", 6,
  (ELEM_START_FUNC) (&start_collation_logical_pos),
  (ELEM_END_FUNC) (&end_collation_logical_pos), NULL
}
Definition at line 635 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_reset_last_trailing
Initial value:
= { "ldml collations collation rules reset last_trailing", 6,
  (ELEM_START_FUNC) (&start_collation_logical_pos),
  (ELEM_END_FUNC) (&end_collation_logical_pos), NULL
}
Definition at line 658 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_reset_last_variable
Initial value:
= { "ldml collations collation rules reset last_variable", 6,
  (ELEM_START_FUNC) (&start_collation_logical_pos),
  (ELEM_END_FUNC) (&end_collation_logical_pos), NULL
}
Definition at line 600 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_rules
Initial value:
= { "ldml collations collation rules", 4,
  (ELEM_START_FUNC) (&start_element_ok), (ELEM_END_FUNC) (&end_element_ok),
  NULL
}
Definition at line 493 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_s
Initial value:
= { "ldml collations collation rules s", 5,
  (ELEM_START_FUNC) (&start_collation_rule),
  (ELEM_END_FUNC) (&end_collation_rule),
  (ELEM_DATA_FUNC) (&handle_data_collation_rule)
}
Definition at line 514 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_sc
Initial value:
= { "ldml collations collation rules sc", 5,
  (ELEM_START_FUNC) (&start_collation_rule),
  (ELEM_END_FUNC) (&end_collation_rule),
  (ELEM_DATA_FUNC) (&handle_data_collation_rule)
}
Definition at line 538 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_settings
Initial value:
= { "ldml collations collation settings", 4,
  (ELEM_START_FUNC) (&start_collation_settings),
  (ELEM_END_FUNC) (&end_element_ok), NULL
}
Definition at line 498 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_t
Initial value:
= { "ldml collations collation rules t", 5,
  (ELEM_START_FUNC) (&start_collation_rule),
  (ELEM_END_FUNC) (&end_collation_rule),
  (ELEM_DATA_FUNC) (&handle_data_collation_rule)
}
Definition at line 520 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_tc
Initial value:
= { "ldml collations collation rules tc", 5,
  (ELEM_START_FUNC) (&start_collation_rule),
  (ELEM_END_FUNC) (&end_collation_rule),
  (ELEM_DATA_FUNC) (&handle_data_collation_rule)
}
Definition at line 544 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_x
Initial value:
= { "ldml collations collation rules x", 5,
  (ELEM_START_FUNC) (&start_collation_x), (ELEM_END_FUNC) (&end_collation_x),
  NULL
}
Definition at line 556 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_x_context
Initial value:
= { "ldml collations collation rules x context", 6,
  (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_collation_x_context), (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 590 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_x_extend
Initial value:
= { "ldml collations collation rules x extend", 6,
  (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_collation_x_extend), (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 585 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_x_i
Initial value:
= { "ldml collations collation rules x i", 6,
  (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_collation_x_rule),
  (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 579 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_x_p
Initial value:
= { "ldml collations collation rules x p", 6,
  (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_collation_x_rule),
  (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 561 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_x_s
Initial value:
= { "ldml collations collation rules x s", 6,
  (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_collation_x_rule),
  (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 567 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collation_x_t
Initial value:
= { "ldml collations collation rules x t", 6,
  (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_collation_x_rule),
  (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 573 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_collations
Initial value:
= { "ldml collations", 2, (ELEM_START_FUNC) (&start_collations),
  (ELEM_END_FUNC) (&end_element_ok), NULL
}
Definition at line 485 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_consoleconversion
Initial value:
=
  { "ldml consoleconversion", 2, (ELEM_START_FUNC) (&start_consoleconversion),
  (ELEM_END_FUNC) (&end_element_ok), NULL
}
Definition at line 770 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_currencies
Initial value:
= { "ldml numbers currencies", 3, (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_element_ok), NULL
}
Definition at line 476 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_currency
Initial value:
= { "ldml numbers currencies currency", 4,
  (ELEM_START_FUNC) (&start_currency),
  (ELEM_END_FUNC) (&end_element_ok), NULL
}
Definition at line 480 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_dateFormatCUBRID
Initial value:
= { "ldml dates calendars calendar dateFormatCUBRID", 5,
  (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_dateFormatCUBRID), (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 356 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_dates
Initial value:
= { "ldml dates", 2, (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_element_ok), NULL
}
Definition at line 344 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_day
Initial value:
= { "ldml dates calendars calendar days dayContext dayWidth day", 8,
  (ELEM_START_FUNC) (&start_day), (ELEM_END_FUNC) (&end_day),
  (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 430 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_dayContext
Initial value:
= { "ldml dates calendars calendar days dayContext", 6,
  (ELEM_START_FUNC) (&start_calendar_name_context),
  (ELEM_END_FUNC) (&end_element_ok), NULL
}
Definition at line 420 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_dayPeriod
Initial value:
= {
  "ldml dates calendars calendar dayPeriods dayPeriodContext dayPeriodWidth dayPeriod",
  8,
  (ELEM_START_FUNC) (&start_dayPeriod), (ELEM_END_FUNC) (&end_dayPeriod),
  (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 453 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_dayPeriodContext
Initial value:
= { "ldml dates calendars calendar dayPeriods dayPeriodContext", 6,
  (ELEM_START_FUNC) (&start_calendar_name_context),
  (ELEM_END_FUNC) (&end_element_ok), NULL
}
Definition at line 440 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_dayPeriods
Initial value:
= { "ldml dates calendars calendar dayPeriods", 5,
  (ELEM_START_FUNC) (&start_element_ok), (ELEM_END_FUNC) (&end_element_ok),
  NULL
}
Definition at line 435 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_dayPeriodWidth
Initial value:
= {
  "ldml dates calendars calendar dayPeriods dayPeriodContext dayPeriodWidth",
  7,
  (ELEM_START_FUNC) (&start_dayPeriodWidth),
  (ELEM_END_FUNC) (&end_element_ok),
  NULL
}
Definition at line 445 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_days
Initial value:
= { "ldml dates calendars calendar days", 5,
  (ELEM_START_FUNC) (&start_element_ok), (ELEM_END_FUNC) (&end_element_ok),
  NULL
}
Definition at line 415 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_dayWidth
Initial value:
= { "ldml dates calendars calendar days dayContext dayWidth", 7,
  (ELEM_START_FUNC) (&start_month_day_Width),
  (ELEM_END_FUNC) (&end_month_day_Width), NULL
}
Definition at line 425 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_include_collation
Initial value:
= { "ldml collations include", 3,
  (ELEM_START_FUNC) (&start_include_collation),
  (ELEM_END_FUNC) (&end_element_ok),
  NULL
}
Definition at line 726 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_ldml
Initial value:
= { "ldml", 1, (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_element_ok), NULL
}
Definition at line 340 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_month
Initial value:
= { "ldml dates calendars calendar months monthContext monthWidth month", 8,
  (ELEM_START_FUNC) (&start_month), (ELEM_END_FUNC) (&end_month),
  (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 410 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_monthContext
Initial value:
= { "ldml dates calendars calendar months monthContext", 6,
  (ELEM_START_FUNC) (&start_calendar_name_context),
  (ELEM_END_FUNC) (&end_element_ok), NULL
}
Definition at line 400 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_months
Initial value:
= { "ldml dates calendars calendar months", 5,
  (ELEM_START_FUNC) (&start_element_ok), (ELEM_END_FUNC) (&end_element_ok),
  NULL
}
Definition at line 395 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_monthWidth
Initial value:
= { "ldml dates calendars calendar months monthContext monthWidth", 7,
  (ELEM_START_FUNC) (&start_month_day_Width),
  (ELEM_END_FUNC) (&end_month_day_Width), NULL
}
Definition at line 405 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_numbers
Initial value:
= { "ldml numbers", 2, (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_element_ok), NULL
}
Definition at line 460 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_numbers_symbols
Initial value:
= { "ldml numbers symbols", 3, (ELEM_START_FUNC) (&start_numbers_symbols),
  (ELEM_END_FUNC) (&end_element_ok), NULL
}
Definition at line 464 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_symbol_decimal
Initial value:
= { "ldml numbers symbols decimal", 4, (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_number_symbol), (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 468 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_symbol_group
Initial value:
= { "ldml numbers symbols group", 4, (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_number_symbol), (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 472 of file locale_support.c.
XML_ELEMENT_DEF ldml_elem_unicodefile
Initial value:
= { "ldml unicodefile", 2, (ELEM_START_FUNC) (&start_unicode_file),
  (ELEM_END_FUNC) (&end_element_ok), NULL
}
Definition at line 766 of file locale_support.c.
XML_ELEMENT_DEF* ldml_elements[]
Definition at line 779 of file locale_support.c.
const char* ldml_ref_am_pm_names[]
Initial value:
= { "am", "pm", "Am", "Pm", "AM", "PM",
  "a.m.", "p.m.", "A.m.", "P.m.", "A.M.", "P.M."
}
Definition at line 61 of file locale_support.c.
Referenced by start_dayPeriod().
const char* ldml_ref_day_names[] = { "sun", "mon", "tue", "wed", "thu", "fri", "sat" }
Definition at line 58 of file locale_support.c.
Referenced by start_day().
XML_ELEMENT_DEF ldml_timeFormatCUBRID
Initial value:
= { "ldml dates calendars calendar timeFormatCUBRID", 5,
  (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_timeFormatCUBRID), (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 361 of file locale_support.c.
XML_ELEMENT_DEF ldml_timestampFormatCUBRID
Initial value:
= { "ldml dates calendars calendar timestampFormatCUBRID", 5,
  (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_timestampFormatCUBRID),
  (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 371 of file locale_support.c.
XML_ELEMENT_DEF ldml_timestamptzFormatCUBRID
Initial value:
= { "ldml dates calendars calendar timestamptzFormatCUBRID", 5,
  (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_timestamptzFormatCUBRID),
  (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 389 of file locale_support.c.
XML_ELEMENT_DEF ldml_timetzFormatCUBRID
Initial value:
= { "ldml dates calendars calendar timetzFormatCUBRID", 5,
  (ELEM_START_FUNC) (&start_element_ok),
  (ELEM_END_FUNC) (&end_timetzFormatCUBRID),
  (ELEM_DATA_FUNC) (&handle_data)
}
Definition at line 377 of file locale_support.c.
LOC_SHARED_DATA* shared_data = NULL static
Definition at line 92 of file locale_support.c.