CUBRID Engine: src/transaction/locator_cl.h File Reference
locator_cl.h File Reference
#include "config.h"
#include "error_manager.h"
#include "work_space.h"
#include "storage_common.h"
#include "locator.h"
#include "replication.h"
Classes
struct list_mops
Macros
#define ONE_MFLUSH true
#define MANY_MFLUSHES false
#define DECACHE true
#define DONT_DECACHE false
#define OID_BATCH_SIZE 2000
#define LC_INSERT_OPERATION_TYPE(p)
#define LC_UPDATE_OPERATION_TYPE(p)
Typedefs
typedef struct list_mops LIST_MOPS
typedef void(* LC_OIDMAP_CALLBACK) (LC_OIDMAP *map)
Enumerations
enum LC_OBJTYPE { LC_OBJECT, LC_CLASS, LC_INSTANCE }
Functions
bool locator_is_root (MOP mop)
int locator_is_class (MOP mop, DB_FETCH_MODE hint_purpose)
LOCK locator_fetch_mode_to_lock (DB_FETCH_MODE purpose, LC_OBJTYPE type, LC_FETCH_VERSION_TYPE fetch_version_type)
int locator_get_cache_coherency_number (MOP mop)
MOBJ locator_fetch_object (MOP mop, DB_FETCH_MODE purpose, LC_FETCH_VERSION_TYPE fetch_version_type)
MOBJ locator_fetch_class (MOP class_mop, DB_FETCH_MODE purpose)
MOBJ locator_fetch_class_of_instance (MOP inst_mop, MOP *class_mop, DB_FETCH_MODE purpose)
MOBJ locator_fetch_instance (MOP mop, DB_FETCH_MODE purpose, LC_FETCH_VERSION_TYPE fetch_version_type)
MOBJ locator_fetch_set (int num_mops, MOP *mop_set, DB_FETCH_MODE inst_purpose, DB_FETCH_MODE class_purpose, int quit_on_errors)
MOBJ locator_fetch_nested (MOP mop, DB_FETCH_MODE purpose, int prune_level, int quit_on_errors)
int locator_flush_class (MOP class_mop)
int locator_flush_instance (MOP mop)
int locator_flush_all_instances (MOP class_mop, bool decache)
int locator_flush_for_multi_update (MOP class_mop)
int locator_all_flush (void)
int locator_repl_flush_all (void)
MOP locator_add_class (MOBJ classobj, const char *classname)
MOP locator_add_instance (MOBJ instance, MOP class_mop)
MOP locator_add_root (OID *root_oid, MOBJ class_root)
int locator_remove_class (MOP class_mop)
void locator_remove_instance (MOP mop)
MOBJ locator_update_instance (MOP mop)
MOBJ locator_update_class (MOP mop)
int locator_update_tree_classes (MOP *classes_mop_set, int num_classes)
MOBJ locator_prepare_rename_class (MOP class_mop, const char *old_classname, const char *new_classname)
OID * locator_assign_permanent_oid (MOP mop)
MOP locator_find_class (const char *classname)
MOP locator_find_class_with_purpose (const char *classname, bool for_update)
LC_FIND_CLASSNAME locator_lockhint_classes (int num_classes, const char **many_classnames, LOCK *many_locks, int *need_subclasses, LC_PREFETCH_FLAGS *flags, int quit_on_errors, LOCK lock_rr_tran)
int locator_does_exist_object (MOP mop, DB_FETCH_MODE purpose)
LIST_MOPS * locator_get_all_mops (MOP class_mop, DB_FETCH_MODE class_purpose, LC_FETCH_VERSION_TYPE *force_fetch_version_type)
LIST_MOPS * locator_get_all_class_mops (DB_FETCH_MODE purpose, int(*fun)(MOBJ class_obj))
void locator_free_list_mops (LIST_MOPS *mops)
void locator_synch_isolation_incons (void)
void locator_set_sig_interrupt (int set)
MOBJ locator_create_heap_if_needed (MOP class_mop, bool reuse_oid)
MOBJ locator_has_heap (MOP class_mop)
LC_OIDMAP * locator_add_oidset_object (LC_OIDSET *oidset, DB_OBJECT *obj)
int locator_assign_oidset (LC_OIDSET *oidset, LC_OIDMAP_CALLBACK callback)
int locator_assign_all_permanent_oids (void)
int locator_decache_all_lock_instances (MOP class_mop)
int locator_get_append_lsa (struct log_lsa *lsa)
int locator_flush_replication_info (REPL_INFO *repl_info)
LC_FIND_CLASSNAME locator_reserve_class_name (const char *class_name, OID *class_oid)
Macro Definition Documentation
#define DECACHE true
Definition at line 48 of file locator_cl.h.
Referenced by compactdb_start(), do_reclaim_class_addresses(), install_new_representation(), locator_flush_instance(), sm_delete_class_mop(), sm_exist_index(), and ws_intern_instances().
#define DONT_DECACHE false
Definition at line 49 of file locator_cl.h.
Referenced by do_check_for_empty_classes_in_delete(), locator_all_flush(), locator_flush_class(), locator_flush_instance(), locator_fun_get_all_mops(), locator_repl_flush_all(), process_class(), sm_flush_and_decache_objects_internal(), sm_force_write_all_classes(), sm_update_statistics(), and vid_allflush().
#define LC_INSERT_OPERATION_TYPE (p)
Value:
((p)==DB_NOT_PARTITIONED_CLASS ? LC_FLUSH_INSERT :   \
         ((p)==DB_PARTITIONED_CLASS ? LC_FLUSH_INSERT_PRUNE :\
                      LC_FLUSH_INSERT_PRUNE_VERIFY))
Definition at line 53 of file locator_cl.h.
Referenced by la_repl_add_object(), and locator_mflush().
#define LC_UPDATE_OPERATION_TYPE (p)
Value:
((p)==DB_NOT_PARTITIONED_CLASS ? LC_FLUSH_UPDATE :   \
         ((p)==DB_PARTITIONED_CLASS ? LC_FLUSH_UPDATE_PRUNE :\
                      LC_FLUSH_UPDATE_PRUNE_VERIFY))
Definition at line 58 of file locator_cl.h.
Referenced by la_repl_add_object(), and locator_mflush().
#define MANY_MFLUSHES false
Definition at line 46 of file locator_cl.h.
Referenced by locator_all_flush(), locator_flush_all_instances(), locator_flush_for_multi_update(), and locator_repl_flush_all().
#define OID_BATCH_SIZE 2000
Definition at line 51 of file locator_cl.h.
Referenced by ldr_assign_all_perm_oids(), and locator_add_to_oidset_when_temp_oid().
#define ONE_MFLUSH true
Definition at line 45 of file locator_cl.h.
Referenced by locator_flush_class(), and locator_internal_flush_instance().
Typedef Documentation
typedef void(* LC_OIDMAP_CALLBACK) (LC_OIDMAP *map)
Definition at line 130 of file locator_cl.h.
typedef struct list_mops LIST_MOPS
Definition at line 63 of file locator_cl.h.
Enumeration Type Documentation
enum LC_OBJTYPE
Enumerator
LC_OBJECT
LC_CLASS
LC_INSTANCE
Definition at line 70 of file locator_cl.h.
Function Documentation
MOP locator_add_class (MOBJ classobj, const char * classname)
Definition at line 5595 of file locator_cl.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_LC_CLASSNAME_EXIST, er_set(), IX_LOCK, LC_CLASS, LC_FETCH_CURRENT_VERSION, locator_delete_class_name(), locator_flush_class(), locator_get_reserved_class_name_oid(), locator_lock(), lock_Conv, NA_LOCK, NO_ERROR, NULL, NULL_LOCK, SCH_M_LOCK, sm_Root_class_mop, ws_cache_with_oid(), ws_dirty(), ws_find_class(), ws_get_lock(), WS_IS_DELETED, and ws_set_lock().
Referenced by update_class().
MOP locator_add_instance (MOBJ instance, MOP class_mop)
Definition at line 5782 of file locator_cl.c.
References locator_all_flush(), locator_create_heap_if_needed(), locator_mflush_temp_oid::mop, NO_ERROR, NULL, OID_ASSIGN_TEMPOID, OID_INIT_TEMPID, OID_ISNULL, sm_is_reuse_oid_class(), ws_cache_with_oid(), ws_dirty(), ws_set_lock(), and X_LOCK.
Referenced by create_template_object(), and vid_add_virtual_instance().
LC_OIDMAP* locator_add_oidset_object (LC_OIDSET * oidset, DB_OBJECT * obj)
MOP locator_add_root (OID * root_oid, MOBJ class_root)
Definition at line 5544 of file locator_cl.c.
References LC_CLASSNAME_RESERVED, locator_flush_class(), locator_reserve_class_name(), NO_ERROR, NULL, oid_Root_class_oid, ROOTCLASS_NAME, SCH_M_LOCK, sm_mark_system_class(), sm_Root_class_mop, ws_cache(), ws_dirty(), ws_mop(), ws_oid(), and ws_set_lock().
Referenced by sm_create_root().
int locator_all_flush (void)
Definition at line 5457 of file locator_cl.c.
References DONT_DECACHE, ER_FAILED, locator_mflush(), locator_mflush_end(), locator_mflush_force(), locator_mflush_initialize(), MANY_MFLUSHES, locator_mflush_cache::mobjs, NO_ERROR, NULL, lc_copyarea_manyobjs::num_objs, vid_allflush(), ws_map_dirty(), WS_MAP_FAIL, and WS_MAP_SUCCESS.
Referenced by do_create_trigger(), do_execute_select(), do_execute_statement(), do_statement(), locator_add_instance(), sm_update_all_statistics(), tr_create_trigger(), tran_2pc_prepare(), tran_2pc_prepare_global_tran(), tran_flush_to_commit(), and tran_savepoint_internal().
int locator_assign_all_permanent_oids (void)
Definition at line 6836 of file locator_cl.c.
References ER_FAILED, error(), locator_add_to_oidset_when_temp_oid(), locator_assign_oidset(), locator_free_oid_set(), locator_make_oid_set(), NO_ERROR, NULL, ws_map_dirty(), and WS_MAP_FAIL.
Referenced by do_execute_select(), and tran_flush_to_commit().
int locator_assign_oidset (LC_OIDSET * oidset, LC_OIDMAP_CALLBACK callback)
Definition at line 6687 of file locator_cl.c.
References assert, lc_oidset::classes, er_errid(), locator_assign_oid_batch(), lc_oidmap::mop, lc_oidmap::next, lc_class_oidset::next, NO_ERROR, NULL, lc_oidmap::oid, lc_class_oidset::oids, lc_oidset::total_oids, and ws_update_oid().
Referenced by col_permanent_oids(), ldr_assign_all_perm_oids(), locator_add_to_oidset_when_temp_oid(), locator_assign_all_permanent_oids(), and tf_do_fixup().
OID* locator_assign_permanent_oid (MOP mop)
Definition at line 6084 of file locator_cl.c.
References ARG_FILE_LINE, DB_FETCH_CLREAD_INSTWRITE, er_errid(), ER_ERROR_SEVERITY, ER_HEAP_UNKNOWN_OBJECT, ER_LK_UNILATERALLY_ABORTED, er_set(), locator_assign_oid(), locator_fetch_class(), locator_is_root(), NO_ERROR, NULL, db_identifier::pageid, db_identifier::slotid, sm_ch_heap(), sm_ch_name(), sm_Root_class_hfid, tf_object_size(), tran_abort_only_client(), db_identifier::volid, ws_class_mop(), ws_find(), WS_FIND_MOP_DELETED, ws_oid(), and ws_update_oid().
Referenced by allocate_disk_structures(), collect_hier_class_info(), tf_mem_to_disk(), tf_need_permanent_oid(), and vid_encode_object().
MOBJ locator_create_heap_if_needed (MOP class_mop, bool reuse_oid)
Definition at line 5690 of file locator_cl.c.
References assert, DB_FETCH_CLREAD_INSTWRITE, DB_FETCH_WRITE, heap_create(), HFID_IS_NULL, locator_fetch_class(), locator_flush_class(), NO_ERROR, NULL, OID_ISNULL, OID_ISTEMP, sm_ch_heap(), sm_ch_rep_dir(), ws_dirty(), and ws_oid().
Referenced by au_install(), define_trigger_classes(), do_create_entity(), do_create_partition(), locator_add_instance(), locator_has_heap(), pt_to_func_pred(), pt_to_insert_xasl(), pt_to_merge_insert_xasl(), and pt_to_pred_with_context().
int locator_decache_all_lock_instances (MOP class_mop)
Definition at line 3293 of file locator_cl.c.
References ER_FAILED, locator_decache_lock(), NO_ERROR, NULL, ws_map_class(), and WS_MAP_SUCCESS.
Referenced by locator_cache_not_have_object(), locator_cache_object_class(), and unloaddb().
int locator_does_exist_object (MOP mop, DB_FETCH_MODE purpose)
Definition at line 3242 of file locator_cl.c.
References LC_CLASS, LC_INSTANCE, LC_OBJECT, locator_fetch_mode_to_lock(), locator_is_root(), locator_lock_and_doesexist(), NULL, TM_TRAN_READ_FETCH_VERSION, and ws_class_mop().
Referenced by check_set_object(), get_object_value(), obj_find_object_by_pkey(), obj_isinstance(), pt_bind_parameter(), and tp_domain_check_class().
MOBJ locator_fetch_class (MOP class_mop, DB_FETCH_MODE purpose)
Definition at line 2293 of file locator_cl.c.
References ARG_FILE_LINE, er_log_debug, LC_CLASS, LC_FETCH_CURRENT_VERSION, LC_FETCH_MVCC_VERSION, locator_fetch_instance(), locator_fetch_mode_to_lock(), locator_is_root(), locator_lock(), NO_ERROR, NULL, db_identifier::pageid, db_identifier::slotid, db_identifier::volid, ws_class_mop(), ws_find(), WS_FIND_MOP_DELETED, and ws_oid().
Referenced by chksum_start(), class_referenced_by_class(), delete_list_by_oids(), delete_real_class(), do_alter_change_col_comment(), do_alter_change_default_cs_coll(), do_alter_change_tbl_comment(), do_alter_clause_change_attribute(), do_alter_trigger(), do_execute_merge(), do_insert_checks(), do_merge(), do_reclaim_class_addresses(), fetch_class(), la_apply_delete_log(), la_apply_insert_log(), la_apply_update_log(), locator_assign_permanent_oid(), locator_cache_object_instance(), locator_create_heap_if_needed(), locator_fetch_instance(), locator_fetch_nested(), locator_fetch_set(), locator_flush_all_instances(), locator_flush_for_multi_update(), locator_fun_get_all_mops(), locator_mflush(), locator_prepare_rename_class(), locator_remove_class(), locator_update_class(), process_value(), pt_make_class_access_spec(), sm_decache_instances_after_query_executed_with_commit(), sm_flush_and_decache_objects_internal(), sm_get_class_repid(), smt_change_query_spec(), update_object_by_oid(), and update_real_class().
MOBJ locator_fetch_class_of_instance (MOP inst_mop, MOP * class_mop, DB_FETCH_MODE purpose)
Definition at line 2354 of file locator_cl.c.
References LC_CLASS, locator_fetch_mode_to_lock(), locator_lock_class_of_instance(), NO_ERROR, NULL, TM_TRAN_READ_FETCH_VERSION, ws_find(), and WS_FIND_MOP_DELETED.
Referenced by fetch_class().
MOBJ locator_fetch_instance (MOP mop, DB_FETCH_MODE purpose, LC_FETCH_VERSION_TYPE fetch_version_type)
Definition at line 2393 of file locator_cl.c.
References ARG_FILE_LINE, er_log_debug, LC_INSTANCE, locator_fetch_class(), locator_fetch_mode_to_lock(), locator_is_root(), locator_lock(), NO_ERROR, NULL, db_identifier::pageid, db_identifier::slotid, db_identifier::volid, ws_class_mop(), ws_find(), WS_FIND_MOP_DELETED, and ws_oid().
Referenced by fetch_instance(), locator_fetch_class(), locator_fetch_set(), and locator_update_instance().
LOCK locator_fetch_mode_to_lock (DB_FETCH_MODE purpose, LC_OBJTYPE type, LC_FETCH_VERSION_TYPE fetch_version_type)
Definition at line 2068 of file locator_cl.c.
References ARG_FILE_LINE, assert, DB_FETCH_CLREAD_INSTREAD, DB_FETCH_CLREAD_INSTWRITE, DB_FETCH_DIRTY, DB_FETCH_EXCLUSIVE_SCAN, DB_FETCH_QUERY_READ, DB_FETCH_QUERY_WRITE, DB_FETCH_READ, DB_FETCH_SCAN, DB_FETCH_WRITE, er_log_debug, IS_LOCK, IX_LOCK, LC_CLASS, LC_FETCH_DIRTY_VERSION, LC_INSTANCE, NULL_LOCK, S_LOCK, SCH_M_LOCK, SCH_S_LOCK, SIX_LOCK, and X_LOCK.
Referenced by ldr_init_loader(), locator_does_exist_object(), locator_fetch_class(), locator_fetch_class_of_instance(), locator_fetch_instance(), locator_fetch_nested(), locator_fetch_object(), locator_fetch_set(), locator_find_class_with_purpose(), locator_fun_get_all_mops(), locator_get_cache_coherency_number(), locator_save_nested_mops(), lockhint_subclasses(), pt_add_lock_class(), and pt_in_lck_array().
MOBJ locator_fetch_nested (MOP mop, DB_FETCH_MODE purpose, int prune_level, int quit_on_errors)
Definition at line 2549 of file locator_cl.c.
References ARG_FILE_LINE, er_log_debug, LC_INSTANCE, locator_fetch_class(), locator_fetch_mode_to_lock(), locator_is_root(), locator_lock_nested(), NO_ERROR, NULL, db_identifier::pageid, db_identifier::slotid, TM_TRAN_READ_FETCH_VERSION, db_identifier::volid, ws_class_mop(), ws_find(), WS_FIND_MOP_DELETED, and ws_oid().
Referenced by db_fetch_composition().
MOBJ locator_fetch_object (MOP mop, DB_FETCH_MODE purpose, LC_FETCH_VERSION_TYPE fetch_version_type)
Definition at line 2235 of file locator_cl.c.
References LC_CLASS, LC_INSTANCE, LC_OBJECT, locator_fetch_mode_to_lock(), locator_is_root(), locator_lock(), NO_ERROR, NULL, ws_class_mop(), ws_find(), and WS_FIND_MOP_DELETED.
Referenced by cursor_fetch_oids(), and locator_is_class().
MOBJ locator_fetch_set (int num_mops, MOP * mop_set, DB_FETCH_MODE inst_purpose, DB_FETCH_MODE class_purpose, int quit_on_errors)
Definition at line 2464 of file locator_cl.c.
References db_real_instance(), LC_CLASS, LC_FETCH_CURRENT_VERSION, LC_INSTANCE, locator_fetch_class(), locator_fetch_instance(), locator_fetch_mode_to_lock(), locator_lock_set(), NO_ERROR, NULL, sm_Root_class_mop, TM_TRAN_READ_FETCH_VERSION, ws_class_mop(), ws_find(), WS_FIND_MOP_DELETED, and WS_ISVID.
Referenced by acquire_locks_for_multiple_rename(), cursor_fetch_oids(), db_fetch_array(), extract_objects(), and fetch_set_internal().
MOP locator_find_class (const char * classname)
Definition at line 3142 of file locator_cl.c.
References LC_CLASSNAME_EXIST, locator_find_class_by_name(), NULL, and SCH_S_LOCK.
Referenced by catcls_vclass_install(), get_class_mops(), get_requested_classes(), la_create_repl_filter(), sm_find_class(), sm_mark_system_class(), and util_get_class_oids_and_index_btid().
MOP locator_find_class_with_purpose (const char * classname, bool for_update)
Definition at line 3167 of file locator_cl.c.
References LC_CLASS, LC_CLASSNAME_EXIST, locator_fetch_mode_to_lock(), locator_find_class_by_name(), NULL, SCH_M_LOCK, and SCH_S_LOCK.
Referenced by sm_find_class_with_purpose().
int locator_flush_all_instances (MOP class_mop, bool decache)
Definition at line 5278 of file locator_cl.c.
References ASSERT_ERROR_AND_SET, DB_FETCH_READ, ER_FAILED, locator_fetch_class(), locator_is_root(), locator_mflush(), locator_mflush_end(), locator_mflush_force(), locator_mflush_initialize(), MANY_MFLUSHES, locator_mflush_cache::mobjs, db_objlist::next, NO_ERROR, NULL, lc_copyarea_manyobjs::num_objs, locator_mflush_temp_oid::obj, db_object::object, db_objlist::op, sm_class::partition, sm_ch_heap(), sm_class::users, vid_flush_all_instances(), ws_disconnect_deleted_instances(), WS_ISVID, ws_map_class(), ws_map_class_dirty(), and WS_MAP_FAIL.
Referenced by compactdb_start(), do_check_for_empty_classes_in_delete(), do_reclaim_class_addresses(), install_new_representation(), locator_fun_get_all_mops(), process_class(), sm_delete_class_mop(), sm_exist_index(), sm_flush_and_decache_objects_internal(), sm_force_write_all_classes(), sm_update_statistics(), and ws_intern_instances().
int locator_flush_class (MOP class_mop)
Definition at line 5068 of file locator_cl.c.
References ARG_FILE_LINE, DONT_DECACHE, er_errid(), ER_ERROR_SEVERITY, ER_FAILED, ER_GENERIC_ERROR, ER_OBJ_INVALID_ARGUMENTS, er_set(), locator_mflush(), locator_mflush_end(), locator_mflush_force(), locator_mflush_initialize(), locator_mflush_cache::mobjs, NO_ERROR, NULL, lc_copyarea_manyobjs::num_objs, ONE_MFLUSH, ws_find(), WS_FIND_MOP_DELETED, WS_ISDIRTY, WS_MAP_CONTINUE, ws_map_dirty(), WS_MAP_FAIL, and WS_MAP_SUCCESS.
Referenced by allocate_disk_structures(), au_change_owner(), do_alter_change_col_comment(), do_alter_change_default_cs_coll(), do_alter_change_tbl_comment(), do_alter_clause_change_attribute(), do_create_entity(), do_create_partition(), do_prepare_update(), ldr_finish_context(), locator_add_class(), locator_add_root(), locator_check_object_and_get_class(), locator_create_heap_if_needed(), locator_lockhint_classes(), locator_remove_class(), obt_apply_assignments(), pt_set_class_chn(), pt_to_insert_xasl(), pt_to_merge_insert_xasl(), pt_to_merge_update_xasl(), pt_to_update_xasl(), sm_drop_index(), sm_exist_index(), sm_flush_and_decache_objects_internal(), sm_get_class_with_statistics(), sm_truncate_using_delete(), sm_update_all_statistics(), and sm_update_statistics().
int locator_flush_for_multi_update (MOP class_mop)
Definition at line 5401 of file locator_cl.c.
References DB_FETCH_READ, END_MULTI_UPDATE, ER_FAILED, error(), IS_MULTI_UPDATE, locator_fetch_class(), locator_manyobj_flag_set(), locator_mflush(), locator_mflush_end(), locator_mflush_force(), locator_mflush_initialize(), MANY_MFLUSHES, locator_mflush_cache::mobjs, NO_ERROR, NULL, sm_ch_heap(), START_MULTI_UPDATE, ws_map_class_dirty(), WS_MAP_FAIL, and WS_MAP_SUCCESS.
Referenced by sm_flush_for_multi_update().
int locator_flush_instance (MOP mop)
Definition at line 5236 of file locator_cl.c.
References DECACHE, DONT_DECACHE, and locator_internal_flush_instance().
Referenced by delete_list_by_oids(), do_alter_trigger(), do_change_auto_increment_serial(), do_reset_auto_increment_serial(), jsp_add_stored_procedure(), jsp_add_stored_procedure_argument(), locator_lock_nested(), obt_apply_assignments(), tr_drop_trigger_internal(), tr_rename_trigger(), update_object_tuple(), and ws_identifier_with_check().
int locator_flush_replication_info (REPL_INFO * repl_info)
Definition at line 6869 of file locator_cl.c.
References repl_set_info().
Referenced by do_replicate_statement().
void locator_free_list_mops (LIST_MOPS * mops)
Definition at line 2978 of file locator_cl.c.
References free_and_init, i, list_mops::mops, NULL, and list_mops::num.
Referenced by compactdb_start(), db_get_all_chosen_classes(), do_reclaim_class_addresses(), locator_fun_get_all_mops(), locator_save_nested_mops(), sm_fetch_all_base_classes(), sm_fetch_all_classes(), sm_fetch_all_objects_internal(), sm_force_write_all_classes(), sm_mark_system_classes(), smt_change_query_spec(), and unloaddb().
LIST_MOPS* locator_get_all_class_mops (DB_FETCH_MODE purpose, int(*)(MOBJ class_obj) fun)
Definition at line 2861 of file locator_cl.c.
References locator_fun_get_all_mops(), NULL, and sm_Root_class_mop.
Referenced by db_get_all_chosen_classes(), and do_reclaim_class_addresses().
LIST_MOPS* locator_get_all_mops (MOP class_mop, DB_FETCH_MODE class_purpose, LC_FETCH_VERSION_TYPE * force_fetch_version_type)
Definition at line 2839 of file locator_cl.c.
References locator_fun_get_all_mops(), and NULL.
Referenced by compactdb_start(), sm_fetch_all_base_classes(), sm_fetch_all_classes(), sm_fetch_all_objects_internal(), sm_force_write_all_classes(), sm_mark_system_classes(), smt_change_query_spec(), and unloaddb().
int locator_get_append_lsa (struct log_lsa * lsa)
Definition at line 6882 of file locator_cl.c.
References repl_log_get_append_lsa().
Referenced by extract_objects().
int locator_get_cache_coherency_number (MOP mop)
Definition at line 2171 of file locator_cl.c.
References DB_FETCH_READ, LC_CLASS, LC_FETCH_CURRENT_VERSION, LC_INSTANCE, LC_OBJECT, locator_fetch_mode_to_lock(), locator_is_root(), locator_lock(), NO_ERROR, NULL, NULL_CHN, TM_TRAN_READ_FETCH_VERSION, ws_chn(), ws_class_mop(), ws_find(), and WS_FIND_MOP_DELETED.
Referenced by db_chn(), pt_has_modified_class_helper(), and pt_set_class_chn().
MOBJ locator_has_heap (MOP class_mop)
Definition at line 5761 of file locator_cl.c.
References locator_create_heap_if_needed().
Referenced by boot_define_attribute(), boot_define_charsets(), boot_define_class(), boot_define_class_authorization(), boot_define_collations(), boot_define_data_type(), boot_define_domain(), boot_define_dual(), boot_define_ha_apply_info(), boot_define_index(), boot_define_index_key(), boot_define_meth_argument(), boot_define_meth_file(), boot_define_meth_sig(), boot_define_method(), boot_define_partition(), boot_define_query_spec(), boot_define_serial(), boot_define_stored_procedure(), and boot_define_stored_procedure_arguments().
int locator_is_class (MOP mop, DB_FETCH_MODE hint_purpose)
Definition at line 239 of file locator_cl.c.
References er_errid(), er_stack_pop(), er_stack_pop_and_keep_error(), er_stack_push(), error(), locator_fetch_object(), locator_is_root(), NO_ERROR, NULL, locator_mflush_temp_oid::obj, TM_TRAN_READ_FETCH_VERSION, ws_class_mop(), and WS_ISVID.
Referenced by assign_set_value(), db_instance_equal(), db_is_any_class(), db_is_class(), db_is_real_instance(), db_is_updatable_attribute(), db_is_updatable_object(), db_is_vclass(), do_reclaim_class_addresses(), fetch_class(), find_attribute(), get_set_value(), help_describe_mop(), help_print_obj(), object_description::init(), class_description::init(), obj_copy(), obj_delete(), obj_find_object_by_pkey(), obj_isinstance(), obj_locate_attribute(), obj_lock(), obj_set_att(), obt_def_object(), obt_edit_object(), pt_flush_classes(), pt_spec_to_xasl_class_oid_list(), pt_to_insert_xasl(), pt_to_merge_insert_xasl(), sm_delete_class_mop(), sm_fetch_all_objects_internal(), sm_flush_and_decache_objects(), sm_get_attribute_descriptor(), sm_get_ch_heap(), sm_get_class(), sm_get_class_flag(), sm_get_class_repid(), sm_get_class_with_statistics(), sm_get_method_descriptor(), sm_get_statistics_force(), sm_is_partitioned_class(), sm_object_size_quick(), sm_update_statistics(), smt_copy_class_mop(), smt_edit_class_mop(), and ws_identifier_with_check().
bool locator_is_root (MOP mop)
Definition at line 212 of file locator_cl.c.
References sm_Root_class_mop, and ws_mop_compare().
Referenced by au_fetch_class_internal(), help_print_obj(), class_description::init(), locator_assign_permanent_oid(), locator_cache_lock_set(), locator_cache_not_have_object(), locator_does_exist_object(), locator_fetch_class(), locator_fetch_instance(), locator_fetch_nested(), locator_fetch_object(), locator_flush_all_instances(), locator_fun_get_all_mops(), locator_get_cache_coherency_number(), locator_is_class(), locator_mflush(), locator_save_nested_mops(), sm_decache_instances_after_query_executed_with_commit(), and sm_is_partitioned_class().
LC_FIND_CLASSNAME locator_lockhint_classes (int num_classes, const char ** many_classnames, LOCK * many_locks, int * need_subclasses, LC_PREFETCH_FLAGS * flags, int quit_on_errors, LOCK lock_rr_tran)
Definition at line 6260 of file locator_cl.c.
References ARG_FILE_LINE, assert, lc_lockhint_class::chn, lc_lock_hint::classes, COPY_OID, er_errid(), ER_ERROR_SEVERITY, ER_LK_UNILATERALLY_ABORTED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, i, LC_CLASSNAME_ERROR, LC_CLASSNAME_EXIST, LC_PREF_FLAG_COUNT_OPTIM, locator_cache(), locator_cache_lock_lockhint_classes(), locator_fetch_lockhint_classes(), locator_find_lockhint_class_oids(), locator_flush_class(), locator_free_copy_area(), locator_free_lockhint(), lock_Conv, MAX_FETCH_SIZE, NA_LOCK, NO_ERROR, NULL, NULL_CHN, NULL_LOCK, lc_lock_hint::num_classes, lc_lock_hint::num_classes_processed, lc_lockhint_class::oid, OID_ISNULL, OID_ISTEMP, OID_SET_NULL, sm_Root_class_mop, tran_abort_only_client(), WS_CHN, ws_chn(), ws_find(), ws_find_class(), WS_FIND_MOP_DELETED, ws_get_lock(), WS_ISDIRTY, ws_mop(), and ws_oid().
Referenced by do_check_for_empty_classes_in_delete(), ldr_find_class(), lockhint_subclasses(), and pt_class_pre_fetch().
MOBJ locator_prepare_rename_class (MOP class_mop, const char * old_classname, const char * new_classname)
Definition at line 5975 of file locator_cl.c.
References ARG_FILE_LINE, DB_FETCH_WRITE, ER_ERROR_SEVERITY, ER_LC_CLASSNAME_EXIST, er_set(), LC_CLASSNAME_EXIST, LC_CLASSNAME_RESERVED_RENAME, locator_fetch_class(), locator_rename_class_name(), NULL, NULL_LOCK, ws_add_classname(), ws_dirty(), ws_drop_classname(), ws_find_class(), ws_get_lock(), WS_IS_DELETED, and ws_oid().
Referenced by sm_rename_class().
int locator_remove_class (MOP class_mop)
Definition at line 5858 of file locator_cl.c.
References BOOT_IS_CLIENT_RESTARTED, DB_FETCH_WRITE, ER_FAILED, error(), vfid::fileid, heap_destroy_newly_created(), LC_CLASSNAME_DELETED, locator_delete_class_name(), locator_fetch_class(), locator_flush_class(), locator_instance_decache(), NO_ERROR, NULL, NULL_FILEID, vid_oid::oid, db_object::oid_info, sm_ch_heap(), sm_ch_name(), hfid::vfid, ws_dirty(), ws_map_class(), and ws_mark_deleted().
Referenced by sm_delete_class_mop().
void locator_remove_instance (MOP mop)
Definition at line 5916 of file locator_cl.c.
References ws_mark_deleted().
Referenced by obj_delete().
int locator_repl_flush_all (void)
Definition at line 5500 of file locator_cl.c.
References DONT_DECACHE, ER_LC_PARTIALLY_FAILED_TO_FLUSH, error(), locator_mflush_end(), locator_mflush_initialize(), locator_repl_mflush(), locator_repl_mflush_force(), MANY_MFLUSHES, NO_ERROR, and NULL.
Referenced by la_flush_repl_items().
LC_FIND_CLASSNAME locator_reserve_class_name (const char * class_name, OID * class_oid)
Definition at line 179 of file locator_cl.c.
References locator_reserve_class_names().
Referenced by db_create_class(), db_create_vclass(), dbt_reserve_name(), and locator_add_root().
void locator_set_sig_interrupt (int set)
Definition at line 193 of file locator_cl.c.
References lc_Is_siginterrupt, and log_set_interrupt().
Referenced by db_set_interrupt().
void locator_synch_isolation_incons (void)
Definition at line 6171 of file locator_cl.c.
References locator_cache(), locator_free_copy_area(), locator_notify_isolation_incons(), NULL, TM_TRAN_ISOLATION, TRAN_REPEATABLE_READ, and TRAN_SERIALIZABLE.
Referenced by db_synchronize_cache().
MOBJ locator_update_class (MOP mop)
Definition at line 5938 of file locator_cl.c.
References DB_FETCH_WRITE, locator_fetch_class(), NULL, and ws_dirty().
Referenced by allocate_disk_structures(), fetch_class(), install_new_representation(), sm_drop_index(), and sm_exist_index().
MOBJ locator_update_instance (MOP mop)
Definition at line 6035 of file locator_cl.c.
References DB_FETCH_WRITE, LC_FETCH_MVCC_VERSION, locator_fetch_instance(), locator_lock_set(), locator_update_tree_classes(), NULL, SCH_M_LOCK, ws_dirty(), and X_LOCK.
Referenced by fetch_instance().
int locator_update_tree_classes (MOP * classes_mop_set, int num_classes)
Referenced by locator_update_instance().