CUBRID Engine: src/transaction/log_applier.c File Reference
log_applier.c File Reference
#include <unistd.h>
#include <errno.h>
#include <fcntl.h>
#include <sys/time.h>
#include <signal.h>
#include <pthread.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/socket.h>
#include <sys/un.h>
#include "log_applier.h"
#include "authenticate.h"
#include "porting.h"
#include "utility.h"
#include "environment_variable.h"
#include "message_catalog.h"
#include "msgcat_set_log.hpp"
#include "log_compress.h"
#include "log_lsa.hpp"
#include "parser.h"
#include "object_primitive.h"
#include "object_representation.h"
#include "db_value_printer.hpp"
#include "db.h"
#include "object_accessor.h"
#include "locator_cl.h"
#include "connection_cl.h"
#include "network_interface_cl.h"
#include "transform.h"
#include "file_io.h"
#include "memory_hash.h"
#include "schema_manager.h"
#include "log_applier_sql_log.h"
#include "util_func.h"
#include "dbtype.h"
#include "heartbeat.h"
#include "mem_block.hpp"
#include "string_buffer.hpp"
Classes
struct la_cache_buffer
struct la_cache_buffer_area
struct la_cache_pb
struct la_repl_filter
struct la_act_log
struct la_arv_log
struct la_item
struct la_apply
struct la_commit
struct la_info
struct la_ovf_first_part
struct la_ovf_rest_parts
struct la_ovf_page_list
struct la_recdes_pool
struct la_ha_apply_info
Macros
#define LA_DEFAULT_CACHE_BUFFER_SIZE 100
#define LA_MAX_REPL_ITEM_WITHOUT_RELEASE_PB 50
#define LA_MAX_UNFLUSHED_REPL_ITEMS 200
#define LA_DEFAULT_LOG_PAGE_SIZE 4096
#define LA_GET_PAGE_RETRY_COUNT 10
#define LA_REPL_LIST_COUNT 50
#define LA_PAGE_DOESNOT_EXIST 0
#define LA_PAGE_EXST_IN_ACTIVE_LOG 1
#define LA_PAGE_EXST_IN_ARCHIVE_LOG 2
#define LA_STATUS_BUSY 1
#define LA_STATUS_IDLE 0
#define LA_LOCK_SUFFIX "_lgla__lock"
#define LA_QUERY_BUF_SIZE 2048
#define LA_MAX_REPL_ITEMS 1000
#define LA_NUM_DELAY_HISTORY 10
#define LA_MAX_TOLERABLE_DELAY 2
#define LA_REINIT_COMMIT_INTERVAL 10
#define LA_WS_CULL_MOPS_PER_APPLY (100000)
#define LA_WS_CULL_MOPS_INTERVAL (180)
#define LA_WS_CULL_MOPS_PER_APPLY_MIN (100)
#define LA_WS_CULL_MOPS_INTERVAL_MIN (2)
#define LA_NUM_REPL_FILTER 50
#define LA_LOG_IS_IN_ARCHIVE(pageid) ((pageid) < la_Info.act_log.log_hdr->nxarv_pageid)
#define SIZEOF_LA_CACHE_LOG_BUFFER(io_pagesize) (offsetof(LA_CACHE_BUFFER, logpage) + (io_pagesize))
#define LA_LOGAREA_SIZE (la_Info.act_log.db_logpagesize - SSIZEOF(LOG_HDRPAGE))
#define LA_LOG_READ_ADVANCE_WHEN_DOESNT_FIT(result, length, offset, pageid, pgptr)
#define LA_LOG_READ_ALIGN(result, offset, pageid, log_pgptr)
#define LA_LOG_READ_ADD_ALIGN(result, add, offset, pageid, log_pgptr)
#define LA_SLEEP(sec, usec)
#define LA_MOVE_INSIDE_RECORD(rec, dest_offset, src_offset)
#define LA_IN_VALUE_COUNT 2
#define LA_OUT_VALUE_COUNT 23
#define LA_IN_VALUE_COUNT 15
#define LA_IN_VALUE_COUNT 2
#define LA_IN_VALUE_COUNT 3
#define LA_IN_VALUE_COUNT 22
#define LA_IN_VALUE_COUNT 2
Typedefs
typedef struct la_cache_buffer LA_CACHE_BUFFER
typedef struct la_cache_buffer_area LA_CACHE_BUFFER_AREA
typedef struct la_cache_pb LA_CACHE_PB
typedef struct la_repl_filter LA_REPL_FILTER
typedef struct la_act_log LA_ACT_LOG
typedef struct la_arv_log LA_ARV_LOG
typedef struct la_item LA_ITEM
typedef struct la_apply LA_APPLY
typedef struct la_commit LA_COMMIT
typedef struct la_info LA_INFO
typedef struct la_ovf_first_part LA_OVF_FIRST_PART
typedef struct la_ovf_rest_parts LA_OVF_REST_PARTS
typedef struct la_ovf_page_list LA_OVF_PAGE_LIST
typedef struct la_recdes_pool LA_RECDES_POOL
typedef struct la_ha_apply_info LA_HA_APPLY_INFO
Functions
static void la_shutdown_by_signal (int)
static void la_init_ha_apply_info (LA_HA_APPLY_INFO *ha_apply_info)
static LOG_PHY_PAGEID la_log_phypageid (LOG_PAGEID logical_pageid)
static int la_log_io_open (const char *vlabel, int flags, int mode)
static int la_log_io_read (char *vname, int vdes, void *io_pgptr, LOG_PHY_PAGEID pageid, int pagesize)
static int la_log_io_read_with_max_retries (char *vname, int vdes, void *io_pgptr, LOG_PHY_PAGEID pageid, int pagesize, int retries)
static int la_find_archive_num (int *arv_log_num, LOG_PAGEID pageid)
static int la_get_range_of_archive (int arv_log_num, LOG_PAGEID *fpageid, DKNPAGES *npages)
static int la_log_fetch_from_archive (LOG_PAGEID pageid, char *data)
static int la_log_fetch (LOG_PAGEID pageid, LA_CACHE_BUFFER *cache_buffer)
static int la_expand_cache_log_buffer (LA_CACHE_PB *cache_pb, int slb_cnt, int slb_size)
static LA_CACHE_BUFFER * la_cache_buffer_replace (LA_CACHE_PB *cache_pb, LOG_PAGEID pageid, int io_pagesize, int buffer_size)
static LA_CACHE_BUFFER * la_get_page_buffer (LOG_PAGEID pageid)
static LOG_PAGE * la_get_page (LOG_PAGEID pageid)
static void la_release_page_buffer (LOG_PAGEID pageid)
static void la_release_all_page_buffers (LOG_PAGEID except_pageid)
static void la_invalidate_page_buffer (LA_CACHE_BUFFER *cache_buffer)
static void la_decache_page_buffers (LOG_PAGEID from, LOG_PAGEID to)
static int la_find_required_lsa (LOG_LSA *required_lsa)
static int la_get_ha_apply_info (const char *log_path, const char *prefix_name, LA_HA_APPLY_INFO *ha_apply_info)
static int la_insert_ha_apply_info (DB_DATETIME *creation_time)
static int la_update_ha_apply_info_start_time (void)
static int la_get_last_ha_applied_info (void)
static int la_update_ha_last_applied_info (void)
static int la_delete_ha_apply_info (void)
static bool la_ignore_on_error (int errid)
static bool la_retry_on_error (int errid)
static int la_init_recdes_pool (int page_size, int num_recdes)
static RECDES * la_assign_recdes_from_pool (void)
static int la_realloc_recdes_data (RECDES *recdes, int data_size)
static void la_clear_recdes_pool (void)
static LA_CACHE_PB * la_init_cache_pb (void)
static unsigned int log_pageid_hash (const void *key, unsigned int htsize)
static int la_init_cache_log_buffer (LA_CACHE_PB *cache_pb, int slb_cnt, int slb_size)
static int la_fetch_log_hdr (LA_ACT_LOG *act_log)
static int la_find_log_pagesize (LA_ACT_LOG *act_log, const char *logpath, const char *dbname, bool check_charset)
static bool la_apply_pre (void)
static int la_does_page_exist (LOG_PAGEID pageid)
static int la_init_repl_lists (bool need_realloc)
static bool la_is_repl_lists_empty ()
static LA_APPLY * la_find_apply_list (int tranid)
static void la_log_copy_fromlog (char *rec_type, char *area, int length, LOG_PAGEID log_pageid, PGLENGTH log_offset, LOG_PAGE *log_pgptr)
static LA_ITEM * la_new_repl_item (LOG_LSA *lsa, LOG_LSA *target_lsa)
static void la_add_repl_item (LA_APPLY *apply, LA_ITEM *item)
static DB_VALUE * la_get_item_pk_value (LA_ITEM *item)
static LA_ITEM * la_make_repl_item (LOG_PAGE *log_pgptr, int log_type, int tranid, LOG_LSA *lsa)
static void la_unlink_repl_item (LA_APPLY *apply, LA_ITEM *item)
static void la_free_repl_item (LA_APPLY *apply, LA_ITEM *item)
static void la_free_all_repl_items_except_head (LA_APPLY *apply)
static void la_free_all_repl_items (LA_APPLY *apply)
static void la_free_and_add_next_repl_item (LA_APPLY *apply, LA_ITEM *next_item, LOG_LSA *lsa)
static void la_clear_applied_info (LA_APPLY *apply)
static void la_clear_all_repl_and_commit_list (void)
static int la_set_repl_log (LOG_PAGE *log_pgptr, int log_type, int tranid, LOG_LSA *lsa)
static int la_add_node_into_la_commit_list (int tranid, LOG_LSA *lsa, int type, time_t eot_time)
static time_t la_retrieve_eot_time (LOG_PAGE *pgptr, LOG_LSA *lsa)
static int la_get_current (OR_BUF *buf, SM_CLASS *sm_class, int bound_bit_flag, DB_OTMPL *def, DB_VALUE *key, int offset_size)
static void la_make_room_for_mvcc_insid (RECDES *recdes)
static int la_disk_to_obj (MOBJ classobj, RECDES *record, DB_OTMPL *def, DB_VALUE *key)
static char * la_get_zipped_data (char *undo_data, int undo_length, bool is_diff, bool is_undo_zip, bool is_overflow, char **rec_type, char **data, int *length)
static int la_get_undoredo_diff (LOG_PAGE **pgptr, LOG_PAGEID *pageid, PGLENGTH *offset, bool *is_undo_zip, char **undo_data, int *undo_length)
static int la_get_log_data (LOG_RECORD_HEADER *lrec, LOG_LSA *lsa, LOG_PAGE *pgptr, unsigned int match_rcvindex, unsigned int *rcvindex, void **logs, char **rec_type, char **data, int *d_length)
static int la_get_overflow_recdes (LOG_RECORD_HEADER *lrec, void *logs, RECDES *recdes, unsigned int rcvindex)
static int la_get_next_update_log (LOG_RECORD_HEADER *prev_lrec, LOG_PAGE *pgptr, void **logs, char **rec_type, char **data, int *d_length)
static int la_get_relocation_recdes (LOG_RECORD_HEADER *lrec, LOG_PAGE *pgptr, unsigned int match_rcvindex, void **logs, char **rec_type, RECDES *recdes)
static int la_get_recdes (LOG_LSA *lsa, LOG_PAGE *pgptr, RECDES *recdes, unsigned int *rcvindex, char *rec_type)
static int la_apply_delete_log (LA_ITEM *item)
static int la_apply_update_log (LA_ITEM *item)
static int la_apply_insert_log (LA_ITEM *item)
static int la_update_query_execute (const char *sql, bool au_disable)
static int la_update_query_execute_with_values (const char *sql, int arg_count, DB_VALUE *vals, bool au_disable)
static int la_apply_statement_log (LA_ITEM *item)
static int la_apply_repl_log (int tranid, int rectype, LOG_LSA *commit_lsa, int *total_rows, LOG_PAGEID final_pageid)
static int la_apply_commit_list (LOG_LSA *lsa, LOG_PAGEID final_pageid)
static void la_free_repl_items_by_tranid (int tranid)
static int la_log_record_process (LOG_RECORD_HEADER *lrec, LOG_LSA *final, LOG_PAGE *pg_ptr)
static int la_change_state (void)
static int la_log_commit (bool update_commit_time)
static unsigned long la_get_mem_size (void)
static int la_check_mem_size (void)
static int la_check_time_commit (struct timeval *time, unsigned int threshold)
static void la_init (const char *log_path, const int max_mem_size)
static int la_check_duplicated (const char *logpath, const char *dbname, int *lockf_vdes, int *last_deleted_arv_num)
static int la_lock_dbname (int *lockf_vdes, char *db_name, char *log_path)
static int la_unlock_dbname (int *lockf_vdes, char *db_name, bool clear_owner)
static void la_shutdown (void)
static int la_remove_archive_logs (const char *db_name, int last_deleted_arv_num, int nxarv_num, int max_arv_count_to_delete)
static LA_ITEM * la_get_next_repl_item (LA_ITEM *item, bool is_long_trans, LOG_LSA *last_lsa)
static LA_ITEM * la_get_next_repl_item_from_list (LA_ITEM *item)
static LA_ITEM * la_get_next_repl_item_from_log (LA_ITEM *item, LOG_LSA *last_lsa)
static int la_commit_transaction (void)
static int la_find_last_deleted_arv_num (void)
static bool la_restart_on_bulk_flush_error (int errid)
static char * la_get_hostname_from_log_path (char *log_path)
static int la_delay_replica (time_t eot_time)
static float la_get_avg (int *array, int size)
static void la_get_adaptive_time_commit_interval (int *time_commit_interval, int *delay_hist)
static int la_flush_repl_items (bool immediate)
static bool la_need_filter_out (LA_ITEM *item)
static int la_create_repl_filter (void)
static void la_destroy_repl_filter (void)
static void la_print_repl_filter_info (void)
static int check_reinit_copylog (void)
bool la_force_shutdown (void)
static int la_update_ha_apply_info_log_record_time (time_t new_time)
static LA_APPLY * la_add_apply_list (int tranid)
static LOG_REC_HA_SERVER_STATE * la_get_ha_server_state (LOG_PAGE *pgptr, LOG_LSA *lsa)
static int la_repl_add_object (MOP classop, LA_ITEM *item, RECDES *recdes)
static int la_update_last_deleted_arv_num (int lockf_vdes, int last_deleted_arv_num)
void la_print_log_header (const char *database_name, LOG_HEADER *hdr, bool verbose)
void la_print_log_arv_header (const char *database_name, LOG_ARV_HEADER *hdr, bool verbose)
int la_log_page_check (const char *database_name, const char *log_path, INT64 page_num, bool check_applied_info, bool check_copied_info, bool check_replica_info, bool verbose, LOG_LSA *copied_eof_lsa, LOG_LSA *copied_append_lsa, LOG_LSA *applied_final_lsa)
void la_print_delay_info (LOG_LSA working_lsa, LOG_LSA target_lsa, float process_rate)
static int la_add_repl_filter (const char *classname)
int la_apply_log_file (const char *database_name, const char *log_path, const int max_mem_size)
Variables
LA_INFO la_Info
LA_RECDES_POOL la_recdes_pool
static bool la_applier_need_shutdown = false
static bool la_applier_shutdown_by_signal = false
static char la_slave_db_name [DB_MAX_IDENTIFIER_LENGTH+1]
static char la_peer_host [CUB_MAXHOSTNAMELEN+1]
static bool la_enable_sql_logging = false
Macro Definition Documentation
#define LA_DEFAULT_CACHE_BUFFER_SIZE 100
Definition at line 82 of file log_applier.c.
Referenced by la_init().
#define LA_DEFAULT_LOG_PAGE_SIZE 4096
Definition at line 85 of file log_applier.c.
Referenced by la_find_log_pagesize(), and la_init().
#define LA_GET_PAGE_RETRY_COUNT 10
Definition at line 86 of file log_applier.c.
Referenced by la_apply_log_file().
#define LA_IN_VALUE_COUNT 2
Referenced by la_delete_ha_apply_info(), la_get_ha_apply_info(), la_insert_ha_apply_info(), la_update_ha_apply_info_log_record_time(), la_update_ha_apply_info_start_time(), and la_update_ha_last_applied_info().
#define LA_IN_VALUE_COUNT 15
#define LA_IN_VALUE_COUNT 2
#define LA_IN_VALUE_COUNT 3
#define LA_IN_VALUE_COUNT 22
#define LA_IN_VALUE_COUNT 2
#define LA_LOCK_SUFFIX "_lgla__lock"
Definition at line 96 of file log_applier.c.
Referenced by la_check_duplicated().
#define LA_LOG_IS_IN_ARCHIVE (pageid) ((pageid) < la_Info.act_log.log_hdr->nxarv_pageid)
Definition at line 114 of file log_applier.c.
Referenced by la_log_fetch(), la_log_page_check(), and la_remove_archive_logs().
#define LA_LOG_READ_ADD_ALIGN (result, add, offset, pageid, log_pgptr)
Value:
do { \
    (offset) += (add); \
    LA_LOG_READ_ALIGN(result, (offset), (pageid), (log_pgptr));   \
  } while(0)
Definition at line 143 of file log_applier.c.
Referenced by la_get_log_data(), la_get_next_update_log(), and la_get_undoredo_diff().
#define LA_LOG_READ_ADVANCE_WHEN_DOESNT_FIT (result, length, offset, pageid, pgptr)
Value:
do { \
    if ((offset)+(length) >= LA_LOGAREA_SIZE) { \
      if (((pgptr) = la_get_page(++(pageid))) == NULL) { \
        result = ER_IO_READ; \
      } \
      (offset) = 0; \
    } \
  } while(0)
Definition at line 121 of file log_applier.c.
Referenced by la_get_ha_server_state(), la_get_log_data(), la_get_next_update_log(), la_log_copy_fromlog(), la_make_repl_item(), and la_retrieve_eot_time().
#define LA_LOG_READ_ALIGN (result, offset, pageid, log_pgptr)
Value:
do { \
    (offset) = DB_ALIGN((offset), MAX_ALIGNMENT); \
    while ((offset) >= LA_LOGAREA_SIZE) { \
      if (((log_pgptr) = la_get_page(++(pageid))) == NULL) { \
        result = ER_IO_READ; \
      } \
      (offset) -= LA_LOGAREA_SIZE; \
      (offset) = DB_ALIGN((offset), MAX_ALIGNMENT); \
    } \
  } while(0)
Definition at line 131 of file log_applier.c.
Referenced by la_get_log_data(), la_get_next_update_log(), la_make_repl_item(), and la_retrieve_eot_time().
#define LA_LOGAREA_SIZE (la_Info.act_log.db_logpagesize - SSIZEOF(LOG_HDRPAGE))
Definition at line 120 of file log_applier.c.
Referenced by la_log_copy_fromlog().
#define LA_MAX_REPL_ITEM_WITHOUT_RELEASE_PB 50
Definition at line 83 of file log_applier.c.
Referenced by la_apply_repl_log().
#define LA_MAX_REPL_ITEMS 1000
Definition at line 100 of file log_applier.c.
Referenced by la_set_repl_log().
#define LA_MAX_TOLERABLE_DELAY 2
Definition at line 104 of file log_applier.c.
Referenced by la_get_adaptive_time_commit_interval().
#define LA_MAX_UNFLUSHED_REPL_ITEMS 200
Definition at line 84 of file log_applier.c.
Referenced by la_apply_log_file(), and la_flush_repl_items().
#define LA_MOVE_INSIDE_RECORD (rec, dest_offset, src_offset)
Value:
do \
    { \
      assert ((rec) != NULL && (dest_offset) >= 0 && (src_offset) >= 0); \
      assert (((rec)->length - (src_offset)) >= 0); \
      assert (((rec)->area_size <= 0) || ((rec)->area_size >= (rec)->length)); \
      assert (((rec)->area_size <= 0) \
              || (((rec)->length + ((dest_offset) - (src_offset))) \
                  <= (rec)->area_size)); \
      if ((dest_offset) != (src_offset)) \
        { \
          memmove ((rec)->data + (dest_offset), (rec)->data + (src_offset), \
                   (rec)->length - (src_offset)); \
          (rec)->length = (rec)->length + ((dest_offset) - (src_offset)); \
        } \
    } \
  while (0)
Definition at line 158 of file log_applier.c.
Referenced by la_make_room_for_mvcc_insid().
#define LA_NUM_DELAY_HISTORY 10
Definition at line 103 of file log_applier.c.
Referenced by la_apply_log_file(), and la_get_adaptive_time_commit_interval().
#define LA_NUM_REPL_FILTER 50
Definition at line 112 of file log_applier.c.
Referenced by la_add_repl_filter(), and la_create_repl_filter().
#define LA_OUT_VALUE_COUNT 23
Referenced by la_get_ha_apply_info().
#define LA_PAGE_DOESNOT_EXIST 0
Definition at line 89 of file log_applier.c.
Referenced by la_apply_log_file(), and la_does_page_exist().
#define LA_PAGE_EXST_IN_ACTIVE_LOG 1
Definition at line 90 of file log_applier.c.
Referenced by la_does_page_exist().
#define LA_PAGE_EXST_IN_ARCHIVE_LOG 2
Definition at line 91 of file log_applier.c.
Referenced by la_does_page_exist(), and la_log_record_process().
#define LA_QUERY_BUF_SIZE 2048
Definition at line 98 of file log_applier.c.
Referenced by la_delete_ha_apply_info(), la_get_ha_apply_info(), la_insert_ha_apply_info(), la_update_ha_apply_info_log_record_time(), la_update_ha_apply_info_start_time(), and la_update_ha_last_applied_info().
#define LA_REINIT_COMMIT_INTERVAL 10
Definition at line 105 of file log_applier.c.
Referenced by la_get_adaptive_time_commit_interval().
#define LA_REPL_LIST_COUNT 50
Definition at line 87 of file log_applier.c.
Referenced by la_init_repl_lists().
#define LA_SLEEP (sec, usec)
Value:
do { \
   struct timeval sleep_time_val; \
   sleep_time_val.tv_sec = (sec); \
   sleep_time_val.tv_usec = (usec); \
   select (0, 0, 0, 0, &sleep_time_val); \
 } while(0)
Definition at line 149 of file log_applier.c.
Referenced by la_apply_log_file(), la_apply_repl_log(), la_delay_replica(), la_find_log_pagesize(), la_lock_dbname(), and la_unlock_dbname().
#define LA_STATUS_BUSY 1
Definition at line 93 of file log_applier.c.
Referenced by la_check_time_commit(), and la_log_record_process().
#define LA_STATUS_IDLE 0
Definition at line 94 of file log_applier.c.
Referenced by la_check_time_commit(), la_get_ha_apply_info(), and la_log_record_process().
#define LA_WS_CULL_MOPS_INTERVAL (180)
Definition at line 108 of file log_applier.c.
Referenced by la_commit_transaction().
#define LA_WS_CULL_MOPS_INTERVAL_MIN (2)
Definition at line 110 of file log_applier.c.
Referenced by la_commit_transaction().
#define LA_WS_CULL_MOPS_PER_APPLY (100000)
Definition at line 107 of file log_applier.c.
Referenced by la_commit_transaction().
#define LA_WS_CULL_MOPS_PER_APPLY_MIN (100)
Definition at line 109 of file log_applier.c.
Referenced by la_commit_transaction().
#define SIZEOF_LA_CACHE_LOG_BUFFER (io_pagesize) (offsetof(LA_CACHE_BUFFER, logpage) + (io_pagesize))
Definition at line 117 of file log_applier.c.
Referenced by la_apply_log_file(), and la_cache_buffer_replace().
Typedef Documentation
typedef struct la_act_log LA_ACT_LOG
Definition at line 214 of file log_applier.c.
typedef struct la_apply LA_APPLY
Definition at line 253 of file log_applier.c.
typedef struct la_arv_log LA_ARV_LOG
Definition at line 225 of file log_applier.c.
typedef struct la_cache_buffer LA_CACHE_BUFFER
Definition at line 176 of file log_applier.c.
typedef struct la_cache_buffer_area LA_CACHE_BUFFER_AREA
Definition at line 189 of file log_applier.c.
typedef struct la_cache_pb LA_CACHE_PB
Definition at line 196 of file log_applier.c.
typedef struct la_commit LA_COMMIT
Definition at line 265 of file log_applier.c.
typedef struct la_ha_apply_info LA_HA_APPLY_INFO
Definition at line 390 of file log_applier.c.
typedef struct la_info LA_INFO
Definition at line 278 of file log_applier.c.
typedef struct la_item LA_ITEM
Definition at line 235 of file log_applier.c.
typedef struct la_ovf_first_part LA_OVF_FIRST_PART
Definition at line 354 of file log_applier.c.
typedef struct la_ovf_page_list LA_OVF_PAGE_LIST
Definition at line 370 of file log_applier.c.
typedef struct la_ovf_rest_parts LA_OVF_REST_PARTS
Definition at line 362 of file log_applier.c.
typedef struct la_recdes_pool LA_RECDES_POOL
Definition at line 379 of file log_applier.c.
typedef struct la_repl_filter LA_REPL_FILTER
Definition at line 205 of file log_applier.c.
Function Documentation
static int check_reinit_copylog (void) static
Definition at line 7771 of file log_applier.c.
References la_info::act_log, ER_FAILED, error(), la_fetch_log_hdr(), la_act_log::log_hdr, log_header::mark_will_del, NO_ERROR, and la_info::reinit_copylog.
Referenced by la_apply_log_file(), and la_log_fetch_from_archive().
static LA_APPLY* la_add_apply_list (int tranid) static
Definition at line 2893 of file log_applier.c.
References la_info::cur_repl, i, la_find_apply_list(), la_init_repl_lists(), NO_ERROR, NULL, la_info::repl_cnt, la_info::repl_lists, and la_apply::tranid.
Referenced by la_log_record_process().
static int la_add_node_into_la_commit_list (int tranid, LOG_LSA * lsa, int type, time_t eot_time) static
Definition at line 3477 of file log_applier.c.
References ARG_FILE_LINE, la_info::commit_head, la_info::commit_tail, DB_SIZEOF, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), la_commit::log_lsa, la_commit::log_record_time, LSA_COPY(), la_commit::next, NO_ERROR, NULL, la_commit::prev, la_commit::tranid, and la_commit::type.
Referenced by la_log_record_process().
static int la_add_repl_filter (const char * classname) static
Definition at line 7577 of file log_applier.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), LA_NUM_REPL_FILTER, la_repl_filter::list, la_repl_filter::list_size, NO_ERROR, NULL, la_repl_filter::num_filters, la_info::repl_filter, strdup(), and strlen.
Referenced by la_create_repl_filter().
static void la_add_repl_item (LA_APPLY * apply, LA_ITEM * item) static
Definition at line 3054 of file log_applier.c.
References assert, la_apply::head, la_item::next, NULL, la_apply::num_items, la_item::prev, and la_apply::tail.
Referenced by la_free_and_add_next_repl_item(), and la_set_repl_log().
static int la_apply_commit_list (LOG_LSA * lsa, LOG_PAGEID final_pageid) static
Definition at line 5818 of file log_applier.c.
References ARG_FILE_LINE, la_info::commit_head, la_info::commit_tail, er_log_debug, error(), free_and_init, la_apply_repl_log(), LOG_ABORT, LOG_COMMIT, la_commit::log_lsa, la_commit::log_record_time, la_info::log_record_time, LOG_SYSOP_END, LSA_COPY(), LSA_SET_NULL(), la_commit::next, NO_ERROR, NULL, la_commit::prev, la_info::total_rows, la_commit::tranid, and la_commit::type.
Referenced by la_log_record_process().
static int la_apply_delete_log (LA_ITEM * item) static
Definition at line 4885 of file log_applier.c.
References ARG_FILE_LINE, assert, la_item::class_name, string_buffer::clear(), DB_FETCH_CLREAD_INSTREAD, db_find_class(), db_sprint_value(), la_info::delete_counter, er_errid(), ER_ERROR_SEVERITY, ER_HA_GENERIC_ERROR, ER_HA_LA_FAILED_TO_APPLY_DELETE, er_log_debug, er_msg(), er_set(), er_stack_pop(), er_stack_push(), error(), la_info::fail_counter, string_buffer::get_buffer(), la_item::key, la_enable_sql_logging, la_flush_repl_items(), la_get_item_pk_value(), la_repl_add_object(), locator_fetch_class(), NO_ERROR, NULL, la_info::num_unflushed, and sl_write_delete_sql().
Referenced by la_apply_repl_log().
static int la_apply_insert_log (LA_ITEM * item) static
Definition at line 5152 of file log_applier.c.
References ARG_FILE_LINE, assert, AU_RESTORE, AU_SAVE_AND_DISABLE, la_item::class_name, string_buffer::clear(), DB_FETCH_CLREAD_INSTREAD, db_find_class(), db_sprint_value(), dbt_abort_object(), dbt_create_object_internal(), er_errid(), ER_ERROR_SEVERITY, ER_FAILED, ER_HA_GENERIC_ERROR, ER_HA_LA_FAILED_TO_APPLY_INSERT, er_log_debug, er_msg(), ER_NET_CANT_CONNECT_SERVER, ER_OBJ_NO_CONNECT, er_set(), er_stack_pop(), er_stack_push(), error(), la_info::fail_counter, string_buffer::get_buffer(), la_info::insert_counter, la_assign_recdes_from_pool(), la_disk_to_obj(), la_enable_sql_logging, la_flush_repl_items(), la_get_item_pk_value(), la_get_page(), la_get_recdes(), la_release_page_buffer(), la_repl_add_object(), locator_fetch_class(), NO_ERROR, NULL, NULL_PAGEID, la_info::num_unflushed, obj_template::object, log_lsa::pageid, rc, REC_ASSIGN_ADDRESS, REC_RELOCATION, la_info::rec_type, RVHF_INSERT, RVHF_MVCC_INSERT, sl_write_insert_sql(), la_item::target_lsa, recdes::type, ws_decache(), and ws_release_user_instance().
Referenced by la_apply_repl_log().
int la_apply_log_file (const char * database_name, const char * log_path, const int max_mem_size)
Definition at line 7810 of file log_applier.c.
References la_info::act_log, log_header::append_lsa, la_info::apply_state, ARG_FILE_LINE, assert, assert_release, log_rec_header::back_lsa, la_info::cache_buffer_size, la_info::cache_pb, check_reinit_copylog(), la_info::committed_lsa, la_info::committed_rep_lsa, CUB_MAXHOSTNAMELEN, la_act_log::db_iopagesize, la_info::db_lockf_vdes, la_act_log::db_logpagesize, DB_MAX_IDENTIFIER_LENGTH, log_header::eof_lsa, er_errid(), ER_ERROR_SEVERITY, ER_HA_GENERIC_ERROR, ER_HA_LA_EXCEED_MAX_MEM_SIZE, ER_HA_LA_INVALID_REPL_LOG_PAGEID_OFFSET, ER_HA_LA_REPL_FILTER_GENERIC, ER_HA_LA_STARTED, ER_HA_LA_STOPPED_BY_SIGNAL, ER_HB_PROCESS_EVENT, ER_LC_FAILED_TO_FLUSH_REPL_ITEMS, ER_LC_PARTIALLY_FAILED_TO_FLUSH, er_log_debug, ER_LOG_PAGE_CORRUPTED, ER_NET_CANT_CONNECT_SERVER, ER_OBJ_NO_CONNECT, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), er_stack_pop(), er_stack_push(), error(), fileio_make_log_info_name(), la_info::final_lsa, log_rec_header::forw_lsa, log_header::ha_file_status, HA_LOG_APPLIER_STATE_DONE, HA_LOG_APPLIER_STATE_RECOVERING, log_header::ha_server_state, HA_SERVER_STATE_ACTIVE, HA_SERVER_STATE_DEAD, HA_SERVER_STATE_TO_BE_STANDBY, hb_Proc_shutdown, log_page::hdr, i, la_info::is_end_of_record, tde_cipher::is_loaded, la_info::is_role_changed, la_applier_need_shutdown, la_applier_shutdown_by_signal, la_apply_pre(), la_change_state(), la_check_duplicated(), la_check_mem_size(), la_check_time_commit(), la_create_repl_filter(), la_decache_page_buffers(), la_delete_ha_apply_info(), la_does_page_exist(), la_enable_sql_logging, la_find_last_deleted_arv_num(), la_find_log_pagesize(), la_get_adaptive_time_commit_interval(), la_get_hostname_from_log_path(), la_get_last_ha_applied_info(), la_get_page_buffer(), LA_GET_PAGE_RETRY_COUNT, la_init(), la_init_cache_log_buffer(), la_init_cache_pb(), la_init_recdes_pool(), la_invalidate_page_buffer(), la_log_commit(), la_log_record_process(), LA_MAX_UNFLUSHED_REPL_ITEMS, LA_NUM_DELAY_HISTORY, LA_PAGE_DOESNOT_EXIST, la_peer_host, la_print_repl_filter_info(), la_release_all_page_buffers(), la_remove_archive_logs(), la_shutdown(), la_shutdown_by_signal(), la_slave_db_name, LA_SLEEP, la_unlock_dbname(), la_update_last_deleted_arv_num(), la_info::last_deleted_archive_num, la_info::last_time_archive_deleted, LOG_END_OF_LOG, LOG_GET_LOG_RECORD_HEADER, LOG_HA_FILESTAT_SYNCHRONIZED, la_act_log::log_hdr, la_info::log_path, la_info::log_path_lockf_vdes, log_hdrpage::logical_pageid, la_info::loginf_path, la_cache_buffer::logpage, LOGPAGEID_MAX, LSA_COPY(), LSA_EQ(), LSA_GE(), LSA_GT(), LSA_ISNULL(), LSA_SET_NULL(), NO_ERROR, NULL, NULL_OFFSET, NULL_PAGEID, log_header::nxarv_num, log_lsa::offset, log_hdrpage::offset, os_set_signal_handler(), log_lsa::pageid, la_cache_buffer::pageid, prm_get_bool_value(), prm_get_integer_value(), PRM_ID_HA_APPLYLOGDB_LOG_WAIT_TIME_IN_SECS, PRM_ID_HA_APPLYLOGDB_MAX_COMMIT_INTERVAL_IN_MSECS, PRM_ID_HA_REPL_FILTER_TYPE, PRM_ID_HA_SQL_LOGGING, PRM_ID_REMOVE_LOG_ARCHIVES_INTERVAL, la_info::reinit_copylog, REPL_FILTER_NONE, la_info::required_lsa, SIZEOF_LA_CACHE_LOG_BUFFER, sl_init(), tde_Cipher, and log_rec_header::type.
Referenced by applylogdb().
static bool la_apply_pre (void) static
Definition at line 2697 of file log_applier.c.
References la_info::act_log, ARG_FILE_LINE, la_info::committed_lsa, la_act_log::db_iopagesize, DB_SIZEOF, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), la_info::final_lsa, log_zip_alloc(), LSA_COPY(), NULL, la_info::rec_type, la_info::redo_unzip_ptr, and la_info::undo_unzip_ptr.
Referenced by la_apply_log_file().
static int la_apply_repl_log (int tranid, int rectype, LOG_LSA * commit_lsa, int * total_rows, LOG_PAGEID final_pageid) static
Definition at line 5637 of file log_applier.c.
References ARG_FILE_LINE, assert, assert_release, la_item::class_name, string_buffer::clear(), la_info::committed_rep_lsa, db_error_string(), la_info::db_lockf_vdes, db_sprint_value(), er_errid(), ER_HA_GENERIC_ERROR, ER_LC_FAILED_TO_FLUSH_REPL_ITEMS, ER_LC_PARTIALLY_FAILED_TO_FLUSH, er_log_debug, ER_NET_CANT_CONNECT_SERVER, ER_NOTIFICATION_SEVERITY, ER_OBJ_NO_CONNECT, er_set(), error(), string_buffer::get_buffer(), la_apply::head, la_apply::is_long_trans, la_item::item_type, la_apply_delete_log(), la_apply_insert_log(), la_apply_statement_log(), la_apply_update_log(), la_clear_applied_info(), la_find_apply_list(), la_free_all_repl_items(), la_free_and_add_next_repl_item(), la_free_repl_item(), la_get_item_pk_value(), la_get_next_repl_item(), la_ignore_on_error(), la_lock_dbname(), LA_MAX_REPL_ITEM_WITHOUT_RELEASE_PB, la_need_filter_out(), la_release_all_page_buffers(), la_retry_on_error(), la_slave_db_name, LA_SLEEP, la_info::last_committed_lsa, la_info::last_committed_rep_lsa, la_apply::last_lsa, LOG_ABORT, la_info::log_path, LOG_REPLICATION_DATA, LOG_REPLICATION_STATEMENT, LOG_SYSOP_END, la_item::log_type, la_item::lsa, LSA_COPY(), LSA_GT(), LSA_LE(), NO_ERROR, NULL, NULL_PAGEID, RVREPL_DATA_DELETE, RVREPL_DATA_INSERT, RVREPL_DATA_UPDATE, RVREPL_DATA_UPDATE_END, and RVREPL_DATA_UPDATE_START.
Referenced by la_apply_commit_list().
static int la_apply_statement_log (LA_ITEM * item) static
Definition at line 5413 of file log_applier.c.
References ARG_FILE_LINE, assert, au_find_user(), AU_SET_USER, Au_user, la_item::class_name, CUBRID_STMT_ALTER_CLASS, CUBRID_STMT_ALTER_INDEX, CUBRID_STMT_ALTER_SERIAL, CUBRID_STMT_ALTER_STORED_PROCEDURE, CUBRID_STMT_ALTER_USER, CUBRID_STMT_CREATE_CLASS, CUBRID_STMT_CREATE_INDEX, CUBRID_STMT_CREATE_SERIAL, CUBRID_STMT_CREATE_STORED_PROCEDURE, CUBRID_STMT_CREATE_TRIGGER, CUBRID_STMT_CREATE_USER, CUBRID_STMT_DELETE, CUBRID_STMT_DROP_CLASS, CUBRID_STMT_DROP_DATABASE, CUBRID_STMT_DROP_INDEX, CUBRID_STMT_DROP_LABEL, CUBRID_STMT_DROP_SERIAL, CUBRID_STMT_DROP_STORED_PROCEDURE, CUBRID_STMT_DROP_TRIGGER, CUBRID_STMT_DROP_USER, CUBRID_STMT_GRANT, CUBRID_STMT_INSERT, CUBRID_STMT_REMOVE_TRIGGER, CUBRID_STMT_RENAME_CLASS, CUBRID_STMT_RENAME_TRIGGER, CUBRID_STMT_REVOKE, CUBRID_STMT_SET_TRIGGER, CUBRID_STMT_TRUNCATE, CUBRID_STMT_UPDATE, CUBRID_STMT_UPDATE_STATS, db_get_string(), db_reset_system_parameters_from_assignments(), db_set_system_parameters_for_ha_repl(), la_item::db_user, la_info::delete_counter, er_errid(), ER_ERROR_SEVERITY, ER_HA_GENERIC_ERROR, ER_HA_LA_FAILED_TO_APPLY_STATEMENT, er_log_debug, er_msg(), ER_NET_CANT_CONNECT_SERVER, ER_OBJ_NO_CONNECT, er_set(), er_stack_pop(), er_stack_push(), error(), la_info::fail_counter, la_item::ha_sys_prm, la_info::insert_counter, la_item::item_type, la_item::key, la_enable_sql_logging, la_flush_repl_items(), la_need_filter_out(), la_update_query_execute(), NO_ERROR, NULL, la_info::schema_counter, sl_write_statement_sql(), and la_info::update_counter.
Referenced by la_apply_repl_log().
static int la_apply_update_log (LA_ITEM * item) static
Definition at line 4967 of file log_applier.c.
References ARG_FILE_LINE, assert, AU_RESTORE, AU_SAVE_AND_DISABLE, la_item::class_name, string_buffer::clear(), DB_FETCH_CLREAD_INSTREAD, db_find_class(), db_sprint_value(), dbt_abort_object(), dbt_create_object_internal(), er_errid(), ER_ERROR_SEVERITY, ER_FAILED, ER_HA_GENERIC_ERROR, ER_HA_LA_FAILED_TO_APPLY_UPDATE, er_log_debug, er_msg(), ER_NET_CANT_CONNECT_SERVER, ER_OBJ_NO_CONNECT, er_set(), er_stack_pop(), er_stack_push(), error(), la_info::fail_counter, string_buffer::get_buffer(), la_item::key, la_assign_recdes_from_pool(), la_disk_to_obj(), la_enable_sql_logging, la_flush_repl_items(), la_get_item_pk_value(), la_get_page(), la_get_recdes(), la_release_page_buffer(), la_repl_add_object(), locator_fetch_class(), NO_ERROR, NULL, NULL_PAGEID, la_info::num_unflushed, obj_template::object, log_lsa::pageid, rc, REC_ASSIGN_ADDRESS, REC_RELOCATION, la_info::rec_type, RVHF_INSERT_NEWHOME, RVHF_MVCC_INSERT, RVHF_UPDATE, RVHF_UPDATE_NOTIFY_VACUUM, RVOVF_CHANGE_LINK, sl_write_update_sql(), la_item::target_lsa, recdes::type, la_info::update_counter, ws_decache(), and ws_release_user_instance().
Referenced by la_apply_repl_log().
static RECDES * la_assign_recdes_from_pool (void) static
Definition at line 2385 of file log_applier.c.
References la_recdes_pool::area, recdes::area_size, assert, recdes::data, la_recdes_pool::db_page_size, free_and_init, la_recdes_pool::is_initialized, recdes::length, la_recdes_pool::next_idx, NULL, la_recdes_pool::num_recdes, and la_recdes_pool::recdes_arr.
Referenced by la_apply_insert_log(), and la_apply_update_log().
static LA_CACHE_BUFFER * la_cache_buffer_replace (LA_CACHE_PB * cache_pb, LOG_PAGEID pageid, int io_pagesize, int buffer_size) static
Definition at line 1223 of file log_applier.c.
References error(), la_cache_buffer::fix_count, la_cache_pb::hash_table, i, la_expand_cache_log_buffer(), la_log_fetch(), la_cache_pb::log_buffer, mht_rem(), NO_ERROR, NULL, la_cache_pb::num_buffers, la_cache_buffer::pageid, la_cache_buffer::recently_free, and SIZEOF_LA_CACHE_LOG_BUFFER.
Referenced by la_get_page_buffer().
static int la_change_state (void) static
Definition at line 6295 of file log_applier.c.
References la_info::act_log, la_info::apply_state, ARG_FILE_LINE, boot_notify_ha_log_applier_state(), la_info::committed_lsa, css_ha_applier_state_string(), css_ha_server_state_string(), ER_ERROR_SEVERITY, ER_FAILED, ER_HA_GENERIC_ERROR, ER_HA_LA_FAILED_TO_CHANGE_STATE, er_log_debug, ER_NOTIFICATION_SEVERITY, er_set(), error(), log_header::ha_file_status, HA_LOG_APPLIER_STATE_DONE, HA_LOG_APPLIER_STATE_NA, HA_LOG_APPLIER_STATE_RECOVERING, HA_LOG_APPLIER_STATE_WORKING, log_header::ha_server_state, HA_SERVER_STATE_ACTIVE, HA_SERVER_STATE_DEAD, HA_SERVER_STATE_MAINTENANCE, HA_SERVER_STATE_STANDBY, HA_SERVER_STATE_TO_BE_ACTIVE, HA_SERVER_STATE_TO_BE_STANDBY, la_info::is_end_of_record, la_clear_all_repl_and_commit_list(), la_log_commit(), la_peer_host, la_slave_db_name, la_info::last_file_state, la_info::last_is_end_of_record, la_info::last_server_state, LOG_HA_FILESTAT_SYNCHRONIZED, la_act_log::log_hdr, NO_ERROR, log_lsa::offset, and log_lsa::pageid.
Referenced by la_apply_log_file().
static int la_check_duplicated (const char * logpath, const char * dbname, int * lockf_vdes, int * last_deleted_arv_num) static
Definition at line 6664 of file log_applier.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_FAILED, ER_IO_MOUNT_FAIL, er_log_debug, er_set_with_oserror(), fileio_close(), fileio_lock_la_log_path(), FILEIO_NOT_LOCKF, fileio_open(), FILEIO_PATH_SEPARATOR, LA_LOCK_SUFFIX, NO_ERROR, and NULL_VOLDES.
Referenced by la_apply_log_file().
static int la_check_mem_size (void) static
Definition at line 6508 of file log_applier.c.
References ARG_FILE_LINE, la_info::committed_lsa, ER_ERROR_SEVERITY, ER_HA_LA_EXCEED_MAX_MEM_SIZE, er_set(), error(), HB_START_WAITING_TIME_IN_SECS, la_get_mem_size(), la_info::max_mem_size, NO_ERROR, NULL, log_lsa::offset, ONE_K, log_lsa::pageid, la_info::required_lsa, la_info::start_time, and la_info::start_vsize.
Referenced by la_apply_log_file().
static int la_check_time_commit (struct timeval * time, unsigned int threshold) static
Definition at line 6606 of file log_applier.c.
References assert, db_ping_server(), ER_NET_CANT_CONNECT_SERVER, error(), la_info::is_apply_info_updated, la_log_commit(), LA_STATUS_BUSY, LA_STATUS_IDLE, NO_ERROR, NULL, la_info::prev_total_rows, la_info::status, and la_info::total_rows.
Referenced by la_apply_log_file().
static void la_clear_all_repl_and_commit_list (void) static
Definition at line 3396 of file log_applier.c.
References la_info::cur_repl, i, la_free_repl_items_by_tranid(), la_info::repl_lists, and la_apply::tranid.
Referenced by la_change_state().
static void la_clear_applied_info (LA_APPLY * apply) static
Definition at line 3382 of file log_applier.c.
References assert, la_free_all_repl_items(), la_apply::last_lsa, LSA_SET_NULL(), la_apply::start_lsa, and la_apply::tranid.
Referenced by la_apply_repl_log(), and la_free_repl_items_by_tranid().
static void la_clear_recdes_pool (void) static
Definition at line 2306 of file log_applier.c.
References la_recdes_pool::area, recdes::area_size, recdes::data, la_recdes_pool::db_page_size, free_and_init, i, la_recdes_pool::is_initialized, la_recdes_pool::next_idx, NULL, la_recdes_pool::num_recdes, and la_recdes_pool::recdes_arr.
Referenced by la_init_recdes_pool(), and la_shutdown().
int la_commit_transaction (void) static
Definition at line 6545 of file log_applier.c.
References db_commit_transaction(), la_info::delete_counter, error(), la_info::fail_counter, HB_START_WAITING_TIME_IN_SECS, la_info::insert_counter, LA_WS_CULL_MOPS_INTERVAL, LA_WS_CULL_MOPS_INTERVAL_MIN, LA_WS_CULL_MOPS_PER_APPLY, LA_WS_CULL_MOPS_PER_APPLY_MIN, NO_ERROR, NULL, start_time, la_info::start_time, la_info::update_counter, ws_cull_mops(), and ws_filter_dirty().
Referenced by la_log_commit().
static int la_create_repl_filter (void) static
Definition at line 7624 of file log_applier.c.
References ARG_FILE_LINE, envvar_confdir_file(), ER_ERROR_SEVERITY, ER_HA_LA_REPL_FILTER_GENERIC, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), er_set_with_oserror(), er_stack_pop(), er_stack_push(), error(), la_add_repl_filter(), la_destroy_repl_filter(), LA_NUM_REPL_FILTER, la_repl_filter::list, la_repl_filter::list_size, locator_find_class(), NO_ERROR, NULL, PATH_SEPARATOR, prm_get_integer_value(), prm_get_string_value(), PRM_ID_HA_REPL_FILTER_FILE, PRM_ID_HA_REPL_FILTER_TYPE, la_info::repl_filter, REPL_FILTER_NONE, sm_downcase_name(), SM_MAX_IDENTIFIER_LENGTH, snprintf_dots_truncate, strlen, trim(), la_repl_filter::type, ws_cull_mops(), ws_decache(), and ws_release_user_instance().
Referenced by la_apply_log_file().
static void la_decache_page_buffers (LOG_PAGEID from, LOG_PAGEID to) static
Definition at line 1428 of file log_applier.c.
References la_info::cache_pb, la_cache_buffer::fix_count, la_cache_pb::hash_table, i, la_cache_pb::log_buffer, mht_rem(), NULL, NULL_PAGEID, la_cache_pb::num_buffers, la_cache_buffer::pageid, and la_cache_buffer::recently_free.
Referenced by la_apply_log_file().
static int la_delay_replica (time_t eot_time) static
Definition at line 8432 of file log_applier.c.
References ARG_FILE_LINE, assert, tde_cipher::data_keys, ER_ERROR_SEVERITY, ER_HA_GENERIC_ERROR, er_set(), er_set_with_oserror(), ER_TDE_CIPHER_IS_NOT_LOADED, error(), HA_MODE_OFF, HA_MODE_REPLICA, tde_cipher::is_loaded, la_log_commit(), LA_SLEEP, la_info::log_path, NO_ERROR, NULL, pid, prm_get_integer_value(), prm_get_name(), prm_get_string_value(), PRM_ID_HA_MODE, PRM_ID_HA_REPLICA_DELAY_IN_SECS, PRM_ID_HA_REPLICA_TIME_BOUND, tde_Cipher, THREAD_CALLING_CONVENTION, THREAD_RET_T, and util_str_to_time_since_epoch().
Referenced by la_log_record_process().
static int la_delete_ha_apply_info (void) static
Definition at line 2209 of file log_applier.c.
References la_info::act_log, assert, CT_HA_APPLY_INFO_NAME, db_commit_transaction(), db_make_varchar(), db_value_clear(), i, la_info::is_apply_info_updated, LA_IN_VALUE_COUNT, LA_QUERY_BUF_SIZE, la_update_query_execute_with_values(), LANG_SYS_CODESET, LANG_SYS_COLLATION, la_act_log::log_hdr, la_info::log_path, log_header::prefix_name, and strlen.
Referenced by la_apply_log_file().
static void la_destroy_repl_filter (void) static
Definition at line 7745 of file log_applier.c.
References free_and_init, i, la_repl_filter::list, la_repl_filter::list_size, NULL, la_repl_filter::num_filters, and la_info::repl_filter.
Referenced by la_create_repl_filter(), and la_shutdown().
static int la_disk_to_obj (MOBJ classobj, RECDES * record, DB_OTMPL * def, DB_VALUE * key) static
Definition at line 3703 of file log_applier.c.
References ARG_FILE_LINE, recdes::data, or_buf::env, ER_ERROR_SEVERITY, ER_GENERIC_ERROR, er_set_with_oserror(), error(), or_buf::error_abort, la_get_current(), recdes::length, NO_ERROR, or_advance(), OR_BOUND_BIT_FLAG, OR_GET_OFFSET_SIZE, or_init(), OR_INT_SIZE, OR_MVCC_FLAG_MASK, OR_MVCC_FLAG_SHIFT_BITS, OR_MVCC_FLAG_VALID_DELID, OR_MVCC_FLAG_VALID_INSID, OR_MVCC_FLAG_VALID_PREV_VERSION, or_mvcc_get_repid_and_flags(), OR_MVCCID_SIZE, or_buf::ptr, and rc.
Referenced by la_apply_insert_log(), and la_apply_update_log().
static int la_does_page_exist (LOG_PAGEID pageid) static
Definition at line 2742 of file log_applier.c.
References log_page::hdr, la_cache_buffer::in_archive, la_get_page_buffer(), la_invalidate_page_buffer(), LA_PAGE_DOESNOT_EXIST, LA_PAGE_EXST_IN_ACTIVE_LOG, LA_PAGE_EXST_IN_ARCHIVE_LOG, la_release_page_buffer(), log_hdrpage::logical_pageid, la_cache_buffer::logpage, NULL, NULL_OFFSET, log_hdrpage::offset, and la_cache_buffer::pageid.
Referenced by la_apply_log_file(), and la_log_record_process().
static int la_expand_cache_log_buffer (LA_CACHE_PB * cache_pb, int slb_cnt, int slb_size) static
Definition at line 1168 of file log_applier.c.
References ARG_FILE_LINE, assert, la_cache_buffer_area::buffer_area, la_cache_pb::buffer_area, DB_SIZEOF, ER_ERROR_SEVERITY, er_log_debug, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, i, la_cache_pb::log_buffer, la_cache_buffer_area::next, NO_ERROR, NULL, and la_cache_pb::num_buffers.
Referenced by la_cache_buffer_replace(), and la_init_cache_log_buffer().
static int la_fetch_log_hdr (LA_ACT_LOG * act_log) static
Definition at line 2555 of file log_applier.c.
References log_page::area, ARG_FILE_LINE, la_act_log::db_logpagesize, ER_FATAL_ERROR_SEVERITY, ER_LOG_READ, er_set(), error(), la_act_log::hdr_page, la_log_io_read(), la_act_log::log_hdr, la_act_log::log_vdes, NO_ERROR, and la_act_log::path.
Referenced by check_reinit_copylog(), and la_log_fetch().
static LA_APPLY * la_find_apply_list (int tranid) static
Definition at line 2864 of file log_applier.c.
References la_info::cur_repl, i, NULL, la_info::repl_lists, and la_apply::tranid.
Referenced by la_add_apply_list(), la_apply_repl_log(), la_free_repl_items_by_tranid(), and la_set_repl_log().
static int la_find_archive_num (int * arv_log_num, LOG_PAGEID pageid) static
Definition at line 823 of file log_applier.c.
References la_info::act_log, ARG_FILE_LINE, la_info::arv_log, log_arv_header::arv_num, CEIL_PTVDIV, ER_ERROR_SEVERITY, ER_LOG_MOUNT_FAIL, ER_LOG_NOTIN_ARCHIVE, er_set(), ER_WARNING_SEVERITY, error(), fileio_make_log_archive_name(), log_arv_header::fpageid, la_get_range_of_archive(), la_info::last_deleted_archive_num, la_act_log::log_hdr, la_arv_log::log_hdr, la_info::log_path, la_arv_log::log_vdes, NO_ERROR, log_header::npages, log_arv_header::npages, NULL, NULL_VOLDES, log_header::nxarv_num, and log_header::prefix_name.
Referenced by la_log_fetch_from_archive(), and la_remove_archive_logs().
static int la_find_last_deleted_arv_num (void) static
Definition at line 7379 of file log_applier.c.
References la_info::act_log, fileio_close(), fileio_make_log_archive_name(), fileio_open(), la_act_log::log_hdr, la_info::log_path, NULL_VOLDES, log_header::nxarv_num, and log_header::prefix_name.
Referenced by la_apply_log_file(), and la_log_page_check().
static int la_find_log_pagesize (LA_ACT_LOG * act_log, const char * logpath, const char * dbname, bool check_charset) static
Definition at line 2572 of file log_applier.c.
References log_page::area, ARG_FILE_LINE, CUBRID_MAGIC_LOG_ACTIVE, CUBRID_MAGIC_MAX_LENGTH, log_header::db_charset, log_header::db_iopagesize, la_act_log::db_iopagesize, log_header::db_logpagesize, la_act_log::db_logpagesize, ER_ERROR_SEVERITY, ER_FATAL_ERROR_SEVERITY, ER_LOC_INIT, er_log_debug, ER_LOG_MOUNT_FAIL, ER_LOG_PAGE_CORRUPTED, ER_LOG_READ, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), er_set_with_oserror(), ERR_MSG_SIZE, error(), fileio_make_log_active_name(), fileio_open(), la_act_log::hdr_page, if(), IO_MAX_PAGE_SIZE, IO_MIN_PAGE_SIZE, la_applier_need_shutdown, LA_DEFAULT_LOG_PAGE_SIZE, la_log_io_read(), LA_SLEEP, lang_charset(), lang_charset_cubrid_name(), la_act_log::log_hdr, la_act_log::log_vdes, log_header::magic, log_header::mark_will_del, NO_ERROR, NULL, NULL_VOLDES, la_act_log::path, log_header::prefix_name, snprintf_dots_truncate, and strlen.
Referenced by la_apply_log_file(), and la_log_page_check().
static int la_find_required_lsa (LOG_LSA * required_lsa) static
Definition at line 1462 of file log_applier.c.
References la_info::cur_repl, error(), la_info::final_lsa, i, LSA_COPY(), LSA_GT(), LSA_ISNULL(), LSA_SET_NULL(), NO_ERROR, la_info::repl_lists, la_apply::start_lsa, and la_apply::tranid.
Referenced by la_log_commit().
static int la_flush_repl_items (bool immediate) static
Definition at line 4685 of file log_applier.c.
References ARG_FILE_LINE, assert, ws_repl_flush_err::class_oid, string_buffer::clear(), db_sprint_value(), la_info::delete_counter, ER_ERROR_SEVERITY, ER_FAILED, ER_HA_GENERIC_ERROR, ER_HA_LA_FAILED_TO_APPLY_DELETE, ER_HA_LA_FAILED_TO_APPLY_INSERT, ER_HA_LA_FAILED_TO_APPLY_UPDATE, ER_LC_FAILED_TO_FLUSH_REPL_ITEMS, ER_LC_PARTIALLY_FAILED_TO_FLUSH, er_set(), er_stack_pop(), er_stack_push(), error(), ws_repl_flush_err::error_code, ws_repl_flush_err::error_msg, la_info::fail_counter, string_buffer::get_buffer(), la_info::insert_counter, LA_MAX_UNFLUSHED_REPL_ITEMS, la_restart_on_bulk_flush_error(), LC_FLUSH_DELETE, LC_IS_FLUSH_INSERT, LC_IS_FLUSH_UPDATE, locator_repl_flush_all(), NO_ERROR, NULL, la_info::num_unflushed, db_object::object, ws_repl_flush_err::operation, ws_repl_flush_err::pkey_value, sm_ch_name(), sm_Root_class_mop, la_info::update_counter, ws_clear_all_repl_errors_of_error_link(), ws_clear_all_repl_objs(), ws_free_repl_flush_error(), ws_get_repl_error_from_error_link(), and ws_mop().
Referenced by la_apply_delete_log(), la_apply_insert_log(), la_apply_statement_log(), la_apply_update_log(), and la_log_commit().
bool la_force_shutdown (void)
Definition at line 591 of file log_applier.c.
References la_applier_need_shutdown, and la_applier_shutdown_by_signal.
Referenced by applylogdb().
static void la_free_all_repl_items (LA_APPLY * apply) static
Definition at line 3362 of file log_applier.c.
References assert, la_apply::head, la_apply::is_long_trans, la_free_all_repl_items_except_head(), la_free_repl_item(), NULL, la_apply::num_items, and la_apply::tail.
Referenced by la_apply_repl_log(), and la_clear_applied_info().
static void la_free_all_repl_items_except_head (LA_APPLY * apply) static
Definition at line 3304 of file log_applier.c.
References assert, la_apply::head, la_free_repl_item(), la_item::next, and NULL.
Referenced by la_free_all_repl_items(), and la_set_repl_log().
static void la_free_and_add_next_repl_item (LA_APPLY * apply, LA_ITEM * next_item, LOG_LSA * lsa) static
Definition at line 3331 of file log_applier.c.
References assert, la_apply::head, la_apply::is_long_trans, la_add_repl_item(), la_free_repl_item(), la_item::lsa, LSA_ISNULL(), LSA_LT(), la_item::next, and NULL.
Referenced by la_apply_repl_log().
static void la_free_repl_item (LA_APPLY * apply, LA_ITEM * item) static
Definition at line 3270 of file log_applier.c.
References assert, la_item::class_name, db_private_free_and_init, la_item::db_user, free_and_init, la_item::ha_sys_prm, la_item::key, la_unlink_repl_item(), NULL, la_item::packed_key_value, and pr_clear_value().
Referenced by la_apply_repl_log(), la_free_all_repl_items(), la_free_all_repl_items_except_head(), and la_free_and_add_next_repl_item().
static void la_free_repl_items_by_tranid (int tranid) static
Definition at line 5871 of file log_applier.c.
References la_info::commit_head, la_info::commit_tail, free_and_init, la_clear_applied_info(), la_find_apply_list(), la_commit::next, NULL, la_commit::prev, and la_commit::tranid.
Referenced by la_clear_all_repl_and_commit_list(), and la_log_record_process().
static void la_get_adaptive_time_commit_interval (int * time_commit_interval, int * delay_hist) static
Definition at line 7428 of file log_applier.c.
References la_get_avg(), LA_MAX_TOLERABLE_DELAY, LA_NUM_DELAY_HISTORY, LA_REINIT_COMMIT_INTERVAL, la_info::log_record_time, NULL, prm_get_integer_value(), and PRM_ID_HA_APPLYLOGDB_MAX_COMMIT_INTERVAL_IN_MSECS.
Referenced by la_apply_log_file().
static float la_get_avg (int * array, int size) static
Definition at line 7406 of file log_applier.c.
References assert, and i.
Referenced by la_get_adaptive_time_commit_interval().
static int la_get_current (OR_BUF * buf, SM_CLASS * sm_class, int bound_bit_flag, DB_OTMPL * def, DB_VALUE * key, int offset_size) static
Definition at line 3559 of file log_applier.c.
References ARG_FILE_LINE, sm_class::attributes, db_make_null(), DB_SIZEOF, dbt_put_internal(), db_value::domain, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), sm_class::fixed_count, sm_class::fixed_size, free_and_init, sm_attribute::header, i, INT_ALIGNMENT, sm_component::next, NO_ERROR, NULL, or_advance(), OR_BOUND_BIT_BYTES, OR_GET_BOUND_BIT, or_get_offset_internal(), pr_clear_value(), or_buf::ptr, PTR_ALIGN, rc, tp_domain_disk_size(), and sm_class::variable_count.
Referenced by la_disk_to_obj().
static int la_get_ha_apply_info (const char * log_path, const char * prefix_name, LA_HA_APPLY_INFO * ha_apply_info) static
Definition at line 1505 of file log_applier.c.
References la_ha_apply_info::append_lsa, assert, assert_release, la_ha_apply_info::commit_counter, la_ha_apply_info::committed_lsa, la_ha_apply_info::committed_rep_lsa, la_ha_apply_info::copied_log_path, la_ha_apply_info::creation_time, CT_HA_APPLY_INFO_NAME, db_datetime::date, DB_CURSOR_END, DB_CURSOR_ERROR, DB_CURSOR_SUCCESS, db_execute_with_values(), db_find_class(), db_get_bigint(), db_get_datetime(), db_get_int(), DB_IS_NULL, db_make_varchar(), la_ha_apply_info::db_name, db_query_column_count(), db_query_end(), db_query_first_tuple(), db_query_get_tuple_valuelist(), db_value_clear(), la_ha_apply_info::delete_counter, la_ha_apply_info::eof_lsa, er_errid(), ER_FAILED, error(), la_ha_apply_info::fail_counter, la_ha_apply_info::final_lsa, i, la_ha_apply_info::insert_counter, LA_IN_VALUE_COUNT, LA_OUT_VALUE_COUNT, LA_QUERY_BUF_SIZE, LA_STATUS_IDLE, LANG_SYS_CODESET, LANG_SYS_COLLATION, la_ha_apply_info::last_access_time, la_ha_apply_info::log_commit_time, la_ha_apply_info::log_record_time, LSA_SET_NULL(), NO_ERROR, NULL, log_lsa::offset, log_lsa::pageid, la_ha_apply_info::required_lsa, la_ha_apply_info::schema_counter, la_ha_apply_info::start_time, la_ha_apply_info::status, strlen, db_datetime::time, and la_ha_apply_info::update_counter.
Referenced by la_get_last_ha_applied_info(), and la_log_page_check().
static LOG_REC_HA_SERVER_STATE* la_get_ha_server_state (LOG_PAGE * pgptr, LOG_LSA * lsa) static
Definition at line 4654 of file log_applier.c.
References log_page::area, DB_SIZEOF, error(), LA_LOG_READ_ADVANCE_WHEN_DOESNT_FIT, NO_ERROR, NULL, log_lsa::offset, log_lsa::pageid, and la_cache_buffer::pageid.
Referenced by la_log_record_process().
static char * la_get_hostname_from_log_path (char * log_path) static
Definition at line 6252 of file log_applier.c.
References la_slave_db_name, NULL, p, and strlen.
Referenced by la_apply_log_file().
static DB_VALUE * la_get_item_pk_value (LA_ITEM * item) static
Definition at line 3077 of file log_applier.c.
References assert, DB_IS_NULL, DB_TYPE_NULL, DB_VALUE_TYPE, la_item::key, LOG_REPLICATION_DATA, la_item::log_type, NULL, or_unpack_mem_value(), la_item::packed_key_value, and la_item::packed_key_value_length.
Referenced by la_apply_delete_log(), la_apply_insert_log(), la_apply_repl_log(), and la_apply_update_log().
static int la_get_last_ha_applied_info (void) static
Definition at line 1956 of file log_applier.c.
References la_info::act_log, la_info::append_lsa, la_ha_apply_info::append_lsa, ARG_FILE_LINE, la_info::commit_counter, la_ha_apply_info::commit_counter, la_info::committed_lsa, la_ha_apply_info::committed_lsa, la_info::committed_rep_lsa, la_ha_apply_info::committed_rep_lsa, la_ha_apply_info::creation_time, CT_HA_APPLY_INFO_NAME, db_datetime::date, db_commit_transaction(), log_header::db_creation, db_localdatetime(), la_info::delete_counter, la_ha_apply_info::delete_counter, log_header::eof_lsa, la_info::eof_lsa, la_ha_apply_info::eof_lsa, ER_ERROR_SEVERITY, ER_FAILED, ER_HA_GENERIC_ERROR, er_set(), la_info::fail_counter, la_ha_apply_info::fail_counter, la_info::final_lsa, la_ha_apply_info::final_lsa, la_info::insert_counter, la_ha_apply_info::insert_counter, la_get_ha_apply_info(), la_insert_ha_apply_info(), la_update_ha_apply_info_start_time(), la_info::last_committed_lsa, la_info::last_committed_rep_lsa, la_act_log::log_hdr, la_info::log_path, LSA_COPY(), LSA_ISNULL(), NO_ERROR, log_header::prefix_name, la_info::required_lsa, la_ha_apply_info::required_lsa, la_info::schema_counter, la_ha_apply_info::schema_counter, db_datetime::time, la_info::update_counter, and la_ha_apply_info::update_counter.
Referenced by la_apply_log_file().
static int la_get_log_data (LOG_RECORD_HEADER * lrec, LOG_LSA * lsa, LOG_PAGE * pgptr, unsigned int match_rcvindex, unsigned int * rcvindex, void ** logs, char ** rec_type, char ** data, int * d_length) static
Definition at line 3926 of file log_applier.c.
References log_page::area, ARG_FILE_LINE, assert, log_rec_undoredo::data, log_rec_undo::data, log_rec_redo::data, DB_SIZEOF, er_errid(), ER_ERROR_SEVERITY, ER_IO_LZ4_DECOMPRESS_FAIL, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, GET_ZIP_LEN, la_get_undoredo_diff(), la_get_zipped_data(), la_log_copy_fromlog(), LA_LOG_READ_ADD_ALIGN, LA_LOG_READ_ADVANCE_WHEN_DOESNT_FIT, LA_LOG_READ_ALIGN, log_rec_undo::length, log_rec_redo::length, LOG_DIFF_UNDOREDO_DATA, LOG_IS_DIFF_UNDOREDO_TYPE, LOG_IS_MVCC_OP_RECORD_TYPE, LOG_MVCC_DIFF_UNDOREDO_DATA, LOG_MVCC_REDO_DATA, LOG_MVCC_UNDO_DATA, LOG_MVCC_UNDOREDO_DATA, LOG_REDO_DATA, LOG_UNDO_DATA, LOG_UNDOREDO_DATA, log_unzip(), NO_ERROR, NULL, log_lsa::offset, log_lsa::pageid, la_cache_buffer::pageid, log_data::rcvindex, log_rec_mvcc_redo::redo, la_info::redo_unzip_ptr, log_rec_undoredo::rlength, log_rec_header::type, log_rec_undoredo::ulength, log_rec_mvcc_undo::undo, log_rec_mvcc_undoredo::undoredo, and ZIP_CHECK.
Referenced by la_get_overflow_recdes(), la_get_recdes(), and la_get_relocation_recdes().
static unsigned long la_get_mem_size (void) static
Definition at line 6479 of file log_applier.c.
References NULL, ONE_K, and pid.
Referenced by la_check_mem_size(), and la_init().
static LA_ITEM * la_get_next_repl_item (LA_ITEM * item, bool is_long_trans, LOG_LSA * last_lsa) static
Definition at line 5922 of file log_applier.c.
References la_get_next_repl_item_from_list(), and la_get_next_repl_item_from_log().
Referenced by la_apply_repl_log().
static LA_ITEM * la_get_next_repl_item_from_list (LA_ITEM * item) static
Definition at line 5935 of file log_applier.c.
References la_item::next.
Referenced by la_get_next_repl_item().
static LA_ITEM * la_get_next_repl_item_from_log (LA_ITEM * item, LOG_LSA * last_lsa) static
Definition at line 5941 of file log_applier.c.
References la_info::act_log, assert, log_header::eof_lsa, log_rec_header::forw_lsa, free_and_init, la_get_page(), la_make_repl_item(), la_release_page_buffer(), LOG_ABORT, LOG_COMMIT, LOG_GET_LOG_RECORD_HEADER, la_act_log::log_hdr, LOG_REPLICATION_DATA, LOG_REPLICATION_STATEMENT, la_item::lsa, LSA_COPY(), LSA_EQ(), LSA_GE(), LSA_GT(), LSA_ISNULL(), NULL, log_lsa::pageid, log_rec_header::trid, and log_rec_header::type.
Referenced by la_get_next_repl_item().
static int la_get_next_update_log (LOG_RECORD_HEADER * prev_lrec, LOG_PAGE * pgptr, void ** logs, char ** rec_type, char ** data, int * d_length) static
Definition at line 4373 of file log_applier.c.
References log_page::area, ARG_FILE_LINE, assert, log_rec_undoredo::data, DB_SIZEOF, er_errid(), ER_ERROR_SEVERITY, ER_GENERIC_ERROR, ER_IO_LZ4_DECOMPRESS_FAIL, er_set(), error(), log_rec_header::forw_lsa, free_and_init, GET_ZIP_LEN, log_page::hdr, la_get_page(), la_get_undoredo_diff(), la_get_zipped_data(), la_log_copy_fromlog(), LA_LOG_READ_ADD_ALIGN, LA_LOG_READ_ADVANCE_WHEN_DOESNT_FIT, LA_LOG_READ_ALIGN, LOG_ABORT, LOG_COMMIT, LOG_GET_LOG_RECORD_HEADER, LOG_IS_DIFF_UNDOREDO_TYPE, LOG_IS_MVCC_OP_RECORD_TYPE, LOG_IS_UNDOREDO_RECORD_TYPE, log_unzip(), log_hdrpage::logical_pageid, LSA_COPY(), NO_ERROR, NULL, log_lsa::offset, log_data::offset, log_lsa::pageid, log_data::pageid, la_cache_buffer::pageid, log_data::rcvindex, la_info::redo_unzip_ptr, log_rec_undoredo::rlength, RVHF_UPDATE, RVHF_UPDATE_NOTIFY_VACUUM, log_rec_header::trid, log_rec_header::type, log_rec_undoredo::ulength, log_rec_mvcc_undoredo::undoredo, log_data::volid, and ZIP_CHECK.
Referenced by la_get_recdes().
static int la_get_overflow_recdes (LOG_RECORD_HEADER * lrec, void * logs, RECDES * recdes, unsigned int rcvindex) static
Definition at line 4226 of file log_applier.c.
References ARG_FILE_LINE, assert, recdes::data, la_ovf_page_list::data, DB_SIZEOF, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, la_get_log_data(), la_get_page(), la_realloc_recdes_data(), la_release_page_buffer(), recdes::length, la_ovf_page_list::length, LOG_DUMMY_OVF_RECORD, LOG_GET_LOG_RECORD_HEADER, LOG_IS_REDO_RECORD_TYPE, LSA_COPY(), LSA_ISNULL(), la_ovf_page_list::next, NO_ERROR, NULL, log_lsa::pageid, vpid::pageid, log_rec_header::prev_tranlsa, log_rec_header::trid, log_rec_header::type, and vpid::volid.
Referenced by la_get_recdes().
static LOG_PAGE * la_get_page (LOG_PAGEID pageid) static
Definition at line 1327 of file log_applier.c.
References assert, la_get_page_buffer(), la_cache_buffer::logpage, NULL, and NULL_PAGEID.
Referenced by la_apply_insert_log(), la_apply_update_log(), la_get_next_repl_item_from_log(), la_get_next_update_log(), la_get_overflow_recdes(), and la_get_relocation_recdes().
static LA_CACHE_BUFFER * la_get_page_buffer (LOG_PAGEID pageid) static
Definition at line 1288 of file log_applier.c.
References la_info::act_log, la_info::cache_buffer_size, la_info::cache_pb, la_act_log::db_logpagesize, la_cache_buffer::fix_count, la_cache_pb::hash_table, log_page::hdr, la_cache_buffer_replace(), log_hdrpage::logical_pageid, la_cache_buffer::logpage, mht_get(), mht_put(), mht_rem(), NULL, and la_cache_buffer::pageid.
Referenced by la_apply_log_file(), la_does_page_exist(), and la_get_page().
static int la_get_range_of_archive (int arv_log_num, LOG_PAGEID * fpageid, DKNPAGES * npages) static
Definition at line 760 of file log_applier.c.
References la_info::act_log, log_page::area, ARG_FILE_LINE, la_act_log::db_logpagesize, ER_ERROR_SEVERITY, er_log_debug, ER_LOG_MOUNT_FAIL, ER_LOG_READ, ER_OUT_OF_VIRTUAL_MEMORY, ER_PB_BAD_PAGEID, er_set(), error(), fileio_close(), fileio_make_log_archive_name(), fileio_open(), log_arv_header::fpageid, la_log_io_read_with_max_retries(), la_act_log::log_hdr, la_info::log_path, NO_ERROR, log_arv_header::npages, NULL, NULL_VOLDES, and log_header::prefix_name.
Referenced by la_find_archive_num().
static int la_get_recdes (LOG_LSA * lsa, LOG_PAGE * pgptr, RECDES * recdes, unsigned int * rcvindex, char * rec_type) static
Definition at line 4583 of file log_applier.c.
References ARG_FILE_LINE, recdes::data, ER_FAILED, er_log_debug, error(), la_get_log_data(), la_get_next_update_log(), la_get_overflow_recdes(), la_get_relocation_recdes(), la_make_room_for_mvcc_insid(), recdes::length, LOG_GET_LOG_RECORD_HEADER, NO_ERROR, NULL, log_lsa::offset, log_lsa::pageid, REC_ASSIGN_ADDRESS, REC_BIGONE, REC_RELOCATION, RVHF_INSERT, RVHF_MVCC_INSERT, RVHF_UPDATE, RVHF_UPDATE_NOTIFY_VACUUM, RVOVF_CHANGE_LINK, RVOVF_NEWPAGE_INSERT, RVOVF_PAGE_UPDATE, and recdes::type.
Referenced by la_apply_insert_log(), and la_apply_update_log().
static int la_get_relocation_recdes (LOG_RECORD_HEADER * lrec, LOG_PAGE * pgptr, unsigned int match_rcvindex, void ** logs, char ** rec_type, RECDES * recdes) static
Definition at line 4532 of file log_applier.c.
References ARG_FILE_LINE, recdes::data, ER_ERROR_SEVERITY, ER_LOG_PAGE_CORRUPTED, er_set(), error(), la_get_log_data(), la_get_page(), la_release_page_buffer(), recdes::length, LOG_GET_LOG_RECORD_HEADER, LSA_COPY(), LSA_ISNULL(), NO_ERROR, log_lsa::pageid, log_rec_header::prev_tranlsa, RVHF_INSERT_NEWHOME, and log_rec_header::trid.
Referenced by la_get_recdes().
int la_get_undoredo_diff (LOG_PAGE ** pgptr, LOG_PAGEID * pageid, PGLENGTH * offset, bool * is_undo_zip, char ** undo_data, int * undo_length) static
Definition at line 3857 of file log_applier.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_IO_LZ4_DECOMPRESS_FAIL, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, GET_ZIP_LEN, la_log_copy_fromlog(), LA_LOG_READ_ADD_ALIGN, log_unzip(), NO_ERROR, NULL, la_cache_buffer::pageid, la_info::undo_unzip_ptr, and ZIP_CHECK.
Referenced by la_get_log_data(), and la_get_next_update_log().
char * la_get_zipped_data (char * undo_data, int undo_length, bool is_diff, bool is_undo_zip, bool is_overflow, char ** rec_type, char ** data, int * length) static
Definition at line 3780 of file log_applier.c.
References ARG_FILE_LINE, log_zip::data_length, DB_SIZEOF, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, log_zip::log_data, log_diff(), NULL, la_info::redo_unzip_ptr, and la_info::undo_unzip_ptr.
Referenced by la_get_log_data(), and la_get_next_update_log().
static bool la_ignore_on_error (int errid) static
Definition at line 2247 of file log_applier.c.
References assert_release, NO_ERROR, PRM_ID_HA_APPLYLOGDB_IGNORE_ERROR_LIST, and sysprm_find_err_in_integer_list().
Referenced by la_apply_repl_log(), and la_restart_on_bulk_flush_error().
static void la_init (const char * log_path, const int max_mem_size) static
Definition at line 6781 of file log_applier.c.
References la_info::act_log, la_info::append_lsa, la_info::arv_log, la_info::cache_buffer_size, la_info::committed_lsa, la_info::committed_rep_lsa, DB_CLIENT_TYPE_LOG_APPLIER, db_get_client_type(), la_act_log::db_iopagesize, la_info::db_lockf_vdes, la_act_log::db_logpagesize, la_info::eof_lsa, la_info::final_lsa, la_info::is_apply_info_updated, la_recdes_pool::is_initialized, la_info::is_role_changed, LA_DEFAULT_CACHE_BUFFER_SIZE, LA_DEFAULT_LOG_PAGE_SIZE, la_get_mem_size(), la_info::last_committed_lsa, la_info::last_committed_rep_lsa, la_info::last_deleted_archive_num, la_info::last_time_archive_deleted, la_repl_filter::list_size, la_info::log_path, la_act_log::log_vdes, la_arv_log::log_vdes, LSA_SET_NULL(), la_info::max_mem_size, NULL, NULL_VOLDES, la_repl_filter::num_filters, la_info::num_unflushed, la_info::reinit_copylog, la_info::repl_filter, REPL_FILTER_NONE, la_info::required_lsa, la_info::start_time, la_info::start_vsize, la_repl_filter::type, and ws_init_repl_objs().
Referenced by la_apply_log_file(), and la_log_page_check().
static int la_init_cache_log_buffer (LA_CACHE_PB * cache_pb, int slb_cnt, int slb_size) static
Definition at line 2532 of file log_applier.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), la_cache_pb::hash_table, la_expand_cache_log_buffer(), log_pageid_hash(), mht_compare_logpageids_are_equal(), mht_create(), NO_ERROR, NULL, and la_cache_pb::num_buffers.
Referenced by la_apply_log_file().
static LA_CACHE_PB * la_init_cache_pb (void) static
Definition at line 2478 of file log_applier.c.
References ARG_FILE_LINE, la_cache_pb::buffer_area, DB_SIZEOF, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), la_cache_pb::hash_table, la_cache_pb::log_buffer, NULL, and la_cache_pb::num_buffers.
Referenced by la_apply_log_file().
static void la_init_ha_apply_info (LA_HA_APPLY_INFO * ha_apply_info) static
Definition at line 597 of file log_applier.c.
References la_ha_apply_info::append_lsa, la_ha_apply_info::committed_lsa, la_ha_apply_info::committed_rep_lsa, la_ha_apply_info::eof_lsa, la_ha_apply_info::final_lsa, LSA_SET_NULL(), and la_ha_apply_info::required_lsa.
Referenced by la_log_page_check().
static int la_init_recdes_pool (int page_size, int num_recdes) static
Definition at line 2420 of file log_applier.c.
References la_recdes_pool::area, recdes::area_size, ARG_FILE_LINE, assert, recdes::data, la_recdes_pool::db_page_size, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), i, IO_MAX_PAGE_SIZE, IO_MIN_PAGE_SIZE, la_recdes_pool::is_initialized, la_clear_recdes_pool(), recdes::length, la_recdes_pool::next_idx, NO_ERROR, NULL, la_recdes_pool::num_recdes, p, page_size, and la_recdes_pool::recdes_arr.
Referenced by la_apply_log_file().
static int la_init_repl_lists (bool need_realloc) static
Definition at line 2777 of file log_applier.c.
References ARG_FILE_LINE, la_info::cur_repl, DB_SIZEOF, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, la_apply::head, i, la_apply::is_long_trans, LA_REPL_LIST_COUNT, la_apply::last_lsa, LSA_SET_NULL(), NO_ERROR, NULL, la_apply::num_items, la_info::repl_cnt, la_info::repl_lists, la_apply::start_lsa, la_apply::tail, and la_apply::tranid.
Referenced by la_add_apply_list().
static int la_insert_ha_apply_info (DB_DATETIME * creation_time) static
Definition at line 1707 of file log_applier.c.
References la_info::act_log, la_info::append_lsa, ARG_FILE_LINE, assert_release, la_info::committed_lsa, la_info::committed_rep_lsa, CT_HA_APPLY_INFO_NAME, CUBRID_MAGIC_LOG_INFO, db_make_bigint(), db_make_datetime(), db_make_int(), db_make_varchar(), db_value_clear(), la_info::eof_lsa, ER_LOG_MOUNT_FAIL, er_set(), ER_WARNING_SEVERITY, la_info::final_lsa, i, LA_IN_VALUE_COUNT, LA_QUERY_BUF_SIZE, la_update_query_execute_with_values(), LANG_SYS_CODESET, LANG_SYS_COLLATION, la_act_log::log_hdr, la_info::log_path, la_info::loginf_path, MSGCAT_CATALOG_CUBRID, MSGCAT_LOG_LOGINFO_COMMENT, msgcat_message(), MSGCAT_SET_LOG, NULL, log_lsa::offset, log_lsa::pageid, log_header::prefix_name, la_info::required_lsa, and strlen.
Referenced by la_get_last_ha_applied_info(), la_update_ha_apply_info_log_record_time(), and la_update_ha_last_applied_info().
static void la_invalidate_page_buffer (LA_CACHE_BUFFER * cache_buffer) static
Definition at line 1409 of file log_applier.c.
References la_info::cache_pb, la_cache_buffer::fix_count, la_cache_pb::hash_table, mht_rem(), NULL, la_cache_buffer::pageid, and la_cache_buffer::recently_free.
Referenced by la_apply_log_file(), and la_does_page_exist().
static bool la_is_repl_lists_empty () static
Definition at line 2841 of file log_applier.c.
References la_info::cur_repl, i, la_apply::num_items, and la_info::repl_lists.
Referenced by la_log_record_process().
static int la_lock_dbname (int * lockf_vdes, char * db_name, char * log_path) static
Definition at line 6724 of file log_applier.c.
References assert_release, error(), fileio_lock_la_dbname(), FILEIO_LOCKF, la_info::is_role_changed, LA_SLEEP, NO_ERROR, and NULL_VOLDES.
Referenced by la_apply_repl_log().
static int la_log_commit (bool update_commit_time) static
Definition at line 6429 of file log_applier.c.
References la_info::act_log, log_header::append_lsa, la_info::append_lsa, ARG_FILE_LINE, la_info::committed_lsa, log_header::eof_lsa, la_info::eof_lsa, ER_ERROR_SEVERITY, ER_HA_GENERIC_ERROR, er_log_debug, ER_NET_CANT_CONNECT_SERVER, ER_OBJ_NO_CONNECT, er_set(), error(), la_info::fail_counter, la_commit_transaction(), la_find_required_lsa(), la_flush_repl_items(), la_update_ha_last_applied_info(), la_info::log_commit_time, la_act_log::log_hdr, LSA_COPY(), NO_ERROR, log_lsa::offset, log_lsa::pageid, and la_info::required_lsa.
Referenced by la_apply_log_file(), la_change_state(), la_check_time_commit(), la_delay_replica(), and la_log_record_process().
static void la_log_copy_fromlog (char * rec_type, char * area, int length, LOG_PAGEID log_pageid, PGLENGTH log_offset, LOG_PAGE * log_pgptr) static
Definition at line 2964 of file log_applier.c.
References DB_SIZEOF, error(), LA_LOG_READ_ADVANCE_WHEN_DOESNT_FIT, LA_LOGAREA_SIZE, NO_ERROR, and NULL.
Referenced by la_get_log_data(), la_get_next_update_log(), la_get_undoredo_diff(), and la_make_repl_item().
static int la_log_fetch (LOG_PAGEID pageid, LA_CACHE_BUFFER * cache_buffer) static
Definition at line 1054 of file log_applier.c.
References la_info::act_log, log_header::append_lsa, ARG_FILE_LINE, assert, la_act_log::db_logpagesize, er_log_debug, ER_LOG_NOTIN_ARCHIVE, ER_LOG_READ, er_set(), ER_WARNING_SEVERITY, error(), log_page::hdr, la_cache_buffer::in_archive, la_applier_need_shutdown, la_fetch_log_hdr(), la_log_fetch_from_archive(), la_log_io_read(), LA_LOG_IS_IN_ARCHIVE, la_log_phypageid(), la_act_log::log_hdr, LOG_IS_PAGE_TDE_ENCRYPTED, la_act_log::log_vdes, log_hdrpage::logical_pageid, la_cache_buffer::logpage, NO_ERROR, NULL_PAGEID, log_lsa::pageid, la_cache_buffer::pageid, la_act_log::path, la_cache_buffer::phy_pageid, and tde_decrypt_log_page().
Referenced by la_cache_buffer_replace().
static int la_log_fetch_from_archive (LOG_PAGEID pageid, char * data) static
Definition at line 903 of file log_applier.c.
References la_info::act_log, log_page::area, ARG_FILE_LINE, la_info::arv_log, la_arv_log::arv_num, log_arv_header::arv_num, ASSERT_ERROR, check_reinit_copylog(), CUBRID_MAGIC_LOG_ARCHIVE, CUBRID_MAGIC_MAX_LENGTH, la_act_log::db_logpagesize, ER_ERROR_SEVERITY, er_log_debug, ER_LOG_MOUNT_FAIL, ER_LOG_READ, ER_OUT_OF_VIRTUAL_MEMORY, ER_PB_BAD_PAGEID, er_set(), er_set_with_oserror(), ER_WARNING_SEVERITY, error(), fileio_close(), fileio_make_log_archive_name(), fileio_open(), log_arv_header::fpageid, la_arv_log::hdr_page, la_applier_need_shutdown, la_find_archive_num(), la_log_io_read_with_max_retries(), la_act_log::log_hdr, la_arv_log::log_hdr, LOG_IS_PAGE_TDE_ENCRYPTED, la_info::log_path, la_arv_log::log_vdes, log_arv_header::magic, NO_ERROR, log_arv_header::npages, NULL, NULL_VOLDES, la_arv_log::path, log_header::prefix_name, and tde_decrypt_log_page().
Referenced by la_log_fetch(), and la_log_page_check().
static int la_log_io_open (const char * vlabel, int flags, int mode) static
static int la_log_io_read (char * vname, int vdes, void * io_pgptr, LOG_PHY_PAGEID pageid, int pagesize) static
Definition at line 668 of file log_applier.c.
References la_log_io_read_with_max_retries().
Referenced by la_fetch_log_hdr(), la_find_log_pagesize(), la_log_fetch(), and la_log_page_check().
static int la_log_io_read_with_max_retries (char * vname, int vdes, void * io_pgptr, LOG_PHY_PAGEID pageid, int pagesize, int retries) static
Definition at line 687 of file log_applier.c.
References ARG_FILE_LINE, er_errid(), ER_ERROR_SEVERITY, ER_FAILED, ER_IO_READ, ER_PB_BAD_PAGEID, er_set(), er_set_with_oserror(), ER_WARNING_SEVERITY, and NO_ERROR.
Referenced by la_get_range_of_archive(), la_log_fetch_from_archive(), and la_log_io_read().
int la_log_page_check (const char * database_name, const char * log_path, INT64 page_num, bool check_applied_info, bool check_copied_info, bool check_replica_info, bool verbose, LOG_LSA * copied_eof_lsa, LOG_LSA * copied_append_lsa, LOG_LSA * applied_final_lsa)
Definition at line 7046 of file log_applier.c.
References la_info::act_log, log_header::append_lsa, la_ha_apply_info::append_lsa, ARG_FILE_LINE, la_info::arv_log, assert, log_rec_header::back_lsa, la_ha_apply_info::commit_counter, la_ha_apply_info::committed_lsa, la_ha_apply_info::committed_rep_lsa, la_ha_apply_info::creation_time, db_datetime::date, db_datetime_to_string(), db_datetime_to_string2(), db_error_string(), la_act_log::db_iopagesize, la_act_log::db_logpagesize, la_ha_apply_info::delete_counter, log_header::eof_lsa, la_ha_apply_info::eof_lsa, ER_ERROR_SEVERITY, ER_HA_GENERIC_ERROR, ER_LOG_MOUNT_FAIL, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), er_set_with_oserror(), error(), la_ha_apply_info::fail_counter, fileio_is_volume_exist(), fileio_make_log_active_name(), la_ha_apply_info::final_lsa, log_rec_header::forw_lsa, free_and_init, log_page::hdr, if(), la_ha_apply_info::insert_counter, la_find_last_deleted_arv_num(), la_find_log_pagesize(), la_get_ha_apply_info(), la_init(), la_init_ha_apply_info(), la_log_fetch_from_archive(), la_log_io_read(), LA_LOG_IS_IN_ARCHIVE, la_log_phypageid(), la_print_log_arv_header(), la_print_log_header(), la_ha_apply_info::last_access_time, la_info::last_deleted_archive_num, la_ha_apply_info::log_commit_time, la_info::log_data, LOG_GET_LOG_RECORD_HEADER, la_act_log::log_hdr, la_arv_log::log_hdr, LOG_IS_PAGE_TDE_ENCRYPTED, la_info::log_path, la_ha_apply_info::log_record_time, la_act_log::log_vdes, log_hdrpage::logical_pageid, la_cache_buffer::logpage, LSA_AS_ARGS, LSA_COPY(), NO_ERROR, NULL, log_lsa::offset, log_hdrpage::offset, log_lsa::pageid, la_act_log::path, prm_get_integer_value(), prm_get_string_value(), PRM_ID_HA_REPLICA_DELAY_IN_SECS, PRM_ID_HA_REPLICA_TIME_BOUND, la_ha_apply_info::required_lsa, la_ha_apply_info::schema_counter, la_ha_apply_info::start_time, tde_decrypt_log_page(), db_datetime::time, log_rec_header::trid, log_rec_header::type, and la_ha_apply_info::update_counter.
Referenced by applyinfo().
static LOG_PHY_PAGEID la_log_phypageid (LOG_PAGEID logical_pageid) static
Definition at line 621 of file log_applier.c.
References la_info::act_log, assert, log_header::fpageid, la_act_log::log_hdr, LOGPB_HEADER_PAGE_ID, log_header::npages, PAGEID_MAX, and la_cache_buffer::phy_pageid.
Referenced by la_log_fetch(), and la_log_page_check().
static int la_log_record_process (LOG_RECORD_HEADER * lrec, LOG_LSA * final, LOG_PAGE * pg_ptr) static
Definition at line 5999 of file log_applier.c.
References ARG_FILE_LINE, assert, log_rec_ha_server_state::at_time, log_rec_header::back_lsa, la_info::commit_counter, la_info::committed_lsa, css_ha_server_state_string(), la_info::db_lockf_vdes, er_errid(), ER_ERROR_SEVERITY, ER_FAILED, ER_HA_GENERIC_ERROR, ER_HA_LA_EXCEED_MAX_MEM_SIZE, ER_HA_LA_INVALID_REPL_LOG_RECORD, ER_HA_LA_UNEXPECTED_EOF_IN_ARCHIVE_LOG, ER_INTERRUPTED, ER_LC_FAILED_TO_FLUSH_REPL_ITEMS, ER_LC_PARTIALLY_FAILED_TO_FLUSH, ER_LK_UNILATERALLY_ABORTED, er_log_debug, ER_LOG_PAGE_CORRUPTED, ER_NET_CANT_CONNECT_SERVER, ER_NET_SERVER_COMM_ERROR, ER_NOTIFICATION_SEVERITY, er_set(), ER_TDE_CIPHER_IS_NOT_LOADED, ER_TM_SERVER_DOWN_UNILATERALLY_ABORTED, error(), log_rec_header::forw_lsa, HA_SERVER_STATE_ACTIVE, HA_SERVER_STATE_TO_BE_STANDBY, log_page::hdr, la_info::is_end_of_record, la_info::is_role_changed, la_add_apply_list(), la_add_node_into_la_commit_list(), la_applier_need_shutdown, la_apply_commit_list(), la_delay_replica(), la_does_page_exist(), la_free_repl_items_by_tranid(), la_get_ha_server_state(), la_is_repl_lists_empty(), la_log_commit(), LA_PAGE_EXST_IN_ARCHIVE_LOG, la_peer_host, la_retrieve_eot_time(), la_set_repl_log(), la_slave_db_name, LA_STATUS_BUSY, LA_STATUS_IDLE, la_update_ha_apply_info_log_record_time(), LOG_ABORT, LOG_COMMIT, LOG_DUMMY_CRASH_RECOVERY, LOG_DUMMY_HA_SERVER_STATE, LOG_END_CHKPT, LOG_END_OF_LOG, LOG_LARGER_LOGREC_TYPE, LOG_REPLICATION_DATA, LOG_REPLICATION_STATEMENT, LOG_SMALLER_LOGREC_TYPE, LOG_SYSOP_END, LOG_SYSTEM_TRANID, log_hdrpage::logical_pageid, LSA_COPY(), LSA_GT(), LSA_ISNULL(), NO_ERROR, NULL, NULL_PAGEID, NULL_TRANID, NULL_VOLDES, log_lsa::offset, log_lsa::pageid, log_rec_header::prev_tranlsa, snprintf_dots_truncate, la_apply::start_lsa, log_rec_ha_server_state::state, la_info::status, log_rec_header::trid, and log_rec_header::type.
Referenced by la_apply_log_file().
static LA_ITEM * la_make_repl_item (LOG_PAGE * log_pgptr, int log_type, int tranid, LOG_LSA * lsa) static
Definition at line 3096 of file log_applier.c.
References log_page::area, ARG_FILE_LINE, la_item::class_name, db_make_string(), db_private_free_and_init, DB_SIZEOF, la_item::db_user, ER_ERROR_SEVERITY, ER_GENERIC_ERROR, er_set(), error(), free_and_init, la_item::ha_sys_prm, la_item::item_type, la_item::key, la_log_copy_fromlog(), LA_LOG_READ_ADVANCE_WHEN_DOESNT_FIT, LA_LOG_READ_ALIGN, la_new_repl_item(), log_rec_replication::length, LOG_REPLICATION_DATA, LOG_REPLICATION_STATEMENT, la_item::log_type, log_rec_replication::lsa, MAX_ALIGNMENT, db_value::need_clear, NO_ERROR, NULL, log_lsa::offset, or_unpack_int(), or_unpack_string(), la_item::packed_key_value, la_item::packed_key_value_length, log_lsa::pageid, la_cache_buffer::pageid, pr_clear_value(), PTR_ALIGN, and log_rec_replication::rcvindex.
Referenced by la_get_next_repl_item_from_log(), and la_set_repl_log().
static void la_make_room_for_mvcc_insid (RECDES * recdes) static
Definition at line 3673 of file log_applier.c.
References recdes::area_size, assert, recdes::data, LA_MOVE_INSIDE_RECORD, recdes::length, OR_GET_MVCC_REPID_AND_FLAG, OR_INT_SIZE, OR_MVCC_FLAG_MASK, OR_MVCC_FLAG_SHIFT_BITS, OR_MVCC_FLAG_VALID_DELID, OR_MVCCID_SIZE, REC_BIGONE, and recdes::type.
Referenced by la_get_recdes().
static bool la_need_filter_out (LA_ITEM * item) static
Definition at line 7536 of file log_applier.c.
References assert, la_item::class_name, CT_SERIAL_NAME, CUBRID_STMT_TRUNCATE, i, la_item::item_type, la_repl_filter::list, LOG_REPLICATION_STATEMENT, la_item::log_type, NULL, la_repl_filter::num_filters, la_info::repl_filter, REPL_FILTER_EXCLUDE_TBL, REPL_FILTER_INCLUDE_TBL, REPL_FILTER_NONE, and la_repl_filter::type.
Referenced by la_apply_repl_log(), and la_apply_statement_log().
static LA_ITEM * la_new_repl_item (LOG_LSA * lsa, LOG_LSA * target_lsa) static
Definition at line 3016 of file log_applier.c.
References ARG_FILE_LINE, la_item::class_name, db_make_null(), DB_SIZEOF, la_item::db_user, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), la_item::ha_sys_prm, la_item::item_type, la_item::key, la_item::log_type, la_item::lsa, LSA_COPY(), la_item::next, NULL, la_item::packed_key_value, la_item::packed_key_value_length, la_item::prev, and la_item::target_lsa.
Referenced by la_make_repl_item().
void la_print_delay_info (LOG_LSA working_lsa, LOG_LSA target_lsa, float process_rate)
Definition at line 7269 of file log_applier.c.
References log_lsa::pageid.
Referenced by applyinfo().
void la_print_log_arv_header (const char * database_name, LOG_ARV_HEADER * hdr, bool verbose)
Definition at line 7018 of file log_applier.c.
References log_arv_header::arv_num, log_arv_header::db_creation, db_datetime_to_string(), db_localdatetime(), log_arv_header::fpageid, log_arv_header::next_trid, and log_arv_header::npages.
Referenced by la_log_page_check().
void la_print_log_header (const char * database_name, LOG_HEADER * hdr, bool verbose)
Definition at line 6960 of file log_applier.c.
References log_header::append_lsa, log_header::chkpt_lsa, css_ha_server_state_string(), log_header::db_charset, log_header::db_creation, db_datetime_to_string(), log_header::db_iopagesize, db_localdatetime(), log_header::db_logpagesize, log_header::db_release, log_header::db_restore_time, log_header::eof_lsa, log_header::fpageid, log_header::ha_file_status, log_header::ha_promotion_time, log_header::ha_server_state, log_header::is_shutdown, lang_charset_cubrid_name(), logwr_log_ha_filestat_to_string(), log_header::magic, log_header::mark_will_del, log_header::next_trid, log_header::npages, log_header::nxarv_num, log_header::nxarv_pageid, log_header::nxarv_phy_pageid, log_lsa::offset, and log_lsa::pageid.
Referenced by la_log_page_check().
static void la_print_repl_filter_info (void) static
Definition at line 7490 of file log_applier.c.
References ARG_FILE_LINE, ER_HA_LA_REPL_FILTER_GENERIC, ER_NOTIFICATION_SEVERITY, er_set(), er_stack_pop(), er_stack_push(), i, la_repl_filter::list, la_repl_filter::num_filters, p, la_info::repl_filter, REPL_FILTER_EXCLUDE_TBL, REPL_FILTER_INCLUDE_TBL, REPL_FILTER_NONE, and la_repl_filter::type.
Referenced by la_apply_log_file().
static int la_realloc_recdes_data (RECDES * recdes, int data_size) static
Definition at line 2348 of file log_applier.c.
References recdes::area_size, ARG_FILE_LINE, recdes::data, la_recdes_pool::db_page_size, ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, la_recdes_pool::is_initialized, recdes::length, NO_ERROR, and NULL.
Referenced by la_get_overflow_recdes().
static void la_release_all_page_buffers (LOG_PAGEID except_pageid) static
Definition at line 1378 of file log_applier.c.
References la_info::cache_pb, la_cache_buffer::fix_count, i, la_cache_pb::log_buffer, NULL, la_cache_pb::num_buffers, la_cache_buffer::pageid, and la_cache_buffer::recently_free.
Referenced by la_apply_log_file(), and la_apply_repl_log().
static void la_release_page_buffer (LOG_PAGEID pageid) static
Definition at line 1355 of file log_applier.c.
References la_info::cache_pb, la_cache_buffer::fix_count, la_cache_pb::hash_table, mht_get(), NULL, la_cache_buffer::pageid, and la_cache_buffer::recently_free.
Referenced by la_apply_insert_log(), la_apply_update_log(), la_does_page_exist(), la_get_next_repl_item_from_log(), la_get_overflow_recdes(), and la_get_relocation_recdes().
int la_remove_archive_logs (const char * db_name, int last_deleted_arv_num, int nxarv_num, int max_arv_count_to_delete) static
Definition at line 7303 of file log_applier.c.
References error(), fileio_make_log_archive_name(), fileio_unformat(), i, la_find_archive_num(), LA_LOG_IS_IN_ARCHIVE, log_dump_log_info(), la_info::log_path, la_info::loginf_path, MSGCAT_CATALOG_CUBRID, MSGCAT_LOG_LOGINFO_REMOVE_REASON, MSGCAT_LOG_MAX_ARCHIVES_HAS_BEEN_EXCEEDED, msgcat_message(), MSGCAT_SET_LOG, NO_ERROR, NULL, log_lsa::pageid, prm_get_integer_value(), PRM_ID_HA_COPY_LOG_MAX_ARCHIVES, and la_info::required_lsa.
Referenced by la_apply_log_file().
static int la_repl_add_object (MOP classop, LA_ITEM * item, RECDES * recdes) static
Definition at line 4819 of file log_applier.c.
References assert, au_fetch_class(), AU_FETCH_READ, AU_SELECT, classobj_class_has_indexes(), DB_NOT_PARTITIONED_CLASS, error(), la_item::item_type, LC_FLUSH_DELETE, LC_INSERT_OPERATION_TYPE, LC_UPDATE_OPERATION_TYPE, NO_ERROR, NULL, la_item::packed_key_value, la_item::packed_key_value_length, RVREPL_DATA_DELETE, RVREPL_DATA_INSERT, RVREPL_DATA_UPDATE, RVREPL_DATA_UPDATE_END, RVREPL_DATA_UPDATE_START, sm_flush_objects(), sm_partitioned_class_type(), ws_add_to_repl_obj_list(), and ws_oid().
Referenced by la_apply_delete_log(), la_apply_insert_log(), and la_apply_update_log().
static bool la_restart_on_bulk_flush_error (int errid) static
Definition at line 2271 of file log_applier.c.
References la_ignore_on_error(), and la_retry_on_error().
Referenced by la_flush_repl_items().
static time_t la_retrieve_eot_time (LOG_PAGE * pgptr, LOG_LSA * lsa) static
Definition at line 3519 of file log_applier.c.
References log_page::area, log_rec_donetime::at_time, DB_SIZEOF, error(), LA_LOG_READ_ADVANCE_WHEN_DOESNT_FIT, LA_LOG_READ_ALIGN, NO_ERROR, log_lsa::offset, log_lsa::pageid, and la_cache_buffer::pageid.
Referenced by la_log_record_process().
static bool la_retry_on_error (int errid) static
Definition at line 2282 of file log_applier.c.
References assert_release, LA_RETRY_ON_ERROR, NO_ERROR, PRM_ID_HA_APPLYLOGDB_RETRY_ERROR_LIST, and sysprm_find_err_in_integer_list().
Referenced by la_apply_repl_log(), and la_restart_on_bulk_flush_error().
static int la_set_repl_log (LOG_PAGE * log_pgptr, int log_type, int tranid, LOG_LSA * lsa) static
Definition at line 3423 of file log_applier.c.
References ARG_FILE_LINE, er_log_debug, ER_OUT_OF_VIRTUAL_MEMORY, la_apply::is_long_trans, la_add_repl_item(), la_find_apply_list(), la_free_all_repl_items_except_head(), la_make_repl_item(), LA_MAX_REPL_ITEMS, la_apply::last_lsa, LSA_COPY(), NO_ERROR, NULL, and la_apply::num_items.
Referenced by la_log_record_process().
static void la_shutdown (void) static
Definition at line 6845 of file log_applier.c.
References la_info::act_log, la_info::arv_log, assert_release, la_cache_pb::buffer_area, la_info::cache_pb, DB_CLIENT_TYPE_LOG_APPLIER, db_get_client_type(), la_info::db_lockf_vdes, error(), fileio_close(), free_and_init, la_cache_pb::hash_table, la_act_log::hdr_page, i, la_recdes_pool::is_initialized, la_clear_recdes_pool(), la_destroy_repl_filter(), la_slave_db_name, la_unlock_dbname(), la_cache_pb::log_buffer, la_info::log_path_lockf_vdes, la_act_log::log_vdes, la_arv_log::log_vdes, log_zip_free(), mht_destroy(), NO_ERROR, NULL, NULL_VOLDES, la_info::num_unflushed, la_info::rec_type, la_info::redo_unzip_ptr, la_info::reinit_copylog, la_info::repl_cnt, la_info::repl_lists, la_info::undo_unzip_ptr, and ws_clear_all_repl_objs().
Referenced by la_apply_log_file().
static void la_shutdown_by_signal (int ignore) static
Definition at line 583 of file log_applier.c.
References la_applier_need_shutdown, and la_applier_shutdown_by_signal.
Referenced by la_apply_log_file().
static void la_unlink_repl_item (LA_APPLY * apply, LA_ITEM * item) static
Definition at line 3232 of file log_applier.c.
References assert, la_apply::head, la_item::next, NULL, la_apply::num_items, la_item::prev, and la_apply::tail.
Referenced by la_free_repl_item().
static int la_unlock_dbname (int * lockf_vdes, char * db_name, bool clear_owner) static
Definition at line 6754 of file log_applier.c.
References ER_FAILED, error(), FILEIO_LOCKF, fileio_unlock_la_dbname(), la_info::is_role_changed, LA_SLEEP, NO_ERROR, and NULL_VOLDES.
Referenced by la_apply_log_file(), and la_shutdown().
static int la_update_ha_apply_info_log_record_time (time_t new_time) static
Definition at line 1888 of file log_applier.c.
References la_info::act_log, assert_release, CT_HA_APPLY_INFO_NAME, log_header::db_creation, db_localdatetime(), db_make_datetime(), db_make_varchar(), db_value_clear(), er_clear(), i, la_info::is_apply_info_updated, LA_IN_VALUE_COUNT, la_insert_ha_apply_info(), LA_QUERY_BUF_SIZE, la_update_query_execute_with_values(), LANG_SYS_CODESET, LANG_SYS_COLLATION, la_act_log::log_hdr, la_info::log_path, la_info::log_record_time, log_header::prefix_name, and strlen.
Referenced by la_log_record_process().
static int la_update_ha_apply_info_start_time (void) static
Definition at line 1851 of file log_applier.c.
References la_info::act_log, assert, CT_HA_APPLY_INFO_NAME, db_make_varchar(), db_value_clear(), i, la_info::is_apply_info_updated, LA_IN_VALUE_COUNT, LA_QUERY_BUF_SIZE, la_update_query_execute_with_values(), LANG_SYS_CODESET, LANG_SYS_COLLATION, la_act_log::log_hdr, la_info::log_path, log_header::prefix_name, and strlen.
Referenced by la_get_last_ha_applied_info().
static int la_update_ha_last_applied_info (void) static
Definition at line 2065 of file log_applier.c.
References la_info::act_log, la_info::append_lsa, assert_release, la_info::commit_counter, la_info::committed_lsa, la_info::committed_rep_lsa, CT_HA_APPLY_INFO_NAME, log_header::db_creation, db_localdatetime(), db_make_bigint(), db_make_datetime(), db_make_int(), db_make_null(), db_make_varchar(), db_value_clear(), la_info::delete_counter, la_info::eof_lsa, er_clear(), la_info::fail_counter, la_info::final_lsa, i, la_info::insert_counter, LA_IN_VALUE_COUNT, la_insert_ha_apply_info(), LA_QUERY_BUF_SIZE, la_update_query_execute_with_values(), LANG_SYS_CODESET, LANG_SYS_COLLATION, la_info::last_committed_lsa, la_info::last_committed_rep_lsa, la_info::log_commit_time, la_act_log::log_hdr, la_info::log_path, la_info::log_record_time, LSA_GE(), log_lsa::offset, log_lsa::pageid, log_header::prefix_name, la_info::required_lsa, la_info::schema_counter, strlen, and la_info::update_counter.
Referenced by la_log_commit().
static int la_update_last_deleted_arv_num (int lockf_vdes, int last_deleted_arv_num) static
Definition at line 6696 of file log_applier.c.
References assert, ER_FAILED, NO_ERROR, and NULL_VOLDES.
Referenced by la_apply_log_file().
static int la_update_query_execute (const char * sql, bool au_disable) static
Definition at line 5329 of file log_applier.c.
References ARG_FILE_LINE, AU_DISABLE, AU_ENABLE, db_execute(), db_query_end(), er_log_debug, error(), and NO_ERROR.
Referenced by la_apply_statement_log().
static int la_update_query_execute_with_values (const char * sql, int arg_count, DB_VALUE * vals, bool au_disable) static
Definition at line 5373 of file log_applier.c.
References AU_DISABLE, AU_ENABLE, db_execute_with_values(), db_query_end(), error(), and NO_ERROR.
Referenced by la_delete_ha_apply_info(), la_insert_ha_apply_info(), la_update_ha_apply_info_log_record_time(), la_update_ha_apply_info_start_time(), and la_update_ha_last_applied_info().
static unsigned int log_pageid_hash (const void * key, unsigned int htsize) static
Definition at line 2504 of file log_applier.c.
References assert, LOGPB_HEADER_PAGE_ID, and NULL.
Referenced by la_init_cache_log_buffer().
Variable Documentation
bool la_applier_need_shutdown = false static
Definition at line 420 of file log_applier.c.
Referenced by la_apply_log_file(), la_find_log_pagesize(), la_force_shutdown(), la_log_fetch(), la_log_fetch_from_archive(), la_log_record_process(), and la_shutdown_by_signal().
bool la_applier_shutdown_by_signal = false static
Definition at line 421 of file log_applier.c.
Referenced by la_apply_log_file(), la_force_shutdown(), and la_shutdown_by_signal().
bool la_enable_sql_logging = false static
Definition at line 425 of file log_applier.c.
Referenced by la_apply_delete_log(), la_apply_insert_log(), la_apply_log_file(), la_apply_statement_log(), and la_apply_update_log().
LA_INFO la_Info
Definition at line 416 of file log_applier.c.
char la_peer_host[CUB_MAXHOSTNAMELEN+1] static
Definition at line 423 of file log_applier.c.
Referenced by la_apply_log_file(), la_change_state(), and la_log_record_process().
LA_RECDES_POOL la_recdes_pool
Definition at line 418 of file log_applier.c.
char la_slave_db_name[DB_MAX_IDENTIFIER_LENGTH+1] static
Definition at line 422 of file log_applier.c.
Referenced by la_apply_log_file(), la_apply_repl_log(), la_change_state(), la_get_hostname_from_log_path(), la_log_record_process(), and la_shutdown().