CUBRID Engine: src/transaction/log_compress.c File Reference
log_compress.c File Reference
#include <string.h>
#include <assert.h>
#include "log_compress.h"
#include "error_manager.h"
#include "memory_alloc.h"
#include "perf_monitor.h"
Functions
bool log_zip (LOG_ZIP *log_zip, LOG_ZIP_SIZE_T length, const void *data)
bool log_unzip (LOG_ZIP *log_unzip, LOG_ZIP_SIZE_T length, void *data)
bool log_diff (LOG_ZIP_SIZE_T undo_length, const void *undo_data, LOG_ZIP_SIZE_T redo_length, void *redo_data)
LOG_ZIP * log_zip_alloc (LOG_ZIP_SIZE_T size)
void log_zip_free (LOG_ZIP *log_zip)
Function Documentation
bool log_diff (LOG_ZIP_SIZE_T undo_length, const void * undo_data, LOG_ZIP_SIZE_T redo_length, void * redo_data)
Definition at line 201 of file log_compress.c.
References assert, i, LOG_ZIP_SIZE_T, NULL, and p.
Referenced by la_get_zipped_data(), log_rv_redo_record(), and prior_lsa_gen_undoredo_record_from_crumbs().
bool log_unzip (LOG_ZIP * log_unzip, LOG_ZIP_SIZE_T length, void * data)
Definition at line 123 of file log_compress.c.
References ARG_FILE_LINE, assert, log_zip::buf_size, log_zip::data_length, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, log_zip::log_data, LOG_ZIP_SIZE_T, NULL, and PSTAT_LOG_LZ4_DECOMPRESS_TIME_COUNTERS.
Referenced by la_get_log_data(), la_get_next_update_log(), la_get_undoredo_diff(), log_dump_data(), log_get_undo_record(), log_rollback_record(), log_rv_get_unzip_log_data(), log_rv_redo_record(), log_rv_undo_record(), and vacuum_process_log_record().
bool log_zip (LOG_ZIP * log_zip, LOG_ZIP_SIZE_T length, const void * data)
Definition at line 43 of file log_compress.c.
References ARG_FILE_LINE, assert, log_zip::buf_size, log_zip::data_length, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, log_zip::log_data, LOG_ZIP_BUF_SIZE, LOG_ZIP_SIZE_T, NULL, and PSTAT_LOG_LZ4_COMPRESS_TIME_COUNTERS.
Referenced by log_zip_alloc(), and prior_lsa_gen_undoredo_record_from_crumbs().
LOG_ZIP* log_zip_alloc (LOG_ZIP_SIZE_T size)
Definition at line 230 of file log_compress.c.
References ARG_FILE_LINE, assert, log_zip::buf_size, log_zip::data_length, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, log_zip::log_data, log_zip(), LOG_ZIP_BUF_SIZE, LOG_ZIP_SIZE_T, and NULL.
Referenced by la_apply_pre(), log_append_get_zip_redo(), log_append_get_zip_undo(), log_append_init_zip(), log_get_undo_record(), log_recovery_redo(), log_recovery_undo(), log_rollback(), vacuum_worker_allocate_resources(), and xlog_dump().
void log_zip_free (LOG_ZIP * log_zip)
Definition at line 265 of file log_compress.c.
References assert, free_and_init, log_zip::log_data, and NULL.
Referenced by cubthread::entry::clear_resources(), la_shutdown(), log_append_final_zip(), log_append_init_zip(), log_get_undo_record(), log_recovery_redo(), log_recovery_undo(), log_rollback(), vacuum_finalize_worker(), and xlog_dump().