CUBRID Engine: src/transaction/log_lsa.hpp File Reference
log_lsa.hpp File Reference
#include <cassert>
#include <cinttypes>
#include <cstddef>
Classes
struct log_lsa
Macros
#define Wrong module
#define LSA_INITIALIZER {NULL_LOG_PAGEID, NULL_LOG_OFFSET}
#define LSA_AS_ARGS(lsa_ptr) (long long int) (lsa_ptr)->pageid, (int) (lsa_ptr)->offset
Typedefs
using LOG_LSA = log_lsa
Functions
void lsa_to_string (char *buf, int buf_size, const log_lsa *lsa)
void LSA_COPY (log_lsa *plsa1, const log_lsa *plsa2)
void LSA_SET_NULL (log_lsa *lsa_ptr)
bool LSA_ISNULL (const log_lsa *lsa_ptr)
bool LSA_EQ (const log_lsa *plsa1, const log_lsa *plsa2)
bool LSA_LE (const log_lsa *plsa1, const log_lsa *plsa2)
bool LSA_LT (const log_lsa *plsa1, const log_lsa *plsa2)
bool LSA_GE (const log_lsa *plsa1, const log_lsa *plsa2)
bool LSA_GT (const log_lsa *plsa1, const log_lsa *plsa2)
Variables
static const std::int64_t NULL_LOG_PAGEID = -1
static const std::int16_t NULL_LOG_OFFSET = -1
const log_lsa NULL_LSA = { NULL_LOG_PAGEID, NULL_LOG_OFFSET }
Macro Definition Documentation
#define LSA_AS_ARGS (lsa_ptr) (long long int) (lsa_ptr)->pageid, (int) (lsa_ptr)->offset
Definition at line 78 of file log_lsa.hpp.
Referenced by file_rv_dealloc_on_postpone(), file_rv_dealloc_on_undo(), file_tracker_item_mark_heap_deleted(), hb_resource_check_server_log_grow(), hb_resource_receive_get_eof(), la_log_page_check(), locator_print_class_name(), log_dump_checkpoint_topops(), log_dump_header(), log_dump_record_checkpoint(), log_dump_record_commit_postpone(), log_dump_record_compensate(), log_dump_record_postpone(), log_dump_record_replication(), log_dump_record_save_point(), log_dump_record_sysop_end_internal(), log_dump_record_sysop_start_postpone(), log_recovery(), log_recovery_abort_atomic_sysop(), log_recovery_needs_skip_logical_redo(), log_recovery_redo(), log_recovery_undo(), logpb_dump_log_header(), logtb_dump_top_operations(), lsa_to_string(), pgbuf_check_bcb_page_vpid(), pgbuf_flush_seq_list(), pgbuf_unfix_all(), prior_lsa_next_record_internal(), tx_transient_class_registry::to_string(), vacuum_data_load_and_recover(), vacuum_process_log_block(), vacuum_produce_log_block_data(), vacuum_recover_lost_block_data(), and xlog_dump().
#define LSA_INITIALIZER {NULL_LOG_PAGEID, NULL_LOG_OFFSET}
Definition at line 76 of file log_lsa.hpp.
Referenced by btree_key_relocate_last_into_ovf(), btree_merge_node_and_advance(), btree_split_node_and_advance(), disk_volume_expand(), file_extdata_merge_pages(), heap_attrinfo_transform_to_disk_internal(), heap_update_adjust_recdes_header(), heap_update_relocation(), log_append_sysop_end(), log_recovery_abort_interrupted_sysop(), logwr_log_ha_filestat_to_string(), pgbuf_flush_victim_candidates(), and vacuum_recover_lost_block_data().
#define Wrong module
Definition at line 27 of file log_lsa.hpp.
Typedef Documentation
using LOG_LSA = log_lsa
Definition at line 55 of file log_lsa.hpp.
Function Documentation
void LSA_COPY (log_lsa * plsa1, const log_lsa * plsa2) inline
Definition at line 139 of file log_lsa.hpp.
References assert, and NULL.
Referenced by btree_delete_helper_to_insert_helper(), btree_delete_internal(), btree_delete_key_from_leaf(), btree_get_next_key_info(), btree_insert_helper_to_delete_helper(), btree_insert_internal(), btree_insert_mvcc_delid_into_page(), btree_key_append_object_as_new_overflow(), btree_key_append_object_non_unique(), btree_key_append_object_to_overflow(), btree_key_append_object_unique(), btree_key_find_and_lock_unique_of_non_unique(), btree_key_insert_new_key(), btree_key_lock_and_append_object_unique(), btree_key_online_index_IB_insert(), btree_key_online_index_tran_delete(), btree_key_online_index_tran_insert(), btree_key_online_index_tran_insert_DF(), btree_key_relocate_last_into_ovf(), btree_key_remove_delete_mvccid_unique(), btree_key_remove_insert_mvccid(), btree_key_remove_object_and_keep_visible_first(), btree_leaf_record_replace_first_with_last(), btree_modify_leaf_ovfl_vpid(), btree_modify_overflow_link(), btree_online_index_list_dispatcher(), btree_range_scan(), btree_record_remove_object(), btree_replace_first_oid_with_ovfl_oid(), dwb_initialize_slot(), dwb_load_and_recover_pages(), dwb_set_slot_data(), fileio_continue_restore(), fileio_set_page_lsa(), fileio_start_backup(), fix_volume_header(), hb_resource_check_server_log_grow(), heap_get_visible_version_from_log(), heap_log_delete_physical(), heap_update_home(), heap_update_relocation(), la_add_node_into_la_commit_list(), la_apply_commit_list(), la_apply_log_file(), la_apply_pre(), la_apply_repl_log(), la_find_required_lsa(), la_get_last_ha_applied_info(), la_get_next_repl_item_from_log(), la_get_next_update_log(), la_get_overflow_recdes(), la_get_relocation_recdes(), la_log_commit(), la_log_page_check(), la_log_record_process(), la_new_repl_item(), la_set_repl_log(), locator_savepoint_class_name_entry(), locator_update_index(), log_2pc_recovery_analysis_info(), log_abort_partial(), log_append_commit_postpone(), log_append_compensate_internal(), log_append_donetime_internal(), log_append_postpone(), log_append_redo_crumbs(), log_append_repl_info_internal(), log_append_run_postpone(), log_append_savepoint(), log_append_undoredo_crumbs(), log_do_postpone(), log_execute_run_postpone(), log_final(), log_find_end_log(), log_get_next_nested_top(), log_get_parent_lsa_system_op(), log_get_savepoint_lsa(), log_initialize_internal(), log_is_page_of_record_broken(), log_recovery(), log_recovery_abort_atomic_sysop(), log_recovery_analysis(), log_recovery_find_first_postpone(), log_recovery_redo(), log_recovery_resetlog(), log_recovery_undo(), log_rollback(), log_rollback_record(), log_run_postpone_op(), log_rv_analysis_2pc_abort_decision(), log_rv_analysis_2pc_abort_inform_particps(), log_rv_analysis_2pc_commit_decision(), log_rv_analysis_2pc_commit_inform_particps(), log_rv_analysis_2pc_prepare(), log_rv_analysis_2pc_recv_ack(), log_rv_analysis_2pc_start(), log_rv_analysis_commit_with_postpone(), log_rv_analysis_compensate(), log_rv_analysis_complete(), log_rv_analysis_dummy_head_postpone(), log_rv_analysis_end_checkpoint(), log_rv_analysis_postpone(), log_rv_analysis_run_postpone(), log_rv_analysis_save_point(), log_rv_analysis_sysop_end(), log_rv_analysis_sysop_start_postpone(), log_rv_analysis_undo_redo(), log_rv_analysis_will_commit(), log_rv_find_checkpoint(), log_rv_undo_record(), log_skip_logging(), log_startof_nxrec(), log_sysop_abort(), log_sysop_attach_to_outer(), log_sysop_commit_internal(), log_sysop_end_unstack(), log_sysop_start(), logpb_backup(), logpb_checkpoint(), logpb_checkpoint_trans(), logpb_fatal_error_internal(), logpb_fetch_page(), logpb_flush_all_append_pages(), logpb_initialize_header(), logpb_remove_archive_logs(), logpb_restore(), logpb_start_append(), logtb_find_smallest_lsa(), logtb_rv_find_allocate_tran_index(), logtb_rv_update_global_unique_stats_by_abs(), logtb_update_global_unique_stats_by_delta(), logwr_log_ha_filestat_to_string(), pgbuf_bcb_flush_with_wal(), pgbuf_flush_checkpoint(), pgbuf_flush_page_and_neighbors_fb(), pgbuf_flush_seq_list(), pgbuf_flush_victim_candidates(), pgbuf_page_has_changed(), pgbuf_set_lsa(), pgbuf_unfix_debug(), prior_lsa_end_append(), prior_lsa_next_record_internal(), prior_lsa_start_append(), repl_log_get_append_lsa(), scan_next_heap_scan(), vacuum_consume_buffer_log_blocks(), vacuum_notify_server_crashed(), vacuum_process_log_block(), vacuum_process_log_record(), vacuum_recover_lost_block_data(), xlog_dump(), and xtran_server_savepoint().
bool LSA_EQ (const log_lsa * plsa1, const log_lsa * plsa2) inline
Definition at line 160 of file log_lsa.hpp.
References assert, and NULL.
Referenced by btree_key_find_and_lock_unique_of_non_unique(), btree_key_lock_and_append_object_unique(), btree_leaf_lsa_eq(), btree_range_scan_resume(), dwb_slots_hash_insert(), fileio_is_page_sane(), la_apply_log_file(), la_get_next_repl_item_from_log(), log_do_postpone(), log_find_end_log(), log_initialize_internal(), log_prior_has_worker_log_records(), log_recovery_abort_atomic_sysop(), log_recovery_abort_interrupted_sysop(), log_recovery_analysis(), log_recovery_find_first_postpone(), log_recovery_redo(), log_rollback_record(), log_rv_analysis_start_checkpoint(), log_rv_undo_record(), logpb_append_next_record(), logpb_end_append(), logpb_flush_log_for_wal(), logpb_start_append(), logtb_free_tran_index_with_undo_lsa(), pgbuf_check_bcb_page_vpid(), pgbuf_page_has_changed(), and xlog_dump().
bool LSA_GE (const log_lsa * plsa1, const log_lsa * plsa2) inline
Definition at line 181 of file log_lsa.hpp.
References assert, and NULL.
Referenced by la_apply_log_file(), la_get_next_repl_item_from_log(), la_update_ha_last_applied_info(), log_recovery_abort_atomic_sysop(), log_skip_logging(), logpb_flush_pages(), logwr_log_ha_filestat_to_string(), tx_lob_locator_clear(), and xtx_change_state_of_locator().
bool LSA_GT (const log_lsa * plsa1, const log_lsa * plsa2) inline
Definition at line 188 of file log_lsa.hpp.
References assert, and NULL.
Referenced by hb_resource_check_server_log_grow(), la_apply_log_file(), la_apply_repl_log(), la_find_required_lsa(), la_get_next_repl_item_from_log(), la_log_record_process(), log_do_postpone(), log_get_next_nested_top(), log_initialize_internal(), log_recovery_abort_atomic_sysop(), log_recovery_abort_interrupted_sysop(), log_recovery_analysis(), log_recovery_find_first_postpone(), log_recovery_redo(), log_rv_analysis_sysop_end(), log_skip_logging(), log_sysop_commit_internal(), logpb_checkpoint(), logpb_checkpoint_trans(), logtb_create_unique_stats_from_repr(), pgbuf_flush_checkpoint(), and pgbuf_flush_seq_list().
bool LSA_ISNULL (const log_lsa * lsa_ptr) inline
Definition at line 153 of file log_lsa.hpp.
References assert, log_lsa::is_null(), and NULL.
Referenced by applyinfo(), btree_rv_remove_marked_for_delete(), dwb_flush_block(), file_rv_tracker_mark_heap_deleted(), fileio_backup_volume(), fileio_write_backup_node(), hb_resource_check_server_log_grow(), heap_get_visible_version_from_log(), heap_update_set_prev_version(), la_apply_log_file(), la_find_required_lsa(), la_free_and_add_next_repl_item(), la_get_last_ha_applied_info(), la_get_next_repl_item_from_log(), la_get_overflow_recdes(), la_get_relocation_recdes(), la_log_record_process(), locator_drop_class_name_entry(), locator_is_exist_class_name_entry(), locator_permoid_class_name(), locator_savepoint_class_name_entry(), locator_update_index(), log_2pc_recovery_analysis_info(), log_abort_local(), log_abort_partial(), log_append_postpone(), log_append_sysop_end(), log_commit_local(), log_complete(), log_complete_for_2pc(), log_do_postpone(), log_find_end_log(), log_get_next_nested_top(), log_get_savepoint_lsa(), log_initialize_internal(), log_is_page_of_record_broken(), log_is_tran_in_system_op(), log_recovery_abort_atomic_sysop(), log_recovery_abort_interrupted_sysop(), log_recovery_analysis(), log_recovery_find_first_postpone(), log_recovery_finish_postpone(), log_recovery_finish_sysop_postpone(), log_recovery_redo(), log_recovery_resetlog(), log_recovery_undo(), log_rollback(), log_rv_analysis_dummy_head_postpone(), log_rv_analysis_postpone(), log_rv_analysis_run_postpone(), log_rv_analysis_sysop_end(), log_rv_find_checkpoint(), log_skip_logging(), log_startof_nxrec(), log_sysop_abort(), log_sysop_attach_to_outer(), log_sysop_commit_internal(), log_sysop_do_postpone(), log_sysop_start_atomic(), log_tran_do_postpone(), logpb_backup(), logpb_checkpoint(), logpb_checkpoint_topops(), logpb_checkpoint_trans(), logpb_flush_log_for_wal(), logpb_flush_pages(), logpb_is_smallest_lsa_in_archive(), logpb_last_complete_blockid(), logpb_remove_archive_logs(), logpb_remove_archive_logs_exceed_limit(), logtb_create_unique_stats_from_repr(), logtb_find_smallest_and_largest_active_pages(), logtb_find_smallest_lsa(), logtb_free_tran_index_with_undo_lsa(), logtb_has_updated(), logtb_reflect_global_unique_stats_to_btree(), logtb_rv_update_global_unique_stats_by_abs(), logtb_update_global_unique_stats_by_delta(), logwr_log_ha_filestat_to_string(), pgbuf_bcb_flush_with_wal(), pgbuf_claim_bcb_for_fix(), pgbuf_fix_debug(), pgbuf_flush_checkpoint(), pgbuf_flush_seq_list(), pgbuf_flush_victim_candidates(), pgbuf_set_lsa(), pgbuf_unlatch_bcb_upon_unfix(), prior_lsa_next_record_internal(), prior_lsa_start_append(), vacuum_data_load_and_recover(), vacuum_process_log_block(), vacuum_recover_lost_block_data(), vacuum_verify_vacuum_data_debug(), xlocator_delete_class_name(), xlocator_reserve_class_name(), and xlog_dump().
bool LSA_LE (const log_lsa * plsa1, const log_lsa * plsa2) inline
Definition at line 167 of file log_lsa.hpp.
References assert, and NULL.
Referenced by dwb_flush_block(), dwb_load_and_recover_pages(), la_apply_repl_log(), log_append_postpone(), log_get_next_nested_top(), log_is_logged_since_restart(), log_recovery_abort_interrupted_sysop(), log_recovery_finish_sysop_postpone(), log_recovery_redo(), log_rollback(), log_rv_analysis_sysop_end(), log_sysop_abort(), log_sysop_commit_internal(), logpb_checkpoint(), logpb_fetch_page(), logpb_need_wal(), pgbuf_flush_seq_list(), and pgbuf_flush_victim_candidates().
bool LSA_LT (const log_lsa * plsa1, const log_lsa * plsa2) inline
Definition at line 174 of file log_lsa.hpp.
References assert, and NULL.
Referenced by btree_reflect_global_unique_statistics(), dwb_load_and_recover_pages(), dwb_slots_hash_insert(), fileio_backup_volume(), fileio_write_backup_node(), heap_get_visible_version_from_log(), la_free_and_add_next_repl_item(), locator_drop_class_name_entry(), log_abort_partial(), log_do_postpone(), log_find_unilaterally_largest_undo_lsa(), log_get_undo_record(), log_prior_has_worker_log_records(), log_recovery_find_first_postpone(), log_recovery_needs_skip_logical_redo(), log_rv_analysis_end_checkpoint(), log_rv_analysis_sysop_start_postpone(), log_rv_find_checkpoint(), logpb_backup(), logpb_checkpoint(), logpb_flush_pages(), logpb_remove_archive_logs(), logtb_find_smallest_lsa(), pgbuf_flush_checkpoint(), pgbuf_flush_page_and_neighbors_fb(), pgbuf_flush_seq_list(), pgbuf_flush_victim_candidates(), pgbuf_set_lsa(), prior_lsa_next_record_internal(), tx_lob_locator_clear(), xtx_add_lob_locator(), and xtx_change_state_of_locator().
void LSA_SET_NULL (log_lsa * lsa_ptr) inline
Definition at line 146 of file log_lsa.hpp.
References assert, NULL, and log_lsa::set_null().
Referenced by applyinfo(), btree_range_scan(), dwb_init_slot(), fileio_abort_backup(), fileio_init_lsa_of_page(), fileio_initialize_backup(), fileio_reset_page_lsa(), fileio_start_backup(), hb_alloc_new_proc(), hb_cleanup_conn_and_start_process(), heap_update_adjust_recdes_header(), la_apply_commit_list(), la_apply_log_file(), la_clear_applied_info(), la_find_required_lsa(), la_get_ha_apply_info(), la_init(), la_init_ha_apply_info(), la_init_repl_lists(), locator_drop_class_name_entry(), locator_initialize(), locator_permoid_class_name(), locator_update_index(), log_2pc_recovery_analysis_info(), log_abort_partial(), log_append_repl_info_internal(), log_commit_local(), log_create_internal(), log_do_postpone(), log_dump_record(), log_find_end_log(), log_find_unilaterally_largest_undo_lsa(), log_get_next_nested_top(), log_get_parent_lsa_system_op(), log_get_savepoint_lsa(), log_initialize_internal(), log_recovery_abort_atomic_sysop(), log_recovery_analysis(), log_recovery_find_first_postpone(), log_recovery_finish_postpone(), log_recovery_finish_sysop_postpone(), log_recovery_redo(), log_recreate(), log_rollback(), log_rv_analysis_commit_with_postpone(), log_rv_analysis_run_postpone(), log_rv_analysis_sysop_end(), log_rv_analysis_sysop_start_postpone(), log_rv_analysis_will_commit(), log_sysop_end_logical_undo(), log_sysop_end_unstack(), log_sysop_start(), logpb_backup(), logpb_checkpoint(), logpb_copy_database(), logpb_finalize_pool(), logpb_flush_all_append_pages(), logpb_initialize_header(), logpb_page_get_first_null_block_lsa(), logpb_rename_all_volumes_files(), logpb_vacuum_reset_log_header_cache(), logtb_clear_tdes(), logtb_find_smallest_lsa(), logtb_get_system_tdes(), logtb_global_unique_stat_init(), logtb_initialize_global_unique_stats_table(), logtb_initialize_tdes(), logtb_reflect_global_unique_stats_to_btree(), logwr_log_ha_filestat_to_string(), log_system_tdes::on_sysop_end(), log_system_tdes::on_sysop_start(), or_mvcc_get_prev_version_lsa(), pgbuf_bcb_flush_with_wal(), pgbuf_claim_bcb_for_fix(), pgbuf_flush_checkpoint(), pgbuf_initialize_bcb_table(), pgbuf_invalidate_bcb(), prior_lsa_gen_undoredo_record_from_crumbs(), prior_lsa_next_record_internal(), prior_lsa_start_append(), vacuum_consume_buffer_log_blocks(), vacuum_data_load_and_recover(), vacuum_heap_record_insid_and_prev_version(), vacuum_process_log_block(), vacuum_process_log_record(), vacuum_rv_check_at_undo(), vacuum_rv_redo_remove_ovf_insid(), xlocator_delete_class_name(), xlocator_reserve_class_name(), xlog_dump(), xtran_server_savepoint(), and xtran_server_start_topop().
void lsa_to_string (char * buf, int buf_size, const log_lsa * lsa)
Definition at line 28 of file log_lsa.cpp.
References LSA_AS_ARGS.
Referenced by disk_volume_header_next_scan(), log_active_log_header_next_scan(), and logtb_descriptors_start_scan().
Variable Documentation
const std::int16_t NULL_LOG_OFFSET = -1 static
Definition at line 58 of file log_lsa.hpp.
Referenced by log_lsa::set_null().
const std::int64_t NULL_LOG_PAGEID = -1 static
Definition at line 57 of file log_lsa.hpp.
Referenced by log_lsa::is_null(), and log_lsa::set_null().
const log_lsa NULL_LSA = { NULL_LOG_PAGEID, NULL_LOG_OFFSET }
Definition at line 59 of file log_lsa.hpp.
Referenced by log_cleanup_modified_class_list(), log_header::log_header(), and logpb_finalize_pool().