CUBRID Engine: src/transaction/log_impl.h File Reference
log_impl.h File Reference
#include "boot.h"
#include "btree_unique.hpp"
#include "client_credentials.hpp"
#include "config.h"
#include "connection_globals.h"
#include "critical_section.h"
#include "es.h"
#include "file_io.h"
#include "lock_free.h"
#include "lock_manager.h"
#include "log_2pc.h"
#include "log_append.hpp"
#include "log_archives.hpp"
#include "log_comm.h"
#include "log_common_impl.h"
#include "log_lsa.hpp"
#include "log_postpone_cache.hpp"
#include "log_storage.hpp"
#include "mvcc.h"
#include "mvcc_table.hpp"
#include "porting.h"
#include "recovery.h"
#include "release_string.h"
#include "storage_common.h"
#include "thread_entry.hpp"
#include "transaction_transient.hpp"
#include "tde.h"
#include <assert.h>
#include <signal.h>
Classes
struct log_flush_info
struct log_group_commit_info
struct log_topops_addresses
struct log_topops_stack
struct log_unique_stats
struct log_tran_btid_unique_stats
struct log_tran_btid_unique_stats_chunk
struct log_tran_class_cos
struct log_tran_class_cos_chunk
struct log_tran_update_stats
struct log_rcv_tdes
struct log_tdes
struct log_addr_tdesarea
struct trantable
struct global_unique_stats
struct global_unique_stats_table
struct log_global
struct log_logging_stat
Macros
#define TR_TABLE_CS_ENTER(thread_p)
#define TR_TABLE_CS_ENTER_READ_MODE(thread_p)
#define TR_TABLE_CS_EXIT(thread_p)
#define LOG_ARCHIVE_CS_ENTER(thread_p)
#define LOG_ARCHIVE_CS_ENTER_READ_MODE(thread_p)
#define LOG_ARCHIVE_CS_EXIT(thread_p)
#define LOG_ARCHIVE_CS_OWN(thread_p) (true)
#define LOG_ARCHIVE_CS_OWN_WRITE_MODE(thread_p) (true)
#define LOG_ARCHIVE_CS_OWN_READ_MODE(thread_p) (true)
#define LOG_ESTIMATE_NACTIVE_TRANS 100 /* Estimate num of trans */
#define LOG_ESTIMATE_NOBJ_LOCKS 977 /* Estimate num of locks */
#define LOGAREA_SIZE (LOG_PAGESIZE - SSIZEOF(LOG_HDRPAGE))
#define LOG_IS_GROUP_COMMIT_ACTIVE() (prm_get_integer_value (PRM_ID_LOG_GROUP_COMMIT_INTERVAL_MSECS) > 0)
#define LOG_READ_ALIGN(thread_p, lsa, log_pgptr)
#define LOG_READ_ADD_ALIGN(thread_p, add, lsa, log_pgptr)
#define LOG_READ_ADVANCE_WHEN_DOESNT_FIT(thread_p, length, lsa, log_pgptr)
#define LOG_FIND_THREAD_TRAN_INDEX(thrd) (log_Tran_index)
#define LOG_SET_CURRENT_TRAN_INDEX(thrd, index) log_Tran_index = (index)
#define LOG_ISTRAN_ACTIVE(tdes) ((tdes)->state == TRAN_ACTIVE && LOG_ISRESTARTED ())
#define LOG_ISTRAN_COMMITTED(tdes)
#define LOG_ISTRAN_ABORTED(tdes)
#define LOG_ISTRAN_LOOSE_ENDS(tdes)
#define LOG_ISTRAN_2PC_IN_SECOND_PHASE(tdes)
#define LOG_ISTRAN_2PC(tdes)
#define LOG_ISTRAN_2PC_PREPARE(tdes) ((tdes)->state == TRAN_UNACTIVE_2PC_PREPARE)
#define LOG_ISTRAN_2PC_INFORMING_PARTICIPANTS(tdes)
#define LOG_READ_NEXT_TRANID (log_Gl.hdr.next_trid)
#define LOG_READ_NEXT_MVCCID (log_Gl.hdr.mvcc_next_id)
#define LOG_HAS_LOGGING_BEEN_IGNORED() (log_Gl.hdr.has_logging_been_skipped == true)
#define LOG_ISRESTARTED() (log_Gl.rcv_phase == LOG_RESTARTED)
#define LOG_CHECK_LOG_APPLIER(thread_p) (0)
#define _DB_DISABLE_MODIFICATIONS_
#define CHECK_MODIFICATION_NO_RETURN(thread_p, error)
#define MAX_NUM_EXEC_QUERY_HISTORY 100
#define LOG_GROUP_COMMIT_INFO_INITIALIZER { PTHREAD_MUTEX_INITIALIZER, PTHREAD_COND_INITIALIZER }
#define TRAN_UNIQUE_STATS_CHUNK_SIZE 128 /* size of the memory chunk for unique statistics */
#define COS_CLASSES_CHUNK_SIZE 64 /* size of the memory chunk for count optimization classes */
#define TRANTABLE_INITIALIZER { 0, 0, 0, 0, 0, 0, NULL, NULL }
#define GLOBAL_UNIQUE_STATS_TABLE_INITIALIZER { LF_HASH_TABLE_INITIALIZER, LF_ENTRY_DESCRIPTOR_INITIALIZER, LF_FREELIST_INITIALIZER, LSA_INITIALIZER, false }
#define GLOBAL_UNIQUE_STATS_HASH_SIZE 1000
#define LOG_TRAN_INDEX
#define LOG_THREAD_TRAN_MSG "(thr=%d, trid=%d)"
#define LOG_THREAD_TRAN_ARGS(thread_p) thread_get_current_entry_index (), LOG_FIND_CURRENT_TDES (thread_p)
Typedefs
typedef enum log_flush LOG_FLUSH
typedef enum log_setdirty LOG_SETDIRTY
typedef enum log_getnewtrid LOG_GETNEWTRID
typedef enum log_wrote_eot_log LOG_WRITE_EOT_LOG
typedef struct log_flush_info LOG_FLUSH_INFO
typedef struct log_group_commit_info LOG_GROUP_COMMIT_INFO
typedef struct log_topops_addresses LOG_TOPOPS_ADDRESSES
typedef enum log_topops_type LOG_TOPOPS_TYPE
typedef struct log_topops_stack LOG_TOPOPS_STACK
typedef enum tran_abort_reason TRAN_ABORT_REASON
typedef struct log_unique_stats LOG_UNIQUE_STATS
typedef struct log_tran_btid_unique_stats LOG_TRAN_BTID_UNIQUE_STATS
typedef enum count_optim_state COUNT_OPTIM_STATE
typedef struct log_tran_btid_unique_stats_chunk LOG_TRAN_BTID_UNIQUE_STATS_CHUNK
typedef struct log_tran_class_cos LOG_TRAN_CLASS_COS
typedef struct log_tran_class_cos_chunk LOG_TRAN_CLASS_COS_CHUNK
typedef struct log_tran_update_stats LOG_TRAN_UPDATE_STATS
typedef struct log_rcv_tdes LOG_RCV_TDES
typedef struct log_tdes LOG_TDES
typedef struct log_addr_tdesarea LOG_ADDR_TDESAREA
typedef struct trantable TRANTABLE
typedef enum log_recvphase LOG_RECVPHASE
typedef struct global_unique_stats GLOBAL_UNIQUE_STATS
typedef struct global_unique_stats_table GLOBAL_UNIQUE_STATS_TABLE
typedef struct log_global LOG_GLOBAL
typedef struct log_logging_stat LOG_LOGGING_STAT
typedef enum log_cs_access_mode LOG_CS_ACCESS_MODE
Enumerations
enum log_flush { LOG_DONT_NEED_FLUSH, LOG_NEED_FLUSH }
enum log_setdirty { LOG_DONT_SET_DIRTY, LOG_SET_DIRTY }
enum log_getnewtrid { LOG_DONT_NEED_NEWTRID, LOG_NEED_NEWTRID }
enum log_wrote_eot_log { LOG_NEED_TO_WRITE_EOT_LOG, LOG_ALREADY_WROTE_EOT_LOG }
enum log_topops_type { LOG_TOPOPS_NORMAL, LOG_TOPOPS_COMPENSATE_TRAN_ABORT, LOG_TOPOPS_COMPENSATE_SYSOP_ABORT, LOG_TOPOPS_POSTPONE }
enum tran_abort_reason { TRAN_NORMAL = 0, TRAN_ABORT_DUE_DEADLOCK = 1, TRAN_ABORT_DUE_ROLLBACK_ON_ESCALATION = 2 }
enum count_optim_state { COS_NOT_LOADED = 0, COS_TO_LOAD = 1, COS_LOADED = 2 }
enum log_recvphase {
LOG_RESTARTED, LOG_RECOVERY_ANALYSIS_PHASE, LOG_RECOVERY_REDO_PHASE, LOG_RECOVERY_UNDO_PHASE,
LOG_RECOVERY_FINISH_2PC_PHASE
}
enum log_cs_access_mode { LOG_CS_FORCE_USE, LOG_CS_SAFE_READER }
Functions
int logpb_initialize_pool (THREAD_ENTRY *thread_p)
void logpb_finalize_pool (THREAD_ENTRY *thread_p)
bool logpb_is_pool_initialized (void)
void logpb_invalidate_pool (THREAD_ENTRY *thread_p)
LOG_PAGE * logpb_create_page (THREAD_ENTRY *thread_p, LOG_PAGEID pageid)
LOG_PAGE * log_pbfetch (LOG_PAGEID pageid)
void logpb_set_dirty (THREAD_ENTRY *thread_p, LOG_PAGE *log_pgptr)
int logpb_flush_page (THREAD_ENTRY *thread_p, LOG_PAGE *log_pgptr)
LOG_PAGEID logpb_get_page_id (LOG_PAGE *log_pgptr)
int logpb_initialize_header (THREAD_ENTRY *thread_p, LOG_HEADER *loghdr, const char *prefix_logname, DKNPAGES npages, INT64 *db_creation)
LOG_PAGE * logpb_create_header_page (THREAD_ENTRY *thread_p)
void logpb_fetch_header (THREAD_ENTRY *thread_p, LOG_HEADER *hdr)
void logpb_fetch_header_with_buffer (THREAD_ENTRY *thread_p, LOG_HEADER *hdr, LOG_PAGE *log_pgptr)
void logpb_flush_header (THREAD_ENTRY *thread_p)
int logpb_fetch_page (THREAD_ENTRY *thread_p, const LOG_LSA *req_lsa, LOG_CS_ACCESS_MODE access_mode, LOG_PAGE *log_pgptr)
int logpb_copy_page_from_log_buffer (THREAD_ENTRY *thread_p, LOG_PAGEID pageid, LOG_PAGE *log_pgptr)
int logpb_copy_page_from_file (THREAD_ENTRY *thread_p, LOG_PAGEID pageid, LOG_PAGE *log_pgptr)
int logpb_read_page_from_file (THREAD_ENTRY *thread_p, LOG_PAGEID pageid, LOG_CS_ACCESS_MODE access_mode, LOG_PAGE *log_pgptr)
int logpb_read_page_from_active_log (THREAD_ENTRY *thread_p, LOG_PAGEID pageid, int num_pages, bool decrypt_needed, LOG_PAGE *log_pgptr)
int logpb_write_page_to_disk (THREAD_ENTRY *thread_p, LOG_PAGE *log_pgptr, LOG_PAGEID logical_pageid)
PGLENGTH logpb_find_header_parameters (THREAD_ENTRY *thread_p, const bool force_read_log_header, const char *db_fullname, const char *logpath, const char *prefix_logname, PGLENGTH *io_page_size, PGLENGTH *log_page_size, INT64 *db_creation, float *db_compatibility, int *db_charset)
int logpb_fetch_start_append_page (THREAD_ENTRY *thread_p)
LOG_PAGE * logpb_fetch_start_append_page_new (THREAD_ENTRY *thread_p)
void logpb_flush_pages_direct (THREAD_ENTRY *thread_p)
void logpb_flush_pages (THREAD_ENTRY *thread_p, LOG_LSA *flush_lsa)
void logpb_force_flush_pages (THREAD_ENTRY *thread_p)
void logpb_force_flush_header_and_pages (THREAD_ENTRY *thread_p)
void logpb_invalid_all_append_pages (THREAD_ENTRY *thread_p)
void logpb_flush_log_for_wal (THREAD_ENTRY *thread_p, const LOG_LSA *lsa_ptr)
void logpb_create_log_info (const char *logname_info, const char *db_fullname)
bool logpb_find_volume_info_exist (void)
int logpb_create_volume_info (const char *db_fullname)
int logpb_recreate_volume_info (THREAD_ENTRY *thread_p)
VOLID logpb_add_volume (const char *db_fullname, VOLID new_volid, const char *new_volfullname, DISK_VOLPURPOSE new_volpurpose)
int logpb_scan_volume_info (THREAD_ENTRY *thread_p, const char *db_fullname, VOLID ignore_volid, VOLID start_volid, int(*fun)(THREAD_ENTRY *thread_p, VOLID xvolid, const char *vlabel, void *args), void *args)
LOG_PHY_PAGEID logpb_to_physical_pageid (LOG_PAGEID logical_pageid)
bool logpb_is_page_in_archive (LOG_PAGEID pageid)
bool logpb_is_smallest_lsa_in_archive (THREAD_ENTRY *thread_p)
int logpb_get_archive_number (THREAD_ENTRY *thread_p, LOG_PAGEID pageid)
void logpb_decache_archive_info (THREAD_ENTRY *thread_p)
LOG_PAGE * logpb_fetch_from_archive (THREAD_ENTRY *thread_p, LOG_PAGEID pageid, LOG_PAGE *log_pgptr, int *ret_arv_num, LOG_ARV_HEADER *arv_hdr, bool is_fatal)
void logpb_remove_archive_logs (THREAD_ENTRY *thread_p, const char *info_reason)
int logpb_remove_archive_logs_exceed_limit (THREAD_ENTRY *thread_p, int max_count)
void logpb_copy_from_log (THREAD_ENTRY *thread_p, char *area, int length, LOG_LSA *log_lsa, LOG_PAGE *log_pgptr)
int logpb_initialize_log_names (THREAD_ENTRY *thread_p, const char *db_fullname, const char *logpath, const char *prefix_logname)
bool logpb_exist_log (THREAD_ENTRY *thread_p, const char *db_fullname, const char *logpath, const char *prefix_logname)
LOG_PAGEID logpb_checkpoint (THREAD_ENTRY *thread_p)
void logpb_dump_checkpoint_trans (FILE *out_fp, int length, void *data)
int logpb_backup (THREAD_ENTRY *thread_p, int num_perm_vols, const char *allbackup_path, FILEIO_BACKUP_LEVEL backup_level, bool delete_unneeded_logarchives, const char *backup_verbose_file_path, int num_threads, FILEIO_ZIP_METHOD zip_method, FILEIO_ZIP_LEVEL zip_level, int skip_activelog, int sleep_msecs, bool separate_keys)
int logpb_restore (THREAD_ENTRY *thread_p, const char *db_fullname, const char *logpath, const char *prefix_logname, bo_restart_arg *r_args)
int logpb_copy_database (THREAD_ENTRY *thread_p, VOLID num_perm_vols, const char *to_db_fullname, const char *to_logpath, const char *to_prefix_logname, const char *toext_path, const char *fileof_vols_and_copypaths)
int logpb_rename_all_volumes_files (THREAD_ENTRY *thread_p, VOLID num_perm_vols, const char *to_db_fullname, const char *to_logpath, const char *to_prefix_logname, const char *toext_path, const char *fileof_vols_and_renamepaths, bool extern_rename, bool force_delete)
int logpb_delete (THREAD_ENTRY *thread_p, VOLID num_perm_vols, const char *db_fullname, const char *logpath, const char *prefix_logname, bool force_delete)
int logpb_check_exist_any_volumes (THREAD_ENTRY *thread_p, const char *db_fullname, const char *logpath, const char *prefix_logname, char *first_vol, bool *is_exist)
void logpb_fatal_error (THREAD_ENTRY *thread_p, bool logexit, const char *file_name, const int lineno, const char *fmt,...)
void logpb_fatal_error_exit_immediately_wo_flush (THREAD_ENTRY *thread_p, const char *file_name, const int lineno, const char *fmt,...)
int logpb_check_and_reset_temp_lsa (THREAD_ENTRY *thread_p, VOLID volid)
void logpb_initialize_arv_page_info_table (void)
void logpb_initialize_logging_statistics (void)
int logpb_background_archiving (THREAD_ENTRY *thread_p)
void xlogpb_dump_stat (FILE *outfp)
void logpb_dump (THREAD_ENTRY *thread_p, FILE *out_fp)
int logpb_remove_all_in_log_path (THREAD_ENTRY *thread_p, const char *db_fullname, const char *logpath, const char *prefix_logname)
TDE_ALGORITHM logpb_get_tde_algorithm (const LOG_PAGE *log_pgptr)
void logpb_set_tde_algorithm (THREAD_ENTRY *thread_p, LOG_PAGE *log_pgptr, const TDE_ALGORITHM tde_algo)
void log_recovery (THREAD_ENTRY *thread_p, int ismedia_crash, time_t *stopat)
LOG_LSA * log_startof_nxrec (THREAD_ENTRY *thread_p, LOG_LSA *lsa, bool canuse_forwaddr)
void * logtb_realloc_topops_stack (LOG_TDES *tdes, int num_elms)
void logtb_define_trantable (THREAD_ENTRY *thread_p, int num_expected_tran_indices, int num_expected_locks)
int logtb_define_trantable_log_latch (THREAD_ENTRY *thread_p, int num_expected_tran_indices)
void logtb_undefine_trantable (THREAD_ENTRY *thread_p)
int logtb_get_number_assigned_tran_indices (void)
int logtb_get_number_of_total_tran_indices (void)
bool logtb_am_i_dba_client (THREAD_ENTRY *thread_p)
int logtb_assign_tran_index (THREAD_ENTRY *thread_p, TRANID trid, TRAN_STATE state, const BOOT_CLIENT_CREDENTIAL *client_credential, TRAN_STATE *current_state, int wait_msecs, TRAN_ISOLATION isolation)
LOG_TDES * logtb_rv_find_allocate_tran_index (THREAD_ENTRY *thread_p, TRANID trid, const LOG_LSA *log_lsa)
void logtb_rv_assign_mvccid_for_undo_recovery (THREAD_ENTRY *thread_p, MVCCID mvccid)
void logtb_release_tran_index (THREAD_ENTRY *thread_p, int tran_index)
void logtb_free_tran_index (THREAD_ENTRY *thread_p, int tran_index)
void logtb_free_tran_index_with_undo_lsa (THREAD_ENTRY *thread_p, const LOG_LSA *undo_lsa)
void logtb_initialize_tdes (LOG_TDES *tdes, int tran_index)
void logtb_clear_tdes (THREAD_ENTRY *thread_p, LOG_TDES *tdes)
void logtb_finalize_tdes (THREAD_ENTRY *thread_p, LOG_TDES *tdes)
int logtb_get_new_tran_id (THREAD_ENTRY *thread_p, LOG_TDES *tdes)
int logtb_find_tran_index (THREAD_ENTRY *thread_p, TRANID trid)
TRANID logtb_find_tranid (int tran_index)
TRANID logtb_find_current_tranid (THREAD_ENTRY *thread_p)
int logtb_count_clients (THREAD_ENTRY *thread_p)
int logtb_count_not_allowed_clients_in_maintenance_mode (THREAD_ENTRY *thread_p)
int logtb_find_client_type (int tran_index)
const char * logtb_find_client_name (int tran_index)
void logtb_set_user_name (int tran_index, const char *client_name)
void logtb_set_current_user_name (THREAD_ENTRY *thread_p, const char *client_name)
const char * logtb_find_client_hostname (int tran_index)
void logtb_set_current_user_active (THREAD_ENTRY *thread_p, bool is_user_active)
int logtb_find_client_name_host_pid (int tran_index, const char **client_prog_name, const char **client_user_name, const char **client_host_name, int *client_pid)
void logpb_debug_check_log_page (THREAD_ENTRY *thread_p, void *log_pgptr_ptr)
int logtb_get_client_ids (int tran_index, CLIENTIDS *client_info)
int logtb_find_current_client_type (THREAD_ENTRY *thread_p)
const char * logtb_find_current_client_name (THREAD_ENTRY *thread_p)
const char * logtb_find_current_client_hostname (THREAD_ENTRY *thread_p)
LOG_LSA * logtb_find_current_tran_lsa (THREAD_ENTRY *thread_p)
TRAN_STATE logtb_find_state (int tran_index)
int logtb_find_wait_msecs (int tran_index)
int logtb_find_interrupt (int tran_index, bool *interrupt)
TRAN_ISOLATION logtb_find_isolation (int tran_index)
TRAN_ISOLATION logtb_find_current_isolation (THREAD_ENTRY *thread_p)
bool logtb_set_tran_index_interrupt (THREAD_ENTRY *thread_p, int tran_index, bool set)
bool logtb_set_suppress_repl_on_transaction (THREAD_ENTRY *thread_p, int tran_index, int set)
bool logtb_is_interrupted (THREAD_ENTRY *thread_p, bool clear, bool *continue_checking)
bool logtb_is_interrupted_tran (THREAD_ENTRY *thread_p, bool clear, bool *continue_checking, int tran_index)
bool logtb_is_active (THREAD_ENTRY *thread_p, TRANID trid)
bool logtb_is_current_active (THREAD_ENTRY *thread_p)
bool logtb_istran_finished (THREAD_ENTRY *thread_p, TRANID trid)
void logtb_disable_update (THREAD_ENTRY *thread_p)
void logtb_enable_update (THREAD_ENTRY *thread_p)
void logtb_set_to_system_tran_index (THREAD_ENTRY *thread_p)
int logtb_set_num_loose_end_trans (THREAD_ENTRY *thread_p)
void log_find_unilaterally_largest_undo_lsa (THREAD_ENTRY *thread_p, LOG_LSA &max_undo_lsa)
void logtb_find_smallest_lsa (THREAD_ENTRY *thread_p, LOG_LSA *lsa)
void logtb_find_smallest_and_largest_active_pages (THREAD_ENTRY *thread_p, LOG_PAGEID *smallest, LOG_PAGEID *largest)
int logtb_is_tran_modification_disabled (THREAD_ENTRY *thread_p)
bool logtb_has_deadlock_priority (int tran_index)
void xlogtb_dump_trantable (THREAD_ENTRY *thread_p, FILE *out_fp)
bool logpb_need_wal (const LOG_LSA *lsa)
char * logpb_backup_level_info_to_string (char *buf, int buf_size, const LOG_HDR_BKUP_LEVEL_INFO *info)
const char * tran_abort_reason_to_string (TRAN_ABORT_REASON val)
int logtb_descriptors_start_scan (THREAD_ENTRY *thread_p, int type, DB_VALUE **arg_values, int arg_cnt, void **ctx)
LOG_PAGEID logpb_find_oldest_available_page_id (THREAD_ENTRY *thread_p)
int logpb_find_oldest_available_arv_num (THREAD_ENTRY *thread_p)
void logtb_get_new_subtransaction_mvccid (THREAD_ENTRY *thread_p, MVCC_INFO *curr_mvcc_info)
MVCCID logtb_find_current_mvccid (THREAD_ENTRY *thread_p)
MVCCID logtb_get_current_mvccid (THREAD_ENTRY *thread_p)
int logtb_invalidate_snapshot_data (THREAD_ENTRY *thread_p)
int xlogtb_get_mvcc_snapshot (THREAD_ENTRY *thread_p)
bool logtb_is_current_mvccid (THREAD_ENTRY *thread_p, MVCCID mvccid)
bool logtb_is_mvccid_committed (THREAD_ENTRY *thread_p, MVCCID mvccid)
MVCC_SNAPSHOT * logtb_get_mvcc_snapshot (THREAD_ENTRY *thread_p)
void logtb_complete_mvcc (THREAD_ENTRY *thread_p, LOG_TDES *tdes, bool committed)
void logtb_complete_sub_mvcc (THREAD_ENTRY *thread_p, LOG_TDES *tdes)
LOG_TRAN_CLASS_COS * logtb_tran_find_class_cos (THREAD_ENTRY *thread_p, const OID *class_oid, bool create)
int logtb_tran_update_unique_stats (THREAD_ENTRY *thread_p, const BTID *btid, int n_keys, int n_oids, int n_nulls, bool write_to_log)
int logtb_tran_update_unique_stats (THREAD_ENTRY *thread_p, const BTID &btid, const btree_unique_stats &ustats, bool write_to_log)
int logtb_tran_update_unique_stats (THREAD_ENTRY *thread_p, const multi_index_unique_stats &multi_stats, bool write_to_log)
int logtb_tran_update_btid_unique_stats (THREAD_ENTRY *thread_p, const BTID *btid, int n_keys, int n_oids, int n_nulls)
LOG_TRAN_BTID_UNIQUE_STATS * logtb_tran_find_btid_stats (THREAD_ENTRY *thread_p, const BTID *btid, bool create)
int logtb_tran_prepare_count_optim_classes (THREAD_ENTRY *thread_p, const char **classes, LC_PREFETCH_FLAGS *flags, int n_classes)
void logtb_tran_reset_count_optim_state (THREAD_ENTRY *thread_p)
int logtb_find_log_records_count (int tran_index)
int logtb_initialize_global_unique_stats_table (THREAD_ENTRY *thread_p)
void logtb_finalize_global_unique_stats_table (THREAD_ENTRY *thread_p)
int logtb_get_global_unique_stats (THREAD_ENTRY *thread_p, BTID *btid, int *num_oids, int *num_nulls, int *num_keys)
int logtb_rv_update_global_unique_stats_by_abs (THREAD_ENTRY *thread_p, BTID *btid, int num_oids, int num_nulls, int num_keys)
int logtb_update_global_unique_stats_by_delta (THREAD_ENTRY *thread_p, BTID *btid, int oid_delta, int null_delta, int key_delta, bool log)
int logtb_delete_global_unique_stats (THREAD_ENTRY *thread_p, BTID *btid)
int logtb_reflect_global_unique_stats_to_btree (THREAD_ENTRY *thread_p)
int logtb_tran_update_all_global_unique_stats (THREAD_ENTRY *thread_p)
int log_rv_undoredo_record_partial_changes (THREAD_ENTRY *thread_p, char *rcv_data, int rcv_data_length, RECDES *record, bool is_undo)
int log_rv_redo_record_modify (THREAD_ENTRY *thread_p, LOG_RCV *rcv)
int log_rv_undo_record_modify (THREAD_ENTRY *thread_p, LOG_RCV *rcv)
char * log_rv_pack_redo_record_changes (char *ptr, int offset_to_data, int old_data_size, int new_data_size, char *new_data)
char * log_rv_pack_undo_record_changes (char *ptr, int offset_to_data, int old_data_size, int new_data_size, char *old_data)
void log_set_ha_promotion_time (THREAD_ENTRY *thread_p, INT64 ha_promotion_time)
void log_set_db_restore_time (THREAD_ENTRY *thread_p, INT64 db_restore_time)
int logpb_prior_lsa_append_all_list (THREAD_ENTRY *thread_p)
bool logtb_check_class_for_rr_isolation_err (const OID *class_oid)
void logpb_vacuum_reset_log_header_cache (THREAD_ENTRY *thread_p, LOG_HEADER *loghdr)
VACUUM_LOG_BLOCKID logpb_last_complete_blockid (void)
int logpb_page_check_corruption (THREAD_ENTRY *thread_p, LOG_PAGE *log_pgptr, bool *is_page_corrupted)
void logpb_dump_log_page_area (THREAD_ENTRY *thread_p, LOG_PAGE *log_pgptr, int offset, int length)
void logpb_page_get_first_null_block_lsa (THREAD_ENTRY *thread_p, LOG_PAGE *log_pgptr, LOG_LSA *first_null_block_lsa)
void logtb_slam_transaction (THREAD_ENTRY *thread_p, int tran_index)
int xlogtb_kill_tran_index (THREAD_ENTRY *thread_p, int kill_tran_index, char *kill_user, char *kill_host, int kill_pid)
int xlogtb_kill_or_interrupt_tran (THREAD_ENTRY *thread_p, int tran_id, bool is_dba_group_member, bool interrupt_only)
THREAD_ENTRY * logtb_find_thread_by_tran_index (int tran_index)
THREAD_ENTRY * logtb_find_thread_by_tran_index_except_me (int tran_index)
int logtb_get_current_tran_index (void)
void logtb_set_current_tran_index (THREAD_ENTRY *thread_p, int tran_index)
bool logtb_set_check_interrupt (THREAD_ENTRY *thread_p, bool flag)
bool logtb_get_check_interrupt (THREAD_ENTRY *thread_p)
int logpb_set_page_checksum (THREAD_ENTRY *thread_p, LOG_PAGE *log_pgptr)
LOG_TDES * logtb_get_system_tdes (THREAD_ENTRY *thread_p=NULL)
LOG_TDES * LOG_FIND_TDES (int tran_index)
LOG_TDES * LOG_FIND_CURRENT_TDES (THREAD_ENTRY *thread_p=NULL)
bool logtb_is_system_worker_tranid (TRANID trid)
Variables
const TRANID LOG_SYSTEM_WORKER_FIRST_TRANID = NULL_TRANID - 1
const int LOG_SYSTEM_WORKER_INCR_TRANID = -1
int db_Disable_modifications
int log_Tran_index
LOG_GLOBAL log_Gl
LOG_LOGGING_STAT log_Stat
char log_Path []
char log_Archive_path []
char log_Prefix []
const char * log_Db_fullname
char log_Name_active []
char log_Name_info []
char log_Name_bkupinfo []
char log_Name_volinfo []
char log_Name_bg_archive []
char log_Name_removed_archive []
Macro Definition Documentation
#define _DB_DISABLE_MODIFICATIONS_
Definition at line 244 of file log_impl.h.
#define CHECK_MODIFICATION_NO_RETURN (thread_p, error)
Value:
do \
    { \
      int mod_disabled; \
      mod_disabled = logtb_is_tran_modification_disabled (thread_p); \
      if (mod_disabled) \
        { \
          er_set (ER_ERROR_SEVERITY, ARG_FILE_LINE, ER_DB_NO_MODIFICATIONS, \
                  0); \
          er_log_debug (ARG_FILE_LINE, "tdes->disable_modification = %d\n", \
                        mod_disabled); \
          error = ER_DB_NO_MODIFICATIONS; \
        } \
      else \
        { \
          error = NO_ERROR; \
        } \
    } \
  while (0)
Definition at line 253 of file log_impl.h.
#define COS_CLASSES_CHUNK_SIZE 64 /* size of the memory chunk for count optimization classes */
Definition at line 410 of file log_impl.h.
Referenced by logtb_tran_create_class_cos().
#define GLOBAL_UNIQUE_STATS_HASH_SIZE 1000
Definition at line 644 of file log_impl.h.
Referenced by logtb_initialize_global_unique_stats_table().
#define GLOBAL_UNIQUE_STATS_TABLE_INITIALIZER { LF_HASH_TABLE_INITIALIZER, LF_ENTRY_DESCRIPTOR_INITIALIZER, LF_FREELIST_INITIALIZER, LSA_INITIALIZER, false }
Definition at line 641 of file log_impl.h.
#define LOG_ARCHIVE_CS_ENTER (thread_p)
Definition at line 92 of file log_impl.h.
Referenced by logpb_archive_active_log(), logpb_decache_archive_info(), logpb_dismount_log_archive(), logpb_fetch_from_archive(), and logpb_find_oldest_available_page_id().
#define LOG_ARCHIVE_CS_ENTER_READ_MODE (thread_p)
Definition at line 93 of file log_impl.h.
#define LOG_ARCHIVE_CS_EXIT (thread_p)
Definition at line 94 of file log_impl.h.
Referenced by logpb_archive_active_log(), logpb_decache_archive_info(), logpb_dismount_log_archive(), logpb_fetch_from_archive(), and logpb_find_oldest_available_page_id().
#define LOG_ARCHIVE_CS_OWN (thread_p) (true)
Definition at line 107 of file log_impl.h.
#define LOG_ARCHIVE_CS_OWN_READ_MODE (thread_p) (true)
Definition at line 109 of file log_impl.h.
#define LOG_ARCHIVE_CS_OWN_WRITE_MODE (thread_p) (true)
Definition at line 108 of file log_impl.h.
Referenced by logpb_is_archive_available(), and logpb_set_unavailable_archive().
#define LOG_CHECK_LOG_APPLIER (thread_p) (0)
Definition at line 240 of file log_impl.h.
Referenced by btree_prepare_bts(), locator_add_or_remove_index_internal(), locator_check_foreign_key(), locator_check_primary_key_delete(), locator_check_primary_key_update(), locator_update_force(), locator_update_index(), log_append_redo_crumbs(), log_append_undoredo_crumbs(), log_commit_local(), log_complete_for_2pc(), log_sysop_abort(), log_sysop_commit_internal(), qexec_execute_selupd_list(), serial_update_serial_object(), srepl_set_info(), xlocator_force(), and xrepl_set_info().
#define LOG_ESTIMATE_NACTIVE_TRANS 100 /* Estimate num of trans */
Definition at line 112 of file log_impl.h.
Referenced by logpb_initialize_header(), and logtb_define_trantable_log_latch().
#define LOG_ESTIMATE_NOBJ_LOCKS 977 /* Estimate num of locks */
Definition at line 113 of file log_impl.h.
Referenced by logpb_initialize_header().
#define LOG_FIND_THREAD_TRAN_INDEX (thrd) (log_Tran_index)
Definition at line 176 of file log_impl.h.
Referenced by LOG_FIND_CURRENT_TDES().
#define LOG_GROUP_COMMIT_INFO_INITIALIZER { PTHREAD_MUTEX_INITIALIZER, PTHREAD_COND_INITIALIZER }
Definition at line 323 of file log_impl.h.
#define LOG_HAS_LOGGING_BEEN_IGNORED () (log_Gl.hdr.has_logging_been_skipped == true)
Definition at line 229 of file log_impl.h.
Referenced by log_abort(), log_abort_partial(), log_commit(), and log_recovery().
#define LOG_IS_GROUP_COMMIT_ACTIVE () (prm_get_integer_value (PRM_ID_LOG_GROUP_COMMIT_INTERVAL_MSECS) > 0)
Definition at line 119 of file log_impl.h.
Referenced by logpb_flush_pages().
#define LOG_ISRESTARTED () (log_Gl.rcv_phase == LOG_RESTARTED)
Definition at line 232 of file log_impl.h.
Referenced by btree_fix_root_for_delete(), btree_split_node_and_advance(), disk_rv_undo_format(), disk_stab_cursor_check_valid(), disk_stab_init(), file_get_sticky_first_page(), fileio_expand_to(), log_commit(), log_complete_for_2pc(), log_get_restart_lsa(), log_is_in_crash_recovery(), log_is_logged_since_restart(), log_rollback(), log_system_tdes::log_system_tdes(), logpb_read_page_from_file(), logtb_free_tran_index(), logtb_get_system_tdes(), logtb_is_active(), pgbuf_is_temporary_volume(), prior_lsa_next_record_internal(), systdes_claim_tdes(), vacuum_add_dropped_file(), vacuum_cleanup_dropped_files(), vacuum_notify_all_workers_dropped_file(), xlog_dump(), and log_system_tdes::~log_system_tdes().
#define LOG_ISTRAN_2PC (tdes)
Value:
((tdes)->state == TRAN_UNACTIVE_2PC_COLLECTING_PARTICIPANT_VOTES \
   || (tdes)->state == TRAN_UNACTIVE_2PC_PREPARE \
   || LOG_ISTRAN_2PC_IN_SECOND_PHASE (tdes))
Definition at line 212 of file log_impl.h.
Referenced by log_2pc_attach_global_tran(), log_2pc_recovery(), log_2pc_recovery_analysis_info(), log_2pc_set_global_tran_info(), log_recovery_analysis(), log_recovery_redo(), and log_rv_analysis_end_checkpoint().
#define LOG_ISTRAN_2PC_IN_SECOND_PHASE (tdes)
Value:
((tdes)->state == TRAN_UNACTIVE_2PC_ABORT_DECISION \
   || (tdes)->state == TRAN_UNACTIVE_2PC_COMMIT_DECISION \
   || (tdes)->state == TRAN_UNACTIVE_WILL_COMMIT \
   || (tdes)->state == TRAN_UNACTIVE_COMMITTED_WITH_POSTPONE \
   || (tdes)->state == TRAN_UNACTIVE_ABORTED_INFORMING_PARTICIPANTS \
   || (tdes)->state == TRAN_UNACTIVE_COMMITTED_INFORMING_PARTICIPANTS)
Definition at line 204 of file log_impl.h.
Referenced by log_2pc_recovery_analysis_record(), and logtb_set_loose_end_tdes().
#define LOG_ISTRAN_2PC_INFORMING_PARTICIPANTS (tdes)
Value:
((tdes)->state == TRAN_UNACTIVE_COMMITTED_INFORMING_PARTICIPANTS \
   || (tdes)->state == TRAN_UNACTIVE_ABORTED_INFORMING_PARTICIPANTS)
Definition at line 220 of file log_impl.h.
Referenced by logtb_release_tran_index().
#define LOG_ISTRAN_2PC_PREPARE (tdes) ((tdes)->state == TRAN_UNACTIVE_2PC_PREPARE)
Definition at line 217 of file log_impl.h.
Referenced by log_2pc_find_tran_descriptor(), log_2pc_recovery_prepared(), log_abort(), log_commit(), logtb_release_tran_index(), and logtb_set_loose_end_tdes().
#define LOG_ISTRAN_ABORTED (tdes)
Value:
((tdes)->state == TRAN_UNACTIVE_ABORTED \
   || (tdes)->state == TRAN_UNACTIVE_UNILATERALLY_ABORTED \
   || (tdes)->state == TRAN_UNACTIVE_2PC_ABORT_DECISION \
   || (tdes)->state == TRAN_UNACTIVE_ABORTED_INFORMING_PARTICIPANTS)
Definition at line 192 of file log_impl.h.
Referenced by btree_check_locking_for_delete_unique(), log_append_dboutside_redo(), log_append_postpone(), log_append_redo_crumbs(), log_append_undo_crumbs(), log_append_undoredo_crumbs(), and logtb_tran_update_stats_online_index_rb().
#define LOG_ISTRAN_ACTIVE (tdes) ((tdes)->state == TRAN_ACTIVE && LOG_ISRESTARTED ())
Definition at line 182 of file log_impl.h.
Referenced by log_2pc_prepare_global_tran(), log_2pc_start(), log_abort(), log_abort_all_active_transaction(), log_abort_partial(), log_append_dboutside_redo(), log_append_postpone(), log_append_redo_crumbs(), log_append_savepoint(), log_append_undo_crumbs(), log_append_undoredo_crumbs(), log_commit(), log_final(), log_sysop_attach_to_outer(), logtb_is_active(), logtb_is_current_active(), logtb_is_interrupted_tdes(), and xboot_unregister_client().
#define LOG_ISTRAN_COMMITTED (tdes)
Value:
((tdes)->state == TRAN_UNACTIVE_COMMITTED \
   || (tdes)->state == TRAN_UNACTIVE_WILL_COMMIT \
   || (tdes)->state == TRAN_UNACTIVE_COMMITTED_WITH_POSTPONE \
   || (tdes)->state == TRAN_UNACTIVE_2PC_COMMIT_DECISION \
   || (tdes)->state == TRAN_UNACTIVE_COMMITTED_INFORMING_PARTICIPANTS)
Definition at line 185 of file log_impl.h.
Referenced by logtb_set_loose_end_tdes().
#define LOG_ISTRAN_LOOSE_ENDS (tdes)
Value:
((tdes)->state == TRAN_UNACTIVE_COMMITTED_INFORMING_PARTICIPANTS \
   || (tdes)->state == TRAN_UNACTIVE_ABORTED_INFORMING_PARTICIPANTS \
   || (tdes)->state == TRAN_UNACTIVE_2PC_COLLECTING_PARTICIPANT_VOTES \
   || (tdes)->state == TRAN_UNACTIVE_2PC_PREPARE)
Definition at line 198 of file log_impl.h.
#define LOG_READ_ADD_ALIGN (thread_p, add, lsa, log_pgptr)
Value:
do \
    { \
      (lsa)->offset += (add); \
      LOG_READ_ALIGN ((thread_p), (lsa), (log_pgptr)); \
    } \
  while (0)
Definition at line 141 of file log_impl.h.
Referenced by log_2pc_read_prepare(), log_2pc_recovery_prepare(), log_2pc_recovery_recv_ack(), log_2pc_recovery_start(), log_dump_record_2pc_prepare_commit(), log_dump_record_2pc_start(), log_dump_record_checkpoint(), log_dump_record_compensate(), log_dump_record_dbout_redo(), log_dump_record_mvcc_redo(), log_dump_record_mvcc_undo(), log_dump_record_mvcc_undoredo(), log_dump_record_postpone(), log_dump_record_redo(), log_dump_record_replication(), log_dump_record_save_point(), log_dump_record_sysop_end_internal(), log_dump_record_undo(), log_dump_record_undoredo(), log_get_next_nested_top(), log_get_savepoint_lsa(), log_get_undo_record(), log_read_sysop_start_postpone(), log_recovery_abort_interrupted_sysop(), log_recovery_analysis(), log_recovery_find_first_postpone(), log_recovery_redo(), log_recovery_undo(), log_rollback(), log_run_postpone_op(), log_rv_analysis_commit_with_postpone(), log_rv_analysis_compensate(), log_rv_analysis_complete(), log_rv_analysis_end_checkpoint(), log_rv_analysis_run_postpone(), log_rv_analysis_sysop_end(), log_rv_analysis_sysop_start_postpone(), log_startof_nxrec(), vacuum_recover_lost_block_data(), and xlog_dump().
#define LOG_READ_ADVANCE_WHEN_DOESNT_FIT (thread_p, length, lsa, log_pgptr)
Value:
do \
    { \
      if ((lsa)->offset + (int) (length) >= (int) LOGAREA_SIZE) \
        { \
          assert (log_pgptr != NULL); \
          (lsa)->pageid++; \
          if ((logpb_fetch_page ((thread_p), (lsa), LOG_CS_FORCE_USE, log_pgptr))!= NO_ERROR) \
            { \
              logpb_fatal_error ((thread_p), true, ARG_FILE_LINE, \
                                 "LOG_READ_ADVANCE_WHEN_DOESNT_FIT"); \
            } \
          (lsa)->offset = 0; \
        } \
    } \
  while (0)
Definition at line 149 of file log_impl.h.
Referenced by log_2pc_read_prepare(), log_2pc_recovery_recv_ack(), log_2pc_recovery_start(), log_dump_record_2pc_acknowledgement(), log_dump_record_2pc_prepare_commit(), log_dump_record_2pc_start(), log_dump_record_checkpoint(), log_dump_record_commit_postpone(), log_dump_record_compensate(), log_dump_record_dbout_redo(), log_dump_record_ha_server_state(), log_dump_record_mvcc_redo(), log_dump_record_mvcc_undo(), log_dump_record_mvcc_undoredo(), log_dump_record_postpone(), log_dump_record_redo(), log_dump_record_replication(), log_dump_record_save_point(), log_dump_record_sysop_end(), log_dump_record_sysop_start_postpone(), log_dump_record_transaction_finish(), log_dump_record_undo(), log_dump_record_undoredo(), log_get_next_nested_top(), log_get_savepoint_lsa(), log_get_undo_record(), log_read_sysop_start_postpone(), log_recovery_abort_interrupted_sysop(), log_recovery_analysis(), log_recovery_find_first_postpone(), log_recovery_redo(), log_recovery_undo(), log_rollback(), log_run_postpone_op(), log_rv_analysis_commit_with_postpone(), log_rv_analysis_compensate(), log_rv_analysis_complete(), log_rv_analysis_end_checkpoint(), log_rv_analysis_run_postpone(), log_rv_analysis_sysop_end(), log_rv_analysis_sysop_start_postpone(), log_startof_nxrec(), logpb_copy_from_log(), and vacuum_recover_lost_block_data().
#define LOG_READ_ALIGN (thread_p, lsa, log_pgptr)
Value:
do \
    { \
      (lsa)->offset = DB_ALIGN ((lsa)->offset, DOUBLE_ALIGNMENT); \
      while ((lsa)->offset >= (int) LOGAREA_SIZE) \
        { \
          assert (log_pgptr != NULL); \
          (lsa)->pageid++; \
          if (logpb_fetch_page ((thread_p), (lsa), LOG_CS_FORCE_USE, (log_pgptr)) != NO_ERROR) \
        { \
              logpb_fatal_error ((thread_p), true, ARG_FILE_LINE, \
                                 "LOG_READ_ALIGN"); \
        } \
          (lsa)->offset -= LOGAREA_SIZE; \
          (lsa)->offset = DB_ALIGN ((lsa)->offset, DOUBLE_ALIGNMENT); \
        } \
    } \
  while (0)
Definition at line 122 of file log_impl.h.
Referenced by log_2pc_read_prepare(), log_2pc_recovery_start(), log_dump_data(), log_recovery_redo(), and log_rv_get_unzip_log_data().
#define LOG_READ_NEXT_MVCCID (log_Gl.hdr.mvcc_next_id)
Definition at line 228 of file log_impl.h.
#define LOG_READ_NEXT_TRANID (log_Gl.hdr.next_trid)
Definition at line 227 of file log_impl.h.
Referenced by logpb_flush_all_append_pages().
#define LOG_SET_CURRENT_TRAN_INDEX (thrd, index) log_Tran_index = (index)
Definition at line 178 of file log_impl.h.
Referenced by log_2pc_attach_client(), log_2pc_recovery(), log_complete_for_2pc(), log_final(), log_initialize_internal(), log_recovery(), log_rv_end_simulation(), log_rv_outside_noop_redo(), log_rv_simulate_runtime_worker(), logtb_allocate_tran_index(), logtb_assign_tran_index(), logtb_define_trantable(), logtb_define_trantable_log_latch(), logtb_free_tran_index(), logtb_set_to_system_tran_index(), xboot_unregister_client(), and xtran_server_abort().
#define LOG_THREAD_TRAN_ARGS (thread_p) thread_get_current_entry_index (), LOG_FIND_CURRENT_TDES (thread_p)
Definition at line 797 of file log_impl.h.
#define LOG_THREAD_TRAN_MSG "(thr=%d, trid=%d)"
Definition at line 796 of file log_impl.h.
#define LOG_TRAN_INDEX
Definition at line 769 of file log_impl.h.
#define LOGAREA_SIZE (LOG_PAGESIZE - SSIZEOF(LOG_HDRPAGE))
Definition at line 116 of file log_impl.h.
Referenced by log_dump_data(), log_get_savepoint_lsa(), log_get_undo_record(), log_prior_lsa_append_advance_when_doesnot_fit(), log_prior_lsa_append_align(), LOG_PRIOR_LSA_LAST_APPEND_OFFSET(), log_read_sysop_start_postpone(), log_recovery_analysis(), log_recovery_redo(), log_recovery_undo(), log_rollback_record(), log_run_postpone_op(), log_rv_analysis_end_checkpoint(), log_rv_get_unzip_log_data(), log_rv_redo_record(), log_rv_undo_record(), logpb_copy_from_log(), logpb_dump_log_page_area(), logpb_dump_pages(), vacuum_copy_data_from_log(), vacuum_process_log_record(), vacuum_read_advance_when_doesnt_fit(), and vacuum_read_log_aligned().
#define MAX_NUM_EXEC_QUERY_HISTORY 100
Definition at line 275 of file log_impl.h.
Referenced by copy_bind_value_to_tdes(), event_log_many_ioreads(), event_log_slow_query(), event_log_temp_expand_pages(), lock_wait_state_to_string(), logtb_clear_tdes(), and logtb_initialize_tdes().
#define TR_TABLE_CS_ENTER (thread_p)
Definition at line 88 of file log_impl.h.
Referenced by css_change_ha_server_state(), log_2pc_attach_global_tran(), log_2pc_commit(), log_2pc_get_global_tran_info(), log_2pc_prepare_global_tran(), log_2pc_recovery_prepared(), log_2pc_send_abort_decision(), log_2pc_set_global_tran_info(), log_2pc_start(), log_complete_for_2pc(), logpb_checkpoint(), logtb_assign_tran_index(), logtb_clear_tdes(), logtb_define_trantable(), logtb_free_tran_index(), logtb_free_tran_index_with_undo_lsa(), logtb_get_new_tran_id(), logtb_is_interrupted_tdes(), logtb_release_tran_index(), logtb_set_num_loose_end_trans(), logtb_set_number_of_total_tran_indices(), and logtb_set_tran_index_interrupt().
#define TR_TABLE_CS_ENTER_READ_MODE (thread_p)
Definition at line 89 of file log_impl.h.
Referenced by log_find_unilaterally_largest_undo_lsa(), logtb_count_clients(), logtb_count_not_allowed_clients_in_maintenance_mode(), logtb_create_unique_stats_from_repr(), logtb_descriptors_start_scan(), logtb_find_current_tranid(), logtb_find_smallest_and_largest_active_pages(), logtb_find_smallest_lsa(), logtb_find_tran_index(), logtb_is_active(), logtb_istran_finished(), xlogtb_does_active_user_exist(), xlogtb_dump_trantable(), and xlogtb_get_pack_tran_table().
#define TR_TABLE_CS_EXIT (thread_p)
Definition at line 90 of file log_impl.h.
Referenced by css_change_ha_server_state(), log_2pc_attach_global_tran(), log_2pc_commit(), log_2pc_get_global_tran_info(), log_2pc_prepare_global_tran(), log_2pc_recovery_prepared(), log_2pc_send_abort_decision(), log_2pc_set_global_tran_info(), log_2pc_start(), log_complete_for_2pc(), log_find_unilaterally_largest_undo_lsa(), logpb_checkpoint(), logpb_checkpoint_topops(), logtb_assign_tran_index(), logtb_clear_tdes(), logtb_count_clients(), logtb_count_not_allowed_clients_in_maintenance_mode(), logtb_create_unique_stats_from_repr(), logtb_define_trantable(), logtb_descriptors_start_scan(), logtb_find_current_tranid(), logtb_find_smallest_and_largest_active_pages(), logtb_find_smallest_lsa(), logtb_find_tran_index(), logtb_free_tran_index(), logtb_free_tran_index_with_undo_lsa(), logtb_get_new_tran_id(), logtb_is_active(), logtb_is_interrupted_tdes(), logtb_istran_finished(), logtb_release_tran_index(), logtb_set_num_loose_end_trans(), logtb_set_number_of_total_tran_indices(), logtb_set_tran_index_interrupt(), xlogtb_does_active_user_exist(), xlogtb_dump_trantable(), and xlogtb_get_pack_tran_table().
#define TRAN_UNIQUE_STATS_CHUNK_SIZE 128 /* size of the memory chunk for unique statistics */
Definition at line 388 of file log_impl.h.
Referenced by logtb_tran_create_btid_unique_stats().
#define TRANTABLE_INITIALIZER { 0, 0, 0, 0, 0, 0, NULL, NULL }
Definition at line 598 of file log_impl.h.
Typedef Documentation
typedef enum count_optim_state COUNT_OPTIM_STATE
Definition at line 386 of file log_impl.h.
typedef struct global_unique_stats GLOBAL_UNIQUE_STATS
Definition at line 613 of file log_impl.h.
typedef struct global_unique_stats_table GLOBAL_UNIQUE_STATS_TABLE
Definition at line 628 of file log_impl.h.
typedef struct log_addr_tdesarea LOG_ADDR_TDESAREA
Definition at line 570 of file log_impl.h.
typedef enum log_cs_access_mode LOG_CS_ACCESS_MODE
Definition at line 765 of file log_impl.h.
typedef enum log_flush LOG_FLUSH
Definition at line 279 of file log_impl.h.
typedef struct log_flush_info LOG_FLUSH_INFO
Definition at line 297 of file log_impl.h.
typedef enum log_getnewtrid LOG_GETNEWTRID
Definition at line 287 of file log_impl.h.
typedef struct log_global LOG_GLOBAL
Definition at line 647 of file log_impl.h.
typedef struct log_group_commit_info LOG_GROUP_COMMIT_INFO
Definition at line 315 of file log_impl.h.
typedef struct log_logging_stat LOG_LOGGING_STAT
typedef struct log_rcv_tdes LOG_RCV_TDES
Definition at line 442 of file log_impl.h.
typedef enum log_recvphase LOG_RECVPHASE
Definition at line 610 of file log_impl.h.
typedef enum log_setdirty LOG_SETDIRTY
Definition at line 283 of file log_impl.h.
typedef struct log_tdes LOG_TDES
Definition at line 459 of file log_impl.h.
typedef struct log_topops_addresses LOG_TOPOPS_ADDRESSES
Definition at line 328 of file log_impl.h.
typedef struct log_topops_stack LOG_TOPOPS_STACK
Definition at line 346 of file log_impl.h.
typedef enum log_topops_type LOG_TOPOPS_TYPE
Definition at line 344 of file log_impl.h.
typedef struct log_tran_btid_unique_stats LOG_TRAN_BTID_UNIQUE_STATS
Definition at line 370 of file log_impl.h.
typedef struct log_tran_btid_unique_stats_chunk LOG_TRAN_BTID_UNIQUE_STATS_CHUNK
Definition at line 393 of file log_impl.h.
typedef struct log_tran_class_cos LOG_TRAN_CLASS_COS
Definition at line 403 of file log_impl.h.
typedef struct log_tran_class_cos_chunk LOG_TRAN_CLASS_COS_CHUNK
Definition at line 415 of file log_impl.h.
typedef struct log_tran_update_stats LOG_TRAN_UPDATE_STATS
Definition at line 426 of file log_impl.h.
typedef struct log_unique_stats LOG_UNIQUE_STATS
Definition at line 362 of file log_impl.h.
typedef enum log_wrote_eot_log LOG_WRITE_EOT_LOG
Definition at line 291 of file log_impl.h.
typedef enum tran_abort_reason TRAN_ABORT_REASON
Definition at line 360 of file log_impl.h.
typedef struct trantable TRANTABLE
Definition at line 578 of file log_impl.h.
Enumeration Type Documentation
enum count_optim_state
Enumerator
COS_NOT_LOADED
COS_TO_LOAD
COS_LOADED
Definition at line 380 of file log_impl.h.
enum log_cs_access_mode
Enumerator
LOG_CS_FORCE_USE
LOG_CS_SAFE_READER
Definition at line 763 of file log_impl.h.
enum log_flush
Enumerator
LOG_DONT_NEED_FLUSH
LOG_NEED_FLUSH
Definition at line 277 of file log_impl.h.
enum log_getnewtrid
Enumerator
LOG_DONT_NEED_NEWTRID
LOG_NEED_NEWTRID
Definition at line 285 of file log_impl.h.
enum log_recvphase
Enumerator
LOG_RESTARTED
LOG_RECOVERY_ANALYSIS_PHASE
LOG_RECOVERY_REDO_PHASE
LOG_RECOVERY_UNDO_PHASE
LOG_RECOVERY_FINISH_2PC_PHASE
Definition at line 602 of file log_impl.h.
enum log_setdirty
Enumerator
LOG_DONT_SET_DIRTY
LOG_SET_DIRTY
Definition at line 281 of file log_impl.h.
enum log_topops_type
Enumerator
LOG_TOPOPS_NORMAL
LOG_TOPOPS_COMPENSATE_TRAN_ABORT
LOG_TOPOPS_COMPENSATE_SYSOP_ABORT
LOG_TOPOPS_POSTPONE
Definition at line 337 of file log_impl.h.
enum log_wrote_eot_log
Enumerator
LOG_NEED_TO_WRITE_EOT_LOG
LOG_ALREADY_WROTE_EOT_LOG
Definition at line 289 of file log_impl.h.
enum tran_abort_reason
Enumerator
TRAN_NORMAL
TRAN_ABORT_DUE_DEADLOCK
TRAN_ABORT_DUE_ROLLBACK_ON_ESCALATION
Definition at line 354 of file log_impl.h.
Function Documentation
LOG_TDES* LOG_FIND_CURRENT_TDES (THREAD_ENTRY * thread_p = NULL) inline
Definition at line 1115 of file log_impl.h.
References LOG_FIND_TDES(), and LOG_FIND_THREAD_TRAN_INDEX.
Referenced by btree_check_locking_for_delete_unique(), btree_key_remove_delete_mvccid_non_unique(), btree_key_remove_delete_mvccid_unique(), btree_key_remove_object_and_keep_visible_first(), btree_rv_log_delete_object(), btree_rv_log_insert_object(), copy_bind_value_to_tdes(), file_rv_user_page_unmark_delete_logical(), file_tracker_item_mark_heap_deleted(), heap_get_insert_location_with_lock(), locator_update_force(), log_append_undoredo_recdes2(), log_does_allow_replication(), logtb_find_current_tran_lsa(), logtb_rv_assign_mvccid_for_undo_recovery(), logtb_update_global_unique_stats_by_delta(), need_to_abort_tran(), pgbuf_rv_dealloc_undo(), prior_lsa_gen_undoredo_record_from_crumbs(), redistribute_partition_data(), return_error_to_client(), spage_save_space(), sqmgr_execute_query(), vacuum_add_dropped_file(), vacuum_process_log_block(), xbtree_load_index(), xbtree_load_online_index(), xchksum_insert_repl_log_and_demote_table_lock(), xlocator_upgrade_instances_domain(), and xtran_server_end_topop().
LOG_TDES* LOG_FIND_TDES (int tran_index) inline
Definition at line 1095 of file log_impl.h.
References trantable::all_tdes, LOG_SYSTEM_TRAN_INDEX, logtb_get_system_tdes(), NULL, trantable::num_total_indices, and log_global::trantable.
Referenced by event_log_bind_values(), event_log_many_ioreads(), event_log_slow_query(), event_log_temp_expand_pages(), locator_decr_num_transient_classnames(), locator_drop_class_name_entry(), locator_drop_transient_class_name_entries(), locator_force_for_multi_update(), locator_get_num_transient_classnames(), locator_incr_num_transient_classnames(), locator_savepoint_transient_class_name_entries(), locator_update_index(), lock_wait_state_to_string(), log_2pc_attach_global_tran(), log_2pc_check_duplicate_global_tran_id(), log_2pc_find_tran_descriptor(), log_2pc_get_global_tran_info(), log_2pc_prepare(), log_2pc_prepare_global_tran(), log_2pc_recovery(), log_2pc_recovery_prepared(), log_2pc_send_abort_decision(), log_2pc_set_global_tran_info(), log_2pc_start(), log_abort(), log_abort_all_active_transaction(), log_abort_partial(), log_add_to_modified_class_list(), log_append_dboutside_redo(), log_append_empty_record(), log_append_ha_server_state(), log_append_postpone(), log_append_redo_crumbs(), log_append_run_postpone(), log_append_savepoint(), log_append_undo_crumbs(), log_append_undoredo_crumbs(), log_check_system_op_is_started(), log_commit(), log_complete_for_2pc(), log_final(), LOG_FIND_CURRENT_TDES(), log_get_parent_lsa_system_op(), log_is_class_being_modified(), log_is_tran_in_system_op(), log_recovery(), log_recovery_abort_all_atomic_sysops(), log_recovery_analysis(), log_recovery_finish_all_postpone(), log_recovery_needs_skip_logical_redo(), log_recovery_redo(), log_recovery_undo(), log_skip_logging(), log_sysop_get_tran_index_and_tdes(), log_sysop_start(), log_update_global_btid_online_index_stats(), login_user(), logpb_checkpoint(), logtb_allocate_tran_index(), logtb_find_client_hostname(), logtb_find_client_name(), logtb_find_client_name_host_pid(), logtb_find_client_type(), logtb_find_current_mvccid(), logtb_find_interrupt(), logtb_find_isolation(), logtb_find_log_records_count(), logtb_find_state(), logtb_find_tran_index(), logtb_find_tranid(), logtb_find_wait_msecs(), logtb_free_tran_index(), logtb_get_client_ids(), logtb_get_current_mvccid(), logtb_get_mvcc_snapshot(), logtb_has_deadlock_priority(), logtb_has_updated(), logtb_initialize_system_tdes(), logtb_invalidate_snapshot_data(), logtb_is_active(), logtb_is_current_active(), logtb_is_current_mvccid(), logtb_is_interrupted(), logtb_is_interrupted_tran(), logtb_is_tran_modification_disabled(), logtb_istran_finished(), logtb_load_global_statistics_to_tran(), logtb_release_tran_index(), logtb_rv_find_allocate_tran_index(), logtb_set_current_user_active(), logtb_set_suppress_repl_on_transaction(), logtb_set_tran_index_interrupt(), logtb_set_user_name(), logtb_tran_create_btid_unique_stats(), logtb_tran_create_class_cos(), logtb_tran_find_btid_stats(), logtb_tran_find_class_cos(), logtb_tran_reset_count_optim_state(), logtb_tran_update_all_global_unique_stats(), logtb_tran_update_stats_online_index_rb(), mvcc_is_active_id(), pgbuf_find_current_wait_msecs(), qexec_evaluate_aggregates_optimize(), qexec_execute_insert(), qexec_execute_query(), qexec_execute_selupd_list(), qmgr_get_temp_file_membuf_pages(), spage_save_space(), test_mvcc_get_snapshot(), test_new_mvcc_complete(), xboot_unregister_client(), xlogtb_reset_isolation(), xlogtb_reset_wait_msecs(), xtx_add_lob_locator(), xtx_change_state_of_locator(), xtx_drop_lob_locator(), and xtx_find_lob_locator().
void log_find_unilaterally_largest_undo_lsa (THREAD_ENTRY * thread_p, LOG_LSA & max_undo_lsa)
Definition at line 4170 of file log_tran_table.c.
References trantable::all_tdes, i, log_Gl, LOG_SYSTEM_TRAN_INDEX, LSA_LT(), LSA_SET_NULL(), log_system_tdes::map_all_tdes(), NULL, NULL_TRANID, NUM_TOTAL_TRAN_INDICES, log_tdes::state, TR_TABLE_CS_ENTER_READ_MODE, TR_TABLE_CS_EXIT, TRAN_UNACTIVE_ABORTED, TRAN_UNACTIVE_UNILATERALLY_ABORTED, log_global::trantable, log_tdes::trid, and log_tdes::undo_nxlsa.
Referenced by log_recovery_undo().
LOG_PAGE* log_pbfetch (LOG_PAGEID pageid)
void log_recovery (THREAD_ENTRY * thread_p, int ismedia_crash, time_t * stopat)
Definition at line 648 of file log_recovery.c.
References log_header::append_lsa, ARG_FILE_LINE, assert, log_rec_header::back_lsa, boot_reset_db_parm(), log_header::chkpt_lsa, log_global::chkpt_redo_lsa, ER_FATAL_ERROR_SEVERITY, ER_LOG_CORRUPTED_DB_DUE_CRASH_NOLOGGING, er_log_debug, ER_LOG_RECOVERY_FINISHED, ER_LOG_RECOVERY_STARTED, ER_LOG_UNKNOWN_TRANINDEX, ER_NOTIFICATION_SEVERITY, er_set(), fileio_map_mounted(), fileio_synchronize_all(), log_global::final_restored_lsa, log_header::has_logging_been_skipped, log_global::hdr, heap_classrepr_restart_cache(), locator_initialize(), log_2pc_recovery(), log_append_empty_record(), LOG_APPEND_PTR(), LOG_CS_ENTER(), LOG_CS_EXIT(), LOG_CS_OWN_WRITE_MODE(), LOG_DUMMY_CRASH_RECOVERY, LOG_FIND_TDES(), LOG_FIND_THREAD_TRAN_INDEX, log_Gl, LOG_HAS_LOGGING_BEEN_IGNORED, log_recovery_analysis(), LOG_RECOVERY_ANALYSIS_PHASE, LOG_RECOVERY_FINISH_2PC_PHASE, log_recovery_notpartof_volumes(), log_recovery_redo(), LOG_RECOVERY_REDO_PHASE, log_recovery_undo(), LOG_RECOVERY_UNDO_PHASE, LOG_RESET_PREV_LSA(), log_rv_find_checkpoint(), LOG_SET_CURRENT_TRAN_INDEX, logpb_checkpoint(), logpb_decache_archive_info(), logpb_fatal_error(), logpb_fetch_start_append_page(), logpb_flush_header(), logpb_flush_pages_direct(), logtb_set_num_loose_end_trans(), LSA_AS_ARGS, LSA_COPY(), NO_ERROR, NULL, NULL_VOLID, trantable::num_coord_loose_end_indices, trantable::num_prepared_loose_end_indices, log_lsa::pageid, pgbuf_flush_all(), log_global::rcv_phase, log_global::rcv_phase_lsa, log_system_tdes::rv_final(), log_tdes::state, log_tdes::tail_lsa, TRAN_ACTIVE, TRAN_RECOVERY, log_global::trantable, and vacuum_notify_server_crashed().
Referenced by log_initialize_internal().
char* log_rv_pack_redo_record_changes (char * ptr, int offset_to_data, int old_data_size, int new_data_size, char * new_data)
Definition at line 6314 of file log_recovery.c.
References assert, INT_ALIGNMENT, NULL, OR_BYTE_SIZE, OR_PUT_BYTE, OR_PUT_SHORT, OR_SHORT_SIZE, and PTR_ALIGN.
Referenced by btree_add_mvccid(), btree_insert_object_ordered_by_oid(), btree_leaf_change_first_object(), btree_leaf_record_change_overflow_link(), btree_leaf_record_handle_first_overflow(), btree_record_append_object(), btree_record_remove_last_object(), btree_record_remove_object_internal(), btree_record_replace_object(), btree_remove_delete_mvccid_unique_internal(), btree_remove_mvccid(), and btree_set_mvccid().
char* log_rv_pack_undo_record_changes (char * ptr, int offset_to_data, int old_data_size, int new_data_size, char * old_data)
Definition at line 6356 of file log_recovery.c.
References assert, INT_ALIGNMENT, NULL, OR_BYTE_SIZE, OR_PUT_BYTE, OR_PUT_SHORT, OR_SHORT_SIZE, PTR_ALIGN, and STATIC_INLINE.
Referenced by btree_add_mvccid(), btree_insert_object_ordered_by_oid(), btree_leaf_change_first_object(), btree_leaf_record_change_overflow_link(), btree_leaf_record_handle_first_overflow(), btree_record_append_object(), btree_record_remove_last_object(), btree_record_remove_object_internal(), btree_record_replace_object(), btree_remove_delete_mvccid_unique_internal(), btree_remove_mvccid(), and btree_set_mvccid().
int log_rv_redo_record_modify (THREAD_ENTRY * thread_p, LOG_RCV * rcv)
Definition at line 6177 of file log_recovery.c.
References log_rv_record_modify_internal().
int log_rv_undo_record_modify (THREAD_ENTRY * thread_p, LOG_RCV * rcv)
Definition at line 6195 of file log_recovery.c.
References log_rv_record_modify_internal().
int log_rv_undoredo_record_partial_changes (THREAD_ENTRY * thread_p, char * rcv_data, int rcv_data_length, RECDES * record, bool is_undo)
Definition at line 6148 of file log_recovery.c.
References assert, log_rv_undoredo_partial_changes_recursive(), NULL, and OR_BUF_INIT.
Referenced by btree_rv_record_modify_internal(), and log_rv_record_modify_internal().
void log_set_db_restore_time (THREAD_ENTRY * thread_p, INT64 db_restore_time)
Definition at line 9351 of file log_manager.c.
References log_header::db_restore_time, log_global::hdr, LOG_CS_ENTER(), LOG_CS_EXIT(), and log_Gl.
Referenced by boot_restart_server().
void log_set_ha_promotion_time (THREAD_ENTRY * thread_p, INT64 ha_promotion_time)
Definition at line 9334 of file log_manager.c.
References log_header::ha_promotion_time, log_global::hdr, LOG_CS_ENTER(), LOG_CS_EXIT(), and log_Gl.
Referenced by boot_restart_server(), css_change_ha_server_state(), and css_transit_ha_server_state().
LOG_LSA* log_startof_nxrec (THREAD_ENTRY * thread_p, LOG_LSA * lsa, bool canuse_forwaddr)
Definition at line 5433 of file log_recovery.c.
References log_page::area, error(), log_rec_header::forw_lsa, GET_ZIP_LEN, log_rec_2pc_prepcommit::gtrinfo_length, log_page::hdr, IO_MAX_PAGE_SIZE, log_rec_undo::length, log_rec_redo::length, log_rec_replication::length, log_rec_dbout_redo::length, log_rec_compensate::length, log_rec_run_postpone::length, log_rec_savept::length, LOG_2PC_ABORT_DECISION, LOG_2PC_ABORT_INFORM_PARTICPS, LOG_2PC_COMMIT_DECISION, LOG_2PC_COMMIT_INFORM_PARTICPS, LOG_2PC_PREPARE, LOG_2PC_RECV_ACK, LOG_2PC_START, LOG_ABORT, LOG_COMMIT, LOG_COMMIT_WITH_POSTPONE, LOG_COMPENSATE, LOG_CS_FORCE_USE, LOG_DBEXTERN_REDO_DATA, LOG_DIFF_UNDOREDO_DATA, LOG_DUMMY_CRASH_RECOVERY, LOG_DUMMY_GENERIC, LOG_DUMMY_HA_SERVER_STATE, LOG_DUMMY_HEAD_POSTPONE, LOG_DUMMY_OVF_RECORD, LOG_END_CHKPT, LOG_END_OF_LOG, LOG_GET_LOG_RECORD_HEADER, LOG_LARGER_LOGREC_TYPE, LOG_MVCC_DIFF_UNDOREDO_DATA, LOG_MVCC_REDO_DATA, LOG_MVCC_UNDO_DATA, LOG_MVCC_UNDOREDO_DATA, LOG_POSTPONE, LOG_READ_ADD_ALIGN, LOG_READ_ADVANCE_WHEN_DOESNT_FIT, LOG_REDO_DATA, LOG_REPLICATION_DATA, LOG_REPLICATION_STATEMENT, LOG_RUN_POSTPONE, LOG_SAVEPOINT, LOG_SMALLER_LOGREC_TYPE, LOG_START_CHKPT, LOG_SYSOP_ATOMIC_START, LOG_SYSOP_END, LOG_SYSOP_END_LOGICAL_MVCC_UNDO, LOG_SYSOP_END_LOGICAL_UNDO, LOG_SYSOP_START_POSTPONE, LOG_UNDO_DATA, LOG_UNDOREDO_DATA, LOG_WILL_COMMIT, logpb_fetch_page(), logpb_is_page_in_archive(), LSA_COPY(), LSA_ISNULL(), MAX_ALIGNMENT, log_rec_sysop_end::mvcc_undo, NO_ERROR, log_rec_chkpt::ntops, log_rec_chkpt::ntrans, NULL, NULL_OFFSET, log_rec_2pc_prepcommit::num_object_locks, log_rec_2pc_start::num_particps, log_lsa::offset, log_hdrpage::offset, log_lsa::pageid, log_rec_2pc_start::particp_id_length, PTR_ALIGN, log_rec_mvcc_redo::redo, log_rec_undoredo::rlength, log_rec_sysop_start_postpone::sysop_end, log_rec_header::type, log_rec_sysop_end::type, log_rec_undoredo::ulength, log_rec_mvcc_undo::undo, log_rec_sysop_end::undo, and log_rec_mvcc_undoredo::undoredo.
Referenced by log_recovery_analysis(), and xlog_dump().
VOLID logpb_add_volume (const char * db_fullname, VOLID new_volid, const char * new_volfullname, DISK_VOLPURPOSE new_volpurpose)
Definition at line 4764 of file log_page_buffer.c.
References DB_TEMPORARY_DATA_PURPOSE, fileio_make_volume_info_name(), log_Name_volinfo, NULL, and NULL_VOLID.
Referenced by boot_create_all_volumes(), disk_add_volume(), log_create_internal(), log_recreate(), logpb_copy_database(), logpb_create_log_info(), logpb_recreate_volume_info(), and logpb_rename_all_volumes_files().
int logpb_background_archiving (THREAD_ENTRY * thread_p)
Definition at line 10836 of file log_page_buffer.c.
References ARG_FILE_LINE, assert, log_global::bg_archive_info, log_header::chkpt_lsa, background_archiving_info::current_page_id, er_errid(), er_log_debug, ER_LOG_READ, ER_LOG_WRITE, error(), fileio_dismount(), FILEIO_WRITE_NO_COMPENSATE_WRITE, fileio_write_pages(), log_global::hdr, IO_MAX_PAGE_SIZE, background_archiving_info::last_sync_pageid, log_archive_er_log, log_Gl, LOG_PAGESIZE, LOGPB_IO_NPAGES, logpb_read_page_from_active_log(), MAX_ALIGNMENT, NO_ERROR, NULL, NULL_PAGEID, NULL_VOLDES, log_lsa::pageid, log_buffer::phy_pageid, prm_get_bool_value(), PRM_ID_LOG_BACKGROUND_ARCHIVING, PTR_ALIGN, background_archiving_info::start_page_id, and background_archiving_info::vdes.
Referenced by log_initialize_internal().
int logpb_backup (THREAD_ENTRY * thread_p, int num_perm_vols, const char * allbackup_path, FILEIO_BACKUP_LEVEL backup_level, bool delete_unneeded_logarchives, const char * backup_verbose_file_path, int num_threads, FILEIO_ZIP_METHOD zip_method, FILEIO_ZIP_LEVEL zip_level, int skip_activelog, int sleep_msecs, bool separate_keys)
Definition at line 7427 of file log_page_buffer.c.
References log_header::append_lsa, ARG_FILE_LINE, assert, ASSERT_ERROR, assert_release, fileio_backup_record_info::at_time, log_header::bkinfo, io_backup_session::bkup, log_hdr_bkup_level_info::bkup_attime, log_header::bkup_level0_lsa, log_header::bkup_level1_lsa, log_header::bkup_level2_lsa, fileio_backup_buffer::bkuphdr, boot_db_name(), log_header::chkpt_lsa, CTIME_MAX, fileio_backup_buffer::current_path, log_header::db_creation, fileio_backup_header::db_fullname, disk_lock_extend(), disk_unlock_extend(), fileio_backup_buffer::dtype, er_errid(), ER_ERROR_SEVERITY, ER_FAILED, ER_FATAL_ERROR_SEVERITY, ER_INTERRUPTED, ER_LOG_BACKUP_CS_ENTER, ER_LOG_BACKUP_CS_EXIT, ER_LOG_BACKUP_LEVEL_NOGAPS, ER_LOG_BKUP_DUPLICATE_REQUESTS, ER_LOG_CANNOT_ACCESS_BACKUP, ER_LOG_CREATE_DBBACKUP_DIRINFO, ER_LOG_DBBACKUP_FAIL, ER_NOTIFICATION_SEVERITY, er_set(), er_set_with_oserror(), error(), fileio_abort_backup(), FILEIO_BACKUP_BIG_INCREMENT_LEVEL, FILEIO_BACKUP_FULL_LEVEL, FILEIO_BACKUP_SMALL_INCREMENT_LEVEL, FILEIO_BACKUP_UNDEFINED_LEVEL, FILEIO_BACKUP_VOL_DEVICE, fileio_backup_volume(), FILEIO_BACKUP_WRITE, fileio_clear_backup_info_level(), fileio_dismount(), fileio_finalize_backup_info(), fileio_find_next_perm_volume(), fileio_finish_backup(), FILEIO_FIRST_BACKUP_VOL_INFO, fileio_get_backup_info_volume_name(), fileio_get_base_file_name(), fileio_get_directory_path(), fileio_get_volume_label(), fileio_get_zip_level_string(), fileio_get_zip_method_string(), FILEIO_INITIAL_BACKUP_UNITS, fileio_initialize_backup(), fileio_is_volume_exist(), fileio_is_volume_exist_and_file(), fileio_make_backup_name(), fileio_make_volume_info_name(), fileio_mount(), FILEIO_NO_BACKUP_UNITS, FILEIO_PROMPT_DISPLAY_ONLY, fileio_read_backup_info_entries(), fileio_remove_all_backup(), fileio_request_user_response(), fileio_start_backup(), FILEIO_ZIP_NONE_METHOD, log_global::hdr, log_header::last_arv_num_for_syscrashes, fileio_backup_header::level, LOG_CS_ENTER(), LOG_CS_EXIT(), log_Db_fullname, LOG_DBFIRST_VOLID, LOG_DBLOG_ACTIVE_VOLID, LOG_DBLOG_BKUPINFO_VOLID, LOG_DBLOG_INFO_VOLID, LOG_DBTDE_KEYS_VOLID, LOG_DBVOLINFO_VOLID, log_Gl, log_Name_active, log_Name_bkupinfo, log_Name_info, log_Path, logpb_archive_active_log(), logpb_backup_for_volume(), logpb_flush_header(), logpb_get_archive_number(), logpb_initialize_backup_info(), logpb_is_page_in_archive(), LOGPB_NEXT_ARCHIVE_PAGE_ID, logpb_remote_ask_user_before_delete_volumes(), logpb_remove_archive_logs(), logpb_update_backup_volume_info(), logtb_get_check_interrupt(), logtb_is_interrupted(), LSA_COPY(), LSA_ISNULL(), LSA_LT(), LSA_SET_NULL(), MSGCAT_CATALOG_CUBRID, MSGCAT_LOG_BACKUP_HALTED_BY_USER, MSGCAT_LOG_DATABASE_BACKUP_WAS_TAKEN, msgcat_message(), MSGCAT_SET_LOG, NO_ERROR, NULL, NULL_PAGEID, NULL_VOLDES, NULL_VOLID, fileio_thread_info::num_threads, log_header::nxarv_num, log_lsa::offset, log_lsa::pageid, PEEK, log_header::prefix_name, prm_get_integer_value(), PRM_ID_IO_BACKUP_SLEEP_MSECS, pthread_mutex_lock, pthread_mutex_unlock, io_backup_session::read_thread_info, log_global::run_nxchkpt_atpageid, rv, fileio_backup_header::skip_activelog, log_header::smallest_lsa_at_last_chkpt, fileio_backup_header::start_time, tde_copy_keys_file(), tde_make_keys_file_fullname(), thread_sleep(), io_backup_session::type, fileio_backup_header::unit_num, vacuum_er_log, VACUUM_ER_LOG_ARCHIVES, vacuum_min_log_pageid_to_keep(), and io_backup_session::verbose_fp.
Referenced by xboot_backup().
char* logpb_backup_level_info_to_string (char * buf, int buf_size, const LOG_HDR_BKUP_LEVEL_INFO * info)
Definition at line 11074 of file log_page_buffer.c.
References log_hdr_bkup_level_info::bkup_attime, if(), and strlen.
Referenced by log_active_log_header_next_scan().
int logpb_check_and_reset_temp_lsa (THREAD_ENTRY * thread_p, VOLID volid)
Definition at line 10665 of file log_page_buffer.c.
References DB_TEMPORARY_DATA_PURPOSE, ER_FAILED, FREE, LOG_DBFIRST_VOLID, NO_ERROR, NULL, OLD_PAGE, vpid::pageid, pgbuf_fix, PGBUF_LATCH_WRITE, pgbuf_reset_temp_lsa(), pgbuf_set_dirty(), PGBUF_UNCONDITIONAL_LATCH, pgbuf_unfix, vpid::volid, and xdisk_get_purpose().
Referenced by log_recreate(), and logpb_copy_volume().
int logpb_check_exist_any_volumes (THREAD_ENTRY * thread_p, const char * db_fullname, const char * logpath, const char * prefix_logname, char * first_vol, bool * is_exist)
Definition at line 10373 of file log_page_buffer.c.
References log_Name_active, log_Name_info, log_Name_volinfo, logpb_check_if_exists(), logpb_initialize_log_names(), and NO_ERROR.
Referenced by xboot_initialize_server().
LOG_PAGEID logpb_checkpoint (THREAD_ENTRY * thread_p)
Definition at line 6746 of file log_page_buffer.c.
References log_header::append_lsa, log_global::archive, ARG_FILE_LINE, assert, log_header::avg_nlocks, log_header::avg_ntrans, BO_IS_SERVER_RESTARTED, log_global::chkpt_every_npages, log_header::chkpt_lsa, log_global::chkpt_redo_lsa, log_prior_node::data_header, detailed_er_log, disk_set_checkpoint(), ER_LOG_CHECKPOINT_FINISHED, ER_LOG_CHECKPOINT_STARTED, er_log_debug, ER_LOG_MOUNT_FAIL, ER_NOTIFICATION_SEVERITY, er_set(), fileio_find_next_perm_volume(), fileio_get_volume_descriptor(), fileio_get_volume_label(), fileio_make_log_archive_name(), FILEIO_SYNC_ALSO_FLUSH_DWB, fileio_synchronize(), fileio_synchronize_all(), free_and_init, log_global::hdr, i, log_header::last_arv_num_for_syscrashes, lock_get_number_object_locks(), log_Archive_path, LOG_CS_ENTER(), LOG_CS_EXIT(), LOG_CS_OWN_WRITE_MODE(), LOG_DBFIRST_VOLID, log_dump_log_info(), LOG_END_CHKPT, LOG_FIND_TDES(), log_Gl, log_Name_info, log_Prefix, LOG_START_CHKPT, LOG_SYSTEM_TRAN_INDEX, logpb_checkpoint_topops(), logpb_checkpoint_trans(), logpb_dismount_log_archive(), logpb_fetch_from_archive(), logpb_flush_header(), logpb_flush_pages_direct(), logpb_is_page_in_archive(), logtb_clear_tdes(), logtb_find_smallest_lsa(), logtb_reflect_global_unique_stats_to_btree(), LSA_COPY(), LSA_GT(), LSA_ISNULL(), LSA_LE(), LSA_LT(), LSA_SET_NULL(), log_system_tdes::map_all_tdes(), MSGCAT_CATALOG_CUBRID, MSGCAT_LOG_LOGINFO_COMMENT_ARCHIVE_NONEEDED, MSGCAT_LOG_LOGINFO_COMMENT_MANY_ARCHIVES_NONEEDED, msgcat_message(), MSGCAT_SET_LOG, NO_ERROR, log_rec_chkpt::ntops, log_rec_chkpt::ntrans, NULL, NULL_PAGEID, NULL_VOLDES, NULL_VOLID, trantable::num_assigned_indices, trantable::num_total_indices, log_header::nxarv_num, log_lsa::pageid, PEEK, perfmon_inc_stat(), pgbuf_flush_checkpoint(), log_global::prior_info, prior_lsa_alloc_and_copy_data(), log_prior_lsa_info::prior_lsa_mutex, prior_lsa_next_record(), prior_lsa_next_record_with_lock(), prm_get_bool_value(), PRM_ID_LOG_CHKPT_DETAILED, PSTAT_LOG_NUM_END_CHECKPOINTS, PSTAT_LOG_NUM_START_CHECKPOINTS, pthread_mutex_lock, pthread_mutex_unlock, log_rec_chkpt::redo_lsa, log_global::run_nxchkpt_atpageid, RV_NOT_DEFINED, log_header::smallest_lsa_at_last_chkpt, TR_TABLE_CS_ENTER, TR_TABLE_CS_EXIT, log_global::trantable, log_archives::vdes, and xboot_find_last_permanent().
Referenced by boot_create_all_volumes(), log_complete(), log_complete_for_2pc(), log_final(), log_is_log_flush_daemon_available(), log_recovery(), and log_sysop_end_final().
int logpb_copy_database (THREAD_ENTRY * thread_p, VOLID num_perm_vols, const char * to_db_fullname, const char * to_logpath, const char * to_prefix_logname, const char * toext_path, const char * fileof_vols_and_copypaths)
Definition at line 9225 of file log_page_buffer.c.
References log_page::area, ARG_FILE_LINE, log_rec_header::back_lsa, boot_db_full_name(), log_header::chkpt_lsa, log_header::db_creation, DB_PERMANENT_DATA_PURPOSE, DISK_FLUSH, disk_set_link(), DISK_UNKNOWN_PURPOSE, dwb_destroy(), dwb_is_created(), log_header::eof_lsa, ER_ERROR_SEVERITY, ER_FAILED, ER_LOG_MOUNT_FAIL, er_set(), ER_TDE_COPY_KEYS_FILE_FAIL, error(), fileio_dismount(), fileio_find_next_perm_volume(), fileio_format(), fileio_make_backup_volume_info_name(), fileio_make_log_active_name(), fileio_make_log_info_name(), fileio_make_volume_info_name(), fileio_mount(), FILEIO_SYNC_ALSO_FLUSH_DWB, fileio_synchronize(), fileio_unformat(), fileio_write(), FILEIO_WRITE_DEFAULT_WRITE, FILEIO_WRITE_NO_COMPENSATE_WRITE, log_hdrpage::flags, log_rec_header::forw_lsa, free_and_init, log_page::hdr, log_global::hdr, log_Db_fullname, LOG_DBCOPY_VOLID, LOG_DBFIRST_VOLID, LOG_DBLOG_ACTIVE_VOLID, LOG_DBLOG_BKUPINFO_VOLID, log_dump_log_info(), LOG_END_OF_LOG, log_Gl, LOG_PAGE_INIT_VALUE, LOG_PAGESIZE, LOG_SYSTEM_TRANID, log_hdrpage::logical_pageid, logpb_add_volume(), logpb_copy_log_header(), logpb_copy_volume(), logpb_create_log_info(), logpb_create_volume_info(), logpb_flush_pages_direct(), LOGPB_HEADER_PAGE_ID, logpb_initialize_header(), logpb_next_where_path(), LOGPB_PHYSICAL_HEADER_PAGE_ID, logpb_set_page_checksum(), logpb_start_where_path(), logpb_to_physical_pageid(), logpb_verify_length(), LSA_SET_NULL(), MSGCAT_CATALOG_CUBRID, MSGCAT_LOG_LOGINFO_ACTIVE, msgcat_message(), MSGCAT_SET_LOG, NO_ERROR, log_header::npages, NULL, NULL_OFFSET, NULL_VOLDES, NULL_VOLID, log_lsa::offset, log_hdrpage::offset, log_lsa::pageid, pgbuf_flush_all_unfixed_and_set_lsa_as_null(), pgbuf_invalidate_all, log_buffer::phy_pageid, log_rec_header::prev_tranlsa, tde_copy_keys_file(), tde_make_keys_file_fullname(), log_rec_header::trid, and log_rec_header::type.
Referenced by xboot_copy().
void logpb_copy_from_log (THREAD_ENTRY * thread_p, char * area, int length, LOG_LSA * log_lsa, LOG_PAGE * log_pgptr)
Definition at line 6407 of file log_page_buffer.c.
References log_page::area, LOG_READ_ADVANCE_WHEN_DOESNT_FIT, LOGAREA_SIZE, and log_lsa::offset.
Referenced by log_2pc_read_prepare(), log_2pc_recovery_start(), log_dump_data(), log_get_undo_record(), log_read_sysop_start_postpone(), log_recovery_analysis(), log_recovery_redo(), log_rollback_record(), log_run_postpone_op(), log_rv_analysis_end_checkpoint(), log_rv_get_unzip_log_data(), log_rv_redo_record(), and log_rv_undo_record().
int logpb_copy_page_from_file (THREAD_ENTRY * thread_p, LOG_PAGEID pageid, LOG_PAGE * log_pgptr)
Definition at line 1816 of file log_page_buffer.c.
References log_header::append_lsa, assert, ER_FAILED, log_global::hdr, LOG_CS_ENTER_READ_MODE(), LOG_CS_EXIT(), LOG_CS_FORCE_USE, log_Gl, logpb_log, logpb_read_page_from_file(), NO_ERROR, NULL, NULL_PAGEID, log_lsa::pageid, and rv.
Referenced by logwr_log_ha_filestat_to_string().
int logpb_copy_page_from_log_buffer (THREAD_ENTRY * thread_p, LOG_PAGEID pageid, LOG_PAGE * log_pgptr)
Definition at line 1788 of file log_page_buffer.c.
References log_header::append_lsa, assert, ASSERT_ERROR, ER_FAILED, log_global::hdr, LOG_CS_FORCE_USE, log_Gl, logpb_copy_page(), logpb_log, NO_ERROR, NULL, NULL_PAGEID, log_lsa::pageid, and rv.
Referenced by logwr_log_ha_filestat_to_string().
LOG_PAGE* logpb_create_header_page (THREAD_ENTRY * thread_p)
Definition at line 1397 of file log_page_buffer.c.
References assert, LOG_CS_OWN_WRITE_MODE(), logpb_create_page(), and LOGPB_HEADER_PAGE_ID.
Referenced by log_create_internal(), and log_recovery_resetlog().
void logpb_create_log_info (const char * logname_info, const char * db_fullname)
Definition at line 4479 of file log_page_buffer.c.
References CUBRID_MAGIC_LOG_INFO, db_name, DISK_UNKNOWN_PURPOSE, log_Db_fullname, LOG_DBLOG_INFO_VOLID, log_dump_log_info(), logpb_add_volume(), MSGCAT_CATALOG_CUBRID, MSGCAT_LOG_LOGINFO_COMMENT, msgcat_message(), MSGCAT_SET_LOG, NO_ERROR, and NULL.
Referenced by log_create_internal(), logpb_copy_database(), and logpb_rename_all_volumes_files().
LOG_PAGE* logpb_create_page (THREAD_ENTRY * thread_p, LOG_PAGEID pageid)
Definition at line 776 of file log_page_buffer.c.
References logpb_locate_page(), and NEW_PAGE.
Referenced by log_recovery_resetlog(), logpb_create_header_page(), and logpb_next_append_page().
int logpb_create_volume_info (const char * db_fullname)
Definition at line 4647 of file log_page_buffer.c.
References ARG_FILE_LINE, ER_BO_CANNOT_CREATE_VOL, ER_ERROR_SEVERITY, er_set_with_oserror(), fileio_make_volume_info_name(), LOG_DBVOLINFO_VOLID, log_Name_volinfo, NO_ERROR, and NULL.
Referenced by log_create_internal(), logpb_copy_database(), logpb_recreate_volume_info(), and logpb_rename_all_volumes_files().
void logpb_debug_check_log_page (THREAD_ENTRY * thread_p, void * log_pgptr_ptr)
Definition at line 11348 of file log_page_buffer.c.
References assert, boot_Server_status, BOOT_SERVER_UP, err, log_page::hdr, log_hdrpage::logical_pageid, LOGPB_HEADER_PAGE_ID, logpb_page_check_corruption(), NO_ERROR, and NULL.
Referenced by logpb_fetch_from_archive(), logpb_fetch_header_from_active_log(), logpb_find_oldest_available_page_id(), logpb_flush_all_append_pages(), logpb_read_page_from_active_log(), logpb_read_page_from_file(), logpb_write_toflush_pages_to_archive(), and pwrite_with_injected_fault().
void logpb_decache_archive_info (THREAD_ENTRY * thread_p)
Definition at line 5081 of file log_page_buffer.c.
References log_global::archive, free_and_init, LOG_ARCHIVE_CS_ENTER, LOG_ARCHIVE_CS_EXIT, log_Gl, logpb_dismount_log_archive(), log_archives::max_unav, log_archives::next_unav, NULL, NULL_VOLDES, log_archives::unav_archives, and log_archives::vdes.
Referenced by log_create_internal(), log_final(), log_initialize_internal(), log_recovery(), log_recovery_resetlog(), and logpb_remove_archive_logs_internal().
int logpb_delete (THREAD_ENTRY * thread_p, VOLID num_perm_vols, const char * db_fullname, const char * logpath, const char * prefix_logname, bool force_delete)
Definition at line 10078 of file log_page_buffer.c.
References ALLOC_COPY, log_global::append, log_global::archive, trantable::area, log_global::bg_archive_info, log_pb_global_data::buffers, log_header::db_compatibility, log_header::db_iopagesize, log_header::db_logpagesize, db_set_page_size(), er_clear(), er_errid(), ER_IO_MOUNT_LOCKED, fileio_dismount(), fileio_finalize_backup_info(), fileio_find_next_perm_volume(), FILEIO_FIRST_BACKUP_VOL_INFO, fileio_get_volume_descriptor(), fileio_get_volume_label(), fileio_is_volume_exist(), fileio_make_dwb_name(), fileio_make_log_archive_name(), fileio_make_volume_info_name(), fileio_mount(), fileio_read_backup_info_entries(), fileio_remove_all_backup(), fileio_unformat(), log_global::hdr, i, IO_MAX_PAGE_SIZE, IO_PAGESIZE, log_header::last_deleted_arv_num, log_Archive_path, LOG_DBFIRST_VOLID, LOG_DBLOG_ACTIVE_VOLID, LOG_DBLOG_BKUPINFO_VOLID, LOG_DBLOG_INFO_VOLID, LOG_DBTDE_KEYS_VOLID, LOG_DBVOLINFO_VOLID, log_Gl, log_Name_active, log_Name_bg_archive, log_Name_bkupinfo, log_Name_info, log_Name_removed_archive, LOG_PAGESIZE, log_Path, log_append_info::log_pgptr, log_Prefix, logpb_dismount_log_archive(), logpb_fetch_header_with_buffer(), logpb_finalize_pool(), logpb_initialize_log_names(), logpb_initialize_pool(), logpb_Initialized, logtb_define_trantable_log_latch(), logtb_undefine_trantable(), MAX_ALIGNMENT, NO_ERROR, NULL, NULL_VOLDES, NULL_VOLID, pgbuf_invalidate_all, prm_get_bool_value(), PRM_ID_LOG_BACKGROUND_ARCHIVING, PTR_ALIGN, rel_disk_compatible(), tde_make_keys_file_fullname(), log_global::trantable, log_archives::vdes, background_archiving_info::vdes, and log_append_info::vdes.
Referenced by boot_create_all_volumes(), and boot_remove_all_volumes().
void logpb_dump (THREAD_ENTRY * thread_p, FILE * out_fp)
Definition at line 1128 of file log_page_buffer.c.
References assert, log_global::flush_info, LOG_CS_OWN_WRITE_MODE(), log_Gl, logpb_dump_information(), logpb_dump_pages(), logpb_dump_to_flush_page(), logpb_Initialized, and log_flush_info::num_toflush.
Referenced by logpb_finalize_pool(), logpb_flush_all_append_pages(), and logpb_flush_log_for_wal().
void logpb_dump_checkpoint_trans (FILE * out_fp, int length, void * data)
Definition at line 7269 of file log_page_buffer.c.
References log_info_chkpt_trans::head_lsa, i, log_info_chkpt_trans::isloose_end, log_state_string(), log_lsa::offset, log_lsa::pageid, log_info_chkpt_trans::posp_nxlsa, log_info_chkpt_trans::savept_lsa, log_info_chkpt_trans::state, log_info_chkpt_trans::tail_lsa, log_info_chkpt_trans::tail_topresult_lsa, log_info_chkpt_trans::trid, log_info_chkpt_trans::undo_nxlsa, and log_info_chkpt_trans::user_name.
Referenced by log_dump_record_checkpoint().
void logpb_dump_log_page_area (THREAD_ENTRY * thread_p, LOG_PAGE * log_pgptr, int offset, int length)
Definition at line 3099 of file log_page_buffer.c.
References log_page::area, assert, log_hdrpage::checksum, log_page::hdr, i, LOGAREA_SIZE, log_hdrpage::logical_pageid, logpb_log, logpb_Logging, NULL, and ONE_K.
Referenced by logpb_flush_all_append_pages().
bool logpb_exist_log (THREAD_ENTRY * thread_p, const char * db_fullname, const char * logpath, const char * prefix_logname)
Definition at line 6641 of file log_page_buffer.c.
References fileio_is_volume_exist(), log_Name_active, logpb_initialize_log_names(), logpb_is_pool_initialized(), and NO_ERROR.
Referenced by boot_remove_all_volumes().
void logpb_fatal_error (THREAD_ENTRY * thread_p, bool logexit, const char * file_name, const int lineno, const char * fmt, ...)
Definition at line 10428 of file log_page_buffer.c.
References logpb_fatal_error_internal().
Referenced by heap_get_visible_version_from_log(), log_2pc_commit_first_phase(), log_2pc_expand_ack_list(), log_2pc_read_prepare(), log_2pc_recovery_analysis_info(), log_2pc_recovery_start(), log_complete_for_2pc(), log_do_postpone(), log_find_end_log(), log_get_next_nested_top(), log_get_undo_record(), log_initialize_internal(), log_recovery(), log_recovery_abort_atomic_sysop(), log_recovery_abort_interrupted_sysop(), log_recovery_analysis(), log_recovery_find_first_postpone(), log_recovery_redo(), log_recovery_resetlog(), log_recovery_undo(), log_rollback(), log_rollback_record(), log_run_postpone_op(), log_rv_analysis_2pc_abort_decision(), log_rv_analysis_2pc_abort_inform_particps(), log_rv_analysis_2pc_commit_decision(), log_rv_analysis_2pc_commit_inform_particps(), log_rv_analysis_2pc_prepare(), log_rv_analysis_2pc_recv_ack(), log_rv_analysis_2pc_start(), log_rv_analysis_atomic_sysop_start(), log_rv_analysis_commit_with_postpone(), log_rv_analysis_compensate(), log_rv_analysis_dummy_head_postpone(), log_rv_analysis_end_checkpoint(), log_rv_analysis_postpone(), log_rv_analysis_run_postpone(), log_rv_analysis_save_point(), log_rv_analysis_sysop_end(), log_rv_analysis_sysop_start_postpone(), log_rv_analysis_undo_redo(), log_rv_analysis_will_commit(), log_rv_redo_record(), log_rv_undo_record(), logpb_append_next_record(), logpb_archive_active_log(), logpb_fetch_from_archive(), logpb_fetch_header_with_buffer(), logpb_flush_all_append_pages(), logpb_flush_header(), logpb_flush_page(), logpb_initialize_header(), logpb_initialize_log_names(), logpb_initialize_pool(), logpb_next_append_page(), logpb_restore(), logpb_start_append(), logpb_write_page_to_disk(), logtb_define_trantable_log_latch(), logtb_initialize_system_tdes(), logtb_rv_find_allocate_tran_index(), vacuum_fetch_log_page(), vacuum_process_log_block(), vacuum_process_log_record(), vacuum_read_log_aligned(), vacuum_recover_lost_block_data(), and vacuum_worker_allocate_resources().
void logpb_fatal_error_exit_immediately_wo_flush (THREAD_ENTRY * thread_p, const char * file_name, const int lineno, const char * fmt, ...)
Definition at line 10439 of file log_page_buffer.c.
References logpb_fatal_error_internal().
Referenced by spage_compact().
LOG_PAGE* logpb_fetch_from_archive (THREAD_ENTRY * thread_p, LOG_PAGEID pageid, LOG_PAGE * log_pgptr, int * ret_arv_num, LOG_ARV_HEADER * arv_hdr, bool is_fatal)
Definition at line 5151 of file log_page_buffer.c.
References log_global::append, log_global::archive, log_page::area, ARG_FILE_LINE, log_arv_header::arv_num, assert, ASSERT_ERROR, log_header::db_creation, log_arv_header::db_creation, difftime64, ER_FAILED, ER_FATAL_ERROR_SEVERITY, ER_LOG_DOESNT_CORRESPOND_TO_DATABASE, ER_LOG_NOTIN_ARCHIVE, ER_LOG_PAGE_CORRUPTED, ER_LOG_READ, er_msg(), er_set(), ER_WARNING_SEVERITY, fileio_dismount(), fileio_get_volume_label_by_fd(), fileio_is_volume_exist(), fileio_make_log_archive_name(), fileio_mount(), fileio_read(), log_arv_header::fpageid, log_archives::hdr, log_page::hdr, log_global::hdr, if(), IO_MAX_PAGE_SIZE, LOG_ARCHIVE_CS_ENTER, LOG_ARCHIVE_CS_EXIT, log_Archive_path, LOG_CS_OWN(), log_Db_fullname, LOG_DBLOG_ARCHIVE_VOLID, log_default_input_for_archive_log_location, log_Gl, log_is_in_crash_recovery(), LOG_PAGESIZE, log_Prefix, LOG_RESTARTED, log_hdrpage::logical_pageid, logpb_debug_check_log_page(), logpb_fatal_error(), logpb_get_guess_archive_num(), logpb_get_tde_algorithm(), logpb_is_archive_available(), logpb_log, logpb_set_unavailable_archive(), MAX_ALIGNMENT, MSGCAT_CATALOG_CUBRID, MSGCAT_LOG_INPUT_RANGE_ERROR, MSGCAT_LOG_LOGARCHIVE_NEEDED, MSGCAT_LOG_NEWLOCATION, MSGCAT_LOG_STARTS, msgcat_message(), MSGCAT_SET_LOG, NO_ERROR, log_arv_header::npages, NULL, NULL_PAGEID, NULL_VOLDES, log_header::nxarv_num, PEEK, perfmon_inc_stat(), log_buffer::phy_pageid, prm_get_bool_value(), PRM_ID_LOG_TRACE_DEBUG, PSTAT_LOG_NUM_IOREADS, PTR_ALIGN, log_global::rcv_phase, TDE_ALGORITHM_NONE, tde_decrypt_log_page(), log_archives::vdes, and log_append_info::vdes.
Referenced by logpb_archive_active_log(), logpb_checkpoint(), logpb_get_archive_number(), logpb_read_page_from_file(), and logwr_log_ha_filestat_to_string().
void logpb_fetch_header (THREAD_ENTRY * thread_p, LOG_HEADER * hdr)
Definition at line 1440 of file log_page_buffer.c.
References log_header::append_lsa, assert, log_global::hdr, LOG_CS_OWN_WRITE_MODE(), log_Gl, LOG_RESET_APPEND_LSA(), log_global::loghdr_pgptr, logpb_fetch_header_with_buffer(), and NULL.
Referenced by log_initialize_internal().
void logpb_fetch_header_with_buffer (THREAD_ENTRY * thread_p, LOG_HEADER * hdr, LOG_PAGE * log_pgptr)
Definition at line 1463 of file log_page_buffer.c.
References log_page::area, ARG_FILE_LINE, assert, log_page::hdr, LOG_CS_OWN_WRITE_MODE(), LOG_CS_SAFE_READER, LOG_PAGESIZE, log_hdrpage::logical_pageid, logpb_fatal_error(), logpb_fetch_page(), LOGPB_HEADER_PAGE_ID, logpb_initialize_header(), NO_ERROR, NULL, NULL_OFFSET, log_lsa::offset, log_hdrpage::offset, and log_lsa::pageid.
Referenced by logpb_delete(), logpb_fetch_header(), and logpb_remove_all_in_log_path().
int logpb_fetch_page (THREAD_ENTRY * thread_p, const LOG_LSA * req_lsa, LOG_CS_ACCESS_MODE access_mode, LOG_PAGE * log_pgptr)
Definition at line 1724 of file log_page_buffer.c.
References log_global::append, log_header::append_lsa, assert, ASSERT_ERROR, ER_FAILED, log_global::hdr, LOG_CS_ENTER(), LOG_CS_EXIT(), log_Gl, logpb_copy_page(), logpb_log, logpb_prior_lsa_append_all_list(), LSA_COPY(), LSA_LE(), NO_ERROR, NULL, NULL_PAGEID, log_lsa::pageid, log_append_info::prev_lsa, and rv.
Referenced by heap_get_visible_version_from_log(), log_2pc_recovery_analysis_info(), log_do_postpone(), log_find_end_log(), log_get_next_nested_top(), log_get_savepoint_lsa(), log_is_page_of_record_broken(), log_read_sysop_start_postpone(), log_recovery_abort_atomic_sysop(), log_recovery_abort_interrupted_sysop(), log_recovery_analysis(), log_recovery_find_first_postpone(), log_recovery_redo(), log_recovery_resetlog(), log_recovery_undo(), log_rollback(), log_startof_nxrec(), logpb_fetch_header_with_buffer(), logpb_write_toflush_pages_to_archive(), vacuum_fetch_log_page(), vacuum_log_prefetch_vacuum_block(), vacuum_recover_lost_block_data(), and xlog_dump().
int logpb_fetch_start_append_page (THREAD_ENTRY * thread_p)
Definition at line 2475 of file log_page_buffer.c.
References log_global::append, log_header::append_lsa, assert, ER_FAILED, log_global::flush_info, log_global::hdr, LOG_CS_OWN_WRITE_MODE(), log_Gl, log_append_info::log_pgptr, logpb_flush_pages_direct(), logpb_invalid_all_append_pages(), logpb_locate_page(), logpb_log, log_flush_info::max_toflush, NEW_PAGE, NO_ERROR, NULL, log_flush_info::num_toflush, log_lsa::offset, OLD_PAGE, log_lsa::pageid, pthread_mutex_lock, pthread_mutex_unlock, rv, log_append_info::set_nxio_lsa(), and log_flush_info::toflush.
Referenced by log_create_internal(), log_initialize_internal(), log_recovery(), log_recovery_resetlog(), logpb_find_header_parameters(), and logpb_rename_all_volumes_files().
LOG_PAGE* logpb_fetch_start_append_page_new (THREAD_ENTRY * thread_p)
Definition at line 2552 of file log_page_buffer.c.
References log_global::append, log_header::append_lsa, assert, log_global::hdr, LOG_CS_OWN_WRITE_MODE(), log_Gl, log_append_info::log_pgptr, logpb_locate_page(), logpb_log, NEW_PAGE, NULL, log_lsa::pageid, and log_append_info::set_nxio_lsa().
void logpb_finalize_pool (THREAD_ENTRY * thread_p)
Definition at line 667 of file log_page_buffer.c.
References log_global::append, ARG_FILE_LINE, assert, log_pb_global_data::buffers, er_log_debug, free_and_init, log_group_commit_info::gc_cond, log_group_commit_info::gc_mutex, log_global::group_commit_info, log_pb_global_data::header_page, log_append_final_zip(), LOG_CS_OWN_WRITE_MODE(), log_Gl, log_append_info::log_pgptr, LOG_RESET_PREV_LSA(), logpb_dump(), logpb_finalize_flush_info(), logpb_finalize_writer_info(), logpb_Initialized, logpb_is_any_dirty(), LSA_SET_NULL(), NULL, NULL_LSA, log_pb_global_data::num_buffers, log_pb_global_data::pages_area, log_append_info::prev_lsa, pthread_mutex_destroy, and log_append_info::set_nxio_lsa().
Referenced by log_create_internal(), log_final(), log_initialize_internal(), log_rv_outside_noop_redo(), logpb_delete(), logpb_find_header_parameters(), logpb_initialize_pool(), logpb_remove_all_in_log_path(), logpb_rename_all_volumes_files(), and logtb_define_trantable().
PGLENGTH logpb_find_header_parameters (THREAD_ENTRY * thread_p, const bool force_read_log_header, const char * db_fullname, const char * logpath, const char * prefix_logname, PGLENGTH * io_page_size, PGLENGTH * log_page_size, INT64 * db_creation, float * db_compatibility, int * db_charset)
Definition at line 2342 of file log_page_buffer.c.
References log_global::append, trantable::area, ARG_FILE_LINE, assert, log_header::db_charset, log_header::db_compatibility, log_header::db_creation, log_header::db_iopagesize, log_header::db_logpagesize, db_set_page_size(), ER_ERROR_SEVERITY, ER_LOG_INCOMPATIBLE_DATABASE, ER_LOG_INCOMPATIBLE_PREFIX_NAME, ER_NOTIFICATION_SEVERITY, er_set(), error(), log_global::hdr, if(), IO_MAX_PAGE_SIZE, IO_PAGESIZE, LOG_CS_OWN_WRITE_MODE(), log_Gl, log_Name_active, LOG_PAGESIZE, log_append_info::log_pgptr, logpb_fetch_header_from_active_log(), logpb_fetch_start_append_page(), logpb_finalize_pool(), logpb_initialize_pool(), logtb_define_trantable_log_latch(), MAX_ALIGNMENT, NO_ERROR, NULL, trantable::num_total_indices, log_header::prefix_name, PTR_ALIGN, REL_FULLY_COMPATIBLE, rel_get_disk_compatible(), rel_name(), rel_release_string(), and log_global::trantable.
Referenced by log_get_charset_from_header_page(), log_get_io_page_size(), and logpb_restore().
int logpb_find_oldest_available_arv_num (THREAD_ENTRY * thread_p)
Definition at line 11183 of file log_page_buffer.c.
References assert, fileio_is_volume_exist(), fileio_make_log_archive_name(), log_global::hdr, log_Archive_path, LOG_CS_OWN(), log_Gl, log_Prefix, log_header::nxarv_num, and thread_get_thread_entry_info().
Referenced by logpb_find_oldest_available_page_id().
LOG_PAGEID logpb_find_oldest_available_page_id (THREAD_ENTRY * thread_p)
Definition at line 11102 of file log_page_buffer.c.
References log_global::append, log_global::archive, log_page::area, ARG_FILE_LINE, assert, log_header::db_creation, log_arv_header::db_creation, difftime64, ER_ERROR_SEVERITY, ER_LOG_DOESNT_CORRESPOND_TO_DATABASE, ER_LOG_READ, er_set(), fileio_dismount(), fileio_make_log_archive_name(), fileio_mount(), fileio_read(), log_arv_header::fpageid, log_global::hdr, if(), IO_MAX_PAGE_SIZE, LOG_ARCHIVE_CS_ENTER, LOG_ARCHIVE_CS_EXIT, log_Archive_path, LOG_CS_OWN(), log_Db_fullname, LOG_DBLOG_ARCHIVE_VOLID, log_Gl, LOG_PAGESIZE, log_Prefix, LOG_RESTARTED, logpb_debug_check_log_page(), logpb_dismount_log_archive(), logpb_find_oldest_available_arv_num(), MAX_ALIGNMENT, NULL, NULL_PAGEID, NULL_VOLDES, log_header::nxarv_pageid, PTR_ALIGN, log_global::rcv_phase, thread_get_thread_entry_info(), log_archives::vdes, and log_append_info::vdes.
Referenced by logwr_log_ha_filestat_to_string().
bool logpb_find_volume_info_exist (void)
Definition at line 4632 of file log_page_buffer.c.
References fileio_is_volume_exist(), and log_Name_volinfo.
Referenced by boot_mount().
void logpb_flush_header (THREAD_ENTRY * thread_p)
Definition at line 1661 of file log_page_buffer.c.
References log_page::area, ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, er_log_debug, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), log_hdrpage::flags, log_logging_stat::flush_hdr_call_count, log_page::hdr, log_global::hdr, log_logging_stat::last_flush_hdr_sec_by_LFT, LOG_CS_OWN_WRITE_MODE(), log_Gl, LOG_PAGE_INIT_VALUE, LOG_PAGESIZE, log_global::loghdr_pgptr, log_hdrpage::logical_pageid, logpb_fatal_error(), LOGPB_HEADER_PAGE_ID, logpb_write_page_to_disk(), NULL, NULL_OFFSET, log_hdrpage::offset, and log_logging_stat::total_flush_hdr_sec_by_LFT.
Referenced by log_commit(), log_final(), log_initialize_internal(), log_recovery(), log_recovery_notpartof_archives(), log_recovery_redo(), log_recovery_resetlog(), log_recovery_undo(), logpb_archive_active_log(), logpb_backup(), logpb_checkpoint(), logpb_force_flush_header_and_pages(), logpb_next_append_page(), logpb_remove_archive_logs(), logpb_remove_archive_logs_exceed_limit(), logpb_rename_all_volumes_files(), and xlog_dump().
void logpb_flush_log_for_wal (THREAD_ENTRY * thread_p, const LOG_LSA * lsa_ptr)
Definition at line 4120 of file log_page_buffer.c.
References ARG_FILE_LINE, assert, er_log_debug, LOG_CS_ENTER(), LOG_CS_EXIT(), log_Gl, logpb_dump(), logpb_flush_pages_direct(), logpb_need_wal(), LSA_EQ(), LSA_ISNULL(), perfmon_inc_stat(), PSTAT_LOG_NUM_WALS, and log_global::rcv_phase_lsa.
Referenced by pgbuf_bcb_flush_with_wal(), pgbuf_flush_checkpoint(), pgbuf_flush_page_and_neighbors_fb(), and pgbuf_flush_victim_candidates().
int logpb_flush_page (THREAD_ENTRY * thread_p, LOG_PAGE * log_pgptr)
Definition at line 1042 of file log_page_buffer.c.
References ARG_FILE_LINE, assert, log_buffer::dirty, ER_FAILED, ER_FATAL_ERROR_SEVERITY, ER_LOG_FLUSHING_UNUPDATABLE, ER_LOG_PAGE_CORRUPTED, er_set(), ER_WARNING_SEVERITY, error(), LOG_CS_OWN_WRITE_MODE(), logpb_fatal_error(), logpb_get_log_buffer(), LOGPB_HEADER_PAGE_ID, LOGPB_LAST_ACTIVE_PAGE_ID, logpb_log, LOGPB_NEXT_ARCHIVE_PAGE_ID, logpb_to_physical_pageid(), logpb_write_page_to_disk(), NO_ERROR, NULL_PAGEID, log_buffer::pageid, and log_buffer::phy_pageid.
Referenced by log_create_internal(), and log_recovery_resetlog().
void logpb_flush_pages (THREAD_ENTRY * thread_p, LOG_LSA * flush_lsa)
Definition at line 3938 of file log_page_buffer.c.
References log_global::append, assert, log_logging_stat::async_commit_request_count, BO_IS_SERVER_RESTARTED, log_logging_stat::gc_commit_request_count, log_group_commit_info::gc_cond, log_group_commit_info::gc_mutex, log_append_info::get_nxio_lsa(), log_global::group_commit_info, LOG_CS_ENTER(), LOG_CS_EXIT(), LOG_CS_OWN_WRITE_MODE(), log_Gl, LOG_IS_GROUP_COMMIT_ACTIVE, log_is_log_flush_daemon_available(), log_wakeup_log_flush_daemon(), logpb_flush_pages_direct(), LSA_GE(), LSA_ISNULL(), LSA_LT(), NULL, pgbuf_has_perm_pages_fixed(), prm_get_bool_value(), PRM_ID_LOG_ASYNC_COMMIT, pthread_mutex_lock, pthread_mutex_unlock, rv, timeval_add_msec(), and timeval_to_timespec().
Referenced by log_2pc_append_decision(), log_2pc_append_start(), log_2pc_prepare_global_tran(), log_append_commit_postpone(), log_append_ha_server_state(), log_change_tran_as_completed(), and log_complete_for_2pc().
void logpb_flush_pages_direct (THREAD_ENTRY * thread_p)
Definition at line 3910 of file log_page_buffer.c.
References ARG_FILE_LINE, assert, log_logging_stat::direct_flush_count, er_log_debug, LOG_CS_OWN_WRITE_MODE(), logpb_flush_all_append_pages(), and logpb_prior_lsa_append_all_list().
Referenced by fi_handler_random_exit(), log_commit(), log_create_internal(), log_final(), log_is_log_flush_daemon_available(), log_recovery(), log_recovery_redo(), log_recovery_resetlog(), log_recovery_undo(), log_recreate(), log_rv_outside_noop_redo(), logpb_backup_for_volume(), logpb_checkpoint(), logpb_copy_database(), logpb_copy_volume(), logpb_fetch_start_append_page(), logpb_flush_log_for_wal(), logpb_flush_pages(), logpb_force_flush_header_and_pages(), logpb_force_flush_pages(), logpb_invalid_all_append_pages(), logpb_invalidate_pool(), logpb_rename_all_volumes_files(), and xlog_dump().
void logpb_force_flush_header_and_pages (THREAD_ENTRY * thread_p)
Definition at line 4062 of file log_page_buffer.c.
References LOG_CS_ENTER(), LOG_CS_EXIT(), logpb_flush_header(), and logpb_flush_pages_direct().
Referenced by boot_after_copydb().
void logpb_force_flush_pages (THREAD_ENTRY * thread_p)
Definition at line 4054 of file log_page_buffer.c.
References LOG_CS_ENTER(), LOG_CS_EXIT(), and logpb_flush_pages_direct().
Referenced by boot_create_all_volumes(), css_init(), disk_format(), disk_set_link(), disk_volume_expand(), heap_create_internal(), pgbuf_flush_victim_candidates(), xbtree_load_index(), xbtree_load_online_index(), and xvacuum().
int logpb_get_archive_number (THREAD_ENTRY * thread_p, LOG_PAGEID pageid)
Definition at line 4988 of file log_page_buffer.c.
References logpb_fetch_from_archive(), and NULL.
Referenced by log_recovery_resetlog(), logpb_backup(), logpb_remove_archive_logs(), logpb_remove_archive_logs_exceed_limit(), and xvacuum_dump().
LOG_PAGEID logpb_get_page_id (LOG_PAGE * log_pgptr)
Definition at line 1111 of file log_page_buffer.c.
References logpb_get_log_buffer(), and log_buffer::pageid.
Referenced by logpb_dump_information(), and logpb_flush_all_append_pages().
TDE_ALGORITHM logpb_get_tde_algorithm (const LOG_PAGE * log_pgptr)
Definition at line 11386 of file log_page_buffer.c.
References assert, log_hdrpage::flags, log_page::hdr, LOG_HDRPAGE_FLAG_ENCRYPTED_AES, LOG_HDRPAGE_FLAG_ENCRYPTED_ARIA, TDE_ALGORITHM_AES, TDE_ALGORITHM_ARIA, and TDE_ALGORITHM_NONE.
Referenced by logpb_fetch_from_archive(), logpb_read_page_from_active_log(), logpb_read_page_from_file(), logpb_start_append(), logpb_write_page_to_disk(), logpb_write_toflush_pages_to_archive(), and logpb_writev_append_pages().
void logpb_initialize_arv_page_info_table (void)
Definition at line 10808 of file log_page_buffer.c.
References ARV_LOG_PAGE_INFO_TABLE::rear.
Referenced by log_initialize_internal().
int logpb_initialize_header (THREAD_ENTRY * thread_p, LOG_HEADER * loghdr, const char * prefix_logname, DKNPAGES npages, INT64 * db_creation)
Definition at line 1308 of file log_page_buffer.c.
References log_header::append_lsa, ARG_FILE_LINE, assert, log_header::avg_nlocks, log_header::avg_ntrans, log_header::bkinfo, log_hdr_bkup_level_info::bkup_attime, log_header::bkup_level0_lsa, log_header::bkup_level1_lsa, log_header::bkup_level2_lsa, log_header::chkpt_lsa, CUBRID_MAGIC_LOG_ACTIVE, CUBRID_MAGIC_MAX_LENGTH, log_header::db_charset, log_header::db_compatibility, log_header::db_creation, log_header::db_iopagesize, log_header::db_logpagesize, log_header::db_release, log_header::eof_lsa, ER_FATAL_ERROR_SEVERITY, ER_LOG_COMPILATION_RELEASE, er_set(), FILEIO_BACKUP_UNDEFINED_LEVEL, log_header::fpageid, log_header::ha_file_status, log_header::ha_server_state, HA_SERVER_STATE_IDLE, log_header::has_logging_been_skipped, i, IO_PAGESIZE, log_header::is_shutdown, lang_charset(), log_header::last_arv_num_for_syscrashes, log_header::last_deleted_arv_num, LOG_CS_OWN_WRITE_MODE(), LOG_ESTIMATE_NACTIVE_TRANS, LOG_ESTIMATE_NOBJ_LOCKS, LOG_PAGESIZE, LOG_SYSTEM_TRANID, logpb_fatal_error(), logpb_initialize_backup_info(), logpb_vacuum_reset_log_header_cache(), LSA_COPY(), LSA_SET_NULL(), log_header::magic, log_header::mvcc_next_id, MVCCID_FIRST, log_header::next_trid, NO_ERROR, log_header::npages, NULL, log_header::nxarv_num, log_header::nxarv_pageid, log_header::nxarv_phy_pageid, log_lsa::offset, log_lsa::pageid, log_header::perm_status_obsolete, log_header::prefix_name, rel_disk_compatible(), REL_MAX_RELEASE_LENGTH, rel_release_string(), log_header::smallest_lsa_at_last_chkpt, strlen, strncpy_bufsize, and log_header::vacuum_last_blockid.
Referenced by log_create_internal(), log_initialize_internal(), logpb_copy_database(), and logpb_fetch_header_with_buffer().
int logpb_initialize_log_names (THREAD_ENTRY * thread_p, const char * db_fullname, const char * logpath, const char * prefix_logname)
Definition at line 6574 of file log_page_buffer.c.
References ARG_FILE_LINE, fileio_make_backup_volume_info_name(), fileio_make_log_active_name(), fileio_make_log_archive_temp_name(), fileio_make_log_info_name(), fileio_make_removed_log_archive_name(), fileio_make_volume_info_name(), log_Archive_path, log_Db_fullname, log_Name_active, log_Name_bg_archive, log_Name_bkupinfo, log_Name_info, log_Name_removed_archive, log_Name_volinfo, log_Path, log_Prefix, logpb_fatal_error(), logpb_verify_length(), NO_ERROR, and NULL.
Referenced by alterdbhost(), log_create_internal(), log_initialize_internal(), logpb_check_exist_any_volumes(), logpb_delete(), logpb_exist_log(), logpb_fetch_header_from_active_log(), logpb_remove_all_in_log_path(), and logpb_rename_all_volumes_files().
void logpb_initialize_logging_statistics (void)
Definition at line 10822 of file log_page_buffer.c.
Referenced by log_initialize_internal().
int logpb_initialize_pool (THREAD_ENTRY * thread_p)
Definition at line 548 of file log_page_buffer.c.
References ARG_FILE_LINE, assert, logpb_partial_append::buffer_log_page, log_pb_global_data::buffers, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), logwr_info::flush_end_cond, logwr_info::flush_end_mutex, logwr_info::flush_start_cond, logwr_info::flush_start_mutex, logwr_info::flush_wait_cond, logwr_info::flush_wait_mutex, free_and_init, log_group_commit_info::gc_cond, log_group_commit_info::gc_mutex, log_global::group_commit_info, log_pb_global_data::header_buffer, log_pb_global_data::header_page, i, IO_MAX_PAGE_SIZE, logwr_info::is_init, log_append_init_zip(), LOG_CS_OWN_WRITE_MODE(), log_Gl, LOG_PAGE_INIT_VALUE, logpb_partial_append::log_page_record_header, LOG_PAGESIZE, LOGPB_APPENDREC_SUCCESS, logpb_fatal_error(), logpb_finalize_pool(), logpb_initialize_flush_info(), logpb_initialize_log_buffer(), logpb_Initialized, logpb_Logging, MAX_ALIGNMENT, NO_ERROR, NULL, log_pb_global_data::num_buffers, log_pb_global_data::pages_area, log_pb_global_data::partial_append, prm_get_bool_value(), prm_get_integer_value(), PRM_ID_LOG_NBUFFERS, PRM_ID_LOGPB_LOGGING_DEBUG, pthread_mutex_init, PTR_ALIGN, logpb_partial_append::status, logwr_info::wr_list_mutex, and log_global::writer_info.
Referenced by log_create_internal(), log_initialize_internal(), logpb_delete(), logpb_find_header_parameters(), logpb_remove_all_in_log_path(), and logpb_rename_all_volumes_files().
void logpb_invalid_all_append_pages (THREAD_ENTRY * thread_p)
Definition at line 4079 of file log_page_buffer.c.
References log_global::append, assert, log_global::flush_info, LOG_CS_OWN_WRITE_MODE(), log_Gl, log_append_info::log_pgptr, logpb_flush_pages_direct(), logpb_log, NULL, log_flush_info::num_toflush, pthread_mutex_lock, pthread_mutex_unlock, rv, and log_flush_info::toflush.
Referenced by log_recovery_resetlog(), and logpb_fetch_start_append_page().
void logpb_invalidate_pool (THREAD_ENTRY * thread_p)
Definition at line 735 of file log_page_buffer.c.
References assert, log_buffer::dirty, i, LOG_CS_OWN_WRITE_MODE(), log_buffer::logpage, LOGPB_FIND_BUFPTR, logpb_flush_pages_direct(), logpb_initialize_log_buffer(), logpb_Initialized, NULL_PAGEID, log_pb_global_data::num_buffers, and log_buffer::pageid.
Referenced by log_recovery_resetlog().
bool logpb_is_page_in_archive (LOG_PAGEID pageid)
Definition at line 4957 of file log_page_buffer.c.
References LOGPB_IS_ARCHIVE_PAGE.
Referenced by log_do_postpone(), log_dump_record(), log_find_end_log(), log_recovery_analysis(), log_recovery_find_first_postpone(), log_recovery_redo(), log_rv_analysis_log_end(), log_startof_nxrec(), logpb_backup(), logpb_checkpoint(), logpb_is_smallest_lsa_in_archive(), logpb_read_page_from_file(), logpb_remove_archive_logs(), logpb_remove_archive_logs_exceed_limit(), logwr_log_ha_filestat_to_string(), xlog_dump(), and xvacuum_dump().
bool logpb_is_pool_initialized (void)
Definition at line 719 of file log_page_buffer.c.
References assert, LOG_CS_OWN_WRITE_MODE(), logpb_Initialized, and NULL.
Referenced by log_final(), log_rv_outside_noop_redo(), logpb_exist_log(), and logtb_define_trantable().
bool logpb_is_smallest_lsa_in_archive (THREAD_ENTRY * thread_p)
Definition at line 4970 of file log_page_buffer.c.
References logpb_is_page_in_archive(), logtb_find_smallest_lsa(), LSA_ISNULL(), and log_lsa::pageid.
VACUUM_LOG_BLOCKID logpb_last_complete_blockid (void)
Definition at line 11305 of file log_page_buffer.c.
References log_global::append, assert, log_Gl, LSA_ISNULL(), log_lsa::pageid, log_append_info::prev_lsa, vacuum_get_log_blockid(), and VACUUM_NULL_LOG_BLOCKID.
Referenced by logpb_remove_archive_logs_exceed_limit(), vacuum_data_load_and_recover(), and vacuum_sa_reflect_last_blockid().
bool logpb_need_wal (const LOG_LSA * lsa)
Definition at line 11050 of file log_page_buffer.c.
References log_global::append, log_append_info::get_nxio_lsa(), log_Gl, and LSA_LE().
Referenced by dwb_flush_block(), logpb_flush_log_for_wal(), and pgbuf_flush_victim_candidates().
int logpb_page_check_corruption (THREAD_ENTRY * thread_p, LOG_PAGE * log_pgptr, bool * is_page_corrupted)
Definition at line 11329 of file log_page_buffer.c.
References assert, logpb_page_has_valid_checksum(), NO_ERROR, and NULL.
Referenced by log_recovery_analysis(), and logpb_debug_check_log_page().
void logpb_page_get_first_null_block_lsa (THREAD_ENTRY * thread_p, LOG_PAGE * log_pgptr, LOG_LSA * first_null_block_lsa)
Definition at line 3151 of file log_page_buffer.c.
References assert, log_page::hdr, i, LOG_PAGE_INIT_VALUE, LOG_PAGESIZE, log_hdrpage::logical_pageid, LSA_SET_NULL(), MAX_ALIGNMENT, NULL, log_lsa::offset, ONE_K, log_lsa::pageid, and PTR_ALIGN.
Referenced by log_recovery_analysis().
int logpb_prior_lsa_append_all_list (THREAD_ENTRY * thread_p)
Definition at line 3067 of file log_page_buffer.c.
References assert, log_prior_lsa_info::list_size, LOG_CS_OWN_WRITE_MODE(), log_Gl, logpb_append_prior_lsa_list(), NO_ERROR, NULL, ONE_K, perfmon_add_stat(), perfmon_inc_stat(), log_global::prior_info, log_prior_lsa_info::prior_lsa_mutex, prior_lsa_remove_prior_list(), PSTAT_PRIOR_LSA_LIST_REMOVED, and PSTAT_PRIOR_LSA_LIST_SIZE.
Referenced by heap_get_visible_version_from_log(), logpb_fetch_page(), logpb_flush_pages_direct(), and prior_lsa_next_record_internal().
int logpb_read_page_from_active_log (THREAD_ENTRY * thread_p, LOG_PAGEID pageid, int num_pages, bool decrypt_needed, LOG_PAGE * log_pgptr)
Definition at line 2130 of file log_page_buffer.c.
References log_global::append, ARG_FILE_LINE, assert, ASSERT_ERROR, ER_ERROR_SEVERITY, ER_LOG_PAGE_CORRUPTED, ER_LOG_READ, er_set(), fileio_read_pages(), log_page::hdr, i, IO_MAX_PAGE_SIZE, tde_cipher::is_loaded, log_Gl, log_Name_active, LOG_PAGESIZE, LOG_RESTARTED, log_hdrpage::logical_pageid, LOGPB_ACTIVE_NPAGES, logpb_debug_check_log_page(), logpb_get_tde_algorithm(), logpb_log, logpb_to_physical_pageid(), MAX_ALIGNMENT, NO_ERROR, NULL, NULL_PAGEID, perfmon_inc_stat(), PSTAT_LOG_NUM_IOREADS, PTR_ALIGN, log_global::rcv_phase, TDE_ALGORITHM_NONE, tde_Cipher, tde_decrypt_log_page(), and log_append_info::vdes.
Referenced by logpb_archive_active_log(), and logpb_background_archiving().
int logpb_read_page_from_file (THREAD_ENTRY * thread_p, LOG_PAGEID pageid, LOG_CS_ACCESS_MODE access_mode, LOG_PAGE * log_pgptr)
Definition at line 1974 of file log_page_buffer.c.
References log_global::append, log_header::append_lsa, ARG_FILE_LINE, assert, ASSERT_ERROR, log_hdrpage::checksum, ER_FAILED, ER_FATAL_ERROR_SEVERITY, ER_LOG_PAGE_CORRUPTED, ER_LOG_READ, er_set(), error(), fileio_read(), log_page::hdr, log_global::hdr, LOG_CS_ENTER_READ_MODE(), LOG_CS_EXIT(), LOG_CS_OWN(), LOG_CS_SAFE_READER, log_Gl, LOG_ISRESTARTED, log_Name_active, LOG_PAGESIZE, LOG_RESTARTED, log_hdrpage::logical_pageid, LOGPB_ACTIVE_NPAGES, logpb_debug_check_log_page(), logpb_fetch_from_archive(), logpb_get_tde_algorithm(), logpb_is_page_in_archive(), logpb_log, logpb_to_physical_pageid(), NO_ERROR, NULL, NULL_PAGEID, log_lsa::pageid, perfmon_inc_stat(), log_buffer::phy_pageid, PSTAT_LOG_NUM_IOREADS, log_global::rcv_phase, TDE_ALGORITHM_NONE, tde_decrypt_log_page(), TT_VACUUM_MASTER, VACUUM_ER_LOG_ARCHIVES, vacuum_er_log_error, VACUUM_ER_LOG_MASTER, log_append_info::vdes, and log_header::was_active_log_reset.
Referenced by log_create_internal(), logpb_copy_page(), logpb_copy_page_from_file(), and logpb_locate_page().
int logpb_recreate_volume_info (THREAD_ENTRY * thread_p)
Definition at line 4691 of file log_page_buffer.c.
References DB_PERMANENT_DATA_PURPOSE, disk_get_link(), DISK_UNKNOWN_PURPOSE, ER_FAILED, error(), log_Db_fullname, LOG_DBFIRST_VOLID, LOG_DBLOG_ACTIVE_VOLID, LOG_DBLOG_BKUPINFO_VOLID, LOG_DBLOG_INFO_VOLID, log_Name_active, log_Name_bkupinfo, log_Name_info, log_Name_volinfo, logpb_add_volume(), logpb_create_volume_info(), NO_ERROR, NULL, and NULL_VOLID.
Referenced by boot_find_rest_permanent_volumes(), disk_rv_undo_format(), and log_recovery_notpartof_volumes().
int logpb_remove_all_in_log_path (THREAD_ENTRY * thread_p, const char * db_fullname, const char * logpath, const char * prefix_logname)
Definition at line 11223 of file log_page_buffer.c.
References log_global::append, er_clear(), fileio_dismount(), fileio_is_volume_exist(), fileio_make_log_archive_name(), fileio_mount(), fileio_unformat(), i, IO_MAX_PAGE_SIZE, log_header::last_deleted_arv_num, log_Archive_path, LOG_DBLOG_ACTIVE_VOLID, log_Gl, log_Name_active, log_Name_bg_archive, log_Name_info, log_Name_removed_archive, log_Prefix, logpb_fetch_header_with_buffer(), logpb_finalize_pool(), logpb_initialize_log_names(), logpb_initialize_pool(), logpb_Initialized, MAX_ALIGNMENT, NO_ERROR, NULL, NULL_VOLDES, prm_get_bool_value(), PRM_ID_LOG_BACKGROUND_ARCHIVING, PTR_ALIGN, and log_append_info::vdes.
Referenced by boot_restart_server().
void logpb_remove_archive_logs (THREAD_ENTRY * thread_p, const char * info_reason)
Definition at line 6123 of file log_page_buffer.c.
References _er_log_debug(), log_global::archive, ARG_FILE_LINE, assert, log_header::chkpt_lsa, fileio_synchronize_all(), log_global::hdr, log_header::last_arv_num_for_syscrashes, log_header::last_deleted_arv_num, LOG_CS_OWN_WRITE_MODE(), log_Gl, logpb_dismount_log_archive(), logpb_flush_header(), logpb_get_archive_number(), logpb_is_page_in_archive(), LOGPB_NEXT_ARCHIVE_PAGE_ID, logpb_remove_archive_logs_internal(), LSA_COPY(), LSA_ISNULL(), LSA_LT(), NO_ERROR, NULL, NULL_OFFSET, NULL_PAGEID, NULL_VOLDES, log_header::nxarv_num, log_lsa::offset, log_lsa::pageid, pgbuf_flush_checkpoint(), log_global::run_nxchkpt_atpageid, vacuum_is_safe_to_remove_archives(), vacuum_min_log_pageid_to_keep(), and log_archives::vdes.
Referenced by logpb_backup().
int logpb_remove_archive_logs_exceed_limit (THREAD_ENTRY * thread_p, int max_count)
Definition at line 5960 of file log_page_buffer.c.
References _er_log_debug(), ARG_FILE_LINE, assert, ER_LOG_MAX_ARCHIVES_HAS_BEEN_EXCEEDED, ER_NOTIFICATION_SEVERITY, er_set(), log_global::hdr, log_header::last_arv_num_for_syscrashes, log_header::last_deleted_arv_num, LOG_CS_ENTER(), LOG_CS_EXIT(), log_Gl, logpb_flush_header(), logpb_get_archive_number(), logpb_is_page_in_archive(), logpb_last_complete_blockid(), logpb_remove_archive_logs_internal(), LSA_ISNULL(), MSGCAT_CATALOG_CUBRID, MSGCAT_LOG_MAX_ARCHIVES_HAS_BEEN_EXCEEDED, msgcat_message(), MSGCAT_SET_LOG, log_header::mvcc_op_log_lsa, NULL, NULL_PAGEID, log_header::nxarv_num, prm_get_bool_value(), prm_get_integer_value(), PRM_ID_DEBUG_LOG_ARCHIVES, PRM_ID_FORCE_REMOVE_LOG_ARCHIVES, PRM_ID_LOG_MAX_ARCHIVES, vacuum_er_log, VACUUM_ER_LOG_ARCHIVES, VACUUM_IS_ER_LOG_LEVEL_SET, vacuum_is_safe_to_remove_archives(), log_header::vacuum_last_blockid, and vacuum_min_log_pageid_to_keep().
Referenced by log_is_log_flush_daemon_available(), and logpb_archive_active_log().
int logpb_rename_all_volumes_files (THREAD_ENTRY * thread_p, VOLID num_perm_vols, const char * to_db_fullname, const char * to_logpath, const char * to_prefix_logname, const char * toext_path, const char * fileof_vols_and_renamepaths, bool extern_rename, bool force_delete)
Definition at line 9649 of file log_page_buffer.c.
References log_global::append, log_global::archive, ARG_FILE_LINE, log_global::bg_archive_info, log_header::bkup_level0_lsa, log_header::bkup_level1_lsa, log_header::bkup_level2_lsa, boot_db_full_name(), log_header::chkpt_lsa, log_header::db_creation, DB_PERMANENT_DATA_PURPOSE, DISK_DONT_FLUSH, DISK_FLUSH, disk_set_creation(), disk_set_link(), DISK_UNKNOWN_PURPOSE, ER_ERROR_SEVERITY, ER_FAILED, ER_LOG_MOUNT_FAIL, er_set(), er_set_with_oserror(), ER_TM_CROSS_DEVICE_LINK, ER_TM_GET_STAT_FAIL, ER_TM_IS_NOT_WRITEABLE, error(), fileio_dismount(), fileio_finalize_backup_info(), fileio_find_next_perm_volume(), fileio_find_previous_perm_volume(), FILEIO_FIRST_BACKUP_VOL_INFO, fileio_get_volume_descriptor(), fileio_get_volume_label(), fileio_is_volume_exist(), fileio_make_backup_volume_info_name(), fileio_make_log_active_name(), fileio_make_log_archive_name(), fileio_make_log_info_name(), fileio_mount(), fileio_read_backup_info_entries(), fileio_remove_all_backup(), fileio_rename(), FILEIO_SYNC_ALSO_FLUSH_DWB, fileio_synchronize(), fileio_unformat(), free_and_init, log_global::hdr, i, log_header::last_arv_num_for_syscrashes, log_header::last_deleted_arv_num, log_Archive_path, log_Db_fullname, LOG_DBFIRST_VOLID, LOG_DBLOG_ACTIVE_VOLID, LOG_DBLOG_BKUPINFO_VOLID, LOG_DBTDE_KEYS_VOLID, log_dump_log_info(), log_Gl, log_Name_active, log_Name_bg_archive, log_Name_bkupinfo, log_Name_info, log_Name_removed_archive, log_Name_volinfo, log_Prefix, logpb_add_volume(), logpb_create_log_info(), logpb_create_volume_info(), logpb_dismount_log_archive(), logpb_fetch_start_append_page(), logpb_finalize_pool(), logpb_flush_header(), logpb_flush_pages_direct(), logpb_initialize_log_names(), logpb_initialize_pool(), logpb_next_where_path(), logpb_start_where_path(), logpb_verify_length(), LSA_SET_NULL(), MSGCAT_CATALOG_CUBRID, MSGCAT_LOG_LOGINFO_ACTIVE, MSGCAT_LOG_LOGINFO_COMMENT_FROM_RENAMED, msgcat_message(), MSGCAT_SET_LOG, NO_ERROR, log_header::npages, NULL, NULL_VOLDES, NULL_VOLID, log_header::nxarv_num, PEEK, pgbuf_flush_all(), pgbuf_invalidate_all, log_header::prefix_name, prm_get_bool_value(), PRM_ID_LOG_BACKGROUND_ARCHIVING, tde_make_keys_file_fullname(), log_archives::vdes, background_archiving_info::vdes, and log_append_info::vdes.
Referenced by xboot_soft_rename().
int logpb_restore (THREAD_ENTRY * thread_p, const char * db_fullname, const char * logpath, const char * prefix_logname, bo_restart_arg * r_args)
Definition at line 8273 of file log_page_buffer.c.
References log_global::append, ARG_FILE_LINE, assert, ASSERT_ERROR_AND_SET, fileio_backup_record_info::at_time, bo_restart_arg::backuppath, io_backup_session::bkup, fileio_backup_buffer::bkuphdr, boot_db_full_name(), boot_db_name(), CEIL_PTVDIV, fileio_backup_header::chkpt_lsa, CTIME_MAX, fileio_backup_buffer::current_path, db_set_page_size(), io_backup_session::dbfile, fileio_backup_buffer::dtype, fileio_backup_header::end_time, er_errid(), ER_ERROR_SEVERITY, ER_FAILED, ER_FATAL_ERROR_SEVERITY, ER_GENERIC_ERROR, ER_LOG_BKUP_INCOMPATIBLE, ER_LOG_CANNOT_ACCESS_BACKUP, ER_LOG_MAYNEED_MEDIA_RECOVERY, er_set(), ER_TDE_INVALID_KEYS_FILE, error(), fileio_abort_restore(), fileio_add_volume_to_backup_info(), FILEIO_BACKUP_FULL_LEVEL, FILEIO_BACKUP_UNDEFINED_LEVEL, FILEIO_BACKUP_VOL_DEVICE, fileio_clear_backup_info_level(), fileio_dismount(), fileio_finalize_backup_info(), fileio_finish_restore(), FILEIO_FIRST_BACKUP_VOL_INFO, fileio_get_backup_volume(), fileio_get_base_file_name(), fileio_get_directory_path(), fileio_get_next_restore_file(), FILEIO_INITIAL_BACKUP_UNITS, fileio_is_volume_exist(), fileio_make_backup_name(), fileio_make_backup_volume_info_name(), fileio_make_temp_log_files_from_backup(), fileio_mount(), FILEIO_NO_BACKUP_UNITS, fileio_page_bitmap_create(), fileio_page_bitmap_list_add(), fileio_page_bitmap_list_destroy(), fileio_page_bitmap_list_find(), fileio_page_bitmap_list_init(), fileio_restore_volume(), FILEIO_SECOND_BACKUP_VOL_INFO, fileio_skip_restore_volume(), fileio_start_restore(), fileio_write_backup_info_entries(), IO_PAGESIZE, bo_restart_arg::keys_file_path, fileio_backup_buffer::last_chkpt_lsa, bo_restart_arg::level, LOG_CS_ENTER(), LOG_CS_EXIT(), LOG_DBFIRST_VOLID, LOG_DBLOG_ACTIVE_VOLID, LOG_DBLOG_ARCHIVE_VOLID, LOG_DBLOG_BKUPINFO_VOLID, LOG_DBLOG_INFO_VOLID, LOG_DBTDE_KEYS_VOLID, LOG_DBVOLINFO_VOLID, log_Gl, log_Name_active, log_Name_bkupinfo, LOG_PAGESIZE, fileio_backup_buffer::log_path, logpb_check_stop_at_time(), logpb_fatal_error(), logpb_find_header_parameters(), logpb_is_log_active_from_backup_useful(), logtb_define_trantable_log_latch(), LSA_COPY(), MSGCAT_CATALOG_CUBRID, MSGCAT_LOG_READ_ERROR_DURING_RESTORE, msgcat_message(), MSGCAT_SET_LOG, fileio_backup_buffer::name, fileio_backup_db_buffer::nbytes, bo_restart_arg::newvolpath, NO_ERROR, NULL, NULL_VOLDES, os_rename_file(), fileio_backup_header::previnfo, bo_restart_arg::printtoc, REL_BACKWARD_COMPATIBLE, rel_disk_compatible(), REL_FULLY_COMPATIBLE, rel_get_disk_compatible(), rel_name(), rel_release_string(), bo_restart_arg::restore_upto_bktime, fileio_backup_header::start_time, bo_restart_arg::stopat, strncpy_bufsize, success(), tde_make_keys_file_fullname(), tde_validate_keys_file(), fileio_backup_header::unit_num, log_append_info::vdes, bo_restart_arg::verbose_file, io_backup_session::verbose_fp, fileio_backup_buffer::vlabel, and fileio_backup_db_buffer::volid.
Referenced by boot_restart_server().
int logpb_scan_volume_info (THREAD_ENTRY * thread_p, const char * db_fullname, VOLID ignore_volid, VOLID start_volid, int(*)(THREAD_ENTRY *thread_p, VOLID xvolid, const char *vlabel, void *args) fun, void * args)
Definition at line 4815 of file log_page_buffer.c.
References ARG_FILE_LINE, ER_BO_CANNOT_FINE_VOLINFO, ER_BO_UNSORTED_VOLINFO, ER_ERROR_SEVERITY, er_set(), ER_WARNING_SEVERITY, fileio_make_volume_info_name(), LOG_DBFIRST_VOLID, log_Name_volinfo, NO_ERROR, NULL, and NULL_VOLID.
Referenced by boot_find_rest_permanent_volumes().
void logpb_set_dirty (THREAD_ENTRY * thread_p, LOG_PAGE * log_pgptr)
Definition at line 922 of file log_page_buffer.c.
References ARG_FILE_LINE, log_buffer::dirty, ER_LOG_FLUSHING_UNUPDATABLE, er_set(), ER_WARNING_SEVERITY, logpb_get_log_buffer(), LOGPB_HEADER_PAGE_ID, LOGPB_LAST_ACTIVE_PAGE_ID, logpb_log, LOGPB_NEXT_ARCHIVE_PAGE_ID, and log_buffer::pageid.
Referenced by log_create_internal(), log_recovery_resetlog(), logpb_end_append(), logpb_next_append_page(), and logpb_start_append().
int logpb_set_page_checksum (THREAD_ENTRY * thread_p, LOG_PAGE * log_pgptr)
Definition at line 490 of file log_page_buffer.c.
References assert, log_hdrpage::checksum, log_page::hdr, log_hdrpage::logical_pageid, logpb_compute_page_checksum(), logpb_log, NO_ERROR, and NULL.
Referenced by logpb_archive_active_log(), logpb_copy_database(), logpb_write_page_to_disk(), logpb_writev_append_pages(), and logwr_log_ha_filestat_to_string().
void logpb_set_tde_algorithm (THREAD_ENTRY * thread_p, LOG_PAGE * log_pgptr, const TDE_ALGORITHM tde_algo)
Definition at line 11414 of file log_page_buffer.c.
References assert, log_hdrpage::flags, log_page::hdr, tde_cipher::is_loaded, LOG_HDRPAGE_FLAG_ENCRYPTED_AES, LOG_HDRPAGE_FLAG_ENCRYPTED_ARIA, LOG_HDRPAGE_FLAG_ENCRYPTED_MASK, TDE_ALGORITHM_AES, TDE_ALGORITHM_ARIA, TDE_ALGORITHM_NONE, and tde_Cipher.
Referenced by logpb_next_append_page(), logpb_start_append(), logpb_write_page_to_disk(), logpb_write_toflush_pages_to_archive(), and logpb_writev_append_pages().
LOG_PHY_PAGEID logpb_to_physical_pageid (LOG_PAGEID logical_pageid)
Definition at line 4912 of file log_page_buffer.c.
References assert, LOGPB_ACTIVE_NPAGES, LOGPB_FIRST_ACTIVE_PAGE_ID, LOGPB_HEADER_PAGE_ID, LOGPB_PHYSICAL_HEADER_PAGE_ID, PAGEID_MAX, and log_buffer::phy_pageid.
Referenced by log_recovery_resetlog(), logpb_archive_active_log(), logpb_copy_database(), logpb_fetch_header_from_active_log(), logpb_flush_page(), logpb_locate_page(), logpb_read_page_from_active_log(), logpb_read_page_from_file(), and logpb_write_page_to_disk().
void logpb_vacuum_reset_log_header_cache (THREAD_ENTRY * thread_p, LOG_HEADER * loghdr)
Definition at line 11290 of file log_page_buffer.c.
References log_header::does_block_need_vacuum, LSA_SET_NULL(), log_header::mvcc_op_log_lsa, MVCCID_FIRST, MVCCID_NULL, log_header::newest_block_mvccid, log_header::oldest_visible_mvccid, vacuum_er_log, and VACUUM_ER_LOG_VACUUM_DATA.
Referenced by log_recovery_redo(), logpb_initialize_header(), vacuum_recover_lost_block_data(), vacuum_rv_redo_vacuum_complete(), and xvacuum().
int logpb_write_page_to_disk (THREAD_ENTRY * thread_p, LOG_PAGE * log_pgptr, LOG_PAGEID logical_pageid)
Definition at line 2239 of file log_page_buffer.c.
References log_global::append, ARG_FILE_LINE, assert, log_header::db_logpagesize, dwb_is_created(), er_errid(), ER_ERROR_SEVERITY, ER_FAILED, ER_FATAL_ERROR_SEVERITY, ER_IO_WRITE_OUT_OF_SPACE, ER_LOG_WRITE, ER_LOG_WRITE_OUT_OF_SPACE, er_set(), er_set_with_oserror(), ER_TDE_ENCRYPTION_LOGPAGE_ERORR_AND_OFF_TDE, fileio_write(), FILEIO_WRITE_DEFAULT_WRITE, FILEIO_WRITE_NO_COMPENSATE_WRITE, log_page::hdr, log_global::hdr, IO_MAX_PAGE_SIZE, log_Gl, LOG_IS_PAGE_TDE_ENCRYPTED, log_Name_active, LOG_PAGESIZE, log_hdrpage::logical_pageid, logpb_fatal_error(), logpb_get_tde_algorithm(), LOGPB_HEADER_PAGE_ID, LOGPB_IS_ARCHIVE_PAGE, LOGPB_LAST_ACTIVE_PAGE_ID, logpb_log, logpb_set_page_checksum(), logpb_set_tde_algorithm(), logpb_to_physical_pageid(), MAX_ALIGNMENT, NO_ERROR, NULL, perfmon_inc_stat(), log_buffer::phy_pageid, PSTAT_LOG_NUM_IOWRITES, PTR_ALIGN, TDE_ALGORITHM_NONE, tde_encrypt_log_page(), and log_append_info::vdes.
Referenced by log_recovery_analysis(), logpb_flush_all_append_pages(), logpb_flush_header(), logpb_flush_page(), and logpb_locate_page().
bool logtb_am_i_dba_client (THREAD_ENTRY * thread_p)
Definition at line 751 of file log_tran_table.c.
References logtb_find_current_client_name(), and NULL.
Referenced by logtb_check_kill_tran_auth(), and net_server_request().
int logtb_assign_tran_index (THREAD_ENTRY * thread_p, TRANID trid, TRAN_STATE state, const BOOT_CLIENT_CREDENTIAL * client_credential, TRAN_STATE * current_state, int wait_msecs, TRAN_ISOLATION isolation)
Definition at line 792 of file log_tran_table.c.
References LOG_SET_CURRENT_TRAN_INDEX, LOG_SYSTEM_TRAN_INDEX, logtb_allocate_tran_index(), NULL, NULL_TRAN_INDEX, thread_get_thread_entry_info(), TR_TABLE_CS_ENTER, and TR_TABLE_CS_EXIT.
Referenced by boot_create_all_volumes(), boot_restart_server(), cubload::load_task::execute(), log_complete_for_2pc(), and xboot_register_client().
bool logtb_check_class_for_rr_isolation_err (const OID * class_oid)
Definition at line 5645 of file log_tran_table.c.
References assert, NULL, OID_CACHE_DB_ROOT_CLASS_ID, OID_CACHE_TRIGGER_CLASS_ID, OID_CACHE_USER_CLASS_ID, oid_check_cached_class_oid(), and OID_ISNULL.
Referenced by locator_lock_and_get_object_internal().
void logtb_clear_tdes (THREAD_ENTRY * thread_p, LOG_TDES * tdes)
Definition at line 1484 of file log_tran_table.c.
References log_rcv_tdes::analysis_last_aborted_sysop_lsa, log_rcv_tdes::analysis_last_aborted_sysop_start_lsa, log_tdes::append_repl_recidx, assert, log_rcv_tdes::atomic_sysop_start_lsa, log_tdes::bind_history, BOOT_WRITE_ON_STANDY_CLIENT_TYPE, tx_transient_class_registry::clear(), multi_index_unique_stats::clear(), log_tdes::client, clientids::client_type, log_tdes::coord, log_tdes::cur_repl_record, db_change_private_heap(), db_Disable_modifications, db_private_free_and_init, db_value_clear(), log_tdes::disable_modifications, log_tdes::first_save_entry, log_tdes::fl_mark_repl_recidx, free_and_init, log_tdes::gtrid, log_tdes::gtrinfo, log_tdes::has_deadlock_priority, log_tdes::head_lsa, i, mvcc_info::id, log_2pc_gtrinfo::info_data, log_2pc_gtrinfo::info_length, log_tdes::interrupt, log_tdes::isloose_end, log_topops_stack::last, log_2pc_free_coord_info(), LOG_2PC_NULL_GTRID, log_Gl, log_tdes::log_upd_stats, logtb_tran_clear_update_stats(), LSA_SET_NULL(), log_tdes::m_log_postpone_cache, log_tdes::m_modified_classes, log_tdes::m_multiupd_stats, MAX_NUM_EXEC_QUERY_HISTORY, MVCCID_NULL, log_tdes::mvccinfo, NULL, log_tdes::num_exec_queries, trantable::num_interrupts, log_tdes::num_log_records_written, log_tdes::posp_nxlsa, log_tdes::query_start_time, log_tdes::query_timeout, log_tdes::rcv, log_tdes::repl_insert_lsa, log_tdes::repl_records, log_tdes::repl_update_lsa, log_postpone_cache::reset(), log_tdes::savept_lsa, db_value_array::size, log_tdes::state, log_tdes::suppress_replication, log_rcv_tdes::sysop_start_postpone_lsa, log_tdes::tail_lsa, log_tdes::tail_topresult_lsa, log_tdes::topop_lsa, log_tdes::topops, TR_TABLE_CS_ENTER, TR_TABLE_CS_EXIT, log_tdes::tran_abort_reason, TRAN_ACTIVE, TRAN_NORMAL, log_rcv_tdes::tran_start_postpone_lsa, log_tdes::tran_start_time, log_global::trantable, log_tdes::undo_nxlsa, db_value_array::vals, log_tdes::waiting_for_res, log_tdes::xasl_id, and XASL_ID_SET_NULL.
Referenced by log_complete(), log_complete_for_2pc(), log_rv_analysis_end_checkpoint(), logpb_checkpoint(), logtb_allocate_tran_index(), logtb_finalize_tdes(), logtb_free_tran_index(), logtb_get_new_tran_id(), logtb_initialize_system_tdes(), and systdes_retire_tdes().
void logtb_complete_mvcc (THREAD_ENTRY * thread_p, LOG_TDES * tdes, bool committed)
Definition at line 3978 of file log_tran_table.c.
References assert, BTID_INITIALIZER, BTID_IS_NULL, mvcctable::complete_mvcc(), mvcc_info::id, LOG_FIND_THREAD_TRAN_INDEX, log_Gl, log_tdes::log_upd_stats, logtb_tran_clear_update_stats(), logtb_tran_find_btid_stats(), logtb_tran_reset_count_optim_state(), logtb_tran_update_all_global_unique_stats(), logtb_update_global_unique_stats_by_delta(), log_global::mvcc_table, MVCCID_IS_VALID, MVCCID_NULL, log_tdes::mvccinfo, NO_ERROR, NULL, log_unique_stats::num_keys, log_unique_stats::num_nulls, log_unique_stats::num_oids, perfmon_add_stat(), perfmon_is_perf_tracking(), PSTAT_LOG_TRAN_COMPLETE_TIME_COUNTERS, mvcc_info::recent_snapshot_lowest_active_mvccid, mvcc_info::reset(), mvcctable::reset_transaction_lowest_active(), mvcc_info::snapshot, log_tran_btid_unique_stats::tran_stats, tsc_elapsed_time_usec(), tsc_getticks(), and mvcc_snapshot::valid.
Referenced by log_abort_local(), log_commit_local(), and test_new_mvcc_complete().
void logtb_complete_sub_mvcc (THREAD_ENTRY * thread_p, LOG_TDES * tdes)
Definition at line 4569 of file log_tran_table.c.
References assert, mvcctable::complete_sub_mvcc(), mvcc_snapshot::highest_completed_mvccid, log_Gl, mvcc_snapshot::m_active_mvccs, log_global::mvcc_table, MVCCID_FORWARD, log_tdes::mvccinfo, NULL, mvcc_active_tran::set_inactive_mvccid(), mvcc_info::snapshot, mvcc_info::sub_ids, and mvcc_snapshot::valid.
Referenced by qexec_execute_selupd_list().
int logtb_count_clients (THREAD_ENTRY * thread_p)
Definition at line 1933 of file log_tran_table.c.
References trantable::all_tdes, BOOT_NORMAL_CLIENT_TYPE, log_tdes::client, clientids::client_type, cubregex::count(), i, log_Gl, NULL, NULL_TRANID, trantable::num_total_indices, TR_TABLE_CS_ENTER_READ_MODE, TR_TABLE_CS_EXIT, log_global::trantable, and log_tdes::trid.
Referenced by css_change_ha_server_state(), and css_check_ha_server_state_for_client().
int logtb_count_not_allowed_clients_in_maintenance_mode (THREAD_ENTRY * thread_p)
Definition at line 1963 of file log_tran_table.c.
References trantable::all_tdes, boot_Host_name, BOOT_IS_ALLOWED_CLIENT_TYPE_IN_MT_MODE, log_tdes::client, clientids::client_type, cubregex::count(), clientids::get_host_name(), i, log_Gl, NULL, NULL_TRANID, trantable::num_total_indices, TR_TABLE_CS_ENTER_READ_MODE, TR_TABLE_CS_EXIT, log_global::trantable, and log_tdes::trid.
Referenced by css_change_ha_server_state().
void logtb_define_trantable (THREAD_ENTRY * thread_p, int num_expected_tran_indices, int num_expected_locks)
Definition at line 362 of file log_tran_table.c.
References LOG_CS_ENTER(), LOG_CS_EXIT(), LOG_SET_CURRENT_TRAN_INDEX, LOG_SYSTEM_TRAN_INDEX, logpb_finalize_pool(), logpb_is_pool_initialized(), logtb_define_trantable_log_latch(), TR_TABLE_CS_ENTER, and TR_TABLE_CS_EXIT.
Referenced by boot_remove_all_volumes(), boot_restart_server(), and xboot_emergency_patch().
int logtb_define_trantable_log_latch (THREAD_ENTRY * thread_p, int num_expected_tran_indices)
Definition at line 396 of file log_tran_table.c.
References trantable::area, ARG_FILE_LINE, assert, ER_FATAL_ERROR_SEVERITY, ER_LOG_UNKNOWN_TRANINDEX, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), file_manager_init(), mvcctable::initialize(), lock_initialize(), LOG_CS_OWN_WRITE_MODE(), LOG_ESTIMATE_NACTIVE_TRANS, log_Gl, LOG_RESTARTED, LOG_SET_CURRENT_TRAN_INDEX, LOG_SYSTEM_TRAN_INDEX, logpb_fatal_error(), logtb_expand_trantable(), logtb_initialize_system_tdes(), logtb_initialize_trantable(), logtb_set_number_of_assigned_tran_indices(), logtb_undefine_trantable(), MAX_NTRANS, log_global::mvcc_table, NO_ERROR, NULL, pgbuf_initialize(), log_global::rcv_phase, and log_global::trantable.
Referenced by log_get_io_page_size(), log_initialize_internal(), logpb_delete(), logpb_find_header_parameters(), logpb_restore(), and logtb_define_trantable().
int logtb_delete_global_unique_stats (THREAD_ENTRY * thread_p, BTID * btid)
Definition at line 5025 of file log_tran_table.c.
References assert, BTID_IS_NULL, error(), lf_hash_delete(), log_Gl, NO_ERROR, NULL, vpid::pageid, pgbuf_is_page_fixed_by_thread(), btid::root_pageid, thread_get_tran_entry(), THREAD_TS_GLOBAL_UNIQUE_STATS, global_unique_stats_table::unique_stats_hash, log_global::unique_stats_table, btid::vfid, vpid::volid, and vfid::volid.
Referenced by btree_rv_remove_unique_stats(), and xbtree_load_index().
int logtb_descriptors_start_scan (THREAD_ENTRY * thread_p, int type, DB_VALUE ** arg_values, int arg_cnt, void ** ctx)
Definition at line 5178 of file log_tran_table.c.
References trantable::all_tdes, log_tdes::append_repl_recidx, assert, boot_client_type_to_string(), CACHE_TIME_AS_ARGS, log_tdes::client, log_tdes::client_id, clientids::client_type, log_tdes::cur_repl_record, db_localdatetime_msec(), db_make_datetime(), db_make_int(), db_make_null(), db_make_string(), db_make_string_copy(), log_tdes::disable_modifications, tx_transient_class_registry::empty(), multi_index_unique_stats::empty(), er_errid(), error(), file_get_tran_num_temp_files(), log_tdes::first_save_entry, log_tdes::fl_mark_repl_recidx, clientids::get_client_info(), clientids::get_db_user(), clientids::get_host_name(), clientids::get_login_name(), clientids::get_program_name(), log_tdes::has_deadlock_priority, log_tdes::head_lsa, i, log_tdes::interrupt, log_tdes::isloose_end, log_tdes::isolation, log_topops_stack::last, log_Gl, log_isolation_string(), log_state_short_string(), lsa_to_string(), log_tdes::m_modified_classes, log_tdes::m_multiupd_stats, log_tdes::max_unique_btrees, db_value::need_clear, NO_ERROR, NULL, NULL_TRANID, log_tdes::num_repl_records, NUM_TOTAL_TRAN_INDICES, log_tdes::num_transient_classnames, log_tdes::num_unique_btrees, log_tdes::posp_nxlsa, cubmem::PRIVATE_BLOCK_ALLOCATOR, clientids::process_id, log_tdes::query_start_time, log_tdes::query_timeout, string_buffer::release_ptr(), log_tdes::repl_insert_lsa, log_tdes::repl_records, log_tdes::repl_update_lsa, log_tdes::savept_lsa, xasl_id::sha1, SHA1_AS_ARGS, showstmt_alloc_array_context(), showstmt_alloc_tuple_in_context(), showstmt_free_array_context(), log_tdes::state, log_tdes::suppress_replication, log_tdes::tail_lsa, log_tdes::tail_topresult_lsa, xasl_id::time_stored, tx_transient_class_registry::to_string(), multi_index_unique_stats::to_string(), log_tdes::topop_lsa, log_tdes::topops, TR_TABLE_CS_ENTER_READ_MODE, TR_TABLE_CS_EXIT, log_tdes::tran_abort_reason, tran_abort_reason_to_string(), log_tdes::tran_index, log_tdes::tran_start_time, log_global::trantable, log_tdes::trid, log_tdes::undo_nxlsa, log_tdes::wait_msecs, log_tdes::waiting_for_res, log_tdes::xasl_id, XASL_ID_COPY, and XASL_ID_IS_NULL.
Referenced by showstmt_scan_init().
void logtb_disable_update (THREAD_ENTRY * thread_p)
Definition at line 3131 of file log_tran_table.c.
References ARG_FILE_LINE, db_Disable_modifications, and er_log_debug.
Referenced by boot_restart_server(), css_change_ha_server_state(), css_check_ha_server_state_for_client(), and css_notify_ha_log_applier_state().
void logtb_enable_update (THREAD_ENTRY * thread_p)
Definition at line 3142 of file log_tran_table.c.
References ARG_FILE_LINE, db_Disable_modifications, er_log_debug, prm_get_bool_value(), and PRM_ID_READ_ONLY_MODE.
Referenced by css_change_ha_server_state(), and css_notify_ha_log_applier_state().
void logtb_finalize_global_unique_stats_table (THREAD_ENTRY * thread_p)
Definition at line 4745 of file log_tran_table.c.
References global_unique_stats_table::initialized, lf_freelist_destroy(), lf_hash_destroy(), log_Gl, global_unique_stats_table::unique_stats_freelist, global_unique_stats_table::unique_stats_hash, and log_global::unique_stats_table.
Referenced by boot_restart_server(), and boot_server_all_finalize().
void logtb_finalize_tdes (THREAD_ENTRY * thread_p, LOG_TDES * tdes)
Definition at line 1696 of file log_tran_table.c.
References assert, free_and_init, log_topops_stack::last, log_tdes::log_upd_stats, logtb_clear_tdes(), logtb_free_tran_mvcc_info(), logtb_tran_free_update_stats(), log_topops_stack::max, NO_ERROR, rmutex_finalize, log_tdes::rmutex_topop, log_topops_stack::stack, and log_tdes::topops.
Referenced by log_system_tdes::destroy_system_transactions(), logtb_undefine_trantable(), and log_system_tdes::~log_system_tdes().
const char* logtb_find_client_hostname (int tran_index)
Definition at line 2088 of file log_tran_table.c.
References log_tdes::client, clientids::get_host_name(), LOG_FIND_TDES(), NULL, NULL_TRANID, and log_tdes::trid.
Referenced by logtb_find_current_client_hostname().
const char* logtb_find_client_name (int tran_index)
Definition at line 2015 of file log_tran_table.c.
References log_tdes::client, clientids::get_db_user(), LOG_FIND_TDES(), NULL, NULL_TRANID, and log_tdes::trid.
Referenced by logtb_check_kill_tran_auth(), and logtb_find_current_client_name().
int logtb_find_client_name_host_pid (int tran_index, const char ** client_prog_name, const char ** client_user_name, const char ** client_host_name, int * client_pid)
Definition at line 2119 of file log_tran_table.c.
References log_tdes::client, ER_FAILED, clientids::get_db_user(), clientids::get_host_name(), clientids::get_program_name(), LOG_FIND_TDES(), logtb_get_current_tran_index(), NO_ERROR, NULL, NULL_TRANID, clientids::process_id, log_tdes::trid, and clientids::UNKNOWN_ID.
Referenced by css_default_server_timeout_fn(), event_log_print_client_info(), lock_demote_class_lock(), pgbuf_block_bcb(), pgbuf_latch_bcb_upon_fix(), xlock_dump(), xlogtb_kill_tran_index(), and xtran_server_abort().
int logtb_find_client_type (int tran_index)
Definition at line 1995 of file log_tran_table.c.
References log_tdes::client, clientids::client_type, LOG_FIND_TDES(), NULL, NULL_TRANID, and log_tdes::trid.
Referenced by logtb_find_current_client_type(), and net_server_request().
const char* logtb_find_current_client_hostname (THREAD_ENTRY * thread_p)
Definition at line 2440 of file log_tran_table.c.
References LOG_FIND_THREAD_TRAN_INDEX, and logtb_find_client_hostname().
Referenced by xtran_lock_rep_read().
const char* logtb_find_current_client_name (THREAD_ENTRY * thread_p)
Definition at line 2429 of file log_tran_table.c.
References LOG_FIND_THREAD_TRAN_INDEX, and logtb_find_client_name().
Referenced by logtb_am_i_dba_client(), and logtb_check_kill_tran_auth().
int logtb_find_current_client_type (THREAD_ENTRY * thread_p)
Definition at line 2418 of file log_tran_table.c.
References LOG_FIND_THREAD_TRAN_INDEX, and logtb_find_client_type().
Referenced by xtran_lock_rep_read().
TRAN_ISOLATION logtb_find_current_isolation (THREAD_ENTRY * thread_p)
Definition at line 2667 of file log_tran_table.c.
References LOG_FIND_THREAD_TRAN_INDEX, and logtb_find_isolation().
Referenced by btree_key_lock_and_append_object_unique(), locator_lock_and_get_object_internal(), qexec_execute_query(), scan_next_index_scan(), and xbtree_find_unique().
MVCCID logtb_find_current_mvccid (THREAD_ENTRY * thread_p)
Definition at line 3850 of file log_tran_table.c.
References mvcc_info::id, LOG_FIND_TDES(), LOG_FIND_THREAD_TRAN_INDEX, MVCCID_NULL, log_tdes::mvccinfo, NULL, and mvcc_info::sub_ids.
Referenced by btree_key_delete_remove_object(), and locator_update_force().
LOG_LSA* logtb_find_current_tran_lsa (THREAD_ENTRY * thread_p)
Definition at line 2451 of file log_tran_table.c.
References LOG_FIND_CURRENT_TDES(), NULL, and log_tdes::tail_lsa.
Referenced by heap_log_delete_physical(), heap_update_bigone(), heap_update_home(), and heap_update_relocation().
TRANID logtb_find_current_tranid (THREAD_ENTRY * thread_p)
Definition at line 1892 of file log_tran_table.c.
References trantable::all_tdes, log_tdes::client, clientids::client_type, cubregex::count(), i, LOG_FIND_THREAD_TRAN_INDEX, log_Gl, logtb_find_tranid(), NULL, NULL_TRANID, trantable::num_total_indices, TR_TABLE_CS_ENTER_READ_MODE, TR_TABLE_CS_EXIT, log_global::trantable, and log_tdes::trid.
Referenced by fetch_peek_arith(), spage_check_slot_owner(), spage_free_saved_spaces(), spage_get_saved_spaces(), spage_has_enough_total_space(), spage_insert_data(), spage_save_space(), and xtran_get_local_transaction_id().
int logtb_find_interrupt (int tran_index, bool * interrupt)
Definition at line 2552 of file log_tran_table.c.
References assert, ER_FAILED, log_tdes::interrupt, LOG_FIND_TDES(), NO_ERROR, NULL, NULL_TRANID, and log_tdes::trid.
Referenced by xlogtb_kill_or_interrupt_tran().
TRAN_ISOLATION logtb_find_isolation (int tran_index)
Definition at line 2643 of file log_tran_table.c.
References log_tdes::isolation, LOG_FIND_TDES(), NULL, and TRAN_UNKNOWN_ISOLATION.
Referenced by lock_classes_lock_hint(), lock_notify_isolation_incons(), lock_object(), lock_scan(), lock_subclass(), lock_unlock_classes_lock_hint(), lock_unlock_object(), lock_unlock_objects_lock_set(), logtb_find_current_isolation(), qfile_update_list_cache_entry(), scan_next_heap_scan(), scan_next_index_lookup_heap(), and xlock_dump().
int logtb_find_log_records_count (int tran_index)
Definition at line 2579 of file log_tran_table.c.
References LOG_FIND_TDES(), NULL, and log_tdes::num_log_records_written.
Referenced by lock_demote_class_lock().
void logtb_find_smallest_and_largest_active_pages (THREAD_ENTRY * thread_p, LOG_PAGEID * smallest, LOG_PAGEID * largest)
Definition at line 4457 of file log_tran_table.c.
References trantable::all_tdes, log_tdes::head_lsa, i, log_Gl, LOG_SYSTEM_TRAN_INDEX, LSA_ISNULL(), NULL, NULL_PAGEID, NULL_TRANID, NUM_TOTAL_TRAN_INDICES, log_lsa::pageid, log_tdes::posp_nxlsa, log_tdes::tail_lsa, TR_TABLE_CS_ENTER_READ_MODE, TR_TABLE_CS_EXIT, log_global::trantable, and log_tdes::trid.
void logtb_find_smallest_lsa (THREAD_ENTRY * thread_p, LOG_LSA * lsa)
Definition at line 4217 of file log_tran_table.c.
References trantable::all_tdes, log_tdes::head_lsa, i, log_Gl, LOG_SYSTEM_TRAN_INDEX, LSA_COPY(), LSA_ISNULL(), LSA_LT(), LSA_SET_NULL(), NULL, NULL_TRANID, NUM_TOTAL_TRAN_INDICES, TR_TABLE_CS_ENTER_READ_MODE, TR_TABLE_CS_EXIT, log_global::trantable, and log_tdes::trid.
Referenced by logpb_checkpoint(), and logpb_is_smallest_lsa_in_archive().
TRAN_STATE logtb_find_state (int tran_index)
Definition at line 2467 of file log_tran_table.c.
References LOG_FIND_TDES(), NULL, log_tdes::state, and TRAN_UNACTIVE_UNKNOWN.
Referenced by lock_demote_class_lock(), and xlock_dump().
THREAD_ENTRY* logtb_find_thread_by_tran_index (int tran_index)
Definition at line 5914 of file log_tran_table.c.
References logtb_find_thread_entry_mapfunc(), cubthread::manager::map_entries(), NULL, and thread_get_manager().
THREAD_ENTRY* logtb_find_thread_by_tran_index_except_me (int tran_index)
Definition at line 5928 of file log_tran_table.c.
References logtb_find_thread_entry_mapfunc(), cubthread::manager::map_entries(), NULL, thread_get_manager(), and thread_wakeup().
Referenced by net_server_conn_down().
int logtb_find_tran_index (THREAD_ENTRY * thread_p, TRANID trid)
Definition at line 1789 of file log_tran_table.c.
References trantable::all_tdes, assert, log_tdes::client, clientids::get_host_name(), i, LOG_FIND_TDES(), LOG_FIND_THREAD_TRAN_INDEX, log_Gl, NULL, NULL_TRAN_INDEX, NULL_TRANID, NUM_TOTAL_TRAN_INDICES, clientids::process_id, TR_TABLE_CS_ENTER_READ_MODE, TR_TABLE_CS_EXIT, log_global::trantable, and log_tdes::trid.
Referenced by log_recovery_analysis(), log_recovery_needs_skip_logical_redo(), log_recovery_redo(), log_recovery_undo(), log_rv_analysis_complete(), and logtb_rv_find_allocate_tran_index().
TRANID logtb_find_tranid (int tran_index)
Definition at line 1873 of file log_tran_table.c.
References LOG_FIND_TDES(), NULL, NULL_TRANID, and log_tdes::trid.
Referenced by lock_demote_class_lock(), lock_detect_local_deadlock(), and logtb_find_current_tranid().
int logtb_find_wait_msecs (int tran_index)
Definition at line 2526 of file log_tran_table.c.
References assert, LOG_FIND_TDES(), NULL, and log_tdes::wait_msecs.
Referenced by lock_classes_lock_hint(), lock_demote_class_lock(), lock_detect_local_deadlock(), lock_initialize_composite_lock(), lock_object(), lock_rep_read_tran(), lock_scan(), lock_subclass(), pgbuf_latch_bcb_upon_fix(), and xlock_dump().
void logtb_free_tran_index (THREAD_ENTRY * thread_p, int tran_index)
Definition at line 1198 of file log_tran_table.c.
References ARG_FILE_LINE, log_tdes::client_id, er_log_debug, free_and_init, trantable::hint_free_index, log_topops_stack::last, LOG_FIND_TDES(), LOG_FIND_THREAD_TRAN_INDEX, log_Gl, LOG_ISRESTARTED, LOG_SET_CURRENT_TRAN_INDEX, LOG_SYSTEM_TRAN_INDEX, logtb_clear_tdes(), logtb_decrement_number_of_assigned_tran_indices(), log_topops_stack::max, NULL, NULL_TRAN_INDEX, NULL_TRANID, log_tdes::num_repl_records, NUM_TOTAL_TRAN_INDICES, log_tdes::repl_records, log_topops_stack::stack, thread_get_thread_entry_info(), log_tdes::topops, TR_TABLE_CS_ENTER, TR_TABLE_CS_EXIT, log_global::trantable, and log_tdes::trid.
Referenced by boot_restart_server(), log_2pc_attach_client(), log_complete_for_2pc(), log_recovery_finish_postpone(), log_recovery_redo(), log_recovery_undo(), log_rv_analysis_complete(), logtb_free_tran_index_with_undo_lsa(), logtb_release_tran_index(), and cubload::session::notify_batch_done_and_register_tran_end().
void logtb_free_tran_index_with_undo_lsa (THREAD_ENTRY * thread_p, const LOG_LSA * undo_lsa)
Definition at line 1277 of file log_tran_table.c.
References trantable::all_tdes, i, log_Gl, LOG_SYSTEM_TRAN_INDEX, logtb_free_tran_index(), LSA_EQ(), LSA_ISNULL(), NULL, NULL_TRANID, NUM_TOTAL_TRAN_INDICES, log_tdes::state, TR_TABLE_CS_ENTER, TR_TABLE_CS_EXIT, TRAN_UNACTIVE_UNILATERALLY_ABORTED, log_global::trantable, log_tdes::trid, and log_tdes::undo_nxlsa.
Referenced by log_recovery_undo().
bool logtb_get_check_interrupt (THREAD_ENTRY * thread_p)
Definition at line 6017 of file log_tran_table.c.
References BO_IS_SERVER_RESTARTED, NULL, thread_get_thread_entry_info(), and tran_get_check_interrupt().
Referenced by disk_extend(), fileio_initialize_pages(), logpb_backup(), pgbuf_fix_debug(), qmgr_free_list_temp_file(), qmgr_get_old_page(), and vacuum_process_log_block().
int logtb_get_client_ids (int tran_index, CLIENTIDS * client_info)
Definition at line 2167 of file log_tran_table.c.
References log_tdes::client, ER_FAILED, LOG_FIND_TDES(), NO_ERROR, NULL, NULL_TRANID, and log_tdes::trid.
Referenced by logwr_log_ha_filestat_to_string().
MVCCID logtb_get_current_mvccid (THREAD_ENTRY * thread_p)
Definition at line 3880 of file log_tran_table.c.
References assert, mvcctable::get_new_mvccid(), mvcc_info::id, LOG_FIND_TDES(), LOG_FIND_THREAD_TRAN_INDEX, log_Gl, log_global::mvcc_table, MVCCID_IS_VALID, log_tdes::mvccinfo, NULL, and mvcc_info::sub_ids.
Referenced by btree_build_nleafs(), btree_construct_leafs(), btree_physical_delete(), btree_rv_save_keyval_for_undo(), file_create(), file_tracker_item_reuse_heap(), heap_delete_bigone(), heap_delete_home(), heap_delete_relocation(), heap_insert_adjust_recdes_header(), heap_log_update_physical(), heap_mvcc_log_delete(), heap_mvcc_log_home_change_on_delete(), heap_mvcc_log_home_no_change(), heap_mvcc_log_insert(), heap_mvcc_log_redistribute(), heap_update_adjust_recdes_header(), locator_add_or_remove_index_internal(), locator_update_index(), log_sysop_end_logical_undo(), test_new_mvcc_complete(), and xbtree_add_index().
int logtb_get_current_tran_index (void)
Definition at line 5961 of file log_tran_table.c.
References assert, NULL, and thread_get_thread_entry_info().
Referenced by cubmonitor::transaction_sheet_manager::end_watch(), file_get_tempcache_entry_index(), cubmonitor::transaction_sheet_manager::get_sheet(), lock_get_class_lock(), lock_get_object_lock(), lock_has_lock_on_object(), logtb_find_client_name_host_pid(), and cubmonitor::transaction_sheet_manager::start_watch().
int logtb_get_global_unique_stats (THREAD_ENTRY * thread_p, BTID * btid, int * num_oids, int * num_nulls, int * num_keys)
Definition at line 4840 of file log_tran_table.c.
References assert, ER_FAILED, logtb_get_global_unique_stats_entry(), global_unique_stats::mutex, NO_ERROR, NULL, log_unique_stats::num_keys, log_unique_stats::num_nulls, log_unique_stats::num_oids, pthread_mutex_unlock, and global_unique_stats::unique_stats.
Referenced by btree_online_index_check_unique_constraint(), btree_scan_for_show_index_header(), locator_check_unique_btree_entries(), logtb_create_unique_stats_from_repr(), and xbtree_test_unique().
MVCC_SNAPSHOT* logtb_get_mvcc_snapshot (THREAD_ENTRY * thread_p)
Definition at line 3947 of file log_tran_table.c.
References assert, mvcctable::build_mvcc_info(), LOG_FIND_TDES(), LOG_FIND_THREAD_TRAN_INDEX, log_Gl, log_global::mvcc_table, log_tdes::mvccinfo, NULL, mvcc_info::snapshot, and mvcc_snapshot::valid.
Referenced by btree_get_stats_with_fullscan(), btree_key_lock_and_append_object_unique(), btree_keyoid_checkscan_check(), catalog_check_consistency(), catalog_dump(), css_make_access_status_exist_user(), heap_class_get_partition_info(), heap_is_object_not_null(), locator_all_reference_lockset(), locator_check_all_entries_of_all_btrees(), locator_check_btree_entries(), locator_check_by_class_oid(), locator_check_class_names(), locator_check_primary_key_delete(), locator_check_primary_key_update(), locator_check_unique_btree_entries(), locator_force_for_multi_update(), locator_lock_and_get_object_internal(), locator_update_force(), process_class(), process_value(), qexec_evaluate_aggregates_optimize(), qexec_execute_delete(), qexec_execute_obj_fetch(), qexec_execute_query(), qexec_execute_selupd_list(), qexec_execute_update(), qexec_upddel_setup_current_class(), scan_start_scan(), test_mvcc_get_snapshot(), xbtree_find_unique(), xbtree_load_online_index(), xheap_has_instance(), xlocator_check_fk_validity(), xlocator_fetch(), xlocator_fetch_all(), xlocator_fetch_lockset(), xlocator_remove_class_from_index(), xlogtb_get_mvcc_snapshot(), and xstats_update_all_statistics().
void logtb_get_new_subtransaction_mvccid (THREAD_ENTRY * thread_p, MVCC_INFO * curr_mvcc_info)
Definition at line 4523 of file log_tran_table.c.
References assert, mvcctable::get_new_mvccid(), mvcctable::get_two_new_mvccid(), mvcc_info::id, log_Gl, logtb_assign_subtransaction_mvccid(), log_global::mvcc_table, MVCCID_IS_VALID, and NULL.
Referenced by qexec_execute_selupd_list().
int logtb_get_new_tran_id (THREAD_ENTRY * thread_p, LOG_TDES * tdes)
Definition at line 1723 of file log_tran_table.c.
References assert, DB_INT32_MAX, log_global::hdr, log_Gl, LOG_SYSTEM_TRANID, logtb_clear_tdes(), log_header::next_trid, TR_TABLE_CS_ENTER, TR_TABLE_CS_EXIT, log_tdes::trid, and VOLATILE_ACCESS.
Referenced by log_complete(), log_complete_for_2pc(), and logtb_allocate_tran_index().
int logtb_get_number_assigned_tran_indices (void)
Definition at line 633 of file log_tran_table.c.
References NUM_ASSIGNED_TRAN_INDICES.
Referenced by lock_victimize_first_thread_mapfunc().
int logtb_get_number_of_total_tran_indices (void)
Definition at line 692 of file log_tran_table.c.
References log_Gl, trantable::num_total_indices, and log_global::trantable.
Referenced by mvcctable::alloc_transaction_lowest_active(), mvcctable::build_mvcc_info(), file_tempcache_final(), file_tempcache_init(), heap_chnguess_initialize(), heap_chnguess_realloc(), heap_chnguess_remove_entry(), mvcc_active_tran::long_tran_max_size(), and qmgr_initialize().
LOG_TDES* logtb_get_system_tdes (THREAD_ENTRY * thread_p = NULL)
Definition at line 6039 of file log_tran_table.c.
References trantable::all_tdes, assert, log_tdes::block_global_oldest_active_until_commit, log_tdes::head_lsa, mvcctable::is_global_oldest_visible_locked(), log_topops_stack::last, mvcctable::lock_global_oldest_visible(), log_Gl, LOG_ISRESTARTED, LOG_SYSTEM_TRAN_INDEX, LOG_SYSTEM_TRANID, LSA_SET_NULL(), log_global::mvcc_table, NO_ERROR, NULL, NULL_ATTRID, trantable::num_total_indices, log_tdes::rcv, rmutex_lock, log_tdes::rmutex_topop, rmutex_unlock, log_rcv_tdes::sysop_start_postpone_lsa, log_tdes::tail_lsa, log_tdes::tail_topresult_lsa, thread_get_thread_entry_info(), log_tdes::topops, log_rcv_tdes::tran_start_postpone_lsa, log_global::trantable, log_tdes::trid, log_tdes::undo_nxlsa, and mvcctable::unlock_global_oldest_visible().
Referenced by LOG_FIND_TDES(), and vacuum_worker_allocate_resources().
bool logtb_has_deadlock_priority (int tran_index)
Definition at line 4498 of file log_tran_table.c.
References log_tdes::has_deadlock_priority, and LOG_FIND_TDES().
Referenced by lock_demote_class_lock().
int logtb_initialize_global_unique_stats_table (THREAD_ENTRY * thread_p)
Definition at line 4691 of file log_tran_table.c.
References btree_compare_btids(), btree_hash_btid(), global_unique_stats_table::curr_rcv_rec_lsa, lf_entry_descriptor::f_alloc, lf_entry_descriptor::f_duplicate, lf_entry_descriptor::f_free, lf_entry_descriptor::f_hash, lf_entry_descriptor::f_init, lf_entry_descriptor::f_key_cmp, lf_entry_descriptor::f_key_copy, lf_entry_descriptor::f_uninit, GLOBAL_UNIQUE_STATS_HASH_SIZE, global_unique_stats_Ts, global_unique_stats_table::initialized, LF_EM_USING_MUTEX, lf_freelist_init(), lf_hash_destroy(), lf_hash_init(), log_Gl, logtb_global_unique_stat_alloc(), logtb_global_unique_stat_free(), logtb_global_unique_stat_init(), logtb_global_unique_stat_key_copy(), LSA_SET_NULL(), mutex, NO_ERROR, NULL, lf_entry_descriptor::of_del_tran_id, lf_entry_descriptor::of_key, lf_entry_descriptor::of_local_next, lf_entry_descriptor::of_mutex, lf_entry_descriptor::of_next, global_unique_stats_table::unique_stats_descriptor, global_unique_stats_table::unique_stats_freelist, global_unique_stats_table::unique_stats_hash, log_global::unique_stats_table, and lf_entry_descriptor::using_mutex.
Referenced by boot_create_all_volumes(), boot_restart_server(), and xboot_emergency_patch().
void logtb_initialize_tdes (LOG_TDES * tdes, int tran_index)
Definition at line 1600 of file log_tran_table.c.
References log_rcv_tdes::analysis_last_aborted_sysop_lsa, log_rcv_tdes::analysis_last_aborted_sysop_start_lsa, log_tdes::append_repl_recidx, assert, log_rcv_tdes::atomic_sysop_start_lsa, log_tdes::bind_history, log_tdes::block_global_oldest_active_until_commit, log_tran_update_stats::classes_cos_hash, log_tdes::client_id, multi_index_unique_stats::construct(), log_tdes::coord, log_tran_update_stats::cos_count, log_tran_update_stats::cos_current_chunk, log_tran_update_stats::cos_first_chunk, log_tdes::cur_repl_record, db_Disable_modifications, log_tdes::disable_modifications, log_tdes::first_save_entry, log_tdes::fl_mark_repl_recidx, log_tdes::gtrid, log_tdes::gtrinfo, log_tdes::has_deadlock_priority, log_tdes::head_lsa, i, log_2pc_gtrinfo::info_data, log_2pc_gtrinfo::info_length, lob_rb_root::init(), mvcc_info::init(), log_tdes::interrupt, log_tdes::is_user_active, log_tdes::isloose_end, log_tdes::isolation, log_topops_stack::last, log_tdes::lob_locator_root, LOG_2PC_NULL_GTRID, log_tdes::log_upd_stats, logtb_tran_btid_hash_cmp_func(), logtb_tran_btid_hash_func(), LSA_SET_NULL(), log_tdes::m_multiupd_stats, log_topops_stack::max, MAX_NUM_EXEC_QUERY_HISTORY, log_tdes::max_unique_btrees, mht_create(), log_tdes::mvccinfo, NO_ERROR, NULL, NULL_TRANID, log_tdes::num_exec_queries, log_tdes::num_log_records_written, log_tdes::num_repl_records, log_tdes::num_transient_classnames, log_tdes::num_unique_btrees, oid_compare_equals(), oid_hash(), log_tdes::posp_nxlsa, log_tdes::query_start_time, log_tdes::query_timeout, log_tdes::rcv, log_tdes::repl_insert_lsa, log_tdes::repl_records, log_tdes::repl_update_lsa, rmutex_initialize, RMUTEX_NAME_TDES_TOPOP, log_tdes::rmutex_topop, log_tdes::savept_lsa, db_value_array::size, log_topops_stack::stack, log_tran_update_stats::stats_count, log_tran_update_stats::stats_current_chunk, log_tran_update_stats::stats_first_chunk, log_tdes::suppress_replication, log_rcv_tdes::sysop_start_postpone_lsa, log_tdes::tail_lsa, log_tdes::tail_topresult_lsa, log_tdes::topop_lsa, log_tdes::topops, log_tdes::tran_abort_reason, log_tdes::tran_index, TRAN_LOCK_INFINITE_WAIT, TRAN_NORMAL, TRAN_SERIALIZABLE, log_rcv_tdes::tran_start_postpone_lsa, log_tdes::tran_start_time, log_tdes::trid, log_tdes::undo_nxlsa, log_tran_update_stats::unique_stats_hash, db_value_array::vals, log_tdes::wait_msecs, log_tdes::waiting_for_res, log_tdes::xasl_id, and XASL_ID_SET_NULL.
Referenced by logtb_allocate_tdes_area(), and systdes_create_tdes().
int logtb_invalidate_snapshot_data (THREAD_ENTRY * thread_p)
Definition at line 3801 of file log_tran_table.c.
References log_tdes::isolation, LOG_FIND_TDES(), LOG_FIND_THREAD_TRAN_INDEX, logtb_tran_reset_count_optim_state(), log_tdes::mvccinfo, NO_ERROR, NULL, mvcc_info::snapshot, TRAN_REPEATABLE_READ, and mvcc_snapshot::valid.
Referenced by net_server_request(), and xbtree_load_online_index().
bool logtb_is_active (THREAD_ENTRY * thread_p, TRANID trid)
Definition at line 2982 of file log_tran_table.c.
References trantable::all_tdes, i, LOG_FIND_TDES(), LOG_FIND_THREAD_TRAN_INDEX, log_Gl, LOG_ISRESTARTED, LOG_ISTRAN_ACTIVE, NULL, NULL_TRANID, NUM_TOTAL_TRAN_INDICES, TR_TABLE_CS_ENTER_READ_MODE, TR_TABLE_CS_EXIT, log_global::trantable, and log_tdes::trid.
Referenced by lock_demote_class_lock(), lock_detect_local_deadlock(), spage_has_enough_total_space(), and spage_save_space().
bool logtb_is_current_active (THREAD_ENTRY * thread_p)
Definition at line 3028 of file log_tran_table.c.
References assert, LOG_FIND_TDES(), LOG_FIND_THREAD_TRAN_INDEX, LOG_ISTRAN_ACTIVE, and NULL.
Referenced by btree_reflect_global_unique_statistics(), css_stop_log_writer(), css_stop_non_log_writer(), pgbuf_block_bcb(), pgbuf_set_lsa(), spage_find_empty_slot_at(), and xtran_server_is_active_and_has_updated().
bool logtb_is_current_mvccid (THREAD_ENTRY * thread_p, MVCCID mvccid)
Definition at line 3913 of file log_tran_table.c.
References assert, i, mvcc_info::id, LOG_FIND_TDES(), LOG_FIND_THREAD_TRAN_INDEX, log_tdes::mvccinfo, NULL, and mvcc_info::sub_ids.
Referenced by mvcc_is_active_id().
bool logtb_is_interrupted (THREAD_ENTRY * thread_p, bool clear, bool * continue_checking)
Definition at line 2868 of file log_tran_table.c.
References trantable::area, LOG_FIND_TDES(), LOG_FIND_THREAD_TRAN_INDEX, log_Gl, logtb_is_interrupted_tdes(), NULL, and log_global::trantable.
Referenced by disk_extend(), logpb_backup(), logwr_log_ha_filestat_to_string(), online_index_builder(), pgbuf_copy_to_area(), pgbuf_fix_debug(), pgbuf_is_log_check_for_interrupts(), vacuum_process_log_block(), xs_receive_data_from_client_with_timeout(), xs_send_action_to_client(), and xvacuum().
bool logtb_is_interrupted_tran (THREAD_ENTRY * thread_p, bool clear, bool * continue_checking, int tran_index)
Definition at line 2906 of file log_tran_table.c.
References trantable::area, LOG_FIND_TDES(), log_Gl, logtb_is_interrupted_tdes(), NULL, and log_global::trantable.
Referenced by lock_force_timeout_expired_wait_transactions(), net_server_conn_down(), qmgr_free_list_temp_file(), qmgr_get_old_page(), and xtran_wait_server_active_trans().
bool logtb_is_mvccid_committed (THREAD_ENTRY * thread_p, MVCCID mvccid)
bool logtb_is_system_worker_tranid (TRANID trid) inline
Definition at line 1121 of file log_impl.h.
References NULL_TRANID.
Referenced by log_recovery_undo(), and logtb_rv_find_allocate_tran_index().
int logtb_is_tran_modification_disabled (THREAD_ENTRY * thread_p)
Definition at line 1018 of file log_tran_table.c.
References db_Disable_modifications, log_tdes::disable_modifications, LOG_FIND_TDES(), LOG_FIND_THREAD_TRAN_INDEX, and NULL.
bool logtb_istran_finished (THREAD_ENTRY * thread_p, TRANID trid)
Definition at line 3069 of file log_tran_table.c.
References trantable::all_tdes, i, LOG_FIND_TDES(), LOG_FIND_THREAD_TRAN_INDEX, log_Gl, NULL, NULL_TRANID, NUM_TOTAL_TRAN_INDICES, TR_TABLE_CS_ENTER_READ_MODE, TR_TABLE_CS_EXIT, log_global::trantable, and log_tdes::trid.
void* logtb_realloc_topops_stack (LOG_TDES * tdes, int num_elms)
Definition at line 157 of file log_tran_table.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), log_topops_stack::last, LOG_TOPOPS_STACK_INCREMENT, log_topops_stack::max, NULL, log_topops_stack::stack, and log_tdes::topops.
Referenced by log_rv_analysis_end_checkpoint(), log_rv_analysis_sysop_end(), log_rv_analysis_sysop_start_postpone(), and log_sysop_start().
int logtb_reflect_global_unique_stats_to_btree (THREAD_ENTRY * thread_p)
Definition at line 5058 of file log_tran_table.c.
References ASSERT_ERROR, btree_reflect_global_unique_statistics(), error(), global_unique_stats_table::initialized, global_unique_stats::last_log_lsa, lf_hash_create_iterator(), lf_hash_iterate(), lf_tran_end_with_mb, log_Gl, logtb_set_check_interrupt(), LSA_ISNULL(), LSA_SET_NULL(), global_unique_stats::mutex, NO_ERROR, NULL, pthread_mutex_unlock, thread_get_tran_entry(), THREAD_TS_GLOBAL_UNIQUE_STATS, global_unique_stats_table::unique_stats_hash, and log_global::unique_stats_table.
Referenced by logpb_checkpoint(), and xboot_shutdown_server().
void logtb_release_tran_index (THREAD_ENTRY * thread_p, int tran_index)
Definition at line 1135 of file log_tran_table.c.
References log_tdes::client, free_and_init, heap_chnguess_clear(), log_tdes::is_user_active, log_tdes::isloose_end, log_topops_stack::last, LOG_FIND_TDES(), log_Gl, LOG_ISTRAN_2PC_INFORMING_PARTICIPANTS, LOG_ISTRAN_2PC_PREPARE, LOG_SYSTEM_TRAN_INDEX, logtb_free_tran_index(), log_topops_stack::max, log_tdes::mvccinfo, NULL, trantable::num_coord_loose_end_indices, trantable::num_prepared_loose_end_indices, qmgr_clear_trans_wakeup(), clientids::reset(), mvcc_info::reset(), log_topops_stack::stack, log_tdes::topops, TR_TABLE_CS_ENTER, TR_TABLE_CS_EXIT, and log_global::trantable.
Referenced by boot_create_all_volumes(), xboot_initialize_server(), xboot_register_client(), and xboot_unregister_client().
void logtb_rv_assign_mvccid_for_undo_recovery (THREAD_ENTRY * thread_p, MVCCID mvccid)
Definition at line 1111 of file log_tran_table.c.
References assert, mvcc_info::id, LOG_FIND_CURRENT_TDES(), MVCCID_IS_VALID, log_tdes::mvccinfo, and NULL.
Referenced by log_rv_undo_record().
LOG_TDES* logtb_rv_find_allocate_tran_index (THREAD_ENTRY * thread_p, TRANID trid, const LOG_LSA * log_lsa)
Definition at line 1052 of file log_tran_table.c.
References ARG_FILE_LINE, assert, log_tdes::head_lsa, LOG_FIND_TDES(), logpb_fatal_error(), logtb_allocate_tran_index(), logtb_find_tran_index(), logtb_is_system_worker_tranid(), LSA_COPY(), NULL, NULL_TRAN_INDEX, NULL_TRANID, log_system_tdes::rv_get_or_alloc_tdes(), TRAN_LOCK_INFINITE_WAIT, TRAN_SERIALIZABLE, and TRAN_UNACTIVE_UNILATERALLY_ABORTED.
Referenced by log_rv_analysis_2pc_abort_decision(), log_rv_analysis_2pc_abort_inform_particps(), log_rv_analysis_2pc_commit_decision(), log_rv_analysis_2pc_commit_inform_particps(), log_rv_analysis_2pc_prepare(), log_rv_analysis_2pc_recv_ack(), log_rv_analysis_2pc_start(), log_rv_analysis_atomic_sysop_start(), log_rv_analysis_commit_with_postpone(), log_rv_analysis_compensate(), log_rv_analysis_dummy_head_postpone(), log_rv_analysis_end_checkpoint(), log_rv_analysis_postpone(), log_rv_analysis_run_postpone(), log_rv_analysis_save_point(), log_rv_analysis_sysop_end(), log_rv_analysis_sysop_start_postpone(), log_rv_analysis_undo_redo(), and log_rv_analysis_will_commit().
int logtb_rv_update_global_unique_stats_by_abs (THREAD_ENTRY * thread_p, BTID * btid, int num_oids, int num_nulls, int num_keys)
Definition at line 4875 of file log_tran_table.c.
References _er_log_debug(), ARG_FILE_LINE, global_unique_stats_table::curr_rcv_rec_lsa, ER_FAILED, vfid::fileid, global_unique_stats::last_log_lsa, log_Gl, logtb_get_global_unique_stats_entry(), LSA_COPY(), LSA_ISNULL(), global_unique_stats::mutex, NO_ERROR, NULL, log_unique_stats::num_keys, log_unique_stats::num_nulls, log_unique_stats::num_oids, log_lsa::offset, log_lsa::pageid, prm_get_bool_value(), PRM_ID_LOG_UNIQUE_STATS, pthread_mutex_unlock, btid::root_pageid, global_unique_stats::unique_stats, log_global::unique_stats_table, btid::vfid, and vfid::volid.
Referenced by btree_rv_redo_global_unique_stats_commit().
bool logtb_set_check_interrupt (THREAD_ENTRY * thread_p, bool flag)
Definition at line 5988 of file log_tran_table.c.
References assert, BO_IS_SERVER_RESTARTED, NULL, thread_get_thread_entry_info(), tran_set_check_interrupt(), and VACUUM_IS_THREAD_VACUUM.
Referenced by btree_delete_internal(), btree_verify_node(), disk_extend(), disk_is_page_sector_reserved_with_debug_crash(), disk_reserve_sectors(), dwb_wait_for_block_completion(), dwb_wait_for_strucure_modification(), file_create(), file_destroy(), file_temp_alloc(), file_temp_reset_user_pages(), heap_does_exist(), heap_is_object_not_null(), logtb_reflect_global_unique_stats_to_btree(), logtb_tran_update_all_global_unique_stats(), px_sort_myself(), qexec_destroy_upddel_ehash_files(), xbtree_load_online_index(), and xvacuum().
void logtb_set_current_tran_index (THREAD_ENTRY * thread_p, int tran_index)
Definition at line 5973 of file log_tran_table.c.
References NULL, and thread_get_thread_entry_info().
void logtb_set_current_user_active (THREAD_ENTRY * thread_p, bool is_user_active)
Definition at line 2069 of file log_tran_table.c.
References log_tdes::is_user_active, LOG_FIND_TDES(), and LOG_FIND_THREAD_TRAN_INDEX.
Referenced by session_check_session(), session_state_create(), and session_state_destroy().
void logtb_set_current_user_name (THREAD_ENTRY * thread_p, const char * client_name)
Definition at line 2056 of file log_tran_table.c.
References LOG_FIND_THREAD_TRAN_INDEX, and logtb_set_user_name().
Referenced by ssession_find_or_create_session().
int logtb_set_num_loose_end_trans (THREAD_ENTRY * thread_p)
Definition at line 4131 of file log_tran_table.c.
References trantable::all_tdes, i, log_Gl, LOG_SYSTEM_TRAN_INDEX, logtb_set_loose_end_tdes(), NULL, NULL_TRANID, trantable::num_coord_loose_end_indices, trantable::num_prepared_loose_end_indices, NUM_TOTAL_TRAN_INDICES, TR_TABLE_CS_ENTER, TR_TABLE_CS_EXIT, log_global::trantable, and log_tdes::trid.
Referenced by log_recovery().
bool logtb_set_suppress_repl_on_transaction (THREAD_ENTRY * thread_p, int tran_index, int set)
Definition at line 2944 of file log_tran_table.c.
References trantable::area, LOG_FIND_TDES(), log_Gl, NULL, NULL_TRANID, log_tdes::suppress_replication, log_global::trantable, and log_tdes::trid.
Referenced by xlogtb_set_suppress_repl_on_transaction().
void logtb_set_to_system_tran_index (THREAD_ENTRY * thread_p)
Definition at line 3159 of file log_tran_table.c.
References LOG_SET_CURRENT_TRAN_INDEX, and LOG_SYSTEM_TRAN_INDEX.
Referenced by boot_restart_server(), and xboot_shutdown_server().
bool logtb_set_tran_index_interrupt (THREAD_ENTRY * thread_p, int tran_index, bool set)
Definition at line 2706 of file log_tran_table.c.
References trantable::area, ARG_FILE_LINE, assert, ER_INTERRUPTING, ER_NOTIFICATION_SEVERITY, er_set(), log_tdes::interrupt, LOG_FIND_TDES(), log_Gl, LOG_SYSTEM_TRAN_INDEX, NULL, NULL_TRANID, trantable::num_interrupts, perfmon_inc_stat(), pgbuf_force_to_check_for_interrupts(), PSTAT_TRAN_NUM_INTERRUPTS, TR_TABLE_CS_ENTER, TR_TABLE_CS_EXIT, log_global::trantable, and log_tdes::trid.
Referenced by css_block_all_active_conn(), css_stop_non_log_writer(), cubload::session::interrupt(), logtb_slam_transaction(), net_server_conn_down(), xbtree_load_online_index(), xlogtb_kill_or_interrupt_tran(), xlogtb_set_interrupt(), and xtran_wait_server_active_trans().
void logtb_set_user_name (int tran_index, const char * client_name)
Definition at line 2036 of file log_tran_table.c.
References log_tdes::client, LOG_FIND_TDES(), NULL, NULL_TRANID, clientids::set_user(), log_tdes::trid, and clientids::UNKNOWN_ID.
Referenced by logtb_set_current_user_name().
void logtb_slam_transaction (THREAD_ENTRY * thread_p, int tran_index)
Definition at line 5660 of file log_tran_table.c.
References ARG_FILE_LINE, css_shutdown_conn_by_tran_index(), ER_CSS_CONN_SHUTDOWN, ER_ERROR_SEVERITY, er_set(), and logtb_set_tran_index_interrupt().
Referenced by css_change_ha_server_state(), and xlogtb_kill_tran_index().
LOG_TRAN_BTID_UNIQUE_STATS* logtb_tran_find_btid_stats (THREAD_ENTRY * thread_p, const BTID * btid, bool create)
Definition at line 3458 of file log_tran_table.c.
References LOG_FIND_TDES(), LOG_FIND_THREAD_TRAN_INDEX, log_tdes::log_upd_stats, logtb_tran_create_btid_unique_stats(), mht_get(), NULL, and log_tran_update_stats::unique_stats_hash.
Referenced by btree_get_unique_statistics_for_count(), btree_online_index_check_unique_constraint(), btree_rv_remove_unique_stats(), index_builder_loader_task::execute(), logtb_complete_mvcc(), logtb_create_unique_stats_from_repr(), logtb_tran_update_btid_unique_stats(), and qexec_evaluate_aggregates_optimize().
LOG_TRAN_CLASS_COS* logtb_tran_find_class_cos (THREAD_ENTRY * thread_p, const OID * class_oid, bool create)
Definition at line 3427 of file log_tran_table.c.
References assert, log_tran_update_stats::classes_cos_hash, LOG_FIND_TDES(), LOG_FIND_THREAD_TRAN_INDEX, log_tdes::log_upd_stats, logtb_tran_create_class_cos(), mht_get(), and NULL.
Referenced by logtb_tran_load_global_stats_func(), logtb_tran_prepare_count_optim_classes(), and qexec_evaluate_aggregates_optimize().
int logtb_tran_prepare_count_optim_classes (THREAD_ENTRY * thread_p, const char ** classes, LC_PREFETCH_FLAGS * flags, int n_classes)
Definition at line 4267 of file log_tran_table.c.
References COS_LOADED, COS_TO_LOAD, log_tran_class_cos::count_state, ER_FAILED, LC_CLASSNAME_ERROR, LC_CLASSNAME_EXIST, LC_PREF_FLAG_COUNT_OPTIM, logtb_tran_find_class_cos(), NO_ERROR, NULL, NULL_LOCK, OID_ISNULL, and xlocator_find_class_oid().
Referenced by xlocator_find_lockhint_class_oids().
void logtb_tran_reset_count_optim_state (THREAD_ENTRY * thread_p)
Definition at line 4348 of file log_tran_table.c.
References log_tran_update_stats::classes_cos_hash, LOG_FIND_TDES(), LOG_FIND_THREAD_TRAN_INDEX, log_tdes::log_upd_stats, logtb_tran_reset_cos_func(), mht_map_no_key(), and NULL.
Referenced by logtb_complete_mvcc(), and logtb_invalidate_snapshot_data().
int logtb_tran_update_all_global_unique_stats (THREAD_ENTRY * thread_p)
Definition at line 3640 of file log_tran_table.c.
References ER_FAILED, LOG_FIND_TDES(), LOG_FIND_THREAD_TRAN_INDEX, log_tdes::log_upd_stats, logtb_set_check_interrupt(), logtb_tran_update_delta_hash_func(), mht_map_no_key(), NO_ERROR, NULL, and log_tran_update_stats::unique_stats_hash.
Referenced by mvcctable::complete_mvcc(), and logtb_complete_mvcc().
int logtb_tran_update_btid_unique_stats (THREAD_ENTRY * thread_p, const BTID * btid, int n_keys, int n_oids, int n_nulls)
Definition at line 3494 of file log_tran_table.c.
References ER_FAILED, logtb_tran_find_btid_stats(), NO_ERROR, NULL, log_unique_stats::num_keys, log_unique_stats::num_nulls, log_unique_stats::num_oids, and log_tran_btid_unique_stats::tran_stats.
Referenced by logtb_tran_update_unique_stats(), and online_index_builder().
int logtb_tran_update_unique_stats (THREAD_ENTRY * thread_p, const BTID * btid, int n_keys, int n_oids, int n_nulls, bool write_to_log)
Definition at line 3527 of file log_tran_table.c.
References recdes::area_size, btree_rv_mvcc_save_increments(), recdes::data, error(), recdes::length, log_append_undo_data2(), logtb_tran_update_btid_unique_stats(), MAX_ALIGNMENT, NO_ERROR, NULL, NULL_OFFSET, OR_BTID_ALIGNED_SIZE, OR_INT_SIZE, PTR_ALIGN, and RVBT_MVCC_INCREMENTS_UPD.
Referenced by btree_fix_root_for_delete(), btree_fix_root_for_insert(), btree_key_online_index_IB_insert(), btree_key_online_index_tran_delete(), btree_key_online_index_tran_insert(), btree_key_online_index_tran_insert_DF(), btree_online_index_list_dispatcher(), btree_rv_update_tran_stats(), locator_force_for_multi_update(), logtb_tran_update_unique_stats(), qexec_execute_insert(), qexec_process_partition_unique_stats(), qexec_process_unique_stats(), cubload::server_object_loader::stop_scancache(), and xlocator_remove_class_from_index().
int logtb_tran_update_unique_stats (THREAD_ENTRY * thread_p, const BTID & btid, const btree_unique_stats & ustats, bool write_to_log)
Definition at line 3568 of file log_tran_table.c.
References btree_unique_stats::get_key_count(), btree_unique_stats::get_null_count(), btree_unique_stats::get_row_count(), btree_unique_stats::is_zero(), logtb_tran_update_unique_stats(), and NO_ERROR.
int logtb_tran_update_unique_stats (THREAD_ENTRY * thread_p, const multi_index_unique_stats & multi_stats, bool write_to_log)
Definition at line 3580 of file log_tran_table.c.
References ASSERT_ERROR, error(), multi_index_unique_stats::get_map(), logtb_tran_update_unique_stats(), and NO_ERROR.
void logtb_undefine_trantable (THREAD_ENTRY * thread_p)
Definition at line 568 of file log_tran_table.c.
References trantable::all_tdes, trantable::area, assert, file_manager_final(), mvcctable::finalize(), free_and_init, i, lock_finalize(), log_Gl, logtb_finalize_tdes(), logtb_initialize_trantable(), log_global::mvcc_table, log_addr_tdesarea::next, NULL, NUM_TOTAL_TRAN_INDICES, pgbuf_finalize(), log_addr_tdesarea::tdesarea, log_tdes::tran_index, and log_global::trantable.
Referenced by log_final(), log_initialize_internal(), log_rv_outside_noop_redo(), logpb_delete(), and logtb_define_trantable_log_latch().
int logtb_update_global_unique_stats_by_delta (THREAD_ENTRY * thread_p, BTID * btid, int oid_delta, int null_delta, int key_delta, bool log)
Definition at line 4925 of file log_tran_table.c.
References _er_log_debug(), recdes::area_size, ARG_FILE_LINE, BTREE_MAX_ALIGN, CAST_BUFLEN, global_unique_stats_table::curr_rcv_rec_lsa, recdes::data, ER_FAILED, vfid::fileid, HEADER, global_unique_stats::last_log_lsa, recdes::length, log_append_undoredo_data2(), LOG_FIND_CURRENT_TDES(), log_Gl, logtb_get_global_unique_stats_entry(), LSA_COPY(), LSA_ISNULL(), global_unique_stats::mutex, NO_ERROR, NULL, log_unique_stats::num_keys, log_unique_stats::num_nulls, log_unique_stats::num_oids, log_lsa::offset, OR_BTID_ALIGNED_SIZE, OR_INT_SIZE, OR_PUT_BTID, OR_PUT_INT, log_lsa::pageid, prm_get_bool_value(), PRM_ID_LOG_UNIQUE_STATS, pthread_mutex_unlock, PTR_ALIGN, btid::root_pageid, RVBT_LOG_GLOBAL_UNIQUE_STATS_COMMIT, log_tdes::tail_lsa, global_unique_stats::unique_stats, log_global::unique_stats_table, btid::vfid, and vfid::volid.
Referenced by btree_rv_undo_global_unique_stats_commit(), logtb_complete_mvcc(), logtb_tran_update_delta_hash_func(), and logtb_tran_update_stats_online_index_rb().
const char* tran_abort_reason_to_string (TRAN_ABORT_REASON val)
Definition at line 5612 of file log_tran_table.c.
References TRAN_ABORT_DUE_DEADLOCK, TRAN_ABORT_DUE_ROLLBACK_ON_ESCALATION, and TRAN_NORMAL.
Referenced by logtb_descriptors_start_scan().
void xlogpb_dump_stat (FILE * outfp)
Definition at line 11039 of file log_page_buffer.c.
References logpb_dump_log_header(), logpb_dump_parameter(), and logpb_dump_runtime().
Referenced by log_dump_stat(), and slogpb_dump_stat().
void xlogtb_dump_trantable (THREAD_ENTRY * thread_p, FILE * out_fp)
Definition at line 1433 of file log_tran_table.c.
References trantable::all_tdes, i, log_Gl, logtb_dump_tdes(), NULL, NULL_TRANID, NUM_TOTAL_TRAN_INDICES, TR_TABLE_CS_ENTER_READ_MODE, TR_TABLE_CS_EXIT, log_global::trantable, and log_tdes::trid.
Referenced by logtb_dump_trantable(), slogtb_dump_trantable(), and xlog_dump().
int xlogtb_get_mvcc_snapshot (THREAD_ENTRY * thread_p)
Definition at line 3829 of file log_tran_table.c.
References ASSERT_ERROR_AND_SET, logtb_get_mvcc_snapshot(), NO_ERROR, and NULL.
Referenced by log_get_mvcc_snapshot(), and slogtb_get_mvcc_snapshot().
int xlogtb_kill_or_interrupt_tran (THREAD_ENTRY * thread_p, int tran_id, bool is_dba_group_member, bool interrupt_only)
Definition at line 5807 of file log_tran_table.c.
References ARG_FILE_LINE, css_shutdown_conn_by_tran_index(), ER_ERROR_SEVERITY, ER_FAILED, ER_KILL_TR_NOT_ALLOWED, er_set(), error(), i, KILLSTMT_QUERY, KILLSTMT_TRAN, LOG_SYSTEM_TRAN_INDEX, logtb_check_kill_tran_auth(), logtb_find_interrupt(), LOGTB_RETRY_SLAM_MAX_TIMES, logtb_set_tran_index_interrupt(), NO_ERROR, and thread_sleep_for().
Referenced by sthread_kill_or_interrupt_tran().
int xlogtb_kill_tran_index (THREAD_ENTRY * thread_p, int kill_tran_index, char * kill_user, char * kill_host, int kill_pid)
Definition at line 5717 of file log_tran_table.c.
References ARG_FILE_LINE, ER_CSS_KILL_BAD_INTERFACE, ER_CSS_KILL_DOES_NOTMATCH, ER_CSS_KILL_UNKNOWN_TRANSACTION, ER_ERROR_SEVERITY, ER_FAILED, ER_KILL_TR_NOT_ALLOWED, er_set(), i, LOG_SYSTEM_TRAN_INDEX, logtb_find_client_name_host_pid(), LOGTB_RETRY_SLAM_MAX_TIMES, logtb_slam_transaction(), NO_ERROR, NULL, NULL_TRAN_INDEX, and thread_sleep_for().
Referenced by sthread_kill_tran_index().
Variable Documentation
int db_Disable_modifications
Definition at line 90 of file db_macro.c.
char log_Archive_path[]
Definition at line 86 of file log_global.c.
Referenced by log_recovery_notpartof_archives(), logpb_append_archives_removed_to_log_info(), logpb_archive_active_log(), logpb_checkpoint(), logpb_delete(), logpb_fatal_error_internal(), logpb_fetch_from_archive(), logpb_find_oldest_available_arv_num(), logpb_find_oldest_available_page_id(), logpb_initialize_log_names(), logpb_remove_all_in_log_path(), logpb_remove_archive_logs_internal(), and logpb_rename_all_volumes_files().
const char* log_Db_fullname
Definition at line 89 of file log_global.c.
Referenced by log_initialize_internal(), log_recovery_notpartof_volumes(), log_recovery_resetlog(), logpb_archive_active_log(), logpb_backup(), logpb_copy_database(), logpb_create_log_info(), logpb_fetch_from_archive(), logpb_find_oldest_available_page_id(), logpb_initialize_log_names(), logpb_recreate_volume_info(), and logpb_rename_all_volumes_files().
LOG_GLOBAL log_Gl
Referenced by boot_after_copydb(), btree_check_valid_record(), btree_leaf_change_first_object(), btree_rv_redo_global_unique_stats_commit(), btree_rv_undo_global_unique_stats_commit(), css_change_ha_server_state(), disk_can_overwrite_data_volume(), dwb_flush_block(), cubload::load_task::execute(), mvcctable::get_new_mvccid(), mvcctable::get_two_new_mvccid(), log_2pc_attach_client(), log_2pc_attach_global_tran(), log_2pc_check_duplicate_global_tran_id(), log_2pc_find_tran_descriptor(), log_2pc_get_global_tran_info(), log_2pc_prepare_global_tran(), log_2pc_recovery(), log_2pc_recovery_prepared(), log_2pc_set_global_tran_info(), log_abort_all_active_transaction(), log_active_log_header_start_scan(), LOG_APPEND_PTR(), log_append_repl_info_and_commit_log(), log_change_tran_as_completed(), log_commit(), log_complete(), log_complete_for_2pc(), log_create_internal(), log_final(), log_find_end_log(), log_find_unilaterally_largest_undo_lsa(), log_get_append_lsa(), log_get_crash_point_lsa(), log_get_db_start_parameters(), log_get_eof_lsa(), log_get_io_page_size(), log_get_restart_lsa(), log_initialize_internal(), log_is_in_crash_recovery_and_not_yet_completes_redo(), log_is_log_flush_daemon_available(), log_is_logged_since_restart(), log_prior_has_worker_log_records(), log_prior_lsa_append_add_align(), log_prior_lsa_append_advance_when_doesnot_fit(), log_prior_lsa_append_align(), log_recovery(), log_recovery_abort_all_atomic_sysops(), log_recovery_analysis(), log_recovery_finish_all_postpone(), log_recovery_notpartof_archives(), log_recovery_notpartof_volumes(), log_recovery_redo(), log_recovery_resetlog(), log_recovery_undo(), log_recreate(), LOG_RESET_APPEND_LSA(), LOG_RESET_PREV_LSA(), log_rv_analysis_log_end(), log_rv_outside_noop_redo(), log_set_db_restore_time(), log_set_ha_promotion_time(), log_set_no_logging(), log_skip_logging(), log_skip_logging_set_lsa(), logpb_append_crumbs(), logpb_append_data(), logpb_append_next_record(), logpb_append_prior_lsa_list(), logpb_archive_active_log(), logpb_background_archiving(), logpb_backup(), logpb_checkpoint(), logpb_checkpoint_topops(), logpb_copy_database(), logpb_copy_page_from_file(), logpb_copy_page_from_log_buffer(), logpb_decache_archive_info(), logpb_delete(), logpb_dismount_log_archive(), logpb_dump(), logpb_dump_information(), logpb_dump_log_header(), logpb_dump_to_flush_page(), logpb_end_append(), logpb_fatal_error_internal(), logpb_fetch_from_archive(), logpb_fetch_header(), logpb_fetch_header_from_active_log(), logpb_fetch_page(), logpb_fetch_start_append_page(), logpb_fetch_start_append_page_new(), logpb_finalize_flush_info(), logpb_finalize_pool(), logpb_finalize_writer_info(), logpb_find_header_parameters(), logpb_find_oldest_available_arv_num(), logpb_find_oldest_available_page_id(), logpb_flush_all_append_pages(), logpb_flush_header(), logpb_flush_log_for_wal(), logpb_flush_pages(), logpb_get_guess_archive_num(), logpb_initialize_flush_info(), logpb_initialize_pool(), logpb_invalid_all_append_pages(), logpb_is_archive_available(), logpb_last_complete_blockid(), logpb_need_wal(), logpb_next_append_page(), logpb_prior_lsa_append_all_list(), logpb_read_page_from_active_log(), logpb_read_page_from_file(), logpb_remove_all_in_log_path(), logpb_remove_archive_logs(), logpb_remove_archive_logs_exceed_limit(), logpb_rename_all_volumes_files(), logpb_restore(), logpb_set_unavailable_archive(), logpb_start_append(), logpb_write_page_to_disk(), logpb_write_toflush_pages_to_archive(), logpb_writev_append_pages(), logtb_allocate_tdes_area(), logtb_allocate_tran_index(), logtb_clear_tdes(), logtb_collect_local_clients(), logtb_complete_mvcc(), logtb_complete_sub_mvcc(), logtb_count_clients(), logtb_count_not_allowed_clients_in_maintenance_mode(), logtb_create_unique_stats_from_repr(), logtb_decrement_number_of_assigned_tran_indices(), logtb_define_trantable_log_latch(), logtb_delete_global_unique_stats(), logtb_descriptors_start_scan(), logtb_expand_trantable(), logtb_finalize_global_unique_stats_table(), logtb_finalize_mvcc_testing(), logtb_finalize_mvcctable(), logtb_find_current_tranid(), logtb_find_smallest_and_largest_active_pages(), logtb_find_smallest_lsa(), logtb_find_tran_index(), logtb_free_tran_index(), logtb_free_tran_index_with_undo_lsa(), logtb_get_current_mvccid(), logtb_get_global_unique_stats_entry(), logtb_get_mvcc_snapshot(), logtb_get_new_subtransaction_mvccid(), logtb_get_new_tran_id(), logtb_get_number_of_total_tran_indices(), logtb_get_system_tdes(), logtb_increment_number_of_assigned_tran_indices(), logtb_initialize_global_unique_stats_table(), logtb_initialize_mvcc_testing(), logtb_initialize_mvcctable(), logtb_is_active(), logtb_is_interrupted(), logtb_is_interrupted_tdes(), logtb_is_interrupted_tran(), logtb_istran_finished(), logtb_reflect_global_unique_stats_to_btree(), logtb_release_tran_index(), logtb_rv_update_global_unique_stats_by_abs(), logtb_set_loose_end_tdes(), logtb_set_num_loose_end_trans(), logtb_set_number_of_assigned_tran_indices(), logtb_set_number_of_total_tran_indices(), logtb_set_suppress_repl_on_transaction(), logtb_set_tran_index_interrupt(), logtb_undefine_trantable(), logtb_update_global_unique_stats_by_delta(), logwr_log_ha_filestat_to_string(), mvcc_is_active_id(), pgbuf_set_lsa(), prior_lsa_append_data(), prior_lsa_end_append(), prior_lsa_next_record_internal(), prior_lsa_remove_prior_list(), prior_lsa_start_append(), prior_update_header_mvcc_info(), redistribute_partition_data(), mvcctable::reset_start_mvccid(), vacuum_data::set_last_blockid(), vacuum_data::set_oldest_unvacuumed_on_boot(), test_mvcc_get_oldest(), test_mvcc_get_snapshot(), test_new_mvcc_complete(), vacuum_consume_buffer_log_blocks(), vacuum_data_load_and_recover(), vacuum_data_unload_first_and_last_page(), vacuum_process_log_block(), vacuum_produce_log_block_data(), vacuum_recover_lost_block_data(), vacuum_rv_check_at_undo(), vacuum_rv_notify_dropped_file(), vacuum_rv_redo_add_dropped_file(), vacuum_rv_redo_vacuum_complete(), vacuum_rv_replace_dropped_file(), vacuum_sa_reflect_last_blockid(), vacuum_verify_vacuum_data_debug(), xbtree_load_index(), xlocator_upgrade_instances_domain(), xlog_dump(), xlogtb_does_active_user_exist(), xlogtb_dump_trantable(), xlogtb_get_pack_tran_table(), and xvacuum().
char log_Name_active[]
Definition at line 90 of file log_global.c.
Referenced by alterdbhost(), log_create_internal(), log_get_charset_from_header_page(), log_get_io_page_size(), log_initialize_internal(), log_recovery_resetlog(), logpb_backup(), logpb_check_exist_any_volumes(), logpb_delete(), logpb_exist_log(), logpb_fetch_header_from_active_log(), logpb_find_header_parameters(), logpb_flush_all_append_pages(), logpb_initialize_log_names(), logpb_read_page_from_active_log(), logpb_read_page_from_file(), logpb_recreate_volume_info(), logpb_remove_all_in_log_path(), logpb_rename_all_volumes_files(), logpb_restore(), logpb_write_page_to_disk(), logpb_writev_append_pages(), xboot_soft_rename(), and xvacuum_dump().
char log_Name_bg_archive[]
Definition at line 94 of file log_global.c.
Referenced by log_initialize_internal(), logpb_archive_active_log(), logpb_delete(), logpb_initialize_log_names(), logpb_remove_all_in_log_path(), logpb_rename_all_volumes_files(), and logpb_write_toflush_pages_to_archive().
char log_Name_bkupinfo[]
Definition at line 92 of file log_global.c.
Referenced by log_create_internal(), logpb_backup(), logpb_delete(), logpb_initialize_log_names(), logpb_recreate_volume_info(), logpb_rename_all_volumes_files(), and logpb_restore().
char log_Name_info[]
Definition at line 91 of file log_global.c.
Referenced by log_create_internal(), log_recovery_notpartof_archives(), logpb_append_archives_removed_to_log_info(), logpb_archive_active_log(), logpb_backup(), logpb_check_exist_any_volumes(), logpb_checkpoint(), logpb_delete(), logpb_get_guess_archive_num(), logpb_initialize_log_names(), logpb_recreate_volume_info(), logpb_remove_all_in_log_path(), and logpb_rename_all_volumes_files().
char log_Name_removed_archive[]
Definition at line 95 of file log_global.c.
Referenced by logpb_archive_active_log(), logpb_delete(), logpb_initialize_log_names(), logpb_remove_all_in_log_path(), logpb_remove_archive_logs_internal(), and logpb_rename_all_volumes_files().
char log_Name_volinfo[]
Definition at line 93 of file log_global.c.
Referenced by logpb_add_volume(), logpb_check_exist_any_volumes(), logpb_create_volume_info(), logpb_find_volume_info_exist(), logpb_initialize_log_names(), logpb_recreate_volume_info(), logpb_rename_all_volumes_files(), and logpb_scan_volume_info().
char log_Path[]
Definition at line 47 of file log_global.c.
Referenced by logpb_backup(), logpb_delete(), and logpb_initialize_log_names().
char log_Prefix[]
Definition at line 87 of file log_global.c.
Referenced by log_recovery_notpartof_archives(), logpb_append_archives_removed_to_log_info(), logpb_archive_active_log(), logpb_checkpoint(), logpb_delete(), logpb_fatal_error_internal(), logpb_fetch_from_archive(), logpb_find_oldest_available_arv_num(), logpb_find_oldest_available_page_id(), logpb_initialize_log_names(), logpb_remove_all_in_log_path(), logpb_remove_archive_logs_internal(), logpb_rename_all_volumes_files(), and xvacuum_dump().
LOG_LOGGING_STAT log_Stat
Definition at line 273 of file log_page_buffer.c.
Referenced by log_change_tran_as_completed(), and log_is_log_flush_daemon_available().
const TRANID LOG_SYSTEM_WORKER_FIRST_TRANID = NULL_TRANID - 1
Definition at line 224 of file log_impl.h.
const int LOG_SYSTEM_WORKER_INCR_TRANID = -1
Definition at line 225 of file log_impl.h.
Referenced by systdes_claim_tdes().
int log_Tran_index
Definition at line 43 of file log_global.c.