CUBRID Engine: src/transaction/log_lsa.cpp File Reference
log_lsa.cpp File Reference
#include "log_lsa.hpp"
#include <cstdio>
Functions
void lsa_to_string (char *buf, int buf_size, const log_lsa *lsa)
Function Documentation
void lsa_to_string (char * buf, int buf_size, const log_lsa * lsa)
Definition at line 28 of file log_lsa.cpp.
References LSA_AS_ARGS.
Referenced by disk_volume_header_next_scan(), log_active_log_header_next_scan(), and logtb_descriptors_start_scan().