CUBRID Engine: src/transaction/log_system_tran.cpp File Reference
log_system_tran.cpp File Reference
#include "log_system_tran.hpp"
#include "log_impl.h"
#include "thread_entry.hpp"
#include "thread_manager.hpp"
#include <forward_list>
#include <mutex>
Functions
static log_tdes * systdes_create_tdes ()
static void systdes_remove_tdes_from_map (TRANID trid)
static void systdes_retire_tdes (log_tdes *tdes)
log_tdes * systdes_claim_tdes ()
Variables
std::mutex systb_Mutex
std::forward_list< log_tdes * > systb_Free_tdes_list
TRANID systb_Next_tranid = LOG_SYSTEM_WORKER_FIRST_TRANID
std::map< TRANID, log_tdes * > systb_System_tdes
Function Documentation
log_tdes* systdes_claim_tdes ()
Definition at line 76 of file log_system_tran.cpp.
References assert, LOG_ISRESTARTED, LOG_SYSTEM_WORKER_INCR_TRANID, NULL, NULL_TRANID, log_tdes::state, systb_Free_tdes_list, systb_Mutex, systb_Next_tranid, systb_System_tdes, systdes_create_tdes(), TRAN_ACTIVE, and log_tdes::trid.
Referenced by log_system_tdes::log_system_tdes().
static log_tdes* systdes_create_tdes () static
Definition at line 40 of file log_system_tran.cpp.
References LOG_SYSTEM_TRAN_INDEX, and logtb_initialize_tdes().
Referenced by log_system_tdes::log_system_tdes(), log_system_tdes::rv_get_or_alloc_tdes(), and systdes_claim_tdes().
static void systdes_remove_tdes_from_map (TRANID trid) static
Definition at line 48 of file log_system_tran.cpp.
References assert, and systb_System_tdes.
Referenced by systdes_retire_tdes().
static void systdes_retire_tdes (log_tdes * tdes) static
Definition at line 62 of file log_system_tran.cpp.
References logtb_clear_tdes(), NULL, systb_Free_tdes_list, systb_Mutex, systdes_remove_tdes_from_map(), and log_tdes::trid.
Referenced by log_system_tdes::~log_system_tdes().
Variable Documentation
std::forward_list<log_tdes *> systb_Free_tdes_list
Definition at line 33 of file log_system_tran.cpp.
Referenced by log_system_tdes::destroy_system_transactions(), systdes_claim_tdes(), and systdes_retire_tdes().
std::mutex systb_Mutex
Definition at line 32 of file log_system_tran.cpp.
Referenced by log_system_tdes::destroy_system_transactions(), log_system_tdes::map_all_tdes(), systdes_claim_tdes(), and systdes_retire_tdes().
TRANID systb_Next_tranid = LOG_SYSTEM_WORKER_FIRST_TRANID
Definition at line 34 of file log_system_tran.cpp.
Referenced by systdes_claim_tdes().
std::map<TRANID, log_tdes *> systb_System_tdes
Definition at line 37 of file log_system_tran.cpp.
Referenced by log_system_tdes::destroy_system_transactions(), log_system_tdes::map_all_tdes(), log_system_tdes::rv_delete_all_tdes_if(), log_system_tdes::rv_delete_tdes(), log_system_tdes::rv_final(), log_system_tdes::rv_get_or_alloc_tdes(), log_system_tdes::rv_get_tdes(), log_system_tdes::rv_simulate_system_tdes(), systdes_claim_tdes(), and systdes_remove_tdes_from_map().