CUBRID Engine: src/transaction/log_applier_sql_log.h File Reference
log_applier_sql_log.h File Reference
#include "dbtype_def.h"
#include "work_space.h"
Functions
int sl_write_statement_sql (char *class_name, char *db_user, int item_type, const char *ddl, char *ha_sys_prm)
int sl_write_insert_sql (DB_OTMPL *inst_tp, DB_VALUE *key)
int sl_write_update_sql (DB_OTMPL *inst_tp, DB_VALUE *key)
int sl_write_delete_sql (char *class_name, MOBJ mclass, DB_VALUE *key)
int sl_init (const char *db_name, const char *repl_log_path)
Function Documentation
int sl_init (const char * db_name, const char * repl_log_path)
Definition at line 171 of file log_applier_sql_log.c.
References basename(), catalog_fp, create_dir(), sl_info::curr_file_id, ER_FAILED, sl_info::last_inserted_sql_id, log_fp, NO_ERROR, NULL, sl_read_catalog(), sql_catalog_path, and sql_log_base_path.
Referenced by la_apply_log_file().
int sl_write_delete_sql (char * class_name, MOBJ mclass, DB_VALUE * key)
Definition at line 423 of file log_applier_sql_log.c.
References ER_FAILED, NO_ERROR, sl_print_pk(), sl_print_select(), and sl_write_sql().
Referenced by la_apply_delete_log().
int sl_write_insert_sql (DB_OTMPL * inst_tp, DB_VALUE * key)
Definition at line 335 of file log_applier_sql_log.c.
References obj_template::assignments, obj_template::class_, ER_FAILED, obj_template::nassigns, NO_ERROR, sl_print_insert_att_names(), sl_print_insert_att_values(), sl_print_select(), sl_write_sql(), and sm_ch_name().
Referenced by la_apply_insert_log().
int sl_write_statement_sql (char * class_name, char * db_user, int item_type, const char * ddl, char * ha_sys_prm)
Definition at line 445 of file log_applier_sql_log.c.
References string_buffer::clear(), CUBRID_STMT_CREATE_CLASS, ER_FAILED, error(), NO_ERROR, NULL, PRM_ERR_NO_ERROR, rc, sl_write_sql(), strlen, sysprm_make_default_values(), and sysprm_set_error().
Referenced by la_apply_statement_log().
int sl_write_update_sql (DB_OTMPL * inst_tp, DB_VALUE * key)
Definition at line 361 of file log_applier_sql_log.c.
References obj_template::assignments, obj_template::class_, ER_FAILED, string_buffer::get_buffer(), string_buffer::len(), obj_template::nassigns, NO_ERROR, NULL, numeric_db_value_add(), numeric_db_value_print(), NUMERIC_MAX_STRING_SIZE, sl_find_att_value(), sl_print_att_value(), sl_print_pk(), sl_print_select(), sl_print_update_att_set(), sl_write_sql(), sm_ch_name(), and trim_single_quote().
Referenced by la_apply_update_log().