CUBRID Engine: src/transaction/log_comm.h File Reference
log_comm.h File Reference
#include "dbtran_def.h"
#include "storage_common.h"
#include <stdio.h>
Macros
#define TRAN_LOCK_INFINITE_WAIT (-1)
#define TIME_SIZE_OF_DUMP_LOG_INFO 30
Typedefs
typedef DB_TRAN_ISOLATION TRAN_ISOLATION
Enumerations
enum TRAN_STATE {
TRAN_RECOVERY, TRAN_ACTIVE, TRAN_UNACTIVE_COMMITTED, TRAN_UNACTIVE_WILL_COMMIT,
TRAN_UNACTIVE_COMMITTED_WITH_POSTPONE, TRAN_UNACTIVE_TOPOPE_COMMITTED_WITH_POSTPONE, TRAN_UNACTIVE_ABORTED, TRAN_UNACTIVE_UNILATERALLY_ABORTED,
TRAN_UNACTIVE_2PC_PREPARE, TRAN_UNACTIVE_2PC_COLLECTING_PARTICIPANT_VOTES, TRAN_UNACTIVE_2PC_ABORT_DECISION, TRAN_UNACTIVE_2PC_COMMIT_DECISION,
TRAN_UNACTIVE_COMMITTED_INFORMING_PARTICIPANTS, TRAN_UNACTIVE_ABORTED_INFORMING_PARTICIPANTS, TRAN_UNACTIVE_UNKNOWN
}
enum LOG_RESULT_TOPOP { LOG_RESULT_TOPOP_COMMIT, LOG_RESULT_TOPOP_ABORT, LOG_RESULT_TOPOP_ATTACH_TO_OUTER }
Functions
const char * log_state_string (TRAN_STATE state)
const char * log_state_short_string (TRAN_STATE state)
const char * log_isolation_string (TRAN_ISOLATION isolation)
int log_dump_log_info (const char *logname_info, bool also_stdout, const char *fmt,...)
bool log_does_allow_replication (void)
Variables
const int LOG_MIN_NBUFFERS
Macro Definition Documentation
#define TIME_SIZE_OF_DUMP_LOG_INFO 30
Definition at line 31 of file log_comm.h.
Referenced by log_dump_log_info(), and logpb_get_guess_archive_num().
#define TRAN_LOCK_INFINITE_WAIT (-1)
Definition at line 29 of file log_comm.h.
Referenced by boot_client_all_finalize(), boot_restart_client(), boot_restart_server(), cubload::load_task::execute(), log_rollback(), logtb_initialize_system_tdes(), logtb_initialize_tdes(), and logtb_rv_find_allocate_tran_index().
Typedef Documentation
typedef DB_TRAN_ISOLATION TRAN_ISOLATION
Definition at line 81 of file log_comm.h.
Enumeration Type Documentation
enum LOG_RESULT_TOPOP
Enumerator
LOG_RESULT_TOPOP_COMMIT
LOG_RESULT_TOPOP_ABORT
LOG_RESULT_TOPOP_ATTACH_TO_OUTER
Definition at line 73 of file log_comm.h.
enum TRAN_STATE
Enumerator
TRAN_RECOVERY
TRAN_ACTIVE
TRAN_UNACTIVE_COMMITTED
TRAN_UNACTIVE_WILL_COMMIT
TRAN_UNACTIVE_COMMITTED_WITH_POSTPONE
TRAN_UNACTIVE_TOPOPE_COMMITTED_WITH_POSTPONE
TRAN_UNACTIVE_ABORTED
TRAN_UNACTIVE_UNILATERALLY_ABORTED
TRAN_UNACTIVE_2PC_PREPARE
TRAN_UNACTIVE_2PC_COLLECTING_PARTICIPANT_VOTES
TRAN_UNACTIVE_2PC_ABORT_DECISION
TRAN_UNACTIVE_2PC_COMMIT_DECISION
TRAN_UNACTIVE_COMMITTED_INFORMING_PARTICIPANTS
TRAN_UNACTIVE_ABORTED_INFORMING_PARTICIPANTS
TRAN_UNACTIVE_UNKNOWN
Definition at line 36 of file log_comm.h.
Function Documentation
bool log_does_allow_replication (void)
Definition at line 270 of file log_comm.c.
References assert, css_ha_server_state(), DB_CLIENT_TYPE_LOG_APPLIER, DB_CLIENT_TYPE_LOG_COPIER, db_Disable_modifications, db_get_client_type(), HA_DISABLED, HA_SERVER_STATE_ACTIVE, HA_SERVER_STATE_TO_BE_STANDBY, LOG_FIND_CURRENT_TDES(), and NULL.
Referenced by do_replicate_statement(), locator_add_or_remove_index_internal(), locator_update_force(), locator_update_index(), log_append_redo_crumbs(), log_append_undoredo_crumbs(), log_commit_local(), log_complete_for_2pc(), log_sysop_abort(), log_sysop_commit_internal(), qexec_execute_selupd_list(), serial_update_serial_object(), sm_truncate_class(), srepl_set_info(), tran_commit(), tran_server_abort(), tran_server_commit(), and xrepl_set_info().
int log_dump_log_info (const char * logname_info, bool also_stdout, const char * fmt, ...)
Definition at line 205 of file log_comm.c.
References ARG_FILE_LINE, ER_FAILED, ER_LOG_MOUNT_FAIL, er_set(), ER_WARNING_SEVERITY, NO_ERROR, NULL, prm_get_bool_value(), PRM_ID_LOG_TRACE_DEBUG, strlen, and TIME_SIZE_OF_DUMP_LOG_INFO.
Referenced by la_remove_archive_logs(), log_create_internal(), log_recovery_notpartof_archives(), logpb_append_archives_removed_to_log_info(), logpb_archive_active_log(), logpb_checkpoint(), logpb_copy_database(), logpb_create_log_info(), and logpb_rename_all_volumes_files().
const char* log_isolation_string (TRAN_ISOLATION isolation)
Definition at line 176 of file log_comm.c.
References i, log_Isolation_names, and isolation_name::name.
Referenced by logtb_descriptors_start_scan(), logtb_dump_tdes(), and xlock_dump().
const char* log_state_short_string (TRAN_STATE state)
Definition at line 152 of file log_comm.c.
References log_state_string().
Referenced by logtb_descriptors_start_scan().
const char* log_state_string (TRAN_STATE state)
Definition at line 125 of file log_comm.c.
References i, log_Tran_state_names, and tran_state_name::name.
Referenced by lock_demote_class_lock(), log_2pc_prepare_global_tran(), log_2pc_recovery_analysis_info(), log_2pc_set_global_tran_info(), log_2pc_start(), log_commit(), log_recovery_redo(), log_rv_analysis_run_postpone(), log_state_short_string(), logpb_dump_checkpoint_trans(), logtb_dump_tdes(), tran_2pc_prepare(), tran_2pc_prepare_global_tran(), tran_abort(), tran_commit(), tran_internal_abort_upto_savepoint(), and xlock_dump().
Variable Documentation
const int LOG_MIN_NBUFFERS
Definition at line 113 of file log_comm.c.