CUBRID Engine: src/transaction/log_comm.c File Reference
log_comm.c File Reference
#include "config.h"
#include <assert.h>
#include <sys/time.h>
#include "log_comm.h"
#include "memory_alloc.h"
#include "storage_common.h"
#include "error_manager.h"
#include "porting.h"
#include "environment_variable.h"
#include "system_parameter.h"
#include "misc_string.h"
#include "intl_support.h"
#include "log_common_impl.h"
Classes
struct tran_state_name
struct isolation_name
Typedefs
typedef struct tran_state_name TRAN_STATE_NAME
typedef struct isolation_name TRAN_ISOLATION_NAME
Functions
const char * log_state_string (TRAN_STATE state)
const char * log_state_short_string (TRAN_STATE state)
const char * log_isolation_string (TRAN_ISOLATION isolation)
int log_dump_log_info (const char *logname_info, bool also_stdout, const char *fmt,...)
bool log_does_allow_replication (void)
Variables
static TRAN_STATE_NAME log_Tran_state_names []
static TRAN_ISOLATION_NAME log_Isolation_names []
const int LOG_MIN_NBUFFERS = 3
Typedef Documentation
typedef struct isolation_name TRAN_ISOLATION_NAME
Definition at line 104 of file log_comm.c.
typedef struct tran_state_name TRAN_STATE_NAME
Definition at line 64 of file log_comm.c.
Function Documentation
bool log_does_allow_replication (void)
Definition at line 270 of file log_comm.c.
References assert, css_ha_server_state(), DB_CLIENT_TYPE_LOG_APPLIER, DB_CLIENT_TYPE_LOG_COPIER, db_Disable_modifications, db_get_client_type(), HA_DISABLED, HA_SERVER_STATE_ACTIVE, HA_SERVER_STATE_TO_BE_STANDBY, LOG_FIND_CURRENT_TDES(), and NULL.
Referenced by do_replicate_statement(), locator_add_or_remove_index_internal(), locator_update_force(), locator_update_index(), log_append_redo_crumbs(), log_append_undoredo_crumbs(), log_commit_local(), log_complete_for_2pc(), log_sysop_abort(), log_sysop_commit_internal(), qexec_execute_selupd_list(), serial_update_serial_object(), sm_truncate_class(), srepl_set_info(), tran_commit(), tran_server_abort(), tran_server_commit(), and xrepl_set_info().
int log_dump_log_info (const char * logname_info, bool also_stdout, const char * fmt, ...)
Definition at line 205 of file log_comm.c.
References ARG_FILE_LINE, ER_FAILED, ER_LOG_MOUNT_FAIL, er_set(), ER_WARNING_SEVERITY, NO_ERROR, NULL, prm_get_bool_value(), PRM_ID_LOG_TRACE_DEBUG, strlen, and TIME_SIZE_OF_DUMP_LOG_INFO.
Referenced by la_remove_archive_logs(), log_create_internal(), log_recovery_notpartof_archives(), logpb_append_archives_removed_to_log_info(), logpb_archive_active_log(), logpb_checkpoint(), logpb_copy_database(), logpb_create_log_info(), and logpb_rename_all_volumes_files().
const char* log_isolation_string (TRAN_ISOLATION isolation)
Definition at line 176 of file log_comm.c.
References i, log_Isolation_names, and isolation_name::name.
Referenced by logtb_descriptors_start_scan(), logtb_dump_tdes(), and xlock_dump().
const char* log_state_short_string (TRAN_STATE state)
Definition at line 152 of file log_comm.c.
References log_state_string().
Referenced by logtb_descriptors_start_scan().
const char* log_state_string (TRAN_STATE state)
Definition at line 125 of file log_comm.c.
References i, log_Tran_state_names, and tran_state_name::name.
Referenced by lock_demote_class_lock(), log_2pc_prepare_global_tran(), log_2pc_recovery_analysis_info(), log_2pc_set_global_tran_info(), log_2pc_start(), log_commit(), log_recovery_redo(), log_rv_analysis_run_postpone(), log_state_short_string(), logpb_dump_checkpoint_trans(), logtb_dump_tdes(), tran_2pc_prepare(), tran_2pc_prepare_global_tran(), tran_abort(), tran_commit(), tran_internal_abort_upto_savepoint(), and xlock_dump().
Variable Documentation
TRAN_ISOLATION_NAME log_Isolation_names[] static
Initial value:
= {
  {TRAN_SERIALIZABLE, "SERIALIZABLE"},
  {TRAN_REPEATABLE_READ, "REPEATABLE READ"},
  {TRAN_READ_COMMITTED, "COMMITTED READ"},
  {TRAN_UNKNOWN_ISOLATION, "TRAN_UNKNOWN_ISOLATION"}
}
Definition at line 106 of file log_comm.c.
Referenced by log_isolation_string().
const int LOG_MIN_NBUFFERS = 3
Definition at line 113 of file log_comm.c.
TRAN_STATE_NAME log_Tran_state_names[] static
Definition at line 66 of file log_comm.c.
Referenced by log_state_string().