CUBRID Engine: src/broker/log_top_string.c File Reference
log_top_string.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "cas_common.h"
#include "log_top_string.h"
Macros
#define STR_ALLOC_SIZE(X) (((X) + 1023) / 1024 * 1024)
Functions
T_STRING * t_string_make (int init_size)
void t_string_clear (T_STRING *t_str)
int t_string_add (T_STRING *t_str, char *str, int str_len)
int t_bind_string_add (T_STRING *t_str, char *str, int str_len, int bind_len)
void t_string_free (T_STRING *t_str)
char * t_string_str (T_STRING *t_str)
int t_string_len (T_STRING *t_str)
int t_string_bind_len (T_STRING *t_str)
Macro Definition Documentation
#define STR_ALLOC_SIZE (X) (((X) + 1023) / 1024 * 1024)
Definition at line 33 of file log_top_string.c.
Referenced by t_bind_string_add(), and t_string_make().
Function Documentation
int t_bind_string_add (T_STRING * t_str, char * str, int str_len, int bind_len)
Definition at line 74 of file log_top_string.c.
References t_string::alloc_size, t_string::bind_len, t_string::data, t_string::data_len, NULL, REALLOC, and STR_ALLOC_SIZE.
Referenced by t_string_add(), and ut_get_line().
int t_string_add (T_STRING * t_str, char * str, int str_len)
Definition at line 68 of file log_top_string.c.
References t_bind_string_add().
Referenced by log_top(), read_bind_value(), read_multi_line_sql(), sql_list_make(), and ut_get_line().
int t_string_bind_len (T_STRING * t_str)
Definition at line 114 of file log_top_string.c.
References t_string::bind_len.
Referenced by log_bind_value(), and log_converter().
void t_string_clear (T_STRING * t_str)
Definition at line 60 of file log_top_string.c.
References t_string::bind_len, t_string::data, and t_string::data_len.
Referenced by log_top(), sql_list_make(), t_string_make(), and ut_get_line().
void t_string_free (T_STRING * t_str)
Definition at line 92 of file log_top_string.c.
References t_string::data, and FREE_MEM.
Referenced by cas_runner(), log_top(), search_offset(), and sql_list_make().
int t_string_len (T_STRING * t_str)
Definition at line 108 of file log_top_string.c.
References t_string::data_len.
Referenced by cas_runner(), get_next_log_line(), log_converter(), log_top(), read_bind_value(), and ut_get_line().
T_STRING* t_string_make (int init_size)
Definition at line 36 of file log_top_string.c.
References t_string::alloc_size, t_string::data, FREE_MEM, MALLOC, NULL, STR_ALLOC_SIZE, and t_string_clear().
Referenced by cas_runner(), log_converter(), log_replay(), log_top(), search_offset(), and sql_list_make().
char* t_string_str (T_STRING * t_str)
Definition at line 102 of file log_top_string.c.
References t_string::data.
Referenced by cas_runner(), get_next_log_line(), log_converter(), log_top(), sql_list_make(), and ut_get_line().