CUBRID Engine: src/executables/master_util.c File Reference
master_util.c File Reference
#include "config.h"
#include <sys/types.h>
#include <signal.h>
#include <stdio.h>
#include "system_parameter.h"
#include "master_util.h"
Functions
bool master_util_config_startup (const char *db_name, int *port_id)
void master_util_wait_proc_terminate (int pid)
Function Documentation
bool master_util_config_startup (const char * db_name, int * port_id)
Definition at line 42 of file master_util.c.
References NO_ERROR, NULL, prm_get_master_port_id(), SYSPRM_IGNORE_INTL_PARAMS, and sysprm_load_and_init().
Referenced by main().
void master_util_wait_proc_terminate (int pid)
Definition at line 72 of file master_util.c.
References FALSE.
Referenced by css_process_shutdown(), and process_slave_kill().