CUBRID Engine: src/executables/master_request.h File Reference
master_request.h File Reference
#include "connection_defs.h"
#include "master_util.h"
Functions
void css_process_info_request (CSS_CONN_ENTRY *conn)
void css_process_stop_shutdown (void)
void css_process_start_shutdown (SOCKET_QUEUE_ENTRY *sock_entq, int timeout, char *buffer)
void css_process_heartbeat_request (CSS_CONN_ENTRY *conn)
void css_remove_entry_by_conn (CSS_CONN_ENTRY *conn_p, SOCKET_QUEUE_ENTRY **anchor_p)
void css_master_cleanup (int sig)
SOCKET_QUEUE_ENTRY * css_return_entry_of_server (char *name_p, SOCKET_QUEUE_ENTRY *anchor_p)
SOCKET_QUEUE_ENTRY * css_add_request_to_socket_queue (CSS_CONN_ENTRY *conn_p, int info_p, char *name_p, SOCKET fd, int fd_type, int pid, SOCKET_QUEUE_ENTRY **anchor_p)
SOCKET_QUEUE_ENTRY * css_return_entry_by_conn (CSS_CONN_ENTRY *conn_p, SOCKET_QUEUE_ENTRY **anchor_p)
Variables
SOCKET css_Master_socket_fd [2]
struct timeval * css_Master_timeout
int css_Master_timeout_value_in_seconds
int css_Master_timeout_value_in_microseconds
time_t css_Start_time
int css_Total_server_count
int css_Total_request_count
SOCKET_QUEUE_ENTRY * css_Master_socket_anchor
pthread_mutex_t css_Master_socket_anchor_lock
Function Documentation
SOCKET_QUEUE_ENTRY* css_add_request_to_socket_queue (CSS_CONN_ENTRY * conn_p, int info_p, char * name_p, SOCKET fd, int fd_type, int pid, SOCKET_QUEUE_ENTRY ** anchor_p)
Definition at line 1329 of file master.c.
References socket_queue_entry::conn_ptr, socket_queue_entry::db_error, socket_queue_entry::env_var, socket_queue_entry::error_p, FALSE, socket_queue_entry::fd, socket_queue_entry::fd_type, socket_queue_entry::ha_mode, socket_queue_entry::info_p, IS_MASTER_CONN_NAME_HA_APPLYLOG, IS_MASTER_CONN_NAME_HA_COPYLOG, IS_MASTER_CONN_NAME_HA_SERVER, socket_queue_entry::name, socket_queue_entry::next, NULL, p, socket_queue_entry::pid, pid, socket_queue_entry::port_id, socket_queue_entry::queue_p, strlen, TRUE, and socket_queue_entry::version_string.
Referenced by css_accept_new_request(), css_process_new_connection(), css_register_new_server(), css_register_new_server2(), and main().
void css_master_cleanup (int sig)
Definition at line 218 of file master.c.
References ARG_FILE_LINE, css_get_master_domain_path(), css_Master_socket_fd, css_shutdown_socket(), ER_HB_STOPPED, ER_NOTIFICATION_SEVERITY, HA_DISABLED, and MASTER_ER_SET.
Referenced by css_master_init(), hb_resource_job_demote_confirm_shutdown(), hb_resource_job_demote_start_shutdown(), hb_resource_job_proc_start(), hb_start_util_process(), and main().
void css_process_heartbeat_request (CSS_CONN_ENTRY * conn)
Definition at line 2011 of file master_request.c.
References ARG_FILE_LINE, css_cleanup_info_connection(), css_process_change_ha_mode(), css_process_deregister_ha_process(), css_process_get_eof(), css_process_register_ha_process(), css_receive_heartbeat_request(), error(), css_conn_entry::fd, hb_cleanup_conn_and_start_process(), INVALID_SOCKET, MASTER_ER_LOG_DEBUG, NO_ERRORS, NULL, SERVER_CHANGE_HA_MODE, SERVER_DEREGISTER_HA_PROCESS, SERVER_GET_EOF, and SERVER_REGISTER_HA_PROCESS.
Referenced by css_check_master_socket_input().
void css_process_info_request (CSS_CONN_ENTRY * conn)
Definition at line 1855 of file master_request.c.
References ACTIVATE_HEARTBEAT, CANCEL_SHUTDOWN, css_cleanup_info_connection(), css_process_activate_heartbeat(), css_process_all_count_info(), css_process_all_list_info(), css_process_deact_confirm_no_server(), css_process_deact_confirm_stop_all(), css_process_deact_stop_all(), css_process_deactivate_heartbeat(), css_process_get_server_ha_mode(), css_process_ha_admin_info(), css_process_ha_deregister_by_args(), css_process_ha_deregister_by_pid(), css_process_ha_node_list_info(), css_process_ha_ping_host_info(), css_process_ha_process_list_info(), css_process_ha_start_util_process(), css_process_is_registered_ha_proc(), css_process_kill_all_ha_process(), css_process_kill_immediate(), css_process_kill_master(), css_process_kill_slave(), css_process_reconfig_heartbeat(), css_process_request_count_info(), css_process_server_count_info(), css_process_server_list_info(), css_process_server_state(), css_process_shutdown(), css_process_shutdown_time_info(), css_process_start_time_info(), css_process_stop_shutdown(), css_receive_data(), css_receive_request(), DEACT_CONFIRM_NO_SERVER, DEACT_CONFIRM_STOP_ALL, DEACT_STOP_ALL, DEACTIVATE_HEARTBEAT, DEREGISTER_HA_PROCESS_BY_ARGS, DEREGISTER_HA_PROCESS_BY_PID, free_and_init, GET_ALL_COUNT, GET_ALL_LIST, GET_HA_ADMIN_INFO, GET_HA_NODE_LIST, GET_HA_NODE_LIST_VERBOSE, GET_HA_PING_HOST_INFO, GET_HA_PROCESS_LIST, GET_HA_PROCESS_LIST_VERBOSE, GET_REQUEST_COUNT, GET_SERVER_COUNT, GET_SERVER_HA_MODE, GET_SERVER_LIST, GET_SERVER_STATE, GET_SHUTDOWN_TIME, GET_START_TIME, IS_REGISTERED_HA_PROC, KILL_ALL_HA_PROCESS, KILL_MASTER_SERVER, KILL_SERVER_IMMEDIATE, KILL_SLAVE_SERVER, NO_ERRORS, NULL, rc, RECONFIG_HEARTBEAT, START_HA_UTIL_PROCESS, and START_SHUTDOWN.
Referenced by css_check_master_socket_input().
void css_process_start_shutdown (SOCKET_QUEUE_ENTRY * sock_entq, int timeout, char * buffer)
Definition at line 684 of file master_request.c.
References css_send_command_to_server(), css_send_message_to_server(), and SERVER_START_SHUTDOWN.
Referenced by css_process_kill_slave(), css_process_shutdown(), hb_resource_demote_start_shutdown_server_proc(), hb_resource_job_proc_dereg(), and hb_resource_shutdown_all_ha_procs().
void css_process_stop_shutdown (void)
Definition at line 753 of file master_request.c.
References css_Master_socket_anchor, css_Master_timeout, css_send_command_to_server(), socket_queue_entry::fd, free_and_init, IS_INVALID_SOCKET, IS_MASTER_CONN_NAME_DRIVER, IS_MASTER_CONN_NAME_HA_APPLYLOG, IS_MASTER_CONN_NAME_HA_COPYLOG, IS_MASTER_CONN_NAME_HA_SERVER, IS_MASTER_SOCKET_FD, socket_queue_entry::name, socket_queue_entry::next, NULL, and SERVER_STOP_SHUTDOWN.
Referenced by css_process_info_request().
void css_remove_entry_by_conn (CSS_CONN_ENTRY * conn_p, SOCKET_QUEUE_ENTRY ** anchor_p)
Definition at line 1287 of file master.c.
References css_free_entry(), socket_queue_entry::next, NULL, and p.
Referenced by css_check_master_socket_exception(), css_check_master_socket_input(), css_cleanup_info_connection(), css_master_select_error(), css_master_timeout(), css_send_to_existing_server(), hb_cleanup_conn_and_start_process(), hb_register_new_process(), and hb_resource_shutdown_all_ha_procs().
SOCKET_QUEUE_ENTRY* css_return_entry_by_conn (CSS_CONN_ENTRY * conn_p, SOCKET_QUEUE_ENTRY ** anchor_p)
Definition at line 1424 of file master.c.
References socket_queue_entry::conn_ptr, socket_queue_entry::next, NULL, and p.
Referenced by hb_get_process_info_string(), hb_resource_demote_start_shutdown_server_proc(), hb_resource_job_proc_dereg(), and hb_resource_shutdown_all_ha_procs().
SOCKET_QUEUE_ENTRY* css_return_entry_of_server (char * name_p, SOCKET_QUEUE_ENTRY * anchor_p)
Definition at line 1386 of file master.c.
References IS_MASTER_CONN_NAME_HA_SERVER, socket_queue_entry::name, socket_queue_entry::next, NULL, and p.
Referenced by css_accept_new_request(), css_process_server_state(), css_register_new_server(), css_register_new_server2(), and css_send_to_existing_server().
Variable Documentation
SOCKET_QUEUE_ENTRY* css_Master_socket_anchor
Definition at line 125 of file master.c.
Referenced by css_cleanup_info_connection(), css_process_all_count_info(), css_process_all_list_info(), css_process_get_server_ha_mode(), css_process_kill_immediate(), css_process_kill_slave(), css_process_server_count_info(), css_process_server_list_info(), css_process_server_state(), css_process_shutdown(), css_process_stop_shutdown(), hb_cleanup_conn_and_start_process(), hb_get_process_info_string(), hb_register_new_process(), hb_resource_demote_start_shutdown_server_proc(), hb_resource_job_proc_dereg(), and hb_resource_shutdown_all_ha_procs().
pthread_mutex_t css_Master_socket_anchor_lock
Definition at line 127 of file master.c.
Referenced by css_check_master_socket_exception(), css_check_master_socket_input(), css_master_init(), css_master_select_error(), css_master_timeout(), hb_resource_job_change_mode(), hb_resource_job_cleanup_all(), hb_resource_job_demote_start_shutdown(), hb_resource_job_proc_dereg(), and hb_thread_check_disk_failure().
SOCKET css_Master_socket_fd[2]
Definition at line 122 of file master.c.
Referenced by css_check_master_socket_exception(), css_check_master_socket_input(), css_master_cleanup(), css_process_kill_master(), and main().
struct timeval* css_Master_timeout
Definition at line 111 of file master.c.
Referenced by css_master_timeout(), css_process_shutdown(), css_process_shutdown_time_info(), and css_process_stop_shutdown().
int css_Master_timeout_value_in_microseconds
Definition at line 113 of file master.c.
Referenced by css_master_loop().
int css_Master_timeout_value_in_seconds
Definition at line 112 of file master.c.
Referenced by css_master_loop().
time_t css_Start_time
Definition at line 118 of file master.c.
Referenced by css_process_start_time_info(), and main().
int css_Total_request_count
Definition at line 119 of file master.c.
Referenced by css_process_new_connection(), and css_process_request_count_info().
int css_Total_server_count