CUBRID Engine: src/base/memory_hash.c File Reference
memory_hash.c File Reference
#include "config.h"
#include <stdio.h>
#include <assert.h>
#include "memory_hash.h"
#include "chartype.h"
#include "misc_string.h"
#include "error_manager.h"
#include "memory_alloc.h"
#include "message_catalog.h"
#include "environment_variable.h"
#include "set_object.h"
#include "language_support.h"
#include "intl_support.h"
#include "object_primitive.h"
#include "dbtype.h"
Macros
#define GET_PTR_FOR_HASH(key) (((UINT64)(key)) & 0xFFFFFFFFUL)
#define NPRIMES 170
Typedefs
typedef enum mht_put_opt MHT_PUT_OPT
Enumerations
enum mht_put_opt { MHT_OPT_DEFAULT = 0, MHT_OPT_KEEP_KEY = 1, MHT_OPT_INSERT_ONLY = 2, MHT_OPT_INSERT_IF_NOT_EXISTS = 4 }
Functions
static unsigned int mht_1str_pseudo_key (const void *key, int key_size)
static unsigned int mht_3str_pseudo_key (const void *key, int key_size, const unsigned int max_value)
static unsigned int mht_4str_pseudo_key (const void *key, int key_size)
static unsigned int mht_5str_pseudo_key (const void *key, int key_size)
static unsigned int mht_calculate_htsize (unsigned int ht_size)
static int mht_rehash (MHT_TABLE *ht)
static const void * mht_put_internal (MHT_TABLE *ht, const void *key, void *data, MHT_PUT_OPT opt)
static const void * mht_put2_internal (MHT_TABLE *ht, const void *key, void *data, MHT_PUT_OPT opt)
static const void * mht_put_hls_internal (MHT_HLS_TABLE *ht, const void *key, void *data, MHT_PUT_OPT opt)
static unsigned int mht_get_shiftmult32 (unsigned int key, const unsigned int ht_size)
unsigned int mht_2str_pseudo_key (const void *key, int key_size)
unsigned int mht_1strlowerhash (const void *key, const unsigned int ht_size)
unsigned int mht_1strhash (const void *key, const unsigned int ht_size)
unsigned int mht_2strhash (const void *key, const unsigned int ht_size)
unsigned int mht_3strhash (const void *key, const unsigned int ht_size)
unsigned int mht_4strhash (const void *key, const unsigned int ht_size)
unsigned int mht_5strhash (const void *key, const unsigned int ht_size)
unsigned int mht_numhash (const void *key, const unsigned int ht_size)
unsigned int mht_ptrhash (const void *key, const unsigned int ht_size)
unsigned int mht_valhash (const void *key, const unsigned int ht_size)
int mht_compare_ints_are_equal (const void *key1, const void *key2)
int mht_compare_logpageids_are_equal (const void *key1, const void *key2)
int mht_compare_identifiers_equal (const void *key1, const void *key2)
int mht_compare_strings_are_equal (const void *key1, const void *key2)
int mht_compare_ptrs_are_equal (const void *key1, const void *key2)
int mht_compare_dbvalues_are_equal (const void *key1, const void *key2)
MHT_TABLE * mht_create (const char *name, int est_size, unsigned int(*hash_func)(const void *key, unsigned int ht_size), int(*cmp_func)(const void *key1, const void *key2))
MHT_HLS_TABLE * mht_create_hls (const char *name, int est_size, unsigned int(*hash_func)(const void *key, unsigned int ht_size), int(*cmp_func)(const void *key1, const void *key2))
void mht_destroy (MHT_TABLE *ht)
void mht_destroy_hls (MHT_HLS_TABLE *ht)
int mht_clear (MHT_TABLE *ht, int(*rem_func)(const void *key, void *data, void *args), void *func_args)
int mht_clear_hls (MHT_HLS_TABLE *ht, int(*rem_func)(const void *key, void *data, void *args), void *func_args)
int mht_dump (THREAD_ENTRY *thread_p, FILE *out_fp, const MHT_TABLE *ht, const int print_id_opt, int(*print_func)(THREAD_ENTRY *thread_p, FILE *fp, const void *key, void *data, void *args), void *func_args)
int mht_dump_hls (THREAD_ENTRY *thread_p, FILE *out_fp, const MHT_HLS_TABLE *ht, const int print_id_opt, int(*print_func)(THREAD_ENTRY *thread_p, FILE *fp, const void *data, void *args), void *func_args)
void * mht_get (MHT_TABLE *ht, const void *key)
int mht_adjust_lru_list (MHT_TABLE *ht, HENTRY_PTR hentry)
void * mht_get2 (const MHT_TABLE *ht, const void *key, void **last)
void * mht_get_hls (const MHT_HLS_TABLE *ht, const void *key, void **last)
const void * mht_put_new (MHT_TABLE *ht, const void *key, void *data)
const void * mht_put_hls (MHT_HLS_TABLE *ht, const void *key, void *data)
const void * mht_put_if_not_exists (MHT_TABLE *ht, const void *key, void *data)
const void * mht_put_data (MHT_TABLE *ht, const void *key, void *data)
const void * mht_put (MHT_TABLE *ht, const void *key, void *data)
const void * mht_put2_new (MHT_TABLE *ht, const void *key, void *data)
int mht_rem (MHT_TABLE *ht, const void *key, int(*rem_func)(const void *key, void *data, void *args), void *func_args)
int mht_rem2 (MHT_TABLE *ht, const void *key, const void *data, int(*rem_func)(const void *key, void *data, void *args), void *func_args)
int mht_map (const MHT_TABLE *ht, int(*map_func)(const void *key, void *data, void *args), void *func_args)
int mht_map_no_key (THREAD_ENTRY *thread_p, const MHT_TABLE *ht, int(*map_func)(THREAD_ENTRY *thread_p, void *data, void *args), void *func_args)
unsigned int mht_count (const MHT_TABLE *ht)
unsigned int mht_get_hash_number (const int ht_size, const DB_VALUE *val)
Variables
static const float MHT_REHASH_TRESHOLD = 0.7f
static const float MHT_REHASH_FACTOR = 1.3f
static const unsigned int mht_Primes [NPRIMES]
Macro Definition Documentation
#define GET_PTR_FOR_HASH (key) (((UINT64)(key)) & 0xFFFFFFFFUL)
Definition at line 63 of file memory_hash.c.
Referenced by mht_ptrhash(), and mht_valhash().
#define NPRIMES 170
Definition at line 808 of file memory_hash.c.
Referenced by mht_calculate_htsize().
Typedef Documentation
typedef enum mht_put_opt MHT_PUT_OPT
Definition at line 78 of file memory_hash.c.
Enumeration Type Documentation
enum mht_put_opt
Enumerator
MHT_OPT_DEFAULT
MHT_OPT_KEEP_KEY
MHT_OPT_INSERT_ONLY
MHT_OPT_INSERT_IF_NOT_EXISTS
Definition at line 71 of file memory_hash.c.
Function Documentation
static unsigned int mht_1str_pseudo_key (const void * key, int key_size) static
Definition at line 128 of file memory_hash.c.
References assert, and NULL.
Referenced by mht_1strhash(), and mht_valhash().
unsigned int mht_1strhash (const void * key, const unsigned int ht_size)
Definition at line 447 of file memory_hash.c.
References assert, mht_1str_pseudo_key(), and NULL.
Referenced by ehash_hash_string_type(), locator_initialize(), shard_stmt_initialize(), and ws_init().
unsigned int mht_1strlowerhash (const void * key, const unsigned int ht_size)
Definition at line 420 of file memory_hash.c.
References assert, char_tolower(), and NULL.
unsigned int mht_2str_pseudo_key (const void * key, int key_size)
Definition at line 175 of file memory_hash.c.
References assert, i, and NULL.
Referenced by lang_mht2str_default(), and mht_2strhash().
unsigned int mht_2strhash (const void * key, const unsigned int ht_size)
Definition at line 466 of file memory_hash.c.
References assert, mht_2str_pseudo_key(), and NULL.
Referenced by ehash_hash_string_type().
static unsigned int mht_3str_pseudo_key (const void * key, int key_size, const unsigned int max_value) static
Definition at line 230 of file memory_hash.c.
References assert, and NULL.
Referenced by mht_3strhash().
unsigned int mht_3strhash (const void * key, const unsigned int ht_size)
Definition at line 483 of file memory_hash.c.
References assert, mht_3str_pseudo_key(), and NULL.
Referenced by ehash_hash_string_type().
static unsigned int mht_4str_pseudo_key (const void * key, int key_size) static
Definition at line 277 of file memory_hash.c.
References assert, and NULL.
Referenced by mht_4strhash().
unsigned int mht_4strhash (const void * key, const unsigned int ht_size)
Definition at line 505 of file memory_hash.c.
References assert, mht_4str_pseudo_key(), and NULL.
Referenced by pt_make_subclass_list().
static unsigned int mht_5str_pseudo_key (const void * key, int key_size) static
Definition at line 376 of file memory_hash.c.
References assert, i, and NULL.
Referenced by mht_5strhash().
unsigned int mht_5strhash (const void * key, const unsigned int ht_size)
Definition at line 521 of file memory_hash.c.
References mht_5str_pseudo_key().
Referenced by er_call_stack_init(), es_name_hash_func(), xtx_add_lob_locator(), xtx_change_state_of_locator(), xtx_drop_lob_locator(), and xtx_find_lob_locator().
int mht_adjust_lru_list (MHT_TABLE * ht, HENTRY_PTR hentry)
Definition at line 1457 of file memory_hash.c.
References assert, mht_table::build_lru_list, mht_table::lru_head, hentry::lru_next, hentry::lru_prev, mht_table::lru_tail, NO_ERROR, and NULL.
Referenced by mht_get().
static unsigned int mht_calculate_htsize (unsigned int ht_size) static
Definition at line 830 of file memory_hash.c.
References CEIL_PTVDIV, mht_Primes, and NPRIMES.
Referenced by mht_create(), mht_create_hls(), and mht_rehash().
int mht_clear (MHT_TABLE * ht, int(*)(const void *key, void *data, void *args) rem_func, void * func_args)
Definition at line 1180 of file memory_hash.c.
References mht_table::act_head, mht_table::act_tail, assert, hentry::data, i, hentry::key, mht_table::lru_head, mht_table::lru_tail, mht_table::ncollisions, mht_table::nentries, hentry::next, NO_ERROR, mht_table::nprealloc_entries, NULL, mht_table::prealloc_entries, and mht_table::table.
Referenced by logtb_tran_clear_update_stats(), qdata_save_agg_htable_to_list(), qexec_free_agg_hash_context(), qfile_clear_list_cache(), and qfile_initialize_list_cache().
int mht_clear_hls (MHT_HLS_TABLE * ht, int(*)(const void *key, void *data, void *args) rem_func, void * func_args)
Definition at line 1238 of file memory_hash.c.
References assert, hentry_hls::data, i, mht_hls_table::ncollisions, mht_hls_table::nentries, hentry_hls::next, NO_ERROR, mht_hls_table::nprealloc_entries, NULL, mht_hls_table::prealloc_entries, and mht_hls_table::table.
Referenced by scan_close_scan().
int mht_compare_dbvalues_are_equal (const void * key1, const void * key2)
Definition at line 791 of file memory_hash.c.
References DB_EQ, and tp_value_compare().
Referenced by qfile_compare_equal_db_value_array().
int mht_compare_identifiers_equal (const void * key1, const void * key2)
Definition at line 755 of file memory_hash.c.
References intl_identifier_casecmp().
Referenced by pt_associate_label_with_value().
int mht_compare_ints_are_equal (const void * key1, const void * key2)
Definition at line 731 of file memory_hash.c.
int mht_compare_logpageids_are_equal (const void * key1, const void * key2)
Definition at line 743 of file memory_hash.c.
Referenced by la_init_cache_log_buffer().
int mht_compare_ptrs_are_equal (const void * key1, const void * key2)
Definition at line 779 of file memory_hash.c.
Referenced by tr_init().
int mht_compare_strings_are_equal (const void * key1, const void * key2)
Definition at line 767 of file memory_hash.c.
Referenced by er_call_stack_init(), locator_initialize(), pt_make_subclass_list(), shard_stmt_initialize(), and ws_init().
unsigned int mht_count (const MHT_TABLE * ht)
Definition at line 2260 of file memory_hash.c.
References assert, mht_table::nentries, and NULL.
Referenced by heap_check_all_pages(), heap_chkreloc_end(), heap_chnguess_remove_entry(), heap_stats_add_bestspace(), heap_stats_del_bestspace_by_hfid(), heap_stats_del_bestspace_by_vpid(), qexec_groupby(), and qfile_dump_list_cache_internal().
MHT_TABLE* mht_create (const char * name, int est_size, unsigned int(*)(const void *key, unsigned int ht_size) hash_func, int(*)(const void *key1, const void *key2) cmp_func)
Definition at line 894 of file memory_hash.c.
References mht_table::act_head, mht_table::act_tail, ARG_FILE_LINE, assert, mht_table::build_lru_list, mht_table::cmp_func, db_create_fixed_heap(), db_destroy_fixed_heap(), DB_SIZEOF, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, mht_table::hash_func, mht_table::heap_id, mht_table::lru_head, mht_table::lru_tail, mht_calculate_htsize(), MHT_REHASH_TRESHOLD, mht_table::name, mht_table::ncollisions, mht_table::nentries, mht_table::nprealloc_entries, NULL, mht_table::prealloc_entries, mht_table::rehash_at, mht_table::size, and mht_table::table.
Referenced by catcls_initialize_class_oid_to_oid_hash_table(), er_call_stack_init(), heap_chkreloc_start(), heap_chnguess_initialize(), heap_stats_bestspace_initialize(), la_init_cache_log_buffer(), locator_all_reference_lockset(), locator_initialize(), locator_lock_set(), logtb_initialize_tdes(), logtb_initialize_tdes_for_mvcc_testing(), partition_cache_init(), pgbuf_initialize_aout_list(), pt_associate_label_with_value(), pt_make_subclass_list(), qexec_alloc_agg_hash_context(), qfile_initialize_list_cache(), serial_initialize_cache_pool(), shard_stmt_initialize(), tr_init(), and ws_init().
MHT_HLS_TABLE* mht_create_hls (const char * name, int est_size, unsigned int(*)(const void *key, unsigned int ht_size) hash_func, int(*)(const void *key1, const void *key2) cmp_func)
Definition at line 982 of file memory_hash.c.
References ARG_FILE_LINE, assert, mht_hls_table::build_lru_list, mht_hls_table::cmp_func, db_create_fixed_heap(), db_destroy_fixed_heap(), DB_SIZEOF, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, mht_hls_table::hash_func, mht_hls_table::heap_id, mht_calculate_htsize(), mht_hls_table::name, mht_hls_table::ncollisions, mht_hls_table::nentries, mht_hls_table::nprealloc_entries, NULL, mht_hls_table::prealloc_entries, mht_hls_table::size, and mht_hls_table::table.
Referenced by scan_open_list_scan().
void mht_destroy (MHT_TABLE * ht)
Definition at line 1140 of file memory_hash.c.
References assert, db_destroy_fixed_heap(), free_and_init, mht_table::heap_id, NULL, and mht_table::table.
Referenced by catcls_finalize_class_oid_to_oid_hash_table(), er_call_stack_final(), heap_chkreloc_end(), heap_chkreloc_start(), heap_chnguess_finalize(), heap_chnguess_initialize(), heap_stats_bestspace_finalize(), la_shutdown(), locator_all_reference_lockset(), locator_finalize(), locator_lock_set(), logtb_finalize_mvcc_testing(), logtb_tran_free_update_stats(), partition_cache_finalize(), pgbuf_finalize(), pgbuf_initialize_aout_list(), pt_free_label_table(), pt_make_subclass_list(), qexec_free_agg_hash_context(), qfile_finalize_list_cache(), qfile_initialize_list_cache(), serial_finalize_cache_pool(), shard_stmt_destroy(), tr_final(), ws_final(), and ws_init().
void mht_destroy_hls (MHT_HLS_TABLE * ht)
Definition at line 1160 of file memory_hash.c.
References assert, db_destroy_fixed_heap(), free_and_init, mht_hls_table::heap_id, NULL, and mht_hls_table::table.
Referenced by scan_close_scan().
int mht_dump (THREAD_ENTRY * thread_p, FILE * out_fp, const MHT_TABLE * ht, const int print_id_opt, int(*)(THREAD_ENTRY *thread_p, FILE *fp, const void *key, void *data, void *args) print_func, void * func_args)
Definition at line 1299 of file memory_hash.c.
References mht_table::act_head, hentry::act_next, assert, hentry::data, i, hentry::key, mht_table::name, mht_table::ncollisions, mht_table::nentries, hentry::next, mht_table::nprealloc_entries, NULL, mht_table::rehash_at, mht_table::size, mht_table::table, and TRUE.
Referenced by locator_dump_class_names(), and qfile_dump_list_cache_internal().
int mht_dump_hls (THREAD_ENTRY * thread_p, FILE * out_fp, const MHT_HLS_TABLE * ht, const int print_id_opt, int(*)(THREAD_ENTRY *thread_p, FILE *fp, const void *data, void *args) print_func, void * func_args)
Definition at line 1369 of file memory_hash.c.
References assert, hentry_hls::data, i, mht_hls_table::name, mht_hls_table::ncollisions, mht_hls_table::nentries, hentry_hls::next, mht_hls_table::nprealloc_entries, NULL, mht_hls_table::size, mht_hls_table::table, and TRUE.
Referenced by scan_close_scan().
void* mht_get (MHT_TABLE * ht, const void * key)
Definition at line 1419 of file memory_hash.c.
References assert, mht_table::cmp_func, hentry::data, mht_table::hash_func, hentry::key, mht_adjust_lru_list(), hentry::next, NULL, mht_table::size, and mht_table::table.
Referenced by catcls_find_oid(), catcls_replace_entry_oid(), heap_chkreloc_end(), heap_chkreloc_next(), heap_chnguess_decache(), heap_chnguess_get(), heap_chnguess_put(), heap_stats_add_bestspace(), heap_stats_del_bestspace_by_vpid(), la_get_page_buffer(), la_release_page_buffer(), locator_all_reference_lockset(), locator_check_class_names(), locator_drop_class_name_entry(), locator_lock_set(), locator_permoid_class_name(), locator_savepoint_class_name_entry(), logtb_tran_find_btid_stats(), logtb_tran_find_class_cos(), partition_load_context_from_cache(), pgbuf_remove_vpid_from_aout_list(), pt_associate_label_with_value(), pt_find_value_of_label(), pt_make_subclass_list(), qexec_hash_gby_agg_tuple(), qfile_lookup_list_cache_entry(), qfile_update_list_cache_entry(), shard_stmt_del_statement_from_map(), shard_stmt_find_by_sql(), shard_stmt_put_statement_to_map(), tr_map_trigger(), ws_add_classname(), ws_find_class(), xlocator_delete_class_name(), xlocator_find_class_oid(), xlocator_find_lockhint_class_oids(), xlocator_get_reserved_class_name_oid(), xlocator_rename_class_name(), xlocator_reserve_class_name(), xserial_decache(), xserial_get_current_value(), xserial_get_next_value(), and xserial_get_next_value_internal().
void* mht_get2 (const MHT_TABLE * ht, const void * key, void ** last)
Definition at line 1496 of file memory_hash.c.
References assert, mht_table::cmp_func, hentry::data, mht_table::hash_func, hentry::key, hentry::next, NULL, mht_table::size, and mht_table::table.
Referenced by heap_check_all_pages(), heap_stats_del_bestspace_by_hfid(), heap_stats_find_page_in_bestspace(), and qexec_clear_list_cache_by_class().
unsigned int mht_get_hash_number (const int ht_size, const DB_VALUE * val)
Definition at line 2275 of file memory_hash.c.
References ARG_FILE_LINE, db_numeric::buf, db_numeric::d, db_data::d, db_value::data, db_datetime::date, db_data::date, db_datetimetz::datetime, db_data::datetime, db_data::datetimetz, db_get_bigint(), db_get_json_raw_body(), db_get_string(), db_get_string_collation(), db_get_string_size(), DB_IS_NULL, db_private_free, DB_TYPE_BIGINT, DB_TYPE_BIT, DB_TYPE_CHAR, DB_TYPE_DATE, DB_TYPE_DATETIME, DB_TYPE_DATETIMELTZ, DB_TYPE_DATETIMETZ, DB_TYPE_DOUBLE, DB_TYPE_ENUMERATION, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_JSON, DB_TYPE_MONETARY, DB_TYPE_MULTISET, DB_TYPE_NCHAR, DB_TYPE_NUMERIC, DB_TYPE_OID, DB_TYPE_SEQUENCE, DB_TYPE_SET, DB_TYPE_SMALLINT, DB_TYPE_TIME, DB_TYPE_TIMESTAMP, DB_TYPE_TIMESTAMPLTZ, DB_TYPE_TIMESTAMPTZ, DB_TYPE_VARBIT, DB_TYPE_VARCHAR, DB_TYPE_VARNCHAR, DB_TYPE_VOBJ, db_value_type(), db_set::disk_set, db_set::disk_size, db_data::enumeration, er_log_debug, db_data::f, i, db_data::i, LANG_COLL_BINARY, MHT2STR_COLL, mht_get_shiftmult32(), NULL, db_data::num, db_data::oid, db_identifier::pageid, db_data::set, db_data::sh, db_enum_element::short_val, db_identifier::slotid, strlen, db_datetime::time, db_data::time, db_timestamptz::timestamp, db_data::timestamptz, db_data::utime, and db_identifier::volid.
Referenced by partition_prune_hash(), qdata_hash_agg_hkey(), and qdata_hash_scan_key().
void* mht_get_hls (const MHT_HLS_TABLE * ht, const void * key, void ** last)
Definition at line 1550 of file memory_hash.c.
References assert, hentry_hls::data, mht_hls_table::hash_func, NULL, mht_hls_table::size, and mht_hls_table::table.
Referenced by scan_hash_probe_next().
static unsigned int mht_get_shiftmult32 (unsigned int key, const unsigned int ht_size) static
Definition at line 2512 of file memory_hash.c.
Referenced by mht_get_hash_number().
int mht_map (const MHT_TABLE * ht, int(*)(const void *key, void *data, void *args) map_func, void * func_args)
Definition at line 2199 of file memory_hash.c.
References mht_table::act_head, hentry::act_next, assert, hentry::data, hentry::key, NO_ERROR, and NULL.
Referenced by catcls_finalize_class_oid_to_oid_hash_table(), er_call_stack_final(), heap_chkreloc_end(), heap_chnguess_decache(), locator_check_class_names(), locator_drop_transient_class_name_entries(), locator_finalize(), locator_initialize(), partition_cache_finalize(), pt_find_value_of_label(), pt_free_label_table(), and tr_final().
int mht_map_no_key (THREAD_ENTRY * thread_p, const MHT_TABLE * ht, int(*)(THREAD_ENTRY *thread_p, void *data, void *args) map_func, void * func_args)
Definition at line 2231 of file memory_hash.c.
References mht_table::act_head, hentry::act_next, assert, hentry::data, NO_ERROR, and NULL.
Referenced by heap_stats_bestspace_finalize(), log_update_global_btid_online_index_stats(), logtb_load_global_statistics_to_tran(), logtb_tran_reset_count_optim_state(), logtb_tran_update_all_global_unique_stats(), qfile_clear_list_cache(), qfile_finalize_list_cache(), and qfile_initialize_list_cache().
unsigned int mht_numhash (const void * key, const unsigned int ht_size)
Definition at line 533 of file memory_hash.c.
References assert, and NULL.
unsigned int mht_ptrhash (const void * key, const unsigned int ht_size)
Definition at line 547 of file memory_hash.c.
References assert, GET_PTR_FOR_HASH, and NULL.
Referenced by tr_init().
const void* mht_put (MHT_TABLE * ht, const void * key, void * data)
Definition at line 1778 of file memory_hash.c.
References assert, MHT_OPT_DEFAULT, mht_put_internal(), and NULL.
Referenced by heap_chkreloc_next(), heap_stats_add_bestspace(), la_get_page_buffer(), locator_all_reference_lockset(), locator_initialize(), locator_lock_set(), logtb_tran_create_btid_unique_stats(), logtb_tran_create_class_cos(), pgbuf_add_vpid_to_aout_list(), pt_associate_label_with_value(), pt_make_subclass_list(), qexec_hash_gby_agg_tuple(), shard_stmt_del_statement_from_map(), shard_stmt_put_statement_to_map(), tr_create_trigger(), tr_map_trigger(), ws_add_classname(), xlocator_reserve_class_name(), and xserial_get_next_value_internal().
static const void * mht_put2_internal (MHT_TABLE * ht, const void * key, void * data, MHT_PUT_OPT opt) static
Definition at line 1802 of file memory_hash.c.
References mht_table::act_head, hentry::act_next, hentry::act_prev, mht_table::act_tail, assert, mht_table::build_lru_list, mht_table::cmp_func, hentry::data, db_fixed_alloc(), DB_SIZEOF, mht_table::hash_func, mht_table::heap_id, hentry::key, mht_table::lru_head, hentry::lru_next, hentry::lru_prev, mht_table::lru_tail, MHT_OPT_INSERT_ONLY, MHT_OPT_KEEP_KEY, mht_rehash(), mht_table::ncollisions, mht_table::nentries, hentry::next, mht_table::nprealloc_entries, NULL, mht_table::prealloc_entries, mht_table::rehash_at, mht_table::size, and mht_table::table.
Referenced by mht_put2_new().
const void* mht_put2_new (MHT_TABLE * ht, const void * key, void * data)
Definition at line 1901 of file memory_hash.c.
References assert, MHT_OPT_DEFAULT, MHT_OPT_INSERT_ONLY, MHT_OPT_KEEP_KEY, mht_put2_internal(), and NULL.
const void* mht_put_data (MHT_TABLE * ht, const void * key, void * data)
Definition at line 1756 of file memory_hash.c.
References assert, MHT_OPT_KEEP_KEY, mht_put_internal(), and NULL.
Referenced by pt_associate_label_with_value().
const void* mht_put_hls (MHT_HLS_TABLE * ht, const void * key, void * data)
Definition at line 1730 of file memory_hash.c.
References assert, MHT_OPT_INSERT_ONLY, mht_put_hls_internal(), and NULL.
Referenced by scan_build_hash_list_scan().
static const void * mht_put_hls_internal (MHT_HLS_TABLE * ht, const void * key, void * data, MHT_PUT_OPT opt) static
Definition at line 2567 of file memory_hash.c.
References assert, hentry_hls::data, db_fixed_alloc(), DB_SIZEOF, mht_hls_table::hash_func, mht_hls_table::heap_id, mht_hls_table::ncollisions, mht_hls_table::nentries, hentry_hls::next, mht_hls_table::nprealloc_entries, NULL, mht_hls_table::prealloc_entries, mht_hls_table::size, mht_hls_table::table, and hentry_hls::tail.
Referenced by mht_put_hls().
const void* mht_put_if_not_exists (MHT_TABLE * ht, const void * key, void * data)
Definition at line 1749 of file memory_hash.c.
References assert, MHT_OPT_INSERT_IF_NOT_EXISTS, mht_put_internal(), and NULL.
Referenced by catcls_put_entry(), and partition_cache_pruning_context().
static const void * mht_put_internal (MHT_TABLE * ht, const void * key, void * data, MHT_PUT_OPT opt) static
Definition at line 1604 of file memory_hash.c.
References mht_table::act_head, hentry::act_next, hentry::act_prev, mht_table::act_tail, assert, mht_table::build_lru_list, mht_table::cmp_func, hentry::data, db_fixed_alloc(), DB_SIZEOF, mht_table::hash_func, mht_table::heap_id, hentry::key, mht_table::lru_head, hentry::lru_next, hentry::lru_prev, mht_table::lru_tail, MHT_OPT_INSERT_IF_NOT_EXISTS, MHT_OPT_INSERT_ONLY, MHT_OPT_KEEP_KEY, mht_rehash(), mht_table::ncollisions, mht_table::nentries, hentry::next, mht_table::nprealloc_entries, NULL, mht_table::prealloc_entries, mht_table::rehash_at, mht_table::size, and mht_table::table.
Referenced by mht_put(), mht_put_data(), mht_put_if_not_exists(), and mht_put_new().
const void* mht_put_new (MHT_TABLE * ht, const void * key, void * data)
Definition at line 1723 of file memory_hash.c.
References assert, MHT_OPT_INSERT_ONLY, mht_put_internal(), and NULL.
Referenced by heap_stats_add_bestspace(), and qfile_update_list_cache_entry().
static int mht_rehash (MHT_TABLE * ht) static
Definition at line 1060 of file memory_hash.c.
References ARG_FILE_LINE, DB_SIZEOF, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), est_size, free_and_init, mht_table::hash_func, i, hentry::key, mht_calculate_htsize(), MHT_REHASH_FACTOR, MHT_REHASH_TRESHOLD, mht_table::ncollisions, mht_table::nentries, hentry::next, NO_ERROR, NULL, mht_table::rehash_at, mht_table::size, and mht_table::table.
Referenced by mht_put2_internal(), and mht_put_internal().
int mht_rem (MHT_TABLE * ht, const void * key, int(*)(const void *key, void *data, void *args) rem_func, void * func_args)
Definition at line 1952 of file memory_hash.c.
References mht_table::act_head, hentry::act_next, hentry::act_prev, mht_table::act_tail, assert, mht_table::build_lru_list, mht_table::cmp_func, hentry::data, ER_FAILED, mht_table::hash_func, hentry::key, mht_table::lru_head, hentry::lru_next, hentry::lru_prev, mht_table::lru_tail, mht_table::ncollisions, mht_table::nentries, hentry::next, NO_ERROR, mht_table::nprealloc_entries, NULL, mht_table::prealloc_entries, mht_table::size, and mht_table::table.
Referenced by catcls_remove_entry(), do_drop_variable(), heap_chkreloc_end(), heap_chkreloc_next(), heap_chkreloc_print_notfound(), heap_chnguess_remove_entry(), heap_stats_add_bestspace(), heap_stats_del_bestspace_by_hfid(), heap_stats_del_bestspace_by_vpid(), heap_stats_find_page_in_bestspace(), la_cache_buffer_replace(), la_decache_page_buffers(), la_get_page_buffer(), la_invalidate_page_buffer(), locator_force_drop_class_name_entry(), partition_decache_class(), pgbuf_add_vpid_to_aout_list(), pgbuf_remove_private_from_aout_list(), pgbuf_remove_vpid_from_aout_list(), qexec_hash_gby_agg_tuple(), shard_stmt_del_statement_from_map(), tr_create_trigger(), tr_unmap_trigger(), ws_add_classname(), ws_drop_classname(), xlocator_reserve_class_name(), and xserial_decache().
int mht_rem2 (MHT_TABLE * ht, const void * key, const void * data, int(*)(const void *key, void *data, void *args) rem_func, void * func_args)
Definition at line 2078 of file memory_hash.c.
References mht_table::act_head, hentry::act_next, hentry::act_prev, mht_table::act_tail, assert, mht_table::build_lru_list, mht_table::cmp_func, hentry::data, ER_FAILED, mht_table::hash_func, hentry::key, mht_table::lru_head, hentry::lru_next, hentry::lru_prev, mht_table::lru_tail, mht_table::ncollisions, mht_table::nentries, hentry::next, NO_ERROR, mht_table::nprealloc_entries, NULL, mht_table::prealloc_entries, mht_table::size, and mht_table::table.
Referenced by heap_stats_del_bestspace_by_hfid(), heap_stats_del_bestspace_by_vpid(), heap_stats_find_page_in_bestspace(), and qfile_delete_list_cache_entry().
unsigned int mht_valhash (const void * key, const unsigned int ht_size)
Definition at line 561 of file memory_hash.c.
References db_monetary::amount, db_datetime::date, db_datetimetz::datetime, db_get_bigint(), db_get_bit(), db_get_date(), db_get_datetime(), db_get_datetimetz(), db_get_double(), db_get_float(), db_get_int(), db_get_midxkey(), db_get_monetary(), db_get_numeric(), db_get_object(), db_get_oid(), db_get_pointer(), db_get_set(), db_get_short(), db_get_string(), db_get_string_size(), db_get_time(), db_get_timestamp(), db_get_timestamptz(), db_make_null(), DB_TYPE_BIGINT, DB_TYPE_BIT, DB_TYPE_BLOB, DB_TYPE_CHAR, DB_TYPE_CLOB, DB_TYPE_DATE, DB_TYPE_DATETIME, DB_TYPE_DATETIMELTZ, DB_TYPE_DATETIMETZ, DB_TYPE_DB_VALUE, DB_TYPE_DOUBLE, DB_TYPE_ERROR, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_MIDXKEY, DB_TYPE_MONETARY, DB_TYPE_MULTISET, DB_TYPE_NCHAR, DB_TYPE_NULL, DB_TYPE_NUMERIC, DB_TYPE_OBJECT, DB_TYPE_OID, DB_TYPE_POINTER, DB_TYPE_RESULTSET, DB_TYPE_SEQUENCE, DB_TYPE_SET, DB_TYPE_SHORT, DB_TYPE_SUB, DB_TYPE_TABLE, DB_TYPE_TIME, DB_TYPE_TIMESTAMP, DB_TYPE_TIMESTAMPLTZ, DB_TYPE_TIMESTAMPTZ, DB_TYPE_VARBIT, DB_TYPE_VARCHAR, DB_TYPE_VARNCHAR, DB_TYPE_VOBJ, db_value_type(), GET_PTR_FOR_HASH, mht_1str_pseudo_key(), mht_valhash(), NO_ERROR, NULL, OID_PSEUDO_KEY, pr_clear_value(), pr_midxkey_get_element_nocopy(), set_get_element(), set_size(), db_midxkey::size, db_datetime::time, and db_timestamptz::timestamp.
Referenced by mht_valhash(), qfile_hash_db_value_array(), ws_rehash_vmop(), and ws_vmop().
Variable Documentation
const unsigned int mht_Primes[NPRIMES] static
Initial value:
= {
  11, 23, 37, 53, 67, 79, 97, 109, 127, 149,
  167, 191, 211, 227, 251, 269, 293, 311, 331, 349,
  367, 389, 409, 431, 449, 467, 487, 509, 541, 563,
  587, 607, 631, 653, 673, 521, 541, 557, 569, 587,
  599, 613, 641, 673, 701, 727, 751, 787, 821, 853,
  881, 907, 941, 977, 1039, 1087, 1129, 1171, 1213, 1259,
  1301, 1361, 1409, 1471, 1523, 1579, 1637, 1693, 1747, 1777,
  1823, 1867, 1913, 1973, 2017, 2129, 2237, 2339, 2441, 2543,
  2647, 2749, 2851, 2953, 3061, 3163, 3271, 3373, 3491, 3593,
  3697, 3803, 3907, 4013, 4177, 4337, 4493, 4649, 4801, 4957,
  5059, 5167, 5273, 5381, 5483, 5591, 5693, 5801, 5903, 6007,
  6113, 6217, 6317, 6421, 6521, 6637, 6737, 6841, 6847, 7057,
  7283, 7487, 7687, 7901, 8101, 8311, 8513, 8713, 8923, 9127,
  9337, 9539, 9739, 9941, 10141, 10343, 10559, 10771, 10973, 11177,
  11383, 11587, 11789, 12007, 12409, 12809, 13217, 13619, 14029, 14431,
  14831, 15233, 15641, 16057, 16477, 16879, 17291, 18097, 18899, 19699,
  20507, 21313, 22123, 23131, 24133, 25147, 26153, 27179, 28181, 29123
}
Definition at line 809 of file memory_hash.c.
Referenced by mht_calculate_htsize().
const float MHT_REHASH_FACTOR = 1.3f static
Definition at line 68 of file memory_hash.c.
Referenced by mht_rehash().
const float MHT_REHASH_TRESHOLD = 0.7f static
Definition at line 67 of file memory_hash.c.
Referenced by mht_create(), and mht_rehash().