CUBRID Engine: src/query/method_scan.c File Reference
method_scan.c File Reference
#include "config.h"
#include <string.h>
#include "method_scan.h"
#include "network_interface_sr.h"
#include "object_accessor.h"
#include "dbi.h"
#include "authenticate.h"
#include "xasl.h"
#include "dbtype.h"
#include "object_primitive.h"
#include "object_representation.h"
#include "query_list.h"
#include "regu_var.hpp"
Macros
#define ENTER_SERVER_IN_METHOD_CALL(save_pri_heap_id_)
#define EXIT_SERVER_IN_METHOD_CALL(save_pri_heap_id_)
Functions
static int method_open_value_array_scan (METHOD_SCAN_BUFFER *scan_buf)
static int method_close_value_array_scan (METHOD_SCAN_BUFFER *scan_buf)
static SCAN_CODE method_scan_next_value_array (METHOD_SCAN_BUFFER *scan_buf, VAL_LIST *val_list)
static int method_invoke (THREAD_ENTRY *thread_p, METHOD_SCAN_BUFFER *scan_buf)
static SCAN_CODE method_receive_results (THREAD_ENTRY *thread_p, METHOD_SCAN_BUFFER *scan_buf)
static void method_clear_scan_buffer (METHOD_SCAN_BUFFER *scan_buf)
int method_open_scan (THREAD_ENTRY *thread_p, METHOD_SCAN_BUFFER *scan_buffer_p, qfile_list_id *list_id_p, method_sig_list *method_sig_list_p)
int method_close_scan (THREAD_ENTRY *thread_p, METHOD_SCAN_BUFFER *scan_buffer_p)
SCAN_CODE method_scan_next (THREAD_ENTRY *thread_p, METHOD_SCAN_BUFFER *scan_buffer_p, val_list_node *value_list_p)
static int method_invoke_from_stand_alone (METHOD_SCAN_BUFFER *scan_buffer_p)
static SCAN_CODE method_receive_results_for_stand_alone (METHOD_SCAN_BUFFER *scan_buffer_p)
Variables
unsigned int db_on_server
int method_Num_method_jsp_calls = 0
Macro Definition Documentation
#define ENTER_SERVER_IN_METHOD_CALL (save_pri_heap_id_)
Value:
do { \
    db_on_server = 1; \
    private_heap_id = save_pri_heap_id_; \
  } while (0)
Definition at line 56 of file method_scan.c.
Referenced by method_receive_results_for_stand_alone().
#define EXIT_SERVER_IN_METHOD_CALL (save_pri_heap_id_)
Value:
do { \
     save_pri_heap_id_ = private_heap_id; \
     private_heap_id = 0; \
     db_on_server = 0; \
  } while (0)
Definition at line 62 of file method_scan.c.
Referenced by method_receive_results_for_stand_alone().
Function Documentation
static void method_clear_scan_buffer (METHOD_SCAN_BUFFER * scan_buf) static
Definition at line 606 of file method_scan.c.
References vacomm_buffer::action, vacomm_buffer::area, ARG_FILE_LINE, vacomm_buffer::buffer, cursor_id::buffer, method_scan_buffer::crs_id, vacomm_buffer::cur_pos, cursor_close(), db_value_clear(), ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, i, METHOD_EOF, METHOD_ERROR, method_initialize_vacomm_buffer(), METHOD_SUCCESS, NO_ERROR, NULL, vacomm_buffer::num_vals, method_scan_buffer::oid_cols, or_unpack_db_value(), or_unpack_int(), OR_VALUE_ALIGNED_SIZE, p, S_END, S_ERROR, S_SUCCESS, vacomm_buffer::size, VACOMM_BUFFER_HEADER_ERROR_OFFSET, VACOMM_BUFFER_HEADER_LENGTH_OFFSET, VACOMM_BUFFER_HEADER_NO_VALS_OFFSET, VACOMM_BUFFER_HEADER_SIZE, VACOMM_BUFFER_HEADER_STATUS_OFFSET, VACOMM_BUFFER_SEND, method_scan_buffer::val_cnt, method_scan_buffer::vallist, method_scan_buffer::valptrs, xs_receive_data_from_client(), and xs_send_action_to_client().
Referenced by method_close_scan(), method_invoke_from_stand_alone(), and method_receive_results_for_stand_alone().
int method_close_scan (THREAD_ENTRY * thread_p, METHOD_SCAN_BUFFER * scan_buffer_p)
Definition at line 202 of file method_scan.c.
References vacomm_buffer::action, method_clear_scan_buffer(), method_close_value_array_scan(), method_receive_results(), METHOD_SUCCESS, and VACOMM_BUFFER_ABORT.
Referenced by scan_close_scan().
static int method_close_value_array_scan (METHOD_SCAN_BUFFER * scan_buf) static
Definition at line 124 of file method_scan.c.
References method_scan_buffer::dbval_list, free_and_init, NO_ERROR, and NULL.
Referenced by method_close_scan(), and method_open_scan().
static int method_invoke (THREAD_ENTRY * thread_p, METHOD_SCAN_BUFFER * scan_buf) static
Definition at line 353 of file method_scan.c.
References db_make_null(), db_value_clear(), method_scan_buffer::dbval_list, free_and_init, i, method_scan_buffer::method_ctl, METHOD_ERROR, method_invoke_from_stand_alone(), method_sig_list::method_sig, method_info::method_sig_list, method_sig_node::next, NULL, method_sig_list::num_methods, method_scan_buffer::s, S_ERROR, S_SUCCESS, and qproc_db_value_list::val.
Referenced by method_open_scan().
static int method_invoke_from_stand_alone (METHOD_SCAN_BUFFER * scan_buffer_p) static
Definition at line 263 of file method_scan.c.
References cursor_id::buffer, method_scan_buffer::crs_id, cursor_open(), cursor_set_oid_columns(), db_make_null(), ER_FAILED, i, method_info::list_id, method_sig_node::method_arg_pos, method_clear_scan_buffer(), method_scan_buffer::method_ctl, method_sig_list::method_sig, method_sig_list::method_sig_list(), method_info::method_sig_list, method_sig_node::next, NO_ERROR, NULL, method_sig_node::num_method_args, method_sig_list::num_methods, method_scan_buffer::oid_cols, cursor_id::query_id, method_scan_buffer::s, qfile_list_id::tfile_vfid, qfile_tuple_value_type_list::type_cnt, qfile_list_id::type_list, method_scan_buffer::val_cnt, method_scan_buffer::vallist, and method_scan_buffer::valptrs.
Referenced by method_invoke().
int method_open_scan (THREAD_ENTRY * thread_p, METHOD_SCAN_BUFFER * scan_buffer_p, qfile_list_id * list_id_p, method_sig_list * method_sig_list_p)
Definition at line 169 of file method_scan.c.
References error(), method_info::list_id, method_close_value_array_scan(), method_scan_buffer::method_ctl, method_invoke(), method_open_value_array_scan(), method_info::method_sig_list, NO_ERROR, and method_scan_buffer::s.
Referenced by scan_open_method_scan().
static int method_open_value_array_scan (METHOD_SCAN_BUFFER * scan_buf) static
Definition at line 90 of file method_scan.c.
References method_scan_buffer::dbval_list, ER_FAILED, MAX_XS_SCANBUF_DBVALS, method_scan_buffer::method_ctl, method_initialize_vacomm_buffer(), method_info::method_sig_list, NO_ERROR, NULL, method_sig_list::num_methods, and method_scan_buffer::s.
Referenced by method_open_scan().
static SCAN_CODE method_receive_results (THREAD_ENTRY * thread_p, METHOD_SCAN_BUFFER * scan_buf) static
Definition at line 590 of file method_scan.c.
References method_receive_results_for_stand_alone().
Referenced by method_close_scan(), and method_scan_next().
static SCAN_CODE method_receive_results_for_stand_alone (METHOD_SCAN_BUFFER * scan_buffer_p) static
Definition at line 421 of file method_scan.c.
References ARG_FILE_LINE, AU_DISABLE, AU_ENABLE, method_sig_node::class_name, method_scan_buffer::crs_id, cursor_get_tuple_value_list(), cursor_next_tuple(), DB_CURSOR_END, DB_CURSOR_SUCCESS, DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_disable_modification(), db_enable_modification(), db_get_object(), db_is_any_class(), db_is_instance(), DB_IS_NULL, db_make_null(), db_make_oid(), DB_TYPE_ERROR, DB_TYPE_NULL, DB_TYPE_OBJECT, db_value_clone(), db_value_domain_init(), DB_VALUE_DOMAIN_TYPE, DB_VALUE_TYPE, method_scan_buffer::dbval_list, ENTER_SERVER_IN_METHOD_CALL, er_errid(), ER_ERROR_SEVERITY, ER_GENERIC_ERROR, ER_HEAP_UNKNOWN_OBJECT, er_set(), error(), EXIT_SERVER_IN_METHOD_CALL, i, jsp_call_from_server(), method_info::list_id, method_sig_node::method_arg_pos, method_clear_scan_buffer(), method_scan_buffer::method_ctl, method_sig_node::method_name, method_Num_method_jsp_calls, method_sig_list::method_sig, method_sig_list::method_sig_list(), method_info::method_sig_list, method_sig_node::next, NO_ERROR, NULL, method_sig_node::num_method_args, method_sig_list::num_methods, obj_send_array(), pr_clear_value(), method_scan_buffer::s, S_END, S_ERROR, S_SUCCESS, qfile_tuple_value_type_list::type_cnt, qfile_list_id::type_list, qproc_db_value_list::val, method_scan_buffer::vallist, method_scan_buffer::valptrs, and ws_oid().
Referenced by method_receive_results().
SCAN_CODE method_scan_next (THREAD_ENTRY * thread_p, METHOD_SCAN_BUFFER * scan_buffer_p, val_list_node * value_list_p)
Definition at line 237 of file method_scan.c.
References method_info::list_id, method_scan_buffer::method_ctl, method_receive_results(), method_scan_next_value_array(), method_info::method_sig_list, method_sig_list::num_methods, method_scan_buffer::s, S_SUCCESS, val_list_node::val_cnt, and xs_send_method_call_info_to_client().
Referenced by scan_next_method_scan().
static SCAN_CODE method_scan_next_value_array (METHOD_SCAN_BUFFER * scan_buf, VAL_LIST * val_list) static
Definition at line 142 of file method_scan.c.
References method_scan_buffer::dbval_list, qproc_db_value_list::next, NULL, S_SUCCESS, val_list_node::val_cnt, and val_list_node::valp.
Referenced by method_scan_next().
Variable Documentation
unsigned int db_on_server
Definition at line 91 of file network_interface_cl.c.
int method_Num_method_jsp_calls = 0
Definition at line 54 of file method_scan.c.
Referenced by method_receive_results_for_stand_alone().