CUBRID Engine: src/query/method_scan.h File Reference
method_scan.h File Reference
#include "dbtype_def.h"
#include "method_def.hpp"
#include "work_space.h"
#include "cursor.h"
#include "storage_common.h"
#include "thread_compat.hpp"
Classes
struct method_info
struct method_scan_buffer
Macros
#define MAX_XS_SCANBUF_DBVALS 256
Typedefs
typedef struct method_sig_list METHOD_SIG_LIST
typedef struct method_info METHOD_INFO
typedef struct method_scan_buffer METHOD_SCAN_BUFFER
Functions
int method_open_scan (THREAD_ENTRY *thread_p, METHOD_SCAN_BUFFER *scan_buf, qfile_list_id *list_id, method_sig_list *method_sig_list)
int method_close_scan (THREAD_ENTRY *thread_p, METHOD_SCAN_BUFFER *scan_buf)
SCAN_CODE method_scan_next (THREAD_ENTRY *thread_p, METHOD_SCAN_BUFFER *scan_buf, val_list_node *val_list)
Macro Definition Documentation
#define MAX_XS_SCANBUF_DBVALS 256
Definition at line 67 of file method_scan.h.
Referenced by method_open_value_array_scan().
Typedef Documentation
typedef struct method_info METHOD_INFO
Definition at line 69 of file method_scan.h.
typedef struct method_scan_buffer METHOD_SCAN_BUFFER
Definition at line 76 of file method_scan.h.
typedef struct method_sig_list METHOD_SIG_LIST
Definition at line 46 of file method_scan.h.
Function Documentation
int method_close_scan (THREAD_ENTRY * thread_p, METHOD_SCAN_BUFFER * scan_buf)
Definition at line 202 of file method_scan.c.
References vacomm_buffer::action, method_clear_scan_buffer(), method_close_value_array_scan(), method_receive_results(), METHOD_SUCCESS, and VACOMM_BUFFER_ABORT.
Referenced by scan_close_scan().
int method_open_scan (THREAD_ENTRY * thread_p, METHOD_SCAN_BUFFER * scan_buf, qfile_list_id * list_id, method_sig_list * method_sig_list)
Definition at line 169 of file method_scan.c.
References error(), method_info::list_id, method_close_value_array_scan(), method_scan_buffer::method_ctl, method_invoke(), method_open_value_array_scan(), method_info::method_sig_list, NO_ERROR, and method_scan_buffer::s.
Referenced by scan_open_method_scan().
SCAN_CODE method_scan_next (THREAD_ENTRY * thread_p, METHOD_SCAN_BUFFER * scan_buf, val_list_node * val_list)
Definition at line 237 of file method_scan.c.
References method_info::list_id, method_scan_buffer::method_ctl, method_receive_results(), method_scan_next_value_array(), method_info::method_sig_list, method_sig_list::num_methods, method_scan_buffer::s, S_SUCCESS, val_list_node::val_cnt, and xs_send_method_call_info_to_client().
Referenced by scan_next_method_scan().