CUBRID Engine: src/base/misc_string.c File Reference
misc_string.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "misc_string.h"
Functions
char * ustr_casestr (const char *s1, const char *s2)
char * ustr_upper (char *s)
char * ustr_lower (char *s)
Function Documentation
char* ustr_casestr (const char * s1, const char * s2)
Definition at line 41 of file misc_string.c.
References NULL, and strlen.
Referenced by pt_check_hint().
char* ustr_lower (char * s)
Definition at line 116 of file misc_string.c.
References NULL.
char* ustr_upper (char * s)
Definition at line 98 of file misc_string.c.
References NULL.
Referenced by object_printer::describe_domain(), prm_check_environment(), and pt_to_regu_variable().