CUBRID Engine: src/transaction/mvcc_table.cpp File Reference
mvcc_table.cpp File Reference
#include "mvcc_table.hpp"
#include "extensible_array.hpp"
#include "log_impl.h"
#include "mvcc.h"
#include "perf_monitor.h"
#include "thread_manager.hpp"
#include <cassert>
Classes
struct oldest_active_event
struct oldest_active_history_tracker
Functions
static void oldest_active_add_event (MVCCID mvccid, int tran_index, oldest_active_event::op_type set_or_get, oldest_active_event::source src)
static void oldest_active_set (mvcctable::lowest_active_mvccid_type &lowest, int tran_index, MVCCID mvccid, oldest_active_event::source src)
static MVCCID oldest_active_get (const mvcctable::lowest_active_mvccid_type &lowest, int tran_index, oldest_active_event::source src)
Variables
const size_t OLDEST_ACTIVE_HISTORY_SIZE = 1024 * 8
oldest_active_history_tracker Oldest_active_tracker
Function Documentation
static void oldest_active_add_event (MVCCID mvccid, int tran_index, oldest_active_event::op_type set_or_get, oldest_active_event::source src) inline static
Definition at line 78 of file mvcc_table.cpp.
References oldest_active_history_tracker::m_event_count, oldest_active_history_tracker::m_history, and OLDEST_ACTIVE_HISTORY_SIZE.
Referenced by mvcctable::advance_oldest_active(), mvcctable::complete_mvcc(), oldest_active_get(), and oldest_active_set().
static MVCCID oldest_active_get (const mvcctable::lowest_active_mvccid_type & lowest, int tran_index, oldest_active_event::source src) inline static
Definition at line 100 of file mvcc_table.cpp.
References oldest_active_event::GET, MVCCID_NULL, and oldest_active_add_event().
Referenced by mvcctable::build_mvcc_info(), mvcctable::complete_mvcc(), and mvcctable::compute_oldest_visible_mvccid().
static void oldest_active_set (mvcctable::lowest_active_mvccid_type & lowest, int tran_index, MVCCID mvccid, oldest_active_event::source src) inline static
Definition at line 90 of file mvcc_table.cpp.
References oldest_active_add_event(), and oldest_active_event::SET.
Referenced by mvcctable::build_mvcc_info(), mvcctable::complete_mvcc(), and mvcctable::reset_transaction_lowest_active().
Variable Documentation
const size_t OLDEST_ACTIVE_HISTORY_SIZE = 1024 * 8
Definition at line 69 of file mvcc_table.cpp.
Referenced by oldest_active_add_event().
oldest_active_history_tracker Oldest_active_tracker
Definition at line 75 of file mvcc_table.cpp.