CUBRID Engine: HL Namespace Reference
HL Namespace Reference
Classes
class AddHeap
class CPUInfo
Architecture-independent wrapper to get number of CPUs.
class FreelistHeap
class gcd
class gcd< a, 0 >
class lcm
class LockedHeap
class MallocHeap
class MallocInfo
class ObstackHeap
class SizeHeap
Allocates extra room for the size of an object.
class SpinLockType
class ZoneHeap
Functions
align
Rounds up a value to the next multiple of v.
Note
Argument must be a power of two.
template<size_t Alignment>
size_t align (size_t v)
Function Documentation
template<size_t Alignment> size_t HL::align (size_t v) inline
Definition at line 19 of file align.h.
Referenced by pr_type::get_cmpval_function(), PRIM_SET_NULL(), qdata_copy_db_value_to_tuple_value(), qdata_get_tuple_value_size_from_dbval(), qfile_add_item_to_list(), and qfile_save_single_bound_item_tuple().