CUBRID Engine: cubperf Namespace Reference
cubperf Namespace Reference
Classes
class generic_stat_counter
class generic_stat_counter_and_timer
class generic_stat_timer
class generic_statset
class stat_definition
class statset_definition
Typedefs
using clock = std::chrono::high_resolution_clock
using time_point = clock::time_point
using duration = clock::duration
template<bool IsAtomic>
using generic_value = typename std::conditional< IsAtomic, std::atomic< std::uint64_t >, std::uint64_t >::type
using stat_value = generic_value< false >
using atomic_stat_value = generic_value< true >
using stat_id = std::size_t
using statset = generic_statset< false >
using atomic_statset = generic_statset< true >
using stat_counter = generic_stat_counter< false >
using atomic_stat_counter = generic_stat_counter< true >
using stat_timer = generic_stat_timer< false >
using atomic_stat_timer = generic_stat_timer< true >
using stat_counter_and_timer = generic_stat_counter_and_timer< false >
using atomic_stat_counter_and_timer = generic_stat_counter_and_timer< true >
Functions
void reset_timept (time_point &timept)
Typedef Documentation
using cubperf::atomic_stat_counter = typedef generic_stat_counter<true>
Definition at line 138 of file perf_def.hpp.
using cubperf::atomic_stat_counter_and_timer = typedef generic_stat_counter_and_timer<true>
Definition at line 142 of file perf_def.hpp.
using cubperf::atomic_stat_timer = typedef generic_stat_timer<true>
Definition at line 140 of file perf_def.hpp.
using cubperf::atomic_stat_value = typedef generic_value<true>
Definition at line 47 of file perf_def.hpp.
using cubperf::atomic_statset = typedef generic_statset<true>
Definition at line 74 of file perf_def.hpp.
using cubperf::clock = typedef std::chrono::high_resolution_clock
Definition at line 39 of file perf_def.hpp.
using cubperf::duration = typedef clock::duration
Definition at line 41 of file perf_def.hpp.
template<bool IsAtomic> using cubperf::generic_value = typedef typename std::conditional<IsAtomic, std::atomic<std::uint64_t>, std::uint64_t>::type
Definition at line 45 of file perf_def.hpp.
using cubperf::stat_counter = typedef generic_stat_counter<false>
Definition at line 137 of file perf_def.hpp.
using cubperf::stat_counter_and_timer = typedef generic_stat_counter_and_timer<false>
Definition at line 141 of file perf_def.hpp.
using cubperf::stat_id = typedef std::size_t
Definition at line 50 of file perf_def.hpp.
using cubperf::stat_timer = typedef generic_stat_timer<false>
Definition at line 139 of file perf_def.hpp.
using cubperf::stat_value = typedef generic_value<false>
Definition at line 46 of file perf_def.hpp.
using cubperf::statset = typedef generic_statset<false>
Definition at line 73 of file perf_def.hpp.
using cubperf::time_point = typedef clock::time_point
Definition at line 40 of file perf_def.hpp.
Function Documentation
void cubperf::reset_timept (time_point & timept) inline
Definition at line 623 of file perf.hpp.
Referenced by cubthread::waiter::awake(), cubthread::looper::put_to_sleep(), and cubthread::daemon::register_stat_start().