CUBRID Engine: cublocale Namespace Reference
cublocale Namespace Reference
Functions
std::string get_lang_name (const LANG_COLLATION *lang_coll)
std::string get_codeset_name (const LANG_COLLATION *lang_coll)
std::locale get_locale (const std::string &charset, const std::string &lang)
bool convert_to_wstring (std::wstring &out, const std::string &in, const INTL_CODESET codeset)
bool convert_to_string (std::string &out, const std::wstring &in, const INTL_CODESET codeset)
Function Documentation
bool cublocale::convert_to_string (std::string & out, const std::wstring & in, const INTL_CODESET codeset)
Definition at line 164 of file locale_helper.cpp.
References assert, INTL_CODESET_ISO88591, INTL_CODESET_KSC5601_EUC, INTL_CODESET_RAW_BYTES, INTL_CODESET_UTF8, intl_utf8_to_euckr(), intl_utf8_to_iso88591(), and NULL.
Referenced by cubregex::instr(), cubregex::replace(), and cubregex::substr().
bool cublocale::convert_to_wstring (std::wstring & out, const std::string & in, const INTL_CODESET codeset)
Definition at line 75 of file locale_helper.cpp.
References assert, intl_binary_to_utf8(), INTL_CODESET_ISO88591, INTL_CODESET_KSC5601_EUC, INTL_CODESET_MULT, INTL_CODESET_RAW_BYTES, INTL_CODESET_UTF8, intl_euckr_to_utf8(), intl_fast_iso88591_to_utf8(), and NULL.
Referenced by cubregex::compile(), cubregex::count(), cubregex::instr(), cubregex::replace(), cubregex::search(), and cubregex::substr().
std::string cublocale::get_codeset_name (const LANG_COLLATION * lang_coll)
Definition at line 38 of file locale_helper.cpp.
References lang_collation::codeset, and lang_get_codeset_name().
std::string cublocale::get_lang_name (const LANG_COLLATION * lang_coll)
Definition at line 31 of file locale_helper.cpp.
References lang_collation::default_lang, and lang_locale_data::lang_name.
Referenced by cubregex::compile().
std::locale cublocale::get_locale (const std::string & charset, const std::string & lang)
Definition at line 45 of file locale_helper.cpp.
References assert.
Referenced by cubregex::compile().