CUBRID Engine: cubpacking Namespace Reference
cubpacking Namespace Reference
Classes
class packable_object
class packer
class unpacker
Functions
static void check_range (const char *ptr, const char *endptr, const size_t amount)
Function Documentation
static void cubpacking::check_range (const char * ptr, const char * endptr, const size_t amount) static
Definition at line 50 of file packer.cpp.
References assert.
Referenced by cubpacking::packer::delegate_to_or_buf(), cubpacking::unpacker::delegate_to_or_buf(), cubpacking::packer::pack_bigint(), cubpacking::packer::pack_buffer_with_length(), cubpacking::packer::pack_c_string(), cubpacking::packer::pack_db_value(), cubpacking::packer::pack_int(), cubpacking::packer::pack_int_array(), cubpacking::packer::pack_int_vector(), cubpacking::packer::pack_large_c_string(), cubpacking::packer::pack_oid(), cubpacking::packer::pack_short(), cubpacking::packer::pack_small_string(), cubpacking::unpacker::peek_unpack_int(), cubpacking::unpacker::unpack_bigint(), cubpacking::unpacker::unpack_buffer_with_length(), cubpacking::unpacker::unpack_db_value(), cubpacking::unpacker::unpack_int(), cubpacking::unpacker::unpack_int_array(), cubpacking::unpacker::unpack_int_vector(), cubpacking::unpacker::unpack_large_string(), cubpacking::unpacker::unpack_oid(), cubpacking::unpacker::unpack_short(), cubpacking::unpacker::unpack_small_string(), cubpacking::unpacker::unpack_string(), and cubpacking::unpacker::unpack_string_size().