CUBRID Engine: cubthread Namespace Reference
cubthread Namespace Reference
Namespaces
internal_tasks_worker_pool
Classes
class callable_task
class callable_task< void >
class context_manager
class daemon
class daemon_entry_manager
class entry
class entry_manager
class lockfree_hashmap
class looper
class manager
class task
class task< void >
struct wait_duration
class waiter
class worker_pool
class worker_pool_task_capper
Typedefs
using entry_task = task< entry >
using entry_callable_task = callable_task< entry >
typedef std::chrono::system_clock::duration delta_time
typedef std::function< void(bool &, delta_time &)> period_function
using entry_workpool = worker_pool< entry >
using task_without_context = task< void >
using wait_seconds = wait_duration< std::chrono::seconds >
Functions
lockfree::tran::system & get_thread_entry_lftransys ()
void initialize (entry *&my_entry)
void finalize (void)
int initialize_thread_entries (bool with_lock_free)
entry * get_main_entry (void)
manager * get_manager (void)
void set_manager (manager *manager)
std::size_t get_max_thread_count (void)
entry & get_entry (void)
void set_thread_local_entry (entry &tl_entry)
void clear_thread_local_entry (void)
bool is_single_thread (void)
void check_not_single_thread (void)
void return_lock_free_transaction_entries (void)
bool is_logging_configured (const int logging_flag)
template<typename D >
void condvar_wait (std::condition_variable &condvar, std::unique_lock< std::mutex > &lock, const wait_duration< D > &duration)
template<typename D , typename P >
bool condvar_wait (std::condition_variable &condvar, std::unique_lock< std::mutex > &lock, const wait_duration< D > &duration, P pred)
bool wp_is_thread_always_alive_forced ()
void wp_set_force_thread_always_alive ()
cubperf::statset & wp_worker_statset_create (void)
void wp_worker_statset_destroy (cubperf::statset &stats)
void wp_worker_statset_time_and_increment (cubperf::statset &stats, cubperf::stat_id id)
void wp_worker_statset_accumulate (const cubperf::statset &what, cubperf::stat_value *where)
std::size_t wp_worker_statset_get_count (void)
const char * wp_worker_statset_get_name (std::size_t stat_index)
std::size_t system_core_count (void)
void wp_handle_system_error (const char *message, const std::system_error &e)
void wp_er_log_stats (const char *header, cubperf::stat_value *statsp)
template<typename Func >
void wp_call_func_throwing_system_error (const char *message, Func &func)
Variables
constexpr size_t WORKER_COUNT = 2
constexpr size_t TASK_COUNT = 10
constexpr size_t CORE_COUNT = 1
constexpr bool ENABLE_LOGGING = true
entry_workpool * instance = NULL
static const cubperf::stat_id STAT_LOOP_EXECUTE_COUNT_AND_TIME = 0
static const cubperf::stat_id STAT_LOOP_PAUSE_TIME = 1
static const cubperf::statset_definition Daemon_statistics
static const bool ENABLE_TRACKERS
const char * ALLOC_TRACK_NAME = "Virtual Memory"
const char * ALLOC_TRACK_RES_NAME = "res_ptr"
const std::size_t ALLOC_TRACK_MAX_ITEMS = 32767
const char * PGBUF_TRACK_NAME = "Page Buffer"
const char * PGBUF_TRACK_RES_NAME = "pgptr"
const std::size_t PGBUF_TRACK_MAX_ITEMS = 1024
const unsigned PGBUF_TRACK_MAX_AMOUNT = 16
static const cubperf::stat_id STAT_LOOPER_SLEEP_COUNT_AND_TIME = 0
static cubperf::stat_id STAT_LOOPER_RESET_COUNT = 1
static const cubperf::statset_definition Looper_statistics
const std::size_t MAX_LOOPER_PERIODS = 3
thread_local entry * tl_Entry_p = NULL
const bool Is_single_thread = true
static manager * Manager = NULL
static entry * Main_entry_p = NULL
const int LOG_MANAGER = 0x1
const int LOG_MANAGER_ALL = 0xFF
const int LOG_WORKER_POOL_VACUUM = 0x100
const int LOG_WORKER_POOL_CONNECTIONS = 0x200
const int LOG_WORKER_POOL_TRAN_WORKERS = 0x400
const int LOG_WORKER_POOL_INDEX_BUILDER = 0x800
const int LOG_WORKER_POOL_ALL = 0xFF00
const int LOG_DAEMON_VACUUM = 0x10000
const int LOG_DAEMON_ALL = 0xFFFF0000
static const cubperf::stat_id STAT_LOCK_WAKEUP_COUNT = 0
static const cubperf::stat_id STAT_SLEEP_COUNT = 1
static const cubperf::stat_id STAT_TIMEOUT_COUNT = 2
static const cubperf::stat_id STAT_NO_SLEEP_COUNT = 3
static const cubperf::stat_id STAT_AWAKEN_COUNT_AND_TIME = 4
static const cubperf::statset_definition Waiter_statistics
static const char * STAT_WAKEUP_CALL_COUNT_NAME = "waiter_wakeup_count"
static bool FORCE_THREAD_ALWAYS_ALIVE = false
static const cubperf::statset_definition Worker_pool_statdef
static const cubperf::stat_id Wpstat_start_thread = 0
static const cubperf::stat_id Wpstat_create_context = 1
static const cubperf::stat_id Wpstat_execute_task = 2
static const cubperf::stat_id Wpstat_retire_task = 3
static const cubperf::stat_id Wpstat_found_in_queue = 4
static const cubperf::stat_id Wpstat_wakeup_with_task = 5
static const cubperf::stat_id Wpstat_recycle_context = 6
static const cubperf::stat_id Wpstat_retire_context = 7
Typedef Documentation
typedef std::chrono::system_clock::duration cubthread::delta_time
Definition at line 40 of file thread_looper.hpp.
using cubthread::entry_callable_task = typedef callable_task<entry>
Definition at line 58 of file thread_entry_task.hpp.
using cubthread::entry_task = typedef task<entry>
Definition at line 57 of file thread_entry_task.hpp.
using cubthread::entry_workpool = typedef worker_pool<entry>
Definition at line 65 of file thread_manager.hpp.
typedef std::function<void (bool &, delta_time &)> cubthread::period_function
Definition at line 41 of file thread_looper.hpp.
using cubthread::task_without_context = typedef task<void>
Definition at line 131 of file thread_task.hpp.
using cubthread::wait_seconds = typedef wait_duration<std::chrono::seconds>
Definition at line 133 of file thread_waiter.hpp.
Function Documentation
void cubthread::check_not_single_thread (void)
Definition at line 630 of file thread_manager.cpp.
References assert.
Referenced by cubthread::manager::create_and_track_resource(), cubthread::manager::destroy_and_untrack_resource(), cubthread::manager::push_task(), cubthread::manager::push_task_on_core(), and cubthread::manager::try_task().
void cubthread::clear_thread_local_entry (void)
Definition at line 617 of file thread_manager.cpp.
References assert, and NULL.
Referenced by test_mvcc_get_oldest(), test_mvcc_get_snapshot(), and test_new_mvcc_complete().
template<typename D > void cubthread::condvar_wait (std::condition_variable & condvar, std::unique_lock< std::mutex > & lock, const wait_duration< D > & duration)
Definition at line 148 of file thread_waiter.hpp.
References cubthread::wait_duration< D >::m_duration, and cubthread::wait_duration< D >::m_infinite.
Referenced by cubthread::worker_pool< Context >::core::worker::get_new_task().
template<typename D , typename P > bool cubthread::condvar_wait (std::condition_variable & condvar, std::unique_lock< std::mutex > & lock, const wait_duration< D > & duration, P pred)
Definition at line 163 of file thread_waiter.hpp.
References cubthread::wait_duration< D >::m_duration, and cubthread::wait_duration< D >::m_infinite.
void cubthread::finalize (void)
Definition at line 514 of file thread_manager.cpp.
References cuberr::context::deregister_thread_local(), cubthread::entry::get_error_context(), Main_entry_p, Manager, and NULL.
Referenced by boot_restart_server(), net_server_start(), xboot_delete(), xboot_initialize_server(), and xboot_shutdown_server().
entry & cubthread::get_entry (void)
Definition at line 599 of file thread_manager.cpp.
References assert, NULL, and tl_Entry_p.
Referenced by mvcctable::compute_oldest_visible_mvccid(), cubload::error_handler::get_driver_lineno(), cubmem::get_private_heapid(), cubload::error_handler::get_scanner_lineno(), cuberr::context::get_thread_local_context(), heap_classrepr_logging_template(), cubload::server_object_loader::init(), cubload::session::interrupt(), ldr_init_driver(), ldr_sa_load(), cubload::server_class_installer::locate_class(), cubload::session::notify_batch_done_and_register_tran_end(), cubthread::manager::push_task(), cubthread::manager::push_task_on_core(), cubload::server_class_installer::register_class_with_attributes(), log_system_tdes::rv_end_simulation(), log_system_tdes::rv_simulate_system_tdes(), vacuum_job_cursor::search(), cubload::session::session(), vacuum_job_cursor::start_job_on_current_entry(), thread_get_thread_entry_info(), vacuum_job_cursor::unload(), and vacuum_data::update().
entry * cubthread::get_main_entry (void)
Definition at line 569 of file thread_manager.cpp.
References assert, Main_entry_p, and NULL.
manager * cubthread::get_manager (void)
Definition at line 577 of file thread_manager.cpp.
References assert, Manager, and NULL.
Referenced by cubthread::entry_manager::create_context(), css_init(), css_internal_connection_handler(), dwb_read_page(), get_thread_entry_lftransys(), cuberr::context::get_thread_local_context(), cubthread::internal_tasks_worker_pool::initialize(), lock_initialize(), log_is_log_flush_daemon_available(), log_stop_ha_delay_registration(), pgbuf_get_page_flush_interval(), cubthread::entry_manager::retire_context(), session_free_prepared_statement(), thread_get_manager(), vacuum_boot(), vacuum_data_unload_first_and_last_page(), vacuum_stop_master(), vacuum_stop_workers(), cubload::worker_manager_register_session(), and cubload::worker_manager_unregister_session().
std::size_t cubthread::get_max_thread_count (void)
Definition at line 592 of file thread_manager.cpp.
References cubthread::manager::get_max_thread_count(), and NULL.
Referenced by thread_num_total_threads().
lockfree::tran::system & cubthread::get_thread_entry_lftransys ()
Definition at line 26 of file thread_lockfree_hash_map.cpp.
References cubthread::manager::get_lockfree_transys(), and get_manager().
Referenced by cubthread::lockfree_hashmap< Key, T >::init().
void cubthread::initialize (entry *& my_entry)
Definition at line 472 of file thread_manager.cpp.
References assert, cubthread::entry::get_error_context(), cubthread::entry::index, cubthread::entry::m_status, Main_entry_p, cubthread::manager::manager(), NULL, prm_get_bool_value(), PRM_ID_PERF_TEST_MODE, cubthread::entry::register_id(), cuberr::context::register_thread_local(), cubthread::entry::resume_status, thread_get_thread_entry_info(), THREAD_RESUME_NONE, cubthread::entry::tran_index, cubthread::entry::TS_RUN, and wp_set_force_thread_always_alive().
Referenced by boot_restart_server(), net_server_start(), xboot_delete(), xboot_emergency_patch(), and xboot_initialize_server().
int cubthread::initialize_thread_entries (bool with_lock_free)
Definition at line 532 of file thread_manager.cpp.
References cubthread::manager::alloc_entries(), assert, ASSERT_ERROR, lockfree::tran::system::assign_index(), cubthread::entry::assign_lf_tran_index(), cubthread::manager::get_lockfree_transys(), cubthread::manager::get_max_thread_count(), cubthread::manager::init_entries(), cubthread::manager::init_lockfree_system(), lf_initialize_transaction_systems(), NO_ERROR, NULL, cubthread::entry::request_lock_free_transactions(), and cubthread::manager::set_max_thread_count_from_config().
Referenced by boot_restart_server(), xboot_delete(), xboot_emergency_patch(), and xboot_initialize_server().
bool cubthread::is_logging_configured (const int logging_flag)
Definition at line 650 of file thread_manager.cpp.
References flag< T >::is_flag_set(), prm_get_integer_value(), and PRM_ID_THREAD_LOGGING_FLAG.
Referenced by btree_is_worker_pool_logging_true(), css_init(), and vacuum_boot().
bool cubthread::is_single_thread (void)
Definition at line 624 of file thread_manager.cpp.
References Is_single_thread.
Referenced by cubthread::manager::create_daemon(), cubthread::manager::create_daemon_without_entry(), cubthread::manager::create_worker_pool(), rmutex_lock(), and rmutex_unlock().
void cubthread::return_lock_free_transaction_entries (void)
Definition at line 636 of file thread_manager.cpp.
References NULL, cubthread::manager::return_lock_free_transaction_entries(), and cubthread::entry::return_lock_free_transaction_entries().
Referenced by cubthread::manager::get_lockfree_transys(), and thread_return_lock_free_transaction_entries().
void cubthread::set_manager (manager * manager)
Definition at line 584 of file thread_manager.cpp.
References assert, cubthread::manager::manager(), and NULL.
void cubthread::set_thread_local_entry (entry & tl_entry)
Definition at line 610 of file thread_manager.cpp.
References assert, and NULL.
Referenced by test_mvcc_get_oldest(), test_mvcc_get_snapshot(), and test_new_mvcc_complete().
std::size_t cubthread::system_core_count (void)
Definition at line 113 of file thread_worker_pool.cpp.
References cubregex::count().
Referenced by css_init().
template<typename Func > void cubthread::wp_call_func_throwing_system_error (const char * message, Func & func)
Definition at line 1457 of file thread_worker_pool.hpp.
References wp_handle_system_error().
Referenced by cubthread::worker_pool< Context >::core::worker::start_thread().
void cubthread::wp_er_log_stats (const char * header, cubperf::stat_value * statsp)
Definition at line 134 of file thread_worker_pool.cpp.
References _er_log_debug(), ARG_FILE_LINE, cubperf::statset_definition::get_value_count(), and cubperf::statset_definition::get_value_name().
Referenced by cubthread::worker_pool< Context >::er_log_stats().
void cubthread::wp_handle_system_error (const char * message, const std::system_error & e)
Definition at line 126 of file thread_worker_pool.cpp.
References ARG_FILE_LINE, assert, and er_print_callstack().
Referenced by wp_call_func_throwing_system_error().
bool cubthread::wp_is_thread_always_alive_forced ()
Definition at line 37 of file thread_worker_pool.cpp.
References FORCE_THREAD_ALWAYS_ALIVE.
Referenced by cubthread::worker_pool< Context >::worker_pool().
void cubthread::wp_set_force_thread_always_alive ()
Definition at line 43 of file thread_worker_pool.cpp.
Referenced by initialize().
void cubthread::wp_worker_statset_accumulate (const cubperf::statset & what, cubperf::stat_value * where)
Definition at line 91 of file thread_worker_pool.cpp.
References cubperf::statset_definition::add_stat_values_with_converted_timers().
Referenced by cubthread::worker_pool< Context >::core::worker::get_stats().
cubperf::statset & cubthread::wp_worker_statset_create (void)
Definition at line 73 of file thread_worker_pool.cpp.
References cubperf::statset_definition::create_statset().
void cubthread::wp_worker_statset_destroy (cubperf::statset & stats)
Definition at line 79 of file thread_worker_pool.cpp.
Referenced by cubthread::worker_pool< Context >::core::worker::~worker().
std::size_t cubthread::wp_worker_statset_get_count (void)
Definition at line 97 of file thread_worker_pool.cpp.
References cubperf::statset_definition::get_value_count().
const char * cubthread::wp_worker_statset_get_name (std::size_t stat_index)
Definition at line 103 of file thread_worker_pool.cpp.
References cubperf::statset_definition::get_value_name().
void cubthread::wp_worker_statset_time_and_increment (cubperf::statset & stats, cubperf::stat_id id)
Definition at line 85 of file thread_worker_pool.cpp.
References cubperf::statset_definition::time_and_increment().
Referenced by cubthread::worker_pool< Context >::core::worker::execute_current_task(), cubthread::worker_pool< Context >::core::worker::finish_run(), cubthread::worker_pool< Context >::core::worker::get_new_task(), cubthread::worker_pool< Context >::core::worker::init_run(), and cubthread::worker_pool< Context >::core::worker::retire_current_task().
Variable Documentation
const std::size_t cubthread::ALLOC_TRACK_MAX_ITEMS = 32767
Definition at line 65 of file thread_entry.cpp.
const char* cubthread::ALLOC_TRACK_NAME = "Virtual Memory"
Definition at line 63 of file thread_entry.cpp.
const char* cubthread::ALLOC_TRACK_RES_NAME = "res_ptr"
Definition at line 64 of file thread_entry.cpp.
constexpr size_t cubthread::CORE_COUNT = 1
Definition at line 30 of file internal_tasks_worker_pool.cpp.
const cubperf::statset_definition cubthread::Daemon_statistics static
Initial value:
=
  {
    cubperf::stat_definition (STAT_LOOP_EXECUTE_COUNT_AND_TIME, cubperf::stat_definition::COUNTER_AND_TIMER,
                  "daemon_loop_count", "daemon_execute_time"),
    cubperf::stat_definition (STAT_LOOP_PAUSE_TIME, cubperf::stat_definition::TIMER,
                  "daemon_pause_time")
  }
Definition at line 39 of file thread_daemon.cpp.
constexpr bool cubthread::ENABLE_LOGGING = true
Definition at line 31 of file internal_tasks_worker_pool.cpp.
const bool cubthread::ENABLE_TRACKERS static
Initial value:
=
      false
Definition at line 54 of file thread_entry.cpp.
bool cubthread::FORCE_THREAD_ALWAYS_ALIVE = false static
Definition at line 34 of file thread_worker_pool.cpp.
Referenced by wp_is_thread_always_alive_forced().
entry_workpool* cubthread::instance = NULL
Definition at line 33 of file internal_tasks_worker_pool.cpp.
Referenced by cubthread::internal_tasks_worker_pool::finalize(), cubthread::internal_tasks_worker_pool::get_instance(), otable_insert(), and otable_reserve().
const bool cubthread::Is_single_thread = true
Definition at line 465 of file thread_manager.cpp.
Referenced by cubthread::manager::find_by_tid(), and is_single_thread().
const int cubthread::LOG_DAEMON_ALL = 0xFFFF0000
Definition at line 305 of file thread_manager.hpp.
const int cubthread::LOG_DAEMON_VACUUM = 0x10000
Definition at line 304 of file thread_manager.hpp.
const int cubthread::LOG_MANAGER = 0x1
Definition at line 293 of file thread_manager.hpp.
const int cubthread::LOG_MANAGER_ALL = 0xFF
Definition at line 294 of file thread_manager.hpp.
const int cubthread::LOG_WORKER_POOL_ALL = 0xFF00
Definition at line 301 of file thread_manager.hpp.
const int cubthread::LOG_WORKER_POOL_CONNECTIONS = 0x200
Definition at line 298 of file thread_manager.hpp.
Referenced by css_init().
const int cubthread::LOG_WORKER_POOL_INDEX_BUILDER = 0x800
Definition at line 300 of file thread_manager.hpp.
Referenced by btree_is_worker_pool_logging_true().
const int cubthread::LOG_WORKER_POOL_TRAN_WORKERS = 0x400
Definition at line 299 of file thread_manager.hpp.
Referenced by css_init().
const int cubthread::LOG_WORKER_POOL_VACUUM = 0x100
Definition at line 297 of file thread_manager.hpp.
Referenced by vacuum_boot().
const cubperf::statset_definition cubthread::Looper_statistics static
Initial value:
=
  {
    cubperf::stat_definition (STAT_LOOPER_SLEEP_COUNT_AND_TIME, cubperf::stat_definition::COUNTER_AND_TIMER,
                  "looper_sleep_count", "looper_sleep_time"),
    cubperf::stat_definition (STAT_LOOPER_RESET_COUNT, cubperf::stat_definition::COUNTER, "looper_reset_count")
  }
Definition at line 36 of file thread_looper.cpp.
entry* cubthread::Main_entry_p = NULL static
Definition at line 469 of file thread_manager.cpp.
Referenced by finalize(), get_main_entry(), and initialize().
manager* cubthread::Manager = NULL static
Definition at line 468 of file thread_manager.cpp.
Referenced by finalize(), and get_manager().
const std::size_t cubthread::MAX_LOOPER_PERIODS = 3
Definition at line 44 of file thread_looper.hpp.
const unsigned cubthread::PGBUF_TRACK_MAX_AMOUNT = 16
Definition at line 71 of file thread_entry.cpp.
const std::size_t cubthread::PGBUF_TRACK_MAX_ITEMS = 1024
Definition at line 70 of file thread_entry.cpp.
const char* cubthread::PGBUF_TRACK_NAME = "Page Buffer"
Definition at line 68 of file thread_entry.cpp.
const char* cubthread::PGBUF_TRACK_RES_NAME = "pgptr"
Definition at line 69 of file thread_entry.cpp.
const cubperf::stat_id cubthread::STAT_AWAKEN_COUNT_AND_TIME = 4 static
Definition at line 40 of file thread_waiter.cpp.
const cubperf::stat_id cubthread::STAT_LOCK_WAKEUP_COUNT = 0 static
Definition at line 36 of file thread_waiter.cpp.
const cubperf::stat_id cubthread::STAT_LOOP_EXECUTE_COUNT_AND_TIME = 0 static
Definition at line 37 of file thread_daemon.cpp.
const cubperf::stat_id cubthread::STAT_LOOP_PAUSE_TIME = 1 static
Definition at line 38 of file thread_daemon.cpp.
cubperf::stat_id cubthread::STAT_LOOPER_RESET_COUNT = 1 static
Definition at line 35 of file thread_looper.cpp.
const cubperf::stat_id cubthread::STAT_LOOPER_SLEEP_COUNT_AND_TIME = 0 static
Definition at line 34 of file thread_looper.cpp.
const cubperf::stat_id cubthread::STAT_NO_SLEEP_COUNT = 3 static
Definition at line 39 of file thread_waiter.cpp.
const cubperf::stat_id cubthread::STAT_SLEEP_COUNT = 1 static
Definition at line 37 of file thread_waiter.cpp.
const cubperf::stat_id cubthread::STAT_TIMEOUT_COUNT = 2 static
Definition at line 38 of file thread_waiter.cpp.
const char* cubthread::STAT_WAKEUP_CALL_COUNT_NAME = "waiter_wakeup_count" static
Definition at line 53 of file thread_waiter.cpp.
Referenced by cubthread::waiter::get_stat_name().
constexpr size_t cubthread::TASK_COUNT = 10
Definition at line 29 of file internal_tasks_worker_pool.cpp.
thread_local entry* cubthread::tl_Entry_p = NULL
Definition at line 47 of file thread_manager.cpp.
Referenced by cubthread::manager::claim_entry(), and get_entry().
const cubperf::statset_definition cubthread::Waiter_statistics static
Initial value:
=
  {
    cubperf::stat_definition (STAT_LOCK_WAKEUP_COUNT, cubperf::stat_definition::COUNTER, "waiter_lock_wakeup_count"),
    cubperf::stat_definition (STAT_SLEEP_COUNT, cubperf::stat_definition::COUNTER, "waiter_sleep_count"),
    cubperf::stat_definition (STAT_TIMEOUT_COUNT, cubperf::stat_definition::COUNTER,
                  "waiter_timeout_count"),
    cubperf::stat_definition (STAT_NO_SLEEP_COUNT, cubperf::stat_definition::COUNTER, "waiter_no_sleep_count"),
    cubperf::stat_definition (STAT_AWAKEN_COUNT_AND_TIME, cubperf::stat_definition::COUNTER_AND_TIMER,
                  "waiter_awake_count", "waiter_wakeup_delay_time")
  }
Definition at line 41 of file thread_waiter.cpp.
constexpr size_t cubthread::WORKER_COUNT = 2
Definition at line 28 of file internal_tasks_worker_pool.cpp.
const cubperf::statset_definition cubthread::Worker_pool_statdef static
Initial value:
=
  {
    cubperf::stat_definition (Wpstat_start_thread, cubperf::stat_definition::COUNTER_AND_TIMER,
                  "Counter_start_thread", "Timer_start_thread"),
    cubperf::stat_definition (Wpstat_create_context, cubperf::stat_definition::COUNTER_AND_TIMER,
                  "Counter_create_context", "Timer_create_context"),
    cubperf::stat_definition (Wpstat_execute_task, cubperf::stat_definition::COUNTER_AND_TIMER,
                  "Counter_execute_task", "Timer_execute_task"),
    cubperf::stat_definition (Wpstat_retire_task, cubperf::stat_definition::COUNTER_AND_TIMER,
                  "Counter_retire_task", "Timer_retire_task"),
    cubperf::stat_definition (Wpstat_found_in_queue, cubperf::stat_definition::COUNTER_AND_TIMER,
                  "Counter_found_task_in_queue", "Timer_found_task_in_queue"),
    cubperf::stat_definition (Wpstat_wakeup_with_task, cubperf::stat_definition::COUNTER_AND_TIMER,
                  "Counter_wakeup_with_task", "Timer_wakeup_with_task"),
    cubperf::stat_definition (Wpstat_recycle_context, cubperf::stat_definition::COUNTER_AND_TIMER,
                  "Counter_recycle_context", "Timer_recycle_context"),
    cubperf::stat_definition (Wpstat_retire_context, cubperf::stat_definition::COUNTER_AND_TIMER,
                  "Counter_retire_context", "Timer_retire_context")
  }
Definition at line 52 of file thread_worker_pool.cpp.
const cubperf::stat_id cubthread::Wpstat_create_context = 1 static
Definition at line 491 of file thread_worker_pool.hpp.
const cubperf::stat_id cubthread::Wpstat_execute_task = 2 static
Definition at line 492 of file thread_worker_pool.hpp.
const cubperf::stat_id cubthread::Wpstat_found_in_queue = 4 static
Definition at line 494 of file thread_worker_pool.hpp.
const cubperf::stat_id cubthread::Wpstat_recycle_context = 6 static
Definition at line 496 of file thread_worker_pool.hpp.
const cubperf::stat_id cubthread::Wpstat_retire_context = 7 static
Definition at line 497 of file thread_worker_pool.hpp.
const cubperf::stat_id cubthread::Wpstat_retire_task = 3 static
Definition at line 493 of file thread_worker_pool.hpp.
const cubperf::stat_id cubthread::Wpstat_start_thread = 0 static
Definition at line 490 of file thread_worker_pool.hpp.
const cubperf::stat_id cubthread::Wpstat_wakeup_with_task = 5 static
Definition at line 495 of file thread_worker_pool.hpp.