CUBRID Engine: cubbase Namespace Reference
cubbase Namespace Reference
Classes
class factory
struct fileline_location
class pinnable
class pinner
class resource_tracker
struct resource_tracker_item
Typedefs
using alloc_tracker = resource_tracker< const void * >
using pgbuf_tracker = resource_tracker< const char * >
Functions
std::ostream & operator<< (std::ostream &os, const fileline_location &fileline)
std::ostream & operator<< (std::ostream &os, const resource_tracker_item &item)
bool restrack_pop_error (void)
void restrack_set_error (bool error)
void restrack_set_suppress_assert (bool suppress)
bool restrack_is_assert_suppressed (void)
void restrack_log (const std::string &str)
void restrack_assert (bool cond)
Variables
bool Restrack_has_error = false
bool Restrack_suppress_assert = false
Typedef Documentation
using cubbase::alloc_tracker = typedef resource_tracker<const void *>
Definition at line 64 of file thread_entry.hpp.
using cubbase::pgbuf_tracker = typedef resource_tracker<const char *>
Definition at line 66 of file thread_entry.hpp.
Function Documentation
std::ostream & cubbase::operator<< (std::ostream & os, const resource_tracker_item & item)
Definition at line 37 of file resource_tracker.cpp.
References cubbase::resource_tracker_item::m_first_location, and cubbase::resource_tracker_item::m_reuse_count.
std::ostream & cubbase::operator<< (std::ostream & os, const fileline_location & fileline)
Definition at line 57 of file fileline_location.cpp.
References cubbase::fileline_location::m_file, and cubbase::fileline_location::m_line.
void cubbase::restrack_assert (bool cond) inline
Definition at line 446 of file resource_tracker.hpp.
References assert, restrack_is_assert_suppressed(), and restrack_set_error().
Referenced by cubbase::resource_tracker< Res >::clear_all(), cubsync::cstrack_assert(), cubbase::resource_tracker< Res >::decrement(), cubbase::resource_tracker< Res >::increment(), cubbase::resource_tracker< Res >::pop_track(), and cubbase::resource_tracker< Res >::~resource_tracker().
bool cubbase::restrack_is_assert_suppressed (void)
Definition at line 69 of file resource_tracker.cpp.
References Restrack_suppress_assert.
Referenced by restrack_assert().
void cubbase::restrack_log (const std::string & str)
Definition at line 75 of file resource_tracker.cpp.
References _er_log_debug(), and ARG_FILE_LINE.
Referenced by cubbase::resource_tracker< Res >::dump().
bool cubbase::restrack_pop_error (void)
Definition at line 49 of file resource_tracker.cpp.
References Restrack_has_error.
void cubbase::restrack_set_error (bool error)
Definition at line 57 of file resource_tracker.cpp.
References error().
Referenced by restrack_assert().
void cubbase::restrack_set_suppress_assert (bool suppress)
Definition at line 63 of file resource_tracker.cpp.
Variable Documentation
bool cubbase::Restrack_has_error = false
Definition at line 45 of file resource_tracker.cpp.
Referenced by restrack_pop_error().
bool cubbase::Restrack_suppress_assert = false
Definition at line 46 of file resource_tracker.cpp.
Referenced by restrack_is_assert_suppressed().