CUBRID Engine: cubload Namespace Reference
cubload Namespace Reference
Classes
class attribute
class batch
struct class_command_spec_type
class class_entry
class class_installer
class class_registry
struct constant_type
struct constructor_spec_type
class driver
class error_handler
struct load_args
class load_status
class load_task
struct monetary_type
class object_loader
struct object_ref_type
class sa_class_installer
class sa_object_loader
class scanner
class semantic_helper
class server_class_installer
class server_object_loader
class session
struct stats
struct string_type
class worker_context_manager
Typedefs
using batch_id = int64_t
using class_id = int
using batch_handler = std::function< int64_t(const batch &)>
using class_handler = std::function< int64_t(const batch &, bool &)>
using conv_setters = std::array< std::array< conv_func, NUM_LDR_TYPES >, NUM_DB_TYPES >
typedef int(* conv_func) (const char *, const size_t, const attribute *, db_value *)
Enumerations
enum data_type {
LDR_NULL, LDR_INT, LDR_STR, LDR_NSTR,
LDR_NUMERIC, LDR_DOUBLE, LDR_FLOAT, LDR_OID,
LDR_CLASS_OID, LDR_DATE, LDR_TIME, LDR_TIMESTAMP,
LDR_TIMESTAMPLTZ, LDR_TIMESTAMPTZ, LDR_COLLECTION, LDR_ELO_INT,
LDR_ELO_EXT, LDR_SYS_USER, LDR_SYS_CLASS, LDR_MONETARY,
LDR_BSTR, LDR_XSTR, LDR_DATETIME, LDR_DATETIMELTZ,
LDR_DATETIMETZ, LDR_JSON, LDR_TYPE_MAX = LDR_JSON
}
enum attribute_type { LDR_ATTRIBUTE_ANY = 0, LDR_ATTRIBUTE_SHARED, LDR_ATTRIBUTE_CLASS, LDR_ATTRIBUTE_DEFAULT }
enum interrupt_type { LDR_NO_INTERRUPT, LDR_STOP_AND_ABORT_INTERRUPT, LDR_STOP_AND_COMMIT_INTERRUPT }
Functions
int handle_batch (batch_handler &handler, class_id clsid, std::string &batch_content, batch_id &batch_id, int64_t line_offset, int64_t &rows)
bool starts_with (const std::string &str, const std::string &prefix)
bool ends_with (const std::string &str, const std::string &suffix)
void rtrim (std::string &str)
int split (int batch_size, const std::string &object_file_name, class_handler &c_handler, batch_handler &b_handler)
int mismatch (const char *str, const size_t str_size, const attribute *attr, db_value *val)
int to_db_null (const char *str, const size_t str_size, const attribute *attr, db_value *val)
int to_db_short (const char *str, const size_t str_size, const attribute *attr, db_value *val)
int to_db_int (const char *str, const size_t str_size, const attribute *attr, db_value *val)
int to_db_int_set (const char *str, const size_t str_size, const attribute *attr, db_value *val)
int to_db_bigint (const char *str, const size_t str_size, const attribute *attr, db_value *val)
int to_db_generic_char (DB_TYPE type, const char *str, const size_t str_size, const attribute *attr, db_value *val)
int to_db_char (const char *str, const size_t str_size, const attribute *attr, db_value *val)
int to_db_varchar (const char *str, const size_t str_size, const attribute *attr, db_value *val)
int to_db_make_nchar (const char *str, const size_t str_size, const attribute *attr, db_value *val)
int to_db_make_varnchar (const char *str, const size_t str_size, const attribute *attr, db_value *val)
int to_db_string (const char *str, const size_t str_size, const attribute *attr, db_value *val)
int to_db_float (const char *str, const size_t str_size, const attribute *attr, db_value *val)
int to_db_double (const char *str, const size_t str_size, const attribute *attr, db_value *val)
int to_db_numeric (const char *str, const size_t str_size, const attribute *attr, db_value *val)
int to_db_date (const char *str, const size_t str_size, const attribute *attr, db_value *val)
int to_db_time (const char *str, const size_t str_size, const attribute *attr, db_value *val)
int to_db_timestamp (const char *str, const size_t str_size, const attribute *attr, db_value *val)
int to_db_timestampltz (const char *str, const size_t str_size, const attribute *attr, db_value *val)
int to_db_timestamptz (const char *str, const size_t str_size, const attribute *attr, db_value *val)
int to_db_datetime (const char *str, const size_t str_size, const attribute *attr, db_value *val)
int to_db_datetimeltz (const char *str, const size_t str_size, const attribute *attr, db_value *val)
int to_db_datetimetz (const char *str, const size_t str_size, const attribute *attr, db_value *val)
int to_db_json (const char *str, const size_t str_size, const attribute *attr, db_value *val)
int to_db_monetary (const char *str, const size_t str_size, const attribute *attr, db_value *val)
int to_db_varbit_from_bin_str (const char *str, const size_t str_size, const attribute *attr, db_value *val)
int to_db_varbit_from_hex_str (const char *str, const size_t str_size, const attribute *attr, db_value *val)
int to_db_elo_ext (const char *str, const size_t str_size, const attribute *attr, db_value *val)
int to_db_elo_int (const char *str, const size_t str_size, const attribute *attr, db_value *val)
int to_int_generic (const char *str, const size_t str_size, const attribute *attr, db_value *val)
static conv_setters init_setters ()
conv_func & get_conv_func (const data_type ldr_type, const DB_TYPE db_type)
void init_driver (driver *driver, session &session)
bool invoke_parser (driver *driver, const batch &batch_)
bool worker_manager_try_task (cubthread::entry_task *task)
void worker_manager_register_session (session &load_session)
void worker_manager_unregister_session (session &load_session)
void worker_manager_stop_all ()
void worker_manager_get_stats (UINT64 *stats_out)
Variables
const class_id NULL_CLASS_ID = 0
const batch_id NULL_BATCH_ID = 0
const class_id FIRST_CLASS_ID = 1
const batch_id FIRST_BATCH_ID = 1
static conv_setters setters = init_setters ()
static const std::size_t STRING_POOL_SIZE = 1024
static const std::size_t MAX_COPY_BUF_SIZE = 256
static const std::size_t COPY_BUF_POOL_SIZE = 512
static const std::size_t CONSTANT_POOL_SIZE = 1024
static const std::size_t QUOTED_STR_BUF_POOL_SIZE = 512
static const std::size_t MAX_QUOTED_STR_BUF_SIZE = 32 * 1024
static std::mutex g_wp_mutex
static std::condition_variable g_wp_condvar
std::set< session * > g_active_sessions
static cubthread::entry_workpool * g_worker_pool
static worker_context_manager * g_wp_context_manager
static cubthread::worker_pool_task_capper< cubthread::entry > * g_wp_task_capper
Typedef Documentation
using cubload::batch_handler = typedef std::function<int64_t (const batch &)>
Definition at line 77 of file load_common.hpp.
using cubload::batch_id = typedef int64_t
Definition at line 39 of file load_common.hpp.
using cubload::class_handler = typedef std::function<int64_t (const batch &, bool &)>
Definition at line 78 of file load_common.hpp.
using cubload::class_id = typedef int
Definition at line 40 of file load_common.hpp.
typedef int(* cubload::conv_func) (const char *, const size_t, const attribute *, db_value *)
Definition at line 34 of file load_db_value_converter.hpp.
using cubload::conv_setters = typedef std::array<std::array<conv_func, NUM_LDR_TYPES>, NUM_DB_TYPES>
Definition at line 80 of file load_db_value_converter.cpp.
Enumeration Type Documentation
enum cubload::attribute_type
Enumerator
LDR_ATTRIBUTE_ANY
LDR_ATTRIBUTE_SHARED
LDR_ATTRIBUTE_CLASS
LDR_ATTRIBUTE_DEFAULT
Definition at line 169 of file load_common.hpp.
enum cubload::data_type
Enumerator
LDR_NULL
LDR_INT
LDR_STR
LDR_NSTR
LDR_NUMERIC
LDR_DOUBLE
LDR_FLOAT
LDR_OID
LDR_CLASS_OID
LDR_DATE
LDR_TIME
LDR_TIMESTAMP
LDR_TIMESTAMPLTZ
LDR_TIMESTAMPTZ
LDR_COLLECTION
LDR_ELO_INT
LDR_ELO_EXT
LDR_SYS_USER
LDR_SYS_CLASS
LDR_MONETARY
LDR_BSTR
LDR_XSTR
LDR_DATETIME
LDR_DATETIMELTZ
LDR_DATETIMETZ
LDR_JSON
LDR_TYPE_MAX
Definition at line 129 of file load_common.hpp.
enum cubload::interrupt_type
Enumerator
LDR_NO_INTERRUPT
LDR_STOP_AND_ABORT_INTERRUPT
LDR_STOP_AND_COMMIT_INTERRUPT
Definition at line 177 of file load_common.hpp.
Function Documentation
bool cubload::ends_with (const std::string & str, const std::string & suffix) inline
Definition at line 780 of file load_common.cpp.
Referenced by split().
conv_func & cubload::get_conv_func (const data_type ldr_type, const DB_TYPE db_type)
Definition at line 197 of file load_db_value_converter.cpp.
Referenced by cubload::server_object_loader::process_generic_constant(), and cubload::server_object_loader::process_monetary_constant().
int cubload::handle_batch (batch_handler & handler, class_id clsid, std::string & batch_content, batch_id & batch_id, int64_t line_offset, int64_t & rows)
Definition at line 754 of file load_common.cpp.
References NO_ERROR.
Referenced by split().
void cubload::init_driver (driver * driver, session & session)
Definition at line 46 of file load_session.cpp.
References assert, cubload::session::fail(), cubload::driver::initialize(), cubload::driver::is_initialized(), and NULL.
Referenced by cubload::load_task::execute(), and cubload::session::session().
static conv_setters cubload::init_setters () static
Definition at line 86 of file load_db_value_converter.cpp.
References DB_TYPE_BIGINT, DB_TYPE_BIT, DB_TYPE_BLOB, DB_TYPE_CHAR, DB_TYPE_CLOB, DB_TYPE_DATE, DB_TYPE_DATETIME, DB_TYPE_DATETIMELTZ, DB_TYPE_DATETIMETZ, DB_TYPE_DOUBLE, DB_TYPE_ENUMERATION, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_JSON, DB_TYPE_MONETARY, DB_TYPE_MULTISET, DB_TYPE_NCHAR, DB_TYPE_NUMERIC, DB_TYPE_SEQUENCE, DB_TYPE_SET, DB_TYPE_SHORT, DB_TYPE_TIME, DB_TYPE_TIMESTAMP, DB_TYPE_TIMESTAMPLTZ, DB_TYPE_TIMESTAMPTZ, DB_TYPE_VARBIT, DB_TYPE_VARCHAR, DB_TYPE_VARNCHAR, i, LDR_BSTR, LDR_DATE, LDR_DATETIME, LDR_DATETIMELTZ, LDR_DATETIMETZ, LDR_DOUBLE, LDR_ELO_EXT, LDR_ELO_INT, LDR_FLOAT, LDR_INT, LDR_JSON, LDR_MONETARY, LDR_NSTR, LDR_NULL, LDR_NUMERIC, LDR_STR, LDR_TIME, LDR_TIMESTAMP, LDR_TIMESTAMPLTZ, LDR_TIMESTAMPTZ, LDR_XSTR, mismatch(), NUM_DB_TYPES, NUM_LDR_TYPES, to_db_bigint(), to_db_char(), to_db_date(), to_db_datetime(), to_db_datetimeltz(), to_db_datetimetz(), to_db_double(), to_db_elo_ext(), to_db_elo_int(), to_db_float(), to_db_int(), to_db_int_set(), to_db_json(), to_db_make_nchar(), to_db_make_varnchar(), to_db_monetary(), to_db_null(), to_db_numeric(), to_db_short(), to_db_string(), to_db_time(), to_db_timestamp(), to_db_timestampltz(), to_db_timestamptz(), to_db_varbit_from_bin_str(), to_db_varbit_from_hex_str(), to_db_varchar(), and to_int_generic().
bool cubload::invoke_parser (driver * driver, const batch & batch_)
Definition at line 69 of file load_session.cpp.
References cubload::object_loader::destroy(), cubload::batch::get_class_id(), cubload::driver::get_class_installer(), cubload::batch::get_content(), cubload::batch::get_line_offset(), cubload::driver::get_object_loader(), cubload::object_loader::init(), cubload::driver::is_initialized(), NULL, cubload::driver::parse(), and cubload::class_installer::set_class_id().
Referenced by cubload::load_task::execute(), and cubload::session::install_class().
int cubload::mismatch (const char * str, const size_t str_size, const attribute * attr, db_value * val)
Definition at line 204 of file load_db_value_converter.cpp.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_OBJ_DOMAIN_CONFLICT, er_set(), and cubload::attribute::get_name().
Referenced by init_setters().
void cubload::rtrim (std::string & str) inline
Definition at line 786 of file load_common.cpp.
Referenced by cubload::load_args::parse_ignore_class_file(), and split().
int cubload::split (int batch_size, const std::string & object_file_name, class_handler & c_handler, batch_handler & b_handler)
Definition at line 622 of file load_common.cpp.
References assert, ends_with(), ER_FILE_UNKNOWN_FILE, FIRST_CLASS_ID, handle_batch(), NO_ERROR, NULL_BATCH_ID, rtrim(), and starts_with().
Referenced by load_object_file().
bool cubload::starts_with (const std::string & str, const std::string & prefix) inline
Definition at line 774 of file load_common.cpp.
Referenced by split().
int cubload::to_db_bigint (const char * str, const size_t str_size, const attribute * attr, db_value * val)
Definition at line 320 of file load_db_value_converter.cpp.
References ARG_FILE_LINE, db_data::bigint, db_numeric::buf, db_numeric::d, db_value::data, db_make_bigint(), DB_TYPE_BIGINT, ER_ERROR_SEVERITY, ER_IT_DATA_OVERFLOW, er_set(), MAX_DIGITS_FOR_BIGINT, NO_ERROR, numeric_coerce_dec_str_to_num(), numeric_coerce_num_to_bigint(), parse_bigint(), and pr_type_name().
Referenced by init_setters(), and to_db_int_set().
int cubload::to_db_char (const char * str, const size_t str_size, const attribute * attr, db_value * val)
Definition at line 405 of file load_db_value_converter.cpp.
References DB_TYPE_CHAR, and to_db_generic_char().
Referenced by init_setters().
int cubload::to_db_date (const char * str, const size_t str_size, const attribute * attr, db_value * val)
Definition at line 494 of file load_db_value_converter.cpp.
References db_value::data, db_data::date, db_make_date(), and db_string_to_date().
Referenced by init_setters().
int cubload::to_db_datetime (const char * str, const size_t str_size, const attribute * attr, db_value * val)
Definition at line 540 of file load_db_value_converter.cpp.
References db_value::data, db_data::datetime, db_datetime_encode(), db_make_datetime(), and db_string_to_datetime().
Referenced by init_setters().
int cubload::to_db_datetimeltz (const char * str, const size_t str_size, const attribute * attr, db_value * val)
Definition at line 551 of file load_db_value_converter.cpp.
References db_value::data, db_data::datetime, db_datetime_encode(), db_make_datetimeltz(), and db_string_to_datetimeltz().
Referenced by init_setters().
int cubload::to_db_datetimetz (const char * str, const size_t str_size, const attribute * attr, db_value * val)
Definition at line 562 of file load_db_value_converter.cpp.
References db_value::data, db_datetimetz::datetime, db_data::datetimetz, db_datetime_encode(), db_make_datetimetz(), db_string_to_datetimetz(), and db_datetimetz::tz_id.
Referenced by init_setters().
int cubload::to_db_double (const char * str, const size_t str_size, const attribute * attr, db_value * val)
Definition at line 456 of file load_db_value_converter.cpp.
References ARG_FILE_LINE, db_data::d, db_value::data, db_make_double(), ER_ERROR_SEVERITY, ER_IT_DATA_OVERFLOW, er_set(), cubload::attribute::get_domain(), pr_type::get_name(), NO_ERROR, OR_CHECK_DOUBLE_OVERFLOW, and tp_domain::type.
Referenced by init_setters().
int cubload::to_db_elo_ext (const char * str, const size_t str_size, const attribute * attr, db_value * val)
Definition at line 762 of file load_db_value_converter.cpp.
References ARG_FILE_LINE, assert, db_make_elo(), db_private_alloc, db_private_free_and_init, DB_TYPE_BLOB, DB_TYPE_CLOB, ELO_FBO, elo_init_structure(), er_errid(), ER_ERROR_SEVERITY, ER_LDR_ELO_INPUT_FILE, er_set(), db_elo::locator, db_elo::meta_data, db_value::need_clear, NO_ERROR, NULL, db_elo::size, str_to_int64(), strlen, and db_elo::type.
Referenced by init_setters().
int cubload::to_db_elo_int (const char * str, const size_t str_size, const attribute * attr, db_value * val)
Definition at line 888 of file load_db_value_converter.cpp.
References assert, and ER_FAILED.
Referenced by init_setters().
int cubload::to_db_float (const char * str, const size_t str_size, const attribute * attr, db_value * val)
Definition at line 433 of file load_db_value_converter.cpp.
References ARG_FILE_LINE, db_value::data, db_make_float(), ER_ERROR_SEVERITY, ER_IT_DATA_OVERFLOW, er_set(), db_data::f, cubload::attribute::get_domain(), pr_type::get_name(), NO_ERROR, OR_CHECK_FLOAT_OVERFLOW, and tp_domain::type.
Referenced by init_setters().
int cubload::to_db_generic_char (DB_TYPE type, const char * str, const size_t str_size, const attribute * attr, db_value * val)
Definition at line 357 of file load_db_value_converter.cpp.
References ARG_FILE_LINE, tp_domain::codeset, tp_domain::collation_id, db_make_db_char(), db_value_domain_init(), ER_ERROR_SEVERITY, ER_IT_DATA_OVERFLOW, er_set(), error(), cubload::attribute::get_domain(), intl_char_count(), intl_char_size(), intl_skip_spaces(), NO_ERROR, p, pr_type_name(), and tp_domain::precision.
Referenced by to_db_char(), to_db_make_nchar(), to_db_make_varnchar(), and to_db_varchar().
int cubload::to_db_int (const char * str, const size_t str_size, const attribute * attr, db_value * val)
Definition at line 265 of file load_db_value_converter.cpp.
References ARG_FILE_LINE, db_value::data, db_make_int(), DB_TYPE_INTEGER, ER_ERROR_SEVERITY, ER_IT_DATA_OVERFLOW, er_set(), db_data::i, MAX_DIGITS_FOR_INT, NO_ERROR, OR_CHECK_INT_OVERFLOW, parse_int(), and pr_type_name().
Referenced by init_setters(), and to_db_int_set().
int cubload::to_db_int_set (const char * str, const size_t str_size, const attribute * attr, db_value * val)
Used in case of collection when if int overflows fallback to bigint
Definition at line 306 of file load_db_value_converter.cpp.
References er_clear(), ER_IT_DATA_OVERFLOW, to_db_bigint(), and to_db_int().
Referenced by init_setters().
int cubload::to_db_json (const char * str, const size_t str_size, const attribute * attr, db_value * val)
Definition at line 579 of file load_db_value_converter.cpp.
References assert, db_json_get_json_from_str(), db_make_json(), NO_ERROR, and NULL.
Referenced by init_setters().
int cubload::to_db_make_nchar (const char * str, const size_t str_size, const attribute * attr, db_value * val)
Definition at line 416 of file load_db_value_converter.cpp.
References DB_TYPE_NCHAR, and to_db_generic_char().
Referenced by init_setters().
int cubload::to_db_make_varnchar (const char * str, const size_t str_size, const attribute * attr, db_value * val)
Definition at line 421 of file load_db_value_converter.cpp.
References DB_TYPE_VARNCHAR, and to_db_generic_char().
Referenced by init_setters().
int cubload::to_db_monetary (const char * str, const size_t str_size, const attribute * attr, db_value * val)
Definition at line 594 of file load_db_value_converter.cpp.
References ARG_FILE_LINE, CURRENCY_CHECK_MODE_ESC_ISO, CURRENCY_CHECK_MODE_GRAMMAR, DB_CURRENCY_DOLLAR, DB_CURRENCY_NULL, db_make_monetary(), DB_TYPE_MONETARY, ER_ERROR_SEVERITY, ER_IT_DATA_OVERFLOW, er_set(), intl_is_currency_symbol(), OR_CHECK_DOUBLE_OVERFLOW, p, and pr_type_name().
Referenced by init_setters().
int cubload::to_db_null (const char * str, const size_t str_size, const attribute * attr, db_value * val)
Definition at line 212 of file load_db_value_converter.cpp.
References db_make_null(), ER_OBJ_ATTRIBUTE_CANT_BE_NULL, cubload::attribute::get_repr(), and or_attribute::is_notnull.
Referenced by init_setters().
int cubload::to_db_numeric (const char * str, const size_t str_size, const attribute * attr, db_value * val)
Definition at line 479 of file load_db_value_converter.cpp.
References DB_TYPE_C_CHAR, DB_TYPE_NUMERIC, db_value_domain_init(), db_value_put(), and NO_ERROR.
Referenced by init_setters().
int cubload::to_db_short (const char * str, const size_t str_size, const attribute * attr, db_value * val)
Definition at line 225 of file load_db_value_converter.cpp.
References ARG_FILE_LINE, db_value::data, db_make_short(), DB_TYPE_SHORT, ER_ERROR_SEVERITY, ER_IT_DATA_OVERFLOW, er_set(), MAX_DIGITS_FOR_SHORT, NO_ERROR, OR_CHECK_SHORT_OVERFLOW, parse_int(), pr_type_name(), and db_data::sh.
Referenced by init_setters().
int cubload::to_db_string (const char * str, const size_t str_size, const attribute * attr, db_value * val)
Definition at line 427 of file load_db_value_converter.cpp.
References db_make_string().
Referenced by init_setters().
int cubload::to_db_time (const char * str, const size_t str_size, const attribute * attr, db_value * val)
Definition at line 502 of file load_db_value_converter.cpp.
References db_value::data, db_make_time(), db_string_to_time(), and db_data::time.
Referenced by init_setters().
int cubload::to_db_timestamp (const char * str, const size_t str_size, const attribute * attr, db_value * val)
Definition at line 510 of file load_db_value_converter.cpp.
References db_value::data, db_make_timestamp(), db_string_to_timestamp(), and db_data::utime.
Referenced by init_setters().
int cubload::to_db_timestampltz (const char * str, const size_t str_size, const attribute * attr, db_value * val)
Definition at line 518 of file load_db_value_converter.cpp.
References db_value::data, db_make_timestampltz(), db_string_to_timestampltz(), and db_data::utime.
Referenced by init_setters().
int cubload::to_db_timestamptz (const char * str, const size_t str_size, const attribute * attr, db_value * val)
Definition at line 526 of file load_db_value_converter.cpp.
References db_value::data, db_make_timestamptz(), db_string_to_timestamptz(), db_timestamptz::timestamp, db_data::timestamptz, and db_timestamptz::tz_id.
Referenced by init_setters().
int cubload::to_db_varbit_from_bin_str (const char * str, const size_t str_size, const attribute * attr, db_value * val)
Definition at line 629 of file load_db_value_converter.cpp.
References ARG_FILE_LINE, assert, db_make_varbit(), db_private_alloc, db_private_free_and_init, db_value_clear(), db_value_domain_init(), DOMAIN_COMPATIBLE, er_errid(), ER_ERROR_SEVERITY, ER_OBJ_DOMAIN_CONFLICT, er_set(), cubload::attribute::get_domain(), cubload::attribute::get_name(), pr_type::id, db_value::need_clear, NO_ERROR, NULL, tp_domain::precision, qstr_bit_to_bin(), tp_domain::scale, tp_domain_resolve_value(), TP_FLOATING_PRECISION_VALUE, tp_value_cast(), and tp_domain::type.
Referenced by init_setters().
int cubload::to_db_varbit_from_hex_str (const char * str, const size_t str_size, const attribute * attr, db_value * val)
Definition at line 695 of file load_db_value_converter.cpp.
References ARG_FILE_LINE, assert, db_make_null(), db_make_varbit(), db_private_alloc, db_private_free_and_init, db_value_clear(), db_value_domain_init(), er_errid(), ER_ERROR_SEVERITY, ER_OBJ_DOMAIN_CONFLICT, er_set(), cubload::attribute::get_domain(), cubload::attribute::get_name(), pr_type::id, db_value::need_clear, NO_ERROR, NULL, tp_domain::precision, qstr_hex_to_bin(), tp_domain::scale, tp_domain_resolve_value(), TP_FLOATING_PRECISION_VALUE, tp_value_cast(), and tp_domain::type.
Referenced by init_setters().
int cubload::to_db_varchar (const char * str, const size_t str_size, const attribute * attr, db_value * val)
Definition at line 411 of file load_db_value_converter.cpp.
References DB_TYPE_VARCHAR, and to_db_generic_char().
Referenced by init_setters().
int cubload::to_int_generic (const char * str, const size_t str_size, const attribute * attr, db_value * val)
Definition at line 896 of file load_db_value_converter.cpp.
References ARG_FILE_LINE, ASSERT_ERROR, db_data::bigint, db_numeric::buf, db_numeric::d, db_value::data, db_make_bigint(), db_make_int(), DB_TYPE_BIGINT, DB_TYPE_C_CHAR, DB_TYPE_INTEGER, DB_TYPE_NUMERIC, db_value_domain_init(), db_value_put(), ER_ERROR_SEVERITY, ER_IT_DATA_OVERFLOW, er_set(), db_data::i, MAX_DIGITS_FOR_BIGINT, MAX_DIGITS_FOR_INT, NO_ERROR, numeric_coerce_dec_str_to_num(), numeric_coerce_num_to_bigint(), parse_bigint(), parse_int(), and pr_type_name().
Referenced by init_setters().
void cubload::worker_manager_get_stats (UINT64 * stats_out)
Definition at line 182 of file load_worker_manager.cpp.
References cubthread::worker_pool< Context >::get_stats(), and NULL.
Referenced by perfmon_server_calc_stats().
void cubload::worker_manager_register_session (session & load_session)
Definition at line 105 of file load_worker_manager.cpp.
References assert, cubthread::manager::create_worker_pool(), g_worker_pool, cubthread::get_manager(), NULL, prm_get_integer_value(), PRM_ID_LOADDB_WORKER_COUNT, and cubload::worker_context_manager::worker_context_manager().
Referenced by cubload::session::session().
void cubload::worker_manager_stop_all ()
Definition at line 162 of file load_worker_manager.cpp.
Referenced by css_init().
bool cubload::worker_manager_try_task (cubthread::entry_task * task)
Definition at line 98 of file load_worker_manager.cpp.
References assert, NULL, and cubthread::worker_pool_task_capper< Context >::try_task().
Referenced by cubload::session::load_batch().
void cubload::worker_manager_unregister_session (session & load_session)
Definition at line 134 of file load_worker_manager.cpp.
References assert, cubthread::manager::destroy_worker_pool(), g_wp_context_manager, g_wp_task_capper, cubthread::get_manager(), and NULL.
Referenced by cubload::session::~session().
Variable Documentation
const std::size_t cubload::CONSTANT_POOL_SIZE = 1024 static
Definition at line 37 of file load_semantic_helper.hpp.
Referenced by cubload::semantic_helper::make_constant().
const std::size_t cubload::COPY_BUF_POOL_SIZE = 512 static
Definition at line 36 of file load_semantic_helper.hpp.
Referenced by cubload::semantic_helper::use_copy_buf_pool().
const batch_id cubload::FIRST_BATCH_ID = 1
Definition at line 45 of file load_common.hpp.
Referenced by cubload::session::wait_for_previous_batch().
const class_id cubload::FIRST_CLASS_ID = 1
Definition at line 44 of file load_common.hpp.
Referenced by cubload::session::session(), and split().
std::set<session *> cubload::g_active_sessions
Definition at line 63 of file load_worker_manager.cpp.
cubthread::entry_workpool* cubload::g_worker_pool static
Definition at line 64 of file load_worker_manager.cpp.
Referenced by worker_manager_register_session().
std::condition_variable cubload::g_wp_condvar static
Definition at line 62 of file load_worker_manager.cpp.
worker_context_manager* cubload::g_wp_context_manager static
Definition at line 65 of file load_worker_manager.cpp.
Referenced by worker_manager_unregister_session().
std::mutex cubload::g_wp_mutex static
Definition at line 61 of file load_worker_manager.cpp.
cubthread::worker_pool_task_capper<cubthread::entry>* cubload::g_wp_task_capper static
Definition at line 66 of file load_worker_manager.cpp.
Referenced by worker_manager_unregister_session().
const std::size_t cubload::MAX_COPY_BUF_SIZE = 256 static
Definition at line 35 of file load_semantic_helper.hpp.
Referenced by cubload::semantic_helper::use_copy_buf_pool().
const std::size_t cubload::MAX_QUOTED_STR_BUF_SIZE = 32 * 1024 static
Definition at line 39 of file load_semantic_helper.hpp.
Referenced by cubload::semantic_helper::append_char(), and cubload::semantic_helper::set_quoted_string_buffer().
const batch_id cubload::NULL_BATCH_ID = 0
Definition at line 43 of file load_common.hpp.
Referenced by cubload::session::session(), and split().
const class_id cubload::NULL_CLASS_ID = 0
Definition at line 42 of file load_common.hpp.
Referenced by cubload::server_object_loader::destroy(), and cubload::server_class_installer::register_class_with_attributes().
const std::size_t cubload::QUOTED_STR_BUF_POOL_SIZE = 512 static
Definition at line 38 of file load_semantic_helper.hpp.
Referenced by cubload::semantic_helper::set_quoted_string_buffer().
conv_setters cubload::setters = init_setters () static
Definition at line 83 of file load_db_value_converter.cpp.
const std::size_t cubload::STRING_POOL_SIZE = 1024 static
Definition at line 34 of file load_semantic_helper.hpp.
Referenced by cubload::semantic_helper::clear(), and cubload::semantic_helper::make_string().