CUBRID Engine: filesys Namespace Reference
filesys Namespace Reference
Classes
struct file_closer
struct file_deleter
Typedefs
using auto_close_file = std::unique_ptr< FILE, file_closer >
using auto_delete_file = std::unique_ptr< const char, file_deleter >
Functions
std::pair< std::string, int > open_temp_filedes (const char *prefix, int flags=0)
std::pair< std::string, FILE * > open_temp_file (const char *prefix, const char *mode="w", int flags=0)
Typedef Documentation
using filesys::auto_close_file = typedef std::unique_ptr<FILE, file_closer>
Definition at line 43 of file filesys.hpp.
using filesys::auto_delete_file = typedef std::unique_ptr<const char, file_deleter>
Definition at line 58 of file filesys.hpp.
Function Documentation
std::pair< std::string, FILE * > filesys::open_temp_file (const char * prefix, const char * mode = "w", int flags = 0)
Definition at line 69 of file filesys_temp.cpp.
References mode.
Referenced by csql_invoke_system_editor(), and csql_print_buffer().
std::pair< std::string, int > filesys::open_temp_filedes (const char * prefix, int flags = 0)
Definition at line 55 of file filesys_temp.cpp.
Referenced by fh_create().