CUBRID Engine: cubmonitor Namespace Reference
cubmonitor Namespace Reference
Classes
class accumulator_atomic_statistic
class accumulator_statistic
class atomic_primitive
class atomic_primitive< time_rep >
class counter_timer_max_statistic
class counter_timer_statistic
class gauge_atomic_statistic
class gauge_statistic
class max_atomic_statistic
class max_statistic
class min_atomic_statistic
class min_statistic
class monitor
class primitive
class timer
class timer_statistic
class transaction_sheet_manager
class transaction_statistic
Typedefs
using timer_stat = timer_statistic< time_accumulator_statistic >
using atomic_timer_stat = timer_statistic< time_accumulator_atomic_statistic >
using transaction_timer_stat = timer_statistic< transaction_statistic< time_accumulator_statistic >>
using transaction_atomic_timer_stat = timer_statistic< transaction_statistic< time_accumulator_atomic_statistic >>
using counter_timer_stat = counter_timer_statistic<>
using atomic_counter_timer_stat = counter_timer_statistic< amount_accumulator_atomic_statistic, time_accumulator_atomic_statistic >
using statistic_value = std::uint64_t
using clock_type = std::chrono::high_resolution_clock
using time_point = clock_type::time_point
using duration = clock_type::duration
using fetch_mode = bool
using amount_rep = std::uint64_t
using floating_rep = double
using time_rep = duration
using amount_accumulator_statistic = accumulator_statistic< amount_rep >
using floating_accumulator_statistic = accumulator_statistic< floating_rep >
using time_accumulator_statistic = accumulator_statistic< time_rep >
using amount_gauge_statistic = gauge_statistic< amount_rep >
using floating_gauge_statistic = gauge_statistic< floating_rep >
using time_gauge_statistic = gauge_statistic< time_rep >
using amount_max_statistic = max_statistic< amount_rep >
using floating_max_statistic = max_statistic< floating_rep >
using time_max_statistic = max_statistic< time_rep >
using amount_min_statistic = min_statistic< amount_rep >
using floating_min_statistic = min_statistic< floating_rep >
using time_min_statistic = min_statistic< time_rep >
using amount_accumulator_atomic_statistic = accumulator_atomic_statistic< amount_rep >
using time_accumulator_atomic_statistic = accumulator_atomic_statistic< time_rep >
using amount_gauge_atomic_statistic = gauge_atomic_statistic< amount_rep >
using time_gauge_atomic_statistic = gauge_atomic_statistic< time_rep >
using amount_max_atomic_statistic = max_atomic_statistic< amount_rep >
using time_max_atomic_statistic = max_atomic_statistic< time_rep >
using amount_min_atomic_statistic = min_atomic_statistic< amount_rep >
using time_min_atomic_statistic = min_atomic_statistic< time_rep >
using transaction_sheet = std::size_t
Functions
void build_name_vector (std::vector< std::string > &names, const char *basename, const char *prefix)
template<typename... Args>
void build_name_vector (std::vector< std::string > &names, const char *basename, const char *prefix, Args &&...args)
monitor & get_global_monitor (void)
statistic_value statistic_value_cast (const amount_rep &rep)
amount_rep amount_rep_cast (statistic_value value)
statistic_value statistic_value_cast (const floating_rep &rep)
floating_rep floating_rep_cast (statistic_value value)
statistic_value statistic_value_cast (const time_rep &rep)
time_rep time_rep_cast (statistic_value value)
Variables
const fetch_mode FETCH_GLOBAL = true
const fetch_mode FETCH_TRANSACTION_SHEET = false
static monitor Monitor
Typedef Documentation
using cubmonitor::amount_accumulator_atomic_statistic = typedef accumulator_atomic_statistic<amount_rep>
Definition at line 405 of file monitor_statistic.hpp.
using cubmonitor::amount_accumulator_statistic = typedef accumulator_statistic<amount_rep>
Definition at line 388 of file monitor_statistic.hpp.
using cubmonitor::amount_gauge_atomic_statistic = typedef gauge_atomic_statistic<amount_rep>
Definition at line 411 of file monitor_statistic.hpp.
using cubmonitor::amount_gauge_statistic = typedef gauge_statistic<amount_rep>
Definition at line 392 of file monitor_statistic.hpp.
using cubmonitor::amount_max_atomic_statistic = typedef max_atomic_statistic<amount_rep>
Definition at line 417 of file monitor_statistic.hpp.
using cubmonitor::amount_max_statistic = typedef max_statistic<amount_rep>
Definition at line 396 of file monitor_statistic.hpp.
using cubmonitor::amount_min_atomic_statistic = typedef min_atomic_statistic<amount_rep>
Definition at line 423 of file monitor_statistic.hpp.
using cubmonitor::amount_min_statistic = typedef min_statistic<amount_rep>
Definition at line 400 of file monitor_statistic.hpp.
using cubmonitor::amount_rep = typedef std::uint64_t
Definition at line 90 of file monitor_statistic.hpp.
using cubmonitor::atomic_counter_timer_stat = typedef counter_timer_statistic<amount_accumulator_atomic_statistic, time_accumulator_atomic_statistic>
Definition at line 184 of file monitor_collect.hpp.
using cubmonitor::atomic_timer_stat = typedef timer_statistic<time_accumulator_atomic_statistic>
Definition at line 120 of file monitor_collect.hpp.
using cubmonitor::clock_type = typedef std::chrono::high_resolution_clock
Definition at line 36 of file monitor_definition.hpp.
using cubmonitor::counter_timer_stat = typedef counter_timer_statistic<>
Definition at line 182 of file monitor_collect.hpp.
using cubmonitor::duration = typedef clock_type::duration
Definition at line 38 of file monitor_definition.hpp.
using cubmonitor::fetch_mode = typedef bool
Definition at line 41 of file monitor_definition.hpp.
using cubmonitor::floating_accumulator_statistic = typedef accumulator_statistic<floating_rep>
Definition at line 389 of file monitor_statistic.hpp.
using cubmonitor::floating_gauge_statistic = typedef gauge_statistic<floating_rep>
Definition at line 393 of file monitor_statistic.hpp.
using cubmonitor::floating_max_statistic = typedef max_statistic<floating_rep>
Definition at line 397 of file monitor_statistic.hpp.
using cubmonitor::floating_min_statistic = typedef min_statistic<floating_rep>
Definition at line 401 of file monitor_statistic.hpp.
using cubmonitor::floating_rep = typedef double
Definition at line 92 of file monitor_statistic.hpp.
using cubmonitor::statistic_value = typedef std::uint64_t
Definition at line 33 of file monitor_definition.hpp.
using cubmonitor::time_accumulator_atomic_statistic = typedef accumulator_atomic_statistic<time_rep>
Definition at line 409 of file monitor_statistic.hpp.
using cubmonitor::time_accumulator_statistic = typedef accumulator_statistic<time_rep>
Definition at line 390 of file monitor_statistic.hpp.
using cubmonitor::time_gauge_atomic_statistic = typedef gauge_atomic_statistic<time_rep>
Definition at line 415 of file monitor_statistic.hpp.
using cubmonitor::time_gauge_statistic = typedef gauge_statistic<time_rep>
Definition at line 394 of file monitor_statistic.hpp.
using cubmonitor::time_max_atomic_statistic = typedef max_atomic_statistic<time_rep>
Definition at line 421 of file monitor_statistic.hpp.
using cubmonitor::time_max_statistic = typedef max_statistic<time_rep>
Definition at line 398 of file monitor_statistic.hpp.
using cubmonitor::time_min_atomic_statistic = typedef min_atomic_statistic<time_rep>
Definition at line 427 of file monitor_statistic.hpp.
using cubmonitor::time_min_statistic = typedef min_statistic<time_rep>
Definition at line 402 of file monitor_statistic.hpp.
using cubmonitor::time_point = typedef clock_type::time_point
Definition at line 37 of file monitor_definition.hpp.
using cubmonitor::time_rep = typedef duration
Definition at line 94 of file monitor_statistic.hpp.
using cubmonitor::timer_stat = typedef timer_statistic<time_accumulator_statistic>
Definition at line 119 of file monitor_collect.hpp.
using cubmonitor::transaction_atomic_timer_stat = typedef timer_statistic<transaction_statistic<time_accumulator_atomic_statistic>>
Definition at line 122 of file monitor_collect.hpp.
using cubmonitor::transaction_sheet = typedef std::size_t
Definition at line 49 of file monitor_transaction.hpp.
using cubmonitor::transaction_timer_stat = typedef timer_statistic<transaction_statistic<time_accumulator_statistic>>
Definition at line 121 of file monitor_collect.hpp.
Function Documentation
amount_rep cubmonitor::amount_rep_cast (statistic_value value)
Definition at line 41 of file monitor_statistic.cpp.
void cubmonitor::build_name_vector (std::vector< std::string > & names, const char * basename, const char * prefix)
Definition at line 24 of file monitor_collect.cpp.
Referenced by build_name_vector(), cubmonitor::counter_timer_statistic< A, T >::register_to_monitor(), and cubmonitor::counter_timer_max_statistic< A, T, M >::register_to_monitor().
template<typename... Args> void cubmonitor::build_name_vector (std::vector< std::string > & names, const char * basename, const char * prefix, Args &&... args)
Definition at line 61 of file monitor_collect.hpp.
References build_name_vector().
floating_rep cubmonitor::floating_rep_cast (statistic_value value)
Definition at line 56 of file monitor_statistic.cpp.
monitor & cubmonitor::get_global_monitor (void)
Definition at line 157 of file monitor_registration.cpp.
References Monitor.
statistic_value cubmonitor::statistic_value_cast (const amount_rep & rep)
Definition at line 35 of file monitor_statistic.cpp.
Referenced by cubmonitor::primitive< Rep >::fetch(), cubmonitor::atomic_primitive< Rep >::fetch(), cubmonitor::atomic_primitive< time_rep >::fetch(), cubmonitor::counter_timer_statistic< A, T >::register_to_monitor(), and cubmonitor::counter_timer_max_statistic< A, T, M >::register_to_monitor().
statistic_value cubmonitor::statistic_value_cast (const floating_rep & rep)
Definition at line 47 of file monitor_statistic.cpp.
statistic_value cubmonitor::statistic_value_cast (const time_rep & rep)
Definition at line 65 of file monitor_statistic.cpp.
References cubregex::count().
time_rep cubmonitor::time_rep_cast (statistic_value value)
Definition at line 72 of file monitor_statistic.cpp.
Variable Documentation
const fetch_mode cubmonitor::FETCH_GLOBAL = true
Definition at line 42 of file monitor_definition.hpp.
Referenced by cubmonitor::transaction_statistic< S >::fetch(), cubmonitor::monitor::fetch_global_statistics(), cubmonitor::transaction_statistic< S >::get_value(), cubmonitor::atomic_primitive< time_rep >::get_value(), cubmonitor::primitive< Rep >::operator=(), cubmonitor::atomic_primitive< Rep >::operator=(), and cubmonitor::atomic_primitive< time_rep >::operator=().
const fetch_mode cubmonitor::FETCH_TRANSACTION_SHEET = false
Definition at line 43 of file monitor_definition.hpp.
Referenced by cubmonitor::primitive< Rep >::fetch(), cubmonitor::atomic_primitive< Rep >::fetch(), cubmonitor::atomic_primitive< time_rep >::fetch(), and cubmonitor::monitor::fetch_transaction_statistics().
monitor cubmonitor::Monitor static
Definition at line 155 of file monitor_registration.cpp.
Referenced by get_global_monitor().