CUBRID Engine: cubsync Namespace Reference
cubsync Namespace Reference
Classes
class critical_section_tracker
class event_semaphore
class semaphore
Functions
static void cstrack_assert (bool cond)
Function Documentation
static void cubsync::cstrack_assert (bool cond) static
Definition at line 36 of file critical_section_tracker.cpp.
References cubbase::restrack_assert().
Referenced by cubsync::critical_section_tracker::check(), cubsync::critical_section_tracker::check_csect_interdependencies(), cubsync::critical_section_tracker::on_demote(), cubsync::critical_section_tracker::on_enter_as_reader(), cubsync::critical_section_tracker::on_enter_as_writer(), cubsync::critical_section_tracker::on_exit(), cubsync::critical_section_tracker::on_promote(), and cubsync::critical_section_tracker::stop().