CUBRID Engine: cubthread::internal_tasks_worker_pool Namespace Reference
cubthread::internal_tasks_worker_pool Namespace Reference
Functions
void initialize ()
entry_workpool * get_instance ()
void finalize ()
Function Documentation
void cubthread::internal_tasks_worker_pool::finalize ()
Definition at line 54 of file internal_tasks_worker_pool.cpp.
References cubthread::instance, and NULL.
Referenced by net_server_start(), and set_to_string().
entry_workpool * cubthread::internal_tasks_worker_pool::get_instance ()
Definition at line 48 of file internal_tasks_worker_pool.cpp.
References assert, cubthread::instance, and NULL.
void cubthread::internal_tasks_worker_pool::initialize ()
Definition at line 37 of file internal_tasks_worker_pool.cpp.
References cubthread::manager::create_worker_pool(), cubthread::get_manager(), and NULL.
Referenced by net_server_start(), and pgbuf_get_page_flush_interval().