CUBRID Engine: lockfree::tran Namespace Reference
lockfree::tran Namespace Reference
Classes
class descriptor
class reclaimable_node
class system
class table
Typedefs
using index = size_t
using id = std::uint64_t
Variables
static const id INVALID_TRANID = std::numeric_limits<id>::max ()
static const index INVALID_INDEX = std::numeric_limits<index>::max ()
Typedef Documentation
using lockfree::tran::id = typedef std::uint64_t
Definition at line 33 of file lockfree_transaction_def.hpp.
using lockfree::tran::index = typedef size_t
Definition at line 30 of file lockfree_transaction_def.hpp.
Variable Documentation
const index lockfree::tran::INVALID_INDEX = std::numeric_limits<index>::max () static
Definition at line 74 of file lockfree_transaction_system.hpp.
Referenced by lockfree::tran::system::assign_index(), lockfree::tran::system::free_index(), and cubthread::entry::pull_lf_tran_index().
const id lockfree::tran::INVALID_TRANID = std::numeric_limits<id>::max () static
Definition at line 49 of file lockfree_transaction_descriptor.hpp.
Referenced by lockfree::tran::table::compute_min_active_tranid(), lockfree::tran::descriptor::end_tran(), lockfree::tran::descriptor::is_tran_started(), and lockfree::tran::descriptor::start_tran_and_increment_id().