CUBRID Engine: lockfree Namespace Reference
lockfree Namespace Reference
Namespaces
tran
Classes
class address_marker
class bitmap
class circular_queue
class freelist
class hashmap
Functions
static void lf_bitmap_init (LF_BITMAP *bitmap, LF_BITMAP_STYLE style, int entries_cnt, float usage_threshold)
static void lf_bitmap_destroy (LF_BITMAP *bitmap)
static int lf_bitmap_get_entry (LF_BITMAP *bitmap)
static void lf_bitmap_free_entry (LF_BITMAP *bitmap, int entry_idx)
Function Documentation
static void lockfree::lf_bitmap_destroy (LF_BITMAP * bitmap) static
Definition at line 123 of file lockfree_bitmap.cpp.
References assert, lockfree::bitmap::bitfield, lockfree::bitmap::entry_count, lockfree::bitmap::entry_count_in_use, LF_BITMAP_ONE_CHUNK, NULL, lockfree::bitmap::start_idx, lockfree::bitmap::style, and lockfree::bitmap::usage_threshold.
Referenced by lockfree::bitmap::destroy().
static void lockfree::lf_bitmap_free_entry (LF_BITMAP * bitmap, int entry_idx) static
Definition at line 237 of file lockfree_bitmap.cpp.
References assert, lockfree::bitmap::bitfield, lockfree::bitmap::entry_count, lockfree::bitmap::entry_count_in_use, LF_BITFIELD_WORD_SIZE, LF_BITMAP_LIST_OF_CHUNKS, NULL, lockfree::bitmap::start_idx, and lockfree::bitmap::style.
Referenced by lockfree::bitmap::free_entry().
static int lockfree::lf_bitmap_get_entry (LF_BITMAP * bitmap) static
Definition at line 136 of file lockfree_bitmap.cpp.
References assert, lockfree::bitmap::bitfield, CEIL_PTVDIV, lockfree::bitmap::entry_count, lockfree::bitmap::entry_count_in_use, i, LF_BITFIELD_WORD_SIZE, LF_BITMAP_IS_FULL, LF_BITMAP_LIST_OF_CHUNKS, LF_BITMAP_ONE_CHUNK, NULL, lockfree::bitmap::start_idx, and lockfree::bitmap::style.
Referenced by lockfree::bitmap::get_entry().
static void lockfree::lf_bitmap_init (LF_BITMAP * bitmap, LF_BITMAP_STYLE style, int entries_cnt, float usage_threshold) static
Definition at line 81 of file lockfree_bitmap.cpp.
References assert, lockfree::bitmap::bitfield, CEIL_PTVDIV, lockfree::bitmap::entry_count, lockfree::bitmap::entry_count_in_use, i, LF_BITFIELD_WORD_SIZE, LF_BITMAP_LIST_OF_CHUNKS, NULL, lockfree::bitmap::start_idx, lockfree::bitmap::style, and lockfree::bitmap::usage_threshold.
Referenced by lockfree::bitmap::init().