CUBRID Engine: cubregex Namespace Reference
cubregex Namespace Reference
Functions
std::string parse_regex_exception (std::regex_error &e)
int parse_match_type (std::regex_constants::syntax_option_type &reg_flags, std::string &opt_str)
void clear (cub_regex_object *&regex, char *&pattern)
bool check_should_recompile (const cub_regex_object *compiled_regex, const char *compiled_pattern, const std::string &pattern, const std::regex_constants::syntax_option_type reg_flags)
int compile (cub_regex_object *&compiled_regex, const char *pattern, const std::regex_constants::syntax_option_type reg_flags, const LANG_COLLATION *collation)
int search (int &result, const cub_regex_object &reg, const std::string &src, const INTL_CODESET codeset)
int count (int &result, const cub_regex_object &reg, const std::string &src, const int position, const INTL_CODESET codeset)
int instr (int &result, const cub_regex_object &reg, const std::string &src, const int position, const int occurrence, const int return_opt, const INTL_CODESET codeset)
int replace (std::string &result, const cub_regex_object &reg, const std::string &src, const std::string &repl, const int position, const int occurrence, const INTL_CODESET codeset)
int substr (std::string &result, bool &is_matched, const cub_regex_object &reg, const std::string &src, const int position, const int occurrence, const INTL_CODESET codeset)
Function Documentation
bool cubregex::check_should_recompile (const cub_regex_object * compiled_regex, const char * compiled_pattern, const std::string & pattern, const std::regex_constants::syntax_option_type reg_flags)
Definition at line 140 of file string_regex.cpp.
References NULL, and strlen.
Referenced by db_string_regexp_count(), db_string_regexp_instr(), db_string_regexp_like(), db_string_regexp_replace(), db_string_regexp_substr(), and db_string_rlike().
void cubregex::clear (cub_regex_object *& regex, char *& pattern)
Definition at line 126 of file string_regex.cpp.
References db_private_free_and_init, and NULL.
Referenced by cubxasl::pred_expr::clear_xasl(), db_string_regexp_count(), db_string_regexp_instr(), db_string_regexp_like(), db_string_regexp_replace(), db_string_regexp_substr(), db_string_rlike(), ehash_find_depth(), main(), print_appl_header(), qexec_clear_pred(), qexec_cmp_tpl_vals_merge(), and thread_set_clear_trace().
int cubregex::compile (cub_regex_object *& compiled_regex, const char * pattern, const std::regex_constants::syntax_option_type reg_flags, const LANG_COLLATION * collation)
Definition at line 160 of file string_regex.cpp.
References ARG_FILE_LINE, lang_collation::codeset, cublocale::convert_to_wstring(), ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, ER_QSTR_BAD_SRC_CODESET, ER_REGEX_COMPILE_ERROR, er_set(), cublocale::get_lang_name(), cublocale::get_locale(), NO_ERROR, NULL, and parse_regex_exception().
Referenced by db_string_regexp_count(), db_string_regexp_instr(), db_string_regexp_like(), db_string_regexp_replace(), db_string_regexp_substr(), and db_string_rlike().
int cubregex::count (int & result, const cub_regex_object & reg, const std::string & src, const int position, const INTL_CODESET codeset)
Definition at line 264 of file string_regex.cpp.
References ARG_FILE_LINE, assert, cublocale::convert_to_wstring(), ER_ERROR_SEVERITY, ER_QSTR_BAD_SRC_CODESET, ER_REGEX_EXEC_ERROR, er_set(), NO_ERROR, and parse_regex_exception().
Referenced by add_element(), cubmonitor::monitor::add_registration(), cubmem::private_allocator< T >::address(), bitset_string(), btree_find_multi_uniques(), build_xasl_for_server_delete(), calc_avg(), calc_min_max(), calc_stddev(), catalog_get_cardinality(), catalog_sum_disk_attribute_size(), catcls_free_sub_value(), catcls_get_object_set(), catcls_get_subset(), cfg_get_hosts(), check_trigger(), lockfree::freelist< T >::claim(), classobj_copy_constraint_like(), classobj_find_class_primary_key(), classobj_point_at_att_names(), HL::SpinLockType::contendedLock(), copy_and_shift_values(), count_bits(), csession_drop_session_variables(), csession_set_session_variables(), css_count_transaction_worker_threads(), css_fd_error(), css_is_any_thread_not_suspended_mapfunc(), css_process_all_count_info(), css_process_request_count_info(), css_process_server_count_info(), css_start_all_threads(), cursor_fetch_page_having_tuple(), da_create(), da_expand(), db_2pc_prepared_transactions(), db_fetch_array(), db_json_get_paths_helper(), db_method_arg_count(), db_string_regexp_count(), delete_list_by_oids(), object_printer::describe_domain(), do_alter_trigger(), do_check_rows_for_null(), do_drop_session_variables(), do_insert_at_server(), do_replace_names_for_insert_values_pre(), do_set_session_variables(), lockfree::hashmap< Key, T >::dump_stat(), elo_write(), emit_domain_def(), es_posix_final(), file_extdata_append_array(), file_extdata_insert_at(), file_extdata_remove_at(), file_log_extdata_add(), file_log_extdata_remove(), file_rv_dump_extdata_add(), file_rv_dump_extdata_remove(), file_rv_extdata_add(), file_rv_extdata_remove(), fileio_flush_backup(), fileio_write_backup_header(), find_update_columns(), fn_xa_end_tran(), fn_xa_recover(), get_col_count(), cubthread::manager::get_lockfree_transys(), get_object_set(), get_ordered_classes(), get_substructure_set(), hb_cluster_job_failback(), hb_kill_all_heartbeat_process(), hb_kill_process(), heap_classrepr_dump_all(), heap_rv_dump_append_pages_to_heap(), help_class_names(), help_trigger_names(), object_description::init(), class_description::init(), install_substructure_set(), intl_char_tolower_utf8(), intl_char_toupper_utf8(), jsp_get_argument_count(), lang_locales_count(), ldr_assign_all_perm_oids(), locator_get_packed_oid_set_size(), lock_demote_class_lock(), lock_stop_instant_lock_mode(), log_2pc_recovery_prepared(), logddl_set_commit_count(), logpb_get_archive_num_from_info_table(), logtb_count_clients(), logtb_count_not_allowed_clients_in_maintenance_mode(), logtb_find_current_tranid(), main(), method_invoke_for_server(), mq_get_expression(), object_disk_size(), object_set_size(), or_get_enumeration(), or_header_size(), or_skip_set_header(), or_unpack_unbound_listid(), os_send_signal(), cubpacking::packer::pack_int_array(), cubpacking::packer::pack_int_vector(), parse_digits(), pgbuf_assign_direct_victim(), pgbuf_get_victim_from_lru_list(), pt_check_enum_data_type(), pt_check_hint(), pt_check_type_compatibility_of_values_query(), pt_get_expression_count(), pt_get_values_query_compatible_info(), pt_mvcc_set_spec_assign_reev_extra_indexes(), pt_number_of_attributes(), pt_to_delete_xasl(), pt_to_outlist(), put_attributes(), put_object_set(), put_substructure_set(), put_varinfo(), qdata_benchmark(), qdata_get_valptr_type_list(), qdump_print_db_value_array(), qexec_analytic_group_header_next(), qexec_clear_internal_classes(), qexec_clear_topn_tuple(), qexec_create_internal_classes(), qexec_create_mvcc_reev_assignments(), qexec_setup_topn_proc(), qfile_update_domains_on_type_list(), query_info_print(), query_multi_range_opt_check_set_sort_col(), sbtree_find_multi_uniques(), scan_regu_key_to_index_key(), ses_posix_read_file(), ses_posix_write_file(), cubthread::manager::set_max_thread_count(), ssession_drop_session_variables(), ssession_set_session_variables(), cubmonitor::statistic_value_cast(), stran_server_2pc_recovery_prepared(), stx_build_list_id(), stx_build_regu_value_list(), substructure_set_size(), sysprm_pack_assign_values(), sysprm_unpack_assign_values(), cubthread::system_core_count(), tran_server_2pc_recovery_prepared(), tz_decode_tz_id(), tz_explain_tz_id(), tz_zone_info_to_str(), tzc_check_ds_ruleset(), cubpacking::unpacker::unpack_int_array(), cubpacking::unpacker::unpack_int_vector(), update_at_server(), update_objs_for_list_file(), util_parse_string_table(), util_split_string(), ux_cursor(), valcnv_convert_bit_to_string(), vasprintf(), ws_cull_mops(), ws_dump(), xbtree_find_multi_uniques(), xcache_cleanup(), xml_init_schema_tree(), and xstats_update_statistics().
int cubregex::instr (int & result, const cub_regex_object & reg, const std::string & src, const int position, const int occurrence, const int return_opt, const INTL_CODESET codeset)
Definition at line 324 of file string_regex.cpp.
References ARG_FILE_LINE, assert, cublocale::convert_to_string(), cublocale::convert_to_wstring(), ER_ERROR_SEVERITY, ER_QSTR_BAD_SRC_CODESET, ER_REGEX_EXEC_ERROR, er_set(), NO_ERROR, parse_regex_exception(), and replace().
Referenced by db_string_regexp_instr().
int cubregex::parse_match_type (std::regex_constants::syntax_option_type & reg_flags, std::string & opt_str)
Definition at line 99 of file string_regex.cpp.
References ER_QPROC_INVALID_PARAMETER, and NO_ERROR.
Referenced by db_string_regexp_count(), db_string_regexp_instr(), db_string_regexp_like(), db_string_regexp_replace(), and db_string_regexp_substr().
std::string cubregex::parse_regex_exception (std::regex_error & e)
Definition at line 46 of file string_regex.cpp.
Referenced by compile(), count(), instr(), replace(), search(), and substr().
int cubregex::replace (std::string & result, const cub_regex_object & reg, const std::string & src, const std::string & repl, const int position, const int occurrence, const INTL_CODESET codeset)
Definition at line 528 of file string_regex.cpp.
References ARG_FILE_LINE, assert, cublocale::convert_to_string(), cublocale::convert_to_wstring(), ER_ERROR_SEVERITY, ER_QSTR_BAD_SRC_CODESET, ER_REGEX_EXEC_ERROR, er_set(), NO_ERROR, and parse_regex_exception().
Referenced by db_string_regexp_replace(), and instr().
int cubregex::search (int & result, const cub_regex_object & reg, const std::string & src, const INTL_CODESET codeset)
Definition at line 216 of file string_regex.cpp.
References ARG_FILE_LINE, cublocale::convert_to_wstring(), ER_ERROR_SEVERITY, ER_QSTR_BAD_SRC_CODESET, ER_REGEX_EXEC_ERROR, er_set(), NO_ERROR, parse_regex_exception(), V_FALSE, and V_TRUE.
Referenced by db_string_regexp_like(), db_string_rlike(), mq_check_delete(), and synccoll_check().
int cubregex::substr (std::string & result, bool & is_matched, const cub_regex_object & reg, const std::string & src, const int position, const int occurrence, const INTL_CODESET codeset)
Definition at line 635 of file string_regex.cpp.
References ARG_FILE_LINE, assert, cublocale::convert_to_string(), cublocale::convert_to_wstring(), ER_ERROR_SEVERITY, ER_QSTR_BAD_SRC_CODESET, ER_REGEX_EXEC_ERROR, er_set(), NO_ERROR, and parse_regex_exception().
Referenced by db_string_regexp_substr(), pt_print_json_table(), pt_print_json_table_column_error_or_empty_behavior(), pt_print_json_table_column_info(), pt_print_json_table_node(), and statdump().