CUBRID Engine: object_print Namespace Reference
object_print Namespace Reference
Functions
void free_strarray (char **strs)
char * copy_string (const char *source)
Function Documentation
char * object_print::copy_string (const char * source)
Definition at line 61 of file object_print_util.cpp.
References NULL, and strlen.
Referenced by help_class_names(), help_trigger_names(), object_description::init(), trigger_description::init(), and class_description::init().
void object_print::free_strarray (char ** strs)
Definition at line 39 of file object_print_util.cpp.
References free_and_init, i, and NULL.
Referenced by help_free_names(), class_description::~class_description(), and object_description::~object_description().