CUBRID Engine: src/communication/network.h File Reference
network.h File Reference
#include "perf_monitor.h"
#include "locator.h"
#include "log_comm.h"
Macros
#define EXECUTE_QUERY_MAX_ARGUMENT_DATA_SIZE 512
#define NET_CAP_BACKWARD_COMPATIBLE 0x80000000
#define NET_CAP_FORWARD_COMPATIBLE 0x40000000
#define NET_CAP_INTERRUPT_ENABLED 0x00800000
#define NET_CAP_UPDATE_DISABLED 0x00008000
#define NET_CAP_REMOTE_DISABLED 0x00000080
#define NET_CAP_HA_REPL_DELAY 0x00000008
#define NET_CAP_HA_REPLICA 0x00000004
#define NET_CAP_HA_IGNORE_REPL_DELAY 0x00000002
Enumerations
enum net_server_request {
NET_SERVER_REQUEST_START = 0, NET_SERVER_PING, NET_SERVER_BO_INIT_SERVER, NET_SERVER_BO_REGISTER_CLIENT,
NET_SERVER_BO_UNREGISTER_CLIENT, NET_SERVER_BO_BACKUP, NET_SERVER_BO_ADD_VOLEXT, NET_SERVER_BO_CHECK_DBCONSISTENCY,
NET_SERVER_BO_FIND_NPERM_VOLS, NET_SERVER_BO_FIND_NTEMP_VOLS, NET_SERVER_BO_FIND_LAST_PERM, NET_SERVER_BO_FIND_LAST_TEMP,
NET_SERVER_BO_CHANGE_HA_MODE, NET_SERVER_BO_NOTIFY_HA_LOG_APPLIER_STATE, NET_SERVER_BO_COMPACT_DB, NET_SERVER_BO_HEAP_COMPACT,
NET_SERVER_BO_COMPACT_DB_START, NET_SERVER_BO_COMPACT_DB_STOP, NET_SERVER_BO_GET_LOCALES_INFO, NET_SERVER_TM_SERVER_COMMIT,
NET_SERVER_TM_SERVER_ABORT, NET_SERVER_TM_SERVER_START_TOPOP, NET_SERVER_TM_SERVER_END_TOPOP, NET_SERVER_TM_SERVER_SAVEPOINT,
NET_SERVER_TM_SERVER_PARTIAL_ABORT, NET_SERVER_TM_SERVER_HAS_UPDATED, NET_SERVER_TM_SERVER_ISACTIVE_AND_HAS_UPDATED, NET_SERVER_TM_ISBLOCKED,
NET_SERVER_TM_WAIT_SERVER_ACTIVE_TRANS, NET_SERVER_TM_SERVER_GET_GTRINFO, NET_SERVER_TM_SERVER_SET_GTRINFO, NET_SERVER_TM_SERVER_2PC_START,
NET_SERVER_TM_SERVER_2PC_PREPARE, NET_SERVER_TM_SERVER_2PC_RECOVERY_PREPARED, NET_SERVER_TM_SERVER_2PC_ATTACH_GT, NET_SERVER_TM_SERVER_2PC_PREPARE_GT,
NET_SERVER_TM_LOCAL_TRANSACTION_ID, NET_SERVER_LC_FETCH, NET_SERVER_LC_FETCHALL, NET_SERVER_LC_FETCH_LOCKSET,
NET_SERVER_LC_FETCH_ALLREFS_LOCKSET, NET_SERVER_LC_GET_CLASS, NET_SERVER_LC_FIND_CLASSOID, NET_SERVER_LC_DOESEXIST,
NET_SERVER_LC_FORCE, NET_SERVER_LC_RESERVE_CLASSNAME, NET_SERVER_LC_RESERVE_CLASSNAME_GET_OID, NET_SERVER_LC_DELETE_CLASSNAME,
NET_SERVER_LC_RENAME_CLASSNAME, NET_SERVER_LC_ASSIGN_OID, NET_SERVER_LC_NOTIFY_ISOLATION_INCONS, NET_SERVER_LC_FIND_LOCKHINT_CLASSOIDS,
NET_SERVER_LC_FETCH_LOCKHINT_CLASSES, NET_SERVER_LC_ASSIGN_OID_BATCH, NET_SERVER_LC_CHECK_FK_VALIDITY, NET_SERVER_LC_REM_CLASS_FROM_INDEX,
NET_SERVER_LC_UPGRADE_INSTANCES_DOMAIN, NET_SERVER_LC_REPL_FORCE, NET_SERVER_LC_REDISTRIBUTE_PARTITION_DATA, NET_SERVER_HEAP_CREATE,
NET_SERVER_HEAP_DESTROY, NET_SERVER_HEAP_DESTROY_WHEN_NEW, NET_SERVER_HEAP_GET_CLASS_NOBJS_AND_NPAGES, NET_SERVER_HEAP_HAS_INSTANCE,
NET_SERVER_HEAP_RECLAIM_ADDRESSES, NET_SERVER_FILE_APPLY_TDE_TO_CLASS_FILES, NET_SERVER_TDE_GET_DATA_KEYS, NET_SERVER_TDE_GET_MK_FILE_PATH,
NET_SERVER_TDE_GET_MK_INFO, NET_SERVER_TDE_CHANGE_MK_ON_SERVER, NET_SERVER_LOG_RESET_WAIT_MSECS, NET_SERVER_LOG_RESET_ISOLATION,
NET_SERVER_LOG_SET_INTERRUPT, NET_SERVER_LOG_DUMP_STAT, NET_SERVER_LOG_GETPACK_TRANTB, NET_SERVER_LOG_DUMP_TRANTB,
NET_SERVER_LOG_FIND_LOB_LOCATOR, NET_SERVER_LOG_ADD_LOB_LOCATOR, NET_SERVER_LOG_CHANGE_STATE_OF_LOCATOR, NET_SERVER_LOG_DROP_LOB_LOCATOR,
NET_SERVER_LOG_CHECKPOINT, NET_SERVER_LK_DUMP, NET_SERVER_BTREE_ADDINDEX, NET_SERVER_BTREE_DELINDEX,
NET_SERVER_BTREE_LOADINDEX, NET_SERVER_BTREE_FIND_UNIQUE, NET_SERVER_BTREE_CLASS_UNIQUE_TEST, NET_SERVER_BTREE_GET_STATISTICS,
NET_SERVER_BTREE_GET_KEY_TYPE, NET_SERVER_BTREE_FIND_MULTI_UNIQUES, NET_SERVER_DISK_TOTALPGS, NET_SERVER_DISK_FREEPGS,
NET_SERVER_DISK_REMARKS, NET_SERVER_DISK_VLABEL, NET_SERVER_QST_GET_STATISTICS, NET_SERVER_QST_UPDATE_STATISTICS,
NET_SERVER_QST_UPDATE_ALL_STATISTICS, NET_SERVER_QM_QUERY_PREPARE, NET_SERVER_QM_QUERY_EXECUTE, NET_SERVER_QM_QUERY_PREPARE_AND_EXECUTE,
NET_SERVER_QM_QUERY_END, NET_SERVER_QM_QUERY_DROP_ALL_PLANS, NET_SERVER_QM_QUERY_DUMP_PLANS, NET_SERVER_QM_QUERY_DUMP_CACHE,
NET_SERVER_LS_GET_LIST_FILE_PAGE, NET_SERVER_MNT_SERVER_START_STATS, NET_SERVER_MNT_SERVER_STOP_STATS, NET_SERVER_MNT_SERVER_COPY_STATS,
NET_SERVER_MNT_SERVER_COPY_GLOBAL_STATS, NET_SERVER_CT_CHECK_REP_DIR, NET_SERVER_CSS_KILL_TRANSACTION, NET_SERVER_CSS_DUMP_CS_STAT,
NET_SERVER_CSS_KILL_OR_INTERRUPT_TRANSACTION, NET_SERVER_QPROC_GET_SYS_TIMESTAMP, NET_SERVER_QPROC_GET_CURRENT_VALUE, NET_SERVER_QPROC_GET_NEXT_VALUE,
NET_SERVER_QPROC_GET_SERVER_INFO, NET_SERVER_SERIAL_DECACHE, NET_SERVER_JSP_GET_SERVER_PORT, NET_SERVER_PRM_SET_PARAMETERS,
NET_SERVER_PRM_GET_PARAMETERS, NET_SERVER_PRM_GET_FORCE_PARAMETERS, NET_SERVER_PRM_DUMP_PARAMETERS, NET_SERVER_REPL_INFO,
NET_SERVER_REPL_LOG_GET_APPEND_LSA, NET_SERVER_LOG_SET_SUPPRESS_REPL_ON_TRANSACTION, NET_SERVER_CHKSUM_REPL, NET_SERVER_LOGWR_GET_LOG_PAGES,
NET_SERVER_SHUTDOWN, NET_SERVER_ES_CREATE_FILE, NET_SERVER_ES_WRITE_FILE, NET_SERVER_ES_READ_FILE,
NET_SERVER_ES_DELETE_FILE, NET_SERVER_ES_COPY_FILE, NET_SERVER_ES_RENAME_FILE, NET_SERVER_ES_GET_FILE_SIZE,
NET_SERVER_SES_CHECK_SESSION, NET_SERVER_SES_END_SESSION, NET_SERVER_SES_SET_ROW_COUNT, NET_SERVER_SES_GET_ROW_COUNT,
NET_SERVER_SES_GET_LAST_INSERT_ID, NET_SERVER_SES_RESET_CUR_INSERT_ID, NET_SERVER_SES_CREATE_PREPARED_STATEMENT, NET_SERVER_SES_GET_PREPARED_STATEMENT,
NET_SERVER_SES_DELETE_PREPARED_STATEMENT, NET_SERVER_SES_SET_SESSION_VARIABLES, NET_SERVER_SES_GET_SESSION_VARIABLE, NET_SERVER_SES_DROP_SESSION_VARIABLES,
NET_SERVER_ACL_DUMP, NET_SERVER_ACL_RELOAD, NET_SERVER_AU_LOGIN_USER, NET_SERVER_AU_DOES_ACTIVE_USER_EXIST,
NET_SERVER_VACUUM, NET_SERVER_GET_MVCC_SNAPSHOT, NET_SERVER_LOCK_RR, NET_SERVER_TZ_GET_CHECKSUM,
NET_SERVER_SPACEDB, NET_SERVER_LC_DEMOTE_CLASS_LOCK, NET_SERVER_LD_INIT, NET_SERVER_LD_INSTALL_CLASS,
NET_SERVER_LD_LOAD_BATCH, NET_SERVER_LD_FETCH_STATUS, NET_SERVER_LD_DESTROY, NET_SERVER_LD_INTERRUPT,
NET_SERVER_LD_UPDATE_STATS, NET_SERVER_VACUUM_DUMP, NET_SERVER_REQUEST_END, NET_SERVER_PING_WITH_HANDSHAKE = 999
}
enum QUERY_SERVER_REQUEST {
QUERY_END = 1, METHOD_CALL, ASYNC_OBTAIN_USER_INPUT, GET_NEXT_LOG_PAGES,
END_CALLBACK, CONSOLE_OUTPUT
}
Functions
int net_server_start (const char *name)
const char * net_server_request_name (int request)
Macro Definition Documentation
#define EXECUTE_QUERY_MAX_ARGUMENT_DATA_SIZE 512
Definition at line 41 of file network.h.
Referenced by qmgr_execute_query(), and sqmgr_execute_query().
#define NET_CAP_BACKWARD_COMPATIBLE 0x80000000
Definition at line 263 of file network.h.
Referenced by check_client_capabilities(), and check_server_capabilities().
#define NET_CAP_FORWARD_COMPATIBLE 0x40000000
Definition at line 264 of file network.h.
Referenced by check_client_capabilities(), and check_server_capabilities().
#define NET_CAP_HA_IGNORE_REPL_DELAY 0x00000002
Definition at line 270 of file network.h.
Referenced by check_client_capabilities(), and client_capabilities().
#define NET_CAP_HA_REPL_DELAY 0x00000008
Definition at line 268 of file network.h.
Referenced by check_server_capabilities(), and server_capabilities().
#define NET_CAP_HA_REPLICA 0x00000004
Definition at line 269 of file network.h.
Referenced by check_server_capabilities(), and server_capabilities().
#define NET_CAP_INTERRUPT_ENABLED 0x00800000
Definition at line 265 of file network.h.
Referenced by check_client_capabilities(), check_server_capabilities(), client_capabilities(), get_capability_string(), and server_capabilities().
#define NET_CAP_REMOTE_DISABLED 0x00000080
Definition at line 267 of file network.h.
Referenced by check_client_capabilities(), check_server_capabilities(), net_client_ping_server_with_handshake(), and server_capabilities().
#define NET_CAP_UPDATE_DISABLED 0x00008000
Definition at line 266 of file network.h.
Referenced by check_server_capabilities(), client_capabilities(), get_capability_string(), and server_capabilities().
Enumeration Type Documentation
enum net_server_request
Enumerator
NET_SERVER_REQUEST_START
NET_SERVER_PING
NET_SERVER_BO_INIT_SERVER
NET_SERVER_BO_REGISTER_CLIENT
NET_SERVER_BO_UNREGISTER_CLIENT
NET_SERVER_BO_BACKUP
NET_SERVER_BO_ADD_VOLEXT
NET_SERVER_BO_CHECK_DBCONSISTENCY
NET_SERVER_BO_FIND_NPERM_VOLS
NET_SERVER_BO_FIND_NTEMP_VOLS
NET_SERVER_BO_FIND_LAST_PERM
NET_SERVER_BO_FIND_LAST_TEMP
NET_SERVER_BO_CHANGE_HA_MODE
NET_SERVER_BO_NOTIFY_HA_LOG_APPLIER_STATE
NET_SERVER_BO_COMPACT_DB
NET_SERVER_BO_HEAP_COMPACT
NET_SERVER_BO_COMPACT_DB_START
NET_SERVER_BO_COMPACT_DB_STOP
NET_SERVER_BO_GET_LOCALES_INFO
NET_SERVER_TM_SERVER_COMMIT
NET_SERVER_TM_SERVER_ABORT
NET_SERVER_TM_SERVER_START_TOPOP
NET_SERVER_TM_SERVER_END_TOPOP
NET_SERVER_TM_SERVER_SAVEPOINT
NET_SERVER_TM_SERVER_PARTIAL_ABORT
NET_SERVER_TM_SERVER_HAS_UPDATED
NET_SERVER_TM_SERVER_ISACTIVE_AND_HAS_UPDATED
NET_SERVER_TM_ISBLOCKED
NET_SERVER_TM_WAIT_SERVER_ACTIVE_TRANS
NET_SERVER_TM_SERVER_GET_GTRINFO
NET_SERVER_TM_SERVER_SET_GTRINFO
NET_SERVER_TM_SERVER_2PC_START
NET_SERVER_TM_SERVER_2PC_PREPARE
NET_SERVER_TM_SERVER_2PC_RECOVERY_PREPARED
NET_SERVER_TM_SERVER_2PC_ATTACH_GT
NET_SERVER_TM_SERVER_2PC_PREPARE_GT
NET_SERVER_TM_LOCAL_TRANSACTION_ID
NET_SERVER_LC_FETCH
NET_SERVER_LC_FETCHALL
NET_SERVER_LC_FETCH_LOCKSET
NET_SERVER_LC_FETCH_ALLREFS_LOCKSET
NET_SERVER_LC_GET_CLASS
NET_SERVER_LC_FIND_CLASSOID
NET_SERVER_LC_DOESEXIST
NET_SERVER_LC_FORCE
NET_SERVER_LC_RESERVE_CLASSNAME
NET_SERVER_LC_RESERVE_CLASSNAME_GET_OID
NET_SERVER_LC_DELETE_CLASSNAME
NET_SERVER_LC_RENAME_CLASSNAME
NET_SERVER_LC_ASSIGN_OID
NET_SERVER_LC_NOTIFY_ISOLATION_INCONS
NET_SERVER_LC_FIND_LOCKHINT_CLASSOIDS
NET_SERVER_LC_FETCH_LOCKHINT_CLASSES
NET_SERVER_LC_ASSIGN_OID_BATCH
NET_SERVER_LC_CHECK_FK_VALIDITY
NET_SERVER_LC_REM_CLASS_FROM_INDEX
NET_SERVER_LC_UPGRADE_INSTANCES_DOMAIN
NET_SERVER_LC_REPL_FORCE
NET_SERVER_LC_REDISTRIBUTE_PARTITION_DATA
NET_SERVER_HEAP_CREATE
NET_SERVER_HEAP_DESTROY
NET_SERVER_HEAP_DESTROY_WHEN_NEW
NET_SERVER_HEAP_GET_CLASS_NOBJS_AND_NPAGES
NET_SERVER_HEAP_HAS_INSTANCE
NET_SERVER_HEAP_RECLAIM_ADDRESSES
NET_SERVER_FILE_APPLY_TDE_TO_CLASS_FILES
NET_SERVER_TDE_GET_DATA_KEYS
NET_SERVER_TDE_GET_MK_FILE_PATH
NET_SERVER_TDE_GET_MK_INFO
NET_SERVER_TDE_CHANGE_MK_ON_SERVER
NET_SERVER_LOG_RESET_WAIT_MSECS
NET_SERVER_LOG_RESET_ISOLATION
NET_SERVER_LOG_SET_INTERRUPT
NET_SERVER_LOG_DUMP_STAT
NET_SERVER_LOG_GETPACK_TRANTB
NET_SERVER_LOG_DUMP_TRANTB
NET_SERVER_LOG_FIND_LOB_LOCATOR
NET_SERVER_LOG_ADD_LOB_LOCATOR
NET_SERVER_LOG_CHANGE_STATE_OF_LOCATOR
NET_SERVER_LOG_DROP_LOB_LOCATOR
NET_SERVER_LOG_CHECKPOINT
NET_SERVER_LK_DUMP
NET_SERVER_BTREE_ADDINDEX
NET_SERVER_BTREE_DELINDEX
NET_SERVER_BTREE_LOADINDEX
NET_SERVER_BTREE_FIND_UNIQUE
NET_SERVER_BTREE_CLASS_UNIQUE_TEST
NET_SERVER_BTREE_GET_STATISTICS
NET_SERVER_BTREE_GET_KEY_TYPE
NET_SERVER_BTREE_FIND_MULTI_UNIQUES
NET_SERVER_DISK_TOTALPGS
NET_SERVER_DISK_FREEPGS
NET_SERVER_DISK_REMARKS
NET_SERVER_DISK_VLABEL
NET_SERVER_QST_GET_STATISTICS
NET_SERVER_QST_UPDATE_STATISTICS
NET_SERVER_QST_UPDATE_ALL_STATISTICS
NET_SERVER_QM_QUERY_PREPARE
NET_SERVER_QM_QUERY_EXECUTE
NET_SERVER_QM_QUERY_PREPARE_AND_EXECUTE
NET_SERVER_QM_QUERY_END
NET_SERVER_QM_QUERY_DROP_ALL_PLANS
NET_SERVER_QM_QUERY_DUMP_PLANS
NET_SERVER_QM_QUERY_DUMP_CACHE
NET_SERVER_LS_GET_LIST_FILE_PAGE
NET_SERVER_MNT_SERVER_START_STATS
NET_SERVER_MNT_SERVER_STOP_STATS
NET_SERVER_MNT_SERVER_COPY_STATS
NET_SERVER_MNT_SERVER_COPY_GLOBAL_STATS
NET_SERVER_CT_CHECK_REP_DIR
NET_SERVER_CSS_KILL_TRANSACTION
NET_SERVER_CSS_DUMP_CS_STAT
NET_SERVER_CSS_KILL_OR_INTERRUPT_TRANSACTION
NET_SERVER_QPROC_GET_SYS_TIMESTAMP
NET_SERVER_QPROC_GET_CURRENT_VALUE
NET_SERVER_QPROC_GET_NEXT_VALUE
NET_SERVER_QPROC_GET_SERVER_INFO
NET_SERVER_SERIAL_DECACHE
NET_SERVER_JSP_GET_SERVER_PORT
NET_SERVER_PRM_SET_PARAMETERS
NET_SERVER_PRM_GET_PARAMETERS
NET_SERVER_PRM_GET_FORCE_PARAMETERS
NET_SERVER_PRM_DUMP_PARAMETERS
NET_SERVER_REPL_INFO
NET_SERVER_REPL_LOG_GET_APPEND_LSA
NET_SERVER_LOG_SET_SUPPRESS_REPL_ON_TRANSACTION
NET_SERVER_CHKSUM_REPL
NET_SERVER_LOGWR_GET_LOG_PAGES
NET_SERVER_SHUTDOWN
NET_SERVER_ES_CREATE_FILE
NET_SERVER_ES_WRITE_FILE
NET_SERVER_ES_READ_FILE
NET_SERVER_ES_DELETE_FILE
NET_SERVER_ES_COPY_FILE
NET_SERVER_ES_RENAME_FILE
NET_SERVER_ES_GET_FILE_SIZE
NET_SERVER_SES_CHECK_SESSION
NET_SERVER_SES_END_SESSION
NET_SERVER_SES_SET_ROW_COUNT
NET_SERVER_SES_GET_ROW_COUNT
NET_SERVER_SES_GET_LAST_INSERT_ID
NET_SERVER_SES_RESET_CUR_INSERT_ID
NET_SERVER_SES_CREATE_PREPARED_STATEMENT
NET_SERVER_SES_GET_PREPARED_STATEMENT
NET_SERVER_SES_DELETE_PREPARED_STATEMENT
NET_SERVER_SES_SET_SESSION_VARIABLES
NET_SERVER_SES_GET_SESSION_VARIABLE
NET_SERVER_SES_DROP_SESSION_VARIABLES
NET_SERVER_ACL_DUMP
NET_SERVER_ACL_RELOAD
NET_SERVER_AU_LOGIN_USER
NET_SERVER_AU_DOES_ACTIVE_USER_EXIST
NET_SERVER_VACUUM
NET_SERVER_GET_MVCC_SNAPSHOT
NET_SERVER_LOCK_RR
NET_SERVER_TZ_GET_CHECKSUM
NET_SERVER_SPACEDB
NET_SERVER_LC_DEMOTE_CLASS_LOCK
NET_SERVER_LD_INIT
NET_SERVER_LD_INSTALL_CLASS
NET_SERVER_LD_LOAD_BATCH
NET_SERVER_LD_FETCH_STATUS
NET_SERVER_LD_DESTROY
NET_SERVER_LD_INTERRUPT
NET_SERVER_LD_UPDATE_STATS
NET_SERVER_VACUUM_DUMP
NET_SERVER_REQUEST_END
NET_SERVER_PING_WITH_HANDSHAKE
Definition at line 44 of file network.h.
enum QUERY_SERVER_REQUEST
Enumerator
QUERY_END
METHOD_CALL
ASYNC_OBTAIN_USER_INPUT
GET_NEXT_LOG_PAGES
END_CALLBACK
CONSOLE_OUTPUT
Definition at line 272 of file network.h.
Function Documentation
const char* net_server_request_name (int request)
Definition at line 1441 of file network_sr.c.
References net_request::name, net_Requests, NET_SERVER_PING_WITH_HANDSHAKE, NET_SERVER_REQUEST_END, and NET_SERVER_REQUEST_START.
Referenced by showstmt_array_end_scan().
int net_server_start (const char * name)
Definition at line 1292 of file network_sr.c.
References ARG_FILE_LINE, assert, boot_restart_server(), csect_finalize_static_critical_sections(), csect_initialize_static_critical_sections(), css_final_conn_list(), css_free_user_access_status(), css_init(), css_initialize_server_interfaces(), css_pack_server_name(), css_windows_shutdown(), css_windows_startup(), ER_ALL_FINAL, er_errid(), ER_ERROR_SEVERITY, er_final(), er_init(), er_msg(), ER_NET_NO_MASTER, ER_NEVER_EXIT, er_set(), ER_THREAD_FINAL, error(), cubthread::internal_tasks_worker_pool::finalize(), cubthread::finalize(), free_and_init, cubthread::internal_tasks_worker_pool::initialize(), cubthread::initialize(), msgcat_init(), net_server_conn_down(), net_server_init(), NO_ERROR, NULL, PRINT_AND_LOG_ERR_MSG, prm_get_integer_value(), PRM_ID_ER_EXIT_ASK, PRM_ID_TCP_PORT_ID, sync_finalize_sync_stats(), sync_initialize_sync_stats(), SYSPRM_LOAD_ALL, sysprm_load_and_init(), sysprm_set_er_log_file(), thread_get_thread_entry_info(), tz_load(), and xboot_shutdown_server().
Referenced by main().