CUBRID Engine: src/communication/network_interface_sr.c File Reference
network_interface_sr.c File Reference
#include "config.h"
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include "porting.h"
#include "porting_inline.hpp"
#include "perf_monitor.h"
#include "memory_alloc.h"
#include "storage_common.h"
#include "xserver_interface.h"
#include "statistics_sr.h"
#include "btree_load.h"
#include "log_impl.h"
#include "log_lsa.hpp"
#include "boot_sr.h"
#include "locator_sr.h"
#include "server_interface.h"
#include "oid.h"
#include "error_manager.h"
#include "object_representation.h"
#include "network.h"
#include "log_comm.h"
#include "network_interface_sr.h"
#include "page_buffer.h"
#include "file_manager.h"
#include "arithmetic.h"
#include "serial.h"
#include "query_manager.h"
#include "transaction_sr.h"
#include "release_string.h"
#include "critical_section.h"
#include "statistics.h"
#include "chartype.h"
#include "heap_file.h"
#include "jsp_sr.h"
#include "replication.h"
#include "server_support.h"
#include "connection_sr.h"
#include "log_writer.h"
#include "databases_file.h"
#include "es.h"
#include "es_posix.h"
#include "event_log.h"
#include "tsc_timer.h"
#include "vacuum.h"
#include "object_primitive.h"
#include "tz_support.h"
#include "dbtype.h"
#include "thread_manager.hpp"
#include "compile_context.h"
#include "load_session.hpp"
#include "session.h"
#include "xasl.h"
#include "xasl_cache.h"
#include "elo.h"
#include "transaction_transient.hpp"
Macros
#define NET_COPY_AREA_SENDRECV_SIZE (OR_INT_SIZE * 3)
#define NET_SENDRECV_BUFFSIZE (OR_INT_SIZE)
#define STATDUMP_BUF_SIZE (2 * 16 * 1024)
#define QUERY_INFO_BUF_SIZE (2048 + STATDUMP_BUF_SIZE)
#define NET_DEFER_END_QUERIES_MAX 10
#define QEWC_SAFE_GUARD_SIZE 1024
#define QEWC_MAX_DATA_SIZE (DB_PAGESIZE - QEWC_SAFE_GUARD_SIZE)
Functions
STATIC_INLINE TRAN_STATE stran_server_commit_internal (THREAD_ENTRY *thread_p, unsigned int rid, bool retain_lock, bool *should_conn_reset) __attribute__((ALWAYS_INLINE))
STATIC_INLINE TRAN_STATE stran_server_abort_internal (THREAD_ENTRY *thread_p, unsigned int rid, bool retain_lock, bool *should_conn_reset) __attribute__((ALWAYS_INLINE))
STATIC_INLINE void stran_server_auto_commit_or_abort (THREAD_ENTRY *thread_p, unsigned int rid, QUERY_ID *p_end_queries, int n_query_ids, bool need_abort, bool has_updated, bool *end_query_allowed, TRAN_STATE *tran_state, bool *should_conn_reset) __attribute__((ALWAYS_INLINE))
STATIC_INLINE int stran_can_end_after_query_execution (THREAD_ENTRY *thread_p, int query_flag, QFILE_LIST_ID *list_id, bool *can_end_transaction) __attribute__((ALWAYS_INLINE))
static bool need_to_abort_tran (THREAD_ENTRY *thread_p, int *errid)
static int server_capabilities (void)
static int check_client_capabilities (THREAD_ENTRY *thread_p, int client_cap, int rel_compare, REL_COMPATIBILITY *compatibility, const char *client_host)
static void sbtree_find_unique_internal (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
static int er_log_slow_query (THREAD_ENTRY *thread_p, EXECUTION_INFO *info, int time, UINT64 *diff_stats, char *queryinfo_string)
static void event_log_slow_query (THREAD_ENTRY *thread_p, EXECUTION_INFO *info, int time, UINT64 *diff_stats)
static void event_log_many_ioreads (THREAD_ENTRY *thread_p, EXECUTION_INFO *info, int time, UINT64 *diff_stats)
static void event_log_temp_expand_pages (THREAD_ENTRY *thread_p, EXECUTION_INFO *info)
STATIC_INLINE TRAN_STATE stran_server_abort_internal (THREAD_ENTRY *thread_p, unsigned int rid, bool *should_conn_reset)
TRAN_STATE return_error_to_client (THREAD_ENTRY *thread_p, unsigned int rid)
void server_ping (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
int server_ping_with_handshake (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slocator_fetch (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slocator_get_class (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slocator_fetch_all (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slocator_does_exist (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slocator_notify_isolation_incons (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slocator_repl_force (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slocator_force (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slocator_fetch_lockset (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slocator_fetch_all_reference_lockset (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slocator_find_class_oid (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slocator_reserve_classnames (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slocator_get_reserved_class_name_oid (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slocator_delete_class_name (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slocator_rename_class_name (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slocator_assign_oid (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sqst_server_get_statistics (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slog_checkpoint (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slogtb_set_interrupt (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slogtb_set_suppress_repl_on_transaction (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slogtb_reset_wait_msecs (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slogtb_reset_isolation (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slogpb_dump_stat (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slog_find_lob_locator (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slog_add_lob_locator (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slog_change_state_of_locator (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slog_drop_lob_locator (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sacl_reload (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sacl_dump (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slock_dump (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void shf_create (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void shf_destroy (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void shf_destroy_when_new (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void shf_heap_reclaim_addresses (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sfile_apply_tde_to_class_files (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void stde_get_data_keys (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void stde_get_mk_file_path (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void stde_get_mk_info (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void stde_change_mk_on_server (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void stran_server_commit (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void stran_server_abort (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void stran_server_has_updated (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void stran_server_start_topop (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void stran_server_end_topop (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void stran_server_savepoint (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void stran_server_partial_abort (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void stran_server_is_active_and_has_updated (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void stran_wait_server_active_trans (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void stran_is_blocked (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void stran_server_set_global_tran_info (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void stran_server_get_global_tran_info (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void stran_server_2pc_start (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void stran_server_2pc_prepare (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void stran_server_2pc_recovery_prepared (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void stran_server_2pc_attach_global_tran (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void stran_server_2pc_prepare_global_tran (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void stran_lock_rep_read (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sboot_initialize_server (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sboot_register_client (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sboot_notify_unregister_client (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sboot_backup (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sboot_add_volume_extension (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sboot_check_db_consistency (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sboot_find_number_permanent_volumes (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sboot_find_number_temp_volumes (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sboot_find_last_permanent (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sboot_find_last_temp (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sboot_change_ha_mode (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sboot_notify_ha_log_applier_state (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sqst_update_statistics (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sqst_update_all_statistics (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sbtree_add_index (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sbtree_load_index (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sbtree_delete_index (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slocator_remove_class_from_index (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sbtree_find_unique (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sbtree_find_multi_uniques (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sbtree_class_test_unique (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sdk_totalpgs (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sdk_freepgs (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sdk_remarks (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sdk_vlabel (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sqfile_get_list_file_page (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sqmgr_prepare_query (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sqmgr_execute_query (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sqmgr_prepare_and_execute_query (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sqmgr_end_query (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sqmgr_drop_all_query_plans (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sqmgr_dump_query_plans (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sqmgr_dump_query_cache (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sqp_get_sys_timestamp (THREAD_ENTRY *thread_p, unsigned int rid, char *request_ignore, int reqlen_ignore)
void sserial_get_current_value (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sserial_get_next_value (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sserial_decache (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void smnt_server_start_stats (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void smnt_server_stop_stats (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void smnt_server_copy_stats (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void smnt_server_copy_global_stats (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sct_check_rep_dir (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
int xs_send_method_call_info_to_client (THREAD_ENTRY *thread_p, qfile_list_id *list_id, method_sig_list *methsg_list)
int xs_receive_data_from_client (THREAD_ENTRY *thread_p, char **area, int *datasize)
int xs_receive_data_from_client_with_timeout (THREAD_ENTRY *thread_p, char **area, int *datasize, int timeout)
int xs_send_action_to_client (THREAD_ENTRY *thread_p, VACOMM_BUFFER_CLIENT_ACTION action)
void slocator_assign_oid_batch (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slocator_find_lockhint_class_oids (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slocator_fetch_lockhint_classes (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sthread_kill_tran_index (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sthread_kill_or_interrupt_tran (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sthread_dump_cs_stat (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slogtb_get_pack_tran_table (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slogtb_dump_trantable (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
int xcallback_console_print (THREAD_ENTRY *thread_p, char *print_str)
int xio_send_user_prompt_to_client (THREAD_ENTRY *thread_p, FILEIO_REMOTE_PROMPT_TYPE prompt_id, const char *prompt, const char *failure_prompt, int range_low, int range_high, const char *secondary_prompt, int reprompt_value)
int xlog_send_log_pages_to_client (THREAD_ENTRY *thread_p, char *logpg_area, int area_size, LOGWR_MODE mode)
int xlog_get_page_request_with_reply (THREAD_ENTRY *thread_p, LOG_PAGEID *fpageid_ptr, LOGWR_MODE *mode_ptr, int timeout)
void shf_get_class_num_objs_and_pages (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sbtree_get_statistics (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sbtree_get_key_type (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sqp_get_server_info (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sprm_server_change_parameters (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sprm_server_get_force_parameters (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sprm_server_obtain_parameters (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sprm_server_dump_parameters (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void shf_has_instance (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void stran_get_local_transaction_id (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sjsp_get_server_port (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void srepl_set_info (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void srepl_log_get_append_lsa (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slocator_check_fk_validity (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slogwr_get_log_pages (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sboot_compact_db (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sboot_heap_compact (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sboot_compact_start (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sboot_compact_stop (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void ses_posix_create_file (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void ses_posix_write_file (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void ses_posix_read_file (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void ses_posix_delete_file (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void ses_posix_copy_file (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void ses_posix_rename_file (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void ses_posix_get_file_size (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slocator_upgrade_instances_domain (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void ssession_find_or_create_session (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void ssession_end_session (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void ssession_set_row_count (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void ssession_get_row_count (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void ssession_get_last_insert_id (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void ssession_reset_cur_insert_id (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void ssession_create_prepared_statement (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void ssession_get_prepared_statement (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void ssession_delete_prepared_statement (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slogin_user (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void ssession_set_session_variables (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void ssession_get_session_variable (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void svacuum (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void svacuum_dump (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slogtb_get_mvcc_snapshot (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void ssession_drop_session_variables (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sboot_get_locales_info (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sboot_get_timezone_checksum (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void schksum_insert_repl_log_and_demote_table_lock (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slogtb_does_active_user_exist (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slocator_redistribute_partition_data (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void netsr_spacedb (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void slocator_demote_class_lock (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sloaddb_init (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sloaddb_install_class (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sloaddb_load_batch (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sloaddb_fetch_status (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sloaddb_destroy (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sloaddb_interrupt (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void sloaddb_update_stats (THREAD_ENTRY *thread_p, unsigned int rid, char *request, int reqlen)
void ssession_stop_attached_threads (void *session)
Variables
unsigned int db_on_server = 1
Macro Definition Documentation
#define NET_COPY_AREA_SENDRECV_SIZE (OR_INT_SIZE * 3)
Definition at line 91 of file network_interface_sr.c.
Referenced by slocator_does_exist(), slocator_fetch(), slocator_fetch_all(), slocator_fetch_all_reference_lockset(), slocator_fetch_lockhint_classes(), slocator_fetch_lockset(), slocator_find_lockhint_class_oids(), slocator_get_class(), slocator_notify_isolation_incons(), and slocator_repl_force().
#define NET_DEFER_END_QUERIES_MAX 10
Definition at line 97 of file network_interface_sr.c.
Referenced by qmgr_end_query(), qmgr_execute_query(), sqmgr_execute_query(), and tran_server_commit().
#define NET_SENDRECV_BUFFSIZE (OR_INT_SIZE)
Definition at line 92 of file network_interface_sr.c.
Referenced by slocator_fetch_all_reference_lockset(), slocator_fetch_lockhint_classes(), slocator_fetch_lockset(), and slocator_find_lockhint_class_oids().
#define QEWC_MAX_DATA_SIZE (DB_PAGESIZE - QEWC_SAFE_GUARD_SIZE)
Definition at line 102 of file network_interface_sr.c.
Referenced by stran_can_end_after_query_execution().
#define QEWC_SAFE_GUARD_SIZE 1024
Definition at line 100 of file network_interface_sr.c.
#define QUERY_INFO_BUF_SIZE (2048 + STATDUMP_BUF_SIZE)
Definition at line 95 of file network_interface_sr.c.
Referenced by er_log_slow_query(), and sqmgr_execute_query().
#define STATDUMP_BUF_SIZE (2 * 16 * 1024)
Definition at line 94 of file network_interface_sr.c.
Referenced by er_log_slow_query().
Function Documentation
static int check_client_capabilities (THREAD_ENTRY * thread_p, int client_cap, int rel_compare, REL_COMPATIBILITY * compatibility, const char * client_host) static
Definition at line 450 of file network_interface_sr.c.
References ARG_FILE_LINE, assert, boot_Host_name, er_log_debug, NET_CAP_BACKWARD_COMPATIBLE, NET_CAP_FORWARD_COMPATIBLE, NET_CAP_HA_IGNORE_REPL_DELAY, NET_CAP_INTERRUPT_ENABLED, NET_CAP_REMOTE_DISABLED, NULL, REL_BACKWARD_COMPATIBLE, REL_FORWARD_COMPATIBLE, REL_NOT_COMPATIBLE, and server_capabilities().
Referenced by server_ping_with_handshake().
static int er_log_slow_query (THREAD_ENTRY * thread_p, EXECUTION_INFO * info, int time, UINT64 * diff_stats, char * queryinfo_string) static
Definition at line 5374 of file network_interface_sr.c.
References ARG_FILE_LINE, ER_NOTIFICATION_SEVERITY, er_set(), ER_SLOW_QUERY, NO_ERROR, NULL, perfmon_server_dump_stats_to_buffer(), prm_get_bool_value(), PRM_ID_SQL_TRACE_EXECUTION_PLAN, qmgr_get_sql_id(), QUERY_INFO_BUF_SIZE, execution_info::sql_hash_text, execution_info::sql_plan_text, execution_info::sql_user_text, STATDUMP_BUF_SIZE, and strlen.
Referenced by sqmgr_execute_query().
static void event_log_many_ioreads (THREAD_ENTRY * thread_p, EXECUTION_INFO * info, int time, UINT64 * diff_stats) static
Definition at line 5479 of file network_interface_sr.c.
References event_log_bind_values(), event_log_end(), event_log_print_client_info(), event_log_start(), LOG_FIND_TDES(), LOG_FIND_THREAD_TRAN_INDEX, log_fp, MAX_NUM_EXEC_QUERY_HISTORY, NULL, log_tdes::num_exec_queries, pstat_Metadata, PSTAT_PB_NUM_IOREADS, and execution_info::sql_hash_text.
Referenced by sqmgr_execute_query().
static void event_log_slow_query (THREAD_ENTRY * thread_p, EXECUTION_INFO * info, int time, UINT64 * diff_stats) static
Definition at line 5433 of file network_interface_sr.c.
References event_log_bind_values(), event_log_end(), event_log_print_client_info(), event_log_start(), LOG_FIND_TDES(), LOG_FIND_THREAD_TRAN_INDEX, log_fp, MAX_NUM_EXEC_QUERY_HISTORY, NULL, log_tdes::num_exec_queries, pstat_Metadata, PSTAT_PB_NUM_FETCHES, PSTAT_PB_NUM_IOREADS, PSTAT_PB_NUM_IOWRITES, execution_info::sql_hash_text, and TO_MSEC.
Referenced by sqmgr_execute_query().
static void event_log_temp_expand_pages (THREAD_ENTRY * thread_p, EXECUTION_INFO * info) static
Definition at line 5519 of file network_interface_sr.c.
References event_log_bind_values(), event_log_end(), event_log_print_client_info(), event_log_start(), LOG_FIND_TDES(), LOG_FIND_THREAD_TRAN_INDEX, log_fp, MAX_NUM_EXEC_QUERY_HISTORY, NULL, log_tdes::num_exec_queries, execution_info::sql_hash_text, and TO_MSEC.
Referenced by sqmgr_execute_query().
static bool need_to_abort_tran (THREAD_ENTRY * thread_p, int * errid) static
Definition at line 302 of file network_interface_sr.c.
References ARG_FILE_LINE, assert, log_tdes::client, ER_DB_NO_MODIFICATIONS, er_errid(), ER_ERROR_SEVERITY, ER_LK_UNILATERALLY_ABORTED, er_set(), clientids::get_db_user(), clientids::get_host_name(), LOG_FIND_CURRENT_TDES(), NO_ERROR, NULL, clientids::process_id, log_tdes::tran_abort_reason, and TRAN_NORMAL.
Referenced by return_error_to_client(), and sqmgr_execute_query().
void netsr_spacedb (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 9876 of file network_interface_sr.c.
References assert, ASSERT_ERROR, css_send_reply_and_data_to_client(), db_private_alloc, db_private_free_and_init, disk_spacedb(), file_spacedb(), free_and_init, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_pack_spacedb(), or_packed_spacedb_size(), or_unpack_int(), return_error_to_client(), SPACEDB_ALL_COUNT, and SPACEDB_FILE_COUNT.
Referenced by net_server_init().
TRAN_STATE return_error_to_client (THREAD_ENTRY * thread_p, unsigned int rid)
Definition at line 347 of file network_interface_sr.c.
References assert, css_send_error_to_client(), css_conn_entry::db_error, ER_DB_NO_MODIFICATIONS, er_get_area_error(), er_stack_pop(), er_stack_push(), LOG_FIND_CURRENT_TDES(), need_to_abort_tran(), NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_START, css_conn_entry::reset_on_commit, log_tdes::state, log_tdes::tran_abort_reason, TRAN_NORMAL, tran_server_unilaterally_abort_tran(), and TRAN_UNACTIVE_UNKNOWN.
Referenced by net_server_request(), netsr_spacedb(), sacl_reload(), sboot_add_volume_extension(), sboot_backup(), sboot_change_ha_mode(), sboot_check_db_consistency(), sboot_compact_db(), sboot_compact_start(), sboot_compact_stop(), sboot_get_locales_info(), sboot_get_timezone_checksum(), sboot_heap_compact(), sboot_notify_ha_log_applier_state(), sboot_register_client(), sbtree_add_index(), sbtree_class_test_unique(), sbtree_delete_index(), sbtree_find_multi_uniques(), sbtree_find_unique_internal(), sbtree_get_key_type(), sbtree_get_statistics(), sbtree_load_index(), sct_check_rep_dir(), sdk_freepgs(), sdk_remarks(), sdk_totalpgs(), sdk_vlabel(), server_ping_with_handshake(), ses_posix_copy_file(), ses_posix_create_file(), ses_posix_delete_file(), ses_posix_get_file_size(), ses_posix_read_file(), ses_posix_rename_file(), ses_posix_write_file(), sfile_apply_tde_to_class_files(), shf_create(), shf_destroy(), shf_destroy_when_new(), shf_get_class_num_objs_and_pages(), shf_has_instance(), shf_heap_reclaim_addresses(), sloaddb_destroy(), sloaddb_fetch_status(), sloaddb_install_class(), sloaddb_load_batch(), sloaddb_update_stats(), slocator_assign_oid(), slocator_assign_oid_batch(), slocator_check_fk_validity(), slocator_delete_class_name(), slocator_demote_class_lock(), slocator_does_exist(), slocator_fetch(), slocator_fetch_all(), slocator_fetch_all_reference_lockset(), slocator_fetch_lockhint_classes(), slocator_fetch_lockset(), slocator_find_class_oid(), slocator_find_lockhint_class_oids(), slocator_force(), slocator_get_class(), slocator_get_reserved_class_name_oid(), slocator_notify_isolation_incons(), slocator_redistribute_partition_data(), slocator_remove_class_from_index(), slocator_rename_class_name(), slocator_repl_force(), slocator_reserve_classnames(), slocator_upgrade_instances_domain(), slog_add_lob_locator(), slog_change_state_of_locator(), slog_drop_lob_locator(), slogin_user(), slogtb_get_mvcc_snapshot(), slogtb_reset_isolation(), slogwr_get_log_pages(), sprm_server_get_force_parameters(), sqfile_get_list_file_page(), sqmgr_drop_all_query_plans(), sqmgr_end_query(), sqmgr_execute_query(), sqmgr_prepare_and_execute_query(), sqmgr_prepare_query(), sqp_get_server_info(), sqst_server_get_statistics(), sqst_update_all_statistics(), sqst_update_statistics(), sserial_get_current_value(), sserial_get_next_value(), ssession_create_prepared_statement(), ssession_delete_prepared_statement(), ssession_drop_session_variables(), ssession_find_or_create_session(), ssession_get_last_insert_id(), ssession_get_prepared_statement(), ssession_get_row_count(), ssession_get_session_variable(), ssession_reset_cur_insert_id(), ssession_set_row_count(), ssession_set_session_variables(), stde_change_mk_on_server(), stde_get_data_keys(), stde_get_mk_file_path(), stde_get_mk_info(), sthread_kill_or_interrupt_tran(), sthread_kill_tran_index(), stran_lock_rep_read(), stran_server_2pc_attach_global_tran(), stran_server_2pc_prepare(), stran_server_2pc_prepare_global_tran(), stran_server_2pc_recovery_prepared(), stran_server_2pc_start(), stran_server_abort_internal(), stran_server_auto_commit_or_abort(), stran_server_commit_internal(), stran_server_get_global_tran_info(), stran_server_partial_abort(), stran_server_savepoint(), stran_server_set_global_tran_info(), stran_server_start_topop(), and svacuum().
void sacl_dump (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 2217 of file network_interface_sr.c.
References ARG_FILE_LINE, css_send_abort_to_client(), css_send_data_to_client(), db_private_alloc, db_private_free_and_init, ER_ERROR_SEVERITY, ER_GENERIC_ERROR, er_set_with_oserror(), NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), and xacl_dump().
Referenced by net_server_init().
void sacl_reload (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 2189 of file network_interface_sr.c.
References css_send_data_to_client(), error(), NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_errcode(), return_error_to_client(), and xacl_reload().
Referenced by net_server_init().
void sboot_add_volume_extension (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 3545 of file network_interface_sr.c.
References bool, dbdef_vol_ext_info::comments, css_send_data_to_client(), dbdef_vol_ext_info::max_npages, dbdef_vol_ext_info::max_writesize_in_sec, dbdef_vol_ext_info::name, NULL_VOLID, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), or_unpack_string_nocopy(), dbdef_vol_ext_info::overwrite, dbdef_vol_ext_info::path, dbdef_vol_ext_info::purpose, return_error_to_client(), and xboot_add_volume_extension().
Referenced by net_server_init().
void sboot_backup (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 3485 of file network_interface_sr.c.
References css_send_data_to_client(), END_CALLBACK, NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), or_unpack_string_nocopy(), return_error_to_client(), success(), and xboot_backup().
Referenced by net_server_init().
void sboot_change_ha_mode (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 3743 of file network_interface_sr.c.
References ARG_FILE_LINE, boot_db_name(), cfg_find_db(), cfg_free_directory(), css_change_ha_server_state(), css_ha_server_state(), css_send_data_to_client(), css_set_ha_num_of_hosts(), ER_ERROR_SEVERITY, er_set(), ERR_CSS_ERROR_FROM_SERVER, HA_SERVER_STATE_DEAD, HA_SERVER_STATE_IDLE, NO_ERROR, NULL, database_info::num_hosts, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), and return_error_to_client().
Referenced by net_server_init().
void sboot_check_db_consistency (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 3591 of file network_interface_sr.c.
References CHECKDB_ALL_CHECK_EXCEPT_PREV_LINK, css_send_data_to_client(), END_CALLBACK, ER_FAILED, free_and_init, i, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_btid(), or_unpack_int(), or_unpack_oid(), return_error_to_client(), success(), and xboot_check_db_consistency().
Referenced by net_server_init().
void sboot_compact_db (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 8034 of file network_interface_sr.c.
References boot_compact_stop(), css_send_abort_to_client(), css_send_data_to_client(), db_private_alloc, db_private_free_and_init, failed_objects, i, NO_ERROR, NULL, OR_INT_SIZE, OR_OID_SIZE, or_pack_int(), or_pack_oid(), or_unpack_int(), or_unpack_int_array(), or_unpack_oid(), or_unpack_oid_array(), return_error_to_client(), success(), total_objects, and xboot_compact_db().
Referenced by net_server_init().
void sboot_compact_start (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 8259 of file network_interface_sr.c.
References css_send_data_to_client(), NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), return_error_to_client(), success(), and xboot_compact_start().
Referenced by net_server_init().
void sboot_compact_stop (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 8288 of file network_interface_sr.c.
References css_send_data_to_client(), NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), return_error_to_client(), success(), and xboot_compact_stop().
Referenced by net_server_init().
void sboot_find_last_permanent (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 3703 of file network_interface_sr.c.
References css_send_data_to_client(), OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), and xboot_find_last_permanent().
Referenced by net_server_init().
void sboot_find_last_temp (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 3727 of file network_interface_sr.c.
References css_send_data_to_client(), OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), and xboot_find_last_temp().
Referenced by net_server_init().
void sboot_find_number_permanent_volumes (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 3655 of file network_interface_sr.c.
References css_send_data_to_client(), OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), and xboot_find_number_permanent_volumes().
Referenced by net_server_init().
void sboot_find_number_temp_volumes (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 3679 of file network_interface_sr.c.
References css_send_data_to_client(), OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), and xboot_find_number_temp_volumes().
Referenced by net_server_init().
void sboot_get_locales_info (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 9549 of file network_interface_sr.c.
References ARG_FILE_LINE, assert, lang_locale_data::checksum, coll_data::checksum, lang_collation::codeset, lang_locale_data::codeset, lang_collation::coll, coll_data::coll_id, coll_data::coll_name, css_send_reply_and_data_to_client(), ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), err, free_and_init, i, LANG_COLL_DEFAULT, lang_collation_count(), lang_get_collation(), lang_get_first_locale_for_lang(), lang_locales_count(), LANG_MAX_COLLATIONS, lang_locale_data::lang_name, lang_locale_data::next_lld, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_pack_string_with_length(), or_packed_string_length(), return_error_to_client(), and strlen.
Referenced by net_server_init().
void sboot_get_timezone_checksum (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 9685 of file network_interface_sr.c.
References ARG_FILE_LINE, assert, tz_data::checksum, css_send_reply_and_data_to_client(), ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), err, free_and_init, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_pack_string_with_length(), or_packed_string_length(), return_error_to_client(), strlen, and tz_get_data().
Referenced by net_server_init().
void sboot_heap_compact (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 8218 of file network_interface_sr.c.
References boot_compact_stop(), css_send_data_to_client(), NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_oid(), return_error_to_client(), success(), and xboot_heap_compact().
Referenced by net_server_init().
void sboot_initialize_server (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 3322 of file network_interface_sr.c.
References css_send_abort_to_client().
Referenced by net_server_init().
void sboot_notify_ha_log_applier_state (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 3785 of file network_interface_sr.c.
References ARG_FILE_LINE, css_notify_ha_log_applier_state(), css_send_data_to_client(), ER_ERROR_SEVERITY, ER_FAILED, er_set(), ERR_CSS_ERROR_FROM_SERVER, HA_LOG_APPLIER_STATE_ERROR, HA_LOG_APPLIER_STATE_UNREGISTERED, i, NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), and return_error_to_client().
Referenced by net_server_init().
void sboot_notify_unregister_client (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 3432 of file network_interface_sr.c.
References assert, css_send_data_to_client(), NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), rmutex_lock, rmutex_unlock, success(), and thread_get_thread_entry_info().
Referenced by net_server_init().
void sboot_register_client (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 3339 of file network_interface_sr.c.
References css_send_reply_and_data_to_client(), boot_server_credential::db_charset, boot_server_credential::db_full_name, boot_server_credential::db_lang, db_private_alloc, db_private_free_and_init, boot_server_credential::disk_compatibility, boot_server_credential::ha_server_state, boot_server_credential::host_name, boot_server_credential::lob_path, boot_server_credential::log_page_size, NULL, NULL_TRAN_INDEX, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_FLOAT_SIZE, OR_HFID_SIZE, OR_INT_SIZE, OR_OID_SIZE, or_pack_float(), or_pack_hfid(), or_pack_int(), or_pack_oid(), or_pack_string_with_length(), or_packed_string_length(), boot_server_credential::page_size, boot_server_credential::process_id, return_error_to_client(), boot_server_credential::root_class_hfid, boot_server_credential::root_class_oid, cubpacking::unpacker::set_buffer(), cubpacking::unpacker::unpack_all(), and xboot_register_client().
Referenced by net_server_init().
void sbtree_add_index (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 3889 of file network_interface_sr.c.
References css_send_data_to_client(), er_errid(), NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_BTID_ALIGNED_SIZE, OR_INT_SIZE, or_pack_btid(), or_pack_int(), or_unpack_btid(), or_unpack_domain(), or_unpack_int(), or_unpack_oid(), return_error_to_client(), and xbtree_add_index().
Referenced by net_server_init().
void sbtree_class_test_unique (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 4386 of file network_interface_sr.c.
References css_send_data_to_client(), NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), return_error_to_client(), success(), and xbtree_class_test_unique().
Referenced by net_server_init().
void sbtree_delete_index (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 4141 of file network_interface_sr.c.
References css_send_data_to_client(), ER_FAILED, NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_btid(), return_error_to_client(), success(), and xbtree_delete_index().
Referenced by net_server_init().
void sbtree_find_multi_uniques (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 4257 of file network_interface_sr.c.
References assert_release, BTREE_ERROR_OCCURRED, BTREE_KEY_FOUND, cleanup(), cubregex::count(), css_send_reply_and_data_to_client(), db_private_alloc, db_private_free, ER_FAILED, error(), i, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_pack_oid(), or_unpack_btid(), or_unpack_db_value(), or_unpack_int(), or_unpack_oid(), pr_clear_value(), return_error_to_client(), and xbtree_find_multi_uniques().
Referenced by net_server_init().
void sbtree_find_unique (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 4208 of file network_interface_sr.c.
References sbtree_find_unique_internal().
Referenced by net_server_init().
static void sbtree_find_unique_internal (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen) static
Definition at line 4214 of file network_interface_sr.c.
References BTREE_ERROR_OCCURRED, css_send_data_to_client(), OID_SET_NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_OID_SIZE, or_pack_int(), or_pack_oid(), or_unpack_btid(), or_unpack_oid(), or_unpack_value(), pr_clear_value(), return_error_to_client(), S_SELECT_WITH_LOCK, success(), and xbtree_find_unique().
Referenced by sbtree_find_unique().
void sbtree_get_key_type (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 7401 of file network_interface_sr.c.
References ARG_FILE_LINE, assert_release, BTID_IS_NULL, css_send_reply_and_data_to_client(), er_errid(), ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_domain(), or_pack_int(), or_packed_domain_size(), or_unpack_btid(), return_error_to_client(), and xbtree_get_key_type().
Referenced by net_server_init().
void sbtree_get_statistics (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 7361 of file network_interface_sr.c.
References assert_release, btree_stats::btid, BTID_IS_NULL, btree_get_stats(), css_send_data_to_client(), btree_stats::height, btree_stats::keys, btree_stats::leafs, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_btid(), btree_stats::pages, btree_stats::pkeys, btree_stats::pkeys_size, return_error_to_client(), STATS_WITH_SAMPLING, and success().
Referenced by net_server_init().
void sbtree_load_index (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 3932 of file network_interface_sr.c.
References ARG_FILE_LINE, assert, ASSERT_ERROR_AND_SET, css_is_shutdowning_server(), css_receive_data_from_client(), css_send_abort_to_client(), css_send_data_to_client(), db_private_free_and_init, ER_ERROR_SEVERITY, ER_NET_SERVER_DATA_RECEIVE, er_set(), err, free_and_init, ib_thread_count, lock_get_object_lock(), LOG_FIND_THREAD_TRAN_INDEX, NO_ERROR, NULL, oid_Root_class_oid, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_BTID_ALIGNED_SIZE, OR_INT_SIZE, OR_ONLINE_INDEX_BUILDING_IN_PROGRESS, or_pack_btid(), or_pack_int(), or_unpack_btid(), or_unpack_domain(), or_unpack_hfid_array(), or_unpack_int(), or_unpack_int_array(), or_unpack_oid(), or_unpack_oid_array(), or_unpack_string_nocopy(), return_error_to_client(), SCH_M_LOCK, xbtree_load_index(), and xbtree_load_online_index().
Referenced by net_server_init().
void schksum_insert_repl_log_and_demote_table_lock (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 9735 of file network_interface_sr.c.
References css_send_data_to_client(), repl_info_statement::db_user, ER_FAILED, repl_info::info, repl_info_statement::name, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), or_unpack_oid(), or_unpack_string_nocopy(), repl_info::repl_info_type, REPL_INFO_TYPE_SBR, repl_info_statement::statement_type, repl_info_statement::stmt_text, success(), repl_info_statement::sys_prm_context, and xchksum_insert_repl_log_and_demote_table_lock().
Referenced by net_server_init().
void sct_check_rep_dir (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 6328 of file network_interface_sr.c.
References assert, css_send_data_to_client(), NO_ERROR, OID_ISNULL, OID_SET_NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_OID_SIZE, or_pack_int(), or_pack_oid(), or_unpack_oid(), return_error_to_client(), success(), and xcatalog_check_rep_dir().
Referenced by net_server_init().
void sdk_freepgs (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 4448 of file network_interface_sr.c.
References css_send_data_to_client(), OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), return_error_to_client(), and xdisk_get_free_numpages().
Referenced by net_server_init().
void sdk_remarks (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 4481 of file network_interface_sr.c.
References css_send_reply_and_data_to_client(), db_private_alloc, db_private_free_and_init, free_and_init, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_pack_string_with_length(), or_packed_string_length(), or_unpack_int(), return_error_to_client(), strlen, and xdisk_get_remarks().
Referenced by net_server_init().
void sdk_totalpgs (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 4415 of file network_interface_sr.c.
References css_send_data_to_client(), OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), return_error_to_client(), and xdisk_get_total_numpages().
Referenced by net_server_init().
void sdk_vlabel (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 4541 of file network_interface_sr.c.
References css_send_reply_and_data_to_client(), db_private_alloc, db_private_free_and_init, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_pack_string_with_length(), or_packed_string_length(), or_unpack_int(), return_error_to_client(), strlen, and xdisk_get_fullname().
Referenced by net_server_init().
static int server_capabilities (void) static
Definition at line 416 of file network_interface_sr.c.
References assert_release, BOOT_SERVER_MAINTENANCE, boot_Server_status, css_ha_server_state(), css_is_ha_repl_delayed(), db_Disable_modifications, HA_GET_MODE, HA_MODE_REPLICA, HA_SERVER_STATE_STANDBY, NET_CAP_HA_REPL_DELAY, NET_CAP_HA_REPLICA, NET_CAP_INTERRUPT_ENABLED, NET_CAP_REMOTE_DISABLED, and NET_CAP_UPDATE_DISABLED.
Referenced by check_client_capabilities(), net_client_ping_server_with_handshake(), and server_ping_with_handshake().
void server_ping (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 508 of file network_interface_sr.c.
References ARG_FILE_LINE, css_send_data_to_client(), er_log_debug, OR_ALIGNED_BUF, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), and or_unpack_int().
Referenced by net_server_init().
int server_ping_with_handshake (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 539 of file network_interface_sr.c.
References ARG_FILE_LINE, boot_Host_name, check_client_capabilities(), client_capabilities(), css_add_client_version_string(), css_increment_num_conn(), CSS_NO_ERRORS, css_send_data_to_client(), CSS_UNPLANNED_SHUTDOWN, CUB_MAXHOSTNAMELEN, ER_CSS_CLIENTS_EXCEEDED, ER_ERROR_SEVERITY, ER_NET_DIFFERENT_BIT_PLATFORM, ER_NET_DIFFERENT_RELEASE, ER_NET_SERVER_HAND_SHAKE, er_set(), NO_ERROR, NULL, NUM_NORMAL_TRANS, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_pack_string(), or_pack_string_with_length(), or_packed_string_length(), or_unpack_int(), or_unpack_string_nocopy(), rel_bit_platform(), rel_compare(), rel_get_net_compatible(), REL_MAX_RELEASE_LENGTH, REL_NOT_COMPATIBLE, rel_release_string(), return_error_to_client(), and server_capabilities().
Referenced by net_server_request().
void ses_posix_copy_file (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 8487 of file network_interface_sr.c.
References css_send_reply_and_data_to_client(), NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_string_nocopy(), return_error_to_client(), and strlen.
Referenced by net_server_init().
void ses_posix_create_file (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 8317 of file network_interface_sr.c.
References css_send_reply_and_data_to_client(), NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), return_error_to_client(), and strlen.
Referenced by net_server_init().
void ses_posix_delete_file (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 8455 of file network_interface_sr.c.
References css_send_data_to_client(), NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_string_nocopy(), and return_error_to_client().
Referenced by net_server_init().
void ses_posix_get_file_size (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 8565 of file network_interface_sr.c.
References css_send_data_to_client(), OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT64_SIZE, or_pack_int64(), or_unpack_string_nocopy(), and return_error_to_client().
Referenced by net_server_init().
void ses_posix_read_file (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 8406 of file network_interface_sr.c.
References cubregex::count(), css_send_abort_to_client(), css_send_reply_and_data_to_client(), db_private_alloc, db_private_free_and_init, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT64_SIZE, or_pack_int64(), or_unpack_int64(), or_unpack_string_nocopy(), and return_error_to_client().
Referenced by net_server_init().
void ses_posix_rename_file (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 8526 of file network_interface_sr.c.
References css_send_reply_and_data_to_client(), NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_string_nocopy(), return_error_to_client(), and strlen.
Referenced by net_server_init().
void ses_posix_write_file (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 8353 of file network_interface_sr.c.
References ARG_FILE_LINE, cubregex::count(), css_receive_data_from_client(), css_send_abort_to_client(), css_send_data_to_client(), ER_ERROR_SEVERITY, ER_NET_SERVER_DATA_RECEIVE, er_set(), free_and_init, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT64_SIZE, or_pack_int64(), or_unpack_int64(), or_unpack_string_nocopy(), and return_error_to_client().
Referenced by net_server_init().
void sfile_apply_tde_to_class_files (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 2522 of file network_interface_sr.c.
References css_send_data_to_client(), error(), NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_errcode(), or_unpack_oid(), return_error_to_client(), and xfile_apply_tde_to_class_files().
Referenced by net_server_init().
void shf_create (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 2373 of file network_interface_sr.c.
References css_send_data_to_client(), error(), NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_HFID_SIZE, OR_INT_SIZE, or_pack_errcode(), or_pack_hfid(), or_unpack_hfid(), or_unpack_int(), or_unpack_oid(), return_error_to_client(), and xheap_create().
Referenced by net_server_init().
void shf_destroy (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 2410 of file network_interface_sr.c.
References css_send_data_to_client(), error(), NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_errcode(), or_unpack_hfid(), return_error_to_client(), and xheap_destroy().
Referenced by net_server_init().
void shf_destroy_when_new (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 2443 of file network_interface_sr.c.
References css_send_data_to_client(), error(), NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_errcode(), or_unpack_hfid(), or_unpack_oid(), return_error_to_client(), and xheap_destroy_newly_created().
Referenced by net_server_init().
void shf_get_class_num_objs_and_pages (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 7323 of file network_interface_sr.c.
References css_send_data_to_client(), ER_FAILED, NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_hfid(), or_unpack_int(), return_error_to_client(), success(), and xheap_get_class_num_objects_pages().
Referenced by net_server_init().
void shf_has_instance (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 7763 of file network_interface_sr.c.
References css_send_data_to_client(), OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_hfid(), or_unpack_int(), or_unpack_oid(), return_error_to_client(), and xheap_has_instance().
Referenced by net_server_init().
void shf_heap_reclaim_addresses (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 2477 of file network_interface_sr.c.
References boot_can_compact(), boot_compact_stop(), css_send_data_to_client(), ER_COMPACTDB_ALREADY_STARTED, error(), NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_errcode(), or_unpack_hfid(), return_error_to_client(), and xheap_reclaim_addresses().
Referenced by net_server_init().
void sjsp_get_server_port (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 7826 of file network_interface_sr.c.
References css_send_data_to_client(), jsp_server_port(), OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, and or_pack_int().
Referenced by net_server_init().
void sloaddb_destroy (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 10152 of file network_interface_sr.c.
References assert, css_send_data_to_client(), er_errid(), er_has_error(), NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), return_error_to_client(), session_get_load_session(), session_set_load_session(), and cubload::session::wait_for_completion().
Referenced by net_server_init().
void sloaddb_fetch_status (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 10113 of file network_interface_sr.c.
References ARG_FILE_LINE, assert, css_send_reply_and_data_to_client(), er_errid(), ER_ERROR_SEVERITY, er_has_error(), ER_LDR_INVALID_STATE, er_set(), cubload::session::fetch_status(), cubpacking::packer::get_current_size(), cubmem::extensible_block::get_ptr(), NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), return_error_to_client(), session_get_load_session(), and cubpacking::packer::set_buffer_and_pack_all().
Referenced by net_server_init().
void sloaddb_init (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 9982 of file network_interface_sr.c.
References css_send_data_to_client(), NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), session_set_load_session(), and cubload::load_args::unpack().
Referenced by net_server_init().
void sloaddb_install_class (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 10008 of file network_interface_sr.c.
References ARG_FILE_LINE, assert, css_send_reply_and_data_to_client(), er_errid(), ER_ERROR_SEVERITY, er_has_error(), ER_LDR_INVALID_STATE, er_set(), cubload::session::install_class(), NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), return_error_to_client(), session_get_load_session(), and cubload::batch::unpack().
Referenced by net_server_init().
void sloaddb_interrupt (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 10178 of file network_interface_sr.c.
References assert, cubload::session::interrupt(), NO_ERROR, NULL, and session_get_load_session().
Referenced by net_server_init().
void sloaddb_load_batch (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 10052 of file network_interface_sr.c.
References ARG_FILE_LINE, assert, css_send_reply_and_data_to_client(), er_errid(), ER_ERROR_SEVERITY, er_has_error(), ER_LDR_INVALID_STATE, er_set(), cubpacking::packer::get_current_size(), cubmem::extensible_block::get_ptr(), cubload::session::load_batch(), NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), return_error_to_client(), session_get_load_session(), cubpacking::packer::set_buffer_and_pack_all(), cubload::batch::unpack(), and cubpacking::unpacker::unpack_bool().
Referenced by net_server_init().
void sloaddb_update_stats (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 10195 of file network_interface_sr.c.
References assert, css_send_data_to_client(), er_errid(), er_has_error(), NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), return_error_to_client(), session_get_load_session(), and cubload::session::update_class_statistics().
Referenced by net_server_init().
void slocator_assign_oid (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 1734 of file network_interface_sr.c.
References css_send_data_to_client(), ER_FAILED, NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_OID_SIZE, or_pack_int(), or_pack_oid(), or_unpack_hfid(), or_unpack_int(), or_unpack_oid(), or_unpack_string_nocopy(), return_error_to_client(), success(), and xlocator_assign_oid().
Referenced by net_server_init().
void slocator_assign_oid_batch (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 6505 of file network_interface_sr.c.
References css_send_data_to_client(), ER_FAILED, locator_free_oid_set(), locator_pack_oid_set(), locator_unpack_oid_set_to_new(), NO_ERROR, NULL, OR_INT_SIZE, or_pack_int(), return_error_to_client(), success(), and xlocator_assign_oid_batch().
Referenced by net_server_init().
void slocator_check_fk_validity (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 7925 of file network_interface_sr.c.
References css_send_data_to_client(), db_private_free_and_init, er_errid(), NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_btid(), or_unpack_domain(), or_unpack_hfid(), or_unpack_int(), or_unpack_int_array(), or_unpack_oid(), or_unpack_string(), return_error_to_client(), and xlocator_check_fk_validity().
Referenced by net_server_init().
void slocator_delete_class_name (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 1668 of file network_interface_sr.c.
References css_send_data_to_client(), LC_CLASSNAME_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_string_nocopy(), return_error_to_client(), and xlocator_delete_class_name().
Referenced by net_server_init().
void slocator_demote_class_lock (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 9957 of file network_interface_sr.c.
References css_send_data_to_client(), error(), NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_pack_lock(), or_unpack_lock(), or_unpack_oid(), return_error_to_client(), and xlocator_demote_class_lock().
Referenced by net_server_init().
void slocator_does_exist (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 898 of file network_interface_sr.c.
References css_send_data_to_client(), css_send_reply_and_2_data_to_client(), free_and_init, LC_ERROR, locator_free_copy_area(), locator_send_copy_area(), NET_COPY_AREA_SENDRECV_SIZE, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_OID_SIZE, or_pack_int(), or_pack_oid(), or_unpack_int(), or_unpack_lock(), or_unpack_oid(), return_error_to_client(), and xlocator_does_exist().
Referenced by net_server_init().
void slocator_fetch (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 646 of file network_interface_sr.c.
References css_send_data_to_client(), css_send_reply_and_2_data_to_client(), free_and_init, locator_free_copy_area(), locator_send_copy_area(), NET_COPY_AREA_SENDRECV_SIZE, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), or_unpack_lock(), or_unpack_oid(), return_error_to_client(), success(), and xlocator_fetch().
Referenced by net_server_init().
void slocator_fetch_all (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 810 of file network_interface_sr.c.
References css_send_data_to_client(), css_send_reply_and_2_data_to_client(), free_and_init, locator_free_copy_area(), locator_send_copy_area(), NET_COPY_AREA_SENDRECV_SIZE, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_OID_SIZE, or_pack_int(), or_pack_lock(), or_pack_oid(), or_unpack_hfid(), or_unpack_int(), or_unpack_lock(), or_unpack_oid(), return_error_to_client(), success(), and xlocator_fetch_all().
Referenced by net_server_init().
void slocator_fetch_all_reference_lockset (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 1423 of file network_interface_sr.c.
References css_send_data_to_client(), css_send_reply_and_3_data_to_client(), ER_FAILED, free_and_init, lc_lock_set::length, locator_free_copy_area(), locator_free_lockset(), locator_pack_lockset(), locator_send_copy_area(), NET_COPY_AREA_SENDRECV_SIZE, NET_SENDRECV_BUFFSIZE, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), or_unpack_lock(), or_unpack_oid(), lc_lock_set::packed, lc_lock_set::packed_size, return_error_to_client(), success(), and xlocator_fetch_all_reference_lockset().
Referenced by net_server_init().
void slocator_fetch_lockhint_classes (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 6712 of file network_interface_sr.c.
References ARG_FILE_LINE, css_receive_data_from_client(), css_send_abort_to_client(), css_send_data_to_client(), css_send_reply_and_3_data_to_client(), ER_ERROR_SEVERITY, ER_FAILED, ER_NET_SERVER_DATA_RECEIVE, er_set(), free_and_init, lc_lock_hint::length, locator_allocate_and_unpack_lockhint(), locator_free_copy_area(), locator_free_lockhint(), locator_pack_lockhint(), locator_send_copy_area(), NET_COPY_AREA_SENDRECV_SIZE, NET_SENDRECV_BUFFSIZE, NO_ERROR, NULL, lc_lock_hint::num_classes, lc_lock_hint::num_classes_processed, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), lc_lock_hint::packed, lc_lock_hint::packed_size, return_error_to_client(), success(), and xlocator_fetch_lockhint_classes().
Referenced by net_server_init().
void slocator_fetch_lockset (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 1295 of file network_interface_sr.c.
References ARG_FILE_LINE, css_receive_data_from_client(), css_send_abort_to_client(), css_send_data_to_client(), css_send_reply_and_3_data_to_client(), ER_ERROR_SEVERITY, ER_FAILED, ER_NET_SERVER_DATA_RECEIVE, er_set(), free_and_init, lc_lock_set::length, locator_allocate_and_unpack_lockset(), locator_free_copy_area(), locator_free_lockset(), locator_pack_lockset(), locator_send_copy_area(), NET_COPY_AREA_SENDRECV_SIZE, NET_SENDRECV_BUFFSIZE, NO_ERROR, NULL, lc_lock_set::num_classes_of_reqobjs, lc_lock_set::num_classes_of_reqobjs_processed, lc_lock_set::num_reqobjs, lc_lock_set::num_reqobjs_processed, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), lc_lock_set::packed, lc_lock_set::packed_size, return_error_to_client(), success(), and xlocator_fetch_lockset().
Referenced by net_server_init().
void slocator_find_class_oid (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 1539 of file network_interface_sr.c.
References css_send_data_to_client(), LC_CLASSNAME_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_OID_SIZE, or_pack_int(), or_pack_oid(), or_unpack_lock(), or_unpack_oid(), or_unpack_string_nocopy(), return_error_to_client(), and xlocator_find_class_oid().
Referenced by net_server_init().
void slocator_find_lockhint_class_oids (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 6556 of file network_interface_sr.c.
References ARG_FILE_LINE, css_send_data_to_client(), css_send_reply_and_3_data_to_client(), db_private_alloc, db_private_free_and_init, ER_ERROR_SEVERITY, ER_GENERIC_ERROR, er_set(), free_and_init, i, LC_CLASSNAME_ERROR, LC_CLASSNAME_EXIST, lc_lock_hint::length, locator_free_copy_area(), locator_free_lockhint(), locator_pack_lockhint(), locator_send_copy_area(), NET_COPY_AREA_SENDRECV_SIZE, NET_SENDRECV_BUFFSIZE, NO_ERROR, NULL, NULL_LOCK, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), or_unpack_lock(), or_unpack_oid(), or_unpack_string_nocopy(), lc_lock_hint::packed, lc_lock_hint::packed_size, return_error_to_client(), xlocator_find_lockhint_class_oids(), and xtran_lock_rep_read().
Referenced by net_server_init().
void slocator_force (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 1174 of file network_interface_sr.c.
References ARG_FILE_LINE, assert, css_receive_data_from_client(), css_send_abort_to_client(), css_send_reply_and_2_data_to_client(), ER_ERROR_SEVERITY, ER_LAST_ERROR, ER_LC_PARTIALLY_FAILED_TO_FLUSH, ER_NET_SERVER_DATA_RECEIVE, er_set(), free_and_init, i, LC_MANYOBJS_PTR_IN_COPYAREA, locator_free_copy_area(), locator_pack_copy_area_descriptor(), locator_recv_allocate_copyarea(), locator_unpack_copy_area_descriptor(), lc_copyarea_manyobjs::multi_update_flags, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), return_error_to_client(), success(), and xlocator_force().
Referenced by net_server_init().
void slocator_get_class (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 731 of file network_interface_sr.c.
References css_send_data_to_client(), css_send_reply_and_2_data_to_client(), free_and_init, locator_free_copy_area(), locator_send_copy_area(), NET_COPY_AREA_SENDRECV_SIZE, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_OID_SIZE, or_pack_int(), or_pack_oid(), or_unpack_int(), or_unpack_lock(), or_unpack_oid(), return_error_to_client(), success(), and xlocator_get_class().
Referenced by net_server_init().
void slocator_get_reserved_class_name_oid (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 1632 of file network_interface_sr.c.
References assert, ASSERT_ERROR, css_send_data_to_client(), error(), NO_ERROR, OID_INITIALIZER, OID_ISNULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_OID_SIZE, or_pack_oid(), or_unpack_string_nocopy(), return_error_to_client(), and xlocator_get_reserved_class_name_oid().
Referenced by net_server_init().
void slocator_notify_isolation_incons (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 982 of file network_interface_sr.c.
References css_send_data_to_client(), css_send_reply_and_2_data_to_client(), free_and_init, locator_free_copy_area(), locator_send_copy_area(), NET_COPY_AREA_SENDRECV_SIZE, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), return_error_to_client(), success(), and xlocator_notify_isolation_incons().
Referenced by net_server_init().
void slocator_redistribute_partition_data (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 9812 of file network_interface_sr.c.
References ARG_FILE_LINE, css_send_data_to_client(), ER_ERROR_SEVERITY, ER_INVALID_PARTITION_REQUEST, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, i, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), or_unpack_oid(), return_error_to_client(), success(), and xlocator_redistribute_partition_data().
Referenced by net_server_init().
void slocator_remove_class_from_index (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 4172 of file network_interface_sr.c.
References css_send_data_to_client(), ER_FAILED, NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_btid(), or_unpack_hfid(), or_unpack_oid(), return_error_to_client(), success(), and xlocator_remove_class_from_index().
Referenced by net_server_init().
void slocator_rename_class_name (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 1699 of file network_interface_sr.c.
References css_send_data_to_client(), LC_CLASSNAME_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_oid(), or_unpack_string_nocopy(), return_error_to_client(), and xlocator_rename_class_name().
Referenced by net_server_init().
void slocator_repl_force (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 1050 of file network_interface_sr.c.
References ARG_FILE_LINE, css_receive_data_from_client(), css_send_abort_to_client(), css_send_reply_and_2_data_to_client(), ER_ERROR_SEVERITY, ER_LC_PARTIALLY_FAILED_TO_FLUSH, ER_NET_SERVER_DATA_RECEIVE, er_set(), free_and_init, LC_MANYOBJS_PTR_IN_COPYAREA, locator_free_copy_area(), locator_recv_allocate_copyarea(), locator_send_copy_area(), locator_unpack_copy_area_descriptor(), NET_COPY_AREA_SENDRECV_SIZE, NO_ERROR, NULL, lc_copyarea_manyobjs::num_objs, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), return_error_to_client(), success(), and xlocator_repl_force().
Referenced by net_server_init().
void slocator_reserve_classnames (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 1577 of file network_interface_sr.c.
References css_send_data_to_client(), db_private_alloc, db_private_free_and_init, i, LC_CLASSNAME_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), or_unpack_oid(), or_unpack_string_nocopy(), return_error_to_client(), and xlocator_reserve_class_names().
Referenced by net_server_init().
void slocator_upgrade_instances_domain (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 8597 of file network_interface_sr.c.
References css_send_data_to_client(), NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), or_unpack_oid(), return_error_to_client(), success(), and xlocator_upgrade_instances_domain().
Referenced by net_server_init().
void slock_dump (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 2295 of file network_interface_sr.c.
References ARG_FILE_LINE, css_send_abort_to_client(), css_send_data_to_client(), db_private_alloc, db_private_free_and_init, ER_ERROR_SEVERITY, ER_GENERIC_ERROR, er_set_with_oserror(), NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), and xlock_dump().
Referenced by net_server_init().
void slog_add_lob_locator (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 2086 of file network_interface_sr.c.
References css_send_data_to_client(), error(), NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), or_unpack_string_nocopy(), return_error_to_client(), and xtx_add_lob_locator().
Referenced by net_server_init().
void slog_change_state_of_locator (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 2121 of file network_interface_sr.c.
References css_send_data_to_client(), error(), NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), or_unpack_string_nocopy(), return_error_to_client(), and xtx_change_state_of_locator().
Referenced by net_server_init().
void slog_checkpoint (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 1817 of file network_interface_sr.c.
References css_send_data_to_client(), error(), log_wakeup_checkpoint_daemon(), logtb_has_updated(), NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_errcode(), and or_pack_int().
Referenced by net_server_init().
void slog_drop_lob_locator (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 2157 of file network_interface_sr.c.
References css_send_data_to_client(), error(), NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_string_nocopy(), return_error_to_client(), and xtx_drop_lob_locator().
Referenced by net_server_init().
void slog_find_lob_locator (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 2053 of file network_interface_sr.c.
References css_send_reply_and_data_to_client(), OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_string_nocopy(), strlen, and xtx_find_lob_locator().
Referenced by net_server_init().
void slogin_user (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 9161 of file network_interface_sr.c.
References css_send_data_to_client(), ER_FAILED, err, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_string_nocopy(), return_error_to_client(), and xlogin_user().
Referenced by net_server_init().
void slogpb_dump_stat (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 1975 of file network_interface_sr.c.
References ARG_FILE_LINE, css_send_abort_to_client(), css_send_data_to_client(), db_private_alloc, db_private_free_and_init, ER_ERROR_SEVERITY, ER_GENERIC_ERROR, er_set_with_oserror(), NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), and xlogpb_dump_stat().
Referenced by net_server_init().
void slogtb_does_active_user_exist (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 9786 of file network_interface_sr.c.
References css_send_data_to_client(), OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_string_nocopy(), and xlogtb_does_active_user_exist().
Referenced by net_server_init().
void slogtb_dump_trantable (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 7051 of file network_interface_sr.c.
References ARG_FILE_LINE, css_send_abort_to_client(), css_send_data_to_client(), db_private_alloc, db_private_free_and_init, ER_ERROR_SEVERITY, ER_GENERIC_ERROR, er_set_with_oserror(), NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), and xlogtb_dump_trantable().
Referenced by net_server_init().
void slogtb_get_mvcc_snapshot (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 9445 of file network_interface_sr.c.
References css_send_data_to_client(), err, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), return_error_to_client(), and xlogtb_get_mvcc_snapshot().
Referenced by net_server_init().
void slogtb_get_pack_tran_table (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 7012 of file network_interface_sr.c.
References css_send_data_to_client(), error(), free_and_init, NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), and xlogtb_get_pack_tran_table().
Referenced by net_server_init().
void slogtb_reset_isolation (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 1943 of file network_interface_sr.c.
References css_send_data_to_client(), NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), return_error_to_client(), and xlogtb_reset_isolation().
Referenced by net_server_init().
void slogtb_reset_wait_msecs (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 1917 of file network_interface_sr.c.
References css_send_data_to_client(), OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), and xlogtb_reset_wait_msecs().
Referenced by net_server_init().
void slogtb_set_interrupt (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 1867 of file network_interface_sr.c.
References or_unpack_int(), and xlogtb_set_interrupt().
Referenced by net_server_init().
void slogtb_set_suppress_repl_on_transaction (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 1891 of file network_interface_sr.c.
References css_send_data_to_client(), NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), and xlogtb_set_suppress_repl_on_transaction().
Referenced by net_server_init().
void slogwr_get_log_pages (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 7988 of file network_interface_sr.c.
References css_end_server_request(), css_send_data_to_client(), END_CALLBACK, ER_INTERRUPTED, ER_NET_DATA_RECEIVE_TIMEDOUT, error(), mode, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), or_unpack_int64(), and return_error_to_client().
Referenced by net_server_init().
void smnt_server_copy_global_stats (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 6285 of file network_interface_sr.c.
References ASSERT_ERROR, css_send_abort_to_client(), css_send_data_to_client(), free_and_init, NULL, perfmon_allocate_packed_values_buffer(), perfmon_allocate_values(), perfmon_get_number_of_statistic_values(), perfmon_pack_stats(), and xperfmon_server_copy_global_stats().
Referenced by net_server_init().
void smnt_server_copy_stats (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 6241 of file network_interface_sr.c.
References ASSERT_ERROR, css_send_abort_to_client(), css_send_data_to_client(), free_and_init, NULL, perfmon_allocate_packed_values_buffer(), perfmon_allocate_values(), perfmon_get_number_of_statistic_values(), perfmon_pack_stats(), and xperfmon_server_copy_stats().
Referenced by net_server_init().
void smnt_server_start_stats (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 6195 of file network_interface_sr.c.
References css_send_data_to_client(), NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, and or_pack_int().
Referenced by net_server_init().
void smnt_server_stop_stats (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 6218 of file network_interface_sr.c.
References css_send_data_to_client(), OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, and or_pack_int().
Referenced by net_server_init().
void sprm_server_change_parameters (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 7563 of file network_interface_sr.c.
References css_send_data_to_client(), NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), PRM_ERR_NO_ERROR, sysprm_free_assign_values(), sysprm_unpack_assign_values(), and xsysprm_change_server_parameters().
Referenced by net_server_init().
void sprm_server_dump_parameters (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 7684 of file network_interface_sr.c.
References ARG_FILE_LINE, css_send_abort_to_client(), css_send_data_to_client(), db_private_alloc, db_private_free_and_init, ER_ERROR_SEVERITY, ER_GENERIC_ERROR, er_set_with_oserror(), NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), and xsysprm_dump_server_parameters().
Referenced by net_server_init().
void sprm_server_get_force_parameters (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 7591 of file network_interface_sr.c.
References ARG_FILE_LINE, css_send_reply_and_data_to_client(), er_errid(), ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), return_error_to_client(), sysprm_free_assign_values(), sysprm_pack_assign_values(), sysprm_packed_assign_values_length(), and xsysprm_get_force_server_parameters().
Referenced by net_server_init().
void sprm_server_obtain_parameters (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 7637 of file network_interface_sr.c.
References ARG_FILE_LINE, css_send_reply_and_data_to_client(), ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), PRM_ERR_NO_ERROR, PRM_ERR_NO_MEM_FOR_PRM, rc, sysprm_free_assign_values(), sysprm_pack_assign_values(), sysprm_packed_assign_values_length(), sysprm_unpack_assign_values(), and xsysprm_obtain_server_parameters().
Referenced by net_server_init().
void sqfile_get_list_file_page (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 4595 of file network_interface_sr.c.
References css_send_reply_and_data_to_client(), error(), IO_MAX_PAGE_SIZE, MAX_ALIGNMENT, NO_ERROR, NULL_PAGEID, NULL_VOLID, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), or_unpack_ptr(), page_size, PTR_ALIGN, QFILE_PAGE_HEADER_SIZE, qmgr_setup_empty_list_file(), return_error_to_client(), and xqfile_get_list_file_page().
Referenced by net_server_init().
void sqmgr_drop_all_query_plans (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 5816 of file network_interface_sr.c.
References css_send_data_to_client(), NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), return_error_to_client(), and xqmgr_drop_all_query_plans().
Referenced by net_server_init().
void sqmgr_dump_query_cache (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 5929 of file network_interface_sr.c.
References ARG_FILE_LINE, css_send_abort_to_client(), css_send_data_to_client(), db_private_alloc, db_private_free_and_init, ER_ERROR_SEVERITY, ER_GENERIC_ERROR, er_set_with_oserror(), NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), and xqmgr_dump_query_cache().
Referenced by net_server_init().
void sqmgr_dump_query_plans (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 5850 of file network_interface_sr.c.
References ARG_FILE_LINE, css_send_abort_to_client(), css_send_data_to_client(), db_private_alloc, db_private_free_and_init, ER_ERROR_SEVERITY, ER_GENERIC_ERROR, er_set_with_oserror(), NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), and xqmgr_dump_query_plans().
Referenced by net_server_init().
void sqmgr_end_query (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 5770 of file network_interface_sr.c.
References css_send_data_to_client(), i, NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), or_unpack_ptr(), return_error_to_client(), and xqmgr_end_query().
Referenced by net_server_init().
void sqmgr_execute_query (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 4945 of file network_interface_sr.c.
References ARG_FILE_LINE, assert, ASSERT_ERROR, ASSERT_ERROR_AND_SET, CACHE_TIME_EQ, CACHE_TIME_RESET, css_receive_data_from_client(), css_send_abort_to_client(), css_send_reply_and_3_data_to_client(), DB_PAGESIZE, db_private_alloc, db_private_free_and_init, ER_ERROR_SEVERITY, ER_INTERRUPTED, er_log_slow_query(), ER_NET_SERVER_DATA_RECEIVE, ER_NOTIFICATION_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, ER_QPROC_XASLNODE_RECOMPILE_REQUESTED, ER_QUERY_EXECUTION_ERROR, er_set(), event_log_many_ioreads(), event_log_slow_query(), event_log_temp_expand_pages(), EXECUTE_QUERY_MAX_ARGUMENT_DATA_SIZE, qfile_list_id::first_vpid, free_and_init, i, IO_MAX_PAGE_SIZE, IS_QUERY_EXECUTE_WITH_COMMIT, IS_QUERY_EXECUTED_WITHOUT_DATA_BUFFERS, IS_TRAN_AUTO_COMMIT, LOG_FIND_CURRENT_TDES(), logtb_has_updated(), MAX_ALIGNMENT, need_to_abort_tran(), NET_DEFER_END_QUERIES_MAX, NO_ERROR, NULL, NULL_PAGEID, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_CACHE_TIME_SIZE, OR_INT_SIZE, or_listid_length(), OR_PACK_CACHE_TIME, or_pack_int(), or_pack_listid(), or_pack_ptr(), OR_PTR_ALIGNED_SIZE, OR_UNPACK_CACHE_TIME, or_unpack_int(), or_unpack_ptr(), OR_UNPACK_XASL_ID, page_size, perfmon_allocate_values(), perfmon_calc_diff_stats(), prm_get_integer_value(), PRM_ID_SQL_TRACE_IOREADS, PRM_ID_SQL_TRACE_SLOW_MSECS, pstat_Metadata, PSTAT_PB_NUM_IOREADS, PTR_ALIGN, QFILE_FREE_AND_INIT_LIST_ID, QFILE_GET_LAST_TUPLE_OFFSET, QFILE_GET_OVERFLOW_PAGE_ID, QFILE_GET_TUPLE_COUNT, QFILE_GET_TUPLE_LENGTH, qmgr_free_old_page_and_init, qmgr_get_old_page(), qmgr_get_sql_id(), QUERY_END, QUERY_INFO_BUF_SIZE, query_timeout, return_error_to_client(), execution_info::sql_hash_text, xasl_cache_ent::sql_info, execution_info::sql_user_text, log_tdes::state, stran_can_end_after_query_execution(), stran_server_auto_commit_or_abort(), strlen, qfile_list_id::tfile_vfid, tran_abort(), tsc_elapsed_time_usec(), tsc_getticks(), VPID_ISNULL, xcache_unfix(), xperfmon_server_copy_stats(), xqmgr_execute_query(), and xsession_set_tran_auto_commit().
Referenced by net_server_init().
void sqmgr_prepare_and_execute_query (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 5562 of file network_interface_sr.c.
References ARG_FILE_LINE, cleanup(), css_receive_data_from_client(), css_send_abort_to_client(), css_send_reply_and_3_data_to_client(), DB_PAGESIZE, db_private_alloc, db_private_free_and_init, er_errid(), ER_ERROR_SEVERITY, ER_NET_SERVER_DATA_RECEIVE, er_set(), qfile_list_id::first_vpid, free_and_init, IO_MAX_PAGE_SIZE, IS_TRAN_AUTO_COMMIT, MAX_ALIGNMENT, NULL, NULL_PAGEID, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_listid_length(), or_pack_int(), or_pack_listid(), or_pack_ptr(), OR_PTR_ALIGNED_SIZE, or_unpack_int(), page_size, PTR_ALIGN, QFILE_FREE_AND_INIT_LIST_ID, QFILE_GET_LAST_TUPLE_OFFSET, QFILE_GET_OVERFLOW_PAGE_ID, QFILE_GET_TUPLE_COUNT, QFILE_GET_TUPLE_LENGTH, qmgr_free_old_page_and_init, qmgr_get_old_page(), QUERY_END, query_timeout, return_error_to_client(), qfile_list_id::tfile_vfid, VPID_ISNULL, xqmgr_prepare_and_execute_query(), and xsession_set_tran_auto_commit().
Referenced by net_server_init().
void sqmgr_prepare_query (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 4662 of file network_interface_sr.c.
References ARG_FILE_LINE, assert, ASSERT_ERROR, bool, xasl_stream::buffer, xasl_stream::buffer_size, css_receive_data_from_client(), css_send_abort_to_client(), css_send_reply_and_data_to_client(), ER_ERROR_SEVERITY, ER_NET_SERVER_DATA_RECEIVE, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, INIT_XASL_NODE_HEADER, compile_context::is_xasl_pinned_reference, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), OR_PACK_XASL_ID, OR_PACK_XASL_NODE_HEADER, or_unpack_int(), or_unpack_sha1(), or_unpack_string_nocopy(), OR_XASL_ID_SIZE, compile_context::recompile_xasl, compile_context::recompile_xasl_pinned, return_error_to_client(), compile_context::sha1, SHA1_HASH_INITIALIZER, compile_context::sql_hash_text, compile_context::sql_plan_text, compile_context::sql_user_text, STATIC_INLINE, xasl_stream::xasl_header, xasl_stream::xasl_id, XASL_ID_IS_NULL, XASL_ID_SET_NULL, XASL_NODE_HEADER_SIZE, and xqmgr_prepare_query().
Referenced by net_server_init().
void sqp_get_server_info (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 7470 of file network_interface_sr.c.
References css_send_reply_and_data_to_client(), db_private_alloc, db_private_free_and_init, db_sys_date_and_epoch_time(), ER_OUT_OF_VIRTUAL_MEMORY, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_pack_value(), or_unpack_int(), OR_VALUE_ALIGNED_SIZE, return_error_to_client(), SI_LOCAL_TRANSACTION_ID, SI_SYS_DATETIME, success(), and xtran_get_local_transaction_id().
Referenced by net_server_init().
void sqp_get_sys_timestamp (THREAD_ENTRY * thread_p, unsigned int rid, char * request_ignore, int reqlen_ignore)
Definition at line 6005 of file network_interface_sr.c.
References css_send_data_to_client(), db_get_timestamp(), db_sys_timestamp(), OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, and OR_UTIME_SIZE.
Referenced by net_server_init().
void sqst_server_get_statistics (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 1774 of file network_interface_sr.c.
References css_send_reply_and_data_to_client(), free_and_init, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), or_unpack_oid(), return_error_to_client(), and xstats_get_statistics_from_server().
Referenced by net_server_init().
void sqst_update_all_statistics (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 3858 of file network_interface_sr.c.
References css_send_data_to_client(), error(), NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_errcode(), or_unpack_int(), return_error_to_client(), STATS_WITH_FULLSCAN, STATS_WITH_SAMPLING, and xstats_update_all_statistics().
Referenced by net_server_init().
void sqst_update_statistics (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 3825 of file network_interface_sr.c.
References css_send_data_to_client(), error(), NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_errcode(), or_unpack_int(), or_unpack_oid(), return_error_to_client(), STATS_WITH_FULLSCAN, STATS_WITH_SAMPLING, and xstats_update_statistics().
Referenced by net_server_init().
void srepl_log_get_append_lsa (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 7899 of file network_interface_sr.c.
References css_send_data_to_client(), OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_LOG_LSA_ALIGNED_SIZE, or_pack_log_lsa(), and xrepl_log_get_append_lsa().
Referenced by net_server_init().
void srepl_set_info (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 7847 of file network_interface_sr.c.
References css_send_data_to_client(), repl_info_statement::db_user, ER_FAILED, repl_info::info, LOG_CHECK_LOG_APPLIER, log_does_allow_replication(), repl_info_statement::name, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), or_unpack_string_nocopy(), repl_info::repl_info_type, REPL_INFO_TYPE_SBR, repl_info_statement::statement_type, repl_info_statement::stmt_text, success(), repl_info_statement::sys_prm_context, and xrepl_set_info().
Referenced by net_server_init().
void sserial_decache (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 6170 of file network_interface_sr.c.
References css_send_data_to_client(), NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_oid(), and xserial_decache().
Referenced by net_server_init().
void sserial_get_current_value (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 6031 of file network_interface_sr.c.
References assert, css_send_reply_and_data_to_client(), db_private_alloc, db_private_free_and_init, db_value_clear(), er_errid(), ER_OUT_OF_VIRTUAL_MEMORY, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, or_db_value_size(), OR_INT_SIZE, or_pack_int(), or_pack_value(), or_unpack_int(), or_unpack_oid(), p, return_error_to_client(), and xserial_get_current_value().
Referenced by net_server_init().
void sserial_get_next_value (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 6099 of file network_interface_sr.c.
References css_send_reply_and_data_to_client(), db_private_alloc, db_private_free_and_init, db_value_clear(), ER_OUT_OF_VIRTUAL_MEMORY, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, or_db_value_size(), OR_INT_SIZE, or_pack_int(), or_pack_value(), or_unpack_int(), or_unpack_oid(), p, return_error_to_client(), and xserial_get_next_value().
Referenced by net_server_init().
void ssession_create_prepared_statement (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 8924 of file network_interface_sr.c.
References ARG_FILE_LINE, css_receive_data_from_client(), css_send_abort_to_client(), css_send_data_to_client(), ER_ERROR_SEVERITY, ER_NET_SERVER_DATA_RECEIVE, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), err, error(), free_and_init, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), or_unpack_sha1(), or_unpack_string_alloc(), return_error_to_client(), SHA1_HASH_INITIALIZER, and xsession_create_prepared_statement().
Referenced by net_server_init().
void ssession_delete_prepared_statement (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 9126 of file network_interface_sr.c.
References css_send_data_to_client(), ER_FAILED, err, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_string_nocopy(), return_error_to_client(), and xsession_delete_prepared_statement().
Referenced by net_server_init().
void ssession_drop_session_variables (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 9474 of file network_interface_sr.c.
References ARG_FILE_LINE, cleanup(), cubregex::count(), css_receive_data_from_client(), css_send_abort_to_client(), css_send_data_to_client(), ER_ERROR_SEVERITY, ER_FAILED, ER_NET_SERVER_DATA_RECEIVE, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), err, free_and_init, i, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_db_value(), or_unpack_int(), pr_clear_value(), return_error_to_client(), and xsession_drop_session_variables().
Referenced by net_server_init().
void ssession_end_session (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 8759 of file network_interface_sr.c.
References css_send_data_to_client(), err, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), and xsession_end_session().
Referenced by net_server_init().
void ssession_find_or_create_session (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 8634 of file network_interface_sr.c.
References ARG_FILE_LINE, assert, css_send_reply_and_data_to_client(), css_set_user_access_status(), DB_EMPTY_SESSION, DB_MAX_USER_LENGTH, er_clear(), ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, host, intl_identifier_upper(), logtb_set_current_user_name(), NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_pack_stream(), or_packed_stream_length(), or_unpack_int(), or_unpack_stream(), or_unpack_string_alloc(), program_name, return_error_to_client(), SERVER_SESSION_KEY_SIZE, sysprm_pack_session_parameters(), sysprm_packed_session_parameters_length(), sysprm_set_error(), sysprm_unpack_session_parameters(), xboot_get_server_session_key(), xsession_check_session(), xsession_create_new(), and xsession_get_row_count().
Referenced by net_server_init().
void ssession_get_last_insert_id (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 8843 of file network_interface_sr.c.
References css_send_reply_and_data_to_client(), db_private_alloc, db_private_free, ER_FAILED, err, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_pack_value(), or_unpack_int(), OR_VALUE_ALIGNED_SIZE, return_error_to_client(), and xsession_get_last_insert_id().
Referenced by net_server_init().
void ssession_get_prepared_statement (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 9024 of file network_interface_sr.c.
References ARG_FILE_LINE, cleanup(), css_send_reply_and_data_to_client(), db_private_free_and_init, ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), err, error(), free_and_init, INIT_XASL_NODE_HEADER, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_pack_stream(), OR_PACK_XASL_ID, OR_PACK_XASL_NODE_HEADER, or_packed_stream_length(), or_unpack_int(), or_unpack_string(), OR_XASL_ID_SIZE, return_error_to_client(), XASL_NODE_HEADER_SIZE, and xsession_get_prepared_statement().
Referenced by net_server_init().
void ssession_get_row_count (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 8816 of file network_interface_sr.c.
References css_send_data_to_client(), err, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), return_error_to_client(), and xsession_get_row_count().
Referenced by net_server_init().
void ssession_get_session_variable (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 9275 of file network_interface_sr.c.
References ARG_FILE_LINE, css_send_reply_and_data_to_client(), db_make_null(), ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), err, free_and_init, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, or_db_value_size(), OR_INT_SIZE, or_pack_db_value(), or_pack_int(), or_unpack_db_value(), pr_clear_value(), return_error_to_client(), and xsession_get_session_variable().
Referenced by net_server_init().
void ssession_reset_cur_insert_id (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 8898 of file network_interface_sr.c.
References css_send_data_to_client(), err, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), return_error_to_client(), and xsession_reset_cur_insert_id().
Referenced by net_server_init().
void ssession_set_row_count (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 8787 of file network_interface_sr.c.
References css_send_data_to_client(), err, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), return_error_to_client(), and xsession_set_row_count().
Referenced by net_server_init().
void ssession_set_session_variables (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 9197 of file network_interface_sr.c.
References ARG_FILE_LINE, cleanup(), cubregex::count(), css_receive_data_from_client(), css_send_abort_to_client(), css_send_data_to_client(), ER_ERROR_SEVERITY, ER_FAILED, ER_NET_SERVER_DATA_RECEIVE, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), err, free_and_init, i, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_db_value(), or_unpack_int(), pr_clear_value(), return_error_to_client(), and xsession_set_session_variables().
Referenced by net_server_init().
void ssession_stop_attached_threads (void * session)
Definition at line 10222 of file network_interface_sr.c.
References session_stop_attached_threads().
Referenced by net_server_conn_down().
void stde_change_mk_on_server (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 2681 of file network_interface_sr.c.
References css_send_data_to_client(), error(), NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_errcode(), or_unpack_int(), return_error_to_client(), and xtde_change_mk_without_flock().
Referenced by net_server_init().
void stde_get_data_keys (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 2543 of file network_interface_sr.c.
References css_send_reply_and_data_to_client(), tde_cipher::data_keys, db_private_alloc, db_private_free_and_init, ER_TDE_CIPHER_IS_NOT_LOADED, err, tde_cipher::is_loaded, tde_data_key_set::log_key, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_pack_stream(), or_packed_stream_length(), tde_data_key_set::perm_key, return_error_to_client(), tde_Cipher, TDE_DATA_KEY_LENGTH, and tde_data_key_set::temp_key.
Referenced by net_server_init().
void stde_get_mk_file_path (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 2599 of file network_interface_sr.c.
References boot_db_full_name(), css_send_reply_and_data_to_client(), db_private_alloc, db_private_free_and_init, err, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_pack_string_with_length(), or_packed_string_length(), return_error_to_client(), and tde_make_keys_file_fullname().
Referenced by net_server_init().
void stde_get_mk_info (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 2647 of file network_interface_sr.c.
References css_send_data_to_client(), error(), NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_BIGINT_SIZE, OR_INT_SIZE, or_pack_errcode(), or_pack_int(), or_pack_int64(), return_error_to_client(), and xtde_get_mk_info().
Referenced by net_server_init().
void sthread_dump_cs_stat (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 6935 of file network_interface_sr.c.
References ARG_FILE_LINE, css_send_abort_to_client(), css_send_data_to_client(), db_private_alloc, db_private_free_and_init, ER_ERROR_SEVERITY, ER_GENERIC_ERROR, er_set_with_oserror(), NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), sync_dump_statistics(), and SYNC_TYPE_ALL.
Referenced by net_server_init().
void sthread_kill_or_interrupt_tran (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 6876 of file network_interface_sr.c.
References css_send_data_to_client(), db_private_free, ER_KILL_TR_NOT_ALLOWED, i, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), or_unpack_int_array(), return_error_to_client(), success(), and xlogtb_kill_or_interrupt_tran().
Referenced by net_server_init().
void sthread_kill_tran_index (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 6837 of file network_interface_sr.c.
References css_send_data_to_client(), ER_FAILED, NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), or_unpack_string_nocopy(), return_error_to_client(), success(), and xlogtb_kill_tran_index().
Referenced by net_server_init().
STATIC_INLINE int stran_can_end_after_query_execution (THREAD_ENTRY * thread_p, int query_flag, QFILE_LIST_ID * list_id, bool * can_end_transaction)
Definition at line 4812 of file network_interface_sr.c.
References assert, DB_TYPE_VARCHAR, DB_TYPE_VARNCHAR, qfile_tuple_value_type_list::domp, ER_FAILED, i, pr_type::id, qfile_list_id::last_offset, NO_ERROR, NULL, or_get_varchar_compression_lengths(), or_init(), qfile_list_id::page_cnt, PEEK, or_buf::ptr, QEWC_MAX_DATA_SIZE, qfile_close_scan(), QFILE_GET_TUPLE_LENGTH, QFILE_GET_TUPLE_VALUE_FLAG, QFILE_GET_TUPLE_VALUE_LENGTH, qfile_open_list_scan(), qfile_scan_list_next(), QFILE_TUPLE_LENGTH_SIZE, QFILE_TUPLE_VALUE_HEADER_SIZE, RESULT_HOLDABLE, S_ERROR, S_SUCCESS, qfile_tuple_record::tpl, tp_domain::type, qfile_tuple_value_type_list::type_cnt, qfile_list_id::type_list, and V_UNBOUND.
Referenced by sqmgr_execute_query().
void stran_get_local_transaction_id (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 7801 of file network_interface_sr.c.
References css_send_data_to_client(), db_get_int(), ER_FAILED, NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), success(), and xtran_get_local_transaction_id().
Referenced by net_server_init().
void stran_is_blocked (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 2998 of file network_interface_sr.c.
References css_send_data_to_client(), OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), and xtran_is_blocked().
Referenced by net_server_init().
void stran_lock_rep_read (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 3288 of file network_interface_sr.c.
References css_send_data_to_client(), NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), return_error_to_client(), success(), and xtran_lock_rep_read().
Referenced by net_server_init().
void stran_server_2pc_attach_global_tran (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 3225 of file network_interface_sr.c.
References css_send_data_to_client(), NULL_TRAN_INDEX, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), return_error_to_client(), and xtran_server_2pc_attach_global_tran().
Referenced by net_server_init().
void stran_server_2pc_prepare (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 3143 of file network_interface_sr.c.
References css_send_data_to_client(), OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), return_error_to_client(), TRAN_UNACTIVE_2PC_PREPARE, TRAN_UNACTIVE_COMMITTED, TRAN_UNACTIVE_UNKNOWN, and xtran_server_2pc_prepare().
Referenced by net_server_init().
void stran_server_2pc_prepare_global_tran (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 3256 of file network_interface_sr.c.
References css_send_data_to_client(), OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), return_error_to_client(), TRAN_UNACTIVE_2PC_PREPARE, TRAN_UNACTIVE_COMMITTED, and xtran_server_2pc_prepare_global_tran().
Referenced by net_server_init().
void stran_server_2pc_recovery_prepared (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 3172 of file network_interface_sr.c.
References cubregex::count(), css_send_abort_to_client(), css_send_data_to_client(), free_and_init, i, NULL, OR_INT_SIZE, or_pack_int(), or_unpack_int(), return_error_to_client(), and xtran_server_2pc_recovery_prepared().
Referenced by net_server_init().
void stran_server_2pc_start (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 3115 of file network_interface_sr.c.
References css_send_data_to_client(), NULL_TRANID, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), return_error_to_client(), and xtran_server_2pc_start().
Referenced by net_server_init().
void stran_server_abort (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 2765 of file network_interface_sr.c.
References css_send_data_to_client(), logtb_has_updated(), OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), and stran_server_abort_internal().
Referenced by net_server_init().
STATIC_INLINE TRAN_STATE stran_server_abort_internal (THREAD_ENTRY * thread_p, unsigned int rid, bool retain_lock, bool * should_conn_reset)
Referenced by stran_server_abort(), and stran_server_auto_commit_or_abort().
STATIC_INLINE TRAN_STATE stran_server_abort_internal (THREAD_ENTRY * thread_p, unsigned int rid, bool * should_conn_reset)
Definition at line 178 of file network_interface_sr.c.
References logtb_has_updated(), net_cleanup_server_queues(), return_error_to_client(), STATIC_INLINE, TRAN_UNACTIVE_ABORTED, TRAN_UNACTIVE_ABORTED_INFORMING_PARTICIPANTS, xtran_server_abort(), and xtran_should_connection_reset().
STATIC_INLINE void stran_server_auto_commit_or_abort (THREAD_ENTRY * thread_p, unsigned int rid, QUERY_ID * p_end_queries, int n_query_ids, bool need_abort, bool has_updated, bool * end_query_allowed, TRAN_STATE * tran_state, bool * should_conn_reset)
Definition at line 219 of file network_interface_sr.c.
References _er_log_debug(), ARG_FILE_LINE, assert, i, NO_ERROR, NULL, prm_get_bool_value(), PRM_ID_DEBUG_AUTOCOMMIT, return_error_to_client(), stran_server_abort_internal(), stran_server_commit_internal(), TRAN_UNACTIVE_ABORTED, TRAN_UNACTIVE_ABORTED_INFORMING_PARTICIPANTS, xqmgr_end_query(), and xtran_should_connection_reset().
Referenced by sqmgr_execute_query().
void stran_server_commit (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 2714 of file network_interface_sr.c.
References bool, css_send_data_to_client(), DB_ROW_COUNT_NOT_SET, i, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), or_unpack_ptr(), stran_server_commit_internal(), xqmgr_end_query(), and xsession_set_row_count().
Referenced by net_server_init().
STATIC_INLINE TRAN_STATE stran_server_commit_internal (THREAD_ENTRY * thread_p, unsigned int rid, bool retain_lock, bool * should_conn_reset)
Definition at line 143 of file network_interface_sr.c.
References assert, logtb_has_updated(), net_cleanup_server_queues(), NULL, return_error_to_client(), STATIC_INLINE, TRAN_UNACTIVE_COMMITTED, TRAN_UNACTIVE_COMMITTED_INFORMING_PARTICIPANTS, xtran_server_commit(), and xtran_should_connection_reset().
Referenced by stran_server_auto_commit_or_abort(), and stran_server_commit().
void stran_server_end_topop (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 2849 of file network_interface_sr.c.
References css_send_data_to_client(), OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_LOG_LSA_ALIGNED_SIZE, or_pack_int(), or_pack_log_lsa(), or_unpack_int(), and xtran_server_end_topop().
Referenced by net_server_init().
void stran_server_get_global_tran_info (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 3070 of file network_interface_sr.c.
References css_send_abort_to_client(), css_send_reply_and_data_to_client(), ER_FAILED, free_and_init, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), return_error_to_client(), success(), and xtran_server_get_global_tran_info().
Referenced by net_server_init().
void stran_server_has_updated (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 2794 of file network_interface_sr.c.
References css_send_data_to_client(), OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), and xtran_server_has_updated().
Referenced by net_server_init().
void stran_server_is_active_and_has_updated (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 2950 of file network_interface_sr.c.
References css_send_data_to_client(), OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), and xtran_server_is_active_and_has_updated().
Referenced by net_server_init().
void stran_server_partial_abort (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 2915 of file network_interface_sr.c.
References css_send_data_to_client(), OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_LOG_LSA_ALIGNED_SIZE, or_pack_int(), or_pack_log_lsa(), or_unpack_string_nocopy(), return_error_to_client(), TRAN_UNACTIVE_ABORTED, and xtran_server_partial_abort().
Referenced by net_server_init().
void stran_server_savepoint (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 2881 of file network_interface_sr.c.
References css_send_data_to_client(), ER_FAILED, NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_LOG_LSA_ALIGNED_SIZE, or_pack_int(), or_pack_log_lsa(), or_unpack_string_nocopy(), return_error_to_client(), success(), and xtran_server_savepoint().
Referenced by net_server_init().
void stran_server_set_global_tran_info (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 3025 of file network_interface_sr.c.
References ARG_FILE_LINE, css_receive_data_from_client(), css_send_abort_to_client(), css_send_data_to_client(), ER_ERROR_SEVERITY, ER_FAILED, ER_NET_SERVER_DATA_RECEIVE, er_set(), free_and_init, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), return_error_to_client(), success(), and xtran_server_set_global_tran_info().
Referenced by net_server_init().
void stran_server_start_topop (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 2818 of file network_interface_sr.c.
References css_send_data_to_client(), ER_FAILED, NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_LOG_LSA_ALIGNED_SIZE, or_pack_int(), or_pack_log_lsa(), return_error_to_client(), success(), and xtran_server_start_topop().
Referenced by net_server_init().
void stran_wait_server_active_trans (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 2974 of file network_interface_sr.c.
References css_send_data_to_client(), OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), and xtran_wait_server_active_trans().
Referenced by net_server_init().
void svacuum (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 9334 of file network_interface_sr.c.
References css_send_data_to_client(), err, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), return_error_to_client(), and xvacuum().
Referenced by net_server_init().
void svacuum_dump (THREAD_ENTRY * thread_p, unsigned int rid, char * request, int reqlen)
Definition at line 9369 of file network_interface_sr.c.
References ARG_FILE_LINE, css_send_abort_to_client(), css_send_data_to_client(), db_private_alloc, db_private_free_and_init, ER_ERROR_SEVERITY, ER_GENERIC_ERROR, er_set_with_oserror(), NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), and xvacuum_dump().
Referenced by net_server_init().
int xcallback_console_print (THREAD_ENTRY * thread_p, char * print_str)
Definition at line 7125 of file network_interface_sr.c.
References ARG_FILE_LINE, CONSOLE_OUTPUT, css_get_comm_request_id(), css_send_reply_and_data_to_client(), db_private_alloc, db_private_free_and_init, ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_pack_string_with_length(), or_packed_string_length(), and rc.
Referenced by btree_repair_prev_link_by_btid(), and xboot_checkdb_table().
int xio_send_user_prompt_to_client (THREAD_ENTRY * thread_p, FILEIO_REMOTE_PROMPT_TYPE prompt_id, const char * prompt, const char * failure_prompt, int range_low, int range_high, const char * secondary_prompt, int reprompt_value)
Definition at line 7180 of file network_interface_sr.c.
References ASYNC_OBTAIN_USER_INPUT, css_get_comm_request_id(), css_send_reply_and_data_to_client(), db_private_alloc, db_private_free_and_init, ER_FAILED, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_pack_string_with_length(), or_packed_string_length(), and rc.
Referenced by fileio_request_user_response().
int xlog_get_page_request_with_reply (THREAD_ENTRY * thread_p, LOG_PAGEID * fpageid_ptr, LOGWR_MODE * mode_ptr, int timeout)
Definition at line 7275 of file network_interface_sr.c.
References ARG_FILE_LINE, assert, er_log_debug, error(), free_and_init, LOGWR_MODE_ASYNC, LOGWR_MODE_SYNC, mode, NO_ERROR, NULL, or_unpack_int(), or_unpack_int64(), and xs_receive_data_from_client_with_timeout().
Referenced by logwr_log_ha_filestat_to_string().
int xlog_send_log_pages_to_client (THREAD_ENTRY * thread_p, char * logpg_area, int area_size, LOGWR_MODE mode)
Definition at line 7238 of file network_interface_sr.c.
References ARG_FILE_LINE, css_get_comm_request_id(), css_send_reply_and_data_to_client(), ER_FAILED, er_log_debug, GET_NEXT_LOG_PAGES, NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), and rc.
Referenced by logwr_log_ha_filestat_to_string().
int xs_receive_data_from_client (THREAD_ENTRY * thread_p, char ** area, int * datasize)
Definition at line 6409 of file network_interface_sr.c.
References xs_receive_data_from_client_with_timeout().
Referenced by fileio_request_user_response(), and method_clear_scan_buffer().
int xs_receive_data_from_client_with_timeout (THREAD_ENTRY * thread_p, char ** area, int * datasize, int timeout)
Definition at line 6426 of file network_interface_sr.c.
References ARG_FILE_LINE, css_get_comm_request_id(), css_receive_data_from_client_with_timeout(), ER_ERROR_SEVERITY, ER_FAILED, ER_INTERRUPTED, ER_NET_DATA_RECEIVE_TIMEDOUT, ER_NET_SERVER_DATA_RECEIVE, er_set(), free_and_init, logtb_is_interrupted(), NO_ERROR, rc, and TIMEDOUT_ON_QUEUE.
Referenced by xlog_get_page_request_with_reply(), and xs_receive_data_from_client().
int xs_send_action_to_client (THREAD_ENTRY * thread_p, VACOMM_BUFFER_CLIENT_ACTION action)
Definition at line 6470 of file network_interface_sr.c.
References ARG_FILE_LINE, css_get_comm_request_id(), css_send_data_to_client(), ER_ERROR_SEVERITY, ER_FAILED, ER_INTERRUPTED, er_set(), logtb_is_interrupted(), NO_ERROR, OR_ALIGNED_BUF, OR_ALIGNED_BUF_START, OR_INT_SIZE, and or_pack_int().
Referenced by method_clear_scan_buffer().
int xs_send_method_call_info_to_client (THREAD_ENTRY * thread_p, qfile_list_id * list_id, method_sig_list * methsg_list)
Definition at line 6365 of file network_interface_sr.c.
References css_get_comm_request_id(), css_send_reply_and_data_to_client(), db_private_alloc, db_private_free_and_init, ER_FAILED, METHOD_CALL, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_listid_length(), or_method_sig_list_length(), or_pack_int(), or_pack_listid(), and or_pack_method_sig_list().
Referenced by method_scan_next().
Variable Documentation
unsigned int db_on_server = 1
Definition at line 105 of file network_interface_sr.c.
Referenced by check_set_object(), db_change_private_heap(), db_create_private_heap(), db_private_alloc_debug(), db_private_free_debug(), db_private_realloc_debug(), db_replace_private_heap(), fileio_request_user_response(), mr_data_lengthval_nchar(), mr_data_readval_object(), mr_data_writeval_object(), mr_initval_object(), mr_lengthval_varnchar_internal(), mr_readval_nchar_internal(), mr_readval_varnchar_internal(), mr_setval_object(), mr_writeval_nchar_internal(), mr_writeval_varnchar_internal(), swizzle_value(), tp_domain_check_class(), tp_domain_select(), and ws_pin().