CUBRID Engine: src/communication/network_interface_cl.h File Reference
network_interface_cl.h File Reference
#include <stdio.h>
#include "dbtype_def.h"
#include "lob_locator.hpp"
#include "replication.h"
#include "server_interface.h"
#include "perf_monitor.h"
#include "storage_common.h"
#include "object_domain.h"
#include "query_list.h"
#include "query_monitoring.hpp"
#include "statistics.h"
#include "connection_defs.h"
#include "log_writer.h"
#include "language_support.h"
#include "log_common_impl.h"
#include "parse_tree.h"
#include "load_common.hpp"
#include "timezone_lib_common.h"
Classes
struct one_tran_info
struct trans_info
Typedefs
typedef struct one_tran_info ONE_TRAN_INFO
typedef struct trans_info TRANS_INFO
Functions
int locator_fetch (OID *oidp, int chn, LOCK lock, LC_FETCH_VERSION_TYPE fetch_type, OID *class_oid, int class_chn, int prefetch, LC_COPYAREA **fetch_copyarea)
int locator_get_class (OID *class_oid, int class_chn, const OID *oid, LOCK lock, int prefetching, LC_COPYAREA **fetch_copyarea)
int locator_fetch_all (const HFID *hfid, LOCK *lock, LC_FETCH_VERSION_TYPE fetch_version_type, OID *class_oidp, int *nobjects, int *nfetched, OID *last_oidp, LC_COPYAREA **fetch_copyarea)
int locator_does_exist (OID *oidp, int chn, LOCK lock, OID *class_oid, int class_chn, int need_fetching, int prefetch, LC_COPYAREA **fetch_copyarea, LC_FETCH_VERSION_TYPE fetch_version_type)
int locator_notify_isolation_incons (LC_COPYAREA **synch_copyarea)
int locator_force (LC_COPYAREA *copy_area, int num_ignore_error_list, int *ignore_error_list, int content_size)
int locator_repl_force (LC_COPYAREA *copy_area, LC_COPYAREA **reply_copy_area)
int locator_fetch_lockset (LC_LOCKSET *lockset, LC_COPYAREA **fetch_copyarea)
int locator_fetch_all_reference_lockset (OID *oid, int chn, OID *class_oid, int class_chn, LOCK lock, int quit_on_errors, int prune_level, LC_LOCKSET **lockset, LC_COPYAREA **fetch_copyarea)
LC_FIND_CLASSNAME locator_find_class_oid (const char *class_name, OID *class_oid, LOCK lock)
LC_FIND_CLASSNAME locator_reserve_class_names (const int num_classes, const char **class_names, OID *class_oids)
int locator_get_reserved_class_name_oid (const char *classname, OID *class_oid)
LC_FIND_CLASSNAME locator_delete_class_name (const char *class_name)
LC_FIND_CLASSNAME locator_rename_class_name (const char *old_name, const char *new_name, OID *class_oid)
int locator_assign_oid (const HFID *hfid, OID *perm_oid, int expected_length, OID *class_oid, const char *class_name)
int locator_assign_oid_batch (LC_OIDSET *oidset)
LC_FIND_CLASSNAME locator_find_lockhint_class_oids (int num_classes, const char **many_classnames, LOCK *many_locks, int *many_need_subclasses, LC_PREFETCH_FLAGS *many_flags, OID *guessed_class_oids, int *guessed_class_chns, int quit_on_errors, LOCK lock_rr_tran, LC_LOCKHINT **lockhint, LC_COPYAREA **fetch_copyarea)
int locator_fetch_lockhint_classes (LC_LOCKHINT *lockhint, LC_COPYAREA **fetch_area)
int locator_check_fk_validity (OID *cls_oid, HFID *hfid, TP_DOMAIN *key_type, int n_attrs, int *attr_ids, OID *pk_cls_oid, BTID *pk_btid, char *fk_name)
int locator_prefetch_repl_insert (OID *class_oid, RECDES *recdes)
int heap_create (HFID *hfid, const OID *class_oid, bool reuse_oid)
int heap_destroy_newly_created (const HFID *hfid, const OID *class_oid)
int heap_reclaim_addresses (const HFID *hfid)
int file_apply_tde_to_class_files (const OID *class_oid)
int tde_get_mk_file_path (char *mk_path)
int tde_get_mk_info (int *mk_index, time_t *created_time, time_t *set_time)
int tde_change_mk_on_server (int mk_index)
DKNPAGES disk_get_total_numpages (VOLID volid)
DKNPAGES disk_get_free_numpages (VOLID volid)
char * disk_get_remarks (VOLID volid)
char * disk_get_fullname (VOLID volid, char *vol_fullname)
int log_reset_wait_msecs (int wait_msecs)
int log_reset_isolation (TRAN_ISOLATION isolation)
void log_set_interrupt (int set)
int log_checkpoint (void)
void log_dump_stat (FILE *outfp)
int log_set_suppress_repl_on_transaction (int set)
TRAN_STATE tran_server_commit (bool retain_lock)
TRAN_STATE tran_server_abort (void)
bool tran_is_blocked (int tran_index)
int tran_server_has_updated (void)
int tran_server_is_active_and_has_updated (void)
int tran_wait_server_active_trans (void)
int tran_server_set_global_tran_info (int gtrid, void *info, int size)
int tran_server_get_global_tran_info (int gtrid, void *buffer, int size)
int tran_server_2pc_start (void)
TRAN_STATE tran_server_2pc_prepare (void)
int tran_server_2pc_recovery_prepared (int gtrids[], int size)
int tran_server_2pc_attach_global_tran (int gtrid)
TRAN_STATE tran_server_2pc_prepare_global_tran (int gtrid)
int tran_server_savepoint (const char *savept_name, LOG_LSA *savept_lsa)
TRAN_STATE tran_server_partial_abort (const char *savept_name, LOG_LSA *savept_lsa)
const char * tran_get_tranlist_state_name (TRAN_STATE state)
void lock_dump (FILE *outfp)
void vacuum_dump (FILE *outfp)
int acl_reload (void)
void acl_dump (FILE *outfp)
int boot_initialize_server (const BOOT_CLIENT_CREDENTIAL *client_credential, BOOT_DB_PATH_INFO *db_path_info, bool db_overwrite, const char *file_addmore_vols, DKNPAGES db_npages, PGLENGTH db_desired_pagesize, DKNPAGES log_npages, PGLENGTH db_desired_log_page_size, OID *rootclass_oid, HFID *rootclass_hfid, int client_lock_wait, TRAN_ISOLATION client_isolation)
int boot_register_client (BOOT_CLIENT_CREDENTIAL *client_credential, int client_lock_wait, TRAN_ISOLATION client_isolation, TRAN_STATE *tran_state, BOOT_SERVER_CREDENTIAL *server_credential)
int boot_unregister_client (int tran_index)
int boot_backup (const char *backup_path, FILEIO_BACKUP_LEVEL backup_level, bool delete_unneeded_logarchives, const char *backup_verbose_file, int num_threads, FILEIO_ZIP_METHOD zip_method, FILEIO_ZIP_LEVEL zip_level, int skip_activelog, int sleep_msecs, bool separate_keys)
VOLID boot_add_volume_extension (DBDEF_VOL_EXT_INFO *ext_info)
int boot_check_db_consistency (int check_flag, OID *oids, int num_oids, BTID *idx_btid)
int boot_find_number_permanent_volumes (void)
int boot_find_number_temp_volumes (void)
VOLID boot_find_last_permanent (void)
int boot_find_last_temp (void)
int boot_delete (const char *db_name, bool force_delete)
bool boot_shutdown_server (ER_FINAL_CODE iserfinal)
int boot_soft_rename (const char *old_db_name, const char *new_db_name, const char *new_db_path, const char *new_log_path, const char *new_db_server_host, const char *new_volext_path, const char *fileof_vols_and_renamepaths, bool newdb_overwrite, bool extern_rename, bool force_delete)
int boot_copy (const char *from_dbname, const char *new_db_name, const char *new_db_path, const char *new_log_path, const char *new_lob_path, const char *new_db_server_host, const char *new_volext_path, const char *fileof_vols_and_copypaths, bool newdb_overwrite)
int boot_emergency_patch (const char *db_name, bool recreate_log, DKNPAGES log_npages, const char *db_locale, FILE *out_fp)
HA_SERVER_STATE boot_change_ha_mode (HA_SERVER_STATE state, bool force, int timeout)
int boot_notify_ha_log_applier_state (HA_LOG_APPLIER_STATE state)
int stats_get_statistics_from_server (OID *classoid, unsigned int timestamp, int *length_ptr, char **stats_buffer)
int stats_update_statistics (OID *classoid, int with_fullscan)
int stats_update_all_statistics (int with_fullscan)
int btree_add_index (BTID *btid, TP_DOMAIN *key_type, OID *class_oid, int attr_id, int unique_pk)
int btree_load_index (BTID *btid, const char *bt_name, TP_DOMAIN *key_type, OID *class_oids, int n_classes, int n_attrs, int *attr_ids, int *attrs_prefix_length, HFID *hfids, int unique_pk, int not_null_flag, OID *fk_refcls_oid, BTID *fk_refcls_pk_btid, const char *fk_name, char *pred_stream, int pred_stream_size, char *expr_stream, int expr_stream_size, int func_col_id, int func_attr_index_start, SM_INDEX_STATUS index_status)
int btree_delete_index (BTID *btid)
int locator_log_force_nologging (void)
int locator_remove_class_from_index (OID *oid, BTID *btid, HFID *hfid)
BTREE_SEARCH btree_find_unique (BTID *btid, DB_VALUE *key, OID *class_oid, OID *oid)
BTREE_SEARCH repl_btree_find_unique (BTID *btid, DB_VALUE *key, OID *class_oid, OID *oid)
BTREE_SEARCH btree_find_multi_uniques (OID *class_oid, int pruning_type, BTID *btids, DB_VALUE *keys, int count, SCAN_OPERATION_TYPE op_type, OID **oids, int *oids_count)
int btree_class_test_unique (char *buf, int buf_size)
int qfile_get_list_file_page (QUERY_ID query_id, VOLID volid, PAGEID pageid, char *buffer, int *buffer_size)
int qmgr_prepare_query (struct compile_context *context, xasl_stream *stream)
QFILE_LIST_ID * qmgr_execute_query (const XASL_ID *xasl_id, QUERY_ID *query_idp, int dbval_cnt, const DB_VALUE *dbvals, QUERY_FLAG flag, CACHE_TIME *clt_cache_time, CACHE_TIME *srv_cache_time, int query_timeout)
QFILE_LIST_ID * qmgr_prepare_and_execute_query (char *xasl_stream, int xasl_stream_size, QUERY_ID *query_id, int dbval_cnt, DB_VALUE *dbval_ptr, QUERY_FLAG flag, int query_timeout)
int qmgr_end_query (QUERY_ID query_id)
int qmgr_drop_all_query_plans (void)
void qmgr_dump_query_plans (FILE *outfp)
void qmgr_dump_query_cache (FILE *outfp)
int serial_get_next_value (DB_VALUE *value, OID *oid_p, int cached_num, int num_alloc, int is_auto_increment)
int serial_get_current_value (DB_VALUE *value, OID *oid_p, int cached_num)
int serial_decache (OID *oid)
int perfmon_server_start_stats (void)
int perfmon_server_stop_stats (void)
int perfmon_server_copy_stats (UINT64 *to_stats)
int perfmon_server_copy_global_stats (UINT64 *to_stats)
int catalog_check_rep_dir (OID *class_id, OID *rep_dir_p)
int thread_kill_tran_index (int kill_tran_index, char *kill_user, char *kill_host, int kill_pid)
int thread_kill_or_interrupt_tran (int *tran_index_list, int num_tran_index, bool is_dba_group_member, bool interrupt_only, int *num_killed)
void thread_dump_cs_stat (FILE *outfp)
int logtb_get_pack_tran_table (char **buffer_p, int *size_p, bool include_query_exec_info)
void logtb_free_trans_info (TRANS_INFO *info)
TRANS_INFO * logtb_get_trans_info (bool include_query_exec_info)
void logtb_dump_trantable (FILE *outfp)
int heap_get_class_num_objects_pages (HFID *hfid, int approximation, int *nobjs, int *npages)
int btree_get_statistics (BTID *btid, BTREE_STATS *stat_info)
int btree_get_index_key_type (BTID btid, TP_DOMAIN **key_type_p)
int db_local_transaction_id (DB_VALUE *trid)
int qp_get_server_info (PARSER_CONTEXT *parser, int server_info_bits)
int heap_has_instance (HFID *hfid, OID *class_oid, int has_visible_instance)
int locator_redistribute_partition_data (OID *class_oid, int no_oids, OID *oid_list)
int jsp_get_server_port (void)
int repl_log_get_append_lsa (LOG_LSA *lsa)
int repl_set_info (REPL_INFO *repl_info)
int logwr_get_log_pages (LOGWR_CONTEXT *ctx_ptr)
bool histo_is_supported (void)
int histo_start (bool for_all_trans)
int histo_stop (void)
int histo_print (FILE *stream)
int histo_print_global_stats (FILE *stream, bool cumulative, const char *substr)
void histo_clear (void)
int net_histo_start (bool for_all_trans)
int net_histo_stop (void)
int net_histo_print (FILE *stream)
int net_histo_print_global_stats (FILE *stream, bool cumulative, const char *substr)
void net_histo_clear (void)
int net_client_request_no_reply (int request, char *argbuf, int argsize)
int net_client_request (int request, char *argbuf, int argsize, char *replybuf, int replysize, char *databuf, int datasize, char *replydata, int replydatasize)
int net_client_request2 (int request, char *argbuf, int argsize, char *replybuf, int replysize, char *databuf, int datasize, char **replydata_ptr, int *replydatasize_ptr)
int net_client_request2_no_malloc (int request, char *argbuf, int argsize, char *replybuf, int replysize, char *databuf, int datasize, char *replydata, int *replydatasize_ptr)
int net_client_request_3_data (int request, char *argbuf, int argsize, char *databuf1, int datasize1, char *databuf2, int datasize2, char *replydata0, int replydatasize0, char *replydata1, int replydatasize1, char *replydata2, int replydatasize2)
int net_client_request_with_callback (int request, char *argbuf, int argsize, char *replybuf, int replysize, char *databuf1, int datasize1, char *databuf2, int datasize2, char **replydata_ptr1, int *replydatasize_ptr1, char **replydata_ptr2, int *replydatasize_ptr2, char **replydata_ptr3, int *replydatasize_ptr3)
int net_client_check_log_header (LOGWR_CONTEXT *ctx_ptr, char *argbuf, int argsize, char *replybuf, int replysize, char **logpg_area_buf, bool verbose)
int net_client_request_with_logwr_context (LOGWR_CONTEXT *ctx_ptr, int request, char *argbuf, int argsize, char *replybuf, int replysize, char *databuf1, int datasize1, char *databuf2, int datasize2, char **replydata_ptr1, int *replydatasize_ptr1, char **replydata_ptr2, int *replydatasize_ptr2)
void net_client_logwr_send_end_msg (int rc, int error)
int net_client_get_next_log_pages (int rc, char *replybuf, int replysize, int length)
int net_client_request_recv_copyarea (int request, char *argbuf, int argsize, char *replybuf, int replysize, LC_COPYAREA **reply_copy_area)
int net_client_request_2recv_copyarea (int request, char *argbuf, int argsize, char *replybuf, int replysize, char *databuf, int datasize, char *recvbuffer, int recvbuffer_size, LC_COPYAREA **reply_copy_area, int *eid)
int net_client_recv_copyarea (int request, char *replybuf, int replysize, char *recvbuffer, int recvbuffer_size, LC_COPYAREA **reply_copy_area, int eid)
int net_client_request_3_data_recv_copyarea (int request, char *argbuf, int argsize, char *databuf1, int datasize1, char *databuf2, int datasize2, char *replybuf, int replysize, LC_COPYAREA **reply_copy_area)
int net_client_request_3recv_copyarea (int request, char *argbuf, int argsize, char *replybuf, int replysize, char *databuf, int datasize, char **recvbuffer, int *recvbuffer_size, LC_COPYAREA **reply_copy_area)
int net_client_request_recv_stream (int request, char *argbuf, int argsize, char *replybuf, int replybuf_size, char *databuf, int datasize, FILE *outfp)
int net_client_ping_server (int client_val, int *server_val, int timeout)
int net_client_ping_server_with_handshake (int client_type, bool check_capabilities, int opt_cap)
int net_client_init (const char *dbname, const char *hostname)
int net_client_final (void)
void net_cleanup_client_queues (void)
int net_client_send_data (char *host, unsigned int rc, char *databuf, int datasize)
int net_client_receive_action (int rc, int *action)
char * net_client_get_server_host (void)
int boot_compact_classes (OID **class_oids, int num_classes, int space_to_process, int instance_lock_timeout, int class_lock_timeout, bool delete_old_repr, OID *last_processed_class_oid, OID *last_processed_oid, int *total_objects, int *failed_objects, int *modified_objects, int *big_objects, int *ids_repr)
int boot_heap_compact (OID *class_oid)
int compact_db_start (void)
int compact_db_stop (void)
int es_posix_create_file (char *new_path)
ssize_t es_posix_write_file (const char *path, const void *buf, size_t count, off_t offset)
ssize_t es_posix_read_file (const char *path, void *buf, size_t count, off_t offset)
int es_posix_delete_file (const char *path)
int es_posix_copy_file (const char *src_path, const char *metaname, char *new_path)
int es_posix_rename_file (const char *src_path, const char *metaname, char *new_path)
off_t es_posix_get_file_size (const char *path)
int locator_upgrade_instances_domain (OID *class_oid, int attribute_id)
int boot_get_server_locales (LANG_COLL_COMPAT **server_collations, LANG_LOCALE_COMPAT **server_locales, int *server_coll_cnt, int *server_locales_cnt)
int boot_get_server_timezone_checksum (char *timezone_checksum)
int csession_find_or_create_session (SESSION_ID *session_id, int *row_count, char *server_session_key, const char *db_user, const char *host, const char *program_name)
int csession_end_session (SESSION_ID session_id)
int csession_set_row_count (int rows)
int csession_get_row_count (int *rows)
int csession_get_last_insert_id (DB_VALUE *value, bool update_last_insert_id)
int csession_reset_cur_insert_id (void)
int csession_create_prepared_statement (const char *name, const char *alias_print, char *stmt_info, int info_length)
int csession_get_prepared_statement (const char *name, XASL_ID *xasl_id, char **stmt_info, xasl_node_header *xasl_header_p)
int csession_delete_prepared_statement (const char *name)
int clogin_user (const char *username)
int csession_set_session_variables (DB_VALUE *variables, const int count)
int csession_get_variable (DB_VALUE *name, DB_VALUE *value)
int csession_drop_session_variables (DB_VALUE *variables, const int count)
int cvacuum (void)
int log_get_mvcc_snapshot (void)
int tran_lock_rep_read (LOCK lock_rr_tran)
int chksum_insert_repl_log_and_demote_table_lock (REPL_INFO *repl_info, const OID *class_oidp)
int log_does_active_user_exist (const char *user_name, bool *existed)
int netcl_spacedb (SPACEDB_ALL *spaceall, SPACEDB_ONEVOL **spacevols, SPACEDB_FILES *spacefiles)
int locator_demote_class_lock (const OID *class_oid, LOCK lock, LOCK *ex_lock)
int loaddb_init (cubload::load_args &args)
int loaddb_install_class (const cubload::batch &batch, bool &class_is_ignored, std::string &class_name)
int loaddb_load_batch (const cubload::batch &batch, bool use_temp_batch, bool &is_batch_accepted, load_status &status)
int loaddb_fetch_status (load_status &status)
int loaddb_destroy ()
int loaddb_interrupt ()
int loaddb_update_stats ()
Typedef Documentation
typedef struct one_tran_info ONE_TRAN_INFO
Definition at line 62 of file network_interface_cl.h.
typedef struct trans_info TRANS_INFO
Definition at line 75 of file network_interface_cl.h.
Function Documentation
void acl_dump (FILE * outfp)
Definition at line 3567 of file network_interface_cl.c.
References net_client_request_recv_stream(), NET_SERVER_ACL_DUMP, and NULL.
Referenced by acldb().
int acl_reload (void)
Definition at line 3536 of file network_interface_cl.c.
References ER_NET_CLIENT_DATA_RECEIVE, error(), net_client_request(), NET_SERVER_ACL_RELOAD, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, and or_unpack_errcode().
Referenced by acldb().
VOLID boot_add_volume_extension (DBDEF_VOL_EXT_INFO * ext_info)
Definition at line 3901 of file network_interface_cl.c.
References ARG_FILE_LINE, dbdef_vol_ext_info::comments, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, dbdef_vol_ext_info::max_npages, dbdef_vol_ext_info::max_writesize_in_sec, dbdef_vol_ext_info::name, net_client_request(), NET_SERVER_BO_ADD_VOLEXT, NULL, NULL_VOLID, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), dbdef_vol_ext_info::overwrite, dbdef_vol_ext_info::path, dbdef_vol_ext_info::purpose, and xboot_add_volume_extension().
Referenced by db_add_volume_ex().
int boot_backup (const char * backup_path, FILEIO_BACKUP_LEVEL backup_level, bool delete_unneeded_logarchives, const char * backup_verbose_file, int num_threads, FILEIO_ZIP_METHOD zip_method, FILEIO_ZIP_LEVEL zip_level, int skip_activelog, int sleep_msecs, bool separate_keys)
Definition at line 3826 of file network_interface_cl.c.
References ARG_FILE_LINE, d1, ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, net_client_request_with_callback(), NET_SERVER_BO_BACKUP, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), success(), and xboot_backup().
Referenced by backupdb().
HA_SERVER_STATE boot_change_ha_mode (HA_SERVER_STATE state, bool force, int timeout)
Definition at line 5347 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_NOT_IN_STANDALONE, er_set(), HA_SERVER_STATE_NA, net_client_request(), NET_SERVER_BO_CHANGE_HA_MODE, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), and or_unpack_int().
Referenced by changemode(), and css_ha_server_state().
int boot_check_db_consistency (int check_flag, OID * oids, int num_oids, BTID * idx_btid)
Definition at line 3966 of file network_interface_cl.c.
References ARG_FILE_LINE, d1, ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, i, net_client_request_with_callback(), NET_SERVER_BO_CHECK_DBCONSISTENCY, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_BTID_ALIGNED_SIZE, OR_INT_SIZE, OR_OID_SIZE, or_pack_btid(), or_pack_int(), or_pack_oid(), or_unpack_int(), success(), and xboot_check_db_consistency().
Referenced by backupdb(), and checkdb().
int boot_compact_classes (OID ** class_oids, int num_classes, int space_to_process, int instance_lock_timeout, int class_lock_timeout, bool delete_old_repr, OID * last_processed_class_oid, OID * last_processed_oid, int * total_objects, int * failed_objects, int * modified_objects, int * big_objects, int * ids_repr)
Definition at line 8989 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, ER_QPROC_INVALID_PARAMETER, er_set(), free_and_init, i, net_client_request(), NET_SERVER_BO_COMPACT_DB, NULL, OR_INT_SIZE, OR_OID_SIZE, or_pack_int(), or_pack_oid(), or_unpack_int(), or_unpack_oid(), and success().
Referenced by compactdb_start().
int boot_copy (const char * from_dbname, const char * new_db_name, const char * new_db_path, const char * new_log_path, const char * new_lob_path, const char * new_db_server_host, const char * new_volext_path, const char * fileof_vols_and_copypaths, bool newdb_overwrite)
Definition at line 5293 of file network_interface_cl.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_FAILED, ER_ONLY_IN_STANDALONE, er_set(), NULL, and xboot_copy().
Referenced by copydb().
int boot_delete (const char * db_name, bool force_delete)
Definition at line 4190 of file network_interface_cl.c.
References ARG_FILE_LINE, BOOT_SHUTDOWN_ALL_MODULES, db_name, ER_ERROR_SEVERITY, ER_FAILED, ER_ONLY_IN_STANDALONE, er_set(), NULL, xboot_delete(), and xboot_restart_from_backup().
Referenced by copydb(), and deletedb().
int boot_emergency_patch (const char * db_name, bool recreate_log, DKNPAGES log_npages, const char * db_locale, FILE * out_fp)
Definition at line 5324 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_FAILED, ER_ONLY_IN_STANDALONE, er_set(), and xboot_emergency_patch().
Referenced by patchdb().
VOLID boot_find_last_permanent (void)
Definition at line 4112 of file network_interface_cl.c.
References net_client_request(), NET_SERVER_BO_FIND_LAST_PERM, NULL, NULL_VOLID, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), and xboot_find_last_permanent().
Referenced by db_last_volume().
int boot_find_last_temp (void)
Definition at line 4151 of file network_interface_cl.c.
References net_client_request(), NET_SERVER_BO_FIND_LAST_TEMP, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), and xboot_find_last_temp().
int boot_find_number_permanent_volumes (void)
Definition at line 4034 of file network_interface_cl.c.
References net_client_request(), NET_SERVER_BO_FIND_NPERM_VOLS, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), and xboot_find_number_permanent_volumes().
Referenced by db_num_volumes().
int boot_find_number_temp_volumes (void)
Definition at line 4073 of file network_interface_cl.c.
References net_client_request(), NET_SERVER_BO_FIND_NTEMP_VOLS, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), and xboot_find_number_temp_volumes().
int boot_get_server_locales (LANG_COLL_COMPAT ** server_collations, LANG_LOCALE_COMPAT ** server_locales, int * server_coll_cnt, int * server_locales_cnt)
Definition at line 9679 of file network_interface_cl.c.
References ARG_FILE_LINE, assert, lang_coll_compat::checksum, lang_locale_compat::checksum, lang_coll_compat::codeset, lang_locale_compat::codeset, lang_coll_compat::coll_id, lang_coll_compat::coll_name, ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, i, lang_locale_compat::lang_name, net_client_request2(), NET_SERVER_BO_GET_LOCALES_INFO, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), and or_unpack_string_nocopy().
Referenced by boot_get_host_name().
int boot_get_server_timezone_checksum (char * timezone_checksum)
Definition at line 9843 of file network_interface_cl.c.
References assert, error(), free_and_init, net_client_request2(), NET_SERVER_TZ_GET_CHECKSUM, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), or_unpack_string_nocopy(), and TZ_CHECKSUM_SIZE.
Referenced by boot_set_server_session_key().
int boot_heap_compact (OID * class_oid)
Definition at line 9113 of file network_interface_cl.c.
References ER_FAILED, ER_QPROC_INVALID_PARAMETER, net_client_request(), NET_SERVER_BO_HEAP_COMPACT, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_OID_SIZE, or_pack_oid(), or_unpack_int(), and success().
Referenced by compactdb_start().
int boot_initialize_server (const BOOT_CLIENT_CREDENTIAL * client_credential, BOOT_DB_PATH_INFO * db_path_info, bool db_overwrite, const char * file_addmore_vols, DKNPAGES db_npages, PGLENGTH db_desired_pagesize, DKNPAGES log_npages, PGLENGTH db_desired_log_page_size, OID * rootclass_oid, HFID * rootclass_hfid, int client_lock_wait, TRAN_ISOLATION client_isolation)
Definition at line 3639 of file network_interface_cl.c.
References assert, NULL_TRAN_INDEX, and xboot_initialize_server().
Referenced by boot_initialize_client().
int boot_notify_ha_log_applier_state (HA_LOG_APPLIER_STATE state)
Definition at line 5388 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_FAILED, ER_NOT_IN_STANDALONE, er_set(), net_client_request(), NET_SERVER_BO_NOTIFY_HA_LOG_APPLIER_STATE, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), and or_unpack_int().
Referenced by la_change_state().
int boot_register_client (BOOT_CLIENT_CREDENTIAL * client_credential, int client_lock_wait, TRAN_ISOLATION client_isolation, TRAN_STATE * tran_state, BOOT_SERVER_CREDENTIAL * server_credential)
Definition at line 3677 of file network_interface_cl.c.
References boot_server_credential::db_charset, boot_server_credential::db_full_name, boot_server_credential::db_lang, boot_server_credential::disk_compatibility, free_and_init, cubpacking::packer::get_current_size(), cubmem::extensible_block::get_ptr(), boot_server_credential::ha_server_state, boot_server_credential::host_name, boot_server_credential::lob_path, boot_server_credential::log_page_size, net_client_request2(), NET_SERVER_BO_REGISTER_CLIENT, NULL, NULL_TRAN_INDEX, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_float(), or_unpack_hfid(), or_unpack_int(), or_unpack_oid(), or_unpack_string(), boot_server_credential::page_size, boot_server_credential::process_id, boot_server_credential::root_class_hfid, boot_server_credential::root_class_oid, cubpacking::packer::set_buffer_and_pack_all(), and xboot_register_client().
Referenced by boot_restart_client().
bool boot_shutdown_server (ER_FINAL_CODE iserfinal)
Definition at line 4239 of file network_interface_cl.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_ONLY_IN_STANDALONE, er_set(), NULL, and xboot_shutdown_server().
Referenced by restoredb(), and restoreslave().
int boot_soft_rename (const char * old_db_name, const char * new_db_name, const char * new_db_path, const char * new_log_path, const char * new_db_server_host, const char * new_volext_path, const char * fileof_vols_and_renamepaths, bool newdb_overwrite, bool extern_rename, bool force_delete)
Definition at line 5249 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_FAILED, ER_ONLY_IN_STANDALONE, er_set(), and xboot_soft_rename().
Referenced by installdb(), and renamedb().
int boot_unregister_client (int tran_index)
Definition at line 3755 of file network_interface_cl.c.
References assert, BO_IS_SERVER_RESTARTED, ER_FAILED, net_client_request(), NET_SERVER_BO_UNREGISTER_CLIENT, NO_ERROR, NULL, NULL_TRAN_INDEX, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), and xboot_unregister_client().
Referenced by boot_shutdown_client().
int btree_add_index (BTID * btid, TP_DOMAIN * key_type, OID * class_oid, int attr_id, int unique_pk)
Definition at line 5584 of file network_interface_cl.c.
References ARG_FILE_LINE, assert, domain_size(), er_errid(), ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, net_client_request(), NET_SERVER_BTREE_ADDINDEX, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_BTID_ALIGNED_SIZE, OR_INT_SIZE, OR_OID_SIZE, or_pack_btid(), or_pack_domain(), or_pack_int(), or_pack_oid(), or_packed_domain_size(), or_unpack_btid(), or_unpack_int(), and xbtree_add_index().
Referenced by allocate_index().
int btree_class_test_unique (char * buf, int buf_size)
Definition at line 6285 of file network_interface_cl.c.
References ER_FAILED, net_client_request(), NET_SERVER_BTREE_CLASS_UNIQUE_TEST, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), success(), and xbtree_class_test_unique().
Referenced by sm_class_check_uniques().
int btree_delete_index (BTID * btid)
Definition at line 5897 of file network_interface_cl.c.
References ER_FAILED, net_client_request(), NET_SERVER_BTREE_DELINDEX, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_BTID_ALIGNED_SIZE, OR_INT_SIZE, or_pack_btid(), or_unpack_int(), success(), and xbtree_delete_index().
Referenced by deallocate_index().
BTREE_SEARCH btree_find_multi_uniques (OID * class_oid, int pruning_type, BTID * btids, DB_VALUE * keys, int count, SCAN_OPERATION_TYPE op_type, OID ** oids, int * oids_count)
Definition at line 6115 of file network_interface_cl.c.
References ARG_FILE_LINE, assert, BTREE_ERROR_OCCURRED, BTREE_KEY_FOUND, BTREE_KEY_NOTFOUND, cleanup(), cubregex::count(), db_private_free, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, i, net_client_request2(), NET_SERVER_BTREE_FIND_MULTI_UNIQUES, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_BTID_ALIGNED_SIZE, OR_INT_SIZE, OR_OID_SIZE, or_pack_btid(), or_pack_int(), or_pack_oid(), or_pack_value(), or_unpack_int(), or_unpack_oid(), OR_VALUE_ALIGNED_SIZE, and xbtree_find_multi_uniques().
Referenced by do_find_unique_constraint_violations().
BTREE_SEARCH btree_find_unique (BTID * btid, DB_VALUE * key, OID * class_oid, OID * oid)
Definition at line 6029 of file network_interface_cl.c.
References ARG_FILE_LINE, BTREE_ERROR_OCCURRED, CAST_BUFLEN, ER_ERROR_SEVERITY, ER_OBJ_INVALID_ARGUMENTS, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, net_client_request(), NET_SERVER_BTREE_FIND_UNIQUE, NULL, OID_SET_NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_BTID_ALIGNED_SIZE, OR_INT_SIZE, OR_OID_SIZE, or_pack_btid(), or_pack_oid(), or_pack_value(), or_unpack_int(), or_unpack_oid(), OR_VALUE_ALIGNED_SIZE, S_SELECT_WITH_LOCK, and xbtree_find_unique().
Referenced by find_unique(), obj_find_object_by_cons_and_key(), and obj_find_object_by_pkey().
int btree_get_index_key_type (BTID btid, TP_DOMAIN ** key_type_p)
Definition at line 8068 of file network_interface_cl.c.
References assert_release, BTID_IS_NULL, error(), free_and_init, net_client_request2(), NET_SERVER_BTREE_GET_KEY_TYPE, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_BTID_ALIGNED_SIZE, OR_INT_SIZE, or_pack_btid(), or_unpack_domain(), or_unpack_int(), and xbtree_get_key_type().
Referenced by pt_bind_names_post().
int btree_get_statistics (BTID * btid, BTREE_STATS * stat_info)
Definition at line 7998 of file network_interface_cl.c.
References assert_release, btree_stats::btid, BTID_COPY, BTID_IS_NULL, btree_get_stats(), ER_FAILED, btree_stats::height, btree_stats::keys, btree_stats::leafs, net_client_request(), NET_SERVER_BTREE_GET_STATISTICS, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_BTID_ALIGNED_SIZE, OR_INT_SIZE, or_pack_btid(), or_unpack_int(), btree_stats::pages, btree_stats::pkeys, btree_stats::pkeys_size, STATS_WITH_SAMPLING, and success().
Referenced by db_get_btree_statistics().
int btree_load_index (BTID * btid, const char * bt_name, TP_DOMAIN * key_type, OID * class_oids, int n_classes, int n_attrs, int * attr_ids, int * attrs_prefix_length, HFID * hfids, int unique_pk, int not_null_flag, OID * fk_refcls_oid, BTID * fk_refcls_pk_btid, const char * fk_name, char * pred_stream, int pred_stream_size, char * expr_stream, int expr_stream_size, int func_col_id, int func_attr_index_start, SM_INDEX_STATUS index_status)
Definition at line 5671 of file network_interface_cl.c.
References ARG_FILE_LINE, assert, BTID_IS_NULL, domain_size(), er_errid(), ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, i, ib_get_thread_count(), net_client_request(), NET_SERVER_BTREE_LOADINDEX, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_BTID_ALIGNED_SIZE, OR_HFID_SIZE, OR_INT_SIZE, OR_OID_SIZE, or_pack_btid(), or_pack_domain(), or_pack_hfid(), or_pack_int(), or_pack_oid(), or_pack_string_with_length(), or_packed_domain_size(), or_packed_string_length(), or_unpack_btid(), or_unpack_int(), SCH_M_LOCK, SM_ONLINE_INDEX_BUILDING_IN_PROGRESS, sm_Root_class_mop, ws_mop(), ws_set_lock(), xbtree_load_index(), and xbtree_load_online_index().
Referenced by allocate_index(), and sm_load_online_index().
int catalog_check_rep_dir (OID * class_id, OID * rep_dir_p)
Definition at line 7497 of file network_interface_cl.c.
References ER_FAILED, net_client_request(), NET_SERVER_CT_CHECK_REP_DIR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_OID_SIZE, or_pack_oid(), or_unpack_int(), or_unpack_oid(), success(), and xcatalog_check_rep_dir().
Referenced by sm_check_catalog_rep_dir().
int chksum_insert_repl_log_and_demote_table_lock (REPL_INFO * repl_info, const OID * class_oidp)
Definition at line 9897 of file network_interface_cl.c.
References ARG_FILE_LINE, repl_info_statement::db_user, ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, repl_info::info, repl_info_statement::name, net_client_request(), NET_SERVER_CHKSUM_REPL, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_OID_SIZE, or_pack_int(), or_pack_oid(), or_unpack_int(), repl_info::repl_info_type, REPL_INFO_TYPE_SBR, repl_info_statement::statement_type, repl_info_statement::stmt_text, success(), repl_info_statement::sys_prm_context, and xchksum_insert_repl_log_and_demote_table_lock().
Referenced by chksum_set_repl_info_and_demote_table_lock().
int clogin_user (const char * username)
Definition at line 4974 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, net_client_request(), NET_SERVER_AU_LOGIN_USER, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), and xlogin_user().
Referenced by au_login_method().
int compact_db_start (void)
Definition at line 9156 of file network_interface_cl.c.
References ER_FAILED, net_client_request(), NET_SERVER_BO_COMPACT_DB_START, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), and success().
Referenced by compactdb_start().
int compact_db_stop (void)
Definition at line 9185 of file network_interface_cl.c.
References ER_FAILED, net_client_request(), NET_SERVER_BO_COMPACT_DB_STOP, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), and success().
Referenced by compactdb_start().
int csession_create_prepared_statement (const char * name, const char * alias_print, char * stmt_info, int info_length)
Definition at line 4647 of file network_interface_cl.c.
References ARG_FILE_LINE, ASSERT_ERROR, cleanup(), ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, net_client_request(), NET_SERVER_SES_CREATE_PREPARED_STATEMENT, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_pack_sha1(), OR_SHA1_SIZE, or_unpack_int(), SHA1_HASH_INITIALIZER, SHA1Compute(), strlen, and xsession_create_prepared_statement().
Referenced by do_process_prepare_statement().
int csession_delete_prepared_statement (const char * name)
Definition at line 4920 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, net_client_request(), NET_SERVER_SES_DELETE_PREPARED_STATEMENT, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), and xsession_delete_prepared_statement().
Referenced by do_process_deallocate_prepare(), and do_process_prepare_statement().
int csession_drop_session_variables (DB_VALUE * variables, const int count)
Definition at line 5098 of file network_interface_cl.c.
References ARG_FILE_LINE, cleanup(), cubregex::count(), ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), err, free_and_init, i, net_client_request(), NET_SERVER_SES_DROP_SESSION_VARIABLES, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_db_value(), or_pack_int(), or_unpack_int(), OR_VALUE_ALIGNED_SIZE, and xsession_drop_session_variables().
Referenced by do_drop_session_variables().
int csession_end_session (SESSION_ID session_id)
Definition at line 4405 of file network_interface_cl.c.
References ER_FAILED, net_client_request(), NET_SERVER_SES_END_SESSION, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), and xsession_end_session().
Referenced by db_end_session().
int csession_find_or_create_session (SESSION_ID * session_id, int * row_count, char * server_session_key, const char * db_user, const char * host, const char * program_name)
Definition at line 4268 of file network_interface_cl.c.
References ARG_FILE_LINE, assert, DB_EMPTY_SESSION, db_Session_id, er_errid(), ER_ERROR_SEVERITY, ER_FAILED, ER_GENERIC_ERROR, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, net_client_request2(), NET_SERVER_SES_CHECK_SESSION, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_pack_stream(), or_packed_stream_length(), or_unpack_int(), or_unpack_stream(), SERVER_SESSION_KEY_SIZE, sysprm_free_session_parameters(), sysprm_pack_session_parameters(), sysprm_packed_session_parameters_length(), sysprm_unpack_session_parameters(), xsession_check_session(), xsession_create_new(), and xsession_get_row_count().
Referenced by db_find_or_create_session().
int csession_get_last_insert_id (DB_VALUE * value, bool update_last_insert_id)
Definition at line 4541 of file network_interface_cl.c.
References cleanup(), db_make_null(), ER_FAILED, free_and_init, net_client_request2(), NET_SERVER_SES_GET_LAST_INSERT_ID, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), or_unpack_value(), and xsession_get_last_insert_id().
Referenced by db_get_last_insert_id(), and pt_evaluate_db_value_expr().
int csession_get_prepared_statement (const char * name, XASL_ID * xasl_id, char ** stmt_info, xasl_node_header * xasl_header_p)
Definition at line 4818 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_GENERIC_ERROR, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, INIT_XASL_NODE_HEADER, net_client_request2(), NET_SERVER_SES_GET_PREPARED_STATEMENT, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_pack_string_with_length(), or_packed_string_length(), or_unpack_int(), or_unpack_string_alloc(), OR_UNPACK_XASL_ID, OR_UNPACK_XASL_NODE_HEADER, OR_XASL_ID_SIZE, and xsession_get_prepared_statement().
Referenced by do_get_prepared_statement_info().
int csession_get_row_count (int * rows)
Definition at line 4498 of file network_interface_cl.c.
References ER_FAILED, net_client_request(), NET_SERVER_SES_GET_ROW_COUNT, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), and xsession_get_row_count().
Referenced by db_get_row_count().
int csession_get_variable (DB_VALUE * name, DB_VALUE * value)
Definition at line 5167 of file network_interface_cl.c.
References ARG_FILE_LINE, assert, cleanup(), db_make_null(), ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), err, free_and_init, net_client_request2(), NET_SERVER_SES_GET_SESSION_VARIABLE, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_db_value(), or_unpack_db_value(), or_unpack_int(), OR_VALUE_ALIGNED_SIZE, pr_clone_value(), and xsession_get_session_variable_no_copy().
Referenced by db_get_variable().
int csession_reset_cur_insert_id (void)
Definition at line 4606 of file network_interface_cl.c.
References ER_FAILED, net_client_request(), NET_SERVER_SES_RESET_CUR_INSERT_ID, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), and xsession_reset_cur_insert_id().
Referenced by insert_local().
int csession_set_row_count (int rows)
Definition at line 4451 of file network_interface_cl.c.
References ER_FAILED, net_client_request(), NET_SERVER_SES_SET_ROW_COUNT, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), and xsession_set_row_count().
int csession_set_session_variables (DB_VALUE * variables, const int count)
Definition at line 5029 of file network_interface_cl.c.
References ARG_FILE_LINE, cleanup(), cubregex::count(), ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), err, free_and_init, i, net_client_request(), NET_SERVER_SES_SET_SESSION_VARIABLES, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_db_value(), or_pack_int(), or_unpack_int(), OR_VALUE_ALIGNED_SIZE, and xsession_set_session_variables().
Referenced by do_send_plan_trace_to_session(), and do_set_session_variables().
int cvacuum (void)
Definition at line 9525 of file network_interface_cl.c.
References err, net_client_request(), NET_SERVER_VACUUM, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), and xvacuum().
Referenced by do_vacuum(), and vacuumdb().
int db_local_transaction_id (DB_VALUE * trid)
Definition at line 8134 of file network_interface_cl.c.
References db_make_int(), ER_FAILED, net_client_request(), NET_SERVER_TM_LOCAL_TRANSACTION_ID, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), success(), and xtran_get_local_transaction_id().
Referenced by qp_get_server_info().
DKNPAGES disk_get_free_numpages (VOLID volid)
Definition at line 2082 of file network_interface_cl.c.
References net_client_request(), NET_SERVER_DISK_FREEPGS, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), and xdisk_get_free_numpages().
Referenced by db_freepgs().
char* disk_get_fullname (VOLID volid, char * vol_fullname)
Definition at line 2186 of file network_interface_cl.c.
References free_and_init, net_client_request2(), NET_SERVER_DISK_VLABEL, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), or_unpack_string_nocopy(), and xdisk_get_fullname().
Referenced by db_vol_label().
char* disk_get_remarks (VOLID volid)
Definition at line 2130 of file network_interface_cl.c.
References free_and_init, net_client_request2(), NET_SERVER_DISK_REMARKS, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), or_unpack_string_nocopy(), p, strdup(), and xdisk_get_remarks().
Referenced by db_get_database_comments().
DKNPAGES disk_get_total_numpages (VOLID volid)
Definition at line 2035 of file network_interface_cl.c.
References net_client_request(), NET_SERVER_DISK_TOTALPGS, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), and xdisk_get_total_numpages().
Referenced by db_totalpgs().
int es_posix_copy_file (const char * src_path, const char * metaname, char * new_path)
Definition at line 9386 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_FAILED, ER_NET_CLIENT_DATA_RECEIVE, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, net_client_request2_no_malloc(), NET_SERVER_ES_COPY_FILE, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, and or_unpack_int().
Referenced by es_copy_file().
int es_posix_create_file (char * new_path)
Definition at line 9214 of file network_interface_cl.c.
References ER_FAILED, ER_NET_CLIENT_DATA_RECEIVE, error(), net_client_request2_no_malloc(), NET_SERVER_ES_CREATE_FILE, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, and or_unpack_int().
Referenced by es_create_file().
int es_posix_delete_file (const char * path)
Definition at line 9341 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_FAILED, ER_NET_CLIENT_DATA_RECEIVE, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, net_client_request(), NET_SERVER_ES_DELETE_FILE, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), and strlen.
Referenced by es_delete_file().
off_t es_posix_get_file_size (const char * path)
Definition at line 9481 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, net_client_request(), NET_SERVER_ES_GET_FILE_SIZE, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT64_SIZE, or_unpack_int64(), and strlen.
Referenced by es_get_file_size().
ssize_t es_posix_read_file (const char * path, void * buf, size_t count, off_t offset)
Definition at line 9296 of file network_interface_cl.c.
References ARG_FILE_LINE, DB_ALIGN, ER_ERROR_SEVERITY, ER_FAILED, ER_NET_CLIENT_DATA_RECEIVE, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, MAX_ALIGNMENT, net_client_request(), NET_SERVER_ES_READ_FILE, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT64_SIZE, or_pack_int64(), or_unpack_int64(), and strlen.
Referenced by es_read_file().
int es_posix_rename_file (const char * src_path, const char * metaname, char * new_path)
Definition at line 9435 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_FAILED, ER_NET_CLIENT_DATA_RECEIVE, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, net_client_request2_no_malloc(), NET_SERVER_ES_RENAME_FILE, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, and or_unpack_int().
Referenced by es_rename_file().
ssize_t es_posix_write_file (const char * path, const void * buf, size_t count, off_t offset)
Definition at line 9249 of file network_interface_cl.c.
References ARG_FILE_LINE, DB_ALIGN, ER_ERROR_SEVERITY, ER_FAILED, ER_NET_CLIENT_DATA_RECEIVE, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, MAX_ALIGNMENT, net_client_request(), NET_SERVER_ES_WRITE_FILE, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT64_SIZE, or_pack_int64(), or_unpack_int64(), and strlen.
Referenced by es_write_file().
int file_apply_tde_to_class_files (const OID * class_oid)
Definition at line 1806 of file network_interface_cl.c.
References tde_cipher::data_keys, ER_NET_CLIENT_DATA_RECEIVE, error(), free_and_init, tde_data_key_set::log_key, net_client_request(), net_client_request2(), NET_SERVER_FILE_APPLY_TDE_TO_CLASS_FILES, NET_SERVER_TDE_GET_DATA_KEYS, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_OID_SIZE, or_pack_oid(), or_unpack_errcode(), or_unpack_int(), or_unpack_stream(), tde_data_key_set::perm_key, success(), tde_Cipher, TDE_DATA_KEY_LENGTH, tde_data_key_set::temp_key, and xfile_apply_tde_to_class_files().
Referenced by do_create_entity(), and do_create_partition().
int heap_create (HFID * hfid, const OID * class_oid, bool reuse_oid)
Definition at line 1608 of file network_interface_cl.c.
References ER_NET_CLIENT_DATA_RECEIVE, error(), net_client_request(), NET_SERVER_HEAP_CREATE, NET_SERVER_HEAP_DESTROY, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_HFID_SIZE, OR_INT_SIZE, OR_OID_SIZE, or_pack_hfid(), or_pack_int(), or_pack_oid(), or_unpack_errcode(), or_unpack_hfid(), success(), xheap_create(), and xheap_destroy().
Referenced by locator_create_heap_if_needed(), and sm_truncate_using_delete().
int heap_destroy_newly_created (const HFID * hfid, const OID * class_oid)
Definition at line 1708 of file network_interface_cl.c.
References ER_FAILED, ER_NET_CLIENT_DATA_RECEIVE, error(), net_client_request(), NET_SERVER_HEAP_DESTROY_WHEN_NEW, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_HFID_SIZE, OR_INT_SIZE, OR_OID_SIZE, or_pack_hfid(), or_pack_oid(), or_unpack_errcode(), success(), and xheap_destroy_newly_created().
Referenced by locator_remove_class(), and sm_truncate_using_delete().
int heap_get_class_num_objects_pages (HFID * hfid, int approximation, int * nobjs, int * npages)
Definition at line 7945 of file network_interface_cl.c.
References ER_FAILED, net_client_request(), NET_SERVER_HEAP_GET_CLASS_NOBJS_AND_NPAGES, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_HFID_SIZE, OR_INT_SIZE, or_pack_hfid(), or_pack_int(), or_unpack_int(), success(), and xheap_get_class_num_objects_pages().
Referenced by db_get_class_num_objs_and_pages(), and get_estimated_objs().
int heap_has_instance (HFID * hfid, OID * class_oid, int has_visible_instance)
Definition at line 8483 of file network_interface_cl.c.
References ER_FAILED, net_client_request(), NET_SERVER_HEAP_HAS_INSTANCE, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_HFID_SIZE, OR_INT_SIZE, OR_OID_SIZE, or_pack_hfid(), or_pack_int(), or_pack_oid(), or_unpack_int(), and xheap_has_instance().
Referenced by allocate_index(), check_fk_validity(), db_class_has_instance(), and do_check_for_empty_classes_in_delete().
int heap_reclaim_addresses (const HFID * hfid)
Definition at line 1758 of file network_interface_cl.c.
References ER_FAILED, ER_NET_CLIENT_DATA_RECEIVE, error(), net_client_request(), NET_SERVER_HEAP_RECLAIM_ADDRESSES, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_HFID_SIZE, OR_INT_SIZE, or_pack_hfid(), or_unpack_errcode(), success(), and xheap_reclaim_addresses().
Referenced by compactdb_start(), and do_reclaim_class_addresses().
void histo_clear (void)
Definition at line 8958 of file network_interface_cl.c.
References net_histo_clear().
bool histo_is_supported (void)
Definition at line 8904 of file network_interface_cl.c.
References prm_get_bool_value(), and PRM_ID_ENABLE_HISTO.
Referenced by csql_do_session_cmd(), csql_exit_cleanup(), csql_exit_session(), and start_csql().
int histo_print (FILE * stream)
Definition at line 8930 of file network_interface_cl.c.
References err, net_histo_print(), and NO_ERROR.
int histo_print_global_stats (FILE * stream, bool cumulative, const char * substr)
Definition at line 8944 of file network_interface_cl.c.
References err, net_histo_print_global_stats(), and NO_ERROR.
Referenced by statdump().
int histo_start (bool for_all_trans)
Definition at line 8910 of file network_interface_cl.c.
References net_histo_start().
Referenced by csql_do_session_cmd(), and statdump().
int histo_stop (void)
Definition at line 8920 of file network_interface_cl.c.
References net_histo_stop().
Referenced by csql_do_session_cmd(), csql_exit_cleanup(), csql_exit_session(), start_csql(), and statdump().
int jsp_get_server_port (void)
Definition at line 8528 of file network_interface_cl.c.
References jsp_server_port(), net_client_request(), NET_SERVER_JSP_GET_SERVER_PORT, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, and or_unpack_int().
Referenced by jsp_execute_stored_procedure().
int loaddb_destroy ()
Definition at line 10369 of file network_interface_cl.c.
References ER_FAILED, net_client_request(), NET_SERVER_LD_DESTROY, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), and rc.
Referenced by ldr_server_load().
int loaddb_fetch_status (load_status & status)
Definition at line 10335 of file network_interface_cl.c.
References ER_FAILED, free_and_init, net_client_request2(), NET_SERVER_LD_FETCH_STATUS, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), and cubload::load_status::unpack().
Referenced by ldr_server_load().
int loaddb_init (cubload::load_args & args)
Definition at line 10219 of file network_interface_cl.c.
References ER_FAILED, cubpacking::packer::get_current_size(), cubmem::extensible_block::get_ptr(), net_client_request(), NET_SERVER_LD_INIT, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), rc, and cubpacking::packer::set_buffer_and_pack_all().
Referenced by ldr_server_load().
int loaddb_install_class (const cubload::batch & batch, bool & class_is_ignored, std::string & class_name)
Definition at line 10245 of file network_interface_cl.c.
References assert, DB_MAX_IDENTIFIER_LENGTH, ER_FAILED, free_and_init, cubpacking::packer::get_current_size(), cubmem::extensible_block::get_ptr(), net_client_request2(), NET_SERVER_LD_INSTALL_CLASS, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), rc, and cubpacking::packer::set_buffer_and_pack_all().
Referenced by load_object_file().
int loaddb_interrupt ()
Definition at line 10390 of file network_interface_cl.c.
References net_client_request_no_reply(), NET_SERVER_LD_INTERRUPT, NO_ERROR, and NULL.
Referenced by ldr_server_load(), and register_signal_handlers().
int loaddb_load_batch (const cubload::batch & batch, bool use_temp_batch, bool & is_batch_accepted, load_status & status)
Definition at line 10282 of file network_interface_cl.c.
References ER_FAILED, free_and_init, cubpacking::packer::get_current_size(), cubmem::extensible_block::get_ptr(), net_client_request2(), NET_SERVER_LD_LOAD_BATCH, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), rc, cubpacking::packer::set_buffer_and_pack_all(), and cubload::load_status::unpack().
Referenced by load_object_file().
int loaddb_update_stats ()
Definition at line 10400 of file network_interface_cl.c.
References ER_FAILED, net_client_request(), NET_SERVER_LD_UPDATE_STATS, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), and rc.
Referenced by ldr_server_load().
int locator_assign_oid (const HFID * hfid, OID * perm_oid, int expected_length, OID * class_oid, const char * class_name)
Definition at line 1262 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, net_client_request(), NET_SERVER_LC_ASSIGN_OID, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_HFID_SIZE, OR_INT_SIZE, OR_OID_SIZE, or_pack_hfid(), or_pack_int(), or_pack_oid(), or_unpack_int(), or_unpack_oid(), strlen, success(), and xlocator_assign_oid().
Referenced by locator_assign_permanent_oid().
int locator_assign_oid_batch (LC_OIDSET * oidset)
Definition at line 1320 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, locator_get_packed_oid_set_size(), locator_pack_oid_set(), locator_unpack_oid_set_to_exist(), net_client_request(), NET_SERVER_LC_ASSIGN_OID_BATCH, NO_ERROR, NULL, OR_INT_SIZE, or_pack_int(), or_unpack_int(), success(), and xlocator_assign_oid_batch().
Referenced by locator_assign_oidset().
int locator_check_fk_validity (OID * cls_oid, HFID * hfid, TP_DOMAIN * key_type, int n_attrs, int * attr_ids, OID * pk_cls_oid, BTID * pk_btid, char * fk_name)
Definition at line 8700 of file network_interface_cl.c.
References ARG_FILE_LINE, domain_size(), ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, i, net_client_request(), NET_SERVER_LC_CHECK_FK_VALIDITY, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_BTID_ALIGNED_SIZE, OR_HFID_SIZE, OR_INT_SIZE, OR_OID_SIZE, or_pack_btid(), or_pack_domain(), or_pack_hfid(), or_pack_int(), or_pack_oid(), or_pack_string_with_length(), or_packed_domain_size(), or_packed_string_length(), or_unpack_int(), strlen, and xlocator_check_fk_validity().
Referenced by check_fk_validity().
LC_FIND_CLASSNAME locator_delete_class_name (const char * class_name)
Definition at line 1143 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, LC_CLASSNAME_ERROR, net_client_request(), NET_SERVER_LC_DELETE_CLASSNAME, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), strlen, and xlocator_delete_class_name().
Referenced by locator_add_class(), and locator_remove_class().
int locator_demote_class_lock (const OID * class_oid, LOCK lock, LOCK * ex_lock)
Definition at line 10176 of file network_interface_cl.c.
References ER_FAILED, net_client_request(), NET_SERVER_LC_DEMOTE_CLASS_LOCK, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_OID_SIZE, or_pack_lock(), or_pack_oid(), or_unpack_int(), or_unpack_lock(), rc, sm_Root_class_mop, ws_mop(), and ws_set_lock().
int locator_does_exist (OID * oidp, int chn, LOCK lock, OID * class_oid, int class_chn, int need_fetching, int prefetch, LC_COPYAREA ** fetch_copyarea, LC_FETCH_VERSION_TYPE fetch_version_type)
Definition at line 469 of file network_interface_cl.c.
References COPY_OID, ER_FAILED, LC_ERROR, LC_EXIST, net_client_request_recv_copyarea(), NET_COPY_AREA_SENDRECV_SIZE, NET_SERVER_LC_DOESEXIST, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_OID_SIZE, or_pack_int(), or_pack_lock(), or_pack_oid(), or_unpack_int(), or_unpack_oid(), success(), and xlocator_does_exist().
Referenced by locator_lock_and_doesexist(), and process_value().
int locator_fetch (OID * oidp, int chn, LOCK lock, LC_FETCH_VERSION_TYPE fetch_type, OID * class_oid, int class_chn, int prefetch, LC_COPYAREA ** fetch_copyarea)
Definition at line 258 of file network_interface_cl.c.
References assert, ER_FAILED, net_client_request_recv_copyarea(), NET_COPY_AREA_SENDRECV_SIZE, NET_SERVER_LC_FETCH, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_OID_SIZE, or_pack_int(), or_pack_lock(), or_pack_oid(), or_unpack_int(), db_identifier::pageid, db_identifier::slotid, success(), db_identifier::volid, and xlocator_fetch().
Referenced by locator_lock().
int locator_fetch_all (const HFID * hfid, LOCK * lock, LC_FETCH_VERSION_TYPE fetch_version_type, OID * class_oidp, int * nobjects, int * nfetched, OID * last_oidp, LC_COPYAREA ** fetch_copyarea)
Definition at line 395 of file network_interface_cl.c.
References ER_FAILED, net_client_request_recv_copyarea(), NET_COPY_AREA_SENDRECV_SIZE, NET_SERVER_LC_FETCHALL, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_HFID_SIZE, OR_INT_SIZE, OR_OID_SIZE, or_pack_hfid(), or_pack_int(), or_pack_lock(), or_pack_oid(), or_unpack_int(), or_unpack_lock(), or_unpack_oid(), success(), and xlocator_fetch_all().
Referenced by locator_fun_get_all_mops(), and process_class().
int locator_fetch_all_reference_lockset (OID * oid, int chn, OID * class_oid, int class_chn, LOCK lock, int quit_on_errors, int prune_level, LC_LOCKSET ** lockset, LC_COPYAREA ** fetch_copyarea)
Definition at line 869 of file network_interface_cl.c.
References ER_FAILED, free_and_init, locator_allocate_and_unpack_lockset(), net_client_request_3recv_copyarea(), NET_COPY_AREA_SENDRECV_SIZE, NET_SENDRECV_BUFFSIZE, NET_SERVER_LC_FETCH_ALLREFS_LOCKSET, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_OID_SIZE, or_pack_int(), or_pack_lock(), or_pack_oid(), or_unpack_int(), success(), and xlocator_fetch_all_reference_lockset().
Referenced by locator_lock_nested().
int locator_fetch_lockhint_classes (LC_LOCKHINT * lockhint, LC_COPYAREA ** fetch_area)
Definition at line 1516 of file network_interface_cl.c.
References eid, ER_FAILED, lc_lock_hint::first_fetch_lockhint_call, locator_pack_lockhint(), locator_unpack_lockhint(), net_client_recv_copyarea(), net_client_request_2recv_copyarea(), NET_COPY_AREA_SENDRECV_SIZE, NET_SENDRECV_BUFFSIZE, NET_SERVER_LC_FETCH_LOCKHINT_CLASSES, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), lc_lock_hint::packed, lc_lock_hint::packed_size, success(), and xlocator_fetch_lockhint_classes().
Referenced by locator_lockhint_classes().
int locator_fetch_lockset (LC_LOCKSET * lockset, LC_COPYAREA ** fetch_copyarea)
Definition at line 769 of file network_interface_cl.c.
References eid, ER_FAILED, lc_lock_set::first_fetch_lockset_call, locator_pack_lockset(), locator_unpack_lockset(), net_client_recv_copyarea(), net_client_request_2recv_copyarea(), NET_COPY_AREA_SENDRECV_SIZE, NET_SENDRECV_BUFFSIZE, NET_SERVER_LC_FETCH_LOCKSET, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), lc_lock_set::packed, lc_lock_set::packed_size, success(), and xlocator_fetch_lockset().
Referenced by locator_get_rest_objects_classes().
LC_FIND_CLASSNAME locator_find_class_oid (const char * class_name, OID * class_oid, LOCK lock)
Definition at line 955 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, LC_CLASSNAME_ERROR, net_client_request(), NET_SERVER_LC_FIND_CLASSOID, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_OID_SIZE, or_pack_lock(), or_pack_oid(), or_unpack_int(), or_unpack_oid(), strlen, and xlocator_find_class_oid().
Referenced by locator_find_class_by_oid().
LC_FIND_CLASSNAME locator_find_lockhint_class_oids (int num_classes, const char ** many_classnames, LOCK * many_locks, int * many_need_subclasses, LC_PREFETCH_FLAGS * many_flags, OID * guessed_class_oids, int * guessed_class_chns, int quit_on_errors, LOCK lock_rr_tran, LC_LOCKHINT ** lockhint, LC_COPYAREA ** fetch_copyarea)
Definition at line 1402 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, i, LC_CLASSNAME_ERROR, locator_allocate_and_unpack_lockhint(), net_client_request_3recv_copyarea(), NET_COPY_AREA_SENDRECV_SIZE, NET_SENDRECV_BUFFSIZE, NET_SERVER_LC_FIND_LOCKHINT_CLASSOIDS, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_OID_SIZE, or_pack_int(), or_pack_lock(), or_pack_oid(), or_unpack_int(), tm_Tran_rep_read_lock, and xlocator_find_lockhint_class_oids().
Referenced by locator_lockhint_classes().
int locator_force (LC_COPYAREA * copy_area, int num_ignore_error_list, int * ignore_error_list, int content_size)
Definition at line 657 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, i, LC_MANYOBJS_PTR_IN_COPYAREA, lc_copy_area::length, locator_allocate_copy_area_by_length(), locator_free_copy_area(), locator_manyobj_flag_is_set(), locator_manyobj_flag_remove(), locator_send_copy_area(), locator_unpack_copy_area_descriptor(), lc_copy_area::mem, lc_copyarea_manyobjs::multi_update_flags, net_client_request_3_data(), NET_SERVER_LC_FORCE, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), START_MULTI_UPDATE, and xlocator_force().
Referenced by locator_mflush_force().
int locator_get_class (OID * class_oid, int class_chn, const OID * oid, LOCK lock, int prefetching, LC_COPYAREA ** fetch_copyarea)
Definition at line 328 of file network_interface_cl.c.
References ER_FAILED, net_client_request_recv_copyarea(), NET_COPY_AREA_SENDRECV_SIZE, NET_SERVER_LC_GET_CLASS, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_OID_SIZE, or_pack_int(), or_pack_lock(), or_pack_oid(), or_unpack_int(), or_unpack_oid(), success(), and xlocator_get_class().
Referenced by locator_lock_class_of_instance().
int locator_get_reserved_class_name_oid (const char * classname, OID * class_oid)
Definition at line 1082 of file network_interface_cl.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, net_client_request(), NET_SERVER_LC_RESERVE_CLASSNAME_GET_OID, NO_ERROR, NULL, OID_SET_NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_OID_SIZE, or_unpack_oid(), and xlocator_get_reserved_class_name_oid().
Referenced by locator_add_class().
int locator_log_force_nologging (void)
Definition at line 5945 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_FAILED, ER_ONLY_IN_STANDALONE, er_set(), log_set_no_logging(), and success().
Referenced by csql(), and loaddb_internal().
int locator_notify_isolation_incons (LC_COPYAREA ** synch_copyarea)
Definition at line 543 of file network_interface_cl.c.
References ER_FAILED, net_client_request_recv_copyarea(), NET_COPY_AREA_SENDRECV_SIZE, NET_SERVER_LC_NOTIFY_ISOLATION_INCONS, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), success(), and xlocator_notify_isolation_incons().
Referenced by locator_synch_isolation_incons().
int locator_prefetch_repl_insert (OID * class_oid, RECDES * recdes)
int locator_redistribute_partition_data (OID * class_oid, int no_oids, OID * oid_list)
Definition at line 10035 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, ER_QPROC_INVALID_PARAMETER, er_set(), free_and_init, i, net_client_request(), NET_SERVER_LC_REDISTRIBUTE_PARTITION_DATA, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_OID_SIZE, or_pack_int(), or_pack_oid(), or_unpack_int(), success(), and xlocator_redistribute_partition_data().
Referenced by do_redistribute_partitions_data().
int locator_remove_class_from_index (OID * oid, BTID * btid, HFID * hfid)
Definition at line 5975 of file network_interface_cl.c.
References ER_FAILED, net_client_request(), NET_SERVER_LC_REM_CLASS_FROM_INDEX, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_BTID_ALIGNED_SIZE, OR_HFID_SIZE, OR_INT_SIZE, OR_OID_SIZE, or_pack_btid(), or_pack_hfid(), or_pack_oid(), or_unpack_int(), success(), and xlocator_remove_class_from_index().
Referenced by rem_class_from_index().
LC_FIND_CLASSNAME locator_rename_class_name (const char * old_name, const char * new_name, OID * class_oid)
Definition at line 1200 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, LC_CLASSNAME_ERROR, net_client_request(), NET_SERVER_LC_RENAME_CLASSNAME, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_OID_SIZE, or_pack_oid(), or_unpack_int(), and xlocator_rename_class_name().
Referenced by locator_prepare_rename_class().
int locator_repl_force (LC_COPYAREA * copy_area, LC_COPYAREA ** reply_copy_area)
Definition at line 594 of file network_interface_cl.c.
References assert, er_errid(), ER_FAILED, free_and_init, locator_send_copy_area(), net_client_request_3_data_recv_copyarea(), NET_COPY_AREA_SENDRECV_SIZE, NET_SERVER_LC_REPL_FORCE, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), and or_unpack_int().
Referenced by locator_repl_mflush_force().
LC_FIND_CLASSNAME locator_reserve_class_names (const int num_classes, const char ** class_names, OID * class_oids)
Definition at line 1017 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, i, LC_CLASSNAME_ERROR, net_client_request(), NET_SERVER_LC_RESERVE_CLASSNAME, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_OID_SIZE, or_pack_int(), or_pack_oid(), or_unpack_int(), and xlocator_reserve_class_names().
Referenced by acquire_locks_for_multiple_rename(), and locator_reserve_class_name().
int locator_upgrade_instances_domain (OID * class_oid, int attribute_id)
Definition at line 9632 of file network_interface_cl.c.
References ER_FAILED, ER_QPROC_INVALID_PARAMETER, error(), net_client_request(), NET_SERVER_LC_UPGRADE_INSTANCES_DOMAIN, NO_ERROR, NULL, OID_ISNULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_OID_SIZE, or_pack_int(), or_pack_oid(), or_unpack_int(), success(), and xlocator_upgrade_instances_domain().
Referenced by do_run_upgrade_instances_domain().
void lock_dump (FILE * outfp)
Definition at line 3589 of file network_interface_cl.c.
References net_client_request_recv_stream(), NET_SERVER_LK_DUMP, NULL, and xlock_dump().
Referenced by help_print_info(), and lockdb().
int log_checkpoint (void)
Definition at line 2365 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_NET_CLIENT_DATA_RECEIVE, ER_NOT_IN_STANDALONE, er_set(), error(), net_client_request(), NET_SERVER_LOG_CHECKPOINT, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, and or_unpack_errcode().
Referenced by db_checkpoint().
int log_does_active_user_exist (const char * user_name, bool * existed)
Definition at line 9972 of file network_interface_cl.c.
References ARG_FILE_LINE, assert, er_errid(), ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, net_client_request(), NET_SERVER_AU_DOES_ACTIVE_USER_EXIST, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), and strlen.
Referenced by au_find_user_to_drop().
void log_dump_stat (FILE * outfp)
Definition at line 2401 of file network_interface_cl.c.
References net_client_request_recv_stream(), NET_SERVER_LOG_DUMP_STAT, NULL, and xlogpb_dump_stat().
Referenced by help_print_info().
int log_get_mvcc_snapshot (void)
Definition at line 9593 of file network_interface_cl.c.
References err, net_client_request(), NET_SERVER_GET_MVCC_SNAPSHOT, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), and xlogtb_get_mvcc_snapshot().
Referenced by do_insert_template().
int log_reset_isolation (TRAN_ISOLATION isolation)
Definition at line 2291 of file network_interface_cl.c.
References ER_NET_CLIENT_DATA_RECEIVE, net_client_request(), NET_SERVER_LOG_RESET_ISOLATION, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), and xlogtb_reset_isolation().
Referenced by tran_reset_isolation().
int log_reset_wait_msecs (int wait_msecs)
Definition at line 2244 of file network_interface_cl.c.
References net_client_request(), NET_SERVER_LOG_RESET_WAIT_MSECS, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), and xlogtb_reset_wait_msecs().
Referenced by tran_reset_wait_times().
void log_set_interrupt (int set)
Definition at line 2337 of file network_interface_cl.c.
References net_client_request_no_reply(), NET_SERVER_LOG_SET_INTERRUPT, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), and xlogtb_set_interrupt().
Referenced by ldr_exec_query_interrupt_handler(), and locator_set_sig_interrupt().
int log_set_suppress_repl_on_transaction (int set)
Definition at line 2432 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_FAILED, ER_NET_CLIENT_DATA_RECEIVE, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, LOB_UNKNOWN, net_client_request(), net_client_request2_no_malloc(), NET_SERVER_LOG_ADD_LOB_LOCATOR, NET_SERVER_LOG_CHANGE_STATE_OF_LOCATOR, NET_SERVER_LOG_DROP_LOB_LOCATOR, NET_SERVER_LOG_FIND_LOB_LOCATOR, NET_SERVER_LOG_SET_SUPPRESS_REPL_ON_TRANSACTION, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), strlen, and xlogtb_set_suppress_repl_on_transaction().
Referenced by db_set_suppress_repl_on_transaction().
void logtb_dump_trantable (FILE * outfp)
Definition at line 7911 of file network_interface_cl.c.
References net_client_request_recv_stream(), NET_SERVER_LOG_DUMP_TRANTB, NULL, and xlogtb_dump_trantable().
Referenced by help_print_info().
void logtb_free_trans_info (TRANS_INFO * info)
Definition at line 7752 of file network_interface_cl.c.
References assert_release, db_private_free_and_init, one_tran_info::db_user, free_and_init, one_tran_info::host_name, i, trans_info::include_query_exec_info, one_tran_info::login_name, NULL, trans_info::num_trans, one_tran_info::program_name, one_tran_info::query_exec_info, tran_query_exec_info::query_stmt, tran_query_exec_info::sql_id, trans_info::tran, and tran_query_exec_info::wait_for_tran_index_string.
Referenced by csql_killtran(), killtran(), logtb_get_trans_info(), and tranlist().
int logtb_get_pack_tran_table (char ** buffer_p, int * size_p, bool include_query_exec_info)
Definition at line 7700 of file network_interface_cl.c.
References assert, er_errid(), error(), net_client_request2(), NET_SERVER_LOG_GETPACK_TRANTB, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), and xlogtb_get_pack_tran_table().
Referenced by logtb_get_trans_info().
TRANS_INFO* logtb_get_trans_info (bool include_query_exec_info)
Definition at line 7811 of file network_interface_cl.c.
References ARG_FILE_LINE, assert, one_tran_info::db_user, ER_ERROR_SEVERITY, ER_GENERIC_ERROR, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, one_tran_info::host_name, i, trans_info::include_query_exec_info, one_tran_info::login_name, logtb_free_trans_info(), logtb_get_pack_tran_table(), NO_ERROR, NULL, trans_info::num_trans, or_unpack_float(), or_unpack_int(), or_unpack_string(), OR_UNPACK_XASL_ID, one_tran_info::process_id, one_tran_info::program_name, one_tran_info::query_exec_info, tran_query_exec_info::query_stmt, tran_query_exec_info::query_time, tran_query_exec_info::sql_id, one_tran_info::state, trans_info::tran, one_tran_info::tran_index, tran_query_exec_info::tran_time, tran_query_exec_info::wait_for_tran_index_string, and tran_query_exec_info::xasl_id.
Referenced by csql_killtran(), killtran(), and tranlist().
int logwr_get_log_pages (LOGWR_CONTEXT * ctx_ptr)
Definition at line 8774 of file network_interface_cl.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_HA_LW_FAILED_GET_LOG_PAGE, er_log_debug, ER_NET_SERVER_CRASHED, ER_NOT_IN_STANDALONE, er_set(), error(), HA_SERVER_STATE_DEAD, logwr_context::last_error, LOG_HA_FILESTAT_SYNCHRONIZED, LOGPB_HEADER_PAGE_ID, LOGWR_COPY_FROM_FIRST_PHY_PAGE_MASK, LOGWR_MODE_ASYNC, LOGWR_MODE_SEMISYNC, LOGWR_MODE_SYNC, mode, net_client_request_with_logwr_context(), NET_SERVER_LOGWR_GET_LOG_PAGES, NO_ERROR, NULL, NULL_PAGEID, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT64_SIZE, OR_INT_SIZE, or_pack_int(), or_pack_int64(), and logwr_context::shutdown.
void net_cleanup_client_queues (void)
Definition at line 3975 of file network_cl.c.
References css_cleanup_client_queues(), net_Server_host, and net_Server_name.
Referenced by qmgr_execute_query(), tran_server_abort(), and tran_server_commit().
int net_client_check_log_header (LOGWR_CONTEXT * ctx_ptr, char * argbuf, int argsize, char * replybuf, int replysize, char ** logpg_area_buf, bool verbose)
Definition at line 2216 of file network_cl.c.
References ARG_FILE_LINE, COMPARE_AND_FREE_BUFFER, COMPARE_SIZE_AND_BUFFER, css_Errno, css_queue_receive_data_buffer(), css_receive_data_from_server(), css_send_req_to_server_2_data(), END_CALLBACK, ER_ERROR_SEVERITY, ER_NET_SERVER_CRASHED, ER_NET_SERVER_DATA_RECEIVE, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), GET_NEXT_LOG_PAGES, net_client_send_data(), net_Server_host, NET_SERVER_LOGWR_GET_LOG_PAGES, net_Server_name, NO_ERROR, NULL, or_unpack_int(), logwr_context::rc, rc, and set_server_error().
int net_client_final (void)
Definition at line 3991 of file network_cl.c.
References css_terminate(), and NO_ERROR.
Referenced by boot_shutdown_client().
int net_client_get_next_log_pages (int rc, char * replybuf, int replysize, int length)
Definition at line 2518 of file network_cl.c.
References ARG_FILE_LINE, COMPARE_AND_FREE_BUFFER, css_queue_receive_data_buffer(), css_receive_data_from_server(), ER_ERROR_SEVERITY, ER_NET_SERVER_CRASHED, er_set(), error(), LOGWR_MODE_ASYNC, LOGWR_MODE_SEMISYNC, LOGWR_MODE_SYNC, NO_ERROR, NULL, and set_server_error().
Referenced by net_client_request_with_logwr_context().
char* net_client_get_server_host (void)
Definition at line 936 of file network_cl.c.
References net_Server_host.
int net_client_init (const char * dbname, const char * hostname)
Definition at line 3921 of file network_cl.c.
References ARG_FILE_LINE, css_client_init(), css_terminate(), CUB_MAXHOSTNAMELEN, DB_MAX_IDENTIFIER_LENGTH, ER_ERROR_SEVERITY, ER_NET_INVALID_HOST_NAME, ER_NET_INVALID_SERVER_NAME, er_set(), error(), net_Server_host, net_Server_name, NO_ERROR, NULL, prm_get_integer_value(), PRM_ID_TCP_PORT_ID, and strlen.
Referenced by boot_client_all_finalize().
void net_client_logwr_send_end_msg (int rc, int error)
Definition at line 2487 of file network_cl.c.
References LOGPB_HEADER_PAGE_ID, LOGWR_MODE_ASYNC, net_client_send_data(), net_Server_host, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT64_SIZE, OR_INT_SIZE, or_pack_int(), and or_pack_int64().
int net_client_ping_server (int client_val, int * server_val, int timeout)
Definition at line 3727 of file network_cl.c.
References ARG_FILE_LINE, COMPARE_AND_FREE_BUFFER, css_receive_data_from_server_with_timeout(), css_send_request_to_server_with_buffer(), eid, ER_ERROR_SEVERITY, er_log_debug, ER_NET_CANT_CONNECT_SERVER, ER_NET_NO_SERVER_HOST, ER_NET_SERVER_DATA_RECEIVE, er_set(), error(), net_Server_host, net_Server_name, NET_SERVER_PING, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), and or_unpack_int().
Referenced by db_ping_server().
int net_client_ping_server_with_handshake (int client_type, bool check_capabilities, int opt_cap)
Definition at line 3782 of file network_cl.c.
References ARG_FILE_LINE, boot_Host_name, check_server_capabilities(), client_capabilities(), COMPARE_AND_FREE_BUFFER, css_receive_data_from_server(), css_send_request_to_server_with_buffer(), CUB_MAXHOSTNAMELEN, eid, er_errid(), ER_ERROR_SEVERITY, ER_NET_CANT_CONNECT_SERVER, ER_NET_DIFFERENT_BIT_PLATFORM, ER_NET_DIFFERENT_RELEASE, ER_NET_HS_UNKNOWN_SERVER_REL, ER_NET_NO_SERVER_HOST, ER_NET_SERVER_DATA_RECEIVE, ER_NET_SERVER_HAND_SHAKE, ER_NET_UNUSED_BUFFER, er_set(), error(), free_and_init, NET_CAP_REMOTE_DISABLED, net_Server_host, net_Server_name, NET_SERVER_PING_WITH_HANDSHAKE, NET_SERVER_SHUTDOWN, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_pack_string_with_length(), or_packed_string_length(), or_unpack_int(), or_unpack_string_nocopy(), rel_bit_platform(), rel_compare(), rel_get_net_compatible(), REL_MAX_RELEASE_LENGTH, REL_NOT_COMPATIBLE, rel_release_string(), and server_capabilities().
Referenced by boot_client_all_finalize().
int net_client_receive_action (int rc, int * action)
Definition at line 4037 of file network_cl.c.
References ARG_FILE_LINE, css_receive_data_from_server(), ER_ERROR_SEVERITY, ER_NET_DATASIZE_MISMATCH, ER_NET_SERVER_CRASHED, er_set(), error(), free_and_init, net_Server_name, NO_ERROR, NULL, OR_INT_SIZE, or_unpack_int(), and set_server_error().
Referenced by method_send_value_to_server().
int net_client_recv_copyarea (int request, char * replybuf, int replysize, char * recvbuffer, int recvbuffer_size, LC_COPYAREA ** reply_copy_area, int eid)
Definition at line 3169 of file network_cl.c.
References ARG_FILE_LINE, assert, ASSERT_ERROR_AND_SET, CANT_ALLOC_BUFFER, COMPARE_AND_FREE_BUFFER, COMPARE_SIZE_AND_BUFFER, css_queue_receive_data_buffer(), css_receive_data_from_server(), ER_ERROR_SEVERITY, ER_FAILED, ER_NET_DATASIZE_MISMATCH, ER_NET_SERVER_CRASHED, ER_NET_UNUSED_BUFFER, er_set(), error(), free_and_init, locator_recv_allocate_copyarea(), locator_unpack_copy_area_descriptor(), net_consume_expected_packets(), net_histo_add_entry(), net_histo_request_finished(), net_Histo_setup, net_Server_name, NO_ERROR, NULL, or_unpack_int(), and set_server_error().
Referenced by locator_fetch_lockhint_classes(), and locator_fetch_lockset().
int net_client_request (int request, char * argbuf, int argsize, char * replybuf, int replysize, char * databuf, int datasize, char * replydata, int replydatasize)
Definition at line 1053 of file network_cl.c.
References ARG_FILE_LINE, CANT_ALLOC_BUFFER, COMPARE_AND_FREE_BUFFER, COMPARE_SIZE_AND_BUFFER, css_Errno, css_queue_receive_data_buffer(), css_receive_data_from_server(), css_send_req_to_server(), ER_ERROR_SEVERITY, ER_NET_SERVER_CRASHED, er_set(), error(), free_and_init, i, net_client_request_internal(), net_histo_add_entry(), net_histo_request_finished(), net_Histo_setup, net_Server_host, net_Server_name, NO_ERROR, NULL, or_unpack_int64(), rc, and set_server_error().
Referenced by acl_reload(), boot_add_volume_extension(), boot_change_ha_mode(), boot_compact_classes(), boot_find_last_permanent(), boot_find_last_temp(), boot_find_number_permanent_volumes(), boot_find_number_temp_volumes(), boot_heap_compact(), boot_notify_ha_log_applier_state(), boot_unregister_client(), btree_add_index(), btree_class_test_unique(), btree_delete_index(), btree_find_unique(), btree_get_statistics(), btree_load_index(), catalog_check_rep_dir(), chksum_insert_repl_log_and_demote_table_lock(), clogin_user(), compact_db_start(), compact_db_stop(), csession_create_prepared_statement(), csession_delete_prepared_statement(), csession_drop_session_variables(), csession_end_session(), csession_get_row_count(), csession_reset_cur_insert_id(), csession_set_row_count(), csession_set_session_variables(), cvacuum(), db_local_transaction_id(), disk_get_free_numpages(), disk_get_total_numpages(), es_posix_delete_file(), es_posix_get_file_size(), es_posix_read_file(), es_posix_write_file(), file_apply_tde_to_class_files(), heap_create(), heap_destroy_newly_created(), heap_get_class_num_objects_pages(), heap_has_instance(), heap_reclaim_addresses(), jsp_get_server_port(), loaddb_destroy(), loaddb_init(), loaddb_update_stats(), locator_assign_oid(), locator_assign_oid_batch(), locator_check_fk_validity(), locator_delete_class_name(), locator_demote_class_lock(), locator_find_class_oid(), locator_get_reserved_class_name_oid(), locator_redistribute_partition_data(), locator_remove_class_from_index(), locator_rename_class_name(), locator_reserve_class_names(), locator_upgrade_instances_domain(), log_checkpoint(), log_does_active_user_exist(), log_get_mvcc_snapshot(), log_reset_isolation(), log_reset_wait_msecs(), log_set_suppress_repl_on_transaction(), perfmon_server_copy_global_stats(), perfmon_server_copy_stats(), perfmon_server_start_stats(), perfmon_server_stop_stats(), qmgr_drop_all_query_plans(), qmgr_dump_query_cache(), qmgr_end_query(), repl_log_get_append_lsa(), repl_set_info(), serial_decache(), stats_update_all_statistics(), stats_update_statistics(), sysprm_change_server_parameters(), tde_change_mk_on_server(), tde_get_mk_info(), thread_kill_or_interrupt_tran(), thread_kill_tran_index(), tran_is_blocked(), tran_lock_rep_read(), tran_server_2pc_attach_global_tran(), tran_server_2pc_prepare(), tran_server_2pc_prepare_global_tran(), tran_server_2pc_recovery_prepared(), tran_server_2pc_start(), tran_server_abort(), tran_server_commit(), tran_server_has_updated(), tran_server_is_active_and_has_updated(), tran_server_partial_abort(), tran_server_savepoint(), tran_server_set_global_tran_info(), and tran_wait_server_active_trans().
int net_client_request2 (int request, char * argbuf, int argsize, char * replybuf, int replysize, char * databuf, int datasize, char ** replydata_ptr, int * replydatasize_ptr)
Definition at line 1288 of file network_cl.c.
References ARG_FILE_LINE, COMPARE_AND_FREE_BUFFER, COMPARE_SIZE_AND_BUFFER, css_Errno, css_queue_receive_data_buffer(), css_receive_data_from_server(), css_send_req_to_server(), ER_ERROR_SEVERITY, ER_NET_SERVER_CRASHED, er_set(), error(), free_and_init, net_consume_expected_packets(), net_histo_add_entry(), net_histo_request_finished(), net_Histo_setup, net_Server_host, net_Server_name, net_set_alloc_err_if_not_set(), NO_ERROR, NULL, or_unpack_int(), rc, and set_server_error().
Referenced by boot_get_server_locales(), boot_get_server_timezone_checksum(), boot_register_client(), btree_find_multi_uniques(), btree_get_index_key_type(), csession_find_or_create_session(), csession_get_last_insert_id(), csession_get_prepared_statement(), csession_get_variable(), disk_get_fullname(), disk_get_remarks(), file_apply_tde_to_class_files(), loaddb_fetch_status(), loaddb_install_class(), loaddb_load_batch(), logtb_get_pack_tran_table(), netcl_spacedb(), qmgr_prepare_query(), qp_get_server_info(), serial_get_current_value(), serial_get_next_value(), stats_get_statistics_from_server(), sysprm_get_force_server_parameters(), sysprm_obtain_server_parameters(), and tde_get_mk_file_path().
int net_client_request2_no_malloc (int request, char * argbuf, int argsize, char * replybuf, int replysize, char * databuf, int datasize, char * replydata, int * replydatasize_ptr)
Definition at line 1395 of file network_cl.c.
References ARG_FILE_LINE, COMPARE_AND_FREE_BUFFER, COMPARE_SIZE_AND_BUFFER, css_Errno, css_queue_receive_data_buffer(), css_receive_data_from_server(), css_send_req_to_server(), ER_ERROR_SEVERITY, ER_NET_SERVER_CRASHED, er_set(), error(), net_histo_add_entry(), net_histo_request_finished(), net_Histo_setup, net_Server_host, net_Server_name, NO_ERROR, NULL, or_unpack_int(), rc, and set_server_error().
Referenced by es_posix_copy_file(), es_posix_create_file(), es_posix_rename_file(), log_set_suppress_repl_on_transaction(), qfile_get_list_file_page(), and tran_server_get_global_tran_info().
int net_client_request_2recv_copyarea (int request, char * argbuf, int argsize, char * replybuf, int replysize, char * databuf, int datasize, char * recvbuffer, int recvbuffer_size, LC_COPYAREA ** reply_copy_area, int * eid)
Definition at line 2769 of file network_cl.c.
References ARG_FILE_LINE, assert, ASSERT_ERROR_AND_SET, CANT_ALLOC_BUFFER, COMPARE_AND_FREE_BUFFER, COMPARE_SIZE_AND_BUFFER, css_Errno, css_queue_receive_data_buffer(), css_receive_data_from_server(), css_send_req_to_server(), ER_ERROR_SEVERITY, ER_FAILED, ER_NET_DATASIZE_MISMATCH, ER_NET_SERVER_CRASHED, ER_NET_UNUSED_BUFFER, er_set(), error(), free_and_init, locator_recv_allocate_copyarea(), locator_unpack_copy_area_descriptor(), net_consume_expected_packets(), net_histo_add_entry(), net_histo_request_finished(), net_Histo_setup, net_Server_host, net_Server_name, NO_ERROR, NULL, or_unpack_int(), rc, and set_server_error().
Referenced by locator_fetch_lockhint_classes(), and locator_fetch_lockset().
int net_client_request_3_data (int request, char * argbuf, int argsize, char * databuf1, int datasize1, char * databuf2, int datasize2, char * replydata0, int replydatasize0, char * replydata1, int replydatasize1, char * replydata2, int replydatasize2)
Definition at line 1490 of file network_cl.c.
References ARG_FILE_LINE, COMPARE_AND_FREE_BUFFER, COMPARE_SIZE_AND_BUFFER, css_Errno, css_queue_receive_data_buffer(), css_receive_data_from_server(), css_send_req_to_server_2_data(), ER_ERROR_SEVERITY, ER_NET_SERVER_CRASHED, er_set(), error(), net_histo_add_entry(), net_histo_request_finished(), net_Histo_setup, net_Server_host, net_Server_name, NO_ERROR, NULL, or_unpack_int(), rc, and set_server_error().
Referenced by locator_force().
int net_client_request_3_data_recv_copyarea (int request, char * argbuf, int argsize, char * databuf1, int datasize1, char * databuf2, int datasize2, char * replybuf, int replysize, LC_COPYAREA ** reply_copy_area)
Definition at line 3004 of file network_cl.c.
References ARG_FILE_LINE, assert, ASSERT_ERROR_AND_SET, COMPARE_AND_FREE_BUFFER, COMPARE_SIZE_AND_BUFFER, css_Errno, css_queue_receive_data_buffer(), css_receive_data_from_server(), css_send_req_to_server_2_data(), ER_ERROR_SEVERITY, ER_FAILED, ER_NET_SERVER_CRASHED, er_set(), error(), free_and_init, locator_recv_allocate_copyarea(), locator_unpack_copy_area_descriptor(), net_consume_expected_packets(), net_histo_add_entry(), net_histo_request_finished(), net_Histo_setup, net_Server_host, net_Server_name, NO_ERROR, NULL, or_unpack_int(), set_server_error(), and success().
Referenced by locator_repl_force().
int net_client_request_3recv_copyarea (int request, char * argbuf, int argsize, char * replybuf, int replysize, char * databuf, int datasize, char ** recvbuffer, int * recvbuffer_size, LC_COPYAREA ** reply_copy_area)
Definition at line 3392 of file network_cl.c.
References ARG_FILE_LINE, ASSERT_ERROR_AND_SET, COMPARE_AND_FREE_BUFFER, COMPARE_SIZE_AND_BUFFER, css_Errno, css_queue_receive_data_buffer(), css_receive_data_from_server(), css_send_req_to_server(), ER_ERROR_SEVERITY, ER_FAILED, ER_NET_SERVER_CRASHED, er_set(), error(), free_and_init, locator_recv_allocate_copyarea(), locator_unpack_copy_area_descriptor(), net_consume_expected_packets(), net_histo_add_entry(), net_histo_request_finished(), net_Histo_setup, net_Server_host, net_Server_name, net_set_alloc_err_if_not_set(), NO_ERROR, NULL, or_unpack_int(), rc, and set_server_error().
Referenced by locator_fetch_all_reference_lockset(), and locator_find_lockhint_class_oids().
int net_client_request_no_reply (int request, char * argbuf, int argsize)
Definition at line 896 of file network_cl.c.
References ARG_FILE_LINE, assert, css_Errno, css_send_req_to_server_no_reply(), ER_ERROR_SEVERITY, ER_NET_SERVER_CRASHED, er_set(), error(), net_histo_add_entry(), net_Histo_setup, net_Server_host, NET_SERVER_LD_INTERRUPT, NET_SERVER_LOG_SET_INTERRUPT, net_Server_name, NO_ERROR, rc, and set_server_error().
Referenced by loaddb_interrupt(), and log_set_interrupt().
int net_client_request_recv_copyarea (int request, char * argbuf, int argsize, char * replybuf, int replysize, LC_COPYAREA ** reply_copy_area)
Definition at line 2583 of file network_cl.c.
References ARG_FILE_LINE, ASSERT_ERROR_AND_SET, COMPARE_AND_FREE_BUFFER, COMPARE_SIZE_AND_BUFFER, css_Errno, css_queue_receive_data_buffer(), css_receive_data_from_server(), css_send_req_to_server(), ER_ERROR_SEVERITY, ER_FAILED, ER_NET_SERVER_CRASHED, er_set(), error(), free_and_init, locator_free_copy_area(), locator_recv_allocate_copyarea(), locator_unpack_copy_area_descriptor(), net_consume_expected_packets(), net_histo_add_entry(), net_histo_request_finished(), net_Histo_setup, net_Server_host, net_Server_name, NO_ERROR, NULL, or_unpack_int(), rc, and set_server_error().
Referenced by locator_does_exist(), locator_fetch(), locator_fetch_all(), locator_get_class(), and locator_notify_isolation_incons().
int net_client_request_recv_stream (int request, char * argbuf, int argsize, char * replybuf, int replybuf_size, char * databuf, int datasize, FILE * outfp)
Definition at line 3587 of file network_cl.c.
References ARG_FILE_LINE, COMPARE_AND_FREE_BUFFER, COMPARE_SIZE_AND_BUFFER, css_Errno, css_queue_receive_data_buffer(), css_receive_data_from_server(), css_send_req_to_server(), ER_ERROR_SEVERITY, ER_NET_CANT_ALLOC_BUFFER, ER_NET_DATASIZE_MISMATCH, ER_NET_SERVER_CRASHED, ER_NET_UNUSED_BUFFER, er_set(), error(), free_and_init, net_histo_add_entry(), net_histo_request_finished(), net_Histo_setup, net_Server_host, net_Server_name, NO_ERROR, NULL, OR_INT_SIZE, or_pack_int(), or_unpack_int(), rc, and set_server_error().
Referenced by acl_dump(), lock_dump(), log_dump_stat(), logtb_dump_trantable(), qmgr_dump_query_cache(), qmgr_dump_query_plans(), sysprm_dump_server_parameters(), thread_dump_cs_stat(), and vacuum_dump().
int net_client_request_with_callback (int request, char * argbuf, int argsize, char * replybuf, int replysize, char * databuf1, int datasize1, char * databuf2, int datasize2, char ** replydata_ptr1, int * replydatasize_ptr1, char ** replydata_ptr2, int * replydatasize_ptr2, char ** replydata_ptr3, int * replydatasize_ptr3)
Definition at line 1611 of file network_cl.c.
References ARG_FILE_LINE, assert, ASYNC_OBTAIN_USER_INPUT, CAST_STRLEN, char_tolower(), COMPARE_AND_FREE_BUFFER, COMPARE_SIZE_AND_BUFFER, CONSOLE_OUTPUT, css_Errno, css_queue_receive_data_buffer(), css_receive_data_from_server(), CSS_RID_FROM_EID, css_send_req_to_server_2_data(), cursor_free_self_list_id, DB_PAGESIZE, END_CALLBACK, er_clear(), er_errid(), ER_ERROR_SEVERITY, ER_FAILED, ER_FATAL_ERROR_SEVERITY, ER_NET_DATA_TRUNCATED, ER_NET_SERVER_CRASHED, ER_NET_SERVER_DATA_RECEIVE, er_set(), error(), FILEIO_MAX_USER_RESPONSE_SIZE, FILEIO_PROMPT_BOOLEAN_TYPE, FILEIO_PROMPT_DISPLAY_ONLY, FILEIO_PROMPT_RANGE_TYPE, FILEIO_PROMPT_RANGE_WITH_SECONDARY_STRING_TYPE, FILEIO_PROMPT_STRING_TYPE, free_and_init, intl_mbs_casecmp(), qfile_list_id::last_pgptr, METHOD_CALL, method_invoke_for_server(), method_send_error_to_server(), method_sig_list_freemem(), net_client_send_data(), net_consume_expected_packets(), net_histo_add_entry(), net_histo_request_finished(), net_Histo_setup, net_Server_host, net_Server_name, net_set_alloc_err_if_not_set(), NO_ERROR, NULL, OR_INT_SIZE, or_pack_int(), or_pack_string_with_length(), or_unpack_int(), or_unpack_method_sig_list(), or_unpack_string_nocopy(), or_unpack_unbound_listid(), QUERY_END, rc, return_error_to_server(), set_server_error(), str_to_int32(), and strlen.
Referenced by boot_backup(), boot_check_db_consistency(), qmgr_execute_query(), and qmgr_prepare_and_execute_query().
int net_client_request_with_logwr_context (LOGWR_CONTEXT * ctx_ptr, int request, char * argbuf, int argsize, char * replybuf, int replysize, char * databuf1, int datasize1, char * databuf2, int datasize2, char ** replydata_ptr1, int * replydatasize_ptr1, char ** replydata_ptr2, int * replydatasize_ptr2)
Definition at line 2329 of file network_cl.c.
References ARG_FILE_LINE, COMPARE_AND_FREE_BUFFER, COMPARE_SIZE_AND_BUFFER, css_Errno, css_queue_receive_data_buffer(), css_receive_data_from_server(), css_receive_data_from_server_with_timeout(), css_send_req_to_server_2_data(), END_CALLBACK, ER_ERROR_SEVERITY, ER_HA_LW_FAILED_GET_LOG_PAGE, ER_NET_SERVER_CRASHED, ER_NET_SERVER_DATA_RECEIVE, er_set(), error(), GET_NEXT_LOG_PAGES, logwr_context::last_error, LOGWR_MODE_SEMISYNC, net_client_get_next_log_pages(), net_client_send_data(), net_histo_add_entry(), net_histo_request_finished(), net_Histo_setup, net_Server_host, net_Server_name, NO_ERROR, NULL, or_unpack_int(), logwr_context::rc, rc, set_server_error(), and logwr_context::shutdown.
Referenced by logwr_get_log_pages().
int net_client_send_data (char * host, unsigned int rc, char * databuf, int datasize)
Definition at line 4010 of file network_cl.c.
References css_send_data_to_server(), error(), NO_ERROR, NULL, and set_server_error().
Referenced by method_send_eof_to_server(), method_send_error_to_server(), method_send_value_to_server(), net_client_check_log_header(), net_client_logwr_send_end_msg(), net_client_request_with_callback(), and net_client_request_with_logwr_context().
void net_histo_clear (void)
Definition at line 666 of file network_cl.c.
References net_request_buffer::elapsed_time, i, net_Histo_call_count, net_Histo_last_call_time, net_Histo_setup_mnt, net_Histo_total_server_time, net_Req_buffer, net_request_buffer::request_count, net_request_buffer::total_size_received, and net_request_buffer::total_size_sent.
Referenced by histo_clear(), and net_histo_start().
int net_histo_print (FILE * stream)
Definition at line 695 of file network_cl.c.
References net_request_buffer::elapsed_time, err, i, net_request_buffer::name, net_Histo_setup_mnt, net_Req_buffer, NO_ERROR, NULL, net_request_buffer::request_count, net_request_buffer::total_size_received, and net_request_buffer::total_size_sent.
Referenced by histo_print().
int net_histo_print_global_stats (FILE * stream, bool cumulative, const char * substr)
Definition at line 756 of file network_cl.c.
References err, net_Histo_setup_mnt, and NO_ERROR.
Referenced by histo_print_global_stats().
int net_histo_start (bool for_all_trans)
Definition at line 775 of file network_cl.c.
References ER_FAILED, net_histo_clear(), net_Histo_setup, net_Histo_setup_mnt, net_histo_setup_names(), and NO_ERROR.
Referenced by histo_start().
int net_histo_stop (void)
Definition at line 804 of file network_cl.c.
References err, net_Histo_setup, net_Histo_setup_mnt, and NO_ERROR.
Referenced by histo_stop().
int netcl_spacedb (SPACEDB_ALL * spaceall, SPACEDB_ONEVOL ** spacevols, SPACEDB_FILES * spacefiles)
Definition at line 10103 of file network_interface_cl.c.
References assert, ASSERT_ERROR, ASSERT_ERROR_AND_SET, assert_release, disk_spacedb(), ER_FAILED, file_spacedb(), free_and_init, net_client_request2(), NET_SERVER_SPACEDB, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), and or_unpack_spacedb().
Referenced by spacedb().
int perfmon_server_copy_global_stats (UINT64 * to_stats)
Definition at line 7446 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, net_client_request(), NET_SERVER_MNT_SERVER_COPY_GLOBAL_STATS, NO_ERROR, NULL, OR_INT64_SIZE, perfmon_get_number_of_statistic_values(), perfmon_unpack_stats(), and xperfmon_server_copy_global_stats().
int perfmon_server_copy_stats (UINT64 * to_stats)
Definition at line 7393 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, net_client_request(), NET_SERVER_MNT_SERVER_COPY_STATS, NO_ERROR, NULL, OR_INT64_SIZE, perfmon_get_number_of_statistic_values(), perfmon_unpack_stats(), and xperfmon_server_copy_stats().
int perfmon_server_start_stats (void)
Definition at line 7317 of file network_interface_cl.c.
References ER_FAILED, net_client_request(), NET_SERVER_MNT_SERVER_START_STATS, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, and or_unpack_int().
int perfmon_server_stop_stats (void)
Definition at line 7355 of file network_interface_cl.c.
References ER_FAILED, net_client_request(), NET_SERVER_MNT_SERVER_STOP_STATS, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, and OR_INT_SIZE.
int qfile_get_list_file_page (QUERY_ID query_id, VOLID volid, PAGEID pageid, char * buffer, int * buffer_size)
Definition at line 6334 of file network_interface_cl.c.
References ER_NET_CLIENT_DATA_RECEIVE, error(), net_client_request2_no_malloc(), NET_SERVER_LS_GET_LIST_FILE_PAGE, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_pack_ptr(), OR_PTR_SIZE, or_unpack_int(), page_size, success(), and xqfile_get_list_file_page().
Referenced by cursor_get_list_file_page().
int qmgr_drop_all_query_plans (void)
Definition at line 7005 of file network_interface_cl.c.
References ER_FAILED, net_client_request(), NET_SERVER_QM_QUERY_DROP_ALL_PLANS, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), OR_XASL_ID_SIZE, and xqmgr_drop_all_query_plans().
Referenced by plandump().
void qmgr_dump_query_cache (FILE * outfp)
Definition at line 7086 of file network_interface_cl.c.
References db_make_timestamp(), db_sys_timestamp(), net_client_request(), net_client_request_recv_stream(), NET_SERVER_QM_QUERY_DUMP_CACHE, NET_SERVER_QPROC_GET_SYS_TIMESTAMP, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_UTIME_SIZE, and xqmgr_dump_query_cache().
Referenced by help_print_info().
void qmgr_dump_query_plans (FILE * outfp)
Definition at line 7055 of file network_interface_cl.c.
References net_client_request_recv_stream(), NET_SERVER_QM_QUERY_DUMP_PLANS, NULL, and xqmgr_dump_query_plans().
Referenced by help_print_info(), and plandump().
int qmgr_end_query (QUERY_ID query_id)
Definition at line 6930 of file network_interface_cl.c.
References assert, CAST_BUFLEN, ER_FAILED, i, MAX_ALIGNMENT, net_client_request(), NET_DEFER_END_QUERIES_MAX, NET_SERVER_QM_QUERY_END, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_pack_ptr(), OR_PTR_SIZE, or_unpack_int(), success(), and xqmgr_end_query().
Referenced by db_query_end_internal(), do_execute_merge(), do_merge(), and pt_end_query().
QFILE_LIST_ID* qmgr_execute_query (const XASL_ID * xasl_id, QUERY_ID * query_idp, int dbval_cnt, const DB_VALUE * dbvals, QUERY_FLAG flag, CACHE_TIME * clt_cache_time, CACHE_TIME * srv_cache_time, int query_timeout)
Definition at line 6572 of file network_interface_cl.c.
References ARG_FILE_LINE, assert, CAST_BUFLEN, cleanup(), db_get_object(), db_make_null(), db_make_oid(), db_private_alloc, db_private_free, db_set_execution_plan(), DB_TYPE_OBJECT, db_value_clear(), db_value_clone(), DB_VALUE_TYPE, ER_ERROR_SEVERITY, er_log_debug, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), EXECUTE_QUERY_MAX_ARGUMENT_DATA_SIZE, EXECUTE_QUERY_WITHOUT_DATA_BUFFERS, free_and_init, i, IS_QUERY_EXECUTE_WITH_COMMIT, IS_QUERY_EXECUTED_WITHOUT_DATA_BUFFERS, IS_TRAN_AUTO_COMMIT, qfile_list_id::last_pgptr, net_cleanup_client_queues(), net_client_request_with_callback(), NET_DEFER_END_QUERIES_MAX, NET_SERVER_QM_QUERY_EXECUTE, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_CACHE_TIME_SIZE, OR_INT_SIZE, OR_PACK_CACHE_TIME, or_pack_db_value(), or_pack_int(), or_pack_ptr(), OR_PACK_XASL_ID, OR_PTR_ALIGNED_SIZE, OR_PTR_SIZE, OR_UNPACK_CACHE_TIME, or_unpack_int(), or_unpack_ptr(), or_unpack_unbound_listid(), OR_VALUE_ALIGNED_SIZE, OR_XASL_ID_SIZE, prm_get_bool_value(), PRM_ID_ER_LOG_DEBUG, tran_set_latest_query_status(), TRAN_UNACTIVE_ABORTED, TRAN_UNACTIVE_ABORTED_INFORMING_PARTICIPANTS, TRAN_UNACTIVE_COMMITTED, TRAN_UNACTIVE_COMMITTED_INFORMING_PARTICIPANTS, ws_identifier(), and xqmgr_execute_query().
Referenced by execute_query().
QFILE_LIST_ID* qmgr_prepare_and_execute_query (char * xasl_stream, int xasl_stream_size, QUERY_ID * query_id, int dbval_cnt, DB_VALUE * dbval_ptr, QUERY_FLAG flag, int query_timeout)
Definition at line 6823 of file network_interface_cl.c.
References ARG_FILE_LINE, CAST_BUFLEN, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, i, qfile_list_id::last_pgptr, net_client_request_with_callback(), NET_SERVER_QM_QUERY_PREPARE_AND_EXECUTE, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_db_value(), or_pack_int(), OR_PTR_ALIGNED_SIZE, or_unpack_int(), or_unpack_ptr(), or_unpack_unbound_listid(), OR_VALUE_ALIGNED_SIZE, page_size, and xqmgr_prepare_and_execute_query().
Referenced by prepare_and_execute_query().
int qmgr_prepare_query (struct compile_context * context, xasl_stream * stream)
Definition at line 6391 of file network_interface_cl.c.
References ARG_FILE_LINE, assert, ASSERT_ERROR, xasl_stream::buffer, xasl_stream::buffer_size, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, INIT_XASL_NODE_HEADER, compile_context::is_xasl_pinned_reference, net_client_request2(), NET_SERVER_QM_QUERY_PREPARE, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_pack_sha1(), OR_SHA1_SIZE, or_unpack_int(), OR_UNPACK_XASL_ID, OR_UNPACK_XASL_NODE_HEADER, OR_XASL_ID_SIZE, compile_context::recompile_xasl, compile_context::recompile_xasl_pinned, compile_context::sha1, compile_context::sql_hash_text, compile_context::sql_plan_text, compile_context::sql_user_text, compile_context::sql_user_text_len, xasl_stream::xasl_header, xasl_stream::xasl_id, and xqmgr_prepare_query().
Referenced by prepare_query().
int qp_get_server_info (PARSER_CONTEXT * parser, int server_info_bits)
Definition at line 8178 of file network_interface_cl.c.
References db_local_transaction_id(), db_sys_date_and_epoch_time(), ER_FAILED, free_and_init, parser_context::local_transaction_id, net_client_request2(), NET_SERVER_QPROC_GET_SERVER_INFO, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), or_unpack_value(), SI_LOCAL_TRANSACTION_ID, SI_SYS_DATETIME, success(), parser_context::sys_datetime, and parser_context::sys_epochtime.
Referenced by db_execute_and_keep_statement_local(), and pt_exec_trigger_stmt().
BTREE_SEARCH repl_btree_find_unique (BTID * btid, DB_VALUE * key, OID * class_oid, OID * oid)
int repl_log_get_append_lsa (LOG_LSA * lsa)
Definition at line 8569 of file network_interface_cl.c.
References ER_FAILED, LSA_COPY(), net_client_request(), NET_SERVER_REPL_LOG_GET_APPEND_LSA, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_LOG_LSA_ALIGNED_SIZE, or_unpack_log_lsa(), success(), and xrepl_log_get_append_lsa().
Referenced by locator_get_append_lsa().
int repl_set_info (REPL_INFO * repl_info)
Definition at line 8621 of file network_interface_cl.c.
References ARG_FILE_LINE, repl_info_statement::db_user, ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, repl_info::info, repl_info_statement::name, net_client_request(), NET_SERVER_REPL_INFO, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), repl_info::repl_info_type, REPL_INFO_TYPE_SBR, repl_info_statement::statement_type, repl_info_statement::stmt_text, success(), repl_info_statement::sys_prm_context, and xrepl_set_info().
Referenced by locator_flush_replication_info().
int serial_decache (OID * oid)
Definition at line 7274 of file network_interface_cl.c.
References net_client_request(), NET_SERVER_SERIAL_DECACHE, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_OID_SIZE, or_pack_oid(), or_unpack_int(), and xserial_decache().
Referenced by dbt_drop_attribute(), do_alter_serial(), do_change_att_schema_only(), do_drop_serial(), do_update_maxvalue_of_auto_increment_serial(), and sm_delete_class_mop().
int serial_get_current_value (DB_VALUE * value, OID * oid_p, int cached_num)
Definition at line 7165 of file network_interface_cl.c.
References ER_NET_CLIENT_DATA_RECEIVE, error(), free_and_init, net_client_request2(), NET_SERVER_QPROC_GET_CURRENT_VALUE, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_OID_SIZE, or_pack_int(), or_pack_oid(), or_unpack_int(), or_unpack_value(), and xserial_get_current_value().
Referenced by db_get_serial_current_value(), and pt_evaluate_tree_internal().
int serial_get_next_value (DB_VALUE * value, OID * oid_p, int cached_num, int num_alloc, int is_auto_increment)
Definition at line 7217 of file network_interface_cl.c.
References ER_NET_CLIENT_DATA_RECEIVE, error(), free_and_init, net_client_request2(), NET_SERVER_QPROC_GET_NEXT_VALUE, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_OID_SIZE, or_pack_int(), or_pack_oid(), or_unpack_int(), or_unpack_value(), and xserial_get_next_value().
Referenced by db_get_serial_next_value_ex(), populate_auto_increment(), and pt_evaluate_tree_internal().
int stats_get_statistics_from_server (OID * classoid, unsigned int timestamp, int * length_ptr, char ** stats_buffer)
Definition at line 5432 of file network_interface_cl.c.
References assert, net_client_request2(), NET_SERVER_QST_GET_STATISTICS, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_OID_SIZE, or_pack_int(), or_pack_oid(), or_unpack_int(), and xstats_get_statistics_from_server().
Referenced by stats_get_statistics().
int stats_update_all_statistics (int with_fullscan)
Definition at line 5532 of file network_interface_cl.c.
References ER_NET_CLIENT_DATA_RECEIVE, error(), net_client_request(), NET_SERVER_QST_UPDATE_ALL_STATISTICS, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_errcode(), STATS_WITH_FULLSCAN, STATS_WITH_SAMPLING, success(), and xstats_update_all_statistics().
Referenced by sm_update_all_statistics().
int stats_update_statistics (OID * classoid, int with_fullscan)
Definition at line 5484 of file network_interface_cl.c.
References ER_NET_CLIENT_DATA_RECEIVE, error(), net_client_request(), NET_SERVER_QST_UPDATE_STATISTICS, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_OID_SIZE, or_pack_int(), or_pack_oid(), or_unpack_errcode(), STATS_WITH_FULLSCAN, STATS_WITH_SAMPLING, success(), and xstats_update_statistics().
Referenced by sm_update_statistics().
int tde_change_mk_on_server (int mk_index)
Definition at line 1988 of file network_interface_cl.c.
References ER_NET_CLIENT_DATA_RECEIVE, error(), net_client_request(), NET_SERVER_TDE_CHANGE_MK_ON_SERVER, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_errcode(), success(), and xtde_change_mk_without_flock().
Referenced by tde().
int tde_get_mk_file_path (char * mk_path)
Definition at line 1898 of file network_interface_cl.c.
References boot_db_full_name(), DB_MAX_PATH_LENGTH, ER_NET_CLIENT_DATA_RECEIVE, error(), free_and_init, net_client_request2(), NET_SERVER_TDE_GET_MK_FILE_PATH, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), or_unpack_string_nocopy(), and tde_make_keys_file_fullname().
Referenced by tde().
int tde_get_mk_info (int * mk_index, time_t * created_time, time_t * set_time)
Definition at line 1942 of file network_interface_cl.c.
References ER_NET_CLIENT_DATA_RECEIVE, error(), net_client_request(), NET_SERVER_TDE_GET_MK_INFO, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_BIGINT_SIZE, OR_INT_SIZE, or_unpack_errcode(), or_unpack_int(), or_unpack_int64(), success(), and xtde_get_mk_info().
Referenced by tde().
void thread_dump_cs_stat (FILE * outfp)
Definition at line 7671 of file network_interface_cl.c.
References ARG_FILE_LINE, er_log_debug, net_client_request_recv_stream(), NET_SERVER_CSS_DUMP_CS_STAT, and NULL.
Referenced by help_print_info().
int thread_kill_or_interrupt_tran (int * tran_index_list, int num_tran_index, bool is_dba_group_member, bool interrupt_only, int * num_killed)
Definition at line 7610 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_FAILED, er_log_debug, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, i, net_client_request(), NET_SERVER_CSS_KILL_OR_INTERRUPT_TRANSACTION, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), and success().
Referenced by do_kill().
int thread_kill_tran_index (int kill_tran_index, char * kill_user, char * kill_host, int kill_pid)
Definition at line 7553 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_FAILED, er_log_debug, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, net_client_request(), NET_SERVER_CSS_KILL_TRANSACTION, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), and success().
Referenced by csql_killtran(), and kill_transactions().
const char* tran_get_tranlist_state_name (TRAN_STATE state)
Definition at line 2773 of file network_interface_cl.c.
References TRAN_ACTIVE, TRAN_RECOVERY, TRAN_UNACTIVE_2PC_ABORT_DECISION, TRAN_UNACTIVE_2PC_COLLECTING_PARTICIPANT_VOTES, TRAN_UNACTIVE_2PC_COMMIT_DECISION, TRAN_UNACTIVE_2PC_PREPARE, TRAN_UNACTIVE_ABORTED, TRAN_UNACTIVE_ABORTED_INFORMING_PARTICIPANTS, TRAN_UNACTIVE_COMMITTED, TRAN_UNACTIVE_COMMITTED_INFORMING_PARTICIPANTS, TRAN_UNACTIVE_COMMITTED_WITH_POSTPONE, TRAN_UNACTIVE_TOPOPE_COMMITTED_WITH_POSTPONE, TRAN_UNACTIVE_UNILATERALLY_ABORTED, TRAN_UNACTIVE_UNKNOWN, and TRAN_UNACTIVE_WILL_COMMIT.
Referenced by csql_dump_alltran(), csql_killtran(), and print_tran_entry().
bool tran_is_blocked (int tran_index)
Definition at line 2828 of file network_interface_cl.c.
References net_client_request(), NET_SERVER_TM_ISBLOCKED, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), and xtran_is_blocked().
int tran_lock_rep_read (LOCK lock_rr_tran)
Definition at line 9804 of file network_interface_cl.c.
References net_client_request(), NET_SERVER_LOCK_RR, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), and tm_Tran_rep_read_lock.
Referenced by pt_class_pre_fetch().
int tran_server_2pc_attach_global_tran (int gtrid)
Definition at line 3233 of file network_interface_cl.c.
References net_client_request(), NET_SERVER_TM_SERVER_2PC_ATTACH_GT, NULL, NULL_TRAN_INDEX, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), and xtran_server_2pc_attach_global_tran().
Referenced by tran_2pc_attach_global_tran().
TRAN_STATE tran_server_2pc_prepare (void)
Definition at line 3133 of file network_interface_cl.c.
References net_client_request(), NET_SERVER_TM_SERVER_2PC_PREPARE, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), TRAN_UNACTIVE_UNKNOWN, and xtran_server_2pc_prepare().
Referenced by tran_2pc_prepare().
TRAN_STATE tran_server_2pc_prepare_global_tran (int gtrid)
Definition at line 3280 of file network_interface_cl.c.
References ER_FAILED, net_client_request(), NET_SERVER_TM_SERVER_2PC_PREPARE_GT, NET_SERVER_TM_SERVER_END_TOPOP, NET_SERVER_TM_SERVER_START_TOPOP, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_LOG_LSA_ALIGNED_SIZE, or_pack_int(), or_unpack_int(), or_unpack_log_lsa(), success(), TRAN_UNACTIVE_UNKNOWN, xtran_server_2pc_prepare_global_tran(), xtran_server_end_topop(), and xtran_server_start_topop().
Referenced by tran_2pc_prepare_global_tran().
int tran_server_2pc_recovery_prepared (int gtrids[], int size)
Definition at line 3176 of file network_interface_cl.c.
References ARG_FILE_LINE, cubregex::count(), ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, i, net_client_request(), NET_SERVER_TM_SERVER_2PC_RECOVERY_PREPARED, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), and xtran_server_2pc_recovery_prepared().
Referenced by tran_2pc_recovery_prepared().
int tran_server_2pc_start (void)
Definition at line 3093 of file network_interface_cl.c.
References net_client_request(), NET_SERVER_TM_SERVER_2PC_START, NULL, NULL_TRANID, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), and xtran_server_2pc_start().
Referenced by tran_2pc_start().
TRAN_STATE tran_server_abort (void)
Definition at line 2724 of file network_interface_cl.c.
References ARG_FILE_LINE, db_Connect_status, DB_CONNECTION_STATUS_RESET, er_log_debug, log_does_allow_replication(), net_cleanup_client_queues(), net_client_request(), NET_SERVER_TM_SERVER_ABORT, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), TRAN_UNACTIVE_UNKNOWN, and xtran_server_abort().
Referenced by tran_abort().
TRAN_STATE tran_server_commit (bool retain_lock)
Definition at line 2645 of file network_interface_cl.c.
References ARG_FILE_LINE, assert, CAST_BUFLEN, db_Connect_status, DB_CONNECTION_STATUS_RESET, db_get_row_count_cache(), er_log_debug, i, log_does_allow_replication(), MAX_ALIGNMENT, net_cleanup_client_queues(), net_client_request(), NET_DEFER_END_QUERIES_MAX, NET_SERVER_TM_SERVER_COMMIT, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_pack_ptr(), OR_PTR_SIZE, or_unpack_int(), TRAN_UNACTIVE_UNKNOWN, and xtran_server_commit().
Referenced by tran_commit().
int tran_server_get_global_tran_info (int gtrid, void * buffer, int size)
Definition at line 3046 of file network_interface_cl.c.
References ER_FAILED, net_client_request2_no_malloc(), NET_SERVER_TM_SERVER_GET_GTRINFO, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), success(), and xtran_server_get_global_tran_info().
Referenced by tran_get_global_tran_info().
int tran_server_has_updated (void)
Definition at line 2875 of file network_interface_cl.c.
References net_client_request(), NET_SERVER_TM_SERVER_HAS_UPDATED, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), and xtran_server_has_updated().
Referenced by tran_has_updated().
int tran_server_is_active_and_has_updated (void)
Definition at line 2915 of file network_interface_cl.c.
References BO_IS_SERVER_RESTARTED, net_client_request(), NET_SERVER_TM_SERVER_ISACTIVE_AND_HAS_UPDATED, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), and xtran_server_is_active_and_has_updated().
Referenced by tran_is_active_and_has_updated().
TRAN_STATE tran_server_partial_abort (const char * savept_name, LOG_LSA * savept_lsa)
Definition at line 3485 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, net_client_request(), NET_SERVER_TM_SERVER_PARTIAL_ABORT, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_LOG_LSA_ALIGNED_SIZE, or_unpack_int(), or_unpack_log_lsa(), strlen, TRAN_UNACTIVE_UNKNOWN, and xtran_server_partial_abort().
Referenced by tran_internal_abort_upto_savepoint().
int tran_server_savepoint (const char * savept_name, LOG_LSA * savept_lsa)
Definition at line 3430 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, net_client_request(), NET_SERVER_TM_SERVER_SAVEPOINT, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, OR_LOG_LSA_ALIGNED_SIZE, or_unpack_int(), or_unpack_log_lsa(), strlen, success(), and xtran_server_savepoint().
Referenced by tran_savepoint_internal().
int tran_server_set_global_tran_info (int gtrid, void * info, int size)
Definition at line 2997 of file network_interface_cl.c.
References ER_FAILED, net_client_request(), NET_SERVER_TM_SERVER_SET_GTRINFO, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_unpack_int(), success(), and xtran_server_set_global_tran_info().
Referenced by tran_set_global_tran_info().
int tran_wait_server_active_trans (void)
Definition at line 2961 of file network_interface_cl.c.
References net_client_request(), NET_SERVER_TM_WAIT_SERVER_ACTIVE_TRANS, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, and or_unpack_int().
Referenced by boot_shutdown_client().
void vacuum_dump (FILE * outfp)
Definition at line 9566 of file network_interface_cl.c.
References net_client_request_recv_stream(), NET_SERVER_VACUUM_DUMP, NULL, and xvacuum_dump().
Referenced by vacuumdb().