CUBRID Engine: src/communication/network_cl.c File Reference
network_cl.c File Reference
#include "config.h"
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <sys/time.h>
#include <sys/resource.h>
#include "network.h"
#include "network_interface_cl.h"
#include "chartype.h"
#include "connection_cl.h"
#include "server_interface.h"
#include "memory_alloc.h"
#include "databases_file.h"
#include "error_manager.h"
#include "system_parameter.h"
#include "environment_variable.h"
#include "boot_cl.h"
#include "query_method.h"
#include "method_def.hpp"
#include "release_string.h"
#include "log_comm.h"
#include "file_io.h"
#include "locator.h"
#include "db.h"
#include "client_support.h"
#include "perf_monitor.h"
#include "log_writer.h"
#include "object_representation.h"
Classes
struct net_request_buffer
Macros
#define COMPARE_SIZE_AND_BUFFER(replysize, size, replybuf, buf)
#define COMPARE_AND_FREE_BUFFER(queued, reply)
Functions
static void return_error_to_server (char *host, unsigned int eid)
static int client_capabilities (void)
static int check_server_capabilities (int server_cap, int client_type, int rel_compare, REL_COMPATIBILITY *compatibility, const char *server_host, int opt_cap)
static int net_set_alloc_err_if_not_set (int err, const char *file, const int line)
static void net_consume_expected_packets (int rc, int num_packets)
static int compare_size_and_buffer (int *replysize, int size, char **replybuf, char *buf, const char *file, const int line)
static int net_client_request_internal (int request, char *argbuf, int argsize, char *replybuf, int replysize, char *databuf, int datasize, char *replydata, int replydatasize)
static int set_server_error (int error)
static void net_histo_setup_names (void)
static void net_histo_add_entry (int request, int data_sent)
static void net_histo_request_finished (int request, int data_received)
static const char * get_capability_string (int cap, int cap_type)
void net_histo_clear (void)
int net_histo_print (FILE *stream)
int net_histo_print_global_stats (FILE *stream, bool cumulative, const char *substr)
int net_histo_start (bool for_all_trans)
int net_histo_stop (void)
int net_client_request_no_reply (int request, char *argbuf, int argsize)
char * net_client_get_server_host (void)
int net_client_request (int request, char *argbuf, int argsize, char *replybuf, int replysize, char *databuf, int datasize, char *replydata, int replydatasize)
int net_client_request2 (int request, char *argbuf, int argsize, char *replybuf, int replysize, char *databuf, int datasize, char **replydata_ptr, int *replydatasize_ptr)
int net_client_request2_no_malloc (int request, char *argbuf, int argsize, char *replybuf, int replysize, char *databuf, int datasize, char *replydata, int *replydatasize_ptr)
int net_client_request_3_data (int request, char *argbuf, int argsize, char *databuf1, int datasize1, char *databuf2, int datasize2, char *reply0, int replysize0, char *reply1, int replysize1, char *reply2, int replysize2)
int net_client_request_with_callback (int request, char *argbuf, int argsize, char *replybuf, int replysize, char *databuf1, int datasize1, char *databuf2, int datasize2, char **replydata_listid, int *replydatasize_listid, char **replydata_page, int *replydatasize_page, char **replydata_plan, int *replydatasize_plan)
int net_client_check_log_header (LOGWR_CONTEXT *ctx_ptr, char *argbuf, int argsize, char *replybuf, int replysize, char **logpg_area_buf, bool verbose)
int net_client_request_with_logwr_context (LOGWR_CONTEXT *ctx_ptr, int request, char *argbuf, int argsize, char *replybuf, int replysize, char *databuf1, int datasize1, char *databuf2, int datasize2, char **replydata_ptr1, int *replydatasize_ptr1, char **replydata_ptr2, int *replydatasize_ptr2)
void net_client_logwr_send_end_msg (int rc, int error)
int net_client_get_next_log_pages (int rc, char *replybuf, int replysize, int length)
int net_client_request_recv_copyarea (int request, char *argbuf, int argsize, char *replybuf, int replysize, LC_COPYAREA **reply_copy_area)
int net_client_request_2recv_copyarea (int request, char *argbuf, int argsize, char *replybuf, int replysize, char *databuf, int datasize, char *recvbuffer, int recvbuffer_size, LC_COPYAREA **reply_copy_area, int *eid)
int net_client_request_3_data_recv_copyarea (int request, char *argbuf, int argsize, char *databuf1, int datasize1, char *databuf2, int datasize2, char *replybuf, int replysize, LC_COPYAREA **reply_copy_area)
int net_client_recv_copyarea (int request, char *replybuf, int replysize, char *recvbuffer, int recvbuffer_size, LC_COPYAREA **reply_copy_area, int rc)
int net_client_request_3recv_copyarea (int request, char *argbuf, int argsize, char *replybuf, int replysize, char *databuf, int datasize, char **recvbuffer, int *recvbuffer_size, LC_COPYAREA **reply_copy_area)
int net_client_request_recv_stream (int request, char *argbuf, int argsize, char *replybuf, int replybuf_size, char *databuf, int datasize, FILE *outfp)
int net_client_ping_server (int client_val, int *server_val, int timeout)
int net_client_ping_server_with_handshake (int client_type, bool check_capabilities, int opt_cap)
int net_client_init (const char *dbname, const char *hostname)
void net_cleanup_client_queues (void)
int net_client_final (void)
int net_client_send_data (char *host, unsigned int rc, char *databuf, int datasize)
int net_client_receive_action (int rc, int *action)
Variables
static struct net_request_buffer net_Req_buffer [NET_SERVER_REQUEST_END]
static int net_Histo_setup = 0
static int net_Histo_setup_mnt = 0
static int net_Histo_call_count = 0
static INT64 net_Histo_last_call_time = 0
static INT64 net_Histo_total_server_time = 0
static char net_Server_host [CUB_MAXHOSTNAMELEN+1] = ""
static char net_Server_name [DB_MAX_IDENTIFIER_LENGTH+1] = ""
Macro Definition Documentation
#define COMPARE_AND_FREE_BUFFER (queued, reply)
Value:
do { \
    if (((reply) != NULL) && ((reply) != (queued))) { \
      free_and_init ((reply)); \
    } \
    (reply) = NULL; \
  } while (0)
Definition at line 72 of file network_cl.c.
Referenced by net_client_check_log_header(), net_client_get_next_log_pages(), net_client_ping_server(), net_client_ping_server_with_handshake(), net_client_recv_copyarea(), net_client_request(), net_client_request2(), net_client_request2_no_malloc(), net_client_request_2recv_copyarea(), net_client_request_3_data(), net_client_request_3_data_recv_copyarea(), net_client_request_3recv_copyarea(), net_client_request_internal(), net_client_request_recv_copyarea(), net_client_request_recv_stream(), net_client_request_with_callback(), and net_client_request_with_logwr_context().
#define COMPARE_SIZE_AND_BUFFER (replysize, size, replybuf, buf)
Value:
compare_size_and_buffer((replysize), (size), (replybuf), (buf),     \
              __FILE__, __LINE__)
Definition at line 68 of file network_cl.c.
Referenced by net_client_check_log_header(), net_client_recv_copyarea(), net_client_request(), net_client_request2(), net_client_request2_no_malloc(), net_client_request_2recv_copyarea(), net_client_request_3_data(), net_client_request_3_data_recv_copyarea(), net_client_request_3recv_copyarea(), net_client_request_internal(), net_client_request_recv_copyarea(), net_client_request_recv_stream(), net_client_request_with_callback(), and net_client_request_with_logwr_context().
Function Documentation
static int check_server_capabilities (int server_cap, int client_type, int rel_compare, REL_COMPATIBILITY * compatibility, const char * server_host, int opt_cap) static
Definition at line 282 of file network_cl.c.
References ARG_FILE_LINE, assert, boot_Host_name, BOOT_IS_ALLOWED_CLIENT_TYPE_IN_MT_MODE, BOOT_REPLICA_ONLY_BROKER_CLIENT_TYPE, client_capabilities(), DB_HS_HA_DELAYED, DB_HS_MISMATCHED_RW_MODE, db_set_host_status(), ER_ERROR_SEVERITY, ER_NET_HS_HA_REPL_DELAY, ER_NET_HS_HA_REPLICA_ONLY, ER_NET_HS_INCOMPAT_INTERRUPTIBILITY, ER_NET_HS_INCOMPAT_RW_MODE, ER_NET_HS_REMOTE_DISABLED, er_set(), get_capability_string(), NET_CAP_BACKWARD_COMPATIBLE, NET_CAP_FORWARD_COMPATIBLE, NET_CAP_HA_REPL_DELAY, NET_CAP_HA_REPLICA, NET_CAP_INTERRUPT_ENABLED, NET_CAP_REMOTE_DISABLED, NET_CAP_UPDATE_DISABLED, net_Server_host, NULL, REL_BACKWARD_COMPATIBLE, REL_FORWARD_COMPATIBLE, and REL_NOT_COMPATIBLE.
Referenced by net_client_ping_server_with_handshake().
static int client_capabilities (void) static
Definition at line 230 of file network_cl.c.
References db_Disable_modifications, db_need_ignore_repl_delay(), NET_CAP_HA_IGNORE_REPL_DELAY, NET_CAP_INTERRUPT_ENABLED, and NET_CAP_UPDATE_DISABLED.
Referenced by check_server_capabilities(), net_client_ping_server_with_handshake(), and server_ping_with_handshake().
static int compare_size_and_buffer (int * replysize, int size, char ** replybuf, char * buf, const char * file, const int line) static
Definition at line 427 of file network_cl.c.
References ER_ERROR_SEVERITY, ER_NET_DATASIZE_MISMATCH, ER_NET_UNUSED_BUFFER, er_set(), err, and NO_ERROR.
static const char * get_capability_string (int cap, int cap_type) static
Definition at line 255 of file network_cl.c.
References NET_CAP_INTERRUPT_ENABLED, and NET_CAP_UPDATE_DISABLED.
Referenced by check_server_capabilities().
void net_cleanup_client_queues (void)
Definition at line 3975 of file network_cl.c.
References css_cleanup_client_queues(), net_Server_host, and net_Server_name.
Referenced by qmgr_execute_query(), tran_server_abort(), and tran_server_commit().
int net_client_check_log_header (LOGWR_CONTEXT * ctx_ptr, char * argbuf, int argsize, char * replybuf, int replysize, char ** logpg_area_buf, bool verbose)
Definition at line 2216 of file network_cl.c.
References ARG_FILE_LINE, COMPARE_AND_FREE_BUFFER, COMPARE_SIZE_AND_BUFFER, css_Errno, css_queue_receive_data_buffer(), css_receive_data_from_server(), css_send_req_to_server_2_data(), END_CALLBACK, ER_ERROR_SEVERITY, ER_NET_SERVER_CRASHED, ER_NET_SERVER_DATA_RECEIVE, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), GET_NEXT_LOG_PAGES, net_client_send_data(), net_Server_host, NET_SERVER_LOGWR_GET_LOG_PAGES, net_Server_name, NO_ERROR, NULL, or_unpack_int(), logwr_context::rc, rc, and set_server_error().
int net_client_final (void)
Definition at line 3991 of file network_cl.c.
References css_terminate(), and NO_ERROR.
Referenced by boot_shutdown_client().
int net_client_get_next_log_pages (int rc, char * replybuf, int replysize, int length)
Definition at line 2518 of file network_cl.c.
References ARG_FILE_LINE, COMPARE_AND_FREE_BUFFER, css_queue_receive_data_buffer(), css_receive_data_from_server(), ER_ERROR_SEVERITY, ER_NET_SERVER_CRASHED, er_set(), error(), LOGWR_MODE_ASYNC, LOGWR_MODE_SEMISYNC, LOGWR_MODE_SYNC, NO_ERROR, NULL, and set_server_error().
Referenced by net_client_request_with_logwr_context().
char* net_client_get_server_host (void)
Definition at line 936 of file network_cl.c.
References net_Server_host.
int net_client_init (const char * dbname, const char * hostname)
Definition at line 3921 of file network_cl.c.
References ARG_FILE_LINE, css_client_init(), css_terminate(), CUB_MAXHOSTNAMELEN, DB_MAX_IDENTIFIER_LENGTH, ER_ERROR_SEVERITY, ER_NET_INVALID_HOST_NAME, ER_NET_INVALID_SERVER_NAME, er_set(), error(), net_Server_host, net_Server_name, NO_ERROR, NULL, prm_get_integer_value(), PRM_ID_TCP_PORT_ID, and strlen.
Referenced by boot_client_all_finalize().
void net_client_logwr_send_end_msg (int rc, int error)
Definition at line 2487 of file network_cl.c.
References LOGPB_HEADER_PAGE_ID, LOGWR_MODE_ASYNC, net_client_send_data(), net_Server_host, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT64_SIZE, OR_INT_SIZE, or_pack_int(), and or_pack_int64().
int net_client_ping_server (int client_val, int * server_val, int timeout)
Definition at line 3727 of file network_cl.c.
References ARG_FILE_LINE, COMPARE_AND_FREE_BUFFER, css_receive_data_from_server_with_timeout(), css_send_request_to_server_with_buffer(), eid, ER_ERROR_SEVERITY, er_log_debug, ER_NET_CANT_CONNECT_SERVER, ER_NET_NO_SERVER_HOST, ER_NET_SERVER_DATA_RECEIVE, er_set(), error(), net_Server_host, net_Server_name, NET_SERVER_PING, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), and or_unpack_int().
Referenced by db_ping_server().
int net_client_ping_server_with_handshake (int client_type, bool check_capabilities, int opt_cap)
Definition at line 3782 of file network_cl.c.
References ARG_FILE_LINE, boot_Host_name, check_server_capabilities(), client_capabilities(), COMPARE_AND_FREE_BUFFER, css_receive_data_from_server(), css_send_request_to_server_with_buffer(), CUB_MAXHOSTNAMELEN, eid, er_errid(), ER_ERROR_SEVERITY, ER_NET_CANT_CONNECT_SERVER, ER_NET_DIFFERENT_BIT_PLATFORM, ER_NET_DIFFERENT_RELEASE, ER_NET_HS_UNKNOWN_SERVER_REL, ER_NET_NO_SERVER_HOST, ER_NET_SERVER_DATA_RECEIVE, ER_NET_SERVER_HAND_SHAKE, ER_NET_UNUSED_BUFFER, er_set(), error(), free_and_init, NET_CAP_REMOTE_DISABLED, net_Server_host, net_Server_name, NET_SERVER_PING_WITH_HANDSHAKE, NET_SERVER_SHUTDOWN, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_pack_int(), or_pack_string_with_length(), or_packed_string_length(), or_unpack_int(), or_unpack_string_nocopy(), rel_bit_platform(), rel_compare(), rel_get_net_compatible(), REL_MAX_RELEASE_LENGTH, REL_NOT_COMPATIBLE, rel_release_string(), and server_capabilities().
Referenced by boot_client_all_finalize().
int net_client_receive_action (int rc, int * action)
Definition at line 4037 of file network_cl.c.
References ARG_FILE_LINE, css_receive_data_from_server(), ER_ERROR_SEVERITY, ER_NET_DATASIZE_MISMATCH, ER_NET_SERVER_CRASHED, er_set(), error(), free_and_init, net_Server_name, NO_ERROR, NULL, OR_INT_SIZE, or_unpack_int(), and set_server_error().
Referenced by method_send_value_to_server().
int net_client_recv_copyarea (int request, char * replybuf, int replysize, char * recvbuffer, int recvbuffer_size, LC_COPYAREA ** reply_copy_area, int rc)
Definition at line 3169 of file network_cl.c.
References ARG_FILE_LINE, assert, ASSERT_ERROR_AND_SET, CANT_ALLOC_BUFFER, COMPARE_AND_FREE_BUFFER, COMPARE_SIZE_AND_BUFFER, css_queue_receive_data_buffer(), css_receive_data_from_server(), ER_ERROR_SEVERITY, ER_FAILED, ER_NET_DATASIZE_MISMATCH, ER_NET_SERVER_CRASHED, ER_NET_UNUSED_BUFFER, er_set(), error(), free_and_init, locator_recv_allocate_copyarea(), locator_unpack_copy_area_descriptor(), net_consume_expected_packets(), net_histo_add_entry(), net_histo_request_finished(), net_Histo_setup, net_Server_name, NO_ERROR, NULL, or_unpack_int(), and set_server_error().
Referenced by locator_fetch_lockhint_classes(), and locator_fetch_lockset().
int net_client_request (int request, char * argbuf, int argsize, char * replybuf, int replysize, char * databuf, int datasize, char * replydata, int replydatasize)
Definition at line 1053 of file network_cl.c.
References ARG_FILE_LINE, CANT_ALLOC_BUFFER, COMPARE_AND_FREE_BUFFER, COMPARE_SIZE_AND_BUFFER, css_Errno, css_queue_receive_data_buffer(), css_receive_data_from_server(), css_send_req_to_server(), ER_ERROR_SEVERITY, ER_NET_SERVER_CRASHED, er_set(), error(), free_and_init, i, net_client_request_internal(), net_histo_add_entry(), net_histo_request_finished(), net_Histo_setup, net_Server_host, net_Server_name, NO_ERROR, NULL, or_unpack_int64(), rc, and set_server_error().
Referenced by acl_reload(), boot_add_volume_extension(), boot_change_ha_mode(), boot_compact_classes(), boot_find_last_permanent(), boot_find_last_temp(), boot_find_number_permanent_volumes(), boot_find_number_temp_volumes(), boot_heap_compact(), boot_notify_ha_log_applier_state(), boot_unregister_client(), btree_add_index(), btree_class_test_unique(), btree_delete_index(), btree_find_unique(), btree_get_statistics(), btree_load_index(), catalog_check_rep_dir(), chksum_insert_repl_log_and_demote_table_lock(), clogin_user(), compact_db_start(), compact_db_stop(), csession_create_prepared_statement(), csession_delete_prepared_statement(), csession_drop_session_variables(), csession_end_session(), csession_get_row_count(), csession_reset_cur_insert_id(), csession_set_row_count(), csession_set_session_variables(), cvacuum(), db_local_transaction_id(), disk_get_free_numpages(), disk_get_total_numpages(), es_posix_delete_file(), es_posix_get_file_size(), es_posix_read_file(), es_posix_write_file(), file_apply_tde_to_class_files(), heap_create(), heap_destroy_newly_created(), heap_get_class_num_objects_pages(), heap_has_instance(), heap_reclaim_addresses(), jsp_get_server_port(), loaddb_destroy(), loaddb_init(), loaddb_update_stats(), locator_assign_oid(), locator_assign_oid_batch(), locator_check_fk_validity(), locator_delete_class_name(), locator_demote_class_lock(), locator_find_class_oid(), locator_get_reserved_class_name_oid(), locator_redistribute_partition_data(), locator_remove_class_from_index(), locator_rename_class_name(), locator_reserve_class_names(), locator_upgrade_instances_domain(), log_checkpoint(), log_does_active_user_exist(), log_get_mvcc_snapshot(), log_reset_isolation(), log_reset_wait_msecs(), log_set_suppress_repl_on_transaction(), perfmon_server_copy_global_stats(), perfmon_server_copy_stats(), perfmon_server_start_stats(), perfmon_server_stop_stats(), qmgr_drop_all_query_plans(), qmgr_dump_query_cache(), qmgr_end_query(), repl_log_get_append_lsa(), repl_set_info(), serial_decache(), stats_update_all_statistics(), stats_update_statistics(), sysprm_change_server_parameters(), tde_change_mk_on_server(), tde_get_mk_info(), thread_kill_or_interrupt_tran(), thread_kill_tran_index(), tran_is_blocked(), tran_lock_rep_read(), tran_server_2pc_attach_global_tran(), tran_server_2pc_prepare(), tran_server_2pc_prepare_global_tran(), tran_server_2pc_recovery_prepared(), tran_server_2pc_start(), tran_server_abort(), tran_server_commit(), tran_server_has_updated(), tran_server_is_active_and_has_updated(), tran_server_partial_abort(), tran_server_savepoint(), tran_server_set_global_tran_info(), and tran_wait_server_active_trans().
int net_client_request2 (int request, char * argbuf, int argsize, char * replybuf, int replysize, char * databuf, int datasize, char ** replydata_ptr, int * replydatasize_ptr)
Definition at line 1288 of file network_cl.c.
References ARG_FILE_LINE, COMPARE_AND_FREE_BUFFER, COMPARE_SIZE_AND_BUFFER, css_Errno, css_queue_receive_data_buffer(), css_receive_data_from_server(), css_send_req_to_server(), ER_ERROR_SEVERITY, ER_NET_SERVER_CRASHED, er_set(), error(), free_and_init, net_consume_expected_packets(), net_histo_add_entry(), net_histo_request_finished(), net_Histo_setup, net_Server_host, net_Server_name, net_set_alloc_err_if_not_set(), NO_ERROR, NULL, or_unpack_int(), rc, and set_server_error().
Referenced by boot_get_server_locales(), boot_get_server_timezone_checksum(), boot_register_client(), btree_find_multi_uniques(), btree_get_index_key_type(), csession_find_or_create_session(), csession_get_last_insert_id(), csession_get_prepared_statement(), csession_get_variable(), disk_get_fullname(), disk_get_remarks(), file_apply_tde_to_class_files(), loaddb_fetch_status(), loaddb_install_class(), loaddb_load_batch(), logtb_get_pack_tran_table(), netcl_spacedb(), qmgr_prepare_query(), qp_get_server_info(), serial_get_current_value(), serial_get_next_value(), stats_get_statistics_from_server(), sysprm_get_force_server_parameters(), sysprm_obtain_server_parameters(), and tde_get_mk_file_path().
int net_client_request2_no_malloc (int request, char * argbuf, int argsize, char * replybuf, int replysize, char * databuf, int datasize, char * replydata, int * replydatasize_ptr)
Definition at line 1395 of file network_cl.c.
References ARG_FILE_LINE, COMPARE_AND_FREE_BUFFER, COMPARE_SIZE_AND_BUFFER, css_Errno, css_queue_receive_data_buffer(), css_receive_data_from_server(), css_send_req_to_server(), ER_ERROR_SEVERITY, ER_NET_SERVER_CRASHED, er_set(), error(), net_histo_add_entry(), net_histo_request_finished(), net_Histo_setup, net_Server_host, net_Server_name, NO_ERROR, NULL, or_unpack_int(), rc, and set_server_error().
Referenced by es_posix_copy_file(), es_posix_create_file(), es_posix_rename_file(), log_set_suppress_repl_on_transaction(), qfile_get_list_file_page(), and tran_server_get_global_tran_info().
int net_client_request_2recv_copyarea (int request, char * argbuf, int argsize, char * replybuf, int replysize, char * databuf, int datasize, char * recvbuffer, int recvbuffer_size, LC_COPYAREA ** reply_copy_area, int * eid)
Definition at line 2769 of file network_cl.c.
References ARG_FILE_LINE, assert, ASSERT_ERROR_AND_SET, CANT_ALLOC_BUFFER, COMPARE_AND_FREE_BUFFER, COMPARE_SIZE_AND_BUFFER, css_Errno, css_queue_receive_data_buffer(), css_receive_data_from_server(), css_send_req_to_server(), ER_ERROR_SEVERITY, ER_FAILED, ER_NET_DATASIZE_MISMATCH, ER_NET_SERVER_CRASHED, ER_NET_UNUSED_BUFFER, er_set(), error(), free_and_init, locator_recv_allocate_copyarea(), locator_unpack_copy_area_descriptor(), net_consume_expected_packets(), net_histo_add_entry(), net_histo_request_finished(), net_Histo_setup, net_Server_host, net_Server_name, NO_ERROR, NULL, or_unpack_int(), rc, and set_server_error().
Referenced by locator_fetch_lockhint_classes(), and locator_fetch_lockset().
int net_client_request_3_data (int request, char * argbuf, int argsize, char * databuf1, int datasize1, char * databuf2, int datasize2, char * reply0, int replysize0, char * reply1, int replysize1, char * reply2, int replysize2)
Definition at line 1490 of file network_cl.c.
References ARG_FILE_LINE, COMPARE_AND_FREE_BUFFER, COMPARE_SIZE_AND_BUFFER, css_Errno, css_queue_receive_data_buffer(), css_receive_data_from_server(), css_send_req_to_server_2_data(), ER_ERROR_SEVERITY, ER_NET_SERVER_CRASHED, er_set(), error(), net_histo_add_entry(), net_histo_request_finished(), net_Histo_setup, net_Server_host, net_Server_name, NO_ERROR, NULL, or_unpack_int(), rc, and set_server_error().
Referenced by locator_force().
int net_client_request_3_data_recv_copyarea (int request, char * argbuf, int argsize, char * databuf1, int datasize1, char * databuf2, int datasize2, char * replybuf, int replysize, LC_COPYAREA ** reply_copy_area)
Definition at line 3004 of file network_cl.c.
References ARG_FILE_LINE, assert, ASSERT_ERROR_AND_SET, COMPARE_AND_FREE_BUFFER, COMPARE_SIZE_AND_BUFFER, css_Errno, css_queue_receive_data_buffer(), css_receive_data_from_server(), css_send_req_to_server_2_data(), ER_ERROR_SEVERITY, ER_FAILED, ER_NET_SERVER_CRASHED, er_set(), error(), free_and_init, locator_recv_allocate_copyarea(), locator_unpack_copy_area_descriptor(), net_consume_expected_packets(), net_histo_add_entry(), net_histo_request_finished(), net_Histo_setup, net_Server_host, net_Server_name, NO_ERROR, NULL, or_unpack_int(), set_server_error(), and success().
Referenced by locator_repl_force().
int net_client_request_3recv_copyarea (int request, char * argbuf, int argsize, char * replybuf, int replysize, char * databuf, int datasize, char ** recvbuffer, int * recvbuffer_size, LC_COPYAREA ** reply_copy_area)
Definition at line 3392 of file network_cl.c.
References ARG_FILE_LINE, ASSERT_ERROR_AND_SET, COMPARE_AND_FREE_BUFFER, COMPARE_SIZE_AND_BUFFER, css_Errno, css_queue_receive_data_buffer(), css_receive_data_from_server(), css_send_req_to_server(), ER_ERROR_SEVERITY, ER_FAILED, ER_NET_SERVER_CRASHED, er_set(), error(), free_and_init, locator_recv_allocate_copyarea(), locator_unpack_copy_area_descriptor(), net_consume_expected_packets(), net_histo_add_entry(), net_histo_request_finished(), net_Histo_setup, net_Server_host, net_Server_name, net_set_alloc_err_if_not_set(), NO_ERROR, NULL, or_unpack_int(), rc, and set_server_error().
Referenced by locator_fetch_all_reference_lockset(), and locator_find_lockhint_class_oids().
static int net_client_request_internal (int request, char * argbuf, int argsize, char * replybuf, int replysize, char * databuf, int datasize, char * replydata, int replydatasize) static
Definition at line 961 of file network_cl.c.
References ARG_FILE_LINE, COMPARE_AND_FREE_BUFFER, COMPARE_SIZE_AND_BUFFER, css_Errno, css_queue_receive_data_buffer(), css_receive_data_from_server(), css_send_req_to_server(), ER_ERROR_SEVERITY, ER_NET_SERVER_CRASHED, er_set(), error(), net_histo_add_entry(), net_histo_request_finished(), net_Histo_setup, net_Server_host, net_Server_name, NO_ERROR, NULL, rc, and set_server_error().
Referenced by net_client_request().
int net_client_request_no_reply (int request, char * argbuf, int argsize)
Definition at line 896 of file network_cl.c.
References ARG_FILE_LINE, assert, css_Errno, css_send_req_to_server_no_reply(), ER_ERROR_SEVERITY, ER_NET_SERVER_CRASHED, er_set(), error(), net_histo_add_entry(), net_Histo_setup, net_Server_host, NET_SERVER_LD_INTERRUPT, NET_SERVER_LOG_SET_INTERRUPT, net_Server_name, NO_ERROR, rc, and set_server_error().
Referenced by loaddb_interrupt(), and log_set_interrupt().
int net_client_request_recv_copyarea (int request, char * argbuf, int argsize, char * replybuf, int replysize, LC_COPYAREA ** reply_copy_area)
Definition at line 2583 of file network_cl.c.
References ARG_FILE_LINE, ASSERT_ERROR_AND_SET, COMPARE_AND_FREE_BUFFER, COMPARE_SIZE_AND_BUFFER, css_Errno, css_queue_receive_data_buffer(), css_receive_data_from_server(), css_send_req_to_server(), ER_ERROR_SEVERITY, ER_FAILED, ER_NET_SERVER_CRASHED, er_set(), error(), free_and_init, locator_free_copy_area(), locator_recv_allocate_copyarea(), locator_unpack_copy_area_descriptor(), net_consume_expected_packets(), net_histo_add_entry(), net_histo_request_finished(), net_Histo_setup, net_Server_host, net_Server_name, NO_ERROR, NULL, or_unpack_int(), rc, and set_server_error().
Referenced by locator_does_exist(), locator_fetch(), locator_fetch_all(), locator_get_class(), and locator_notify_isolation_incons().
int net_client_request_recv_stream (int request, char * argbuf, int argsize, char * replybuf, int replybuf_size, char * databuf, int datasize, FILE * outfp)
Definition at line 3587 of file network_cl.c.
References ARG_FILE_LINE, COMPARE_AND_FREE_BUFFER, COMPARE_SIZE_AND_BUFFER, css_Errno, css_queue_receive_data_buffer(), css_receive_data_from_server(), css_send_req_to_server(), ER_ERROR_SEVERITY, ER_NET_CANT_ALLOC_BUFFER, ER_NET_DATASIZE_MISMATCH, ER_NET_SERVER_CRASHED, ER_NET_UNUSED_BUFFER, er_set(), error(), free_and_init, net_histo_add_entry(), net_histo_request_finished(), net_Histo_setup, net_Server_host, net_Server_name, NO_ERROR, NULL, OR_INT_SIZE, or_pack_int(), or_unpack_int(), rc, and set_server_error().
Referenced by acl_dump(), lock_dump(), log_dump_stat(), logtb_dump_trantable(), qmgr_dump_query_cache(), qmgr_dump_query_plans(), sysprm_dump_server_parameters(), thread_dump_cs_stat(), and vacuum_dump().
int net_client_request_with_callback (int request, char * argbuf, int argsize, char * replybuf, int replysize, char * databuf1, int datasize1, char * databuf2, int datasize2, char ** replydata_listid, int * replydatasize_listid, char ** replydata_page, int * replydatasize_page, char ** replydata_plan, int * replydatasize_plan)
Definition at line 1611 of file network_cl.c.
References ARG_FILE_LINE, assert, ASYNC_OBTAIN_USER_INPUT, CAST_STRLEN, char_tolower(), COMPARE_AND_FREE_BUFFER, COMPARE_SIZE_AND_BUFFER, CONSOLE_OUTPUT, css_Errno, css_queue_receive_data_buffer(), css_receive_data_from_server(), CSS_RID_FROM_EID, css_send_req_to_server_2_data(), cursor_free_self_list_id, DB_PAGESIZE, END_CALLBACK, er_clear(), er_errid(), ER_ERROR_SEVERITY, ER_FAILED, ER_FATAL_ERROR_SEVERITY, ER_NET_DATA_TRUNCATED, ER_NET_SERVER_CRASHED, ER_NET_SERVER_DATA_RECEIVE, er_set(), error(), FILEIO_MAX_USER_RESPONSE_SIZE, FILEIO_PROMPT_BOOLEAN_TYPE, FILEIO_PROMPT_DISPLAY_ONLY, FILEIO_PROMPT_RANGE_TYPE, FILEIO_PROMPT_RANGE_WITH_SECONDARY_STRING_TYPE, FILEIO_PROMPT_STRING_TYPE, free_and_init, intl_mbs_casecmp(), qfile_list_id::last_pgptr, METHOD_CALL, method_invoke_for_server(), method_send_error_to_server(), method_sig_list_freemem(), net_client_send_data(), net_consume_expected_packets(), net_histo_add_entry(), net_histo_request_finished(), net_Histo_setup, net_Server_host, net_Server_name, net_set_alloc_err_if_not_set(), NO_ERROR, NULL, OR_INT_SIZE, or_pack_int(), or_pack_string_with_length(), or_unpack_int(), or_unpack_method_sig_list(), or_unpack_string_nocopy(), or_unpack_unbound_listid(), QUERY_END, rc, return_error_to_server(), set_server_error(), str_to_int32(), and strlen.
Referenced by boot_backup(), boot_check_db_consistency(), qmgr_execute_query(), and qmgr_prepare_and_execute_query().
int net_client_request_with_logwr_context (LOGWR_CONTEXT * ctx_ptr, int request, char * argbuf, int argsize, char * replybuf, int replysize, char * databuf1, int datasize1, char * databuf2, int datasize2, char ** replydata_ptr1, int * replydatasize_ptr1, char ** replydata_ptr2, int * replydatasize_ptr2)
Definition at line 2329 of file network_cl.c.
References ARG_FILE_LINE, COMPARE_AND_FREE_BUFFER, COMPARE_SIZE_AND_BUFFER, css_Errno, css_queue_receive_data_buffer(), css_receive_data_from_server(), css_receive_data_from_server_with_timeout(), css_send_req_to_server_2_data(), END_CALLBACK, ER_ERROR_SEVERITY, ER_HA_LW_FAILED_GET_LOG_PAGE, ER_NET_SERVER_CRASHED, ER_NET_SERVER_DATA_RECEIVE, er_set(), error(), GET_NEXT_LOG_PAGES, logwr_context::last_error, LOGWR_MODE_SEMISYNC, net_client_get_next_log_pages(), net_client_send_data(), net_histo_add_entry(), net_histo_request_finished(), net_Histo_setup, net_Server_host, net_Server_name, NO_ERROR, NULL, or_unpack_int(), logwr_context::rc, rc, set_server_error(), and logwr_context::shutdown.
Referenced by logwr_get_log_pages().
int net_client_send_data (char * host, unsigned int rc, char * databuf, int datasize)
Definition at line 4010 of file network_cl.c.
References css_send_data_to_server(), error(), NO_ERROR, NULL, and set_server_error().
Referenced by method_send_eof_to_server(), method_send_error_to_server(), method_send_value_to_server(), net_client_check_log_header(), net_client_logwr_send_end_msg(), net_client_request_with_callback(), and net_client_request_with_logwr_context().
static void net_consume_expected_packets (int rc, int num_packets) static
Definition at line 395 of file network_cl.c.
References css_receive_data_from_server(), free_and_init, i, and NULL.
Referenced by net_client_recv_copyarea(), net_client_request2(), net_client_request_2recv_copyarea(), net_client_request_3_data_recv_copyarea(), net_client_request_3recv_copyarea(), net_client_request_recv_copyarea(), and net_client_request_with_callback().
static void net_histo_add_entry (int request, int data_sent) static
Definition at line 833 of file network_cl.c.
References net_Histo_call_count, net_Histo_last_call_time, net_Req_buffer, NET_SERVER_REQUEST_END, NULL, net_request_buffer::request_count, and net_request_buffer::total_size_sent.
Referenced by net_client_recv_copyarea(), net_client_request(), net_client_request2(), net_client_request2_no_malloc(), net_client_request_2recv_copyarea(), net_client_request_3_data(), net_client_request_3_data_recv_copyarea(), net_client_request_3recv_copyarea(), net_client_request_internal(), net_client_request_no_reply(), net_client_request_recv_copyarea(), net_client_request_recv_stream(), net_client_request_with_callback(), and net_client_request_with_logwr_context().
void net_histo_clear (void)
Definition at line 666 of file network_cl.c.
References net_request_buffer::elapsed_time, i, net_Histo_call_count, net_Histo_last_call_time, net_Histo_setup_mnt, net_Histo_total_server_time, net_Req_buffer, net_request_buffer::request_count, net_request_buffer::total_size_received, and net_request_buffer::total_size_sent.
Referenced by histo_clear(), and net_histo_start().
int net_histo_print (FILE * stream)
Definition at line 695 of file network_cl.c.
References net_request_buffer::elapsed_time, err, i, net_request_buffer::name, net_Histo_setup_mnt, net_Req_buffer, NO_ERROR, NULL, net_request_buffer::request_count, net_request_buffer::total_size_received, and net_request_buffer::total_size_sent.
Referenced by histo_print().
int net_histo_print_global_stats (FILE * stream, bool cumulative, const char * substr)
Definition at line 756 of file network_cl.c.
References err, net_Histo_setup_mnt, and NO_ERROR.
Referenced by histo_print_global_stats().
static void net_histo_request_finished (int request, int data_received) static
Definition at line 866 of file network_cl.c.
References net_request_buffer::elapsed_time, net_Histo_last_call_time, net_Histo_total_server_time, net_Req_buffer, NULL, and net_request_buffer::total_size_received.
Referenced by net_client_recv_copyarea(), net_client_request(), net_client_request2(), net_client_request2_no_malloc(), net_client_request_2recv_copyarea(), net_client_request_3_data(), net_client_request_3_data_recv_copyarea(), net_client_request_3recv_copyarea(), net_client_request_internal(), net_client_request_recv_copyarea(), net_client_request_recv_stream(), net_client_request_with_callback(), and net_client_request_with_logwr_context().
static void net_histo_setup_names (void) static
Definition at line 462 of file network_cl.c.
References net_request_buffer::elapsed_time, i, net_request_buffer::name, net_Req_buffer, NET_SERVER_BO_ADD_VOLEXT, NET_SERVER_BO_BACKUP, NET_SERVER_BO_CHANGE_HA_MODE, NET_SERVER_BO_CHECK_DBCONSISTENCY, NET_SERVER_BO_COMPACT_DB, NET_SERVER_BO_COMPACT_DB_START, NET_SERVER_BO_COMPACT_DB_STOP, NET_SERVER_BO_FIND_LAST_PERM, NET_SERVER_BO_FIND_LAST_TEMP, NET_SERVER_BO_FIND_NPERM_VOLS, NET_SERVER_BO_FIND_NTEMP_VOLS, NET_SERVER_BO_GET_LOCALES_INFO, NET_SERVER_BO_HEAP_COMPACT, NET_SERVER_BO_INIT_SERVER, NET_SERVER_BO_NOTIFY_HA_LOG_APPLIER_STATE, NET_SERVER_BO_REGISTER_CLIENT, NET_SERVER_BO_UNREGISTER_CLIENT, NET_SERVER_BTREE_ADDINDEX, NET_SERVER_BTREE_CLASS_UNIQUE_TEST, NET_SERVER_BTREE_DELINDEX, NET_SERVER_BTREE_FIND_MULTI_UNIQUES, NET_SERVER_BTREE_FIND_UNIQUE, NET_SERVER_BTREE_GET_KEY_TYPE, NET_SERVER_BTREE_GET_STATISTICS, NET_SERVER_BTREE_LOADINDEX, NET_SERVER_CSS_DUMP_CS_STAT, NET_SERVER_CSS_KILL_TRANSACTION, NET_SERVER_CT_CHECK_REP_DIR, NET_SERVER_DISK_FREEPGS, NET_SERVER_DISK_REMARKS, NET_SERVER_DISK_TOTALPGS, NET_SERVER_DISK_VLABEL, NET_SERVER_ES_COPY_FILE, NET_SERVER_ES_CREATE_FILE, NET_SERVER_ES_DELETE_FILE, NET_SERVER_ES_GET_FILE_SIZE, NET_SERVER_ES_READ_FILE, NET_SERVER_ES_RENAME_FILE, NET_SERVER_ES_WRITE_FILE, NET_SERVER_FILE_APPLY_TDE_TO_CLASS_FILES, NET_SERVER_GET_MVCC_SNAPSHOT, NET_SERVER_HEAP_CREATE, NET_SERVER_HEAP_DESTROY, NET_SERVER_HEAP_DESTROY_WHEN_NEW, NET_SERVER_HEAP_GET_CLASS_NOBJS_AND_NPAGES, NET_SERVER_HEAP_HAS_INSTANCE, NET_SERVER_HEAP_RECLAIM_ADDRESSES, NET_SERVER_JSP_GET_SERVER_PORT, NET_SERVER_LC_ASSIGN_OID, NET_SERVER_LC_ASSIGN_OID_BATCH, NET_SERVER_LC_CHECK_FK_VALIDITY, NET_SERVER_LC_DELETE_CLASSNAME, NET_SERVER_LC_DEMOTE_CLASS_LOCK, NET_SERVER_LC_DOESEXIST, NET_SERVER_LC_FETCH, NET_SERVER_LC_FETCH_ALLREFS_LOCKSET, NET_SERVER_LC_FETCH_LOCKHINT_CLASSES, NET_SERVER_LC_FETCH_LOCKSET, NET_SERVER_LC_FETCHALL, NET_SERVER_LC_FIND_CLASSOID, NET_SERVER_LC_FIND_LOCKHINT_CLASSOIDS, NET_SERVER_LC_FORCE, NET_SERVER_LC_GET_CLASS, NET_SERVER_LC_NOTIFY_ISOLATION_INCONS, NET_SERVER_LC_REM_CLASS_FROM_INDEX, NET_SERVER_LC_RENAME_CLASSNAME, NET_SERVER_LC_RESERVE_CLASSNAME, NET_SERVER_LC_RESERVE_CLASSNAME_GET_OID, NET_SERVER_LC_UPGRADE_INSTANCES_DOMAIN, NET_SERVER_LD_DESTROY, NET_SERVER_LD_INIT, NET_SERVER_LD_INSTALL_CLASS, NET_SERVER_LD_INTERRUPT, NET_SERVER_LD_LOAD_BATCH, NET_SERVER_LD_UPDATE_STATS, NET_SERVER_LK_DUMP, NET_SERVER_LOCK_RR, NET_SERVER_LOG_ADD_LOB_LOCATOR, NET_SERVER_LOG_CHANGE_STATE_OF_LOCATOR, NET_SERVER_LOG_CHECKPOINT, NET_SERVER_LOG_DROP_LOB_LOCATOR, NET_SERVER_LOG_DUMP_STAT, NET_SERVER_LOG_DUMP_TRANTB, NET_SERVER_LOG_FIND_LOB_LOCATOR, NET_SERVER_LOG_GETPACK_TRANTB, NET_SERVER_LOG_RESET_ISOLATION, NET_SERVER_LOG_RESET_WAIT_MSECS, NET_SERVER_LOG_SET_INTERRUPT, NET_SERVER_LOG_SET_SUPPRESS_REPL_ON_TRANSACTION, NET_SERVER_LOGWR_GET_LOG_PAGES, NET_SERVER_LS_GET_LIST_FILE_PAGE, NET_SERVER_MNT_SERVER_COPY_STATS, NET_SERVER_MNT_SERVER_START_STATS, NET_SERVER_MNT_SERVER_STOP_STATS, NET_SERVER_PRM_DUMP_PARAMETERS, NET_SERVER_PRM_GET_PARAMETERS, NET_SERVER_PRM_SET_PARAMETERS, NET_SERVER_QM_QUERY_DROP_ALL_PLANS, NET_SERVER_QM_QUERY_DUMP_CACHE, NET_SERVER_QM_QUERY_DUMP_PLANS, NET_SERVER_QM_QUERY_END, NET_SERVER_QM_QUERY_EXECUTE, NET_SERVER_QM_QUERY_PREPARE, NET_SERVER_QM_QUERY_PREPARE_AND_EXECUTE, NET_SERVER_QPROC_GET_CURRENT_VALUE, NET_SERVER_QPROC_GET_NEXT_VALUE, NET_SERVER_QPROC_GET_SERVER_INFO, NET_SERVER_QPROC_GET_SYS_TIMESTAMP, NET_SERVER_QST_GET_STATISTICS, NET_SERVER_QST_UPDATE_ALL_STATISTICS, NET_SERVER_QST_UPDATE_STATISTICS, NET_SERVER_REPL_INFO, NET_SERVER_REPL_LOG_GET_APPEND_LSA, NET_SERVER_SERIAL_DECACHE, NET_SERVER_SES_CHECK_SESSION, NET_SERVER_SES_CREATE_PREPARED_STATEMENT, NET_SERVER_SES_DELETE_PREPARED_STATEMENT, NET_SERVER_SES_DROP_SESSION_VARIABLES, NET_SERVER_SES_END_SESSION, NET_SERVER_SES_GET_LAST_INSERT_ID, NET_SERVER_SES_GET_PREPARED_STATEMENT, NET_SERVER_SES_GET_ROW_COUNT, NET_SERVER_SES_GET_SESSION_VARIABLE, NET_SERVER_SES_RESET_CUR_INSERT_ID, NET_SERVER_SES_SET_ROW_COUNT, NET_SERVER_SES_SET_SESSION_VARIABLES, NET_SERVER_SHUTDOWN, NET_SERVER_SPACEDB, NET_SERVER_TDE_CHANGE_MK_ON_SERVER, NET_SERVER_TDE_GET_DATA_KEYS, NET_SERVER_TDE_GET_MK_FILE_PATH, NET_SERVER_TDE_GET_MK_INFO, NET_SERVER_TM_ISBLOCKED, NET_SERVER_TM_LOCAL_TRANSACTION_ID, NET_SERVER_TM_SERVER_2PC_ATTACH_GT, NET_SERVER_TM_SERVER_2PC_PREPARE, NET_SERVER_TM_SERVER_2PC_PREPARE_GT, NET_SERVER_TM_SERVER_2PC_RECOVERY_PREPARED, NET_SERVER_TM_SERVER_2PC_START, NET_SERVER_TM_SERVER_ABORT, NET_SERVER_TM_SERVER_COMMIT, NET_SERVER_TM_SERVER_END_TOPOP, NET_SERVER_TM_SERVER_GET_GTRINFO, NET_SERVER_TM_SERVER_HAS_UPDATED, NET_SERVER_TM_SERVER_ISACTIVE_AND_HAS_UPDATED, NET_SERVER_TM_SERVER_PARTIAL_ABORT, NET_SERVER_TM_SERVER_SAVEPOINT, NET_SERVER_TM_SERVER_SET_GTRINFO, NET_SERVER_TM_SERVER_START_TOPOP, NET_SERVER_TM_WAIT_SERVER_ACTIVE_TRANS, NET_SERVER_TZ_GET_CHECKSUM, NET_SERVER_VACUUM, NET_SERVER_VACUUM_DUMP, net_request_buffer::request_count, net_request_buffer::total_size_received, and net_request_buffer::total_size_sent.
Referenced by net_histo_start().
int net_histo_start (bool for_all_trans)
Definition at line 775 of file network_cl.c.
References ER_FAILED, net_histo_clear(), net_Histo_setup, net_Histo_setup_mnt, net_histo_setup_names(), and NO_ERROR.
Referenced by histo_start().
int net_histo_stop (void)
Definition at line 804 of file network_cl.c.
References err, net_Histo_setup, net_Histo_setup_mnt, and NO_ERROR.
Referenced by histo_stop().
static int net_set_alloc_err_if_not_set (int err, const char * file, const int line) static
Definition at line 382 of file network_cl.c.
References ER_ERROR_SEVERITY, ER_NET_CANT_ALLOC_BUFFER, er_set(), err, and NO_ERROR.
Referenced by net_client_request2(), net_client_request_3recv_copyarea(), and net_client_request_with_callback().
static void return_error_to_server (char * host, unsigned int eid) static
Definition at line 208 of file network_cl.c.
References css_send_error_to_server(), er_get_area_error(), NULL, OR_ALIGNED_BUF, and OR_ALIGNED_BUF_START.
Referenced by net_client_request_with_callback().
static int set_server_error (int error) static
Definition at line 144 of file network_cl.c.
References ARG_FILE_LINE, assert, boot_server_die_or_changed(), CANT_ALLOC_BUFFER, db_Connect_status, DB_CONNECTION_STATUS_NOT_CONNECTED, ER_AU_DBA_ONLY, ER_DB_NO_MODIFICATIONS, er_errid(), ER_ERROR_SEVERITY, er_log_debug, ER_NET_CANT_ALLOC_BUFFER, ER_NET_DATA_TRUNCATED, ER_NET_SERVER_CRASHED, er_set(), er_set_with_oserror(), net_Server_host, net_Server_name, NO_ERROR, RECORD_TRUNCATED, REQUEST_REFUSED, and SERVER_ABORTED.
Referenced by net_client_check_log_header(), net_client_get_next_log_pages(), net_client_receive_action(), net_client_recv_copyarea(), net_client_request(), net_client_request2(), net_client_request2_no_malloc(), net_client_request_2recv_copyarea(), net_client_request_3_data(), net_client_request_3_data_recv_copyarea(), net_client_request_3recv_copyarea(), net_client_request_internal(), net_client_request_no_reply(), net_client_request_recv_copyarea(), net_client_request_recv_stream(), net_client_request_with_callback(), net_client_request_with_logwr_context(), and net_client_send_data().
Variable Documentation
int net_Histo_call_count = 0 static
Definition at line 97 of file network_cl.c.
Referenced by net_histo_add_entry(), and net_histo_clear().
INT64 net_Histo_last_call_time = 0 static
Definition at line 98 of file network_cl.c.
Referenced by net_histo_add_entry(), net_histo_clear(), and net_histo_request_finished().
int net_Histo_setup = 0 static
Definition at line 95 of file network_cl.c.
Referenced by net_client_recv_copyarea(), net_client_request(), net_client_request2(), net_client_request2_no_malloc(), net_client_request_2recv_copyarea(), net_client_request_3_data(), net_client_request_3_data_recv_copyarea(), net_client_request_3recv_copyarea(), net_client_request_internal(), net_client_request_no_reply(), net_client_request_recv_copyarea(), net_client_request_recv_stream(), net_client_request_with_callback(), net_client_request_with_logwr_context(), net_histo_start(), and net_histo_stop().
int net_Histo_setup_mnt = 0 static
Definition at line 96 of file network_cl.c.
Referenced by net_histo_clear(), net_histo_print(), net_histo_print_global_stats(), net_histo_start(), and net_histo_stop().
INT64 net_Histo_total_server_time = 0 static
Definition at line 99 of file network_cl.c.
Referenced by net_histo_clear(), and net_histo_request_finished().
struct net_request_buffer net_Req_buffer[NET_SERVER_REQUEST_END] static
Definition at line 93 of file network_cl.c.
Referenced by net_histo_add_entry(), net_histo_clear(), net_histo_print(), net_histo_request_finished(), and net_histo_setup_names().
char net_Server_host[CUB_MAXHOSTNAMELEN+1] = "" static
Definition at line 106 of file network_cl.c.
Referenced by check_server_capabilities(), net_cleanup_client_queues(), net_client_check_log_header(), net_client_get_server_host(), net_client_init(), net_client_logwr_send_end_msg(), net_client_ping_server(), net_client_ping_server_with_handshake(), net_client_request(), net_client_request2(), net_client_request2_no_malloc(), net_client_request_2recv_copyarea(), net_client_request_3_data(), net_client_request_3_data_recv_copyarea(), net_client_request_3recv_copyarea(), net_client_request_internal(), net_client_request_no_reply(), net_client_request_recv_copyarea(), net_client_request_recv_stream(), net_client_request_with_callback(), net_client_request_with_logwr_context(), and set_server_error().
char net_Server_name[DB_MAX_IDENTIFIER_LENGTH+1] = "" static
Definition at line 109 of file network_cl.c.
Referenced by net_cleanup_client_queues(), net_client_check_log_header(), net_client_init(), net_client_ping_server(), net_client_ping_server_with_handshake(), net_client_receive_action(), net_client_recv_copyarea(), net_client_request(), net_client_request2(), net_client_request2_no_malloc(), net_client_request_2recv_copyarea(), net_client_request_3_data(), net_client_request_3_data_recv_copyarea(), net_client_request_3recv_copyarea(), net_client_request_internal(), net_client_request_no_reply(), net_client_request_recv_copyarea(), net_client_request_recv_stream(), net_client_request_with_callback(), net_client_request_with_logwr_context(), and set_server_error().