CUBRID Engine: src/object/object_print.c File Reference
object_print.c File Reference
#include "object_print.h"
#include "authenticate.h"
#include "chartype.h"
#include "class_description.hpp"
#include "dbi.h"
#include "dbtype.h"
#include "error_manager.h"
#include "locator_cl.h"
#include "message_catalog.h"
#include "msgcat_help.hpp"
#include "network_interface_cl.h"
#include "object_description.hpp"
#include "object_print_util.hpp"
#include "object_printer.hpp"
#include "printer.hpp"
#include "schema_manager.h"
#include "string_buffer.hpp"
#include "trigger_description.hpp"
#include "trigger_manager.h"
Macros
#define MATCH_TOKEN(string, token) ((string == NULL) ? 0 : intl_mbs_casecmp(string, token) == 0)
Functions
static char * obj_print_next_token (char *ptr, char *buf)
int help_trigger_names (char ***names_ptr)
void help_print_obj (print_output &output_ctx, MOP obj)
char ** help_class_names (const char *qualifier)
void help_free_names (char **names)
void help_free_class_names (char **names)
void help_fprint_class_names (FILE *fp, const char *qualifier)
int help_describe_mop (DB_OBJECT *obj, char *buffer, int maxlen)
void help_print_info (const char *command, FILE *fpp)
void help_print_describe_comment (print_output &output_ctx, const char *comment)
Macro Definition Documentation
#define MATCH_TOKEN (string, token) ((string == NULL) ? 0 : intl_mbs_casecmp(string, token) == 0)
Definition at line 50 of file object_print.c.
Referenced by help_print_info().
Function Documentation
char** help_class_names (const char * qualifier)
Definition at line 347 of file object_print.c.
References ARG_FILE_LINE, object_print::copy_string(), cubregex::count(), db_fetch_all_classes(), DB_FETCH_READ, db_find_user(), db_get(), db_get_class_name(), db_get_owner(), db_get_string(), DB_MAX_IDENTIFIER_LENGTH, db_objlist_free(), db_value_clear(), ER_AU_INVALID_USER, ER_ERROR_SEVERITY, er_set(), i, db_objlist::next, NULL, ws_is_same_object(), and ws_list_length().
Referenced by help_fprint_class_names().
int help_describe_mop (DB_OBJECT * obj, char * buffer, int maxlen)
Definition at line 498 of file object_print.c.
References au_fetch_class(), AU_FETCH_READ, AU_SELECT, DB_FETCH_READ, locator_is_class(), NO_ERROR, NULL, sm_ch_name(), strlen, and WS_OID.
Referenced by db_print_mop().
void help_fprint_class_names (FILE * fp, const char * qualifier)
Definition at line 465 of file object_print.c.
References help_class_names(), help_free_class_names(), i, and NULL.
Referenced by help_print_info().
void help_free_class_names (char ** names)
Definition at line 451 of file object_print.c.
References help_free_names().
Referenced by help_fprint_class_names().
void help_free_names (char ** names)
Definition at line 431 of file object_print.c.
References object_print::free_strarray(), and NULL.
Referenced by csql_help_trigger(), help_free_class_names(), and help_print_info().
void help_print_describe_comment (print_output & output_ctx, const char * comment)
Definition at line 716 of file object_print.c.
References assert, object_printer::describe_comment(), string_buffer::get_buffer(), string_buffer::len(), and NULL.
Referenced by au_export_users(), classobj_filter_components(), emit_attribute_def(), emit_foreign_key(), emit_index_def(), emit_partition_parts(), emit_schema(), emit_unique_def(), help_print_obj(), and tr_dump_trigger().
void help_print_info (const char * command, FILE * fpp)
Definition at line 595 of file object_print.c.
References tp_domain::class_mop, db_find_class(), trigger_description::fprint(), help_fprint_class_names(), help_free_names(), help_print_obj(), help_trigger_names(), i, trigger_description::init(), lock_dump(), log_dump_stat(), logtb_dump_trantable(), MATCH_TOKEN, NO_ERROR, NULL, obj_print_next_token(), qmgr_dump_query_cache(), qmgr_dump_query_plans(), stats_dump(), strlen, thread_dump_cs_stat(), tr_dump(), and ws_dump().
Referenced by au_info_method(), and csql_help_info().
void help_print_obj (print_output & output_ctx, MOP obj)
Definition at line 141 of file object_print.c.
References trigger_description::action, trigger_description::action_time, trigger_description::attribute, object_description::attributes, class_description::attributes, class_description::class_attributes, class_description::class_methods, trigger_description::class_name, class_description::class_type, object_description::classname, trigger_description::comment, trigger_description::condition, trigger_description::condition_time, class_description::CSQL_SCHEMA_COMMAND, DB_FETCH_READ, trigger_description::event, help_print_describe_comment(), i, object_description::init(), trigger_description::init(), class_description::init(), locator_is_class(), locator_is_root(), class_description::method_files, class_description::methods, MSGCAT_CATALOG_CUBRID, MSGCAT_HELP_ATTRIBUTES, MSGCAT_HELP_CLASS_ATTRIBUTES, MSGCAT_HELP_CLASS_METHODS, MSGCAT_HELP_CLASS_TITLE, MSGCAT_HELP_METHOD_FILES, MSGCAT_HELP_METHODS, MSGCAT_HELP_OBJECT_TITLE, MSGCAT_HELP_QUERY_SPEC, MSGCAT_HELP_RESOLUTIONS, MSGCAT_HELP_ROOTCLASS_TITLE, MSGCAT_HELP_SUB_CLASSES, MSGCAT_HELP_SUPER_CLASSES, msgcat_message(), MSGCAT_SET_HELP, trigger_description::name, class_description::name, NO_ERROR, NULL, trigger_description::priority, class_description::query_spec, class_description::resolutions, object_description::shared, trigger_description::status, class_description::subs, class_description::supers, tr_is_trigger(), and class_description::triggers.
Referenced by db_fprint(), db_print(), and help_print_info().
int help_trigger_names (char *** names_ptr)
Definition at line 78 of file object_print.c.
References ARG_FILE_LINE, object_print::copy_string(), cubregex::count(), db_objlist_free(), ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), i, db_objlist::next, NO_ERROR, NULL, db_objlist::op, tr_find_all_triggers(), tr_trigger_name(), ws_free_string(), and ws_list_length().
Referenced by csql_help_trigger(), and help_print_info().
static char * obj_print_next_token (char * ptr, char * buf) static
Definition at line 567 of file object_print.c.
References char_isspace(), and p.
Referenced by help_print_info().