CUBRID Engine: src/object/object_primitive.c File Reference
object_primitive.c File Reference
#include "config.h"
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include "object_primitive.h"
#include "area_alloc.h"
#include "db_value_printer.hpp"
#include "db_json.hpp"
#include "elo.h"
#include "error_manager.h"
#include "file_io.h"
#include "mem_block.hpp"
#include "object_domain.h"
#include "object_representation.h"
#include "set_object.h"
#include "string_buffer.hpp"
#include "string_opfunc.h"
#include "system_parameter.h"
#include "tz_support.h"
#include <utility>
#include "work_space.h"
#include "virtual_object.h"
#include "transform_cl.h"
#include "dbi.h"
#include "dbtype.h"
#include "memory_private_allocator.hpp"
Macros
#define MR_CMP(d1, d2) ((d1) < (d2) ? DB_LT : (d1) > (d2) ? DB_GT : DB_EQ)
#define MR_CMP_RETURN_CODE(c) ((c) < 0 ? DB_LT : (c) > 0 ? DB_GT : DB_EQ)
#define MR_OID_SIZE sizeof(WS_MEMOID)
#define VALUE_AREA_COUNT 1024
#define PR_INHIBIT_OID_PROMOTION_DEFAULT 0
#define OR_NUMERIC_SIZE(precision) DB_NUMERIC_BUF_SIZE
#define MR_NUMERIC_SIZE(precision) DB_NUMERIC_BUF_SIZE
#define STR_SIZE(prec, codeset)
#define BITS_IN_BYTE 8
#define BITS_TO_BYTES(bit_cnt) (((bit_cnt) + 7) / 8)
#define DO_CONVERSION_TO_SRVR_STR(codeset) false
#define DO_CONVERSION_TO_SQLTEXT(codeset) false
#define DB_DOMAIN_INIT_CHAR(value, precision)
#define IS_FLOATING_PRECISION(prec) ((prec) == TP_FLOATING_PRECISION_VALUE)
Functions
static void mr_initmem_string (void *mem, TP_DOMAIN *domain)
static int mr_setmem_string (void *memptr, TP_DOMAIN *domain, DB_VALUE *value)
static int mr_getmem_string (void *memptr, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static int mr_data_lengthmem_string (void *memptr, TP_DOMAIN *domain, int disk)
static int mr_index_lengthmem_string (void *memptr, TP_DOMAIN *domain)
static void mr_data_writemem_string (OR_BUF *buf, void *memptr, TP_DOMAIN *domain)
static void mr_data_readmem_string (OR_BUF *buf, void *memptr, TP_DOMAIN *domain, int size)
static void mr_freemem_string (void *memptr)
static void mr_initval_string (DB_VALUE *value, int precision, int scale)
static int mr_setval_string (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_lengthval_string (DB_VALUE *value, int disk)
static int mr_data_writeval_string (OR_BUF *buf, DB_VALUE *value)
static int mr_data_readval_string (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_index_lengthval_string (DB_VALUE *value)
static int mr_index_writeval_string (OR_BUF *buf, DB_VALUE *value)
static int mr_index_readval_string (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_lengthval_string_internal (DB_VALUE *value, int disk, int align)
static int mr_writeval_string_internal (OR_BUF *buf, DB_VALUE *value, int align)
static int mr_readval_string_internal (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len, int align)
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_string (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_string (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_string (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static void mr_initmem_char (void *memptr, TP_DOMAIN *domain)
static int mr_setmem_char (void *memptr, TP_DOMAIN *domain, DB_VALUE *value)
static int mr_getmem_char (void *mem, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static int mr_data_lengthmem_char (void *memptr, TP_DOMAIN *domain, int disk)
static int mr_index_lengthmem_char (void *memptr, TP_DOMAIN *domain)
static void mr_data_writemem_char (OR_BUF *buf, void *mem, TP_DOMAIN *domain)
static void mr_data_readmem_char (OR_BUF *buf, void *mem, TP_DOMAIN *domain, int size)
static void mr_freemem_char (void *memptr)
static void mr_initval_char (DB_VALUE *value, int precision, int scale)
static int mr_setval_char (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_lengthval_char (DB_VALUE *value, int disk)
static int mr_data_writeval_char (OR_BUF *buf, DB_VALUE *value)
static int mr_writeval_char_internal (OR_BUF *buf, DB_VALUE *value, int align)
static int mr_data_readval_char (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int disk_size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_readval_char_internal (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int disk_size, bool copy, char *copy_buf, int copy_buf_len, int align)
static int mr_index_lengthval_char (DB_VALUE *value)
static int mr_index_writeval_char (OR_BUF *buf, DB_VALUE *value)
static int mr_index_readval_char (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int disk_size, bool copy, char *copy_buf, int copy_buf_len)
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_char (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_char (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_char (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static DB_VALUE_COMPARE_RESULT mr_cmpdisk_char_internal (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp, int align)
static void mr_initmem_nchar (void *memptr, TP_DOMAIN *domain)
static int mr_setmem_nchar (void *memptr, TP_DOMAIN *domain, DB_VALUE *value)
static int mr_getmem_nchar (void *mem, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static int mr_data_lengthmem_nchar (void *memptr, TP_DOMAIN *domain, int disk)
static int mr_index_lengthmem_nchar (void *memptr, TP_DOMAIN *domain)
static void mr_data_writemem_nchar (OR_BUF *buf, void *mem, TP_DOMAIN *domain)
static void mr_data_readmem_nchar (OR_BUF *buf, void *mem, TP_DOMAIN *domain, int size)
static void mr_freemem_nchar (void *memptr)
static void mr_initval_nchar (DB_VALUE *value, int precision, int scale)
static int mr_setval_nchar (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_lengthval_nchar (DB_VALUE *value, int disk)
static int mr_data_writeval_nchar (OR_BUF *buf, DB_VALUE *value)
static int mr_writeval_nchar_internal (OR_BUF *buf, DB_VALUE *value, int align)
static int mr_data_readval_nchar (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int disk_size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_readval_nchar_internal (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int disk_size, bool copy, char *copy_buf, int copy_buf_len, int align)
static int mr_index_lengthval_nchar (DB_VALUE *value)
static int mr_index_writeval_nchar (OR_BUF *buf, DB_VALUE *value)
static int mr_index_readval_nchar (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int disk_size, bool copy, char *copy_buf, int copy_buf_len)
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_nchar (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_nchar (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpdisk_nchar_internal (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp, int align)
static DB_VALUE_COMPARE_RESULT mr_cmpval_nchar (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static void mr_initmem_varnchar (void *mem, TP_DOMAIN *domain)
static int mr_setmem_varnchar (void *memptr, TP_DOMAIN *domain, DB_VALUE *value)
static int mr_getmem_varnchar (void *memptr, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static int mr_data_lengthmem_varnchar (void *memptr, TP_DOMAIN *domain, int disk)
static int mr_index_lengthmem_varnchar (void *memptr, TP_DOMAIN *domain)
static void mr_data_writemem_varnchar (OR_BUF *buf, void *memptr, TP_DOMAIN *domain)
static void mr_data_readmem_varnchar (OR_BUF *buf, void *memptr, TP_DOMAIN *domain, int size)
static void mr_freemem_varnchar (void *memptr)
static void mr_initval_varnchar (DB_VALUE *value, int precision, int scale)
static int mr_setval_varnchar (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_lengthval_varnchar (DB_VALUE *value, int disk)
static int mr_data_writeval_varnchar (OR_BUF *buf, DB_VALUE *value)
static int mr_data_readval_varnchar (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_index_lengthval_varnchar (DB_VALUE *value)
static int mr_index_writeval_varnchar (OR_BUF *buf, DB_VALUE *value)
static int mr_index_readval_varnchar (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_lengthval_varnchar_internal (DB_VALUE *value, int disk, int align)
static int mr_writeval_varnchar_internal (OR_BUF *buf, DB_VALUE *value, int align)
static int mr_readval_varnchar_internal (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len, int align)
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_varnchar (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_varnchar (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_varnchar (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static void mr_initmem_bit (void *memptr, TP_DOMAIN *domain)
static int mr_setmem_bit (void *memptr, TP_DOMAIN *domain, DB_VALUE *value)
static int mr_getmem_bit (void *mem, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static int mr_data_lengthmem_bit (void *memptr, TP_DOMAIN *domain, int disk)
static void mr_data_writemem_bit (OR_BUF *buf, void *mem, TP_DOMAIN *domain)
static void mr_data_readmem_bit (OR_BUF *buf, void *mem, TP_DOMAIN *domain, int size)
static void mr_freemem_bit (void *memptr)
static void mr_initval_bit (DB_VALUE *value, int precision, int scale)
static int mr_setval_bit (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_lengthval_bit (DB_VALUE *value, int disk)
static int mr_data_writeval_bit (OR_BUF *buf, DB_VALUE *value)
static int mr_writeval_bit_internal (OR_BUF *buf, DB_VALUE *value, int align)
static int mr_data_readval_bit (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int disk_size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_readval_bit_internal (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int disk_size, bool copy, char *copy_buf, int copy_buf_len, int align)
static int mr_index_lengthmem_bit (void *memptr, TP_DOMAIN *domain)
static int mr_index_lengthval_bit (DB_VALUE *value)
static int mr_index_writeval_bit (OR_BUF *buf, DB_VALUE *value)
static int mr_index_readval_bit (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int disk_size, bool copy, char *copy_buf, int copy_buf_len)
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_bit (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_bit (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpdisk_bit_internal (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp, int align)
static DB_VALUE_COMPARE_RESULT mr_cmpval_bit (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static DB_VALUE_COMPARE_RESULT mr_cmpval_bit2 (DB_VALUE *value1, DB_VALUE *value2, int length, int do_coercion, int total_order, int *start_colp)
static void mr_initmem_varbit (void *mem, TP_DOMAIN *domain)
static int mr_setmem_varbit (void *memptr, TP_DOMAIN *domain, DB_VALUE *value)
static int mr_getmem_varbit (void *memptr, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static int mr_data_lengthmem_varbit (void *memptr, TP_DOMAIN *domain, int disk)
static int mr_index_lengthmem_varbit (void *memptr, TP_DOMAIN *domain)
static void mr_data_writemem_varbit (OR_BUF *buf, void *memptr, TP_DOMAIN *domain)
static void mr_data_readmem_varbit (OR_BUF *buf, void *memptr, TP_DOMAIN *domain, int size)
static void mr_freemem_varbit (void *memptr)
static void mr_initval_varbit (DB_VALUE *value, int precision, int scale)
static int mr_setval_varbit (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_lengthval_varbit (DB_VALUE *value, int disk)
static int mr_data_writeval_varbit (OR_BUF *buf, DB_VALUE *value)
static int mr_data_readval_varbit (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_index_lengthval_varbit (DB_VALUE *value)
static int mr_index_writeval_varbit (OR_BUF *buf, DB_VALUE *value)
static int mr_index_readval_varbit (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_lengthval_varbit_internal (DB_VALUE *value, int disk, int align)
static int mr_writeval_varbit_internal (OR_BUF *buf, DB_VALUE *value, int align)
static int mr_readval_varbit_internal (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len, int align)
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_varbit (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_varbit (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_varbit (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static DB_VALUE_COMPARE_RESULT mr_cmpval_varbit2 (DB_VALUE *value1, DB_VALUE *value2, int length, int do_coercion, int total_order, int *start_colp)
static void mr_initmem_null (void *mem, TP_DOMAIN *domain)
static int mr_setmem_null (void *memptr, TP_DOMAIN *domain, DB_VALUE *value)
static int mr_getmem_null (void *memptr, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static void mr_data_writemem_null (OR_BUF *buf, void *memptr, TP_DOMAIN *domain)
static void mr_data_readmem_null (OR_BUF *buf, void *memptr, TP_DOMAIN *domain, int size)
static void mr_initval_null (DB_VALUE *value, int precision, int scale)
static int mr_setval_null (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_writeval_null (OR_BUF *buf, DB_VALUE *value)
static int mr_data_readval_null (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_null (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_null (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static void mr_initmem_int (void *mem, TP_DOMAIN *domain)
static int mr_setmem_int (void *mem, TP_DOMAIN *domain, DB_VALUE *value)
static int mr_getmem_int (void *mem, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static void mr_data_writemem_int (OR_BUF *buf, void *mem, TP_DOMAIN *domain)
static void mr_data_readmem_int (OR_BUF *buf, void *mem, TP_DOMAIN *domain, int size)
static void mr_initval_int (DB_VALUE *value, int precision, int scale)
static int mr_setval_int (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_writeval_int (OR_BUF *buf, DB_VALUE *value)
static int mr_data_readval_int (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_index_writeval_int (OR_BUF *buf, DB_VALUE *value)
static int mr_index_readval_int (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_int (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_int (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_int (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static void mr_initmem_short (void *mem, TP_DOMAIN *domain)
static int mr_setmem_short (void *mem, TP_DOMAIN *domain, DB_VALUE *value)
static int mr_getmem_short (void *mem, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static void mr_data_writemem_short (OR_BUF *buf, void *memptr, TP_DOMAIN *domain)
static void mr_data_readmem_short (OR_BUF *buf, void *mem, TP_DOMAIN *domain, int size)
static void mr_initval_short (DB_VALUE *value, int precision, int scale)
static int mr_setval_short (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_writeval_short (OR_BUF *buf, DB_VALUE *value)
static int mr_data_readval_short (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_index_writeval_short (OR_BUF *buf, DB_VALUE *value)
static int mr_index_readval_short (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_short (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_short (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_short (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static void mr_initmem_bigint (void *mem, TP_DOMAIN *domain)
static int mr_setmem_bigint (void *mem, TP_DOMAIN *domain, DB_VALUE *value)
static int mr_getmem_bigint (void *mem, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static void mr_data_writemem_bigint (OR_BUF *buf, void *mem, TP_DOMAIN *domain)
static void mr_data_readmem_bigint (OR_BUF *buf, void *mem, TP_DOMAIN *domain, int size)
static void mr_initval_bigint (DB_VALUE *value, int precision, int scale)
static int mr_setval_bigint (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_writeval_bigint (OR_BUF *buf, DB_VALUE *value)
static int mr_data_readval_bigint (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_index_writeval_bigint (OR_BUF *buf, DB_VALUE *value)
static int mr_index_readval_bigint (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_bigint (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_bigint (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_bigint (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static void mr_initmem_float (void *mem, TP_DOMAIN *domain)
static int mr_setmem_float (void *mem, TP_DOMAIN *domain, DB_VALUE *value)
static int mr_getmem_float (void *mem, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static void mr_data_writemem_float (OR_BUF *buf, void *mem, TP_DOMAIN *domain)
static void mr_data_readmem_float (OR_BUF *buf, void *mem, TP_DOMAIN *domain, int size)
static void mr_initval_float (DB_VALUE *value, int precision, int scale)
static int mr_setval_float (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_writeval_float (OR_BUF *buf, DB_VALUE *value)
static int mr_data_readval_float (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_index_writeval_float (OR_BUF *buf, DB_VALUE *value)
static int mr_index_readval_float (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_float (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_float (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_float (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static void mr_initmem_double (void *mem, TP_DOMAIN *domain)
static int mr_setmem_double (void *mem, TP_DOMAIN *domain, DB_VALUE *value)
static int mr_getmem_double (void *mem, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static void mr_data_writemem_double (OR_BUF *buf, void *mem, TP_DOMAIN *domain)
static void mr_data_readmem_double (OR_BUF *buf, void *mem, TP_DOMAIN *domain, int size)
static void mr_initval_double (DB_VALUE *value, int precision, int scale)
static int mr_setval_double (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_writeval_double (OR_BUF *buf, DB_VALUE *value)
static int mr_data_readval_double (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_index_writeval_double (OR_BUF *buf, DB_VALUE *value)
static int mr_index_readval_double (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_double (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_double (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_double (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static void mr_initmem_time (void *mem, TP_DOMAIN *domain)
static int mr_setmem_time (void *mem, TP_DOMAIN *domain, DB_VALUE *value)
static int mr_getmem_time (void *mem, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static void mr_data_writemem_time (OR_BUF *buf, void *mem, TP_DOMAIN *domain)
static void mr_data_readmem_time (OR_BUF *buf, void *mem, TP_DOMAIN *domain, int size)
static void mr_initval_time (DB_VALUE *value, int precision, int scale)
static int mr_setval_time (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_writeval_time (OR_BUF *buf, DB_VALUE *value)
static int mr_data_readval_time (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_index_writeval_time (OR_BUF *buf, DB_VALUE *value)
static int mr_index_readval_time (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_time (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_time (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_time (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static void mr_initmem_utime (void *mem, TP_DOMAIN *domain)
static int mr_setmem_utime (void *mem, TP_DOMAIN *domain, DB_VALUE *value)
static int mr_getmem_utime (void *mem, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static int mr_getmem_timestampltz (void *mem, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static void mr_data_writemem_utime (OR_BUF *buf, void *mem, TP_DOMAIN *domain)
static void mr_data_readmem_utime (OR_BUF *buf, void *mem, TP_DOMAIN *domain, int size)
static void mr_initval_utime (DB_VALUE *value, int precision, int scale)
static void mr_initval_timestampltz (DB_VALUE *value, int precision, int scale)
static int mr_setval_utime (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_setval_timestampltz (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_writeval_utime (OR_BUF *buf, DB_VALUE *value)
static int mr_data_readval_utime (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_data_readval_timestampltz (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_index_writeval_utime (OR_BUF *buf, DB_VALUE *value)
static int mr_index_readval_utime (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_index_readval_timestampltz (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_utime (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_utime (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_utime (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static void mr_initmem_timestamptz (void *mem, TP_DOMAIN *domain)
static int mr_setmem_timestamptz (void *mem, TP_DOMAIN *domain, DB_VALUE *value)
static int mr_getmem_timestamptz (void *mem, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static void mr_data_writemem_timestamptz (OR_BUF *buf, void *mem, TP_DOMAIN *domain)
static void mr_data_readmem_timestamptz (OR_BUF *buf, void *mem, TP_DOMAIN *domain, int size)
static void mr_initval_timestamptz (DB_VALUE *value, int precision, int scale)
static int mr_setval_timestamptz (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_writeval_timestamptz (OR_BUF *buf, DB_VALUE *value)
static int mr_data_readval_timestamptz (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_index_writeval_timestamptz (OR_BUF *buf, DB_VALUE *value)
static int mr_index_readval_timestamptz (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_timestamptz (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_timestamptz (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_timestamptz (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static void mr_initmem_datetime (void *memptr, TP_DOMAIN *domain)
static void mr_initval_datetime (DB_VALUE *value, int precision, int scale)
static void mr_initval_datetimeltz (DB_VALUE *value, int precision, int scale)
static int mr_setmem_datetime (void *mem, TP_DOMAIN *domain, DB_VALUE *value)
static int mr_getmem_datetime (void *mem, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static int mr_getmem_datetimeltz (void *mem, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static int mr_setval_datetime (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_setval_datetimeltz (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static void mr_data_writemem_datetime (OR_BUF *buf, void *mem, TP_DOMAIN *domain)
static void mr_data_readmem_datetime (OR_BUF *buf, void *mem, TP_DOMAIN *domain, int size)
static int mr_data_writeval_datetime (OR_BUF *buf, DB_VALUE *value)
static int mr_data_readval_datetime (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_data_readval_datetimeltz (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_index_writeval_datetime (OR_BUF *buf, DB_VALUE *value)
static int mr_index_readval_datetime (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_index_readval_datetimeltz (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_datetime (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_datetime (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_datetime (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static void mr_initmem_datetimetz (void *memptr, TP_DOMAIN *domain)
static void mr_initval_datetimetz (DB_VALUE *value, int precision, int scale)
static int mr_setmem_datetimetz (void *mem, TP_DOMAIN *domain, DB_VALUE *value)
static int mr_getmem_datetimetz (void *mem, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static int mr_setval_datetimetz (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static void mr_data_writemem_datetimetz (OR_BUF *buf, void *mem, TP_DOMAIN *domain)
static void mr_data_readmem_datetimetz (OR_BUF *buf, void *mem, TP_DOMAIN *domain, int size)
static int mr_data_writeval_datetimetz (OR_BUF *buf, DB_VALUE *value)
static int mr_data_readval_datetimetz (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_index_writeval_datetimetz (OR_BUF *buf, DB_VALUE *value)
static int mr_index_readval_datetimetz (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_datetimetz (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_datetimetz (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_datetimetz (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static void mr_initmem_money (void *memptr, TP_DOMAIN *domain)
static int mr_setmem_money (void *memptr, TP_DOMAIN *domain, DB_VALUE *value)
static int mr_getmem_money (void *memptr, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static void mr_data_writemem_money (OR_BUF *buf, void *mem, TP_DOMAIN *domain)
static void mr_data_readmem_money (OR_BUF *buf, void *mem, TP_DOMAIN *domain, int size)
static void mr_initval_money (DB_VALUE *value, int precision, int scale)
static int mr_setval_money (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_writeval_money (OR_BUF *buf, DB_VALUE *value)
static int mr_data_readval_money (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_index_writeval_money (OR_BUF *buf, DB_VALUE *value)
static int mr_index_readval_money (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_money (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_money (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_money (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static void mr_initmem_date (void *mem, TP_DOMAIN *domain)
static int mr_setmem_date (void *mem, TP_DOMAIN *domain, DB_VALUE *value)
static int mr_getmem_date (void *mem, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static void mr_data_writemem_date (OR_BUF *buf, void *mem, TP_DOMAIN *domain)
static void mr_data_readmem_date (OR_BUF *buf, void *mem, TP_DOMAIN *domain, int size)
static void mr_initval_date (DB_VALUE *value, int precision, int scale)
static int mr_setval_date (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_writeval_date (OR_BUF *buf, DB_VALUE *value)
static int mr_data_readval_date (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_index_writeval_date (OR_BUF *buf, DB_VALUE *value)
static int mr_index_readval_date (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_date (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_date (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_date (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static void mr_null_oid (OID *oid)
static void mr_initmem_object (void *mem, TP_DOMAIN *domain)
static void mr_initval_object (DB_VALUE *value, int precision, int scale)
static int mr_setmem_object (void *memptr, TP_DOMAIN *domain, DB_VALUE *value)
static int mr_getmem_object (void *memptr, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static int mr_setval_object (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_lengthval_object (DB_VALUE *value, int disk)
static void mr_data_writemem_object (OR_BUF *buf, void *memptr, TP_DOMAIN *domain)
static void mr_data_readmem_object (OR_BUF *buf, void *memptr, TP_DOMAIN *domain, int size)
static int mr_data_writeval_object (OR_BUF *buf, DB_VALUE *value)
static int mr_data_readval_object (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_index_writeval_object (OR_BUF *buf, DB_VALUE *value)
static int mr_index_readval_object (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_object (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_object (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_object (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static void mr_initmem_elo (void *memptr, TP_DOMAIN *domain)
static void mr_initval_elo (DB_VALUE *value, int precision, int scale)
static int mr_setmem_elo (void *memptr, TP_DOMAIN *domain, DB_VALUE *value)
static int mr_setval_elo (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_lengthmem_elo (void *memptr, TP_DOMAIN *domain, int disk)
static void mr_data_writemem_elo (OR_BUF *buf, void *memptr, TP_DOMAIN *domain)
static void mr_data_readmem_elo (OR_BUF *buf, void *memptr, TP_DOMAIN *domain, int size)
static int mr_getmem_elo (void *memptr, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static int getmem_elo_with_type (void *memptr, TP_DOMAIN *domain, DB_VALUE *value, bool copy, DB_TYPE type)
static void peekmem_elo (OR_BUF *buf, DB_ELO *elo)
static int mr_data_lengthval_elo (DB_VALUE *value, int disk)
static int mr_data_writeval_elo (OR_BUF *buf, DB_VALUE *value)
static int mr_data_readval_elo (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static int setval_elo_with_type (DB_VALUE *dest, const DB_VALUE *src, bool copy, DB_TYPE type)
static int readval_elo_with_type (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len, DB_TYPE type)
static void mr_freemem_elo (void *memptr)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_elo (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_elo (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static void mr_initval_blob (DB_VALUE *value, int precision, int scale)
static int mr_getmem_blob (void *memptr, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static int mr_setval_blob (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_readval_blob (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static void mr_initval_clob (DB_VALUE *value, int precision, int scale)
static int mr_getmem_clob (void *memptr, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static int mr_setval_clob (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_readval_clob (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static void mr_initval_variable (DB_VALUE *value, int precision, int scale)
static int mr_setval_variable (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_lengthval_variable (DB_VALUE *value, int disk)
static int mr_data_writeval_variable (OR_BUF *buf, DB_VALUE *value)
static int mr_data_readval_variable (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_variable (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_variable (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static void mr_initmem_sub (void *mem, TP_DOMAIN *domain)
static void mr_initval_sub (DB_VALUE *value, int precision, int scale)
static int mr_setmem_sub (void *mem, TP_DOMAIN *domain, DB_VALUE *value)
static int mr_getmem_sub (void *mem, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static int mr_setval_sub (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_lengthmem_sub (void *mem, TP_DOMAIN *domain, int disk)
static void mr_data_writemem_sub (OR_BUF *buf, void *mem, TP_DOMAIN *domain)
static void mr_data_readmem_sub (OR_BUF *buf, void *mem, TP_DOMAIN *domain, int size)
static int mr_data_lengthval_sub (DB_VALUE *value, int disk)
static int mr_data_writeval_sub (OR_BUF *buf, DB_VALUE *value)
static int mr_data_readval_sub (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_sub (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_sub (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static void mr_initmem_ptr (void *memptr, TP_DOMAIN *domain)
static void mr_initval_ptr (DB_VALUE *value, int precision, int scale)
static int mr_setmem_ptr (void *memptr, TP_DOMAIN *domain, DB_VALUE *value)
static int mr_getmem_ptr (void *memptr, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static int mr_setval_ptr (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_lengthmem_ptr (void *memptr, TP_DOMAIN *domain, int disk)
static void mr_data_writemem_ptr (OR_BUF *buf, void *memptr, TP_DOMAIN *domain)
static void mr_data_readmem_ptr (OR_BUF *buf, void *memptr, TP_DOMAIN *domain, int size)
static int mr_data_lengthval_ptr (DB_VALUE *value, int disk)
static int mr_data_writeval_ptr (OR_BUF *buf, DB_VALUE *value)
static int mr_data_readval_ptr (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_ptr (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_ptr (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static void mr_initmem_error (void *memptr, TP_DOMAIN *domain)
static void mr_initval_error (DB_VALUE *value, int precision, int scale)
static int mr_setmem_error (void *memptr, TP_DOMAIN *domain, DB_VALUE *value)
static int mr_getmem_error (void *memptr, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static int mr_setval_error (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_lengthmem_error (void *memptr, TP_DOMAIN *domain, int disk)
static int mr_data_lengthval_error (DB_VALUE *value, int disk)
static void mr_data_writemem_error (OR_BUF *buf, void *memptr, TP_DOMAIN *domain)
static void mr_data_readmem_error (OR_BUF *buf, void *memptr, TP_DOMAIN *domain, int size)
static int mr_data_writeval_error (OR_BUF *buf, DB_VALUE *value)
static int mr_data_readval_error (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_error (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_error (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static void mr_initmem_oid (void *memptr, TP_DOMAIN *domain)
static void mr_initval_oid (DB_VALUE *value, int precision, int scale)
static int mr_setmem_oid (void *memptr, TP_DOMAIN *domain, DB_VALUE *value)
static int mr_getmem_oid (void *memptr, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static int mr_setval_oid (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static void mr_data_writemem_oid (OR_BUF *buf, void *memptr, TP_DOMAIN *domain)
static void mr_data_readmem_oid (OR_BUF *buf, void *memptr, TP_DOMAIN *domain, int size)
static int mr_data_writeval_oid (OR_BUF *buf, DB_VALUE *value)
static int mr_data_readval_oid (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_index_writeval_oid (OR_BUF *buf, DB_VALUE *value)
static int mr_index_readval_oid (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_oid (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_oid (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_oid (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static void mr_initmem_set (void *memptr, TP_DOMAIN *domain)
static void mr_initval_set (DB_VALUE *value, int precision, int scale)
static int mr_setmem_set (void *memptr, TP_DOMAIN *domain, DB_VALUE *value)
static int mr_getmem_set (void *memptr, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static int mr_setval_set_internal (DB_VALUE *dest, const DB_VALUE *src, bool copy, DB_TYPE set_type)
static int mr_setval_set (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_lengthmem_set (void *memptr, TP_DOMAIN *domain, int disk)
static void mr_data_writemem_set (OR_BUF *buf, void *memptr, TP_DOMAIN *domain)
static void mr_data_readmem_set (OR_BUF *buf, void *memptr, TP_DOMAIN *domain, int size)
static int mr_data_lengthval_set (DB_VALUE *value, int disk)
static int mr_data_writeval_set (OR_BUF *buf, DB_VALUE *value)
static int mr_data_readval_set (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static void mr_freemem_set (void *memptr)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_set (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_set (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static void mr_initval_multiset (DB_VALUE *value, int precision, int scale)
static int mr_getmem_multiset (void *memptr, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static int mr_setval_multiset (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static void mr_initval_sequence (DB_VALUE *value, int precision, int scale)
static int mr_getmem_sequence (void *memptr, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static int mr_setval_sequence (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_sequence (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_sequence (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static void mr_initval_midxkey (DB_VALUE *value, int precision, int scale)
static int mr_setval_midxkey (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_lengthmem_midxkey (void *memptr, TP_DOMAIN *domain, int disk)
static int mr_index_lengthmem_midxkey (void *memptr, TP_DOMAIN *domain)
static int mr_data_lengthval_midxkey (DB_VALUE *value, int disk)
static int mr_index_lengthval_midxkey (DB_VALUE *value)
static int mr_data_writeval_midxkey (OR_BUF *buf, DB_VALUE *value)
static int mr_index_writeval_midxkey (OR_BUF *buf, DB_VALUE *value)
static int mr_data_readval_midxkey (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_index_readval_midxkey (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static DB_VALUE_COMPARE_RESULT pr_midxkey_compare_element (char *mem1, char *mem2, TP_DOMAIN *dom1, TP_DOMAIN *dom2, int do_coercion, int total_order)
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_midxkey (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_midxkey (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_midxkey (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static void mr_initval_vobj (DB_VALUE *value, int precision, int scale)
static int mr_setval_vobj (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_readval_vobj (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_vobj (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_vobj (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static void mr_initmem_numeric (void *memptr, TP_DOMAIN *domain)
static int mr_setmem_numeric (void *mem, TP_DOMAIN *domain, DB_VALUE *value)
static int mr_getmem_numeric (void *mem, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static int mr_data_lengthmem_numeric (void *mem, TP_DOMAIN *domain, int disk)
static int mr_index_lengthmem_numeric (void *mem, TP_DOMAIN *domain)
static void mr_data_writemem_numeric (OR_BUF *buf, void *mem, TP_DOMAIN *domain)
static void mr_data_readmem_numeric (OR_BUF *buf, void *mem, TP_DOMAIN *domain, int size)
static void mr_initval_numeric (DB_VALUE *value, int precision, int scale)
static int mr_setval_numeric (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_lengthval_numeric (DB_VALUE *value, int disk)
static int mr_data_writeval_numeric (OR_BUF *buf, DB_VALUE *value)
static int mr_data_readval_numeric (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_index_lengthval_numeric (DB_VALUE *value)
static int mr_index_writeval_numeric (OR_BUF *buf, DB_VALUE *value)
static int mr_index_readval_numeric (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_numeric (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_numeric (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_numeric (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static void mr_initmem_resultset (void *mem, TP_DOMAIN *domain)
static int mr_setmem_resultset (void *mem, TP_DOMAIN *domain, DB_VALUE *value)
static int mr_getmem_resultset (void *mem, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static void mr_data_writemem_resultset (OR_BUF *buf, void *mem, TP_DOMAIN *domain)
static void mr_data_readmem_resultset (OR_BUF *buf, void *mem, TP_DOMAIN *domain, int size)
static void mr_initval_resultset (DB_VALUE *value, int precision, int scale)
static int mr_setval_resultset (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_writeval_resultset (OR_BUF *buf, DB_VALUE *value)
static int mr_data_readval_resultset (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_resultset (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_resultset (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static int pr_midxkey_get_vals_size (TP_DOMAIN *domains, DB_VALUE *dbvals, int total)
static int pr_midxkey_get_element_internal (const DB_MIDXKEY *midxkey, int index, DB_VALUE *value, bool copy, int *prev_indexp, char **prev_ptrp)
static void mr_initmem_enumeration (void *mem, TP_DOMAIN *domain)
static void mr_initval_enumeration (DB_VALUE *value, int precision, int scale)
static int mr_setmem_enumeration (void *mem, TP_DOMAIN *domain, DB_VALUE *value)
static int mr_getmem_enumeration (void *mem, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static int mr_setval_enumeration (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static void mr_data_writemem_enumeration (OR_BUF *buf, void *memptr, TP_DOMAIN *domain)
static void mr_data_readmem_enumeration (OR_BUF *buf, void *mem, TP_DOMAIN *domain, int size)
static int mr_setval_enumeration_internal (DB_VALUE *value, TP_DOMAIN *domain, unsigned short index, int size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_data_readval_enumeration (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static int mr_data_writeval_enumeration (OR_BUF *buf, DB_VALUE *value)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_enumeration (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_enumeration (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_enumeration (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static int mr_index_writeval_enumeration (OR_BUF *buf, DB_VALUE *value)
static int mr_index_readval_enumeration (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static int pr_write_compressed_string_to_buffer (OR_BUF *buf, const char *compressed_string, int compressed_length, int decompressed_length, int alignment)
static int pr_write_uncompressed_string_to_buffer (OR_BUF *buf, const char *string, int size, int align)
static void mr_initmem_json (void *mem, TP_DOMAIN *domain)
static int mr_setmem_json (void *memptr, TP_DOMAIN *domain, DB_VALUE *value)
static int mr_getmem_json (void *memptr, TP_DOMAIN *domain, DB_VALUE *value, bool copy)
static int mr_data_lengthmem_json (void *memptr, TP_DOMAIN *domain, int disk)
static void mr_data_writemem_json (OR_BUF *buf, void *memptr, TP_DOMAIN *domain)
static void mr_data_readmem_json (OR_BUF *buf, void *memptr, TP_DOMAIN *domain, int size)
static void mr_freemem_json (void *memptr)
static void mr_initval_json (DB_VALUE *value, int precision, int scale)
static int mr_setval_json (DB_VALUE *dest, const DB_VALUE *src, bool copy)
static int mr_data_lengthval_json (DB_VALUE *value, int disk)
static int mr_data_writeval_json (OR_BUF *buf, DB_VALUE *value)
static int mr_data_readval_json (OR_BUF *buf, DB_VALUE *value, TP_DOMAIN *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_json (void *mem1, void *mem2, TP_DOMAIN *domain, int do_coercion, int total_order, int *start_colp)
static DB_VALUE_COMPARE_RESULT mr_cmpval_json (DB_VALUE *value1, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
int pr_area_init (void)
void pr_area_final (void)
DB_VALUE * pr_make_value (void)
DB_VALUE * pr_make_ext_value (void)
int pr_clear_value (DB_VALUE *value)
void pr_clear_value_vector (std::vector< DB_VALUE > &value_vector)
int pr_free_value (DB_VALUE *value)
int pr_free_ext_value (DB_VALUE *value)
int pr_clone_value (const DB_VALUE *src, DB_VALUE *dest)
DB_VALUE * pr_copy_value (DB_VALUE *value)
static int mr_index_lengthval_object (DB_VALUE *value)
DB_VALUE_COMPARE_RESULT pr_midxkey_compare (DB_MIDXKEY *mul1, DB_MIDXKEY *mul2, int do_coercion, int total_order, int num_index_term, int *start_colp, int *result_size1, int *result_size2, int *diff_column, bool *dom_is_desc, bool *next_dom_is_desc)
PR_TYPE * pr_type_from_id (DB_TYPE id)
const char * pr_type_name (DB_TYPE id)
bool pr_is_set_type (DB_TYPE type)
int pr_is_string_type (DB_TYPE type)
int pr_is_prefix_key_type (DB_TYPE type)
int pr_is_variable_type (DB_TYPE id)
PR_TYPE * pr_find_type (const char *name)
int pr_mem_size (const PR_TYPE *type)
int pr_value_mem_size (const DB_VALUE *value)
int pr_midxkey_element_disk_size (char *mem, DB_DOMAIN *domain)
int pr_midxkey_get_element_offset (const DB_MIDXKEY *midxkey, int index)
int pr_midxkey_add_prefix (DB_VALUE *result, DB_VALUE *prefix, DB_VALUE *postfix, int n_prefix)
int pr_midxkey_remove_prefix (DB_VALUE *key, int prefix)
int pr_midxkey_common_prefix (DB_VALUE *key1, DB_VALUE *key2)
int pr_midxkey_unique_prefix (const DB_VALUE *db_midxkey1, const DB_VALUE *db_midxkey2, DB_VALUE *db_result)
int pr_midxkey_get_element_nocopy (const DB_MIDXKEY *midxkey, int index, DB_VALUE *value, int *prev_indexp, char **prev_ptrp)
int pr_midxkey_init_boundbits (char *bufptr, int n_atts)
int pr_midxkey_add_elements (DB_VALUE *keyval, DB_VALUE *dbvals, int num_dbvals, struct tp_domain *dbvals_domain_list)
int pr_data_writeval_disk_size (DB_VALUE *value)
int pr_index_writeval_disk_size (DB_VALUE *value)
void pr_data_writeval (struct or_buf *buf, DB_VALUE *value)
char * pr_valstring (const DB_VALUE *val)
int pr_complete_enum_value (DB_VALUE *value, struct tp_domain *domain)
int pr_get_compressed_data_from_buffer (struct or_buf *buf, char *data, int compressed_size, int expected_decompressed_size)
int pr_get_compression_length (const char *string, int str_length)
int pr_get_size_and_write_string_to_buffer (struct or_buf *buf, char *val_p, DB_VALUE *value, int *val_size, int align)
int pr_data_compress_string (const char *string, int str_length, char *compressed_string, int compress_buffer_size, int *compressed_length)
int pr_clear_compressed_string (DB_VALUE *value)
int pr_do_db_value_string_compression (DB_VALUE *value)
Variables
unsigned int db_on_server
static AREA * Value_area = NULL
int pr_Inhibit_oid_promotion = PR_INHIBIT_OID_PROMOTION_DEFAULT
int pr_Enable_string_compression = true
PR_TYPE tp_Null
PR_TYPE * tp_Type_null = &tp_Null
PR_TYPE tp_Integer
PR_TYPE * tp_Type_integer = &tp_Integer
PR_TYPE tp_Short
PR_TYPE * tp_Type_short = &tp_Short
PR_TYPE tp_Bigint
PR_TYPE * tp_Type_bigint = &tp_Bigint
PR_TYPE tp_Float
PR_TYPE * tp_Type_float = &tp_Float
PR_TYPE tp_Double
PR_TYPE * tp_Type_double = &tp_Double
PR_TYPE tp_Time
PR_TYPE * tp_Type_time = &tp_Time
PR_TYPE tp_Utime
PR_TYPE * tp_Type_utime = &tp_Utime
PR_TYPE tp_Timestamptz
PR_TYPE * tp_Type_Timestamptz = &tp_Timestamptz
PR_TYPE tp_Timestampltz
PR_TYPE tp_Datetime
PR_TYPE * tp_Type_datetime = &tp_Datetime
PR_TYPE tp_Datetimetz
PR_TYPE * tp_Type_Datetimetz = &tp_Datetimetz
PR_TYPE tp_Datetimeltz
PR_TYPE * tp_Type_datetimeltz = &tp_Datetimeltz
PR_TYPE tp_Monetary
PR_TYPE * tp_Type_monetary = &tp_Monetary
PR_TYPE tp_Date
PR_TYPE * tp_Type_date = &tp_Date
PR_TYPE tp_Object
PR_TYPE * tp_Type_object = &tp_Object
PR_TYPE tp_Elo
PR_TYPE * tp_Type_elo = &tp_Elo
PR_TYPE tp_Blob
PR_TYPE * tp_Type_blob = &tp_Blob
PR_TYPE tp_Clob
PR_TYPE * tp_Type_clob = &tp_Clob
PR_TYPE tp_Variable
PR_TYPE * tp_Type_variable = &tp_Variable
PR_TYPE tp_Substructure
PR_TYPE * tp_Type_substructure = &tp_Substructure
PR_TYPE tp_Pointer
PR_TYPE * tp_Type_pointer = &tp_Pointer
PR_TYPE tp_Error
PR_TYPE * tp_Type_error = &tp_Error
PR_TYPE tp_Oid
PR_TYPE * tp_Type_oid = &tp_Oid
PR_TYPE tp_Set
PR_TYPE * tp_Type_set = &tp_Set
PR_TYPE tp_Multiset
PR_TYPE * tp_Type_multiset = &tp_Multiset
PR_TYPE tp_Sequence
PR_TYPE * tp_Type_sequence = &tp_Sequence
PR_TYPE tp_Midxkey
PR_TYPE * tp_Type_midxkey = &tp_Midxkey
PR_TYPE tp_Vobj
PR_TYPE * tp_Type_vobj = &tp_Vobj
PR_TYPE tp_Numeric
PR_TYPE * tp_Type_numeric = &tp_Numeric
PR_TYPE tp_Enumeration
PR_TYPE * tp_Type_enumeration = &tp_Enumeration
PR_TYPE * tp_Type_id_map []
PR_TYPE tp_ResultSet
PR_TYPE * tp_Type_resultset = &tp_ResultSet
PR_TYPE tp_String
PR_TYPE * tp_Type_string = &tp_String
PR_TYPE tp_Char
PR_TYPE * tp_Type_char = &tp_Char
PR_TYPE tp_NChar
PR_TYPE * tp_Type_nchar = &tp_NChar
PR_TYPE tp_VarNChar
PR_TYPE * tp_Type_varnchar = &tp_VarNChar
PR_TYPE tp_Bit
PR_TYPE * tp_Type_bit = &tp_Bit
PR_TYPE tp_VarBit
PR_TYPE * tp_Type_varbit = &tp_VarBit
PR_TYPE tp_Json
PR_TYPE * tp_Type_json = &tp_Json
Macro Definition Documentation
#define BITS_IN_BYTE 8
Definition at line 126 of file object_primitive.c.
#define BITS_TO_BYTES (bit_cnt) (((bit_cnt) + 7) / 8)
Definition at line 127 of file object_primitive.c.
Referenced by mr_cmpdisk_bit_internal(), mr_data_cmpdisk_varbit(), mr_data_readmem_varbit(), mr_getmem_varbit(), mr_readval_bit_internal(), mr_readval_varbit_internal(), and mr_writeval_bit_internal().
#define DB_DOMAIN_INIT_CHAR (value, precision)
Value:
do {                                 \
    (value)->domain.general_info.type = DB_TYPE_CHAR;        \
    (value)->domain.general_info.is_null = 1;            \
    (value)->domain.char_info.length =               \
    (precision) == DB_DEFAULT_PRECISION ?            \
    TP_FLOATING_PRECISION_VALUE : (precision);           \
    (value)->need_clear = false;                 \
    (value)->data.ch.info.codeset = LANG_SYS_CODESET;            \
    (value)->domain.char_info.collation_id = LANG_SYS_COLLATION; \
  } while (0)
Definition at line 133 of file object_primitive.c.
Referenced by mr_initval_char(), and mr_setval_char().
#define DO_CONVERSION_TO_SQLTEXT (codeset) false
Definition at line 131 of file object_primitive.c.
Referenced by mr_readval_nchar_internal(), and mr_readval_varnchar_internal().
#define DO_CONVERSION_TO_SRVR_STR (codeset) false
Definition at line 130 of file object_primitive.c.
Referenced by mr_data_lengthval_nchar(), mr_lengthval_varnchar_internal(), mr_writeval_nchar_internal(), and mr_writeval_varnchar_internal().
#define IS_FLOATING_PRECISION (prec) ((prec) == TP_FLOATING_PRECISION_VALUE)
Definition at line 146 of file object_primitive.c.
Referenced by mr_cmpdisk_bit_internal(), mr_cmpdisk_char_internal(), mr_cmpdisk_nchar_internal(), mr_data_lengthmem_bit(), mr_data_lengthmem_char(), mr_data_lengthmem_nchar(), mr_data_lengthval_bit(), mr_data_lengthval_char(), mr_data_lengthval_nchar(), mr_data_readmem_char(), mr_data_writemem_char(), mr_getmem_char(), mr_index_lengthmem_bit(), mr_index_lengthmem_char(), mr_index_lengthmem_nchar(), mr_initmem_bit(), mr_initmem_char(), mr_initmem_nchar(), mr_initmem_numeric(), mr_readval_bit_internal(), mr_readval_char_internal(), mr_readval_nchar_internal(), mr_setmem_char(), mr_writeval_bit_internal(), mr_writeval_char_internal(), and mr_writeval_nchar_internal().
#define MR_CMP (d1, d2) ((d1) < (d2) ? DB_LT : (d1) > (d2) ? DB_GT : DB_EQ)
Definition at line 71 of file object_primitive.c.
Referenced by mr_cmpval_bigint(), mr_cmpval_date(), mr_cmpval_double(), mr_cmpval_elo(), mr_cmpval_enumeration(), mr_cmpval_error(), mr_cmpval_float(), mr_cmpval_int(), mr_cmpval_money(), mr_cmpval_ptr(), mr_cmpval_resultset(), mr_cmpval_short(), mr_cmpval_time(), mr_cmpval_timestamptz(), mr_cmpval_utime(), mr_data_cmpdisk_bigint(), mr_data_cmpdisk_date(), mr_data_cmpdisk_double(), mr_data_cmpdisk_enumeration(), mr_data_cmpdisk_float(), mr_data_cmpdisk_int(), mr_data_cmpdisk_money(), mr_data_cmpdisk_resultset(), mr_data_cmpdisk_short(), mr_data_cmpdisk_time(), mr_data_cmpdisk_timestamptz(), mr_data_cmpdisk_utime(), mr_index_cmpdisk_bigint(), mr_index_cmpdisk_date(), mr_index_cmpdisk_double(), mr_index_cmpdisk_enumeration(), mr_index_cmpdisk_float(), mr_index_cmpdisk_int(), mr_index_cmpdisk_money(), mr_index_cmpdisk_short(), mr_index_cmpdisk_time(), mr_index_cmpdisk_timestamptz(), and mr_index_cmpdisk_utime().
#define MR_CMP_RETURN_CODE (c) ((c) < 0 ? DB_LT : (c) > 0 ? DB_GT : DB_EQ)
Definition at line 74 of file object_primitive.c.
Referenced by mr_cmpdisk_bit_internal(), mr_cmpdisk_char_internal(), mr_cmpdisk_nchar_internal(), mr_cmpval_bit(), mr_cmpval_bit2(), mr_cmpval_char(), mr_cmpval_nchar(), mr_cmpval_object(), mr_cmpval_oid(), mr_cmpval_string(), mr_cmpval_varbit(), mr_cmpval_varbit2(), mr_cmpval_varnchar(), mr_data_cmpdisk_numeric(), mr_data_cmpdisk_object(), mr_data_cmpdisk_oid(), mr_data_cmpdisk_string(), mr_data_cmpdisk_varbit(), mr_data_cmpdisk_varnchar(), and mr_index_cmpdisk_oid().
#define MR_NUMERIC_SIZE (precision) DB_NUMERIC_BUF_SIZE
Definition at line 119 of file object_primitive.c.
Referenced by mr_data_lengthmem_numeric(), mr_data_lengthval_numeric(), mr_initmem_numeric(), and mr_setmem_numeric().
#define MR_OID_SIZE sizeof(WS_MEMOID)
Definition at line 83 of file object_primitive.c.
Referenced by mr_data_lengthval_object().
#define OR_NUMERIC_SIZE (precision) DB_NUMERIC_BUF_SIZE
Definition at line 118 of file object_primitive.c.
Referenced by mr_data_lengthmem_numeric(), mr_data_lengthval_numeric(), mr_data_readmem_numeric(), mr_data_readval_numeric(), mr_data_writemem_numeric(), and mr_data_writeval_numeric().
#define PR_INHIBIT_OID_PROMOTION_DEFAULT 0
Definition at line 110 of file object_primitive.c.
#define STR_SIZE (prec, codeset)
Value:
(((codeset) == INTL_CODESET_RAW_BITS) ? ((prec+7)/8) :          \
      INTL_CODESET_MULT (codeset) * (prec))
Definition at line 121 of file object_primitive.c.
Referenced by mr_cmpdisk_bit_internal(), mr_cmpdisk_char_internal(), mr_cmpdisk_nchar_internal(), mr_data_lengthmem_bit(), mr_data_lengthmem_char(), mr_data_lengthmem_nchar(), mr_data_lengthval_bit(), mr_data_lengthval_char(), mr_data_lengthval_nchar(), mr_data_readmem_bit(), mr_data_readmem_char(), mr_data_readmem_nchar(), mr_data_writemem_bit(), mr_data_writemem_char(), mr_data_writemem_nchar(), mr_getmem_bit(), mr_getmem_char(), mr_getmem_nchar(), mr_index_lengthmem_bit(), mr_index_lengthmem_char(), mr_index_lengthmem_nchar(), mr_initmem_bit(), mr_initmem_char(), mr_initmem_nchar(), mr_lengthval_varnchar_internal(), mr_readval_bit_internal(), mr_readval_char_internal(), mr_readval_nchar_internal(), mr_readval_varnchar_internal(), mr_setmem_bit(), mr_setmem_char(), mr_setmem_nchar(), mr_writeval_bit_internal(), mr_writeval_char_internal(), mr_writeval_nchar_internal(), and mr_writeval_varnchar_internal().
#define VALUE_AREA_COUNT 1024
Definition at line 88 of file object_primitive.c.
Referenced by pr_area_init().
Function Documentation
static int getmem_elo_with_type (void * memptr, TP_DOMAIN * domain, DB_VALUE * value, bool copy, DB_TYPE type) static
Definition at line 5706 of file object_primitive.c.
References db_make_elo(), db_make_null(), elo_copy_structure(), db_value::need_clear, NO_ERROR, NULL, and db_elo::size.
Referenced by pr_type::get_cmpval_function(), mr_getmem_blob(), and mr_getmem_clob().
static DB_VALUE_COMPARE_RESULT mr_cmpdisk_bit_internal (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp, int align) static
Definition at line 14888 of file object_primitive.c.
References assert, bit_compare(), BITS_TO_BYTES, INT_ALIGNMENT, INTL_CODESET_RAW_BITS, IS_FLOATING_PRECISION, MR_CMP_RETURN_CODE, OR_GET_INT, OR_INT_SIZE, tp_domain::precision, STR_SIZE, and TP_DOMAIN_CODESET.
Referenced by pr_type::get_cmpval_function(), mr_data_cmpdisk_bit(), and mr_index_cmpdisk_bit().
static DB_VALUE_COMPARE_RESULT mr_cmpdisk_char_internal (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp, int align) static
Definition at line 11930 of file object_primitive.c.
References tp_domain::collation_id, DB_TYPE_CHAR, DB_TYPE_NCHAR, pr_type::id, INT_ALIGNMENT, IS_FLOATING_PRECISION, MR_CMP_RETURN_CODE, OR_GET_INT, OR_INT_SIZE, tp_domain::precision, prm_get_bool_value(), PRM_ID_IGNORE_TRAILING_SPACE, QSTR_CHAR_COMPARE, STR_SIZE, TP_DOMAIN_CODESET, and tp_domain::type.
Referenced by pr_type::get_cmpval_function(), mr_data_cmpdisk_char(), and mr_index_cmpdisk_char().
static DB_VALUE_COMPARE_RESULT mr_cmpdisk_nchar_internal (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp, int align) static
Definition at line 12912 of file object_primitive.c.
References tp_domain::collation_id, INT_ALIGNMENT, IS_FLOATING_PRECISION, MR_CMP_RETURN_CODE, OR_GET_INT, OR_INT_SIZE, tp_domain::precision, QSTR_NCHAR_COMPARE, STR_SIZE, and TP_DOMAIN_CODESET.
Referenced by pr_type::get_cmpval_function(), mr_data_cmpdisk_nchar(), and mr_index_cmpdisk_nchar().
static DB_VALUE_COMPARE_RESULT mr_cmpval_bigint (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 2897 of file object_primitive.c.
References db_get_bigint(), and MR_CMP.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_bit (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 14924 of file object_primitive.c.
References bit_compare(), db_get_string(), db_get_string_size(), DB_UNK, MR_CMP_RETURN_CODE, NULL, and REINTERPRET_CAST.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_bit2 (DB_VALUE * value1, DB_VALUE * value2, int length, int do_coercion, int total_order, int * start_colp) static
Definition at line 14944 of file object_primitive.c.
References bit_compare(), db_get_string(), db_get_string_size(), DB_UNK, MR_CMP_RETURN_CODE, NULL, and REINTERPRET_CAST.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_char (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 11978 of file object_primitive.c.
References assert, db_data::ch, db_domain_info::char_info, db_value::data, DB_EQ, db_get_string(), db_get_string_codeset(), db_get_string_size(), DB_GT, DB_LT, DB_TYPE_CHAR, DB_TYPE_NCHAR, DB_TYPE_STRING, DB_TYPE_VARNCHAR, DB_UNK, db_value::domain, i, db_char::info, db_char::is_max_string, MR_CMP_RETURN_CODE, NULL, prm_get_bool_value(), PRM_ID_IGNORE_TRAILING_SPACE, QSTR_CHAR_COMPARE, REINTERPRET_CAST, and db_domain_info::char_info::type.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_date (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 4873 of file object_primitive.c.
References d1, db_get_date(), and MR_CMP.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_datetime (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 4241 of file object_primitive.c.
References db_datetime::date, DB_EQ, db_get_datetime(), DB_GT, DB_LT, and db_datetime::time.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_datetimetz (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 4457 of file object_primitive.c.
References db_datetime::date, db_datetimetz::datetime, DB_EQ, db_get_datetimetz(), DB_GT, DB_LT, DB_NE, db_datetime::time, and db_datetimetz::tz_id.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_double (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 3263 of file object_primitive.c.
References d1, db_get_double(), and MR_CMP.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_elo (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 6117 of file object_primitive.c.
References db_get_elo(), and MR_CMP.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_enumeration (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 15946 of file object_primitive.c.
References db_get_enum_short(), and MR_CMP.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_error (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 6539 of file object_primitive.c.
References db_get_error(), and MR_CMP.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_float (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 3072 of file object_primitive.c.
References db_get_float(), and MR_CMP.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_int (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 2553 of file object_primitive.c.
References db_get_int(), and MR_CMP.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_json (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 16924 of file object_primitive.c.
References assert, db_convert_json_into_scalar(), DB_EQ, db_get_json_document(), DB_GT, DB_IS_NULL, db_json_doc_is_uncomparable(), db_json_get_json_body_from_document(), db_json_get_type(), DB_LT, db_make_null(), db_make_string(), DB_UNK, db_value::need_clear, NO_ERROR, NULL, pr_clear_value(), and tp_value_compare_with_error().
Referenced by pr_type::get_cmpval_function(), and mr_data_cmpdisk_json().
static DB_VALUE_COMPARE_RESULT mr_cmpval_midxkey (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 8089 of file object_primitive.c.
References assert_release, DB_EQ, db_get_midxkey(), DB_GT, DB_LT, DB_UNK, db_midxkey::domain, db_midxkey::ncolumns, NULL, pr_midxkey_compare(), and tp_domain::precision.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_money (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 4702 of file object_primitive.c.
References db_monetary::amount, db_get_monetary(), and MR_CMP.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_nchar (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 12950 of file object_primitive.c.
References assert, db_domain_info::char_info, db_get_string(), db_get_string_codeset(), db_get_string_size(), DB_TYPE_CHAR, DB_TYPE_NCHAR, DB_TYPE_STRING, DB_TYPE_VARNCHAR, DB_UNK, db_value::domain, i, MR_CMP_RETURN_CODE, nchar_compare(), NULL, prm_get_bool_value(), PRM_ID_IGNORE_TRAILING_SPACE, QSTR_NCHAR_COMPARE, REINTERPRET_CAST, and db_domain_info::char_info::type.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_null (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 2389 of file object_primitive.c.
References DB_UNK.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_numeric (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 8690 of file object_primitive.c.
References DB_EQ, db_get_int(), DB_GT, DB_LT, DB_UNK, NO_ERROR, and numeric_db_value_compare().
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_object (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 5429 of file object_primitive.c.
References assert, DB_EQ, db_get_class(), db_get_object(), db_get_oid(), DB_GT, db_is_updatable_object(), DB_LT, db_real_instance(), DB_TYPE_OID, DB_VALUE_DOMAIN_TYPE, MR_CMP_RETURN_CODE, NULL, oid_compare(), oid_Null_oid, tp_value_compare(), vid_get_keys(), WS_ISVID, and WS_OID.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_oid (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 6790 of file object_primitive.c.
References db_get_oid(), DB_UNK, MR_CMP_RETURN_CODE, NULL, and oid_compare().
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_ptr (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 6406 of file object_primitive.c.
References db_get_pointer(), and MR_CMP.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_resultset (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 9952 of file object_primitive.c.
References db_get_resultset(), and MR_CMP.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_sequence (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 7519 of file object_primitive.c.
References db_get_set(), and set_seq_compare().
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_set (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 7385 of file object_primitive.c.
References db_get_set(), and set_compare_order().
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_short (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 2726 of file object_primitive.c.
References db_get_short(), and MR_CMP.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_string (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 11083 of file object_primitive.c.
References assert, db_data::ch, db_domain_info::char_info, db_value::data, DB_EQ, db_get_string(), db_get_string_codeset(), db_get_string_size(), DB_GT, DB_LT, DB_TYPE_CHAR, DB_TYPE_NCHAR, DB_UNK, db_value::domain, i, db_char::info, db_char::is_max_string, MR_CMP_RETURN_CODE, NULL, prm_get_bool_value(), PRM_ID_IGNORE_TRAILING_SPACE, QSTR_COMPARE, REINTERPRET_CAST, strlen, and db_domain_info::char_info::type.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_sub (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 6275 of file object_primitive.c.
References DB_UNK.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_time (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 3441 of file object_primitive.c.
References db_get_time(), and MR_CMP.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_timestamptz (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 3890 of file object_primitive.c.
References db_get_timestamptz(), DB_NE, MR_CMP, db_timestamptz::timestamp, and db_timestamptz::tz_id.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_utime (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 3696 of file object_primitive.c.
References db_get_timestamp(), and MR_CMP.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_varbit (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 15615 of file object_primitive.c.
References db_get_string(), db_get_string_size(), DB_UNK, MR_CMP_RETURN_CODE, NULL, REINTERPRET_CAST, and varbit_compare().
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_varbit2 (DB_VALUE * value1, DB_VALUE * value2, int length, int do_coercion, int total_order, int * start_colp) static
Definition at line 15636 of file object_primitive.c.
References db_get_string(), db_get_string_size(), DB_UNK, MR_CMP_RETURN_CODE, NULL, REINTERPRET_CAST, and varbit_compare().
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_variable (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 6188 of file object_primitive.c.
References DB_UNK.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_varnchar (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 14138 of file object_primitive.c.
References assert, db_domain_info::char_info, db_get_string(), db_get_string_codeset(), db_get_string_size(), DB_TYPE_CHAR, DB_TYPE_NCHAR, DB_UNK, db_value::domain, i, MR_CMP_RETURN_CODE, NULL, prm_get_bool_value(), PRM_ID_IGNORE_TRAILING_SPACE, QSTR_NCHAR_COMPARE, REINTERPRET_CAST, strlen, db_domain_info::char_info::type, and varnchar_compare().
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_cmpval_vobj (DB_VALUE * value1, DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) static
Definition at line 8359 of file object_primitive.c.
References db_get_set(), and vobj_compare().
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_bigint (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 2884 of file object_primitive.c.
References assert, MR_CMP, NULL, and OR_GET_BIGINT.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_bit (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 14880 of file object_primitive.c.
References assert, INT_ALIGNMENT, mr_cmpdisk_bit_internal(), and NULL.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_char (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 11922 of file object_primitive.c.
References assert, INT_ALIGNMENT, mr_cmpdisk_char_internal(), and NULL.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_date (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 4860 of file object_primitive.c.
References assert, d1, MR_CMP, NULL, and OR_GET_DATE.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_datetime (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 4198 of file object_primitive.c.
References assert, db_datetime::date, DB_EQ, DB_GT, DB_LT, NULL, OR_GET_DATETIME, and db_datetime::time.
Referenced by pr_type::get_cmpval_function(), and mr_data_cmpdisk_datetimetz().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_datetimetz (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 4449 of file object_primitive.c.
References mr_data_cmpdisk_datetime().
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_double (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 3250 of file object_primitive.c.
References assert, d1, MR_CMP, NULL, and OR_GET_DOUBLE.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_elo (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 6105 of file object_primitive.c.
References assert, DB_UNK, and NULL.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_enumeration (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 15932 of file object_primitive.c.
References assert, MR_CMP, NULL, and OR_GET_SHORT.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_error (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 6530 of file object_primitive.c.
References assert, DB_UNK, and NULL.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_float (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 3059 of file object_primitive.c.
References assert, MR_CMP, NULL, and OR_GET_FLOAT.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_int (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 2540 of file object_primitive.c.
References assert, MR_CMP, NULL, and OR_GET_INT.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_json (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 16874 of file object_primitive.c.
References ASSERT_ERROR, db_json_deserialize(), db_make_json(), DB_UNK, mr_cmpval_json(), NO_ERROR, NULL, or_init(), pr_clear_value(), and rc.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_midxkey (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 8133 of file object_primitive.c.
References assert, mr_index_cmpdisk_midxkey(), and NULL.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_money (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 4689 of file object_primitive.c.
References db_monetary::amount, assert, MR_CMP, NULL, and OR_GET_MONETARY.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_nchar (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 12904 of file object_primitive.c.
References assert, INT_ALIGNMENT, mr_cmpdisk_nchar_internal(), and NULL.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_null (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 2372 of file object_primitive.c.
References assert, DB_UNK, and NULL.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_numeric (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 8654 of file object_primitive.c.
References assert, db_get_int(), DB_UNK, MR_CMP_RETURN_CODE, mr_data_readval_numeric(), NO_ERROR, NULL, numeric_db_value_compare(), or_init(), and rc.
Referenced by pr_type::get_cmpval_function(), and mr_index_cmpdisk_numeric().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_object (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 5409 of file object_primitive.c.
References assert, MR_CMP_RETURN_CODE, NULL, oid_compare(), and OR_GET_OID.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_oid (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 6772 of file object_primitive.c.
References assert, MR_CMP_RETURN_CODE, NULL, oid_compare(), and OR_GET_OID.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_ptr (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 6397 of file object_primitive.c.
References assert, DB_UNK, and NULL.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_resultset (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 9935 of file object_primitive.c.
References assert, tp_domain::is_desc, MR_CMP, NULL, OR_GET_INT, TP_DOMAIN_TYPE, and tp_valid_indextype().
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_sequence (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 7492 of file object_primitive.c.
References assert, DB_UNK, tp_domain::is_desc, NULL, or_unpack_set(), setobj_compare_order(), setobj_free(), TP_DOMAIN_TYPE, and tp_valid_indextype().
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_set (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 7358 of file object_primitive.c.
References assert, DB_UNK, tp_domain::is_desc, NULL, or_unpack_set(), setobj_compare_order(), setobj_free(), TP_DOMAIN_TYPE, and tp_valid_indextype().
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_short (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 2713 of file object_primitive.c.
References assert, MR_CMP, NULL, and OR_GET_SHORT.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_string (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 10923 of file object_primitive.c.
References ARG_FILE_LINE, assert, ASSERT_ERROR, cleanup(), tp_domain::collation_id, db_private_alloc, db_private_free_and_init, DB_UNK, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), MR_CMP_RETURN_CODE, NO_ERROR, NULL, OR_BYTE_SIZE, OR_GET_BYTE, or_get_varchar_compression_lengths(), or_init(), OR_MINIMUM_STRING_LENGTH_FOR_COMPRESSION, pr_get_compressed_data_from_buffer(), prm_get_bool_value(), PRM_ID_IGNORE_TRAILING_SPACE, or_buf::ptr, QSTR_COMPARE, and rc.
Referenced by pr_type::get_cmpval_function(), and mr_index_cmpdisk_string().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_sub (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 6267 of file object_primitive.c.
References assert, DB_UNK, and NULL.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_time (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 3428 of file object_primitive.c.
References assert, MR_CMP, NULL, and OR_GET_TIME.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_timestamptz (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 3875 of file object_primitive.c.
References assert, MR_CMP, NULL, and OR_GET_UTIME.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_utime (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 3683 of file object_primitive.c.
References assert, MR_CMP, NULL, and OR_GET_UTIME.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_varbit (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 15588 of file object_primitive.c.
References assert, BITS_TO_BYTES, error(), MR_CMP_RETURN_CODE, NO_ERROR, NULL, or_get_varbit_length(), or_init(), or_buf::ptr, and varbit_compare().
Referenced by pr_type::get_cmpval_function(), and mr_index_cmpdisk_varbit().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_variable (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 6180 of file object_primitive.c.
References assert, DB_UNK, and NULL.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_varnchar (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 13992 of file object_primitive.c.
References ARG_FILE_LINE, assert, ASSERT_ERROR, cleanup(), tp_domain::collation_id, db_private_alloc, db_private_free_and_init, DB_UNK, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), MR_CMP_RETURN_CODE, NO_ERROR, NULL, OR_BYTE_SIZE, OR_GET_BYTE, or_get_varchar_compression_lengths(), or_init(), OR_MINIMUM_STRING_LENGTH_FOR_COMPRESSION, pr_get_compressed_data_from_buffer(), or_buf::ptr, QSTR_NCHAR_COMPARE, rc, and TP_DOMAIN_CODESET.
Referenced by pr_type::get_cmpval_function(), and mr_index_cmpdisk_varnchar().
static DB_VALUE_COMPARE_RESULT mr_data_cmpdisk_vobj (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 8332 of file object_primitive.c.
References assert, DB_UNK, tp_domain::is_desc, NULL, or_unpack_set(), setobj_free(), setvobj_compare(), TP_DOMAIN_TYPE, and tp_valid_indextype().
Referenced by pr_type::get_cmpval_function().
static int mr_data_lengthmem_bit (void * memptr, TP_DOMAIN * domain, int disk) static
Definition at line 14396 of file object_primitive.c.
References assert, INTL_CODESET_RAW_BITS, IS_FLOATING_PRECISION, tp_domain::precision, STR_SIZE, and TP_DOMAIN_CODESET.
Referenced by pr_type::get_cmpval_function().
static int mr_data_lengthmem_char (void * memptr, TP_DOMAIN * domain, int disk) static
Definition at line 11385 of file object_primitive.c.
References assert, IS_FLOATING_PRECISION, tp_domain::precision, STR_SIZE, and TP_DOMAIN_CODESET.
Referenced by pr_type::get_cmpval_function().
static int mr_data_lengthmem_elo (void * memptr, TP_DOMAIN * domain, int disk) static
Definition at line 5815 of file object_primitive.c.
References assert, assert_release, ELO_NULL, db_elo::locator, db_elo::meta_data, NULL, OR_BIGINT_SIZE, OR_INT_SIZE, or_packed_string_length(), pr_type::size, and db_elo::type.
Referenced by pr_type::get_cmpval_function(), and mr_data_lengthval_elo().
static int mr_data_lengthmem_error (void * memptr, TP_DOMAIN * domain, int disk) static
Definition at line 6477 of file object_primitive.c.
Referenced by pr_type::get_cmpval_function(), and mr_data_lengthval_error().
static int mr_data_lengthmem_json (void * memptr, TP_DOMAIN * domain, int disk) static
Definition at line 16643 of file object_primitive.c.
References db_json_serialize_length(), db_json::document, NULL, and pr_type::size.
Referenced by pr_type::get_cmpval_function().
static int mr_data_lengthmem_midxkey (void * memptr, TP_DOMAIN * domain, int disk) static
Definition at line 8198 of file object_primitive.c.
References mr_index_lengthmem_midxkey().
Referenced by pr_type::get_cmpval_function().
static int mr_data_lengthmem_nchar (void * memptr, TP_DOMAIN * domain, int disk) static
Definition at line 12296 of file object_primitive.c.
References assert, IS_FLOATING_PRECISION, tp_domain::precision, STR_SIZE, and TP_DOMAIN_CODESET.
Referenced by pr_type::get_cmpval_function().
static int mr_data_lengthmem_numeric (void * mem, TP_DOMAIN * domain, int disk) static
Definition at line 8480 of file object_primitive.c.
References MR_NUMERIC_SIZE, OR_NUMERIC_SIZE, and tp_domain::precision.
Referenced by pr_type::get_cmpval_function(), and mr_index_lengthmem_numeric().
static int mr_data_lengthmem_ptr (void * memptr, TP_DOMAIN * domain, int disk) static
Definition at line 6345 of file object_primitive.c.
Referenced by pr_type::get_cmpval_function(), and mr_data_lengthval_ptr().
static int mr_data_lengthmem_set (void * memptr, TP_DOMAIN * domain, int disk) static
Definition at line 7008 of file object_primitive.c.
References or_packed_set_length(), and pr_type::size.
Referenced by pr_type::get_cmpval_function().
static int mr_data_lengthmem_string (void * memptr, TP_DOMAIN * domain, int disk) static
Definition at line 10114 of file object_primitive.c.
References NULL, OR_MINIMUM_STRING_LENGTH_FOR_COMPRESSION, or_packed_varchar_length(), pr_get_compression_length(), PRIM_TEMPORARY_DISK_SIZE, pr_type::size, and tp_String.
Referenced by pr_type::get_cmpval_function().
static int mr_data_lengthmem_sub (void * mem, TP_DOMAIN * domain, int disk) static
Definition at line 6232 of file object_primitive.c.
Referenced by pr_type::get_cmpval_function().
static int mr_data_lengthmem_varbit (void * memptr, TP_DOMAIN * domain, int disk) static
Definition at line 15123 of file object_primitive.c.
References NULL, or_packed_varbit_length(), pr_type::size, and tp_VarBit.
Referenced by pr_type::get_cmpval_function().
static int mr_data_lengthmem_varnchar (void * memptr, TP_DOMAIN * domain, int disk) static
Definition at line 13241 of file object_primitive.c.
References NULL, OR_MINIMUM_STRING_LENGTH_FOR_COMPRESSION, or_packed_varchar_length(), pr_get_compression_length(), PRIM_TEMPORARY_DISK_SIZE, pr_type::size, and tp_VarNChar.
Referenced by pr_type::get_cmpval_function().
static int mr_data_lengthval_bit (DB_VALUE * value, int disk) static
Definition at line 14560 of file object_primitive.c.
References assert, db_get_string(), db_get_string_codeset(), db_get_string_size(), db_value_precision(), INTL_CODESET_RAW_BITS, IS_FLOATING_PRECISION, NULL, OR_INT_SIZE, and STR_SIZE.
Referenced by pr_type::get_cmpval_function(), and mr_index_lengthval_bit().
static int mr_data_lengthval_char (DB_VALUE * value, int disk) static
Definition at line 11567 of file object_primitive.c.
References db_get_string(), db_get_string_codeset(), db_get_string_size(), db_value_precision(), IS_FLOATING_PRECISION, NULL, OR_INT_SIZE, STR_SIZE, and strlen.
Referenced by pr_type::get_cmpval_function(), and mr_index_lengthval_char().
static int mr_data_lengthval_elo (DB_VALUE * value, int disk) static
Definition at line 5845 of file object_primitive.c.
References db_get_elo(), mr_data_lengthmem_elo(), and NULL.
Referenced by pr_type::get_cmpval_function().
static int mr_data_lengthval_error (DB_VALUE * value, int disk) static
Definition at line 6483 of file object_primitive.c.
References db_get_error(), error(), mr_data_lengthmem_error(), NO_ERROR, and NULL.
Referenced by pr_type::get_cmpval_function().
static int mr_data_lengthval_json (DB_VALUE * value, int disk) static
Definition at line 16793 of file object_primitive.c.
References db_value::data, db_json_serialize_length(), db_json::document, db_data::json, NULL, and pr_type::size.
Referenced by pr_type::get_cmpval_function(), and mr_data_writeval_json().
static int mr_data_lengthval_midxkey (DB_VALUE * value, int disk) static
Definition at line 8272 of file object_primitive.c.
References mr_index_lengthval_midxkey().
Referenced by pr_type::get_cmpval_function().
static int mr_data_lengthval_nchar (DB_VALUE * value, int disk) static
Definition at line 12465 of file object_primitive.c.
References db_get_string(), db_get_string_codeset(), db_get_string_length(), db_get_string_size(), db_on_server, db_private_alloc, db_private_free_and_init, db_value_precision(), DO_CONVERSION_TO_SRVR_STR, intl_char_size(), intl_convert_charset(), IS_FLOATING_PRECISION, lang_charset(), NULL, OR_INT_SIZE, STR_SIZE, and strlen.
Referenced by pr_type::get_cmpval_function(), and mr_index_lengthval_nchar().
static int mr_data_lengthval_numeric (DB_VALUE * value, int disk) static
Definition at line 8545 of file object_primitive.c.
References db_value_precision(), MR_NUMERIC_SIZE, NULL, and OR_NUMERIC_SIZE.
Referenced by pr_type::get_cmpval_function(), and mr_index_lengthval_numeric().
static int mr_data_lengthval_object (DB_VALUE * value, int disk) static
Definition at line 5118 of file object_primitive.c.
References db_get_object(), DB_TYPE_OBJECT, DB_VALUE_TYPE, error(), mr_data_lengthval_set(), MR_OID_SIZE, NULL, OR_OID_SIZE, pr_clear_value(), pr_type::size, vid_object_to_vobj(), WS_IS_DELETED, and WS_ISVID.
Referenced by pr_type::get_cmpval_function().
static int mr_data_lengthval_ptr (DB_VALUE * value, int disk) static
Definition at line 6351 of file object_primitive.c.
References db_get_pointer(), mr_data_lengthmem_ptr(), NO_ERROR, and NULL.
Referenced by pr_type::get_cmpval_function().
static int mr_data_lengthval_set (DB_VALUE * value, int disk) static
Definition at line 7027 of file object_primitive.c.
References db_get_set(), db_set::disk_set, db_set::disk_size, NO_ERROR, NULL, or_packed_set_length(), db_set::owner, set_get_setobj(), pr_type::size, and ws_pin().
Referenced by pr_type::get_cmpval_function(), and mr_data_lengthval_object().
static int mr_data_lengthval_string (DB_VALUE * value, int disk) static
Definition at line 10443 of file object_primitive.c.
References INT_ALIGNMENT, and mr_lengthval_string_internal().
Referenced by pr_type::get_cmpval_function().
static int mr_data_lengthval_sub (DB_VALUE * value, int disk) static
Definition at line 6238 of file object_primitive.c.
Referenced by pr_type::get_cmpval_function().
static int mr_data_lengthval_varbit (DB_VALUE * value, int disk) static
Definition at line 15361 of file object_primitive.c.
References INT_ALIGNMENT, and mr_lengthval_varbit_internal().
Referenced by pr_type::get_cmpval_function().
static int mr_data_lengthval_variable (DB_VALUE * value, int disk) static
Definition at line 6161 of file object_primitive.c.
Referenced by pr_type::get_cmpval_function().
static int mr_data_lengthval_varnchar (DB_VALUE * value, int disk) static
Definition at line 13434 of file object_primitive.c.
References INT_ALIGNMENT, and mr_lengthval_varnchar_internal().
Referenced by pr_type::get_cmpval_function().
static void mr_data_readmem_bigint (OR_BUF * buf, void * mem, TP_DOMAIN * domain, int size) static
Definition at line 2773 of file object_primitive.c.
References pr_type::disksize, NO_ERROR, NULL, or_advance(), or_get_bigint(), and rc.
Referenced by pr_type::get_cmpval_function().
static void mr_data_readmem_bit (OR_BUF * buf, void * mem, TP_DOMAIN * domain, int size) static
Definition at line 14422 of file object_primitive.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, er_set(), ER_SM_CORRUPTED, INTL_CODESET_RAW_BITS, NULL, or_abort(), or_advance(), or_get_data(), tp_domain::precision, STR_SIZE, and TP_DOMAIN_CODESET.
Referenced by pr_type::get_cmpval_function().
static void mr_data_readmem_char (OR_BUF * buf, void * mem, TP_DOMAIN * domain, int size) static
Definition at line 11434 of file object_primitive.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, er_set(), ER_SM_CORRUPTED, IS_FLOATING_PRECISION, NULL, or_abort(), or_advance(), or_get_data(), tp_domain::precision, STR_SIZE, and TP_DOMAIN_CODESET.
Referenced by pr_type::get_cmpval_function().
static void mr_data_readmem_date (OR_BUF * buf, void * mem, TP_DOMAIN * domain, int size) static
Definition at line 4748 of file object_primitive.c.
References pr_type::disksize, NULL, or_advance(), and or_get_date().
Referenced by pr_type::get_cmpval_function().
static void mr_data_readmem_datetime (OR_BUF * buf, void * mem, TP_DOMAIN * domain, int size) static
Definition at line 4010 of file object_primitive.c.
References pr_type::disksize, NULL, or_advance(), and or_get_datetime().
Referenced by pr_type::get_cmpval_function().
static void mr_data_readmem_datetimetz (OR_BUF * buf, void * mem, TP_DOMAIN * domain, int size) static
Definition at line 4345 of file object_primitive.c.
References pr_type::disksize, NULL, or_advance(), and or_get_datetimetz().
Referenced by pr_type::get_cmpval_function().
static void mr_data_readmem_double (OR_BUF * buf, void * mem, TP_DOMAIN * domain, int size) static
Definition at line 3136 of file object_primitive.c.
References pr_type::disksize, NO_ERROR, NULL, or_advance(), or_get_double(), OR_MOVE_DOUBLE, and rc.
Referenced by pr_type::get_cmpval_function().
static void mr_data_readmem_elo (OR_BUF * buf, void * memptr, TP_DOMAIN * domain, int size) static
Definition at line 5976 of file object_primitive.c.
References db_private_alloc, db_private_free_and_init, elo_copy_structure(), NO_ERROR, NULL, or_abort(), or_advance(), peekmem_elo(), and rc.
Referenced by pr_type::get_cmpval_function(), and readval_elo_with_type().
static void mr_data_readmem_enumeration (OR_BUF * buf, void * mem, TP_DOMAIN * domain, int size) static
Definition at line 15775 of file object_primitive.c.
References pr_type::disksize, NO_ERROR, NULL, or_advance(), or_get_short(), and rc.
Referenced by pr_type::get_cmpval_function().
static void mr_data_readmem_error (OR_BUF * buf, void * memptr, TP_DOMAIN * domain, int size) static
Definition at line 6504 of file object_primitive.c.
References NO_ERROR.
Referenced by pr_type::get_cmpval_function().
static void mr_data_readmem_float (OR_BUF * buf, void * mem, TP_DOMAIN * domain, int size) static
Definition at line 2948 of file object_primitive.c.
References pr_type::disksize, NO_ERROR, NULL, or_advance(), or_get_float(), and rc.
Referenced by pr_type::get_cmpval_function().
static void mr_data_readmem_int (OR_BUF * buf, void * mem, TP_DOMAIN * domain, int size) static
Definition at line 2432 of file object_primitive.c.
References pr_type::disksize, NO_ERROR, NULL, or_advance(), or_get_int(), and rc.
Referenced by pr_type::get_cmpval_function().
static void mr_data_readmem_json (OR_BUF * buf, void * memptr, TP_DOMAIN * domain, int size) static
Definition at line 16689 of file object_primitive.c.
References assert, ASSERT_ERROR, db_json_delete_doc(), db_json_deserialize(), db_json::document, mr_initmem_json(), NO_ERROR, NULL, or_advance(), and rc.
Referenced by pr_type::get_cmpval_function().
static void mr_data_readmem_money (OR_BUF * buf, void * mem, TP_DOMAIN * domain, int size) static
Definition at line 4564 of file object_primitive.c.
References pr_type::disksize, NULL, or_advance(), and or_get_monetary().
Referenced by pr_type::get_cmpval_function().
static void mr_data_readmem_nchar (OR_BUF * buf, void * mem, TP_DOMAIN * domain, int size) static
Definition at line 12339 of file object_primitive.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, er_set(), ER_SM_CORRUPTED, NULL, or_abort(), or_advance(), or_get_data(), tp_domain::precision, STR_SIZE, and TP_DOMAIN_CODESET.
Referenced by pr_type::get_cmpval_function().
static void mr_data_readmem_null (OR_BUF * buf, void * memptr, TP_DOMAIN * domain, int size) static
Definition at line 2302 of file object_primitive.c.
Referenced by pr_type::get_cmpval_function().
static void mr_data_readmem_numeric (OR_BUF * buf, void * mem, TP_DOMAIN * domain, int size) static
Definition at line 8444 of file object_primitive.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, er_set(), ER_SM_CORRUPTED, NULL, or_abort(), or_advance(), or_get_data(), OR_NUMERIC_SIZE, and tp_domain::precision.
Referenced by pr_type::get_cmpval_function().
static void mr_data_readmem_object (OR_BUF * buf, void * memptr, TP_DOMAIN * domain, int size) static
Definition at line 5223 of file object_primitive.c.
References pr_type::disksize, NULL, ws_memoid::oid, or_advance(), or_get_oid(), and ws_memoid::pointer.
Referenced by pr_type::get_cmpval_function().
static void mr_data_readmem_oid (OR_BUF * buf, void * memptr, TP_DOMAIN * domain, int size) static
Definition at line 6650 of file object_primitive.c.
References NULL, and or_get_oid().
Referenced by pr_type::get_cmpval_function().
static void mr_data_readmem_ptr (OR_BUF * buf, void * memptr, TP_DOMAIN * domain, int size) static
Definition at line 6372 of file object_primitive.c.
References NULL.
Referenced by pr_type::get_cmpval_function().
static void mr_data_readmem_resultset (OR_BUF * buf, void * mem, TP_DOMAIN * domain, int size) static
Definition at line 9875 of file object_primitive.c.
References pr_type::disksize, NO_ERROR, NULL, or_advance(), or_get_int(), and rc.
Referenced by pr_type::get_cmpval_function().
static void mr_data_readmem_set (OR_BUF * buf, void * memptr, TP_DOMAIN * domain, int size) static
Definition at line 7152 of file object_primitive.c.
References NULL, or_abort(), or_advance(), or_get_set(), and setobj_free().
Referenced by pr_type::get_cmpval_function().
static void mr_data_readmem_short (OR_BUF * buf, void * mem, TP_DOMAIN * domain, int size) static
Definition at line 2601 of file object_primitive.c.
References pr_type::disksize, NO_ERROR, NULL, or_advance(), or_get_short(), and rc.
Referenced by pr_type::get_cmpval_function().
static void mr_data_readmem_string (OR_BUF * buf, void * memptr, TP_DOMAIN * domain, int size) static
Definition at line 10214 of file object_primitive.c.
References db_private_alloc, db_private_free, db_private_free_and_init, NO_ERROR, NULL, or_abort(), or_advance(), or_get_align32(), or_get_varchar_compression_lengths(), pr_get_compressed_data_from_buffer(), or_buf::ptr, and rc.
Referenced by pr_type::get_cmpval_function(), and mr_data_readmem_varnchar().
static void mr_data_readmem_sub (OR_BUF * buf, void * mem, TP_DOMAIN * domain, int size) static
Definition at line 6249 of file object_primitive.c.
Referenced by pr_type::get_cmpval_function().
static void mr_data_readmem_time (OR_BUF * buf, void * mem, TP_DOMAIN * domain, int size) static
Definition at line 3314 of file object_primitive.c.
References pr_type::disksize, NULL, or_advance(), and or_get_time().
Referenced by pr_type::get_cmpval_function().
static void mr_data_readmem_timestamptz (OR_BUF * buf, void * mem, TP_DOMAIN * domain, int size) static
Definition at line 3754 of file object_primitive.c.
References pr_type::disksize, NULL, or_advance(), and or_get_timestamptz().
Referenced by pr_type::get_cmpval_function().
static void mr_data_readmem_utime (OR_BUF * buf, void * mem, TP_DOMAIN * domain, int size) static
Definition at line 3504 of file object_primitive.c.
References pr_type::disksize, NULL, or_advance(), and or_get_utime().
Referenced by pr_type::get_cmpval_function().
static void mr_data_readmem_varbit (OR_BUF * buf, void * memptr, TP_DOMAIN * domain, int size) static
Definition at line 15187 of file object_primitive.c.
References BITS_TO_BYTES, db_private_alloc, db_private_free_and_init, NO_ERROR, NULL, or_abort(), or_advance(), or_get_align32(), or_get_data(), or_get_varbit_length(), or_buf::ptr, and rc.
Referenced by pr_type::get_cmpval_function().
static void mr_data_readmem_varnchar (OR_BUF * buf, void * memptr, TP_DOMAIN * domain, int size) static
Definition at line 13306 of file object_primitive.c.
References mr_data_readmem_string().
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_bigint (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 2814 of file object_primitive.c.
References db_make_bigint(), pr_type::disksize, db_value::need_clear, NO_ERROR, NULL, or_advance(), or_get_bigint(), and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_bit (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int disk_size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 14699 of file object_primitive.c.
References INT_ALIGNMENT, and mr_readval_bit_internal().
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_blob (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 6074 of file object_primitive.c.
References DB_TYPE_BLOB, and readval_elo_with_type().
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_char (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int disk_size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 11721 of file object_primitive.c.
References INT_ALIGNMENT, and mr_readval_char_internal().
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_clob (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 6081 of file object_primitive.c.
References DB_TYPE_CLOB, and readval_elo_with_type().
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_date (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 4790 of file object_primitive.c.
References db_value_put_encoded_date(), pr_type::disksize, db_value::need_clear, NO_ERROR, NULL, or_advance(), or_get_date(), and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_datetime (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 4029 of file object_primitive.c.
References db_make_datetime(), pr_type::disksize, db_value::need_clear, NO_ERROR, NULL, or_advance(), or_get_datetime(), and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_datetimeltz (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 4052 of file object_primitive.c.
References db_make_datetimeltz(), pr_type::disksize, NO_ERROR, NULL, or_advance(), or_get_datetime(), and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_datetimetz (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 4364 of file object_primitive.c.
References db_make_datetimetz(), pr_type::disksize, NO_ERROR, NULL, or_advance(), or_get_datetimetz(), and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_double (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 3179 of file object_primitive.c.
References db_make_double(), pr_type::disksize, db_value::need_clear, NO_ERROR, NULL, or_advance(), or_get_double(), and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_elo (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 6065 of file object_primitive.c.
References assert, and ER_FAILED.
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_enumeration (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 15860 of file object_primitive.c.
References pr_type::disksize, mr_setval_enumeration_internal(), NO_ERROR, NULL, or_advance(), or_get_short(), and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_error (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 6518 of file object_primitive.c.
References DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_make_error(), DB_TYPE_ERROR, db_value_domain_init(), and NO_ERROR.
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_float (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 2989 of file object_primitive.c.
References db_make_float(), pr_type::disksize, db_value::need_clear, NO_ERROR, NULL, or_advance(), or_get_float(), and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_int (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 2473 of file object_primitive.c.
References db_make_int(), pr_type::disksize, db_value::need_clear, NO_ERROR, NULL, or_advance(), or_get_int(), and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_json (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 16846 of file object_primitive.c.
References ASSERT_ERROR, db_json_deserialize(), db_make_json(), db_make_null(), NO_ERROR, NULL, and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_midxkey (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 7626 of file object_primitive.c.
References mr_index_readval_midxkey().
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_money (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 4607 of file object_primitive.c.
References db_monetary::amount, db_make_monetary(), pr_type::disksize, db_value::need_clear, NO_ERROR, NULL, or_advance(), or_get_monetary(), rc, and db_monetary::type.
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_nchar (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int disk_size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 12684 of file object_primitive.c.
References INT_ALIGNMENT, and mr_readval_nchar_internal().
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_null (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 2350 of file object_primitive.c.
References db_make_null(), db_value::need_clear, and NO_ERROR.
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_numeric (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 8600 of file object_primitive.c.
References db_make_numeric(), ER_FAILED, db_value::need_clear, NO_ERROR, NULL, or_advance(), OR_NUMERIC_SIZE, tp_domain::precision, or_buf::ptr, rc, and tp_domain::scale.
Referenced by pr_type::get_cmpval_function(), mr_data_cmpdisk_numeric(), and mr_index_readval_numeric().
static int mr_data_readval_object (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 5342 of file object_primitive.c.
References DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_get_object(), db_make_object(), db_make_oid(), db_on_server, DB_TYPE_OBJECT, DB_TYPE_OID, db_value_domain_init(), pr_type::disksize, ER_FAILED, NO_ERROR, NULL, OID_ISNULL, or_abort(), or_advance(), or_get_oid(), pr_Inhibit_oid_promotion, rc, and ws_mop().
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_oid (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 6672 of file object_primitive.c.
References DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_make_oid(), DB_TYPE_OID, db_value_domain_init(), pr_type::disksize, NO_ERROR, NULL, or_advance(), or_get_oid(), and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_ptr (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 6386 of file object_primitive.c.
References DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, DB_TYPE_POINTER, db_value_domain_init(), and NO_ERROR.
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_resultset (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 9916 of file object_primitive.c.
References db_make_resultset(), pr_type::disksize, db_value::need_clear, NO_ERROR, NULL, or_advance(), or_get_int(), and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_set (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 7194 of file object_primitive.c.
References DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_make_multiset(), db_make_sequence(), db_make_set(), DB_TYPE_MULTISET, DB_TYPE_SEQUENCE, DB_TYPE_SET, db_value_domain_init(), db_set::disk_domain, db_set::disk_set, db_set::disk_size, ER_FAILED, db_set::need_clear, NO_ERROR, NULL, or_abort(), or_advance(), or_disk_set_size(), or_get_set(), or_get_set_header(), tp_domain::precision, or_buf::ptr, rc, tp_domain::scale, set_get_type(), set_make_reference(), setobj_free(), setobj_get_reference(), pr_type::size, and TP_DOMAIN_TYPE.
Referenced by pr_type::get_cmpval_function(), and mr_data_readval_vobj().
static int mr_data_readval_short (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 2642 of file object_primitive.c.
References db_make_short(), pr_type::disksize, db_value::need_clear, NO_ERROR, NULL, or_advance(), or_get_short(), and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_string (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 10455 of file object_primitive.c.
References INT_ALIGNMENT, and mr_readval_string_internal().
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_sub (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 6260 of file object_primitive.c.
References NO_ERROR.
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_time (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 3358 of file object_primitive.c.
References db_value_put_encoded_time(), pr_type::disksize, db_value::need_clear, NO_ERROR, NULL, or_advance(), or_get_time(), and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_timestampltz (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 3592 of file object_primitive.c.
References db_make_timestampltz(), pr_type::disksize, db_value::need_clear, NO_ERROR, NULL, or_advance(), or_get_utime(), and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_timestamptz (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 3798 of file object_primitive.c.
References db_make_timestamptz(), pr_type::disksize, NO_ERROR, NULL, or_advance(), or_get_timestamptz(), and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_utime (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 3569 of file object_primitive.c.
References db_make_utime, pr_type::disksize, db_value::need_clear, NO_ERROR, NULL, or_advance(), or_get_utime(), and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_varbit (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 15373 of file object_primitive.c.
References INT_ALIGNMENT, and mr_readval_varbit_internal().
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_variable (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 6173 of file object_primitive.c.
References NO_ERROR.
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_varnchar (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 13446 of file object_primitive.c.
References INT_ALIGNMENT, and mr_readval_varnchar_internal().
Referenced by pr_type::get_cmpval_function().
static int mr_data_readval_vobj (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 8316 of file object_primitive.c.
References DB_TYPE_VOBJ, db_value_alter_type(), ER_FAILED, mr_data_readval_set(), NO_ERROR, and tp_Sequence_domain.
Referenced by pr_type::get_cmpval_function().
static void mr_data_writemem_bigint (OR_BUF * buf, void * mem, TP_DOMAIN * domain) static
Definition at line 2767 of file object_primitive.c.
References or_put_bigint().
Referenced by pr_type::get_cmpval_function().
static void mr_data_writemem_bit (OR_BUF * buf, void * mem, TP_DOMAIN * domain) static
Definition at line 14406 of file object_primitive.c.
References assert, INTL_CODESET_RAW_BITS, or_put_data(), tp_domain::precision, STR_SIZE, and TP_DOMAIN_CODESET.
Referenced by pr_type::get_cmpval_function().
static void mr_data_writemem_char (OR_BUF * buf, void * mem, TP_DOMAIN * domain) static
Definition at line 11417 of file object_primitive.c.
References assert, IS_FLOATING_PRECISION, or_put_data(), tp_domain::precision, STR_SIZE, and TP_DOMAIN_CODESET.
Referenced by pr_type::get_cmpval_function().
static void mr_data_writemem_date (OR_BUF * buf, void * mem, TP_DOMAIN * domain) static
Definition at line 4742 of file object_primitive.c.
References or_put_date().
Referenced by pr_type::get_cmpval_function().
static void mr_data_writemem_datetime (OR_BUF * buf, void * mem, TP_DOMAIN * domain) static
Definition at line 4004 of file object_primitive.c.
References or_put_datetime().
Referenced by pr_type::get_cmpval_function().
static void mr_data_writemem_datetimetz (OR_BUF * buf, void * mem, TP_DOMAIN * domain) static
Definition at line 4339 of file object_primitive.c.
References or_put_datetimetz().
Referenced by pr_type::get_cmpval_function().
static void mr_data_writemem_double (OR_BUF * buf, void * mem, TP_DOMAIN * domain) static
Definition at line 3127 of file object_primitive.c.
References OR_MOVE_DOUBLE, and or_put_double().
Referenced by pr_type::get_cmpval_function().
static void mr_data_writemem_elo (OR_BUF * buf, void * memptr, TP_DOMAIN * domain) static
Definition at line 5861 of file object_primitive.c.
References assert, assert_release, ELO_NULL, db_elo::locator, db_elo::meta_data, NULL, OR_INT_SIZE, or_packed_string_length(), or_put_bigint(), or_put_int(), or_put_string_aligned(), db_elo::size, and db_elo::type.
Referenced by pr_type::get_cmpval_function(), and mr_data_writeval_elo().
static void mr_data_writemem_enumeration (OR_BUF * buf, void * memptr, TP_DOMAIN * domain) static
Definition at line 15767 of file object_primitive.c.
References or_put_short().
Referenced by pr_type::get_cmpval_function().
static void mr_data_writemem_error (OR_BUF * buf, void * memptr, TP_DOMAIN * domain) static
Definition at line 6499 of file object_primitive.c.
Referenced by pr_type::get_cmpval_function().
static void mr_data_writemem_float (OR_BUF * buf, void * mem, TP_DOMAIN * domain) static
Definition at line 2942 of file object_primitive.c.
References or_put_float().
Referenced by pr_type::get_cmpval_function().
static void mr_data_writemem_int (OR_BUF * buf, void * mem, TP_DOMAIN * domain) static
Definition at line 2426 of file object_primitive.c.
References or_put_int().
Referenced by pr_type::get_cmpval_function().
static void mr_data_writemem_json (OR_BUF * buf, void * memptr, TP_DOMAIN * domain) static
Definition at line 16670 of file object_primitive.c.
References ASSERT_ERROR, db_json_serialize(), db_json::document, NO_ERROR, NULL, and rc.
Referenced by pr_type::get_cmpval_function().
static void mr_data_writemem_money (OR_BUF * buf, void * mem, TP_DOMAIN * domain) static
Definition at line 4558 of file object_primitive.c.
References or_put_monetary().
Referenced by pr_type::get_cmpval_function().
static void mr_data_writemem_nchar (OR_BUF * buf, void * mem, TP_DOMAIN * domain) static
Definition at line 12324 of file object_primitive.c.
References or_put_data(), tp_domain::precision, STR_SIZE, and TP_DOMAIN_CODESET.
Referenced by pr_type::get_cmpval_function().
static void mr_data_writemem_null (OR_BUF * buf, void * memptr, TP_DOMAIN * domain) static
Definition at line 2289 of file object_primitive.c.
Referenced by pr_type::get_cmpval_function().
static void mr_data_writemem_numeric (OR_BUF * buf, void * mem, TP_DOMAIN * domain) static
Definition at line 8435 of file object_primitive.c.
References OR_NUMERIC_SIZE, or_put_data(), and tp_domain::precision.
Referenced by pr_type::get_cmpval_function().
static void mr_data_writemem_object (OR_BUF * buf, void * memptr, TP_DOMAIN * domain) static
Definition at line 5161 of file object_primitive.c.
References ARG_FILE_LINE, ER_MR_TEMP_OID_WITHOUT_MOP, er_set(), ER_WARNING_SEVERITY, NULL, ws_memoid::oid, OID_ISTEMP, oid_Null_oid, or_put_oid(), ws_memoid::pointer, tf_need_permanent_oid(), WS_IS_DELETED, and WS_OID.
Referenced by pr_type::get_cmpval_function().
static void mr_data_writemem_oid (OR_BUF * buf, void * memptr, TP_DOMAIN * domain) static
Definition at line 6642 of file object_primitive.c.
References or_put_oid().
Referenced by pr_type::get_cmpval_function().
static void mr_data_writemem_ptr (OR_BUF * buf, void * memptr, TP_DOMAIN * domain) static
Definition at line 6367 of file object_primitive.c.
Referenced by pr_type::get_cmpval_function().
static void mr_data_writemem_resultset (OR_BUF * buf, void * mem, TP_DOMAIN * domain) static
Definition at line 9869 of file object_primitive.c.
References or_put_int().
Referenced by pr_type::get_cmpval_function().
static void mr_data_writemem_set (OR_BUF * buf, void * memptr, TP_DOMAIN * domain) static
Definition at line 7072 of file object_primitive.c.
References NULL, and or_put_set().
Referenced by pr_type::get_cmpval_function().
static void mr_data_writemem_short (OR_BUF * buf, void * memptr, TP_DOMAIN * domain) static
Definition at line 2593 of file object_primitive.c.
References or_put_short().
Referenced by pr_type::get_cmpval_function().
static void mr_data_writemem_string (OR_BUF * buf, void * memptr, TP_DOMAIN * domain) static
Definition at line 10188 of file object_primitive.c.
References NULL, and or_packed_put_varchar().
Referenced by pr_type::get_cmpval_function().
static void mr_data_writemem_sub (OR_BUF * buf, void * mem, TP_DOMAIN * domain) static
Definition at line 6244 of file object_primitive.c.
Referenced by pr_type::get_cmpval_function().
static void mr_data_writemem_time (OR_BUF * buf, void * mem, TP_DOMAIN * domain) static
Definition at line 3308 of file object_primitive.c.
References or_put_time().
Referenced by pr_type::get_cmpval_function().
static void mr_data_writemem_timestamptz (OR_BUF * buf, void * mem, TP_DOMAIN * domain) static
Definition at line 3748 of file object_primitive.c.
References or_put_timestamptz().
Referenced by pr_type::get_cmpval_function().
static void mr_data_writemem_utime (OR_BUF * buf, void * mem, TP_DOMAIN * domain) static
Definition at line 3498 of file object_primitive.c.
References or_put_utime().
Referenced by pr_type::get_cmpval_function().
static void mr_data_writemem_varbit (OR_BUF * buf, void * memptr, TP_DOMAIN * domain) static
Definition at line 15162 of file object_primitive.c.
References NULL, and or_packed_put_varbit().
Referenced by pr_type::get_cmpval_function().
static void mr_data_writemem_varnchar (OR_BUF * buf, void * memptr, TP_DOMAIN * domain) static
Definition at line 13281 of file object_primitive.c.
References NULL, and or_packed_put_varchar().
Referenced by pr_type::get_cmpval_function().
static int mr_data_writeval_bigint (OR_BUF * buf, DB_VALUE * value) static
Definition at line 2808 of file object_primitive.c.
References db_get_bigint(), and or_put_bigint().
Referenced by pr_type::get_cmpval_function().
static int mr_data_writeval_bit (OR_BUF * buf, DB_VALUE * value) static
Definition at line 14610 of file object_primitive.c.
References INT_ALIGNMENT, and mr_writeval_bit_internal().
Referenced by pr_type::get_cmpval_function().
static int mr_data_writeval_char (OR_BUF * buf, DB_VALUE * value) static
Definition at line 11622 of file object_primitive.c.
References INT_ALIGNMENT, and mr_writeval_char_internal().
Referenced by pr_type::get_cmpval_function().
static int mr_data_writeval_date (OR_BUF * buf, DB_VALUE * value) static
Definition at line 4784 of file object_primitive.c.
References db_get_date(), and or_put_date().
Referenced by pr_type::get_cmpval_function().
static int mr_data_writeval_datetime (OR_BUF * buf, DB_VALUE * value) static
Definition at line 4023 of file object_primitive.c.
References db_get_datetime(), and or_put_datetime().
Referenced by pr_type::get_cmpval_function().
static int mr_data_writeval_datetimetz (OR_BUF * buf, DB_VALUE * value) static
Definition at line 4358 of file object_primitive.c.
References db_get_datetimetz(), and or_put_datetimetz().
Referenced by pr_type::get_cmpval_function().
static int mr_data_writeval_double (OR_BUF * buf, DB_VALUE * value) static
Definition at line 3173 of file object_primitive.c.
References db_get_double(), and or_put_double().
Referenced by pr_type::get_cmpval_function().
static int mr_data_writeval_elo (OR_BUF * buf, DB_VALUE * value) static
Definition at line 6014 of file object_primitive.c.
References db_get_elo(), mr_data_writemem_elo(), NO_ERROR, and NULL.
Referenced by pr_type::get_cmpval_function().
static int mr_data_writeval_enumeration (OR_BUF * buf, DB_VALUE * value) static
Definition at line 15882 of file object_primitive.c.
References db_get_enum_short(), and or_put_short().
Referenced by pr_type::get_cmpval_function().
static int mr_data_writeval_error (OR_BUF * buf, DB_VALUE * value) static
Definition at line 6512 of file object_primitive.c.
References NO_ERROR.
Referenced by pr_type::get_cmpval_function().
static int mr_data_writeval_float (OR_BUF * buf, DB_VALUE * value) static
Definition at line 2983 of file object_primitive.c.
References db_get_float(), and or_put_float().
Referenced by pr_type::get_cmpval_function().
static int mr_data_writeval_int (OR_BUF * buf, DB_VALUE * value) static
Definition at line 2467 of file object_primitive.c.
References db_get_int(), and or_put_int().
Referenced by pr_type::get_cmpval_function().
static int mr_data_writeval_json (OR_BUF * buf, DB_VALUE * value) static
Definition at line 16811 of file object_primitive.c.
References assert, ASSERT_ERROR, db_value::data, db_get_json_document(), DB_IS_NULL, db_json_serialize(), db_json::document, or_buf::endptr, ER_FAILED, or_buf::error_abort, db_data::json, mr_data_lengthval_json(), NO_ERROR, NULL, or_overflow(), or_buf::ptr, and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_data_writeval_midxkey (OR_BUF * buf, DB_VALUE * value) static
Definition at line 7603 of file object_primitive.c.
References mr_index_writeval_midxkey().
Referenced by pr_type::get_cmpval_function().
static int mr_data_writeval_money (OR_BUF * buf, DB_VALUE * value) static
Definition at line 4601 of file object_primitive.c.
References db_get_monetary(), and or_put_monetary().
Referenced by pr_type::get_cmpval_function().
static int mr_data_writeval_nchar (OR_BUF * buf, DB_VALUE * value) static
Definition at line 12545 of file object_primitive.c.
References INT_ALIGNMENT, and mr_writeval_nchar_internal().
Referenced by pr_type::get_cmpval_function().
static int mr_data_writeval_null (OR_BUF * buf, DB_VALUE * value) static
Definition at line 2333 of file object_primitive.c.
References NO_ERROR.
Referenced by pr_type::get_cmpval_function().
static int mr_data_writeval_numeric (OR_BUF * buf, DB_VALUE * value) static
Definition at line 8573 of file object_primitive.c.
References db_get_numeric(), db_value_precision(), NO_ERROR, NULL, OR_NUMERIC_SIZE, or_put_data(), and rc.
Referenced by pr_type::get_cmpval_function(), and mr_index_writeval_numeric().
static int mr_data_writeval_object (OR_BUF * buf, DB_VALUE * value) static
Definition at line 5252 of file object_primitive.c.
References db_get_object(), db_get_oid(), db_on_server, DB_TYPE_OBJECT, DB_TYPE_OID, DB_VALUE_TYPE, ER_FAILED, error(), mr_data_writeval_set(), NO_ERROR, NULL, OID_ISTEMP, oid_Null_oid, or_put_oid(), pr_clear_value(), pr_Inhibit_oid_promotion, rc, tf_need_permanent_oid(), vid_object_to_vobj(), WS_IS_DELETED, WS_ISVID, and WS_OID.
Referenced by pr_type::get_cmpval_function().
static int mr_data_writeval_oid (OR_BUF * buf, DB_VALUE * value) static
Definition at line 6666 of file object_primitive.c.
References db_get_oid(), and or_put_oid().
Referenced by pr_type::get_cmpval_function().
static int mr_data_writeval_ptr (OR_BUF * buf, DB_VALUE * value) static
Definition at line 6380 of file object_primitive.c.
References NO_ERROR.
Referenced by pr_type::get_cmpval_function().
static int mr_data_writeval_resultset (OR_BUF * buf, DB_VALUE * value) static
Definition at line 9910 of file object_primitive.c.
References db_get_resultset(), and or_put_int().
Referenced by pr_type::get_cmpval_function().
static int mr_data_writeval_set (OR_BUF * buf, DB_VALUE * value) static
Definition at line 7084 of file object_primitive.c.
References db_get_set(), db_set::disk_set, db_set::disk_size, or_buf::endptr, NO_ERROR, NULL, or_advance(), or_overflow(), or_packed_set_length(), or_put_set(), db_set::owner, or_buf::ptr, rc, set_get_setobj(), pr_type::size, and ws_pin().
Referenced by pr_type::get_cmpval_function(), and mr_data_writeval_object().
static int mr_data_writeval_short (OR_BUF * buf, DB_VALUE * value) static
Definition at line 2636 of file object_primitive.c.
References db_get_short(), and or_put_short().
Referenced by pr_type::get_cmpval_function().
static int mr_data_writeval_string (OR_BUF * buf, DB_VALUE * value) static
Definition at line 10449 of file object_primitive.c.
References INT_ALIGNMENT, and mr_writeval_string_internal().
Referenced by pr_type::get_cmpval_function().
static int mr_data_writeval_sub (OR_BUF * buf, DB_VALUE * value) static
Definition at line 6254 of file object_primitive.c.
References NO_ERROR.
Referenced by pr_type::get_cmpval_function().
static int mr_data_writeval_time (OR_BUF * buf, DB_VALUE * value) static
Definition at line 3352 of file object_primitive.c.
References db_get_time(), and or_put_time().
Referenced by pr_type::get_cmpval_function().
static int mr_data_writeval_timestamptz (OR_BUF * buf, DB_VALUE * value) static
Definition at line 3792 of file object_primitive.c.
References db_get_timestamptz(), and or_put_timestamptz().
Referenced by pr_type::get_cmpval_function().
static int mr_data_writeval_utime (OR_BUF * buf, DB_VALUE * value) static
Definition at line 3563 of file object_primitive.c.
References db_get_timestamp(), and or_put_utime().
Referenced by pr_type::get_cmpval_function().
static int mr_data_writeval_varbit (OR_BUF * buf, DB_VALUE * value) static
Definition at line 15367 of file object_primitive.c.
References INT_ALIGNMENT, and mr_writeval_varbit_internal().
Referenced by pr_type::get_cmpval_function().
static int mr_data_writeval_variable (OR_BUF * buf, DB_VALUE * value) static
Definition at line 6167 of file object_primitive.c.
References NO_ERROR.
Referenced by pr_type::get_cmpval_function().
static int mr_data_writeval_varnchar (OR_BUF * buf, DB_VALUE * value) static
Definition at line 13440 of file object_primitive.c.
References INT_ALIGNMENT, and mr_writeval_varnchar_internal().
Referenced by pr_type::get_cmpval_function().
static void mr_freemem_bit (void * memptr) static
Definition at line 14469 of file object_primitive.c.
Referenced by pr_type::get_cmpval_function().
static void mr_freemem_char (void * memptr) static
Definition at line 11485 of file object_primitive.c.
Referenced by pr_type::get_cmpval_function().
static void mr_freemem_elo (void * memptr) static
Definition at line 6088 of file object_primitive.c.
References db_private_free_and_init, elo_free_structure(), and NULL.
Referenced by pr_type::get_cmpval_function(), and mr_setmem_elo().
static void mr_freemem_json (void * memptr) static
Definition at line 16728 of file object_primitive.c.
References db_json_delete_doc(), db_private_free, db_json::document, NULL, and db_json::schema_raw.
Referenced by pr_type::get_cmpval_function(), and mr_setmem_json().
static void mr_freemem_nchar (void * memptr) static
Definition at line 12388 of file object_primitive.c.
Referenced by pr_type::get_cmpval_function().
static void mr_freemem_set (void * memptr) static
Definition at line 7343 of file object_primitive.c.
References NULL, and setobj_free().
Referenced by pr_type::get_cmpval_function().
static void mr_freemem_string (void * memptr) static
Definition at line 10309 of file object_primitive.c.
References db_private_free_and_init, and NULL.
Referenced by pr_type::get_cmpval_function().
static void mr_freemem_varbit (void * memptr) static
Definition at line 15270 of file object_primitive.c.
References db_private_free_and_init, and NULL.
Referenced by pr_type::get_cmpval_function().
static void mr_freemem_varnchar (void * memptr) static
Definition at line 13312 of file object_primitive.c.
References db_private_free_and_init, and NULL.
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_bigint (void * mem, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 2761 of file object_primitive.c.
References db_make_bigint().
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_bit (void * mem, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 14363 of file object_primitive.c.
References assert, db_make_bit(), db_private_alloc, er_errid(), INTL_CODESET_RAW_BITS, db_value::need_clear, NO_ERROR, NULL, tp_domain::precision, STR_SIZE, and TP_DOMAIN_CODESET.
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_blob (void * memptr, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 5753 of file object_primitive.c.
References DB_TYPE_BLOB, and getmem_elo_with_type().
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_char (void * mem, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 11340 of file object_primitive.c.
References assert, db_make_char(), db_private_alloc, er_errid(), ER_FAILED, intl_char_size(), IS_FLOATING_PRECISION, db_value::need_clear, NO_ERROR, NULL, tp_domain::precision, STR_SIZE, TP_DOMAIN_CODESET, TP_DOMAIN_COLL_NORMAL, TP_DOMAIN_COLLATION, and TP_DOMAIN_COLLATION_FLAG.
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_clob (void * memptr, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 5759 of file object_primitive.c.
References DB_TYPE_CLOB, and getmem_elo_with_type().
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_date (void * mem, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 4736 of file object_primitive.c.
References db_value_put_encoded_date().
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_datetime (void * mem, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 3960 of file object_primitive.c.
References db_make_datetime().
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_datetimeltz (void * mem, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 3966 of file object_primitive.c.
References db_make_datetimeltz().
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_datetimetz (void * mem, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 4317 of file object_primitive.c.
References db_make_datetimetz().
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_double (void * mem, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 3118 of file object_primitive.c.
References db_make_double(), and OR_MOVE_DOUBLE.
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_elo (void * memptr, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 5745 of file object_primitive.c.
References assert, and ER_FAILED.
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_enumeration (void * mem, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 15717 of file object_primitive.c.
References mr_setval_enumeration_internal(), and NULL.
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_error (void * memptr, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 6455 of file object_primitive.c.
References db_make_error().
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_float (void * mem, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 2936 of file object_primitive.c.
References db_make_float().
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_int (void * mem, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 2420 of file object_primitive.c.
References db_make_int().
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_json (void * memptr, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 16598 of file object_primitive.c.
References db_get_deep_copy_of_json(), db_get_json_schema, db_init_db_json_pointers(), db_make_json(), db_make_null(), DB_TYPE_JSON, db_value_domain_init(), db_json::document, error(), db_value::need_clear, NO_ERROR, NULL, tp_domain::precision, and db_json::schema_raw.
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_money (void * memptr, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 4545 of file object_primitive.c.
References db_monetary::amount, db_make_monetary(), error(), db_value::need_clear, NO_ERROR, OR_MOVE_DOUBLE, and db_monetary::type.
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_multiset (void * memptr, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 7402 of file object_primitive.c.
References assert, db_make_multiset(), er_errid(), error(), NO_ERROR, NULL, and setobj_get_reference().
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_nchar (void * mem, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 12248 of file object_primitive.c.
References assert, db_make_nchar(), db_private_alloc, er_errid(), ER_FAILED, intl_char_size(), db_value::need_clear, NO_ERROR, NULL, tp_domain::precision, STR_SIZE, TP_DOMAIN_CODESET, TP_DOMAIN_COLL_NORMAL, TP_DOMAIN_COLLATION, and TP_DOMAIN_COLLATION_FLAG.
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_null (void * memptr, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 2275 of file object_primitive.c.
References db_make_null(), and NO_ERROR.
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_numeric (void * mem, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 8417 of file object_primitive.c.
References db_make_numeric(), error(), db_value::need_clear, NO_ERROR, NULL, tp_domain::precision, and tp_domain::scale.
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_object (void * memptr, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 5008 of file object_primitive.c.
References assert, db_make_object(), er_errid(), error(), NO_ERROR, NULL, ws_memoid::oid, OID_ISNULL, ws_memoid::pointer, and ws_mop().
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_oid (void * memptr, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 6613 of file object_primitive.c.
References db_make_oid(), db_identifier::pageid, db_identifier::slotid, and db_identifier::volid.
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_ptr (void * memptr, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 6323 of file object_primitive.c.
References db_make_pointer().
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_resultset (void * mem, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 9863 of file object_primitive.c.
References db_make_resultset().
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_sequence (void * memptr, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 7451 of file object_primitive.c.
References assert, db_make_sequence(), er_errid(), error(), NO_ERROR, NULL, and setobj_get_reference().
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_set (void * memptr, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 6873 of file object_primitive.c.
References assert, db_make_set(), er_errid(), error(), NO_ERROR, NULL, and setobj_get_reference().
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_short (void * mem, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 2587 of file object_primitive.c.
References db_make_short().
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_string (void * memptr, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 10047 of file object_primitive.c.
References assert, db_make_varchar(), db_private_alloc, DB_TYPE_VARCHAR, db_value_domain_init(), er_errid(), ER_FAILED, error(), db_value::need_clear, NO_ERROR, NULL, tp_domain::precision, TP_DOMAIN_CODESET, TP_DOMAIN_COLL_NORMAL, TP_DOMAIN_COLLATION, and TP_DOMAIN_COLLATION_FLAG.
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_sub (void * mem, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 6220 of file object_primitive.c.
References NO_ERROR.
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_time (void * mem, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 3300 of file object_primitive.c.
References db_value_put_encoded_time(), db_value::need_clear, and NO_ERROR.
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_timestampltz (void * mem, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 3488 of file object_primitive.c.
References db_make_timestampltz(), error(), and db_value::need_clear.
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_timestamptz (void * mem, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 3739 of file object_primitive.c.
References db_make_timestamptz(), and error().
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_utime (void * mem, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 3478 of file object_primitive.c.
References db_make_utime, error(), and db_value::need_clear.
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_varbit (void * memptr, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 15070 of file object_primitive.c.
References assert, BITS_TO_BYTES, db_make_varbit(), db_private_alloc, DB_TYPE_VARBIT, db_value_domain_init(), er_errid(), error(), db_value::need_clear, NO_ERROR, NULL, and tp_domain::precision.
Referenced by pr_type::get_cmpval_function().
static int mr_getmem_varnchar (void * memptr, TP_DOMAIN * domain, DB_VALUE * value, bool copy) static
Definition at line 13174 of file object_primitive.c.
References assert, db_make_varnchar(), db_private_alloc, DB_TYPE_VARNCHAR, db_value_domain_init(), er_errid(), ER_FAILED, error(), db_value::need_clear, NO_ERROR, NULL, tp_domain::precision, TP_DOMAIN_CODESET, TP_DOMAIN_COLL_NORMAL, TP_DOMAIN_COLLATION, and TP_DOMAIN_COLLATION_FLAG.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_bigint (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 2871 of file object_primitive.c.
References assert, COPYMEM, MR_CMP, and NULL.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_bit (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 14872 of file object_primitive.c.
References assert, CHAR_ALIGNMENT, mr_cmpdisk_bit_internal(), and NULL.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_char (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 11914 of file object_primitive.c.
References assert, CHAR_ALIGNMENT, mr_cmpdisk_char_internal(), and NULL.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_date (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 4847 of file object_primitive.c.
References assert, COPYMEM, d1, MR_CMP, and NULL.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_datetime (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 4152 of file object_primitive.c.
References assert, COPYMEM, db_datetime::date, DB_EQ, DB_GT, DB_LT, NULL, OR_DATETIME_DATE, OR_DATETIME_TIME, and db_datetime::time.
Referenced by pr_type::get_cmpval_function(), and mr_index_cmpdisk_datetimetz().
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_datetimetz (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 4441 of file object_primitive.c.
References mr_index_cmpdisk_datetime().
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_double (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 3237 of file object_primitive.c.
References assert, COPYMEM, d1, MR_CMP, and NULL.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_enumeration (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 15918 of file object_primitive.c.
References assert, COPYMEM, MR_CMP, and NULL.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_float (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 3046 of file object_primitive.c.
References assert, COPYMEM, MR_CMP, and NULL.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_int (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 2527 of file object_primitive.c.
References assert, COPYMEM, MR_CMP, and NULL.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_midxkey (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 8143 of file object_primitive.c.
References assert, db_midxkey::buf, DB_EQ, DB_GT, DB_LT, DB_UNK, db_midxkey::domain, tp_domain::is_desc, db_midxkey::ncolumns, tp_domain::next, NULL, pr_midxkey_compare(), tp_domain::setdomain, and db_midxkey::size.
Referenced by pr_type::get_cmpval_function(), and mr_data_cmpdisk_midxkey().
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_money (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 4676 of file object_primitive.c.
References db_monetary::amount, assert, COPYMEM, pr_type::disksize, MR_CMP, and NULL.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_nchar (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 12896 of file object_primitive.c.
References assert, CHAR_ALIGNMENT, mr_cmpdisk_nchar_internal(), and NULL.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_numeric (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 8646 of file object_primitive.c.
References assert, mr_data_cmpdisk_numeric(), and NULL.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_object (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 5401 of file object_primitive.c.
References assert, mr_index_cmpdisk_oid(), and NULL.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_oid (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 6749 of file object_primitive.c.
References assert, COPYMEM, MR_CMP_RETURN_CODE, NULL, oid_compare(), OR_OID_PAGEID, OR_OID_SLOTID, OR_OID_VOLID, db_identifier::pageid, db_identifier::slotid, and db_identifier::volid.
Referenced by pr_type::get_cmpval_function(), and mr_index_cmpdisk_object().
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_short (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 2700 of file object_primitive.c.
References assert, COPYMEM, MR_CMP, and NULL.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_string (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 10915 of file object_primitive.c.
References assert, mr_data_cmpdisk_string(), and NULL.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_time (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 3415 of file object_primitive.c.
References assert, COPYMEM, MR_CMP, and NULL.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_timestamptz (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 3860 of file object_primitive.c.
References assert, COPYMEM, MR_CMP, and NULL.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_utime (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 3670 of file object_primitive.c.
References assert, COPYMEM, MR_CMP, and NULL.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_varbit (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 15580 of file object_primitive.c.
References assert, mr_data_cmpdisk_varbit(), and NULL.
Referenced by pr_type::get_cmpval_function().
static DB_VALUE_COMPARE_RESULT mr_index_cmpdisk_varnchar (void * mem1, void * mem2, TP_DOMAIN * domain, int do_coercion, int total_order, int * start_colp) static
Definition at line 13983 of file object_primitive.c.
References assert, mr_data_cmpdisk_varnchar(), and NULL.
Referenced by pr_type::get_cmpval_function().
static int mr_index_lengthmem_bit (void * memptr, TP_DOMAIN * domain) static
Definition at line 14531 of file object_primitive.c.
References assert, INTL_CODESET_RAW_BITS, IS_FLOATING_PRECISION, NULL, OR_INT_SIZE, tp_domain::precision, STR_SIZE, and TP_DOMAIN_CODESET.
Referenced by pr_type::get_cmpval_function().
static int mr_index_lengthmem_char (void * memptr, TP_DOMAIN * domain) static
Definition at line 11397 of file object_primitive.c.
References assert, IS_FLOATING_PRECISION, NULL, OR_INT_SIZE, tp_domain::precision, STR_SIZE, and TP_DOMAIN_CODESET.
Referenced by pr_type::get_cmpval_function().
static int mr_index_lengthmem_midxkey (void * memptr, TP_DOMAIN * domain) static
Definition at line 8204 of file object_primitive.c.
References assert, CAST_BUFLEN, i, tp_domain::next, OR_MULTI_ATT_IS_UNBOUND, OR_MULTI_BOUND_BIT_BYTES, pr_midxkey_element_disk_size(), tp_domain::precision, and tp_domain::setdomain.
Referenced by pr_type::get_cmpval_function(), mr_data_lengthmem_midxkey(), and mr_index_readval_midxkey().
static int mr_index_lengthmem_nchar (void * memptr, TP_DOMAIN * domain) static
Definition at line 12304 of file object_primitive.c.
References assert, IS_FLOATING_PRECISION, NULL, OR_INT_SIZE, tp_domain::precision, STR_SIZE, and TP_DOMAIN_CODESET.
Referenced by pr_type::get_cmpval_function().
static int mr_index_lengthmem_numeric (void * mem, TP_DOMAIN * domain) static
Definition at line 8474 of file object_primitive.c.
References mr_data_lengthmem_numeric().
Referenced by pr_type::get_cmpval_function().
static int mr_index_lengthmem_string (void * memptr, TP_DOMAIN * domain) static
Definition at line 10148 of file object_primitive.c.
References assert, NO_ERROR, OR_GET_BYTE, or_get_varchar_compression_lengths(), or_init(), OR_MINIMUM_STRING_LENGTH_FOR_COMPRESSION, or_varchar_length(), PRIM_TEMPORARY_DISK_SIZE, and rc.
Referenced by pr_type::get_cmpval_function(), and mr_index_lengthmem_varnchar().
static int mr_index_lengthmem_varbit (void * memptr, TP_DOMAIN * domain) static
Definition at line 15148 of file object_primitive.c.
References NO_ERROR, or_get_varbit_length(), or_init(), or_varbit_length(), and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_index_lengthmem_varnchar (void * memptr, TP_DOMAIN * domain) static
Definition at line 13275 of file object_primitive.c.
References mr_index_lengthmem_string().
Referenced by pr_type::get_cmpval_function().
static int mr_index_lengthval_bit (DB_VALUE * value) static
Definition at line 14554 of file object_primitive.c.
References mr_data_lengthval_bit().
Referenced by pr_type::get_cmpval_function().
static int mr_index_lengthval_char (DB_VALUE * value) static
Definition at line 11559 of file object_primitive.c.
References mr_data_lengthval_char().
Referenced by pr_type::get_cmpval_function().
static int mr_index_lengthval_midxkey (DB_VALUE * value) static
Definition at line 8278 of file object_primitive.c.
References db_value::data, DB_IS_NULL, db_data::midxkey, and db_midxkey::size.
Referenced by pr_type::get_cmpval_function(), and mr_data_lengthval_midxkey().
static int mr_index_lengthval_nchar (DB_VALUE * value) static
Definition at line 12459 of file object_primitive.c.
References mr_data_lengthval_nchar().
Referenced by pr_type::get_cmpval_function().
static int mr_index_lengthval_numeric (DB_VALUE * value) static
Definition at line 8539 of file object_primitive.c.
References mr_data_lengthval_numeric().
Referenced by pr_type::get_cmpval_function().
static int mr_index_lengthval_object (DB_VALUE * value) static
Definition at line 5104 of file object_primitive.c.
References pr_type::disksize.
static int mr_index_lengthval_string (DB_VALUE * value) static
Definition at line 10424 of file object_primitive.c.
References CHAR_ALIGNMENT, and mr_lengthval_string_internal().
Referenced by pr_type::get_cmpval_function().
static int mr_index_lengthval_varbit (DB_VALUE * value) static
Definition at line 15342 of file object_primitive.c.
References CHAR_ALIGNMENT, and mr_lengthval_varbit_internal().
Referenced by pr_type::get_cmpval_function().
static int mr_index_lengthval_varnchar (DB_VALUE * value) static
Definition at line 13415 of file object_primitive.c.
References CHAR_ALIGNMENT, and mr_lengthval_varnchar_internal().
Referenced by pr_type::get_cmpval_function().
static int mr_index_readval_bigint (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 2847 of file object_primitive.c.
References db_make_bigint(), pr_type::disksize, db_value::need_clear, NO_ERROR, NULL, or_advance(), or_get_data(), and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_index_readval_bit (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int disk_size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 14692 of file object_primitive.c.
References CHAR_ALIGNMENT, and mr_readval_bit_internal().
Referenced by pr_type::get_cmpval_function().
static int mr_index_readval_char (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int disk_size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 11714 of file object_primitive.c.
References CHAR_ALIGNMENT, and mr_readval_char_internal().
Referenced by pr_type::get_cmpval_function().
static int mr_index_readval_date (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 4823 of file object_primitive.c.
References db_value_put_encoded_date(), pr_type::disksize, db_value::need_clear, NO_ERROR, NULL, or_advance(), or_get_data(), and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_index_readval_datetime (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 4090 of file object_primitive.c.
References assert, db_datetime::date, db_make_datetime(), pr_type::disksize, db_value::need_clear, NO_ERROR, NULL, or_advance(), or_get_data(), rc, and db_datetime::time.
Referenced by pr_type::get_cmpval_function().
static int mr_index_readval_datetimeltz (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 4121 of file object_primitive.c.
References assert, db_datetime::date, db_make_datetimeltz(), pr_type::disksize, db_value::need_clear, NO_ERROR, NULL, or_advance(), or_get_data(), rc, and db_datetime::time.
Referenced by pr_type::get_cmpval_function().
static int mr_index_readval_datetimetz (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 4406 of file object_primitive.c.
References assert, db_datetime::date, db_datetimetz::datetime, db_make_datetimetz(), pr_type::disksize, db_value::need_clear, NO_ERROR, NULL, or_advance(), or_get_data(), rc, db_datetime::time, and db_datetimetz::tz_id.
Referenced by pr_type::get_cmpval_function().
static int mr_index_readval_double (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 3213 of file object_primitive.c.
References db_make_double(), pr_type::disksize, db_value::need_clear, NO_ERROR, NULL, or_advance(), or_get_data(), and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_index_readval_enumeration (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 15896 of file object_primitive.c.
References pr_type::disksize, mr_setval_enumeration_internal(), NO_ERROR, NULL, or_advance(), or_get_data(), and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_index_readval_float (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 3022 of file object_primitive.c.
References db_make_float(), pr_type::disksize, db_value::need_clear, NO_ERROR, NULL, or_advance(), or_get_data(), and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_index_readval_int (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 2505 of file object_primitive.c.
References db_make_int(), pr_type::disksize, i, db_value::need_clear, NO_ERROR, NULL, or_advance(), or_get_data(), and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_index_readval_midxkey (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 7633 of file object_primitive.c.
References assert, db_midxkey::buf, db_make_midxkey(), db_private_alloc, db_private_free_and_init, db_value_domain_init(), db_midxkey::domain, ER_FAILED, MIN_COLUMN, db_midxkey::min_max_val, mr_index_lengthmem_midxkey(), db_midxkey::ncolumns, db_value::need_clear, NO_ERROR, NULL, or_abort(), or_advance(), or_get_data(), special_column::position, tp_domain::precision, or_buf::ptr, rc, pr_type::size, db_midxkey::size, TP_DOMAIN_TYPE, TP_FLOATING_PRECISION_VALUE, and special_column::type.
Referenced by pr_type::get_cmpval_function(), and mr_data_readval_midxkey().
static int mr_index_readval_money (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 4647 of file object_primitive.c.
References db_monetary::amount, db_make_monetary(), pr_type::disksize, db_value::need_clear, NO_ERROR, NULL, or_advance(), or_get_data(), rc, and db_monetary::type.
Referenced by pr_type::get_cmpval_function().
static int mr_index_readval_nchar (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int disk_size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 12677 of file object_primitive.c.
References CHAR_ALIGNMENT, and mr_readval_nchar_internal().
Referenced by pr_type::get_cmpval_function().
static int mr_index_readval_numeric (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 8593 of file object_primitive.c.
References mr_data_readval_numeric().
Referenced by pr_type::get_cmpval_function().
static int mr_index_readval_object (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 5335 of file object_primitive.c.
References mr_index_readval_oid().
Referenced by pr_type::get_cmpval_function().
static int mr_index_readval_oid (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 6716 of file object_primitive.c.
References DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_make_oid(), DB_TYPE_OID, db_value_domain_init(), pr_type::disksize, NO_ERROR, NULL, or_advance(), or_get_data(), db_identifier::pageid, rc, db_identifier::slotid, and db_identifier::volid.
Referenced by pr_type::get_cmpval_function(), and mr_index_readval_object().
static int mr_index_readval_short (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 2676 of file object_primitive.c.
References db_make_short(), pr_type::disksize, db_value::need_clear, NO_ERROR, NULL, or_advance(), or_get_data(), and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_index_readval_string (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 10436 of file object_primitive.c.
References CHAR_ALIGNMENT, and mr_readval_string_internal().
Referenced by pr_type::get_cmpval_function().
static int mr_index_readval_time (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 3391 of file object_primitive.c.
References db_value_put_encoded_time(), pr_type::disksize, db_value::need_clear, NO_ERROR, NULL, or_advance(), or_get_data(), and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_index_readval_timestampltz (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 3646 of file object_primitive.c.
References db_make_timestampltz(), pr_type::disksize, db_value::need_clear, NO_ERROR, NULL, or_advance(), or_get_data(), and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_index_readval_timestamptz (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 3836 of file object_primitive.c.
References db_make_timestamptz(), pr_type::disksize, db_value::need_clear, NO_ERROR, NULL, or_advance(), or_get_data(), and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_index_readval_utime (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 3622 of file object_primitive.c.
References db_make_utime, pr_type::disksize, db_value::need_clear, NO_ERROR, NULL, or_advance(), or_get_data(), and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_index_readval_varbit (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 15354 of file object_primitive.c.
References CHAR_ALIGNMENT, and mr_readval_varbit_internal().
Referenced by pr_type::get_cmpval_function().
static int mr_index_readval_varnchar (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 13427 of file object_primitive.c.
References CHAR_ALIGNMENT, and mr_readval_varnchar_internal().
Referenced by pr_type::get_cmpval_function().
static int mr_index_writeval_bigint (OR_BUF * buf, DB_VALUE * value) static
Definition at line 2837 of file object_primitive.c.
References db_get_bigint(), pr_type::disksize, and or_put_data().
Referenced by pr_type::get_cmpval_function().
static int mr_index_writeval_bit (OR_BUF * buf, DB_VALUE * value) static
Definition at line 14601 of file object_primitive.c.
References CHAR_ALIGNMENT, and mr_writeval_bit_internal().
Referenced by pr_type::get_cmpval_function().
static int mr_index_writeval_char (OR_BUF * buf, DB_VALUE * value) static
Definition at line 11613 of file object_primitive.c.
References CHAR_ALIGNMENT, and mr_writeval_char_internal().
Referenced by pr_type::get_cmpval_function().
static int mr_index_writeval_date (OR_BUF * buf, DB_VALUE * value) static
Definition at line 4813 of file object_primitive.c.
References db_get_date(), pr_type::disksize, and or_put_data().
Referenced by pr_type::get_cmpval_function().
static int mr_index_writeval_datetime (OR_BUF * buf, DB_VALUE * value) static
Definition at line 4071 of file object_primitive.c.
References assert, db_datetime::date, db_get_datetime(), pr_type::disksize, NO_ERROR, or_put_data(), rc, and db_datetime::time.
Referenced by pr_type::get_cmpval_function().
static int mr_index_writeval_datetimetz (OR_BUF * buf, DB_VALUE * value) static
Definition at line 4383 of file object_primitive.c.
References assert, db_datetime::date, db_datetimetz::datetime, db_get_datetimetz(), pr_type::disksize, NO_ERROR, or_put_data(), rc, db_datetime::time, and db_datetimetz::tz_id.
Referenced by pr_type::get_cmpval_function().
static int mr_index_writeval_double (OR_BUF * buf, DB_VALUE * value) static
Definition at line 3203 of file object_primitive.c.
References db_get_double(), pr_type::disksize, and or_put_data().
Referenced by pr_type::get_cmpval_function().
static int mr_index_writeval_enumeration (OR_BUF * buf, DB_VALUE * value) static
Definition at line 15888 of file object_primitive.c.
References db_get_enum_short(), pr_type::disksize, and or_put_data().
Referenced by pr_type::get_cmpval_function().
static int mr_index_writeval_float (OR_BUF * buf, DB_VALUE * value) static
Definition at line 3012 of file object_primitive.c.
References db_get_float(), pr_type::disksize, and or_put_data().
Referenced by pr_type::get_cmpval_function().
static int mr_index_writeval_int (OR_BUF * buf, DB_VALUE * value) static
Definition at line 2495 of file object_primitive.c.
References db_get_int(), pr_type::disksize, i, and or_put_data().
Referenced by pr_type::get_cmpval_function().
static int mr_index_writeval_midxkey (OR_BUF * buf, DB_VALUE * value) static
Definition at line 7609 of file object_primitive.c.
References db_midxkey::buf, db_get_midxkey(), ER_FAILED, NULL, or_put_data(), rc, and db_midxkey::size.
Referenced by pr_type::get_cmpval_function(), and mr_data_writeval_midxkey().
static int mr_index_writeval_money (OR_BUF * buf, DB_VALUE * value) static
Definition at line 4630 of file object_primitive.c.
References db_monetary::amount, db_get_monetary(), pr_type::disksize, NO_ERROR, or_put_data(), rc, and db_monetary::type.
Referenced by pr_type::get_cmpval_function().
static int mr_index_writeval_nchar (OR_BUF * buf, DB_VALUE * value) static
Definition at line 12536 of file object_primitive.c.
References CHAR_ALIGNMENT, and mr_writeval_nchar_internal().
Referenced by pr_type::get_cmpval_function().
static int mr_index_writeval_numeric (OR_BUF * buf, DB_VALUE * value) static
Definition at line 8567 of file object_primitive.c.
References mr_data_writeval_numeric().
Referenced by pr_type::get_cmpval_function().
static int mr_index_writeval_object (OR_BUF * buf, DB_VALUE * value) static
Definition at line 5246 of file object_primitive.c.
References mr_index_writeval_oid().
Referenced by pr_type::get_cmpval_function().
static int mr_index_writeval_oid (OR_BUF * buf, DB_VALUE * value) static
Definition at line 6693 of file object_primitive.c.
References assert, db_get_oid(), DB_TYPE_OBJECT, DB_TYPE_OID, DB_VALUE_TYPE, pr_type::disksize, NO_ERROR, NULL, or_put_data(), db_identifier::pageid, rc, db_identifier::slotid, and db_identifier::volid.
Referenced by pr_type::get_cmpval_function(), and mr_index_writeval_object().
static int mr_index_writeval_short (OR_BUF * buf, DB_VALUE * value) static
Definition at line 2666 of file object_primitive.c.
References db_get_short(), pr_type::disksize, and or_put_data().
Referenced by pr_type::get_cmpval_function().
static int mr_index_writeval_string (OR_BUF * buf, DB_VALUE * value) static
Definition at line 10430 of file object_primitive.c.
References CHAR_ALIGNMENT, and mr_writeval_string_internal().
Referenced by pr_type::get_cmpval_function().
static int mr_index_writeval_time (OR_BUF * buf, DB_VALUE * value) static
Definition at line 3381 of file object_primitive.c.
References db_get_time(), pr_type::disksize, and or_put_data().
Referenced by pr_type::get_cmpval_function().
static int mr_index_writeval_timestamptz (OR_BUF * buf, DB_VALUE * value) static
Definition at line 3817 of file object_primitive.c.
References assert, db_get_timestamptz(), pr_type::disksize, NO_ERROR, or_put_data(), rc, db_timestamptz::timestamp, and db_timestamptz::tz_id.
Referenced by pr_type::get_cmpval_function().
static int mr_index_writeval_utime (OR_BUF * buf, DB_VALUE * value) static
Definition at line 3612 of file object_primitive.c.
References db_get_timestamp(), pr_type::disksize, and or_put_data().
Referenced by pr_type::get_cmpval_function().
static int mr_index_writeval_varbit (OR_BUF * buf, DB_VALUE * value) static
Definition at line 15348 of file object_primitive.c.
References CHAR_ALIGNMENT, and mr_writeval_varbit_internal().
Referenced by pr_type::get_cmpval_function().
static int mr_index_writeval_varnchar (OR_BUF * buf, DB_VALUE * value) static
Definition at line 13421 of file object_primitive.c.
References CHAR_ALIGNMENT, and mr_writeval_varnchar_internal().
Referenced by pr_type::get_cmpval_function().
static void mr_initmem_bigint (void * mem, TP_DOMAIN * domain) static
Definition at line 2744 of file object_primitive.c.
Referenced by pr_type::get_cmpval_function(), and mr_setmem_bigint().
static void mr_initmem_bit (void * memptr, TP_DOMAIN * domain) static
Definition at line 14272 of file object_primitive.c.
References assert, INTL_CODESET_RAW_BITS, IS_FLOATING_PRECISION, tp_domain::precision, STR_SIZE, and TP_DOMAIN_CODESET.
Referenced by pr_type::get_cmpval_function().
static void mr_initmem_char (void * memptr, TP_DOMAIN * domain) static
Definition at line 11241 of file object_primitive.c.
References assert, IS_FLOATING_PRECISION, tp_domain::precision, STR_SIZE, and TP_DOMAIN_CODESET.
Referenced by pr_type::get_cmpval_function().
static void mr_initmem_date (void * mem, TP_DOMAIN * domain) static
Definition at line 4719 of file object_primitive.c.
Referenced by pr_type::get_cmpval_function(), and mr_setmem_date().
static void mr_initmem_datetime (void * memptr, TP_DOMAIN * domain) static
Definition at line 3916 of file object_primitive.c.
References db_datetime::date, and db_datetime::time.
Referenced by pr_type::get_cmpval_function(), mr_initval_datetime(), mr_initval_datetimeltz(), and mr_setmem_datetime().
static void mr_initmem_datetimetz (void * memptr, TP_DOMAIN * domain) static
Definition at line 4283 of file object_primitive.c.
References db_datetime::date, db_datetimetz::datetime, db_datetime::time, and db_datetimetz::tz_id.
Referenced by pr_type::get_cmpval_function(), mr_initval_datetimetz(), and mr_setmem_datetimetz().
static void mr_initmem_double (void * mem, TP_DOMAIN * domain) static
Definition at line 3093 of file object_primitive.c.
References OR_MOVE_DOUBLE.
Referenced by pr_type::get_cmpval_function(), and mr_setmem_double().
static void mr_initmem_elo (void * memptr, TP_DOMAIN * domain) static
Definition at line 5635 of file object_primitive.c.
References NULL.
Referenced by pr_type::get_cmpval_function(), and mr_setmem_elo().
static void mr_initmem_enumeration (void * mem, TP_DOMAIN * domain) static
Definition at line 15689 of file object_primitive.c.
Referenced by pr_type::get_cmpval_function(), and mr_setmem_enumeration().
static void mr_initmem_error (void * memptr, TP_DOMAIN * domain) static
Definition at line 6424 of file object_primitive.c.
References NO_ERROR.
Referenced by pr_type::get_cmpval_function(), and mr_setmem_error().
static void mr_initmem_float (void * mem, TP_DOMAIN * domain) static
Definition at line 2915 of file object_primitive.c.
Referenced by pr_type::get_cmpval_function(), and mr_setmem_float().
static void mr_initmem_int (void * mem, TP_DOMAIN * domain) static
Definition at line 2403 of file object_primitive.c.
Referenced by pr_type::get_cmpval_function(), and mr_setmem_int().
static void mr_initmem_json (void * mem, TP_DOMAIN * domain) static
Definition at line 16547 of file object_primitive.c.
References assert, db_json::document, NULL, and db_json::schema_raw.
Referenced by pr_type::get_cmpval_function(), and mr_data_readmem_json().
static void mr_initmem_money (void * memptr, TP_DOMAIN * domain) static
Definition at line 4515 of file object_primitive.c.
References db_monetary::amount, DB_CURRENCY_DEFAULT, OR_MOVE_DOUBLE, and db_monetary::type.
Referenced by pr_type::get_cmpval_function(), and mr_setmem_money().
static void mr_initmem_nchar (void * memptr, TP_DOMAIN * domain) static
Definition at line 12144 of file object_primitive.c.
References assert, IS_FLOATING_PRECISION, tp_domain::precision, STR_SIZE, and TP_DOMAIN_CODESET.
Referenced by pr_type::get_cmpval_function().
static void mr_initmem_null (void * mem, TP_DOMAIN * domain) static
Definition at line 2249 of file object_primitive.c.
Referenced by pr_type::get_cmpval_function().
static void mr_initmem_numeric (void * memptr, TP_DOMAIN * domain) static
Definition at line 8369 of file object_primitive.c.
References assert, IS_FLOATING_PRECISION, MR_NUMERIC_SIZE, and tp_domain::precision.
Referenced by pr_type::get_cmpval_function(), and mr_setmem_numeric().
static void mr_initmem_object (void * mem, TP_DOMAIN * domain) static
Definition at line 4926 of file object_primitive.c.
References mr_null_oid(), NULL, ws_memoid::oid, and ws_memoid::pointer.
Referenced by pr_type::get_cmpval_function(), and mr_setmem_object().
static void mr_initmem_oid (void * memptr, TP_DOMAIN * domain) static
Definition at line 6568 of file object_primitive.c.
References mr_null_oid().
Referenced by pr_type::get_cmpval_function(), and mr_setmem_oid().
static void mr_initmem_ptr (void * memptr, TP_DOMAIN * domain) static
Definition at line 6292 of file object_primitive.c.
References NULL.
Referenced by pr_type::get_cmpval_function(), and mr_setmem_ptr().
static void mr_initmem_resultset (void * mem, TP_DOMAIN * domain) static
Definition at line 9842 of file object_primitive.c.
Referenced by pr_type::get_cmpval_function(), and mr_setmem_resultset().
static void mr_initmem_set (void * memptr, TP_DOMAIN * domain) static
Definition at line 6823 of file object_primitive.c.
References NULL.
Referenced by pr_type::get_cmpval_function(), and mr_setmem_set().
static void mr_initmem_short (void * mem, TP_DOMAIN * domain) static
Definition at line 2570 of file object_primitive.c.
Referenced by pr_type::get_cmpval_function(), and mr_setmem_short().
static void mr_initmem_string (void * mem, TP_DOMAIN * domain) static
Definition at line 9969 of file object_primitive.c.
References NULL.
Referenced by pr_type::get_cmpval_function(), and mr_setmem_string().
static void mr_initmem_sub (void * mem, TP_DOMAIN * domain) static
Definition at line 6203 of file object_primitive.c.
Referenced by pr_type::get_cmpval_function().
static void mr_initmem_time (void * mem, TP_DOMAIN * domain) static
Definition at line 3283 of file object_primitive.c.
Referenced by pr_type::get_cmpval_function(), and mr_setmem_time().
static void mr_initmem_timestamptz (void * mem, TP_DOMAIN * domain) static
Definition at line 3715 of file object_primitive.c.
References db_timestamptz::timestamp, and db_timestamptz::tz_id.
Referenced by pr_type::get_cmpval_function(), mr_initval_timestamptz(), and mr_setmem_timestamptz().
static void mr_initmem_utime (void * mem, TP_DOMAIN * domain) static
Definition at line 3461 of file object_primitive.c.
Referenced by pr_type::get_cmpval_function(), and mr_setmem_utime().
static void mr_initmem_varbit (void * mem, TP_DOMAIN * domain) static
Definition at line 15000 of file object_primitive.c.
References NULL.
Referenced by pr_type::get_cmpval_function(), and mr_setmem_varbit().
static void mr_initmem_varnchar (void * mem, TP_DOMAIN * domain) static
Definition at line 13093 of file object_primitive.c.
References NULL.
Referenced by pr_type::get_cmpval_function(), and mr_setmem_varnchar().
static void mr_initval_bigint (DB_VALUE * value, int precision, int scale) static
Definition at line 2788 of file object_primitive.c.
References db_make_bigint(), DB_TYPE_BIGINT, and db_value_domain_init().
Referenced by pr_type::get_cmpval_function().
static void mr_initval_bit (DB_VALUE * value, int precision, int scale) static
Definition at line 14474 of file object_primitive.c.
References DB_TYPE_BIT, and db_value_domain_init().
Referenced by pr_type::get_cmpval_function().
static void mr_initval_blob (DB_VALUE * value, int precision, int scale) static
Definition at line 5651 of file object_primitive.c.
References db_make_elo(), DB_TYPE_BLOB, db_value_domain_init(), and NULL.
Referenced by pr_type::get_cmpval_function().
static void mr_initval_char (DB_VALUE * value, int precision, int scale) static
Definition at line 11490 of file object_primitive.c.
References DB_DOMAIN_INIT_CHAR.
Referenced by pr_type::get_cmpval_function().
static void mr_initval_clob (DB_VALUE * value, int precision, int scale) static
Definition at line 5659 of file object_primitive.c.
References db_make_elo(), DB_TYPE_CLOB, db_value_domain_init(), and NULL.
Referenced by pr_type::get_cmpval_function().
static void mr_initval_date (DB_VALUE * value, int precision, int scale) static
Definition at line 4761 of file object_primitive.c.
References db_value_put_encoded_date(), and db_value::need_clear.
Referenced by pr_type::get_cmpval_function().
static void mr_initval_datetime (DB_VALUE * value, int precision, int scale) static
Definition at line 3925 of file object_primitive.c.
References db_make_datetime(), mr_initmem_datetime(), db_value::need_clear, and NULL.
Referenced by pr_type::get_cmpval_function().
static void mr_initval_datetimeltz (DB_VALUE * value, int precision, int scale) static
Definition at line 3935 of file object_primitive.c.
References db_make_datetimeltz(), mr_initmem_datetime(), db_value::need_clear, and NULL.
Referenced by pr_type::get_cmpval_function().
static void mr_initval_datetimetz (DB_VALUE * value, int precision, int scale) static
Definition at line 4293 of file object_primitive.c.
References db_make_datetimetz(), mr_initmem_datetimetz(), and NULL.
Referenced by pr_type::get_cmpval_function().
static void mr_initval_double (DB_VALUE * value, int precision, int scale) static
Definition at line 3153 of file object_primitive.c.
References db_make_double(), DB_TYPE_DOUBLE, and db_value_domain_init().
Referenced by pr_type::get_cmpval_function().
static void mr_initval_elo (DB_VALUE * value, int precision, int scale) static
Definition at line 5644 of file object_primitive.c.
References assert.
Referenced by pr_type::get_cmpval_function().
static void mr_initval_enumeration (DB_VALUE * value, int precision, int scale) static
Definition at line 15695 of file object_primitive.c.
References db_make_enumeration(), DB_TYPE_ENUMERATION, db_value_domain_init(), LANG_SYS_CODESET, LANG_SYS_COLLATION, and NULL.
Referenced by pr_type::get_cmpval_function().
static void mr_initval_error (DB_VALUE * value, int precision, int scale) static
Definition at line 6432 of file object_primitive.c.
References db_make_error(), DB_TYPE_ERROR, db_value_domain_init(), and NO_ERROR.
Referenced by pr_type::get_cmpval_function().
static void mr_initval_float (DB_VALUE * value, int precision, int scale) static
Definition at line 2963 of file object_primitive.c.
References db_make_float(), and db_value::need_clear.
Referenced by pr_type::get_cmpval_function().
static void mr_initval_int (DB_VALUE * value, int precision, int scale) static
Definition at line 2447 of file object_primitive.c.
References db_make_int(), DB_TYPE_INTEGER, and db_value_domain_init().
Referenced by pr_type::get_cmpval_function().
static void mr_initval_json (DB_VALUE * value, int precision, int scale) static
Definition at line 16750 of file object_primitive.c.
References DB_TYPE_JSON, db_value_domain_init(), and db_value::need_clear.
Referenced by pr_type::get_cmpval_function().
static void mr_initval_midxkey (DB_VALUE * value, int precision, int scale) static
Definition at line 7530 of file object_primitive.c.
References db_make_midxkey(), DB_TYPE_MIDXKEY, db_value_domain_init(), and NULL.
Referenced by pr_type::get_cmpval_function().
static void mr_initval_money (DB_VALUE * value, int precision, int scale) static
Definition at line 4577 of file object_primitive.c.
References DB_CURRENCY_DEFAULT, db_make_monetary(), and db_value::need_clear.
Referenced by pr_type::get_cmpval_function().
static void mr_initval_multiset (DB_VALUE * value, int precision, int scale) static
Definition at line 7395 of file object_primitive.c.
References db_make_multiset(), DB_TYPE_MULTISET, db_value_domain_init(), and NULL.
Referenced by pr_type::get_cmpval_function().
static void mr_initval_nchar (DB_VALUE * value, int precision, int scale) static
Definition at line 12393 of file object_primitive.c.
References DB_TYPE_NCHAR, and db_value_domain_init().
Referenced by pr_type::get_cmpval_function().
static void mr_initval_null (DB_VALUE * value, int precision, int scale) static
Definition at line 2307 of file object_primitive.c.
References DB_TYPE_NULL, and db_value_domain_init().
Referenced by pr_type::get_cmpval_function(), mr_initval_variable(), mr_setval_null(), and mr_setval_variable().
static void mr_initval_numeric (DB_VALUE * value, int precision, int scale) static
Definition at line 8498 of file object_primitive.c.
References DB_TYPE_NUMERIC, and db_value_domain_init().
Referenced by pr_type::get_cmpval_function().
static void mr_initval_object (DB_VALUE * value, int precision, int scale) static
Definition at line 4943 of file object_primitive.c.
References db_make_object(), db_make_oid(), db_on_server, DB_TYPE_OBJECT, DB_TYPE_OID, db_value_domain_init(), NULL, and OID_SET_NULL.
Referenced by pr_type::get_cmpval_function().
static void mr_initval_oid (DB_VALUE * value, int precision, int scale) static
Definition at line 6576 of file object_primitive.c.
References db_make_oid(), DB_TYPE_OID, db_value_domain_init(), and mr_null_oid().
Referenced by pr_type::get_cmpval_function().
static void mr_initval_ptr (DB_VALUE * value, int precision, int scale) static
Definition at line 6300 of file object_primitive.c.
References db_make_pointer(), DB_TYPE_POINTER, db_value_domain_init(), and NULL.
Referenced by pr_type::get_cmpval_function().
static void mr_initval_resultset (DB_VALUE * value, int precision, int scale) static
Definition at line 9890 of file object_primitive.c.
References db_make_resultset(), DB_TYPE_RESULTSET, and db_value_domain_init().
Referenced by pr_type::get_cmpval_function().
static void mr_initval_sequence (DB_VALUE * value, int precision, int scale) static
Definition at line 7444 of file object_primitive.c.
References db_make_sequence(), DB_TYPE_SEQUENCE, db_value_domain_init(), and NULL.
Referenced by pr_type::get_cmpval_function().
static void mr_initval_set (DB_VALUE * value, int precision, int scale) static
Definition at line 6831 of file object_primitive.c.
References db_make_set(), DB_TYPE_SET, db_value_domain_init(), and NULL.
Referenced by pr_type::get_cmpval_function().
static void mr_initval_short (DB_VALUE * value, int precision, int scale) static
Definition at line 2616 of file object_primitive.c.
References db_make_short(), DB_TYPE_SHORT, and db_value_domain_init().
Referenced by pr_type::get_cmpval_function().
static void mr_initval_string (DB_VALUE * value, int precision, int scale) static
Definition at line 10322 of file object_primitive.c.
References db_make_varchar(), LANG_SYS_CODESET, LANG_SYS_COLLATION, db_value::need_clear, and NULL.
Referenced by pr_type::get_cmpval_function().
static void mr_initval_sub (DB_VALUE * value, int precision, int scale) static
Definition at line 6208 of file object_primitive.c.
References DB_TYPE_SUB, and db_value_domain_init().
Referenced by pr_type::get_cmpval_function().
static void mr_initval_time (DB_VALUE * value, int precision, int scale) static
Definition at line 3327 of file object_primitive.c.
References db_value_put_encoded_time(), and db_value::need_clear.
Referenced by pr_type::get_cmpval_function().
static void mr_initval_timestampltz (DB_VALUE * value, int precision, int scale) static
Definition at line 3524 of file object_primitive.c.
References db_make_timestampltz(), and db_value::need_clear.
Referenced by pr_type::get_cmpval_function().
static void mr_initval_timestamptz (DB_VALUE * value, int precision, int scale) static
Definition at line 3767 of file object_primitive.c.
References db_make_timestamptz(), mr_initmem_timestamptz(), and NULL.
Referenced by pr_type::get_cmpval_function().
static void mr_initval_utime (DB_VALUE * value, int precision, int scale) static
Definition at line 3517 of file object_primitive.c.
References db_make_utime, and db_value::need_clear.
Referenced by pr_type::get_cmpval_function().
static void mr_initval_varbit (DB_VALUE * value, int precision, int scale) static
Definition at line 15285 of file object_primitive.c.
References db_make_varbit(), db_value::need_clear, and NULL.
Referenced by pr_type::get_cmpval_function().
static void mr_initval_variable (DB_VALUE * value, int precision, int scale) static
Definition at line 6148 of file object_primitive.c.
References mr_initval_null().
Referenced by pr_type::get_cmpval_function().
static void mr_initval_varnchar (DB_VALUE * value, int precision, int scale) static
Definition at line 13327 of file object_primitive.c.
References db_make_varnchar(), LANG_SYS_CODESET, LANG_SYS_COLLATION, db_value::need_clear, and NULL.
Referenced by pr_type::get_cmpval_function().
static void mr_initval_vobj (DB_VALUE * value, int precision, int scale) static
Definition at line 8299 of file object_primitive.c.
References DB_TYPE_VOBJ, and db_value_domain_init().
Referenced by pr_type::get_cmpval_function().
static int mr_lengthval_string_internal (DB_VALUE * value, int disk, int align) static
Definition at line 10466 of file object_primitive.c.
References db_char::buf, db_data::ch, db_value::data, db_get_compressed_size(), DB_IS_NULL, DB_TRIED_COMPRESSION, INT_ALIGNMENT, db_char::medium, NO_ERROR, OR_MINIMUM_STRING_LENGTH_FOR_COMPRESSION, or_packed_varchar_length(), or_varchar_length(), pr_do_db_value_string_compression(), PRIM_TEMPORARY_DISK_SIZE, rc, db_char::size, and strlen.
Referenced by pr_type::get_cmpval_function(), mr_data_lengthval_string(), and mr_index_lengthval_string().
static int mr_lengthval_varbit_internal (DB_VALUE * value, int disk, int align) static
Definition at line 15380 of file object_primitive.c.
References db_get_string(), db_get_string_length(), INT_ALIGNMENT, NULL, or_packed_varbit_length(), and or_varbit_length().
Referenced by pr_type::get_cmpval_function(), mr_data_lengthval_varbit(), and mr_index_lengthval_varbit().
static int mr_lengthval_varnchar_internal (DB_VALUE * value, int disk, int align) static
Definition at line 13457 of file object_primitive.c.
References db_get_compressed_size(), db_get_string(), db_get_string_codeset(), db_get_string_length(), db_get_string_size(), db_on_server, db_private_alloc, db_private_free_and_init, DB_TRIED_COMPRESSION, DO_CONVERSION_TO_SRVR_STR, INT_ALIGNMENT, intl_char_size(), intl_convert_charset(), lang_charset(), NO_ERROR, NULL, OR_MINIMUM_STRING_LENGTH_FOR_COMPRESSION, or_packed_varchar_length(), or_varchar_length(), pr_do_db_value_string_compression(), PRIM_TEMPORARY_DISK_SIZE, rc, STR_SIZE, and strlen.
Referenced by pr_type::get_cmpval_function(), mr_data_lengthval_varnchar(), and mr_index_lengthval_varnchar().
static void mr_null_oid (OID * oid) static
Definition at line 4916 of file object_primitive.c.
References OID_SET_NULL, db_identifier::pageid, db_identifier::slotid, and db_identifier::volid.
Referenced by pr_type::get_cmpval_function(), mr_initmem_object(), mr_initmem_oid(), mr_initval_oid(), and mr_setmem_object().
static int mr_readval_bit_internal (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int disk_size, bool copy, char * copy_buf, int copy_buf_len, int align) static
Definition at line 14706 of file object_primitive.c.
References ARG_FILE_LINE, assert, BITS_TO_BYTES, db_make_bit(), db_private_alloc, db_private_free_and_init, db_value_domain_init(), ER_ERROR_SEVERITY, ER_FAILED, er_set(), ER_SM_CORRUPTED, INT_ALIGNMENT, INTL_CODESET_RAW_BITS, IS_FLOATING_PRECISION, db_value::need_clear, NO_ERROR, NULL, or_abort(), or_advance(), or_get_data(), or_get_int(), OR_INT_SIZE, tp_domain::precision, or_buf::ptr, rc, STR_SIZE, TP_DOMAIN_CODESET, TP_DOMAIN_TYPE, and TP_FLOATING_PRECISION_VALUE.
Referenced by pr_type::get_cmpval_function(), mr_data_readval_bit(), and mr_index_readval_bit().
static int mr_readval_char_internal (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int disk_size, bool copy, char * copy_buf, int copy_buf_len, int align) static
Definition at line 11728 of file object_primitive.c.
References ARG_FILE_LINE, assert, db_make_char(), db_private_alloc, db_private_free_and_init, DB_TYPE_CHAR, db_value_domain_init(), ER_ERROR_SEVERITY, ER_FAILED, er_set(), ER_SM_CORRUPTED, INT_ALIGNMENT, intl_char_size(), IS_FLOATING_PRECISION, db_value::need_clear, NO_ERROR, NULL, or_abort(), or_advance(), or_get_data(), or_get_int(), OR_INT_SIZE, tp_domain::precision, or_buf::ptr, rc, STR_SIZE, TP_DOMAIN_CODESET, TP_DOMAIN_COLL_NORMAL, TP_DOMAIN_COLLATION, TP_DOMAIN_COLLATION_FLAG, TP_DOMAIN_TYPE, and TP_FLOATING_PRECISION_VALUE.
Referenced by pr_type::get_cmpval_function(), mr_data_readval_char(), and mr_index_readval_char().
static int mr_readval_nchar_internal (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int disk_size, bool copy, char * copy_buf, int copy_buf_len, int align) static
Definition at line 12691 of file object_primitive.c.
References ARG_FILE_LINE, assert, db_get_nchar(), DB_IS_NULL, db_make_nchar(), db_on_server, db_private_alloc, db_private_free_and_init, db_value_clear(), db_value_domain_init(), DO_CONVERSION_TO_SQLTEXT, ER_ERROR_SEVERITY, ER_FAILED, er_set(), ER_SM_CORRUPTED, INT_ALIGNMENT, intl_char_size(), intl_convert_charset(), IS_FLOATING_PRECISION, LANG_SYS_CODESET, db_value::need_clear, NO_ERROR, NULL, or_abort(), or_advance(), or_get_data(), or_get_int(), OR_INT_SIZE, tp_domain::precision, or_buf::ptr, rc, STR_SIZE, TP_DOMAIN_CODESET, TP_DOMAIN_COLL_NORMAL, TP_DOMAIN_COLLATION, TP_DOMAIN_COLLATION_FLAG, TP_DOMAIN_TYPE, and TP_FLOATING_PRECISION_VALUE.
Referenced by pr_type::get_cmpval_function(), mr_data_readval_nchar(), and mr_index_readval_nchar().
static int mr_readval_string_internal (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len, int align) static
Definition at line 10612 of file object_primitive.c.
References ARG_FILE_LINE, assert, cleanup(), db_make_varchar(), DB_MAX_VARCHAR_PRECISION, db_private_alloc, db_private_free_and_init, db_set_compressed_string(), DB_TYPE_VARCHAR, DB_UNCOMPRESSABLE, db_value_domain_init(), ER_ERROR_SEVERITY, ER_FAILED, ER_IO_LZ4_DECOMPRESS_FAIL, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), INT_ALIGNMENT, db_value::need_clear, NO_ERROR, NULL, or_abort(), or_advance(), or_get_align32(), or_get_data(), or_get_varchar_compression_lengths(), or_skip_varchar(), or_skip_varchar_remainder(), pr_get_compressed_data_from_buffer(), tp_domain::precision, or_buf::ptr, rc, TP_DOMAIN_CODESET, TP_DOMAIN_COLL_NORMAL, TP_DOMAIN_COLLATION, TP_DOMAIN_COLLATION_FLAG, TP_DOMAIN_TYPE, and TP_FLOATING_PRECISION_VALUE.
Referenced by pr_type::get_cmpval_function(), mr_data_readval_string(), and mr_index_readval_string().
static int mr_readval_varbit_internal (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len, int align) static
Definition at line 15437 of file object_primitive.c.
References BITS_TO_BYTES, db_make_varbit(), DB_MAX_VARBIT_PRECISION, db_private_alloc, db_private_free_and_init, DB_TYPE_VARBIT, db_value_domain_init(), ER_FAILED, INT_ALIGNMENT, db_value::need_clear, NO_ERROR, NULL, or_abort(), or_advance(), or_get_align32(), or_get_data(), or_get_varbit_length(), or_skip_varbit(), or_skip_varbit_remainder(), tp_domain::precision, or_buf::ptr, rc, TP_DOMAIN_TYPE, and TP_FLOATING_PRECISION_VALUE.
Referenced by pr_type::get_cmpval_function(), mr_data_readval_varbit(), and mr_index_readval_varbit().
static int mr_readval_varnchar_internal (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len, int align) static
Definition at line 13639 of file object_primitive.c.
References ARG_FILE_LINE, assert, cleanup(), db_get_nchar(), DB_IS_NULL, db_make_varnchar(), DB_MAX_VARNCHAR_PRECISION, db_on_server, db_private_alloc, db_private_free_and_init, db_set_compressed_string(), DB_TYPE_VARNCHAR, DB_UNCOMPRESSABLE, db_value_clear(), db_value_domain_init(), DO_CONVERSION_TO_SQLTEXT, ER_ERROR_SEVERITY, ER_FAILED, ER_IO_LZ4_DECOMPRESS_FAIL, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), INT_ALIGNMENT, intl_convert_charset(), LANG_SYS_CODESET, db_value::need_clear, NO_ERROR, NULL, or_abort(), or_advance(), or_get_align32(), or_get_data(), or_get_varchar_compression_lengths(), or_skip_varchar(), or_skip_varchar_remainder(), pr_get_compressed_data_from_buffer(), tp_domain::precision, or_buf::ptr, rc, STR_SIZE, TP_DOMAIN_CODESET, TP_DOMAIN_COLL_NORMAL, TP_DOMAIN_COLLATION, TP_DOMAIN_COLLATION_FLAG, TP_DOMAIN_TYPE, and TP_FLOATING_PRECISION_VALUE.
Referenced by pr_type::get_cmpval_function(), mr_data_readval_varnchar(), and mr_index_readval_varnchar().
static int mr_setmem_bigint (void * mem, TP_DOMAIN * domain, DB_VALUE * value) static
Definition at line 2750 of file object_primitive.c.
References db_get_bigint(), mr_initmem_bigint(), NO_ERROR, and NULL.
Referenced by pr_type::get_cmpval_function().
static int mr_setmem_bit (void * memptr, TP_DOMAIN * domain, DB_VALUE * value) static
Definition at line 14300 of file object_primitive.c.
References ARG_FILE_LINE, assert, db_get_string(), db_get_string_size(), db_value_precision(), ER_ERROR_SEVERITY, ER_OBJ_DOMAIN_CONFLICT, er_set(), error(), i, INTL_CODESET_RAW_BITS, NO_ERROR, NULL, tp_domain::precision, STR_SIZE, and TP_DOMAIN_CODESET.
Referenced by pr_type::get_cmpval_function().
static int mr_setmem_char (void * memptr, TP_DOMAIN * domain, DB_VALUE * value) static
Definition at line 11269 of file object_primitive.c.
References ARG_FILE_LINE, assert, db_get_string(), DB_GET_STRING_PRECISION, db_get_string_size(), ER_ERROR_SEVERITY, ER_OBJ_DOMAIN_CONFLICT, er_set(), error(), i, IS_FLOATING_PRECISION, NO_ERROR, NULL, tp_domain::precision, STR_SIZE, strlen, and TP_DOMAIN_CODESET.
Referenced by pr_type::get_cmpval_function().
static int mr_setmem_date (void * mem, TP_DOMAIN * domain, DB_VALUE * value) static
Definition at line 4725 of file object_primitive.c.
References db_get_date(), mr_initmem_date(), NO_ERROR, and NULL.
Referenced by pr_type::get_cmpval_function().
static int mr_setmem_datetime (void * mem, TP_DOMAIN * domain, DB_VALUE * value) static
Definition at line 3945 of file object_primitive.c.
References db_get_datetime(), mr_initmem_datetime(), NO_ERROR, and NULL.
Referenced by pr_type::get_cmpval_function().
static int mr_setmem_datetimetz (void * mem, TP_DOMAIN * domain, DB_VALUE * value) static
Definition at line 4302 of file object_primitive.c.
References db_get_datetimetz(), mr_initmem_datetimetz(), NO_ERROR, and NULL.
Referenced by pr_type::get_cmpval_function().
static int mr_setmem_double (void * mem, TP_DOMAIN * domain, DB_VALUE * value) static
Definition at line 3101 of file object_primitive.c.
References db_get_double(), mr_initmem_double(), NO_ERROR, NULL, and OR_MOVE_DOUBLE.
Referenced by pr_type::get_cmpval_function().
static int mr_setmem_elo (void * memptr, TP_DOMAIN * domain, DB_VALUE * value) static
Definition at line 5667 of file object_primitive.c.
References assert_release, db_get_elo(), db_private_alloc, db_private_free_and_init, elo_copy_structure(), er_errid(), ER_FAILED, mr_freemem_elo(), mr_initmem_elo(), NO_ERROR, NULL, and rc.
Referenced by pr_type::get_cmpval_function().
static int mr_setmem_enumeration (void * mem, TP_DOMAIN * domain, DB_VALUE * value) static
Definition at line 15702 of file object_primitive.c.
References db_get_enum_short(), mr_initmem_enumeration(), NO_ERROR, and NULL.
Referenced by pr_type::get_cmpval_function().
static int mr_setmem_error (void * memptr, TP_DOMAIN * domain, DB_VALUE * value) static
Definition at line 6439 of file object_primitive.c.
References db_get_error(), mr_initmem_error(), NO_ERROR, and NULL.
Referenced by pr_type::get_cmpval_function().
static int mr_setmem_float (void * mem, TP_DOMAIN * domain, DB_VALUE * value) static
Definition at line 2921 of file object_primitive.c.
References db_get_float(), mr_initmem_float(), NO_ERROR, and NULL.
Referenced by pr_type::get_cmpval_function().
static int mr_setmem_int (void * mem, TP_DOMAIN * domain, DB_VALUE * value) static
Definition at line 2409 of file object_primitive.c.
References db_get_int(), mr_initmem_int(), NO_ERROR, and NULL.
Referenced by pr_type::get_cmpval_function().
static int mr_setmem_json (void * memptr, TP_DOMAIN * domain, DB_VALUE * value) static
Definition at line 16563 of file object_primitive.c.
References assert, ASSERT_ERROR, db_value::data, db_get_deep_copy_of_json(), db_get_json_document(), error(), db_data::json, mr_freemem_json(), NO_ERROR, and NULL.
Referenced by pr_type::get_cmpval_function().
static int mr_setmem_money (void * memptr, TP_DOMAIN * domain, DB_VALUE * value) static
Definition at line 4526 of file object_primitive.c.
References db_monetary::amount, db_get_monetary(), mr_initmem_money(), NO_ERROR, NULL, OR_MOVE_DOUBLE, and db_monetary::type.
Referenced by pr_type::get_cmpval_function().
static int mr_setmem_nchar (void * memptr, TP_DOMAIN * domain, DB_VALUE * value) static
Definition at line 12171 of file object_primitive.c.
References ARG_FILE_LINE, db_get_string(), db_get_string_size(), db_value_precision(), ER_ERROR_SEVERITY, ER_OBJ_DOMAIN_CONFLICT, er_set(), error(), i, NO_ERROR, NULL, tp_domain::precision, STR_SIZE, strlen, and TP_DOMAIN_CODESET.
Referenced by pr_type::get_cmpval_function().
static int mr_setmem_null (void * memptr, TP_DOMAIN * domain, DB_VALUE * value) static
Definition at line 2261 of file object_primitive.c.
References NO_ERROR.
Referenced by pr_type::get_cmpval_function().
static int mr_setmem_numeric (void * mem, TP_DOMAIN * domain, DB_VALUE * value) static
Definition at line 8383 of file object_primitive.c.
References ARG_FILE_LINE, db_get_numeric(), db_value_precision(), db_value_scale(), ER_ERROR_SEVERITY, ER_OBJ_DOMAIN_CONFLICT, er_set(), error(), mr_initmem_numeric(), MR_NUMERIC_SIZE, NO_ERROR, NULL, tp_domain::precision, and tp_domain::scale.
Referenced by pr_type::get_cmpval_function().
static int mr_setmem_object (void * memptr, TP_DOMAIN * domain, DB_VALUE * value) static
Definition at line 4967 of file object_primitive.c.
References db_get_object(), db_object::is_temp, mr_initmem_object(), mr_null_oid(), NO_ERROR, NULL, ws_memoid::oid, db_identifier::pageid, ws_memoid::pointer, db_identifier::slotid, db_identifier::volid, and WS_OID.
Referenced by pr_type::get_cmpval_function().
static int mr_setmem_oid (void * memptr, TP_DOMAIN * domain, DB_VALUE * value) static
Definition at line 6586 of file object_primitive.c.
References db_get_oid(), ER_FAILED, mr_initmem_oid(), NO_ERROR, NULL, db_identifier::pageid, db_identifier::slotid, and db_identifier::volid.
Referenced by pr_type::get_cmpval_function().
static int mr_setmem_ptr (void * memptr, TP_DOMAIN * domain, DB_VALUE * value) static
Definition at line 6307 of file object_primitive.c.
References db_get_pointer(), mr_initmem_ptr(), NO_ERROR, and NULL.
Referenced by pr_type::get_cmpval_function().
static int mr_setmem_resultset (void * mem, TP_DOMAIN * domain, DB_VALUE * value) static
Definition at line 9848 of file object_primitive.c.
References db_get_resultset(), mr_initmem_resultset(), NO_ERROR, and NULL.
Referenced by pr_type::get_cmpval_function().
static int mr_setmem_set (void * memptr, TP_DOMAIN * domain, DB_VALUE * value) static
Definition at line 6838 of file object_primitive.c.
References db_get_set(), error(), mr_initmem_set(), NO_ERROR, NULL, db_set::set, and setobj_release().
Referenced by pr_type::get_cmpval_function().
static int mr_setmem_short (void * mem, TP_DOMAIN * domain, DB_VALUE * value) static
Definition at line 2576 of file object_primitive.c.
References db_get_short(), mr_initmem_short(), NO_ERROR, and NULL.
Referenced by pr_type::get_cmpval_function().
static int mr_setmem_string (void * memptr, TP_DOMAIN * domain, DB_VALUE * value) static
Definition at line 9981 of file object_primitive.c.
References assert, db_get_string(), DB_GET_STRING_PRECISION, db_get_string_size(), db_private_alloc, db_private_free_and_init, er_errid(), error(), mr_initmem_string(), NO_ERROR, NULL, and strlen.
Referenced by pr_type::get_cmpval_function().
static int mr_setmem_sub (void * mem, TP_DOMAIN * domain, DB_VALUE * value) static
Definition at line 6214 of file object_primitive.c.
References NO_ERROR.
Referenced by pr_type::get_cmpval_function().
static int mr_setmem_time (void * mem, TP_DOMAIN * domain, DB_VALUE * value) static
Definition at line 3289 of file object_primitive.c.
References db_get_time(), mr_initmem_time(), NO_ERROR, and NULL.
Referenced by pr_type::get_cmpval_function().
static int mr_setmem_timestamptz (void * mem, TP_DOMAIN * domain, DB_VALUE * value) static
Definition at line 3724 of file object_primitive.c.
References db_get_timestamptz(), mr_initmem_timestamptz(), NO_ERROR, and NULL.
Referenced by pr_type::get_cmpval_function().
static int mr_setmem_utime (void * mem, TP_DOMAIN * domain, DB_VALUE * value) static
Definition at line 3467 of file object_primitive.c.
References db_get_timestamp(), mr_initmem_utime(), NO_ERROR, and NULL.
Referenced by pr_type::get_cmpval_function().
static int mr_setmem_varbit (void * memptr, TP_DOMAIN * domain, DB_VALUE * value) static
Definition at line 15012 of file object_primitive.c.
References assert, db_get_string(), db_get_string_length(), db_get_string_size(), db_private_alloc, db_private_free_and_init, db_value_precision(), er_errid(), error(), mr_initmem_varbit(), NO_ERROR, and NULL.
Referenced by pr_type::get_cmpval_function().
static int mr_setmem_varnchar (void * memptr, TP_DOMAIN * domain, DB_VALUE * value) static
Definition at line 13105 of file object_primitive.c.
References assert, db_get_string(), db_get_string_size(), db_private_alloc, db_private_free_and_init, db_value_precision(), er_errid(), error(), mr_initmem_varnchar(), NO_ERROR, NULL, and strlen.
Referenced by pr_type::get_cmpval_function().
static int mr_setval_bigint (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 2795 of file object_primitive.c.
References DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_get_bigint(), DB_IS_NULL, db_make_bigint(), DB_TYPE_BIGINT, and db_value_domain_init().
Referenced by pr_type::get_cmpval_function().
static int mr_setval_bit (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 14480 of file object_primitive.c.
References assert, DB_DEFAULT_PRECISION, db_get_bit(), db_get_string_size(), DB_IS_NULL, db_make_bit(), db_private_alloc, DB_TYPE_BIT, db_value_domain_init(), db_value_is_corrupted(), db_value_precision(), er_errid(), error(), db_value::need_clear, NO_ERROR, and NULL.
Referenced by pr_type::get_cmpval_function().
static int mr_setval_blob (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 5803 of file object_primitive.c.
References DB_TYPE_BLOB, and setval_elo_with_type().
Referenced by pr_type::get_cmpval_function().
static int mr_setval_char (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 11496 of file object_primitive.c.
References assert, DB_DOMAIN_INIT_CHAR, db_get_string(), db_get_string_codeset(), db_get_string_collation(), DB_GET_STRING_PRECISION, db_get_string_size(), DB_IS_NULL, db_make_char(), db_private_alloc, db_value_is_corrupted(), er_errid(), error(), db_value::need_clear, NO_ERROR, NULL, strlen, and TP_FLOATING_PRECISION_VALUE.
Referenced by pr_type::get_cmpval_function().
static int mr_setval_clob (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 5809 of file object_primitive.c.
References DB_TYPE_CLOB, and setval_elo_with_type().
Referenced by pr_type::get_cmpval_function().
static int mr_setval_date (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 4768 of file object_primitive.c.
References DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_get_date(), DB_IS_NULL, DB_TYPE_DATE, db_value_domain_init(), db_value_put_encoded_date(), and error().
Referenced by pr_type::get_cmpval_function().
static int mr_setval_datetime (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 3972 of file object_primitive.c.
References DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_get_datetime(), DB_IS_NULL, db_make_datetime(), DB_TYPE_DATETIME, db_value_domain_init(), and error().
Referenced by pr_type::get_cmpval_function().
static int mr_setval_datetimeltz (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 3988 of file object_primitive.c.
References DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_get_datetime(), DB_IS_NULL, db_make_datetimeltz(), DB_TYPE_DATETIMELTZ, db_value_domain_init(), and error().
Referenced by pr_type::get_cmpval_function().
static int mr_setval_datetimetz (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 4323 of file object_primitive.c.
References DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_get_datetimetz(), DB_IS_NULL, db_make_datetimetz(), DB_TYPE_DATETIMETZ, db_value_domain_init(), and error().
Referenced by pr_type::get_cmpval_function().
static int mr_setval_double (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 3160 of file object_primitive.c.
References DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_get_double(), DB_IS_NULL, db_make_double(), DB_TYPE_DOUBLE, and db_value_domain_init().
Referenced by pr_type::get_cmpval_function().
static int mr_setval_elo (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 5796 of file object_primitive.c.
References assert, and ER_FAILED.
Referenced by pr_type::get_cmpval_function().
static int mr_setval_enumeration (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 15727 of file object_primitive.c.
References assert, DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_get_enum_codeset(), db_get_enum_collation(), db_get_enum_short(), db_get_enum_string(), db_get_enum_string_size(), DB_IS_NULL, db_make_enumeration(), db_private_alloc, DB_TYPE_ENUMERATION, db_value_domain_init(), er_errid(), db_value::need_clear, NO_ERROR, and NULL.
Referenced by pr_type::get_cmpval_function().
static int mr_setval_enumeration_internal (DB_VALUE * value, TP_DOMAIN * domain, unsigned short index, int size, bool copy, char * copy_buf, int copy_buf_len) static
Definition at line 15801 of file object_primitive.c.
References assert, DB_ENUM_OVERFLOW_VAL, DB_GET_ENUM_ELEM_STRING, DB_GET_ENUM_ELEM_STRING_SIZE, db_make_enumeration(), db_private_alloc, DOM_GET_ENUM_ELEM, DOM_GET_ENUM_ELEMS_COUNT, ER_FAILED, db_value::need_clear, NO_ERROR, NULL, TP_DOMAIN_CODESET, and TP_DOMAIN_COLLATION.
Referenced by pr_type::get_cmpval_function(), mr_data_readval_enumeration(), mr_getmem_enumeration(), and mr_index_readval_enumeration().
static int mr_setval_error (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 6463 of file object_primitive.c.
References db_get_error(), DB_IS_NULL, db_make_error(), db_make_null(), and NO_ERROR.
Referenced by pr_type::get_cmpval_function().
static int mr_setval_float (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 2970 of file object_primitive.c.
References DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_get_float(), DB_IS_NULL, db_make_float(), DB_TYPE_FLOAT, and db_value_domain_init().
Referenced by pr_type::get_cmpval_function().
static int mr_setval_int (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 2454 of file object_primitive.c.
References DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_get_int(), DB_IS_NULL, db_make_int(), DB_TYPE_INTEGER, and db_value_domain_init().
Referenced by pr_type::get_cmpval_function().
static int mr_setval_json (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 16757 of file object_primitive.c.
References ASSERT_ERROR, db_value::data, DB_DEFAULT_PRECISION, DB_IS_NULL, db_json_get_copy_of_doc(), db_private_strdup(), DB_TYPE_JSON, db_value_domain_init(), db_json::document, db_value::domain, error(), db_domain_info::general_info, db_domain_info::general_info::is_null, db_data::json, db_value::need_clear, NO_ERROR, NULL, and db_json::schema_raw.
Referenced by pr_type::get_cmpval_function().
static int mr_setval_midxkey (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 7538 of file object_primitive.c.
References assert, db_midxkey::buf, DB_DEFAULT_PRECISION, db_get_midxkey(), DB_IS_NULL, db_make_midxkey(), db_private_alloc, DB_TYPE_MIDXKEY, db_value_domain_init(), db_value_precision(), db_midxkey::domain, er_errid(), error(), db_midxkey::min_max_val, db_midxkey::ncolumns, db_value::need_clear, NO_ERROR, NULL, special_column::position, db_midxkey::size, strlen, and special_column::type.
Referenced by pr_type::get_cmpval_function().
static int mr_setval_money (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 4584 of file object_primitive.c.
References db_monetary::amount, DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_get_monetary(), DB_IS_NULL, db_make_monetary(), DB_TYPE_MONETARY, db_value_domain_init(), error(), NULL, and db_monetary::type.
Referenced by pr_type::get_cmpval_function().
static int mr_setval_multiset (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 7434 of file object_primitive.c.
References DB_TYPE_MULTISET, and mr_setval_set_internal().
Referenced by pr_type::get_cmpval_function().
static int mr_setval_nchar (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 12399 of file object_primitive.c.
References assert, DB_DEFAULT_PRECISION, db_get_string(), db_get_string_codeset(), db_get_string_collation(), db_get_string_size(), DB_IS_NULL, db_make_nchar(), db_private_alloc, DB_TYPE_NCHAR, db_value_domain_init(), db_value_is_corrupted(), db_value_precision(), er_errid(), error(), db_value::need_clear, NO_ERROR, NULL, and strlen.
Referenced by pr_type::get_cmpval_function().
static int mr_setval_null (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 2320 of file object_primitive.c.
References mr_initval_null(), and NO_ERROR.
Referenced by pr_type::get_cmpval_function().
static int mr_setval_numeric (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 8504 of file object_primitive.c.
References assert, DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_get_numeric(), DB_IS_NULL, db_make_numeric(), DB_TYPE_NUMERIC, db_value_domain_init(), db_value_is_corrupted(), db_value_precision(), db_value_scale(), error(), NO_ERROR, and NULL.
Referenced by pr_type::get_cmpval_function().
static int mr_setval_object (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 5045 of file object_primitive.c.
References DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_get_object(), db_get_oid(), DB_IS_NULL, db_make_null(), db_make_object(), db_make_oid(), db_on_server, DB_TYPE_OBJECT, DB_TYPE_OID, db_value_domain_init(), DB_VALUE_TYPE, error(), NO_ERROR, and WS_OID.
Referenced by pr_type::get_cmpval_function().
static int mr_setval_oid (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 6625 of file object_primitive.c.
References db_get_oid(), DB_IS_NULL, db_make_null(), db_make_oid(), and NO_ERROR.
Referenced by pr_type::get_cmpval_function().
static int mr_setval_ptr (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 6331 of file object_primitive.c.
References db_get_pointer(), DB_IS_NULL, db_make_null(), db_make_pointer(), and NO_ERROR.
Referenced by pr_type::get_cmpval_function().
static int mr_setval_resultset (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 9897 of file object_primitive.c.
References DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_get_resultset(), DB_IS_NULL, db_make_resultset(), DB_TYPE_RESULTSET, and db_value_domain_init().
Referenced by pr_type::get_cmpval_function().
static int mr_setval_sequence (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 7486 of file object_primitive.c.
References DB_TYPE_SEQUENCE, and mr_setval_set_internal().
Referenced by pr_type::get_cmpval_function(), and mr_setval_vobj().
static int mr_setval_set (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 7002 of file object_primitive.c.
References DB_TYPE_SET, and mr_setval_set_internal().
Referenced by pr_type::get_cmpval_function().
static int mr_setval_set_internal (DB_VALUE * dest, const DB_VALUE * src, bool copy, DB_TYPE set_type) static
Definition at line 6908 of file object_primitive.c.
References assert, DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_get_set(), DB_IS_NULL, db_make_multiset(), db_make_null(), db_make_sequence(), db_make_set(), db_private_alloc, DB_TYPE_MULTISET, DB_TYPE_SEQUENCE, DB_TYPE_SET, db_value_domain_init(), db_set::disk_domain, db_set::disk_set, db_set::disk_size, er_errid(), error(), db_set::need_clear, NO_ERROR, NULL, db_set::ref_count, set_copy(), and set_make_reference().
Referenced by pr_type::get_cmpval_function(), mr_setval_multiset(), mr_setval_sequence(), and mr_setval_set().
static int mr_setval_short (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 2623 of file object_primitive.c.
References DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_get_short(), DB_IS_NULL, db_make_short(), DB_TYPE_SHORT, and db_value_domain_init().
Referenced by pr_type::get_cmpval_function().
static int mr_setval_string (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 10329 of file object_primitive.c.
References assert, db_data::ch, db_domain_info::char_info, db_char::codeset, db_domain_info::char_info::collation_id, db_char::compressed_buf, db_char::compressed_need_clear, db_char::compressed_size, db_value::data, DB_DEFAULT_PRECISION, db_get_string(), db_get_string_codeset(), db_get_string_collation(), db_get_string_size(), DB_IS_NULL, db_make_varchar(), db_private_alloc, DB_TYPE_VARCHAR, DB_UNCOMPRESSABLE, db_value_domain_init(), db_value_is_corrupted(), db_value_precision(), db_value::domain, er_errid(), error(), db_domain_info::general_info, db_char::info, db_char::is_max_string, db_domain_info::general_info::is_null, db_char::medium, db_value::need_clear, NO_ERROR, NULL, and strlen.
Referenced by pr_type::get_cmpval_function().
static int mr_setval_sub (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 6226 of file object_primitive.c.
References NO_ERROR.
Referenced by pr_type::get_cmpval_function().
static int mr_setval_time (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 3336 of file object_primitive.c.
References DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_get_time(), DB_IS_NULL, DB_TYPE_TIME, db_value_domain_init(), db_value_put_encoded_time(), and error().
Referenced by pr_type::get_cmpval_function().
static int mr_setval_timestampltz (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 3547 of file object_primitive.c.
References DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_get_timestamp(), DB_IS_NULL, db_make_timestampltz(), DB_TYPE_TIMESTAMPLTZ, db_value_domain_init(), and error().
Referenced by pr_type::get_cmpval_function().
static int mr_setval_timestamptz (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 3776 of file object_primitive.c.
References DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_get_timestamptz(), DB_IS_NULL, db_make_timestamptz(), DB_TYPE_TIMESTAMPTZ, db_value_domain_init(), and error().
Referenced by pr_type::get_cmpval_function().
static int mr_setval_utime (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 3531 of file object_primitive.c.
References DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_get_timestamp(), DB_IS_NULL, db_make_utime, DB_TYPE_TIMESTAMP, db_value_domain_init(), and error().
Referenced by pr_type::get_cmpval_function().
static int mr_setval_varbit (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 15292 of file object_primitive.c.
References assert, DB_DEFAULT_PRECISION, db_get_string(), db_get_string_length(), db_get_string_size(), DB_IS_NULL, db_make_varbit(), db_private_alloc, DB_TYPE_VARBIT, db_value_domain_init(), db_value_is_corrupted(), db_value_precision(), er_errid(), error(), db_value::need_clear, NO_ERROR, and NULL.
Referenced by pr_type::get_cmpval_function().
static int mr_setval_variable (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 6154 of file object_primitive.c.
References mr_initval_null(), and NO_ERROR.
Referenced by pr_type::get_cmpval_function().
static int mr_setval_varnchar (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 13334 of file object_primitive.c.
References assert, db_data::ch, db_char::compressed_buf, db_char::compressed_need_clear, db_char::compressed_size, db_value::data, DB_DEFAULT_PRECISION, db_get_string(), db_get_string_codeset(), db_get_string_collation(), db_get_string_size(), DB_IS_NULL, db_make_varnchar(), db_private_alloc, DB_TYPE_VARNCHAR, db_value_domain_init(), db_value_is_corrupted(), db_value_precision(), er_errid(), error(), db_char::info, db_char::medium, db_value::need_clear, NO_ERROR, NULL, and strlen.
Referenced by pr_type::get_cmpval_function().
static int mr_setval_vobj (DB_VALUE * dest, const DB_VALUE * src, bool copy) static
Definition at line 8305 of file object_primitive.c.
References DB_TYPE_VOBJ, db_value_alter_type(), error(), and mr_setval_sequence().
Referenced by pr_type::get_cmpval_function().
static int mr_writeval_bit_internal (OR_BUF * buf, DB_VALUE * value, int align) static
Definition at line 14616 of file object_primitive.c.
References assert, BITS_TO_BYTES, db_get_string(), db_get_string_codeset(), db_get_string_length(), db_get_string_size(), db_value_precision(), i, INT_ALIGNMENT, INTL_CODESET_RAW_BITS, IS_FLOATING_PRECISION, NO_ERROR, NULL, OR_INT_SIZE, or_put_byte(), or_put_data(), or_put_int(), rc, and STR_SIZE.
Referenced by pr_type::get_cmpval_function(), mr_data_writeval_bit(), and mr_index_writeval_bit().
static int mr_writeval_char_internal (OR_BUF * buf, DB_VALUE * value, int align) static
Definition at line 11628 of file object_primitive.c.
References db_get_string(), db_get_string_codeset(), db_get_string_size(), db_value_precision(), i, INT_ALIGNMENT, IS_FLOATING_PRECISION, NO_ERROR, NULL, OR_INT_SIZE, or_put_byte(), or_put_data(), or_put_int(), rc, STR_SIZE, and strlen.
Referenced by pr_type::get_cmpval_function(), mr_data_writeval_char(), and mr_index_writeval_char().
static int mr_writeval_nchar_internal (OR_BUF * buf, DB_VALUE * value, int align) static
Definition at line 12551 of file object_primitive.c.
References db_get_string(), db_get_string_codeset(), db_get_string_length(), db_get_string_size(), db_on_server, db_private_alloc, db_private_free_and_init, db_value_precision(), DO_CONVERSION_TO_SRVR_STR, error(), i, INT_ALIGNMENT, intl_char_size(), intl_convert_charset(), intl_pad_char(), IS_FLOATING_PRECISION, lang_charset(), NO_ERROR, NULL, OR_INT_SIZE, or_put_byte(), or_put_data(), or_put_int(), rc, STR_SIZE, and strlen.
Referenced by pr_type::get_cmpval_function(), mr_data_writeval_nchar(), and mr_index_writeval_nchar().
static int mr_writeval_string_internal (OR_BUF * buf, DB_VALUE * value, int align) static
Definition at line 10546 of file object_primitive.c.
References assert, db_char::buf, db_data::ch, db_value::data, db_get_compressed_size(), DB_GET_COMPRESSED_STRING, db_get_string(), db_get_string_size(), DB_TRIED_COMPRESSION, DB_UNCOMPRESSABLE, db_char::medium, NO_ERROR, NULL, OR_MINIMUM_STRING_LENGTH_FOR_COMPRESSION, pr_do_db_value_string_compression(), pr_write_compressed_string_to_buffer(), pr_write_uncompressed_string_to_buffer(), rc, pr_type::size, and strlen.
Referenced by pr_type::get_cmpval_function(), mr_data_writeval_string(), and mr_index_writeval_string().
static int mr_writeval_varbit_internal (OR_BUF * buf, DB_VALUE * value, int align) static
Definition at line 15403 of file object_primitive.c.
References db_get_string(), db_get_string_length(), INT_ALIGNMENT, NO_ERROR, NULL, or_packed_put_varbit(), or_put_varbit(), and rc.
Referenced by pr_type::get_cmpval_function(), mr_data_writeval_varbit(), and mr_index_writeval_varbit().
static int mr_writeval_varnchar_internal (OR_BUF * buf, DB_VALUE * value, int align) static
Definition at line 13547 of file object_primitive.c.
References assert, db_char::buf, db_data::ch, db_value::data, db_get_compressed_size(), DB_GET_COMPRESSED_STRING, db_get_string(), db_get_string_codeset(), db_get_string_length(), db_get_string_size(), DB_NOT_YET_COMPRESSED, db_on_server, db_private_alloc, db_private_free_and_init, DB_TRIED_COMPRESSION, DB_UNCOMPRESSABLE, DO_CONVERSION_TO_SRVR_STR, INT_ALIGNMENT, intl_char_size(), intl_convert_charset(), lang_charset(), db_char::medium, NO_ERROR, NULL, OR_MINIMUM_STRING_LENGTH_FOR_COMPRESSION, or_packed_put_varchar(), or_put_varchar(), pr_do_db_value_string_compression(), pr_write_compressed_string_to_buffer(), pr_write_uncompressed_string_to_buffer(), rc, REINTERPRET_CAST, pr_type::size, STR_SIZE, and strlen.
Referenced by pr_type::get_cmpval_function(), mr_data_writeval_varnchar(), and mr_index_writeval_varnchar().
static void peekmem_elo (OR_BUF * buf, DB_ELO * elo) static
Definition at line 5899 of file object_primitive.c.
References assert, ELO_NULL, error(), db_elo::locator, db_elo::meta_data, NO_ERROR, NULL, or_advance(), or_get_bigint(), or_get_int(), or_buf::ptr, rc, db_elo::size, and db_elo::type.
Referenced by pr_type::get_cmpval_function(), mr_data_readmem_elo(), and readval_elo_with_type().
void pr_area_final (void)
Definition at line 1848 of file object_primitive.c.
References area_destroy(), and NULL.
Referenced by PRIM_SET_NULL(), and ws_init().
int pr_area_init (void)
Definition at line 1831 of file object_primitive.c.
References area_create(), assert, er_errid(), NO_ERROR, NULL, and VALUE_AREA_COUNT.
Referenced by boot_restart_server(), PRIM_SET_NULL(), ws_init(), and xboot_initialize_server().
int pr_clear_compressed_string (DB_VALUE * value)
Definition at line 16396 of file object_primitive.c.
References db_data::ch, db_char::compressed_buf, db_char::compressed_need_clear, db_char::compressed_size, db_value::data, DB_IS_NULL, db_private_free_and_init, db_set_compressed_string(), DB_TYPE_VARCHAR, DB_TYPE_VARNCHAR, DB_VALUE_DOMAIN_TYPE, db_char::info, db_char::medium, NO_ERROR, and NULL.
Referenced by PRIM_SET_NULL(), qdata_copy_db_value_to_tuple_value(), and string_disk_size().
int pr_clear_value (DB_VALUE * value)
Definition at line 1912 of file object_primitive.c.
References assert, db_midxkey::buf, db_char::buf, db_data::ch, db_char::compressed_buf, db_char::compressed_need_clear, CONST_CAST, db_value::data, DB_GET_COMPRESSED_STRING, db_get_elo(), db_get_enum_codeset(), db_get_enum_collation(), db_get_enum_string(), db_get_set(), DB_IS_NULL, db_json_delete_doc(), db_make_enumeration(), db_private_free, db_private_free_and_init, db_set_compressed_string(), DB_TYPE_BIT, DB_TYPE_BLOB, DB_TYPE_CHAR, DB_TYPE_CLOB, DB_TYPE_ENUMERATION, DB_TYPE_JSON, DB_TYPE_MIDXKEY, DB_TYPE_MULTISET, DB_TYPE_NCHAR, DB_TYPE_OBJECT, DB_TYPE_SEQUENCE, DB_TYPE_SET, DB_TYPE_VARBIT, DB_TYPE_VARCHAR, DB_TYPE_VARNCHAR, DB_TYPE_VOBJ, DB_VALUE_DOMAIN_TYPE, db_json::document, elo_free_structure(), db_char::info, db_data::json, db_char::medium, db_data::midxkey, db_value::need_clear, NO_ERROR, NULL, db_data::op, PRIM_SET_NULL(), prm_get_bool_value(), PRM_ID_ORACLE_STYLE_EMPTY_STRING, QSTR_IS_ANY_CHAR_OR_BIT, db_json::schema_raw, db_data::set, and set_free().
Referenced by assign_null_value(), au_change_serial_owner(), au_check_serial_authorization(), au_delete_auth_of_dropping_table(), au_drop_user(), au_dump_to_file(), au_dump_user(), au_print_auth(), au_print_grant_entry(), au_set_new_auth(), au_set_user_comment(), au_user_name(), btree_advance_to_next_slot_and_fix_page(), btree_apply_key_range_and_filter(), btree_attrinfo_read_dbvalues(), btree_build_nleafs(), btree_check_valid_record(), btree_clear_key_value(), btree_coerce_key(), btree_delete_internal(), btree_find_split_point(), btree_first_oid(), btree_get_next_key_info(), btree_get_next_node_info(), btree_get_stats(), btree_get_stats_key(), btree_get_stats_midxkey(), btree_get_unique_statistics(), btree_ils_adjust_range(), btree_iss_set_key(), btree_key_insert_new_key(), btree_range_opt_check_add_index_key(), btree_recompress_record(), btree_rv_keyval_undo_online_index_tran_delete(), btree_rv_keyval_undo_online_index_tran_insert(), btree_set_split_point(), btree_sort_get_next(), btree_store_overflow_key(), btree_top_n_items_binary_search(), btree_verify_leaf_node(), catcls_apply_resolutions(), catcls_convert_attr_id_to_name(), catcls_find_oid_by_class_name(), catcls_free_or_value(), catcls_free_sub_value(), catcls_get_or_value_from_attribute(), catcls_get_or_value_from_indexes(), catcls_get_property_set(), check_default_on_update_clause(), classobj_cache_constraint_entry(), classobj_cache_constraint_list(), classobj_cache_constraints(), classobj_change_constraint_comment(), classobj_change_constraint_status(), classobj_check_function_constraint_info(), classobj_clear_attribute_value(), classobj_drop_foreign_key_ref(), classobj_drop_prop(), classobj_find_prop_constraint(), classobj_get_prop(), classobj_make_class_constraints(), classobj_make_foreign_key_info(), classobj_make_foreign_key_ref(), classobj_make_foreign_key_ref_list(), classobj_make_index_filter_pred_info(), classobj_make_index_filter_pred_seq(), classobj_print_props(), classobj_put_foreign_key_ref(), classobj_put_index(), classobj_put_prop(), classobj_put_value_and_iterate(), index_builder_loader_task::clear_keys(), cubscan::json_table::scanner::clear_node_columns(), cubxasl::json_table::column::clear_xasl(), regu_variable_node::clear_xasl_local(), col_delete(), compare_driver(), cursor_copy_vobj_to_dbvalue(), cursor_fixup_set_vobjs(), cursor_fixup_vobjs(), cursor_has_set_vobjs(), db_bigint_to_binary_string(), db_date_add_sub_interval_expr(), db_format(), db_json_convert_to_utf8(), db_like_bound(), db_string_concatenate(), db_string_convert_to(), db_string_insert_substring(), db_string_repeat(), db_string_replace(), db_string_substring_index(), db_string_truncate(), db_time_format(), db_trunc_dbval(), db_value_alloc_and_copy(), db_value_clear(), db_value_clear_array(), db_value_get(), db_value_to_json_doc(), db_value_to_json_key(), db_value_to_json_value(), desc_disk_to_obj(), desc_free(), object_printer::describe_attribute(), object_printer::describe_class(), object_printer::describe_comment(), db_value_printer::describe_midxkey(), object_printer::describe_partition_parts(), disk_to_attribute(), disk_to_partition_info(), do_alter_change_owner(), do_alter_one_clause_with_template(), do_alter_serial(), do_alter_trigger(), do_change_att_schema_only(), do_create_auto_increment_serial(), do_create_serial(), do_create_serial_internal(), do_drop_serial(), do_drop_session_variables(), do_evaluate(), do_evaluate_default_expr(), do_evaluate_insert_values(), do_find_unique_constraint_violations(), do_get_optimization_param(), do_get_prepared_statement_info(), do_get_serial_obj_id(), do_get_stats(), do_prepare_merge(), do_prepare_update(), do_set_optimization_param(), do_set_session_variables(), do_set_sys_params(), do_update_auto_increment_serial_on_rename(), do_update_maxvalue_of_auto_increment_serial(), domain_to_disk(), drop_stored_procedure(), eliminate_duplicated_keys(), emit_autoincrement_def(), emit_instance_attributes(), emit_stored_procedure_args(), eval_item_card_set(), eval_item_card_sort_list(), eval_key_filter(), eval_some_eval(), eval_some_list_eval(), eval_sub_multi_set_to_sort_list(), eval_sub_sort_list_to_multi_set(), eval_sub_sort_list_to_sort_list(), cubxasl::json_table::column::evaluate(), cubxasl::json_table::column::evaluate_extract(), fetch_copy_dbval(), fetch_peek_arith(), fetch_peek_dbval(), fetch_peek_dbval_pos(), fetch_val_list(), filter_local_constraints(), flatten_properties(), get_current_result(), heap_attrinfo_clear_dbvalues(), heap_attrinfo_generate_key(), heap_attrinfo_set(), heap_attrinfo_set_uninitialized(), heap_attrinfo_transform_to_disk_internal(), heap_attrvalue_get_key(), heap_attrvalue_read(), heap_classrepr_dump(), heap_eval_function_index(), heap_midxkey_key_generate(), heap_midxkey_key_get(), heap_object_upgrade_domain(), jsp_add_stored_procedure(), jsp_add_stored_procedure_argument(), jsp_alter_stored_procedure(), jsp_do_call_stored_procedure(), jsp_get_value_size(), jsp_pack_set_argument(), jsp_unpack_set_value(), la_free_repl_item(), la_get_current(), la_make_repl_item(), lang_db_put_charset(), locator_add_or_remove_index_internal(), locator_check_btree_entries(), locator_check_foreign_key(), locator_check_primary_key_delete(), locator_check_primary_key_update(), locator_check_unique_btree_entries(), locator_mvcc_reev_cond_assigns(), locator_prefetch_index_page_internal(), locator_repair_btree_by_delete(), locator_update_index(), log_repl_data_dump(), make_desired_string_db_value(), merge_key_ranges(), method_invoke_for_server(), method_receive_results_for_stand_alone(), mht_valhash(), mq_set_non_updatable_oid(), mr_cmpval_json(), mr_data_cmpdisk_json(), mr_data_lengthval_object(), mr_data_writeval_object(), obj_assign_value(), obj_copy(), obj_find_multi_attr(), obj_find_multi_desc(), obj_find_object_by_cons_and_key(), obt_assign(), online_index_builder(), or_class_get_partition_info(), or_get_current_representation(), or_get_enumeration(), or_get_json_schema(), or_get_set(), or_packed_enumeration_size(), or_packed_json_schema_length(), or_put_enumeration(), or_put_json_schema(), partition_load_partition_predicate(), partition_prune(), partition_prune_hash(), partition_prune_list(), partition_prune_partition_index(), partition_prune_range(), pr_clear_value_vector(), pr_complete_enum_value(), pr_free_ext_value(), pr_free_value(), pr_midxkey_compare_element(), PRIM_SET_NULL(), pt_check_alter_partition(), pt_check_enum_data_type(), pt_coerce_value_internal(), pt_db_value_initialize(), pt_eval_value_path(), pt_evaluate_db_value_expr(), pt_evaluate_function(), pt_evaluate_tree_internal(), pt_fold_const_expr(), pt_fold_const_function(), pt_get_query_limit_from_limit(), pt_get_query_limit_from_orderby_for(), pt_json_str_codeset_normalization(), pt_make_regu_constant(), pt_seq_value_to_db(), pt_set_host_variables(), pt_set_table_to_db(), pt_set_value_to_db(), pt_to_list_key(), pt_to_regu_variable(), pt_to_upd_del_query(), put_string(), qdata_add_dbval(), qdata_add_sequence_to_dbval(), qdata_aggregate_accumulator_to_accumulator(), qdata_aggregate_value_to_accumulator(), qdata_benchmark(), qdata_concatenate_dbval(), qdata_convert_dbvals_to_set(), qdata_convert_table_to_set(), qdata_copy_db_value(), qdata_copy_hscan_key_without_alloc(), qdata_evaluate_aggregate_hierarchy(), qdata_evaluate_aggregate_list(), qdata_evaluate_analytic_func(), qdata_evaluate_function(), qdata_evaluate_sys_connect_by_path(), qdata_finalize_aggregate_list(), qdata_finalize_analytic_func(), qdata_get_interpolation_function_result(), qdata_group_concat_first_value(), qdata_group_concat_value(), qdata_load_agg_hentry_from_tuple(), qdata_set_valptr_list_unbound(), qdata_set_value_list_to_null(), qdata_strcat_dbval(), qdata_tuple_to_values_array(), qexec_analytic_evaluate_interpolation_function(), qexec_analytic_evaluate_offset_function(), qexec_analytic_put_next(), qexec_analytic_sort_key_header_load(), qexec_analytic_start_group(), qexec_clear_access_spec_list(), qexec_clear_agg_list(), qexec_clear_analytic_function_list(), qexec_clear_analytic_function_state(), qexec_clear_arith_list(), qexec_clear_db_val_list(), qexec_clear_regu_var(), qexec_clear_topn_tuple(), qexec_clear_update_assignment(), qexec_clear_xasl(), qexec_clear_xasl_head(), qexec_cmp_tpl_vals_merge(), qexec_collection_has_null(), qexec_compare_valptr_with_tuple(), qexec_execute_build_columns(), qexec_execute_build_indexes(), qexec_execute_connect_by(), qexec_execute_delete(), qexec_execute_do_stmt(), qexec_execute_insert(), qexec_free_agg_hash_context(), qexec_gby_finalize_group(), qexec_gby_finalize_group_val_list(), qexec_get_orderbynum_upper_bound(), qexec_get_xasl_list_id(), qexec_groupby_index(), qexec_init_next_partition(), qexec_oid_of_duplicate_key_update(), qexec_remove_duplicates_for_replace(), qexec_reset_pseudocolumns_val_pointers(), qexec_resolve_domains_for_aggregation(), qexec_schema_get_type_desc(), qexec_setup_topn_proc(), qexec_upddel_add_unique_oid_to_ehid(), qfile_compare_tuple_values(), qfile_compare_with_interpolation_domain(), qfile_free_list_cache_entry(), qfile_locate_tuple_next_value(), qo_env_free(), qo_fold_is_and_not_null(), qo_reduce_equality_terms(), regu_make_constant_vid(), btree_insert_list::reset_boundary_keys(), save_previous_value(), sbtree_find_multi_uniques(), sbtree_find_unique_internal(), scan_close_scan(), scan_dbvals_to_midxkey(), scan_dump_key_into_tuple(), scan_end_scan(), scan_get_index_oidset(), scan_get_next_iss_value(), scan_init_iss(), scan_next_heap_scan(), scan_next_method_scan(), scan_next_set_scan(), serial_clear_value(), serial_update_cur_val_of_serial(), session_add_variable(), session_get_last_insert_id(), session_reset_cur_insert_id(), session_set_cur_insert_id(), session_state_uninit(), page_key_boundary::set_value(), setobj_add_element(), setobj_clear(), setobj_convert_oids_to_objects(), setobj_put_element(), showstmt_free_array_context(), showstmt_next_scan(), smt_add_constraint_to_property(), smt_change_class_shared_attribute_domain(), smt_drop_constraint_from_property(), smt_set_attribute_default(), smt_set_attribute_orig_default_value(), ssession_drop_session_variables(), ssession_get_session_variable(), ssession_set_session_variables(), stmt_destroyf(), stmt_prepare_internal(), tf_attribute_default_expr_to_property(), tp_set_compare(), tp_value_auto_cast(), tp_value_cast_internal(), tp_value_compare_with_error(), tp_value_str_auto_cast_to_number(), tr_set_comment(), cubxasl::json_table::column::trigger_on_empty(), cubxasl::json_table::column::trigger_on_error(), trigger_table_add(), trigger_table_drop(), trigger_table_find(), trigger_table_rename(), trigger_to_object(), update_at_server(), valcnv_convert_set_to_string(), valcnv_convert_value_to_string(), values_list_to_values_array(), vid_build_non_upd_object(), vid_fetch_instance(), vid_vobj_to_object(), ws_clear_internal(), ws_cull_mops(), ws_free_mop(), ws_rehash_vmop(), xbtree_load_index(), xlocator_check_fk_validity(), xlocator_remove_class_from_index(), xlocator_repl_force(), xqmgr_execute_query(), xqmgr_prepare_and_execute_query(), xserial_get_next_value_internal(), btree_insert_list::~btree_insert_list(), and page_key_boundary::~page_key_boundary().
void pr_clear_value_vector (std::vector< DB_VALUE > & value_vector)
Definition at line 2093 of file object_primitive.c.
References pr_clear_value().
Referenced by PRIM_SET_NULL(), and qdata_evaluate_aggregate_list().
int pr_clone_value (const DB_VALUE * src, DB_VALUE * dest)
Definition at line 2155 of file object_primitive.c.
References DB_IS_NULL, db_make_null(), db_value_domain_init(), DB_VALUE_DOMAIN_TYPE, DB_VALUE_PRECISION, DB_VALUE_SCALE, NO_ERROR, NULL, pr_type_from_id(), and pr_type::setval().
Referenced by assign_set_value(), btree_attrinfo_read_dbvalues(), btree_coerce_key(), btree_find_min_or_max_key(), btree_find_split_point(), btree_first_oid(), btree_get_next_key_info(), btree_get_next_node_info(), btree_get_prefix_separator(), btree_get_stats_midxkey(), btree_get_unique_statistics(), btree_ils_adjust_range(), btree_iss_set_key(), btree_key_insert_new_key(), btree_range_opt_check_add_index_key(), btree_range_scan_descending_fix_prev_leaf(), btree_recompress_record(), btree_set_split_point(), catcls_apply_resolutions(), catcls_convert_attr_id_to_name(), classobj_init_attribute(), copy_bind_value_to_tdes(), csession_get_variable(), db_datetime_to_timestamp(), db_least_or_greatest(), db_query_get_tuple_value(), db_string_concatenate(), db_string_elt(), db_string_insert_substring(), db_string_limit_size_string(), db_string_md5(), db_string_regexp_replace(), db_string_substring_index(), db_to_char(), db_value_alloc_and_copy(), db_value_clone(), db_value_copy(), do_drop_session_variables(), do_evaluate_default_expr(), do_find_unique_constraint_violations(), do_set_session_variables(), eval_key_filter(), fetch_peek_arith(), get_desc_old(), heap_attrinfo_generate_key(), heap_attrinfo_set_uninitialized(), heap_attrvalue_get_key(), heap_eval_function_index(), heap_object_upgrade_domain(), locator_check_primary_key_delete(), locator_check_primary_key_update(), locator_update_index(), obj_assign_value(), obj_get_value(), obt_assign(), partition_attrinfo_get_key(), partition_get_value_from_inarith(), partition_get_value_from_key(), partition_get_value_from_regu_var(), partition_prune_hash(), populate_defaults(), pr_copy_value(), pr_midxkey_unique_prefix(), PRIM_SET_NULL(), pt_evaluate_db_value_expr(), pt_evaluate_tree_internal(), pt_get_query_limit_from_orderby_for(), pt_rewrite_to_auto_param(), pt_set_host_variables(), pt_to_aggregate_node(), qdata_add_dbval(), qdata_aggregate_value_to_accumulator(), qdata_apply_interpolation_function_coercion(), qdata_copy_hscan_key_without_alloc(), qdata_elt(), qdata_evaluate_aggregate_hierarchy(), qdata_evaluate_aggregate_list(), qdata_evaluate_analytic_func(), qdata_evaluate_connect_by_root(), qdata_evaluate_sys_connect_by_path(), qdata_finalize_aggregate_list(), qdata_finalize_analytic_func(), qdata_group_concat_first_value(), qdata_group_concat_value(), qdata_load_agg_hvalue_in_agg_list(), qdata_subtract_timestampltz_to_dbval(), qdata_tuple_to_values_array(), qexec_analytic_evaluate_interpolation_function(), qexec_analytic_evaluate_offset_function(), qexec_execute_insert(), qexec_get_orderbynum_upper_bound(), qexec_groupby_index(), qexec_init_instnum_val(), qexec_schema_get_type_desc(), qexec_topn_tuples_to_list_id(), qfile_update_list_cache_entry(), save_previous_value(), scan_dbvals_to_midxkey(), scan_get_next_iss_value(), scan_regu_key_to_index_key(), serial_get_next_cached_value(), serial_set_cache_entry(), serial_update_cur_val_of_serial(), session_define_variable(), session_get_last_insert_id(), session_get_trace_stats(), session_get_variable(), session_set_cur_insert_id(), page_key_boundary::set_value(), setobj_copy(), setobj_get_element(), showstmt_array_next_scan(), smt_change_class_shared_attribute_domain(), smt_set_attribute_default(), smt_set_attribute_orig_default_value(), stmt_add_batch_param(), tp_value_cast_internal(), tp_value_coerce_strict(), cubxasl::json_table::column::trigger_on_empty(), cubxasl::json_table::column::trigger_on_error(), value_to_db_value(), values_list_to_values_array(), vid_fetch_instance(), ws_rehash_vmop(), ws_vmop(), xserial_get_current_value(), xserial_get_next_value(), and xserial_get_next_value_internal().
int pr_complete_enum_value (DB_VALUE * value, struct tp_domain * domain)
Definition at line 9762 of file object_primitive.c.
References db_get_enum_collation(), DB_GET_ENUM_ELEM_CODESET, DB_GET_ENUM_ELEM_SHORT, DB_GET_ENUM_ELEM_STRING, DB_GET_ENUM_ELEM_STRING_SIZE, db_get_enum_short(), db_get_enum_string(), db_get_enum_string_size(), DB_IS_NULL, db_make_enumeration(), db_private_alloc, DB_TYPE_ENUMERATION, DOM_GET_ENUM_ELEM, DOM_GET_ENUM_ELEMS_COUNT, db_value::domain, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, db_domain_info::general_info, pr_type::id, db_value::need_clear, NO_ERROR, NULL, pr_clear_value(), tp_domain::type, and db_domain_info::general_info::type.
Referenced by disk_to_attribute(), and PRIM_SET_NULL().
DB_VALUE* pr_copy_value (DB_VALUE * value)
Definition at line 2208 of file object_primitive.c.
References NO_ERROR, NULL, pr_clone_value(), pr_free_value(), and pr_make_value().
Referenced by PRIM_SET_NULL(), qdata_copy_agg_hkey(), qdata_copy_hscan_key(), and qo_merge_range_helper().
int pr_data_compress_string (const char * string, int str_length, char * compressed_string, int compress_buffer_size, int * compressed_length)
Definition at line 16341 of file object_primitive.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_IO_LZ4_COMPRESS_FAIL, er_set(), fileio_get_zip_level_string(), fileio_get_zip_method_string(), FILEIO_ZIP_LZ4_DEFAULT_LEVEL, FILEIO_ZIP_LZ4_METHOD, NO_ERROR, NULL, OR_IS_STRING_LENGTH_COMPRESSABLE, and pr_Enable_string_compression.
Referenced by pr_do_db_value_string_compression(), and PRIM_SET_NULL().
void pr_data_writeval (struct or_buf * buf, DB_VALUE * value)
Definition at line 9705 of file object_primitive.c.
References pr_type::data_writeval(), DB_VALUE_DOMAIN_TYPE, NULL, pr_type_from_id(), and tp_Type_null.
Referenced by PRIM_SET_NULL(), and put_attributes().
int pr_data_writeval_disk_size (DB_VALUE * value)
Definition at line 9660 of file object_primitive.c.
References assert, DB_VALUE_DOMAIN_TYPE, pr_type::get_disk_size_of_value(), NULL, and pr_type_from_id().
Referenced by fetch_peek_arith(), heap_attrinfo_get_disksize(), object_disk_size(), PRIM_SET_NULL(), pt_evaluate_db_value_expr(), put_varinfo(), qdata_copy_db_value_to_tuple_value(), qdata_evaluate_aggregate_list(), qdata_evaluate_analytic_func(), qfile_fast_intval_tuple_to_list(), qfile_fast_val_tuple_to_list(), vid_db_value_size(), and vid_pack_db_value().
int pr_do_db_value_string_compression (DB_VALUE * value)
Definition at line 16444 of file object_primitive.c.
References ARG_FILE_LINE, ASSERT_ERROR, db_data::ch, db_char::compressed_buf, db_char::compressed_size, db_value::data, db_get_string(), db_get_string_size(), DB_IS_NULL, db_private_alloc, db_private_free_and_init, db_set_compressed_string(), DB_TYPE_VARCHAR, DB_TYPE_VARNCHAR, DB_VALUE_DOMAIN_TYPE, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), db_char::medium, NO_ERROR, NULL, OR_IS_STRING_LENGTH_COMPRESSABLE, pr_data_compress_string(), pr_Enable_string_compression, and rc.
Referenced by mr_lengthval_string_internal(), mr_lengthval_varnchar_internal(), mr_writeval_string_internal(), mr_writeval_varnchar_internal(), and PRIM_SET_NULL().
PR_TYPE* pr_find_type (const char * name)
Definition at line 8853 of file object_primitive.c.
References DB_TYPE_FIRST, DB_TYPE_LAST, i, intl_mbs_casecmp(), pr_type::name, NULL, tp_Type_integer, tp_Type_multiset, tp_Type_sequence, tp_Type_short, tp_Type_string, and tp_Type_utime.
Referenced by db_create_vclass(), db_type_from_string(), def_class_internal(), get_domain_internal(), and PRIM_SET_NULL().
int pr_free_ext_value (DB_VALUE * value)
Definition at line 2132 of file object_primitive.c.
References area_free(), error(), NO_ERROR, NULL, and pr_clear_value().
Referenced by catcls_get_or_value_from_indexes(), check_args(), check_att_domain(), cleanup_argstate(), db_value_free(), db_value_list_finddel(), heap_attrinfo_set_uninitialized(), locator_update_index(), obj_set_att(), obj_set_shared(), obt_assign(), obt_check_assignment(), obt_free_assignment(), partition_range_min_max(), PRIM_SET_NULL(), pt_check_alter_partition(), pt_evaluate_tree_internal(), qdata_evaluate_sys_connect_by_path(), smt_change_attribute_w_dflt_w_order(), smt_change_class_shared_attribute_domain(), and smt_set_attribute_default().
int pr_free_value (DB_VALUE * value)
Definition at line 2109 of file object_primitive.c.
References db_private_free_and_init, error(), NO_ERROR, NULL, and pr_clear_value().
Referenced by pr_copy_value(), PRIM_SET_NULL(), qdata_free_agg_hkey(), qdata_free_agg_hvalue(), qdata_free_hscan_key(), and qo_merge_range_helper().
int pr_get_compressed_data_from_buffer (struct or_buf * buf, char * data, int compressed_size, int expected_decompressed_size)
Definition at line 15967 of file object_primitive.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_IO_LZ4_DECOMPRESS_FAIL, er_set(), NO_ERROR, or_get_data(), or_buf::ptr, and rc.
Referenced by bf2df_str_cmpdisk(), mr_data_cmpdisk_string(), mr_data_cmpdisk_varnchar(), mr_data_readmem_string(), mr_readval_string_internal(), mr_readval_varnchar_internal(), or_get_attr_string(), and PRIM_SET_NULL().
int pr_get_compression_length (const char * string, int str_length)
Definition at line 16010 of file object_primitive.c.
References ARG_FILE_LINE, assert, cleanup(), ER_ERROR_SEVERITY, ER_IO_LZ4_COMPRESS_FAIL, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), fileio_get_zip_level_string(), fileio_get_zip_method_string(), FILEIO_ZIP_LZ4_DEFAULT_LEVEL, FILEIO_ZIP_LZ4_METHOD, free_and_init, NO_ERROR, NULL, OR_MINIMUM_STRING_LENGTH_FOR_COMPRESSION, pr_Enable_string_compression, and rc.
Referenced by mr_data_lengthmem_string(), mr_data_lengthmem_varnchar(), and PRIM_SET_NULL().
int pr_get_size_and_write_string_to_buffer (struct or_buf * buf, char * val_p, DB_VALUE * value, int * val_size, int align)
Definition at line 16083 of file object_primitive.c.
References ARG_FILE_LINE, assert, cleanup(), db_get_string(), db_get_string_size(), DB_TYPE_STRING, DB_TYPE_VARCHAR, DB_TYPE_VARNCHAR, DB_VALUE_DOMAIN_TYPE, ER_ERROR_SEVERITY, ER_FAILED, ER_IO_LZ4_COMPRESS_FAIL, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), ER_TF_BUFFER_OVERFLOW, or_buf::error_abort, fileio_get_zip_level_string(), fileio_get_zip_method_string(), FILEIO_ZIP_LZ4_DEFAULT_LEVEL, FILEIO_ZIP_LZ4_METHOD, free_and_init, NO_ERROR, NULL, OR_MINIMUM_STRING_LENGTH_FOR_COMPRESSION, or_overflow(), or_packed_varchar_length(), pr_Enable_string_compression, pr_write_compressed_string_to_buffer(), PRIM_TEMPORARY_DISK_SIZE, and rc.
Referenced by PRIM_SET_NULL().
int pr_index_writeval_disk_size (DB_VALUE * value)
Definition at line 9686 of file object_primitive.c.
References assert, DB_VALUE_DOMAIN_TYPE, pr_type::get_index_size_of_value(), NULL, and pr_type_from_id().
Referenced by btree_get_disk_size_of_key(), pr_midxkey_get_vals_size(), and PRIM_SET_NULL().
int pr_is_prefix_key_type (DB_TYPE type)
Definition at line 8808 of file object_primitive.c.
References DB_TYPE_MIDXKEY, and pr_is_string_type().
Referenced by btree_build_nleafs(), and PRIM_SET_NULL().
bool pr_is_set_type (DB_TYPE type)
Definition at line 8776 of file object_primitive.c.
References DB_TYPE_VOBJ, and TP_IS_SET_TYPE.
Referenced by btree_keyoid_checkscan_check(), catcls_expand_or_value_by_subset(), class_referenced_by_domain(), compare_domains(), cursor_fixup_set_vobjs(), db_domain_set(), fetch_val_list(), heap_classrepr_dump(), PRIM_SET_NULL(), pt_check_and_replace_hostvar(), pt_make_regu_constant(), qdata_generate_tuple_desc_for_valptr_list(), qexec_cmp_tpl_vals_merge(), qexec_collection_has_null(), qexec_compare_valptr_with_tuple(), qexec_get_attr_default(), qfile_compare_tuple_values(), qfile_locate_tuple_next_value(), setof_mop_to_setof_vobj(), smt_add_set_argument_domain(), smt_add_set_attribute_domain(), smt_delete_set_attribute_domain(), tp_domain_filter_list(), and vid_compare_non_updatable_objects().
int pr_is_string_type (DB_TYPE type)
Definition at line 8788 of file object_primitive.c.
References DB_TYPE_BIT, DB_TYPE_CHAR, DB_TYPE_NCHAR, DB_TYPE_VARBIT, DB_TYPE_VARCHAR, and DB_TYPE_VARNCHAR.
Referenced by btree_get_prefix_separator(), btree_store_overflow_key(), fetch_peek_dbval(), pr_is_prefix_key_type(), PRIM_SET_NULL(), qdata_get_tuple_value_size_from_dbval(), and qfile_unify_types().
int pr_is_variable_type (DB_TYPE id)
Definition at line 8826 of file object_primitive.c.
References NULL, pr_type_from_id(), and pr_type::variable_p.
Referenced by fetch_peek_dbval(), PRIM_SET_NULL(), qfile_unify_types(), and tf_compile_meta_classes().
DB_VALUE* pr_make_ext_value (void)
Definition at line 1888 of file object_primitive.c.
References area_alloc(), DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, DB_TYPE_NULL, db_value_domain_init(), and NULL.
Referenced by check_args(), check_att_domain(), db_object_fetch(), db_value_copy(), db_value_create(), locator_update_index(), obt_apply_assignments(), obt_assign(), obt_check_assignment(), populate_auto_increment(), populate_defaults(), PRIM_SET_NULL(), smt_change_attribute_w_dflt_w_order(), smt_change_class_shared_attribute_domain(), and smt_set_attribute_default().
DB_VALUE* pr_make_value (void)
Definition at line 1865 of file object_primitive.c.
References DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_private_alloc, DB_TYPE_NULL, db_value_domain_init(), and NULL.
Referenced by pr_copy_value(), PRIM_SET_NULL(), qdata_alloc_agg_hkey(), qdata_alloc_agg_hvalue(), qdata_alloc_hscan_key(), and qdata_copy_hscan_key().
int pr_mem_size (const PR_TYPE * type)
Definition at line 8931 of file object_primitive.c.
References pr_type::size.
Referenced by PRIM_SET_NULL(), and pt_find_size_from_dbtype().
int pr_midxkey_add_elements (DB_VALUE * keyval, DB_VALUE * dbvals, int num_dbvals, struct tp_domain * dbvals_domain_list)
Definition at line 9551 of file object_primitive.c.
References assert, db_midxkey::buf, or_buf::buffer, CAST_BUFLEN, db_get_midxkey(), DB_IS_NULL, db_private_alloc, db_private_free_and_init, ER_FAILED, error(), i, db_midxkey::ncolumns, tp_domain::next, NO_ERROR, NULL, or_advance(), OR_ENABLE_BOUND_BIT, or_init(), OR_MULTI_BOUND_BIT_BYTES, or_put_data(), pr_midxkey_get_vals_size(), pr_midxkey_init_boundbits(), or_buf::ptr, and db_midxkey::size.
Referenced by btree_coerce_key(), btree_ils_adjust_range(), and PRIM_SET_NULL().
int pr_midxkey_add_prefix (DB_VALUE * result, DB_VALUE * prefix, DB_VALUE * postfix, int n_prefix)
Definition at line 9111 of file object_primitive.c.
References assert, db_midxkey::buf, db_get_midxkey(), db_make_midxkey(), db_private_alloc, DB_TYPE_MIDXKEY, DB_VALUE_TYPE, db_midxkey::domain, i, MIN_COLUMN, db_midxkey::min_max_val, db_midxkey::ncolumns, db_value::need_clear, NO_ERROR, NULL, OR_MULTI_ATT_IS_BOUND, OR_MULTI_CLEAR_BOUND_BIT, OR_MULTI_ENABLE_BOUND_BIT, special_column::position, pr_midxkey_get_element_offset(), db_midxkey::size, and special_column::type.
Referenced by btree_read_record(), btree_recompress_record(), btree_verify_leaf_node(), and PRIM_SET_NULL().
int pr_midxkey_common_prefix (DB_VALUE * key1, DB_VALUE * key2)
Definition at line 9200 of file object_primitive.c.
References assert, db_get_midxkey(), DB_TYPE_MIDXKEY, DB_UNK, DB_VALUE_TYPE, NULL, and pr_midxkey_compare().
Referenced by btree_merge_node(), btree_node_common_prefix(), and PRIM_SET_NULL().
DB_VALUE_COMPARE_RESULT pr_midxkey_compare (DB_MIDXKEY * mul1, DB_MIDXKEY * mul2, int do_coercion, int total_order, int num_index_term, int * start_colp, int * result_size1, int * result_size2, int * diff_column, bool * dom_is_desc, bool * next_dom_is_desc)
Definition at line 7775 of file object_primitive.c.
References ARG_FILE_LINE, assert, db_midxkey::buf, DB_EQ, DB_GT, DB_LT, DB_TYPE_MIDXKEY, DB_UNK, db_midxkey::domain, ER_ERROR_SEVERITY, ER_MR_NULL_DOMAIN, er_set(), i, tp_domain::is_desc, MAX_COLUMN, MIN_COLUMN, db_midxkey::min_max_val, db_midxkey::ncolumns, tp_domain::next, NULL, OR_MULTI_ATT_IS_BOUND, OR_MULTI_BOUND_BIT_BYTES, special_column::position, pr_midxkey_compare_element(), pr_midxkey_element_disk_size(), tp_domain::precision, tp_domain::setdomain, tp_domain_match(), TP_DOMAIN_TYPE, TP_EXACT_MATCH, and special_column::type.
Referenced by btree_compare_key(), mr_cmpval_midxkey(), mr_index_cmpdisk_midxkey(), pr_midxkey_common_prefix(), pr_midxkey_unique_prefix(), PRIM_SET_NULL(), and scan_key_compare().
static DB_VALUE_COMPARE_RESULT pr_midxkey_compare_element (char * mem1, char * mem2, TP_DOMAIN * dom1, TP_DOMAIN * dom2, int do_coercion, int total_order) static
Definition at line 7719 of file object_primitive.c.
References assert, clean_up(), db_make_null(), DB_NEED_CLEAR, DB_UNK, error(), pr_type::index_readval(), tp_domain::is_desc, NO_ERROR, NULL, OR_BUF_INIT, pr_clear_value(), tp_value_compare_with_error(), and tp_domain::type.
Referenced by pr_type::get_cmpval_function(), and pr_midxkey_compare().
int pr_midxkey_element_disk_size (char * mem, DB_DOMAIN * domain)
Definition at line 8990 of file object_primitive.c.
References assert, pr_type::get_index_size_of_mem(), QSTR_IS_VARIABLE_LENGTH, TP_DOMAIN_TYPE, tp_domain::type, and pr_type::variable_p.
Referenced by compare_driver(), mr_index_lengthmem_midxkey(), pr_midxkey_compare(), pr_midxkey_get_element_internal(), pr_midxkey_get_element_offset(), and PRIM_SET_NULL().
static int pr_midxkey_get_element_internal (const DB_MIDXKEY * midxkey, int index, DB_VALUE * value, bool copy, int * prev_indexp, char ** prev_ptrp) static
Definition at line 9238 of file object_primitive.c.
References assert, db_midxkey::buf, CAST_BUFLEN, db_make_null(), db_midxkey::domain, error(), i, db_midxkey::ncolumns, tp_domain::next, NO_ERROR, NULL, or_advance(), or_init(), OR_MULTI_ATT_IS_UNBOUND, OR_MULTI_BOUND_BIT_BYTES, pr_midxkey_element_disk_size(), tp_domain::precision, or_buf::ptr, tp_domain::setdomain, and db_midxkey::size.
Referenced by pr_type::get_cmpval_function(), and pr_midxkey_get_element_nocopy().
int pr_midxkey_get_element_nocopy (const DB_MIDXKEY * midxkey, int index, DB_VALUE * value, int * prev_indexp, char ** prev_ptrp)
Definition at line 9508 of file object_primitive.c.
References pr_midxkey_get_element_internal().
Referenced by btree_apply_key_range_and_filter(), btree_attrinfo_read_dbvalues(), btree_get_stats_midxkey(), btree_get_unique_statistics(), btree_ils_adjust_range(), btree_range_opt_check_add_index_key(), btree_top_n_items_binary_search(), db_value_printer::describe_midxkey(), eval_key_filter(), mht_valhash(), PRIM_SET_NULL(), scan_get_next_iss_value(), and sl_print_midxkey().
int pr_midxkey_get_element_offset (const DB_MIDXKEY * midxkey, int index)
Definition at line 9037 of file object_primitive.c.
References assert, db_midxkey::buf, or_buf::buffer, CAST_BUFLEN, db_midxkey::domain, error(), i, db_midxkey::ncolumns, tp_domain::next, NO_ERROR, or_advance(), or_init(), OR_MULTI_ATT_IS_UNBOUND, OR_MULTI_BOUND_BIT_BYTES, pr_midxkey_element_disk_size(), tp_domain::precision, or_buf::ptr, tp_domain::setdomain, and db_midxkey::size.
Referenced by btree_node_size_uncompressed(), pr_midxkey_add_prefix(), pr_midxkey_remove_prefix(), and PRIM_SET_NULL().
static int pr_midxkey_get_vals_size (TP_DOMAIN * domains, DB_VALUE * dbvals, int total) static
Definition at line 9011 of file object_primitive.c.
References DB_IS_NULL, i, tp_domain::next, and pr_index_writeval_disk_size().
Referenced by pr_type::get_cmpval_function(), and pr_midxkey_add_elements().
int pr_midxkey_init_boundbits (char * bufptr, int n_atts)
Definition at line 9524 of file object_primitive.c.
References i, and OR_MULTI_BOUND_BIT_BYTES.
Referenced by heap_midxkey_key_generate(), heap_midxkey_key_get(), pr_midxkey_add_elements(), and PRIM_SET_NULL().
int pr_midxkey_remove_prefix (DB_VALUE * key, int prefix)
Definition at line 9170 of file object_primitive.c.
References db_midxkey::buf, db_get_midxkey(), i, NO_ERROR, OR_MULTI_CLEAR_BOUND_BIT, pr_midxkey_get_element_offset(), and db_midxkey::size.
Referenced by btree_compress_node(), btree_key_insert_new_key(), btree_recompress_record(), and PRIM_SET_NULL().
int pr_midxkey_unique_prefix (const DB_VALUE * db_midxkey1, const DB_VALUE * db_midxkey2, DB_VALUE * db_result)
Definition at line 9386 of file object_primitive.c.
References assert, db_midxkey::buf, DB_EQ, db_get_midxkey(), DB_GT, DB_LT, db_make_midxkey(), db_private_alloc, DB_UNK, db_midxkey::domain, er_errid(), ER_FAILED, i, MIN_COLUMN, db_midxkey::min_max_val, db_midxkey::ncolumns, db_value::need_clear, NO_ERROR, NULL, OR_MULTI_ATT_IS_UNBOUND, OR_MULTI_CLEAR_BOUND_BIT, special_column::position, pr_clone_value(), pr_midxkey_compare(), tp_domain::setdomain, pr_type::size, db_midxkey::size, and special_column::type.
Referenced by btree_get_prefix_separator(), and PRIM_SET_NULL().
PR_TYPE* pr_type_from_id (DB_TYPE id)
Definition at line 8731 of file object_primitive.c.
References DB_TYPE_LAST, DB_TYPE_TABLE, and NULL.
Referenced by btree_set_unknown_key_error(), catcls_get_or_value_from_domain(), cursor_copy_vobj_to_dbvalue(), disk_to_attribute(), disk_to_metharg(), emit_domain_def(), get_desc_old(), get_old(), heap_attrinfo_set(), heap_attrvalue_read(), heap_classrepr_dump(), locator_update_index(), or_pack_mem_value(), or_packed_value_size(), or_put_value(), pr_clone_value(), pr_data_writeval(), pr_data_writeval_disk_size(), pr_index_writeval_disk_size(), pr_is_variable_type(), pr_type_name(), pr_value_mem_size(), PRIM_SET_NULL(), pt_find_size_from_dbtype(), pt_get_src_domain(), pt_set_domain_class(), qdata_calculate_aggregate_cume_dist_percent_rank(), qdata_convert_table_to_set(), qdata_copy_db_value(), qdata_copy_db_value_to_tuple_value(), qdata_evaluate_aggregate_list(), qdata_evaluate_analytic_func(), qdata_finalize_aggregate_list(), qdata_finalize_analytic_func(), qdata_get_tuple_value_size_from_dbval(), qexec_get_attr_default(), qfile_fast_intval_tuple_to_list(), qfile_fast_val_tuple_to_list(), sm_att_type_id(), tp_domain_init(), and tp_value_compare_with_error().
const char* pr_type_name (DB_TYPE id)
Definition at line 8752 of file object_primitive.c.
References pr_type::name, NULL, and pr_type_from_id().
Referenced by allocate_index(), btree_compare_key(), btree_dump_root_header(), cnv_bad_char(), col_new(), db_bit_string(), db_conv(), db_get_type_name(), db_round_dbval(), db_string_unique_prefix(), db_string_value(), db_to_number(), db_typeof_dbval(), db_value_to_json_doc(), export_serial(), fetch_peek_arith(), heap_attrinfo_dump(), heap_classrepr_dump(), key_type_to_string(), numeric_coerce_string_to_num(), numeric_common_prec_scale(), numeric_db_value_add(), numeric_db_value_div(), numeric_db_value_sub(), PRIM_SET_NULL(), cubload::server_object_loader::process_collection_constant(), cubload::server_object_loader::process_generic_constant(), pt_make_regu_hostvar(), pt_value_to_db(), qdata_copy_hscan_key(), qdata_copy_hscan_key_without_alloc(), sm_load_online_index(), smt_add_constraint(), cubload::to_db_bigint(), cubload::to_db_generic_char(), cubload::to_db_int(), cubload::to_db_monetary(), cubload::to_db_short(), cubload::to_int_generic(), tp_domain_status_er_set(), tp_dtoa(), tp_ftoa(), tp_value_compare_with_error(), tp_value_domain_name(), and cubxasl::json_table::column::trigger_on_error().
char* pr_valstring (const DB_VALUE * val)
Definition at line 9736 of file object_primitive.c.
References BUFFER_SIZE, DB_IS_NULL, db_sprint_value(), NULL, cubmem::PRIVATE_BLOCK_ALLOCATOR, and string_buffer::release_ptr().
Referenced by btree_check_foreign_key(), btree_fix_root_for_delete(), btree_fix_root_for_insert(), btree_key_lock_and_append_object_unique(), btree_load_check_fk(), btree_rv_record_modify_internal(), btree_set_error(), btree_set_unknown_key_error(), event_log_bind_values(), locator_check_btree_entries(), locator_check_foreign_key(), locator_check_unique_btree_entries(), PRIM_SET_NULL(), qfile_delete_list_cache_entry(), qfile_update_list_cache_entry(), and xqmgr_execute_query().
int pr_value_mem_size (const DB_VALUE * value)
Definition at line 8964 of file object_primitive.c.
References assert, DB_VALUE_DOMAIN_TYPE, pr_type::get_mem_size_of_value(), NULL, and pr_type_from_id().
Referenced by classobj_attribute_size(), PRIM_SET_NULL(), qdata_get_agg_hkey_size(), and qdata_get_agg_hvalue_size().
static int pr_write_compressed_string_to_buffer (OR_BUF * buf, const char * compressed_string, int compressed_length, int decompressed_length, int alignment) static
Definition at line 16216 of file object_primitive.c.
References assert, INT_ALIGNMENT, NO_ERROR, OR_INT_SIZE, OR_MINIMUM_STRING_LENGTH_FOR_COMPRESSION, or_put_align32(), or_put_byte(), or_put_data(), OR_PUT_INT, and rc.
Referenced by pr_type::get_cmpval_function(), mr_writeval_string_internal(), mr_writeval_varnchar_internal(), and pr_get_size_and_write_string_to_buffer().
static int pr_write_uncompressed_string_to_buffer (OR_BUF * buf, const char * string, int size, int align) static
Definition at line 16293 of file object_primitive.c.
References assert, INT_ALIGNMENT, NO_ERROR, OR_MINIMUM_STRING_LENGTH_FOR_COMPRESSION, or_put_align32(), or_put_byte(), or_put_data(), and rc.
Referenced by pr_type::get_cmpval_function(), mr_writeval_string_internal(), and mr_writeval_varnchar_internal().
static int readval_elo_with_type (OR_BUF * buf, DB_VALUE * value, TP_DOMAIN * domain, int size, bool copy, char * copy_buf, int copy_buf_len, DB_TYPE type) static
Definition at line 6024 of file object_primitive.c.
References db_make_elo(), db_private_free_and_init, mr_data_readmem_elo(), db_value::need_clear, NO_ERROR, NULL, or_advance(), peekmem_elo(), and rc.
Referenced by pr_type::get_cmpval_function(), mr_data_readval_blob(), and mr_data_readval_clob().
static int setval_elo_with_type (DB_VALUE * dest, const DB_VALUE * src, bool copy, DB_TYPE type) static
Definition at line 5765 of file object_primitive.c.
References db_get_elo(), DB_IS_NULL, db_make_elo(), db_make_null(), elo_copy_structure(), db_value::need_clear, NO_ERROR, and NULL.
Referenced by pr_type::get_cmpval_function(), mr_setval_blob(), and mr_setval_clob().
Variable Documentation
unsigned int db_on_server
Definition at line 91 of file network_interface_cl.c.
Referenced by mr_data_lengthval_nchar(), mr_data_readval_object(), mr_data_writeval_object(), mr_initval_object(), mr_lengthval_varnchar_internal(), mr_readval_nchar_internal(), mr_readval_varnchar_internal(), mr_setval_object(), mr_writeval_nchar_internal(), and mr_writeval_varnchar_internal().
int pr_Enable_string_compression = true
Definition at line 949 of file object_primitive.c.
Referenced by boot_restart_client(), boot_restart_server(), or_put_varchar_internal(), pr_data_compress_string(), pr_do_db_value_string_compression(), pr_get_compression_length(), and pr_get_size_and_write_string_to_buffer().
int pr_Inhibit_oid_promotion = PR_INHIBIT_OID_PROMOTION_DEFAULT
Definition at line 947 of file object_primitive.c.
Referenced by desc_disk_to_obj(), mr_data_readval_object(), mr_data_writeval_object(), and PRIM_SET_NULL().
PR_TYPE tp_Bigint
Initial value:
= {
  "bigint", DB_TYPE_BIGINT, 0, sizeof (DB_BIGINT), sizeof (DB_BIGINT), 4,
  mr_initmem_bigint,
  mr_initval_bigint,
  mr_setmem_bigint,
  mr_getmem_bigint,
  mr_setval_bigint,
  NULL,
  NULL,
  mr_data_writemem_bigint,
  mr_data_readmem_bigint,
  mr_data_writeval_bigint,
  mr_data_readval_bigint,
  NULL,
  NULL,
  mr_index_writeval_bigint,
  mr_index_readval_bigint,
  mr_index_cmpdisk_bigint,
  NULL,
  mr_data_cmpdisk_bigint,
  mr_cmpval_bigint
}
Definition at line 1025 of file object_primitive.c.
PR_TYPE tp_Bit
Initial value:
= {
  "bit", DB_TYPE_BIT, 0, 0, 0, 1,
  mr_initmem_bit,
  mr_initval_bit,
  mr_setmem_bit,
  mr_getmem_bit,
  mr_setval_bit,
  mr_data_lengthmem_bit,
  mr_data_lengthval_bit,
  mr_data_writemem_bit,
  mr_data_readmem_bit,
  mr_data_writeval_bit,
  mr_data_readval_bit,
  mr_index_lengthmem_bit,
  mr_index_lengthval_bit,
  mr_index_writeval_bit,
  mr_index_readval_bit,
  mr_index_cmpdisk_bit,
  mr_freemem_bit,
  mr_data_cmpdisk_bit,
  mr_cmpval_bit
}
Definition at line 14970 of file object_primitive.c.
Referenced by db_string_truncate().
PR_TYPE tp_Blob
Initial value:
= {
  "blob", DB_TYPE_BLOB, 1, sizeof (DB_ELO *), 0, 8,
  mr_initmem_elo,
  mr_initval_blob,
  mr_setmem_elo,
  mr_getmem_blob,
  mr_setval_blob,
  mr_data_lengthmem_elo,
  mr_data_lengthval_elo,
  mr_data_writemem_elo,
  mr_data_readmem_elo,
  mr_data_writeval_elo,
  mr_data_readval_blob,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  mr_freemem_elo,
  mr_data_cmpdisk_elo,
  mr_cmpval_elo
}
Definition at line 1385 of file object_primitive.c.
PR_TYPE tp_Char
Initial value:
= {
  "character", DB_TYPE_CHAR, 0, 0, 0, 1,
  mr_initmem_char,
  mr_initval_char,
  mr_setmem_char,
  mr_getmem_char,
  mr_setval_char,
  mr_data_lengthmem_char,
  mr_data_lengthval_char,
  mr_data_writemem_char,
  mr_data_readmem_char,
  mr_data_writeval_char,
  mr_data_readval_char,
  mr_index_lengthmem_char,
  mr_index_lengthval_char,
  mr_index_writeval_char,
  mr_index_readval_char,
  mr_index_cmpdisk_char,
  mr_freemem_char,
  mr_data_cmpdisk_char,
  mr_cmpval_char
}
Definition at line 12114 of file object_primitive.c.
Referenced by db_string_truncate().
PR_TYPE tp_Clob
Initial value:
= {
  "clob", DB_TYPE_CLOB, 1, sizeof (DB_ELO *), 0, 8,
  mr_initmem_elo,
  mr_initval_clob,
  mr_setmem_elo,
  mr_getmem_clob,
  mr_setval_clob,
  mr_data_lengthmem_elo,
  mr_data_lengthval_elo,
  mr_data_writemem_elo,
  mr_data_readmem_elo,
  mr_data_writeval_elo,
  mr_data_readval_clob,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  mr_freemem_elo,
  mr_data_cmpdisk_elo,
  mr_cmpval_elo
}
Definition at line 1410 of file object_primitive.c.
PR_TYPE tp_Date
Initial value:
= {
  "date", DB_TYPE_DATE, 0, sizeof (DB_DATE), OR_DATE_SIZE, 4,
  mr_initmem_date,
  mr_initval_date,
  mr_setmem_date,
  mr_getmem_date,
  mr_setval_date,
  NULL,
  NULL,
  mr_data_writemem_date,
  mr_data_readmem_date,
  mr_data_writeval_date,
  mr_data_readval_date,
  NULL,
  NULL,
  mr_index_writeval_date,
  mr_index_readval_date,
  mr_index_cmpdisk_date,
  NULL,
  mr_data_cmpdisk_date,
  mr_cmpval_date
}
Definition at line 1302 of file object_primitive.c.
PR_TYPE tp_Datetime
Initial value:
= {
  "datetime", DB_TYPE_DATETIME, 0, sizeof (DB_DATETIME), OR_DATETIME_SIZE, 4,
  mr_initmem_datetime,
  mr_initval_datetime,
  mr_setmem_datetime,
  mr_getmem_datetime,
  mr_setval_datetime,
  NULL,
  NULL,
  mr_data_writemem_datetime,
  mr_data_readmem_datetime,
  mr_data_writeval_datetime,
  mr_data_readval_datetime,
  NULL,
  NULL,
  mr_index_writeval_datetime,
  mr_index_readval_datetime,
  mr_index_cmpdisk_datetime,
  NULL,
  mr_data_cmpdisk_datetime,
  mr_cmpval_datetime
}
Definition at line 1200 of file object_primitive.c.
PR_TYPE tp_Datetimeltz
Initial value:
= {
  "datetimeltz", DB_TYPE_DATETIMELTZ, 0, sizeof (DB_DATETIME), OR_DATETIME_SIZE, 4,
  mr_initmem_datetime,
  mr_initval_datetimeltz,
  mr_setmem_datetime,
  mr_getmem_datetimeltz,
  mr_setval_datetimeltz,
  NULL,
  NULL,
  mr_data_writemem_datetime,
  mr_data_readmem_datetime,
  mr_data_writeval_datetime,
  mr_data_readval_datetimeltz,
  NULL,
  NULL,
  mr_index_writeval_datetime,
  mr_index_readval_datetimeltz,
  mr_index_cmpdisk_datetime,
  NULL,
  mr_data_cmpdisk_datetime,
  mr_cmpval_datetime
}
Definition at line 1252 of file object_primitive.c.
PR_TYPE tp_Datetimetz
Initial value:
= {
  "datetimetz", DB_TYPE_DATETIMETZ, 0, sizeof (DB_DATETIMETZ), OR_DATETIMETZ_SIZE, 4,
  mr_initmem_datetimetz,
  mr_initval_datetimetz,
  mr_setmem_datetimetz,
  mr_getmem_datetimetz,
  mr_setval_datetimetz,
  NULL,
  NULL,
  mr_data_writemem_datetimetz,
  mr_data_readmem_datetimetz,
  mr_data_writeval_datetimetz,
  mr_data_readval_datetimetz,
  NULL,
  NULL,
  mr_index_writeval_datetimetz,
  mr_index_readval_datetimetz,
  mr_index_cmpdisk_datetimetz,
  NULL,
  mr_data_cmpdisk_datetimetz,
  mr_cmpval_datetimetz
}
Definition at line 1225 of file object_primitive.c.
PR_TYPE tp_Double
Initial value:
= {
  "double", DB_TYPE_DOUBLE, 0, sizeof (double), sizeof (double), 4,
  mr_initmem_double,
  mr_initval_double,
  mr_setmem_double,
  mr_getmem_double,
  mr_setval_double,
  NULL,
  NULL,
  mr_data_writemem_double,
  mr_data_readmem_double,
  mr_data_writeval_double,
  mr_data_readval_double,
  NULL,
  NULL,
  mr_index_writeval_double,
  mr_index_readval_double,
  mr_index_cmpdisk_double,
  NULL,
  mr_data_cmpdisk_double,
  mr_cmpval_double
}
Definition at line 1075 of file object_primitive.c.
PR_TYPE tp_Elo
Initial value:
= {
  "*elo*", DB_TYPE_ELO, 1, sizeof (DB_ELO *), 0, 8,
  mr_initmem_elo,
  mr_initval_elo,
  mr_setmem_elo,
  mr_getmem_elo,
  mr_setval_elo,
  mr_data_lengthmem_elo,
  mr_data_lengthval_elo,
  mr_data_writemem_elo,
  mr_data_readmem_elo,
  mr_data_writeval_elo,
  mr_data_readval_elo,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  mr_freemem_elo,
  mr_data_cmpdisk_elo,
  mr_cmpval_elo
}
Definition at line 1360 of file object_primitive.c.
PR_TYPE tp_Enumeration
Initial value:
= {
  "enum", DB_TYPE_ENUMERATION, 0, sizeof (unsigned short), sizeof (unsigned short), sizeof (unsigned short),
  mr_initmem_enumeration,
  mr_initval_enumeration,
  mr_setmem_enumeration,
  mr_getmem_enumeration,
  mr_setval_enumeration,
  NULL,
  NULL,
  mr_data_writemem_enumeration,
  mr_data_readmem_enumeration,
  mr_data_writeval_enumeration,
  mr_data_readval_enumeration,
  NULL,
  NULL,
  mr_index_writeval_enumeration,
  mr_index_readval_enumeration,
  mr_index_cmpdisk_enumeration,
  NULL,
  mr_data_cmpdisk_enumeration,
  mr_cmpval_enumeration
}
Definition at line 1717 of file object_primitive.c.
PR_TYPE tp_Error
Initial value:
= {
  "*error*", DB_TYPE_ERROR, 0, sizeof (int), 0, 4,
  mr_initmem_error,
  mr_initval_error,
  mr_setmem_error,
  mr_getmem_error,
  mr_setval_error,
  mr_data_lengthmem_error,
  mr_data_lengthval_error,
  mr_data_writemem_error,
  mr_data_readmem_error,
  mr_data_writeval_error,
  mr_data_readval_error,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  mr_data_cmpdisk_error,
  mr_cmpval_error
}
Definition at line 1510 of file object_primitive.c.
PR_TYPE tp_Float
Initial value:
= {
  "float", DB_TYPE_FLOAT, 0, sizeof (float), sizeof (float), 4,
  mr_initmem_float,
  mr_initval_float,
  mr_setmem_float,
  mr_getmem_float,
  mr_setval_float,
  NULL,
  NULL,
  mr_data_writemem_float,
  mr_data_readmem_float,
  mr_data_writeval_float,
  mr_data_readval_float,
  NULL,
  NULL,
  mr_index_writeval_float,
  mr_index_readval_float,
  mr_index_cmpdisk_float,
  NULL,
  mr_data_cmpdisk_float,
  mr_cmpval_float
}
Definition at line 1050 of file object_primitive.c.
PR_TYPE tp_Integer
Initial value:
= {
  "integer", DB_TYPE_INTEGER, 0, sizeof (int), sizeof (int), 4,
  mr_initmem_int,
  mr_initval_int,
  mr_setmem_int,
  mr_getmem_int,
  mr_setval_int,
  NULL,
  NULL,
  mr_data_writemem_int,
  mr_data_readmem_int,
  mr_data_writeval_int,
  mr_data_readval_int,
  NULL,
  NULL,
  mr_index_writeval_int,
  mr_index_readval_int,
  mr_index_cmpdisk_int,
  NULL,
  mr_data_cmpdisk_int,
  mr_cmpval_int
}
Definition at line 975 of file object_primitive.c.
Referenced by catcls_get_or_value_from_attribute(), catcls_get_or_value_from_attrid(), catcls_get_or_value_from_class(), catcls_get_or_value_from_domain(), catcls_get_or_value_from_method_argument(), catcls_get_or_value_from_method_signiture(), catcls_get_or_value_from_partition(), catcls_get_or_value_from_resolution(), qexec_analytic_group_header_load(), qexec_analytic_sort_key_header_load(), qfile_fast_intint_tuple_to_list(), and qfile_fast_intval_tuple_to_list().
PR_TYPE tp_Json
Initial value:
= {
  "json", DB_TYPE_JSON, 1, sizeof (DB_JSON), 0, 1,
  mr_initmem_json,
  mr_initval_json,
  mr_setmem_json,
  mr_getmem_json,
  mr_setval_json,
  mr_data_lengthmem_json,
  mr_data_lengthval_json,
  mr_data_writemem_json,
  mr_data_readmem_json,
  mr_data_writeval_json,
  mr_data_readval_json,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  mr_freemem_json,
  mr_data_cmpdisk_json,
  mr_cmpval_json
}
Definition at line 16521 of file object_primitive.c.
PR_TYPE tp_Midxkey
Initial value:
= {
  "midxkey", DB_TYPE_MIDXKEY, 1, 0, 0, 1,
  NULL,
  mr_initval_midxkey,
  NULL,
  NULL,
  mr_setval_midxkey,
  mr_data_lengthmem_midxkey,
  mr_data_lengthval_midxkey,
  NULL,
  NULL,
  mr_data_writeval_midxkey,
  mr_data_readval_midxkey,
  mr_index_lengthmem_midxkey,
  mr_index_lengthval_midxkey,
  mr_index_writeval_midxkey,
  mr_index_readval_midxkey,
  mr_index_cmpdisk_midxkey,
  NULL,
  mr_data_cmpdisk_midxkey,
  mr_cmpval_midxkey
}
Definition at line 1642 of file object_primitive.c.
PR_TYPE tp_Monetary
Initial value:
= {
  "monetary", DB_TYPE_MONETARY, 0, sizeof (DB_MONETARY), OR_MONETARY_SIZE, 4,
  mr_initmem_money,
  mr_initval_money,
  mr_setmem_money,
  mr_getmem_money,
  mr_setval_money,
  NULL,
  NULL,
  mr_data_writemem_money,
  mr_data_readmem_money,
  mr_data_writeval_money,
  mr_data_readval_money,
  NULL,
  NULL,
  mr_index_writeval_money,
  mr_index_readval_money,
  mr_index_cmpdisk_money,
  NULL,
  mr_data_cmpdisk_money,
  mr_cmpval_money
}
Definition at line 1277 of file object_primitive.c.
PR_TYPE tp_Multiset
Initial value:
= {
  "multiset", DB_TYPE_MULTISET, 1, sizeof (SETOBJ *), 0, 4,
  mr_initmem_set,
  mr_initval_multiset,
  mr_setmem_set,
  mr_getmem_multiset,
  mr_setval_multiset,
  mr_data_lengthmem_set,
  mr_data_lengthval_set,
  mr_data_writemem_set,
  mr_data_readmem_set,
  mr_data_writeval_set,
  mr_data_readval_set,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  mr_freemem_set,
  mr_data_cmpdisk_set,
  mr_cmpval_set
}
Definition at line 1592 of file object_primitive.c.
PR_TYPE tp_NChar
Initial value:
= {
  "national character", DB_TYPE_NCHAR, 0, 0, 0, 1,
  mr_initmem_nchar,
  mr_initval_nchar,
  mr_setmem_nchar,
  mr_getmem_nchar,
  mr_setval_nchar,
  mr_data_lengthmem_nchar,
  mr_data_lengthval_nchar,
  mr_data_writemem_nchar,
  mr_data_readmem_nchar,
  mr_data_writeval_nchar,
  mr_data_readval_nchar,
  mr_index_lengthmem_nchar,
  mr_index_lengthval_nchar,
  mr_index_writeval_nchar,
  mr_index_readval_nchar,
  mr_index_cmpdisk_nchar,
  mr_freemem_nchar,
  mr_data_cmpdisk_nchar,
  mr_cmpval_nchar
}
Definition at line 13063 of file object_primitive.c.
Referenced by db_string_truncate().
PR_TYPE tp_Null
Initial value:
= {
  "*NULL*", DB_TYPE_NULL, 0, 0, 0, 0,
  mr_initmem_null,
  mr_initval_null,
  mr_setmem_null,
  mr_getmem_null,
  mr_setval_null,
  NULL,
  NULL,
  mr_data_writemem_null,
  mr_data_readmem_null,
  mr_data_writeval_null,
  mr_data_readval_null,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  mr_data_cmpdisk_null,
  mr_cmpval_null
}
Definition at line 950 of file object_primitive.c.
PR_TYPE tp_Numeric
Initial value:
= {
  "numeric", DB_TYPE_NUMERIC, 0, 0, 0, 1,
  mr_initmem_numeric,
  mr_initval_numeric,
  mr_setmem_numeric,
  mr_getmem_numeric,
  mr_setval_numeric,
  mr_data_lengthmem_numeric,
  mr_data_lengthval_numeric,
  mr_data_writemem_numeric,
  mr_data_readmem_numeric,
  mr_data_writeval_numeric,
  mr_data_readval_numeric,
  mr_index_lengthmem_numeric,
  mr_index_lengthval_numeric,
  mr_index_writeval_numeric,
  mr_index_readval_numeric,
  mr_index_cmpdisk_numeric,
  NULL,
  mr_data_cmpdisk_numeric,
  mr_cmpval_numeric
}
Definition at line 1692 of file object_primitive.c.
PR_TYPE tp_Object
Initial value:
= {
  "object", DB_TYPE_OBJECT, 0, MR_OID_SIZE, OR_OID_SIZE, 4,
  mr_initmem_object,
  mr_initval_object,
  mr_setmem_object,
  mr_getmem_object,
  mr_setval_object,
  NULL,
  mr_data_lengthval_object,
  mr_data_writemem_object,
  mr_data_readmem_object,
  mr_data_writeval_object,
  mr_data_readval_object,
  NULL,
  NULL,
  mr_index_writeval_object,
  mr_index_readval_object,
  mr_index_cmpdisk_object,
  NULL,
  mr_data_cmpdisk_object,
  mr_cmpval_object
}
Definition at line 1335 of file object_primitive.c.
Referenced by catcls_get_object_set(), catcls_get_or_value_from_attribute(), catcls_get_or_value_from_class(), catcls_get_or_value_from_domain(), catcls_get_or_value_from_method(), catcls_get_or_value_from_method_file(), catcls_get_or_value_from_resolution(), disk_to_attribute(), disk_to_class(), disk_to_methfile(), disk_to_method(), disk_to_resolution(), get_object_set(), object_set_size(), and or_pack_mop().
PR_TYPE tp_Oid
Initial value:
= {
  "*oid*", DB_TYPE_OID, 0, sizeof (OID), OR_OID_SIZE, 4,
  mr_initmem_oid,
  mr_initval_oid,
  mr_setmem_oid,
  mr_getmem_oid,
  mr_setval_oid,
  NULL,
  NULL,
  mr_data_writemem_oid,
  mr_data_readmem_oid,
  mr_data_writeval_oid,
  mr_data_readval_oid,
  NULL,
  NULL,
  mr_index_writeval_oid,
  mr_index_readval_oid,
  mr_index_cmpdisk_oid,
  NULL,
  mr_data_cmpdisk_oid,
  mr_cmpval_oid
}
Definition at line 1542 of file object_primitive.c.
Referenced by disk_to_domain2().
PR_TYPE tp_Pointer
Initial value:
= {
  "*pointer*", DB_TYPE_POINTER, 0, sizeof (void *), 0, 4,
  mr_initmem_ptr,
  mr_initval_ptr,
  mr_setmem_ptr,
  mr_getmem_ptr,
  mr_setval_ptr,
  mr_data_lengthmem_ptr,
  mr_data_lengthval_ptr,
  mr_data_writemem_ptr,
  mr_data_readmem_ptr,
  mr_data_writeval_ptr,
  mr_data_readval_ptr,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  mr_data_cmpdisk_ptr,
  mr_cmpval_ptr
}
Definition at line 1485 of file object_primitive.c.
PR_TYPE tp_ResultSet
Initial value:
= {
  "resultset", DB_TYPE_RESULTSET, 0, sizeof (DB_RESULTSET), sizeof (DB_RESULTSET), 4,
  mr_initmem_resultset,
  mr_initval_resultset,
  mr_setmem_resultset,
  mr_getmem_resultset,
  mr_setval_resultset,
  NULL,
  NULL,
  mr_data_writemem_resultset,
  mr_data_readmem_resultset,
  mr_data_writeval_resultset,
  mr_data_readval_resultset,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  mr_data_cmpdisk_resultset,
  mr_cmpval_resultset
}
Definition at line 1794 of file object_primitive.c.
PR_TYPE tp_Sequence
Initial value:
= {
  "sequence", DB_TYPE_SEQUENCE, 1, sizeof (SETOBJ *), 0, 4,
  mr_initmem_set,
  mr_initval_sequence,
  mr_setmem_set,
  mr_getmem_sequence,
  mr_setval_sequence,
  mr_data_lengthmem_set,
  mr_data_lengthval_set,
  mr_data_writemem_set,
  mr_data_readmem_set,
  mr_data_writeval_set,
  mr_data_readval_set,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  mr_freemem_set,
  mr_data_cmpdisk_sequence,
  mr_cmpval_sequence
}
Definition at line 1617 of file object_primitive.c.
Referenced by catcls_get_property_set(), get_property_list(), property_list_size(), and put_property_list().
PR_TYPE tp_Set
Initial value:
= {
  "set", DB_TYPE_SET, 1, sizeof (SETOBJ *), 0, 4,
  mr_initmem_set,
  mr_initval_set,
  mr_setmem_set,
  mr_getmem_set,
  mr_setval_set,
  mr_data_lengthmem_set,
  mr_data_lengthval_set,
  mr_data_writemem_set,
  mr_data_readmem_set,
  mr_data_writeval_set,
  mr_data_readval_set,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  mr_freemem_set,
  mr_data_cmpdisk_set,
  mr_cmpval_set
}
Definition at line 1567 of file object_primitive.c.
Referenced by tf_attribute_default_expr_to_property().
PR_TYPE tp_Short
Initial value:
= {
  "smallint", DB_TYPE_SHORT, 0, sizeof (short), sizeof (short), 2,
  mr_initmem_short,
  mr_initval_short,
  mr_setmem_short,
  mr_getmem_short,
  mr_setval_short,
  NULL,
  NULL,
  mr_data_writemem_short,
  mr_data_readmem_short,
  mr_data_writeval_short,
  mr_data_readval_short,
  NULL,
  NULL,
  mr_index_writeval_short,
  mr_index_readval_short,
  mr_index_cmpdisk_short,
  NULL,
  mr_data_cmpdisk_short,
  mr_cmpval_short
}
Definition at line 1000 of file object_primitive.c.
PR_TYPE tp_String
Initial value:
= {
  "character varying", DB_TYPE_STRING, 1, sizeof (const char *), 0, 1,
  mr_initmem_string,
  mr_initval_string,
  mr_setmem_string,
  mr_getmem_string,
  mr_setval_string,
  mr_data_lengthmem_string,
  mr_data_lengthval_string,
  mr_data_writemem_string,
  mr_data_readmem_string,
  mr_data_writeval_string,
  mr_data_readval_string,
  mr_index_lengthmem_string,
  mr_index_lengthval_string,
  mr_index_writeval_string,
  mr_index_readval_string,
  mr_index_cmpdisk_string,
  mr_freemem_string,
  mr_data_cmpdisk_string,
  mr_cmpval_string
}
Definition at line 11211 of file object_primitive.c.
Referenced by catcls_get_or_value_from_attribute(), catcls_get_or_value_from_attrid(), catcls_get_or_value_from_class(), catcls_get_or_value_from_method(), catcls_get_or_value_from_method_file(), catcls_get_or_value_from_method_signiture(), catcls_get_or_value_from_partition(), catcls_get_or_value_from_query_spec(), catcls_get_or_value_from_resolution(), db_string_truncate(), domain_to_disk(), mr_data_lengthmem_string(), or_get_enumeration(), or_get_json_schema(), or_packed_enumeration_size(), or_packed_json_schema_length(), or_put_enumeration(), or_put_json_schema(), qexec_execute_connect_by(), and valcnv_convert_value_to_string().
PR_TYPE tp_Substructure
Initial value:
= {
  "*substructure*", DB_TYPE_SUB, 1, sizeof (void *), 0, 8,
  mr_initmem_sub,
  mr_initval_sub,
  mr_setmem_sub,
  mr_getmem_sub,
  mr_setval_sub,
  mr_data_lengthmem_sub,
  mr_data_lengthval_sub,
  mr_data_writemem_sub,
  mr_data_readmem_sub,
  mr_data_writeval_sub,
  mr_data_readval_sub,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  mr_data_cmpdisk_sub,
  mr_cmpval_sub
}
Definition at line 1460 of file object_primitive.c.
PR_TYPE tp_Time
Initial value:
= {
  "time", DB_TYPE_TIME, 0, sizeof (DB_TIME), OR_TIME_SIZE, 4,
  mr_initmem_time,
  mr_initval_time,
  mr_setmem_time,
  mr_getmem_time,
  mr_setval_time,
  NULL,
  NULL,
  mr_data_writemem_time,
  mr_data_readmem_time,
  mr_data_writeval_time,
  mr_data_readval_time,
  NULL,
  NULL,
  mr_index_writeval_time,
  mr_index_readval_time,
  mr_index_cmpdisk_time,
  NULL,
  mr_data_cmpdisk_time,
  mr_cmpval_time
}
Definition at line 1100 of file object_primitive.c.
PR_TYPE tp_Timestampltz
Initial value:
= {
  "timestampltz", DB_TYPE_TIMESTAMPLTZ, 0, sizeof (DB_UTIME), OR_UTIME_SIZE, 4,
  mr_initmem_utime,
  mr_initval_timestampltz,
  mr_setmem_utime,
  mr_getmem_timestampltz,
  mr_setval_timestampltz,
  NULL,
  NULL,
  mr_data_writemem_utime,
  mr_data_readmem_utime,
  mr_data_writeval_utime,
  mr_data_readval_timestampltz,
  NULL,
  NULL,
  mr_index_writeval_utime,
  mr_index_readval_timestampltz,
  mr_index_cmpdisk_utime,
  NULL,
  mr_data_cmpdisk_utime,
  mr_cmpval_utime
}
Definition at line 1177 of file object_primitive.c.
PR_TYPE tp_Timestamptz
Initial value:
= {
  "timestamptz", DB_TYPE_TIMESTAMPTZ, 0, sizeof (DB_TIMESTAMPTZ), OR_TIMESTAMPTZ_SIZE, 4,
  mr_initmem_timestamptz,
  mr_initval_timestamptz,
  mr_setmem_timestamptz,
  mr_getmem_timestamptz,
  mr_setval_timestamptz,
  NULL,
  NULL,
  mr_data_writemem_timestamptz,
  mr_data_readmem_timestamptz,
  mr_data_writeval_timestamptz,
  mr_data_readval_timestamptz,
  NULL,
  NULL,
  mr_index_writeval_timestamptz,
  mr_index_readval_timestamptz,
  mr_index_cmpdisk_timestamptz,
  NULL,
  mr_data_cmpdisk_timestamptz,
  mr_cmpval_timestamptz
}
Definition at line 1150 of file object_primitive.c.
PR_TYPE* tp_Type_bigint = &tp_Bigint
Definition at line 1048 of file object_primitive.c.
PR_TYPE* tp_Type_bit = &tp_Bit
Definition at line 14993 of file object_primitive.c.
PR_TYPE* tp_Type_blob = &tp_Blob
Definition at line 1408 of file object_primitive.c.
PR_TYPE* tp_Type_char = &tp_Char
Definition at line 12137 of file object_primitive.c.
PR_TYPE* tp_Type_clob = &tp_Clob
Definition at line 1433 of file object_primitive.c.
PR_TYPE* tp_Type_date = &tp_Date
Definition at line 1325 of file object_primitive.c.
PR_TYPE* tp_Type_datetime = &tp_Datetime
Definition at line 1223 of file object_primitive.c.
PR_TYPE* tp_Type_datetimeltz = &tp_Datetimeltz
Definition at line 1275 of file object_primitive.c.
PR_TYPE* tp_Type_Datetimetz = &tp_Datetimetz
Definition at line 1248 of file object_primitive.c.
PR_TYPE* tp_Type_double = &tp_Double
Definition at line 1098 of file object_primitive.c.
PR_TYPE* tp_Type_elo = &tp_Elo
Definition at line 1383 of file object_primitive.c.
PR_TYPE* tp_Type_enumeration = &tp_Enumeration
Definition at line 1740 of file object_primitive.c.
PR_TYPE* tp_Type_error = &tp_Error
Definition at line 1533 of file object_primitive.c.
PR_TYPE* tp_Type_float = &tp_Float
Definition at line 1073 of file object_primitive.c.
PR_TYPE* tp_Type_id_map[]
Definition at line 1750 of file object_primitive.c.
Referenced by catcls_get_or_value_from_buffer(), catcls_guess_record_length(), catcls_put_or_value_into_buffer(), and vid_pack_db_value().
PR_TYPE* tp_Type_integer = &tp_Integer
Definition at line 998 of file object_primitive.c.
Referenced by pr_find_type().
PR_TYPE* tp_Type_json = &tp_Json
Definition at line 16544 of file object_primitive.c.
PR_TYPE* tp_Type_midxkey = &tp_Midxkey
Definition at line 1665 of file object_primitive.c.
PR_TYPE* tp_Type_monetary = &tp_Monetary
Definition at line 1300 of file object_primitive.c.
PR_TYPE* tp_Type_multiset = &tp_Multiset
Definition at line 1615 of file object_primitive.c.
Referenced by pr_find_type().
PR_TYPE* tp_Type_nchar = &tp_NChar
Definition at line 13086 of file object_primitive.c.
PR_TYPE* tp_Type_null = &tp_Null
Definition at line 973 of file object_primitive.c.
Referenced by compare_domains(), fixup_attribute_self_domain(), fixup_self_domain(), pr_data_writeval(), and resolve_class_domain().
PR_TYPE* tp_Type_numeric = &tp_Numeric
Definition at line 1715 of file object_primitive.c.
PR_TYPE* tp_Type_object = &tp_Object
Definition at line 1358 of file object_primitive.c.
Referenced by check_class_domain(), check_constraints(), check_object_domain(), compare_domains(), db_domain_class(), fixup_attribute_self_domain(), fixup_self_domain(), obj_assign_value(), obj_get_value(), obt_assign_obt(), sm_att_class(), sm_check_class_domain(), sm_check_object_domain(), sm_coerce_object_domain(), tp_domain_check_class(), tp_domain_filter_list(), and vid_compare_non_updatable_objects().
PR_TYPE* tp_Type_oid = &tp_Oid
Definition at line 1565 of file object_primitive.c.
PR_TYPE* tp_Type_pointer = &tp_Pointer
Definition at line 1508 of file object_primitive.c.
PR_TYPE* tp_Type_resultset = &tp_ResultSet
Definition at line 1817 of file object_primitive.c.
PR_TYPE* tp_Type_sequence = &tp_Sequence
Definition at line 1640 of file object_primitive.c.
Referenced by pr_find_type().
PR_TYPE* tp_Type_set = &tp_Set
Definition at line 1590 of file object_primitive.c.
PR_TYPE* tp_Type_short = &tp_Short
Definition at line 1023 of file object_primitive.c.
Referenced by pr_find_type().
PR_TYPE* tp_Type_string = &tp_String
Definition at line 11234 of file object_primitive.c.
Referenced by pr_find_type().
PR_TYPE* tp_Type_substructure = &tp_Substructure
Definition at line 1483 of file object_primitive.c.
PR_TYPE* tp_Type_time = &tp_Time
Definition at line 1123 of file object_primitive.c.
PR_TYPE* tp_Type_Timestamptz = &tp_Timestamptz
Definition at line 1173 of file object_primitive.c.
PR_TYPE* tp_Type_utime = &tp_Utime
Definition at line 1148 of file object_primitive.c.
Referenced by pr_find_type().
PR_TYPE* tp_Type_varbit = &tp_VarBit
Definition at line 15685 of file object_primitive.c.
PR_TYPE* tp_Type_variable = &tp_Variable
Definition at line 1458 of file object_primitive.c.
PR_TYPE* tp_Type_varnchar = &tp_VarNChar
Definition at line 14265 of file object_primitive.c.
PR_TYPE* tp_Type_vobj = &tp_Vobj
Definition at line 1690 of file object_primitive.c.
PR_TYPE tp_Utime
Initial value:
= {
  "timestamp", DB_TYPE_TIMESTAMP, 0, sizeof (DB_UTIME), OR_UTIME_SIZE, 4,
  mr_initmem_utime,
  mr_initval_utime,
  mr_setmem_utime,
  mr_getmem_utime,
  mr_setval_utime,
  NULL,
  NULL,
  mr_data_writemem_utime,
  mr_data_readmem_utime,
  mr_data_writeval_utime,
  mr_data_readval_utime,
  NULL,
  NULL,
  mr_index_writeval_utime,
  mr_index_readval_utime,
  mr_index_cmpdisk_utime,
  NULL,
  mr_data_cmpdisk_utime,
  mr_cmpval_utime
}
Definition at line 1125 of file object_primitive.c.
PR_TYPE tp_VarBit
Initial value:
= {
  "bit varying", DB_TYPE_VARBIT, 1, sizeof (const char *), 0, 1,
  mr_initmem_varbit,
  mr_initval_varbit,
  mr_setmem_varbit,
  mr_getmem_varbit,
  mr_setval_varbit,
  mr_data_lengthmem_varbit,
  mr_data_lengthval_varbit,
  mr_data_writemem_varbit,
  mr_data_readmem_varbit,
  mr_data_writeval_varbit,
  mr_data_readval_varbit,
  mr_index_lengthmem_varbit,
  mr_index_lengthval_varbit,
  mr_index_writeval_varbit,
  mr_index_readval_varbit,
  mr_index_cmpdisk_varbit,
  mr_freemem_varbit,
  mr_data_cmpdisk_varbit,
  mr_cmpval_varbit
}
Definition at line 15662 of file object_primitive.c.
Referenced by db_string_truncate(), and mr_data_lengthmem_varbit().
PR_TYPE tp_Variable
Initial value:
= {
  "*variable*", DB_TYPE_VARIABLE, 1, sizeof (DB_VALUE), 0, 4,
  NULL,
  mr_initval_variable,
  NULL,
  NULL,
  mr_setval_variable,
  NULL,
  mr_data_lengthval_variable,
  NULL,
  NULL,
  mr_data_writeval_variable,
  mr_data_readval_variable,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  mr_data_cmpdisk_variable,
  mr_cmpval_variable
}
Definition at line 1435 of file object_primitive.c.
PR_TYPE tp_VarNChar
Initial value:
= {
  "national character varying", DB_TYPE_VARNCHAR, 1, sizeof (const char *), 0, 1,
  mr_initmem_varnchar,
  mr_initval_varnchar,
  mr_setmem_varnchar,
  mr_getmem_varnchar,
  mr_setval_varnchar,
  mr_data_lengthmem_varnchar,
  mr_data_lengthval_varnchar,
  mr_data_writemem_varnchar,
  mr_data_readmem_varnchar,
  mr_data_writeval_varnchar,
  mr_data_readval_varnchar,
  mr_index_lengthmem_varnchar,
  mr_index_lengthval_varnchar,
  mr_index_writeval_varnchar,
  mr_index_readval_varnchar,
  mr_index_cmpdisk_varnchar,
  mr_freemem_varnchar,
  mr_data_cmpdisk_varnchar,
  mr_cmpval_varnchar
}
Definition at line 14242 of file object_primitive.c.
Referenced by db_string_truncate(), disk_to_resolution(), get_string(), mr_data_lengthmem_varnchar(), put_string(), and string_disk_size().
PR_TYPE tp_Vobj
Initial value:
= {
  "*vobj*", DB_TYPE_VOBJ, 1, sizeof (SETOBJ *), 0, 8,
  mr_initmem_set,
  mr_initval_vobj,
  mr_setmem_set,
  mr_getmem_sequence,
  mr_setval_vobj,
  mr_data_lengthmem_set,
  mr_data_lengthval_set,
  mr_data_writemem_set,
  mr_data_readmem_set,
  mr_data_writeval_set,
  mr_data_readval_vobj,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  mr_freemem_set,
  mr_data_cmpdisk_vobj,
  mr_cmpval_vobj
}
Definition at line 1667 of file object_primitive.c.
AREA* Value_area = NULL static
Definition at line 945 of file object_primitive.c.