CUBRID Engine: src/base/object_representation.h File Reference
object_representation.h File Reference
#include <setjmp.h>
#include <time.h>
#include <float.h>
#include <limits.h>
#include <assert.h>
#include <netinet/in.h>
#include "byte_order.h"
#include "db_set.h"
#include "error_manager.h"
#include "memory_alloc.h"
#include "oid.h"
#include "object_representation_constants.h"
#include "porting_inline.hpp"
#include "storage_common.h"
Classes
struct db_binary
struct db_reference
struct or_varinfo
struct or_buf
Macros
#define OR_VALUE_ALIGNED_SIZE(value) (or_db_value_size (value) + MAX_ALIGNMENT)
#define OR_CHECK_ASSIGN_OVERFLOW(dest, src) (((src) > 0 && (dest) < 0) || ((src) < 0 && (dest) > 0))
#define OR_CHECK_ADD_OVERFLOW(a, b, c)
#define OR_CHECK_UNS_ADD_OVERFLOW(a, b, c) (c) < (a) || (c) < (b)
#define OR_CHECK_SUB_UNDERFLOW(a, b, c)
#define OR_CHECK_UNS_SUB_UNDERFLOW(a, b, c) (b) > (a)
#define OR_CHECK_MULT_OVERFLOW(a, b, c) (((b) == 0) ? ((c) != 0) : ((c) / (b) != (a)))
#define OR_CHECK_SHORT_DIV_OVERFLOW(a, b) ((a) == DB_INT16_MIN && (b) == -1)
#define OR_CHECK_INT_DIV_OVERFLOW(a, b) ((a) == DB_INT32_MIN && (b) == -1)
#define OR_CHECK_BIGINT_DIV_OVERFLOW(a, b) ((a) == DB_BIGINT_MIN && (b) == -1)
#define OR_CHECK_SHORT_OVERFLOW(i) ((i) > DB_INT16_MAX || (i) < DB_INT16_MIN)
#define OR_CHECK_INT_OVERFLOW(i) ((i) > DB_INT32_MAX || (i) < DB_INT32_MIN)
#define OR_CHECK_BIGINT_OVERFLOW(i) ((i) > DB_BIGINT_MAX || (i) < DB_BIGINT_MIN)
#define OR_CHECK_USHRT_OVERFLOW(i) ((i) > (int) DB_UINT16_MAX || (i) < 0)
#define OR_CHECK_UINT_OVERFLOW(i) ((i) > DB_UINT32_MAX || (i) < 0)
#define OR_CHECK_FLOAT_OVERFLOW(i) ((i) > FLT_MAX || (-(i)) > FLT_MAX)
#define OR_CHECK_DOUBLE_OVERFLOW(i) ((i) > DBL_MAX || (-(i)) > DBL_MAX)
#define OR_GET_BYTE(ptr) (*(unsigned char *) ((char *) (ptr)))
#define OR_GET_SHORT(ptr) ((short) ntohs (*(short *) ((char *) (ptr))))
#define OR_GET_INT(ptr) ((int) ntohl (*(int *) ((char *) (ptr))))
#define OR_GET_FLOAT(ptr, value) (*(value) = ntohf (*(UINT32 *) (ptr)))
#define OR_GET_DOUBLE(ptr, value) (*(value) = ntohd (*(UINT64 *) (ptr)))
#define OR_GET_STRING(ptr) ((char *) ((char *) (ptr)))
#define OR_PUT_BYTE(ptr, val) (*((unsigned char *) (ptr)) = (unsigned char) (val))
#define OR_PUT_SHORT(ptr, val) (*(short *) ((char *) (ptr)) = htons ((short) (val)))
#define OR_PUT_INT(ptr, val) (*(int *) ((char *) (ptr)) = htonl ((int) (val)))
#define OR_GET_BIG_VAR_OFFSET(ptr) OR_GET_INT (ptr) /* 4byte */
#define OR_PUT_BIG_VAR_OFFSET(ptr, val) OR_PUT_INT (ptr, val) /* 4byte */
#define OR_PUT_OFFSET(ptr, val) OR_PUT_OFFSET_INTERNAL(ptr, val, BIG_VAR_OFFSET_SIZE)
#define OR_PUT_OFFSET_INTERNAL(ptr, val, offset_size)
#define OR_GET_OFFSET(ptr) OR_GET_OFFSET_INTERNAL (ptr, BIG_VAR_OFFSET_SIZE)
#define OR_GET_OFFSET_INTERNAL(ptr, offset_size)
#define OR_MOVE_MONETARY(src, dst)
#define swap64(x)
#define OR_PTR_SIZE 8
#define OR_PUT_PTR(ptr, val) (*(UINTPTR *) ((char *) (ptr)) = swap64 ((UINTPTR) val))
#define OR_GET_PTR(ptr) ((UINTPTR) swap64 (*(UINTPTR *) ((char *) (ptr))))
#define OR_INT64_SIZE 8
#define OR_PUT_BIGINT(ptr, val) OR_PUT_INT64 (ptr, val)
#define OR_GET_BIGINT(ptr, val) OR_GET_INT64 (ptr, val)
#define OR_GET_INT64(ptr, val)
#define OR_PUT_INT64(ptr, val)
#define OR_GET_TIME(ptr, value) *((DB_TIME *) (value)) = OR_GET_INT (ptr)
#define OR_PUT_TIME(ptr, value) OR_PUT_INT (ptr, *((DB_TIME *) (value)))
#define OR_GET_UTIME(ptr, value) *((DB_UTIME *) (value)) = OR_GET_INT (ptr)
#define OR_PUT_UTIME(ptr, value) OR_PUT_INT (ptr, *((DB_UTIME *) (value)))
#define OR_GET_TIMESTAMPTZ(ptr, ts_tz)
#define OR_PUT_TIMESTAMPTZ(ptr, ts_tz)
#define OR_GET_DATE(ptr, value) *((DB_DATE *) (value)) = OR_GET_INT (ptr)
#define OR_PUT_DATE(ptr, value) OR_PUT_INT (ptr, *((DB_DATE *) (value)))
#define OR_GET_DATETIME(ptr, datetime)
#define OR_PUT_DATETIME(ptr, datetime)
#define OR_GET_DATETIMETZ(ptr, datetimetz)
#define OR_PUT_DATETIMETZ(ptr, datetimetz)
#define OR_GET_MONETARY(ptr, value)
#define OR_GET_CURRENCY_TYPE(ptr) (DB_CURRENCY) OR_GET_INT (((char *) (ptr)) + OR_MONETARY_TYPE)
#define OR_PUT_MONETARY(ptr, value)
#define OR_GET_SHA1(ptr, value)
#define OR_PUT_SHA1(ptr, value)
#define OR_GET_OID(ptr, oid)
#define OR_PUT_OID(ptr, oid)
#define OR_GET_VPID(ptr, vpid)
#define OR_PUT_VPID(ptr, vpid)
#define OR_PUT_VPID_ALIGNED(ptr, vpid)
#define OR_PUT_NULL_OID(ptr)
#define OR_GET_HFID(ptr, hfid)
#define OR_PUT_HFID(ptr, hfid)
#define OR_PUT_NULL_HFID(ptr)
#define OR_GET_BTID(ptr, btid)
#define OR_PUT_BTID(ptr, btid)
#define OR_PUT_NULL_BTID(ptr)
#define OR_GET_EHID(ptr, ehid)
#define OR_PUT_EHID(ptr, ehid)
#define OR_GET_LOG_LSA(ptr, lsa)
#define OR_PUT_LOG_LSA(ptr, lsa)
#define OR_PUT_NULL_LOG_LSA(ptr)
#define OR_VAR_TABLE_SIZE(vars) (OR_VAR_TABLE_SIZE_INTERNAL (vars, BIG_VAR_OFFSET_SIZE))
#define OR_VAR_TABLE_SIZE_INTERNAL(vars, offset_size) (((vars) == 0) ? 0 : DB_ALIGN ((offset_size * ((vars) + 1)), INT_ALIGNMENT))
#define OR_VAR_TABLE_ELEMENT_PTR(table, index, offset_size)
#define OR_VAR_TABLE_ELEMENT_OFFSET_INTERNAL(table, index, offset_size)
#define OR_VAR_TABLE_ELEMENT_LENGTH_INTERNAL(table, index, offset_size)
#define OR_FIXED_ATTRIBUTES_OFFSET(ptr, nvars) (OR_FIXED_ATTRIBUTES_OFFSET_INTERNAL (ptr, nvars, BIG_VAR_OFFSET_SIZE))
#define OR_FIXED_ATTRIBUTES_OFFSET_INTERNAL(ptr, nvars, offset_size) (OR_HEADER_SIZE (ptr) + OR_VAR_TABLE_SIZE_INTERNAL (nvars, offset_size))
#define OR_HEADER_SIZE(ptr) (or_header_size ((char *) (ptr)))
#define OR_REP_OFFSET 0
#define OR_MVCC_REP_SIZE 4
#define OR_MVCC_FLAG_OFFSET OR_REP_OFFSET
#define OR_MVCC_FLAG_SIZE OR_MVCC_REP_SIZE
#define OR_CHN_OFFSET (OR_REP_OFFSET + OR_MVCC_REP_SIZE)
#define OR_CHN_SIZE 4
#define OR_MVCC_INSERT_ID_OFFSET (OR_CHN_OFFSET + OR_CHN_SIZE)
#define OR_MVCC_INSERT_ID_SIZE 8
#define OR_MVCC_DELETE_ID_OFFSET(mvcc_flags) (OR_MVCC_INSERT_ID_OFFSET + (((mvcc_flags) & OR_MVCC_FLAG_VALID_INSID) ? OR_MVCC_INSERT_ID_SIZE : 0))
#define OR_MVCC_DELETE_ID_SIZE 8
#define OR_MVCC_PREV_VERSION_LSA_OFFSET(mvcc_flags) (OR_MVCC_DELETE_ID_OFFSET(mvcc_flags) + (((mvcc_flags) & OR_MVCC_FLAG_VALID_DELID) ? OR_MVCC_DELETE_ID_SIZE : 0))
#define OR_MVCC_PREV_VERSION_LSA_SIZE 8
#define OR_MVCCID_SIZE OR_BIGINT_SIZE
#define OR_PUT_MVCCID OR_PUT_BIGINT
#define OR_GET_MVCCID OR_GET_BIGINT
#define OR_BOUND_BIT_FLAG 0x80000000
#define BIG_VAR_OFFSET_SIZE OR_INT_SIZE /* 4byte */
#define OR_GET_REPID(ptr) ((OR_GET_INT ((ptr) + OR_REP_OFFSET)) & ~OR_BOUND_BIT_FLAG & ~OR_OFFSET_SIZE_FLAG)
#define OR_GET_BOUND_BIT_FLAG(ptr) ((OR_GET_INT ((ptr) + OR_REP_OFFSET)) & OR_BOUND_BIT_FLAG)
#define OR_GET_OFFSET_SIZE(ptr)
#define OR_SET_VAR_OFFSET_SIZE(val, offset_size)
#define OR_GET_MVCC_INSERT_ID(ptr, mvcc_flags, valp)
#define OR_GET_MVCC_DELETE_ID(ptr, mvcc_flags, valp)
#define OR_GET_MVCC_REPID(ptr)
#define OR_GET_MVCC_CHN(ptr) (OR_GET_INT ((char *) (ptr) + OR_CHN_OFFSET))
#define OR_GET_MVCC_FLAG(ptr)
#define OR_GET_MVCC_REPID_AND_FLAG(ptr) (OR_GET_INT (((char *) (ptr)) + OR_REP_OFFSET))
#define OR_GET_OBJECT_VAR_TABLE(obj) ((short *) (((char *) (obj)) + OR_HEADER_SIZE ((char *) (obj))))
#define OR_VAR_ELEMENT_PTR(obj, index) (OR_VAR_TABLE_ELEMENT_PTR (OR_GET_OBJECT_VAR_TABLE (obj), index, OR_GET_OFFSET_SIZE (obj)))
#define OR_VAR_OFFSET(obj, index)
#define OR_VAR_IS_NULL(obj, index)
#define OR_VAR_LENGTH(length, obj, index, n_variables)
#define OR_BOUND_BIT_WORDS(count) (((count) + 31) >> 5)
#define OR_BOUND_BIT_BYTES(count) ((((count) + 31) >> 5) * 4)
#define OR_BOUND_BIT_MASK(element) (1 << ((int) (element) & 7))
#define OR_GET_BOUND_BIT_BYTE(bitptr, element) ((char *) (bitptr) + ((int) (element) >> 3))
#define OR_GET_BOUND_BIT(bitptr, element) ((*OR_GET_BOUND_BIT_BYTE ((bitptr), (element))) & OR_BOUND_BIT_MASK ((element)))
#define OR_GET_BOUND_BITS(obj, nvars, fsize)
#define OR_FIXED_ATT_IS_BOUND(obj, nvars, fsize, position) (!OR_GET_BOUND_BIT_FLAG (obj) || OR_GET_BOUND_BIT (OR_GET_BOUND_BITS (obj, nvars, fsize), position))
#define OR_FIXED_ATT_IS_UNBOUND(obj, nvars, fsize, position) (OR_GET_BOUND_BIT_FLAG (obj) && !OR_GET_BOUND_BIT (OR_GET_BOUND_BITS (obj, nvars, fsize), position))
#define OR_ENABLE_BOUND_BIT(bitptr, element) *OR_GET_BOUND_BIT_BYTE (bitptr, element) = *OR_GET_BOUND_BIT_BYTE (bitptr, element) | OR_BOUND_BIT_MASK (element)
#define OR_CLEAR_BOUND_BIT(bitptr, element) *OR_GET_BOUND_BIT_BYTE (bitptr, element) = *OR_GET_BOUND_BIT_BYTE (bitptr, element) & ~OR_BOUND_BIT_MASK (element)
#define OR_SET_HEADER_SIZE 8
#define OR_SET_SIZE_OFFSET 4
#define OR_SET_DOMAIN_SIZE_OFFSET 8
#define OR_SET_TYPE_MASK 0xFF
#define OR_SET_ETYPE_MASK 0xFF00
#define OR_SET_ETYPE_SHIFT 8
#define OR_SET_BOUND_BIT 0x10000
#define OR_SET_VARIABLE_BIT 0x20000
#define OR_SET_DOMAIN_BIT 0x40000
#define OR_SET_TAG_BIT 0x80000
#define OR_SET_COMMON_SUB_BIT 0x100000
#define OR_SET_TYPE(setptr) (DB_TYPE) ((OR_GET_INT ((char *) (setptr))) & OR_SET_TYPE_MASK)
#define OR_SET_ELEMENT_TYPE(setptr) (DB_TYPE) ((OR_GET_INT ((char *) (setptr)) & OR_SET_ETYPE_MASK) >> OR_SET_ETYPE_SHIFT)
#define OR_SET_HAS_BOUND_BITS(setptr) (OR_GET_INT ((char *) (setptr)) & OR_SET_BOUND_BIT)
#define OR_SET_HAS_OFFSET_TABLE(setptr) (OR_GET_INT ((char *) (setptr)) & OR_SET_VARIABLE_BIT)
#define OR_SET_HAS_DOMAIN(setptr) (OR_GET_INT ((char *) (setptr)) & OR_SET_DOMAIN_BIT)
#define OR_SET_HAS_ELEMENT_TAGS(setptr) (OR_GET_INT ((char *) (setptr)) & OR_SET_TAG_BIT)
#define OR_SET_ELEMENT_COUNT(setptr) ((OR_GET_INT ((char *) (setptr) + OR_SET_SIZE_OFFSET)))
#define OR_SET_DOMAIN_SIZE(setptr) ((OR_GET_INT ((char *) (setptr) + OR_SET_DOMAIN_SIZE_OFFSET)))
#define OR_GET_SET_VAR_TABLE(setptr) ((int *) ((char *) (setptr) + OR_SET_HEADER_SIZE))
#define OR_SET_ELEMENT_OFFSET(setptr, element) (OR_VAR_TABLE_ELEMENT_OFFSET_INTERNAL (OR_GET_SET_VAR_TABLE (setptr), element, BIG_VAR_OFFSET_SIZE))
#define OR_GET_SET_BOUND_BITS(setptr) (int *) ((char *) (setptr) + OR_SET_HEADER_SIZE)
#define OR_MULTI_BOUND_BIT_BYTES(count) (((count) + 7) >> 3)
#define OR_MULTI_BOUND_BIT_MASK(element) (1 << ((int) (element) & 7))
#define OR_MULTI_GET_BOUND_BIT_BYTE(bitptr, element) ((char *)(bitptr) + ((int)(element) >> 3))
#define OR_MULTI_GET_BOUND_BIT(bitptr, element) ((*OR_MULTI_GET_BOUND_BIT_BYTE(bitptr, element)) & OR_MULTI_BOUND_BIT_MASK(element))
#define OR_MULTI_GET_BOUND_BITS(bitptr, fsize) (char *) (((char *) (bitptr)) + fsize)
#define OR_MULTI_ATT_IS_BOUND(bitptr, element) OR_MULTI_GET_BOUND_BIT(bitptr, element)
#define OR_MULTI_ATT_IS_UNBOUND(bitptr, element) (!OR_MULTI_GET_BOUND_BIT (bitptr, element))
#define OR_MULTI_ENABLE_BOUND_BIT(bitptr, element)
#define OR_MULTI_CLEAR_BOUND_BIT(bitptr, element)
#define OR_SUB_HEADER_SIZE OR_OID_SIZE + OR_INT_SIZE + OR_INT_SIZE
#define OR_SUB_DOMAIN_SIZE OR_INT_SIZE
#define OR_VARIABLE_HEADER_SIZE 4
#define OR_GET_VARIABLE_TYPE(ptr) (OR_GET_INT ((int *) (ptr)))
#define OR_BINARY_MAX_LENGTH 65535
#define OR_BINARY_LENGTH_MASK 0xFFFF
#define OR_BINARY_PAD_SHIFT 16
#define OR_TYPE_SIZE(type) or_Type_sizes[(int)(type)]
#define OR_ALIGNED_BUF(size)
#define OR_ALIGNED_BUF_START(abuf) (abuf.buf)
#define OR_ALIGNED_BUF_SIZE(abuf) (sizeof (abuf.buf))
#define OR_INFINITE_POINTER ((void *) (~((UINTPTR) 0UL)))
#define OR_BUF_INIT(buf, data, size)
#define OR_BUF_INIT2(buf, data, size)
#define OR_PACK_DOMAIN_OBJECT_TO_OID(p, d, o, n)
#define ASSERT_ALIGN(ptr, alignment) (assert (PTR_ALIGN (ptr, alignment) == ptr))
#define OR_MINIMUM_STRING_LENGTH_FOR_COMPRESSION 255
#define OR_IS_STRING_LENGTH_COMPRESSABLE(str_length) ((str_length) >= OR_MINIMUM_STRING_LENGTH_FOR_COMPRESSION && (str_length) <= LZ4_MAX_INPUT_SIZE)
Typedefs
typedef struct db_binary DB_BINARY
typedef struct db_reference DB_REFERENCE
typedef struct setobj SETOBJ
typedef struct db_set SETREF
typedef struct or_varinfo OR_VARINFO
typedef struct or_buf OR_BUF
Enumerations
enum {
ORC_REP_DIR_OFFSET = 8, ORC_HFID_FILEID_OFFSET = 16, ORC_HFID_VOLID_OFFSET = 20, ORC_HFID_PAGEID_OFFSET = 24,
ORC_FIXED_COUNT_OFFSET = 28, ORC_VARIABLE_COUNT_OFFSET = 32, ORC_FIXED_LENGTH_OFFSET = 36, ORC_ATT_COUNT_OFFSET = 40,
ORC_SHARED_COUNT_OFFSET = 48, ORC_CLASS_ATTR_COUNT_OFFSET = 60, ORC_CLASS_FLAGS = 64, ORC_CLASS_TYPE = 68,
ORC_CLASS_TDE_ALGORITHM = 84
}
enum {
ORC_NAME_INDEX = 0, ORC_LOADER_COMMANDS_INDEX = 1, ORC_REPRESENTATIONS_INDEX = 2, ORC_SUBCLASSES_INDEX = 3,
ORC_SUPERCLASSES_INDEX = 4, ORC_ATTRIBUTES_INDEX = 5, ORC_SHARED_ATTRS_INDEX = 6, ORC_CLASS_ATTRS_INDEX = 7,
ORC_METHODS_INDEX = 8, ORC_CLASS_METHODS_INDEX = 9, ORC_METHOD_FILES_INDEX = 10, ORC_RESOLUTIONS_INDEX = 11,
ORC_QUERY_SPEC_INDEX = 12, ORC_TRIGGERS_INDEX = 13, ORC_PROPERTIES_INDEX = 14, ORC_COMMENT_INDEX = 15,
ORC_PARTITION_INDEX = 16, ORC_LAST_INDEX, ORC_CLASS_VAR_ATT_COUNT = ORC_LAST_INDEX
}
enum {
ORC_ATT_ID_OFFSET = 0, ORC_ATT_TYPE_OFFSET = 4, ORC_ATT_DEF_ORDER_OFFSET = 12, ORC_ATT_CLASS_OFFSET = 16,
ORC_ATT_FLAG_OFFSET = 24, ORC_ATT_INDEX_OFFSET = 28
}
enum {
ORC_ATT_NAME_INDEX = 0, ORC_ATT_CURRENT_VALUE_INDEX = 1, ORC_ATT_ORIGINAL_VALUE_INDEX = 2, ORC_ATT_DOMAIN_INDEX = 3,
ORC_ATT_TRIGGER_INDEX = 4, ORC_ATT_PROPERTIES_INDEX = 5, ORC_ATT_COMMENT_INDEX = 6, ORC_ATT_LAST_INDEX,
ORC_ATT_VAR_ATT_COUNT = ORC_ATT_LAST_INDEX
}
enum { ORC_REP_ID_OFFSET = 0, ORC_REP_FIXED_COUNT_OFFSET = 4, ORC_REP_VARIABLE_COUNT_OFFSET = 8 }
enum { ORC_REP_ATTRIBUTES_INDEX = 0, ORC_REP_PROPERTIES_INDEX = 1, ORC_REP_LAST_INDEX, ORC_REP_VAR_ATT_COUNT = ORC_REP_LAST_INDEX }
enum { ORC_REPATT_ID_OFFSET = 0, ORC_REPATT_TYPE_OFFSET = 4 }
enum { ORC_REPATT_DOMAIN_INDEX = 0, ORC_REPATT_LAST_INDEX, ORC_REPATT_VAR_ATT_COUNT = ORC_REPATT_LAST_INDEX }
enum {
ORC_DOMAIN_TYPE_OFFSET = 0, ORC_DOMAIN_PRECISION_OFFSET = 4, ORC_DOMAIN_SCALE_OFFSET = 8, ORC_DOMAIN_CODESET_OFFSET = 12,
ORC_DOMAIN_COLLATION_ID_OFFSET = 16, ORC_DOMAIN_CLASS_OFFSET = 20
}
enum {
ORC_DOMAIN_SETDOMAIN_INDEX = 0, ORC_DOMAIN_ENUMERATION_INDEX = 1, ORC_DOMAIN_SCHEMA_JSON_OFFSET = 2, ORC_DOMAIN_LAST_INDEX,
ORC_DOMAIN_VAR_ATT_COUNT = ORC_DOMAIN_LAST_INDEX
}
enum {
ORC_METHOD_NAME_INDEX = 0, ORC_METHOD_SIGNATURE_INDEX = 1, ORC_METHOD_PROPERTIES_INDEX = 2, ORC_METHOD_LAST_INDEX,
ORC_METHOD_VAR_ATT_COUNT = ORC_METHOD_LAST_INDEX
}
enum { ORC_METHARG_DOMAIN_INDEX = 0, ORC_METHARG_LAST_INDEX, ORC_METHARG_VAR_ATT_COUNT = ORC_METHARG_LAST_INDEX }
enum {
ORC_METHSIG_FUNCTION_NAME_INDEX = 0, ORC_METHSIG_SQL_DEF_INDEX = 1, ORC_METHSIG_RETURN_VALUE_INDEX = 2, ORC_METHSIG_ARGUMENTS_INDEX = 3,
ORC_METHSIG_LAST_INDEX, ORC_METHSIG_VAR_ATT_COUNT = ORC_METHSIG_LAST_INDEX
}
enum { ORC_METHFILE_NAME_INDEX = 0, ORC_METHFILE_PROPERTIES_INDEX = 1, ORC_METHFILE_LAST_INDEX, ORC_METHFILE_VAR_ATT_COUNT = ORC_METHFILE_LAST_INDEX }
enum { ORC_QUERY_SPEC_SPEC_INDEX = 0, ORC_QUERY_LAST_INDEX, ORC_QUERY_SPEC_VAR_ATT_COUNT = ORC_QUERY_LAST_INDEX }
enum { ORC_RES_NAME_INDEX = 0, ORC_RES_ALIAS_INDEX = 1, ORC_RES_LAST_INDEX, ORC_RES_VAR_ATT_COUNT = ORC_RES_LAST_INDEX }
enum {
ORC_PARTITION_NAME_INDEX = 0, ORC_PARTITION_EXPR_INDEX = 1, ORC_PARTITION_VALUES_INDEX = 2, ORC_PARTITION_COMMENT_INDEX = 3,
ORC_PARTITION_LAST_INDEX, ORC_PARTITION_VAR_ATT_COUNT = ORC_PARTITION_LAST_INDEX
}
Functions
void OR_PUT_FLOAT (char *ptr, float val)
void OR_PUT_DOUBLE (char *ptr, double val)
int db_string_put_cs_and_collation (DB_VALUE *value, const int codeset, const int collation_id)
int db_enum_put_cs_and_collation (DB_VALUE *value, const int codeset, const int collation_id)
int valcnv_convert_value_to_string (DB_VALUE *value)
int or_rep_id (RECDES *record)
int or_set_rep_id (RECDES *record, int repid)
int or_chn (RECDES *record)
int or_replace_chn (RECDES *record, int chn)
int or_mvcc_get_repid_and_flags (OR_BUF *buf, int *error)
int or_mvcc_set_repid_and_flags (OR_BUF *buf, int mvcc_flag, int repid, int bound_bit, int variable_offset_size)
char * or_class_name (RECDES *record)
int or_set_element_offset (char *setptr, int element)
char * or_pack_int (char *ptr, int number)
char * or_pack_int64 (char *ptr, INT64 number)
char * or_pack_float (char *ptr, float number)
char * or_pack_double (char *ptr, double number)
char * or_pack_short (char *ptr, short number)
char * or_pack_string_with_null_padding (char *ptr, const char *stream, size_t len)
char * or_pack_stream (char *ptr, const char *stream, size_t len)
char * or_pack_string (char *ptr, const char *string)
char * or_pack_string_with_length (char *ptr, const char *string, int length)
char * or_pack_errcode (char *ptr, int error)
char * or_pack_oid (char *ptr, const OID *oid)
char * or_pack_oid_array (char *ptr, int n, const OID *oids)
char * or_pack_hfid (const char *ptr, const HFID *hfid)
char * or_pack_btid (char *buf, const BTID *btid)
char * or_pack_ehid (char *buf, EHID *btid)
char * or_pack_recdes (char *buf, RECDES *recdes)
char * or_pack_log_lsa (const char *ptr, const struct log_lsa *lsa)
char * or_unpack_log_lsa (char *ptr, struct log_lsa *lsa)
char * or_unpack_set (char *ptr, setobj **set, struct tp_domain *domain)
char * or_unpack_setref (char *ptr, DB_SET **ref)
char * or_pack_listid (char *ptr, void *listid)
char * or_pack_lock (char *ptr, LOCK lock)
char * or_pack_set_header (char *buf, DB_TYPE stype, DB_TYPE etype, int bound_bits, int size)
char * or_pack_method_sig_list (char *ptr, void *method_sig_list)
char * or_pack_set_node (char *ptr, void *set_node)
char * or_pack_db_value (char *buffer, DB_VALUE *var)
char * or_unpack_db_value (char *buffer, DB_VALUE *val)
int or_db_value_size (DB_VALUE *var)
char * or_unpack_int (char *ptr, int *number)
char * or_unpack_int64 (char *ptr, INT64 *number)
char * or_unpack_int_array (char *ptr, int n, int **number_array)
char * or_unpack_longint (char *ptr, int *number)
char * or_unpack_short (char *ptr, short *number)
char * or_unpack_float (char *ptr, float *number)
char * or_unpack_double (char *ptr, double *number)
char * or_unpack_stream (char *ptr, char *stream, size_t len)
char * or_unpack_string (char *ptr, char **string)
char * or_unpack_string_alloc (char *ptr, char **string)
char * or_unpack_string_nocopy (char *ptr, char **string)
char * or_unpack_errcode (char *ptr, int *error)
char * or_unpack_oid (char *ptr, OID *oid)
char * or_unpack_oid_array (char *ptr, int n, OID **oids)
char * or_unpack_hfid (char *ptr, HFID *hfid)
char * or_unpack_hfid_array (char *ptr, int n, HFID **hfids)
char * or_unpack_btid (char *buf, BTID *btid)
char * or_unpack_ehid (char *buf, EHID *btid)
char * or_unpack_recdes (char *buf, RECDES **recdes)
char * or_unpack_listid (char *ptr, void *listid_ptr)
char * or_unpack_unbound_listid (char *ptr, void **listid_ptr)
char * or_unpack_lock (char *ptr, LOCK *lock)
char * or_unpack_set_header (char *buf, DB_TYPE *stype, DB_TYPE *etype, int *bound_bits, int *size)
char * or_unpack_method_sig_list (char *ptr, void **method_sig_list_ptr)
char * or_unpack_set_node (char *ptr, void *set_node_ptr)
char * or_pack_ptr (char *ptr, UINTPTR ptrval)
char * or_unpack_ptr (char *ptr, UINTPTR *ptrval)
char * or_pack_bool_array (char *ptr, const bool *bools, int size)
char * or_unpack_bool_array (char *ptr, bool **bools)
int or_packed_bool_array_length (const bool *bools, int size)
int or_packed_stream_length (size_t len)
int or_packed_string_length (const char *string, int *strlen)
int or_packed_varbit_length (int bitlen)
int or_varbit_length (int bitlen)
int or_packed_varchar_length (int charlen)
int or_varchar_length (int charlen)
int or_packed_recdesc_length (int length)
int or_listid_length (void *listid)
int or_method_sig_list_length (void *method_sig_list_ptr)
int or_set_node_length (void *set_node_ptr)
void or_encode (char *buffer, const char *source, int size)
void or_decode (const char *buffer, char *dest, int size)
void or_init (OR_BUF *buf, char *data, int length)
int or_overflow (OR_BUF *buf)
int or_underflow (OR_BUF *buf)
void or_abort (OR_BUF *buf)
int or_put_byte (OR_BUF *buf, int num)
int or_put_short (OR_BUF *buf, int num)
int or_put_int (OR_BUF *buf, int num)
int or_put_bigint (OR_BUF *buf, DB_BIGINT num)
int or_put_float (OR_BUF *buf, float num)
int or_put_double (OR_BUF *buf, double num)
int or_put_time (OR_BUF *buf, DB_TIME *timeval)
int or_put_utime (OR_BUF *buf, DB_UTIME *timeval)
int or_put_timestamptz (OR_BUF *buf, DB_TIMESTAMPTZ *ts_tz)
int or_put_date (OR_BUF *buf, DB_DATE *date)
int or_put_datetime (OR_BUF *buf, DB_DATETIME *datetimeval)
int or_put_datetimetz (OR_BUF *buf, DB_DATETIMETZ *datetimetz)
int or_put_monetary (OR_BUF *buf, DB_MONETARY *monetary)
int or_put_string_aligned (OR_BUF *buf, char *string)
int or_put_string_aligned_with_length (OR_BUF *buf, const char *str)
int or_put_data (OR_BUF *buf, const char *data, int length)
int or_put_oid (OR_BUF *buf, const OID *oid)
int or_put_varbit (OR_BUF *buf, const char *string, int bitlen)
int or_packed_put_varbit (OR_BUF *buf, const char *string, int bitlen)
int or_put_varchar (OR_BUF *buf, char *string, int charlen)
int or_packed_put_varchar (OR_BUF *buf, char *string, int charlen)
int or_put_align32 (OR_BUF *buf)
int or_put_offset (OR_BUF *buf, int num)
int or_put_offset_internal (OR_BUF *buf, int num, int offset_size)
int or_put_mvccid (OR_BUF *buf, MVCCID mvccid)
int or_get_byte (OR_BUF *buf, int *error)
int or_get_short (OR_BUF *buf, int *error)
int or_get_int (OR_BUF *buf, int *error)
DB_BIGINT or_get_bigint (OR_BUF *buf, int *error)
float or_get_float (OR_BUF *buf, int *error)
double or_get_double (OR_BUF *buf, int *error)
int or_get_time (OR_BUF *buf, DB_TIME *timeval)
int or_get_utime (OR_BUF *buf, DB_UTIME *timeval)
int or_get_timestamptz (OR_BUF *buf, DB_TIMESTAMPTZ *ts_tz)
int or_get_date (OR_BUF *buf, DB_DATE *date)
int or_get_datetime (OR_BUF *buf, DB_DATETIME *datetime)
int or_get_datetimetz (OR_BUF *buf, DB_DATETIMETZ *datetimetz)
int or_get_monetary (OR_BUF *buf, DB_MONETARY *monetary)
int or_get_data (OR_BUF *buf, char *data, int length)
int or_get_oid (OR_BUF *buf, OID *oid)
int or_get_offset (OR_BUF *buf, int *error)
int or_get_offset_internal (OR_BUF *buf, int *error, int offset_size)
int or_get_mvccid (OR_BUF *buf, MVCCID *mvccid)
int or_skip_varchar_remainder (OR_BUF *buf, int charlen, int align)
int or_skip_varchar (OR_BUF *buf, int align)
int or_skip_varbit (OR_BUF *buf, int align)
int or_skip_varbit_remainder (OR_BUF *buf, int bitlen, int align)
int or_advance (OR_BUF *buf, int offset)
int or_seek (OR_BUF *buf, int psn)
int or_align (OR_BUF *buf, int alignment)
int or_pad (OR_BUF *buf, int length)
int or_get_varchar_length (OR_BUF *buf, int *intval)
int or_get_align (OR_BUF *buf, int align)
int or_get_align32 (OR_BUF *buf)
int or_get_align64 (OR_BUF *buf)
int or_get_varbit_length (OR_BUF *buf, int *intval)
char * or_unpack_var_table (char *ptr, int nvars, OR_VARINFO *vars)
OR_VARINFO * or_get_var_table (OR_BUF *buf, int nvars, char *(*allocator)(int))
OR_VARINFO * or_get_var_table_internal (OR_BUF *buf, int nvars, char *(*allocator)(int), int offset_size)
int or_packed_domain_size (struct tp_domain *domain, int include_classoids)
char * or_pack_domain (char *ptr, struct tp_domain *domain, int include_classoids, int is_null)
char * or_unpack_domain (char *ptr, struct tp_domain **domain_ptr, int *is_null)
int or_put_domain (OR_BUF *buf, struct tp_domain *domain, int include_classoids, int is_null)
struct tp_domain * or_get_domain (OR_BUF *buf, struct tp_domain *dom, int *is_null)
int or_put_sub_domain (OR_BUF *buf)
void or_packed_set_info (DB_TYPE set_type, struct tp_domain *domain, int include_domain, int *bound_bits, int *offset_table, int *element_tags, int *element_size)
int or_put_set_header (OR_BUF *buf, DB_TYPE set_type, int size, int domain, int bound_bits, int offset_table, int element_tags, int common_sub_header)
int or_get_set_header (OR_BUF *buf, DB_TYPE *set_type, int *size, int *domain, int *bound_bits, int *offset_table, int *element_tags, int *common_sub_header)
int or_skip_set_header (OR_BUF *buf)
int or_packed_set_length (setobj *set, int include_domain)
void or_put_set (OR_BUF *buf, setobj *set, int include_domain)
setobj * or_get_set (OR_BUF *buf, struct tp_domain *domain)
int or_disk_set_size (OR_BUF *buf, struct tp_domain *domain, DB_TYPE *set_type)
int or_packed_value_size (const DB_VALUE *value, int collapse_null, int include_domain, int include_domain_classoids)
int or_put_value (OR_BUF *buf, DB_VALUE *value, int collapse_null, int include_domain, int include_domain_classoids)
int or_get_value (OR_BUF *buf, DB_VALUE *value, struct tp_domain *domain, int expected, bool copy)
char * or_pack_value (char *buf, DB_VALUE *value)
char * or_pack_mem_value (char *ptr, DB_VALUE *value, int *packed_len_except_alignment)
char * or_unpack_value (const char *buf, DB_VALUE *value)
char * or_unpack_mem_value (char *buf, DB_VALUE *value)
int or_packed_enumeration_size (const DB_ENUMERATION *e)
int or_put_enumeration (OR_BUF *buf, const DB_ENUMERATION *e)
int or_get_enumeration (OR_BUF *buf, DB_ENUMERATION *e)
int or_header_size (char *ptr)
char * or_pack_mvccid (char *ptr, const MVCCID mvccid)
char * or_unpack_mvccid (char *ptr, MVCCID *mvccid)
char * or_pack_sha1 (char *ptr, const SHA1Hash *sha1)
char * or_unpack_sha1 (char *ptr, SHA1Hash *sha1)
STATIC_INLINE int or_get_string_size_byte (OR_BUF *buf, int *error) __attribute__((ALWAYS_INLINE))
STATIC_INLINE int or_get_varchar_compression_lengths (OR_BUF *buf, int *compressed_size, int *decompressed_size) __attribute__((ALWAYS_INLINE))
int or_packed_spacedb_size (const SPACEDB_ALL *all, const SPACEDB_ONEVOL *vols, const SPACEDB_FILES *files)
char * or_pack_spacedb (char *ptr, const SPACEDB_ALL *all, const SPACEDB_ONEVOL *vols, const SPACEDB_FILES *files)
char * or_unpack_spacedb (char *ptr, SPACEDB_ALL *all, SPACEDB_ONEVOL **vols, SPACEDB_FILES *files)
int classobj_decompose_property_oid (const char *buffer, int *volid, int *fileid, int *pageid)
void classobj_initialize_default_expr (DB_DEFAULT_EXPR *default_expr)
int classobj_get_prop (DB_SEQ *properties, const char *name, DB_VALUE *pvalue)
Variables
int or_Type_sizes []
Macro Definition Documentation
#define ASSERT_ALIGN (ptr, alignment) (assert (PTR_ALIGN (ptr, alignment) == ptr))
Definition at line 1095 of file object_representation.h.
Referenced by btree_or_get_object(), btree_rv_record_modify_internal(), btree_rv_save_keyval_for_undo(), btree_rv_save_keyval_for_undo_two_objects(), er_get_area_error(), er_set_area_error(), logpb_locate_page(), or_get_bigint(), or_get_date(), or_get_datetime(), or_get_datetimetz(), or_get_double(), or_get_float(), or_get_int(), or_get_json_schema(), or_get_monetary(), or_get_mvccid(), or_get_oid(), or_get_short(), or_get_time(), or_get_timestamptz(), or_get_utime(), or_mvcc_get_chn(), or_mvcc_get_delid(), or_mvcc_get_insid(), or_mvcc_get_prev_version_lsa(), or_mvcc_get_repid_and_flags(), or_mvcc_set_chn(), or_mvcc_set_delid(), or_mvcc_set_insid(), or_mvcc_set_prev_version_lsa(), or_pack_bool_array(), or_pack_btid(), or_pack_ehid(), or_pack_errcode(), or_pack_float(), or_pack_hfid(), or_pack_int(), or_pack_lock(), or_pack_log_lsa(), or_pack_mvccid(), or_pack_oid(), or_pack_oid_array(), or_pack_sha1(), or_pack_short(), or_pack_stream(), or_pack_string(), or_pack_string_with_length(), or_put_bigint(), or_put_date(), or_put_datetime(), or_put_datetimetz(), or_put_double(), or_put_float(), or_put_int(), or_put_json_schema(), or_put_monetary(), or_put_mvccid(), or_put_oid(), or_put_short(), or_put_time(), or_put_timestamptz(), or_put_utime(), or_unpack_bool_array(), or_unpack_btid(), or_unpack_double(), or_unpack_ehid(), or_unpack_errcode(), or_unpack_float(), or_unpack_hfid(), or_unpack_hfid_array(), or_unpack_int(), or_unpack_int_array(), or_unpack_lock(), or_unpack_log_lsa(), or_unpack_mvccid(), or_unpack_oid(), or_unpack_oid_array(), or_unpack_sha1(), or_unpack_short(), or_unpack_stream(), or_unpack_string(), or_unpack_string_alloc(), or_unpack_string_nocopy(), or_unpack_var_table_internal(), perfmon_allocate_packed_values_buffer(), spage_add_contiguous_free_space(), spage_compact(), spage_delete(), spage_find_empty_slot(), spage_find_empty_slot_at(), spage_merge(), spage_put_helper(), spage_reduce_contiguous_free_space(), spage_split(), spage_take_out(), spage_update_record_after_compact(), spage_update_record_in_place(), stx_build_xasl_header(), sysprm_pack_assign_values(), sysprm_pack_session_parameters(), sysprm_pack_sysprm_value(), sysprm_unpack_assign_values(), sysprm_unpack_session_parameters(), sysprm_unpack_sysprm_value(), and xts_process_xasl_header().
#define BIG_VAR_OFFSET_SIZE OR_INT_SIZE /* 4byte */
Definition at line 499 of file object_representation.h.
Referenced by catcls_get_or_value_from_buffer(), catcls_get_or_value_from_class_record(), catcls_put_or_value_into_buffer(), heap_attrinfo_get_disksize(), object_disk_size(), object_size(), or_class_hfid(), or_class_rep_dir(), or_class_tde_algorithm(), or_disk_set_size(), or_find_diskattr(), or_get_all_representation(), or_get_classrep(), or_get_classrep_noindex(), or_get_current_representation(), or_get_offset(), or_get_offset_internal(), or_get_old_representation(), or_get_set(), or_get_unique_hierarchy(), or_get_var_table(), or_put_offset(), or_put_offset_internal(), or_put_set(), or_unpack_var_table(), put_substructure_set(), read_var_table(), tf_class_to_disk(), and tf_disk_to_class().
#define OR_ALIGNED_BUF (size)
Value:
union \
  { \
    double dummy; \
    char buf[(size)]; \
  }
Definition at line 1044 of file object_representation.h.
Referenced by acl_reload(), boot_add_volume_extension(), boot_backup(), boot_change_ha_mode(), boot_check_db_consistency(), boot_find_last_permanent(), boot_find_last_temp(), boot_find_number_permanent_volumes(), boot_find_number_temp_volumes(), boot_get_server_locales(), boot_get_server_timezone_checksum(), boot_heap_compact(), boot_notify_ha_log_applier_state(), boot_register_client(), boot_unregister_client(), btree_add_index(), btree_class_test_unique(), btree_delete_index(), btree_find_multi_uniques(), btree_find_unique(), btree_get_index_key_type(), btree_get_statistics(), btree_load_index(), btree_proceed_leaf(), catalog_check_rep_dir(), chksum_insert_repl_log_and_demote_table_lock(), clogin_user(), compact_db_start(), compact_db_stop(), csession_create_prepared_statement(), csession_delete_prepared_statement(), csession_drop_session_variables(), csession_end_session(), csession_find_or_create_session(), csession_get_last_insert_id(), csession_get_prepared_statement(), csession_get_row_count(), csession_get_variable(), csession_reset_cur_insert_id(), csession_set_row_count(), csession_set_session_variables(), css_process_get_eof_request(), css_refuse_connection_request(), cvacuum(), db_local_transaction_id(), disk_get_free_numpages(), disk_get_fullname(), disk_get_remarks(), disk_get_total_numpages(), es_posix_copy_file(), es_posix_create_file(), es_posix_delete_file(), es_posix_get_file_size(), es_posix_read_file(), es_posix_rename_file(), es_posix_write_file(), file_apply_tde_to_class_files(), hb_resource_receive_get_eof(), heap_create(), heap_destroy_newly_created(), heap_get_class_num_objects_pages(), heap_has_instance(), heap_reclaim_addresses(), javasp_ping_server(), javasp_status_server(), jsp_get_server_port(), jsp_send_destroy_request(), loaddb_destroy(), loaddb_fetch_status(), loaddb_init(), loaddb_install_class(), loaddb_load_batch(), loaddb_update_stats(), locator_assign_oid(), locator_check_fk_validity(), locator_delete_class_name(), locator_demote_class_lock(), locator_does_exist(), locator_fetch(), locator_fetch_all(), locator_fetch_all_reference_lockset(), locator_fetch_lockhint_classes(), locator_fetch_lockset(), locator_find_class_oid(), locator_find_lockhint_class_oids(), locator_force(), locator_get_class(), locator_get_reserved_class_name_oid(), locator_notify_isolation_incons(), locator_redistribute_partition_data(), locator_remove_class_from_index(), locator_rename_class_name(), locator_repl_force(), locator_reserve_class_names(), locator_upgrade_instances_domain(), log_checkpoint(), log_does_active_user_exist(), log_get_mvcc_snapshot(), log_reset_isolation(), log_reset_wait_msecs(), log_set_interrupt(), log_set_suppress_repl_on_transaction(), logtb_get_pack_tran_table(), logwr_get_log_pages(), net_client_logwr_send_end_msg(), net_client_ping_server(), net_client_ping_server_with_handshake(), netcl_spacedb(), netsr_spacedb(), perfmon_server_start_stats(), perfmon_server_stop_stats(), qfile_get_list_file_page(), qmgr_drop_all_query_plans(), qmgr_dump_query_cache(), qmgr_end_query(), qmgr_execute_query(), qmgr_prepare_and_execute_query(), qmgr_prepare_query(), qp_get_server_info(), repl_log_get_append_lsa(), repl_set_info(), return_error_to_client(), return_error_to_server(), sacl_dump(), sacl_reload(), sboot_add_volume_extension(), sboot_backup(), sboot_change_ha_mode(), sboot_check_db_consistency(), sboot_compact_start(), sboot_compact_stop(), sboot_find_last_permanent(), sboot_find_last_temp(), sboot_find_number_permanent_volumes(), sboot_find_number_temp_volumes(), sboot_get_locales_info(), sboot_get_timezone_checksum(), sboot_heap_compact(), sboot_notify_ha_log_applier_state(), sboot_notify_unregister_client(), sboot_register_client(), sbtree_add_index(), sbtree_class_test_unique(), sbtree_delete_index(), sbtree_find_multi_uniques(), sbtree_find_unique_internal(), sbtree_get_key_type(), sbtree_get_statistics(), sbtree_load_index(), schksum_insert_repl_log_and_demote_table_lock(), sct_check_rep_dir(), sdk_freepgs(), sdk_remarks(), sdk_totalpgs(), sdk_vlabel(), serial_decache(), serial_get_current_value(), serial_get_next_value(), server_ping(), server_ping_with_handshake(), ses_posix_copy_file(), ses_posix_create_file(), ses_posix_delete_file(), ses_posix_get_file_size(), ses_posix_read_file(), ses_posix_rename_file(), ses_posix_write_file(), sfile_apply_tde_to_class_files(), shf_create(), shf_destroy(), shf_destroy_when_new(), shf_get_class_num_objs_and_pages(), shf_has_instance(), shf_heap_reclaim_addresses(), showstmt_array_end_scan(), sjsp_get_server_port(), sloaddb_destroy(), sloaddb_fetch_status(), sloaddb_init(), sloaddb_install_class(), sloaddb_load_batch(), sloaddb_update_stats(), slocator_assign_oid(), slocator_check_fk_validity(), slocator_delete_class_name(), slocator_demote_class_lock(), slocator_does_exist(), slocator_fetch(), slocator_fetch_all(), slocator_fetch_all_reference_lockset(), slocator_fetch_lockhint_classes(), slocator_fetch_lockset(), slocator_find_class_oid(), slocator_find_lockhint_class_oids(), slocator_force(), slocator_get_class(), slocator_get_reserved_class_name_oid(), slocator_notify_isolation_incons(), slocator_redistribute_partition_data(), slocator_remove_class_from_index(), slocator_rename_class_name(), slocator_repl_force(), slocator_reserve_classnames(), slocator_upgrade_instances_domain(), slock_dump(), slog_add_lob_locator(), slog_change_state_of_locator(), slog_checkpoint(), slog_drop_lob_locator(), slog_find_lob_locator(), slogin_user(), slogpb_dump_stat(), slogtb_does_active_user_exist(), slogtb_dump_trantable(), slogtb_get_mvcc_snapshot(), slogtb_get_pack_tran_table(), slogtb_reset_isolation(), slogtb_reset_wait_msecs(), slogtb_set_suppress_repl_on_transaction(), slogwr_get_log_pages(), sm_class_check_uniques(), smnt_server_start_stats(), smnt_server_stop_stats(), sprm_server_change_parameters(), sprm_server_dump_parameters(), sprm_server_get_force_parameters(), sprm_server_obtain_parameters(), sqfile_get_list_file_page(), sqmgr_drop_all_query_plans(), sqmgr_dump_query_cache(), sqmgr_dump_query_plans(), sqmgr_end_query(), sqmgr_execute_query(), sqmgr_prepare_and_execute_query(), sqmgr_prepare_query(), sqp_get_server_info(), sqp_get_sys_timestamp(), sqst_server_get_statistics(), sqst_update_all_statistics(), sqst_update_statistics(), srepl_log_get_append_lsa(), srepl_set_info(), sserial_decache(), sserial_get_current_value(), sserial_get_next_value(), ssession_create_prepared_statement(), ssession_delete_prepared_statement(), ssession_drop_session_variables(), ssession_end_session(), ssession_find_or_create_session(), ssession_get_last_insert_id(), ssession_get_prepared_statement(), ssession_get_row_count(), ssession_get_session_variable(), ssession_reset_cur_insert_id(), ssession_set_row_count(), ssession_set_session_variables(), stats_get_statistics_from_server(), stats_update_all_statistics(), stats_update_statistics(), stde_change_mk_on_server(), stde_get_data_keys(), stde_get_mk_file_path(), stde_get_mk_info(), sthread_dump_cs_stat(), sthread_kill_or_interrupt_tran(), sthread_kill_tran_index(), stran_get_local_transaction_id(), stran_is_blocked(), stran_lock_rep_read(), stran_server_2pc_attach_global_tran(), stran_server_2pc_prepare(), stran_server_2pc_prepare_global_tran(), stran_server_2pc_start(), stran_server_abort(), stran_server_commit(), stran_server_end_topop(), stran_server_get_global_tran_info(), stran_server_has_updated(), stran_server_is_active_and_has_updated(), stran_server_partial_abort(), stran_server_savepoint(), stran_server_set_global_tran_info(), stran_server_start_topop(), stran_wait_server_active_trans(), svacuum(), svacuum_dump(), sysprm_change_server_parameters(), sysprm_get_force_server_parameters(), sysprm_obtain_server_parameters(), tde_change_mk_on_server(), tde_get_mk_file_path(), tde_get_mk_info(), thread_kill_or_interrupt_tran(), thread_kill_tran_index(), tran_is_blocked(), tran_lock_rep_read(), tran_server_2pc_attach_global_tran(), tran_server_2pc_prepare(), tran_server_2pc_prepare_global_tran(), tran_server_2pc_recovery_prepared(), tran_server_2pc_start(), tran_server_abort(), tran_server_commit(), tran_server_get_global_tran_info(), tran_server_has_updated(), tran_server_is_active_and_has_updated(), tran_server_partial_abort(), tran_server_savepoint(), tran_server_set_global_tran_info(), tran_wait_server_active_trans(), xcallback_console_print(), xio_send_user_prompt_to_client(), xlog_send_log_pages_to_client(), xs_send_action_to_client(), xs_send_method_call_info_to_client(), xts_save_aggregate_type(), xts_save_analytic_eval_type(), xts_save_analytic_type(), xts_save_arith_type(), xts_save_cache_attrinfo(), xts_save_db_value(), xts_save_filter_pred_node(), xts_save_func_pred(), xts_save_function_type(), xts_save_indx_info(), xts_save_list_id(), xts_save_method_sig(), xts_save_method_sig_list(), xts_save_outptr_list(), xts_save_pred_expr(), xts_save_regu_variable(), xts_save_selupd_list(), xts_save_sort_list(), xts_save_srlist_id(), xts_save_val_list(), and xts_save_xasl_node().
#define OR_ALIGNED_BUF_SIZE (abuf) (sizeof (abuf.buf))
Definition at line 1052 of file object_representation.h.
Referenced by acl_reload(), boot_add_volume_extension(), boot_backup(), boot_change_ha_mode(), boot_check_db_consistency(), boot_find_last_permanent(), boot_find_last_temp(), boot_find_number_permanent_volumes(), boot_find_number_temp_volumes(), boot_get_server_locales(), boot_get_server_timezone_checksum(), boot_notify_ha_log_applier_state(), boot_register_client(), boot_unregister_client(), btree_add_index(), btree_class_test_unique(), btree_delete_index(), btree_find_multi_uniques(), btree_find_unique(), btree_get_index_key_type(), btree_get_statistics(), btree_load_index(), catalog_check_rep_dir(), chksum_insert_repl_log_and_demote_table_lock(), clogin_user(), csession_create_prepared_statement(), csession_delete_prepared_statement(), csession_drop_session_variables(), csession_end_session(), csession_find_or_create_session(), csession_get_last_insert_id(), csession_get_prepared_statement(), csession_get_row_count(), csession_get_variable(), csession_reset_cur_insert_id(), csession_set_row_count(), csession_set_session_variables(), css_process_get_eof_request(), cvacuum(), db_local_transaction_id(), disk_get_free_numpages(), disk_get_fullname(), disk_get_remarks(), disk_get_total_numpages(), es_posix_copy_file(), es_posix_create_file(), es_posix_delete_file(), es_posix_get_file_size(), es_posix_read_file(), es_posix_rename_file(), es_posix_write_file(), file_apply_tde_to_class_files(), hb_resource_receive_get_eof(), heap_create(), heap_destroy_newly_created(), heap_get_class_num_objects_pages(), heap_has_instance(), heap_reclaim_addresses(), jsp_get_server_port(), loaddb_destroy(), loaddb_fetch_status(), loaddb_init(), loaddb_install_class(), loaddb_load_batch(), loaddb_update_stats(), locator_assign_oid(), locator_check_fk_validity(), locator_delete_class_name(), locator_demote_class_lock(), locator_does_exist(), locator_fetch(), locator_fetch_all(), locator_fetch_all_reference_lockset(), locator_fetch_lockhint_classes(), locator_fetch_lockset(), locator_find_class_oid(), locator_find_lockhint_class_oids(), locator_force(), locator_get_class(), locator_get_reserved_class_name_oid(), locator_notify_isolation_incons(), locator_redistribute_partition_data(), locator_remove_class_from_index(), locator_rename_class_name(), locator_repl_force(), locator_reserve_class_names(), locator_upgrade_instances_domain(), log_checkpoint(), log_does_active_user_exist(), log_get_mvcc_snapshot(), log_reset_isolation(), log_reset_wait_msecs(), log_set_interrupt(), log_set_suppress_repl_on_transaction(), logtb_get_pack_tran_table(), logwr_get_log_pages(), net_client_logwr_send_end_msg(), net_client_ping_server_with_handshake(), netcl_spacedb(), netsr_spacedb(), perfmon_server_start_stats(), perfmon_server_stop_stats(), qfile_get_list_file_page(), qmgr_drop_all_query_plans(), qmgr_dump_query_cache(), qmgr_end_query(), qmgr_execute_query(), qmgr_prepare_and_execute_query(), qmgr_prepare_query(), qp_get_server_info(), repl_log_get_append_lsa(), repl_set_info(), sacl_dump(), sacl_reload(), sboot_add_volume_extension(), sboot_backup(), sboot_change_ha_mode(), sboot_check_db_consistency(), sboot_compact_start(), sboot_compact_stop(), sboot_find_last_permanent(), sboot_find_last_temp(), sboot_find_number_permanent_volumes(), sboot_find_number_temp_volumes(), sboot_get_locales_info(), sboot_get_timezone_checksum(), sboot_heap_compact(), sboot_notify_ha_log_applier_state(), sboot_notify_unregister_client(), sboot_register_client(), sbtree_add_index(), sbtree_class_test_unique(), sbtree_delete_index(), sbtree_find_multi_uniques(), sbtree_find_unique_internal(), sbtree_get_key_type(), sbtree_get_statistics(), sbtree_load_index(), schksum_insert_repl_log_and_demote_table_lock(), sct_check_rep_dir(), sdk_freepgs(), sdk_remarks(), sdk_totalpgs(), sdk_vlabel(), serial_decache(), serial_get_current_value(), serial_get_next_value(), server_ping_with_handshake(), ses_posix_copy_file(), ses_posix_create_file(), ses_posix_delete_file(), ses_posix_get_file_size(), ses_posix_read_file(), ses_posix_rename_file(), ses_posix_write_file(), sfile_apply_tde_to_class_files(), shf_create(), shf_destroy(), shf_destroy_when_new(), shf_get_class_num_objs_and_pages(), shf_has_instance(), shf_heap_reclaim_addresses(), sjsp_get_server_port(), sloaddb_destroy(), sloaddb_fetch_status(), sloaddb_init(), sloaddb_install_class(), sloaddb_load_batch(), sloaddb_update_stats(), slocator_assign_oid(), slocator_check_fk_validity(), slocator_delete_class_name(), slocator_demote_class_lock(), slocator_does_exist(), slocator_fetch(), slocator_fetch_all(), slocator_fetch_all_reference_lockset(), slocator_fetch_lockhint_classes(), slocator_fetch_lockset(), slocator_find_class_oid(), slocator_find_lockhint_class_oids(), slocator_force(), slocator_get_class(), slocator_get_reserved_class_name_oid(), slocator_notify_isolation_incons(), slocator_redistribute_partition_data(), slocator_remove_class_from_index(), slocator_rename_class_name(), slocator_repl_force(), slocator_reserve_classnames(), slocator_upgrade_instances_domain(), slock_dump(), slog_add_lob_locator(), slog_change_state_of_locator(), slog_checkpoint(), slog_drop_lob_locator(), slog_find_lob_locator(), slogin_user(), slogpb_dump_stat(), slogtb_does_active_user_exist(), slogtb_dump_trantable(), slogtb_get_mvcc_snapshot(), slogtb_get_pack_tran_table(), slogtb_reset_isolation(), slogtb_reset_wait_msecs(), slogtb_set_suppress_repl_on_transaction(), slogwr_get_log_pages(), smnt_server_start_stats(), smnt_server_stop_stats(), sprm_server_change_parameters(), sprm_server_dump_parameters(), sprm_server_get_force_parameters(), sprm_server_obtain_parameters(), sqfile_get_list_file_page(), sqmgr_drop_all_query_plans(), sqmgr_dump_query_cache(), sqmgr_dump_query_plans(), sqmgr_end_query(), sqmgr_execute_query(), sqmgr_prepare_and_execute_query(), sqmgr_prepare_query(), sqp_get_server_info(), sqp_get_sys_timestamp(), sqst_server_get_statistics(), sqst_update_all_statistics(), sqst_update_statistics(), srepl_log_get_append_lsa(), srepl_set_info(), sserial_decache(), sserial_get_current_value(), sserial_get_next_value(), ssession_create_prepared_statement(), ssession_delete_prepared_statement(), ssession_drop_session_variables(), ssession_end_session(), ssession_find_or_create_session(), ssession_get_last_insert_id(), ssession_get_prepared_statement(), ssession_get_row_count(), ssession_get_session_variable(), ssession_reset_cur_insert_id(), ssession_set_row_count(), ssession_set_session_variables(), stats_get_statistics_from_server(), stats_update_all_statistics(), stats_update_statistics(), stde_change_mk_on_server(), stde_get_data_keys(), stde_get_mk_file_path(), stde_get_mk_info(), sthread_dump_cs_stat(), sthread_kill_or_interrupt_tran(), sthread_kill_tran_index(), stran_get_local_transaction_id(), stran_is_blocked(), stran_lock_rep_read(), stran_server_2pc_attach_global_tran(), stran_server_2pc_prepare(), stran_server_2pc_prepare_global_tran(), stran_server_2pc_start(), stran_server_abort(), stran_server_commit(), stran_server_end_topop(), stran_server_get_global_tran_info(), stran_server_has_updated(), stran_server_is_active_and_has_updated(), stran_server_partial_abort(), stran_server_savepoint(), stran_server_set_global_tran_info(), stran_server_start_topop(), stran_wait_server_active_trans(), svacuum(), svacuum_dump(), sysprm_change_server_parameters(), sysprm_get_force_server_parameters(), sysprm_obtain_server_parameters(), tde_change_mk_on_server(), tde_get_mk_file_path(), tde_get_mk_info(), thread_kill_or_interrupt_tran(), thread_kill_tran_index(), tran_is_blocked(), tran_lock_rep_read(), tran_server_2pc_attach_global_tran(), tran_server_2pc_prepare(), tran_server_2pc_prepare_global_tran(), tran_server_2pc_recovery_prepared(), tran_server_2pc_start(), tran_server_abort(), tran_server_commit(), tran_server_get_global_tran_info(), tran_server_has_updated(), tran_server_is_active_and_has_updated(), tran_server_partial_abort(), tran_server_savepoint(), tran_server_set_global_tran_info(), tran_wait_server_active_trans(), xcallback_console_print(), xio_send_user_prompt_to_client(), xlog_send_log_pages_to_client(), xs_send_method_call_info_to_client(), xts_save_aggregate_type(), xts_save_analytic_eval_type(), xts_save_analytic_type(), xts_save_arith_type(), xts_save_cache_attrinfo(), xts_save_db_value(), xts_save_filter_pred_node(), xts_save_func_pred(), xts_save_function_type(), xts_save_indx_info(), xts_save_list_id(), xts_save_method_sig(), xts_save_method_sig_list(), xts_save_outptr_list(), xts_save_pred_expr(), xts_save_regu_variable(), xts_save_selupd_list(), xts_save_sort_list(), xts_save_srlist_id(), xts_save_val_list(), and xts_save_xasl_node().
#define OR_ALIGNED_BUF_START (abuf) (abuf.buf)
Definition at line 1051 of file object_representation.h.
Referenced by acl_reload(), boot_add_volume_extension(), boot_backup(), boot_change_ha_mode(), boot_check_db_consistency(), boot_find_last_permanent(), boot_find_last_temp(), boot_find_number_permanent_volumes(), boot_find_number_temp_volumes(), boot_get_server_locales(), boot_get_server_timezone_checksum(), boot_heap_compact(), boot_notify_ha_log_applier_state(), boot_register_client(), boot_unregister_client(), btree_add_index(), btree_class_test_unique(), btree_delete_index(), btree_find_multi_uniques(), btree_find_unique(), btree_get_index_key_type(), btree_get_statistics(), btree_load_index(), btree_proceed_leaf(), catalog_check_rep_dir(), chksum_insert_repl_log_and_demote_table_lock(), clogin_user(), compact_db_start(), compact_db_stop(), csession_create_prepared_statement(), csession_delete_prepared_statement(), csession_drop_session_variables(), csession_end_session(), csession_find_or_create_session(), csession_get_last_insert_id(), csession_get_prepared_statement(), csession_get_row_count(), csession_get_variable(), csession_reset_cur_insert_id(), csession_set_row_count(), csession_set_session_variables(), css_process_get_eof_request(), css_refuse_connection_request(), cvacuum(), db_local_transaction_id(), disk_get_free_numpages(), disk_get_fullname(), disk_get_remarks(), disk_get_total_numpages(), es_posix_copy_file(), es_posix_create_file(), es_posix_delete_file(), es_posix_get_file_size(), es_posix_read_file(), es_posix_rename_file(), es_posix_write_file(), file_apply_tde_to_class_files(), hb_resource_receive_get_eof(), heap_create(), heap_destroy_newly_created(), heap_get_class_num_objects_pages(), heap_has_instance(), heap_reclaim_addresses(), javasp_ping_server(), javasp_status_server(), jsp_get_server_port(), jsp_send_destroy_request(), loaddb_destroy(), loaddb_fetch_status(), loaddb_init(), loaddb_install_class(), loaddb_load_batch(), loaddb_update_stats(), locator_assign_oid(), locator_check_fk_validity(), locator_delete_class_name(), locator_demote_class_lock(), locator_does_exist(), locator_fetch(), locator_fetch_all(), locator_fetch_all_reference_lockset(), locator_fetch_lockhint_classes(), locator_fetch_lockset(), locator_find_class_oid(), locator_find_lockhint_class_oids(), locator_force(), locator_get_class(), locator_get_reserved_class_name_oid(), locator_notify_isolation_incons(), locator_redistribute_partition_data(), locator_remove_class_from_index(), locator_rename_class_name(), locator_repl_force(), locator_reserve_class_names(), locator_upgrade_instances_domain(), log_checkpoint(), log_does_active_user_exist(), log_get_mvcc_snapshot(), log_reset_isolation(), log_reset_wait_msecs(), log_set_interrupt(), log_set_suppress_repl_on_transaction(), logtb_get_pack_tran_table(), logwr_get_log_pages(), net_client_logwr_send_end_msg(), net_client_ping_server(), net_client_ping_server_with_handshake(), netcl_spacedb(), netsr_spacedb(), perfmon_server_start_stats(), perfmon_server_stop_stats(), qfile_get_list_file_page(), qmgr_drop_all_query_plans(), qmgr_dump_query_cache(), qmgr_end_query(), qmgr_execute_query(), qmgr_prepare_and_execute_query(), qmgr_prepare_query(), qp_get_server_info(), repl_log_get_append_lsa(), repl_set_info(), return_error_to_client(), return_error_to_server(), sacl_dump(), sacl_reload(), sboot_add_volume_extension(), sboot_backup(), sboot_change_ha_mode(), sboot_check_db_consistency(), sboot_compact_start(), sboot_compact_stop(), sboot_find_last_permanent(), sboot_find_last_temp(), sboot_find_number_permanent_volumes(), sboot_find_number_temp_volumes(), sboot_get_locales_info(), sboot_get_timezone_checksum(), sboot_heap_compact(), sboot_notify_ha_log_applier_state(), sboot_notify_unregister_client(), sboot_register_client(), sbtree_add_index(), sbtree_class_test_unique(), sbtree_delete_index(), sbtree_find_multi_uniques(), sbtree_find_unique_internal(), sbtree_get_key_type(), sbtree_get_statistics(), sbtree_load_index(), schksum_insert_repl_log_and_demote_table_lock(), sct_check_rep_dir(), sdk_freepgs(), sdk_remarks(), sdk_totalpgs(), sdk_vlabel(), serial_decache(), serial_get_current_value(), serial_get_next_value(), server_ping(), server_ping_with_handshake(), ses_posix_copy_file(), ses_posix_create_file(), ses_posix_delete_file(), ses_posix_get_file_size(), ses_posix_read_file(), ses_posix_rename_file(), ses_posix_write_file(), sfile_apply_tde_to_class_files(), shf_create(), shf_destroy(), shf_destroy_when_new(), shf_get_class_num_objs_and_pages(), shf_has_instance(), shf_heap_reclaim_addresses(), showstmt_array_end_scan(), sjsp_get_server_port(), sloaddb_destroy(), sloaddb_fetch_status(), sloaddb_init(), sloaddb_install_class(), sloaddb_load_batch(), sloaddb_update_stats(), slocator_assign_oid(), slocator_check_fk_validity(), slocator_delete_class_name(), slocator_demote_class_lock(), slocator_does_exist(), slocator_fetch(), slocator_fetch_all(), slocator_fetch_all_reference_lockset(), slocator_fetch_lockhint_classes(), slocator_fetch_lockset(), slocator_find_class_oid(), slocator_find_lockhint_class_oids(), slocator_force(), slocator_get_class(), slocator_get_reserved_class_name_oid(), slocator_notify_isolation_incons(), slocator_redistribute_partition_data(), slocator_remove_class_from_index(), slocator_rename_class_name(), slocator_repl_force(), slocator_reserve_classnames(), slocator_upgrade_instances_domain(), slock_dump(), slog_add_lob_locator(), slog_change_state_of_locator(), slog_checkpoint(), slog_drop_lob_locator(), slog_find_lob_locator(), slogin_user(), slogpb_dump_stat(), slogtb_does_active_user_exist(), slogtb_dump_trantable(), slogtb_get_mvcc_snapshot(), slogtb_get_pack_tran_table(), slogtb_reset_isolation(), slogtb_reset_wait_msecs(), slogtb_set_suppress_repl_on_transaction(), slogwr_get_log_pages(), sm_class_check_uniques(), smnt_server_start_stats(), smnt_server_stop_stats(), sprm_server_change_parameters(), sprm_server_dump_parameters(), sprm_server_get_force_parameters(), sprm_server_obtain_parameters(), sqfile_get_list_file_page(), sqmgr_drop_all_query_plans(), sqmgr_dump_query_cache(), sqmgr_dump_query_plans(), sqmgr_end_query(), sqmgr_execute_query(), sqmgr_prepare_and_execute_query(), sqmgr_prepare_query(), sqp_get_server_info(), sqp_get_sys_timestamp(), sqst_server_get_statistics(), sqst_update_all_statistics(), sqst_update_statistics(), srepl_log_get_append_lsa(), srepl_set_info(), sserial_decache(), sserial_get_current_value(), sserial_get_next_value(), ssession_create_prepared_statement(), ssession_delete_prepared_statement(), ssession_drop_session_variables(), ssession_end_session(), ssession_find_or_create_session(), ssession_get_last_insert_id(), ssession_get_prepared_statement(), ssession_get_row_count(), ssession_get_session_variable(), ssession_reset_cur_insert_id(), ssession_set_row_count(), ssession_set_session_variables(), stats_get_statistics_from_server(), stats_update_all_statistics(), stats_update_statistics(), stde_change_mk_on_server(), stde_get_data_keys(), stde_get_mk_file_path(), stde_get_mk_info(), sthread_dump_cs_stat(), sthread_kill_or_interrupt_tran(), sthread_kill_tran_index(), stran_get_local_transaction_id(), stran_is_blocked(), stran_lock_rep_read(), stran_server_2pc_attach_global_tran(), stran_server_2pc_prepare(), stran_server_2pc_prepare_global_tran(), stran_server_2pc_start(), stran_server_abort(), stran_server_commit(), stran_server_end_topop(), stran_server_get_global_tran_info(), stran_server_has_updated(), stran_server_is_active_and_has_updated(), stran_server_partial_abort(), stran_server_savepoint(), stran_server_set_global_tran_info(), stran_server_start_topop(), stran_wait_server_active_trans(), svacuum(), svacuum_dump(), sysprm_change_server_parameters(), sysprm_get_force_server_parameters(), sysprm_obtain_server_parameters(), tde_change_mk_on_server(), tde_get_mk_file_path(), tde_get_mk_info(), thread_kill_or_interrupt_tran(), thread_kill_tran_index(), tran_is_blocked(), tran_lock_rep_read(), tran_server_2pc_attach_global_tran(), tran_server_2pc_prepare(), tran_server_2pc_prepare_global_tran(), tran_server_2pc_recovery_prepared(), tran_server_2pc_start(), tran_server_abort(), tran_server_commit(), tran_server_get_global_tran_info(), tran_server_has_updated(), tran_server_is_active_and_has_updated(), tran_server_partial_abort(), tran_server_savepoint(), tran_server_set_global_tran_info(), tran_wait_server_active_trans(), xcallback_console_print(), xio_send_user_prompt_to_client(), xlog_send_log_pages_to_client(), xs_send_action_to_client(), xs_send_method_call_info_to_client(), xts_save_aggregate_type(), xts_save_analytic_eval_type(), xts_save_analytic_type(), xts_save_arith_type(), xts_save_cache_attrinfo(), xts_save_db_value(), xts_save_filter_pred_node(), xts_save_func_pred(), xts_save_function_type(), xts_save_indx_info(), xts_save_list_id(), xts_save_method_sig(), xts_save_method_sig_list(), xts_save_outptr_list(), xts_save_pred_expr(), xts_save_regu_variable(), xts_save_selupd_list(), xts_save_sort_list(), xts_save_srlist_id(), xts_save_val_list(), and xts_save_xasl_node().
#define OR_BINARY_LENGTH_MASK 0xFFFF
Definition at line 970 of file object_representation.h.
#define OR_BINARY_MAX_LENGTH 65535
Definition at line 969 of file object_representation.h.
Referenced by or_put_string_aligned().
#define OR_BINARY_PAD_SHIFT 16
Definition at line 971 of file object_representation.h.
Referenced by or_put_string_aligned().
#define OR_BOUND_BIT_BYTES (count) ((((count) + 31) >> 5) * 4)
Definition at line 596 of file object_representation.h.
Referenced by catcls_get_or_value_from_buffer(), catcls_guess_record_length(), catcls_put_or_value_into_buffer(), get_current(), get_desc_current(), get_desc_old(), get_old(), heap_attrinfo_get_disksize(), heap_attrinfo_transform_to_disk_internal(), la_get_current(), object_disk_size(), object_size(), or_disk_set_size(), or_get_set(), or_packed_set_length(), or_put_set(), or_skip_set_header(), put_attributes(), and put_varinfo().
#define OR_BOUND_BIT_FLAG 0x80000000
Definition at line 497 of file object_representation.h.
Referenced by catcls_get_or_value_from_buffer(), catcls_put_or_value_into_buffer(), desc_disk_to_obj(), desc_obj_to_disk(), heap_attrinfo_transform_to_disk_internal(), heap_rv_mvcc_redo_insert(), heap_rv_mvcc_redo_redistribute(), la_disk_to_obj(), or_mvcc_set_header(), or_mvcc_set_repid_and_flags(), or_replace_rep_id(), tf_disk_to_mem(), and tf_mem_to_disk().
#define OR_BOUND_BIT_MASK (element) (1 << ((int) (element) & 7))
Definition at line 598 of file object_representation.h.
#define OR_BOUND_BIT_WORDS (count) (((count) + 31) >> 5)
Definition at line 595 of file object_representation.h.
Referenced by obj_alloc().
#define OR_BUF_INIT (buf, data, size)
Value:
do { \
    (buf).buffer = (buf).ptr = (data); \
    (buf).endptr = ((size) <= 0 || (size) == DB_INT32_MAX) \
                    ? (char *) OR_INFINITE_POINTER : (data) + (size); \
    (buf).error_abort = 0; \
    (buf).fixups = NULL; \
  } while (0)
Definition at line 1071 of file object_representation.h.
Referenced by btree_key_insert_new_key(), btree_pack_object(), compare_driver(), cubpacking::packer::delegate_to_or_buf(), cubpacking::unpacker::delegate_to_or_buf(), do_create_midxkey_for_constraint(), eval_item_card_sort_list(), eval_some_list_eval(), eval_sub_sort_list_to_multi_set(), eval_sub_sort_list_to_sort_list(), fetch_peek_dbval(), fetch_peek_dbval_pos(), log_rv_undoredo_record_partial_changes(), or_get_attr_string(), or_mvcc_add_header(), or_mvcc_set_flag(), or_mvcc_set_header(), or_replace_chn(), or_replace_rep_id(), or_set_rep_id(), pr_midxkey_compare_element(), qdata_copy_db_value_to_tuple_value(), qdata_evaluate_aggregate_list(), qdata_evaluate_analytic_func(), qdata_get_single_tuple_from_list_id(), qdata_load_agg_hentry_from_tuple(), qexec_analytic_sort_key_header_load(), qexec_get_tuple_column_value(), qfile_compare_with_interpolation_domain(), qfile_fast_intval_tuple_to_list(), qfile_fast_val_tuple_to_list(), qfile_locate_tuple_next_value(), qfile_set_tuple_column_value(), and scan_dbvals_to_midxkey().
#define OR_BUF_INIT2 (buf, data, size)
Value:
do { \
    (buf).buffer = (buf).ptr = (data); \
    (buf).endptr = ((size) <= 0 || (size) == DB_INT32_MAX) \
                    ? (char *) OR_INFINITE_POINTER : (data) + (size); \
    (buf).error_abort = 1; \
    (buf).fixups = NULL; \
  } while (0)
Definition at line 1080 of file object_representation.h.
Referenced by heap_attrinfo_transform_to_disk_internal(), and heap_attrvalue_read().
#define OR_CHECK_ADD_OVERFLOW (a, b, c)
Value:
(((a) > 0 && (b) > 0 && (c) < 0) \
   || ((a) < 0 && (b) < 0 && (c) >= 0))
Definition at line 60 of file object_representation.h.
Referenced by db_add_int_to_datetime(), pt_evaluate_db_value_expr(), qdata_add_bigint(), qdata_add_int(), qdata_add_short(), and qdata_increment_dbval().
#define OR_CHECK_ASSIGN_OVERFLOW (dest, src) (((src) > 0 && (dest) < 0) || ((src) < 0 && (dest) > 0))
Definition at line 58 of file object_representation.h.
Referenced by tp_value_cast_internal().
#define OR_CHECK_BIGINT_DIV_OVERFLOW (a, b) ((a) == DB_BIGINT_MIN && (b) == -1)
Definition at line 76 of file object_representation.h.
Referenced by pt_evaluate_db_value_expr(), and qdata_divmod_dbval().
#define OR_CHECK_BIGINT_OVERFLOW (i) ((i) > DB_BIGINT_MAX || (i) < DB_BIGINT_MIN)
Definition at line 81 of file object_representation.h.
Referenced by qdata_get_interpolation_function_result(), tp_value_cast_internal(), and tp_value_coerce_strict().
#define OR_CHECK_DOUBLE_OVERFLOW (i) ((i) > DBL_MAX || (-(i)) > DBL_MAX)
Definition at line 86 of file object_representation.h.
Referenced by db_exp_dbval(), db_power_dbval(), db_width_bucket(), db_width_bucket_calculate_numeric(), ldr_double_elem(), ldr_monetary_elem(), ldr_real_db_double(), numeric_db_value_coerce_from_num(), numeric_db_value_coerce_from_num_strict(), pt_evaluate_db_value_expr(), qdata_add_double(), qdata_add_monetary(), qdata_divide_double(), qdata_divide_monetary(), qdata_multiply_double(), qdata_multiply_monetary(), qdata_subtract_double(), qdata_subtract_monetary(), cubload::to_db_double(), and cubload::to_db_monetary().
#define OR_CHECK_FLOAT_OVERFLOW (i) ((i) > FLT_MAX || (-(i)) > FLT_MAX)
Definition at line 85 of file object_representation.h.
Referenced by ldr_float_elem(), ldr_real_db_float(), numeric_db_value_coerce_from_num(), numeric_db_value_coerce_from_num_strict(), pt_evaluate_db_value_expr(), qdata_add_float(), qdata_divide_float(), qdata_multiply_float(), qdata_subtract_float(), cubload::to_db_float(), tp_value_cast_internal(), and tp_value_coerce_strict().
#define OR_CHECK_INT_DIV_OVERFLOW (a, b) ((a) == DB_INT32_MIN && (b) == -1)
Definition at line 74 of file object_representation.h.
Referenced by pt_evaluate_db_value_expr(), and qdata_divmod_dbval().
#define OR_CHECK_INT_OVERFLOW (i) ((i) > DB_INT32_MAX || (i) < DB_INT32_MIN)
Definition at line 80 of file object_representation.h.
Referenced by db_add_int_to_datetime(), db_string_repeat(), db_subtract_int_from_datetime(), db_sys_timestamp(), db_timestamp_encode_utc(), db_width_bucket(), ldr_int_db_int(), numeric_db_value_coerce_from_num(), numeric_db_value_coerce_from_num_strict(), pt_evaluate_db_value_expr(), cubload::to_db_int(), tp_value_cast_internal(), and tp_value_coerce_strict().
#define OR_CHECK_MULT_OVERFLOW (a, b, c) (((b) == 0) ? ((c) != 0) : ((c) / (b) != (a)))
Definition at line 70 of file object_representation.h.
Referenced by pt_evaluate_db_value_expr(), qdata_multiply_bigint(), qdata_multiply_int(), and qdata_multiply_short().
#define OR_CHECK_SHORT_DIV_OVERFLOW (a, b) ((a) == DB_INT16_MIN && (b) == -1)
Definition at line 72 of file object_representation.h.
Referenced by pt_evaluate_db_value_expr(), and qdata_divmod_dbval().
#define OR_CHECK_SHORT_OVERFLOW (i) ((i) > DB_INT16_MAX || (i) < DB_INT16_MIN)
Definition at line 79 of file object_representation.h.
Referenced by ldr_int_db_short(), numeric_db_value_coerce_from_num(), numeric_db_value_coerce_from_num_strict(), cubload::to_db_short(), tp_value_cast_internal(), and tp_value_coerce_strict().
#define OR_CHECK_SUB_UNDERFLOW (a, b, c)
Value:
(((a) < (b) && (c) > 0) \
   || ((a) > (b) && (c) < 0))
Definition at line 65 of file object_representation.h.
Referenced by db_subtract_int_from_datetime(), pt_evaluate_db_value_expr(), qdata_increment_dbval(), qdata_subtract_bigint(), qdata_subtract_date_to_dbval(), qdata_subtract_datetime(), qdata_subtract_int(), and qdata_subtract_short().
#define OR_CHECK_UINT_OVERFLOW (i) ((i) > DB_UINT32_MAX || (i) < 0)
Definition at line 83 of file object_representation.h.
Referenced by qdata_subtract_date_to_dbval().
#define OR_CHECK_UNS_ADD_OVERFLOW (a, b, c) (c) < (a) || (c) < (b)
Definition at line 63 of file object_representation.h.
Referenced by pt_evaluate_db_value_expr(), qdata_add_bigint_to_date(), qdata_add_bigint_to_timestamptz(), qdata_add_bigint_to_utime(), qdata_add_int_to_date(), qdata_add_int_to_timestamptz(), qdata_add_int_to_utime(), qdata_add_short_to_date(), qdata_add_short_to_timestamptz(), and qdata_add_short_to_utime().
#define OR_CHECK_UNS_SUB_UNDERFLOW (a, b, c) (b) > (a)
Definition at line 68 of file object_representation.h.
Referenced by pt_evaluate_db_value_expr(), qdata_subtract_bigint_to_dbval(), qdata_subtract_date_to_dbval(), qdata_subtract_int_to_dbval(), qdata_subtract_short_to_dbval(), and qdata_subtract_utime().
#define OR_CHECK_USHRT_OVERFLOW (i) ((i) > (int) DB_UINT16_MAX || (i) < 0)
Definition at line 82 of file object_representation.h.
Referenced by tp_value_cast_internal().
#define OR_CHN_OFFSET (OR_REP_OFFSET + OR_MVCC_REP_SIZE)
Definition at line 472 of file object_representation.h.
Referenced by heap_mvcc_log_insert(), or_chn(), and or_replace_chn().
#define OR_CHN_SIZE 4
Definition at line 473 of file object_representation.h.
Referenced by or_chn().
#define OR_CLEAR_BOUND_BIT (bitptr, element) *OR_GET_BOUND_BIT_BYTE (bitptr, element) = *OR_GET_BOUND_BIT_BYTE (bitptr, element) & ~OR_BOUND_BIT_MASK (element)
Definition at line 622 of file object_representation.h.
Referenced by catcls_put_or_value_into_buffer(), do_create_midxkey_for_constraint(), heap_attrinfo_transform_to_disk_internal(), and scan_dbvals_to_midxkey().
#define OR_ENABLE_BOUND_BIT (bitptr, element) *OR_GET_BOUND_BIT_BYTE (bitptr, element) = *OR_GET_BOUND_BIT_BYTE (bitptr, element) | OR_BOUND_BIT_MASK (element)
Definition at line 619 of file object_representation.h.
Referenced by catcls_put_or_value_into_buffer(), do_create_midxkey_for_constraint(), heap_attrinfo_transform_to_disk_internal(), heap_midxkey_key_generate(), heap_midxkey_key_get(), pr_midxkey_add_elements(), put_attributes(), and scan_dbvals_to_midxkey().
#define OR_FIXED_ATT_IS_BOUND (obj, nvars, fsize, position) (!OR_GET_BOUND_BIT_FLAG (obj) || OR_GET_BOUND_BIT (OR_GET_BOUND_BITS (obj, nvars, fsize), position))
Definition at line 613 of file object_representation.h.
#define OR_FIXED_ATT_IS_UNBOUND (obj, nvars, fsize, position) (OR_GET_BOUND_BIT_FLAG (obj) && !OR_GET_BOUND_BIT (OR_GET_BOUND_BITS (obj, nvars, fsize), position))
Definition at line 616 of file object_representation.h.
Referenced by heap_attrvalue_read(), and heap_midxkey_get_value().
#define OR_FIXED_ATTRIBUTES_OFFSET (ptr, nvars) (OR_FIXED_ATTRIBUTES_OFFSET_INTERNAL (ptr, nvars, BIG_VAR_OFFSET_SIZE))
Definition at line 452 of file object_representation.h.
Referenced by locator_insert_force(), locator_update_force(), or_class_hfid(), or_class_rep_dir(), or_class_tde_algorithm(), or_find_diskattr(), or_get_current_representation(), and or_get_unique_hierarchy().
#define OR_FIXED_ATTRIBUTES_OFFSET_INTERNAL (ptr, nvars, offset_size) (OR_HEADER_SIZE (ptr) + OR_VAR_TABLE_SIZE_INTERNAL (nvars, offset_size))
Definition at line 455 of file object_representation.h.
#define OR_GET_BIG_VAR_OFFSET (ptr) OR_GET_INT (ptr) /* 4byte */
Definition at line 125 of file object_representation.h.
#define OR_GET_BIGINT (ptr, val) OR_GET_INT64 (ptr, val)
Definition at line 193 of file object_representation.h.
Referenced by jsp_unpack_bigint_value(), mr_data_cmpdisk_bigint(), or_get_bigint(), or_mvcc_get_delid(), and or_mvcc_get_insid().
#define OR_GET_BOUND_BIT (bitptr, element) ((*OR_GET_BOUND_BIT_BYTE ((bitptr), (element))) & OR_BOUND_BIT_MASK ((element)))
Definition at line 603 of file object_representation.h.
Referenced by catcls_get_or_value_from_buffer(), get_desc_current(), get_desc_old(), get_old(), la_get_current(), and or_mvcc_set_repid_and_flags().
#define OR_GET_BOUND_BIT_BYTE (bitptr, element) ((char *) (bitptr) + ((int) (element) >> 3))
Definition at line 600 of file object_representation.h.
#define OR_GET_BOUND_BIT_FLAG (ptr) ((OR_GET_INT ((ptr) + OR_REP_OFFSET)) & OR_BOUND_BIT_FLAG)
Definition at line 506 of file object_representation.h.
Referenced by heap_delete_home(), heap_delete_relocation(), and or_replace_rep_id().
#define OR_GET_BOUND_BITS (obj, nvars, fsize)
Value:
(char *) (((char *) (obj)) \
            + OR_HEADER_SIZE ((char *) (obj)) \
            + OR_VAR_TABLE_SIZE_INTERNAL ((nvars), OR_GET_OFFSET_SIZE (obj)) + (fsize))
Definition at line 606 of file object_representation.h.
Referenced by heap_attrinfo_transform_to_disk_internal().
#define OR_GET_BTID (ptr, btid)
Value:
do { \
    (btid)->root_pageid = OR_GET_INT (((char *) (ptr)) + OR_BTID_PAGEID); \
    (btid)->vfid.fileid = OR_GET_INT (((char *) (ptr)) + OR_BTID_VFID_FILEID); \
    (btid)->vfid.volid  = OR_GET_SHORT (((char *) (ptr)) + OR_BTID_VFID_VOLID); \
  } while (0)
Definition at line 364 of file object_representation.h.
Referenced by btree_rv_redo_global_unique_stats_commit(), btree_rv_undo_global_unique_stats_commit(), btree_rv_update_tran_stats(), or_unpack_btid(), and stats_client_unpack_statistics().
#define OR_GET_BYTE (ptr) (*(unsigned char *) ((char *) (ptr)))
Definition at line 90 of file object_representation.h.
Referenced by bf2df_str_cmpdisk(), catalog_drop_representation_item(), catalog_insert_representation_item(), catalog_put_representation_item(), compare_driver(), log_rv_record_modify_internal(), mr_data_cmpdisk_string(), mr_data_cmpdisk_varnchar(), mr_index_lengthmem_string(), or_get_byte(), or_get_string_size_byte(), cubpacking::unpacker::unpack_small_string(), cubpacking::unpacker::unpack_string(), and cubpacking::unpacker::unpack_string_size().
#define OR_GET_CURRENCY_TYPE (ptr) (DB_CURRENCY) OR_GET_INT (((char *) (ptr)) + OR_MONETARY_TYPE)
Definition at line 273 of file object_representation.h.
#define OR_GET_DATE (ptr, value) *((DB_DATE *) (value)) = OR_GET_INT (ptr)
Definition at line 233 of file object_representation.h.
Referenced by mr_data_cmpdisk_date(), or_get_date(), and or_unpack_double().
#define OR_GET_DATETIME (ptr, datetime)
Value:
do { \
    (datetime)->date = OR_GET_INT (((char *) (ptr)) + OR_DATETIME_DATE); \
    (datetime)->time = OR_GET_INT (((char *) (ptr)) + OR_DATETIME_TIME); \
  } while (0)
Definition at line 239 of file object_representation.h.
Referenced by mr_data_cmpdisk_datetime(), and or_get_datetime().
#define OR_GET_DATETIMETZ (ptr, datetimetz)
Value:
do { \
    OR_GET_DATETIME ((char *) ptr, \
             &((DB_DATETIMETZ *) datetimetz)->datetime); \
    (datetimetz)->tz_id = OR_GET_INT (((char *) (ptr)) + OR_DATETIMETZ_TZID); \
  } while (0)
Definition at line 251 of file object_representation.h.
Referenced by or_get_datetimetz().
#define OR_GET_DOUBLE (ptr, value) (*(value) = ntohd (*(UINT64 *) (ptr)))
Definition at line 98 of file object_representation.h.
Referenced by jsp_unpack_double_value(), jsp_unpack_monetary_value(), mr_data_cmpdisk_double(), or_get_double(), and or_unpack_double().
#define OR_GET_EHID (ptr, ehid)
Value:
do { \
    (ehid)->vfid.volid = OR_GET_INT (((char *) (ptr)) + OR_EHID_VOLID); \
    (ehid)->vfid.fileid = OR_GET_INT (((char *) (ptr)) + OR_EHID_FILEID); \
    (ehid)->pageid = OR_GET_INT (((char *) (ptr)) + OR_EHID_PAGEID); \
  } while (0)
Definition at line 385 of file object_representation.h.
Referenced by or_unpack_ehid().
#define OR_GET_FLOAT (ptr, value) (*(value) = ntohf (*(UINT32 *) (ptr)))
Definition at line 96 of file object_representation.h.
Referenced by mr_data_cmpdisk_float(), or_get_float(), and or_unpack_float().
#define OR_GET_HFID (ptr, hfid)
Value:
do { \
    (hfid)->hpgid = OR_GET_INT (((char *) (ptr)) + OR_HFID_PAGEID); \
    (hfid)->vfid.fileid = OR_GET_INT (((char *) (ptr)) + OR_HFID_VFID_FILEID); \
    (hfid)->vfid.volid = OR_GET_INT (((char *) (ptr)) + OR_HFID_VFID_VOLID); \
  } while (0)
Definition at line 343 of file object_representation.h.
Referenced by catalog_get_class_info_from_record(), heap_rv_dump_append_pages_to_heap(), heap_rv_postpone_append_pages_to_heap(), or_unpack_hfid(), and or_unpack_hfid_array().
#define OR_GET_INT (ptr) ((int) ntohl (*(int *) ((char *) (ptr))))
Definition at line 94 of file object_representation.h.
Referenced by btree_read_fixed_portion_of_non_leaf_record(), btree_rv_record_modify_internal(), btree_rv_redo_global_unique_stats_commit(), btree_rv_roothdr_dump(), btree_rv_roothdr_undo_update(), btree_rv_undo_global_unique_stats_commit(), btree_rv_update_tran_stats(), catalog_get_btree_statistics(), catalog_get_class_info_from_record(), catalog_get_disk_attribute(), catalog_get_disk_representation(), catalog_get_repr_item_from_record(), er_set_area_error(), heap_rv_dump_append_pages_to_heap(), heap_rv_mvcc_redo_insert(), heap_rv_mvcc_redo_redistribute(), heap_rv_postpone_append_pages_to_heap(), mr_cmpdisk_bit_internal(), mr_cmpdisk_char_internal(), mr_cmpdisk_nchar_internal(), mr_data_cmpdisk_int(), mr_data_cmpdisk_resultset(), or_class_get_partition_info(), or_class_hfid(), or_class_tde_algorithm(), or_disk_set_size(), or_find_diskattr(), or_get_all_representation(), or_get_att_index(), or_get_current_representation(), or_get_domain_internal(), or_get_int(), or_get_old_representation(), or_get_set(), or_get_unique_hierarchy(), or_get_varbit_length(), or_get_varchar_compression_lengths(), or_mvcc_get_chn(), or_mvcc_get_repid_and_flags(), or_mvcc_set_flag(), or_unpack_bool_array(), or_unpack_errcode(), or_unpack_int(), or_unpack_listid(), or_unpack_lock(), or_unpack_short(), or_unpack_stream(), or_unpack_string(), or_unpack_string_alloc(), or_unpack_string_nocopy(), cubpacking::unpacker::peek_unpack_int(), qexec_analytic_group_header_load(), qexec_analytic_sort_key_header_load(), stats_client_unpack_statistics(), stx_restore_string(), cubpacking::unpacker::unpack_buffer_with_length(), cubpacking::unpacker::unpack_int(), cubpacking::unpacker::unpack_int_array(), cubpacking::unpacker::unpack_int_vector(), cubpacking::unpacker::unpack_large_string(), and cubpacking::unpacker::unpack_string_size().
#define OR_GET_INT64 (ptr, val)
Value:
do { \
    INT64 packed_value; \
    memcpy (&packed_value, ptr, OR_INT64_SIZE); \
    *((INT64*) (val)) = ((INT64) swap64 (packed_value)); \
  } while (0)
Definition at line 195 of file object_representation.h.
Referenced by or_unpack_int64(), perfmon_unpack_stats(), and cubpacking::unpacker::unpack_bigint().
#define OR_GET_LOG_LSA (ptr, lsa)
Value:
do { \
    INT64 value; \
    OR_GET_INT64 (((char *) (ptr)) + OR_LOG_LSA_PAGEID, &value); \
    (lsa)->pageid = value; \
    (lsa)->offset = OR_GET_SHORT (((char *) (ptr)) + OR_LOG_LSA_OFFSET); \
  } while (0)
Definition at line 399 of file object_representation.h.
Referenced by or_unpack_log_lsa().
#define OR_GET_MONETARY (ptr, value)
Value:
do { \
    UINT64 pack_value; \
    (value)->type = (DB_CURRENCY) OR_GET_INT (((char *) (ptr)) + OR_MONETARY_TYPE); \
    memcpy ((char *) (&pack_value), ((char *) (ptr)) + OR_MONETARY_AMOUNT, OR_DOUBLE_SIZE); \
    OR_GET_DOUBLE (&pack_value, &(value)->amount); \
  } while (0)
Definition at line 265 of file object_representation.h.
Referenced by mr_data_cmpdisk_money(), or_get_monetary(), and or_unpack_double().
#define OR_GET_MVCC_CHN (ptr) (OR_GET_INT ((char *) (ptr) + OR_CHN_OFFSET))
Definition at line 537 of file object_representation.h.
Referenced by heap_get_record_info(), and or_chn().
#define OR_GET_MVCC_DELETE_ID (ptr, mvcc_flags, valp)
Value:
((((mvcc_flags) & OR_MVCC_FLAG_VALID_DELID) == 0) \
    ? MVCCID_NULL \
    : (OR_GET_BIGINT (((char *) (ptr)) + OR_MVCC_DELETE_ID_OFFSET(mvcc_flags), (valp))))
Definition at line 528 of file object_representation.h.
#define OR_GET_MVCC_FLAG (ptr)
Value:
(((OR_GET_INT (((char *) (ptr)) + OR_REP_OFFSET)) \
    >> OR_MVCC_FLAG_SHIFT_BITS) & OR_MVCC_FLAG_MASK)
Definition at line 539 of file object_representation.h.
Referenced by heap_mvcc_log_insert(), or_header_size(), and or_mvcc_get_flag().
#define OR_GET_MVCC_INSERT_ID (ptr, mvcc_flags, valp)
Value:
((((mvcc_flags) & OR_MVCC_FLAG_VALID_INSID) == 0) \
    ? MVCCID_ALL_VISIBLE \
    : (OR_GET_BIGINT (((char *) (ptr)) + OR_MVCC_INSERT_ID_OFFSET, (valp))))
Definition at line 523 of file object_representation.h.
#define OR_GET_MVCC_REPID (ptr)
Value:
((OR_GET_INT(((char *) (ptr)) + OR_REP_OFFSET)) \
   & OR_MVCC_REPID_MASK)
Definition at line 533 of file object_representation.h.
Referenced by or_rep_id().
#define OR_GET_MVCC_REPID_AND_FLAG (ptr) (OR_GET_INT (((char *) (ptr)) + OR_REP_OFFSET))
Definition at line 543 of file object_representation.h.
Referenced by heap_delete_home(), heap_delete_relocation(), heap_insert_adjust_recdes_header(), heap_update_adjust_recdes_header(), la_make_room_for_mvcc_insid(), or_mvcc_set_header(), or_replace_rep_id(), or_set_rep_id(), and vacuum_heap_record_insid_and_prev_version().
#define OR_GET_MVCCID OR_GET_BIGINT
Definition at line 489 of file object_representation.h.
Referenced by btree_dump_leaf_record(), btree_leaf_record_handle_first_overflow(), btree_rv_read_keybuf_nocopy(), heap_rv_mvcc_redo_delete_newhome(), heap_rv_mvcc_redo_delete_overflow(), heap_rv_mvcc_redo_redistribute(), or_get_mvccid(), and or_unpack_mvccid().
#define OR_GET_OBJECT_VAR_TABLE (obj) ((short *) (((char *) (obj)) + OR_HEADER_SIZE ((char *) (obj))))
Definition at line 548 of file object_representation.h.
#define OR_GET_OFFSET (ptr) OR_GET_OFFSET_INTERNAL (ptr, BIG_VAR_OFFSET_SIZE)
Definition at line 147 of file object_representation.h.
Referenced by or_disk_set_size(), and or_get_set().
#define OR_GET_OFFSET_INTERNAL (ptr, offset_size)
Value:
(offset_size == OR_BYTE_SIZE) \
   ? OR_GET_BYTE (ptr) \
   : ((offset_size == OR_SHORT_SIZE) \
      ? OR_GET_SHORT (ptr) : OR_GET_INT (ptr))
Definition at line 150 of file object_representation.h.
Referenced by or_unpack_var_table_internal().
#define OR_GET_OFFSET_SIZE (ptr)
Value:
((((OR_GET_INT (((char *) (ptr)) + OR_REP_OFFSET)) & OR_OFFSET_SIZE_FLAG) == OR_OFFSET_SIZE_1BYTE) \
     ? OR_BYTE_SIZE \
     : ((((OR_GET_INT (((char *) (ptr)) + OR_REP_OFFSET)) & OR_OFFSET_SIZE_FLAG) == OR_OFFSET_SIZE_2BYTE) \
          ? OR_SHORT_SIZE : OR_INT_SIZE))
Definition at line 509 of file object_representation.h.
Referenced by catcls_get_or_value_from_buffer(), catcls_get_or_value_from_class_record(), desc_disk_to_obj(), heap_delete_home(), heap_delete_relocation(), la_disk_to_obj(), or_class_hfid(), or_class_rep_dir(), or_class_tde_algorithm(), or_find_diskattr(), or_get_all_representation(), or_get_classrep(), or_get_classrep_noindex(), or_get_current_representation(), or_get_old_representation(), or_get_unique_hierarchy(), or_mvcc_set_header(), or_replace_rep_id(), tf_disk_to_class(), and tf_disk_to_mem().
#define OR_GET_OID (ptr, oid)
Value:
do { \
    (oid)->pageid = OR_GET_INT (((char *) (ptr)) + OR_OID_PAGEID); \
    (oid)->slotid = OR_GET_SHORT (((char *) (ptr)) + OR_OID_SLOTID); \
    (oid)->volid  = OR_GET_SHORT (((char *) (ptr)) + OR_OID_VOLID); \
  } while (0)
Definition at line 304 of file object_representation.h.
Referenced by btree_rv_read_keybuf_nocopy(), btree_rv_record_modify_internal(), catalog_get_class_info_from_record(), catalog_get_disk_attribute(), compare_driver(), cursor_fetch_oids(), heap_rv_dump_append_pages_to_heap(), heap_rv_postpone_append_pages_to_heap(), mr_data_cmpdisk_object(), mr_data_cmpdisk_oid(), or_class_rep_dir(), or_class_tde_algorithm(), or_get_current_representation(), or_get_domain_internal(), or_get_hierarchy_helper(), or_get_oid(), or_get_unique_hierarchy(), or_unpack_oid(), or_unpack_oid_array(), orc_subclasses_from_record(), orc_superclasses_from_record(), and cubpacking::unpacker::unpack_oid().
#define OR_GET_PTR (ptr) ((UINTPTR) swap64 (*(UINTPTR *) ((char *) (ptr))))
Definition at line 185 of file object_representation.h.
Referenced by or_unpack_listid(), and or_unpack_ptr().
#define OR_GET_REPID (ptr) ((OR_GET_INT ((ptr) + OR_REP_OFFSET)) & ~OR_BOUND_BIT_FLAG & ~OR_OFFSET_SIZE_FLAG)
Definition at line 503 of file object_representation.h.
#define OR_GET_SET_BOUND_BITS (setptr) (int *) ((char *) (setptr) + OR_SET_HEADER_SIZE)
Definition at line 685 of file object_representation.h.
#define OR_GET_SET_VAR_TABLE (setptr) ((int *) ((char *) (setptr) + OR_SET_HEADER_SIZE))
Definition at line 671 of file object_representation.h.
#define OR_GET_SHA1 (ptr, value)
Value:
do { \
    int i = 0; \
    for (; i < 5; i++) \
      { \
    ((SHA1Hash *) (value))->h[i] = (INT32) OR_GET_INT (ptr + i * OR_INT_SIZE); \
      } \
  } while (0)
Definition at line 285 of file object_representation.h.
Referenced by or_unpack_sha1().
#define OR_GET_SHORT (ptr) ((short) ntohs (*(short *) ((char *) (ptr))))
Definition at line 92 of file object_representation.h.
Referenced by btree_leaf_clear_flag(), btree_leaf_get_flag(), btree_leaf_is_flaged(), btree_leaf_set_flag(), btree_read_fixed_portion_of_non_leaf_record(), btree_record_object_clear_mvcc_flags(), btree_record_object_get_mvcc_flags(), btree_record_object_is_flagged(), btree_record_object_set_mvcc_flags(), catalog_get_repr_item_from_record(), mr_data_cmpdisk_enumeration(), mr_data_cmpdisk_short(), or_get_short(), and cubpacking::unpacker::unpack_short().
#define OR_GET_STRING (ptr) ((char *) ((char *) (ptr)))
Definition at line 100 of file object_representation.h.
#define OR_GET_TIME (ptr, value) *((DB_TIME *) (value)) = OR_GET_INT (ptr)
Definition at line 209 of file object_representation.h.
Referenced by mr_data_cmpdisk_time(), or_get_time(), and or_unpack_double().
#define OR_GET_TIMESTAMPTZ (ptr, ts_tz)
Value:
do { \
    (ts_tz)->timestamp = OR_GET_INT ((char *) (ptr)); \
    (ts_tz)->tz_id = OR_GET_INT (((char *) (ptr)) + OR_TIMESTAMPTZ_TZID); \
  } while (0)
Definition at line 221 of file object_representation.h.
Referenced by or_get_timestamptz().
#define OR_GET_UTIME (ptr, value) *((DB_UTIME *) (value)) = OR_GET_INT (ptr)
Definition at line 215 of file object_representation.h.
Referenced by mr_data_cmpdisk_timestamptz(), mr_data_cmpdisk_utime(), or_get_utime(), and or_unpack_double().
#define OR_GET_VARIABLE_TYPE (ptr) (OR_GET_INT ((int *) (ptr)))
Definition at line 737 of file object_representation.h.
#define OR_GET_VPID (ptr, vpid)
Value:
do { \
    (vpid)->pageid = OR_GET_INT (((char *) (ptr)) + OR_VPID_PAGEID); \
    (vpid)->volid = OR_GET_SHORT (((char *) (ptr)) + OR_VPID_VOLID); \
  } while (0)
Definition at line 318 of file object_representation.h.
Referenced by btree_check_valid_record(), btree_record_append_object(), btree_rv_record_modify_internal(), heap_rv_dump_append_pages_to_heap(), and heap_rv_postpone_append_pages_to_heap().
#define OR_HEADER_SIZE (ptr) (or_header_size ((char *) (ptr)))
Definition at line 460 of file object_representation.h.
Referenced by heap_mvcc_log_insert(), heap_mvcc_log_redistribute(), heap_set_mvcc_rec_header_on_overflow(), heap_update_set_prev_version(), or_mvcc_get_flag(), or_rep_id(), and or_set_rep_id().
#define OR_INFINITE_POINTER ((void *) (~((UINTPTR) 0UL)))
Definition at line 1056 of file object_representation.h.
Referenced by or_init().
#define OR_INT64_SIZE 8
Definition at line 188 of file object_representation.h.
Referenced by es_posix_get_file_size(), es_posix_read_file(), es_posix_write_file(), logwr_get_log_pages(), net_client_logwr_send_end_msg(), or_pack_int64(), or_unpack_int64(), perfmon_pack_stats(), perfmon_server_copy_global_stats(), perfmon_server_copy_stats(), perfmon_unpack_stats(), ses_posix_get_file_size(), ses_posix_read_file(), ses_posix_write_file(), and sysprm_packed_sysprm_value_length().
#define OR_IS_STRING_LENGTH_COMPRESSABLE (str_length) ((str_length) >= OR_MINIMUM_STRING_LENGTH_FOR_COMPRESSION && (str_length) <= LZ4_MAX_INPUT_SIZE)
Definition at line 1412 of file object_representation.h.
Referenced by or_put_varchar_internal(), pr_data_compress_string(), and pr_do_db_value_string_compression().
#define OR_MINIMUM_STRING_LENGTH_FOR_COMPRESSION 255
Definition at line 1410 of file object_representation.h.
Referenced by bf2df_str_cmpdisk(), mr_data_cmpdisk_string(), mr_data_cmpdisk_varnchar(), mr_data_lengthmem_string(), mr_data_lengthmem_varnchar(), mr_index_lengthmem_string(), mr_lengthval_string_internal(), mr_lengthval_varnchar_internal(), mr_writeval_string_internal(), mr_writeval_varnchar_internal(), or_get_varchar_compression_lengths(), or_put_varchar_internal(), or_varchar_length_internal(), pr_get_compression_length(), pr_get_size_and_write_string_to_buffer(), pr_write_compressed_string_to_buffer(), and pr_write_uncompressed_string_to_buffer().
#define OR_MOVE_MONETARY (src, dst)
Value:
do { \
    OR_MOVE_DOUBLE (src, dst); \
    ((DB_MONETARY *) dst)->type = ((DB_MONETARY *) src)->type; \
  } while (0)
Definition at line 156 of file object_representation.h.
#define OR_MULTI_ATT_IS_BOUND (bitptr, element) OR_MULTI_GET_BOUND_BIT(bitptr, element)
Definition at line 703 of file object_representation.h.
Referenced by pr_midxkey_add_prefix(), and pr_midxkey_compare().
#define OR_MULTI_ATT_IS_UNBOUND (bitptr, element) (!OR_MULTI_GET_BOUND_BIT (bitptr, element))
Definition at line 705 of file object_representation.h.
Referenced by btree_multicol_key_has_null(), compare_driver(), mr_index_lengthmem_midxkey(), pr_midxkey_get_element_internal(), pr_midxkey_get_element_offset(), and pr_midxkey_unique_prefix().
#define OR_MULTI_BOUND_BIT_BYTES (count) (((count) + 7) >> 3)
Definition at line 690 of file object_representation.h.
Referenced by btree_multicol_key_is_null(), compare_driver(), do_create_midxkey_for_constraint(), mr_index_lengthmem_midxkey(), pr_midxkey_add_elements(), pr_midxkey_compare(), pr_midxkey_get_element_internal(), pr_midxkey_get_element_offset(), pr_midxkey_init_boundbits(), and scan_dbvals_to_midxkey().
#define OR_MULTI_BOUND_BIT_MASK (element) (1 << ((int) (element) & 7))
Definition at line 692 of file object_representation.h.
#define OR_MULTI_CLEAR_BOUND_BIT (bitptr, element)
Value:
*OR_MULTI_GET_BOUND_BIT_BYTE (bitptr, element) = (*OR_MULTI_GET_BOUND_BIT_BYTE (bitptr, element) \
                            & ~OR_MULTI_BOUND_BIT_MASK (element))
Definition at line 712 of file object_representation.h.
Referenced by pr_midxkey_add_prefix(), pr_midxkey_remove_prefix(), and pr_midxkey_unique_prefix().
#define OR_MULTI_ENABLE_BOUND_BIT (bitptr, element)
Value:
*OR_MULTI_GET_BOUND_BIT_BYTE (bitptr, element) = (*OR_MULTI_GET_BOUND_BIT_BYTE (bitptr, element) \
                            | OR_MULTI_BOUND_BIT_MASK (element))
Definition at line 708 of file object_representation.h.
Referenced by pr_midxkey_add_prefix().
#define OR_MULTI_GET_BOUND_BIT (bitptr, element) ((*OR_MULTI_GET_BOUND_BIT_BYTE(bitptr, element)) & OR_MULTI_BOUND_BIT_MASK(element))
Definition at line 697 of file object_representation.h.
#define OR_MULTI_GET_BOUND_BIT_BYTE (bitptr, element) ((char *)(bitptr) + ((int)(element) >> 3))
Definition at line 694 of file object_representation.h.
#define OR_MULTI_GET_BOUND_BITS (bitptr, fsize) (char *) (((char *) (bitptr)) + fsize)
Definition at line 700 of file object_representation.h.
#define OR_MVCC_DELETE_ID_OFFSET (mvcc_flags) (OR_MVCC_INSERT_ID_OFFSET + (((mvcc_flags) & OR_MVCC_FLAG_VALID_INSID) ? OR_MVCC_INSERT_ID_SIZE : 0))
Definition at line 478 of file object_representation.h.
Referenced by heap_delete_home(), and heap_delete_relocation().
#define OR_MVCC_DELETE_ID_SIZE 8
Definition at line 480 of file object_representation.h.
Referenced by heap_delete_home().
#define OR_MVCC_FLAG_OFFSET OR_REP_OFFSET
Definition at line 469 of file object_representation.h.
#define OR_MVCC_FLAG_SIZE OR_MVCC_REP_SIZE
Definition at line 470 of file object_representation.h.
#define OR_MVCC_INSERT_ID_OFFSET (OR_CHN_OFFSET + OR_CHN_SIZE)
Definition at line 475 of file object_representation.h.
Referenced by heap_insert_adjust_recdes_header(), heap_update_adjust_recdes_header(), and vacuum_heap_record_insid_and_prev_version().
#define OR_MVCC_INSERT_ID_SIZE 8
Definition at line 476 of file object_representation.h.
#define OR_MVCC_PREV_VERSION_LSA_OFFSET (mvcc_flags) (OR_MVCC_DELETE_ID_OFFSET(mvcc_flags) + (((mvcc_flags) & OR_MVCC_FLAG_VALID_DELID) ? OR_MVCC_DELETE_ID_SIZE : 0))
Definition at line 482 of file object_representation.h.
Referenced by heap_delete_home(), and heap_delete_relocation().
#define OR_MVCC_PREV_VERSION_LSA_SIZE 8
Definition at line 484 of file object_representation.h.
Referenced by catcls_get_or_value_from_buffer(), desc_disk_to_obj(), heap_attrinfo_transform_to_disk_internal(), heap_update_adjust_recdes_header(), or_mvcc_get_prev_version_lsa(), or_mvcc_set_log_lsa_to_record(), or_mvcc_set_prev_version_lsa(), and tf_disk_to_mem().
#define OR_MVCC_REP_SIZE 4
Definition at line 467 of file object_representation.h.
Referenced by or_mvcc_get_header(), or_mvcc_set_flag(), and or_mvcc_set_log_lsa_to_record().
#define OR_MVCCID_SIZE OR_BIGINT_SIZE
Definition at line 487 of file object_representation.h.
Referenced by btree_add_mvccid(), btree_construct_leafs(), btree_delete_overflow_key(), btree_dump_leaf_record(), btree_get_max_new_data_size(), btree_leaf_change_first_object(), btree_leaf_record_handle_first_overflow(), btree_packed_mvccinfo_size(), btree_read_record_without_decompression(), btree_record_add_delid(), btree_record_remove_delid(), btree_record_remove_insid(), btree_remove_mvccid(), btree_rv_read_keybuf_nocopy(), btree_rv_save_keyval_for_undo(), btree_set_mvccid(), btree_sort_get_next(), catcls_get_or_value_from_buffer(), compare_driver(), desc_disk_to_obj(), heap_delete_home(), heap_delete_relocation(), heap_insert_adjust_recdes_header(), heap_mvcc_log_delete(), heap_mvcc_log_redistribute(), heap_rv_mvcc_redo_delete_newhome(), heap_rv_mvcc_redo_delete_overflow(), heap_rv_mvcc_redo_redistribute(), heap_update_adjust_recdes_header(), la_disk_to_obj(), la_make_room_for_mvcc_insid(), or_get_mvccid(), or_mvcc_get_delid(), or_mvcc_get_insid(), or_mvcc_set_log_lsa_to_record(), or_pack_mvccid(), or_put_mvccid(), or_unpack_mvccid(), tf_disk_to_mem(), and vacuum_heap_record_insid_and_prev_version().
#define OR_PACK_DOMAIN_OBJECT_TO_OID (p, d, o, n)
Value:
or_pack_domain ((p), \
                  TP_DOMAIN_TYPE (d) == DB_TYPE_OBJECT ? &tp_Oid_domain : (d), \
                  (o), (n))
Definition at line 1090 of file object_representation.h.
Referenced by xts_process_aggregate_type(), xts_process_analytic_type(), xts_process_arith_type(), xts_process_pos_descr(), and xts_process_regu_variable().
#define OR_PTR_SIZE 8
Definition at line 183 of file object_representation.h.
Referenced by or_listid_length(), or_pack_listid(), or_pack_ptr(), or_unpack_listid(), or_unpack_ptr(), qfile_get_list_file_page(), qmgr_end_query(), qmgr_execute_query(), and tran_server_commit().
#define OR_PUT_BIG_VAR_OFFSET (ptr, val) OR_PUT_INT (ptr, val) /* 4byte */
Definition at line 126 of file object_representation.h.
#define OR_PUT_BIGINT (ptr, val) OR_PUT_INT64 (ptr, val)
Definition at line 192 of file object_representation.h.
Referenced by heap_delete_home(), heap_delete_relocation(), heap_insert_adjust_recdes_header(), heap_update_adjust_recdes_header(), jsp_pack_bigint_argument(), and or_put_bigint().
#define OR_PUT_BTID (ptr, btid)
Value:
do { \
    OR_PUT_INT (((char *) (ptr)) + OR_BTID_PAGEID, (btid)->root_pageid); \
    OR_PUT_INT (((char *) (ptr)) + OR_BTID_VFID_FILEID, (btid)->vfid.fileid); \
    OR_PUT_SHORT (((char *) (ptr)) + OR_BTID_VFID_VOLID, (btid)->vfid.volid); \
  } while (0)
Definition at line 371 of file object_representation.h.
Referenced by btree_rv_mvcc_save_increments(), catalog_put_btree_statistics(), logtb_update_global_unique_stats_by_delta(), or_pack_btid(), and xstats_get_statistics_from_server().
#define OR_PUT_BYTE (ptr, val) (*((unsigned char *) (ptr)) = (unsigned char) (val))
Definition at line 103 of file object_representation.h.
Referenced by catalog_drop_old_representations(), catalog_drop_representation_item(), catalog_put_representation_item(), log_rv_pack_redo_record_changes(), log_rv_pack_undo_record_changes(), or_put_byte(), cubpacking::packer::pack_c_string(), and cubpacking::packer::pack_small_string().
#define OR_PUT_DATE (ptr, value) OR_PUT_INT (ptr, *((DB_DATE *) (value)))
Definition at line 236 of file object_representation.h.
Referenced by or_put_date(), and or_unpack_double().
#define OR_PUT_DATETIME (ptr, datetime)
Value:
do { \
    OR_PUT_INT (((char *)ptr) + OR_DATETIME_DATE, (datetime)->date); \
    OR_PUT_INT (((char *)ptr) + OR_DATETIME_TIME, (datetime)->time); \
  } while (0)
Definition at line 245 of file object_representation.h.
Referenced by or_put_datetime().
#define OR_PUT_DATETIMETZ (ptr, datetimetz)
Value:
do { \
    OR_PUT_DATETIME (((char *) ptr), \
             &((DB_DATETIMETZ *) datetimetz)->datetime); \
    OR_PUT_INT (((char *) ptr) + OR_DATETIMETZ_TZID, (datetimetz)->tz_id); \
  } while (0)
Definition at line 258 of file object_representation.h.
Referenced by or_put_datetimetz().
#define OR_PUT_EHID (ptr, ehid)
Value:
do { \
    OR_PUT_INT (((char *) (ptr)) + OR_EHID_VOLID,  (ehid)->vfid.volid); \
    OR_PUT_INT (((char *) (ptr)) + OR_EHID_FILEID, (ehid)->vfid.fileid); \
    OR_PUT_INT (((char *) (ptr)) + OR_EHID_PAGEID, (ehid)->pageid); \
  } while (0)
Definition at line 392 of file object_representation.h.
Referenced by or_pack_ehid().
#define OR_PUT_HFID (ptr, hfid)
Value:
do { \
    OR_PUT_INT (((char *) (ptr)) + OR_HFID_PAGEID, (hfid)->hpgid); \
    OR_PUT_INT (((char *) (ptr)) + OR_HFID_VFID_FILEID, (hfid)->vfid.fileid); \
    OR_PUT_INT (((char *) (ptr)) + OR_HFID_VFID_VOLID, (hfid)->vfid.volid); \
  } while (0)
Definition at line 350 of file object_representation.h.
Referenced by catalog_put_class_info_to_record(), heap_log_postpone_heap_append_pages(), and or_pack_hfid().
#define OR_PUT_INT (ptr, val) (*(int *) ((char *) (ptr)) = htonl ((int) (val)))
Definition at line 107 of file object_representation.h.
Referenced by btree_rv_mvcc_save_increments(), btree_rv_save_root_head(), btree_write_fixed_portion_of_non_leaf_record(), catalog_put_btree_statistics(), catalog_put_class_info_to_record(), catalog_put_disk_attribute(), catalog_put_disk_representation(), catalog_put_repr_item_to_record(), er_get_area_error(), heap_delete_home(), heap_delete_relocation(), heap_insert_adjust_recdes_header(), heap_log_postpone_heap_append_pages(), heap_update_adjust_recdes_header(), logtb_update_global_unique_stats_by_delta(), or_pack_bool_array(), or_pack_errcode(), or_pack_int(), or_pack_listid(), or_pack_lock(), or_pack_short(), or_pack_stream(), or_pack_string(), or_pack_string_with_length(), or_put_int(), or_put_set(), or_put_varbit_internal(), or_put_varchar_internal(), cubpacking::packer::pack_buffer_with_length(), cubpacking::packer::pack_int(), cubpacking::packer::pack_int_array(), cubpacking::packer::pack_int_vector(), cubpacking::packer::pack_large_c_string(), pr_write_compressed_string_to_buffer(), qfile_fast_intint_tuple_to_list(), qfile_fast_intval_tuple_to_list(), qfile_initialize_page_header(), qmgr_put_page_header(), sysprm_pack_assign_values(), vacuum_heap_record_insid_and_prev_version(), and xstats_get_statistics_from_server().
#define OR_PUT_INT64 (ptr, val)
Value:
do { \
    INT64 packed_value; \
    packed_value = ((INT64) swap64 (*(INT64*) val)); \
    memcpy (ptr, &packed_value, OR_INT64_SIZE);\
  } while (0)
Definition at line 202 of file object_representation.h.
Referenced by or_pack_int64(), cubpacking::packer::pack_bigint(), and perfmon_pack_stats().
#define OR_PUT_LOG_LSA (ptr, lsa)
Value:
do { \
    INT64 pageid = (lsa)->pageid; \
    OR_PUT_INT64 (((char *) (ptr)) + OR_LOG_LSA_PAGEID, &pageid); \
    OR_PUT_SHORT (((char *) (ptr)) + OR_LOG_LSA_OFFSET, (lsa)->offset); \
  } while (0)
Definition at line 407 of file object_representation.h.
Referenced by or_pack_log_lsa().
#define OR_PUT_MONETARY (ptr, value)
Value:
do { \
    char pack_value[OR_DOUBLE_SIZE]; \
    OR_PUT_INT (((char *) (ptr)) + OR_MONETARY_TYPE, (int) (value)->type); \
    OR_PUT_DOUBLE (pack_value, (value)->amount); \
    memcpy (((char *) (ptr)) + OR_MONETARY_AMOUNT, pack_value, OR_DOUBLE_SIZE); \
  } while (0)
Definition at line 276 of file object_representation.h.
Referenced by or_put_monetary(), and or_unpack_double().
#define OR_PUT_MVCCID OR_PUT_BIGINT
Definition at line 488 of file object_representation.h.
Referenced by btree_add_mvccid(), btree_leaf_record_handle_first_overflow(), btree_rv_save_keyval_for_undo(), btree_set_mvccid(), or_pack_mvccid(), and or_put_mvccid().
#define OR_PUT_NULL_BTID (ptr)
Value:
do { \
    OR_PUT_INT (((char *) (ptr)) + OR_BTID_PAGEID, NULL_PAGEID); \
    OR_PUT_INT (((char *) (ptr)) + OR_BTID_VFID_FILEID, NULL_FILEID); \
    OR_PUT_SHORT (((char *) (ptr)) + OR_BTID_VFID_VOLID, NULL_VOLID); \
  } while (0)
Definition at line 378 of file object_representation.h.
Referenced by or_pack_btid().
#define OR_PUT_NULL_HFID (ptr)
Value:
do { \
    OR_PUT_INT (((char *) (ptr)) + OR_HFID_PAGEID, -1); \
    OR_PUT_INT (((char *) (ptr)) + OR_HFID_VFID_FILEID, -1); \
    OR_PUT_INT (((char *) (ptr)) + OR_HFID_VFID_VOLID, -1); \
  } while (0)
Definition at line 357 of file object_representation.h.
Referenced by or_pack_hfid().
#define OR_PUT_NULL_LOG_LSA (ptr)
Value:
do { \
    INT64 pageid = -1; \
    OR_PUT_INT64 (((char *) (ptr)) + OR_LOG_LSA_PAGEID, &pageid); \
    OR_PUT_SHORT (((char *) (ptr)) + OR_LOG_LSA_OFFSET, -1); \
  } while (0)
Definition at line 414 of file object_representation.h.
Referenced by or_pack_log_lsa().
#define OR_PUT_NULL_OID (ptr)
Value:
do { \
    OR_PUT_INT (((char *) (ptr)) + OR_OID_PAGEID, NULL_PAGEID); \
    OR_PUT_SHORT (((char *) (ptr)) + OR_OID_SLOTID, 0); \
    OR_PUT_SHORT (((char *) (ptr)) + OR_OID_VOLID,  0); \
  } while (0)
Definition at line 336 of file object_representation.h.
Referenced by extract_objects(), fh_create(), or_pack_oid(), and or_put_oid().
#define OR_PUT_OFFSET (ptr, val) OR_PUT_OFFSET_INTERNAL(ptr, val, BIG_VAR_OFFSET_SIZE)
Definition at line 128 of file object_representation.h.
Referenced by catcls_put_or_value_into_buffer(), or_put_set(), and put_substructure_set().
#define OR_PUT_OFFSET_INTERNAL (ptr, val, offset_size)
Value:
do { \
    if (offset_size == OR_BYTE_SIZE) \
      { \
        OR_PUT_BYTE(ptr, val); \
      } \
    else if (offset_size == OR_SHORT_SIZE) \
      { \
        OR_PUT_SHORT(ptr, val); \
      } \
    else if (offset_size == OR_INT_SIZE) \
      { \
        OR_PUT_INT(ptr, val); \
      } \
  } while (0)
Definition at line 131 of file object_representation.h.
#define OR_PUT_OID (ptr, oid)
Value:
do { \
    OR_PUT_INT (((char *) (ptr)) + OR_OID_PAGEID, (oid)->pageid); \
    OR_PUT_SHORT (((char *) (ptr)) + OR_OID_SLOTID, (oid)->slotid); \
    OR_PUT_SHORT (((char *) (ptr)) + OR_OID_VOLID, (oid)->volid); \
  } while (0)
Definition at line 311 of file object_representation.h.
Referenced by btree_append_oid(), btree_construct_leafs(), btree_leaf_record_handle_first_overflow(), btree_rv_save_keyval_for_undo(), catalog_put_class_info_to_record(), catalog_put_disk_attribute(), cursor_prefetch_column_oids(), fixup_callback(), heap_log_postpone_heap_append_pages(), locator_insert_force(), locator_update_force(), or_pack_oid(), or_put_oid(), and cubpacking::packer::pack_oid().
#define OR_PUT_PTR (ptr, val) (*(UINTPTR *) ((char *) (ptr)) = swap64 ((UINTPTR) val))
Definition at line 184 of file object_representation.h.
Referenced by or_pack_listid(), and or_pack_ptr().
#define OR_PUT_SHA1 (ptr, value)
Value:
do { \
    int i = 0; \
    for (; i < 5; i++) \
      { \
    OR_PUT_INT (ptr + i * OR_INT_SIZE, ((SHA1Hash *) (value))->h[i]); \
      } \
  } while (0)
Definition at line 293 of file object_representation.h.
Referenced by or_pack_sha1().
#define OR_PUT_SHORT (ptr, val) (*(short *) ((char *) (ptr)) = htons ((short) (val)))
Definition at line 105 of file object_representation.h.
Referenced by btree_leaf_clear_flag(), btree_leaf_set_flag(), btree_record_object_clear_mvcc_flags(), btree_record_object_set_mvcc_flags(), btree_write_fixed_portion_of_non_leaf_record(), catalog_put_repr_item_to_record(), log_rv_pack_redo_record_changes(), log_rv_pack_undo_record_changes(), or_pack_btid(), or_pack_log_lsa(), or_put_short(), cubpacking::packer::pack_short(), qfile_initialize_page_header(), and qmgr_put_page_header().
#define OR_PUT_TIME (ptr, value) OR_PUT_INT (ptr, *((DB_TIME *) (value)))
Definition at line 212 of file object_representation.h.
Referenced by or_put_time(), and or_unpack_double().
#define OR_PUT_TIMESTAMPTZ (ptr, ts_tz)
Value:
do { \
    OR_PUT_INT (((char *) ptr), (ts_tz)->timestamp); \
    OR_PUT_INT (((char *) ptr) + OR_TIMESTAMPTZ_TZID, (ts_tz)->tz_id); \
  } while (0)
Definition at line 227 of file object_representation.h.
Referenced by or_put_timestamptz().
#define OR_PUT_UTIME (ptr, value) OR_PUT_INT (ptr, *((DB_UTIME *) (value)))
Definition at line 218 of file object_representation.h.
Referenced by or_put_utime(), and or_unpack_double().
#define OR_PUT_VPID (ptr, vpid)
Value:
do { \
    OR_PUT_INT (((char *) (ptr)) + OR_VPID_PAGEID, (vpid)->pageid); \
    OR_PUT_SHORT (((char *) (ptr)) + OR_VPID_VOLID, (vpid)->volid); \
  } while (0)
Definition at line 324 of file object_representation.h.
#define OR_PUT_VPID_ALIGNED (ptr, vpid)
Value:
do { \
    OR_PUT_INT (((char *) (ptr)) + OR_VPID_PAGEID, (vpid)->pageid); \
    OR_PUT_SHORT (((char *) (ptr)) + OR_VPID_VOLID, (vpid)->volid); \
    OR_PUT_SHORT (((char *) (ptr)) + OR_VPID_SIZE, 0); \
  } while (0)
Definition at line 329 of file object_representation.h.
Referenced by btree_leaf_record_change_overflow_link(), btree_record_append_object(), btree_start_overflow_page(), and heap_log_postpone_heap_append_pages().
#define OR_REP_OFFSET 0
Definition at line 466 of file object_representation.h.
Referenced by or_mvcc_set_flag(), or_mvcc_set_log_lsa_to_record(), or_replace_rep_id(), and or_set_rep_id().
#define OR_SET_BOUND_BIT 0x10000
Definition at line 637 of file object_representation.h.
Referenced by or_get_set_header(), and or_put_set_header().
#define OR_SET_COMMON_SUB_BIT 0x100000
Definition at line 641 of file object_representation.h.
Referenced by or_get_set_header(), and or_put_set_header().
#define OR_SET_DOMAIN_BIT 0x40000
Definition at line 639 of file object_representation.h.
Referenced by or_get_set_header(), and or_put_set_header().
#define OR_SET_DOMAIN_SIZE (setptr) ((OR_GET_INT ((char *) (setptr) + OR_SET_DOMAIN_SIZE_OFFSET)))
Definition at line 664 of file object_representation.h.
#define OR_SET_DOMAIN_SIZE_OFFSET 8
Definition at line 630 of file object_representation.h.
#define OR_SET_ELEMENT_COUNT (setptr) ((OR_GET_INT ((char *) (setptr) + OR_SET_SIZE_OFFSET)))
Definition at line 661 of file object_representation.h.
Referenced by or_class_tde_algorithm(), or_get_all_representation(), or_get_domain_internal(), or_get_hierarchy_helper(), or_get_old_representation(), orc_subclasses_from_record(), and orc_superclasses_from_record().
#define OR_SET_ELEMENT_OFFSET (setptr, element) (OR_VAR_TABLE_ELEMENT_OFFSET_INTERNAL (OR_GET_SET_VAR_TABLE (setptr), element, BIG_VAR_OFFSET_SIZE))
Definition at line 674 of file object_representation.h.
Referenced by or_class_get_partition_info(), or_find_diskattr(), or_get_all_representation(), or_get_current_representation(), or_get_domain_internal(), or_get_old_representation(), and or_get_unique_hierarchy().
#define OR_SET_ELEMENT_TYPE (setptr) (DB_TYPE) ((OR_GET_INT ((char *) (setptr)) & OR_SET_ETYPE_MASK) >> OR_SET_ETYPE_SHIFT)
Definition at line 646 of file object_representation.h.
#define OR_SET_ETYPE_MASK 0xFF00
Definition at line 635 of file object_representation.h.
#define OR_SET_ETYPE_SHIFT 8
Definition at line 636 of file object_representation.h.
#define OR_SET_HAS_BOUND_BITS (setptr) (OR_GET_INT ((char *) (setptr)) & OR_SET_BOUND_BIT)
Definition at line 649 of file object_representation.h.
#define OR_SET_HAS_DOMAIN (setptr) (OR_GET_INT ((char *) (setptr)) & OR_SET_DOMAIN_BIT)
Definition at line 655 of file object_representation.h.
#define OR_SET_HAS_ELEMENT_TAGS (setptr) (OR_GET_INT ((char *) (setptr)) & OR_SET_TAG_BIT)
Definition at line 658 of file object_representation.h.
#define OR_SET_HAS_OFFSET_TABLE (setptr) (OR_GET_INT ((char *) (setptr)) & OR_SET_VARIABLE_BIT)
Definition at line 652 of file object_representation.h.
#define OR_SET_HEADER_SIZE 8
Definition at line 627 of file object_representation.h.
Referenced by object_set_size(), or_class_tde_algorithm(), or_get_hierarchy_helper(), or_packed_enumeration_size(), or_packed_set_length(), orc_subclasses_from_record(), orc_superclasses_from_record(), and substructure_set_size().
#define OR_SET_SIZE_OFFSET 4
Definition at line 628 of file object_representation.h.
#define OR_SET_TAG_BIT 0x80000
Definition at line 640 of file object_representation.h.
Referenced by or_get_set_header(), and or_put_set_header().
#define OR_SET_TYPE (setptr) (DB_TYPE) ((OR_GET_INT ((char *) (setptr))) & OR_SET_TYPE_MASK)
Definition at line 643 of file object_representation.h.
#define OR_SET_TYPE_MASK 0xFF
Definition at line 634 of file object_representation.h.
Referenced by or_get_set_header().
#define OR_SET_VAR_OFFSET_SIZE (val, offset_size)
Value:
(((offset_size) == OR_BYTE_SIZE) \
   ? ((val) |= OR_OFFSET_SIZE_1BYTE) \
   : (((offset_size) == OR_SHORT_SIZE) \
      ? ((val) |= OR_OFFSET_SIZE_2BYTE) \
      : ((val) |= OR_OFFSET_SIZE_4BYTE)))
Definition at line 515 of file object_representation.h.
Referenced by catcls_put_or_value_into_buffer(), desc_obj_to_disk(), heap_attrinfo_transform_to_disk_internal(), or_mvcc_set_repid_and_flags(), or_replace_rep_id(), tf_class_to_disk(), and tf_mem_to_disk().
#define OR_SET_VARIABLE_BIT 0x20000
Definition at line 638 of file object_representation.h.
Referenced by or_get_set_header(), and or_put_set_header().
#define OR_SUB_DOMAIN_SIZE OR_INT_SIZE
Definition at line 732 of file object_representation.h.
Referenced by put_substructure_set(), and substructure_set_size().
#define OR_SUB_HEADER_SIZE OR_OID_SIZE + OR_INT_SIZE + OR_INT_SIZE
Definition at line 723 of file object_representation.h.
Referenced by or_skip_set_header(), and substructure_set_size().
#define OR_TYPE_SIZE (type) or_Type_sizes[(int)(type)]
Definition at line 1015 of file object_representation.h.
#define OR_VALUE_ALIGNED_SIZE (value) (or_db_value_size (value) + MAX_ALIGNMENT)
Definition at line 53 of file object_representation.h.
Referenced by btree_find_multi_uniques(), btree_find_unique(), csession_drop_session_variables(), csession_get_variable(), csession_set_session_variables(), db_pack_prepare_info(), heap_attrinfo_generate_key(), heap_attrvalue_get_key(), locator_repl_add_error_to_copyarea(), method_clear_scan_buffer(), method_send_value_to_server(), qmgr_execute_query(), qmgr_prepare_and_execute_query(), sqp_get_server_info(), ssession_get_last_insert_id(), xts_get_regu_variable_value_size(), and xts_sizeof_json_table_column_behavior().
#define OR_VAR_ELEMENT_PTR (obj, index) (OR_VAR_TABLE_ELEMENT_PTR (OR_GET_OBJECT_VAR_TABLE (obj), index, OR_GET_OFFSET_SIZE (obj)))
Definition at line 551 of file object_representation.h.
Referenced by heap_attrinfo_transform_to_disk_internal().
#define OR_VAR_IS_NULL (obj, index)
Value:
((OR_VAR_TABLE_ELEMENT_LENGTH_INTERNAL (OR_GET_OBJECT_VAR_TABLE (obj), \
                                          index, OR_GET_OFFSET_SIZE (obj))) ? 0 : 1)
Definition at line 559 of file object_representation.h.
Referenced by heap_attrvalue_read(), heap_midxkey_get_value(), or_class_get_partition_info(), or_class_tde_algorithm(), or_get_all_representation(), or_get_constraint_comment(), or_get_current_representation(), or_get_hierarchy_helper(), or_get_old_representation(), orc_subclasses_from_record(), and orc_superclasses_from_record().
#define OR_VAR_LENGTH (length, obj, index, n_variables)
Value:
do { \
    int _this_offset, _next_offset, _temp_offset, _nth_var; \
    _this_offset = OR_VAR_OFFSET(obj, index); \
    _next_offset = OR_VAR_OFFSET(obj, index + 1); \
    if ((length = _next_offset - _this_offset) != 0) \
      { \
        _next_offset = 0; \
        for (_nth_var = 0; _nth_var <= n_variables; _nth_var++) \
          { \
            _temp_offset = OR_VAR_OFFSET(obj, _nth_var); \
            if (_temp_offset > _this_offset ) \
              { \
                if (_next_offset == 0) \
                  { \
                    _next_offset = _temp_offset; \
                  } \
                else if (_temp_offset < _next_offset) \
                  { \
                    _next_offset = _temp_offset; \
          } \
              } \
          } \
        length = _next_offset - _this_offset; \
      } \
  } while (0)
Definition at line 563 of file object_representation.h.
Referenced by heap_attrvalue_read().
#define OR_VAR_OFFSET (obj, index)
Value:
(OR_HEADER_SIZE (obj)   \
   + OR_VAR_TABLE_ELEMENT_OFFSET_INTERNAL (OR_GET_OBJECT_VAR_TABLE (obj), \
                                           index, OR_GET_OFFSET_SIZE (obj)))
Definition at line 554 of file object_representation.h.
Referenced by heap_attrvalue_read(), heap_midxkey_get_value(), or_class_get_partition_info(), or_class_name(), or_class_tde_algorithm(), or_find_diskattr(), or_get_all_representation(), or_get_constraint_comment(), or_get_current_representation(), or_get_hierarchy_helper(), or_get_old_representation(), or_get_unique_hierarchy(), orc_subclasses_from_record(), and orc_superclasses_from_record().
#define OR_VAR_TABLE_ELEMENT_LENGTH_INTERNAL (table, index, offset_size)
Value:
(OR_VAR_TABLE_ELEMENT_OFFSET_INTERNAL (table, (index) + 1, offset_size) \
   - OR_VAR_TABLE_ELEMENT_OFFSET_INTERNAL (table, (index), offset_size))
Definition at line 446 of file object_representation.h.
#define OR_VAR_TABLE_ELEMENT_OFFSET_INTERNAL (table, index, offset_size)
Value:
((offset_size == OR_BYTE_SIZE) \
   ? (OR_GET_BYTE (OR_VAR_TABLE_ELEMENT_PTR (table, index, offset_size))) \
   : ((offset_size == OR_SHORT_SIZE) \
      ? (OR_GET_SHORT (OR_VAR_TABLE_ELEMENT_PTR (table, index, offset_size))) \
      : (OR_GET_INT (OR_VAR_TABLE_ELEMENT_PTR (table, index, offset_size)))))
Definition at line 439 of file object_representation.h.
#define OR_VAR_TABLE_ELEMENT_PTR (table, index, offset_size)
Value:
((offset_size == OR_BYTE_SIZE) \
   ? (&((char *) (table))[(index)]) \
   : ((offset_size == OR_SHORT_SIZE) \
      ? ((char *) (&((short *) (table))[(index)])) \
      : ((char *) (&((int *) (table))[(index)]))))
Definition at line 432 of file object_representation.h.
#define OR_VAR_TABLE_SIZE (vars) (OR_VAR_TABLE_SIZE_INTERNAL (vars, BIG_VAR_OFFSET_SIZE))
Definition at line 426 of file object_representation.h.
Referenced by attribute_size(), attribute_to_disk(), catcls_guess_record_length(), catcls_put_or_value_into_buffer(), domain_size(), domain_to_disk(), metharg_size(), metharg_to_disk(), methfile_size(), methfile_to_disk(), method_size(), method_to_disk(), methsig_size(), methsig_to_disk(), or_class_get_partition_info(), or_disk_set_size(), or_find_diskattr(), or_get_all_representation(), or_get_current_representation(), or_get_domain_internal(), or_get_old_representation(), or_get_set(), or_get_unique_hierarchy(), or_packed_set_length(), or_put_set(), or_skip_set_header(), partition_info_size(), partition_info_to_disk(), put_class_varinfo(), put_substructure_set(), query_spec_size(), query_spec_to_disk(), repattribute_size(), repattribute_to_disk(), representation_size(), representation_to_disk(), resolution_size(), resolution_to_disk(), root_size(), root_to_disk(), substructure_set_size(), and tf_class_size().
#define OR_VAR_TABLE_SIZE_INTERNAL (vars, offset_size) (((vars) == 0) ? 0 : DB_ALIGN ((offset_size * ((vars) + 1)), INT_ALIGNMENT))
Definition at line 429 of file object_representation.h.
Referenced by heap_attrinfo_get_disksize(), object_disk_size(), object_size(), and put_varinfo().
#define OR_VARIABLE_HEADER_SIZE 4
Definition at line 735 of file object_representation.h.
#define swap64 (x)
Value:
((((unsigned long long) (x) & (0x00000000000000FFULL)) << 56) \
   | (((unsigned long long) (x) & (0xFF00000000000000ULL)) >> 56) \
   | (((unsigned long long) (x) & (0x000000000000FF00ULL)) << 40) \
   | (((unsigned long long) (x) & (0x00FF000000000000ULL)) >> 40) \
   | (((unsigned long long) (x) & (0x0000000000FF0000ULL)) << 24) \
   | (((unsigned long long) (x) & (0x0000FF0000000000ULL)) >> 24) \
   | (((unsigned long long) (x) & (0x00000000FF000000ULL)) << 8) \
   | (((unsigned long long) (x) & (0x000000FF00000000ULL)) >> 8))
Definition at line 164 of file object_representation.h.
Typedef Documentation
typedef struct db_binary DB_BINARY
Definition at line 973 of file object_representation.h.
typedef struct db_reference DB_REFERENCE
Definition at line 988 of file object_representation.h.
typedef struct or_buf OR_BUF
Definition at line 1058 of file object_representation.h.
typedef struct or_varinfo OR_VARINFO
Definition at line 1023 of file object_representation.h.
typedef struct setobj SETOBJ
Definition at line 1000 of file object_representation.h.
typedef struct db_set SETREF
Definition at line 1002 of file object_representation.h.
Enumeration Type Documentation
anonymous enum
Enumerator
ORC_REP_DIR_OFFSET
ORC_HFID_FILEID_OFFSET
ORC_HFID_VOLID_OFFSET
ORC_HFID_PAGEID_OFFSET
ORC_FIXED_COUNT_OFFSET
ORC_VARIABLE_COUNT_OFFSET
ORC_FIXED_LENGTH_OFFSET
ORC_ATT_COUNT_OFFSET
ORC_SHARED_COUNT_OFFSET
ORC_CLASS_ATTR_COUNT_OFFSET
ORC_CLASS_FLAGS
ORC_CLASS_TYPE
ORC_CLASS_TDE_ALGORITHM
Definition at line 740 of file object_representation.h.
anonymous enum
Enumerator
ORC_NAME_INDEX
ORC_LOADER_COMMANDS_INDEX
ORC_REPRESENTATIONS_INDEX
ORC_SUBCLASSES_INDEX
ORC_SUPERCLASSES_INDEX
ORC_ATTRIBUTES_INDEX
ORC_SHARED_ATTRS_INDEX
ORC_CLASS_ATTRS_INDEX
ORC_METHODS_INDEX
ORC_CLASS_METHODS_INDEX
ORC_METHOD_FILES_INDEX
ORC_RESOLUTIONS_INDEX
ORC_QUERY_SPEC_INDEX
ORC_TRIGGERS_INDEX
ORC_PROPERTIES_INDEX
ORC_COMMENT_INDEX
ORC_PARTITION_INDEX
ORC_LAST_INDEX
ORC_CLASS_VAR_ATT_COUNT
Definition at line 757 of file object_representation.h.
anonymous enum
Enumerator
ORC_ATT_ID_OFFSET
ORC_ATT_TYPE_OFFSET
ORC_ATT_DEF_ORDER_OFFSET
ORC_ATT_CLASS_OFFSET
ORC_ATT_FLAG_OFFSET
ORC_ATT_INDEX_OFFSET
Definition at line 785 of file object_representation.h.
anonymous enum
Enumerator
ORC_ATT_NAME_INDEX
ORC_ATT_CURRENT_VALUE_INDEX
ORC_ATT_ORIGINAL_VALUE_INDEX
ORC_ATT_DOMAIN_INDEX
ORC_ATT_TRIGGER_INDEX
ORC_ATT_PROPERTIES_INDEX
ORC_ATT_COMMENT_INDEX
ORC_ATT_LAST_INDEX
ORC_ATT_VAR_ATT_COUNT
Definition at line 795 of file object_representation.h.
anonymous enum
Enumerator
ORC_REP_ID_OFFSET
ORC_REP_FIXED_COUNT_OFFSET
ORC_REP_VARIABLE_COUNT_OFFSET
Definition at line 813 of file object_representation.h.
anonymous enum
Enumerator
ORC_REP_ATTRIBUTES_INDEX
ORC_REP_PROPERTIES_INDEX
ORC_REP_LAST_INDEX
ORC_REP_VAR_ATT_COUNT
Definition at line 820 of file object_representation.h.
anonymous enum
Enumerator
ORC_REPATT_ID_OFFSET
ORC_REPATT_TYPE_OFFSET
Definition at line 833 of file object_representation.h.
anonymous enum
Enumerator
ORC_REPATT_DOMAIN_INDEX
ORC_REPATT_LAST_INDEX
ORC_REPATT_VAR_ATT_COUNT
Definition at line 839 of file object_representation.h.
anonymous enum
Enumerator
ORC_DOMAIN_TYPE_OFFSET
ORC_DOMAIN_PRECISION_OFFSET
ORC_DOMAIN_SCALE_OFFSET
ORC_DOMAIN_CODESET_OFFSET
ORC_DOMAIN_COLLATION_ID_OFFSET
ORC_DOMAIN_CLASS_OFFSET
Definition at line 851 of file object_representation.h.
anonymous enum
Enumerator
ORC_DOMAIN_SETDOMAIN_INDEX
ORC_DOMAIN_ENUMERATION_INDEX
ORC_DOMAIN_SCHEMA_JSON_OFFSET
ORC_DOMAIN_LAST_INDEX
ORC_DOMAIN_VAR_ATT_COUNT
Definition at line 861 of file object_representation.h.
anonymous enum
Enumerator
ORC_METHOD_NAME_INDEX
ORC_METHOD_SIGNATURE_INDEX
ORC_METHOD_PROPERTIES_INDEX
ORC_METHOD_LAST_INDEX
ORC_METHOD_VAR_ATT_COUNT
Definition at line 875 of file object_representation.h.
anonymous enum
Enumerator
ORC_METHARG_DOMAIN_INDEX
ORC_METHARG_LAST_INDEX
ORC_METHARG_VAR_ATT_COUNT
Definition at line 889 of file object_representation.h.
anonymous enum
Enumerator
ORC_METHSIG_FUNCTION_NAME_INDEX
ORC_METHSIG_SQL_DEF_INDEX
ORC_METHSIG_RETURN_VALUE_INDEX
ORC_METHSIG_ARGUMENTS_INDEX
ORC_METHSIG_LAST_INDEX
ORC_METHSIG_VAR_ATT_COUNT
Definition at line 901 of file object_representation.h.
anonymous enum
Enumerator
ORC_METHFILE_NAME_INDEX
ORC_METHFILE_PROPERTIES_INDEX
ORC_METHFILE_LAST_INDEX
ORC_METHFILE_VAR_ATT_COUNT
Definition at line 916 of file object_representation.h.
anonymous enum
Enumerator
ORC_QUERY_SPEC_SPEC_INDEX
ORC_QUERY_LAST_INDEX
ORC_QUERY_SPEC_VAR_ATT_COUNT
Definition at line 929 of file object_representation.h.
anonymous enum
Enumerator
ORC_RES_NAME_INDEX
ORC_RES_ALIAS_INDEX
ORC_RES_LAST_INDEX
ORC_RES_VAR_ATT_COUNT
Definition at line 941 of file object_representation.h.
anonymous enum
Enumerator
ORC_PARTITION_NAME_INDEX
ORC_PARTITION_EXPR_INDEX
ORC_PARTITION_VALUES_INDEX
ORC_PARTITION_COMMENT_INDEX
ORC_PARTITION_LAST_INDEX
ORC_PARTITION_VAR_ATT_COUNT
Definition at line 954 of file object_representation.h.
Function Documentation
int classobj_decompose_property_oid (const char * buffer, int * volid, int * fileid, int * pageid)
Definition at line 176 of file object_representation.c.
References NULL, and str_to_int32().
Referenced by classobj_btid_from_property_value(), classobj_drop_foreign_key_ref(), classobj_oid_from_property_value(), classobj_put_foreign_key_ref(), or_install_btids_constraint(), or_install_btids_foreign_key(), and or_install_btids_foreign_key_ref().
int classobj_get_prop (DB_SEQ * properties, const char * name, DB_VALUE * pvalue)
Definition at line 105 of file object_representation.c.
References ARG_FILE_LINE, db_get_string(), DB_TYPE_STRING, DB_VALUE_TYPE, ER_ERROR_SEVERITY, er_set(), ER_SM_INVALID_PROPERTY, error(), i, max, NO_ERROR, NULL, pr_clear_value(), set_get_element(), and set_size().
Referenced by catcls_get_or_value_from_attribute(), catcls_get_property_set(), classobj_cache_constraints(), classobj_change_constraint_comment(), classobj_change_constraint_status(), classobj_drop_foreign_key_ref(), classobj_find_prop_constraint(), classobj_make_class_constraints(), classobj_put_foreign_key_ref(), classobj_put_index(), disk_to_attribute(), filter_local_constraints(), or_get_current_representation(), smt_drop_constraint_from_property(), vid_att_in_obj_id(), and ws_rehash_vmop().
void classobj_initialize_default_expr (DB_DEFAULT_EXPR * default_expr)
Definition at line 8041 of file object_representation.c.
References assert, DB_DEFAULT_NONE, db_default_expr::default_expr_format, db_default_expr::default_expr_op, db_default_expr::default_expr_type, NULL, and NULL_DEFAULT_EXPRESSION_OPERATOR.
Referenced by classobj_initialize_attributes(), classobj_make_attribute(), disk_to_attribute(), do_change_att_schema_only(), or_get_all_representation(), or_get_current_representation(), or_get_old_representation(), pt_get_default_expression_from_data_default_node(), smt_set_attribute_default(), and smt_set_attribute_orig_default_value().
int db_enum_put_cs_and_collation (DB_VALUE * value, const int codeset, const int collation_id)
Definition at line 4191 of file db_macro.c.
References ARG_FILE_LINE, db_domain_info::char_info, CHECK_1ARG_ERROR, db_char::codeset, db_domain_info::char_info::collation_id, db_value::data, DB_TYPE_ENUMERATION, db_value::domain, db_data::enumeration, ER_QPROC_INVALID_DATATYPE, er_set(), ER_WARNING_SEVERITY, error(), db_domain_info::general_info, db_char::info, NO_ERROR, db_enum_element::str_val, and db_domain_info::general_info::type.
Referenced by fetch_peek_arith(), fetch_peek_dbval(), and or_get_value().
int db_string_put_cs_and_collation (DB_VALUE * value, const int codeset, const int collation_id)
Definition at line 4164 of file db_macro.c.
References ARG_FILE_LINE, db_data::ch, db_domain_info::char_info, CHECK_1ARG_ERROR, db_char::codeset, db_domain_info::char_info::collation_id, db_value::data, db_value::domain, ER_QPROC_INVALID_DATATYPE, er_set(), ER_WARNING_SEVERITY, error(), db_domain_info::general_info, db_char::info, NO_ERROR, TP_IS_CHAR_TYPE, and db_domain_info::general_info::type.
Referenced by db_clob_to_char(), db_date_dbval(), db_date_format(), db_json_search_func(), db_string_concatenate(), db_string_convert_to(), db_time_dbval(), db_time_format(), db_to_char(), fetch_peek_arith(), fetch_peek_dbval(), jsp_unpack_string_value(), netval_to_dbval(), or_get_value(), pt_coerce_node_collation(), pt_make_regu_hostvar(), qdata_list_dbs(), qexec_resolve_domains_for_group_by(), qo_find_like_rewrite_bound(), tp_value_cast_internal(), tp_value_compare_with_error(), and tp_value_slam_domain().
void or_abort (OR_BUF * buf)
Definition at line 621 of file object_representation.c.
References or_buf::env, er_errid(), and or_buf::error_abort.
Referenced by class_to_disk(), disk_to_attribute(), disk_to_class(), disk_to_domain2(), disk_to_metharg(), disk_to_methfile(), disk_to_method(), disk_to_methsig(), disk_to_partition_info(), disk_to_query_spec(), disk_to_repattribute(), disk_to_representation(), disk_to_resolution(), disk_to_root(), get_current(), get_desc_old(), get_object_set(), get_old(), get_property_list(), get_substructure_set(), mr_data_readmem_bit(), mr_data_readmem_char(), mr_data_readmem_elo(), mr_data_readmem_nchar(), mr_data_readmem_numeric(), mr_data_readmem_set(), mr_data_readmem_string(), mr_data_readmem_varbit(), mr_data_readval_object(), mr_data_readval_set(), mr_index_readval_midxkey(), mr_readval_bit_internal(), mr_readval_char_internal(), mr_readval_nchar_internal(), mr_readval_string_internal(), mr_readval_varbit_internal(), mr_readval_varnchar_internal(), or_get_offset_internal(), or_get_set(), or_get_value(), or_get_var_table_internal(), or_put_oid(), or_put_varchar_internal(), put_attributes(), tf_class_to_disk(), tf_mem_to_disk(), and tf_need_permanent_oid().
int or_advance (OR_BUF * buf, int offset)
Definition at line 2368 of file object_representation.c.
References or_buf::endptr, NO_ERROR, or_overflow(), and or_buf::ptr.
Referenced by btree_construct_leafs(), btree_leaf_get_nth_oid_ptr(), btree_read_record_without_decompression(), btree_record_get_num_visible_oids(), btree_sort_get_next(), catcls_convert_attr_id_to_name(), catcls_get_or_value_from_attribute(), catcls_get_or_value_from_attrid(), catcls_get_or_value_from_buffer(), catcls_get_or_value_from_class(), catcls_get_or_value_from_class_record(), catcls_get_or_value_from_method(), catcls_get_or_value_from_method_file(), catcls_get_or_value_from_method_signiture(), catcls_put_or_value_into_buffer(), desc_disk_to_obj(), disk_to_root(), get_current(), get_desc_current(), get_desc_old(), get_old(), heap_midxkey_key_generate(), heap_midxkey_key_get(), la_disk_to_obj(), la_get_current(), log_rv_undoredo_partial_changes_recursive(), mr_data_readmem_bigint(), mr_data_readmem_bit(), mr_data_readmem_char(), mr_data_readmem_date(), mr_data_readmem_datetime(), mr_data_readmem_datetimetz(), mr_data_readmem_double(), mr_data_readmem_elo(), mr_data_readmem_enumeration(), mr_data_readmem_float(), mr_data_readmem_int(), mr_data_readmem_json(), mr_data_readmem_money(), mr_data_readmem_nchar(), mr_data_readmem_numeric(), mr_data_readmem_object(), mr_data_readmem_resultset(), mr_data_readmem_set(), mr_data_readmem_short(), mr_data_readmem_string(), mr_data_readmem_time(), mr_data_readmem_timestamptz(), mr_data_readmem_utime(), mr_data_readmem_varbit(), mr_data_readval_bigint(), mr_data_readval_date(), mr_data_readval_datetime(), mr_data_readval_datetimeltz(), mr_data_readval_datetimetz(), mr_data_readval_double(), mr_data_readval_enumeration(), mr_data_readval_float(), mr_data_readval_int(), mr_data_readval_money(), mr_data_readval_numeric(), mr_data_readval_object(), mr_data_readval_oid(), mr_data_readval_resultset(), mr_data_readval_set(), mr_data_readval_short(), mr_data_readval_time(), mr_data_readval_timestampltz(), mr_data_readval_timestamptz(), mr_data_readval_utime(), mr_data_writeval_set(), mr_index_readval_bigint(), mr_index_readval_date(), mr_index_readval_datetime(), mr_index_readval_datetimeltz(), mr_index_readval_datetimetz(), mr_index_readval_double(), mr_index_readval_enumeration(), mr_index_readval_float(), mr_index_readval_int(), mr_index_readval_midxkey(), mr_index_readval_money(), mr_index_readval_oid(), mr_index_readval_short(), mr_index_readval_time(), mr_index_readval_timestampltz(), mr_index_readval_timestamptz(), mr_index_readval_utime(), mr_readval_bit_internal(), mr_readval_char_internal(), mr_readval_nchar_internal(), mr_readval_string_internal(), mr_readval_varbit_internal(), mr_readval_varnchar_internal(), or_disk_set_size(), or_get_align32(), or_get_align64(), or_get_set(), or_get_value(), or_put_set(), or_skip_set_header(), or_skip_varbit_remainder(), or_skip_varchar_remainder(), or_unpack_mem_value(), peekmem_elo(), pr_midxkey_add_elements(), pr_midxkey_get_element_internal(), pr_midxkey_get_element_offset(), put_substructure_set(), qdata_load_agg_hentry_from_tuple(), qfile_locate_tuple_next_value(), readval_elo_with_type(), and tf_disk_to_mem().
int or_align (OR_BUF * buf, int alignment)
Definition at line 2410 of file object_representation.c.
References or_buf::endptr, NO_ERROR, or_overflow(), or_buf::ptr, and PTR_ALIGN.
Referenced by btree_recompress_record(), db_json_unpack_string_to_value(), log_rv_undoredo_partial_changes_recursive(), or_put_string_aligned_with_length(), and unpack_domain().
int or_chn (RECDES * record)
Definition at line 400 of file object_representation.c.
References ARG_FILE_LINE, recdes::data, ER_ERROR_SEVERITY, er_set(), ER_TF_BUFFER_UNDERFLOW, recdes::length, NULL_CHN, OR_CHN_OFFSET, OR_CHN_SIZE, and OR_GET_MVCC_CHN.
Referenced by catcls_update_instance(), heap_attrinfo_read_dbvalues(), heap_attrinfo_set_uninitialized(), heap_get_record_info(), heap_insert_logical(), heap_ovf_get(), heap_update_logical(), locator_cache_have_object(), locator_cache_object_class(), locator_cache_object_instance(), locator_repl_prepare_force(), and locator_return_object_assign().
char* or_class_name (RECDES * record)
Definition at line 285 of file object_representation.c.
References recdes::data, OR_INT_SIZE, and OR_VAR_OFFSET.
Referenced by catalog_check_consistency(), catalog_dump(), heap_classrepr_dump(), heap_get_class_info_from_record(), heap_get_class_name_alloc_if_diff(), locator_check_class_names(), locator_delete_force_internal(), locator_initialize(), locator_insert_force(), locator_update_force(), qexec_execute_build_indexes(), and xstats_update_all_statistics().
int or_db_value_size (DB_VALUE * var)
Definition at line 7052 of file object_representation.c.
References or_packed_value_size().
Referenced by or_header_size(), sserial_get_current_value(), sserial_get_next_value(), ssession_get_session_variable(), and xts_sizeof_db_value().
void or_decode (const char * buffer, char * dest, int size)
Definition at line 3869 of file object_representation.c.
Referenced by vid_decode_object().
int or_disk_set_size (OR_BUF * buf, struct tp_domain * domain, DB_TYPE * set_type)
Definition at line 5934 of file object_representation.c.
References BIG_VAR_OFFSET_SIZE, i, tp_domain::next, NO_ERROR, NULL, or_advance(), OR_BOUND_BIT_BYTES, or_get_domain(), OR_GET_INT, or_get_int(), OR_GET_OFFSET, or_get_set_header(), or_get_value(), OR_INT_SIZE, OR_VAR_TABLE_SIZE, or_buf::ptr, rc, tp_domain::setdomain, and tp_domain_disk_size().
Referenced by mr_data_readval_set().
void or_encode (char * buffer, const char * source, int size)
Definition at line 3850 of file object_representation.c.
Referenced by vid_encode_object().
int or_get_align (OR_BUF * buf, int align)
Definition at line 723 of file object_representation.c.
References or_buf::endptr, NO_ERROR, or_overflow(), or_buf::ptr, and PTR_ALIGN.
int or_get_align32 (OR_BUF * buf)
Definition at line 682 of file object_representation.c.
References NO_ERROR, or_advance(), or_buf::ptr, and rc.
Referenced by mr_data_readmem_string(), mr_data_readmem_varbit(), mr_readval_string_internal(), mr_readval_varbit_internal(), mr_readval_varnchar_internal(), or_get_offset_internal(), or_put_varchar_internal(), or_skip_varbit_remainder(), and or_skip_varchar_remainder().
int or_get_align64 (OR_BUF * buf)
Definition at line 702 of file object_representation.c.
References NO_ERROR, or_advance(), or_buf::ptr, and rc.
Referenced by or_pack_mem_value(), and or_unpack_mem_value().
DB_BIGINT or_get_bigint (OR_BUF * buf, int * error)
Definition at line 1606 of file object_representation.c.
References ASSERT_ALIGN, or_buf::endptr, INT_ALIGNMENT, NO_ERROR, OR_BIGINT_SIZE, OR_GET_BIGINT, or_underflow(), and or_buf::ptr.
Referenced by db_json_unpack_bigint_to_value(), mr_data_readmem_bigint(), mr_data_readval_bigint(), and peekmem_elo().
int or_get_byte (OR_BUF * buf, int * error)
Definition at line 1459 of file object_representation.c.
References or_buf::endptr, NO_ERROR, OR_BYTE_SIZE, OR_GET_BYTE, or_underflow(), and or_buf::ptr.
Referenced by log_rv_undoredo_partial_changes_recursive(), or_get_offset_internal(), and or_get_varbit_length().
int or_get_data (OR_BUF * buf, char * data, int length)
Definition at line 2183 of file object_representation.c.
References or_buf::endptr, NO_ERROR, or_underflow(), and or_buf::ptr.
Referenced by catcls_get_or_value_from_buffer(), get_current(), mr_data_readmem_bit(), mr_data_readmem_char(), mr_data_readmem_nchar(), mr_data_readmem_numeric(), mr_data_readmem_varbit(), mr_index_readval_bigint(), mr_index_readval_date(), mr_index_readval_datetime(), mr_index_readval_datetimeltz(), mr_index_readval_datetimetz(), mr_index_readval_double(), mr_index_readval_enumeration(), mr_index_readval_float(), mr_index_readval_int(), mr_index_readval_midxkey(), mr_index_readval_money(), mr_index_readval_oid(), mr_index_readval_short(), mr_index_readval_time(), mr_index_readval_timestampltz(), mr_index_readval_timestamptz(), mr_index_readval_utime(), mr_readval_bit_internal(), mr_readval_char_internal(), mr_readval_nchar_internal(), mr_readval_string_internal(), mr_readval_varbit_internal(), mr_readval_varnchar_internal(), or_get_offset_internal(), or_get_varbit_length(), or_get_varchar_compression_lengths(), or_put_varchar_internal(), and pr_get_compressed_data_from_buffer().
int or_get_date (OR_BUF * buf, DB_DATE * date)
Definition at line 1897 of file object_representation.c.
References ASSERT_ALIGN, or_buf::endptr, INT_ALIGNMENT, NO_ERROR, OR_DATE_SIZE, OR_GET_DATE, or_underflow(), and or_buf::ptr.
Referenced by mr_data_readmem_date(), and mr_data_readval_date().
int or_get_datetime (OR_BUF * buf, DB_DATETIME * datetime)
Definition at line 1943 of file object_representation.c.
References ASSERT_ALIGN, or_buf::endptr, INT_ALIGNMENT, NO_ERROR, OR_DATETIME_SIZE, OR_GET_DATETIME, or_underflow(), and or_buf::ptr.
Referenced by mr_data_readmem_datetime(), mr_data_readval_datetime(), and mr_data_readval_datetimeltz().
int or_get_datetimetz (OR_BUF * buf, DB_DATETIMETZ * datetimetz)
Definition at line 1989 of file object_representation.c.
References ASSERT_ALIGN, or_buf::endptr, INT_ALIGNMENT, NO_ERROR, OR_DATETIMETZ_SIZE, OR_GET_DATETIMETZ, or_underflow(), and or_buf::ptr.
Referenced by mr_data_readmem_datetimetz(), and mr_data_readval_datetimetz().
struct tp_domain* or_get_domain (OR_BUF * buf, struct tp_domain * dom, int * is_null)
Definition at line 5116 of file object_representation.c.
References tp_domain::is_cached, NULL, tp_domain_cache(), tp_domain_free(), tp_domain_match(), TP_SET_MATCH, unpack_domain(), and unpack_domain_2().
Referenced by btree_dump_root_header(), btree_glean_root_header_info(), btree_scan_for_show_index_header(), catalog_fetch_btree_statistics(), or_disk_set_size(), or_get_set(), or_get_value(), or_unpack_domain(), or_unpack_mem_value(), and xbtree_get_key_type().
double or_get_double (OR_BUF * buf, int * error)
Definition at line 1704 of file object_representation.c.
References ASSERT_ALIGN, or_buf::endptr, INT_ALIGNMENT, NO_ERROR, OR_DOUBLE_SIZE, OR_GET_DOUBLE, or_underflow(), and or_buf::ptr.
Referenced by db_json_unpack_double_to_value(), mr_data_readmem_double(), and mr_data_readval_double().
int or_get_enumeration (OR_BUF * buf, DB_ENUMERATION * e)
Definition at line 7152 of file object_representation.c.
References ARG_FILE_LINE, assert, assert_release, db_data::ch, lang_collation::codeset, db_enumeration::collation_id, cubregex::count(), db_enumeration::count, db_value::data, pr_type::data_readval(), DB_GET_ENUM_ELEM_DBCHAR, DB_GET_ENUM_ELEM_STRING, db_get_string(), db_get_string_size(), db_make_null(), DB_SET_ENUM_ELEM_CODESET, DB_SET_ENUM_ELEM_STRING, DB_SET_ENUM_ELEM_STRING_SIZE, db_enumeration::elements, ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, db_char::info, lang_get_collation(), NO_ERROR, NULL, or_skip_set_header(), pr_clear_value(), db_enum_element::short_val, and tp_String.
Referenced by get_enumeration(), or_get_domain_internal(), unpack_domain(), and unpack_domain_2().
float or_get_float (OR_BUF * buf, int * error)
Definition at line 1655 of file object_representation.c.
References ASSERT_ALIGN, or_buf::endptr, FLOAT_ALIGNMENT, NO_ERROR, OR_FLOAT_SIZE, OR_GET_FLOAT, or_underflow(), and or_buf::ptr.
Referenced by mr_data_readmem_float(), and mr_data_readval_float().
int or_get_int (OR_BUF * buf, int * error)
Definition at line 1557 of file object_representation.c.
References ASSERT_ALIGN, or_buf::endptr, INT_ALIGNMENT, NO_ERROR, OR_GET_INT, OR_INT_SIZE, or_underflow(), and or_buf::ptr.
Referenced by btree_delete_overflow_key(), btree_key_insert_new_key(), btree_leaf_get_vpid_for_overflow_oids(), btree_read_fixed_portion_of_non_leaf_record_from_orbuf(), btree_read_record_without_decompression(), db_json_deserialize_doc_internal(), db_json_unpack_array_to_value(), db_json_unpack_bigint_to_value(), db_json_unpack_bool_to_value(), db_json_unpack_int_to_value(), db_json_unpack_object_to_value(), db_json_unpack_string_to_value(), disk_to_attribute(), disk_to_class(), disk_to_domain2(), disk_to_metharg(), disk_to_method(), disk_to_methsig(), disk_to_partition_info(), disk_to_repattribute(), disk_to_representation(), disk_to_resolution(), disk_to_root(), mr_data_readmem_int(), mr_data_readmem_resultset(), mr_data_readval_int(), mr_data_readval_resultset(), mr_readval_bit_internal(), mr_readval_char_internal(), mr_readval_nchar_internal(), or_disk_set_size(), or_get_offset_internal(), or_get_set(), or_get_set_header(), or_skip_set_header(), peekmem_elo(), tf_disk_to_class(), tf_disk_to_mem(), unpack_domain(), and unpack_domain_2().
int or_get_monetary (OR_BUF * buf, DB_MONETARY * monetary)
Definition at line 2078 of file object_representation.c.
References ASSERT_ALIGN, or_buf::endptr, INT_ALIGNMENT, NO_ERROR, OR_GET_MONETARY, OR_MONETARY_SIZE, or_underflow(), and or_buf::ptr.
Referenced by mr_data_readmem_money(), and mr_data_readval_money().
int or_get_mvccid (OR_BUF * buf, MVCCID * mvccid)
Definition at line 7555 of file object_representation.c.
References assert, ASSERT_ALIGN, or_buf::endptr, INT_ALIGNMENT, MVCCID_NULL, NO_ERROR, NULL, OR_GET_MVCCID, OR_MVCCID_SIZE, or_underflow(), and or_buf::ptr.
Referenced by btree_check_valid_record(), btree_construct_leafs(), and btree_dump_leaf_record().
int or_get_offset (OR_BUF * buf, int * error)
Definition at line 1277 of file object_representation.c.
References BIG_VAR_OFFSET_SIZE, and or_get_offset_internal().
int or_get_offset_internal (OR_BUF * buf, int * error, int offset_size)
Definition at line 1283 of file object_representation.c.
References assert, BIG_VAR_OFFSET_SIZE, BITS_TO_BYTES, db_private_alloc, db_private_free_and_init, NO_ERROR, NULL, or_abort(), OR_BYTE_SIZE, or_get_align32(), or_get_byte(), or_get_data(), or_get_int(), or_get_short(), or_get_varbit_length(), OR_SHORT_SIZE, and rc.
Referenced by get_current(), get_desc_current(), get_desc_old(), get_old(), la_get_current(), and or_get_offset().
int or_get_oid (OR_BUF * buf, OID * oid)
Definition at line 2137 of file object_representation.c.
References ASSERT_ALIGN, or_buf::endptr, INT_ALIGNMENT, NO_ERROR, OR_GET_OID, OR_OID_SIZE, or_underflow(), and or_buf::ptr.
Referenced by btree_check_valid_record(), btree_construct_leafs(), btree_dump_leaf_record(), btree_key_find_first_visible_row(), btree_or_get_object(), btree_verify_leaf_node(), disk_to_class(), mr_data_readmem_object(), mr_data_readmem_oid(), mr_data_readval_object(), mr_data_readval_oid(), unpack_domain(), and unpack_domain_2().
setobj* or_get_set (OR_BUF * buf, struct tp_domain * domain)
Definition at line 5741 of file object_representation.c.
References BIG_VAR_OFFSET_SIZE, DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_make_null(), DB_TYPE_NULL, db_value_domain_init(), i, tp_domain::next, NO_ERROR, NULL, or_abort(), or_advance(), OR_BOUND_BIT_BYTES, or_get_domain(), OR_GET_INT, or_get_int(), OR_GET_OFFSET, or_get_set_header(), or_get_value(), OR_INT_SIZE, OR_VAR_TABLE_SIZE, pr_clear_value(), or_buf::ptr, rc, tp_domain::setdomain, setobj_create(), setobj_domain(), setobj_put_domain(), setobj_put_value(), and tp_domain_disk_size().
Referenced by mr_data_readmem_set(), mr_data_readval_set(), or_unpack_set(), and set_tform_disk_set().
int or_get_set_header (OR_BUF * buf, DB_TYPE * set_type, int * size, int * domain, int * bound_bits, int * offset_table, int * element_tags, int * common_sub_header)
Definition at line 5389 of file object_representation.c.
References NO_ERROR, NULL, or_get_int(), OR_SET_BOUND_BIT, OR_SET_COMMON_SUB_BIT, OR_SET_DOMAIN_BIT, OR_SET_TAG_BIT, OR_SET_TYPE_MASK, OR_SET_VARIABLE_BIT, and rc.
Referenced by mr_data_readval_set(), or_disk_set_size(), or_get_set(), and or_skip_set_header().
int or_get_short (OR_BUF * buf, int * error)
Definition at line 1507 of file object_representation.c.
References ASSERT_ALIGN, or_buf::endptr, NO_ERROR, OR_GET_SHORT, OR_SHORT_SIZE, or_underflow(), or_buf::ptr, and SHORT_ALIGNMENT.
Referenced by btree_delete_overflow_key(), btree_key_insert_new_key(), btree_leaf_get_vpid_for_overflow_oids(), btree_read_fixed_portion_of_non_leaf_record_from_orbuf(), btree_read_record_without_decompression(), log_rv_undoredo_partial_changes_recursive(), mr_data_readmem_enumeration(), mr_data_readmem_short(), mr_data_readval_enumeration(), mr_data_readval_short(), and or_get_offset_internal().
STATIC_INLINE int or_get_string_size_byte (OR_BUF * buf, int * error)
Definition at line 1424 of file object_representation.h.
References or_buf::endptr, NO_ERROR, OR_BYTE_SIZE, OR_GET_BYTE, or_underflow(), or_buf::ptr, and STATIC_INLINE.
Referenced by or_get_varchar_compression_lengths().
int or_get_time (OR_BUF * buf, DB_TIME * timeval)
Definition at line 1759 of file object_representation.c.
References ASSERT_ALIGN, or_buf::endptr, INT_ALIGNMENT, NO_ERROR, OR_GET_TIME, OR_TIME_SIZE, or_underflow(), and or_buf::ptr.
Referenced by mr_data_readmem_time(), and mr_data_readval_time().
int or_get_timestamptz (OR_BUF * buf, DB_TIMESTAMPTZ * ts_tz)
Definition at line 1851 of file object_representation.c.
References ASSERT_ALIGN, or_buf::endptr, INT_ALIGNMENT, NO_ERROR, OR_GET_TIMESTAMPTZ, OR_TIMESTAMPTZ_SIZE, or_underflow(), and or_buf::ptr.
Referenced by mr_data_readmem_timestamptz(), and mr_data_readval_timestamptz().
int or_get_utime (OR_BUF * buf, DB_UTIME * timeval)
Definition at line 1805 of file object_representation.c.
References ASSERT_ALIGN, or_buf::endptr, INT_ALIGNMENT, NO_ERROR, OR_GET_UTIME, or_underflow(), OR_UTIME_SIZE, and or_buf::ptr.
Referenced by mr_data_readmem_utime(), mr_data_readval_timestampltz(), and mr_data_readval_utime().
int or_get_value (OR_BUF * buf, DB_VALUE * value, struct tp_domain * domain, int expected, bool copy)
Definition at line 6295 of file object_representation.c.
References ARG_FILE_LINE, CAST_BUFLEN, db_value::data, pr_type::data_readval(), db_enum_put_cs_and_collation(), db_make_null(), db_string_put_cs_and_collation(), DB_TYPE_ENUMERATION, DB_TYPE_JSON, db_value_put_null(), ER_ERROR_SEVERITY, ER_FAILED, ER_GENERIC_ERROR, er_set(), db_data::json, NO_ERROR, NULL, or_abort(), or_advance(), or_get_domain(), or_buf::ptr, rc, db_json::schema_raw, TP_DOMAIN_CODESET, TP_DOMAIN_COLLATION, TP_DOMAIN_TYPE, tp_init_value_domain(), TP_IS_CHAR_TYPE, and tp_domain::type.
Referenced by catcls_get_or_value_from_attribute(), catcls_get_or_value_from_partition(), disk_to_attribute(), disk_to_partition_info(), or_class_get_partition_info(), or_disk_set_size(), or_get_current_representation(), or_get_set(), and or_unpack_value().
OR_VARINFO* or_get_var_table (OR_BUF * buf, int nvars, char *(*)(int) allocator)
Definition at line 2489 of file object_representation.c.
References BIG_VAR_OFFSET_SIZE, and or_get_var_table_internal().
Referenced by catcls_convert_attr_id_to_name(), catcls_get_or_value_from_attribute(), catcls_get_or_value_from_attrid(), catcls_get_or_value_from_buffer(), catcls_get_or_value_from_class(), catcls_get_or_value_from_domain(), catcls_get_or_value_from_method(), catcls_get_or_value_from_method_argument(), catcls_get_or_value_from_method_file(), catcls_get_or_value_from_method_signiture(), catcls_get_or_value_from_partition(), catcls_get_or_value_from_query_spec(), and catcls_get_or_value_from_resolution().
OR_VARINFO* or_get_var_table_internal (OR_BUF * buf, int nvars, char *(*)(int) allocator, int offset_size)
Definition at line 2503 of file object_representation.c.
References DB_ALIGN, or_buf::endptr, INT_ALIGNMENT, NULL, or_abort(), or_underflow(), or_unpack_var_table_internal(), and or_buf::ptr.
Referenced by or_get_var_table(), and read_var_table_internal().
int or_get_varbit_length (OR_BUF * buf, int * intval)
Definition at line 1363 of file object_representation.c.
References NO_ERROR, or_get_byte(), or_get_data(), OR_GET_INT, and OR_INT_SIZE.
Referenced by mr_data_cmpdisk_varbit(), mr_data_readmem_varbit(), mr_index_lengthmem_varbit(), mr_readval_varbit_internal(), or_get_offset_internal(), and or_skip_varbit().
STATIC_INLINE int or_get_varchar_compression_lengths (OR_BUF * buf, int * compressed_size, int * decompressed_size)
Definition at line 1451 of file object_representation.h.
References assert, NO_ERROR, or_get_data(), OR_GET_INT, or_get_string_size_byte(), OR_INT_SIZE, OR_MINIMUM_STRING_LENGTH_FOR_COMPRESSION, and rc.
Referenced by bf2df_str_cmpdisk(), mr_data_cmpdisk_string(), mr_data_cmpdisk_varnchar(), mr_data_readmem_string(), mr_index_lengthmem_string(), mr_readval_string_internal(), mr_readval_varnchar_internal(), or_get_attr_string(), or_get_varchar_length(), and stran_can_end_after_query_execution().
int or_get_varchar_length (OR_BUF * buf, int * intval)
Definition at line 1038 of file object_representation.c.
References or_get_varchar_compression_lengths().
Referenced by or_put_varchar_internal(), and or_skip_varchar().
int or_header_size (char * ptr)
Definition at line 7265 of file object_representation.c.
References cubregex::count(), db_private_alloc, i, mvcc_header_size_lookup, NULL, or_db_value_size(), OR_GET_MVCC_FLAG, OR_INT_SIZE, or_pack_db_value(), or_pack_int(), or_pack_string(), or_packed_string_length(), or_unpack_db_value(), or_unpack_int(), and or_unpack_string().
void or_init (OR_BUF * buf, char * data, int length)
Definition at line 638 of file object_representation.c.
References or_buf::buffer, DB_INT32_MAX, or_buf::endptr, or_buf::error_abort, or_buf::fixups, NULL, OR_INFINITE_POINTER, and or_buf::ptr.
Referenced by bf2df_str_cmpdisk(), btree_check_valid_record(), btree_construct_leafs(), btree_delete_overflow_key(), btree_dump_leaf_record(), btree_dump_root_header(), btree_glean_root_header_info(), btree_key_find_first_visible_row(), btree_leaf_change_first_object(), btree_leaf_get_vpid_for_overflow_oids(), btree_load_overflow_key(), btree_pack_root_header(), btree_read_record_without_decompression(), btree_recompress_record(), btree_record_get_num_visible_oids(), btree_rv_read_keybuf_nocopy(), btree_rv_read_keybuf_two_objects(), btree_rv_save_keyval_for_undo(), btree_rv_save_keyval_for_undo_two_objects(), btree_scan_for_show_index_header(), btree_sort_get_next(), btree_store_overflow_key(), btree_verify_leaf_node(), btree_write_record(), catalog_fetch_btree_statistics(), catcls_convert_attr_id_to_name(), catcls_get_or_value_from_class_record(), catcls_get_or_value_from_record(), catcls_put_or_value_into_record(), cursor_get_first_tuple_value(), cursor_get_oid_from_vobj(), cursor_get_tuple_value_from_list(), desc_disk_to_obj(), desc_obj_to_disk(), eval_sub_sort_list_to_multi_set(), eval_sub_sort_list_to_sort_list(), heap_classrepr_dump(), heap_midxkey_get_value(), heap_midxkey_key_generate(), heap_midxkey_key_get(), la_disk_to_obj(), mr_data_cmpdisk_json(), mr_data_cmpdisk_numeric(), mr_data_cmpdisk_string(), mr_data_cmpdisk_varbit(), mr_data_cmpdisk_varnchar(), mr_index_lengthmem_string(), mr_index_lengthmem_varbit(), or_class_get_partition_info(), or_get_current_representation(), or_get_domain_internal(), or_mvcc_get_header(), or_pack_domain(), or_pack_mem_value(), or_pack_value(), or_unpack_domain(), or_unpack_mem_value(), or_unpack_set(), or_unpack_value(), pr_midxkey_add_elements(), pr_midxkey_get_element_internal(), pr_midxkey_get_element_offset(), qdata_convert_table_to_set(), qdata_finalize_aggregate_list(), qdata_finalize_analytic_func(), qexec_cmp_tpl_vals_merge(), qexec_compare_valptr_with_tuple(), qexec_get_attr_default(), qfile_compare_tuple_values(), qfile_locate_tuple_next_value(), set_tform_disk_set(), stran_can_end_after_query_execution(), tf_attribute_default_expr_to_property(), tf_class_to_disk(), tf_disk_to_class(), tf_disk_to_mem(), tf_mem_to_disk(), vid_decode_object(), vid_pack_db_value(), and xbtree_get_key_type().
int or_listid_length (void * listid)
Definition at line 6826 of file object_representation.c.
References qfile_tuple_value_type_list::domp, i, NULL, OR_INT_SIZE, or_packed_domain_size(), OR_PTR_SIZE, qfile_tuple_value_type_list::type_cnt, and qfile_list_id::type_list.
Referenced by sqmgr_execute_query(), sqmgr_prepare_and_execute_query(), xs_send_method_call_info_to_client(), and xts_sizeof_list_id().
int or_method_sig_list_length (void * method_sig_list_ptr)
Definition at line 7010 of file object_representation.c.
References method_sig_node::class_name, method_sig_node::method_name, method_sig_list::method_sig, method_sig_node::next, NULL, method_sig_node::num_method_args, OR_INT_SIZE, and or_packed_string_length().
Referenced by xs_send_method_call_info_to_client().
int or_mvcc_get_repid_and_flags (OR_BUF * buf, int * error)
Definition at line 447 of file object_representation.c.
References ASSERT_ALIGN, or_buf::endptr, INT_ALIGNMENT, NO_ERROR, OR_GET_INT, OR_INT_SIZE, or_underflow(), and or_buf::ptr.
Referenced by catcls_get_or_value_from_buffer(), desc_disk_to_obj(), la_disk_to_obj(), or_mvcc_get_header(), and tf_disk_to_mem().
int or_mvcc_set_repid_and_flags (OR_BUF * buf, int mvcc_flag, int repid, int bound_bit, int variable_offset_size)
Definition at line 476 of file object_representation.c.
References OR_BOUND_BIT_FLAG, OR_GET_BOUND_BIT, OR_MVCC_FLAG_MASK, OR_MVCC_FLAG_SHIFT_BITS, or_put_int(), and OR_SET_VAR_OFFSET_SIZE.
Referenced by or_mvcc_add_header(), and or_mvcc_set_header().
int or_overflow (OR_BUF * buf)
Definition at line 574 of file object_representation.c.
References or_buf::env, ER_TF_BUFFER_OVERFLOW, and or_buf::error_abort.
Referenced by btree_or_get_mvccinfo(), get_desc_old(), get_old(), log_rv_undoredo_partial_changes_recursive(), mr_data_writeval_json(), mr_data_writeval_set(), or_advance(), or_align(), or_get_align(), or_mvcc_set_prev_version_lsa(), or_pad(), or_put_bigint(), or_put_byte(), or_put_data(), or_put_date(), or_put_datetime(), or_put_datetimetz(), or_put_double(), or_put_float(), or_put_int(), or_put_monetary(), or_put_mvccid(), or_put_oid(), or_put_short(), or_put_time(), or_put_timestamptz(), or_put_utime(), or_put_varchar_internal(), or_seek(), and pr_get_size_and_write_string_to_buffer().
char* or_pack_bool_array (char * ptr, const bool * bools, int size)
Definition at line 3700 of file object_representation.c.
References ASSERT_ALIGN, INT_ALIGNMENT, NULL, OR_INT_SIZE, and OR_PUT_INT.
char* or_pack_btid (char * buf, const BTID * btid)
Definition at line 3171 of file object_representation.c.
References ASSERT_ALIGN, INT_ALIGNMENT, OR_BTID_ALIGNED_SIZE, OR_BTID_SIZE, OR_PUT_BTID, OR_PUT_NULL_BTID, and OR_PUT_SHORT.
Referenced by boot_check_db_consistency(), btree_add_index(), btree_delete_index(), btree_find_multi_uniques(), btree_find_unique(), btree_get_index_key_type(), btree_get_statistics(), btree_load_index(), btree_rv_save_keyval_for_undo(), btree_rv_save_keyval_for_undo_two_objects(), locator_check_fk_validity(), locator_remove_class_from_index(), sbtree_add_index(), sbtree_load_index(), sm_class_check_uniques(), xts_process_aggregate_type(), and xts_process_indx_info().
char* or_pack_db_value (char * buffer, DB_VALUE * var)
Definition at line 7041 of file object_representation.c.
References or_pack_value().
Referenced by csession_drop_session_variables(), csession_get_variable(), csession_set_session_variables(), db_pack_prepare_info(), method_send_value_to_server(), or_header_size(), qmgr_execute_query(), qmgr_prepare_and_execute_query(), ssession_get_session_variable(), and xts_process_db_value().
char* or_pack_domain (char * ptr, struct tp_domain * domain, int include_classoids, int is_null)
Definition at line 5157 of file object_representation.c.
References NO_ERROR, NULL, or_init(), or_put_domain(), or_buf::ptr, and rc.
Referenced by btree_add_index(), btree_load_index(), classobj_make_function_index_info_seq(), db_pack_prepare_info(), locator_check_fk_validity(), or_pack_listid(), or_pack_query_format(), sbtree_get_key_type(), xstats_get_statistics_from_server(), xts_process(), and xts_save_db_value_array().
char* or_pack_double (char * ptr, double number)
Definition at line 2774 of file object_representation.c.
References MAX_ALIGNMENT, OR_DOUBLE_SIZE, OR_PUT_DOUBLE(), and PTR_ALIGN.
Referenced by xts_process_xasl_node().
char* or_pack_ehid (char * buf, EHID * btid)
Definition at line 3130 of file object_representation.c.
References ASSERT_ALIGN, INT_ALIGNMENT, OR_EHID_SIZE, and OR_PUT_EHID.
char* or_pack_errcode (char * ptr, int error)
Definition at line 2682 of file object_representation.c.
References ASSERT_ALIGN, INT_ALIGNMENT, OR_INT_SIZE, and OR_PUT_INT.
Referenced by sacl_reload(), sfile_apply_tde_to_class_files(), shf_create(), shf_destroy(), shf_destroy_when_new(), shf_heap_reclaim_addresses(), slog_checkpoint(), sqst_update_all_statistics(), sqst_update_statistics(), stde_change_mk_on_server(), and stde_get_mk_info().
char* or_pack_float (char * ptr, float number)
Definition at line 2743 of file object_representation.c.
References ASSERT_ALIGN, FLOAT_ALIGNMENT, OR_FLOAT_SIZE, and OR_PUT_FLOAT().
Referenced by jsp_pack_float_argument(), sboot_register_client(), sysprm_pack_sysprm_value(), and xlogtb_get_pack_tran_table().
char* or_pack_hfid (const char * ptr, const HFID * hfid)
Definition at line 3057 of file object_representation.c.
References ASSERT_ALIGN, INT_ALIGNMENT, NULL, OR_HFID_SIZE, OR_PUT_HFID, and OR_PUT_NULL_HFID.
Referenced by btree_load_index(), heap_create(), heap_destroy_newly_created(), heap_get_class_num_objects_pages(), heap_has_instance(), heap_reclaim_addresses(), locator_assign_oid(), locator_check_fk_validity(), locator_fetch_all(), locator_pack_copy_area_descriptor(), locator_pack_oid_set(), locator_remove_class_from_index(), sboot_register_client(), shf_create(), xts_process_cls_spec_type(), xts_process_insert_proc(), xts_process_selupd_list(), and xts_save_hfid_array().
char* or_pack_int (char * ptr, int number)
Definition at line 2554 of file object_representation.c.
References ASSERT_ALIGN, INT_ALIGNMENT, NULL, OR_INT_SIZE, and OR_PUT_INT.
Referenced by boot_add_volume_extension(), boot_backup(), boot_change_ha_mode(), boot_check_db_consistency(), boot_compact_classes(), boot_notify_ha_log_applier_state(), boot_unregister_client(), btree_add_index(), btree_find_multi_uniques(), btree_key_insert_new_key(), btree_load_index(), chksum_insert_repl_log_and_demote_table_lock(), csession_create_prepared_statement(), csession_drop_session_variables(), csession_end_session(), csession_find_or_create_session(), csession_get_last_insert_id(), csession_get_prepared_statement(), csession_set_row_count(), csession_set_session_variables(), db_pack_prepare_info(), disk_get_free_numpages(), disk_get_fullname(), disk_get_remarks(), disk_get_total_numpages(), hb_cluster_send_heartbeat_internal(), heap_create(), heap_get_class_num_objects_pages(), heap_has_instance(), javasp_ping_server(), javasp_status_server(), jsp_pack_argument(), jsp_pack_bigint_argument(), jsp_pack_date_argument(), jsp_pack_datetime_argument(), jsp_pack_double_argument(), jsp_pack_float_argument(), jsp_pack_int_argument(), jsp_pack_monetary_argument(), jsp_pack_null_argument(), jsp_pack_object_argument(), jsp_pack_set_argument(), jsp_pack_short_argument(), jsp_pack_time_argument(), jsp_pack_timestamp_argument(), jsp_send_call_request(), jsp_send_destroy_request(), locator_assign_oid(), locator_assign_oid_batch(), locator_check_fk_validity(), locator_does_exist(), locator_fetch(), locator_fetch_all(), locator_fetch_all_reference_lockset(), locator_fetch_lockhint_classes(), locator_fetch_lockset(), locator_find_lockhint_class_oids(), locator_force(), locator_get_class(), locator_pack_copy_area_descriptor(), locator_pack_lockhint_classes(), locator_pack_lockhint_header(), locator_pack_lockset_classes(), locator_pack_lockset_header(), locator_pack_lockset_objects(), locator_pack_oid_set(), locator_redistribute_partition_data(), locator_repl_add_error_to_copyarea(), locator_repl_force(), locator_reserve_class_names(), locator_upgrade_instances_domain(), log_reset_isolation(), log_reset_wait_msecs(), log_set_interrupt(), log_set_suppress_repl_on_transaction(), logtb_get_pack_tran_table(), logwr_get_log_pages(), method_send_eof_to_server(), method_send_error_to_server(), method_send_value_to_server(), net_client_logwr_send_end_msg(), net_client_ping_server(), net_client_ping_server_with_handshake(), net_client_request_recv_stream(), net_client_request_with_callback(), netcl_spacedb(), netsr_spacedb(), or_header_size(), or_pack_method_sig(), or_pack_method_sig_list(), or_pack_query_format(), or_pack_recdes(), or_pack_spacedb(), qfile_get_list_file_page(), qmgr_drop_all_query_plans(), qmgr_end_query(), qmgr_execute_query(), qmgr_free_list_temp_file(), qmgr_prepare_and_execute_query(), qmgr_prepare_query(), qp_get_server_info(), repl_set_info(), sacl_dump(), sboot_add_volume_extension(), sboot_backup(), sboot_change_ha_mode(), sboot_check_db_consistency(), sboot_compact_db(), sboot_compact_start(), sboot_compact_stop(), sboot_find_last_permanent(), sboot_find_last_temp(), sboot_find_number_permanent_volumes(), sboot_find_number_temp_volumes(), sboot_get_locales_info(), sboot_get_timezone_checksum(), sboot_heap_compact(), sboot_notify_ha_log_applier_state(), sboot_notify_unregister_client(), sboot_register_client(), sbtree_add_index(), sbtree_class_test_unique(), sbtree_delete_index(), sbtree_find_multi_uniques(), sbtree_find_unique_internal(), sbtree_get_key_type(), sbtree_get_statistics(), sbtree_load_index(), schksum_insert_repl_log_and_demote_table_lock(), sct_check_rep_dir(), sdk_freepgs(), sdk_remarks(), sdk_totalpgs(), sdk_vlabel(), serial_get_current_value(), serial_get_next_value(), server_ping(), server_ping_with_handshake(), ses_posix_copy_file(), ses_posix_create_file(), ses_posix_delete_file(), ses_posix_rename_file(), JSON_SERIALIZER::SetSizePointers(), shf_get_class_num_objs_and_pages(), shf_has_instance(), sjsp_get_server_port(), sloaddb_destroy(), sloaddb_fetch_status(), sloaddb_init(), sloaddb_install_class(), sloaddb_load_batch(), sloaddb_update_stats(), slocator_assign_oid(), slocator_assign_oid_batch(), slocator_check_fk_validity(), slocator_delete_class_name(), slocator_demote_class_lock(), slocator_does_exist(), slocator_fetch(), slocator_fetch_all(), slocator_fetch_all_reference_lockset(), slocator_fetch_lockhint_classes(), slocator_fetch_lockset(), slocator_find_class_oid(), slocator_find_lockhint_class_oids(), slocator_force(), slocator_get_class(), slocator_notify_isolation_incons(), slocator_redistribute_partition_data(), slocator_remove_class_from_index(), slocator_rename_class_name(), slocator_repl_force(), slocator_reserve_classnames(), slocator_upgrade_instances_domain(), slock_dump(), slog_add_lob_locator(), slog_change_state_of_locator(), slog_checkpoint(), slog_drop_lob_locator(), slog_find_lob_locator(), slogin_user(), slogpb_dump_stat(), slogtb_does_active_user_exist(), slogtb_dump_trantable(), slogtb_get_mvcc_snapshot(), slogtb_get_pack_tran_table(), slogtb_reset_isolation(), slogtb_reset_wait_msecs(), slogtb_set_suppress_repl_on_transaction(), slogwr_get_log_pages(), smnt_server_start_stats(), smnt_server_stop_stats(), sprm_server_change_parameters(), sprm_server_dump_parameters(), sprm_server_get_force_parameters(), sprm_server_obtain_parameters(), sqfile_get_list_file_page(), sqmgr_drop_all_query_plans(), sqmgr_dump_query_cache(), sqmgr_dump_query_plans(), sqmgr_end_query(), sqmgr_execute_query(), sqmgr_prepare_and_execute_query(), sqmgr_prepare_query(), sqp_get_server_info(), sqst_server_get_statistics(), srepl_set_info(), sserial_decache(), sserial_get_current_value(), sserial_get_next_value(), ssession_create_prepared_statement(), ssession_delete_prepared_statement(), ssession_drop_session_variables(), ssession_end_session(), ssession_find_or_create_session(), ssession_get_last_insert_id(), ssession_get_prepared_statement(), ssession_get_row_count(), ssession_get_session_variable(), ssession_reset_cur_insert_id(), ssession_set_row_count(), ssession_set_session_variables(), stats_get_statistics_from_server(), stats_update_all_statistics(), stats_update_statistics(), stde_get_data_keys(), stde_get_mk_file_path(), stde_get_mk_info(), sthread_dump_cs_stat(), sthread_kill_or_interrupt_tran(), sthread_kill_tran_index(), stran_get_local_transaction_id(), stran_is_blocked(), stran_lock_rep_read(), stran_server_2pc_attach_global_tran(), stran_server_2pc_prepare(), stran_server_2pc_prepare_global_tran(), stran_server_2pc_recovery_prepared(), stran_server_2pc_start(), stran_server_abort(), stran_server_commit(), stran_server_end_topop(), stran_server_get_global_tran_info(), stran_server_has_updated(), stran_server_is_active_and_has_updated(), stran_server_partial_abort(), stran_server_savepoint(), stran_server_set_global_tran_info(), stran_server_start_topop(), stran_wait_server_active_trans(), svacuum(), svacuum_dump(), sysprm_pack_assign_values(), sysprm_pack_session_parameters(), sysprm_pack_sysprm_value(), tde_change_mk_on_server(), thread_kill_or_interrupt_tran(), thread_kill_tran_index(), tran_is_blocked(), tran_lock_rep_read(), tran_server_2pc_attach_global_tran(), tran_server_2pc_prepare_global_tran(), tran_server_2pc_recovery_prepared(), tran_server_commit(), tran_server_get_global_tran_info(), tran_server_set_global_tran_info(), xcallback_console_print(), xio_send_user_prompt_to_client(), xlog_send_log_pages_to_client(), xlogtb_get_pack_tran_table(), xs_send_action_to_client(), xs_send_method_call_info_to_client(), xts_map_filter_pred_to_stream(), xts_map_func_pred_to_stream(), xts_map_xasl_to_stream(), xts_pack_regu_variable_value(), xts_process(), xts_process_access_spec_type(), xts_process_aggregate_type(), xts_process_alsm_eval_term(), xts_process_analytic_eval_type(), xts_process_analytic_type(), xts_process_arith_type(), xts_process_attr_descr(), xts_process_buildlist_proc(), xts_process_buildvalue_proc(), xts_process_cache_attrinfo(), xts_process_cls_spec_type(), xts_process_comp_eval_term(), xts_process_connectby_proc(), xts_process_cte_proc(), xts_process_delete_proc(), xts_process_eval_term(), xts_process_fetch_proc(), xts_process_filter_pred_node(), xts_process_func_pred(), xts_process_function_type(), xts_process_indx_info(), xts_process_insert_proc(), xts_process_json_table_column_behavior(), xts_process_key_info(), xts_process_like_eval_term(), xts_process_list_spec_type(), xts_process_ls_merge_info(), xts_process_merge_proc(), xts_process_mergelist_proc(), xts_process_method_sig(), xts_process_method_sig_list(), xts_process_method_spec_type(), xts_process_outptr_list(), xts_process_pos_descr(), xts_process_pred(), xts_process_pred_expr(), xts_process_regu_value_list(), xts_process_regu_variable(), xts_process_regu_variable_list(), xts_process_rlike_eval_term(), xts_process_selupd_list(), xts_process_set_spec_type(), xts_process_showstmt_spec_type(), xts_process_sort_list(), xts_process_srlist_id(), xts_process_union_proc(), xts_process_update_proc(), xts_process_val_list(), xts_process_xasl_node(), xts_save_int_array(), xts_save_odku_info(), xts_save_update_assignment(), and xts_save_upddel_class_info().
char* or_pack_int64 (char * ptr, INT64 number)
Definition at line 2621 of file object_representation.c.
References MAX_ALIGNMENT, OR_INT64_SIZE, OR_PUT_INT64, and PTR_ALIGN.
Referenced by es_posix_read_file(), es_posix_write_file(), logwr_get_log_pages(), net_client_logwr_send_end_msg(), or_unpack_int(), ses_posix_get_file_size(), ses_posix_read_file(), ses_posix_write_file(), stde_get_mk_info(), and sysprm_pack_sysprm_value().
char* or_pack_listid (char * ptr, void * listid)
Definition at line 6625 of file object_representation.c.
References qfile_tuple_value_type_list::domp, qfile_list_id::first_vpid, i, qfile_list_id::last_offset, qfile_list_id::last_vpid, qfile_list_id::lasttpl_len, OR_INT_SIZE, or_pack_domain(), OR_PTR_SIZE, OR_PUT_INT, OR_PUT_PTR, qfile_list_id::page_cnt, vpid::pageid, qfile_list_id::query_id, qfile_list_id::tfile_vfid, qfile_list_id::tuple_cnt, qfile_tuple_value_type_list::type_cnt, qfile_list_id::type_list, and vpid::volid.
Referenced by sqmgr_execute_query(), sqmgr_prepare_and_execute_query(), xs_send_method_call_info_to_client(), and xts_process_list_id().
char* or_pack_lock (char * ptr, LOCK lock)
Definition at line 2713 of file object_representation.c.
References ASSERT_ALIGN, INT_ALIGNMENT, OR_INT_SIZE, and OR_PUT_INT.
Referenced by locator_demote_class_lock(), locator_does_exist(), locator_fetch(), locator_fetch_all(), locator_fetch_all_reference_lockset(), locator_find_class_oid(), locator_find_lockhint_class_oids(), locator_get_class(), locator_pack_lockhint_classes(), slocator_demote_class_lock(), and slocator_fetch_all().
char* or_pack_log_lsa (const char * ptr, const struct log_lsa * lsa)
Referenced by css_process_get_eof_request(), srepl_log_get_append_lsa(), stran_server_end_topop(), stran_server_partial_abort(), stran_server_savepoint(), and stran_server_start_topop().
char* or_pack_mem_value (char * ptr, DB_VALUE * value, int * packed_len_except_alignment)
Definition at line 6435 of file object_representation.c.
References pr_type::data_writeval(), DB_TYPE_NULL, DB_VALUE_DOMAIN_TYPE, DB_VALUE_TYPE, NO_ERROR, NULL, or_get_align64(), or_init(), or_pad(), or_put_domain(), pr_type_from_id(), or_buf::ptr, rc, tp_domain_resolve_value(), and tp_Null_domain.
Referenced by locator_repl_add_error_to_copyarea().
char* or_pack_method_sig_list (char * ptr, void * method_sig_list)
Definition at line 6938 of file object_representation.c.
References assert, i, method_sig_list::method_sig, method_sig_node::next, method_sig_list::num_methods, or_pack_int(), and or_pack_method_sig().
Referenced by xs_send_method_call_info_to_client().
char* or_pack_mvccid (char * ptr, const MVCCID mvccid)
Definition at line 7582 of file object_representation.c.
References ASSERT_ALIGN, INT_ALIGNMENT, OR_MVCCID_SIZE, and OR_PUT_MVCCID.
Referenced by btree_pack_mvccinfo(), btree_rv_save_keyval_for_undo_two_objects(), and heap_mvcc_log_delete().
char* or_pack_oid (char * ptr, const OID * oid)
Definition at line 2961 of file object_representation.c.
References ASSERT_ALIGN, INT_ALIGNMENT, NULL, OR_OID_SIZE, OR_PUT_NULL_OID, and OR_PUT_OID.
Referenced by boot_check_db_consistency(), boot_compact_classes(), boot_heap_compact(), btree_add_index(), btree_find_multi_uniques(), btree_find_unique(), btree_load_index(), btree_rv_save_keyval_for_undo_two_objects(), catalog_check_rep_dir(), chksum_insert_repl_log_and_demote_table_lock(), file_apply_tde_to_class_files(), heap_create(), heap_destroy_newly_created(), heap_has_instance(), locator_assign_oid(), locator_check_fk_validity(), locator_demote_class_lock(), locator_does_exist(), locator_fetch(), locator_fetch_all(), locator_fetch_all_reference_lockset(), locator_find_class_oid(), locator_find_lockhint_class_oids(), locator_get_class(), locator_pack_copy_area_descriptor(), locator_pack_lockhint_classes(), locator_pack_lockset_classes(), locator_pack_lockset_objects(), locator_pack_oid_set(), locator_redistribute_partition_data(), locator_remove_class_from_index(), locator_rename_class_name(), locator_reserve_class_names(), locator_upgrade_instances_domain(), or_pack_oid_array(), sboot_compact_db(), sboot_register_client(), sbtree_find_multi_uniques(), sbtree_find_unique_internal(), sct_check_rep_dir(), serial_decache(), serial_get_current_value(), serial_get_next_value(), slocator_assign_oid(), slocator_does_exist(), slocator_fetch_all(), slocator_find_class_oid(), slocator_get_class(), slocator_get_reserved_class_name_oid(), stats_get_statistics_from_server(), stats_update_statistics(), xts_map_xasl_to_stream(), xts_process_cls_spec_type(), xts_process_insert_proc(), xts_process_selupd_list(), and xts_save_oid_array().
char* or_pack_oid_array (char * ptr, int n, const OID * oids)
Definition at line 2985 of file object_representation.c.
References assert, ASSERT_ALIGN, i, INT_ALIGNMENT, NULL, and or_pack_oid().
char* or_pack_ptr (char * ptr, UINTPTR ptrval)
Definition at line 7491 of file object_representation.c.
References OR_PTR_SIZE, OR_PUT_PTR, PTR_ALIGN, and PTR_ALIGNMENT.
Referenced by qfile_get_list_file_page(), qmgr_end_query(), qmgr_execute_query(), sqmgr_execute_query(), sqmgr_prepare_and_execute_query(), and tran_server_commit().
char* or_pack_recdes (char * buf, RECDES * recdes)
Definition at line 3140 of file object_representation.c.
References recdes::data, recdes::length, or_pack_int(), or_pack_short(), or_pack_stream(), and recdes::type.
char* or_pack_set_header (char * buf, DB_TYPE stype, DB_TYPE etype, int bound_bits, int size)
char* or_pack_set_node (char * ptr, void * set_node)
char* or_pack_sha1 (char * ptr, const SHA1Hash * sha1)
Definition at line 7618 of file object_representation.c.
References assert, ASSERT_ALIGN, INT_ALIGNMENT, NULL, OR_PUT_SHA1, and OR_SHA1_SIZE.
Referenced by csession_create_prepared_statement(), and qmgr_prepare_query().
char* or_pack_short (char * ptr, short number)
Definition at line 2652 of file object_representation.c.
References ASSERT_ALIGN, INT_ALIGNMENT, OR_INT_SIZE, and OR_PUT_INT.
Referenced by jsp_pack_object_argument(), jsp_pack_short_argument(), and or_pack_recdes().
char* or_pack_spacedb (char * ptr, const SPACEDB_ALL * all, const SPACEDB_ONEVOL * vols, const SPACEDB_FILES * files)
Definition at line 7879 of file object_representation.c.
References i, NULL, spacedb_all::nvols, or_pack_int(), or_pack_string(), SPACEDB_ALL_COUNT, SPACEDB_FILE_COUNT, and SPACEDB_TOTAL_ALL.
Referenced by netsr_spacedb().
char* or_pack_stream (char * ptr, const char * stream, size_t len)
Definition at line 3374 of file object_representation.c.
References ASSERT_ALIGN, INT_ALIGNMENT, NULL, OR_INT_SIZE, and OR_PUT_INT.
Referenced by csession_find_or_create_session(), or_pack_recdes(), or_pack_string_with_null_padding(), ssession_find_or_create_session(), ssession_get_prepared_statement(), and stde_get_data_keys().
char* or_pack_string (char * ptr, const char * string)
Definition at line 3314 of file object_representation.c.
References ASSERT_ALIGN, INT_ALIGNMENT, NULL, OR_INT_SIZE, OR_PUT_INT, and strlen.
Referenced by db_pack_prepare_info(), jsp_pack_numeric_argument(), jsp_pack_string_argument(), locator_repl_add_error_to_copyarea(), or_header_size(), or_pack_method_sig(), or_pack_spacedb(), server_ping_with_handshake(), sysprm_pack_sysprm_value(), vacuum_rv_es_nop(), and xlogtb_get_pack_tran_table().
char* or_pack_string_with_length (char * ptr, const char * string, int length)
Definition at line 3414 of file object_representation.c.
References ASSERT_ALIGN, INT_ALIGNMENT, NULL, OR_INT_SIZE, and OR_PUT_INT.
Referenced by btree_load_index(), csession_get_prepared_statement(), db_pack_prepare_info(), jsp_send_call_request(), locator_check_fk_validity(), net_client_ping_server_with_handshake(), net_client_request_with_callback(), or_pack_query_format(), sboot_get_locales_info(), sboot_get_timezone_checksum(), sboot_register_client(), sdk_remarks(), sdk_vlabel(), server_ping_with_handshake(), stde_get_mk_file_path(), xcallback_console_print(), xio_send_user_prompt_to_client(), xlogtb_get_pack_tran_table(), and xts_save_string().
char* or_pack_string_with_null_padding (char * ptr, const char * stream, size_t len)
Definition at line 3356 of file object_representation.c.
References OR_INT_SIZE, and or_pack_stream().
char* or_pack_value (char * buf, DB_VALUE * value)
Definition at line 6420 of file object_representation.c.
References MAX_ALIGNMENT, or_init(), or_put_value(), or_buf::ptr, and PTR_ALIGN.
Referenced by btree_find_multi_uniques(), btree_find_unique(), or_pack_db_value(), cubpacking::packer::pack_db_value(), sqp_get_server_info(), sserial_get_current_value(), sserial_get_next_value(), and ssession_get_last_insert_id().
int or_packed_bool_array_length (const bool * bools, int size)
Definition at line 3785 of file object_representation.c.
References NULL, and OR_INT_SIZE.
int or_packed_domain_size (struct tp_domain * domain, int include_classoids)
Definition at line 3933 of file object_representation.c.
References tp_domain::built_in_index, tp_domain::collation_id, DB_MAX_NUMERIC_PRECISION, DB_MAX_VARBIT_PRECISION, DB_MAX_VARCHAR_PRECISION, DB_MAX_VARNCHAR_PRECISION, DB_TYPE_BIT, DB_TYPE_CHAR, DB_TYPE_ENUMERATION, DB_TYPE_JSON, DB_TYPE_NCHAR, DB_TYPE_NUMERIC, DB_TYPE_OBJECT, DB_TYPE_VARBIT, DB_TYPE_VARCHAR, DB_TYPE_VARNCHAR, DOM_GET_ENUMERATION, tp_domain::json_validator, LANG_COLL_ISO_BINARY, tp_domain::next, NULL, OR_DOMAIN_PRECISION_MAX, OR_DOMAIN_SCALE_MAX, OR_INT_SIZE, OR_OID_SIZE, or_packed_enumeration_size(), or_packed_json_validator_length(), tp_domain::precision, tp_domain::scale, tp_domain::setdomain, TP_DOMAIN_TYPE, and TP_FLOATING_PRECISION_VALUE.
Referenced by btree_add_index(), btree_load_index(), classobj_make_function_index_info_seq(), db_pack_prepare_info(), locator_check_fk_validity(), or_listid_length(), or_packed_query_format_size(), or_packed_set_length(), or_packed_value_size(), or_put_set(), pt_check_enum_data_type(), sbtree_get_key_type(), xstats_get_statistics_from_server(), xts_save_db_value_array(), xts_sizeof(), xts_sizeof_aggregate_type(), xts_sizeof_analytic_type(), xts_sizeof_arith_type(), xts_sizeof_pos_descr(), and xts_sizeof_regu_variable().
int or_packed_enumeration_size (const DB_ENUMERATION * e)
Definition at line 7077 of file object_representation.c.
References db_enumeration::count, DB_GET_ENUM_ELEM_CODESET, DB_GET_ENUM_ELEM_STRING, DB_GET_ENUM_ELEM_STRING_SIZE, db_make_varchar(), db_enumeration::elements, pr_type::get_disk_size_of_value(), LANG_GET_BINARY_COLLATION, NULL, OR_SET_HEADER_SIZE, pr_clear_value(), TP_FLOATING_PRECISION_VALUE, and tp_String.
Referenced by enumeration_size(), and or_packed_domain_size().
int or_packed_put_varbit (OR_BUF * buf, const char * string, int bitlen)
Definition at line 1161 of file object_representation.c.
References INT_ALIGNMENT, and or_put_varbit_internal().
Referenced by mr_data_writemem_varbit(), and mr_writeval_varbit_internal().
int or_packed_put_varchar (OR_BUF * buf, char * string, int charlen)
Definition at line 823 of file object_representation.c.
References INT_ALIGNMENT, and or_put_varchar_internal().
Referenced by mr_data_writemem_string(), mr_data_writemem_varnchar(), and mr_writeval_varnchar_internal().
int or_packed_recdesc_length (int length)
Definition at line 764 of file object_representation.c.
References OR_INT_SIZE, and or_packed_stream_length().
void or_packed_set_info (DB_TYPE set_type, struct tp_domain * domain, int include_domain, int * bound_bits, int * offset_table, int * element_tags, int * element_size)
Definition at line 5248 of file object_representation.c.
References tp_domain::next, NULL, tp_domain::setdomain, and tp_domain_disk_size().
Referenced by or_packed_set_length(), and or_put_set().
int or_packed_set_length (setobj * set, int include_domain)
Definition at line 5476 of file object_representation.c.
References error(), i, NULL, OR_BOUND_BIT_BYTES, OR_INT_SIZE, or_packed_domain_size(), or_packed_set_info(), or_packed_value_size(), OR_SET_HEADER_SIZE, OR_VAR_TABLE_SIZE, set_size(), setobj_domain(), setobj_get_element_ptr(), setobj_size(), and setobj_type().
Referenced by mr_data_lengthmem_set(), mr_data_lengthval_set(), and mr_data_writeval_set().
int or_packed_spacedb_size (const SPACEDB_ALL * all, const SPACEDB_ONEVOL * vols, const SPACEDB_FILES * files)
Definition at line 7838 of file object_representation.c.
References i, NULL, spacedb_all::nvols, OR_INT_SIZE, or_packed_string_length(), SPACEDB_ALL_COUNT, SPACEDB_FILE_COUNT, and SPACEDB_TOTAL_ALL.
Referenced by netsr_spacedb().
int or_packed_stream_length (size_t len)
Definition at line 3670 of file object_representation.c.
References OR_INT_SIZE.
Referenced by csession_find_or_create_session(), or_packed_recdesc_length(), ssession_find_or_create_session(), ssession_get_prepared_statement(), and stde_get_data_keys().
int or_packed_string_length (const char * string, int * strlen)
Definition at line 3591 of file object_representation.c.
References NULL, OR_INT_SIZE, and strlen.
Referenced by btree_load_index(), csession_get_prepared_statement(), db_pack_prepare_info(), JSON_SERIALIZER_LENGTH::GetStringPackedSize(), jsp_get_value_size(), jsp_send_call_request(), locator_check_fk_validity(), locator_repl_add_error_to_copyarea(), mr_data_lengthmem_elo(), mr_data_writemem_elo(), net_client_ping_server_with_handshake(), or_header_size(), or_method_sig_list_length(), or_packed_query_format_size(), or_packed_spacedb_size(), sboot_get_locales_info(), sboot_get_timezone_checksum(), sboot_register_client(), sdk_remarks(), sdk_vlabel(), server_ping_with_handshake(), stde_get_mk_file_path(), sysprm_packed_sysprm_value_length(), vacuum_rv_es_nop(), xcallback_console_print(), xio_send_user_prompt_to_client(), xlogtb_get_pack_tran_table(), and xts_save_string().
int or_packed_value_size (const DB_VALUE * value, int collapse_null, int include_domain, int include_domain_classoids)
Definition at line 6107 of file object_representation.c.
References DB_TYPE_NULL, DB_VALUE_DOMAIN_TYPE, DB_VALUE_TYPE, pr_type::get_disk_size_of_value(), NULL, or_packed_domain_size(), pr_type_from_id(), tp_domain_resolve_value(), and tp_Null_domain.
Referenced by attribute_size(), attribute_to_disk(), classobj_partition_info_size(), cubpacking::packer::get_packed_db_value_size(), or_db_value_size(), or_packed_set_length(), cubpacking::packer::pack_db_value(), partition_info_size(), partition_info_to_disk(), and cubpacking::unpacker::unpack_db_value().
int or_packed_varbit_length (int bitlen)
Definition at line 1111 of file object_representation.c.
References INT_ALIGNMENT, and or_varbit_length_internal().
Referenced by mr_data_lengthmem_varbit(), and mr_lengthval_varbit_internal().
int or_packed_varchar_length (int charlen)
Definition at line 746 of file object_representation.c.
References INT_ALIGNMENT, and or_varchar_length_internal().
Referenced by mr_data_lengthmem_string(), mr_data_lengthmem_varnchar(), mr_lengthval_string_internal(), mr_lengthval_varnchar_internal(), and pr_get_size_and_write_string_to_buffer().
int or_pad (OR_BUF * buf, int length)
Definition at line 2347 of file object_representation.c.
References or_buf::endptr, NO_ERROR, or_overflow(), and or_buf::ptr.
Referenced by btree_sort_get_next(), catcls_put_or_value_into_buffer(), heap_attrinfo_transform_to_disk_internal(), or_pack_mem_value(), or_put_align32(), or_put_set(), or_put_string_aligned(), or_put_value(), and put_attributes().
int or_put_align32 (OR_BUF * buf)
Definition at line 662 of file object_representation.c.
References if(), NO_ERROR, or_pad(), or_buf::ptr, and rc.
Referenced by btree_write_record(), or_put_varbit_internal(), or_put_varchar_internal(), pr_write_compressed_string_to_buffer(), and pr_write_uncompressed_string_to_buffer().
int or_put_bigint (OR_BUF * buf, DB_BIGINT num)
Definition at line 1583 of file object_representation.c.
References ASSERT_ALIGN, or_buf::endptr, INT_ALIGNMENT, NO_ERROR, OR_BIGINT_SIZE, or_overflow(), OR_PUT_BIGINT, and or_buf::ptr.
Referenced by catcls_put_or_value_into_buffer(), desc_obj_to_disk(), heap_attrinfo_transform_to_disk_internal(), JSON_SERIALIZER::Int64(), mr_data_writemem_bigint(), mr_data_writemem_elo(), mr_data_writeval_bigint(), or_mvcc_set_delid(), or_mvcc_set_insid(), tf_mem_to_disk(), and JSON_SERIALIZER::Uint64().
int or_put_byte (OR_BUF * buf, int num)
Definition at line 1438 of file object_representation.c.
References or_buf::endptr, NO_ERROR, OR_BYTE_SIZE, or_overflow(), OR_PUT_BYTE, and or_buf::ptr.
Referenced by btree_sort_get_next(), mr_writeval_bit_internal(), mr_writeval_char_internal(), mr_writeval_nchar_internal(), or_put_offset_internal(), or_put_varbit_internal(), or_put_varchar_internal(), pr_write_compressed_string_to_buffer(), and pr_write_uncompressed_string_to_buffer().
int or_put_data (OR_BUF * buf, const char * data, int length)
Definition at line 2161 of file object_representation.c.
References or_buf::endptr, NO_ERROR, or_overflow(), and or_buf::ptr.
Referenced by catcls_put_or_value_into_buffer(), heap_attrinfo_transform_to_disk_internal(), mr_data_writemem_bit(), mr_data_writemem_char(), mr_data_writemem_nchar(), mr_data_writemem_numeric(), mr_data_writeval_numeric(), mr_index_writeval_bigint(), mr_index_writeval_date(), mr_index_writeval_datetime(), mr_index_writeval_datetimetz(), mr_index_writeval_double(), mr_index_writeval_enumeration(), mr_index_writeval_float(), mr_index_writeval_int(), mr_index_writeval_midxkey(), mr_index_writeval_money(), mr_index_writeval_oid(), mr_index_writeval_short(), mr_index_writeval_time(), mr_index_writeval_timestamptz(), mr_index_writeval_utime(), mr_writeval_bit_internal(), mr_writeval_char_internal(), mr_writeval_nchar_internal(), or_put_string_aligned(), or_put_string_aligned_with_length(), or_put_varbit_internal(), or_put_varchar_internal(), pr_midxkey_add_elements(), pr_write_compressed_string_to_buffer(), pr_write_uncompressed_string_to_buffer(), and put_attributes().
int or_put_date (OR_BUF * buf, DB_DATE * date)
Definition at line 1874 of file object_representation.c.
References ASSERT_ALIGN, or_buf::endptr, INT_ALIGNMENT, NO_ERROR, OR_DATE_SIZE, or_overflow(), OR_PUT_DATE, and or_buf::ptr.
Referenced by mr_data_writemem_date(), and mr_data_writeval_date().
int or_put_datetime (OR_BUF * buf, DB_DATETIME * datetimeval)
Definition at line 1920 of file object_representation.c.
References ASSERT_ALIGN, or_buf::endptr, INT_ALIGNMENT, NO_ERROR, OR_DATETIME_SIZE, or_overflow(), OR_PUT_DATETIME, and or_buf::ptr.
Referenced by mr_data_writemem_datetime(), and mr_data_writeval_datetime().
int or_put_datetimetz (OR_BUF * buf, DB_DATETIMETZ * datetimetz)
Definition at line 1966 of file object_representation.c.
References ASSERT_ALIGN, or_buf::endptr, INT_ALIGNMENT, NO_ERROR, OR_DATETIMETZ_SIZE, or_overflow(), OR_PUT_DATETIMETZ, and or_buf::ptr.
Referenced by mr_data_writemem_datetimetz(), and mr_data_writeval_datetimetz().
int or_put_domain (OR_BUF * buf, struct tp_domain * domain, int include_classoids, int is_null)
Definition at line 4064 of file object_representation.c.
References assert, tp_domain::built_in_index, tp_domain::class_oid, tp_domain::codeset, tp_domain::collation_flag, tp_domain::collation_id, DB_DEFAULT_SCALE, DB_MAX_NUMERIC_PRECISION, DB_MAX_VARBIT_PRECISION, DB_MAX_VARCHAR_PRECISION, DB_MAX_VARNCHAR_PRECISION, DB_TYPE_BIT, DB_TYPE_CHAR, DB_TYPE_ENUMERATION, DB_TYPE_JSON, DB_TYPE_MIDXKEY, DB_TYPE_MULTISET, DB_TYPE_NCHAR, DB_TYPE_NULL, DB_TYPE_NUMERIC, DB_TYPE_OBJECT, DB_TYPE_OID, DB_TYPE_SEQUENCE, DB_TYPE_SET, DB_TYPE_TABLE, DB_TYPE_VARBIT, DB_TYPE_VARCHAR, DB_TYPE_VARNCHAR, DOM_GET_ENUM_ELEMENTS, DOM_GET_ENUMERATION, tp_domain::is_desc, tp_domain::json_validator, LANG_COLL_ISO_BINARY, tp_domain::next, NO_ERROR, NULL, OR_DOMAIN_BUILTIN_FLAG, OR_DOMAIN_CLASS_OID_FLAG, OR_DOMAIN_CODSET_SHIFT, OR_DOMAIN_COLL_ENFORCE_FLAG, OR_DOMAIN_COLL_LEAVE_FLAG, OR_DOMAIN_DESC_FLAG, OR_DOMAIN_ENUM_COLL_FLAG, OR_DOMAIN_ENUMERATION_FLAG, OR_DOMAIN_NEXT_FLAG, OR_DOMAIN_NULL_FLAG, OR_DOMAIN_PRECISION_MAX, OR_DOMAIN_PRECISION_SHIFT, OR_DOMAIN_SCALE_MAX, OR_DOMAIN_SCALE_SHIFT, OR_DOMAIN_SCHEMA_FLAG, OR_DOMAIN_SET_DOMAIN_FLAG, OR_DOMAIN_TYPE_MASK, or_put_enumeration(), or_put_int(), or_put_json_validator(), or_put_oid(), tp_domain::precision, rc, tp_domain::scale, tp_domain::setdomain, TP_DOMAIN_COLL_ENFORCE, TP_DOMAIN_COLL_LEAVE, tp_domain_size(), TP_DOMAIN_TYPE, and TP_FLOATING_PRECISION_VALUE.
Referenced by btree_pack_root_header(), or_pack_domain(), or_pack_mem_value(), or_put_set(), or_put_value(), and put_object_set().
void OR_PUT_DOUBLE (char * ptr, double val) inline
Definition at line 118 of file object_representation.h.
References htond().
Referenced by jsp_pack_double_argument(), jsp_pack_monetary_argument(), or_pack_double(), and or_put_double().
int or_put_double (OR_BUF * buf, double num)
Definition at line 1681 of file object_representation.c.
References ASSERT_ALIGN, or_buf::endptr, INT_ALIGNMENT, NO_ERROR, OR_DOUBLE_SIZE, or_overflow(), OR_PUT_DOUBLE(), and or_buf::ptr.
Referenced by JSON_SERIALIZER::Double(), mr_data_writemem_double(), and mr_data_writeval_double().
int or_put_enumeration (OR_BUF * buf, const DB_ENUMERATION * e)
Definition at line 7110 of file object_representation.c.
References db_enumeration::collation_id, db_enumeration::count, pr_type::data_writeval(), DB_GET_ENUM_ELEM_CODESET, DB_GET_ENUM_ELEM_STRING, DB_GET_ENUM_ELEM_STRING_SIZE, db_make_varchar(), DB_TYPE_SEQUENCE, db_enumeration::elements, NO_ERROR, NULL, or_put_set_header(), pr_clear_value(), rc, TP_FLOATING_PRECISION_VALUE, and tp_String.
Referenced by or_put_domain(), and put_enumeration().
void OR_PUT_FLOAT (char * ptr, float val) inline
Definition at line 110 of file object_representation.h.
References htonf().
Referenced by or_pack_float(), and or_put_float().
int or_put_float (OR_BUF * buf, float num)
Definition at line 1632 of file object_representation.c.
References ASSERT_ALIGN, or_buf::endptr, FLOAT_ALIGNMENT, NO_ERROR, OR_FLOAT_SIZE, or_overflow(), OR_PUT_FLOAT(), and or_buf::ptr.
Referenced by mr_data_writemem_float(), and mr_data_writeval_float().
int or_put_int (OR_BUF * buf, int num)
Definition at line 1534 of file object_representation.c.
References ASSERT_ALIGN, or_buf::endptr, INT_ALIGNMENT, NO_ERROR, OR_INT_SIZE, or_overflow(), OR_PUT_INT, and or_buf::ptr.
Referenced by attribute_to_disk(), JSON_SERIALIZER::Bool(), btree_write_fixed_portion_of_non_leaf_record_to_orbuf(), btree_write_record(), catcls_put_or_value_into_buffer(), desc_obj_to_disk(), domain_to_disk(), heap_attrinfo_transform_to_disk_internal(), JSON_SERIALIZER::Int(), JSON_SERIALIZER::Int64(), metharg_to_disk(), method_to_disk(), methsig_to_disk(), mr_data_writemem_elo(), mr_data_writemem_int(), mr_data_writemem_resultset(), mr_data_writeval_int(), mr_data_writeval_resultset(), mr_writeval_bit_internal(), mr_writeval_char_internal(), mr_writeval_nchar_internal(), or_mvcc_set_chn(), or_mvcc_set_flag(), or_mvcc_set_repid_and_flags(), or_put_domain(), or_put_offset_internal(), or_put_set(), or_put_set_header(), or_put_string_aligned(), or_put_string_aligned_with_length(), or_put_sub_domain(), or_replace_chn(), or_replace_rep_id(), or_set_rep_id(), JSON_SERIALIZER::PackType(), partition_info_to_disk(), put_class_attributes(), put_object_set(), put_substructure_set(), repattribute_to_disk(), representation_to_disk(), resolution_to_disk(), root_to_disk(), JSON_SERIALIZER::SaveSizePointers(), tf_class_to_disk(), tf_mem_to_disk(), JSON_SERIALIZER::Uint(), and JSON_SERIALIZER::Uint64().
int or_put_monetary (OR_BUF * buf, DB_MONETARY * monetary)
Definition at line 2012 of file object_representation.c.
References ARG_FILE_LINE, ASSERT_ALIGN, DB_CURRENCY_AUSTRALIAN_DOLLAR, DB_CURRENCY_BRASILIAN_REAL, DB_CURRENCY_BRITISH_POUND, DB_CURRENCY_BULGARIAN_LEV, DB_CURRENCY_CAMBODIAN_RIEL, DB_CURRENCY_CANADIAN_DOLLAR, DB_CURRENCY_CHINESE_RENMINBI, DB_CURRENCY_CROATIAN_KUNA, DB_CURRENCY_CZECH_KORUNA, DB_CURRENCY_DANISH_KRONE, DB_CURRENCY_DOLLAR, DB_CURRENCY_EURO, DB_CURRENCY_INDIAN_RUPEE, DB_CURRENCY_NORWEGIAN_KRONE, DB_CURRENCY_POLISH_ZLOTY, DB_CURRENCY_ROMANIAN_LEU, DB_CURRENCY_RUSSIAN_RUBLE, DB_CURRENCY_SERBIAN_DINAR, DB_CURRENCY_SWEDISH_KRONA, DB_CURRENCY_SWISS_FRANC, DB_CURRENCY_TL, DB_CURRENCY_VIETNAMESE_DONG, DB_CURRENCY_WON, DB_CURRENCY_YEN, or_buf::endptr, ER_INVALID_CURRENCY_TYPE, er_set(), ER_WARNING_SEVERITY, error(), INT_ALIGNMENT, NO_ERROR, OR_MONETARY_SIZE, or_overflow(), OR_PUT_MONETARY, or_buf::ptr, and db_monetary::type.
Referenced by mr_data_writemem_money(), and mr_data_writeval_money().
int or_put_mvccid (OR_BUF * buf, MVCCID mvccid)
Definition at line 7525 of file object_representation.c.
References ASSERT_ALIGN, or_buf::endptr, INT_ALIGNMENT, NO_ERROR, OR_MVCCID_SIZE, or_overflow(), OR_PUT_MVCCID, and or_buf::ptr.
Referenced by btree_leaf_change_first_object(), btree_or_put_mvccinfo(), btree_sort_get_next(), and btree_write_record().
int or_put_offset (OR_BUF * buf, int num)
Definition at line 1252 of file object_representation.c.
References BIG_VAR_OFFSET_SIZE, and or_put_offset_internal().
Referenced by attribute_to_disk(), domain_to_disk(), metharg_to_disk(), methfile_to_disk(), method_to_disk(), methsig_to_disk(), partition_info_to_disk(), put_class_varinfo(), query_spec_to_disk(), repattribute_to_disk(), representation_to_disk(), resolution_to_disk(), and root_to_disk().
int or_put_offset_internal (OR_BUF * buf, int num, int offset_size)
Definition at line 1258 of file object_representation.c.
References assert, BIG_VAR_OFFSET_SIZE, OR_BYTE_SIZE, or_put_byte(), or_put_int(), or_put_short(), and OR_SHORT_SIZE.
Referenced by heap_attrinfo_transform_to_disk_internal(), or_put_offset(), and put_varinfo().
int or_put_oid (OR_BUF * buf, const OID * oid)
Definition at line 2101 of file object_representation.c.
References ARG_FILE_LINE, ASSERT_ALIGN, or_buf::endptr, ER_ERROR_SEVERITY, ER_GENERIC_ERROR, er_set(), INT_ALIGNMENT, NO_ERROR, NULL, OID_ISTEMP, or_abort(), OR_OID_SIZE, or_overflow(), OR_PUT_NULL_OID, OR_PUT_OID, and or_buf::ptr.
Referenced by btree_leaf_change_first_object(), btree_or_put_object(), btree_sort_get_next(), btree_write_record(), mr_data_writemem_object(), mr_data_writemem_oid(), mr_data_writeval_object(), mr_data_writeval_oid(), or_put_domain(), put_class_attributes(), and put_substructure_set().
void or_put_set (OR_BUF * buf, setobj * set, int include_domain)
Definition at line 5565 of file object_representation.c.
References BIG_VAR_OFFSET_SIZE, CAST_BUFLEN, DB_TYPE_NULL, DB_VALUE_TYPE, error(), i, NULL, or_advance(), OR_BOUND_BIT_BYTES, OR_INT_SIZE, or_packed_domain_size(), or_packed_set_info(), or_pad(), or_put_domain(), OR_PUT_INT, or_put_int(), OR_PUT_OFFSET, or_put_set_header(), or_put_value(), OR_VAR_TABLE_SIZE, or_buf::ptr, set_size(), setobj_domain(), setobj_get_element_ptr(), setobj_size(), setobj_type(), and TP_DOMAIN_TYPE.
Referenced by mr_data_writemem_set(), and mr_data_writeval_set().
int or_put_set_header (OR_BUF * buf, DB_TYPE set_type, int size, int domain, int bound_bits, int offset_table, int element_tags, int common_sub_header)
Definition at line 5337 of file object_representation.c.
References NO_ERROR, or_put_int(), OR_SET_BOUND_BIT, OR_SET_COMMON_SUB_BIT, OR_SET_DOMAIN_BIT, OR_SET_TAG_BIT, OR_SET_VARIABLE_BIT, and rc.
Referenced by or_put_enumeration(), or_put_set(), put_object_set(), and put_substructure_set().
int or_put_short (OR_BUF * buf, int num)
Definition at line 1484 of file object_representation.c.
References ASSERT_ALIGN, or_buf::endptr, NO_ERROR, or_overflow(), OR_PUT_SHORT, OR_SHORT_SIZE, or_buf::ptr, and SHORT_ALIGNMENT.
Referenced by btree_write_fixed_portion_of_non_leaf_record_to_orbuf(), btree_write_record(), mr_data_writemem_enumeration(), mr_data_writemem_short(), mr_data_writeval_enumeration(), mr_data_writeval_short(), and or_put_offset_internal().
int or_put_string_aligned (OR_BUF * buf, char * string)
Definition at line 2214 of file object_representation.c.
References db_binary::data, db_binary::length, NO_ERROR, NULL, OR_BINARY_MAX_LENGTH, OR_BINARY_PAD_SHIFT, OR_INT_SIZE, or_pad(), or_put_data(), or_put_int(), rc, and strlen.
Referenced by mr_data_writemem_elo().
int or_put_string_aligned_with_length (OR_BUF * buf, const char * str)
Definition at line 8009 of file object_representation.c.
References NO_ERROR, NULL, or_align(), OR_INT_SIZE, or_put_data(), or_put_int(), rc, and strlen.
Referenced by JSON_SERIALIZER::PackString().
int or_put_sub_domain (OR_BUF * buf)
Definition at line 5215 of file object_representation.c.
References DB_TYPE_SUB, OR_DOMAIN_TYPE_MASK, and or_put_int().
Referenced by put_substructure_set().
int or_put_time (OR_BUF * buf, DB_TIME * timeval)
Definition at line 1736 of file object_representation.c.
References ASSERT_ALIGN, or_buf::endptr, INT_ALIGNMENT, NO_ERROR, or_overflow(), OR_PUT_TIME, OR_TIME_SIZE, and or_buf::ptr.
Referenced by mr_data_writemem_time(), and mr_data_writeval_time().
int or_put_timestamptz (OR_BUF * buf, DB_TIMESTAMPTZ * ts_tz)
Definition at line 1828 of file object_representation.c.
References ASSERT_ALIGN, or_buf::endptr, INT_ALIGNMENT, NO_ERROR, or_overflow(), OR_PUT_TIMESTAMPTZ, OR_TIMESTAMPTZ_SIZE, and or_buf::ptr.
Referenced by mr_data_writemem_timestamptz(), and mr_data_writeval_timestamptz().
int or_put_utime (OR_BUF * buf, DB_UTIME * timeval)
Definition at line 1782 of file object_representation.c.
References ASSERT_ALIGN, or_buf::endptr, INT_ALIGNMENT, NO_ERROR, or_overflow(), OR_PUT_UTIME, OR_UTIME_SIZE, and or_buf::ptr.
Referenced by mr_data_writemem_utime(), and mr_data_writeval_utime().
int or_put_value (OR_BUF * buf, DB_VALUE * value, int collapse_null, int include_domain, int include_domain_classoids)
Definition at line 6187 of file object_representation.c.
References pr_type::data_writeval(), DB_TYPE_NULL, DB_VALUE_DOMAIN_TYPE, DB_VALUE_TYPE, ER_FAILED, NO_ERROR, NULL, or_pad(), or_put_domain(), pr_type_from_id(), or_buf::ptr, rc, tp_domain_resolve_value(), and tp_Null_domain.
Referenced by attribute_to_disk(), or_pack_value(), or_put_set(), and partition_info_to_disk().
int or_put_varbit (OR_BUF * buf, const char * string, int bitlen)
Definition at line 1174 of file object_representation.c.
References CHAR_ALIGNMENT, and or_put_varbit_internal().
Referenced by mr_writeval_varbit_internal().
int or_put_varchar (OR_BUF * buf, char * string, int charlen)
Definition at line 810 of file object_representation.c.
References CHAR_ALIGNMENT, and or_put_varchar_internal().
Referenced by mr_writeval_varnchar_internal().
int or_rep_id (RECDES * record)
Definition at line 329 of file object_representation.c.
References ARG_FILE_LINE, assert, recdes::data, ER_ERROR_SEVERITY, er_set(), ER_TF_BUFFER_UNDERFLOW, recdes::length, NULL, NULL_REPRID, OR_GET_MVCC_REPID, and OR_HEADER_SIZE.
Referenced by catalog_insert(), catalog_update(), heap_attrinfo_delete_lob(), heap_attrinfo_read_dbvalues(), heap_attrinfo_read_dbvalues_without_oid(), heap_attrinfo_set_uninitialized(), heap_attrvalue_get_key(), heap_classrepr_get_from_record(), heap_get_record_info(), heap_midxkey_get_value(), heap_midxkey_key_generate(), or_class_get_partition_info(), or_get_classrep(), or_get_classrep_noindex(), or_get_current_representation(), and partition_find_partition_for_record().
int or_replace_chn (RECDES * record, int chn)
Definition at line 422 of file object_representation.c.
References recdes::area_size, or_buf::buffer, recdes::data, error(), OR_BUF_INIT, OR_CHN_OFFSET, or_put_int(), and or_buf::ptr.
Referenced by locator_repl_prepare_force().
int or_seek (OR_BUF * buf, int psn)
Definition at line 2389 of file object_representation.c.
References or_buf::buffer, or_buf::endptr, NO_ERROR, or_overflow(), and or_buf::ptr.
Referenced by btree_find_oid_from_leaf(), btree_key_find_first_visible_row(), btree_or_get_object(), btree_record_get_last_object(), btree_record_get_num_oids(), btree_record_get_num_visible_oids(), and catcls_convert_attr_id_to_name().
int or_set_element_offset (char * setptr, int element)
int or_set_node_length (void * set_node_ptr)
int or_set_rep_id (RECDES * record, int repid)
Definition at line 362 of file object_representation.c.
References recdes::area_size, ARG_FILE_LINE, or_buf::buffer, recdes::data, ER_ERROR_SEVERITY, ER_FAILED, er_set(), ER_TF_BUFFER_UNDERFLOW, recdes::length, NO_ERROR, OR_BUF_INIT, OR_GET_MVCC_REPID_AND_FLAG, OR_HEADER_SIZE, OR_MVCC_REPID_MASK, or_put_int(), OR_REP_OFFSET, and or_buf::ptr.
Referenced by partition_find_partition_for_record(), and qexec_execute_duplicate_key_update().
int or_skip_set_header (OR_BUF * buf)
Definition at line 5422 of file object_representation.c.
References cubregex::count(), NO_ERROR, or_advance(), OR_BOUND_BIT_BYTES, or_get_int(), or_get_set_header(), OR_SUB_HEADER_SIZE, OR_VAR_TABLE_SIZE, and rc.
Referenced by catcls_get_object_set(), catcls_get_subset(), get_object_set(), get_substructure_set(), install_substructure_set(), and or_get_enumeration().
int or_skip_varbit (OR_BUF * buf, int align)
Definition at line 1410 of file object_representation.c.
References NO_ERROR, or_get_varbit_length(), or_skip_varbit_remainder(), and rc.
Referenced by mr_readval_varbit_internal().
int or_skip_varbit_remainder (OR_BUF * buf, int bitlen, int align)
Definition at line 1391 of file object_representation.c.
References BITS_TO_BYTES, INT_ALIGNMENT, NO_ERROR, or_advance(), or_get_align32(), and rc.
Referenced by mr_readval_varbit_internal(), and or_skip_varbit().
int or_skip_varchar (OR_BUF * buf, int align)
Definition at line 1091 of file object_representation.c.
References NO_ERROR, or_get_varchar_length(), or_skip_varchar_remainder(), and rc.
Referenced by mr_readval_string_internal(), and mr_readval_varnchar_internal().
int or_skip_varchar_remainder (OR_BUF * buf, int charlen, int align)
Definition at line 1064 of file object_representation.c.
References INT_ALIGNMENT, NO_ERROR, or_advance(), or_get_align32(), and rc.
Referenced by mr_readval_string_internal(), mr_readval_varnchar_internal(), and or_skip_varchar().
int or_underflow (OR_BUF * buf)
Definition at line 601 of file object_representation.c.
References ARG_FILE_LINE, or_buf::env, ER_ERROR_SEVERITY, er_set(), ER_TF_BUFFER_UNDERFLOW, and or_buf::error_abort.
Referenced by db_json_or_buf_underflow(), or_get_bigint(), or_get_byte(), or_get_data(), or_get_date(), or_get_datetime(), or_get_datetimetz(), or_get_double(), or_get_float(), or_get_int(), or_get_monetary(), or_get_mvccid(), or_get_oid(), or_get_short(), or_get_string_size_byte(), or_get_time(), or_get_timestamptz(), or_get_utime(), or_get_var_table_internal(), or_mvcc_get_chn(), or_mvcc_get_delid(), or_mvcc_get_insid(), or_mvcc_get_prev_version_lsa(), and or_mvcc_get_repid_and_flags().
char* or_unpack_bool_array (char * ptr, bool ** bools)
Definition at line 3740 of file object_representation.c.
References ASSERT_ALIGN, db_private_alloc, INT_ALIGNMENT, NULL, OR_GET_INT, and OR_INT_SIZE.
char* or_unpack_btid (char * buf, BTID * btid)
Definition at line 3199 of file object_representation.c.
References ASSERT_ALIGN, INT_ALIGNMENT, OR_BTID_ALIGNED_SIZE, and OR_GET_BTID.
Referenced by btree_add_index(), btree_load_index(), btree_rv_keyval_dump(), btree_rv_read_keybuf_nocopy(), btree_rv_read_keybuf_two_objects(), sboot_check_db_consistency(), sbtree_add_index(), sbtree_delete_index(), sbtree_find_multi_uniques(), sbtree_find_unique_internal(), sbtree_get_key_type(), sbtree_get_statistics(), sbtree_load_index(), slocator_check_fk_validity(), slocator_remove_class_from_index(), stx_build_aggregate_type(), stx_build_indx_info(), and xbtree_class_test_unique().
char* or_unpack_db_value (char * buffer, DB_VALUE * val)
Definition at line 7065 of file object_representation.c.
References or_unpack_value().
Referenced by csession_get_variable(), db_unpack_prepare_info(), method_clear_scan_buffer(), or_header_size(), sbtree_find_multi_uniques(), ssession_drop_session_variables(), ssession_get_session_variable(), ssession_set_session_variables(), stx_build_db_value(), xqmgr_execute_query(), and xqmgr_prepare_and_execute_query().
char* or_unpack_domain (char * ptr, struct tp_domain ** domain_ptr, int * is_null)
Definition at line 5182 of file object_representation.c.
References NULL, or_get_domain(), or_init(), and or_buf::ptr.
Referenced by btree_get_index_key_type(), btree_read_key_type(), btree_rv_record_modify_internal(), catcls_get_or_value_from_indexes(), classobj_make_function_index_info(), db_unpack_prepare_info(), or_get_current_default_value(), or_get_default_value(), or_unpack_query_format(), or_unpack_unbound_listid(), sbtree_add_index(), sbtree_load_index(), slocator_check_fk_validity(), stats_client_unpack_statistics(), stx_build(), stx_build_aggregate_type(), stx_build_analytic_type(), stx_build_arith_type(), stx_build_list_id(), stx_build_pos_descr(), stx_build_regu_variable(), and stx_restore_db_value_array_extra().
char* or_unpack_double (char * ptr, double * number)
Definition at line 2789 of file object_representation.c.
References ASSERT_ALIGN, INT_ALIGNMENT, MAX_ALIGNMENT, OR_DATE_SIZE, OR_DOUBLE_SIZE, OR_GET_DATE, OR_GET_DOUBLE, OR_GET_MONETARY, OR_GET_TIME, OR_GET_UTIME, OR_MONETARY_SIZE, OR_PUT_DATE, OR_PUT_MONETARY, OR_PUT_TIME, OR_PUT_UTIME, OR_TIME_SIZE, OR_UTIME_SIZE, and PTR_ALIGN.
Referenced by stx_build_xasl_node().
char* or_unpack_ehid (char * buf, EHID * btid)
Definition at line 3155 of file object_representation.c.
References ASSERT_ALIGN, INT_ALIGNMENT, OR_EHID_SIZE, and OR_GET_EHID.
char* or_unpack_errcode (char * ptr, int * error)
Definition at line 2697 of file object_representation.c.
References ASSERT_ALIGN, INT_ALIGNMENT, OR_GET_INT, and OR_INT_SIZE.
Referenced by acl_reload(), file_apply_tde_to_class_files(), heap_create(), heap_destroy_newly_created(), heap_reclaim_addresses(), log_checkpoint(), stats_update_all_statistics(), stats_update_statistics(), tde_change_mk_on_server(), and tde_get_mk_info().
char* or_unpack_float (char * ptr, float * number)
Definition at line 2758 of file object_representation.c.
References ASSERT_ALIGN, FLOAT_ALIGNMENT, OR_FLOAT_SIZE, and OR_GET_FLOAT.
Referenced by boot_register_client(), jsp_unpack_float_value(), logtb_get_trans_info(), and sysprm_unpack_sysprm_value().
char* or_unpack_hfid (char * ptr, HFID * hfid)
Definition at line 3084 of file object_representation.c.
References ASSERT_ALIGN, INT_ALIGNMENT, OR_GET_HFID, and OR_HFID_SIZE.
Referenced by boot_register_client(), heap_create(), locator_unpack_copy_area_descriptor(), locator_unpack_oid_set_to_new(), shf_create(), shf_destroy(), shf_destroy_when_new(), shf_get_class_num_objs_and_pages(), shf_has_instance(), shf_heap_reclaim_addresses(), slocator_assign_oid(), slocator_check_fk_validity(), slocator_fetch_all(), slocator_remove_class_from_index(), stx_build_cls_spec_type(), stx_build_insert_proc(), stx_build_selupd_list(), and stx_restore_hfid_array().
char* or_unpack_hfid_array (char * ptr, int n, HFID ** hfids)
Definition at line 3100 of file object_representation.c.
References ASSERT_ALIGN, db_private_alloc, i, INT_ALIGNMENT, NULL, OR_GET_HFID, and OR_HFID_SIZE.
Referenced by sbtree_load_index().
char* or_unpack_int (char * ptr, int * number)
Definition at line 2574 of file object_representation.c.
References ASSERT_ALIGN, INT_ALIGNMENT, NULL, OR_GET_INT, OR_INT_SIZE, or_pack_int64(), and or_unpack_int64().
Referenced by boot_add_volume_extension(), boot_backup(), boot_change_ha_mode(), boot_check_db_consistency(), boot_compact_classes(), boot_find_last_permanent(), boot_find_last_temp(), boot_find_number_permanent_volumes(), boot_find_number_temp_volumes(), boot_get_server_locales(), boot_get_server_timezone_checksum(), boot_heap_compact(), boot_notify_ha_log_applier_state(), boot_register_client(), boot_unregister_client(), btree_add_index(), btree_class_test_unique(), btree_delete_index(), btree_find_multi_uniques(), btree_find_unique(), btree_get_index_key_type(), btree_get_statistics(), btree_load_index(), btree_rv_record_modify_internal(), catalog_check_rep_dir(), chksum_insert_repl_log_and_demote_table_lock(), clogin_user(), compact_db_start(), compact_db_stop(), csession_create_prepared_statement(), csession_delete_prepared_statement(), csession_drop_session_variables(), csession_find_or_create_session(), csession_get_last_insert_id(), csession_get_prepared_statement(), csession_get_row_count(), csession_get_variable(), csession_reset_cur_insert_id(), csession_set_row_count(), csession_set_session_variables(), cvacuum(), db_local_transaction_id(), db_unpack_prepare_info(), disk_get_free_numpages(), disk_get_fullname(), disk_get_remarks(), disk_get_total_numpages(), es_posix_copy_file(), es_posix_create_file(), es_posix_delete_file(), es_posix_rename_file(), file_apply_tde_to_class_files(), fileio_request_user_response(), hb_cluster_receive_heartbeat(), heap_get_class_num_objects_pages(), heap_has_instance(), javasp_status_server(), jsp_get_server_port(), jsp_receive_response(), jsp_unpack_int_value(), jsp_unpack_object_value(), jsp_unpack_resultset(), jsp_unpack_set_value(), jsp_unpack_value(), la_make_repl_item(), loaddb_destroy(), loaddb_fetch_status(), loaddb_init(), loaddb_install_class(), loaddb_load_batch(), loaddb_update_stats(), locator_allocate_and_unpack_lockhint(), locator_allocate_and_unpack_lockset(), locator_assign_oid(), locator_assign_oid_batch(), locator_check_fk_validity(), locator_delete_class_name(), locator_demote_class_lock(), locator_does_exist(), locator_fetch(), locator_fetch_all(), locator_fetch_all_reference_lockset(), locator_fetch_lockhint_classes(), locator_fetch_lockset(), locator_find_class_oid(), locator_find_lockhint_class_oids(), locator_force(), locator_get_class(), locator_notify_isolation_incons(), locator_redistribute_partition_data(), locator_remove_class_from_index(), locator_rename_class_name(), locator_repl_force(), locator_reserve_class_names(), locator_unpack_copy_area_descriptor(), locator_unpack_lockhint_classes(), locator_unpack_lockhint_header(), locator_unpack_lockset_classes(), locator_unpack_lockset_header(), locator_unpack_lockset_objects(), locator_unpack_oid_set_to_exist(), locator_unpack_oid_set_to_new(), locator_upgrade_instances_domain(), log_does_active_user_exist(), log_get_mvcc_snapshot(), log_repl_schema_dump(), log_reset_isolation(), log_reset_wait_msecs(), log_set_suppress_repl_on_transaction(), logtb_get_pack_tran_table(), logtb_get_trans_info(), method_clear_scan_buffer(), net_client_check_log_header(), net_client_ping_server(), net_client_ping_server_with_handshake(), net_client_receive_action(), net_client_recv_copyarea(), net_client_request2(), net_client_request2_no_malloc(), net_client_request_2recv_copyarea(), net_client_request_3_data(), net_client_request_3_data_recv_copyarea(), net_client_request_3recv_copyarea(), net_client_request_recv_copyarea(), net_client_request_recv_stream(), net_client_request_with_callback(), net_client_request_with_logwr_context(), netcl_spacedb(), netsr_spacedb(), or_header_size(), or_unpack_int_array(), or_unpack_method_sig(), or_unpack_method_sig_list(), or_unpack_query_format(), or_unpack_recdes(), or_unpack_spacedb(), perfmon_server_start_stats(), qfile_get_list_file_page(), qmgr_drop_all_query_plans(), qmgr_end_query(), qmgr_execute_query(), qmgr_prepare_and_execute_query(), qmgr_prepare_query(), qp_get_server_info(), repl_set_info(), sacl_dump(), sboot_add_volume_extension(), sboot_backup(), sboot_change_ha_mode(), sboot_check_db_consistency(), sboot_compact_db(), sboot_notify_ha_log_applier_state(), sboot_notify_unregister_client(), sbtree_add_index(), sbtree_find_multi_uniques(), sbtree_load_index(), schksum_insert_repl_log_and_demote_table_lock(), sdk_freepgs(), sdk_remarks(), sdk_totalpgs(), sdk_vlabel(), serial_decache(), serial_get_current_value(), serial_get_next_value(), server_ping(), server_ping_with_handshake(), shf_create(), shf_get_class_num_objs_and_pages(), shf_has_instance(), slocator_assign_oid(), slocator_check_fk_validity(), slocator_does_exist(), slocator_fetch(), slocator_fetch_all(), slocator_fetch_all_reference_lockset(), slocator_fetch_lockhint_classes(), slocator_fetch_lockset(), slocator_find_lockhint_class_oids(), slocator_force(), slocator_get_class(), slocator_redistribute_partition_data(), slocator_repl_force(), slocator_reserve_classnames(), slocator_upgrade_instances_domain(), slock_dump(), slog_add_lob_locator(), slog_change_state_of_locator(), slogpb_dump_stat(), slogtb_dump_trantable(), slogtb_get_pack_tran_table(), slogtb_reset_isolation(), slogtb_reset_wait_msecs(), slogtb_set_interrupt(), slogtb_set_suppress_repl_on_transaction(), slogwr_get_log_pages(), sprm_server_dump_parameters(), sqfile_get_list_file_page(), sqmgr_dump_query_cache(), sqmgr_dump_query_plans(), sqmgr_end_query(), sqmgr_execute_query(), sqmgr_prepare_and_execute_query(), sqmgr_prepare_query(), sqp_get_server_info(), sqst_server_get_statistics(), sqst_update_all_statistics(), sqst_update_statistics(), srepl_set_info(), sserial_get_current_value(), sserial_get_next_value(), ssession_create_prepared_statement(), ssession_drop_session_variables(), ssession_end_session(), ssession_find_or_create_session(), ssession_get_last_insert_id(), ssession_get_prepared_statement(), ssession_set_row_count(), ssession_set_session_variables(), stats_get_statistics_from_server(), stde_change_mk_on_server(), sthread_dump_cs_stat(), sthread_kill_or_interrupt_tran(), sthread_kill_tran_index(), stran_is_blocked(), stran_lock_rep_read(), stran_server_2pc_attach_global_tran(), stran_server_2pc_prepare_global_tran(), stran_server_2pc_recovery_prepared(), stran_server_commit(), stran_server_end_topop(), stran_server_get_global_tran_info(), stran_server_set_global_tran_info(), stx_build(), stx_build_access_spec_type(), stx_build_aggregate_type(), stx_build_alsm_eval_term(), stx_build_analytic_eval_type(), stx_build_analytic_type(), stx_build_arith_type(), stx_build_attr_descr(), stx_build_buildlist_proc(), stx_build_buildvalue_proc(), stx_build_cache_attrinfo(), stx_build_cls_spec_type(), stx_build_comp_eval_term(), stx_build_connectby_proc(), stx_build_cte_proc(), stx_build_delete_proc(), stx_build_eval_term(), stx_build_fetch_proc(), stx_build_filter_pred_node(), stx_build_func_pred(), stx_build_function_type(), stx_build_indx_info(), stx_build_insert_proc(), stx_build_key_info(), stx_build_like_eval_term(), stx_build_list_spec_type(), stx_build_ls_merge_info(), stx_build_merge_proc(), stx_build_mergelist_proc(), stx_build_method_sig(), stx_build_method_sig_list(), stx_build_method_spec_type(), stx_build_outptr_list(), stx_build_pos_descr(), stx_build_pred(), stx_build_pred_expr(), stx_build_regu_value_list(), stx_build_regu_variable(), stx_build_regu_variable_list(), stx_build_rlike_eval_term(), stx_build_selupd_list(), stx_build_set_spec_type(), stx_build_showstmt_spec_type(), stx_build_sort_list(), stx_build_srlist_id(), stx_build_string(), stx_build_union_proc(), stx_build_update_assignment(), stx_build_update_class_info(), stx_build_update_proc(), stx_build_val_list(), stx_build_xasl_node(), stx_init_regu_variable(), stx_map_stream_to_filter_pred(), stx_map_stream_to_func_pred(), stx_map_stream_to_xasl(), stx_map_stream_to_xasl_node_header(), stx_restore(), stx_restore_access_spec_type(), stx_restore_int_array(), stx_restore_odku_info(), stx_restore_regu_variable_list(), stx_restore_regu_varlist_list(), stx_restore_string(), stx_unpack(), stx_unpack_regu_variable_value(), svacuum_dump(), sysprm_change_server_parameters(), sysprm_get_force_server_parameters(), sysprm_obtain_server_parameters(), sysprm_unpack_assign_values(), sysprm_unpack_session_parameters(), sysprm_unpack_sysprm_value(), tde_get_mk_file_path(), tde_get_mk_info(), thread_kill_or_interrupt_tran(), thread_kill_tran_index(), tran_is_blocked(), tran_lock_rep_read(), tran_server_2pc_attach_global_tran(), tran_server_2pc_prepare(), tran_server_2pc_prepare_global_tran(), tran_server_2pc_recovery_prepared(), tran_server_2pc_start(), tran_server_abort(), tran_server_commit(), tran_server_get_global_tran_info(), tran_server_has_updated(), tran_server_is_active_and_has_updated(), tran_server_partial_abort(), tran_server_savepoint(), tran_server_set_global_tran_info(), tran_wait_server_active_trans(), ws_set_repl_error_into_error_link(), xlog_get_page_request_with_reply(), xqmgr_prepare_query(), and xts_map_func_pred_to_stream().
char* or_unpack_int64 (char * ptr, INT64 * number)
Definition at line 2636 of file object_representation.c.
References MAX_ALIGNMENT, OR_GET_INT64, OR_INT64_SIZE, and PTR_ALIGN.
Referenced by es_posix_get_file_size(), es_posix_read_file(), es_posix_write_file(), net_client_request(), or_unpack_int(), ses_posix_read_file(), ses_posix_write_file(), slogwr_get_log_pages(), sysprm_unpack_sysprm_value(), tde_get_mk_info(), and xlog_get_page_request_with_reply().
char* or_unpack_int_array (char * ptr, int n, int ** number_array)
Definition at line 2927 of file object_representation.c.
References ASSERT_ALIGN, db_private_alloc, i, INT_ALIGNMENT, NULL, and or_unpack_int().
Referenced by sboot_compact_db(), sbtree_load_index(), slocator_check_fk_validity(), and sthread_kill_or_interrupt_tran().
char* or_unpack_listid (char * ptr, void * listid_ptr)
Definition at line 6711 of file object_representation.c.
References qfile_list_id::first_vpid, qfile_list_id::last_offset, qfile_list_id::last_vpid, qfile_list_id::lasttpl_len, OR_GET_INT, OR_GET_PTR, OR_INT_SIZE, OR_PTR_SIZE, qfile_list_id::page_cnt, vpid::pageid, QFILE_CLEAR_LIST_ID, qfile_list_id::query_id, qfile_list_id::tfile_vfid, qfile_list_id::tuple_cnt, qfile_tuple_value_type_list::type_cnt, qfile_list_id::type_list, and vpid::volid.
Referenced by or_unpack_unbound_listid(), and stx_build_list_id().
char* or_unpack_lock (char * ptr, LOCK * lock)
Definition at line 2728 of file object_representation.c.
References ASSERT_ALIGN, INT_ALIGNMENT, OR_GET_INT, and OR_INT_SIZE.
Referenced by locator_demote_class_lock(), locator_fetch_all(), locator_unpack_lockhint_classes(), slocator_demote_class_lock(), slocator_does_exist(), slocator_fetch(), slocator_fetch_all(), slocator_fetch_all_reference_lockset(), slocator_find_class_oid(), slocator_find_lockhint_class_oids(), and slocator_get_class().
char* or_unpack_log_lsa (char * ptr, struct log_lsa * lsa)
Definition at line 3247 of file object_representation.c.
References ASSERT_ALIGN, INT_ALIGNMENT, OR_GET_LOG_LSA, and OR_LOG_LSA_ALIGNED_SIZE.
Referenced by hb_resource_receive_get_eof(), repl_log_get_append_lsa(), tran_server_2pc_prepare_global_tran(), tran_server_partial_abort(), and tran_server_savepoint().
char* or_unpack_longint (char * ptr, int * number)
char* or_unpack_mem_value (char * buf, DB_VALUE * value)
Definition at line 6543 of file object_representation.c.
References pr_type::data_readval(), db_make_null(), db_value_put_null(), NO_ERROR, NULL, or_advance(), or_get_align64(), or_get_domain(), or_init(), or_buf::ptr, rc, tp_init_value_domain(), and tp_domain::type.
Referenced by la_get_item_pk_value(), locator_repl_get_key_value(), log_repl_data_dump(), and ws_set_repl_error_into_error_link().
char* or_unpack_method_sig_list (char * ptr, void ** method_sig_list_ptr)
Definition at line 6970 of file object_representation.c.
References assert, db_private_alloc, i, method_sig_list::method_sig, method_sig_node::next, NULL, method_sig_list::num_methods, or_unpack_int(), and or_unpack_method_sig().
Referenced by net_client_request_with_callback().
char* or_unpack_mvccid (char * ptr, MVCCID * mvccid)
Definition at line 7598 of file object_representation.c.
References assert, ASSERT_ALIGN, INT_ALIGNMENT, NULL, OR_GET_MVCCID, and OR_MVCCID_SIZE.
Referenced by btree_rv_keyval_dump(), btree_rv_read_keybuf_two_objects(), and btree_unpack_mvccinfo().
char* or_unpack_oid (char * ptr, OID * oid)
Definition at line 3011 of file object_representation.c.
References ASSERT_ALIGN, INT_ALIGNMENT, OR_GET_OID, and OR_OID_SIZE.
Referenced by boot_compact_classes(), boot_register_client(), btree_find_multi_uniques(), btree_find_unique(), btree_is_fence_key(), btree_rv_keyval_dump(), btree_rv_read_keybuf_two_objects(), catalog_check_rep_dir(), locator_assign_oid(), locator_does_exist(), locator_fetch_all(), locator_find_class_oid(), locator_get_class(), locator_get_reserved_class_name_oid(), locator_unpack_copy_area_descriptor(), locator_unpack_lockhint_classes(), locator_unpack_lockset_classes(), locator_unpack_lockset_objects(), locator_unpack_oid_set_to_exist(), locator_unpack_oid_set_to_new(), sboot_check_db_consistency(), sboot_compact_db(), sboot_heap_compact(), sbtree_add_index(), sbtree_find_multi_uniques(), sbtree_find_unique_internal(), sbtree_load_index(), schksum_insert_repl_log_and_demote_table_lock(), sct_check_rep_dir(), sfile_apply_tde_to_class_files(), shf_create(), shf_destroy_when_new(), shf_has_instance(), slocator_assign_oid(), slocator_check_fk_validity(), slocator_demote_class_lock(), slocator_does_exist(), slocator_fetch(), slocator_fetch_all(), slocator_fetch_all_reference_lockset(), slocator_find_class_oid(), slocator_find_lockhint_class_oids(), slocator_get_class(), slocator_redistribute_partition_data(), slocator_remove_class_from_index(), slocator_rename_class_name(), slocator_reserve_classnames(), slocator_upgrade_instances_domain(), sqst_server_get_statistics(), sqst_update_statistics(), sserial_decache(), sserial_get_current_value(), sserial_get_next_value(), stx_build_cls_spec_type(), stx_build_insert_proc(), stx_build_selupd_list(), stx_restore_OID_array(), and xqmgr_prepare_query().
char* or_unpack_oid_array (char * ptr, int n, OID ** oids)
Definition at line 3027 of file object_representation.c.
References ASSERT_ALIGN, db_private_alloc, i, INT_ALIGNMENT, NULL, OR_GET_OID, and OR_OID_SIZE.
Referenced by sboot_compact_db(), and sbtree_load_index().
char* or_unpack_ptr (char * ptr, UINTPTR * ptrval)
Definition at line 7506 of file object_representation.c.
References OR_GET_PTR, OR_PTR_SIZE, PTR_ALIGN, and PTR_ALIGNMENT.
Referenced by qmgr_execute_query(), qmgr_prepare_and_execute_query(), sqfile_get_list_file_page(), sqmgr_end_query(), sqmgr_execute_query(), and stran_server_commit().
char* or_unpack_recdes (char * buf, RECDES ** recdes)
Definition at line 6669 of file object_representation.c.
References recdes::area_size, ARG_FILE_LINE, recdes::data, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), recdes::length, NULL, or_unpack_int(), or_unpack_short(), or_unpack_stream(), and recdes::type.
char* or_unpack_set (char * ptr, setobj ** set, struct tp_domain * domain)
Definition at line 3263 of file object_representation.c.
References or_get_set(), or_init(), and or_buf::ptr.
Referenced by mr_data_cmpdisk_sequence(), mr_data_cmpdisk_set(), mr_data_cmpdisk_vobj(), and or_unpack_setref().
char* or_unpack_set_header (char * buf, DB_TYPE * stype, DB_TYPE * etype, int * bound_bits, int * size)
char* or_unpack_set_node (char * ptr, void * set_node_ptr)
char* or_unpack_setref (char * ptr, DB_SET ** ref)
Definition at line 3280 of file object_representation.c.
References NULL, or_unpack_set(), and setobj_get_reference().
Referenced by or_get_all_representation(), or_get_constraint_comment(), or_get_current_representation(), and or_get_old_representation().
char* or_unpack_sha1 (char * ptr, SHA1Hash * sha1)
Definition at line 7641 of file object_representation.c.
References assert, ASSERT_ALIGN, INT_ALIGNMENT, NULL, OR_GET_SHA1, and OR_SHA1_SIZE.
Referenced by sqmgr_prepare_query(), and ssession_create_prepared_statement().
char* or_unpack_short (char * ptr, short * number)
Definition at line 2667 of file object_representation.c.
References ASSERT_ALIGN, INT_ALIGNMENT, OR_GET_INT, and OR_INT_SIZE.
Referenced by jsp_unpack_object_value(), jsp_unpack_short_value(), and or_unpack_recdes().
char* or_unpack_spacedb (char * ptr, SPACEDB_ALL * all, SPACEDB_ONEVOL ** vols, SPACEDB_FILES * files)
Definition at line 7930 of file object_representation.c.
References ARG_FILE_LINE, assert, DB_MAX_PATH_LENGTH, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), i, spacedb_all::npage_free, spacedb_files::npage_ftab, spacedb_files::npage_reserved, spacedb_all::npage_used, spacedb_files::npage_user, NULL, spacedb_all::nvols, or_unpack_int(), or_unpack_string_nocopy(), SPACEDB_ALL_COUNT, SPACEDB_FILE_COUNT, and SPACEDB_TOTAL_ALL.
Referenced by netcl_spacedb().
char* or_unpack_stream (char * ptr, char * stream, size_t len)
Definition at line 3493 of file object_representation.c.
References ASSERT_ALIGN, assert_release, INT_ALIGNMENT, OR_GET_INT, and OR_INT_SIZE.
Referenced by csession_find_or_create_session(), file_apply_tde_to_class_files(), or_unpack_recdes(), and ssession_find_or_create_session().
char* or_unpack_string (char * ptr, char ** string)
Definition at line 3455 of file object_representation.c.
References ASSERT_ALIGN, db_private_alloc, INT_ALIGNMENT, NULL, OR_GET_INT, and OR_INT_SIZE.
Referenced by boot_register_client(), jsp_unpack_string_value(), la_make_repl_item(), logtb_get_trans_info(), or_header_size(), or_unpack_method_sig(), slocator_check_fk_validity(), ssession_get_prepared_statement(), and vacuum_process_log_block().
char* or_unpack_string_alloc (char * ptr, char ** string)
Definition at line 3520 of file object_representation.c.
References ARG_FILE_LINE, ASSERT_ALIGN, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), INT_ALIGNMENT, NULL, OR_GET_INT, and OR_INT_SIZE.
Referenced by csession_get_prepared_statement(), db_unpack_prepare_info(), or_unpack_query_format(), ssession_create_prepared_statement(), ssession_find_or_create_session(), and ws_set_repl_error_into_error_link().
char* or_unpack_string_nocopy (char * ptr, char ** string)
Definition at line 3559 of file object_representation.c.
References ASSERT_ALIGN, INT_ALIGNMENT, NULL, OR_GET_INT, and OR_INT_SIZE.
Referenced by boot_get_server_locales(), boot_get_server_timezone_checksum(), disk_get_fullname(), disk_get_remarks(), fileio_request_user_response(), javasp_status_server(), jsp_unpack_date_value(), jsp_unpack_datetime_value(), jsp_unpack_numeric_value(), jsp_unpack_time_value(), jsp_unpack_timestamp_value(), log_repl_data_dump(), log_repl_schema_dump(), net_client_ping_server_with_handshake(), net_client_request_with_callback(), or_unpack_spacedb(), sboot_add_volume_extension(), sboot_backup(), sbtree_load_index(), schksum_insert_repl_log_and_demote_table_lock(), server_ping_with_handshake(), ses_posix_copy_file(), ses_posix_delete_file(), ses_posix_get_file_size(), ses_posix_read_file(), ses_posix_rename_file(), ses_posix_write_file(), slocator_assign_oid(), slocator_delete_class_name(), slocator_find_class_oid(), slocator_find_lockhint_class_oids(), slocator_get_reserved_class_name_oid(), slocator_rename_class_name(), slocator_reserve_classnames(), slog_add_lob_locator(), slog_change_state_of_locator(), slog_drop_lob_locator(), slog_find_lob_locator(), slogin_user(), slogtb_does_active_user_exist(), sqmgr_prepare_query(), srepl_set_info(), ssession_delete_prepared_statement(), sthread_kill_tran_index(), stran_server_partial_abort(), stran_server_savepoint(), sysprm_unpack_sysprm_value(), and tde_get_mk_file_path().
char* or_unpack_unbound_listid (char * ptr, void ** listid_ptr)
Definition at line 6760 of file object_representation.c.
References ARG_FILE_LINE, cubregex::count(), qfile_tuple_value_type_list::domp, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, i, NULL, or_unpack_domain(), or_unpack_listid(), qfile_tuple_value_type_list::type_cnt, and qfile_list_id::type_list.
Referenced by net_client_request_with_callback(), qmgr_execute_query(), and qmgr_prepare_and_execute_query().
char* or_unpack_value (const char * buf, DB_VALUE * value)
Definition at line 6531 of file object_representation.c.
References CONST_CAST, MAX_ALIGNMENT, NULL, or_get_value(), or_init(), or_buf::ptr, and PTR_ALIGN.
Referenced by csession_get_last_insert_id(), or_unpack_db_value(), qp_get_server_info(), sbtree_find_unique_internal(), serial_get_current_value(), serial_get_next_value(), and cubpacking::unpacker::unpack_db_value().
char* or_unpack_var_table (char * ptr, int nvars, OR_VARINFO * vars)
Definition at line 2436 of file object_representation.c.
References BIG_VAR_OFFSET_SIZE, and or_unpack_var_table_internal().
int or_varbit_length (int bitlen)
Definition at line 1122 of file object_representation.c.
References CHAR_ALIGNMENT, and or_varbit_length_internal().
Referenced by mr_index_lengthmem_varbit(), and mr_lengthval_varbit_internal().
int or_varchar_length (int charlen)
Definition at line 758 of file object_representation.c.
References CHAR_ALIGNMENT, and or_varchar_length_internal().
Referenced by mr_index_lengthmem_string(), mr_lengthval_string_internal(), and mr_lengthval_varnchar_internal().
int valcnv_convert_value_to_string (DB_VALUE * value)
Definition at line 4901 of file db_macro.c.
References valcnv_buffer::bytes, CAST_STRLEN, DB_IS_NULL, db_make_varchar(), DB_MAX_STRING_LENGTH, ER_FAILED, free_and_init, LANG_SYS_CODESET, LANG_SYS_COLLATION, valcnv_buffer::length, NO_ERROR, NULL, pr_clear_value(), REINTERPRET_CAST, pr_type::setval(), tp_String, and valcnv_convert_db_value_to_string().
Referenced by catcls_get_or_value_from_attribute(), and qexec_execute_build_columns().
Variable Documentation
int or_Type_sizes[]
Definition at line 225 of file object_representation.c.