CUBRID Engine: src/parser/parse_tree_cl.c File Reference
parse_tree_cl.c File Reference
#include "config.h"
#include <ctype.h>
#include <stdio.h>
#include <stdarg.h>
#include <stddef.h>
#include <float.h>
#include <assert.h>
#include <math.h>
#include "authenticate.h"
#include "db_value_printer.hpp"
#include "porting.h"
#include "parser.h"
#include "parser_message.h"
#include "misc_string.h"
#include "csql_grammar_scan.h"
#include "mem_block.hpp"
#include "memory_alloc.h"
#include "language_support.h"
#include "object_primitive.h"
#include "object_print.h"
#include "optimizer.h"
#include "system_parameter.h"
#include "show_meta.h"
#include "virtual_object.h"
#include "set_object.h"
#include "dbi.h"
#include "string_buffer.hpp"
#include "dbtype.h"
#include "parser_allocator.hpp"
#include "tde.h"
#include <malloc.h>
Classes
struct pt_lambda_arg
struct pt_find_id_info
struct pt_walk_arg
struct pt_string_block
struct pt_copy_cte_info
struct pt_tree_copy_info
Macros
#define SAFENUM(node, field) ((node) ? (node)->field : -1)
#define PT_MEMB_BUF_SIZE 100
#define PT_MEMB_PRINTABLE_BUF_SIZE 512
#define PT_MEMB_ERR_BUF_SIZE 256
#define MAX_STRING_SEGMENT_LENGTH 254
#define DONT_PRT_LONG_STRING_LENGTH 256
#define PT_APPLY_WALK(parser, ptr, arg)
#define INITIAL_EXTENT 512
#define DELTA 512
#define PT_QUERY_STRING_USER_TEXT
#define pt_init_func_null_function ((PARSER_INIT_NODE_FUNC)(NULL))
#define ASSIGN_LINKS_EXTENT 10
Typedefs
typedef struct pt_lambda_arg PT_LAMBDA_ARG
typedef struct pt_find_id_info PT_FIND_ID_INFO
typedef struct pt_walk_arg PT_WALK_ARG
typedef struct pt_string_block PT_STRING_BLOCK
typedef struct pt_copy_cte_info PT_CTE_COPY_INFO
typedef struct pt_tree_copy_info PT_TREE_COPY_INFO
typedef PT_NODE *(* PARSER_INIT_NODE_FUNC) (PT_NODE *)
typedef PARSER_VARCHAR *(* PARSER_PRINT_NODE_FUNC) (PARSER_CONTEXT *parser, PT_NODE *node)
typedef PT_NODE *(* PARSER_APPLY_NODE_FUNC) (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
Functions
static void strcat_with_realloc (PT_STRING_BLOCK *sb, const char *tail)
static PT_NODE * pt_lambda_check_reduce_eq (PARSER_CONTEXT *parser, PT_NODE *tree_or_name, void *void_arg, int *continue_walk)
static PT_NODE * pt_lambda_node (PARSER_CONTEXT *parser, PT_NODE *tree_or_name, void *void_arg, int *continue_walk)
static PT_NODE * pt_find_id_node (PARSER_CONTEXT *parser, PT_NODE *tree, void *void_arg, int *continue_walk)
static PT_NODE * copy_node_in_tree_pre (PARSER_CONTEXT *parser, PT_NODE *old_node, void *arg, int *continue_walk)
static PT_NODE * copy_node_in_tree_post (PARSER_CONTEXT *parser, PT_NODE *new_node, void *arg, int *continue_walk)
static PT_NODE * free_node_in_tree_pre (PARSER_CONTEXT *parser, PT_NODE *node, void *arg, int *continue_walk)
static PT_NODE * free_node_in_tree_post (PARSER_CONTEXT *parser, PT_NODE *node, void *arg, int *continue_walk)
static PT_NODE * pt_walk_private (PARSER_CONTEXT *parser, PT_NODE *node, void *void_arg)
static const char * pt_show_event_type (PT_EVENT_TYPE p)
static DB_CURRENCY pt_currency_to_db (const PT_CURRENCY t)
static PARSER_VARCHAR * pt_append_quoted_string (const PARSER_CONTEXT *parser, PARSER_VARCHAR *buf, const char *str, size_t str_length)
static PARSER_VARCHAR * pt_append_string_prefix (const PARSER_CONTEXT *parser, PARSER_VARCHAR *buf, const PT_NODE *value)
static bool pt_is_nested_expr (const PT_NODE *node)
static bool pt_function_is_allowed_as_function_index (const PT_NODE *func)
static bool pt_expr_is_allowed_as_function_index (const PT_NODE *expr)
static void pt_init_apply_f (void)
static void pt_init_init_f (void)
static void pt_init_print_f (void)
static PT_NODE * pt_apply_alter_serial (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_alter_trigger (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_attach (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_auto_increment (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_create_serial (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_create_trigger (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_drop_serial (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_drop_trigger (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_evaluate (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_event_object (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_event_spec (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_event_target (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_execute_trigger (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_get_opt_lvl (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_get_trigger (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_get_xaction (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_isolation_lvl (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_partition (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_parts (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_remove_trigger (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_savepoint (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_scope (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_set_opt_lvl (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_set_sys_params (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_set_trigger (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_set_xaction (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_sp_parameter (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_stored_procedure (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_prepare (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_timeout (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_trigger_action (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_trigger_spec_list (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_alter_index (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_alter (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_alter_user (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_attr_def (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_attr_ordering (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_auth_cmd (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_check_option (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_commit_work (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_constraint (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_create_entity (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_create_index (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_create_user (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_data_default (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_datatype (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_delete (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_difference (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_dot (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_drop_index (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_drop (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_drop_user (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_drop_variable (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_error_msg (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_expr (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_file_path (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_function (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_get_stats (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_grant (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_host_var (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_insert (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_intersection (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_method_call (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_method_def (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_name (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_named_arg (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_node_list (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_pointer (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_prepare_to_commit (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_rename (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_rename_trigger (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_resolution (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_revoke (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_rollback_work (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_select (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_set_names (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_set_timezone (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_set_session_variables (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_drop_session_variables (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_showstmt (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_sort_spec (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_spec (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_table_option (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_truncate (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_do (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_union_stmt (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_update (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_update_stats (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_value (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_merge (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_tuple_value (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_query_trace (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_insert_value (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_kill (PARSER_CONTEXT *parser, PT_NODE *P, void *arg)
static PT_NODE * pt_apply_vacuum (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_with_clause (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_cte (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_json_table (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_json_table_node (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_apply_json_table_column (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
static PT_NODE * pt_init_alter_trigger (PT_NODE *p)
static PT_NODE * pt_init_get_opt_lvl (PT_NODE *p)
static PT_NODE * pt_init_isolation_lvl (PT_NODE *p)
static PT_NODE * pt_init_set_opt_lvl (PT_NODE *p)
static PT_NODE * pt_init_attr_def (PT_NODE *p)
static PT_NODE * pt_init_auth_cmd (PT_NODE *p)
static PT_NODE * pt_init_constraint (PT_NODE *node)
static PT_NODE * pt_init_create_entity (PT_NODE *p)
static PT_NODE * pt_init_create_index (PT_NODE *p)
static PT_NODE * pt_init_data_default (PT_NODE *p)
static PT_NODE * pt_init_datatype (PT_NODE *p)
static PT_NODE * pt_init_delete (PT_NODE *p)
static PT_NODE * pt_init_difference (PT_NODE *p)
static PT_NODE * pt_init_expr (PT_NODE *p)
static PT_NODE * pt_init_function (PT_NODE *p)
static PT_NODE * pt_init_grant (PT_NODE *p)
static PT_NODE * pt_init_insert (PT_NODE *p)
static PT_NODE * pt_init_intersection (PT_NODE *p)
static PT_NODE * pt_init_method_def (PT_NODE *p)
static PT_NODE * pt_init_name (PT_NODE *p)
static PT_NODE * pt_init_node_list (PT_NODE *p)
static PT_NODE * pt_init_pointer (PT_NODE *node)
static PT_NODE * pt_init_resolution (PT_NODE *p)
static PT_NODE * pt_init_select (PT_NODE *p)
static PT_NODE * pt_init_showstmt (PT_NODE *p)
static PT_NODE * pt_init_sort_spec (PT_NODE *p)
static PT_NODE * pt_init_spec (PT_NODE *p)
static PT_NODE * pt_init_table_option (PT_NODE *p)
static PT_NODE * pt_init_union_stmt (PT_NODE *p)
static PT_NODE * pt_init_update (PT_NODE *p)
static PT_NODE * pt_init_value (PT_NODE *p)
static PT_NODE * pt_init_merge (PT_NODE *p)
static PT_NODE * pt_init_tuple_value (PT_NODE *p)
static PT_NODE * pt_init_query_trace (PT_NODE *p)
static PT_NODE * pt_init_insert_value (PT_NODE *p)
static PT_NODE * pt_init_kill (PT_NODE *p)
static PT_NODE * pt_init_vacuum (PT_NODE *p)
static PT_NODE * pt_init_json_table_column (PT_NODE *p)
static PARSER_VARCHAR * pt_print_alter_index (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_alter (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_alter_serial (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_alter_stored_procedure (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_alter_trigger (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_alter_user (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_attach (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_attr_def (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_attr_ordering (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_auth_cmd (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_auto_increment (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_check_option (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_commit_work (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_constraint (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_col_def_constraint (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_create_entity (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_create_index (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_create_serial (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_create_stored_procedure (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_create_trigger (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_create_user (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_data_default (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_datatype (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_delete (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_difference (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_dot (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_drop_index (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_drop (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_drop_serial (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_drop_stored_procedure (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_drop_trigger (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_drop_user (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_drop_variable (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_error_msg (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_evaluate (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_event_object (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_event_spec (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_event_target (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_execute_trigger (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_expr (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_file_path (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_function (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_get_opt_lvl (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_get_stats (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_get_trigger (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_get_xaction (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_grant (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_host_var (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_insert (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_intersection (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_isolation_lvl (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_method_call (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_method_def (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_name (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_named_arg (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_node_list (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_partition (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_parts (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_pointer (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_prepare_to_commit (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_remove_trigger (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_rename (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_rename_trigger (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_resolution (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_revoke (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_rollback_work (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_savepoint (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_scope (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_select (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_set_names (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_set_timezone (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_set_session_variables (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_drop_session_variables (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_set_opt_lvl (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_set_sys_params (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_set_trigger (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_set_xaction (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_showstmt (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_sort_spec (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_spec (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_sp_parameter (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_table_option (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_timeout (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_trigger_action (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_trigger_spec_list (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_truncate (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_do (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_union_stmt (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_update (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_update_stats (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_value (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_session_variables (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_merge (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_index_columns (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_tuple_value (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_query_trace (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_insert_value (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_vacuum (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_with_clause (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_cte (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_json_table (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_json_table_node (PARSER_CONTEXT *parser, PT_NODE *p)
static PARSER_VARCHAR * pt_print_json_table_columns (PARSER_CONTEXT *parser, PT_NODE *p)
static int parser_print_user (char *user_text, int len)
static void pt_clean_tree_copy_info (PT_TREE_COPY_INFO *tree_copy_info)
static const char * pt_json_table_column_behavior_to_string (const json_table_column_behavior_type &behavior_type)
static PARSER_VARCHAR * pt_print_json_table_column_error_or_empty_behavior (PARSER_CONTEXT *parser, PARSER_VARCHAR *pstr, const struct json_table_column_behavior &column_behavior)
static PARSER_VARCHAR * pt_print_json_table_column_info (PARSER_CONTEXT *parser, PT_NODE *p, PARSER_VARCHAR *pstr)
PT_NODE * parser_walk_leaves (PARSER_CONTEXT *parser, PT_NODE *node, PT_NODE_WALK_FUNCTION pre_function, void *pre_argument, PT_NODE_WALK_FUNCTION post_function, void *post_argument)
PT_NODE * parser_walk_tree (PARSER_CONTEXT *parser, PT_NODE *node, PT_NODE_WALK_FUNCTION pre_function, void *pre_argument, PT_NODE_WALK_FUNCTION post_function, void *post_argument)
PT_NODE * pt_continue_walk (PARSER_CONTEXT *parser, PT_NODE *tree, void *arg, int *continue_walk)
PT_NODE * pt_lambda_with_arg (PARSER_CONTEXT *parser, PT_NODE *tree_with_names, PT_NODE *name_node, PT_NODE *corresponding_tree, bool loc_check, int type, bool dont_replace)
PT_NODE * pt_lambda (PARSER_CONTEXT *parser, PT_NODE *tree_with_names, PT_NODE *name_node, PT_NODE *corresponding_tree)
UINTPTR pt_find_id (PARSER_CONTEXT *parser, PT_NODE *tree_with_names, UINTPTR id)
PT_NODE * parser_copy_tree (PARSER_CONTEXT *parser, const PT_NODE *tree)
PT_NODE * parser_copy_tree_list (PARSER_CONTEXT *parser, PT_NODE *tree)
PT_NODE * parser_get_tree_list_diff (PARSER_CONTEXT *parser, PT_NODE *list1, PT_NODE *list2)
PT_NODE * pt_point (PARSER_CONTEXT *parser, const PT_NODE *in_tree)
PT_NODE * pt_point_l (PARSER_CONTEXT *parser, const PT_NODE *in_tree)
PT_NODE * pt_point_ref (PARSER_CONTEXT *parser, const PT_NODE *node)
PT_NODE * pt_pointer_stack_push (PARSER_CONTEXT *parser, PT_NODE *stack, PT_NODE *node)
PT_NODE * pt_pointer_stack_pop (PARSER_CONTEXT *parser, PT_NODE *stack, PT_NODE **node)
void parser_free_tree (PARSER_CONTEXT *parser, PT_NODE *tree)
void parser_free_subtrees (PARSER_CONTEXT *parser, PT_NODE *tree)
void parser_clear_node (PARSER_CONTEXT *parser, PT_NODE *node)
void * pt_internal_error (PARSER_CONTEXT *parser, const char *file, int line, const char *what)
static int fgetin (PARSER_CONTEXT *p)
static int buffgetin (PARSER_CONTEXT *p)
int pt_push (PARSER_CONTEXT *parser, PT_NODE *node)
PT_NODE * pt_pop (PARSER_CONTEXT *parser)
PT_NODE * pt_top (PARSER_CONTEXT *parser)
PT_NODE ** parser_parse_string_use_sys_charset (PARSER_CONTEXT *parser, const char *buffer)
PT_NODE ** parser_parse_string (PARSER_CONTEXT *parser, const char *buffer)
PT_NODE ** parser_parse_string_with_escapes (PARSER_CONTEXT *parser, const char *buffer, const bool strings_have_no_escapes)
PT_NODE ** parser_parse_file (PARSER_CONTEXT *parser, FILE *file)
PT_NODE ** pt_init_one_statement_parser (PARSER_CONTEXT *parser, FILE *file)
void pt_record_error (PARSER_CONTEXT *parser, int stmt_no, int line_no, int col_no, const char *msg, const char *context)
void pt_frob_warning (PARSER_CONTEXT *parser, const PT_NODE *stmt, const char *fmt,...)
void pt_frob_error (PARSER_CONTEXT *parser, const PT_NODE *stmt, const char *fmt,...)
PT_NODE * pt_get_errors (PARSER_CONTEXT *parser)
PT_NODE * pt_get_next_error (PT_NODE *errors, int *stmt_no, int *line_no, int *col_no, const char **msg)
PT_NODE * parser_new_node (PARSER_CONTEXT *parser, PT_NODE_TYPE node_type)
PT_NODE * parser_init_node (PT_NODE *node, PT_NODE_TYPE node_type)
PT_NODE * parser_reinit_node (PT_NODE *node)
PARSER_VARCHAR * pt_print_bytes_alias (PARSER_CONTEXT *parser, const PT_NODE *node)
PARSER_VARCHAR * pt_print_bytes (PARSER_CONTEXT *parser, const PT_NODE *node)
PARSER_VARCHAR * pt_print_bytes_l (PARSER_CONTEXT *parser, const PT_NODE *p)
PARSER_VARCHAR * pt_print_bytes_spec_list (PARSER_CONTEXT *parser, const PT_NODE *p)
PARSER_VARCHAR * pt_print_node_value (PARSER_CONTEXT *parser, const PT_NODE *val)
PARSER_VARCHAR * pt_print_db_value (PARSER_CONTEXT *parser, const struct db_value *val)
char * pt_print_alias (PARSER_CONTEXT *parser, const PT_NODE *node)
char * parser_print_tree (PARSER_CONTEXT *parser, const PT_NODE *node)
char * parser_print_tree_with_quotes (PARSER_CONTEXT *parser, const PT_NODE *node)
char * parser_print_function_index_expr (PARSER_CONTEXT *parser, const PT_NODE *expr)
char * parser_print_tree_list (PARSER_CONTEXT *parser, const PT_NODE *node)
PARSER_VARCHAR * pt_print_and_list (PARSER_CONTEXT *parser, const PT_NODE *p)
char * pt_print_query_spec_no_list (PARSER_CONTEXT *parser, const PT_NODE *node)
char * pt_short_print (PARSER_CONTEXT *parser, const PT_NODE *node)
char * pt_short_print_l (PARSER_CONTEXT *parser, const PT_NODE *node)
const char * pt_show_node_type (PT_NODE *node)
PT_NODE * parser_append_node (PT_NODE *node, PT_NODE *list)
PT_NODE * parser_append_node_or (PT_NODE *node, PT_NODE *list)
int pt_length_of_list (const PT_NODE *list)
int pt_length_of_select_list (PT_NODE *list, int hidden_col)
PT_NODE * pt_get_node_from_list (PT_NODE *list, int index)
const char * pt_show_misc_type (PT_MISC_TYPE p)
const char * pt_show_binopcode (PT_OP_TYPE n)
const char * pt_show_priv (PT_PRIV_TYPE t)
const char * pt_show_type_enum (PT_TYPE_ENUM t)
const char * pt_show_partition_type (PT_PARTITION_TYPE t)
PT_NODE * pt_gather_constraints (PARSER_CONTEXT *parser, PT_NODE *node)
PT_NODE * pt_get_subquery_list (PT_NODE *node)
int pt_get_expression_count (PT_NODE *node)
void pt_select_list_to_one_col (PARSER_CONTEXT *parser, PT_NODE *node, bool do_one)
int pt_check_set_count_set (PARSER_CONTEXT *parser, PT_NODE *arg1, PT_NODE *arg2)
PT_NODE * pt_rewrite_set_eq_set (PARSER_CONTEXT *parser, PT_NODE *exp)
void pt_init_node (PT_NODE *node, PT_NODE_TYPE node_type)
PARSER_VARCHAR * pt_append_name (const PARSER_CONTEXT *parser, PARSER_VARCHAR *string, const char *name)
static PARSER_VARCHAR * pt_print_alter_one_clause (PARSER_CONTEXT *parser, PT_NODE *p)
static void pt_print_range_op (PARSER_CONTEXT *parser, PT_STRING_BLOCK *sb, PT_NODE *t, PARSER_VARCHAR *lhs)
void parser_init_func_vectors (void)
bool pt_is_const_expr_node (PT_NODE *node)
void pt_restore_assignment_links (PT_NODE *assigns, PT_NODE **links, int count)
int pt_get_assignment_lists (PARSER_CONTEXT *parser, PT_NODE **select_names, PT_NODE **select_values, PT_NODE **const_names, PT_NODE **const_values, int *no_vals, int *no_consts, PT_NODE *assign, PT_NODE ***old_links)
PT_NODE * pt_function_index_skip_expr (PT_NODE *node)
bool pt_is_function_index_expr (PARSER_CONTEXT *parser, PT_NODE *expr, bool report_error)
PT_NODE * pt_expr_to_sort_spec (PARSER_CONTEXT *parser, PT_NODE *expr)
bool pt_is_join_expr (PT_NODE *expr, UINTPTR *spec_id)
PT_NODE * pt_sort_spec_list_to_name_node_list (PARSER_CONTEXT *parser, PT_NODE *sort_spec_list)
void pt_move_node (REFPTR(PT_NODE, destp), REFPTR(PT_NODE, srcp))
Variables
static PARSER_INIT_NODE_FUNC * pt_init_f = NULL
static PARSER_PRINT_NODE_FUNC * pt_print_f = NULL
static PARSER_APPLY_NODE_FUNC * pt_apply_f = NULL
PARSER_CONTEXT * parent_parser = NULL
static PARSER_APPLY_NODE_FUNC pt_apply_func_array [PT_NODE_NUMBER]
static PARSER_INIT_NODE_FUNC pt_init_func_array [PT_NODE_NUMBER]
static PARSER_PRINT_NODE_FUNC pt_print_func_array [PT_NODE_NUMBER]
char * g_query_string
int g_query_string_len
Macro Definition Documentation
#define ASSIGN_LINKS_EXTENT 10
Referenced by pt_get_assignment_lists().
#define DELTA 512
Referenced by pt_push().
#define DONT_PRT_LONG_STRING_LENGTH 256
Definition at line 69 of file parse_tree_cl.c.
Referenced by pt_print_value().
#define INITIAL_EXTENT 512
Referenced by pt_push().
#define MAX_STRING_SEGMENT_LENGTH 254
Definition at line 68 of file parse_tree_cl.c.
Referenced by pt_append_quoted_string().
#define PT_APPLY_WALK (parser, ptr, arg)
Value:
do { \
         if((ptr))                           \
           {                                 \
                (ptr) = pt_walk_private ((parser), (ptr), (arg)); \
           }                                 \
      } while (0)
Definition at line 71 of file parse_tree_cl.c.
Referenced by pt_apply_alter(), pt_apply_alter_index(), pt_apply_alter_serial(), pt_apply_alter_trigger(), pt_apply_alter_user(), pt_apply_attr_def(), pt_apply_attr_ordering(), pt_apply_auth_cmd(), pt_apply_check_option(), pt_apply_constraint(), pt_apply_create_entity(), pt_apply_create_index(), pt_apply_create_serial(), pt_apply_create_trigger(), pt_apply_create_user(), pt_apply_cte(), pt_apply_data_default(), pt_apply_datatype(), pt_apply_delete(), pt_apply_difference(), pt_apply_do(), pt_apply_dot(), pt_apply_drop(), pt_apply_drop_index(), pt_apply_drop_session_variables(), pt_apply_drop_trigger(), pt_apply_drop_user(), pt_apply_drop_variable(), pt_apply_evaluate(), pt_apply_event_object(), pt_apply_event_spec(), pt_apply_event_target(), pt_apply_execute_trigger(), pt_apply_expr(), pt_apply_function(), pt_apply_get_opt_lvl(), pt_apply_get_stats(), pt_apply_get_trigger(), pt_apply_get_xaction(), pt_apply_grant(), pt_apply_insert(), pt_apply_insert_value(), pt_apply_intersection(), pt_apply_isolation_lvl(), pt_apply_json_table(), pt_apply_json_table_column(), pt_apply_json_table_node(), pt_apply_merge(), pt_apply_method_call(), pt_apply_method_def(), pt_apply_name(), pt_apply_named_arg(), pt_apply_node_list(), pt_apply_partition(), pt_apply_parts(), pt_apply_pointer(), pt_apply_remove_trigger(), pt_apply_rename(), pt_apply_rename_trigger(), pt_apply_resolution(), pt_apply_revoke(), pt_apply_rollback_work(), pt_apply_savepoint(), pt_apply_scope(), pt_apply_select(), pt_apply_set_names(), pt_apply_set_opt_lvl(), pt_apply_set_session_variables(), pt_apply_set_sys_params(), pt_apply_set_timezone(), pt_apply_set_trigger(), pt_apply_set_xaction(), pt_apply_showstmt(), pt_apply_sort_spec(), pt_apply_spec(), pt_apply_table_option(), pt_apply_timeout(), pt_apply_trigger_action(), pt_apply_trigger_spec_list(), pt_apply_truncate(), pt_apply_tuple_value(), pt_apply_union_stmt(), pt_apply_update(), pt_apply_update_stats(), pt_apply_value(), pt_apply_with_clause(), and pt_print_get_stats().
#define pt_init_func_null_function ((PARSER_INIT_NODE_FUNC)(NULL))
Referenced by pt_init_init_f().
#define PT_MEMB_BUF_SIZE 100
Definition at line 65 of file parse_tree_cl.c.
Referenced by pt_print_attach(), pt_print_attr_def(), pt_print_datatype(), pt_print_expr(), pt_print_host_var(), pt_print_partition(), pt_print_prepare_to_commit(), and pt_print_value().
#define PT_MEMB_ERR_BUF_SIZE 256
Definition at line 67 of file parse_tree_cl.c.
Referenced by pt_print_error_msg().
#define PT_MEMB_PRINTABLE_BUF_SIZE 512
Definition at line 66 of file parse_tree_cl.c.
Referenced by pt_print_value().
#define PT_QUERY_STRING_USER_TEXT
Value:
(\
  5   /* user= */ \
  + 6     /* volid| (values up to 16384) */ \
  + 11    /* pageid| (values up to 2147483647) */ \
  + 5     /* slotid (values up to 16384) */ \
  + 1     /* \0 */)
Referenced by parser_print_tree().
#define SAFENUM (node, field) ((node) ? (node)->field : -1)
Definition at line 64 of file parse_tree_cl.c.
Referenced by pt_frob_error(), and pt_frob_warning().
Typedef Documentation
typedef PT_NODE*(* PARSER_APPLY_NODE_FUNC) (PARSER_CONTEXT *parser, PT_NODE *p, void *arg)
Definition at line 130 of file parse_tree_cl.c.
typedef PT_NODE*(* PARSER_INIT_NODE_FUNC) (PT_NODE *)
Definition at line 128 of file parse_tree_cl.c.
typedef PARSER_VARCHAR*(* PARSER_PRINT_NODE_FUNC) (PARSER_CONTEXT *parser, PT_NODE *node)
Definition at line 129 of file parse_tree_cl.c.
typedef struct pt_copy_cte_info PT_CTE_COPY_INFO
Definition at line 114 of file parse_tree_cl.c.
typedef struct pt_find_id_info PT_FIND_ID_INFO
Definition at line 89 of file parse_tree_cl.c.
typedef struct pt_lambda_arg PT_LAMBDA_ARG
Definition at line 78 of file parse_tree_cl.c.
typedef struct pt_string_block PT_STRING_BLOCK
Definition at line 106 of file parse_tree_cl.c.
typedef struct pt_tree_copy_info PT_TREE_COPY_INFO
Definition at line 122 of file parse_tree_cl.c.
typedef struct pt_walk_arg PT_WALK_ARG
Definition at line 96 of file parse_tree_cl.c.
Function Documentation
static int buffgetin (PARSER_CONTEXT * p) static
Definition at line 1542 of file parse_tree_cl.c.
References parser_context::buffer, parser_context::input_buffer_length, parser_context::input_buffer_position, and p.
Referenced by parser_parse_string_with_escapes().
static PT_NODE * copy_node_in_tree_post (PARSER_CONTEXT * parser, PT_NODE * new_node, void * arg, int * continue_walk) static
Definition at line 806 of file parse_tree_cl.c.
References assert, pt_spec_info::cte_pointer, pt_tree_copy_info::cte_structures_list, parser_node::info, pt_copy_cte_info::new_cte_node, pt_copy_cte_info::next, pt_pointer_info::node, parser_node::node_type, NULL, pt_copy_cte_info::old_cte_node, pt_statement_info::pointer, PT_CTE, PT_SPEC, PT_SPEC_IS_CTE, and pt_statement_info::spec.
Referenced by parser_copy_tree(), and parser_copy_tree_list().
static PT_NODE * copy_node_in_tree_pre (PARSER_CONTEXT * parser, PT_NODE * old_node, void * arg, int * continue_walk) static
Definition at line 718 of file parse_tree_cl.c.
References pt_tree_copy_info::cte_structures_list, pt_value_info::db_value, db_value_clone(), db_value_copy(), pt_value_info::db_value_is_in_workspace, pt_value_info::db_value_is_initialized, er_msg(), parser_context::id, parser_node::info, pt_statement_info::json_table_column_info, json_table_column_behavior::m_default_value, pt_statement_info::name, pt_copy_cte_info::new_cte_node, pt_copy_cte_info::next, parser_node::node_type, NULL, pt_copy_cte_info::old_cte_node, pt_json_table_column_info::on_empty, pt_json_table_column_info::on_error, pt_name_info::original, parser_node::parser_id, parser_new_node(), pt_append_string(), PT_CTE, PT_ERRORc, PT_INTERNAL_ERROR, PT_JSON_TABLE_COLUMN, PT_NAME, PT_VALUE, pt_name_info::resolved, pt_value_info::text, and pt_statement_info::value.
Referenced by parser_copy_tree(), and parser_copy_tree_list().
static int fgetin (PARSER_CONTEXT * p) static
Definition at line 1520 of file parse_tree_cl.c.
References parser_context::file.
Referenced by parser_parse_file(), and pt_init_one_statement_parser().
static PT_NODE * free_node_in_tree_post (PARSER_CONTEXT * parser, PT_NODE * node, void * arg, int * continue_walk) static
Definition at line 1433 of file parse_tree_cl.c.
References NULL, and parser_free_node().
Referenced by parser_free_subtrees(), and parser_free_tree().
static PT_NODE * free_node_in_tree_pre (PARSER_CONTEXT * parser, PT_NODE * node, void * arg, int * continue_walk) static
Definition at line 1414 of file parse_tree_cl.c.
References parser_node::info, pt_pointer_info::node, parser_node::node_type, NULL, pt_statement_info::pointer, and PT_NODE_POINTER.
Referenced by parser_free_subtrees(), and parser_free_tree().
PT_NODE* parser_append_node (PT_NODE * node, PT_NODE * list)
Definition at line 3066 of file parse_tree_cl.c.
References parser_node::next.
Referenced by char_array_to_name_list(), check_for_cons(), create_select_to_insert_into(), do_update_new_cols_with_default_expression(), do_update_new_notnull_cols_without_default(), fill_in_insert_default_function_arguments(), gen_outer(), meth_collapse_nodes(), meth_copy_hierarchical_expr_to_list(), meth_create_method_list(), meth_gen_as_attr_list(), meth_get_method_params(), meth_grab_cnf_conj(), meth_method_path_entities(), meth_non_method_path_entities(), meth_translate_spec(), mq_class_lambda(), mq_copypush_sargable_terms_helper(), mq_derived_path(), mq_flatten_union(), mq_insert_symbol(), mq_lambda_node(), mq_make_derived_spec(), mq_push_dot_in_query(), mq_push_path(), mq_reset_paths(), mq_rewrite_agg_names(), mq_rewrite_aggregate_as_derived(), mq_rewrite_order_dependent_nodes(), mq_rewrite_order_dependent_query(), mq_rewrite_query_as_derived(), mq_substitute_path(), mq_substitute_subquery_in_statement(), mq_substitute_subquery_list_in_statement(), mq_translate_local(), mq_translate_paths(), mq_translate_tree(), mq_update_order_by(), parser_generate_xasl_proc(), parser_get_tree_list_diff(), pt_add_name_col_to_sel_list(), pt_add_string_col_to_sel_list(), pt_add_table_name_to_from_list(), pt_append_assignment_references(), pt_append_omitted_on_update_expr_assignments(), pt_append_query_select_list(), pt_bind_names(), pt_check_access_status(), pt_check_assignments(), pt_check_create_view(), pt_check_function_index_expr(), pt_check_hint(), pt_check_order_by(), pt_check_show_index(), pt_check_table_in_show_heap(), pt_collect_parameters(), pt_common_attribute(), pt_copypush_terms(), pt_domain_to_data_type(), pt_expand_analytic_node(), pt_expr_to_sort_spec(), pt_fix_buildlist_aggregate_cume_dist_percent_rank(), pt_gather_constraints(), pt_get_all_showstmt_attributes_and_types(), pt_get_assignment_lists(), pt_get_attr_list_of_derived_table(), pt_get_attributes(), pt_get_mvcc_reev_range_data(), pt_get_pred_attrs(), pt_get_resolution(), pt_json_table_gather_attribs(), pt_make_aptr_parent_node(), pt_make_collection_type_subquery_node(), pt_make_field_extra_expr_node(), pt_make_field_key_type_expr_node(), pt_make_field_type_expr_node(), pt_make_flat_name_list(), pt_make_outer_select_for_show_stmt(), pt_make_prefix_index_data_filter(), pt_make_query_show_collation(), pt_make_query_show_columns(), pt_make_query_show_create_view(), pt_make_query_show_grants(), pt_make_query_show_index(), pt_make_query_show_table(), pt_make_query_show_trace(), pt_make_query_showstmt(), pt_make_query_user_groups(), pt_make_select_count_star(), pt_make_subclass_list(), pt_name_list_diff(), pt_name_list_union(), pt_negate_expr(), pt_number_of_attributes(), pt_point_l(), pt_print_select(), pt_propagate_types(), pt_record_error(), pt_record_warning(), pt_register_orphan(), pt_register_orphan_db_value(), pt_remove_unusable_sort_specs(), pt_resolve_showstmt_args_named(), pt_resolve_star_reserved_names(), pt_resolve_vclass_args(), pt_rewrite_derived_for_upd_del(), pt_select_list_to_one_col(), pt_semantic_check_local(), pt_set_elements_to_value(), pt_set_orderby_for_sort_limit_plan(), pt_sort_list_from_metadomain(), pt_sort_spec_list_to_name_node_list(), pt_split_attrs(), pt_split_hash_attrs(), pt_split_hash_attrs_for_HQ(), pt_split_join_preds(), pt_to_aggregate_node(), pt_to_analytic_final_node(), pt_to_buildlist_proc(), pt_to_delete_xasl(), pt_to_false_subquery(), pt_to_index_attrs(), pt_to_list_key(), pt_to_merge_insert_query(), pt_to_merge_update_query(), pt_to_merge_update_xasl(), pt_to_range_key(), pt_to_rangelist_key(), pt_to_single_key(), pt_to_upd_del_query(), pt_transform_cnf_post(), pt_type_generic_func(), qo_analyze_path_join(), qo_check_iscan_for_multi_range_opt(), qo_collect_name_spec(), qo_converse_sarg_terms(), qo_optimize_queries(), qo_plan_compute_iscan_sort_list(), qo_reduce_equality_terms(), qo_reduce_order_by(), qo_reduce_order_by_for(), qo_rewrite_subqueries(), and update_check_for_constraints().
PT_NODE* parser_append_node_or (PT_NODE * node, PT_NODE * list)
Definition at line 3092 of file parse_tree_cl.c.
References parser_node::or_next.
Referenced by pt_negate_expr().
void parser_clear_node (PARSER_CONTEXT * parser, PT_NODE * node)
Definition at line 1465 of file parse_tree_cl.c.
References parser_free_node_resources(), and parser_free_subtrees().
Referenced by pt_coerce_value_internal().
PT_NODE* parser_copy_tree (PARSER_CONTEXT * parser, const PT_NODE * tree)
Definition at line 1122 of file parse_tree_cl.c.
References copy_node_in_tree_post(), copy_node_in_tree_pre(), pt_tree_copy_info::cte_structures_list, parser_node::next, NULL, parser_walk_tree(), and pt_clean_tree_copy_info().
Referenced by do_alter_clause_rename_entity(), do_alter_one_clause_with_template(), do_create_partition(), do_evaluate_insert_values(), do_replace_names_for_insert_values_pre(), do_update_new_cols_with_default_expression(), do_update_new_notnull_cols_without_default(), execute_create_select_query(), fill_in_insert_default_function_arguments(), get_att_default_from_def(), meth_copy_hierarchical_expr_to_list(), meth_create_method_list(), meth_gen_as_attr_list(), meth_get_method_params(), meth_method_path_entities(), meth_non_method_path_entities(), meth_replace_call(), meth_replace_hierarchical_exprs(), meth_replace_method_params(), meth_translate_spec(), mq_copypush_sargable_terms_helper(), mq_derived_path(), mq_fetch_subqueries(), mq_generate_unique(), mq_insert_symbol(), mq_lambda_node(), mq_make_derived_spec(), mq_oid(), mq_push_arg2(), mq_push_dot_in_query(), mq_replace_name_with_path(), mq_rewrite_aggregate_as_derived(), mq_rewrite_order_dependent_nodes(), mq_rewrite_order_dependent_query(), mq_rewrite_query_as_derived(), mq_rewrite_vclass_spec_as_derived(), mq_set_types(), mq_substitute_path(), mq_substitute_path_pre(), mq_substitute_subquery_in_statement(), mq_translate_insert(), mq_translate_tree(), mq_update_order_by(), mq_virtual_queries(), pt_apply_union_select_list_collation(), pt_attr_check_default_cs_coll(), pt_check_alter_partition(), pt_check_analytic_function(), pt_check_auto_increment_table_option(), pt_check_function_index_expr(), pt_check_order_by(), pt_check_partitions(), pt_check_union_compatibility(), pt_collect_host_info(), pt_collect_parameters(), pt_compile_trigger_stmt(), pt_create_param_for_value(), pt_dup_key_update_stmt(), pt_eval_expr_type(), pt_eval_type(), pt_evaluate_tree_internal(), pt_exec_trigger_stmt(), pt_expr_to_sort_spec(), pt_fix_interpolation_aggregate_function_order_by(), pt_fold_const_expr(), pt_gen_isnull_preds(), pt_get_all_json_table_attributes_and_types(), pt_get_mvcc_reev_range_data(), pt_get_resolution(), pt_get_select_query_columns(), pt_insert_conjunct(), pt_insert_entity(), pt_insert_host_var(), pt_invert(), pt_json_table_gather_attribs(), pt_limit_to_numbering_expr(), pt_make_tuple_value_reference(), pt_must_have_exposed_name(), pt_negate_expr(), pt_node_to_enumeration_expr(), pt_replace_referenced_attributes(), pt_resolve_group_having_alias_pt_name(), pt_resolve_object(), pt_resolve_star(), pt_rewrite_derived_for_upd_del(), pt_rewrite_set_eq_set(), pt_select_list_to_one_col(), pt_semantic_check_local(), pt_set_table_to_db(), pt_sort_list_from_metadomain(), pt_sort_spec_list_to_name_node_list(), pt_spec_to_oid_attr(), pt_split_delete_stmt(), pt_split_hash_attrs(), pt_split_hash_attrs_for_HQ(), pt_to_merge_insert_query(), pt_to_merge_update_xasl(), pt_to_odku_info(), pt_to_regu_variable(), pt_transform_cnf_post(), qo_allocate_like_bound_for_index_scan(), qo_analyze_path_join(), qo_apply_range_intersection_helper(), qo_construct_new_set(), qo_converse_sarg_terms(), qo_convert_attref_to_dotexpr(), qo_find_like_rewrite_bound(), qo_get_orderby_num_upper_bound_node(), qo_make_new_derived_tblspec(), qo_merge_range_helper(), qo_reduce_equality_terms(), qo_rewrite_like_for_index_scan(), qo_rewrite_subqueries(), and qo_set_value_to_range_list().
PT_NODE* parser_copy_tree_list (PARSER_CONTEXT * parser, PT_NODE * tree)
Definition at line 1153 of file parse_tree_cl.c.
References copy_node_in_tree_post(), copy_node_in_tree_pre(), pt_tree_copy_info::cte_structures_list, NULL, parser_walk_tree(), pt_clean_tree_copy_info(), and pt_lambda_arg::tree.
Referenced by db_execute_and_keep_statement_local(), do_merge(), do_prepare_merge(), make_sort_limit_proc(), meth_move_hierarchical_to_derived(), meth_translate_spec(), mq_class_lambda(), mq_derived_path(), mq_invert_subqueries(), mq_lambda_node(), mq_push_arg2(), mq_push_dot_in_query(), mq_push_path(), mq_rewrite_agg_names(), mq_rewrite_vclass_spec_as_derived(), mq_set_types(), mq_set_virt_object(), mq_substitute_subquery_in_statement(), mq_translate_paths(), mq_translate_subqueries(), mq_translate_tree(), mq_update_order_by(), mq_virtual_queries(), pt_add_type_to_set(), pt_apply_union_select_list_collation(), pt_assignment_compatible(), pt_bind_names(), pt_bind_spec_attrs(), pt_check_vclass_query_spec(), pt_coerce_expression_argument(), pt_coerce_node_collation(), pt_coerce_value_internal(), pt_copy_data_type_entity(), pt_copy_upddel_hints_to_select(), pt_copypush_terms(), pt_eval_expr_type(), pt_eval_function_type_old(), pt_eval_type(), pt_expand_analytic_node(), pt_expand_external_path(), pt_find_name_in_spec(), pt_fold_const_expr(), pt_gen_isnull_preds(), pt_gen_simple_merge_plan(), pt_gen_simple_plan(), pt_get_attr_list_of_derived_table(), pt_get_resolution(), pt_get_select_list(), pt_insert_conjunct(), pt_lambda_node(), pt_make_cast_with_compatible_info(), pt_make_connect_by_proc(), pt_make_method_call(), pt_make_prefix_index_data_filter(), pt_object_to_data_type(), pt_propagate_types(), pt_resolve_star(), pt_resolve_vclass_args(), pt_rewrite_derived_for_upd_del(), pt_select_list_to_one_col(), pt_set_attr_list_types(), pt_set_reserved_name_key_type(), pt_spec_to_oid_attr(), pt_substitute_assigned_name_node(), pt_to_analytic_node(), pt_to_compatible_cast(), pt_to_merge_insert_query(), pt_to_merge_update_query(), pt_to_merge_update_xasl(), pt_to_upd_del_query(), pt_transform_cnf_post(), pt_type_cast_vclass_query_spec(), pt_type_cast_vclass_query_spec_column(), pt_upd_domain_info(), pt_values_query_to_compatible_cast(), pt_wrap_collection_with_cast_op(), pt_wrap_with_cast_op(), qo_analyze_path_join(), qo_check_condition_yields_null(), qo_construct_new_set(), qo_reduce_equality_terms(), qo_rewrite_like_for_index_scan(), and func_type::Node::set_return_type().
void parser_free_subtrees (PARSER_CONTEXT * parser, PT_NODE * tree)
Definition at line 1458 of file parse_tree_cl.c.
References free_node_in_tree_post(), free_node_in_tree_pre(), NULL, and parser_walk_leaves().
Referenced by parser_clear_node(), and pt_check_union_type_compatibility_of_values_query().
void parser_free_tree (PARSER_CONTEXT * parser, PT_NODE * tree)
Definition at line 1446 of file parse_tree_cl.c.
References free_node_in_tree_post(), free_node_in_tree_pre(), NULL, and parser_walk_tree().
Referenced by add_access_spec(), add_sort_spec(), check_for_cons(), compile_trigger_activity(), create_select_to_insert_into(), db_close_session_local(), db_drop_all_statements(), db_drop_statement(), db_execute_and_keep_statement_local(), db_execute_statement_local(), db_parse_one_statement(), do_alter_clause_rename_entity(), do_alter_one_clause_with_template(), do_create_odku_stmt(), do_create_partition(), do_evaluate_insert_values(), do_execute_merge(), do_insert(), do_insert_template(), do_merge(), do_prepare_delete(), do_prepare_insert(), do_prepare_merge(), do_prepare_update(), do_recreate_filter_index_constr(), do_recreate_func_index_constr(), do_replace_names_for_insert_values_pre(), do_update_new_cols_with_default_expression(), do_update_new_notnull_cols_without_default(), execute_create_select_query(), fill_in_insert_default_function_arguments(), free_activity(), gen_inner(), gen_outer(), get_att_default_from_def(), get_select_list_to_update(), init_class_scan_proc(), init_list_scan_proc(), insert_subquery_results(), is_server_update_allowed(), make_fetch_proc(), make_mergelist_proc(), make_pred_from_bitset(), make_sort_limit_proc(), meth_create_method_list(), meth_move_hierarchical_to_derived(), meth_replace_hierarchical_exprs(), meth_translate_spec(), mq_class_lambda(), mq_clean_dot(), mq_copypush_sargable_terms_helper(), mq_fetch_subqueries(), mq_free_virtual_query_cache(), mq_invert_insert_select(), mq_invert_subqueries(), mq_is_real_class_of_vclass(), mq_lambda_node(), mq_oid(), mq_path_spec_lambda(), mq_push_arg2(), mq_push_path(), mq_push_paths_select(), mq_replace_name_with_path(), mq_replace_virtual_oid_with_real_oid(), mq_reset_ids_and_references_helper(), mq_reset_paths(), mq_rewrite_agg_names(), mq_rewrite_vclass_spec_as_derived(), mq_set_references_local(), mq_set_types(), mq_set_virt_object(), mq_substitute_path(), mq_substitute_path_pre(), mq_substitute_subquery_in_statement(), mq_translate_insert(), mq_translate_paths(), mq_translate_tree(), mq_update_attribute(), mq_virtual_queries(), parser_generate_xasl(), pt_add_oid_to_select_list(), pt_add_type_to_set(), pt_and_or_form(), pt_append_omitted_on_update_expr_assignments(), pt_apply_union_select_list_collation(), pt_assignment_compatible(), pt_attr_check_default_cs_coll(), pt_bind_names(), pt_bind_names_post(), pt_bind_parameter(), pt_bind_parameter_path(), pt_bind_reserved_name(), pt_bind_spec_attrs(), pt_bind_value_to_hostvar_local(), pt_check_alter_partition(), pt_check_analytic_function(), pt_check_and_replace_hostvar(), pt_check_assignments(), pt_check_auto_increment_table_option(), pt_check_default_vclass_query_spec(), pt_check_group_concat_order_by(), pt_check_hint(), pt_check_order_by(), pt_check_union_compatibility(), pt_check_union_type_compatibility_of_values_query(), pt_chop_to_one_select_item(), pt_coerce_range_expr_arguments(), pt_coerce_str_to_time_date_utime_datetime(), pt_dup_key_update_stmt(), pt_eval_expr_type(), pt_eval_type(), pt_evaluate_tree_internal(), pt_exec_trigger_stmt(), pt_expand_analytic_node(), pt_find_attr_in_class_list(), pt_fix_enumeration_comparison(), pt_fix_first_term_expr_for_iss(), pt_fix_first_term_func_index_for_iss(), pt_fold_const_expr(), pt_fold_const_function(), pt_fold_union(), pt_free_escape_char(), pt_free_orphans(), pt_gen_simple_merge_plan(), pt_gen_simple_plan(), pt_get_all_attributes_and_types(), pt_get_all_showstmt_attributes_and_types(), pt_get_mvcc_reev_range_data(), pt_get_pred_attrs(), pt_get_resolution(), pt_get_select_list(), pt_get_select_query_columns(), pt_init_pred_expr_context(), pt_insert_entity(), pt_limit_to_numbering_expr(), pt_make_aptr_parent_node(), pt_make_cast_with_compatible_info(), pt_make_connect_by_proc(), pt_make_outer_select_for_show_columns(), pt_make_prefix_index_data_filter(), pt_make_prim_data_type(), pt_make_prim_data_type_fortonum(), pt_make_query_show_columns(), pt_make_query_show_index(), pt_make_query_showstmt(), pt_mvcc_flag_specs_assign_reev(), pt_mvcc_flag_specs_cond_reev(), pt_mvcc_set_spec_assign_reev_extra_indexes(), pt_name_list_diff(), pt_negate_expr(), pt_plan_query(), pt_point_l(), pt_pointer_stack_pop(), pt_print_host_var(), pt_propagate_types(), pt_remove_from_list(), pt_remove_unusable_sort_specs(), pt_replace_names_in_update_values(), pt_replace_names_index_expr(), pt_reset_error(), pt_resolve_correlation(), pt_resolve_default_value(), pt_resolve_hint(), pt_resolve_names(), pt_resolve_partition_spec(), pt_resolve_star_reserved_names(), pt_resolve_vclass_args(), pt_rewrite_set_eq_set(), pt_rewrite_to_auto_param(), pt_select_list_to_one_col(), pt_set_attr_list_types(), pt_set_orderby_for_sort_limit_plan(), pt_set_table_to_db(), pt_set_trigger_obj_post(), pt_set_update_object(), pt_sm_attribute_default_value_to_node(), pt_sort_list_from_metadomain(), pt_split_attrs(), pt_split_delete_stmt(), pt_split_hash_attrs(), pt_split_hash_attrs_for_HQ(), pt_substitute_analytic_references(), pt_substitute_assigned_name_node(), pt_to_analytic_final_node(), pt_to_buildlist_proc(), pt_to_class_spec_list(), pt_to_compatible_cast(), pt_to_constraint_pred(), pt_to_cte_table_spec_list(), pt_to_delete_xasl(), pt_to_false_subquery(), pt_to_fetch_as_scan_proc(), pt_to_index_attrs(), pt_to_list_key(), pt_to_merge_insert_query(), pt_to_merge_insert_xasl(), pt_to_merge_update_query(), pt_to_merge_update_xasl(), pt_to_odku_info(), pt_to_range_key(), pt_to_rangelist_key(), pt_to_regu_variable(), pt_to_single_key(), pt_to_subquery_table_spec_list(), pt_to_upd_del_query(), pt_to_update_xasl(), pt_transform_cnf_post(), pt_try_remove_order_by(), pt_type_cast_vclass_query_spec(), pt_type_cast_vclass_query_spec_column(), pt_values_query_to_compatible_cast(), pt_where_type(), qo_add_hq_iterations_access_spec(), qo_allocate_like_bound_for_index_scan(), qo_analyze_path_join(), qo_apply_range_intersection(), qo_apply_range_intersection_helper(), qo_check_condition_yields_null(), qo_check_iscan_for_multi_range_opt(), qo_converse_sarg_terms(), qo_convert_to_range(), qo_convert_to_range_helper(), qo_find_like_rewrite_bound(), qo_fold_is_and_not_null(), qo_get_orderby_num_upper_bound_node(), qo_merge_range_helper(), qo_optimize_queries_post(), qo_plan_add_to_free_list(), qo_plan_is_orderby_skip_candidate(), qo_reduce_comp_pair_terms(), qo_reduce_equality_terms(), qo_reduce_order_by(), qo_reduce_order_by_for(), qo_replace_spec_name_with_null(), qo_rewrite_hidden_col_as_derived(), qo_rewrite_index_hints(), qo_rewrite_like_for_index_scan(), qo_rewrite_one_like_term(), qo_rewrite_subqueries(), qo_set_value_to_range_list(), qo_term_free(), replace_names_alter_chg_attr(), select_delete_list(), update_check_for_constraints(), and update_real_class().
PT_NODE* parser_get_tree_list_diff (PARSER_CONTEXT * parser, PT_NODE * list1, PT_NODE * list2)
Definition at line 1175 of file parse_tree_cl.c.
References CAST_POINTER_TO_NODE, parser_node::next, NULL, parser_append_node(), and pt_point().
Referenced by pt_get_mvcc_reev_range_data(), and pt_make_prefix_index_data_filter().
void parser_init_func_vectors (void)
Definition at line 16739 of file parse_tree_cl.c.
References pt_apply_f, pt_init_apply_f(), pt_init_f, pt_init_init_f(), pt_init_print_f(), and pt_print_f.
Referenced by parser_create_parser().
PT_NODE* parser_init_node (PT_NODE * node, PT_NODE_TYPE node_type)
Definition at line 2174 of file parse_tree_cl.c.
References assert, parser_node::buffer_pos, parser_node::node_type, NULL, parser_id, parser_node::parser_id, pt_init_f, PT_LAST_NODE_NUMBER, PT_TYPE_NONE, and parser_node::type_enum.
Referenced by mq_fetch_expression_for_real_class_update(), mq_fetch_one_real_class_get_cache(), mq_get_attribute(), mq_is_updatable_att(), mq_is_updatable_local(), mq_oid(), mq_update_attribute(), parser_new_node(), and pt_bind_set_type().
PT_NODE* parser_new_node (PARSER_CONTEXT * parser, PT_NODE_TYPE node_type)
Definition at line 2153 of file parse_tree_cl.c.
References g_query_string, g_query_string_len, parser_create_node(), parser_init_node(), pt_parser_line_col(), parser_node::sql_user_text, and parser_node::sql_user_text_len.
Referenced by build_graph_for_entity(), copy_node_in_tree_pre(), create_select_to_insert_into(), do_create_odku_stmt(), do_create_partition(), do_replace_names_for_insert_values_pre(), fill_in_insert_default_function_arguments(), meth_add_conj(), meth_gen_as_attr_list(), meth_grab_conj(), meth_make_unique_range_var(), meth_translate_spec(), mq_bump_order_dep_corr_lvl_pre(), mq_class_lambda(), mq_derived_path(), mq_fetch_subqueries(), mq_invert_assign(), mq_make_derived_spec(), mq_new_spec(), mq_push_dot_in_query(), mq_rewrite_aggregate_as_derived(), mq_rewrite_order_dependent_query(), mq_rewrite_query_as_derived(), mq_rewrite_vclass_spec_as_derived(), mq_translate_insert(), parser_generate_xasl(), parser_generate_xasl_proc(), pt_add_type_to_set(), pt_and(), pt_append_omitted_on_update_expr_assignments(), pt_attr_check_default_cs_coll(), pt_bind_helper(), pt_check_analytic_function(), pt_check_assignments(), pt_check_default_vclass_query_spec(), pt_check_group_concat_order_by(), pt_check_hint(), pt_check_order_by(), pt_check_union_type_compatibility_of_values_query(), pt_coerce_node_collation(), pt_coerce_range_expr_arguments(), pt_compare_bounds_to_value(), pt_compile_trigger_stmt(), pt_convert_to_logical_expr(), pt_create_delete_stmt(), pt_create_param_for_value(), pt_create_pt_expr_and_node(), pt_create_pt_expr_equal_node(), pt_create_pt_name(), pt_dbval_to_value(), pt_derive_attribute(), pt_domain_to_data_type(), pt_dup_key_update_stmt(), pt_entity(), pt_eval_expr_type(), pt_eval_type(), pt_evaluate_tree_internal(), pt_expand_analytic_node(), pt_expand_external_path(), pt_expr_to_sort_spec(), pt_expression(), pt_filter_pseudo_specs(), pt_find_attr_in_class_list(), pt_find_omitted_default_expr(), pt_fix_buildlist_aggregate_cume_dist_percent_rank(), pt_fix_enumeration_comparison(), pt_fix_interpolation_aggregate_function_order_by(), pt_fold_const_expr(), pt_fold_union(), pt_gen_isnull_preds(), pt_get_attributes(), pt_get_object_data_type(), pt_get_resolution(), pt_insert_conjunct(), pt_insert_entity(), pt_insert_value(), pt_invert(), pt_limit_to_numbering_expr(), pt_make_cast_with_compatible_info(), pt_make_collation_expr_node(), pt_make_collection_type_subquery_node(), pt_make_dotted_identifier_internal(), pt_make_field_key_type_expr_node(), pt_make_field_type_expr_node(), pt_make_integer_value(), pt_make_method_call(), pt_make_outer_select_for_show_columns(), pt_make_outer_select_for_show_stmt(), pt_make_pred_term_is(), pt_make_prim_data_type(), pt_make_prim_data_type_fortonum(), pt_make_query_show_collation(), pt_make_query_show_columns(), pt_make_query_show_create_table(), pt_make_query_show_create_view(), pt_make_query_show_grants(), pt_make_query_show_index(), pt_make_query_show_table(), pt_make_query_show_trace(), pt_make_query_showstmt(), pt_make_query_user_groups(), pt_make_select_count_star(), pt_make_sort_spec_with_identifier(), pt_make_sort_spec_with_number(), pt_make_string_value(), pt_must_have_exposed_name(), pt_name(), pt_negate_expr(), pt_node_list(), pt_node_to_enumeration_expr(), pt_object_to_data_type(), pt_point(), pt_query_to_set_table(), pt_record_error(), pt_record_warning(), pt_register_orphan(), pt_register_orphan_db_value(), pt_resolve_default_value(), pt_resolve_object(), pt_resolve_vclass_args(), pt_rewrite_set_eq_set(), pt_select_list_to_one_col(), pt_set_default_data_type(), pt_set_orderby_for_sort_limit_plan(), pt_set_update_object(), pt_sm_attribute_default_value_to_node(), pt_spec_to_oid_attr(), pt_table_option(), pt_to_aggregate_node(), pt_to_analytic_node(), pt_to_constraint_pred(), pt_to_false_subquery(), pt_to_list_key(), pt_to_merge_insert_query(), pt_to_merge_update_query(), pt_to_odku_info(), pt_to_pred_expr_local_with_arg(), pt_to_range_key(), pt_to_rangelist_key(), pt_to_regu_variable(), pt_to_single_key(), pt_to_upd_del_query(), pt_tuple_value(), pt_type_cast_vclass_query_spec_column(), pt_type_generic_func(), pt_union(), pt_union_compatible(), pt_upd_domain_info(), pt_where_type(), pt_where_type_keep_true(), pt_wrap_collection_with_cast_op(), pt_wrap_with_cast_op(), qo_analyze_path_join(), qo_apply_range_intersection(), qo_construct_new_set(), qo_convert_to_range_helper(), qo_find_like_rewrite_bound(), qo_get_orderby_num_upper_bound_node(), qo_make_new_derived_tblspec(), qo_plan_compute_iscan_sort_list(), qo_reduce_comp_pair_terms(), qo_reduce_order_by(), qo_reduce_order_by_for(), qo_rewrite_subqueries(), and qo_set_value_to_range_list().
PT_NODE** parser_parse_file (PARSER_CONTEXT * parser, FILE * file)
Definition at line 1832 of file parse_tree_cl.c.
References parser_context::casecmp, parser_context::column, dbcs_get_next(), parser_context::dont_collect_exec_stats, fgetin(), parser_context::file, parser_context::flag, intl_identifier_casecmp(), parser_context::is_in_and_list, lang_charset(), LANG_VARIABLE_CHARSET, parser_context::line, parser_context::next_byte, parser_context::next_char, parser_context::num_plan_trace, parser_main(), prm_get_bool_value(), PRM_ID_QUERY_TRACE, PT_CLEAR_JMP_ENV, PT_SET_JMP_ENV, parser_context::query_trace, parser_context::stack_top, parser_context::strings_have_no_escapes, and pt_lambda_arg::tree.
Referenced by db_open_file(), and db_open_file_name().
PT_NODE** parser_parse_string (PARSER_CONTEXT * parser, const char * buffer)
Definition at line 1708 of file parse_tree_cl.c.
References parser_parse_string_with_escapes().
Referenced by emit_query_specs(), emit_query_specs_has_using_index(), mq_get_expression(), mq_virtual_queries(), parser_parse_string_use_sys_charset(), pt_check_alter_partition(), pt_get_proxy_spec_name(), pt_make_query_show_exec_stats(), pt_make_query_show_exec_stats_all(), and pt_string_to_db_domain().
PT_NODE** parser_parse_string_use_sys_charset (PARSER_CONTEXT * parser, const char * buffer)
Definition at line 1690 of file parse_tree_cl.c.
References lang_set_parser_use_client_charset(), NULL, and parser_parse_string().
Referenced by db_validate_query_spec(), do_recreate_filter_index_constr(), do_recreate_func_index_constr(), mq_translate_subqueries(), pt_check_cyclic_reference_in_view_spec(), pt_compile_trigger_stmt(), pt_fix_first_term_func_index_for_iss(), pt_make_query_show_exec_stats(), and pt_make_query_show_exec_stats_all().
PT_NODE** parser_parse_string_with_escapes (PARSER_CONTEXT * parser, const char * buffer, const bool strings_have_no_escapes)
Definition at line 1721 of file parse_tree_cl.c.
References parser_context::buffer, buffgetin(), parser_context::casecmp, parser_context::column, dbcs_get_next(), parser_context::dont_collect_exec_stats, parser_context::flag, parser_context::input_buffer_length, parser_context::input_buffer_position, intl_identifier_casecmp(), lang_charset(), LANG_VARIABLE_CHARSET, parser_context::line, parser_context::next_byte, parser_context::next_char, parser_context::num_plan_trace, parser_context::original_buffer, parser_main(), prm_get_bool_value(), PRM_ID_QUERY_TRACE, PT_CLEAR_JMP_ENV, PT_SET_JMP_ENV, parser_context::query_trace, parser_context::stack_top, parser_context::strings_have_no_escapes, and pt_lambda_arg::tree.
Referenced by db_open_buffer_local(), mq_get_expression(), and parser_parse_string().
char* parser_print_function_index_expr (PARSER_CONTEXT * parser, const PT_NODE * expr)
Definition at line 2724 of file parse_tree_cl.c.
References assert, parser_context::custom_print, parser_print_tree_with_quotes(), PT_CHARSET_COLLATE_FULL, PT_FORCE_ORIGINAL_TABLE_NAME, and PT_IS_EXPR_NODE.
Referenced by build_query_graph_function_index(), lookup_seg(), and pt_mark_function_index_expression().
char* parser_print_tree (PARSER_CONTEXT * parser, const PT_NODE * node)
Definition at line 2627 of file parse_tree_cl.c.
References parser_context::custom_print, free_and_init, NULL, parser_print_user(), pt_append_nulstring(), pt_print_bytes(), PT_PRINT_DIFFERENT_SYSTEM_PARAMETERS, PT_PRINT_USER, PT_QUERY_STRING_USER_TEXT, and sysprm_print_parameters_for_qry_string().
Referenced by do_check_internal_statements(), do_run_update_query_for_new_default_expression_fields(), mq_check_using_index(), parser_generate_do_stmt_xasl(), parser_generate_xasl(), pt_check_constraint(), pt_check_create_entity(), pt_check_group_concat_order_by(), pt_check_order_by(), pt_check_single_valued_node(), pt_check_union_type_compatibility_of_values_query(), pt_compare_sort_spec_expr(), pt_evaluate_db_value_expr(), pt_get_attr_name(), pt_get_one_tuple_from_list_id(), pt_plan_query(), pt_plan_schema(), pt_short_print(), pt_to_pos_descr(), pt_to_pos_descr_groupby(), pt_to_regu_variable(), pt_to_upd_del_query(), pt_transform_cnf_post(), qo_term_dump(), qo_term_string(), qo_top_plan_print_json(), and qo_top_plan_print_text().
char* parser_print_tree_list (PARSER_CONTEXT * parser, const PT_NODE * node)
Definition at line 2745 of file parse_tree_cl.c.
References NULL, and pt_print_bytes_l().
Referenced by mq_translate_tree(), pt_short_print_l(), qo_scan_fprint(), and qo_scan_info().
char* parser_print_tree_with_quotes (PARSER_CONTEXT * parser, const PT_NODE * node)
Definition at line 2693 of file parse_tree_cl.c.
References parser_context::custom_print, NULL, pt_print_bytes(), and PT_PRINT_QUOTES.
Referenced by add_query_to_virtual_class(), do_alter_one_clause_with_template(), get_activity_info(), parser_print_function_index_expr(), pt_node_to_function_index(), pt_node_to_partition_info(), and pt_print_query_spec_no_list().
static int parser_print_user (char * user_text, int len) static
Definition at line 2671 of file parse_tree_cl.c.
References db_get_user(), NULL, db_identifier::pageid, db_identifier::slotid, db_identifier::volid, and ws_identifier().
Referenced by parser_print_tree().
PT_NODE* parser_reinit_node (PT_NODE * node)
Definition at line 2200 of file parse_tree_cl.c.
References assert, parser_node::buffer_pos, parser_node::cache_time, parser_node::column_number, parser_node::line_number, parser_node::node_type, parser_id, parser_node::parser_id, pt_init_f, PT_LAST_NODE_NUMBER, PT_TYPE_NONE, parser_node::sql_user_text, parser_node::sql_user_text_len, and parser_node::type_enum.
Referenced by pt_check_union_type_compatibility_of_values_query(), pt_resolve_star(), pt_select_list_to_one_col(), and pt_to_outlist().
PT_NODE* parser_walk_leaves (PARSER_CONTEXT * parser, PT_NODE * node, PT_NODE_WALK_FUNCTION pre_function, void * pre_argument, PT_NODE_WALK_FUNCTION post_function, void * post_argument)
Definition at line 926 of file parse_tree_cl.c.
References pt_walk_arg::continue_walk, parser_node::node_type, NULL, parser_node::or_next, parser, pt_walk_arg::post_argument, pt_walk_arg::post_function, pt_walk_arg::pre_argument, pt_walk_arg::pre_function, pt_apply_f, PT_CONTINUE_WALK, PT_LAST_NODE_NUMBER, and pt_walk_private().
Referenced by get_local_subqueries(), meth_bump_corr_pre(), meth_create_method_list(), meth_find_last_entity(), meth_find_outside_refs(), meth_replace_call(), meth_translate_spec(), parser_free_subtrees(), pt_bind_names(), pt_check_order_by(), pt_make_method_call(), pt_pushable_query_in_pos(), pt_sargable_term(), pt_tag_term_with_id(), and pt_to_uncorr_subquery_list().
PT_NODE* parser_walk_tree (PARSER_CONTEXT * parser, PT_NODE * node, PT_NODE_WALK_FUNCTION pre_function, void * pre_argument, PT_NODE_WALK_FUNCTION post_function, void * post_argument)
Definition at line 973 of file parse_tree_cl.c.
References pt_walk_arg::continue_walk, NULL, pt_walk_arg::post_argument, pt_walk_arg::post_function, pt_walk_arg::pre_argument, pt_walk_arg::pre_function, PT_CONTINUE_WALK, and pt_walk_private().
Referenced by compile_trigger_activity(), db_can_execute_statement_with_autocommit(), db_number_of_output_markers(), do_check_internal_statements(), do_evaluate_insert_values(), do_execute_select(), do_execute_session_statement(), do_insert_template(), do_recreate_filter_index_constr(), do_recreate_func_index_constr(), emit_query_specs(), get_term_subqueries(), insert_local(), insert_rewrite_names_in_value_clauses(), insert_subquery_results(), is_server_insert_allowed(), make_sort_limit_proc(), meth_bump_correlation_level(), meth_copy_hierarchical_expr_to_list(), meth_create_method_list(), meth_find_hierarchical_in_method_list(), meth_grab_cnf_conj(), meth_grab_conj(), meth_push_conjuncts(), meth_refs_to_scope(), meth_replace_hierarchical_exprs(), meth_replace_method_calls(), meth_translate(), meth_translate_helper(), meth_translate_select(), meth_translate_spec(), mq_bump_correlation_level(), mq_bump_order_dep_corr_lvl(), mq_class_lambda(), mq_clear_ids(), mq_copypush_sargable_terms_helper(), mq_derived_path(), mq_evaluate_expression(), mq_evaluate_expression_having_serial(), mq_fix_derived(), mq_get_references_node(), mq_has_class_methods_corr_subqueries(), mq_is_pushable_subquery(), mq_is_referenced(), mq_lambda(), mq_mark_location(), mq_new_spec(), mq_oid(), mq_optimize(), mq_path_name_lambda(), mq_path_spec_lambda(), mq_push_path(), mq_rename_resolved(), mq_reset_ids(), mq_reset_ids_and_references_helper(), mq_reset_ids_in_methods(), mq_reset_ids_in_statement(), mq_reset_select_specs(), mq_reset_spec_ids(), mq_reset_specs_from_column(), mq_resolve_insert_statement(), mq_rewrite_agg_names(), mq_rewrite_aggregate_as_derived(), mq_set_references_local(), mq_substitute_path(), mq_substitute_select_in_statement(), mq_translate_helper(), mq_translate_insert(), mq_translate_subqueries(), parser_copy_tree(), parser_copy_tree_list(), parser_free_tree(), parser_generate_xasl(), pt_bind_names(), pt_bind_names_in_cte(), pt_bind_names_merge_insert(), pt_bind_names_merge_update(), pt_bind_names_post(), pt_bind_scope(), pt_bind_values_to_hostvars(), pt_build_do_stmt_aptr_list(), pt_check_alter_partition(), pt_check_create_view(), pt_check_cyclic_reference_in_view_spec(), pt_check_data_default(), pt_check_drop(), pt_check_filter_index_expr(), pt_check_for_update_clause(), pt_check_function_index_expr(), pt_check_grant_revoke(), pt_check_partitions(), pt_check_single_valued_node(), pt_check_sub_insert(), pt_check_truncate(), pt_check_vacuum(), pt_check_vclass_query_spec(), pt_check_with_info(), pt_check_xaction_list(), pt_class_pre_fetch(), pt_cnf(), pt_exec_trigger_stmt(), pt_expand_isnull_preds(), pt_expand_isnull_preds_helper(), pt_filter_pseudo_specs(), pt_find_aggregate_analytic_in_where(), pt_find_aggregate_functions_pre(), pt_find_id(), pt_flat_spec_pre(), pt_get_all_json_table_attributes_and_types(), pt_get_parameters(), pt_get_resolution(), pt_has_aggregate(), pt_has_analytic(), pt_has_inst_or_orderby_num(), pt_has_modified_class(), pt_has_parameters(), pt_has_reev_in_subquery(), pt_host_info(), pt_is_filtering_expression(), pt_is_filtering_predicate(), pt_is_spec_referenced(), pt_lambda_with_arg(), pt_mark_group_having_pt_name(), pt_quick_resolve_names(), pt_replace_names_in_update_values(), pt_resolve_cte_specs(), pt_resolve_names(), pt_semantic_check_local(), pt_semantic_type(), pt_set_connect_by_operator_node_etc(), pt_set_iscycle_node_etc(), pt_set_isleaf_node_etc(), pt_set_level_node_etc(), pt_set_numbering_node_etc(), pt_set_qprior_node_etc(), pt_split_access_if_instnum(), pt_split_delete_stmt(), pt_split_hash_attrs(), pt_split_hash_attrs_for_HQ(), pt_split_having_grbynum(), pt_split_if_instnum(), pt_statement_have_methods(), pt_table_compatible(), pt_to_aggregate(), pt_to_buildlist_proc(), pt_to_corr_subquery_list(), pt_to_insert_xasl(), pt_to_merge_update_query(), pt_to_pred_expr_with_arg(), pt_transform_cnf_post(), pt_uncorr_pre(), pt_validate_query_spec(), qo_analyze_path_join(), qo_analyze_term(), qo_check_condition_yields_null(), qo_check_nullable_expr_with_spec(), qo_expr_segs(), qo_optimize_helper(), qo_optimize_queries(), qo_reduce_equality_terms(), qo_reduce_order_by(), qo_rewrite_innerjoin(), qo_rewrite_like_terms(), qo_rewrite_oid_equality(), qo_rewrite_outerjoin(), qo_rewrite_subqueries(), qo_validate(), qo_validate_index_attr_notnull(), and set_seg_expr().
PARSER_VARCHAR* pt_append_name (const PARSER_CONTEXT * parser, PARSER_VARCHAR * string, const char * name)
Definition at line 5208 of file parse_tree_cl.c.
References parser_context::custom_print, lang_check_identifier(), pt_append_nulstring(), pt_is_keyword(), PT_PRINT_QUOTES, PT_SUPPRESS_QUOTES, and strlen.
Referenced by pt_print_bytes_alias(), pt_print_insert(), and pt_print_name().
static PARSER_VARCHAR * pt_append_quoted_string (const PARSER_CONTEXT * parser, PARSER_VARCHAR * buf, const char * str, size_t str_length) static
Definition at line 5244 of file parse_tree_cl.c.
References i, MAX_STRING_SEGMENT_LENGTH, pt_append_bytes(), and pt_append_nulstring().
Referenced by pt_print_value().
static PARSER_VARCHAR * pt_append_string_prefix (const PARSER_CONTEXT * parser, PARSER_VARCHAR * buf, const PT_NODE * value) static
Definition at line 5284 of file parse_tree_cl.c.
References parser_node::info, pt_append_nulstring(), pt_value_info::string_type, and pt_statement_info::value.
Referenced by pt_print_value().
static PT_NODE * pt_apply_alter (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 5423 of file parse_tree_cl.c.
References pt_statement_info::alter, pt_alter_info::alter_clause, pt_alter_info::attr_mthd, pt_alter_info::ch_attr_def, pt_alter_info::code, pt_alter_info::constraint_list, pt_alter_info::create_index, pt_alter_info::entity_name, parser_node::info, pt_alter_info::internal_stmts, p, pt_alter_info::partition, PT_ADD_ATTR_MTHD, PT_ADD_HASHPARTITION, PT_ADD_PARTITION, PT_ADD_QUERY, PT_ALTER_DEFAULT, PT_ANALYZE_PARTITION, PT_APPLY_PARTITION, PT_APPLY_WALK, PT_CHANGE_ATTR, PT_COALESCE_PARTITION, PT_DROP_ATTR_MTHD, PT_DROP_PARTITION, PT_DROP_QUERY, PT_MODIFY_ATTR_MTHD, PT_MODIFY_DEFAULT, PT_MODIFY_QUERY, PT_PROMOTE_PARTITION, PT_REMOVE_PARTITION, PT_RENAME_ATTR_MTHD, PT_RENAME_ENTITY, PT_REORG_PARTITION, PT_RESET_QUERY, pt_alter_info::query, pt_alter_info::rename, pt_alter_info::resolution_list, pt_alter_info::sup_class_list, and pt_alter_info::super.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_alter_index (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 6146 of file parse_tree_cl.c.
References pt_index_info::column_names, pt_index_info::function_expr, pt_statement_info::index, pt_index_info::indexed_class, parser_node::info, p, PT_APPLY_WALK, and pt_index_info::where.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_alter_serial (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 8075 of file parse_tree_cl.c.
References pt_serial_info::increment_val, parser_node::info, pt_serial_info::max_val, pt_serial_info::min_val, p, PT_APPLY_WALK, and pt_statement_info::serial.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_alter_trigger (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 6310 of file parse_tree_cl.c.
References pt_statement_info::alter_trigger, parser_node::info, p, PT_APPLY_WALK, pt_alter_trigger_info::trigger_priority, and pt_alter_trigger_info::trigger_spec_list.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_alter_user (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 6261 of file parse_tree_cl.c.
References pt_statement_info::alter_user, parser_node::info, p, pt_alter_user_info::password, PT_APPLY_WALK, and pt_alter_user_info::user_name.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_attach (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 6382 of file parse_tree_cl.c.
References p.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_attr_def (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 6413 of file parse_tree_cl.c.
References pt_statement_info::attr_def, pt_attr_def_info::attr_name, pt_attr_def_info::auto_increment, pt_attr_def_info::data_default, parser_node::info, pt_attr_def_info::ordering_info, p, and PT_APPLY_WALK.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_attr_ordering (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 6640 of file parse_tree_cl.c.
References pt_attr_ordering_info::after, pt_statement_info::attr_ordering, parser_node::info, p, and PT_APPLY_WALK.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_auth_cmd (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 6681 of file parse_tree_cl.c.
References pt_auth_cmd_info::attr_mthd_list, pt_statement_info::auth_cmd, parser_node::info, p, and PT_APPLY_WALK.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_auto_increment (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 12643 of file parse_tree_cl.c.
References p.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_check_option (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 6731 of file parse_tree_cl.c.
References pt_statement_info::check_option, pt_check_option_info::expr, parser_node::info, p, and PT_APPLY_WALK.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_commit_work (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 6764 of file parse_tree_cl.c.
References p.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_constraint (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 15885 of file parse_tree_cl.c.
References pt_foreign_key_info::attrs, pt_constraint_info::check, pt_statement_info::constraint, pt_constraint_info::foreign_key, parser_node::info, pt_constraint_info::not_null, p, pt_constraint_info::primary_key, PT_APPLY_WALK, PT_CONSTRAIN_CHECK, PT_CONSTRAIN_FOREIGN_KEY, PT_CONSTRAIN_NOT_NULL, PT_CONSTRAIN_NULL, PT_CONSTRAIN_PRIMARY_KEY, PT_CONSTRAIN_UNIQUE, PT_CONSTRAIN_UNKNOWN, pt_foreign_key_info::referenced_attrs, pt_foreign_key_info::referenced_class, pt_constraint_info::type, pt_constraint_info::un, and pt_constraint_info::unique.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_create_entity (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 6799 of file parse_tree_cl.c.
References pt_create_entity_info::as_query_list, pt_create_entity_info::attr_def_list, pt_create_entity_info::class_attr_def_list, pt_create_entity_info::constraint_list, pt_statement_info::create_entity, pt_create_entity_info::create_index, pt_create_entity_info::create_like, pt_create_entity_info::create_select, pt_create_entity_info::entity_name, parser_node::info, pt_create_entity_info::internal_stmts, pt_create_entity_info::method_def_list, pt_create_entity_info::method_file_list, pt_create_entity_info::object_id_list, p, pt_create_entity_info::partition_info, PT_APPLY_WALK, pt_create_entity_info::resolution_list, pt_create_entity_info::supclass_list, and pt_create_entity_info::update.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_create_index (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 7091 of file parse_tree_cl.c.
References pt_index_info::column_names, pt_index_info::function_expr, pt_statement_info::index, pt_index_info::index_name, pt_index_info::indexed_class, parser_node::info, p, pt_index_info::prefix_length, PT_APPLY_WALK, and pt_index_info::where.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_create_serial (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 8057 of file parse_tree_cl.c.
References pt_serial_info::increment_val, parser_node::info, pt_serial_info::max_val, pt_serial_info::min_val, p, PT_APPLY_WALK, pt_statement_info::serial, and pt_serial_info::start_val.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_create_trigger (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 7290 of file parse_tree_cl.c.
References pt_statement_info::create_trigger, parser_node::info, p, PT_APPLY_WALK, pt_create_trigger_info::trigger_action, pt_create_trigger_info::trigger_condition, pt_create_trigger_info::trigger_event, pt_create_trigger_info::trigger_name, pt_create_trigger_info::trigger_priority, and pt_create_trigger_info::trigger_reference.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_create_user (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 7229 of file parse_tree_cl.c.
References pt_statement_info::create_user, pt_create_user_info::groups, parser_node::info, pt_create_user_info::members, p, pt_create_user_info::password, PT_APPLY_WALK, and pt_create_user_info::user_name.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_cte (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 16525 of file parse_tree_cl.c.
References pt_statement_info::cte, parser_node::info, pt_cte_info::non_recursive_part, p, PT_APPLY_WALK, and pt_cte_info::recursive_part.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_data_default (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 8107 of file parse_tree_cl.c.
References pt_statement_info::data_default, pt_data_default_info::default_value, parser_node::info, p, and PT_APPLY_WALK.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_datatype (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 8172 of file parse_tree_cl.c.
References pt_statement_info::data_type, pt_data_type_info::entity, pt_data_type_info::enumeration, parser_node::info, p, PT_APPLY_WALK, and pt_data_type_info::virt_data_type.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_delete (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 8344 of file parse_tree_cl.c.
References pt_delete_info::cursor_name, pt_statement_info::delete_, parser_node::info, pt_delete_info::internal_stmts, pt_delete_info::limit, pt_delete_info::ordered_hint, p, PT_APPLY_WALK, pt_delete_info::search_cond, pt_delete_info::spec, pt_delete_info::target_classes, pt_delete_info::use_idx_hint, pt_delete_info::use_merge_hint, pt_delete_info::use_nl_hint, pt_delete_info::using_index, pt_delete_info::waitsecs_hint, and pt_delete_info::with.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_difference (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 8577 of file parse_tree_cl.c.
References pt_union_info::arg1, pt_union_info::arg2, parser_node::info, pt_query_info::into_list, pt_query_info::order_by, pt_query_info::orderby_for, p, PT_APPLY_WALK, pt_query_info::q, pt_statement_info::query, pt_query_info::union_, and pt_query_info::with.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_do (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 7608 of file parse_tree_cl.c.
References pt_statement_info::do_, pt_do_info::expr, parser_node::info, p, and PT_APPLY_WALK.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_dot (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 8666 of file parse_tree_cl.c.
References pt_dot_info::arg1, pt_dot_info::arg2, pt_statement_info::dot, parser_node::info, p, PT_APPLY_WALK, and pt_dot_info::selector.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_drop (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 8715 of file parse_tree_cl.c.
References pt_statement_info::drop, parser_node::info, pt_drop_info::internal_stmts, p, PT_APPLY_WALK, and pt_drop_info::spec_list.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_drop_index (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 8762 of file parse_tree_cl.c.
References pt_index_info::column_names, pt_index_info::function_expr, pt_statement_info::index, pt_index_info::indexed_class, parser_node::info, p, PT_APPLY_WALK, and pt_index_info::where.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_drop_serial (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 8092 of file parse_tree_cl.c.
References p.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_drop_session_variables (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 15327 of file parse_tree_cl.c.
References pt_statement_info::drop_session_var, parser_node::info, p, PT_APPLY_WALK, and pt_drop_session_var_info::variables.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_drop_trigger (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 8873 of file parse_tree_cl.c.
References pt_statement_info::drop_trigger, parser_node::info, p, PT_APPLY_WALK, and pt_drop_trigger_info::trigger_spec_list.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_drop_user (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 8839 of file parse_tree_cl.c.
References pt_statement_info::drop_user, parser_node::info, p, PT_APPLY_WALK, and pt_drop_user_info::user_name.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_drop_variable (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 8907 of file parse_tree_cl.c.
References pt_statement_info::drop_variable, parser_node::info, p, PT_APPLY_WALK, and pt_drop_variable_info::var_names.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_error_msg (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 15839 of file parse_tree_cl.c.
References p.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_evaluate (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 9221 of file parse_tree_cl.c.
References pt_statement_info::evaluate, pt_evaluate_info::expression, parser_node::info, pt_evaluate_info::into_var, p, and PT_APPLY_WALK.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_event_object (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 9262 of file parse_tree_cl.c.
References pt_event_object_info::correlation_name, pt_event_object_info::event_object, pt_statement_info::event_object, parser_node::info, p, and PT_APPLY_WALK.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_event_spec (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 9292 of file parse_tree_cl.c.
References pt_statement_info::event_spec, pt_event_spec_info::event_target, parser_node::info, p, and PT_APPLY_WALK.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_event_target (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 9329 of file parse_tree_cl.c.
References pt_event_target_info::attribute, pt_event_target_info::class_name, pt_statement_info::event_target, parser_node::info, p, and PT_APPLY_WALK.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_execute_trigger (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 9371 of file parse_tree_cl.c.
References pt_statement_info::execute_trigger, parser_node::info, p, PT_APPLY_WALK, and pt_execute_trigger_info::trigger_spec_list.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_expr (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 9405 of file parse_tree_cl.c.
References pt_expr_info::arg1, pt_expr_info::arg2, pt_expr_info::arg3, pt_expr_info::cast_type, pt_statement_info::expr, parser_node::info, p, PT_APPLY_WALK, and pt_expr_info::value.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_file_path (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 11728 of file parse_tree_cl.c.
References p.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_function (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 11763 of file parse_tree_cl.c.
References pt_function_info::analytic, pt_function_info::arg_list, pt_function_info::default_value, pt_function_info::expanded_list, pt_statement_info::function, parser_node::info, pt_function_info::is_analytic, pt_function_info::offset, pt_function_info::order_by, p, pt_function_info::partition_by, pt_function_info::percentile, and PT_APPLY_WALK.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_get_opt_lvl (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 12049 of file parse_tree_cl.c.
References pt_get_opt_lvl_info::args, pt_statement_info::get_opt_lvl, parser_node::info, pt_get_opt_lvl_info::into_var, p, and PT_APPLY_WALK.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_get_stats (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 15137 of file parse_tree_cl.c.
References pt_get_stats_info::args, pt_get_stats_info::class_, pt_statement_info::get_stats, parser_node::info, pt_get_stats_info::into_var, p, and PT_APPLY_WALK.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_get_trigger (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 12109 of file parse_tree_cl.c.
References pt_statement_info::get_trigger, parser_node::info, pt_get_trigger_info::into_var, p, and PT_APPLY_WALK.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_get_xaction (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 12148 of file parse_tree_cl.c.
References pt_statement_info::get_xaction, parser_node::info, pt_get_xaction_info::into_var, p, and PT_APPLY_WALK.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_grant (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 12187 of file parse_tree_cl.c.
References pt_grant_info::auth_cmd_list, pt_statement_info::grant, parser_node::info, p, PT_APPLY_WALK, pt_grant_info::spec_list, and pt_grant_info::user_list.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_host_var (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 12251 of file parse_tree_cl.c.
References p.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_insert (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 12336 of file parse_tree_cl.c.
References pt_insert_info::attr_list, parser_node::info, pt_statement_info::insert, pt_insert_info::internal_stmts, pt_insert_info::into_var, pt_insert_info::non_null_attrs, pt_insert_info::odku_assignments, pt_insert_info::odku_non_null_attrs, p, PT_APPLY_WALK, pt_insert_info::spec, pt_insert_info::value_clauses, pt_insert_info::waitsecs_hint, and pt_insert_info::where.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_insert_value (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 16465 of file parse_tree_cl.c.
References parser_node::info, pt_statement_info::insert_value, pt_insert_value_info::original_node, p, and PT_APPLY_WALK.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_intersection (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 12555 of file parse_tree_cl.c.
References pt_union_info::arg1, pt_union_info::arg2, parser_node::info, pt_query_info::into_list, pt_query_info::order_by, pt_query_info::orderby_for, p, PT_APPLY_WALK, pt_query_info::q, pt_statement_info::query, pt_query_info::union_, and pt_query_info::with.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_isolation_lvl (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 12685 of file parse_tree_cl.c.
References parser_node::info, pt_statement_info::isolation_lvl, pt_isolation_lvl_info::level, p, and PT_APPLY_WALK.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_json_table (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 17980 of file parse_tree_cl.c.
References pt_json_table_info::expr, parser_node::info, pt_statement_info::json_table_info, p, PT_APPLY_WALK, and pt_json_table_info::tree.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_json_table_column (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 18079 of file parse_tree_cl.c.
References parser_node::info, pt_statement_info::json_table_column_info, pt_json_table_column_info::name, p, and PT_APPLY_WALK.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_json_table_node (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 18015 of file parse_tree_cl.c.
References pt_json_table_node_info::columns, parser_node::info, pt_statement_info::json_table_node_info, pt_json_table_node_info::nested_paths, p, and PT_APPLY_WALK.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_kill (PARSER_CONTEXT * parser, PT_NODE * P, void * arg) static
Definition at line 16472 of file parse_tree_cl.c.
References p.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_merge (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 16259 of file parse_tree_cl.c.
References pt_merge_info::assignment, pt_merge_info::attr_list, pt_merge_info::check_where, pt_merge_info::class_where, pt_merge_info::del_search_cond, parser_node::info, pt_merge_info::insert, pt_merge_info::into, pt_statement_info::merge, p, PT_APPLY_WALK, pt_merge_info::search_cond, pt_merge_info::update, pt_merge_info::using_clause, pt_merge_info::value_clauses, and pt_merge_info::waitsecs_hint.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_method_call (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 12760 of file parse_tree_cl.c.
References pt_method_call_info::arg_list, parser_node::info, pt_statement_info::method_call, pt_method_call_info::method_name, pt_method_call_info::on_call_target, p, PT_APPLY_WALK, and pt_method_call_info::to_return_var.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_method_def (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 12811 of file parse_tree_cl.c.
References pt_method_def_info::function_name, parser_node::info, pt_method_def_info::method_args_list, pt_statement_info::method_def, pt_method_def_info::method_name, p, and PT_APPLY_WALK.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_name (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 12890 of file parse_tree_cl.c.
References pt_name_info::default_value, pt_name_info::indx_key_limit, parser_node::info, pt_statement_info::name, p, pt_name_info::path_correlation, and PT_APPLY_WALK.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_named_arg (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 16648 of file parse_tree_cl.c.
References parser_node::info, pt_named_arg_info::name, pt_statement_info::named_arg, p, PT_APPLY_WALK, and pt_named_arg_info::value.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_node_list (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 16218 of file parse_tree_cl.c.
References parser_node::info, pt_node_list_info::list, pt_statement_info::node_list, p, and PT_APPLY_WALK.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_partition (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 7688 of file parse_tree_cl.c.
References pt_partition_info::expr, pt_partition_info::hashsize, parser_node::info, p, pt_statement_info::partition, pt_partition_info::parts, PT_APPLY_WALK, PT_PARTITION_HASH, and pt_partition_info::type.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_parts (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 7753 of file parse_tree_cl.c.
References parser_node::info, pt_parts_info::name, p, pt_statement_info::parts, PT_APPLY_WALK, and pt_parts_info::values.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_pointer (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 16163 of file parse_tree_cl.c.
References pt_pointer_info::do_walk, parser_node::info, pt_pointer_info::node, p, pt_statement_info::pointer, and PT_APPLY_WALK.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_prepare (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 7455 of file parse_tree_cl.c.
References p.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_prepare_to_commit (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 13113 of file parse_tree_cl.c.
References p.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_query_trace (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 17917 of file parse_tree_cl.c.
References p.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_remove_trigger (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 13143 of file parse_tree_cl.c.
References parser_node::info, p, PT_APPLY_WALK, pt_statement_info::remove_trigger, and pt_remove_trigger_info::trigger_spec_list.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_rename (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 13177 of file parse_tree_cl.c.
References pt_rename_info::in_class, parser_node::info, pt_rename_info::new_name, pt_rename_info::old_name, p, PT_APPLY_WALK, and pt_statement_info::rename.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_rename_trigger (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 13229 of file parse_tree_cl.c.
References parser_node::info, pt_rename_trigger_info::new_name, pt_rename_trigger_info::old_name, p, PT_APPLY_WALK, and pt_statement_info::rename_trigger.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_resolution (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 13267 of file parse_tree_cl.c.
References pt_resolution_info::as_attr_mthd_name, pt_resolution_info::attr_mthd_name, parser_node::info, pt_resolution_info::of_sup_class_name, p, PT_APPLY_WALK, and pt_statement_info::resolution.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_revoke (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 13328 of file parse_tree_cl.c.
References pt_revoke_info::auth_cmd_list, parser_node::info, p, PT_APPLY_WALK, pt_statement_info::revoke, pt_revoke_info::spec_list, and pt_revoke_info::user_list.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_rollback_work (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 13374 of file parse_tree_cl.c.
References parser_node::info, p, PT_APPLY_WALK, pt_statement_info::rollback_work, and pt_rollback_work_info::save_name.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_savepoint (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 13412 of file parse_tree_cl.c.
References parser_node::info, p, PT_APPLY_WALK, pt_savepoint_info::save_name, and pt_statement_info::savepoint.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_scope (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 13446 of file parse_tree_cl.c.
References pt_scope_info::from, parser_node::info, p, PT_APPLY_WALK, pt_statement_info::scope, and pt_scope_info::stmt.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_select (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 13484 of file parse_tree_cl.c.
References pt_select_info::after_cb_filter, pt_select_info::check_where, pt_select_info::connect_by, pt_select_info::for_update, pt_select_info::from, pt_select_info::group_by, pt_select_info::having, pt_select_info::index_ls, pt_select_info::index_ss, parser_node::info, pt_query_info::into_list, pt_query_info::limit, pt_select_info::list, pt_query_info::order_by, pt_query_info::orderby_for, pt_select_info::ordered, p, PT_APPLY_WALK, pt_query_info::q, pt_query_info::qcache_hint, pt_statement_info::query, pt_query_info::select, pt_select_info::start_with, pt_select_info::use_idx, pt_select_info::use_merge, pt_select_info::use_nl, pt_select_info::using_index, pt_select_info::waitsecs_hint, pt_select_info::where, pt_query_info::with, and pt_select_info::with_increment.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_set_names (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 14223 of file parse_tree_cl.c.
References pt_set_names_info::charset_node, pt_set_names_info::collation_node, parser_node::info, p, PT_APPLY_WALK, and pt_statement_info::set_names.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_set_opt_lvl (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 14306 of file parse_tree_cl.c.
References parser_node::info, p, PT_APPLY_WALK, pt_statement_info::set_opt_lvl, and pt_set_opt_lvl_info::val.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_set_session_variables (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 15296 of file parse_tree_cl.c.
References pt_set_session_variable_info::assignments, parser_node::info, p, PT_APPLY_WALK, and pt_statement_info::set_variables.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_set_sys_params (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 14366 of file parse_tree_cl.c.
References parser_node::info, p, PT_APPLY_WALK, pt_statement_info::set_sys_params, and pt_set_sys_params_info::val.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_set_timezone (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 14240 of file parse_tree_cl.c.
References parser_node::info, p, PT_APPLY_WALK, pt_statement_info::set_timezone, and pt_set_timezone_info::timezone_node.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_set_trigger (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 14404 of file parse_tree_cl.c.
References parser_node::info, p, PT_APPLY_WALK, pt_statement_info::set_trigger, and pt_set_trigger_info::val.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_set_xaction (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 14503 of file parse_tree_cl.c.
References parser_node::info, p, PT_APPLY_WALK, pt_statement_info::set_xaction, and pt_set_xaction_info::xaction_modes.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_showstmt (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 14455 of file parse_tree_cl.c.
References parser_node::info, p, PT_APPLY_WALK, pt_showstmt_info::show_args, and pt_statement_info::showstmt.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_sort_spec (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 14537 of file parse_tree_cl.c.
References pt_sort_spec_info::expr, parser_node::info, p, PT_APPLY_WALK, and pt_statement_info::sort_spec.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_sp_parameter (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 7645 of file parse_tree_cl.c.
References p.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_spec (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 8941 of file parse_tree_cl.c.
References pt_spec_info::as_attr_list, pt_spec_info::cte_name, pt_spec_info::cte_pointer, pt_spec_info::derived_table, pt_spec_info::entity_name, pt_spec_info::except_list, pt_spec_info::flat_entity_list, parser_node::info, pt_spec_info::method_list, pt_spec_info::on_cond, p, pt_spec_info::partition, pt_spec_info::path_conjuncts, pt_spec_info::path_entities, PT_APPLY_WALK, pt_spec_info::range_var, pt_spec_info::referenced_attrs, and pt_statement_info::spec.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_stored_procedure (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 7374 of file parse_tree_cl.c.
References p.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_table_option (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 7508 of file parse_tree_cl.c.
References parser_node::info, p, PT_APPLY_WALK, pt_statement_info::table_option, and pt_table_option_info::val.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_timeout (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 14596 of file parse_tree_cl.c.
References parser_node::info, p, PT_APPLY_WALK, pt_statement_info::timeout, and pt_timeout_info::val.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_trigger_action (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 14646 of file parse_tree_cl.c.
References pt_trigger_action_info::expression, parser_node::info, p, PT_APPLY_WALK, pt_trigger_action_info::string, and pt_statement_info::trigger_action.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_trigger_spec_list (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 14696 of file parse_tree_cl.c.
References pt_trigger_spec_list_info::event_list, parser_node::info, p, PT_APPLY_WALK, pt_trigger_spec_list_info::trigger_name_list, and pt_statement_info::trigger_spec_list.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_truncate (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 7470 of file parse_tree_cl.c.
References parser_node::info, p, PT_APPLY_WALK, pt_truncate_info::spec, and pt_statement_info::truncate.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_tuple_value (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 16419 of file parse_tree_cl.c.
References parser_node::info, pt_tuple_value_info::name, p, PT_APPLY_WALK, and pt_statement_info::tuple_value.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_union_stmt (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 14730 of file parse_tree_cl.c.
References pt_union_info::arg1, pt_union_info::arg2, parser_node::info, pt_query_info::into_list, pt_query_info::limit, pt_query_info::order_by, pt_query_info::orderby_for, p, PT_APPLY_WALK, pt_query_info::q, pt_statement_info::query, pt_query_info::union_, and pt_query_info::with.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_update (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 14822 of file parse_tree_cl.c.
References pt_update_info::assignment, pt_update_info::check_where, pt_update_info::cursor_name, parser_node::info, pt_update_info::internal_stmts, pt_update_info::limit, pt_update_info::object_parameter, pt_update_info::order_by, pt_update_info::orderby_for, pt_update_info::ordered_hint, p, PT_APPLY_WALK, pt_update_info::search_cond, pt_update_info::spec, pt_statement_info::update, pt_update_info::use_idx_hint, pt_update_info::use_merge_hint, pt_update_info::use_nl_hint, pt_update_info::using_index, pt_update_info::waitsecs_hint, and pt_update_info::with.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_update_stats (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 15086 of file parse_tree_cl.c.
References pt_update_stats_info::class_list, parser_node::info, p, PT_APPLY_WALK, and pt_statement_info::update_stats.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_vacuum (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 17868 of file parse_tree_cl.c.
References assert, p, and PT_IS_VACUUM_NODE.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_value (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 15261 of file parse_tree_cl.c.
References pt_value_info::data_value, parser_node::info, p, PT_APPLY_WALK, PT_TYPE_MULTISET, PT_TYPE_SEQUENCE, PT_TYPE_SET, pt_data_value::set, parser_node::type_enum, and pt_statement_info::value.
Referenced by pt_init_apply_f().
static PT_NODE * pt_apply_with_clause (PARSER_CONTEXT * parser, PT_NODE * p, void * arg) static
Definition at line 16508 of file parse_tree_cl.c.
References pt_with_clause_info::cte_definition_list, parser_node::info, p, PT_APPLY_WALK, and pt_statement_info::with_clause.
Referenced by pt_init_apply_f().
int pt_check_set_count_set (PARSER_CONTEXT * parser, PT_NODE * arg1, PT_NODE * arg2)
Definition at line 4534 of file parse_tree_cl.c.
References pt_value_info::data_value, parser_node::info, MSGCAT_SEMANTIC_ATT_CNT_COL_CNT_NE, MSGCAT_SET_PARSER_SEMANTIC, parser_node::next, parser_node::node_type, pt_check_set_count_set(), PT_ERROR, PT_ERRORmf2, pt_get_expression_count(), pt_is_set_type, PT_VALUE, rc, pt_data_value::set, and pt_statement_info::value.
Referenced by pt_check_set_count_set().
static void pt_clean_tree_copy_info (PT_TREE_COPY_INFO * tree_copy_info) static
Definition at line 17967 of file parse_tree_cl.c.
References pt_tree_copy_info::cte_structures_list, pt_copy_cte_info::next, and NULL.
Referenced by parser_copy_tree(), and parser_copy_tree_list().
PT_NODE* pt_continue_walk (PARSER_CONTEXT * parser, PT_NODE * tree, void * arg, int * continue_walk)
Definition at line 1001 of file parse_tree_cl.c.
References PT_CONTINUE_WALK, and pt_lambda_arg::tree.
Referenced by do_evaluate_insert_values(), get_term_subqueries(), mq_clear_ids(), mq_evaluate_expression(), mq_evaluate_expression_having_serial(), mq_get_references_node(), mq_new_spec(), mq_path_name_lambda(), mq_rename_resolved(), mq_reset_ids_and_references_helper(), mq_rewrite_agg_names(), mq_set_references_local(), mq_substitute_path(), pt_bind_names(), pt_build_do_stmt_aptr_list(), pt_check_drop(), pt_check_grant_revoke(), pt_check_truncate(), pt_check_vacuum(), pt_check_with_info(), pt_filter_pseudo_specs(), pt_find_aggregate_functions_pre(), pt_flat_spec_pre(), pt_get_resolution(), pt_is_spec_referenced(), pt_resolve_names(), pt_set_numbering_node_etc(), pt_split_delete_stmt(), pt_table_compatible(), pt_to_aggregate(), pt_to_corr_subquery_list(), qo_expr_segs(), qo_optimize_helper(), qo_validate(), and set_seg_expr().
static DB_CURRENCY pt_currency_to_db (const PT_CURRENCY t) static
Definition at line 5302 of file parse_tree_cl.c.
References DB_CURRENCY_AUSTRALIAN_DOLLAR, DB_CURRENCY_BRASILIAN_REAL, DB_CURRENCY_BRITISH_POUND, DB_CURRENCY_BULGARIAN_LEV, DB_CURRENCY_CAMBODIAN_RIEL, DB_CURRENCY_CANADIAN_DOLLAR, DB_CURRENCY_CHINESE_RENMINBI, DB_CURRENCY_CROATIAN_KUNA, DB_CURRENCY_CZECH_KORUNA, DB_CURRENCY_DANISH_KRONE, DB_CURRENCY_DOLLAR, DB_CURRENCY_EURO, DB_CURRENCY_INDIAN_RUPEE, DB_CURRENCY_NORWEGIAN_KRONE, DB_CURRENCY_NULL, DB_CURRENCY_POLISH_ZLOTY, DB_CURRENCY_ROMANIAN_LEU, DB_CURRENCY_RUSSIAN_RUBLE, DB_CURRENCY_SERBIAN_DINAR, DB_CURRENCY_SWEDISH_KRONA, DB_CURRENCY_SWISS_FRANC, DB_CURRENCY_TL, DB_CURRENCY_VIETNAMESE_DONG, DB_CURRENCY_WON, DB_CURRENCY_YEN, PT_CURRENCY_AUSTRALIAN_DOLLAR, PT_CURRENCY_BRASILIAN_REAL, PT_CURRENCY_BRITISH_POUND, PT_CURRENCY_BULGARIAN_LEV, PT_CURRENCY_CAMBODIAN_RIEL, PT_CURRENCY_CANADIAN_DOLLAR, PT_CURRENCY_CHINESE_RENMINBI, PT_CURRENCY_CROATIAN_KUNA, PT_CURRENCY_CZECH_KORUNA, PT_CURRENCY_DANISH_KRONE, PT_CURRENCY_DOLLAR, PT_CURRENCY_EURO, PT_CURRENCY_INDIAN_RUPEE, PT_CURRENCY_NORWEGIAN_KRONE, PT_CURRENCY_POLISH_ZLOTY, PT_CURRENCY_ROMANIAN_LEU, PT_CURRENCY_RUSSIAN_RUBLE, PT_CURRENCY_SERBIAN_DINAR, PT_CURRENCY_SWEDISH_KRONA, PT_CURRENCY_SWISS_FRANC, PT_CURRENCY_TL, PT_CURRENCY_VIETNAMESE_DONG, PT_CURRENCY_WON, and PT_CURRENCY_YEN.
Referenced by pt_print_value().
static bool pt_expr_is_allowed_as_function_index (const PT_NODE * expr) static
Definition at line 17432 of file parse_tree_cl.c.
References assert, pt_statement_info::expr, parser_node::info, parser_node::node_type, NULL, pt_expr_info::op, PT_ABS, PT_ACOS, PT_ADD_MONTHS, PT_ADDDATE, PT_AES_DECRYPT, PT_AES_ENCRYPT, PT_ASIN, PT_ATAN, PT_ATAN2, PT_BIT_COUNT, PT_BIT_LENGTH, PT_CAST, PT_CEIL, PT_CHAR_LENGTH, PT_CHR, PT_COS, PT_COT, PT_CRC32, PT_DATE_ADD, PT_DATE_FORMAT, PT_DATE_SUB, PT_DATEDIFF, PT_DATEF, PT_DAYF, PT_DAYOFMONTH, PT_DAYOFWEEK, PT_DAYOFYEAR, PT_DEGREES, PT_EXP, PT_EXPR, PT_EXPR_INFO_CAST_COLL_MODIFIER, PT_EXPR_INFO_IS_FLAGED, PT_FLOOR, PT_FORMAT, PT_FROM_BASE64, PT_FROM_UNIXTIME, PT_FROMDAYS, PT_FUNCTION_HOLDER, PT_GREATEST, PT_HOURF, PT_IFNULL, PT_INET_ATON, PT_INET_NTOA, PT_INSTR, PT_LAST_DAY, PT_LEAST, PT_LEFT, PT_LN, PT_LOCATE, PT_LOG, PT_LOG10, PT_LOG2, PT_LOWER, PT_LPAD, PT_LTRIM, PT_MAKEDATE, PT_MAKETIME, PT_MD5, PT_MID, PT_MINUTEF, PT_MOD, PT_MODULUS, PT_MONTHF, PT_MONTHS_BETWEEN, PT_NULLIF, PT_NVL, PT_NVL2, PT_OCTET_LENGTH, PT_POSITION, PT_POWER, PT_QUARTERF, PT_RADIANS, PT_REPEAT, PT_REPLACE, PT_REVERSE, PT_RIGHT, PT_ROUND, PT_RPAD, PT_RTRIM, PT_SECONDF, PT_SECTOTIME, PT_SHA_ONE, PT_SHA_TWO, PT_SIN, PT_SQRT, PT_STR_TO_DATE, PT_STRCMP, PT_SUBDATE, PT_SUBSTRING, PT_SUBSTRING_INDEX, PT_TAN, PT_TIME_FORMAT, PT_TIMEDIFF, PT_TIMEF, PT_TIMESTAMP, PT_TIMETOSEC, PT_TO_BASE64, PT_TO_CHAR, PT_TO_DATE, PT_TO_DATETIME, PT_TO_DATETIME_TZ, PT_TO_NUMBER, PT_TO_TIME, PT_TO_TIMESTAMP, PT_TO_TIMESTAMP_TZ, PT_TODAYS, PT_TRANSLATE, PT_TRIM, PT_TRUNC, PT_TZ_OFFSET, PT_UNIX_TIMESTAMP, PT_UPPER, PT_WEEKDAY, PT_WEEKF, and PT_YEARF.
Referenced by pt_is_function_index_expr().
PT_NODE* pt_expr_to_sort_spec (PARSER_CONTEXT * parser, PT_NODE * expr)
Definition at line 17648 of file parse_tree_cl.c.
References pt_expr_info::arg1, pt_expr_info::arg2, pt_expr_info::arg3, pt_function_info::arg_list, pt_sort_spec_info::asc_or_desc, pt_sort_spec_info::expr, pt_statement_info::expr, pt_statement_info::function, parser_node::info, parser_node::next, NULL, pt_expr_info::op, parser_append_node(), parser_copy_tree(), parser_new_node(), PT_ASC, PT_FUNCTION_HOLDER, pt_function_index_skip_expr(), PT_INTERNAL_ERROR, PT_IS_EXPR_NODE, PT_IS_NAME_NODE, PT_SORT_SPEC, and pt_statement_info::sort_spec.
Referenced by pt_check_function_index_expr().
UINTPTR pt_find_id (PARSER_CONTEXT * parser, PT_NODE * tree_with_names, UINTPTR id)
Definition at line 1103 of file parse_tree_cl.c.
References pt_find_id_info::found, pt_find_id_info::id, NULL, parser_walk_tree(), and pt_find_id_node().
Referenced by mq_reset_spec_distr_subpath_post().
static PT_NODE * pt_find_id_node (PARSER_CONTEXT * parser, PT_NODE * tree, void * void_arg, int * continue_walk) static
Definition at line 692 of file parse_tree_cl.c.
References pt_find_id_info::found, pt_find_id_info::id, parser_node::info, pt_statement_info::name, parser_node::node_type, PT_NAME, PT_STOP_WALK, pt_name_info::spec_id, and pt_lambda_arg::tree.
Referenced by pt_find_id().
void pt_frob_error (PARSER_CONTEXT * parser, const PT_NODE * stmt, const char * fmt, ...)
Definition at line 2070 of file parse_tree_cl.c.
References parser_node::buffer_pos, parser_context::error_buffer, NULL, parser_context::original_buffer, pt_record_error(), SAFENUM, parser_context::statement_number, strlen, and vasprintf().
Referenced by pt_eval_function_type_new(), and pt_internal_error().
void pt_frob_warning (PARSER_CONTEXT * parser, const PT_NODE * stmt, const char * fmt, ...)
Definition at line 2040 of file parse_tree_cl.c.
References parser_context::error_buffer, pt_record_warning(), SAFENUM, parser_context::statement_number, and vasprintf().
PT_NODE* pt_function_index_skip_expr (PT_NODE * node)
Definition at line 17312 of file parse_tree_cl.c.
References pt_expr_info::arg1, pt_statement_info::expr, parser_node::info, NULL, pt_expr_info::op, PT_CAST, pt_function_index_skip_expr(), PT_IS_EXPR_NODE, and PT_UNARY_MINUS.
Referenced by is_local_name(), lookup_node(), pt_expr_to_sort_spec(), pt_function_index_skip_expr(), pt_is_join_expr(), and pt_is_nested_expr().
static bool pt_function_is_allowed_as_function_index (const PT_NODE * func) static
Definition at line 17385 of file parse_tree_cl.c.
References assert, F_BENCHMARK, F_ELT, F_INSERT_SUBSTRING, F_JSON_ARRAY, F_JSON_ARRAY_APPEND, F_JSON_ARRAY_INSERT, F_JSON_CONTAINS, F_JSON_CONTAINS_PATH, F_JSON_DEPTH, F_JSON_EXTRACT, F_JSON_GET_ALL_PATHS, F_JSON_INSERT, F_JSON_KEYS, F_JSON_LENGTH, F_JSON_MERGE, F_JSON_MERGE_PATCH, F_JSON_OBJECT, F_JSON_PRETTY, F_JSON_QUOTE, F_JSON_REMOVE, F_JSON_REPLACE, F_JSON_SEARCH, F_JSON_SET, F_JSON_TYPE, F_JSON_UNQUOTE, F_JSON_VALID, pt_statement_info::function, pt_function_info::function_type, parser_node::info, parser_node::node_type, NULL, and PT_FUNCTION.
Referenced by pt_is_function_index_expr().
PT_NODE* pt_gather_constraints (PARSER_CONTEXT * parser, PT_NODE * node)
Definition at line 4149 of file parse_tree_cl.c.
References pt_statement_info::alter, pt_alter_info::alter_clause, pt_create_entity_info::attr_def_list, pt_alter_info::attr_mthd, pt_create_entity_info::class_attr_def_list, pt_alter_info::code, pt_alter_info::constraint_list, pt_create_entity_info::constraint_list, pt_statement_info::create_entity, pt_alter_info::create_index, pt_create_entity_info::create_index, error(), parser_node::info, parser_node::next, parser_node::node_type, NULL, parser_append_node(), PT_ADD_ATTR_MTHD, PT_ALTER, PT_CHANGE_ATTR, PT_CONSTRAINT, PT_CREATE_ENTITY, PT_CREATE_INDEX, PT_INTERNAL_ERROR, and PT_MODIFY_ATTR_MTHD.
int pt_get_assignment_lists (PARSER_CONTEXT * parser, PT_NODE ** select_names, PT_NODE ** select_values, PT_NODE ** const_names, PT_NODE ** const_values, int * no_vals, int * no_consts, PT_NODE * assign, PT_NODE *** old_links)
Definition at line 17146 of file parse_tree_cl.c.
References pt_expr_info::arg1, pt_expr_info::arg2, ASSIGN_LINKS_EXTENT, db_private_alloc, db_private_realloc, ER_GENERIC_ERROR, ER_OUT_OF_VIRTUAL_MEMORY, error(), pt_statement_info::expr, parser_node::info, parser_node::next, NO_ERROR, parser_node::node_type, NULL, pt_expr_info::op, parser_append_node(), PT_ASSIGN, PT_EXPR, PT_IS_CONST_NOT_HOSTVAR, PT_IS_N_COLUMN_UPDATE_EXPR, PT_NAME, and pt_restore_assignment_links().
Referenced by do_merge(), do_prepare_merge(), do_prepare_update(), pt_to_merge_update_xasl(), pt_to_update_xasl(), and update_real_class().
PT_NODE* pt_get_errors (PARSER_CONTEXT * parser)
Definition at line 2108 of file parse_tree_cl.c.
References parser_context::error_msgs, and NULL.
Referenced by compile_trigger_activity(), db_get_errors(), db_get_line_col_of_1st_error(), mq_copy_view_error_msgs(), pt_compile_trigger_stmt(), stmt_exec_batch_query_internal(), and stmt_reset_session_and_parse().
int pt_get_expression_count (PT_NODE * node)
Definition at line 4316 of file parse_tree_cl.c.
References pt_function_info::arg_list, cubregex::count(), pt_value_info::data_value, EXCLUDE_HIDDEN_COLUMNS, pt_statement_info::function, parser_node::info, parser_node::next, parser_node::node_type, NULL, PT_FUNCTION, pt_get_subquery_list(), PT_IS_QUERY_NODE_TYPE, pt_is_set_type, pt_length_of_list(), pt_length_of_select_list(), PT_VALUE, pt_data_value::set, and pt_statement_info::value.
Referenced by pt_check_set_count_set().
PT_NODE* pt_get_next_error (PT_NODE * errors, int * stmt_no, int * line_no, int * col_no, const char ** msg)
Definition at line 2129 of file parse_tree_cl.c.
References parser_node::column_number, PT_ZZ_ERROR_MSG_INFO::error_message, pt_statement_info::error_msg, parser_node::info, parser_node::line_number, parser_node::next, parser_node::node_type, NULL, PT_ZZ_ERROR_MSG, and PT_ZZ_ERROR_MSG_INFO::statement_number.
Referenced by compile_trigger_activity(), db_get_line_col_of_1st_error(), db_get_next_error(), db_get_next_warning(), and mq_copy_view_error_msgs().
PT_NODE* pt_get_node_from_list (PT_NODE * list, int index)
Definition at line 3168 of file parse_tree_cl.c.
References parser_node::next, and NULL.
Referenced by pt_resolve_sort_spec_expr().
PT_NODE* pt_get_subquery_list (PT_NODE * node)
Definition at line 4257 of file parse_tree_cl.c.
References pt_union_info::arg1, assert, parser_node::info, pt_node_list_info::list, pt_select_info::list, parser_node::next, pt_statement_info::node_list, parser_node::node_type, NULL, PT_DIFFERENCE, PT_INTERSECTION, PT_IS_VALUE_QUERY, PT_NAME, PT_SELECT, PT_TYPE_STAR, PT_UNION, PT_VALUE, pt_query_info::q, pt_statement_info::query, pt_query_info::select, parser_node::type_enum, and pt_query_info::union_.
Referenced by pt_get_expression_count().
static PT_NODE * pt_init_alter_trigger (PT_NODE * p) static
Definition at line 6323 of file parse_tree_cl.c.
References pt_statement_info::alter_trigger, parser_node::info, PT_MISC_DUMMY, and pt_alter_trigger_info::trigger_status.
Referenced by pt_init_init_f().
static void pt_init_apply_f (void) static
Definition at line 4817 of file parse_tree_cl.c.
References PT_2PC_ATTACH, PT_ALTER, PT_ALTER_INDEX, PT_ALTER_SERIAL, PT_ALTER_STORED_PROCEDURE, PT_ALTER_TRIGGER, PT_ALTER_USER, pt_apply_alter(), pt_apply_alter_index(), pt_apply_alter_serial(), pt_apply_alter_trigger(), pt_apply_alter_user(), pt_apply_attach(), pt_apply_attr_def(), pt_apply_attr_ordering(), pt_apply_auth_cmd(), pt_apply_auto_increment(), pt_apply_check_option(), pt_apply_commit_work(), pt_apply_constraint(), pt_apply_create_entity(), pt_apply_create_index(), pt_apply_create_serial(), pt_apply_create_trigger(), pt_apply_create_user(), pt_apply_cte(), pt_apply_data_default(), pt_apply_datatype(), pt_apply_delete(), pt_apply_difference(), pt_apply_do(), pt_apply_dot(), pt_apply_drop(), pt_apply_drop_index(), pt_apply_drop_serial(), pt_apply_drop_session_variables(), pt_apply_drop_trigger(), pt_apply_drop_user(), pt_apply_drop_variable(), pt_apply_error_msg(), pt_apply_evaluate(), pt_apply_event_object(), pt_apply_event_spec(), pt_apply_event_target(), pt_apply_execute_trigger(), pt_apply_expr(), pt_apply_f, pt_apply_file_path(), pt_apply_func_array, pt_apply_function(), pt_apply_get_opt_lvl(), pt_apply_get_stats(), pt_apply_get_trigger(), pt_apply_get_xaction(), pt_apply_grant(), pt_apply_host_var(), pt_apply_insert(), pt_apply_insert_value(), pt_apply_intersection(), pt_apply_isolation_lvl(), pt_apply_json_table(), pt_apply_json_table_column(), pt_apply_json_table_node(), pt_apply_kill(), pt_apply_merge(), pt_apply_method_call(), pt_apply_method_def(), pt_apply_name(), pt_apply_named_arg(), pt_apply_node_list(), pt_apply_partition(), pt_apply_parts(), pt_apply_pointer(), pt_apply_prepare(), pt_apply_prepare_to_commit(), pt_apply_query_trace(), pt_apply_remove_trigger(), pt_apply_rename(), pt_apply_rename_trigger(), pt_apply_resolution(), pt_apply_revoke(), pt_apply_rollback_work(), pt_apply_savepoint(), pt_apply_scope(), pt_apply_select(), pt_apply_set_names(), pt_apply_set_opt_lvl(), pt_apply_set_session_variables(), pt_apply_set_sys_params(), pt_apply_set_timezone(), pt_apply_set_trigger(), pt_apply_set_xaction(), pt_apply_showstmt(), pt_apply_sort_spec(), pt_apply_sp_parameter(), pt_apply_spec(), pt_apply_stored_procedure(), pt_apply_table_option(), pt_apply_timeout(), pt_apply_trigger_action(), pt_apply_trigger_spec_list(), pt_apply_truncate(), pt_apply_tuple_value(), pt_apply_union_stmt(), pt_apply_update(), pt_apply_update_stats(), pt_apply_vacuum(), pt_apply_value(), pt_apply_with_clause(), PT_ATTR_DEF, PT_ATTR_ORDERING, PT_AUTH_CMD, PT_AUTO_INCREMENT, PT_CHECK_OPTION, PT_COMMIT_WORK, PT_CONSTRAINT, PT_CREATE_ENTITY, PT_CREATE_INDEX, PT_CREATE_SERIAL, PT_CREATE_STORED_PROCEDURE, PT_CREATE_TRIGGER, PT_CREATE_USER, PT_CTE, PT_DATA_DEFAULT, PT_DATA_TYPE, PT_DEALLOCATE_PREPARE, PT_DELETE, PT_DIFFERENCE, PT_DO, PT_DOT_, PT_DROP, PT_DROP_INDEX, PT_DROP_SERIAL, PT_DROP_SESSION_VARIABLES, PT_DROP_STORED_PROCEDURE, PT_DROP_TRIGGER, PT_DROP_USER, PT_DROP_VARIABLE, PT_EVALUATE, PT_EVENT_OBJECT, PT_EVENT_SPEC, PT_EVENT_TARGET, PT_EXECUTE_PREPARE, PT_EXECUTE_TRIGGER, PT_EXPR, PT_FILE_PATH, PT_FUNCTION, PT_GET_OPT_LVL, PT_GET_STATS, PT_GET_TRIGGER, PT_GET_XACTION, PT_GRANT, PT_HOST_VAR, PT_INSERT, PT_INSERT_VALUE, PT_INTERSECTION, PT_ISOLATION_LVL, PT_JSON_TABLE, PT_JSON_TABLE_COLUMN, PT_JSON_TABLE_NODE, PT_KILL_STMT, PT_MERGE, PT_METHOD_CALL, PT_METHOD_DEF, PT_NAME, PT_NAMED_ARG, PT_NODE_LIST, PT_NODE_POINTER, PT_PARTITION, PT_PARTS, PT_PREPARE_STATEMENT, PT_PREPARE_TO_COMMIT, PT_QUERY_TRACE, PT_REMOVE_TRIGGER, PT_RENAME, PT_RENAME_TRIGGER, PT_RESOLUTION, PT_REVOKE, PT_ROLLBACK_WORK, PT_SAVEPOINT, PT_SCOPE, PT_SELECT, PT_SET_NAMES, PT_SET_OPT_LVL, PT_SET_SESSION_VARIABLES, PT_SET_SYS_PARAMS, PT_SET_TIMEZONE, PT_SET_TRIGGER, PT_SET_XACTION, PT_SHOWSTMT, PT_SORT_SPEC, PT_SP_PARAMETERS, PT_SPEC, PT_TABLE_OPTION, PT_TIMEOUT, PT_TRIGGER_ACTION, PT_TRIGGER_SPEC_LIST, PT_TRUNCATE, PT_TUPLE_VALUE, PT_UNION, PT_UPDATE, PT_UPDATE_STATS, PT_VACUUM, PT_VALUE, PT_WITH_CLAUSE, and PT_ZZ_ERROR_MSG.
Referenced by parser_init_func_vectors().
static PT_NODE * pt_init_attr_def (PT_NODE * p) static
Definition at line 6428 of file parse_tree_cl.c.
References pt_statement_info::attr_def, pt_attr_def_info::attr_type, parser_node::info, p, and PT_NORMAL.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_auth_cmd (PT_NODE * p) static
Definition at line 6693 of file parse_tree_cl.c.
References pt_auth_cmd_info::auth_cmd, pt_statement_info::auth_cmd, parser_node::info, and PT_NO_PRIV.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_constraint (PT_NODE * node) static
Definition at line 15925 of file parse_tree_cl.c.
References pt_statement_info::constraint, parser_node::info, PT_CONSTRAIN_UNKNOWN, and pt_constraint_info::type.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_create_entity (PT_NODE * p) static
Definition at line 6826 of file parse_tree_cl.c.
References pt_statement_info::create_entity, pt_create_entity_info::create_select_action, pt_create_entity_info::entity_type, parser_node::info, p, and PT_CREATE_SELECT_NO_ACTION.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_create_index (PT_NODE * p) static
Definition at line 7108 of file parse_tree_cl.c.
References pt_index_info::func_pos, pt_statement_info::index, parser_node::info, and p.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_data_default (PT_NODE * p) static
Definition at line 8119 of file parse_tree_cl.c.
References pt_statement_info::data_default, DB_DEFAULT_NONE, pt_data_default_info::default_expr_type, pt_data_default_info::default_value, parser_node::info, p, and pt_data_default_info::shared.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_datatype (PT_NODE * p) static
Definition at line 8186 of file parse_tree_cl.c.
References pt_data_type_info::collation_flag, pt_data_type_info::collation_id, pt_statement_info::data_type, parser_node::info, LANG_COERCIBLE_CODESET, LANG_COERCIBLE_COLL, p, TP_DOMAIN_COLL_NORMAL, and pt_data_type_info::units.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_delete (PT_NODE * p) static
Definition at line 8369 of file parse_tree_cl.c.
References pt_statement_info::delete_, pt_delete_info::hint, parser_node::info, p, and PT_HINT_NONE.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_difference (PT_NODE * p) static
Definition at line 8594 of file parse_tree_cl.c.
References pt_query_info::all_distinct, pt_query_info::hint, parser_node::info, p, PT_ALL, PT_HINT_NONE, pt_statement_info::query, S_SELECT, and pt_query_info::scan_op_type.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_expr (PT_NODE * p) static
Definition at line 9424 of file parse_tree_cl.c.
References pt_statement_info::expr, parser_node::info, p, PT_TYPE_NONE, and pt_expr_info::recursive_type.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_function (PT_NODE * p) static
Definition at line 11785 of file parse_tree_cl.c.
References pt_function_info::all_or_distinct, pt_statement_info::function, pt_function_info::function_type, parser_node::info, and p.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_get_opt_lvl (PT_NODE * p) static
Definition at line 12062 of file parse_tree_cl.c.
References pt_statement_info::get_opt_lvl, parser_node::info, pt_get_opt_lvl_info::option, p, and PT_OPT_LVL.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_grant (PT_NODE * p) static
Definition at line 12201 of file parse_tree_cl.c.
References pt_statement_info::grant, pt_grant_info::grant_option, and parser_node::info.
Referenced by pt_init_init_f().
static void pt_init_init_f (void) static
Definition at line 4935 of file parse_tree_cl.c.
References PT_2PC_ATTACH, PT_ALTER, PT_ALTER_INDEX, PT_ALTER_SERIAL, PT_ALTER_STORED_PROCEDURE, PT_ALTER_TRIGGER, PT_ALTER_USER, PT_ATTR_DEF, PT_ATTR_ORDERING, PT_AUTH_CMD, PT_AUTO_INCREMENT, PT_CHECK_OPTION, PT_COMMIT_WORK, PT_CONSTRAINT, PT_CREATE_ENTITY, PT_CREATE_INDEX, PT_CREATE_SERIAL, PT_CREATE_STORED_PROCEDURE, PT_CREATE_TRIGGER, PT_CREATE_USER, PT_CTE, PT_DATA_DEFAULT, PT_DATA_TYPE, PT_DEALLOCATE_PREPARE, PT_DELETE, PT_DIFFERENCE, PT_DO, PT_DOT_, PT_DROP, PT_DROP_INDEX, PT_DROP_SERIAL, PT_DROP_SESSION_VARIABLES, PT_DROP_STORED_PROCEDURE, PT_DROP_TRIGGER, PT_DROP_USER, PT_DROP_VARIABLE, PT_EVALUATE, PT_EVENT_OBJECT, PT_EVENT_SPEC, PT_EVENT_TARGET, PT_EXECUTE_PREPARE, PT_EXECUTE_TRIGGER, PT_EXPR, PT_FILE_PATH, PT_FUNCTION, PT_GET_OPT_LVL, PT_GET_STATS, PT_GET_TRIGGER, PT_GET_XACTION, PT_GRANT, PT_HOST_VAR, pt_init_alter_trigger(), pt_init_attr_def(), pt_init_auth_cmd(), pt_init_constraint(), pt_init_create_entity(), pt_init_create_index(), pt_init_data_default(), pt_init_datatype(), pt_init_delete(), pt_init_difference(), pt_init_expr(), pt_init_f, pt_init_func_array, pt_init_func_null_function, pt_init_function(), pt_init_get_opt_lvl(), pt_init_grant(), pt_init_insert(), pt_init_insert_value(), pt_init_intersection(), pt_init_isolation_lvl(), pt_init_json_table_column(), pt_init_kill(), pt_init_merge(), pt_init_method_def(), pt_init_name(), pt_init_node_list(), pt_init_pointer(), pt_init_query_trace(), pt_init_resolution(), pt_init_select(), pt_init_set_opt_lvl(), pt_init_showstmt(), pt_init_sort_spec(), pt_init_spec(), pt_init_table_option(), pt_init_tuple_value(), pt_init_union_stmt(), pt_init_update(), pt_init_vacuum(), pt_init_value(), PT_INSERT, PT_INSERT_VALUE, PT_INTERSECTION, PT_ISOLATION_LVL, PT_JSON_TABLE, PT_JSON_TABLE_COLUMN, PT_JSON_TABLE_NODE, PT_KILL_STMT, PT_MERGE, PT_METHOD_CALL, PT_METHOD_DEF, PT_NAME, PT_NAMED_ARG, PT_NODE_LIST, PT_NODE_POINTER, PT_PARTITION, PT_PARTS, PT_PREPARE_STATEMENT, PT_PREPARE_TO_COMMIT, PT_QUERY_TRACE, PT_REMOVE_TRIGGER, PT_RENAME, PT_RENAME_TRIGGER, PT_RESOLUTION, PT_REVOKE, PT_ROLLBACK_WORK, PT_SAVEPOINT, PT_SCOPE, PT_SELECT, PT_SET_NAMES, PT_SET_OPT_LVL, PT_SET_SESSION_VARIABLES, PT_SET_SYS_PARAMS, PT_SET_TIMEZONE, PT_SET_TRIGGER, PT_SET_XACTION, PT_SHOWSTMT, PT_SORT_SPEC, PT_SP_PARAMETERS, PT_SPEC, PT_TABLE_OPTION, PT_TIMEOUT, PT_TRIGGER_ACTION, PT_TRIGGER_SPEC_LIST, PT_TRUNCATE, PT_TUPLE_VALUE, PT_UNION, PT_UPDATE, PT_UPDATE_STATS, PT_VACUUM, PT_VALUE, PT_WITH_CLAUSE, and PT_ZZ_ERROR_MSG.
Referenced by parser_init_func_vectors().
static PT_NODE * pt_init_insert (PT_NODE * p) static
Definition at line 12357 of file parse_tree_cl.c.
References pt_insert_info::hint, parser_node::info, pt_statement_info::insert, pt_insert_info::is_subinsert, p, PT_HINT_NONE, pt_insert_info::server_allowed, and SERVER_INSERT_NOT_CHECKED.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_insert_value (PT_NODE * p) static
Definition at line 16483 of file parse_tree_cl.c.
References db_make_null(), parser_node::info, pt_statement_info::insert_value, p, and pt_insert_value_info::value.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_intersection (PT_NODE * p) static
Definition at line 12572 of file parse_tree_cl.c.
References pt_query_info::all_distinct, pt_query_info::hint, parser_node::info, p, PT_ALL, PT_HINT_NONE, pt_statement_info::query, S_SELECT, and pt_query_info::scan_op_type.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_isolation_lvl (PT_NODE * p) static
Definition at line 12697 of file parse_tree_cl.c.
References parser_node::info, pt_isolation_lvl_info::instances, pt_statement_info::isolation_lvl, PT_NO_ISOLATION_LEVEL, and pt_isolation_lvl_info::schema.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_json_table_column (PT_NODE * p) static
Definition at line 18070 of file parse_tree_cl.c.
References pt_json_table_column_info::func, parser_node::info, pt_statement_info::json_table_column_info, JSON_TABLE_EXTRACT, JSON_TABLE_RETURN_NULL, json_table_column_behavior::m_behavior, pt_json_table_column_info::on_empty, pt_json_table_column_info::on_error, and p.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_kill (PT_NODE * p) static
Definition at line 16491 of file parse_tree_cl.c.
References parser_node::info, pt_killstmt_info::kill_type, pt_statement_info::killstmt, KILLSTMT_TRAN, and p.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_merge (PT_NODE * p) static
Definition at line 16283 of file parse_tree_cl.c.
References pt_merge_info::hint, parser_node::info, pt_statement_info::merge, p, and PT_HINT_NONE.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_method_def (PT_NODE * p) static
Definition at line 12825 of file parse_tree_cl.c.
References parser_node::info, pt_statement_info::method_def, pt_method_def_info::mthd_type, p, and PT_NORMAL.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_name (PT_NODE * p) static
Definition at line 12904 of file parse_tree_cl.c.
References pt_name_info::db_object_chn, parser_node::info, pt_statement_info::name, NULL_CHN, and p.
Referenced by pt_init_init_f().
void pt_init_node (PT_NODE * node, PT_NODE_TYPE node_type)
Definition at line 5178 of file parse_tree_cl.c.
References assert, parser_node::info, parser_node::node_type, NULL, pt_init_f, and PT_LAST_NODE_NUMBER.
Referenced by qo_convert_attref_to_dotexpr().
static PT_NODE * pt_init_node_list (PT_NODE * p) static
Definition at line 16230 of file parse_tree_cl.c.
References parser_node::info, pt_node_list_info::list_type, pt_statement_info::node_list, and p.
Referenced by pt_init_init_f().
PT_NODE** pt_init_one_statement_parser (PARSER_CONTEXT * parser, FILE * file)
Definition at line 1891 of file parse_tree_cl.c.
References parser_context::casecmp, parser_context::column, dbcs_get_next(), dbcs_start_input(), fgetin(), parser_context::file, intl_identifier_casecmp(), lang_charset(), LANG_VARIABLE_CHARSET, parser_context::line, parser_context::next_byte, parser_context::next_char, parser, parser_input_host_index, parser_output_host_index, parser_context::stack_top, and this_parser.
Referenced by db_make_session_for_one_statement_execution().
static PT_NODE * pt_init_pointer (PT_NODE * node) static
Definition at line 16179 of file parse_tree_cl.c.
References pt_pointer_info::do_walk, parser_node::info, pt_statement_info::pointer, PT_POINTER_NORMAL, and pt_pointer_info::type.
Referenced by pt_init_init_f().
static void pt_init_print_f (void) static
Definition at line 5059 of file parse_tree_cl.c.
References NULL, PT_2PC_ATTACH, PT_ALTER, PT_ALTER_INDEX, PT_ALTER_SERIAL, PT_ALTER_STORED_PROCEDURE, PT_ALTER_TRIGGER, PT_ALTER_USER, PT_ATTR_DEF, PT_ATTR_ORDERING, PT_AUTH_CMD, PT_AUTO_INCREMENT, PT_CHECK_OPTION, PT_COMMIT_WORK, PT_CONSTRAINT, PT_CREATE_ENTITY, PT_CREATE_INDEX, PT_CREATE_SERIAL, PT_CREATE_STORED_PROCEDURE, PT_CREATE_TRIGGER, PT_CREATE_USER, PT_CTE, PT_DATA_DEFAULT, PT_DATA_TYPE, PT_DEALLOCATE_PREPARE, PT_DELETE, PT_DIFFERENCE, PT_DO, PT_DOT_, PT_DROP, PT_DROP_INDEX, PT_DROP_SERIAL, PT_DROP_SESSION_VARIABLES, PT_DROP_STORED_PROCEDURE, PT_DROP_TRIGGER, PT_DROP_USER, PT_DROP_VARIABLE, PT_EVALUATE, PT_EVENT_OBJECT, PT_EVENT_SPEC, PT_EVENT_TARGET, PT_EXECUTE_PREPARE, PT_EXECUTE_TRIGGER, PT_EXPR, PT_FILE_PATH, PT_FUNCTION, PT_GET_OPT_LVL, PT_GET_STATS, PT_GET_TRIGGER, PT_GET_XACTION, PT_GRANT, PT_HOST_VAR, PT_INSERT, PT_INSERT_VALUE, PT_INTERSECTION, PT_ISOLATION_LVL, PT_JSON_TABLE, PT_JSON_TABLE_COLUMN, PT_JSON_TABLE_NODE, PT_MERGE, PT_METHOD_CALL, PT_METHOD_DEF, PT_NAME, PT_NAMED_ARG, PT_NODE_LIST, PT_NODE_POINTER, PT_PARTITION, PT_PARTS, PT_PREPARE_STATEMENT, PT_PREPARE_TO_COMMIT, pt_print_alter(), pt_print_alter_index(), pt_print_alter_serial(), pt_print_alter_stored_procedure(), pt_print_alter_trigger(), pt_print_alter_user(), pt_print_attach(), pt_print_attr_def(), pt_print_attr_ordering(), pt_print_auth_cmd(), pt_print_auto_increment(), pt_print_check_option(), pt_print_commit_work(), pt_print_constraint(), pt_print_create_entity(), pt_print_create_index(), pt_print_create_serial(), pt_print_create_stored_procedure(), pt_print_create_trigger(), pt_print_create_user(), pt_print_cte(), pt_print_data_default(), pt_print_datatype(), pt_print_delete(), pt_print_difference(), pt_print_do(), pt_print_dot(), pt_print_drop(), pt_print_drop_index(), pt_print_drop_serial(), pt_print_drop_session_variables(), pt_print_drop_stored_procedure(), pt_print_drop_trigger(), pt_print_drop_user(), pt_print_drop_variable(), pt_print_error_msg(), pt_print_evaluate(), pt_print_event_object(), pt_print_event_spec(), pt_print_event_target(), pt_print_execute_trigger(), pt_print_expr(), pt_print_f, pt_print_file_path(), pt_print_func_array, pt_print_function(), pt_print_get_opt_lvl(), pt_print_get_stats(), pt_print_get_trigger(), pt_print_get_xaction(), pt_print_grant(), pt_print_host_var(), pt_print_insert(), pt_print_insert_value(), pt_print_intersection(), pt_print_isolation_lvl(), pt_print_json_table(), pt_print_json_table_columns(), pt_print_json_table_node(), pt_print_merge(), pt_print_method_call(), pt_print_method_def(), pt_print_name(), pt_print_named_arg(), pt_print_node_list(), pt_print_partition(), pt_print_parts(), pt_print_pointer(), pt_print_prepare_to_commit(), pt_print_query_trace(), pt_print_remove_trigger(), pt_print_rename(), pt_print_rename_trigger(), pt_print_resolution(), pt_print_revoke(), pt_print_rollback_work(), pt_print_savepoint(), pt_print_scope(), pt_print_select(), pt_print_set_names(), pt_print_set_opt_lvl(), pt_print_set_session_variables(), pt_print_set_sys_params(), pt_print_set_timezone(), pt_print_set_trigger(), pt_print_set_xaction(), pt_print_showstmt(), pt_print_sort_spec(), pt_print_sp_parameter(), pt_print_spec(), pt_print_table_option(), pt_print_timeout(), pt_print_trigger_action(), pt_print_trigger_spec_list(), pt_print_truncate(), pt_print_tuple_value(), pt_print_union_stmt(), pt_print_update(), pt_print_update_stats(), pt_print_vacuum(), pt_print_value(), pt_print_with_clause(), PT_QUERY_TRACE, PT_REMOVE_TRIGGER, PT_RENAME, PT_RENAME_TRIGGER, PT_RESOLUTION, PT_REVOKE, PT_ROLLBACK_WORK, PT_SAVEPOINT, PT_SCOPE, PT_SELECT, PT_SET_NAMES, PT_SET_OPT_LVL, PT_SET_SESSION_VARIABLES, PT_SET_SYS_PARAMS, PT_SET_TIMEZONE, PT_SET_TRIGGER, PT_SET_XACTION, PT_SHOWSTMT, PT_SORT_SPEC, PT_SP_PARAMETERS, PT_SPEC, PT_TABLE_OPTION, PT_TIMEOUT, PT_TRIGGER_ACTION, PT_TRIGGER_SPEC_LIST, PT_TRUNCATE, PT_TUPLE_VALUE, PT_UNION, PT_UPDATE, PT_UPDATE_STATS, PT_VACUUM, PT_VALUE, PT_WITH_CLAUSE, and PT_ZZ_ERROR_MSG.
Referenced by parser_init_func_vectors().
static PT_NODE * pt_init_query_trace (PT_NODE * p) static
Definition at line 17928 of file parse_tree_cl.c.
References pt_trace_info::format, parser_node::info, pt_trace_info::on_off, p, PT_TRACE_FORMAT_TEXT, PT_TRACE_OFF, and pt_statement_info::trace.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_resolution (PT_NODE * p) static
Definition at line 13281 of file parse_tree_cl.c.
References pt_resolution_info::attr_type, parser_node::info, p, PT_NORMAL, and pt_statement_info::resolution.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_select (PT_NODE * p) static
Definition at line 13520 of file parse_tree_cl.c.
References pt_query_info::all_distinct, pt_select_info::check_cycles, CONNECT_BY_CYCLES_ERROR, pt_select_info::hint, pt_query_info::hint, parser_node::info, pt_query_info::is_subquery, p, PT_ALL, PT_HINT_NONE, pt_query_info::q, pt_statement_info::query, S_SELECT, pt_query_info::scan_op_type, and pt_query_info::select.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_set_opt_lvl (PT_NODE * p) static
Definition at line 14318 of file parse_tree_cl.c.
References parser_node::info, pt_set_opt_lvl_info::option, PT_OPT_LVL, and pt_statement_info::set_opt_lvl.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_showstmt (PT_NODE * p) static
Definition at line 14467 of file parse_tree_cl.c.
References parser_node::info, pt_showstmt_info::show_type, pt_statement_info::showstmt, and SHOWSTMT_NULL.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_sort_spec (PT_NODE * p) static
Definition at line 14549 of file parse_tree_cl.c.
References pt_sort_spec_info::asc_or_desc, parser_node::info, pt_sort_spec_info::nulls_first_or_last, p, PT_ASC, PT_NULLS_DEFAULT, and pt_statement_info::sort_spec.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_spec (PT_NODE * p) static
Definition at line 8968 of file parse_tree_cl.c.
References pt_spec_info::auth_bypass_mask, DB_AUTH_NONE, parser_node::info, pt_spec_info::join_type, pt_spec_info::location, pt_spec_info::only_all, p, PT_JOIN_NONE, PT_ONLY, and pt_statement_info::spec.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_table_option (PT_NODE * p) static
Definition at line 7520 of file parse_tree_cl.c.
References parser_node::info, pt_table_option_info::option, p, PT_TABLE_OPTION_NONE, and pt_statement_info::table_option.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_tuple_value (PT_NODE * p) static
Definition at line 16431 of file parse_tree_cl.c.
References pt_tuple_value_info::index, parser_node::info, p, and pt_statement_info::tuple_value.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_union_stmt (PT_NODE * p) static
Definition at line 14753 of file parse_tree_cl.c.
References pt_query_info::all_distinct, pt_query_info::hint, parser_node::info, p, PT_ALL, PT_HINT_NONE, pt_statement_info::query, S_SELECT, and pt_query_info::scan_op_type.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_update (PT_NODE * p) static
Definition at line 14851 of file parse_tree_cl.c.
References pt_update_info::hint, parser_node::info, p, PT_HINT_NONE, and pt_statement_info::update.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_vacuum (PT_NODE * p) static
Definition at line 17882 of file parse_tree_cl.c.
References assert, p, and PT_IS_VACUUM_NODE.
Referenced by pt_init_init_f().
static PT_NODE * pt_init_value (PT_NODE * p) static
Definition at line 15281 of file parse_tree_cl.c.
References pt_value_info::host_var_index, parser_node::info, p, and pt_statement_info::value.
Referenced by pt_init_init_f().
void* pt_internal_error (PARSER_CONTEXT * parser, const char * file, int line, const char * what)
Definition at line 1481 of file parse_tree_cl.c.
References parser_node::buffer_pos, parser_node::column_number, parser_context::flag, parser_context::has_internal_error, parser_node::line_number, NULL, parser, pt_frob_error(), pt_has_error, and pt_internal_error().
Referenced by pt_internal_error().
bool pt_is_const_expr_node (PT_NODE * node)
Definition at line 16761 of file parse_tree_cl.c.
References pt_expr_info::arg1, pt_expr_info::arg2, pt_expr_info::arg3, pt_function_info::arg_list, assert, pt_statement_info::expr, pt_statement_info::function, parser_node::info, pt_name_info::meta_class, pt_statement_info::name, parser_node::next, parser_node::node_type, NULL, pt_expr_info::op, PT_ABS, PT_ACOS, PT_ADD_MONTHS, PT_ADDDATE, PT_ADDTIME, PT_AES_DECRYPT, PT_AES_ENCRYPT, PT_ASCII, PT_ASIN, PT_ATAN, PT_ATAN2, PT_BIN, PT_BIT_AND, PT_BIT_COUNT, PT_BIT_LENGTH, PT_BIT_NOT, PT_BIT_OR, PT_BIT_XOR, PT_BITSHIFT_LEFT, PT_BITSHIFT_RIGHT, PT_CASE, PT_CAST, PT_CEIL, PT_CHAR_LENGTH, PT_CHARSET, PT_CHR, PT_COALESCE, PT_COERCIBILITY, PT_COLLATION, PT_CONCAT, PT_CONCAT_WS, PT_CONV, PT_CONV_TZ, PT_COS, PT_COT, PT_CRC32, PT_CURRENT_DATE, PT_CURRENT_DATETIME, PT_CURRENT_TIME, PT_CURRENT_TIMESTAMP, PT_CURRENT_USER, PT_CURRENT_VALUE, PT_DATABASE, PT_DATE_ADD, PT_DATE_FORMAT, PT_DATE_SUB, PT_DATEDIFF, PT_DATEF, PT_DAYF, PT_DAYOFMONTH, PT_DAYOFWEEK, PT_DAYOFYEAR, PT_DBTIMEZONE, PT_DECODE, PT_DEFAULTF, PT_DEGREES, PT_DISK_SIZE, PT_DIV, PT_DIVIDE, PT_EQ, PT_EXP, PT_EXPR, PT_EXTRACT, PT_FIELD, PT_FINDINSET, PT_FLOOR, PT_FORMAT, PT_FROM_BASE64, PT_FROM_TZ, PT_FROM_UNIXTIME, PT_FROMDAYS, PT_FUNCTION_HOLDER, PT_GE, PT_GREATEST, PT_GT, PT_HEX, PT_HOST_VAR, PT_HOURF, PT_IF, PT_IFNULL, PT_INDEX_PREFIX, PT_INET_ATON, PT_INET_NTOA, PT_INSTR, pt_is_const_expr_node(), PT_ISNULL, PT_LAST_DAY, PT_LE, PT_LEAST, PT_LEFT, PT_LIKE_LOWER_BOUND, PT_LIKE_UPPER_BOUND, PT_LIST_DBS, PT_LN, PT_LOCAL_TRANSACTION_ID, PT_LOCATE, PT_LOG, PT_LOG10, PT_LOG2, PT_LOWER, PT_LPAD, PT_LT, PT_LTRIM, PT_MAKEDATE, PT_MAKETIME, PT_MD5, PT_MID, PT_MINUS, PT_MINUTEF, PT_MOD, PT_MODULUS, PT_MONTHF, PT_MONTHS_BETWEEN, PT_NAME, PT_NE, PT_NEW_TIME, PT_NEXT_VALUE, PT_NULLIF, PT_NULLSAFE_EQ, PT_NVL, PT_NVL2, PT_OCTET_LENGTH, PT_OID_OF_DUPLICATE_KEY, PT_PARAMETER, PT_PI, PT_PLUS, PT_POSITION, PT_POWER, PT_QUARTERF, PT_RADIANS, PT_REPEAT, PT_REPLACE, PT_REVERSE, PT_RIGHT, PT_ROUND, PT_ROW_COUNT, PT_RPAD, PT_RTRIM, PT_SCHEMA, PT_SCHEMA_DEF, PT_SECONDF, PT_SECTOTIME, PT_SESSIONTIMEZONE, PT_SHA_ONE, PT_SHA_TWO, PT_SIGN, PT_SIN, PT_SQRT, PT_STR_TO_DATE, PT_STRCMP, PT_SUBDATE, PT_SUBSTRING, PT_SUBSTRING_INDEX, PT_SYS_DATE, PT_SYS_DATETIME, PT_SYS_TIME, PT_SYS_TIMESTAMP, PT_TAN, PT_TIME_FORMAT, PT_TIMEDIFF, PT_TIMEF, PT_TIMES, PT_TIMESTAMP, PT_TIMETOSEC, PT_TO_BASE64, PT_TO_CHAR, PT_TO_DATE, PT_TO_DATETIME, PT_TO_DATETIME_TZ, PT_TO_ENUMERATION_VALUE, PT_TO_NUMBER, PT_TO_TIME, PT_TO_TIMESTAMP, PT_TO_TIMESTAMP_TZ, PT_TODAYS, PT_TRANSLATE, PT_TRIM, PT_TRUNC, PT_TZ_OFFSET, PT_UNARY_MINUS, PT_UNIX_TIMESTAMP, PT_UPPER, PT_USER, PT_UTC_DATE, PT_UTC_TIME, PT_UTC_TIMESTAMP, PT_VALUE, PT_VERSION, PT_WEEKDAY, PT_WEEKF, PT_WIDTH_BUCKET, and PT_YEARF.
Referenced by pt_check_cume_dist_percent_rank_order_by(), pt_is_const_expr_node(), pt_is_function_index_expr(), pt_remove_unusable_sort_specs(), and qo_search_comp_pair_term().
bool pt_is_function_index_expr (PARSER_CONTEXT * parser, PT_NODE * expr, bool report_error)
Definition at line 17574 of file parse_tree_cl.c.
References pt_expr_info::arg1, pt_statement_info::expr, fcode_get_uppercase_name(), pt_statement_info::function, pt_function_info::function_type, parser_node::info, MSGCAT_SEMANTIC_CONSTANT_IN_FUNCTION_INDEX_NOT_ALLOWED, MSGCAT_SEMANTIC_FUNCTION_CANNOT_BE_USED_FOR_INDEX, MSGCAT_SEMANTIC_INVALID_FUNCTION_INDEX, MSGCAT_SEMANTIC_INVALID_FUNCTION_INDEX_EXPR, MSGCAT_SET_PARSER_SEMANTIC, parser_node::node_type, pt_expr_info::op, PT_ERRORm, PT_ERRORmf, PT_EXPR, pt_expr_is_allowed_as_function_index(), PT_FUNCTION_HOLDER, pt_function_is_allowed_as_function_index(), pt_is_const_expr_node(), pt_is_nested_expr(), pt_show_binopcode(), and PT_VALUE.
Referenced by build_query_graph_function_index(), do_recreate_func_index_constr(), is_local_name(), lookup_node(), lookup_seg(), pt_check_function_index_expr(), pt_check_with_info(), qo_analyze_term(), qo_rewrite_like_terms(), and set_seg_expr().
bool pt_is_join_expr (PT_NODE * expr, UINTPTR * spec_id)
Definition at line 17736 of file parse_tree_cl.c.
References pt_expr_info::arg1, pt_expr_info::arg2, pt_expr_info::arg3, pt_function_info::arg_list, assert, pt_statement_info::expr, pt_statement_info::function, parser_node::info, pt_statement_info::name, parser_node::next, NULL, pt_expr_info::op, PT_FUNCTION_HOLDER, pt_function_index_skip_expr(), PT_IS_NAME_NODE, and pt_name_info::spec_id.
Referenced by build_query_graph_function_index().
static bool pt_is_nested_expr (const PT_NODE * node) static
Definition at line 17338 of file parse_tree_cl.c.
References pt_expr_info::arg1, pt_expr_info::arg2, pt_expr_info::arg3, pt_function_info::arg_list, assert, pt_statement_info::expr, pt_statement_info::function, parser_node::info, parser_node::next, parser_node::node_type, NULL, pt_expr_info::op, PT_EXPR, PT_FUNCTION_HOLDER, pt_function_index_skip_expr(), PT_IS_NAME_NODE, and PT_IS_VALUE_NODE.
Referenced by pt_is_function_index_expr().
static const char * pt_json_table_column_behavior_to_string (const json_table_column_behavior_type & behavior_type) static
Definition at line 18092 of file parse_tree_cl.c.
References assert, JSON_TABLE_DEFAULT_VALUE, JSON_TABLE_RETURN_NULL, and JSON_TABLE_THROW_ERROR.
Referenced by pt_print_json_table_column_error_or_empty_behavior().
PT_NODE* pt_lambda (PARSER_CONTEXT * parser, PT_NODE * tree_with_names, PT_NODE * name_node, PT_NODE * corresponding_tree)
Definition at line 1090 of file parse_tree_cl.c.
References pt_lambda_with_arg().
Referenced by meth_replace_referenced_attrs(), and mq_push_path().
static PT_NODE * pt_lambda_check_reduce_eq (PARSER_CONTEXT * parser, PT_NODE * tree_or_name, void * void_arg, int * continue_walk) static
Definition at line 474 of file parse_tree_cl.c.
References pt_dot_info::arg1, pt_expr_info::arg1, pt_data_type_info::collation_id, pt_statement_info::data_type, parser_node::data_type, pt_statement_info::dot, pt_statement_info::expr, parser_node::info, LANG_SYS_COLLATION, pt_lambda_arg::name, parser_node::node_type, NULL, pt_expr_info::op, PT_BIT_LENGTH, PT_CAST, PT_CHAR_LENGTH, PT_DOT_, PT_EXPR, PT_EXPR_INFO_CAST_COLL_MODIFIER, PT_EXPR_INFO_IS_FLAGED, PT_GET_COLLATION_MODIFIER, PT_HAS_COLLATION, PT_LIST_WALK, PT_METHOD_CALL, PT_NAME, pt_name_equal(), PT_NAME_INFO_DOT_SPEC, PT_NAME_INFO_SET_FLAG, PT_OCTET_LENGTH, PT_TYPE_VARBIT, PT_TYPE_VARCHAR, PT_TYPE_VARNCHAR, pt_lambda_arg::tree, and parser_node::type_enum.
Referenced by pt_lambda_with_arg().
static PT_NODE * pt_lambda_node (PARSER_CONTEXT * parser, PT_NODE * tree_or_name, void * void_arg, int * continue_walk) static
Definition at line 565 of file parse_tree_cl.c.
References pt_dot_info::arg2, pt_lambda_arg::dont_replace, pt_statement_info::dot, pt_statement_info::expr, F_MULTISET, F_SEQUENCE, F_SET, pt_statement_info::function, pt_function_info::function_type, parser_node::info, pt_function_info::is_type_checked, pt_lambda_arg::loc_check, pt_name_info::location, pt_lambda_arg::name, pt_statement_info::name, parser_node::next, parser_node::node_type, pt_expr_info::op, parser_copy_tree_list(), parser_free_node(), PT_CONTINUE_WALK, PT_DOT_, PT_EXPR, PT_FUNCTION, pt_get_end_path_node(), PT_NAME, pt_name_equal(), PT_NAME_INFO_CONSTANT, PT_NAME_INFO_DOT_SPEC, PT_NAME_INFO_IS_FLAGED, PT_NAME_INFO_SET_FLAG, PT_ORDERBY_NUM, pt_lambda_arg::replace_num, pt_lambda_arg::tree, and pt_lambda_arg::type.
Referenced by pt_lambda_with_arg().
PT_NODE* pt_lambda_with_arg (PARSER_CONTEXT * parser, PT_NODE * tree_with_names, PT_NODE * name_node, PT_NODE * corresponding_tree, bool loc_check, int type, bool dont_replace)
Definition at line 1020 of file parse_tree_cl.c.
References pt_lambda_arg::dont_replace, pt_statement_info::expr, pt_statement_info::function, pt_function_info::function_type, parser_node::info, pt_lambda_arg::loc_check, pt_lambda_arg::name, parser_node::node_type, NULL, pt_expr_info::op, pt_expr_info::paren_type, parser_walk_tree(), PT_DOT_, PT_EXPR, PT_FUNCTION, PT_GROUPBY_NUM, PT_INST_NUM, PT_INTERNAL_ERROR, pt_lambda_check_reduce_eq(), pt_lambda_node(), PT_NAME, PT_ORDERBY_NUM, pt_lambda_arg::replace_num, pt_lambda_arg::tree, and pt_lambda_arg::type.
Referenced by pt_lambda(), qo_reduce_equality_terms(), qo_reduce_order_by(), and qo_reduce_order_by_for().
int pt_length_of_list (const PT_NODE * list)
Definition at line 3117 of file parse_tree_cl.c.
References parser_node::next.
Referenced by acquire_locks_for_multiple_rename(), add_foreign_key(), create_or_drop_index_helper(), do_add_constraints(), do_execute_select(), do_execute_session_statement(), do_insert_template(), do_kill(), do_prepare_insert(), do_select_internal(), find_update_columns(), gen_outer(), func_type::Node::get_signature(), make_mergelist_proc(), meth_collapse_nodes(), meth_get_method_params(), meth_replace_method_calls(), meth_replace_referenced_attrs(), meth_translate_spec(), pt_bind_spec_attrs(), pt_check_assignments(), pt_check_cume_dist_percent_rank_order_by(), pt_check_group_concat_order_by(), pt_check_into_clause(), pt_check_method(), pt_check_same_datatype(), pt_check_vclass_query_spec(), pt_coerce_insert_values(), pt_coerce_node_collation(), pt_fillin_type_size(), pt_get_expression_count(), pt_get_select_from_spec(), pt_make_identity_offsets(), pt_number_of_attributes(), pt_semantic_check_local(), pt_set_attr_list_types(), pt_split_attrs(), pt_to_aggregate(), pt_to_buildlist_proc(), pt_to_index_attrs(), pt_to_insert_xasl(), pt_to_merge_insert_xasl(), pt_to_method_arglist(), pt_to_method_sig_list(), pt_to_update_xasl(), qo_all_some_in_selectivity(), qo_reduce_equality_terms(), set_prepare_info_into_list(), and uci_static().
int pt_length_of_select_list (PT_NODE * list, int hidden_col)
Definition at line 3134 of file parse_tree_cl.c.
References parser_node::flag, INCLUDE_HIDDEN_COLUMNS, parser_node::is_hidden_column, and parser_node::next.
Referenced by db_get_query_type_list(), insert_subquery_results(), mq_virtual_queries(), pt_bind_names(), pt_check_assignments(), pt_check_into_clause(), pt_check_order_by(), pt_check_type_compatibility_of_values_query(), pt_check_union_compatibility(), pt_check_union_type_compatibility_of_values_query(), pt_check_vclass_query_spec(), pt_coerce_insert_values(), pt_coerce_range_expr_arguments(), pt_fillin_type_size(), pt_get_compatible_info(), pt_get_expression_count(), pt_get_select_list(), pt_get_titles(), pt_get_values_query_compatible_info(), pt_new_query_result_descriptor(), pt_select_list_to_one_col(), pt_semantic_check_local(), pt_set_attr_list_types(), pt_set_table_to_db(), pt_to_false_subquery(), pt_to_insert_xasl(), pt_to_merge_insert_xasl(), pt_to_regu_variable(), pt_to_update_xasl(), and qo_rewrite_subqueries().
void pt_move_node (REFPTR(PT_NODE, destp) , REFPTR(PT_NODE, srcp))
Definition at line 18262 of file parse_tree_cl.c.
References NULL.
Referenced by pt_fold_union().
PT_NODE* pt_point (PARSER_CONTEXT * parser, const PT_NODE * in_tree)
Definition at line 1229 of file parse_tree_cl.c.
References CAST_POINTER_TO_NODE, parser_node::column_number, parser_node::info, parser_node::line_number, pt_pointer_info::node, NULL, parser_new_node(), pt_statement_info::pointer, PT_NODE_POINTER, and pt_lambda_arg::tree.
Referenced by check_for_cons(), gen_outer(), make_namelist_from_projected_segs(), make_pred_from_bitset(), parser_get_tree_list_diff(), pt_get_pred_attrs(), pt_make_aptr_parent_node(), pt_point_l(), pt_point_ref(), pt_pointer_stack_push(), pt_resolve_spec_to_cte(), pt_set_orderby_for_sort_limit_plan(), pt_split_attrs(), pt_to_aggregate_node(), pt_to_buildlist_proc(), pt_to_index_attrs(), pt_to_list_key(), pt_to_range_key(), pt_to_rangelist_key(), pt_to_single_key(), qo_check_iscan_for_multi_range_opt(), qo_collect_name_spec(), qo_converse_sarg_terms(), qo_plan_compute_iscan_sort_list(), and update_check_for_constraints().
PT_NODE* pt_point_l (PARSER_CONTEXT * parser, const PT_NODE * in_tree)
Definition at line 1268 of file parse_tree_cl.c.
References parser_node::next, NULL, parser_append_node(), parser_free_tree(), pt_point(), and pt_lambda_arg::tree.
Referenced by pt_make_aptr_parent_node().
PT_NODE* pt_point_ref (PARSER_CONTEXT * parser, const PT_NODE * node)
Definition at line 1314 of file parse_tree_cl.c.
References parser_node::info, NULL, pt_statement_info::pointer, pt_point(), PT_POINTER_REF, and pt_pointer_info::type.
Referenced by pt_expand_analytic_node(), and pt_to_analytic_final_node().
PT_NODE* pt_pointer_stack_pop (PARSER_CONTEXT * parser, PT_NODE * stack, PT_NODE ** node)
Definition at line 1370 of file parse_tree_cl.c.
References parser_node::info, parser_node::next, pt_pointer_info::node, NULL, parser_free_tree(), pt_statement_info::pointer, and PT_INTERNAL_ERROR.
Referenced by mq_rewrite_agg_names_post(), mq_rewrite_aggregate_as_derived(), pt_find_aggregate_functions_post(), and qo_optimize_queries().
PT_NODE* pt_pointer_stack_push (PARSER_CONTEXT * parser, PT_NODE * stack, PT_NODE * node)
Definition at line 1334 of file parse_tree_cl.c.
References MSGCAT_SEMANTIC_OUT_OF_MEMORY, MSGCAT_SET_PARSER_SEMANTIC, parser_node::next, NULL, PT_ERRORm, and pt_point().
Referenced by mq_rewrite_agg_names(), mq_rewrite_aggregate_as_derived(), pt_find_aggregate_functions_pre(), and qo_optimize_queries().
PT_NODE* pt_pop (PARSER_CONTEXT * parser)
Definition at line 1638 of file parse_tree_cl.c.
References parser_context::node_stack, NULL, and parser_context::stack_top.
Referenced by pt_make_query_show_exec_stats(), pt_make_query_show_exec_stats_all(), and pt_rewrite_set_eq_set().
char* pt_print_alias (PARSER_CONTEXT * parser, const PT_NODE * node)
Definition at line 2608 of file parse_tree_cl.c.
References NULL, and pt_print_bytes_alias().
Referenced by pt_get_node_title().
static PARSER_VARCHAR * pt_print_alter (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 6103 of file parse_tree_cl.c.
References pt_statement_info::alter, pt_alter_info::entity_name, pt_alter_info::entity_type, pt_alter_info::hint, parser_node::info, parser_node::next, NULL, pt_append_nulstring(), pt_append_varchar(), PT_HINT_NONE, PT_HINT_SKIP_UPDATE_NULL, pt_print_alter_one_clause(), pt_print_bytes(), and pt_show_misc_type().
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_alter_index (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 6163 of file parse_tree_cl.c.
References assert, pt_index_info::code, pt_index_info::comment, parser_context::custom_print, pt_statement_info::index, pt_index_info::index_name, pt_index_info::index_status, pt_index_info::indexed_class, parser_node::info, pt_statement_info::name, NULL, pt_name_info::original, pt_append_bytes(), pt_append_nulstring(), pt_append_varchar(), pt_print_and_list(), pt_print_bytes(), pt_print_index_columns(), PT_REBUILD_INDEX, PT_SUPPRESS_RESOLVED, pt_index_info::reverse, SM_INVISIBLE_INDEX, SM_NORMAL_INDEX, strlen, pt_index_info::unique, and pt_index_info::where.
Referenced by pt_init_print_f().
static PARSER_VARCHAR* pt_print_alter_one_clause (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 5507 of file parse_tree_cl.c.
References pt_statement_info::alter, pt_alter_info::alter_clause, assert, pt_alter_info::attr_mthd, pt_alter_info::auto_increment, pt_alter_info::ch_attr_def, pt_alter_info::code, pt_alter_info::collation, pt_alter_info::comment, pt_alter_info::constraint_list, pt_alter_info::create_index, parser_context::custom_print, pt_alter_info::index, parser_node::info, lang_get_codeset_name(), lang_get_collation_name(), pt_name_info::meta_class, pt_statement_info::name, parser_node::next, NULL, pt_alter_info::partition, PT_ADD_ATTR_MTHD, PT_ADD_HASHPARTITION, PT_ADD_INDEX_CLAUSE, PT_ADD_PARTITION, PT_ADD_QUERY, PT_ADD_SUPCLASS, PT_ALTER_DEFAULT, PT_ANALYZE_PARTITION, pt_append_nulstring(), pt_append_varchar(), PT_APPLY_PARTITION, PT_ATTRIBUTE, PT_CHANGE_ATTR, PT_CHANGE_AUTO_INCREMENT, PT_CHANGE_COLLATION, PT_CHANGE_OWNER, PT_CHANGE_TABLE_COMMENT, PT_CLASS, PT_COALESCE_PARTITION, PT_CONSTRAINT_NAME, PT_DROP_ATTR_MTHD, PT_DROP_CONSTRAINT, PT_DROP_FK_CLAUSE, PT_DROP_INDEX_CLAUSE, PT_DROP_PARTITION, PT_DROP_PRIMARY_CLAUSE, PT_DROP_QUERY, PT_DROP_RESOLUTION, PT_DROP_SUPCLASS, PT_FILE_RENAME, PT_FUNCTION_RENAME, PT_INDEX_NAME, PT_META_ATTR, PT_METHOD, PT_MODIFY_ATTR_MTHD, PT_MODIFY_DEFAULT, PT_MODIFY_QUERY, PT_PRINT_ALIAS, pt_print_bytes(), pt_print_bytes_l(), pt_print_col_def_constraint(), PT_PROMOTE_PARTITION, PT_REMOVE_PARTITION, PT_RENAME_ATTR_MTHD, PT_RENAME_ENTITY, PT_RENAME_RESOLUTION, PT_REORG_PARTITION, PT_RESET_QUERY, pt_show_misc_type(), PT_SUPPRESS_INDEX, PT_SUPPRESS_META_ATTR_CLASS, PT_SUPPRESS_ORDERING, PT_SUPPRESS_RESOLVED, pt_alter_info::query, pt_alter_info::rename, pt_alter_info::resolution_list, pt_alter_info::sup_class_list, pt_alter_info::super, and pt_alter_info::user.
Referenced by pt_print_alter().
static PARSER_VARCHAR * pt_print_alter_serial (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 7904 of file parse_tree_cl.c.
References pt_serial_info::cached_num_val, pt_serial_info::comment, pt_serial_info::cyclic, pt_serial_info::increment_val, parser_node::info, pt_serial_info::max_val, pt_serial_info::min_val, pt_serial_info::no_cache, pt_serial_info::no_cyclic, pt_serial_info::no_max, pt_serial_info::no_min, NULL, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes(), pt_statement_info::serial, pt_serial_info::serial_name, and pt_serial_info::start_val.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_alter_stored_procedure (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 7985 of file parse_tree_cl.c.
References assert, pt_stored_proc_info::comment, parser_node::info, pt_stored_proc_info::name, NULL, pt_stored_proc_info::owner, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes(), pt_print_bytes_l(), PT_SP_PROCEDURE, pt_statement_info::sp, and pt_stored_proc_info::type.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_alter_trigger (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 6336 of file parse_tree_cl.c.
References pt_statement_info::alter_trigger, pt_alter_trigger_info::comment, parser_node::info, NULL, PT_ACTIVE, pt_append_nulstring(), pt_append_varchar(), PT_INACTIVE, pt_print_bytes(), pt_print_bytes_l(), pt_show_misc_type(), pt_alter_trigger_info::trigger_owner, pt_alter_trigger_info::trigger_priority, pt_alter_trigger_info::trigger_spec_list, and pt_alter_trigger_info::trigger_status.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_alter_user (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 6275 of file parse_tree_cl.c.
References pt_statement_info::alter_user, pt_alter_user_info::comment, parser_node::info, NULL, pt_alter_user_info::password, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes(), and pt_alter_user_info::user_name.
Referenced by pt_init_print_f().
PARSER_VARCHAR* pt_print_and_list (PARSER_CONTEXT * parser, const PT_NODE * p)
Definition at line 2764 of file parse_tree_cl.c.
References pt_statement_info::expr, parser_context::flag, parser_node::info, parser_context::is_in_and_list, parser_node::next, parser_node::node_type, NULL, parser_node::or_next, pt_expr_info::paren_type, pt_append_nulstring(), pt_append_varchar(), PT_EXPR, and pt_print_bytes().
Referenced by pt_print_alter_index(), pt_print_bytes(), pt_print_check_option(), pt_print_create_index(), pt_print_delete(), pt_print_drop_index(), pt_print_insert(), pt_print_merge(), pt_print_select(), pt_print_spec(), and pt_print_update().
static PARSER_VARCHAR * pt_print_attach (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 6394 of file parse_tree_cl.c.
References pt_statement_info::attach, parser_node::info, NULL, pt_append_nulstring(), PT_MEMB_BUF_SIZE, and pt_attach_info::trans_id.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_attr_def (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 6441 of file parse_tree_cl.c.
References pt_statement_info::attr_def, pt_attr_def_info::attr_name, pt_attr_def_info::attr_type, pt_attr_def_info::auto_increment, pt_data_type_info::collation_id, pt_attr_def_info::comment, pt_attr_def_info::constrain_not_null, parser_context::custom_print, pt_attr_def_info::data_default, pt_statement_info::data_type, parser_node::data_type, db_default_expression_string(), DB_DEFAULT_NONE, DB_MAX_VARBIT_PRECISION, DB_MAX_VARCHAR_PRECISION, DB_MAX_VARNCHAR_PRECISION, pt_data_type_info::dec_precision, pt_data_type_info::enumeration, pt_data_type_info::has_coll_spec, pt_data_type_info::has_cs_spec, parser_node::info, lang_get_collation_name(), NULL, pt_attr_def_info::on_update, pt_attr_def_info::ordering_info, pt_data_type_info::precision, pt_append_nulstring(), pt_append_varchar(), PT_HAS_COLLATION, PT_MEMB_BUF_SIZE, PT_META_ATTR, pt_print_bytes(), pt_print_bytes_l(), pt_show_type_enum(), PT_SUPPRESS_META_ATTR_CLASS, PT_SUPPRESS_ORDERING, PT_TYPE_BIGINT, PT_TYPE_BIT, PT_TYPE_CHAR, PT_TYPE_DATE, PT_TYPE_DATETIME, PT_TYPE_DATETIMELTZ, PT_TYPE_DATETIMETZ, PT_TYPE_DOUBLE, PT_TYPE_ENUMERATION, PT_TYPE_FLOAT, PT_TYPE_INTEGER, PT_TYPE_MONETARY, PT_TYPE_NCHAR, PT_TYPE_NONE, PT_TYPE_NUMERIC, PT_TYPE_OBJECT, PT_TYPE_SMALLINT, PT_TYPE_TIME, PT_TYPE_TIMESTAMP, PT_TYPE_TIMESTAMPLTZ, PT_TYPE_TIMESTAMPTZ, PT_TYPE_VARBIT, PT_TYPE_VARCHAR, PT_TYPE_VARNCHAR, TP_FLOATING_PRECISION_VALUE, and parser_node::type_enum.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_attr_ordering (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 6653 of file parse_tree_cl.c.
References pt_attr_ordering_info::after, pt_statement_info::attr_ordering, pt_attr_ordering_info::first, parser_node::info, NULL, pt_append_nulstring(), pt_append_varchar(), and pt_print_bytes().
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_auth_cmd (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 6706 of file parse_tree_cl.c.
References pt_auth_cmd_info::attr_mthd_list, pt_auth_cmd_info::auth_cmd, pt_statement_info::auth_cmd, parser_node::info, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes_l(), and pt_show_priv().
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_auto_increment (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 12655 of file parse_tree_cl.c.
References pt_statement_info::auto_increment, pt_auto_increment_info::increment_val, parser_node::info, NULL, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes(), and pt_auto_increment_info::start_val.
Referenced by pt_init_print_f().
PARSER_VARCHAR* pt_print_bytes (PARSER_CONTEXT * parser, const PT_NODE * node)
Definition at line 2268 of file parse_tree_cl.c.
References CAST_POINTER_TO_NODE, parser_node::flag, parser_context::flag, parser_node::is_cnf_start, parser_context::is_in_and_list, parser_node::node_type, NULL, PT_LAST_NODE_NUMBER, pt_print_and_list(), and pt_print_f.
Referenced by create_or_drop_index_helper(), do_recreate_filter_index_constr(), do_replicate_statement(), parser_print_tree(), parser_print_tree_with_quotes(), pt_fold_const_expr(), pt_get_attr_list_of_derived_table(), pt_print_alter(), pt_print_alter_index(), pt_print_alter_one_clause(), pt_print_alter_serial(), pt_print_alter_stored_procedure(), pt_print_alter_trigger(), pt_print_alter_user(), pt_print_and_list(), pt_print_attr_def(), pt_print_attr_ordering(), pt_print_auto_increment(), pt_print_bytes_alias(), pt_print_bytes_l(), pt_print_bytes_spec_list(), pt_print_col_def_constraint(), pt_print_constraint(), pt_print_create_entity(), pt_print_create_index(), pt_print_create_serial(), pt_print_create_stored_procedure(), pt_print_create_trigger(), pt_print_create_user(), pt_print_data_default(), pt_print_datatype(), pt_print_delete(), pt_print_difference(), pt_print_dot(), pt_print_drop_index(), pt_print_drop_serial(), pt_print_drop_user(), pt_print_evaluate(), pt_print_event_spec(), pt_print_event_target(), pt_print_expr(), pt_print_file_path(), pt_print_function(), pt_print_get_opt_lvl(), pt_print_get_stats(), pt_print_get_trigger(), pt_print_get_xaction(), pt_print_host_var(), pt_print_index_columns(), pt_print_insert(), pt_print_intersection(), pt_print_isolation_lvl(), pt_print_json_table(), pt_print_json_table_column_info(), pt_print_json_table_node(), pt_print_merge(), pt_print_method_call(), pt_print_method_def(), pt_print_name(), pt_print_named_arg(), pt_print_partition(), pt_print_parts(), pt_print_range_op(), pt_print_rename(), pt_print_rename_trigger(), pt_print_resolution(), pt_print_rollback_work(), pt_print_savepoint(), pt_print_scope(), pt_print_select(), pt_print_session_variables(), pt_print_set_names(), pt_print_set_opt_lvl(), pt_print_set_sys_params(), pt_print_set_timezone(), pt_print_set_trigger(), pt_print_sort_spec(), pt_print_sp_parameter(), pt_print_spec(), pt_print_timeout(), pt_print_trigger_action(), pt_print_union_stmt(), and pt_print_update().
PARSER_VARCHAR* pt_print_bytes_alias (PARSER_CONTEXT * parser, const PT_NODE * node)
Definition at line 2244 of file parse_tree_cl.c.
References parser_node::alias_print, NULL, pt_append_name(), and pt_print_bytes().
Referenced by pt_print_alias(), and pt_print_pointer().
PARSER_VARCHAR* pt_print_bytes_l (PARSER_CONTEXT * parser, const PT_NODE * p)
Definition at line 2314 of file parse_tree_cl.c.
References pt_string_block::body, parser_node::flag, parser_node::is_cnf_start, pt_string_block::length, parser_context::max_print_len, parser_node::next, NULL, pt_append_nulstring(), pt_print_bytes(), pt_string_block::size, and strcat_with_realloc().
Referenced by parser_print_tree_list(), pt_print_alter_one_clause(), pt_print_alter_stored_procedure(), pt_print_alter_trigger(), pt_print_attr_def(), pt_print_auth_cmd(), pt_print_col_def_constraint(), pt_print_constraint(), pt_print_create_entity(), pt_print_create_stored_procedure(), pt_print_cte(), pt_print_datatype(), pt_print_delete(), pt_print_difference(), pt_print_do(), pt_print_drop(), pt_print_drop_stored_procedure(), pt_print_drop_trigger(), pt_print_drop_variable(), pt_print_execute_trigger(), pt_print_expr(), pt_print_function(), pt_print_get_stats(), pt_print_grant(), pt_print_index_columns(), pt_print_insert(), pt_print_insert_value(), pt_print_intersection(), pt_print_merge(), pt_print_method_call(), pt_print_method_def(), pt_print_node_list(), pt_print_partition(), pt_print_parts(), pt_print_remove_trigger(), pt_print_revoke(), pt_print_select(), pt_print_set_session_variables(), pt_print_set_xaction(), pt_print_showstmt(), pt_print_spec(), pt_print_table_option(), pt_print_trigger_spec_list(), pt_print_truncate(), pt_print_union_stmt(), pt_print_update(), pt_print_update_stats(), and pt_print_value().
PARSER_VARCHAR* pt_print_bytes_spec_list (PARSER_CONTEXT * parser, const PT_NODE * p)
Definition at line 2385 of file parse_tree_cl.c.
References parser_node::info, pt_spec_info::join_type, parser_node::next, parser_node::node_type, pt_append_bytes(), pt_append_varchar(), PT_JOIN_CROSS, PT_JOIN_FULL_OUTER, PT_JOIN_INNER, PT_JOIN_LEFT_OUTER, PT_JOIN_NONE, PT_JOIN_RIGHT_OUTER, pt_print_bytes(), PT_SPEC, and pt_statement_info::spec.
Referenced by pt_print_delete(), pt_print_merge(), pt_print_select(), and pt_print_update().
static PARSER_VARCHAR * pt_print_check_option (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 6745 of file parse_tree_cl.c.
References pt_statement_info::check_option, pt_check_option_info::expr, parser_node::info, NULL, and pt_print_and_list().
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_col_def_constraint (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 15941 of file parse_tree_cl.c.
References assert, pt_constraint_info::check, pt_statement_info::constraint, pt_constraint_info::deferrable, pt_foreign_key_info::delete_action, pt_constraint_info::foreign_key, parser_node::info, pt_constraint_info::initially_deferred, pt_foreign_key_info::match_type, pt_constraint_info::name, parser_node::node_type, NULL, pt_append_nulstring(), pt_append_varchar(), PT_CONSTRAIN_CHECK, PT_CONSTRAIN_FOREIGN_KEY, PT_CONSTRAIN_NOT_NULL, PT_CONSTRAIN_NULL, PT_CONSTRAIN_PRIMARY_KEY, PT_CONSTRAIN_UNIQUE, PT_CONSTRAIN_UNKNOWN, PT_CONSTRAINT, PT_MATCH_REGULAR, pt_print_bytes(), pt_print_bytes_l(), PT_RULE_RESTRICT, pt_show_misc_type(), pt_foreign_key_info::referenced_attrs, pt_foreign_key_info::referenced_class, pt_constraint_info::type, pt_constraint_info::un, and pt_foreign_key_info::update_action.
Referenced by pt_print_alter_one_clause().
static PARSER_VARCHAR * pt_print_commit_work (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 6776 of file parse_tree_cl.c.
References pt_statement_info::commit_work, parser_node::info, NULL, pt_append_nulstring(), and pt_commit_work_info::retain_lock.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_constraint (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 16040 of file parse_tree_cl.c.
References pt_foreign_key_info::attrs, pt_constraint_info::check, pt_constraint_info::comment, pt_statement_info::constraint, pt_constraint_info::deferrable, pt_foreign_key_info::delete_action, pt_constraint_info::foreign_key, parser_node::info, pt_constraint_info::initially_deferred, pt_foreign_key_info::match_type, pt_constraint_info::name, pt_constraint_info::primary_key, pt_append_nulstring(), pt_append_varchar(), PT_CONSTRAIN_CHECK, PT_CONSTRAIN_FOREIGN_KEY, PT_CONSTRAIN_NOT_NULL, PT_CONSTRAIN_NULL, PT_CONSTRAIN_PRIMARY_KEY, PT_CONSTRAIN_UNIQUE, PT_CONSTRAIN_UNKNOWN, PT_MATCH_REGULAR, pt_print_bytes(), pt_print_bytes_l(), PT_RULE_RESTRICT, pt_show_misc_type(), pt_foreign_key_info::referenced_attrs, pt_foreign_key_info::referenced_class, pt_constraint_info::type, pt_constraint_info::un, pt_constraint_info::unique, and pt_foreign_key_info::update_action.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_create_entity (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 6840 of file parse_tree_cl.c.
References pt_create_entity_info::as_query_list, pt_create_entity_info::attr_def_list, pt_create_entity_info::class_attr_def_list, pt_statement_info::constraint, pt_create_entity_info::constraint_list, pt_statement_info::create_entity, pt_create_entity_info::create_index, pt_create_entity_info::create_like, pt_create_entity_info::create_select, pt_create_entity_info::create_select_action, parser_context::custom_print, pt_create_entity_info::entity_name, pt_create_entity_info::entity_type, pt_create_entity_info::if_not_exists, parser_node::info, pt_create_entity_info::method_def_list, pt_create_entity_info::method_file_list, parser_node::next, NULL, pt_create_entity_info::object_id_list, pt_create_entity_info::or_replace, pt_create_entity_info::partition_info, pt_append_bytes(), pt_append_nulstring(), pt_append_varchar(), PT_CASCADED, PT_CONSTRAIN_NOT_NULL, PT_CONSTRAIN_NULL, PT_CREATE_SELECT_IGNORE, PT_CREATE_SELECT_REPLACE, PT_LOCAL, PT_PRINT_ALIAS, pt_print_bytes(), pt_print_bytes_l(), pt_show_misc_type(), PT_SUPPRESS_INDEX, PT_SUPPRESS_META_ATTR_CLASS, PT_SUPPRESS_RESOLVED, PT_VCLASS, pt_create_entity_info::resolution_list, pt_create_entity_info::supclass_list, pt_create_entity_info::table_option_list, pt_constraint_info::type, pt_create_entity_info::update, pt_create_entity_info::vclass_comment, and pt_create_entity_info::with_check_option.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_create_index (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 7121 of file parse_tree_cl.c.
References pt_sort_spec_info::asc_or_desc, assert, pt_index_info::column_names, pt_index_info::comment, parser_context::custom_print, pt_sort_spec_info::expr, pt_statement_info::index, pt_index_info::index_name, pt_index_info::index_status, pt_index_info::indexed_class, parser_node::info, pt_statement_info::name, NULL, pt_name_info::original, pt_index_info::prefix_length, pt_append_bytes(), pt_append_nulstring(), pt_append_varchar(), PT_DESC, pt_print_and_list(), pt_print_bytes(), pt_print_index_columns(), PT_SUPPRESS_INDEX, PT_SUPPRESS_RESOLVED, pt_index_info::reverse, SM_INVISIBLE_INDEX, SM_ONLINE_INDEX_BUILDING_IN_PROGRESS, pt_statement_info::sort_spec, strlen, pt_index_info::unique, and pt_index_info::where.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_create_serial (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 7823 of file parse_tree_cl.c.
References pt_serial_info::cached_num_val, pt_serial_info::comment, pt_serial_info::cyclic, pt_serial_info::increment_val, parser_node::info, pt_serial_info::max_val, pt_serial_info::min_val, pt_serial_info::no_cache, pt_serial_info::no_cyclic, pt_serial_info::no_max, pt_serial_info::no_min, NULL, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes(), pt_statement_info::serial, pt_serial_info::serial_name, and pt_serial_info::start_val.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_create_stored_procedure (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 7386 of file parse_tree_cl.c.
References pt_stored_proc_info::comment, parser_node::info, pt_stored_proc_info::java_method, pt_stored_proc_info::name, NULL, pt_stored_proc_info::or_replace, pt_stored_proc_info::param_list, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes(), pt_print_bytes_l(), pt_show_misc_type(), pt_show_type_enum(), PT_SP_FUNCTION, pt_stored_proc_info::ret_type, pt_statement_info::sp, and pt_stored_proc_info::type.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_create_trigger (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 7308 of file parse_tree_cl.c.
References pt_create_trigger_info::action_time, pt_create_trigger_info::comment, pt_create_trigger_info::condition_time, pt_statement_info::create_trigger, parser_node::info, NULL, pt_append_nulstring(), pt_append_varchar(), PT_MISC_DUMMY, pt_print_bytes(), pt_show_misc_type(), pt_create_trigger_info::trigger_action, pt_create_trigger_info::trigger_condition, pt_create_trigger_info::trigger_event, pt_create_trigger_info::trigger_name, pt_create_trigger_info::trigger_priority, and pt_create_trigger_info::trigger_status.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_create_user (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 7245 of file parse_tree_cl.c.
References pt_create_user_info::comment, pt_statement_info::create_user, pt_create_user_info::groups, parser_node::info, pt_create_user_info::members, NULL, pt_create_user_info::password, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes(), and pt_create_user_info::user_name.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_cte (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 16599 of file parse_tree_cl.c.
References pt_cte_info::as_attr_list, pt_statement_info::cte, parser_node::info, pt_cte_info::name, pt_cte_info::non_recursive_part, NULL, pt_cte_info::only_all, PT_ALL, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes_l(), and pt_cte_info::recursive_part.
Referenced by pt_init_print_f(), and pt_print_with_clause().
static PARSER_VARCHAR * pt_print_data_default (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 8134 of file parse_tree_cl.c.
References pt_statement_info::data_default, pt_data_default_info::default_value, parser_node::info, parser_node::node_type, pt_append_nulstring(), pt_append_varchar(), PT_DEFAULT, PT_IS_QUERY_NODE_TYPE, pt_print_bytes(), PT_SHARED, and pt_data_default_info::shared.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_datatype (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 8201 of file parse_tree_cl.c.
References pt_data_type_info::collation_id, pt_statement_info::data_type, parser_node::data_type, DB_MAX_VARBIT_PRECISION, DB_MAX_VARCHAR_PRECISION, DB_MAX_VARNCHAR_PRECISION, pt_data_type_info::dec_precision, pt_data_type_info::entity, pt_data_type_info::enumeration, parser_node::info, lang_get_collation_name(), LANG_SYS_COLLATION, NULL, pt_data_type_info::precision, pt_append_nulstring(), pt_append_varchar(), PT_MEMB_BUF_SIZE, pt_print_bytes(), pt_print_bytes_l(), pt_show_type_enum(), PT_TYPE_BIT, PT_TYPE_CHAR, PT_TYPE_DOUBLE, PT_TYPE_ENUMERATION, PT_TYPE_FLOAT, PT_TYPE_MULTISET, PT_TYPE_NCHAR, PT_TYPE_NUMERIC, PT_TYPE_OBJECT, PT_TYPE_SEQUENCE, PT_TYPE_SET, PT_TYPE_VARBIT, PT_TYPE_VARCHAR, PT_TYPE_VARNCHAR, TP_FLOATING_PRECISION_VALUE, and parser_node::type_enum.
Referenced by pt_init_print_f().
PARSER_VARCHAR* pt_print_db_value (PARSER_CONTEXT * parser, const struct db_value * val)
Definition at line 2507 of file parse_tree_cl.c.
References parser_context::custom_print, db_get_monetary(), db_get_set(), db_set_get(), db_set_size(), DB_TYPE_BIT, DB_TYPE_DATE, DB_TYPE_DATETIME, DB_TYPE_DATETIMELTZ, DB_TYPE_DATETIMETZ, DB_TYPE_MONETARY, DB_TYPE_MULTISET, DB_TYPE_OBJECT, DB_TYPE_SEQUENCE, DB_TYPE_SET, DB_TYPE_TIME, DB_TYPE_TIMESTAMP, DB_TYPE_TIMESTAMPLTZ, DB_TYPE_TIMESTAMPTZ, DB_TYPE_VARBIT, DB_VALUE_TYPE, db_value_printer::describe_money(), db_value_printer::describe_value(), error(), string_buffer::get_buffer(), i, NO_ERROR, NULL, pt_append_nulstring(), pt_db_to_type_enum(), PT_PAD_BYTE, and pt_show_type_enum().
Referenced by do_replicate_statement(), pt_print_insert_value(), pt_print_json_table_column_error_or_empty_behavior(), and pt_print_node_value().
static PARSER_VARCHAR * pt_print_delete (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 8382 of file parse_tree_cl.c.
References pt_statement_info::delete_, parser_node::etc, pt_delete_info::hint, parser_node::info, pt_delete_info::limit, pt_statement_info::name, parser_node::next, NULL, pt_delete_info::ordered_hint, pt_name_info::original, pt_append_nulstring(), pt_append_varchar(), PT_HINT_LK_TIMEOUT, PT_HINT_NO_COVERING_IDX, PT_HINT_NO_IDX_DESC, PT_HINT_NO_LOGGING, PT_HINT_NO_MULTI_RANGE_OPT, PT_HINT_NO_SORT_LIMIT, PT_HINT_NONE, PT_HINT_ORDERED, PT_HINT_USE_IDX, PT_HINT_USE_IDX_DESC, PT_HINT_USE_MERGE, PT_HINT_USE_NL, PT_HINT_USE_SBR, PT_IDX_HINT_CLASS_NONE, pt_print_and_list(), pt_print_bytes(), pt_print_bytes_l(), pt_print_bytes_spec_list(), pt_name_info::resolved, pt_delete_info::rewrite_limit, pt_delete_info::search_cond, pt_delete_info::spec, pt_delete_info::target_classes, pt_delete_info::use_idx_hint, pt_delete_info::use_merge_hint, pt_delete_info::use_nl_hint, pt_delete_info::using_index, pt_delete_info::waitsecs_hint, and pt_delete_info::with.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_difference (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 8609 of file parse_tree_cl.c.
References pt_query_info::all_distinct, pt_union_info::arg1, pt_union_info::arg2, pt_query_info::flag, parser_node::info, pt_query_info::limit, NULL, pt_query_info::order_by, pt_query_info::orderby_for, PT_ALL, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes(), pt_print_bytes_l(), pt_query_info::q, pt_statement_info::query, pt_query_info::rewrite_limit, pt_query_info::union_, and pt_query_info::with.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_do (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 7621 of file parse_tree_cl.c.
References parser_context::custom_print, pt_statement_info::do_, pt_do_info::expr, parser_node::info, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes_l(), and PT_SUPPRESS_RESOLVED.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_dot (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 8681 of file parse_tree_cl.c.
References parser_node::alias_print, pt_dot_info::arg1, pt_dot_info::arg2, parser_context::custom_print, pt_statement_info::dot, parser_node::info, NULL, pt_append_nulstring(), pt_append_varchar(), PT_PRINT_ALIAS, and pt_print_bytes().
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_drop (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 8729 of file parse_tree_cl.c.
References parser_context::custom_print, pt_statement_info::drop, pt_drop_info::if_exists, parser_node::info, pt_drop_info::is_cascade_constraints, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes_l(), PT_SUPPRESS_RESOLVED, and pt_drop_info::spec_list.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_drop_index (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 8779 of file parse_tree_cl.c.
References assert, parser_context::custom_print, pt_statement_info::index, pt_index_info::index_name, pt_index_info::indexed_class, parser_node::info, pt_statement_info::name, NULL, pt_name_info::original, pt_append_bytes(), pt_append_nulstring(), pt_append_varchar(), pt_print_and_list(), pt_print_bytes(), pt_print_index_columns(), PT_SUPPRESS_RESOLVED, pt_index_info::reverse, strlen, pt_index_info::unique, and pt_index_info::where.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_drop_serial (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 8033 of file parse_tree_cl.c.
References pt_serial_info::if_exists, parser_node::info, NULL, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes(), pt_statement_info::serial, and pt_serial_info::serial_name.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_drop_session_variables (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 15377 of file parse_tree_cl.c.
References pt_statement_info::drop_session_var, parser_node::info, NULL, pt_append_nulstring(), pt_append_varchar(), pt_print_session_variables(), and pt_drop_session_var_info::variables.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_drop_stored_procedure (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 7432 of file parse_tree_cl.c.
References parser_node::info, pt_stored_proc_info::name, NULL, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes_l(), pt_show_misc_type(), pt_statement_info::sp, and pt_stored_proc_info::type.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_drop_trigger (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 8886 of file parse_tree_cl.c.
References pt_statement_info::drop_trigger, parser_node::info, NULL, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes_l(), and pt_drop_trigger_info::trigger_spec_list.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_drop_user (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 8852 of file parse_tree_cl.c.
References pt_statement_info::drop_user, parser_node::info, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes(), and pt_drop_user_info::user_name.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_drop_variable (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 8920 of file parse_tree_cl.c.
References pt_statement_info::drop_variable, parser_node::info, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes_l(), and pt_drop_variable_info::var_names.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_error_msg (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 15852 of file parse_tree_cl.c.
References parser_node::column_number, PT_ZZ_ERROR_MSG_INFO::error_message, pt_statement_info::error_msg, parser_node::info, parser_node::line_number, pt_append_nulstring(), PT_MEMB_ERR_BUF_SIZE, and PT_ZZ_ERROR_MSG_INFO::statement_number.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_evaluate (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 9235 of file parse_tree_cl.c.
References pt_statement_info::evaluate, pt_evaluate_info::expression, parser_node::info, pt_evaluate_info::into_var, NULL, pt_append_nulstring(), pt_append_varchar(), and pt_print_bytes().
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_event_object (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 9276 of file parse_tree_cl.c.
References NULL.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_event_spec (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 9305 of file parse_tree_cl.c.
References pt_statement_info::event_spec, pt_event_spec_info::event_target, pt_event_spec_info::event_type, parser_node::info, NULL, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes(), and pt_show_event_type().
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_event_target (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 9343 of file parse_tree_cl.c.
References pt_event_target_info::attribute, pt_event_target_info::class_name, pt_statement_info::event_target, parser_node::info, NULL, pt_append_nulstring(), pt_append_varchar(), and pt_print_bytes().
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_execute_trigger (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 9384 of file parse_tree_cl.c.
References pt_statement_info::execute_trigger, parser_node::info, NULL, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes_l(), and pt_execute_trigger_info::trigger_spec_list.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_expr (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 9505 of file parse_tree_cl.c.
References parser_node::alias_print, pt_expr_info::arg1, pt_expr_info::arg2, pt_expr_info::arg3, assert, assert_release, pt_string_block::body, parser_varchar::bytes, pt_expr_info::cast_type, pt_data_type_info::collation_flag, pt_data_type_info::collation_id, pt_expr_info::continued_case, parser_context::custom_print, pt_statement_info::data_type, parser_node::data_type, pt_value_info::data_value, pt_statement_info::expr, parser_node::flag, pt_data_value::i, parser_node::info, pt_value_info::is_collate_allowed, parser_node::is_hidden_column, lang_get_codeset_name(), lang_get_collation_name(), lang_get_lang_id_from_flag(), lang_get_lang_name_from_id(), lang_id(), LANG_SYS_CODESET, LANG_SYS_COLLATION, pt_string_block::length, parser_varchar::length, parser_node::node_type, NULL, pt_expr_info::op, parser_node::or_next, pt_expr_info::paren_type, pt_value_info::print_collation, PT_ABS, PT_ACOS, PT_ADD_MONTHS, PT_ADDDATE, PT_ADDTIME, PT_AES_DECRYPT, PT_AES_ENCRYPT, pt_append_nulstring(), pt_append_varchar(), PT_ASCII, PT_ASIN, PT_ATAN, PT_ATAN2, PT_BETWEEN, PT_BETWEEN_GE_INF, PT_BETWEEN_GE_LT, PT_BETWEEN_GT_INF, PT_BETWEEN_INF_LE, PT_BETWEEN_INF_LT, PT_BIN, PT_BIT_COUNT, PT_BIT_LENGTH, PT_BIT_NOT, PT_BIT_TO_BLOB, PT_BLOB_FROM_FILE, PT_BLOB_LENGTH, PT_BLOB_TO_BIT, PT_BOTH, PT_CASE, PT_CAST, PT_CEIL, PT_CHAR_LENGTH, PT_CHAR_TO_BLOB, PT_CHAR_TO_CLOB, PT_CHARSET, PT_CHR, PT_CLOB_FROM_FILE, PT_CLOB_LENGTH, PT_CLOB_TO_CHAR, PT_COALESCE, PT_COERCIBILITY, PT_COLLATION, PT_CONCAT, PT_CONCAT_WS, PT_CONNECT_BY_ISCYCLE, PT_CONNECT_BY_ISLEAF, PT_CONNECT_BY_ROOT, PT_CONV, PT_CONVERT_RANGE, PT_COS, PT_COT, PT_CRC32, PT_CURRENT_DATE, PT_CURRENT_DATETIME, PT_CURRENT_TIME, PT_CURRENT_TIMESTAMP, PT_CURRENT_USER, PT_CURRENT_VALUE, PT_DATABASE, PT_DATE_ADD, PT_DATE_FORMAT, PT_DATE_SUB, PT_DATEDIFF, PT_DATEF, PT_DAY, PT_DAY_HOUR, PT_DAY_MILLISECOND, PT_DAY_MINUTE, PT_DAY_SECOND, PT_DAYF, PT_DAYOFMONTH, PT_DAYOFWEEK, PT_DAYOFYEAR, PT_DBTIMEZONE, PT_DECODE, PT_DECR, PT_DEFAULTF, PT_DEFINE_VARIABLE, PT_DEGREES, PT_DISK_SIZE, PT_DOT_, PT_DRAND, PT_DRANDOM, PT_EVALUATE_VARIABLE, PT_EXEC_STATS, PT_EXISTS, PT_EXP, PT_EXPR, PT_EXPR_INFO_CAST_COLL_MODIFIER, PT_EXPR_INFO_IS_FLAGED, PT_EXTRACT, PT_FIELD, PT_FINDINSET, PT_FLOOR, PT_FORMAT, PT_FROM_BASE64, PT_FROM_TZ, PT_FROM_UNIXTIME, PT_FROMDAYS, PT_FUNCTION_HOLDER, PT_GET_COLLATION_MODIFIER, PT_GREATEST, PT_HAS_COLLATION, PT_HEX, PT_HOST_VAR, PT_HOUR, PT_HOUR_MILLISECOND, PT_HOUR_MINUTE, PT_HOUR_SECOND, PT_HOURF, PT_IF, PT_IFNULL, PT_INCR, PT_INDEX_CARDINALITY, PT_INDEX_PREFIX, PT_INET_ATON, PT_INET_NTOA, PT_INST_NUM, PT_INSTR, PT_ISNULL, PT_LAST_DAY, PT_LAST_INSERT_ID, PT_LEADING, PT_LEAST, PT_LEFT, PT_LEVEL, PT_LIKE_ESCAPE, PT_LIKE_LOWER_BOUND, PT_LIKE_UPPER_BOUND, PT_LIST_DBS, PT_LN, PT_LOCATE, PT_LOG, PT_LOG10, PT_LOG2, PT_LOWER, PT_LPAD, PT_LTRIM, PT_MAKEDATE, PT_MAKETIME, PT_MD5, PT_MEMB_BUF_SIZE, PT_MID, PT_MILLISECOND, PT_MINUTE, PT_MINUTE_MILLISECOND, PT_MINUTE_SECOND, PT_MINUTEF, PT_MODULUS, PT_MONTH, PT_MONTHF, PT_MONTHS_BETWEEN, PT_NAME, PT_NEW_TIME, PT_NEXT_VALUE, PT_NOT, PT_NULLIF, PT_NVL, PT_NVL2, PT_OCTET_LENGTH, PT_OID_OF_DUPLICATE_KEY, PT_ORDERBY_NUM, PT_PATH_EXPR_SET, PT_PI, PT_POSITION, PT_POWER, PT_PRINT_ALIAS, pt_print_bytes(), pt_print_bytes_l(), pt_print_function(), pt_print_range_op(), PT_PRIOR, PT_QPRIOR, PT_QUARTER, PT_QUARTERF, PT_RADIANS, PT_RAND, PT_RANDOM, PT_RANGE, PT_REPEAT, PT_REPLACE, PT_REVERSE, PT_RIGHT, PT_ROUND, PT_ROW_COUNT, PT_ROWNUM, PT_RPAD, PT_RTRIM, PT_SCHEMA, PT_SCHEMA_DEF, PT_SEARCHED_CASE, PT_SECOND, PT_SECOND_MILLISECOND, PT_SECONDF, PT_SECTOTIME, PT_SESSIONTIMEZONE, PT_SHA_ONE, PT_SHA_TWO, pt_show_binopcode(), PT_SIGN, PT_SIMPLE_CASE, PT_SIN, PT_SLEEP, PT_SPACE, PT_SQRT, PT_STR_TO_DATE, PT_STRCMP, PT_SUBDATE, PT_SUBSTR, PT_SUBSTR_ORG, PT_SUBSTRING, PT_SUBSTRING_INDEX, PT_SUPPRESS_CHARSET_PRINT, PT_SYS_CONNECT_BY_PATH, PT_SYS_DATE, PT_SYS_DATETIME, PT_SYS_GUID, PT_SYS_TIME, PT_SYS_TIMESTAMP, PT_TAN, PT_TIME_FORMAT, PT_TIMEDIFF, PT_TIMEF, PT_TIMESTAMP, PT_TIMETOSEC, PT_TO_BASE64, PT_TO_CHAR, PT_TO_DATE, PT_TO_DATETIME, PT_TO_DATETIME_TZ, PT_TO_ENUMERATION_VALUE, PT_TO_NUMBER, PT_TO_TIME, PT_TO_TIMESTAMP, PT_TO_TIMESTAMP_TZ, PT_TODAYS, PT_TRACE_STATS, PT_TRAILING, PT_TRANSLATE, PT_TRIM, PT_TRUNC, PT_TYPE_NULL, PT_TYPEOF, PT_TZ_OFFSET, PT_UNARY_MINUS, PT_UNIX_TIMESTAMP, PT_UPPER, PT_USER, PT_UTC_DATE, PT_UTC_TIME, PT_UTC_TIMESTAMP, PT_VALUE, PT_VERSION, PT_WEEK, PT_WEEKDAY, PT_WEEKF, PT_WIDTH_BUCKET, PT_YEAR, PT_YEAR_MONTH, PT_YEARF, pt_expr_info::qualifier, pt_string_block::size, strcat_with_realloc(), pt_value_info::text, TP_DOMAIN_COLL_NORMAL, parser_node::type_enum, and pt_statement_info::value.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_file_path (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 11741 of file parse_tree_cl.c.
References pt_statement_info::file_path, parser_node::info, pt_append_varchar(), pt_print_bytes(), and pt_file_path_info::string.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_function (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 11800 of file parse_tree_cl.c.
References parser_node::alias_print, pt_function_info::all_or_distinct, pt_function_info::analytic, pt_function_info::arg_list, pt_sort_spec_info::asc_or_desc, parser_context::custom_print, pt_function_info::default_value, F_CLASS_OF, F_MULTISET, F_SEQUENCE, F_SET, fcode_get_lowercase_name(), pt_function_info::from_last, pt_statement_info::function, pt_function_info::function_type, pt_function_info::generic_name, pt_function_info::ignore_nulls, parser_node::info, pt_function_info::is_analytic, parser_node::next, NULL, pt_sort_spec_info::nulls_first_or_last, pt_function_info::offset, pt_function_info::order_by, pt_function_info::partition_by, pt_function_info::percentile, pt_append_nulstring(), pt_append_varchar(), PT_COUNT_STAR, PT_CUME_DIST, PT_DESC, PT_DISTINCT, PT_GENERIC, PT_GROUP_CONCAT, PT_LAG, PT_LEAD, PT_NTH_VALUE, PT_NULLS_FIRST, PT_NULLS_LAST, PT_PERCENT_RANK, PT_PERCENTILE_CONT, PT_PERCENTILE_DISC, PT_PRINT_ALIAS, pt_print_bytes(), pt_print_bytes_l(), PT_TOP_AGG_FUNC, pt_statement_info::sort_spec, and parser_node::spec_ident.
Referenced by pt_init_print_f(), and pt_print_expr().
static PARSER_VARCHAR * pt_print_get_opt_lvl (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 12075 of file parse_tree_cl.c.
References pt_get_opt_lvl_info::args, pt_statement_info::get_opt_lvl, parser_node::info, pt_get_opt_lvl_info::into_var, NULL, pt_get_opt_lvl_info::option, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes(), and pt_show_misc_type().
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_get_stats (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 15152 of file parse_tree_cl.c.
References pt_get_stats_info::args, pt_get_stats_info::class_, pt_statement_info::get_stats, parser_node::info, pt_get_stats_info::into_var, p, pt_append_nulstring(), pt_append_varchar(), PT_APPLY_WALK, PT_CURRENT, PT_DEFAULT, pt_print_bytes(), and pt_print_bytes_l().
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_get_trigger (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 12122 of file parse_tree_cl.c.
References pt_statement_info::get_trigger, parser_node::info, pt_get_trigger_info::into_var, NULL, pt_get_trigger_info::option, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes(), and pt_show_misc_type().
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_get_xaction (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 12161 of file parse_tree_cl.c.
References pt_statement_info::get_xaction, parser_node::info, pt_get_xaction_info::into_var, NULL, pt_get_xaction_info::option, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes(), and pt_show_misc_type().
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_grant (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 12215 of file parse_tree_cl.c.
References pt_grant_info::auth_cmd_list, parser_context::custom_print, pt_statement_info::grant, pt_grant_info::grant_option, parser_node::info, pt_append_nulstring(), pt_append_varchar(), PT_GRANT_OPTION, pt_print_bytes_l(), PT_SUPPRESS_RESOLVED, pt_grant_info::spec_list, and pt_grant_info::user_list.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_host_var (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 12263 of file parse_tree_cl.c.
References DB_TYPE_ENUMERATION, parser_context::error_msgs, parser_node::expected_domain, pt_statement_info::host_var, pt_host_var_info::index, parser_node::info, NULL, parser_node::or_next, parser_free_tree(), parser_context::print_db_value, pt_append_nulstring(), pt_append_varchar(), pt_has_error, PT_HOST_IN, PT_MEMB_BUF_SIZE, pt_print_bytes(), pt_host_var_info::str, TP_DOMAIN_TYPE, and pt_host_var_info::var_type.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_index_columns (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 16679 of file parse_tree_cl.c.
References pt_index_info::column_names, pt_index_info::func_pos, pt_index_info::function_expr, i, pt_statement_info::index, parser_node::info, parser_node::next, NULL, pt_append_bytes(), pt_append_varchar(), pt_print_bytes(), and pt_print_bytes_l().
Referenced by pt_print_alter_index(), pt_print_create_index(), and pt_print_drop_index().
static PARSER_VARCHAR * pt_print_insert (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 12372 of file parse_tree_cl.c.
References assert, pt_insert_info::attr_list, parser_context::custom_print, pt_insert_info::do_replace, pt_insert_info::hint, parser_node::info, pt_statement_info::insert, pt_insert_info::insert_mode, pt_insert_info::into_var, pt_insert_info::is_subinsert, pt_query_info::is_subquery, pt_node_list_info::list, pt_node_list_info::list_type, pt_statement_info::name, parser_node::next, pt_statement_info::node_list, parser_node::node_type, NULL, pt_insert_info::odku_assignments, pt_name_info::original, pt_append_name(), pt_append_nulstring(), pt_append_varchar(), PT_HINT_INSERT_MODE, PT_HINT_LK_TIMEOUT, PT_HINT_NO_LOGGING, PT_HINT_NONE, PT_HINT_USE_SBR, PT_IS_DEFAULT_VALUE, PT_IS_SUBINSERT, PT_IS_SUBQUERY, PT_IS_VALUE, pt_print_and_list(), pt_print_bytes(), pt_print_bytes_l(), PT_PRINT_ORIGINAL_BEFORE_CONST_FOLDING, PT_SELECT, PT_SUPPRESS_INTO, pt_statement_info::query, pt_insert_info::spec, pt_insert_info::value_clauses, pt_insert_info::waitsecs_hint, and pt_insert_info::where.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_insert_value (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 16540 of file parse_tree_cl.c.
References assert, parser_context::custom_print, parser_node::info, pt_statement_info::insert_value, NULL, pt_insert_value_info::original_node, pt_print_bytes_l(), PT_PRINT_DB_VALUE, pt_print_db_value(), and pt_insert_value_info::value.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_intersection (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 12587 of file parse_tree_cl.c.
References pt_query_info::all_distinct, pt_union_info::arg1, pt_union_info::arg2, pt_query_info::flag, parser_node::info, pt_query_info::limit, NULL, pt_query_info::order_by, pt_query_info::orderby_for, PT_ALL, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes(), pt_print_bytes_l(), pt_query_info::q, pt_statement_info::query, pt_query_info::rewrite_limit, pt_query_info::union_, and pt_query_info::with.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_isolation_lvl (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 12710 of file parse_tree_cl.c.
References pt_isolation_lvl_info::async_ws, parser_node::info, pt_isolation_lvl_info::instances, pt_statement_info::isolation_lvl, pt_isolation_lvl_info::level, NULL, pt_append_nulstring(), pt_append_varchar(), PT_NO_ISOLATION_LEVEL, pt_print_bytes(), PT_SERIALIZABLE, pt_show_misc_type(), and pt_isolation_lvl_info::schema.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_json_table (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 17988 of file parse_tree_cl.c.
References pt_json_table_info::expr, parser_node::info, pt_statement_info::json_table_info, NULL, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes(), cubregex::substr(), and pt_json_table_info::tree.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_json_table_column_error_or_empty_behavior (PARSER_CONTEXT * parser, PARSER_VARCHAR * pstr, const struct json_table_column_behavior & column_behavior) static
Definition at line 18120 of file parse_tree_cl.c.
References JSON_TABLE_DEFAULT_VALUE, json_table_column_behavior::m_behavior, json_table_column_behavior::m_default_value, NULL, pt_append_nulstring(), pt_append_varchar(), pt_json_table_column_behavior_to_string(), pt_print_db_value(), and cubregex::substr().
Referenced by pt_print_json_table_column_info().
static PARSER_VARCHAR * pt_print_json_table_column_info (PARSER_CONTEXT * parser, PT_NODE * p, PARSER_VARCHAR * pstr) static
Definition at line 18148 of file parse_tree_cl.c.
References assert, parser_node::data_type, pt_json_table_column_info::func, parser_node::info, pt_statement_info::json_table_column_info, JSON_TABLE_EXISTS, JSON_TABLE_EXTRACT, JSON_TABLE_ORDINALITY, pt_json_table_column_info::name, pt_statement_info::name, parser_node::node_type, NULL, pt_json_table_column_info::on_empty, pt_json_table_column_info::on_error, pt_name_info::original, pt_json_table_column_info::path, pt_append_nulstring(), pt_append_varchar(), PT_JSON_TABLE_COLUMN, pt_print_bytes(), pt_print_json_table_column_error_or_empty_behavior(), pt_type_enum_to_db_domain_name(), cubregex::substr(), pt_lambda_arg::type, and parser_node::type_enum.
Referenced by pt_print_json_table_columns().
static PARSER_VARCHAR * pt_print_json_table_columns (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 18237 of file parse_tree_cl.c.
References parser_node::next, NULL, pt_append_nulstring(), and pt_print_json_table_column_info().
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_json_table_node (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 18023 of file parse_tree_cl.c.
References pt_json_table_node_info::columns, parser_node::info, pt_statement_info::json_table_node_info, pt_json_table_node_info::nested_paths, NULL, pt_json_table_node_info::path, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes(), and cubregex::substr().
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_merge (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 16297 of file parse_tree_cl.c.
References pt_merge_info::assignment, pt_merge_info::attr_list, pt_merge_info::del_search_cond, pt_merge_info::has_delete, pt_merge_info::hint, pt_merge_info::index_hint, parser_node::info, pt_merge_info::insert, pt_merge_info::into, pt_node_list_info::list, pt_node_list_info::list_type, pt_statement_info::merge, pt_statement_info::node_list, NULL, pt_append_nulstring(), pt_append_varchar(), PT_HINT_LK_TIMEOUT, PT_HINT_NO_LOGGING, PT_HINT_NONE, PT_HINT_USE_INSERT_IDX, PT_HINT_USE_UPDATE_IDX, PT_IS_DEFAULT_VALUE, pt_print_and_list(), pt_print_bytes(), pt_print_bytes_l(), pt_print_bytes_spec_list(), pt_merge_info::search_cond, pt_merge_info::update, pt_merge_info::using_clause, pt_merge_info::value_clauses, and pt_merge_info::waitsecs_hint.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_method_call (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 12776 of file parse_tree_cl.c.
References pt_method_call_info::arg_list, pt_method_call_info::call_or_expr, parser_node::info, pt_statement_info::method_call, pt_method_call_info::method_name, pt_method_call_info::on_call_target, pt_append_nulstring(), pt_append_varchar(), PT_IS_CALL_STMT, pt_print_bytes(), and pt_print_bytes_l().
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_method_def (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 12838 of file parse_tree_cl.c.
References parser_node::data_type, pt_method_def_info::function_name, parser_node::info, pt_method_def_info::method_args_list, pt_statement_info::method_def, pt_method_def_info::method_name, pt_method_def_info::mthd_type, pt_append_nulstring(), pt_append_varchar(), PT_META_ATTR, pt_print_bytes(), pt_print_bytes_l(), pt_show_type_enum(), PT_TYPE_NONE, and parser_node::type_enum.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_name (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 12917 of file parse_tree_cl.c.
References parser_node::alias_print, assert, pt_name_info::custom_print, parser_context::custom_print, db_private_alloc, db_private_free_and_init, pt_spec_info::entity_name, parser_node::etc, if(), pt_name_info::indx_key_limit, parser_node::info, intl_identifier_lower(), intl_identifier_lower_string_size(), pt_name_info::meta_class, pt_statement_info::name, parser_node::next, NULL, pt_name_info::original, pt_name_info::path_correlation, pt_append_name(), pt_append_nulstring(), pt_append_varchar(), PT_CLASS, PT_CLASSOID_ATTR, PT_FORCE_ORIGINAL_TABLE_NAME, PT_HINT_NAME, PT_IDX_HINT_CLASS_NONE, PT_IDX_HINT_FORCE, PT_IDX_HINT_IGNORE, PT_INDEX_NAME, PT_META_CLASS, PT_NAME_INFO_DESC, PT_NAME_INFO_IS_FLAGED, PT_NORMAL, PT_OID_ATTR, PT_PARAMETER, PT_PRINT_ALIAS, pt_print_bytes(), PT_SUPPRESS_META_ATTR_CLASS, PT_SUPPRESS_RESOLVED, PT_SUPPRESS_SELECTOR, PT_TYPE_STAR, pt_name_info::resolved, pt_statement_info::spec, pt_name_info::spec_id, and parser_node::type_enum.
Referenced by pt_init_print_f(), and pt_print_tuple_value().
static PARSER_VARCHAR * pt_print_named_arg (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 16662 of file parse_tree_cl.c.
References parser_node::info, pt_named_arg_info::name, pt_statement_info::named_arg, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes(), and pt_named_arg_info::value.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_node_list (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 16243 of file parse_tree_cl.c.
References parser_node::info, pt_node_list_info::list, pt_statement_info::node_list, and pt_print_bytes_l().
Referenced by pt_init_print_f().
PARSER_VARCHAR* pt_print_node_value (PARSER_CONTEXT * parser, const PT_NODE * val)
Definition at line 2438 of file parse_tree_cl.c.
References parser_context::custom_print, db_get_object(), db_get_set(), DB_TYPE_OBJECT, DB_TYPE_VOBJ, DB_VALUE_DOMAIN_TYPE, er_msg(), error(), parser_node::expr_before_const_folding, parser_node::info, pt_name_info::meta_class, pt_statement_info::name, NO_ERROR, parser_node::node_type, NULL, PT_ERRORc, PT_HOST_VAR, PT_NAME, PT_PARAMETER, pt_print_db_value(), PT_PRINT_ORIGINAL_BEFORE_CONST_FOLDING, PT_TYPE_OBJECT, PT_VALUE, pt_value_to_db(), set_get_setobj(), setobj_get_element_ptr(), parser_node::type_enum, and vid_get_keys().
Referenced by qo_scan_fprint(), qo_scan_info(), and qo_term_dump().
static PARSER_VARCHAR * pt_print_partition (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 7710 of file parse_tree_cl.c.
References pt_partition_info::expr, pt_partition_info::hashsize, parser_node::info, NULL, pt_statement_info::partition, pt_partition_info::parts, pt_append_nulstring(), pt_append_varchar(), PT_MEMB_BUF_SIZE, PT_PARTITION_HASH, pt_print_bytes(), pt_print_bytes_l(), pt_show_partition_type(), and pt_partition_info::type.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_parts (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 7768 of file parse_tree_cl.c.
References pt_parts_info::comment, parser_context::custom_print, parser_node::info, pt_parts_info::name, NULL, pt_statement_info::parts, pt_append_nulstring(), pt_append_varchar(), PT_PARTITION_LIST, pt_print_bytes(), pt_print_bytes_l(), PT_SUPPRESS_BIGINT_CAST, pt_parts_info::type, and pt_parts_info::values.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_pointer (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 16197 of file parse_tree_cl.c.
References parser_node::info, pt_pointer_info::node, NULL, pt_statement_info::pointer, and pt_print_bytes_alias().
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_prepare_to_commit (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 13125 of file parse_tree_cl.c.
References parser_node::info, NULL, pt_statement_info::prepare_to_commit, pt_append_nulstring(), PT_MEMB_BUF_SIZE, and pt_attach_info::trans_id.
Referenced by pt_init_print_f().
char* pt_print_query_spec_no_list (PARSER_CONTEXT * parser, const PT_NODE * node)
Definition at line 2810 of file parse_tree_cl.c.
References parser_context::custom_print, parser_print_tree_with_quotes(), PT_CHARSET_COLLATE_FULL, PT_SUPPRESS_INTO, and PT_SUPPRESS_SELECT_LIST.
Referenced by emit_query_specs(), and emit_query_specs_has_using_index().
static PARSER_VARCHAR * pt_print_query_trace (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 17943 of file parse_tree_cl.c.
References pt_trace_info::format, parser_node::info, NULL, pt_trace_info::on_off, pt_append_nulstring(), pt_show_misc_type(), PT_TRACE_ON, and pt_statement_info::trace.
Referenced by pt_init_print_f().
static void pt_print_range_op (PARSER_CONTEXT * parser, PT_STRING_BLOCK * sb, PT_NODE * t, PARSER_VARCHAR * lhs) static
Definition at line 9432 of file parse_tree_cl.c.
References pt_expr_info::arg1, pt_expr_info::arg2, assert, parser_varchar::bytes, pt_statement_info::expr, parser_node::info, NULL, pt_expr_info::op, PT_BETWEEN_EQ_NA, PT_BETWEEN_GE_INF, PT_BETWEEN_GE_LE, PT_BETWEEN_GE_LT, PT_BETWEEN_GT_INF, PT_BETWEEN_GT_LE, PT_BETWEEN_GT_LT, PT_BETWEEN_INF_LE, PT_BETWEEN_INF_LT, PT_EQ, PT_GE, PT_GT, PT_LE, PT_LT, pt_print_bytes(), pt_show_binopcode(), and strcat_with_realloc().
Referenced by pt_print_expr().
static PARSER_VARCHAR * pt_print_remove_trigger (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 13156 of file parse_tree_cl.c.
References parser_node::info, NULL, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes_l(), pt_statement_info::remove_trigger, and pt_remove_trigger_info::trigger_spec_list.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_rename (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 13192 of file parse_tree_cl.c.
References pt_rename_info::entity_type, parser_node::info, pt_rename_info::new_name, parser_node::next, NULL, pt_rename_info::old_name, p, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes(), pt_show_misc_type(), and pt_statement_info::rename.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_rename_trigger (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 13243 of file parse_tree_cl.c.
References parser_node::info, pt_rename_trigger_info::new_name, pt_rename_trigger_info::old_name, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes(), and pt_statement_info::rename_trigger.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_resolution (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 13294 of file parse_tree_cl.c.
References pt_resolution_info::as_attr_mthd_name, pt_resolution_info::attr_mthd_name, pt_resolution_info::attr_type, parser_node::info, pt_resolution_info::of_sup_class_name, pt_append_nulstring(), pt_append_varchar(), PT_META_ATTR, pt_print_bytes(), and pt_statement_info::resolution.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_revoke (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 13343 of file parse_tree_cl.c.
References pt_revoke_info::auth_cmd_list, parser_context::custom_print, parser_node::info, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes_l(), PT_SUPPRESS_RESOLVED, pt_statement_info::revoke, pt_revoke_info::spec_list, and pt_revoke_info::user_list.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_rollback_work (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 13387 of file parse_tree_cl.c.
References parser_node::info, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes(), pt_statement_info::rollback_work, and pt_rollback_work_info::save_name.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_savepoint (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 13425 of file parse_tree_cl.c.
References parser_node::info, NULL, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes(), pt_savepoint_info::save_name, and pt_statement_info::savepoint.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_scope (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 13460 of file parse_tree_cl.c.
References pt_scope_info::from, parser_node::info, NULL, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes(), pt_statement_info::scope, and pt_scope_info::stmt.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_select (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 13538 of file parse_tree_cl.c.
References pt_select_info::after_cb_filter, parser_node::alias_print, pt_query_info::all_distinct, assert, pt_select_info::check_cycles, pt_select_info::check_where, pt_select_info::connect_by, CONNECT_BY_CYCLES_NONE, CONNECT_BY_CYCLES_NONE_IGNORE, parser_context::custom_print, pt_spec_info::derived_table, pt_spec_info::derived_table_type, parser_node::etc, pt_statement_info::expr, pt_spec_info::flag, pt_query_info::flag, parser_node::flag, pt_select_info::for_update, pt_select_info::from, pt_select_info::group_by, pt_select_info::having, pt_select_info::hint, pt_query_info::hint, pt_select_info::index_ls, pt_select_info::index_ss, parser_node::info, pt_query_info::into_list, pt_query_info::is_subquery, pt_query_info::limit, pt_node_list_info::list, pt_select_info::list, pt_statement_info::name, parser_node::next, pt_statement_info::node_list, parser_node::node_type, NULL, pt_expr_info::op, OPTIMIZATION_ENABLED, pt_query_info::order_by, pt_query_info::order_siblings, pt_query_info::orderby_for, pt_select_info::ordered, pt_name_info::original, parser_append_node(), PT_ALL, pt_append_nulstring(), pt_append_varchar(), PT_DECR, PT_DISTINCT, PT_EXPR, PT_HINT_INDEX_LS, PT_HINT_INDEX_SS, PT_HINT_LK_TIMEOUT, PT_HINT_NO_COVERING_IDX, PT_HINT_NO_HASH_AGGREGATE, PT_HINT_NO_HASH_LIST_SCAN, PT_HINT_NO_IDX_DESC, PT_HINT_NO_INDEX_LS, PT_HINT_NO_INDEX_SS, PT_HINT_NO_MULTI_RANGE_OPT, PT_HINT_NO_SORT_LIMIT, PT_HINT_NONE, PT_HINT_ORDERED, PT_HINT_QUERY_CACHE, PT_HINT_REEXECUTE, PT_HINT_SELECT_BTREE_NODE_INFO, PT_HINT_SELECT_KEY_INFO, PT_HINT_SELECT_PAGE_INFO, PT_HINT_SELECT_RECORD_INFO, PT_HINT_USE_HASH, PT_HINT_USE_IDX, PT_HINT_USE_IDX_DESC, PT_HINT_USE_MERGE, PT_HINT_USE_NL, PT_IDX_HINT_CLASS_NONE, PT_IS_SHOWSTMT, PT_IS_SUBQUERY, PT_IS_UNION_QUERY, PT_IS_UNION_SUBQUERY, PT_NODE_LIST, PT_PRINT_ALIAS, pt_print_and_list(), pt_print_bytes(), pt_print_bytes_l(), pt_print_bytes_spec_list(), PT_SELECT_FULL_INFO_COLS_SCHEMA, PT_SELECT_INFO_COLS_SCHEMA, PT_SELECT_INFO_FOR_UPDATE, PT_SELECT_INFO_IDX_SCHEMA, PT_SELECT_INFO_IS_FLAGED, PT_SELECT_INFO_IS_UPD_DEL_QUERY, PT_SHOWSTMT, PT_SPEC_FLAG_FOR_UPDATE_CLAUSE, PT_SPEC_IS_DERIVED, PT_SUPPRESS_INTO, PT_SUPPRESS_SELECT_LIST, pt_query_info::q, pt_query_info::qcache_hint, qo_get_optimization_param(), QO_PARAM_LEVEL, pt_statement_info::query, pt_spec_info::range_var, pt_name_info::resolved, pt_query_info::rewrite_limit, pt_query_info::select, pt_select_info::single_table_opt, pt_statement_info::spec, pt_select_info::start_with, pt_select_info::use_idx, pt_select_info::use_merge, pt_select_info::use_nl, pt_select_info::using_index, pt_select_info::waitsecs_hint, pt_select_info::where, pt_query_info::with, pt_select_info::with_increment, and parser_node::with_rollup.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_session_variables (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 15340 of file parse_tree_cl.c.
References parser_node::next, NULL, pt_append_bytes(), pt_append_nulstring(), pt_append_varchar(), and pt_print_bytes().
Referenced by pt_print_drop_session_variables().
static PARSER_VARCHAR * pt_print_set_names (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 14254 of file parse_tree_cl.c.
References assert, pt_set_names_info::charset_node, pt_set_names_info::collation_node, parser_node::info, NULL, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes(), and pt_statement_info::set_names.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_set_opt_lvl (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 14331 of file parse_tree_cl.c.
References parser_node::info, parser_node::next, NULL, pt_set_opt_lvl_info::option, pt_append_nulstring(), pt_append_varchar(), PT_OPT_COST, pt_print_bytes(), pt_show_misc_type(), pt_statement_info::set_opt_lvl, and pt_set_opt_lvl_info::val.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_set_session_variables (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 15309 of file parse_tree_cl.c.
References pt_set_session_variable_info::assignments, parser_node::info, NULL, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes_l(), and pt_statement_info::set_variables.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_set_sys_params (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 14379 of file parse_tree_cl.c.
References parser_node::info, NULL, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes(), pt_statement_info::set_sys_params, and pt_set_sys_params_info::val.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_set_timezone (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 14283 of file parse_tree_cl.c.
References assert, parser_node::info, NULL, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes(), pt_statement_info::set_timezone, and pt_set_timezone_info::timezone_node.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_set_trigger (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 14417 of file parse_tree_cl.c.
References pt_value_info::data_value, pt_data_value::i, parser_node::info, NULL, pt_set_trigger_info::option, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes(), pt_show_misc_type(), PT_TRIGGER_TRACE, pt_statement_info::set_trigger, pt_set_trigger_info::val, and pt_statement_info::value.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_set_xaction (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 14516 of file parse_tree_cl.c.
References parser_node::info, NULL, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes_l(), pt_statement_info::set_xaction, and pt_set_xaction_info::xaction_modes.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_showstmt (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 14480 of file parse_tree_cl.c.
References parser_node::info, NULL, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes_l(), pt_showstmt_info::show_args, pt_showstmt_info::show_type, pt_statement_info::showstmt, and showstmt_get_metadata().
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_sort_spec (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 14563 of file parse_tree_cl.c.
References pt_sort_spec_info::asc_or_desc, pt_sort_spec_info::expr, parser_node::info, pt_sort_spec_info::nulls_first_or_last, pt_append_nulstring(), pt_append_varchar(), PT_DESC, PT_NULLS_FIRST, PT_NULLS_LAST, pt_print_bytes(), and pt_statement_info::sort_spec.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_sp_parameter (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 7657 of file parse_tree_cl.c.
References pt_stored_proc_param_info::comment, parser_node::info, pt_stored_proc_param_info::mode, pt_stored_proc_param_info::name, NULL, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes(), pt_show_misc_type(), pt_show_type_enum(), pt_statement_info::sp_param, and parser_node::type_enum.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_spec (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 8984 of file parse_tree_cl.c.
References pt_spec_info::as_attr_list, parser_context::custom_print, pt_spec_info::derived_table, pt_spec_info::derived_table_type, pt_spec_info::entity_name, pt_spec_info::except_list, parser_node::flag, pt_spec_info::flat_entity_list, pt_insert_info::hint, i, parser_node::info, pt_statement_info::insert, pt_spec_info::join_type, pt_spec_info::meta_class, pt_statement_info::name, pt_spec_info::natural, parser_node::next, NULL, pt_spec_info::on_cond, pt_spec_info::only_all, pt_name_info::original, pt_spec_info::partition, parser_node::partition_pruned, PT_ALL, pt_append_nulstring(), pt_append_varchar(), PT_DERIVED_JSON_TABLE, PT_HINT_USE_SBR, PT_IS_SET_EXPR, PT_IS_SUBQUERY, PT_JOIN_CROSS, PT_JOIN_FULL_OUTER, PT_JOIN_INNER, PT_JOIN_LEFT_OUTER, PT_JOIN_NONE, PT_JOIN_RIGHT_OUTER, PT_META_CLASS, PT_PRINT_ALIAS, pt_print_and_list(), pt_print_bytes(), pt_print_bytes_l(), PT_PRINT_ORIGINAL_BEFORE_CONST_FOLDING, PT_SPEC_IS_CTE, PT_SPEC_IS_DERIVED, PT_SPEC_IS_ENTITY, PT_SUPPRESS_META_ATTR_CLASS, PT_SUPPRESS_RESOLVED, pt_spec_info::range_var, pt_statement_info::spec, parser_context::statement_number, parser_context::statements, and pt_spec_info::using_cond.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_table_option (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 7533 of file parse_tree_cl.c.
References assert, pt_value_info::data_value, pt_data_value::i, parser_node::info, parser_node::node_type, NULL, pt_table_option_info::option, pt_append_bytes(), pt_append_nulstring(), pt_append_varchar(), PT_IS_SIMPLE_CHAR_STRING_TYPE, pt_print_bytes_l(), PT_TABLE_OPTION_AUTO_INCREMENT, PT_TABLE_OPTION_CHARSET, PT_TABLE_OPTION_COLLATION, PT_TABLE_OPTION_COMMENT, PT_TABLE_OPTION_DONT_REUSE_OID, PT_TABLE_OPTION_ENCRYPT, PT_TABLE_OPTION_REUSE_OID, PT_TYPE_INTEGER, PT_VALUE, pt_data_value::str, strlen, pt_statement_info::table_option, tde_get_algorithm_name(), parser_node::type_enum, pt_table_option_info::val, and pt_statement_info::value.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_timeout (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 14609 of file parse_tree_cl.c.
References pt_value_info::data_value, pt_data_value::i, parser_node::info, NULL, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes(), pt_statement_info::timeout, pt_timeout_info::val, and pt_statement_info::value.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_trigger_action (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 14660 of file parse_tree_cl.c.
References pt_trigger_action_info::action_type, pt_trigger_action_info::expression, parser_node::info, NULL, pt_append_nulstring(), pt_append_varchar(), PT_EXPRESSION, PT_INVALIDATE_XACTION, PT_PRINT, pt_print_bytes(), PT_REJECT, pt_show_misc_type(), pt_trigger_action_info::string, and pt_statement_info::trigger_action.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_trigger_spec_list (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 14710 of file parse_tree_cl.c.
References parser_node::info, NULL, pt_append_varchar(), pt_print_bytes_l(), pt_trigger_spec_list_info::trigger_name_list, and pt_statement_info::trigger_spec_list.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_truncate (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 7483 of file parse_tree_cl.c.
References parser_context::custom_print, parser_node::info, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes_l(), PT_SUPPRESS_RESOLVED, pt_truncate_info::spec, and pt_statement_info::truncate.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_tuple_value (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 16445 of file parse_tree_cl.c.
References assert, parser_node::info, pt_tuple_value_info::name, NULL, pt_append_bytes(), pt_print_name(), and pt_statement_info::tuple_value.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_union_stmt (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 14768 of file parse_tree_cl.c.
References pt_query_info::all_distinct, pt_union_info::arg1, pt_union_info::arg2, pt_query_info::flag, parser_node::info, pt_query_info::limit, NULL, pt_query_info::order_by, pt_query_info::orderby_for, PT_ALL, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes(), pt_print_bytes_l(), pt_query_info::q, pt_statement_info::query, pt_query_info::rewrite_limit, pt_query_info::union_, and pt_query_info::with.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_update (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 14864 of file parse_tree_cl.c.
References pt_update_info::assignment, pt_update_info::check_where, parser_context::custom_print, parser_node::etc, pt_update_info::hint, parser_node::info, IS_UPDATE_OBJ, pt_update_info::limit, pt_statement_info::name, parser_node::next, NULL, pt_update_info::object_parameter, pt_update_info::order_by, pt_update_info::orderby_for, pt_update_info::ordered_hint, pt_name_info::original, pt_append_nulstring(), pt_append_varchar(), PT_HINT_LK_TIMEOUT, PT_HINT_NO_COVERING_IDX, PT_HINT_NO_IDX_DESC, PT_HINT_NO_LOGGING, PT_HINT_NO_MULTI_RANGE_OPT, PT_HINT_NO_SORT_LIMIT, PT_HINT_NONE, PT_HINT_ORDERED, PT_HINT_USE_IDX, PT_HINT_USE_IDX_DESC, PT_HINT_USE_MERGE, PT_HINT_USE_NL, PT_HINT_USE_SBR, PT_IDX_HINT_CLASS_NONE, pt_print_and_list(), pt_print_bytes(), pt_print_bytes_l(), pt_print_bytes_spec_list(), PT_SUPPRESS_INTO, pt_name_info::resolved, pt_update_info::rewrite_limit, pt_update_info::search_cond, pt_update_info::spec, pt_statement_info::update, pt_update_info::use_idx_hint, pt_update_info::use_merge_hint, pt_update_info::use_nl_hint, pt_update_info::using_index, pt_update_info::waitsecs_hint, and pt_update_info::with.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_update_stats (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 15099 of file parse_tree_cl.c.
References pt_update_stats_info::all_classes, assert, pt_update_stats_info::class_list, parser_node::info, pt_append_nulstring(), pt_append_varchar(), pt_print_bytes_l(), pt_statement_info::update_stats, and pt_update_stats_info::with_fullscan.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_vacuum (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 17897 of file parse_tree_cl.c.
References assert, NULL, pt_append_nulstring(), and PT_IS_VACUUM_NODE.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_value (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 15431 of file parse_tree_cl.c.
References parser_node::alias_print, pt_monetary_value::amount, ARG_FILE_LINE, assert, pt_data_value::bigint, parser_varchar::bytes, pt_data_type_info::collation_id, parser_context::custom_print, pt_data_value::d, pt_statement_info::data_type, parser_node::data_type, pt_value_info::data_value, DB_CURRENCY_NULL, DB_DOUBLE_DECIMAL_PRECISION, DB_FLOAT_DECIMAL_PRECISION, DB_IS_NULL, pt_value_info::db_value_is_initialized, db_value_printer::DECIMAL_FORMAT, parser_context::dont_prt_long_string, DONT_PRT_LONG_STRING_LENGTH, pt_data_value::enumeration, ER_ERROR_SEVERITY, ER_GENERIC_ERROR, er_set(), pt_data_value::f, parser_context::flag, pt_value_info::has_cs_introducer, pt_data_value::i, parser_node::info, INTL_CODESET_NONE, intl_get_money_esc_ISO_symbol(), pt_value_info::is_collate_allowed, lang_charset_introducer(), lang_get_collation_name(), LANG_SYS_CODESET, LANG_SYS_COLLATION, parser_varchar::length, parser_context::long_string_skipped, pt_data_value::money, NULL, pt_data_type_info::precision, pt_value_info::print_charset, pt_value_info::print_collation, parser_context::print_type_ambiguity, pt_append_nulstring(), pt_append_quoted_string(), pt_append_string_prefix(), pt_append_varchar(), PT_CHARSET_COLLATE_FULL, PT_CHARSET_COLLATE_USER_ONLY, pt_currency_to_db(), PT_GET_COLLATION_MODIFIER, PT_HAS_COLLATION, PT_MEMB_BUF_SIZE, PT_MEMB_PRINTABLE_BUF_SIZE, PT_PRINT_ALIAS, pt_print_bytes_l(), pt_show_type_enum(), PT_SUPPRESS_BIGINT_CAST, PT_SUPPRESS_CHARSET_PRINT, PT_TYPE_BIGINT, PT_TYPE_BIT, PT_TYPE_BLOB, PT_TYPE_CHAR, PT_TYPE_CLOB, PT_TYPE_DATE, PT_TYPE_DATETIME, PT_TYPE_DATETIMELTZ, PT_TYPE_DATETIMETZ, PT_TYPE_DOUBLE, PT_TYPE_ENUMERATION, PT_TYPE_FLOAT, PT_TYPE_INTEGER, PT_TYPE_JSON, PT_TYPE_LOGICAL, PT_TYPE_MONETARY, PT_TYPE_MULTISET, PT_TYPE_NA, PT_TYPE_NCHAR, PT_TYPE_NULL, PT_TYPE_NUMERIC, PT_TYPE_OBJECT, PT_TYPE_SEQUENCE, PT_TYPE_SET, PT_TYPE_SMALLINT, PT_TYPE_STAR, PT_TYPE_TIME, PT_TYPE_TIMESTAMP, PT_TYPE_TIMESTAMPLTZ, PT_TYPE_TIMESTAMPTZ, PT_TYPE_VARBIT, PT_TYPE_VARCHAR, PT_TYPE_VARNCHAR, pt_value_to_db(), pt_data_value::set, parser_node::spec_ident, pt_data_value::str, pt_enum_element_value::str_val, strlen, pt_value_info::text, TP_FLOATING_PRECISION_VALUE, pt_monetary_value::type, parser_node::type_enum, pt_data_type_info::units, and pt_statement_info::value.
Referenced by pt_init_print_f().
static PARSER_VARCHAR * pt_print_with_clause (PARSER_CONTEXT * parser, PT_NODE * p) static
Definition at line 16566 of file parse_tree_cl.c.
References pt_with_clause_info::cte_definition_list, parser_node::info, parser_node::next, NULL, pt_append_nulstring(), pt_append_varchar(), pt_print_cte(), pt_with_clause_info::recursive, and pt_statement_info::with_clause.
Referenced by pt_init_print_f().
int pt_push (PARSER_CONTEXT * parser, PT_NODE * node)
Definition at line 1591 of file parse_tree_cl.c.
References DELTA, INITIAL_EXTENT, parser_context::node_stack, parser_alloc(), parser_context::stack_size, and parser_context::stack_top.
Referenced by pt_rewrite_set_eq_set().
void pt_record_error (PARSER_CONTEXT * parser, int stmt_no, int line_no, int col_no, const char * msg, const char * context)
Definition at line 1935 of file parse_tree_cl.c.
References parser_node::column_number, PT_ZZ_ERROR_MSG_INFO::error_message, pt_statement_info::error_msg, parser_context::error_msgs, parser_node::info, parser_node::line_number, MAX_PRINT_ERROR_CONTEXT_LENGTH, MSGCAT_CATALOG_CUBRID, msgcat_message(), MSGCAT_SET_PARSER_SYNTAX, MSGCAT_SYNTAX_BEFORE_CONTEXT, MSGCAT_SYNTAX_BEFORE_END_OF_STMT, NULL, parser_allocate_string_buffer(), parser_append_node(), parser_new_node(), pt_append_string(), pt_has_error, PT_INTERNAL_ERROR, PT_ZZ_ERROR_MSG, PT_ZZ_ERROR_MSG_INFO::statement_number, and strlen.
Referenced by do_alter_change_col_comment(), do_alter_change_default_cs_coll(), do_alter_change_tbl_comment(), do_alter_clause_change_attribute(), do_alter_one_clause_with_template(), do_execute_merge(), do_execute_update(), do_merge(), do_prepare_delete(), do_prepare_merge(), do_prepare_update(), do_update(), mq_copy_view_error_msgs(), pt_frob_error(), and validate_attribute_domain().
void pt_restore_assignment_links (PT_NODE * assigns, PT_NODE ** links, int count)
Definition at line 17095 of file parse_tree_cl.c.
References pt_expr_info::arg1, pt_expr_info::arg2, db_private_free, pt_statement_info::expr, parser_node::info, parser_node::next, parser_node::node_type, NULL, and PT_NAME.
Referenced by do_merge(), do_prepare_merge(), do_prepare_update(), pt_get_assignment_lists(), pt_to_merge_update_xasl(), pt_to_update_xasl(), and update_real_class().
PT_NODE* pt_rewrite_set_eq_set (PARSER_CONTEXT * parser, PT_NODE * exp)
Definition at line 4616 of file parse_tree_cl.c.
References pt_expr_info::arg1, pt_expr_info::arg2, pt_expr_info::arg3, pt_value_info::data_value, pt_statement_info::expr, parser_node::info, parser_node::next, parser_node::node_type, NULL, pt_expr_info::op, p, pt_expr_info::paren_type, parser_copy_tree(), parser_free_tree(), parser_new_node(), PT_AND, PT_EQ, PT_ERRORf, PT_EXPR, PT_INTERNAL_ERROR, pt_is_set_type, pt_pop(), pt_push(), pt_rewrite_set_eq_set(), pt_show_binopcode(), PT_TYPE_LOGICAL, PT_VALUE, pt_data_value::set, parser_node::type_enum, and pt_statement_info::value.
Referenced by pt_rewrite_set_eq_set().
void pt_select_list_to_one_col (PARSER_CONTEXT * parser, PT_NODE * node, bool do_one)
Definition at line 4379 of file parse_tree_cl.c.
References pt_union_info::arg1, pt_union_info::arg2, pt_function_info::arg_list, pt_spec_info::as_attr_list, pt_select_info::connect_by, pt_value_info::data_value, pt_spec_info::derived_table, pt_spec_info::derived_table_type, EXCLUDE_HIDDEN_COLUMNS, pt_statement_info::expr, pt_query_info::flag, pt_select_info::from, pt_statement_info::function, i, parser_node::info, pt_select_info::list, parser_node::next, parser_node::node_type, NULL, pt_expr_info::op, pt_query_info::order_by, pt_query_info::orderby_for, parser_append_node(), parser_copy_tree(), parser_copy_tree_list(), parser_free_tree(), parser_new_node(), parser_reinit_node(), pt_append_string(), PT_DIFFERENCE, PT_EXPR, PT_FUNCTION, PT_INTERNAL_ERROR, PT_INTERSECTION, pt_is_set_type, PT_IS_SUBQUERY, pt_length_of_select_list(), pt_name(), PT_NAME_GENERATED_DERIVED_SPEC, PT_NAME_INFO_SET_FLAG, PT_ORDERBY_NUM, PT_SELECT, pt_select_list_to_one_col(), PT_SPEC, PT_TYPE_SEQUENCE, PT_UNION, PT_VALUE, pt_query_info::q, pt_statement_info::query, pt_spec_info::range_var, pt_query_info::select, pt_union_info::select_list, pt_data_value::set, pt_query_info::single_tuple, pt_statement_info::spec, parser_node::type_enum, pt_query_info::union_, and pt_statement_info::value.
Referenced by pt_select_list_to_one_col(), and qo_rewrite_subqueries().
char* pt_short_print (PARSER_CONTEXT * parser, const PT_NODE * node)
Definition at line 2829 of file parse_tree_cl.c.
References parser_context::max_print_len, NULL, parser_print_tree(), and strlen.
Referenced by check_default_on_update_clause(), do_alter_one_clause_with_template(), do_evaluate_insert_values(), do_insert_template(), do_replace_names_for_insert_values_pre(), get_att_default_from_def(), mq_class_lambda(), mq_invert_insert_select(), pt_apply_union_select_list_collation(), pt_bind_name_or_path_in_scope(), pt_bind_names(), pt_bind_names_post(), pt_bind_spec_attrs(), pt_check_analytic_function(), pt_check_cast_op(), pt_check_class_eq(), pt_check_create_entity(), pt_check_create_index(), pt_check_create_view(), pt_check_cume_dist_percent_rank_order_by(), pt_check_filter_index_expr(), pt_check_group_concat_order_by(), pt_check_order_by(), pt_check_path_eq(), pt_check_single_valued_node(), pt_check_vclass_query_spec(), pt_check_vclass_union_spec(), pt_check_with_info(), pt_coerce_value_internal(), pt_db_value_initialize(), pt_eval_function_type_new(), pt_eval_function_type_old(), pt_eval_path_expr(), pt_evaluate_db_value_expr(), pt_evaluate_tree_internal(), pt_get_common_type_for_union(), pt_get_compatible_info(), pt_get_resolution(), pt_get_values_query_compatible_info(), pt_insert_entity(), pt_node_to_enumeration_expr(), pt_resolve_correlation(), pt_resolve_group_having_alias_pt_name(), pt_resolve_using_index(), pt_semantic_check_local(), pt_set_attr_list_types(), pt_to_sort_list(), pt_undef_names_pre(), qo_optimize_queries_post(), qo_reduce_equality_terms(), and qo_reduce_order_by().
char* pt_short_print_l (PARSER_CONTEXT * parser, const PT_NODE * node)
Definition at line 2859 of file parse_tree_cl.c.
References parser_context::max_print_len, NULL, parser_print_tree_list(), and strlen.
Referenced by pt_check_create_entity(), pt_flat_spec_pre(), pt_get_resolution(), and pt_set_attr_list_types().
const char* pt_show_binopcode (PT_OP_TYPE n)
Definition at line 3347 of file parse_tree_cl.c.
References assert, PT_ABS, PT_ACOS, PT_ADD_MONTHS, PT_ADDDATE, PT_ADDTIME, PT_AES_DECRYPT, PT_AES_ENCRYPT, PT_AND, PT_ASCII, PT_ASIN, PT_ASSIGN, PT_ATAN, PT_ATAN2, PT_BETWEEN, PT_BETWEEN_AND, PT_BETWEEN_EQ_NA, PT_BETWEEN_GE_INF, PT_BETWEEN_GE_LE, PT_BETWEEN_GE_LT, PT_BETWEEN_GT_INF, PT_BETWEEN_GT_LE, PT_BETWEEN_GT_LT, PT_BETWEEN_INF_LE, PT_BETWEEN_INF_LT, PT_BIN, PT_BIT_AND, PT_BIT_COUNT, PT_BIT_LENGTH, PT_BIT_NOT, PT_BIT_OR, PT_BIT_TO_BLOB, PT_BIT_XOR, PT_BITSHIFT_LEFT, PT_BITSHIFT_RIGHT, PT_BLOB_FROM_FILE, PT_BLOB_LENGTH, PT_BLOB_TO_BIT, PT_CASE, PT_CAST, PT_CEIL, PT_CHAR_LENGTH, PT_CHAR_TO_BLOB, PT_CHAR_TO_CLOB, PT_CHARSET, PT_CHR, PT_CLOB_FROM_FILE, PT_CLOB_LENGTH, PT_CLOB_TO_CHAR, PT_COALESCE, PT_COERCIBILITY, PT_COLLATION, PT_CONCAT, PT_CONCAT_WS, PT_CONNECT_BY_ISCYCLE, PT_CONNECT_BY_ISLEAF, PT_CONNECT_BY_ROOT, PT_CONV, PT_CONV_TZ, PT_COS, PT_COT, PT_CRC32, PT_CURRENT_DATE, PT_CURRENT_DATETIME, PT_CURRENT_TIME, PT_CURRENT_TIMESTAMP, PT_CURRENT_USER, PT_CURRENT_VALUE, PT_DATABASE, PT_DATE_ADD, PT_DATE_FORMAT, PT_DATE_SUB, PT_DATEDIFF, PT_DATEF, PT_DAYF, PT_DAYOFMONTH, PT_DAYOFWEEK, PT_DAYOFYEAR, PT_DBTIMEZONE, PT_DECODE, PT_DECR, PT_DEFAULTF, PT_DEFINE_VARIABLE, PT_DEGREES, PT_DISK_SIZE, PT_DIV, PT_DIVIDE, PT_DRAND, PT_DRANDOM, PT_EQ, PT_EQ_ALL, PT_EQ_SOME, PT_EVALUATE_VARIABLE, PT_EXEC_STATS, PT_EXISTS, PT_EXP, PT_EXTRACT, PT_FIELD, PT_FINDINSET, PT_FLOOR, PT_FORMAT, PT_FROM_BASE64, PT_FROM_TZ, PT_FROM_UNIXTIME, PT_FROMDAYS, PT_FUNCTION_HOLDER, PT_GE, PT_GE_ALL, PT_GE_SOME, PT_GREATEST, PT_GT, PT_GT_ALL, PT_GT_SOME, PT_HEX, PT_HOURF, PT_IF, PT_IFNULL, PT_INCR, PT_INDEX_CARDINALITY, PT_INDEX_PREFIX, PT_INET_ATON, PT_INET_NTOA, PT_INST_NUM, PT_INSTR, PT_IS, PT_IS_IN, PT_IS_NOT, PT_IS_NOT_IN, PT_IS_NOT_NULL, PT_IS_NULL, PT_ISNULL, PT_LAST_DAY, PT_LAST_INSERT_ID, PT_LE, PT_LE_ALL, PT_LE_SOME, PT_LEAST, PT_LEFT, PT_LEVEL, PT_LIKE, PT_LIKE_ESCAPE, PT_LIKE_LOWER_BOUND, PT_LIKE_UPPER_BOUND, PT_LIST_DBS, PT_LN, PT_LOCAL_TRANSACTION_ID, PT_LOCATE, PT_LOG, PT_LOG10, PT_LOG2, PT_LOWER, PT_LPAD, PT_LT, PT_LT_ALL, PT_LT_SOME, PT_LTRIM, PT_MAKEDATE, PT_MAKETIME, PT_MD5, PT_MID, PT_MINUS, PT_MINUTEF, PT_MOD, PT_MODULUS, PT_MONTHF, PT_MONTHS_BETWEEN, PT_NE, PT_NE_ALL, PT_NE_SOME, PT_NEW_TIME, PT_NEXT_VALUE, PT_NOT, PT_NOT_BETWEEN, PT_NOT_LIKE, PT_NOT_RLIKE, PT_NOT_RLIKE_BINARY, PT_NULLIF, PT_NULLSAFE_EQ, PT_NVL, PT_NVL2, PT_OCTET_LENGTH, PT_OID_OF_DUPLICATE_KEY, PT_OR, PT_ORDERBY_NUM, PT_PI, PT_PLUS, PT_POSITION, PT_POWER, PT_PRIOR, PT_QPRIOR, PT_QUARTERF, PT_RADIANS, PT_RAND, PT_RANDOM, PT_RANGE, PT_REPEAT, PT_REPLACE, PT_REVERSE, PT_RIGHT, PT_RLIKE, PT_RLIKE_BINARY, PT_ROUND, PT_ROW_COUNT, PT_ROWNUM, PT_RPAD, PT_RTRIM, PT_SCHEMA, PT_SCHEMA_DEF, PT_SECONDF, PT_SECTOTIME, PT_SESSIONTIMEZONE, PT_SETEQ, PT_SETNEQ, PT_SHA_ONE, PT_SHA_TWO, PT_SIGN, PT_SIN, PT_SLEEP, PT_SPACE, PT_SQRT, PT_STR_TO_DATE, PT_STRCAT, PT_STRCMP, PT_SUBDATE, PT_SUBSET, PT_SUBSETEQ, PT_SUBSTRING, PT_SUBSTRING_INDEX, PT_SUPERSET, PT_SUPERSETEQ, PT_SYS_CONNECT_BY_PATH, PT_SYS_DATE, PT_SYS_DATETIME, PT_SYS_GUID, PT_SYS_TIME, PT_SYS_TIMESTAMP, PT_TAN, PT_TIME_FORMAT, PT_TIMEDIFF, PT_TIMEF, PT_TIMES, PT_TIMESTAMP, PT_TIMETOSEC, PT_TO_BASE64, PT_TO_CHAR, PT_TO_DATE, PT_TO_DATETIME, PT_TO_DATETIME_TZ, PT_TO_ENUMERATION_VALUE, PT_TO_NUMBER, PT_TO_TIME, PT_TO_TIMESTAMP, PT_TO_TIMESTAMP_TZ, PT_TODAYS, PT_TRACE_STATS, PT_TRANSLATE, PT_TRIM, PT_TRUNC, PT_TYPEOF, PT_TZ_OFFSET, PT_UNARY_MINUS, PT_UNIX_TIMESTAMP, PT_UPPER, PT_USER, PT_UTC_DATE, PT_UTC_TIME, PT_UTC_TIMESTAMP, PT_VERSION, PT_WEEKDAY, PT_WEEKF, PT_WIDTH_BUCKET, PT_XOR, and PT_YEARF.
Referenced by pt_check_data_default(), pt_check_expr_collation(), pt_check_filter_index_expr_pre(), pt_check_recursive_expr_collation(), pt_coerce_expression_argument(), pt_eval_expr_type(), pt_expr_disallow_op_pre(), pt_is_function_index_expr(), pt_print_expr(), pt_print_range_op(), pt_rewrite_set_eq_set(), and pt_to_regu_variable().
static const char * pt_show_event_type (PT_EVENT_TYPE p) static
Definition at line 5389 of file parse_tree_cl.c.
References PT_EV_COMMIT, PT_EV_DELETE, PT_EV_INSERT, PT_EV_ROLLBACK, PT_EV_STMT_DELETE, PT_EV_STMT_INSERT, PT_EV_STMT_UPDATE, and PT_EV_UPDATE.
Referenced by pt_print_event_spec().
const char* pt_show_misc_type (PT_MISC_TYPE p)
Definition at line 3190 of file parse_tree_cl.c.
References PT_ACTIVE, PT_AFTER, PT_ALL, PT_ASC, PT_ATTRIBUTE, PT_BEFORE, PT_BIT_STRING, PT_CHAR_STRING, PT_CLASS, PT_CONSTRAINT_NAME, PT_DAY, PT_DEFAULT, PT_DEFERRED, PT_DESC, PT_DISTINCT, PT_FILE_RENAME, PT_FUNCTION_RENAME, PT_GRANT_OPTION, PT_HEX_STRING, PT_HOUR, PT_INACTIVE, PT_INDEX_NAME, PT_INPUT, PT_INPUTOUTPUT, PT_INVALIDATE_XACTION, PT_IS_SUBINSERT, PT_IS_SUBQUERY, PT_IS_VALUE, PT_ISOLATION_LEVEL, PT_LOCK_TIMEOUT, PT_MATCH_FULL, PT_MATCH_PARTIAL, PT_MATCH_REGULAR, PT_META_ATTR, PT_META_CLASS, PT_METHOD, PT_MILLISECOND, PT_MINUTE, PT_MISC_DUMMY, PT_MONTH, PT_NCHAR_STRING, PT_NO_GRANT_OPTION, PT_NO_ISOLATION_LEVEL, PT_NOPUT, PT_NORMAL, PT_ONLY, PT_OPT_COST, PT_OPT_LVL, PT_OUTPUT, PT_PRINT, PT_READ_COMMITTED, PT_REJECT, PT_REPEATABLE_READ, PT_RULE_CASCADE, PT_RULE_NO_ACTION, PT_RULE_RESTRICT, PT_RULE_SET_NULL, PT_SEARCHED_CASE, PT_SECOND, PT_SERIALIZABLE, PT_SHARED, PT_SIMPLE_CASE, PT_SP_FUNCTION, PT_SP_PROCEDURE, PT_TRACE_FORMAT_JSON, PT_TRACE_FORMAT_TEXT, PT_TRACE_OFF, PT_TRACE_ON, PT_TRIGGER_DEPTH, PT_TRIGGER_TRACE, PT_VCLASS, and PT_YEAR.
Referenced by map_iso_levels(), pt_check_alter(), pt_check_create_entity(), pt_check_drop(), pt_check_truncate(), pt_eval_expr_type(), pt_evaluate_db_value_expr(), pt_help_show_create_table(), pt_print_alter(), pt_print_alter_one_clause(), pt_print_alter_trigger(), pt_print_col_def_constraint(), pt_print_constraint(), pt_print_create_entity(), pt_print_create_stored_procedure(), pt_print_create_trigger(), pt_print_drop_stored_procedure(), pt_print_get_opt_lvl(), pt_print_get_trigger(), pt_print_get_xaction(), pt_print_isolation_lvl(), pt_print_query_trace(), pt_print_rename(), pt_print_set_opt_lvl(), pt_print_set_trigger(), pt_print_sp_parameter(), and pt_print_trigger_action().
const char* pt_show_node_type (PT_NODE * node)
Definition at line 2888 of file parse_tree_cl.c.
References parser_node::node_type, PT_2PC_ATTACH, PT_ALTER, PT_ALTER_INDEX, PT_ALTER_TRIGGER, PT_ALTER_USER, PT_ATTR_DEF, PT_ATTR_ORDERING, PT_AUTH_CMD, PT_COMMIT_WORK, PT_CONSTRAINT, PT_CREATE_ENTITY, PT_CREATE_INDEX, PT_CREATE_TRIGGER, PT_CREATE_USER, PT_CTE, PT_DATA_DEFAULT, PT_DATA_TYPE, PT_DEALLOCATE_PREPARE, PT_DELETE, PT_DIFFERENCE, PT_DO, PT_DOT_, PT_DROP, PT_DROP_INDEX, PT_DROP_TRIGGER, PT_DROP_USER, PT_EVENT_OBJECT, PT_EVENT_SPEC, PT_EVENT_TARGET, PT_EXECUTE_PREPARE, PT_EXECUTE_TRIGGER, PT_EXPR, PT_FILE_PATH, PT_FUNCTION, PT_GET_OPT_LVL, PT_GET_STATS, PT_GET_XACTION, PT_GRANT, PT_HOST_VAR, PT_INSERT, PT_INTERSECTION, PT_ISOLATION_LVL, PT_MERGE, PT_METHOD_CALL, PT_METHOD_DEF, PT_NAME, PT_NAMED_ARG, PT_NODE_LIST, PT_PARTITION, PT_PARTS, PT_PREPARE_STATEMENT, PT_PREPARE_TO_COMMIT, PT_REMOVE_TRIGGER, PT_RENAME, PT_RESOLUTION, PT_REVOKE, PT_ROLLBACK_WORK, PT_SAVEPOINT, PT_SELECT, PT_SET_NAMES, PT_SET_OPT_LVL, PT_SET_SYS_PARAMS, PT_SET_TIMEZONE, PT_SET_XACTION, PT_SHOWSTMT, PT_SORT_SPEC, PT_SPEC, PT_TIMEOUT, PT_TRIGGER_ACTION, PT_TRIGGER_SPEC_LIST, PT_TRUNCATE, PT_UNION, PT_UPDATE, PT_UPDATE_STATS, PT_VACUUM, PT_VALUE, and PT_WITH_CLAUSE.
Referenced by do_process_prepare_statement().
const char* pt_show_partition_type (PT_PARTITION_TYPE t)
Definition at line 4124 of file parse_tree_cl.c.
References PT_PARTITION_HASH, PT_PARTITION_LIST, and PT_PARTITION_RANGE.
Referenced by pt_print_partition().
const char* pt_show_priv (PT_PRIV_TYPE t)
Definition at line 3908 of file parse_tree_cl.c.
References PT_ADD_PRIV, PT_ALL_PRIV, PT_ALTER_PRIV, PT_DELETE_PRIV, PT_DROP_PRIV, PT_EXECUTE_PRIV, PT_INDEX_PRIV, PT_INSERT_PRIV, PT_NO_PRIV, PT_REFERENCES_PRIV, PT_SELECT_PRIV, and PT_UPDATE_PRIV.
Referenced by pt_print_auth_cmd().
const char* pt_show_type_enum (PT_TYPE_ENUM t)
Definition at line 3948 of file parse_tree_cl.c.
References PT_ADD_ATTR_MTHD, PT_ADD_HASHPARTITION, PT_ADD_PARTITION, PT_ADD_QUERY, PT_ADD_SUPCLASS, PT_ALTER_DEFAULT, PT_ANALYZE_PARTITION, PT_APPLY_PARTITION, PT_COALESCE_PARTITION, PT_DROP_ATTR_MTHD, PT_DROP_CONSTRAINT, PT_DROP_FK_CLAUSE, PT_DROP_INDEX_CLAUSE, PT_DROP_PARTITION, PT_DROP_PRIMARY_CLAUSE, PT_DROP_QUERY, PT_DROP_RESOLUTION, PT_DROP_SUPCLASS, PT_MODIFY_ATTR_MTHD, PT_MODIFY_DEFAULT, PT_MODIFY_QUERY, PT_PROMOTE_PARTITION, PT_REMOVE_PARTITION, PT_RENAME_ATTR_MTHD, PT_RENAME_ENTITY, PT_RENAME_RESOLUTION, PT_REORG_PARTITION, PT_RESET_QUERY, PT_TYPE_BIGINT, PT_TYPE_BIT, PT_TYPE_BLOB, PT_TYPE_CHAR, PT_TYPE_CLOB, PT_TYPE_COMPOUND, PT_TYPE_DATE, PT_TYPE_DATETIME, PT_TYPE_DATETIMELTZ, PT_TYPE_DATETIMETZ, PT_TYPE_DOUBLE, PT_TYPE_ELO, PT_TYPE_ENUMERATION, PT_TYPE_FLOAT, PT_TYPE_INTEGER, PT_TYPE_JSON, PT_TYPE_LOGICAL, PT_TYPE_MAX, PT_TYPE_MAYBE, PT_TYPE_MONETARY, PT_TYPE_MULTISET, PT_TYPE_NA, PT_TYPE_NCHAR, PT_TYPE_NONE, PT_TYPE_NULL, PT_TYPE_NUMERIC, PT_TYPE_OBJECT, PT_TYPE_RESULTSET, PT_TYPE_SEQUENCE, PT_TYPE_SET, PT_TYPE_SMALLINT, PT_TYPE_STAR, PT_TYPE_TIME, PT_TYPE_TIMESTAMP, PT_TYPE_TIMESTAMPLTZ, PT_TYPE_TIMESTAMPTZ, PT_TYPE_VARBIT, PT_TYPE_VARCHAR, and PT_TYPE_VARNCHAR.
Referenced by check_att_chg_allowed(), check_default_on_update_clause(), do_add_attribute_from_select_column(), do_update_new_notnull_cols_without_default(), get_att_default_from_def(), func_type::Node::invalid_arg_error(), func_type::Node::preprocess(), pt_arg_type_to_string_buffer(), pt_check_cast_op(), pt_check_cume_dist_percent_rank_order_by(), pt_coerce_expression_argument(), pt_coerce_value_internal(), pt_dbval_to_value(), pt_eval_expr_type(), pt_eval_function_type_old(), pt_eval_opt_type(), pt_evaluate_db_value_expr(), pt_get_resolution(), pt_node_to_enumeration_expr(), pt_print_attr_def(), pt_print_create_stored_procedure(), pt_print_datatype(), pt_print_db_value(), pt_print_method_def(), pt_print_sp_parameter(), pt_print_value(), pt_semantic_check_local(), qo_reduce_equality_terms(), and validate_attribute_domain().
PT_NODE* pt_sort_spec_list_to_name_node_list (PARSER_CONTEXT * parser, PT_NODE * sort_spec_list)
Definition at line 17826 of file parse_tree_cl.c.
References pt_sort_spec_info::asc_or_desc, pt_sort_spec_info::expr, parser_node::info, parser_node::next, parser_node::node_type, NULL, parser_append_node(), parser_copy_tree(), PT_DESC, PT_IS_SORT_SPEC_NODE, PT_NAME, PT_NAME_INFO_DESC, PT_NAME_INFO_SET_FLAG, and pt_statement_info::sort_spec.
PT_NODE* pt_top (PARSER_CONTEXT * parser)
Definition at line 1660 of file parse_tree_cl.c.
References parser_context::node_stack, NULL, and parser_context::stack_top.
static PT_NODE * pt_walk_private (PARSER_CONTEXT * parser, PT_NODE * node, void * void_arg) static
Definition at line 843 of file parse_tree_cl.c.
References assert, pt_walk_arg::continue_walk, parser_node::next, parser_node::node_type, NULL, parser_node::or_next, parser, pt_walk_arg::post_argument, pt_walk_arg::post_function, pt_walk_arg::pre_argument, pt_walk_arg::pre_function, pt_apply_f, PT_CONTINUE_WALK, PT_LAST_NODE_NUMBER, PT_LEAF_WALK, PT_LIST_WALK, and PT_STOP_WALK.
Referenced by parser_walk_leaves(), and parser_walk_tree().
static void strcat_with_realloc (PT_STRING_BLOCK * sb, const char * tail) static
Definition at line 449 of file parse_tree_cl.c.
References pt_string_block::body, pt_string_block::length, pt_string_block::size, and strlen.
Referenced by pt_print_bytes_l(), pt_print_expr(), and pt_print_range_op().
Variable Documentation
char* g_query_string
Referenced by parser_new_node().
int g_query_string_len
Referenced by parser_new_node().
PARSER_CONTEXT* parent_parser = NULL
Definition at line 135 of file parse_tree_cl.c.
Referenced by do_check_internal_statements(), and pt_check_with_info().
PARSER_APPLY_NODE_FUNC* pt_apply_f = NULL static
Definition at line 134 of file parse_tree_cl.c.
Referenced by parser_init_func_vectors(), parser_walk_leaves(), pt_init_apply_f(), and pt_walk_private().
PARSER_APPLY_NODE_FUNC pt_apply_func_array[PT_NODE_NUMBER] static
Definition at line 269 of file parse_tree_cl.c.
Referenced by pt_init_apply_f().
PARSER_INIT_NODE_FUNC* pt_init_f = NULL static
Definition at line 132 of file parse_tree_cl.c.
Referenced by parser_init_func_vectors(), parser_init_node(), parser_reinit_node(), pt_init_init_f(), and pt_init_node().
PARSER_INIT_NODE_FUNC pt_init_func_array[PT_NODE_NUMBER] static
Definition at line 311 of file parse_tree_cl.c.
Referenced by pt_init_init_f().
PARSER_PRINT_NODE_FUNC* pt_print_f = NULL static
Definition at line 133 of file parse_tree_cl.c.
Referenced by parser_init_func_vectors(), pt_init_print_f(), and pt_print_bytes().
PARSER_PRINT_NODE_FUNC pt_print_func_array[PT_NODE_NUMBER] static
Definition at line 435 of file parse_tree_cl.c.
Referenced by pt_init_print_f().