CUBRID Engine: src/parser/parser_support.h File Reference
parser_support.h File Reference
#include "config.h"
Functions
char * pt_alloc_packing_buf (int size)
void pt_final_packing_buf (void)
void pt_enter_packing_buf (void)
void pt_exit_packing_buf (void)
void regu_set_error_with_zero_args (int err_type)
Variables
int qp_Packing_er_code
Function Documentation
char* pt_alloc_packing_buf (int size)
Definition at line 3555 of file parser_support.c.
References ARG_FILE_LINE, db_create_ostk_heap(), db_ostk_alloc(), ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), i, NULL, packing_heap, packing_heap_num_slot, packing_level, PACKING_MMGR_BLOCK_SIZE, PACKING_MMGR_CHUNK_SIZE, and qp_Packing_er_code.
Referenced by make_mergelist_proc(), pt_make_json_table_spec_node(), pt_make_json_table_spec_node_internal(), pt_plan_query(), pt_symbol_info_alloc(), pt_table_info_alloc(), pt_to_outlist(), regu_alloc(), and regu_array_alloc().
void pt_enter_packing_buf (void)
Definition at line 3545 of file parser_support.c.
References packing_level.
Referenced by build_xasl_for_server_delete(), compile_partition_expression(), create_or_drop_index_helper(), do_execute_do(), do_insert_at_server(), do_prepare_delete(), do_prepare_insert_internal(), do_prepare_merge(), do_prepare_select(), do_prepare_update(), do_recreate_filter_index_constr(), do_recreate_func_index_constr(), do_select_internal(), and update_at_server().
void pt_exit_packing_buf (void)
Definition at line 3639 of file parser_support.c.
References packing_level, and pt_free_packing_buf().
Referenced by build_xasl_for_server_delete(), compile_partition_expression(), create_or_drop_index_helper(), do_alter_index_rebuild(), do_execute_do(), do_insert_at_server(), do_prepare_delete(), do_prepare_insert_internal(), do_prepare_merge(), do_prepare_select(), do_prepare_update(), do_recreate_filter_index_constr(), do_recreate_func_index_constr(), do_select_internal(), and update_at_server().
void pt_final_packing_buf (void)
Definition at line 3649 of file parser_support.c.
References free_and_init, i, packing_heap, packing_heap_num_slot, packing_level, and pt_free_packing_buf().
Referenced by parser_final().
void regu_set_error_with_zero_args (int err_type)
Definition at line 3680 of file parser_support.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_REGU_SYSTEM, er_set(), qp_Packing_er_code, and regu_set_global_error().
Referenced by pt_agg_orderby_to_sort_list(), pt_to_sort_list(), regu_alloc(), and regu_array_alloc().
Variable Documentation
int qp_Packing_er_code
Definition at line 98 of file parser_support.c.
Referenced by pt_alloc_packing_buf(), and regu_set_error_with_zero_args().