CUBRID Engine: src/parser/parse_type.hpp File Reference
parse_type.hpp File Reference
#include "parse_tree.h"
#include <string>
Classes
struct pt_arg_type
union pt_arg_type::pt_arg_type_val
Typedefs
typedef pt_arg_type PT_ARG_TYPE
Enumerations
enum pt_generic_type_enum {
PT_GENERIC_TYPE_NONE, PT_GENERIC_TYPE_STRING, PT_GENERIC_TYPE_STRING_VARYING, PT_GENERIC_TYPE_CHAR,
PT_GENERIC_TYPE_NCHAR, PT_GENERIC_TYPE_BIT, PT_GENERIC_TYPE_DISCRETE_NUMBER, PT_GENERIC_TYPE_NUMBER,
PT_GENERIC_TYPE_DATE, PT_GENERIC_TYPE_DATETIME, PT_GENERIC_TYPE_SEQUENCE, PT_GENERIC_TYPE_LOB,
PT_GENERIC_TYPE_QUERY, PT_GENERIC_TYPE_PRIMITIVE, PT_GENERIC_TYPE_ANY, PT_GENERIC_TYPE_JSON_VAL,
PT_GENERIC_TYPE_JSON_DOC, PT_GENERIC_TYPE_SCALAR
}
Functions
const char * pt_generic_type_to_string (pt_generic_type_enum type)
const char * pt_arg_type_to_string_buffer (const pt_arg_type &type, string_buffer &sb)
PT_TYPE_ENUM pt_to_variable_size_type (PT_TYPE_ENUM type_enum)
Typedef Documentation
typedef pt_arg_type PT_ARG_TYPE
Definition at line 126 of file parse_type.hpp.
Enumeration Type Documentation
enum pt_generic_type_enum
Enumerator
PT_GENERIC_TYPE_NONE
PT_GENERIC_TYPE_STRING
PT_GENERIC_TYPE_STRING_VARYING
PT_GENERIC_TYPE_CHAR
PT_GENERIC_TYPE_NCHAR
PT_GENERIC_TYPE_BIT
PT_GENERIC_TYPE_DISCRETE_NUMBER
PT_GENERIC_TYPE_NUMBER
PT_GENERIC_TYPE_DATE
PT_GENERIC_TYPE_DATETIME
PT_GENERIC_TYPE_SEQUENCE
PT_GENERIC_TYPE_LOB
PT_GENERIC_TYPE_QUERY
PT_GENERIC_TYPE_PRIMITIVE
PT_GENERIC_TYPE_ANY
PT_GENERIC_TYPE_JSON_VAL
PT_GENERIC_TYPE_JSON_DOC
PT_GENERIC_TYPE_SCALAR
Definition at line 31 of file parse_type.hpp.
Function Documentation
const char* pt_arg_type_to_string_buffer (const pt_arg_type & type, string_buffer & sb)
Definition at line 56 of file parse_type.cpp.
References pt_arg_type::GENERIC, pt_arg_type::pt_arg_type_val::generic_type, string_buffer::get_buffer(), pt_arg_type::INDEX, pt_arg_type::pt_arg_type_val::index, pt_arg_type::NORMAL, pt_generic_type_to_string(), pt_show_type_enum(), pt_arg_type::type, pt_arg_type::pt_arg_type_val::type, and pt_arg_type::val.
Referenced by func_type::Node::get_types(), func_type::Node::invalid_arg_error(), and func_signature::to_string_buffer().
const char* pt_generic_type_to_string (pt_generic_type_enum type)
Definition at line 27 of file parse_type.cpp.
References PT_GENERIC_TYPE_SCALAR.
Referenced by pt_arg_type_to_string_buffer().
PT_TYPE_ENUM pt_to_variable_size_type (PT_TYPE_ENUM type_enum)
Definition at line 24915 of file type_checking.c.
References PT_TYPE_BIT, PT_TYPE_CHAR, PT_TYPE_NCHAR, PT_TYPE_VARBIT, PT_TYPE_VARCHAR, and PT_TYPE_VARNCHAR.
Referenced by pt_eval_expr_type(), and func_type::Node::set_return_type().