CUBRID Engine: src/parser/parse_type.cpp File Reference
parse_type.cpp File Reference
#include "parse_type.hpp"
#include "parser.h"
#include "string_buffer.hpp"
Functions
const char * pt_generic_type_to_string (pt_generic_type_enum type)
const char * pt_arg_type_to_string_buffer (const pt_arg_type &type, string_buffer &sb)
Function Documentation
const char* pt_arg_type_to_string_buffer (const pt_arg_type & type, string_buffer & sb)
Definition at line 56 of file parse_type.cpp.
References pt_arg_type::GENERIC, pt_arg_type::pt_arg_type_val::generic_type, string_buffer::get_buffer(), pt_arg_type::INDEX, pt_arg_type::pt_arg_type_val::index, pt_arg_type::NORMAL, pt_generic_type_to_string(), pt_show_type_enum(), pt_arg_type::type, pt_arg_type::pt_arg_type_val::type, and pt_arg_type::val.
Referenced by func_type::Node::get_types(), func_type::Node::invalid_arg_error(), and func_signature::to_string_buffer().
const char* pt_generic_type_to_string (pt_generic_type_enum type)
Definition at line 27 of file parse_type.cpp.
References PT_GENERIC_TYPE_SCALAR.
Referenced by pt_arg_type_to_string_buffer().