CUBRID Engine: src/query/query_method.c File Reference
query_method.c File Reference
#include "query_method.h"
#include "authenticate.h"
#include "config.h"
#include "db.h"
#include "dbtype.h"
#include "jsp_cl.h"
#include "method_def.hpp"
#include "network.h"
#include "network_interface_cl.h"
#include "object_accessor.h"
#include "object_primitive.h"
#include "object_representation.h"
#include "query_list.h"
#include "regu_var.hpp"
Functions
static int method_initialize_vacomm_buffer (VACOMM_BUFFER *vacomm_buffer, unsigned int rc, char *host, char *server_name)
static void method_clear_vacomm_buffer (VACOMM_BUFFER *vacomm_buffer)
static int method_send_value_to_server (DB_VALUE *dbval, VACOMM_BUFFER *vacomm_buffer)
static int method_send_eof_to_server (VACOMM_BUFFER *vacomm_buffer)
static void methid_sig_freemem (method_sig_node *meth_sig)
int method_send_error_to_server (unsigned int rc, char *host_p, char *server_name_p)
int method_invoke_for_server (unsigned int rc, char *host_p, char *server_name_p, qfile_list_id *list_id_p, method_sig_list *method_sig_list_p)
void method_sig_list_freemem (method_sig_list *meth_sig_list)
Function Documentation
static void methid_sig_freemem (method_sig_node * meth_sig) static
Definition at line 506 of file query_method.c.
References method_sig_node::class_name, db_private_free_and_init, method_sig_node::method_arg_pos, method_sig_node::method_name, method_sig_node::next, and NULL.
Referenced by method_sig_list_freemem().
static void method_clear_vacomm_buffer (VACOMM_BUFFER * vacomm_buffer) static
Definition at line 54 of file query_method.c.
References vacomm_buffer::area, free_and_init, vacomm_buffer::host, and vacomm_buffer::server_name.
Referenced by method_initialize_vacomm_buffer(), and method_invoke_for_server().
static int method_initialize_vacomm_buffer (VACOMM_BUFFER * vacomm_buffer, unsigned int rc, char * host, char * server_name) static
Definition at line 73 of file query_method.c.
References vacomm_buffer::action, vacomm_buffer::area, ARG_FILE_LINE, vacomm_buffer::buffer, vacomm_buffer::cur_pos, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), vacomm_buffer::host, method_clear_vacomm_buffer(), NO_ERROR, NULL, vacomm_buffer::num_vals, vacomm_buffer::rc, rc, vacomm_buffer::server_name, vacomm_buffer::size, strdup(), strlen, VACOMM_BUFFER_HEADER_SIZE, VACOMM_BUFFER_SEND, and VACOMM_BUFFER_SIZE.
Referenced by method_clear_scan_buffer(), method_invoke_for_server(), and method_open_value_array_scan().
int method_invoke_for_server (unsigned int rc, char * host_p, char * server_name_p, qfile_list_id * list_id_p, method_sig_list * method_sig_list_p)
Definition at line 271 of file query_method.c.
References vacomm_buffer::action, ARG_FILE_LINE, AU_DISABLE, AU_ENABLE, method_sig_node::class_name, cubregex::count(), cursor_close(), cursor_get_tuple_value_list(), cursor_next_tuple(), cursor_open(), cursor_set_oid_columns(), DB_CURSOR_END, DB_CURSOR_SUCCESS, db_disable_modification(), db_enable_modification(), db_get_object(), db_is_any_class(), db_is_instance(), DB_IS_NULL, db_make_null(), DB_TYPE_ERROR, DB_VALUE_TYPE, er_errid(), ER_ERROR_SEVERITY, ER_FAILED, ER_GENERIC_ERROR, ER_HEAP_UNKNOWN_OBJECT, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, jsp_call_from_server(), method_sig_node::method_arg_pos, method_clear_vacomm_buffer(), method_initialize_vacomm_buffer(), method_sig_node::method_name, method_send_eof_to_server(), method_send_value_to_server(), method_sig_list::method_sig, method_sig_node::next, NO_ERROR, NULL, method_sig_node::num_method_args, method_sig_list::num_methods, obj_send_array(), pr_clear_value(), cursor_id::query_id, qfile_list_id::tfile_vfid, qfile_tuple_value_type_list::type_cnt, qfile_list_id::type_list, and VACOMM_BUFFER_ABORT.
Referenced by net_client_request_with_callback().
static int method_send_eof_to_server (VACOMM_BUFFER * vacomm_buffer) static
Definition at line 211 of file query_method.c.
References vacomm_buffer::area, vacomm_buffer::cur_pos, ER_FAILED, error(), vacomm_buffer::host, METHOD_EOF, net_client_send_data(), NO_ERROR, vacomm_buffer::num_vals, or_pack_int(), p, vacomm_buffer::rc, VACOMM_BUFFER_HEADER_LENGTH_OFFSET, VACOMM_BUFFER_HEADER_NO_VALS_OFFSET, VACOMM_BUFFER_HEADER_SIZE, and VACOMM_BUFFER_HEADER_STATUS_OFFSET.
Referenced by method_invoke_for_server().
int method_send_error_to_server (unsigned int rc, char * host_p, char * server_name_p)
Definition at line 241 of file query_method.c.
References er_errid(), ER_FAILED, error(), METHOD_ERROR, net_client_send_data(), NO_ERROR, or_pack_int(), p, VACOMM_BUFFER_HEADER_ERROR_OFFSET, VACOMM_BUFFER_HEADER_LENGTH_OFFSET, VACOMM_BUFFER_HEADER_SIZE, and VACOMM_BUFFER_HEADER_STATUS_OFFSET.
Referenced by net_client_request_with_callback().
static int method_send_value_to_server (DB_VALUE * dbval, VACOMM_BUFFER * vacomm_buffer) static
Definition at line 124 of file query_method.c.
References vacomm_buffer::action, vacomm_buffer::area, ARG_FILE_LINE, vacomm_buffer::buffer, vacomm_buffer::cur_pos, ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), vacomm_buffer::host, METHOD_SUCCESS, net_client_receive_action(), net_client_send_data(), NO_ERROR, NULL, vacomm_buffer::num_vals, or_pack_db_value(), or_pack_int(), OR_VALUE_ALIGNED_SIZE, p, vacomm_buffer::rc, vacomm_buffer::size, VACOMM_BUFFER_HEADER_LENGTH_OFFSET, VACOMM_BUFFER_HEADER_NO_VALS_OFFSET, VACOMM_BUFFER_HEADER_SIZE, VACOMM_BUFFER_HEADER_STATUS_OFFSET, and VACOMM_BUFFER_SEND.
Referenced by method_invoke_for_server().
void method_sig_list_freemem (method_sig_list * meth_sig_list)
Definition at line 526 of file query_method.c.
References db_private_free_and_init, methid_sig_freemem(), method_sig_list::method_sig, and NULL.
Referenced by net_client_request_with_callback().