CUBRID Engine: src/query/query_dump.h File Reference
query_dump.h File Reference
#include "dbtype_def.h"
#include "storage_common.h"
#include <cstdio>
Functions
bool qdump_print_xasl (xasl_node *xasl)
const char * qdump_operator_type_string (OPERATOR_TYPE optype)
const char * qdump_default_expression_string (DB_DEFAULT_EXPR_TYPE default_expr_type)
Function Documentation
const char* qdump_default_expression_string (DB_DEFAULT_EXPR_TYPE default_expr_type)
const char* qdump_operator_type_string (OPERATOR_TYPE optype)
Definition at line 1016 of file query_dump.c.
References NULL, and T_TO_CHAR.
Referenced by catcls_get_or_value_from_attribute(), and qexec_execute_build_columns().
bool qdump_print_xasl (xasl_node * xasl)
Definition at line 2294 of file query_dump.c.
References access_spec_node::access, ACCESS_METHOD_INDEX, ACCESS_METHOD_SEQUENTIAL, ACCESS_SPEC_CLS_SPEC, xasl_node::after_join_pred, xasl_node::aptr_list, assert, xasl_node::bptr_list, indx_info::btid, BUILD_SCHEMA_PROC, xasl_node::buildlist, BUILDLIST_PROC, BUILDVALUE_PROC, xasl_node::cat_fetched, xasl_node::class_locks, xasl_node::class_oid_list, cls_spec_node::cls_oid, xasl_node::connect_by_ptr, CONNECTBY_PROC, xasl_node::creator_oid, xasl_node::cte, CTE_PROC, xasl_node::curr_spec, DB_VALUE_DOMAIN_TYPE, xasl_node::dbval_cnt, xasl_node::delete_, DELETE_PROC, DIFFERENCE_PROC, DO_PROC, xasl_node::dptr_list, buildlist_proc_node::eptr_list, er_clear(), xasl_node::flag, foutput, xasl_node::fptr_list, free_and_init, HAVE_SUBQUERY_PROC, heap_get_class_name(), heap_get_indexinfo_of_btid(), HS_ACCEPT_ALL, HS_REJECT_ALL, i, xasl_node::if_pred, access_spec_node::indexptr, mergelist_proc_node::inner_xasl, xasl_node::insert, INSERT_PROC, merge_proc_node::insert_xasl, xasl_node::instnum_flag, xasl_node::instnum_pred, xasl_node::instnum_val, INTERSECTION_PROC, xasl_node::is_single_tuple, xasl_node::iscycle_regu, xasl_node::iscycle_val, xasl_node::isleaf_regu, xasl_node::isleaf_val, union_proc_node::left, xasl_node::level_regu, xasl_node::level_val, xasl_node::list_id, LOCK_TO_LOCKMODE_STRING, xasl_node::merge, MERGE_PROC, xasl_node::merge_spec, xasl_node::mergelist, MERGELIST_PROC, xasl_node::n_oid_list, qproc_db_value_list::next, access_spec_node::next, xasl_node::next, xasl_node::next_scan_block_on, xasl_node::next_scan_on, NO_ERROR, cte_proc_node::non_recursive_part, NULL, OBJFETCH_PROC, xasl_node::option, xasl_node::ordbynum_flag, xasl_node::ordbynum_pred, xasl_node::ordbynum_val, xasl_node::orderby_limit, xasl_node::orderby_list, mergelist_proc_node::outer_xasl, xasl_node::outptr_list, prm_get_bool_value(), PRM_ID_USE_ORDERBY_SORT_LIMIT, xasl_node::proc, Q_DISTINCT, qdump_data_type_string(), qdump_print_access_spec(), qdump_print_build_list_node(), qdump_print_build_value_node(), qdump_print_connect_by_proc_node(), qdump_print_db_value(), qdump_print_delete_proc_node(), qdump_print_fetch_node(), qdump_print_insert_proc_node(), qdump_print_list_id(), qdump_print_merge_list_proc_node(), qdump_print_oid(), qdump_print_outlist(), qdump_print_predicate(), qdump_print_sort_list(), qdump_print_update_proc_node(), qdump_print_value(), qdump_print_value_list(), qdump_print_xasl(), qdump_print_xasl_type(), xasl_node::query_alias, cte_proc_node::recursive_part, union_proc_node::right, xasl_node::save_instnum_val, SCAN_PROC, xasl_node::scan_ptr, xasl_node::single_tuple, xasl_node::spec_list, TARGET_CLASS, TARGET_CLASS_ATTR, TARGET_LIST, TARGET_METHOD, TARGET_SET, TARGET_SHOWSTMT, xasl_node::tcard_list, thread_get_thread_entry_info(), TO_MSEC, access_spec_node::type, xasl_node::type, xasl_node::union_, UNION_PROC, xasl_node::update, UPDATE_PROC, merge_proc_node::update_xasl, qproc_db_value_list::val, xasl_node::val_list, val_list_node::valp, XASL_CLEAR_FLAG, XASL_INSTNUM_FLAG_SCAN_CONTINUE, XASL_IS_FLAGED, XASL_LINK_TO_REGU_VARIABLE, XASL_ORDBYNUM_FLAG_SCAN_CONTINUE, XASL_SKIP_ORDERBY_LIST, XASL_TOP_MOST_XASL, and XASL_ZERO_CORR_LEVEL.
Referenced by parser_generate_do_stmt_xasl(), parser_generate_xasl(), qdump_print_xasl(), and qexec_execute_query().