CUBRID Engine: src/query/query_method.h File Reference
query_method.h File Reference
#include "dbtype_def.h"
Classes
struct vacomm_buffer
Macros
#define VACOMM_BUFFER_SIZE 4096
Typedefs
typedef struct vacomm_buffer VACOMM_BUFFER
Functions
int method_send_error_to_server (unsigned int rc, char *host, char *server_name)
int method_invoke_for_server (unsigned int rc, char *host, char *server_name, qfile_list_id *list_id, method_sig_list *method_sig_list)
void method_sig_list_freemem (method_sig_list *meth_sig_list)
Macro Definition Documentation
#define VACOMM_BUFFER_SIZE 4096
Definition at line 34 of file query_method.h.
Referenced by method_initialize_vacomm_buffer().
Typedef Documentation
typedef struct vacomm_buffer VACOMM_BUFFER
Definition at line 36 of file query_method.h.
Function Documentation
int method_invoke_for_server (unsigned int rc, char * host, char * server_name, qfile_list_id * list_id, method_sig_list * method_sig_list)
Definition at line 271 of file query_method.c.
References vacomm_buffer::action, ARG_FILE_LINE, AU_DISABLE, AU_ENABLE, method_sig_node::class_name, cubregex::count(), cursor_close(), cursor_get_tuple_value_list(), cursor_next_tuple(), cursor_open(), cursor_set_oid_columns(), DB_CURSOR_END, DB_CURSOR_SUCCESS, db_disable_modification(), db_enable_modification(), db_get_object(), db_is_any_class(), db_is_instance(), DB_IS_NULL, db_make_null(), DB_TYPE_ERROR, DB_VALUE_TYPE, er_errid(), ER_ERROR_SEVERITY, ER_FAILED, ER_GENERIC_ERROR, ER_HEAP_UNKNOWN_OBJECT, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, jsp_call_from_server(), method_sig_node::method_arg_pos, method_clear_vacomm_buffer(), method_initialize_vacomm_buffer(), method_sig_node::method_name, method_send_eof_to_server(), method_send_value_to_server(), method_sig_list::method_sig, method_sig_node::next, NO_ERROR, NULL, method_sig_node::num_method_args, method_sig_list::num_methods, obj_send_array(), pr_clear_value(), cursor_id::query_id, qfile_list_id::tfile_vfid, qfile_tuple_value_type_list::type_cnt, qfile_list_id::type_list, and VACOMM_BUFFER_ABORT.
Referenced by net_client_request_with_callback().
int method_send_error_to_server (unsigned int rc, char * host, char * server_name)
Definition at line 241 of file query_method.c.
References er_errid(), ER_FAILED, error(), METHOD_ERROR, net_client_send_data(), NO_ERROR, or_pack_int(), p, VACOMM_BUFFER_HEADER_ERROR_OFFSET, VACOMM_BUFFER_HEADER_LENGTH_OFFSET, VACOMM_BUFFER_HEADER_SIZE, and VACOMM_BUFFER_HEADER_STATUS_OFFSET.
Referenced by net_client_request_with_callback().
void method_sig_list_freemem (method_sig_list * meth_sig_list)
Definition at line 526 of file query_method.c.
References db_private_free_and_init, methid_sig_freemem(), method_sig_list::method_sig, and NULL.
Referenced by net_client_request_with_callback().