CUBRID Engine: src/query/query_cl.h File Reference
query_cl.h File Reference
#include "parse_tree.h"
Functions
int prepare_query (compile_context *context, xasl_stream *stream)
int execute_query (const XASL_ID *xasl_id, QUERY_ID *query_idp, int var_cnt, const DB_VALUE *varptr, QFILE_LIST_ID **list_idp, QUERY_FLAG flag, CACHE_TIME *clt_cache_time, CACHE_TIME *srv_cache_time)
int prepare_and_execute_query (char *stream, int stream_size, QUERY_ID *query_id, int var_cnt, DB_VALUE *varptr, QFILE_LIST_ID **result, QUERY_FLAG flag)
Function Documentation
int execute_query (const XASL_ID * xasl_id, QUERY_ID * query_idp, int var_cnt, const DB_VALUE * varptr, QFILE_LIST_ID ** list_idp, QUERY_FLAG flag, CACHE_TIME * clt_cache_time, CACHE_TIME * srv_cache_time)
Definition at line 105 of file query_cl.c.
References assert, er_errid(), ER_FAILED, NO_ERROR, NULL, qmgr_execute_query(), qo_need_skip_execution(), query_timeout, and tran_get_query_timeout().
Referenced by do_execute_delete(), do_execute_insert(), do_execute_merge(), do_execute_select(), do_execute_session_statement(), do_execute_update(), and tzc_compute_timezone_checksum().
int prepare_and_execute_query (char * stream, int stream_size, QUERY_ID * query_id, int var_cnt, DB_VALUE * varptr, QFILE_LIST_ID ** result, QUERY_FLAG flag)
Definition at line 152 of file query_cl.c.
References assert, er_errid(), ER_FAILED, NO_ERROR, NULL, qmgr_prepare_and_execute_query(), qo_need_skip_execution(), query_timeout, and tran_get_query_timeout().
Referenced by build_xasl_for_server_delete(), do_execute_do(), do_insert_at_server(), do_select_internal(), and update_at_server().
int prepare_query (compile_context * context, xasl_stream * stream)
Definition at line 52 of file query_cl.c.
References ARG_FILE_LINE, assert, ASSERT_ERROR, xasl_stream::buffer, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, NO_ERROR, NULL, qmgr_prepare_query(), qo_need_skip_execution(), compile_context::sql_hash_text, xasl_stream::xasl_id, and XASL_ID_IS_NULL.
Referenced by do_prepare_delete(), do_prepare_insert_internal(), do_prepare_merge(), do_prepare_select(), and do_prepare_update().