CUBRID Engine: src/query/query_evaluator.c File Reference
query_evaluator.c File Reference
#include "config.h"
#include <stdio.h>
#include <string.h>
#include "system_parameter.h"
#include "error_manager.h"
#include "heap_file.h"
#include "fetch.h"
#include "list_file.h"
#include "object_primitive.h"
#include "object_representation.h"
#include "regu_var.hpp"
#include "set_object.h"
#include "xasl.h"
#include "dbtype.h"
#include "query_executor.h"
#include "thread_entry.hpp"
#include "xasl_predicate.hpp"
Macros
#define UNKNOWN_CARD -2 /* Unknown cardinality of a set member */
Functions
static DB_LOGICAL eval_negative (DB_LOGICAL res)
static DB_LOGICAL eval_logical_result (DB_LOGICAL res1, DB_LOGICAL res2)
static DB_LOGICAL eval_value_rel_cmp (DB_VALUE *dbval1, DB_VALUE *dbval2, REL_OP rel_operator, const COMP_EVAL_TERM *et_comp)
static DB_LOGICAL eval_some_eval (DB_VALUE *item, DB_SET *set, REL_OP rel_operator)
static DB_LOGICAL eval_all_eval (DB_VALUE *item, DB_SET *set, REL_OP rel_operator)
static int eval_item_card_set (DB_VALUE *item, DB_SET *set, REL_OP rel_operator)
static DB_LOGICAL eval_some_list_eval (THREAD_ENTRY *thread_p, DB_VALUE *item, QFILE_LIST_ID *list_id, REL_OP rel_operator)
static DB_LOGICAL eval_all_list_eval (THREAD_ENTRY *thread_p, DB_VALUE *item, QFILE_LIST_ID *list_id, REL_OP rel_operator)
static int eval_item_card_sort_list (THREAD_ENTRY *thread_p, DB_VALUE *item, QFILE_LIST_ID *list_id)
static DB_LOGICAL eval_sub_multi_set_to_sort_list (THREAD_ENTRY *thread_p, DB_SET *set1, QFILE_LIST_ID *list_id)
static DB_LOGICAL eval_sub_sort_list_to_multi_set (THREAD_ENTRY *thread_p, QFILE_LIST_ID *list_id, DB_SET *set)
static DB_LOGICAL eval_sub_sort_list_to_sort_list (THREAD_ENTRY *thread_p, QFILE_LIST_ID *list_id1, QFILE_LIST_ID *list_id2)
static DB_LOGICAL eval_eq_multi_set_to_sort_list (THREAD_ENTRY *thread_p, DB_SET *set, QFILE_LIST_ID *list_id)
static DB_LOGICAL eval_ne_multi_set_to_sort_list (THREAD_ENTRY *thread_p, DB_SET *set, QFILE_LIST_ID *list_id)
static DB_LOGICAL eval_le_multi_set_to_sort_list (THREAD_ENTRY *thread_p, DB_SET *set, QFILE_LIST_ID *list_id)
static DB_LOGICAL eval_lt_multi_set_to_sort_list (THREAD_ENTRY *thread_p, DB_SET *set, QFILE_LIST_ID *list_id)
static DB_LOGICAL eval_le_sort_list_to_multi_set (THREAD_ENTRY *thread_p, QFILE_LIST_ID *list_id, DB_SET *set)
static DB_LOGICAL eval_lt_sort_list_to_multi_set (THREAD_ENTRY *thread_p, QFILE_LIST_ID *list_id, DB_SET *set)
static DB_LOGICAL eval_eq_sort_list_to_sort_list (THREAD_ENTRY *thread_p, QFILE_LIST_ID *list_id1, QFILE_LIST_ID *list_id2)
static DB_LOGICAL eval_ne_sort_list_to_sort_list (THREAD_ENTRY *thread_p, QFILE_LIST_ID *list_id1, QFILE_LIST_ID *list_id2)
static DB_LOGICAL eval_le_sort_list_to_sort_list (THREAD_ENTRY *thread_p, QFILE_LIST_ID *list_id1, QFILE_LIST_ID *list_id2)
static DB_LOGICAL eval_lt_sort_list_to_sort_list (THREAD_ENTRY *thread_p, QFILE_LIST_ID *list_id1, QFILE_LIST_ID *list_id2)
static DB_LOGICAL eval_multi_set_to_sort_list (THREAD_ENTRY *thread_p, DB_SET *set, QFILE_LIST_ID *list_id, REL_OP rel_operator)
static DB_LOGICAL eval_sort_list_to_multi_set (THREAD_ENTRY *thread_p, QFILE_LIST_ID *list_id, DB_SET *set, REL_OP rel_operator)
static DB_LOGICAL eval_sort_list_to_sort_list (THREAD_ENTRY *thread_p, QFILE_LIST_ID *list_id1, QFILE_LIST_ID *list_id2, REL_OP rel_operator)
static DB_LOGICAL eval_set_list_cmp (THREAD_ENTRY *thread_p, const COMP_EVAL_TERM *et_comp, val_descr *vd, DB_VALUE *dbval1, DB_VALUE *dbval2)
DB_LOGICAL eval_pred (THREAD_ENTRY *thread_p, const PRED_EXPR *pr, val_descr *vd, OID *obj_oid)
DB_LOGICAL eval_pred_comp0 (THREAD_ENTRY *thread_p, const PRED_EXPR *pr, val_descr *vd, OID *obj_oid)
DB_LOGICAL eval_pred_comp1 (THREAD_ENTRY *thread_p, const PRED_EXPR *pr, val_descr *vd, OID *obj_oid)
DB_LOGICAL eval_pred_comp2 (THREAD_ENTRY *thread_p, const PRED_EXPR *pr, val_descr *vd, OID *obj_oid)
DB_LOGICAL eval_pred_comp3 (THREAD_ENTRY *thread_p, const PRED_EXPR *pr, val_descr *vd, OID *obj_oid)
DB_LOGICAL eval_pred_alsm4 (THREAD_ENTRY *thread_p, const PRED_EXPR *pr, val_descr *vd, OID *obj_oid)
DB_LOGICAL eval_pred_alsm5 (THREAD_ENTRY *thread_p, const PRED_EXPR *pr, val_descr *vd, OID *obj_oid)
DB_LOGICAL eval_pred_like6 (THREAD_ENTRY *thread_p, const PRED_EXPR *pr, val_descr *vd, OID *obj_oid)
DB_LOGICAL eval_pred_rlike7 (THREAD_ENTRY *thread_p, const PRED_EXPR *pr, val_descr *vd, OID *obj_oid)
PR_EVAL_FNC eval_fnc (THREAD_ENTRY *thread_p, const PRED_EXPR *pr, DB_TYPE *single_node_type)
DB_LOGICAL update_logical_result (THREAD_ENTRY *thread_p, DB_LOGICAL ev_res, int *qualification)
DB_LOGICAL eval_data_filter (THREAD_ENTRY *thread_p, OID *oid, RECDES *recdesp, HEAP_SCANCACHE *scan_cache, FILTER_INFO *filterp)
DB_LOGICAL eval_key_filter (THREAD_ENTRY *thread_p, DB_VALUE *value, FILTER_INFO *filterp)
Macro Definition Documentation
#define UNKNOWN_CARD -2 /* Unknown cardinality of a set member */
Definition at line 46 of file query_evaluator.c.
Referenced by eval_item_card_set(), eval_item_card_sort_list(), eval_sub_multi_set_to_sort_list(), eval_sub_sort_list_to_multi_set(), and eval_sub_sort_list_to_sort_list().
Function Documentation
static DB_LOGICAL eval_all_eval (DB_VALUE * item, DB_SET * set, REL_OP rel_operator) static
Definition at line 401 of file query_evaluator.c.
References eval_negative(), eval_some_eval(), R_EQ, R_EQ_TORDER, R_GE, R_GT, R_LE, R_LT, R_NE, and V_ERROR.
Referenced by eval_pred(), and eval_pred_alsm4().
static DB_LOGICAL eval_all_list_eval (THREAD_ENTRY * thread_p, DB_VALUE * item, QFILE_LIST_ID * list_id, REL_OP rel_operator) static
Definition at line 632 of file query_evaluator.c.
References eval_negative(), eval_some_list_eval(), R_EQ, R_EQ_TORDER, R_GE, R_GT, R_LE, R_LT, R_NE, and V_ERROR.
Referenced by eval_pred(), and eval_pred_alsm5().
DB_LOGICAL eval_data_filter (THREAD_ENTRY * thread_p, OID * oid, RECDES * recdesp, HEAP_SCANCACHE * scan_cache, FILTER_INFO * filterp)
Definition at line 2691 of file query_evaluator.c.
References scan_attrs::attr_cache, filter_info::class_oid, fetch_val_list(), heap_attrinfo_read_dbvalues(), NO_ERROR, NULL, PEEK, scan_pred::pr_eval_fnc, scan_pred::pred_expr, scan_pred::regu_list, filter_info::scan_attrs, filter_info::scan_pred, V_ERROR, V_TRUE, filter_info::val_descr, and filter_info::val_list.
Referenced by locator_mvcc_reevaluate_filters(), scan_next_class_attr_scan(), scan_next_heap_page_scan(), scan_next_heap_scan(), scan_next_index_key_info_scan(), scan_next_index_lookup_heap(), and scan_next_index_node_info_scan().
static DB_LOGICAL eval_eq_multi_set_to_sort_list (THREAD_ENTRY * thread_p, DB_SET * set, QFILE_LIST_ID * list_id) static
Definition at line 1244 of file query_evaluator.c.
References eval_logical_result(), eval_sub_multi_set_to_sort_list(), and eval_sub_sort_list_to_multi_set().
Referenced by eval_multi_set_to_sort_list(), eval_ne_multi_set_to_sort_list(), and eval_sort_list_to_multi_set().
static DB_LOGICAL eval_eq_sort_list_to_sort_list (THREAD_ENTRY * thread_p, QFILE_LIST_ID * list_id1, QFILE_LIST_ID * list_id2) static
Definition at line 1350 of file query_evaluator.c.
References eval_logical_result(), and eval_sub_sort_list_to_sort_list().
Referenced by eval_ne_sort_list_to_sort_list(), and eval_sort_list_to_sort_list().
PR_EVAL_FNC eval_fnc (THREAD_ENTRY * thread_p, const PRED_EXPR * pr, DB_TYPE * single_node_type)
Definition at line 2540 of file query_evaluator.c.
References DB_TYPE_NULL, cubxasl::alsm_eval_term::elemset, cubxasl::eval_term::et, cubxasl::eval_term::et_alsm, cubxasl::eval_term::et_comp, cubxasl::eval_term::et_type, eval_pred(), eval_pred_alsm4(), eval_pred_alsm5(), eval_pred_comp0(), eval_pred_comp1(), eval_pred_comp2(), eval_pred_comp3(), eval_pred_like6(), eval_pred_rlike7(), cubxasl::alsm_eval_term::item_type, cubxasl::comp_eval_term::lhs, cubxasl::pred_expr::m_eval_term, NULL, cubxasl::pred_expr::pe, R_EXISTS, R_NULL, cubxasl::comp_eval_term::rel_op, cubxasl::comp_eval_term::rhs, T_ALSM_EVAL_TERM, T_COMP_EVAL_TERM, T_EVAL_TERM, T_LIKE_EVAL_TERM, T_RLIKE_EVAL_TERM, cubxasl::comp_eval_term::type, cubxasl::pred_expr::type, regu_variable_node::type, and TYPE_LIST_ID.
Referenced by locator_eval_filter_predicate(), online_index_builder(), scan_open_class_attr_scan(), scan_open_heap_page_scan(), scan_open_heap_scan(), scan_open_index_key_info_scan(), scan_open_index_node_info_scan(), scan_open_index_scan(), scan_open_json_table_scan(), scan_open_list_scan(), scan_open_set_scan(), scan_open_showstmt_scan(), and xbtree_load_index().
static int eval_item_card_set (DB_VALUE * item, DB_SET * set, REL_OP rel_operator) static
Definition at line 463 of file query_evaluator.c.
References db_value_is_null(), ER_FAILED, eval_value_rel_cmp(), i, NO_ERROR, NULL, pr_clear_value(), PRIM_SET_NULL(), set_get_element(), set_size(), UNKNOWN_CARD, V_ERROR, and V_TRUE.
Referenced by eval_sub_multi_set_to_sort_list(), and eval_sub_sort_list_to_multi_set().
static int eval_item_card_sort_list (THREAD_ENTRY * thread_p, DB_VALUE * item, QFILE_LIST_ID * list_id) static
Definition at line 679 of file query_evaluator.c.
References pr_type::data_readval(), qfile_tuple_value_type_list::domp, ER_FAILED, eval_value_rel_cmp(), NO_ERROR, NULL, OR_BUF_INIT, PEEK, pr_clear_value(), PRIM_SET_NULL(), qfile_close_scan(), qfile_locate_tuple_value(), qfile_open_list_scan(), qfile_scan_list_next(), R_EQ, R_LT, rc, S_END, S_SUCCESS, qfile_tuple_record::tpl, tp_domain::type, qfile_list_id::type_list, UNKNOWN_CARD, V_ERROR, V_TRUE, and V_UNBOUND.
Referenced by eval_sub_multi_set_to_sort_list(), and eval_sub_sort_list_to_sort_list().
DB_LOGICAL eval_key_filter (THREAD_ENTRY * thread_p, DB_VALUE * value, FILTER_INFO * filterp)
Definition at line 2772 of file query_evaluator.c.
References assert_release, scan_attrs::attr_cache, scan_attrs::attr_ids, filter_info::btree_attr_ids, filter_info::btree_num_attrs, db_char::buf, db_data::ch, db_value::data, db_get_midxkey(), db_make_null(), DB_TYPE_MIDXKEY, DB_VALUE_DOMAIN_TYPE, db_value_is_null(), DB_VALUE_TYPE, db_value::domain, filter_info::func_idx_col_id, db_domain_info::general_info, heap_attrinfo_set(), heap_attrvalue_locate(), i, db_domain_info::general_info::is_null, db_char::medium, db_value::need_clear, NO_ERROR, NULL, scan_attrs::num_attrs, pr_clear_value(), pr_clone_value(), scan_pred::pr_eval_fnc, pr_midxkey_get_element_nocopy(), scan_pred::pred_expr, prm_get_bool_value(), PRM_ID_ORACLE_STYLE_EMPTY_STRING, QSTR_IS_ANY_CHAR_OR_BIT, scan_pred::regu_list, filter_info::scan_attrs, filter_info::scan_pred, xasl_node::type, V_ERROR, V_TRUE, and filter_info::val_descr.
Referenced by btree_apply_key_range_and_filter().
static DB_LOGICAL eval_le_multi_set_to_sort_list (THREAD_ENTRY * thread_p, DB_SET * set, QFILE_LIST_ID * list_id) static
Definition at line 1281 of file query_evaluator.c.
References eval_sub_multi_set_to_sort_list().
Referenced by eval_multi_set_to_sort_list(), and eval_sort_list_to_multi_set().
static DB_LOGICAL eval_le_sort_list_to_multi_set (THREAD_ENTRY * thread_p, QFILE_LIST_ID * list_id, DB_SET * set) static
Definition at line 1314 of file query_evaluator.c.
References eval_sub_sort_list_to_multi_set().
Referenced by eval_multi_set_to_sort_list(), and eval_sort_list_to_multi_set().
static DB_LOGICAL eval_le_sort_list_to_sort_list (THREAD_ENTRY * thread_p, QFILE_LIST_ID * list_id1, QFILE_LIST_ID * list_id2) static
Definition at line 1387 of file query_evaluator.c.
References eval_sub_sort_list_to_sort_list().
Referenced by eval_sort_list_to_sort_list().
static DB_LOGICAL eval_logical_result (DB_LOGICAL res1, DB_LOGICAL res2) static
Definition at line 116 of file query_evaluator.c.
References V_ERROR, V_FALSE, V_TRUE, and V_UNKNOWN.
Referenced by eval_eq_multi_set_to_sort_list(), eval_eq_sort_list_to_sort_list(), eval_lt_multi_set_to_sort_list(), eval_lt_sort_list_to_multi_set(), and eval_lt_sort_list_to_sort_list().
static DB_LOGICAL eval_lt_multi_set_to_sort_list (THREAD_ENTRY * thread_p, DB_SET * set, QFILE_LIST_ID * list_id) static
Definition at line 1295 of file query_evaluator.c.
References eval_logical_result(), eval_ne_multi_set_to_sort_list(), and eval_sub_multi_set_to_sort_list().
Referenced by eval_multi_set_to_sort_list(), and eval_sort_list_to_multi_set().
static DB_LOGICAL eval_lt_sort_list_to_multi_set (THREAD_ENTRY * thread_p, QFILE_LIST_ID * list_id, DB_SET * set) static
Definition at line 1328 of file query_evaluator.c.
References eval_logical_result(), eval_ne_multi_set_to_sort_list(), and eval_sub_sort_list_to_multi_set().
Referenced by eval_multi_set_to_sort_list(), and eval_sort_list_to_multi_set().
static DB_LOGICAL eval_lt_sort_list_to_sort_list (THREAD_ENTRY * thread_p, QFILE_LIST_ID * list_id1, QFILE_LIST_ID * list_id2) static
Definition at line 1402 of file query_evaluator.c.
References eval_logical_result(), eval_ne_sort_list_to_sort_list(), and eval_sub_sort_list_to_sort_list().
Referenced by eval_sort_list_to_sort_list().
static DB_LOGICAL eval_multi_set_to_sort_list (THREAD_ENTRY * thread_p, DB_SET * set, QFILE_LIST_ID * list_id, REL_OP rel_operator) static
Definition at line 1425 of file query_evaluator.c.
References eval_eq_multi_set_to_sort_list(), eval_le_multi_set_to_sort_list(), eval_le_sort_list_to_multi_set(), eval_lt_multi_set_to_sort_list(), eval_lt_sort_list_to_multi_set(), eval_ne_multi_set_to_sort_list(), R_EQ, R_GE, R_GT, R_LE, R_LT, R_NE, and V_ERROR.
Referenced by eval_set_list_cmp().
static DB_LOGICAL eval_ne_multi_set_to_sort_list (THREAD_ENTRY * thread_p, DB_SET * set, QFILE_LIST_ID * list_id) static
Definition at line 1263 of file query_evaluator.c.
References eval_eq_multi_set_to_sort_list(), and eval_negative().
Referenced by eval_lt_multi_set_to_sort_list(), eval_lt_sort_list_to_multi_set(), eval_multi_set_to_sort_list(), and eval_sort_list_to_multi_set().
static DB_LOGICAL eval_ne_sort_list_to_sort_list (THREAD_ENTRY * thread_p, QFILE_LIST_ID * list_id1, QFILE_LIST_ID * list_id2) static
Definition at line 1369 of file query_evaluator.c.
References eval_eq_sort_list_to_sort_list(), and eval_negative().
Referenced by eval_lt_sort_list_to_sort_list(), and eval_sort_list_to_sort_list().
static DB_LOGICAL eval_negative (DB_LOGICAL res) static
Definition at line 93 of file query_evaluator.c.
References V_FALSE, and V_TRUE.
Referenced by eval_all_eval(), eval_all_list_eval(), eval_ne_multi_set_to_sort_list(), eval_ne_sort_list_to_sort_list(), and eval_pred().
DB_LOGICAL eval_pred (THREAD_ENTRY * thread_p, const PRED_EXPR * pr, val_descr * vd, OID * obj_oid)
Definition at line 1650 of file query_evaluator.c.
References ARG_FILE_LINE, B_AND, B_IS, B_IS_NOT, B_OR, B_XOR, cubxasl::pred::bool_op, CHECK_REGU_VARIABLE_XASL_STATUS, db_get_set(), db_set_size(), db_string_like(), DB_TYPE_UNKNOWN, DB_VALUE_DOMAIN_TYPE, db_value_is_null(), DB_VALUE_TYPE, cubxasl::alsm_eval_term::elem, cubxasl::alsm_eval_term::elemset, cubxasl::alsm_eval_term::eq_flag, ER_ERROR_SEVERITY, ER_MAX_RECURSION_SQL_DEPTH, ER_QPROC_INVALID_DATATYPE, er_set(), cubxasl::like_eval_term::esc_char, cubxasl::eval_term::et, cubxasl::eval_term::et_alsm, cubxasl::eval_term::et_comp, cubxasl::eval_term::et_like, cubxasl::eval_term::et_type, eval_all_eval(), eval_all_list_eval(), eval_negative(), eval_pred(), eval_pred_comp1(), eval_pred_rlike7(), eval_set_list_cmp(), eval_some_eval(), eval_some_list_eval(), eval_value_rel_cmp(), EXECUTE_REGU_VARIABLE_XASL, F_ALL, fetch_peek_dbval(), cubxasl::pred::lhs, cubxasl::comp_eval_term::lhs, qfile_sorted_list_id::list_id, cubxasl::pred_expr::m_eval_term, cubxasl::pred_expr::m_not_term, cubxasl::pred_expr::m_pred, NO_ERROR, NULL, cubxasl::like_eval_term::pattern, cubxasl::pred_expr::pe, prm_get_integer_value(), PRM_ID_MAX_RECURSION_SQL_DEPTH, R_EQ_TORDER, R_EXISTS, R_NULL, R_NULLSAFE_EQ, cubxasl::comp_eval_term::rel_op, cubxasl::alsm_eval_term::rel_op, cubxasl::pred::rhs, cubxasl::comp_eval_term::rhs, set_size(), cubxasl::like_eval_term::src, regu_variable_node::regu_data_value::srlist_id, T_ALSM_EVAL_TERM, T_COMP_EVAL_TERM, T_EVAL_TERM, T_LIKE_EVAL_TERM, T_NOT_TERM, T_PRED, T_RLIKE_EVAL_TERM, thread_dec_recursion_depth(), thread_get_recursion_depth(), thread_inc_recursion_depth(), TP_IS_SET_TYPE, qfile_list_id::tuple_cnt, cubxasl::pred_expr::type, regu_variable_node::type, TYPE_LIST_ID, V_ERROR, V_FALSE, V_TRUE, V_UNKNOWN, and regu_variable_node::value.
Referenced by eval_fnc(), eval_pred(), fetch_peek_arith(), qexec_end_buildvalueblock_iterations(), qexec_eval_grbynum_pred(), qexec_eval_instnum_pred(), qexec_eval_ordbynum_pred(), qexec_execute_connect_by(), qexec_execute_duplicate_key_update(), qexec_execute_insert(), qexec_execute_obj_fetch(), qexec_execute_scan(), qexec_execute_update(), qexec_gby_finalize_group(), qexec_intprt_fnc(), qexec_iterate_connect_by_results(), qexec_merge_fnc(), qexec_merge_list_outer(), and qexec_update_connect_by_lists().
DB_LOGICAL eval_pred_alsm4 (THREAD_ENTRY * thread_p, const PRED_EXPR * pr, val_descr * vd, OID * obj_oid)
Definition at line 2302 of file query_evaluator.c.
References ARG_FILE_LINE, db_get_set(), DB_VALUE_DOMAIN_TYPE, db_value_is_null(), cubxasl::alsm_eval_term::elem, cubxasl::alsm_eval_term::elemset, cubxasl::alsm_eval_term::eq_flag, ER_ERROR_SEVERITY, ER_QPROC_INVALID_DATATYPE, er_set(), cubxasl::eval_term::et, cubxasl::eval_term::et_alsm, eval_all_eval(), eval_some_eval(), F_ALL, fetch_peek_dbval(), cubxasl::pred_expr::m_eval_term, NO_ERROR, NULL, cubxasl::pred_expr::pe, cubxasl::alsm_eval_term::rel_op, set_size(), TP_IS_SET_TYPE, V_ERROR, V_FALSE, V_TRUE, and V_UNKNOWN.
Referenced by eval_fnc().
DB_LOGICAL eval_pred_alsm5 (THREAD_ENTRY * thread_p, const PRED_EXPR * pr, val_descr * vd, OID * obj_oid)
Definition at line 2368 of file query_evaluator.c.
References CHECK_REGU_VARIABLE_XASL_STATUS, db_value_is_null(), cubxasl::alsm_eval_term::elem, cubxasl::alsm_eval_term::elemset, cubxasl::alsm_eval_term::eq_flag, cubxasl::eval_term::et, cubxasl::eval_term::et_alsm, eval_all_list_eval(), eval_some_list_eval(), EXECUTE_REGU_VARIABLE_XASL, F_ALL, fetch_peek_dbval(), qfile_sorted_list_id::list_id, cubxasl::pred_expr::m_eval_term, NO_ERROR, NULL, cubxasl::pred_expr::pe, cubxasl::alsm_eval_term::rel_op, regu_variable_node::regu_data_value::srlist_id, qfile_list_id::tuple_cnt, V_ERROR, V_FALSE, V_TRUE, V_UNKNOWN, and regu_variable_node::value.
Referenced by eval_fnc().
DB_LOGICAL eval_pred_comp0 (THREAD_ENTRY * thread_p, const PRED_EXPR * pr, val_descr * vd, OID * obj_oid)
Definition at line 2099 of file query_evaluator.c.
References db_value_is_null(), cubxasl::eval_term::et, cubxasl::eval_term::et_comp, eval_value_rel_cmp(), fetch_peek_dbval(), cubxasl::comp_eval_term::lhs, cubxasl::pred_expr::m_eval_term, NO_ERROR, NULL, cubxasl::pred_expr::pe, R_NULLSAFE_EQ, cubxasl::comp_eval_term::rel_op, cubxasl::comp_eval_term::rhs, V_ERROR, and V_UNKNOWN.
Referenced by eval_fnc().
DB_LOGICAL eval_pred_comp1 (THREAD_ENTRY * thread_p, const PRED_EXPR * pr, val_descr * vd, OID * obj_oid)
Definition at line 2148 of file query_evaluator.c.
References db_get_oid(), DB_TYPE_OID, DB_VALUE_DOMAIN_TYPE, db_value_is_null(), cubxasl::eval_term::et, cubxasl::eval_term::et_comp, fetch_peek_dbval(), heap_is_object_not_null(), cubxasl::comp_eval_term::lhs, cubxasl::pred_expr::m_eval_term, NO_ERROR, NULL, cubxasl::pred_expr::pe, V_ERROR, V_FALSE, and V_TRUE.
Referenced by eval_fnc(), and eval_pred().
DB_LOGICAL eval_pred_comp2 (THREAD_ENTRY * thread_p, const PRED_EXPR * pr, val_descr * vd, OID * obj_oid)
Definition at line 2187 of file query_evaluator.c.
References ARG_FILE_LINE, CHECK_REGU_VARIABLE_XASL_STATUS, db_get_set(), DB_VALUE_DOMAIN_TYPE, db_value_is_null(), ER_ERROR_SEVERITY, ER_QPROC_INVALID_DATATYPE, er_set(), cubxasl::eval_term::et, cubxasl::eval_term::et_comp, EXECUTE_REGU_VARIABLE_XASL, fetch_peek_dbval(), cubxasl::comp_eval_term::lhs, qfile_sorted_list_id::list_id, cubxasl::pred_expr::m_eval_term, NO_ERROR, NULL, cubxasl::pred_expr::pe, set_size(), regu_variable_node::regu_data_value::srlist_id, TP_IS_SET_TYPE, qfile_list_id::tuple_cnt, regu_variable_node::type, TYPE_LIST_ID, V_ERROR, V_FALSE, V_TRUE, V_UNKNOWN, and regu_variable_node::value.
Referenced by eval_fnc().
DB_LOGICAL eval_pred_comp3 (THREAD_ENTRY * thread_p, const PRED_EXPR * pr, val_descr * vd, OID * obj_oid)
Definition at line 2244 of file query_evaluator.c.
References db_value_is_null(), cubxasl::eval_term::et, cubxasl::eval_term::et_comp, eval_set_list_cmp(), fetch_peek_dbval(), cubxasl::comp_eval_term::lhs, cubxasl::pred_expr::m_eval_term, NO_ERROR, NULL, cubxasl::pred_expr::pe, cubxasl::comp_eval_term::rhs, regu_variable_node::type, TYPE_LIST_ID, V_ERROR, and V_UNKNOWN.
Referenced by eval_fnc().
DB_LOGICAL eval_pred_like6 (THREAD_ENTRY * thread_p, const PRED_EXPR * pr, val_descr * vd, OID * obj_oid)
Definition at line 2426 of file query_evaluator.c.
References db_string_like(), db_value_is_null(), cubxasl::like_eval_term::esc_char, cubxasl::eval_term::et, cubxasl::eval_term::et_like, fetch_peek_dbval(), cubxasl::pred_expr::m_eval_term, NO_ERROR, NULL, cubxasl::like_eval_term::pattern, cubxasl::pred_expr::pe, cubxasl::like_eval_term::src, V_ERROR, and V_UNKNOWN.
Referenced by eval_fnc().
DB_LOGICAL eval_pred_rlike7 (THREAD_ENTRY * thread_p, const PRED_EXPR * pr, val_descr * vd, OID * obj_oid)
Definition at line 2484 of file query_evaluator.c.
References cubxasl::rlike_eval_term::case_sensitive, cubxasl::rlike_eval_term::compiled_pattern, cubxasl::rlike_eval_term::compiled_regex, db_string_rlike(), db_value_is_null(), cubxasl::eval_term::et, cubxasl::eval_term::et_rlike, fetch_peek_dbval(), cubxasl::pred_expr::m_eval_term, NO_ERROR, NULL, cubxasl::rlike_eval_term::pattern, cubxasl::pred_expr::pe, cubxasl::rlike_eval_term::src, V_ERROR, and V_UNKNOWN.
Referenced by eval_fnc(), and eval_pred().
static DB_LOGICAL eval_set_list_cmp (THREAD_ENTRY * thread_p, const COMP_EVAL_TERM * et_comp, val_descr * vd, DB_VALUE * dbval1, DB_VALUE * dbval2) static
Definition at line 1526 of file query_evaluator.c.
References CHECK_REGU_VARIABLE_XASL_STATUS, db_get_set(), eval_multi_set_to_sort_list(), eval_sort_list_to_multi_set(), eval_sort_list_to_sort_list(), EXECUTE_REGU_VARIABLE_XASL, cubxasl::comp_eval_term::lhs, qfile_sorted_list_id::list_id, NULL, Q_ALL, qfile_sort_list(), cubxasl::comp_eval_term::rel_op, cubxasl::comp_eval_term::rhs, qfile_sorted_list_id::sorted, regu_variable_node::regu_data_value::srlist_id, qfile_list_id::tuple_cnt, regu_variable_node::type, TYPE_LIST_ID, V_ERROR, V_UNKNOWN, and regu_variable_node::value.
Referenced by eval_pred(), and eval_pred_comp3().
static DB_LOGICAL eval_some_eval (DB_VALUE * item, DB_SET * set, REL_OP rel_operator) static
Definition at line 337 of file query_evaluator.c.
References eval_value_rel_cmp(), i, NO_ERROR, NULL, pr_clear_value(), PRIM_SET_NULL(), set_get_element(), set_size(), V_ERROR, V_FALSE, V_TRUE, and V_UNKNOWN.
Referenced by eval_all_eval(), eval_pred(), and eval_pred_alsm4().
static DB_LOGICAL eval_some_list_eval (THREAD_ENTRY * thread_p, DB_VALUE * item, QFILE_LIST_ID * list_id, REL_OP rel_operator) static
Definition at line 533 of file query_evaluator.c.
References pr_type::data_readval(), qfile_tuple_value_type_list::domp, eval_value_rel_cmp(), NO_ERROR, NULL, OR_BUF_INIT, PEEK, pr_clear_value(), PRIM_SET_NULL(), qfile_close_scan(), qfile_locate_tuple_value(), qfile_open_list_scan(), qfile_scan_list_next(), S_END, S_SUCCESS, qfile_tuple_record::tpl, qfile_list_id::tuple_cnt, tp_domain::type, qfile_list_id::type_list, V_ERROR, V_FALSE, V_TRUE, V_UNBOUND, and V_UNKNOWN.
Referenced by eval_all_list_eval(), eval_pred(), and eval_pred_alsm5().
static DB_LOGICAL eval_sort_list_to_multi_set (THREAD_ENTRY * thread_p, QFILE_LIST_ID * list_id, DB_SET * set, REL_OP rel_operator) static
Definition at line 1459 of file query_evaluator.c.
References eval_eq_multi_set_to_sort_list(), eval_le_multi_set_to_sort_list(), eval_le_sort_list_to_multi_set(), eval_lt_multi_set_to_sort_list(), eval_lt_sort_list_to_multi_set(), eval_ne_multi_set_to_sort_list(), R_EQ, R_GE, R_GT, R_LE, R_LT, R_NE, and V_ERROR.
Referenced by eval_set_list_cmp().
static DB_LOGICAL eval_sort_list_to_sort_list (THREAD_ENTRY * thread_p, QFILE_LIST_ID * list_id1, QFILE_LIST_ID * list_id2, REL_OP rel_operator) static
Definition at line 1493 of file query_evaluator.c.
References eval_eq_sort_list_to_sort_list(), eval_le_sort_list_to_sort_list(), eval_lt_sort_list_to_sort_list(), eval_ne_sort_list_to_sort_list(), R_EQ, R_GE, R_GT, R_LE, R_LT, R_NE, and V_ERROR.
Referenced by eval_set_list_cmp().
static DB_LOGICAL eval_sub_multi_set_to_sort_list (THREAD_ENTRY * thread_p, DB_SET * set1, QFILE_LIST_ID * list_id) static
Definition at line 776 of file query_evaluator.c.
References db_value_is_null(), ER_FAILED, eval_item_card_set(), eval_item_card_sort_list(), eval_value_rel_cmp(), i, NO_ERROR, NULL, pr_clear_value(), PRIM_SET_NULL(), R_EQ, rc, set_get_element(), set_size(), UNKNOWN_CARD, V_ERROR, V_FALSE, V_TRUE, and V_UNKNOWN.
Referenced by eval_eq_multi_set_to_sort_list(), eval_le_multi_set_to_sort_list(), and eval_lt_multi_set_to_sort_list().
static DB_LOGICAL eval_sub_sort_list_to_multi_set (THREAD_ENTRY * thread_p, QFILE_LIST_ID * list_id, DB_SET * set) static
Definition at line 890 of file query_evaluator.c.
References pr_type::data_readval(), DB_PAGESIZE, db_private_alloc, db_private_free_and_init, db_private_realloc, qfile_tuple_value_type_list::domp, ER_FAILED, eval_item_card_set(), eval_value_rel_cmp(), NO_ERROR, NULL, OR_BUF_INIT, or_init(), PEEK, pr_clear_value(), PRIM_SET_NULL(), qfile_close_scan(), QFILE_GET_TUPLE_LENGTH, QFILE_GET_TUPLE_VALUE_LENGTH, qfile_locate_tuple_value(), qfile_open_list_scan(), qfile_scan_list_next(), QFILE_TUPLE_LENGTH_SIZE, QFILE_TUPLE_VALUE_HEADER_SIZE, R_EQ, rc, S_END, S_SUCCESS, qfile_tuple_record::size, qfile_tuple_record::tpl, qfile_list_id::tuple_cnt, tp_domain::type, qfile_list_id::type_list, UNKNOWN_CARD, V_ERROR, V_FALSE, V_TRUE, V_UNBOUND, and V_UNKNOWN.
Referenced by eval_eq_multi_set_to_sort_list(), eval_le_sort_list_to_multi_set(), and eval_lt_sort_list_to_multi_set().
static DB_LOGICAL eval_sub_sort_list_to_sort_list (THREAD_ENTRY * thread_p, QFILE_LIST_ID * list_id1, QFILE_LIST_ID * list_id2) static
Definition at line 1066 of file query_evaluator.c.
References pr_type::data_readval(), DB_PAGESIZE, db_private_alloc, db_private_free_and_init, db_private_realloc, qfile_tuple_value_type_list::domp, ER_FAILED, eval_item_card_sort_list(), eval_value_rel_cmp(), NO_ERROR, NULL, OR_BUF_INIT, or_init(), PEEK, pr_clear_value(), PRIM_SET_NULL(), qfile_close_scan(), QFILE_GET_TUPLE_LENGTH, QFILE_GET_TUPLE_VALUE_LENGTH, qfile_locate_tuple_value(), qfile_open_list_scan(), qfile_scan_list_next(), QFILE_TUPLE_LENGTH_SIZE, QFILE_TUPLE_VALUE_HEADER_SIZE, R_EQ, rc, S_END, S_SUCCESS, qfile_tuple_record::size, qfile_tuple_record::tpl, qfile_list_id::tuple_cnt, tp_domain::type, qfile_list_id::type_list, UNKNOWN_CARD, V_ERROR, V_FALSE, V_TRUE, V_UNBOUND, and V_UNKNOWN.
Referenced by eval_eq_sort_list_to_sort_list(), eval_le_sort_list_to_sort_list(), and eval_lt_sort_list_to_sort_list().
static DB_LOGICAL eval_value_rel_cmp (DB_VALUE * dbval1, DB_VALUE * dbval2, REL_OP rel_operator, const COMP_EVAL_TERM * et_comp) static
Definition at line 149 of file query_evaluator.c.
References assert, DB_EQ, DB_GT, DB_IS_NULL, DB_LT, DB_SUBSET, DB_SUPERSET, DB_TYPE_DOUBLE, DB_TYPE_OBJECT, DB_UNK, DB_VALUE_DOMAIN_TYPE, cubxasl::comp_eval_term::lhs, NULL, R_EQ, R_EQ_TORDER, R_GE, R_GT, R_LE, R_LT, R_NE, R_NULLSAFE_EQ, R_SUBSET, R_SUBSETEQ, R_SUPERSET, R_SUPERSETEQ, REGU_VARIABLE_FETCH_ALL_CONST, REGU_VARIABLE_FETCH_NOT_CONST, REGU_VARIABLE_IS_FLAGED(), cubxasl::comp_eval_term::rhs, tp_domain_resolve_default(), TP_IS_CHAR_TYPE, TP_IS_DATE_OR_TIME_TYPE, TP_IS_NUMERIC_TYPE, tp_more_general_type(), tp_set_compare(), tp_value_coerce(), tp_value_compare_with_error(), V_ERROR, V_FALSE, V_TRUE, and V_UNKNOWN.
Referenced by eval_item_card_set(), eval_item_card_sort_list(), eval_pred(), eval_pred_comp0(), eval_some_eval(), eval_some_list_eval(), eval_sub_multi_set_to_sort_list(), eval_sub_sort_list_to_multi_set(), and eval_sub_sort_list_to_sort_list().
DB_LOGICAL update_logical_result (THREAD_ENTRY * thread_p, DB_LOGICAL ev_res, int * qualification)
Definition at line 2618 of file query_evaluator.c.
References assert, NULL, QPROC_NOT_QUALIFIED, QPROC_QUALIFIED, QPROC_QUALIFIED_OR_NOT, V_ERROR, V_FALSE, and V_TRUE.
Referenced by locator_mvcc_reevaluate_filters(), and scan_next_index_lookup_heap().