CUBRID Engine: src/query/query_dump.c File Reference
query_dump.c File Reference
#include "config.h"
#include <stdio.h>
#include "jansson.h"
#include "query_dump.h"
#include "object_primitive.h"
#include "system_parameter.h"
#include "dbtype.h"
#include "xasl.h"
#include "xasl_aggregate.hpp"
#include "xasl_predicate.hpp"
Classes
struct qdump_xasl_check_node
Macros
#define foutput stdout
#define HASH_NUMBER 128
#define HAVE_SUBQUERY_PROC(xasl_p)
Typedefs
typedef struct qdump_xasl_check_node QDUMP_XASL_CHECK_NODE
Enumerations
enum { ARITH_EXP = 0, AGG_EXP = 1 }
Functions
static bool qdump_print_xasl_type (XASL_NODE *xasl)
static bool qdump_print_db_value_array (DB_VALUE **array, int cnt)
static bool qdump_print_column (const char *title_p, int col_count, int *column_p)
static bool qdump_print_list_merge_info (QFILE_LIST_MERGE_INFO *ptr)
static bool qdump_print_merge_list_proc_node (MERGELIST_PROC_NODE *ptr)
static bool qdump_print_update_proc_node (UPDATE_PROC_NODE *ptr)
static bool qdump_print_delete_proc_node (DELETE_PROC_NODE *ptr)
static bool qdump_print_insert_proc_node (INSERT_PROC_NODE *ptr)
static const char * qdump_target_type_string (TARGET_TYPE type)
static const char * qdump_access_method_string (ACCESS_METHOD access)
static bool qdump_print_access_spec (ACCESS_SPEC_TYPE *spec_list)
static const char * qdump_key_range_string (RANGE range)
static bool qdump_print_key_info (KEY_INFO *key_info)
static const char * qdump_range_type_string (RANGE_TYPE range_type)
static bool qdump_print_index (INDX_INFO *indexptr)
static bool qdump_print_btid (BTID id)
static bool qdump_print_class (CLS_SPEC_TYPE *ptr)
static bool qdump_print_hfid (HFID id)
static bool qdump_print_vfid (VFID id)
static bool qdump_print_list (LIST_SPEC_TYPE *ptr)
static bool qdump_print_showstmt (SHOWSTMT_SPEC_TYPE *ptr)
static bool qdump_print_outlist (const char *title, OUTPTR_LIST *outlist)
static bool qdump_print_list_id (QFILE_LIST_ID *idptr)
static bool qdump_print_type_list (QFILE_TUPLE_VALUE_TYPE_LIST *typeptr)
static bool qdump_print_domain_list (int cnt, TP_DOMAIN **ptr)
static bool qdump_print_sort_list (SORT_LIST *sorting_list)
static bool qdump_print_attribute_id (ATTR_DESCR attr)
static bool qdump_print_tuple_value_position (QFILE_TUPLE_VALUE_POSITION pos)
static bool qdump_print_value_list (VAL_LIST *vallist)
static bool qdump_print_regu_variable_list (REGU_VARIABLE_LIST varlist)
static const char * qdump_option_string (int option)
static bool qdump_print_db_value (DB_VALUE *value)
static const char * qdump_regu_type_string (REGU_DATATYPE type)
static bool qdump_print_regu_type (REGU_VARIABLE *value)
static const char * qdump_data_type_string (DB_TYPE type)
static bool qdump_print_value (REGU_VARIABLE *value)
static bool qdump_print_function_value (REGU_VARIABLE *regu)
static bool qdump_print_value_type_addr (REGU_VARIABLE *value)
static bool qdump_print_oid (OID *oidptr)
static bool qdump_print_predicate (PRED_EXPR *predptr)
static const char * qdump_relation_operator_string (int op)
static const char * qdump_arith_operator_string (OPERATOR_TYPE opcode)
static bool qdump_print_arith_expression (ARITH_TYPE *arith_p)
static bool qdump_print_aggregate_expression (AGGREGATE_TYPE *aggptr)
static bool qdump_print_arith (int type, void *ptr)
static bool qdump_print_term (PRED_EXPR *pred_ptr)
static const char * qdump_bool_operator_string (BOOL_OP bool_op)
static bool qdump_print_lhs_predicate (PRED_EXPR *pred_p)
static bool qdump_print_attribute (const char *action_p, int attr_count, int *attr_ids_p)
const char * qdump_operator_type_string (OPERATOR_TYPE optype)
static bool qdump_print_comp_eval_term (EVAL_TERM *term_p)
static bool qdump_print_alsm_eval_term (EVAL_TERM *term_p)
static bool qdump_print_like_eval_term (EVAL_TERM *term_p)
static bool qdump_print_rlike_eval_term (EVAL_TERM *term_p)
static bool qdump_print_eval_term (PRED_EXPR *pred_p)
static bool qdump_print_fetch_node (XASL_NODE *xasl_p)
static bool qdump_print_build_list_node (XASL_NODE *xasl_p)
static bool qdump_print_build_value_node (XASL_NODE *xasl_p)
static bool qdump_print_connect_by_proc_node (XASL_NODE *xasl_p)
bool qdump_print_xasl (xasl_node *xasl_p)
Macro Definition Documentation
#define foutput stdout
Definition at line 40 of file query_dump.c.
Referenced by qdump_print_access_spec(), qdump_print_aggregate_expression(), qdump_print_alsm_eval_term(), qdump_print_arith_expression(), qdump_print_attribute(), qdump_print_attribute_id(), qdump_print_btid(), qdump_print_build_list_node(), qdump_print_build_value_node(), qdump_print_class(), qdump_print_column(), qdump_print_comp_eval_term(), qdump_print_connect_by_proc_node(), qdump_print_db_value_array(), qdump_print_delete_proc_node(), qdump_print_domain_list(), qdump_print_fetch_node(), qdump_print_function_value(), qdump_print_hfid(), qdump_print_index(), qdump_print_insert_proc_node(), qdump_print_key_info(), qdump_print_lhs_predicate(), qdump_print_like_eval_term(), qdump_print_list(), qdump_print_list_id(), qdump_print_list_merge_info(), qdump_print_merge_list_proc_node(), qdump_print_oid(), qdump_print_outlist(), qdump_print_predicate(), qdump_print_regu_type(), qdump_print_regu_variable_list(), qdump_print_rlike_eval_term(), qdump_print_showstmt(), qdump_print_sort_list(), qdump_print_term(), qdump_print_tuple_value_position(), qdump_print_type_list(), qdump_print_update_proc_node(), qdump_print_value(), qdump_print_value_list(), qdump_print_value_type_addr(), qdump_print_vfid(), qdump_print_xasl(), and qdump_print_xasl_type().
#define HASH_NUMBER 128
Definition at line 48 of file query_dump.c.
Referenced by qdump_print_arith().
#define HAVE_SUBQUERY_PROC (xasl_p)
Value:
((xasl_p)->type != MERGELIST_PROC && (xasl_p)->type != UNION_PROC \
   && (xasl_p)->type != INTERSECTION_PROC && (xasl_p)->type != DIFFERENCE_PROC)
Definition at line 50 of file query_dump.c.
Referenced by qdump_print_xasl().
Typedef Documentation
typedef struct qdump_xasl_check_node QDUMP_XASL_CHECK_NODE
Definition at line 54 of file query_dump.c.
Enumeration Type Documentation
anonymous enum
Enumerator
ARITH_EXP
AGG_EXP
Definition at line 42 of file query_dump.c.
Function Documentation
static const char * qdump_access_method_string (ACCESS_METHOD access) static
Definition at line 435 of file query_dump.c.
References ACCESS_METHOD_INDEX, ACCESS_METHOD_SEQUENTIAL, ACCESS_METHOD_SEQUENTIAL_PAGE_SCAN, and ACCESS_METHOD_SEQUENTIAL_RECORD_INFO.
Referenced by qdump_print_access_spec().
static const char * qdump_arith_operator_string (OPERATOR_TYPE opcode) static
Definition at line 1673 of file query_dump.c.
References T_ADD, T_BIT_AND, T_BIT_NOT, T_BIT_OR, T_BIT_XOR, T_BITSHIFT_LEFT, T_BITSHIFT_RIGHT, T_DIV, T_INTDIV, T_INTMOD, T_MUL, T_STRCAT, and T_SUB.
Referenced by qdump_print_arith_expression().
static const char * qdump_bool_operator_string (BOOL_OP bool_op) static
Definition at line 1529 of file query_dump.c.
References B_AND, B_IS, B_IS_NOT, B_OR, and B_XOR.
Referenced by qdump_print_lhs_predicate().
static const char * qdump_data_type_string (DB_TYPE type) static
Definition at line 1100 of file query_dump.c.
References DB_TYPE_BIGINT, DB_TYPE_BIT, DB_TYPE_BLOB, DB_TYPE_CHAR, DB_TYPE_CLOB, DB_TYPE_DATE, DB_TYPE_DATETIME, DB_TYPE_DATETIMELTZ, DB_TYPE_DATETIMETZ, DB_TYPE_DB_VALUE, DB_TYPE_DOUBLE, DB_TYPE_ENUMERATION, DB_TYPE_ERROR, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_JSON, DB_TYPE_MIDXKEY, DB_TYPE_MONETARY, DB_TYPE_MULTISET, DB_TYPE_NCHAR, DB_TYPE_NULL, DB_TYPE_NUMERIC, DB_TYPE_OBJECT, DB_TYPE_OID, DB_TYPE_POINTER, DB_TYPE_RESULTSET, DB_TYPE_SEQUENCE, DB_TYPE_SET, DB_TYPE_SMALLINT, DB_TYPE_SUB, DB_TYPE_TABLE, DB_TYPE_TIME, DB_TYPE_TIMESTAMP, DB_TYPE_TIMESTAMPLTZ, DB_TYPE_TIMESTAMPTZ, DB_TYPE_VARBIT, DB_TYPE_VARCHAR, DB_TYPE_VARIABLE, DB_TYPE_VARNCHAR, and DB_TYPE_VOBJ.
Referenced by qdump_print_aggregate_expression(), qdump_print_alsm_eval_term(), qdump_print_arith_expression(), qdump_print_attribute_id(), qdump_print_build_list_node(), qdump_print_build_value_node(), qdump_print_comp_eval_term(), qdump_print_domain_list(), qdump_print_fetch_node(), qdump_print_regu_type(), qdump_print_tuple_value_position(), qdump_print_value(), qdump_print_value_list(), and qdump_print_xasl().
static const char * qdump_key_range_string (RANGE range) static
Definition at line 538 of file query_dump.c.
References EQ_NA, GE_INF, GE_LE, GE_LT, GT_INF, GT_LE, GT_LT, INF_INF, INF_LE, INF_LT, and NA_NA.
Referenced by qdump_print_key_info().
const char* qdump_operator_type_string (OPERATOR_TYPE optype)
Definition at line 1016 of file query_dump.c.
References NULL, and T_TO_CHAR.
Referenced by catcls_get_or_value_from_attribute(), and qexec_execute_build_columns().
static const char * qdump_option_string (int option) static
Definition at line 990 of file query_dump.c.
References Q_ALL, and Q_DISTINCT.
Referenced by qdump_print_aggregate_expression().
static bool qdump_print_access_spec (ACCESS_SPEC_TYPE * spec_list) static
Definition at line 458 of file query_dump.c.
References access_spec_node::access, ACCESS_SPEC_CLS_SPEC, ACCESS_SPEC_LIST_SPEC, ACCESS_SPEC_SET_PTR, ACCESS_SPEC_SHOWSTMT_SPEC, foutput, access_spec_node::indexptr, IS_ANY_INDEX_ACCESS, access_spec_node::next, NULL, qdump_access_method_string(), qdump_print_class(), qdump_print_db_value(), qdump_print_index(), qdump_print_list(), qdump_print_predicate(), qdump_print_showstmt(), qdump_print_value(), qdump_target_type_string(), access_spec_node::s_dbval, access_spec_node::single_fetch, TARGET_CLASS, TARGET_LIST, TARGET_SET, TARGET_SHOWSTMT, access_spec_node::type, access_spec_node::where_key, access_spec_node::where_pred, and access_spec_node::where_range.
Referenced by qdump_print_merge_list_proc_node(), and qdump_print_xasl().
static bool qdump_print_aggregate_expression (AGGREGATE_TYPE * aggptr) static
Definition at line 1760 of file query_dump.c.
References cubxasl::aggregate_list_node::accumulator, AGG_EXP, cubxasl::aggregate_list_node::btid, DB_VALUE_DOMAIN_TYPE, fcode_get_uppercase_name(), cubxasl::aggregate_list_node::flag_agg_optimize, foutput, cubxasl::aggregate_list_node::function, cubxasl::aggregate_list_node::list_id, cubxasl::aggregate_list_node::next, regu_variable_list_node::next, NULL, cubxasl::aggregate_list_node::operands, cubxasl::aggregate_list_node::option, qdump_data_type_string(), qdump_option_string(), qdump_print_arith(), qdump_print_btid(), qdump_print_list_id(), qdump_print_value(), cubxasl::aggregate_accumulator::value, and regu_variable_list_node::value.
Referenced by qdump_print_arith().
static bool qdump_print_alsm_eval_term (EVAL_TERM * term_p) static
Definition at line 1401 of file query_dump.c.
References cubxasl::alsm_eval_term::elem, cubxasl::alsm_eval_term::elemset, cubxasl::alsm_eval_term::eq_flag, cubxasl::eval_term::et, cubxasl::eval_term::et_alsm, F_ALL, F_SOME, foutput, cubxasl::alsm_eval_term::item_type, qdump_data_type_string(), qdump_print_value(), qdump_relation_operator_string(), and cubxasl::alsm_eval_term::rel_op.
Referenced by qdump_print_eval_term().
static bool qdump_print_arith (int type, void * ptr) static
Definition at line 1810 of file query_dump.c.
References ACCESS_SPEC_XASL_NODE, AGG_EXP, xasl_node::aptr_list, ARITH_EXP, xasl_node::bptr_list, xasl_node::buildlist, BUILDLIST_PROC, xasl_node::connect_by_ptr, DIFFERENCE_PROC, xasl_node::dptr_list, buildlist_proc_node::eptr_list, error(), xasl_node::fptr_list, free_and_init, HASH_NUMBER, i, mergelist_proc_node::inner_xasl, INTERSECTION_PROC, union_proc_node::left, xasl_node::mergelist, MERGELIST_PROC, qdump_xasl_check_node::next, access_spec_node::next, xasl_node::next, NULL, xasl_node::proc, qdump_print_aggregate_expression(), qdump_print_arith_expression(), qdump_xasl_check_node::reachable, qdump_xasl_check_node::referenced, union_proc_node::right, xasl_node::scan_ptr, xasl_node::spec_list, TARGET_LIST, access_spec_node::type, xasl_node::type, xasl_node::union_, UNION_PROC, qdump_xasl_check_node::xasl_addr, and qdump_xasl_check_node::xasl_type.
Referenced by qdump_print_aggregate_expression(), qdump_print_build_list_node(), qdump_print_build_value_node(), and qdump_print_value().
static bool qdump_print_arith_expression (ARITH_TYPE * arith_p) static
Definition at line 1709 of file query_dump.c.
References DB_VALUE_DOMAIN_TYPE, foutput, arith_list_node::leftptr, arith_list_node::opcode, qdump_arith_operator_string(), qdump_data_type_string(), qdump_print_value(), arith_list_node::rightptr, T_UNMINUS, T_UNPLUS, and arith_list_node::value.
Referenced by qdump_print_arith().
static bool qdump_print_attribute (const char * action_p, int attr_count, int * attr_ids_p) static
Definition at line 300 of file query_dump.c.
References foutput, and i.
Referenced by qdump_print_insert_proc_node(), and qdump_print_update_proc_node().
static bool qdump_print_attribute_id (ATTR_DESCR attr) static
Definition at line 897 of file query_dump.c.
References foutput, attr_descr_node::id, qdump_data_type_string(), and attr_descr_node::type.
Referenced by qdump_print_value().
static bool qdump_print_btid (BTID id) static
Definition at line 668 of file query_dump.c.
References vfid::fileid, and foutput.
Referenced by qdump_print_aggregate_expression(), and qdump_print_index().
static bool qdump_print_build_list_node (XASL_NODE * xasl_p) static
Definition at line 2068 of file query_dump.c.
References AGG_EXP, xasl_node::buildlist, DB_VALUE_DOMAIN_TYPE, buildlist_proc_node::eptr_list, foutput, buildlist_proc_node::g_agg_list, buildlist_proc_node::g_grbynum_flag, buildlist_proc_node::g_grbynum_pred, buildlist_proc_node::g_grbynum_val, buildlist_proc_node::g_having_pred, buildlist_proc_node::g_outptr_list, buildlist_proc_node::g_regu_list, buildlist_proc_node::g_val_list, buildlist_proc_node::g_with_rollup, buildlist_proc_node::groupby_list, NULL, xasl_node::outptr_list, buildlist_proc_node::output_columns, xasl_node::proc, qdump_data_type_string(), qdump_print_arith(), qdump_print_db_value(), qdump_print_db_value_array(), qdump_print_outlist(), qdump_print_predicate(), qdump_print_regu_variable_list(), qdump_print_sort_list(), qdump_print_value_list(), valptr_list_node::valptr_cnt, and XASL_G_GRBYNUM_FLAG_SCAN_CONTINUE.
Referenced by qdump_print_xasl().
static bool qdump_print_build_value_node (XASL_NODE * xasl_p) static
Definition at line 2156 of file query_dump.c.
References AGG_EXP, buildvalue_proc_node::agg_list, ARITH_EXP, xasl_node::buildvalue, DB_VALUE_DOMAIN_TYPE, foutput, buildvalue_proc_node::grbynum_val, buildvalue_proc_node::having_pred, buildvalue_proc_node::is_always_false, buildvalue_proc_node::outarith_list, xasl_node::proc, qdump_data_type_string(), qdump_print_arith(), qdump_print_db_value(), and qdump_print_predicate().
Referenced by qdump_print_xasl().
static bool qdump_print_class (CLS_SPEC_TYPE * ptr) static
Definition at line 680 of file query_dump.c.
References cls_spec_node::cls_oid, cls_spec_node::cls_regu_list_key, cls_spec_node::cls_regu_list_pred, cls_spec_node::cls_regu_list_rest, foutput, cls_spec_node::hfid, db_identifier::pageid, qdump_print_hfid(), qdump_print_regu_variable_list(), db_identifier::slotid, and db_identifier::volid.
Referenced by qdump_print_access_spec().
static bool qdump_print_column (const char * title_p, int col_count, int * column_p) static
Definition at line 210 of file query_dump.c.
References foutput, and i.
Referenced by qdump_print_list_merge_info().
static bool qdump_print_comp_eval_term (EVAL_TERM * term_p) static
Definition at line 1383 of file query_dump.c.
References cubxasl::eval_term::et, cubxasl::eval_term::et_comp, foutput, cubxasl::comp_eval_term::lhs, NULL, qdump_data_type_string(), qdump_print_value(), qdump_relation_operator_string(), cubxasl::comp_eval_term::rel_op, cubxasl::comp_eval_term::rhs, and cubxasl::comp_eval_term::type.
Referenced by qdump_print_eval_term().
static bool qdump_print_connect_by_proc_node (XASL_NODE * xasl_p) static
Definition at line 2198 of file query_dump.c.
References connectby_proc_node::after_cb_regu_list_pred, connectby_proc_node::after_cb_regu_list_rest, connectby_proc_node::after_connect_by_pred, xasl_node::connect_by, foutput, connectby_proc_node::input_list_id, connectby_proc_node::prior_outptr_list, connectby_proc_node::prior_regu_list_pred, connectby_proc_node::prior_regu_list_rest, connectby_proc_node::prior_val_list, xasl_node::proc, qdump_print_list_id(), qdump_print_outlist(), qdump_print_predicate(), qdump_print_regu_variable_list(), qdump_print_value_list(), connectby_proc_node::regu_list_pred, connectby_proc_node::regu_list_rest, connectby_proc_node::start_with_list_id, and connectby_proc_node::start_with_pred.
Referenced by qdump_print_xasl().
static bool qdump_print_db_value (DB_VALUE * value) static
Definition at line 1009 of file query_dump.c.
References db_value_print().
Referenced by qdump_print_access_spec(), qdump_print_build_list_node(), qdump_print_build_value_node(), qdump_print_db_value_array(), qdump_print_value(), qdump_print_value_list(), and qdump_print_xasl().
static bool qdump_print_db_value_array (DB_VALUE ** array, int cnt) static
Definition at line 188 of file query_dump.c.
References cubregex::count(), foutput, i, NULL, and qdump_print_db_value().
Referenced by qdump_print_build_list_node().
static bool qdump_print_delete_proc_node (DELETE_PROC_NODE * ptr) static
Definition at line 356 of file query_dump.c.
References upddel_class_info::class_hfid, upddel_class_info::class_oid, delete_proc_node::classes, foutput, i, delete_proc_node::num_classes, upddel_class_info::num_subclasses, qdump_print_hfid(), and qdump_print_oid().
Referenced by qdump_print_xasl().
static bool qdump_print_domain_list (int cnt, TP_DOMAIN ** ptr) static
Definition at line 837 of file query_dump.c.
References foutput, i, NULL, qdump_data_type_string(), and TP_DOMAIN_TYPE.
Referenced by qdump_print_type_list().
static bool qdump_print_eval_term (PRED_EXPR * pred_p) static
Definition at line 1471 of file query_dump.c.
References cubxasl::eval_term::et_type, cubxasl::pred_expr::m_eval_term, cubxasl::pred_expr::pe, qdump_print_alsm_eval_term(), qdump_print_comp_eval_term(), qdump_print_like_eval_term(), qdump_print_rlike_eval_term(), T_ALSM_EVAL_TERM, T_COMP_EVAL_TERM, T_LIKE_EVAL_TERM, and T_RLIKE_EVAL_TERM.
Referenced by qdump_print_term().
static bool qdump_print_fetch_node (XASL_NODE * xasl_p) static
Definition at line 2044 of file query_dump.c.
References fetch_proc_node::arg, DB_VALUE_DOMAIN_TYPE, xasl_node::fetch, fetch_proc_node::fetch_res, foutput, xasl_node::proc, qdump_data_type_string(), qdump_print_predicate(), fetch_proc_node::ql_flag, and fetch_proc_node::set_pred.
Referenced by qdump_print_xasl().
static bool qdump_print_function_value (REGU_VARIABLE * regu) static
Definition at line 1288 of file query_dump.c.
References fcode_get_uppercase_name(), foutput, NULL, qdump_print_regu_variable_list(), REGU_VARIABLE_HIDDEN_COLUMN, and REGU_VARIABLE_IS_FLAGED().
Referenced by qdump_print_value().
static bool qdump_print_hfid (HFID id) static
Definition at line 699 of file query_dump.c.
References foutput, and qdump_print_vfid().
Referenced by qdump_print_class(), qdump_print_delete_proc_node(), qdump_print_insert_proc_node(), and qdump_print_update_proc_node().
static bool qdump_print_index (INDX_INFO * indexptr) static
Definition at line 636 of file query_dump.c.
References indx_info::btid, foutput, indx_info::key_info, NULL, qdump_print_btid(), qdump_print_key_info(), qdump_range_type_string(), and indx_info::range_type.
Referenced by qdump_print_access_spec().
static bool qdump_print_insert_proc_node (INSERT_PROC_NODE * ptr) static
Definition at line 392 of file query_dump.c.
References insert_proc_node::att_id, insert_proc_node::class_hfid, insert_proc_node::class_oid, foutput, insert_proc_node::num_vals, db_identifier::pageid, qdump_print_attribute(), qdump_print_hfid(), db_identifier::slotid, and db_identifier::volid.
Referenced by qdump_print_xasl().
static bool qdump_print_key_info (KEY_INFO * key_info) static
Definition at line 575 of file query_dump.c.
References foutput, i, key_info::is_constant, key_info::is_user_given_keylimit, key_range::key1, key_range::key2, key_info::key_cnt, key_info::key_limit_l, key_info::key_limit_reset, key_info::key_limit_u, key_info::key_ranges, qdump_key_range_string(), qdump_print_value(), and key_range::range.
Referenced by qdump_print_index().
static bool qdump_print_lhs_predicate (PRED_EXPR * pred_p) static
Definition at line 1558 of file query_dump.c.
References cubxasl::pred::bool_op, foutput, cubxasl::pred::lhs, cubxasl::pred_expr::m_pred, cubxasl::pred_expr::pe, qdump_bool_operator_string(), and qdump_print_predicate().
Referenced by qdump_print_predicate().
static bool qdump_print_like_eval_term (EVAL_TERM * term_p) static
Definition at line 1428 of file query_dump.c.
References cubxasl::like_eval_term::esc_char, cubxasl::eval_term::et, cubxasl::eval_term::et_like, foutput, cubxasl::like_eval_term::pattern, qdump_print_value(), and cubxasl::like_eval_term::src.
Referenced by qdump_print_eval_term().
static bool qdump_print_list (LIST_SPEC_TYPE * ptr) static
Definition at line 725 of file query_dump.c.
References foutput, list_spec_node::list_regu_list_build, list_spec_node::list_regu_list_pred, list_spec_node::list_regu_list_probe, list_spec_node::list_regu_list_rest, qdump_print_regu_variable_list(), and list_spec_node::xasl_node.
Referenced by qdump_print_access_spec().
static bool qdump_print_list_id (QFILE_LIST_ID * idptr) static
Definition at line 795 of file query_dump.c.
References foutput, NULL, qdump_print_type_list(), qfile_list_id::tuple_cnt, and qfile_list_id::type_list.
Referenced by qdump_print_aggregate_expression(), qdump_print_connect_by_proc_node(), qdump_print_value(), and qdump_print_xasl().
static bool qdump_print_list_merge_info (QFILE_LIST_MERGE_INFO * ptr) static
Definition at line 231 of file query_dump.c.
References foutput, qfile_list_merge_info::join_type, qfile_list_merge_info::ls_column_cnt, qfile_list_merge_info::ls_inner_column, qfile_list_merge_info::ls_inner_unique, qfile_list_merge_info::ls_outer_column, qfile_list_merge_info::ls_outer_inner_list, qfile_list_merge_info::ls_outer_unique, qfile_list_merge_info::ls_pos_cnt, qfile_list_merge_info::ls_pos_list, NULL, qdump_print_column(), and qfile_list_merge_info::single_fetch.
Referenced by qdump_print_merge_list_proc_node().
static bool qdump_print_merge_list_proc_node (MERGELIST_PROC_NODE * ptr) static
Definition at line 260 of file query_dump.c.
References foutput, mergelist_proc_node::inner_spec_list, mergelist_proc_node::inner_val_list, mergelist_proc_node::inner_xasl, mergelist_proc_node::ls_merge, mergelist_proc_node::outer_spec_list, mergelist_proc_node::outer_val_list, mergelist_proc_node::outer_xasl, qdump_print_access_spec(), qdump_print_list_merge_info(), and qdump_print_value_list().
Referenced by qdump_print_xasl().
static bool qdump_print_oid (OID * oidptr) static
Definition at line 1376 of file query_dump.c.
References foutput, db_identifier::pageid, db_identifier::slotid, and db_identifier::volid.
Referenced by qdump_print_delete_proc_node(), qdump_print_update_proc_node(), and qdump_print_xasl().
static bool qdump_print_outlist (const char * title, OUTPTR_LIST * outlist) static
Definition at line 761 of file query_dump.c.
References foutput, regu_variable_list_node::next, NULL, qdump_print_value(), valptr_list_node::valptrp, and regu_variable_list_node::value.
Referenced by qdump_print_build_list_node(), qdump_print_connect_by_proc_node(), and qdump_print_xasl().
static bool qdump_print_predicate (PRED_EXPR * predptr) static
Definition at line 1578 of file query_dump.c.
References foutput, cubxasl::pred_expr::m_pred, NULL, cubxasl::pred_expr::pe, qdump_print_lhs_predicate(), qdump_print_term(), cubxasl::pred::rhs, T_EVAL_TERM, T_NOT_TERM, T_PRED, and cubxasl::pred_expr::type.
Referenced by qdump_print_access_spec(), qdump_print_build_list_node(), qdump_print_build_value_node(), qdump_print_connect_by_proc_node(), qdump_print_fetch_node(), qdump_print_lhs_predicate(), qdump_print_term(), and qdump_print_xasl().
static bool qdump_print_regu_type (REGU_VARIABLE * value) static
Definition at line 1076 of file query_dump.c.
References DB_VALUE_DOMAIN_TYPE, foutput, qdump_data_type_string(), qdump_regu_type_string(), and TYPE_DBVAL.
Referenced by qdump_print_value_type_addr().
static bool qdump_print_regu_variable_list (REGU_VARIABLE_LIST varlist) static
Definition at line 963 of file query_dump.c.
References foutput, regu_variable_list_node::next, NULL, qdump_print_value(), and regu_variable_list_node::value.
Referenced by qdump_print_build_list_node(), qdump_print_class(), qdump_print_connect_by_proc_node(), qdump_print_function_value(), qdump_print_list(), and qdump_print_showstmt().
static bool qdump_print_rlike_eval_term (EVAL_TERM * term_p) static
Definition at line 1453 of file query_dump.c.
References cubxasl::rlike_eval_term::case_sensitive, db_value::data, regu_variable_node::regu_data_value::dbval, cubxasl::eval_term::et, cubxasl::eval_term::et_rlike, foutput, db_data::i, cubxasl::rlike_eval_term::pattern, qdump_print_value(), cubxasl::rlike_eval_term::src, and regu_variable_node::value.
Referenced by qdump_print_eval_term().
static bool qdump_print_showstmt (SHOWSTMT_SPEC_TYPE * ptr) static
Definition at line 746 of file query_dump.c.
References showstmt_spec_node::arg_list, foutput, qdump_print_regu_variable_list(), and showstmt_spec_node::show_type.
Referenced by qdump_print_access_spec().
static bool qdump_print_sort_list (SORT_LIST * sorting_list) static
Definition at line 860 of file query_dump.c.
References foutput, sort_list::next, NULL, sort_list::pos_descr, qdump_print_tuple_value_position(), S_ASC, and sort_list::s_order.
Referenced by qdump_print_build_list_node(), and qdump_print_xasl().
static bool qdump_print_term (PRED_EXPR * pred_ptr) static
Definition at line 1500 of file query_dump.c.
References foutput, cubxasl::pred_expr::m_not_term, NULL, cubxasl::pred_expr::pe, qdump_print_eval_term(), qdump_print_predicate(), T_EVAL_TERM, T_NOT_TERM, and cubxasl::pred_expr::type.
Referenced by qdump_print_predicate().
static bool qdump_print_tuple_value_position (QFILE_TUPLE_VALUE_POSITION pos) static
Definition at line 911 of file query_dump.c.
References qfile_tuple_value_position::dom, foutput, qfile_tuple_value_position::pos_no, qdump_data_type_string(), and TP_DOMAIN_TYPE.
Referenced by qdump_print_sort_list(), and qdump_print_value().
static bool qdump_print_type_list (QFILE_TUPLE_VALUE_TYPE_LIST * typeptr) static
Definition at line 820 of file query_dump.c.
References qfile_tuple_value_type_list::domp, foutput, qdump_print_domain_list(), and qfile_tuple_value_type_list::type_cnt.
Referenced by qdump_print_list_id().
static bool qdump_print_update_proc_node (UPDATE_PROC_NODE * ptr) static
Definition at line 321 of file query_dump.c.
References upddel_class_info::att_id, upddel_class_info::class_hfid, upddel_class_info::class_oid, update_proc_node::classes, foutput, i, NULL, upddel_class_info::num_attrs, update_proc_node::num_classes, update_proc_node::num_orderby_keys, upddel_class_info::num_subclasses, qdump_print_attribute(), qdump_print_hfid(), and qdump_print_oid().
Referenced by qdump_print_xasl().
static bool qdump_print_value (REGU_VARIABLE * value) static
Definition at line 1195 of file query_dump.c.
References ARITH_EXP, foutput, NULL, qdump_data_type_string(), qdump_print_arith(), qdump_print_attribute_id(), qdump_print_db_value(), qdump_print_function_value(), qdump_print_list_id(), qdump_print_tuple_value_position(), qdump_print_value_type_addr(), REGU_VARIABLE_HIDDEN_COLUMN, REGU_VARIABLE_IS_FLAGED(), TYPE_ATTR_ID, TYPE_CONSTANT, TYPE_DBVAL, TYPE_FUNC, TYPE_INARITH, TYPE_LIST_ID, TYPE_OID, TYPE_ORDERBY_NUM, TYPE_OUTARITH, TYPE_POS_VALUE, and TYPE_POSITION.
Referenced by qdump_print_access_spec(), qdump_print_aggregate_expression(), qdump_print_alsm_eval_term(), qdump_print_arith_expression(), qdump_print_comp_eval_term(), qdump_print_key_info(), qdump_print_like_eval_term(), qdump_print_outlist(), qdump_print_regu_variable_list(), qdump_print_rlike_eval_term(), and qdump_print_xasl().
static bool qdump_print_value_list (VAL_LIST * vallist) static
Definition at line 926 of file query_dump.c.
References DB_VALUE_DOMAIN_TYPE, foutput, qproc_db_value_list::next, NULL, qdump_data_type_string(), qdump_print_db_value(), qproc_db_value_list::val, val_list_node::val_cnt, and val_list_node::valp.
Referenced by qdump_print_build_list_node(), qdump_print_connect_by_proc_node(), qdump_print_merge_list_proc_node(), and qdump_print_xasl().
static bool qdump_print_value_type_addr (REGU_VARIABLE * value) static
Definition at line 1315 of file query_dump.c.
References foutput, qdump_print_regu_type(), TYPE_ATTR_ID, TYPE_CLASS_ATTR_ID, TYPE_CLASSOID, TYPE_CONSTANT, TYPE_DBVAL, TYPE_FUNC, TYPE_INARITH, TYPE_LIST_ID, TYPE_OID, TYPE_ORDERBY_NUM, TYPE_OUTARITH, TYPE_POS_VALUE, TYPE_POSITION, and TYPE_SHARED_ATTR_ID.
Referenced by qdump_print_value().
static bool qdump_print_vfid (VFID id) static
Definition at line 713 of file query_dump.c.
References foutput.
Referenced by qdump_print_hfid().
bool qdump_print_xasl (xasl_node * xasl_p)
Definition at line 2294 of file query_dump.c.
References access_spec_node::access, ACCESS_METHOD_INDEX, ACCESS_METHOD_SEQUENTIAL, ACCESS_SPEC_CLS_SPEC, xasl_node::after_join_pred, xasl_node::aptr_list, assert, xasl_node::bptr_list, indx_info::btid, BUILD_SCHEMA_PROC, xasl_node::buildlist, BUILDLIST_PROC, BUILDVALUE_PROC, xasl_node::cat_fetched, xasl_node::class_locks, xasl_node::class_oid_list, cls_spec_node::cls_oid, xasl_node::connect_by_ptr, CONNECTBY_PROC, xasl_node::creator_oid, xasl_node::cte, CTE_PROC, xasl_node::curr_spec, DB_VALUE_DOMAIN_TYPE, xasl_node::dbval_cnt, xasl_node::delete_, DELETE_PROC, DIFFERENCE_PROC, DO_PROC, xasl_node::dptr_list, buildlist_proc_node::eptr_list, er_clear(), xasl_node::flag, foutput, xasl_node::fptr_list, free_and_init, HAVE_SUBQUERY_PROC, heap_get_class_name(), heap_get_indexinfo_of_btid(), HS_ACCEPT_ALL, HS_REJECT_ALL, i, xasl_node::if_pred, access_spec_node::indexptr, mergelist_proc_node::inner_xasl, xasl_node::insert, INSERT_PROC, merge_proc_node::insert_xasl, xasl_node::instnum_flag, xasl_node::instnum_pred, xasl_node::instnum_val, INTERSECTION_PROC, xasl_node::is_single_tuple, xasl_node::iscycle_regu, xasl_node::iscycle_val, xasl_node::isleaf_regu, xasl_node::isleaf_val, union_proc_node::left, xasl_node::level_regu, xasl_node::level_val, xasl_node::list_id, LOCK_TO_LOCKMODE_STRING, xasl_node::merge, MERGE_PROC, xasl_node::merge_spec, xasl_node::mergelist, MERGELIST_PROC, xasl_node::n_oid_list, qproc_db_value_list::next, access_spec_node::next, xasl_node::next, xasl_node::next_scan_block_on, xasl_node::next_scan_on, NO_ERROR, cte_proc_node::non_recursive_part, NULL, OBJFETCH_PROC, xasl_node::option, xasl_node::ordbynum_flag, xasl_node::ordbynum_pred, xasl_node::ordbynum_val, xasl_node::orderby_limit, xasl_node::orderby_list, mergelist_proc_node::outer_xasl, xasl_node::outptr_list, prm_get_bool_value(), PRM_ID_USE_ORDERBY_SORT_LIMIT, xasl_node::proc, Q_DISTINCT, qdump_data_type_string(), qdump_print_access_spec(), qdump_print_build_list_node(), qdump_print_build_value_node(), qdump_print_connect_by_proc_node(), qdump_print_db_value(), qdump_print_delete_proc_node(), qdump_print_fetch_node(), qdump_print_insert_proc_node(), qdump_print_list_id(), qdump_print_merge_list_proc_node(), qdump_print_oid(), qdump_print_outlist(), qdump_print_predicate(), qdump_print_sort_list(), qdump_print_update_proc_node(), qdump_print_value(), qdump_print_value_list(), qdump_print_xasl(), qdump_print_xasl_type(), xasl_node::query_alias, cte_proc_node::recursive_part, union_proc_node::right, xasl_node::save_instnum_val, SCAN_PROC, xasl_node::scan_ptr, xasl_node::single_tuple, xasl_node::spec_list, TARGET_CLASS, TARGET_CLASS_ATTR, TARGET_LIST, TARGET_METHOD, TARGET_SET, TARGET_SHOWSTMT, xasl_node::tcard_list, thread_get_thread_entry_info(), TO_MSEC, access_spec_node::type, xasl_node::type, xasl_node::union_, UNION_PROC, xasl_node::update, UPDATE_PROC, merge_proc_node::update_xasl, qproc_db_value_list::val, xasl_node::val_list, val_list_node::valp, XASL_CLEAR_FLAG, XASL_INSTNUM_FLAG_SCAN_CONTINUE, XASL_IS_FLAGED, XASL_LINK_TO_REGU_VARIABLE, XASL_ORDBYNUM_FLAG_SCAN_CONTINUE, XASL_SKIP_ORDERBY_LIST, XASL_TOP_MOST_XASL, and XASL_ZERO_CORR_LEVEL.
Referenced by parser_generate_do_stmt_xasl(), parser_generate_xasl(), qdump_print_xasl(), and qexec_execute_query().
static bool qdump_print_xasl_type (XASL_NODE * xasl) static
Definition at line 125 of file query_dump.c.
References BUILDLIST_PROC, BUILDVALUE_PROC, CONNECTBY_PROC, CTE_PROC, DELETE_PROC, DIFFERENCE_PROC, foutput, INSERT_PROC, INTERSECTION_PROC, MERGE_PROC, MERGELIST_PROC, OBJFETCH_PROC, SCAN_PROC, xasl_node::type, UNION_PROC, and UPDATE_PROC.
Referenced by qdump_print_xasl().
static const char * qdump_range_type_string (RANGE_TYPE range_type) static
Definition at line 613 of file query_dump.c.
References R_KEY, R_KEYLIST, R_RANGE, and R_RANGELIST.
Referenced by qdump_print_index().
static const char * qdump_regu_type_string (REGU_DATATYPE type) static
Definition at line 1029 of file query_dump.c.
References TYPE_ATTR_ID, TYPE_CLASS_ATTR_ID, TYPE_CLASSOID, TYPE_CONSTANT, TYPE_DBVAL, TYPE_FUNC, TYPE_INARITH, TYPE_LIST_ID, TYPE_OID, TYPE_ORDERBY_NUM, TYPE_OUTARITH, TYPE_POS_VALUE, TYPE_POSITION, TYPE_REGU_VAR_LIST, TYPE_REGUVAL_LIST, and TYPE_SHARED_ATTR_ID.
Referenced by qdump_print_regu_type().
static const char * qdump_relation_operator_string (int op) static
Definition at line 1645 of file query_dump.c.
References R_EQ, R_EXISTS, R_GE, R_GT, R_LE, R_LT, R_NE, R_NULL, and R_NULLSAFE_EQ.
Referenced by qdump_print_alsm_eval_term(), and qdump_print_comp_eval_term().
static const char * qdump_target_type_string (TARGET_TYPE type) static
Definition at line 408 of file query_dump.c.
References TARGET_CLASS, TARGET_CLASS_ATTR, TARGET_LIST, TARGET_METHOD, TARGET_SET, and TARGET_SHOWSTMT.
Referenced by qdump_print_access_spec().