CUBRID Engine: src/object/quick_fit.h File Reference
quick_fit.h File Reference
Macros
#define db_ws_free_and_init(obj)
Functions
HL_HEAPID db_create_workspace_heap (void)
void db_destroy_workspace_heap (void)
void db_ws_free (void *obj)
void * db_ws_alloc (size_t bytes)
void * db_ws_realloc (void *obj, size_t newsize)
Macro Definition Documentation
#define db_ws_free_and_init (obj)
Value:
do \
    { \
      db_ws_free ((obj)); \
      (obj) = NULL; \
    } \
  while (0)
Definition at line 30 of file quick_fit.h.
Referenced by allocate_disk_structures(), and classobj_free_class().
Function Documentation
HL_HEAPID db_create_workspace_heap (void)
Definition at line 43 of file quick_fit.c.
References hl_register_lea_heap(), and ws_Heap_id.
Referenced by db_ws_alloc(), db_ws_realloc(), and ws_init().
void db_destroy_workspace_heap (void)
Definition at line 58 of file quick_fit.c.
References hl_unregister_lea_heap(), and ws_Heap_id.
Referenced by ws_final(), and ws_init().
void* db_ws_alloc (size_t bytes)
Definition at line 73 of file quick_fit.c.
References db_create_workspace_heap(), hl_lea_alloc(), NULL, and ws_Heap_id.
Referenced by allocate_disk_structures(), classobj_alloc_threaded_array(), classobj_cache_not_null_constraints(), classobj_copy_attribute(), classobj_copy_method(), classobj_make_attribute(), classobj_make_class(), classobj_make_class_constraint(), classobj_make_class_constraints(), classobj_make_constraint(), classobj_make_foreign_key_info(), classobj_make_foreign_key_ref(), classobj_make_function_index_info(), classobj_make_index_filter_pred_info(), classobj_make_index_prefix_info(), classobj_make_method(), classobj_make_method_arg(), classobj_make_method_file(), classobj_make_method_signature(), classobj_make_partition_info(), classobj_make_query_spec(), classobj_make_repattribute(), classobj_make_representation(), classobj_make_resolution(), collect_class_grants(), db_private_alloc_debug(), db_ws_realloc(), do_alter_index_rebuild(), get_current(), get_old(), insert_trigger_list(), lock_subclasses_internal(), make_candidate_from_component(), merge_trigger_list(), ml_add(), ml_append(), ml_copy(), nlist_add(), nlist_append(), nlist_copy(), obj_alloc(), pt_find_value_of_label(), pt_node_to_function_index(), sm_build_function_nlist(), sm_dynamic_link_class(), sm_get_class_repid(), sm_link_static_method(), sm_prelink_methods(), sm_split_loader_commands(), stats_client_unpack_statistics(), tr_make_schema_cache(), tran_add_savepoint(), ws_add_label_value_to_mop(), and ws_copy_string().
void db_ws_free (void * obj)
Definition at line 194 of file quick_fit.c.
References assert, db_private_free, hl_lea_free(), NULL, and ws_Heap_id.
Referenced by add_resolution(), classobj_cache_not_null_constraints(), classobj_copy_attribute(), classobj_copy_method(), classobj_free_attribute(), classobj_free_class_constraints(), classobj_free_constraint(), classobj_free_foreign_key_ref(), classobj_free_method(), classobj_free_method_arg(), classobj_free_method_file(), classobj_free_method_signature(), classobj_free_partition_info(), classobj_free_query_spec(), classobj_free_repattribute(), classobj_free_representation(), classobj_free_resolution(), classobj_free_template(), classobj_free_threaded_array(), classobj_make_attribute(), classobj_make_class(), classobj_make_foreign_key_info(), classobj_make_foreign_key_ref(), classobj_make_function_index_info(), classobj_make_index_filter_pred_info(), classobj_make_index_prefix_info(), classobj_make_method(), classobj_make_method_file(), classobj_make_method_signature(), classobj_make_query_spec(), create_or_drop_index_helper(), csql_print_database(), db_private_free_debug(), db_string_free(), disk_to_class(), do_alter_index_rebuild(), do_recreate_func_index_constr(), flatten_components(), free_candidates(), free_grant_list(), get_current(), get_old(), ml_free(), ml_remove(), nlist_add(), nlist_append(), nlist_copy(), nlist_free(), obj_free_memory(), pt_find_value_of_label(), pt_node_to_function_index(), pt_node_to_partition_info(), sm_build_function_nlist(), sm_dynamic_link_class(), sm_free_function_nlist(), sm_free_loader_commands(), sm_free_method_links(), sm_prelink_methods(), sm_split_loader_commands(), smt_add_query_spec(), stats_client_unpack_statistics(), stats_free_statistics(), tr_free_schema_cache(), tr_free_trigger_list(), tran_add_savepoint(), tran_free_list_upto_savepoint(), vid_build_non_upd_object(), ws_clean_label_value_list(), ws_free_string(), and ws_remove_label_value_from_mop().
void* db_ws_realloc (void * obj, size_t newsize)
Definition at line 123 of file quick_fit.c.
References db_create_workspace_heap(), db_private_realloc, db_ws_alloc(), hl_lea_realloc(), NULL, and ws_Heap_id.
Referenced by db_private_realloc_debug().