CUBRID Engine: src/transaction/recovery.c File Reference
recovery.c File Reference
#include "config.h"
#include <stdio.h>
#include "recovery.h"
#include "log_manager.h"
#include "replication.h"
#include "btree.h"
#include "btree_load.h"
#include "system_catalog.h"
#include "disk_manager.h"
#include "extendible_hash.h"
#include "file_manager.h"
#include "overflow_file.h"
#include "boot_sr.h"
#include "locator_sr.h"
Functions
const char * rv_rcvindex_string (LOG_RCVINDEX rcvindex)
void rv_check_rvfuns (void)
Variables
struct rvfun RV_fun []
Function Documentation
void rv_check_rvfuns (void)
Definition at line 861 of file recovery.c.
References ARG_FILE_LINE, assert, ER_FATAL_ERROR_SEVERITY, ER_GENERIC_ERROR, er_log_debug, er_set(), i, and rvfun::recv_index.
Referenced by log_initialize_internal().
const char* rv_rcvindex_string (LOG_RCVINDEX rcvindex)
Definition at line 846 of file recovery.c.
References rvfun::recv_string.
Referenced by log_dump_record_compensate(), log_dump_record_dbout_redo(), log_dump_record_mvcc_redo(), log_dump_record_mvcc_undo(), log_dump_record_mvcc_undoredo(), log_dump_record_postpone(), log_dump_record_redo(), log_dump_record_sysop_end_internal(), log_dump_record_undo(), log_dump_record_undoredo(), log_recovery_needs_skip_logical_redo(), log_recovery_redo(), log_recovery_undo(), log_rollback_record(), log_rv_undo_record(), log_undo_rec_restartable(), and prior_set_tde_encrypted().
Variable Documentation
struct rvfun RV_fun[]
Definition at line 49 of file recovery.c.
Referenced by log_append_dboutside_redo(), log_append_postpone(), log_append_redo_crumbs(), log_append_undo_crumbs(), log_append_undoredo_crumbs(), log_dump_record_compensate(), log_dump_record_dbout_redo(), log_dump_record_mvcc_redo(), log_dump_record_mvcc_undo(), log_dump_record_mvcc_undoredo(), log_dump_record_postpone(), log_dump_record_redo(), log_dump_record_sysop_end_internal(), log_dump_record_undo(), log_dump_record_undoredo(), log_execute_run_postpone(), log_recovery_redo(), log_rollback_record(), log_rv_undo_record(), and log_undo_rec_restartable().