CUBRID Engine: src/query/regu_var.hpp File Reference
regu_var.hpp File Reference
#include "heap_attrinfo.h"
#include "object_domain.h"
#include "query_list.h"
#include "string_opfunc.h"
#include "object_primitive.h"
#include <functional>
Classes
struct attr_descr_node
struct regu_value_item
struct regu_value_list
struct valptr_list_node
struct arith_list_node
struct function_node
union function_tmp_obj
class regu_variable_node
union regu_variable_node::regu_data_value
struct regu_variable_list_node
struct regu_varlist_list_node
struct regu_ptr_list_node
Namespaces
cubxasl
Typedefs
typedef class regu_variable_node REGU_VARIABLE
typedef struct regu_variable_list_node * REGU_VARIABLE_LIST
typedef int CL_ATTR_ID
typedef struct attr_descr_node ATTR_DESCR
typedef struct regu_value_item REGU_VALUE_ITEM
typedef struct regu_value_list REGU_VALUE_LIST
typedef struct valptr_list_node VALPTR_LIST
typedef struct valptr_list_node OUTPTR_LIST
typedef struct arith_list_node ARITH_TYPE
typedef struct function_node FUNCTION_TYPE
typedef struct regu_varlist_list_node * REGU_VARLIST_LIST
typedef struct regu_ptr_list_node * REGU_PTR_LIST
Enumerations
enum REGU_DATATYPE {
TYPE_DBVAL, TYPE_CONSTANT, TYPE_ORDERBY_NUM, TYPE_INARITH,
TYPE_OUTARITH, TYPE_ATTR_ID, TYPE_CLASS_ATTR_ID, TYPE_SHARED_ATTR_ID,
TYPE_POSITION, TYPE_LIST_ID, TYPE_POS_VALUE, TYPE_OID,
TYPE_CLASSOID, TYPE_FUNC, TYPE_REGUVAL_LIST, TYPE_REGU_VAR_LIST
}
Functions
bool REGU_VARIABLE_IS_FLAGED (const regu_variable_node *regu, int flag)
void REGU_VARIABLE_SET_FLAG (regu_variable_node *regu, int flag)
void REGU_VARIABLE_CLEAR_FLAG (regu_variable_node *regu, int flag)
DB_TYPE REGU_VARIABLE_GET_TYPE (const regu_variable_node *regu)
Variables
const int REGU_VARIABLE_HIDDEN_COLUMN = 0x01
const int REGU_VARIABLE_FIELD_COMPARE = 0x02
const int REGU_VARIABLE_FIELD_NESTED = 0x04
const int REGU_VARIABLE_APPLY_COLLATION = 0x08
const int REGU_VARIABLE_ANALYTIC_WINDOW = 0x10
const int REGU_VARIABLE_INFER_COLLATION = 0x20
const int REGU_VARIABLE_FETCH_ALL_CONST = 0x40
const int REGU_VARIABLE_FETCH_NOT_CONST = 0x80
const int REGU_VARIABLE_CLEAR_AT_CLONE_DECACHE = 0x100
const int REGU_VARIABLE_UPD_INS_LIST = 0x200
const int REGU_VARIABLE_STRICT_TYPE_CAST = 0x400
Typedef Documentation
typedef struct arith_list_node ARITH_TYPE
Definition at line 122 of file regu_var.hpp.
typedef struct attr_descr_node ATTR_DESCR
Definition at line 73 of file regu_var.hpp.
typedef int CL_ATTR_ID
Definition at line 71 of file regu_var.hpp.
typedef struct function_node FUNCTION_TYPE
Definition at line 139 of file regu_var.hpp.
typedef struct valptr_list_node OUTPTR_LIST
Definition at line 113 of file regu_var.hpp.
typedef struct regu_ptr_list_node* REGU_PTR_LIST
Definition at line 234 of file regu_var.hpp.
typedef struct regu_value_item REGU_VALUE_ITEM
Definition at line 93 of file regu_var.hpp.
typedef struct regu_value_list REGU_VALUE_LIST
Definition at line 102 of file regu_var.hpp.
typedef class regu_variable_node REGU_VARIABLE
Definition at line 64 of file regu_var.hpp.
typedef struct regu_variable_list_node* REGU_VARIABLE_LIST
Definition at line 65 of file regu_var.hpp.
typedef struct regu_varlist_list_node* REGU_VARLIST_LIST
Definition at line 225 of file regu_var.hpp.
typedef struct valptr_list_node VALPTR_LIST
Definition at line 112 of file regu_var.hpp.
Enumeration Type Documentation
enum REGU_DATATYPE
Enumerator
TYPE_DBVAL
TYPE_CONSTANT
TYPE_ORDERBY_NUM
TYPE_INARITH
TYPE_OUTARITH
TYPE_ATTR_ID
TYPE_CLASS_ATTR_ID
TYPE_SHARED_ATTR_ID
TYPE_POSITION
TYPE_LIST_ID
TYPE_POS_VALUE
TYPE_OID
TYPE_CLASSOID
TYPE_FUNC
TYPE_REGUVAL_LIST
TYPE_REGU_VAR_LIST
Definition at line 42 of file regu_var.hpp.
Function Documentation
void REGU_VARIABLE_CLEAR_FLAG (regu_variable_node * regu, int flag) inline
Definition at line 265 of file regu_var.hpp.
References regu_variable_node::flags.
Referenced by qexec_clear_regu_var().
DB_TYPE REGU_VARIABLE_GET_TYPE (const regu_variable_node * regu) inline
Definition at line 271 of file regu_var.hpp.
References DB_TYPE_UNKNOWN, regu_variable_node::domain, and TP_DOMAIN_TYPE.
Referenced by check_hash_list_scan(), qdata_copy_hscan_key(), and qdata_copy_hscan_key_without_alloc().
bool REGU_VARIABLE_IS_FLAGED (const regu_variable_node * regu, int flag) inline
Definition at line 253 of file regu_var.hpp.
References regu_variable_node::flags.
Referenced by eval_value_rel_cmp(), fetch_peek_arith(), fetch_peek_dbval(), qdata_calculate_aggregate_cume_dist_percent_rank(), qdata_copy_valptr_list_to_tuple(), qdata_generate_tuple_desc_for_valptr_list(), qdata_get_dbval_from_constant_regu_variable(), qdata_get_valptr_type_list(), qdata_set_valptr_list_unbound(), qdump_print_function_value(), qdump_print_value(), qexec_clear_regu_var(), qexec_execute_build_columns(), qexec_execute_build_indexes(), qexec_resolve_domains_for_aggregation(), qexec_setup_topn_proc(), qexec_topn_tuples_to_list_id(), qfile_update_domains_on_type_list(), query_multi_range_opt_check_set_sort_col(), stx_build_regu_variable(), and xts_process_regu_variable().
void REGU_VARIABLE_SET_FLAG (regu_variable_node * regu, int flag) inline
Definition at line 259 of file regu_var.hpp.
References regu_variable_node::flags.
Referenced by fetch_force_not_const_recursive(), fetch_peek_arith(), fetch_peek_dbval(), pt_make_function(), pt_to_buildlist_proc(), pt_to_cume_dist_percent_rank_regu_variable(), pt_to_regu_variable(), qdata_get_dbval_from_constant_regu_variable(), and stx_unpack_regu_variable_value().
Variable Documentation
const int REGU_VARIABLE_ANALYTIC_WINDOW = 0x10
Definition at line 161 of file regu_var.hpp.
Referenced by pt_to_buildlist_proc(), and qdata_get_dbval_from_constant_regu_variable().
const int REGU_VARIABLE_APPLY_COLLATION = 0x08
Definition at line 159 of file regu_var.hpp.
Referenced by fetch_peek_arith(), fetch_peek_dbval(), and pt_to_regu_variable().
const int REGU_VARIABLE_CLEAR_AT_CLONE_DECACHE = 0x100
Definition at line 165 of file regu_var.hpp.
Referenced by qdata_calculate_aggregate_cume_dist_percent_rank(), qdata_copy_valptr_list_to_tuple(), qdata_generate_tuple_desc_for_valptr_list(), qdata_get_dbval_from_constant_regu_variable(), qdata_set_valptr_list_unbound(), qexec_clear_regu_var(), qexec_execute_build_columns(), qexec_execute_build_indexes(), qexec_resolve_domains_for_aggregation(), and stx_unpack_regu_variable_value().
const int REGU_VARIABLE_FETCH_ALL_CONST = 0x40
Definition at line 163 of file regu_var.hpp.
Referenced by eval_value_rel_cmp(), fetch_peek_arith(), fetch_peek_dbval(), qexec_clear_regu_var(), stx_build_regu_variable(), and xts_process_regu_variable().
const int REGU_VARIABLE_FETCH_NOT_CONST = 0x80
Definition at line 164 of file regu_var.hpp.
Referenced by eval_value_rel_cmp(), fetch_force_not_const_recursive(), fetch_peek_arith(), fetch_peek_dbval(), qexec_clear_regu_var(), stx_build_regu_variable(), and xts_process_regu_variable().
const int REGU_VARIABLE_FIELD_COMPARE = 0x02
Definition at line 157 of file regu_var.hpp.
Referenced by fetch_peek_arith(), and pt_to_regu_variable().
const int REGU_VARIABLE_FIELD_NESTED = 0x04
Definition at line 158 of file regu_var.hpp.
Referenced by fetch_peek_arith(), and pt_to_regu_variable().
const int REGU_VARIABLE_HIDDEN_COLUMN = 0x01
Definition at line 156 of file regu_var.hpp.
Referenced by pt_make_function(), pt_to_cume_dist_percent_rank_regu_variable(), pt_to_regu_variable(), qdata_copy_valptr_list_to_tuple(), qdata_generate_tuple_desc_for_valptr_list(), qdata_get_valptr_type_list(), qdump_print_function_value(), qdump_print_value(), qexec_setup_topn_proc(), qexec_topn_tuples_to_list_id(), qfile_update_domains_on_type_list(), and query_multi_range_opt_check_set_sort_col().
const int REGU_VARIABLE_INFER_COLLATION = 0x20
Definition at line 162 of file regu_var.hpp.
Referenced by fetch_peek_arith().
const int REGU_VARIABLE_STRICT_TYPE_CAST = 0x400
Definition at line 167 of file regu_var.hpp.
Referenced by fetch_peek_arith(), qdata_get_dbval_from_constant_regu_variable(), and qexec_execute_insert().
const int REGU_VARIABLE_UPD_INS_LIST = 0x200
Definition at line 166 of file regu_var.hpp.
Referenced by do_select_internal(), pt_make_aptr_parent_node(), and qdata_get_dbval_from_constant_regu_variable().