CUBRID Engine: src/base/release_string.c File Reference
release_string.c File Reference
#include <stdlib.h>
#include <string.h>
#include "config.h"
#include "porting.h"
#include "release_string.h"
#include "message_catalog.h"
#include "chartype.h"
#include "language_support.h"
#include "environment_variable.h"
#include "log_comm.h"
Classes
struct version
struct compatibility_rule
Macros
#define makestring1(x) #x
#define makestring(x) makestring1(x)
Typedefs
typedef struct version REL_VERSION
typedef struct compatibility_rule COMPATIBILITY_RULE
Enumerations
enum COMPATIBILITY_CHECK_MODE { CHECK_LOG_COMPATIBILITY, CHECK_NET_PROTOCOL_COMPATIBILITY }
Functions
static REL_COMPATIBILITY rel_get_compatible_internal (const char *base_rel_str, const char *apply_rel_str, COMPATIBILITY_CHECK_MODE check, REL_VERSION rules[])
void rel_copy_version_string (char *buf, size_t len)
const char * rel_name (void)
const char * rel_release_string (void)
const char * rel_major_release_string (void)
const char * rel_build_number (void)
const char * rel_build_os (void)
const char * rel_build_type (void)
float rel_disk_compatible (void)
void rel_set_disk_compatible (float level)
int rel_bit_platform (void)
REL_COMPATIBILITY rel_get_disk_compatible (float db_level, REL_FIXUP_FUNCTION **fixups)
int rel_compare (const char *rel_a, const char *rel_b)
bool rel_is_log_compatible (const char *writer_rel_str, const char *reader_rel_str)
REL_COMPATIBILITY rel_get_net_compatible (const char *client_rel_str, const char *server_rel_str)
Variables
static const char * copyright_header
static const char * copyright_body
static const char * release_string = makestring (RELEASE_STRING)
static const char * major_release_string = makestring (MAJOR_RELEASE_STRING)
static const char * build_number = makestring (BUILD_NUMBER)
static const char * package_string = PACKAGE_STRING
static const char * build_os = makestring (BUILD_OS)
static const char * build_type = makestring (BUILD_TYPE)
static int bit_platform = __WORDSIZE
static float disk_compatibility_level = 11.0f
static COMPATIBILITY_RULE disk_compatibility_rules []
static REL_VERSION log_incompatible_versions []
static REL_VERSION net_incompatible_versions []
Macro Definition Documentation
#define makestring (x) makestring1(x)
Definition at line 83 of file release_string.c.
Referenced by admin_getid_cmd(), main(), and uc_version().
#define makestring1 (x) #x
Definition at line 82 of file release_string.c.
Typedef Documentation
typedef struct compatibility_rule COMPATIBILITY_RULE
typedef struct version REL_VERSION
Enumeration Type Documentation
enum COMPATIBILITY_CHECK_MODE
Enumerator
CHECK_LOG_COMPATIBILITY
CHECK_NET_PROTOCOL_COMPATIBILITY
Definition at line 62 of file release_string.c.
Function Documentation
int rel_bit_platform (void)
Definition at line 257 of file release_string.c.
References bit_platform.
Referenced by boot_restart_server(), net_client_ping_server_with_handshake(), rel_copy_version_string(), server_ping_with_handshake(), and xboot_initialize_server().
const char* rel_build_number (void)
Definition at line 161 of file release_string.c.
References build_number.
Referenced by boot_restart_server(), db_get_database_version(), jsp_start_server(), proxy_io_make_get_db_version(), rel_copy_version_string(), ux_get_db_version(), and xboot_initialize_server().
const char* rel_build_os (void)
Definition at line 171 of file release_string.c.
References build_os.
Referenced by rel_copy_version_string().
const char* rel_build_type (void)
Definition at line 182 of file release_string.c.
References build_type, copyright_body, copyright_header, lang_init(), MSGCAT_CATALOG_CUBRID, MSGCAT_GENERAL_COPYRIGHT_BODY, MSGCAT_GENERAL_COPYRIGHT_HEADER, msgcat_message(), and MSGCAT_SET_GENERAL.
Referenced by boot_restart_server(), rel_copy_version_string(), and xboot_initialize_server().
int rel_compare (const char * rel_a, const char * rel_b)
Definition at line 347 of file release_string.c.
References char_isalpha(), and str_to_int32().
Referenced by net_client_ping_server_with_handshake(), and server_ping_with_handshake().
void rel_copy_version_string (char * buf, size_t len)
Definition at line 110 of file release_string.c.
References rel_bit_platform(), rel_build_number(), rel_build_os(), rel_build_type(), and rel_name().
Referenced by main(), and util_service_version().
float rel_disk_compatible (void)
Definition at line 234 of file release_string.c.
References disk_compatibility_level.
Referenced by boot_restart_client(), check_and_fix_compat_level(), fileio_start_backup(), logpb_delete(), logpb_initialize_header(), logpb_restore(), main(), and xboot_register_client().
static REL_COMPATIBILITY rel_get_compatible_internal (const char * base_rel_str, const char * apply_rel_str, COMPATIBILITY_CHECK_MODE check, REL_VERSION rules[]) static
Definition at line 515 of file release_string.c.
References CHECK_NET_PROTOCOL_COMPATIBILITY, version::major, version::minor, NULL, version::patch, REL_FULLY_COMPATIBLE, REL_NOT_COMPATIBLE, and str_to_int32().
Referenced by rel_get_net_compatible(), and rel_is_log_compatible().
REL_COMPATIBILITY rel_get_disk_compatible (float db_level, REL_FIXUP_FUNCTION ** fixups)
Definition at line 291 of file release_string.c.
References compatibility_rule::apply, compatibility_rule::base, compatibility_rule::compatibility, disk_compatibility_level, compatibility_rule::fix_function, version::major, version::minor, NULL, REL_FULLY_COMPATIBLE, and REL_NOT_COMPATIBLE.
Referenced by log_initialize_internal(), logpb_find_header_parameters(), and logpb_restore().
REL_COMPATIBILITY rel_get_net_compatible (const char * client_rel_str, const char * server_rel_str)
Definition at line 500 of file release_string.c.
References CHECK_NET_PROTOCOL_COMPATIBILITY, and rel_get_compatible_internal().
Referenced by net_client_ping_server_with_handshake(), and server_ping_with_handshake().
bool rel_is_log_compatible (const char * writer_rel_str, const char * reader_rel_str)
Definition at line 456 of file release_string.c.
References CHECK_LOG_COMPATIBILITY, rel_get_compatible_internal(), and REL_NOT_COMPATIBLE.
Referenced by fileio_continue_restore(), and log_initialize_internal().
const char* rel_major_release_string (void)
Definition at line 151 of file release_string.c.
References major_release_string.
Referenced by classobj_check_index_exist(), css_pack_server_name(), do_create_trigger(), hb_pack_server_name(), pt_check_alter(), pt_check_attribute_domain(), pt_check_create_entity(), sm_exist_index(), sm_rename_class(), smt_add_constraint(), and smt_rename_any().
const char* rel_name (void)
Definition at line 131 of file release_string.c.
References package_string.
Referenced by boot_initialize_client(), boot_restart_server(), er_stop_on_error(), fileio_continue_restore(), log_initialize_internal(), logpb_find_header_parameters(), logpb_restore(), rel_copy_version_string(), and xboot_initialize_server().
const char* rel_release_string (void)
Definition at line 141 of file release_string.c.
References release_string.
Referenced by css_process_shutdown_time_info(), fileio_continue_restore(), fileio_start_backup(), log_initialize_internal(), logpb_find_header_parameters(), logpb_initialize_header(), logpb_restore(), net_client_ping_server_with_handshake(), and server_ping_with_handshake().
void rel_set_disk_compatible (float level)
Definition at line 246 of file release_string.c.
References disk_compatibility_level.
Referenced by boot_restart_client().
Variable Documentation
int bit_platform = __WORDSIZE static
Definition at line 95 of file release_string.c.
Referenced by rel_bit_platform().
const char* build_number = makestring (BUILD_NUMBER) static
Definition at line 87 of file release_string.c.
Referenced by rel_build_number().
const char* build_os = makestring (BUILD_OS) static
Definition at line 89 of file release_string.c.
Referenced by rel_build_os().
const char* build_type = makestring (BUILD_TYPE) static
Definition at line 90 of file release_string.c.
Referenced by rel_build_type().
const char* copyright_body static
Initial value:
= "\
Copyright Information\n\
"
Definition at line 75 of file release_string.c.
Referenced by rel_build_type().
const char* copyright_header static
Initial value:
= "\
Copyright (C) 2008 Search Solution Corporation.\nCopyright (C) 2016 CUBRID Corporation.\n\
"
Definition at line 71 of file release_string.c.
Referenced by rel_build_type().
float disk_compatibility_level = 11.0f static
Definition at line 103 of file release_string.c.
Referenced by rel_disk_compatible(), rel_get_disk_compatible(), and rel_set_disk_compatible().
COMPATIBILITY_RULE disk_compatibility_rules[] static
Initial value:
= {
  {{0, 0, 0}, {0, 0, 0}, REL_NOT_COMPATIBLE, NULL}
}
Definition at line 270 of file release_string.c.
REL_VERSION log_incompatible_versions[] static
Initial value:
= {
  {10, 0, 0},
  {0, 0, 0}
}
Definition at line 439 of file release_string.c.
const char* major_release_string = makestring (MAJOR_RELEASE_STRING) static
Definition at line 86 of file release_string.c.
Referenced by rel_major_release_string().
REL_VERSION net_incompatible_versions[] static
Initial value:
= {
  {10, 0, 0},
  {0, 0, 0}
}
Definition at line 473 of file release_string.c.
const char* package_string = PACKAGE_STRING static
Definition at line 88 of file release_string.c.
Referenced by rel_name().
const char* release_string = makestring (RELEASE_STRING) static
Definition at line 85 of file release_string.c.
Referenced by rel_release_string().