CUBRID Engine: src/base/release_string.h File Reference
release_string.h File Reference
#include "config.h"
Macros
#define REL_MAX_RELEASE_LENGTH 15
#define REL_MAX_VERSION_LENGTH 256
Typedefs
typedef void(* REL_FIXUP_FUNCTION) (void)
Enumerations
enum REL_COMPATIBILITY { REL_NOT_COMPATIBLE, REL_FULLY_COMPATIBLE, REL_FORWARD_COMPATIBLE, REL_BACKWARD_COMPATIBLE }
Functions
const char * rel_name (void)
const char * rel_release_string (void)
const char * rel_major_release_string (void)
const char * rel_build_number (void)
const char * rel_build_os (void)
const char * rel_build_type (void)
float rel_disk_compatible (void)
void rel_set_disk_compatible (float level)
int rel_bit_platform (void)
int rel_compare (const char *rel_a, const char *rel_b)
REL_COMPATIBILITY rel_get_disk_compatible (float db_level, REL_FIXUP_FUNCTION **fixups)
bool rel_is_log_compatible (const char *writer_rel_str, const char *reader_rel_str)
REL_COMPATIBILITY rel_get_net_compatible (const char *client_rel_str, const char *server_rel_str)
void rel_copy_version_string (char *buf, size_t len)
Macro Definition Documentation
#define REL_MAX_RELEASE_LENGTH 15
Definition at line 31 of file release_string.h.
Referenced by log_initialize_internal(), logpb_initialize_header(), net_client_ping_server_with_handshake(), and server_ping_with_handshake().
#define REL_MAX_VERSION_LENGTH 256
Definition at line 32 of file release_string.h.
Referenced by main(), and util_service_version().
Typedef Documentation
typedef void(* REL_FIXUP_FUNCTION) (void)
Definition at line 40 of file release_string.h.
Enumeration Type Documentation
enum REL_COMPATIBILITY
Enumerator
REL_NOT_COMPATIBLE
REL_FULLY_COMPATIBLE
REL_FORWARD_COMPATIBLE
REL_BACKWARD_COMPATIBLE
Definition at line 46 of file release_string.h.
Function Documentation
int rel_bit_platform (void)
Definition at line 257 of file release_string.c.
References bit_platform.
Referenced by boot_restart_server(), net_client_ping_server_with_handshake(), rel_copy_version_string(), server_ping_with_handshake(), and xboot_initialize_server().
const char* rel_build_number (void)
Definition at line 161 of file release_string.c.
const char* rel_build_os (void)
Definition at line 171 of file release_string.c.
References build_os.
Referenced by rel_copy_version_string().
const char* rel_build_type (void)
Definition at line 182 of file release_string.c.
References build_type, copyright_body, copyright_header, lang_init(), MSGCAT_CATALOG_CUBRID, MSGCAT_GENERAL_COPYRIGHT_BODY, MSGCAT_GENERAL_COPYRIGHT_HEADER, msgcat_message(), and MSGCAT_SET_GENERAL.
Referenced by boot_restart_server(), rel_copy_version_string(), and xboot_initialize_server().
int rel_compare (const char * rel_a, const char * rel_b)
Definition at line 347 of file release_string.c.
References char_isalpha(), and str_to_int32().
Referenced by net_client_ping_server_with_handshake(), and server_ping_with_handshake().
void rel_copy_version_string (char * buf, size_t len)
Definition at line 110 of file release_string.c.
References rel_bit_platform(), rel_build_number(), rel_build_os(), rel_build_type(), and rel_name().
Referenced by main(), and util_service_version().
float rel_disk_compatible (void)
Definition at line 234 of file release_string.c.
References disk_compatibility_level.
Referenced by boot_restart_client(), check_and_fix_compat_level(), fileio_start_backup(), logpb_delete(), logpb_initialize_header(), logpb_restore(), main(), and xboot_register_client().
REL_COMPATIBILITY rel_get_disk_compatible (float db_level, REL_FIXUP_FUNCTION ** fixups)
Definition at line 291 of file release_string.c.
References compatibility_rule::apply, compatibility_rule::base, compatibility_rule::compatibility, disk_compatibility_level, compatibility_rule::fix_function, version::major, version::minor, NULL, REL_FULLY_COMPATIBLE, and REL_NOT_COMPATIBLE.
Referenced by log_initialize_internal(), logpb_find_header_parameters(), and logpb_restore().
REL_COMPATIBILITY rel_get_net_compatible (const char * client_rel_str, const char * server_rel_str)
Definition at line 500 of file release_string.c.
References CHECK_NET_PROTOCOL_COMPATIBILITY, and rel_get_compatible_internal().
Referenced by net_client_ping_server_with_handshake(), and server_ping_with_handshake().
bool rel_is_log_compatible (const char * writer_rel_str, const char * reader_rel_str)
Definition at line 456 of file release_string.c.
References CHECK_LOG_COMPATIBILITY, rel_get_compatible_internal(), and REL_NOT_COMPATIBLE.
Referenced by fileio_continue_restore(), and log_initialize_internal().
const char* rel_major_release_string (void)
Definition at line 151 of file release_string.c.
References major_release_string.
Referenced by classobj_check_index_exist(), css_pack_server_name(), do_create_trigger(), hb_pack_server_name(), pt_check_alter(), pt_check_attribute_domain(), pt_check_create_entity(), sm_exist_index(), sm_rename_class(), smt_add_constraint(), and smt_rename_any().
const char* rel_name (void)
Definition at line 131 of file release_string.c.
References package_string.
Referenced by boot_initialize_client(), boot_restart_server(), er_stop_on_error(), fileio_continue_restore(), log_initialize_internal(), logpb_find_header_parameters(), logpb_restore(), rel_copy_version_string(), and xboot_initialize_server().
const char* rel_release_string (void)
Definition at line 141 of file release_string.c.
References release_string.
Referenced by css_process_shutdown_time_info(), fileio_continue_restore(), fileio_start_backup(), log_initialize_internal(), logpb_find_header_parameters(), logpb_initialize_header(), logpb_restore(), net_client_ping_server_with_handshake(), and server_ping_with_handshake().
void rel_set_disk_compatible (float level)
Definition at line 246 of file release_string.c.
References disk_compatibility_level.
Referenced by boot_restart_client().