CUBRID Engine: src/query/serial.h File Reference
serial.h File Reference
#include "dbtype_def.h"
#include "thread_compat.hpp"
#include "storage_common.h"
Functions
int xserial_get_current_value (THREAD_ENTRY *thread_p, DB_VALUE *result_num, const OID *oid_p, int cached_num)
int xserial_get_next_value (THREAD_ENTRY *thread_p, DB_VALUE *result_num, const OID *oid_p, int cached_num, int num_alloc, int is_auto_increment, bool force_set_last_insert_id)
void serial_finalize_cache_pool (void)
int serial_initialize_cache_pool (THREAD_ENTRY *thread_p)
void xserial_decache (THREAD_ENTRY *thread_p, OID *oidp)
Function Documentation
void serial_finalize_cache_pool (void)
Definition at line 1111 of file serial.c.
References serial_cache_pool::area, serial_cache_pool::cache_pool_mutex, free_and_init, serial_cache_pool::free_list, serial_cache_pool::ht, mht_destroy(), serial_cache_area::next, NULL, serial_cache_area::obj_area, pthread_mutex_destroy, and serial_Num_attrs.
Referenced by boot_server_all_finalize(), and serial_initialize_cache_pool().
int serial_initialize_cache_pool (THREAD_ENTRY * thread_p)
Definition at line 1073 of file serial.c.
References serial_cache_pool::area, serial_cache_pool::cache_pool_mutex, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, serial_cache_pool::free_list, serial_cache_pool::ht, i, mht_create(), NCACHE_OBJECTS, NO_ERROR, NULL, serial_cache_area::obj_area, oid_compare_equals(), oid_hash(), pthread_mutex_init, serial_alloc_cache_area(), serial_Attrs_id, and serial_finalize_cache_pool().
Referenced by boot_restart_server().
void xserial_decache (THREAD_ENTRY * thread_p, OID * oidp)
Definition at line 1366 of file serial.c.
References serial_cache_pool::cache_pool_mutex, serial_cache_pool::free_list, serial_cache_pool::ht, mht_get(), mht_rem(), serial_entry::next, NULL, serial_entry::oid, OID_SET_NULL, pthread_mutex_lock, pthread_mutex_unlock, rc, serial_clear_value(), and xcache_remove_by_oid().
Referenced by serial_decache(), and sserial_decache().
int xserial_get_current_value (THREAD_ENTRY * thread_p, DB_VALUE * result_num, const OID * oid_p, int cached_num)
Definition at line 156 of file serial.c.
References assert, serial_cache_pool::cache_pool_mutex, serial_entry::cur_val, serial_cache_pool::ht, mht_get(), NO_ERROR, NULL, pr_clone_value(), pthread_mutex_lock, pthread_mutex_unlock, rc, and xserial_get_current_value_internal().
Referenced by fetch_peek_arith(), serial_get_current_value(), and sserial_get_current_value().
int xserial_get_next_value (THREAD_ENTRY * thread_p, DB_VALUE * result_num, const OID * oid_p, int cached_num, int num_alloc, int is_auto_increment, bool force_set_last_insert_id)
Definition at line 282 of file serial.c.
References ARG_FILE_LINE, assert, serial_cache_pool::cache_pool_mutex, CHECK_MODIFICATION_NO_RETURN, serial_entry::cur_val, serial_cache_pool::db_serial_class_oid, er_errid(), ER_ERROR_SEVERITY, ER_FAILED, ER_QPROC_INVALID_PARAMETER, er_set(), GENERATE_AUTO_INCREMENT, serial_cache_pool::ht, LK_COND_LOCK, LK_GRANTED, LK_NOTGRANTED, LK_UNCOND_LOCK, lock_object(), lock_unlock_object(), mht_get(), NO_ERROR, NULL, OID_ISNULL, pr_clone_value(), pthread_mutex_lock, pthread_mutex_unlock, rc, serial_get_next_cached_value(), serial_load_attribute_info_of_db_serial(), X_LOCK, xserial_get_next_value_internal(), and xsession_set_cur_insert_id().
Referenced by fetch_peek_arith(), heap_set_autoincrement_value(), serial_get_next_value(), and sserial_get_next_value().