CUBRID Engine: src/executables/server.c File Reference
server.c File Reference
#include "config.h"
#include <stdio.h>
#include <string.h>
#include <fcntl.h>
#include <signal.h>
#include <sys/resource.h>
#include <unistd.h>
#include <limits.h>
#include "porting.h"
#include "system_parameter.h"
#include "connection_error.h"
#include "network.h"
#include "environment_variable.h"
#include "boot_sr.h"
#include "perf_monitor.h"
#include "util_func.h"
#include "tcp.h"
#include "heartbeat.h"
#include "log_impl.h"
Functions
static void register_fatal_signal_handler (int signo)
static void crash_handler (int signo, siginfo_t *siginfo, void *dummyp)
static void abort_handler (int signo, siginfo_t *siginfo, void *dummyp)
static int unmask_signal (int signo)
static void register_abort_signal_handler (int signo)
int main (int argc, char **argv)
Variables
static const char * database_name = ""
static char executable_path [PATH_MAX]
Function Documentation
static void abort_handler (int signo, siginfo_t * siginfo, void * dummyp) static
Definition at line 266 of file server.c.
References assert, BO_IS_SERVER_RESTARTED, i, logtb_collect_local_clients(), NULL, and os_set_signal_handler().
Referenced by register_abort_signal_handler().
static void crash_handler (int signo, siginfo_t * siginfo, void * dummyp) static
Definition at line 207 of file server.c.
References BO_IS_SERVER_RESTARTED, css_get_max_socket_fds(), database_name, executable_path, NULL, os_set_signal_handler(), pid, prm_get_bool_value(), prm_get_string_value(), PRM_ID_AUTO_RESTART_SERVER, PRM_ID_ER_LOG_FILE, register_fatal_signal_handler(), and unmask_signal().
Referenced by register_fatal_signal_handler().
int main (int argc, char ** argv)
Definition at line 315 of file server.c.
References basename(), database_name, envvar_bindir_file(), executable_path, hb_set_argv(), hb_set_exec_path(), net_server_start(), PRINT_AND_LOG_ERR_MSG, register_abort_signal_handler(), and register_fatal_signal_handler().
static void register_abort_signal_handler (int signo) static
Definition at line 117 of file server.c.
References abort_handler(), db_name, envvar_bindir_file(), executable_path, FALSE, and NULL.
Referenced by main().
static void register_fatal_signal_handler (int signo) static
Definition at line 103 of file server.c.
References crash_handler(), and NULL.
Referenced by crash_handler(), and main().
static int unmask_signal (int signo) static
Definition at line 85 of file server.c.
References NULL.
Referenced by crash_handler().
Variable Documentation
const char* database_name = "" static
Definition at line 71 of file server.c.
Referenced by crash_handler(), and main().
char executable_path[PATH_MAX] static
Definition at line 73 of file server.c.
Referenced by applylogdb(), copylogdb(), crash_handler(), hb_start_util_process(), main(), proc_execute_hide_cmd_args(), proc_execute_internal(), and register_abort_signal_handler().