CUBRID Engine: src/session/session_sr.c File Reference
session_sr.c File Reference
#include "session.h"
#include "dbtype.h"
#include "xasl.h"
#include "xasl_cache.h"
#include "xserver_interface.h"
Functions
int xsession_create_new (THREAD_ENTRY *thread_p, SESSION_ID *id)
int xsession_check_session (THREAD_ENTRY *thread_p, const SESSION_ID id)
int xsession_end_session (THREAD_ENTRY *thread_p, const SESSION_ID id)
int xsession_set_row_count (THREAD_ENTRY *thread_p, int row_count)
int xsession_get_row_count (THREAD_ENTRY *thread_p, int *row_count)
int xsession_set_cur_insert_id (THREAD_ENTRY *thread_p, const DB_VALUE *value, bool force)
int xsession_get_last_insert_id (THREAD_ENTRY *thread_p, DB_VALUE *value, bool update_last_insert_id)
int xsession_reset_cur_insert_id (THREAD_ENTRY *thread_p)
int xsession_create_prepared_statement (THREAD_ENTRY *thread_p, char *name, char *alias_print, SHA1Hash *sha1, char *info, int info_len)
int xsession_get_prepared_statement (THREAD_ENTRY *thread_p, const char *name, char **info, int *info_len, XASL_ID *xasl_id, xasl_node_header *xasl_header_p)
int xsession_delete_prepared_statement (THREAD_ENTRY *thread_p, const char *name)
int xlogin_user (THREAD_ENTRY *thread_p, const char *username)
int xsession_set_session_variables (THREAD_ENTRY *thread_p, DB_VALUE *values, const int count)
int xsession_get_session_variable (THREAD_ENTRY *thread_p, const DB_VALUE *name, DB_VALUE *value)
int xsession_get_session_variable_no_copy (THREAD_ENTRY *thread_p, const DB_VALUE *name, DB_VALUE **value)
int xsession_drop_session_variables (THREAD_ENTRY *thread_p, DB_VALUE *values, const int count)
void xsession_store_query_entry_info (THREAD_ENTRY *thread_p, QMGR_QUERY_ENTRY *qentry_p)
int xsession_load_query_entry_info (THREAD_ENTRY *thread_p, QMGR_QUERY_ENTRY *qentry_p)
int xsession_remove_query_entry_info (THREAD_ENTRY *thread_p, const QUERY_ID query_id)
int xsession_clear_query_entry_info (THREAD_ENTRY *thread_p, const QUERY_ID query_id)
int xsession_set_tran_auto_commit (THREAD_ENTRY *thread_p, bool auto_commit)
Function Documentation
int xlogin_user (THREAD_ENTRY * thread_p, const char * username)
Definition at line 245 of file session_sr.c.
References login_user().
Referenced by clogin_user(), and slogin_user().
int xsession_check_session (THREAD_ENTRY * thread_p, const SESSION_ID id)
Definition at line 53 of file session_sr.c.
References session_check_session().
Referenced by csession_find_or_create_session(), and ssession_find_or_create_session().
int xsession_clear_query_entry_info (THREAD_ENTRY * thread_p, const QUERY_ID query_id)
Definition at line 357 of file session_sr.c.
References session_clear_query_entry_info().
Referenced by qmgr_clear_trans_wakeup(), and xqmgr_end_query().
int xsession_create_new (THREAD_ENTRY * thread_p, SESSION_ID * id)
Definition at line 38 of file session_sr.c.
References assert, NULL, and session_state_create().
Referenced by csession_find_or_create_session(), and ssession_find_or_create_session().
int xsession_create_prepared_statement (THREAD_ENTRY * thread_p, char * name, char * alias_print, SHA1Hash * sha1, char * info, int info_len)
Definition at line 171 of file session_sr.c.
References session_create_prepared_statement().
Referenced by csession_create_prepared_statement(), and ssession_create_prepared_statement().
int xsession_delete_prepared_statement (THREAD_ENTRY * thread_p, const char * name)
Definition at line 233 of file session_sr.c.
References session_delete_prepared_statement().
Referenced by csession_delete_prepared_statement(), and ssession_delete_prepared_statement().
int xsession_drop_session_variables (THREAD_ENTRY * thread_p, DB_VALUE * values, const int count)
Definition at line 306 of file session_sr.c.
References session_drop_session_variables().
Referenced by csession_drop_session_variables(), and ssession_drop_session_variables().
int xsession_end_session (THREAD_ENTRY * thread_p, const SESSION_ID id)
Definition at line 65 of file session_sr.c.
References session_state_destroy().
Referenced by csession_end_session(), and ssession_end_session().
int xsession_get_last_insert_id (THREAD_ENTRY * thread_p, DB_VALUE * value, bool update_last_insert_id)
Definition at line 126 of file session_sr.c.
References assert, db_make_null(), err, NO_ERROR, NULL, and session_get_last_insert_id().
Referenced by csession_get_last_insert_id(), and ssession_get_last_insert_id().
int xsession_get_prepared_statement (THREAD_ENTRY * thread_p, const char * name, char ** info, int * info_len, XASL_ID * xasl_id, xasl_node_header * xasl_header_p)
Definition at line 190 of file session_sr.c.
References assert, ASSERT_ERROR, xasl_stream::buffer, error(), NO_ERROR, NULL, perfmon_inc_stat(), PSTAT_PC_NUM_INVALID_XASL_ID, qfile_load_xasl_node_header(), session_get_prepared_statement(), xasl_cache_ent::stream, xasl_cache_ent::xasl_id, XASL_ID_COPY, XASL_ID_SET_NULL, and xcache_unfix().
Referenced by csession_get_prepared_statement(), and ssession_get_prepared_statement().
int xsession_get_row_count (THREAD_ENTRY * thread_p, int * row_count)
Definition at line 91 of file session_sr.c.
References session_get_row_count().
Referenced by csession_find_or_create_session(), csession_get_row_count(), ssession_find_or_create_session(), and ssession_get_row_count().
int xsession_get_session_variable (THREAD_ENTRY * thread_p, const DB_VALUE * name, DB_VALUE * value)
Definition at line 271 of file session_sr.c.
References session_get_variable().
Referenced by ssession_get_session_variable().
int xsession_get_session_variable_no_copy (THREAD_ENTRY * thread_p, const DB_VALUE * name, DB_VALUE ** value)
Definition at line 288 of file session_sr.c.
References assert, ER_FAILED, and session_get_variable_no_copy().
Referenced by csession_get_variable().
int xsession_load_query_entry_info (THREAD_ENTRY * thread_p, QMGR_QUERY_ENTRY * qentry_p)
Definition at line 330 of file session_sr.c.
References session_load_query_entry_info().
Referenced by qmgr_get_query_entry().
int xsession_remove_query_entry_info (THREAD_ENTRY * thread_p, const QUERY_ID query_id)
Definition at line 343 of file session_sr.c.
References session_remove_query_entry_info().
Referenced by xqmgr_end_query().
int xsession_reset_cur_insert_id (THREAD_ENTRY * thread_p)
Definition at line 147 of file session_sr.c.
References err, NO_ERROR, and session_reset_cur_insert_id().
Referenced by csession_reset_cur_insert_id(), and ssession_reset_cur_insert_id().
int xsession_set_cur_insert_id (THREAD_ENTRY * thread_p, const DB_VALUE * value, bool force)
Definition at line 106 of file session_sr.c.
References assert, err, NO_ERROR, NULL, and session_set_cur_insert_id().
Referenced by xserial_get_next_value().
int xsession_set_row_count (THREAD_ENTRY * thread_p, int row_count)
Definition at line 78 of file session_sr.c.
References session_set_row_count().
Referenced by csession_set_row_count(), ssession_set_row_count(), and stran_server_commit().
int xsession_set_session_variables (THREAD_ENTRY * thread_p, DB_VALUE * values, const int count)
Definition at line 258 of file session_sr.c.
References session_set_session_variables().
Referenced by csession_set_session_variables(), and ssession_set_session_variables().
int xsession_set_tran_auto_commit (THREAD_ENTRY * thread_p, bool auto_commit)
Definition at line 370 of file session_sr.c.
References session_set_tran_auto_commit().
Referenced by sqmgr_execute_query(), and sqmgr_prepare_and_execute_query().
void xsession_store_query_entry_info (THREAD_ENTRY * thread_p, QMGR_QUERY_ENTRY * qentry_p)
Definition at line 318 of file session_sr.c.
References session_store_query_entry_info().
Referenced by qmgr_clear_trans_wakeup().