CUBRID Engine: src/query/set_scan.c File Reference
set_scan.c File Reference
#include "config.h"
#include <string.h>
#include "set_scan.h"
#include "dbtype.h"
#include "fetch.h"
#include "xasl.h"
Functions
SCAN_CODE qproc_next_set_scan (THREAD_ENTRY *thread_p, SCAN_ID *s_id)
Function Documentation
SCAN_CODE qproc_next_set_scan (THREAD_ENTRY * thread_p, SCAN_ID * s_id)
Definition at line 44 of file set_scan.c.
References ARG_FILE_LINE, set_scan_id::cur_index, db_get_set(), DB_IS_NULL, db_set_get(), db_set_size(), db_value_clear(), ER_ERROR_SEVERITY, ER_QPROC_UNKNOWN_CRSPOS, er_set(), F_SEQUENCE, fetch_copy_dbval(), regu_variable_list_node::next, NO_ERROR, NULL, set_scan_id::operand, scan_id_struct::position, scan_id_struct::s, S_AFTER, S_BEFORE, S_END, S_ERROR, S_ON, S_SUCCESS, set_scan_id::set, set_scan_id::set_card, set_scan_id::set_ptr, scan_id_struct::ssid, TYPE_FUNC, qproc_db_value_list::val, scan_id_struct::val_list, val_list_node::valp, regu_variable_list_node::value, and scan_id_struct::vd.
Referenced by scan_next_set_scan().