CUBRID Engine: src/base/sha1.c File Reference
sha1.c File Reference
#include "sha1.h"
#include "error_manager.h"
#include <assert.h>
Macros
#define SHA1CircularShift(bits, word)
Functions
void SHA1ProcessMessageBlock (SHA1Context *)
void SHA1PadMessage (SHA1Context *)
void SHA1Reset (SHA1Context *context)
int SHA1Result (SHA1Context *context)
void SHA1Input (SHA1Context *context, const unsigned char *message_array, size_t length)
int SHA1Compute (const unsigned char *message_array, size_t length, SHA1Hash *hash)
int SHA1Compare (void *a, void *b)
Macro Definition Documentation
#define SHA1CircularShift (bits, word)
Value:
((((word) << (bits)) & 0xFFFFFFFF) | \
                ((word) >> (32-(bits))))
Definition at line 49 of file sha1.c.
Referenced by SHA1ProcessMessageBlock().
Function Documentation
int SHA1Compare (void * a, void * b)
Definition at line 400 of file sha1.c.
References diff, SHA1Hash::h, and i.
Referenced by xcache_compare_key().
int SHA1Compute (const unsigned char * message_array, size_t length, SHA1Hash * hash)
Definition at line 372 of file sha1.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_FAILED, ER_GENERIC_ERROR, er_set(), SHA1Hash::h, SHA1Context::Message_Digest, NO_ERROR, NULL, SHA1Input(), SHA1Reset(), and SHA1Result().
Referenced by btree_fix_root_for_delete(), btree_fix_root_for_insert(), csession_create_prepared_statement(), do_prepare_delete(), do_prepare_insert_internal(), do_prepare_merge(), do_prepare_select(), and do_prepare_update().
void SHA1Input (SHA1Context * context, const unsigned char * message_array, size_t length)
Definition at line 149 of file sha1.c.
References SHA1Context::Computed, SHA1Context::Corrupted, SHA1Context::Length_High, SHA1Context::Length_Low, SHA1Context::Message_Block, SHA1Context::Message_Block_Index, and SHA1ProcessMessageBlock().
Referenced by crypt_encrypt_sha1_printable(), and SHA1Compute().
void SHA1PadMessage (SHA1Context * context)
Definition at line 324 of file sha1.c.
References SHA1Context::Length_High, SHA1Context::Length_Low, SHA1Context::Message_Block, SHA1Context::Message_Block_Index, and SHA1ProcessMessageBlock().
Referenced by SHA1Result().
void SHA1ProcessMessageBlock (SHA1Context * context)
Definition at line 211 of file sha1.c.
References SHA1Context::Message_Block, SHA1Context::Message_Block_Index, SHA1Context::Message_Digest, and SHA1CircularShift.
Referenced by SHA1Input(), and SHA1PadMessage().
void SHA1Reset (SHA1Context * context)
Definition at line 75 of file sha1.c.
References SHA1Context::Computed, SHA1Context::Corrupted, SHA1Context::Length_High, SHA1Context::Length_Low, SHA1Context::Message_Block_Index, and SHA1Context::Message_Digest.
Referenced by crypt_encrypt_sha1_printable(), and SHA1Compute().
int SHA1Result (SHA1Context * context)
Definition at line 109 of file sha1.c.
References SHA1Context::Computed, SHA1Context::Corrupted, and SHA1PadMessage().
Referenced by crypt_encrypt_sha1_printable(), and SHA1Compute().