CUBRID Engine: src/base/sha1.h File Reference
sha1.h File Reference
#include "system.h"
Classes
struct SHA1Context
struct SHA1Hash
Macros
#define SHA1_HASH_INITIALIZER { { 0, 0, 0, 0, 0 } }
#define SHA1_AS_ARGS(sha1) (sha1)->h[0], (sha1)->h[1], (sha1)->h[2], (sha1)->h[3], (sha1)->h[4]
Typedefs
typedef struct SHA1Context SHA1Context
typedef struct SHA1Hash SHA1Hash
Functions
void SHA1Reset (SHA1Context *)
int SHA1Result (SHA1Context *)
void SHA1Input (SHA1Context *, const unsigned char *, size_t)
int SHA1Compute (const unsigned char *, size_t, SHA1Hash *)
int SHA1Compare (void *a, void *b)
Macro Definition Documentation
#define SHA1_AS_ARGS (sha1) (sha1)->h[0], (sha1)->h[1], (sha1)->h[2], (sha1)->h[3], (sha1)->h[4]
Definition at line 56 of file sha1.h.
Referenced by logtb_descriptors_start_scan(), qmgr_free_tran_entries(), session_dump_prepared_statement(), xcache_dump(), and xqmgr_execute_query().
#define SHA1_HASH_INITIALIZER { { 0, 0, 0, 0, 0 } }
Definition at line 54 of file sha1.h.
Referenced by csession_create_prepared_statement(), sqmgr_prepare_query(), and ssession_create_prepared_statement().
Typedef Documentation
typedef struct SHA1Context SHA1Context
typedef struct SHA1Hash SHA1Hash
Function Documentation
int SHA1Compare (void * a, void * b)
Definition at line 400 of file sha1.c.
References diff, SHA1Hash::h, and i.
Referenced by xcache_compare_key().
int SHA1Compute (const unsigned char * , size_t , SHA1Hash *)
Definition at line 372 of file sha1.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_FAILED, ER_GENERIC_ERROR, er_set(), SHA1Hash::h, SHA1Context::Message_Digest, NO_ERROR, NULL, SHA1Input(), SHA1Reset(), and SHA1Result().
Referenced by btree_fix_root_for_delete(), btree_fix_root_for_insert(), csession_create_prepared_statement(), do_prepare_delete(), do_prepare_insert_internal(), do_prepare_merge(), do_prepare_select(), and do_prepare_update().
void SHA1Input (SHA1Context * , const unsigned char * , size_t)
Definition at line 149 of file sha1.c.
References SHA1Context::Computed, SHA1Context::Corrupted, SHA1Context::Length_High, SHA1Context::Length_Low, SHA1Context::Message_Block, SHA1Context::Message_Block_Index, and SHA1ProcessMessageBlock().
Referenced by crypt_encrypt_sha1_printable(), and SHA1Compute().
void SHA1Reset (SHA1Context *)
Definition at line 75 of file sha1.c.
References SHA1Context::Computed, SHA1Context::Corrupted, SHA1Context::Length_High, SHA1Context::Length_Low, SHA1Context::Message_Block_Index, and SHA1Context::Message_Digest.
Referenced by crypt_encrypt_sha1_printable(), and SHA1Compute().
int SHA1Result (SHA1Context *)
Definition at line 109 of file sha1.c.
References SHA1Context::Computed, SHA1Context::Corrupted, and SHA1PadMessage().
Referenced by crypt_encrypt_sha1_printable(), and SHA1Compute().