CUBRID Engine: src/broker/shard_key_func.h File Reference
shard_key_func.h File Reference
#include "shard_key.h"
#include "shard_parser.h"
Functions
int register_fn_get_shard_key (void)
int fn_get_shard_key_default (const char *shard_key, T_SHARD_U_TYPE type, const void *value, int value_len)
int proxy_find_shard_id_by_hint_value (SP_VALUE *value_p, const char *key_column)
Function Documentation
int fn_get_shard_key_default (const char * shard_key, T_SHARD_U_TYPE type, const void * value, int value_len)
Definition at line 78 of file shard_key_func.c.
References ERROR_ON_ARGUMENT, ERROR_ON_MAKE_SHARD_KEY, NULL, PROXY_LOG, PROXY_LOG_MODE_ERROR, t_shm_proxy::shard_key_modular, SHARD_U_TYPE_BIGINT, SHARD_U_TYPE_INT, SHARD_U_TYPE_SHORT, SHARD_U_TYPE_UBIGINT, SHARD_U_TYPE_UINT, and SHARD_U_TYPE_USHORT.
Referenced by register_fn_get_shard_key().
int proxy_find_shard_id_by_hint_value (SP_VALUE * value_p, const char * key_column)
Definition at line 123 of file shard_key_func.c.
References sp_value::integer, sp_value::length, PROXY_LOG, PROXY_LOG_MODE_ERROR, SHARD_U_TYPE_BIGINT, SHARD_U_TYPE_STRING, sp_value::string, sp_value::type, sp_value::value, VT_INTEGER, and VT_STRING.
Referenced by admin_getid_cmd(), proxy_get_range_by_param(), and shard_stmt_change_shard_val_to_id().
int register_fn_get_shard_key (void)
Definition at line 47 of file shard_key_func.c.
References close_shard_key_function(), error(), fn_get_shard_key, fn_get_shard_key_default(), load_shard_key_function(), PROXY_LOG, PROXY_LOG_MODE_ERROR, PROXY_LOG_MODE_NOTICE, t_shm_proxy::shard_key_function_name, and t_shm_proxy::shard_key_library_name.
Referenced by admin_getid_cmd(), and main().