CUBRID Engine: src/query/show_scan.h File Reference
show_scan.h File Reference
#include "dbtype_def.h"
#include "thread_compat.hpp"
Classes
struct showstmt_array_context
Typedefs
typedef struct showstmt_array_context SHOWSTMT_ARRAY_CONTEXT
Functions
SHOWSTMT_ARRAY_CONTEXT * showstmt_alloc_array_context (THREAD_ENTRY *thread_p, int num_capacity, int num_cols)
void showstmt_free_array_context (THREAD_ENTRY *thread_p, SHOWSTMT_ARRAY_CONTEXT *ctx)
DB_VALUE * showstmt_alloc_tuple_in_context (THREAD_ENTRY *thread_p, SHOWSTMT_ARRAY_CONTEXT *ctx)
int thread_start_scan (THREAD_ENTRY *thread_p, int type, DB_VALUE **arg_values, int arg_cnt, void **ctx)
Typedef Documentation
typedef struct showstmt_array_context SHOWSTMT_ARRAY_CONTEXT
Definition at line 31 of file show_scan.h.
Function Documentation
SHOWSTMT_ARRAY_CONTEXT* showstmt_alloc_array_context (THREAD_ENTRY * thread_p, int num_capacity, int num_cols)
Definition at line 336 of file show_scan.c.
References db_private_alloc, db_private_free, NULL, showstmt_array_context::num_cols, showstmt_array_context::num_total, showstmt_array_context::num_used, on_error, and showstmt_array_context::tuples.
Referenced by csect_start_scan(), css_user_access_status_start_scan(), logtb_descriptors_start_scan(), pgbuf_start_scan(), thread_start_scan(), tz_full_timezones_start_scan(), and tz_timezones_start_scan().
DB_VALUE* showstmt_alloc_tuple_in_context (THREAD_ENTRY * thread_p, SHOWSTMT_ARRAY_CONTEXT * ctx)
Definition at line 402 of file show_scan.c.
References db_make_null(), db_private_alloc, db_private_realloc, i, NULL, showstmt_array_context::num_cols, showstmt_array_context::num_total, showstmt_array_context::num_used, and showstmt_array_context::tuples.
Referenced by csect_start_scan(), css_make_access_status_exist_user(), css_user_access_status_start_scan(), css_wp_core_job_scan_mapper(), logtb_descriptors_start_scan(), pgbuf_start_scan(), showstmt_array_end_scan(), tz_full_timezones_start_scan(), and tz_timezones_start_scan().
void showstmt_free_array_context (THREAD_ENTRY * thread_p, SHOWSTMT_ARRAY_CONTEXT * ctx)
Definition at line 373 of file show_scan.c.
References assert, db_private_free, i, NULL, showstmt_array_context::num_cols, showstmt_array_context::num_used, pr_clear_value(), and showstmt_array_context::tuples.
Referenced by csect_start_scan(), css_user_access_status_start_scan(), logtb_descriptors_start_scan(), pgbuf_start_scan(), showstmt_array_end_scan(), thread_start_scan(), tz_full_timezones_start_scan(), and tz_timezones_start_scan().
int thread_start_scan (THREAD_ENTRY * thread_p, int type, DB_VALUE ** arg_values, int arg_cnt, void ** ctx)
Definition at line 813 of file show_scan.c.
References ASSERT_ERROR, ASSERT_ERROR_AND_SET, error(), cubthread::manager::map_entries(), NO_ERROR, NULL, showstmt_alloc_array_context(), showstmt_free_array_context(), thread_get_manager(), thread_num_total_threads(), and THREAD_SCAN_COLUMN_COUNT.
Referenced by showstmt_scan_init().