CUBRID Engine: src/parser/show_meta.h File Reference
show_meta.h File Reference
#include "config.h"
#include "dbtype_def.h"
#include "parse_tree.h"
Classes
struct showstmt_column
struct showstmt_column_orderby
struct showstmt_named_arg
struct showstmt_metadata
Typedefs
typedef struct showstmt_column SHOWSTMT_COLUMN
typedef struct showstmt_column_orderby SHOWSTMT_COLUMN_ORDERBY
typedef struct showstmt_named_arg SHOWSTMT_NAMED_ARG
typedef PT_NODE *(* SHOW_SEMANTIC_CHECK_FUNC) (PARSER_CONTEXT *parser, PT_NODE *node)
typedef struct showstmt_metadata SHOWSTMT_METADATA
Enumerations
enum ARG_VALUE_TYPE { AVT_INTEGER, AVT_STRING, AVT_IDENTIFIER }
Functions
int showstmt_metadata_init (void)
void showstmt_metadata_final (void)
const SHOWSTMT_METADATA * showstmt_get_metadata (SHOWSTMT_TYPE show_type)
DB_ATTRIBUTE * showstmt_get_attributes (SHOWSTMT_TYPE show_type)
Typedef Documentation
typedef PT_NODE*(* SHOW_SEMANTIC_CHECK_FUNC) (PARSER_CONTEXT *parser, PT_NODE *node)
Definition at line 63 of file show_meta.h.
typedef struct showstmt_column SHOWSTMT_COLUMN
Definition at line 34 of file show_meta.h.
typedef struct showstmt_column_orderby SHOWSTMT_COLUMN_ORDERBY
Definition at line 41 of file show_meta.h.
typedef struct showstmt_metadata SHOWSTMT_METADATA
Definition at line 65 of file show_meta.h.
typedef struct showstmt_named_arg SHOWSTMT_NAMED_ARG
Definition at line 55 of file show_meta.h.
Enumeration Type Documentation
enum ARG_VALUE_TYPE
Enumerator
AVT_INTEGER
AVT_STRING
AVT_IDENTIFIER
Definition at line 48 of file show_meta.h.
Function Documentation
DB_ATTRIBUTE* showstmt_get_attributes (SHOWSTMT_TYPE show_type)
Definition at line 753 of file show_meta.c.
References NULL, showstmt_metadata::showstmt_attrs, and showstmt_get_metadata().
Referenced by pt_get_all_showstmt_attributes_and_types().
const SHOWSTMT_METADATA* showstmt_get_metadata (SHOWSTMT_TYPE show_type)
Definition at line 734 of file show_meta.c.
References assert_release, NULL, showstmt_metadata::show_type, SHOWSTMT_END, and SHOWSTMT_START.
Referenced by pt_make_query_showstmt(), pt_print_showstmt(), pt_semantic_check_local(), and showstmt_get_attributes().
void showstmt_metadata_final (void)
Definition at line 994 of file show_meta.c.
References free_db_attribute_list(), i, and show_Inited.
Referenced by boot_client_all_finalize(), boot_initialize_client(), and boot_restart_client().
int showstmt_metadata_init (void)
Definition at line 937 of file show_meta.c.
References error(), free_db_attribute_list(), i, init_db_attribute_list(), metadata_of_access_status(), metadata_of_active_log_header(), metadata_of_archive_log_header(), metadata_of_full_timezones(), metadata_of_global_critical_sections(), metadata_of_heap_capacity(), metadata_of_heap_header(), metadata_of_index_capacity(), metadata_of_index_header(), metadata_of_job_queues(), metadata_of_page_buffer_status(), metadata_of_slotted_page_header(), metadata_of_slotted_page_slots(), metadata_of_threads(), metadata_of_timezones(), metadata_of_tran_tables(), metadata_of_volume_header(), NO_ERROR, on_error, SHOW_ALL, show_Inited, SHOW_ONLY, SHOWSTMT_ACCESS_STATUS, SHOWSTMT_ACTIVE_LOG_HEADER, SHOWSTMT_ALL_HEAP_CAPACITY, SHOWSTMT_ALL_HEAP_HEADER, SHOWSTMT_ALL_INDEXES_CAPACITY, SHOWSTMT_ALL_INDEXES_HEADER, SHOWSTMT_ARCHIVE_LOG_HEADER, SHOWSTMT_FULL_TIMEZONES, SHOWSTMT_GLOBAL_CRITICAL_SECTIONS, SHOWSTMT_HEAP_CAPACITY, SHOWSTMT_HEAP_HEADER, SHOWSTMT_INDEX_CAPACITY, SHOWSTMT_INDEX_HEADER, SHOWSTMT_JOB_QUEUES, SHOWSTMT_PAGE_BUFFER_STATUS, SHOWSTMT_SLOTTED_PAGE_HEADER, SHOWSTMT_SLOTTED_PAGE_SLOTS, SHOWSTMT_THREADS, SHOWSTMT_TIMEZONES, SHOWSTMT_TRAN_TABLES, and SHOWSTMT_VOLUME_HEADER.
Referenced by boot_restart_client().