CUBRID Engine: src/base/stack_dump.c File Reference
stack_dump.c File Reference
#include "printer.hpp"
#include <stdio.h>
#include "stack_dump.h"
Functions
void er_dump_call_stack_internal (print_output &output)
void er_dump_call_stack (FILE *outfp)
char * er_dump_call_stack_to_string (void)
Function Documentation
void er_dump_call_stack (FILE * outfp)
Definition at line 500 of file stack_dump.c.
References er_dump_call_stack_internal().
Referenced by er_call_stack_dump_on_error(), and er_print_callstack().
void er_dump_call_stack_internal (print_output & output)
Definition at line 493 of file stack_dump.c.
Referenced by er_dump_call_stack(), and er_dump_call_stack_to_string().
char* er_dump_call_stack_to_string (void)
Definition at line 507 of file stack_dump.c.
References string_print_output::clear(), er_dump_call_stack_internal(), string_print_output::get_buffer(), and strdup().