CUBRID Engine: src/storage/statistics_cl.c File Reference
statistics_cl.c File Reference
#include "config.h"
#include <stdio.h>
#include "object_representation.h"
#include "statistics.h"
#include "object_primitive.h"
#include "memory_alloc.h"
#include "work_space.h"
#include "schema_manager.h"
#include "network_interface_cl.h"
#include "tz_support.h"
#include "db_date.h"
Functions
static CLASS_STATS * stats_client_unpack_statistics (char *buffer)
int stats_get_statistics (OID *class_oid_p, unsigned int time_stamp, CLASS_STATS **stats_p)
void stats_free_statistics (CLASS_STATS *class_statsp)
void stats_dump (const char *class_name_p, FILE *file_p)
Function Documentation
static CLASS_STATS * stats_client_unpack_statistics (char * buffer) static
Definition at line 83 of file statistics_cl.c.
References assert, class_stats::attr_stats, attr_stats::bt_stats, btree_stats::btid, BTREE_STATS_PKEYS_NUM, DB_TYPE_MIDXKEY, db_ws_alloc(), db_ws_free(), btree_stats::has_function, class_stats::heap_num_objects, class_stats::heap_num_pages, btree_stats::height, i, attr_stats::id, btree_stats::key_type, btree_stats::keys, btree_stats::leafs, class_stats::n_attrs, attr_stats::n_btstats, NULL, OR_BTID_ALIGNED_SIZE, OR_GET_BTID, OR_GET_INT, OR_INT_SIZE, or_unpack_domain(), btree_stats::pages, btree_stats::pkeys, btree_stats::pkeys_size, tp_domain::setdomain, stats_free_statistics(), class_stats::time_stamp, tp_domain_size(), TP_DOMAIN_TYPE, and attr_stats::type.
Referenced by stats_get_statistics().
void stats_dump (const char * class_name_p, FILE * file_p)
Definition at line 294 of file statistics_cl.c.
References assert, class_stats::attr_stats, attr_stats::bt_stats, btree_stats::btid, BTREE_STATS_PKEYS_NUM, DB_TYPE_BIGINT, DB_TYPE_BIT, DB_TYPE_BLOB, DB_TYPE_CHAR, DB_TYPE_CLOB, DB_TYPE_DATE, DB_TYPE_DATETIME, DB_TYPE_DATETIMELTZ, DB_TYPE_DATETIMETZ, DB_TYPE_DB_VALUE, DB_TYPE_DOUBLE, DB_TYPE_ENUMERATION, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_MONETARY, DB_TYPE_MULTISET, DB_TYPE_NCHAR, DB_TYPE_NULL, DB_TYPE_NUMERIC, DB_TYPE_OBJECT, DB_TYPE_POINTER, DB_TYPE_SEQUENCE, DB_TYPE_SET, DB_TYPE_SHORT, DB_TYPE_STRING, DB_TYPE_SUB, DB_TYPE_TIME, DB_TYPE_TIMESTAMP, DB_TYPE_TIMESTAMPLTZ, DB_TYPE_TIMESTAMPTZ, DB_TYPE_VARBIT, DB_TYPE_VARIABLE, DB_TYPE_VARNCHAR, vfid::fileid, class_stats::heap_num_objects, class_stats::heap_num_pages, btree_stats::height, i, attr_stats::id, btree_stats::keys, btree_stats::leafs, class_stats::n_attrs, attr_stats::n_btstats, NULL, btree_stats::pages, btree_stats::pkeys, btree_stats::pkeys_size, sm_find_class(), sm_get_att_name(), sm_get_class_with_statistics(), sm_class::stats, class_stats::time_stamp, attr_stats::type, btid::vfid, and vfid::volid.
Referenced by help_print_info().
void stats_free_statistics (CLASS_STATS * class_statsp)
Definition at line 253 of file statistics_cl.c.
References class_stats::attr_stats, attr_stats::bt_stats, db_ws_free(), i, attr_stats::n_btstats, NULL, and btree_stats::pkeys.
Referenced by classobj_find_cons_index2_col_type_list(), install_new_representation(), sm_get_class_with_statistics(), sm_get_statistics_force(), sm_update_all_statistics(), sm_update_statistics(), and stats_client_unpack_statistics().
int stats_get_statistics (OID * class_oid_p, unsigned int time_stamp, CLASS_STATS ** stats_p)
Definition at line 54 of file statistics_cl.c.
References assert, error(), free_and_init, NO_ERROR, NULL, stats_client_unpack_statistics(), and stats_get_statistics_from_server().
Referenced by classobj_find_cons_index2_col_type_list(), sm_get_class_with_statistics(), sm_get_statistics_force(), sm_update_all_statistics(), and sm_update_statistics().