CUBRID Engine: src/storage/statistics_sr.h File Reference
statistics_sr.h File Reference
#include "dbtype_def.h"
#include "statistics.h"
#include "system_catalog.h"
#include "object_representation_sr.h"
Functions
unsigned int stats_get_time_stamp (void)
const BTREE_STATS * stats_find_inherited_index_stats (OR_CLASSREP *cls_rep, OR_CLASSREP *subcls_rep, DISK_ATTR *subcls_attr, BTID *cls_btid)
Function Documentation
const BTREE_STATS* stats_find_inherited_index_stats (OR_CLASSREP * cls_rep, OR_CLASSREP * subcls_rep, DISK_ATTR * subcls_attr, BTID * cls_btid)
Definition at line 1786 of file statistics_sr.c.
References ARG_FILE_LINE, assert, disk_attribute::bt_stats, btree_stats::btid, or_index::btid, BTID_IS_EQUAL, or_index::btname, ER_ERROR_SEVERITY, ER_GENERIC_ERROR, er_set(), i, or_classrep::indexes, or_classrep::n_indexes, and NULL.
Referenced by catalog_get_cardinality(), and stats_update_partitioned_statistics().
unsigned int stats_get_time_stamp (void)
Definition at line 1000 of file statistics_sr.c.
References assert, class_stats::attr_stats, attr_stats::bt_stats, btree_stats::btid, BTREE_STATS_PKEYS_NUM, DB_TYPE_BIGINT, DB_TYPE_BIT, DB_TYPE_BLOB, DB_TYPE_CHAR, DB_TYPE_CLOB, DB_TYPE_DATE, DB_TYPE_DATETIME, DB_TYPE_DATETIMELTZ, DB_TYPE_DATETIMETZ, DB_TYPE_DOUBLE, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_JSON, DB_TYPE_MONETARY, DB_TYPE_MULTISET, DB_TYPE_NCHAR, DB_TYPE_NULL, DB_TYPE_NUMERIC, DB_TYPE_OBJECT, DB_TYPE_POINTER, DB_TYPE_SEQUENCE, DB_TYPE_SET, DB_TYPE_SHORT, DB_TYPE_STRING, DB_TYPE_SUB, DB_TYPE_TIME, DB_TYPE_TIMESTAMP, DB_TYPE_TIMESTAMPLTZ, DB_TYPE_TIMESTAMPTZ, DB_TYPE_VARBIT, DB_TYPE_VARIABLE, DB_TYPE_VARNCHAR, vfid::fileid, class_stats::heap_num_objects, class_stats::heap_num_pages, btree_stats::height, i, attr_stats::id, btree_stats::keys, btree_stats::leafs, class_stats::n_attrs, attr_stats::n_btstats, NULL, btree_stats::pages, btree_stats::pkeys, btree_stats::pkeys_size, class_stats::time_stamp, attr_stats::type, btid::vfid, and vfid::volid.
Referenced by stats_update_partitioned_statistics(), xcache_check_recompilation_threshold(), and xstats_update_statistics().