CUBRID Engine: src/query/stream_to_xasl.c File Reference
stream_to_xasl.c File Reference
#include "config.h"
#include <assert.h>
#include <cstring>
#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
#include "stream_to_xasl.h"
#include "dbtype.h"
#include "error_manager.h"
#include "query_aggregate.hpp"
#include "xasl.h"
#include "xasl_aggregate.hpp"
#include "xasl_analytic.hpp"
#include "xasl_predicate.hpp"
#include "xasl_stream.hpp"
#include "xasl_unpack_info.hpp"
Functions
static ACCESS_SPEC_TYPE * stx_restore_access_spec_type (THREAD_ENTRY *thread_p, char **ptr, void *arg)
static AGGREGATE_TYPE * stx_restore_aggregate_type (THREAD_ENTRY *thread_p, char *ptr)
static FUNCTION_TYPE * stx_restore_function_type (THREAD_ENTRY *thread_p, char *ptr)
static ANALYTIC_TYPE * stx_restore_analytic_type (THREAD_ENTRY *thread_p, char *ptr)
static ANALYTIC_EVAL_TYPE * stx_restore_analytic_eval_type (THREAD_ENTRY *thread_p, char *ptr)
static QFILE_SORTED_LIST_ID * stx_restore_srlist_id (THREAD_ENTRY *thread_p, char *ptr)
static QFILE_LIST_ID * stx_restore_list_id (THREAD_ENTRY *thread_p, char *ptr)
static ARITH_TYPE * stx_restore_arith_type (THREAD_ENTRY *thread_p, char *ptr)
static INDX_INFO * stx_restore_indx_info (THREAD_ENTRY *thread_p, char *ptr)
static OUTPTR_LIST * stx_restore_outptr_list (THREAD_ENTRY *thread_p, char *ptr)
static SELUPD_LIST * stx_restore_selupd_list (THREAD_ENTRY *thread_p, char *ptr)
static UPDDEL_CLASS_INFO * stx_restore_update_class_info_array (THREAD_ENTRY *thread_p, char *ptr, int num_classes)
static UPDATE_ASSIGNMENT * stx_restore_update_assignment_array (THREAD_ENTRY *thread_p, char *ptr, int num_assigns)
static ODKU_INFO * stx_restore_odku_info (THREAD_ENTRY *thread_p, char *ptr)
static PRED_EXPR * stx_restore_pred_expr (THREAD_ENTRY *thread_p, char *ptr)
static REGU_VARIABLE * stx_restore_regu_variable (THREAD_ENTRY *thread_p, char *ptr)
static REGU_VARIABLE_LIST stx_restore_regu_variable_list (THREAD_ENTRY *thread_p, char *ptr)
static REGU_VARLIST_LIST stx_restore_regu_varlist_list (THREAD_ENTRY *thread_p, char *ptr)
static SORT_LIST * stx_restore_sort_list (THREAD_ENTRY *thread_p, char *ptr)
static VAL_LIST * stx_restore_val_list (THREAD_ENTRY *thread_p, char *ptr)
static DB_VALUE * stx_restore_db_value (THREAD_ENTRY *thread_p, char *ptr)
static XASL_NODE * stx_restore_xasl_node (THREAD_ENTRY *thread_p, char *ptr)
static PRED_EXPR_WITH_CONTEXT * stx_restore_filter_pred_node (THREAD_ENTRY *thread_p, char *ptr)
static FUNC_PRED * stx_restore_func_pred (THREAD_ENTRY *thread_p, char *ptr)
static HEAP_CACHE_ATTRINFO * stx_restore_cache_attrinfo (THREAD_ENTRY *thread_p, char *ptr)
static DB_VALUE ** stx_restore_db_value_array_extra (THREAD_ENTRY *thread_p, char *ptr, int size, int total_size)
static int * stx_restore_int_array (THREAD_ENTRY *thread_p, char *ptr, int size)
static OID * stx_restore_OID_array (THREAD_ENTRY *thread_p, char *ptr, int size)
static METHOD_SIG_LIST * stx_restore_method_sig_list (THREAD_ENTRY *thread_p, char *ptr)
static METHOD_SIG * stx_restore_method_sig (THREAD_ENTRY *thread_p, char *ptr, int size)
static KEY_RANGE * stx_restore_key_range_array (THREAD_ENTRY *thread_p, char *ptr, int size)
static char * stx_build_xasl_node (THREAD_ENTRY *thread_p, char *tmp, XASL_NODE *ptr)
static char * stx_build_xasl_header (THREAD_ENTRY *thread_p, char *ptr, XASL_NODE_HEADER *xasl_header)
static char * stx_build_filter_pred_node (THREAD_ENTRY *thread_p, char *ptr, PRED_EXPR_WITH_CONTEXT *pred)
static char * stx_build_func_pred (THREAD_ENTRY *thread_p, char *tmp, FUNC_PRED *ptr)
static char * stx_build_cache_attrinfo (char *tmp)
static char * stx_build_list_id (THREAD_ENTRY *thread_p, char *tmp, QFILE_LIST_ID *ptr)
static char * stx_build_method_sig_list (THREAD_ENTRY *thread_p, char *tmp, METHOD_SIG_LIST *ptr)
static char * stx_build_method_sig (THREAD_ENTRY *thread_p, char *tmp, METHOD_SIG *ptr, int size)
static char * stx_build_union_proc (THREAD_ENTRY *thread_p, char *tmp, UNION_PROC_NODE *ptr)
static char * stx_build_fetch_proc (THREAD_ENTRY *thread_p, char *tmp, FETCH_PROC_NODE *ptr)
static char * stx_build_buildlist_proc (THREAD_ENTRY *thread_p, char *tmp, BUILDLIST_PROC_NODE *ptr)
static char * stx_build_buildvalue_proc (THREAD_ENTRY *thread_p, char *tmp, BUILDVALUE_PROC_NODE *ptr)
static char * stx_build_mergelist_proc (THREAD_ENTRY *thread_p, char *tmp, MERGELIST_PROC_NODE *ptr)
static char * stx_build_ls_merge_info (THREAD_ENTRY *thread_p, char *tmp, QFILE_LIST_MERGE_INFO *ptr)
static char * stx_build_update_class_info (THREAD_ENTRY *thread_p, char *tmp, UPDDEL_CLASS_INFO *ptr)
static char * stx_build_update_assignment (THREAD_ENTRY *thread_p, char *tmp, UPDATE_ASSIGNMENT *ptr)
static char * stx_build_update_proc (THREAD_ENTRY *thread_p, char *tmp, UPDATE_PROC_NODE *ptr)
static char * stx_build_delete_proc (THREAD_ENTRY *thread_p, char *tmp, DELETE_PROC_NODE *ptr)
static char * stx_build_insert_proc (THREAD_ENTRY *thread_p, char *tmp, INSERT_PROC_NODE *ptr)
static char * stx_build_merge_proc (THREAD_ENTRY *thread_p, char *tmp, MERGE_PROC_NODE *ptr)
static char * stx_build_cte_proc (THREAD_ENTRY *thread_p, char *tmp, CTE_PROC_NODE *ptr)
static char * stx_build_outptr_list (THREAD_ENTRY *thread_p, char *tmp, OUTPTR_LIST *ptr)
static char * stx_build_selupd_list (THREAD_ENTRY *thread_p, char *tmp, SELUPD_LIST *ptr)
static char * stx_build_pred_expr (THREAD_ENTRY *thread_p, char *tmp, PRED_EXPR *ptr)
static char * stx_build_pred (THREAD_ENTRY *thread_p, char *tmp, PRED *ptr)
static char * stx_build_eval_term (THREAD_ENTRY *thread_p, char *tmp, EVAL_TERM *ptr)
static char * stx_build_comp_eval_term (THREAD_ENTRY *thread_p, char *tmp, COMP_EVAL_TERM *ptr)
static char * stx_build_alsm_eval_term (THREAD_ENTRY *thread_p, char *tmp, ALSM_EVAL_TERM *ptr)
static char * stx_build_like_eval_term (THREAD_ENTRY *thread_p, char *tmp, LIKE_EVAL_TERM *ptr)
static char * stx_build_rlike_eval_term (THREAD_ENTRY *thread_p, char *tmp, RLIKE_EVAL_TERM *ptr)
static char * stx_build_access_spec_type (THREAD_ENTRY *thread_p, char *tmp, ACCESS_SPEC_TYPE *ptr, void *arg)
static char * stx_build_indx_info (THREAD_ENTRY *thread_p, char *tmp, INDX_INFO *ptr)
static char * stx_build_key_info (THREAD_ENTRY *thread_p, char *tmp, KEY_INFO *ptr)
static char * stx_build_cls_spec_type (THREAD_ENTRY *thread_p, char *tmp, CLS_SPEC_TYPE *ptr)
static char * stx_build_list_spec_type (THREAD_ENTRY *thread_p, char *tmp, LIST_SPEC_TYPE *ptr)
static char * stx_build_showstmt_spec_type (THREAD_ENTRY *thread_p, char *ptr, SHOWSTMT_SPEC_TYPE *spec)
static char * stx_build_rlist_spec_type (THREAD_ENTRY *thread_p, char *ptr, REGUVAL_LIST_SPEC_TYPE *spec, OUTPTR_LIST *outptr_list)
static char * stx_build_set_spec_type (THREAD_ENTRY *thread_p, char *tmp, SET_SPEC_TYPE *ptr)
static char * stx_build_method_spec_type (THREAD_ENTRY *thread_p, char *tmp, METHOD_SPEC_TYPE *ptr)
static char * stx_build_val_list (THREAD_ENTRY *thread_p, char *tmp, VAL_LIST *ptr)
static char * stx_build_regu_variable (THREAD_ENTRY *thread_p, char *tmp, REGU_VARIABLE *ptr)
static char * stx_unpack_regu_variable_value (THREAD_ENTRY *thread_p, char *tmp, REGU_VARIABLE *ptr)
static char * stx_build_attr_descr (THREAD_ENTRY *thread_p, char *tmp, ATTR_DESCR *ptr)
static char * stx_build_pos_descr (char *tmp, QFILE_TUPLE_VALUE_POSITION *ptr)
static char * stx_build_arith_type (THREAD_ENTRY *thread_p, char *tmp, ARITH_TYPE *ptr)
static char * stx_build_aggregate_type (THREAD_ENTRY *thread_p, char *tmp, AGGREGATE_TYPE *ptr)
static char * stx_build_function_type (THREAD_ENTRY *thread_p, char *tmp, FUNCTION_TYPE *ptr)
static char * stx_build_analytic_type (THREAD_ENTRY *thread_p, char *tmp, ANALYTIC_TYPE *ptr)
static char * stx_build_analytic_eval_type (THREAD_ENTRY *thread_p, char *tmp, ANALYTIC_EVAL_TYPE *ptr)
static char * stx_build_srlist_id (THREAD_ENTRY *thread_p, char *tmp, QFILE_SORTED_LIST_ID *ptr)
static char * stx_build_sort_list (THREAD_ENTRY *thread_p, char *tmp, SORT_LIST *ptr)
static char * stx_build_connectby_proc (THREAD_ENTRY *thread_p, char *tmp, CONNECTBY_PROC_NODE *ptr)
static REGU_VALUE_LIST * stx_regu_value_list_alloc_and_init (THREAD_ENTRY *thread_p)
static REGU_VALUE_ITEM * stx_regu_value_item_alloc_and_init (THREAD_ENTRY *thread_p)
static char * stx_build_regu_value_list (THREAD_ENTRY *thread_p, char *ptr, REGU_VALUE_LIST *regu_value_list, TP_DOMAIN *domain)
static void stx_init_regu_variable (REGU_VARIABLE *regu)
static char * stx_build_regu_variable_list (THREAD_ENTRY *thread_p, char *ptr, REGU_VARIABLE_LIST *regu_var_list)
int stx_map_stream_to_xasl_node_header (THREAD_ENTRY *thread_p, xasl_node_header *xasl_header_p, char *xasl_stream)
int stx_map_stream_to_xasl (THREAD_ENTRY *thread_p, xasl_node **xasl_tree, bool use_xasl_clone, char *xasl_stream, int xasl_stream_size, XASL_UNPACK_INFO **xasl_unpack_info_ptr)
int stx_map_stream_to_filter_pred (THREAD_ENTRY *thread_p, pred_expr_with_context **pred, char *pred_stream, int pred_stream_size)
int stx_map_stream_to_func_pred (THREAD_ENTRY *thread_p, func_pred **xasl, char *xasl_stream, int xasl_stream_size, XASL_UNPACK_INFO **xasl_unpack_info_ptr)
static HFID * stx_restore_hfid_array (THREAD_ENTRY *thread_p, char *ptr, int nelements)
char * stx_build (THREAD_ENTRY *thread_p, char *ptr, regu_variable_node &reguvar)
Function Documentation
char* stx_build (THREAD_ENTRY * thread_p, char * ptr, regu_variable_node & reguvar)
Definition at line 6380 of file stream_to_xasl.c.
References stx_build_regu_variable().
Referenced by stx_build_access_spec_type(), and xts_debug_check().
static char * stx_build_access_spec_type (THREAD_ENTRY * thread_p, char * tmp, ACCESS_SPEC_TYPE * ptr, void * arg) static
Definition at line 4247 of file stream_to_xasl.c.
References access_spec_node::access, ACCESS_SPEC_CLS_SPEC, ACCESS_SPEC_JSON_TABLE_SPEC, ACCESS_SPEC_LIST_SPEC, ACCESS_SPEC_METHOD_SPEC, ACCESS_SPEC_RLIST_SPEC, ACCESS_SPEC_SET_SPEC, ACCESS_SPEC_SHOWSTMT_SPEC, indx_info::btid, access_spec_node::btid, ER_OUT_OF_VIRTUAL_MEMORY, ER_QPROC_INVALID_XASLNODE, error(), access_spec_node::flags, get_xasl_unpack_info_ptr(), access_spec_node::indexptr, hybrid_node::json_table_node, NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, access_spec_node::pruning_type, access_spec_node::s, S_CLOSED, access_spec_node::s_dbval, S_JSON_TABLE_SCAN, access_spec_node::single_fetch, stx_build(), stx_build_cls_spec_type(), stx_build_list_spec_type(), stx_build_method_spec_type(), stx_build_rlist_spec_type(), stx_build_set_spec_type(), stx_build_showstmt_spec_type(), stx_restore_db_value(), stx_restore_indx_info(), stx_restore_pred_expr(), stx_set_xasl_errcode(), TARGET_CLASS, TARGET_CLASS_ATTR, TARGET_JSON_TABLE, TARGET_LIST, TARGET_METHOD, TARGET_REGUVAL_LIST, TARGET_SET, TARGET_SHOWSTMT, access_spec_node::type, xasl_unpack_info::use_xasl_clone, access_spec_node::where_key, access_spec_node::where_pred, and access_spec_node::where_range.
Referenced by stx_restore_access_spec_type().
static char * stx_build_aggregate_type (THREAD_ENTRY * thread_p, char * tmp, AGGREGATE_TYPE * ptr) static
Definition at line 5470 of file stream_to_xasl.c.
References cubxasl::aggregate_list_node::accumulator, assert, cubxasl::aggregate_list_node::btid, cubxasl::aggregate_accumulator::clear_value2_at_clone_decache, cubxasl::aggregate_accumulator::clear_value_at_clone_decache, cubxasl::aggregate_accumulator::curr_cnt, db_value_is_null(), cubxasl::aggregate_list_node::domain, ER_OUT_OF_VIRTUAL_MEMORY, error(), cubxasl::aggregate_list_node::flag_agg_optimize, cubxasl::aggregate_list_node::function, get_xasl_unpack_info_ptr(), cubxasl::aggregate_list_node::info, cubxasl::aggregate_list_node::list_id, cubxasl::aggregate_list_node::next, NULL, cubxasl::aggregate_list_node::operands, cubxasl::aggregate_list_node::opr_dbtype, cubxasl::aggregate_list_node::option, or_unpack_btid(), or_unpack_domain(), or_unpack_int(), cubxasl::aggregate_list_node::original_domain, cubxasl::aggregate_list_node::original_opr_dbtype, xasl_unpack_info::packed_xasl, cubxasl::aggregate_specific_function_info::percentile, cubxasl::aggregate_percentile_info::percentile_reguvar, PT_CUME_DIST, PT_PERCENT_RANK, PT_PERCENTILE_CONT, PT_PERCENTILE_DISC, cubxasl::aggregate_list_node::sort_list, stx_build_regu_variable_list(), stx_restore_aggregate_type(), stx_restore_db_value(), stx_restore_list_id(), stx_restore_regu_variable(), stx_restore_sort_list(), stx_set_xasl_errcode(), xasl_unpack_info::use_xasl_clone, cubxasl::aggregate_accumulator::value, and cubxasl::aggregate_accumulator::value2.
Referenced by stx_restore_aggregate_type().
static char * stx_build_alsm_eval_term (THREAD_ENTRY * thread_p, char * tmp, ALSM_EVAL_TERM * ptr) static
Definition at line 4084 of file stream_to_xasl.c.
References cubxasl::alsm_eval_term::elem, cubxasl::alsm_eval_term::elemset, cubxasl::alsm_eval_term::eq_flag, ER_OUT_OF_VIRTUAL_MEMORY, get_xasl_unpack_info_ptr(), cubxasl::alsm_eval_term::item_type, NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, cubxasl::alsm_eval_term::rel_op, stx_restore_regu_variable(), and stx_set_xasl_errcode().
Referenced by stx_build_eval_term().
static char * stx_build_analytic_eval_type (THREAD_ENTRY * thread_p, char * tmp, ANALYTIC_EVAL_TYPE * ptr) static
Definition at line 5850 of file stream_to_xasl.c.
References assert, ER_OUT_OF_VIRTUAL_MEMORY, error(), get_xasl_unpack_info_ptr(), cubxasl::analytic_eval_type::head, cubxasl::analytic_eval_type::next, NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, cubxasl::analytic_eval_type::sort_list, stx_restore_analytic_eval_type(), stx_restore_analytic_type(), stx_restore_sort_list(), and stx_set_xasl_errcode().
Referenced by stx_restore_analytic_eval_type().
static char * stx_build_analytic_type (THREAD_ENTRY * thread_p, char * tmp, ANALYTIC_TYPE * ptr) static
Definition at line 5681 of file stream_to_xasl.c.
References assert, bool, cubxasl::analytic_list_node::default_idx, cubxasl::analytic_list_node::domain, ER_OUT_OF_VIRTUAL_MEMORY, error(), cubxasl::analytic_list_node::flag, cubxasl::analytic_list_node::from_last, cubxasl::analytic_list_node::function, get_xasl_unpack_info_ptr(), cubxasl::analytic_list_node::ignore_nulls, cubxasl::analytic_list_node::info, cubxasl::analytic_list_node::is_const_operand, cubxasl::analytic_list_node::list_id, db_value::need_clear, cubxasl::analytic_list_node::next, NULL, cubxasl::analytic_list_node::offset_idx, cubxasl::analytic_list_node::operand, cubxasl::analytic_list_node::opr_dbtype, cubxasl::analytic_list_node::option, or_unpack_domain(), or_unpack_int(), cubxasl::analytic_list_node::original_domain, cubxasl::analytic_list_node::original_opr_dbtype, cubxasl::analytic_list_node::out_value, xasl_unpack_info::packed_xasl, cubxasl::analytic_function_info::percentile, cubxasl::analytic_percentile_function_info::percentile_reguvar, PT_PERCENTILE_CONT, PT_PERCENTILE_DISC, cubxasl::analytic_list_node::sort_list_size, cubxasl::analytic_list_node::sort_prefix_size, stx_build_regu_variable(), stx_restore_analytic_type(), stx_restore_db_value(), stx_restore_list_id(), stx_restore_regu_variable(), stx_set_xasl_errcode(), cubxasl::analytic_list_node::value, and cubxasl::analytic_list_node::value2.
Referenced by stx_restore_analytic_type().
static char * stx_build_arith_type (THREAD_ENTRY * thread_p, char * tmp, ARITH_TYPE * ptr) static
Definition at line 5365 of file stream_to_xasl.c.
References assert, arith_list_node::domain, ER_OUT_OF_VIRTUAL_MEMORY, error(), get_xasl_unpack_info_ptr(), arith_list_node::leftptr, arith_list_node::misc_operand, db_value::need_clear, NULL, arith_list_node::opcode, or_unpack_domain(), or_unpack_int(), arith_list_node::original_domain, xasl_unpack_info::packed_xasl, arith_list_node::pred, arith_list_node::rand_seed, arith_list_node::rightptr, stx_restore_db_value(), stx_restore_pred_expr(), stx_restore_regu_variable(), stx_set_xasl_errcode(), T_CASE, T_DECODE, T_IF, T_PREDICATE, arith_list_node::thirdptr, and arith_list_node::value.
Referenced by stx_restore_arith_type().
static char * stx_build_attr_descr (THREAD_ENTRY * thread_p, char * tmp, ATTR_DESCR * ptr) static
Definition at line 5323 of file stream_to_xasl.c.
References attr_descr_node::cache_attrinfo, attr_descr_node::cache_dbvalp, ER_OUT_OF_VIRTUAL_MEMORY, get_xasl_unpack_info_ptr(), attr_descr_node::id, NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, stx_restore_cache_attrinfo(), stx_set_xasl_errcode(), and attr_descr_node::type.
Referenced by stx_unpack_regu_variable_value().
static char * stx_build_buildlist_proc (THREAD_ENTRY * thread_p, char * tmp, BUILDLIST_PROC_NODE * ptr) static
Definition at line 2552 of file stream_to_xasl.c.
References buildlist_proc_node::a_eval_list, buildlist_proc_node::a_outptr_list, buildlist_proc_node::a_outptr_list_ex, buildlist_proc_node::a_outptr_list_interm, buildlist_proc_node::a_regu_list, buildlist_proc_node::a_val_list, buildlist_proc_node::after_groupby_list, assert, buildlist_proc_node::eptr_list, ER_OUT_OF_VIRTUAL_MEMORY, error(), buildlist_proc_node::g_agg_list, buildlist_proc_node::g_func_count, buildlist_proc_node::g_grbynum_flag, buildlist_proc_node::g_grbynum_pred, buildlist_proc_node::g_grbynum_val, buildlist_proc_node::g_hash_eligible, buildlist_proc_node::g_having_pred, buildlist_proc_node::g_hk_scan_regu_list, buildlist_proc_node::g_hk_sort_regu_list, buildlist_proc_node::g_hkey_size, buildlist_proc_node::g_outptr_list, buildlist_proc_node::g_output_first_tuple, buildlist_proc_node::g_regu_list, buildlist_proc_node::g_scan_regu_list, buildlist_proc_node::g_val_list, buildlist_proc_node::g_with_rollup, get_xasl_unpack_info_ptr(), buildlist_proc_node::groupby_list, db_value::need_clear, NULL, or_unpack_int(), buildlist_proc_node::output_columns, xasl_unpack_info::packed_xasl, buildlist_proc_node::push_list_id, stx_alloc_struct(), stx_restore_aggregate_type(), stx_restore_analytic_eval_type(), stx_restore_db_value(), stx_restore_list_id(), stx_restore_outptr_list(), stx_restore_pred_expr(), stx_restore_regu_variable_list(), stx_restore_sort_list(), stx_restore_val_list(), stx_restore_xasl_node(), and stx_set_xasl_errcode().
Referenced by stx_build_xasl_node().
static char * stx_build_buildvalue_proc (THREAD_ENTRY * thread_p, char * tmp, BUILDVALUE_PROC_NODE * ptr) static
Definition at line 2870 of file stream_to_xasl.c.
References buildvalue_proc_node::agg_list, assert, ER_OUT_OF_VIRTUAL_MEMORY, get_xasl_unpack_info_ptr(), buildvalue_proc_node::grbynum_val, buildvalue_proc_node::having_pred, buildvalue_proc_node::is_always_false, db_value::need_clear, NULL, or_unpack_int(), buildvalue_proc_node::outarith_list, xasl_unpack_info::packed_xasl, stx_restore_aggregate_type(), stx_restore_arith_type(), stx_restore_db_value(), stx_restore_pred_expr(), and stx_set_xasl_errcode().
Referenced by stx_build_xasl_node().
static char * stx_build_cache_attrinfo (char * tmp) static
Definition at line 2317 of file stream_to_xasl.c.
References or_unpack_int().
Referenced by stx_restore_cache_attrinfo().
static char * stx_build_cls_spec_type (THREAD_ENTRY * thread_p, char * tmp, CLS_SPEC_TYPE * ptr) static
Definition at line 4544 of file stream_to_xasl.c.
References cls_spec_node::attrids_key, cls_spec_node::attrids_pred, cls_spec_node::attrids_range, cls_spec_node::attrids_rest, cls_spec_node::cache_key, cls_spec_node::cache_pred, cls_spec_node::cache_range, cls_spec_node::cache_reserved, cls_spec_node::cache_rest, cls_spec_node::cls_oid, cls_spec_node::cls_output_val_list, cls_spec_node::cls_regu_list_key, cls_spec_node::cls_regu_list_pred, cls_spec_node::cls_regu_list_range, cls_spec_node::cls_regu_list_reserved, cls_spec_node::cls_regu_list_rest, cls_spec_node::cls_regu_val_list, ER_OUT_OF_VIRTUAL_MEMORY, error(), get_xasl_unpack_info_ptr(), cls_spec_node::hfid, NULL, cls_spec_node::num_attrs_key, cls_spec_node::num_attrs_pred, cls_spec_node::num_attrs_range, cls_spec_node::num_attrs_reserved, cls_spec_node::num_attrs_rest, or_unpack_hfid(), or_unpack_int(), or_unpack_oid(), xasl_unpack_info::packed_xasl, cls_spec_node::schema_type, stx_restore_cache_attrinfo(), stx_restore_db_value_array_extra(), stx_restore_int_array(), stx_restore_outptr_list(), stx_restore_regu_variable_list(), and stx_set_xasl_errcode().
Referenced by stx_build_access_spec_type().
static char * stx_build_comp_eval_term (THREAD_ENTRY * thread_p, char * tmp, COMP_EVAL_TERM * ptr) static
Definition at line 4039 of file stream_to_xasl.c.
References ER_OUT_OF_VIRTUAL_MEMORY, get_xasl_unpack_info_ptr(), cubxasl::comp_eval_term::lhs, NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, cubxasl::comp_eval_term::rel_op, cubxasl::comp_eval_term::rhs, stx_restore_regu_variable(), stx_set_xasl_errcode(), and cubxasl::comp_eval_term::type.
Referenced by stx_build_eval_term().
static char * stx_build_connectby_proc (THREAD_ENTRY * thread_p, char * tmp, CONNECTBY_PROC_NODE * ptr) static
Definition at line 5963 of file stream_to_xasl.c.
References connectby_proc_node::after_cb_regu_list_pred, connectby_proc_node::after_cb_regu_list_rest, connectby_proc_node::after_connect_by_pred, bool, connectby_proc_node::curr_tuple, ER_OUT_OF_VIRTUAL_MEMORY, error(), get_xasl_unpack_info_ptr(), connectby_proc_node::input_list_id, NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, connectby_proc_node::prior_outptr_list, connectby_proc_node::prior_regu_list_pred, connectby_proc_node::prior_regu_list_rest, connectby_proc_node::prior_val_list, connectby_proc_node::regu_list_pred, connectby_proc_node::regu_list_rest, connectby_proc_node::single_table_opt, connectby_proc_node::start_with_list_id, connectby_proc_node::start_with_pred, stx_restore_list_id(), stx_restore_outptr_list(), stx_restore_pred_expr(), stx_restore_regu_variable_list(), stx_restore_val_list(), and stx_set_xasl_errcode().
Referenced by stx_build_xasl_node().
static char * stx_build_cte_proc (THREAD_ENTRY * thread_p, char * tmp, CTE_PROC_NODE * ptr) static
Definition at line 3775 of file stream_to_xasl.c.
References ER_OUT_OF_VIRTUAL_MEMORY, error(), get_xasl_unpack_info_ptr(), cte_proc_node::non_recursive_part, NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, cte_proc_node::recursive_part, stx_restore_xasl_node(), and stx_set_xasl_errcode().
Referenced by stx_build_xasl_node().
static char * stx_build_delete_proc (THREAD_ENTRY * thread_p, char * tmp, DELETE_PROC_NODE * ptr) static
Definition at line 3544 of file stream_to_xasl.c.
References delete_proc_node::classes, ER_OUT_OF_VIRTUAL_MEMORY, error(), get_xasl_unpack_info_ptr(), delete_proc_node::mvcc_reev_classes, delete_proc_node::no_logging, NULL, delete_proc_node::num_classes, delete_proc_node::num_reev_classes, or_unpack_int(), xasl_unpack_info::packed_xasl, stx_restore_int_array(), stx_restore_update_class_info_array(), stx_set_xasl_errcode(), and delete_proc_node::wait_msecs.
Referenced by stx_build_xasl_node().
static char * stx_build_eval_term (THREAD_ENTRY * thread_p, char * tmp, EVAL_TERM * ptr) static
Definition at line 4005 of file stream_to_xasl.c.
References ER_QPROC_INVALID_XASLNODE, cubxasl::eval_term::et, cubxasl::eval_term::et_alsm, cubxasl::eval_term::et_comp, cubxasl::eval_term::et_like, cubxasl::eval_term::et_rlike, cubxasl::eval_term::et_type, NULL, or_unpack_int(), stx_build_alsm_eval_term(), stx_build_comp_eval_term(), stx_build_like_eval_term(), stx_build_rlike_eval_term(), stx_set_xasl_errcode(), T_ALSM_EVAL_TERM, T_COMP_EVAL_TERM, T_LIKE_EVAL_TERM, and T_RLIKE_EVAL_TERM.
Referenced by stx_build_pred_expr().
static char * stx_build_fetch_proc (THREAD_ENTRY * thread_p, char * tmp, FETCH_PROC_NODE * ptr) static
Definition at line 2505 of file stream_to_xasl.c.
References fetch_proc_node::arg, assert, bool, ER_OUT_OF_VIRTUAL_MEMORY, fetch_proc_node::fetch_res, get_xasl_unpack_info_ptr(), i, db_value::need_clear, NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, fetch_proc_node::ql_flag, fetch_proc_node::set_pred, stx_restore_db_value(), stx_restore_pred_expr(), and stx_set_xasl_errcode().
Referenced by stx_build_xasl_node().
static char * stx_build_filter_pred_node (THREAD_ENTRY * thread_p, char * ptr, PRED_EXPR_WITH_CONTEXT * pred) static
Definition at line 2221 of file stream_to_xasl.c.
References pred_expr_with_context::attrids_pred, pred_expr_with_context::cache_pred, ER_OUT_OF_VIRTUAL_MEMORY, error(), get_xasl_unpack_info_ptr(), NULL, pred_expr_with_context::num_attrs_pred, or_unpack_int(), xasl_unpack_info::packed_xasl, pred_expr_with_context::pred, stx_restore_cache_attrinfo(), stx_restore_int_array(), stx_restore_pred_expr(), and stx_set_xasl_errcode().
Referenced by stx_restore_filter_pred_node().
static char * stx_build_func_pred (THREAD_ENTRY * thread_p, char * tmp, FUNC_PRED * ptr) static
Definition at line 2277 of file stream_to_xasl.c.
References func_pred::cache_attrinfo, ER_OUT_OF_VIRTUAL_MEMORY, error(), func_pred::func_regu, get_xasl_unpack_info_ptr(), NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, stx_restore_cache_attrinfo(), stx_restore_regu_variable(), and stx_set_xasl_errcode().
Referenced by stx_restore_func_pred().
static char * stx_build_function_type (THREAD_ENTRY * thread_p, char * tmp, FUNCTION_TYPE * ptr) static
Definition at line 5636 of file stream_to_xasl.c.
References assert, ER_OUT_OF_VIRTUAL_MEMORY, get_xasl_unpack_info_ptr(), NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, stx_restore_db_value(), stx_restore_regu_variable_list(), and stx_set_xasl_errcode().
Referenced by stx_restore_function_type().
static char * stx_build_indx_info (THREAD_ENTRY * thread_p, char * tmp, INDX_INFO * ptr) static
Definition at line 4415 of file stream_to_xasl.c.
References indx_info::btid, indx_info::coverage, ER_OUT_OF_VIRTUAL_MEMORY, indx_info::func_idx_col_id, get_xasl_unpack_info_ptr(), indx_info::groupby_desc, indx_info::groupby_skip, indx_info::ils_prefix_len, indx_info::iss_range, key_range::key1, key_range::key2, indx_info::key_info, NULL, or_unpack_btid(), or_unpack_int(), indx_info::orderby_desc, indx_info::orderby_skip, xasl_unpack_info::packed_xasl, key_range::range, indx_info::range_type, stx_build_key_info(), stx_restore_regu_variable(), stx_set_xasl_errcode(), indx_info::use_desc_index, and indx_info::use_iss.
Referenced by stx_restore_indx_info().
static char * stx_build_insert_proc (THREAD_ENTRY * thread_p, char * tmp, INSERT_PROC_NODE * ptr) static
Definition at line 3595 of file stream_to_xasl.c.
References assert, insert_proc_node::att_id, insert_proc_node::class_hfid, insert_proc_node::class_oid, insert_proc_node::cons_pred, insert_proc_node::do_replace, ER_OUT_OF_VIRTUAL_MEMORY, error(), get_xasl_unpack_info_ptr(), insert_proc_node::has_uniques, i, db_value::need_clear, insert_proc_node::no_logging, NULL, insert_proc_node::num_default_expr, insert_proc_node::num_val_lists, insert_proc_node::num_vals, insert_proc_node::obj_oid, insert_proc_node::odku, or_unpack_hfid(), or_unpack_int(), or_unpack_oid(), xasl_unpack_info::packed_xasl, insert_proc_node::pruning_type, stx_alloc_struct(), stx_restore_db_value(), stx_restore_int_array(), stx_restore_odku_info(), stx_restore_outptr_list(), stx_restore_pred_expr(), stx_set_xasl_errcode(), insert_proc_node::valptr_lists, insert_proc_node::vals, and insert_proc_node::wait_msecs.
Referenced by stx_build_xasl_node().
static char * stx_build_key_info (THREAD_ENTRY * thread_p, char * tmp, KEY_INFO * ptr) static
Definition at line 4477 of file stream_to_xasl.c.
References bool, ER_OUT_OF_VIRTUAL_MEMORY, get_xasl_unpack_info_ptr(), i, key_info::is_constant, key_info::is_user_given_keylimit, key_info::key_cnt, key_info::key_limit_l, key_info::key_limit_reset, key_info::key_limit_u, key_info::key_ranges, NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, stx_restore_key_range_array(), stx_restore_regu_variable(), and stx_set_xasl_errcode().
Referenced by stx_build_indx_info().
static char * stx_build_like_eval_term (THREAD_ENTRY * thread_p, char * tmp, LIKE_EVAL_TERM * ptr) static
Definition at line 4132 of file stream_to_xasl.c.
References ER_OUT_OF_VIRTUAL_MEMORY, error(), cubxasl::like_eval_term::esc_char, get_xasl_unpack_info_ptr(), NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, cubxasl::like_eval_term::pattern, cubxasl::like_eval_term::src, stx_restore_regu_variable(), and stx_set_xasl_errcode().
Referenced by stx_build_eval_term().
static char * stx_build_list_id (THREAD_ENTRY * thread_p, char * tmp, QFILE_LIST_ID * ptr) static
Definition at line 2328 of file stream_to_xasl.c.
References assert_release, cubregex::count(), db_private_alloc, qfile_tuple_value_type_list::domp, ER_OUT_OF_VIRTUAL_MEMORY, error(), i, NULL, or_unpack_domain(), or_unpack_listid(), stx_set_xasl_errcode(), qfile_tuple_value_type_list::type_cnt, and qfile_list_id::type_list.
Referenced by stx_restore_list_id().
static char * stx_build_list_spec_type (THREAD_ENTRY * thread_p, char * tmp, LIST_SPEC_TYPE * ptr) static
Definition at line 4800 of file stream_to_xasl.c.
References ER_OUT_OF_VIRTUAL_MEMORY, error(), get_xasl_unpack_info_ptr(), list_spec_node::hash_list_scan_yn, list_spec_node::list_regu_list_build, list_spec_node::list_regu_list_pred, list_spec_node::list_regu_list_probe, list_spec_node::list_regu_list_rest, NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, stx_restore_regu_variable_list(), stx_restore_xasl_node(), stx_set_xasl_errcode(), and list_spec_node::xasl_node.
Referenced by stx_build_access_spec_type().
static char * stx_build_ls_merge_info (THREAD_ENTRY * thread_p, char * tmp, QFILE_LIST_MERGE_INFO * ptr) static
Definition at line 3022 of file stream_to_xasl.c.
References ER_OUT_OF_VIRTUAL_MEMORY, error(), get_xasl_unpack_info_ptr(), qfile_list_merge_info::join_type, qfile_list_merge_info::ls_column_cnt, qfile_list_merge_info::ls_inner_column, qfile_list_merge_info::ls_inner_unique, qfile_list_merge_info::ls_outer_column, qfile_list_merge_info::ls_outer_inner_list, qfile_list_merge_info::ls_outer_unique, qfile_list_merge_info::ls_pos_cnt, qfile_list_merge_info::ls_pos_list, NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, qfile_list_merge_info::single_fetch, stx_restore_int_array(), and stx_set_xasl_errcode().
Referenced by stx_build_mergelist_proc(), and stx_restore_cache_attrinfo().
static char * stx_build_merge_proc (THREAD_ENTRY * thread_p, char * tmp, MERGE_PROC_NODE * ptr) static
Definition at line 3730 of file stream_to_xasl.c.
References bool, ER_OUT_OF_VIRTUAL_MEMORY, error(), get_xasl_unpack_info_ptr(), merge_proc_node::has_delete, merge_proc_node::insert_xasl, NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, stx_restore_xasl_node(), stx_set_xasl_errcode(), and merge_proc_node::update_xasl.
Referenced by stx_build_xasl_node().
static char * stx_build_mergelist_proc (THREAD_ENTRY * thread_p, char * tmp, MERGELIST_PROC_NODE * ptr) static
Definition at line 2942 of file stream_to_xasl.c.
References ER_OUT_OF_VIRTUAL_MEMORY, ER_QPROC_INVALID_XASLNODE, error(), get_xasl_unpack_info_ptr(), mergelist_proc_node::inner_spec_list, mergelist_proc_node::inner_val_list, mergelist_proc_node::inner_xasl, mergelist_proc_node::ls_merge, NULL, or_unpack_int(), mergelist_proc_node::outer_spec_list, mergelist_proc_node::outer_val_list, mergelist_proc_node::outer_xasl, xasl_unpack_info::packed_xasl, stx_build_ls_merge_info(), stx_restore_access_spec_type(), stx_restore_val_list(), stx_restore_xasl_node(), and stx_set_xasl_errcode().
Referenced by stx_build_xasl_node().
static char * stx_build_method_sig (THREAD_ENTRY * thread_p, char * tmp, METHOD_SIG * ptr, int size) static
Definition at line 2412 of file stream_to_xasl.c.
References assert, method_sig_node::class_name, ER_OUT_OF_VIRTUAL_MEMORY, error(), get_xasl_unpack_info_ptr(), method_sig_node::method_arg_pos, method_sig_node::method_name, method_sig_node::method_type, method_sig_node::next, NULL, method_sig_node::num_method_args, or_unpack_int(), xasl_unpack_info::packed_xasl, stx_alloc_struct(), stx_restore_method_sig(), stx_restore_string(), and stx_set_xasl_errcode().
Referenced by stx_restore_method_sig().
static char * stx_build_method_sig_list (THREAD_ENTRY * thread_p, char * tmp, METHOD_SIG_LIST * ptr) static
Definition at line 2369 of file stream_to_xasl.c.
References assert, ER_OUT_OF_VIRTUAL_MEMORY, error(), get_xasl_unpack_info_ptr(), i, method_sig_list::method_sig, method_sig_node::next, NULL, method_sig_list::num_methods, or_unpack_int(), xasl_unpack_info::packed_xasl, stx_restore_method_sig(), and stx_set_xasl_errcode().
Referenced by stx_restore_method_sig_list().
static char * stx_build_method_spec_type (THREAD_ENTRY * thread_p, char * tmp, METHOD_SPEC_TYPE * ptr) static
Definition at line 4974 of file stream_to_xasl.c.
References ER_OUT_OF_VIRTUAL_MEMORY, get_xasl_unpack_info_ptr(), method_spec_node::method_regu_list, method_spec_node::method_sig_list, NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, stx_restore_method_sig_list(), stx_restore_regu_variable_list(), stx_restore_xasl_node(), stx_set_xasl_errcode(), and method_spec_node::xasl_node.
Referenced by stx_build_access_spec_type().
static char * stx_build_outptr_list (THREAD_ENTRY * thread_p, char * tmp, OUTPTR_LIST * ptr) static
Definition at line 3817 of file stream_to_xasl.c.
References ER_OUT_OF_VIRTUAL_MEMORY, get_xasl_unpack_info_ptr(), NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, stx_restore_regu_variable_list(), stx_set_xasl_errcode(), valptr_list_node::valptr_cnt, and valptr_list_node::valptrp.
Referenced by stx_restore_outptr_list().
static char * stx_build_pos_descr (char * tmp, QFILE_TUPLE_VALUE_POSITION * ptr) static
Definition at line 5355 of file stream_to_xasl.c.
References qfile_tuple_value_position::dom, NULL, or_unpack_domain(), or_unpack_int(), qfile_tuple_value_position::original_domain, and qfile_tuple_value_position::pos_no.
Referenced by stx_build_sort_list(), and stx_unpack_regu_variable_value().
static char * stx_build_pred (THREAD_ENTRY * thread_p, char * tmp, PRED * ptr) static
Definition at line 3919 of file stream_to_xasl.c.
References cubxasl::pred::bool_op, ER_OUT_OF_VIRTUAL_MEMORY, error(), get_xasl_unpack_info_ptr(), cubxasl::pred::lhs, cubxasl::pred_expr::m_pred, NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, cubxasl::pred_expr::pe, cubxasl::pred::rhs, stx_alloc_struct(), stx_restore_pred_expr(), stx_set_xasl_errcode(), T_PRED, and cubxasl::pred_expr::type.
Referenced by stx_build_pred_expr().
static char * stx_build_pred_expr (THREAD_ENTRY * thread_p, char * tmp, PRED_EXPR * ptr) static
Definition at line 3875 of file stream_to_xasl.c.
References ER_OUT_OF_VIRTUAL_MEMORY, ER_QPROC_INVALID_XASLNODE, get_xasl_unpack_info_ptr(), cubxasl::pred_expr::m_eval_term, cubxasl::pred_expr::m_not_term, cubxasl::pred_expr::m_pred, NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, cubxasl::pred_expr::pe, stx_build_eval_term(), stx_build_pred(), stx_restore_pred_expr(), stx_set_xasl_errcode(), T_EVAL_TERM, T_NOT_TERM, T_PRED, and cubxasl::pred_expr::type.
Referenced by stx_restore_pred_expr().
static char * stx_build_regu_value_list (THREAD_ENTRY * thread_p, char * ptr, REGU_VALUE_LIST * regu_value_list, TP_DOMAIN * domain) static
Definition at line 6213 of file stream_to_xasl.c.
References assert, regu_value_list::count, cubregex::count(), regu_value_list::current_value, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, ER_QPROC_INVALID_XASLNODE, error(), i, regu_value_item::next, NULL, or_unpack_int(), regu_value_list::regu_list, stx_alloc_struct(), stx_get_struct_visited_ptr(), stx_init_regu_variable(), stx_mark_struct_visited(), stx_regu_value_item_alloc_and_init(), stx_set_xasl_errcode(), stx_unpack_regu_variable_value(), TYPE_DBVAL, TYPE_INARITH, TYPE_POS_VALUE, and regu_value_item::value.
Referenced by stx_unpack_regu_variable_value().
static char * stx_build_regu_variable (THREAD_ENTRY * thread_p, char * tmp, REGU_VARIABLE * ptr) static
Definition at line 5122 of file stream_to_xasl.c.
References assert, ER_OUT_OF_VIRTUAL_MEMORY, error(), get_xasl_unpack_info_ptr(), NULL, or_unpack_domain(), or_unpack_int(), xasl_unpack_info::packed_xasl, REGU_VARIABLE_FETCH_ALL_CONST, REGU_VARIABLE_FETCH_NOT_CONST, REGU_VARIABLE_IS_FLAGED(), stx_restore_db_value(), stx_restore_xasl_node(), stx_set_xasl_errcode(), and stx_unpack_regu_variable_value().
Referenced by stx_build(), stx_build_analytic_type(), stx_restore_regu_variable(), and stx_restore_regu_variable_list().
static char * stx_build_regu_variable_list (THREAD_ENTRY * thread_p, char * ptr, REGU_VARIABLE_LIST * regu_var_list) static
Definition at line 6301 of file stream_to_xasl.c.
References assert, get_xasl_unpack_info_ptr(), NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, and stx_restore_regu_variable_list().
Referenced by stx_build_aggregate_type(), and stx_unpack_regu_variable_value().
static char * stx_build_rlike_eval_term (THREAD_ENTRY * thread_p, char * tmp, RLIKE_EVAL_TERM * ptr) static
Definition at line 4187 of file stream_to_xasl.c.
References cubxasl::rlike_eval_term::case_sensitive, cubxasl::rlike_eval_term::compiled_pattern, cubxasl::rlike_eval_term::compiled_regex, ER_OUT_OF_VIRTUAL_MEMORY, error(), get_xasl_unpack_info_ptr(), NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, cubxasl::rlike_eval_term::pattern, cubxasl::rlike_eval_term::src, stx_restore_regu_variable(), and stx_set_xasl_errcode().
Referenced by stx_build_eval_term().
static char * stx_build_rlist_spec_type (THREAD_ENTRY * thread_p, char * ptr, REGUVAL_LIST_SPEC_TYPE * spec, OUTPTR_LIST * outptr_list) static
Definition at line 4920 of file stream_to_xasl.c.
References assert, ER_QPROC_INVALID_XASLNODE, NULL, stx_set_xasl_errcode(), and reguval_list_spec_node::valptr_list.
Referenced by stx_build_access_spec_type().
static char * stx_build_selupd_list (THREAD_ENTRY * thread_p, char * tmp, SELUPD_LIST * ptr) static
Definition at line 3843 of file stream_to_xasl.c.
References selupd_list::class_hfid, selupd_list::class_oid, ER_OUT_OF_VIRTUAL_MEMORY, get_xasl_unpack_info_ptr(), selupd_list::next, NULL, or_unpack_hfid(), or_unpack_int(), or_unpack_oid(), xasl_unpack_info::packed_xasl, selupd_list::select_list, selupd_list::select_list_size, stx_restore_regu_varlist_list(), stx_restore_selupd_list(), stx_set_xasl_errcode(), and selupd_list::wait_msecs.
Referenced by stx_restore_selupd_list().
static char * stx_build_set_spec_type (THREAD_ENTRY * thread_p, char * tmp, SET_SPEC_TYPE * ptr) static
Definition at line 4935 of file stream_to_xasl.c.
References ER_OUT_OF_VIRTUAL_MEMORY, get_xasl_unpack_info_ptr(), NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, set_spec_node::set_ptr, set_spec_node::set_regu_list, stx_restore_regu_variable(), stx_restore_regu_variable_list(), and stx_set_xasl_errcode().
Referenced by stx_build_access_spec_type().
static char * stx_build_showstmt_spec_type (THREAD_ENTRY * thread_p, char * ptr, SHOWSTMT_SPEC_TYPE * spec) static
Definition at line 4889 of file stream_to_xasl.c.
References showstmt_spec_node::arg_list, ER_OUT_OF_VIRTUAL_MEMORY, error(), get_xasl_unpack_info_ptr(), NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, showstmt_spec_node::show_type, stx_restore_regu_variable_list(), and stx_set_xasl_errcode().
Referenced by stx_build_access_spec_type().
static char * stx_build_sort_list (THREAD_ENTRY * thread_p, char * tmp, SORT_LIST * ptr) static
Definition at line 5927 of file stream_to_xasl.c.
References ER_OUT_OF_VIRTUAL_MEMORY, get_xasl_unpack_info_ptr(), sort_list::next, NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, sort_list::pos_descr, sort_list::s_nulls, sort_list::s_order, stx_build_pos_descr(), stx_restore_sort_list(), and stx_set_xasl_errcode().
Referenced by stx_restore_sort_list().
static char * stx_build_srlist_id (THREAD_ENTRY * thread_p, char * tmp, QFILE_SORTED_LIST_ID * ptr) static
Definition at line 5901 of file stream_to_xasl.c.
References ER_OUT_OF_VIRTUAL_MEMORY, get_xasl_unpack_info_ptr(), qfile_sorted_list_id::list_id, NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, qfile_sorted_list_id::sorted, stx_restore_list_id(), and stx_set_xasl_errcode().
Referenced by stx_restore_srlist_id().
static char * stx_build_union_proc (THREAD_ENTRY * thread_p, char * tmp, UNION_PROC_NODE * ptr) static
Definition at line 2466 of file stream_to_xasl.c.
References ER_OUT_OF_VIRTUAL_MEMORY, get_xasl_unpack_info_ptr(), union_proc_node::left, NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, union_proc_node::right, stx_restore_xasl_node(), and stx_set_xasl_errcode().
Referenced by stx_build_xasl_node().
static char * stx_build_update_assignment (THREAD_ENTRY * thread_p, char * tmp, UPDATE_ASSIGNMENT * ptr) static
Definition at line 3299 of file stream_to_xasl.c.
References update_assignment::att_idx, update_assignment::clear_value_at_clone_decache, update_assignment::cls_idx, update_assignment::constant, db_value_is_null(), get_xasl_unpack_info_ptr(), NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, update_assignment::regu_var, stx_restore_db_value(), stx_restore_regu_variable(), and xasl_unpack_info::use_xasl_clone.
Referenced by stx_restore_update_assignment_array().
static char * stx_build_update_class_info (THREAD_ENTRY * thread_p, char * tmp, UPDDEL_CLASS_INFO * ptr) static
Definition at line 3136 of file stream_to_xasl.c.
References assert, upddel_class_info::att_id, upddel_class_info::class_hfid, upddel_class_info::class_oid, ER_OUT_OF_VIRTUAL_MEMORY, get_xasl_unpack_info_ptr(), upddel_class_info::has_uniques, i, upddel_class_info::lob_attr_ids, upddel_class_info::mvcc_extra_assign_reev, upddel_class_info::needs_pruning, NULL, upddel_class_info::num_attrs, upddel_class_info::num_extra_assign_reev, upddel_class_info::num_lob_attrs, upddel_class_info::num_subclasses, or_unpack_int(), p, xasl_unpack_info::packed_xasl, stx_alloc_struct(), stx_restore_hfid_array(), stx_restore_int_array(), stx_restore_OID_array(), and stx_set_xasl_errcode().
Referenced by stx_restore_update_class_info_array().
static char * stx_build_update_proc (THREAD_ENTRY * thread_p, char * tmp, UPDATE_PROC_NODE * ptr) static
Definition at line 3457 of file stream_to_xasl.c.
References update_proc_node::assigns, update_proc_node::classes, update_proc_node::cons_pred, ER_GENERIC_ERROR, ER_OUT_OF_VIRTUAL_MEMORY, error(), get_xasl_unpack_info_ptr(), update_proc_node::mvcc_reev_classes, update_proc_node::no_logging, NULL, update_proc_node::num_assign_reev_classes, update_proc_node::num_assigns, update_proc_node::num_classes, update_proc_node::num_orderby_keys, update_proc_node::num_reev_classes, or_unpack_int(), xasl_unpack_info::packed_xasl, stx_restore_int_array(), stx_restore_pred_expr(), stx_restore_update_assignment_array(), stx_restore_update_class_info_array(), stx_set_xasl_errcode(), and update_proc_node::wait_msecs.
Referenced by stx_build_xasl_node().
static char * stx_build_val_list (THREAD_ENTRY * thread_p, char * tmp, VAL_LIST * ptr) static
Definition at line 5028 of file stream_to_xasl.c.
References assert, ER_OUT_OF_VIRTUAL_MEMORY, get_xasl_unpack_info_ptr(), i, qproc_db_value_list::next, NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, stx_alloc_struct(), stx_restore_db_value(), stx_set_xasl_errcode(), qproc_db_value_list::val, val_list_node::val_cnt, and val_list_node::valp.
Referenced by stx_restore_val_list().
static char * stx_build_xasl_header (THREAD_ENTRY * thread_p, char * ptr, XASL_NODE_HEADER * xasl_header) static
Definition at line 1616 of file stream_to_xasl.c.
References ASSERT_ALIGN, INT_ALIGNMENT, NULL, and OR_UNPACK_XASL_NODE_HEADER.
Referenced by stx_build_xasl_node().
static char * stx_build_xasl_node (THREAD_ENTRY * thread_p, char * tmp, XASL_NODE * ptr) static
Definition at line 1629 of file stream_to_xasl.c.
References xasl_node::after_iscan_list, xasl_node::after_join_pred, xasl_node::aptr_list, assert, bool, xasl_node::bptr_list, BUILD_SCHEMA_PROC, xasl_node::buildlist, BUILDLIST_PROC, xasl_node::buildvalue, BUILDVALUE_PROC, xasl_node::cardinality, xasl_node::cat_fetched, xasl_node::connect_by, xasl_node::connect_by_ptr, CONNECTBY_PROC, xasl_node::cte, CTE_PROC, xasl_node::curr_spec, xasl_node::delete_, DELETE_PROC, DIFFERENCE_PROC, DO_PROC, xasl_node::dptr_list, ER_OUT_OF_VIRTUAL_MEMORY, ER_QPROC_INVALID_XASLNODE, error(), xasl_node::fetch, xasl_node::flag, xasl_node::fptr_list, get_xasl_unpack_info_ptr(), xasl_node::header, xasl_node::if_pred, xasl_node::insert, INSERT_PROC, xasl_node::instnum_flag, xasl_node::instnum_pred, xasl_node::instnum_val, INTERSECTION_PROC, xasl_node::is_single_tuple, xasl_node::iscan_oid_order, xasl_node::iscycle_regu, xasl_node::iscycle_val, xasl_node::isleaf_regu, xasl_node::isleaf_val, xasl_node::level_regu, xasl_node::level_val, xasl_node::limit_offset, xasl_node::limit_row_count, xasl_node::list_id, xasl_node::max_iterations, xasl_node::merge, MERGE_PROC, xasl_node::merge_spec, xasl_node::merge_val_list, xasl_node::mergelist, MERGELIST_PROC, xasl_node::mvcc_reev_extra_cls_cnt, db_value::need_clear, xasl_node::next, xasl_node::next_scan_block_on, xasl_node::next_scan_on, NULL, OBJFETCH_PROC, xasl_node::option, or_unpack_double(), or_unpack_int(), xasl_node::ordbynum_flag, xasl_node::ordbynum_pred, xasl_node::ordbynum_val, xasl_node::orderby_limit, xasl_node::orderby_list, xasl_node::outptr_list, xasl_unpack_info::packed_xasl, xasl_node::proc, xasl_node::projected_size, xasl_node::query_alias, xasl_node::query_in_progress, xasl_node::save_instnum_val, xasl_node::scan_op_type, SCAN_PROC, xasl_node::scan_ptr, xasl_node::selected_upd_list, xasl_node::single_tuple, xasl_node::spec_list, stx_build_buildlist_proc(), stx_build_buildvalue_proc(), stx_build_connectby_proc(), stx_build_cte_proc(), stx_build_delete_proc(), stx_build_fetch_proc(), stx_build_insert_proc(), stx_build_merge_proc(), stx_build_mergelist_proc(), stx_build_union_proc(), stx_build_update_proc(), stx_build_xasl_header(), stx_restore_access_spec_type(), stx_restore_db_value(), stx_restore_list_id(), stx_restore_outptr_list(), stx_restore_pred_expr(), stx_restore_regu_variable(), stx_restore_selupd_list(), stx_restore_sort_list(), stx_restore_string(), stx_restore_val_list(), stx_restore_xasl_node(), stx_set_xasl_errcode(), xasl_node::type, xasl_node::union_, UNION_PROC, xasl_node::upd_del_class_cnt, xasl_node::update, UPDATE_PROC, and xasl_node::val_list.
Referenced by stx_restore_xasl_node().
static void stx_init_regu_variable (REGU_VARIABLE * regu) static
Definition at line 6331 of file stream_to_xasl.c.
References assert, i, NULL, or_unpack_int(), and TYPE_POS_VALUE.
Referenced by stx_build_regu_value_list().
int stx_map_stream_to_filter_pred (THREAD_ENTRY * thread_p, pred_expr_with_context ** pred, char * pred_stream, int pred_stream_size)
Definition at line 272 of file stream_to_xasl.c.
References ER_QPROC_INVALID_XASLNODE, free_xasl_unpack_info(), get_xasl_unpack_info_ptr(), NO_ERROR, NULL, or_unpack_int(), p, set_xasl_unpack_info_ptr(), stx_free_visited_ptrs(), stx_get_xasl_errcode(), stx_init_xasl_unpack_info(), stx_restore_filter_pred_node(), stx_set_xasl_errcode(), xasl_unpack_info::track_allocated_bufers, pred_expr_with_context::unpack_info, xasl_unpack_info::use_xasl_clone, and xasl_stream_make_align().
Referenced by fpcache_claim(), xbtree_load_index(), and xbtree_load_online_index().
int stx_map_stream_to_func_pred (THREAD_ENTRY * thread_p, func_pred ** xasl, char * xasl_stream, int xasl_stream_size, XASL_UNPACK_INFO ** xasl_unpack_info_ptr)
Definition at line 329 of file stream_to_xasl.c.
References ER_QPROC_INVALID_XASLNODE, free_xasl_unpack_info(), get_xasl_unpack_info_ptr(), NO_ERROR, NULL, or_unpack_int(), p, set_xasl_unpack_info_ptr(), stx_free_visited_ptrs(), stx_get_xasl_errcode(), stx_init_xasl_unpack_info(), stx_restore_func_pred(), stx_set_xasl_errcode(), xasl_unpack_info::track_allocated_bufers, xasl_unpack_info::use_xasl_clone, and xasl_stream_make_align().
Referenced by heap_eval_function_index(), heap_init_func_pred_unpack_info(), partition_load_partition_predicate(), xbtree_load_index(), and xbtree_load_online_index().
int stx_map_stream_to_xasl (THREAD_ENTRY * thread_p, xasl_node ** xasl_tree, bool use_xasl_clone, char * xasl_stream, int xasl_stream_size, XASL_UNPACK_INFO ** xasl_unpack_info_ptr)
Definition at line 197 of file stream_to_xasl.c.
References xasl_node::class_locks, xasl_node::class_oid_list, xasl_node::creator_oid, xasl_node::dbval_cnt, ER_QPROC_INVALID_XASLNODE, free_xasl_unpack_info(), get_xasl_unpack_info_ptr(), xasl_node::n_oid_list, NO_ERROR, NULL, OID_SET_NULL, or_unpack_int(), p, xasl_node::query_in_progress, set_xasl_unpack_info_ptr(), stx_free_visited_ptrs(), stx_get_xasl_errcode(), stx_init_xasl_unpack_info(), stx_restore_xasl_node(), stx_set_xasl_errcode(), xasl_node::tcard_list, xasl_unpack_info::track_allocated_bufers, xasl_unpack_info::use_xasl_clone, and xasl_stream_make_align().
Referenced by qmgr_process_query(), and xcache_find_xasl_id_for_execute().
int stx_map_stream_to_xasl_node_header (THREAD_ENTRY * thread_p, xasl_node_header * xasl_header_p, char * xasl_stream)
Definition at line 161 of file stream_to_xasl.c.
References assert, ER_FAILED, NO_ERROR, NULL, OR_INT_SIZE, or_unpack_int(), OR_UNPACK_XASL_NODE_HEADER, and xasl_stream_make_align().
Referenced by qfile_load_xasl_node_header().
static REGU_VALUE_ITEM * stx_regu_value_item_alloc_and_init (THREAD_ENTRY * thread_p) static
Definition at line 6187 of file stream_to_xasl.c.
References ER_OUT_OF_VIRTUAL_MEMORY, regu_value_item::next, NULL, stx_alloc_struct(), stx_set_xasl_errcode(), and regu_value_item::value.
Referenced by stx_build_regu_value_list().
static REGU_VALUE_LIST * stx_regu_value_list_alloc_and_init (THREAD_ENTRY * thread_p) static
Definition at line 6162 of file stream_to_xasl.c.
References regu_value_list::count, regu_value_list::current_value, ER_OUT_OF_VIRTUAL_MEMORY, NULL, regu_value_list::regu_list, stx_alloc_struct(), and stx_set_xasl_errcode().
Referenced by stx_unpack_regu_variable_value().
static ACCESS_SPEC_TYPE * stx_restore_access_spec_type (THREAD_ENTRY * thread_p, char ** ptr, void * arg) static
Definition at line 1570 of file stream_to_xasl.c.
References ER_OUT_OF_VIRTUAL_MEMORY, i, access_spec_node::next, NULL, or_unpack_int(), stx_alloc_struct(), stx_build_access_spec_type(), and stx_set_xasl_errcode().
Referenced by stx_build_mergelist_proc(), and stx_build_xasl_node().
static AGGREGATE_TYPE * stx_restore_aggregate_type (THREAD_ENTRY * thread_p, char * ptr) static
Definition at line 390 of file stream_to_xasl.c.
References ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, NULL, stx_alloc_struct(), stx_build_aggregate_type(), stx_get_struct_visited_ptr(), stx_mark_struct_visited(), and stx_set_xasl_errcode().
Referenced by stx_build_aggregate_type(), stx_build_buildlist_proc(), and stx_build_buildvalue_proc().
static ANALYTIC_EVAL_TYPE * stx_restore_analytic_eval_type (THREAD_ENTRY * thread_p, char * ptr) static
Definition at line 488 of file stream_to_xasl.c.
References ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, NULL, stx_alloc_struct(), stx_build_analytic_eval_type(), stx_get_struct_visited_ptr(), stx_mark_struct_visited(), and stx_set_xasl_errcode().
Referenced by stx_build_analytic_eval_type(), and stx_build_buildlist_proc().
static ANALYTIC_TYPE * stx_restore_analytic_type (THREAD_ENTRY * thread_p, char * ptr) static
Definition at line 454 of file stream_to_xasl.c.
References ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, cubxasl::analytic_list_node::init(), NULL, stx_alloc_struct(), stx_build_analytic_type(), stx_get_struct_visited_ptr(), stx_mark_struct_visited(), and stx_set_xasl_errcode().
Referenced by stx_build_analytic_eval_type(), and stx_build_analytic_type().
static ARITH_TYPE * stx_restore_arith_type (THREAD_ENTRY * thread_p, char * ptr) static
Definition at line 552 of file stream_to_xasl.c.
References ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, NULL, stx_alloc_struct(), stx_build_arith_type(), stx_get_struct_visited_ptr(), stx_mark_struct_visited(), and stx_set_xasl_errcode().
Referenced by stx_build_buildvalue_proc(), and stx_unpack_regu_variable_value().
static HEAP_CACHE_ATTRINFO * stx_restore_cache_attrinfo (THREAD_ENTRY * thread_p, char * ptr) static
Definition at line 970 of file stream_to_xasl.c.
References ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, NULL, stx_alloc_struct(), stx_build_cache_attrinfo(), stx_build_ls_merge_info(), stx_get_struct_visited_ptr(), stx_mark_struct_visited(), and stx_set_xasl_errcode().
Referenced by stx_build_attr_descr(), stx_build_cls_spec_type(), stx_build_filter_pred_node(), stx_build_func_pred(), and stx_restore_odku_info().
static DB_VALUE * stx_restore_db_value (THREAD_ENTRY * thread_p, char * ptr) static
Definition at line 808 of file stream_to_xasl.c.
References ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, NULL, stx_alloc_struct(), stx_build_db_value(), stx_get_struct_visited_ptr(), stx_mark_struct_visited(), and stx_set_xasl_errcode().
Referenced by stx_build_access_spec_type(), stx_build_aggregate_type(), stx_build_analytic_type(), stx_build_arith_type(), stx_build_buildlist_proc(), stx_build_buildvalue_proc(), stx_build_fetch_proc(), stx_build_function_type(), stx_build_insert_proc(), stx_build_regu_variable(), stx_build_update_assignment(), stx_build_val_list(), stx_build_xasl_node(), stx_restore_db_value_array_extra(), and stx_unpack_regu_variable_value().
static DB_VALUE ** stx_restore_db_value_array_extra (THREAD_ENTRY * thread_p, char * ptr, int size, int total_size) static
Definition at line 1266 of file stream_to_xasl.c.
References assert, ER_OUT_OF_VIRTUAL_MEMORY, get_xasl_unpack_info_ptr(), i, NULL, or_unpack_domain(), xasl_unpack_info::packed_xasl, stx_alloc_struct(), stx_restore_db_value(), stx_restore_int_array(), and stx_set_xasl_errcode().
Referenced by stx_build_cls_spec_type().
static PRED_EXPR_WITH_CONTEXT * stx_restore_filter_pred_node (THREAD_ENTRY * thread_p, char * ptr) static
Definition at line 913 of file stream_to_xasl.c.
References db_private_alloc, ER_OUT_OF_VIRTUAL_MEMORY, NULL, stx_build_filter_pred_node(), and stx_set_xasl_errcode().
Referenced by stx_map_stream_to_filter_pred().
static FUNC_PRED * stx_restore_func_pred (THREAD_ENTRY * thread_p, char * ptr) static
Definition at line 938 of file stream_to_xasl.c.
References ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, NULL, stx_alloc_struct(), stx_build_func_pred(), stx_get_struct_visited_ptr(), stx_mark_struct_visited(), and stx_set_xasl_errcode().
Referenced by stx_map_stream_to_func_pred().
static FUNCTION_TYPE * stx_restore_function_type (THREAD_ENTRY * thread_p, char * ptr) static
Definition at line 422 of file stream_to_xasl.c.
References ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, NULL, stx_alloc_struct(), stx_build_function_type(), stx_get_struct_visited_ptr(), stx_mark_struct_visited(), and stx_set_xasl_errcode().
Referenced by stx_unpack_regu_variable_value().
static HFID* stx_restore_hfid_array (THREAD_ENTRY * thread_p, char * ptr, int nelements) static
Definition at line 1348 of file stream_to_xasl.c.
References ER_OUT_OF_VIRTUAL_MEMORY, i, NULL, or_unpack_hfid(), stx_alloc_struct(), and stx_set_xasl_errcode().
Referenced by stx_build_update_class_info().
static INDX_INFO * stx_restore_indx_info (THREAD_ENTRY * thread_p, char * ptr) static
Definition at line 584 of file stream_to_xasl.c.
References ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, NULL, stx_alloc_struct(), stx_build_indx_info(), stx_get_struct_visited_ptr(), stx_mark_struct_visited(), and stx_set_xasl_errcode().
Referenced by stx_build_access_spec_type().
static int * stx_restore_int_array (THREAD_ENTRY * thread_p, char * ptr, int size) static
Definition at line 1328 of file stream_to_xasl.c.
References ER_OUT_OF_VIRTUAL_MEMORY, i, NULL, or_unpack_int(), stx_alloc_struct(), and stx_set_xasl_errcode().
Referenced by stx_build_cls_spec_type(), stx_build_delete_proc(), stx_build_filter_pred_node(), stx_build_insert_proc(), stx_build_ls_merge_info(), stx_build_update_class_info(), stx_build_update_proc(), stx_restore_db_value_array_extra(), stx_restore_key_range_array(), and stx_restore_odku_info().
static KEY_RANGE * stx_restore_key_range_array (THREAD_ENTRY * thread_p, char * ptr, int size) static
Definition at line 1506 of file stream_to_xasl.c.
References ER_OUT_OF_VIRTUAL_MEMORY, error(), get_xasl_unpack_info_ptr(), i, key_range::key1, key_range::key2, NULL, xasl_unpack_info::packed_xasl, key_range::range, stx_alloc_struct(), stx_restore_int_array(), stx_restore_regu_variable(), and stx_set_xasl_errcode().
Referenced by stx_build_key_info().
static QFILE_LIST_ID * stx_restore_list_id (THREAD_ENTRY * thread_p, char * ptr) static
Definition at line 1164 of file stream_to_xasl.c.
References ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, NULL, stx_alloc_struct(), stx_build_list_id(), stx_get_struct_visited_ptr(), stx_mark_struct_visited(), and stx_set_xasl_errcode().
Referenced by stx_build_aggregate_type(), stx_build_analytic_type(), stx_build_buildlist_proc(), stx_build_connectby_proc(), stx_build_srlist_id(), and stx_build_xasl_node().
static METHOD_SIG * stx_restore_method_sig (THREAD_ENTRY * thread_p, char * ptr, int size) static
Definition at line 1231 of file stream_to_xasl.c.
References assert, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, NULL, stx_alloc_struct(), stx_build_method_sig(), stx_get_struct_visited_ptr(), stx_mark_struct_visited(), and stx_set_xasl_errcode().
Referenced by stx_build_method_sig(), and stx_build_method_sig_list().
static METHOD_SIG_LIST * stx_restore_method_sig_list (THREAD_ENTRY * thread_p, char * ptr) static
Definition at line 1200 of file stream_to_xasl.c.
References ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, NULL, stx_alloc_struct(), stx_build_method_sig_list(), stx_get_struct_visited_ptr(), stx_mark_struct_visited(), and stx_set_xasl_errcode().
Referenced by stx_build_method_spec_type().
static ODKU_INFO * stx_restore_odku_info (THREAD_ENTRY * thread_p, char * ptr) static
Definition at line 3374 of file stream_to_xasl.c.
References odku_info::assignments, odku_info::attr_ids, odku_info::attr_info, odku_info::cons_pred, ER_OUT_OF_VIRTUAL_MEMORY, get_xasl_unpack_info_ptr(), NULL, odku_info::num_assigns, or_unpack_int(), xasl_unpack_info::packed_xasl, stx_alloc_struct(), stx_restore_cache_attrinfo(), stx_restore_int_array(), stx_restore_pred_expr(), stx_restore_update_assignment_array(), and stx_set_xasl_errcode().
Referenced by stx_build_insert_proc().
static OID * stx_restore_OID_array (THREAD_ENTRY * thread_p, char * ptr, int size) static
Definition at line 1368 of file stream_to_xasl.c.
References ER_OUT_OF_VIRTUAL_MEMORY, i, NULL, or_unpack_oid(), stx_alloc_struct(), and stx_set_xasl_errcode().
Referenced by stx_build_update_class_info().
static OUTPTR_LIST * stx_restore_outptr_list (THREAD_ENTRY * thread_p, char * ptr) static
Definition at line 616 of file stream_to_xasl.c.
References ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, NULL, stx_alloc_struct(), stx_build_outptr_list(), stx_get_struct_visited_ptr(), stx_mark_struct_visited(), and stx_set_xasl_errcode().
Referenced by stx_build_buildlist_proc(), stx_build_cls_spec_type(), stx_build_connectby_proc(), stx_build_insert_proc(), and stx_build_xasl_node().
static PRED_EXPR * stx_restore_pred_expr (THREAD_ENTRY * thread_p, char * ptr) static
Definition at line 680 of file stream_to_xasl.c.
References ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, NULL, stx_alloc_struct(), stx_build_pred_expr(), stx_get_struct_visited_ptr(), stx_mark_struct_visited(), and stx_set_xasl_errcode().
Referenced by stx_build_access_spec_type(), stx_build_arith_type(), stx_build_buildlist_proc(), stx_build_buildvalue_proc(), stx_build_connectby_proc(), stx_build_fetch_proc(), stx_build_filter_pred_node(), stx_build_insert_proc(), stx_build_pred(), stx_build_pred_expr(), stx_build_update_proc(), stx_build_xasl_node(), and stx_restore_odku_info().
static REGU_VARIABLE * stx_restore_regu_variable (THREAD_ENTRY * thread_p, char * ptr) static
Definition at line 712 of file stream_to_xasl.c.
References ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, NULL, stx_alloc_struct(), stx_build_regu_variable(), stx_get_struct_visited_ptr(), stx_mark_struct_visited(), and stx_set_xasl_errcode().
Referenced by stx_build_aggregate_type(), stx_build_alsm_eval_term(), stx_build_analytic_type(), stx_build_arith_type(), stx_build_comp_eval_term(), stx_build_func_pred(), stx_build_indx_info(), stx_build_key_info(), stx_build_like_eval_term(), stx_build_rlike_eval_term(), stx_build_set_spec_type(), stx_build_update_assignment(), stx_build_xasl_node(), and stx_restore_key_range_array().
static REGU_VARIABLE_LIST stx_restore_regu_variable_list (THREAD_ENTRY * thread_p, char * ptr) static
Definition at line 1410 of file stream_to_xasl.c.
References ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, get_xasl_unpack_info_ptr(), i, regu_variable_list_node::next, NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, stx_alloc_struct(), stx_build_regu_variable(), stx_get_struct_visited_ptr(), stx_mark_struct_visited(), stx_set_xasl_errcode(), and regu_variable_list_node::value.
Referenced by stx_build_buildlist_proc(), stx_build_cls_spec_type(), stx_build_connectby_proc(), stx_build_function_type(), stx_build_list_spec_type(), stx_build_method_spec_type(), stx_build_outptr_list(), stx_build_regu_variable_list(), stx_build_set_spec_type(), stx_build_showstmt_spec_type(), and stx_restore_regu_varlist_list().
static REGU_VARLIST_LIST stx_restore_regu_varlist_list (THREAD_ENTRY * thread_p, char * ptr) static
Definition at line 1460 of file stream_to_xasl.c.
References ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, get_xasl_unpack_info_ptr(), i, regu_varlist_list_node::list, regu_varlist_list_node::next, NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, stx_alloc_struct(), stx_get_struct_visited_ptr(), stx_mark_struct_visited(), stx_restore_regu_variable_list(), and stx_set_xasl_errcode().
Referenced by stx_build_selupd_list().
static SELUPD_LIST * stx_restore_selupd_list (THREAD_ENTRY * thread_p, char * ptr) static
Definition at line 648 of file stream_to_xasl.c.
References ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, NULL, stx_alloc_struct(), stx_build_selupd_list(), stx_get_struct_visited_ptr(), stx_mark_struct_visited(), and stx_set_xasl_errcode().
Referenced by stx_build_selupd_list(), and stx_build_xasl_node().
static SORT_LIST * stx_restore_sort_list (THREAD_ENTRY * thread_p, char * ptr) static
Definition at line 744 of file stream_to_xasl.c.
References ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, NULL, stx_alloc_struct(), stx_build_sort_list(), stx_get_struct_visited_ptr(), stx_mark_struct_visited(), and stx_set_xasl_errcode().
Referenced by stx_build_aggregate_type(), stx_build_analytic_eval_type(), stx_build_buildlist_proc(), stx_build_sort_list(), and stx_build_xasl_node().
static QFILE_SORTED_LIST_ID * stx_restore_srlist_id (THREAD_ENTRY * thread_p, char * ptr) static
Definition at line 520 of file stream_to_xasl.c.
References ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, NULL, stx_alloc_struct(), stx_build_srlist_id(), stx_get_struct_visited_ptr(), stx_mark_struct_visited(), and stx_set_xasl_errcode().
Referenced by stx_unpack_regu_variable_value().
static UPDATE_ASSIGNMENT * stx_restore_update_assignment_array (THREAD_ENTRY * thread_p, char * ptr, int num_assigns) static
Definition at line 3349 of file stream_to_xasl.c.
References ER_OUT_OF_VIRTUAL_MEMORY, NULL, stx_alloc_struct(), stx_build_update_assignment(), and stx_set_xasl_errcode().
Referenced by stx_build_update_proc(), and stx_restore_odku_info().
static UPDDEL_CLASS_INFO * stx_restore_update_class_info_array (THREAD_ENTRY * thread_p, char * ptr, int num_classes) static
Definition at line 3274 of file stream_to_xasl.c.
References ER_OUT_OF_VIRTUAL_MEMORY, NULL, stx_alloc_struct(), stx_build_update_class_info(), and stx_set_xasl_errcode().
Referenced by stx_build_delete_proc(), and stx_build_update_proc().
static VAL_LIST * stx_restore_val_list (THREAD_ENTRY * thread_p, char * ptr) static
Definition at line 776 of file stream_to_xasl.c.
References ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, NULL, stx_alloc_struct(), stx_build_val_list(), stx_get_struct_visited_ptr(), stx_mark_struct_visited(), and stx_set_xasl_errcode().
Referenced by stx_build_buildlist_proc(), stx_build_connectby_proc(), stx_build_mergelist_proc(), and stx_build_xasl_node().
static XASL_NODE * stx_restore_xasl_node (THREAD_ENTRY * thread_p, char * ptr) static
Definition at line 873 of file stream_to_xasl.c.
References ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, NULL, stx_alloc_struct(), stx_build_xasl_node(), stx_get_struct_visited_ptr(), stx_mark_struct_visited(), and stx_set_xasl_errcode().
Referenced by stx_build_buildlist_proc(), stx_build_cte_proc(), stx_build_list_spec_type(), stx_build_merge_proc(), stx_build_mergelist_proc(), stx_build_method_spec_type(), stx_build_regu_variable(), stx_build_union_proc(), stx_build_xasl_node(), and stx_map_stream_to_xasl().
static char * stx_unpack_regu_variable_value (THREAD_ENTRY * thread_p, char * tmp, REGU_VARIABLE * ptr) static
Definition at line 5177 of file stream_to_xasl.c.
References assert, db_value_is_null(), ER_OUT_OF_VIRTUAL_MEMORY, ER_QPROC_INVALID_XASLNODE, error(), get_xasl_unpack_info_ptr(), NULL, or_unpack_int(), xasl_unpack_info::packed_xasl, REGU_VARIABLE_CLEAR_AT_CLONE_DECACHE, REGU_VARIABLE_SET_FLAG(), stx_build_attr_descr(), stx_build_db_value(), stx_build_pos_descr(), stx_build_regu_value_list(), stx_build_regu_variable_list(), stx_regu_value_list_alloc_and_init(), stx_restore_arith_type(), stx_restore_db_value(), stx_restore_function_type(), stx_restore_srlist_id(), stx_set_xasl_errcode(), TYPE_ATTR_ID, TYPE_CLASS_ATTR_ID, TYPE_CLASSOID, TYPE_CONSTANT, TYPE_DBVAL, TYPE_FUNC, TYPE_INARITH, TYPE_LIST_ID, TYPE_OID, TYPE_ORDERBY_NUM, TYPE_OUTARITH, TYPE_POS_VALUE, TYPE_POSITION, TYPE_REGU_VAR_LIST, TYPE_REGUVAL_LIST, TYPE_SHARED_ATTR_ID, and xasl_unpack_info::use_xasl_clone.
Referenced by stx_build_regu_value_list(), and stx_build_regu_variable().