CUBRID Engine: src/query/stream_to_xasl.h File Reference
stream_to_xasl.h File Reference
#include "thread_compat.hpp"
Functions
int stx_map_stream_to_xasl (THREAD_ENTRY *thread_p, xasl_node **xasl_tree, bool use_xasl_clone, char *xasl_stream, int xasl_stream_size, xasl_unpack_info **xasl_unpack_info_ptr)
int stx_map_stream_to_filter_pred (THREAD_ENTRY *thread_p, pred_expr_with_context **pred_expr_tree, char *pred_stream, int pred_stream_size)
int stx_map_stream_to_func_pred (THREAD_ENTRY *thread_p, func_pred **xasl, char *xasl_stream, int xasl_stream_size, xasl_unpack_info **xasl_unpack_info_ptr)
int stx_map_stream_to_xasl_node_header (THREAD_ENTRY *thread_p, xasl_node_header *xasl_header_p, char *xasl_stream)
Function Documentation
int stx_map_stream_to_filter_pred (THREAD_ENTRY * thread_p, pred_expr_with_context ** pred_expr_tree, char * pred_stream, int pred_stream_size)
Definition at line 272 of file stream_to_xasl.c.
References ER_QPROC_INVALID_XASLNODE, free_xasl_unpack_info(), get_xasl_unpack_info_ptr(), NO_ERROR, NULL, or_unpack_int(), p, set_xasl_unpack_info_ptr(), stx_free_visited_ptrs(), stx_get_xasl_errcode(), stx_init_xasl_unpack_info(), stx_restore_filter_pred_node(), stx_set_xasl_errcode(), xasl_unpack_info::track_allocated_bufers, pred_expr_with_context::unpack_info, xasl_unpack_info::use_xasl_clone, and xasl_stream_make_align().
Referenced by fpcache_claim(), xbtree_load_index(), and xbtree_load_online_index().
int stx_map_stream_to_func_pred (THREAD_ENTRY * thread_p, func_pred ** xasl, char * xasl_stream, int xasl_stream_size, xasl_unpack_info ** xasl_unpack_info_ptr)
Definition at line 329 of file stream_to_xasl.c.
References ER_QPROC_INVALID_XASLNODE, free_xasl_unpack_info(), get_xasl_unpack_info_ptr(), NO_ERROR, NULL, or_unpack_int(), p, set_xasl_unpack_info_ptr(), stx_free_visited_ptrs(), stx_get_xasl_errcode(), stx_init_xasl_unpack_info(), stx_restore_func_pred(), stx_set_xasl_errcode(), xasl_unpack_info::track_allocated_bufers, xasl_unpack_info::use_xasl_clone, and xasl_stream_make_align().
Referenced by heap_eval_function_index(), heap_init_func_pred_unpack_info(), partition_load_partition_predicate(), xbtree_load_index(), and xbtree_load_online_index().
int stx_map_stream_to_xasl (THREAD_ENTRY * thread_p, xasl_node ** xasl_tree, bool use_xasl_clone, char * xasl_stream, int xasl_stream_size, xasl_unpack_info ** xasl_unpack_info_ptr)
Definition at line 197 of file stream_to_xasl.c.
References xasl_node::class_locks, xasl_node::class_oid_list, xasl_node::creator_oid, xasl_node::dbval_cnt, ER_QPROC_INVALID_XASLNODE, free_xasl_unpack_info(), get_xasl_unpack_info_ptr(), xasl_node::n_oid_list, NO_ERROR, NULL, OID_SET_NULL, or_unpack_int(), p, xasl_node::query_in_progress, set_xasl_unpack_info_ptr(), stx_free_visited_ptrs(), stx_get_xasl_errcode(), stx_init_xasl_unpack_info(), stx_restore_xasl_node(), stx_set_xasl_errcode(), xasl_node::tcard_list, xasl_unpack_info::track_allocated_bufers, xasl_unpack_info::use_xasl_clone, and xasl_stream_make_align().
Referenced by qmgr_process_query(), and xcache_find_xasl_id_for_execute().
int stx_map_stream_to_xasl_node_header (THREAD_ENTRY * thread_p, xasl_node_header * xasl_header_p, char * xasl_stream)
Definition at line 161 of file stream_to_xasl.c.
References assert, ER_FAILED, NO_ERROR, NULL, OR_INT_SIZE, or_unpack_int(), OR_UNPACK_XASL_NODE_HEADER, and xasl_stream_make_align().
Referenced by qfile_load_xasl_node_header().