CUBRID Engine: cubmem::extensible_block Struct Reference
cubmem::extensible_block Struct Reference
#include <mem_block.hpp>
Public Member Functions
extensible_block ()
extensible_block (extensible_block &&b)
extensible_block (const block_allocator &alloc)
~extensible_block ()
extensible_block & operator= (extensible_block &&b)
void extend_by (size_t additional_bytes)
void extend_to (size_t total_bytes)
void freemem ()
char * get_ptr ()
const char * get_read_ptr () const
std::size_t get_size () const
char * release_ptr ()
Private Member Functions
extensible_block (const extensible_block &)=delete
extensible_block & operator= (const extensible_block &)=delete
Private Attributes
block m_block
const block_allocator * m_allocator
Detailed Description
Definition at line 159 of file mem_block.hpp.
Constructor & Destructor Documentation
cubmem::extensible_block::extensible_block () inline
Definition at line 301 of file mem_block.hpp.
References cubmem::STANDARD_BLOCK_ALLOCATOR.
cubmem::extensible_block::extensible_block (extensible_block && b) inline
Definition at line 306 of file mem_block.hpp.
References m_allocator, and NULL.
cubmem::extensible_block::extensible_block (const block_allocator & alloc) inline
Definition at line 313 of file mem_block.hpp.
References m_allocator.
cubmem::extensible_block::~extensible_block () inline
Definition at line 334 of file mem_block.hpp.
References m_allocator, m_block, and cubmem::block_allocator::m_dealloc_f.
Referenced by operator=().
cubmem::extensible_block::extensible_block (const extensible_block &) private delete
Member Function Documentation
void cubmem::extensible_block::extend_by (size_t additional_bytes) inline
Definition at line 340 of file mem_block.hpp.
References cubmem::block::dim, cubmem::block_allocator::m_alloc_f, m_allocator, and m_block.
Referenced by cubmem::extensible_stack_block< S >::extend_by(), and extend_to().
void cubmem::extensible_block::extend_to (size_t total_bytes) inline
Definition at line 346 of file mem_block.hpp.
References cubmem::block::dim, extend_by(), and m_block.
Referenced by string_buffer::add_bytes(), log_postpone_cache::add_redo_data(), cubmem::extensible_stack_block< S >::extend_by(), cubload::semantic_helper::extend_quoted_string_buffer(), cubmem::extensible_stack_block< S >::extend_to(), string_buffer::operator()(), string_buffer::operator+=(), record_descriptor::resize_buffer(), record_descriptor::set_recdes(), string_buffer::string_buffer(), cubload::server_class_installer::to_lowercase_identifier(), and cubpacking::unpacker::unpack_string_to_memblock().
void cubmem::extensible_block::freemem () inline
Definition at line 356 of file mem_block.hpp.
References m_allocator, m_block, and cubmem::block_allocator::m_dealloc_f.
Referenced by log_postpone_cache::reset(), and record_descriptor::set_external_buffer().
char * cubmem::extensible_block::get_ptr (void) inline
Definition at line 362 of file mem_block.hpp.
References m_block, and cubmem::block::ptr.
Referenced by string_buffer::add_bytes(), log_postpone_cache::add_redo_data(), boot_register_client(), string_buffer::clear(), log_postpone_cache::do_postpone(), cubload::semantic_helper::extend_quoted_string_buffer(), cubmem::extensible_stack_block< S >::get_ptr(), cubload::server_class_installer::is_class_ignored(), loaddb_init(), loaddb_install_class(), loaddb_load_batch(), string_buffer::operator()(), string_buffer::operator+=(), record_descriptor::resize_buffer(), record_descriptor::set_recdes(), sloaddb_fetch_status(), sloaddb_load_batch(), string_buffer::string_buffer(), cubload::server_class_installer::to_lowercase_identifier(), and cubpacking::unpacker::unpack_string_to_memblock().
const char * cubmem::extensible_block::get_read_ptr (void) const inline
Definition at line 368 of file mem_block.hpp.
References m_block, and cubmem::block::ptr.
Referenced by cubload::server_class_installer::check_class(), string_buffer::get_buffer(), cubmem::extensible_stack_block< S >::get_read_ptr(), and cubload::server_class_installer::register_class_with_attributes().
std::size_t cubmem::extensible_block::get_size (void) const inline
Definition at line 374 of file mem_block.hpp.
References cubmem::block::dim, and m_block.
Referenced by string_buffer::operator()(), string_buffer::operator+=(), record_descriptor::release_buffer(), and log_postpone_cache::reset().
extensible_block & cubmem::extensible_block::operator= (extensible_block && b) inline
Definition at line 320 of file mem_block.hpp.
References cubmem::block::dim, m_allocator, m_block, NULL, cubmem::block::ptr, and ~extensible_block().
extensible_block& cubmem::extensible_block::operator= (const extensible_block &) private delete
char * cubmem::extensible_block::release_ptr () inline
Definition at line 380 of file mem_block.hpp.
References cubmem::block::dim, m_block, NULL, and cubmem::block::ptr.
Referenced by record_descriptor::release_buffer(), and string_buffer::release_ptr().
Member Data Documentation
const block_allocator* cubmem::extensible_block::m_allocator private
Definition at line 182 of file mem_block.hpp.
Referenced by extend_by(), extensible_block(), freemem(), operator=(), and ~extensible_block().
block cubmem::extensible_block::m_block private
Definition at line 181 of file mem_block.hpp.
Referenced by extend_by(), extend_to(), freemem(), get_ptr(), get_read_ptr(), get_size(), operator=(), release_ptr(), and ~extensible_block().
The documentation for this struct was generated from the following file:
src/base/mem_block.hpp