CUBRID Engine: value_bind_table_ifs_s Struct Reference
value_bind_table_ifs_s Struct Reference
#include <api_common.h>
Public Attributes
int(* get_value)(VALUE_BIND_TABLE *tbl, int index, CI_TYPE type, void *addr, size_t len, size_t *outlen, bool *isnull)
int(* set_value)(VALUE_BIND_TABLE *tbl, int index, CI_TYPE type, void *addr, size_t len)
int(* get_value_by_name)(VALUE_BIND_TABLE *tbl, const char *name, CI_TYPE type, void *addr, size_t len, size_t *outlen, bool *isnull)
int(* set_value_by_name)(VALUE_BIND_TABLE *tbl, const char *name, CI_TYPE type, void *addr, size_t len)
int(* apply_updates)(VALUE_BIND_TABLE *tbl)
int(* reset)(VALUE_BIND_TABLE *tbl)
void(* destroy)(VALUE_BIND_TABLE *tbl)
Detailed Description
Definition at line 240 of file api_common.h.
Member Data Documentation
int(* value_bind_table_ifs_s::apply_updates) (VALUE_BIND_TABLE *tbl)
Definition at line 248 of file api_common.h.
Referenced by api_rs_apply_row(), and res_api_apply_update().
void(* value_bind_table_ifs_s::destroy) (VALUE_BIND_TABLE *tbl)
Definition at line 250 of file api_common.h.
Referenced by or_destroy(), res_api_delete_row(), and rs_destroyf().
int(* value_bind_table_ifs_s::get_value) (VALUE_BIND_TABLE *tbl, int index, CI_TYPE type, void *addr, size_t len, size_t *outlen, bool *isnull)
Definition at line 242 of file api_common.h.
Referenced by api_rs_get_value(), res_api_get_value(), and vbt_api_get_value_by_name().
int(* value_bind_table_ifs_s::get_value_by_name) (VALUE_BIND_TABLE *tbl, const char *name, CI_TYPE type, void *addr, size_t len, size_t *outlen, bool *isnull)
Definition at line 245 of file api_common.h.
Referenced by api_rs_get_value_by_name(), and res_api_get_value_by_name().
int(* value_bind_table_ifs_s::reset) (VALUE_BIND_TABLE *tbl)
Definition at line 249 of file api_common.h.
Referenced by api_rs_clear_updates(), api_rs_fetch(), and res_api_clear_updates().
int(* value_bind_table_ifs_s::set_value) (VALUE_BIND_TABLE *tbl, int index, CI_TYPE type, void *addr, size_t len)
Definition at line 244 of file api_common.h.
Referenced by api_rs_update_value(), res_api_update_value(), and vbt_api_set_value_by_name().
int(* value_bind_table_ifs_s::set_value_by_name) (VALUE_BIND_TABLE *tbl, const char *name, CI_TYPE type, void *addr, size_t len)
Definition at line 247 of file api_common.h.
The documentation for this struct was generated from the following file:
src/api/api_common.h