CUBRID Engine: rvfun Struct Reference
rvfun Struct Reference
#include <recovery.h>
Public Attributes
LOG_RCVINDEX recv_index
const char * recv_string
int(* undofun)(THREAD_ENTRY *thread_p, LOG_RCV *logrcv)
int(* redofun)(THREAD_ENTRY *thread_p, LOG_RCV *logrcv)
void(* dump_undofun)(FILE *fp, int length, void *data)
void(* dump_redofun)(FILE *fp, int length, void *data)
Detailed Description
Definition at line 211 of file recovery.h.
Member Data Documentation
void(* rvfun::dump_redofun) (FILE *fp, int length, void *data)
Definition at line 218 of file recovery.h.
void(* rvfun::dump_undofun) (FILE *fp, int length, void *data)
Definition at line 217 of file recovery.h.
LOG_RCVINDEX rvfun::recv_index
Definition at line 213 of file recovery.h.
Referenced by rv_check_rvfuns().
const char* rvfun::recv_string
Definition at line 214 of file recovery.h.
Referenced by rv_rcvindex_string().
int(* rvfun::redofun) (THREAD_ENTRY *thread_p, LOG_RCV *logrcv)
Definition at line 216 of file recovery.h.
Referenced by log_execute_run_postpone().
int(* rvfun::undofun) (THREAD_ENTRY *thread_p, LOG_RCV *logrcv)
Definition at line 215 of file recovery.h.
Referenced by log_rollback_record(), log_rv_undo_record(), and log_undo_rec_restartable().
The documentation for this struct was generated from the following file:
src/transaction/recovery.h