CUBRID Engine: boot_client_credential Struct Reference
boot_client_credential Struct Reference
#include <client_credentials.hpp>
Public Member Functions
boot_client_credential ()
~boot_client_credential () override
const char * get_db_name () const
const char * get_db_password () const
virtual size_t get_packed_size (cubpacking::packer &serializator, std::size_t start_offset=0) const override
virtual void pack (cubpacking::packer &serializator) const override
virtual void unpack (cubpacking::unpacker &deserializator) override
Public Member Functions inherited from clientids
clientids ()
~clientids () override
const char * get_client_info () const
const char * get_db_user () const
const char * get_program_name () const
const char * get_login_name () const
const char * get_host_name () const
void set_ids (db_client_type type, const char *client_info, const char *db_user, const char *program_name, const char *login_name, const char *host_name, int process_id)
void set_ids (const clientids &other)
void set_user (const char *db_user)
void set_system_internal ()
void set_system_internal_with_user (const char *db_user)
void reset ()
Public Member Functions inherited from cubpacking::packable_object
virtual ~packable_object ()
virtual bool is_equal (const packable_object *other)
Public Attributes
std::string db_name
std::string db_password
char * preferred_hosts
int connect_order
Public Attributes inherited from clientids
db_client_type client_type
std::string client_info
std::string db_user
std::string program_name
std::string login_name
std::string host_name
int process_id
Additional Inherited Members
Static Public Attributes inherited from clientids
static const char * UNKNOWN_ID = "(unknown)"
Detailed Description
Definition at line 82 of file client_credentials.hpp.
Constructor & Destructor Documentation
boot_client_credential::boot_client_credential ()
Definition at line 198 of file client_credentials.cpp.
References connect_order, db_password, NULL, and preferred_hosts.
boot_client_credential::~boot_client_credential () override
Definition at line 207 of file client_credentials.cpp.
Member Function Documentation
const char * boot_client_credential::get_db_name () const
Definition at line 212 of file client_credentials.cpp.
References db_name.
Referenced by boot_get_host_name(), boot_initialize_client(), boot_restart_client(), boot_set_server_session_key(), xboot_initialize_server(), and xboot_register_client().
const char * boot_client_credential::get_db_password () const
Definition at line 218 of file client_credentials.cpp.
References db_password.
Referenced by boot_restart_client().
size_t boot_client_credential::get_packed_size (cubpacking::packer & serializator, std::size_t start_offset = 0) const override virtual
Reimplemented from clientids.
Definition at line 231 of file client_credentials.cpp.
References BOOTCLCRED_PACKER_ARGS, cubpacking::packer::get_all_packed_size(), and clientids::get_packed_size().
void boot_client_credential::pack (cubpacking::packer & serializator) const override virtual
Reimplemented from clientids.
Definition at line 237 of file client_credentials.cpp.
References BOOTCLCRED_PACKER_ARGS, clientids::pack(), and cubpacking::packer::pack_all().
void boot_client_credential::unpack (cubpacking::unpacker & deserializator) override virtual
Reimplemented from clientids.
Definition at line 244 of file client_credentials.cpp.
References BOOTCLCRED_PACKER_ARGS, clientids::unpack(), and cubpacking::unpacker::unpack_all().
Member Data Documentation
int boot_client_credential::connect_order
Definition at line 87 of file client_credentials.hpp.
Referenced by boot_client_credential(), boot_restart_client(), conn_restart_client(), and db_restart().
std::string boot_client_credential::db_name
Definition at line 84 of file client_credentials.hpp.
Referenced by boot_initialize_client(), conn_restart_client(), db_init(), db_restart(), get_db_name(), and xboot_initialize_server().
std::string boot_client_credential::db_password
Definition at line 85 of file client_credentials.hpp.
Referenced by boot_client_credential(), boot_restart_client(), conn_restart_client(), and get_db_password().
char* boot_client_credential::preferred_hosts
Definition at line 86 of file client_credentials.hpp.
Referenced by boot_client_credential(), boot_restart_client(), and db_restart().
The documentation for this struct was generated from the following files:
src/transaction/client_credentials.hpp
src/transaction/client_credentials.cpp