CUBRID Engine: api_object_resultset_pool_s Struct Reference
api_object_resultset_pool_s Struct Reference
#include <api_common.h>
Public Attributes
int(* get_object_resultset)(API_OBJECT_RESULTSET_POOL *pool, CI_OID *oid, API_RESULTSET **rres)
int(* oid_delete)(API_OBJECT_RESULTSET_POOL *pool, CI_OID *oid)
int(* oid_get_classname)(API_OBJECT_RESULTSET_POOL *pool, CI_OID *oid, char *name, size_t size)
void(* destroy)(API_OBJECT_RESULTSET_POOL *pool)
int(* glo_create)(API_OBJECT_RESULTSET_POOL *pool, CI_CONNECTION conn, const char *file_path, const char *init_file_path, CI_OID *glo)
int(* glo_get_path_name)(API_OBJECT_RESULTSET_POOL *pool, CI_OID *glo, char *buf, size_t bufsz, bool full_path)
int(* glo_do_compaction)(API_OBJECT_RESULTSET_POOL *pool, CI_OID *glo)
int(* glo_insert)(API_OBJECT_RESULTSET_POOL *pool, CI_OID *glo, const char *buf, size_t bufsz)
int(* glo_delete)(API_OBJECT_RESULTSET_POOL *pool, CI_OID *glo, size_t sz, size_t *ndeleted)
int(* glo_read)(API_OBJECT_RESULTSET_POOL *pool, CI_OID *glo, char *buf, size_t bufsz, size_t *nread)
int(* glo_write)(API_OBJECT_RESULTSET_POOL *pool, CI_OID *glo, const char *buf, size_t sz)
int(* glo_truncate)(API_OBJECT_RESULTSET_POOL *pool, CI_OID *glo, size_t *ndeleted)
int(* glo_seek)(API_OBJECT_RESULTSET_POOL *pool, CI_OID *glo, long offset, int whence)
int(* glo_tell)(API_OBJECT_RESULTSET_POOL *pool, CI_OID *glo, long *offset)
int(* glo_like_search)(API_OBJECT_RESULTSET_POOL *pool, CI_OID *glo, const char *str, size_t strsz, bool *found)
int(* glo_reg_search)(API_OBJECT_RESULTSET_POOL *pool, CI_OID *glo, const char *str, size_t strsz, bool *found)
int(* glo_bin_search)(API_OBJECT_RESULTSET_POOL *pool, CI_OID *glo, const char *str, size_t strsz, bool *found)
int(* glo_copy)(API_OBJECT_RESULTSET_POOL *pool, CI_OID *to, CI_OID *from)
Detailed Description
Definition at line 168 of file api_common.h.
Member Data Documentation
void(* api_object_resultset_pool_s::destroy) (API_OBJECT_RESULTSET_POOL *pool)
Definition at line 173 of file api_common.h.
Referenced by api_object_resultset_pool_create(), conn_destroyf(), and opool_create().
int(* api_object_resultset_pool_s::get_object_resultset) (API_OBJECT_RESULTSET_POOL *pool, CI_OID *oid, API_RESULTSET **rres)
Definition at line 170 of file api_common.h.
Referenced by api_object_resultset_pool_create(), ci_oid_get_resultset(), and opool_create().
int(* api_object_resultset_pool_s::glo_bin_search) (API_OBJECT_RESULTSET_POOL *pool, CI_OID *glo, const char *str, size_t strsz, bool *found)
Definition at line 187 of file api_common.h.
int(* api_object_resultset_pool_s::glo_copy) (API_OBJECT_RESULTSET_POOL *pool, CI_OID *to, CI_OID *from)
Definition at line 188 of file api_common.h.
int(* api_object_resultset_pool_s::glo_create) (API_OBJECT_RESULTSET_POOL *pool, CI_CONNECTION conn, const char *file_path, const char *init_file_path, CI_OID *glo)
Definition at line 174 of file api_common.h.
int(* api_object_resultset_pool_s::glo_delete) (API_OBJECT_RESULTSET_POOL *pool, CI_OID *glo, size_t sz, size_t *ndeleted)
Definition at line 179 of file api_common.h.
int(* api_object_resultset_pool_s::glo_do_compaction) (API_OBJECT_RESULTSET_POOL *pool, CI_OID *glo)
Definition at line 177 of file api_common.h.
int(* api_object_resultset_pool_s::glo_get_path_name) (API_OBJECT_RESULTSET_POOL *pool, CI_OID *glo, char *buf, size_t bufsz, bool full_path)
Definition at line 176 of file api_common.h.
int(* api_object_resultset_pool_s::glo_insert) (API_OBJECT_RESULTSET_POOL *pool, CI_OID *glo, const char *buf, size_t bufsz)
Definition at line 178 of file api_common.h.
int(* api_object_resultset_pool_s::glo_like_search) (API_OBJECT_RESULTSET_POOL *pool, CI_OID *glo, const char *str, size_t strsz, bool *found)
Definition at line 185 of file api_common.h.
int(* api_object_resultset_pool_s::glo_read) (API_OBJECT_RESULTSET_POOL *pool, CI_OID *glo, char *buf, size_t bufsz, size_t *nread)
Definition at line 180 of file api_common.h.
int(* api_object_resultset_pool_s::glo_reg_search) (API_OBJECT_RESULTSET_POOL *pool, CI_OID *glo, const char *str, size_t strsz, bool *found)
Definition at line 186 of file api_common.h.
int(* api_object_resultset_pool_s::glo_seek) (API_OBJECT_RESULTSET_POOL *pool, CI_OID *glo, long offset, int whence)
Definition at line 183 of file api_common.h.
int(* api_object_resultset_pool_s::glo_tell) (API_OBJECT_RESULTSET_POOL *pool, CI_OID *glo, long *offset)
Definition at line 184 of file api_common.h.
int(* api_object_resultset_pool_s::glo_truncate) (API_OBJECT_RESULTSET_POOL *pool, CI_OID *glo, size_t *ndeleted)
Definition at line 182 of file api_common.h.
int(* api_object_resultset_pool_s::glo_write) (API_OBJECT_RESULTSET_POOL *pool, CI_OID *glo, const char *buf, size_t sz)
Definition at line 181 of file api_common.h.
int(* api_object_resultset_pool_s::oid_delete) (API_OBJECT_RESULTSET_POOL *pool, CI_OID *oid)
Definition at line 171 of file api_common.h.
Referenced by api_object_resultset_pool_create(), ci_oid_delete(), and opool_create().
int(* api_object_resultset_pool_s::oid_get_classname) (API_OBJECT_RESULTSET_POOL *pool, CI_OID *oid, char *name, size_t size)
Definition at line 172 of file api_common.h.
Referenced by api_object_resultset_pool_create(), ci_oid_get_classname(), and opool_create().
The documentation for this struct was generated from the following file:
src/api/api_common.h