CUBRID Engine: esql_translate_table_s Struct Reference
esql_translate_table_s Struct Reference
#include <esql_translate.h>
Public Attributes
void(* tr_connect)(HOST_REF *db_name, HOST_REF *user_name, HOST_REF *passwd)
void(* tr_disconnect)(void)
void(* tr_commit)(void)
void(* tr_rollback)(void)
void(* tr_static)(const char *stmt, int length, bool repeat, int num_in_vars, HOST_REF *in_vars, const char *in_desc_name, int num_out_vars, HOST_REF *out_vars, const char *out_desc_name)
void(* tr_open_cs)(int cs_no, const char *stmt, int length, int stmt_no, bool readonly, int num_in_vars, HOST_REF *in_vars, const char *desc_name)
void(* tr_fetch_cs)(int cs_no, int num_out_vars, HOST_REF *out_vars, const char *desc_name)
void(* tr_update_cs)(int cs_no, const char *text, int length, bool repetitive, int num_in_vars, HOST_REF *in_vars)
void(* tr_delete_cs)(int cs_no)
void(* tr_close_cs)(int cs_no)
void(* tr_prepare_esql)(int stmt_no, HOST_REF *stmt)
void(* tr_describe)(int stmt_no, const char *desc_name)
void(* tr_execute)(int stmt_no, int num_in_vars, HOST_REF *in_vars, const char *in_desc_name, int num_out_vars, HOST_REF *out_vars, const char *out_desc_name)
void(* tr_execute_immediate)(HOST_REF *stmt)
void(* tr_object_describe)(HOST_REF *obj, int num_attrs, const char **attr_names, const char *desc_name)
void(* tr_object_fetch)(HOST_REF *obj, int num_attrs, const char **attr_names, int num_out_vars, HOST_REF *out_vars, const char *desc_name)
void(* tr_object_update)(const char *set_expr, int length, bool repetitive, int num_in_vars, HOST_REF *in_vars)
void(* tr_whenever)(WHEN_CONDITION condition, WHEN_ACTION action, const char *name)
void(* tr_set_out_stream)(FILE *out_stream)
void(* tr_set_line_terminator)(const char *)
Detailed Description
Definition at line 34 of file esql_translate.h.
Member Data Documentation
void(* esql_translate_table_s::tr_close_cs) (int cs_no)
Definition at line 47 of file esql_translate.h.
void(* esql_translate_table_s::tr_commit) (void)
Definition at line 38 of file esql_translate.h.
void(* esql_translate_table_s::tr_connect) (HOST_REF *db_name, HOST_REF *user_name, HOST_REF *passwd)
Definition at line 36 of file esql_translate.h.
void(* esql_translate_table_s::tr_delete_cs) (int cs_no)
Definition at line 46 of file esql_translate.h.
void(* esql_translate_table_s::tr_describe) (int stmt_no, const char *desc_name)
Definition at line 49 of file esql_translate.h.
void(* esql_translate_table_s::tr_disconnect) (void)
Definition at line 37 of file esql_translate.h.
void(* esql_translate_table_s::tr_execute) (int stmt_no, int num_in_vars, HOST_REF *in_vars, const char *in_desc_name, int num_out_vars, HOST_REF *out_vars, const char *out_desc_name)
Definition at line 50 of file esql_translate.h.
void(* esql_translate_table_s::tr_execute_immediate) (HOST_REF *stmt)
Definition at line 52 of file esql_translate.h.
void(* esql_translate_table_s::tr_fetch_cs) (int cs_no, int num_out_vars, HOST_REF *out_vars, const char *desc_name)
Definition at line 44 of file esql_translate.h.
void(* esql_translate_table_s::tr_object_describe) (HOST_REF *obj, int num_attrs, const char **attr_names, const char *desc_name)
Definition at line 53 of file esql_translate.h.
void(* esql_translate_table_s::tr_object_fetch) (HOST_REF *obj, int num_attrs, const char **attr_names, int num_out_vars, HOST_REF *out_vars, const char *desc_name)
Definition at line 54 of file esql_translate.h.
void(* esql_translate_table_s::tr_object_update) (const char *set_expr, int length, bool repetitive, int num_in_vars, HOST_REF *in_vars)
Definition at line 56 of file esql_translate.h.
void(* esql_translate_table_s::tr_open_cs) (int cs_no, const char *stmt, int length, int stmt_no, bool readonly, int num_in_vars, HOST_REF *in_vars, const char *desc_name)
Definition at line 42 of file esql_translate.h.
void(* esql_translate_table_s::tr_prepare_esql) (int stmt_no, HOST_REF *stmt)
Definition at line 48 of file esql_translate.h.
void(* esql_translate_table_s::tr_rollback) (void)
Definition at line 39 of file esql_translate.h.
void(* esql_translate_table_s::tr_set_line_terminator) (const char *)
Definition at line 59 of file esql_translate.h.
Referenced by pp_startup().
void(* esql_translate_table_s::tr_set_out_stream) (FILE *out_stream)
Definition at line 58 of file esql_translate.h.
Referenced by pp_startup().
void(* esql_translate_table_s::tr_static) (const char *stmt, int length, bool repeat, int num_in_vars, HOST_REF *in_vars, const char *in_desc_name, int num_out_vars, HOST_REF *out_vars, const char *out_desc_name)
Definition at line 40 of file esql_translate.h.
void(* esql_translate_table_s::tr_update_cs) (int cs_no, const char *text, int length, bool repetitive, int num_in_vars, HOST_REF *in_vars)
Definition at line 45 of file esql_translate.h.
void(* esql_translate_table_s::tr_whenever) (WHEN_CONDITION condition, WHEN_ACTION action, const char *name)
Definition at line 57 of file esql_translate.h.
Referenced by pp_add_whenever_to_scope(), and pp_finish_whenever_scope().
The documentation for this struct was generated from the following file:
src/executables/esql_translate.h