CUBRID Engine: object_description Struct Reference
object_description Struct Reference
#include <object_description.hpp>
Public Member Functions
object_description ()
~object_description ()
int init (struct db_object *op)
Public Attributes
char * classname
char * oid
char ** attributes
char ** shared
Detailed Description
Definition at line 35 of file object_description.hpp.
Constructor & Destructor Documentation
object_description::object_description ()
Definition at line 38 of file object_description.cpp.
object_description::~object_description ()
Definition at line 135 of file object_description.cpp.
References attributes, classname, object_print::free_strarray(), oid, and shared.
Member Function Documentation
int object_description::init (struct db_object * op)
Definition at line 46 of file object_description.cpp.
References ARG_FILE_LINE, attributes, au_fetch_class(), au_fetch_instance(), AU_FETCH_READ, AU_SELECT, classname, string_buffer::clear(), object_print::copy_string(), cubregex::count(), DB_FETCH_READ, db_get(), db_make_null(), db_make_object(), db_value_clear(), sm_attribute::default_value, db_value_printer::describe_data(), db_value_printer::describe_value(), ER_ERROR_SEVERITY, ER_OBJ_INVALID_ARGUMENTS, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), sm_attribute::header, i, ID_SHARED_ATTRIBUTE, is_class(), locator_is_class(), sm_component::name, sm_component::name_space, NO_ERROR, NULL, oid, sm_attribute::order_link, string_buffer::release_ptr(), sm_ch_name(), TM_TRAN_READ_FETCH_VERSION, sm_default_value::value, ws_class_mop(), and ws_pin().
Referenced by help_print_obj().
Member Data Documentation
char** object_description::attributes
Definition at line 39 of file object_description.hpp.
Referenced by help_print_obj(), init(), and ~object_description().
char* object_description::classname
Definition at line 37 of file object_description.hpp.
Referenced by help_print_obj(), init(), and ~object_description().
char* object_description::oid
Definition at line 38 of file object_description.hpp.
Referenced by init(), and ~object_description().
char** object_description::shared
Definition at line 40 of file object_description.hpp.
Referenced by help_print_obj(), and ~object_description().
The documentation for this struct was generated from the following files:
src/object/object_description.hpp
src/object/object_description.cpp