CUBRID Engine: page_key_boundary Struct Reference
page_key_boundary Struct Reference
#include <btree.h>
Public Member Functions
page_key_boundary ()
~page_key_boundary ()
void set_value (DB_VALUE &dest_value, DB_VALUE &src_value, bool &clear_src_value)
int set_value (THREAD_ENTRY *thread_p, DB_VALUE &dest_value, BTID_INT *btid, PAGE_PTR page_ptr, const INT16 slot)
int set_value (THREAD_ENTRY *thread_p, DB_VALUE &dest_value, BTID_INT *btid, PAGE_PTR page_ptr, RECDES &rec)
int update_boundary_eq (THREAD_ENTRY *thread_p, BTID_INT *btid, PAGE_PTR page_ptr, DB_VALUE &subtree_value, bool &clear_subtree_value, const INT16 subtree_slot)
int update_boundary_lt (THREAD_ENTRY *thread_p, BTID_INT *btid, PAGE_PTR page_ptr, RECDES &left_subtree_rec, DB_VALUE &subtree_value, bool &clear_subtree_value)
int update_boundary_gt_or_eq (THREAD_ENTRY *thread_p, BTID_INT *btid, PAGE_PTR page_ptr, DB_VALUE &subtree_value, bool &clear_subtree_value, const INT16 subtree_slot, const int key_cnt)
Public Attributes
DB_VALUE m_left_key
DB_VALUE m_right_key
bool m_is_inf_left_key
bool m_is_inf_right_key
Detailed Description
Definition at line 543 of file btree.h.
Constructor & Destructor Documentation
page_key_boundary::page_key_boundary ()
Definition at line 35454 of file btree.c.
References db_make_null(), m_left_key, and m_right_key.
page_key_boundary::~page_key_boundary ()
Definition at line 35462 of file btree.c.
References m_left_key, m_right_key, and pr_clear_value().
Member Function Documentation
void page_key_boundary::set_value (DB_VALUE & dest_value, DB_VALUE & src_value, bool & clear_src_value)
Definition at line 35469 of file btree.c.
References btree_clear_key_value(), pr_clear_value(), and pr_clone_value().
Referenced by set_value(), update_boundary_eq(), update_boundary_gt_or_eq(), and update_boundary_lt().
int page_key_boundary::set_value (THREAD_ENTRY * thread_p, DB_VALUE & dest_value, BTID_INT * btid, PAGE_PTR page_ptr, const INT16 slot)
Definition at line 35477 of file btree.c.
References ER_FAILED, PEEK, S_SUCCESS, set_value(), and spage_get_record().
int page_key_boundary::set_value (THREAD_ENTRY * thread_p, DB_VALUE & dest_value, BTID_INT * btid, PAGE_PTR page_ptr, RECDES & rec)
Definition at line 35490 of file btree.c.
References BTREE_NON_LEAF_NODE, btree_read_record_without_decompression(), db_make_null(), ER_FAILED, NO_ERROR, PEEK_KEY_VALUE, pr_clear_value(), and pr_clone_value().
int page_key_boundary::update_boundary_eq (THREAD_ENTRY * thread_p, BTID_INT * btid, PAGE_PTR page_ptr, DB_VALUE & subtree_value, bool & clear_subtree_value, const INT16 subtree_slot)
Definition at line 35528 of file btree.c.
References error(), m_is_inf_left_key, m_is_inf_right_key, m_left_key, m_right_key, NO_ERROR, and set_value().
Referenced by btree_search_nonleaf_page().
int page_key_boundary::update_boundary_gt_or_eq (THREAD_ENTRY * thread_p, BTID_INT * btid, PAGE_PTR page_ptr, DB_VALUE & subtree_value, bool & clear_subtree_value, const INT16 subtree_slot, const int key_cnt)
Definition at line 35591 of file btree.c.
References error(), m_is_inf_left_key, m_is_inf_right_key, m_left_key, m_right_key, NO_ERROR, and set_value().
Referenced by btree_search_nonleaf_page().
int page_key_boundary::update_boundary_lt (THREAD_ENTRY * thread_p, BTID_INT * btid, PAGE_PTR page_ptr, RECDES & left_subtree_rec, DB_VALUE & subtree_value, bool & clear_subtree_value)
Definition at line 35561 of file btree.c.
References error(), m_is_inf_left_key, m_is_inf_right_key, m_left_key, m_right_key, NO_ERROR, and set_value().
Referenced by btree_search_nonleaf_page().
Member Data Documentation
bool page_key_boundary::m_is_inf_left_key
Definition at line 548 of file btree.h.
Referenced by btree_key_online_index_IB_insert_list(), btree_insert_list::reset_boundary_keys(), update_boundary_eq(), update_boundary_gt_or_eq(), and update_boundary_lt().
bool page_key_boundary::m_is_inf_right_key
Definition at line 549 of file btree.h.
Referenced by btree_key_online_index_IB_insert_list(), btree_insert_list::reset_boundary_keys(), update_boundary_eq(), update_boundary_gt_or_eq(), and update_boundary_lt().
DB_VALUE page_key_boundary::m_left_key
Definition at line 545 of file btree.h.
Referenced by btree_key_online_index_IB_insert_list(), page_key_boundary(), btree_insert_list::reset_boundary_keys(), update_boundary_eq(), update_boundary_gt_or_eq(), update_boundary_lt(), and ~page_key_boundary().
DB_VALUE page_key_boundary::m_right_key
Definition at line 546 of file btree.h.
Referenced by btree_key_online_index_IB_insert_list(), page_key_boundary(), btree_insert_list::reset_boundary_keys(), update_boundary_eq(), update_boundary_gt_or_eq(), update_boundary_lt(), and ~page_key_boundary().
The documentation for this struct was generated from the following files:
src/storage/btree.h
src/storage/btree.c