CUBRID Engine: value_indexer_ifs_s Struct Reference
value_indexer_ifs_s Struct Reference
#include <api_common.h>
Public Attributes
int(* check)(VALUE_INDEXER *indexer, int index, CHECK_PURPOSE pup)
int(* length)(VALUE_INDEXER *indexer, int *len)
int(* get)(VALUE_INDEXER *indexer, int index, VALUE_AREA **rva, API_VALUE **rv)
int(* set)(VALUE_INDEXER *indexer, int index, VALUE_AREA *va, API_VALUE *val)
int(* map)(VALUE_INDEXER *indexer, int(*mapf)(void *, int, VALUE_AREA *, API_VALUE *), void *arg)
int(* insert)(VALUE_INDEXER *indexer, int index, VALUE_AREA *va, API_VALUE *dval)
int(* delete)(VALUE_INDEXER *indexer, int index, VALUE_AREA **rva, API_VALUE **rval)
void(* destroy)(VALUE_INDEXER *indexer, void(*df)(VALUE_AREA *va, API_VALUE *db))
Detailed Description
Definition at line 216 of file api_common.h.
Member Data Documentation
int(* value_indexer_ifs_s::check) (VALUE_INDEXER *indexer, int index, CHECK_PURPOSE pup)
Definition at line 218 of file api_common.h.
Referenced by api_col_delete(), api_col_get_elem(), api_col_get_elem_domain_info(), api_col_insert(), api_col_update(), api_qres_clear_updates(), api_qres_get_value(), api_qres_update_value(), ci_stmt_execute_impl(), ci_stmt_get_parameter_impl(), ci_stmt_set_parameter_impl(), col_api_delete(), col_api_get_elem(), col_api_get_elem_domain_info(), col_api_insert(), col_api_update(), complete_statement(), fill_collection(), and vbt_lazy_init_db_value().
int(* value_indexer_ifs_s::delete) (VALUE_INDEXER *indexer, int index, VALUE_AREA **rva, API_VALUE **rval)
Definition at line 224 of file api_common.h.
Referenced by api_col_delete(), and col_api_delete().
void(* value_indexer_ifs_s::destroy) (VALUE_INDEXER *indexer, void(*df)(VALUE_AREA *va, API_VALUE *db))
Definition at line 225 of file api_common.h.
Referenced by col_api_destroy(), resultset_impl_dtor(), statement_impl_dtor(), vbt_api_destroy(), and xcol_destroy().
int(* value_indexer_ifs_s::get) (VALUE_INDEXER *indexer, int index, VALUE_AREA **rva, API_VALUE **rv)
Definition at line 220 of file api_common.h.
Referenced by api_col_get_elem(), api_col_get_elem_domain_info(), api_col_update(), api_qres_clear_updates(), api_qres_get_value(), api_qres_update_value(), ci_stmt_execute_impl(), ci_stmt_get_parameter_impl(), ci_stmt_set_parameter_impl(), col_api_get_elem(), col_api_get_elem_domain_info(), col_api_update(), complete_statement(), vbt_lazy_init_db_value(), and xcol_copy().
int(* value_indexer_ifs_s::insert) (VALUE_INDEXER *indexer, int index, VALUE_AREA *va, API_VALUE *dval)
Definition at line 223 of file api_common.h.
Referenced by api_col_insert(), cci_set_to_xcol(), col_api_insert(), fill_collection(), and xcol_copy().
int(* value_indexer_ifs_s::length) (VALUE_INDEXER *indexer, int *len)
Definition at line 219 of file api_common.h.
Referenced by api_col_length(), api_collection_set_to_db_value(), api_qres_clear_updates(), col_api_length(), xcol_copy(), and xcol_to_cci_set().
int(* value_indexer_ifs_s::map) (VALUE_INDEXER *indexer, int(*mapf)(void *, int, VALUE_AREA *, API_VALUE *), void *arg)
Definition at line 222 of file api_common.h.
Referenced by api_collection_set_to_db_value(), api_ores_apply_update(), api_qres_apply_update(), ci_stmt_add_batch_impl(), vbt_api_apply_updates(), vbt_api_reset(), and xcol_to_cci_set().
int(* value_indexer_ifs_s::set) (VALUE_INDEXER *indexer, int index, VALUE_AREA *va, API_VALUE *val)
Definition at line 221 of file api_common.h.
Referenced by add_batch_params_mapf(), add_batch_params_restore_mapf(), api_qres_clear_updates(), api_qres_update_value(), ci_stmt_set_parameter_impl(), complete_statement(), vbt_lazy_init_db_value(), and vbt_resetf_map().
The documentation for this struct was generated from the following file:
src/api/api_common.h