CUBRID Engine: vacuum_data_entry Struct Reference
vacuum_data_entry Struct Reference
Public Member Functions
vacuum_data_entry ()=default
vacuum_data_entry (const log_lsa &lsa, MVCCID oldest, MVCCID newest)
vacuum_data_entry (const log_header &hdr)
VACUUM_LOG_BLOCKID get_blockid () const
bool is_available () const
bool is_vacuumed () const
bool is_job_in_progress () const
bool was_interrupted () const
void set_vacuumed ()
void set_job_in_progress ()
void set_interrupted ()
Public Attributes
VACUUM_LOG_BLOCKID blockid
LOG_LSA start_lsa
MVCCID oldest_visible_mvccid
MVCCID newest_mvccid
Detailed Description
Definition at line 95 of file vacuum.c.
Constructor & Destructor Documentation
vacuum_data_entry::vacuum_data_entry () default
vacuum_data_entry::vacuum_data_entry (const log_lsa & lsa, MVCCID oldest, MVCCID newest)
Definition at line 8015 of file vacuum.c.
References assert, blockid, log_lsa::is_null(), MVCCID_IS_VALID, log_lsa::pageid, start_lsa, and vacuum_get_log_blockid().
vacuum_data_entry::vacuum_data_entry (const log_header & hdr)
Definition at line 8028 of file vacuum.c.
Member Function Documentation
VACUUM_LOG_BLOCKID vacuum_data_entry::get_blockid () const
Definition at line 8034 of file vacuum.c.
References blockid, and VACUUM_BLOCKID_WITHOUT_FLAGS.
Referenced by vacuum_data_page::get_index_of_blockid(), vacuum_consume_buffer_log_blocks(), vacuum_data_mark_finished(), vacuum_data_unload_first_and_last_page(), vacuum_finished_block_vacuum(), vacuum_log_prefetch_vacuum_block(), vacuum_process_log_block(), vacuum_rv_redo_data_finished(), vacuum_verify_vacuum_data_debug(), and xvacuum().
bool vacuum_data_entry::is_available () const
Definition at line 8040 of file vacuum.c.
References blockid, and VACUUM_BLOCK_STATUS_IS_AVAILABLE.
Referenced by vacuum_consume_buffer_log_blocks(), vacuum_data_unload_first_and_last_page(), vacuum_verify_vacuum_data_debug(), and xvacuum().
bool vacuum_data_entry::is_job_in_progress () const
Definition at line 8052 of file vacuum.c.
References blockid, and VACUUM_BLOCK_STATUS_IS_IN_PROGRESS.
Referenced by vacuum_data_load_and_recover(), vacuum_data_mark_finished(), vacuum_data_unload_first_and_last_page(), and vacuum_verify_vacuum_data_debug().
bool vacuum_data_entry::is_vacuumed () const
Definition at line 8046 of file vacuum.c.
References blockid, and VACUUM_BLOCK_STATUS_IS_VACUUMED.
Referenced by vacuum_data_mark_finished(), vacuum_data_unload_first_and_last_page(), vacuum_rv_redo_data_finished(), vacuum_verify_vacuum_data_debug(), and xvacuum().
void vacuum_data_entry::set_interrupted ()
Definition at line 8077 of file vacuum.c.
References blockid, VACUUM_BLOCK_SET_INTERRUPTED, and VACUUM_BLOCK_STATUS_SET_AVAILABLE.
Referenced by vacuum_data_load_and_recover(), vacuum_data_mark_finished(), vacuum_finished_block_vacuum(), and vacuum_rv_redo_data_finished().
void vacuum_data_entry::set_job_in_progress ()
Definition at line 8071 of file vacuum.c.
References blockid, and VACUUM_BLOCK_STATUS_SET_IN_PROGRESS.
Referenced by vacuum_job_cursor::start_job_on_current_entry(), and vacuum_rv_redo_start_job().
void vacuum_data_entry::set_vacuumed ()
Definition at line 8064 of file vacuum.c.
References blockid, VACUUM_BLOCK_CLEAR_INTERRUPTED, and VACUUM_BLOCK_STATUS_SET_VACUUMED.
Referenced by vacuum_consume_buffer_log_blocks(), vacuum_data_mark_finished(), vacuum_finished_block_vacuum(), and vacuum_rv_redo_data_finished().
bool vacuum_data_entry::was_interrupted () const
Definition at line 8058 of file vacuum.c.
References blockid, and VACUUM_BLOCK_IS_INTERRUPTED.
Referenced by vacuum_job_cursor::start_job_on_current_entry(), and vacuum_process_log_block().
Member Data Documentation
VACUUM_LOG_BLOCKID vacuum_data_entry::blockid
Definition at line 98 of file vacuum.c.
Referenced by get_blockid(), is_available(), is_job_in_progress(), is_vacuumed(), set_interrupted(), set_job_in_progress(), vacuum_data::set_last_blockid(), set_vacuumed(), vacuum_consume_buffer_log_blocks(), vacuum_data::vacuum_data(), vacuum_data_entry(), vacuum_data_load_and_recover(), vacuum_data_mark_finished(), vacuum_finished_block_vacuum(), vacuum_init_data_page_with_last_blockid(), vacuum_recover_lost_block_data(), vacuum_rv_redo_append_data_dump(), vacuum_rv_redo_data_finished(), vacuum_rv_redo_data_finished_dump(), vacuum_rv_redo_initialize_data_page(), and was_interrupted().
MVCCID vacuum_data_entry::newest_mvccid
Definition at line 101 of file vacuum.c.
Referenced by vacuum_consume_buffer_log_blocks(), vacuum_process_log_block(), vacuum_recover_lost_block_data(), and vacuum_rv_redo_append_data_dump().
MVCCID vacuum_data_entry::oldest_visible_mvccid
Definition at line 100 of file vacuum.c.
Referenced by vacuum_data::update(), vacuum_consume_buffer_log_blocks(), vacuum_process_log_block(), vacuum_recover_lost_block_data(), vacuum_rv_redo_append_data_dump(), and vacuum_verify_vacuum_data_debug().
LOG_LSA vacuum_data_entry::start_lsa
Definition at line 99 of file vacuum.c.
Referenced by vacuum_consume_buffer_log_blocks(), vacuum_data_entry(), vacuum_process_log_block(), vacuum_recover_lost_block_data(), vacuum_rv_redo_append_data_dump(), and vacuum_verify_vacuum_data_debug().
The documentation for this struct was generated from the following file:
src/query/vacuum.c