CUBRID Engine: hash_tab_s Struct Reference
hash_tab_s Struct Reference
#include <esql_hash.h>
Public Attributes
void(* free_table)(HASH_TAB *tbl, HT_FREE_FN free)
void *(* add_symbol)(HASH_TAB *tbl, void *sym)
void *(* find_symbol)(HASH_TAB *tbl, void *sym)
void *(* next_symbol)(HASH_TAB *tbl, void *last)
void(* remove_symbol)(HASH_TAB *tbl, void *sym)
int(* print_table)(HASH_TAB *tbl, void(*prnt)(), void *par, int srt)
int(* get_symbol_count)(HASH_TAB *tbl)
Detailed Description
Definition at line 34 of file esql_hash.h.
Member Data Documentation
void*(* hash_tab_s::add_symbol) (HASH_TAB *tbl, void *sym)
Definition at line 37 of file esql_hash.h.
Referenced by es_ht_make_table(), pp_add_dummy_structdef(), pp_add_symbols_to_table(), pp_do_enum(), pp_new_cursor(), pp_new_pseudo_def(), and pp_new_stmt().
void*(* hash_tab_s::find_symbol) (HASH_TAB *tbl, void *sym)
Definition at line 38 of file esql_hash.h.
Referenced by es_ht_make_table(), pp_findsym(), pp_lookup_cursor(), and pp_new_stmt().
void(* hash_tab_s::free_table) (HASH_TAB *tbl, HT_FREE_FN free)
Definition at line 36 of file esql_hash.h.
Referenced by es_ht_make_table(), pp_cursor_finish(), and pp_free_symtab().
int(* hash_tab_s::get_symbol_count) (HASH_TAB *tbl)
Definition at line 42 of file esql_hash.h.
Referenced by es_ht_make_table(), pp_print_cursors(), and pp_print_syms().
void*(* hash_tab_s::next_symbol) (HASH_TAB *tbl, void *last)
Definition at line 39 of file esql_hash.h.
Referenced by es_ht_make_table().
int(* hash_tab_s::print_table) (HASH_TAB *tbl, void(*prnt)(), void *par, int srt)
Definition at line 41 of file esql_hash.h.
Referenced by es_ht_make_table(), pp_print_cursors(), and pp_print_syms().
void(* hash_tab_s::remove_symbol) (HASH_TAB *tbl, void *sym)
Definition at line 40 of file esql_hash.h.
Referenced by es_ht_make_table(), pp_remove_cursors_from_table(), pp_remove_structdefs_from_table(), and pp_remove_symbols_from_table().
The documentation for this struct was generated from the following file:
src/executables/esql_hash.h