CUBRID Engine: bh_interface_s Struct Reference
bh_interface_s Struct Reference
#include <api_handle.h>
Public Attributes
int(* alloc_handle)(BH_INTERFACE *ifs, BH_BIND *bind, BIND_HANDLE *bh)
int(* destroy_handle)(BH_INTERFACE *ifs, BIND_HANDLE bh)
int(* lookup)(BH_INTERFACE *ifs, BIND_HANDLE bh, BH_BIND **bind)
int(* bind_to_handle)(BH_INTERFACE *ifs, BH_BIND *bind, BIND_HANDLE *bh)
int(* bind_get_parent)(BH_INTERFACE *ifs, BH_BIND *bind, BH_BIND **pbind)
int(* bind_prune)(BH_INTERFACE *ifs, BH_BIND *bind)
int(* bind_graft)(BH_INTERFACE *ifs, BH_BIND *bind, BH_BIND *on_bind)
int(* bind_get_first_child)(BH_INTERFACE *ifs, BH_BIND *bind, BH_BIND **pchild)
int(* bind_get_next_sibling)(BH_INTERFACE *ifs, BH_BIND *bind, BH_BIND **psibling)
int(* bind_map)(BH_INTERFACE *ifs, BH_BIND *bind, bh_mapf mf, void *arg)
void(* destroy)(BH_INTERFACE *ifs)
Detailed Description
Definition at line 58 of file api_handle.h.
Member Data Documentation
int(* bh_interface_s::alloc_handle) (BH_INTERFACE *ifs, BH_BIND *bind, BIND_HANDLE *bh)
Definition at line 60 of file api_handle.h.
Referenced by bind_api_structure(), ci_conn_create_statement_impl(), ci_create_connection_impl(), create_handle_context(), or_create(), stmt_batch_alloc_and_bind_new_result(), stmt_bind_pmeta_handle(), stmt_bind_resultset_meta_handle(), stmt_exec_internal(), and stmt_exec_one_statement().
int(* bh_interface_s::bind_get_first_child) (BH_INTERFACE *ifs, BH_BIND *bind, BH_BIND **pchild)
Definition at line 67 of file api_handle.h.
Referenced by complete_connection(), conn_end_tran(), create_handle_context(), stmt_batch_result_free(), stmt_exec_internal(), and stmt_release_children().
int(* bh_interface_s::bind_get_next_sibling) (BH_INTERFACE *ifs, BH_BIND *bind, BH_BIND **psibling)
Definition at line 68 of file api_handle.h.
Referenced by complete_connection(), conn_end_tran(), create_handle_context(), stmt_batch_result_free(), stmt_exec_internal(), and stmt_release_children().
int(* bh_interface_s::bind_get_parent) (BH_INTERFACE *ifs, BH_BIND *bind, BH_BIND **pbind)
Definition at line 64 of file api_handle.h.
Referenced by api_rmeta_get_info(), api_rs_apply_row(), api_rs_clear_updates(), api_rs_delete_row(), api_rs_get_resultset_metadata(), api_rs_update_value(), create_handle_context(), and rs_destroyf().
int(* bh_interface_s::bind_graft) (BH_INTERFACE *ifs, BH_BIND *bind, BH_BIND *on_bind)
Definition at line 66 of file api_handle.h.
Referenced by bind_api_structure(), ci_conn_create_statement_impl(), create_handle_context(), or_create(), stmt_batch_alloc_and_bind_new_result(), stmt_bind_pmeta_handle(), stmt_bind_resultset_meta_handle(), stmt_exec_internal(), and stmt_exec_one_statement().
int(* bh_interface_s::bind_map) (BH_INTERFACE *ifs, BH_BIND *bind, bh_mapf mf, void *arg)
Definition at line 69 of file api_handle.h.
Referenced by create_handle_context().
int(* bh_interface_s::bind_prune) (BH_INTERFACE *ifs, BH_BIND *bind)
Definition at line 65 of file api_handle.h.
Referenced by create_handle_context().
int(* bh_interface_s::bind_to_handle) (BH_INTERFACE *ifs, BH_BIND *bind, BIND_HANDLE *bh)
Definition at line 63 of file api_handle.h.
Referenced by ci_stmt_get_parameter_metadata_impl(), ci_stmt_get_resultset_impl(), create_handle_context(), or_destroy(), rs_destroyf(), statement_get_reshandle_or_affectedrows(), stmt_batch_result_free(), stmt_exec_internal(), stmt_exec_one_statement(), stmt_get_resultset_metadata_internal(), and stmt_release_children().
void(* bh_interface_s::destroy) (BH_INTERFACE *ifs)
Definition at line 70 of file api_handle.h.
Referenced by bh_root_release(), and create_handle_context().
int(* bh_interface_s::destroy_handle) (BH_INTERFACE *ifs, BIND_HANDLE bh)
Definition at line 61 of file api_handle.h.
Referenced by bind_api_structure(), ci_stmt_close(), ci_stmt_execute_batch_impl(), ci_stmt_next_result_impl(), complete_statement(), create_handle_context(), or_create(), or_destroy(), rs_destroyf(), stmt_batch_result_free(), stmt_bind_resultset_meta_handle(), stmt_exec_internal(), stmt_exec_one_statement(), and stmt_release_children().
int(* bh_interface_s::lookup) (BH_INTERFACE *ifs, BIND_HANDLE bh, BH_BIND **bind)
Definition at line 62 of file api_handle.h.
Referenced by ci_stmt_get_resultset_metadata_impl(), and create_handle_context().
The documentation for this struct was generated from the following file:
src/api/api_handle.h