CUBRID Engine: bh_context_be_s Struct Reference
bh_context_be_s Struct Reference
Public Attributes
void(* destroy)(bh_context_be *be)
int(* lookup)(bh_context_be *be, BIND_HANDLE handle, BHIFS_NODE **node)
int(* insert)(bh_context_be *be, BHIFS_NODE *const node)
int(* delete)(bh_context_be *be, BIND_HANDLE handle, BHIFS_NODE **node)
Detailed Description
Definition at line 91 of file api_handle.c.
Member Data Documentation
int(* bh_context_be_s::delete) (bh_context_be *be, BIND_HANDLE handle, BHIFS_NODE **node)
Definition at line 96 of file api_handle.c.
Referenced by be_create_static_hash(), and fe_destroy_handle_worker().
void(* bh_context_be_s::destroy) (bh_context_be *be)
Definition at line 93 of file api_handle.c.
Referenced by be_create_static_hash(), and fe_destroy().
int(* bh_context_be_s::insert) (bh_context_be *be, BHIFS_NODE *const node)
Definition at line 95 of file api_handle.c.
Referenced by be_create_static_hash(), and fe_alloc_handle().
int(* bh_context_be_s::lookup) (bh_context_be *be, BIND_HANDLE handle, BHIFS_NODE **node)
Definition at line 94 of file api_handle.c.
Referenced by be_create_static_hash(), fe_destroy_handle(), and fe_lookup().
The documentation for this struct was generated from the following file:
src/api/api_handle.c