CUBRID Engine: cubquery::mvcc_scan_reev_data Struct Reference
cubquery::mvcc_scan_reev_data Struct Reference
#include <query_reevaluation.hpp>
Public Member Functions
void set_filters (upddel_mvcc_cond_reeval &ureev)
Public Attributes
filter_info * range_filter
filter_info * key_filter
filter_info * data_filter
QPROC_QUALIFICATION * qualification
Detailed Description
Definition at line 101 of file query_reevaluation.hpp.
Member Function Documentation
void cubquery::mvcc_scan_reev_data::set_filters (upddel_mvcc_cond_reeval & ureev)
Definition at line 80 of file query_reevaluation.cpp.
References cubquery::upddel_mvcc_cond_reeval::data_filter, cubquery::upddel_mvcc_cond_reeval::key_filter, NULL, cubquery::upddel_mvcc_cond_reeval::range_filter, scan_pred::regu_list, and filter_info::scan_pred.
Referenced by locator_mvcc_reeval_scan_filters(), qexec_execute_selupd_list(), scan_next_heap_scan(), and scan_next_index_lookup_heap().
Member Data Documentation
filter_info* cubquery::mvcc_scan_reev_data::data_filter
Definition at line 105 of file query_reevaluation.hpp.
Referenced by locator_mvcc_reevaluate_filters().
filter_info* cubquery::mvcc_scan_reev_data::key_filter
Definition at line 104 of file query_reevaluation.hpp.
Referenced by locator_mvcc_reevaluate_filters().
QPROC_QUALIFICATION* cubquery::mvcc_scan_reev_data::qualification
Definition at line 107 of file query_reevaluation.hpp.
Referenced by locator_mvcc_reeval_scan_filters(), locator_mvcc_reevaluate_filters(), qexec_execute_selupd_list(), scan_next_heap_scan(), and scan_next_index_lookup_heap().
filter_info* cubquery::mvcc_scan_reev_data::range_filter
Definition at line 103 of file query_reevaluation.hpp.
Referenced by locator_mvcc_reevaluate_filters().
The documentation for this struct was generated from the following files:
src/query/query_reevaluation.hpp
src/query/query_reevaluation.cpp