CUBRID Engine: func_signature Struct Reference
func_signature Struct Reference
#include <func_type.hpp>
Public Member Functions
void to_string_buffer (string_buffer &sb) const
Public Attributes
pt_arg_type ret
pt_group_arg_type fix
pt_group_arg_type rep
Detailed Description
Definition at line 34 of file func_type.hpp.
Member Function Documentation
void func_signature::to_string_buffer (string_buffer & sb) const
Definition at line 537 of file func_type.cpp.
References fix, pt_arg_type_to_string_buffer(), rep, and ret.
Referenced by func_type::Node::invalid_arg_count_error(), func_type::Node::invalid_arg_error(), and func_type::Node::invalid_coll_error().
Member Data Documentation
pt_group_arg_type func_signature::fix
Definition at line 37 of file func_type.hpp.
Referenced by func_type::Node::apply_signature(), func_type::sig_has_json_args(), and to_string_buffer().
pt_group_arg_type func_signature::rep
Definition at line 38 of file func_type.hpp.
Referenced by func_type::Node::apply_signature(), func_type::sig_has_json_args(), and to_string_buffer().
pt_arg_type func_signature::ret
Definition at line 36 of file func_type.hpp.
Referenced by func_type::Node::set_return_type(), and to_string_buffer().
The documentation for this struct was generated from the following files:
src/parser/func_type.hpp
src/parser/func_type.cpp