CUBRID Engine: pr_type Struct Reference
pr_type Struct Reference
#include <object_primitive.h>
Public Types
typedef void(* initmem_function_type) (void *memptr, struct tp_domain *domain)
typedef void(* initval_function_type) (DB_VALUE *value, int precision, int scale)
typedef int(* setmem_function_type) (void *memptr, struct tp_domain *domain, DB_VALUE *value)
typedef int(* getmem_function_type) (void *memptr, struct tp_domain *domain, DB_VALUE *value, bool copy)
typedef int(* setval_function_type) (DB_VALUE *dest, const DB_VALUE *src, bool copy)
typedef int(* data_lengthmem_function_type) (void *memptr, struct tp_domain *domain, int disk)
typedef int(* data_lengthval_function_type) (DB_VALUE *value, int disk)
typedef void(* data_writemem_function_type) (struct or_buf *buf, void *memptr, struct tp_domain *domain)
typedef void(* data_readmem_function_type) (struct or_buf *buf, void *memptr, struct tp_domain *domain, int size)
typedef int(* data_writeval_function_type) (struct or_buf *buf, DB_VALUE *value)
typedef int(* data_readval_function_type) (struct or_buf *buf, DB_VALUE *value, struct tp_domain *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
typedef int(* index_lengthmem_function_type) (void *memptr, struct tp_domain *domain)
typedef int(* index_lengthval_function_type) (DB_VALUE *value)
typedef int(* index_writeval_function_type) (struct or_buf *buf, DB_VALUE *value)
typedef int(* index_readval_function_type) (struct or_buf *buf, DB_VALUE *value, struct tp_domain *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
typedef DB_VALUE_COMPARE_RESULT(* index_cmpdisk_function_type) (void *memptr1, void *memptr2, struct tp_domain *domain, int do_coercion, int total_order, int *start_colp)
typedef void(* freemem_function_type) (void *memptr)
typedef DB_VALUE_COMPARE_RESULT(* data_cmpdisk_function_type) (void *memptr1, void *memptr2, tp_domain *domain, int do_coercion, int total_order, int *start_colp)
typedef DB_VALUE_COMPARE_RESULT(* cmpval_function_type) (DB_VALUE *value, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
Public Member Functions
pr_type ()=delete
pr_type (const char *name_arg, DB_TYPE id_arg, int varp_arg, int size_arg, int disksize_arg, int align_arg, initmem_function_type initmem_f_arg, initval_function_type initval_f_arg, setmem_function_type setmem_f_arg, getmem_function_type getmem_f_arg, setval_function_type setval_f_arg, data_lengthmem_function_type data_lengthmem_f_arg, data_lengthval_function_type data_lengthval_f_arg, data_writemem_function_type data_writemem_f_arg, data_readmem_function_type data_readmem_f_arg, data_writeval_function_type data_writeval_f_arg, data_readval_function_type data_readval_f_arg, index_lengthmem_function_type index_lengthmem_f_arg, index_lengthval_function_type index_lengthval_f_arg, index_writeval_function_type index_writeval_f_arg, index_readval_function_type index_readval_f_arg, index_cmpdisk_function_type index_cmpdisk_f_arg, freemem_function_type freemem_f_arg, data_cmpdisk_function_type data_cmpdisk_f_arg, cmpval_function_type cmpval_f_arg)
const char * get_name () const
DB_TYPE get_id () const
size_t get_alignment () const
void set_data_cmpdisk_function (data_cmpdisk_function_type data_cmpdisk_arg)
data_cmpdisk_function_type get_data_cmpdisk_function () const
void set_cmpval_function (cmpval_function_type cmpval_arg)
cmpval_function_type get_cmpval_function () const
bool is_always_variable () const
bool is_size_computed () const
int get_mem_size_of_mem (const void *mem, const tp_domain *domain=NULL) const
int get_disk_size_of_mem (const void *mem, const tp_domain *domain=NULL) const
int get_index_size_of_mem (const void *memptr, const tp_domain *domain) const
int get_mem_size_of_value (const DB_VALUE *value) const
int get_disk_size_of_value (const DB_VALUE *value) const
int get_index_size_of_value (const DB_VALUE *value) const
void initmem (void *memptr, const tp_domain *domain) const
int setmem (void *memptr, const tp_domain *domain, const DB_VALUE *value) const
int getmem (void *memptr, const tp_domain *domain, DB_VALUE *value, bool copy=true) const
void freemem (void *memptr) const
void initval (DB_VALUE *value, int precision, int scale) const
int setval (DB_VALUE *dest, const DB_VALUE *src, bool copy) const
DB_VALUE_COMPARE_RESULT cmpval (const DB_VALUE *value, const DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation) const
void data_writemem (struct or_buf *buf, const void *memptr, const tp_domain *domain) const
void data_readmem (struct or_buf *buf, void *memptr, const tp_domain *domain, int size) const
int data_writeval (struct or_buf *buf, const DB_VALUE *value) const
int data_readval (struct or_buf *buf, DB_VALUE *value, const tp_domain *domain, int size, bool copy, char *copy_buf, int copy_buf_len) const
DB_VALUE_COMPARE_RESULT data_cmpdisk (const void *memptr1, const void *memptr2, const tp_domain *domain, int do_coercion, int total_order, int *start_colp) const
int index_writeval (struct or_buf *buf, const DB_VALUE *value) const
int index_readval (struct or_buf *buf, DB_VALUE *value, const tp_domain *domain, int size, bool copy, char *copy_buf, int copy_buf_len) const
DB_VALUE_COMPARE_RESULT index_cmpdisk (const void *memptr1, const void *memptr2, const tp_domain *domain, int do_coercion, int total_order, int *start_colp) const
Public Attributes
const char * name
DB_TYPE id
int variable_p
int size
int disksize
int alignment
Protected Attributes
initmem_function_type f_initmem
initval_function_type f_initval
setmem_function_type f_setmem
getmem_function_type f_getmem
setval_function_type f_setval
data_lengthmem_function_type f_data_lengthmem
data_lengthval_function_type f_data_lengthval
data_writemem_function_type f_data_writemem
data_readmem_function_type f_data_readmem
data_writeval_function_type f_data_writeval
data_readval_function_type f_data_readval
index_lengthmem_function_type f_index_lengthmem
index_lengthval_function_type f_index_lengthval
index_writeval_function_type f_index_writeval
index_readval_function_type f_index_readval
index_cmpdisk_function_type f_index_cmpdisk
freemem_function_type f_freemem
data_cmpdisk_function_type f_data_cmpdisk
cmpval_function_type f_cmpval
Detailed Description
Definition at line 51 of file object_primitive.h.
Member Typedef Documentation
typedef DB_VALUE_COMPARE_RESULT(* pr_type::cmpval_function_type) (DB_VALUE *value, DB_VALUE *value2, int do_coercion, int total_order, int *start_colp, int collation)
Definition at line 77 of file object_primitive.h.
typedef DB_VALUE_COMPARE_RESULT(* pr_type::data_cmpdisk_function_type) (void *memptr1, void *memptr2, tp_domain *domain, int do_coercion, int total_order, int *start_colp)
Definition at line 75 of file object_primitive.h.
typedef int(* pr_type::data_lengthmem_function_type) (void *memptr, struct tp_domain *domain, int disk)
Definition at line 59 of file object_primitive.h.
typedef int(* pr_type::data_lengthval_function_type) (DB_VALUE *value, int disk)
Definition at line 60 of file object_primitive.h.
typedef void(* pr_type::data_readmem_function_type) (struct or_buf *buf, void *memptr, struct tp_domain *domain, int size)
Definition at line 62 of file object_primitive.h.
typedef int(* pr_type::data_readval_function_type) (struct or_buf *buf, DB_VALUE *value, struct tp_domain *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
Definition at line 64 of file object_primitive.h.
typedef void(* pr_type::data_writemem_function_type) (struct or_buf *buf, void *memptr, struct tp_domain *domain)
Definition at line 61 of file object_primitive.h.
typedef int(* pr_type::data_writeval_function_type) (struct or_buf *buf, DB_VALUE *value)
Definition at line 63 of file object_primitive.h.
typedef void(* pr_type::freemem_function_type) (void *memptr)
Definition at line 74 of file object_primitive.h.
typedef int(* pr_type::getmem_function_type) (void *memptr, struct tp_domain *domain, DB_VALUE *value, bool copy)
Definition at line 57 of file object_primitive.h.
typedef DB_VALUE_COMPARE_RESULT(* pr_type::index_cmpdisk_function_type) (void *memptr1, void *memptr2, struct tp_domain *domain, int do_coercion, int total_order, int *start_colp)
Definition at line 71 of file object_primitive.h.
typedef int(* pr_type::index_lengthmem_function_type) (void *memptr, struct tp_domain *domain)
Definition at line 66 of file object_primitive.h.
typedef int(* pr_type::index_lengthval_function_type) (DB_VALUE *value)
Definition at line 67 of file object_primitive.h.
typedef int(* pr_type::index_readval_function_type) (struct or_buf *buf, DB_VALUE *value, struct tp_domain *domain, int size, bool copy, char *copy_buf, int copy_buf_len)
Definition at line 69 of file object_primitive.h.
typedef int(* pr_type::index_writeval_function_type) (struct or_buf *buf, DB_VALUE *value)
Definition at line 68 of file object_primitive.h.
typedef void(* pr_type::initmem_function_type) (void *memptr, struct tp_domain *domain)
Definition at line 54 of file object_primitive.h.
typedef void(* pr_type::initval_function_type) (DB_VALUE *value, int precision, int scale)
Definition at line 55 of file object_primitive.h.
typedef int(* pr_type::setmem_function_type) (void *memptr, struct tp_domain *domain, DB_VALUE *value)
Definition at line 56 of file object_primitive.h.
typedef int(* pr_type::setval_function_type) (DB_VALUE *dest, const DB_VALUE *src, bool copy)
Definition at line 58 of file object_primitive.h.
Constructor & Destructor Documentation
pr_type::pr_type () delete
pr_type::pr_type (const char * name_arg, DB_TYPE id_arg, int varp_arg, int size_arg, int disksize_arg, int align_arg, initmem_function_type initmem_f_arg, initval_function_type initval_f_arg, setmem_function_type setmem_f_arg, getmem_function_type getmem_f_arg, setval_function_type setval_f_arg, data_lengthmem_function_type data_lengthmem_f_arg, data_lengthval_function_type data_lengthval_f_arg, data_writemem_function_type data_writemem_f_arg, data_readmem_function_type data_readmem_f_arg, data_writeval_function_type data_writeval_f_arg, data_readval_function_type data_readval_f_arg, index_lengthmem_function_type index_lengthmem_f_arg, index_lengthval_function_type index_lengthval_f_arg, index_writeval_function_type index_writeval_f_arg, index_readval_function_type index_readval_f_arg, index_cmpdisk_function_type index_cmpdisk_f_arg, freemem_function_type freemem_f_arg, data_cmpdisk_function_type data_cmpdisk_f_arg, cmpval_function_type cmpval_f_arg)
Definition at line 150 of file object_primitive.c.
References alignment, disksize, f_cmpval, f_data_cmpdisk, f_data_lengthmem, f_data_lengthval, f_data_readmem, f_data_readval, f_data_writemem, f_data_writeval, f_freemem, f_getmem, f_index_cmpdisk, f_index_lengthmem, f_index_lengthval, f_index_readval, f_index_writeval, f_initmem, f_initval, f_setmem, f_setval, size, and variable_p.
Member Function Documentation
DB_VALUE_COMPARE_RESULT pr_type::cmpval (const DB_VALUE * value, const DB_VALUE * value2, int do_coercion, int total_order, int * start_colp, int collation) const inline
Definition at line 577 of file object_primitive.h.
References f_cmpval.
Referenced by btree_compare_individual_key_value(), btree_compare_key(), qdata_calculate_aggregate_cume_dist_percent_rank(), qdata_evaluate_analytic_func(), qexec_compare_valptr_with_tuple(), qexec_topn_cmpval(), qfile_compare_tuple_values(), qfile_compare_with_interpolation_domain(), and tp_value_compare_with_error().
DB_VALUE_COMPARE_RESULT pr_type::data_cmpdisk (const void * memptr1, const void * memptr2, const tp_domain * domain, int do_coercion, int total_order, int * start_colp) const inline
Definition at line 569 of file object_primitive.h.
References f_data_cmpdisk.
void pr_type::data_readmem (struct or_buf * buf, void * memptr, const tp_domain * domain, int size) const inline
Definition at line 492 of file object_primitive.h.
Referenced by disk_to_domain2(), get_current(), and get_old().
int pr_type::data_readval (struct or_buf * buf, DB_VALUE * value, const tp_domain * domain, int size, bool copy, char * copy_buf, int copy_buf_len) const inline
Definition at line 504 of file object_primitive.h.
References f_data_readval.
Referenced by btree_construct_leafs(), catcls_get_object_set(), catcls_get_or_value_from_attribute(), catcls_get_or_value_from_attrid(), catcls_get_or_value_from_class(), catcls_get_or_value_from_domain(), catcls_get_or_value_from_method(), catcls_get_or_value_from_method_argument(), catcls_get_or_value_from_method_file(), catcls_get_or_value_from_method_signiture(), catcls_get_or_value_from_partition(), catcls_get_or_value_from_query_spec(), catcls_get_or_value_from_resolution(), catcls_get_property_set(), compare_driver(), cursor_copy_vobj_to_dbvalue(), cursor_get_tuple_value_to_dbvalue(), disk_to_attribute(), disk_to_class(), disk_to_methfile(), disk_to_method(), disk_to_resolution(), eval_item_card_sort_list(), eval_some_list_eval(), eval_sub_sort_list_to_multi_set(), eval_sub_sort_list_to_sort_list(), fetch_peek_dbval(), fetch_peek_dbval_pos(), get_desc_old(), get_object_set(), get_property_list(), get_string(), heap_attrvalue_read(), heap_classrepr_dump(), heap_midxkey_get_value(), or_get_enumeration(), or_get_json_schema(), or_get_value(), or_unpack_mem_value(), qdata_convert_table_to_set(), qdata_finalize_aggregate_list(), qdata_finalize_analytic_func(), qdata_get_single_tuple_from_list_id(), qdata_load_agg_hentry_from_tuple(), qexec_analytic_sort_key_header_load(), qexec_compare_valptr_with_tuple(), qexec_get_attr_default(), qexec_get_tuple_column_value(), qfile_compare_tuple_values(), and qfile_compare_with_interpolation_domain().
void pr_type::data_writemem (struct or_buf * buf, const void * memptr, const tp_domain * domain) const inline
Definition at line 486 of file object_primitive.h.
Referenced by put_attributes().
int pr_type::data_writeval (struct or_buf * buf, const DB_VALUE * value) const inline
Definition at line 498 of file object_primitive.h.
References f_data_writeval.
Referenced by btree_sort_get_next(), domain_to_disk(), heap_attrinfo_transform_to_disk_internal(), or_pack_mem_value(), or_pack_mop(), or_put_enumeration(), or_put_json_schema(), or_put_value(), pr_data_writeval(), put_property_list(), put_string(), qdata_copy_db_value_to_tuple_value(), qdata_evaluate_aggregate_list(), qdata_evaluate_analytic_func(), qfile_fast_intval_tuple_to_list(), qfile_fast_val_tuple_to_list(), qfile_set_tuple_column_value(), and vid_pack_db_value().
void pr_type::freemem (void * memptr) const inline
Definition at line 560 of file object_primitive.h.
References f_freemem, and NULL.
Referenced by obj_free_memory().
size_t pr_type::get_alignment () const inline
Definition at line 372 of file object_primitive.h.
References alignment.
pr_type::cmpval_function_type pr_type::get_cmpval_function () const
Definition at line 208 of file object_primitive.c.
References HL::align(), alignment, f_cmpval, getmem_elo_with_type(), mr_cmpdisk_bit_internal(), mr_cmpdisk_char_internal(), mr_cmpdisk_nchar_internal(), mr_cmpval_bigint(), mr_cmpval_bit(), mr_cmpval_bit2(), mr_cmpval_char(), mr_cmpval_date(), mr_cmpval_datetime(), mr_cmpval_datetimetz(), mr_cmpval_double(), mr_cmpval_elo(), mr_cmpval_enumeration(), mr_cmpval_error(), mr_cmpval_float(), mr_cmpval_int(), mr_cmpval_json(), mr_cmpval_midxkey(), mr_cmpval_money(), mr_cmpval_nchar(), mr_cmpval_null(), mr_cmpval_numeric(), mr_cmpval_object(), mr_cmpval_oid(), mr_cmpval_ptr(), mr_cmpval_resultset(), mr_cmpval_sequence(), mr_cmpval_set(), mr_cmpval_short(), mr_cmpval_string(), mr_cmpval_sub(), mr_cmpval_time(), mr_cmpval_timestamptz(), mr_cmpval_utime(), mr_cmpval_varbit(), mr_cmpval_varbit2(), mr_cmpval_variable(), mr_cmpval_varnchar(), mr_cmpval_vobj(), mr_data_cmpdisk_bigint(), mr_data_cmpdisk_bit(), mr_data_cmpdisk_char(), mr_data_cmpdisk_date(), mr_data_cmpdisk_datetime(), mr_data_cmpdisk_datetimetz(), mr_data_cmpdisk_double(), mr_data_cmpdisk_elo(), mr_data_cmpdisk_enumeration(), mr_data_cmpdisk_error(), mr_data_cmpdisk_float(), mr_data_cmpdisk_int(), mr_data_cmpdisk_json(), mr_data_cmpdisk_midxkey(), mr_data_cmpdisk_money(), mr_data_cmpdisk_nchar(), mr_data_cmpdisk_null(), mr_data_cmpdisk_numeric(), mr_data_cmpdisk_object(), mr_data_cmpdisk_oid(), mr_data_cmpdisk_ptr(), mr_data_cmpdisk_resultset(), mr_data_cmpdisk_sequence(), mr_data_cmpdisk_set(), mr_data_cmpdisk_short(), mr_data_cmpdisk_string(), mr_data_cmpdisk_sub(), mr_data_cmpdisk_time(), mr_data_cmpdisk_timestamptz(), mr_data_cmpdisk_utime(), mr_data_cmpdisk_varbit(), mr_data_cmpdisk_variable(), mr_data_cmpdisk_varnchar(), mr_data_cmpdisk_vobj(), mr_data_lengthmem_bit(), mr_data_lengthmem_char(), mr_data_lengthmem_elo(), mr_data_lengthmem_error(), mr_data_lengthmem_json(), mr_data_lengthmem_midxkey(), mr_data_lengthmem_nchar(), mr_data_lengthmem_numeric(), mr_data_lengthmem_ptr(), mr_data_lengthmem_set(), mr_data_lengthmem_string(), mr_data_lengthmem_sub(), mr_data_lengthmem_varbit(), mr_data_lengthmem_varnchar(), mr_data_lengthval_bit(), mr_data_lengthval_char(), mr_data_lengthval_elo(), mr_data_lengthval_error(), mr_data_lengthval_json(), mr_data_lengthval_midxkey(), mr_data_lengthval_nchar(), mr_data_lengthval_numeric(), mr_data_lengthval_object(), mr_data_lengthval_ptr(), mr_data_lengthval_set(), mr_data_lengthval_string(), mr_data_lengthval_sub(), mr_data_lengthval_varbit(), mr_data_lengthval_variable(), mr_data_lengthval_varnchar(), mr_data_readmem_bigint(), mr_data_readmem_bit(), mr_data_readmem_char(), mr_data_readmem_date(), mr_data_readmem_datetime(), mr_data_readmem_datetimetz(), mr_data_readmem_double(), mr_data_readmem_elo(), mr_data_readmem_enumeration(), mr_data_readmem_error(), mr_data_readmem_float(), mr_data_readmem_int(), mr_data_readmem_json(), mr_data_readmem_money(), mr_data_readmem_nchar(), mr_data_readmem_null(), mr_data_readmem_numeric(), mr_data_readmem_object(), mr_data_readmem_oid(), mr_data_readmem_ptr(), mr_data_readmem_resultset(), mr_data_readmem_set(), mr_data_readmem_short(), mr_data_readmem_string(), mr_data_readmem_sub(), mr_data_readmem_time(), mr_data_readmem_timestamptz(), mr_data_readmem_utime(), mr_data_readmem_varbit(), mr_data_readmem_varnchar(), mr_data_readval_bigint(), mr_data_readval_bit(), mr_data_readval_blob(), mr_data_readval_char(), mr_data_readval_clob(), mr_data_readval_date(), mr_data_readval_datetime(), mr_data_readval_datetimeltz(), mr_data_readval_datetimetz(), mr_data_readval_double(), mr_data_readval_elo(), mr_data_readval_enumeration(), mr_data_readval_error(), mr_data_readval_float(), mr_data_readval_int(), mr_data_readval_json(), mr_data_readval_midxkey(), mr_data_readval_money(), mr_data_readval_nchar(), mr_data_readval_null(), mr_data_readval_numeric(), mr_data_readval_object(), mr_data_readval_oid(), mr_data_readval_ptr(), mr_data_readval_resultset(), mr_data_readval_set(), mr_data_readval_short(), mr_data_readval_string(), mr_data_readval_sub(), mr_data_readval_time(), mr_data_readval_timestampltz(), mr_data_readval_timestamptz(), mr_data_readval_utime(), mr_data_readval_varbit(), mr_data_readval_variable(), mr_data_readval_varnchar(), mr_data_readval_vobj(), mr_data_writemem_bigint(), mr_data_writemem_bit(), mr_data_writemem_char(), mr_data_writemem_date(), mr_data_writemem_datetime(), mr_data_writemem_datetimetz(), mr_data_writemem_double(), mr_data_writemem_elo(), mr_data_writemem_enumeration(), mr_data_writemem_error(), mr_data_writemem_float(), mr_data_writemem_int(), mr_data_writemem_json(), mr_data_writemem_money(), mr_data_writemem_nchar(), mr_data_writemem_null(), mr_data_writemem_numeric(), mr_data_writemem_object(), mr_data_writemem_oid(), mr_data_writemem_ptr(), mr_data_writemem_resultset(), mr_data_writemem_set(), mr_data_writemem_short(), mr_data_writemem_string(), mr_data_writemem_sub(), mr_data_writemem_time(), mr_data_writemem_timestamptz(), mr_data_writemem_utime(), mr_data_writemem_varbit(), mr_data_writemem_varnchar(), mr_data_writeval_bigint(), mr_data_writeval_bit(), mr_data_writeval_char(), mr_data_writeval_date(), mr_data_writeval_datetime(), mr_data_writeval_datetimetz(), mr_data_writeval_double(), mr_data_writeval_elo(), mr_data_writeval_enumeration(), mr_data_writeval_error(), mr_data_writeval_float(), mr_data_writeval_int(), mr_data_writeval_json(), mr_data_writeval_midxkey(), mr_data_writeval_money(), mr_data_writeval_nchar(), mr_data_writeval_null(), mr_data_writeval_numeric(), mr_data_writeval_object(), mr_data_writeval_oid(), mr_data_writeval_ptr(), mr_data_writeval_resultset(), mr_data_writeval_set(), mr_data_writeval_short(), mr_data_writeval_string(), mr_data_writeval_sub(), mr_data_writeval_time(), mr_data_writeval_timestamptz(), mr_data_writeval_utime(), mr_data_writeval_varbit(), mr_data_writeval_variable(), mr_data_writeval_varnchar(), mr_freemem_bit(), mr_freemem_char(), mr_freemem_elo(), mr_freemem_json(), mr_freemem_nchar(), mr_freemem_set(), mr_freemem_string(), mr_freemem_varbit(), mr_freemem_varnchar(), mr_getmem_bigint(), mr_getmem_bit(), mr_getmem_blob(), mr_getmem_char(), mr_getmem_clob(), mr_getmem_date(), mr_getmem_datetime(), mr_getmem_datetimeltz(), mr_getmem_datetimetz(), mr_getmem_double(), mr_getmem_elo(), mr_getmem_enumeration(), mr_getmem_error(), mr_getmem_float(), mr_getmem_int(), mr_getmem_json(), mr_getmem_money(), mr_getmem_multiset(), mr_getmem_nchar(), mr_getmem_null(), mr_getmem_numeric(), mr_getmem_object(), mr_getmem_oid(), mr_getmem_ptr(), mr_getmem_resultset(), mr_getmem_sequence(), mr_getmem_set(), mr_getmem_short(), mr_getmem_string(), mr_getmem_sub(), mr_getmem_time(), mr_getmem_timestampltz(), mr_getmem_timestamptz(), mr_getmem_utime(), mr_getmem_varbit(), mr_getmem_varnchar(), mr_index_cmpdisk_bigint(), mr_index_cmpdisk_bit(), mr_index_cmpdisk_char(), mr_index_cmpdisk_date(), mr_index_cmpdisk_datetime(), mr_index_cmpdisk_datetimetz(), mr_index_cmpdisk_double(), mr_index_cmpdisk_enumeration(), mr_index_cmpdisk_float(), mr_index_cmpdisk_int(), mr_index_cmpdisk_midxkey(), mr_index_cmpdisk_money(), mr_index_cmpdisk_nchar(), mr_index_cmpdisk_numeric(), mr_index_cmpdisk_object(), mr_index_cmpdisk_oid(), mr_index_cmpdisk_short(), mr_index_cmpdisk_string(), mr_index_cmpdisk_time(), mr_index_cmpdisk_timestamptz(), mr_index_cmpdisk_utime(), mr_index_cmpdisk_varbit(), mr_index_cmpdisk_varnchar(), mr_index_lengthmem_bit(), mr_index_lengthmem_char(), mr_index_lengthmem_midxkey(), mr_index_lengthmem_nchar(), mr_index_lengthmem_numeric(), mr_index_lengthmem_string(), mr_index_lengthmem_varbit(), mr_index_lengthmem_varnchar(), mr_index_lengthval_bit(), mr_index_lengthval_char(), mr_index_lengthval_midxkey(), mr_index_lengthval_nchar(), mr_index_lengthval_numeric(), mr_index_lengthval_string(), mr_index_lengthval_varbit(), mr_index_lengthval_varnchar(), mr_index_readval_bigint(), mr_index_readval_bit(), mr_index_readval_char(), mr_index_readval_date(), mr_index_readval_datetime(), mr_index_readval_datetimeltz(), mr_index_readval_datetimetz(), mr_index_readval_double(), mr_index_readval_enumeration(), mr_index_readval_float(), mr_index_readval_int(), mr_index_readval_midxkey(), mr_index_readval_money(), mr_index_readval_nchar(), mr_index_readval_numeric(), mr_index_readval_object(), mr_index_readval_oid(), mr_index_readval_short(), mr_index_readval_string(), mr_index_readval_time(), mr_index_readval_timestampltz(), mr_index_readval_timestamptz(), mr_index_readval_utime(), mr_index_readval_varbit(), mr_index_readval_varnchar(), mr_index_writeval_bigint(), mr_index_writeval_bit(), mr_index_writeval_char(), mr_index_writeval_date(), mr_index_writeval_datetime(), mr_index_writeval_datetimetz(), mr_index_writeval_double(), mr_index_writeval_enumeration(), mr_index_writeval_float(), mr_index_writeval_int(), mr_index_writeval_midxkey(), mr_index_writeval_money(), mr_index_writeval_nchar(), mr_index_writeval_numeric(), mr_index_writeval_object(), mr_index_writeval_oid(), mr_index_writeval_short(), mr_index_writeval_string(), mr_index_writeval_time(), mr_index_writeval_timestamptz(), mr_index_writeval_utime(), mr_index_writeval_varbit(), mr_index_writeval_varnchar(), mr_initmem_bigint(), mr_initmem_bit(), mr_initmem_char(), mr_initmem_date(), mr_initmem_datetime(), mr_initmem_datetimetz(), mr_initmem_double(), mr_initmem_elo(), mr_initmem_enumeration(), mr_initmem_error(), mr_initmem_float(), mr_initmem_int(), mr_initmem_json(), mr_initmem_money(), mr_initmem_nchar(), mr_initmem_null(), mr_initmem_numeric(), mr_initmem_object(), mr_initmem_oid(), mr_initmem_ptr(), mr_initmem_resultset(), mr_initmem_set(), mr_initmem_short(), mr_initmem_string(), mr_initmem_sub(), mr_initmem_time(), mr_initmem_timestamptz(), mr_initmem_utime(), mr_initmem_varbit(), mr_initmem_varnchar(), mr_initval_bigint(), mr_initval_bit(), mr_initval_blob(), mr_initval_char(), mr_initval_clob(), mr_initval_date(), mr_initval_datetime(), mr_initval_datetimeltz(), mr_initval_datetimetz(), mr_initval_double(), mr_initval_elo(), mr_initval_enumeration(), mr_initval_error(), mr_initval_float(), mr_initval_int(), mr_initval_json(), mr_initval_midxkey(), mr_initval_money(), mr_initval_multiset(), mr_initval_nchar(), mr_initval_null(), mr_initval_numeric(), mr_initval_object(), mr_initval_oid(), mr_initval_ptr(), mr_initval_resultset(), mr_initval_sequence(), mr_initval_set(), mr_initval_short(), mr_initval_string(), mr_initval_sub(), mr_initval_time(), mr_initval_timestampltz(), mr_initval_timestamptz(), mr_initval_utime(), mr_initval_varbit(), mr_initval_variable(), mr_initval_varnchar(), mr_initval_vobj(), mr_lengthval_string_internal(), mr_lengthval_varbit_internal(), mr_lengthval_varnchar_internal(), mr_null_oid(), mr_readval_bit_internal(), mr_readval_char_internal(), mr_readval_nchar_internal(), mr_readval_string_internal(), mr_readval_varbit_internal(), mr_readval_varnchar_internal(), mr_setmem_bigint(), mr_setmem_bit(), mr_setmem_char(), mr_setmem_date(), mr_setmem_datetime(), mr_setmem_datetimetz(), mr_setmem_double(), mr_setmem_elo(), mr_setmem_enumeration(), mr_setmem_error(), mr_setmem_float(), mr_setmem_int(), mr_setmem_json(), mr_setmem_money(), mr_setmem_nchar(), mr_setmem_null(), mr_setmem_numeric(), mr_setmem_object(), mr_setmem_oid(), mr_setmem_ptr(), mr_setmem_resultset(), mr_setmem_set(), mr_setmem_short(), mr_setmem_string(), mr_setmem_sub(), mr_setmem_time(), mr_setmem_timestamptz(), mr_setmem_utime(), mr_setmem_varbit(), mr_setmem_varnchar(), mr_setval_bigint(), mr_setval_bit(), mr_setval_blob(), mr_setval_char(), mr_setval_clob(), mr_setval_date(), mr_setval_datetime(), mr_setval_datetimeltz(), mr_setval_datetimetz(), mr_setval_double(), mr_setval_elo(), mr_setval_enumeration(), mr_setval_enumeration_internal(), mr_setval_error(), mr_setval_float(), mr_setval_int(), mr_setval_json(), mr_setval_midxkey(), mr_setval_money(), mr_setval_multiset(), mr_setval_nchar(), mr_setval_null(), mr_setval_numeric(), mr_setval_object(), mr_setval_oid(), mr_setval_ptr(), mr_setval_resultset(), mr_setval_sequence(), mr_setval_set(), mr_setval_set_internal(), mr_setval_short(), mr_setval_string(), mr_setval_sub(), mr_setval_time(), mr_setval_timestampltz(), mr_setval_timestamptz(), mr_setval_utime(), mr_setval_varbit(), mr_setval_variable(), mr_setval_varnchar(), mr_setval_vobj(), mr_writeval_bit_internal(), mr_writeval_char_internal(), mr_writeval_nchar_internal(), mr_writeval_string_internal(), mr_writeval_varbit_internal(), mr_writeval_varnchar_internal(), peekmem_elo(), pr_midxkey_compare_element(), pr_midxkey_get_element_internal(), pr_midxkey_get_vals_size(), pr_write_compressed_string_to_buffer(), pr_write_uncompressed_string_to_buffer(), readval_elo_with_type(), setval_elo_with_type(), and size.
pr_type::data_cmpdisk_function_type pr_type::get_data_cmpdisk_function () const
Definition at line 196 of file object_primitive.c.
References f_data_cmpdisk.
Referenced by qfile_initialize_sort_key_info().
int pr_type::get_disk_size_of_mem (const void * mem, const tp_domain * domain = NULL) const inline
Definition at line 393 of file object_primitive.h.
References assert, DB_TYPE_NULL, disksize, f_data_lengthmem, and NULL.
Referenced by object_size(), put_varinfo(), and tp_domain_disk_size().
int pr_type::get_disk_size_of_value (const DB_VALUE * value) const inline
Definition at line 435 of file object_primitive.h.
References assert, DB_TYPE_NULL, disksize, f_data_lengthval, and NULL.
Referenced by btree_insert_list::add_key(), btree_sort_get_next(), catcls_guess_record_length(), or_packed_enumeration_size(), or_packed_json_schema_length(), or_packed_value_size(), pr_data_writeval_disk_size(), property_list_size(), qdata_get_tuple_value_size_from_dbval(), and string_disk_size().
DB_TYPE pr_type::get_id () const inline
Definition at line 366 of file object_primitive.h.
References id.
Referenced by cubload::server_object_loader::process_collection_constant(), cubload::server_object_loader::process_generic_constant(), cubload::server_object_loader::process_monetary_constant(), tp_domain_disk_size(), and tp_domain_memory_size().
int pr_type::get_index_size_of_mem (const void * memptr, const tp_domain * domain) const inline
Definition at line 511 of file object_primitive.h.
References assert, DB_TYPE_NULL, disksize, f_index_lengthmem, and NULL.
Referenced by pr_midxkey_element_disk_size().
int pr_type::get_index_size_of_value (const DB_VALUE * value) const inline
Definition at line 525 of file object_primitive.h.
References assert, DB_TYPE_NULL, disksize, f_index_lengthval, and NULL.
Referenced by btree_split_node(), btree_split_root(), btree_split_test(), do_create_midxkey_for_constraint(), and pr_index_writeval_disk_size().
int pr_type::get_mem_size_of_mem (const void * mem, const tp_domain * domain = NULL) const inline
Definition at line 407 of file object_primitive.h.
References assert, DB_TYPE_NULL, f_data_lengthmem, NULL, and size.
Referenced by sm_object_size_quick(), and tp_domain_memory_size().
int pr_type::get_mem_size_of_value (const DB_VALUE * value) const inline
Definition at line 421 of file object_primitive.h.
References assert, DB_TYPE_NULL, f_data_lengthval, NULL, and size.
Referenced by pr_value_mem_size().
const char * pr_type::get_name (void) const inline
Definition at line 360 of file object_primitive.h.
References name.
Referenced by cubload::server_object_loader::process_collection_constant(), cubload::to_db_double(), and cubload::to_db_float().
int pr_type::getmem (void * memptr, const tp_domain * domain, DB_VALUE * value, bool copy = true) const inline
Definition at line 474 of file object_primitive.h.
References f_getmem.
Referenced by get_object_value(), get_set_value(), obj_get_value(), vid_compare_non_updatable_objects(), and ws_rehash_vmop().
DB_VALUE_COMPARE_RESULT pr_type::index_cmpdisk (const void * memptr1, const void * memptr2, const tp_domain * domain, int do_coercion, int total_order, int * start_colp) const inline
Definition at line 552 of file object_primitive.h.
References f_index_cmpdisk.
Referenced by compare_driver().
int pr_type::index_readval (struct or_buf * buf, DB_VALUE * value, const tp_domain * domain, int size, bool copy, char * copy_buf, int copy_buf_len) const inline
Definition at line 545 of file object_primitive.h.
References f_index_readval.
Referenced by btree_check_valid_record(), btree_fix_root_for_delete(), btree_load_overflow_key(), btree_read_record_without_decompression(), btree_rv_read_keyval_info_nocopy(), and pr_midxkey_compare_element().
int pr_type::index_writeval (struct or_buf * buf, const DB_VALUE * value) const inline
Definition at line 539 of file object_primitive.h.
References f_index_writeval.
Referenced by btree_recompress_record(), btree_rv_save_keyval_for_undo(), btree_rv_save_keyval_for_undo_two_objects(), btree_store_overflow_key(), btree_write_record(), heap_midxkey_key_generate(), and heap_midxkey_key_get().
void pr_type::initmem (void * memptr, const tp_domain * domain) const inline
Definition at line 449 of file object_primitive.h.
Referenced by clear_new_unbound(), and obj_alloc().
void pr_type::initval (DB_VALUE * value, int precision, int scale) const inline
Definition at line 461 of file object_primitive.h.
References tp_domain::precision, and tp_domain::scale.
Referenced by or_pack_mop(), and tp_init_value_domain().
bool pr_type::is_always_variable () const inline
Definition at line 378 of file object_primitive.h.
References variable_p.
Referenced by tp_domain_disk_size().
bool pr_type::is_size_computed () const inline
Definition at line 386 of file object_primitive.h.
References assert, f_data_lengthmem, f_data_lengthval, and NULL.
Referenced by qdata_get_tuple_value_size_from_dbval().
void pr_type::set_cmpval_function (cmpval_function_type cmpval_arg)
Definition at line 202 of file object_primitive.c.
References f_cmpval.
Referenced by qexec_execute_connect_by().
void pr_type::set_data_cmpdisk_function (data_cmpdisk_function_type data_cmpdisk_arg)
Definition at line 190 of file object_primitive.c.
References f_data_cmpdisk.
Referenced by qexec_execute_connect_by().
int pr_type::setmem (void * memptr, const tp_domain * domain, const DB_VALUE * value) const inline
Definition at line 467 of file object_primitive.h.
References f_setmem.
Referenced by assign_null_value(), assign_set_value(), clear_new_unbound(), get_object_value(), ldr_class_oid_db_object(), ldr_date_db_date(), ldr_datetime_db_datetime(), ldr_datetimeltz_db_datetimeltz(), ldr_datetimetz_db_datetimetz(), ldr_elo_ext_db_elo(), ldr_int_db_bigint(), ldr_int_db_int(), ldr_int_db_short(), ldr_monetary_db_monetary(), ldr_null_db_generic(), ldr_oid_db_object(), ldr_real_db_double(), ldr_real_db_float(), ldr_str_db_char(), ldr_str_db_varchar(), ldr_time_db_time(), ldr_timestamp_db_timestamp(), ldr_timestampltz_db_timestampltz(), ldr_timestamptz_db_timestamptz(), and obj_assign_value().
int pr_type::setval (DB_VALUE * dest, const DB_VALUE * src, bool copy) const inline
Definition at line 480 of file object_primitive.h.
References f_setval.
Referenced by btree_build_nleafs(), btree_find_split_point(), db_string_truncate(), heap_attrinfo_set(), or_pack_mop(), pr_clone_value(), qdata_aggregate_accumulator_to_accumulator(), qdata_copy_db_value(), qdata_evaluate_analytic_func(), qdata_finalize_aggregate_list(), qdata_finalize_analytic_func(), and valcnv_convert_value_to_string().
Member Data Documentation
int pr_type::alignment
Definition at line 88 of file object_primitive.h.
Referenced by get_alignment(), get_cmpval_function(), order_atts_by_alignment(), and pr_type().
int pr_type::disksize
Definition at line 87 of file object_primitive.h.
Referenced by get_disk_size_of_mem(), get_disk_size_of_value(), get_index_size_of_mem(), get_index_size_of_value(), mr_data_readmem_bigint(), mr_data_readmem_date(), mr_data_readmem_datetime(), mr_data_readmem_datetimetz(), mr_data_readmem_double(), mr_data_readmem_enumeration(), mr_data_readmem_float(), mr_data_readmem_int(), mr_data_readmem_money(), mr_data_readmem_object(), mr_data_readmem_resultset(), mr_data_readmem_short(), mr_data_readmem_time(), mr_data_readmem_timestamptz(), mr_data_readmem_utime(), mr_data_readval_bigint(), mr_data_readval_date(), mr_data_readval_datetime(), mr_data_readval_datetimeltz(), mr_data_readval_datetimetz(), mr_data_readval_double(), mr_data_readval_enumeration(), mr_data_readval_float(), mr_data_readval_int(), mr_data_readval_money(), mr_data_readval_object(), mr_data_readval_oid(), mr_data_readval_resultset(), mr_data_readval_short(), mr_data_readval_time(), mr_data_readval_timestampltz(), mr_data_readval_timestamptz(), mr_data_readval_utime(), mr_index_cmpdisk_money(), mr_index_lengthval_object(), mr_index_readval_bigint(), mr_index_readval_date(), mr_index_readval_datetime(), mr_index_readval_datetimeltz(), mr_index_readval_datetimetz(), mr_index_readval_double(), mr_index_readval_enumeration(), mr_index_readval_float(), mr_index_readval_int(), mr_index_readval_money(), mr_index_readval_oid(), mr_index_readval_short(), mr_index_readval_time(), mr_index_readval_timestampltz(), mr_index_readval_timestamptz(), mr_index_readval_utime(), mr_index_writeval_bigint(), mr_index_writeval_date(), mr_index_writeval_datetime(), mr_index_writeval_datetimetz(), mr_index_writeval_double(), mr_index_writeval_enumeration(), mr_index_writeval_float(), mr_index_writeval_int(), mr_index_writeval_money(), mr_index_writeval_oid(), mr_index_writeval_short(), mr_index_writeval_time(), mr_index_writeval_timestamptz(), mr_index_writeval_utime(), object_set_size(), pr_type(), qexec_analytic_group_header_load(), qexec_analytic_sort_key_header_load(), qfile_fast_intint_tuple_to_list(), and qfile_fast_intval_tuple_to_list().
cmpval_function_type pr_type::f_cmpval protected
Definition at line 109 of file object_primitive.h.
Referenced by cmpval(), get_cmpval_function(), pr_type(), and set_cmpval_function().
data_cmpdisk_function_type pr_type::f_data_cmpdisk protected
Definition at line 108 of file object_primitive.h.
Referenced by data_cmpdisk(), get_data_cmpdisk_function(), pr_type(), and set_data_cmpdisk_function().
data_lengthmem_function_type pr_type::f_data_lengthmem protected
Definition at line 96 of file object_primitive.h.
Referenced by get_disk_size_of_mem(), get_mem_size_of_mem(), is_size_computed(), and pr_type().
data_lengthval_function_type pr_type::f_data_lengthval protected
Definition at line 97 of file object_primitive.h.
Referenced by get_disk_size_of_value(), get_mem_size_of_value(), is_size_computed(), and pr_type().
data_readmem_function_type pr_type::f_data_readmem protected
Definition at line 99 of file object_primitive.h.
Referenced by pr_type().
data_readval_function_type pr_type::f_data_readval protected
Definition at line 101 of file object_primitive.h.
Referenced by data_readval(), and pr_type().
data_writemem_function_type pr_type::f_data_writemem protected
Definition at line 98 of file object_primitive.h.
Referenced by pr_type().
data_writeval_function_type pr_type::f_data_writeval protected
Definition at line 100 of file object_primitive.h.
Referenced by data_writeval(), and pr_type().
freemem_function_type pr_type::f_freemem protected
Definition at line 107 of file object_primitive.h.
Referenced by freemem(), and pr_type().
getmem_function_type pr_type::f_getmem protected
Definition at line 94 of file object_primitive.h.
Referenced by getmem(), and pr_type().
index_cmpdisk_function_type pr_type::f_index_cmpdisk protected
Definition at line 106 of file object_primitive.h.
Referenced by index_cmpdisk(), and pr_type().
index_lengthmem_function_type pr_type::f_index_lengthmem protected
Definition at line 102 of file object_primitive.h.
Referenced by get_index_size_of_mem(), and pr_type().
index_lengthval_function_type pr_type::f_index_lengthval protected
Definition at line 103 of file object_primitive.h.
Referenced by get_index_size_of_value(), and pr_type().
index_readval_function_type pr_type::f_index_readval protected
Definition at line 105 of file object_primitive.h.
Referenced by index_readval(), and pr_type().
index_writeval_function_type pr_type::f_index_writeval protected
Definition at line 104 of file object_primitive.h.
Referenced by index_writeval(), and pr_type().
initmem_function_type pr_type::f_initmem protected
Definition at line 91 of file object_primitive.h.
Referenced by pr_type().
initval_function_type pr_type::f_initval protected
Definition at line 92 of file object_primitive.h.
Referenced by pr_type().
setmem_function_type pr_type::f_setmem protected
Definition at line 93 of file object_primitive.h.
Referenced by pr_type(), and setmem().
setval_function_type pr_type::f_setval protected
Definition at line 95 of file object_primitive.h.
Referenced by pr_type(), and setval().
DB_TYPE pr_type::id
Definition at line 84 of file object_primitive.h.
Referenced by allocate_index(), attribute_to_disk(), btree_fix_root_for_delete(), btree_fix_root_for_insert(), btree_read_record_without_decompression(), btree_rv_read_keyval_info_nocopy(), btree_store_overflow_key(), construct_index_key_domain(), cursor_copy_vobj_to_dbvalue(), cursor_get_tuple_value_to_dbvalue(), db_attribute_type(), db_seq_create(), db_set_create(), db_set_create_basic(), db_set_create_multi(), db_type_from_string(), delete_object_tuple(), disk_to_attribute(), do_add_attribute_from_select_column(), do_cast_host_variables_to_expected_domain(), do_create_entity(), cubxasl::json_table::column::evaluate_ordinality(), fetch_peek_arith(), get_domain_internal(), get_id(), heap_attrinfo_set(), heap_attrinfo_transform_to_disk_internal(), locator_update_index(), metharg_to_disk(), mr_cmpdisk_char_internal(), obt_apply_assignments(), patchdb(), populate_auto_increment(), pr_complete_enum_value(), pt_add_type_to_set(), pt_assignment_compatible(), pt_check_enum_data_type(), pt_check_partitions(), pt_evaluate_db_value_expr(), pt_expr_get_return_type(), pt_set_host_variables(), pt_sm_attribute_default_value_to_node(), pt_to_delete_xasl(), pt_to_index_info(), pt_to_regu_attr_descr(), pt_wrap_expr_w_exp_dom_cast(), qdata_get_single_tuple_from_list_id(), qexec_schema_get_type_desc(), qfile_locate_tuple_next_value(), func_type::Node::set_return_type(), sm_att_type_id(), sm_load_online_index(), smt_add_constraint(), smt_check_foreign_key(), smt_set_attribute_default(), stran_can_end_after_query_execution(), cubload::to_db_varbit_from_bin_str(), cubload::to_db_varbit_from_hex_str(), tp_domain_copy(), tp_domain_free(), tp_infer_common_domain(), tp_value_cast_internal(), tp_value_compare_with_error(), vid_compare_non_updatable_objects(), and ws_rehash_vmop().
const char* pr_type::name
Definition at line 83 of file object_primitive.h.
Referenced by btree_set_unknown_key_error(), classobj_filter_components(), object_printer::describe_argument(), object_printer::describe_domain(), emit_domain_def(), get_name(), obt_assign_obt(), pr_find_type(), pr_type_name(), PRIM_SET_NULL(), round_date(), round_double(), select_set_domain(), sm_att_type_id(), smt_set_attribute_default(), tp_check_value_size(), and tp_domain_name().
int pr_type::size
Definition at line 86 of file object_primitive.h.
Referenced by get_cmpval_function(), get_mem_size_of_mem(), get_mem_size_of_value(), mr_data_lengthmem_elo(), mr_data_lengthmem_json(), mr_data_lengthmem_set(), mr_data_lengthmem_string(), mr_data_lengthmem_varbit(), mr_data_lengthmem_varnchar(), mr_data_lengthval_json(), mr_data_lengthval_object(), mr_data_lengthval_set(), mr_data_readval_set(), mr_data_writeval_set(), mr_index_readval_midxkey(), mr_writeval_string_internal(), mr_writeval_varnchar_internal(), pr_mem_size(), pr_midxkey_unique_prefix(), and pr_type().
int pr_type::variable_p
Definition at line 85 of file object_primitive.h.
Referenced by assign_null_value(), build_storage_order(), classobj_fixup_loaded_class(), classobj_install_template(), clear_new_unbound(), is_always_variable(), ldr_null_db_generic(), obj_assign_value(), obj_get_value(), object_disk_size(), pr_is_variable_type(), pr_midxkey_element_disk_size(), pr_type(), pt_find_size_from_dbtype(), put_attributes(), put_varinfo(), and sm_object_size_quick().
The documentation for this struct was generated from the following files:
src/object/object_primitive.h
src/object/object_primitive.c