CUBRID Engine: src/base/system_parameter.h File Reference
system_parameter.h File Reference
#include "config.h"
#include <stdio.h>
#include "error_manager.h"
#include "error_code.h"
#include "porting.h"
Classes
union sysprm_value
struct session_param
struct sysprm_assign_value
Macros
#define SYSPRM_LOAD_IS_IGNORE_HA(flags) ((flags) & SYSPRM_IGNORE_HA)
#define SYSPRM_LOAD_IS_IGNORE_INTL(flags) ((flags) & SYSPRM_IGNORE_INTL_PARAMS)
Typedefs
typedef enum compat_mode COMPAT_MODE
typedef enum query_trace_format QUERY_TRACE_FORMAT
typedef enum param_id PARAM_ID
typedef union sysprm_value SYSPRM_VALUE
typedef struct session_param SESSION_PARAM
typedef struct sysprm_assign_value SYSPRM_ASSIGN_VALUE
typedef enum sysprm_load_flag SYSPRM_LOAD_FLAG
Enumerations
enum SYSPRM_ERR {
PRM_ERR_NO_ERROR = NO_ERROR, PRM_ERR_NOT_DIRECTORY = 2, PRM_ERR_INIT_FILE_NOT_CREATED = 3, PRM_ERR_CANT_WRITE = 4,
PRM_ERR_CANT_ACCESS = 6, PRM_ERR_NO_HOME = 7, PRM_ERR_NO_VALUE = 8, PRM_ERR_CANT_OPEN_INIT = 9,
PRM_ERR_BAD_LINE = 10, PRM_ERR_BAD_ENV_VAR = 11, PRM_ERR_UNKNOWN_PARAM = 12, PRM_ERR_BAD_VALUE = 13,
PRM_ERR_NO_MEM_FOR_PRM = 14, PRM_ERR_BAD_STRING = 15, PRM_ERR_BAD_RANGE = 16, PRM_ERR_UNIX_ERROR = 17,
PRM_ERR_NO_MSG = 18, PRM_ERR_RESET_BAD_RANGE = 19, PRM_ERR_KEYWROD_INFO_INT = 20, PRM_ERR_KEYWORK_INFO_FLOAT = 21,
PRM_ERR_DEPRICATED = 22, PRM_ERR_NOT_BOTH = 23, PRM_ERR_CANNOT_CHANGE = 24, PRM_ERR_NOT_FOR_CLIENT = 25,
PRM_ERR_NOT_FOR_SERVER = 26, PRM_ERR_NOT_SOLE_TRAN = 27, PRM_ERR_COMM_ERR = 28, PRM_ERR_FILE_ERR = 29,
PRM_ERR_NOT_FOR_CLIENT_NO_AUTH = 30, PRM_ERR_BAD_PARAM = 31
}
enum compat_mode { COMPAT_CUBRID, COMPAT_MYSQL, COMPAT_ORACLE }
enum query_trace_format { QUERY_TRACE_TEXT = 1, QUERY_TRACE_JSON }
enum param_id {
PRM_FIRST_ID = 0, PRM_ID_ER_LOG_DEBUG = 0, PRM_ID_ER_BTREE_DEBUG, PRM_ID_ER_LOG_LEVEL,
PRM_ID_ER_LOG_WARNING, PRM_ID_ER_EXIT_ASK, PRM_ID_ER_LOG_SIZE, PRM_ID_ER_LOG_FILE,
PRM_ID_ACCESS_IP_CONTROL, PRM_ID_ACCESS_IP_CONTROL_FILE, PRM_ID_IO_LOCKF_ENABLE, PRM_ID_SR_NBUFFERS,
PRM_ID_SORT_BUFFER_SIZE, PRM_ID_PB_BUFFER_FLUSH_RATIO, PRM_ID_PB_NBUFFERS, PRM_ID_PAGE_BUFFER_SIZE,
PRM_ID_HF_UNFILL_FACTOR, PRM_ID_HF_MAX_BESTSPACE_ENTRIES, PRM_ID_BT_UNFILL_FACTOR, PRM_ID_BT_OID_NBUFFERS,
PRM_ID_BT_OID_BUFFER_SIZE, PRM_ID_BT_INDEX_SCAN_OID_ORDER, PRM_ID_BOSR_MAXTMP_PAGES, PRM_ID_LK_TIMEOUT_MESSAGE_DUMP_LEVEL,
PRM_ID_LK_ESCALATION_AT, PRM_ID_LK_ROLLBACK_ON_LOCK_ESCALATION, PRM_ID_LK_TIMEOUT_SECS, PRM_ID_LK_TIMEOUT,
PRM_ID_LK_RUN_DEADLOCK_INTERVAL, PRM_ID_LOG_NBUFFERS, PRM_ID_LOG_BUFFER_SIZE, PRM_ID_LOG_CHECKPOINT_NPAGES,
PRM_ID_LOG_CHECKPOINT_SIZE, PRM_ID_LOG_CHECKPOINT_INTERVAL_SECS, PRM_ID_LOG_CHECKPOINT_INTERVAL, PRM_ID_LOG_CHECKPOINT_SLEEP_MSECS,
PRM_ID_LOG_BACKGROUND_ARCHIVING, PRM_ID_LOG_ISOLATION_LEVEL, PRM_ID_LOG_MEDIA_FAILURE_SUPPORT, PRM_ID_COMMIT_ON_SHUTDOWN,
PRM_ID_SHUTDOWN_WAIT_TIME_IN_SECS, PRM_ID_CSQL_AUTO_COMMIT, PRM_ID_LOG_SWEEP_CLEAN, PRM_ID_WS_HASHTABLE_SIZE,
PRM_ID_WS_MEMORY_REPORT, PRM_ID_GC_ENABLE, PRM_ID_TCP_PORT_ID, PRM_ID_TCP_CONNECTION_TIMEOUT,
PRM_ID_OPTIMIZATION_LEVEL, PRM_ID_QO_DUMP, PRM_ID_CSS_MAX_CLIENTS, PRM_ID_THREAD_STACKSIZE,
PRM_ID_CFG_DB_HOSTS, PRM_ID_RESET_TR_PARSER, PRM_ID_IO_BACKUP_NBUFFERS, PRM_ID_IO_BACKUP_MAX_VOLUME_SIZE,
PRM_ID_IO_BACKUP_SLEEP_MSECS, PRM_ID_MAX_PAGES_IN_TEMP_FILE_CACHE, PRM_ID_MAX_ENTRIES_IN_TEMP_FILE_CACHE, PRM_ID_PTHREAD_SCOPE_PROCESS,
PRM_ID_TEMP_MEM_BUFFER_PAGES, PRM_ID_INDEX_SCAN_KEY_BUFFER_PAGES, PRM_ID_INDEX_SCAN_KEY_BUFFER_SIZE, PRM_ID_DONT_REUSE_HEAP_FILE,
PRM_ID_INSERT_MODE, PRM_ID_LK_MAX_SCANID_BIT, PRM_ID_HOSTVAR_LATE_BINDING, PRM_ID_ENABLE_HISTO,
PRM_ID_MUTEX_BUSY_WAITING_CNT, PRM_ID_PB_NUM_LRU_CHAINS, PRM_ID_PAGE_BG_FLUSH_INTERVAL_MSECS, PRM_ID_PAGE_BG_FLUSH_INTERVAL,
PRM_ID_ADAPTIVE_FLUSH_CONTROL, PRM_ID_MAX_FLUSH_PAGES_PER_SECOND, PRM_ID_MAX_FLUSH_SIZE_PER_SECOND, PRM_ID_PB_SYNC_ON_NFLUSH,
PRM_ID_PB_SYNC_ON_FLUSH_SIZE, PRM_ID_PB_DEBUG_PAGE_VALIDATION_LEVEL, PRM_ID_ORACLE_STYLE_OUTERJOIN, PRM_ID_ANSI_QUOTES,
PRM_ID_DEFAULT_WEEK_FORMAT, PRM_ID_TEST_MODE, PRM_ID_ONLY_FULL_GROUP_BY, PRM_ID_PIPES_AS_CONCAT,
PRM_ID_MYSQL_TRIGGER_CORRELATION_NAMES, PRM_ID_REQUIRE_LIKE_ESCAPE_CHARACTER, PRM_ID_NO_BACKSLASH_ESCAPES, PRM_ID_GROUP_CONCAT_MAX_LEN,
PRM_ID_STRING_MAX_SIZE_BYTES, PRM_ID_ADD_COLUMN_UPDATE_HARD_DEFAULT, PRM_ID_RETURN_NULL_ON_FUNCTION_ERRORS, PRM_ID_ALTER_TABLE_CHANGE_TYPE_STRICT,
PRM_ID_COMPACTDB_PAGE_RECLAIM_ONLY, PRM_ID_PLUS_AS_CONCAT, PRM_ID_LIKE_TERM_SELECTIVITY, PRM_ID_MAX_OUTER_CARD_OF_IDXJOIN,
PRM_ID_ORACLE_STYLE_EMPTY_STRING, PRM_ID_SUPPRESS_FSYNC, PRM_ID_CALL_STACK_DUMP_ON_ERROR, PRM_ID_CALL_STACK_DUMP_ACTIVATION,
PRM_ID_CALL_STACK_DUMP_DEACTIVATION, PRM_ID_COMPAT_NUMERIC_DIVISION_SCALE, PRM_ID_DBFILES_PROTECT, PRM_ID_AUTO_RESTART_SERVER,
PRM_ID_XASL_CACHE_MAX_ENTRIES, PRM_ID_XASL_CACHE_MAX_CLONES, PRM_ID_XASL_CACHE_TIMEOUT, PRM_ID_XASL_CACHE_LOGGING,
PRM_ID_FILTER_PRED_MAX_CACHE_ENTRIES, PRM_ID_FILTER_PRED_MAX_CACHE_CLONES, PRM_ID_LIST_QUERY_CACHE_MODE, PRM_ID_LIST_MAX_QUERY_CACHE_ENTRIES,
PRM_ID_LIST_MAX_QUERY_CACHE_PAGES, PRM_ID_USE_ORDERBY_SORT_LIMIT, PRM_ID_REPLICATION_MODE, PRM_ID_HA_MODE,
PRM_ID_HA_MODE_FOR_SA_UTILS_ONLY, PRM_ID_HA_SERVER_STATE, PRM_ID_HA_LOG_APPLIER_STATE, PRM_ID_HA_NODE_LIST,
PRM_ID_HA_REPLICA_LIST, PRM_ID_HA_DB_LIST, PRM_ID_HA_COPY_LOG_BASE, PRM_ID_HA_COPY_SYNC_MODE,
PRM_ID_HA_APPLY_MAX_MEM_SIZE, PRM_ID_HA_PORT_ID, PRM_ID_HA_INIT_TIMER_IN_MSECS, PRM_ID_HA_HEARTBEAT_INTERVAL_IN_MSECS,
PRM_ID_HA_CALC_SCORE_INTERVAL_IN_MSECS, PRM_ID_HA_FAILOVER_WAIT_TIME_IN_MSECS, PRM_ID_HA_PROCESS_START_CONFIRM_INTERVAL_IN_MSECS, PRM_ID_HA_PROCESS_DEREG_CONFIRM_INTERVAL_IN_MSECS,
PRM_ID_HA_MAX_PROCESS_START_CONFIRM, PRM_ID_HA_MAX_PROCESS_DEREG_CONFIRM, PRM_ID_HA_UNACCEPTABLE_PROC_RESTART_TIMEDIFF_IN_MSECS, PRM_ID_HA_CHANGEMODE_INTERVAL_IN_MSECS,
PRM_ID_HA_MAX_HEARTBEAT_GAP, PRM_ID_HA_PING_HOSTS, PRM_ID_HA_APPLYLOGDB_RETRY_ERROR_LIST, PRM_ID_HA_APPLYLOGDB_IGNORE_ERROR_LIST,
PRM_ID_HA_APPLYLOGDB_LOG_WAIT_TIME_IN_SECS, PRM_ID_HA_SQL_LOGGING, PRM_ID_HA_SQL_LOG_MAX_SIZE_IN_MB, PRM_ID_HA_COPY_LOG_MAX_ARCHIVES,
PRM_ID_HA_COPY_LOG_TIMEOUT, PRM_ID_HA_REPLICA_DELAY_IN_SECS, PRM_ID_HA_REPLICA_TIME_BOUND, PRM_ID_HA_DELAY_LIMIT_IN_SECS,
PRM_ID_HA_DELAY_LIMIT_DELTA_IN_SECS, PRM_ID_HA_APPLYLOGDB_MAX_COMMIT_INTERVAL_IN_MSECS, PRM_ID_HA_APPLYLOGDB_MAX_COMMIT_INTERVAL, PRM_ID_HA_CHECK_DISK_FAILURE_INTERVAL_IN_SECS,
PRM_ID_GENERAL_RESERVE_01, PRM_ID_COMPAT_PRIMARY_KEY, PRM_ID_LOG_HEADER_FLUSH_INTERVAL, PRM_ID_LOG_ASYNC_COMMIT,
PRM_ID_LOG_GROUP_COMMIT_INTERVAL_MSECS, PRM_ID_LOG_BG_FLUSH_INTERVAL_MSECS, PRM_ID_LOG_BG_FLUSH_NUM_PAGES, PRM_ID_INTL_MBS_SUPPORT,
PRM_ID_LOG_COMPRESS, PRM_ID_BLOCK_NOWHERE_STATEMENT, PRM_ID_BLOCK_DDL_STATEMENT, PRM_ID_CSQL_HISTORY_NUM,
PRM_ID_LOG_TRACE_DEBUG, PRM_ID_DL_FORK, PRM_ID_ER_PRODUCTION_MODE, PRM_ID_ER_STOP_ON_ERROR,
PRM_ID_TCP_RCVBUF_SIZE, PRM_ID_TCP_SNDBUF_SIZE, PRM_ID_TCP_NODELAY, PRM_ID_TCP_KEEPALIVE,
PRM_ID_CSQL_SINGLE_LINE_MODE, PRM_ID_XASL_DEBUG_DUMP, PRM_ID_LOG_MAX_ARCHIVES, PRM_ID_FORCE_REMOVE_LOG_ARCHIVES,
PRM_ID_REMOVE_LOG_ARCHIVES_INTERVAL, PRM_ID_LOG_NO_LOGGING, PRM_ID_UNLOADDB_IGNORE_ERROR, PRM_ID_UNLOADDB_LOCK_TIMEOUT,
PRM_ID_LOADDB_FLUSH_INTERVAL, PRM_ID_IO_TEMP_VOLUME_PATH, PRM_ID_IO_VOLUME_EXT_PATH, PRM_ID_UNIQUE_ERROR_KEY_VALUE,
PRM_ID_USE_SYSTEM_MALLOC, PRM_ID_EVENT_HANDLER, PRM_ID_EVENT_ACTIVATION, PRM_ID_READ_ONLY_MODE,
PRM_ID_MNT_WAITING_THREAD, PRM_ID_MNT_STATS_THRESHOLD, PRM_ID_SERVICE_SERVICE_LIST, PRM_ID_SERVICE_SERVER_LIST,
PRM_ID_SESSION_STATE_TIMEOUT, PRM_ID_MULTI_RANGE_OPT_LIMIT, PRM_ID_INTL_NUMBER_LANG, PRM_ID_INTL_DATE_LANG,
PRM_ID_COMPAT_MODE, PRM_ID_DB_VOLUME_SIZE, PRM_ID_LOG_VOLUME_SIZE, PRM_ID_UNICODE_INPUT_NORMALIZATION,
PRM_ID_UNICODE_OUTPUT_NORMALIZATION, PRM_ID_INTL_CHECK_INPUT_STRING, PRM_ID_CHECK_PEER_ALIVE, PRM_ID_SQL_TRACE_SLOW_MSECS,
PRM_ID_SQL_TRACE_SLOW, PRM_ID_SQL_TRACE_EXECUTION_PLAN, PRM_ID_LOG_TRACE_FLUSH_TIME_MSECS, PRM_ID_INTL_COLLATION,
PRM_ID_GENERIC_VOL_PREALLOC_SIZE, PRM_ID_SORT_LIMIT_MAX_COUNT, PRM_ID_SQL_TRACE_IOREADS, PRM_ID_QUERY_TRACE,
PRM_ID_QUERY_TRACE_FORMAT, PRM_ID_MAX_RECURSION_SQL_DEPTH, PRM_ID_UPDATE_USE_ATTRIBUTE_REFERENCES, PRM_ID_PB_AOUT_RATIO,
PRM_ID_MAX_AGG_HASH_SIZE, PRM_ID_AGG_HASH_RESPECT_ORDER, PRM_ID_USE_BTREE_FENCE_KEY, PRM_ID_OPTIMIZER_ENABLE_MERGE_JOIN,
PRM_ID_MAX_HASH_LIST_SCAN_SIZE, PRM_ID_OPTIMIZER_RESERVE_02, PRM_ID_OPTIMIZER_RESERVE_03, PRM_ID_OPTIMIZER_RESERVE_04,
PRM_ID_OPTIMIZER_RESERVE_05, PRM_ID_OPTIMIZER_RESERVE_06, PRM_ID_OPTIMIZER_RESERVE_07, PRM_ID_OPTIMIZER_RESERVE_08,
PRM_ID_OPTIMIZER_RESERVE_09, PRM_ID_OPTIMIZER_RESERVE_10, PRM_ID_OPTIMIZER_RESERVE_11, PRM_ID_OPTIMIZER_RESERVE_12,
PRM_ID_OPTIMIZER_RESERVE_13, PRM_ID_OPTIMIZER_RESERVE_14, PRM_ID_OPTIMIZER_RESERVE_15, PRM_ID_OPTIMIZER_RESERVE_16,
PRM_ID_OPTIMIZER_RESERVE_17, PRM_ID_OPTIMIZER_RESERVE_18, PRM_ID_OPTIMIZER_RESERVE_19, PRM_ID_OPTIMIZER_RESERVE_20,
PRM_ID_HA_REPL_ENABLE_SERVER_SIDE_UPDATE, PRM_ID_PB_LRU_HOT_RATIO, PRM_ID_PB_LRU_BUFFER_RATIO, PRM_ID_VACUUM_MASTER_WAKEUP_INTERVAL,
PRM_ID_VACUUM_LOG_BLOCK_PAGES, PRM_ID_VACUUM_WORKER_COUNT, PRM_ID_ER_LOG_VACUUM, PRM_ID_DISABLE_VACUUM,
PRM_ID_LOG_BTREE_OPS, PRM_ID_OBJECT_PRINT_FORMAT_OID, PRM_ID_TIMEZONE, PRM_ID_SERVER_TIMEZONE,
PRM_ID_TZ_LEAP_SECOND_SUPPORT, PRM_ID_OPTIMIZER_ENABLE_AGGREGATE_OPTIMIZATION, PRM_ID_VACUUM_PREFETCH_LOG_NBUFFERS, PRM_ID_VACUUM_PREFETCH_LOG_BUFFER_SIZE,
PRM_ID_VACUUM_PREFETCH_LOG_MODE, PRM_ID_PB_NEIGHBOR_FLUSH_NONDIRTY, PRM_ID_PB_NEIGHBOR_FLUSH_PAGES, PRM_ID_FAULT_INJECTION_IDS,
PRM_ID_FAULT_INJECTION_TEST, PRM_ID_FAULT_INJECTION_ACTION_PREFER_ABORT_TO_EXIT, PRM_ID_HA_REPL_FILTER_TYPE, PRM_ID_HA_REPL_FILTER_FILE,
PRM_ID_COMPENSATE_DEBUG, PRM_ID_POSTPONE_DEBUG, PRM_ID_CLIENT_CLASS_CACHE_DEBUG, PRM_ID_EXAMINE_CLIENT_CACHED_LOCKS,
PRM_ID_PB_SEQUENTIAL_VICTIM_FLUSH, PRM_ID_LOG_UNIQUE_STATS, PRM_ID_LOGPB_LOGGING_DEBUG, PRM_ID_FORCE_RESTART_TO_SKIP_RECOVERY,
PRM_ID_EXTENDED_STATISTICS_ACTIVATION, PRM_ID_ENABLE_STRING_COMPRESSION, PRM_ID_XASL_CACHE_TIME_THRESHOLD_IN_MINUTES, PRM_ID_DISK_LOGGING,
PRM_ID_FILE_LOGGING, PRM_ID_PB_NUM_PRIVATE_CHAINS, PRM_ID_PB_MONITOR_LOCKS, PRM_ID_CTE_MAX_RECURSIONS,
PRM_ID_JSON_LOG_ALLOCATIONS, PRM_ID_JSON_MAX_ARRAY_IDX, PRM_ID_CONNECTION_LOGGING, PRM_ID_THREAD_LOGGING_FLAG,
PRM_ID_LOG_QUERY_LISTS, PRM_ID_THREAD_CONNECTION_POOLING, PRM_ID_THREAD_CONNECTION_TIMEOUT_SECONDS, PRM_ID_THREAD_WORKER_POOLING,
PRM_ID_THREAD_WORKER_TIMEOUT_SECONDS, PRM_ID_DWB_SIZE, PRM_ID_DWB_BLOCKS, PRM_ID_ENABLE_DWB_FLUSH_THREAD,
PRM_ID_DWB_LOGGING, PRM_ID_DATA_FILE_ADVISE, PRM_ID_DEBUG_LOG_ARCHIVES, PRM_ID_DEBUG_ES,
PRM_ID_DEBUG_BESTSPACE, PRM_ID_DEBUG_LOGWR, PRM_ID_DEBUG_AUTOCOMMIT, PRM_ID_DEBUG_REPLICATION_DATA,
PRM_ID_TRACK_REQUESTS, PRM_ID_LOG_PGBUF_VICTIM_FLUSH, PRM_ID_LOG_CHKPT_DETAILED, PRM_ID_IB_TASK_MEMSIZE,
PRM_ID_STATS_ON, PRM_ID_LOADDB_WORKER_COUNT, PRM_ID_PERF_TEST_MODE, PRM_ID_REPR_CACHE_LOG,
PRM_ID_ENABLE_NEW_LFHASH, PRM_ID_HEAP_INFO_CACHE_LOGGING, PRM_ID_TDE_KEYS_FILE_PATH, PRM_ID_TDE_DEFAULT_ALGORITHM,
PRM_ID_JAVA_STORED_PROCEDURE, PRM_ID_JAVA_STORED_PROCEDURE_PORT, PRM_ID_JAVA_STORED_PROCEDURE_JVM_OPTIONS, PRM_ID_JAVA_STORED_PROCEDURE_DEBUG,
PRM_ID_JAVA_STORED_PROCEDURE_RESERVE_01, PRM_ID_ALLOW_TRUNCATED_STRING, PRM_ID_TB_DEFAULT_REUSE_OID, PRM_ID_USE_STAT_ESTIMATION,
PRM_ID_IGNORE_TRAILING_SPACE, PRM_ID_DDL_AUDIT_LOG, PRM_ID_DDL_AUDIT_LOG_SIZE, PRM_LAST_ID = PRM_ID_DDL_AUDIT_LOG_SIZE
}
enum SYSPRM_DATATYPE {
PRM_INTEGER = 0, PRM_FLOAT, PRM_BOOLEAN, PRM_KEYWORD,
PRM_BIGINT, PRM_STRING, PRM_INTEGER_LIST, PRM_NO_TYPE
}
enum sysprm_load_flag { SYSPRM_LOAD_ALL = 0x0, SYSPRM_IGNORE_HA = 0x1, SYSPRM_IGNORE_INTL_PARAMS = 0x2 }
Functions
const char * prm_get_name (PARAM_ID prm_id)
void * prm_get_value (PARAM_ID prm_id)
int prm_get_integer_value (PARAM_ID prm_id)
float prm_get_float_value (PARAM_ID prm_id)
bool prm_get_bool_value (PARAM_ID prm_id)
char * prm_get_string_value (PARAM_ID prm_id)
int * prm_get_integer_list_value (PARAM_ID prm_id)
UINT64 prm_get_bigint_value (PARAM_ID prm_id)
void prm_set_integer_value (PARAM_ID prm_id, int value)
void prm_set_float_value (PARAM_ID prm_id, float value)
void prm_set_bool_value (PARAM_ID prm_id, bool value)
void prm_set_string_value (PARAM_ID prm_id, char *value)
void prm_set_integer_list_value (PARAM_ID prm_id, int *value)
void prm_set_bigint_value (PARAM_ID prm_id, UINT64 value)
bool sysprm_find_err_in_integer_list (PARAM_ID prm_id, int error_code)
bool sysprm_find_fi_code_in_integer_list (PARAM_ID prm_id, int fi_code)
int sysprm_load_and_init (const char *db_name, const char *conf_file, const int load_flags)
int sysprm_load_and_init_client (const char *db_name, const char *conf_file)
int sysprm_reload_and_init (const char *db_name, const char *conf_file)
void sysprm_final (void)
void sysprm_dump_parameters (FILE *fp)
void sysprm_set_er_log_file (const char *base_db_name)
void sysprm_dump_server_parameters (FILE *fp)
SYSPRM_ERR sysprm_obtain_parameters (char *data, SYSPRM_ASSIGN_VALUE **prm_values)
SYSPRM_ERR sysprm_change_server_parameters (const SYSPRM_ASSIGN_VALUE *assignments)
SYSPRM_ERR sysprm_obtain_server_parameters (SYSPRM_ASSIGN_VALUE **prm_values_ptr)
int sysprm_get_force_server_parameters (SYSPRM_ASSIGN_VALUE **change_values)
void sysprm_tune_client_parameters (void)
void sysprm_free_session_parameters (SESSION_PARAM **session_parameters)
void xsysprm_change_server_parameters (const SYSPRM_ASSIGN_VALUE *assignments)
void xsysprm_obtain_server_parameters (SYSPRM_ASSIGN_VALUE *prm_values)
SYSPRM_ASSIGN_VALUE * xsysprm_get_force_server_parameters (void)
void xsysprm_dump_server_parameters (FILE *fp)
int sysprm_set_force (const char *pname, const char *pvalue)
int sysprm_set_to_default (const char *pname, bool set_to_force)
int sysprm_check_range (const char *pname, void *value)
int sysprm_get_range (const char *pname, void *min, void *max)
int prm_get_master_port_id (void)
bool prm_get_commit_on_shutdown (void)
char * sysprm_pack_session_parameters (char *ptr, SESSION_PARAM *session_parameters)
int sysprm_packed_session_parameters_length (SESSION_PARAM *session_parameters, int offset)
char * sysprm_unpack_session_parameters (char *ptr, SESSION_PARAM **session_parameters_ptr)
char * sysprm_pack_assign_values (char *ptr, const SYSPRM_ASSIGN_VALUE *assign_values)
int sysprm_packed_assign_values_length (const SYSPRM_ASSIGN_VALUE *assign_values, int offset)
char * sysprm_unpack_assign_values (char *ptr, SYSPRM_ASSIGN_VALUE **assign_values_ptr)
void sysprm_free_assign_values (SYSPRM_ASSIGN_VALUE **assign_values_ptr)
void sysprm_change_parameter_values (const SYSPRM_ASSIGN_VALUE *assignments, bool check, bool set_flag)
char * sysprm_print_parameters_for_qry_string (void)
char * sysprm_print_parameters_for_ha_repl (void)
SYSPRM_ERR sysprm_validate_change_parameters (const char *data, bool check, SYSPRM_ASSIGN_VALUE **assignments_ptr)
SYSPRM_ERR sysprm_make_default_values (const char *data, char *default_val_buf, const int buf_size)
int sysprm_init_intl_param (void)
int sysprm_print_assign_values (SYSPRM_ASSIGN_VALUE *prm_values, char *buffer, int length)
int sysprm_set_error (SYSPRM_ERR rc, const char *data)
int sysprm_get_session_parameters_count (void)
Macro Definition Documentation
#define SYSPRM_LOAD_IS_IGNORE_HA (flags) ((flags) & SYSPRM_IGNORE_HA)
Definition at line 512 of file system_parameter.h.
Referenced by prm_load_by_section(), and prm_read_and_parse_ini_file().
#define SYSPRM_LOAD_IS_IGNORE_INTL (flags) ((flags) & SYSPRM_IGNORE_INTL_PARAMS)
Definition at line 513 of file system_parameter.h.
Referenced by prm_load_by_section().
Typedef Documentation
typedef enum compat_mode COMPAT_MODE
Definition at line 79 of file system_parameter.h.
typedef enum param_id PARAM_ID
Definition at line 458 of file system_parameter.h.
typedef enum query_trace_format QUERY_TRACE_FORMAT
Definition at line 86 of file system_parameter.h.
typedef struct session_param SESSION_PARAM
Definition at line 487 of file system_parameter.h.
typedef struct sysprm_assign_value SYSPRM_ASSIGN_VALUE
Definition at line 496 of file system_parameter.h.
typedef enum sysprm_load_flag SYSPRM_LOAD_FLAG
Definition at line 510 of file system_parameter.h.
typedef union sysprm_value SYSPRM_VALUE
Definition at line 476 of file system_parameter.h.
Enumeration Type Documentation
enum compat_mode
Enumerator
COMPAT_CUBRID
COMPAT_MYSQL
COMPAT_ORACLE
Definition at line 71 of file system_parameter.h.
enum param_id
Enumerator
PRM_FIRST_ID
PRM_ID_ER_LOG_DEBUG
PRM_ID_ER_BTREE_DEBUG
PRM_ID_ER_LOG_LEVEL
PRM_ID_ER_LOG_WARNING
PRM_ID_ER_EXIT_ASK
PRM_ID_ER_LOG_SIZE
PRM_ID_ER_LOG_FILE
PRM_ID_ACCESS_IP_CONTROL
PRM_ID_ACCESS_IP_CONTROL_FILE
PRM_ID_IO_LOCKF_ENABLE
PRM_ID_SR_NBUFFERS
PRM_ID_SORT_BUFFER_SIZE
PRM_ID_PB_BUFFER_FLUSH_RATIO
PRM_ID_PB_NBUFFERS
PRM_ID_PAGE_BUFFER_SIZE
PRM_ID_HF_UNFILL_FACTOR
PRM_ID_HF_MAX_BESTSPACE_ENTRIES
PRM_ID_BT_UNFILL_FACTOR
PRM_ID_BT_OID_NBUFFERS
PRM_ID_BT_OID_BUFFER_SIZE
PRM_ID_BT_INDEX_SCAN_OID_ORDER
PRM_ID_BOSR_MAXTMP_PAGES
PRM_ID_LK_TIMEOUT_MESSAGE_DUMP_LEVEL
PRM_ID_LK_ESCALATION_AT
PRM_ID_LK_ROLLBACK_ON_LOCK_ESCALATION
PRM_ID_LK_TIMEOUT_SECS
PRM_ID_LK_TIMEOUT
PRM_ID_LK_RUN_DEADLOCK_INTERVAL
PRM_ID_LOG_NBUFFERS
PRM_ID_LOG_BUFFER_SIZE
PRM_ID_LOG_CHECKPOINT_NPAGES
PRM_ID_LOG_CHECKPOINT_SIZE
PRM_ID_LOG_CHECKPOINT_INTERVAL_SECS
PRM_ID_LOG_CHECKPOINT_INTERVAL
PRM_ID_LOG_CHECKPOINT_SLEEP_MSECS
PRM_ID_LOG_BACKGROUND_ARCHIVING
PRM_ID_LOG_ISOLATION_LEVEL
PRM_ID_LOG_MEDIA_FAILURE_SUPPORT
PRM_ID_COMMIT_ON_SHUTDOWN
PRM_ID_SHUTDOWN_WAIT_TIME_IN_SECS
PRM_ID_CSQL_AUTO_COMMIT
PRM_ID_LOG_SWEEP_CLEAN
PRM_ID_WS_HASHTABLE_SIZE
PRM_ID_WS_MEMORY_REPORT
PRM_ID_GC_ENABLE
PRM_ID_TCP_PORT_ID
PRM_ID_TCP_CONNECTION_TIMEOUT
PRM_ID_OPTIMIZATION_LEVEL
PRM_ID_QO_DUMP
PRM_ID_CSS_MAX_CLIENTS
PRM_ID_THREAD_STACKSIZE
PRM_ID_CFG_DB_HOSTS
PRM_ID_RESET_TR_PARSER
PRM_ID_IO_BACKUP_NBUFFERS
PRM_ID_IO_BACKUP_MAX_VOLUME_SIZE
PRM_ID_IO_BACKUP_SLEEP_MSECS
PRM_ID_MAX_PAGES_IN_TEMP_FILE_CACHE
PRM_ID_MAX_ENTRIES_IN_TEMP_FILE_CACHE
PRM_ID_PTHREAD_SCOPE_PROCESS
PRM_ID_TEMP_MEM_BUFFER_PAGES
PRM_ID_INDEX_SCAN_KEY_BUFFER_PAGES
PRM_ID_INDEX_SCAN_KEY_BUFFER_SIZE
PRM_ID_DONT_REUSE_HEAP_FILE
PRM_ID_INSERT_MODE
PRM_ID_LK_MAX_SCANID_BIT
PRM_ID_HOSTVAR_LATE_BINDING
PRM_ID_ENABLE_HISTO
PRM_ID_MUTEX_BUSY_WAITING_CNT
PRM_ID_PB_NUM_LRU_CHAINS
PRM_ID_PAGE_BG_FLUSH_INTERVAL_MSECS
PRM_ID_PAGE_BG_FLUSH_INTERVAL
PRM_ID_ADAPTIVE_FLUSH_CONTROL
PRM_ID_MAX_FLUSH_PAGES_PER_SECOND
PRM_ID_MAX_FLUSH_SIZE_PER_SECOND
PRM_ID_PB_SYNC_ON_NFLUSH
PRM_ID_PB_SYNC_ON_FLUSH_SIZE
PRM_ID_PB_DEBUG_PAGE_VALIDATION_LEVEL
PRM_ID_ORACLE_STYLE_OUTERJOIN
PRM_ID_ANSI_QUOTES
PRM_ID_DEFAULT_WEEK_FORMAT
PRM_ID_TEST_MODE
PRM_ID_ONLY_FULL_GROUP_BY
PRM_ID_PIPES_AS_CONCAT
PRM_ID_MYSQL_TRIGGER_CORRELATION_NAMES
PRM_ID_REQUIRE_LIKE_ESCAPE_CHARACTER
PRM_ID_NO_BACKSLASH_ESCAPES
PRM_ID_GROUP_CONCAT_MAX_LEN
PRM_ID_STRING_MAX_SIZE_BYTES
PRM_ID_ADD_COLUMN_UPDATE_HARD_DEFAULT
PRM_ID_RETURN_NULL_ON_FUNCTION_ERRORS
PRM_ID_ALTER_TABLE_CHANGE_TYPE_STRICT
PRM_ID_COMPACTDB_PAGE_RECLAIM_ONLY
PRM_ID_PLUS_AS_CONCAT
PRM_ID_LIKE_TERM_SELECTIVITY
PRM_ID_MAX_OUTER_CARD_OF_IDXJOIN
PRM_ID_ORACLE_STYLE_EMPTY_STRING
PRM_ID_SUPPRESS_FSYNC
PRM_ID_CALL_STACK_DUMP_ON_ERROR
PRM_ID_CALL_STACK_DUMP_ACTIVATION
PRM_ID_CALL_STACK_DUMP_DEACTIVATION
PRM_ID_COMPAT_NUMERIC_DIVISION_SCALE
PRM_ID_DBFILES_PROTECT
PRM_ID_AUTO_RESTART_SERVER
PRM_ID_XASL_CACHE_MAX_ENTRIES
PRM_ID_XASL_CACHE_MAX_CLONES
PRM_ID_XASL_CACHE_TIMEOUT
PRM_ID_XASL_CACHE_LOGGING
PRM_ID_FILTER_PRED_MAX_CACHE_ENTRIES
PRM_ID_FILTER_PRED_MAX_CACHE_CLONES
PRM_ID_LIST_QUERY_CACHE_MODE
PRM_ID_LIST_MAX_QUERY_CACHE_ENTRIES
PRM_ID_LIST_MAX_QUERY_CACHE_PAGES
PRM_ID_USE_ORDERBY_SORT_LIMIT
PRM_ID_REPLICATION_MODE
PRM_ID_HA_MODE
PRM_ID_HA_MODE_FOR_SA_UTILS_ONLY
PRM_ID_HA_SERVER_STATE
PRM_ID_HA_LOG_APPLIER_STATE
PRM_ID_HA_NODE_LIST
PRM_ID_HA_REPLICA_LIST
PRM_ID_HA_DB_LIST
PRM_ID_HA_COPY_LOG_BASE
PRM_ID_HA_COPY_SYNC_MODE
PRM_ID_HA_APPLY_MAX_MEM_SIZE
PRM_ID_HA_PORT_ID
PRM_ID_HA_INIT_TIMER_IN_MSECS
PRM_ID_HA_HEARTBEAT_INTERVAL_IN_MSECS
PRM_ID_HA_CALC_SCORE_INTERVAL_IN_MSECS
PRM_ID_HA_FAILOVER_WAIT_TIME_IN_MSECS
PRM_ID_HA_PROCESS_START_CONFIRM_INTERVAL_IN_MSECS
PRM_ID_HA_PROCESS_DEREG_CONFIRM_INTERVAL_IN_MSECS
PRM_ID_HA_MAX_PROCESS_START_CONFIRM
PRM_ID_HA_MAX_PROCESS_DEREG_CONFIRM
PRM_ID_HA_UNACCEPTABLE_PROC_RESTART_TIMEDIFF_IN_MSECS
PRM_ID_HA_CHANGEMODE_INTERVAL_IN_MSECS
PRM_ID_HA_MAX_HEARTBEAT_GAP
PRM_ID_HA_PING_HOSTS
PRM_ID_HA_APPLYLOGDB_RETRY_ERROR_LIST
PRM_ID_HA_APPLYLOGDB_IGNORE_ERROR_LIST
PRM_ID_HA_APPLYLOGDB_LOG_WAIT_TIME_IN_SECS
PRM_ID_HA_SQL_LOGGING
PRM_ID_HA_SQL_LOG_MAX_SIZE_IN_MB
PRM_ID_HA_COPY_LOG_MAX_ARCHIVES
PRM_ID_HA_COPY_LOG_TIMEOUT
PRM_ID_HA_REPLICA_DELAY_IN_SECS
PRM_ID_HA_REPLICA_TIME_BOUND
PRM_ID_HA_DELAY_LIMIT_IN_SECS
PRM_ID_HA_DELAY_LIMIT_DELTA_IN_SECS
PRM_ID_HA_APPLYLOGDB_MAX_COMMIT_INTERVAL_IN_MSECS
PRM_ID_HA_APPLYLOGDB_MAX_COMMIT_INTERVAL
PRM_ID_HA_CHECK_DISK_FAILURE_INTERVAL_IN_SECS
PRM_ID_GENERAL_RESERVE_01
PRM_ID_COMPAT_PRIMARY_KEY
PRM_ID_LOG_HEADER_FLUSH_INTERVAL
PRM_ID_LOG_ASYNC_COMMIT
PRM_ID_LOG_GROUP_COMMIT_INTERVAL_MSECS
PRM_ID_LOG_BG_FLUSH_INTERVAL_MSECS
PRM_ID_LOG_BG_FLUSH_NUM_PAGES
PRM_ID_INTL_MBS_SUPPORT
PRM_ID_LOG_COMPRESS
PRM_ID_BLOCK_NOWHERE_STATEMENT
PRM_ID_BLOCK_DDL_STATEMENT
PRM_ID_CSQL_HISTORY_NUM
PRM_ID_LOG_TRACE_DEBUG
PRM_ID_DL_FORK
PRM_ID_ER_PRODUCTION_MODE
PRM_ID_ER_STOP_ON_ERROR
PRM_ID_TCP_RCVBUF_SIZE
PRM_ID_TCP_SNDBUF_SIZE
PRM_ID_TCP_NODELAY
PRM_ID_TCP_KEEPALIVE
PRM_ID_CSQL_SINGLE_LINE_MODE
PRM_ID_XASL_DEBUG_DUMP
PRM_ID_LOG_MAX_ARCHIVES
PRM_ID_FORCE_REMOVE_LOG_ARCHIVES
PRM_ID_REMOVE_LOG_ARCHIVES_INTERVAL
PRM_ID_LOG_NO_LOGGING
PRM_ID_UNLOADDB_IGNORE_ERROR
PRM_ID_UNLOADDB_LOCK_TIMEOUT
PRM_ID_LOADDB_FLUSH_INTERVAL
PRM_ID_IO_TEMP_VOLUME_PATH
PRM_ID_IO_VOLUME_EXT_PATH
PRM_ID_UNIQUE_ERROR_KEY_VALUE
PRM_ID_USE_SYSTEM_MALLOC
PRM_ID_EVENT_HANDLER
PRM_ID_EVENT_ACTIVATION
PRM_ID_READ_ONLY_MODE
PRM_ID_MNT_WAITING_THREAD
PRM_ID_MNT_STATS_THRESHOLD
PRM_ID_SERVICE_SERVICE_LIST
PRM_ID_SERVICE_SERVER_LIST
PRM_ID_SESSION_STATE_TIMEOUT
PRM_ID_MULTI_RANGE_OPT_LIMIT
PRM_ID_INTL_NUMBER_LANG
PRM_ID_INTL_DATE_LANG
PRM_ID_COMPAT_MODE
PRM_ID_DB_VOLUME_SIZE
PRM_ID_LOG_VOLUME_SIZE
PRM_ID_UNICODE_INPUT_NORMALIZATION
PRM_ID_UNICODE_OUTPUT_NORMALIZATION
PRM_ID_INTL_CHECK_INPUT_STRING
PRM_ID_CHECK_PEER_ALIVE
PRM_ID_SQL_TRACE_SLOW_MSECS
PRM_ID_SQL_TRACE_SLOW
PRM_ID_SQL_TRACE_EXECUTION_PLAN
PRM_ID_LOG_TRACE_FLUSH_TIME_MSECS
PRM_ID_INTL_COLLATION
PRM_ID_GENERIC_VOL_PREALLOC_SIZE
PRM_ID_SORT_LIMIT_MAX_COUNT
PRM_ID_SQL_TRACE_IOREADS
PRM_ID_QUERY_TRACE
PRM_ID_QUERY_TRACE_FORMAT
PRM_ID_MAX_RECURSION_SQL_DEPTH
PRM_ID_UPDATE_USE_ATTRIBUTE_REFERENCES
PRM_ID_PB_AOUT_RATIO
PRM_ID_MAX_AGG_HASH_SIZE
PRM_ID_AGG_HASH_RESPECT_ORDER
PRM_ID_USE_BTREE_FENCE_KEY
PRM_ID_OPTIMIZER_ENABLE_MERGE_JOIN
PRM_ID_MAX_HASH_LIST_SCAN_SIZE
PRM_ID_OPTIMIZER_RESERVE_02
PRM_ID_OPTIMIZER_RESERVE_03
PRM_ID_OPTIMIZER_RESERVE_04
PRM_ID_OPTIMIZER_RESERVE_05
PRM_ID_OPTIMIZER_RESERVE_06
PRM_ID_OPTIMIZER_RESERVE_07
PRM_ID_OPTIMIZER_RESERVE_08
PRM_ID_OPTIMIZER_RESERVE_09
PRM_ID_OPTIMIZER_RESERVE_10
PRM_ID_OPTIMIZER_RESERVE_11
PRM_ID_OPTIMIZER_RESERVE_12
PRM_ID_OPTIMIZER_RESERVE_13
PRM_ID_OPTIMIZER_RESERVE_14
PRM_ID_OPTIMIZER_RESERVE_15
PRM_ID_OPTIMIZER_RESERVE_16
PRM_ID_OPTIMIZER_RESERVE_17
PRM_ID_OPTIMIZER_RESERVE_18
PRM_ID_OPTIMIZER_RESERVE_19
PRM_ID_OPTIMIZER_RESERVE_20
PRM_ID_HA_REPL_ENABLE_SERVER_SIDE_UPDATE
PRM_ID_PB_LRU_HOT_RATIO
PRM_ID_PB_LRU_BUFFER_RATIO
PRM_ID_VACUUM_MASTER_WAKEUP_INTERVAL
PRM_ID_VACUUM_LOG_BLOCK_PAGES
PRM_ID_VACUUM_WORKER_COUNT
PRM_ID_ER_LOG_VACUUM
PRM_ID_DISABLE_VACUUM
PRM_ID_LOG_BTREE_OPS
PRM_ID_OBJECT_PRINT_FORMAT_OID
PRM_ID_TIMEZONE
PRM_ID_SERVER_TIMEZONE
PRM_ID_TZ_LEAP_SECOND_SUPPORT
PRM_ID_OPTIMIZER_ENABLE_AGGREGATE_OPTIMIZATION
PRM_ID_VACUUM_PREFETCH_LOG_NBUFFERS
PRM_ID_VACUUM_PREFETCH_LOG_BUFFER_SIZE
PRM_ID_VACUUM_PREFETCH_LOG_MODE
PRM_ID_PB_NEIGHBOR_FLUSH_NONDIRTY
PRM_ID_PB_NEIGHBOR_FLUSH_PAGES
PRM_ID_FAULT_INJECTION_IDS
PRM_ID_FAULT_INJECTION_TEST
PRM_ID_FAULT_INJECTION_ACTION_PREFER_ABORT_TO_EXIT
PRM_ID_HA_REPL_FILTER_TYPE
PRM_ID_HA_REPL_FILTER_FILE
PRM_ID_COMPENSATE_DEBUG
PRM_ID_POSTPONE_DEBUG
PRM_ID_CLIENT_CLASS_CACHE_DEBUG
PRM_ID_EXAMINE_CLIENT_CACHED_LOCKS
PRM_ID_PB_SEQUENTIAL_VICTIM_FLUSH
PRM_ID_LOG_UNIQUE_STATS
PRM_ID_LOGPB_LOGGING_DEBUG
PRM_ID_FORCE_RESTART_TO_SKIP_RECOVERY
PRM_ID_EXTENDED_STATISTICS_ACTIVATION
PRM_ID_ENABLE_STRING_COMPRESSION
PRM_ID_XASL_CACHE_TIME_THRESHOLD_IN_MINUTES
PRM_ID_DISK_LOGGING
PRM_ID_FILE_LOGGING
PRM_ID_PB_NUM_PRIVATE_CHAINS
PRM_ID_PB_MONITOR_LOCKS
PRM_ID_CTE_MAX_RECURSIONS
PRM_ID_JSON_LOG_ALLOCATIONS
PRM_ID_JSON_MAX_ARRAY_IDX
PRM_ID_CONNECTION_LOGGING
PRM_ID_THREAD_LOGGING_FLAG
PRM_ID_LOG_QUERY_LISTS
PRM_ID_THREAD_CONNECTION_POOLING
PRM_ID_THREAD_CONNECTION_TIMEOUT_SECONDS
PRM_ID_THREAD_WORKER_POOLING
PRM_ID_THREAD_WORKER_TIMEOUT_SECONDS
PRM_ID_DWB_SIZE
PRM_ID_DWB_BLOCKS
PRM_ID_ENABLE_DWB_FLUSH_THREAD
PRM_ID_DWB_LOGGING
PRM_ID_DATA_FILE_ADVISE
PRM_ID_DEBUG_LOG_ARCHIVES
PRM_ID_DEBUG_ES
PRM_ID_DEBUG_BESTSPACE
PRM_ID_DEBUG_LOGWR
PRM_ID_DEBUG_AUTOCOMMIT
PRM_ID_DEBUG_REPLICATION_DATA
PRM_ID_TRACK_REQUESTS
PRM_ID_LOG_PGBUF_VICTIM_FLUSH
PRM_ID_LOG_CHKPT_DETAILED
PRM_ID_IB_TASK_MEMSIZE
PRM_ID_STATS_ON
PRM_ID_LOADDB_WORKER_COUNT
PRM_ID_PERF_TEST_MODE
PRM_ID_REPR_CACHE_LOG
PRM_ID_ENABLE_NEW_LFHASH
PRM_ID_HEAP_INFO_CACHE_LOGGING
PRM_ID_TDE_KEYS_FILE_PATH
PRM_ID_TDE_DEFAULT_ALGORITHM
PRM_ID_JAVA_STORED_PROCEDURE
PRM_ID_JAVA_STORED_PROCEDURE_PORT
PRM_ID_JAVA_STORED_PROCEDURE_JVM_OPTIONS
PRM_ID_JAVA_STORED_PROCEDURE_DEBUG
PRM_ID_JAVA_STORED_PROCEDURE_RESERVE_01
PRM_ID_ALLOW_TRUNCATED_STRING
PRM_ID_TB_DEFAULT_REUSE_OID
PRM_ID_USE_STAT_ESTIMATION
PRM_ID_IGNORE_TRAILING_SPACE
PRM_ID_DDL_AUDIT_LOG
PRM_ID_DDL_AUDIT_LOG_SIZE
PRM_LAST_ID
Definition at line 92 of file system_parameter.h.
enum query_trace_format
Enumerator
QUERY_TRACE_TEXT
QUERY_TRACE_JSON
Definition at line 81 of file system_parameter.h.
enum SYSPRM_DATATYPE
Enumerator
PRM_INTEGER
PRM_FLOAT
PRM_BOOLEAN
PRM_KEYWORD
PRM_BIGINT
PRM_STRING
PRM_INTEGER_LIST
PRM_NO_TYPE
Definition at line 463 of file system_parameter.h.
enum SYSPRM_ERR
Enumerator
PRM_ERR_NO_ERROR
PRM_ERR_NOT_DIRECTORY
PRM_ERR_INIT_FILE_NOT_CREATED
PRM_ERR_CANT_WRITE
PRM_ERR_CANT_ACCESS
PRM_ERR_NO_HOME
PRM_ERR_NO_VALUE
PRM_ERR_CANT_OPEN_INIT
PRM_ERR_BAD_LINE
PRM_ERR_BAD_ENV_VAR
PRM_ERR_UNKNOWN_PARAM
PRM_ERR_BAD_VALUE
PRM_ERR_NO_MEM_FOR_PRM
PRM_ERR_BAD_STRING
PRM_ERR_BAD_RANGE
PRM_ERR_UNIX_ERROR
PRM_ERR_NO_MSG
PRM_ERR_RESET_BAD_RANGE
PRM_ERR_KEYWROD_INFO_INT
PRM_ERR_KEYWORK_INFO_FLOAT
PRM_ERR_DEPRICATED
PRM_ERR_NOT_BOTH
PRM_ERR_CANNOT_CHANGE
PRM_ERR_NOT_FOR_CLIENT
PRM_ERR_NOT_FOR_SERVER
PRM_ERR_NOT_SOLE_TRAN
PRM_ERR_COMM_ERR
PRM_ERR_FILE_ERR
PRM_ERR_NOT_FOR_CLIENT_NO_AUTH
PRM_ERR_BAD_PARAM
Definition at line 37 of file system_parameter.h.
enum sysprm_load_flag
Enumerator
SYSPRM_LOAD_ALL
SYSPRM_IGNORE_HA
SYSPRM_IGNORE_INTL_PARAMS
Definition at line 504 of file system_parameter.h.
Function Documentation
UINT64 prm_get_bigint_value (PARAM_ID prm_id)
Definition at line 11040 of file system_parameter.c.
References assert, PRM_GET_BIGINT, prm_get_value(), PRM_IS_BIGINT, and PRM_LAST_ID.
Referenced by index_builder_loader_task::add_key(), addvoldb(), check_hash_list_scan(), createdb(), db_string_pad(), db_string_repeat(), db_string_space(), disk_cache_init(), fileio_flush_backup(), fileio_get_lockf_type(), fileio_initialize_backup(), hb_create_master_reader(), hb_thread_initialize(), logddl_write(), logddl_write_end_for_csql_fileinput(), logddl_write_tran_str(), qdata_group_concat_first_value(), qdata_group_concat_value(), qexec_hash_gby_agg_tuple(), qstr_bit_concatenate(), qstr_concatenate(), qstr_grow_string(), and xboot_initialize_server().
bool prm_get_bool_value (PARAM_ID prm_id)
Definition at line 10979 of file system_parameter.c.
References assert, PRM_GET_BOOL, prm_get_value(), PRM_IS_BOOLEAN, and PRM_LAST_ID.
Referenced by boot_restart_client(), boot_restart_server(), boot_server_die_or_changed(), boot_shutdown_client(), btree_apply_key_range_and_filter(), btree_construct_leafs(), btree_delete_internal(), btree_delete_postponed(), btree_insert(), btree_insert_internal(), btree_key_lock_and_append_object_unique(), btree_mvcc_delete(), btree_online_index_list_dispatcher(), btree_physical_delete(), btree_prepare_bts(), btree_reflect_global_unique_statistics(), btree_rv_record_modify_internal(), btree_rv_redo_global_unique_stats_commit(), btree_rv_undo_global_unique_stats_commit(), btree_sort_get_next(), btree_split_node(), btree_split_root(), btree_undo_delete_physical(), btree_undo_insert_object(), btree_undo_insert_object_unique_multiupd(), btree_undo_mvcc_delete(), btree_vacuum_insert_mvccid(), btree_vacuum_object(), build_att_type_change_map(), build_attr_change_map(), cas_main(), check_att_chg_allowed(), crash_handler(), csql(), csql_execute_statements(), csql_is_auto_commit_requested(), csql_set_trace(), csql_walk_statement(), css_get_connection_thread_pooling_configuration(), css_get_server_request_thread_pooling_configuration(), css_init(), css_is_shutdown_timeout_expired(), css_notify_ha_log_applier_state(), css_open_server_connection_socket(), css_process_new_client(), css_sockopt(), css_tcp_client_open_with_retry(), db_abs_dbval(), db_add_days_to_year(), db_add_time(), db_ascii(), db_bigint_to_binary_string(), db_ceil_dbval(), db_constraint_type(), db_conv(), db_convert_sec_to_time(), db_convert_time_to_sec(), db_convert_to_time(), db_crc32_dbval(), db_date_add_sub_interval_days(), db_date_add_sub_interval_expr(), db_date_dbval(), db_date_diff(), db_evaluate_json_search(), db_find_string_in_in_set(), db_floor_dbval(), db_from_unixtime(), db_get_cs_coll_info(), db_get_date_dayofyear(), db_get_date_item(), db_get_date_quarter(), db_get_date_totaldays(), db_get_date_week(), db_get_date_weekday(), db_get_schema_def_dbval(), db_get_time_item(), db_guid(), db_hex(), db_inet_aton(), db_inet_ntoa(), db_last_day(), db_mod_bigint(), db_mod_dbval(), db_mod_double(), db_mod_float(), db_mod_int(), db_mod_monetary(), db_mod_numeric(), db_mod_short(), db_mod_string(), db_round_dbval(), db_str_to_date(), db_string_aes_decrypt(), db_string_aes_encrypt(), db_string_chr(), db_string_compare(), db_string_concatenate(), db_string_from_base64(), db_string_insert_substring(), db_string_prefix_compare(), db_string_regexp_count(), db_string_regexp_instr(), db_string_regexp_like(), db_string_regexp_replace(), db_string_regexp_substr(), db_string_repeat(), db_string_replace(), db_string_rlike(), db_string_sha_one(), db_string_sha_two(), db_string_substring_index(), db_string_to_base64(), db_string_unique_prefix(), db_time_dbval(), db_time_diff(), db_trunc_dbval(), disk_manager_init(), do_alter_clause_change_attribute(), do_check_delete_trigger(), do_check_merge_trigger(), do_check_update_trigger(), do_create_entity(), do_execute_delete(), do_execute_do(), do_execute_insert(), do_execute_select(), do_execute_session_statement(), do_execute_statement(), do_execute_update(), do_select_internal(), do_statement(), do_update_new_notnull_cols_without_default(), does_op_specially_treat_null_arg(), dwb_file_sync_helper_daemon_is_running(), dwb_flush_block_daemon_is_running(), dwb_is_file_sync_helper_daemon_available(), dwb_is_flush_block_daemon_available(), dwb_read_page(), eliminate_duplicated_keys(), er_call_stack_dump_on_error(), er_init(), er_log_slow_query(), er_set_area_error(), er_set_internal(), eval_key_filter(), index_builder_loader_task::execute(), fetch_peek_arith(), fi_handler_random_exit(), file_header_sanity_check(), fileio_close(), fileio_flush_control_add_tokens(), fileio_lock(), fileio_mount(), fileio_open(), fileio_unlock(), get_backslash_escape_string(), get_date_weekday(), get_hour_minute_or_second(), get_object_print_format(), get_reference_names(), get_year_month_or_day(), hb_create_master_reader(), hb_thread_initialize(), heap_create_internal(), heap_initialize_hfid_table(), heap_object_upgrade_domain(), histo_is_supported(), hl_clear_lea_heap(), hl_lea_alloc(), hl_lea_free(), hl_lea_realloc(), hl_register_lea_heap(), hl_unregister_lea_heap(), cubthread::lockfree_hashmap< Key, T >::init(), cubthread::initialize(), intl_char_size(), intl_cmp_char(), intl_lower_string(), intl_next_char(), intl_prev_char(), jsp_alter_stored_procedure(), jsp_create_stored_procedure(), jsp_drop_stored_procedure(), la_apply_log_file(), loaddb_internal(), log_append_init_zip(), log_change_tran_as_completed(), log_complete_for_2pc(), log_create_internal(), log_dump_log_info(), log_final(), log_initialize(), log_initialize_internal(), log_recovery_analysis(), log_recovery_redo(), log_recovery_undo(), log_rollback_record(), log_rv_analysis_complete(), log_rv_undo_record(), log_set_no_logging(), logddl_write_end(), logpb_archive_active_log(), logpb_background_archiving(), logpb_checkpoint(), logpb_delete(), logpb_dump_parameter(), logpb_fetch_from_archive(), logpb_flush_all_append_pages(), logpb_flush_pages(), logpb_initialize_pool(), logpb_remove_all_in_log_path(), logpb_remove_archive_logs_exceed_limit(), logpb_remove_archive_logs_internal(), logpb_rename_all_volumes_files(), logpb_write_toflush_pages_to_archive(), logtb_enable_update(), logtb_rv_update_global_unique_stats_by_abs(), logtb_set_loose_end_tdes(), logtb_update_global_unique_stats_by_delta(), main(), JSON_PRIVATE_ALLOCATOR::Malloc(), mr_cmpdisk_char_internal(), mr_cmpval_char(), mr_cmpval_nchar(), mr_cmpval_string(), mr_cmpval_varnchar(), mr_data_cmpdisk_string(), net_server_request(), numeric_db_value_div(), parser_generate_do_stmt_xasl(), parser_generate_xasl(), parser_parse_file(), parser_parse_string_with_escapes(), perfmon_initialize(), pgbuf_flush_checkpoint(), pgbuf_flush_page_and_neighbors_fb(), pgbuf_flush_seq_list(), pgbuf_flush_victim_candidates(), pgbuf_get_victim_candidates_from_lru(), pgbuf_initialize(), pr_clear_value(), pt_bind_names(), pt_bind_value_to_hostvar_local(), pt_check_create_entity(), pt_check_enum_data_type(), pt_check_expr_collation(), pt_coerce_expression_argument(), pt_coerce_value_internal(), pt_eval_expr_type(), pt_evaluate_db_value_expr(), pt_fold_const_expr(), pt_get_expression_definition(), pt_replace_names_in_update_values(), pt_semantic_check_local(), pt_to_buildlist_proc(), pt_to_index_attrs(), pt_to_pred_expr_local_with_arg(), pt_upd_domain_info(), pt_wrap_collection_with_cast_op(), pwrite_with_injected_fault(), qdata_add_date_to_dbval(), qdata_add_dbval(), qdata_divide_dbval(), qdata_get_dbval_from_constant_regu_variable(), qdata_group_concat_first_value(), qdata_group_concat_value(), qdata_multiply_dbval(), qdata_strcat_dbval(), qdata_subtract_dbval(), qdata_unary_minus_dbval(), qdump_print_xasl(), qexec_execute_query(), qexec_fill_sort_limit(), qexec_groupby(), qexec_intprt_fnc(), qfile_update_qlist_count(), qmgr_execute_query(), qo_allocate_like_bound_for_index_scan(), qo_env_new(), qo_examine_merge_join(), qo_optimize_queries(), qo_rewrite_one_like_term(), qstr_grow_string(), JSON_PRIVATE_ALLOCATOR::Realloc(), regu_init(), round_date(), scan_key_compare(), scan_open_index_key_info_scan(), scan_open_index_scan(), session_state_create(), stran_server_auto_commit_or_abort(), sysprm_load_and_init_internal(), tp_domain_select(), tp_value_auto_cast(), tp_value_cast_internal(), tz_get_leapsec_support(), unicode_compose_string(), unicode_decompose_string(), unicode_string_need_compose(), unicode_string_need_decompose(), unloaddb(), vacuum_boot(), vacuum_consume_buffer_log_blocks(), vacuum_data_unload_first_and_last_page(), vacuum_finalize(), vacuum_initialize(), vacuum_is_file_dropped(), vacuum_min_log_pageid_to_keep(), vacuum_process_log_block(), vacuum_produce_log_block_data(), ws_abort_mops(), ws_cache(), ws_clear_all_hints(), ws_clear_hints(), ws_decache(), ws_final(), ws_set_lock(), xboot_emergency_patch(), xbtree_load_index(), xbtree_load_online_index(), xcache_check_recompilation_threshold(), xcache_dump(), xstats_get_statistics_from_server(), and xvacuum().
bool prm_get_commit_on_shutdown (void)
Definition at line 10733 of file system_parameter.c.
References PRM_COMMIT_ON_SHUTDOWN.
Referenced by csql_exit_session(), and uci_disconnect().
float prm_get_float_value (PARAM_ID prm_id)
Definition at line 10994 of file system_parameter.c.
References assert, PRM_GET_FLOAT, prm_get_value(), PRM_IS_FLOAT, and PRM_LAST_ID.
Referenced by heap_create_internal(), heap_reuse(), locator_multi_insert_force(), lock_is_local_deadlock_detection_interval_up(), pgbuf_get_page_flush_interval(), pgbuf_initialize(), pgbuf_initialize_aout_list(), pgbuf_wakeup_page_flush_daemon(), qo_expr_selectivity(), and xlock_dump().
int* prm_get_integer_list_value (PARAM_ID prm_id)
Definition at line 11025 of file system_parameter.c.
References assert, PRM_GET_INTEGER_LIST, prm_get_value(), PRM_IS_INTEGER_LIST, and PRM_LAST_ID.
Referenced by sysprm_find_err_in_integer_list(), and sysprm_find_fi_code_in_integer_list().
int prm_get_integer_value (PARAM_ID prm_id)
Definition at line 10964 of file system_parameter.c.
References assert, PRM_GET_INT, prm_get_value(), PRM_IS_INTEGER, PRM_IS_KEYWORD, and PRM_LAST_ID.
Referenced by boot_create_all_volumes(), boot_initialize_client(), boot_restart_client(), boot_restart_server(), btree_key_insert_new_key(), btree_merge_node(), btree_merge_root(), btree_split_node(), btree_split_root(), btree_verify_node(), compactdb_start(), create_or_drop_index_helper(), csect_demote_critical_section(), csect_enter_critical_section(), csect_enter_critical_section_as_reader(), csect_promote_critical_section(), csql_set_trace(), css_check_magic_with_socket(), css_connect_to_cubrid_server(), css_get_connection_thread_timeout_configuration(), css_get_normal_client_max_conn(), css_get_server_request_thread_timeout_configuration(), css_master_thread(), css_server_connect(), css_server_connect_part_two(), css_sockopt(), css_tcp_client_open_with_retry(), db_acos_dbval(), db_asin_dbval(), db_compile_statement_local(), db_error_init(), db_execute_and_keep_statement_local(), db_get_date_week(), db_json_path_is_token_valid_array_index(), db_power_dbval(), db_sqrt_dbval(), disk_manager_init(), do_alter_one_clause_with_template(), do_create_entity(), do_prepare_merge(), do_scope(), do_set_trace_to_query_flag(), dwb_create_internal(), dwb_file_sync_helper(), dwb_flush_block(), dwb_write_block(), er_file_open(), er_log(), er_set_area_error(), er_set_internal(), eval_action(), eval_condition(), eval_pred(), event_file_open(), event_log_start(), fetch_peek_arith(), file_tempcache_init(), file_tempcache_put(), fileio_compensate_flush(), fileio_flush_control_add_tokens(), fileio_get_lockf_type(), fileio_initialize_backup(), fileio_initialize_backup_thread(), fileio_mount(), fileio_read(), fileio_read_backup(), fileio_read_pages(), fileio_synchronize(), fileio_unformat_and_rename(), fileio_write(), fileio_write_pages(), fpcache_initialize(), hb_cleanup_conn_and_start_process(), hb_cluster_calc_score(), hb_cluster_initialize(), hb_cluster_is_received_heartbeat_from_all(), hb_cluster_job_calc_score(), hb_cluster_job_check_ping(), hb_cluster_job_failback(), hb_cluster_job_failover(), hb_cluster_job_heartbeat(), hb_cluster_job_init(), hb_cluster_send_heartbeat_req(), hb_deregister_process(), hb_master_init(), hb_process_master_request(), hb_resource_job_change_mode(), hb_resource_job_cleanup_all(), hb_resource_job_confirm_cleanup_all(), hb_resource_job_confirm_dereg(), hb_resource_job_confirm_start(), hb_resource_job_demote_confirm_shutdown(), hb_resource_job_demote_start_shutdown(), hb_resource_job_initialize(), hb_resource_job_proc_dereg(), hb_resource_job_proc_start(), hb_thread_check_disk_failure(), heap_check_all_pages(), heap_reuse(), heap_stats_add_bestspace(), heap_stats_find_page_in_bestspace(), heap_stats_sync_bestspace(), heap_stats_update(), heap_vpid_alloc(), cubthread::is_logging_configured(), is_server_insert_allowed(), javasp_start_server(), jsp_start_server(), la_apply_log_file(), la_create_repl_filter(), la_delay_replica(), la_get_adaptive_time_commit_interval(), la_log_page_check(), la_remove_archive_logs(), ldr_clear_context(), loaddb_internal(), lock_add_composite_lock(), lock_classes_lock_hint(), lock_finalize_composite_lock(), lock_object(), lock_scan(), lock_subclass(), log_complete_for_2pc(), log_create_internal(), log_get_checkpoint_interval(), log_get_log_group_commit_interval(), log_initialize_internal(), log_is_log_flush_daemon_available(), logpb_archive_active_log(), logpb_backup(), logpb_dump_parameter(), logpb_flush_all_append_pages(), logpb_initialize_pool(), logpb_next_append_page(), logpb_remove_archive_logs_exceed_limit(), logpb_start_append(), logpb_write_toflush_pages_to_archive(), logwr_log_ha_filestat_to_string(), main(), net_client_init(), net_server_start(), perfmon_initialize(), pgbuf_flush_chkpt_seq_list(), pgbuf_get_check_page_validation_level(), pgbuf_get_page_flush_interval(), pgbuf_initialize(), pgbuf_initialize_lru_list(), pgbuf_initialize_page_quota_parameters(), pt_check_ordby_num_for_multi_range_opt(), pt_common_type(), pt_eval_expr_type(), pt_evaluate_db_value_expr(), pt_plan_query(), pt_recompile_for_limit_optimizations(), qdata_add_bigint_to_date(), qdata_add_bigint_to_time(), qdata_add_bigint_to_timestamptz(), qdata_add_bigint_to_utime(), qdata_add_int_to_date(), qdata_add_int_to_timestamptz(), qdata_add_int_to_utime(), qdata_add_monetary(), qdata_add_short_to_date(), qdata_add_short_to_timestamptz(), qdata_add_short_to_utime(), qexec_execute_cte(), qexec_execute_mainblock(), qexec_setup_topn_proc(), qfile_initialize(), qfile_initialize_list_cache(), qfile_update_list_cache_entry(), qmgr_create_new_temp_file(), qmgr_create_result_file(), qmgr_get_new_page(), qmgr_initialize_temp_file_list(), qmgr_is_allowed_result_cache(), qo_discover_sort_limit_nodes(), qo_follow_cost(), qo_get_optimization_param(), qo_iscan_cost(), qo_nljoin_cost(), qo_optimize_queries(), qo_set_optimization_param(), qo_sort_cost(), session_check_timeout(), cubthread::manager::set_max_thread_count_from_config(), set_optimization_level(), sort_add_new_file(), sort_inphase_sort(), sort_listfile(), sqmgr_execute_query(), start_csql(), unloaddb(), util_get_ha_mode_for_sa_utils(), util_get_ha_parameters(), util_log_file_fopen(), vacuum_boot(), cubload::worker_manager_register_session(), ws_init(), xboot_register_client(), xcache_initialize(), xheap_reclaim_addresses(), and xlock_dump().
int prm_get_master_port_id (void)
Definition at line 10727 of file system_parameter.c.
References PRM_TCP_PORT_ID.
Referenced by check_all_services_status(), connect_to_master_for_server_monitor(), css_get_master_domain_path(), hb_connect_to_master(), is_server_running(), master_util_config_startup(), process_heartbeat_deregister(), process_heartbeat_reload(), process_heartbeat_replication(), process_heartbeat_start(), process_heartbeat_status(), process_heartbeat_stop(), process_master(), process_server(), and process_service().
const char* prm_get_name (PARAM_ID prm_id)
Definition at line 10911 of file system_parameter.c.
References assert, sysprm_param::name, and PRM_LAST_ID.
Referenced by addvoldb(), applyinfo(), applylogdb(), backupdb(), boot_restart_server(), checkdb(), compactdb(), copydb(), copylogdb(), createdb(), deletedb(), diagdb(), hb_cluster_initialize(), hb_reload_config(), installdb(), la_delay_replica(), loaddb_internal(), main(), optimizedb(), paramdump(), renamedb(), restoredb(), restoreslave(), spacedb(), statdump(), synccolldb(), unloaddb(), util_get_ha_parameters(), util_make_ha_conf(), vacuumdb(), and xboot_shutdown_server().
char* prm_get_string_value (PARAM_ID prm_id)
Definition at line 11009 of file system_parameter.c.
References assert, PRM_GET_STRING, prm_get_value(), PRM_IS_STRING, and PRM_LAST_ID.
Referenced by applyinfo(), applylogdb(), boot_find_rest_temp_volumes(), boot_get_new_volume_name_and_id(), boot_make_temp_volume_fullname(), boot_restart_client(), boot_restart_server(), cfg_create_host_list(), cfg_read_directory(), crash_handler(), css_get_required_conn_num_for_ha(), css_notify_ha_log_applier_state(), delete_all_slave_ha_apply_info(), dl_initiate_dynamic_loader(), do_evaluate_default_expr(), er_event(), er_event_final(), er_event_init(), er_init(), hb_cluster_initialize(), hb_master_init(), hb_reload_config(), insert_ha_apply_info(), jsp_start_server(), la_create_repl_filter(), la_delay_replica(), la_log_page_check(), lang_get_client_charset(), lang_get_client_collation(), load_properties(), pt_check_default_vclass_query_spec(), pt_eval_expr_type(), pt_find_attr_in_class_list(), pt_resolve_default_value(), qexec_execute_insert(), sysprm_generate_new_value(), sysprm_init_intl_param(), sysprm_print_parameters_for_ha_repl(), tde_make_keys_file_fullname(), tz_get_session_local_timezone(), tz_get_system_timezone(), util_get_ha_parameters(), and util_is_replica_node().
void* prm_get_value (PARAM_ID prm_id)
Definition at line 10929 of file system_parameter.c.
References assert, BO_IS_SERVER_RESTARTED, PRM_LAST_ID, PRM_SERVER_SESSION, session_get_session_parameter(), thread_get_thread_entry_info(), session_param::value, and sysprm_param::value.
Referenced by css_sockopt(), prm_get_bigint_value(), prm_get_bool_value(), prm_get_float_value(), prm_get_integer_list_value(), prm_get_integer_value(), and prm_get_string_value().
void prm_set_bigint_value (PARAM_ID prm_id, UINT64 value)
Definition at line 11167 of file system_parameter.c.
References assert, PRM_GET_BIGINT, PRM_IS_BIGINT, PRM_LAST_ID, sysprm_update_flag_different(), and sysprm_param::value.
Referenced by sysprm_set_system_parameter_value().
void prm_set_bool_value (PARAM_ID prm_id, bool value)
Definition at line 11076 of file system_parameter.c.
References assert, PRM_GET_BOOL, PRM_IS_BOOLEAN, PRM_LAST_ID, sysprm_update_flag_different(), and sysprm_param::value.
Referenced by csql_set_trace(), do_set_query_trace(), sysprm_set_system_parameter_value(), and xboot_restart_from_backup().
void prm_set_float_value (PARAM_ID prm_id, float value)
Definition at line 11094 of file system_parameter.c.
References assert, PRM_GET_FLOAT, PRM_IS_FLOAT, PRM_LAST_ID, sysprm_update_flag_different(), and sysprm_param::value.
Referenced by sysprm_set_system_parameter_value().
void prm_set_integer_list_value (PARAM_ID prm_id, int * value)
Definition at line 11140 of file system_parameter.c.
References assert, sysprm_param::dynamic_flag, free_and_init, NULL, PRM_ALLOCATED, PRM_CLEAR_BIT, PRM_GET_INTEGER_LIST, PRM_IS_ALLOCATED, PRM_IS_INTEGER_LIST, PRM_LAST_ID, PRM_SET_BIT, sysprm_update_flag_different(), and sysprm_param::value.
Referenced by sysprm_final(), and sysprm_set_system_parameter_value().
void prm_set_integer_value (PARAM_ID prm_id, int value)
Definition at line 11058 of file system_parameter.c.
References assert, PRM_GET_INT, PRM_IS_INTEGER, PRM_IS_KEYWORD, PRM_LAST_ID, sysprm_update_flag_different(), and sysprm_param::value.
Referenced by csql_set_trace(), css_transit_ha_server_state(), do_set_query_trace(), qo_set_optimization_param(), reset_optimization_level_as_saved(), set_optimization_level(), sysprm_set_system_parameter_value(), us_hb_applylogdb_start(), us_hb_copylogdb_start(), and us_hb_server_start().
void prm_set_string_value (PARAM_ID prm_id, char * value)
Definition at line 11112 of file system_parameter.c.
References assert, sysprm_param::dynamic_flag, free_and_init, NULL, PRM_ALLOCATED, PRM_CLEAR_BIT, PRM_GET_STRING, PRM_IS_ALLOCATED, PRM_IS_STRING, PRM_LAST_ID, PRM_SET_BIT, sysprm_update_flag_different(), and sysprm_param::value.
Referenced by sysprm_set_system_parameter_value().
void sysprm_change_parameter_values (const SYSPRM_ASSIGN_VALUE * assignments, bool check, bool set_flag)
Definition at line 7870 of file system_parameter.c.
References css_set_accessible_ip_info(), GET_PRM, sysprm_assign_value::next, NULL, sysprm_assign_value::prm_id, PRM_ID_ACCESS_IP_CONTROL, PRM_IS_FOR_CLIENT, PRM_IS_FOR_SERVER, PRM_IS_FOR_SESSION, sysprm_param::static_flag, sysprm_get_id(), sysprm_set_value(), and sysprm_assign_value::value.
Referenced by db_set_system_parameters(), prm_tune_parameters(), and xsysprm_change_server_parameters().
SYSPRM_ERR sysprm_change_server_parameters (const SYSPRM_ASSIGN_VALUE * assignments)
Definition at line 8264 of file network_interface_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, net_client_request(), NET_SERVER_PRM_SET_PARAMETERS, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), PRM_ERR_COMM_ERR, PRM_ERR_NO_ERROR, PRM_ERR_NO_MEM_FOR_PRM, rc, sysprm_pack_assign_values(), sysprm_packed_assign_values_length(), and xsysprm_change_server_parameters().
Referenced by db_set_system_parameters().
int sysprm_check_range (const char * pname, void * value)
Definition at line 8908 of file system_parameter.c.
References error(), NULL, prm_check_range(), PRM_ERR_UNKNOWN_PARAM, and prm_find().
Referenced by createdb().
void sysprm_dump_parameters (FILE * fp)
Definition at line 6446 of file system_parameter.c.
References conf_path, db_name, i, MAX_NUM_OF_PRM_FILES_LOADED, NULL, NUM_PRM, prm_Files_loaded, PRM_IS_HIDDEN, PRM_IS_OBSOLETED, prm_print(), PRM_PRINT_CURR_VAL, PRM_PRINT_NAME, and sysprm_param::static_flag.
Referenced by paramdump(), sysprm_load_and_init_internal(), and xsysprm_dump_server_parameters().
void sysprm_dump_server_parameters (FILE * fp)
Definition at line 8451 of file network_interface_cl.c.
References net_client_request_recv_stream(), NET_SERVER_PRM_DUMP_PARAMETERS, NULL, and xsysprm_dump_server_parameters().
Referenced by paramdump().
void sysprm_final (void)
Definition at line 10282 of file system_parameter.c.
References ARG_FILE_LINE, assert, call_stack_dump_error_codes, conf_path, css_get_max_socket_fds(), CUB_MAXHOSTNAMELEN, sysprm_param::datatype, db_name, sysprm_param::dynamic_flag, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), fi_Groups, FI_TEST_NONE, free_and_init, GET_PRM, GETHOSTNAME, HA_MODE_OFF, HA_MODE_REPLICA, HA_SERVER_STATE_ACTIVE_STR, HA_SERVER_STATE_STANDBY_STR, i, MAX_NUM_OF_PRM_FILES_LOADED, MSGCAT_CATALOG_CUBRID, msgcat_message(), MSGCAT_SET_PARAMETERS, sysprm_param::name, NULL, NUM_PRM, PRM_ALLOCATED, PRM_CLEAR_BIT, prm_css_max_clients_upper, PRM_DEFAULT_USED, PRM_DEFAULT_VAL_USED, PRM_ERR_NO_ERROR, PRM_ERR_NO_VALUE, prm_Files_loaded, prm_find(), PRM_FOR_QRY_STRING, PRM_GET_BOOL, PRM_GET_INT, PRM_GET_INTEGER_LIST, PRM_GET_STRING, PRM_HA_MODE, PRM_HA_MODE_FOR_SA_UTILS_ONLY, PRM_ID_CALL_STACK_DUMP_ACTIVATION, PRM_ID_FAULT_INJECTION_IDS, PRM_ID_FAULT_INJECTION_TEST, PRM_INTEGER_LIST, PRM_IS_ALLOCATED, PRM_IS_SET, PRM_NAME_AUTO_RESTART_SERVER, PRM_NAME_CSS_MAX_CLIENTS, PRM_NAME_FORCE_REMOVE_LOG_ARCHIVES, PRM_NAME_HA_MODE, PRM_NAME_HA_NODE_LIST, PRM_NAME_HA_SERVER_STATE, PRM_NAME_LIST_MAX_QUERY_CACHE_ENTRIES, PRM_NAME_LIST_MAX_QUERY_CACHE_PAGES, PRM_NAME_LIST_QUERY_CACHE_MODE, PRM_NAME_LOG_BACKGROUND_ARCHIVING, PRM_NAME_LOG_MAX_ARCHIVES, PRM_NAME_PB_AOUT_RATIO, PRM_NAME_SERVER_TIMEZONE, PRM_NAME_TEST_MODE, PRM_NAME_TZ_LEAP_SECOND_SUPPORT, PRM_NAME_XASL_CACHE_MAX_ENTRIES, PRM_SET, prm_set(), PRM_SET_BIT, prm_set_default(), prm_set_integer_list_value(), PRM_STRING, prm_tune_parameters(), sysprm_param::static_flag, TZ_GENERIC_NAME_SIZE, tz_get_data(), tz_resolve_os_timezone(), and sysprm_param::value.
Referenced by boot_client_all_finalize(), boot_initialize_client(), boot_restart_client(), and boot_server_all_finalize().
bool sysprm_find_err_in_integer_list (PARAM_ID prm_id, int error_code)
Definition at line 11186 of file system_parameter.c.
References i, NULL, and prm_get_integer_list_value().
Referenced by er_call_stack_dump_on_error(), er_notify_event_on_error(), la_ignore_on_error(), and la_retry_on_error().
bool sysprm_find_fi_code_in_integer_list (PARAM_ID prm_id, int fi_code)
Definition at line 11215 of file system_parameter.c.
References i, NULL, and prm_get_integer_list_value().
Referenced by fi_set(), fi_set_force(), fi_state(), fi_test(), and fi_test_on().
void sysprm_free_assign_values (SYSPRM_ASSIGN_VALUE ** assign_values_ptr)
Definition at line 11891 of file system_parameter.c.
References free_and_init, GET_PRM_DATATYPE, sysprm_assign_value::next, NULL, sysprm_assign_value::prm_id, sysprm_clear_sysprm_value(), and sysprm_assign_value::value.
Referenced by db_get_system_parameters(), db_set_system_parameters(), prm_tune_parameters(), sprm_server_change_parameters(), sprm_server_get_force_parameters(), sprm_server_obtain_parameters(), sysprm_obtain_parameters(), sysprm_obtain_server_parameters(), sysprm_unpack_assign_values(), sysprm_validate_change_parameters(), and xsysprm_get_force_server_parameters().
void sysprm_free_session_parameters (SESSION_PARAM ** session_parameters)
Definition at line 11403 of file system_parameter.c.
References assert, session_param::datatype, free_and_init, i, NULL, NUM_SESSION_PRM, sysprm_clear_sysprm_value(), and session_param::value.
Referenced by csession_find_or_create_session(), session_state_uninit(), sysprm_get_id(), sysprm_load_and_init_internal(), and sysprm_unpack_session_parameters().
int sysprm_get_force_server_parameters (SYSPRM_ASSIGN_VALUE ** change_values)
Definition at line 8394 of file network_interface_cl.c.
References assert, error(), free_and_init, net_client_request2(), NET_SERVER_PRM_GET_FORCE_PARAMETERS, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), and sysprm_unpack_assign_values().
Referenced by prm_tune_parameters().
int sysprm_get_range (const char * pname, void * min, void * max)
Definition at line 8884 of file system_parameter.c.
References assert, sysprm_param::get_dup, NULL, PRM_DIFFERENT_UNIT, PRM_ERR_UNKNOWN_PARAM, prm_find(), sysprm_param::static_flag, and sysprm_get_param_range().
Referenced by createdb().
int sysprm_get_session_parameters_count (void)
Definition at line 12626 of file system_parameter.c.
References assert, sysprm_param::dynamic_flag, session_param::flag, GET_PRM, i, NUM_SESSION_PRM, session_param::prm_id, sysprm_set_sysprm_value_from_parameter(), sysprm_update_session_prm_flag_allocated(), and session_param::value.
Referenced by session_get_session_parameter().
int sysprm_init_intl_param (void)
Definition at line 12492 of file system_parameter.c.
References sysprm_param::dynamic_flag, error(), LANG_GET_BINARY_COLLATION, lang_get_collation_name(), lang_get_Lang_name(), LANG_SYS_CODESET, NO_ERROR, NULL, prm_find(), prm_get_string_value(), PRM_ID_INTL_COLLATION, PRM_ID_INTL_DATE_LANG, PRM_ID_INTL_NUMBER_LANG, PRM_ID_SERVER_TIMEZONE, PRM_ID_TIMEZONE, PRM_IS_SET, PRM_NAME_INTL_COLLATION, PRM_NAME_INTL_DATE_LANG, PRM_NAME_INTL_NUMBER_LANG, PRM_NAME_TIMEZONE, and prm_set().
Referenced by boot_restart_client().
int sysprm_load_and_init (const char * db_name, const char * conf_file, const int load_flags)
Definition at line 6802 of file system_parameter.c.
References sysprm_load_and_init_internal().
Referenced by applyinfo(), applylogdb(), boot_remove_all_volumes(), boot_restart_server(), checksumdb(), connect_to_master_for_server_monitor(), copylogdb(), createdb(), load_properties(), loaddb_internal(), main(), master_util_config_startup(), net_server_start(), paramdump(), patchdb(), process_heartbeat_start(), process_heartbeat_stop(), process_heartbeat_util(), process_server(), restoreslave(), us_hb_applylogdb_start(), us_hb_copylogdb_start(), us_hb_server_start(), xboot_delete(), xboot_emergency_patch(), xboot_initialize_server(), and xboot_restart_from_backup().
int sysprm_load_and_init_client (const char * db_name, const char * conf_file)
Definition at line 6816 of file system_parameter.c.
References SYSPRM_LOAD_ALL, and sysprm_load_and_init_internal().
Referenced by boot_initialize_client(), and boot_restart_client().
SYSPRM_ERR sysprm_make_default_values (const char * data, char * default_val_buf, const int buf_size)
Definition at line 7790 of file system_parameter.c.
References err, intl_mbs_ncpy(), LANG_GET_BINARY_COLLATION, lang_get_collation_name(), lang_get_Lang_name(), LANG_SYS_CODESET, sysprm_param::name, NULL, p, PRM_ERR_BAD_VALUE, PRM_ERR_NO_ERROR, PRM_ERR_UNKNOWN_PARAM, prm_find(), prm_get_next_param_value(), PRM_ID_INTL_COLLATION, PRM_ID_INTL_DATE_LANG, PRM_ID_INTL_NUMBER_LANG, PRM_ID_TIMEZONE, PRM_NAME_INTL_COLLATION, PRM_NAME_INTL_DATE_LANG, PRM_NAME_INTL_NUMBER_LANG, PRM_NAME_TIMEZONE, prm_print(), PRM_PRINT_DEFAULT_VAL, PRM_PRINT_NAME, sysprm_get_id(), tz_get_system_timezone(), and sysprm_param::value.
Referenced by db_reset_system_parameters_from_assignments(), and sl_write_statement_sql().
SYSPRM_ERR sysprm_obtain_parameters (char * data, SYSPRM_ASSIGN_VALUE ** prm_values)
Definition at line 8533 of file system_parameter.c.
References ARG_FILE_LINE, assert, char_isspace(), ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), intl_mbs_ncpy(), sysprm_param::name, sysprm_assign_value::next, NULL, p, PRM_ERR_BAD_VALUE, PRM_ERR_CANNOT_CHANGE, PRM_ERR_NO_ERROR, PRM_ERR_NO_MEM_FOR_PRM, PRM_ERR_NO_VALUE, PRM_ERR_NOT_FOR_CLIENT, PRM_ERR_UNKNOWN_PARAM, prm_find(), sysprm_assign_value::prm_id, PRM_IS_FOR_CLIENT, PRM_IS_FOR_SERVER, PRM_IS_GET_SERVER, sysprm_param::static_flag, sysprm_free_assign_values(), sysprm_get_id(), sysprm_set_sysprm_value_from_parameter(), sysprm_assign_value::value, and sysprm_param::value.
Referenced by db_get_system_parameters().
SYSPRM_ERR sysprm_obtain_server_parameters (SYSPRM_ASSIGN_VALUE ** prm_values_ptr)
Definition at line 8316 of file network_interface_cl.c.
References ARG_FILE_LINE, assert, cleanup(), ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, net_client_request2(), NET_SERVER_PRM_GET_PARAMETERS, NO_ERROR, NULL, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, OR_INT_SIZE, or_unpack_int(), PRM_ERR_COMM_ERR, PRM_ERR_NO_ERROR, PRM_ERR_NO_MEM_FOR_PRM, rc, sysprm_free_assign_values(), sysprm_pack_assign_values(), sysprm_packed_assign_values_length(), sysprm_unpack_assign_values(), and xsysprm_obtain_server_parameters().
Referenced by db_get_system_parameters().
char* sysprm_pack_assign_values (char * ptr, const SYSPRM_ASSIGN_VALUE * assign_values)
Definition at line 11768 of file system_parameter.c.
References ASSERT_ALIGN, cubregex::count(), GET_PRM_DATATYPE, INT_ALIGNMENT, sysprm_assign_value::next, NULL, OR_INT_SIZE, or_pack_int(), OR_PUT_INT, sysprm_assign_value::prm_id, sysprm_pack_sysprm_value(), and sysprm_assign_value::value.
Referenced by sprm_server_get_force_parameters(), sprm_server_obtain_parameters(), sysprm_change_server_parameters(), and sysprm_obtain_server_parameters().
char* sysprm_pack_session_parameters (char * ptr, SESSION_PARAM * session_parameters)
Definition at line 11643 of file system_parameter.c.
References ASSERT_ALIGN, session_param::datatype, session_param::flag, i, INT_ALIGNMENT, NULL, NUM_SESSION_PRM, or_pack_int(), session_param::prm_id, sysprm_pack_sysprm_value(), and session_param::value.
Referenced by csession_find_or_create_session(), and ssession_find_or_create_session().
int sysprm_packed_assign_values_length (const SYSPRM_ASSIGN_VALUE * assign_values, int offset)
Definition at line 11797 of file system_parameter.c.
References GET_PRM_DATATYPE, sysprm_assign_value::next, NULL, OR_INT_SIZE, sysprm_assign_value::prm_id, sysprm_packed_sysprm_value_length(), and sysprm_assign_value::value.
Referenced by sprm_server_get_force_parameters(), sprm_server_obtain_parameters(), sysprm_change_server_parameters(), and sysprm_obtain_server_parameters().
int sysprm_packed_session_parameters_length (SESSION_PARAM * session_parameters, int offset)
Definition at line 11678 of file system_parameter.c.
References session_param::datatype, i, NULL, NUM_SESSION_PRM, OR_INT_SIZE, sysprm_packed_sysprm_value_length(), and sysprm_param::value.
Referenced by csession_find_or_create_session(), and ssession_find_or_create_session().
int sysprm_print_assign_values (SYSPRM_ASSIGN_VALUE * prm_values, char * buffer, int length)
Definition at line 12328 of file system_parameter.c.
References sysprm_assign_value::next, NULL, sysprm_assign_value::prm_id, PRM_PRINT_NAME, sysprm_print_sysprm_value(), and sysprm_assign_value::value.
Referenced by db_get_system_parameters().
char* sysprm_print_parameters_for_ha_repl (void)
Definition at line 12411 of file system_parameter.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), GET_PRM, GET_PRM_DYNAMIC_FLAG, GET_PRM_STATIC_FLAG, i, LANG_GET_BINARY_COLLATION, lang_get_collation_name(), lang_get_Lang_name(), LANG_SYS_CODESET, NULL, NUM_PRM, prm_get_string_value(), PRM_ID_INTL_COLLATION, PRM_ID_INTL_DATE_LANG, PRM_ID_INTL_NUMBER_LANG, PRM_IS_DIFFERENT, PRM_IS_FOR_HA_CONTEXT, prm_print(), PRM_PRINT_CURR_VAL, and PRM_PRINT_NAME.
Referenced by do_replicate_statement().
char* sysprm_print_parameters_for_qry_string (void)
Definition at line 12358 of file system_parameter.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), GET_PRM, i, NULL, NUM_PRM, prm_print(), PRM_PRINT_CURR_VAL, PRM_PRINT_ID, and PRM_PRINT_QRY_STRING.
Referenced by parser_print_tree().
int sysprm_reload_and_init (const char * db_name, const char * conf_file)
Definition at line 6829 of file system_parameter.c.
References SYSPRM_LOAD_ALL, and sysprm_load_and_init_internal().
Referenced by hb_master_init(), hb_reload_config(), and log_get_io_page_size().
void sysprm_set_er_log_file (const char * base_db_name)
Definition at line 6492 of file system_parameter.c.
References basename(), DB_MAX_IDENTIFIER_LENGTH, sysprm_param::dynamic_flag, ER_LOG_FILE_DIR, NULL, PATH_SEPARATOR, prm_find(), PRM_IS_SET, PRM_NAME_ER_LOG_FILE, prm_set(), and strncpy_bufsize.
Referenced by net_server_start(), and sysprm_load_and_init_internal().
int sysprm_set_error (SYSPRM_ERR rc, const char * data)
Definition at line 12556 of file system_parameter.c.
References ARG_FILE_LINE, er_errid(), ER_ERROR_SEVERITY, ER_GENERIC_ERROR, ER_NET_SERVER_COMM_ERROR, ER_NOT_SOLE_TRAN, ER_PRM_BAD_VALUE, ER_PRM_BAD_VALUE_NO_DATA, ER_PRM_CANNOT_CHANGE, ER_PRM_CANNOT_CHANGE_NO_DATA, er_set(), error(), NO_ERROR, PRM_ERR_BAD_RANGE, PRM_ERR_BAD_STRING, PRM_ERR_BAD_VALUE, PRM_ERR_CANNOT_CHANGE, PRM_ERR_COMM_ERR, PRM_ERR_NO_ERROR, PRM_ERR_NO_MEM_FOR_PRM, PRM_ERR_NOT_FOR_CLIENT, PRM_ERR_NOT_FOR_SERVER, PRM_ERR_NOT_SOLE_TRAN, and PRM_ERR_UNKNOWN_PARAM.
Referenced by db_get_system_parameters(), db_reset_system_parameters_from_assignments(), db_set_system_parameters(), sl_write_statement_sql(), and ssession_find_or_create_session().
int sysprm_set_force (const char * pname, const char * pvalue)
Definition at line 10123 of file system_parameter.c.
References ER_PRM_BAD_VALUE, ER_PRM_CANNOT_CHANGE, NO_ERROR, NULL, prm_find(), and prm_set_force().
Referenced by addvoldb(), backupdb(), checkdb(), compactdb(), conn_restart_client(), copydb(), copylogdb(), createdb(), deletedb(), diagdb(), installdb(), loaddb_internal(), main(), optimizedb(), paramdump(), renamedb(), restoredb(), restoreslave(), spacedb(), synccolldb(), unloaddb(), vacuumdb(), and xboot_shutdown_server().
int sysprm_set_to_default (const char * pname, bool set_to_force)
Definition at line 10152 of file system_parameter.c.
References ER_PRM_BAD_VALUE, ER_PRM_CANNOT_CHANGE, NO_ERROR, NULL, prm_find(), prm_print(), PRM_PRINT_CURR_VAL, PRM_PRINT_NONE, prm_set_default(), and prm_set_force().
Referenced by copylogdb().
void sysprm_tune_client_parameters (void)
Referenced by boot_restart_client(), and prm_tune_parameters().
char* sysprm_unpack_assign_values (char * ptr, SYSPRM_ASSIGN_VALUE ** assign_values_ptr)
Definition at line 11824 of file system_parameter.c.
References ARG_FILE_LINE, assert, ASSERT_ALIGN, cubregex::count(), ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, GET_PRM_DATATYPE, i, INT_ALIGNMENT, sysprm_assign_value::next, NULL, or_unpack_int(), sysprm_assign_value::prm_id, sysprm_free_assign_values(), sysprm_unpack_sysprm_value(), and sysprm_assign_value::value.
Referenced by sprm_server_change_parameters(), sprm_server_obtain_parameters(), sysprm_get_force_server_parameters(), and sysprm_obtain_server_parameters().
char* sysprm_unpack_session_parameters (char * ptr, SESSION_PARAM ** session_parameters_ptr)
Definition at line 11706 of file system_parameter.c.
References ARG_FILE_LINE, assert, ASSERT_ALIGN, session_param::datatype, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), session_param::flag, INT_ALIGNMENT, NULL, NUM_SESSION_PRM, or_unpack_int(), session_param::prm_id, sysprm_alloc_session_parameters(), sysprm_free_session_parameters(), sysprm_unpack_sysprm_value(), sysprm_update_session_prm_flag_allocated(), and session_param::value.
Referenced by csession_find_or_create_session(), and ssession_find_or_create_session().
SYSPRM_ERR sysprm_validate_change_parameters (const char * data, bool check, SYSPRM_ASSIGN_VALUE ** assignments_ptr)
Definition at line 7663 of file system_parameter.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), err, free_and_init, intl_mbs_ncpy(), sysprm_param::name, sysprm_assign_value::next, NULL, p, PRM_ERR_BAD_VALUE, PRM_ERR_CANNOT_CHANGE, PRM_ERR_NO_ERROR, PRM_ERR_NO_MEM_FOR_PRM, PRM_ERR_NOT_FOR_CLIENT, PRM_ERR_NOT_FOR_CLIENT_NO_AUTH, PRM_ERR_UNKNOWN_PARAM, prm_find(), prm_get_next_param_value(), sysprm_assign_value::prm_id, PRM_TEST_CHANGE_ONLY, PRM_TEST_MODE, PRM_USER_CAN_CHANGE, sysprm_param::static_flag, sysprm_free_assign_values(), sysprm_generate_new_value(), sysprm_get_id(), sysprm_validate_escape_char_parameters(), sysprm_assign_value::value, and sysprm_param::value.
Referenced by db_set_system_parameters().
void xsysprm_change_server_parameters (const SYSPRM_ASSIGN_VALUE * assignments)
Definition at line 8674 of file system_parameter.c.
References sysprm_change_parameter_values().
Referenced by sprm_server_change_parameters(), and sysprm_change_server_parameters().
void xsysprm_dump_server_parameters (FILE * fp)
Definition at line 8761 of file system_parameter.c.
References sysprm_dump_parameters().
Referenced by sprm_server_dump_parameters(), and sysprm_dump_server_parameters().
SYSPRM_ASSIGN_VALUE* xsysprm_get_force_server_parameters (void)
Definition at line 8716 of file system_parameter.c.
References ARG_FILE_LINE, cleanup(), ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), GET_PRM, i, sysprm_assign_value::next, NULL, NUM_PRM, PRM_GET_FROM_SERVER, sysprm_assign_value::prm_id, sysprm_param::static_flag, sysprm_free_assign_values(), sysprm_set_sysprm_value_from_parameter(), and sysprm_assign_value::value.
Referenced by sprm_server_get_force_parameters().
void xsysprm_obtain_server_parameters (SYSPRM_ASSIGN_VALUE * prm_values)
Definition at line 8690 of file system_parameter.c.
References GET_PRM, sysprm_assign_value::next, NULL, sysprm_assign_value::prm_id, PRM_IS_FOR_CLIENT, PRM_IS_FOR_SERVER, PRM_IS_GET_SERVER, sysprm_param::static_flag, sysprm_set_sysprm_value_from_parameter(), and sysprm_assign_value::value.
Referenced by sprm_server_obtain_parameters(), and sysprm_obtain_server_parameters().