CUBRID Engine: src/base/system_parameter.c File Reference
system_parameter.c File Reference
#include "config.h"
#include <stdio.h>
#include <stdlib.h>
#include <limits.h>
#include <float.h>
#include <errno.h>
#include <time.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/param.h>
#include <assert.h>
#include <ctype.h>
#include "porting.h"
#include "chartype.h"
#include "misc_string.h"
#include "error_manager.h"
#include "storage_common.h"
#include "system_parameter.h"
#include "util_func.h"
#include "log_comm.h"
#include "memory_alloc.h"
#include "object_representation.h"
#include "environment_variable.h"
#include "intl_support.h"
#include "message_catalog.h"
#include "language_support.h"
#include "connection_defs.h"
#include "ini_parser.h"
#include "tcp.h"
#include "heartbeat.h"
#include "log_applier.h"
#include "utility.h"
#include "tz_support.h"
#include "perf_monitor.h"
#include "fault_injection.h"
#include "tde.h"
Classes
struct sysprm_param
struct keyval
Macros
#define strlen(s1) ((int) strlen(s1))
#define ER_LOG_FILE_DIR "server"
#define PRM_NAME_ER_LOG_DEBUG "er_log_debug"
#define PRM_NAME_ER_BTREE_DEBUG "er_btree_debug"
#define PRM_NAME_ER_LOG_LEVEL "error_log_level"
#define PRM_NAME_ER_LOG_WARNING "error_log_warning"
#define PRM_NAME_ER_EXIT_ASK "inquire_on_exit"
#define PRM_NAME_ER_LOG_SIZE "error_log_size"
#define PRM_NAME_ER_LOG_FILE "error_log"
#define PRM_NAME_IO_LOCKF_ENABLE "file_lock"
#define PRM_NAME_SR_NBUFFERS "sort_buffer_pages"
#define PRM_NAME_SORT_BUFFER_SIZE "sort_buffer_size"
#define PRM_NAME_PB_NBUFFERS "data_buffer_pages"
#define PRM_NAME_PAGE_BUFFER_SIZE "data_buffer_size"
#define PRM_NAME_PB_BUFFER_FLUSH_RATIO "data_buffer_flush_ratio"
#define PRM_NAME_HF_UNFILL_FACTOR "unfill_factor"
#define PRM_NAME_HF_MAX_BESTSPACE_ENTRIES "max_bestspace_entries"
#define PRM_NAME_BT_UNFILL_FACTOR "index_unfill_factor"
#define PRM_NAME_BT_OID_NBUFFERS "index_scan_oid_buffer_pages"
#define PRM_NAME_BT_OID_BUFFER_SIZE "index_scan_oid_buffer_size"
#define PRM_NAME_BT_INDEX_SCAN_OID_ORDER "index_scan_in_oid_order"
#define PRM_NAME_BOSR_MAXTMP_PAGES "temp_file_max_size_in_pages"
#define PRM_NAME_LK_TIMEOUT_MESSAGE_DUMP_LEVEL "lock_timeout_message_type"
#define PRM_NAME_LK_ESCALATION_AT "lock_escalation"
#define PRM_NAME_LK_ROLLBACK_ON_LOCK_ESCALATION "rollback_on_lock_escalation"
#define PRM_NAME_LK_TIMEOUT_SECS "lock_timeout_in_secs"
#define PRM_NAME_LK_TIMEOUT "lock_timeout"
#define PRM_NAME_LK_RUN_DEADLOCK_INTERVAL "deadlock_detection_interval_in_secs"
#define PRM_NAME_LOG_NBUFFERS "log_buffer_pages"
#define PRM_NAME_LOG_BUFFER_SIZE "log_buffer_size"
#define PRM_NAME_LOG_CHECKPOINT_NPAGES "checkpoint_every_npages"
#define PRM_NAME_LOG_CHECKPOINT_SIZE "checkpoint_every_size"
#define PRM_NAME_LOG_CHECKPOINT_INTERVAL_SECS "checkpoint_interval_in_mins"
#define PRM_NAME_LOG_CHECKPOINT_INTERVAL "checkpoint_interval"
#define PRM_NAME_LOG_CHECKPOINT_SLEEP_MSECS "checkpoint_sleep_msecs"
#define PRM_NAME_LOG_BACKGROUND_ARCHIVING "background_archiving"
#define PRM_NAME_LOG_ISOLATION_LEVEL "isolation_level"
#define PRM_NAME_LOG_MEDIA_FAILURE_SUPPORT "media_failure_support"
#define PRM_NAME_LOG_SWEEP_CLEAN "log_file_sweep_clean"
#define PRM_NAME_COMMIT_ON_SHUTDOWN "commit_on_shutdown"
#define PRM_NAME_SHUTDOWN_WAIT_TIME_IN_SECS "shutdown_wait_time_in_secs"
#define PRM_NAME_CSQL_AUTO_COMMIT "csql_auto_commit"
#define PRM_NAME_WS_HASHTABLE_SIZE "initial_workspace_table_size"
#define PRM_NAME_WS_MEMORY_REPORT "workspace_memory_report"
#define PRM_NAME_GC_ENABLE "garbage_collection"
#define PRM_NAME_TCP_PORT_ID "cubrid_port_id"
#define PRM_NAME_TCP_CONNECTION_TIMEOUT "connection_timeout"
#define PRM_NAME_OPTIMIZATION_LEVEL "optimization_level"
#define PRM_NAME_QO_DUMP "qo_dump"
#define PRM_NAME_CSS_MAX_CLIENTS "max_clients"
#define PRM_NAME_THREAD_STACKSIZE "thread_stacksize"
#define PRM_NAME_CFG_DB_HOSTS "db_hosts"
#define PRM_NAME_RESET_TR_PARSER "reset_tr_parser_interval"
#define PRM_NAME_IO_BACKUP_NBUFFERS "backup_buffer_pages"
#define PRM_NAME_IO_BACKUP_MAX_VOLUME_SIZE "backup_volume_max_size_bytes"
#define PRM_NAME_IO_BACKUP_SLEEP_MSECS "backup_sleep_msecs"
#define PRM_NAME_MAX_PAGES_IN_TEMP_FILE_CACHE "max_pages_in_temp_file_cache"
#define PRM_NAME_MAX_ENTRIES_IN_TEMP_FILE_CACHE "max_entries_in_temp_file_cache"
#define PRM_NAME_PTHREAD_SCOPE_PROCESS "pthread_scope_process"
#define PRM_NAME_TEMP_MEM_BUFFER_PAGES "temp_file_memory_size_in_pages"
#define PRM_NAME_INDEX_SCAN_KEY_BUFFER_PAGES "index_scan_key_buffer_pages"
#define PRM_NAME_INDEX_SCAN_KEY_BUFFER_SIZE "index_scan_key_buffer_size"
#define PRM_NAME_DONT_REUSE_HEAP_FILE "dont_reuse_heap_file"
#define PRM_NAME_INSERT_MODE "insert_execution_mode"
#define PRM_NAME_LK_MAX_SCANID_BIT "max_index_scan_count"
#define PRM_NAME_HOSTVAR_LATE_BINDING "hostvar_late_binding"
#define PRM_NAME_ENABLE_HISTO "communication_histogram"
#define PRM_NAME_MUTEX_BUSY_WAITING_CNT "mutex_busy_waiting_cnt"
#define PRM_NAME_PB_NUM_LRU_CHAINS "num_LRU_chains"
#define PRM_NAME_PAGE_BG_FLUSH_INTERVAL_MSECS "page_flush_interval_in_msecs"
#define PRM_NAME_PAGE_BG_FLUSH_INTERVAL "page_flush_interval"
#define PRM_NAME_ADAPTIVE_FLUSH_CONTROL "adaptive_flush_control"
#define PRM_NAME_MAX_FLUSH_PAGES_PER_SECOND "max_flush_pages_per_second"
#define PRM_NAME_MAX_FLUSH_SIZE_PER_SECOND "max_flush_size_per_second"
#define PRM_NAME_PB_SYNC_ON_NFLUSH "sync_on_nflush"
#define PRM_NAME_PB_SYNC_ON_FLUSH_SIZE "sync_on_flush_size"
#define PRM_NAME_PB_DEBUG_PAGE_VALIDATION_LEVEL "page_validation_level"
#define PRM_NAME_ORACLE_STYLE_OUTERJOIN "oracle_style_outerjoin"
#define PRM_NAME_COMPAT_MODE "compat_mode"
#define PRM_NAME_ANSI_QUOTES "ansi_quotes"
#define PRM_NAME_DEFAULT_WEEK_FORMAT "default_week_format"
#define PRM_NAME_TEST_MODE "test_mode"
#define PRM_NAME_ONLY_FULL_GROUP_BY "only_full_group_by"
#define PRM_NAME_PIPES_AS_CONCAT "pipes_as_concat"
#define PRM_NAME_MYSQL_TRIGGER_CORRELATION_NAMES "mysql_trigger_correlation_names"
#define PRM_NAME_REQUIRE_LIKE_ESCAPE_CHARACTER "require_like_escape_character"
#define PRM_NAME_NO_BACKSLASH_ESCAPES "no_backslash_escapes"
#define PRM_NAME_GROUP_CONCAT_MAX_LEN "group_concat_max_len"
#define PRM_NAME_STRING_MAX_SIZE_BYTES "string_max_size_bytes"
#define PRM_NAME_ADD_COLUMN_UPDATE_HARD_DEFAULT "add_column_update_hard_default"
#define PRM_NAME_RETURN_NULL_ON_FUNCTION_ERRORS "return_null_on_function_errors"
#define PRM_NAME_PLUS_AS_CONCAT "plus_as_concat"
#define PRM_NAME_ALTER_TABLE_CHANGE_TYPE_STRICT "alter_table_change_type_strict"
#define PRM_NAME_COMPACTDB_PAGE_RECLAIM_ONLY "compactdb_page_reclaim_only"
#define PRM_NAME_LIKE_TERM_SELECTIVITY "like_term_selectivity"
#define PRM_NAME_MAX_OUTER_CARD_OF_IDXJOIN "max_outer_card_of_idxjoin"
#define PRM_NAME_ORACLE_STYLE_EMPTY_STRING "oracle_style_empty_string"
#define PRM_NAME_SUPPRESS_FSYNC "suppress_fsync"
#define PRM_NAME_CALL_STACK_DUMP_ON_ERROR "call_stack_dump_on_error"
#define PRM_NAME_CALL_STACK_DUMP_ACTIVATION "call_stack_dump_activation_list"
#define PRM_NAME_CALL_STACK_DUMP_DEACTIVATION "call_stack_dump_deactivation_list"
#define PRM_NAME_COMPAT_NUMERIC_DIVISION_SCALE "compat_numeric_division_scale"
#define PRM_NAME_DBFILES_PROTECT "dbfiles_protect"
#define PRM_NAME_AUTO_RESTART_SERVER "auto_restart_server"
#define PRM_NAME_XASL_CACHE_MAX_ENTRIES "max_plan_cache_entries"
#define PRM_NAME_XASL_CACHE_MAX_CLONES "max_plan_cache_clones"
#define PRM_NAME_XASL_CACHE_TIMEOUT "plan_cache_timeout"
#define PRM_NAME_XASL_CACHE_LOGGING "plan_cache_logging"
#define PRM_NAME_FILTER_PRED_MAX_CACHE_ENTRIES "max_filter_pred_cache_entries"
#define PRM_NAME_FILTER_PRED_MAX_CACHE_CLONES "max_filter_pred_cache_clones"
#define PRM_NAME_LIST_QUERY_CACHE_MODE "query_cache_mode"
#define PRM_NAME_LIST_MAX_QUERY_CACHE_ENTRIES "max_query_cache_entries"
#define PRM_NAME_LIST_MAX_QUERY_CACHE_PAGES "query_cache_size_in_pages"
#define PRM_NAME_USE_ORDERBY_SORT_LIMIT "use_orderby_sort_limit"
#define PRM_NAME_REPLICATION_MODE "replication"
#define PRM_NAME_HA_MODE "ha_mode"
#define PRM_NAME_HA_MODE_FOR_SA_UTILS_ONLY "ha_mode_for_sa_utils_only"
#define PRM_NAME_HA_SERVER_STATE "ha_server_state"
#define PRM_NAME_HA_LOG_APPLIER_STATE "ha_log_applier_state"
#define PRM_NAME_HA_NODE_LIST "ha_node_list"
#define PRM_NAME_HA_REPLICA_LIST "ha_replica_list"
#define PRM_NAME_HA_DB_LIST "ha_db_list"
#define PRM_NAME_HA_COPY_LOG_BASE "ha_copy_log_base"
#define PRM_NAME_HA_COPY_SYNC_MODE "ha_copy_sync_mode"
#define PRM_NAME_HA_APPLY_MAX_MEM_SIZE "ha_apply_max_mem_size"
#define PRM_NAME_HA_PORT_ID "ha_port_id"
#define PRM_NAME_HA_INIT_TIMER_IN_MSECS "ha_init_timer_in_msec"
#define PRM_NAME_HA_HEARTBEAT_INTERVAL_IN_MSECS "ha_heartbeat_interval_in_msecs"
#define PRM_NAME_HA_CALC_SCORE_INTERVAL_IN_MSECS "ha_calc_score_interval_in_msecs"
#define PRM_NAME_HA_FAILOVER_WAIT_TIME_IN_MSECS "ha_failover_wait_time_in_msecs"
#define PRM_NAME_HA_PROCESS_START_CONFIRM_INTERVAL_IN_MSECS "ha_process_start_confirm_interval_in_msecs"
#define PRM_NAME_HA_PROCESS_DEREG_CONFIRM_INTERVAL_IN_MSECS "ha_process_dereg_confirm_interval_in_msecs"
#define PRM_NAME_HA_MAX_PROCESS_START_CONFIRM "ha_max_process_start_confirm"
#define PRM_NAME_HA_MAX_PROCESS_DEREG_CONFIRM "ha_max_process_dereg_confirm"
#define PRM_NAME_HA_UNACCEPTABLE_PROC_RESTART_TIMEDIFF "ha_unacceptable_proc_restart_timediff"
#define PRM_NAME_HA_CHANGEMODE_INTERVAL_IN_MSEC "ha_changemode_interval_in_msecs"
#define PRM_NAME_HA_MAX_HEARTBEAT_GAP "ha_max_heartbeat_gap"
#define PRM_NAME_HA_PING_HOSTS "ha_ping_hosts"
#define PRM_NAME_HA_APPLYLOGDB_RETRY_ERROR_LIST "ha_applylogdb_retry_error_list"
#define PRM_NAME_HA_APPLYLOGDB_IGNORE_ERROR_LIST "ha_applylogdb_ignore_error_list"
#define PRM_NAME_HA_APPLYLOGDB_LOG_WAIT_TIME_IN_SECS "ha_applylogdb_log_wait_time_in_secs"
#define PRM_NAME_HA_SQL_LOGGING "ha_enable_sql_logging"
#define PRM_NAME_HA_SQL_LOG_MAX_SIZE_IN_MB "ha_sql_log_max_size_in_mbytes"
#define PRM_NAME_HA_COPY_LOG_MAX_ARCHIVES "ha_copy_log_max_archives"
#define PRM_NAME_HA_COPY_LOG_TIMEOUT "ha_copy_log_timeout"
#define PRM_NAME_HA_REPLICA_DELAY "ha_replica_delay"
#define PRM_NAME_HA_REPLICA_TIME_BOUND "ha_replica_time_bound"
#define PRM_NAME_HA_DELAY_LIMIT "ha_delay_limit"
#define PRM_NAME_HA_DELAY_LIMIT_DELTA "ha_delay_limit_delta"
#define PRM_NAME_HA_APPLYLOGDB_MAX_COMMIT_INTERVAL_IN_MSECS "ha_applylogdb_max_commit_interval_in_msecs"
#define PRM_NAME_HA_APPLYLOGDB_MAX_COMMIT_INTERVAL "ha_applylogdb_max_commit_interval"
#define PRM_NAME_HA_CHECK_DISK_FAILURE_INTERVAL_IN_SECS "ha_check_disk_failure_interval"
#define PRM_NAME_JAVA_STORED_PROCEDURE "java_stored_procedure"
#define PRM_NAME_JAVA_STORED_PROCEDURE_PORT "java_stored_procedure_port"
#define PRM_NAME_JAVA_STORED_PROCEDURE_JVM_OPTIONS "java_stored_procedure_jvm_options"
#define PRM_NAME_JAVA_STORED_PROCEDURE_DEBUG "java_stored_procedure_debug"
#define PRM_NAME_JAVA_STORED_PROCEDURE_RESERVE_01 "java_stored_procedure_reserve_01"
#define PRM_NAME_ALLOW_TRUNCATED_STRING "allow_truncated_string"
#define PRM_NAME_COMPAT_PRIMARY_KEY "compat_primary_key"
#define PRM_NAME_INTL_MBS_SUPPORT "intl_mbs_support"
#define PRM_NAME_LOG_HEADER_FLUSH_INTERVAL "log_header_flush_interval_in_secs"
#define PRM_NAME_LOG_ASYNC_COMMIT "async_commit"
#define PRM_NAME_LOG_GROUP_COMMIT_INTERVAL_MSECS "group_commit_interval_in_msecs"
#define PRM_NAME_LOG_BG_FLUSH_INTERVAL_MSECS "log_flush_interval_in_msecs"
#define PRM_NAME_LOG_BG_FLUSH_NUM_PAGES "log_flush_every_npages"
#define PRM_NAME_LOG_COMPRESS "log_compress"
#define PRM_NAME_BLOCK_NOWHERE_STATEMENT "block_nowhere_statement"
#define PRM_NAME_BLOCK_DDL_STATEMENT "block_ddl_statement"
#define PRM_NAME_SINGLE_BYTE_COMPARE "single_byte_compare"
#define PRM_NAME_CSQL_HISTORY_NUM "csql_history_num"
#define PRM_NAME_LOG_TRACE_DEBUG "log_trace_debug"
#define PRM_NAME_DL_FORK "dl_fork"
#define PRM_NAME_ER_PRODUCTION_MODE "error_log_production_mode"
#define PRM_NAME_ER_STOP_ON_ERROR "stop_on_error"
#define PRM_NAME_TCP_RCVBUF_SIZE "tcp_rcvbuf_size"
#define PRM_NAME_TCP_SNDBUF_SIZE "tcp_sndbuf_size"
#define PRM_NAME_TCP_NODELAY "tcp_nodelay"
#define PRM_NAME_TCP_KEEPALIVE "tcp_keepalive"
#define PRM_NAME_CSQL_SINGLE_LINE_MODE "csql_single_line_mode"
#define PRM_NAME_XASL_DEBUG_DUMP "xasl_debug_dump"
#define PRM_NAME_LOG_MAX_ARCHIVES "log_max_archives"
#define PRM_NAME_FORCE_REMOVE_LOG_ARCHIVES "force_remove_log_archives"
#define PRM_NAME_REMOVE_LOG_ARCHIVES_INTERVAL "remove_log_archive_interval_in_secs"
#define PRM_NAME_LOG_NO_LOGGING "no_logging"
#define PRM_NAME_UNLOADDB_IGNORE_ERROR "unload_ignore_error"
#define PRM_NAME_UNLOADDB_LOCK_TIMEOUT "unload_lock_timeout"
#define PRM_NAME_LOADDB_FLUSH_INTERVAL "load_flush_interval"
#define PRM_NAME_IO_TEMP_VOLUME_PATH "temp_volume_path"
#define PRM_NAME_TDE_KEYS_FILE_PATH "tde_keys_file_path"
#define PRM_NAME_IO_VOLUME_EXT_PATH "volume_extension_path"
#define PRM_NAME_UNIQUE_ERROR_KEY_VALUE "print_key_value_on_unique_error"
#define PRM_NAME_USE_SYSTEM_MALLOC "use_system_malloc"
#define PRM_NAME_EVENT_HANDLER "event_handler"
#define PRM_NAME_EVENT_ACTIVATION "event_activation_list"
#define PRM_NAME_READ_ONLY_MODE "read_only"
#define PRM_NAME_MNT_WAITING_THREAD "monitor_waiting_thread"
#define PRM_NAME_MNT_STATS_THRESHOLD "monitor_stats_threshold"
#define PRM_NAME_SERVICE_SERVICE_LIST "service::service"
#define PRM_NAME_SERVICE_SERVER_LIST "service::server"
#define PRM_NAME_SESSION_STATE_TIMEOUT "session_state_timeout"
#define PRM_NAME_MULTI_RANGE_OPT_LIMIT "multi_range_optimization_limit"
#define PRM_NAME_ACCESS_IP_CONTROL "access_ip_control"
#define PRM_NAME_ACCESS_IP_CONTROL_FILE "access_ip_control_file"
#define PRM_NAME_DB_VOLUME_SIZE "db_volume_size"
#define PRM_NAME_LOG_VOLUME_SIZE "log_volume_size"
#define PRM_NAME_INTL_NUMBER_LANG "intl_number_lang"
#define PRM_NAME_INTL_DATE_LANG "intl_date_lang"
#define PRM_NAME_UNICODE_INPUT_NORMALIZATION "unicode_input_normalization"
#define PRM_NAME_UNICODE_OUTPUT_NORMALIZATION "unicode_output_normalization"
#define PRM_NAME_INTL_CHECK_INPUT_STRING "intl_check_input_string"
#define PRM_NAME_CHECK_PEER_ALIVE "check_peer_alive"
#define PRM_NAME_SQL_TRACE_EXECUTION_PLAN "sql_trace_execution_plan"
#define PRM_NAME_SQL_TRACE_SLOW_MSECS "sql_trace_slow_msecs"
#define PRM_NAME_SQL_TRACE_SLOW "sql_trace_slow"
#define PRM_NAME_LOG_TRACE_FLUSH_TIME "log_trace_flush_time"
#define PRM_NAME_INTL_COLLATION "intl_collation"
#define PRM_NAME_GENERIC_VOL_PREALLOC_SIZE "generic_vol_prealloc_size"
#define PRM_NAME_SORT_LIMIT_MAX_COUNT "sort_limit_max_count"
#define PRM_NAME_SQL_TRACE_IOREADS "sql_trace_ioread_pages"
#define PRM_NAME_QUERY_TRACE "query_trace"
#define PRM_NAME_QUERY_TRACE_FORMAT "query_trace_format"
#define PRM_NAME_MAX_RECURSION_SQL_DEPTH "max_recursion_sql_depth"
#define PRM_NAME_UPDATE_USE_ATTRIBUTE_REFERENCES "update_use_attribute_references"
#define PRM_NAME_PB_AOUT_RATIO "data_aout_ratio"
#define PRM_NAME_MAX_AGG_HASH_SIZE "max_agg_hash_size"
#define PRM_NAME_AGG_HASH_RESPECT_ORDER "agg_hash_respect_order"
#define PRM_NAME_USE_BTREE_FENCE_KEY "use_btree_fence_key"
#define PRM_NAME_OPTIMIZER_ENABLE_MERGE_JOIN "optimizer_enable_merge_join"
#define PRM_NAME_MAX_HASH_LIST_SCAN_SIZE "max_hash_list_scan_size"
#define PRM_NAME_OPTIMIZER_RESERVE_02 "optimizer_reserve_02"
#define PRM_NAME_OPTIMIZER_RESERVE_03 "optimizer_reserve_03"
#define PRM_NAME_OPTIMIZER_RESERVE_04 "optimizer_reserve_04"
#define PRM_NAME_OPTIMIZER_RESERVE_05 "optimizer_reserve_05"
#define PRM_NAME_OPTIMIZER_RESERVE_06 "optimizer_reserve_06"
#define PRM_NAME_OPTIMIZER_RESERVE_07 "optimizer_reserve_07"
#define PRM_NAME_OPTIMIZER_RESERVE_08 "optimizer_reserve_08"
#define PRM_NAME_OPTIMIZER_RESERVE_09 "optimizer_reserve_09"
#define PRM_NAME_OPTIMIZER_RESERVE_10 "optimizer_reserve_10"
#define PRM_NAME_OPTIMIZER_RESERVE_11 "optimizer_reserve_11"
#define PRM_NAME_OPTIMIZER_RESERVE_12 "optimizer_reserve_12"
#define PRM_NAME_OPTIMIZER_RESERVE_13 "optimizer_reserve_13"
#define PRM_NAME_OPTIMIZER_RESERVE_14 "optimizer_reserve_14"
#define PRM_NAME_OPTIMIZER_RESERVE_15 "optimizer_reserve_15"
#define PRM_NAME_OPTIMIZER_RESERVE_16 "optimizer_reserve_16"
#define PRM_NAME_OPTIMIZER_RESERVE_17 "optimizer_reserve_17"
#define PRM_NAME_OPTIMIZER_RESERVE_18 "optimizer_reserve_18"
#define PRM_NAME_OPTIMIZER_RESERVE_19 "optimizer_reserve_19"
#define PRM_NAME_OPTIMIZER_RESERVE_20 "optimizer_reserve_20"
#define PRM_NAME_HA_REPL_ENABLE_SERVER_SIDE_UPDATE "ha_repl_enable_server_side_update"
#define PRM_NAME_PB_LRU_HOT_RATIO "lru_hot_ratio"
#define PRM_NAME_PB_LRU_BUFFER_RATIO "lru_buffer_ratio"
#define PRM_NAME_VACUUM_MASTER_WAKEUP_INTERVAL "vacuum_master_interval_in_msecs"
#define PRM_NAME_VACUUM_LOG_BLOCK_PAGES "vacuum_log_block_pages"
#define PRM_NAME_VACUUM_WORKER_COUNT "vacuum_worker_count"
#define PRM_NAME_DISABLE_VACUUM "vacuum_disable"
#define PRM_NAME_SA_MODE_AUTO_VACUUM "sa_mode_auto_vacuum"
#define PRM_NAME_ER_LOG_VACUUM "er_log_vacuum"
#define PRM_NAME_LOG_BTREE_OPS "log_btree_operations"
#define PRM_NAME_OBJECT_PRINT_FORMAT_OID "print_object_as_oid"
#define PRM_NAME_TIMEZONE "timezone"
#define PRM_NAME_SERVER_TIMEZONE "server_timezone"
#define PRM_NAME_TZ_LEAP_SECOND_SUPPORT "tz_leap_second_support"
#define PRM_NAME_OPTIMIZER_ENABLE_AGGREGATE_OPTIMIZATION "optimizer_enable_aggregate_optimization"
#define PRM_NAME_VACUUM_PREFETCH_LOG_NBUFFERS "vacuum_prefetch_log_pages"
#define PRM_NAME_VACUUM_PREFETCH_LOG_BUFFER_SIZE "vacuum_prefetch_log_buffer_size"
#define PRM_NAME_VACUUM_PREFETCH_LOG_MODE "vacuum_prefetch_log_mode"
#define PRM_NAME_PB_NEIGHBOR_FLUSH_NONDIRTY "data_buffer_neighbor_flush_nondirty"
#define PRM_NAME_PB_NEIGHBOR_FLUSH_PAGES "data_buffer_neighbor_flush_pages"
#define PRM_NAME_FAULT_INJECTION_IDS "fault_injection_ids"
#define PRM_NAME_FAULT_INJECTION_TEST "fault_injection_test"
#define PRM_NAME_FAULT_INJECTION_ACTION_PREFER_ABORT_TO_EXIT "fault_injection_action_prefer_abort_to_exit"
#define PRM_NAME_HA_REPL_FILTER_TYPE "ha_repl_filter_type"
#define PRM_NAME_HA_REPL_FILTER_FILE "ha_repl_filter_file"
#define PRM_NAME_COMPENSATE_DEBUG "compensate_debug"
#define PRM_NAME_POSTPONE_DEBUG "postpone_debug"
#define PRM_NAME_CLIENT_CLASS_CACHE_DEBUG "client_class_cache_debug"
#define PRM_NAME_EXAMINE_CLIENT_CACHED_LOCKS "examine_client_cached_locks"
#define PRM_NAME_PB_SEQUENTIAL_VICTIM_FLUSH "data_buffer_sequential_victim_flush"
#define PRM_NAME_LOG_UNIQUE_STATS "log_unique_stats"
#define PRM_NAME_LOGPB_LOGGING_DEBUG "logpb_logging_debug"
#define PRM_NAME_FORCE_RESTART_TO_SKIP_RECOVERY "force_restart_to_skip_recovery"
#define PRM_NAME_ENABLE_STRING_COMPRESSION "enable_string_compression"
#define PRM_NAME_XASL_CACHE_TIME_THRESHOLD_IN_MINUTES "xasl_cache_time_threshold_in_minutes"
#define PRM_NAME_EXTENDED_STATISTICS_ACTIVATION "extended_statistics_activation"
#define PRM_NAME_DISK_LOGGING "disk_logging_debug"
#define PRM_NAME_FILE_LOGGING "file_logging_debug"
#define PRM_NAME_PB_NUM_PRIVATE_CHAINS "num_private_chains"
#define PRM_NAME_PB_MONITOR_LOCKS "pgbuf_monitor_locks"
#define PRM_NAME_PB_MAX_DEPTH_OF_SEARCHING_FOR_VICTIMS_IN_LRU_LIST "max_depth_of_searching_for_victims_in_lru_list"
#define PRM_NAME_CTE_MAX_RECURSIONS "cte_max_recursions"
#define PRM_NAME_DWB_SIZE "double_write_buffer_size"
#define PRM_NAME_DWB_BLOCKS "double_write_buffer_blocks"
#define PRM_NAME_ENABLE_DWB_FLUSH_THREAD "double_write_buffer_enable_flush_thread"
#define PRM_NAME_DWB_LOGGING "double_write_buffer_logging"
#define PRM_NAME_JSON_LOG_ALLOCATIONS "json_log_allocations"
#define PRM_NAME_JSON_MAX_ARRAY_IDX "json_max_array_idx"
#define PRM_NAME_CONNECTION_LOGGING "connection_logging"
#define PRM_NAME_THREAD_LOGGING_FLAG "thread_logging_flag"
#define PRM_NAME_LOG_QUERY_LISTS "log_query_lists"
#define PRM_NAME_THREAD_CONNECTION_POOLING "thread_connection_pooling"
#define PRM_NAME_THREAD_CONNECTION_TIMEOUT_SECONDS "thread_connection_timeout_seconds"
#define PRM_NAME_THREAD_WORKER_POOLING "thread_worker_pooling"
#define PRM_NAME_THREAD_WORKER_TIMEOUT_SECONDS "thread_worker_timeout_seconds"
#define PRM_NAME_DATA_FILE_ADVISE "data_file_os_advise"
#define PRM_NAME_DEBUG_LOG_ARCHIVES "debug_log_archives"
#define PRM_NAME_DEBUG_ES "debug_external_storage"
#define PRM_NAME_DEBUG_BESTSPACE "debug_heap_bestspace"
#define PRM_NAME_DEBUG_LOG_WRITER "debug_log_writer"
#define PRM_NAME_DEBUG_AUTOCOMMIT "debug_autocommit"
#define PRM_NAME_DEBUG_REPLICATION_DATA "debug_replication_data"
#define PRM_NAME_TRACK_REQUESTS "track_client_requests"
#define PRM_NAME_LOG_PGBUF_VICTIM_FLUSH "log_pgbuf_victim_flush"
#define PRM_NAME_LOG_CHKPT_DETAILED "detailed_checkpoint_logging"
#define PRM_NAME_IB_TASK_MEMSIZE "index_load_task_memsize"
#define PRM_NAME_STATS_ON "stats_on"
#define PRM_NAME_LOADDB_WORKER_COUNT "loaddb_worker_count"
#define PRM_NAME_PERF_TEST_MODE "perf_test_mode"
#define PRM_NAME_REPR_CACHE_LOG "er_log_repr_cache"
#define PRM_NAME_ENABLE_NEW_LFHASH "new_lfhash"
#define PRM_NAME_HEAP_INFO_CACHE_LOGGING "heap_info_cache_logging"
#define PRM_NAME_TDE_DEFAULT_ALGORITHM "tde_default_algorithm"
#define PRM_NAME_GENERAL_RESERVE_01 "general_reserve_01"
#define PRM_NAME_TB_DEFAULT_REUSE_OID "create_table_reuseoid"
#define PRM_NAME_USE_STAT_ESTIMATION "use_stat_estimation"
#define PRM_NAME_IGNORE_TRAILING_SPACE "ignore_trailing_space"
#define PRM_NAME_DDL_AUDIT_LOG "ddl_audit_log"
#define PRM_NAME_DDL_AUDIT_LOG_SIZE "ddl_audit_log_size"
#define PRM_VALUE_DEFAULT "DEFAULT"
#define PRM_VALUE_MAX "MAX"
#define PRM_VALUE_MIN "MIN"
#define PRM_EMPTY_FLAG 0x00000000 /* empty flag */
#define PRM_USER_CHANGE 0x00000001 /* user can change, not implemented */
#define PRM_FOR_CLIENT 0x00000002 /* is for client parameter */
#define PRM_FOR_SERVER 0x00000004 /* is for server parameter */
#define PRM_HIDDEN 0x00000008 /* is hidden */
#define PRM_RELOADABLE 0x00000010 /* is reloadable */
#define PRM_COMPOUND 0x00000020 /* sets the value of several others */
#define PRM_TEST_CHANGE 0x00000040 /* can only be changed in the test mode */
#define PRM_FOR_HA 0x00000080 /* is for heartbeat */
#define PRM_FOR_SESSION
#define PRM_FORCE_SERVER 0x00000200 /* client should get value from server */
#define PRM_FOR_QRY_STRING
#define PRM_CLIENT_SESSION
#define PRM_SIZE_UNIT 0x00001000 /* has size unit interface */
#define PRM_TIME_UNIT 0x00002000 /* has time unit interface */
#define PRM_DIFFER_UNIT 0x00004000 /* parameter unit need to be changed */
#define PRM_FOR_HA_CONTEXT 0x00008000 /* should be replicated into HA log applier */
#define PRM_GET_SERVER
#define PRM_DEPRECATED 0x40000000 /* is deprecated */
#define PRM_OBSOLETED 0x80000000 /* is obsoleted */
#define PRM_SET 0x00000001 /* has been set */
#define PRM_ALLOCATED 0x00000002 /* storage has been malloc'd */
#define PRM_DEFAULT_USED 0x00000004 /* Default value has been used */
#define PRM_DIFFERENT
#define PRM_IS_STRING(x) ((x)->datatype == PRM_STRING)
#define PRM_IS_INTEGER(x) ((x)->datatype == PRM_INTEGER)
#define PRM_IS_FLOAT(x) ((x)->datatype == PRM_FLOAT)
#define PRM_IS_BOOLEAN(x) ((x)->datatype == PRM_BOOLEAN)
#define PRM_IS_KEYWORD(x) ((x)->datatype == PRM_KEYWORD)
#define PRM_IS_INTEGER_LIST(x) ((x)->datatype == PRM_INTEGER_LIST)
#define PRM_IS_BIGINT(x) ((x)->datatype == PRM_BIGINT)
#define PRM_USER_CAN_CHANGE(x) (x & PRM_USER_CHANGE)
#define PRM_IS_FOR_CLIENT(x) (x & PRM_FOR_CLIENT)
#define PRM_IS_FOR_SERVER(x) (x & PRM_FOR_SERVER)
#define PRM_IS_HIDDEN(x) (x & PRM_HIDDEN)
#define PRM_IS_RELOADABLE(x) (x & PRM_RELOADABLE)
#define PRM_IS_COMPOUND(x) (x & PRM_COMPOUND)
#define PRM_TEST_CHANGE_ONLY(x) (x & PRM_TEST_CHANGE)
#define PRM_IS_FOR_HA(x) (x & PRM_FOR_HA)
#define PRM_IS_FOR_SESSION(x) (x & PRM_FOR_SESSION)
#define PRM_GET_FROM_SERVER(x) (x & PRM_FORCE_SERVER)
#define PRM_IS_FOR_QRY_STRING(x) (x & PRM_FOR_QRY_STRING)
#define PRM_CLIENT_SESSION_ONLY(x) (x & PRM_CLIENT_SESSION)
#define PRM_HAS_SIZE_UNIT(x) (x & PRM_SIZE_UNIT)
#define PRM_HAS_TIME_UNIT(x) (x & PRM_TIME_UNIT)
#define PRM_DIFFERENT_UNIT(x) (x & PRM_DIFFER_UNIT)
#define PRM_IS_FOR_HA_CONTEXT(x) (x & PRM_FOR_HA_CONTEXT)
#define PRM_IS_GET_SERVER(x) (x & PRM_GET_SERVER)
#define PRM_IS_DEPRECATED(x) (x & PRM_DEPRECATED)
#define PRM_IS_OBSOLETED(x) (x & PRM_OBSOLETED)
#define PRM_IS_SET(x) (x & PRM_SET)
#define PRM_IS_ALLOCATED(x) (x & PRM_ALLOCATED)
#define PRM_DEFAULT_VAL_USED(x) (x & PRM_DEFAULT_USED)
#define PRM_IS_DIFFERENT(x) (x & PRM_DIFFERENT)
#define PRM_CLEAR_BIT(this, here) (here &= ~this)
#define PRM_SET_BIT(this, here) (here |= this)
#define PRM_GET_INT(x) (*((int *) (x)))
#define PRM_GET_FLOAT(x) (*((float *) (x)))
#define PRM_GET_STRING(x) (*((char **) (x)))
#define PRM_GET_BOOL(x) (*((bool *) (x)))
#define PRM_GET_INTEGER_LIST(x) (*((int **) (x)))
#define PRM_GET_BIGINT(x) (*((UINT64 *) (x)))
#define PRM_ADJUST_FOR_SET_BIGINT_TO_INTEGER(prm, out_val, in_val, err)
#define PRM_ADJUST_FOR_SET_BIGINT_TO_FLOAT(prm, out_val, in_val, err)
#define PRM_ADJUST_FOR_SET_INTEGER_TO_INTEGER(prm, out_val, in_val, err)
#define PRM_ADJUST_FOR_SET_FLOAT_TO_FLOAT(prm, out_val, in_val, err)
#define PRM_ADJUST_FOR_SET_BIGINT_TO_BIGINT(prm, out_val, in_val, err)
#define PRM_ADJUST_FOR_GET_INTEGER_TO_BIGINT(prm, out_val, in_val, err)
#define PRM_ADJUST_FOR_GET_FLOAT_TO_BIGINT(prm, out_val, in_val, err)
#define PRM_ADJUST_FOR_GET_INTEGER_TO_INTEGER(prm, out_val, in_val, err)
#define PRM_ADJUST_FOR_GET_FLOAT_TO_FLOAT(prm, out_val, in_val, err)
#define PRM_ADJUST_FOR_GET_BIGINT_TO_BIGINT(prm, out_val, in_val, err)
#define PRM_DEFAULT_BUFFER_SIZE 256
#define LOGPB_BUFFER_NPAGES_LOWER 128
#define CSS_MAX_CLIENT_COUNT 4000
#define VACUUM_LOG_BLOCK_PAGES_DEFAULT 0
#define VACUUM_MAX_WORKER_COUNT 0
#define NUM_PRM ((int)(sizeof(prm_Def)/sizeof(prm_Def[0])))
#define PARAM_MSG_FMT(msgid) msgcat_message (MSGCAT_CATALOG_CUBRID, MSGCAT_SET_PARAMETERS, (msgid))
#define GET_PRM(id) (&prm_Def[(id)])
#define GET_PRM_STATIC_FLAG(id) ((GET_PRM (id))->static_flag)
#define GET_PRM_DYNAMIC_FLAG(id) ((GET_PRM (id))->dynamic_flag)
#define GET_PRM_DATATYPE(id) ((GET_PRM (id))->datatype)
#define PRM_PRINT_QRY_STRING(id) (PRM_IS_FOR_QRY_STRING (GET_PRM_STATIC_FLAG (id)))
#define PRM_SERVER_SESSION(id)
#define NUM_SESSION_PRM num_session_parameters
#define MAX_NUM_OF_PRM_FILES_LOADED 10
Typedefs
typedef int(* DUP_PRM_FUNC) (void *, SYSPRM_DATATYPE, void *, SYSPRM_DATATYPE)
typedef struct sysprm_param SYSPRM_PARAM
typedef struct keyval KEYVAL
Enumerations
enum PGBUF_DEBUG_PAGE_VALIDATION_LEVEL {
PGBUF_DEBUG_NO_PAGE_VALIDATION, PGBUF_DEBUG_PAGE_VALIDATION_FETCH, PGBUF_DEBUG_PAGE_VALIDATION_FREE, PGBUF_DEBUG_PAGE_VALIDATION_ALL,
PGBUF_DEBUG_NO_PAGE_VALIDATION, PGBUF_DEBUG_PAGE_VALIDATION_FETCH, PGBUF_DEBUG_PAGE_VALIDATION_FREE, PGBUF_DEBUG_PAGE_VALIDATION_ALL
}
enum PRM_PRINT_MODE { PRM_PRINT_NONE = 0, PRM_PRINT_NAME, PRM_PRINT_ID }
enum PRM_PRINT_VALUE_MODE { PRM_PRINT_CURR_VAL = 0, PRM_PRINT_DEFAULT_VAL }
Functions
static int prm_size_to_io_pages (void *out_val, SYSPRM_DATATYPE out_type, void *in_val, SYSPRM_DATATYPE in_type)
static int prm_io_pages_to_size (void *out_val, SYSPRM_DATATYPE out_type, void *in_val, SYSPRM_DATATYPE in_type)
static int prm_size_to_log_pages (void *out_val, SYSPRM_DATATYPE out_type, void *in_val, SYSPRM_DATATYPE in_type)
static int prm_log_pages_to_size (void *out_val, SYSPRM_DATATYPE out_type, void *in_val, SYSPRM_DATATYPE in_type)
static int prm_msec_to_sec (void *out_val, SYSPRM_DATATYPE out_type, void *in_val, SYSPRM_DATATYPE in_type)
static int prm_sec_to_msec (void *out_val, SYSPRM_DATATYPE out_type, void *in_val, SYSPRM_DATATYPE in_type)
static int prm_sec_to_min (void *out_val, SYSPRM_DATATYPE out_type, void *in_val, SYSPRM_DATATYPE in_type)
static int prm_min_to_sec (void *out_val, SYSPRM_DATATYPE out_type, void *in_val, SYSPRM_DATATYPE in_type)
static int prm_equal_to_ori (void *out_val, SYSPRM_DATATYPE out_type, void *in_val, SYSPRM_DATATYPE in_type)
static int prm_print (const SYSPRM_PARAM *prm, char *buf, size_t len, PRM_PRINT_MODE print_mode, PRM_PRINT_VALUE_MODE print_value_mode)
static int sysprm_load_and_init_internal (const char *db_name, const char *conf_file, bool reload, const int load_flags)
static void prm_check_environment (void)
static int prm_check_parameters (void)
static SYSPRM_ERR sysprm_validate_escape_char_parameters (const SYSPRM_ASSIGN_VALUE *assignment_list)
static int prm_load_by_section (INI_TABLE *ini, const char *section, bool ignore_section, bool reload, const char *file, const int load_flags)
static int prm_read_and_parse_ini_file (const char *prm_file_name, const char *db_name, const bool reload, const int load_flags)
static void prm_report_bad_entry (const char *key, int line, int err, const char *where)
static SYSPRM_ERR sysprm_get_param_range (SYSPRM_PARAM *prm, void *min, void *max)
static int prm_check_range (SYSPRM_PARAM *prm, void *value)
static int prm_set (SYSPRM_PARAM *prm, const char *value, bool set_flag)
static int prm_set_force (SYSPRM_PARAM *prm, const char *value)
static int prm_set_default (SYSPRM_PARAM *prm)
static SYSPRM_PARAM * prm_find (const char *pname, const char *section)
static const KEYVAL * prm_keyword (int val, const char *name, const KEYVAL *tbl, int dim)
static void prm_tune_parameters (void)
static int prm_compound_has_changed (SYSPRM_PARAM *prm, bool set_flag)
static void prm_set_compound (SYSPRM_PARAM *param, const char **compound_param_values[], const int values_count, bool set_flag)
static int prm_get_next_param_value (char **data, char **prm, char **value)
static PARAM_ID sysprm_get_id (const SYSPRM_PARAM *prm)
static int sysprm_compare_values (void *first_value, void *second_value, unsigned int val_type)
static void sysprm_set_sysprm_value_from_parameter (SYSPRM_VALUE *prm_value, SYSPRM_PARAM *prm)
static SESSION_PARAM * sysprm_alloc_session_parameters (void)
static SYSPRM_ERR sysprm_generate_new_value (SYSPRM_PARAM *prm, const char *value, bool check, SYSPRM_VALUE *new_value)
static int sysprm_set_value (SYSPRM_PARAM *prm, SYSPRM_VALUE value, bool set_flag, bool duplicate)
static void sysprm_set_system_parameter_value (SYSPRM_PARAM *prm, SYSPRM_VALUE value)
static int sysprm_print_sysprm_value (PARAM_ID prm_id, SYSPRM_VALUE value, char *buf, size_t len, PRM_PRINT_MODE print_mode)
static void sysprm_update_flag_different (SYSPRM_PARAM *prm)
static void sysprm_update_flag_allocated (SYSPRM_PARAM *prm)
static void sysprm_update_session_prm_flag_allocated (SESSION_PARAM *prm)
static void sysprm_clear_sysprm_value (SYSPRM_VALUE *value, SYSPRM_DATATYPE datatype)
static char * sysprm_pack_sysprm_value (char *ptr, SYSPRM_VALUE value, SYSPRM_DATATYPE datatype)
static int sysprm_packed_sysprm_value_length (SYSPRM_VALUE value, SYSPRM_DATATYPE datatype, int offset)
static char * sysprm_unpack_sysprm_value (char *ptr, SYSPRM_VALUE *value, SYSPRM_DATATYPE datatype)
static void prm_file_has_been_loaded (const char *conf_path, const char *db_name)
void sysprm_dump_parameters (FILE *fp)
void sysprm_set_er_log_file (const char *db_name)
int sysprm_load_and_init (const char *db_name, const char *conf_file, const int load_flags)
int sysprm_load_and_init_client (const char *db_name, const char *conf_file)
int sysprm_reload_and_init (const char *db_name, const char *conf_file)
SYSPRM_ERR sysprm_validate_change_parameters (const char *data, bool check, SYSPRM_ASSIGN_VALUE **assignments_ptr)
SYSPRM_ERR sysprm_make_default_values (const char *data, char *default_val_buf, const int buf_size)
void sysprm_change_parameter_values (const SYSPRM_ASSIGN_VALUE *assignments, bool check, bool set_flag)
SYSPRM_ERR sysprm_obtain_parameters (char *data, SYSPRM_ASSIGN_VALUE **prm_values_ptr)
void xsysprm_change_server_parameters (const SYSPRM_ASSIGN_VALUE *assignments)
void xsysprm_obtain_server_parameters (SYSPRM_ASSIGN_VALUE *prm_values)
SYSPRM_ASSIGN_VALUE * xsysprm_get_force_server_parameters (void)
void xsysprm_dump_server_parameters (FILE *outfp)
int sysprm_get_range (const char *pname, void *min, void *max)
int sysprm_check_range (const char *pname, void *value)
int sysprm_set_force (const char *pname, const char *pvalue)
int sysprm_set_to_default (const char *pname, bool set_to_force)
void sysprm_final (void)
int prm_get_master_port_id (void)
bool prm_get_commit_on_shutdown (void)
const char * prm_get_name (PARAM_ID prm_id)
void * prm_get_value (PARAM_ID prm_id)
int prm_get_integer_value (PARAM_ID prm_id)
bool prm_get_bool_value (PARAM_ID prm_id)
float prm_get_float_value (PARAM_ID prm_id)
char * prm_get_string_value (PARAM_ID prm_id)
int * prm_get_integer_list_value (PARAM_ID prm_id)
UINT64 prm_get_bigint_value (PARAM_ID prm_id)
void prm_set_integer_value (PARAM_ID prm_id, int value)
void prm_set_bool_value (PARAM_ID prm_id, bool value)
void prm_set_float_value (PARAM_ID prm_id, float value)
void prm_set_string_value (PARAM_ID prm_id, char *value)
void prm_set_integer_list_value (PARAM_ID prm_id, int *value)
void prm_set_bigint_value (PARAM_ID prm_id, UINT64 value)
bool sysprm_find_err_in_integer_list (PARAM_ID prm_id, int error_code)
bool sysprm_find_fi_code_in_integer_list (PARAM_ID prm_id, int fi_code)
void sysprm_free_session_parameters (SESSION_PARAM **session_parameters_ptr)
char * sysprm_pack_session_parameters (char *ptr, SESSION_PARAM *session_parameters)
int sysprm_packed_session_parameters_length (SESSION_PARAM *session_parameters, int offset)
char * sysprm_unpack_session_parameters (char *ptr, SESSION_PARAM **session_parameters_ptr)
char * sysprm_pack_assign_values (char *ptr, const SYSPRM_ASSIGN_VALUE *assign_values)
int sysprm_packed_assign_values_length (const SYSPRM_ASSIGN_VALUE *assign_values, int offset)
char * sysprm_unpack_assign_values (char *ptr, SYSPRM_ASSIGN_VALUE **assign_values_ptr)
void sysprm_free_assign_values (SYSPRM_ASSIGN_VALUE **assign_values_ptr)
int sysprm_print_assign_values (SYSPRM_ASSIGN_VALUE *prm_values, char *buffer, int length)
char * sysprm_print_parameters_for_qry_string (void)
char * sysprm_print_parameters_for_ha_repl (void)
int sysprm_init_intl_param (void)
int sysprm_set_error (SYSPRM_ERR rc, const char *data)
int sysprm_get_session_parameters_count (void)
Variables
static const char sysprm_error_log_file [] = "cub_server.err"
static const char sysprm_conf_file_name [] = "cubrid.conf"
static const char sysprm_ha_conf_file_name [] = "cubrid_ha.conf"
static int int_list_initial [1] = { 0 }
bool PRM_ER_LOG_DEBUG = false
static bool prm_er_log_debug_default = true
static unsigned int prm_er_log_debug_flag = 0
int PRM_ER_BTREE_DEBUG = 0
static int prm_er_btree_debug_default = 0
static unsigned int prm_er_btree_debug_flag = 0
int PRM_ER_LOG_LEVEL = ER_NOTIFICATION_SEVERITY
static int prm_er_log_level_default = ER_NOTIFICATION_SEVERITY
static int prm_er_log_level_lower = ER_FATAL_ERROR_SEVERITY
static int prm_er_log_level_upper = ER_NOTIFICATION_SEVERITY
static unsigned int prm_er_log_level_flag = 0
bool PRM_ER_LOG_WARNING = false
static bool prm_er_log_warning_default = false
static unsigned int prm_er_log_warning_flag = 0
int PRM_ER_EXIT_ASK = ER_EXIT_DEFAULT
static int prm_er_exit_ask_default = ER_EXIT_DEFAULT
static unsigned int prm_er_exit_ask_flag = 0
int PRM_ER_LOG_SIZE = (512 * 1024 * 1024)
static int prm_er_log_size_default = (512 * 1024 * 1024)
static int prm_er_log_size_lower = (100 * 80)
static unsigned int prm_er_log_size_flag = 0
const char * PRM_ER_LOG_FILE = sysprm_error_log_file
static const char * prm_er_log_file_default = sysprm_error_log_file
static unsigned int prm_er_log_file_flag = 0
bool PRM_ACCESS_IP_CONTROL = false
static bool prm_access_ip_control_default = false
static unsigned int prm_access_ip_control_flag = 0
const char * PRM_ACCESS_IP_CONTROL_FILE = ""
static const char * prm_access_ip_control_file_default = ""
static unsigned int prm_access_ip_control_file_flag = 0
bool PRM_IO_LOCKF_ENABLE = false
static bool prm_io_lockf_enable_default = true
static unsigned int prm_io_lockf_enable_flag = 0
int PRM_SR_NBUFFERS = 128
static int prm_sr_nbuffers_default = 128
static int prm_sr_nbuffers_lower = 1
static unsigned int prm_sr_nbuffers_flag = 0
int PRM_PB_NBUFFERS = 32768
static int prm_pb_nbuffers_default = 32768
static int prm_pb_nbuffers_lower = 1024
static unsigned int prm_pb_nbuffers_flag = 0
float PRM_PB_BUFFER_FLUSH_RATIO = 0.01f
static float prm_pb_buffer_flush_ratio_default = 0.01f
static float prm_pb_buffer_flush_ratio_lower = 0.01f
static float prm_pb_buffer_flush_ratio_upper = 0.95f
static unsigned int prm_pb_buffer_flush_ratio_flag = 0
float PRM_HF_UNFILL_FACTOR = 0.10f
static float prm_hf_unfill_factor_default = 0.10f
static float prm_hf_unfill_factor_lower = 0.0f
static float prm_hf_unfill_factor_upper = 0.3f
static unsigned int prm_hf_unfill_factor_flag = 0
int PRM_HF_MAX_BESTSPACE_ENTRIES = 1000000
static int prm_hf_max_bestspace_entries_default = 1000000
static unsigned int prm_hf_max_bestspace_entries_flag = 0
float PRM_BT_UNFILL_FACTOR = 0.05f
static float prm_bt_unfill_factor_default = 0.05f
static float prm_bt_unfill_factor_lower = 0.0f
static float prm_bt_unfill_factor_upper = 0.5f
static unsigned int prm_bt_unfill_factor_flag = 0
float PRM_BT_OID_NBUFFERS = 4.0f
static float prm_bt_oid_nbuffers_default = 4.0f
static float prm_bt_oid_nbuffers_lower = 0.049999f
static float prm_bt_oid_nbuffers_upper = 16.0f
static unsigned int prm_bt_oid_nbuffers_flag = 0
bool PRM_BT_INDEX_SCAN_OID_ORDER = false
static bool prm_bt_index_scan_oid_order_default = false
static unsigned int prm_bt_index_scan_oid_order_flag = 0
int PRM_BOSR_MAXTMP_PAGES = INT_MIN
static int prm_bosr_maxtmp_pages = -1
static unsigned int prm_bosr_maxtmp_flag = 0
int PRM_LK_TIMEOUT_MESSAGE_DUMP_LEVEL = 0
static unsigned int prm_lk_timeout_message_dump_level_flag = 0
int PRM_LK_ESCALATION_AT = 100000
static int prm_lk_escalation_at_default = 100000
static int prm_lk_escalation_at_lower = 5
static unsigned int prm_lk_escalation_at_flag = 0
bool PRM_LK_ROLLBACK_ON_LOCK_ESCALATION = false
static bool prm_lk_rollback_on_lock_escalation_default = false
static unsigned int prm_lk_rollback_on_lock_escalation_flag = 0
int PRM_LK_TIMEOUT_SECS = -1
static int prm_lk_timeout_secs_default = -1
static int prm_lk_timeout_secs_lower = -1
static unsigned int prm_lk_timeout_secs_flag = 0
float PRM_LK_RUN_DEADLOCK_INTERVAL = 1.0f
static float prm_lk_run_deadlock_interval_default = 1.0f
static float prm_lk_run_deadlock_interval_lower = 0.1f
static unsigned int prm_lk_run_deadlock_interval_flag = 0
int PRM_LOG_NBUFFERS = LOGPB_BUFFER_NPAGES_LOWER
static int prm_log_nbuffers_default = 16 * ONE_K
static int prm_log_nbuffers_lower = LOGPB_BUFFER_NPAGES_LOWER
static unsigned int prm_log_nbuffers_flag = 0
int PRM_LOG_CHECKPOINT_NPAGES = 100000
static int prm_log_checkpoint_npages_default = 100000
static int prm_log_checkpoint_npages_lower = 10
static unsigned int prm_log_checkpoint_npages_flag = 0
int PRM_LOG_CHECKPOINT_INTERVAL_SECS = 360
static int prm_log_checkpoint_interval_secs_default = 360
static int prm_log_checkpoint_interval_secs_lower = 60
static unsigned int prm_log_checkpoint_interval_secs_flag = 0
int PRM_LOG_CHECKPOINT_SLEEP_MSECS = 1
static int prm_log_checkpoint_sleep_msecs_default = 1
static int prm_log_checkpoint_sleep_msecs_lower = 0
static unsigned int prm_log_checkpoint_sleep_msecs_flag = 0
bool PRM_LOG_BACKGROUND_ARCHIVING = true
static bool prm_log_background_archiving_default = true
static unsigned int prm_log_background_archiving_flag = 0
int PRM_LOG_ISOLATION_LEVEL = TRAN_READ_COMMITTED
static int prm_log_isolation_level_default = TRAN_READ_COMMITTED
static int prm_log_isolation_level_lower = TRAN_READ_COMMITTED
static int prm_log_isolation_level_upper = TRAN_SERIALIZABLE
static unsigned int prm_log_isolation_level_flag = 0
static unsigned int prm_log_media_failure_support_flag = 0
bool PRM_COMMIT_ON_SHUTDOWN = false
static bool prm_commit_on_shutdown_default = false
static unsigned int prm_commit_on_shutdown_flag = 0
int PRM_SHUTDOWN_WAIT_TIME_IN_SECS = 600
static int prm_shutdown_wait_time_in_secs_default = 600
static int prm_shutdown_wait_time_in_secs_lower = 60
static unsigned int prm_shutdown_wait_time_in_secs_flag = 0
bool PRM_CSQL_AUTO_COMMIT = true
static bool prm_csql_auto_commit_default = true
static unsigned int prm_csql_auto_commit_flag = 0
bool PRM_LOG_SWEEP_CLEAN = true
static bool prm_log_sweep_clean_default = true
static unsigned int prm_log_sweep_clean_flag = 0
int PRM_WS_HASHTABLE_SIZE = 4096
static int prm_ws_hashtable_size_default = 4096
static int prm_ws_hashtable_size_lower = 1024
static unsigned int prm_ws_hashtable_size_flag = 0
bool PRM_WS_MEMORY_REPORT = false
static bool prm_ws_memory_report_default = false
static unsigned int prm_ws_memory_report_flag = 0
bool PRM_GC_ENABLE = false
static bool prm_gc_enable_default = false
static unsigned int prm_gc_enable_flag = 0
int PRM_TCP_PORT_ID = 1523
static int prm_tcp_port_id_default = 1523
static unsigned int prm_tcp_port_id_flag = 0
static int prm_tcp_port_id_upper = USHRT_MAX
static int prm_tcp_port_id_lower = 1
int PRM_TCP_CONNECTION_TIMEOUT = 5
static int prm_tcp_connection_timeout_default = 5
static int prm_tcp_connection_timeout_lower = -1
static unsigned int prm_tcp_connection_timeout_flag = 0
int PRM_OPTIMIZATION_LEVEL = 1
static int prm_optimization_level_default = 1
static unsigned int prm_optimization_level_flag = 0
bool PRM_QO_DUMP = false
static bool prm_qo_dump_default = false
static unsigned int prm_qo_dump_flag = 0
int PRM_CSS_MAX_CLIENTS = 100
static int prm_css_max_clients_default = 100
static int prm_css_max_clients_lower = 10
static int prm_css_max_clients_upper = CSS_MAX_CLIENT_COUNT
static unsigned int prm_css_max_clients_flag = 0
UINT64 PRM_THREAD_STACKSIZE = (1024 * 1024)
static UINT64 prm_thread_stacksize_default = (1024 * 1024)
static UINT64 prm_thread_stacksize_lower = 64 * 1024
static UINT64 prm_thread_stacksize_upper = INT_MAX
static unsigned int prm_thread_stacksize_flag = 0
const char * PRM_CFG_DB_HOSTS = ""
static const char * prm_cfg_db_hosts_default = NULL
static unsigned int prm_cfg_db_hosts_flag = 0
int PRM_RESET_TR_PARSER = 10
static int prm_reset_tr_parser_default = 10
static unsigned int prm_reset_tr_parser_flag = 0
int PRM_IO_BACKUP_NBUFFERS = 256
static int prm_io_backup_nbuffers_default = 256
static int prm_io_backup_nbuffers_lower = 256
static unsigned int prm_io_backup_nbuffers_flag = 0
UINT64 PRM_IO_BACKUP_MAX_VOLUME_SIZE = 0
static UINT64 prm_io_backup_max_volume_size_default = 0
static UINT64 prm_io_backup_max_volume_size_lower = 1024 * 32
static UINT64 prm_io_backup_max_volume_size_upper = DB_BIGINT_MAX
static unsigned int prm_io_backup_max_volume_size_flag = 0
int PRM_IO_BACKUP_SLEEP_MSECS = 0
static int prm_io_backup_sleep_msecs_default = 0
static int prm_io_backup_sleep_msecs_lower = 0
static unsigned int prm_io_backup_sleep_msecs_flag = 0
int PRM_MAX_PAGES_IN_TEMP_FILE_CACHE = 1000
static int prm_max_pages_in_temp_file_cache_default = 1000
static int prm_max_pages_in_temp_file_cache_lower = 100
static unsigned int prm_max_pages_in_temp_file_cache_flag = 0
int PRM_MAX_ENTRIES_IN_TEMP_FILE_CACHE = 512
static int prm_max_entries_in_temp_file_cache_default = 512
static int prm_max_entries_in_temp_file_cache_lower = 10
static unsigned int prm_max_entries_in_temp_file_cache_flag = 0
bool PRM_PTHREAD_SCOPE_PROCESS = true
static bool prm_pthread_scope_process_default = true
static unsigned int prm_pthread_scope_process_flag = 0
int PRM_TEMP_MEM_BUFFER_PAGES = 4
static int prm_temp_mem_buffer_pages_default = 4
static int prm_temp_mem_buffer_pages_lower = 0
static int prm_temp_mem_buffer_pages_upper = 20
static unsigned int prm_temp_mem_buffer_pages_flag = 0
int PRM_INDEX_SCAN_KEY_BUFFER_PAGES = 20
static int prm_index_scan_key_buffer_pages_default = 20
static int prm_index_scan_key_buffer_pages_lower = 0
static unsigned int prm_index_scan_key_buffer_pages_flag = 0
bool PRM_DONT_REUSE_HEAP_FILE = false
static bool prm_dont_reuse_heap_file_default = false
static unsigned int prm_dont_reuse_heap_file_flag = 0
int PRM_INSERT_MODE = 1 + 2
static int prm_insert_mode_default = 1 + 2
static int prm_insert_mode_lower = 0
static int prm_insert_mode_upper = 31
static unsigned int prm_insert_mode_flag = 0
int PRM_LK_MAX_SCANID_BIT = 32
static int prm_lk_max_scanid_bit_default = 32
static int prm_lk_max_scanid_bit_lower = 32
static int prm_lk_max_scanid_bit_upper = 128
static unsigned int prm_lk_max_scanid_bit_flag = 0
bool PRM_HOSTVAR_LATE_BINDING = false
static bool prm_hostvar_late_binding_default = false
static unsigned int prm_hostvar_late_binding_flag = 0
bool PRM_ENABLE_HISTO = false
static bool prm_enable_histo_default = false
static unsigned int prm_enable_histo_flag = 0
int PRM_MUTEX_BUSY_WAITING_CNT = 0
static int prm_mutex_busy_waiting_cnt_default = 0
static unsigned int prm_mutex_busy_waiting_cnt_flag = 0
int PRM_PB_NUM_LRU_CHAINS = 0
static int prm_pb_num_LRU_chains_default = 0
static int prm_pb_num_LRU_chains_lower = 0
static int prm_pb_num_LRU_chains_upper = 1000
static unsigned int prm_pb_num_LRU_chains_flag = 0
int PRM_PAGE_BG_FLUSH_INTERVAL_MSEC = 1000
static int prm_page_bg_flush_interval_msec_default = 1000
static int prm_page_bg_flush_interval_msec_lower = -1
static unsigned int prm_page_bg_flush_interval_msec_flag = 0
bool PRM_ADAPTIVE_FLUSH_CONTROL = true
static bool prm_adaptive_flush_control_default = true
static unsigned int prm_adaptive_flush_control_flag = 0
int PRM_MAX_FLUSH_PAGES_PER_SECOND = 10000
static int prm_max_flush_pages_per_second_default = 10000
static int prm_max_flush_pages_per_second_lower = 1
static int prm_max_flush_pages_per_second_upper = INT_MAX
static unsigned int prm_max_flush_pages_per_second_flag = 0
int PRM_PB_SYNC_ON_NFLUSH = 200
static int prm_pb_sync_on_nflush_default = 200
static int prm_pb_sync_on_nflush_lower = 1
static int prm_pb_sync_on_nflush_upper = INT_MAX
static unsigned int prm_pb_sync_on_nflush_flag = 0
int PRM_PB_DEBUG_PAGE_VALIDATION_LEVEL = PGBUF_DEBUG_NO_PAGE_VALIDATION
static int prm_pb_debug_page_validation_level_default = PGBUF_DEBUG_PAGE_VALIDATION_FETCH
static unsigned int prm_pb_debug_page_validation_level_flag = 0
bool PRM_ORACLE_STYLE_OUTERJOIN = false
static bool prm_oracle_style_outerjoin_default = false
static unsigned int prm_oracle_style_outerjoin_flag = 0
int PRM_COMPAT_MODE = COMPAT_CUBRID
static int prm_compat_mode_default = COMPAT_CUBRID
static int prm_compat_mode_lower = COMPAT_CUBRID
static int prm_compat_mode_upper = COMPAT_ORACLE
static unsigned int prm_compat_mode_flag = 0
bool PRM_ANSI_QUOTES = true
static bool prm_ansi_quotes_default = true
static unsigned int prm_ansi_quotes_flag = 0
int PRM_DEFAULT_WEEK_FORMAT = 0
static int prm_week_format_default = 0
static int prm_week_format_lower = 0
static int prm_week_format_upper = 7
static unsigned int prm_week_format_flag = 0
bool PRM_TEST_MODE = false
static bool prm_test_mode_default = false
static unsigned int prm_test_mode_flag = 0
bool PRM_ONLY_FULL_GROUP_BY = false
static bool prm_only_full_group_by_default = false
static unsigned int prm_only_full_group_by_flag = 0
bool PRM_PIPES_AS_CONCAT = true
static bool prm_pipes_as_concat_default = true
static unsigned int prm_pipes_as_concat_flag = 0
bool PRM_MYSQL_TRIGGER_CORRELATION_NAMES = false
static bool prm_mysql_trigger_correlation_names_default = false
static unsigned int prm_mysql_trigger_correlation_names_flag = 0
bool PRM_REQUIRE_LIKE_ESCAPE_CHARACTER = false
static bool prm_require_like_escape_character_default = false
static unsigned int prm_require_like_escape_character_flag = 0
bool PRM_NO_BACKSLASH_ESCAPES = true
static bool prm_no_backslash_escapes_default = true
static unsigned int prm_no_backslash_escapes_flag = 0
UINT64 PRM_GROUP_CONCAT_MAX_LEN = 1024
static UINT64 prm_group_concat_max_len_default = 1024
static UINT64 prm_group_concat_max_len_lower = 4
static UINT64 prm_group_concat_max_len_upper = INT_MAX
static unsigned int prm_group_concat_max_len_flag = 0
UINT64 PRM_STRING_MAX_SIZE_BYTES = 1024 * 1024
static UINT64 prm_string_max_size_bytes_default = 1024 * 1024
static UINT64 prm_string_max_size_bytes_lower = 64
static UINT64 prm_string_max_size_bytes_upper = 32 * 1024 * 1024
static unsigned int prm_string_max_size_bytes_flag = 0
bool PRM_ADD_COLUMN_UPDATE_HARD_DEFAULT = false
static bool prm_add_column_update_hard_default_default = false
static unsigned int prm_add_column_update_hard_default_flag = 0
bool PRM_RETURN_NULL_ON_FUNCTION_ERRORS = false
static bool prm_return_null_on_function_errors_default = false
static unsigned int prm_return_null_on_function_errors_flag = 0
bool PRM_ALTER_TABLE_CHANGE_TYPE_STRICT = true
static bool prm_alter_table_change_type_strict_default = true
static unsigned int prm_alter_table_change_type_strict_flag = 1
bool PRM_PLUS_AS_CONCAT = true
static bool prm_plus_as_concat_default = true
static unsigned int prm_plus_as_concat_flag = 0
int PRM_COMPACTDB_PAGE_RECLAIM_ONLY = 0
static int prm_compactdb_page_reclaim_only_default = 0
static unsigned int prm_compactdb_page_reclaim_only_flag = 0
float PRM_LIKE_TERM_SELECTIVITY = 0.1f
static float prm_like_term_selectivity_default = 0.1f
static float prm_like_term_selectivity_upper = 1.0f
static float prm_like_term_selectivity_lower = 0.0f
static unsigned int prm_like_term_selectivity_flag = 0
int PRM_MAX_OUTER_CARD_OF_IDXJOIN = 0
static int prm_max_outer_card_of_idxjoin_default = 0
static int prm_max_outer_card_of_idxjoin_lower = 0
static unsigned int prm_max_outer_card_of_idxjoin_flag = 0
bool PRM_ORACLE_STYLE_EMPTY_STRING = false
static bool prm_oracle_style_empty_string_default = false
static unsigned int prm_oracle_style_empty_string_flag = 0
int PRM_SUPPRESS_FSYNC = 0
static int prm_suppress_fsync_default = 0
static int prm_suppress_fsync_upper = 100
static int prm_suppress_fsync_lower = 0
static unsigned int prm_suppress_fsync_flag = 0
bool PRM_CALL_STACK_DUMP_ON_ERROR = false
static bool prm_call_stack_dump_on_error_default = false
static unsigned int prm_call_stack_dump_on_error_flag = 0
int * PRM_CALL_STACK_DUMP_ACTIVATION = int_list_initial
static bool * prm_call_stack_dump_activation_default = NULL
static unsigned int prm_call_stack_dump_activation_flag = 0
int * PRM_CALL_STACK_DUMP_DEACTIVATION = int_list_initial
static bool * prm_call_stack_dump_deactivation_default = NULL
static unsigned int prm_call_stack_dump_deactivation_flag = 0
bool PRM_COMPAT_NUMERIC_DIVISION_SCALE = false
static bool prm_compat_numeric_division_scale_default = false
static unsigned int prm_compat_numeric_division_scale_flag = 0
bool PRM_DBFILES_PROTECT = false
static bool prm_dbfiles_protect_default = false
static unsigned int prm_dbfiles_protect_flag = 0
bool PRM_AUTO_RESTART_SERVER = true
static bool prm_auto_restart_server_default = true
static unsigned int prm_auto_restart_server_flag = 0
int PRM_XASL_CACHE_MAX_ENTRIES = 1000
static int prm_xasl_cache_max_entries_default = 1000
static unsigned int prm_xasl_cache_max_entries_flag = 0
int PRM_XASL_CACHE_MAX_CLONES = 1000
static int prm_xasl_cache_max_clones_default = 1000
static int prm_xasl_cache_max_clones_lower = 0
static int prm_xasl_cache_max_clones_upper = 2000
static unsigned int prm_xasl_cache_max_clones_flag = 0
int PRM_XASL_CACHE_TIMEOUT = -1
static int prm_xasl_cache_timeout_default = -1
static unsigned int prm_xasl_cache_timeout_flag = 0
bool PRM_XASL_CACHE_LOGGING = false
static bool prm_xasl_cache_logging_default = false
static unsigned int prm_xasl_cache_logging_flag = 0
int PRM_FILTER_PRED_MAX_CACHE_ENTRIES = 1000
static int prm_filter_pred_max_cache_entries_default = 1000
static unsigned int prm_filter_pred_max_cache_entries_flag = 0
int PRM_FILTER_PRED_MAX_CACHE_CLONES = 10
static int prm_filter_pred_max_cache_clones_default = 10
static unsigned int prm_filter_pred_max_cache_clones_flag = 0
int PRM_LIST_QUERY_CACHE_MODE = 2
static int prm_list_query_cache_mode_default = 2
static int prm_list_query_cache_mode_upper = 2
static int prm_list_query_cache_mode_lower = 2
static unsigned int prm_list_query_cache_mode_flag = 0
int PRM_LIST_MAX_QUERY_CACHE_ENTRIES = 0
static int prm_list_max_query_cache_entries_default = 0
static int prm_list_max_query_cache_entries_upper = INT_MAX
static int prm_list_max_query_cache_entries_lower = 0
static unsigned int prm_list_max_query_cache_entries_flag = 0
int PRM_LIST_MAX_QUERY_CACHE_PAGES = 0
static int prm_list_max_query_cache_pages_default = 0
static int prm_list_max_query_cache_pages_upper = INT_MAX
static int prm_list_max_query_cache_pages_lower = 0
static unsigned int prm_list_max_query_cache_pages_flag = 0
bool PRM_USE_ORDERBY_SORT_LIMIT = true
static bool prm_use_orderby_sort_limit_default = true
static unsigned int prm_use_orderby_sort_limit_flag = 0
static unsigned int prm_replication_mode_flag = 0
int PRM_HA_MODE = HA_MODE_OFF
static int prm_ha_mode_default = HA_MODE_OFF
static int prm_ha_mode_upper = HA_MODE_REPLICA
static int prm_ha_mode_lower = HA_MODE_OFF
int PRM_HA_MODE_FOR_SA_UTILS_ONLY = HA_MODE_OFF
static unsigned int prm_ha_mode_flag = 0
int PRM_HA_SERVER_STATE = HA_SERVER_STATE_IDLE
static int prm_ha_server_state_default = HA_SERVER_STATE_IDLE
static int prm_ha_server_state_upper = HA_SERVER_STATE_DEAD
static int prm_ha_server_state_lower = HA_SERVER_STATE_IDLE
static unsigned int prm_ha_server_state_flag = 0
int PRM_HA_LOG_APPLIER_STATE = HA_LOG_APPLIER_STATE_UNREGISTERED
static int prm_ha_log_applier_state_default = HA_LOG_APPLIER_STATE_UNREGISTERED
static int prm_ha_log_applier_state_upper = HA_LOG_APPLIER_STATE_ERROR
static int prm_ha_log_applier_state_lower = HA_LOG_APPLIER_STATE_UNREGISTERED
static unsigned int prm_ha_log_applier_state_flag = 0
const char * PRM_HA_NODE_LIST = ""
static const char * prm_ha_node_list_default = NULL
static unsigned int prm_ha_node_list_flag = 0
const char * PRM_HA_REPLICA_LIST = ""
static const char * prm_ha_replica_list_default = NULL
static unsigned int prm_ha_replica_list_flag = 0
const char * PRM_HA_DB_LIST = ""
static const char * prm_ha_db_list_default = NULL
static unsigned int prm_ha_db_list_flag = 0
const char * PRM_HA_COPY_LOG_BASE = ""
static const char * prm_ha_copy_log_base_default = NULL
static unsigned int prm_ha_copy_log_base_flag = 0
const char * PRM_HA_COPY_SYNC_MODE = ""
static const char * prm_ha_copy_sync_mode_default = NULL
static unsigned int prm_ha_copy_sync_mode_flag = 0
int PRM_HA_APPLY_MAX_MEM_SIZE = HB_DEFAULT_APPLY_MAX_MEM_SIZE
static int prm_ha_apply_max_mem_size_default = HB_DEFAULT_APPLY_MAX_MEM_SIZE
static int prm_ha_apply_max_mem_size_upper = INT_MAX
static int prm_ha_apply_max_mem_size_lower = 0
static unsigned int prm_ha_apply_max_mem_size_flag = 0
int PRM_HA_PORT_ID = HB_DEFAULT_HA_PORT_ID
static int prm_ha_port_id_default = HB_DEFAULT_HA_PORT_ID
static unsigned int prm_ha_port_id_flag = 0
static int prm_ha_port_id_upper = USHRT_MAX
static int prm_ha_port_id_lower = 1
int PRM_HA_INIT_TIMER_IN_MSECS = HB_DEFAULT_INIT_TIMER_IN_MSECS
static int prm_ha_init_timer_im_msecs_default = HB_DEFAULT_INIT_TIMER_IN_MSECS
static unsigned int prm_ha_init_timer_im_msecs_flag = 0
int PRM_HA_HEARTBEAT_INTERVAL_IN_MSECS = HB_DEFAULT_HEARTBEAT_INTERVAL_IN_MSECS
static int prm_ha_heartbeat_interval_in_msecs_default = HB_DEFAULT_HEARTBEAT_INTERVAL_IN_MSECS
static unsigned int prm_ha_heartbeat_interval_in_msecs_flag = 0
int PRM_HA_CALC_SCORE_INTERVAL_IN_MSECS = HB_DEFAULT_CALC_SCORE_INTERVAL_IN_MSECS
static int prm_ha_calc_score_interval_in_msecs_default = HB_DEFAULT_CALC_SCORE_INTERVAL_IN_MSECS
static unsigned int prm_ha_calc_score_interval_in_msecs_flag = 0
int PRM_HA_FAILOVER_WAIT_TIME_IN_MSECS = HB_DEFAULT_FAILOVER_WAIT_TIME_IN_MSECS
static int prm_ha_failover_wait_time_in_msecs_default = HB_DEFAULT_FAILOVER_WAIT_TIME_IN_MSECS
static unsigned int prm_ha_failover_wait_time_in_msecs_flag = 0
int PRM_HA_PROCESS_START_CONFIRM_INTERVAL_IN_MSECS = HB_DEFAULT_START_CONFIRM_INTERVAL_IN_MSECS
static int prm_ha_process_start_confirm_interval_in_msecs_default = HB_DEFAULT_START_CONFIRM_INTERVAL_IN_MSECS
static unsigned int prm_ha_process_start_confirm_interval_in_msecs_flag = 0
int PRM_HA_PROCESS_DEREG_CONFIRM_INTERVAL_IN_MSECS = HB_DEFAULT_DEREG_CONFIRM_INTERVAL_IN_MSECS
static int prm_ha_process_dereg_confirm_interval_in_msecs_default = HB_DEFAULT_DEREG_CONFIRM_INTERVAL_IN_MSECS
static unsigned int prm_ha_process_dereg_confirm_interval_in_msecs_flag = 0
int PRM_HA_MAX_PROCESS_START_CONFIRM = HB_DEFAULT_MAX_PROCESS_START_CONFIRM
static int prm_ha_max_process_start_confirm_default = HB_DEFAULT_MAX_PROCESS_START_CONFIRM
static unsigned int prm_ha_max_process_start_confirm_flag = 0
int PRM_HA_MAX_PROCESS_DEREG_CONFIRM = HB_DEFAULT_MAX_PROCESS_DEREG_CONFIRM
static int prm_ha_max_process_dereg_confirm_default = HB_DEFAULT_MAX_PROCESS_DEREG_CONFIRM
static unsigned int prm_ha_max_process_dereg_confirm_flag = 0
int PRM_HA_UNACCEPTABLE_PROC_RESTART_TIMEDIFF = HB_DEFAULT_UNACCEPTABLE_PROC_RESTART_TIMEDIFF_IN_MSECS
static int prm_ha_unacceptable_proc_restart_timediff_default = HB_DEFAULT_UNACCEPTABLE_PROC_RESTART_TIMEDIFF_IN_MSECS
static unsigned int prm_ha_unacceptable_proc_restart_timediff_flag = 0
int PRM_HA_CHANGEMODE_INTERVAL_IN_MSECS = HB_DEFAULT_CHANGEMODE_INTERVAL_IN_MSECS
static int prm_ha_changemode_interval_in_msecs_default = HB_DEFAULT_CHANGEMODE_INTERVAL_IN_MSECS
static unsigned int prm_ha_changemode_interval_in_msecs_flag = 0
int PRM_HA_MAX_HEARTBEAT_GAP = HB_DEFAULT_MAX_HEARTBEAT_GAP
static int prm_ha_max_heartbeat_gap_default = HB_DEFAULT_MAX_HEARTBEAT_GAP
static unsigned int prm_ha_max_heartbeat_gap_flag = 0
const char * PRM_HA_PING_HOSTS = ""
static const char * prm_ha_ping_hosts_default = NULL
static unsigned int prm_ha_ping_hosts_flag = 0
int * PRM_HA_APPLYLOGDB_RETRY_ERROR_LIST = int_list_initial
static bool * prm_ha_applylogdb_retry_error_list_default = NULL
static unsigned int prm_ha_applylogdb_retry_error_list_flag = 0
int * PRM_HA_APPLYLOGDB_IGNORE_ERROR_LIST = int_list_initial
static bool * prm_ha_applylogdb_ignore_error_list_default = NULL
static unsigned int prm_ha_applylogdb_ignore_error_list_flag = 0
int PRM_HA_APPLYLOGDB_LOG_WAIT_TIME_IN_SECS = -1
static int prm_ha_applylogdb_log_wait_time_in_secs_default = -1
static int prm_ha_applylogdb_log_wait_time_in_secs_lower = -1
static unsigned int prm_ha_applylogdb_log_wait_time_in_secs_flag = 0
bool PRM_HA_SQL_LOGGING = false
static bool prm_ha_sql_logging_default = false
static unsigned int prm_ha_sql_logging_flag = 0
int PRM_HA_SQL_LOG_MAX_SIZE_IN_MB = INT_MIN
static int prm_ha_sql_log_max_size_in_mb_default = 50
static int prm_ha_sql_log_max_size_in_mb_upper = 2048
static int prm_ha_sql_log_max_size_in_mb_lower = 1
static unsigned int prm_ha_sql_log_max_size_in_mb_flag = 0
int PRM_HA_COPY_LOG_MAX_ARCHIVES = 1
static int prm_ha_copy_log_max_archives_default = 1
static int prm_ha_copy_log_max_archives_upper = INT_MAX
static int prm_ha_copy_log_max_archives_lower = 0
static unsigned int prm_ha_copy_log_max_archives_flag = 0
int PRM_HA_COPY_LOG_TIMEOUT = 5
static int prm_ha_copy_log_timeout_default = 5
static int prm_ha_copy_log_timeout_upper = INT_MAX
static int prm_ha_copy_log_timeout_lower = -1
static unsigned int prm_ha_copy_log_timeout_flag = 0
int PRM_HA_REPLICA_DELAY_IN_SECS = 0
static int prm_ha_replica_delay_in_secs_default = 0
static int prm_ha_replica_delay_in_secs_upper = INT_MAX
static int prm_ha_replica_delay_in_secs_lower = 0
static unsigned int prm_ha_replica_delay_in_secs_flag = 0
const char * PRM_HA_REPLICA_TIME_BOUND = ""
static const char * prm_ha_replica_time_bound_default = NULL
static unsigned int prm_ha_replica_time_bound_flag = 0
int PRM_HA_DELAY_LIMIT_IN_SECS = 0
static int prm_ha_delay_limit_in_secs_default = 0
static int prm_ha_delay_limit_in_secs_upper = INT_MAX
static int prm_ha_delay_limit_in_secs_lower = 0
static unsigned int prm_ha_delay_limit_in_secs_flag = 0
int PRM_HA_DELAY_LIMIT_DELTA_IN_SECS = 0
static int prm_ha_delay_limit_delta_in_secs_default = 0
static int prm_ha_delay_limit_delta_in_secs_upper = INT_MAX
static int prm_ha_delay_limit_delta_in_secs_lower = 0
static unsigned int prm_ha_delay_limit_delta_in_secs_flag = 0
int PRM_HA_APPLYLOGDB_MAX_COMMIT_INTERVAL_IN_MSECS = 500
static int prm_ha_applylogdb_max_commit_interval_in_msecs_default = 500
static int prm_ha_applylogdb_max_commit_interval_in_msecs_upper = INT_MAX
static int prm_ha_applylogdb_max_commit_interval_in_msecs_lower = 0
static unsigned int prm_ha_applylogdb_max_commit_interval_in_msecs_flag = 0
int PRM_HA_CHECK_DISK_FAILURE_INTERVAL_IN_SECS = 15
static int prm_ha_check_disk_failure_interval_in_secs_default = 15
static int prm_ha_check_disk_failure_interval_in_secs_upper = INT_MAX
static int prm_ha_check_disk_failure_interval_in_secs_lower = 0
static unsigned int prm_ha_check_disk_failure_interval_in_secs_flag = 0
bool PRM_GENERAL_RESERVE_01 = false
static bool prm_general_reserve_01_default = false
static unsigned int prm_general_reserve_01_flag = 0
bool PRM_COMPAT_PRIMARY_KEY = false
static bool prm_compat_primary_key_default = false
static unsigned int prm_compat_primary_key_flag = 0
static unsigned int prm_log_header_flush_interval_flag = 0
bool PRM_LOG_ASYNC_COMMIT = false
static bool prm_log_async_commit_default = false
static unsigned int prm_log_async_commit_flag = 0
int PRM_LOG_GROUP_COMMIT_INTERVAL_MSECS = 0
static int prm_log_group_commit_interval_msecs_default = 0
static int prm_log_group_commit_interval_msecs_lower = 0
static unsigned int prm_log_group_commit_interval_msecs_flag = 0
static unsigned int prm_log_bg_flush_interval_msecs_flag = 0
static unsigned int prm_log_bg_flush_num_pages_flag = 0
bool PRM_INTL_MBS_SUPPORT = false
static bool prm_intl_mbs_support_default = false
static unsigned int prm_intl_mbs_support_flag = 0
bool PRM_LOG_COMPRESS = true
static bool prm_log_compress_default = true
static unsigned int prm_log_compress_flag = 0
bool PRM_BLOCK_NOWHERE_STATEMENT = false
static bool prm_block_nowhere_statement_default = false
static unsigned int prm_block_nowhere_statement_flag = 0
bool PRM_BLOCK_DDL_STATEMENT = false
static bool prm_block_ddl_statement_default = false
static unsigned int prm_block_ddl_statement_flag = 0
int PRM_CSQL_HISTORY_NUM = 50
static int prm_csql_history_num_default = 50
static int prm_csql_history_num_upper = 200
static int prm_csql_history_num_lower = 1
static unsigned int prm_csql_history_num_flag = 0
bool PRM_LOG_TRACE_DEBUG = false
static bool prm_log_trace_debug_default = false
static unsigned int prm_log_trace_debug_flag = 0
const char * PRM_DL_FORK = ""
static const char * prm_dl_fork_default = NULL
static unsigned int prm_dl_fork_flag = 0
bool PRM_ER_PRODUCTION_MODE = true
static bool prm_er_production_mode_default = true
static unsigned int prm_er_production_mode_flag = 0
int PRM_ER_STOP_ON_ERROR = 0
static int prm_er_stop_on_error_default = 0
static int prm_er_stop_on_error_upper = 0
static unsigned int prm_er_stop_on_error_flag = 0
int PRM_TCP_RCVBUF_SIZE = -1
static int prm_tcp_rcvbuf_size_default = -1
static unsigned int prm_tcp_rcvbuf_size_flag = 0
int PRM_TCP_SNDBUF_SIZE = -1
static int prm_tcp_sndbuf_size_default = -1
static unsigned int prm_tcp_sndbuf_size_flag = 0
bool PRM_TCP_NODELAY = false
static bool prm_tcp_nodelay_default = false
static unsigned int prm_tcp_nodelay_flag = 0
bool PRM_TCP_KEEPALIVE = true
static bool prm_tcp_keepalive_default = true
static unsigned int prm_tcp_keepalive_flag = 0
bool PRM_CSQL_SINGLE_LINE_MODE = false
static bool prm_csql_single_line_mode_default = false
static unsigned int prm_csql_single_line_mode_flag = 0
bool PRM_XASL_DEBUG_DUMP = false
static bool prm_xasl_debug_dump_default = false
static unsigned int prm_xasl_debug_dump_flag = 0
int PRM_LOG_MAX_ARCHIVES = INT_MAX
static int prm_log_max_archives_default = INT_MAX
static int prm_log_max_archives_lower = 0
static unsigned int prm_log_max_archives_flag = 0
bool PRM_FORCE_REMOVE_LOG_ARCHIVES = true
static bool prm_force_remove_log_archives_default = true
static unsigned int prm_force_remove_log_archives_flag = 0
int PRM_REMOVE_LOG_ARCHIVES_INTERVAL = 0
static int prm_remove_log_archives_interval_default = 0
static int prm_remove_log_archives_interval_lower = 0
static unsigned int prm_remove_log_archives_interval_flag = 0
bool PRM_LOG_NO_LOGGING = false
static bool prm_log_no_logging_default = false
static unsigned int prm_log_no_logging_flag = 0
bool PRM_UNLOADDB_IGNORE_ERROR = false
static bool prm_unloaddb_ignore_error_default = false
static unsigned int prm_unloaddb_ignore_error_flag = 0
int PRM_UNLOADDB_LOCK_TIMEOUT = -1
static int prm_unloaddb_lock_timeout_default = -1
static int prm_unloaddb_lock_timeout_lower = -1
static unsigned int prm_unloaddb_lock_timeout_flag = 0
int PRM_LOADDB_FLUSH_INTERVAL = 1000
static int prm_loaddb_flush_interval_default = 1000
static int prm_loaddb_flush_interval_lower = 0
static unsigned int prm_loaddb_flush_interval_flag = 0
const char * PRM_IO_TEMP_VOLUME_PATH = ""
static char * prm_io_temp_volume_path_default = NULL
static unsigned int prm_io_temp_volume_path_flag = 0
const char * PRM_TDE_KEYS_FILE_PATH = ""
static char * prm_tde_keys_file_path_default = NULL
static unsigned int prm_tde_keys_file_path_flag = 0
const char * PRM_IO_VOLUME_EXT_PATH = ""
static char * prm_io_volume_ext_path_default = NULL
static unsigned int prm_io_volume_ext_path_flag = 0
bool PRM_UNIQUE_ERROR_KEY_VALUE = false
static bool prm_unique_error_key_value_default = false
static unsigned int prm_unique_error_key_value_flag = 0
bool PRM_USE_SYSTEM_MALLOC = false
static bool prm_use_system_malloc_default = false
static unsigned int prm_use_system_malloc_flag = 0
const char * PRM_EVENT_HANDLER = ""
static const char * prm_event_handler_default = NULL
static unsigned int prm_event_handler_flag = 0
int * PRM_EVENT_ACTIVATION = int_list_initial
static bool * prm_event_activation_default = NULL
static unsigned int prm_event_activation_flag = 0
bool PRM_READ_ONLY_MODE = false
static bool prm_read_only_mode_default = false
static unsigned int prm_read_only_mode_flag = 0
int PRM_MNT_WAITING_THREAD = 0
static int prm_mnt_waiting_thread_default = 0
static int prm_mnt_waiting_thread_lower = 0
static unsigned int prm_mnt_waiting_thread_flag = 0
int * PRM_MNT_STATS_THRESHOLD = int_list_initial
static int * prm_mnt_stats_threshold_default = NULL
static unsigned int prm_mnt_stats_threshold_flag = 0
const char * PRM_SERVICE_SERVICE_LIST = ""
static const char * prm_service_service_list_default = NULL
static unsigned int prm_service_service_list_flag = 0
const char * PRM_SERVICE_SERVER_LIST = ""
static const char * prm_service_server_list_default = NULL
static unsigned int prm_service_server_list_flag = 0
int PRM_SESSION_STATE_TIMEOUT = 60 * 60 * 6
static int prm_session_timeout_default = 60 * 60 * 6
static int prm_session_timeout_lower = 60
static int prm_session_timeout_upper = 60 * 60 * 24 * 365
static unsigned int prm_session_timeout_flag = 0
int PRM_MULTI_RANGE_OPT_LIMIT = 100
static int prm_multi_range_opt_limit_default = 100
static int prm_multi_range_opt_limit_lower = 0
static int prm_multi_range_opt_limit_upper = 10000
static unsigned int prm_multi_range_opt_limit_flag = 0
UINT64 PRM_DB_VOLUME_SIZE = 536870912ULL
static UINT64 prm_db_volume_size_default = 536870912ULL
static UINT64 prm_db_volume_size_lower = 0
static UINT64 prm_db_volume_size_upper = 21474836480ULL
static unsigned int prm_db_volume_size_flag = 0
UINT64 PRM_LOG_VOLUME_SIZE = 536870912ULL
static UINT64 prm_log_volume_size_default = 536870912ULL
static UINT64 prm_log_volume_size_lower = 20971520ULL
static UINT64 prm_log_volume_size_upper = 4294967296ULL
static unsigned int prm_log_volume_size_flag = 0
char * PRM_INTL_NUMBER_LANG = NULL
static char * prm_intl_number_lang_default = NULL
static unsigned int prm_intl_number_lang_flag = 0
char * PRM_INTL_DATE_LANG = NULL
static char * prm_intl_date_lang_default = NULL
static unsigned int prm_intl_date_lang_flag = 0
bool PRM_UNICODE_INPUT_NORMALIZATION = false
static bool prm_unicode_input_normalization_default = false
static unsigned int prm_unicode_input_normalization_flag = 0
bool PRM_UNICODE_OUTPUT_NORMALIZATION = false
static bool prm_unicode_output_normalization_default = false
static unsigned int prm_unicode_output_normalization_flag = 0
bool PRM_INTL_CHECK_INPUT_STRING = false
static bool prm_intl_check_input_string_default = false
static unsigned int prm_intl_check_input_string_flag = 0
int PRM_CHECK_PEER_ALIVE = CSS_CHECK_PEER_ALIVE_BOTH
static int prm_check_peer_alive_default = CSS_CHECK_PEER_ALIVE_BOTH
static unsigned int prm_check_peer_alive_flag = 0
UINT64 PRM_GENERIC_VOL_PREALLOC_SIZE
static UINT64 prm_generic_vol_prealloc_size_default = 52428800ULL
static UINT64 prm_generic_vol_prealloc_size_lower = 0ULL
static UINT64 prm_generic_vol_prealloc_size_upper = 21474836480ULL
static unsigned int prm_generic_vol_prealloc_size_flag = 0
int PRM_SQL_TRACE_SLOW_MSECS = -1
static int prm_sql_trace_slow_msecs_default = -1
static int prm_sql_trace_slow_msecs_lower = -1
static int prm_sql_trace_slow_msecs_upper = 1000 * 60 * 60 * 24
static unsigned int prm_sql_trace_slow_msecs_flag = 0
bool PRM_SQL_TRACE_EXECUTION_PLAN = false
static bool prm_sql_trace_execution_plan_default = false
static unsigned int prm_sql_trace_execution_plan_flag = 0
int PRM_LOG_TRACE_FLUSH_TIME_MSECS = 0
static int prm_log_trace_flush_time_msecs_default = 0
static int prm_log_trace_flush_time_msecs_lower = 0
static unsigned int prm_log_trace_flush_time_msecs_flag = 0
char * PRM_INTL_COLLATION = NULL
static char * prm_intl_collation_default = NULL
static unsigned int prm_intl_collation_flag = 0
int PRM_SORT_LIMIT_MAX_COUNT = 1000
static int prm_sort_limit_max_count_default = 1000
static int prm_sort_limit_max_count_lower = 0
static int prm_sort_limit_max_count_upper = INT_MAX
static unsigned int prm_sort_limit_max_count_flag = 0
int PRM_SQL_TRACE_IOREADS = 0
static int prm_sql_trace_ioreads_default = 0
static int prm_sql_trace_ioreads_lower = 0
static unsigned int prm_sql_trace_ioreads_flag = 0
bool PRM_QUERY_TRACE = false
static bool prm_query_trace_default = false
static unsigned int prm_query_trace_flag = 0
int PRM_QUERY_TRACE_FORMAT = QUERY_TRACE_TEXT
static int prm_query_trace_format_default = QUERY_TRACE_TEXT
static int prm_query_trace_format_lower = QUERY_TRACE_TEXT
static int prm_query_trace_format_upper = QUERY_TRACE_JSON
static unsigned int prm_query_trace_format_flag = 0
int PRM_MAX_RECURSION_SQL_DEPTH = 400
static int prm_max_recursion_sql_depth_default = 400
static unsigned int prm_max_recursion_sql_depth_flag = 0
UINT64 PRM_MAX_AGG_HASH_SIZE = 2 * 1024 * 1024
static UINT64 prm_max_agg_hash_size_default = 2 * 1024 * 1024
static UINT64 prm_max_agg_hash_size_lower = 32 * 1024
static UINT64 prm_max_agg_hash_size_upper = 128 * 1024 * 1024
static unsigned int prm_max_agg_hash_size_flag = 0
bool PRM_AGG_HASH_RESPECT_ORDER = true
static bool prm_agg_hash_respect_order_default = true
static unsigned int prm_agg_hash_respect_order_flag = 0
bool PRM_USE_BTREE_FENCE_KEY = true
static bool prm_use_btree_fence_key_default = true
static unsigned int prm_use_btree_fence_key_flag = 0
bool PRM_UPDATE_USE_ATTRIBUTE_REFERENCES = false
static bool prm_update_use_attribute_references_default = false
static unsigned int prm_update_use_attribute_references_flag = 0
float PRM_PB_AOUT_RATIO = 0.0f
static float prm_pb_aout_ratio_default = 0.0f
static float prm_pb_aout_ratio_upper = 3.0
static float prm_pb_aout_ratio_lower = 0
static unsigned int prm_pb_aout_ratio_flag = 0
bool PRM_OPTIMIZER_ENABLE_MERGE_JOIN = false
static bool prm_optimizer_enable_merge_join_default = false
static unsigned int prm_optimizer_enable_merge_join_flag = 0
UINT64 PRM_MAX_HASH_LIST_SCAN_SIZE = 4 * 1024 * 1024
static UINT64 prm_max_hash_list_scan_size_default = 4 * 1024 * 1024
static UINT64 prm_max_hash_list_scan_size_lower = 0
static UINT64 prm_max_hash_list_scan_size_upper = 128 * 1024 * 1024
static unsigned int prm_max_hash_list_scan_size_flag = 0
bool PRM_OPTIMIZER_RESERVE_02 = false
static bool prm_optimizer_reserve_02_default = false
static unsigned int prm_optimizer_reserve_02_flag = 0
bool PRM_OPTIMIZER_RESERVE_03 = false
static bool prm_optimizer_reserve_03_default = false
static unsigned int prm_optimizer_reserve_03_flag = 0
bool PRM_OPTIMIZER_RESERVE_04 = false
static bool prm_optimizer_reserve_04_default = false
static unsigned int prm_optimizer_reserve_04_flag = 0
bool PRM_OPTIMIZER_RESERVE_05 = false
static bool prm_optimizer_reserve_05_default = false
static unsigned int prm_optimizer_reserve_05_flag = 0
bool PRM_OPTIMIZER_RESERVE_06 = false
static bool prm_optimizer_reserve_06_default = false
static unsigned int prm_optimizer_reserve_06_flag = 0
bool PRM_OPTIMIZER_RESERVE_07 = false
static bool prm_optimizer_reserve_07_default = false
static unsigned int prm_optimizer_reserve_07_flag = 0
bool PRM_OPTIMIZER_RESERVE_08 = false
static bool prm_optimizer_reserve_08_default = false
static unsigned int prm_optimizer_reserve_08_flag = 0
bool PRM_OPTIMIZER_RESERVE_09 = false
static bool prm_optimizer_reserve_09_default = false
static unsigned int prm_optimizer_reserve_09_flag = 0
bool PRM_OPTIMIZER_RESERVE_10 = false
static bool prm_optimizer_reserve_10_default = false
static unsigned int prm_optimizer_reserve_10_flag = 0
bool PRM_OPTIMIZER_RESERVE_11 = false
static bool prm_optimizer_reserve_11_default = false
static unsigned int prm_optimizer_reserve_11_flag = 0
bool PRM_OPTIMIZER_RESERVE_12 = false
static bool prm_optimizer_reserve_12_default = false
static unsigned int prm_optimizer_reserve_12_flag = 0
bool PRM_OPTIMIZER_RESERVE_13 = false
static bool prm_optimizer_reserve_13_default = false
static unsigned int prm_optimizer_reserve_13_flag = 0
bool PRM_OPTIMIZER_RESERVE_14 = false
static bool prm_optimizer_reserve_14_default = false
static unsigned int prm_optimizer_reserve_14_flag = 0
bool PRM_OPTIMIZER_RESERVE_15 = false
static bool prm_optimizer_reserve_15_default = false
static unsigned int prm_optimizer_reserve_15_flag = 0
bool PRM_OPTIMIZER_RESERVE_16 = false
static bool prm_optimizer_reserve_16_default = false
static unsigned int prm_optimizer_reserve_16_flag = 0
bool PRM_OPTIMIZER_RESERVE_17 = false
static bool prm_optimizer_reserve_17_default = false
static unsigned int prm_optimizer_reserve_17_flag = 0
bool PRM_OPTIMIZER_RESERVE_18 = false
static bool prm_optimizer_reserve_18_default = false
static unsigned int prm_optimizer_reserve_18_flag = 0
bool PRM_OPTIMIZER_RESERVE_19 = false
static bool prm_optimizer_reserve_19_default = false
static unsigned int prm_optimizer_reserve_19_flag = 0
bool PRM_OPTIMIZER_RESERVE_20 = false
static bool prm_optimizer_reserve_20_default = false
static unsigned int prm_optimizer_reserve_20_flag = 0
bool PRM_HA_REPL_ENABLE_SERVER_SIDE_UPDATE = false
static bool prm_ha_repl_enable_server_side_update_default = false
static unsigned int prm_ha_repl_enable_server_side_update_flag = 0
float PRM_PB_LRU_HOT_RATIO = 0.4f
static float prm_pb_lru_hot_ratio_default = 0.4f
static float prm_pb_lru_hot_ratio_upper = 0.90f
static float prm_pb_lru_hot_ratio_lower = 0.05f
static unsigned int prm_pb_lru_hot_ratio_flag = 0
float PRM_PB_LRU_BUFFER_RATIO = 0.05f
static float prm_pb_lru_buffer_ratio_default = 0.05f
static float prm_pb_lru_buffer_ratio_upper = 0.90f
static float prm_pb_lru_buffer_ratio_lower = 0.05f
static unsigned int prm_pb_lru_buffer_ratio_flag = 0
int PRM_VACUUM_MASTER_WAKEUP_INTERVAL = 10
static int prm_vacuum_master_wakeup_interval_default = 10
static int prm_vacuum_master_wakeup_interval_lower = 1
static unsigned int prm_vacuum_master_wakeup_interval_flag = 0
int PRM_VACUUM_LOG_BLOCK_PAGES = VACUUM_LOG_BLOCK_PAGES_DEFAULT
static int prm_vacuum_log_block_pages_default = VACUUM_LOG_BLOCK_PAGES_DEFAULT
static int prm_vacuum_log_block_pages_lower = 4
static int prm_vacuum_log_block_pages_upper = 1024
static unsigned int prm_vacuum_log_block_pages_flag = 0
int PRM_VACUUM_WORKER_COUNT = 10
static int prm_vacuum_worker_count_default = 10
static int prm_vacuum_worker_count_lower = 1
static int prm_vacuum_worker_count_upper = VACUUM_MAX_WORKER_COUNT
static unsigned int prm_vacuum_worker_count_flag = 0
int PRM_ER_LOG_VACUUM = 1
static int prm_er_log_vacuum_default = 1
static unsigned int prm_er_log_vacuum_flag = 0
bool PRM_DISABLE_VACUUM = false
static bool prm_disable_vacuum_default = false
static unsigned int prm_disable_vacuum_flag = 0
bool PRM_LOG_BTREE_OPS = false
static bool prm_log_btree_ops_default = false
static unsigned int prm_log_btree_ops_flag = 0
bool PRM_OBJECT_PRINT_FORMAT_OID = false
static bool prm_object_print_format_oid_default = false
static unsigned int prm_object_print_format_oid_flag = 0
char * PRM_TIMEZONE = NULL
static char * prm_timezone_default = NULL
static unsigned int prm_timezone_flag = 0
char * PRM_SERVER_TIMEZONE = NULL
static char * prm_server_timezone_default = NULL
static unsigned int prm_server_timezone_flag = 0
bool prm_tz_leap_second_support_default = false
bool PRM_TZ_LEAP_SECOND_SUPPORT = false
static unsigned int prm_leap_second_support_flag = 0
bool PRM_OPTIMIZER_ENABLE_AGGREGATE_OPTIMIZATION = true
static bool prm_optimizer_enable_aggregate_optimization_default = true
static unsigned int prm_optimizer_enable_aggregate_optimization_flag = 0
static unsigned int prm_vacuum_prefetch_log_nbuffers_flag = 0
static unsigned int prm_vacuum_prefetch_log_mode_flag = 0
bool PRM_PB_NEIGHBOR_FLUSH_NONDIRTY = false
static unsigned int prm_pb_neighbor_flush_nondirty_flag = 0
static bool prm_pb_neighbor_flush_nondirty_default = false
unsigned int PRM_PB_NEIGHBOR_FLUSH_PAGES = 8
static unsigned int prm_pb_neighbor_flush_pages_flag = 0
static unsigned int prm_pb_neighbor_flush_pages_default = 8
static unsigned int prm_pb_neighbor_flush_pages_upper = 32
static unsigned int prm_pb_neighbor_flush_pages_lower = 0
int * PRM_FAULT_INJECTION_IDS = int_list_initial
static int prm_fault_injection_id_flag = 0
static int * prm_fault_injection_id_default = NULL
int PRM_FAULT_INJECTION_TEST = FI_GROUP_NONE
static int prm_fault_injection_test_flag = 0
static int prm_fault_injection_test_default = FI_GROUP_NONE
static int prm_fault_injection_test_lower = FI_GROUP_NONE
static int prm_fault_injection_test_upper = FI_GROUP_MAX
bool PRM_FAULT_INJECTION_ACTION_PREFER_ABORT_TO_EXIT = true
static unsigned int prm_fault_injection_action_prefer_abort_to_exit_flag = 0
static bool prm_fault_injection_action_prefer_abort_to_exit_default = true
int PRM_HA_REPL_FILTER_TYPE = REPL_FILTER_NONE
static int prm_ha_repl_filter_type_default = REPL_FILTER_NONE
static int prm_ha_repl_filter_type_lower = REPL_FILTER_NONE
static int prm_ha_repl_filter_type_upper = REPL_FILTER_EXCLUDE_TBL
static unsigned int prm_ha_repl_filter_type_flag = 0
const char * PRM_HA_REPL_FILTER_FILE = ""
static const char * prm_ha_repl_filter_file_default = ""
static unsigned int prm_ha_repl_filter_file_flag = 0
bool PRM_COMPENSATE_DEBUG = false
static const bool prm_compensate_debug_default = false
static unsigned int prm_compensate_debug_flag = 0
bool PRM_POSTPONE_DEBUG = false
static const bool prm_postpone_debug_default = false
static unsigned int prm_postpone_debug_flag = 0
bool PRM_CLIENT_CLASS_CACHE_DEBUG = false
static const bool prm_client_class_cache_debug_default = false
static unsigned int prm_client_class_cache_debug_flag = 0
bool PRM_EXAMINE_CLIENT_CACHED_LOCKS = false
static bool prm_examine_client_cached_locks_default = false
static unsigned int prm_examine_client_cached_locks_flag = 0
bool PRM_PB_SEQUENTIAL_VICTIM_FLUSH = true
static bool prm_pb_sequential_victim_flush_default = true
static unsigned int prm_pb_sequential_victim_flush_flag = 0
bool PRM_LOG_UNIQUE_STATS = false
static bool prm_log_unique_stats_default = false
static unsigned int prm_log_unique_stats_flag = 0
bool PRM_LOGPB_LOGGING_DEBUG = false
static bool prm_logpb_logging_debug_default = false
static unsigned int prm_logpb_logging_debug_flag = 0
bool PRM_FORCE_RESTART_TO_SKIP_RECOVERY = false
static bool prm_force_restart_to_skip_recovery_default = false
static unsigned int prm_force_restart_to_skip_recovery_flag = 0
int PRM_EXTENDED_STATISTICS = 15
static int prm_extended_statistics_default = 15
static int prm_extended_statistics_lower = 0
static int prm_extended_statistics_upper = PERFMON_ACTIVATION_FLAG_MAX_VALUE
static unsigned int prm_extended_statistics_flag = 0
bool PRM_ENABLE_STRING_COMPRESSION = true
static bool prm_enable_string_compression_default = true
static unsigned int prm_enable_string_compression_flag = 0
int PRM_XASL_CACHE_TIME_THRESHOLD_IN_MINUTES = 360
static unsigned int prm_xasl_cache_time_threshold_in_minutes_flag = 0
static int prm_xasl_cache_time_threshold_in_minutes_default = 360
static int prm_xasl_cache_time_threshold_in_minutes_upper = INT_MAX
static int prm_xasl_cache_time_threshold_in_minutes_lower = 0
bool PRM_DISK_LOGGING = false
static bool prm_disk_logging_default = false
static unsigned int prm_disk_logging_flag = 0
bool PRM_FILE_LOGGING = false
static bool prm_file_logging_default = false
static unsigned int prm_file_logging_flag = 0
int PRM_PB_NUM_PRIVATE_CHAINS = -1
static int prm_pb_num_private_chains_default = -1
static int prm_pb_num_private_chains_upper = CSS_MAX_CLIENT_COUNT + VACUUM_MAX_WORKER_COUNT
static int prm_pb_num_private_chains_lower = -1
static unsigned int prm_pb_num_private_chains_flag = 0
bool PRM_PB_MONITOR_LOCKS = false
static bool prm_pb_monitor_locks_default = false
static unsigned int prm_pb_monitor_locks_flag = 0
int PRM_CTE_MAX_RECURSIONS = 2000
static int prm_cte_max_recursions_default = 2000
static int prm_cte_max_recursions_upper = 1000000
static int prm_cte_max_recursions_lower = 2
static unsigned int prm_cte_max_recursions_flag = 0
bool PRM_JSON_LOG_ALLOCATIONS = false
static bool prm_json_log_allocations_default = false
static unsigned int prm_json_log_allocations_flag = 0
int PRM_JSON_MAX_ARRAY_IDX = 64 * ONE_K
static int prm_json_max_array_idx_default = 64 * ONE_K
static unsigned int prm_json_max_array_idx_flag = 0
static int prm_json_max_array_idx_upper = ONE_M
static int prm_json_max_array_idx_lower = ONE_K
bool PRM_CONNECTION_LOGGING = false
static bool prm_connection_logging_default = false
static unsigned int prm_connection_logging_flag = 0
int PRM_THREAD_LOGGING_FLAG = 0
static int prm_thread_logging_flag_default = 0
static unsigned int prm_thread_logging_flag_flag = 0
bool PRM_LOG_QUERY_LISTS = false
static bool prm_log_query_lists_default = false
static unsigned int prm_log_query_lists_flag = 0
bool PRM_THREAD_CONNECTION_POOLING = true
static bool prm_thread_connection_pooling_default = true
static unsigned int prm_thread_connection_pooling_flag = 0
int PRM_THREAD_CONNECTION_TIMEOUT_SECONDS = 300
static int prm_thread_connection_timeout_seconds_default = 300
static int prm_thread_connection_timeout_seconds_upper = 60 * 60
static int prm_thread_connection_timeout_seconds_lower = -1
static unsigned int prm_thread_connection_timeout_seconds_flag = 0
bool PRM_THREAD_WORKER_POOLING = true
static bool prm_thread_worker_pooling_default = true
static unsigned int prm_thread_worker_pooling_flag = 0
int PRM_THREAD_WORKER_TIMEOUT_SECONDS = 300
static int prm_thread_worker_timeout_seconds_default = 300
static int prm_thread_worker_timeout_seconds_upper = 60 * 60
static int prm_thread_worker_timeout_seconds_lower = -1
static unsigned int prm_thread_worker_timeout_seconds_flag = 0
unsigned int PRM_DWB_SIZE = 2 * 1024 * 1024
static unsigned int prm_dwb_size_flag = 0
static unsigned int prm_dwb_size_default = (2 * 1024 * 1024)
static unsigned int prm_dwb_size_upper = (32 * 1024 * 1024)
static unsigned int prm_dwb_size_lower = 0
unsigned int PRM_DWB_BLOCKS = 2
static unsigned int prm_dwb_blocks_flag = 0
static unsigned int prm_dwb_blocks_default = 2
static unsigned int prm_dwb_blocks_upper = 32
static unsigned int prm_dwb_blocks_lower = 0
bool PRM_ENABLE_DWB_FLUSH_THREAD = true
static bool prm_enable_dwb_flush_thread_default = true
static unsigned int prm_enable_dwb_flush_thread_flag = 0
bool PRM_DWB_LOGGING = false
static bool prm_dwb_logging_default = false
static unsigned int prm_dwb_logging_flag = 0
int PRM_DATA_FILE_ADVISE = 0
static int prm_data_file_advise_default = 0
static unsigned int prm_data_file_advise_flag = 0
static unsigned int prm_data_file_advise_upper = 6
static unsigned int prm_data_file_advise_lower = 0
bool PRM_DEBUG_LOG_ARCHIVES = false
static bool prm_debug_log_archives_default = false
static unsigned int prm_debug_log_archives_flag = 0
bool PRM_DEBUG_ES = false
static bool prm_debug_es_default = false
static unsigned int prm_debug_es_flag = 0
bool PRM_DEBUG_BESTSPACE = false
static bool prm_debug_bestspace_default = false
static unsigned int prm_debug_bestspace_flag = 0
bool PRM_DEBUG_LOGWR = false
static bool prm_debug_logwr_default = false
static unsigned int prm_debug_logwr_flag = 0
bool PRM_DEBUG_AUTOCOMMIT = false
static bool prm_debug_autocommit_default = false
static unsigned int prm_debug_autocommit_flag = 0
bool PRM_DEBUG_REPLICATION_DATA = false
static bool prm_debug_replication_data_default = false
static unsigned int prm_debug_replication_data_flag = 0
bool PRM_TRACK_REQUESTS = false
static bool prm_track_requests_default = false
static unsigned int prm_track_requests_flag = 0
bool PRM_LOG_PGBUF_VICTIM_FLUSH = false
static bool prm_log_pgbuf_victim_flush_default = false
static unsigned int prm_log_pgbuf_victim_flush_flag = 0
bool PRM_LOG_CHKPT_DETAILED = false
static bool prm_log_chkpt_detailed_default = false
static unsigned int prm_log_chkpt_detailed_flag = 0
UINT64 PRM_IB_TASK_MEMSIZE = 16 * ONE_M
static UINT64 prm_ib_task_memsize_default = 16 * ONE_M
static UINT64 prm_ib_task_memsize_lower = ONE_K
static UINT64 prm_ib_task_memsize_upper = 128 * ONE_M
static unsigned int prm_ib_task_memsize_flag = 0
bool PRM_STATS_ON = false
static bool prm_stats_on_default = false
static unsigned int prm_stats_on_flag = 0
int PRM_LOADDB_WORKERS = 8
static int prm_loaddb_workers_default = 8
static int prm_loaddb_workers_upper = 64
static int prm_loaddb_workers_lower = 2
static unsigned int prm_loaddb_workers_flag = 0
bool PRM_PERF_TEST_MODE = false
static bool prm_perf_test_mode_default = false
static unsigned int prm_perf_test_mode_flag = 0
bool PRM_REPR_CACHE_LOG = false
static bool prm_repr_cache_log_default = false
static unsigned int prm_repr_cache_log_flag = 0
bool PRM_NEW_LFHASH = false
static bool prm_new_lfhash_default = false
static unsigned int prm_new_lfhash_flag = 0
bool PRM_HEAP_INFO_CACHE_LOGGING = false
static bool prm_heap_info_cache_logging_default = false
static unsigned int prm_heap_info_cache_logging_flag = 0
int PRM_TDE_DEFAULT_ALGORITHM = TDE_ALGORITHM_AES
static int prm_tde_default_algorithm = TDE_ALGORITHM_AES
static unsigned int prm_tde_default_algorithm_flag = 0
bool PRM_JAVA_STORED_PROCEDURE = false
static bool prm_java_stored_procedure_default = false
static unsigned int prm_java_stored_procedure_flag = 0
int PRM_JAVA_STORED_PROCEDURE_PORT = 0
static int prm_java_stored_procedure_port_default = 0
static int prm_java_stored_procedure_port_upper = 65535
static int prm_java_stored_procedure_port_lower = 0
static unsigned int prm_java_stored_procedure_port_flag = 0
const char * PRM_JAVA_STORED_PROCEDURE_JVM_OPTIONS = ""
static const char * prm_java_stored_procedure_jvm_options_default = ""
static unsigned int prm_java_stored_procedure_jvm_options_flag = 0
int PRM_JAVA_STORED_PROCEDURE_DEBUG = -1
static int prm_java_stored_procedure_debug_default = -1
static int prm_java_stored_procedure_debug_upper = 65535
static int prm_java_stored_procedure_debug_lower = -1
static unsigned int prm_java_stored_procedure_debug_flag = 0
bool PRM_JAVA_STORED_PROCEDURE_RESERVE_01 = false
static bool prm_java_stored_procedure_reserve_01_default = false
static unsigned int prm_java_stored_procedure_reserve_01_flag = 0
bool PRM_ALLOW_TRUNCATED_STRING = false
static bool prm_allow_truncated_string_default = false
static unsigned int prm_allow_truncated_string_flag = 0
bool PRM_TB_REUSE_OID = true
static bool prm_create_table_reuseoid_default = true
static unsigned int prm_create_table_reuseoid = 0
bool PRM_USE_STAT_ESTIMATION = false
static bool prm_use_stat_estimation_default = false
static unsigned int prm_use_stat_estimation_flag = 0
bool PRM_IGNORE_TRAILING_SPACE = false
static bool prm_ignore_trailing_space_default = false
static unsigned int prm_ignore_trailing_space_flag = 0
bool PRM_DDL_AUDIT_LOG = false
static bool prm_ddl_audit_log_default = false
static unsigned int prm_ddl_audit_log_flag = 0
UINT64 PRM_DDL_AUDIT_LOG_SIZE = 10485760ULL
static UINT64 prm_ddl_audit_log_size_default = 10485760ULL
static UINT64 prm_ddl_audit_log_size_lower = 10485760ULL
static UINT64 prm_ddl_audit_log_size_upper = 2147483648ULL
static unsigned int prm_ddl_audit_log_size_flag = 0
static SYSPRM_PARAM prm_Def []
static int num_session_parameters = 0
static KEYVAL boolean_words []
static KEYVAL er_log_level_words []
static KEYVAL isolation_level_words []
static KEYVAL pgbuf_debug_page_validation_level_words []
static KEYVAL null_words []
static KEYVAL ha_mode_words []
static KEYVAL ha_server_state_words []
static KEYVAL ha_log_applier_state_words []
static KEYVAL compat_words []
static KEYVAL check_peer_alive_words []
static KEYVAL query_trace_format_words []
static KEYVAL fi_test_words []
static KEYVAL ha_repl_filter_type_words []
static KEYVAL tde_algorithm_words []
static const char * compat_mode_values_PRM_ANSI_QUOTES [COMPAT_ORACLE+2]
static const char * compat_mode_values_PRM_ORACLE_STYLE_EMPTY_STRING [COMPAT_ORACLE+2]
static const char * compat_mode_values_PRM_ORACLE_STYLE_OUTERJOIN [COMPAT_ORACLE+2]
static const char * compat_mode_values_PRM_PIPES_AS_CONCAT [COMPAT_ORACLE+2]
static const char * compat_mode_values_PRM_MYSQL_TRIGGER_CORRELATION_NAMES [COMPAT_ORACLE+2]
static const char * compat_mode_values_PRM_REQUIRE_LIKE_ESCAPE_CHARACTER [COMPAT_ORACLE+2]
static const char * compat_mode_values_PRM_NO_BACKSLASH_ESCAPES [COMPAT_ORACLE+2]
static const char * compat_mode_values_PRM_ADD_COLUMN_UPDATE_HARD_DEFAULT [COMPAT_ORACLE+2]
static const char * compat_mode_values_PRM_RETURN_NULL_ON_FUNCTION_ERRORS [COMPAT_ORACLE+2]
static const char * compat_mode_values_PRM_PLUS_AS_CONCAT [COMPAT_ORACLE+2]
static const char ** compat_mode_values []
static const int call_stack_dump_error_codes []
struct {
char * conf_path
char * db_name
} prm_Files_loaded [MAX_NUM_OF_PRM_FILES_LOADED]
Macro Definition Documentation
#define CSS_MAX_CLIENT_COUNT 4000
Definition at line 1124 of file system_parameter.c.
#define ER_LOG_FILE_DIR "server"
Definition at line 96 of file system_parameter.c.
Referenced by sysprm_set_er_log_file().
#define GET_PRM (id) (&prm_Def[(id)])
Definition at line 6045 of file system_parameter.c.
Referenced by sysprm_change_parameter_values(), sysprm_final(), sysprm_get_session_parameters_count(), sysprm_load_and_init_internal(), sysprm_print_parameters_for_ha_repl(), sysprm_print_parameters_for_qry_string(), sysprm_print_sysprm_value(), sysprm_set_sysprm_value_from_parameter(), sysprm_validate_escape_char_parameters(), xsysprm_get_force_server_parameters(), and xsysprm_obtain_server_parameters().
#define GET_PRM_DATATYPE (id) ((GET_PRM (id))->datatype)
Definition at line 6048 of file system_parameter.c.
Referenced by sysprm_free_assign_values(), sysprm_pack_assign_values(), sysprm_packed_assign_values_length(), and sysprm_unpack_assign_values().
#define GET_PRM_DYNAMIC_FLAG (id) ((GET_PRM (id))->dynamic_flag)
Definition at line 6047 of file system_parameter.c.
Referenced by sysprm_print_parameters_for_ha_repl().
#define GET_PRM_STATIC_FLAG (id) ((GET_PRM (id))->static_flag)
Definition at line 6046 of file system_parameter.c.
Referenced by sysprm_print_parameters_for_ha_repl().
#define LOGPB_BUFFER_NPAGES_LOWER 128
Definition at line 1040 of file system_parameter.c.
#define MAX_NUM_OF_PRM_FILES_LOADED 10
Definition at line 6409 of file system_parameter.c.
Referenced by prm_file_has_been_loaded(), sysprm_dump_parameters(), and sysprm_final().
#define NUM_PRM ((int)(sizeof(prm_Def)/sizeof(prm_Def[0])))
Definition at line 6042 of file system_parameter.c.
Referenced by prm_check_environment(), sysprm_dump_parameters(), sysprm_final(), sysprm_load_and_init_internal(), sysprm_print_parameters_for_ha_repl(), sysprm_print_parameters_for_qry_string(), and xsysprm_get_force_server_parameters().
#define NUM_SESSION_PRM num_session_parameters
Definition at line 6062 of file system_parameter.c.
Referenced by sysprm_alloc_session_parameters(), sysprm_free_session_parameters(), sysprm_get_id(), sysprm_get_session_parameters_count(), sysprm_pack_session_parameters(), sysprm_packed_session_parameters_length(), sysprm_set_sysprm_value_from_parameter(), and sysprm_unpack_session_parameters().
#define PARAM_MSG_FMT (msgid) msgcat_message (MSGCAT_CATALOG_CUBRID, MSGCAT_SET_PARAMETERS, (msgid))
Definition at line 6043 of file system_parameter.c.
Referenced by prm_report_bad_entry().
#define PRM_ADJUST_FOR_GET_BIGINT_TO_BIGINT (prm, out_val, in_val, err)
Value:
do \
    { \
      assert ((prm) != NULL && (out_val) != NULL && (in_val) != NULL); \
      assert (sizeof (*(out_val)) == sizeof (UINT64));\
      assert (sizeof (*(in_val)) == sizeof (UINT64)); \
      *(err) = (SYSPRM_ERR) (*((prm)->get_dup)) ((void *) (out_val), PRM_BIGINT, (void *) (in_val), PRM_BIGINT); \
    } \
  while (0)
Definition at line 902 of file system_parameter.c.
Referenced by prm_print(), sysprm_get_param_range(), and sysprm_print_sysprm_value().
#define PRM_ADJUST_FOR_GET_FLOAT_TO_BIGINT (prm, out_val, in_val, err)
Value:
do \
    { \
      assert ((prm) != NULL && (out_val) != NULL && (in_val) != NULL); \
      assert (sizeof (*(out_val)) == sizeof (UINT64)); \
      assert (sizeof (*(in_val)) == sizeof (float)); \
      *(err) = (SYSPRM_ERR) (*((prm)->get_dup)) ((void *) (out_val), PRM_BIGINT, (void *) (in_val), PRM_FLOAT); \
    } \
  while (0)
Definition at line 872 of file system_parameter.c.
Referenced by prm_print(), and sysprm_print_sysprm_value().
#define PRM_ADJUST_FOR_GET_FLOAT_TO_FLOAT (prm, out_val, in_val, err)
Value:
do \
    { \
      assert ((prm) != NULL && (out_val) != NULL && (in_val) != NULL); \
      assert (sizeof (*(out_val)) == sizeof (float)); \
      assert (sizeof (*(in_val)) == sizeof (float)); \
      *(err) = (SYSPRM_ERR) (*((prm)->get_dup)) ((void *) (out_val), PRM_FLOAT, (void *) (in_val), PRM_FLOAT); \
    } \
  while (0)
Definition at line 892 of file system_parameter.c.
Referenced by prm_print(), sysprm_get_param_range(), and sysprm_print_sysprm_value().
#define PRM_ADJUST_FOR_GET_INTEGER_TO_BIGINT (prm, out_val, in_val, err)
Value:
do \
    { \
      assert ((prm) != NULL && (out_val) != NULL && (in_val) != NULL); \
      assert (sizeof (*(out_val)) == sizeof (UINT64)); \
      assert (sizeof (*(in_val)) == sizeof (int)); \
      *(err) = (SYSPRM_ERR) (*((prm)->get_dup)) ((void *) (out_val), PRM_BIGINT, (void *) (in_val), PRM_INTEGER); \
    } \
  while (0)
Definition at line 862 of file system_parameter.c.
Referenced by prm_print(), and sysprm_print_sysprm_value().
#define PRM_ADJUST_FOR_GET_INTEGER_TO_INTEGER (prm, out_val, in_val, err)
Value:
do \
    { \
      assert ((prm) != NULL && (out_val) != NULL && (in_val) != NULL);\
      assert (sizeof (*(out_val)) == sizeof (int)); \
      assert (sizeof (*(in_val)) == sizeof (int)); \
      *(err) = (SYSPRM_ERR) (*((prm)->get_dup)) ((void *) (out_val), PRM_INTEGER, (void *) (in_val), PRM_INTEGER); \
    } \
  while (0)
Definition at line 882 of file system_parameter.c.
Referenced by prm_print(), sysprm_get_param_range(), and sysprm_print_sysprm_value().
#define PRM_ADJUST_FOR_SET_BIGINT_TO_BIGINT (prm, out_val, in_val, err)
Value:
do \
    { \
      assert ((prm) != NULL && (out_val) != NULL && (in_val) != NULL); \
      assert (sizeof (*(out_val)) == sizeof (UINT64)); \
      assert (sizeof (*(in_val)) == sizeof (UINT64)); \
      *(err) = (*((prm)->set_dup)) ((void *) (out_val), PRM_BIGINT, (void *) (in_val), PRM_BIGINT); \
    } \
  while (0)
Definition at line 852 of file system_parameter.c.
Referenced by prm_check_range(), and sysprm_generate_new_value().
#define PRM_ADJUST_FOR_SET_BIGINT_TO_FLOAT (prm, out_val, in_val, err)
Value:
do \
    { \
      assert ((prm) != NULL && (out_val) != NULL && (in_val) != NULL); \
      assert (sizeof (*(out_val)) == sizeof (float)); \
      assert (sizeof (*(in_val)) == sizeof (UINT64)); \
      *(err) = (SYSPRM_ERR) (*((prm)->set_dup)) ((void *) (out_val), PRM_FLOAT, (void *) (in_val), PRM_BIGINT); \
    } \
  while (0)
Definition at line 822 of file system_parameter.c.
Referenced by prm_check_range(), and sysprm_generate_new_value().
#define PRM_ADJUST_FOR_SET_BIGINT_TO_INTEGER (prm, out_val, in_val, err)
Value:
do \
    { \
      assert ((prm) != NULL && (out_val) != NULL && (in_val) != NULL); \
      assert (sizeof (*(out_val)) == sizeof (int)); \
      assert (sizeof (*(in_val)) == sizeof (UINT64)); \
      *(err) = (SYSPRM_ERR) (*((prm)->set_dup)) ((void *) (out_val), PRM_INTEGER, (void *) (in_val), PRM_BIGINT); \
    } \
  while (0)
Definition at line 812 of file system_parameter.c.
Referenced by prm_check_range(), and sysprm_generate_new_value().
#define PRM_ADJUST_FOR_SET_FLOAT_TO_FLOAT (prm, out_val, in_val, err)
Value:
do \
    { \
      assert ((prm) != NULL && (out_val) != NULL && (in_val) != NULL); \
      assert (sizeof (*(out_val)) == sizeof (float)); \
      assert (sizeof (*(in_val)) == sizeof (float)); \
      *(err) = (SYSPRM_ERR) (*((prm)->set_dup)) ((void *) (out_val), PRM_FLOAT, (void *) (in_val), PRM_FLOAT); \
    } \
  while (0)
Definition at line 842 of file system_parameter.c.
Referenced by prm_check_range(), and sysprm_generate_new_value().
#define PRM_ADJUST_FOR_SET_INTEGER_TO_INTEGER (prm, out_val, in_val, err)
Value:
do \
    { \
      assert ((prm) != NULL && (out_val) != NULL && (in_val) != NULL); \
      assert (sizeof (*(out_val)) == sizeof (int)); \
      assert (sizeof (*(in_val)) == sizeof (int)); \
      *(err) = (SYSPRM_ERR) (*((prm)->set_dup)) ((void *) (out_val), PRM_INTEGER, (void *) (in_val), PRM_INTEGER);\
    } \
  while (0)
Definition at line 832 of file system_parameter.c.
Referenced by prm_check_range(), and sysprm_generate_new_value().
#define PRM_ALLOCATED 0x00000002 /* storage has been malloc'd */
Definition at line 745 of file system_parameter.c.
Referenced by prm_set_default(), prm_set_integer_list_value(), prm_set_string_value(), sysprm_final(), sysprm_get_id(), sysprm_update_flag_allocated(), and sysprm_update_session_prm_flag_allocated().
#define PRM_CLEAR_BIT (this, here) (here &= ~this)
Definition at line 794 of file system_parameter.c.
Referenced by prm_set_default(), prm_set_integer_list_value(), prm_set_string_value(), sysprm_final(), sysprm_get_id(), sysprm_set_value(), sysprm_update_flag_allocated(), sysprm_update_flag_different(), and sysprm_update_session_prm_flag_allocated().
#define PRM_CLIENT_SESSION
Value:
0x00000800  /* mark those client/server session parameters that should not affect the
                     * server */
Definition at line 727 of file system_parameter.c.
#define PRM_CLIENT_SESSION_ONLY (x) (x & PRM_CLIENT_SESSION)
Definition at line 776 of file system_parameter.c.
Referenced by sysprm_load_and_init_internal().
#define PRM_COMPOUND 0x00000020 /* sets the value of several others */
Definition at line 719 of file system_parameter.c.
#define PRM_DEFAULT_BUFFER_SIZE 256
Definition at line 914 of file system_parameter.c.
Referenced by prm_check_environment(), prm_print(), and sysprm_print_sysprm_value().
#define PRM_DEFAULT_USED 0x00000004 /* Default value has been used */
Definition at line 746 of file system_parameter.c.
Referenced by prm_set_default(), sysprm_final(), and sysprm_set_value().
#define PRM_DEFAULT_VAL_USED (x) (x & PRM_DEFAULT_USED)
Definition at line 787 of file system_parameter.c.
Referenced by prm_tune_parameters(), and sysprm_final().
#define PRM_DEPRECATED 0x40000000 /* is deprecated */
Definition at line 738 of file system_parameter.c.
#define PRM_DIFFER_UNIT 0x00004000 /* parameter unit need to be changed */
Definition at line 731 of file system_parameter.c.
#define PRM_DIFFERENT
Value:
0x00000008  /* mark those parameters that have values different than their default.
                     * currently used by parameters that should be printed to query string */
Definition at line 747 of file system_parameter.c.
Referenced by prm_set_default(), and sysprm_update_flag_different().
#define PRM_DIFFERENT_UNIT (x) (x & PRM_DIFFER_UNIT)
Definition at line 779 of file system_parameter.c.
Referenced by prm_check_range(), prm_print(), sysprm_generate_new_value(), sysprm_get_param_range(), sysprm_get_range(), and sysprm_print_sysprm_value().
#define PRM_EMPTY_FLAG 0x00000000 /* empty flag */
Definition at line 713 of file system_parameter.c.
#define PRM_FOR_CLIENT 0x00000002 /* is for client parameter */
Definition at line 715 of file system_parameter.c.
#define PRM_FOR_HA 0x00000080 /* is for heartbeat */
Definition at line 721 of file system_parameter.c.
#define PRM_FOR_HA_CONTEXT 0x00008000 /* should be replicated into HA log applier */
Definition at line 732 of file system_parameter.c.
#define PRM_FOR_QRY_STRING
Value:
0x00000400  /* if a parameter can affect the plan generation it should be included in the
                     * query string */
Definition at line 725 of file system_parameter.c.
Referenced by prm_tune_parameters(), and sysprm_final().
#define PRM_FOR_SERVER 0x00000004 /* is for server parameter */
Definition at line 716 of file system_parameter.c.
#define PRM_FOR_SESSION
Value:
0x00000100  /* is a session parameter - all client or client/server parameters that can be
                     * changed on-line */
Definition at line 722 of file system_parameter.c.
#define PRM_FORCE_SERVER 0x00000200 /* client should get value from server */
Definition at line 724 of file system_parameter.c.
#define PRM_GET_BIGINT (x) (*((UINT64 *) (x)))
Definition at line 806 of file system_parameter.c.
Referenced by prm_check_range(), prm_get_bigint_value(), prm_print(), prm_set_bigint_value(), prm_set_default(), sysprm_compare_values(), sysprm_generate_new_value(), sysprm_get_id(), sysprm_get_param_range(), and sysprm_set_sysprm_value_from_parameter().
#define PRM_GET_BOOL (x) (*((bool *) (x)))
Definition at line 804 of file system_parameter.c.
Referenced by prm_get_bool_value(), prm_print(), prm_set_bool_value(), prm_set_default(), prm_tune_parameters(), sysprm_compare_values(), sysprm_final(), sysprm_generate_new_value(), sysprm_get_id(), sysprm_set_sysprm_value_from_parameter(), and sysprm_validate_escape_char_parameters().
#define PRM_GET_FLOAT (x) (*((float *) (x)))
Definition at line 802 of file system_parameter.c.
Referenced by prm_check_range(), prm_get_float_value(), prm_print(), prm_set_default(), prm_set_float_value(), sysprm_compare_values(), sysprm_generate_new_value(), sysprm_get_id(), sysprm_get_param_range(), and sysprm_set_sysprm_value_from_parameter().
#define PRM_GET_FROM_SERVER (x) (x & PRM_FORCE_SERVER)
Definition at line 774 of file system_parameter.c.
Referenced by xsysprm_get_force_server_parameters().
#define PRM_GET_INT (x) (*((int *) (x)))
Definition at line 801 of file system_parameter.c.
Referenced by prm_check_range(), prm_get_integer_value(), prm_print(), prm_set_default(), prm_set_integer_value(), prm_tune_parameters(), sysprm_compare_values(), sysprm_final(), sysprm_generate_new_value(), sysprm_get_id(), sysprm_get_param_range(), and sysprm_set_sysprm_value_from_parameter().
#define PRM_GET_INTEGER_LIST (x) (*((int **) (x)))
Definition at line 805 of file system_parameter.c.
Referenced by prm_get_integer_list_value(), prm_print(), prm_set_default(), prm_set_integer_list_value(), sysprm_compare_values(), sysprm_final(), sysprm_generate_new_value(), sysprm_get_id(), sysprm_set_sysprm_value_from_parameter(), and sysprm_update_flag_allocated().
#define PRM_GET_SERVER
Value:
0x00010000  /* return the value of server parameter from client/server parameter. Note that
                     * this flag only can be set if the parameter has PRM_FOR_CLIENT,
                     * PRM_FOR_SERVER, and PRM_USER_CHANGE flags. */
Definition at line 734 of file system_parameter.c.
#define PRM_GET_STRING (x) (*((char **) (x)))
Definition at line 803 of file system_parameter.c.
Referenced by prm_get_string_value(), prm_print(), prm_set_default(), prm_set_force(), prm_set_string_value(), sysprm_compare_values(), sysprm_final(), sysprm_generate_new_value(), sysprm_get_id(), sysprm_set_sysprm_value_from_parameter(), and sysprm_update_flag_allocated().
#define PRM_HAS_SIZE_UNIT (x) (x & PRM_SIZE_UNIT)
Definition at line 777 of file system_parameter.c.
Referenced by prm_check_range(), prm_print(), sysprm_generate_new_value(), and sysprm_print_sysprm_value().
#define PRM_HAS_TIME_UNIT (x) (x & PRM_TIME_UNIT)
Definition at line 778 of file system_parameter.c.
Referenced by prm_check_range(), prm_print(), sysprm_generate_new_value(), and sysprm_print_sysprm_value().
#define PRM_HIDDEN 0x00000008 /* is hidden */
Definition at line 717 of file system_parameter.c.
#define PRM_IS_ALLOCATED (x) (x & PRM_ALLOCATED)
Definition at line 786 of file system_parameter.c.
Referenced by prm_set_default(), prm_set_integer_list_value(), prm_set_string_value(), sysprm_final(), and sysprm_get_id().
#define PRM_IS_BIGINT (x) ((x)->datatype == PRM_BIGINT)
Definition at line 759 of file system_parameter.c.
Referenced by prm_check_range(), prm_get_bigint_value(), prm_print(), prm_set_bigint_value(), prm_set_default(), sysprm_get_param_range(), and sysprm_print_sysprm_value().
#define PRM_IS_BOOLEAN (x) ((x)->datatype == PRM_BOOLEAN)
Definition at line 756 of file system_parameter.c.
Referenced by prm_get_bool_value(), prm_print(), prm_set_bool_value(), prm_set_default(), and sysprm_print_sysprm_value().
#define PRM_IS_COMPOUND (x) (x & PRM_COMPOUND)
Definition at line 770 of file system_parameter.c.
Referenced by prm_compound_has_changed(), and sysprm_set_value().
#define PRM_IS_DEPRECATED (x) (x & PRM_DEPRECATED)
Definition at line 782 of file system_parameter.c.
Referenced by prm_load_by_section().
#define PRM_IS_DIFFERENT (x) (x & PRM_DIFFERENT)
Definition at line 788 of file system_parameter.c.
Referenced by sysprm_print_parameters_for_ha_repl().
#define PRM_IS_FLOAT (x) ((x)->datatype == PRM_FLOAT)
Definition at line 755 of file system_parameter.c.
Referenced by prm_check_range(), prm_get_float_value(), prm_print(), prm_set_default(), prm_set_float_value(), sysprm_get_param_range(), and sysprm_print_sysprm_value().
#define PRM_IS_FOR_CLIENT (x) (x & PRM_FOR_CLIENT)
Definition at line 766 of file system_parameter.c.
Referenced by prm_load_by_section(), sysprm_change_parameter_values(), sysprm_generate_new_value(), sysprm_load_and_init_internal(), sysprm_obtain_parameters(), and xsysprm_obtain_server_parameters().
#define PRM_IS_FOR_HA (x) (x & PRM_FOR_HA)
Definition at line 772 of file system_parameter.c.
Referenced by prm_load_by_section().
#define PRM_IS_FOR_HA_CONTEXT (x) (x & PRM_FOR_HA_CONTEXT)
Definition at line 780 of file system_parameter.c.
Referenced by sysprm_print_parameters_for_ha_repl(), and sysprm_update_flag_different().
#define PRM_IS_FOR_QRY_STRING (x) (x & PRM_FOR_QRY_STRING)
Definition at line 775 of file system_parameter.c.
Referenced by prm_set_default(), and sysprm_update_flag_different().
#define PRM_IS_FOR_SERVER (x) (x & PRM_FOR_SERVER)
Definition at line 767 of file system_parameter.c.
Referenced by prm_load_by_section(), sysprm_change_parameter_values(), sysprm_generate_new_value(), sysprm_load_and_init_internal(), sysprm_obtain_parameters(), and xsysprm_obtain_server_parameters().
#define PRM_IS_FOR_SESSION (x) (x & PRM_FOR_SESSION)
Definition at line 773 of file system_parameter.c.
Referenced by prm_set_default(), sysprm_change_parameter_values(), sysprm_generate_new_value(), sysprm_load_and_init_internal(), and sysprm_set_value().
#define PRM_IS_GET_SERVER (x) (x & PRM_GET_SERVER)
Definition at line 781 of file system_parameter.c.
Referenced by sysprm_load_and_init_internal(), sysprm_obtain_parameters(), and xsysprm_obtain_server_parameters().
#define PRM_IS_HIDDEN (x) (x & PRM_HIDDEN)
Definition at line 768 of file system_parameter.c.
Referenced by sysprm_dump_parameters(), and sysprm_load_and_init_internal().
#define PRM_IS_INTEGER (x) ((x)->datatype == PRM_INTEGER)
Definition at line 754 of file system_parameter.c.
Referenced by prm_check_range(), prm_get_integer_value(), prm_print(), prm_set_compound(), prm_set_default(), prm_set_integer_value(), sysprm_get_param_range(), and sysprm_print_sysprm_value().
#define PRM_IS_INTEGER_LIST (x) ((x)->datatype == PRM_INTEGER_LIST)
Definition at line 758 of file system_parameter.c.
Referenced by prm_get_integer_list_value(), prm_print(), prm_set_default(), prm_set_integer_list_value(), and sysprm_print_sysprm_value().
#define PRM_IS_KEYWORD (x) ((x)->datatype == PRM_KEYWORD)
Definition at line 757 of file system_parameter.c.
Referenced by prm_check_range(), prm_get_integer_value(), prm_print(), prm_set_compound(), prm_set_default(), prm_set_integer_value(), and sysprm_print_sysprm_value().
#define PRM_IS_OBSOLETED (x) (x & PRM_OBSOLETED)
Definition at line 783 of file system_parameter.c.
Referenced by prm_load_by_section(), sysprm_dump_parameters(), and sysprm_load_and_init_internal().
#define PRM_IS_RELOADABLE (x) (x & PRM_RELOADABLE)
Definition at line 769 of file system_parameter.c.
Referenced by prm_load_by_section(), and sysprm_load_and_init_internal().
#define PRM_IS_SET (x) (x & PRM_SET)
Definition at line 785 of file system_parameter.c.
Referenced by sysprm_final(), sysprm_init_intl_param(), sysprm_load_and_init_internal(), and sysprm_set_er_log_file().
#define PRM_IS_STRING (x) ((x)->datatype == PRM_STRING)
Definition at line 753 of file system_parameter.c.
Referenced by prm_get_string_value(), prm_print(), prm_set_default(), prm_set_string_value(), and sysprm_print_sysprm_value().
#define PRM_NAME_ACCESS_IP_CONTROL "access_ip_control"
Definition at line 504 of file system_parameter.c.
#define PRM_NAME_ACCESS_IP_CONTROL_FILE "access_ip_control_file"
Definition at line 506 of file system_parameter.c.
#define PRM_NAME_ADAPTIVE_FLUSH_CONTROL "adaptive_flush_control"
Definition at line 248 of file system_parameter.c.
#define PRM_NAME_ADD_COLUMN_UPDATE_HARD_DEFAULT "add_column_update_hard_default"
Definition at line 284 of file system_parameter.c.
#define PRM_NAME_AGG_HASH_RESPECT_ORDER "agg_hash_respect_order"
Definition at line 551 of file system_parameter.c.
#define PRM_NAME_ALLOW_TRUNCATED_STRING "allow_truncated_string"
Definition at line 416 of file system_parameter.c.
#define PRM_NAME_ALTER_TABLE_CHANGE_TYPE_STRICT "alter_table_change_type_strict"
Definition at line 290 of file system_parameter.c.
#define PRM_NAME_ANSI_QUOTES "ansi_quotes"
Definition at line 264 of file system_parameter.c.
#define PRM_NAME_AUTO_RESTART_SERVER "auto_restart_server"
Definition at line 312 of file system_parameter.c.
Referenced by sysprm_final().
#define PRM_NAME_BLOCK_DDL_STATEMENT "block_ddl_statement"
Definition at line 436 of file system_parameter.c.
#define PRM_NAME_BLOCK_NOWHERE_STATEMENT "block_nowhere_statement"
Definition at line 434 of file system_parameter.c.
#define PRM_NAME_BOSR_MAXTMP_PAGES "temp_file_max_size_in_pages"
Definition at line 147 of file system_parameter.c.
#define PRM_NAME_BT_INDEX_SCAN_OID_ORDER "index_scan_in_oid_order"
Definition at line 145 of file system_parameter.c.
#define PRM_NAME_BT_OID_BUFFER_SIZE "index_scan_oid_buffer_size"
Definition at line 143 of file system_parameter.c.
#define PRM_NAME_BT_OID_NBUFFERS "index_scan_oid_buffer_pages"
Definition at line 141 of file system_parameter.c.
#define PRM_NAME_BT_UNFILL_FACTOR "index_unfill_factor"
Definition at line 139 of file system_parameter.c.
#define PRM_NAME_CALL_STACK_DUMP_ACTIVATION "call_stack_dump_activation_list"
Definition at line 304 of file system_parameter.c.
#define PRM_NAME_CALL_STACK_DUMP_DEACTIVATION "call_stack_dump_deactivation_list"
Definition at line 306 of file system_parameter.c.
#define PRM_NAME_CALL_STACK_DUMP_ON_ERROR "call_stack_dump_on_error"
Definition at line 302 of file system_parameter.c.
#define PRM_NAME_CFG_DB_HOSTS "db_hosts"
Definition at line 208 of file system_parameter.c.
#define PRM_NAME_CHECK_PEER_ALIVE "check_peer_alive"
Definition at line 522 of file system_parameter.c.
Referenced by prm_print(), sysprm_generate_new_value(), and sysprm_print_sysprm_value().
#define PRM_NAME_CLIENT_CLASS_CACHE_DEBUG "client_class_cache_debug"
Definition at line 619 of file system_parameter.c.
#define PRM_NAME_COMMIT_ON_SHUTDOWN "commit_on_shutdown"
Definition at line 184 of file system_parameter.c.
#define PRM_NAME_COMPACTDB_PAGE_RECLAIM_ONLY "compactdb_page_reclaim_only"
Definition at line 292 of file system_parameter.c.
#define PRM_NAME_COMPAT_MODE "compat_mode"
Definition at line 262 of file system_parameter.c.
Referenced by prm_print(), sysprm_generate_new_value(), and sysprm_print_sysprm_value().
#define PRM_NAME_COMPAT_NUMERIC_DIVISION_SCALE "compat_numeric_division_scale"
Definition at line 308 of file system_parameter.c.
#define PRM_NAME_COMPAT_PRIMARY_KEY "compat_primary_key"
Definition at line 418 of file system_parameter.c.
#define PRM_NAME_COMPENSATE_DEBUG "compensate_debug"
Definition at line 616 of file system_parameter.c.
#define PRM_NAME_CONNECTION_LOGGING "connection_logging"
Definition at line 654 of file system_parameter.c.
#define PRM_NAME_CSQL_AUTO_COMMIT "csql_auto_commit"
Definition at line 188 of file system_parameter.c.
#define PRM_NAME_CSQL_HISTORY_NUM "csql_history_num"
Definition at line 440 of file system_parameter.c.
#define PRM_NAME_CSQL_SINGLE_LINE_MODE "csql_single_line_mode"
Definition at line 458 of file system_parameter.c.
#define PRM_NAME_CSS_MAX_CLIENTS "max_clients"
Definition at line 204 of file system_parameter.c.
Referenced by sysprm_final().
#define PRM_NAME_CTE_MAX_RECURSIONS "cte_max_recursions"
Definition at line 644 of file system_parameter.c.
#define PRM_NAME_DATA_FILE_ADVISE "data_file_os_advise"
Definition at line 665 of file system_parameter.c.
#define PRM_NAME_DB_VOLUME_SIZE "db_volume_size"
Definition at line 508 of file system_parameter.c.
#define PRM_NAME_DBFILES_PROTECT "dbfiles_protect"
Definition at line 310 of file system_parameter.c.
#define PRM_NAME_DDL_AUDIT_LOG "ddl_audit_log"
Definition at line 692 of file system_parameter.c.
#define PRM_NAME_DDL_AUDIT_LOG_SIZE "ddl_audit_log_size"
Definition at line 693 of file system_parameter.c.
#define PRM_NAME_DEBUG_AUTOCOMMIT "debug_autocommit"
Definition at line 671 of file system_parameter.c.
#define PRM_NAME_DEBUG_BESTSPACE "debug_heap_bestspace"
Definition at line 669 of file system_parameter.c.
#define PRM_NAME_DEBUG_ES "debug_external_storage"
Definition at line 668 of file system_parameter.c.
#define PRM_NAME_DEBUG_LOG_ARCHIVES "debug_log_archives"
Definition at line 667 of file system_parameter.c.
#define PRM_NAME_DEBUG_LOG_WRITER "debug_log_writer"
Definition at line 670 of file system_parameter.c.
#define PRM_NAME_DEBUG_REPLICATION_DATA "debug_replication_data"
Definition at line 672 of file system_parameter.c.
#define PRM_NAME_DEFAULT_WEEK_FORMAT "default_week_format"
Definition at line 266 of file system_parameter.c.
#define PRM_NAME_DISABLE_VACUUM "vacuum_disable"
Definition at line 586 of file system_parameter.c.
#define PRM_NAME_DISK_LOGGING "disk_logging_debug"
Definition at line 637 of file system_parameter.c.
#define PRM_NAME_DL_FORK "dl_fork"
Definition at line 444 of file system_parameter.c.
#define PRM_NAME_DONT_REUSE_HEAP_FILE "dont_reuse_heap_file"
Definition at line 230 of file system_parameter.c.
#define PRM_NAME_DWB_BLOCKS "double_write_buffer_blocks"
Definition at line 647 of file system_parameter.c.
#define PRM_NAME_DWB_LOGGING "double_write_buffer_logging"
Definition at line 649 of file system_parameter.c.
#define PRM_NAME_DWB_SIZE "double_write_buffer_size"
Definition at line 646 of file system_parameter.c.
#define PRM_NAME_ENABLE_DWB_FLUSH_THREAD "double_write_buffer_enable_flush_thread"
Definition at line 648 of file system_parameter.c.
#define PRM_NAME_ENABLE_HISTO "communication_histogram"
Definition at line 238 of file system_parameter.c.
#define PRM_NAME_ENABLE_NEW_LFHASH "new_lfhash"
Definition at line 681 of file system_parameter.c.
#define PRM_NAME_ENABLE_STRING_COMPRESSION "enable_string_compression"
Definition at line 631 of file system_parameter.c.
#define PRM_NAME_ER_BTREE_DEBUG "er_btree_debug"
Definition at line 111 of file system_parameter.c.
#define PRM_NAME_ER_EXIT_ASK "inquire_on_exit"
Definition at line 117 of file system_parameter.c.
#define PRM_NAME_ER_LOG_DEBUG "er_log_debug"
Definition at line 109 of file system_parameter.c.
#define PRM_NAME_ER_LOG_FILE "error_log"
Definition at line 121 of file system_parameter.c.
Referenced by sysprm_set_er_log_file().
#define PRM_NAME_ER_LOG_LEVEL "error_log_level"
Definition at line 113 of file system_parameter.c.
Referenced by prm_print(), sysprm_generate_new_value(), and sysprm_print_sysprm_value().
#define PRM_NAME_ER_LOG_SIZE "error_log_size"
Definition at line 119 of file system_parameter.c.
#define PRM_NAME_ER_LOG_VACUUM "er_log_vacuum"
Definition at line 590 of file system_parameter.c.
#define PRM_NAME_ER_LOG_WARNING "error_log_warning"
Definition at line 115 of file system_parameter.c.
#define PRM_NAME_ER_PRODUCTION_MODE "error_log_production_mode"
Definition at line 446 of file system_parameter.c.
#define PRM_NAME_ER_STOP_ON_ERROR "stop_on_error"
Definition at line 448 of file system_parameter.c.
#define PRM_NAME_EVENT_ACTIVATION "event_activation_list"
Definition at line 488 of file system_parameter.c.
#define PRM_NAME_EVENT_HANDLER "event_handler"
Definition at line 486 of file system_parameter.c.
#define PRM_NAME_EXAMINE_CLIENT_CACHED_LOCKS "examine_client_cached_locks"
Definition at line 621 of file system_parameter.c.
#define PRM_NAME_EXTENDED_STATISTICS_ACTIVATION "extended_statistics_activation"
Definition at line 635 of file system_parameter.c.
#define PRM_NAME_FAULT_INJECTION_ACTION_PREFER_ABORT_TO_EXIT "fault_injection_action_prefer_abort_to_exit"
Definition at line 611 of file system_parameter.c.
#define PRM_NAME_FAULT_INJECTION_IDS "fault_injection_ids"
Definition at line 609 of file system_parameter.c.
#define PRM_NAME_FAULT_INJECTION_TEST "fault_injection_test"
Definition at line 610 of file system_parameter.c.
Referenced by prm_print(), sysprm_generate_new_value(), and sysprm_print_sysprm_value().
#define PRM_NAME_FILE_LOGGING "file_logging_debug"
Definition at line 638 of file system_parameter.c.
#define PRM_NAME_FILTER_PRED_MAX_CACHE_CLONES "max_filter_pred_cache_clones"
Definition at line 320 of file system_parameter.c.
#define PRM_NAME_FILTER_PRED_MAX_CACHE_ENTRIES "max_filter_pred_cache_entries"
Definition at line 319 of file system_parameter.c.
#define PRM_NAME_FORCE_REMOVE_LOG_ARCHIVES "force_remove_log_archives"
Definition at line 464 of file system_parameter.c.
Referenced by sysprm_final().
#define PRM_NAME_FORCE_RESTART_TO_SKIP_RECOVERY "force_restart_to_skip_recovery"
Definition at line 629 of file system_parameter.c.
#define PRM_NAME_GC_ENABLE "garbage_collection"
Definition at line 194 of file system_parameter.c.
#define PRM_NAME_GENERAL_RESERVE_01 "general_reserve_01"
Definition at line 685 of file system_parameter.c.
#define PRM_NAME_GENERIC_VOL_PREALLOC_SIZE "generic_vol_prealloc_size"
Definition at line 534 of file system_parameter.c.
#define PRM_NAME_GROUP_CONCAT_MAX_LEN "group_concat_max_len"
Definition at line 280 of file system_parameter.c.
#define PRM_NAME_HA_APPLY_MAX_MEM_SIZE "ha_apply_max_mem_size"
Definition at line 350 of file system_parameter.c.
#define PRM_NAME_HA_APPLYLOGDB_IGNORE_ERROR_LIST "ha_applylogdb_ignore_error_list"
Definition at line 380 of file system_parameter.c.
#define PRM_NAME_HA_APPLYLOGDB_LOG_WAIT_TIME_IN_SECS "ha_applylogdb_log_wait_time_in_secs"
Definition at line 382 of file system_parameter.c.
#define PRM_NAME_HA_APPLYLOGDB_MAX_COMMIT_INTERVAL "ha_applylogdb_max_commit_interval"
Definition at line 402 of file system_parameter.c.
#define PRM_NAME_HA_APPLYLOGDB_MAX_COMMIT_INTERVAL_IN_MSECS "ha_applylogdb_max_commit_interval_in_msecs"
Definition at line 400 of file system_parameter.c.
#define PRM_NAME_HA_APPLYLOGDB_RETRY_ERROR_LIST "ha_applylogdb_retry_error_list"
Definition at line 378 of file system_parameter.c.
#define PRM_NAME_HA_CALC_SCORE_INTERVAL_IN_MSECS "ha_calc_score_interval_in_msecs"
Definition at line 358 of file system_parameter.c.
#define PRM_NAME_HA_CHANGEMODE_INTERVAL_IN_MSEC "ha_changemode_interval_in_msecs"
Definition at line 372 of file system_parameter.c.
#define PRM_NAME_HA_CHECK_DISK_FAILURE_INTERVAL_IN_SECS "ha_check_disk_failure_interval"
Definition at line 404 of file system_parameter.c.
Referenced by prm_tune_parameters().
#define PRM_NAME_HA_COPY_LOG_BASE "ha_copy_log_base"
Definition at line 346 of file system_parameter.c.
#define PRM_NAME_HA_COPY_LOG_MAX_ARCHIVES "ha_copy_log_max_archives"
Definition at line 388 of file system_parameter.c.
#define PRM_NAME_HA_COPY_LOG_TIMEOUT "ha_copy_log_timeout"
Definition at line 390 of file system_parameter.c.
Referenced by prm_tune_parameters().
#define PRM_NAME_HA_COPY_SYNC_MODE "ha_copy_sync_mode"
Definition at line 348 of file system_parameter.c.
#define PRM_NAME_HA_DB_LIST "ha_db_list"
Definition at line 344 of file system_parameter.c.
#define PRM_NAME_HA_DELAY_LIMIT "ha_delay_limit"
Definition at line 396 of file system_parameter.c.
#define PRM_NAME_HA_DELAY_LIMIT_DELTA "ha_delay_limit_delta"
Definition at line 398 of file system_parameter.c.
#define PRM_NAME_HA_FAILOVER_WAIT_TIME_IN_MSECS "ha_failover_wait_time_in_msecs"
Definition at line 360 of file system_parameter.c.
#define PRM_NAME_HA_HEARTBEAT_INTERVAL_IN_MSECS "ha_heartbeat_interval_in_msecs"
Definition at line 356 of file system_parameter.c.
#define PRM_NAME_HA_INIT_TIMER_IN_MSECS "ha_init_timer_in_msec"
Definition at line 354 of file system_parameter.c.
#define PRM_NAME_HA_LOG_APPLIER_STATE "ha_log_applier_state"
Definition at line 338 of file system_parameter.c.
Referenced by prm_print(), sysprm_generate_new_value(), and sysprm_print_sysprm_value().
#define PRM_NAME_HA_MAX_HEARTBEAT_GAP "ha_max_heartbeat_gap"
Definition at line 374 of file system_parameter.c.
#define PRM_NAME_HA_MAX_PROCESS_DEREG_CONFIRM "ha_max_process_dereg_confirm"
Definition at line 368 of file system_parameter.c.
Referenced by prm_tune_parameters().
#define PRM_NAME_HA_MAX_PROCESS_START_CONFIRM "ha_max_process_start_confirm"
Definition at line 366 of file system_parameter.c.
#define PRM_NAME_HA_MODE "ha_mode"
Definition at line 332 of file system_parameter.c.
Referenced by prm_print(), prm_tune_parameters(), sysprm_final(), sysprm_generate_new_value(), and sysprm_print_sysprm_value().
#define PRM_NAME_HA_MODE_FOR_SA_UTILS_ONLY "ha_mode_for_sa_utils_only"
Definition at line 334 of file system_parameter.c.
Referenced by prm_print(), sysprm_generate_new_value(), and sysprm_print_sysprm_value().
#define PRM_NAME_HA_NODE_LIST "ha_node_list"
Definition at line 340 of file system_parameter.c.
Referenced by prm_check_parameters(), prm_tune_parameters(), and sysprm_final().
#define PRM_NAME_HA_PING_HOSTS "ha_ping_hosts"
Definition at line 376 of file system_parameter.c.
#define PRM_NAME_HA_PORT_ID "ha_port_id"
Definition at line 352 of file system_parameter.c.
#define PRM_NAME_HA_PROCESS_DEREG_CONFIRM_INTERVAL_IN_MSECS "ha_process_dereg_confirm_interval_in_msecs"
Definition at line 364 of file system_parameter.c.
Referenced by prm_tune_parameters().
#define PRM_NAME_HA_PROCESS_START_CONFIRM_INTERVAL_IN_MSECS "ha_process_start_confirm_interval_in_msecs"
Definition at line 362 of file system_parameter.c.
#define PRM_NAME_HA_REPL_ENABLE_SERVER_SIDE_UPDATE "ha_repl_enable_server_side_update"
Definition at line 577 of file system_parameter.c.
#define PRM_NAME_HA_REPL_FILTER_FILE "ha_repl_filter_file"
Definition at line 614 of file system_parameter.c.
#define PRM_NAME_HA_REPL_FILTER_TYPE "ha_repl_filter_type"
Definition at line 613 of file system_parameter.c.
Referenced by prm_print(), sysprm_generate_new_value(), and sysprm_print_sysprm_value().
#define PRM_NAME_HA_REPLICA_DELAY "ha_replica_delay"
Definition at line 392 of file system_parameter.c.
#define PRM_NAME_HA_REPLICA_LIST "ha_replica_list"
Definition at line 342 of file system_parameter.c.
#define PRM_NAME_HA_REPLICA_TIME_BOUND "ha_replica_time_bound"
Definition at line 394 of file system_parameter.c.
#define PRM_NAME_HA_SERVER_STATE "ha_server_state"
Definition at line 336 of file system_parameter.c.
Referenced by prm_print(), sysprm_final(), sysprm_generate_new_value(), and sysprm_print_sysprm_value().
#define PRM_NAME_HA_SQL_LOG_MAX_SIZE_IN_MB "ha_sql_log_max_size_in_mbytes"
Definition at line 386 of file system_parameter.c.
#define PRM_NAME_HA_SQL_LOGGING "ha_enable_sql_logging"
Definition at line 384 of file system_parameter.c.
#define PRM_NAME_HA_UNACCEPTABLE_PROC_RESTART_TIMEDIFF "ha_unacceptable_proc_restart_timediff"
Definition at line 370 of file system_parameter.c.
#define PRM_NAME_HEAP_INFO_CACHE_LOGGING "heap_info_cache_logging"
Definition at line 682 of file system_parameter.c.
#define PRM_NAME_HF_MAX_BESTSPACE_ENTRIES "max_bestspace_entries"
Definition at line 137 of file system_parameter.c.
#define PRM_NAME_HF_UNFILL_FACTOR "unfill_factor"
Definition at line 135 of file system_parameter.c.
#define PRM_NAME_HOSTVAR_LATE_BINDING "hostvar_late_binding"
Definition at line 236 of file system_parameter.c.
#define PRM_NAME_IB_TASK_MEMSIZE "index_load_task_memsize"
Definition at line 676 of file system_parameter.c.
#define PRM_NAME_IGNORE_TRAILING_SPACE "ignore_trailing_space"
Definition at line 690 of file system_parameter.c.
#define PRM_NAME_INDEX_SCAN_KEY_BUFFER_PAGES "index_scan_key_buffer_pages"
Definition at line 226 of file system_parameter.c.
#define PRM_NAME_INDEX_SCAN_KEY_BUFFER_SIZE "index_scan_key_buffer_size"
Definition at line 228 of file system_parameter.c.
#define PRM_NAME_INSERT_MODE "insert_execution_mode"
Definition at line 232 of file system_parameter.c.
#define PRM_NAME_INTL_CHECK_INPUT_STRING "intl_check_input_string"
Definition at line 520 of file system_parameter.c.
Referenced by prm_load_by_section().
#define PRM_NAME_INTL_COLLATION "intl_collation"
Definition at line 532 of file system_parameter.c.
Referenced by prm_load_by_section(), sysprm_generate_new_value(), sysprm_init_intl_param(), and sysprm_make_default_values().
#define PRM_NAME_INTL_DATE_LANG "intl_date_lang"
Definition at line 514 of file system_parameter.c.
Referenced by prm_load_by_section(), sysprm_generate_new_value(), sysprm_init_intl_param(), and sysprm_make_default_values().
#define PRM_NAME_INTL_MBS_SUPPORT "intl_mbs_support"
Definition at line 420 of file system_parameter.c.
Referenced by prm_load_by_section().
#define PRM_NAME_INTL_NUMBER_LANG "intl_number_lang"
Definition at line 512 of file system_parameter.c.
Referenced by prm_load_by_section(), sysprm_generate_new_value(), sysprm_init_intl_param(), and sysprm_make_default_values().
#define PRM_NAME_IO_BACKUP_MAX_VOLUME_SIZE "backup_volume_max_size_bytes"
Definition at line 214 of file system_parameter.c.
#define PRM_NAME_IO_BACKUP_NBUFFERS "backup_buffer_pages"
Definition at line 212 of file system_parameter.c.
#define PRM_NAME_IO_BACKUP_SLEEP_MSECS "backup_sleep_msecs"
Definition at line 216 of file system_parameter.c.
#define PRM_NAME_IO_LOCKF_ENABLE "file_lock"
Definition at line 123 of file system_parameter.c.
#define PRM_NAME_IO_TEMP_VOLUME_PATH "temp_volume_path"
Definition at line 476 of file system_parameter.c.
#define PRM_NAME_IO_VOLUME_EXT_PATH "volume_extension_path"
Definition at line 480 of file system_parameter.c.
#define PRM_NAME_JAVA_STORED_PROCEDURE "java_stored_procedure"
Definition at line 406 of file system_parameter.c.
#define PRM_NAME_JAVA_STORED_PROCEDURE_DEBUG "java_stored_procedure_debug"
Definition at line 412 of file system_parameter.c.
#define PRM_NAME_JAVA_STORED_PROCEDURE_JVM_OPTIONS "java_stored_procedure_jvm_options"
Definition at line 410 of file system_parameter.c.
#define PRM_NAME_JAVA_STORED_PROCEDURE_PORT "java_stored_procedure_port"
Definition at line 408 of file system_parameter.c.
Referenced by prm_load_by_section().
#define PRM_NAME_JAVA_STORED_PROCEDURE_RESERVE_01 "java_stored_procedure_reserve_01"
Definition at line 414 of file system_parameter.c.
#define PRM_NAME_JSON_LOG_ALLOCATIONS "json_log_allocations"
Definition at line 651 of file system_parameter.c.
#define PRM_NAME_JSON_MAX_ARRAY_IDX "json_max_array_idx"
Definition at line 652 of file system_parameter.c.
#define PRM_NAME_LIKE_TERM_SELECTIVITY "like_term_selectivity"
Definition at line 294 of file system_parameter.c.
#define PRM_NAME_LIST_MAX_QUERY_CACHE_ENTRIES "max_query_cache_entries"
Definition at line 324 of file system_parameter.c.
Referenced by sysprm_final().
#define PRM_NAME_LIST_MAX_QUERY_CACHE_PAGES "query_cache_size_in_pages"
Definition at line 326 of file system_parameter.c.
Referenced by sysprm_final().
#define PRM_NAME_LIST_QUERY_CACHE_MODE "query_cache_mode"
Definition at line 322 of file system_parameter.c.
Referenced by sysprm_final().
#define PRM_NAME_LK_ESCALATION_AT "lock_escalation"
Definition at line 151 of file system_parameter.c.
#define PRM_NAME_LK_MAX_SCANID_BIT "max_index_scan_count"
Definition at line 234 of file system_parameter.c.
#define PRM_NAME_LK_ROLLBACK_ON_LOCK_ESCALATION "rollback_on_lock_escalation"
Definition at line 153 of file system_parameter.c.
#define PRM_NAME_LK_RUN_DEADLOCK_INTERVAL "deadlock_detection_interval_in_secs"
Definition at line 159 of file system_parameter.c.
#define PRM_NAME_LK_TIMEOUT "lock_timeout"
Definition at line 157 of file system_parameter.c.
#define PRM_NAME_LK_TIMEOUT_MESSAGE_DUMP_LEVEL "lock_timeout_message_type"
Definition at line 149 of file system_parameter.c.
#define PRM_NAME_LK_TIMEOUT_SECS "lock_timeout_in_secs"
Definition at line 155 of file system_parameter.c.
#define PRM_NAME_LOADDB_FLUSH_INTERVAL "load_flush_interval"
Definition at line 474 of file system_parameter.c.
#define PRM_NAME_LOADDB_WORKER_COUNT "loaddb_worker_count"
Definition at line 678 of file system_parameter.c.
#define PRM_NAME_LOG_ASYNC_COMMIT "async_commit"
Definition at line 424 of file system_parameter.c.
#define PRM_NAME_LOG_BACKGROUND_ARCHIVING "background_archiving"
Definition at line 176 of file system_parameter.c.
Referenced by sysprm_final().
#define PRM_NAME_LOG_BG_FLUSH_INTERVAL_MSECS "log_flush_interval_in_msecs"
Definition at line 428 of file system_parameter.c.
#define PRM_NAME_LOG_BG_FLUSH_NUM_PAGES "log_flush_every_npages"
Definition at line 430 of file system_parameter.c.
#define PRM_NAME_LOG_BTREE_OPS "log_btree_operations"
Definition at line 592 of file system_parameter.c.
#define PRM_NAME_LOG_BUFFER_SIZE "log_buffer_size"
Definition at line 163 of file system_parameter.c.
#define PRM_NAME_LOG_CHECKPOINT_INTERVAL "checkpoint_interval"
Definition at line 172 of file system_parameter.c.
#define PRM_NAME_LOG_CHECKPOINT_INTERVAL_SECS "checkpoint_interval_in_mins"
Definition at line 170 of file system_parameter.c.
#define PRM_NAME_LOG_CHECKPOINT_NPAGES "checkpoint_every_npages"
Definition at line 165 of file system_parameter.c.
#define PRM_NAME_LOG_CHECKPOINT_SIZE "checkpoint_every_size"
Definition at line 167 of file system_parameter.c.
#define PRM_NAME_LOG_CHECKPOINT_SLEEP_MSECS "checkpoint_sleep_msecs"
Definition at line 174 of file system_parameter.c.
#define PRM_NAME_LOG_CHKPT_DETAILED "detailed_checkpoint_logging"
Definition at line 675 of file system_parameter.c.
#define PRM_NAME_LOG_COMPRESS "log_compress"
Definition at line 432 of file system_parameter.c.
#define PRM_NAME_LOG_GROUP_COMMIT_INTERVAL_MSECS "group_commit_interval_in_msecs"
Definition at line 426 of file system_parameter.c.
#define PRM_NAME_LOG_HEADER_FLUSH_INTERVAL "log_header_flush_interval_in_secs"
Definition at line 422 of file system_parameter.c.
#define PRM_NAME_LOG_ISOLATION_LEVEL "isolation_level"
Definition at line 178 of file system_parameter.c.
Referenced by prm_print(), sysprm_generate_new_value(), and sysprm_print_sysprm_value().
#define PRM_NAME_LOG_MAX_ARCHIVES "log_max_archives"
Definition at line 462 of file system_parameter.c.
Referenced by sysprm_final().
#define PRM_NAME_LOG_MEDIA_FAILURE_SUPPORT "media_failure_support"
Definition at line 180 of file system_parameter.c.
#define PRM_NAME_LOG_NBUFFERS "log_buffer_pages"
Definition at line 161 of file system_parameter.c.
#define PRM_NAME_LOG_NO_LOGGING "no_logging"
Definition at line 468 of file system_parameter.c.
#define PRM_NAME_LOG_PGBUF_VICTIM_FLUSH "log_pgbuf_victim_flush"
Definition at line 674 of file system_parameter.c.
#define PRM_NAME_LOG_QUERY_LISTS "log_query_lists"
Definition at line 658 of file system_parameter.c.
#define PRM_NAME_LOG_SWEEP_CLEAN "log_file_sweep_clean"
Definition at line 182 of file system_parameter.c.
#define PRM_NAME_LOG_TRACE_DEBUG "log_trace_debug"
Definition at line 442 of file system_parameter.c.
#define PRM_NAME_LOG_TRACE_FLUSH_TIME "log_trace_flush_time"
Definition at line 530 of file system_parameter.c.
#define PRM_NAME_LOG_UNIQUE_STATS "log_unique_stats"
Definition at line 625 of file system_parameter.c.
#define PRM_NAME_LOG_VOLUME_SIZE "log_volume_size"
Definition at line 510 of file system_parameter.c.
#define PRM_NAME_LOGPB_LOGGING_DEBUG "logpb_logging_debug"
Definition at line 627 of file system_parameter.c.
#define PRM_NAME_MAX_AGG_HASH_SIZE "max_agg_hash_size"
Definition at line 550 of file system_parameter.c.
#define PRM_NAME_MAX_ENTRIES_IN_TEMP_FILE_CACHE "max_entries_in_temp_file_cache"
Definition at line 220 of file system_parameter.c.
#define PRM_NAME_MAX_FLUSH_PAGES_PER_SECOND "max_flush_pages_per_second"
Definition at line 250 of file system_parameter.c.
#define PRM_NAME_MAX_FLUSH_SIZE_PER_SECOND "max_flush_size_per_second"
Definition at line 252 of file system_parameter.c.
#define PRM_NAME_MAX_HASH_LIST_SCAN_SIZE "max_hash_list_scan_size"
Definition at line 556 of file system_parameter.c.
#define PRM_NAME_MAX_OUTER_CARD_OF_IDXJOIN "max_outer_card_of_idxjoin"
Definition at line 296 of file system_parameter.c.
#define PRM_NAME_MAX_PAGES_IN_TEMP_FILE_CACHE "max_pages_in_temp_file_cache"
Definition at line 218 of file system_parameter.c.
#define PRM_NAME_MAX_RECURSION_SQL_DEPTH "max_recursion_sql_depth"
Definition at line 544 of file system_parameter.c.
#define PRM_NAME_MNT_STATS_THRESHOLD "monitor_stats_threshold"
Definition at line 494 of file system_parameter.c.
#define PRM_NAME_MNT_WAITING_THREAD "monitor_waiting_thread"
Definition at line 492 of file system_parameter.c.
#define PRM_NAME_MULTI_RANGE_OPT_LIMIT "multi_range_optimization_limit"
Definition at line 502 of file system_parameter.c.
#define PRM_NAME_MUTEX_BUSY_WAITING_CNT "mutex_busy_waiting_cnt"
Definition at line 240 of file system_parameter.c.
#define PRM_NAME_MYSQL_TRIGGER_CORRELATION_NAMES "mysql_trigger_correlation_names"
Definition at line 274 of file system_parameter.c.
#define PRM_NAME_NO_BACKSLASH_ESCAPES "no_backslash_escapes"
Definition at line 278 of file system_parameter.c.
#define PRM_NAME_OBJECT_PRINT_FORMAT_OID "print_object_as_oid"
Definition at line 594 of file system_parameter.c.
#define PRM_NAME_ONLY_FULL_GROUP_BY "only_full_group_by"
Definition at line 270 of file system_parameter.c.
#define PRM_NAME_OPTIMIZATION_LEVEL "optimization_level"
Definition at line 200 of file system_parameter.c.
#define PRM_NAME_OPTIMIZER_ENABLE_AGGREGATE_OPTIMIZATION "optimizer_enable_aggregate_optimization"
Definition at line 600 of file system_parameter.c.
#define PRM_NAME_OPTIMIZER_ENABLE_MERGE_JOIN "optimizer_enable_merge_join"
Definition at line 555 of file system_parameter.c.
#define PRM_NAME_OPTIMIZER_RESERVE_02 "optimizer_reserve_02"
Definition at line 557 of file system_parameter.c.
#define PRM_NAME_OPTIMIZER_RESERVE_03 "optimizer_reserve_03"
Definition at line 558 of file system_parameter.c.
#define PRM_NAME_OPTIMIZER_RESERVE_04 "optimizer_reserve_04"
Definition at line 559 of file system_parameter.c.
#define PRM_NAME_OPTIMIZER_RESERVE_05 "optimizer_reserve_05"
Definition at line 560 of file system_parameter.c.
#define PRM_NAME_OPTIMIZER_RESERVE_06 "optimizer_reserve_06"
Definition at line 561 of file system_parameter.c.
#define PRM_NAME_OPTIMIZER_RESERVE_07 "optimizer_reserve_07"
Definition at line 562 of file system_parameter.c.
#define PRM_NAME_OPTIMIZER_RESERVE_08 "optimizer_reserve_08"
Definition at line 563 of file system_parameter.c.
#define PRM_NAME_OPTIMIZER_RESERVE_09 "optimizer_reserve_09"
Definition at line 564 of file system_parameter.c.
#define PRM_NAME_OPTIMIZER_RESERVE_10 "optimizer_reserve_10"
Definition at line 565 of file system_parameter.c.
#define PRM_NAME_OPTIMIZER_RESERVE_11 "optimizer_reserve_11"
Definition at line 566 of file system_parameter.c.
#define PRM_NAME_OPTIMIZER_RESERVE_12 "optimizer_reserve_12"
Definition at line 567 of file system_parameter.c.
#define PRM_NAME_OPTIMIZER_RESERVE_13 "optimizer_reserve_13"
Definition at line 568 of file system_parameter.c.
#define PRM_NAME_OPTIMIZER_RESERVE_14 "optimizer_reserve_14"
Definition at line 569 of file system_parameter.c.
#define PRM_NAME_OPTIMIZER_RESERVE_15 "optimizer_reserve_15"
Definition at line 570 of file system_parameter.c.
#define PRM_NAME_OPTIMIZER_RESERVE_16 "optimizer_reserve_16"
Definition at line 571 of file system_parameter.c.
#define PRM_NAME_OPTIMIZER_RESERVE_17 "optimizer_reserve_17"
Definition at line 572 of file system_parameter.c.
#define PRM_NAME_OPTIMIZER_RESERVE_18 "optimizer_reserve_18"
Definition at line 573 of file system_parameter.c.
#define PRM_NAME_OPTIMIZER_RESERVE_19 "optimizer_reserve_19"
Definition at line 574 of file system_parameter.c.
#define PRM_NAME_OPTIMIZER_RESERVE_20 "optimizer_reserve_20"
Definition at line 575 of file system_parameter.c.
#define PRM_NAME_ORACLE_STYLE_EMPTY_STRING "oracle_style_empty_string"
Definition at line 298 of file system_parameter.c.
#define PRM_NAME_ORACLE_STYLE_OUTERJOIN "oracle_style_outerjoin"
Definition at line 260 of file system_parameter.c.
#define PRM_NAME_PAGE_BG_FLUSH_INTERVAL "page_flush_interval"
Definition at line 246 of file system_parameter.c.
#define PRM_NAME_PAGE_BG_FLUSH_INTERVAL_MSECS "page_flush_interval_in_msecs"
Definition at line 244 of file system_parameter.c.
#define PRM_NAME_PAGE_BUFFER_SIZE "data_buffer_size"
Definition at line 131 of file system_parameter.c.
#define PRM_NAME_PB_AOUT_RATIO "data_aout_ratio"
Definition at line 548 of file system_parameter.c.
Referenced by sysprm_final().
#define PRM_NAME_PB_BUFFER_FLUSH_RATIO "data_buffer_flush_ratio"
Definition at line 133 of file system_parameter.c.
#define PRM_NAME_PB_DEBUG_PAGE_VALIDATION_LEVEL "page_validation_level"
Definition at line 258 of file system_parameter.c.
Referenced by prm_print(), sysprm_generate_new_value(), and sysprm_print_sysprm_value().
#define PRM_NAME_PB_LRU_BUFFER_RATIO "lru_buffer_ratio"
Definition at line 579 of file system_parameter.c.
#define PRM_NAME_PB_LRU_HOT_RATIO "lru_hot_ratio"
Definition at line 578 of file system_parameter.c.
#define PRM_NAME_PB_MAX_DEPTH_OF_SEARCHING_FOR_VICTIMS_IN_LRU_LIST "max_depth_of_searching_for_victims_in_lru_list"
Definition at line 642 of file system_parameter.c.
#define PRM_NAME_PB_MONITOR_LOCKS "pgbuf_monitor_locks"
Definition at line 641 of file system_parameter.c.
#define PRM_NAME_PB_NBUFFERS "data_buffer_pages"
Definition at line 129 of file system_parameter.c.
#define PRM_NAME_PB_NEIGHBOR_FLUSH_NONDIRTY "data_buffer_neighbor_flush_nondirty"
Definition at line 606 of file system_parameter.c.
#define PRM_NAME_PB_NEIGHBOR_FLUSH_PAGES "data_buffer_neighbor_flush_pages"
Definition at line 607 of file system_parameter.c.
#define PRM_NAME_PB_NUM_LRU_CHAINS "num_LRU_chains"
Definition at line 242 of file system_parameter.c.
#define PRM_NAME_PB_NUM_PRIVATE_CHAINS "num_private_chains"
Definition at line 640 of file system_parameter.c.
#define PRM_NAME_PB_SEQUENTIAL_VICTIM_FLUSH "data_buffer_sequential_victim_flush"
Definition at line 623 of file system_parameter.c.
#define PRM_NAME_PB_SYNC_ON_FLUSH_SIZE "sync_on_flush_size"
Definition at line 256 of file system_parameter.c.
#define PRM_NAME_PB_SYNC_ON_NFLUSH "sync_on_nflush"
Definition at line 254 of file system_parameter.c.
#define PRM_NAME_PERF_TEST_MODE "perf_test_mode"
Definition at line 679 of file system_parameter.c.
#define PRM_NAME_PIPES_AS_CONCAT "pipes_as_concat"
Definition at line 272 of file system_parameter.c.
#define PRM_NAME_PLUS_AS_CONCAT "plus_as_concat"
Definition at line 288 of file system_parameter.c.
#define PRM_NAME_POSTPONE_DEBUG "postpone_debug"
Definition at line 617 of file system_parameter.c.
#define PRM_NAME_PTHREAD_SCOPE_PROCESS "pthread_scope_process"
Definition at line 222 of file system_parameter.c.
#define PRM_NAME_QO_DUMP "qo_dump"
Definition at line 202 of file system_parameter.c.
#define PRM_NAME_QUERY_TRACE "query_trace"
Definition at line 541 of file system_parameter.c.
#define PRM_NAME_QUERY_TRACE_FORMAT "query_trace_format"
Definition at line 542 of file system_parameter.c.
Referenced by prm_print(), sysprm_generate_new_value(), and sysprm_print_sysprm_value().
#define PRM_NAME_READ_ONLY_MODE "read_only"
Definition at line 490 of file system_parameter.c.
#define PRM_NAME_REMOVE_LOG_ARCHIVES_INTERVAL "remove_log_archive_interval_in_secs"
Definition at line 466 of file system_parameter.c.
#define PRM_NAME_REPLICATION_MODE "replication"
Definition at line 330 of file system_parameter.c.
#define PRM_NAME_REPR_CACHE_LOG "er_log_repr_cache"
Definition at line 680 of file system_parameter.c.
#define PRM_NAME_REQUIRE_LIKE_ESCAPE_CHARACTER "require_like_escape_character"
Definition at line 276 of file system_parameter.c.
#define PRM_NAME_RESET_TR_PARSER "reset_tr_parser_interval"
Definition at line 210 of file system_parameter.c.
#define PRM_NAME_RETURN_NULL_ON_FUNCTION_ERRORS "return_null_on_function_errors"
Definition at line 286 of file system_parameter.c.
#define PRM_NAME_SA_MODE_AUTO_VACUUM "sa_mode_auto_vacuum"
Definition at line 588 of file system_parameter.c.
#define PRM_NAME_SERVER_TIMEZONE "server_timezone"
Definition at line 597 of file system_parameter.c.
Referenced by prm_load_by_section(), and sysprm_final().
#define PRM_NAME_SERVICE_SERVER_LIST "service::server"
Definition at line 498 of file system_parameter.c.
#define PRM_NAME_SERVICE_SERVICE_LIST "service::service"
Definition at line 496 of file system_parameter.c.
#define PRM_NAME_SESSION_STATE_TIMEOUT "session_state_timeout"
Definition at line 500 of file system_parameter.c.
#define PRM_NAME_SHUTDOWN_WAIT_TIME_IN_SECS "shutdown_wait_time_in_secs"
Definition at line 186 of file system_parameter.c.
Referenced by prm_tune_parameters().
#define PRM_NAME_SINGLE_BYTE_COMPARE "single_byte_compare"
Definition at line 438 of file system_parameter.c.
#define PRM_NAME_SORT_BUFFER_SIZE "sort_buffer_size"
Definition at line 127 of file system_parameter.c.
#define PRM_NAME_SORT_LIMIT_MAX_COUNT "sort_limit_max_count"
Definition at line 536 of file system_parameter.c.
#define PRM_NAME_SQL_TRACE_EXECUTION_PLAN "sql_trace_execution_plan"
Definition at line 524 of file system_parameter.c.
#define PRM_NAME_SQL_TRACE_IOREADS "sql_trace_ioread_pages"
Definition at line 538 of file system_parameter.c.
#define PRM_NAME_SQL_TRACE_SLOW "sql_trace_slow"
Definition at line 528 of file system_parameter.c.
#define PRM_NAME_SQL_TRACE_SLOW_MSECS "sql_trace_slow_msecs"
Definition at line 526 of file system_parameter.c.
#define PRM_NAME_SR_NBUFFERS "sort_buffer_pages"
Definition at line 125 of file system_parameter.c.
#define PRM_NAME_STATS_ON "stats_on"
Definition at line 677 of file system_parameter.c.
#define PRM_NAME_STRING_MAX_SIZE_BYTES "string_max_size_bytes"
Definition at line 282 of file system_parameter.c.
#define PRM_NAME_SUPPRESS_FSYNC "suppress_fsync"
Definition at line 300 of file system_parameter.c.
#define PRM_NAME_TB_DEFAULT_REUSE_OID "create_table_reuseoid"
Definition at line 687 of file system_parameter.c.
#define PRM_NAME_TCP_CONNECTION_TIMEOUT "connection_timeout"
Definition at line 198 of file system_parameter.c.
#define PRM_NAME_TCP_KEEPALIVE "tcp_keepalive"
Definition at line 456 of file system_parameter.c.
#define PRM_NAME_TCP_NODELAY "tcp_nodelay"
Definition at line 454 of file system_parameter.c.
#define PRM_NAME_TCP_PORT_ID "cubrid_port_id"
Definition at line 196 of file system_parameter.c.
#define PRM_NAME_TCP_RCVBUF_SIZE "tcp_rcvbuf_size"
Definition at line 450 of file system_parameter.c.
#define PRM_NAME_TCP_SNDBUF_SIZE "tcp_sndbuf_size"
Definition at line 452 of file system_parameter.c.
#define PRM_NAME_TDE_DEFAULT_ALGORITHM "tde_default_algorithm"
Definition at line 683 of file system_parameter.c.
Referenced by prm_print(), sysprm_generate_new_value(), and sysprm_print_sysprm_value().
#define PRM_NAME_TDE_KEYS_FILE_PATH "tde_keys_file_path"
Definition at line 478 of file system_parameter.c.
#define PRM_NAME_TEMP_MEM_BUFFER_PAGES "temp_file_memory_size_in_pages"
Definition at line 224 of file system_parameter.c.
#define PRM_NAME_TEST_MODE "test_mode"
Definition at line 268 of file system_parameter.c.
Referenced by prm_tune_parameters(), and sysprm_final().
#define PRM_NAME_THREAD_CONNECTION_POOLING "thread_connection_pooling"
Definition at line 660 of file system_parameter.c.
#define PRM_NAME_THREAD_CONNECTION_TIMEOUT_SECONDS "thread_connection_timeout_seconds"
Definition at line 661 of file system_parameter.c.
#define PRM_NAME_THREAD_LOGGING_FLAG "thread_logging_flag"
Definition at line 656 of file system_parameter.c.
#define PRM_NAME_THREAD_STACKSIZE "thread_stacksize"
Definition at line 206 of file system_parameter.c.
#define PRM_NAME_THREAD_WORKER_POOLING "thread_worker_pooling"
Definition at line 662 of file system_parameter.c.
#define PRM_NAME_THREAD_WORKER_TIMEOUT_SECONDS "thread_worker_timeout_seconds"
Definition at line 663 of file system_parameter.c.
#define PRM_NAME_TIMEZONE "timezone"
Definition at line 596 of file system_parameter.c.
Referenced by prm_load_by_section(), sysprm_generate_new_value(), sysprm_init_intl_param(), and sysprm_make_default_values().
#define PRM_NAME_TRACK_REQUESTS "track_client_requests"
Definition at line 673 of file system_parameter.c.
#define PRM_NAME_TZ_LEAP_SECOND_SUPPORT "tz_leap_second_support"
Definition at line 598 of file system_parameter.c.
Referenced by prm_tune_parameters(), and sysprm_final().
#define PRM_NAME_UNICODE_INPUT_NORMALIZATION "unicode_input_normalization"
Definition at line 516 of file system_parameter.c.
#define PRM_NAME_UNICODE_OUTPUT_NORMALIZATION "unicode_output_normalization"
Definition at line 518 of file system_parameter.c.
#define PRM_NAME_UNIQUE_ERROR_KEY_VALUE "print_key_value_on_unique_error"
Definition at line 482 of file system_parameter.c.
#define PRM_NAME_UNLOADDB_IGNORE_ERROR "unload_ignore_error"
Definition at line 470 of file system_parameter.c.
#define PRM_NAME_UNLOADDB_LOCK_TIMEOUT "unload_lock_timeout"
Definition at line 472 of file system_parameter.c.
#define PRM_NAME_UPDATE_USE_ATTRIBUTE_REFERENCES "update_use_attribute_references"
Definition at line 546 of file system_parameter.c.
#define PRM_NAME_USE_BTREE_FENCE_KEY "use_btree_fence_key"
Definition at line 553 of file system_parameter.c.
#define PRM_NAME_USE_ORDERBY_SORT_LIMIT "use_orderby_sort_limit"
Definition at line 328 of file system_parameter.c.
#define PRM_NAME_USE_STAT_ESTIMATION "use_stat_estimation"
Definition at line 689 of file system_parameter.c.
#define PRM_NAME_USE_SYSTEM_MALLOC "use_system_malloc"
Definition at line 484 of file system_parameter.c.
#define PRM_NAME_VACUUM_LOG_BLOCK_PAGES "vacuum_log_block_pages"
Definition at line 583 of file system_parameter.c.
#define PRM_NAME_VACUUM_MASTER_WAKEUP_INTERVAL "vacuum_master_interval_in_msecs"
Definition at line 581 of file system_parameter.c.
#define PRM_NAME_VACUUM_PREFETCH_LOG_BUFFER_SIZE "vacuum_prefetch_log_buffer_size"
Definition at line 603 of file system_parameter.c.
#define PRM_NAME_VACUUM_PREFETCH_LOG_MODE "vacuum_prefetch_log_mode"
Definition at line 604 of file system_parameter.c.
#define PRM_NAME_VACUUM_PREFETCH_LOG_NBUFFERS "vacuum_prefetch_log_pages"
Definition at line 602 of file system_parameter.c.
#define PRM_NAME_VACUUM_WORKER_COUNT "vacuum_worker_count"
Definition at line 584 of file system_parameter.c.
#define PRM_NAME_WS_HASHTABLE_SIZE "initial_workspace_table_size"
Definition at line 190 of file system_parameter.c.
#define PRM_NAME_WS_MEMORY_REPORT "workspace_memory_report"
Definition at line 192 of file system_parameter.c.
#define PRM_NAME_XASL_CACHE_LOGGING "plan_cache_logging"
Definition at line 317 of file system_parameter.c.
#define PRM_NAME_XASL_CACHE_MAX_CLONES "max_plan_cache_clones"
Definition at line 315 of file system_parameter.c.
#define PRM_NAME_XASL_CACHE_MAX_ENTRIES "max_plan_cache_entries"
Definition at line 314 of file system_parameter.c.
Referenced by prm_tune_parameters(), and sysprm_final().
#define PRM_NAME_XASL_CACHE_TIME_THRESHOLD_IN_MINUTES "xasl_cache_time_threshold_in_minutes"
Definition at line 633 of file system_parameter.c.
#define PRM_NAME_XASL_CACHE_TIMEOUT "plan_cache_timeout"
Definition at line 316 of file system_parameter.c.
#define PRM_NAME_XASL_DEBUG_DUMP "xasl_debug_dump"
Definition at line 460 of file system_parameter.c.
#define PRM_OBSOLETED 0x80000000 /* is obsoleted */
Definition at line 739 of file system_parameter.c.
#define PRM_PRINT_QRY_STRING (id) (PRM_IS_FOR_QRY_STRING (GET_PRM_STATIC_FLAG (id)))
Definition at line 6054 of file system_parameter.c.
Referenced by sysprm_print_parameters_for_qry_string().
#define PRM_RELOADABLE 0x00000010 /* is reloadable */
Definition at line 718 of file system_parameter.c.
#define PRM_SERVER_SESSION (id)
Value:
(PRM_IS_FOR_SESSION (GET_PRM_STATIC_FLAG (id)) \
            && PRM_IS_FOR_SERVER (GET_PRM_STATIC_FLAG (id)) \
            && !PRM_CLIENT_SESSION_ONLY (GET_PRM_STATIC_FLAG (id)))
Definition at line 6057 of file system_parameter.c.
Referenced by prm_get_value().
#define PRM_SET 0x00000001 /* has been set */
Definition at line 744 of file system_parameter.c.
Referenced by sysprm_final(), and sysprm_set_value().
#define PRM_SET_BIT (this, here) (here |= this)
Definition at line 795 of file system_parameter.c.
Referenced by prm_set_default(), prm_set_integer_list_value(), prm_set_string_value(), sysprm_final(), sysprm_get_id(), sysprm_set_value(), sysprm_update_flag_allocated(), sysprm_update_flag_different(), and sysprm_update_session_prm_flag_allocated().
#define PRM_SIZE_UNIT 0x00001000 /* has size unit interface */
Definition at line 729 of file system_parameter.c.
#define PRM_TEST_CHANGE 0x00000040 /* can only be changed in the test mode */
Definition at line 720 of file system_parameter.c.
#define PRM_TEST_CHANGE_ONLY (x) (x & PRM_TEST_CHANGE)
Definition at line 771 of file system_parameter.c.
Referenced by sysprm_load_and_init_internal(), and sysprm_validate_change_parameters().
#define PRM_TIME_UNIT 0x00002000 /* has time unit interface */
Definition at line 730 of file system_parameter.c.
#define PRM_USER_CAN_CHANGE (x) (x & PRM_USER_CHANGE)
Definition at line 765 of file system_parameter.c.
Referenced by sysprm_load_and_init_internal(), and sysprm_validate_change_parameters().
#define PRM_USER_CHANGE 0x00000001 /* user can change, not implemented */
Definition at line 714 of file system_parameter.c.
#define PRM_VALUE_DEFAULT "DEFAULT"
Definition at line 695 of file system_parameter.c.
Referenced by sysprm_generate_new_value().
#define PRM_VALUE_MAX "MAX"
Definition at line 696 of file system_parameter.c.
Referenced by sysprm_generate_new_value().
#define PRM_VALUE_MIN "MIN"
Definition at line 697 of file system_parameter.c.
Referenced by sysprm_generate_new_value().
#define strlen (s1) ((int) strlen(s1))
Definition at line 93 of file system_parameter.c.
Referenced by prm_load_by_section(), prm_print(), prm_set_force(), sysprm_generate_new_value(), sysprm_get_id(), sysprm_print_sysprm_value(), sysprm_set_sysprm_value_from_parameter(), sysprm_set_value(), and sysprm_unpack_sysprm_value().
#define VACUUM_LOG_BLOCK_PAGES_DEFAULT 0
Definition at line 2001 of file system_parameter.c.
#define VACUUM_MAX_WORKER_COUNT 0
Definition at line 2002 of file system_parameter.c.
Referenced by pgbuf_initialize_page_quota_parameters(), vacuum_finalize(), vacuum_initialize(), vacuum_is_work_in_progress(), vacuum_process_log_record(), and vacuum_worker_context_manager::vacuum_worker_context_manager().
Typedef Documentation
typedef int(* DUP_PRM_FUNC) (void *, SYSPRM_DATATYPE, void *, SYSPRM_DATATYPE)
Definition at line 2347 of file system_parameter.c.
typedef struct keyval KEYVAL
Definition at line 6079 of file system_parameter.c.
typedef struct sysprm_param SYSPRM_PARAM
Definition at line 2381 of file system_parameter.c.
Enumeration Type Documentation
enum PGBUF_DEBUG_PAGE_VALIDATION_LEVEL
Enumerator
PGBUF_DEBUG_NO_PAGE_VALIDATION
PGBUF_DEBUG_PAGE_VALIDATION_FETCH
PGBUF_DEBUG_PAGE_VALIDATION_FREE
PGBUF_DEBUG_PAGE_VALIDATION_ALL
PGBUF_DEBUG_NO_PAGE_VALIDATION
PGBUF_DEBUG_PAGE_VALIDATION_FETCH
PGBUF_DEBUG_PAGE_VALIDATION_FREE
PGBUF_DEBUG_PAGE_VALIDATION_ALL
Definition at line 1243 of file system_parameter.c.
enum PRM_PRINT_MODE
Enumerator
PRM_PRINT_NONE
PRM_PRINT_NAME
PRM_PRINT_ID
Definition at line 6338 of file system_parameter.c.
enum PRM_PRINT_VALUE_MODE
Enumerator
PRM_PRINT_CURR_VAL
PRM_PRINT_DEFAULT_VAL
Definition at line 6345 of file system_parameter.c.
Function Documentation
static void prm_check_environment (void) static
Definition at line 7558 of file system_parameter.c.
References envvar_get(), error(), i, sysprm_param::name, NUM_PRM, PRM_DEFAULT_BUFFER_SIZE, prm_report_bad_entry(), prm_set(), and ustr_upper().
Referenced by sysprm_load_and_init_internal().
static int prm_check_parameters (void) static
Definition at line 7535 of file system_parameter.c.
References ER_FAILED, HA_MODE_OFF, MSGCAT_CATALOG_CUBRID, msgcat_message(), MSGCAT_SET_PARAMETERS, NO_ERROR, NULL, PRM_ERR_NO_VALUE, PRM_HA_DB_LIST, PRM_HA_MODE, PRM_HA_NODE_LIST, and PRM_NAME_HA_NODE_LIST.
Referenced by sysprm_load_and_init_internal().
static int prm_check_range (SYSPRM_PARAM * prm, void * value) static
Definition at line 8931 of file system_parameter.c.
References assert, error(), sysprm_param::lower_limit, NO_ERROR, NULL, PRM_ADJUST_FOR_SET_BIGINT_TO_BIGINT, PRM_ADJUST_FOR_SET_BIGINT_TO_FLOAT, PRM_ADJUST_FOR_SET_BIGINT_TO_INTEGER, PRM_ADJUST_FOR_SET_FLOAT_TO_FLOAT, PRM_ADJUST_FOR_SET_INTEGER_TO_INTEGER, PRM_DIFFERENT_UNIT, PRM_ERR_BAD_RANGE, PRM_ERR_BAD_VALUE, PRM_ERR_NO_ERROR, PRM_GET_BIGINT, PRM_GET_FLOAT, PRM_GET_INT, PRM_HAS_SIZE_UNIT, PRM_HAS_TIME_UNIT, PRM_IS_BIGINT, PRM_IS_FLOAT, PRM_IS_INTEGER, PRM_IS_KEYWORD, sysprm_param::set_dup, sysprm_param::static_flag, and sysprm_param::upper_limit.
Referenced by sysprm_check_range(), and sysprm_generate_new_value().
static int prm_compound_has_changed (SYSPRM_PARAM * prm, bool set_flag) static
Definition at line 9932 of file system_parameter.c.
References assert, compat_mode_values, NO_ERROR, PRM_ID_COMPAT_MODE, PRM_IS_COMPOUND, prm_set_compound(), sysprm_param::static_flag, and sysprm_get_id().
Referenced by sysprm_set_value().
static int prm_equal_to_ori (void * out_val, SYSPRM_DATATYPE out_type, void * in_val, SYSPRM_DATATYPE in_type) static
Definition at line 7474 of file system_parameter.c.
References assert_release, NO_ERROR, NULL, PRM_BIGINT, PRM_ERR_BAD_RANGE, PRM_ERR_BAD_VALUE, PRM_FLOAT, and PRM_INTEGER.
static void prm_file_has_been_loaded (const char * conf_path, const char * db_name) static
Definition at line 6423 of file system_parameter.c.
References assert, i, MAX_NUM_OF_PRM_FILES_LOADED, NULL, prm_Files_loaded, and strdup().
Referenced by prm_read_and_parse_ini_file().
static SYSPRM_PARAM * prm_find (const char * pname, const char * section) static
Definition at line 10084 of file system_parameter.c.
References i, intl_mbs_casecmp(), sysprm_param::name, and NULL.
Referenced by prm_load_by_section(), prm_set_compound(), prm_tune_parameters(), sysprm_check_range(), sysprm_final(), sysprm_get_range(), sysprm_init_intl_param(), sysprm_make_default_values(), sysprm_obtain_parameters(), sysprm_set_er_log_file(), sysprm_set_force(), sysprm_set_to_default(), and sysprm_validate_change_parameters().
UINT64 prm_get_bigint_value (PARAM_ID prm_id)
Definition at line 11040 of file system_parameter.c.
References assert, PRM_GET_BIGINT, prm_get_value(), PRM_IS_BIGINT, and PRM_LAST_ID.
Referenced by index_builder_loader_task::add_key(), addvoldb(), check_hash_list_scan(), createdb(), db_string_pad(), db_string_repeat(), db_string_space(), disk_cache_init(), fileio_flush_backup(), fileio_get_lockf_type(), fileio_initialize_backup(), hb_create_master_reader(), hb_thread_initialize(), logddl_write(), logddl_write_end_for_csql_fileinput(), logddl_write_tran_str(), qdata_group_concat_first_value(), qdata_group_concat_value(), qexec_hash_gby_agg_tuple(), qstr_bit_concatenate(), qstr_concatenate(), qstr_grow_string(), and xboot_initialize_server().
bool prm_get_bool_value (PARAM_ID prm_id)
Definition at line 10979 of file system_parameter.c.
References assert, PRM_GET_BOOL, prm_get_value(), PRM_IS_BOOLEAN, and PRM_LAST_ID.
Referenced by boot_restart_client(), boot_restart_server(), boot_server_die_or_changed(), boot_shutdown_client(), btree_apply_key_range_and_filter(), btree_construct_leafs(), btree_delete_internal(), btree_delete_postponed(), btree_insert(), btree_insert_internal(), btree_key_lock_and_append_object_unique(), btree_mvcc_delete(), btree_online_index_list_dispatcher(), btree_physical_delete(), btree_prepare_bts(), btree_reflect_global_unique_statistics(), btree_rv_record_modify_internal(), btree_rv_redo_global_unique_stats_commit(), btree_rv_undo_global_unique_stats_commit(), btree_sort_get_next(), btree_split_node(), btree_split_root(), btree_undo_delete_physical(), btree_undo_insert_object(), btree_undo_insert_object_unique_multiupd(), btree_undo_mvcc_delete(), btree_vacuum_insert_mvccid(), btree_vacuum_object(), build_att_type_change_map(), build_attr_change_map(), cas_main(), check_att_chg_allowed(), crash_handler(), csql(), csql_execute_statements(), csql_is_auto_commit_requested(), csql_set_trace(), csql_walk_statement(), css_get_connection_thread_pooling_configuration(), css_get_server_request_thread_pooling_configuration(), css_init(), css_is_shutdown_timeout_expired(), css_notify_ha_log_applier_state(), css_open_server_connection_socket(), css_process_new_client(), css_sockopt(), css_tcp_client_open_with_retry(), db_abs_dbval(), db_add_days_to_year(), db_add_time(), db_ascii(), db_bigint_to_binary_string(), db_ceil_dbval(), db_constraint_type(), db_conv(), db_convert_sec_to_time(), db_convert_time_to_sec(), db_convert_to_time(), db_crc32_dbval(), db_date_add_sub_interval_days(), db_date_add_sub_interval_expr(), db_date_dbval(), db_date_diff(), db_evaluate_json_search(), db_find_string_in_in_set(), db_floor_dbval(), db_from_unixtime(), db_get_cs_coll_info(), db_get_date_dayofyear(), db_get_date_item(), db_get_date_quarter(), db_get_date_totaldays(), db_get_date_week(), db_get_date_weekday(), db_get_schema_def_dbval(), db_get_time_item(), db_guid(), db_hex(), db_inet_aton(), db_inet_ntoa(), db_last_day(), db_mod_bigint(), db_mod_dbval(), db_mod_double(), db_mod_float(), db_mod_int(), db_mod_monetary(), db_mod_numeric(), db_mod_short(), db_mod_string(), db_round_dbval(), db_str_to_date(), db_string_aes_decrypt(), db_string_aes_encrypt(), db_string_chr(), db_string_compare(), db_string_concatenate(), db_string_from_base64(), db_string_insert_substring(), db_string_prefix_compare(), db_string_regexp_count(), db_string_regexp_instr(), db_string_regexp_like(), db_string_regexp_replace(), db_string_regexp_substr(), db_string_repeat(), db_string_replace(), db_string_rlike(), db_string_sha_one(), db_string_sha_two(), db_string_substring_index(), db_string_to_base64(), db_string_unique_prefix(), db_time_dbval(), db_time_diff(), db_trunc_dbval(), disk_manager_init(), do_alter_clause_change_attribute(), do_check_delete_trigger(), do_check_merge_trigger(), do_check_update_trigger(), do_create_entity(), do_execute_delete(), do_execute_do(), do_execute_insert(), do_execute_select(), do_execute_session_statement(), do_execute_statement(), do_execute_update(), do_select_internal(), do_statement(), do_update_new_notnull_cols_without_default(), does_op_specially_treat_null_arg(), dwb_file_sync_helper_daemon_is_running(), dwb_flush_block_daemon_is_running(), dwb_is_file_sync_helper_daemon_available(), dwb_is_flush_block_daemon_available(), dwb_read_page(), eliminate_duplicated_keys(), er_call_stack_dump_on_error(), er_init(), er_log_slow_query(), er_set_area_error(), er_set_internal(), eval_key_filter(), index_builder_loader_task::execute(), fetch_peek_arith(), fi_handler_random_exit(), file_header_sanity_check(), fileio_close(), fileio_flush_control_add_tokens(), fileio_lock(), fileio_mount(), fileio_open(), fileio_unlock(), get_backslash_escape_string(), get_date_weekday(), get_hour_minute_or_second(), get_object_print_format(), get_reference_names(), get_year_month_or_day(), hb_create_master_reader(), hb_thread_initialize(), heap_create_internal(), heap_initialize_hfid_table(), heap_object_upgrade_domain(), histo_is_supported(), hl_clear_lea_heap(), hl_lea_alloc(), hl_lea_free(), hl_lea_realloc(), hl_register_lea_heap(), hl_unregister_lea_heap(), cubthread::lockfree_hashmap< Key, T >::init(), cubthread::initialize(), intl_char_size(), intl_cmp_char(), intl_lower_string(), intl_next_char(), intl_prev_char(), jsp_alter_stored_procedure(), jsp_create_stored_procedure(), jsp_drop_stored_procedure(), la_apply_log_file(), loaddb_internal(), log_append_init_zip(), log_change_tran_as_completed(), log_complete_for_2pc(), log_create_internal(), log_dump_log_info(), log_final(), log_initialize(), log_initialize_internal(), log_recovery_analysis(), log_recovery_redo(), log_recovery_undo(), log_rollback_record(), log_rv_analysis_complete(), log_rv_undo_record(), log_set_no_logging(), logddl_write_end(), logpb_archive_active_log(), logpb_background_archiving(), logpb_checkpoint(), logpb_delete(), logpb_dump_parameter(), logpb_fetch_from_archive(), logpb_flush_all_append_pages(), logpb_flush_pages(), logpb_initialize_pool(), logpb_remove_all_in_log_path(), logpb_remove_archive_logs_exceed_limit(), logpb_remove_archive_logs_internal(), logpb_rename_all_volumes_files(), logpb_write_toflush_pages_to_archive(), logtb_enable_update(), logtb_rv_update_global_unique_stats_by_abs(), logtb_set_loose_end_tdes(), logtb_update_global_unique_stats_by_delta(), main(), JSON_PRIVATE_ALLOCATOR::Malloc(), mr_cmpdisk_char_internal(), mr_cmpval_char(), mr_cmpval_nchar(), mr_cmpval_string(), mr_cmpval_varnchar(), mr_data_cmpdisk_string(), net_server_request(), numeric_db_value_div(), parser_generate_do_stmt_xasl(), parser_generate_xasl(), parser_parse_file(), parser_parse_string_with_escapes(), perfmon_initialize(), pgbuf_flush_checkpoint(), pgbuf_flush_page_and_neighbors_fb(), pgbuf_flush_seq_list(), pgbuf_flush_victim_candidates(), pgbuf_get_victim_candidates_from_lru(), pgbuf_initialize(), pr_clear_value(), pt_bind_names(), pt_bind_value_to_hostvar_local(), pt_check_create_entity(), pt_check_enum_data_type(), pt_check_expr_collation(), pt_coerce_expression_argument(), pt_coerce_value_internal(), pt_eval_expr_type(), pt_evaluate_db_value_expr(), pt_fold_const_expr(), pt_get_expression_definition(), pt_replace_names_in_update_values(), pt_semantic_check_local(), pt_to_buildlist_proc(), pt_to_index_attrs(), pt_to_pred_expr_local_with_arg(), pt_upd_domain_info(), pt_wrap_collection_with_cast_op(), pwrite_with_injected_fault(), qdata_add_date_to_dbval(), qdata_add_dbval(), qdata_divide_dbval(), qdata_get_dbval_from_constant_regu_variable(), qdata_group_concat_first_value(), qdata_group_concat_value(), qdata_multiply_dbval(), qdata_strcat_dbval(), qdata_subtract_dbval(), qdata_unary_minus_dbval(), qdump_print_xasl(), qexec_execute_query(), qexec_fill_sort_limit(), qexec_groupby(), qexec_intprt_fnc(), qfile_update_qlist_count(), qmgr_execute_query(), qo_allocate_like_bound_for_index_scan(), qo_env_new(), qo_examine_merge_join(), qo_optimize_queries(), qo_rewrite_one_like_term(), qstr_grow_string(), JSON_PRIVATE_ALLOCATOR::Realloc(), regu_init(), round_date(), scan_key_compare(), scan_open_index_key_info_scan(), scan_open_index_scan(), session_state_create(), stran_server_auto_commit_or_abort(), sysprm_load_and_init_internal(), tp_domain_select(), tp_value_auto_cast(), tp_value_cast_internal(), tz_get_leapsec_support(), unicode_compose_string(), unicode_decompose_string(), unicode_string_need_compose(), unicode_string_need_decompose(), unloaddb(), vacuum_boot(), vacuum_consume_buffer_log_blocks(), vacuum_data_unload_first_and_last_page(), vacuum_finalize(), vacuum_initialize(), vacuum_is_file_dropped(), vacuum_min_log_pageid_to_keep(), vacuum_process_log_block(), vacuum_produce_log_block_data(), ws_abort_mops(), ws_cache(), ws_clear_all_hints(), ws_clear_hints(), ws_decache(), ws_final(), ws_set_lock(), xboot_emergency_patch(), xbtree_load_index(), xbtree_load_online_index(), xcache_check_recompilation_threshold(), xcache_dump(), xstats_get_statistics_from_server(), and xvacuum().
bool prm_get_commit_on_shutdown (void)
Definition at line 10733 of file system_parameter.c.
References PRM_COMMIT_ON_SHUTDOWN.
Referenced by csql_exit_session(), and uci_disconnect().
float prm_get_float_value (PARAM_ID prm_id)
Definition at line 10994 of file system_parameter.c.
References assert, PRM_GET_FLOAT, prm_get_value(), PRM_IS_FLOAT, and PRM_LAST_ID.
Referenced by heap_create_internal(), heap_reuse(), locator_multi_insert_force(), lock_is_local_deadlock_detection_interval_up(), pgbuf_get_page_flush_interval(), pgbuf_initialize(), pgbuf_initialize_aout_list(), pgbuf_wakeup_page_flush_daemon(), qo_expr_selectivity(), and xlock_dump().
int* prm_get_integer_list_value (PARAM_ID prm_id)
Definition at line 11025 of file system_parameter.c.
References assert, PRM_GET_INTEGER_LIST, prm_get_value(), PRM_IS_INTEGER_LIST, and PRM_LAST_ID.
Referenced by sysprm_find_err_in_integer_list(), and sysprm_find_fi_code_in_integer_list().
int prm_get_integer_value (PARAM_ID prm_id)
Definition at line 10964 of file system_parameter.c.
References assert, PRM_GET_INT, prm_get_value(), PRM_IS_INTEGER, PRM_IS_KEYWORD, and PRM_LAST_ID.
Referenced by boot_create_all_volumes(), boot_initialize_client(), boot_restart_client(), boot_restart_server(), btree_key_insert_new_key(), btree_merge_node(), btree_merge_root(), btree_split_node(), btree_split_root(), btree_verify_node(), compactdb_start(), create_or_drop_index_helper(), csect_demote_critical_section(), csect_enter_critical_section(), csect_enter_critical_section_as_reader(), csect_promote_critical_section(), csql_set_trace(), css_check_magic_with_socket(), css_connect_to_cubrid_server(), css_get_connection_thread_timeout_configuration(), css_get_normal_client_max_conn(), css_get_server_request_thread_timeout_configuration(), css_master_thread(), css_server_connect(), css_server_connect_part_two(), css_sockopt(), css_tcp_client_open_with_retry(), db_acos_dbval(), db_asin_dbval(), db_compile_statement_local(), db_error_init(), db_execute_and_keep_statement_local(), db_get_date_week(), db_json_path_is_token_valid_array_index(), db_power_dbval(), db_sqrt_dbval(), disk_manager_init(), do_alter_one_clause_with_template(), do_create_entity(), do_prepare_merge(), do_scope(), do_set_trace_to_query_flag(), dwb_create_internal(), dwb_file_sync_helper(), dwb_flush_block(), dwb_write_block(), er_file_open(), er_log(), er_set_area_error(), er_set_internal(), eval_action(), eval_condition(), eval_pred(), event_file_open(), event_log_start(), fetch_peek_arith(), file_tempcache_init(), file_tempcache_put(), fileio_compensate_flush(), fileio_flush_control_add_tokens(), fileio_get_lockf_type(), fileio_initialize_backup(), fileio_initialize_backup_thread(), fileio_mount(), fileio_read(), fileio_read_backup(), fileio_read_pages(), fileio_synchronize(), fileio_unformat_and_rename(), fileio_write(), fileio_write_pages(), fpcache_initialize(), hb_cleanup_conn_and_start_process(), hb_cluster_calc_score(), hb_cluster_initialize(), hb_cluster_is_received_heartbeat_from_all(), hb_cluster_job_calc_score(), hb_cluster_job_check_ping(), hb_cluster_job_failback(), hb_cluster_job_failover(), hb_cluster_job_heartbeat(), hb_cluster_job_init(), hb_cluster_send_heartbeat_req(), hb_deregister_process(), hb_master_init(), hb_process_master_request(), hb_resource_job_change_mode(), hb_resource_job_cleanup_all(), hb_resource_job_confirm_cleanup_all(), hb_resource_job_confirm_dereg(), hb_resource_job_confirm_start(), hb_resource_job_demote_confirm_shutdown(), hb_resource_job_demote_start_shutdown(), hb_resource_job_initialize(), hb_resource_job_proc_dereg(), hb_resource_job_proc_start(), hb_thread_check_disk_failure(), heap_check_all_pages(), heap_reuse(), heap_stats_add_bestspace(), heap_stats_find_page_in_bestspace(), heap_stats_sync_bestspace(), heap_stats_update(), heap_vpid_alloc(), cubthread::is_logging_configured(), is_server_insert_allowed(), javasp_start_server(), jsp_start_server(), la_apply_log_file(), la_create_repl_filter(), la_delay_replica(), la_get_adaptive_time_commit_interval(), la_log_page_check(), la_remove_archive_logs(), ldr_clear_context(), loaddb_internal(), lock_add_composite_lock(), lock_classes_lock_hint(), lock_finalize_composite_lock(), lock_object(), lock_scan(), lock_subclass(), log_complete_for_2pc(), log_create_internal(), log_get_checkpoint_interval(), log_get_log_group_commit_interval(), log_initialize_internal(), log_is_log_flush_daemon_available(), logpb_archive_active_log(), logpb_backup(), logpb_dump_parameter(), logpb_flush_all_append_pages(), logpb_initialize_pool(), logpb_next_append_page(), logpb_remove_archive_logs_exceed_limit(), logpb_start_append(), logpb_write_toflush_pages_to_archive(), logwr_log_ha_filestat_to_string(), main(), net_client_init(), net_server_start(), perfmon_initialize(), pgbuf_flush_chkpt_seq_list(), pgbuf_get_check_page_validation_level(), pgbuf_get_page_flush_interval(), pgbuf_initialize(), pgbuf_initialize_lru_list(), pgbuf_initialize_page_quota_parameters(), pt_check_ordby_num_for_multi_range_opt(), pt_common_type(), pt_eval_expr_type(), pt_evaluate_db_value_expr(), pt_plan_query(), pt_recompile_for_limit_optimizations(), qdata_add_bigint_to_date(), qdata_add_bigint_to_time(), qdata_add_bigint_to_timestamptz(), qdata_add_bigint_to_utime(), qdata_add_int_to_date(), qdata_add_int_to_timestamptz(), qdata_add_int_to_utime(), qdata_add_monetary(), qdata_add_short_to_date(), qdata_add_short_to_timestamptz(), qdata_add_short_to_utime(), qexec_execute_cte(), qexec_execute_mainblock(), qexec_setup_topn_proc(), qfile_initialize(), qfile_initialize_list_cache(), qfile_update_list_cache_entry(), qmgr_create_new_temp_file(), qmgr_create_result_file(), qmgr_get_new_page(), qmgr_initialize_temp_file_list(), qmgr_is_allowed_result_cache(), qo_discover_sort_limit_nodes(), qo_follow_cost(), qo_get_optimization_param(), qo_iscan_cost(), qo_nljoin_cost(), qo_optimize_queries(), qo_set_optimization_param(), qo_sort_cost(), session_check_timeout(), cubthread::manager::set_max_thread_count_from_config(), set_optimization_level(), sort_add_new_file(), sort_inphase_sort(), sort_listfile(), sqmgr_execute_query(), start_csql(), unloaddb(), util_get_ha_mode_for_sa_utils(), util_get_ha_parameters(), util_log_file_fopen(), vacuum_boot(), cubload::worker_manager_register_session(), ws_init(), xboot_register_client(), xcache_initialize(), xheap_reclaim_addresses(), and xlock_dump().
int prm_get_master_port_id (void)
Definition at line 10727 of file system_parameter.c.
References PRM_TCP_PORT_ID.
Referenced by check_all_services_status(), connect_to_master_for_server_monitor(), css_get_master_domain_path(), hb_connect_to_master(), is_server_running(), master_util_config_startup(), process_heartbeat_deregister(), process_heartbeat_reload(), process_heartbeat_replication(), process_heartbeat_start(), process_heartbeat_status(), process_heartbeat_stop(), process_master(), process_server(), and process_service().
const char* prm_get_name (PARAM_ID prm_id)
Definition at line 10911 of file system_parameter.c.
References assert, sysprm_param::name, and PRM_LAST_ID.
Referenced by addvoldb(), applyinfo(), applylogdb(), backupdb(), boot_restart_server(), checkdb(), compactdb(), copydb(), copylogdb(), createdb(), deletedb(), diagdb(), hb_cluster_initialize(), hb_reload_config(), installdb(), la_delay_replica(), loaddb_internal(), main(), optimizedb(), paramdump(), renamedb(), restoredb(), restoreslave(), spacedb(), statdump(), synccolldb(), unloaddb(), util_get_ha_parameters(), util_make_ha_conf(), vacuumdb(), and xboot_shutdown_server().
static int prm_get_next_param_value (char ** data, char ** prm, char ** value) static
Definition at line 10790 of file system_parameter.c.
References char_isspace(), cleanup(), err, sysprm_param::name, NULL, p, PRM_ERR_BAD_STRING, PRM_ERR_BAD_VALUE, PRM_ERR_NO_ERROR, and sysprm_param::value.
Referenced by sysprm_make_default_values(), and sysprm_validate_change_parameters().
char* prm_get_string_value (PARAM_ID prm_id)
Definition at line 11009 of file system_parameter.c.
References assert, PRM_GET_STRING, prm_get_value(), PRM_IS_STRING, and PRM_LAST_ID.
Referenced by applyinfo(), applylogdb(), boot_find_rest_temp_volumes(), boot_get_new_volume_name_and_id(), boot_make_temp_volume_fullname(), boot_restart_client(), boot_restart_server(), cfg_create_host_list(), cfg_read_directory(), crash_handler(), css_get_required_conn_num_for_ha(), css_notify_ha_log_applier_state(), delete_all_slave_ha_apply_info(), dl_initiate_dynamic_loader(), do_evaluate_default_expr(), er_event(), er_event_final(), er_event_init(), er_init(), hb_cluster_initialize(), hb_master_init(), hb_reload_config(), insert_ha_apply_info(), jsp_start_server(), la_create_repl_filter(), la_delay_replica(), la_log_page_check(), lang_get_client_charset(), lang_get_client_collation(), load_properties(), pt_check_default_vclass_query_spec(), pt_eval_expr_type(), pt_find_attr_in_class_list(), pt_resolve_default_value(), qexec_execute_insert(), sysprm_generate_new_value(), sysprm_init_intl_param(), sysprm_print_parameters_for_ha_repl(), tde_make_keys_file_fullname(), tz_get_session_local_timezone(), tz_get_system_timezone(), util_get_ha_parameters(), and util_is_replica_node().
void* prm_get_value (PARAM_ID prm_id)
Definition at line 10929 of file system_parameter.c.
References assert, BO_IS_SERVER_RESTARTED, PRM_LAST_ID, PRM_SERVER_SESSION, session_get_session_parameter(), thread_get_thread_entry_info(), session_param::value, and sysprm_param::value.
Referenced by css_sockopt(), prm_get_bigint_value(), prm_get_bool_value(), prm_get_float_value(), prm_get_integer_list_value(), prm_get_integer_value(), and prm_get_string_value().
static int prm_io_pages_to_size (void * out_val, SYSPRM_DATATYPE out_type, void * in_val, SYSPRM_DATATYPE in_type) static
Definition at line 7163 of file system_parameter.c.
References assert_release, IO_PAGESIZE, NO_ERROR, NULL, PRM_BIGINT, PRM_ERR_BAD_VALUE, PRM_FLOAT, and PRM_INTEGER.
static const KEYVAL * prm_keyword (int val, const char * name, const KEYVAL * tbl, int dim) static
Definition at line 10191 of file system_parameter.c.
References i, intl_mbs_casecmp(), and NULL.
Referenced by prm_print(), sysprm_generate_new_value(), and sysprm_print_sysprm_value().
static int prm_load_by_section (INI_TABLE * ini, const char * section, bool ignore_section, bool reload, const char * file, const int load_flags) static
Definition at line 6845 of file system_parameter.c.
References error(), i, ini_hassec(), ini_seccmp(), ini_table::key, ini_table::lineno, sysprm_param::name, NO_ERROR, NULL, PRM_ERR_BAD_VALUE, PRM_ERR_CANNOT_CHANGE, PRM_ERR_DEPRICATED, PRM_ERR_UNKNOWN_PARAM, prm_find(), PRM_IS_DEPRECATED, PRM_IS_FOR_CLIENT, PRM_IS_FOR_HA, PRM_IS_FOR_SERVER, PRM_IS_OBSOLETED, PRM_IS_RELOADABLE, PRM_NAME_INTL_CHECK_INPUT_STRING, PRM_NAME_INTL_COLLATION, PRM_NAME_INTL_DATE_LANG, PRM_NAME_INTL_MBS_SUPPORT, PRM_NAME_INTL_NUMBER_LANG, PRM_NAME_JAVA_STORED_PROCEDURE_PORT, PRM_NAME_SERVER_TIMEZONE, PRM_NAME_TIMEZONE, prm_report_bad_entry(), prm_set(), ini_table::size, sysprm_param::static_flag, strlen, SYSPRM_LOAD_IS_IGNORE_HA, SYSPRM_LOAD_IS_IGNORE_INTL, tz_get_client_tz_region_session(), tz_load(), tz_set_tz_region_system(), tz_str_to_region(), ini_table::val, and sysprm_param::value.
Referenced by prm_read_and_parse_ini_file().
static int prm_log_pages_to_size (void * out_val, SYSPRM_DATATYPE out_type, void * in_val, SYSPRM_DATATYPE in_type) static
Definition at line 7257 of file system_parameter.c.
References assert_release, LOG_PAGESIZE, NO_ERROR, NULL, PRM_BIGINT, PRM_ERR_BAD_VALUE, PRM_FLOAT, and PRM_INTEGER.
static int prm_min_to_sec (void * out_val, SYSPRM_DATATYPE out_type, void * in_val, SYSPRM_DATATYPE in_type) static
Definition at line 7429 of file system_parameter.c.
References assert_release, NO_ERROR, NULL, PRM_ERR_BAD_RANGE, PRM_ERR_BAD_VALUE, and PRM_INTEGER.
static int prm_msec_to_sec (void * out_val, SYSPRM_DATATYPE out_type, void * in_val, SYSPRM_DATATYPE in_type) static
Definition at line 7306 of file system_parameter.c.
References assert_release, NO_ERROR, NULL, ONE_SEC, PRM_BIGINT, PRM_ERR_BAD_RANGE, PRM_ERR_BAD_VALUE, and PRM_INTEGER.
static int prm_print (const SYSPRM_PARAM * prm, char * buf, size_t len, PRM_PRINT_MODE print_mode, PRM_PRINT_VALUE_MODE print_value_mode) static
Definition at line 7915 of file system_parameter.c.
References assert, assert_release, sysprm_param::default_value, error(), sysprm_param::get_dup, i, sysprm_param::id, intl_mbs_casecmp(), keyval::key, sysprm_param::name, NO_ERROR, NULL, PRM_ADJUST_FOR_GET_BIGINT_TO_BIGINT, PRM_ADJUST_FOR_GET_FLOAT_TO_BIGINT, PRM_ADJUST_FOR_GET_FLOAT_TO_FLOAT, PRM_ADJUST_FOR_GET_INTEGER_TO_BIGINT, PRM_ADJUST_FOR_GET_INTEGER_TO_INTEGER, PRM_DEFAULT_BUFFER_SIZE, PRM_DIFFERENT_UNIT, PRM_GET_BIGINT, PRM_GET_BOOL, PRM_GET_FLOAT, PRM_GET_INT, PRM_GET_INTEGER_LIST, PRM_GET_STRING, PRM_HAS_SIZE_UNIT, PRM_HAS_TIME_UNIT, PRM_IS_BIGINT, PRM_IS_BOOLEAN, PRM_IS_FLOAT, PRM_IS_INTEGER, PRM_IS_INTEGER_LIST, PRM_IS_KEYWORD, PRM_IS_STRING, prm_keyword(), PRM_NAME_CHECK_PEER_ALIVE, PRM_NAME_COMPAT_MODE, PRM_NAME_ER_LOG_LEVEL, PRM_NAME_FAULT_INJECTION_TEST, PRM_NAME_HA_LOG_APPLIER_STATE, PRM_NAME_HA_MODE, PRM_NAME_HA_MODE_FOR_SA_UTILS_ONLY, PRM_NAME_HA_REPL_FILTER_TYPE, PRM_NAME_HA_SERVER_STATE, PRM_NAME_LOG_ISOLATION_LEVEL, PRM_NAME_PB_DEBUG_PAGE_VALIDATION_LEVEL, PRM_NAME_QUERY_TRACE_FORMAT, PRM_NAME_TDE_DEFAULT_ALGORITHM, PRM_PRINT_DEFAULT_VAL, PRM_PRINT_ID, PRM_PRINT_NAME, sysprm_param::static_flag, strlen, sysprm_get_id(), util_byte_to_size_string(), util_msec_to_time_string(), and sysprm_param::value.
Referenced by sysprm_dump_parameters(), sysprm_make_default_values(), sysprm_print_parameters_for_ha_repl(), sysprm_print_parameters_for_qry_string(), and sysprm_set_to_default().
static int prm_read_and_parse_ini_file (const char * prm_file_name, const char * db_name, const bool reload, const int load_flags) static
Definition at line 7046 of file system_parameter.c.
References CUB_MAXHOSTNAMELEN, error(), GETHOSTNAME, HA_MODE_OFF, ini_parser_free(), ini_parser_load(), MSGCAT_CATALOG_CUBRID, msgcat_message(), MSGCAT_SET_PARAMETERS, NO_ERROR, NULL, PRM_ERR_CANT_OPEN_INIT, PRM_ERR_FILE_ERR, prm_file_has_been_loaded(), PRM_HA_MODE, prm_load_by_section(), and SYSPRM_LOAD_IS_IGNORE_HA.
Referenced by sysprm_load_and_init_internal().
static void prm_report_bad_entry (const char * key, int line, int err, const char * where) static
Definition at line 10227 of file system_parameter.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_PRM_BAD_VALUE, ER_PRM_UNKNOWN_SYSPRM, er_set(), PARAM_MSG_FMT, PRM_ERR_BAD_ENV_VAR, PRM_ERR_BAD_LINE, PRM_ERR_BAD_PARAM, PRM_ERR_BAD_RANGE, PRM_ERR_BAD_STRING, PRM_ERR_BAD_VALUE, PRM_ERR_DEPRICATED, PRM_ERR_NO_MEM_FOR_PRM, PRM_ERR_RESET_BAD_RANGE, PRM_ERR_UNIX_ERROR, and PRM_ERR_UNKNOWN_PARAM.
Referenced by prm_check_environment(), and prm_load_by_section().
static int prm_sec_to_min (void * out_val, SYSPRM_DATATYPE out_type, void * in_val, SYSPRM_DATATYPE in_type) static
Definition at line 7390 of file system_parameter.c.
References assert_release, NO_ERROR, NULL, PRM_ERR_BAD_VALUE, and PRM_INTEGER.
static int prm_sec_to_msec (void * out_val, SYSPRM_DATATYPE out_type, void * in_val, SYSPRM_DATATYPE in_type) static
Definition at line 7348 of file system_parameter.c.
References assert_release, NO_ERROR, NULL, ONE_SEC, PRM_BIGINT, PRM_ERR_BAD_VALUE, and PRM_INTEGER.
static int prm_set (SYSPRM_PARAM * prm, const char * value, bool set_flag) static
Definition at line 9718 of file system_parameter.c.
References error(), PRM_ERR_NO_ERROR, sysprm_generate_new_value(), and sysprm_set_value().
Referenced by prm_check_environment(), prm_load_by_section(), prm_set_compound(), prm_tune_parameters(), sysprm_final(), sysprm_init_intl_param(), sysprm_load_and_init_internal(), and sysprm_set_er_log_file().
void prm_set_bigint_value (PARAM_ID prm_id, UINT64 value)
Definition at line 11167 of file system_parameter.c.
References assert, PRM_GET_BIGINT, PRM_IS_BIGINT, PRM_LAST_ID, sysprm_update_flag_different(), and sysprm_param::value.
Referenced by sysprm_set_system_parameter_value().
void prm_set_bool_value (PARAM_ID prm_id, bool value)
Definition at line 11076 of file system_parameter.c.
References assert, PRM_GET_BOOL, PRM_IS_BOOLEAN, PRM_LAST_ID, sysprm_update_flag_different(), and sysprm_param::value.
Referenced by csql_set_trace(), do_set_query_trace(), sysprm_set_system_parameter_value(), and xboot_restart_from_backup().
static void prm_set_compound (SYSPRM_PARAM * param, const char ** compound_param_values[], const int values_count, bool set_flag) static
Definition at line 10753 of file system_parameter.c.
References assert, i, sysprm_param::lower_limit, NULL, prm_find(), PRM_IS_INTEGER, PRM_IS_KEYWORD, prm_set(), prm_set_default(), sysprm_param::upper_limit, and sysprm_param::value.
Referenced by prm_compound_has_changed().
static int prm_set_default (SYSPRM_PARAM * prm) static
Definition at line 9978 of file system_parameter.c.
References BO_IS_SERVER_RESTARTED, sysprm_param::default_value, sysprm_param::dynamic_flag, ER_FAILED, free_and_init, sysprm_param::id, NO_ERROR, NULL, PRM_ALLOCATED, PRM_CLEAR_BIT, PRM_DEFAULT_USED, PRM_DIFFERENT, PRM_ERR_UNKNOWN_PARAM, PRM_GET_BIGINT, PRM_GET_BOOL, PRM_GET_FLOAT, PRM_GET_INT, PRM_GET_INTEGER_LIST, PRM_GET_STRING, PRM_IS_ALLOCATED, PRM_IS_BIGINT, PRM_IS_BOOLEAN, PRM_IS_FLOAT, PRM_IS_FOR_QRY_STRING, PRM_IS_FOR_SESSION, PRM_IS_INTEGER, PRM_IS_INTEGER_LIST, PRM_IS_KEYWORD, PRM_IS_STRING, PRM_SET_BIT, session_get_session_parameter(), sysprm_param::static_flag, sysprm_get_id(), thread_get_thread_entry_info(), and sysprm_param::value.
Referenced by prm_set_compound(), prm_tune_parameters(), sysprm_final(), sysprm_load_and_init_internal(), and sysprm_set_to_default().
void prm_set_float_value (PARAM_ID prm_id, float value)
Definition at line 11094 of file system_parameter.c.
References assert, PRM_GET_FLOAT, PRM_IS_FLOAT, PRM_LAST_ID, sysprm_update_flag_different(), and sysprm_param::value.
Referenced by sysprm_set_system_parameter_value().
static int prm_set_force (SYSPRM_PARAM * prm, const char * value) static
Definition at line 9955 of file system_parameter.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), sysprm_param::force_value, free_and_init, NO_ERROR, NULL, PRM_ERR_NO_MEM_FOR_PRM, PRM_GET_STRING, strdup(), and strlen.
Referenced by sysprm_set_force(), and sysprm_set_to_default().
void prm_set_integer_list_value (PARAM_ID prm_id, int * value)
Definition at line 11140 of file system_parameter.c.
References assert, sysprm_param::dynamic_flag, free_and_init, NULL, PRM_ALLOCATED, PRM_CLEAR_BIT, PRM_GET_INTEGER_LIST, PRM_IS_ALLOCATED, PRM_IS_INTEGER_LIST, PRM_LAST_ID, PRM_SET_BIT, sysprm_update_flag_different(), and sysprm_param::value.
Referenced by sysprm_final(), and sysprm_set_system_parameter_value().
void prm_set_integer_value (PARAM_ID prm_id, int value)
Definition at line 11058 of file system_parameter.c.
References assert, PRM_GET_INT, PRM_IS_INTEGER, PRM_IS_KEYWORD, PRM_LAST_ID, sysprm_update_flag_different(), and sysprm_param::value.
Referenced by csql_set_trace(), css_transit_ha_server_state(), do_set_query_trace(), qo_set_optimization_param(), reset_optimization_level_as_saved(), set_optimization_level(), sysprm_set_system_parameter_value(), us_hb_applylogdb_start(), us_hb_copylogdb_start(), and us_hb_server_start().
void prm_set_string_value (PARAM_ID prm_id, char * value)
Definition at line 11112 of file system_parameter.c.
References assert, sysprm_param::dynamic_flag, free_and_init, NULL, PRM_ALLOCATED, PRM_CLEAR_BIT, PRM_GET_STRING, PRM_IS_ALLOCATED, PRM_IS_STRING, PRM_LAST_ID, PRM_SET_BIT, sysprm_update_flag_different(), and sysprm_param::value.
Referenced by sysprm_set_system_parameter_value().
static int prm_size_to_io_pages (void * out_val, SYSPRM_DATATYPE out_type, void * in_val, SYSPRM_DATATYPE in_type) static
Definition at line 7104 of file system_parameter.c.
References assert_release, IO_PAGESIZE, NO_ERROR, NULL, PRM_BIGINT, PRM_ERR_BAD_RANGE, PRM_ERR_BAD_VALUE, PRM_FLOAT, and PRM_INTEGER.
static int prm_size_to_log_pages (void * out_val, SYSPRM_DATATYPE out_type, void * in_val, SYSPRM_DATATYPE in_type) static
Definition at line 7198 of file system_parameter.c.
References assert_release, LOG_PAGESIZE, NO_ERROR, NULL, PRM_BIGINT, PRM_ERR_BAD_RANGE, PRM_ERR_BAD_VALUE, PRM_FLOAT, and PRM_INTEGER.
static void prm_tune_parameters (void) static
Definition at line 10610 of file system_parameter.c.
References assert, CUB_MAXHOSTNAMELEN, sysprm_param::dynamic_flag, GETHOSTNAME, HA_MODE_OFF, HB_MIN_DIFF_CHECK_DISK_FAILURE_INTERVAL_IN_SECS, NO_ERROR, NULL, PRM_DEFAULT_VAL_USED, prm_find(), PRM_FOR_QRY_STRING, PRM_GET_BOOL, PRM_GET_INT, PRM_NAME_HA_CHECK_DISK_FAILURE_INTERVAL_IN_SECS, PRM_NAME_HA_COPY_LOG_TIMEOUT, PRM_NAME_HA_MAX_PROCESS_DEREG_CONFIRM, PRM_NAME_HA_MODE, PRM_NAME_HA_NODE_LIST, PRM_NAME_HA_PROCESS_DEREG_CONFIRM_INTERVAL_IN_MSECS, PRM_NAME_SHUTDOWN_WAIT_TIME_IN_SECS, PRM_NAME_TEST_MODE, PRM_NAME_TZ_LEAP_SECOND_SUPPORT, PRM_NAME_XASL_CACHE_MAX_ENTRIES, prm_set(), prm_set_default(), sysprm_param::static_flag, sysprm_change_parameter_values(), sysprm_free_assign_values(), sysprm_get_force_server_parameters(), sysprm_tune_client_parameters(), and sysprm_param::value.
Referenced by sysprm_final(), and sysprm_load_and_init_internal().
static SESSION_PARAM * sysprm_alloc_session_parameters (void) static
Definition at line 11376 of file system_parameter.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), NULL, and NUM_SESSION_PRM.
Referenced by sysprm_load_and_init_internal(), and sysprm_unpack_session_parameters().
void sysprm_change_parameter_values (const SYSPRM_ASSIGN_VALUE * assignments, bool check, bool set_flag)
Definition at line 7870 of file system_parameter.c.
References css_set_accessible_ip_info(), GET_PRM, sysprm_assign_value::next, NULL, sysprm_assign_value::prm_id, PRM_ID_ACCESS_IP_CONTROL, PRM_IS_FOR_CLIENT, PRM_IS_FOR_SERVER, PRM_IS_FOR_SESSION, sysprm_param::static_flag, sysprm_get_id(), sysprm_set_value(), and sysprm_assign_value::value.
Referenced by db_set_system_parameters(), prm_tune_parameters(), and xsysprm_change_server_parameters().
int sysprm_check_range (const char * pname, void * value)
Definition at line 8908 of file system_parameter.c.
References error(), NULL, prm_check_range(), PRM_ERR_UNKNOWN_PARAM, and prm_find().
Referenced by createdb().
static void sysprm_clear_sysprm_value (SYSPRM_VALUE * value, SYSPRM_DATATYPE datatype) static
Definition at line 11351 of file system_parameter.c.
References free_and_init, sysprm_value::integer_list, PRM_INTEGER_LIST, PRM_STRING, and sysprm_value::str.
Referenced by sysprm_free_assign_values(), and sysprm_free_session_parameters().
static int sysprm_compare_values (void * first_value, void * second_value, unsigned int val_type) static
Definition at line 12136 of file system_parameter.c.
References assert, i, intl_mbs_casecmp(), NULL, PRM_BIGINT, PRM_BOOLEAN, PRM_FLOAT, PRM_GET_BIGINT, PRM_GET_BOOL, PRM_GET_FLOAT, PRM_GET_INT, PRM_GET_INTEGER_LIST, PRM_GET_STRING, PRM_INTEGER, PRM_INTEGER_LIST, PRM_KEYWORD, and PRM_STRING.
Referenced by sysprm_update_flag_different().
void sysprm_dump_parameters (FILE * fp)
Definition at line 6446 of file system_parameter.c.
References conf_path, db_name, i, MAX_NUM_OF_PRM_FILES_LOADED, NULL, NUM_PRM, prm_Files_loaded, PRM_IS_HIDDEN, PRM_IS_OBSOLETED, prm_print(), PRM_PRINT_CURR_VAL, PRM_PRINT_NAME, and sysprm_param::static_flag.
Referenced by paramdump(), sysprm_load_and_init_internal(), and xsysprm_dump_server_parameters().
void sysprm_final (void)
Definition at line 10282 of file system_parameter.c.
References ARG_FILE_LINE, assert, call_stack_dump_error_codes, conf_path, css_get_max_socket_fds(), CUB_MAXHOSTNAMELEN, sysprm_param::datatype, db_name, sysprm_param::dynamic_flag, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), fi_Groups, FI_TEST_NONE, free_and_init, GET_PRM, GETHOSTNAME, HA_MODE_OFF, HA_MODE_REPLICA, HA_SERVER_STATE_ACTIVE_STR, HA_SERVER_STATE_STANDBY_STR, i, MAX_NUM_OF_PRM_FILES_LOADED, MSGCAT_CATALOG_CUBRID, msgcat_message(), MSGCAT_SET_PARAMETERS, sysprm_param::name, NULL, NUM_PRM, PRM_ALLOCATED, PRM_CLEAR_BIT, prm_css_max_clients_upper, PRM_DEFAULT_USED, PRM_DEFAULT_VAL_USED, PRM_ERR_NO_ERROR, PRM_ERR_NO_VALUE, prm_Files_loaded, prm_find(), PRM_FOR_QRY_STRING, PRM_GET_BOOL, PRM_GET_INT, PRM_GET_INTEGER_LIST, PRM_GET_STRING, PRM_HA_MODE, PRM_HA_MODE_FOR_SA_UTILS_ONLY, PRM_ID_CALL_STACK_DUMP_ACTIVATION, PRM_ID_FAULT_INJECTION_IDS, PRM_ID_FAULT_INJECTION_TEST, PRM_INTEGER_LIST, PRM_IS_ALLOCATED, PRM_IS_SET, PRM_NAME_AUTO_RESTART_SERVER, PRM_NAME_CSS_MAX_CLIENTS, PRM_NAME_FORCE_REMOVE_LOG_ARCHIVES, PRM_NAME_HA_MODE, PRM_NAME_HA_NODE_LIST, PRM_NAME_HA_SERVER_STATE, PRM_NAME_LIST_MAX_QUERY_CACHE_ENTRIES, PRM_NAME_LIST_MAX_QUERY_CACHE_PAGES, PRM_NAME_LIST_QUERY_CACHE_MODE, PRM_NAME_LOG_BACKGROUND_ARCHIVING, PRM_NAME_LOG_MAX_ARCHIVES, PRM_NAME_PB_AOUT_RATIO, PRM_NAME_SERVER_TIMEZONE, PRM_NAME_TEST_MODE, PRM_NAME_TZ_LEAP_SECOND_SUPPORT, PRM_NAME_XASL_CACHE_MAX_ENTRIES, PRM_SET, prm_set(), PRM_SET_BIT, prm_set_default(), prm_set_integer_list_value(), PRM_STRING, prm_tune_parameters(), sysprm_param::static_flag, TZ_GENERIC_NAME_SIZE, tz_get_data(), tz_resolve_os_timezone(), and sysprm_param::value.
Referenced by boot_client_all_finalize(), boot_initialize_client(), boot_restart_client(), and boot_server_all_finalize().
bool sysprm_find_err_in_integer_list (PARAM_ID prm_id, int error_code)
Definition at line 11186 of file system_parameter.c.
References i, NULL, and prm_get_integer_list_value().
Referenced by er_call_stack_dump_on_error(), er_notify_event_on_error(), la_ignore_on_error(), and la_retry_on_error().
bool sysprm_find_fi_code_in_integer_list (PARAM_ID prm_id, int fi_code)
Definition at line 11215 of file system_parameter.c.
References i, NULL, and prm_get_integer_list_value().
Referenced by fi_set(), fi_set_force(), fi_state(), fi_test(), and fi_test_on().
void sysprm_free_assign_values (SYSPRM_ASSIGN_VALUE ** assign_values_ptr)
Definition at line 11891 of file system_parameter.c.
References free_and_init, GET_PRM_DATATYPE, sysprm_assign_value::next, NULL, sysprm_assign_value::prm_id, sysprm_clear_sysprm_value(), and sysprm_assign_value::value.
Referenced by db_get_system_parameters(), db_set_system_parameters(), prm_tune_parameters(), sprm_server_change_parameters(), sprm_server_get_force_parameters(), sprm_server_obtain_parameters(), sysprm_obtain_parameters(), sysprm_obtain_server_parameters(), sysprm_unpack_assign_values(), sysprm_validate_change_parameters(), and xsysprm_get_force_server_parameters().
void sysprm_free_session_parameters (SESSION_PARAM ** session_parameters_ptr)
Definition at line 11403 of file system_parameter.c.
References assert, session_param::datatype, free_and_init, i, NULL, NUM_SESSION_PRM, sysprm_clear_sysprm_value(), and session_param::value.
Referenced by csession_find_or_create_session(), session_state_uninit(), sysprm_get_id(), sysprm_load_and_init_internal(), and sysprm_unpack_session_parameters().
static SYSPRM_ERR sysprm_generate_new_value (SYSPRM_PARAM * prm, const char * value, bool check, SYSPRM_VALUE * new_value) static
Definition at line 9077 of file system_parameter.c.
References ARG_FILE_LINE, assert, sysprm_value::b, sysprm_value::bi, bool, call_stack_dump_error_codes, sysprm_param::datatype, sysprm_param::default_value, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), sysprm_value::f, free_and_init, sysprm_value::i, sysprm_value::integer_list, intl_mbs_casecmp(), LANG_GET_BINARY_COLLATION, lang_get_collation_by_name(), lang_get_collation_name(), lang_get_lang_id_from_name(), lang_get_Lang_name(), LANG_SYS_CODESET, sysprm_param::lower_limit, max, min, sysprm_param::name, NO_ERROR, NULL, p, parse_int(), PRM_ADJUST_FOR_SET_BIGINT_TO_BIGINT, PRM_ADJUST_FOR_SET_BIGINT_TO_FLOAT, PRM_ADJUST_FOR_SET_BIGINT_TO_INTEGER, PRM_ADJUST_FOR_SET_FLOAT_TO_FLOAT, PRM_ADJUST_FOR_SET_INTEGER_TO_INTEGER, PRM_BIGINT, PRM_BOOLEAN, prm_check_range(), PRM_DIFFERENT_UNIT, PRM_ERR_BAD_RANGE, PRM_ERR_BAD_VALUE, PRM_ERR_CANNOT_CHANGE, PRM_ERR_NO_ERROR, PRM_ERR_NO_MEM_FOR_PRM, PRM_ERR_NOT_FOR_CLIENT, PRM_ERR_NOT_FOR_CLIENT_NO_AUTH, PRM_ERR_NOT_FOR_SERVER, PRM_ERR_UNKNOWN_PARAM, PRM_FLOAT, PRM_GET_BIGINT, PRM_GET_BOOL, PRM_GET_FLOAT, PRM_GET_INT, PRM_GET_INTEGER_LIST, PRM_GET_STRING, prm_get_string_value(), PRM_HAS_SIZE_UNIT, PRM_HAS_TIME_UNIT, PRM_ID_CALL_STACK_DUMP_ACTIVATION, PRM_ID_INTL_COLLATION, PRM_ID_INTL_DATE_LANG, PRM_ID_INTL_NUMBER_LANG, PRM_ID_SERVER_TIMEZONE, PRM_ID_TIMEZONE, PRM_INTEGER, PRM_INTEGER_LIST, PRM_IS_FOR_CLIENT, PRM_IS_FOR_SERVER, PRM_IS_FOR_SESSION, PRM_KEYWORD, prm_keyword(), PRM_NAME_CHECK_PEER_ALIVE, PRM_NAME_COMPAT_MODE, PRM_NAME_ER_LOG_LEVEL, PRM_NAME_FAULT_INJECTION_TEST, PRM_NAME_HA_LOG_APPLIER_STATE, PRM_NAME_HA_MODE, PRM_NAME_HA_MODE_FOR_SA_UTILS_ONLY, PRM_NAME_HA_REPL_FILTER_TYPE, PRM_NAME_HA_SERVER_STATE, PRM_NAME_INTL_COLLATION, PRM_NAME_INTL_DATE_LANG, PRM_NAME_INTL_NUMBER_LANG, PRM_NAME_LOG_ISOLATION_LEVEL, PRM_NAME_PB_DEBUG_PAGE_VALIDATION_LEVEL, PRM_NAME_QUERY_TRACE_FORMAT, PRM_NAME_TDE_DEFAULT_ALGORITHM, PRM_NAME_TIMEZONE, PRM_NO_TYPE, PRM_STRING, PRM_VALUE_DEFAULT, PRM_VALUE_MAX, PRM_VALUE_MIN, sysprm_param::set_dup, sysprm_param::static_flag, sysprm_value::str, str_to_uint64(), strdup(), strlen, sysprm_get_id(), sysprm_get_param_range(), tz_str_to_region(), sysprm_param::upper_limit, util_size_string_to_byte(), util_time_string_to_msec(), and keyval::val.
Referenced by prm_set(), and sysprm_validate_change_parameters().
static PARAM_ID sysprm_get_id (const SYSPRM_PARAM * prm) static
Definition at line 11919 of file system_parameter.c.
References assert, sysprm_value::b, sysprm_value::bi, session_param::datatype, sysprm_param::default_value, sysprm_value::f, session_param::flag, free_and_init, sysprm_value::i, i, sysprm_param::id, sysprm_value::integer_list, NO_ERROR, NULL, NUM_SESSION_PRM, PRM_ALLOCATED, PRM_BIGINT, PRM_BOOLEAN, PRM_CLEAR_BIT, PRM_ERR_NO_ERROR, PRM_FIRST_ID, PRM_FLOAT, PRM_GET_BIGINT, PRM_GET_BOOL, PRM_GET_FLOAT, PRM_GET_INT, PRM_GET_INTEGER_LIST, PRM_GET_STRING, PRM_ID_TIMEZONE, PRM_INTEGER, PRM_INTEGER_LIST, PRM_IS_ALLOCATED, PRM_KEYWORD, PRM_LAST_ID, PRM_SET_BIT, PRM_STRING, session_get_session_parameters(), session_get_session_tz_region(), session_set_session_parameters(), sysprm_value::str, strlen, sysprm_free_session_parameters(), thread_get_thread_entry_info(), tz_str_to_region(), session_param::value, and sysprm_param::value.
Referenced by prm_compound_has_changed(), prm_print(), prm_set_default(), sysprm_change_parameter_values(), sysprm_generate_new_value(), sysprm_make_default_values(), sysprm_obtain_parameters(), sysprm_set_system_parameter_value(), sysprm_set_value(), and sysprm_validate_change_parameters().
static SYSPRM_ERR sysprm_get_param_range (SYSPRM_PARAM * prm, void * min, void * max) static
Definition at line 8775 of file system_parameter.c.
References error(), sysprm_param::lower_limit, NO_ERROR, PRM_ADJUST_FOR_GET_BIGINT_TO_BIGINT, PRM_ADJUST_FOR_GET_FLOAT_TO_FLOAT, PRM_ADJUST_FOR_GET_INTEGER_TO_INTEGER, PRM_DIFFERENT_UNIT, PRM_ERR_BAD_VALUE, PRM_ERR_NO_ERROR, PRM_GET_BIGINT, PRM_GET_FLOAT, PRM_GET_INT, PRM_IS_BIGINT, PRM_IS_FLOAT, PRM_IS_INTEGER, sysprm_param::static_flag, ULLONG_MAX, and sysprm_param::upper_limit.
Referenced by sysprm_generate_new_value(), and sysprm_get_range().
int sysprm_get_range (const char * pname, void * min, void * max)
Definition at line 8884 of file system_parameter.c.
References assert, sysprm_param::get_dup, NULL, PRM_DIFFERENT_UNIT, PRM_ERR_UNKNOWN_PARAM, prm_find(), sysprm_param::static_flag, and sysprm_get_param_range().
Referenced by createdb().
int sysprm_get_session_parameters_count (void)
Definition at line 12626 of file system_parameter.c.
References assert, sysprm_param::dynamic_flag, session_param::flag, GET_PRM, i, NUM_SESSION_PRM, session_param::prm_id, sysprm_set_sysprm_value_from_parameter(), sysprm_update_session_prm_flag_allocated(), and session_param::value.
Referenced by session_get_session_parameter().
int sysprm_init_intl_param (void)
Definition at line 12492 of file system_parameter.c.
References sysprm_param::dynamic_flag, error(), LANG_GET_BINARY_COLLATION, lang_get_collation_name(), lang_get_Lang_name(), LANG_SYS_CODESET, NO_ERROR, NULL, prm_find(), prm_get_string_value(), PRM_ID_INTL_COLLATION, PRM_ID_INTL_DATE_LANG, PRM_ID_INTL_NUMBER_LANG, PRM_ID_SERVER_TIMEZONE, PRM_ID_TIMEZONE, PRM_IS_SET, PRM_NAME_INTL_COLLATION, PRM_NAME_INTL_DATE_LANG, PRM_NAME_INTL_NUMBER_LANG, PRM_NAME_TIMEZONE, and prm_set().
Referenced by boot_restart_client().
int sysprm_load_and_init (const char * db_name, const char * conf_file, const int load_flags)
Definition at line 6802 of file system_parameter.c.
References sysprm_load_and_init_internal().
Referenced by applyinfo(), applylogdb(), boot_remove_all_volumes(), boot_restart_server(), checksumdb(), connect_to_master_for_server_monitor(), copylogdb(), createdb(), load_properties(), loaddb_internal(), main(), master_util_config_startup(), net_server_start(), paramdump(), patchdb(), process_heartbeat_start(), process_heartbeat_stop(), process_heartbeat_util(), process_server(), restoreslave(), us_hb_applylogdb_start(), us_hb_copylogdb_start(), us_hb_server_start(), xboot_delete(), xboot_emergency_patch(), xboot_initialize_server(), and xboot_restart_from_backup().
int sysprm_load_and_init_client (const char * db_name, const char * conf_file)
Definition at line 6816 of file system_parameter.c.
References SYSPRM_LOAD_ALL, and sysprm_load_and_init_internal().
Referenced by boot_initialize_client(), and boot_restart_client().
static int sysprm_load_and_init_internal (const char * db_name, const char * conf_file, bool reload, const int load_flags) static
Definition at line 6546 of file system_parameter.c.
References assert, basename(), session_param::datatype, sysprm_param::datatype, DB_MAX_IDENTIFIER_LENGTH, sysprm_param::dynamic_flag, envvar_confdir_file(), envvar_get(), ER_FAILED, session_param::flag, sysprm_param::force_value, GET_PRM, HA_MODE_OFF, i, intl_Mbs_support, intl_String_validation, MSGCAT_CATALOG_CUBRID, msgcat_init(), msgcat_message(), MSGCAT_SET_PARAMETERS, sysprm_param::name, NO_ERROR, NULL, NUM_PRM, num_session_parameters, prm_check_environment(), prm_check_parameters(), PRM_CLIENT_SESSION_ONLY, PRM_ERR_CANT_ACCESS, PRM_ERR_NO_ERROR, PRM_ERR_NO_VALUE, prm_get_bool_value(), PRM_HA_MODE, session_param::prm_id, PRM_ID_INTL_CHECK_INPUT_STRING, PRM_ID_INTL_MBS_SUPPORT, PRM_IS_FOR_CLIENT, PRM_IS_FOR_SERVER, PRM_IS_FOR_SESSION, PRM_IS_GET_SERVER, PRM_IS_HIDDEN, PRM_IS_OBSOLETED, PRM_IS_RELOADABLE, PRM_IS_SET, prm_read_and_parse_ini_file(), prm_set(), prm_set_default(), PRM_TEST_CHANGE_ONLY, prm_tune_parameters(), PRM_USER_CAN_CHANGE, sysprm_param::static_flag, strncpy_bufsize, sysprm_alloc_session_parameters(), sysprm_conf_file_name, sysprm_dump_parameters(), sysprm_free_session_parameters(), sysprm_ha_conf_file_name, SYSPRM_IGNORE_HA, sysprm_set_er_log_file(), sysprm_set_sysprm_value_from_parameter(), sysprm_update_session_prm_flag_allocated(), session_param::value, and sysprm_param::value.
Referenced by sysprm_load_and_init(), sysprm_load_and_init_client(), and sysprm_reload_and_init().
SYSPRM_ERR sysprm_make_default_values (const char * data, char * default_val_buf, const int buf_size)
Definition at line 7790 of file system_parameter.c.
References err, intl_mbs_ncpy(), LANG_GET_BINARY_COLLATION, lang_get_collation_name(), lang_get_Lang_name(), LANG_SYS_CODESET, sysprm_param::name, NULL, p, PRM_ERR_BAD_VALUE, PRM_ERR_NO_ERROR, PRM_ERR_UNKNOWN_PARAM, prm_find(), prm_get_next_param_value(), PRM_ID_INTL_COLLATION, PRM_ID_INTL_DATE_LANG, PRM_ID_INTL_NUMBER_LANG, PRM_ID_TIMEZONE, PRM_NAME_INTL_COLLATION, PRM_NAME_INTL_DATE_LANG, PRM_NAME_INTL_NUMBER_LANG, PRM_NAME_TIMEZONE, prm_print(), PRM_PRINT_DEFAULT_VAL, PRM_PRINT_NAME, sysprm_get_id(), tz_get_system_timezone(), and sysprm_param::value.
Referenced by db_reset_system_parameters_from_assignments(), and sl_write_statement_sql().
SYSPRM_ERR sysprm_obtain_parameters (char * data, SYSPRM_ASSIGN_VALUE ** prm_values_ptr)
Definition at line 8533 of file system_parameter.c.
References ARG_FILE_LINE, assert, char_isspace(), ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), intl_mbs_ncpy(), sysprm_param::name, sysprm_assign_value::next, NULL, p, PRM_ERR_BAD_VALUE, PRM_ERR_CANNOT_CHANGE, PRM_ERR_NO_ERROR, PRM_ERR_NO_MEM_FOR_PRM, PRM_ERR_NO_VALUE, PRM_ERR_NOT_FOR_CLIENT, PRM_ERR_UNKNOWN_PARAM, prm_find(), sysprm_assign_value::prm_id, PRM_IS_FOR_CLIENT, PRM_IS_FOR_SERVER, PRM_IS_GET_SERVER, sysprm_param::static_flag, sysprm_free_assign_values(), sysprm_get_id(), sysprm_set_sysprm_value_from_parameter(), sysprm_assign_value::value, and sysprm_param::value.
Referenced by db_get_system_parameters().
char* sysprm_pack_assign_values (char * ptr, const SYSPRM_ASSIGN_VALUE * assign_values)
Definition at line 11768 of file system_parameter.c.
References ASSERT_ALIGN, cubregex::count(), GET_PRM_DATATYPE, INT_ALIGNMENT, sysprm_assign_value::next, NULL, OR_INT_SIZE, or_pack_int(), OR_PUT_INT, sysprm_assign_value::prm_id, sysprm_pack_sysprm_value(), and sysprm_assign_value::value.
Referenced by sprm_server_get_force_parameters(), sprm_server_obtain_parameters(), sysprm_change_server_parameters(), and sysprm_obtain_server_parameters().
char* sysprm_pack_session_parameters (char * ptr, SESSION_PARAM * session_parameters)
Definition at line 11643 of file system_parameter.c.
References ASSERT_ALIGN, session_param::datatype, session_param::flag, i, INT_ALIGNMENT, NULL, NUM_SESSION_PRM, or_pack_int(), session_param::prm_id, sysprm_pack_sysprm_value(), and session_param::value.
Referenced by csession_find_or_create_session(), and ssession_find_or_create_session().
static char * sysprm_pack_sysprm_value (char * ptr, SYSPRM_VALUE value, SYSPRM_DATATYPE datatype) static
Definition at line 11433 of file system_parameter.c.
References ASSERT_ALIGN, assert_release, sysprm_value::b, sysprm_value::bi, sysprm_value::f, sysprm_value::i, i, INT_ALIGNMENT, sysprm_value::integer_list, NULL, or_pack_float(), or_pack_int(), or_pack_int64(), or_pack_string(), PRM_BIGINT, PRM_BOOLEAN, PRM_FLOAT, PRM_INTEGER, PRM_INTEGER_LIST, PRM_KEYWORD, PRM_STRING, and sysprm_value::str.
Referenced by sysprm_pack_assign_values(), and sysprm_pack_session_parameters().
int sysprm_packed_assign_values_length (const SYSPRM_ASSIGN_VALUE * assign_values, int offset)
Definition at line 11797 of file system_parameter.c.
References GET_PRM_DATATYPE, sysprm_assign_value::next, NULL, OR_INT_SIZE, sysprm_assign_value::prm_id, sysprm_packed_sysprm_value_length(), and sysprm_assign_value::value.
Referenced by sprm_server_get_force_parameters(), sprm_server_obtain_parameters(), sysprm_change_server_parameters(), and sysprm_obtain_server_parameters().
int sysprm_packed_session_parameters_length (SESSION_PARAM * session_parameters, int offset)
Definition at line 11678 of file system_parameter.c.
References session_param::datatype, i, NULL, NUM_SESSION_PRM, OR_INT_SIZE, sysprm_packed_sysprm_value_length(), and sysprm_param::value.
Referenced by csession_find_or_create_session(), and ssession_find_or_create_session().
static int sysprm_packed_sysprm_value_length (SYSPRM_VALUE value, SYSPRM_DATATYPE datatype, int offset) static
Definition at line 11498 of file system_parameter.c.
References DB_ALIGN, sysprm_value::integer_list, MAX_ALIGNMENT, NULL, OR_FLOAT_SIZE, OR_INT64_SIZE, OR_INT_SIZE, or_packed_string_length(), PRM_BIGINT, PRM_BOOLEAN, PRM_FLOAT, PRM_INTEGER, PRM_INTEGER_LIST, PRM_KEYWORD, PRM_STRING, and sysprm_value::str.
Referenced by sysprm_packed_assign_values_length(), and sysprm_packed_session_parameters_length().
int sysprm_print_assign_values (SYSPRM_ASSIGN_VALUE * prm_values, char * buffer, int length)
Definition at line 12328 of file system_parameter.c.
References sysprm_assign_value::next, NULL, sysprm_assign_value::prm_id, PRM_PRINT_NAME, sysprm_print_sysprm_value(), and sysprm_assign_value::value.
Referenced by db_get_system_parameters().
char* sysprm_print_parameters_for_ha_repl (void)
Definition at line 12411 of file system_parameter.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), GET_PRM, GET_PRM_DYNAMIC_FLAG, GET_PRM_STATIC_FLAG, i, LANG_GET_BINARY_COLLATION, lang_get_collation_name(), lang_get_Lang_name(), LANG_SYS_CODESET, NULL, NUM_PRM, prm_get_string_value(), PRM_ID_INTL_COLLATION, PRM_ID_INTL_DATE_LANG, PRM_ID_INTL_NUMBER_LANG, PRM_IS_DIFFERENT, PRM_IS_FOR_HA_CONTEXT, prm_print(), PRM_PRINT_CURR_VAL, and PRM_PRINT_NAME.
Referenced by do_replicate_statement().
char* sysprm_print_parameters_for_qry_string (void)
Definition at line 12358 of file system_parameter.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), GET_PRM, i, NULL, NUM_PRM, prm_print(), PRM_PRINT_CURR_VAL, PRM_PRINT_ID, and PRM_PRINT_QRY_STRING.
Referenced by parser_print_tree().
static int sysprm_print_sysprm_value (PARAM_ID prm_id, SYSPRM_VALUE value, char * buf, size_t len, PRM_PRINT_MODE print_mode) static
Definition at line 8230 of file system_parameter.c.
References assert, assert_release, sysprm_value::b, sysprm_value::bi, error(), sysprm_value::f, sysprm_param::get_dup, GET_PRM, sysprm_value::i, i, sysprm_value::integer_list, intl_mbs_casecmp(), keyval::key, sysprm_param::name, NO_ERROR, NULL, PRM_ADJUST_FOR_GET_BIGINT_TO_BIGINT, PRM_ADJUST_FOR_GET_FLOAT_TO_BIGINT, PRM_ADJUST_FOR_GET_FLOAT_TO_FLOAT, PRM_ADJUST_FOR_GET_INTEGER_TO_BIGINT, PRM_ADJUST_FOR_GET_INTEGER_TO_INTEGER, PRM_DEFAULT_BUFFER_SIZE, PRM_DIFFERENT_UNIT, PRM_HAS_SIZE_UNIT, PRM_HAS_TIME_UNIT, PRM_IS_BIGINT, PRM_IS_BOOLEAN, PRM_IS_FLOAT, PRM_IS_INTEGER, PRM_IS_INTEGER_LIST, PRM_IS_KEYWORD, PRM_IS_STRING, prm_keyword(), PRM_NAME_CHECK_PEER_ALIVE, PRM_NAME_COMPAT_MODE, PRM_NAME_ER_LOG_LEVEL, PRM_NAME_FAULT_INJECTION_TEST, PRM_NAME_HA_LOG_APPLIER_STATE, PRM_NAME_HA_MODE, PRM_NAME_HA_MODE_FOR_SA_UTILS_ONLY, PRM_NAME_HA_REPL_FILTER_TYPE, PRM_NAME_HA_SERVER_STATE, PRM_NAME_LOG_ISOLATION_LEVEL, PRM_NAME_PB_DEBUG_PAGE_VALIDATION_LEVEL, PRM_NAME_QUERY_TRACE_FORMAT, PRM_NAME_TDE_DEFAULT_ALGORITHM, PRM_PRINT_ID, PRM_PRINT_NAME, sysprm_param::static_flag, sysprm_value::str, strlen, util_byte_to_size_string(), and util_msec_to_time_string().
Referenced by sysprm_print_assign_values().
int sysprm_reload_and_init (const char * db_name, const char * conf_file)
Definition at line 6829 of file system_parameter.c.
References SYSPRM_LOAD_ALL, and sysprm_load_and_init_internal().
Referenced by hb_master_init(), hb_reload_config(), and log_get_io_page_size().
void sysprm_set_er_log_file (const char * db_name)
Definition at line 6492 of file system_parameter.c.
References basename(), DB_MAX_IDENTIFIER_LENGTH, sysprm_param::dynamic_flag, ER_LOG_FILE_DIR, NULL, PATH_SEPARATOR, prm_find(), PRM_IS_SET, PRM_NAME_ER_LOG_FILE, prm_set(), and strncpy_bufsize.
Referenced by net_server_start(), and sysprm_load_and_init_internal().
int sysprm_set_error (SYSPRM_ERR rc, const char * data)
Definition at line 12556 of file system_parameter.c.
References ARG_FILE_LINE, er_errid(), ER_ERROR_SEVERITY, ER_GENERIC_ERROR, ER_NET_SERVER_COMM_ERROR, ER_NOT_SOLE_TRAN, ER_PRM_BAD_VALUE, ER_PRM_BAD_VALUE_NO_DATA, ER_PRM_CANNOT_CHANGE, ER_PRM_CANNOT_CHANGE_NO_DATA, er_set(), error(), NO_ERROR, PRM_ERR_BAD_RANGE, PRM_ERR_BAD_STRING, PRM_ERR_BAD_VALUE, PRM_ERR_CANNOT_CHANGE, PRM_ERR_COMM_ERR, PRM_ERR_NO_ERROR, PRM_ERR_NO_MEM_FOR_PRM, PRM_ERR_NOT_FOR_CLIENT, PRM_ERR_NOT_FOR_SERVER, PRM_ERR_NOT_SOLE_TRAN, and PRM_ERR_UNKNOWN_PARAM.
Referenced by db_get_system_parameters(), db_reset_system_parameters_from_assignments(), db_set_system_parameters(), sl_write_statement_sql(), and ssession_find_or_create_session().
int sysprm_set_force (const char * pname, const char * pvalue)
Definition at line 10123 of file system_parameter.c.
References ER_PRM_BAD_VALUE, ER_PRM_CANNOT_CHANGE, NO_ERROR, NULL, prm_find(), and prm_set_force().
Referenced by addvoldb(), backupdb(), checkdb(), compactdb(), conn_restart_client(), copydb(), copylogdb(), createdb(), deletedb(), diagdb(), installdb(), loaddb_internal(), main(), optimizedb(), paramdump(), renamedb(), restoredb(), restoreslave(), spacedb(), synccolldb(), unloaddb(), vacuumdb(), and xboot_shutdown_server().
static void sysprm_set_sysprm_value_from_parameter (SYSPRM_VALUE * prm_value, SYSPRM_PARAM * prm) static
Definition at line 12227 of file system_parameter.c.
References ARG_FILE_LINE, assert_release, sysprm_value::b, sysprm_value::bi, sysprm_param::datatype, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), sysprm_value::f, GET_PRM, sysprm_value::i, i, sysprm_value::integer_list, NULL, NUM_SESSION_PRM, PRM_BIGINT, PRM_BOOLEAN, PRM_FLOAT, PRM_GET_BIGINT, PRM_GET_BOOL, PRM_GET_FLOAT, PRM_GET_INT, PRM_GET_INTEGER_LIST, PRM_GET_STRING, PRM_INTEGER, PRM_INTEGER_LIST, PRM_KEYWORD, PRM_NO_TYPE, PRM_STRING, sysprm_value::str, strdup(), strlen, sysprm_set_value(), and sysprm_param::value.
Referenced by sysprm_get_session_parameters_count(), sysprm_load_and_init_internal(), sysprm_obtain_parameters(), xsysprm_get_force_server_parameters(), and xsysprm_obtain_server_parameters().
static void sysprm_set_system_parameter_value (SYSPRM_PARAM * prm, SYSPRM_VALUE value) static
Definition at line 9887 of file system_parameter.c.
References assert_release, sysprm_value::b, sysprm_value::bi, sysprm_param::datatype, sysprm_value::f, sysprm_value::i, sysprm_value::integer_list, PRM_BIGINT, PRM_BOOLEAN, PRM_FLOAT, PRM_INTEGER, PRM_INTEGER_LIST, PRM_KEYWORD, prm_set_bigint_value(), prm_set_bool_value(), prm_set_float_value(), prm_set_integer_list_value(), prm_set_integer_value(), prm_set_string_value(), PRM_STRING, sysprm_value::str, and sysprm_get_id().
Referenced by sysprm_set_value().
int sysprm_set_to_default (const char * pname, bool set_to_force)
Definition at line 10152 of file system_parameter.c.
References ER_PRM_BAD_VALUE, ER_PRM_CANNOT_CHANGE, NO_ERROR, NULL, prm_find(), prm_print(), PRM_PRINT_CURR_VAL, PRM_PRINT_NONE, prm_set_default(), and prm_set_force().
Referenced by copylogdb().
static int sysprm_set_value (SYSPRM_PARAM * prm, SYSPRM_VALUE value, bool set_flag, bool duplicate) static
Definition at line 9743 of file system_parameter.c.
References ARG_FILE_LINE, BO_IS_SERVER_RESTARTED, sysprm_param::datatype, sysprm_param::dynamic_flag, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), sysprm_param::id, sysprm_value::integer_list, NO_ERROR, NULL, PRM_CLEAR_BIT, prm_compound_has_changed(), PRM_DEFAULT_USED, PRM_ERR_BAD_PARAM, PRM_ERR_NO_ERROR, PRM_ERR_NO_MEM_FOR_PRM, PRM_ERR_UNKNOWN_PARAM, PRM_ID_SERVER_TIMEZONE, PRM_ID_TIMEZONE, PRM_INTEGER_LIST, PRM_IS_COMPOUND, PRM_IS_FOR_SESSION, PRM_SET, PRM_SET_BIT, PRM_STRING, session_get_session_parameter(), session_get_session_tz_region(), sysprm_param::static_flag, sysprm_value::str, strdup(), strlen, sysprm_get_id(), sysprm_set_system_parameter_value(), thread_get_thread_entry_info(), tz_get_client_tz_region_session(), tz_set_tz_region_system(), and tz_str_to_region().
Referenced by prm_set(), sysprm_change_parameter_values(), and sysprm_set_sysprm_value_from_parameter().
char* sysprm_unpack_assign_values (char * ptr, SYSPRM_ASSIGN_VALUE ** assign_values_ptr)
Definition at line 11824 of file system_parameter.c.
References ARG_FILE_LINE, assert, ASSERT_ALIGN, cubregex::count(), ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, GET_PRM_DATATYPE, i, INT_ALIGNMENT, sysprm_assign_value::next, NULL, or_unpack_int(), sysprm_assign_value::prm_id, sysprm_free_assign_values(), sysprm_unpack_sysprm_value(), and sysprm_assign_value::value.
Referenced by sprm_server_change_parameters(), sprm_server_obtain_parameters(), sysprm_get_force_server_parameters(), and sysprm_obtain_server_parameters().
char* sysprm_unpack_session_parameters (char * ptr, SESSION_PARAM ** session_parameters_ptr)
Definition at line 11706 of file system_parameter.c.
References ARG_FILE_LINE, assert, ASSERT_ALIGN, session_param::datatype, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), session_param::flag, INT_ALIGNMENT, NULL, NUM_SESSION_PRM, or_unpack_int(), session_param::prm_id, sysprm_alloc_session_parameters(), sysprm_free_session_parameters(), sysprm_unpack_sysprm_value(), sysprm_update_session_prm_flag_allocated(), and session_param::value.
Referenced by csession_find_or_create_session(), and ssession_find_or_create_session().
static char * sysprm_unpack_sysprm_value (char * ptr, SYSPRM_VALUE * value, SYSPRM_DATATYPE datatype) static
Definition at line 11541 of file system_parameter.c.
References ARG_FILE_LINE, assert, ASSERT_ALIGN, sysprm_value::b, sysprm_value::bi, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), sysprm_value::f, sysprm_value::i, i, INT_ALIGNMENT, sysprm_value::integer_list, NULL, OR_INT_SIZE, or_unpack_float(), or_unpack_int(), or_unpack_int64(), or_unpack_string_nocopy(), PRM_BIGINT, PRM_BOOLEAN, PRM_FLOAT, PRM_INTEGER, PRM_INTEGER_LIST, PRM_KEYWORD, PRM_STRING, sysprm_value::str, strdup(), and strlen.
Referenced by sysprm_unpack_assign_values(), and sysprm_unpack_session_parameters().
static void sysprm_update_flag_allocated (SYSPRM_PARAM * prm) static
Definition at line 11276 of file system_parameter.c.
References sysprm_param::datatype, sysprm_param::dynamic_flag, NULL, PRM_ALLOCATED, PRM_CLEAR_BIT, PRM_GET_INTEGER_LIST, PRM_GET_STRING, PRM_INTEGER_LIST, PRM_SET_BIT, PRM_STRING, and sysprm_param::value.
static void sysprm_update_flag_different (SYSPRM_PARAM * prm) static
Definition at line 11246 of file system_parameter.c.
References sysprm_param::datatype, sysprm_param::default_value, sysprm_param::dynamic_flag, PRM_CLEAR_BIT, PRM_DIFFERENT, PRM_IS_FOR_HA_CONTEXT, PRM_IS_FOR_QRY_STRING, PRM_SET_BIT, sysprm_param::static_flag, sysprm_compare_values(), and sysprm_param::value.
Referenced by prm_set_bigint_value(), prm_set_bool_value(), prm_set_float_value(), prm_set_integer_list_value(), prm_set_integer_value(), and prm_set_string_value().
static void sysprm_update_session_prm_flag_allocated (SESSION_PARAM * prm) static
Definition at line 11315 of file system_parameter.c.
References session_param::datatype, session_param::flag, sysprm_value::integer_list, NULL, PRM_ALLOCATED, PRM_CLEAR_BIT, PRM_INTEGER_LIST, PRM_SET_BIT, PRM_STRING, sysprm_value::str, and session_param::value.
Referenced by sysprm_get_session_parameters_count(), sysprm_load_and_init_internal(), and sysprm_unpack_session_parameters().
SYSPRM_ERR sysprm_validate_change_parameters (const char * data, bool check, SYSPRM_ASSIGN_VALUE ** assignments_ptr)
Definition at line 7663 of file system_parameter.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), err, free_and_init, intl_mbs_ncpy(), sysprm_param::name, sysprm_assign_value::next, NULL, p, PRM_ERR_BAD_VALUE, PRM_ERR_CANNOT_CHANGE, PRM_ERR_NO_ERROR, PRM_ERR_NO_MEM_FOR_PRM, PRM_ERR_NOT_FOR_CLIENT, PRM_ERR_NOT_FOR_CLIENT_NO_AUTH, PRM_ERR_UNKNOWN_PARAM, prm_find(), prm_get_next_param_value(), sysprm_assign_value::prm_id, PRM_TEST_CHANGE_ONLY, PRM_TEST_MODE, PRM_USER_CAN_CHANGE, sysprm_param::static_flag, sysprm_free_assign_values(), sysprm_generate_new_value(), sysprm_get_id(), sysprm_validate_escape_char_parameters(), sysprm_assign_value::value, and sysprm_param::value.
Referenced by db_set_system_parameters().
static SYSPRM_ERR sysprm_validate_escape_char_parameters (const SYSPRM_ASSIGN_VALUE * assignment_list) static
Definition at line 7597 of file system_parameter.c.
References sysprm_value::b, GET_PRM, sysprm_assign_value::next, NULL, PRM_ERR_CANNOT_CHANGE, PRM_ERR_NO_ERROR, PRM_GET_BOOL, sysprm_assign_value::prm_id, PRM_ID_NO_BACKSLASH_ESCAPES, PRM_ID_REQUIRE_LIKE_ESCAPE_CHARACTER, sysprm_assign_value::value, and sysprm_param::value.
Referenced by sysprm_validate_change_parameters().
void xsysprm_change_server_parameters (const SYSPRM_ASSIGN_VALUE * assignments)
Definition at line 8674 of file system_parameter.c.
References sysprm_change_parameter_values().
Referenced by sprm_server_change_parameters(), and sysprm_change_server_parameters().
void xsysprm_dump_server_parameters (FILE * outfp)
Definition at line 8761 of file system_parameter.c.
References sysprm_dump_parameters().
Referenced by sprm_server_dump_parameters(), and sysprm_dump_server_parameters().
SYSPRM_ASSIGN_VALUE* xsysprm_get_force_server_parameters (void)
Definition at line 8716 of file system_parameter.c.
References ARG_FILE_LINE, cleanup(), ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), GET_PRM, i, sysprm_assign_value::next, NULL, NUM_PRM, PRM_GET_FROM_SERVER, sysprm_assign_value::prm_id, sysprm_param::static_flag, sysprm_free_assign_values(), sysprm_set_sysprm_value_from_parameter(), and sysprm_assign_value::value.
Referenced by sprm_server_get_force_parameters().
void xsysprm_obtain_server_parameters (SYSPRM_ASSIGN_VALUE * prm_values)
Definition at line 8690 of file system_parameter.c.
References GET_PRM, sysprm_assign_value::next, NULL, sysprm_assign_value::prm_id, PRM_IS_FOR_CLIENT, PRM_IS_FOR_SERVER, PRM_IS_GET_SERVER, sysprm_param::static_flag, sysprm_set_sysprm_value_from_parameter(), and sysprm_assign_value::value.
Referenced by sprm_server_obtain_parameters(), and sysprm_obtain_server_parameters().
Variable Documentation
KEYVAL boolean_words[] static
Initial value:
= {
  {"yes", 1},
  {"y", 1},
  {"1", 1},
  {"true", 1},
  {"on", 1},
  {"no", 0},
  {"n", 0},
  {"0", 0},
  {"false", 0},
  {"off", 0}
}
Definition at line 6086 of file system_parameter.c.
const int call_stack_dump_error_codes[] static
Definition at line 6297 of file system_parameter.c.
Referenced by sysprm_final(), and sysprm_generate_new_value().
KEYVAL check_peer_alive_words[] static
Initial value:
= {
  {"none", CSS_CHECK_PEER_ALIVE_NONE},
  {"server_only", CSS_CHECK_PEER_ALIVE_SERVER_ONLY},
  {"client_only", CSS_CHECK_PEER_ALIVE_CLIENT_ONLY},
  {"both", CSS_CHECK_PEER_ALIVE_BOTH},
}
Definition at line 6185 of file system_parameter.c.
const char** compat_mode_values[] static
Initial value:
= {
  compat_mode_values_PRM_ANSI_QUOTES,
  compat_mode_values_PRM_ORACLE_STYLE_EMPTY_STRING,
  compat_mode_values_PRM_ORACLE_STYLE_OUTERJOIN,
  compat_mode_values_PRM_PIPES_AS_CONCAT,
  compat_mode_values_PRM_MYSQL_TRIGGER_CORRELATION_NAMES,
  compat_mode_values_PRM_REQUIRE_LIKE_ESCAPE_CHARACTER,
  compat_mode_values_PRM_NO_BACKSLASH_ESCAPES,
  compat_mode_values_PRM_ADD_COLUMN_UPDATE_HARD_DEFAULT,
  compat_mode_values_PRM_RETURN_NULL_ON_FUNCTION_ERRORS,
  compat_mode_values_PRM_PLUS_AS_CONCAT
}
Definition at line 6284 of file system_parameter.c.
Referenced by prm_compound_has_changed().
const char* compat_mode_values_PRM_ADD_COLUMN_UPDATE_HARD_DEFAULT[COMPAT_ORACLE+2] static
Initial value:
= {
  NULL,
  "yes",
  NULL,
  PRM_NAME_ADD_COLUMN_UPDATE_HARD_DEFAULT
}
Definition at line 6263 of file system_parameter.c.
const char* compat_mode_values_PRM_ANSI_QUOTES[COMPAT_ORACLE+2] static
Initial value:
= {
  NULL,
  "no",
  NULL,
  PRM_NAME_ANSI_QUOTES
}
Definition at line 6213 of file system_parameter.c.
const char* compat_mode_values_PRM_MYSQL_TRIGGER_CORRELATION_NAMES[COMPAT_ORACLE+2] static
Initial value:
= {
  NULL,
  "yes",
  NULL,
  PRM_NAME_MYSQL_TRIGGER_CORRELATION_NAMES
}
Definition at line 6242 of file system_parameter.c.
const char* compat_mode_values_PRM_NO_BACKSLASH_ESCAPES[COMPAT_ORACLE+2] static
Initial value:
= {
  NULL,
  "no",
  NULL,
  PRM_NAME_NO_BACKSLASH_ESCAPES
}
Definition at line 6256 of file system_parameter.c.
const char* compat_mode_values_PRM_ORACLE_STYLE_EMPTY_STRING[COMPAT_ORACLE+2] static
Initial value:
= {
  NULL,
  NULL,
  "yes",
  PRM_NAME_ORACLE_STYLE_EMPTY_STRING
}
Definition at line 6220 of file system_parameter.c.
const char* compat_mode_values_PRM_ORACLE_STYLE_OUTERJOIN[COMPAT_ORACLE+2] static
Initial value:
= {
  NULL,
  NULL,
  "yes",
  PRM_NAME_ORACLE_STYLE_OUTERJOIN
}
Definition at line 6227 of file system_parameter.c.
const char* compat_mode_values_PRM_PIPES_AS_CONCAT[COMPAT_ORACLE+2] static
Initial value:
= {
  NULL,
  "no",
  NULL,
  PRM_NAME_PIPES_AS_CONCAT
}
Definition at line 6234 of file system_parameter.c.
const char* compat_mode_values_PRM_PLUS_AS_CONCAT[COMPAT_ORACLE+2] static
Initial value:
= {
  "yes",
  "no",
  NULL,
  PRM_NAME_PLUS_AS_CONCAT
}
Definition at line 6277 of file system_parameter.c.
const char* compat_mode_values_PRM_REQUIRE_LIKE_ESCAPE_CHARACTER[COMPAT_ORACLE+2] static
Initial value:
= {
  NULL,
  "yes",
  NULL,
  PRM_NAME_REQUIRE_LIKE_ESCAPE_CHARACTER
}
Definition at line 6249 of file system_parameter.c.
const char* compat_mode_values_PRM_RETURN_NULL_ON_FUNCTION_ERRORS[COMPAT_ORACLE+2] static
Initial value:
= {
  NULL,
  "yes",
  NULL,
  PRM_NAME_RETURN_NULL_ON_FUNCTION_ERRORS
}
Definition at line 6270 of file system_parameter.c.
KEYVAL compat_words[] static
Initial value:
= {
  {"cubrid", COMPAT_CUBRID},
  {"default", COMPAT_CUBRID},
  {"mysql", COMPAT_MYSQL},
  {"oracle", COMPAT_ORACLE}
}
Definition at line 6178 of file system_parameter.c.
char* conf_path
Definition at line 6412 of file system_parameter.c.
Referenced by sysprm_dump_parameters(), and sysprm_final().
char* db_name
Definition at line 6413 of file system_parameter.c.
Referenced by alterdbhost(), boot_delete(), cas_main(), check_server_alive(), csql_print_database(), diagdb(), er_file_backup(), gen_tz(), installdb(), logpb_create_log_info(), logwr_info::logwr_info(), main(), optimizedb(), patchdb(), process_heartbeat_start(), process_heartbeat_stop(), process_heartbeat_util(), process_javasp(), process_javasp_start(), process_javasp_status(), process_javasp_stop(), proxy_process_client_register(), pt_make_query_show_table(), register_abort_signal_handler(), synccolldb(), sysprm_dump_parameters(), sysprm_final(), us_hb_applylogdb_stop(), and us_hb_process_applylogdb().
KEYVAL er_log_level_words[] static
Initial value:
= {
  {"fatal", ER_FATAL_ERROR_SEVERITY},
  {"error", ER_ERROR_SEVERITY},
  {"syntax", ER_SYNTAX_ERROR_SEVERITY},
  {"warning", ER_WARNING_SEVERITY},
  {"notification", ER_NOTIFICATION_SEVERITY}
}
Definition at line 6099 of file system_parameter.c.
KEYVAL fi_test_words[] static
Initial value:
= {
  {"recovery", FI_GROUP_RECOVERY},
}
Definition at line 6197 of file system_parameter.c.
KEYVAL ha_log_applier_state_words[] static
Initial value:
= {
  {HA_LOG_APPLIER_STATE_UNREGISTERED_STR, HA_LOG_APPLIER_STATE_UNREGISTERED},
  {HA_LOG_APPLIER_STATE_RECOVERING_STR, HA_LOG_APPLIER_STATE_RECOVERING},
  {HA_LOG_APPLIER_STATE_WORKING_STR, HA_LOG_APPLIER_STATE_WORKING},
  {HA_LOG_APPLIER_STATE_DONE_STR, HA_LOG_APPLIER_STATE_DONE},
  {HA_LOG_APPLIER_STATE_ERROR_STR, HA_LOG_APPLIER_STATE_ERROR}
}
Definition at line 6170 of file system_parameter.c.
KEYVAL ha_mode_words[] static
Initial value:
= {
  {HA_MODE_OFF_STR, HA_MODE_OFF},
  {"no", HA_MODE_OFF},
  {"n", HA_MODE_OFF},
  {"0", HA_MODE_OFF},
  {"false", HA_MODE_OFF},
  {"off", HA_MODE_OFF},
  {"yes", HA_MODE_FAIL_BACK},
  {"y", HA_MODE_FAIL_BACK},
  {"1", HA_MODE_FAIL_BACK},
  {"true", HA_MODE_FAIL_BACK},
  {"on", HA_MODE_FAIL_BACK},
  {HA_MODE_FAIL_BACK_STR, HA_MODE_FAIL_BACK},
  {HA_MODE_ROLE_CHANGE_STR, HA_MODE_ROLE_CHANGE},
  {"r", HA_MODE_REPLICA},
  {"repl", HA_MODE_REPLICA},
  {"replica", HA_MODE_REPLICA},
  {"2", HA_MODE_REPLICA}
}
Definition at line 6138 of file system_parameter.c.
KEYVAL ha_repl_filter_type_words[] static
Initial value:
= {
  {"none", REPL_FILTER_NONE},
  {"include_table", REPL_FILTER_INCLUDE_TBL},
  {"exclude_table", REPL_FILTER_EXCLUDE_TBL}
}
Definition at line 6201 of file system_parameter.c.
KEYVAL ha_server_state_words[] static
Initial value:
= {
  {HA_SERVER_STATE_IDLE_STR, HA_SERVER_STATE_IDLE},
  {HA_SERVER_STATE_ACTIVE_STR, HA_SERVER_STATE_ACTIVE},
  {HA_SERVER_STATE_TO_BE_ACTIVE_STR, HA_SERVER_STATE_TO_BE_ACTIVE},
  {HA_SERVER_STATE_STANDBY_STR, HA_SERVER_STATE_STANDBY},
  {HA_SERVER_STATE_TO_BE_STANDBY_STR, HA_SERVER_STATE_TO_BE_STANDBY},
  {HA_SERVER_STATE_MAINTENANCE_STR, HA_SERVER_STATE_MAINTENANCE},
  {HA_SERVER_STATE_DEAD_STR, HA_SERVER_STATE_DEAD}
}
Definition at line 6160 of file system_parameter.c.
int int_list_initial[1] = { 0 } static
Definition at line 917 of file system_parameter.c.
KEYVAL isolation_level_words[] static
Initial value:
= {
  {"tran_serializable", TRAN_SERIALIZABLE},
  {"tran_no_phantom_read", TRAN_SERIALIZABLE},
  {"tran_rep_class_rep_instance", TRAN_REPEATABLE_READ},
  {"tran_rep_read", TRAN_REPEATABLE_READ},
  {"tran_rep_class_commit_instance", TRAN_READ_COMMITTED},
  {"tran_read_committed", TRAN_READ_COMMITTED},
  {"tran_cursor_stability", TRAN_READ_COMMITTED},
  {"serializable", TRAN_SERIALIZABLE},
  {"no_phantom_read", TRAN_SERIALIZABLE},
  {"rep_class_rep_instance", TRAN_REPEATABLE_READ},
  {"rep_read", TRAN_REPEATABLE_READ},
  {"rep_class_commit_instance", TRAN_READ_COMMITTED},
  {"read_committed", TRAN_READ_COMMITTED},
  {"cursor_stability", TRAN_READ_COMMITTED},
}
Definition at line 6107 of file system_parameter.c.
KEYVAL null_words[] static
Initial value:
= {
  {"null", 0},
  {"0", 0}
}
Definition at line 6133 of file system_parameter.c.
int num_session_parameters = 0 static
Definition at line 6061 of file system_parameter.c.
Referenced by sysprm_load_and_init_internal().
KEYVAL pgbuf_debug_page_validation_level_words[] static
Initial value:
= {
  {"fetch", PGBUF_DEBUG_PAGE_VALIDATION_FETCH},
  {"free", PGBUF_DEBUG_PAGE_VALIDATION_FREE},
  {"all", PGBUF_DEBUG_PAGE_VALIDATION_ALL}
}
Definition at line 6127 of file system_parameter.c.
bool PRM_ACCESS_IP_CONTROL = false
Definition at line 959 of file system_parameter.c.
bool prm_access_ip_control_default = false static
Definition at line 960 of file system_parameter.c.
const char* PRM_ACCESS_IP_CONTROL_FILE = ""
Definition at line 963 of file system_parameter.c.
const char* prm_access_ip_control_file_default = "" static
Definition at line 964 of file system_parameter.c.
unsigned int prm_access_ip_control_file_flag = 0 static
Definition at line 965 of file system_parameter.c.
unsigned int prm_access_ip_control_flag = 0 static
Definition at line 961 of file system_parameter.c.
bool PRM_ADAPTIVE_FLUSH_CONTROL = true
Definition at line 1226 of file system_parameter.c.
bool prm_adaptive_flush_control_default = true static
Definition at line 1227 of file system_parameter.c.
unsigned int prm_adaptive_flush_control_flag = 0 static
Definition at line 1228 of file system_parameter.c.
bool PRM_ADD_COLUMN_UPDATE_HARD_DEFAULT = false
Definition at line 1315 of file system_parameter.c.
bool prm_add_column_update_hard_default_default = false static
Definition at line 1316 of file system_parameter.c.
unsigned int prm_add_column_update_hard_default_flag = 0 static
Definition at line 1317 of file system_parameter.c.
bool PRM_AGG_HASH_RESPECT_ORDER = true
Definition at line 1875 of file system_parameter.c.
bool prm_agg_hash_respect_order_default = true static
Definition at line 1876 of file system_parameter.c.
unsigned int prm_agg_hash_respect_order_flag = 0 static
Definition at line 1877 of file system_parameter.c.
bool PRM_ALLOW_TRUNCATED_STRING = false
Definition at line 2321 of file system_parameter.c.
bool prm_allow_truncated_string_default = false static
Definition at line 2322 of file system_parameter.c.
unsigned int prm_allow_truncated_string_flag = 0 static
Definition at line 2323 of file system_parameter.c.
bool PRM_ALTER_TABLE_CHANGE_TYPE_STRICT = true
Definition at line 1323 of file system_parameter.c.
bool prm_alter_table_change_type_strict_default = true static
Definition at line 1324 of file system_parameter.c.
unsigned int prm_alter_table_change_type_strict_flag = 1 static
Definition at line 1325 of file system_parameter.c.
bool PRM_ANSI_QUOTES = true
Definition at line 1269 of file system_parameter.c.
bool prm_ansi_quotes_default = true static
Definition at line 1270 of file system_parameter.c.
unsigned int prm_ansi_quotes_flag = 0 static
Definition at line 1271 of file system_parameter.c.
bool PRM_AUTO_RESTART_SERVER = true
Definition at line 1376 of file system_parameter.c.
bool prm_auto_restart_server_default = true static
Definition at line 1377 of file system_parameter.c.
unsigned int prm_auto_restart_server_flag = 0 static
Definition at line 1378 of file system_parameter.c.
bool PRM_BLOCK_DDL_STATEMENT = false
Definition at line 1633 of file system_parameter.c.
bool prm_block_ddl_statement_default = false static
Definition at line 1634 of file system_parameter.c.
unsigned int prm_block_ddl_statement_flag = 0 static
Definition at line 1635 of file system_parameter.c.
bool PRM_BLOCK_NOWHERE_STATEMENT = false
Definition at line 1629 of file system_parameter.c.
bool prm_block_nowhere_statement_default = false static
Definition at line 1630 of file system_parameter.c.
unsigned int prm_block_nowhere_statement_flag = 0 static
Definition at line 1631 of file system_parameter.c.
unsigned int prm_bosr_maxtmp_flag = 0 static
Definition at line 1015 of file system_parameter.c.
int PRM_BOSR_MAXTMP_PAGES = INT_MIN
Definition at line 1013 of file system_parameter.c.
int prm_bosr_maxtmp_pages = -1 static
Definition at line 1014 of file system_parameter.c.
bool PRM_BT_INDEX_SCAN_OID_ORDER = false
Definition at line 1009 of file system_parameter.c.
bool prm_bt_index_scan_oid_order_default = false static
Definition at line 1010 of file system_parameter.c.
unsigned int prm_bt_index_scan_oid_order_flag = 0 static
Definition at line 1011 of file system_parameter.c.
float PRM_BT_OID_NBUFFERS = 4.0f
Definition at line 1003 of file system_parameter.c.
float prm_bt_oid_nbuffers_default = 4.0f static
Definition at line 1004 of file system_parameter.c.
unsigned int prm_bt_oid_nbuffers_flag = 0 static
Definition at line 1007 of file system_parameter.c.
float prm_bt_oid_nbuffers_lower = 0.049999f static
Definition at line 1005 of file system_parameter.c.
float prm_bt_oid_nbuffers_upper = 16.0f static
Definition at line 1006 of file system_parameter.c.
float PRM_BT_UNFILL_FACTOR = 0.05f
Definition at line 997 of file system_parameter.c.
float prm_bt_unfill_factor_default = 0.05f static
Definition at line 998 of file system_parameter.c.
unsigned int prm_bt_unfill_factor_flag = 0 static
Definition at line 1001 of file system_parameter.c.
float prm_bt_unfill_factor_lower = 0.0f static
Definition at line 999 of file system_parameter.c.
float prm_bt_unfill_factor_upper = 0.5f static
Definition at line 1000 of file system_parameter.c.
int* PRM_CALL_STACK_DUMP_ACTIVATION = int_list_initial
Definition at line 1360 of file system_parameter.c.
bool* prm_call_stack_dump_activation_default = NULL static
Definition at line 1361 of file system_parameter.c.
unsigned int prm_call_stack_dump_activation_flag = 0 static
Definition at line 1362 of file system_parameter.c.
int* PRM_CALL_STACK_DUMP_DEACTIVATION = int_list_initial
Definition at line 1364 of file system_parameter.c.
bool* prm_call_stack_dump_deactivation_default = NULL static
Definition at line 1365 of file system_parameter.c.
unsigned int prm_call_stack_dump_deactivation_flag = 0 static
Definition at line 1366 of file system_parameter.c.
bool PRM_CALL_STACK_DUMP_ON_ERROR = false
Definition at line 1356 of file system_parameter.c.
bool prm_call_stack_dump_on_error_default = false static
Definition at line 1357 of file system_parameter.c.
unsigned int prm_call_stack_dump_on_error_flag = 0 static
Definition at line 1358 of file system_parameter.c.
const char* PRM_CFG_DB_HOSTS = ""
Definition at line 1138 of file system_parameter.c.
const char* prm_cfg_db_hosts_default = NULL static
Definition at line 1139 of file system_parameter.c.
unsigned int prm_cfg_db_hosts_flag = 0 static
Definition at line 1140 of file system_parameter.c.
int PRM_CHECK_PEER_ALIVE = CSS_CHECK_PEER_ALIVE_BOTH
Definition at line 1815 of file system_parameter.c.
int prm_check_peer_alive_default = CSS_CHECK_PEER_ALIVE_BOTH static
Definition at line 1816 of file system_parameter.c.
unsigned int prm_check_peer_alive_flag = 0 static
Definition at line 1817 of file system_parameter.c.
bool PRM_CLIENT_CLASS_CACHE_DEBUG = false
Definition at line 2093 of file system_parameter.c.
const bool prm_client_class_cache_debug_default = false static
Definition at line 2094 of file system_parameter.c.
unsigned int prm_client_class_cache_debug_flag = 0 static
Definition at line 2095 of file system_parameter.c.
bool PRM_COMMIT_ON_SHUTDOWN = false
Definition at line 1074 of file system_parameter.c.
Referenced by prm_get_commit_on_shutdown().
bool prm_commit_on_shutdown_default = false static
Definition at line 1075 of file system_parameter.c.
unsigned int prm_commit_on_shutdown_flag = 0 static
Definition at line 1076 of file system_parameter.c.
int PRM_COMPACTDB_PAGE_RECLAIM_ONLY = 0
Definition at line 1331 of file system_parameter.c.
int prm_compactdb_page_reclaim_only_default = 0 static
Definition at line 1332 of file system_parameter.c.
unsigned int prm_compactdb_page_reclaim_only_flag = 0 static
Definition at line 1333 of file system_parameter.c.
int PRM_COMPAT_MODE = COMPAT_CUBRID
Definition at line 1263 of file system_parameter.c.
int prm_compat_mode_default = COMPAT_CUBRID static
Definition at line 1264 of file system_parameter.c.
unsigned int prm_compat_mode_flag = 0 static
Definition at line 1267 of file system_parameter.c.
int prm_compat_mode_lower = COMPAT_CUBRID static
Definition at line 1265 of file system_parameter.c.
int prm_compat_mode_upper = COMPAT_ORACLE static
Definition at line 1266 of file system_parameter.c.
bool PRM_COMPAT_NUMERIC_DIVISION_SCALE = false
Definition at line 1368 of file system_parameter.c.
bool prm_compat_numeric_division_scale_default = false static
Definition at line 1369 of file system_parameter.c.
unsigned int prm_compat_numeric_division_scale_flag = 0 static
Definition at line 1370 of file system_parameter.c.
bool PRM_COMPAT_PRIMARY_KEY = false
Definition at line 1602 of file system_parameter.c.
bool prm_compat_primary_key_default = false static
Definition at line 1603 of file system_parameter.c.
unsigned int prm_compat_primary_key_flag = 0 static
Definition at line 1604 of file system_parameter.c.
bool PRM_COMPENSATE_DEBUG = false
Definition at line 2085 of file system_parameter.c.
const bool prm_compensate_debug_default = false static
Definition at line 2086 of file system_parameter.c.
unsigned int prm_compensate_debug_flag = 0 static
Definition at line 2087 of file system_parameter.c.
bool PRM_CONNECTION_LOGGING = false
Definition at line 2167 of file system_parameter.c.
bool prm_connection_logging_default = false static
Definition at line 2168 of file system_parameter.c.
unsigned int prm_connection_logging_flag = 0 static
Definition at line 2169 of file system_parameter.c.
unsigned int prm_create_table_reuseoid = 0 static
Definition at line 2327 of file system_parameter.c.
bool prm_create_table_reuseoid_default = true static
Definition at line 2326 of file system_parameter.c.
bool PRM_CSQL_AUTO_COMMIT = true
Definition at line 1083 of file system_parameter.c.
bool prm_csql_auto_commit_default = true static
Definition at line 1084 of file system_parameter.c.
unsigned int prm_csql_auto_commit_flag = 0 static
Definition at line 1085 of file system_parameter.c.
int PRM_CSQL_HISTORY_NUM = 50
Definition at line 1643 of file system_parameter.c.
int prm_csql_history_num_default = 50 static
Definition at line 1644 of file system_parameter.c.
unsigned int prm_csql_history_num_flag = 0 static
Definition at line 1647 of file system_parameter.c.
int prm_csql_history_num_lower = 1 static
Definition at line 1646 of file system_parameter.c.
int prm_csql_history_num_upper = 200 static
Definition at line 1645 of file system_parameter.c.
bool PRM_CSQL_SINGLE_LINE_MODE = false
Definition at line 1682 of file system_parameter.c.
bool prm_csql_single_line_mode_default = false static
Definition at line 1683 of file system_parameter.c.
unsigned int prm_csql_single_line_mode_flag = 0 static
Definition at line 1684 of file system_parameter.c.
int PRM_CSS_MAX_CLIENTS = 100
Definition at line 1126 of file system_parameter.c.
int prm_css_max_clients_default = 100 static
Definition at line 1127 of file system_parameter.c.
unsigned int prm_css_max_clients_flag = 0 static
Definition at line 1130 of file system_parameter.c.
int prm_css_max_clients_lower = 10 static
Definition at line 1128 of file system_parameter.c.
int prm_css_max_clients_upper = CSS_MAX_CLIENT_COUNT static
Definition at line 1129 of file system_parameter.c.
Referenced by sysprm_final().
int PRM_CTE_MAX_RECURSIONS = 2000
Definition at line 2151 of file system_parameter.c.
int prm_cte_max_recursions_default = 2000 static
Definition at line 2152 of file system_parameter.c.
unsigned int prm_cte_max_recursions_flag = 0 static
Definition at line 2155 of file system_parameter.c.
int prm_cte_max_recursions_lower = 2 static
Definition at line 2154 of file system_parameter.c.
int prm_cte_max_recursions_upper = 1000000 static
Definition at line 2153 of file system_parameter.c.
int PRM_DATA_FILE_ADVISE = 0
Definition at line 2219 of file system_parameter.c.
int prm_data_file_advise_default = 0 static
Definition at line 2220 of file system_parameter.c.
unsigned int prm_data_file_advise_flag = 0 static
Definition at line 2221 of file system_parameter.c.
unsigned int prm_data_file_advise_lower = 0 static
Definition at line 2223 of file system_parameter.c.
unsigned int prm_data_file_advise_upper = 6 static
Definition at line 2222 of file system_parameter.c.
UINT64 PRM_DB_VOLUME_SIZE = 536870912ULL
Definition at line 1783 of file system_parameter.c.
UINT64 prm_db_volume_size_default = 536870912ULL static
Definition at line 1784 of file system_parameter.c.
unsigned int prm_db_volume_size_flag = 0 static
Definition at line 1787 of file system_parameter.c.
UINT64 prm_db_volume_size_lower = 0 static
Definition at line 1785 of file system_parameter.c.
UINT64 prm_db_volume_size_upper = 21474836480ULL static
Definition at line 1786 of file system_parameter.c.
bool PRM_DBFILES_PROTECT = false
Definition at line 1372 of file system_parameter.c.
bool prm_dbfiles_protect_default = false static
Definition at line 1373 of file system_parameter.c.
unsigned int prm_dbfiles_protect_flag = 0 static
Definition at line 1374 of file system_parameter.c.
bool PRM_DDL_AUDIT_LOG = false
Definition at line 2337 of file system_parameter.c.
bool prm_ddl_audit_log_default = false static
Definition at line 2338 of file system_parameter.c.
unsigned int prm_ddl_audit_log_flag = 0 static
Definition at line 2339 of file system_parameter.c.
UINT64 PRM_DDL_AUDIT_LOG_SIZE = 10485760ULL
Definition at line 2341 of file system_parameter.c.
UINT64 prm_ddl_audit_log_size_default = 10485760ULL static
Definition at line 2342 of file system_parameter.c.
unsigned int prm_ddl_audit_log_size_flag = 0 static
Definition at line 2345 of file system_parameter.c.
UINT64 prm_ddl_audit_log_size_lower = 10485760ULL static
Definition at line 2343 of file system_parameter.c.
UINT64 prm_ddl_audit_log_size_upper = 2147483648ULL static
Definition at line 2344 of file system_parameter.c.
bool PRM_DEBUG_AUTOCOMMIT = false
Definition at line 2241 of file system_parameter.c.
bool prm_debug_autocommit_default = false static
Definition at line 2242 of file system_parameter.c.
unsigned int prm_debug_autocommit_flag = 0 static
Definition at line 2243 of file system_parameter.c.
bool PRM_DEBUG_BESTSPACE = false
Definition at line 2233 of file system_parameter.c.
bool prm_debug_bestspace_default = false static
Definition at line 2234 of file system_parameter.c.
unsigned int prm_debug_bestspace_flag = 0 static
Definition at line 2235 of file system_parameter.c.
bool PRM_DEBUG_ES = false
Definition at line 2229 of file system_parameter.c.
bool prm_debug_es_default = false static
Definition at line 2230 of file system_parameter.c.
unsigned int prm_debug_es_flag = 0 static
Definition at line 2231 of file system_parameter.c.
bool PRM_DEBUG_LOG_ARCHIVES = false
Definition at line 2225 of file system_parameter.c.
bool prm_debug_log_archives_default = false static
Definition at line 2226 of file system_parameter.c.
unsigned int prm_debug_log_archives_flag = 0 static
Definition at line 2227 of file system_parameter.c.
bool PRM_DEBUG_LOGWR = false
Definition at line 2237 of file system_parameter.c.
bool prm_debug_logwr_default = false static
Definition at line 2238 of file system_parameter.c.
unsigned int prm_debug_logwr_flag = 0 static
Definition at line 2239 of file system_parameter.c.
bool PRM_DEBUG_REPLICATION_DATA = false
Definition at line 2245 of file system_parameter.c.
bool prm_debug_replication_data_default = false static
Definition at line 2246 of file system_parameter.c.
unsigned int prm_debug_replication_data_flag = 0 static
Definition at line 2247 of file system_parameter.c.
SYSPRM_PARAM prm_Def[] static
Definition at line 2383 of file system_parameter.c.
int PRM_DEFAULT_WEEK_FORMAT = 0
Definition at line 1273 of file system_parameter.c.
bool PRM_DISABLE_VACUUM = false
Definition at line 2020 of file system_parameter.c.
bool prm_disable_vacuum_default = false static
Definition at line 2021 of file system_parameter.c.
unsigned int prm_disable_vacuum_flag = 0 static
Definition at line 2022 of file system_parameter.c.
bool PRM_DISK_LOGGING = false
Definition at line 2133 of file system_parameter.c.
bool prm_disk_logging_default = false static
Definition at line 2134 of file system_parameter.c.
unsigned int prm_disk_logging_flag = 0 static
Definition at line 2135 of file system_parameter.c.
const char* PRM_DL_FORK = ""
Definition at line 1653 of file system_parameter.c.
const char* prm_dl_fork_default = NULL static
Definition at line 1654 of file system_parameter.c.
unsigned int prm_dl_fork_flag = 0 static
Definition at line 1655 of file system_parameter.c.
bool PRM_DONT_REUSE_HEAP_FILE = false
Definition at line 1187 of file system_parameter.c.
bool prm_dont_reuse_heap_file_default = false static
Definition at line 1188 of file system_parameter.c.
unsigned int prm_dont_reuse_heap_file_flag = 0 static
Definition at line 1189 of file system_parameter.c.
unsigned int PRM_DWB_BLOCKS = 2
Definition at line 2205 of file system_parameter.c.
unsigned int prm_dwb_blocks_default = 2 static
Definition at line 2207 of file system_parameter.c.
unsigned int prm_dwb_blocks_flag = 0 static
Definition at line 2206 of file system_parameter.c.
unsigned int prm_dwb_blocks_lower = 0 static
Definition at line 2209 of file system_parameter.c.
unsigned int prm_dwb_blocks_upper = 32 static
Definition at line 2208 of file system_parameter.c.
bool PRM_DWB_LOGGING = false
Definition at line 2215 of file system_parameter.c.
bool prm_dwb_logging_default = false static
Definition at line 2216 of file system_parameter.c.
unsigned int prm_dwb_logging_flag = 0 static
Definition at line 2217 of file system_parameter.c.
unsigned int PRM_DWB_SIZE = 2 * 1024 * 1024
Definition at line 2199 of file system_parameter.c.
unsigned int prm_dwb_size_default = (2 * 1024 * 1024) static
Definition at line 2201 of file system_parameter.c.
unsigned int prm_dwb_size_flag = 0 static
Definition at line 2200 of file system_parameter.c.
unsigned int prm_dwb_size_lower = 0 static
Definition at line 2203 of file system_parameter.c.
unsigned int prm_dwb_size_upper = (32 * 1024 * 1024) static
Definition at line 2202 of file system_parameter.c.
bool PRM_ENABLE_DWB_FLUSH_THREAD = true
Definition at line 2211 of file system_parameter.c.
bool prm_enable_dwb_flush_thread_default = true static
Definition at line 2212 of file system_parameter.c.
unsigned int prm_enable_dwb_flush_thread_flag = 0 static
Definition at line 2213 of file system_parameter.c.
bool PRM_ENABLE_HISTO = false
Definition at line 1207 of file system_parameter.c.
bool prm_enable_histo_default = false static
Definition at line 1208 of file system_parameter.c.
unsigned int prm_enable_histo_flag = 0 static
Definition at line 1209 of file system_parameter.c.
bool PRM_ENABLE_STRING_COMPRESSION = true
Definition at line 2123 of file system_parameter.c.
bool prm_enable_string_compression_default = true static
Definition at line 2124 of file system_parameter.c.
unsigned int prm_enable_string_compression_flag = 0 static
Definition at line 2125 of file system_parameter.c.
int PRM_ER_BTREE_DEBUG = 0
Definition at line 932 of file system_parameter.c.
int prm_er_btree_debug_default = 0 static
Definition at line 933 of file system_parameter.c.
unsigned int prm_er_btree_debug_flag = 0 static
Definition at line 934 of file system_parameter.c.
int PRM_ER_EXIT_ASK = ER_EXIT_DEFAULT
Definition at line 946 of file system_parameter.c.
int prm_er_exit_ask_default = ER_EXIT_DEFAULT static
Definition at line 947 of file system_parameter.c.
unsigned int prm_er_exit_ask_flag = 0 static
Definition at line 948 of file system_parameter.c.
bool PRM_ER_LOG_DEBUG = false
Definition at line 924 of file system_parameter.c.
bool prm_er_log_debug_default = true static
Definition at line 926 of file system_parameter.c.
unsigned int prm_er_log_debug_flag = 0 static
Definition at line 930 of file system_parameter.c.
const char* PRM_ER_LOG_FILE = sysprm_error_log_file
Definition at line 955 of file system_parameter.c.
const char* prm_er_log_file_default = sysprm_error_log_file static
Definition at line 956 of file system_parameter.c.
unsigned int prm_er_log_file_flag = 0 static
Definition at line 957 of file system_parameter.c.
int PRM_ER_LOG_LEVEL = ER_NOTIFICATION_SEVERITY
Definition at line 936 of file system_parameter.c.
int prm_er_log_level_default = ER_NOTIFICATION_SEVERITY static
Definition at line 937 of file system_parameter.c.
unsigned int prm_er_log_level_flag = 0 static
Definition at line 940 of file system_parameter.c.
int prm_er_log_level_lower = ER_FATAL_ERROR_SEVERITY static
Definition at line 938 of file system_parameter.c.
int prm_er_log_level_upper = ER_NOTIFICATION_SEVERITY static
Definition at line 939 of file system_parameter.c.
int PRM_ER_LOG_SIZE = (512 * 1024 * 1024)
Definition at line 950 of file system_parameter.c.
int prm_er_log_size_default = (512 * 1024 * 1024) static
Definition at line 951 of file system_parameter.c.
unsigned int prm_er_log_size_flag = 0 static
Definition at line 953 of file system_parameter.c.
int prm_er_log_size_lower = (100 * 80) static
Definition at line 952 of file system_parameter.c.
int PRM_ER_LOG_VACUUM = 1
Definition at line 2016 of file system_parameter.c.
int prm_er_log_vacuum_default = 1 static
Definition at line 2017 of file system_parameter.c.
unsigned int prm_er_log_vacuum_flag = 0 static
Definition at line 2018 of file system_parameter.c.
bool PRM_ER_LOG_WARNING = false
Definition at line 942 of file system_parameter.c.
bool prm_er_log_warning_default = false static
Definition at line 943 of file system_parameter.c.
unsigned int prm_er_log_warning_flag = 0 static
Definition at line 944 of file system_parameter.c.
bool PRM_ER_PRODUCTION_MODE = true
Definition at line 1657 of file system_parameter.c.
bool prm_er_production_mode_default = true static
Definition at line 1658 of file system_parameter.c.
unsigned int prm_er_production_mode_flag = 0 static
Definition at line 1659 of file system_parameter.c.
int PRM_ER_STOP_ON_ERROR = 0
Definition at line 1661 of file system_parameter.c.
int prm_er_stop_on_error_default = 0 static
Definition at line 1662 of file system_parameter.c.
unsigned int prm_er_stop_on_error_flag = 0 static
Definition at line 1664 of file system_parameter.c.
int prm_er_stop_on_error_upper = 0 static
Definition at line 1663 of file system_parameter.c.
int* PRM_EVENT_ACTIVATION = int_list_initial
Definition at line 1746 of file system_parameter.c.
bool* prm_event_activation_default = NULL static
Definition at line 1747 of file system_parameter.c.
unsigned int prm_event_activation_flag = 0 static
Definition at line 1748 of file system_parameter.c.
const char* PRM_EVENT_HANDLER = ""
Definition at line 1742 of file system_parameter.c.
const char* prm_event_handler_default = NULL static
Definition at line 1743 of file system_parameter.c.
unsigned int prm_event_handler_flag = 0 static
Definition at line 1744 of file system_parameter.c.
bool PRM_EXAMINE_CLIENT_CACHED_LOCKS = false
Definition at line 2097 of file system_parameter.c.
bool prm_examine_client_cached_locks_default = false static
Definition at line 2098 of file system_parameter.c.
unsigned int prm_examine_client_cached_locks_flag = 0 static
Definition at line 2099 of file system_parameter.c.
int PRM_EXTENDED_STATISTICS = 15
Definition at line 2117 of file system_parameter.c.
int prm_extended_statistics_default = 15 static
Definition at line 2118 of file system_parameter.c.
unsigned int prm_extended_statistics_flag = 0 static
Definition at line 2121 of file system_parameter.c.
int prm_extended_statistics_lower = 0 static
Definition at line 2119 of file system_parameter.c.
int prm_extended_statistics_upper = PERFMON_ACTIVATION_FLAG_MAX_VALUE static
Definition at line 2120 of file system_parameter.c.
bool PRM_FAULT_INJECTION_ACTION_PREFER_ABORT_TO_EXIT = true
Definition at line 2071 of file system_parameter.c.
bool prm_fault_injection_action_prefer_abort_to_exit_default = true static
Definition at line 2073 of file system_parameter.c.
unsigned int prm_fault_injection_action_prefer_abort_to_exit_flag = 0 static
Definition at line 2072 of file system_parameter.c.
int* prm_fault_injection_id_default = NULL static
Definition at line 2063 of file system_parameter.c.
int prm_fault_injection_id_flag = 0 static
Definition at line 2062 of file system_parameter.c.
int* PRM_FAULT_INJECTION_IDS = int_list_initial
Definition at line 2061 of file system_parameter.c.
int PRM_FAULT_INJECTION_TEST = FI_GROUP_NONE
Definition at line 2065 of file system_parameter.c.
int prm_fault_injection_test_default = FI_GROUP_NONE static
Definition at line 2067 of file system_parameter.c.
int prm_fault_injection_test_flag = 0 static
Definition at line 2066 of file system_parameter.c.
int prm_fault_injection_test_lower = FI_GROUP_NONE static
Definition at line 2068 of file system_parameter.c.
int prm_fault_injection_test_upper = FI_GROUP_MAX static
Definition at line 2069 of file system_parameter.c.
bool PRM_FILE_LOGGING = false
Definition at line 2137 of file system_parameter.c.
bool prm_file_logging_default = false static
Definition at line 2138 of file system_parameter.c.
unsigned int prm_file_logging_flag = 0 static
Definition at line 2139 of file system_parameter.c.
struct { ... } prm_Files_loaded[MAX_NUM_OF_PRM_FILES_LOADED]
Referenced by prm_file_has_been_loaded(), sysprm_dump_parameters(), and sysprm_final().
int PRM_FILTER_PRED_MAX_CACHE_CLONES = 10
Definition at line 1402 of file system_parameter.c.
int prm_filter_pred_max_cache_clones_default = 10 static
Definition at line 1403 of file system_parameter.c.
unsigned int prm_filter_pred_max_cache_clones_flag = 0 static
Definition at line 1404 of file system_parameter.c.
int PRM_FILTER_PRED_MAX_CACHE_ENTRIES = 1000
Definition at line 1398 of file system_parameter.c.
int prm_filter_pred_max_cache_entries_default = 1000 static
Definition at line 1399 of file system_parameter.c.
unsigned int prm_filter_pred_max_cache_entries_flag = 0 static
Definition at line 1400 of file system_parameter.c.
bool PRM_FORCE_REMOVE_LOG_ARCHIVES = true
Definition at line 1695 of file system_parameter.c.
bool prm_force_remove_log_archives_default = true static
Definition at line 1696 of file system_parameter.c.
unsigned int prm_force_remove_log_archives_flag = 0 static
Definition at line 1697 of file system_parameter.c.
bool PRM_FORCE_RESTART_TO_SKIP_RECOVERY = false
Definition at line 2113 of file system_parameter.c.
bool prm_force_restart_to_skip_recovery_default = false static
Definition at line 2114 of file system_parameter.c.
unsigned int prm_force_restart_to_skip_recovery_flag = 0 static
Definition at line 2115 of file system_parameter.c.
bool PRM_GC_ENABLE = false
Definition at line 1100 of file system_parameter.c.
bool prm_gc_enable_default = false static
Definition at line 1101 of file system_parameter.c.
unsigned int prm_gc_enable_flag = 0 static
Definition at line 1102 of file system_parameter.c.
bool PRM_GENERAL_RESERVE_01 = false
Definition at line 1598 of file system_parameter.c.
bool prm_general_reserve_01_default = false static
Definition at line 1599 of file system_parameter.c.
unsigned int prm_general_reserve_01_flag = 0 static
Definition at line 1600 of file system_parameter.c.
UINT64 PRM_GENERIC_VOL_PREALLOC_SIZE
Definition at line 1819 of file system_parameter.c.
UINT64 prm_generic_vol_prealloc_size_default = 52428800ULL static
Definition at line 1820 of file system_parameter.c.
unsigned int prm_generic_vol_prealloc_size_flag = 0 static
Definition at line 1823 of file system_parameter.c.
UINT64 prm_generic_vol_prealloc_size_lower = 0ULL static
Definition at line 1821 of file system_parameter.c.
UINT64 prm_generic_vol_prealloc_size_upper = 21474836480ULL static
Definition at line 1822 of file system_parameter.c.
UINT64 PRM_GROUP_CONCAT_MAX_LEN = 1024
Definition at line 1303 of file system_parameter.c.
UINT64 prm_group_concat_max_len_default = 1024 static
Definition at line 1304 of file system_parameter.c.
unsigned int prm_group_concat_max_len_flag = 0 static
Definition at line 1307 of file system_parameter.c.
UINT64 prm_group_concat_max_len_lower = 4 static
Definition at line 1305 of file system_parameter.c.
UINT64 prm_group_concat_max_len_upper = INT_MAX static
Definition at line 1306 of file system_parameter.c.
int PRM_HA_APPLY_MAX_MEM_SIZE = HB_DEFAULT_APPLY_MAX_MEM_SIZE
Definition at line 1469 of file system_parameter.c.
int prm_ha_apply_max_mem_size_default = HB_DEFAULT_APPLY_MAX_MEM_SIZE static
Definition at line 1470 of file system_parameter.c.
unsigned int prm_ha_apply_max_mem_size_flag = 0 static
Definition at line 1473 of file system_parameter.c.
int prm_ha_apply_max_mem_size_lower = 0 static
Definition at line 1472 of file system_parameter.c.
int prm_ha_apply_max_mem_size_upper = INT_MAX static
Definition at line 1471 of file system_parameter.c.
int* PRM_HA_APPLYLOGDB_IGNORE_ERROR_LIST = int_list_initial
Definition at line 1533 of file system_parameter.c.
bool* prm_ha_applylogdb_ignore_error_list_default = NULL static
Definition at line 1534 of file system_parameter.c.
unsigned int prm_ha_applylogdb_ignore_error_list_flag = 0 static
Definition at line 1535 of file system_parameter.c.
int PRM_HA_APPLYLOGDB_LOG_WAIT_TIME_IN_SECS = -1
Definition at line 1537 of file system_parameter.c.
int prm_ha_applylogdb_log_wait_time_in_secs_default = -1 static
Definition at line 1538 of file system_parameter.c.
unsigned int prm_ha_applylogdb_log_wait_time_in_secs_flag = 0 static
Definition at line 1540 of file system_parameter.c.
int prm_ha_applylogdb_log_wait_time_in_secs_lower = -1 static
Definition at line 1539 of file system_parameter.c.
int PRM_HA_APPLYLOGDB_MAX_COMMIT_INTERVAL_IN_MSECS = 500
Definition at line 1586 of file system_parameter.c.
int prm_ha_applylogdb_max_commit_interval_in_msecs_default = 500 static
Definition at line 1587 of file system_parameter.c.
unsigned int prm_ha_applylogdb_max_commit_interval_in_msecs_flag = 0 static
Definition at line 1590 of file system_parameter.c.
int prm_ha_applylogdb_max_commit_interval_in_msecs_lower = 0 static
Definition at line 1589 of file system_parameter.c.
int prm_ha_applylogdb_max_commit_interval_in_msecs_upper = INT_MAX static
Definition at line 1588 of file system_parameter.c.
int* PRM_HA_APPLYLOGDB_RETRY_ERROR_LIST = int_list_initial
Definition at line 1529 of file system_parameter.c.
bool* prm_ha_applylogdb_retry_error_list_default = NULL static
Definition at line 1530 of file system_parameter.c.
unsigned int prm_ha_applylogdb_retry_error_list_flag = 0 static
Definition at line 1531 of file system_parameter.c.
int PRM_HA_CALC_SCORE_INTERVAL_IN_MSECS = HB_DEFAULT_CALC_SCORE_INTERVAL_IN_MSECS
Definition at line 1489 of file system_parameter.c.
int prm_ha_calc_score_interval_in_msecs_default = HB_DEFAULT_CALC_SCORE_INTERVAL_IN_MSECS static
Definition at line 1490 of file system_parameter.c.
unsigned int prm_ha_calc_score_interval_in_msecs_flag = 0 static
Definition at line 1491 of file system_parameter.c.
int PRM_HA_CHANGEMODE_INTERVAL_IN_MSECS = HB_DEFAULT_CHANGEMODE_INTERVAL_IN_MSECS
Definition at line 1517 of file system_parameter.c.
int prm_ha_changemode_interval_in_msecs_default = HB_DEFAULT_CHANGEMODE_INTERVAL_IN_MSECS static
Definition at line 1518 of file system_parameter.c.
unsigned int prm_ha_changemode_interval_in_msecs_flag = 0 static
Definition at line 1519 of file system_parameter.c.
int PRM_HA_CHECK_DISK_FAILURE_INTERVAL_IN_SECS = 15
Definition at line 1592 of file system_parameter.c.
int prm_ha_check_disk_failure_interval_in_secs_default = 15 static
Definition at line 1593 of file system_parameter.c.
unsigned int prm_ha_check_disk_failure_interval_in_secs_flag = 0 static
Definition at line 1596 of file system_parameter.c.
int prm_ha_check_disk_failure_interval_in_secs_lower = 0 static
Definition at line 1595 of file system_parameter.c.
int prm_ha_check_disk_failure_interval_in_secs_upper = INT_MAX static
Definition at line 1594 of file system_parameter.c.
const char* PRM_HA_COPY_LOG_BASE = ""
Definition at line 1461 of file system_parameter.c.
const char* prm_ha_copy_log_base_default = NULL static
Definition at line 1462 of file system_parameter.c.
unsigned int prm_ha_copy_log_base_flag = 0 static
Definition at line 1463 of file system_parameter.c.
int PRM_HA_COPY_LOG_MAX_ARCHIVES = 1
Definition at line 1552 of file system_parameter.c.
int prm_ha_copy_log_max_archives_default = 1 static
Definition at line 1553 of file system_parameter.c.
unsigned int prm_ha_copy_log_max_archives_flag = 0 static
Definition at line 1556 of file system_parameter.c.
int prm_ha_copy_log_max_archives_lower = 0 static
Definition at line 1555 of file system_parameter.c.
int prm_ha_copy_log_max_archives_upper = INT_MAX static
Definition at line 1554 of file system_parameter.c.
int PRM_HA_COPY_LOG_TIMEOUT = 5
Definition at line 1558 of file system_parameter.c.
int prm_ha_copy_log_timeout_default = 5 static
Definition at line 1559 of file system_parameter.c.
unsigned int prm_ha_copy_log_timeout_flag = 0 static
Definition at line 1562 of file system_parameter.c.
int prm_ha_copy_log_timeout_lower = -1 static
Definition at line 1561 of file system_parameter.c.
int prm_ha_copy_log_timeout_upper = INT_MAX static
Definition at line 1560 of file system_parameter.c.
const char* PRM_HA_COPY_SYNC_MODE = ""
Definition at line 1465 of file system_parameter.c.
const char* prm_ha_copy_sync_mode_default = NULL static
Definition at line 1466 of file system_parameter.c.
unsigned int prm_ha_copy_sync_mode_flag = 0 static
Definition at line 1467 of file system_parameter.c.
const char* PRM_HA_DB_LIST = ""
Definition at line 1457 of file system_parameter.c.
Referenced by prm_check_parameters().
const char* prm_ha_db_list_default = NULL static
Definition at line 1458 of file system_parameter.c.
unsigned int prm_ha_db_list_flag = 0 static
Definition at line 1459 of file system_parameter.c.
int PRM_HA_DELAY_LIMIT_DELTA_IN_SECS = 0
Definition at line 1580 of file system_parameter.c.
int prm_ha_delay_limit_delta_in_secs_default = 0 static
Definition at line 1581 of file system_parameter.c.
unsigned int prm_ha_delay_limit_delta_in_secs_flag = 0 static
Definition at line 1584 of file system_parameter.c.
int prm_ha_delay_limit_delta_in_secs_lower = 0 static
Definition at line 1583 of file system_parameter.c.
int prm_ha_delay_limit_delta_in_secs_upper = INT_MAX static
Definition at line 1582 of file system_parameter.c.
int PRM_HA_DELAY_LIMIT_IN_SECS = 0
Definition at line 1574 of file system_parameter.c.
int prm_ha_delay_limit_in_secs_default = 0 static
Definition at line 1575 of file system_parameter.c.
unsigned int prm_ha_delay_limit_in_secs_flag = 0 static
Definition at line 1578 of file system_parameter.c.
int prm_ha_delay_limit_in_secs_lower = 0 static
Definition at line 1577 of file system_parameter.c.
int prm_ha_delay_limit_in_secs_upper = INT_MAX static
Definition at line 1576 of file system_parameter.c.
int PRM_HA_FAILOVER_WAIT_TIME_IN_MSECS = HB_DEFAULT_FAILOVER_WAIT_TIME_IN_MSECS
Definition at line 1493 of file system_parameter.c.
int prm_ha_failover_wait_time_in_msecs_default = HB_DEFAULT_FAILOVER_WAIT_TIME_IN_MSECS static
Definition at line 1494 of file system_parameter.c.
unsigned int prm_ha_failover_wait_time_in_msecs_flag = 0 static
Definition at line 1495 of file system_parameter.c.
int PRM_HA_HEARTBEAT_INTERVAL_IN_MSECS = HB_DEFAULT_HEARTBEAT_INTERVAL_IN_MSECS
Definition at line 1485 of file system_parameter.c.
int prm_ha_heartbeat_interval_in_msecs_default = HB_DEFAULT_HEARTBEAT_INTERVAL_IN_MSECS static
Definition at line 1486 of file system_parameter.c.
unsigned int prm_ha_heartbeat_interval_in_msecs_flag = 0 static
Definition at line 1487 of file system_parameter.c.
int prm_ha_init_timer_im_msecs_default = HB_DEFAULT_INIT_TIMER_IN_MSECS static
Definition at line 1482 of file system_parameter.c.
unsigned int prm_ha_init_timer_im_msecs_flag = 0 static
Definition at line 1483 of file system_parameter.c.
int PRM_HA_INIT_TIMER_IN_MSECS = HB_DEFAULT_INIT_TIMER_IN_MSECS
Definition at line 1481 of file system_parameter.c.
int PRM_HA_LOG_APPLIER_STATE = HA_LOG_APPLIER_STATE_UNREGISTERED
Definition at line 1443 of file system_parameter.c.
int prm_ha_log_applier_state_default = HA_LOG_APPLIER_STATE_UNREGISTERED static
Definition at line 1444 of file system_parameter.c.
unsigned int prm_ha_log_applier_state_flag = 0 static
Definition at line 1447 of file system_parameter.c.
int prm_ha_log_applier_state_lower = HA_LOG_APPLIER_STATE_UNREGISTERED static
Definition at line 1446 of file system_parameter.c.
int prm_ha_log_applier_state_upper = HA_LOG_APPLIER_STATE_ERROR static
Definition at line 1445 of file system_parameter.c.
int PRM_HA_MAX_HEARTBEAT_GAP = HB_DEFAULT_MAX_HEARTBEAT_GAP
Definition at line 1521 of file system_parameter.c.
int prm_ha_max_heartbeat_gap_default = HB_DEFAULT_MAX_HEARTBEAT_GAP static
Definition at line 1522 of file system_parameter.c.
unsigned int prm_ha_max_heartbeat_gap_flag = 0 static
Definition at line 1523 of file system_parameter.c.
int PRM_HA_MAX_PROCESS_DEREG_CONFIRM = HB_DEFAULT_MAX_PROCESS_DEREG_CONFIRM
Definition at line 1509 of file system_parameter.c.
int prm_ha_max_process_dereg_confirm_default = HB_DEFAULT_MAX_PROCESS_DEREG_CONFIRM static
Definition at line 1510 of file system_parameter.c.
unsigned int prm_ha_max_process_dereg_confirm_flag = 0 static
Definition at line 1511 of file system_parameter.c.
int PRM_HA_MAX_PROCESS_START_CONFIRM = HB_DEFAULT_MAX_PROCESS_START_CONFIRM
Definition at line 1505 of file system_parameter.c.
int prm_ha_max_process_start_confirm_default = HB_DEFAULT_MAX_PROCESS_START_CONFIRM static
Definition at line 1506 of file system_parameter.c.
unsigned int prm_ha_max_process_start_confirm_flag = 0 static
Definition at line 1507 of file system_parameter.c.
int PRM_HA_MODE = HA_MODE_OFF
Definition at line 1430 of file system_parameter.c.
Referenced by prm_check_parameters(), prm_read_and_parse_ini_file(), sysprm_final(), and sysprm_load_and_init_internal().
int prm_ha_mode_default = HA_MODE_OFF static
Definition at line 1431 of file system_parameter.c.
unsigned int prm_ha_mode_flag = 0 static
Definition at line 1435 of file system_parameter.c.
int PRM_HA_MODE_FOR_SA_UTILS_ONLY = HA_MODE_OFF
Definition at line 1434 of file system_parameter.c.
Referenced by sysprm_final().
int prm_ha_mode_lower = HA_MODE_OFF static
Definition at line 1433 of file system_parameter.c.
int prm_ha_mode_upper = HA_MODE_REPLICA static
Definition at line 1432 of file system_parameter.c.
const char* PRM_HA_NODE_LIST = ""
Definition at line 1449 of file system_parameter.c.
Referenced by prm_check_parameters().
const char* prm_ha_node_list_default = NULL static
Definition at line 1450 of file system_parameter.c.
unsigned int prm_ha_node_list_flag = 0 static
Definition at line 1451 of file system_parameter.c.
const char* PRM_HA_PING_HOSTS = ""
Definition at line 1525 of file system_parameter.c.
const char* prm_ha_ping_hosts_default = NULL static
Definition at line 1526 of file system_parameter.c.
unsigned int prm_ha_ping_hosts_flag = 0 static
Definition at line 1527 of file system_parameter.c.
int PRM_HA_PORT_ID = HB_DEFAULT_HA_PORT_ID
Definition at line 1475 of file system_parameter.c.
int prm_ha_port_id_default = HB_DEFAULT_HA_PORT_ID static
Definition at line 1476 of file system_parameter.c.
unsigned int prm_ha_port_id_flag = 0 static
Definition at line 1477 of file system_parameter.c.
int prm_ha_port_id_lower = 1 static
Definition at line 1479 of file system_parameter.c.
int prm_ha_port_id_upper = USHRT_MAX static
Definition at line 1478 of file system_parameter.c.
int PRM_HA_PROCESS_DEREG_CONFIRM_INTERVAL_IN_MSECS = HB_DEFAULT_DEREG_CONFIRM_INTERVAL_IN_MSECS
Definition at line 1501 of file system_parameter.c.
int prm_ha_process_dereg_confirm_interval_in_msecs_default = HB_DEFAULT_DEREG_CONFIRM_INTERVAL_IN_MSECS static
Definition at line 1502 of file system_parameter.c.
unsigned int prm_ha_process_dereg_confirm_interval_in_msecs_flag = 0 static
Definition at line 1503 of file system_parameter.c.
int PRM_HA_PROCESS_START_CONFIRM_INTERVAL_IN_MSECS = HB_DEFAULT_START_CONFIRM_INTERVAL_IN_MSECS
Definition at line 1497 of file system_parameter.c.
int prm_ha_process_start_confirm_interval_in_msecs_default = HB_DEFAULT_START_CONFIRM_INTERVAL_IN_MSECS static
Definition at line 1498 of file system_parameter.c.
unsigned int prm_ha_process_start_confirm_interval_in_msecs_flag = 0 static
Definition at line 1499 of file system_parameter.c.
bool PRM_HA_REPL_ENABLE_SERVER_SIDE_UPDATE = false
Definition at line 1979 of file system_parameter.c.
bool prm_ha_repl_enable_server_side_update_default = false static
Definition at line 1980 of file system_parameter.c.
unsigned int prm_ha_repl_enable_server_side_update_flag = 0 static
Definition at line 1981 of file system_parameter.c.
const char* PRM_HA_REPL_FILTER_FILE = ""
Definition at line 2081 of file system_parameter.c.
const char* prm_ha_repl_filter_file_default = "" static
Definition at line 2082 of file system_parameter.c.
unsigned int prm_ha_repl_filter_file_flag = 0 static
Definition at line 2083 of file system_parameter.c.
int PRM_HA_REPL_FILTER_TYPE = REPL_FILTER_NONE
Definition at line 2075 of file system_parameter.c.
int prm_ha_repl_filter_type_default = REPL_FILTER_NONE static
Definition at line 2076 of file system_parameter.c.
unsigned int prm_ha_repl_filter_type_flag = 0 static
Definition at line 2079 of file system_parameter.c.
int prm_ha_repl_filter_type_lower = REPL_FILTER_NONE static
Definition at line 2077 of file system_parameter.c.
int prm_ha_repl_filter_type_upper = REPL_FILTER_EXCLUDE_TBL static
Definition at line 2078 of file system_parameter.c.
int PRM_HA_REPLICA_DELAY_IN_SECS = 0
Definition at line 1564 of file system_parameter.c.
int prm_ha_replica_delay_in_secs_default = 0 static
Definition at line 1565 of file system_parameter.c.
unsigned int prm_ha_replica_delay_in_secs_flag = 0 static
Definition at line 1568 of file system_parameter.c.
int prm_ha_replica_delay_in_secs_lower = 0 static
Definition at line 1567 of file system_parameter.c.
int prm_ha_replica_delay_in_secs_upper = INT_MAX static
Definition at line 1566 of file system_parameter.c.
const char* PRM_HA_REPLICA_LIST = ""
Definition at line 1453 of file system_parameter.c.
const char* prm_ha_replica_list_default = NULL static
Definition at line 1454 of file system_parameter.c.
unsigned int prm_ha_replica_list_flag = 0 static
Definition at line 1455 of file system_parameter.c.
const char* PRM_HA_REPLICA_TIME_BOUND = ""
Definition at line 1570 of file system_parameter.c.
const char* prm_ha_replica_time_bound_default = NULL static
Definition at line 1571 of file system_parameter.c.
unsigned int prm_ha_replica_time_bound_flag = 0 static
Definition at line 1572 of file system_parameter.c.
int PRM_HA_SERVER_STATE = HA_SERVER_STATE_IDLE
Definition at line 1437 of file system_parameter.c.
int prm_ha_server_state_default = HA_SERVER_STATE_IDLE static
Definition at line 1438 of file system_parameter.c.
unsigned int prm_ha_server_state_flag = 0 static
Definition at line 1441 of file system_parameter.c.
int prm_ha_server_state_lower = HA_SERVER_STATE_IDLE static
Definition at line 1440 of file system_parameter.c.
int prm_ha_server_state_upper = HA_SERVER_STATE_DEAD static
Definition at line 1439 of file system_parameter.c.
int PRM_HA_SQL_LOG_MAX_SIZE_IN_MB = INT_MIN
Definition at line 1546 of file system_parameter.c.
int prm_ha_sql_log_max_size_in_mb_default = 50 static
Definition at line 1547 of file system_parameter.c.
unsigned int prm_ha_sql_log_max_size_in_mb_flag = 0 static
Definition at line 1550 of file system_parameter.c.
int prm_ha_sql_log_max_size_in_mb_lower = 1 static
Definition at line 1549 of file system_parameter.c.
int prm_ha_sql_log_max_size_in_mb_upper = 2048 static
Definition at line 1548 of file system_parameter.c.
bool PRM_HA_SQL_LOGGING = false
Definition at line 1542 of file system_parameter.c.
bool prm_ha_sql_logging_default = false static
Definition at line 1543 of file system_parameter.c.
unsigned int prm_ha_sql_logging_flag = 0 static
Definition at line 1544 of file system_parameter.c.
int PRM_HA_UNACCEPTABLE_PROC_RESTART_TIMEDIFF = HB_DEFAULT_UNACCEPTABLE_PROC_RESTART_TIMEDIFF_IN_MSECS
Definition at line 1513 of file system_parameter.c.
int prm_ha_unacceptable_proc_restart_timediff_default = HB_DEFAULT_UNACCEPTABLE_PROC_RESTART_TIMEDIFF_IN_MSECS static
Definition at line 1514 of file system_parameter.c.
unsigned int prm_ha_unacceptable_proc_restart_timediff_flag = 0 static
Definition at line 1515 of file system_parameter.c.
bool PRM_HEAP_INFO_CACHE_LOGGING = false
Definition at line 2289 of file system_parameter.c.
bool prm_heap_info_cache_logging_default = false static
Definition at line 2290 of file system_parameter.c.
unsigned int prm_heap_info_cache_logging_flag = 0 static
Definition at line 2291 of file system_parameter.c.
int PRM_HF_MAX_BESTSPACE_ENTRIES = 1000000
Definition at line 993 of file system_parameter.c.
int prm_hf_max_bestspace_entries_default = 1000000 static
Definition at line 994 of file system_parameter.c.
unsigned int prm_hf_max_bestspace_entries_flag = 0 static
Definition at line 995 of file system_parameter.c.
float PRM_HF_UNFILL_FACTOR = 0.10f
Definition at line 987 of file system_parameter.c.
float prm_hf_unfill_factor_default = 0.10f static
Definition at line 988 of file system_parameter.c.
unsigned int prm_hf_unfill_factor_flag = 0 static
Definition at line 991 of file system_parameter.c.
float prm_hf_unfill_factor_lower = 0.0f static
Definition at line 989 of file system_parameter.c.
float prm_hf_unfill_factor_upper = 0.3f static
Definition at line 990 of file system_parameter.c.
bool PRM_HOSTVAR_LATE_BINDING = false
Definition at line 1203 of file system_parameter.c.
bool prm_hostvar_late_binding_default = false static
Definition at line 1204 of file system_parameter.c.
unsigned int prm_hostvar_late_binding_flag = 0 static
Definition at line 1205 of file system_parameter.c.
UINT64 PRM_IB_TASK_MEMSIZE = 16 * ONE_M
Definition at line 2261 of file system_parameter.c.
UINT64 prm_ib_task_memsize_default = 16 * ONE_M static
Definition at line 2262 of file system_parameter.c.
unsigned int prm_ib_task_memsize_flag = 0 static
Definition at line 2265 of file system_parameter.c.
UINT64 prm_ib_task_memsize_lower = ONE_K static
Definition at line 2263 of file system_parameter.c.
UINT64 prm_ib_task_memsize_upper = 128 * ONE_M static
Definition at line 2264 of file system_parameter.c.
bool PRM_IGNORE_TRAILING_SPACE = false
Definition at line 2333 of file system_parameter.c.
bool prm_ignore_trailing_space_default = false static
Definition at line 2334 of file system_parameter.c.
unsigned int prm_ignore_trailing_space_flag = 0 static
Definition at line 2335 of file system_parameter.c.
int PRM_INDEX_SCAN_KEY_BUFFER_PAGES = 20
Definition at line 1182 of file system_parameter.c.
int prm_index_scan_key_buffer_pages_default = 20 static
Definition at line 1183 of file system_parameter.c.
unsigned int prm_index_scan_key_buffer_pages_flag = 0 static
Definition at line 1185 of file system_parameter.c.
int prm_index_scan_key_buffer_pages_lower = 0 static
Definition at line 1184 of file system_parameter.c.
int PRM_INSERT_MODE = 1 + 2
Definition at line 1191 of file system_parameter.c.
int prm_insert_mode_default = 1 + 2 static
Definition at line 1192 of file system_parameter.c.
unsigned int prm_insert_mode_flag = 0 static
Definition at line 1195 of file system_parameter.c.
int prm_insert_mode_lower = 0 static
Definition at line 1193 of file system_parameter.c.
int prm_insert_mode_upper = 31 static
Definition at line 1194 of file system_parameter.c.
bool PRM_INTL_CHECK_INPUT_STRING = false
Definition at line 1811 of file system_parameter.c.
bool prm_intl_check_input_string_default = false static
Definition at line 1812 of file system_parameter.c.
unsigned int prm_intl_check_input_string_flag = 0 static
Definition at line 1813 of file system_parameter.c.
char* PRM_INTL_COLLATION = NULL
Definition at line 1840 of file system_parameter.c.
char* prm_intl_collation_default = NULL static
Definition at line 1841 of file system_parameter.c.
unsigned int prm_intl_collation_flag = 0 static
Definition at line 1842 of file system_parameter.c.
char* PRM_INTL_DATE_LANG = NULL
Definition at line 1799 of file system_parameter.c.
char* prm_intl_date_lang_default = NULL static
Definition at line 1800 of file system_parameter.c.
unsigned int prm_intl_date_lang_flag = 0 static
Definition at line 1801 of file system_parameter.c.
bool PRM_INTL_MBS_SUPPORT = false
Definition at line 1621 of file system_parameter.c.
bool prm_intl_mbs_support_default = false static
Definition at line 1622 of file system_parameter.c.
unsigned int prm_intl_mbs_support_flag = 0 static
Definition at line 1623 of file system_parameter.c.
char* PRM_INTL_NUMBER_LANG = NULL
Definition at line 1795 of file system_parameter.c.
char* prm_intl_number_lang_default = NULL static
Definition at line 1796 of file system_parameter.c.
unsigned int prm_intl_number_lang_flag = 0 static
Definition at line 1797 of file system_parameter.c.
UINT64 PRM_IO_BACKUP_MAX_VOLUME_SIZE = 0
Definition at line 1151 of file system_parameter.c.
UINT64 prm_io_backup_max_volume_size_default = 0 static
Definition at line 1152 of file system_parameter.c.
unsigned int prm_io_backup_max_volume_size_flag = 0 static
Definition at line 1155 of file system_parameter.c.
UINT64 prm_io_backup_max_volume_size_lower = 1024 * 32 static
Definition at line 1153 of file system_parameter.c.
UINT64 prm_io_backup_max_volume_size_upper = DB_BIGINT_MAX static
Definition at line 1154 of file system_parameter.c.
int PRM_IO_BACKUP_NBUFFERS = 256
Definition at line 1146 of file system_parameter.c.
int prm_io_backup_nbuffers_default = 256 static
Definition at line 1147 of file system_parameter.c.
unsigned int prm_io_backup_nbuffers_flag = 0 static
Definition at line 1149 of file system_parameter.c.
int prm_io_backup_nbuffers_lower = 256 static
Definition at line 1148 of file system_parameter.c.
int PRM_IO_BACKUP_SLEEP_MSECS = 0
Definition at line 1157 of file system_parameter.c.
int prm_io_backup_sleep_msecs_default = 0 static
Definition at line 1158 of file system_parameter.c.
unsigned int prm_io_backup_sleep_msecs_flag = 0 static
Definition at line 1160 of file system_parameter.c.
int prm_io_backup_sleep_msecs_lower = 0 static
Definition at line 1159 of file system_parameter.c.
bool PRM_IO_LOCKF_ENABLE = false
Definition at line 967 of file system_parameter.c.
bool prm_io_lockf_enable_default = true static
Definition at line 968 of file system_parameter.c.
unsigned int prm_io_lockf_enable_flag = 0 static
Definition at line 969 of file system_parameter.c.
const char* PRM_IO_TEMP_VOLUME_PATH = ""
Definition at line 1722 of file system_parameter.c.
char* prm_io_temp_volume_path_default = NULL static
Definition at line 1723 of file system_parameter.c.
unsigned int prm_io_temp_volume_path_flag = 0 static
Definition at line 1724 of file system_parameter.c.
const char* PRM_IO_VOLUME_EXT_PATH = ""
Definition at line 1730 of file system_parameter.c.
char* prm_io_volume_ext_path_default = NULL static
Definition at line 1731 of file system_parameter.c.
unsigned int prm_io_volume_ext_path_flag = 0 static
Definition at line 1732 of file system_parameter.c.
bool PRM_JAVA_STORED_PROCEDURE = false
Definition at line 2297 of file system_parameter.c.
int PRM_JAVA_STORED_PROCEDURE_DEBUG = -1
Definition at line 2311 of file system_parameter.c.
int prm_java_stored_procedure_debug_default = -1 static
Definition at line 2312 of file system_parameter.c.
unsigned int prm_java_stored_procedure_debug_flag = 0 static
Definition at line 2315 of file system_parameter.c.
int prm_java_stored_procedure_debug_lower = -1 static
Definition at line 2314 of file system_parameter.c.
int prm_java_stored_procedure_debug_upper = 65535 static
Definition at line 2313 of file system_parameter.c.
bool prm_java_stored_procedure_default = false static
Definition at line 2298 of file system_parameter.c.
unsigned int prm_java_stored_procedure_flag = 0 static
Definition at line 2299 of file system_parameter.c.
const char* PRM_JAVA_STORED_PROCEDURE_JVM_OPTIONS = ""
Definition at line 2307 of file system_parameter.c.
const char* prm_java_stored_procedure_jvm_options_default = "" static
Definition at line 2308 of file system_parameter.c.
unsigned int prm_java_stored_procedure_jvm_options_flag = 0 static
Definition at line 2309 of file system_parameter.c.
int PRM_JAVA_STORED_PROCEDURE_PORT = 0
Definition at line 2301 of file system_parameter.c.
int prm_java_stored_procedure_port_default = 0 static
Definition at line 2302 of file system_parameter.c.
unsigned int prm_java_stored_procedure_port_flag = 0 static
Definition at line 2305 of file system_parameter.c.
int prm_java_stored_procedure_port_lower = 0 static
Definition at line 2304 of file system_parameter.c.
int prm_java_stored_procedure_port_upper = 65535 static
Definition at line 2303 of file system_parameter.c.
bool PRM_JAVA_STORED_PROCEDURE_RESERVE_01 = false
Definition at line 2317 of file system_parameter.c.
bool prm_java_stored_procedure_reserve_01_default = false static
Definition at line 2318 of file system_parameter.c.
unsigned int prm_java_stored_procedure_reserve_01_flag = 0 static
Definition at line 2319 of file system_parameter.c.
bool PRM_JSON_LOG_ALLOCATIONS = false
Definition at line 2157 of file system_parameter.c.
bool prm_json_log_allocations_default = false static
Definition at line 2158 of file system_parameter.c.
unsigned int prm_json_log_allocations_flag = 0 static
Definition at line 2159 of file system_parameter.c.
int PRM_JSON_MAX_ARRAY_IDX = 64 * ONE_K
Definition at line 2161 of file system_parameter.c.
int prm_json_max_array_idx_default = 64 * ONE_K static
Definition at line 2162 of file system_parameter.c.
unsigned int prm_json_max_array_idx_flag = 0 static
Definition at line 2163 of file system_parameter.c.
int prm_json_max_array_idx_lower = ONE_K static
Definition at line 2165 of file system_parameter.c.
int prm_json_max_array_idx_upper = ONE_M static
Definition at line 2164 of file system_parameter.c.
unsigned int prm_leap_second_support_flag = 0 static
Definition at line 2042 of file system_parameter.c.
float PRM_LIKE_TERM_SELECTIVITY = 0.1f
Definition at line 1335 of file system_parameter.c.
float prm_like_term_selectivity_default = 0.1f static
Definition at line 1336 of file system_parameter.c.
unsigned int prm_like_term_selectivity_flag = 0 static
Definition at line 1339 of file system_parameter.c.
float prm_like_term_selectivity_lower = 0.0f static
Definition at line 1338 of file system_parameter.c.
float prm_like_term_selectivity_upper = 1.0f static
Definition at line 1337 of file system_parameter.c.
int PRM_LIST_MAX_QUERY_CACHE_ENTRIES = 0
Definition at line 1412 of file system_parameter.c.
int prm_list_max_query_cache_entries_default = 0 static
Definition at line 1413 of file system_parameter.c.
unsigned int prm_list_max_query_cache_entries_flag = 0 static
Definition at line 1416 of file system_parameter.c.
int prm_list_max_query_cache_entries_lower = 0 static
Definition at line 1415 of file system_parameter.c.
int prm_list_max_query_cache_entries_upper = INT_MAX static
Definition at line 1414 of file system_parameter.c.
int PRM_LIST_MAX_QUERY_CACHE_PAGES = 0
Definition at line 1418 of file system_parameter.c.
int prm_list_max_query_cache_pages_default = 0 static
Definition at line 1419 of file system_parameter.c.
unsigned int prm_list_max_query_cache_pages_flag = 0 static
Definition at line 1422 of file system_parameter.c.
int prm_list_max_query_cache_pages_lower = 0 static
Definition at line 1421 of file system_parameter.c.
int prm_list_max_query_cache_pages_upper = INT_MAX static
Definition at line 1420 of file system_parameter.c.
int PRM_LIST_QUERY_CACHE_MODE = 2
Definition at line 1406 of file system_parameter.c.
int prm_list_query_cache_mode_default = 2 static
Definition at line 1407 of file system_parameter.c.
unsigned int prm_list_query_cache_mode_flag = 0 static
Definition at line 1410 of file system_parameter.c.
int prm_list_query_cache_mode_lower = 2 static
Definition at line 1409 of file system_parameter.c.
int prm_list_query_cache_mode_upper = 2 static
Definition at line 1408 of file system_parameter.c.
int PRM_LK_ESCALATION_AT = 100000
Definition at line 1020 of file system_parameter.c.
int prm_lk_escalation_at_default = 100000 static
Definition at line 1021 of file system_parameter.c.
unsigned int prm_lk_escalation_at_flag = 0 static
Definition at line 1023 of file system_parameter.c.
int prm_lk_escalation_at_lower = 5 static
Definition at line 1022 of file system_parameter.c.
int PRM_LK_MAX_SCANID_BIT = 32
Definition at line 1197 of file system_parameter.c.
int prm_lk_max_scanid_bit_default = 32 static
Definition at line 1198 of file system_parameter.c.
unsigned int prm_lk_max_scanid_bit_flag = 0 static
Definition at line 1201 of file system_parameter.c.
int prm_lk_max_scanid_bit_lower = 32 static
Definition at line 1199 of file system_parameter.c.
int prm_lk_max_scanid_bit_upper = 128 static
Definition at line 1200 of file system_parameter.c.
bool PRM_LK_ROLLBACK_ON_LOCK_ESCALATION = false
Definition at line 1025 of file system_parameter.c.
bool prm_lk_rollback_on_lock_escalation_default = false static
Definition at line 1026 of file system_parameter.c.
unsigned int prm_lk_rollback_on_lock_escalation_flag = 0 static
Definition at line 1027 of file system_parameter.c.
float PRM_LK_RUN_DEADLOCK_INTERVAL = 1.0f
Definition at line 1034 of file system_parameter.c.
float prm_lk_run_deadlock_interval_default = 1.0f static
Definition at line 1035 of file system_parameter.c.
unsigned int prm_lk_run_deadlock_interval_flag = 0 static
Definition at line 1037 of file system_parameter.c.
float prm_lk_run_deadlock_interval_lower = 0.1f static
Definition at line 1036 of file system_parameter.c.
int PRM_LK_TIMEOUT_MESSAGE_DUMP_LEVEL = 0
Definition at line 1017 of file system_parameter.c.
unsigned int prm_lk_timeout_message_dump_level_flag = 0 static
Definition at line 1018 of file system_parameter.c.
int PRM_LK_TIMEOUT_SECS = -1
Definition at line 1029 of file system_parameter.c.
int prm_lk_timeout_secs_default = -1 static
Definition at line 1030 of file system_parameter.c.
unsigned int prm_lk_timeout_secs_flag = 0 static
Definition at line 1032 of file system_parameter.c.
int prm_lk_timeout_secs_lower = -1 static
Definition at line 1031 of file system_parameter.c.
int PRM_LOADDB_FLUSH_INTERVAL = 1000
Definition at line 1717 of file system_parameter.c.
int prm_loaddb_flush_interval_default = 1000 static
Definition at line 1718 of file system_parameter.c.
unsigned int prm_loaddb_flush_interval_flag = 0 static
Definition at line 1720 of file system_parameter.c.
int prm_loaddb_flush_interval_lower = 0 static
Definition at line 1719 of file system_parameter.c.
int PRM_LOADDB_WORKERS = 8
Definition at line 2271 of file system_parameter.c.
int prm_loaddb_workers_default = 8 static
Definition at line 2272 of file system_parameter.c.
unsigned int prm_loaddb_workers_flag = 0 static
Definition at line 2275 of file system_parameter.c.
int prm_loaddb_workers_lower = 2 static
Definition at line 2274 of file system_parameter.c.
int prm_loaddb_workers_upper = 64 static
Definition at line 2273 of file system_parameter.c.
bool PRM_LOG_ASYNC_COMMIT = false
Definition at line 1608 of file system_parameter.c.
bool prm_log_async_commit_default = false static
Definition at line 1609 of file system_parameter.c.
unsigned int prm_log_async_commit_flag = 0 static
Definition at line 1610 of file system_parameter.c.
bool PRM_LOG_BACKGROUND_ARCHIVING = true
Definition at line 1062 of file system_parameter.c.
bool prm_log_background_archiving_default = true static
Definition at line 1063 of file system_parameter.c.
unsigned int prm_log_background_archiving_flag = 0 static
Definition at line 1064 of file system_parameter.c.
unsigned int prm_log_bg_flush_interval_msecs_flag = 0 static
Definition at line 1617 of file system_parameter.c.
unsigned int prm_log_bg_flush_num_pages_flag = 0 static
Definition at line 1619 of file system_parameter.c.
bool PRM_LOG_BTREE_OPS = false
Definition at line 2024 of file system_parameter.c.
bool prm_log_btree_ops_default = false static
Definition at line 2025 of file system_parameter.c.
unsigned int prm_log_btree_ops_flag = 0 static
Definition at line 2026 of file system_parameter.c.
int PRM_LOG_CHECKPOINT_INTERVAL_SECS = 360
Definition at line 1052 of file system_parameter.c.
int prm_log_checkpoint_interval_secs_default = 360 static
Definition at line 1053 of file system_parameter.c.
unsigned int prm_log_checkpoint_interval_secs_flag = 0 static
Definition at line 1055 of file system_parameter.c.
int prm_log_checkpoint_interval_secs_lower = 60 static
Definition at line 1054 of file system_parameter.c.
int PRM_LOG_CHECKPOINT_NPAGES = 100000
Definition at line 1047 of file system_parameter.c.
int prm_log_checkpoint_npages_default = 100000 static
Definition at line 1048 of file system_parameter.c.
unsigned int prm_log_checkpoint_npages_flag = 0 static
Definition at line 1050 of file system_parameter.c.
int prm_log_checkpoint_npages_lower = 10 static
Definition at line 1049 of file system_parameter.c.
int PRM_LOG_CHECKPOINT_SLEEP_MSECS = 1
Definition at line 1057 of file system_parameter.c.
int prm_log_checkpoint_sleep_msecs_default = 1 static
Definition at line 1058 of file system_parameter.c.
unsigned int prm_log_checkpoint_sleep_msecs_flag = 0 static
Definition at line 1060 of file system_parameter.c.
int prm_log_checkpoint_sleep_msecs_lower = 0 static
Definition at line 1059 of file system_parameter.c.
bool PRM_LOG_CHKPT_DETAILED = false
Definition at line 2257 of file system_parameter.c.
bool prm_log_chkpt_detailed_default = false static
Definition at line 2258 of file system_parameter.c.
unsigned int prm_log_chkpt_detailed_flag = 0 static
Definition at line 2259 of file system_parameter.c.
bool PRM_LOG_COMPRESS = true
Definition at line 1625 of file system_parameter.c.
bool prm_log_compress_default = true static
Definition at line 1626 of file system_parameter.c.
unsigned int prm_log_compress_flag = 0 static
Definition at line 1627 of file system_parameter.c.
int PRM_LOG_GROUP_COMMIT_INTERVAL_MSECS = 0
Definition at line 1612 of file system_parameter.c.
int prm_log_group_commit_interval_msecs_default = 0 static
Definition at line 1613 of file system_parameter.c.
unsigned int prm_log_group_commit_interval_msecs_flag = 0 static
Definition at line 1615 of file system_parameter.c.
int prm_log_group_commit_interval_msecs_lower = 0 static
Definition at line 1614 of file system_parameter.c.
unsigned int prm_log_header_flush_interval_flag = 0 static
Definition at line 1606 of file system_parameter.c.
int PRM_LOG_ISOLATION_LEVEL = TRAN_READ_COMMITTED
Definition at line 1066 of file system_parameter.c.
int prm_log_isolation_level_default = TRAN_READ_COMMITTED static
Definition at line 1067 of file system_parameter.c.
unsigned int prm_log_isolation_level_flag = 0 static
Definition at line 1070 of file system_parameter.c.
int prm_log_isolation_level_lower = TRAN_READ_COMMITTED static
Definition at line 1068 of file system_parameter.c.
int prm_log_isolation_level_upper = TRAN_SERIALIZABLE static
Definition at line 1069 of file system_parameter.c.
int PRM_LOG_MAX_ARCHIVES = INT_MAX
Definition at line 1690 of file system_parameter.c.
int prm_log_max_archives_default = INT_MAX static
Definition at line 1691 of file system_parameter.c.
unsigned int prm_log_max_archives_flag = 0 static
Definition at line 1693 of file system_parameter.c.
int prm_log_max_archives_lower = 0 static
Definition at line 1692 of file system_parameter.c.
unsigned int prm_log_media_failure_support_flag = 0 static
Definition at line 1072 of file system_parameter.c.
int PRM_LOG_NBUFFERS = LOGPB_BUFFER_NPAGES_LOWER
Definition at line 1042 of file system_parameter.c.
int prm_log_nbuffers_default = 16 * ONE_K static
Definition at line 1043 of file system_parameter.c.
unsigned int prm_log_nbuffers_flag = 0 static
Definition at line 1045 of file system_parameter.c.
int prm_log_nbuffers_lower = LOGPB_BUFFER_NPAGES_LOWER static
Definition at line 1044 of file system_parameter.c.
bool PRM_LOG_NO_LOGGING = false
Definition at line 1704 of file system_parameter.c.
bool prm_log_no_logging_default = false static
Definition at line 1705 of file system_parameter.c.
unsigned int prm_log_no_logging_flag = 0 static
Definition at line 1706 of file system_parameter.c.
bool PRM_LOG_PGBUF_VICTIM_FLUSH = false
Definition at line 2253 of file system_parameter.c.
bool prm_log_pgbuf_victim_flush_default = false static
Definition at line 2254 of file system_parameter.c.
unsigned int prm_log_pgbuf_victim_flush_flag = 0 static
Definition at line 2255 of file system_parameter.c.
bool PRM_LOG_QUERY_LISTS = false
Definition at line 2175 of file system_parameter.c.
bool prm_log_query_lists_default = false static
Definition at line 2176 of file system_parameter.c.
unsigned int prm_log_query_lists_flag = 0 static
Definition at line 2177 of file system_parameter.c.
bool PRM_LOG_SWEEP_CLEAN = true
Definition at line 1087 of file system_parameter.c.
bool prm_log_sweep_clean_default = true static
Definition at line 1088 of file system_parameter.c.
unsigned int prm_log_sweep_clean_flag = 0 static
Definition at line 1089 of file system_parameter.c.
bool PRM_LOG_TRACE_DEBUG = false
Definition at line 1649 of file system_parameter.c.
bool prm_log_trace_debug_default = false static
Definition at line 1650 of file system_parameter.c.
unsigned int prm_log_trace_debug_flag = 0 static
Definition at line 1651 of file system_parameter.c.
int PRM_LOG_TRACE_FLUSH_TIME_MSECS = 0
Definition at line 1835 of file system_parameter.c.
int prm_log_trace_flush_time_msecs_default = 0 static
Definition at line 1836 of file system_parameter.c.
unsigned int prm_log_trace_flush_time_msecs_flag = 0 static
Definition at line 1838 of file system_parameter.c.
int prm_log_trace_flush_time_msecs_lower = 0 static
Definition at line 1837 of file system_parameter.c.
bool PRM_LOG_UNIQUE_STATS = false
Definition at line 2105 of file system_parameter.c.
bool prm_log_unique_stats_default = false static
Definition at line 2106 of file system_parameter.c.
unsigned int prm_log_unique_stats_flag = 0 static
Definition at line 2107 of file system_parameter.c.
UINT64 PRM_LOG_VOLUME_SIZE = 536870912ULL
Definition at line 1789 of file system_parameter.c.
UINT64 prm_log_volume_size_default = 536870912ULL static
Definition at line 1790 of file system_parameter.c.
unsigned int prm_log_volume_size_flag = 0 static
Definition at line 1793 of file system_parameter.c.
UINT64 prm_log_volume_size_lower = 20971520ULL static
Definition at line 1791 of file system_parameter.c.
UINT64 prm_log_volume_size_upper = 4294967296ULL static
Definition at line 1792 of file system_parameter.c.
bool PRM_LOGPB_LOGGING_DEBUG = false
Definition at line 2109 of file system_parameter.c.
bool prm_logpb_logging_debug_default = false static
Definition at line 2110 of file system_parameter.c.
unsigned int prm_logpb_logging_debug_flag = 0 static
Definition at line 2111 of file system_parameter.c.
UINT64 PRM_MAX_AGG_HASH_SIZE = 2 * 1024 * 1024
Definition at line 1869 of file system_parameter.c.
UINT64 prm_max_agg_hash_size_default = 2 * 1024 * 1024 static
Definition at line 1870 of file system_parameter.c.
unsigned int prm_max_agg_hash_size_flag = 0 static
Definition at line 1873 of file system_parameter.c.
UINT64 prm_max_agg_hash_size_lower = 32 * 1024 static
Definition at line 1871 of file system_parameter.c.
UINT64 prm_max_agg_hash_size_upper = 128 * 1024 * 1024 static
Definition at line 1872 of file system_parameter.c.
int PRM_MAX_ENTRIES_IN_TEMP_FILE_CACHE = 512
Definition at line 1167 of file system_parameter.c.
int prm_max_entries_in_temp_file_cache_default = 512 static
Definition at line 1168 of file system_parameter.c.
unsigned int prm_max_entries_in_temp_file_cache_flag = 0 static
Definition at line 1170 of file system_parameter.c.
int prm_max_entries_in_temp_file_cache_lower = 10 static
Definition at line 1169 of file system_parameter.c.
int PRM_MAX_FLUSH_PAGES_PER_SECOND = 10000
Definition at line 1230 of file system_parameter.c.
int prm_max_flush_pages_per_second_default = 10000 static
Definition at line 1231 of file system_parameter.c.
unsigned int prm_max_flush_pages_per_second_flag = 0 static
Definition at line 1234 of file system_parameter.c.
int prm_max_flush_pages_per_second_lower = 1 static
Definition at line 1232 of file system_parameter.c.
int prm_max_flush_pages_per_second_upper = INT_MAX static
Definition at line 1233 of file system_parameter.c.
UINT64 PRM_MAX_HASH_LIST_SCAN_SIZE = 4 * 1024 * 1024
Definition at line 1897 of file system_parameter.c.
UINT64 prm_max_hash_list_scan_size_default = 4 * 1024 * 1024 static
Definition at line 1898 of file system_parameter.c.
unsigned int prm_max_hash_list_scan_size_flag = 0 static
Definition at line 1901 of file system_parameter.c.
UINT64 prm_max_hash_list_scan_size_lower = 0 static
Definition at line 1899 of file system_parameter.c.
UINT64 prm_max_hash_list_scan_size_upper = 128 * 1024 * 1024 static
Definition at line 1900 of file system_parameter.c.
int PRM_MAX_OUTER_CARD_OF_IDXJOIN = 0
Definition at line 1341 of file system_parameter.c.
int prm_max_outer_card_of_idxjoin_default = 0 static
Definition at line 1342 of file system_parameter.c.
unsigned int prm_max_outer_card_of_idxjoin_flag = 0 static
Definition at line 1344 of file system_parameter.c.
int prm_max_outer_card_of_idxjoin_lower = 0 static
Definition at line 1343 of file system_parameter.c.
int PRM_MAX_PAGES_IN_TEMP_FILE_CACHE = 1000
Definition at line 1162 of file system_parameter.c.
int prm_max_pages_in_temp_file_cache_default = 1000 static
Definition at line 1163 of file system_parameter.c.
unsigned int prm_max_pages_in_temp_file_cache_flag = 0 static
Definition at line 1165 of file system_parameter.c.
int prm_max_pages_in_temp_file_cache_lower = 100 static
Definition at line 1164 of file system_parameter.c.
int PRM_MAX_RECURSION_SQL_DEPTH = 400
Definition at line 1865 of file system_parameter.c.
int prm_max_recursion_sql_depth_default = 400 static
Definition at line 1866 of file system_parameter.c.
unsigned int prm_max_recursion_sql_depth_flag = 0 static
Definition at line 1867 of file system_parameter.c.
int* PRM_MNT_STATS_THRESHOLD = int_list_initial
Definition at line 1759 of file system_parameter.c.
int* prm_mnt_stats_threshold_default = NULL static
Definition at line 1760 of file system_parameter.c.
unsigned int prm_mnt_stats_threshold_flag = 0 static
Definition at line 1761 of file system_parameter.c.
int PRM_MNT_WAITING_THREAD = 0
Definition at line 1754 of file system_parameter.c.
int prm_mnt_waiting_thread_default = 0 static
Definition at line 1755 of file system_parameter.c.
unsigned int prm_mnt_waiting_thread_flag = 0 static
Definition at line 1757 of file system_parameter.c.
int prm_mnt_waiting_thread_lower = 0 static
Definition at line 1756 of file system_parameter.c.
int PRM_MULTI_RANGE_OPT_LIMIT = 100
Definition at line 1777 of file system_parameter.c.
int prm_multi_range_opt_limit_default = 100 static
Definition at line 1778 of file system_parameter.c.
unsigned int prm_multi_range_opt_limit_flag = 0 static
Definition at line 1781 of file system_parameter.c.
int prm_multi_range_opt_limit_lower = 0 static
Definition at line 1779 of file system_parameter.c.
int prm_multi_range_opt_limit_upper = 10000 static
Definition at line 1780 of file system_parameter.c.
int PRM_MUTEX_BUSY_WAITING_CNT = 0
Definition at line 1211 of file system_parameter.c.
int prm_mutex_busy_waiting_cnt_default = 0 static
Definition at line 1212 of file system_parameter.c.
unsigned int prm_mutex_busy_waiting_cnt_flag = 0 static
Definition at line 1213 of file system_parameter.c.
bool PRM_MYSQL_TRIGGER_CORRELATION_NAMES = false
Definition at line 1291 of file system_parameter.c.
bool prm_mysql_trigger_correlation_names_default = false static
Definition at line 1292 of file system_parameter.c.
unsigned int prm_mysql_trigger_correlation_names_flag = 0 static
Definition at line 1293 of file system_parameter.c.
bool PRM_NEW_LFHASH = false
Definition at line 2285 of file system_parameter.c.
bool prm_new_lfhash_default = false static
Definition at line 2286 of file system_parameter.c.
unsigned int prm_new_lfhash_flag = 0 static
Definition at line 2287 of file system_parameter.c.
bool PRM_NO_BACKSLASH_ESCAPES = true
Definition at line 1299 of file system_parameter.c.
bool prm_no_backslash_escapes_default = true static
Definition at line 1300 of file system_parameter.c.
unsigned int prm_no_backslash_escapes_flag = 0 static
Definition at line 1301 of file system_parameter.c.
bool PRM_OBJECT_PRINT_FORMAT_OID = false
Definition at line 2028 of file system_parameter.c.
bool prm_object_print_format_oid_default = false static
Definition at line 2029 of file system_parameter.c.
unsigned int prm_object_print_format_oid_flag = 0 static
Definition at line 2030 of file system_parameter.c.
bool PRM_ONLY_FULL_GROUP_BY = false
Definition at line 1283 of file system_parameter.c.
bool prm_only_full_group_by_default = false static
Definition at line 1284 of file system_parameter.c.
unsigned int prm_only_full_group_by_flag = 0 static
Definition at line 1285 of file system_parameter.c.
int PRM_OPTIMIZATION_LEVEL = 1
Definition at line 1115 of file system_parameter.c.
int prm_optimization_level_default = 1 static
Definition at line 1116 of file system_parameter.c.
unsigned int prm_optimization_level_flag = 0 static
Definition at line 1117 of file system_parameter.c.
bool PRM_OPTIMIZER_ENABLE_AGGREGATE_OPTIMIZATION = true
Definition at line 2044 of file system_parameter.c.
bool prm_optimizer_enable_aggregate_optimization_default = true static
Definition at line 2045 of file system_parameter.c.
unsigned int prm_optimizer_enable_aggregate_optimization_flag = 0 static
Definition at line 2046 of file system_parameter.c.
bool PRM_OPTIMIZER_ENABLE_MERGE_JOIN = false
Definition at line 1893 of file system_parameter.c.
bool prm_optimizer_enable_merge_join_default = false static
Definition at line 1894 of file system_parameter.c.
unsigned int prm_optimizer_enable_merge_join_flag = 0 static
Definition at line 1895 of file system_parameter.c.
bool PRM_OPTIMIZER_RESERVE_02 = false
Definition at line 1903 of file system_parameter.c.
bool prm_optimizer_reserve_02_default = false static
Definition at line 1904 of file system_parameter.c.
unsigned int prm_optimizer_reserve_02_flag = 0 static
Definition at line 1905 of file system_parameter.c.
bool PRM_OPTIMIZER_RESERVE_03 = false
Definition at line 1907 of file system_parameter.c.
bool prm_optimizer_reserve_03_default = false static
Definition at line 1908 of file system_parameter.c.
unsigned int prm_optimizer_reserve_03_flag = 0 static
Definition at line 1909 of file system_parameter.c.
bool PRM_OPTIMIZER_RESERVE_04 = false
Definition at line 1911 of file system_parameter.c.
bool prm_optimizer_reserve_04_default = false static
Definition at line 1912 of file system_parameter.c.
unsigned int prm_optimizer_reserve_04_flag = 0 static
Definition at line 1913 of file system_parameter.c.
bool PRM_OPTIMIZER_RESERVE_05 = false
Definition at line 1915 of file system_parameter.c.
bool prm_optimizer_reserve_05_default = false static
Definition at line 1916 of file system_parameter.c.
unsigned int prm_optimizer_reserve_05_flag = 0 static
Definition at line 1917 of file system_parameter.c.
bool PRM_OPTIMIZER_RESERVE_06 = false
Definition at line 1919 of file system_parameter.c.
bool prm_optimizer_reserve_06_default = false static
Definition at line 1920 of file system_parameter.c.
unsigned int prm_optimizer_reserve_06_flag = 0 static
Definition at line 1921 of file system_parameter.c.
bool PRM_OPTIMIZER_RESERVE_07 = false
Definition at line 1923 of file system_parameter.c.
bool prm_optimizer_reserve_07_default = false static
Definition at line 1924 of file system_parameter.c.
unsigned int prm_optimizer_reserve_07_flag = 0 static
Definition at line 1925 of file system_parameter.c.
bool PRM_OPTIMIZER_RESERVE_08 = false
Definition at line 1927 of file system_parameter.c.
bool prm_optimizer_reserve_08_default = false static
Definition at line 1928 of file system_parameter.c.
unsigned int prm_optimizer_reserve_08_flag = 0 static
Definition at line 1929 of file system_parameter.c.
bool PRM_OPTIMIZER_RESERVE_09 = false
Definition at line 1931 of file system_parameter.c.
bool prm_optimizer_reserve_09_default = false static
Definition at line 1932 of file system_parameter.c.
unsigned int prm_optimizer_reserve_09_flag = 0 static
Definition at line 1933 of file system_parameter.c.
bool PRM_OPTIMIZER_RESERVE_10 = false
Definition at line 1935 of file system_parameter.c.
bool prm_optimizer_reserve_10_default = false static
Definition at line 1936 of file system_parameter.c.
unsigned int prm_optimizer_reserve_10_flag = 0 static
Definition at line 1937 of file system_parameter.c.
bool PRM_OPTIMIZER_RESERVE_11 = false
Definition at line 1939 of file system_parameter.c.
bool prm_optimizer_reserve_11_default = false static
Definition at line 1940 of file system_parameter.c.
unsigned int prm_optimizer_reserve_11_flag = 0 static
Definition at line 1941 of file system_parameter.c.
bool PRM_OPTIMIZER_RESERVE_12 = false
Definition at line 1943 of file system_parameter.c.
bool prm_optimizer_reserve_12_default = false static
Definition at line 1944 of file system_parameter.c.
unsigned int prm_optimizer_reserve_12_flag = 0 static
Definition at line 1945 of file system_parameter.c.
bool PRM_OPTIMIZER_RESERVE_13 = false
Definition at line 1947 of file system_parameter.c.
bool prm_optimizer_reserve_13_default = false static
Definition at line 1948 of file system_parameter.c.
unsigned int prm_optimizer_reserve_13_flag = 0 static
Definition at line 1949 of file system_parameter.c.
bool PRM_OPTIMIZER_RESERVE_14 = false
Definition at line 1951 of file system_parameter.c.
bool prm_optimizer_reserve_14_default = false static
Definition at line 1952 of file system_parameter.c.
unsigned int prm_optimizer_reserve_14_flag = 0 static
Definition at line 1953 of file system_parameter.c.
bool PRM_OPTIMIZER_RESERVE_15 = false
Definition at line 1955 of file system_parameter.c.
bool prm_optimizer_reserve_15_default = false static
Definition at line 1956 of file system_parameter.c.
unsigned int prm_optimizer_reserve_15_flag = 0 static
Definition at line 1957 of file system_parameter.c.
bool PRM_OPTIMIZER_RESERVE_16 = false
Definition at line 1959 of file system_parameter.c.
bool prm_optimizer_reserve_16_default = false static
Definition at line 1960 of file system_parameter.c.
unsigned int prm_optimizer_reserve_16_flag = 0 static
Definition at line 1961 of file system_parameter.c.
bool PRM_OPTIMIZER_RESERVE_17 = false
Definition at line 1963 of file system_parameter.c.
bool prm_optimizer_reserve_17_default = false static
Definition at line 1964 of file system_parameter.c.
unsigned int prm_optimizer_reserve_17_flag = 0 static
Definition at line 1965 of file system_parameter.c.
bool PRM_OPTIMIZER_RESERVE_18 = false
Definition at line 1967 of file system_parameter.c.
bool prm_optimizer_reserve_18_default = false static
Definition at line 1968 of file system_parameter.c.
unsigned int prm_optimizer_reserve_18_flag = 0 static
Definition at line 1969 of file system_parameter.c.
bool PRM_OPTIMIZER_RESERVE_19 = false
Definition at line 1971 of file system_parameter.c.
bool prm_optimizer_reserve_19_default = false static
Definition at line 1972 of file system_parameter.c.
unsigned int prm_optimizer_reserve_19_flag = 0 static
Definition at line 1973 of file system_parameter.c.
bool PRM_OPTIMIZER_RESERVE_20 = false
Definition at line 1975 of file system_parameter.c.
bool prm_optimizer_reserve_20_default = false static
Definition at line 1976 of file system_parameter.c.
unsigned int prm_optimizer_reserve_20_flag = 0 static
Definition at line 1977 of file system_parameter.c.
bool PRM_ORACLE_STYLE_EMPTY_STRING = false
Definition at line 1346 of file system_parameter.c.
bool prm_oracle_style_empty_string_default = false static
Definition at line 1347 of file system_parameter.c.
unsigned int prm_oracle_style_empty_string_flag = 0 static
Definition at line 1348 of file system_parameter.c.
bool PRM_ORACLE_STYLE_OUTERJOIN = false
Definition at line 1259 of file system_parameter.c.
bool prm_oracle_style_outerjoin_default = false static
Definition at line 1260 of file system_parameter.c.
unsigned int prm_oracle_style_outerjoin_flag = 0 static
Definition at line 1261 of file system_parameter.c.
int PRM_PAGE_BG_FLUSH_INTERVAL_MSEC = 1000
Definition at line 1221 of file system_parameter.c.
int prm_page_bg_flush_interval_msec_default = 1000 static
Definition at line 1222 of file system_parameter.c.
unsigned int prm_page_bg_flush_interval_msec_flag = 0 static
Definition at line 1224 of file system_parameter.c.
int prm_page_bg_flush_interval_msec_lower = -1 static
Definition at line 1223 of file system_parameter.c.
float PRM_PB_AOUT_RATIO = 0.0f
Definition at line 1887 of file system_parameter.c.
float prm_pb_aout_ratio_default = 0.0f static
Definition at line 1888 of file system_parameter.c.
unsigned int prm_pb_aout_ratio_flag = 0 static
Definition at line 1891 of file system_parameter.c.
float prm_pb_aout_ratio_lower = 0 static
Definition at line 1890 of file system_parameter.c.
float prm_pb_aout_ratio_upper = 3.0 static
Definition at line 1889 of file system_parameter.c.
float PRM_PB_BUFFER_FLUSH_RATIO = 0.01f
Definition at line 981 of file system_parameter.c.
float prm_pb_buffer_flush_ratio_default = 0.01f static
Definition at line 982 of file system_parameter.c.
unsigned int prm_pb_buffer_flush_ratio_flag = 0 static
Definition at line 985 of file system_parameter.c.
float prm_pb_buffer_flush_ratio_lower = 0.01f static
Definition at line 983 of file system_parameter.c.
float prm_pb_buffer_flush_ratio_upper = 0.95f static
Definition at line 984 of file system_parameter.c.
int PRM_PB_DEBUG_PAGE_VALIDATION_LEVEL = PGBUF_DEBUG_NO_PAGE_VALIDATION
Definition at line 1251 of file system_parameter.c.
int prm_pb_debug_page_validation_level_default = PGBUF_DEBUG_PAGE_VALIDATION_FETCH static
Definition at line 1253 of file system_parameter.c.
unsigned int prm_pb_debug_page_validation_level_flag = 0 static
Definition at line 1257 of file system_parameter.c.
float PRM_PB_LRU_BUFFER_RATIO = 0.05f
Definition at line 1989 of file system_parameter.c.
float prm_pb_lru_buffer_ratio_default = 0.05f static
Definition at line 1990 of file system_parameter.c.
unsigned int prm_pb_lru_buffer_ratio_flag = 0 static
Definition at line 1993 of file system_parameter.c.
float prm_pb_lru_buffer_ratio_lower = 0.05f static
Definition at line 1992 of file system_parameter.c.
float prm_pb_lru_buffer_ratio_upper = 0.90f static
Definition at line 1991 of file system_parameter.c.
float PRM_PB_LRU_HOT_RATIO = 0.4f
Definition at line 1983 of file system_parameter.c.
float prm_pb_lru_hot_ratio_default = 0.4f static
Definition at line 1984 of file system_parameter.c.
unsigned int prm_pb_lru_hot_ratio_flag = 0 static
Definition at line 1987 of file system_parameter.c.
float prm_pb_lru_hot_ratio_lower = 0.05f static
Definition at line 1986 of file system_parameter.c.
float prm_pb_lru_hot_ratio_upper = 0.90f static
Definition at line 1985 of file system_parameter.c.
bool PRM_PB_MONITOR_LOCKS = false
Definition at line 2147 of file system_parameter.c.
bool prm_pb_monitor_locks_default = false static
Definition at line 2148 of file system_parameter.c.
unsigned int prm_pb_monitor_locks_flag = 0 static
Definition at line 2149 of file system_parameter.c.
int PRM_PB_NBUFFERS = 32768
Definition at line 976 of file system_parameter.c.
int prm_pb_nbuffers_default = 32768 static
Definition at line 977 of file system_parameter.c.
unsigned int prm_pb_nbuffers_flag = 0 static
Definition at line 979 of file system_parameter.c.
int prm_pb_nbuffers_lower = 1024 static
Definition at line 978 of file system_parameter.c.
bool PRM_PB_NEIGHBOR_FLUSH_NONDIRTY = false
Definition at line 2051 of file system_parameter.c.
bool prm_pb_neighbor_flush_nondirty_default = false static
Definition at line 2053 of file system_parameter.c.
unsigned int prm_pb_neighbor_flush_nondirty_flag = 0 static
Definition at line 2052 of file system_parameter.c.
unsigned int PRM_PB_NEIGHBOR_FLUSH_PAGES = 8
Definition at line 2055 of file system_parameter.c.
unsigned int prm_pb_neighbor_flush_pages_default = 8 static
Definition at line 2057 of file system_parameter.c.
unsigned int prm_pb_neighbor_flush_pages_flag = 0 static
Definition at line 2056 of file system_parameter.c.
unsigned int prm_pb_neighbor_flush_pages_lower = 0 static
Definition at line 2059 of file system_parameter.c.
unsigned int prm_pb_neighbor_flush_pages_upper = 32 static
Definition at line 2058 of file system_parameter.c.
int PRM_PB_NUM_LRU_CHAINS = 0
Definition at line 1215 of file system_parameter.c.
int prm_pb_num_LRU_chains_default = 0 static
Definition at line 1216 of file system_parameter.c.
unsigned int prm_pb_num_LRU_chains_flag = 0 static
Definition at line 1219 of file system_parameter.c.
int prm_pb_num_LRU_chains_lower = 0 static
Definition at line 1217 of file system_parameter.c.
int prm_pb_num_LRU_chains_upper = 1000 static
Definition at line 1218 of file system_parameter.c.
int PRM_PB_NUM_PRIVATE_CHAINS = -1
Definition at line 2141 of file system_parameter.c.
int prm_pb_num_private_chains_default = -1 static
Definition at line 2142 of file system_parameter.c.
unsigned int prm_pb_num_private_chains_flag = 0 static
Definition at line 2145 of file system_parameter.c.
int prm_pb_num_private_chains_lower = -1 static
Definition at line 2144 of file system_parameter.c.
int prm_pb_num_private_chains_upper = CSS_MAX_CLIENT_COUNT + VACUUM_MAX_WORKER_COUNT static
Definition at line 2143 of file system_parameter.c.
bool PRM_PB_SEQUENTIAL_VICTIM_FLUSH = true
Definition at line 2101 of file system_parameter.c.
bool prm_pb_sequential_victim_flush_default = true static
Definition at line 2102 of file system_parameter.c.
unsigned int prm_pb_sequential_victim_flush_flag = 0 static
Definition at line 2103 of file system_parameter.c.
int PRM_PB_SYNC_ON_NFLUSH = 200
Definition at line 1236 of file system_parameter.c.
int prm_pb_sync_on_nflush_default = 200 static
Definition at line 1237 of file system_parameter.c.
unsigned int prm_pb_sync_on_nflush_flag = 0 static
Definition at line 1240 of file system_parameter.c.
int prm_pb_sync_on_nflush_lower = 1 static
Definition at line 1238 of file system_parameter.c.
int prm_pb_sync_on_nflush_upper = INT_MAX static
Definition at line 1239 of file system_parameter.c.
bool PRM_PERF_TEST_MODE = false
Definition at line 2277 of file system_parameter.c.
bool prm_perf_test_mode_default = false static
Definition at line 2278 of file system_parameter.c.
unsigned int prm_perf_test_mode_flag = 0 static
Definition at line 2279 of file system_parameter.c.
bool PRM_PIPES_AS_CONCAT = true
Definition at line 1287 of file system_parameter.c.
bool prm_pipes_as_concat_default = true static
Definition at line 1288 of file system_parameter.c.
unsigned int prm_pipes_as_concat_flag = 0 static
Definition at line 1289 of file system_parameter.c.
bool PRM_PLUS_AS_CONCAT = true
Definition at line 1327 of file system_parameter.c.
bool prm_plus_as_concat_default = true static
Definition at line 1328 of file system_parameter.c.
unsigned int prm_plus_as_concat_flag = 0 static
Definition at line 1329 of file system_parameter.c.
bool PRM_POSTPONE_DEBUG = false
Definition at line 2089 of file system_parameter.c.
const bool prm_postpone_debug_default = false static
Definition at line 2090 of file system_parameter.c.
unsigned int prm_postpone_debug_flag = 0 static
Definition at line 2091 of file system_parameter.c.
bool PRM_PTHREAD_SCOPE_PROCESS = true
Definition at line 1172 of file system_parameter.c.
bool prm_pthread_scope_process_default = true static
Definition at line 1173 of file system_parameter.c.
unsigned int prm_pthread_scope_process_flag = 0 static
Definition at line 1174 of file system_parameter.c.
bool PRM_QO_DUMP = false
Definition at line 1119 of file system_parameter.c.
bool prm_qo_dump_default = false static
Definition at line 1120 of file system_parameter.c.
unsigned int prm_qo_dump_flag = 0 static
Definition at line 1121 of file system_parameter.c.
bool PRM_QUERY_TRACE = false
Definition at line 1855 of file system_parameter.c.
bool prm_query_trace_default = false static
Definition at line 1856 of file system_parameter.c.
unsigned int prm_query_trace_flag = 0 static
Definition at line 1857 of file system_parameter.c.
int PRM_QUERY_TRACE_FORMAT = QUERY_TRACE_TEXT
Definition at line 1859 of file system_parameter.c.
int prm_query_trace_format_default = QUERY_TRACE_TEXT static
Definition at line 1860 of file system_parameter.c.
unsigned int prm_query_trace_format_flag = 0 static
Definition at line 1863 of file system_parameter.c.
int prm_query_trace_format_lower = QUERY_TRACE_TEXT static
Definition at line 1861 of file system_parameter.c.
int prm_query_trace_format_upper = QUERY_TRACE_JSON static
Definition at line 1862 of file system_parameter.c.
bool PRM_READ_ONLY_MODE = false
Definition at line 1750 of file system_parameter.c.
bool prm_read_only_mode_default = false static
Definition at line 1751 of file system_parameter.c.
unsigned int prm_read_only_mode_flag = 0 static
Definition at line 1752 of file system_parameter.c.
int PRM_REMOVE_LOG_ARCHIVES_INTERVAL = 0
Definition at line 1699 of file system_parameter.c.
int prm_remove_log_archives_interval_default = 0 static
Definition at line 1700 of file system_parameter.c.
unsigned int prm_remove_log_archives_interval_flag = 0 static
Definition at line 1702 of file system_parameter.c.
int prm_remove_log_archives_interval_lower = 0 static
Definition at line 1701 of file system_parameter.c.
unsigned int prm_replication_mode_flag = 0 static
Definition at line 1428 of file system_parameter.c.
bool PRM_REPR_CACHE_LOG = false
Definition at line 2281 of file system_parameter.c.
bool prm_repr_cache_log_default = false static
Definition at line 2282 of file system_parameter.c.
unsigned int prm_repr_cache_log_flag = 0 static
Definition at line 2283 of file system_parameter.c.
bool PRM_REQUIRE_LIKE_ESCAPE_CHARACTER = false
Definition at line 1295 of file system_parameter.c.
bool prm_require_like_escape_character_default = false static
Definition at line 1296 of file system_parameter.c.
unsigned int prm_require_like_escape_character_flag = 0 static
Definition at line 1297 of file system_parameter.c.
int PRM_RESET_TR_PARSER = 10
Definition at line 1142 of file system_parameter.c.
int prm_reset_tr_parser_default = 10 static
Definition at line 1143 of file system_parameter.c.
unsigned int prm_reset_tr_parser_flag = 0 static
Definition at line 1144 of file system_parameter.c.
bool PRM_RETURN_NULL_ON_FUNCTION_ERRORS = false
Definition at line 1319 of file system_parameter.c.
bool prm_return_null_on_function_errors_default = false static
Definition at line 1320 of file system_parameter.c.
unsigned int prm_return_null_on_function_errors_flag = 0 static
Definition at line 1321 of file system_parameter.c.
char* PRM_SERVER_TIMEZONE = NULL
Definition at line 2036 of file system_parameter.c.
char* prm_server_timezone_default = NULL static
Definition at line 2037 of file system_parameter.c.
unsigned int prm_server_timezone_flag = 0 static
Definition at line 2038 of file system_parameter.c.
const char* PRM_SERVICE_SERVER_LIST = ""
Definition at line 1767 of file system_parameter.c.
const char* prm_service_server_list_default = NULL static
Definition at line 1768 of file system_parameter.c.
unsigned int prm_service_server_list_flag = 0 static
Definition at line 1769 of file system_parameter.c.
const char* PRM_SERVICE_SERVICE_LIST = ""
Definition at line 1763 of file system_parameter.c.
const char* prm_service_service_list_default = NULL static
Definition at line 1764 of file system_parameter.c.
unsigned int prm_service_service_list_flag = 0 static
Definition at line 1765 of file system_parameter.c.
int PRM_SESSION_STATE_TIMEOUT = 60 * 60 * 6
Definition at line 1771 of file system_parameter.c.
int prm_session_timeout_default = 60 * 60 * 6 static
Definition at line 1772 of file system_parameter.c.
unsigned int prm_session_timeout_flag = 0 static
Definition at line 1775 of file system_parameter.c.
int prm_session_timeout_lower = 60 static
Definition at line 1773 of file system_parameter.c.
int prm_session_timeout_upper = 60 * 60 * 24 * 365 static
Definition at line 1774 of file system_parameter.c.
int PRM_SHUTDOWN_WAIT_TIME_IN_SECS = 600
Definition at line 1078 of file system_parameter.c.
int prm_shutdown_wait_time_in_secs_default = 600 static
Definition at line 1079 of file system_parameter.c.
unsigned int prm_shutdown_wait_time_in_secs_flag = 0 static
Definition at line 1081 of file system_parameter.c.
int prm_shutdown_wait_time_in_secs_lower = 60 static
Definition at line 1080 of file system_parameter.c.
int PRM_SORT_LIMIT_MAX_COUNT = 1000
Definition at line 1844 of file system_parameter.c.
int prm_sort_limit_max_count_default = 1000 static
Definition at line 1845 of file system_parameter.c.
unsigned int prm_sort_limit_max_count_flag = 0 static
Definition at line 1848 of file system_parameter.c.
int prm_sort_limit_max_count_lower = 0 static
Definition at line 1846 of file system_parameter.c.
int prm_sort_limit_max_count_upper = INT_MAX static
Definition at line 1847 of file system_parameter.c.
bool PRM_SQL_TRACE_EXECUTION_PLAN = false
Definition at line 1831 of file system_parameter.c.
bool prm_sql_trace_execution_plan_default = false static
Definition at line 1832 of file system_parameter.c.
unsigned int prm_sql_trace_execution_plan_flag = 0 static
Definition at line 1833 of file system_parameter.c.
int PRM_SQL_TRACE_IOREADS = 0
Definition at line 1850 of file system_parameter.c.
int prm_sql_trace_ioreads_default = 0 static
Definition at line 1851 of file system_parameter.c.
unsigned int prm_sql_trace_ioreads_flag = 0 static
Definition at line 1853 of file system_parameter.c.
int prm_sql_trace_ioreads_lower = 0 static
Definition at line 1852 of file system_parameter.c.
int PRM_SQL_TRACE_SLOW_MSECS = -1
Definition at line 1825 of file system_parameter.c.
int prm_sql_trace_slow_msecs_default = -1 static
Definition at line 1826 of file system_parameter.c.
unsigned int prm_sql_trace_slow_msecs_flag = 0 static
Definition at line 1829 of file system_parameter.c.
int prm_sql_trace_slow_msecs_lower = -1 static
Definition at line 1827 of file system_parameter.c.
int prm_sql_trace_slow_msecs_upper = 1000 * 60 * 60 * 24 static
Definition at line 1828 of file system_parameter.c.
int PRM_SR_NBUFFERS = 128
Definition at line 971 of file system_parameter.c.
int prm_sr_nbuffers_default = 128 static
Definition at line 972 of file system_parameter.c.
unsigned int prm_sr_nbuffers_flag = 0 static
Definition at line 974 of file system_parameter.c.
int prm_sr_nbuffers_lower = 1 static
Definition at line 973 of file system_parameter.c.
bool PRM_STATS_ON = false
Definition at line 2267 of file system_parameter.c.
bool prm_stats_on_default = false static
Definition at line 2268 of file system_parameter.c.
unsigned int prm_stats_on_flag = 0 static
Definition at line 2269 of file system_parameter.c.
UINT64 PRM_STRING_MAX_SIZE_BYTES = 1024 * 1024
Definition at line 1309 of file system_parameter.c.
UINT64 prm_string_max_size_bytes_default = 1024 * 1024 static
Definition at line 1310 of file system_parameter.c.
unsigned int prm_string_max_size_bytes_flag = 0 static
Definition at line 1313 of file system_parameter.c.
UINT64 prm_string_max_size_bytes_lower = 64 static
Definition at line 1311 of file system_parameter.c.
UINT64 prm_string_max_size_bytes_upper = 32 * 1024 * 1024 static
Definition at line 1312 of file system_parameter.c.
int PRM_SUPPRESS_FSYNC = 0
Definition at line 1350 of file system_parameter.c.
int prm_suppress_fsync_default = 0 static
Definition at line 1351 of file system_parameter.c.
unsigned int prm_suppress_fsync_flag = 0 static
Definition at line 1354 of file system_parameter.c.
int prm_suppress_fsync_lower = 0 static
Definition at line 1353 of file system_parameter.c.
int prm_suppress_fsync_upper = 100 static
Definition at line 1352 of file system_parameter.c.
bool PRM_TB_REUSE_OID = true
Definition at line 2325 of file system_parameter.c.
int PRM_TCP_CONNECTION_TIMEOUT = 5
Definition at line 1110 of file system_parameter.c.
int prm_tcp_connection_timeout_default = 5 static
Definition at line 1111 of file system_parameter.c.
unsigned int prm_tcp_connection_timeout_flag = 0 static
Definition at line 1113 of file system_parameter.c.
int prm_tcp_connection_timeout_lower = -1 static
Definition at line 1112 of file system_parameter.c.
bool PRM_TCP_KEEPALIVE = true
Definition at line 1678 of file system_parameter.c.
bool prm_tcp_keepalive_default = true static
Definition at line 1679 of file system_parameter.c.
unsigned int prm_tcp_keepalive_flag = 0 static
Definition at line 1680 of file system_parameter.c.
bool PRM_TCP_NODELAY = false
Definition at line 1674 of file system_parameter.c.
bool prm_tcp_nodelay_default = false static
Definition at line 1675 of file system_parameter.c.
unsigned int prm_tcp_nodelay_flag = 0 static
Definition at line 1676 of file system_parameter.c.
int PRM_TCP_PORT_ID = 1523
Definition at line 1104 of file system_parameter.c.
Referenced by prm_get_master_port_id().
int prm_tcp_port_id_default = 1523 static
Definition at line 1105 of file system_parameter.c.
unsigned int prm_tcp_port_id_flag = 0 static
Definition at line 1106 of file system_parameter.c.
int prm_tcp_port_id_lower = 1 static
Definition at line 1108 of file system_parameter.c.
int prm_tcp_port_id_upper = USHRT_MAX static
Definition at line 1107 of file system_parameter.c.
int PRM_TCP_RCVBUF_SIZE = -1
Definition at line 1666 of file system_parameter.c.
int prm_tcp_rcvbuf_size_default = -1 static
Definition at line 1667 of file system_parameter.c.
unsigned int prm_tcp_rcvbuf_size_flag = 0 static
Definition at line 1668 of file system_parameter.c.
int PRM_TCP_SNDBUF_SIZE = -1
Definition at line 1670 of file system_parameter.c.
int prm_tcp_sndbuf_size_default = -1 static
Definition at line 1671 of file system_parameter.c.
unsigned int prm_tcp_sndbuf_size_flag = 0 static
Definition at line 1672 of file system_parameter.c.
int PRM_TDE_DEFAULT_ALGORITHM = TDE_ALGORITHM_AES
Definition at line 2293 of file system_parameter.c.
int prm_tde_default_algorithm = TDE_ALGORITHM_AES static
Definition at line 2294 of file system_parameter.c.
unsigned int prm_tde_default_algorithm_flag = 0 static
Definition at line 2295 of file system_parameter.c.
const char* PRM_TDE_KEYS_FILE_PATH = ""
Definition at line 1726 of file system_parameter.c.
char* prm_tde_keys_file_path_default = NULL static
Definition at line 1727 of file system_parameter.c.
unsigned int prm_tde_keys_file_path_flag = 0 static
Definition at line 1728 of file system_parameter.c.
int PRM_TEMP_MEM_BUFFER_PAGES = 4
Definition at line 1176 of file system_parameter.c.
int prm_temp_mem_buffer_pages_default = 4 static
Definition at line 1177 of file system_parameter.c.
unsigned int prm_temp_mem_buffer_pages_flag = 0 static
Definition at line 1180 of file system_parameter.c.
int prm_temp_mem_buffer_pages_lower = 0 static
Definition at line 1178 of file system_parameter.c.
int prm_temp_mem_buffer_pages_upper = 20 static
Definition at line 1179 of file system_parameter.c.
bool PRM_TEST_MODE = false
Definition at line 1279 of file system_parameter.c.
Referenced by sysprm_validate_change_parameters().
bool prm_test_mode_default = false static
Definition at line 1280 of file system_parameter.c.
unsigned int prm_test_mode_flag = 0 static
Definition at line 1281 of file system_parameter.c.
bool PRM_THREAD_CONNECTION_POOLING = true
Definition at line 2179 of file system_parameter.c.
bool prm_thread_connection_pooling_default = true static
Definition at line 2180 of file system_parameter.c.
unsigned int prm_thread_connection_pooling_flag = 0 static
Definition at line 2181 of file system_parameter.c.
int PRM_THREAD_CONNECTION_TIMEOUT_SECONDS = 300
Definition at line 2183 of file system_parameter.c.
int prm_thread_connection_timeout_seconds_default = 300 static
Definition at line 2184 of file system_parameter.c.
unsigned int prm_thread_connection_timeout_seconds_flag = 0 static
Definition at line 2187 of file system_parameter.c.
int prm_thread_connection_timeout_seconds_lower = -1 static
Definition at line 2186 of file system_parameter.c.
int prm_thread_connection_timeout_seconds_upper = 60 * 60 static
Definition at line 2185 of file system_parameter.c.
int PRM_THREAD_LOGGING_FLAG = 0
Definition at line 2171 of file system_parameter.c.
int prm_thread_logging_flag_default = 0 static
Definition at line 2172 of file system_parameter.c.
unsigned int prm_thread_logging_flag_flag = 0 static
Definition at line 2173 of file system_parameter.c.
UINT64 PRM_THREAD_STACKSIZE = (1024 * 1024)
Definition at line 1132 of file system_parameter.c.
UINT64 prm_thread_stacksize_default = (1024 * 1024) static
Definition at line 1133 of file system_parameter.c.
unsigned int prm_thread_stacksize_flag = 0 static
Definition at line 1136 of file system_parameter.c.
UINT64 prm_thread_stacksize_lower = 64 * 1024 static
Definition at line 1134 of file system_parameter.c.
UINT64 prm_thread_stacksize_upper = INT_MAX static
Definition at line 1135 of file system_parameter.c.
bool PRM_THREAD_WORKER_POOLING = true
Definition at line 2189 of file system_parameter.c.
bool prm_thread_worker_pooling_default = true static
Definition at line 2190 of file system_parameter.c.
unsigned int prm_thread_worker_pooling_flag = 0 static
Definition at line 2191 of file system_parameter.c.
int PRM_THREAD_WORKER_TIMEOUT_SECONDS = 300
Definition at line 2193 of file system_parameter.c.
int prm_thread_worker_timeout_seconds_default = 300 static
Definition at line 2194 of file system_parameter.c.
unsigned int prm_thread_worker_timeout_seconds_flag = 0 static
Definition at line 2197 of file system_parameter.c.
int prm_thread_worker_timeout_seconds_lower = -1 static
Definition at line 2196 of file system_parameter.c.
int prm_thread_worker_timeout_seconds_upper = 60 * 60 static
Definition at line 2195 of file system_parameter.c.
char* PRM_TIMEZONE = NULL
Definition at line 2032 of file system_parameter.c.
char* prm_timezone_default = NULL static
Definition at line 2033 of file system_parameter.c.
unsigned int prm_timezone_flag = 0 static
Definition at line 2034 of file system_parameter.c.
bool PRM_TRACK_REQUESTS = false
Definition at line 2249 of file system_parameter.c.
bool prm_track_requests_default = false static
Definition at line 2250 of file system_parameter.c.
unsigned int prm_track_requests_flag = 0 static
Definition at line 2251 of file system_parameter.c.
bool PRM_TZ_LEAP_SECOND_SUPPORT = false
Definition at line 2041 of file system_parameter.c.
bool prm_tz_leap_second_support_default = false
Definition at line 2040 of file system_parameter.c.
bool PRM_UNICODE_INPUT_NORMALIZATION = false
Definition at line 1803 of file system_parameter.c.
bool prm_unicode_input_normalization_default = false static
Definition at line 1804 of file system_parameter.c.
unsigned int prm_unicode_input_normalization_flag = 0 static
Definition at line 1805 of file system_parameter.c.
bool PRM_UNICODE_OUTPUT_NORMALIZATION = false
Definition at line 1807 of file system_parameter.c.
bool prm_unicode_output_normalization_default = false static
Definition at line 1808 of file system_parameter.c.
unsigned int prm_unicode_output_normalization_flag = 0 static
Definition at line 1809 of file system_parameter.c.
bool PRM_UNIQUE_ERROR_KEY_VALUE = false
Definition at line 1734 of file system_parameter.c.
bool prm_unique_error_key_value_default = false static
Definition at line 1735 of file system_parameter.c.
unsigned int prm_unique_error_key_value_flag = 0 static
Definition at line 1736 of file system_parameter.c.
bool PRM_UNLOADDB_IGNORE_ERROR = false
Definition at line 1708 of file system_parameter.c.
bool prm_unloaddb_ignore_error_default = false static
Definition at line 1709 of file system_parameter.c.
unsigned int prm_unloaddb_ignore_error_flag = 0 static
Definition at line 1710 of file system_parameter.c.
int PRM_UNLOADDB_LOCK_TIMEOUT = -1
Definition at line 1712 of file system_parameter.c.
int prm_unloaddb_lock_timeout_default = -1 static
Definition at line 1713 of file system_parameter.c.
unsigned int prm_unloaddb_lock_timeout_flag = 0 static
Definition at line 1715 of file system_parameter.c.
int prm_unloaddb_lock_timeout_lower = -1 static
Definition at line 1714 of file system_parameter.c.
bool PRM_UPDATE_USE_ATTRIBUTE_REFERENCES = false
Definition at line 1883 of file system_parameter.c.
bool prm_update_use_attribute_references_default = false static
Definition at line 1884 of file system_parameter.c.
unsigned int prm_update_use_attribute_references_flag = 0 static
Definition at line 1885 of file system_parameter.c.
bool PRM_USE_BTREE_FENCE_KEY = true
Definition at line 1879 of file system_parameter.c.
bool prm_use_btree_fence_key_default = true static
Definition at line 1880 of file system_parameter.c.
unsigned int prm_use_btree_fence_key_flag = 0 static
Definition at line 1881 of file system_parameter.c.
bool PRM_USE_ORDERBY_SORT_LIMIT = true
Definition at line 1424 of file system_parameter.c.
bool prm_use_orderby_sort_limit_default = true static
Definition at line 1425 of file system_parameter.c.
unsigned int prm_use_orderby_sort_limit_flag = 0 static
Definition at line 1426 of file system_parameter.c.
bool PRM_USE_STAT_ESTIMATION = false
Definition at line 2329 of file system_parameter.c.
bool prm_use_stat_estimation_default = false static
Definition at line 2330 of file system_parameter.c.
unsigned int prm_use_stat_estimation_flag = 0 static
Definition at line 2331 of file system_parameter.c.
bool PRM_USE_SYSTEM_MALLOC = false
Definition at line 1738 of file system_parameter.c.
bool prm_use_system_malloc_default = false static
Definition at line 1739 of file system_parameter.c.
unsigned int prm_use_system_malloc_flag = 0 static
Definition at line 1740 of file system_parameter.c.
int PRM_VACUUM_LOG_BLOCK_PAGES = VACUUM_LOG_BLOCK_PAGES_DEFAULT
Definition at line 2004 of file system_parameter.c.
int prm_vacuum_log_block_pages_default = VACUUM_LOG_BLOCK_PAGES_DEFAULT static
Definition at line 2005 of file system_parameter.c.
unsigned int prm_vacuum_log_block_pages_flag = 0 static
Definition at line 2008 of file system_parameter.c.
int prm_vacuum_log_block_pages_lower = 4 static
Definition at line 2006 of file system_parameter.c.
int prm_vacuum_log_block_pages_upper = 1024 static
Definition at line 2007 of file system_parameter.c.
int PRM_VACUUM_MASTER_WAKEUP_INTERVAL = 10
Definition at line 1995 of file system_parameter.c.
int prm_vacuum_master_wakeup_interval_default = 10 static
Definition at line 1996 of file system_parameter.c.
unsigned int prm_vacuum_master_wakeup_interval_flag = 0 static
Definition at line 1998 of file system_parameter.c.
int prm_vacuum_master_wakeup_interval_lower = 1 static
Definition at line 1997 of file system_parameter.c.
unsigned int prm_vacuum_prefetch_log_mode_flag = 0 static
Definition at line 2049 of file system_parameter.c.
unsigned int prm_vacuum_prefetch_log_nbuffers_flag = 0 static
Definition at line 2048 of file system_parameter.c.
int PRM_VACUUM_WORKER_COUNT = 10
Definition at line 2010 of file system_parameter.c.
int prm_vacuum_worker_count_default = 10 static
Definition at line 2011 of file system_parameter.c.
unsigned int prm_vacuum_worker_count_flag = 0 static
Definition at line 2014 of file system_parameter.c.
int prm_vacuum_worker_count_lower = 1 static
Definition at line 2012 of file system_parameter.c.
int prm_vacuum_worker_count_upper = VACUUM_MAX_WORKER_COUNT static
Definition at line 2013 of file system_parameter.c.
int prm_week_format_default = 0 static
Definition at line 1274 of file system_parameter.c.
unsigned int prm_week_format_flag = 0 static
Definition at line 1277 of file system_parameter.c.
int prm_week_format_lower = 0 static
Definition at line 1275 of file system_parameter.c.
int prm_week_format_upper = 7 static
Definition at line 1276 of file system_parameter.c.
int PRM_WS_HASHTABLE_SIZE = 4096
Definition at line 1091 of file system_parameter.c.
int prm_ws_hashtable_size_default = 4096 static
Definition at line 1092 of file system_parameter.c.
unsigned int prm_ws_hashtable_size_flag = 0 static
Definition at line 1094 of file system_parameter.c.
int prm_ws_hashtable_size_lower = 1024 static
Definition at line 1093 of file system_parameter.c.
bool PRM_WS_MEMORY_REPORT = false
Definition at line 1096 of file system_parameter.c.
bool prm_ws_memory_report_default = false static
Definition at line 1097 of file system_parameter.c.
unsigned int prm_ws_memory_report_flag = 0 static
Definition at line 1098 of file system_parameter.c.
bool PRM_XASL_CACHE_LOGGING = false
Definition at line 1394 of file system_parameter.c.
bool prm_xasl_cache_logging_default = false static
Definition at line 1395 of file system_parameter.c.
unsigned int prm_xasl_cache_logging_flag = 0 static
Definition at line 1396 of file system_parameter.c.
int PRM_XASL_CACHE_MAX_CLONES = 1000
Definition at line 1384 of file system_parameter.c.
int prm_xasl_cache_max_clones_default = 1000 static
Definition at line 1385 of file system_parameter.c.
unsigned int prm_xasl_cache_max_clones_flag = 0 static
Definition at line 1388 of file system_parameter.c.
int prm_xasl_cache_max_clones_lower = 0 static
Definition at line 1386 of file system_parameter.c.
int prm_xasl_cache_max_clones_upper = 2000 static
Definition at line 1387 of file system_parameter.c.
int PRM_XASL_CACHE_MAX_ENTRIES = 1000
Definition at line 1380 of file system_parameter.c.
int prm_xasl_cache_max_entries_default = 1000 static
Definition at line 1381 of file system_parameter.c.
unsigned int prm_xasl_cache_max_entries_flag = 0 static
Definition at line 1382 of file system_parameter.c.
int PRM_XASL_CACHE_TIME_THRESHOLD_IN_MINUTES = 360
Definition at line 2127 of file system_parameter.c.
int prm_xasl_cache_time_threshold_in_minutes_default = 360 static
Definition at line 2129 of file system_parameter.c.
unsigned int prm_xasl_cache_time_threshold_in_minutes_flag = 0 static
Definition at line 2128 of file system_parameter.c.
int prm_xasl_cache_time_threshold_in_minutes_lower = 0 static
Definition at line 2131 of file system_parameter.c.
int prm_xasl_cache_time_threshold_in_minutes_upper = INT_MAX static
Definition at line 2130 of file system_parameter.c.
int PRM_XASL_CACHE_TIMEOUT = -1
Definition at line 1390 of file system_parameter.c.
int prm_xasl_cache_timeout_default = -1 static
Definition at line 1391 of file system_parameter.c.
unsigned int prm_xasl_cache_timeout_flag = 0 static
Definition at line 1392 of file system_parameter.c.
bool PRM_XASL_DEBUG_DUMP = false
Definition at line 1686 of file system_parameter.c.
bool prm_xasl_debug_dump_default = false static
Definition at line 1687 of file system_parameter.c.
unsigned int prm_xasl_debug_dump_flag = 0 static
Definition at line 1688 of file system_parameter.c.
KEYVAL query_trace_format_words[] static
Initial value:
= {
  {"text", QUERY_TRACE_TEXT},
  {"json", QUERY_TRACE_JSON},
}
Definition at line 6192 of file system_parameter.c.
const char sysprm_conf_file_name[] = "cubrid.conf" static
Definition at line 102 of file system_parameter.c.
Referenced by sysprm_load_and_init_internal().
const char sysprm_error_log_file[] = "cub_server.err" static
Definition at line 98 of file system_parameter.c.
const char sysprm_ha_conf_file_name[] = "cubrid_ha.conf" static
Definition at line 103 of file system_parameter.c.
Referenced by sysprm_load_and_init_internal().
KEYVAL tde_algorithm_words[] static
Initial value:
= {
  {"aes", TDE_ALGORITHM_AES},
  {"aria", TDE_ALGORITHM_ARIA}
}
Definition at line 6207 of file system_parameter.c.