CUBRID Engine: src/object/transform_cl.h File Reference
transform_cl.h File Reference
#include "locator.h"
Macros
#define TF_SUCCESS (0)
#define TF_OUT_OF_SPACE (1)
#define TF_ERROR (2)
Typedefs
typedef int TF_STATUS
Functions
TF_STATUS tf_mem_to_disk (MOP classmop, MOBJ classobj, volatile MOBJ obj, RECDES *record, bool *index_flag)
MOBJ tf_disk_to_mem (MOBJ classobj, RECDES *record, int *convertp)
TF_STATUS tf_class_to_disk (MOBJ classobj, RECDES *record)
MOBJ tf_disk_to_class (OID *oid, RECDES *record)
int tf_object_size (MOBJ classobj, MOBJ obj)
OID * tf_need_permanent_oid (or_buf *buf, DB_OBJECT *obj)
Variables
int tf_Allow_fixups
Macro Definition Documentation
#define TF_ERROR (2)
Definition at line 47 of file transform_cl.h.
Referenced by locator_class_to_disk(), locator_mem_to_disk(), tf_class_to_disk(), and tf_mem_to_disk().
#define TF_OUT_OF_SPACE (1)
Definition at line 46 of file transform_cl.h.
Referenced by tf_class_to_disk(), and tf_mem_to_disk().
#define TF_SUCCESS (0)
Definition at line 45 of file transform_cl.h.
Referenced by locator_class_to_disk(), locator_mem_to_disk(), tf_class_to_disk(), and tf_mem_to_disk().
Typedef Documentation
typedef int TF_STATUS
Definition at line 37 of file transform_cl.h.
Function Documentation
TF_STATUS tf_class_to_disk (MOBJ classobj, RECDES * record)
Definition at line 4427 of file transform_cl.c.
References recdes::area_size, ARG_FILE_LINE, assert, sm_class::attributes, BIG_VAR_OFFSET_SIZE, or_buf::buffer, CAST_BUFLEN, sm_class_header::ch_obj_header, sm_class_header::ch_type, ws_object_header::chn, class_to_disk(), classobj_free_prop(), recdes::data, or_buf::env, ER_ERROR_SEVERITY, er_set(), ER_TF_BUFFER_OVERFLOW, ER_TF_SIZE_MISMATCH, or_buf::error_abort, sm_class::header, recdes::length, tf_meta_class::mc_n_variable, NO_ERROR, NULL, or_abort(), or_init(), OR_MVCC_FLAG_MASK, OR_MVCC_FLAG_SHIFT_BITS, OR_OFFSET_SIZE_FLAG, or_put_int(), OR_SET_VAR_OFFSET_SIZE, sm_class::partition, sm_class::properties, or_buf::ptr, rc, sm_class::repid, root_size(), root_to_disk(), SM_META_ROOT, sm_Root_class, tf_attribute_default_expr_to_property(), tf_class_size(), tf_compile_meta_classes(), TF_ERROR, tf_Metaclass_class, TF_OUT_OF_SPACE, and TF_SUCCESS.
Referenced by locator_class_to_disk().
MOBJ tf_disk_to_class (OID * oid, RECDES * record)
Definition at line 4344 of file transform_cl.c.
References assert, BIG_VAR_OFFSET_SIZE, classobj_free_class(), recdes::data, disk_to_class(), disk_to_root(), or_buf::env, or_buf::error_abort, recdes::length, tf_meta_class::mc_n_variable, NO_ERROR, NULL, oid_is_root(), OID_ISNULL, or_get_int(), OR_GET_OFFSET_SIZE, or_init(), OR_MVCC_FLAG_MASK, OR_MVCC_FLAG_SHIFT_BITS, OR_OFFSET_SIZE_FLAG, or_buf::ptr, rc, sm_class::repid, sm_bump_global_schema_version(), tf_compile_meta_classes(), and tf_Metaclass_class.
Referenced by locator_cache_object_class().
MOBJ tf_disk_to_mem (MOBJ classobj, RECDES * record, int * convertp)
Definition at line 1323 of file transform_cl.c.
References recdes::data, or_buf::env, or_buf::error_abort, get_current(), get_old(), recdes::length, NO_ERROR, NULL, obj_free_memory(), or_advance(), OR_BOUND_BIT_FLAG, or_get_int(), OR_GET_OFFSET_SIZE, or_init(), OR_MVCC_FLAG_MASK, OR_MVCC_FLAG_SHIFT_BITS, OR_MVCC_FLAG_VALID_DELID, OR_MVCC_FLAG_VALID_INSID, OR_MVCC_FLAG_VALID_PREV_VERSION, or_mvcc_get_repid_and_flags(), OR_MVCC_PREV_VERSION_LSA_SIZE, OR_MVCC_REPID_MASK, OR_MVCCID_SIZE, or_buf::ptr, rc, sm_class::repid, and WS_CHN.
Referenced by locator_cache_object_instance().
TF_STATUS tf_mem_to_disk (MOP classmop, MOBJ classobj, volatile MOBJ obj, RECDES * record, bool * index_flag)
Definition at line 767 of file transform_cl.c.
References recdes::area_size, ARG_FILE_LINE, or_buf::buffer, classobj_class_has_indexes(), recdes::data, or_buf::env, er_errid(), ER_ERROR_SEVERITY, ER_OBJ_CANT_ASSIGN_OID, er_set(), ER_TF_BUFFER_OVERFLOW, or_buf::error_abort, sm_class::fixed_count, or_buf::fixups, recdes::length, locator_assign_permanent_oid(), MVCCID_NULL, NO_ERROR, NULL, object_size(), OID_ISTEMP, optimize_sets(), or_abort(), OR_BOUND_BIT_FLAG, or_init(), OR_MVCC_FLAG_SHIFT_BITS, OR_MVCC_FLAG_VALID_INSID, OR_MVCC_INSERT_HEADER_SIZE, OR_MVCC_MAX_HEADER_SIZE, or_put_bigint(), or_put_int(), OR_SET_VAR_OFFSET_SIZE, or_buf::ptr, put_attributes(), put_varinfo(), sm_class::repid, tf_Allow_fixups, tf_do_fixup(), TF_ERROR, tf_free_fixup(), tf_make_fixup(), TF_OUT_OF_SPACE, TF_SUCCESS, WS_CHN, and WS_OID.
Referenced by locator_mem_to_disk().
OID* tf_need_permanent_oid (or_buf * buf, DB_OBJECT * obj)
Definition at line 513 of file transform_cl.c.
References ARG_FILE_LINE, db_object::class_mop, er_errid(), ER_ERROR_SEVERITY, ER_OBJ_CANT_ASSIGN_OID, er_set(), or_buf::fixups, locator_assign_permanent_oid(), NO_ERROR, NULL, oid_Null_oid, or_abort(), or_buf::ptr, sm_Root_class_mop, tf_add_fixup(), tf_Allow_fixups, and WS_OID.
Referenced by mr_data_writemem_object(), and mr_data_writeval_object().
int tf_object_size (MOBJ classobj, MOBJ obj)
Definition at line 4562 of file transform_cl.c.
References object_size(), root_size(), sm_Root_class, and tf_class_size().
Referenced by locator_add_oidset_object(), locator_assign_permanent_oid(), and sm_object_size_quick().
Variable Documentation
int tf_Allow_fixups
Definition at line 70 of file transform_cl.c.
Referenced by tf_mem_to_disk(), and tf_need_permanent_oid().