CUBRID Engine: src/transaction/transaction_sr.h File Reference
transaction_sr.h File Reference
#include "connection_defs.h"
#include "log_comm.h"
#include "storage_common.h"
#include "thread_compat.hpp"
Functions
TRAN_STATE tran_server_unilaterally_abort_tran (THREAD_ENTRY *thread_p)
int xtran_get_local_transaction_id (THREAD_ENTRY *thread_p, DB_VALUE *trid)
Function Documentation
TRAN_STATE tran_server_unilaterally_abort_tran (THREAD_ENTRY * thread_p)
Referenced by return_error_to_client(), and xtran_server_abort().
int xtran_get_local_transaction_id (THREAD_ENTRY * thread_p, DB_VALUE * trid)
Definition at line 665 of file transaction_sr.c.
References assert, db_make_int(), DB_TYPE_INTEGER, db_value_domain_init(), logtb_find_current_tranid(), NO_ERROR, and NULL.
Referenced by db_local_transaction_id(), sqp_get_server_info(), and stran_get_local_transaction_id().