CUBRID Engine: src/transaction/transaction_cl.h File Reference
transaction_cl.h File Reference
#include "config.h"
#include "error_manager.h"
#include "locator.h"
#include "storage_common.h"
#include "log_comm.h"
Macros
#define TM_TRAN_INDEX() (tm_Tran_index)
#define TM_TRAN_ISOLATION() (tm_Tran_isolation)
#define TM_TRAN_ASYNC_WS() (tm_Tran_async_ws)
#define TM_TRAN_WAIT_MSECS() (tm_Tran_wait_msecs)
#define TM_TRAN_ID() (tm_Tran_ID)
#define TM_TRAN_REP_READ_LOCK() (tm_Tran_rep_read_lock)
#define TM_TRAN_READ_FETCH_VERSION() (tm_Tran_read_fetch_instance_version)
Typedefs
typedef enum savepoint_type SAVEPOINT_TYPE
Enumerations
enum savepoint_type { USER_SAVEPOINT = 1, SYSTEM_SAVEPOINT = 2 }
Functions
void tran_cache_tran_settings (int tran_index, int lock_timeout, TRAN_ISOLATION tran_isolation)
void tran_get_tran_settings (int *lock_timeout_in_msecs, TRAN_ISOLATION *tran_isolation, bool *async_ws)
int tran_reset_wait_times (int wait_in_msecs)
int tran_reset_isolation (TRAN_ISOLATION isolation, bool async_ws)
int tran_flush_to_commit (void)
int tran_commit (bool retain_lock)
int tran_abort (void)
int tran_unilaterally_abort (void)
int tran_abort_only_client (bool is_server_down)
bool tran_has_updated (void)
bool tran_is_active_and_has_updated (void)
int tran_set_global_tran_info (int gtrid, void *info, int size)
int tran_get_global_tran_info (int gtrid, void *buffer, int size)
int tran_2pc_start (void)
int tran_2pc_prepare (void)
int tran_2pc_recovery_prepared (int gtrids[], int size)
int tran_2pc_attach_global_tran (int gtrid)
int tran_2pc_prepare_global_tran (int gtrid)
void tran_free_savepoint_list (void)
int tran_system_savepoint (const char *savept_name)
int tran_savepoint_internal (const char *savept_name, SAVEPOINT_TYPE savepoint_type)
int tran_abort_upto_user_savepoint (const char *savepoint_name)
int tran_abort_upto_system_savepoint (const char *savepoint_name)
int tran_internal_abort_upto_savepoint (const char *savepoint_name, SAVEPOINT_TYPE savepoint_type, bool client_decache_only_insts)
void tran_set_query_timeout (int query_timeout)
int tran_get_query_timeout (void)
void tran_begin_libcas_function (void)
void tran_end_libcas_function (void)
bool tran_is_in_libcas (void)
bool tran_set_check_interrupt (bool flag)
bool tran_get_check_interrupt (void)
void tran_set_latest_query_status (int end_query_result, int tran_state, int should_conn_reset)
bool tran_was_latest_query_ended (void)
bool tran_was_latest_query_committed (void)
bool tran_was_latest_query_aborted (void)
bool tran_is_reset_required (void)
void tran_reset_latest_query_status (void)
Variables
int tm_Tran_index
TRAN_ISOLATION tm_Tran_isolation
bool tm_Tran_async_ws
int tm_Tran_wait_msecs
int tm_Tran_ID
bool tm_Tran_check_interrupt
bool tm_Use_OID_preflush
LOCK tm_Tran_rep_read_lock
LC_FETCH_VERSION_TYPE tm_Tran_read_fetch_instance_version
int tm_Tran_invalidate_snapshot
Macro Definition Documentation
#define TM_TRAN_ASYNC_WS () (tm_Tran_async_ws)
Definition at line 43 of file transaction_cl.h.
Referenced by boot_restart_client(), ci_conn_set_option_impl(), db_set_isolation(), find_unique(), flush_temporary_OID(), obj_find_multi_attr(), obj_find_multi_desc(), obj_find_object_by_pkey(), and tran_get_tran_settings().
#define TM_TRAN_ID () (tm_Tran_ID)
Definition at line 45 of file transaction_cl.h.
#define TM_TRAN_INDEX () (tm_Tran_index)
Definition at line 41 of file transaction_cl.h.
Referenced by er_log().
#define TM_TRAN_ISOLATION () (tm_Tran_isolation)
Definition at line 42 of file transaction_cl.h.
Referenced by boot_server_die_or_changed(), db_invalidate_mvcc_snapshot_before_statement(), delete_list_by_oids(), do_alter_trigger(), do_create_trigger(), do_execute_delete(), do_execute_update(), do_insert_template(), do_update(), insert_local(), insert_subquery_results(), locator_fun_get_all_mops(), locator_lock(), locator_lock_and_doesexist(), locator_synch_isolation_incons(), make_template(), pt_class_pre_fetch(), tr_create_trigger(), tr_drop_trigger(), tr_rename_trigger(), tran_get_tran_settings(), and update_objs_for_list_file().
#define TM_TRAN_READ_FETCH_VERSION () (tm_Tran_read_fetch_instance_version)
Definition at line 47 of file transaction_cl.h.
Referenced by au_is_dba_group_member(), check_set_object(), csql_help_trigger(), csql_results(), do_execute_statement(), do_statement(), get_object_value(), object_description::init(), its_deleted(), locator_does_exist_object(), locator_fetch_class_of_instance(), locator_fetch_nested(), locator_fetch_set(), locator_get_cache_coherency_number(), locator_is_class(), locator_lock(), locator_lock_and_doesexist(), locator_lock_set(), obj_copy(), obj_get_att(), obj_is_instance_of(), obj_isinstance(), obj_locate_attribute(), object_to_trigger(), process_value(), sm_active_triggers(), sm_check_object_domain(), sm_coerce_object_domain(), sm_flush_and_decache_objects(), validate_trigger(), vid_vobj_to_object(), and ws_rehash_vmop().
#define TM_TRAN_REP_READ_LOCK () (tm_Tran_rep_read_lock)
Definition at line 46 of file transaction_cl.h.
Referenced by pt_class_pre_fetch().
#define TM_TRAN_WAIT_MSECS () (tm_Tran_wait_msecs)
Definition at line 44 of file transaction_cl.h.
Referenced by boot_server_die_or_changed(), delete_real_class(), do_execute_delete(), do_execute_merge(), do_execute_update(), do_insert_template(), do_merge(), tran_get_tran_settings(), and update_real_class().
Typedef Documentation
typedef enum savepoint_type SAVEPOINT_TYPE
Enumeration Type Documentation
enum savepoint_type
Enumerator
USER_SAVEPOINT
SYSTEM_SAVEPOINT
Definition at line 49 of file transaction_cl.h.
Function Documentation
int tran_2pc_attach_global_tran (int gtrid)
Definition at line 840 of file transaction_cl.c.
References assert, er_errid(), NO_ERROR, NULL_TRAN_INDEX, tm_Tran_index, and tran_server_2pc_attach_global_tran().
Referenced by db_2pc_attach_transaction().
int tran_2pc_prepare (void)
Definition at line 717 of file transaction_cl.c.
References ARG_FILE_LINE, assert, BOOT_IS_CLIENT_RESTARTED, db_clear_client_query_result(), er_errid(), er_log_debug, er_stack_clearall(), locator_all_flush(), log_state_string(), NO_ERROR, TRAN_ACTIVE, TRAN_RECOVERY, tran_server_2pc_prepare(), TRAN_UNACTIVE_2PC_ABORT_DECISION, TRAN_UNACTIVE_2PC_COLLECTING_PARTICIPANT_VOTES, TRAN_UNACTIVE_2PC_COMMIT_DECISION, TRAN_UNACTIVE_2PC_PREPARE, TRAN_UNACTIVE_ABORTED, TRAN_UNACTIVE_ABORTED_INFORMING_PARTICIPANTS, TRAN_UNACTIVE_COMMITTED, TRAN_UNACTIVE_COMMITTED_INFORMING_PARTICIPANTS, TRAN_UNACTIVE_COMMITTED_WITH_POSTPONE, TRAN_UNACTIVE_TOPOPE_COMMITTED_WITH_POSTPONE, TRAN_UNACTIVE_UNILATERALLY_ABORTED, TRAN_UNACTIVE_UNKNOWN, and ws_clear_all_hints().
Referenced by db_2pc_prepare_transaction().
int tran_2pc_prepare_global_tran (int gtrid)
Definition at line 871 of file transaction_cl.c.
References ARG_FILE_LINE, assert, BOOT_IS_CLIENT_RESTARTED, db_clear_client_query_result(), er_errid(), er_log_debug, er_stack_clearall(), locator_all_flush(), log_state_string(), NO_ERROR, TRAN_ACTIVE, TRAN_RECOVERY, tran_server_2pc_prepare_global_tran(), TRAN_UNACTIVE_2PC_ABORT_DECISION, TRAN_UNACTIVE_2PC_COLLECTING_PARTICIPANT_VOTES, TRAN_UNACTIVE_2PC_COMMIT_DECISION, TRAN_UNACTIVE_2PC_PREPARE, TRAN_UNACTIVE_ABORTED, TRAN_UNACTIVE_ABORTED_INFORMING_PARTICIPANTS, TRAN_UNACTIVE_COMMITTED, TRAN_UNACTIVE_COMMITTED_INFORMING_PARTICIPANTS, TRAN_UNACTIVE_COMMITTED_WITH_POSTPONE, TRAN_UNACTIVE_TOPOPE_COMMITTED_WITH_POSTPONE, TRAN_UNACTIVE_UNILATERALLY_ABORTED, TRAN_UNACTIVE_UNKNOWN, and ws_clear_all_hints().
Referenced by db_2pc_prepare_to_commit_transaction().
int tran_2pc_recovery_prepared (int gtrids[], int size)
Definition at line 819 of file transaction_cl.c.
References tran_server_2pc_recovery_prepared().
Referenced by db_2pc_prepared_transactions().
int tran_2pc_start (void)
Definition at line 697 of file transaction_cl.c.
References tran_server_2pc_start().
Referenced by db_2pc_start_transaction().
int tran_abort (void)
Definition at line 409 of file transaction_cl.c.
References ARG_FILE_LINE, assert, ASSERT_ERROR_AND_SET, BOOT_IS_CLIENT_RESTARTED, db_clear_client_query_result(), er_log_debug, er_stack_clearall(), log_state_string(), NO_ERROR, NULL_LOCK, sm_transaction_boundary(), tm_Tran_rep_read_lock, tr_check_rollback_triggers(), TR_TIME_AFTER, TR_TIME_BEFORE, TRAN_ACTIVE, tran_free_savepoint_list(), TRAN_RECOVERY, tran_reset_latest_query_status(), tran_server_abort(), TRAN_UNACTIVE_2PC_ABORT_DECISION, TRAN_UNACTIVE_2PC_COLLECTING_PARTICIPANT_VOTES, TRAN_UNACTIVE_2PC_COMMIT_DECISION, TRAN_UNACTIVE_2PC_PREPARE, TRAN_UNACTIVE_ABORTED, TRAN_UNACTIVE_ABORTED_INFORMING_PARTICIPANTS, TRAN_UNACTIVE_COMMITTED, TRAN_UNACTIVE_COMMITTED_INFORMING_PARTICIPANTS, TRAN_UNACTIVE_COMMITTED_WITH_POSTPONE, TRAN_UNACTIVE_TOPOPE_COMMITTED_WITH_POSTPONE, TRAN_UNACTIVE_UNILATERALLY_ABORTED, TRAN_UNACTIVE_UNKNOWN, tran_was_latest_query_aborted(), tran_was_latest_query_committed(), tran_was_latest_query_ended(), ws_abort_mops(), ws_clear(), ws_filter_dirty(), and ws_increment_mvcc_snapshot_version().
Referenced by boot_shutdown_client(), conn_end_tran(), db_abort_transaction(), do_rollback(), sqmgr_execute_query(), and tran_unilaterally_abort().
int tran_abort_only_client (bool is_server_down)
Definition at line 561 of file transaction_cl.c.
References ARG_FILE_LINE, BOOT_IS_CLIENT_RESTARTED, db_clear_client_query_result(), ER_ERROR_SEVERITY, er_set(), ER_TM_SERVER_DOWN_UNILATERALLY_ABORTED, NO_ERROR, NULL_LOCK, tm_Tran_rep_read_lock, tr_check_abort_triggers(), ws_abort_mops(), and ws_filter_dirty().
Referenced by boot_server_die_or_changed(), compactdb_start(), do_execute_statement(), do_reclaim_class_addresses(), do_statement(), locator_assign_permanent_oid(), locator_find_class_by_oid(), locator_fun_get_all_mops(), locator_lock(), locator_lock_and_doesexist(), locator_lock_class_of_instance(), and locator_lockhint_classes().
int tran_abort_upto_system_savepoint (const char * savepoint_name)
Definition at line 1148 of file transaction_cl.c.
References SYSTEM_SAVEPOINT, and tran_internal_abort_upto_savepoint().
Referenced by au_change_owner_method(), au_grant(), au_revoke(), check_merge_trigger(), check_trigger(), dbt_rename(), delete_list_by_oids(), do_alter(), do_alter_change_col_comment(), do_alter_change_default_cs_coll(), do_alter_change_tbl_comment(), do_alter_clause_change_attribute(), do_alter_index_comment(), do_alter_index_rebuild(), do_alter_index_status(), do_alter_one_clause_with_template(), do_alter_trigger(), do_alter_user(), do_check_internal_statements(), do_create_entity(), do_create_user(), do_drop(), do_drop_user(), do_grant(), do_rename(), do_revoke(), do_truncate(), jsp_add_stored_procedure(), jsp_create_stored_procedure(), obt_update_internal(), sm_add_constraint(), sm_add_secondary_index_on_partition(), sm_delete_class_mop(), sm_drop_index(), sm_exist_index(), sm_rename_class(), sm_truncate_class(), tr_create_trigger(), tr_drop_trigger_internal(), tr_rename_trigger(), update_class(), and update_objs_for_list_file().
int tran_abort_upto_user_savepoint (const char * savepoint_name)
Definition at line 1161 of file transaction_cl.c.
References tran_free_list_upto_savepoint(), tran_internal_abort_upto_savepoint(), and USER_SAVEPOINT.
Referenced by db_abort_to_savepoint_internal().
void tran_begin_libcas_function (void)
Definition at line 1315 of file transaction_cl.c.
References tm_Is_libcas.
Referenced by jsp_receive_response(), and jsp_send_destroy_request().
void tran_cache_tran_settings (int tran_index, int lock_timeout, TRAN_ISOLATION tran_isolation)
Definition at line 121 of file transaction_cl.c.
References db_Connect_status, DB_CONNECTION_STATUS_NOT_CONNECTED, NULL_TRAN_INDEX, tm_Tran_index, tm_Tran_isolation, and tm_Tran_wait_msecs.
Referenced by boot_client(), and logpb_fatal_error_internal().
int tran_commit (bool retain_lock)
Definition at line 272 of file transaction_cl.c.
References ARG_FILE_LINE, assert, ASSERT_ERROR_AND_SET, BOOT_IS_CLIENT_RESTARTED, db_clear_client_query_result(), db_Connect_status, DB_CONNECTION_STATUS_RESET, er_log_debug, er_stack_clearall(), log_does_allow_replication(), log_state_string(), NO_ERROR, NULL_LOCK, sm_transaction_boundary(), tm_Tran_rep_read_lock, tr_check_commit_triggers(), TR_TIME_AFTER, TR_TIME_BEFORE, TRAN_ACTIVE, tran_flush_to_commit(), tran_free_savepoint_list(), tran_is_reset_required(), TRAN_RECOVERY, tran_reset_latest_query_status(), tran_server_commit(), TRAN_UNACTIVE_2PC_ABORT_DECISION, TRAN_UNACTIVE_2PC_COLLECTING_PARTICIPANT_VOTES, TRAN_UNACTIVE_2PC_COMMIT_DECISION, TRAN_UNACTIVE_2PC_PREPARE, TRAN_UNACTIVE_ABORTED, TRAN_UNACTIVE_ABORTED_INFORMING_PARTICIPANTS, TRAN_UNACTIVE_COMMITTED, TRAN_UNACTIVE_COMMITTED_INFORMING_PARTICIPANTS, TRAN_UNACTIVE_COMMITTED_WITH_POSTPONE, TRAN_UNACTIVE_TOPOPE_COMMITTED_WITH_POSTPONE, TRAN_UNACTIVE_UNILATERALLY_ABORTED, TRAN_UNACTIVE_UNKNOWN, tran_was_latest_query_aborted(), tran_was_latest_query_committed(), tran_was_latest_query_ended(), ws_clear_all_hints(), and ws_increment_mvcc_snapshot_version().
Referenced by boot_initialize_client(), boot_restart_client(), boot_shutdown_client(), conn_end_tran(), db_commit_transaction(), do_commit(), and proxy_io_make_end_tran_request().
void tran_end_libcas_function (void)
Definition at line 1325 of file transaction_cl.c.
References tm_Is_libcas.
Referenced by jsp_receive_response(), and jsp_send_destroy_request().
int tran_flush_to_commit (void)
Definition at line 229 of file transaction_cl.c.
References err, locator_all_flush(), locator_assign_all_permanent_oids(), NO_ERROR, tm_Use_OID_preflush, and ws_need_flush().
Referenced by do_execute_delete(), do_execute_insert(), do_execute_merge(), do_execute_update(), and tran_commit().
void tran_free_savepoint_list (void)
Definition at line 1007 of file transaction_cl.c.
References nlist_free(), and NULL.
Referenced by boot_client_all_finalize(), boot_initialize_client(), boot_restart_client(), tran_abort(), and tran_commit().
bool tran_get_check_interrupt (void)
Definition at line 1361 of file transaction_cl.c.
References tm_Tran_check_interrupt.
Referenced by logtb_get_check_interrupt().
int tran_get_global_tran_info (int gtrid, void * buffer, int size)
Definition at line 669 of file transaction_cl.c.
References assert, er_errid(), NO_ERROR, and tran_server_get_global_tran_info().
Referenced by db_get_global_transaction_info().
int tran_get_query_timeout (void)
Definition at line 1290 of file transaction_cl.c.
References tm_Query_begin, tm_Query_timeout, and tran_current_timemillis().
Referenced by execute_query(), and prepare_and_execute_query().
void tran_get_tran_settings (int * lock_timeout_in_msecs, TRAN_ISOLATION * tran_isolation, bool * async_ws)
Definition at line 148 of file transaction_cl.c.
References TM_TRAN_ASYNC_WS, TM_TRAN_ISOLATION, and TM_TRAN_WAIT_MSECS.
Referenced by ci_conn_get_option_impl(), db_get_tran_settings(), do_get_xaction(), set_iso_level(), and ux_get_tran_setting().
bool tran_has_updated (void)
Definition at line 603 of file transaction_cl.c.
References tran_server_has_updated(), and ws_has_updated().
Referenced by db_commit_is_needed(), and tran_internal_abort_upto_savepoint().
int tran_internal_abort_upto_savepoint (const char * savepoint_name, SAVEPOINT_TYPE savepoint_type, bool client_decache_only_insts)
Definition at line 1202 of file transaction_cl.c.
References ARG_FILE_LINE, assert, er_errid(), er_log_debug, ER_NET_SERVER_CRASHED, ER_TM_SERVER_DOWN_UNILATERALLY_ABORTED, log_state_string(), NO_ERROR, sm_transaction_boundary(), SYSTEM_SAVEPOINT, tran_has_updated(), tran_server_partial_abort(), TRAN_UNACTIVE_ABORTED, TRAN_UNACTIVE_UNKNOWN, tran_unilaterally_abort(), ws_abort_mops(), ws_clear(), ws_decache_allxlockmops_but_norealclasses(), and ws_filter_dirty().
Referenced by insert_local(), tran_abort_upto_system_savepoint(), and tran_abort_upto_user_savepoint().
bool tran_is_active_and_has_updated (void)
Definition at line 618 of file transaction_cl.c.
References tran_server_is_active_and_has_updated(), and ws_has_updated().
Referenced by boot_shutdown_client().
bool tran_is_in_libcas (void)
Definition at line 1335 of file transaction_cl.c.
References tm_Is_libcas.
bool tran_is_reset_required (void)
Definition at line 1467 of file transaction_cl.c.
References RESET_REQUIRED, and tm_Tran_latest_query_status.
Referenced by tran_commit().
int tran_reset_isolation (TRAN_ISOLATION isolation, bool async_ws)
Definition at line 198 of file transaction_cl.c.
References ARG_FILE_LINE, ER_MVCC_LOG_INVALID_ISOLATION_LEVEL, er_set(), ER_SYNTAX_ERROR_SEVERITY, IS_VALID_ISOLATION_LEVEL, log_reset_isolation(), NO_ERROR, tm_Tran_async_ws, and tm_Tran_isolation.
Referenced by boot_restart_client(), ci_conn_set_option_impl(), db_set_isolation(), and do_set_xaction().
void tran_reset_latest_query_status (void)
Definition at line 1427 of file transaction_cl.c.
References NONE, and tm_Tran_latest_query_status.
Referenced by db_reset_latest_query_status(), tran_abort(), tran_commit(), and tran_set_latest_query_status().
int tran_reset_wait_times (int wait_in_msecs)
Definition at line 171 of file transaction_cl.c.
References log_reset_wait_msecs(), and tm_Tran_wait_msecs.
Referenced by boot_restart_client(), ci_conn_set_option_impl(), compactdb_start(), db_set_lock_timeout(), delete_real_class(), do_execute_delete(), do_execute_merge(), do_execute_update(), do_insert_template(), do_merge(), do_reclaim_addresses(), do_set_xaction(), update_real_class(), and ux_set_lock_timeout().
int tran_savepoint_internal (const char * savept_name, SAVEPOINT_TYPE savepoint_type)
Definition at line 1100 of file transaction_cl.c.
References ARG_FILE_LINE, assert, er_errid(), er_log_debug, er_msg(), locator_all_flush(), NO_ERROR, tran_add_savepoint(), tran_server_savepoint(), USER_SAVEPOINT, and ws_need_flush().
Referenced by db_savepoint_transaction_internal(), and tran_system_savepoint().
bool tran_set_check_interrupt (bool flag)
Definition at line 1346 of file transaction_cl.c.
References tm_Tran_check_interrupt.
Referenced by logtb_set_check_interrupt().
int tran_set_global_tran_info (int gtrid, void * info, int size)
Definition at line 639 of file transaction_cl.c.
References assert, er_errid(), NO_ERROR, and tran_server_set_global_tran_info().
Referenced by db_set_global_transaction_info().
void tran_set_latest_query_status (int end_query_result, int tran_state, int should_conn_reset)
Definition at line 1391 of file transaction_cl.c.
References ABORTED, assert, COMMITTED, NO_ERROR, QUERY_ENDED, RESET_REQUIRED, tm_Tran_latest_query_status, tran_reset_latest_query_status(), TRAN_UNACTIVE_ABORTED, TRAN_UNACTIVE_ABORTED_INFORMING_PARTICIPANTS, TRAN_UNACTIVE_COMMITTED, TRAN_UNACTIVE_COMMITTED_INFORMING_PARTICIPANTS, and tran_was_latest_query_committed().
Referenced by qmgr_execute_query().
void tran_set_query_timeout (int query_timeout)
Definition at line 1279 of file transaction_cl.c.
References query_timeout, tm_Query_begin, tm_Query_timeout, and tran_current_timemillis().
int tran_system_savepoint (const char * savept_name)
Definition at line 1070 of file transaction_cl.c.
References SYSTEM_SAVEPOINT, and tran_savepoint_internal().
Referenced by au_change_owner_method(), au_grant(), au_revoke(), check_merge_trigger(), check_trigger(), dbt_rename(), delete_list_by_oids(), do_alter(), do_alter_change_col_comment(), do_alter_change_default_cs_coll(), do_alter_change_tbl_comment(), do_alter_clause_change_attribute(), do_alter_index_comment(), do_alter_index_rebuild(), do_alter_index_status(), do_alter_one_clause_with_template(), do_alter_trigger(), do_alter_user(), do_check_internal_statements(), do_create_entity(), do_create_user(), do_delete(), do_drop(), do_drop_user(), do_execute_delete(), do_execute_merge(), do_execute_update(), do_grant(), do_merge(), do_rename(), do_revoke(), do_truncate(), do_update(), insert_local(), insert_subquery_results(), jsp_add_stored_procedure(), jsp_create_stored_procedure(), obt_update_internal(), sm_add_constraint(), sm_add_secondary_index_on_partition(), sm_delete_class_mop(), sm_drop_index(), sm_exist_index(), sm_rename_class(), sm_truncate_class(), tr_create_trigger(), tr_drop_trigger_internal(), tr_rename_trigger(), update_class(), and update_objs_for_list_file().
int tran_unilaterally_abort (void)
Definition at line 515 of file transaction_cl.c.
References ARG_FILE_LINE, CUB_MAXHOSTNAMELEN, ER_ERROR_SEVERITY, ER_LK_UNILATERALLY_ABORTED, er_set(), GETHOSTNAME, getuserid(), host, L_cuserid, NO_ERROR, NULL, pid, tm_Tran_index, tr_check_abort_triggers(), and tran_abort().
Referenced by sm_drop_index(), sm_exist_index(), tran_internal_abort_upto_savepoint(), and ws_abort_transaction().
bool tran_was_latest_query_aborted (void)
Definition at line 1457 of file transaction_cl.c.
References ABORTED, and tm_Tran_latest_query_status.
Referenced by do_commit_after_execute(), do_execute_statement(), do_statement(), tran_abort(), tran_commit(), and ux_auto_commit().
bool tran_was_latest_query_committed (void)
Definition at line 1447 of file transaction_cl.c.
References COMMITTED, and tm_Tran_latest_query_status.
Referenced by build_xasl_for_server_delete(), css_send_req_to_server(), do_commit_after_execute(), do_execute_delete(), do_execute_merge(), do_execute_update(), do_insert_at_server(), fetch_result(), tran_abort(), tran_commit(), tran_set_latest_query_status(), update_at_server(), and ux_auto_commit().
bool tran_was_latest_query_ended (void)
Definition at line 1437 of file transaction_cl.c.
References QUERY_ENDED, and tm_Tran_latest_query_status.
Referenced by db_query_end(), do_execute_merge(), do_merge(), pt_end_query(), tran_abort(), and tran_commit().
Variable Documentation
bool tm_Tran_async_ws
Definition at line 68 of file transaction_cl.c.
Referenced by tran_reset_isolation().
bool tm_Tran_check_interrupt
Definition at line 70 of file transaction_cl.c.
Referenced by tran_get_check_interrupt(), and tran_set_check_interrupt().
int tm_Tran_ID
Definition at line 71 of file transaction_cl.c.
int tm_Tran_index
Definition at line 66 of file transaction_cl.c.
Referenced by boot_initialize_client(), boot_restart_client(), boot_shutdown_client(), classobj_make_template(), css_client_init(), css_send_data_to_server(), css_send_error_to_server(), css_send_req_to_server(), css_send_req_to_server_2_data(), css_send_req_to_server_no_reply(), css_send_request_to_server_with_buffer(), isvalid_transaction(), make_template(), tran_2pc_attach_global_tran(), tran_cache_tran_settings(), tran_unilaterally_abort(), and validate_template().
int tm_Tran_invalidate_snapshot
Definition at line 72 of file transaction_cl.c.
Referenced by css_client_init(), css_send_data_to_server(), css_send_error_to_server(), css_send_req_to_server(), css_send_req_to_server_2_data(), css_send_req_to_server_no_reply(), css_send_request_to_server_with_buffer(), and db_invalidate_mvcc_snapshot_before_statement().
TRAN_ISOLATION tm_Tran_isolation
Definition at line 67 of file transaction_cl.c.
Referenced by tran_cache_tran_settings(), and tran_reset_isolation().
LC_FETCH_VERSION_TYPE tm_Tran_read_fetch_instance_version
Definition at line 78 of file transaction_cl.c.
Referenced by db_set_read_fetch_instance_version().
LOCK tm_Tran_rep_read_lock
Definition at line 73 of file transaction_cl.c.
Referenced by locator_find_lockhint_class_oids(), tran_abort(), tran_abort_only_client(), tran_commit(), and tran_lock_rep_read().
int tm_Tran_wait_msecs
Definition at line 69 of file transaction_cl.c.
Referenced by tran_cache_tran_settings(), and tran_reset_wait_times().
bool tm_Use_OID_preflush
Definition at line 226 of file transaction_cl.c.
Referenced by do_execute_select(), ldr_init_loader(), and tran_flush_to_commit().