CUBRID Engine: src/object/transform_cl.c File Reference
transform_cl.c File Reference
#include "config.h"
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include "porting.h"
#include "memory_alloc.h"
#include "error_manager.h"
#include "work_space.h"
#include "oid.h"
#include "object_representation.h"
#include "object_domain.h"
#include "object_primitive.h"
#include "class_object.h"
#include "set_object.h"
#include "transform.h"
#include "transform_cl.h"
#include "schema_manager.h"
#include "locator_cl.h"
#include "object_accessor.h"
#include "trigger_manager.h"
#include "locator.h"
#include "server_interface.h"
#include "execute_statement.h"
#include "db_json.hpp"
#include "dbtype.h"
Classes
struct or_tempoid
struct or_fixup
Macros
#define TF_FIXUP_REFERENCE_QUANT 32
Typedefs
typedef struct or_tempoid OR_TEMPOID
typedef struct or_fixup OR_FIXUP
typedef int(* LSIZER) (void *)
typedef void(* LWRITER) (void *, void *)
typedef DB_LIST *(* LREADER) (void *)
typedef void(* VREADER) (void *, void *)
Functions
static int optimize_sets (SM_CLASS *class_, MOBJ volatile obj)
static OR_FIXUP * tf_make_fixup (void)
static void tf_free_fixup (OR_FIXUP *fix)
static void fixup_callback (LC_OIDMAP *oidmap)
static int tf_do_fixup (OR_FIXUP *fix)
static int put_varinfo (OR_BUF *buf, char *obj, SM_CLASS *class_, int offset_size)
static int object_size (SM_CLASS *class_, MOBJ obj, int *offset_size_ptr)
static int put_attributes (OR_BUF *buf, char *obj, SM_CLASS *class_)
static char * get_current (OR_BUF *buf, SM_CLASS *class_, MOBJ *obj_ptr, int bound_bit_flag, int offset_size)
static SM_ATTRIBUTE * find_current_attribute (SM_CLASS *class_, int id)
static void clear_new_unbound (char *obj, SM_CLASS *class_, SM_REPRESENTATION *oldrep)
static char * get_old (OR_BUF *buf, SM_CLASS *class_, MOBJ *obj_ptr, int repid, int bound_bit_flag, int offset_size)
static char * unpack_allocator (int size)
static OR_VARINFO * read_var_table (OR_BUF *buf, int nvars)
static OR_VARINFO * read_var_table_internal (OR_BUF *buf, int nvars, int offset_size)
static void free_var_table (OR_VARINFO *vars)
static int string_disk_size (const char *string)
static char * get_string (OR_BUF *buf, int length)
static void put_string (OR_BUF *buf, const char *string)
static int object_set_size (DB_OBJLIST *list)
static int put_object_set (OR_BUF *buf, DB_OBJLIST *list)
static DB_OBJLIST * get_object_set (OR_BUF *buf, int expected)
static int substructure_set_size (DB_LIST *list, LSIZER function)
static void put_substructure_set (OR_BUF *buf, DB_LIST *list, LWRITER writer, OID *class_, int repid)
static DB_LIST * get_substructure_set (OR_BUF *buf, LREADER reader, int expected)
static void install_substructure_set (OR_BUF *buf, DB_LIST *list, VREADER reader, int expected)
static int property_list_size (DB_SEQ *properties)
static void put_property_list (OR_BUF *buf, DB_SEQ *properties)
static DB_SEQ * get_property_list (OR_BUF *buf, int expected_size)
static int domain_size (TP_DOMAIN *domain)
static void domain_to_disk (OR_BUF *buf, TP_DOMAIN *domain)
static TP_DOMAIN * disk_to_domain2 (OR_BUF *buf)
static TP_DOMAIN * disk_to_domain (OR_BUF *buf)
static void metharg_to_disk (OR_BUF *buf, SM_METHOD_ARGUMENT *arg)
static int metharg_size (SM_METHOD_ARGUMENT *arg)
static SM_METHOD_ARGUMENT * disk_to_metharg (OR_BUF *buf)
static int methsig_to_disk (OR_BUF *buf, SM_METHOD_SIGNATURE *sig)
static void methsig_to_disk_lwriter (void *buf, void *sig)
static int methsig_size (SM_METHOD_SIGNATURE *sig)
static SM_METHOD_SIGNATURE * disk_to_methsig (OR_BUF *buf)
static int method_to_disk (OR_BUF *buf, SM_METHOD *method)
static void method_to_disk_lwriter (void *buf, void *method)
static int method_size (SM_METHOD *method)
static void disk_to_method (OR_BUF *buf, SM_METHOD *method)
static int methfile_to_disk (OR_BUF *buf, SM_METHOD_FILE *file)
static void methfile_to_disk_lwriter (void *buf, void *file)
static int methfile_size (SM_METHOD_FILE *file)
static SM_METHOD_FILE * disk_to_methfile (OR_BUF *buf)
static int query_spec_to_disk (OR_BUF *buf, SM_QUERY_SPEC *query_spec)
static void query_spec_to_disk_lwriter (void *buf, void *query_spec)
static int query_spec_size (SM_QUERY_SPEC *statement)
static SM_QUERY_SPEC * disk_to_query_spec (OR_BUF *buf)
static int attribute_to_disk (OR_BUF *buf, SM_ATTRIBUTE *att)
static void attribute_to_disk_lwriter (void *buf, void *att)
static int attribute_size (SM_ATTRIBUTE *att)
static void disk_to_attribute (OR_BUF *buf, SM_ATTRIBUTE *att)
static int resolution_to_disk (OR_BUF *buf, SM_RESOLUTION *res)
static void resolution_to_disk_lwriter (void *buf, void *res)
static int resolution_size (SM_RESOLUTION *res)
static SM_RESOLUTION * disk_to_resolution (OR_BUF *buf)
static int repattribute_to_disk (OR_BUF *buf, SM_REPR_ATTRIBUTE *rat)
static void repattribute_to_disk_lwriter (void *buf, void *rat)
static int repattribute_size (SM_REPR_ATTRIBUTE *rat)
static SM_REPR_ATTRIBUTE * disk_to_repattribute (OR_BUF *buf)
static int representation_size (SM_REPRESENTATION *rep)
static int representation_to_disk (OR_BUF *buf, SM_REPRESENTATION *rep)
static void representation_to_disk_lwriter (void *buf, void *rep)
static SM_REPRESENTATION * disk_to_representation (OR_BUF *buf)
static int check_class_structure (SM_CLASS *class_)
static int put_class_varinfo (OR_BUF *buf, SM_CLASS *class_)
static void put_class_attributes (OR_BUF *buf, SM_CLASS *class_)
static void class_to_disk (OR_BUF *buf, SM_CLASS *class_)
static void tag_component_namespace (SM_COMPONENT *components, SM_NAME_SPACE name_space)
static SM_CLASS * disk_to_class (OR_BUF *buf, SM_CLASS **class_ptr)
static void root_to_disk (OR_BUF *buf, ROOT_CLASS *root)
static int root_size (MOBJ rootobj)
static int tf_class_size (MOBJ classobj)
static ROOT_CLASS * disk_to_root (OR_BUF *buf)
static int enumeration_size (const DB_ENUMERATION *enumeration)
static void put_enumeration (OR_BUF *buf, const DB_ENUMERATION *e)
static int get_enumeration (OR_BUF *buf, DB_ENUMERATION *enumeration, int expected)
static int tf_attribute_default_expr_to_property (SM_ATTRIBUTE *attr_list)
static int partition_info_to_disk (OR_BUF *buf, SM_PARTITION *partition_info)
static void partition_info_to_disk_lwriter (void *buf, void *partition_info)
static SM_PARTITION * disk_to_partition_info (OR_BUF *buf)
static int partition_info_size (SM_PARTITION *partition_info)
static void or_pack_mop (OR_BUF *buf, MOP mop)
static int tf_add_fixup (OR_FIXUP *fix, DB_OBJECT *obj, void *ref)
OID * tf_need_permanent_oid (or_buf *buf, DB_OBJECT *obj)
TF_STATUS tf_mem_to_disk (MOP classmop, MOBJ classobj, MOBJ volatile obj, RECDES *record, bool *index_flag)
MOBJ tf_disk_to_mem (MOBJ classobj, RECDES *record, int *convertp)
MOBJ tf_disk_to_class (OID *oid, RECDES *record)
TF_STATUS tf_class_to_disk (MOBJ classobj, RECDES *record)
int tf_object_size (MOBJ classobj, MOBJ obj)
Variables
int tf_Allow_fixups = 1
Macro Definition Documentation
#define TF_FIXUP_REFERENCE_QUANT 32
Definition at line 408 of file transform_cl.c.
Referenced by tf_add_fixup().
Typedef Documentation
typedef DB_LIST*(* LREADER) (void *)
Definition at line 122 of file transform_cl.c.
typedef int(* LSIZER) (void *)
Definition at line 120 of file transform_cl.c.
typedef void(* LWRITER) (void *, void *)
Definition at line 121 of file transform_cl.c.
typedef struct or_fixup OR_FIXUP
typedef struct or_tempoid OR_TEMPOID
typedef void(* VREADER) (void *, void *)
Definition at line 123 of file transform_cl.c.
Function Documentation
static int attribute_size (SM_ATTRIBUTE * att) static
Definition at line 2967 of file transform_cl.c.
References sm_attribute::comment, sm_attribute::default_value, sm_attribute::domain, domain_size(), sm_attribute::header, tf_meta_class::mc_fixed_size, tf_meta_class::mc_n_variable, sm_component::name, object_set_size(), or_packed_value_size(), OR_VAR_TABLE_SIZE, sm_default_value::original_value, sm_attribute::properties, property_list_size(), string_disk_size(), substructure_set_size(), tf_Metaclass_attribute, tr_get_cache_objects(), sm_attribute::triggers, and sm_default_value::value.
Referenced by put_class_varinfo(), and tf_class_size().
static int attribute_to_disk (OR_BUF * buf, SM_ATTRIBUTE * att) static
Definition at line 2863 of file transform_cl.c.
References ARG_FILE_LINE, sm_attribute::class_mop, sm_attribute::comment, sm_attribute::default_value, sm_attribute::domain, domain_size(), domain_to_disk(), ER_ERROR_SEVERITY, er_set(), ER_TF_OUT_OF_SYNC, sm_attribute::flags, sm_attribute::header, pr_type::id, sm_attribute::id, INT_ALIGNMENT, tf_meta_class::mc_classoid, tf_meta_class::mc_fixed_size, tf_meta_class::mc_n_variable, tf_meta_class::mc_repid, sm_component::name, NO_ERROR, NULL_FILEID, NULL_PAGEID, object_set_size(), or_pack_mop(), or_packed_value_size(), or_put_int(), or_put_offset(), or_put_value(), OR_VAR_TABLE_SIZE, sm_attribute::order, sm_default_value::original_value, sm_attribute::properties, property_list_size(), or_buf::ptr, PTR_ALIGN, put_object_set(), put_property_list(), put_string(), put_substructure_set(), string_disk_size(), substructure_set_size(), tf_Metaclass_attribute, tf_Metaclass_domain, tr_get_cache_objects(), sm_attribute::triggers, sm_attribute::type, and sm_default_value::value.
Referenced by attribute_to_disk_lwriter().
static void attribute_to_disk_lwriter (void * buf, void * att) inline static
Definition at line 2956 of file transform_cl.c.
References attribute_to_disk(), and STATIC_CAST.
Referenced by put_class_attributes().
static int check_class_structure (SM_CLASS * class_) static
Definition at line 3545 of file transform_cl.c.
Referenced by class_to_disk(), and tf_class_size().
static void class_to_disk (OR_BUF * buf, SM_CLASS * class_) static
Definition at line 3761 of file transform_cl.c.
References ARG_FILE_LINE, check_class_structure(), ER_ERROR_SEVERITY, er_set(), ER_TF_OUT_OF_SYNC, or_abort(), OR_NON_MVCC_HEADER_SIZE, or_buf::ptr, put_class_attributes(), and put_class_varinfo().
Referenced by tf_class_to_disk().
static void clear_new_unbound (char * obj, SM_CLASS * class_, SM_REPRESENTATION * oldrep) static
Definition at line 1054 of file transform_cl.c.
References sm_repr_attribute::attid, sm_representation::attributes, sm_class::attributes, DB_IS_NULL, sm_attribute::default_value, sm_attribute::domain, sm_attribute::header, sm_attribute::id, pr_type::initmem(), sm_component::next, sm_repr_attribute::next, NULL, OBJ_SET_BOUND_BIT, sm_attribute::offset, sm_default_value::original_value, pr_type::setmem(), sm_attribute::storage_order, sm_attribute::type, and pr_type::variable_p.
Referenced by get_old().
static void disk_to_attribute (OR_BUF * buf, SM_ATTRIBUTE * att) static
Definition at line 3001 of file transform_cl.c.
References assert, sm_attribute::auto_increment, sm_attribute::class_mop, classobj_get_prop(), classobj_initialize_default_expr(), sm_attribute::comment, sm_attribute::constraints, pr_type::data_readval(), DB_DEFAULT_NONE, db_get_int(), db_get_object(), db_get_set(), db_get_string(), DB_TYPE_ENUMERATION, DB_TYPE_INTEGER, DB_TYPE_NULL, DB_TYPE_SEQUENCE, db_value_is_null(), db_value_put_null(), DB_VALUE_TYPE, db_value_type(), sm_default_value::default_expr, db_default_expr::default_expr_format, db_default_expr::default_expr_op, db_default_expr::default_expr_type, sm_attribute::default_value, disk_to_domain(), sm_attribute::domain, er_errid(), sm_attribute::flags, free_var_table(), get_object_set(), get_property_list(), get_string(), get_substructure_set(), sm_attribute::header, pr_type::id, sm_attribute::id, ID_NULL, or_varinfo::length, tf_meta_class::mc_n_variable, sm_component::name, sm_component::name_space, NO_ERROR, NULL, sm_attribute::offset, sm_attribute::on_update_default_expr, or_abort(), or_get_int(), or_get_value(), ORC_ATT_COMMENT_INDEX, ORC_ATT_CURRENT_VALUE_INDEX, ORC_ATT_DOMAIN_INDEX, ORC_ATT_NAME_INDEX, ORC_ATT_ORIGINAL_VALUE_INDEX, ORC_ATT_PROPERTIES_INDEX, ORC_ATT_TRIGGER_INDEX, sm_attribute::order, sm_attribute::order_link, sm_default_value::original_value, pr_clear_value(), pr_complete_enum_value(), pr_type_from_id(), sm_attribute::properties, rc, read_var_table(), set_get_element_nocopy(), set_size(), T_TO_CHAR, tf_Metaclass_attribute, TP_IS_CHAR_TYPE, tp_Object, TR_CACHE_ATTRIBUTE, tr_make_schema_cache(), sm_attribute::triggers, tp_domain::type, sm_attribute::type, sm_default_value::value, and ws_copy_string().
Referenced by disk_to_class().
static SM_CLASS * disk_to_class (OR_BUF * buf, SM_CLASS ** class_ptr) static
Definition at line 3976 of file transform_cl.c.
References ARG_FILE_LINE, assert, ASSERT_ERROR, sm_class::att_ids, sm_attribute::auto_increment, AUTO_INCREMENT_SERIAL_NAME_MAX_LENGTH, sm_class_header::ch_heap, sm_class_header::ch_rep_dir, classobj_alloc_threaded_array(), classobj_fixup_loaded_class(), classobj_free_class(), classobj_initialize_attributes(), classobj_initialize_methods(), classobj_make_class(), CT_SERIAL_NAME, pr_type::data_readval(), db_get_object(), db_ws_free(), disk_to_attribute(), disk_to_methfile(), disk_to_method(), disk_to_partition_info(), disk_to_query_spec(), disk_to_representation(), disk_to_resolution(), do_get_serial_obj_id(), ER_ERROR_SEVERITY, ER_OBJ_INVALID_ATTRIBUTE, er_set(), vfid::fileid, sm_attribute::flags, free_var_table(), get_object_set(), get_property_list(), get_string(), get_substructure_set(), sm_attribute::header, sm_class::header, HFID_IS_NULL, hfid::hpgid, ID_ATTRIBUTE, ID_CLASS_ATTRIBUTE, ID_CLASS_METHOD, ID_METHOD, ID_SHARED_ATTRIBUTE, install_substructure_set(), or_varinfo::length, tf_meta_class::mc_n_variable, sm_class::method_ids, sm_component::name, sm_component::next, NO_ERROR, NULL, OID_ISNULL, on_error, or_abort(), or_get_int(), or_get_oid(), ORC_ATTRIBUTES_INDEX, ORC_CLASS_ATTRS_INDEX, ORC_CLASS_METHODS_INDEX, ORC_COMMENT_INDEX, ORC_LOADER_COMMANDS_INDEX, ORC_METHOD_FILES_INDEX, ORC_METHODS_INDEX, ORC_NAME_INDEX, ORC_PARTITION_INDEX, ORC_PROPERTIES_INDEX, ORC_QUERY_SPEC_INDEX, ORC_REPRESENTATIONS_INDEX, ORC_RESOLUTIONS_INDEX, ORC_SHARED_ATTRS_INDEX, ORC_SUBCLASSES_INDEX, ORC_SUPERCLASSES_INDEX, ORC_TRIGGERS_INDEX, rc, read_var_table(), SET_AUTO_INCREMENT_SERIAL_NAME, SM_ATTFLAG_AUTO_INCREMENT, sm_ch_heap(), sm_ch_name(), sm_ch_rep_dir(), sm_find_class(), tag_component_namespace(), tf_Metaclass_class, tp_Object, TR_CACHE_CLASS, tr_make_schema_cache(), hfid::vfid, and vfid::volid.
Referenced by tf_disk_to_class().
static TP_DOMAIN * disk_to_domain (OR_BUF * buf) static
Definition at line 2239 of file transform_cl.c.
References disk_to_domain2(), NULL, and tp_domain_cache().
Referenced by disk_to_attribute(), disk_to_metharg(), and disk_to_repattribute().
static TP_DOMAIN * disk_to_domain2 (OR_BUF * buf) static
Definition at line 2130 of file transform_cl.c.
References ARG_FILE_LINE, assert, assert_release, tp_domain::class_mop, tp_domain::class_oid, tp_domain::codeset, tp_domain::collation_id, db_enumeration::collation_id, pr_type::data_readmem(), db_json_load_validator(), db_private_free_and_init, DB_TYPE_ENUMERATION, DOM_GET_ENUMERATION, tp_domain::enumeration, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_var_table(), get_enumeration(), get_substructure_set(), INTL_CODESET_ISO88591, tp_domain::json_validator, LANG_COLL_ISO_BINARY, or_varinfo::length, tf_meta_class::mc_n_variable, NO_ERROR, NULL, OID_ISNULL, or_abort(), or_get_int(), or_get_json_schema(), ORC_DOMAIN_ENUMERATION_INDEX, ORC_DOMAIN_SCHEMA_JSON_OFFSET, ORC_DOMAIN_SETDOMAIN_INDEX, tp_domain::precision, rc, read_var_table(), tp_domain::scale, tp_domain::setdomain, tf_Metaclass_domain, tp_domain_free(), tp_domain_new(), tp_Oid, and ws_mop().
Referenced by disk_to_domain().
static SM_METHOD_ARGUMENT * disk_to_metharg (OR_BUF * buf) static
Definition at line 2323 of file transform_cl.c.
References classobj_make_method_arg(), DB_TYPE_NULL, disk_to_domain(), sm_method_argument::domain, free_var_table(), get_substructure_set(), sm_method_argument::index, or_varinfo::length, tf_meta_class::mc_n_variable, NO_ERROR, NULL, or_abort(), or_get_int(), ORC_METHARG_DOMAIN_INDEX, pr_type_from_id(), rc, read_var_table(), tf_Metaclass_metharg, and sm_method_argument::type.
Referenced by disk_to_methsig().
static SM_METHOD_FILE * disk_to_methfile (OR_BUF * buf) static
Definition at line 2719 of file transform_cl.c.
References sm_method_file::class_mop, classobj_make_method_file(), pr_type::data_readval(), db_get_object(), free_var_table(), get_property_list(), get_string(), tf_meta_class::mc_n_variable, sm_method_file::name, NULL, or_abort(), ORC_METHFILE_NAME_INDEX, ORC_METHFILE_PROPERTIES_INDEX, read_var_table(), set_free(), tf_Metaclass_methfile, and tp_Object.
Referenced by disk_to_class().
static void disk_to_method (OR_BUF * buf, SM_METHOD * method) static
Definition at line 2600 of file transform_cl.c.
References sm_method::class_mop, pr_type::data_readval(), db_get_object(), disk_to_methsig(), free_var_table(), sm_method::function, get_property_list(), get_string(), get_substructure_set(), sm_method::header, sm_method::id, ID_NULL, or_varinfo::length, tf_meta_class::mc_n_variable, sm_component::name, sm_component::name_space, NO_ERROR, NULL, or_abort(), or_get_int(), ORC_METHOD_NAME_INDEX, ORC_METHOD_PROPERTIES_INDEX, ORC_METHOD_SIGNATURE_INDEX, sm_method::properties, rc, read_var_table(), sm_method::signatures, tf_Metaclass_method, and tp_Object.
Referenced by disk_to_class().
static SM_METHOD_SIGNATURE * disk_to_methsig (OR_BUF * buf) static
Definition at line 2448 of file transform_cl.c.
References sm_method_signature::args, classobj_make_method_signature(), disk_to_metharg(), free_var_table(), sm_method_signature::function_name, get_string(), get_substructure_set(), or_varinfo::length, tf_meta_class::mc_n_variable, NO_ERROR, NULL, sm_method_signature::num_args, or_abort(), or_get_int(), ORC_METHSIG_ARGUMENTS_INDEX, ORC_METHSIG_FUNCTION_NAME_INDEX, ORC_METHSIG_RETURN_VALUE_INDEX, ORC_METHSIG_SQL_DEF_INDEX, rc, read_var_table(), sm_method_signature::sql_definition, tf_Metaclass_methsig, sm_method_signature::value, ws_copy_string(), and ws_free_string().
Referenced by disk_to_method().
static SM_PARTITION * disk_to_partition_info (OR_BUF * buf) static
Definition at line 4954 of file transform_cl.c.
References assert, classobj_free_partition_info(), classobj_make_partition_info(), sm_partition::comment, db_get_set(), db_seq_copy(), sm_partition::expr, free_var_table(), get_string(), tf_meta_class::mc_n_variable, NO_ERROR, NULL, or_abort(), or_get_int(), or_get_value(), ORC_PARTITION_COMMENT_INDEX, ORC_PARTITION_EXPR_INDEX, ORC_PARTITION_NAME_INDEX, ORC_PARTITION_VALUES_INDEX, sm_partition::partition_type, sm_partition::pname, pr_clear_value(), read_var_table(), tf_Metaclass_partition, and sm_partition::values.
Referenced by disk_to_class().
static SM_QUERY_SPEC * disk_to_query_spec (OR_BUF * buf) static
Definition at line 2826 of file transform_cl.c.
References classobj_make_query_spec(), free_var_table(), get_string(), tf_meta_class::mc_n_variable, NULL, or_abort(), ORC_QUERY_SPEC_SPEC_INDEX, read_var_table(), sm_query_spec::specification, and tf_Metaclass_query_spec.
Referenced by disk_to_class().
static SM_REPR_ATTRIBUTE * disk_to_repattribute (OR_BUF * buf) static
Definition at line 3372 of file transform_cl.c.
References classobj_make_repattribute(), disk_to_domain(), sm_repr_attribute::domain, free_var_table(), get_substructure_set(), or_varinfo::length, tf_meta_class::mc_n_variable, NO_ERROR, NULL, or_abort(), or_get_int(), ORC_REPATT_DOMAIN_INDEX, rc, read_var_table(), and tf_Metaclass_repattribute.
Referenced by disk_to_representation().
static SM_REPRESENTATION * disk_to_representation (OR_BUF * buf) static
Definition at line 3484 of file transform_cl.c.
References sm_representation::attributes, classobj_make_representation(), disk_to_repattribute(), sm_representation::fixed_count, free_var_table(), get_property_list(), get_substructure_set(), sm_representation::id, or_varinfo::length, tf_meta_class::mc_n_variable, NO_ERROR, NULL, or_abort(), or_get_int(), ORC_REP_ATTRIBUTES_INDEX, ORC_REP_PROPERTIES_INDEX, rc, read_var_table(), set_free(), tf_Metaclass_representation, and sm_representation::variable_count.
Referenced by disk_to_class().
static SM_RESOLUTION * disk_to_resolution (OR_BUF * buf) static
Definition at line 3254 of file transform_cl.c.
References sm_resolution::alias, sm_resolution::class_mop, classobj_make_resolution(), pr_type::data_readval(), db_get_object(), free_var_table(), get_string(), tf_meta_class::mc_n_variable, sm_resolution::name, NULL, or_abort(), or_get_int(), ORC_RES_ALIAS_INDEX, ORC_RES_NAME_INDEX, rc, read_var_table(), tf_Metaclass_resolution, tp_Object, and tp_VarNChar.
Referenced by disk_to_class().
static ROOT_CLASS * disk_to_root (OR_BUF * buf) static
Definition at line 4288 of file transform_cl.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, er_set(), ER_TF_OUT_OF_SYNC, free_var_table(), tf_meta_class::mc_n_variable, NO_ERROR, NULL, OID_ISNULL, or_abort(), or_advance(), or_get_int(), OR_NON_MVCC_HEADER_SIZE, or_buf::ptr, rc, read_var_table(), sm_ch_rep_dir(), sm_Root_class, and tf_Metaclass_root.
Referenced by tf_disk_to_class().
static int domain_size (TP_DOMAIN * domain) static
Definition at line 2037 of file transform_cl.c.
References db_json_get_schema_raw_from_validator(), DOM_GET_ENUMERATION, enumeration_size(), tp_domain::json_validator, tf_meta_class::mc_fixed_size, tf_meta_class::mc_n_variable, NULL, OR_VAR_TABLE_SIZE, tp_domain::setdomain, string_disk_size(), substructure_set_size(), and tf_Metaclass_domain.
Referenced by attribute_size(), attribute_to_disk(), btree_add_index(), btree_load_index(), domain_to_disk(), locator_check_fk_validity(), metharg_size(), metharg_to_disk(), repattribute_size(), and repattribute_to_disk().
static void domain_to_disk (OR_BUF * buf, TP_DOMAIN * domain) static
Definition at line 2063 of file transform_cl.c.
References ARG_FILE_LINE, assert, tp_domain::class_mop, tp_domain::codeset, tp_domain::collation_id, pr_type::data_writeval(), db_json_get_schema_raw_from_validator(), db_make_string(), DOM_GET_ENUMERATION, domain_size(), enumeration_size(), ER_ERROR_SEVERITY, er_set(), ER_TF_OUT_OF_SYNC, INT_ALIGNMENT, tp_domain::json_validator, tf_meta_class::mc_classoid, tf_meta_class::mc_fixed_size, tf_meta_class::mc_n_variable, tf_meta_class::mc_repid, NULL, or_pack_mop(), or_put_int(), or_put_offset(), OR_VAR_TABLE_SIZE, pr_clear_value(), tp_domain::precision, or_buf::ptr, PTR_ALIGN, put_enumeration(), put_substructure_set(), tp_domain::scale, tp_domain::setdomain, string_disk_size(), substructure_set_size(), tf_Metaclass_domain, TP_DOMAIN_COLL_NORMAL, TP_DOMAIN_COLLATION_FLAG, TP_DOMAIN_TYPE, and tp_String.
Referenced by attribute_to_disk(), metharg_to_disk(), and repattribute_to_disk().
static int enumeration_size (const DB_ENUMERATION * enumeration) static
Definition at line 4589 of file transform_cl.c.
References or_packed_enumeration_size().
Referenced by domain_size(), and domain_to_disk().
static SM_ATTRIBUTE * find_current_attribute (SM_CLASS * class_, int id) static
Definition at line 1023 of file transform_cl.c.
References sm_class::attributes, sm_attribute::header, sm_attribute::id, sm_component::next, and NULL.
Referenced by get_old().
static void fixup_callback (LC_OIDMAP * oidmap) static
Definition at line 572 of file transform_cl.c.
References lc_oidmap::client_data, i, if(), NULL, lc_oidmap::oid, OR_PUT_OID, or_tempoid::refcount, and or_tempoid::references.
Referenced by tf_do_fixup().
static void free_var_table (OR_VARINFO * vars) static
Definition at line 1456 of file transform_cl.c.
References free_and_init, and NULL.
Referenced by disk_to_attribute(), disk_to_class(), disk_to_domain2(), disk_to_metharg(), disk_to_methfile(), disk_to_method(), disk_to_methsig(), disk_to_partition_info(), disk_to_query_spec(), disk_to_repattribute(), disk_to_representation(), disk_to_resolution(), and disk_to_root().
static char * get_current (OR_BUF * buf, SM_CLASS * class_, MOBJ * obj_ptr, int bound_bit_flag, int offset_size) static
Definition at line 925 of file transform_cl.c.
References sm_class::attributes, pr_type::data_readmem(), db_ws_alloc(), db_ws_free(), sm_attribute::domain, sm_class::fixed_count, sm_class::fixed_size, i, INT_ALIGNMENT, NO_ERROR, NULL, obj_alloc(), OBJ_HEADER_BOUND_BITS_OFFSET, sm_attribute::offset, or_abort(), or_advance(), OR_BOUND_BIT_BYTES, or_get_data(), or_get_offset_internal(), or_buf::ptr, PTR_ALIGN, rc, sm_attribute::type, and sm_class::variable_count.
Referenced by tf_disk_to_mem().
static int get_enumeration (OR_BUF * buf, DB_ENUMERATION * enumeration, int expected) static
Definition at line 4613 of file transform_cl.c.
References db_enumeration::count, db_enumeration::elements, NO_ERROR, NULL, and or_get_enumeration().
Referenced by disk_to_domain2().
static DB_OBJLIST * get_object_set (OR_BUF * buf, int expected) static
Definition at line 1713 of file transform_cl.c.
References cubregex::count(), pr_type::data_readval(), db_get_object(), i, ml_append(), NULL, or_abort(), or_skip_set_header(), and tp_Object.
Referenced by disk_to_attribute(), and disk_to_class().
static char * get_old (OR_BUF * buf, SM_CLASS * class_, MOBJ * obj_ptr, int repid, int bound_bit_flag, int offset_size) static
Definition at line 1103 of file transform_cl.c.
References ARG_FILE_LINE, sm_repr_attribute::attid, sm_representation::attributes, classobj_find_representation(), clear_new_unbound(), pr_type::data_readmem(), DB_ATT_ALIGN, db_ws_alloc(), db_ws_free(), sm_attribute::domain, or_buf::endptr, ER_ERROR_SEVERITY, er_set(), ER_TF_INVALID_REPRESENTATION, find_current_attribute(), sm_representation::fixed_count, i, INT_ALIGNMENT, sm_repr_attribute::next, NO_ERROR, NULL, obj_alloc(), OBJ_SET_BOUND_BIT, or_abort(), or_advance(), OR_BOUND_BIT_BYTES, OR_GET_BOUND_BIT, or_get_offset_internal(), or_overflow(), pr_type_from_id(), or_buf::ptr, PTR_ALIGN, rc, sm_ch_name(), and sm_representation::variable_count.
Referenced by tf_disk_to_mem().
static DB_SEQ * get_property_list (OR_BUF * buf, int expected_size) static
Definition at line 2000 of file transform_cl.c.
References pr_type::data_readval(), db_get_set(), max, NULL, or_abort(), set_free(), set_size(), and tp_Sequence.
Referenced by disk_to_attribute(), disk_to_class(), disk_to_methfile(), disk_to_method(), and disk_to_representation().
static char * get_string (OR_BUF * buf, int length) static
Definition at line 1512 of file transform_cl.c.
References tp_domain::codeset, tp_domain::collation_flag, tp_domain::collation_id, pr_type::data_readval(), db_get_string(), db_make_null(), DB_MAX_VARNCHAR_PRECISION, DB_TYPE_VARNCHAR, db_value_clear(), DB_VALUE_TYPE, lang_charset(), LANG_SYS_COLLATION, NULL, tp_domain::precision, TP_DOMAIN_COLL_NORMAL, tp_VarNChar, and ws_copy_string().
Referenced by disk_to_attribute(), disk_to_class(), disk_to_methfile(), disk_to_method(), disk_to_methsig(), disk_to_partition_info(), disk_to_query_spec(), and disk_to_resolution().
static DB_LIST * get_substructure_set (OR_BUF * buf, LREADER reader, int expected) static
Definition at line 1875 of file transform_cl.c.
References cubregex::count(), i, NULL, or_abort(), or_skip_set_header(), and WS_LIST_APPEND.
Referenced by disk_to_attribute(), disk_to_class(), disk_to_domain2(), disk_to_metharg(), disk_to_method(), disk_to_methsig(), disk_to_repattribute(), and disk_to_representation().
static void install_substructure_set (OR_BUF * buf, DB_LIST * list, VREADER reader, int expected) static
Definition at line 1917 of file transform_cl.c.
References cubregex::count(), i, db_list::next, NULL, or_skip_set_header(), and p.
Referenced by disk_to_class().
static int metharg_size (SM_METHOD_ARGUMENT * arg) static
Definition at line 2306 of file transform_cl.c.
References sm_method_argument::domain, domain_size(), tf_meta_class::mc_fixed_size, tf_meta_class::mc_n_variable, OR_VAR_TABLE_SIZE, substructure_set_size(), and tf_Metaclass_metharg.
Referenced by methsig_size(), and methsig_to_disk().
static void metharg_to_disk (OR_BUF * buf, SM_METHOD_ARGUMENT * arg) static
Definition at line 2264 of file transform_cl.c.
References ARG_FILE_LINE, DB_TYPE_NULL, sm_method_argument::domain, domain_size(), domain_to_disk(), ER_ERROR_SEVERITY, er_set(), ER_TF_OUT_OF_SYNC, pr_type::id, sm_method_argument::index, INT_ALIGNMENT, tf_meta_class::mc_classoid, tf_meta_class::mc_fixed_size, tf_meta_class::mc_n_variable, tf_meta_class::mc_repid, NULL, or_put_int(), or_put_offset(), OR_VAR_TABLE_SIZE, or_buf::ptr, PTR_ALIGN, put_substructure_set(), substructure_set_size(), tf_Metaclass_domain, tf_Metaclass_metharg, and sm_method_argument::type.
Referenced by methsig_to_disk().
static int methfile_size (SM_METHOD_FILE * file) static
Definition at line 2699 of file transform_cl.c.
References tf_meta_class::mc_fixed_size, tf_meta_class::mc_n_variable, sm_method_file::name, NULL, OR_VAR_TABLE_SIZE, property_list_size(), string_disk_size(), and tf_Metaclass_methfile.
Referenced by put_class_varinfo(), and tf_class_size().
static int methfile_to_disk (OR_BUF * buf, SM_METHOD_FILE * file) static
Definition at line 2646 of file transform_cl.c.
References ARG_FILE_LINE, sm_method_file::class_mop, ER_ERROR_SEVERITY, er_set(), ER_TF_OUT_OF_SYNC, INT_ALIGNMENT, tf_meta_class::mc_fixed_size, tf_meta_class::mc_n_variable, sm_method_file::name, NO_ERROR, NULL, or_pack_mop(), or_put_offset(), OR_VAR_TABLE_SIZE, property_list_size(), or_buf::ptr, PTR_ALIGN, put_property_list(), put_string(), string_disk_size(), and tf_Metaclass_methfile.
Referenced by methfile_to_disk_lwriter().
static void methfile_to_disk_lwriter (void * buf, void * file) inline static
Definition at line 2688 of file transform_cl.c.
References methfile_to_disk(), and STATIC_CAST.
Referenced by put_class_attributes().
static int method_size (SM_METHOD * method) static
Definition at line 2578 of file transform_cl.c.
References sm_method::header, tf_meta_class::mc_fixed_size, tf_meta_class::mc_n_variable, methsig_size(), sm_component::name, OR_VAR_TABLE_SIZE, sm_method::properties, property_list_size(), sm_method::signatures, string_disk_size(), substructure_set_size(), and tf_Metaclass_method.
Referenced by put_class_varinfo(), and tf_class_size().
static int method_to_disk (OR_BUF * buf, SM_METHOD * method) static
Definition at line 2518 of file transform_cl.c.
References ARG_FILE_LINE, sm_method::class_mop, ER_ERROR_SEVERITY, er_set(), ER_TF_OUT_OF_SYNC, sm_method::header, sm_method::id, INT_ALIGNMENT, tf_meta_class::mc_classoid, tf_meta_class::mc_fixed_size, tf_meta_class::mc_n_variable, tf_meta_class::mc_repid, methsig_size(), methsig_to_disk_lwriter(), sm_component::name, NO_ERROR, or_pack_mop(), or_put_int(), or_put_offset(), OR_VAR_TABLE_SIZE, sm_method::properties, property_list_size(), or_buf::ptr, PTR_ALIGN, put_property_list(), put_string(), put_substructure_set(), sm_method::signatures, string_disk_size(), substructure_set_size(), tf_Metaclass_method, and tf_Metaclass_methsig.
Referenced by method_to_disk_lwriter().
static void method_to_disk_lwriter (void * buf, void * method) inline static
Definition at line 2567 of file transform_cl.c.
References method_to_disk(), and STATIC_CAST.
Referenced by put_class_attributes().
static int methsig_size (SM_METHOD_SIGNATURE * sig) static
Definition at line 2428 of file transform_cl.c.
References sm_method_signature::args, sm_method_signature::function_name, tf_meta_class::mc_fixed_size, tf_meta_class::mc_n_variable, metharg_size(), OR_VAR_TABLE_SIZE, sm_method_signature::sql_definition, string_disk_size(), substructure_set_size(), tf_Metaclass_methsig, and sm_method_signature::value.
Referenced by method_size(), and method_to_disk().
static int methsig_to_disk (OR_BUF * buf, SM_METHOD_SIGNATURE * sig) static
Definition at line 2372 of file transform_cl.c.
References ARG_FILE_LINE, sm_method_signature::args, ER_ERROR_SEVERITY, er_set(), ER_TF_OUT_OF_SYNC, sm_method_signature::function_name, INT_ALIGNMENT, tf_meta_class::mc_classoid, tf_meta_class::mc_fixed_size, tf_meta_class::mc_n_variable, tf_meta_class::mc_repid, metharg_size(), metharg_to_disk(), NO_ERROR, sm_method_signature::num_args, or_put_int(), or_put_offset(), OR_VAR_TABLE_SIZE, or_buf::ptr, PTR_ALIGN, put_string(), put_substructure_set(), sm_method_signature::sql_definition, string_disk_size(), substructure_set_size(), tf_Metaclass_metharg, tf_Metaclass_methsig, and sm_method_signature::value.
Referenced by methsig_to_disk_lwriter().
static void methsig_to_disk_lwriter (void * buf, void * sig) inline static
Definition at line 2417 of file transform_cl.c.
References methsig_to_disk(), and STATIC_CAST.
Referenced by method_to_disk().
static int object_set_size (DB_OBJLIST * list) static
Definition at line 1597 of file transform_cl.c.
References cubregex::count(), pr_type::disksize, db_objlist::next, NULL, db_objlist::op, OR_INT_SIZE, OR_SET_HEADER_SIZE, tp_Object, and WS_IS_DELETED.
Referenced by attribute_size(), attribute_to_disk(), put_class_varinfo(), and tf_class_size().
static int object_size (SM_CLASS * class_, MOBJ obj, int * offset_size_ptr) static
Definition at line 655 of file transform_cl.c.
References sm_class::attributes, BIG_VAR_OFFSET_SIZE, sm_attribute::domain, sm_class::fixed_count, sm_class::fixed_size, pr_type::get_disk_size_of_mem(), sm_attribute::offset, OR_BOUND_BIT_BYTES, OR_BYTE_SIZE, OR_MAX_BYTE, OR_MAX_SHORT, OR_MVCC_INSERT_HEADER_SIZE, OR_SHORT_SIZE, OR_VAR_TABLE_SIZE_INTERNAL, tp_domain::type, and sm_class::variable_count.
Referenced by btree_record_remove_last_object(), tf_mem_to_disk(), and tf_object_size().
static int optimize_sets (SM_CLASS * class_, MOBJ volatile obj) static
Definition at line 310 of file transform_cl.c.
References sm_class::attributes, sm_attribute::domain, error(), sm_attribute::header, sm_component::next, NO_ERROR, NULL, sm_attribute::offset, setobj_sort(), TP_DOMAIN_TYPE, and TP_IS_SET_TYPE.
Referenced by tf_mem_to_disk().
static void or_pack_mop (OR_BUF * buf, MOP mop) static
Definition at line 1643 of file transform_cl.c.
References pr_type::data_writeval(), db_make_object(), pr_type::initval(), NULL, pr_type::setval(), and tp_Object.
Referenced by attribute_to_disk(), domain_to_disk(), methfile_to_disk(), method_to_disk(), put_class_attributes(), put_object_set(), and resolution_to_disk().
static int partition_info_size (SM_PARTITION * partition_info) static
Definition at line 4930 of file transform_cl.c.
References sm_partition::comment, db_make_sequence(), sm_partition::expr, tf_meta_class::mc_fixed_size, tf_meta_class::mc_n_variable, or_packed_value_size(), OR_VAR_TABLE_SIZE, sm_partition::pname, string_disk_size(), tf_Metaclass_partition, and sm_partition::values.
Referenced by put_class_varinfo(), and tf_class_size().
static int partition_info_to_disk (OR_BUF * buf, SM_PARTITION * partition_info) static
Definition at line 4873 of file transform_cl.c.
References ARG_FILE_LINE, sm_partition::comment, db_make_sequence(), ER_ERROR_SEVERITY, er_set(), ER_TF_OUT_OF_SYNC, sm_partition::expr, INT_ALIGNMENT, tf_meta_class::mc_fixed_size, tf_meta_class::mc_n_variable, NO_ERROR, or_packed_value_size(), or_put_int(), or_put_offset(), or_put_value(), OR_VAR_TABLE_SIZE, sm_partition::partition_type, sm_partition::pname, or_buf::ptr, PTR_ALIGN, put_string(), string_disk_size(), tf_Metaclass_partition, and sm_partition::values.
Referenced by partition_info_to_disk_lwriter().
static void partition_info_to_disk_lwriter (void * buf, void * partition_info) inline static
Definition at line 4919 of file transform_cl.c.
References partition_info_to_disk(), and STATIC_CAST.
Referenced by put_class_attributes().
static int property_list_size (DB_SEQ * properties) static
Definition at line 1939 of file transform_cl.c.
References db_make_sequence(), pr_type::get_disk_size_of_value(), max, NULL, set_size(), and tp_Sequence.
Referenced by attribute_size(), attribute_to_disk(), methfile_size(), methfile_to_disk(), method_size(), method_to_disk(), put_class_varinfo(), representation_size(), representation_to_disk(), and tf_class_size().
static int put_attributes (OR_BUF * buf, char * obj, SM_CLASS * class_) static
Definition at line 706 of file transform_cl.c.
References ARG_FILE_LINE, sm_class::attributes, pr_type::data_writemem(), sm_attribute::domain, ER_ERROR_SEVERITY, er_set(), ER_SM_CORRUPTED, sm_class::fixed_count, sm_class::fixed_size, sm_attribute::header, sm_component::next, NO_ERROR, NULL, OBJ_HEADER_BOUND_BITS_OFFSET, sm_attribute::offset, or_abort(), OR_BOUND_BIT_BYTES, or_pad(), or_put_data(), or_buf::ptr, sm_attribute::type, and pr_type::variable_p.
Referenced by tf_mem_to_disk().
static void put_class_attributes (OR_BUF * buf, SM_CLASS * class_) static
Definition at line 3656 of file transform_cl.c.
References assert, attribute_to_disk_lwriter(), HFID_IS_NULL, tf_meta_class::mc_classoid, tf_meta_class::mc_repid, methfile_to_disk_lwriter(), method_to_disk_lwriter(), OID_ISNULL, or_pack_mop(), or_put_int(), or_put_oid(), partition_info_to_disk_lwriter(), put_object_set(), put_property_list(), put_string(), put_substructure_set(), query_spec_to_disk_lwriter(), representation_to_disk_lwriter(), resolution_to_disk_lwriter(), sm_ch_heap(), sm_ch_name(), sm_ch_rep_dir(), tf_Metaclass_attribute, tf_Metaclass_methfile, tf_Metaclass_method, tf_Metaclass_partition, tf_Metaclass_query_spec, tf_Metaclass_representation, tf_Metaclass_resolution, and tr_get_cache_objects().
Referenced by class_to_disk().
static int put_class_varinfo (OR_BUF * buf, SM_CLASS * class_) static
Definition at line 3569 of file transform_cl.c.
References attribute_size(), INT_ALIGNMENT, tf_meta_class::mc_fixed_size, tf_meta_class::mc_n_variable, methfile_size(), method_size(), object_set_size(), or_put_offset(), OR_VAR_TABLE_SIZE, partition_info_size(), property_list_size(), or_buf::ptr, PTR_ALIGN, query_spec_size(), representation_size(), resolution_size(), sm_ch_name(), string_disk_size(), substructure_set_size(), tf_Metaclass_class, and tr_get_cache_objects().
Referenced by class_to_disk().
static void put_enumeration (OR_BUF * buf, const DB_ENUMERATION * e) static
Definition at line 4600 of file transform_cl.c.
References or_put_enumeration().
Referenced by domain_to_disk().
static int put_object_set (OR_BUF * buf, DB_OBJLIST * list) static
Definition at line 1662 of file transform_cl.c.
References cubregex::count(), DB_TYPE_SEQUENCE, ER_FAILED, db_objlist::next, NO_ERROR, NULL, db_objlist::op, OR_INT_SIZE, or_pack_mop(), or_put_domain(), or_put_int(), or_put_set_header(), tp_Object_domain, and WS_IS_DELETED.
Referenced by attribute_to_disk(), and put_class_attributes().
static void put_property_list (OR_BUF * buf, DB_SEQ * properties) static
Definition at line 1965 of file transform_cl.c.
References pr_type::data_writeval(), db_make_sequence(), max, NULL, set_size(), and tp_Sequence.
Referenced by attribute_to_disk(), methfile_to_disk(), method_to_disk(), put_class_attributes(), and representation_to_disk().
static void put_string (OR_BUF * buf, const char * string) static
Definition at line 1557 of file transform_cl.c.
References pr_type::data_writeval(), db_make_varnchar(), LANG_SYS_CODESET, LANG_SYS_COLLATION, pr_clear_value(), strlen, TP_FLOATING_PRECISION_VALUE, and tp_VarNChar.
Referenced by attribute_to_disk(), methfile_to_disk(), method_to_disk(), methsig_to_disk(), partition_info_to_disk(), put_class_attributes(), query_spec_to_disk(), resolution_to_disk(), and root_to_disk().
static void put_substructure_set (OR_BUF * buf, DB_LIST * list, LWRITER writer, OID * class_, int repid) static
Definition at line 1809 of file transform_cl.c.
References BIG_VAR_OFFSET_SIZE, cubregex::count(), DB_TYPE_SEQUENCE, db_list::next, NULL, or_advance(), or_put_int(), OR_PUT_OFFSET, or_put_oid(), or_put_set_header(), or_put_sub_domain(), OR_SUB_DOMAIN_SIZE, OR_VAR_TABLE_SIZE, and or_buf::ptr.
Referenced by attribute_to_disk(), domain_to_disk(), metharg_to_disk(), method_to_disk(), methsig_to_disk(), put_class_attributes(), repattribute_to_disk(), and representation_to_disk().
static int put_varinfo (OR_BUF * buf, char * obj, SM_CLASS * class_, int offset_size) static
Definition at line 616 of file transform_cl.c.
References sm_class::attributes, sm_attribute::domain, sm_class::fixed_count, sm_class::fixed_size, pr_type::get_disk_size_of_mem(), INT_ALIGNMENT, NO_ERROR, sm_attribute::offset, OR_BOUND_BIT_BYTES, or_put_offset_internal(), OR_VAR_TABLE_SIZE_INTERNAL, or_buf::ptr, PTR_ALIGN, rc, tp_domain::type, and sm_class::variable_count.
Referenced by tf_mem_to_disk().
static int query_spec_size (SM_QUERY_SPEC * statement) static
Definition at line 2808 of file transform_cl.c.
References tf_meta_class::mc_fixed_size, tf_meta_class::mc_n_variable, OR_VAR_TABLE_SIZE, sm_query_spec::specification, string_disk_size(), and tf_Metaclass_query_spec.
Referenced by put_class_varinfo(), and tf_class_size().
static int query_spec_to_disk (OR_BUF * buf, SM_QUERY_SPEC * query_spec) static
Definition at line 2770 of file transform_cl.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, er_set(), ER_TF_OUT_OF_SYNC, INT_ALIGNMENT, tf_meta_class::mc_fixed_size, tf_meta_class::mc_n_variable, NO_ERROR, or_put_offset(), OR_VAR_TABLE_SIZE, or_buf::ptr, PTR_ALIGN, put_string(), sm_query_spec::specification, string_disk_size(), and tf_Metaclass_query_spec.
Referenced by query_spec_to_disk_lwriter().
static void query_spec_to_disk_lwriter (void * buf, void * query_spec) inline static
Definition at line 2797 of file transform_cl.c.
References query_spec_to_disk(), and STATIC_CAST.
Referenced by put_class_attributes().
static OR_VARINFO * read_var_table (OR_BUF * buf, int nvars) static
Definition at line 1431 of file transform_cl.c.
References BIG_VAR_OFFSET_SIZE, and read_var_table_internal().
Referenced by disk_to_attribute(), disk_to_class(), disk_to_domain2(), disk_to_metharg(), disk_to_methfile(), disk_to_method(), disk_to_methsig(), disk_to_partition_info(), disk_to_query_spec(), disk_to_repattribute(), disk_to_representation(), disk_to_resolution(), and disk_to_root().
static OR_VARINFO * read_var_table_internal (OR_BUF * buf, int nvars, int offset_size) static
Definition at line 1444 of file transform_cl.c.
References or_get_var_table_internal(), and unpack_allocator().
Referenced by read_var_table().
static int repattribute_size (SM_REPR_ATTRIBUTE * rat) static
Definition at line 3354 of file transform_cl.c.
References sm_repr_attribute::domain, domain_size(), tf_meta_class::mc_fixed_size, tf_meta_class::mc_n_variable, OR_VAR_TABLE_SIZE, substructure_set_size(), and tf_Metaclass_repattribute.
Referenced by representation_size(), and representation_to_disk().
static int repattribute_to_disk (OR_BUF * buf, SM_REPR_ATTRIBUTE * rat) static
Definition at line 3310 of file transform_cl.c.
References ARG_FILE_LINE, sm_repr_attribute::attid, sm_repr_attribute::domain, domain_size(), domain_to_disk(), ER_ERROR_SEVERITY, er_set(), ER_TF_OUT_OF_SYNC, INT_ALIGNMENT, tf_meta_class::mc_classoid, tf_meta_class::mc_fixed_size, tf_meta_class::mc_n_variable, tf_meta_class::mc_repid, NO_ERROR, or_put_int(), or_put_offset(), OR_VAR_TABLE_SIZE, or_buf::ptr, PTR_ALIGN, put_substructure_set(), substructure_set_size(), tf_Metaclass_domain, tf_Metaclass_repattribute, and sm_repr_attribute::typeid_.
Referenced by repattribute_to_disk_lwriter().
static void repattribute_to_disk_lwriter (void * buf, void * rat) inline static
Definition at line 3343 of file transform_cl.c.
References repattribute_to_disk(), and STATIC_CAST.
Referenced by representation_to_disk().
static int representation_size (SM_REPRESENTATION * rep) static
Definition at line 3411 of file transform_cl.c.
References sm_representation::attributes, tf_meta_class::mc_fixed_size, tf_meta_class::mc_n_variable, NULL, OR_VAR_TABLE_SIZE, property_list_size(), repattribute_size(), substructure_set_size(), and tf_Metaclass_representation.
Referenced by put_class_varinfo(), and tf_class_size().
static int representation_to_disk (OR_BUF * buf, SM_REPRESENTATION * rep) static
Definition at line 3434 of file transform_cl.c.
References ARG_FILE_LINE, sm_representation::attributes, ER_ERROR_SEVERITY, er_set(), ER_TF_OUT_OF_SYNC, sm_representation::fixed_count, sm_representation::id, INT_ALIGNMENT, tf_meta_class::mc_classoid, tf_meta_class::mc_fixed_size, tf_meta_class::mc_n_variable, tf_meta_class::mc_repid, NO_ERROR, NULL, or_put_int(), or_put_offset(), OR_VAR_TABLE_SIZE, property_list_size(), or_buf::ptr, PTR_ALIGN, put_property_list(), put_substructure_set(), repattribute_size(), repattribute_to_disk_lwriter(), substructure_set_size(), tf_Metaclass_repattribute, tf_Metaclass_representation, and sm_representation::variable_count.
Referenced by representation_to_disk_lwriter().
static void representation_to_disk_lwriter (void * buf, void * rep) inline static
Definition at line 3472 of file transform_cl.c.
References representation_to_disk(), and STATIC_CAST.
Referenced by put_class_attributes().
static int resolution_size (SM_RESOLUTION * res) static
Definition at line 3222 of file transform_cl.c.
References sm_resolution::alias, tf_meta_class::mc_fixed_size, tf_meta_class::mc_n_variable, sm_resolution::name, OR_VAR_TABLE_SIZE, string_disk_size(), and tf_Metaclass_resolution.
Referenced by put_class_varinfo(), and tf_class_size().
static int resolution_to_disk (OR_BUF * buf, SM_RESOLUTION * res) static
Definition at line 3175 of file transform_cl.c.
References sm_resolution::alias, ARG_FILE_LINE, sm_resolution::class_mop, ER_ERROR_SEVERITY, er_set(), ER_TF_OUT_OF_SYNC, INT_ALIGNMENT, tf_meta_class::mc_fixed_size, tf_meta_class::mc_n_variable, sm_resolution::name, sm_resolution::name_space, NO_ERROR, or_pack_mop(), or_put_int(), or_put_offset(), OR_VAR_TABLE_SIZE, or_buf::ptr, PTR_ALIGN, put_string(), string_disk_size(), and tf_Metaclass_resolution.
Referenced by resolution_to_disk_lwriter().
static void resolution_to_disk_lwriter (void * buf, void * res) inline static
Definition at line 3211 of file transform_cl.c.
References resolution_to_disk(), and STATIC_CAST.
Referenced by put_class_attributes().
static int root_size (MOBJ rootobj) static
Definition at line 4261 of file transform_cl.c.
References tf_meta_class::mc_fixed_size, tf_meta_class::mc_n_variable, OR_NON_MVCC_HEADER_SIZE, OR_VAR_TABLE_SIZE, sm_ch_name(), string_disk_size(), and tf_Metaclass_root.
Referenced by tf_class_to_disk(), and tf_object_size().
static void root_to_disk (OR_BUF * buf, ROOT_CLASS * root) static
Definition at line 4218 of file transform_cl.c.
References ARG_FILE_LINE, assert, ER_ERROR_SEVERITY, er_set(), ER_TF_OUT_OF_SYNC, INT_ALIGNMENT, tf_meta_class::mc_fixed_size, tf_meta_class::mc_n_variable, OID_ISNULL, OR_NON_MVCC_HEADER_SIZE, or_put_int(), or_put_offset(), OR_VAR_TABLE_SIZE, or_buf::ptr, PTR_ALIGN, put_string(), sm_ch_name(), sm_ch_rep_dir(), string_disk_size(), and tf_Metaclass_root.
Referenced by tf_class_to_disk().
static int string_disk_size (const char * string) static
Definition at line 1473 of file transform_cl.c.
References db_make_varnchar(), pr_type::get_disk_size_of_value(), LANG_SYS_CODESET, LANG_SYS_COLLATION, pr_clear_compressed_string(), strlen, TP_FLOATING_PRECISION_VALUE, and tp_VarNChar.
Referenced by attribute_size(), attribute_to_disk(), domain_size(), domain_to_disk(), methfile_size(), methfile_to_disk(), method_size(), method_to_disk(), methsig_size(), methsig_to_disk(), partition_info_size(), partition_info_to_disk(), put_class_varinfo(), query_spec_size(), query_spec_to_disk(), resolution_size(), resolution_to_disk(), root_size(), root_to_disk(), and tf_class_size().
static int substructure_set_size (DB_LIST * list, LSIZER function) static
Definition at line 1761 of file transform_cl.c.
References cubregex::count(), db_list::next, NULL, OR_INT_SIZE, OR_SET_HEADER_SIZE, OR_SUB_DOMAIN_SIZE, OR_SUB_HEADER_SIZE, and OR_VAR_TABLE_SIZE.
Referenced by attribute_size(), attribute_to_disk(), domain_size(), domain_to_disk(), metharg_size(), metharg_to_disk(), method_size(), method_to_disk(), methsig_size(), methsig_to_disk(), put_class_varinfo(), repattribute_size(), repattribute_to_disk(), representation_size(), representation_to_disk(), and tf_class_size().
static void tag_component_namespace (SM_COMPONENT * components, SM_NAME_SPACE name_space) static
Definition at line 3956 of file transform_cl.c.
References sm_component::name_space, sm_component::next, and NULL.
Referenced by disk_to_class().
static int tf_add_fixup (OR_FIXUP * fix, DB_OBJECT * obj, void * ref) static
Definition at line 418 of file transform_cl.c.
References ARG_FILE_LINE, assert, lc_oidmap::client_data, er_errid(), ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, if(), locator_add_oidset_object(), locator_make_oid_set(), NO_ERROR, NULL, or_fixup::oidset, or_tempoid::refcount, or_tempoid::references, or_tempoid::refsize, and TF_FIXUP_REFERENCE_QUANT.
Referenced by tf_need_permanent_oid().
static int tf_attribute_default_expr_to_property (SM_ATTRIBUTE * attr_list) static
Definition at line 4632 of file transform_cl.c.
References ARG_FILE_LINE, assert, or_buf::buffer, classobj_drop_prop(), classobj_free_prop(), classobj_make_prop(), classobj_put_prop(), DB_DEFAULT_NONE, db_make_int(), db_make_null(), db_make_sequence(), db_make_set(), db_make_string(), sm_default_value::default_expr, db_default_expr::default_expr_format, db_default_expr::default_expr_op, db_default_expr::default_expr_type, sm_attribute::default_value, or_buf::env, er_errid(), ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), ER_TF_BUFFER_OVERFLOW, error(), or_buf::error_abort, sm_attribute::header, sm_component::next, NO_ERROR, NULL, NULL_DEFAULT_EXPRESSION_OPERATOR, sm_attribute::on_update_default_expr, or_init(), pr_clear_value(), sm_attribute::properties, or_buf::ptr, set_create_sequence(), set_put_element(), T_TO_CHAR, and tp_Set.
Referenced by tf_class_to_disk().
static int tf_class_size (MOBJ classobj) static
Definition at line 3797 of file transform_cl.c.
References attribute_size(), check_class_structure(), tf_meta_class::mc_fixed_size, tf_meta_class::mc_n_variable, methfile_size(), method_size(), object_set_size(), OR_NON_MVCC_HEADER_SIZE, OR_VAR_TABLE_SIZE, partition_info_size(), property_list_size(), query_spec_size(), representation_size(), resolution_size(), sm_ch_name(), string_disk_size(), substructure_set_size(), tf_Metaclass_class, and tr_get_cache_objects().
Referenced by tf_class_to_disk(), and tf_object_size().
TF_STATUS tf_class_to_disk (MOBJ classobj, RECDES * record)
Definition at line 4427 of file transform_cl.c.
References recdes::area_size, ARG_FILE_LINE, assert, sm_class::attributes, BIG_VAR_OFFSET_SIZE, or_buf::buffer, CAST_BUFLEN, sm_class_header::ch_obj_header, sm_class_header::ch_type, ws_object_header::chn, class_to_disk(), classobj_free_prop(), recdes::data, or_buf::env, ER_ERROR_SEVERITY, er_set(), ER_TF_BUFFER_OVERFLOW, ER_TF_SIZE_MISMATCH, or_buf::error_abort, sm_class::header, recdes::length, tf_meta_class::mc_n_variable, NO_ERROR, NULL, or_abort(), or_init(), OR_MVCC_FLAG_MASK, OR_MVCC_FLAG_SHIFT_BITS, OR_OFFSET_SIZE_FLAG, or_put_int(), OR_SET_VAR_OFFSET_SIZE, sm_class::partition, sm_class::properties, or_buf::ptr, rc, sm_class::repid, root_size(), root_to_disk(), SM_META_ROOT, sm_Root_class, tf_attribute_default_expr_to_property(), tf_class_size(), tf_compile_meta_classes(), TF_ERROR, tf_Metaclass_class, TF_OUT_OF_SPACE, and TF_SUCCESS.
Referenced by locator_class_to_disk().
MOBJ tf_disk_to_class (OID * oid, RECDES * record)
Definition at line 4344 of file transform_cl.c.
References assert, BIG_VAR_OFFSET_SIZE, classobj_free_class(), recdes::data, disk_to_class(), disk_to_root(), or_buf::env, or_buf::error_abort, recdes::length, tf_meta_class::mc_n_variable, NO_ERROR, NULL, oid_is_root(), OID_ISNULL, or_get_int(), OR_GET_OFFSET_SIZE, or_init(), OR_MVCC_FLAG_MASK, OR_MVCC_FLAG_SHIFT_BITS, OR_OFFSET_SIZE_FLAG, or_buf::ptr, rc, sm_class::repid, sm_bump_global_schema_version(), tf_compile_meta_classes(), and tf_Metaclass_class.
Referenced by locator_cache_object_class().
MOBJ tf_disk_to_mem (MOBJ classobj, RECDES * record, int * convertp)
Definition at line 1323 of file transform_cl.c.
References recdes::data, or_buf::env, or_buf::error_abort, get_current(), get_old(), recdes::length, NO_ERROR, NULL, obj_free_memory(), or_advance(), OR_BOUND_BIT_FLAG, or_get_int(), OR_GET_OFFSET_SIZE, or_init(), OR_MVCC_FLAG_MASK, OR_MVCC_FLAG_SHIFT_BITS, OR_MVCC_FLAG_VALID_DELID, OR_MVCC_FLAG_VALID_INSID, OR_MVCC_FLAG_VALID_PREV_VERSION, or_mvcc_get_repid_and_flags(), OR_MVCC_PREV_VERSION_LSA_SIZE, OR_MVCC_REPID_MASK, OR_MVCCID_SIZE, or_buf::ptr, rc, sm_class::repid, and WS_CHN.
Referenced by locator_cache_object_instance().
static int tf_do_fixup (OR_FIXUP * fix) static
Definition at line 595 of file transform_cl.c.
References error(), fixup_callback(), locator_assign_oidset(), NO_ERROR, NULL, and or_fixup::oidset.
Referenced by tf_mem_to_disk().
static void tf_free_fixup (OR_FIXUP * fix) static
Definition at line 370 of file transform_cl.c.
References lc_oidset::classes, lc_oidmap::client_data, free_and_init, locator_free_oid_set(), lc_oidmap::next, lc_class_oidset::next, NULL, lc_class_oidset::oids, or_fixup::oidset, and or_tempoid::references.
Referenced by tf_mem_to_disk().
static OR_FIXUP * tf_make_fixup (void) static
Definition at line 345 of file transform_cl.c.
References NULL, and or_fixup::oidset.
Referenced by tf_mem_to_disk().
TF_STATUS tf_mem_to_disk (MOP classmop, MOBJ classobj, MOBJ volatile obj, RECDES * record, bool * index_flag)
Definition at line 767 of file transform_cl.c.
References recdes::area_size, ARG_FILE_LINE, or_buf::buffer, classobj_class_has_indexes(), recdes::data, or_buf::env, er_errid(), ER_ERROR_SEVERITY, ER_OBJ_CANT_ASSIGN_OID, er_set(), ER_TF_BUFFER_OVERFLOW, or_buf::error_abort, sm_class::fixed_count, or_buf::fixups, recdes::length, locator_assign_permanent_oid(), MVCCID_NULL, NO_ERROR, NULL, object_size(), OID_ISTEMP, optimize_sets(), or_abort(), OR_BOUND_BIT_FLAG, or_init(), OR_MVCC_FLAG_SHIFT_BITS, OR_MVCC_FLAG_VALID_INSID, OR_MVCC_INSERT_HEADER_SIZE, OR_MVCC_MAX_HEADER_SIZE, or_put_bigint(), or_put_int(), OR_SET_VAR_OFFSET_SIZE, or_buf::ptr, put_attributes(), put_varinfo(), sm_class::repid, tf_Allow_fixups, tf_do_fixup(), TF_ERROR, tf_free_fixup(), tf_make_fixup(), TF_OUT_OF_SPACE, TF_SUCCESS, WS_CHN, and WS_OID.
Referenced by locator_mem_to_disk().
OID* tf_need_permanent_oid (or_buf * buf, DB_OBJECT * obj)
Definition at line 513 of file transform_cl.c.
References ARG_FILE_LINE, db_object::class_mop, er_errid(), ER_ERROR_SEVERITY, ER_OBJ_CANT_ASSIGN_OID, er_set(), or_buf::fixups, locator_assign_permanent_oid(), NO_ERROR, NULL, oid_Null_oid, or_abort(), or_buf::ptr, sm_Root_class_mop, tf_add_fixup(), tf_Allow_fixups, and WS_OID.
Referenced by mr_data_writemem_object(), and mr_data_writeval_object().
int tf_object_size (MOBJ classobj, MOBJ obj)
Definition at line 4562 of file transform_cl.c.
References object_size(), root_size(), sm_Root_class, and tf_class_size().
Referenced by locator_add_oidset_object(), locator_assign_permanent_oid(), and sm_object_size_quick().
static char * unpack_allocator (int size) static
Definition at line 1417 of file transform_cl.c.
Referenced by read_var_table_internal().
Variable Documentation
int tf_Allow_fixups = 1
Definition at line 70 of file transform_cl.c.
Referenced by tf_mem_to_disk(), and tf_need_permanent_oid().