CUBRID Engine: src/object/trigger_description.cpp File Reference
trigger_description.cpp File Reference
#include "trigger_description.hpp"
#include "authenticate.h"
#include "dbi.h"
#include "dbtype_function.h"
#include "object_accessor.h"
#include "object_print.h"
#include "object_printer.hpp"
#include "object_print_util.hpp"
#include "printer.hpp"
#include "set_object.h"
#include "schema_manager.h"
#include "trigger_manager.h"
#include "work_space.h"
Macros
#define STRFREE_W(string) if (string != NULL) db_string_free((char *) (string))
#define MAX_USER_NAME 32 /* actually its 8 */
Functions
static int is_required_trigger (TR_TRIGGER *trigger, DB_OBJLIST *classes)
static char * get_user_name (DB_OBJECT *user)
int tr_dump_trigger (print_output &output_ctx, DB_OBJECT *trigger_object)
int tr_dump_selective_triggers (print_output &output_ctx, DB_OBJLIST *classes)
Macro Definition Documentation
#define MAX_USER_NAME 32 /* actually its 8 */
Referenced by get_user_name().
#define STRFREE_W (string) if (string != NULL) db_string_free((char *) (string))
Definition at line 39 of file trigger_description.cpp.
Referenced by trigger_description::~trigger_description().
Function Documentation
static char * get_user_name (DB_OBJECT * user) static
Definition at line 457 of file trigger_description.cpp.
References db_get(), db_get_string(), DB_IS_NULL, DB_TYPE_STRING, db_value_clear(), DB_VALUE_TYPE, MAX_USER_NAME, and NULL.
Referenced by tr_dump_selective_triggers(), and tr_status_as_string().
static int is_required_trigger (TR_TRIGGER * trigger, DB_OBJLIST * classes) static
Definition at line 435 of file trigger_description.cpp.
References tr_trigger::class_mop, db_objlist::next, NULL, and db_objlist::op.
Referenced by tr_dump_selective_triggers().
int tr_dump_selective_triggers (print_output & output_ctx, DB_OBJLIST * classes)
Definition at line 343 of file trigger_description.cpp.
References ASSERT_ERROR_AND_SET, Au_root, tr_trigger::class_mop, db_get_object(), db_get_set(), DB_IS_NULL, DB_TYPE_OBJECT, DB_VALUE_TYPE, error(), get_user_name(), i, is_required_trigger(), max, tr_trigger::name, NO_ERROR, NULL, obj_get(), tr_trigger::owner, set_filter(), set_free(), set_get_element(), set_size(), sm_is_system_class(), tr_trigger::status, tr_dump_trigger(), tr_map_trigger(), and TR_STATUS_INVALID.
Referenced by extract_triggers().
int tr_dump_trigger (print_output & output_ctx, DB_OBJECT * trigger_object)
Definition at line 238 of file trigger_description.cpp.
References tr_trigger::action, ASSERT_ERROR_AND_SET, tr_trigger::attribute, AU_DISABLE, AU_ENABLE, tr_trigger::class_mop, tr_trigger::comment, tr_trigger::condition, db_get_class_name(), error(), tr_trigger::event, help_print_describe_comment(), trigger_description::name, tr_trigger::name, NO_ERROR, NULL, tr_trigger::priority, tr_activity::source, tr_trigger::status, tr_activity::time, TR_ACT_EXPRESSION, TR_ACT_INVALIDATE, TR_ACT_PRINT, TR_ACT_REJECT, tr_event_as_string(), tr_map_trigger(), tr_status_as_string(), TR_STATUS_INVALID, tr_time_as_string(), TR_TIME_BEFORE, and tr_activity::type.
Referenced by tr_dump_selective_triggers(), and tr_status_as_string().