CUBRID Engine: src/base/tsc_timer.h File Reference
tsc_timer.h File Reference
#include "porting.h"
#include "cycle.h"
Classes
union tsc_ticks
Macros
#define TSC_ADD_TIMEVAL(total, diff)
Typedefs
typedef UINT64 TSC_UINT64
typedef struct timeval TSCTIMEVAL
typedef union tsc_ticks TSC_TICKS
Functions
void tsc_init (void)
void tsc_getticks (TSC_TICKS *tck)
void tsc_elapsed_time_usec (TSCTIMEVAL *tv, TSC_TICKS end_tick, TSC_TICKS start_tick)
UINT64 tsc_elapsed_utime (TSC_TICKS end_tick, TSC_TICKS start_tick)
void tsc_start_time_usec (TSC_TICKS *tck)
void tsc_end_time_usec (TSCTIMEVAL *tv, TSC_TICKS start_tick)
TSC_UINT64 get_clock_freq (void)
Macro Definition Documentation
#define TSC_ADD_TIMEVAL (total, diff)
Value:
do { \
  (total).tv_usec += (diff).tv_usec; \
  (total).tv_sec += (diff).tv_sec; \
  (total).tv_sec += (total).tv_usec / 1000000; \
  (total).tv_usec %= 1000000; \
} while (0)
Definition at line 31 of file tsc_timer.h.
Referenced by csect_demote_critical_section(), csect_enter_critical_section(), csect_enter_critical_section_as_reader(), csect_promote_critical_section(), pgbuf_block_bcb(), qexec_execute_mainblock(), qexec_execute_mainblock_internal(), qexec_groupby(), qexec_groupby_index(), qexec_hash_gby_agg_tuple(), qexec_listfile_orderby(), qexec_orderby_distinct(), scan_next_index_scan(), scan_next_scan_local(), and scan_open_list_scan().
Typedef Documentation
typedef union tsc_ticks TSC_TICKS
Definition at line 42 of file tsc_timer.h.
typedef UINT64 TSC_UINT64
Definition at line 39 of file tsc_timer.h.
typedef struct timeval TSCTIMEVAL
Definition at line 40 of file tsc_timer.h.
Function Documentation
TSC_UINT64 get_clock_freq (void)
Definition at line 36 of file get_clock_freq.c.
References NULL.
Referenced by tsc_init().
void tsc_elapsed_time_usec (TSCTIMEVAL * tv, TSC_TICKS end_tick, TSC_TICKS start_tick)
Definition at line 101 of file tsc_timer.c.
References CALCULATE_ELAPSED_TIME_USEC, CALCULATE_ELAPSED_TIMEVAL, CHECK_CPU_FREQ, cpu_Clock_rate, power_Savings, tsc_ticks::tc, and tsc_ticks::tv.
Referenced by mvcctable::build_mvcc_info(), csect_demote_critical_section(), csect_enter_critical_section(), csect_enter_critical_section_as_reader(), csect_promote_critical_section(), csql_execute_statements(), fileio_initialize_pages(), fileio_read(), fileio_read_pages(), fileio_synchronize(), fileio_unformat_and_rename(), fileio_write(), fileio_write_pages(), lock_classes_lock_hint(), lock_object(), lock_scan(), lock_subclass(), logpb_copy_page(), logpb_locate_page(), logtb_complete_mvcc(), pgbuf_block_bcb(), pgbuf_claim_bcb_for_fix(), pgbuf_fix_debug(), pgbuf_promote_read_latch_debug(), qexec_execute_mainblock(), qexec_execute_mainblock_internal(), qexec_execute_query(), qexec_groupby(), qexec_groupby_index(), qexec_hash_gby_agg_tuple(), qexec_listfile_orderby(), qexec_orderby_distinct(), rmutex_lock(), rwlock_read_lock(), rwlock_write_lock(), scan_next_index_scan(), scan_next_scan_local(), scan_open_list_scan(), sqmgr_execute_query(), and tsc_elapsed_utime().
UINT64 tsc_elapsed_utime (TSC_TICKS end_tick, TSC_TICKS start_tick)
Definition at line 135 of file tsc_timer.c.
References tsc_elapsed_time_usec().
Referenced by pgbuf_adjust_quotas(), pgbuf_delete_from_hash_chain(), pgbuf_flush_victim_candidates(), pgbuf_insert_into_hash_chain(), pgbuf_lock_page(), pgbuf_search_hash_chain(), and pgbuf_unlock_page().
void tsc_end_time_usec (TSCTIMEVAL * tv, TSC_TICKS start_tick)
Definition at line 162 of file tsc_timer.c.
References CALCULATE_ELAPSED_TIME_USEC, CALCULATE_ELAPSED_TIMEVAL, CHECK_CPU_FREQ, cpu_Clock_rate, power_Savings, tsc_ticks::tc, tsc_getticks(), and tsc_ticks::tv.
void tsc_getticks (TSC_TICKS * tck)
Definition at line 81 of file tsc_timer.c.
References NULL, power_Savings, tsc_ticks::tc, and tsc_ticks::tv.
Referenced by mvcctable::build_mvcc_info(), csect_demote_critical_section(), csect_enter_critical_section(), csect_enter_critical_section_as_reader(), csect_promote_critical_section(), csql_execute_statements(), disk_extend(), fileio_initialize_pages(), fileio_read(), fileio_read_pages(), fileio_synchronize(), fileio_unformat_and_rename(), fileio_write(), fileio_write_pages(), lock_classes_lock_hint(), lock_object(), lock_scan(), lock_subclass(), logpb_copy_page(), logpb_locate_page(), logtb_complete_mvcc(), pgbuf_adjust_quotas(), pgbuf_block_bcb(), pgbuf_claim_bcb_for_fix(), pgbuf_delete_from_hash_chain(), pgbuf_fix_debug(), pgbuf_flush_victim_candidates(), pgbuf_initialize_page_quota_parameters(), pgbuf_insert_into_hash_chain(), pgbuf_lock_page(), pgbuf_promote_read_latch_debug(), pgbuf_search_hash_chain(), pgbuf_unlock_page(), qexec_execute_mainblock(), qexec_execute_mainblock_internal(), qexec_execute_query(), qexec_groupby(), qexec_groupby_index(), qexec_hash_gby_agg_tuple(), qexec_listfile_orderby(), qexec_orderby_distinct(), rmutex_lock(), rwlock_read_lock(), rwlock_write_lock(), scan_next_index_scan(), scan_next_scan_local(), scan_open_list_scan(), sqmgr_execute_query(), tsc_end_time_usec(), and tsc_start_time_usec().
void tsc_init (void)
Definition at line 67 of file tsc_timer.c.
References check_power_savings(), cpu_Clock_rate, and get_clock_freq().
Referenced by boot_initialize_client(), boot_restart_client(), boot_restart_server(), patchdb(), xboot_emergency_patch(), and xboot_initialize_server().
void tsc_start_time_usec (TSC_TICKS * tck)
Definition at line 150 of file tsc_timer.c.
References tsc_getticks().