CUBRID Engine: src/base/tsc_timer.c File Reference
tsc_timer.c File Reference
#include "config.h"
#include <fcntl.h>
#include "tsc_timer.h"
#include <sys/time.h>
Macros
#define CHECK_CPU_FREQ(v)
#define CALCULATE_ELAPSED_TIME_USEC(time, diff, freq)
#define CALCULATE_ELAPSED_TIMEVAL(time, end, start)
Functions
static void check_power_savings (void)
void tsc_init (void)
void tsc_getticks (TSC_TICKS *tck)
void tsc_elapsed_time_usec (TSCTIMEVAL *tv, TSC_TICKS end_tick, TSC_TICKS start_tick)
UINT64 tsc_elapsed_utime (TSC_TICKS end_tick, TSC_TICKS start_tick)
void tsc_start_time_usec (TSC_TICKS *tck)
void tsc_end_time_usec (TSCTIMEVAL *tv, TSC_TICKS start_tick)
Variables
static int power_Savings = -1
static TSC_UINT64 cpu_Clock_rate = 0
Macro Definition Documentation
#define CALCULATE_ELAPSED_TIME_USEC (time, diff, freq)
Value:
do { \
  (time)->tv_sec = (long)((diff) / (freq)); \
  (time)->tv_usec = (long)((((diff) % (freq)) * (TSC_UINT64) (1000000)) / (freq)); \
} while (0)
Definition at line 41 of file tsc_timer.c.
Referenced by tsc_elapsed_time_usec(), and tsc_end_time_usec().
#define CALCULATE_ELAPSED_TIMEVAL (time, end, start)
Value:
do { \
  (time)->tv_sec = (end).tv_sec - (start).tv_sec; \
  (time)->tv_usec = (end).tv_usec - (start).tv_usec; \
  if ((time)->tv_usec < 0) \
    { \
      (time)->tv_sec--; \
      (time)->tv_usec += 1000000; \
    } \
} while (0)
Definition at line 47 of file tsc_timer.c.
Referenced by tsc_elapsed_time_usec(), and tsc_end_time_usec().
#define CHECK_CPU_FREQ (v)
Value:
do { \
  if ((v) == 0) \
    { \
      (v) = get_clock_freq (); \
    } \
} while (0)
Definition at line 33 of file tsc_timer.c.
Referenced by tsc_elapsed_time_usec(), and tsc_end_time_usec().
Function Documentation
static void check_power_savings (void) static
Definition at line 192 of file tsc_timer.c.
References power_Savings.
Referenced by tsc_init().
void tsc_elapsed_time_usec (TSCTIMEVAL * tv, TSC_TICKS end_tick, TSC_TICKS start_tick)
Definition at line 101 of file tsc_timer.c.
References CALCULATE_ELAPSED_TIME_USEC, CALCULATE_ELAPSED_TIMEVAL, CHECK_CPU_FREQ, cpu_Clock_rate, power_Savings, tsc_ticks::tc, and tsc_ticks::tv.
Referenced by mvcctable::build_mvcc_info(), csect_demote_critical_section(), csect_enter_critical_section(), csect_enter_critical_section_as_reader(), csect_promote_critical_section(), csql_execute_statements(), fileio_initialize_pages(), fileio_read(), fileio_read_pages(), fileio_synchronize(), fileio_unformat_and_rename(), fileio_write(), fileio_write_pages(), lock_classes_lock_hint(), lock_object(), lock_scan(), lock_subclass(), logpb_copy_page(), logpb_locate_page(), logtb_complete_mvcc(), pgbuf_block_bcb(), pgbuf_claim_bcb_for_fix(), pgbuf_fix_debug(), pgbuf_promote_read_latch_debug(), qexec_execute_mainblock(), qexec_execute_mainblock_internal(), qexec_execute_query(), qexec_groupby(), qexec_groupby_index(), qexec_hash_gby_agg_tuple(), qexec_listfile_orderby(), qexec_orderby_distinct(), rmutex_lock(), rwlock_read_lock(), rwlock_write_lock(), scan_next_index_scan(), scan_next_scan_local(), scan_open_list_scan(), sqmgr_execute_query(), and tsc_elapsed_utime().
UINT64 tsc_elapsed_utime (TSC_TICKS end_tick, TSC_TICKS start_tick)
Definition at line 135 of file tsc_timer.c.
References tsc_elapsed_time_usec().
Referenced by pgbuf_adjust_quotas(), pgbuf_delete_from_hash_chain(), pgbuf_flush_victim_candidates(), pgbuf_insert_into_hash_chain(), pgbuf_lock_page(), pgbuf_search_hash_chain(), and pgbuf_unlock_page().
void tsc_end_time_usec (TSCTIMEVAL * tv, TSC_TICKS start_tick)
Definition at line 162 of file tsc_timer.c.
References CALCULATE_ELAPSED_TIME_USEC, CALCULATE_ELAPSED_TIMEVAL, CHECK_CPU_FREQ, cpu_Clock_rate, power_Savings, tsc_ticks::tc, tsc_getticks(), and tsc_ticks::tv.
void tsc_getticks (TSC_TICKS * tck)
Definition at line 81 of file tsc_timer.c.
References NULL, power_Savings, tsc_ticks::tc, and tsc_ticks::tv.
Referenced by mvcctable::build_mvcc_info(), csect_demote_critical_section(), csect_enter_critical_section(), csect_enter_critical_section_as_reader(), csect_promote_critical_section(), csql_execute_statements(), disk_extend(), fileio_initialize_pages(), fileio_read(), fileio_read_pages(), fileio_synchronize(), fileio_unformat_and_rename(), fileio_write(), fileio_write_pages(), lock_classes_lock_hint(), lock_object(), lock_scan(), lock_subclass(), logpb_copy_page(), logpb_locate_page(), logtb_complete_mvcc(), pgbuf_adjust_quotas(), pgbuf_block_bcb(), pgbuf_claim_bcb_for_fix(), pgbuf_delete_from_hash_chain(), pgbuf_fix_debug(), pgbuf_flush_victim_candidates(), pgbuf_initialize_page_quota_parameters(), pgbuf_insert_into_hash_chain(), pgbuf_lock_page(), pgbuf_promote_read_latch_debug(), pgbuf_search_hash_chain(), pgbuf_unlock_page(), qexec_execute_mainblock(), qexec_execute_mainblock_internal(), qexec_execute_query(), qexec_groupby(), qexec_groupby_index(), qexec_hash_gby_agg_tuple(), qexec_listfile_orderby(), qexec_orderby_distinct(), rmutex_lock(), rwlock_read_lock(), rwlock_write_lock(), scan_next_index_scan(), scan_next_scan_local(), scan_open_list_scan(), sqmgr_execute_query(), tsc_end_time_usec(), and tsc_start_time_usec().
void tsc_init (void)
Definition at line 67 of file tsc_timer.c.
References check_power_savings(), cpu_Clock_rate, and get_clock_freq().
Referenced by boot_initialize_client(), boot_restart_client(), boot_restart_server(), patchdb(), xboot_emergency_patch(), and xboot_initialize_server().
void tsc_start_time_usec (TSC_TICKS * tck)
Definition at line 150 of file tsc_timer.c.
References tsc_getticks().
Variable Documentation
TSC_UINT64 cpu_Clock_rate = 0 static
Definition at line 59 of file tsc_timer.c.
Referenced by tsc_elapsed_time_usec(), tsc_end_time_usec(), and tsc_init().
int power_Savings = -1 static
Definition at line 58 of file tsc_timer.c.
Referenced by check_power_savings(), tsc_elapsed_time_usec(), tsc_end_time_usec(), and tsc_getticks().