CUBRID Engine: src/base/tz_compile.h File Reference
tz_compile.h File Reference
#include "timezone_lib_common.h"
Functions
void tzc_dump_summary (const TZ_DATA *tzd)
void tzc_dump_countries (const TZ_DATA *tzd)
void tzc_dump_timezones (const TZ_DATA *tzd)
void tzc_dump_one_timezone (const TZ_DATA *tzd, const int zone_id)
void tzc_dump_leap_sec (const TZ_DATA *tzd)
Function Documentation
void tzc_dump_countries (const TZ_DATA * tzd)
Definition at line 4637 of file tz_compile.c.
References assert, tz_country::code, tz_data::countries, tz_data::country_count, tz_country::full_name, i, and NULL.
Referenced by dump_tz().
void tzc_dump_leap_sec (const TZ_DATA * tzd)
Definition at line 4788 of file tz_compile.c.
References assert, tz_leap_sec::corr_negative, tz_leap_sec::day, tz_data::ds_leap_sec, tz_data::ds_leap_sec_count, i, tz_leap_sec::is_rolling, tz_leap_sec::month, MONTH_NAMES_ABBREV, NULL, and tz_leap_sec::year.
Referenced by dump_tz().
void tzc_dump_one_timezone (const TZ_DATA * tzd, const int zone_id)
Definition at line 4674 of file tz_compile.c.
References assert, tz_offset_rule::ds_ruleset, tz_offset_rule::ds_type, DS_TYPE_FIXED, tz_timezone::gmt_off_rule_count, tz_timezone::gmt_off_rule_start, i, tz_name::name, tz_data::names, NO_ERROR, NULL, tz_data::offset_rules, tz_data::timezone_names, tz_data::timezones, tzc_dump_ds_ruleset(), tzc_dump_one_offset_rule(), and tzc_get_timezone_aliases().
Referenced by dump_tz().
void tzc_dump_summary (const TZ_DATA * tzd)
Definition at line 4617 of file tz_compile.c.
References assert, tz_data::country_count, tz_data::ds_leap_sec_count, tz_data::ds_rule_count, tz_data::ds_ruleset_count, tz_data::name_count, NULL, tz_data::offset_rule_count, and tz_data::timezone_count.
Referenced by dump_tz().
void tzc_dump_timezones (const TZ_DATA * tzd)
Definition at line 4655 of file tz_compile.c.
References assert, i, NULL, tz_data::timezone_count, and tz_data::timezone_names.
Referenced by dump_tz().