CUBRID Engine: src/base/uca_support.h File Reference
uca_support.h File Reference
#include "locale_support.h"
Functions
int uca_process_collation (LOCALE_COLLATION *lc, bool is_verbose)
void uca_free_data (void)
Function Documentation
void uca_free_data (void)
Definition at line 2119 of file uca_support.c.
References assert, uca_storage::coll_contr, uca_storage::coll_cp, uca_storage::coll_exp, uca_storage::count_contr, uca_storage::max_contr, NULL, and uca_storage::prev_file_path.
Referenced by load_ducet(), and locale_compile_locale().
int uca_process_collation (LOCALE_COLLATION * lc, bool is_verbose)
Definition at line 810 of file uca_support.c.
References apply_absolute_tailoring_rules(), apply_tailoring_rules(), build_key_list_groups(), compute_weights_per_level_stats(), uca_storage::count_contr, coll_tailoring::count_rules, create_opt_ce_w_exp(), create_opt_weights(), coll_tailoring::cub_count_rules, destroy_uca_instance(), init_uca_instance(), NO_ERROR, NULL, locale_collation::opt_coll, uca_options::sett_expansions, sort_coll_key_lists(), locale_collation::tail_coll, coll_data::uca_opt, and coll_tailoring::uca_opt.
Referenced by locale_compile_locale().