CUBRID Engine: src/base/uca_support.c File Reference
uca_support.c File Reference
#include <assert.h>
#include <errno.h>
#include "utility.h"
#include "environment_variable.h"
#include "locale_support.h"
#include "error_manager.h"
#include "porting.h"
#include "intl_support.h"
#include "uca_support.h"
#include "unicode_support.h"
Classes
struct uca_coll_ce
struct uca_coll_ce_list
struct uca_chr_seq
struct uca_coll_contr_id
struct uca_coll_key
struct uca_weight_key_list
struct uca_storage
Macros
#define strlen(s1) ((int) strlen(s1))
#define DUCET_FILE "ducet.txt"
#define MAX_WEIGHT_LEVELS 4
#define MAX_UCA_WEIGHT 0xFFFF
#define MAX_UCA_CODEPOINT 0xFFFF
#define UCA_CONTR_EXP_CNT_GROW 8
#define MAX_LOGICAL_POS 14
#define GET_UCA_WEIGHT(ce_list, i, w) ((ce_list)->ce[(i)].weight[(w)])
#define SET_UCA_WEIGHT(ce_list, i, w, val)
Typedefs
typedef struct uca_coll_ce UCA_COLL_CE
typedef struct uca_coll_ce_list UCA_COLL_CE_LIST
typedef struct uca_chr_seq UCA_CHR_SEQ
typedef UCA_CHR_SEQ UCA_CONTRACTION
typedef UCA_CHR_SEQ UCA_EXPANSION
typedef struct uca_coll_contr_id UCA_COLL_CONTR_ID
typedef struct uca_coll_key UCA_COLL_KEY
typedef struct uca_storage UCA_STORAGE
typedef struct uca_weight_key_list UCA_WEIGHT_KEY_LIST
Enumerations
enum UCA_COLL_KEY_TYPE { COLL_KEY_TYPE_CP = 0, COLL_KEY_TYPE_CONTR, COLL_KEY_TYPE_EXP }
Functions
static int load_ducet (const char *file_path, const int sett_contr_policy)
static int init_uca_instance (LOCALE_COLLATION *lc)
static int destroy_uca_instance (void)
static int build_key_list_groups (LOCALE_COLLATION *lc)
static void sort_coll_key_lists (LOCALE_COLLATION *lc)
static void sort_one_coll_key_list (LOCALE_COLLATION *lc, int weight_index)
static int uca_comp_func_coll_key_fo (const void *arg1, const void *arg2)
static int uca_comp_func_coll_key (const void *arg1, const void *arg2)
static UCA_COLL_CE_LIST * get_ce_list_from_coll_key (const UCA_COLL_KEY *key)
static int create_opt_weights (LOCALE_COLLATION *lc)
static int optimize_coll_contractions (LOCALE_COLLATION *lc)
static int set_next_value_for_coll_key (LOCALE_COLLATION *lc, const UCA_COLL_KEY *coll_key, const UCA_COLL_KEY *next_key)
static int add_opt_coll_contraction (LOCALE_COLLATION *lc, const UCA_COLL_KEY *contr_key, const unsigned int wv, bool use_expansions)
static int compare_ce_list (UCA_COLL_CE_LIST *ce_list1, UCA_COLL_CE_LIST *ce_list2, UCA_OPTIONS *uca_opt)
static UCA_COLL_KEY * get_key_with_ce_sublist (UCA_COLL_CE_LIST *uca_item, const int lvl)
static void make_coll_key (UCA_COLL_KEY *key, UCA_COLL_KEY_TYPE type, const int key_id)
static int find_contr_id (const unsigned int *cp_array, const int cp_count, UCA_STORAGE *st)
static int find_exp_id (const unsigned int *cp_array, const int cp_count, UCA_STORAGE *st)
static int apply_tailoring_rule (TAILOR_DIR dir, UCA_COLL_KEY *anchor_key, UCA_COLL_KEY *key, UCA_COLL_KEY *ref_key, T_LEVEL lvl)
static int apply_tailoring_rule_identity (UCA_COLL_KEY *key, UCA_COLL_KEY *ref_key)
static int apply_tailoring_rule_w_dir (TAILOR_DIR dir, UCA_COLL_KEY *anchor_key, UCA_COLL_KEY *key, UCA_COLL_KEY *ref_key, T_LEVEL lvl)
static int apply_tailoring_rules (LOCALE_COLLATION *lc)
static int compute_weights_per_level_stats (void)
static int add_key_to_weight_stats_list (const UCA_COLL_KEY *key, UCA_W wv)
static int remove_key_from_weight_stats_list (const UCA_COLL_KEY *key, UCA_W wv)
static int change_key_weight_list (const UCA_COLL_KEY *key, UCA_W w_from, UCA_W w_to)
static int string_to_coll_ce_list (char *s, UCA_COLL_CE_LIST *ui)
static int apply_absolute_tailoring_rules (LOCALE_COLLATION *lc)
static UCA_CONTRACTION * new_contraction (UCA_STORAGE *storage)
static int add_uca_contr_or_exp (LOCALE_COLLATION *lc, UCA_STORAGE *storage, const unsigned int *cp_array, const int cp_count, const UCA_COLL_KEY_TYPE seq_type)
static int read_cp_from_tag (unsigned char *buffer, CP_BUF_TYPE type, UCA_CP *cp)
static int comp_func_coll_contr_bin (const void *arg1, const void *arg2)
static int create_opt_ce_w_exp (LOCALE_COLLATION *lc)
static int uca_comp_func_coll_list_exp_fo (const void *arg1, const void *arg2)
static int uca_comp_func_coll_list_exp (const void *arg1, const void *arg2)
static void build_compressed_uca_w_l13 (const UCA_COLL_CE_LIST *ce_list, UCA_L13_W *uca_w_l13)
static void build_uca_w_l4 (const UCA_COLL_CE_LIST *ce_list, UCA_L4_W *uca_w_l4)
int uca_process_collation (LOCALE_COLLATION *lc, bool is_verbose)
void uca_free_data (void)
static UCA_EXPANSION * new_expansion (UCA_STORAGE *storage)
Variables
static UCA_STORAGE ducet
static UCA_STORAGE curr_uca
static UCA_W * w_occurences [MAX_WEIGHT_LEVELS]
static UCA_WEIGHT_KEY_LIST * weight_key_list
static int logical_pos_cp [MAX_LOGICAL_POS]
static UCA_OPTIONS * uca_tailoring_options = NULL
Macro Definition Documentation
#define DUCET_FILE "ducet.txt"
Definition at line 39 of file uca_support.c.
Referenced by init_uca_instance().
#define GET_UCA_WEIGHT (ce_list, i, w) ((ce_list)->ce[(i)].weight[(w)])
Definition at line 64 of file uca_support.c.
Referenced by add_opt_coll_contraction(), add_uca_contr_or_exp(), apply_absolute_tailoring_rules(), apply_tailoring_rule_identity(), apply_tailoring_rule_w_dir(), build_compressed_uca_w_l13(), build_key_list_groups(), build_uca_w_l4(), compare_ce_list(), compute_weights_per_level_stats(), and get_key_with_ce_sublist().
#define MAX_LOGICAL_POS 14
Definition at line 48 of file uca_support.c.
Referenced by apply_tailoring_rules().
#define MAX_UCA_CODEPOINT 0xFFFF
Definition at line 44 of file uca_support.c.
Referenced by apply_tailoring_rules(), compute_weights_per_level_stats(), create_opt_weights(), get_ce_list_from_coll_key(), init_uca_instance(), and load_ducet().
#define MAX_UCA_WEIGHT 0xFFFF
Definition at line 43 of file uca_support.c.
Referenced by apply_absolute_tailoring_rules(), apply_tailoring_rule_w_dir(), build_key_list_groups(), compute_weights_per_level_stats(), create_opt_weights(), destroy_uca_instance(), init_uca_instance(), sort_coll_key_lists(), sort_one_coll_key_list(), and string_to_coll_ce_list().
#define MAX_WEIGHT_LEVELS 4
Definition at line 41 of file uca_support.c.
Referenced by add_uca_contr_or_exp(), apply_absolute_tailoring_rules(), compare_ce_list(), compute_weights_per_level_stats(), destroy_uca_instance(), init_uca_instance(), load_ducet(), and string_to_coll_ce_list().
#define SET_UCA_WEIGHT (ce_list, i, w, val)
Value:
do { \
    (ce_list)->ce[(i)].weight[(w)] = (val); \
    } while (0);
Definition at line 65 of file uca_support.c.
Referenced by add_uca_contr_or_exp(), apply_absolute_tailoring_rules(), apply_tailoring_rule_w_dir(), compute_weights_per_level_stats(), load_ducet(), and string_to_coll_ce_list().
#define strlen (s1) ((int) strlen(s1))
Definition at line 36 of file uca_support.c.
Referenced by apply_absolute_tailoring_rules(), apply_tailoring_rules(), optimize_coll_contractions(), read_cp_from_tag(), and string_to_coll_ce_list().
#define UCA_CONTR_EXP_CNT_GROW 8
Definition at line 46 of file uca_support.c.
Referenced by new_contraction(), and new_expansion().
Typedef Documentation
typedef struct uca_chr_seq UCA_CHR_SEQ
Definition at line 71 of file uca_support.c.
typedef struct uca_coll_ce UCA_COLL_CE
Definition at line 51 of file uca_support.c.
typedef struct uca_coll_ce_list UCA_COLL_CE_LIST
Definition at line 57 of file uca_support.c.
typedef struct uca_coll_contr_id UCA_COLL_CONTR_ID
Definition at line 84 of file uca_support.c.
typedef struct uca_coll_key UCA_COLL_KEY
Definition at line 99 of file uca_support.c.
typedef UCA_CHR_SEQ UCA_CONTRACTION
Definition at line 80 of file uca_support.c.
typedef UCA_CHR_SEQ UCA_EXPANSION
Definition at line 81 of file uca_support.c.
typedef struct uca_storage UCA_STORAGE
Definition at line 111 of file uca_support.c.
typedef struct uca_weight_key_list UCA_WEIGHT_KEY_LIST
Definition at line 113 of file uca_support.c.
Enumeration Type Documentation
enum UCA_COLL_KEY_TYPE
Enumerator
COLL_KEY_TYPE_CP
COLL_KEY_TYPE_CONTR
COLL_KEY_TYPE_EXP
Definition at line 92 of file uca_support.c.
Function Documentation
static int add_key_to_weight_stats_list (const UCA_COLL_KEY * key, UCA_W wv) static
Definition at line 2853 of file uca_support.c.
References assert, ER_LOC_GEN, uca_weight_key_list::list_count, LOG_LOCALE_ERROR, NO_ERROR, and NULL.
Referenced by add_uca_contr_or_exp(), and change_key_weight_list().
static int add_opt_coll_contraction (LOCALE_COLLATION * lc, const UCA_COLL_KEY * contr_key, const unsigned int wv, bool use_expansions) static
Definition at line 2038 of file uca_support.c.
References assert, build_compressed_uca_w_l13(), coll_contraction::c_buf, uca_storage::coll_contr, COLL_KEY_TYPE_CONTR, uca_coll_key::contr_id, coll_data::contr_list, uca_storage::count_contr, coll_data::count_contr, coll_contraction::cp_count, uca_chr_seq::cp_count, uca_chr_seq::cp_list, ER_LOC_GEN, get_ce_list_from_coll_key(), GET_UCA_WEIGHT, i, intl_cp_to_utf8(), LOG_LOCALE_ERROR, MAX_UCA_EXP_CE, NO_ERROR, NULL, uca_coll_ce_list::num, locale_collation::opt_coll, uca_options::sett_strength, coll_contraction::size, locale_collation::tail_coll, TAILOR_QUATERNARY, uca_coll_key::type, coll_contraction::uca_num, coll_tailoring::uca_opt, coll_contraction::uca_w_l13, coll_contraction::uca_w_l4, uca_coll_key::val, and coll_contraction::wv.
Referenced by create_opt_ce_w_exp(), and create_opt_weights().
static int add_uca_contr_or_exp (LOCALE_COLLATION * lc, UCA_STORAGE * storage, const unsigned int * cp_array, const int cp_count, const UCA_COLL_KEY_TYPE seq_type) static
Definition at line 3050 of file uca_support.c.
References add_key_to_weight_stats_list(), assert, uca_chr_seq::ce, COLL_KEY_TYPE_CONTR, COLL_KEY_TYPE_CP, COLL_KEY_TYPE_EXP, uca_storage::count_contr, uca_storage::count_exp, uca_chr_seq::cp_count, uca_chr_seq::cp_list, ER_LOC_GEN, get_ce_list_from_coll_key(), GET_UCA_WEIGHT, i, LOC_MAX_UCA_CHARS_SEQ, LOG_LOCALE_ERROR, make_coll_key(), MAX_UCA_EXP_CE, MAX_WEIGHT_LEVELS, new_contraction(), new_expansion(), NO_ERROR, NULL, uca_coll_ce_list::num, SET_UCA_WEIGHT, coll_tailoring::sett_max_cp, locale_collation::tail_coll, and w_occurences.
Referenced by apply_tailoring_rules().
static int apply_absolute_tailoring_rules (LOCALE_COLLATION * lc) static
Definition at line 2729 of file uca_support.c.
References uca_storage::coll_cp, coll_tailoring::cub_count_rules, coll_tailoring::cub_rules, cubrid_tailor_rule::end_cp_buf, cubrid_tailor_rule::end_cp_buf_type, ER_LOC_GEN, for(), GET_UCA_WEIGHT, LOG_LOCALE_ERROR, MAX_UCA_WEIGHT, MAX_WEIGHT_LEVELS, NO_ERROR, uca_coll_ce_list::num, read_cp_from_tag(), SET_UCA_WEIGHT, cubrid_tailor_rule::start_cp_buf, cubrid_tailor_rule::start_cp_buf_type, cubrid_tailor_rule::start_weight, cubrid_tailor_rule::step, string_to_coll_ce_list(), strlen, locale_collation::tail_coll, and uca_coll_ce::weight.
Referenced by uca_process_collation().
static int apply_tailoring_rule (TAILOR_DIR dir, UCA_COLL_KEY * anchor_key, UCA_COLL_KEY * key, UCA_COLL_KEY * ref_key, T_LEVEL lvl) static
Definition at line 2161 of file uca_support.c.
References apply_tailoring_rule_identity(), apply_tailoring_rule_w_dir(), and TAILOR_IDENTITY.
Referenced by apply_tailoring_rules().
static int apply_tailoring_rule_identity (UCA_COLL_KEY * key, UCA_COLL_KEY * ref_key) static
Definition at line 2180 of file uca_support.c.
References assert, change_key_weight_list(), ER_LOC_GEN, get_ce_list_from_coll_key(), GET_UCA_WEIGHT, LOG_LOCALE_ERROR, NO_ERROR, NULL, and uca_coll_ce_list::num.
Referenced by apply_tailoring_rule().
static int apply_tailoring_rule_w_dir (TAILOR_DIR dir, UCA_COLL_KEY * anchor_key, UCA_COLL_KEY * key, UCA_COLL_KEY * ref_key, T_LEVEL lvl) static
Definition at line 2237 of file uca_support.c.
References assert, change_key_weight_list(), ER_LOC_GEN, get_ce_list_from_coll_key(), get_key_with_ce_sublist(), GET_UCA_WEIGHT, i, LOG_LOCALE_ERROR, MAX_UCA_EXP_CE, MAX_UCA_WEIGHT, NO_ERROR, NULL, uca_coll_ce_list::num, SET_UCA_WEIGHT, TAILOR_AFTER, and TAILOR_BEFORE.
Referenced by apply_tailoring_rule().
static int apply_tailoring_rules (LOCALE_COLLATION * lc) static
Definition at line 919 of file uca_support.c.
References add_uca_contr_or_exp(), tailor_rule::anchor_buf, apply_tailoring_rule(), assert, CAST_STRLEN, COLL_KEY_TYPE_CONTR, COLL_KEY_TYPE_CP, COLL_KEY_TYPE_EXP, CONTR_TAILORING_USE, coll_tailoring::count_rules, tailor_rule::direction, ER_LOC_GEN, er_msg(), ERR_MSG_SIZE, find_contr_id(), find_exp_id(), i, intl_utf8_to_cp(), intl_utf8_to_cp_list(), tailor_rule::level, LOC_MAX_UCA_CHARS_SEQ, LOG_LOCALE_ERROR, logical_pos_cp, make_coll_key(), MAX_LOGICAL_POS, MAX_UCA_CODEPOINT, tailor_rule::multiple_chars, NO_ERROR, NULL, tailor_rule::r_buf, tailor_rule::r_buf_size, tailor_rule::r_pos_type, RULE_POS_BUFFER, coll_tailoring::rules, uca_options::sett_contr_policy, uca_options::sett_expansions, coll_tailoring::sett_max_cp, strlen, tailor_rule::t_buf, tailor_rule::t_buf_size, locale_collation::tail_coll, and coll_tailoring::uca_opt.
Referenced by uca_process_collation().
static void build_compressed_uca_w_l13 (const UCA_COLL_CE_LIST * ce_list, UCA_L13_W * uca_w_l13) static
Definition at line 3544 of file uca_support.c.
References assert, GET_UCA_WEIGHT, i, NULL, and uca_coll_ce_list::num.
Referenced by add_opt_coll_contraction(), and create_opt_ce_w_exp().
static int build_key_list_groups (LOCALE_COLLATION * lc) static
Definition at line 1411 of file uca_support.c.
References uca_chr_seq::ce, uca_storage::coll_contr, uca_storage::coll_cp, COLL_KEY_TYPE_CONTR, COLL_KEY_TYPE_CP, uca_coll_key::contr_id, uca_storage::count_contr, uca_coll_key::cp, ER_LOC_GEN, GET_UCA_WEIGHT, i, uca_weight_key_list::key_list, uca_weight_key_list::list_count, LOG_LOCALE_ERROR, MAX_UCA_WEIGHT, NO_ERROR, NULL, coll_tailoring::sett_max_cp, locale_collation::tail_coll, uca_coll_key::type, uca_coll_key::val, and w_occurences.
Referenced by uca_process_collation().
static void build_uca_w_l4 (const UCA_COLL_CE_LIST * ce_list, UCA_L4_W * uca_w_l4) static
Definition at line 3573 of file uca_support.c.
References assert, GET_UCA_WEIGHT, i, NULL, and uca_coll_ce_list::num.
Referenced by create_opt_ce_w_exp().
static int change_key_weight_list (const UCA_COLL_KEY * key, UCA_W w_from, UCA_W w_to) static
Definition at line 2945 of file uca_support.c.
References add_key_to_weight_stats_list(), assert, NO_ERROR, NULL, and remove_key_from_weight_stats_list().
Referenced by apply_tailoring_rule_identity(), and apply_tailoring_rule_w_dir().
static int comp_func_coll_contr_bin (const void * arg1, const void * arg2) static
Definition at line 3249 of file uca_support.c.
References coll_contraction::c_buf, and uca_coll_contr_id::contr_ref.
Referenced by optimize_coll_contractions().
static int compare_ce_list (UCA_COLL_CE_LIST * ce_list1, UCA_COLL_CE_LIST * ce_list2, UCA_OPTIONS * uca_opt) static
Definition at line 729 of file uca_support.c.
References assert, GET_UCA_WEIGHT, i, MAX_WEIGHT_LEVELS, NULL, uca_coll_ce_list::num, uca_options::sett_backwards, uca_options::sett_caseFirst, uca_options::sett_caseLevel, uca_options::sett_strength, and uca_options::use_only_first_ce.
Referenced by create_opt_weights(), and uca_comp_func_coll_key().
static int compute_weights_per_level_stats (void) static
Definition at line 1234 of file uca_support.c.
References assert, uca_chr_seq::ce, uca_storage::coll_contr, uca_storage::coll_cp, uca_storage::count_contr, ER_LOC_GEN, GET_UCA_WEIGHT, i, LOG_LOCALE_ERROR, MAX_UCA_CODEPOINT, MAX_UCA_WEIGHT, MAX_WEIGHT_LEVELS, NO_ERROR, NULL, uca_coll_ce_list::num, SET_UCA_WEIGHT, and w_occurences.
Referenced by uca_process_collation().
static int create_opt_ce_w_exp (LOCALE_COLLATION * lc) static
Definition at line 3267 of file uca_support.c.
References add_opt_coll_contraction(), assert, build_compressed_uca_w_l13(), build_uca_w_l4(), COLL_KEY_TYPE_CONTR, COLL_KEY_TYPE_CP, CONTR_IGNORE, uca_storage::count_contr, coll_data::count_contr, ER_LOC_GEN, get_ce_list_from_coll_key(), i, INTL_GET_NEXT_CONTR_ID, INTL_IS_NEXT_CONTR, INTL_MASK_CONTR, LOG_LOCALE_ERROR, make_coll_key(), MATCH_CONTR_BOUND_FORBID, coll_data::next_cp, NO_ERROR, NULL, uca_coll_ce_list::num, locale_collation::opt_coll, optimize_coll_contractions(), set_next_value_for_coll_key(), coll_tailoring::sett_max_cp, uca_options::sett_strength, locale_collation::tail_coll, TAILOR_PRIMARY, TAILOR_QUATERNARY, uca_comp_func_coll_list_exp(), uca_comp_func_coll_list_exp_fo(), coll_data::uca_exp_num, coll_data::uca_num, coll_tailoring::uca_opt, uca_tailoring_options, coll_data::uca_w_l13, coll_data::uca_w_l4, and coll_data::w_count.
Referenced by uca_process_collation().
static int create_opt_weights (LOCALE_COLLATION * lc) static
Definition at line 1619 of file uca_support.c.
References add_opt_coll_contraction(), assert, COLL_KEY_TYPE_CONTR, COLL_KEY_TYPE_CP, compare_ce_list(), coll_data::count_contr, uca_coll_key::cp, ER_LOC_GEN, get_ce_list_from_coll_key(), i, uca_weight_key_list::key_list, uca_weight_key_list::list_count, LOG_LOCALE_ERROR, make_coll_key(), MAX_UCA_CODEPOINT, MAX_UCA_WEIGHT, coll_data::next_cp, NO_ERROR, NULL, locale_collation::opt_coll, optimize_coll_contractions(), set_next_value_for_coll_key(), coll_tailoring::sett_max_cp, locale_collation::tail_coll, uca_coll_key::type, coll_tailoring::uca_opt, uca_coll_key::val, coll_data::w_count, and coll_data::weights.
Referenced by uca_process_collation().
static int destroy_uca_instance (void) static
Definition at line 662 of file uca_support.c.
References assert, uca_storage::coll_contr, uca_storage::coll_cp, uca_storage::coll_exp, uca_storage::count_contr, uca_storage::count_exp, i, uca_weight_key_list::key_list, uca_storage::max_contr, uca_storage::max_exp, MAX_UCA_WEIGHT, MAX_WEIGHT_LEVELS, NO_ERROR, NULL, and w_occurences.
Referenced by uca_process_collation().
static int find_contr_id (const unsigned int * cp_array, const int cp_count, UCA_STORAGE * st) static
Definition at line 2491 of file uca_support.c.
References assert, uca_storage::coll_contr, uca_storage::count_contr, uca_chr_seq::cp_count, uca_chr_seq::cp_list, i, LOC_MAX_UCA_CHARS_SEQ, MAX_UNICODE_CHARS, and NULL.
Referenced by apply_tailoring_rules().
static int find_exp_id (const unsigned int * cp_array, const int cp_count, UCA_STORAGE * st) static
Definition at line 2547 of file uca_support.c.
References assert, uca_storage::coll_exp, uca_storage::count_exp, uca_chr_seq::cp_count, uca_chr_seq::cp_list, i, LOC_MAX_UCA_CHARS_SEQ, MAX_UNICODE_CHARS, and NULL.
Referenced by apply_tailoring_rules().
static UCA_COLL_CE_LIST * get_ce_list_from_coll_key (const UCA_COLL_KEY * key) static
Definition at line 1578 of file uca_support.c.
References assert, uca_chr_seq::ce, uca_storage::coll_contr, uca_storage::coll_cp, uca_storage::coll_exp, COLL_KEY_TYPE_CONTR, COLL_KEY_TYPE_CP, COLL_KEY_TYPE_EXP, uca_coll_key::contr_id, uca_storage::count_contr, uca_storage::count_exp, uca_coll_key::cp, uca_coll_key::exp_id, MAX_UCA_CODEPOINT, NULL, uca_coll_key::type, and uca_coll_key::val.
Referenced by add_opt_coll_contraction(), add_uca_contr_or_exp(), apply_tailoring_rule_identity(), apply_tailoring_rule_w_dir(), create_opt_ce_w_exp(), create_opt_weights(), get_key_with_ce_sublist(), and uca_comp_func_coll_key().
static UCA_COLL_KEY * get_key_with_ce_sublist (UCA_COLL_CE_LIST * uca_item, const int lvl) static
Definition at line 2401 of file uca_support.c.
References assert, get_ce_list_from_coll_key(), GET_UCA_WEIGHT, i, uca_weight_key_list::key_list, uca_weight_key_list::list_count, NULL, and uca_coll_ce_list::num.
Referenced by apply_tailoring_rule_w_dir().
static int init_uca_instance (LOCALE_COLLATION * lc) static
Definition at line 570 of file uca_support.c.
References assert, uca_chr_seq::ce, uca_storage::coll_contr, uca_storage::coll_cp, uca_storage::count_contr, uca_chr_seq::cp_count, uca_chr_seq::cp_list, DUCET_FILE, envvar_localedatadir_file(), ER_LOC_GEN, ER_OUT_OF_VIRTUAL_MEMORY, i, load_ducet(), LOG_LOCALE_ERROR, MAX_UCA_CODEPOINT, MAX_UCA_WEIGHT, MAX_WEIGHT_LEVELS, new_contraction(), NO_ERROR, NULL, uca_options::sett_contr_policy, coll_tailoring::sett_max_cp, locale_collation::tail_coll, coll_tailoring::uca_opt, and w_occurences.
Referenced by uca_process_collation().
static int load_ducet (const char * file_path, const int sett_contr_policy) static
Definition at line 224 of file uca_support.c.
References assert, uca_chr_seq::ce, uca_storage::coll_cp, CONTR_DUCET_USE, uca_chr_seq::cp_count, uca_chr_seq::cp_list, ER_LOC_GEN, ER_OUT_OF_VIRTUAL_MEMORY, ERR_MSG_SIZE, fopen_ex(), i, LOC_MAX_UCA_CHARS_SEQ, LOG_LOCALE_ERROR, logical_pos_cp, MAX_UCA_CODEPOINT, MAX_UCA_EXP_CE, MAX_WEIGHT_LEVELS, new_contraction(), NO_ERROR, NULL, uca_coll_ce_list::num, uca_storage::prev_contr_policy, uca_storage::prev_file_path, RULE_POS_FIRST_NON_IGN, RULE_POS_FIRST_PRI_IGN, RULE_POS_FIRST_SEC_IGN, RULE_POS_FIRST_TERT_IGN, RULE_POS_FIRST_VAR, RULE_POS_LAST_NON_IGN, RULE_POS_LAST_PRI_IGN, RULE_POS_LAST_SEC_IGN, RULE_POS_LAST_TERT_IGN, RULE_POS_LAST_TRAIL, RULE_POS_LAST_VAR, SET_UCA_WEIGHT, snprintf_dots_truncate, str_to_int32(), string_to_int_array(), uca_free_data(), and uca_coll_ce::weight.
Referenced by init_uca_instance().
static void make_coll_key (UCA_COLL_KEY * key, UCA_COLL_KEY_TYPE type, const int key_id) static
Definition at line 2456 of file uca_support.c.
References assert, COLL_KEY_TYPE_CONTR, COLL_KEY_TYPE_CP, COLL_KEY_TYPE_EXP, uca_coll_key::contr_id, uca_coll_key::cp, uca_coll_key::exp_id, NULL, uca_coll_key::type, and uca_coll_key::val.
Referenced by add_uca_contr_or_exp(), apply_tailoring_rules(), create_opt_ce_w_exp(), create_opt_weights(), and uca_comp_func_coll_list_exp().
static UCA_CONTRACTION * new_contraction (UCA_STORAGE * storage) static
Definition at line 2971 of file uca_support.c.
References assert, uca_storage::coll_contr, uca_storage::count_contr, ER_LOC_GEN, LOG_LOCALE_ERROR, uca_storage::max_contr, NULL, and UCA_CONTR_EXP_CNT_GROW.
Referenced by add_uca_contr_or_exp(), init_uca_instance(), and load_ducet().
static UCA_EXPANSION* new_expansion (UCA_STORAGE * storage) static
Definition at line 3009 of file uca_support.c.
References assert, uca_storage::coll_exp, uca_storage::count_exp, ER_LOC_GEN, LOG_LOCALE_ERROR, uca_storage::max_exp, NULL, and UCA_CONTR_EXP_CNT_GROW.
Referenced by add_uca_contr_or_exp().
static int optimize_coll_contractions (LOCALE_COLLATION * lc) static
Definition at line 1791 of file uca_support.c.
References assert, coll_contraction::c_buf, comp_func_coll_contr_bin(), coll_data::contr_list, coll_data::contr_min_size, uca_coll_contr_id::contr_ref, coll_data::count_contr, coll_data::cp_first_contr_array, coll_data::cp_first_contr_count, coll_data::cp_first_contr_offset, ER_LOC_GEN, i, INTL_GET_NEXT_CONTR_ID, INTL_IS_NEXT_CONTR, INTL_MASK_CONTR, INTL_UTF8_MAX_CHAR_SIZE, intl_utf8_to_cp(), LOC_MAX_UCA_CHARS_SEQ, LOG_LOCALE_ERROR, MAX_UNICODE_CHARS, coll_contraction::next, coll_data::next_cp, NO_ERROR, NULL, locale_collation::opt_coll, uca_coll_contr_id::pos_id, coll_contraction::size, strlen, and coll_data::w_count.
Referenced by create_opt_ce_w_exp(), and create_opt_weights().
static int read_cp_from_tag (unsigned char * buffer, CP_BUF_TYPE type, UCA_CP * cp) static
Definition at line 3162 of file uca_support.c.
References assert, BUF_TYPE_CHAR, BUF_TYPE_CODE, ER_LOC_GEN, ERR_MSG_SIZE, intl_count_utf8_chars(), intl_utf8_to_cp(), LOG_LOCALE_ERROR, NO_ERROR, NULL, str_to_int32(), and strlen.
Referenced by apply_absolute_tailoring_rules().
static int remove_key_from_weight_stats_list (const UCA_COLL_KEY * key, UCA_W wv) static
Definition at line 2884 of file uca_support.c.
References assert, i, uca_weight_key_list::list_count, and NO_ERROR.
Referenced by change_key_weight_list().
static int set_next_value_for_coll_key (LOCALE_COLLATION * lc, const UCA_COLL_KEY * coll_key, const UCA_COLL_KEY * next_key) static
Definition at line 1991 of file uca_support.c.
References assert, COLL_KEY_TYPE_CONTR, COLL_KEY_TYPE_CP, uca_coll_key::contr_id, coll_data::contr_list, coll_data::count_contr, uca_coll_key::cp, INTL_MASK_CONTR, coll_contraction::next, coll_data::next_cp, NO_ERROR, locale_collation::opt_coll, uca_coll_key::type, and uca_coll_key::val.
Referenced by create_opt_ce_w_exp(), and create_opt_weights().
static void sort_coll_key_lists (LOCALE_COLLATION * lc) static
Definition at line 1462 of file uca_support.c.
References MAX_UCA_WEIGHT, and sort_one_coll_key_list().
Referenced by uca_process_collation().
static void sort_one_coll_key_list (LOCALE_COLLATION * lc, int weight_index) static
Definition at line 1484 of file uca_support.c.
References assert, MAX_UCA_WEIGHT, and uca_comp_func_coll_key_fo().
Referenced by sort_coll_key_lists().
static int string_to_coll_ce_list (char * s, UCA_COLL_CE_LIST * ui) static
Definition at line 2603 of file uca_support.c.
References ER_LOC_GEN, LOG_LOCALE_ERROR, MAX_UCA_WEIGHT, MAX_WEIGHT_LEVELS, NO_ERROR, uca_coll_ce_list::num, SET_UCA_WEIGHT, str_to_int32(), strlen, and uca_coll_ce::weight.
Referenced by apply_absolute_tailoring_rules().
static int uca_comp_func_coll_key (const void * arg1, const void * arg2) static
Definition at line 1551 of file uca_support.c.
References assert, compare_ce_list(), get_ce_list_from_coll_key(), NULL, and uca_tailoring_options.
Referenced by uca_comp_func_coll_key_fo(), and uca_comp_func_coll_list_exp().
static int uca_comp_func_coll_key_fo (const void * arg1, const void * arg2) static
Definition at line 1510 of file uca_support.c.
References cmp, COLL_KEY_TYPE_CONTR, uca_coll_key::cp, uca_coll_key::type, uca_comp_func_coll_key(), and uca_coll_key::val.
Referenced by sort_one_coll_key_list().
static int uca_comp_func_coll_list_exp (const void * arg1, const void * arg2) static
Definition at line 3499 of file uca_support.c.
References COLL_KEY_TYPE_CONTR, COLL_KEY_TYPE_CP, INTL_GET_NEXT_CONTR_ID, INTL_IS_NEXT_CONTR, make_coll_key(), and uca_comp_func_coll_key().
Referenced by create_opt_ce_w_exp(), and uca_comp_func_coll_list_exp_fo().
static int uca_comp_func_coll_list_exp_fo (const void * arg1, const void * arg2) static
Definition at line 3474 of file uca_support.c.
References cmp, and uca_comp_func_coll_list_exp().
Referenced by create_opt_ce_w_exp().
void uca_free_data (void)
Definition at line 2119 of file uca_support.c.
References assert, uca_storage::coll_contr, uca_storage::coll_cp, uca_storage::coll_exp, uca_storage::count_contr, uca_storage::max_contr, NULL, and uca_storage::prev_file_path.
Referenced by load_ducet(), and locale_compile_locale().
int uca_process_collation (LOCALE_COLLATION * lc, bool is_verbose)
Definition at line 810 of file uca_support.c.
References apply_absolute_tailoring_rules(), apply_tailoring_rules(), build_key_list_groups(), compute_weights_per_level_stats(), uca_storage::count_contr, coll_tailoring::count_rules, create_opt_ce_w_exp(), create_opt_weights(), coll_tailoring::cub_count_rules, destroy_uca_instance(), init_uca_instance(), NO_ERROR, NULL, locale_collation::opt_coll, uca_options::sett_expansions, sort_coll_key_lists(), locale_collation::tail_coll, coll_data::uca_opt, and coll_tailoring::uca_opt.
Referenced by locale_compile_locale().
Variable Documentation
UCA_STORAGE curr_uca static
Initial value:
= {
  NULL,
  NULL, 0, 0,
  NULL, 0, 0,
  "", CONTR_IGNORE
}
Definition at line 147 of file uca_support.c.
UCA_STORAGE ducet static
Initial value:
= {
  NULL,
  NULL, 0, 0,
  NULL, 0, 0,
  "", CONTR_IGNORE
}
Definition at line 140 of file uca_support.c.
int logical_pos_cp[MAX_LOGICAL_POS] static
Definition at line 158 of file uca_support.c.
Referenced by apply_tailoring_rules(), and load_ducet().
UCA_OPTIONS* uca_tailoring_options = NULL static
Definition at line 161 of file uca_support.c.
Referenced by create_opt_ce_w_exp(), and uca_comp_func_coll_key().
UCA_W* w_occurences[MAX_WEIGHT_LEVELS] static
Definition at line 154 of file uca_support.c.
Referenced by add_uca_contr_or_exp(), build_key_list_groups(), compute_weights_per_level_stats(), destroy_uca_instance(), and init_uca_instance().
UCA_WEIGHT_KEY_LIST* weight_key_list static
Definition at line 156 of file uca_support.c.