CUBRID Engine: src/base/unicode_support.h File Reference
unicode_support.h File Reference
#include "config.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <assert.h>
Typedefs
typedef unsigned int uint32
typedef unsigned short int uint16
typedef unsigned char uchar
Functions
int unicode_process_alphabet (LOCALE_DATA *ld, bool is_verbose)
int unicode_process_normalization (LOCALE_DATA *ld, bool is_verbose)
void unicode_free_data (void)
bool unicode_string_need_compose (const char *str_in, const int size_in, int *size_out, const UNICODE_NORMALIZATION *norm)
void unicode_compose_string (const char *str_in, const int size_in, char *str_out, int *size_out, bool *is_composed, const UNICODE_NORMALIZATION *norm)
bool unicode_string_need_decompose (const char *str_in, const int size_in, int *decomp_size, const UNICODE_NORMALIZATION *norm)
void unicode_decompose_string (const char *str_in, const int size_in, char *str_out, int *size_out, const UNICODE_NORMALIZATION *norm)
int string_to_int_array (char *s, uint32 *cp_list, const int cp_list_size, const char *delims)
Typedef Documentation
typedef unsigned char uchar
Definition at line 36 of file unicode_support.h.
typedef unsigned short int uint16
Definition at line 35 of file unicode_support.h.
typedef unsigned int uint32
Definition at line 34 of file unicode_support.h.
Function Documentation
int string_to_int_array (char * s, uint32 * cp_list, const int cp_list_size, const char * delims)
Definition at line 661 of file unicode_support.c.
References assert, i, NULL, str_to_uint32(), and strlen.
Referenced by load_ducet(), and load_unicode_data().
void unicode_compose_string (const char * str_in, const int size_in, char * str_out, int * size_out, bool * is_composed, const UNICODE_NORMALIZATION * norm)
Definition at line 1174 of file unicode_support.c.
References assert, unicode_mapping::buffer, CAST_STRLEN, unicode_mapping::cp, CP_HAS_MAPPINGS, GET_MAPPING_OFFSET, i, intl_cp_to_utf8(), intl_utf8_to_cp(), MAX_UNICODE_CHARS, NULL, prm_get_bool_value(), PRM_ID_UNICODE_INPUT_NORMALIZATION, unicode_mapping::size, str_out(), unicode_normalization::unicode_mapping_index, and unicode_normalization::unicode_mappings.
Referenced by csql_help_schema(), csql_help_trigger(), jsp_unpack_string_value(), and netval_to_dbval().
void unicode_decompose_string (const char * str_in, const int size_in, char * str_out, int * size_out, const UNICODE_NORMALIZATION * norm)
Definition at line 1359 of file unicode_support.c.
References assert, unicode_mapping::buffer, CAST_STRLEN, if(), intl_utf8_to_cp(), unicode_normalization::list_full_decomp, MAX_UNICODE_CHARS, NULL, prm_get_bool_value(), PRM_ID_UNICODE_OUTPUT_NORMALIZATION, unicode_mapping::size, str_out(), and unicode_normalization::unicode_mappings.
Referenced by csql_db_value_as_string(), dbval_to_net_buf(), and jsp_pack_string_argument().
void unicode_free_data (void)
Definition at line 565 of file unicode_support.c.
References last_unicode_file, and NULL.
Referenced by load_unicode_data(), and locale_compile_locale().
int unicode_process_alphabet (LOCALE_DATA * ld, bool is_verbose)
Definition at line 134 of file unicode_support.c.
References alphabet_data::a_type, locale_data::alpha_tailoring, locale_data::alphabet, ALPHABET_ASCII, alphabet_tailoring::alphabet_mode, ALPHABET_TAILORED, ALPHABET_UNICODE, assert, CAT_Ll, CAT_Lu, alphabet_tailoring::count_rules, create_alphabet(), transform_rule::dest, transform_rule::dest_size, envvar_localedatadir_file(), ER_LOC_GEN, ERR_MSG_SIZE, error(), i, locale_data::identif_alphabet, INTL_CASING_EXPANSION_MULTIPLIER, intl_utf8_to_cp_list(), load_unicode_data(), LOG_LOCALE_ERROR, UNICODE_CHAR::lower_cp, alphabet_data::lower_cp, NO_ERROR, NULL, alphabet_tailoring::rules, alphabet_tailoring::sett_max_letters, transform_rule::src, transform_rule::src_size, TR_LOWER, TR_UPPER, transform_rule::type, alphabet_tailoring::unicode_data_file, unicode_data_lower_mult, unicode_data_upper_mult, UNICODEDATA_FILE, UNICODE_CHAR::upper_cp, and alphabet_data::upper_cp.
Referenced by locale_compile_locale().
int unicode_process_normalization (LOCALE_DATA * ld, bool is_verbose)
Definition at line 711 of file unicode_support.c.
References assert, comp_func_grouping_unicode_cp_mapping(), comp_func_unicode_cp_mapping(), count_decomp_steps(), count_full_decomp_cp(), UNICODE_CP_MAPPING::cp, CP_HAS_MAPPINGS, ER_LOC_GEN, GET_MAPPING_OFFSET, i, UNICODE_CP_MAPPING::is_full_decomp, load_unicode_data(), LOG_LOCALE_ERROR, UNICODE_CP_MAPPING::map, MAX_UNICODE_CHARS, NO_ERROR, NULL, SET_MAPPING_INDEX, UNICODE_CP_MAPPING::size, UNICODE_CHAR::unicode_full_decomp_cp_count, unicode_make_normalization_data(), UNICODE_CHAR::unicode_mapping, UNICODE_CHAR::unicode_mapping_cp_count, unicode_normalization::unicode_mapping_index, unicode_normalization::unicode_mappings_count, and locale_data::unicode_normalization.
Referenced by locale_compile_locale().
bool unicode_string_need_compose (const char * str_in, const int size_in, int * size_out, const UNICODE_NORMALIZATION * norm)
Definition at line 1128 of file unicode_support.c.
References assert, NULL, prm_get_bool_value(), and PRM_ID_UNICODE_INPUT_NORMALIZATION.
Referenced by csql_help_schema(), csql_help_trigger(), jsp_unpack_string_value(), and netval_to_dbval().
bool unicode_string_need_decompose (const char * str_in, const int size_in, int * decomp_size, const UNICODE_NORMALIZATION * norm)
Definition at line 1274 of file unicode_support.c.
References assert, CAST_STRLEN, if(), intl_utf8_to_cp(), unicode_normalization::list_full_decomp, MAX_UNICODE_CHARS, NULL, prm_get_bool_value(), PRM_ID_UNICODE_OUTPUT_NORMALIZATION, unicode_mapping::size, and unicode_normalization::unicode_mappings.
Referenced by csql_db_value_as_string(), dbval_to_net_buf(), and jsp_pack_string_argument().