CUBRID Engine: src/executables/unittests_bit.c File Reference
unittests_bit.c File Reference
#include "bit.h"
#include "system.h"
#include <assert.h>
#include <cstring>
#include <stdlib.h>
Functions
static int count_bits (const unsigned char *mem, int nbits)
static int ctz8 (UINT8 x)
static int ctz16 (UINT16 x)
static int ctz32 (UINT32 x)
static int ctz64 (UINT64 x)
static void bitset_string (const unsigned char *mem, int nbits, char *bitset)
int main (int ignore_argc, char **ignore_argv)
Function Documentation
static void bitset_string (const unsigned char * mem, int nbits, char * bitset) static
Definition at line 106 of file unittests_bit.c.
References cubregex::count().
Referenced by main().
static int count_bits (const unsigned char * mem, int nbits) static
Definition at line 31 of file unittests_bit.c.
References cubregex::count().
Referenced by mvcc_active_tran::compute_highest_completed_mvccid(), mvcc_active_tran::compute_lowest_active_mvccid(), main(), and set_seg_expr().
static int ctz16 (UINT16 x) static
Definition at line 64 of file unittests_bit.c.
References i.
Referenced by main().
static int ctz32 (UINT32 x) static
Definition at line 78 of file unittests_bit.c.
References i.
Referenced by main().
static int ctz64 (UINT64 x) static
Definition at line 92 of file unittests_bit.c.
References i.
Referenced by main().
static int ctz8 (UINT8 x) static
Definition at line 50 of file unittests_bit.c.
References i.
Referenced by main().
int main (int ignore_argc, char ** ignore_argv)
Definition at line 123 of file unittests_bit.c.
References bit16_count_ones(), bit16_count_trailing_ones(), bit16_count_trailing_zeros(), bit16_count_zeros(), bit32_count_ones(), bit32_count_trailing_ones(), bit32_count_trailing_zeros(), bit32_count_zeros(), bit64_count_ones(), bit64_count_trailing_ones(), bit64_count_trailing_zeros(), bit64_count_zeros(), bit8_count_ones(), bit8_count_trailing_ones(), bit8_count_trailing_zeros(), bit8_count_zeros(), bitset_string(), count_bits(), ctz16(), ctz32(), ctz64(), ctz8(), i, and NULL.