CUBRID Engine: src/executables/unittests_area.c File Reference
unittests_area.c File Reference
#include "dbtype_def.h"
#include "db_set.h"
#include "porting.h"
#include "lock_free.h"
#include "object_domain.h"
#include "set_object.h"
#include <stdio.h>
#include <pthread.h>
#include <sys/time.h>
#include <assert.h>
#include "class_object.h"
#include "object_template.h"
Classes
struct area_create_info
Macros
#define strlen(s1) ((int) strlen(s1))
#define SERVER_MODE
#define MSG_LEN 60
#define NOPS 1000000 /* 1M */
#define NOPS 1000000 /* 1M */
#define NCACHES 32
#define NOPS 1000000 /* 1M */
#define NCACHES 500
#define MAX_THREADS 64
Typedefs
typedef struct area_create_info AREA_CREATE_INFO
Functions
void * test_area_proc (void *param)
void * test_area_proc_1 (void *param)
void * test_area_proc_2 (void *param)
static void begin (char *test_name)
static int success ()
static int fail (const char *message)
static int test_area (AREA_CREATE_INFO *info, int nthreads, void *(*proc)(void *))
int main (int argc, char **argv)
Variables
static struct timeval start_time
Macro Definition Documentation
#define MAX_THREADS 64
Referenced by test_area().
#define MSG_LEN 60
Referenced by begin().
#define NCACHES 32
Referenced by test_area_proc_1(), and test_area_proc_2().
#define NCACHES 500
#define NOPS 1000000 /* 1M */
Referenced by test_area_proc(), test_area_proc_1(), and test_area_proc_2().
#define NOPS 1000000 /* 1M */
#define NOPS 1000000 /* 1M */
#define SERVER_MODE
Definition at line 41 of file unittests_area.c.
Referenced by btree_split_node_and_advance(), dwb_flush_block(), and qmgr_clear_trans_wakeup().
#define strlen (s1) ((int) strlen(s1))
Definition at line 35 of file unittests_area.c.
Referenced by begin().
Typedef Documentation
typedef struct area_create_info AREA_CREATE_INFO
Definition at line 44 of file unittests_area.c.
Function Documentation
static void begin (char * test_name) static
Definition at line 60 of file unittests_area.c.
References i, MSG_LEN, NULL, start_time, and strlen.
Referenced by checksumdb(), css_receive_data(), css_receive_error(), itoa_strreverse(), cubthread::looper::looper(), ltrim(), and test_area().
static int fail (const char * message) static
Definition at line 94 of file unittests_area.c.
References assert, and ER_FAILED.
Referenced by main(), and test_area().
int main (int argc, char ** argv)
Definition at line 346 of file unittests_area.c.
References ER_FAILED, fail(), i, NO_ERROR, test_area(), test_area_proc(), test_area_proc_1(), and test_area_proc_2().
static int success () static
Definition at line 78 of file unittests_area.c.
References NO_ERROR, NULL, and start_time.
Referenced by add_access_spec(), boot_backup(), boot_check_db_consistency(), boot_compact_classes(), boot_heap_compact(), btree_class_test_unique(), btree_delete_index(), btree_find_split_point(), btree_get_statistics(), catalog_add_class_info(), catalog_check_rep_dir(), catalog_initialize_new_page(), catalog_put_representation_item(), catalog_rv_insert_redo(), catalog_rv_new_page_redo(), cfg_delete_db(), chksum_insert_repl_log_and_demote_table_lock(), compact_db_start(), compact_db_stop(), css_tcp_client_open_with_retry(), css_tcp_master_datagram(), db_local_transaction_id(), ehash_distribute_records_into_two_bucket(), ehash_initialize_bucket_new_page(), ehash_insert_to_bucket(), ehash_merge_permanent(), ehash_rv_init_bucket_redo(), ehash_rv_insert_redo(), lf_hash_table_cpp< Key, T >::erase(), lockfree::hashmap< Key, T >::erase_locked(), lf_hash_table_cpp< Key, T >::erase_locked(), file_apply_tde_to_class_files(), fileio_finish_restore(), fileio_get_primitive_way_max(), fileio_reset_volume(), fileio_synchronize_all(), fpcache_remove_by_class(), heap_cache_class_info(), heap_create(), heap_delete_hfid_from_cache(), heap_destroy_newly_created(), heap_get_class_num_objects_pages(), heap_reclaim_addresses(), jsp_connect_server(), locator_assign_oid(), locator_assign_oid_batch(), locator_does_exist(), locator_fetch(), locator_fetch_all(), locator_fetch_all_reference_lockset(), locator_fetch_lockhint_classes(), locator_fetch_lockset(), locator_get_class(), locator_log_force_nologging(), locator_notify_isolation_incons(), locator_redistribute_partition_data(), locator_remove_class_from_index(), locator_upgrade_instances_domain(), logpb_restore(), net_client_request_3_data_recv_copyarea(), or_get_current_default_value(), or_get_default_value(), or_get_hierarchy_helper(), or_install_btids_attribute(), perfmon_server_calc_stats(), perfmon_stat_dump_in_buffer_promote_page_array_stat(), perfmon_stat_dump_in_file_promote_page_array_stat(), pgbuf_claim_bcb_for_fix(), qexec_end_mainblock_iterations(), qfile_combine_two_list(), qfile_get_list_file_page(), qmgr_end_query(), qp_get_server_info(), repl_log_get_append_lsa(), repl_set_info(), sboot_backup(), sboot_check_db_consistency(), sboot_compact_db(), sboot_compact_start(), sboot_compact_stop(), sboot_heap_compact(), sboot_notify_unregister_client(), sbtree_class_test_unique(), sbtree_delete_index(), sbtree_find_unique_internal(), sbtree_get_statistics(), schksum_insert_repl_log_and_demote_table_lock(), sct_check_rep_dir(), session_remove_expired_sessions(), session_state_destroy(), shf_get_class_num_objs_and_pages(), slocator_assign_oid(), slocator_assign_oid_batch(), slocator_fetch(), slocator_fetch_all(), slocator_fetch_all_reference_lockset(), slocator_fetch_lockhint_classes(), slocator_fetch_lockset(), slocator_force(), slocator_get_class(), slocator_notify_isolation_incons(), slocator_redistribute_partition_data(), slocator_remove_class_from_index(), slocator_repl_force(), slocator_upgrade_instances_domain(), sm_flush_for_multi_update(), spage_free_saved_spaces(), sqp_get_server_info(), srepl_set_info(), stats_update_all_statistics(), stats_update_statistics(), sthread_kill_or_interrupt_tran(), sthread_kill_tran_index(), stran_get_local_transaction_id(), stran_lock_rep_read(), stran_server_get_global_tran_info(), stran_server_savepoint(), stran_server_set_global_tran_info(), stran_server_start_topop(), tde_change_mk_on_server(), tde_get_mk_info(), test_area(), thread_kill_or_interrupt_tran(), thread_kill_tran_index(), tran_server_2pc_prepare_global_tran(), tran_server_get_global_tran_info(), tran_server_savepoint(), tran_server_set_global_tran_info(), and update_indexes().
static int test_area (AREA_CREATE_INFO * info, int nthreads, void *(*)(void *) proc) static
Definition at line 259 of file unittests_area.c.
References area_create_info::alloc_cnt, area_create(), area_destroy(), area_final(), area_init(), assert, begin(), lockfree::bitmap::bitfield, area_block::bitmap, area::blockset_list, CEIL_PTVDIV, lockfree::bitmap::entry_count, area_create_info::entry_size, fail(), i, area_blockset_list::items, LF_BITFIELD_WORD_SIZE, MAX_THREADS, area_create_info::name, area_blockset_list::next, NO_ERROR, NULL, success(), and area_blockset_list::used_count.
Referenced by main().
void * test_area_proc (void * param)
Definition at line 103 of file unittests_area.c.
References area_alloc(), area_free(), ER_FAILED, error(), i, NO_ERROR, NOPS, and NULL.
Referenced by main().
void * test_area_proc_1 (void * param)
Definition at line 137 of file unittests_area.c.
References area_alloc(), area_free(), ER_FAILED, error(), i, NCACHES, NO_ERROR, NOPS, and NULL.
Referenced by main().
void * test_area_proc_2 (void * param)
Definition at line 202 of file unittests_area.c.
References area_alloc(), area_free(), ER_FAILED, error(), i, NCACHES, NO_ERROR, NOPS, and NULL.
Referenced by main().
Variable Documentation
struct timeval start_time static
Definition at line 57 of file unittests_area.c.
Referenced by applyinfo(), begin(), css_start_all_threads(), la_commit_transaction(), and success().