CUBRID Engine: src/executables/utility.h File Reference
utility.h File Reference
#include <stdio.h>
#include "config.h"
#include "cubrid_getopt.h"
#include "util_func.h"
#include "dynamic_array.h"
Classes
struct UTIL_ARG_MAP
struct UTIL_MAP
struct _node_config
struct _ha_config
struct UTIL_KEYWORD
struct UTIL_FUNCTION_ARG
Macros
#define OPTION_STRING_TABLE 10000
#define UTIL_EXE_EXT ""
#define UTIL_MASTER_NAME "cub_master" UTIL_EXE_EXT
#define UTIL_COMMDB_NAME "cub_commdb" UTIL_EXE_EXT
#define UTIL_CUBRID_NAME "cub_server" UTIL_EXE_EXT
#define UTIL_BROKER_NAME "cubrid_broker" UTIL_EXE_EXT
#define UTIL_MONITOR_NAME "broker_monitor" UTIL_EXE_EXT
#define UTIL_TESTER_NAME "broker_tester" UTIL_EXE_EXT
#define UTIL_CUB_MANAGER_NAME "cub_manager" UTIL_EXE_EXT
#define UTIL_ADMIN_NAME "cub_admin" UTIL_EXE_EXT
#define UTIL_SQLX_NAME "sqlx" UTIL_EXE_EXT
#define UTIL_CSQL_NAME "csql" UTIL_EXE_EXT
#define UTIL_CUBRID_REL_NAME "cubrid_rel" UTIL_EXE_EXT
#define UTIL_OLD_COMMDB_NAME "commdb" UTIL_EXE_EXT
#define UTIL_CUBRID "cubrid" UTIL_EXE_EXT
#define UTIL_COPYLOGDB "copylogdb" UTIL_EXE_EXT
#define UTIL_APPLYLOGDB "applylogdb" UTIL_EXE_EXT
#define UTIL_JAVASP_NAME "cub_javasp" UTIL_EXE_EXT
#define PROPERTY_ON "on"
#define PROPERTY_OFF "off"
#define PRINT_SERVICE_NAME "cubrid service"
#define PRINT_MASTER_NAME "cubrid master"
#define PRINT_SERVER_NAME "cubrid server"
#define PRINT_BROKER_NAME "cubrid broker"
#define PRINT_MANAGER_NAME "cubrid manager server"
#define PRINT_HEARTBEAT_NAME "cubrid heartbeat"
#define PRINT_JAVASP_NAME "cubrid javasp"
#define PRINT_HA_PROCS_NAME "HA processes"
#define PRINT_CMD_SERVICE "service"
#define PRINT_CMD_BROKER "broker"
#define PRINT_CMD_MANAGER "manager"
#define PRINT_CMD_SERVER "server"
#define PRINT_CMD_JAVASP "javasp"
#define PRINT_CMD_START "start"
#define PRINT_CMD_STOP "stop"
#define PRINT_CMD_STATUS "status"
#define PRINT_CMD_DEREG "deregister"
#define PRINT_CMD_LIST "list"
#define PRINT_CMD_RELOAD "reload"
#define PRINT_CMD_ACL "acl"
#define PRINT_CMD_COPYLOGDB "copylogdb"
#define PRINT_CMD_APPLYLOGDB "applylogdb"
#define PRINT_CMD_GETID "getid"
#define PRINT_CMD_TEST "test"
#define PRINT_CMD_REPLICATION "replication"
#define PRINT_RESULT_SUCCESS "success"
#define PRINT_RESULT_FAIL "fail"
#define CHECK_SERVER "Server"
#define CHECK_HA_SERVER "HA-Server"
#define COMMDB_SERVER_STOP "-S"
#define COMMDB_SERVER_STATUS "-P"
#define COMMDB_ALL_STATUS "-O"
#define COMMDB_ALL_STOP "-A"
#define COMMDB_HA_DEREG_BY_PID "-D"
#define COMMDB_HA_DEREG_BY_ARGS "-R"
#define COMMDB_HA_ALL_STOP "-d"
#define COMMDB_IS_REG "-C"
#define COMMDB_HA_NODE_LIST "-N"
#define COMMDB_HA_PROC_LIST "-L"
#define COMMDB_HA_PING_HOST_LIST "-p"
#define COMMDB_HA_RELOAD "-F"
#define COMMDB_HA_DEACT_STOP_ALL "--deact-stop-all"
#define COMMDB_HA_DEACT_CONFIRM_STOP_ALL "--deact-confirm-stop-all"
#define COMMDB_HA_DEACT_CONFIRM_NO_SERVER "--deact-confirm-no-server"
#define COMMDB_HA_DEACTIVATE "--deactivate-heartbeat"
#define COMMDB_HA_ACTIVATE "--activate-heartbeat"
#define COMMDB_HOST "-h"
#define COMMDB_HB_DEACT_IMMEDIATELY "-i"
#define COMMDB_HA_ADMIN_INFO "--admin-info"
#define COMMDB_VERBOSE_OUTPUT "--verbose"
#define COMMDB_HA_START_UTIL_PROCESS "-t"
#define ACLDB_RELOAD "-r"
#define MASK_ALL 0xFF
#define MASK_SERVICE 0x01
#define MASK_SERVER 0x02
#define MASK_BROKER 0x04
#define MASK_MANAGER 0x08
#define MASK_ADMIN 0x20
#define MASK_HEARTBEAT 0x40
#define MASK_JAVASP 0x80
#define UTIL_OPTION_CREATEDB "createdb"
#define UTIL_OPTION_RENAMEDB "renamedb"
#define UTIL_OPTION_COPYDB "copydb"
#define UTIL_OPTION_DELETEDB "deletedb"
#define UTIL_OPTION_BACKUPDB "backupdb"
#define UTIL_OPTION_RESTOREDB "restoredb"
#define UTIL_OPTION_ADDVOLDB "addvoldb"
#define UTIL_OPTION_SPACEDB "spacedb"
#define UTIL_OPTION_LOCKDB "lockdb"
#define UTIL_OPTION_TRANLIST "tranlist"
#define UTIL_OPTION_KILLTRAN "killtran"
#define UTIL_OPTION_OPTIMIZEDB "optimizedb"
#define UTIL_OPTION_INSTALLDB "installdb"
#define UTIL_OPTION_DIAGDB "diagdb"
#define UTIL_OPTION_PATCHDB "emergency_patchlog"
#define UTIL_OPTION_CHECKDB "checkdb"
#define UTIL_OPTION_ALTERDBHOST "alterdbhost"
#define UTIL_OPTION_PLANDUMP "plandump"
#define UTIL_OPTION_ESTIMATE_DATA "estimate_data"
#define UTIL_OPTION_ESTIMATE_INDEX "estimate_index"
#define UTIL_OPTION_LOADDB "loaddb"
#define UTIL_OPTION_UNLOADDB "unloaddb"
#define UTIL_OPTION_COMPACTDB "compactdb"
#define UTIL_OPTION_PARAMDUMP "paramdump"
#define UTIL_OPTION_STATDUMP "statdump"
#define UTIL_OPTION_CHANGEMODE "changemode"
#define UTIL_OPTION_COPYLOGDB "copylogdb"
#define UTIL_OPTION_APPLYLOGDB "applylogdb"
#define UTIL_OPTION_LOGFILEDUMP "logfiledump"
#define UTIL_OPTION_APPLYINFO "applyinfo"
#define UTIL_OPTION_ACLDB "acldb"
#define UTIL_OPTION_GENERATE_LOCALE "genlocale"
#define UTIL_OPTION_DUMP_LOCALE "dumplocale"
#define UTIL_OPTION_SYNCCOLLDB "synccolldb"
#define UTIL_OPTION_GEN_TZ "gen_tz"
#define UTIL_OPTION_DUMP_TZ "dump_tz"
#define UTIL_OPTION_RESTORESLAVE "restoreslave"
#define UTIL_OPTION_VACUUMDB "vacuumdb"
#define UTIL_OPTION_CHECKSUMDB "checksumdb"
#define UTIL_OPTION_TDE "tde"
#define HIDDEN_CS_MODE_S 15000
#define CREATE_PAGES_S 'p'
#define CREATE_PAGES_L "pages"
#define CREATE_COMMENT_S 10102
#define CREATE_COMMENT_L "comment"
#define CREATE_FILE_PATH_S 'F'
#define CREATE_FILE_PATH_L "file-path"
#define CREATE_LOG_PATH_S 'L'
#define CREATE_LOG_PATH_L "log-path"
#define CREATE_LOB_PATH_S 'B'
#define CREATE_LOB_PATH_L "lob-base-path"
#define CREATE_SERVER_NAME_S 10105
#define CREATE_SERVER_NAME_L "server-name"
#define CREATE_REPLACE_S 'r'
#define CREATE_REPLACE_L "replace"
#define CREATE_MORE_VOLUME_FILE_S 10107
#define CREATE_MORE_VOLUME_FILE_L "more-volume-file"
#define CREATE_USER_DEFINITION_FILE_S 10108
#define CREATE_USER_DEFINITION_FILE_L "user-definition-file"
#define CREATE_CSQL_INITIALIZATION_FILE_S 10109
#define CREATE_CSQL_INITIALIZATION_FILE_L "csql-initialization-file"
#define CREATE_OUTPUT_FILE_S 'o'
#define CREATE_OUTPUT_FILE_L "output-file"
#define CREATE_VERBOSE_S 'v'
#define CREATE_VERBOSE_L "verbose"
#define CREATE_CHARSET_S 10112
#define CREATE_CHARSET_L "charset"
#define CREATE_LOG_PAGE_COUNT_S 'l'
#define CREATE_LOG_PAGE_COUNT_L "log-page-count"
#define CREATE_PAGE_SIZE_S 's'
#define CREATE_PAGE_SIZE_L "page-size"
#define CREATE_LOG_PAGE_SIZE_S 10113
#define CREATE_LOG_PAGE_SIZE_L "log-page-size"
#define CREATE_DB_PAGE_SIZE_S 10114
#define CREATE_DB_PAGE_SIZE_L "db-page-size"
#define CREATE_DB_VOLUME_SIZE_S 10115
#define CREATE_DB_VOLUME_SIZE_L "db-volume-size"
#define CREATE_LOG_VOLUME_SIZE_S 10116
#define CREATE_LOG_VOLUME_SIZE_L "log-volume-size"
#define RENAME_EXTENTED_VOLUME_PATH_S 'E'
#define RENAME_EXTENTED_VOLUME_PATH_L "extended-volume-path"
#define RENAME_CONTROL_FILE_S 'i'
#define RENAME_CONTROL_FILE_L "control-file"
#define RENAME_DELETE_BACKUP_S 'd'
#define RENAME_DELETE_BACKUP_L "delete-backup"
#define COPY_SERVER_NAME_S 10300
#define COPY_SERVER_NAME_L "server-name"
#define COPY_FILE_PATH_S 'F'
#define COPY_FILE_PATH_L "file-path"
#define COPY_LOG_PATH_S 'L'
#define COPY_LOG_PATH_L "log-path"
#define COPY_EXTENTED_VOLUME_PATH_S 'E'
#define COPY_EXTENTED_VOLUME_PATH_L "extended-volume-path"
#define COPY_CONTROL_FILE_S 'i'
#define COPY_CONTROL_FILE_L "control-file"
#define COPY_REPLACE_S 'r'
#define COPY_REPLACE_L "replace"
#define COPY_DELETE_SOURCE_S 'd'
#define COPY_DELETE_SOURCE_L "delete-source"
#define COPY_LOB_PATH_S 'B'
#define COPY_LOB_PATH_L "lob-base-path"
#define COPY_COPY_LOB_PATH_S 10308
#define COPY_COPY_LOB_PATH_L "copy-lob-path"
#define DELETE_OUTPUT_FILE_S 'o'
#define DELETE_OUTPUT_FILE_L "output-file"
#define DELETE_DELETE_BACKUP_S 'd'
#define DELETE_DELETE_BACKUP_L "delete-backup"
#define BACKUP_DESTINATION_PATH_S 'D'
#define BACKUP_DESTINATION_PATH_L "destination-path"
#define BACKUP_REMOVE_ARCHIVE_S 'r'
#define BACKUP_REMOVE_ARCHIVE_L "remove-archive"
#define BACKUP_LEVEL_S 'l'
#define BACKUP_LEVEL_L "level"
#define BACKUP_OUTPUT_FILE_S 'o'
#define BACKUP_OUTPUT_FILE_L "output-file"
#define BACKUP_SA_MODE_S 'S'
#define BACKUP_SA_MODE_L "SA-mode"
#define BACKUP_CS_MODE_S 'C'
#define BACKUP_CS_MODE_L "CS-mode"
#define BACKUP_NO_CHECK_S 10506
#define BACKUP_NO_CHECK_L "no-check"
#define BACKUP_THREAD_COUNT_S 't'
#define BACKUP_THREAD_COUNT_L "thread-count"
#define BACKUP_COMPRESS_S 'z'
#define BACKUP_COMPRESS_L "compress"
#define BACKUP_EXCEPT_ACTIVE_LOG_S 'e'
#define BACKUP_EXCEPT_ACTIVE_LOG_L "except-active-log"
#define BACKUP_SLEEP_MSECS_S 10600
#define BACKUP_SLEEP_MSECS_L "sleep-msecs"
#define BACKUP_SEPARATE_KEYS_S 'k'
#define BACKUP_SEPARATE_KEYS_L "separate-keys"
#define RESTORE_UP_TO_DATE_S 'd'
#define RESTORE_UP_TO_DATE_L "up-to-date"
#define RESTORE_LIST_S 10601
#define RESTORE_LIST_L "list"
#define RESTORE_BACKUP_FILE_PATH_S 'B'
#define RESTORE_BACKUP_FILE_PATH_L "backup-file-path"
#define RESTORE_LEVEL_S 'l'
#define RESTORE_LEVEL_L "level"
#define RESTORE_PARTIAL_RECOVERY_S 'p'
#define RESTORE_PARTIAL_RECOVERY_L "partial-recovery"
#define RESTORE_OUTPUT_FILE_S 'o'
#define RESTORE_OUTPUT_FILE_L "output-file"
#define RESTORE_USE_DATABASE_LOCATION_PATH_S 'u'
#define RESTORE_USE_DATABASE_LOCATION_PATH_L "use-database-location-path"
#define RESTORE_KEYS_FILE_PATH_S 'k'
#define RESTORE_KEYS_FILE_PATH_L "keys-file-path"
#define ADDVOL_VOLUME_NAME_S 'n'
#define ADDVOL_VOLUME_NAME_L "volume-name"
#define ADDVOL_FILE_PATH_S 'F'
#define ADDVOL_FILE_PATH_L "file-path"
#define ADDVOL_COMMENT_S 10702
#define ADDVOL_COMMENT_L "comment"
#define ADDVOL_PURPOSE_S 'p'
#define ADDVOL_PURPOSE_L "purpose"
#define ADDVOL_SA_MODE_S 'S'
#define ADDVOL_SA_MODE_L "SA-mode"
#define ADDVOL_CS_MODE_S 'C'
#define ADDVOL_CS_MODE_L "CS-mode"
#define ADDVOL_VOLUME_SIZE_S 10706
#define ADDVOL_VOLUME_SIZE_L "db-volume-size"
#define ADDVOL_MAX_WRITESIZE_IN_SEC_S 10707
#define ADDVOL_MAX_WRITESIZE_IN_SEC_L "max-writesize-in-sec"
#define SPACE_OUTPUT_FILE_S 'o'
#define SPACE_OUTPUT_FILE_L "output-file"
#define SPACE_SA_MODE_S 'S'
#define SPACE_SA_MODE_L "SA-mode"
#define SPACE_CS_MODE_S 'C'
#define SPACE_CS_MODE_L "CS-mode"
#define SPACE_SIZE_UNIT_S 10803
#define SPACE_SIZE_UNIT_L "size-unit"
#define SPACE_SUMMARIZE_S 's'
#define SPACE_SUMMARIZE_L "summarize"
#define SPACE_PURPOSE_S 'p'
#define SPACE_PURPOSE_L "purpose"
#define LOCK_OUTPUT_FILE_S 'o'
#define LOCK_OUTPUT_FILE_L "output-file"
#define OPTIMIZE_CLASS_NAME_S 'n'
#define OPTIMIZE_CLASS_NAME_L "class-name"
#define INSTALL_SERVER_NAME_S 11100
#define INSTALL_SERVER_NAME_L "server-name"
#define INSTALL_FILE_PATH_S 'F'
#define INSTALL_FILE_PATH_L "file-path"
#define INSTALL_LOG_PATH_S 'L'
#define INSTALL_LOG_PATH_L "log-path"
#define DIAG_DUMP_TYPE_S 'd'
#define DIAG_DUMP_TYPE_L "dump-type"
#define DIAG_DUMP_RECORDS_S 11201
#define DIAG_DUMP_RECORDS_L "dump-records"
#define DIAG_OUTPUT_FILE_S 'o'
#define DIAG_OUTPUT_FILE_L "output-file"
#define DIAG_EMERGENCY_S 11202
#define DIAG_EMERGENCY_L "emergency"
#define PATCH_RECREATE_LOG_S 'r'
#define PATCH_RECREATE_LOG_L "recreate-log"
#define ALTERDBHOST_HOST_S 'h'
#define ALTERDBHOST_HOST_L "host"
#define CHECK_SA_MODE_S 'S'
#define CHECK_SA_MODE_L "SA-mode"
#define CHECK_CS_MODE_S 'C'
#define CHECK_CS_MODE_L "CS-mode"
#define CHECK_REPAIR_S 'r'
#define CHECK_REPAIR_L "repair"
#define CHECK_INPUT_FILE_S 'i'
#define CHECK_INPUT_FILE_L "input-file"
#define CHECK_INDEXNAME_S 'I'
#define CHECK_INDEXNAME_L "index-name"
#define CHECK_CHECK_PREV_LINK_S 11501
#define CHECK_CHECK_PREV_LINK_L "check-prev-link"
#define CHECK_REPAIR_PREV_LINK_S 11502
#define CHECK_REPAIR_PREV_LINK_L "repair-prev-link"
#define CHECK_FILE_TRACKER_S 11503
#define CHECK_FILE_TRACKER_L "check-file-tracker"
#define CHECK_HEAP_ALLHEAPS_S 11504
#define CHECK_HEAP_ALLHEAPS_L "check-heap"
#define CHECK_CAT_CONSISTENCY_S 11505
#define CHECK_CAT_CONSISTENCY_L "check-catalog"
#define CHECK_BTREE_ALL_BTREES_S 11506
#define CHECK_BTREE_ALL_BTREES_L "check-btree"
#define CHECK_LC_CLASSNAMES_S 11507
#define CHECK_LC_CLASSNAMES_L "check-class-name"
#define CHECK_LC_ALLENTRIES_OF_ALLBTREES_S 11508
#define CHECK_LC_ALLENTRIES_OF_ALLBTREES_L "check-btree-entries"
#define PLANDUMP_DROP_S 'd'
#define PLANDUMP_DROP_L "drop"
#define PLANDUMP_OUTPUT_FILE_S 'o'
#define PLANDUMP_OUTPUT_FILE_L "output-file"
#define TRANLIST_SUMMARY_S 's'
#define TRANLIST_SUMMARY_L "summary"
#define TRANLIST_SORT_KEY_S 'k'
#define TRANLIST_SORT_KEY_L "sort-key"
#define TRANLIST_REVERSE_S 'r'
#define TRANLIST_REVERSE_L "reverse"
#define TRANLIST_FULL_SQL_S 'f'
#define TRANLIST_FULL_SQL_L "full"
#define KILLTRAN_KILL_TRANSACTION_INDEX_S 'i'
#define KILLTRAN_KILL_TRANSACTION_INDEX_L "kill-transaction-index"
#define KILLTRAN_KILL_USER_NAME_S 11701
#define KILLTRAN_KILL_USER_NAME_L "kill-user-name"
#define KILLTRAN_KILL_HOST_NAME_S 11702
#define KILLTRAN_KILL_HOST_NAME_L "kill-host-name"
#define KILLTRAN_KILL_PROGRAM_NAME_S 11703
#define KILLTRAN_KILL_PROGRAM_NAME_L "kill-program-name"
#define KILLTRAN_KILL_SQL_ID_S 11704
#define KILLTRAN_KILL_SQL_ID_L "kill-sql-id"
#define KILLTRAN_DBA_PASSWORD_S 'p'
#define KILLTRAN_DBA_PASSWORD_L "dba-password"
#define KILLTRAN_DISPLAY_INFORMATION_S 'd'
#define KILLTRAN_DISPLAY_INFORMATION_L "display-information"
#define KILLTRAN_DISPLAY_QUERY_INFO_S 'q'
#define KILLTRAN_DISPLAY_QUERY_INFO_L "query-exec-info"
#define KILLTRAN_FORCE_S 'f'
#define KILLTRAN_FORCE_L "force"
#define LOAD_USER_S 'u'
#define LOAD_USER_L "user"
#define LOAD_PASSWORD_S 'p'
#define LOAD_PASSWORD_L "password"
#define LOAD_CHECK_ONLY_S 11803
#define LOAD_CHECK_ONLY_L "data-file-check-only"
#define LOAD_LOAD_ONLY_S 'l'
#define LOAD_LOAD_ONLY_L "load-only"
#define LOAD_ESTIMATED_SIZE_S 11805
#define LOAD_ESTIMATED_SIZE_L "estimated-size"
#define LOAD_VERBOSE_S 'v'
#define LOAD_VERBOSE_L "verbose"
#define LOAD_NO_STATISTICS_S 11807
#define LOAD_NO_STATISTICS_L "no-statistics"
#define LOAD_PERIODIC_COMMIT_S 'c'
#define LOAD_PERIODIC_COMMIT_L "periodic-commit"
#define LOAD_NO_OID_S 11809
#define LOAD_NO_OID_L "no-oid"
#define LOAD_SCHEMA_FILE_S 's'
#define LOAD_SCHEMA_FILE_L "schema-file"
#define LOAD_INDEX_FILE_S 'i'
#define LOAD_INDEX_FILE_L "index-file"
#define LOAD_IGNORE_LOGGING_S 11812
#define LOAD_IGNORE_LOGGING_L "no-logging"
#define LOAD_DATA_FILE_S 'd'
#define LOAD_DATA_FILE_L "data-file"
#define LOAD_TRIGGER_FILE_S 11813
#define LOAD_TRIGGER_FILE_L "trigger-file"
#define LOAD_ERROR_CONTROL_FILE_S 'e'
#define LOAD_ERROR_CONTROL_FILE_L "error-control-file"
#define LOAD_IGNORE_CLASS_S 11816
#define LOAD_IGNORE_CLASS_L "ignore-class-file"
#define LOAD_SA_MODE_S 'S'
#define LOAD_SA_MODE_L "SA-mode"
#define LOAD_CS_MODE_S 'C'
#define LOAD_CS_MODE_L "CS-mode"
#define LOAD_TABLE_NAME_S 't'
#define LOAD_TABLE_NAME_L "table"
#define LOAD_COMPARE_STORAGE_ORDER_S 11820
#define LOAD_COMPARE_STORAGE_ORDER_L "compare-storage-order"
#define LOAD_CS_FORCE_LOAD_S 11824
#define LOAD_CS_FORCE_LOAD_L "force-load"
#define UNLOAD_INPUT_CLASS_FILE_S 'i'
#define UNLOAD_INPUT_CLASS_FILE_L "input-class-file"
#define UNLOAD_INCLUDE_REFERENCE_S 11901
#define UNLOAD_INCLUDE_REFERENCE_L "include-reference"
#define UNLOAD_INPUT_CLASS_ONLY_S 11902
#define UNLOAD_INPUT_CLASS_ONLY_L "input-class-only"
#define UNLOAD_LO_COUNT_S 11903
#define UNLOAD_LO_COUNT_L "lo-count"
#define UNLOAD_ESTIMATED_SIZE_S 11904
#define UNLOAD_ESTIMATED_SIZE_L "estimated-size"
#define UNLOAD_CACHED_PAGES_S 11905
#define UNLOAD_CACHED_PAGES_L "cached-pages"
#define UNLOAD_OUTPUT_PATH_S 'O'
#define UNLOAD_OUTPUT_PATH_L "output-path"
#define UNLOAD_SCHEMA_ONLY_S 's'
#define UNLOAD_SCHEMA_ONLY_L "schema-only"
#define UNLOAD_DATA_ONLY_S 'd'
#define UNLOAD_DATA_ONLY_L "data-only"
#define UNLOAD_OUTPUT_PREFIX_S 11909
#define UNLOAD_OUTPUT_PREFIX_L "output-prefix"
#define UNLOAD_HASH_FILE_S 11910
#define UNLOAD_HASH_FILE_L "hash-file"
#define UNLOAD_VERBOSE_S 'v'
#define UNLOAD_VERBOSE_L "verbose"
#define UNLOAD_USE_DELIMITER_S 11912
#define UNLOAD_USE_DELIMITER_L "use-delimiter"
#define UNLOAD_SA_MODE_S 'S'
#define UNLOAD_SA_MODE_L "SA-mode"
#define UNLOAD_CS_MODE_S 'C'
#define UNLOAD_CS_MODE_L "CS-mode"
#define UNLOAD_DATAFILE_PER_CLASS_S 11915
#define UNLOAD_DATAFILE_PER_CLASS_L "datafile-per-class"
#define UNLOAD_USER_S 'u'
#define UNLOAD_USER_L "user"
#define UNLOAD_PASSWORD_S 'p'
#define UNLOAD_PASSWORD_L "password"
#define UNLOAD_KEEP_STORAGE_ORDER_S 11918
#define UNLOAD_KEEP_STORAGE_ORDER_L "keep-storage-order"
#define COMPACT_VERBOSE_S 'v'
#define COMPACT_VERBOSE_L "verbose"
#define COMPACT_INPUT_CLASS_FILE_S 'i'
#define COMPACT_INPUT_CLASS_FILE_L "input-class-file"
#define COMPACT_CS_MODE_S 'C'
#define COMPACT_CS_MODE_L "CS-mode"
#define COMPACT_SA_MODE_S 'S'
#define COMPACT_SA_MODE_L "SA-mode"
#define COMPACT_PAGES_COMMITED_ONCE_S 'p'
#define COMPACT_PAGES_COMMITED_ONCE_L "pages-commited-once"
#define COMPACT_DELETE_OLD_REPR_S 'd'
#define COMPACT_DELETE_OLD_REPR_L "delete-old-repr"
#define COMPACT_INSTANCE_LOCK_TIMEOUT_S 'I'
#define COMPACT_INSTANCE_LOCK_TIMEOUT_L "Instance-lock-timeout"
#define COMPACT_CLASS_LOCK_TIMEOUT_S 'c'
#define COMPACT_CLASS_LOCK_TIMEOUT_L "class-lock-timeout"
#define COMPACT_STANDBY_CS_MODE_S 12000
#define COMPACT_STANDBY_CS_MODE_L "standby"
#define CSQL_SA_MODE_S 'S'
#define CSQL_SA_MODE_L "SA-mode"
#define CSQL_CS_MODE_S 'C'
#define CSQL_CS_MODE_L "CS-mode"
#define CSQL_USER_S 'u'
#define CSQL_USER_L "user"
#define CSQL_PASSWORD_S 'p'
#define CSQL_PASSWORD_L "password"
#define CSQL_ERROR_CONTINUE_S 'e'
#define CSQL_ERROR_CONTINUE_L "error-continue"
#define CSQL_INPUT_FILE_S 'i'
#define CSQL_INPUT_FILE_L "input-file"
#define CSQL_OUTPUT_FILE_S 'o'
#define CSQL_OUTPUT_FILE_L "output-file"
#define CSQL_SINGLE_LINE_S 's'
#define CSQL_SINGLE_LINE_L "single-line"
#define CSQL_COMMAND_S 'c'
#define CSQL_COMMAND_L "command"
#define CSQL_LINE_OUTPUT_S 'l'
#define CSQL_LINE_OUTPUT_L "line-output"
#define CSQL_READ_ONLY_S 'r'
#define CSQL_READ_ONLY_L "read-only"
#define CSQL_NO_AUTO_COMMIT_S 12010
#define CSQL_NO_AUTO_COMMIT_L "no-auto-commit"
#define CSQL_NO_PAGER_S 12011
#define CSQL_NO_PAGER_L "no-pager"
#define CSQL_SYSADM_S 12012
#define CSQL_SYSADM_L "sysadm"
#define CSQL_NO_SINGLE_LINE_S 12013
#define CSQL_NO_SINGLE_LINE_L "no-single-line"
#define CSQL_STRING_WIDTH_S 12014
#define CSQL_STRING_WIDTH_L "string-width"
#define CSQL_WRITE_ON_STANDBY_S 12015
#define CSQL_WRITE_ON_STANDBY_L "write-on-standby"
#define CSQL_NO_TRIGGER_ACTION_S 12016
#define CSQL_NO_TRIGGER_ACTION_L "no-trigger-action"
#define CSQL_PLAIN_OUTPUT_S 't'
#define CSQL_PLAIN_OUTPUT_L "plain-output"
#define CSQL_SKIP_COL_NAMES_S 'N'
#define CSQL_SKIP_COL_NAMES_L "skip-column-names"
#define CSQL_SKIP_VACUUM_S 12017
#define CSQL_SKIP_VACUUM_L "skip-vacuum"
#define CSQL_QUERY_OUTPUT_S 'q'
#define CSQL_QUERY_OUTPUT_L "query-output"
#define CSQL_QUERY_COLUMN_DELIMITER_S 12018
#define CSQL_QUERY_COLUMN_DELIMITER_L "delimiter"
#define CSQL_QUERY_COLUMN_ENCLOSURE_S 12019
#define CSQL_QUERY_COLUMN_ENCLOSURE_L "enclosure"
#define CSQL_LOADDB_OUTPUT_S 'd'
#define CSQL_LOADDB_OUTPUT_L "loaddb-output"
#define COMMDB_SERVER_LIST_S 'P'
#define COMMDB_SERVER_LIST_L "server-list"
#define COMMDB_ALL_LIST_S 'O'
#define COMMDB_ALL_LIST_L "all-list"
#define COMMDB_SHUTDOWN_SERVER_S 'S'
#define COMMDB_SHUTDOWN_SERVER_L "shutdown-server"
#define COMMDB_SHUTDOWN_ALL_S 'A'
#define COMMDB_SHUTDOWN_ALL_L "shutdown-all"
#define COMMDB_HOST_S 'h'
#define COMMDB_HOST_L "host"
#define COMMDB_SERVER_MODE_S 'c'
#define COMMDB_SERVER_MODE_L "server-mode"
#define COMMDB_HA_NODE_LIST_S 'N'
#define COMMDB_HA_NODE_LIST_L "node-list"
#define COMMDB_HA_PROCESS_LIST_S 'L'
#define COMMDB_HA_PROCESS_LIST_L "process-list"
#define COMMDB_HA_PING_HOST_LIST_S 'p'
#define COMMDB_HA_PING_HOST_LIST_L "ping-host"
#define COMMDB_DEREG_HA_BY_PID_S 'D'
#define COMMDB_DEREG_HA_BY_PID_L "dereg-process"
#define COMMDB_DEREG_HA_BY_ARGS_S 'R'
#define COMMDB_DEREG_HA_BY_ARGS_L "dereg-args"
#define COMMDB_KILL_ALL_HA_PROCESS_S 'd'
#define COMMDB_KILL_ALL_HA_PROCESS_L "kill-all-ha-process"
#define COMMDB_IS_REGISTERED_PROC_S 'C'
#define COMMDB_IS_REGISTERED_PROC_L "is-registered-proc"
#define COMMDB_RECONFIG_HEARTBEAT_S 'F'
#define COMMDB_RECONFIG_HEARTBEAT_L "reconfig-node-list"
#define COMMDB_DEACTIVATE_HEARTBEAT_S 12110
#define COMMDB_DEACTIVATE_HEARTBEAT_L "deactivate-heartbeat"
#define COMMDB_DEACT_STOP_ALL_S 12111
#define COMMDB_DEACT_STOP_ALL_L "deact-stop-all"
#define COMMDB_DEACT_CONFIRM_STOP_ALL_S 12112
#define COMMDB_DEACT_CONFIRM_STOP_ALL_L "deact-confirm-stop-all"
#define COMMDB_DEACT_CONFIRM_NO_SERVER_S 12113
#define COMMDB_DEACT_CONFIRM_NO_SERVER_L "deact-confirm-no-server"
#define COMMDB_ACTIVATE_HEARTBEAT_S 12114
#define COMMDB_ACTIVATE_HEARTBEAT_L "activate-heartbeat"
#define COMMDB_VERBOSE_OUTPUT_S 'V'
#define COMMDB_VERBOSE_OUTPUT_L "verbose"
#define COMMDB_HB_DEACT_IMMEDIATELY_S 'i'
#define COMMDB_HB_DEACT_IMMEDIATELY_L "immediately"
#define COMMDB_HA_ADMIN_INFO_S 12115
#define COMMDB_HA_ADMIN_INFO_L "admin-info"
#define COMMDB_HA_START_UTIL_PROCESS_S 't'
#define COMMDB_HA_START_UTIL_PROCESS_L "start-ha-util-process"
#define PARAMDUMP_OUTPUT_FILE_S 'o'
#define PARAMDUMP_OUTPUT_FILE_L "output-file"
#define PARAMDUMP_BOTH_S 'b'
#define PARAMDUMP_BOTH_L "both"
#define PARAMDUMP_SA_MODE_S 'S'
#define PARAMDUMP_SA_MODE_L "SA-mode"
#define PARAMDUMP_CS_MODE_S 'C'
#define PARAMDUMP_CS_MODE_L "CS-mode"
#define STATDUMP_OUTPUT_FILE_S 'o'
#define STATDUMP_OUTPUT_FILE_L "output-file"
#define STATDUMP_INTERVAL_S 'i'
#define STATDUMP_INTERVAL_L "interval"
#define STATDUMP_CUMULATIVE_S 'c'
#define STATDUMP_CUMULATIVE_L "cumulative"
#define STATDUMP_SUBSTR_S 's'
#define STATDUMP_SUBSTR_L "substr"
#define ACLDB_RELOAD_S 'r'
#define ACLDB_RELOAD_L "reload"
#define CHANGEMODE_MODE_S 'm'
#define CHANGEMODE_MODE_L "mode"
#define CHANGEMODE_FORCE_S 'f'
#define CHANGEMODE_FORCE_L "force"
#define CHANGEMODE_TIMEOUT_S 't'
#define CHANGEMODE_TIMEOUT_L "timeout"
#define COPYLOG_LOG_PATH_S 'L'
#define COPYLOG_LOG_PATH_L "log-path"
#define COPYLOG_MODE_S 'm'
#define COPYLOG_MODE_L "mode"
#define COPYLOG_START_PAGEID_S 'S'
#define COPYLOG_START_PAGEID_L "start-page-id"
#define APPLYLOG_LOG_PATH_S 'L'
#define APPLYLOG_LOG_PATH_L "log-path"
#define APPLYLOG_MAX_MEM_SIZE_S 12401
#define APPLYLOG_MAX_MEM_SIZE_L "max-mem-size"
#define APPLYINFO_COPIED_LOG_PATH_S 'L'
#define APPLYINFO_COPIED_LOG_PATH_L "copied-log-path"
#define APPLYINFO_PAGE_S 'p'
#define APPLYINFO_PAGE_L "page"
#define APPLYINFO_REMOTE_NAME_S 'r'
#define APPLYINFO_REMOTE_NAME_L "remote-host-name"
#define APPLYINFO_APPLIED_INFO_S 'a'
#define APPLYINFO_APPLIED_INFO_L "applied-info"
#define APPLYINFO_VERBOSE_S 'v'
#define APPLYINFO_VERBOSE_L "verbose"
#define APPLYINFO_INTERVAL_S 'i'
#define APPLYINFO_INTERVAL_L "interval"
#define GENLOCALE_INPUT_PATH_S 'i'
#define GENLOCALE_INPUT_PATH_L "input-ldml-file"
#define GENLOCALE_VERBOSE_S 'v'
#define GENLOCALE_VERBOSE_L "verbose"
#define DUMPLOCALE_INPUT_PATH_S 'i'
#define DUMPLOCALE_INPUT_PATH_L "input-file"
#define DUMPLOCALE_CALENDAR_S 'd'
#define DUMPLOCALE_CALENDAR_L "calendar"
#define DUMPLOCALE_NUMBERING_S 'n'
#define DUMPLOCALE_NUMBERING_L "numbering"
#define DUMPLOCALE_ALPHABET_S 'a'
#define DUMPLOCALE_ALPHABET_L "alphabet"
#define DUMPLOCALE_ALPHABET_LOWER_S "l"
#define DUMPLOCALE_ALPHABET_LOWER_L "lower"
#define DUMPLOCALE_ALPHABET_UPPER_S "u"
#define DUMPLOCALE_ALPHABET_UPPER_L "upper"
#define DUMPLOCALE_ALPHABET_ALL_CASING "both"
#define DUMPLOCALE_IDENTIFIER_ALPHABET_S 13000
#define DUMPLOCALE_IDENTIFIER_ALPHABET_L "identifier-alphabet"
#define DUMPLOCALE_COLLATION_S 'c'
#define DUMPLOCALE_COLLATION_L "codepoint-order"
#define DUMPLOCALE_WEIGHT_ORDER_S 'w'
#define DUMPLOCALE_WEIGHT_ORDER_L "weight-order"
#define DUMPLOCALE_START_VALUE_S 's'
#define DUMPLOCALE_START_VALUE_L "start-value"
#define DUMPLOCALE_END_VALUE_S 'e'
#define DUMPLOCALE_END_VALUE_L "end-value"
#define DUMPLOCALE_NORMALIZATION_S 'z'
#define DUMPLOCALE_NORMALIZATION_L "normalization"
#define DUMPLOCALE_CONSOLE_CONV_S 'k'
#define DUMPLOCALE_CONSOLE_CONV_L "console-conversion"
#define SYNCCOLL_CHECK_S 'c'
#define SYNCCOLL_CHECK_L "check-only"
#define SYNCCOLL_FORCESYNC_S 'f'
#define SYNCCOLL_FORCESYNC_L "force-only"
#define GEN_TZ_INPUT_FOLDER_S 'i'
#define GEN_TZ_INPUT_FOLDER_L "input-folder"
#define GEN_TZ_MODE_S 'g'
#define GEN_TZ_MODE_L "gen-mode"
#define DUMP_TZ_COUNTRIES_S 'c'
#define DUMP_TZ_COUNTRIES_L "list-countries"
#define DUMP_TZ_ZONES_S 'z'
#define DUMP_TZ_ZONES_L "list-zones"
#define DUMP_TZ_ZONE_ID_S 'd'
#define DUMP_TZ_ZONE_ID_L "zone-id"
#define DUMP_TZ_LEAP_SEC_S 'l'
#define DUMP_TZ_LEAP_SEC_L "leap-seconds"
#define DUMP_TZ_DUMP_SUM_S 's'
#define DUMP_TZ_DUMP_SUM_L "summary"
#define VERSION_S 20000
#define VERSION_L "version"
#define RESTORESLAVE_SOURCE_STATE_S 's'
#define RESTORESLAVE_SOURCE_STATE_L "source-state"
#define RESTORESLAVE_MASTER_HOST_NAME_S 'm'
#define RESTORESLAVE_MASTER_HOST_NAME_L "master-host-name"
#define RESTORESLAVE_LIST_S 10601
#define RESTORESLAVE_LIST_L "list"
#define RESTORESLAVE_BACKUP_FILE_PATH_S 'B'
#define RESTORESLAVE_BACKUP_FILE_PATH_L "backup-file-path"
#define RESTORESLAVE_OUTPUT_FILE_S 'o'
#define RESTORESLAVE_OUTPUT_FILE_L "output-file"
#define RESTORESLAVE_USE_DATABASE_LOCATION_PATH_S 'u'
#define RESTORESLAVE_USE_DATABASE_LOCATION_PATH_L "use-database-location-path"
#define RESTORESLAVE_KEYS_FILE_PATH_S 'k'
#define RESTORESLAVE_KEYS_FILE_PATH_L "keys-file-path"
#define VACUUM_SA_MODE_S 'S'
#define VACUUM_SA_MODE_L "SA-mode"
#define VACUUM_CS_MODE_S 'C'
#define VACUUM_CS_MODE_L "CS-mode"
#define VACUUM_DUMP_S 10700
#define VACUUM_DUMP_L "dump"
#define VACUUM_OUTPUT_FILE_S 'o'
#define VACUUM_OUTPUT_FILE_L "output-file"
#define CHECKSUM_CHUNK_SIZE_S 'c'
#define CHECKSUM_CHUNK_SIZE_L "chunk-size"
#define CHECKSUM_RESUME_S 14000
#define CHECKSUM_RESUME_L "resume"
#define CHECKSUM_SLEEP_S 's'
#define CHECKSUM_SLEEP_L "sleep"
#define CHECKSUM_CONT_ON_ERROR_S 14001
#define CHECKSUM_CONT_ON_ERROR_L "cont-on-error"
#define CHECKSUM_INCLUDE_CLASS_FILE_S 'i'
#define CHECKSUM_INCLUDE_CLASS_FILE_L "include-class-file"
#define CHECKSUM_EXCLUDE_CLASS_FILE_S 'e'
#define CHECKSUM_EXCLUDE_CLASS_FILE_L "exclude-class-file"
#define CHECKSUM_TIMEOUT_S 't'
#define CHECKSUM_TIMEOUT_L "timeout"
#define CHECKSUM_TABLE_NAME_S 'n'
#define CHECKSUM_TABLE_NAME_L "table-name"
#define CHECKSUM_REPORT_ONLY_S 'r'
#define CHECKSUM_REPORT_ONLY_L "report-only"
#define CHECKSUM_SCHEMA_ONLY_S 14002
#define CHECKSUM_SCHEMA_ONLY_L "schema-only"
#define TDE_GENERATE_KEY_S 'n'
#define TDE_GENERATE_KEY_L "generate-new-key"
#define TDE_SHOW_KEYS_S 's'
#define TDE_SHOW_KEYS_L "show-keys"
#define TDE_PRINT_KEY_VALUE_S 14000
#define TDE_PRINT_KEY_VALUE_L "print-value"
#define TDE_SA_MODE_S 'S'
#define TDE_SA_MODE_L "SA-mode"
#define TDE_CS_MODE_S HIDDEN_CS_MODE_S
#define TDE_CS_MODE_L "CS-mode"
#define TDE_CHANGE_KEY_S 'c'
#define TDE_CHANGE_KEY_L "change-key"
#define TDE_DELETE_KEY_S 'd'
#define TDE_DELETE_KEY_L "delete-key"
#define TDE_DBA_PASSWORD_S 'p'
#define TDE_DBA_PASSWORD_L "dba-password"
#define LIB_UTIL_CS_NAME "libcubridcs.so"
#define LIB_UTIL_SA_NAME "libcubridsa.so"
#define UTILITY_GENERIC_MSG_FUNC_NAME "utility_get_generic_message"
#define UTILITY_INIT_FUNC_NAME "utility_initialize"
#define UTILITY_ADMIN_USAGE_FUNC_NAME "util_admin_usage"
#define UTILITY_ADMIN_VERSION_FUNC_NAME "util_admin_version"
Typedefs
typedef void * DSO_HANDLE
typedef struct _node_config HA_NODE_CONF
typedef struct _ha_config HA_CONF
typedef int(* UTILITY_INIT_FUNC) (void)
typedef int(* UTILITY_FUNCTION) (UTIL_FUNCTION_ARG *)
Enumerations
enum MSGCAT_UTIL_SET {
MSGCAT_UTIL_SET_GENERIC = 1, MSGCAT_UTIL_SET_BACKUPDB = 2, MSGCAT_UTIL_SET_COPYDB = 3, MSGCAT_UTIL_SET_CREATEDB = 4,
MSGCAT_UTIL_SET_DELETEDB = 6, MSGCAT_UTIL_SET_RENAMEDB = 7, MSGCAT_UTIL_SET_MASTER = 9, MSGCAT_UTIL_SET_OPTIMIZEDB = 10,
MSGCAT_UTIL_SET_RESTOREDB = 11, MSGCAT_UTIL_SET_LOADDB = 12, MSGCAT_UTIL_SET_UNLOADDB = 13, MSGCAT_UTIL_SET_COMPACTDB = 14,
MSGCAT_UTIL_SET_COMMDB = 15, MSGCAT_UTIL_SET_PATCHDB = 16, MSGCAT_UTIL_SET_ADDVOLDB = 17, MSGCAT_UTIL_SET_CHECKDB = 18,
MSGCAT_UTIL_SET_SPACEDB = 19, MSGCAT_UTIL_SET_ESTIMATEDB_DATA = 20, MSGCAT_UTIL_SET_ESTIMATEDB_INDEX = 21, MSGCAT_UTIL_SET_INSTALLDB = 22,
MSGCAT_UTIL_SET_MIGDB = 23, MSGCAT_UTIL_SET_DIAGDB = 24, MSGCAT_UTIL_SET_LOCKDB = 25, MSGCAT_UTIL_SET_KILLTRAN = 26,
MSGCAT_UTIL_SET_ALTERDBHOST = 33, MSGCAT_UTIL_SET_LOADJAVA = 34, MSGCAT_UTIL_SET_PLANDUMP = 37, MSGCAT_UTIL_SET_PARAMDUMP = 38,
MSGCAT_UTIL_SET_CHANGEMODE = 39, MSGCAT_UTIL_SET_COPYLOGDB = 40, MSGCAT_UTIL_SET_APPLYLOGDB = 41, MSGCAT_UTIL_SET_LOGFILEDUMP = 42,
MSGCAT_UTIL_SET_STATDUMP = 43, MSGCAT_UTIL_SET_APPLYINFO = 44, MSGCAT_UTIL_SET_ACLDB = 45, MSGCAT_UTIL_SET_GENLOCALE = 46,
MSGCAT_UTIL_SET_DUMPLOCALE = 47, MSGCAT_UTIL_SET_SYNCCOLLDB = 48, MSGCAT_UTIL_SET_TRANLIST = 49, MSGCAT_UTIL_SET_GEN_TZ = 51,
MSGCAT_UTIL_SET_DUMP_TZ = 52, MSGCAT_UTIL_SET_RESTORESLAVE = 53, MSGCAT_UTIL_SET_DELVOLDB = 54, MSGCAT_UTIL_SET_VACUUMDB = 55,
MSGCAT_UTIL_SET_CHECKSUMDB = 56, MSGCAT_UTIL_SET_TDE = 57
}
enum MSGCAT_UTIL_GENERIC_MSG {
MSGCAT_UTIL_GENERIC_BAD_DATABASE_NAME = 1, MSGCAT_UTIL_GENERIC_BAD_OUTPUT_FILE = 2, MSGCAT_UTIL_GENERIC_BAD_VOLUME_NAME = 6, MSGCAT_UTIL_GENERIC_VERSION = 9,
MSGCAT_UTIL_GENERIC_ADMIN_USAGE = 10, MSGCAT_UTIL_GENERIC_SERVICE_INVALID_NAME = 12, MSGCAT_UTIL_GENERIC_SERVICE_INVALID_CMD = 13, MSGCAT_UTIL_GENERIC_SERVICE_PROPERTY_FAIL = 14,
MSGCAT_UTIL_GENERIC_START_STOP_3S = 15, MSGCAT_UTIL_GENERIC_START_STOP_2S = 16, MSGCAT_UTIL_GENERIC_NOT_RUNNING_2S = 17, MSGCAT_UTIL_GENERIC_NOT_RUNNING_1S = 18,
MSGCAT_UTIL_GENERIC_ALREADY_RUNNING_2S = 19, MSGCAT_UTIL_GENERIC_ALREADY_RUNNING_1S = 20, MSGCAT_UTIL_GENERIC_RESULT = 21, MSGCAT_UTIL_GENERIC_MISS_ARGUMENT = 22,
MSGCAT_UTIL_GENERIC_CUBRID_USAGE = 23, MSGCAT_UTIL_GENERIC_ARGS_OVER = 31, MSGCAT_UTIL_GENERIC_MISS_DBNAME = 32, MSGCAT_UTIL_GENERIC_DEPRECATED = 33,
MSGCAT_UTIL_GENERIC_INVALID_PARAMETER = 34, MSGCAT_UTIL_GENERIC_NO_MEM = 35, MSGCAT_UTIL_GENERIC_NOT_HA_MODE = 36, MSGCAT_UTIL_GENERIC_HA_MODE = 37,
MSGCAT_UTIL_GENERIC_HA_MODE_NOT_LISTED_HA_DB = 38, MSGCAT_UTIL_GENERIC_HA_MODE_NOT_LISTED_HA_NODE = 39, MSGCAT_UTIL_GENERIC_INVALID_CMD = 40, MSGCAT_UTIL_GENERIC_MANAGER_NOT_INSTALLED = 41,
MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT = 42, MSGCAT_UTIL_GENERIC_FILEOPEN_ERROR = 43
}
enum MSGCAT_DELETEDB_MSG { DELETEDB_MSG_USAGE = 60 }
enum MSGCAT_BACKUPDB_MSG {
BACKUPDB_INVALID_THREAD_NUM_OPT = 30, BACKUPDB_INVALID_PATH = 31, BACKUPDB_USING_SEPARATE_KEYS = 32, BACKUPDB_NOT_USING_SEPARATE_KEYS = 33,
BACKUPDB_FIFO_KEYS_NOT_SUPPORTED = 34, BACKUPDB_MSG_USAGE = 60
}
enum MSGCAT_RENAMEDB_MSG { RENAMEDB_VOLEXT_PATH_INVALID = 31, RENAMEDB_VOLS_TOFROM_PATHS_FILE_INVALID = 32, RENAMEDB_MSG_USAGE = 60 }
enum MSGCAT_OPTIMIZEDB_MSG { OPTIMIZEDB_MSG_USAGE = 60 }
enum MSGCAT_COMMDB_MSG {
COMMDB_STRING1 = 21, COMMDB_STRING2 = 22, COMMDB_STRING3 = 23, COMMDB_STRING4 = 24,
COMMDB_STRING5 = 25, COMMDB_STRING6 = 26, COMMDB_STRING7 = 27, COMMDB_STRING8 = 28,
COMMDB_STRING9 = 29, COMMDB_STRING10 = 30, COMMDB_STRING11 = 31, COMMDB_STRING12 = 32,
COMMDB_STRING13 = 33, COMMDB_STRING14 = 34, COMMDB_INVALID_IMMEDIATELY_OPTION = 39
}
enum MSGCAT_COPYDB_MSG { COPYDB_MSG_IDENTICAL = 30, COPYDB_VOLEXT_PATH_INVALID = 31, COPYDB_VOLS_TOFROM_PATHS_FILE_INVALID = 32, COPYDB_MSG_USAGE = 60 }
enum MSGCAT_CREATEDB_MSG {
CREATEDB_MSG_MISSING_USER = 41, CREATEDB_MSG_UNKNOWN_CMD = 42, CREATEDB_MSG_BAD_OUTPUT = 43, CREATEDB_MSG_CREATING = 45,
CREATEDB_MSG_FAILURE = 46, CREATEDB_MSG_BAD_USERFILE = 47, CREATEDB_MSG_BAD_RANGE = 48, CREATEDB_MSG_INVALID_SIZE = 49,
CREATEDB_MSG_USAGE = 60
}
enum MSGCAT_MASTER_MSG {
MASTER_MSG_DUPLICATE = 11, MASTER_MSG_STARTING = 12, MASTER_MSG_EXITING = 13, MASTER_MSG_NO_PARAMETERS = 15,
MASTER_MSG_PROCESS_ERROR = 16, MASTER_MSG_SERVER_STATUS = 17, MASTER_MSG_SERVER_NOTIFIED = 18, MASTER_MSG_SERVER_NOT_FOUND = 19,
MASTER_MSG_GOING_DOWN = 20, MASTER_MSG_FAILOVER_FINISHED = 21
}
enum MSGCAT_RESTOREDB_MSG { RESTOREDB_MSG_BAD_DATE = 19, RESTOREDB_MSG_FAILURE = 20, RESTOREDB_MSG_USAGE = 60 }
enum MSGCAT_ADDVOLDB_MSG { ADDVOLDB_MSG_BAD_NPAGES = 20, ADDVOLDB_MSG_BAD_PURPOSE = 21, ADDVOLDB_INVALID_MAX_WRITESIZE_IN_SEC = 22, ADDVOLDB_MSG_USAGE = 60 }
enum MSGCAT_CHECKDB_MSG { CHECKDB_MSG_INCONSISTENT = 20, CHECKDB_MSG_NO_SUCH_CLASS = 21, CHECKDB_MSG_NO_SUCH_INDEX = 22, CHECKDB_MSG_USAGE = 60 }
enum MSGCAT_SPACEDB_MSG {
SPACEDB_OUTPUT_TITLE = 10, SPACEDB_MSG_BAD_OUTPUT = 11, SPACEDB_OUTPUT_TITLE_LOB = 12, SPACEDB_MSG_ALL_HEADER_PAGES = 20,
SPACEDB_MSG_ALL_HEADER_SIZE = 21, SPACEDB_MSG_PERM_PERM_FORMAT = 22, SPACEDB_MSG_PERM_TEMP_FORMAT = 23, SPACEDB_MSG_TEMP_TEMP_FORMAT = 24,
SPACEDB_MSG_TOTAL_FORMAT = 25, SPACEDB_MSG_VOLS_TITLE = 30, SPACEDB_MSG_VOLS_HEADER_PAGES = 31, SPACEDB_MSG_VOLS_HEADER_SIZE = 32,
SPACEDB_MSG_VOLS_PERM_PERM_FORMAT = 33, SPACEDB_MSG_VOLS_PERM_TEMP_FORMAT = 34, SPACEDB_MSG_VOLS_TEMP_TEMP_FORMAT = 35, SPACEDB_MSG_FILES_TITLE = 40,
SPACEDB_MSG_FILES_HEADER_PAGES = 41, SPACEDB_MSG_FILES_HEADER_SIZE = 42, SPACEDB_MSG_FILES_FORMAT = 43, SPACEDB_MSG_END_UNDERLINE = 50,
SPACEDB_MSG_USAGE = 60
}
enum MSGCAT_ESTIMATEDB_DATA_MSG { ESTIMATEDB_DATA_MSG_NPAGES = 15, ESTIMATEDB_DATA_MSG_USAGE = 60 }
enum MSGCAT_ESTIMATEDB_INDEX_MSG {
ESTIMATEDB_INDEX_BAD_KEYTYPE = 15, ESTIMATEDB_INDEX_BAD_KEYLENGTH = 16, ESTIMATEDB_INDEX_BAD_ARGUMENTS = 17, ESTIMATEDB_INDEX_MSG_NPAGES = 20,
ESTIMATEDB_INDEX_MSG_BLT_NPAGES = 21, ESTIMATEDB_INDEX_MSG_BLT_WRS_NPAGES = 22, ESTIMATEDB_INDEX_MSG_INPUT = 23, ESTIMATEDB_INDEX_MSG_INSTANCES = 24,
ESTIMATEDB_INDEX_MSG_NUMBER_KEYS = 25, ESTIMATEDB_INDEX_MSG_AVG_KEYSIZE = 26, ESTIMATEDB_INDEX_MSG_KEYTYPE = 27, ESTIMATEDB_INDEX_MSG_USAGE = 60
}
enum MSGCAT_DIAGDB_MSG { DIAGDB_MSG_BAD_OUTPUT = 15, DIAGDB_MSG_USAGE = 60 }
enum MSGCAT_ALTERDBHOST_MSG { ALTERDBHOST_MSG_USAGE = 60 }
enum MSGCAT_PATCHDB_MSG { PATCHDB_MSG_USAGE = 60 }
enum MSGCAT_INSTALLDB_MSG { INSTALLDB_MSG_USAGE = 60 }
enum MSGCAT_LOCKDB_MSG { LOCKDB_MSG_BAD_OUTPUT = 15, LOCKDB_MSG_NOT_IN_STANDALONE = 59, LOCKDB_MSG_USAGE = 60 }
enum MSGCAT_TRANLIST_MSG {
TRANLIST_MSG_USER_PASSWORD = 20, TRANLIST_MSG_SUMMARY_HEADER = 22, TRANLIST_MSG_SUMMARY_UNDERSCORE = 23, TRANLIST_MSG_SUMMARY_ENTRY = 24,
TRANLIST_MSG_NONE_TABLE_ENTRIES = 25, TRANLIST_MSG_NOT_DBA_USER = 26, TRANLIST_MSG_INVALID_SORT_KEY = 27, TRANLIST_MSG_QUERY_INFO_HEADER = 32,
TRANLIST_MSG_QUERY_INFO_ENTRY = 33, TRANLIST_MSG_QUERY_INFO_UNDERSCORE = 34, TRANLIST_MSG_FULL_INFO_HEADER = 42, TRANLIST_MSG_FULL_INFO_ENTRY = 43,
TRANLIST_MSG_FULL_INFO_UNDERSCORE = 44, TRANLIST_MSG_TRAN_INDEX = 45, TRANLIST_MSG_SQL_ID = 46, TRANLIST_MSG_NOT_IN_STANDALONE = 59,
TRANLIST_MSG_USAGE = 60
}
enum MSGCAT_KILLTRAN_MSG {
KILLTRAN_MSG_MANY_ARGS = 20, KILLTRAN_MSG_DBA_PASSWORD = 21, KILLTRAN_MSG_NO_MATCHES = 26, KILLTRAN_MSG_READY_TO_KILL = 27,
KILLTRAN_MSG_VERIFY = 28, KILLTRAN_MSG_KILLING = 29, KILLTRAN_MSG_KILL_FAILED = 30, KILLTRAN_MSG_KILL_TIMEOUT = 31,
KILLTRAN_MSG_INVALID_TRANINDEX = 32, KILLTRAN_MSG_NOT_IN_STANDALONE = 59, KILLTRAN_MSG_USAGE = 60
}
enum MSGCAT_PLANDUMP_MSG { PLANDUMP_MSG_BAD_OUTPUT = 15, PLANDUMP_MSG_NOT_IN_STANDALONE = 59, PLANDUMP_MSG_USAGE = 60 }
enum MSGCAT_LOADJAVA_MSG { LOADJAVA_ARG_FORCE_OVERWRITE = 5, LOADJAVA_ARG_FORCE_OVERWRITE_HELP = 6 }
enum MSGCAT_COMPACTDB_MSG {
COMPACTDB_MSG_PASS1 = 11, COMPACTDB_MSG_PROCESSED = 12, COMPACTDB_MSG_PASS2 = 13, COMPACTDB_MSG_CLASS = 14,
COMPACTDB_MSG_OID = 15, COMPACTDB_MSG_INSTANCES = 16, COMPACTDB_MSG_UPDATING = 17, COMPACTDB_MSG_REFOID = 18,
COMPACTDB_MSG_CANT_TRANSFORM = 19, COMPACTDB_MSG_NO_HEAP = 20, COMPACTDB_MSG_CANT_UPDATE = 21, COMPACTDB_MSG_FAILED = 22,
COMPACTDB_MSG_ALREADY_STARTED = 23, COMPACTDB_MSG_OUT_OF_RANGE_PAGES = 24, COMPACTDB_MSG_OUT_OF_RANGE_INSTANCE_LOCK_TIMEOUT = 25, COMPACTDB_MSG_TOTAL_OBJECTS = 26,
COMPACTDB_MSG_FAILED_OBJECTS = 27, COMPACTDB_MSG_MODIFIED_OBJECTS = 28, COMPACTDB_MSG_BIG_OBJECTS = 29, COMPACTDB_MSG_REPR_DELETED = 30,
COMPACTDB_MSG_REPR_CANT_DELETE = 31, COMPACTDB_MSG_ISOLATION_LEVEL_FAILURE = 32, COMPACTDB_MSG_FAILURE = 33, COMPACTDB_MSG_OUT_OF_RANGE_CLASS_LOCK_TIMEOUT = 34,
COMPACTDB_MSG_LOCKED_CLASS = 35, COMPACTDB_MSG_INVALID_CLASS = 36, COMPACTDB_MSG_PROCESS_CLASS_ERROR = 37, COMPACTDB_MSG_NOTHING_TO_PROCESS = 38,
COMPACTDB_MSG_INVALID_PARAMETERS = 39, COMPACTDB_MSG_UNKNOWN_CLASS_NAME = 40, COMPACTDB_MSG_RECLAIMED = 41, COMPACTDB_MSG_RECLAIM_SKIPPED = 42,
COMPACTDB_MSG_RECLAIM_ERROR = 43, COMPACTDB_MSG_PASS3 = 44, COMPACTDB_MSG_HEAP_COMPACT_FAILED = 45, COMPACTDB_MSG_HEAP_COMPACT_SUCCEEDED = 46
}
enum MSGCAT_UNLOADDB_MSG {
UNLOADDB_MSG_INVALID_CACHED_PAGES = 41, UNLOADDB_MSG_INVALID_CACHED_PAGE_SIZE = 42, UNLOADDB_MSG_OBJECTS_DUMPED = 43, UNLOADDB_MSG_OBJECTS_FAILED = 46,
UNLOADDB_MSG_INVALID_DIR_NAME = 47, UNLOADDB_MSG_LOG_LSA = 48, UNLOADDB_MSG_PASSWORD_PROMPT = 49
}
enum MSGCAT_LOADDB_MSG {
LOADDB_MSG_MISSING_DBNAME = 19, LOADDB_MSG_UNREACHABLE_LINE = 20, LOADDB_MSG_SIG1 = 21, LOADDB_MSG_INTERRUPTED_COMMIT = 22,
LOADDB_MSG_INTERRUPTED_ABORT = 23, LOADDB_MSG_BAD_INFILE = 24, LOADDB_MSG_CHECKING = 25, LOADDB_MSG_ERROR_COUNT = 26,
LOADDB_MSG_INSERTING = 27, LOADDB_MSG_OBJECT_COUNT = 28, LOADDB_MSG_DEFAULT_COUNT = 29, LOADDB_MSG_COMMITTING = 30,
LOADDB_MSG_CLOSING = 31, LOADDB_MSG_LINE = 32, LOADDB_MSG_PARSE_ERROR = 33, LOADDB_MSG_MISSING_DOMAIN = 34,
LOADDB_MSG_SET_DOMAIN_ERROR = 35, LOADDB_MSG_UNEXPECTED_SET = 36, LOADDB_MSG_UNEXPECTED_TYPE = 37, LOADDB_MSG_UNKNOWN_ATT_CLASS = 38,
LOADDB_MSG_UNKNOWN_CLASS = 39, LOADDB_MSG_UNKNOWN_CLASS_ID = 40, LOADDB_MSG_UNAUTHORIZED_CLASS = 41, LOADDB_MSG_STOPPED = 42,
LOADDB_MSG_UPDATE_WARNING = 43, LOADDB_MSG_REDEFINING_INSTANCE = 44, LOADDB_MSG_INSTANCE_DEFINED = 45, LOADDB_MSG_INSTANCE_RESERVED = 46,
LOADDB_MSG_UNIQUE_VIOLATION_NULL = 47, LOADDB_MSG_INSTANCE_COUNT = 48, LOADDB_MSG_CLASS_TITLE = 49, LOADDB_MSG_PASSWORD_PROMPT = 50,
LOADDB_MSG_UPDATING_STATISTICS = 51, LOADDB_MSG_STD_ERR = 52, LOADDB_MSG_LEX_ERROR = 53, LOADDB_MSG_SYNTAX_ERR = 54,
LOADDB_MSG_SYNTAX_MISSING = 55, LOADDB_MSG_SYNTAX_IN = 56, LOADDB_MSG_INCOMPATIBLE_ARGS = 57, LOADDB_MSG_COMMITTED_INSTANCES = 58,
LOADDB_MSG_NOPT_ERR = 59, LOADDB_MSG_CONVERSION_ERROR = 60, LOADDB_MSG_OID_NOT_SUPPORTED = 61, LOADDB_MSG_UPDATED_CLASS_STATS = 62,
LOADDB_MSG_INSTANCE_COUNT_EX = 112, LOADDB_MSG_LAST_COMMITTED_LINE = 113, LOADDB_MSG_INSERT_AND_FAIL_COUNT = 116, LOADDB_MSG_LOAD_FAIL = 117,
LOADDB_MSG_EXCEED_MAX_LEN = 118, LOADDB_MSG_OBJECTS_SYNTAX_CHECKED = 119, LOADDB_MSG_TABLE_IS_MISSING = 120, LOADDB_MSG_IGNORED_CLASS = 121,
LOADDB_MSG_USAGE = 122
}
enum MSGCAT_MIGDB_MSG {
MIGDB_MSG_TEMPORARY_CLASS_OID = 1, MIGDB_MSG_CANT_PRINT_ELO = 2, MIGDB_MSG_CANT_ACCESS_LO = 3, MIGDB_MSG_CANT_OPEN_LO_FILE = 4,
MIGDB_MSG_READ_ERROR = 5, MIGDB_MSG_WRITE_ERROR = 6, MIGDB_MSG_CANT_OPEN_ELO = 7, MIGDB_MSG_FH_HASH_FILENAME = 9,
MIGDB_MSG_FH_NAME = 10, MIGDB_MSG_FH_SIZE = 11, MIGDB_MSG_FH_PAGE_SIZE = 12, MIGDB_MSG_FH_DATA_SIZE = 13,
MIGDB_MSG_FH_ENTRY_SIZE = 14, MIGDB_MSG_FH_ENTRIES_PER_PAGE = 15, MIGDB_MSG_FH_CACHED_PAGES = 16, MIGDB_MSG_FH_NUM_ENTRIES = 17,
MIGDB_MSG_FH_NUM_COLLISIONS = 18, MIGDB_MSG_FH_HASH_FILENAME2 = 19, MIGDB_MSG_FH_NEXT_OVERFLOW_ENTRY = 20, MIGDB_MSG_FH_KEY_TYPE = 21,
MIGDB_MSG_FH_PAGE_HEADERS = 22, MIGDB_MSG_FH_LAST_PAGE_HEADER = 23, MIGDB_MSG_FH_FREE_PAGE_HEADER = 24, MIGDB_MSG_FH_PAGE_BITMAP = 25,
MIGDB_MSG_FH_PAGE_BITMAP_SIZE = 26
}
enum MSGCAT_PARAMDUMP_MSG {
PARAMDUMP_MSG_BAD_OUTPUT = 11, PARAMDUMP_MSG_CLIENT_PARAMETER = 21, PARAMDUMP_MSG_SERVER_PARAMETER = 22, PARAMDUMP_MSG_STANDALONE_PARAMETER = 23,
PARAMDUMP_MSG_USAGE = 60
}
enum MSGCAT_CHANGEMODE_MSG {
CHANGEMODE_MSG_BAD_MODE = 11, CHANGEMODE_MSG_CANNOT_CHANGE = 12, CHANGEMODE_MSG_DBA_PASSWORD = 21, CHANGEMODE_MSG_SERVER_MODE = 22,
CHANGEMODE_MSG_SERVER_MODE_CHANGED = 23, CHANGEMODE_MSG_NOT_HA_MODE = 24, CHANGEMODE_MSG_HA_NOT_SUPPORT = 58, CHANGEMODE_MSG_NOT_IN_STANDALONE = 59,
CHANGEMODE_MSG_USAGE = 60
}
enum MSGCAT_COPYLOGDB_MSG {
COPYLOGDB_MSG_BAD_MODE = 11, COPYLOGDB_MSG_DBA_PASSWORD = 21, COPYLOGDB_MSG_NOT_HA_MODE = 22, COPYLOGDB_MSG_HA_NOT_SUPPORT = 58,
COPYLOGDB_MSG_NOT_IN_STANDALONE = 59, COPYLOGDB_MSG_USAGE = 60
}
enum MSGCAT_APPLYLOGDB_MSG {
APPLYLOGDB_MSG_DBA_PASSWORD = 21, APPLYLOGDB_MSG_NOT_HA_MODE = 22, APPLYLOGDB_MSG_HA_NOT_SUPPORT = 58, APPLYLOGDB_MSG_NOT_IN_STANDALONE = 59,
APPLYLOGDB_MSG_USAGE = 60
}
enum MSGCAT_STATDUMP_MSG { STATDUMP_MSG_BAD_OUTPUT = 11, STATDUMP_MSG_NOT_IN_STANDALONE = 59, STATDUMP_MSG_USAGE = 60 }
enum MSGCAT_APPLYINFO_MSG {
APPLYINFO_MSG_DBA_PASSWORD = 21, APPLYINFO_MSG_NOT_HA_MODE = 22, APPLYINFO_MSG_HA_NOT_SUPPORT = 58, APPLYINFO_MSG_NOT_IN_STANDALONE = 59,
APPLYINFO_MSG_USAGE = 60
}
enum MSGCAT_ACLDB_MSG { ACLDB_MSG_NOT_IN_STANDALONE = 59, ACLDB_MSG_USAGE = 60 }
enum MSGCAT_GENLOCALE_MSG { GENLOCALE_MSG_USAGE = 60, GENLOCALE_MSG_INVALID_LOCALE = 61 }
enum MSGCAT_DUMPLOCALE_MSG { DUMPLOCALE_MSG_INCOMPAT_INPUT_SEL = 57, DUMPLOCALE_MSG_INVALID_CP_RANGE = 58, DUMPLOCALE_MSG_INVALID_LOCALE = 59, DUMPLOCALE_MSG_USAGE = 60 }
enum MSGCAT_SYNCCOLLDB_MSG {
SYNCCOLLDB_MSG_PARTITION_OBS_COLL = 43, SYNCCOLLDB_MSG_FK_OBS_COLL = 44, SYNCCOLLDB_MSG_CLASS_OBS_COLL = 45, SYNCCOLLDB_MSG_FI_OBS_COLL = 46,
SYNCCOLLDB_MSG_SYNC_ABORT = 47, SYNCCOLLDB_MSG_SYNC_OK = 48, SYNCCOLLDB_MSG_SYNC_CONTINUE = 49, SYNCCOLLDB_MSG_OBS_COLL = 50,
SYNCCOLLDB_MSG_TRIG_OBS_COLL = 51, SYNCCOLLDB_MSG_VIEW_OBS_COLL = 52, SYNCCOLLDB_MSG_ATTR_OBS_COLL = 53, SYNCCOLLDB_MSG_REPORT_SQL_FILE = 54,
SYNCCOLLDB_MSG_REPORT_NOT_NEEDED = 55, SYNCCOLLDB_MSG_REPORT_SYNC_REQUIRED = 56, SYNCCOLLDB_MSG_REPORT_NEW_COLL = 57, SYNCCOLLDB_MSG_REPORT_DB_OBS_OK = 58,
SYNCCOLLDB_MSG_REPORT_DB_OBS_NOK = 59, SYNCCOLLDB_MSG_USAGE = 60
}
enum MSGCAT_GEN_TZ_MSG { GEN_TZ_MSG_INVALID_MODE = 59, GEN_TZ_MSG_INVALID_INPUT_FOLDER = 60, GEN_TZ_MSG_USAGE = 61 }
enum MSGCAT_DUMP_TZ_MSG { DUMP_TZ_MSG_ID_OUT_OF_RANGE = 59, DUMP_TZ_MSG_USAGE = 60 }
enum MSGCAT_RESTORESLAVE_MSG {
RESTORESLAVE_MSG_FAILURE = 20, RESTORESLAVE_MSG_HA_CATALOG_FAIL = 21, RESTORESLAVE_MSG_INVAILD_OPTIONS = 22, RESTORESLAVE_MSG_INVAILD_STATE = 23,
RESTORESLAVE_MSG_USAGE = 60
}
enum MSGCAT_DELVOLDB_MSG {
DELVOLDB_MSG_READY_TO_DEL = 21, DELVOLDB_MSG_VERIFY = 22, DELVOLDB_MSG_CANNOT_REMOVE_FIRST_VOL = 31, DELVOLDB_MSG_CANNOT_FIND_VOL = 32,
DELVOLDB_MSG_TOO_MANY_VOLID = 33, DELVOL_MSG_INVALID_VOLUME_ID = 34, DELVOLDB_MSG_USAGE = 60
}
enum MSGCAT_VACUUMDB_MSG { VACUUMDB_MSG_CLIENT_SERVER_NOT_AVAILABLE = 20, VACUUMDB_MSG_FAILED = 21, VACUUMDB_MSG_BAD_OUTPUT = 22, VACUUMDB_MSG_USAGE = 60 }
enum MSGCAT_CHECKSUMDB_MSG {
CHECKSUMDB_MSG_INVALID_INPUT_FILE = 1, CHECKSUMDB_MSG_MUST_RUN_ON_ACTIVE = 2, CHECKSUMDB_MSG_HA_NOT_SUPPORT = 58, CHECKSUMDB_MSG_NOT_IN_STANDALONE = 59,
CHECKSUMDB_MSG_USAGE = 60
}
enum MSGCAT_TDE_MSG {
TDE_MSG_DBA_PASSWORD = 21, TDE_MSG_NO_SET_MK_INFO = 25, TDE_MSG_MK_CHANGING = 26, TDE_MSG_MK_CHANGED = 27,
TDE_MSG_MK_SET_ON_DATABASE_DELETE = 28, TDE_MSG_MK_DELETED = 29, TDE_MSG_MK_GENERATED = 30, TDE_MSG_USAGE = 60
}
enum UTIL_INDEX {
CREATEDB, RENAMEDB, COPYDB, DELETEDB,
BACKUPDB, RESTOREDB, ADDVOLDB, SPACEDB,
LOCKDB, KILLTRAN, OPTIMIZEDB, INSTALLDB,
DIAGDB, PATCHDB, CHECKDB, ALTERDBHOST,
PLANDUMP, ESTIMATE_DATA, ESTIMATE_INDEX, LOADDB,
UNLOADDB, COMPACTDB, PARAMDUMP, STATDUMP,
CHANGEMODE, COPYLOGDB, APPLYLOGDB, APPLYINFO,
ACLDB, GENLOCALE, DUMPLOCALE, SYNCCOLLDB,
TRANLIST, GEN_TZ, DUMP_TZ, RESTORESLAVE,
VACUUMDB, CHECKSUMDB, TDE, LOGFILEDUMP
}
enum UTIL_MODE { SA_ONLY, CS_ONLY, SA_CS }
enum UTIL_ARG_TYPE { ARG_INTEGER, ARG_STRING, ARG_BOOLEAN, ARG_BIGINT }
Functions
int utility_initialize (void)
const char * utility_get_generic_message (int message_index)
int check_database_name (const char *name)
int check_new_database_name (const char *name)
int check_volume_name (const char *name)
int utility_get_option_int_value (UTIL_ARG_MAP *arg_map, int arg_ch)
bool utility_get_option_bool_value (UTIL_ARG_MAP *arg_map, int arg_ch)
char * utility_get_option_string_value (UTIL_ARG_MAP *arg_map, int arg_ch, int index)
INT64 utility_get_option_bigint_value (UTIL_ARG_MAP *arg_map, int arg_ch)
int utility_get_option_string_table_size (UTIL_ARG_MAP *arg_map)
FILE * fopen_ex (const char *filename, const char *type)
bool util_is_localhost (char *host)
bool are_hostnames_equal (const char *hostname_a, const char *hostname_b)
void util_free_ha_conf (HA_CONF *ha_conf)
int util_make_ha_conf (HA_CONF *ha_conf)
int util_get_ha_mode_for_sa_utils (void)
int util_get_num_of_ha_nodes (const char *node_list)
void util_redirect_stdout_to_null (void)
int util_byte_to_size_string (char *buf, size_t len, UINT64 size_num)
int util_size_string_to_byte (UINT64 *size_num, const char *size_str)
int util_msec_to_time_string (char *buf, size_t len, INT64 msec_num)
int util_time_string_to_msec (INT64 *msec_num, char *time_str)
void util_print_deprecated (const char *option)
int util_get_table_list_from_file (char *fname, dynamic_array *darray)
int changemode_keyword (int *keyval_p, char **keystr_p)
int copylogdb_keyword (int *keyval_p, char **keystr_p)
int utility_keyword_value (UTIL_KEYWORD *keywords, int *keyval_p, char **keystr_p)
int utility_keyword_search (UTIL_KEYWORD *keywords, int *keyval_p, char **keystr_p)
int utility_localtime (const time_t *ts, struct tm *result)
int compactdb (UTIL_FUNCTION_ARG *arg_map)
int loaddb_user (UTIL_FUNCTION_ARG *arg_map)
int unloaddb (UTIL_FUNCTION_ARG *arg_map)
int backupdb (UTIL_FUNCTION_ARG *arg_map)
int addvoldb (UTIL_FUNCTION_ARG *arg_map)
int checkdb (UTIL_FUNCTION_ARG *arg_map)
int spacedb (UTIL_FUNCTION_ARG *arg_map)
int lockdb (UTIL_FUNCTION_ARG *arg_map)
int tranlist (UTIL_FUNCTION_ARG *arg_map)
int killtran (UTIL_FUNCTION_ARG *arg_map)
int restartevnt (UTIL_FUNCTION_ARG *arg_map)
int prestartldb (UTIL_FUNCTION_ARG *arg_map)
int shutdownldb (UTIL_FUNCTION_ARG *arg_map)
int mqueueldb (UTIL_FUNCTION_ARG *arg_map)
int plandump (UTIL_FUNCTION_ARG *arg_map)
int createdb (UTIL_FUNCTION_ARG *arg_map)
int deletedb (UTIL_FUNCTION_ARG *arg_map)
int restoredb (UTIL_FUNCTION_ARG *arg_map)
int renamedb (UTIL_FUNCTION_ARG *arg_map)
int installdb (UTIL_FUNCTION_ARG *arg_map)
int copydb (UTIL_FUNCTION_ARG *arg_map)
int optimizedb (UTIL_FUNCTION_ARG *arg_map)
int diagdb (UTIL_FUNCTION_ARG *arg_map)
int patchdb (UTIL_FUNCTION_ARG *arg_map)
int estimatedb_data (UTIL_FUNCTION_ARG *arg_map)
int estimatedb_index (UTIL_FUNCTION_ARG *arg_map)
int estimatedb_hash (UTIL_FUNCTION_ARG *arg_map)
int alterdbhost (UTIL_FUNCTION_ARG *arg_map)
int paramdump (UTIL_FUNCTION_ARG *arg_map)
int statdump (UTIL_FUNCTION_ARG *arg_map)
int changemode (UTIL_FUNCTION_ARG *arg_map)
int copylogdb (UTIL_FUNCTION_ARG *arg_map)
int applylogdb (UTIL_FUNCTION_ARG *arg_map)
int applyinfo (UTIL_FUNCTION_ARG *arg_map)
int acldb (UTIL_FUNCTION_ARG *arg_map)
int genlocale (UTIL_FUNCTION_ARG *arg_map)
int dumplocale (UTIL_FUNCTION_ARG *arg_map)
int synccolldb (UTIL_FUNCTION_ARG *arg_map)
int gen_tz (UTIL_FUNCTION_ARG *arg_map)
int dump_tz (UTIL_FUNCTION_ARG *arg_map)
int synccoll_force (void)
int restoreslave (UTIL_FUNCTION_ARG *arg_map)
int vacuumdb (UTIL_FUNCTION_ARG *arg_map)
int checksumdb (UTIL_FUNCTION_ARG *arg_map)
int tde (UTIL_FUNCTION_ARG *arg_map)
void util_admin_usage (const char *argv0)
void util_admin_version (const char *argv0)
Macro Definition Documentation
#define ACLDB_RELOAD "-r"
Definition at line 903 of file utility.h.
Referenced by process_server().
#define ACLDB_RELOAD_L "reload"
Definition at line 1458 of file utility.h.
#define ACLDB_RELOAD_S 'r'
Definition at line 1457 of file utility.h.
Referenced by acldb().
#define ADDVOL_COMMENT_L "comment"
Definition at line 1086 of file utility.h.
#define ADDVOL_COMMENT_S 10702
Definition at line 1085 of file utility.h.
Referenced by addvoldb().
#define ADDVOL_CS_MODE_L "CS-mode"
Definition at line 1092 of file utility.h.
#define ADDVOL_CS_MODE_S 'C'
Definition at line 1091 of file utility.h.
#define ADDVOL_FILE_PATH_L "file-path"
Definition at line 1084 of file utility.h.
#define ADDVOL_FILE_PATH_S 'F'
Definition at line 1083 of file utility.h.
Referenced by addvoldb().
#define ADDVOL_MAX_WRITESIZE_IN_SEC_L "max-writesize-in-sec"
Definition at line 1096 of file utility.h.
#define ADDVOL_MAX_WRITESIZE_IN_SEC_S 10707
Definition at line 1095 of file utility.h.
Referenced by addvoldb().
#define ADDVOL_PURPOSE_L "purpose"
Definition at line 1088 of file utility.h.
#define ADDVOL_PURPOSE_S 'p'
Definition at line 1087 of file utility.h.
Referenced by addvoldb().
#define ADDVOL_SA_MODE_L "SA-mode"
Definition at line 1090 of file utility.h.
#define ADDVOL_SA_MODE_S 'S'
Definition at line 1089 of file utility.h.
Referenced by addvoldb().
#define ADDVOL_VOLUME_NAME_L "volume-name"
Definition at line 1082 of file utility.h.
#define ADDVOL_VOLUME_NAME_S 'n'
Definition at line 1081 of file utility.h.
Referenced by addvoldb().
#define ADDVOL_VOLUME_SIZE_L "db-volume-size"
Definition at line 1094 of file utility.h.
#define ADDVOL_VOLUME_SIZE_S 10706
Definition at line 1093 of file utility.h.
Referenced by addvoldb().
#define ALTERDBHOST_HOST_L "host"
Definition at line 1160 of file utility.h.
#define ALTERDBHOST_HOST_S 'h'
Definition at line 1159 of file utility.h.
#define APPLYINFO_APPLIED_INFO_L "applied-info"
Definition at line 1490 of file utility.h.
#define APPLYINFO_APPLIED_INFO_S 'a'
Definition at line 1489 of file utility.h.
Referenced by applyinfo().
#define APPLYINFO_COPIED_LOG_PATH_L "copied-log-path"
Definition at line 1484 of file utility.h.
#define APPLYINFO_COPIED_LOG_PATH_S 'L'
Definition at line 1483 of file utility.h.
Referenced by applyinfo().
#define APPLYINFO_INTERVAL_L "interval"
Definition at line 1494 of file utility.h.
#define APPLYINFO_INTERVAL_S 'i'
Definition at line 1493 of file utility.h.
Referenced by applyinfo().
#define APPLYINFO_PAGE_L "page"
Definition at line 1486 of file utility.h.
#define APPLYINFO_PAGE_S 'p'
Definition at line 1485 of file utility.h.
Referenced by applyinfo().
#define APPLYINFO_REMOTE_NAME_L "remote-host-name"
Definition at line 1488 of file utility.h.
#define APPLYINFO_REMOTE_NAME_S 'r'
Definition at line 1487 of file utility.h.
Referenced by applyinfo().
#define APPLYINFO_VERBOSE_L "verbose"
Definition at line 1492 of file utility.h.
#define APPLYINFO_VERBOSE_S 'v'
Definition at line 1491 of file utility.h.
Referenced by applyinfo().
#define APPLYLOG_LOG_PATH_L "log-path"
Definition at line 1478 of file utility.h.
#define APPLYLOG_LOG_PATH_S 'L'
Definition at line 1477 of file utility.h.
Referenced by applylogdb().
#define APPLYLOG_MAX_MEM_SIZE_L "max-mem-size"
Definition at line 1480 of file utility.h.
#define APPLYLOG_MAX_MEM_SIZE_S 12401
Definition at line 1479 of file utility.h.
Referenced by applylogdb().
#define BACKUP_COMPRESS_L "compress"
Definition at line 1053 of file utility.h.
#define BACKUP_COMPRESS_S 'z'
Definition at line 1052 of file utility.h.
Referenced by backupdb().
#define BACKUP_CS_MODE_L "CS-mode"
Definition at line 1047 of file utility.h.
#define BACKUP_CS_MODE_S 'C'
Definition at line 1046 of file utility.h.
#define BACKUP_DESTINATION_PATH_L "destination-path"
Definition at line 1037 of file utility.h.
#define BACKUP_DESTINATION_PATH_S 'D'
Definition at line 1036 of file utility.h.
Referenced by backupdb().
#define BACKUP_EXCEPT_ACTIVE_LOG_L "except-active-log"
Definition at line 1055 of file utility.h.
#define BACKUP_EXCEPT_ACTIVE_LOG_S 'e'
Definition at line 1054 of file utility.h.
#define BACKUP_LEVEL_L "level"
Definition at line 1041 of file utility.h.
#define BACKUP_LEVEL_S 'l'
Definition at line 1040 of file utility.h.
Referenced by backupdb().
#define BACKUP_NO_CHECK_L "no-check"
Definition at line 1049 of file utility.h.
#define BACKUP_NO_CHECK_S 10506
Definition at line 1048 of file utility.h.
Referenced by backupdb().
#define BACKUP_OUTPUT_FILE_L "output-file"
Definition at line 1043 of file utility.h.
#define BACKUP_OUTPUT_FILE_S 'o'
Definition at line 1042 of file utility.h.
Referenced by backupdb().
#define BACKUP_REMOVE_ARCHIVE_L "remove-archive"
Definition at line 1039 of file utility.h.
#define BACKUP_REMOVE_ARCHIVE_S 'r'
Definition at line 1038 of file utility.h.
Referenced by backupdb().
#define BACKUP_SA_MODE_L "SA-mode"
Definition at line 1045 of file utility.h.
#define BACKUP_SA_MODE_S 'S'
Definition at line 1044 of file utility.h.
Referenced by backupdb().
#define BACKUP_SEPARATE_KEYS_L "separate-keys"
Definition at line 1059 of file utility.h.
#define BACKUP_SEPARATE_KEYS_S 'k'
Definition at line 1058 of file utility.h.
Referenced by backupdb().
#define BACKUP_SLEEP_MSECS_L "sleep-msecs"
Definition at line 1057 of file utility.h.
#define BACKUP_SLEEP_MSECS_S 10600
Definition at line 1056 of file utility.h.
Referenced by backupdb().
#define BACKUP_THREAD_COUNT_L "thread-count"
Definition at line 1051 of file utility.h.
#define BACKUP_THREAD_COUNT_S 't'
Definition at line 1050 of file utility.h.
Referenced by backupdb().
#define CHANGEMODE_FORCE_L "force"
Definition at line 1464 of file utility.h.
#define CHANGEMODE_FORCE_S 'f'
Definition at line 1463 of file utility.h.
Referenced by changemode().
#define CHANGEMODE_MODE_L "mode"
Definition at line 1462 of file utility.h.
#define CHANGEMODE_MODE_S 'm'
Definition at line 1461 of file utility.h.
Referenced by changemode().
#define CHANGEMODE_TIMEOUT_L "timeout"
Definition at line 1466 of file utility.h.
#define CHANGEMODE_TIMEOUT_S 't'
Definition at line 1465 of file utility.h.
Referenced by changemode().
#define CHECK_BTREE_ALL_BTREES_L "check-btree"
Definition at line 1184 of file utility.h.
#define CHECK_BTREE_ALL_BTREES_S 11506
Definition at line 1183 of file utility.h.
Referenced by checkdb().
#define CHECK_CAT_CONSISTENCY_L "check-catalog"
Definition at line 1182 of file utility.h.
#define CHECK_CAT_CONSISTENCY_S 11505
Definition at line 1181 of file utility.h.
Referenced by checkdb().
#define CHECK_CHECK_PREV_LINK_L "check-prev-link"
Definition at line 1174 of file utility.h.
#define CHECK_CHECK_PREV_LINK_S 11501
Definition at line 1173 of file utility.h.
Referenced by checkdb().
#define CHECK_CS_MODE_L "CS-mode"
Definition at line 1166 of file utility.h.
#define CHECK_CS_MODE_S 'C'
Definition at line 1165 of file utility.h.
#define CHECK_FILE_TRACKER_L "check-file-tracker"
Definition at line 1178 of file utility.h.
#define CHECK_FILE_TRACKER_S 11503
Definition at line 1177 of file utility.h.
Referenced by checkdb().
#define CHECK_HA_SERVER "HA-Server"
Definition at line 878 of file utility.h.
Referenced by check_server().
#define CHECK_HEAP_ALLHEAPS_L "check-heap"
Definition at line 1180 of file utility.h.
#define CHECK_HEAP_ALLHEAPS_S 11504
Definition at line 1179 of file utility.h.
Referenced by checkdb().
#define CHECK_INDEXNAME_L "index-name"
Definition at line 1172 of file utility.h.
#define CHECK_INDEXNAME_S 'I'
Definition at line 1171 of file utility.h.
Referenced by checkdb().
#define CHECK_INPUT_FILE_L "input-file"
Definition at line 1170 of file utility.h.
#define CHECK_INPUT_FILE_S 'i'
Definition at line 1169 of file utility.h.
Referenced by checkdb().
#define CHECK_LC_ALLENTRIES_OF_ALLBTREES_L "check-btree-entries"
Definition at line 1188 of file utility.h.
#define CHECK_LC_ALLENTRIES_OF_ALLBTREES_S 11508
Definition at line 1187 of file utility.h.
Referenced by checkdb().
#define CHECK_LC_CLASSNAMES_L "check-class-name"
Definition at line 1186 of file utility.h.
#define CHECK_LC_CLASSNAMES_S 11507
Definition at line 1185 of file utility.h.
Referenced by checkdb().
#define CHECK_REPAIR_L "repair"
Definition at line 1168 of file utility.h.
#define CHECK_REPAIR_PREV_LINK_L "repair-prev-link"
Definition at line 1176 of file utility.h.
#define CHECK_REPAIR_PREV_LINK_S 11502
Definition at line 1175 of file utility.h.
Referenced by checkdb().
#define CHECK_REPAIR_S 'r'
Definition at line 1167 of file utility.h.
Referenced by checkdb().
#define CHECK_SA_MODE_L "SA-mode"
Definition at line 1164 of file utility.h.
#define CHECK_SA_MODE_S 'S'
Definition at line 1163 of file utility.h.
#define CHECK_SERVER "Server"
Definition at line 877 of file utility.h.
Referenced by check_all_services_status(), check_server(), process_server(), us_hb_server_start(), and us_hb_server_stop().
#define CHECKSUM_CHUNK_SIZE_L "chunk-size"
Definition at line 1586 of file utility.h.
#define CHECKSUM_CHUNK_SIZE_S 'c'
Definition at line 1585 of file utility.h.
Referenced by checksumdb().
#define CHECKSUM_CONT_ON_ERROR_L "cont-on-error"
Definition at line 1592 of file utility.h.
#define CHECKSUM_CONT_ON_ERROR_S 14001
Definition at line 1591 of file utility.h.
Referenced by checksumdb().
#define CHECKSUM_EXCLUDE_CLASS_FILE_L "exclude-class-file"
Definition at line 1596 of file utility.h.
#define CHECKSUM_EXCLUDE_CLASS_FILE_S 'e'
Definition at line 1595 of file utility.h.
Referenced by checksumdb().
#define CHECKSUM_INCLUDE_CLASS_FILE_L "include-class-file"
Definition at line 1594 of file utility.h.
#define CHECKSUM_INCLUDE_CLASS_FILE_S 'i'
Definition at line 1593 of file utility.h.
Referenced by checksumdb().
#define CHECKSUM_REPORT_ONLY_L "report-only"
Definition at line 1602 of file utility.h.
#define CHECKSUM_REPORT_ONLY_S 'r'
Definition at line 1601 of file utility.h.
Referenced by checksumdb().
#define CHECKSUM_RESUME_L "resume"
Definition at line 1588 of file utility.h.
#define CHECKSUM_RESUME_S 14000
Definition at line 1587 of file utility.h.
Referenced by checksumdb().
#define CHECKSUM_SCHEMA_ONLY_L "schema-only"
Definition at line 1604 of file utility.h.
#define CHECKSUM_SCHEMA_ONLY_S 14002
Definition at line 1603 of file utility.h.
Referenced by checksumdb().
#define CHECKSUM_SLEEP_L "sleep"
Definition at line 1590 of file utility.h.
#define CHECKSUM_SLEEP_S 's'
Definition at line 1589 of file utility.h.
Referenced by checksumdb().
#define CHECKSUM_TABLE_NAME_L "table-name"
Definition at line 1600 of file utility.h.
#define CHECKSUM_TABLE_NAME_S 'n'
Definition at line 1599 of file utility.h.
Referenced by checksumdb().
#define CHECKSUM_TIMEOUT_L "timeout"
Definition at line 1598 of file utility.h.
#define CHECKSUM_TIMEOUT_S 't'
Definition at line 1597 of file utility.h.
Referenced by checksumdb().
#define COMMDB_ACTIVATE_HEARTBEAT_L "activate-heartbeat"
Definition at line 1426 of file utility.h.
Referenced by main().
#define COMMDB_ACTIVATE_HEARTBEAT_S 12114
Definition at line 1425 of file utility.h.
Referenced by main().
#define COMMDB_ALL_LIST_L "all-list"
Definition at line 1392 of file utility.h.
Referenced by main().
#define COMMDB_ALL_LIST_S 'O'
Definition at line 1391 of file utility.h.
Referenced by main().
#define COMMDB_ALL_STATUS "-O"
Definition at line 882 of file utility.h.
Referenced by check_server().
#define COMMDB_ALL_STOP "-A"
Definition at line 883 of file utility.h.
Referenced by process_master().
#define COMMDB_DEACT_CONFIRM_NO_SERVER_L "deact-confirm-no-server"
Definition at line 1424 of file utility.h.
Referenced by main().
#define COMMDB_DEACT_CONFIRM_NO_SERVER_S 12113
Definition at line 1423 of file utility.h.
Referenced by main().
#define COMMDB_DEACT_CONFIRM_STOP_ALL_L "deact-confirm-stop-all"
Definition at line 1422 of file utility.h.
Referenced by main().
#define COMMDB_DEACT_CONFIRM_STOP_ALL_S 12112
Definition at line 1421 of file utility.h.
Referenced by main().
#define COMMDB_DEACT_STOP_ALL_L "deact-stop-all"
Definition at line 1420 of file utility.h.
Referenced by main().
#define COMMDB_DEACT_STOP_ALL_S 12111
Definition at line 1419 of file utility.h.
Referenced by main().
#define COMMDB_DEACTIVATE_HEARTBEAT_L "deactivate-heartbeat"
Definition at line 1418 of file utility.h.
Referenced by main().
#define COMMDB_DEACTIVATE_HEARTBEAT_S 12110
Definition at line 1417 of file utility.h.
Referenced by main().
#define COMMDB_DEREG_HA_BY_ARGS_L "dereg-args"
Definition at line 1410 of file utility.h.
Referenced by main().
#define COMMDB_DEREG_HA_BY_ARGS_S 'R'
Definition at line 1409 of file utility.h.
Referenced by main().
#define COMMDB_DEREG_HA_BY_PID_L "dereg-process"
Definition at line 1408 of file utility.h.
Referenced by main().
#define COMMDB_DEREG_HA_BY_PID_S 'D'
Definition at line 1407 of file utility.h.
Referenced by main().
#define COMMDB_HA_ACTIVATE "--activate-heartbeat"
Definition at line 896 of file utility.h.
Referenced by process_heartbeat_replication(), and process_heartbeat_start().
#define COMMDB_HA_ADMIN_INFO "--admin-info"
Definition at line 899 of file utility.h.
Referenced by process_heartbeat_status().
#define COMMDB_HA_ADMIN_INFO_L "admin-info"
Definition at line 1432 of file utility.h.
Referenced by main().
#define COMMDB_HA_ADMIN_INFO_S 12115
Definition at line 1431 of file utility.h.
Referenced by main().
#define COMMDB_HA_ALL_STOP "-d"
Definition at line 886 of file utility.h.
#define COMMDB_HA_DEACT_CONFIRM_NO_SERVER "--deact-confirm-no-server"
Definition at line 894 of file utility.h.
Referenced by us_hb_deactivate().
#define COMMDB_HA_DEACT_CONFIRM_STOP_ALL "--deact-confirm-stop-all"
Definition at line 893 of file utility.h.
Referenced by us_hb_deactivate().
#define COMMDB_HA_DEACT_STOP_ALL "--deact-stop-all"
Definition at line 892 of file utility.h.
Referenced by us_hb_deactivate().
#define COMMDB_HA_DEACTIVATE "--deactivate-heartbeat"
Definition at line 895 of file utility.h.
Referenced by us_hb_deactivate().
#define COMMDB_HA_DEREG_BY_ARGS "-R"
Definition at line 885 of file utility.h.
Referenced by us_hb_applylogdb_stop(), and us_hb_copylogdb_stop().
#define COMMDB_HA_DEREG_BY_PID "-D"
Definition at line 884 of file utility.h.
Referenced by process_heartbeat_deregister().
#define COMMDB_HA_NODE_LIST "-N"
Definition at line 888 of file utility.h.
Referenced by process_heartbeat_status().
#define COMMDB_HA_NODE_LIST_L "node-list"
Definition at line 1402 of file utility.h.
Referenced by main().
#define COMMDB_HA_NODE_LIST_S 'N'
Definition at line 1401 of file utility.h.
Referenced by main().
#define COMMDB_HA_PING_HOST_LIST "-p"
Definition at line 890 of file utility.h.
Referenced by process_heartbeat_status().
#define COMMDB_HA_PING_HOST_LIST_L "ping-host"
Definition at line 1406 of file utility.h.
Referenced by main().
#define COMMDB_HA_PING_HOST_LIST_S 'p'
Definition at line 1405 of file utility.h.
Referenced by main().
#define COMMDB_HA_PROC_LIST "-L"
Definition at line 889 of file utility.h.
Referenced by process_heartbeat_status().
#define COMMDB_HA_PROCESS_LIST_L "process-list"
Definition at line 1404 of file utility.h.
Referenced by main().
#define COMMDB_HA_PROCESS_LIST_S 'L'
Definition at line 1403 of file utility.h.
Referenced by main().
#define COMMDB_HA_RELOAD "-F"
Definition at line 891 of file utility.h.
Referenced by process_heartbeat_reload().
#define COMMDB_HA_START_UTIL_PROCESS "-t"
Definition at line 901 of file utility.h.
Referenced by us_hb_applylogdb_start(), and us_hb_copylogdb_start().
#define COMMDB_HA_START_UTIL_PROCESS_L "start-ha-util-process"
Definition at line 1434 of file utility.h.
Referenced by main().
#define COMMDB_HA_START_UTIL_PROCESS_S 't'
Definition at line 1433 of file utility.h.
Referenced by main().
#define COMMDB_HB_DEACT_IMMEDIATELY "-i"
Definition at line 898 of file utility.h.
Referenced by us_hb_deactivate().
#define COMMDB_HB_DEACT_IMMEDIATELY_L "immediately"
Definition at line 1430 of file utility.h.
Referenced by main(), and us_hb_stop_get_options().
#define COMMDB_HB_DEACT_IMMEDIATELY_S 'i'
Definition at line 1429 of file utility.h.
Referenced by main(), and us_hb_stop_get_options().
#define COMMDB_HOST "-h"
Definition at line 897 of file utility.h.
Referenced by ha_is_registered(), process_heartbeat_status(), us_hb_applylogdb_start(), us_hb_applylogdb_stop(), us_hb_copylogdb_start(), us_hb_copylogdb_stop(), and us_hb_deactivate().
#define COMMDB_HOST_L "host"
Definition at line 1398 of file utility.h.
Referenced by main(), us_hb_status_get_options(), us_hb_stop_get_options(), and us_hb_util_get_options().
#define COMMDB_HOST_S 'h'
Definition at line 1397 of file utility.h.
Referenced by main(), us_hb_status_get_options(), us_hb_stop_get_options(), and us_hb_util_get_options().
#define COMMDB_IS_REG "-C"
Definition at line 887 of file utility.h.
Referenced by ha_is_registered().
#define COMMDB_IS_REGISTERED_PROC_L "is-registered-proc"
Definition at line 1414 of file utility.h.
Referenced by main().
#define COMMDB_IS_REGISTERED_PROC_S 'C'
Definition at line 1413 of file utility.h.
Referenced by main().
#define COMMDB_KILL_ALL_HA_PROCESS_L "kill-all-ha-process"
Definition at line 1412 of file utility.h.
Referenced by main().
#define COMMDB_KILL_ALL_HA_PROCESS_S 'd'
Definition at line 1411 of file utility.h.
Referenced by main().
#define COMMDB_RECONFIG_HEARTBEAT_L "reconfig-node-list"
Definition at line 1416 of file utility.h.
Referenced by main().
#define COMMDB_RECONFIG_HEARTBEAT_S 'F'
Definition at line 1415 of file utility.h.
Referenced by main().
#define COMMDB_SERVER_LIST_L "server-list"
Definition at line 1390 of file utility.h.
Referenced by main().
#define COMMDB_SERVER_LIST_S 'P'
Definition at line 1389 of file utility.h.
Referenced by main().
#define COMMDB_SERVER_MODE_L "server-mode"
Definition at line 1400 of file utility.h.
Referenced by main().
#define COMMDB_SERVER_MODE_S 'c'
Definition at line 1399 of file utility.h.
Referenced by main().
#define COMMDB_SERVER_STATUS "-P"
Definition at line 881 of file utility.h.
Referenced by process_server().
#define COMMDB_SERVER_STOP "-S"
Definition at line 880 of file utility.h.
Referenced by process_server().
#define COMMDB_SHUTDOWN_ALL_L "shutdown-all"
Definition at line 1396 of file utility.h.
Referenced by main().
#define COMMDB_SHUTDOWN_ALL_S 'A'
Definition at line 1395 of file utility.h.
Referenced by main().
#define COMMDB_SHUTDOWN_SERVER_L "shutdown-server"
Definition at line 1394 of file utility.h.
Referenced by main().
#define COMMDB_SHUTDOWN_SERVER_S 'S'
Definition at line 1393 of file utility.h.
Referenced by main().
#define COMMDB_VERBOSE_OUTPUT "--verbose"
Definition at line 900 of file utility.h.
Referenced by process_heartbeat_status().
#define COMMDB_VERBOSE_OUTPUT_L "verbose"
Definition at line 1428 of file utility.h.
Referenced by main().
#define COMMDB_VERBOSE_OUTPUT_S 'V'
Definition at line 1427 of file utility.h.
Referenced by main().
#define COMPACT_CLASS_LOCK_TIMEOUT_L "class-lock-timeout"
Definition at line 1333 of file utility.h.
#define COMPACT_CLASS_LOCK_TIMEOUT_S 'c'
Definition at line 1332 of file utility.h.
Referenced by compactdb().
#define COMPACT_CS_MODE_L "CS-mode"
Definition at line 1323 of file utility.h.
#define COMPACT_CS_MODE_S 'C'
Definition at line 1322 of file utility.h.
#define COMPACT_DELETE_OLD_REPR_L "delete-old-repr"
Definition at line 1329 of file utility.h.
#define COMPACT_DELETE_OLD_REPR_S 'd'
Definition at line 1328 of file utility.h.
Referenced by compactdb().
#define COMPACT_INPUT_CLASS_FILE_L "input-class-file"
Definition at line 1321 of file utility.h.
#define COMPACT_INPUT_CLASS_FILE_S 'i'
Definition at line 1320 of file utility.h.
Referenced by compactdb().
#define COMPACT_INSTANCE_LOCK_TIMEOUT_L "Instance-lock-timeout"
Definition at line 1331 of file utility.h.
#define COMPACT_INSTANCE_LOCK_TIMEOUT_S 'I'
Definition at line 1330 of file utility.h.
Referenced by compactdb().
#define COMPACT_PAGES_COMMITED_ONCE_L "pages-commited-once"
Definition at line 1327 of file utility.h.
#define COMPACT_PAGES_COMMITED_ONCE_S 'p'
Definition at line 1326 of file utility.h.
Referenced by compactdb().
#define COMPACT_SA_MODE_L "SA-mode"
Definition at line 1325 of file utility.h.
#define COMPACT_SA_MODE_S 'S'
Definition at line 1324 of file utility.h.
#define COMPACT_STANDBY_CS_MODE_L "standby"
Definition at line 1335 of file utility.h.
#define COMPACT_STANDBY_CS_MODE_S 12000
Definition at line 1334 of file utility.h.
Referenced by compactdb().
#define COMPACT_VERBOSE_L "verbose"
Definition at line 1319 of file utility.h.
#define COMPACT_VERBOSE_S 'v'
Definition at line 1318 of file utility.h.
Referenced by compactdb().
#define COPY_CONTROL_FILE_L "control-file"
Definition at line 1019 of file utility.h.
#define COPY_CONTROL_FILE_S 'i'
Definition at line 1018 of file utility.h.
Referenced by copydb().
#define COPY_COPY_LOB_PATH_L "copy-lob-path"
Definition at line 1027 of file utility.h.
#define COPY_COPY_LOB_PATH_S 10308
Definition at line 1026 of file utility.h.
Referenced by copydb().
#define COPY_DELETE_SOURCE_L "delete-source"
Definition at line 1023 of file utility.h.
#define COPY_DELETE_SOURCE_S 'd'
Definition at line 1022 of file utility.h.
Referenced by copydb().
#define COPY_EXTENTED_VOLUME_PATH_L "extended-volume-path"
Definition at line 1017 of file utility.h.
#define COPY_EXTENTED_VOLUME_PATH_S 'E'
Definition at line 1016 of file utility.h.
Referenced by copydb().
#define COPY_FILE_PATH_L "file-path"
Definition at line 1013 of file utility.h.
#define COPY_FILE_PATH_S 'F'
Definition at line 1012 of file utility.h.
Referenced by copydb().
#define COPY_LOB_PATH_L "lob-base-path"
Definition at line 1025 of file utility.h.
#define COPY_LOB_PATH_S 'B'
Definition at line 1024 of file utility.h.
Referenced by copydb().
#define COPY_LOG_PATH_L "log-path"
Definition at line 1015 of file utility.h.
#define COPY_LOG_PATH_S 'L'
Definition at line 1014 of file utility.h.
Referenced by copydb().
#define COPY_REPLACE_L "replace"
Definition at line 1021 of file utility.h.
#define COPY_REPLACE_S 'r'
Definition at line 1020 of file utility.h.
Referenced by copydb().
#define COPY_SERVER_NAME_L "server-name"
Definition at line 1011 of file utility.h.
#define COPY_SERVER_NAME_S 10300
Definition at line 1010 of file utility.h.
Referenced by copydb().
#define COPYLOG_LOG_PATH_L "log-path"
Definition at line 1470 of file utility.h.
#define COPYLOG_LOG_PATH_S 'L'
Definition at line 1469 of file utility.h.
Referenced by copylogdb().
#define COPYLOG_MODE_L "mode"
Definition at line 1472 of file utility.h.
#define COPYLOG_MODE_S 'm'
Definition at line 1471 of file utility.h.
Referenced by copylogdb().
#define COPYLOG_START_PAGEID_L "start-page-id"
Definition at line 1474 of file utility.h.
#define COPYLOG_START_PAGEID_S 'S'
Definition at line 1473 of file utility.h.
Referenced by copylogdb().
#define CREATE_CHARSET_L "charset"
Definition at line 987 of file utility.h.
#define CREATE_CHARSET_S 10112
Definition at line 986 of file utility.h.
#define CREATE_COMMENT_L "comment"
Definition at line 965 of file utility.h.
#define CREATE_COMMENT_S 10102
Definition at line 964 of file utility.h.
Referenced by createdb().
#define CREATE_CSQL_INITIALIZATION_FILE_L "csql-initialization-file"
Definition at line 981 of file utility.h.
#define CREATE_CSQL_INITIALIZATION_FILE_S 10109
Definition at line 980 of file utility.h.
Referenced by createdb().
#define CREATE_DB_PAGE_SIZE_L "db-page-size"
Definition at line 995 of file utility.h.
Referenced by createdb().
#define CREATE_DB_PAGE_SIZE_S 10114
Definition at line 994 of file utility.h.
Referenced by createdb().
#define CREATE_DB_VOLUME_SIZE_L "db-volume-size"
Definition at line 997 of file utility.h.
Referenced by createdb().
#define CREATE_DB_VOLUME_SIZE_S 10115
Definition at line 996 of file utility.h.
Referenced by createdb().
#define CREATE_FILE_PATH_L "file-path"
Definition at line 967 of file utility.h.
#define CREATE_FILE_PATH_S 'F'
Definition at line 966 of file utility.h.
Referenced by createdb().
#define CREATE_LOB_PATH_L "lob-base-path"
Definition at line 971 of file utility.h.
#define CREATE_LOB_PATH_S 'B'
Definition at line 970 of file utility.h.
Referenced by createdb().
#define CREATE_LOG_PAGE_COUNT_L "log-page-count"
Definition at line 989 of file utility.h.
Referenced by createdb().
#define CREATE_LOG_PAGE_COUNT_S 'l'
Definition at line 988 of file utility.h.
Referenced by createdb().
#define CREATE_LOG_PAGE_SIZE_L "log-page-size"
Definition at line 993 of file utility.h.
Referenced by createdb().
#define CREATE_LOG_PAGE_SIZE_S 10113
Definition at line 992 of file utility.h.
Referenced by createdb().
#define CREATE_LOG_PATH_L "log-path"
Definition at line 969 of file utility.h.
#define CREATE_LOG_PATH_S 'L'
Definition at line 968 of file utility.h.
Referenced by createdb().
#define CREATE_LOG_VOLUME_SIZE_L "log-volume-size"
Definition at line 999 of file utility.h.
Referenced by createdb().
#define CREATE_LOG_VOLUME_SIZE_S 10116
Definition at line 998 of file utility.h.
Referenced by createdb().
#define CREATE_MORE_VOLUME_FILE_L "more-volume-file"
Definition at line 977 of file utility.h.
#define CREATE_MORE_VOLUME_FILE_S 10107
Definition at line 976 of file utility.h.
Referenced by createdb().
#define CREATE_OUTPUT_FILE_L "output-file"
Definition at line 983 of file utility.h.
#define CREATE_OUTPUT_FILE_S 'o'
Definition at line 982 of file utility.h.
Referenced by createdb().
#define CREATE_PAGE_SIZE_L "page-size"
Definition at line 991 of file utility.h.
Referenced by createdb().
#define CREATE_PAGE_SIZE_S 's'
Definition at line 990 of file utility.h.
Referenced by createdb().
#define CREATE_PAGES_L "pages"
Definition at line 963 of file utility.h.
Referenced by createdb().
#define CREATE_PAGES_S 'p'
Definition at line 962 of file utility.h.
Referenced by createdb().
#define CREATE_REPLACE_L "replace"
Definition at line 975 of file utility.h.
#define CREATE_REPLACE_S 'r'
Definition at line 974 of file utility.h.
Referenced by createdb().
#define CREATE_SERVER_NAME_L "server-name"
Definition at line 973 of file utility.h.
#define CREATE_SERVER_NAME_S 10105
Definition at line 972 of file utility.h.
Referenced by createdb().
#define CREATE_USER_DEFINITION_FILE_L "user-definition-file"
Definition at line 979 of file utility.h.
#define CREATE_USER_DEFINITION_FILE_S 10108
Definition at line 978 of file utility.h.
Referenced by createdb().
#define CREATE_VERBOSE_L "verbose"
Definition at line 985 of file utility.h.
#define CREATE_VERBOSE_S 'v'
Definition at line 984 of file utility.h.
Referenced by createdb().
#define CSQL_COMMAND_L "command"
Definition at line 1355 of file utility.h.
Referenced by main().
#define CSQL_COMMAND_S 'c'
Definition at line 1354 of file utility.h.
Referenced by main().
#define CSQL_CS_MODE_L "CS-mode"
Definition at line 1341 of file utility.h.
Referenced by main().
#define CSQL_CS_MODE_S 'C'
Definition at line 1340 of file utility.h.
Referenced by main().
#define CSQL_ERROR_CONTINUE_L "error-continue"
Definition at line 1347 of file utility.h.
Referenced by main().
#define CSQL_ERROR_CONTINUE_S 'e'
Definition at line 1346 of file utility.h.
Referenced by main().
#define CSQL_INPUT_FILE_L "input-file"
Definition at line 1349 of file utility.h.
Referenced by main().
#define CSQL_INPUT_FILE_S 'i'
Definition at line 1348 of file utility.h.
Referenced by main().
#define CSQL_LINE_OUTPUT_L "line-output"
Definition at line 1357 of file utility.h.
Referenced by main().
#define CSQL_LINE_OUTPUT_S 'l'
Definition at line 1356 of file utility.h.
Referenced by main().
#define CSQL_LOADDB_OUTPUT_L "loaddb-output"
Definition at line 1387 of file utility.h.
Referenced by main().
#define CSQL_LOADDB_OUTPUT_S 'd'
Definition at line 1386 of file utility.h.
Referenced by main().
#define CSQL_NO_AUTO_COMMIT_L "no-auto-commit"
Definition at line 1361 of file utility.h.
Referenced by main().
#define CSQL_NO_AUTO_COMMIT_S 12010
Definition at line 1360 of file utility.h.
Referenced by main().
#define CSQL_NO_PAGER_L "no-pager"
Definition at line 1363 of file utility.h.
Referenced by main().
#define CSQL_NO_PAGER_S 12011
Definition at line 1362 of file utility.h.
Referenced by main().
#define CSQL_NO_SINGLE_LINE_L "no-single-line"
Definition at line 1367 of file utility.h.
Referenced by main().
#define CSQL_NO_SINGLE_LINE_S 12013
Definition at line 1366 of file utility.h.
Referenced by main().
#define CSQL_NO_TRIGGER_ACTION_L "no-trigger-action"
Definition at line 1373 of file utility.h.
Referenced by main().
#define CSQL_NO_TRIGGER_ACTION_S 12016
Definition at line 1372 of file utility.h.
Referenced by main().
#define CSQL_OUTPUT_FILE_L "output-file"
Definition at line 1351 of file utility.h.
Referenced by main().
#define CSQL_OUTPUT_FILE_S 'o'
Definition at line 1350 of file utility.h.
Referenced by main().
#define CSQL_PASSWORD_L "password"
Definition at line 1345 of file utility.h.
Referenced by main().
#define CSQL_PASSWORD_S 'p'
Definition at line 1344 of file utility.h.
Referenced by main().
#define CSQL_PLAIN_OUTPUT_L "plain-output"
Definition at line 1375 of file utility.h.
Referenced by main().
#define CSQL_PLAIN_OUTPUT_S 't'
Definition at line 1374 of file utility.h.
Referenced by main().
#define CSQL_QUERY_COLUMN_DELIMITER_L "delimiter"
Definition at line 1383 of file utility.h.
Referenced by main().
#define CSQL_QUERY_COLUMN_DELIMITER_S 12018
Definition at line 1382 of file utility.h.
Referenced by main().
#define CSQL_QUERY_COLUMN_ENCLOSURE_L "enclosure"
Definition at line 1385 of file utility.h.
Referenced by main().
#define CSQL_QUERY_COLUMN_ENCLOSURE_S 12019
Definition at line 1384 of file utility.h.
Referenced by main().
#define CSQL_QUERY_OUTPUT_L "query-output"
Definition at line 1381 of file utility.h.
Referenced by main().
#define CSQL_QUERY_OUTPUT_S 'q'
Definition at line 1380 of file utility.h.
Referenced by main().
#define CSQL_READ_ONLY_L "read-only"
Definition at line 1359 of file utility.h.
Referenced by main().
#define CSQL_READ_ONLY_S 'r'
Definition at line 1358 of file utility.h.
Referenced by main().
#define CSQL_SA_MODE_L "SA-mode"
Definition at line 1339 of file utility.h.
Referenced by main().
#define CSQL_SA_MODE_S 'S'
Definition at line 1338 of file utility.h.
Referenced by main().
#define CSQL_SINGLE_LINE_L "single-line"
Definition at line 1353 of file utility.h.
Referenced by main().
#define CSQL_SINGLE_LINE_S 's'
Definition at line 1352 of file utility.h.
Referenced by main().
#define CSQL_SKIP_COL_NAMES_L "skip-column-names"
Definition at line 1377 of file utility.h.
Referenced by main().
#define CSQL_SKIP_COL_NAMES_S 'N'
Definition at line 1376 of file utility.h.
Referenced by main().
#define CSQL_SKIP_VACUUM_L "skip-vacuum"
Definition at line 1379 of file utility.h.
Referenced by main().
#define CSQL_SKIP_VACUUM_S 12017
Definition at line 1378 of file utility.h.
Referenced by main().
#define CSQL_STRING_WIDTH_L "string-width"
Definition at line 1369 of file utility.h.
Referenced by main().
#define CSQL_STRING_WIDTH_S 12014
Definition at line 1368 of file utility.h.
Referenced by main().
#define CSQL_SYSADM_L "sysadm"
Definition at line 1365 of file utility.h.
Referenced by main().
#define CSQL_SYSADM_S 12012
Definition at line 1364 of file utility.h.
Referenced by main().
#define CSQL_USER_L "user"
Definition at line 1343 of file utility.h.
Referenced by main().
#define CSQL_USER_S 'u'
Definition at line 1342 of file utility.h.
Referenced by main().
#define CSQL_WRITE_ON_STANDBY_L "write-on-standby"
Definition at line 1371 of file utility.h.
Referenced by main().
#define CSQL_WRITE_ON_STANDBY_S 12015
Definition at line 1370 of file utility.h.
Referenced by main().
#define DELETE_DELETE_BACKUP_L "delete-backup"
Definition at line 1033 of file utility.h.
#define DELETE_DELETE_BACKUP_S 'd'
Definition at line 1032 of file utility.h.
Referenced by deletedb().
#define DELETE_OUTPUT_FILE_L "output-file"
Definition at line 1031 of file utility.h.
#define DELETE_OUTPUT_FILE_S 'o'
Definition at line 1030 of file utility.h.
Referenced by deletedb().
#define DIAG_DUMP_RECORDS_L "dump-records"
Definition at line 1148 of file utility.h.
#define DIAG_DUMP_RECORDS_S 11201
Definition at line 1147 of file utility.h.
Referenced by diagdb().
#define DIAG_DUMP_TYPE_L "dump-type"
Definition at line 1146 of file utility.h.
#define DIAG_DUMP_TYPE_S 'd'
Definition at line 1145 of file utility.h.
Referenced by diagdb().
#define DIAG_EMERGENCY_L "emergency"
Definition at line 1152 of file utility.h.
#define DIAG_EMERGENCY_S 11202
Definition at line 1151 of file utility.h.
Referenced by diagdb().
#define DIAG_OUTPUT_FILE_L "output-file"
Definition at line 1150 of file utility.h.
#define DIAG_OUTPUT_FILE_S 'o'
Definition at line 1149 of file utility.h.
Referenced by diagdb().
#define DUMP_TZ_COUNTRIES_L "list-countries"
Definition at line 1545 of file utility.h.
#define DUMP_TZ_COUNTRIES_S 'c'
Definition at line 1544 of file utility.h.
Referenced by dump_tz().
#define DUMP_TZ_DUMP_SUM_L "summary"
Definition at line 1553 of file utility.h.
#define DUMP_TZ_DUMP_SUM_S 's'
Definition at line 1552 of file utility.h.
Referenced by dump_tz().
#define DUMP_TZ_LEAP_SEC_L "leap-seconds"
Definition at line 1551 of file utility.h.
#define DUMP_TZ_LEAP_SEC_S 'l'
Definition at line 1550 of file utility.h.
Referenced by dump_tz().
#define DUMP_TZ_ZONE_ID_L "zone-id"
Definition at line 1549 of file utility.h.
#define DUMP_TZ_ZONE_ID_S 'd'
Definition at line 1548 of file utility.h.
Referenced by dump_tz().
#define DUMP_TZ_ZONES_L "list-zones"
Definition at line 1547 of file utility.h.
#define DUMP_TZ_ZONES_S 'z'
Definition at line 1546 of file utility.h.
Referenced by dump_tz().
#define DUMPLOCALE_ALPHABET_ALL_CASING "both"
Definition at line 1515 of file utility.h.
Referenced by dumplocale().
#define DUMPLOCALE_ALPHABET_L "alphabet"
Definition at line 1510 of file utility.h.
#define DUMPLOCALE_ALPHABET_LOWER_L "lower"
Definition at line 1512 of file utility.h.
Referenced by dumplocale().
#define DUMPLOCALE_ALPHABET_LOWER_S "l"
Definition at line 1511 of file utility.h.
Referenced by dumplocale().
#define DUMPLOCALE_ALPHABET_S 'a'
Definition at line 1509 of file utility.h.
Referenced by dumplocale().
#define DUMPLOCALE_ALPHABET_UPPER_L "upper"
Definition at line 1514 of file utility.h.
Referenced by dumplocale().
#define DUMPLOCALE_ALPHABET_UPPER_S "u"
Definition at line 1513 of file utility.h.
Referenced by dumplocale().
#define DUMPLOCALE_CALENDAR_L "calendar"
Definition at line 1506 of file utility.h.
#define DUMPLOCALE_CALENDAR_S 'd'
Definition at line 1505 of file utility.h.
Referenced by dumplocale().
#define DUMPLOCALE_COLLATION_L "codepoint-order"
Definition at line 1519 of file utility.h.
#define DUMPLOCALE_COLLATION_S 'c'
Definition at line 1518 of file utility.h.
Referenced by dumplocale().
#define DUMPLOCALE_CONSOLE_CONV_L "console-conversion"
Definition at line 1529 of file utility.h.
#define DUMPLOCALE_CONSOLE_CONV_S 'k'
Definition at line 1528 of file utility.h.
Referenced by dumplocale().
#define DUMPLOCALE_END_VALUE_L "end-value"
Definition at line 1525 of file utility.h.
#define DUMPLOCALE_END_VALUE_S 'e'
Definition at line 1524 of file utility.h.
Referenced by dumplocale().
#define DUMPLOCALE_IDENTIFIER_ALPHABET_L "identifier-alphabet"
Definition at line 1517 of file utility.h.
#define DUMPLOCALE_IDENTIFIER_ALPHABET_S 13000
Definition at line 1516 of file utility.h.
Referenced by dumplocale().
#define DUMPLOCALE_INPUT_PATH_L "input-file"
Definition at line 1504 of file utility.h.
#define DUMPLOCALE_INPUT_PATH_S 'i'
Definition at line 1503 of file utility.h.
Referenced by dumplocale().
#define DUMPLOCALE_NORMALIZATION_L "normalization"
Definition at line 1527 of file utility.h.
#define DUMPLOCALE_NORMALIZATION_S 'z'
Definition at line 1526 of file utility.h.
Referenced by dumplocale().
#define DUMPLOCALE_NUMBERING_L "numbering"
Definition at line 1508 of file utility.h.
#define DUMPLOCALE_NUMBERING_S 'n'
Definition at line 1507 of file utility.h.
Referenced by dumplocale().
#define DUMPLOCALE_START_VALUE_L "start-value"
Definition at line 1523 of file utility.h.
#define DUMPLOCALE_START_VALUE_S 's'
Definition at line 1522 of file utility.h.
Referenced by dumplocale().
#define DUMPLOCALE_WEIGHT_ORDER_L "weight-order"
Definition at line 1521 of file utility.h.
#define DUMPLOCALE_WEIGHT_ORDER_S 'w'
Definition at line 1520 of file utility.h.
Referenced by dumplocale().
#define GEN_TZ_INPUT_FOLDER_L "input-folder"
Definition at line 1539 of file utility.h.
#define GEN_TZ_INPUT_FOLDER_S 'i'
Definition at line 1538 of file utility.h.
Referenced by gen_tz().
#define GEN_TZ_MODE_L "gen-mode"
Definition at line 1541 of file utility.h.
#define GEN_TZ_MODE_S 'g'
Definition at line 1540 of file utility.h.
Referenced by gen_tz().
#define GENLOCALE_INPUT_PATH_L "input-ldml-file"
Definition at line 1498 of file utility.h.
#define GENLOCALE_INPUT_PATH_S 'i'
Definition at line 1497 of file utility.h.
Referenced by genlocale().
#define GENLOCALE_VERBOSE_L "verbose"
Definition at line 1500 of file utility.h.
#define GENLOCALE_VERBOSE_S 'v'
Definition at line 1499 of file utility.h.
Referenced by genlocale().
#define HIDDEN_CS_MODE_S 15000
Definition at line 959 of file utility.h.
Referenced by util_get_library_name().
#define INSTALL_FILE_PATH_L "file-path"
Definition at line 1140 of file utility.h.
#define INSTALL_FILE_PATH_S 'F'
Definition at line 1139 of file utility.h.
Referenced by installdb().
#define INSTALL_LOG_PATH_L "log-path"
Definition at line 1142 of file utility.h.
#define INSTALL_LOG_PATH_S 'L'
Definition at line 1141 of file utility.h.
Referenced by installdb().
#define INSTALL_SERVER_NAME_L "server-name"
Definition at line 1138 of file utility.h.
#define INSTALL_SERVER_NAME_S 11100
Definition at line 1137 of file utility.h.
Referenced by installdb().
#define KILLTRAN_DBA_PASSWORD_L "dba-password"
Definition at line 1225 of file utility.h.
#define KILLTRAN_DBA_PASSWORD_S 'p'
Definition at line 1224 of file utility.h.
Referenced by killtran(), tde(), and util_is_password_argument().
#define KILLTRAN_DISPLAY_INFORMATION_L "display-information"
Definition at line 1227 of file utility.h.
#define KILLTRAN_DISPLAY_INFORMATION_S 'd'
Definition at line 1226 of file utility.h.
Referenced by killtran().
#define KILLTRAN_DISPLAY_QUERY_INFO_L "query-exec-info"
Definition at line 1229 of file utility.h.
#define KILLTRAN_DISPLAY_QUERY_INFO_S 'q'
Definition at line 1228 of file utility.h.
Referenced by killtran().
#define KILLTRAN_FORCE_L "force"
Definition at line 1231 of file utility.h.
#define KILLTRAN_FORCE_S 'f'
Definition at line 1230 of file utility.h.
Referenced by killtran().
#define KILLTRAN_KILL_HOST_NAME_L "kill-host-name"
Definition at line 1219 of file utility.h.
#define KILLTRAN_KILL_HOST_NAME_S 11702
Definition at line 1218 of file utility.h.
Referenced by killtran().
#define KILLTRAN_KILL_PROGRAM_NAME_L "kill-program-name"
Definition at line 1221 of file utility.h.
#define KILLTRAN_KILL_PROGRAM_NAME_S 11703
Definition at line 1220 of file utility.h.
Referenced by killtran().
#define KILLTRAN_KILL_SQL_ID_L "kill-sql-id"
Definition at line 1223 of file utility.h.
#define KILLTRAN_KILL_SQL_ID_S 11704
Definition at line 1222 of file utility.h.
Referenced by killtran().
#define KILLTRAN_KILL_TRANSACTION_INDEX_L "kill-transaction-index"
Definition at line 1215 of file utility.h.
#define KILLTRAN_KILL_TRANSACTION_INDEX_S 'i'
Definition at line 1214 of file utility.h.
Referenced by killtran().
#define KILLTRAN_KILL_USER_NAME_L "kill-user-name"
Definition at line 1217 of file utility.h.
#define KILLTRAN_KILL_USER_NAME_S 11701
Definition at line 1216 of file utility.h.
Referenced by killtran().
#define LIB_UTIL_CS_NAME "libcubridcs.so"
Definition at line 1636 of file utility.h.
Referenced by main(), and util_get_library_name().
#define LIB_UTIL_SA_NAME "libcubridsa.so"
Definition at line 1637 of file utility.h.
Referenced by main(), print_admin_usage(), print_admin_version(), util_get_library_name(), utility_csql_print(), and utility_csql_usage().
#define LOAD_CHECK_ONLY_L "data-file-check-only"
Definition at line 1239 of file utility.h.
Referenced by loaddb_internal().
#define LOAD_CHECK_ONLY_S 11803
Definition at line 1238 of file utility.h.
Referenced by get_loaddb_args().
#define LOAD_COMPARE_STORAGE_ORDER_L "compare-storage-order"
Definition at line 1273 of file utility.h.
#define LOAD_COMPARE_STORAGE_ORDER_S 11820
Definition at line 1272 of file utility.h.
Referenced by get_loaddb_args().
#define LOAD_CS_FORCE_LOAD_L "force-load"
Definition at line 1275 of file utility.h.
#define LOAD_CS_FORCE_LOAD_S 11824
Definition at line 1274 of file utility.h.
Referenced by loaddb_internal().
#define LOAD_CS_MODE_L "CS-mode"
Definition at line 1269 of file utility.h.
#define LOAD_CS_MODE_S 'C'
Definition at line 1268 of file utility.h.
Referenced by loaddb_internal().
#define LOAD_DATA_FILE_L "data-file"
Definition at line 1259 of file utility.h.
#define LOAD_DATA_FILE_S 'd'
Definition at line 1258 of file utility.h.
Referenced by get_loaddb_args().
#define LOAD_ERROR_CONTROL_FILE_L "error-control-file"
Definition at line 1263 of file utility.h.
Referenced by loaddb_internal().
#define LOAD_ERROR_CONTROL_FILE_S 'e'
Definition at line 1262 of file utility.h.
Referenced by get_loaddb_args().
#define LOAD_ESTIMATED_SIZE_L "estimated-size"
Definition at line 1243 of file utility.h.
#define LOAD_ESTIMATED_SIZE_S 11805
Definition at line 1242 of file utility.h.
Referenced by get_loaddb_args().
#define LOAD_IGNORE_CLASS_L "ignore-class-file"
Definition at line 1265 of file utility.h.
#define LOAD_IGNORE_CLASS_S 11816
Definition at line 1264 of file utility.h.
Referenced by get_loaddb_args().
#define LOAD_IGNORE_LOGGING_L "no-logging"
Definition at line 1257 of file utility.h.
#define LOAD_IGNORE_LOGGING_S 11812
Definition at line 1256 of file utility.h.
Referenced by get_loaddb_args().
#define LOAD_INDEX_FILE_L "index-file"
Definition at line 1255 of file utility.h.
#define LOAD_INDEX_FILE_S 'i'
Definition at line 1254 of file utility.h.
Referenced by get_loaddb_args(), and loaddb_internal().
#define LOAD_LOAD_ONLY_L "load-only"
Definition at line 1241 of file utility.h.
Referenced by loaddb_internal().
#define LOAD_LOAD_ONLY_S 'l'
Definition at line 1240 of file utility.h.
Referenced by get_loaddb_args().
#define LOAD_NO_OID_L "no-oid"
Definition at line 1251 of file utility.h.
#define LOAD_NO_OID_S 11809
Definition at line 1250 of file utility.h.
Referenced by get_loaddb_args().
#define LOAD_NO_STATISTICS_L "no-statistics"
Definition at line 1247 of file utility.h.
#define LOAD_NO_STATISTICS_S 11807
Definition at line 1246 of file utility.h.
Referenced by get_loaddb_args().
#define LOAD_PASSWORD_L "password"
Definition at line 1237 of file utility.h.
#define LOAD_PASSWORD_S 'p'
Definition at line 1236 of file utility.h.
Referenced by get_loaddb_args(), and util_is_password_argument().
#define LOAD_PERIODIC_COMMIT_L "periodic-commit"
Definition at line 1249 of file utility.h.
#define LOAD_PERIODIC_COMMIT_S 'c'
Definition at line 1248 of file utility.h.
Referenced by get_loaddb_args().
#define LOAD_SA_MODE_L "SA-mode"
Definition at line 1267 of file utility.h.
#define LOAD_SA_MODE_S 'S'
Definition at line 1266 of file utility.h.
#define LOAD_SCHEMA_FILE_L "schema-file"
Definition at line 1253 of file utility.h.
#define LOAD_SCHEMA_FILE_S 's'
Definition at line 1252 of file utility.h.
Referenced by get_loaddb_args(), and loaddb_internal().
#define LOAD_TABLE_NAME_L "table"
Definition at line 1271 of file utility.h.
#define LOAD_TABLE_NAME_S 't'
Definition at line 1270 of file utility.h.
Referenced by get_loaddb_args().
#define LOAD_TRIGGER_FILE_L "trigger-file"
Definition at line 1261 of file utility.h.
Referenced by loaddb_internal().
#define LOAD_TRIGGER_FILE_S 11813
Definition at line 1260 of file utility.h.
Referenced by get_loaddb_args().
#define LOAD_USER_L "user"
Definition at line 1235 of file utility.h.
#define LOAD_USER_S 'u'
Definition at line 1234 of file utility.h.
Referenced by get_loaddb_args().
#define LOAD_VERBOSE_L "verbose"
Definition at line 1245 of file utility.h.
#define LOAD_VERBOSE_S 'v'
Definition at line 1244 of file utility.h.
Referenced by get_loaddb_args().
#define LOCK_OUTPUT_FILE_L "output-file"
Definition at line 1130 of file utility.h.
#define LOCK_OUTPUT_FILE_S 'o'
Definition at line 1129 of file utility.h.
Referenced by lockdb().
#define MASK_ADMIN 0x20
Definition at line 910 of file utility.h.
#define MASK_ALL 0xFF
Definition at line 905 of file utility.h.
#define MASK_BROKER 0x04
Definition at line 908 of file utility.h.
#define MASK_HEARTBEAT 0x40
Definition at line 911 of file utility.h.
#define MASK_JAVASP 0x80
Definition at line 912 of file utility.h.
#define MASK_MANAGER 0x08
Definition at line 909 of file utility.h.
#define MASK_SERVER 0x02
Definition at line 907 of file utility.h.
#define MASK_SERVICE 0x01
Definition at line 906 of file utility.h.
#define OPTIMIZE_CLASS_NAME_L "class-name"
Definition at line 1134 of file utility.h.
#define OPTIMIZE_CLASS_NAME_S 'n'
Definition at line 1133 of file utility.h.
Referenced by optimizedb().
#define OPTION_STRING_TABLE 10000
Definition at line 813 of file utility.h.
Referenced by acldb(), addvoldb(), alterdbhost(), applyinfo(), applylogdb(), backupdb(), changemode(), checkdb(), checksumdb(), compactdb(), copydb(), copylogdb(), createdb(), deletedb(), diagdb(), dumplocale(), gen_tz(), genlocale(), get_loaddb_args(), installdb(), killtran(), lockdb(), optimizedb(), paramdump(), patchdb(), plandump(), renamedb(), restoredb(), restoreslave(), spacedb(), statdump(), synccolldb(), tde(), tranlist(), unloaddb(), util_parse_string_table(), utility_get_option_string_table_size(), utility_get_option_string_value(), and vacuumdb().
#define PARAMDUMP_BOTH_L "both"
Definition at line 1440 of file utility.h.
#define PARAMDUMP_BOTH_S 'b'
Definition at line 1439 of file utility.h.
Referenced by paramdump().
#define PARAMDUMP_CS_MODE_L "CS-mode"
Definition at line 1444 of file utility.h.
#define PARAMDUMP_CS_MODE_S 'C'
Definition at line 1443 of file utility.h.
#define PARAMDUMP_OUTPUT_FILE_L "output-file"
Definition at line 1438 of file utility.h.
#define PARAMDUMP_OUTPUT_FILE_S 'o'
Definition at line 1437 of file utility.h.
Referenced by paramdump().
#define PARAMDUMP_SA_MODE_L "SA-mode"
Definition at line 1442 of file utility.h.
#define PARAMDUMP_SA_MODE_S 'S'
Definition at line 1441 of file utility.h.
#define PATCH_RECREATE_LOG_L "recreate-log"
Definition at line 1156 of file utility.h.
#define PATCH_RECREATE_LOG_S 'r'
Definition at line 1155 of file utility.h.
Referenced by patchdb().
#define PLANDUMP_DROP_L "drop"
Definition at line 1192 of file utility.h.
#define PLANDUMP_DROP_S 'd'
Definition at line 1191 of file utility.h.
Referenced by plandump().
#define PLANDUMP_OUTPUT_FILE_L "output-file"
Definition at line 1194 of file utility.h.
#define PLANDUMP_OUTPUT_FILE_S 'o'
Definition at line 1193 of file utility.h.
Referenced by plandump().
#define PRINT_BROKER_NAME "cubrid broker"
Definition at line 849 of file utility.h.
Referenced by process_broker().
#define PRINT_CMD_ACL "acl"
Definition at line 867 of file utility.h.
Referenced by command_string().
#define PRINT_CMD_APPLYLOGDB "applylogdb"
Definition at line 869 of file utility.h.
Referenced by command_string().
#define PRINT_CMD_BROKER "broker"
Definition at line 856 of file utility.h.
Referenced by process_broker().
#define PRINT_CMD_COPYLOGDB "copylogdb"
Definition at line 868 of file utility.h.
Referenced by command_string().
#define PRINT_CMD_DEREG "deregister"
Definition at line 864 of file utility.h.
Referenced by command_string(), and process_heartbeat_deregister().
#define PRINT_CMD_GETID "getid"
Definition at line 870 of file utility.h.
Referenced by process_broker().
#define PRINT_CMD_JAVASP "javasp"
Definition at line 859 of file utility.h.
Referenced by process_javasp_start(), and process_javasp_stop().
#define PRINT_CMD_LIST "list"
Definition at line 865 of file utility.h.
Referenced by command_string().
#define PRINT_CMD_MANAGER "manager"
Definition at line 857 of file utility.h.
Referenced by process_manager().
#define PRINT_CMD_RELOAD "reload"
Definition at line 866 of file utility.h.
Referenced by command_string(), and process_heartbeat_reload().
#define PRINT_CMD_REPLICATION "replication"
Definition at line 872 of file utility.h.
Referenced by command_string(), and process_heartbeat_replication().
#define PRINT_CMD_SERVER "server"
Definition at line 858 of file utility.h.
Referenced by process_server().
#define PRINT_CMD_SERVICE "service"
Definition at line 855 of file utility.h.
Referenced by process_service().
#define PRINT_CMD_START "start"
Definition at line 861 of file utility.h.
Referenced by command_string(), process_broker(), process_heartbeat_start(), process_javasp_start(), process_master(), process_server(), process_service(), us_hb_applylogdb_start(), us_hb_copylogdb_start(), and us_hb_process_start().
#define PRINT_CMD_STATUS "status"
Definition at line 863 of file utility.h.
Referenced by command_string(), process_broker(), process_heartbeat_status(), process_javasp_status(), process_server(), process_service(), and us_hb_status_get_options().
#define PRINT_CMD_STOP "stop"
Definition at line 862 of file utility.h.
Referenced by command_string(), process_broker(), process_heartbeat_stop(), process_javasp_stop(), process_master(), process_server(), process_service(), us_hb_applylogdb_stop(), us_hb_copylogdb_stop(), us_hb_process_stop(), and us_hb_stop_get_options().
#define PRINT_CMD_TEST "test"
Definition at line 871 of file utility.h.
Referenced by command_string(), and process_broker().
#define PRINT_HA_PROCS_NAME "HA processes"
Definition at line 853 of file utility.h.
Referenced by us_hb_process_start(), and us_hb_process_stop().
#define PRINT_HEARTBEAT_NAME "cubrid heartbeat"
Definition at line 851 of file utility.h.
Referenced by process_heartbeat(), process_heartbeat_deregister(), process_heartbeat_reload(), process_heartbeat_replication(), process_heartbeat_start(), process_heartbeat_status(), process_heartbeat_stop(), process_heartbeat_util(), us_hb_status_get_options(), us_hb_stop_get_options(), and us_hb_util_get_options().
#define PRINT_JAVASP_NAME "cubrid javasp"
Definition at line 852 of file utility.h.
Referenced by process_javasp_start(), process_javasp_status(), and process_javasp_stop().
#define PRINT_MANAGER_NAME "cubrid manager server"
Definition at line 850 of file utility.h.
Referenced by process_manager().
#define PRINT_MASTER_NAME "cubrid master"
Definition at line 847 of file utility.h.
Referenced by process_heartbeat_deregister(), process_heartbeat_reload(), process_heartbeat_replication(), process_heartbeat_status(), process_heartbeat_stop(), process_master(), process_server(), and process_service().
#define PRINT_RESULT_FAIL "fail"
Definition at line 875 of file utility.h.
Referenced by print_result(), and process_master().
#define PRINT_RESULT_SUCCESS "success"
Definition at line 874 of file utility.h.
Referenced by print_result().
#define PRINT_SERVER_NAME "cubrid server"
Definition at line 848 of file utility.h.
Referenced by process_server(), us_hb_server_start(), and us_hb_server_stop().
#define PRINT_SERVICE_NAME "cubrid service"
Definition at line 846 of file utility.h.
Referenced by process_service().
#define PROPERTY_OFF "off"
Definition at line 843 of file utility.h.
Referenced by load_properties().
#define PROPERTY_ON "on"
Definition at line 842 of file utility.h.
Referenced by check_all_services_status(), load_properties(), and process_service().
#define RENAME_CONTROL_FILE_L "control-file"
Definition at line 1005 of file utility.h.
#define RENAME_CONTROL_FILE_S 'i'
Definition at line 1004 of file utility.h.
Referenced by renamedb().
#define RENAME_DELETE_BACKUP_L "delete-backup"
Definition at line 1007 of file utility.h.
#define RENAME_DELETE_BACKUP_S 'd'
Definition at line 1006 of file utility.h.
Referenced by renamedb().
#define RENAME_EXTENTED_VOLUME_PATH_L "extended-volume-path"
Definition at line 1003 of file utility.h.
#define RENAME_EXTENTED_VOLUME_PATH_S 'E'
Definition at line 1002 of file utility.h.
Referenced by renamedb().
#define RESTORE_BACKUP_FILE_PATH_L "backup-file-path"
Definition at line 1068 of file utility.h.
#define RESTORE_BACKUP_FILE_PATH_S 'B'
Definition at line 1067 of file utility.h.
Referenced by restoredb().
#define RESTORE_KEYS_FILE_PATH_L "keys-file-path"
Definition at line 1078 of file utility.h.
#define RESTORE_KEYS_FILE_PATH_S 'k'
Definition at line 1077 of file utility.h.
Referenced by restoredb(), and restoreslave().
#define RESTORE_LEVEL_L "level"
Definition at line 1070 of file utility.h.
#define RESTORE_LEVEL_S 'l'
Definition at line 1069 of file utility.h.
Referenced by restoredb().
#define RESTORE_LIST_L "list"
Definition at line 1066 of file utility.h.
#define RESTORE_LIST_S 10601
Definition at line 1065 of file utility.h.
Referenced by restoredb().
#define RESTORE_OUTPUT_FILE_L "output-file"
Definition at line 1074 of file utility.h.
#define RESTORE_OUTPUT_FILE_S 'o'
Definition at line 1073 of file utility.h.
Referenced by restoredb().
#define RESTORE_PARTIAL_RECOVERY_L "partial-recovery"
Definition at line 1072 of file utility.h.
#define RESTORE_PARTIAL_RECOVERY_S 'p'
Definition at line 1071 of file utility.h.
Referenced by restoredb().
#define RESTORE_UP_TO_DATE_L "up-to-date"
Definition at line 1064 of file utility.h.
#define RESTORE_UP_TO_DATE_S 'd'
Definition at line 1063 of file utility.h.
Referenced by restoredb().
#define RESTORE_USE_DATABASE_LOCATION_PATH_L "use-database-location-path"
Definition at line 1076 of file utility.h.
#define RESTORE_USE_DATABASE_LOCATION_PATH_S 'u'
Definition at line 1075 of file utility.h.
Referenced by restoredb().
#define RESTORESLAVE_BACKUP_FILE_PATH_L "backup-file-path"
Definition at line 1566 of file utility.h.
#define RESTORESLAVE_BACKUP_FILE_PATH_S 'B'
Definition at line 1565 of file utility.h.
Referenced by restoreslave().
#define RESTORESLAVE_KEYS_FILE_PATH_L "keys-file-path"
Definition at line 1572 of file utility.h.
#define RESTORESLAVE_KEYS_FILE_PATH_S 'k'
Definition at line 1571 of file utility.h.
#define RESTORESLAVE_LIST_L "list"
Definition at line 1564 of file utility.h.
#define RESTORESLAVE_LIST_S 10601
Definition at line 1563 of file utility.h.
Referenced by restoreslave().
#define RESTORESLAVE_MASTER_HOST_NAME_L "master-host-name"
Definition at line 1562 of file utility.h.
#define RESTORESLAVE_MASTER_HOST_NAME_S 'm'
Definition at line 1561 of file utility.h.
Referenced by restoreslave().
#define RESTORESLAVE_OUTPUT_FILE_L "output-file"
Definition at line 1568 of file utility.h.
#define RESTORESLAVE_OUTPUT_FILE_S 'o'
Definition at line 1567 of file utility.h.
Referenced by restoreslave().
#define RESTORESLAVE_SOURCE_STATE_L "source-state"
Definition at line 1560 of file utility.h.
#define RESTORESLAVE_SOURCE_STATE_S 's'
Definition at line 1559 of file utility.h.
Referenced by restoreslave().
#define RESTORESLAVE_USE_DATABASE_LOCATION_PATH_L "use-database-location-path"
Definition at line 1570 of file utility.h.
#define RESTORESLAVE_USE_DATABASE_LOCATION_PATH_S 'u'
Definition at line 1569 of file utility.h.
Referenced by restoreslave().
#define SPACE_CS_MODE_L "CS-mode"
Definition at line 1120 of file utility.h.
#define SPACE_CS_MODE_S 'C'
Definition at line 1119 of file utility.h.
#define SPACE_OUTPUT_FILE_L "output-file"
Definition at line 1116 of file utility.h.
#define SPACE_OUTPUT_FILE_S 'o'
Definition at line 1115 of file utility.h.
Referenced by spacedb().
#define SPACE_PURPOSE_L "purpose"
Definition at line 1126 of file utility.h.
#define SPACE_PURPOSE_S 'p'
Definition at line 1125 of file utility.h.
Referenced by spacedb().
#define SPACE_SA_MODE_L "SA-mode"
Definition at line 1118 of file utility.h.
#define SPACE_SA_MODE_S 'S'
Definition at line 1117 of file utility.h.
#define SPACE_SIZE_UNIT_L "size-unit"
Definition at line 1122 of file utility.h.
#define SPACE_SIZE_UNIT_S 10803
Definition at line 1121 of file utility.h.
Referenced by spacedb().
#define SPACE_SUMMARIZE_L "summarize"
Definition at line 1124 of file utility.h.
#define SPACE_SUMMARIZE_S 's'
Definition at line 1123 of file utility.h.
Referenced by spacedb().
#define STATDUMP_CUMULATIVE_L "cumulative"
Definition at line 1452 of file utility.h.
#define STATDUMP_CUMULATIVE_S 'c'
Definition at line 1451 of file utility.h.
Referenced by statdump().
#define STATDUMP_INTERVAL_L "interval"
Definition at line 1450 of file utility.h.
#define STATDUMP_INTERVAL_S 'i'
Definition at line 1449 of file utility.h.
Referenced by statdump().
#define STATDUMP_OUTPUT_FILE_L "output-file"
Definition at line 1448 of file utility.h.
#define STATDUMP_OUTPUT_FILE_S 'o'
Definition at line 1447 of file utility.h.
Referenced by statdump().
#define STATDUMP_SUBSTR_L "substr"
Definition at line 1454 of file utility.h.
#define STATDUMP_SUBSTR_S 's'
Definition at line 1453 of file utility.h.
Referenced by statdump().
#define SYNCCOLL_CHECK_L "check-only"
Definition at line 1533 of file utility.h.
#define SYNCCOLL_CHECK_S 'c'
Definition at line 1532 of file utility.h.
Referenced by synccolldb().
#define SYNCCOLL_FORCESYNC_L "force-only"
Definition at line 1535 of file utility.h.
#define SYNCCOLL_FORCESYNC_S 'f'
Definition at line 1534 of file utility.h.
Referenced by synccolldb().
#define TDE_CHANGE_KEY_L "change-key"
Definition at line 1618 of file utility.h.
#define TDE_CHANGE_KEY_S 'c'
Definition at line 1617 of file utility.h.
Referenced by tde().
#define TDE_CS_MODE_L "CS-mode"
Definition at line 1616 of file utility.h.
#define TDE_CS_MODE_S HIDDEN_CS_MODE_S
Definition at line 1615 of file utility.h.
#define TDE_DBA_PASSWORD_L "dba-password"
Definition at line 1622 of file utility.h.
#define TDE_DBA_PASSWORD_S 'p'
Definition at line 1621 of file utility.h.
Referenced by util_is_password_argument().
#define TDE_DELETE_KEY_L "delete-key"
Definition at line 1620 of file utility.h.
#define TDE_DELETE_KEY_S 'd'
Definition at line 1619 of file utility.h.
Referenced by tde().
#define TDE_GENERATE_KEY_L "generate-new-key"
Definition at line 1608 of file utility.h.
#define TDE_GENERATE_KEY_S 'n'
Definition at line 1607 of file utility.h.
Referenced by tde().
#define TDE_PRINT_KEY_VALUE_L "print-value"
Definition at line 1612 of file utility.h.
#define TDE_PRINT_KEY_VALUE_S 14000
Definition at line 1611 of file utility.h.
Referenced by tde().
#define TDE_SA_MODE_L "SA-mode"
Definition at line 1614 of file utility.h.
#define TDE_SA_MODE_S 'S'
Definition at line 1613 of file utility.h.
#define TDE_SHOW_KEYS_L "show-keys"
Definition at line 1610 of file utility.h.
#define TDE_SHOW_KEYS_S 's'
Definition at line 1609 of file utility.h.
Referenced by tde().
#define TRANLIST_FULL_SQL_L "full"
Definition at line 1210 of file utility.h.
#define TRANLIST_FULL_SQL_S 'f'
Definition at line 1209 of file utility.h.
Referenced by tranlist().
#define TRANLIST_REVERSE_L "reverse"
Definition at line 1208 of file utility.h.
#define TRANLIST_REVERSE_S 'r'
Definition at line 1207 of file utility.h.
Referenced by tranlist().
#define TRANLIST_SORT_KEY_L "sort-key"
Definition at line 1206 of file utility.h.
#define TRANLIST_SORT_KEY_S 'k'
Definition at line 1205 of file utility.h.
Referenced by tranlist().
#define TRANLIST_SUMMARY_L "summary"
Definition at line 1204 of file utility.h.
#define TRANLIST_SUMMARY_S 's'
Definition at line 1203 of file utility.h.
Referenced by tranlist().
#define UNLOAD_CACHED_PAGES_L "cached-pages"
Definition at line 1289 of file utility.h.
#define UNLOAD_CACHED_PAGES_S 11905
Definition at line 1288 of file utility.h.
Referenced by unloaddb().
#define UNLOAD_CS_MODE_L "CS-mode"
Definition at line 1307 of file utility.h.
#define UNLOAD_CS_MODE_S 'C'
Definition at line 1306 of file utility.h.
#define UNLOAD_DATA_ONLY_L "data-only"
Definition at line 1295 of file utility.h.
#define UNLOAD_DATA_ONLY_S 'd'
Definition at line 1294 of file utility.h.
Referenced by unloaddb().
#define UNLOAD_DATAFILE_PER_CLASS_L "datafile-per-class"
Definition at line 1309 of file utility.h.
#define UNLOAD_DATAFILE_PER_CLASS_S 11915
Definition at line 1308 of file utility.h.
Referenced by unloaddb().
#define UNLOAD_ESTIMATED_SIZE_L "estimated-size"
Definition at line 1287 of file utility.h.
#define UNLOAD_ESTIMATED_SIZE_S 11904
Definition at line 1286 of file utility.h.
Referenced by unloaddb().
#define UNLOAD_HASH_FILE_L "hash-file"
Definition at line 1299 of file utility.h.
#define UNLOAD_HASH_FILE_S 11910
Definition at line 1298 of file utility.h.
Referenced by unloaddb().
#define UNLOAD_INCLUDE_REFERENCE_L "include-reference"
Definition at line 1281 of file utility.h.
#define UNLOAD_INCLUDE_REFERENCE_S 11901
Definition at line 1280 of file utility.h.
Referenced by unloaddb().
#define UNLOAD_INPUT_CLASS_FILE_L "input-class-file"
Definition at line 1279 of file utility.h.
#define UNLOAD_INPUT_CLASS_FILE_S 'i'
Definition at line 1278 of file utility.h.
Referenced by unloaddb().
#define UNLOAD_INPUT_CLASS_ONLY_L "input-class-only"
Definition at line 1283 of file utility.h.
#define UNLOAD_INPUT_CLASS_ONLY_S 11902
Definition at line 1282 of file utility.h.
Referenced by unloaddb().
#define UNLOAD_KEEP_STORAGE_ORDER_L "keep-storage-order"
Definition at line 1315 of file utility.h.
#define UNLOAD_KEEP_STORAGE_ORDER_S 11918
Definition at line 1314 of file utility.h.
Referenced by unloaddb().
#define UNLOAD_LO_COUNT_L "lo-count"
Definition at line 1285 of file utility.h.
#define UNLOAD_LO_COUNT_S 11903
Definition at line 1284 of file utility.h.
Referenced by unloaddb().
#define UNLOAD_OUTPUT_PATH_L "output-path"
Definition at line 1291 of file utility.h.
#define UNLOAD_OUTPUT_PATH_S 'O'
Definition at line 1290 of file utility.h.
Referenced by unloaddb().
#define UNLOAD_OUTPUT_PREFIX_L "output-prefix"
Definition at line 1297 of file utility.h.
#define UNLOAD_OUTPUT_PREFIX_S 11909
Definition at line 1296 of file utility.h.
Referenced by unloaddb().
#define UNLOAD_PASSWORD_L "password"
Definition at line 1313 of file utility.h.
#define UNLOAD_PASSWORD_S 'p'
Definition at line 1312 of file utility.h.
Referenced by unloaddb(), and util_is_password_argument().
#define UNLOAD_SA_MODE_L "SA-mode"
Definition at line 1305 of file utility.h.
#define UNLOAD_SA_MODE_S 'S'
Definition at line 1304 of file utility.h.
#define UNLOAD_SCHEMA_ONLY_L "schema-only"
Definition at line 1293 of file utility.h.
#define UNLOAD_SCHEMA_ONLY_S 's'
Definition at line 1292 of file utility.h.
Referenced by unloaddb().
#define UNLOAD_USE_DELIMITER_L "use-delimiter"
Definition at line 1303 of file utility.h.
#define UNLOAD_USE_DELIMITER_S 11912
Definition at line 1302 of file utility.h.
Referenced by unloaddb().
#define UNLOAD_USER_L "user"
Definition at line 1311 of file utility.h.
#define UNLOAD_USER_S 'u'
Definition at line 1310 of file utility.h.
Referenced by unloaddb().
#define UNLOAD_VERBOSE_L "verbose"
Definition at line 1301 of file utility.h.
#define UNLOAD_VERBOSE_S 'v'
Definition at line 1300 of file utility.h.
Referenced by unloaddb().
#define UTIL_ADMIN_NAME "cub_admin" UTIL_EXE_EXT
Definition at line 832 of file utility.h.
Referenced by main(), process_admin(), process_server(), us_hb_applylogdb_start(), us_hb_applylogdb_stop(), us_hb_copylogdb_start(), and us_hb_copylogdb_stop().
#define UTIL_APPLYLOGDB "applylogdb" UTIL_EXE_EXT
Definition at line 839 of file utility.h.
Referenced by us_hb_applylogdb_start(), and us_hb_applylogdb_stop().
#define UTIL_BROKER_NAME "cubrid_broker" UTIL_EXE_EXT
Definition at line 828 of file utility.h.
Referenced by process_broker().
#define UTIL_COMMDB_NAME "cub_commdb" UTIL_EXE_EXT
Definition at line 826 of file utility.h.
Referenced by check_server(), ha_is_registered(), main(), process_heartbeat_deregister(), process_heartbeat_reload(), process_heartbeat_replication(), process_heartbeat_start(), process_heartbeat_status(), process_master(), process_server(), us_hb_applylogdb_start(), us_hb_applylogdb_stop(), us_hb_copylogdb_start(), us_hb_copylogdb_stop(), and us_hb_deactivate().
#define UTIL_COPYLOGDB "copylogdb" UTIL_EXE_EXT
Definition at line 838 of file utility.h.
Referenced by us_hb_copylogdb_start(), and us_hb_copylogdb_stop().
#define UTIL_CSQL_NAME "csql" UTIL_EXE_EXT
Definition at line 834 of file utility.h.
Referenced by csql_do_session_cmd(), main(), and utility_csql_usage().
#define UTIL_CUB_MANAGER_NAME "cub_manager" UTIL_EXE_EXT
Definition at line 831 of file utility.h.
Referenced by is_manager_running(), and process_manager().
#define UTIL_CUBRID "cubrid" UTIL_EXE_EXT
Definition at line 837 of file utility.h.
Referenced by main().
#define UTIL_CUBRID_NAME "cub_server" UTIL_EXE_EXT
Definition at line 827 of file utility.h.
Referenced by process_server().
#define UTIL_CUBRID_REL_NAME "cubrid_rel" UTIL_EXE_EXT
Definition at line 835 of file utility.h.
#define UTIL_EXE_EXT ""
Definition at line 818 of file utility.h.
#define UTIL_JAVASP_NAME "cub_javasp" UTIL_EXE_EXT
Definition at line 840 of file utility.h.
Referenced by is_javasp_running(), process_javasp_start(), process_javasp_status(), and process_javasp_stop().
#define UTIL_MASTER_NAME "cub_master" UTIL_EXE_EXT
Definition at line 825 of file utility.h.
Referenced by process_master().
#define UTIL_MONITOR_NAME "broker_monitor" UTIL_EXE_EXT
Definition at line 829 of file utility.h.
Referenced by is_broker_running(), and process_broker().
#define UTIL_OLD_COMMDB_NAME "commdb" UTIL_EXE_EXT
Definition at line 836 of file utility.h.
Referenced by main().
#define UTIL_OPTION_ACLDB "acldb"
Definition at line 948 of file utility.h.
Referenced by process_server().
#define UTIL_OPTION_ADDVOLDB "addvoldb"
Definition at line 921 of file utility.h.
#define UTIL_OPTION_ALTERDBHOST "alterdbhost"
Definition at line 934 of file utility.h.
#define UTIL_OPTION_APPLYINFO "applyinfo"
Definition at line 947 of file utility.h.
#define UTIL_OPTION_APPLYLOGDB "applylogdb"
Definition at line 945 of file utility.h.
#define UTIL_OPTION_BACKUPDB "backupdb"
Definition at line 919 of file utility.h.
#define UTIL_OPTION_CHANGEMODE "changemode"
Definition at line 943 of file utility.h.
#define UTIL_OPTION_CHECKDB "checkdb"
Definition at line 933 of file utility.h.
#define UTIL_OPTION_CHECKSUMDB "checksumdb"
Definition at line 956 of file utility.h.
#define UTIL_OPTION_COMPACTDB "compactdb"
Definition at line 940 of file utility.h.
#define UTIL_OPTION_COPYDB "copydb"
Definition at line 917 of file utility.h.
#define UTIL_OPTION_COPYLOGDB "copylogdb"
Definition at line 944 of file utility.h.
#define UTIL_OPTION_CREATEDB "createdb"
Definition at line 915 of file utility.h.
#define UTIL_OPTION_DELETEDB "deletedb"
Definition at line 918 of file utility.h.
#define UTIL_OPTION_DIAGDB "diagdb"
Definition at line 931 of file utility.h.
#define UTIL_OPTION_DUMP_LOCALE "dumplocale"
Definition at line 950 of file utility.h.
#define UTIL_OPTION_DUMP_TZ "dump_tz"
Definition at line 953 of file utility.h.
#define UTIL_OPTION_ESTIMATE_DATA "estimate_data"
Definition at line 936 of file utility.h.
#define UTIL_OPTION_ESTIMATE_INDEX "estimate_index"
Definition at line 937 of file utility.h.
#define UTIL_OPTION_GEN_TZ "gen_tz"
Definition at line 952 of file utility.h.
#define UTIL_OPTION_GENERATE_LOCALE "genlocale"
Definition at line 949 of file utility.h.
#define UTIL_OPTION_INSTALLDB "installdb"
Definition at line 930 of file utility.h.
#define UTIL_OPTION_KILLTRAN "killtran"
Definition at line 928 of file utility.h.
#define UTIL_OPTION_LOADDB "loaddb"
Definition at line 938 of file utility.h.
#define UTIL_OPTION_LOCKDB "lockdb"
Definition at line 926 of file utility.h.
#define UTIL_OPTION_LOGFILEDUMP "logfiledump"
Definition at line 946 of file utility.h.
#define UTIL_OPTION_OPTIMIZEDB "optimizedb"
Definition at line 929 of file utility.h.
#define UTIL_OPTION_PARAMDUMP "paramdump"
Definition at line 941 of file utility.h.
#define UTIL_OPTION_PATCHDB "emergency_patchlog"
Definition at line 932 of file utility.h.
#define UTIL_OPTION_PLANDUMP "plandump"
Definition at line 935 of file utility.h.
#define UTIL_OPTION_RENAMEDB "renamedb"
Definition at line 916 of file utility.h.
#define UTIL_OPTION_RESTOREDB "restoredb"
Definition at line 920 of file utility.h.
#define UTIL_OPTION_RESTORESLAVE "restoreslave"
Definition at line 954 of file utility.h.
#define UTIL_OPTION_SPACEDB "spacedb"
Definition at line 925 of file utility.h.
#define UTIL_OPTION_STATDUMP "statdump"
Definition at line 942 of file utility.h.
#define UTIL_OPTION_SYNCCOLLDB "synccolldb"
Definition at line 951 of file utility.h.
#define UTIL_OPTION_TDE "tde"
Definition at line 957 of file utility.h.
#define UTIL_OPTION_TRANLIST "tranlist"
Definition at line 927 of file utility.h.
#define UTIL_OPTION_UNLOADDB "unloaddb"
Definition at line 939 of file utility.h.
#define UTIL_OPTION_VACUUMDB "vacuumdb"
Definition at line 955 of file utility.h.
#define UTIL_SQLX_NAME "sqlx" UTIL_EXE_EXT
Definition at line 833 of file utility.h.
Referenced by main().
#define UTIL_TESTER_NAME "broker_tester" UTIL_EXE_EXT
Definition at line 830 of file utility.h.
Referenced by process_broker().
#define UTILITY_ADMIN_USAGE_FUNC_NAME "util_admin_usage"
Definition at line 1642 of file utility.h.
Referenced by print_admin_usage().
#define UTILITY_ADMIN_VERSION_FUNC_NAME "util_admin_version"
Definition at line 1643 of file utility.h.
Referenced by print_admin_version().
#define UTILITY_GENERIC_MSG_FUNC_NAME "utility_get_generic_message"
Definition at line 1640 of file utility.h.
Referenced by utility_csql_print().
#define UTILITY_INIT_FUNC_NAME "utility_initialize"
Definition at line 1641 of file utility.h.
Referenced by utility_load_library().
#define VACUUM_CS_MODE_L "CS-mode"
Definition at line 1578 of file utility.h.
#define VACUUM_CS_MODE_S 'C'
Definition at line 1577 of file utility.h.
#define VACUUM_DUMP_L "dump"
Definition at line 1580 of file utility.h.
#define VACUUM_DUMP_S 10700
Definition at line 1579 of file utility.h.
Referenced by vacuumdb().
#define VACUUM_OUTPUT_FILE_L "output-file"
Definition at line 1582 of file utility.h.
#define VACUUM_OUTPUT_FILE_S 'o'
Definition at line 1581 of file utility.h.
Referenced by vacuumdb().
#define VACUUM_SA_MODE_L "SA-mode"
Definition at line 1576 of file utility.h.
#define VACUUM_SA_MODE_S 'S'
Definition at line 1575 of file utility.h.
#define VERSION_L "version"
Definition at line 1556 of file utility.h.
Referenced by main().
#define VERSION_S 20000
Definition at line 1555 of file utility.h.
Referenced by main().
Typedef Documentation
typedef void* DSO_HANDLE
Definition at line 706 of file utility.h.
typedef struct _ha_config HA_CONF
typedef struct _node_config HA_NODE_CONF
typedef int(* UTILITY_FUNCTION) (UTIL_FUNCTION_ARG *)
Definition at line 1704 of file utility.h.
typedef int(* UTILITY_INIT_FUNC) (void)
Definition at line 1644 of file utility.h.
Enumeration Type Documentation
enum MSGCAT_ACLDB_MSG
Enumerator
ACLDB_MSG_NOT_IN_STANDALONE
ACLDB_MSG_USAGE
Definition at line 592 of file utility.h.
enum MSGCAT_ADDVOLDB_MSG
Enumerator
ADDVOLDB_MSG_BAD_NPAGES
ADDVOLDB_MSG_BAD_PURPOSE
ADDVOLDB_INVALID_MAX_WRITESIZE_IN_SEC
ADDVOLDB_MSG_USAGE
Definition at line 227 of file utility.h.
enum MSGCAT_ALTERDBHOST_MSG
Enumerator
ALTERDBHOST_MSG_USAGE
Definition at line 306 of file utility.h.
enum MSGCAT_APPLYINFO_MSG
Enumerator
APPLYINFO_MSG_DBA_PASSWORD
APPLYINFO_MSG_NOT_HA_MODE
APPLYINFO_MSG_HA_NOT_SUPPORT
APPLYINFO_MSG_NOT_IN_STANDALONE
APPLYINFO_MSG_USAGE
Definition at line 582 of file utility.h.
enum MSGCAT_APPLYLOGDB_MSG
Enumerator
APPLYLOGDB_MSG_DBA_PASSWORD
APPLYLOGDB_MSG_NOT_HA_MODE
APPLYLOGDB_MSG_HA_NOT_SUPPORT
APPLYLOGDB_MSG_NOT_IN_STANDALONE
APPLYLOGDB_MSG_USAGE
Definition at line 564 of file utility.h.
enum MSGCAT_BACKUPDB_MSG
Enumerator
BACKUPDB_INVALID_THREAD_NUM_OPT
BACKUPDB_INVALID_PATH
BACKUPDB_USING_SEPARATE_KEYS
BACKUPDB_NOT_USING_SEPARATE_KEYS
BACKUPDB_FIFO_KEYS_NOT_SUPPORTED
BACKUPDB_MSG_USAGE
Definition at line 136 of file utility.h.
enum MSGCAT_CHANGEMODE_MSG
Enumerator
CHANGEMODE_MSG_BAD_MODE
CHANGEMODE_MSG_CANNOT_CHANGE
CHANGEMODE_MSG_DBA_PASSWORD
CHANGEMODE_MSG_SERVER_MODE
CHANGEMODE_MSG_SERVER_MODE_CHANGED
CHANGEMODE_MSG_NOT_HA_MODE
CHANGEMODE_MSG_HA_NOT_SUPPORT
CHANGEMODE_MSG_NOT_IN_STANDALONE
CHANGEMODE_MSG_USAGE
Definition at line 539 of file utility.h.
enum MSGCAT_CHECKDB_MSG
Enumerator
CHECKDB_MSG_INCONSISTENT
CHECKDB_MSG_NO_SUCH_CLASS
CHECKDB_MSG_NO_SUCH_INDEX
CHECKDB_MSG_USAGE
Definition at line 236 of file utility.h.
enum MSGCAT_CHECKSUMDB_MSG
Enumerator
CHECKSUMDB_MSG_INVALID_INPUT_FILE
CHECKSUMDB_MSG_MUST_RUN_ON_ACTIVE
CHECKSUMDB_MSG_HA_NOT_SUPPORT
CHECKSUMDB_MSG_NOT_IN_STANDALONE
CHECKSUMDB_MSG_USAGE
Definition at line 684 of file utility.h.
enum MSGCAT_COMMDB_MSG
Enumerator
COMMDB_STRING1
COMMDB_STRING2
COMMDB_STRING3
COMMDB_STRING4
COMMDB_STRING5
COMMDB_STRING6
COMMDB_STRING7
COMMDB_STRING8
COMMDB_STRING9
COMMDB_STRING10
COMMDB_STRING11
COMMDB_STRING12
COMMDB_STRING13
COMMDB_STRING14
COMMDB_INVALID_IMMEDIATELY_OPTION
Definition at line 161 of file utility.h.
enum MSGCAT_COMPACTDB_MSG
Enumerator
COMPACTDB_MSG_PASS1
COMPACTDB_MSG_PROCESSED
COMPACTDB_MSG_PASS2
COMPACTDB_MSG_CLASS
COMPACTDB_MSG_OID
COMPACTDB_MSG_INSTANCES
COMPACTDB_MSG_UPDATING
COMPACTDB_MSG_REFOID
COMPACTDB_MSG_CANT_TRANSFORM
COMPACTDB_MSG_NO_HEAP
COMPACTDB_MSG_CANT_UPDATE
COMPACTDB_MSG_FAILED
COMPACTDB_MSG_ALREADY_STARTED
COMPACTDB_MSG_OUT_OF_RANGE_PAGES
COMPACTDB_MSG_OUT_OF_RANGE_INSTANCE_LOCK_TIMEOUT
COMPACTDB_MSG_TOTAL_OBJECTS
COMPACTDB_MSG_FAILED_OBJECTS
COMPACTDB_MSG_MODIFIED_OBJECTS
COMPACTDB_MSG_BIG_OBJECTS
COMPACTDB_MSG_REPR_DELETED
COMPACTDB_MSG_REPR_CANT_DELETE
COMPACTDB_MSG_ISOLATION_LEVEL_FAILURE
COMPACTDB_MSG_FAILURE
COMPACTDB_MSG_OUT_OF_RANGE_CLASS_LOCK_TIMEOUT
COMPACTDB_MSG_LOCKED_CLASS
COMPACTDB_MSG_INVALID_CLASS
COMPACTDB_MSG_PROCESS_CLASS_ERROR
COMPACTDB_MSG_NOTHING_TO_PROCESS
COMPACTDB_MSG_INVALID_PARAMETERS
COMPACTDB_MSG_UNKNOWN_CLASS_NAME
COMPACTDB_MSG_RECLAIMED
COMPACTDB_MSG_RECLAIM_SKIPPED
COMPACTDB_MSG_RECLAIM_ERROR
COMPACTDB_MSG_PASS3
COMPACTDB_MSG_HEAP_COMPACT_FAILED
COMPACTDB_MSG_HEAP_COMPACT_SUCCEEDED
Definition at line 385 of file utility.h.
enum MSGCAT_COPYDB_MSG
Enumerator
COPYDB_MSG_IDENTICAL
COPYDB_VOLEXT_PATH_INVALID
COPYDB_VOLS_TOFROM_PATHS_FILE_INVALID
COPYDB_MSG_USAGE
Definition at line 181 of file utility.h.
enum MSGCAT_COPYLOGDB_MSG
Enumerator
COPYLOGDB_MSG_BAD_MODE
COPYLOGDB_MSG_DBA_PASSWORD
COPYLOGDB_MSG_NOT_HA_MODE
COPYLOGDB_MSG_HA_NOT_SUPPORT
COPYLOGDB_MSG_NOT_IN_STANDALONE
COPYLOGDB_MSG_USAGE
Definition at line 553 of file utility.h.
enum MSGCAT_CREATEDB_MSG
Enumerator
CREATEDB_MSG_MISSING_USER
CREATEDB_MSG_UNKNOWN_CMD
CREATEDB_MSG_BAD_OUTPUT
CREATEDB_MSG_CREATING
CREATEDB_MSG_FAILURE
CREATEDB_MSG_BAD_USERFILE
CREATEDB_MSG_BAD_RANGE
CREATEDB_MSG_INVALID_SIZE
CREATEDB_MSG_USAGE
Definition at line 190 of file utility.h.
enum MSGCAT_DELETEDB_MSG
Enumerator
DELETEDB_MSG_USAGE
Definition at line 130 of file utility.h.
enum MSGCAT_DELVOLDB_MSG
Enumerator
DELVOLDB_MSG_READY_TO_DEL
DELVOLDB_MSG_VERIFY
DELVOLDB_MSG_CANNOT_REMOVE_FIRST_VOL
DELVOLDB_MSG_CANNOT_FIND_VOL
DELVOLDB_MSG_TOO_MANY_VOLID
DELVOL_MSG_INVALID_VOLUME_ID
DELVOLDB_MSG_USAGE
Definition at line 663 of file utility.h.
enum MSGCAT_DIAGDB_MSG
Enumerator
DIAGDB_MSG_BAD_OUTPUT
DIAGDB_MSG_USAGE
Definition at line 299 of file utility.h.
enum MSGCAT_DUMP_TZ_MSG
Enumerator
DUMP_TZ_MSG_ID_OUT_OF_RANGE
DUMP_TZ_MSG_USAGE
Definition at line 646 of file utility.h.
enum MSGCAT_DUMPLOCALE_MSG
Enumerator
DUMPLOCALE_MSG_INCOMPAT_INPUT_SEL
DUMPLOCALE_MSG_INVALID_CP_RANGE
DUMPLOCALE_MSG_INVALID_LOCALE
DUMPLOCALE_MSG_USAGE
Definition at line 606 of file utility.h.
enum MSGCAT_ESTIMATEDB_DATA_MSG
Enumerator
ESTIMATEDB_DATA_MSG_NPAGES
ESTIMATEDB_DATA_MSG_USAGE
Definition at line 275 of file utility.h.
enum MSGCAT_ESTIMATEDB_INDEX_MSG
Enumerator
ESTIMATEDB_INDEX_BAD_KEYTYPE
ESTIMATEDB_INDEX_BAD_KEYLENGTH
ESTIMATEDB_INDEX_BAD_ARGUMENTS
ESTIMATEDB_INDEX_MSG_NPAGES
ESTIMATEDB_INDEX_MSG_BLT_NPAGES
ESTIMATEDB_INDEX_MSG_BLT_WRS_NPAGES
ESTIMATEDB_INDEX_MSG_INPUT
ESTIMATEDB_INDEX_MSG_INSTANCES
ESTIMATEDB_INDEX_MSG_NUMBER_KEYS
ESTIMATEDB_INDEX_MSG_AVG_KEYSIZE
ESTIMATEDB_INDEX_MSG_KEYTYPE
ESTIMATEDB_INDEX_MSG_USAGE
Definition at line 282 of file utility.h.
enum MSGCAT_GEN_TZ_MSG
Enumerator
GEN_TZ_MSG_INVALID_MODE
GEN_TZ_MSG_INVALID_INPUT_FOLDER
GEN_TZ_MSG_USAGE
Definition at line 638 of file utility.h.
enum MSGCAT_GENLOCALE_MSG
Enumerator
GENLOCALE_MSG_USAGE
GENLOCALE_MSG_INVALID_LOCALE
Definition at line 599 of file utility.h.
enum MSGCAT_INSTALLDB_MSG
Enumerator
INSTALLDB_MSG_USAGE
Definition at line 318 of file utility.h.
enum MSGCAT_KILLTRAN_MSG
Enumerator
KILLTRAN_MSG_MANY_ARGS
KILLTRAN_MSG_DBA_PASSWORD
KILLTRAN_MSG_NO_MATCHES
KILLTRAN_MSG_READY_TO_KILL
KILLTRAN_MSG_VERIFY
KILLTRAN_MSG_KILLING
KILLTRAN_MSG_KILL_FAILED
KILLTRAN_MSG_KILL_TIMEOUT
KILLTRAN_MSG_INVALID_TRANINDEX
KILLTRAN_MSG_NOT_IN_STANDALONE
KILLTRAN_MSG_USAGE
Definition at line 354 of file utility.h.
enum MSGCAT_LOADDB_MSG
Enumerator
LOADDB_MSG_MISSING_DBNAME
LOADDB_MSG_UNREACHABLE_LINE
LOADDB_MSG_SIG1
LOADDB_MSG_INTERRUPTED_COMMIT
LOADDB_MSG_INTERRUPTED_ABORT
LOADDB_MSG_BAD_INFILE
LOADDB_MSG_CHECKING
LOADDB_MSG_ERROR_COUNT
LOADDB_MSG_INSERTING
LOADDB_MSG_OBJECT_COUNT
LOADDB_MSG_DEFAULT_COUNT
LOADDB_MSG_COMMITTING
LOADDB_MSG_CLOSING
LOADDB_MSG_LINE
LOADDB_MSG_PARSE_ERROR
LOADDB_MSG_MISSING_DOMAIN
LOADDB_MSG_SET_DOMAIN_ERROR
LOADDB_MSG_UNEXPECTED_SET
LOADDB_MSG_UNEXPECTED_TYPE
LOADDB_MSG_UNKNOWN_ATT_CLASS
LOADDB_MSG_UNKNOWN_CLASS
LOADDB_MSG_UNKNOWN_CLASS_ID
LOADDB_MSG_UNAUTHORIZED_CLASS
LOADDB_MSG_STOPPED
LOADDB_MSG_UPDATE_WARNING
LOADDB_MSG_REDEFINING_INSTANCE
LOADDB_MSG_INSTANCE_DEFINED
LOADDB_MSG_INSTANCE_RESERVED
LOADDB_MSG_UNIQUE_VIOLATION_NULL
LOADDB_MSG_INSTANCE_COUNT
LOADDB_MSG_CLASS_TITLE
LOADDB_MSG_PASSWORD_PROMPT
LOADDB_MSG_UPDATING_STATISTICS
LOADDB_MSG_STD_ERR
LOADDB_MSG_LEX_ERROR
LOADDB_MSG_SYNTAX_ERR
LOADDB_MSG_SYNTAX_MISSING
LOADDB_MSG_SYNTAX_IN
LOADDB_MSG_INCOMPATIBLE_ARGS
LOADDB_MSG_COMMITTED_INSTANCES
LOADDB_MSG_NOPT_ERR
LOADDB_MSG_CONVERSION_ERROR
LOADDB_MSG_OID_NOT_SUPPORTED
LOADDB_MSG_UPDATED_CLASS_STATS
LOADDB_MSG_INSTANCE_COUNT_EX
LOADDB_MSG_LAST_COMMITTED_LINE
LOADDB_MSG_INSERT_AND_FAIL_COUNT
LOADDB_MSG_LOAD_FAIL
LOADDB_MSG_EXCEED_MAX_LEN
LOADDB_MSG_OBJECTS_SYNTAX_CHECKED
LOADDB_MSG_TABLE_IS_MISSING
LOADDB_MSG_IGNORED_CLASS
LOADDB_MSG_USAGE
Definition at line 438 of file utility.h.
enum MSGCAT_LOADJAVA_MSG
Enumerator
LOADJAVA_ARG_FORCE_OVERWRITE
LOADJAVA_ARG_FORCE_OVERWRITE_HELP
Definition at line 378 of file utility.h.
enum MSGCAT_LOCKDB_MSG
Enumerator
LOCKDB_MSG_BAD_OUTPUT
LOCKDB_MSG_NOT_IN_STANDALONE
LOCKDB_MSG_USAGE
Definition at line 324 of file utility.h.
enum MSGCAT_MASTER_MSG
Enumerator
MASTER_MSG_DUPLICATE
MASTER_MSG_STARTING
MASTER_MSG_EXITING
MASTER_MSG_NO_PARAMETERS
MASTER_MSG_PROCESS_ERROR
MASTER_MSG_SERVER_STATUS
MASTER_MSG_SERVER_NOTIFIED
MASTER_MSG_SERVER_NOT_FOUND
MASTER_MSG_GOING_DOWN
MASTER_MSG_FAILOVER_FINISHED
Definition at line 204 of file utility.h.
enum MSGCAT_MIGDB_MSG
Enumerator
MIGDB_MSG_TEMPORARY_CLASS_OID
MIGDB_MSG_CANT_PRINT_ELO
MIGDB_MSG_CANT_ACCESS_LO
MIGDB_MSG_CANT_OPEN_LO_FILE
MIGDB_MSG_READ_ERROR
MIGDB_MSG_WRITE_ERROR
MIGDB_MSG_CANT_OPEN_ELO
MIGDB_MSG_FH_HASH_FILENAME
MIGDB_MSG_FH_NAME
MIGDB_MSG_FH_SIZE
MIGDB_MSG_FH_PAGE_SIZE
MIGDB_MSG_FH_DATA_SIZE
MIGDB_MSG_FH_ENTRY_SIZE
MIGDB_MSG_FH_ENTRIES_PER_PAGE
MIGDB_MSG_FH_CACHED_PAGES
MIGDB_MSG_FH_NUM_ENTRIES
MIGDB_MSG_FH_NUM_COLLISIONS
MIGDB_MSG_FH_HASH_FILENAME2
MIGDB_MSG_FH_NEXT_OVERFLOW_ENTRY
MIGDB_MSG_FH_KEY_TYPE
MIGDB_MSG_FH_PAGE_HEADERS
MIGDB_MSG_FH_LAST_PAGE_HEADER
MIGDB_MSG_FH_FREE_PAGE_HEADER
MIGDB_MSG_FH_PAGE_BITMAP
MIGDB_MSG_FH_PAGE_BITMAP_SIZE
Definition at line 499 of file utility.h.
enum MSGCAT_OPTIMIZEDB_MSG
Enumerator
OPTIMIZEDB_MSG_USAGE
Definition at line 155 of file utility.h.
enum MSGCAT_PARAMDUMP_MSG
Enumerator
PARAMDUMP_MSG_BAD_OUTPUT
PARAMDUMP_MSG_CLIENT_PARAMETER
PARAMDUMP_MSG_SERVER_PARAMETER
PARAMDUMP_MSG_STANDALONE_PARAMETER
PARAMDUMP_MSG_USAGE
Definition at line 529 of file utility.h.
enum MSGCAT_PATCHDB_MSG
Enumerator
PATCHDB_MSG_USAGE
Definition at line 312 of file utility.h.
enum MSGCAT_PLANDUMP_MSG
Enumerator
PLANDUMP_MSG_BAD_OUTPUT
PLANDUMP_MSG_NOT_IN_STANDALONE
PLANDUMP_MSG_USAGE
Definition at line 370 of file utility.h.
enum MSGCAT_RENAMEDB_MSG
Enumerator
RENAMEDB_VOLEXT_PATH_INVALID
RENAMEDB_VOLS_TOFROM_PATHS_FILE_INVALID
RENAMEDB_MSG_USAGE
Definition at line 147 of file utility.h.
enum MSGCAT_RESTOREDB_MSG
Enumerator
RESTOREDB_MSG_BAD_DATE
RESTOREDB_MSG_FAILURE
RESTOREDB_MSG_USAGE
Definition at line 219 of file utility.h.
enum MSGCAT_RESTORESLAVE_MSG
Enumerator
RESTORESLAVE_MSG_FAILURE
RESTORESLAVE_MSG_HA_CATALOG_FAIL
RESTORESLAVE_MSG_INVAILD_OPTIONS
RESTORESLAVE_MSG_INVAILD_STATE
RESTORESLAVE_MSG_USAGE
Definition at line 653 of file utility.h.
enum MSGCAT_SPACEDB_MSG
Enumerator
SPACEDB_OUTPUT_TITLE
SPACEDB_MSG_BAD_OUTPUT
SPACEDB_OUTPUT_TITLE_LOB
SPACEDB_MSG_ALL_HEADER_PAGES
SPACEDB_MSG_ALL_HEADER_SIZE
SPACEDB_MSG_PERM_PERM_FORMAT
SPACEDB_MSG_PERM_TEMP_FORMAT
SPACEDB_MSG_TEMP_TEMP_FORMAT
SPACEDB_MSG_TOTAL_FORMAT
SPACEDB_MSG_VOLS_TITLE
SPACEDB_MSG_VOLS_HEADER_PAGES
SPACEDB_MSG_VOLS_HEADER_SIZE
SPACEDB_MSG_VOLS_PERM_PERM_FORMAT
SPACEDB_MSG_VOLS_PERM_TEMP_FORMAT
SPACEDB_MSG_VOLS_TEMP_TEMP_FORMAT
SPACEDB_MSG_FILES_TITLE
SPACEDB_MSG_FILES_HEADER_PAGES
SPACEDB_MSG_FILES_HEADER_SIZE
SPACEDB_MSG_FILES_FORMAT
SPACEDB_MSG_END_UNDERLINE
SPACEDB_MSG_USAGE
Definition at line 245 of file utility.h.
enum MSGCAT_STATDUMP_MSG
Enumerator
STATDUMP_MSG_BAD_OUTPUT
STATDUMP_MSG_NOT_IN_STANDALONE
STATDUMP_MSG_USAGE
Definition at line 574 of file utility.h.
enum MSGCAT_SYNCCOLLDB_MSG
Enumerator
SYNCCOLLDB_MSG_PARTITION_OBS_COLL
SYNCCOLLDB_MSG_FK_OBS_COLL
SYNCCOLLDB_MSG_CLASS_OBS_COLL
SYNCCOLLDB_MSG_FI_OBS_COLL
SYNCCOLLDB_MSG_SYNC_ABORT
SYNCCOLLDB_MSG_SYNC_OK
SYNCCOLLDB_MSG_SYNC_CONTINUE
SYNCCOLLDB_MSG_OBS_COLL
SYNCCOLLDB_MSG_TRIG_OBS_COLL
SYNCCOLLDB_MSG_VIEW_OBS_COLL
SYNCCOLLDB_MSG_ATTR_OBS_COLL
SYNCCOLLDB_MSG_REPORT_SQL_FILE
SYNCCOLLDB_MSG_REPORT_NOT_NEEDED
SYNCCOLLDB_MSG_REPORT_SYNC_REQUIRED
SYNCCOLLDB_MSG_REPORT_NEW_COLL
SYNCCOLLDB_MSG_REPORT_DB_OBS_OK
SYNCCOLLDB_MSG_REPORT_DB_OBS_NOK
SYNCCOLLDB_MSG_USAGE
Definition at line 615 of file utility.h.
enum MSGCAT_TDE_MSG
Enumerator
TDE_MSG_DBA_PASSWORD
TDE_MSG_NO_SET_MK_INFO
TDE_MSG_MK_CHANGING
TDE_MSG_MK_CHANGED
TDE_MSG_MK_SET_ON_DATABASE_DELETE
TDE_MSG_MK_DELETED
TDE_MSG_MK_GENERATED
TDE_MSG_USAGE
Definition at line 694 of file utility.h.
enum MSGCAT_TRANLIST_MSG
Enumerator
TRANLIST_MSG_USER_PASSWORD
TRANLIST_MSG_SUMMARY_HEADER
TRANLIST_MSG_SUMMARY_UNDERSCORE
TRANLIST_MSG_SUMMARY_ENTRY
TRANLIST_MSG_NONE_TABLE_ENTRIES
TRANLIST_MSG_NOT_DBA_USER
TRANLIST_MSG_INVALID_SORT_KEY
TRANLIST_MSG_QUERY_INFO_HEADER
TRANLIST_MSG_QUERY_INFO_ENTRY
TRANLIST_MSG_QUERY_INFO_UNDERSCORE
TRANLIST_MSG_FULL_INFO_HEADER
TRANLIST_MSG_FULL_INFO_ENTRY
TRANLIST_MSG_FULL_INFO_UNDERSCORE
TRANLIST_MSG_TRAN_INDEX
TRANLIST_MSG_SQL_ID
TRANLIST_MSG_NOT_IN_STANDALONE
TRANLIST_MSG_USAGE
Definition at line 332 of file utility.h.
enum MSGCAT_UNLOADDB_MSG
Enumerator
UNLOADDB_MSG_INVALID_CACHED_PAGES
UNLOADDB_MSG_INVALID_CACHED_PAGE_SIZE
UNLOADDB_MSG_OBJECTS_DUMPED
UNLOADDB_MSG_OBJECTS_FAILED
UNLOADDB_MSG_INVALID_DIR_NAME
UNLOADDB_MSG_LOG_LSA
UNLOADDB_MSG_PASSWORD_PROMPT
Definition at line 426 of file utility.h.
enum MSGCAT_UTIL_GENERIC_MSG
Enumerator
MSGCAT_UTIL_GENERIC_BAD_DATABASE_NAME
MSGCAT_UTIL_GENERIC_BAD_OUTPUT_FILE
MSGCAT_UTIL_GENERIC_BAD_VOLUME_NAME
MSGCAT_UTIL_GENERIC_VERSION
MSGCAT_UTIL_GENERIC_ADMIN_USAGE
MSGCAT_UTIL_GENERIC_SERVICE_INVALID_NAME
MSGCAT_UTIL_GENERIC_SERVICE_INVALID_CMD
MSGCAT_UTIL_GENERIC_SERVICE_PROPERTY_FAIL
MSGCAT_UTIL_GENERIC_START_STOP_3S
MSGCAT_UTIL_GENERIC_START_STOP_2S
MSGCAT_UTIL_GENERIC_NOT_RUNNING_2S
MSGCAT_UTIL_GENERIC_NOT_RUNNING_1S
MSGCAT_UTIL_GENERIC_ALREADY_RUNNING_2S
MSGCAT_UTIL_GENERIC_ALREADY_RUNNING_1S
MSGCAT_UTIL_GENERIC_RESULT
MSGCAT_UTIL_GENERIC_MISS_ARGUMENT
MSGCAT_UTIL_GENERIC_CUBRID_USAGE
MSGCAT_UTIL_GENERIC_ARGS_OVER
MSGCAT_UTIL_GENERIC_MISS_DBNAME
MSGCAT_UTIL_GENERIC_DEPRECATED
MSGCAT_UTIL_GENERIC_INVALID_PARAMETER
MSGCAT_UTIL_GENERIC_NO_MEM
MSGCAT_UTIL_GENERIC_NOT_HA_MODE
MSGCAT_UTIL_GENERIC_HA_MODE
MSGCAT_UTIL_GENERIC_HA_MODE_NOT_LISTED_HA_DB
MSGCAT_UTIL_GENERIC_HA_MODE_NOT_LISTED_HA_NODE
MSGCAT_UTIL_GENERIC_INVALID_CMD
MSGCAT_UTIL_GENERIC_MANAGER_NOT_INSTALLED
MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT
MSGCAT_UTIL_GENERIC_FILEOPEN_ERROR
Definition at line 95 of file utility.h.
enum MSGCAT_UTIL_SET
Enumerator
MSGCAT_UTIL_SET_GENERIC
MSGCAT_UTIL_SET_BACKUPDB
MSGCAT_UTIL_SET_COPYDB
MSGCAT_UTIL_SET_CREATEDB
MSGCAT_UTIL_SET_DELETEDB
MSGCAT_UTIL_SET_RENAMEDB
MSGCAT_UTIL_SET_MASTER
MSGCAT_UTIL_SET_OPTIMIZEDB
MSGCAT_UTIL_SET_RESTOREDB
MSGCAT_UTIL_SET_LOADDB
MSGCAT_UTIL_SET_UNLOADDB
MSGCAT_UTIL_SET_COMPACTDB
MSGCAT_UTIL_SET_COMMDB
MSGCAT_UTIL_SET_PATCHDB
MSGCAT_UTIL_SET_ADDVOLDB
MSGCAT_UTIL_SET_CHECKDB
MSGCAT_UTIL_SET_SPACEDB
MSGCAT_UTIL_SET_ESTIMATEDB_DATA
MSGCAT_UTIL_SET_ESTIMATEDB_INDEX
MSGCAT_UTIL_SET_INSTALLDB
MSGCAT_UTIL_SET_MIGDB
MSGCAT_UTIL_SET_DIAGDB
MSGCAT_UTIL_SET_LOCKDB
MSGCAT_UTIL_SET_KILLTRAN
MSGCAT_UTIL_SET_ALTERDBHOST
MSGCAT_UTIL_SET_LOADJAVA
MSGCAT_UTIL_SET_PLANDUMP
MSGCAT_UTIL_SET_PARAMDUMP
MSGCAT_UTIL_SET_CHANGEMODE
MSGCAT_UTIL_SET_COPYLOGDB
MSGCAT_UTIL_SET_APPLYLOGDB
MSGCAT_UTIL_SET_LOGFILEDUMP
MSGCAT_UTIL_SET_STATDUMP
MSGCAT_UTIL_SET_APPLYINFO
MSGCAT_UTIL_SET_ACLDB
MSGCAT_UTIL_SET_GENLOCALE
MSGCAT_UTIL_SET_DUMPLOCALE
MSGCAT_UTIL_SET_SYNCCOLLDB
MSGCAT_UTIL_SET_TRANLIST
MSGCAT_UTIL_SET_GEN_TZ
MSGCAT_UTIL_SET_DUMP_TZ
MSGCAT_UTIL_SET_RESTORESLAVE
MSGCAT_UTIL_SET_DELVOLDB
MSGCAT_UTIL_SET_VACUUMDB
MSGCAT_UTIL_SET_CHECKSUMDB
MSGCAT_UTIL_SET_TDE
Definition at line 44 of file utility.h.
enum MSGCAT_VACUUMDB_MSG
Enumerator
VACUUMDB_MSG_CLIENT_SERVER_NOT_AVAILABLE
VACUUMDB_MSG_FAILED
VACUUMDB_MSG_BAD_OUTPUT
VACUUMDB_MSG_USAGE
Definition at line 675 of file utility.h.
enum UTIL_ARG_TYPE
Enumerator
ARG_INTEGER
ARG_STRING
ARG_BOOLEAN
ARG_BIGINT
Definition at line 762 of file utility.h.
enum UTIL_INDEX
Enumerator
CREATEDB
RENAMEDB
COPYDB
DELETEDB
BACKUPDB
RESTOREDB
ADDVOLDB
SPACEDB
LOCKDB
KILLTRAN
OPTIMIZEDB
INSTALLDB
DIAGDB
PATCHDB
CHECKDB
ALTERDBHOST
PLANDUMP
ESTIMATE_DATA
ESTIMATE_INDEX
LOADDB
UNLOADDB
COMPACTDB
PARAMDUMP
STATDUMP
CHANGEMODE
COPYLOGDB
APPLYLOGDB
APPLYINFO
ACLDB
GENLOCALE
DUMPLOCALE
SYNCCOLLDB
TRANLIST
GEN_TZ
DUMP_TZ
RESTORESLAVE
VACUUMDB
CHECKSUMDB
TDE
LOGFILEDUMP
Definition at line 708 of file utility.h.
enum UTIL_MODE
Enumerator
SA_ONLY
CS_ONLY
SA_CS
Definition at line 755 of file utility.h.
Function Documentation
int acldb (UTIL_FUNCTION_ARG * arg_map)
Definition at line 1128 of file util_cs.c.
References acl_dump(), acl_reload(), ACLDB_MSG_NOT_IN_STANDALONE, ACLDB_MSG_USAGE, ACLDB_RELOAD_S, UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), check_database_name(), UTIL_FUNCTION_ARG::command_name, database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_error_string(), db_login(), db_restart(), db_set_client_type(), db_shutdown(), er_init(), ER_NEVER_EXIT, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_SET_ACLDB, NO_ERROR, NULL, OPTION_STRING_TABLE, TRUE, utility_get_option_bool_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int addvoldb (UTIL_FUNCTION_ARG * arg_map)
Definition at line 355 of file util_cs.c.
References ADDVOL_COMMENT_S, ADDVOL_FILE_PATH_S, ADDVOL_MAX_WRITESIZE_IN_SEC_S, ADDVOL_PURPOSE_S, ADDVOL_SA_MODE_S, ADDVOL_VOLUME_NAME_S, ADDVOL_VOLUME_SIZE_S, ADDVOLDB_INVALID_MAX_WRITESIZE_IN_SEC, ADDVOLDB_MSG_BAD_NPAGES, ADDVOLDB_MSG_BAD_PURPOSE, ADDVOLDB_MSG_USAGE, UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), check_database_name(), check_volume_name(), UTIL_FUNCTION_ARG::command_name, dbdef_vol_ext_info::comments, database_name, db_add_volume_ex(), DB_CLIENT_TYPE_ADMIN_UTILITY, db_commit_transaction(), db_error_string(), db_login(), DB_PERMANENT_DATA_PURPOSE, db_restart(), db_set_client_type(), db_shutdown(), DB_TEMPORARY_DATA_PURPOSE, er_init(), ER_NEVER_EXIT, IO_PAGESIZE, dbdef_vol_ext_info::max_npages, dbdef_vol_ext_info::max_writesize_in_sec, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_ADDVOLDB, dbdef_vol_ext_info::name, NO_ERROR, NULL, ONE_K, OPTION_STRING_TABLE, dbdef_vol_ext_info::overwrite, dbdef_vol_ext_info::path, PRINT_AND_LOG_ERR_MSG, prm_get_bigint_value(), prm_get_name(), PRM_ID_DB_VOLUME_SIZE, PRM_ID_JAVA_STORED_PROCEDURE, PRM_ID_PB_NBUFFERS, dbdef_vol_ext_info::purpose, sysprm_set_force(), TRUE, util_log_write_errid(), util_print_deprecated(), util_size_string_to_byte(), utility_get_option_bool_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int alterdbhost (UTIL_FUNCTION_ARG * arg_map)
Definition at line 1896 of file util_sa.c.
References ALTERDBHOST_HOST_S, ALTERDBHOST_MSG_USAGE, ARG_FILE_LINE, UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, basename(), BO_DB_FULLNAME, cfg_find_db_list(), cfg_free_directory(), cfg_free_hosts(), cfg_get_hosts(), cfg_maycreate_get_directory_filename(), cfg_read_directory(), cfg_read_directory_ex(), cfg_write_directory(), cfg_write_directory_ex(), check_database_name(), COMPOSE_FULL_NAME(), CUB_MAXHOSTNAMELEN, db_error_string(), db_name, ER_BO_UNABLE_TO_FIND_HOSTNAME, ER_BO_UNKNOWN_DATABASE, ER_ERROR_SEVERITY, er_init(), ER_NEVER_EXIT, er_set(), er_set_with_oserror(), error(), fileio_dismount(), fileio_get_base_file_name(), fileio_is_volume_exist(), fileio_mount(), GETHOSTNAME, database_info::hosts, LOG_DBLOG_ACTIVE_VOLID, LOG_DBTXT_VOLID, log_Name_active, database_info::logpath, logpb_initialize_log_names(), MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_ALTERDBHOST, NO_ERROR, NULL, NULL_VOLDES, OPTION_STRING_TABLE, database_info::pathname, PRINT_AND_LOG_ERR_MSG, util_log_write_errid(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int applyinfo (UTIL_FUNCTION_ARG * arg_map)
Definition at line 3130 of file util_cs.c.
References APPLYINFO_APPLIED_INFO_S, APPLYINFO_COPIED_LOG_PATH_S, APPLYINFO_INTERVAL_S, APPLYINFO_MSG_HA_NOT_SUPPORT, APPLYINFO_MSG_NOT_HA_MODE, APPLYINFO_MSG_NOT_IN_STANDALONE, APPLYINFO_MSG_USAGE, APPLYINFO_PAGE_S, APPLYINFO_REMOTE_NAME_S, APPLYINFO_VERBOSE_S, UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), check_database_name(), UTIL_FUNCTION_ARG::command_name, CUB_MAXHOSTNAMELEN, database_name, db_clear_host_connected(), DB_CLIENT_TYPE_ADMIN_UTILITY, db_error_string(), db_login(), db_restart(), db_set_client_type(), db_shutdown(), er_init(), ER_NEVER_EXIT, error(), HA_DISABLED, HA_GET_MODE, HA_MODE_REPLICA, intr_handler(), is_Sigint_caught, la_log_page_check(), la_print_delay_info(), LSA_ISNULL(), LSA_SET_NULL(), MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_GENERIC_INVALID_PARAMETER, MSGCAT_UTIL_GENERIC_SERVICE_PROPERTY_FAIL, MSGCAT_UTIL_SET_APPLYINFO, MSGCAT_UTIL_SET_GENERIC, NO_ERROR, NULL, OPTION_STRING_TABLE, os_set_signal_handler(), log_lsa::pageid, PRINT_AND_LOG_ERR_MSG, prm_get_name(), prm_get_string_value(), PRM_ID_HA_REPLICA_TIME_BOUND, start_time, SYSPRM_LOAD_ALL, sysprm_load_and_init(), TRUE, util_log_write_errid(), util_str_to_time_since_epoch(), utility_get_option_bigint_value(), utility_get_option_bool_value(), utility_get_option_int_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int applylogdb (UTIL_FUNCTION_ARG * arg_map)
Definition at line 2862 of file util_cs.c.
References APPLYLOG_LOG_PATH_S, APPLYLOG_MAX_MEM_SIZE_S, APPLYLOGDB_MSG_HA_NOT_SUPPORT, APPLYLOGDB_MSG_NOT_HA_MODE, APPLYLOGDB_MSG_NOT_IN_STANDALONE, APPLYLOGDB_MSG_USAGE, ARG_FILE_LINE, UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), check_database_name(), UTIL_FUNCTION_ARG::command_name, database_name, DB_CLIENT_TYPE_LOG_APPLIER, db_disable_trigger(), db_error_string(), db_login(), db_restart(), db_set_client_type(), db_set_lock_timeout(), db_shutdown(), envvar_bindir_file(), ER_BO_CONNECT_FAILED, er_errid(), ER_FAILED, er_init(), ER_LC_PARTIALLY_FAILED_TO_FLUSH, er_log_debug, ER_NET_CANT_CONNECT_SERVER, ER_NET_SERVER_COMM_ERROR, ER_NET_SERVER_CRASHED, ER_NEVER_EXIT, ERR_CSS_TCP_CANNOT_CONNECT_TO_MASTER, error(), executable_path, HA_DISABLED, HA_GET_MODE, HA_MODE_REPLICA, hb_Proc_shutdown, hb_process_init(), HB_PTYPE_APPLYLOGDB, hb_set_argv(), hb_set_exec_path(), la_apply_log_file(), la_force_shutdown(), MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_GENERIC_INVALID_PARAMETER, MSGCAT_UTIL_GENERIC_SERVICE_PROPERTY_FAIL, MSGCAT_UTIL_SET_APPLYLOGDB, MSGCAT_UTIL_SET_GENERIC, NO_ERROR, NULL, OPTION_STRING_TABLE, PRINT_AND_LOG_ERR_MSG, prm_get_name(), prm_get_string_value(), PRM_ID_HA_REPLICA_TIME_BOUND, strdup(), SYSPRM_LOAD_ALL, sysprm_load_and_init(), TRUE, util_log_write_errid(), util_log_write_errstr(), util_redirect_stdout_to_null(), util_str_to_time_since_epoch(), utility_get_option_int_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
bool are_hostnames_equal (const char * hostname_a, const char * hostname_b)
Compare two host names if are equal, if one of the host names is canonical name and the other is not, then only host part (e.g. for canonical name "host-1.cubrid.org" host part is "host-1") is used for comparison
for example following hosts are equal: "host-1" "host-1" "host-1" "host-1.cubrid.org" "host-1.cubrid.org" "host-1" "host-1.cubrid.org" "host-1.cubrid.org"
for example following hosts are not equal: "host-1" "host-2" "host-1.cubrid.org" "host-2" "host-1" "host-2.cubrid.org" "host-1.cubrid.org" "host-2.cubrid.org" "host-1.cubrid.org" "host-1.cubrid.com"
Parameters
hostname_a first hostname
hostname_b second hostname
Returns
true if hostname_a is same as hostname_b
Definition at line 449 of file util_common.c.
Referenced by hb_add_node_to_cluster(), hb_check_ping(), hb_cluster_cleanup(), hb_cluster_load_group_and_node_list(), hb_cluster_receive_heartbeat(), hb_cluster_request_heartbeat_to_all(), hb_reload_config(), hb_return_node_by_name(), hb_return_node_by_name_except_me(), hb_return_ui_node(), and util_is_localhost().
int backupdb (UTIL_FUNCTION_ARG * arg_map)
Definition at line 121 of file util_cs.c.
References ARG_FILE_LINE, UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, assert, AU_DISABLE_PASSWORDS, BACKUP_COMPRESS_S, BACKUP_DESTINATION_PATH_S, BACKUP_LEVEL_S, BACKUP_NO_CHECK_S, BACKUP_OUTPUT_FILE_S, BACKUP_REMOVE_ARCHIVE_S, BACKUP_SA_MODE_S, BACKUP_SEPARATE_KEYS_S, BACKUP_SLEEP_MSECS_S, BACKUP_THREAD_COUNT_S, BACKUPDB_FIFO_KEYS_NOT_SUPPORTED, BACKUPDB_INVALID_PATH, BACKUPDB_INVALID_THREAD_NUM_OPT, BACKUPDB_MSG_USAGE, BACKUPDB_NOT_USING_SEPARATE_KEYS, backupdb_sig_interrupt_handler(), BACKUPDB_USING_SEPARATE_KEYS, basename(), boot_backup(), boot_check_db_consistency(), check_database_name(), CHECKDB_BTREE_CHECK_ALL_BTREES, CHECKDB_CT_CHECK_CAT_CONSISTENCY, CHECKDB_FILE_TRACKER_CHECK, CHECKDB_HEAP_CHECK_ALLHEAPS, CHECKDB_LC_CHECK_CLASSNAMES, CHECKDB_MSG_INCONSISTENT, UTIL_FUNCTION_ARG::command_name, database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_commit_transaction(), db_error_string(), db_login(), db_restart(), db_set_client_type(), db_set_isolation(), db_shutdown(), dirname(), ER_ERROR_SEVERITY, ER_GENERIC_ERROR, er_get_msglog_filename(), er_init(), ER_NEVER_EXIT, er_set(), FILEIO_BACKUP_FULL_LEVEL, FILEIO_BACKUP_NUM_THREADS_AUTO, FILEIO_BACKUP_SLEEP_MSECS_AUTO, FILEIO_BACKUP_UNDEFINED_LEVEL, FILEIO_ZIP_LZ4_DEFAULT_LEVEL, FILEIO_ZIP_LZ4_METHOD, FILEIO_ZIP_NONE_LEVEL, FILEIO_ZIP_NONE_METHOD, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_BACKUPDB, MSGCAT_UTIL_SET_CHECKDB, NO_ERROR, NULL, OPTION_STRING_TABLE, os_set_signal_handler(), PRINT_AND_LOG_ERR_MSG, prm_get_name(), PRM_ID_JAVA_STORED_PROCEDURE, sysprm_set_force(), TRAN_READ_COMMITTED, TRUE, util_log_write_errid(), util_log_write_warnstr(), utility_get_option_bool_value(), utility_get_option_int_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int changemode (UTIL_FUNCTION_ARG * arg_map)
Definition at line 2486 of file util_cs.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), boot_change_ha_mode(), CHANGEMODE_FORCE_S, changemode_keyword(), CHANGEMODE_MODE_S, CHANGEMODE_MSG_BAD_MODE, CHANGEMODE_MSG_HA_NOT_SUPPORT, CHANGEMODE_MSG_NOT_HA_MODE, CHANGEMODE_MSG_NOT_IN_STANDALONE, CHANGEMODE_MSG_SERVER_MODE, CHANGEMODE_MSG_USAGE, CHANGEMODE_TIMEOUT_S, check_database_name(), UTIL_FUNCTION_ARG::command_name, database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_error_string(), db_login(), db_restart(), db_set_client_type(), db_shutdown(), er_init(), ER_NEVER_EXIT, error(), HA_CHANGE_MODE_DEFAULT_TIMEOUT_IN_SECS, HA_DISABLED, HA_SERVER_STATE_ACTIVE, HA_SERVER_STATE_MAINTENANCE, HA_SERVER_STATE_NA, HA_SERVER_STATE_STANDBY, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_CHANGEMODE, NO_ERROR, NULL, OPTION_STRING_TABLE, PRINT_AND_LOG_ERR_MSG, TRUE, util_log_write_errid(), utility_get_option_bool_value(), utility_get_option_int_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int changemode_keyword (int * keyval_p, char ** keystr_p)
Definition at line 555 of file util_common.c.
References HA_SERVER_STATE_ACTIVE, HA_SERVER_STATE_ACTIVE_STR, HA_SERVER_STATE_DEAD, HA_SERVER_STATE_DEAD_STR, HA_SERVER_STATE_IDLE, HA_SERVER_STATE_IDLE_STR, HA_SERVER_STATE_MAINTENANCE, HA_SERVER_STATE_MAINTENANCE_STR, HA_SERVER_STATE_STANDBY, HA_SERVER_STATE_STANDBY_STR, HA_SERVER_STATE_TO_BE_ACTIVE, HA_SERVER_STATE_TO_BE_ACTIVE_STR, HA_SERVER_STATE_TO_BE_STANDBY, HA_SERVER_STATE_TO_BE_STANDBY_STR, keywords, NULL, and utility_keyword_search().
Referenced by changemode().
int check_database_name (const char * name)
Definition at line 99 of file util_common.c.
References check_database_name_local(), and EXISTING_DATABASE.
Referenced by acldb(), addvoldb(), alterdbhost(), applyinfo(), applylogdb(), backupdb(), changemode(), checkdb(), checksumdb(), copydb(), copylogdb(), deletedb(), diagdb(), gen_tz(), installdb(), killtran(), lockdb(), main(), optimizedb(), paramdump(), patchdb(), plandump(), renamedb(), spacedb(), statdump(), synccolldb(), tde(), tranlist(), and vacuumdb().
int check_new_database_name (const char * name)
Definition at line 110 of file util_common.c.
References check_database_name_local(), and NEW_DATABASE.
Referenced by copydb(), createdb(), and renamedb().
int check_volume_name (const char * name)
Definition at line 161 of file util_common.c.
References ER_GENERIC_ERROR, i, MSGCAT_UTIL_GENERIC_BAD_VOLUME_NAME, NO_ERROR, NULL, PRINT_AND_LOG_ERR_MSG, and utility_get_generic_message().
Referenced by addvoldb().
int checkdb (UTIL_FUNCTION_ARG * arg_map)
Definition at line 621 of file util_cs.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), boot_check_db_consistency(), BTID_SET_NULL, CHECK_BTREE_ALL_BTREES_S, CHECK_CAT_CONSISTENCY_S, CHECK_CHECK_PREV_LINK_S, check_database_name(), CHECK_FILE_TRACKER_S, CHECK_HEAP_ALLHEAPS_S, CHECK_INDEXNAME_S, CHECK_INPUT_FILE_S, CHECK_LC_ALLENTRIES_OF_ALLBTREES_S, CHECK_LC_CLASSNAMES_S, CHECK_REPAIR_PREV_LINK_S, CHECK_REPAIR_S, CHECKDB_ALL_CHECK_EXCEPT_PREV_LINK, CHECKDB_BTREE_CHECK_ALL_BTREES, CHECKDB_CHECK_PREV_LINK, CHECKDB_CT_CHECK_CAT_CONSISTENCY, CHECKDB_FILE_TRACKER_CHECK, CHECKDB_HEAP_CHECK_ALLHEAPS, CHECKDB_LC_CHECK_ALLENTRIES_OF_ALLBTREES, CHECKDB_LC_CHECK_CLASSNAMES, CHECKDB_MSG_INCONSISTENT, CHECKDB_MSG_USAGE, CHECKDB_REPAIR, CHECKDB_REPAIR_PREV_LINK, UTIL_FUNCTION_ARG::command_name, da_add(), da_create(), da_destroy(), da_size(), database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_commit_transaction(), db_error_string(), db_login(), db_restart(), db_set_client_type(), db_set_isolation(), db_shutdown(), er_get_msglog_filename(), er_init(), ER_NEVER_EXIT, i, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_GENERIC_NO_MEM, MSGCAT_UTIL_SET_CHECKDB, NO_ERROR, NULL, OPTION_STRING_TABLE, p, PRINT_AND_LOG_ERR_MSG, prm_get_name(), PRM_ID_JAVA_STORED_PROCEDURE, SM_MAX_IDENTIFIER_LENGTH, strncpy_bufsize, sysprm_set_force(), TRAN_READ_COMMITTED, TRUE, util_get_class_oids_and_index_btid(), util_get_table_list_from_file(), util_log_write_errid(), util_log_write_errstr(), utility_get_option_bool_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int checksumdb (UTIL_FUNCTION_ARG * arg_map)
Definition at line 2068 of file checksumdb.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, assert, AU_DISABLE_PASSWORDS, basename(), begin(), check_database_name(), CHECKSUM_CHUNK_SIZE_S, CHECKSUM_CONT_ON_ERROR_S, CHECKSUM_EXCLUDE_CLASS_FILE_S, CHECKSUM_INCLUDE_CLASS_FILE_S, CHECKSUM_REPORT_ONLY_S, CHECKSUM_RESUME_S, CHECKSUM_SCHEMA_ONLY_S, CHECKSUM_SLEEP_S, CHECKSUM_TABLE_NAME_S, CHECKSUM_TIMEOUT_S, CHECKSUMDB_MSG_HA_NOT_SUPPORT, CHECKSUMDB_MSG_INVALID_INPUT_FILE, CHECKSUMDB_MSG_MUST_RUN_ON_ACTIVE, CHECKSUMDB_MSG_NOT_IN_STANDALONE, CHECKSUMDB_MSG_USAGE, CHKSUM_DEFAULT_LIST_SIZE, CHKSUM_DEFAULT_TABLE_NAME, CHKSUM_MIN_CHUNK_SIZE, chksum_report(), chksum_result_Table_name, chksum_schema_Table_name, CHKSUM_SCHEMA_TABLE_SUFFIX, chksum_start(), chksum_arg::chunk_size, UTIL_FUNCTION_ARG::command_name, chksum_arg::cont_on_err, css_ha_server_state(), css_ha_server_state_string(), da_create(), da_destroy(), database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_error_string(), db_login(), db_restart(), db_set_client_type(), db_set_isolation(), db_set_lock_timeout(), db_shutdown(), ER_FAILED, er_init(), ER_NEVER_EXIT, error(), chksum_arg::exclude_list, HA_SERVER_STATE_ACTIVE, HA_SERVER_STATE_NA, chksum_arg::include_list, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_GENERIC_SERVICE_PROPERTY_FAIL, MSGCAT_UTIL_SET_CHECKSUMDB, NO_ERROR, NULL, OPTION_STRING_TABLE, PRINT_AND_LOG_ERR_MSG, chksum_arg::resume, chksum_arg::schema_only, chksum_arg::sleep_msecs, sm_check_name(), SM_MAX_IDENTIFIER_LENGTH, SYSPRM_LOAD_ALL, sysprm_load_and_init(), chksum_arg::timeout_msecs, TRAN_REPEATABLE_READ, TRUE, util_get_table_list_from_file(), util_log_write_errid(), utility_get_option_bool_value(), utility_get_option_int_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int compactdb (UTIL_FUNCTION_ARG * arg_map)
Definition at line 98 of file compactdb.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, UTIL_FUNCTION_ARG::command_name, COMPACT_CLASS_LOCK_TIMEOUT_S, COMPACT_CLASS_MAX_LOCK_TIMEOUT, COMPACT_CLASS_MIN_LOCK_TIMEOUT, COMPACT_DELETE_OLD_REPR_S, COMPACT_INPUT_CLASS_FILE_S, COMPACT_INSTANCE_LOCK_TIMEOUT_S, COMPACT_INSTANCE_MAX_LOCK_TIMEOUT, COMPACT_INSTANCE_MIN_LOCK_TIMEOUT, COMPACT_MAX_PAGES, COMPACT_MIN_PAGES, COMPACT_PAGES_COMMITED_ONCE_S, COMPACT_STANDBY_CS_MODE_S, compact_usage(), COMPACT_VERBOSE_S, COMPACTDB_MSG_FAILURE, COMPACTDB_MSG_OUT_OF_RANGE_CLASS_LOCK_TIMEOUT, COMPACTDB_MSG_OUT_OF_RANGE_INSTANCE_LOCK_TIMEOUT, COMPACTDB_MSG_OUT_OF_RANGE_PAGES, compactdb_start(), compactdb_usage(), database_name, DB_CLIENT_TYPE_ADMIN_COMPACTDB_WOS, DB_CLIENT_TYPE_ADMIN_UTILITY, db_error_string(), db_login(), DB_PAGESIZE, db_restart(), db_set_client_type(), db_set_isolation(), db_shutdown(), ER_FAILED, ER_GENERIC_ERROR, error(), i, input_filename, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_SET_COMPACTDB, NO_ERROR, NULL, OPTION_STRING_TABLE, PRINT_AND_LOG_ERR_MSG, prm_get_name(), PRM_ID_JAVA_STORED_PROCEDURE, sysprm_set_force(), TRAN_DEFAULT_ISOLATION_LEVEL, TRUE, util_log_write_errstr(), utility_get_option_bool_value(), utility_get_option_int_value(), utility_get_option_string_table_size(), utility_get_option_string_value(), and verbose_flag.
int copydb (UTIL_FUNCTION_ARG * arg_map)
Definition at line 1236 of file util_sa.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), boot_copy(), boot_delete(), boot_get_lob_path(), check_database_name(), check_new_database_name(), UTIL_FUNCTION_ARG::command_name, COPY_CONTROL_FILE_S, COPY_COPY_LOB_PATH_S, COPY_DELETE_SOURCE_S, COPY_EXTENTED_VOLUME_PATH_S, COPY_FILE_PATH_S, COPY_LOB_PATH_S, COPY_LOG_PATH_S, COPY_REPLACE_S, COPY_SERVER_NAME_S, COPYDB_MSG_IDENTICAL, COPYDB_MSG_USAGE, DB_CLIENT_TYPE_ADMIN_UTILITY, db_error_string(), db_login(), db_restart(), db_set_client_type(), ER_ALL_FINAL, er_final(), er_init(), ER_NEVER_EXIT, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_COPYDB, NO_ERROR, NULL, OPTION_STRING_TABLE, PRINT_AND_LOG_ERR_MSG, prm_get_name(), PRM_ID_JAVA_STORED_PROCEDURE, PRM_ID_PB_NBUFFERS, sysprm_set_force(), TRUE, util_log_write_errid(), utility_get_option_bool_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int copylogdb (UTIL_FUNCTION_ARG * arg_map)
Definition at line 2633 of file util_cs.c.
References ARG_FILE_LINE, UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), check_database_name(), UTIL_FUNCTION_ARG::command_name, COPYLOG_LOG_PATH_S, COPYLOG_MODE_S, COPYLOG_START_PAGEID_S, copylogdb_keyword(), COPYLOGDB_MSG_BAD_MODE, COPYLOGDB_MSG_HA_NOT_SUPPORT, COPYLOGDB_MSG_NOT_IN_STANDALONE, COPYLOGDB_MSG_USAGE, database_name, DB_CLIENT_TYPE_LOG_COPIER, db_error_string(), db_login(), db_restart(), db_set_client_type(), db_shutdown(), envvar_bindir_file(), ER_BO_CONNECT_FAILED, er_errid(), ER_FAILED, er_init(), er_log_debug, ER_NET_CANT_CONNECT_SERVER, ER_NET_SERVER_CRASHED, ER_NEVER_EXIT, ERR_CSS_TCP_CANNOT_CONNECT_TO_MASTER, ERR_CSS_TCP_CONNECT_TIMEDOUT, error(), executable_path, HA_DISABLED, hb_Proc_shutdown, hb_process_init(), HB_PTYPE_COPYLOGDB, hb_set_argv(), hb_set_exec_path(), logwr_copy_log_file(), logwr_force_shutdown(), LOGWR_MODE_ASYNC, LOGWR_MODE_SEMISYNC, LOGWR_MODE_SYNC, mode, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_COPYLOGDB, NO_ERROR, NULL, NULL_PAGEID, OPTION_STRING_TABLE, PRINT_AND_LOG_ERR_MSG, prm_get_name(), PRM_ID_ER_LOG_FILE, PRM_ID_LOG_BACKGROUND_ARCHIVING, SYSPRM_LOAD_ALL, sysprm_load_and_init(), sysprm_set_force(), sysprm_set_to_default(), TRUE, util_log_write_errid(), util_log_write_errstr(), util_redirect_stdout_to_null(), utility_get_option_bigint_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int copylogdb_keyword (int * keyval_p, char ** keystr_p)
Definition at line 536 of file util_common.c.
References keywords, LOGWR_MODE_ASYNC, LOGWR_MODE_SEMISYNC, LOGWR_MODE_SYNC, NULL, and utility_keyword_search().
Referenced by copylogdb(), and util_make_ha_conf().
int createdb (UTIL_FUNCTION_ARG * arg_map)
Definition at line 303 of file util_sa.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, au_dump_to_file(), au_force_write_new_auth(), CSQL_ARGUMENT::auto_commit, basename(), catcls_compile_catalog_classes(), catcls_Enable, char_isdigit(), check_new_database_name(), tz_data::checksum, UTIL_FUNCTION_ARG::command_name, CREATE_COMMENT_S, CREATE_CSQL_INITIALIZATION_FILE_S, CREATE_DB_PAGE_SIZE_L, CREATE_DB_PAGE_SIZE_S, CREATE_DB_VOLUME_SIZE_L, CREATE_DB_VOLUME_SIZE_S, CREATE_FILE_PATH_S, CREATE_LOB_PATH_S, CREATE_LOG_PAGE_COUNT_L, CREATE_LOG_PAGE_COUNT_S, CREATE_LOG_PAGE_SIZE_L, CREATE_LOG_PAGE_SIZE_S, CREATE_LOG_PATH_S, CREATE_LOG_VOLUME_SIZE_L, CREATE_LOG_VOLUME_SIZE_S, CREATE_MORE_VOLUME_FILE_S, CREATE_OUTPUT_FILE_S, CREATE_PAGE_SIZE_L, CREATE_PAGE_SIZE_S, CREATE_PAGES_L, CREATE_PAGES_S, CREATE_REPLACE_S, CREATE_SERVER_NAME_S, CREATE_USER_DEFINITION_FILE_S, CREATE_VERBOSE_S, CREATEDB_MSG_BAD_OUTPUT, CREATEDB_MSG_BAD_RANGE, CREATEDB_MSG_BAD_USERFILE, CREATEDB_MSG_CREATING, CREATEDB_MSG_FAILURE, CREATEDB_MSG_INVALID_SIZE, CREATEDB_MSG_USAGE, csql(), database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_commit_transaction(), db_error_string(), db_init(), db_login(), CSQL_ARGUMENT::db_name, db_page_size(), db_set_client_type(), db_shutdown(), DISK_SECTOR_NPAGES, disk_sectors_to_extend_npages(), er_init(), ER_NEVER_EXIT, CSQL_ARGUMENT::in_file_name, IO_PAGESIZE, lang_db_put_charset(), make_valid_page_size(), max, tf_meta_class::mc_n_variable, min, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_GENERIC_SERVICE_PROPERTY_FAIL, MSGCAT_UTIL_SET_CREATEDB, NO_ERROR, NULL, OPTION_STRING_TABLE, output_file, parse_user_define_file(), PRINT_AND_LOG_ERR_MSG, prm_get_bigint_value(), prm_get_name(), PRM_ID_DB_VOLUME_SIZE, PRM_ID_JAVA_STORED_PROCEDURE, PRM_ID_LOG_VOLUME_SIZE, PRM_ID_PB_NBUFFERS, PRM_ID_XASL_CACHE_MAX_ENTRIES, program_name, put_timezone_checksum(), sm_force_write_all_classes(), sm_mark_system_classes(), sm_update_all_catalog_statistics(), STATS_WITH_FULLSCAN, strlen, sysprm_check_range(), sysprm_get_range(), SYSPRM_LOAD_ALL, sysprm_load_and_init(), sysprm_set_force(), tf_compile_meta_classes(), tf_Metaclass_class, tz_get_data(), tz_load(), util_byte_to_size_string(), util_log_write_errid(), util_log_write_errstr(), util_print_deprecated(), util_size_string_to_byte(), utility_get_option_bool_value(), utility_get_option_int_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int deletedb (UTIL_FUNCTION_ARG * arg_map)
Definition at line 708 of file util_sa.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), boot_delete(), check_database_name(), UTIL_FUNCTION_ARG::command_name, database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_error_string(), db_login(), db_set_client_type(), DELETE_DELETE_BACKUP_S, DELETE_OUTPUT_FILE_S, DELETEDB_MSG_USAGE, ER_ALL_FINAL, er_final(), er_init(), ER_NEVER_EXIT, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_BAD_OUTPUT_FILE, MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_DELETEDB, MSGCAT_UTIL_SET_GENERIC, NO_ERROR, NULL, OPTION_STRING_TABLE, output_file, PRINT_AND_LOG_ERR_MSG, prm_get_name(), PRM_ID_JAVA_STORED_PROCEDURE, PRM_ID_PB_NBUFFERS, sysprm_set_force(), util_log_write_errid(), utility_get_option_bool_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int diagdb (UTIL_FUNCTION_ARG * arg_map)
Definition at line 1446 of file util_sa.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), catalog_dump(), check_database_name(), UTIL_FUNCTION_ARG::command_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_error_string(), db_login(), db_name, db_restart(), db_set_client_type(), db_shutdown(), DIAG_DUMP_RECORDS_S, DIAG_DUMP_TYPE_S, DIAG_EMERGENCY_S, DIAG_OUTPUT_FILE_S, DIAGDB_MSG_BAD_OUTPUT, DIAGDB_MSG_USAGE, DIAGDUMP_ALL, DIAGDUMP_CATALOG, DIAGDUMP_CLASSNAMES, DIAGDUMP_DISK_BITMAPS, DIAGDUMP_END_OF_OPTION, DIAGDUMP_FILE_CAPACITIES, DIAGDUMP_FILE_TABLES, DIAGDUMP_HEAP, DIAGDUMP_HEAP_CAPACITIES, DIAGDUMP_INDEX_CAPACITIES, DIAGDUMP_LOG, disk_dump_all(), er_init(), ER_NEVER_EXIT, file_tracker_dump(), file_tracker_dump_all_btree_capacities(), file_tracker_dump_all_capacities(), file_tracker_dump_all_heap(), file_tracker_dump_all_heap_capacities(), locator_dump_class_names(), MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_DIAGDB, NO_ERROR, NULL, OPTION_STRING_TABLE, output_file, PRINT_AND_LOG_ERR_MSG, prm_get_name(), PRM_ID_DISABLE_VACUUM, PRM_ID_FORCE_RESTART_TO_SKIP_RECOVERY, PRM_ID_JAVA_STORED_PROCEDURE, sysprm_set_force(), thread_get_thread_entry_info(), TRUE, util_log_write_errid(), utility_get_option_bool_value(), utility_get_option_int_value(), utility_get_option_string_table_size(), utility_get_option_string_value(), and xlog_dump().
int dump_tz (UTIL_FUNCTION_ARG * arg_map)
Definition at line 4113 of file util_sa.c.
References ARG_FILE_LINE, UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, assert, basename(), DUMP_TZ_COUNTRIES_S, DUMP_TZ_DUMP_SUM_S, DUMP_TZ_LEAP_SEC_S, DUMP_TZ_MSG_ID_OUT_OF_RANGE, DUMP_TZ_MSG_USAGE, DUMP_TZ_ZONE_ID_S, DUMP_TZ_ZONES_S, ER_ARG_OUT_OF_RANGE, ER_ERROR_SEVERITY, er_set(), MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_SET_DUMP_TZ, NO_ERROR, NULL, tz_data::timezone_count, tz_get_data(), tz_load(), tz_unload(), tzc_dump_countries(), tzc_dump_leap_sec(), tzc_dump_one_timezone(), tzc_dump_summary(), tzc_dump_timezones(), utility_get_option_bool_value(), and utility_get_option_string_value().
int dumplocale (UTIL_FUNCTION_ARG * arg_map)
Definition at line 2289 of file util_sa.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, assert, basename(), DUMPLOCALE_ALPHABET_ALL_CASING, DUMPLOCALE_ALPHABET_LOWER_L, DUMPLOCALE_ALPHABET_LOWER_S, DUMPLOCALE_ALPHABET_S, DUMPLOCALE_ALPHABET_UPPER_L, DUMPLOCALE_ALPHABET_UPPER_S, DUMPLOCALE_CALENDAR_S, DUMPLOCALE_COLLATION_S, DUMPLOCALE_CONSOLE_CONV_S, DUMPLOCALE_END_VALUE_S, DUMPLOCALE_IDENTIFIER_ALPHABET_S, DUMPLOCALE_INPUT_PATH_S, DUMPLOCALE_IS_ALPHABET, DUMPLOCALE_IS_ALPHABET_LOWER, DUMPLOCALE_IS_ALPHABET_UPPER, DUMPLOCALE_IS_CALENDAR, DUMPLOCALE_IS_COLLATION_CP_ORDER, DUMPLOCALE_IS_COLLATION_WEIGHT_ORDER, DUMPLOCALE_IS_IDENTIFIER_ALPHABET, DUMPLOCALE_IS_IDENTIFIER_ALPHABET_LOWER, DUMPLOCALE_IS_IDENTIFIER_ALPHABET_UPPER, DUMPLOCALE_IS_NORMALIZATION, DUMPLOCALE_IS_NUMBERING, DUMPLOCALE_IS_TEXT_CONV, DUMPLOCALE_MSG_INCOMPAT_INPUT_SEL, DUMPLOCALE_MSG_INVALID_CP_RANGE, DUMPLOCALE_MSG_INVALID_LOCALE, DUMPLOCALE_MSG_USAGE, DUMPLOCALE_NORMALIZATION_S, DUMPLOCALE_NUMBERING_S, DUMPLOCALE_START_VALUE_S, DUMPLOCALE_WEIGHT_ORDER_S, ER_LOC_GEN, ER_LOC_INIT, error(), free_and_init, i, text_conversion::init_conv_func, lang_load_library(), lang_locale_data_load_from_lib(), locale_file::lib_file, LOC_LOCALE_STR_SIZE, locale_check_and_set_default_files(), locale_dump(), locale_dump_lib_collations(), locale_get_cfg_locales(), locale_file::locale_name, LOG_LOCALE_ERROR, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_DUMPLOCALE, NO_ERROR, NULL, OPTION_STRING_TABLE, strdup(), strlen, lang_locale_data::txt_conv, util_log_write_errid(), utility_get_option_bool_value(), utility_get_option_int_value(), utility_get_option_string_table_size(), utility_get_option_string_value(), and UTIL_FUNCTION_ARG::valid_arg.
int estimatedb_data (UTIL_FUNCTION_ARG * arg_map)
Referenced by patchdb().
int estimatedb_hash (UTIL_FUNCTION_ARG * arg_map)
int estimatedb_index (UTIL_FUNCTION_ARG * arg_map)
Referenced by patchdb().
FILE* fopen_ex (const char * filename, const char * type)
Definition at line 322 of file util_common.c.
Referenced by extract_classes_to_file(), extract_indexes_to_file(), extract_objects(), extract_triggers_to_file(), load_console_conv_data(), load_ducet(), load_unicode_data(), loaddb_internal(), locale_check_and_set_default_files(), locale_get_cfg_locales(), locale_prepare_C_file(), locale_save_to_C_file(), tzc_check_new_package_validity(), tzc_export_timezone_dot_c(), tzc_load_backward_zones(), tzc_load_countries(), tzc_load_leap_secs(), tzc_load_rule_file(), tzc_load_zone_names(), and xml_parser_exec().
int gen_tz (UTIL_FUNCTION_ARG * arg_map)
Definition at line 3924 of file util_sa.c.
References ARG_FILE_LINE, UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, assert, AU_DISABLE_PASSWORDS, basename(), cfg_free_directory(), cfg_read_directory(), check_database_name(), UTIL_FUNCTION_ARG::command_name, db_abort_transaction(), DB_CLIENT_TYPE_ADMIN_UTILITY, db_commit_transaction(), db_error_string(), db_login(), db_name, db_restart(), db_set_client_type(), db_shutdown(), envvar_tzdata_dir_file(), ER_ALL_FINAL, ER_ERROR_SEVERITY, er_final(), er_init(), ER_NEVER_EXIT, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), GEN_TZ_INPUT_FOLDER_S, GEN_TZ_MODE_S, GEN_TZ_MSG_INVALID_MODE, GEN_TZ_MSG_USAGE, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_SET_GEN_TZ, database_info::name, database_info::next, NO_ERROR, NULL, OPTION_STRING_TABLE, put_timezone_checksum(), strlen, TRUE, TZ_CHECKSUM_SIZE, TZ_GEN_TYPE_EXTEND, TZ_GEN_TYPE_NEW, TZ_GEN_TYPE_UPDATE, and utility_get_option_string_value().
int genlocale (UTIL_FUNCTION_ARG * arg_map)
Definition at line 2059 of file util_sa.c.
References ARG_FILE_LINE, UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, assert, basename(), UTIL_FUNCTION_ARG::command_name, db_error_string(), er_errid(), ER_ERROR_SEVERITY, er_init(), ER_LOC_GEN, ER_NEVER_EXIT, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, GENLOCALE_INPUT_PATH_S, GENLOCALE_MSG_INVALID_LOCALE, GENLOCALE_MSG_USAGE, GENLOCALE_VERBOSE_S, i, lang_init_builtin(), locale_file::ldml_file, locale_check_and_set_default_files(), locale_compile_locale(), locale_destroy_data(), locale_free_shared_data(), locale_get_cfg_locales(), locale_mark_duplicate_collations(), locale_prepare_C_file(), locale_save_all_to_C_file(), LOG_LOCALE_ERROR, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_GENLOCALE, NO_ERROR, NULL, OPTION_STRING_TABLE, PRINT_AND_LOG_ERR_MSG, strdup(), strlen, util_log_write_errid(), utility_get_option_bool_value(), utility_get_option_string_table_size(), utility_get_option_string_value(), and UTIL_FUNCTION_ARG::valid_arg.
int installdb (UTIL_FUNCTION_ARG * arg_map)
Definition at line 1117 of file util_sa.c.
References ARG_FILE_LINE, UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), boot_soft_rename(), cfg_add_db(), cfg_delete_db(), cfg_find_db(), cfg_free_directory(), cfg_read_directory(), cfg_write_directory(), check_database_name(), UTIL_FUNCTION_ARG::command_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_commit_transaction(), db_error_string(), db_login(), db_name, db_restart(), db_set_client_type(), db_shutdown(), ER_BO_DATABASE_EXISTS, ER_ERROR_SEVERITY, er_init(), ER_NEVER_EXIT, er_set(), FALSE, INSTALL_FILE_PATH_S, INSTALL_LOG_PATH_S, INSTALL_SERVER_NAME_S, INSTALLDB_MSG_USAGE, LOB_PATH_DEFAULT_PREFIX, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_INSTALLDB, NO_ERROR, NULL, OPTION_STRING_TABLE, PATH_SEPARATOR, PRINT_AND_LOG_ERR_MSG, prm_get_name(), PRM_ID_JAVA_STORED_PROCEDURE, strdup(), sysprm_set_force(), TRUE, util_log_write_errid(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int killtran (UTIL_FUNCTION_ARG * arg_map)
Definition at line 1842 of file util_cs.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), check_database_name(), UTIL_FUNCTION_ARG::command_name, database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_error_string(), db_login(), db_restart(), db_set_client_type(), db_shutdown(), dump_trantb(), ER_AU_INVALID_PASSWORD, er_init(), ER_NEVER_EXIT, error(), kill_transactions(), KILLTRAN_DBA_PASSWORD_S, KILLTRAN_DISPLAY_INFORMATION_S, KILLTRAN_DISPLAY_QUERY_INFO_S, KILLTRAN_FORCE_S, KILLTRAN_KILL_HOST_NAME_S, KILLTRAN_KILL_PROGRAM_NAME_S, KILLTRAN_KILL_SQL_ID_S, KILLTRAN_KILL_TRANSACTION_INDEX_S, KILLTRAN_KILL_USER_NAME_S, KILLTRAN_MSG_DBA_PASSWORD, KILLTRAN_MSG_INVALID_TRANINDEX, KILLTRAN_MSG_MANY_ARGS, KILLTRAN_MSG_NOT_IN_STANDALONE, KILLTRAN_MSG_USAGE, logtb_free_trans_info(), logtb_get_trans_info(), MAX_KILLTRAN_INDEX_LIST_NUM, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_KILLTRAN, NO_ERROR, NULL, OPTION_STRING_TABLE, parse_int(), PRINT_AND_LOG_ERR_MSG, strlen, TRANDUMP_QUERY_INFO, TRANDUMP_SUMMARY, TRUE, util_log_write_errid(), util_log_write_errstr(), utility_get_option_bool_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int loaddb_user (UTIL_FUNCTION_ARG * arg_map)
Definition at line 927 of file load_db.c.
References loaddb_internal().
int lockdb (UTIL_FUNCTION_ARG * arg_map)
Definition at line 1203 of file util_cs.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), check_database_name(), UTIL_FUNCTION_ARG::command_name, database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_error_string(), db_login(), db_restart(), db_set_client_type(), db_set_isolation(), db_shutdown(), er_init(), ER_NEVER_EXIT, lock_dump(), LOCK_OUTPUT_FILE_S, LOCKDB_MSG_BAD_OUTPUT, LOCKDB_MSG_NOT_IN_STANDALONE, LOCKDB_MSG_USAGE, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_LOCKDB, NO_ERROR, NULL, OPTION_STRING_TABLE, output_file, PRINT_AND_LOG_ERR_MSG, TRAN_READ_COMMITTED, TRUE, util_log_write_errid(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int mqueueldb (UTIL_FUNCTION_ARG * arg_map)
int optimizedb (UTIL_FUNCTION_ARG * arg_map)
Definition at line 1349 of file util_sa.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), check_database_name(), UTIL_FUNCTION_ARG::command_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_commit_transaction(), db_error_string(), db_find_class(), db_login(), db_name, db_restart(), db_set_client_type(), db_shutdown(), er_init(), ER_NEVER_EXIT, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_OPTIMIZEDB, NO_ERROR, NULL, OPTIMIZE_CLASS_NAME_S, OPTIMIZEDB_MSG_USAGE, OPTION_STRING_TABLE, PRINT_AND_LOG_ERR_MSG, prm_get_name(), PRM_ID_JAVA_STORED_PROCEDURE, sm_update_all_statistics(), sm_update_statistics(), STATS_WITH_SAMPLING, sysprm_set_force(), TRUE, util_log_write_errid(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int paramdump (UTIL_FUNCTION_ARG * arg_map)
Definition at line 2206 of file util_cs.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), check_database_name(), UTIL_FUNCTION_ARG::command_name, database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_error_string(), db_login(), db_restart(), db_set_client_type(), db_shutdown(), er_init(), ER_NEVER_EXIT, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_PARAMDUMP, NO_ERROR, NULL, OPTION_STRING_TABLE, output_file, PARAMDUMP_BOTH_S, PARAMDUMP_MSG_BAD_OUTPUT, PARAMDUMP_MSG_CLIENT_PARAMETER, PARAMDUMP_MSG_SERVER_PARAMETER, PARAMDUMP_MSG_STANDALONE_PARAMETER, PARAMDUMP_MSG_USAGE, PARAMDUMP_OUTPUT_FILE_S, PRINT_AND_LOG_ERR_MSG, prm_get_name(), PRM_ID_JAVA_STORED_PROCEDURE, sysprm_dump_parameters(), sysprm_dump_server_parameters(), SYSPRM_LOAD_ALL, sysprm_load_and_init(), sysprm_set_force(), TRUE, util_log_write_errid(), utility_get_option_bool_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int patchdb (UTIL_FUNCTION_ARG * arg_map)
Definition at line 1672 of file util_sa.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, basename(), boot_emergency_patch(), check_database_name(), UTIL_FUNCTION_ARG::command_name, db_error_string(), db_name, db_set_page_size(), DB_TYPE_BIT, DB_TYPE_CHAR, DB_TYPE_NCHAR, DB_TYPE_VARBIT, DB_TYPE_VARCHAR, DB_TYPE_VARNCHAR, ER_ALL_FINAL, er_final(), er_init(), ER_NEVER_EXIT, estimatedb_data(), estimatedb_index(), ESTIMATEDB_INDEX_BAD_ARGUMENTS, ESTIMATEDB_INDEX_BAD_KEYLENGTH, ESTIMATEDB_INDEX_BAD_KEYTYPE, ESTIMATEDB_INDEX_MSG_AVG_KEYSIZE, ESTIMATEDB_INDEX_MSG_BLT_NPAGES, ESTIMATEDB_INDEX_MSG_BLT_WRS_NPAGES, ESTIMATEDB_INDEX_MSG_INPUT, ESTIMATEDB_INDEX_MSG_INSTANCES, ESTIMATEDB_INDEX_MSG_KEYTYPE, ESTIMATEDB_INDEX_MSG_NPAGES, ESTIMATEDB_INDEX_MSG_NUMBER_KEYS, ESTIMATEDB_INDEX_MSG_USAGE, pr_type::id, IO_DEFAULT_PAGE_SIZE, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_SET_ESTIMATEDB_INDEX, MSGCAT_UTIL_SET_PATCHDB, NO_ERROR, NULL, OPTION_STRING_TABLE, PATCH_RECREATE_LOG_S, PATCHDB_MSG_USAGE, tp_domain::precision, pt_string_to_db_domain(), sysprm_load_and_init(), tp_final(), tp_init(), tp_valid_indextype(), tsc_init(), tp_domain::type, utility_get_option_bool_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int plandump (UTIL_FUNCTION_ARG * arg_map)
Definition at line 2105 of file util_cs.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), check_database_name(), UTIL_FUNCTION_ARG::command_name, database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_error_string(), db_login(), db_restart(), db_set_client_type(), db_shutdown(), er_init(), ER_NEVER_EXIT, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_PLANDUMP, NO_ERROR, NULL, OPTION_STRING_TABLE, output_file, PLANDUMP_DROP_S, PLANDUMP_MSG_BAD_OUTPUT, PLANDUMP_MSG_NOT_IN_STANDALONE, PLANDUMP_MSG_USAGE, PLANDUMP_OUTPUT_FILE_S, PRINT_AND_LOG_ERR_MSG, qmgr_drop_all_query_plans(), qmgr_dump_query_plans(), TRUE, util_log_write_errid(), utility_get_option_bool_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int prestartldb (UTIL_FUNCTION_ARG * arg_map)
int renamedb (UTIL_FUNCTION_ARG * arg_map)
Definition at line 1026 of file util_sa.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), boot_soft_rename(), check_database_name(), check_new_database_name(), UTIL_FUNCTION_ARG::command_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_commit_transaction(), db_error_string(), db_login(), db_restart(), db_set_client_type(), db_shutdown(), er_init(), ER_NEVER_EXIT, FALSE, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_RENAMEDB, NO_ERROR, NULL, OPTION_STRING_TABLE, PRINT_AND_LOG_ERR_MSG, prm_get_name(), PRM_ID_JAVA_STORED_PROCEDURE, PRM_ID_PB_NBUFFERS, RENAME_CONTROL_FILE_S, RENAME_DELETE_BACKUP_S, RENAME_EXTENTED_VOLUME_PATH_S, RENAMEDB_MSG_USAGE, RENAMEDB_VOLEXT_PATH_INVALID, RENAMEDB_VOLS_TOFROM_PATHS_FILE_INVALID, sysprm_set_force(), TRUE, util_log_write_errid(), utility_get_option_bool_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int restartevnt (UTIL_FUNCTION_ARG * arg_map)
int restoredb (UTIL_FUNCTION_ARG * arg_map)
Definition at line 908 of file util_sa.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, bo_restart_arg::backuppath, basename(), boot_shutdown_server(), UTIL_FUNCTION_ARG::command_name, database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_error_string(), db_login(), db_set_client_type(), ER_ALL_FINAL, er_init(), ER_NEVER_EXIT, bo_restart_arg::is_restore_from_backup, bo_restart_arg::keys_file_path, bo_restart_arg::level, log_default_input_for_archive_log_location, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_RESTOREDB, bo_restart_arg::newvolpath, NO_ERROR, NULL, NULL_TRAN_INDEX, OPTION_STRING_TABLE, parse_up_to_date(), PRINT_AND_LOG_ERR_MSG, print_backup_info(), bo_restart_arg::printtoc, prm_get_name(), PRM_ID_JAVA_STORED_PROCEDURE, RESTORE_BACKUP_FILE_PATH_S, RESTORE_KEYS_FILE_PATH_S, RESTORE_LEVEL_S, RESTORE_LIST_S, RESTORE_OUTPUT_FILE_S, RESTORE_PARTIAL_RECOVERY_S, bo_restart_arg::restore_slave, RESTORE_UP_TO_DATE_S, bo_restart_arg::restore_upto_bktime, RESTORE_USE_DATABASE_LOCATION_PATH_S, RESTOREDB_MSG_BAD_DATE, RESTOREDB_MSG_FAILURE, RESTOREDB_MSG_USAGE, bo_restart_arg::stopat, strlen, sysprm_set_force(), util_log_write_errid(), utility_get_option_bool_value(), utility_get_option_int_value(), utility_get_option_string_table_size(), utility_get_option_string_value(), and bo_restart_arg::verbose_file.
int restoreslave (UTIL_FUNCTION_ARG * arg_map)
Definition at line 3736 of file util_sa.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, bo_restart_arg::backuppath, basename(), boot_shutdown_server(), check_ha_db_and_node_list(), UTIL_FUNCTION_ARG::command_name, database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_commit_transaction(), bo_restart_arg::db_creation, db_datetime_to_string(), db_error_string(), db_localdatetime(), db_login(), db_restart(), db_set_client_type(), db_shutdown(), delete_all_ha_apply_info(), delete_all_slave_ha_apply_info(), ER_ALL_FINAL, er_init(), ER_NEVER_EXIT, insert_ha_apply_info(), bo_restart_arg::is_restore_from_backup, bo_restart_arg::keys_file_path, bo_restart_arg::level, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_GENERIC_SERVICE_PROPERTY_FAIL, MSGCAT_UTIL_SET_RESTORESLAVE, bo_restart_arg::newvolpath, NO_ERROR, NULL, NULL_TRAN_INDEX, log_lsa::offset, OPTION_STRING_TABLE, log_lsa::pageid, PRINT_AND_LOG_ERR_MSG, print_backup_info(), bo_restart_arg::printtoc, prm_get_name(), PRM_ID_JAVA_STORED_PROCEDURE, bo_restart_arg::restart_repl_lsa, RESTORE_KEYS_FILE_PATH_S, bo_restart_arg::restore_slave, bo_restart_arg::restore_upto_bktime, RESTORESLAVE_BACKUP_FILE_PATH_S, RESTORESLAVE_LIST_S, RESTORESLAVE_MASTER_HOST_NAME_S, RESTORESLAVE_MSG_FAILURE, RESTORESLAVE_MSG_HA_CATALOG_FAIL, RESTORESLAVE_MSG_INVAILD_OPTIONS, RESTORESLAVE_MSG_INVAILD_STATE, RESTORESLAVE_MSG_USAGE, RESTORESLAVE_OUTPUT_FILE_S, RESTORESLAVE_SOURCE_STATE_S, RESTORESLAVE_USE_DATABASE_LOCATION_PATH_S, bo_restart_arg::stopat, SYSPRM_LOAD_ALL, sysprm_load_and_init(), sysprm_set_force(), TRUE, util_log_write_errid(), utility_get_option_bool_value(), utility_get_option_string_table_size(), utility_get_option_string_value(), and bo_restart_arg::verbose_file.
int shutdownldb (UTIL_FUNCTION_ARG * arg_map)
int spacedb (UTIL_FUNCTION_ARG * arg_map)
Definition at line 844 of file util_cs.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, ASSERT_ERROR, AU_DISABLE_PASSWORDS, basename(), boot_get_lob_path(), check_database_name(), UTIL_FUNCTION_ARG::command_name, database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_error_string(), db_login(), DB_PERMANENT_DATA_PURPOSE, DB_PERMANENT_VOLTYPE, db_restart(), db_set_client_type(), db_shutdown(), er_init(), ER_NEVER_EXIT, ER_WARNING_SEVERITY, free_and_init, i, IO_PAGESIZE, LOG_PAGESIZE, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_SPACEDB, netcl_spacedb(), NO_ERROR, NULL, spacedb_all::nvols, OPTION_STRING_TABLE, output_file, PRINT_AND_LOG_ERR_MSG, prm_get_name(), PRM_ID_JAVA_STORED_PROCEDURE, PRM_ID_PB_NBUFFERS, SPACE_OUTPUT_FILE_S, SPACE_PURPOSE_S, SPACE_SIZE_UNIT_S, SPACE_SUMMARIZE_S, SPACEDB_ALL_COUNT, SPACEDB_FILE_COUNT, SPACEDB_MSG_ALL_HEADER_PAGES, SPACEDB_MSG_ALL_HEADER_SIZE, SPACEDB_MSG_BAD_OUTPUT, SPACEDB_MSG_FILES_FORMAT, SPACEDB_MSG_FILES_HEADER_PAGES, SPACEDB_MSG_FILES_HEADER_SIZE, SPACEDB_MSG_FILES_TITLE, SPACEDB_MSG_PERM_PERM_FORMAT, SPACEDB_MSG_USAGE, SPACEDB_MSG_VOLS_HEADER_PAGES, SPACEDB_MSG_VOLS_HEADER_SIZE, SPACEDB_MSG_VOLS_PERM_PERM_FORMAT, SPACEDB_MSG_VOLS_PERM_TEMP_FORMAT, SPACEDB_MSG_VOLS_TEMP_TEMP_FORMAT, SPACEDB_MSG_VOLS_TITLE, SPACEDB_OUTPUT_TITLE, SPACEDB_OUTPUT_TITLE_LOB, SPACEDB_SIZE_UNIT_GBYTES, SPACEDB_SIZE_UNIT_HUMAN_READABLE, SPACEDB_SIZE_UNIT_MBYTES, SPACEDB_SIZE_UNIT_PAGE, SPACEDB_SIZE_UNIT_TBYTES, SPACEDB_TO_SIZE_ARG, SPACEDB_TOTAL_ALL, sysprm_set_force(), TRUE, util_byte_to_size_string(), util_log_write_errid(), utility_get_option_bool_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
Referenced by file_tracker_item_spacedb().
int statdump (UTIL_FUNCTION_ARG * arg_map)
Definition at line 2323 of file util_cs.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), check_database_name(), UTIL_FUNCTION_ARG::command_name, database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_error_string(), db_get_system_parameters(), db_login(), db_restart(), db_set_client_type(), db_shutdown(), ER_FAILED, er_init(), ER_NEVER_EXIT, histo_print_global_stats(), histo_start(), histo_stop(), intr_handler(), is_Sigint_caught, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_STATDUMP, NO_ERROR, NULL, OPTION_STRING_TABLE, os_set_signal_handler(), output_file, PRINT_AND_LOG_ERR_MSG, print_timestamp(), prm_get_name(), PRM_ID_HA_MODE, STATDUMP_CUMULATIVE_S, STATDUMP_INTERVAL_S, STATDUMP_MSG_BAD_OUTPUT, STATDUMP_MSG_NOT_IN_STANDALONE, STATDUMP_MSG_USAGE, STATDUMP_OUTPUT_FILE_S, STATDUMP_SUBSTR_S, cubregex::substr(), TRUE, util_log_write_errid(), utility_get_option_bool_value(), utility_get_option_int_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int synccoll_force (void)
Definition at line 3411 of file util_sa.c.
References AU_DISABLE, AU_ENABLE, boot_add_collations(), CT_COLLATION_NAME, db_find_class(), db_truncate_class(), NO_ERROR, and NULL.
Referenced by main(), and synccolldb().
int synccolldb (UTIL_FUNCTION_ARG * arg_map)
Definition at line 2582 of file util_sa.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), check_database_name(), UTIL_FUNCTION_ARG::command_name, CT_COLLATION_NAME, db_abort_transaction(), DB_CLIENT_TYPE_ADMIN_UTILITY, db_commit_transaction(), db_error_string(), db_login(), db_name, db_restart(), db_set_client_type(), db_shutdown(), er_init(), ER_NEVER_EXIT, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_SYNCCOLLDB, NO_ERROR, NULL, OPTION_STRING_TABLE, PRINT_AND_LOG_ERR_MSG, prm_get_name(), PRM_ID_JAVA_STORED_PROCEDURE, synccoll_check(), SYNCCOLL_CHECK_S, synccoll_force(), SYNCCOLL_FORCESYNC_S, SYNCCOLLDB_MSG_SYNC_ABORT, SYNCCOLLDB_MSG_SYNC_CONTINUE, SYNCCOLLDB_MSG_SYNC_OK, SYNCCOLLDB_MSG_USAGE, sysprm_set_force(), TRUE, util_log_write_errid(), utility_get_option_bool_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int tde (UTIL_FUNCTION_ARG * arg_map)
Definition at line 3716 of file util_cs.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, basename(), check_database_name(), UTIL_FUNCTION_ARG::command_name, CTIME_MAX, database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_commit_transaction(), db_error_string(), db_login(), db_restart(), db_set_client_type(), db_shutdown(), ER_AU_INVALID_PASSWORD, er_init(), ER_NEVER_EXIT, error(), fileio_mount(), KILLTRAN_DBA_PASSWORD_S, LOG_DBTDE_KEYS_VOLID, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_TDE, NO_ERROR, NULL, NULL_VOLDES, OPTION_STRING_TABLE, PRINT_AND_LOG_ERR_MSG, strlen, tde_add_mk(), TDE_CHANGE_KEY_S, tde_change_mk_on_server(), tde_create_mk(), TDE_DELETE_KEY_S, tde_delete_mk(), tde_dump_mks(), TDE_GENERATE_KEY_S, tde_get_mk_file_path(), tde_get_mk_info(), TDE_MASTER_KEY_LENGTH, TDE_MSG_DBA_PASSWORD, TDE_MSG_MK_CHANGED, TDE_MSG_MK_CHANGING, TDE_MSG_MK_DELETED, TDE_MSG_MK_GENERATED, TDE_MSG_MK_SET_ON_DATABASE_DELETE, TDE_MSG_NO_SET_MK_INFO, TDE_MSG_USAGE, TDE_PRINT_KEY_VALUE_S, tde_print_mk(), TDE_SHOW_KEYS_S, TRUE, util_log_write_errid(), utility_get_option_bool_value(), utility_get_option_int_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int tranlist (UTIL_FUNCTION_ARG * arg_map)
Definition at line 1672 of file util_cs.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, au_is_dba_group_member(), Au_user, basename(), check_database_name(), UTIL_FUNCTION_ARG::command_name, database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_error_string(), db_login(), db_restart(), db_restart_ex(), db_set_client_type(), db_shutdown(), dump_trantb(), ER_AU_INVALID_PASSWORD, er_init(), ER_NEVER_EXIT, error(), logtb_free_trans_info(), logtb_get_trans_info(), MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_TRANLIST, NO_ERROR, NULL, trans_info::num_trans, OPTION_STRING_TABLE, PRINT_AND_LOG_ERR_MSG, trans_info::tran, TRANDUMP_FULL_INFO, TRANDUMP_SUMMARY, tranlist_cmp_f(), TRANLIST_FULL_SQL_S, TRANLIST_MSG_INVALID_SORT_KEY, TRANLIST_MSG_NOT_DBA_USER, TRANLIST_MSG_NOT_IN_STANDALONE, TRANLIST_MSG_USAGE, TRANLIST_MSG_USER_PASSWORD, TRANLIST_REVERSE_S, tranlist_Sort_column, tranlist_Sort_desc, TRANLIST_SORT_KEY_S, TRANLIST_SUMMARY_S, TRUE, util_log_write_errid(), util_log_write_errstr(), utility_get_option_bool_value(), utility_get_option_int_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int unloaddb (UTIL_FUNCTION_ARG * arg_map)
Definition at line 93 of file unloaddb.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, au_fetch_class(), AU_FETCH_READ, AU_RESTORE, AU_SAVE_AND_ENABLE, AU_SELECT, cached_pages, extract_context::clear_schema_workspace(), UTIL_FUNCTION_ARG::command_name, create_filename_indexes(), create_filename_schema(), create_filename_trigger(), database_name, datafile_per_class, DB_CLIENT_TYPE_ADMIN_UTILITY, db_error_code(), db_error_string(), DB_FETCH_READ, db_restart_ex(), db_set_lock_timeout(), db_shutdown(), DB_SIZEOF, extract_context::do_auth, do_objects, do_schema, ER_AU_INVALID_PASSWORD, er_init(), ER_NEVER_EXIT, error(), est_size, extract_context::exec_name, extract_classes_to_file(), extract_indexes_to_file(), extract_objects(), extract_triggers_to_file(), FOLLOW_ATTRIBUTE_ORDER, FOLLOW_STORAGE_ORDER, free_and_init, get_requested_classes(), hash_filename, i, ignore_err_flag, include_references, input_filename, lo_count, locator_decache_all_lock_instances(), locator_free_list_mops(), locator_get_all_mops(), MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_GENERIC_NO_MEM, MSGCAT_UTIL_SET_UNLOADDB, NO_ERROR, NULL, list_mops::num, OPTION_STRING_TABLE, output_dirname, output_prefix, PRINT_AND_LOG_ERR_MSG, prm_get_bool_value(), prm_get_integer_value(), prm_get_name(), PRM_ID_JAVA_STORED_PROCEDURE, PRM_ID_UNLOADDB_IGNORE_ERROR, PRM_ID_UNLOADDB_LOCK_TIMEOUT, required_class_only, sm_ch_name(), sm_Root_class_mop, extract_context::storage_order, sysprm_set_force(), UNLOAD_CACHED_PAGES_S, UNLOAD_DATA_ONLY_S, UNLOAD_DATAFILE_PER_CLASS_S, UNLOAD_ESTIMATED_SIZE_S, UNLOAD_HASH_FILE_S, UNLOAD_INCLUDE_REFERENCE_S, UNLOAD_INPUT_CLASS_FILE_S, UNLOAD_INPUT_CLASS_ONLY_S, UNLOAD_KEEP_STORAGE_ORDER_S, UNLOAD_LO_COUNT_S, UNLOAD_OUTPUT_PATH_S, UNLOAD_OUTPUT_PREFIX_S, UNLOAD_PASSWORD_S, UNLOAD_SCHEMA_ONLY_S, unload_usage(), UNLOAD_USE_DELIMITER_S, UNLOAD_USER_S, UNLOAD_VERBOSE_S, UNLOADDB_MSG_PASSWORD_PROMPT, util_log_write_errid(), util_log_write_errstr(), utility_get_option_bool_value(), utility_get_option_int_value(), utility_get_option_string_table_size(), utility_get_option_string_value(), verbose_flag, and ws_find().
void util_admin_usage (const char * argv0)
Definition at line 122 of file util_sa.c.
References basename(), MSGCAT_UTIL_GENERIC_ADMIN_USAGE, and utility_get_generic_message().
void util_admin_version (const char * argv0)
Definition at line 139 of file util_sa.c.
References basename(), MSGCAT_UTIL_GENERIC_VERSION, and utility_get_generic_message().
int util_byte_to_size_string (char * buf, size_t len, UINT64 size_num)
Definition at line 955 of file util_common.c.
References _dtoa, ER_FAILED, i, NO_ERROR, NULL, ONE_K, and strlen.
Referenced by btree_scan_for_show_index_capacity(), createdb(), prm_print(), spacedb(), and sysprm_print_sysprm_value().
void util_free_ha_conf (HA_CONF * ha_conf)
Definition at line 651 of file util_common.c.
References _ha_config::db_names, free_and_init, i, _ha_config::node_conf, node_name, NULL, _ha_config::num_node_conf, and util_free_string_array().
Referenced by check_ha_db_and_node_list(), process_heartbeat(), and util_make_ha_conf().
int util_get_ha_mode_for_sa_utils (void)
Definition at line 872 of file util_common.c.
References prm_get_integer_value(), and PRM_ID_HA_MODE_FOR_SA_UTILS_ONLY.
Referenced by css_get_required_conn_num_for_ha(), process_heartbeat_start(), process_heartbeat_stop(), process_heartbeat_util(), process_server(), us_hb_applylogdb_start(), us_hb_copylogdb_start(), and us_hb_server_start().
int util_get_num_of_ha_nodes (const char * node_list)
Definition at line 478 of file util_common.c.
References NULL, util_free_string_array(), and util_split_ha_node().
Referenced by css_get_required_conn_num_for_ha().
int util_get_table_list_from_file (char * fname, dynamic_array * darray)
Definition at line 1226 of file util_common.c.
References da_add(), ER_GENERIC_ERROR, i, MSGCAT_UTIL_GENERIC_FILEOPEN_ERROR, MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_GENERIC_NO_MEM, NO_ERROR, NULL, p, SM_MAX_IDENTIFIER_LENGTH, and util_log_write_errid().
Referenced by checkdb(), and checksumdb().
bool util_is_localhost (char * host)
Definition at line 418 of file util_common.c.
References are_hostnames_equal(), CUB_MAXHOSTNAMELEN, and GETHOSTNAME.
Referenced by check_ha_db_and_node_list(), us_hb_applylogdb_start(), us_hb_applylogdb_stop(), us_hb_copylogdb_start(), and us_hb_copylogdb_stop().
int util_make_ha_conf (HA_CONF * ha_conf)
Definition at line 694 of file util_common.c.
References _node_config::apply_max_mem_size, assert_release, _node_config::copy_log_base, _node_config::copy_sync_mode, copylogdb_keyword(), _ha_config::db_names, ER_GENERIC_ERROR, error(), i, mode, MSGCAT_UTIL_GENERIC_INVALID_PARAMETER, MSGCAT_UTIL_GENERIC_NO_MEM, NO_ERROR, _ha_config::node_conf, _node_config::node_name, NULL, _ha_config::num_node_conf, prm_get_name(), PRM_ID_HA_COPY_SYNC_MODE, strdup(), util_free_ha_conf(), util_free_string_array(), util_get_ha_parameters(), util_is_replica_node(), util_split_ha_db(), util_split_ha_node(), util_split_ha_sync(), and utility_get_generic_message().
Referenced by check_ha_db_and_node_list(), and process_heartbeat().
int util_msec_to_time_string (char * buf, size_t len, INT64 msec_num)
Definition at line 1112 of file util_common.c.
References ER_FAILED, error(), NO_ERROR, NULL, and ONE_SEC.
Referenced by prm_print(), and sysprm_print_sysprm_value().
void util_print_deprecated (const char * option)
Definition at line 1205 of file util_common.c.
References MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_DEPRECATED, MSGCAT_UTIL_SET_GENERIC, and NULL.
Referenced by addvoldb(), and createdb().
void util_redirect_stdout_to_null (void)
Definition at line 885 of file util_common.c.
Referenced by applylogdb(), and copylogdb().
int util_size_string_to_byte (UINT64 * size_num, const char * size_str)
Definition at line 1027 of file util_common.c.
References ER_FAILED, NO_ERROR, NULL, and util_size_to_byte().
Referenced by addvoldb(), createdb(), and sysprm_generate_new_value().
int util_time_string_to_msec (INT64 * msec_num, char * time_str)
Definition at line 1155 of file util_common.c.
References ER_FAILED, NO_ERROR, NULL, and util_time_to_msec().
Referenced by sysprm_generate_new_value().
const char* utility_get_generic_message (int message_index)
Definition at line 88 of file util_common.c.
References MSGCAT_CATALOG_UTILS, msgcat_message(), and MSGCAT_UTIL_SET_GENERIC.
Referenced by check_database_name_local(), check_volume_name(), load_properties(), print_message(), util_admin_usage(), util_admin_version(), util_get_ha_parameters(), util_log_write_errid(), and util_make_ha_conf().
INT64 utility_get_option_bigint_value (UTIL_ARG_MAP * arg_map, int arg_ch)
Definition at line 294 of file util_common.c.
References UTIL_ARG_MAP::arg_value, UTIL_ARG_MAP::l, and utility_get_option_index().
Referenced by applyinfo(), and copylogdb().
bool utility_get_option_bool_value (UTIL_ARG_MAP * arg_map, int arg_ch)
Definition at line 245 of file util_common.c.
References UTIL_ARG_MAP::i, and utility_get_option_index().
Referenced by acldb(), addvoldb(), applyinfo(), backupdb(), changemode(), checkdb(), checksumdb(), compactdb(), copydb(), createdb(), deletedb(), diagdb(), dump_tz(), dumplocale(), genlocale(), get_loaddb_args(), killtran(), loaddb_internal(), paramdump(), patchdb(), plandump(), renamedb(), restoredb(), restoreslave(), spacedb(), statdump(), synccolldb(), tde(), tranlist(), unloaddb(), and vacuumdb().
int utility_get_option_int_value (UTIL_ARG_MAP * arg_map, int arg_ch)
Definition at line 227 of file util_common.c.
References UTIL_ARG_MAP::arg_value, UTIL_ARG_MAP::i, and utility_get_option_index().
Referenced by applyinfo(), applylogdb(), backupdb(), changemode(), checksumdb(), compactdb(), createdb(), diagdb(), dumplocale(), get_loaddb_args(), loaddb_internal(), restoredb(), statdump(), tde(), tranlist(), and unloaddb().
int utility_get_option_string_table_size (UTIL_ARG_MAP * arg_map)
Definition at line 305 of file util_common.c.
References UTIL_ARG_MAP::num_strings, OPTION_STRING_TABLE, utility_get_option_index(), and UTIL_ARG_MAP::value_info.
Referenced by acldb(), addvoldb(), alterdbhost(), applyinfo(), applylogdb(), backupdb(), changemode(), checkdb(), checksumdb(), compactdb(), copydb(), copylogdb(), createdb(), deletedb(), diagdb(), dumplocale(), genlocale(), installdb(), killtran(), lockdb(), optimizedb(), paramdump(), patchdb(), plandump(), renamedb(), restoredb(), restoreslave(), spacedb(), statdump(), synccolldb(), tde(), tranlist(), unloaddb(), and vacuumdb().
char* utility_get_option_string_value (UTIL_ARG_MAP * arg_map, int arg_ch, int index)
Definition at line 266 of file util_common.c.
References NULL, UTIL_ARG_MAP::num_strings, OPTION_STRING_TABLE, UTIL_ARG_MAP::p, and utility_get_option_index().
Referenced by acldb(), addvoldb(), alterdbhost(), applyinfo(), applylogdb(), backupdb(), changemode(), checkdb(), checksumdb(), compactdb(), copydb(), copylogdb(), createdb(), deletedb(), diagdb(), dump_tz(), dumplocale(), gen_tz(), genlocale(), get_loaddb_args(), installdb(), killtran(), lockdb(), optimizedb(), paramdump(), patchdb(), plandump(), renamedb(), restoredb(), restoreslave(), spacedb(), statdump(), synccolldb(), tde(), tranlist(), unloaddb(), and vacuumdb().
int utility_initialize (void)
Definition at line 69 of file util_common.c.
References ER_BO_CANNOT_ACCESS_MESSAGE_CATALOG, er_init(), ER_NEVER_EXIT, msgcat_init(), NO_ERROR, NULL, and PRINT_AND_LOG_ERR_MSG.
Referenced by csql(), and main().
int utility_keyword_search (UTIL_KEYWORD * keywords, int * keyval_p, char ** keystr_p)
Definition at line 352 of file util_common.c.
References ER_FAILED, UTIL_KEYWORD::keystr, UTIL_KEYWORD::keyval, NO_ERROR, and NULL.
Referenced by changemode_keyword(), and copylogdb_keyword().
int utility_keyword_value (UTIL_KEYWORD * keywords, int * keyval_p, char ** keystr_p)
int utility_localtime (const time_t * ts, struct tm * result)
Definition at line 390 of file util_common.c.
References NULL.
Referenced by csql_do_session_cmd(), and print_timestamp().
int vacuumdb (UTIL_FUNCTION_ARG * arg_map)
Definition at line 3560 of file util_cs.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), check_database_name(), UTIL_FUNCTION_ARG::command_name, cvacuum(), database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, DB_CLIENT_TYPE_SKIP_VACUUM_ADMIN_CSQL, db_error_string(), db_login(), db_restart(), db_set_client_type(), db_set_isolation(), db_shutdown(), er_get_msglog_filename(), er_init(), ER_NEVER_EXIT, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_VACUUMDB, NO_ERROR, NULL, OPTION_STRING_TABLE, output_file, PRINT_AND_LOG_ERR_MSG, prm_get_name(), PRM_ID_DISABLE_VACUUM, PRM_ID_JAVA_STORED_PROCEDURE, sysprm_set_force(), TRAN_READ_COMMITTED, TRUE, util_log_write_errid(), util_log_write_errstr(), utility_get_option_bool_value(), utility_get_option_string_table_size(), utility_get_option_string_value(), vacuum_dump(), VACUUM_DUMP_S, VACUUM_OUTPUT_FILE_S, VACUUMDB_MSG_BAD_OUTPUT, VACUUMDB_MSG_CLIENT_SERVER_NOT_AVAILABLE, VACUUMDB_MSG_FAILED, and VACUUMDB_MSG_USAGE.