CUBRID Engine: src/executables/util_support.h File Reference
util_support.h File Reference
#include "utility.h"
Functions
char * utility_make_getopt_optstring (const GETOPT_LONG *opt_array, char *buf)
int utility_load_library (DSO_HANDLE *handle, const char *lib_path)
int utility_load_symbol (DSO_HANDLE library_handle, DSO_HANDLE *symbol_handle, const char *symbol_name)
void utility_load_print_error (FILE *fp)
int util_parse_argument (UTIL_MAP *util_map, int argc, char **argv)
void util_hide_password (char *arg)
Function Documentation
void util_hide_password (char * arg)
Definition at line 374 of file util_support.c.
References NULL, and strlen.
Referenced by main(), and util_parse_argument().
int util_parse_argument (UTIL_MAP * util_map, int argc, char ** argv)
Definition at line 186 of file util_support.c.
References ER_FAILED, getopt_long(), UTIL_MAP::getopt_long, NO_ERROR, optarg, optind, util_get_option_name(), util_hide_password(), util_is_password_argument(), util_parse_string_table(), util_put_option_value(), UTIL_MAP::utility_index, and utility_make_getopt_optstring().
Referenced by main().
int utility_load_library (DSO_HANDLE * handle, const char * lib_path)
Definition at line 77 of file util_support.c.
References ER_GENERIC_ERROR, NO_ERROR, NULL, UTILITY_INIT_FUNC_NAME, and utility_load_symbol().
Referenced by main(), print_admin_usage(), print_admin_version(), utility_csql_print(), and utility_csql_usage().
void utility_load_print_error (FILE * fp)
Definition at line 134 of file util_support.c.
References error(), and NULL.
Referenced by main(), print_admin_usage(), print_admin_version(), utility_csql_print(), and utility_csql_usage().
int utility_load_symbol (DSO_HANDLE library_handle, DSO_HANDLE * symbol_handle, const char * symbol_name)
Definition at line 115 of file util_support.c.
References ER_GENERIC_ERROR, NO_ERROR, and NULL.
Referenced by main(), print_admin_usage(), print_admin_version(), utility_csql_print(), utility_csql_usage(), and utility_load_library().
char* utility_make_getopt_optstring (const GETOPT_LONG * opt_array, char * buf)
Definition at line 49 of file util_support.c.
References option::has_arg, i, option::name, p, and option::val.
Referenced by main(), us_hb_status_get_options(), us_hb_stop_get_options(), us_hb_util_get_options(), and util_parse_argument().