CUBRID Engine: src/executables/util_front.c File Reference
util_front.c File Reference
#include <stdio.h>
#include <string.h>
#include <malloc.h>
#include <errno.h>
#include <unistd.h>
#include "utility.h"
#include "error_code.h"
Classes
struct ARG_MAP_TABLE
struct UTIL_MAP_TABLE
Functions
static char * get_long_arg_by_old_arg (char *old_arg, ARG_MAP_TABLE *match_table)
static int convert_argv (int argc, char **argv, ARG_MAP_TABLE *match_table)
int main (int argc, char **argv)
Variables
static ARG_MAP_TABLE ua_Create_map []
static ARG_MAP_TABLE ua_Rename_map []
static ARG_MAP_TABLE ua_Copy_map []
static ARG_MAP_TABLE ua_Delete_map []
static ARG_MAP_TABLE ua_Backup_map []
static ARG_MAP_TABLE ua_Restore_map []
static ARG_MAP_TABLE ua_Addvol_map []
static ARG_MAP_TABLE ua_Space_map []
static ARG_MAP_TABLE ua_Lock_map []
static ARG_MAP_TABLE ua_Optimize_map []
static ARG_MAP_TABLE ua_Install_map []
static ARG_MAP_TABLE ua_Diag_map []
static ARG_MAP_TABLE ua_Check_map []
static ARG_MAP_TABLE ua_Tranlist_map []
static ARG_MAP_TABLE ua_Killtran_map []
static ARG_MAP_TABLE ua_Load_map []
static ARG_MAP_TABLE ua_Unload_map []
static ARG_MAP_TABLE ua_Compact_map []
static ARG_MAP_TABLE ua_Sqlx_map []
static ARG_MAP_TABLE us_Commdb_map []
static ARG_MAP_TABLE ua_Acldb_map []
UTIL_MAP_TABLE ua_Util_table []
Function Documentation
static int convert_argv (int argc, char ** argv, ARG_MAP_TABLE * match_table) static
Definition at line 329 of file util_front.c.
References ER_FAILED, get_long_arg_by_old_arg(), i, NO_ERROR, and NULL.
Referenced by main().
static char* get_long_arg_by_old_arg (char * old_arg, ARG_MAP_TABLE * match_table) static
Definition at line 308 of file util_front.c.
References i, ARG_MAP_TABLE::long_arg, NULL, and ARG_MAP_TABLE::old_arg.
Referenced by convert_argv().
int main (int argc, char ** argv)
Definition at line 365 of file util_front.c.
References UTIL_MAP_TABLE::app_name, basename(), convert_argv(), i, NO_ERROR, NULL, program_name, UTIL_ADMIN_NAME, UTIL_COMMDB_NAME, UTIL_CSQL_NAME, UTIL_CUBRID, UTIL_OLD_COMMDB_NAME, and UTIL_SQLX_NAME.
Variable Documentation
ARG_MAP_TABLE ua_Acldb_map[] static
Initial value:
= {
  {"-r", "--" ACLDB_RELOAD_L},
  {0, 0}
}
Definition at line 263 of file util_front.c.
ARG_MAP_TABLE ua_Addvol_map[] static
Initial value:
= {
  {"-n", "--" ADDVOL_VOLUME_NAME_L},
  {"-f", "--" ADDVOL_FILE_PATH_L},
  {"-c", "--" ADDVOL_COMMENT_L},
  {"-pu", "--" ADDVOL_PURPOSE_L},
  {"-sa", "--" ADDVOL_SA_MODE_L},
  {"-cs", "--" ADDVOL_CS_MODE_L},
  {0, 0}
}
Definition at line 108 of file util_front.c.
ARG_MAP_TABLE ua_Backup_map[] static
Initial value:
= {
  {"-l", "--" BACKUP_DESTINATION_PATH_L},
  {"-r", "--" BACKUP_REMOVE_ARCHIVE_L},
  {"-lv", "--" BACKUP_LEVEL_L},
  {"-o", "--" BACKUP_OUTPUT_FILE_L},
  {"-sa", "--" BACKUP_SA_MODE_L},
  {"-cs", "--" BACKUP_CS_MODE_L},
  {"-nc", "--" BACKUP_NO_CHECK_L},
  {"-mt", "--" BACKUP_THREAD_COUNT_L},
  {"-zip", "--" BACKUP_COMPRESS_L},
  {"-ni", "--" BACKUP_EXCEPT_ACTIVE_LOG_L},
  {"-c", (char *) -1},
  {0, 0}
}
Definition at line 82 of file util_front.c.
ARG_MAP_TABLE ua_Check_map[] static
Initial value:
= {
  {"-sa", "--" CHECK_SA_MODE_L},
  {"-cs", "--" CHECK_CS_MODE_L},
  {"-r", "--" CHECK_REPAIR_L},
  {0, 0}
}
Definition at line 159 of file util_front.c.
ARG_MAP_TABLE ua_Compact_map[] static
Initial value:
= {
  {"-v", "--" COMPACT_VERBOSE_L},
  {0, 0}
}
Definition at line 230 of file util_front.c.
ARG_MAP_TABLE ua_Copy_map[] static
Initial value:
= {
  {"-s", "--" COPY_SERVER_NAME_L},
  {"-f", "--" COPY_FILE_PATH_L},
  {"-l", "--" COPY_LOG_PATH_L},
  {"-e", "--" COPY_EXTENTED_VOLUME_PATH_L},
  {"-tf", "--" COPY_CONTROL_FILE_L},
  {"-r", "--" COPY_REPLACE_L},
  {"-m", "--" COPY_DELETE_SOURCE_L},
  {"-B", "--" COPY_LOB_PATH_L},
  {0, 0}
}
Definition at line 64 of file util_front.c.
ARG_MAP_TABLE ua_Create_map[] static
Initial value:
= {
  {"-p", "--" CREATE_PAGES_L},
  {"-c", "--" CREATE_COMMENT_L},
  {"-f", "--" CREATE_FILE_PATH_L},
  {"-l", "--" CREATE_LOG_PATH_L},
  {"-s", "--" CREATE_SERVER_NAME_L},
  {"-r", "--" CREATE_REPLACE_L},
  {"-mv", "--" CREATE_MORE_VOLUME_FILE_L},
  {"-u", "--" CREATE_USER_DEFINITION_FILE_L},
  {"-i", "--" CREATE_CSQL_INITIALIZATION_FILE_L},
  {"-o", "--" CREATE_OUTPUT_FILE_L},
  {"-v", "--" CREATE_VERBOSE_L},
  {"-n", "--" CREATE_CHARSET_L},
  {"-lp", "--" CREATE_LOG_PAGE_COUNT_L},
  {"-ps", "--" CREATE_PAGE_SIZE_L},
  {0, 0}
}
Definition at line 39 of file util_front.c.
ARG_MAP_TABLE ua_Delete_map[] static
Initial value:
= {
  {"-o", "--" DELETE_OUTPUT_FILE_L},
  {"-f", "--" DELETE_DELETE_BACKUP_L},
  {0, 0}
}
Definition at line 76 of file util_front.c.
ARG_MAP_TABLE ua_Diag_map[] static
Initial value:
= {
  {"-d", "--" DIAG_DUMP_TYPE_L},
  {0, 0}
}
Definition at line 154 of file util_front.c.
ARG_MAP_TABLE ua_Install_map[] static
Initial value:
= {
  {"-s", "--" INSTALL_SERVER_NAME_L},
  {"-f", "--" INSTALL_FILE_PATH_L},
  {"-l", "--" INSTALL_LOG_PATH_L},
  {0, 0}
}
Definition at line 147 of file util_front.c.
ARG_MAP_TABLE ua_Killtran_map[] static
Initial value:
= {
  {"-t", "--" KILLTRAN_KILL_TRANSACTION_INDEX_L},
  {"-u", "--" KILLTRAN_KILL_USER_NAME_L},
  {"-h", "--" KILLTRAN_KILL_HOST_NAME_L},
  {"-pg", "--" KILLTRAN_KILL_PROGRAM_NAME_L},
  {"-s", "--" KILLTRAN_KILL_SQL_ID_L},
  {"-p", "--" KILLTRAN_DBA_PASSWORD_L},
  {"-d", "--" KILLTRAN_DISPLAY_INFORMATION_L},
  {"-q", "--" KILLTRAN_DISPLAY_QUERY_INFO_L},
  {"-v", "--" KILLTRAN_FORCE_L},
  {0, 0}
}
Definition at line 177 of file util_front.c.
ARG_MAP_TABLE ua_Load_map[] static
Initial value:
= {
  {"-u", "--" LOAD_USER_L},
  {"-p", "--" LOAD_PASSWORD_L},
  {"-s", "--" LOAD_CHECK_ONLY_L},
  {"-l", "--" LOAD_LOAD_ONLY_L},
  {"-e", "--" LOAD_ESTIMATED_SIZE_L},
  {"-v", "--" LOAD_VERBOSE_L},
  {"-ns", "--" LOAD_NO_STATISTICS_L},
  {"-c", "--" LOAD_PERIODIC_COMMIT_L},
  {"-noref", "--" LOAD_NO_OID_L},
  {"-sf", "--" LOAD_SCHEMA_FILE_L},
  {"-if", "--" LOAD_INDEX_FILE_L},
  {"-tf", "--" LOAD_TRIGGER_FILE_L},
  {"-of", "--" LOAD_DATA_FILE_L},
  {"-ef", "--" LOAD_ERROR_CONTROL_FILE_L},
  {"-nl", "--" LOAD_IGNORE_LOGGING_L},
  {"-vc", (char *) -1},
  {0, 0}
}
Definition at line 190 of file util_front.c.
ARG_MAP_TABLE ua_Lock_map[] static
Initial value:
= {
  {"-o", "--" LOCK_OUTPUT_FILE_L},
  {0, 0}
}
Definition at line 137 of file util_front.c.
ARG_MAP_TABLE ua_Optimize_map[] static
Initial value:
= {
  {"-c", "--" OPTIMIZE_CLASS_NAME_L},
  {0, 0}
}
Definition at line 142 of file util_front.c.
ARG_MAP_TABLE ua_Rename_map[] static
Initial value:
= {
  {"-e", "--" RENAME_EXTENTED_VOLUME_PATH_L},
  {"-tf", "--" RENAME_CONTROL_FILE_L},
  {"-f", "--" RENAME_DELETE_BACKUP_L},
  {0, 0}
}
Definition at line 57 of file util_front.c.
ARG_MAP_TABLE ua_Restore_map[] static
Initial value:
= {
  {"-d", "--" RESTORE_UP_TO_DATE_L},
  {"-t", "--" RESTORE_LIST_L},
  {"-l", "--" RESTORE_BACKUP_FILE_PATH_L},
  {"-lv", "--" RESTORE_LEVEL_L},
  {"-p", "--" RESTORE_PARTIAL_RECOVERY_L},
  {"-o", "--" RESTORE_OUTPUT_FILE_L},
  {"-n", "--" RESTORE_USE_DATABASE_LOCATION_PATH_L},
  {0, 0}
}
Definition at line 97 of file util_front.c.
ARG_MAP_TABLE ua_Space_map[] static
Initial value:
= {
  {"-o", "--" SPACE_OUTPUT_FILE_L},
  {"-sa", "--" SPACE_SA_MODE_L},
  {"-cs", "--" SPACE_CS_MODE_L},
  {0, 0}
}
Definition at line 130 of file util_front.c.
ARG_MAP_TABLE ua_Sqlx_map[] static
Initial value:
= {
  {"-sa", "--" CSQL_SA_MODE_L},
  {"-cs", "--" CSQL_CS_MODE_L},
  {"-u", "--" CSQL_USER_L},
  {"-p", "--" CSQL_PASSWORD_L},
  {"-e", "--" CSQL_ERROR_CONTINUE_L},
  {"-i", "--" CSQL_INPUT_FILE_L},
  {"-o", "--" CSQL_OUTPUT_FILE_L},
  {"-s", "--" CSQL_SINGLE_LINE_L},
  {"-c", "--" CSQL_COMMAND_L},
  {"-lo", "--" CSQL_LINE_OUTPUT_L},
  {"-noac", "--" CSQL_NO_AUTO_COMMIT_L},
  {"-nopager", "--" CSQL_NO_PAGER_L},
  {"-nosl", "--" CSQL_NO_SINGLE_LINE_L},
  {"-co", (char *) -1},
  {0, 0}
}
Definition at line 235 of file util_front.c.
ARG_MAP_TABLE ua_Tranlist_map[] static
Initial value:
= {
  {"-s", "--" TRANLIST_SUMMARY_L},
  {"-k", "--" TRANLIST_SORT_KEY_L},
  {"-r", "--" TRANLIST_REVERSE_L},
  {0, 0}
}
Definition at line 166 of file util_front.c.
ARG_MAP_TABLE ua_Unload_map[] static
Initial value:
= {
  {"-i", "--" UNLOAD_INPUT_CLASS_FILE_L},
  {"-ir", "--" UNLOAD_INCLUDE_REFERENCE_L},
  {"-io", "--" UNLOAD_INPUT_CLASS_ONLY_L},
  {"-loc", "--" UNLOAD_LO_COUNT_L},
  {"-e", "--" UNLOAD_ESTIMATED_SIZE_L},
  {"-n", "--" UNLOAD_CACHED_PAGES_L},
  {"-od", "--" UNLOAD_OUTPUT_PATH_L},
  {"-so", "--" UNLOAD_SCHEMA_ONLY_L},
  {"-oo", "--" UNLOAD_DATA_ONLY_L},
  {"-p", "--" UNLOAD_OUTPUT_PREFIX_L},
  {"-f", "--" UNLOAD_HASH_FILE_L},
  {"-v", "--" UNLOAD_VERBOSE_L},
  {"-di", "--" UNLOAD_USE_DELIMITER_L},
  {"-sa", "--" UNLOAD_SA_MODE_L},
  {"-cs", "--" UNLOAD_CS_MODE_L},
  {"-dpc", "--" UNLOAD_DATAFILE_PER_CLASS_L},
  {0, 0}
}
Definition at line 210 of file util_front.c.
UTIL_MAP_TABLE ua_Util_table[]
Initial value:
= {
  {"createdb", UTIL_OPTION_CREATEDB, ua_Create_map},
  {"renamedb", UTIL_OPTION_RENAMEDB, ua_Rename_map},
  {"copydb", UTIL_OPTION_COPYDB, ua_Copy_map},
  {"deletedb", UTIL_OPTION_DELETEDB, ua_Delete_map},
  {"backupdb", UTIL_OPTION_BACKUPDB, ua_Backup_map},
  {"restoredb", UTIL_OPTION_RESTOREDB, ua_Restore_map},
  {"addvoldb", UTIL_OPTION_ADDVOLDB, ua_Addvol_map},
  {"spacedb", UTIL_OPTION_SPACEDB, ua_Space_map},
  {"lockdb", UTIL_OPTION_LOCKDB, ua_Lock_map},
  {"optimizedb", UTIL_OPTION_OPTIMIZEDB, ua_Optimize_map},
  {"installdb", UTIL_OPTION_INSTALLDB, ua_Install_map},
  {"diagdb", UTIL_OPTION_DIAGDB, ua_Diag_map},
  {"checkdb", UTIL_OPTION_CHECKDB, ua_Check_map},
  {"killtran", UTIL_OPTION_KILLTRAN, ua_Killtran_map},
  {"loaddb", UTIL_OPTION_LOADDB, ua_Load_map},
  {"unloaddb", UTIL_OPTION_UNLOADDB, ua_Unload_map},
  {"compactdb", UTIL_OPTION_COMPACTDB, ua_Compact_map},
  {"acldb", UTIL_OPTION_ACLDB, ua_Acldb_map},
  {"tranlist", UTIL_OPTION_TRANLIST, ua_Tranlist_map},
  {0, 0, 0}
}
Definition at line 275 of file util_front.c.
ARG_MAP_TABLE us_Commdb_map[] static
Initial value:
= {
  {"-P", "--" COMMDB_SERVER_LIST_L},
  {"-O", "--" COMMDB_ALL_LIST_L},
  {"-S", "--" COMMDB_SHUTDOWN_SERVER_L},
  {"-I", "--" COMMDB_SHUTDOWN_SERVER_L},
  {"-A", "--" COMMDB_SHUTDOWN_ALL_L},
  {"-h", "--" COMMDB_HOST_L},
  {0, 0}
}
Definition at line 253 of file util_front.c.