CUBRID Engine: src/executables/util_admin.c File Reference
util_admin.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "cubrid_getopt.h"
#include "utility.h"
#include "error_code.h"
#include "util_support.h"
#include "file_io.h"
Macros
#define ALTERDBHOST_HOST_S 'h'
Functions
static const char * util_get_library_name (int utility_index)
static int util_get_function_name (const char **function_name, const char *utility_name)
static int util_get_utility_index (int *utility_index, const char *utility_name)
static void print_admin_usage (const char *argv0)
static void print_admin_version (const char *argv0)
int main (int argc, char *argv[])
Variables
static UTIL_ARG_MAP ua_Create_Option_Map []
static GETOPT_LONG ua_Create_Option []
static UTIL_ARG_MAP ua_Rename_Option_Map []
static GETOPT_LONG ua_Rename_Option []
static UTIL_ARG_MAP ua_Copy_Option_Map []
static GETOPT_LONG ua_Copy_Option []
static UTIL_ARG_MAP ua_Delete_Option_Map []
static GETOPT_LONG ua_Delete_Option []
static UTIL_ARG_MAP ua_Backup_Option_Map []
static GETOPT_LONG ua_Backup_Option []
static UTIL_ARG_MAP ua_Restore_Option_Map []
static GETOPT_LONG ua_Restore_Option []
static UTIL_ARG_MAP ua_Addvol_Option_Map []
static GETOPT_LONG ua_Addvol_Option []
static UTIL_ARG_MAP ua_Space_Option_Map []
static GETOPT_LONG ua_Space_Option []
static UTIL_ARG_MAP ua_Lock_Option_Map []
static GETOPT_LONG ua_Lock_Option []
static UTIL_ARG_MAP ua_Acl_Option_Map []
static GETOPT_LONG ua_Acl_Option []
static UTIL_ARG_MAP ua_Optimize_Option_Map []
static GETOPT_LONG ua_Optimize_Option []
static UTIL_ARG_MAP ua_Install_Option_Map []
static GETOPT_LONG ua_Install_Option []
static UTIL_ARG_MAP ua_Diag_Option_Map []
static GETOPT_LONG ua_Diag_Option []
static UTIL_ARG_MAP ua_Patch_Option_Map []
static GETOPT_LONG ua_Patch_Option []
static UTIL_ARG_MAP ua_Check_Option_Map []
static GETOPT_LONG ua_Check_Option []
static UTIL_ARG_MAP ua_Alterdbhost_Option_Map []
static GETOPT_LONG ua_Alterdbhost_Option []
static UTIL_ARG_MAP ua_Plandump_Option_Map []
static GETOPT_LONG ua_Plandump_Option []
static UTIL_ARG_MAP ua_Killtran_Option_Map []
static GETOPT_LONG ua_Killtran_Option []
static UTIL_ARG_MAP ua_Tranlist_Option_Map []
static GETOPT_LONG ua_Tranlist_Option []
static UTIL_ARG_MAP ua_Load_Option_Map []
static GETOPT_LONG ua_Load_Option []
static UTIL_ARG_MAP ua_Unload_Option_Map []
static GETOPT_LONG ua_Unload_Option []
static UTIL_ARG_MAP ua_Compact_Option_Map []
static GETOPT_LONG ua_Compact_Option []
static UTIL_ARG_MAP ua_Paramdump_Option_Map []
static GETOPT_LONG ua_Paramdump_Option []
static UTIL_ARG_MAP ua_Statdump_Option_Map []
static GETOPT_LONG ua_Statdump_Option []
static UTIL_ARG_MAP ua_Changemode_Option_Map []
static GETOPT_LONG ua_Changemode_Option []
static UTIL_ARG_MAP ua_Copylog_Option_Map []
static GETOPT_LONG ua_Copylog_Option []
static UTIL_ARG_MAP ua_Applylog_Option_Map []
static GETOPT_LONG ua_Applylog_Option []
static UTIL_ARG_MAP ua_ApplyInfo_Option_Map []
static GETOPT_LONG ua_ApplyInfo_Option []
static UTIL_ARG_MAP ua_GenLocale_Map []
static GETOPT_LONG ua_GenLocale_Option []
static UTIL_ARG_MAP ua_DumpLocale_Map []
static GETOPT_LONG ua_DumpLocale_Option []
static UTIL_ARG_MAP ua_SyncCollDB_Map []
static GETOPT_LONG ua_SyncCollDB_Option []
static UTIL_ARG_MAP ua_GenTz_Map []
static GETOPT_LONG ua_GenTz_Option []
static UTIL_ARG_MAP ua_DumpTz_Map []
static GETOPT_LONG ua_DumpTz_Option []
static UTIL_ARG_MAP ua_RestoreSlave_Option_Map []
static GETOPT_LONG ua_RestoreSlave_Option []
static UTIL_ARG_MAP ua_Vacuum_Option_Map []
static GETOPT_LONG ua_Vacuum_Option []
static UTIL_ARG_MAP ua_Checksum_Option_Map []
static GETOPT_LONG ua_Checksum_Option []
static UTIL_ARG_MAP ua_Tde_Option_Map []
static GETOPT_LONG ua_Tde_Option []
static UTIL_MAP ua_Utility_Map []
Macro Definition Documentation
#define ALTERDBHOST_HOST_S 'h'
Definition at line 376 of file util_admin.c.
Referenced by alterdbhost().
Function Documentation
int main (int argc, char * argv[])
Definition at line 986 of file util_admin.c.
References UTIL_MAP::arg_map, UTIL_FUNCTION_ARG::arg_map, argv, UTIL_FUNCTION_ARG::argv, UTIL_FUNCTION_ARG::argv0, UTIL_FUNCTION_ARG::command_name, NO_ERROR, print_admin_usage(), print_admin_version(), print_usage(), util_get_function_name(), util_get_library_name(), util_get_utility_index(), util_parse_argument(), utility_load_library(), utility_load_print_error(), utility_load_symbol(), UTIL_MAP::utility_name, and UTIL_FUNCTION_ARG::valid_arg.
static void print_admin_usage (const char * argv0) static
Definition at line 920 of file util_admin.c.
References LIB_UTIL_SA_NAME, NULL, UTILITY_ADMIN_USAGE_FUNC_NAME, utility_load_library(), utility_load_print_error(), and utility_load_symbol().
Referenced by main().
static void print_admin_version (const char * argv0) static
Definition at line 953 of file util_admin.c.
References LIB_UTIL_SA_NAME, NULL, UTILITY_ADMIN_VERSION_FUNC_NAME, utility_load_library(), utility_load_print_error(), and utility_load_symbol().
Referenced by main().
static int util_get_function_name (const char ** function_name, const char * utility_name) static
Definition at line 1111 of file util_admin.c.
References ER_GENERIC_ERROR, UTIL_MAP::function_name, i, NO_ERROR, and UTIL_MAP::utility_index.
Referenced by main().
static const char * util_get_library_name (int utility_index) static
Definition at line 1061 of file util_admin.c.
References UTIL_ARG_MAP::arg_ch, UTIL_MAP::arg_map, CS_ONLY, HIDDEN_CS_MODE_S, i, LIB_UTIL_CS_NAME, LIB_UTIL_SA_NAME, NULL, UTIL_ARG_MAP::p, SA_CS, SA_ONLY, TDE, UTIL_MAP::utility_type, and VACUUMDB.
Referenced by main().
static int util_get_utility_index (int * utility_index, const char * utility_name) static
Definition at line 1131 of file util_admin.c.
References ER_GENERIC_ERROR, i, NO_ERROR, and UTIL_MAP::utility_index.
Referenced by main().
Variable Documentation
GETOPT_LONG ua_Acl_Option[] static
Initial value:
= {
  {ACLDB_RELOAD_L, 0, 0, ACLDB_RELOAD_S},
  {0, 0, 0, 0}
}
Definition at line 280 of file util_admin.c.
UTIL_ARG_MAP ua_Acl_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {0}, {0}},
  {ACLDB_RELOAD_S, {ARG_BOOLEAN}, {0}},
  {0, {0}, {0}}
}
Definition at line 274 of file util_admin.c.
GETOPT_LONG ua_Addvol_Option[] static
Initial value:
= {
  {ADDVOL_VOLUME_NAME_L, 1, 0, ADDVOL_VOLUME_NAME_S},
  {ADDVOL_VOLUME_SIZE_L, 1, 0, ADDVOL_VOLUME_SIZE_S},
  {ADDVOL_FILE_PATH_L, 1, 0, ADDVOL_FILE_PATH_S},
  {ADDVOL_COMMENT_L, 1, 0, ADDVOL_COMMENT_S},
  {ADDVOL_PURPOSE_L, 1, 0, ADDVOL_PURPOSE_S},
  {ADDVOL_SA_MODE_L, 0, 0, ADDVOL_SA_MODE_S},
  {ADDVOL_CS_MODE_L, 0, 0, ADDVOL_CS_MODE_S},
  {ADDVOL_MAX_WRITESIZE_IN_SEC_L, 1, 0, ADDVOL_MAX_WRITESIZE_IN_SEC_S},
  {0, 0, 0, 0}
}
Definition at line 207 of file util_admin.c.
UTIL_ARG_MAP ua_Addvol_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {0}, {0}},
  {ADDVOL_VOLUME_NAME_S, {ARG_STRING}, {0}},
  {ADDVOL_VOLUME_SIZE_S, {ARG_STRING}, {0}},
  {ADDVOL_FILE_PATH_S, {ARG_STRING}, {0}},
  {ADDVOL_COMMENT_S, {ARG_STRING}, {0}},
  {ADDVOL_PURPOSE_S, {ARG_STRING}, {(void *) "generic"}},
  {ADDVOL_SA_MODE_S, {ARG_BOOLEAN}, {0}},
  {ADDVOL_CS_MODE_S, {ARG_BOOLEAN}, {0}},
  {ADDVOL_MAX_WRITESIZE_IN_SEC_S, {ARG_STRING}, {0}},
  {0, {0}, {0}}
}
Definition at line 194 of file util_admin.c.
GETOPT_LONG ua_Alterdbhost_Option[] static
Initial value:
= {
  {ALTERDBHOST_HOST_L, 1, 0, ALTERDBHOST_HOST_S},
  {0, 0, 0, 0}
}
Definition at line 384 of file util_admin.c.
UTIL_ARG_MAP ua_Alterdbhost_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {0}, {0}},
  {ALTERDBHOST_HOST_S, {ARG_STRING}, {0}},
  {0, {0}, {0}}
}
Definition at line 378 of file util_admin.c.
GETOPT_LONG ua_ApplyInfo_Option[] static
Initial value:
= {
  {APPLYINFO_COPIED_LOG_PATH_L, 1, 0, APPLYINFO_COPIED_LOG_PATH_S},
  {APPLYINFO_PAGE_L, 1, 0, APPLYINFO_PAGE_S},
  {APPLYINFO_REMOTE_NAME_L, 1, 0, APPLYINFO_REMOTE_NAME_S},
  {APPLYINFO_APPLIED_INFO_L, 0, 0, APPLYINFO_APPLIED_INFO_S},
  {APPLYINFO_VERBOSE_L, 0, 0, APPLYINFO_VERBOSE_S},
  {APPLYINFO_INTERVAL_L, 1, 0, APPLYINFO_INTERVAL_S},
  {0, 0, 0, 0}
}
Definition at line 668 of file util_admin.c.
UTIL_ARG_MAP ua_ApplyInfo_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {ARG_INTEGER}, {0}},
  {APPLYINFO_COPIED_LOG_PATH_S, {ARG_STRING}, {0}},
  {APPLYINFO_PAGE_S, {ARG_BIGINT}, {(void *) (-1L)}},
  {APPLYINFO_REMOTE_NAME_S, {ARG_STRING}, {0}},
  {APPLYINFO_APPLIED_INFO_S, {ARG_BOOLEAN}, {0}},
  {APPLYINFO_VERBOSE_S, {ARG_BOOLEAN}, {0}},
  {APPLYINFO_INTERVAL_S, {ARG_INTEGER}, {0}},
  {0, {0}, {0}}
}
Definition at line 657 of file util_admin.c.
GETOPT_LONG ua_Applylog_Option[] static
Initial value:
= {
  {APPLYLOG_LOG_PATH_L, 1, 0, APPLYLOG_LOG_PATH_S},
  {APPLYLOG_MAX_MEM_SIZE_L, 1, 0, APPLYLOG_MAX_MEM_SIZE_S},
  {0, 0, 0, 0}
}
Definition at line 651 of file util_admin.c.
UTIL_ARG_MAP ua_Applylog_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {ARG_INTEGER}, {0}},
  {APPLYLOG_LOG_PATH_S, {ARG_STRING}, {0}},
  {APPLYLOG_MAX_MEM_SIZE_S, {ARG_INTEGER}, {0}},
  {0, {0}, {0}}
}
Definition at line 644 of file util_admin.c.
GETOPT_LONG ua_Backup_Option[] static
Initial value:
= {
  {BACKUP_DESTINATION_PATH_L, 1, 0, BACKUP_DESTINATION_PATH_S},
  {BACKUP_REMOVE_ARCHIVE_L, 0, 0, BACKUP_REMOVE_ARCHIVE_S},
  {BACKUP_LEVEL_L, 1, 0, BACKUP_LEVEL_S},
  {BACKUP_OUTPUT_FILE_L, 1, 0, BACKUP_OUTPUT_FILE_S},
  {BACKUP_SA_MODE_L, 0, 0, BACKUP_SA_MODE_S},
  {BACKUP_CS_MODE_L, 0, 0, BACKUP_CS_MODE_S},
  {BACKUP_NO_CHECK_L, 0, 0, BACKUP_NO_CHECK_S},
  {BACKUP_THREAD_COUNT_L, 1, 0, BACKUP_THREAD_COUNT_S},
  {BACKUP_COMPRESS_L, 0, 0, BACKUP_COMPRESS_S},
  {BACKUP_EXCEPT_ACTIVE_LOG_L, 0, 0, BACKUP_EXCEPT_ACTIVE_LOG_S},
  {BACKUP_SLEEP_MSECS_L, 1, 0, BACKUP_SLEEP_MSECS_S},
  {BACKUP_SEPARATE_KEYS_L, 0, 0, BACKUP_SEPARATE_KEYS_S},
  {0, 0, 0, 0}
}
Definition at line 152 of file util_admin.c.
UTIL_ARG_MAP ua_Backup_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {0}, {0}},
  {BACKUP_DESTINATION_PATH_S, {ARG_STRING}, {0}},
  {BACKUP_OUTPUT_FILE_S, {ARG_STRING}, {0}},
  {BACKUP_REMOVE_ARCHIVE_S, {ARG_BOOLEAN}, {0}},
  {BACKUP_LEVEL_S, {ARG_INTEGER}, {(void *) FILEIO_BACKUP_FULL_LEVEL}},
  {BACKUP_SA_MODE_S, {ARG_BOOLEAN}, {0}},
  {BACKUP_CS_MODE_S, {ARG_BOOLEAN}, {0}},
  {BACKUP_NO_CHECK_S, {ARG_BOOLEAN}, {0}},
  {BACKUP_THREAD_COUNT_S, {ARG_INTEGER}, {FILEIO_BACKUP_NUM_THREADS_AUTO}},
  {BACKUP_COMPRESS_S, {ARG_BOOLEAN}, {0}},
  {BACKUP_EXCEPT_ACTIVE_LOG_S, {ARG_BOOLEAN}, {0}},
  {BACKUP_SLEEP_MSECS_S, {ARG_INTEGER}, {FILEIO_BACKUP_SLEEP_MSECS_AUTO}},
  {BACKUP_SEPARATE_KEYS_S, {ARG_BOOLEAN}, {0}},
  {0, {0}, {0}}
}
Definition at line 135 of file util_admin.c.
GETOPT_LONG ua_Changemode_Option[] static
Initial value:
= {
  {CHANGEMODE_MODE_L, 1, 0, CHANGEMODE_MODE_S},
  {CHANGEMODE_FORCE_L, 0, 0, CHANGEMODE_FORCE_S},
  {CHANGEMODE_TIMEOUT_L, 1, 0, CHANGEMODE_TIMEOUT_S},
  {0, 0, 0, 0}
}
Definition at line 622 of file util_admin.c.
UTIL_ARG_MAP ua_Changemode_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {ARG_INTEGER}, {0}},
  {CHANGEMODE_MODE_S, {ARG_STRING}, {0}},
  {CHANGEMODE_FORCE_S, {ARG_BOOLEAN}, {0}},
  {CHANGEMODE_TIMEOUT_S, {ARG_INTEGER}, {(void *) -1}},
  {0, {0}, {0}}
}
Definition at line 614 of file util_admin.c.
GETOPT_LONG ua_Check_Option[] static
Initial value:
= {
  {CHECK_SA_MODE_L, 0, 0, CHECK_SA_MODE_S},
  {CHECK_CS_MODE_L, 0, 0, CHECK_CS_MODE_S},
  {CHECK_INDEXNAME_L, 1, 0, CHECK_INDEXNAME_S},
  {CHECK_REPAIR_L, 0, 0, CHECK_REPAIR_S},
  {CHECK_INPUT_FILE_L, 1, 0, CHECK_INPUT_FILE_S},
  {CHECK_CHECK_PREV_LINK_L, 0, 0, CHECK_CHECK_PREV_LINK_S},
  {CHECK_REPAIR_PREV_LINK_L, 0, 0, CHECK_REPAIR_PREV_LINK_S},
  {CHECK_FILE_TRACKER_L, 0, 0, CHECK_FILE_TRACKER_S},
  {CHECK_HEAP_ALLHEAPS_L, 0, 0, CHECK_HEAP_ALLHEAPS_S},
  {CHECK_CAT_CONSISTENCY_L, 0, 0, CHECK_CAT_CONSISTENCY_S},
  {CHECK_BTREE_ALL_BTREES_L, 0, 0, CHECK_BTREE_ALL_BTREES_S},
  {CHECK_LC_CLASSNAMES_L, 0, 0, CHECK_LC_CLASSNAMES_S},
  {CHECK_LC_ALLENTRIES_OF_ALLBTREES_L, 0, 0,
   CHECK_LC_ALLENTRIES_OF_ALLBTREES_S},
  {0, 0, 0, 0}
}
Definition at line 357 of file util_admin.c.
UTIL_ARG_MAP ua_Check_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {0}, {0}},
  {CHECK_SA_MODE_S, {ARG_BOOLEAN}, {0}},
  {CHECK_CS_MODE_S, {ARG_BOOLEAN}, {0}},
  {CHECK_INDEXNAME_S, {ARG_STRING}, {0}},
  {CHECK_REPAIR_S, {ARG_BOOLEAN}, {0}},
  {CHECK_INPUT_FILE_S, {ARG_STRING}, {0}},
  {CHECK_CHECK_PREV_LINK_S, {ARG_BOOLEAN}, {0}},
  {CHECK_REPAIR_PREV_LINK_S, {ARG_BOOLEAN}, {0}},
  {CHECK_FILE_TRACKER_S, {ARG_BOOLEAN}, {0}},
  {CHECK_HEAP_ALLHEAPS_S, {ARG_BOOLEAN}, {0}},
  {CHECK_CAT_CONSISTENCY_S, {ARG_BOOLEAN}, {0}},
  {CHECK_BTREE_ALL_BTREES_S, {ARG_BOOLEAN}, {0}},
  {CHECK_LC_CLASSNAMES_S, {ARG_BOOLEAN}, {0}},
  {CHECK_LC_ALLENTRIES_OF_ALLBTREES_S, {ARG_BOOLEAN}, {0}},
  {0, {0}, {0}}
}
Definition at line 339 of file util_admin.c.
GETOPT_LONG ua_Checksum_Option[] static
Initial value:
= {
  {CHECKSUM_CHUNK_SIZE_L, 1, 0, CHECKSUM_CHUNK_SIZE_S},
  {CHECKSUM_RESUME_L, 0, 0, CHECKSUM_RESUME_S},
  {CHECKSUM_SLEEP_L, 1, 0, CHECKSUM_SLEEP_S},
  {CHECKSUM_CONT_ON_ERROR_L, 0, 0, CHECKSUM_CONT_ON_ERROR_S},
  {CHECKSUM_INCLUDE_CLASS_FILE_L, 1, 0, CHECKSUM_INCLUDE_CLASS_FILE_S},
  {CHECKSUM_EXCLUDE_CLASS_FILE_L, 1, 0, CHECKSUM_EXCLUDE_CLASS_FILE_S},
  {CHECKSUM_TIMEOUT_L, 1, 0, CHECKSUM_TIMEOUT_S},
  {CHECKSUM_TABLE_NAME_L, 1, 0, CHECKSUM_TABLE_NAME_S},
  {CHECKSUM_REPORT_ONLY_L, 0, 0, CHECKSUM_REPORT_ONLY_S},
  {CHECKSUM_SCHEMA_ONLY_L, 0, 0, CHECKSUM_SCHEMA_ONLY_S},
  {0, 0, 0, 0}
}
Definition at line 823 of file util_admin.c.
UTIL_ARG_MAP ua_Checksum_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {ARG_INTEGER}, {0}},
  {CHECKSUM_CHUNK_SIZE_S, {ARG_INTEGER}, {(void *) 500}},
  {CHECKSUM_RESUME_S, {ARG_BOOLEAN}, {0}},
  {CHECKSUM_SLEEP_S, {ARG_INTEGER}, {(void *) 100}},
  {CHECKSUM_CONT_ON_ERROR_S, {ARG_BOOLEAN}, {0}},
  {CHECKSUM_INCLUDE_CLASS_FILE_S, {ARG_STRING}, {0}},
  {CHECKSUM_EXCLUDE_CLASS_FILE_S, {ARG_STRING}, {0}},
  {CHECKSUM_TIMEOUT_S, {ARG_INTEGER}, {(void *) 1000}},
  {CHECKSUM_TABLE_NAME_S, {ARG_STRING}, {0}},
  {CHECKSUM_REPORT_ONLY_S, {ARG_BOOLEAN}, {0}},
  {CHECKSUM_SCHEMA_ONLY_S, {ARG_BOOLEAN}, {0}},
  {0, {0}, {0}}
}
Definition at line 808 of file util_admin.c.
GETOPT_LONG ua_Compact_Option[] static
Initial value:
= {
  {COMPACT_VERBOSE_L, 0, 0, COMPACT_VERBOSE_S},
  {COMPACT_INPUT_CLASS_FILE_L, 1, 0, COMPACT_INPUT_CLASS_FILE_S},
  {COMPACT_SA_MODE_L, 0, 0, COMPACT_SA_MODE_S},
  {COMPACT_CS_MODE_L, 0, 0, COMPACT_CS_MODE_S},
  {COMPACT_PAGES_COMMITED_ONCE_L, 1, 0, COMPACT_PAGES_COMMITED_ONCE_S},
  {COMPACT_DELETE_OLD_REPR_L, 0, 0, COMPACT_DELETE_OLD_REPR_S},
  {COMPACT_INSTANCE_LOCK_TIMEOUT_L, 1, 0, COMPACT_INSTANCE_LOCK_TIMEOUT_S},
  {COMPACT_CLASS_LOCK_TIMEOUT_L, 1, 0, COMPACT_CLASS_LOCK_TIMEOUT_S},
  {COMPACT_STANDBY_CS_MODE_L, 0, 0, COMPACT_STANDBY_CS_MODE_S},
  {0, 0, 0, 0}
}
Definition at line 567 of file util_admin.c.
UTIL_ARG_MAP ua_Compact_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {0}, {0}},
  {COMPACT_VERBOSE_S, {ARG_BOOLEAN}, {0}},
  {COMPACT_INPUT_CLASS_FILE_S, {ARG_STRING}, {0}},
  {COMPACT_SA_MODE_S, {ARG_BOOLEAN}, {0}},
  {COMPACT_CS_MODE_S, {ARG_BOOLEAN}, {0}},
  {COMPACT_PAGES_COMMITED_ONCE_S, {ARG_INTEGER}, {(void *) 10}},
  {COMPACT_DELETE_OLD_REPR_S, {ARG_BOOLEAN}, {0}},
  {COMPACT_INSTANCE_LOCK_TIMEOUT_S, {ARG_INTEGER}, {(void *) 2}},
  {COMPACT_CLASS_LOCK_TIMEOUT_S, {ARG_INTEGER}, {(void *) 10}},
  {COMPACT_STANDBY_CS_MODE_S, {ARG_BOOLEAN}, {0}},
  {0, {0}, {0}}
}
Definition at line 553 of file util_admin.c.
GETOPT_LONG ua_Copy_Option[] static
Initial value:
= {
  {COPY_SERVER_NAME_L, 1, 0, COPY_SERVER_NAME_S},
  {COPY_FILE_PATH_L, 1, 0, COPY_FILE_PATH_S},
  {COPY_LOG_PATH_L, 1, 0, COPY_LOG_PATH_S},
  {COPY_EXTENTED_VOLUME_PATH_L, 1, 0, COPY_EXTENTED_VOLUME_PATH_S},
  {COPY_CONTROL_FILE_L, 1, 0, COPY_CONTROL_FILE_S},
  {COPY_REPLACE_L, 0, 0, COPY_REPLACE_S},
  {COPY_DELETE_SOURCE_L, 0, 0, COPY_DELETE_SOURCE_S},
  {COPY_LOB_PATH_L, 1, 0, COPY_LOB_PATH_S},
  {COPY_COPY_LOB_PATH_L, 0, 0, COPY_COPY_LOB_PATH_S},
  {0, 0, 0, 0}
}
Definition at line 109 of file util_admin.c.
UTIL_ARG_MAP ua_Copy_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {0}, {0}},
  {COPY_SERVER_NAME_S, {ARG_STRING}, {0}},
  {COPY_FILE_PATH_S, {ARG_STRING}, {0}},
  {COPY_LOG_PATH_S, {ARG_STRING}, {0}},
  {COPY_EXTENTED_VOLUME_PATH_S, {ARG_STRING}, {0}},
  {COPY_CONTROL_FILE_S, {ARG_STRING}, {0}},
  {COPY_REPLACE_S, {ARG_BOOLEAN}, {0}},
  {COPY_DELETE_SOURCE_S, {ARG_BOOLEAN}, {0}},
  {COPY_LOB_PATH_S, {ARG_STRING}, {0}},
  {COPY_COPY_LOB_PATH_S, {ARG_BOOLEAN}, {0}},
  {0, {0}, {0}}
}
Definition at line 95 of file util_admin.c.
GETOPT_LONG ua_Copylog_Option[] static
Initial value:
= {
  {COPYLOG_LOG_PATH_L, 1, 0, COPYLOG_LOG_PATH_S},
  {COPYLOG_MODE_L, 1, 0, COPYLOG_MODE_S},
  {COPYLOG_START_PAGEID_L, 1, 0, COPYLOG_START_PAGEID_S},
  {0, 0, 0, 0}
}
Definition at line 637 of file util_admin.c.
UTIL_ARG_MAP ua_Copylog_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {ARG_INTEGER}, {0}},
  {COPYLOG_LOG_PATH_S, {ARG_STRING}, {0}},
  {COPYLOG_MODE_S, {ARG_STRING}, {0}},
  {COPYLOG_START_PAGEID_S, {ARG_BIGINT}, {(void *) (-2L)}},
  {0, {0}, {0}}
}
Definition at line 629 of file util_admin.c.
GETOPT_LONG ua_Create_Option[] static
Initial value:
= {
  {CREATE_PAGES_L, 1, 0, CREATE_PAGES_S},
  {CREATE_COMMENT_L, 1, 0, CREATE_COMMENT_S},
  {CREATE_FILE_PATH_L, 1, 0, CREATE_FILE_PATH_S},
  {CREATE_LOG_PATH_L, 1, 0, CREATE_LOG_PATH_S},
  {CREATE_LOB_PATH_L, 1, 0, CREATE_LOB_PATH_S},
  {CREATE_SERVER_NAME_L, 1, 0, CREATE_SERVER_NAME_S},
  {CREATE_REPLACE_L, 0, 0, CREATE_REPLACE_S},
  {CREATE_MORE_VOLUME_FILE_L, 1, 0, CREATE_MORE_VOLUME_FILE_S},
  {CREATE_USER_DEFINITION_FILE_L, 1, 0, CREATE_USER_DEFINITION_FILE_S},
  {CREATE_CSQL_INITIALIZATION_FILE_L, 1, 0,
   CREATE_CSQL_INITIALIZATION_FILE_S},
  {CREATE_OUTPUT_FILE_L, 1, 0, CREATE_OUTPUT_FILE_S},
  {CREATE_VERBOSE_L, 0, 0, CREATE_VERBOSE_S},
  {CREATE_CHARSET_L, 1, 0, CREATE_CHARSET_S},
  {CREATE_LOG_PAGE_COUNT_L, 1, 0, CREATE_LOG_PAGE_COUNT_S},
  {CREATE_PAGE_SIZE_L, 1, 0, CREATE_PAGE_SIZE_S},
  {CREATE_DB_PAGE_SIZE_L, 1, 0, CREATE_DB_PAGE_SIZE_S},
  {CREATE_DB_VOLUME_SIZE_L, 1, 0, CREATE_DB_VOLUME_SIZE_S},
  {CREATE_LOG_PAGE_SIZE_L, 1, 0, CREATE_LOG_PAGE_SIZE_S},
  {CREATE_LOG_VOLUME_SIZE_L, 1, 0, CREATE_LOG_VOLUME_SIZE_S},
  {0, 0, 0, 0}
}
Definition at line 56 of file util_admin.c.
UTIL_ARG_MAP ua_Create_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {0}, {0}},
  {CREATE_PAGES_S, {ARG_INTEGER}, {(void *) -1}},
  {CREATE_COMMENT_S, {ARG_STRING}, {0}},
  {CREATE_FILE_PATH_S, {ARG_STRING}, {0}},
  {CREATE_LOG_PATH_S, {ARG_STRING}, {0}},
  {CREATE_LOB_PATH_S, {ARG_STRING}, {0}},
  {CREATE_SERVER_NAME_S, {ARG_STRING}, {0}},
  {CREATE_REPLACE_S, {ARG_BOOLEAN}, {0}},
  {CREATE_MORE_VOLUME_FILE_S, {ARG_STRING}, {0}},
  {CREATE_USER_DEFINITION_FILE_S, {ARG_STRING}, {0}},
  {CREATE_CSQL_INITIALIZATION_FILE_S, {ARG_STRING}, {0}},
  {CREATE_OUTPUT_FILE_S, {ARG_STRING}, {0}},
  {CREATE_VERBOSE_S, {ARG_BOOLEAN}, {0}},
  {CREATE_LOG_PAGE_COUNT_S, {ARG_INTEGER}, {(void *) -1}},
  {CREATE_PAGE_SIZE_S, {ARG_INTEGER}, {(void *) -1}},
  {CREATE_DB_PAGE_SIZE_S, {ARG_STRING}, {0}},
  {CREATE_LOG_PAGE_SIZE_S, {ARG_STRING}, {0}},
  {CREATE_DB_VOLUME_SIZE_S, {ARG_STRING}, {0}},
  {CREATE_LOG_VOLUME_SIZE_S, {ARG_STRING}, {0}},
  {0, {0}, {0}}
}
Definition at line 33 of file util_admin.c.
GETOPT_LONG ua_Delete_Option[] static
Initial value:
= {
  {DELETE_OUTPUT_FILE_L, 1, 0, DELETE_OUTPUT_FILE_S},
  {DELETE_DELETE_BACKUP_L, 0, 0, DELETE_DELETE_BACKUP_S},
  {0, 0, 0, 0}
}
Definition at line 129 of file util_admin.c.
UTIL_ARG_MAP ua_Delete_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {0}, {0}},
  {DELETE_OUTPUT_FILE_S, {ARG_STRING}, {0}},
  {DELETE_DELETE_BACKUP_S, {ARG_BOOLEAN}, {0}},
  {0, {0}, {0}}
}
Definition at line 122 of file util_admin.c.
GETOPT_LONG ua_Diag_Option[] static
Initial value:
= {
  {DIAG_DUMP_TYPE_L, 1, 0, DIAG_DUMP_TYPE_S},
  {DIAG_DUMP_RECORDS_L, 0, 0, DIAG_DUMP_RECORDS_S},
  {DIAG_OUTPUT_FILE_L, 1, 0, DIAG_OUTPUT_FILE_S},
  {DIAG_EMERGENCY_L, 0, 0, DIAG_EMERGENCY_S},
  {0, 0, 0, 0}
}
Definition at line 320 of file util_admin.c.
UTIL_ARG_MAP ua_Diag_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {0}, {0}},
  {DIAG_DUMP_TYPE_S, {ARG_INTEGER}, {(void *) -1}},
  {DIAG_DUMP_RECORDS_S, {ARG_BOOLEAN}, {0}},
  {DIAG_OUTPUT_FILE_S, {ARG_STRING}, {0}},
  {DIAG_EMERGENCY_S, {ARG_BOOLEAN}, {0}},
  {0, {0}, {0}}
}
Definition at line 311 of file util_admin.c.
UTIL_ARG_MAP ua_DumpLocale_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {0}, {0}},
  {DUMPLOCALE_INPUT_PATH_S, {ARG_STRING}, {0}},
  {DUMPLOCALE_CALENDAR_S, {ARG_BOOLEAN}, {0}},
  {DUMPLOCALE_NUMBERING_S, {ARG_BOOLEAN}, {0}},
  {DUMPLOCALE_ALPHABET_S, {ARG_STRING}, {0}},
  {DUMPLOCALE_IDENTIFIER_ALPHABET_S, {ARG_STRING}, {0}},
  {DUMPLOCALE_COLLATION_S, {ARG_BOOLEAN}, {0}},
  {DUMPLOCALE_WEIGHT_ORDER_S, {ARG_BOOLEAN}, {0}},
  {DUMPLOCALE_START_VALUE_S, {ARG_INTEGER}, {0}},
  {DUMPLOCALE_END_VALUE_S, {ARG_INTEGER}, {0}},
  {DUMPLOCALE_NORMALIZATION_S, {ARG_BOOLEAN}, {0}},
  {DUMPLOCALE_CONSOLE_CONV_S, {ARG_BOOLEAN}, {0}},
  {0, {0}, {0}}
}
Definition at line 692 of file util_admin.c.
GETOPT_LONG ua_DumpLocale_Option[] static
Initial value:
= {
  {DUMPLOCALE_INPUT_PATH_L, 1, 0, DUMPLOCALE_INPUT_PATH_S},
  {DUMPLOCALE_CALENDAR_L, 0, 0, DUMPLOCALE_CALENDAR_S},
  {DUMPLOCALE_NUMBERING_L, 0, 0, DUMPLOCALE_NUMBERING_S},
  {DUMPLOCALE_ALPHABET_L, 1, 0, DUMPLOCALE_ALPHABET_S},
  {DUMPLOCALE_IDENTIFIER_ALPHABET_L, 1, 0, DUMPLOCALE_IDENTIFIER_ALPHABET_S},
  {DUMPLOCALE_COLLATION_L, 0, 0, DUMPLOCALE_COLLATION_S},
  {DUMPLOCALE_WEIGHT_ORDER_L, 0, 0, DUMPLOCALE_WEIGHT_ORDER_S},
  {DUMPLOCALE_START_VALUE_L, 1, 0, DUMPLOCALE_START_VALUE_S},
  {DUMPLOCALE_END_VALUE_L, 1, 0, DUMPLOCALE_END_VALUE_S},
  {DUMPLOCALE_NORMALIZATION_L, 0, 0, DUMPLOCALE_NORMALIZATION_S},
  {DUMPLOCALE_CONSOLE_CONV_L, 0, 0, DUMPLOCALE_CONSOLE_CONV_S},
  {0, 0, 0, 0}
}
Definition at line 708 of file util_admin.c.
UTIL_ARG_MAP ua_DumpTz_Map[] static
Initial value:
= {
  {DUMP_TZ_COUNTRIES_S, {ARG_BOOLEAN}, {0}},
  {DUMP_TZ_ZONES_S, {ARG_BOOLEAN}, {0}},
  {DUMP_TZ_ZONE_ID_S, {ARG_STRING}, {0}},
  {DUMP_TZ_LEAP_SEC_S, {ARG_BOOLEAN}, {0}},
  {DUMP_TZ_DUMP_SUM_S, {ARG_BOOLEAN}, {0}},
  {0, {0}, {0}}
}
Definition at line 749 of file util_admin.c.
GETOPT_LONG ua_DumpTz_Option[] static
Initial value:
= {
  {DUMP_TZ_COUNTRIES_L, 0, 0, DUMP_TZ_COUNTRIES_S},
  {DUMP_TZ_ZONES_L, 0, 0, DUMP_TZ_ZONES_S},
  {DUMP_TZ_ZONE_ID_L, 1, 0, DUMP_TZ_ZONE_ID_S},
  {DUMP_TZ_LEAP_SEC_L, 0, 0, DUMP_TZ_LEAP_SEC_S},
  {DUMP_TZ_DUMP_SUM_L, 0, 0, DUMP_TZ_DUMP_SUM_S},
  {0, 0, 0, 0}
}
Definition at line 758 of file util_admin.c.
UTIL_ARG_MAP ua_GenLocale_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {0}, {0}},
  {GENLOCALE_INPUT_PATH_S, {ARG_STRING}, {0}},
  {GENLOCALE_VERBOSE_S, {ARG_BOOLEAN}, {0}},
  {0, {0}, {0}}
}
Definition at line 678 of file util_admin.c.
GETOPT_LONG ua_GenLocale_Option[] static
Initial value:
= {
  {GENLOCALE_INPUT_PATH_L, 1, 0, GENLOCALE_INPUT_PATH_S},
  {GENLOCALE_VERBOSE_L, 0, 0, APPLYINFO_VERBOSE_S},
  {0, 0, 0, 0}
}
Definition at line 685 of file util_admin.c.
UTIL_ARG_MAP ua_GenTz_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {0}, {0}},
  {GEN_TZ_INPUT_FOLDER_S, {ARG_STRING}, {0}},
  {GEN_TZ_MODE_S, {ARG_STRING}, {0}},
  {0, {0}, {0}}
}
Definition at line 736 of file util_admin.c.
GETOPT_LONG ua_GenTz_Option[] static
Initial value:
= {
  {GEN_TZ_INPUT_FOLDER_L, 1, 0, GEN_TZ_INPUT_FOLDER_S},
  {GEN_TZ_MODE_L, 1, 0, GEN_TZ_MODE_S},
  {0, 0, 0, 0}
}
Definition at line 743 of file util_admin.c.
GETOPT_LONG ua_Install_Option[] static
Initial value:
= {
  {INSTALL_SERVER_NAME_L, 1, 0, INSTALL_SERVER_NAME_S},
  {INSTALL_FILE_PATH_L, 1, 0, INSTALL_FILE_PATH_S},
  {INSTALL_LOG_PATH_L, 1, 0, INSTALL_LOG_PATH_S},
  {0, 0, 0, 0}
}
Definition at line 304 of file util_admin.c.
UTIL_ARG_MAP ua_Install_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {0}, {0}},
  {INSTALL_SERVER_NAME_S, {ARG_STRING}, {0}},
  {INSTALL_FILE_PATH_S, {ARG_STRING}, {0}},
  {INSTALL_LOG_PATH_S, {ARG_STRING}, {0}},
  {0, {0}, {0}}
}
Definition at line 296 of file util_admin.c.
GETOPT_LONG ua_Killtran_Option[] static
Initial value:
= {
  {KILLTRAN_KILL_TRANSACTION_INDEX_L, 1, 0,
   KILLTRAN_KILL_TRANSACTION_INDEX_S},
  {KILLTRAN_KILL_USER_NAME_L, 1, 0, KILLTRAN_KILL_USER_NAME_S},
  {KILLTRAN_KILL_HOST_NAME_L, 1, 0, KILLTRAN_KILL_HOST_NAME_S},
  {KILLTRAN_KILL_PROGRAM_NAME_L, 1, 0, KILLTRAN_KILL_PROGRAM_NAME_S},
  {KILLTRAN_KILL_SQL_ID_L, 1, 0, KILLTRAN_KILL_SQL_ID_S},
  {KILLTRAN_DBA_PASSWORD_L, 1, 0, KILLTRAN_DBA_PASSWORD_S},
  {KILLTRAN_DISPLAY_INFORMATION_L, 0, 0, KILLTRAN_DISPLAY_INFORMATION_S},
  {KILLTRAN_DISPLAY_QUERY_INFO_L, 0, 0, KILLTRAN_DISPLAY_QUERY_INFO_S},
  {KILLTRAN_FORCE_L, 0, 0, KILLTRAN_FORCE_S},
  {0, 0, 0, 0}
}
Definition at line 416 of file util_admin.c.
UTIL_ARG_MAP ua_Killtran_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {0}, {0}},
  {KILLTRAN_KILL_TRANSACTION_INDEX_S, {ARG_STRING}, {0}},
  {KILLTRAN_KILL_USER_NAME_S, {ARG_STRING}, {(void *) ""}},
  {KILLTRAN_KILL_HOST_NAME_S, {ARG_STRING}, {(void *) ""}},
  {KILLTRAN_KILL_PROGRAM_NAME_S, {ARG_STRING}, {(void *) ""}},
  {KILLTRAN_KILL_SQL_ID_S, {ARG_STRING}, {0}},
  {KILLTRAN_DBA_PASSWORD_S, {ARG_STRING}, {0}},
  {KILLTRAN_DISPLAY_INFORMATION_S, {ARG_BOOLEAN}, {0}},
  {KILLTRAN_DISPLAY_QUERY_INFO_S, {ARG_BOOLEAN}, {0}},
  {KILLTRAN_FORCE_S, {ARG_BOOLEAN}, {0}},
  {0, {0}, {0}}
}
Definition at line 402 of file util_admin.c.
GETOPT_LONG ua_Load_Option[] static
Initial value:
= {
  {LOAD_USER_L, 1, 0, LOAD_USER_S},
  {LOAD_PASSWORD_L, 1, 0, LOAD_PASSWORD_S},
  {LOAD_CHECK_ONLY_L, 0, 0, LOAD_CHECK_ONLY_S},
  {LOAD_LOAD_ONLY_L, 0, 0, LOAD_LOAD_ONLY_S},
  {LOAD_ESTIMATED_SIZE_L, 1, 0, LOAD_ESTIMATED_SIZE_S},
  {LOAD_VERBOSE_L, 0, 0, LOAD_VERBOSE_S},
  {LOAD_NO_STATISTICS_L, 0, 0, LOAD_NO_STATISTICS_S},
  {LOAD_PERIODIC_COMMIT_L, 1, 0, LOAD_PERIODIC_COMMIT_S},
  {LOAD_NO_OID_L, 0, 0, LOAD_NO_OID_S},
  {LOAD_SCHEMA_FILE_L, 1, 0, LOAD_SCHEMA_FILE_S},
  {LOAD_INDEX_FILE_L, 1, 0, LOAD_INDEX_FILE_S},
  {LOAD_TRIGGER_FILE_L, 1, 0, LOAD_TRIGGER_FILE_S},
  {LOAD_IGNORE_LOGGING_L, 0, 0, LOAD_IGNORE_LOGGING_S},
  {LOAD_DATA_FILE_L, 1, 0, LOAD_DATA_FILE_S},
  {LOAD_ERROR_CONTROL_FILE_L, 1, 0, LOAD_ERROR_CONTROL_FILE_S},
  {LOAD_IGNORE_CLASS_L, 1, 0, LOAD_IGNORE_CLASS_S},
  {LOAD_CS_MODE_L, 0, 0, LOAD_CS_MODE_S},
  {LOAD_SA_MODE_L, 0, 0, LOAD_SA_MODE_S},
  {LOAD_TABLE_NAME_L, 1, 0, LOAD_TABLE_NAME_S},
  {LOAD_COMPARE_STORAGE_ORDER_L, 0, 0, LOAD_COMPARE_STORAGE_ORDER_S},
  {LOAD_CS_FORCE_LOAD_L, 0, 0, LOAD_CS_FORCE_LOAD_S},
  {0, 0, 0, 0}
}
Definition at line 481 of file util_admin.c.
UTIL_ARG_MAP ua_Load_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {0}, {0}},
  {LOAD_USER_S, {ARG_STRING}, {0}},
  {LOAD_PASSWORD_S, {ARG_STRING}, {0}},
  {LOAD_CHECK_ONLY_S, {ARG_BOOLEAN}, {0}},
  {LOAD_LOAD_ONLY_S, {ARG_BOOLEAN}, {0}},
  {LOAD_ESTIMATED_SIZE_S, {ARG_INTEGER}, {0}},
  {LOAD_VERBOSE_S, {ARG_BOOLEAN}, {0}},
  {LOAD_NO_STATISTICS_S, {ARG_BOOLEAN}, {0}},
  {LOAD_PERIODIC_COMMIT_S, {ARG_INTEGER}, {0}},
  {LOAD_NO_OID_S, {ARG_BOOLEAN}, {0}},
  {LOAD_SCHEMA_FILE_S, {ARG_STRING}, {0}},
  {LOAD_INDEX_FILE_S, {ARG_STRING}, {0}},
  {LOAD_TRIGGER_FILE_S, {ARG_STRING}, {0}},
  {LOAD_IGNORE_LOGGING_S, {ARG_BOOLEAN}, {0}},
  {LOAD_DATA_FILE_S, {ARG_STRING}, {0}},
  {LOAD_ERROR_CONTROL_FILE_S, {ARG_STRING}, {0}},
  {LOAD_IGNORE_CLASS_S, {ARG_STRING}, {0}},
  {LOAD_CS_MODE_S, {ARG_BOOLEAN}, {0}},
  {LOAD_SA_MODE_S, {ARG_BOOLEAN}, {(void *) 1}},
  {LOAD_TABLE_NAME_S, {ARG_STRING}, {0}},
  {LOAD_COMPARE_STORAGE_ORDER_S, {ARG_BOOLEAN}, {0}},
  {LOAD_CS_FORCE_LOAD_S, {ARG_BOOLEAN}, {0}},
  {0, {0}, {0}}
}
Definition at line 455 of file util_admin.c.
GETOPT_LONG ua_Lock_Option[] static
Initial value:
= {
  {LOCK_OUTPUT_FILE_L, 1, 0, LOCK_OUTPUT_FILE_S},
  {0, 0, 0, 0}
}
Definition at line 269 of file util_admin.c.
UTIL_ARG_MAP ua_Lock_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {0}, {0}},
  {LOCK_OUTPUT_FILE_S, {ARG_STRING}, {0}},
  {0, {0}, {0}}
}
Definition at line 263 of file util_admin.c.
GETOPT_LONG ua_Optimize_Option[] static
Initial value:
= {
  {OPTIMIZE_CLASS_NAME_L, 1, 0, OPTIMIZE_CLASS_NAME_S},
  {0, 0, 0, 0}
}
Definition at line 291 of file util_admin.c.
UTIL_ARG_MAP ua_Optimize_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {0}, {0}},
  {OPTIMIZE_CLASS_NAME_S, {ARG_STRING}, {0}},
  {0, {0}, {0}}
}
Definition at line 285 of file util_admin.c.
GETOPT_LONG ua_Paramdump_Option[] static
Initial value:
= {
  {PARAMDUMP_OUTPUT_FILE_L, 1, 0, PARAMDUMP_OUTPUT_FILE_S},
  {PARAMDUMP_BOTH_L, 0, 0, PARAMDUMP_BOTH_S},
  {PARAMDUMP_SA_MODE_L, 0, 0, PARAMDUMP_SA_MODE_S},
  {PARAMDUMP_CS_MODE_L, 0, 0, PARAMDUMP_CS_MODE_S},
  {0, 0, 0, 0}
}
Definition at line 589 of file util_admin.c.
UTIL_ARG_MAP ua_Paramdump_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {ARG_INTEGER}, {0}},
  {PARAMDUMP_OUTPUT_FILE_S, {ARG_STRING}, {0}},
  {PARAMDUMP_BOTH_S, {ARG_BOOLEAN}, {0}},
  {PARAMDUMP_SA_MODE_S, {ARG_BOOLEAN}, {0}},
  {PARAMDUMP_CS_MODE_S, {ARG_BOOLEAN}, {0}},
  {0, {0}, {0}}
}
Definition at line 580 of file util_admin.c.
GETOPT_LONG ua_Patch_Option[] static
Initial value:
= {
  {PATCH_RECREATE_LOG_L, 0, 0, PATCH_RECREATE_LOG_S},
  {0, 0, 0, 0}
}
Definition at line 334 of file util_admin.c.
UTIL_ARG_MAP ua_Patch_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {0}, {0}},
  {PATCH_RECREATE_LOG_S, {ARG_BOOLEAN}, {0}},
  {0, {0}, {0}}
}
Definition at line 328 of file util_admin.c.
GETOPT_LONG ua_Plandump_Option[] static
Initial value:
= {
  {PLANDUMP_DROP_L, 0, 0, PLANDUMP_DROP_S},
  {PLANDUMP_OUTPUT_FILE_L, 1, 0, PLANDUMP_OUTPUT_FILE_S},
  {0, 0, 0, 0}
}
Definition at line 396 of file util_admin.c.
UTIL_ARG_MAP ua_Plandump_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {0}, {0}},
  {PLANDUMP_DROP_S, {ARG_BOOLEAN}, {0}},
  {PLANDUMP_OUTPUT_FILE_S, {ARG_STRING}, {0}},
  {0, {0}, {0}}
}
Definition at line 389 of file util_admin.c.
GETOPT_LONG ua_Rename_Option[] static
Initial value:
= {
  {RENAME_EXTENTED_VOLUME_PATH_L, 1, 0, RENAME_EXTENTED_VOLUME_PATH_S},
  {RENAME_CONTROL_FILE_L, 1, 0, RENAME_CONTROL_FILE_S},
  {RENAME_DELETE_BACKUP_L, 0, 0, RENAME_DELETE_BACKUP_S},
  {0, 0, 0, 0}
}
Definition at line 88 of file util_admin.c.
UTIL_ARG_MAP ua_Rename_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {0}, {0}},
  {RENAME_EXTENTED_VOLUME_PATH_S, {ARG_STRING}, {0}},
  {RENAME_CONTROL_FILE_S, {ARG_STRING}, {0}},
  {RENAME_DELETE_BACKUP_S, {ARG_BOOLEAN}, {0}},
  {0, {0}, {0}}
}
Definition at line 80 of file util_admin.c.
GETOPT_LONG ua_Restore_Option[] static
Initial value:
= {
  {RESTORE_UP_TO_DATE_L, 1, 0, RESTORE_UP_TO_DATE_S},
  {RESTORE_LIST_L, 0, 0, RESTORE_LIST_S},
  {RESTORE_BACKUP_FILE_PATH_L, 1, 0, RESTORE_BACKUP_FILE_PATH_S},
  {RESTORE_LEVEL_L, 1, 0, RESTORE_LEVEL_S},
  {RESTORE_PARTIAL_RECOVERY_L, 0, 0, RESTORE_PARTIAL_RECOVERY_S},
  {RESTORE_OUTPUT_FILE_L, 1, 0, RESTORE_OUTPUT_FILE_S},
  {RESTORE_USE_DATABASE_LOCATION_PATH_L, 0, 0,
   RESTORE_USE_DATABASE_LOCATION_PATH_S},
  {RESTORE_KEYS_FILE_PATH_L, 1, 0, RESTORE_KEYS_FILE_PATH_S},
  {0, 0, 0, 0}
}
Definition at line 181 of file util_admin.c.
UTIL_ARG_MAP ua_Restore_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {0}, {0}},
  {RESTORE_UP_TO_DATE_S, {ARG_STRING}, {0}},
  {RESTORE_LIST_S, {ARG_BOOLEAN}, {0}},
  {RESTORE_BACKUP_FILE_PATH_S, {ARG_STRING}, {0}},
  {RESTORE_LEVEL_S, {ARG_INTEGER}, {0}},
  {RESTORE_PARTIAL_RECOVERY_S, {ARG_BOOLEAN}, {0}},
  {RESTORE_OUTPUT_FILE_S, {ARG_STRING}, {0}},
  {RESTORE_USE_DATABASE_LOCATION_PATH_S, {ARG_BOOLEAN}, {0}},
  {RESTORE_KEYS_FILE_PATH_S, {ARG_STRING}, {0}},
  {0, {0}, {0}}
}
Definition at line 168 of file util_admin.c.
GETOPT_LONG ua_RestoreSlave_Option[] static
Initial value:
= {
  {RESTORESLAVE_SOURCE_STATE_L, 1, 0, RESTORESLAVE_SOURCE_STATE_S},
  {RESTORESLAVE_MASTER_HOST_NAME_L, 1, 0, RESTORESLAVE_MASTER_HOST_NAME_S},
  {RESTORESLAVE_LIST_L, 0, 0, RESTORESLAVE_LIST_S},
  {RESTORESLAVE_BACKUP_FILE_PATH_L, 1, 0, RESTORESLAVE_BACKUP_FILE_PATH_S},
  {RESTORESLAVE_OUTPUT_FILE_L, 1, 0, RESTORESLAVE_OUTPUT_FILE_S},
  {RESTORESLAVE_USE_DATABASE_LOCATION_PATH_L, 0, 0,
   RESTORESLAVE_USE_DATABASE_LOCATION_PATH_S},
  {RESTORESLAVE_KEYS_FILE_PATH_L, 1, 0, RESTORESLAVE_KEYS_FILE_PATH_S},
  {0, 0, 0, 0}
}
Definition at line 779 of file util_admin.c.
UTIL_ARG_MAP ua_RestoreSlave_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {0}, {0}},
  {RESTORESLAVE_SOURCE_STATE_S, {ARG_STRING}, {0}},
  {RESTORESLAVE_MASTER_HOST_NAME_S, {ARG_STRING}, {0}},
  {RESTORESLAVE_LIST_S, {ARG_BOOLEAN}, {0}},
  {RESTORESLAVE_BACKUP_FILE_PATH_S, {ARG_STRING}, {0}},
  {RESTORESLAVE_OUTPUT_FILE_S, {ARG_STRING}, {0}},
  {RESTORESLAVE_USE_DATABASE_LOCATION_PATH_S, {ARG_BOOLEAN}, {0}},
  {RESTORESLAVE_KEYS_FILE_PATH_S, {ARG_STRING}, {0}},
  {0, {0}, {0}}
}
Definition at line 767 of file util_admin.c.
GETOPT_LONG ua_Space_Option[] static
Initial value:
= {
  {SPACE_OUTPUT_FILE_L, 1, 0, SPACE_OUTPUT_FILE_S},
  {SPACE_SA_MODE_L, 0, 0, SPACE_SA_MODE_S},
  {SPACE_CS_MODE_L, 0, 0, SPACE_CS_MODE_S},
  {SPACE_SIZE_UNIT_L, 1, 0, SPACE_SIZE_UNIT_S},
  {SPACE_SUMMARIZE_L, 0, 0, SPACE_SUMMARIZE_S},
  {SPACE_PURPOSE_L, 0, 0, SPACE_PURPOSE_S},
  {0, 0, 0, 0}
}
Definition at line 253 of file util_admin.c.
UTIL_ARG_MAP ua_Space_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {0}, {0}},
  {SPACE_OUTPUT_FILE_S, {ARG_STRING}, {0}},
  {SPACE_SA_MODE_S, {ARG_BOOLEAN}, {0}},
  {SPACE_CS_MODE_S, {ARG_BOOLEAN}, {0}},
  {SPACE_SIZE_UNIT_S, {ARG_STRING}, {(void *) "h"}},
  {SPACE_SUMMARIZE_S, {ARG_BOOLEAN}, {0}},
  {SPACE_PURPOSE_S, {ARG_BOOLEAN}, {0}},
  {0, {0}, {0}}
}
Definition at line 242 of file util_admin.c.
GETOPT_LONG ua_Statdump_Option[] static
Initial value:
= {
  {STATDUMP_OUTPUT_FILE_L, 1, 0, STATDUMP_OUTPUT_FILE_S},
  {STATDUMP_INTERVAL_L, 1, 0, STATDUMP_INTERVAL_S},
  {STATDUMP_CUMULATIVE_L, 0, 0, STATDUMP_CUMULATIVE_S},
  {STATDUMP_SUBSTR_L, 1, 0, STATDUMP_SUBSTR_S},
  {0, 0, 0, 0}
}
Definition at line 606 of file util_admin.c.
UTIL_ARG_MAP ua_Statdump_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {ARG_INTEGER}, {0}},
  {STATDUMP_OUTPUT_FILE_S, {ARG_STRING}, {0}},
  {STATDUMP_INTERVAL_S, {ARG_INTEGER}, {0}},
  {STATDUMP_CUMULATIVE_S, {ARG_BOOLEAN}, {0}},
  {STATDUMP_SUBSTR_S, {ARG_STRING}, {0}},
  {0, {0}, {0}}
}
Definition at line 597 of file util_admin.c.
UTIL_ARG_MAP ua_SyncCollDB_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {0}, {0}},
  {SYNCCOLL_CHECK_S, {ARG_BOOLEAN}, {0}},
  {SYNCCOLL_FORCESYNC_S, {ARG_BOOLEAN}, {0}},
  {0, {0}, {0}}
}
Definition at line 723 of file util_admin.c.
GETOPT_LONG ua_SyncCollDB_Option[] static
Initial value:
= {
  {SYNCCOLL_CHECK_L, 0, 0, SYNCCOLL_CHECK_S},
  {SYNCCOLL_FORCESYNC_L, 0, 0, SYNCCOLL_FORCESYNC_S},
  {0, 0, 0, 0}
}
Definition at line 730 of file util_admin.c.
GETOPT_LONG ua_Tde_Option[] static
Initial value:
= {
  {TDE_GENERATE_KEY_L, 0, 0, TDE_GENERATE_KEY_S},
  {TDE_SHOW_KEYS_L, 0, 0, TDE_SHOW_KEYS_S},
  {TDE_PRINT_KEY_VALUE_L, 0, 0, TDE_PRINT_KEY_VALUE_S},
  {TDE_SA_MODE_L, 0, 0, TDE_SA_MODE_S},
  {TDE_CS_MODE_L, 0, 0, TDE_CS_MODE_S},
  {TDE_CHANGE_KEY_L, 1, 0, TDE_CHANGE_KEY_S},
  {TDE_DELETE_KEY_L, 1, 0, TDE_DELETE_KEY_S},
  {TDE_DBA_PASSWORD_L, 1, 0, TDE_DBA_PASSWORD_S},
  {0, 0, 0, 0}
}
Definition at line 850 of file util_admin.c.
UTIL_ARG_MAP ua_Tde_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {0}, {0}},
  {TDE_GENERATE_KEY_S, {ARG_BOOLEAN}, {0}},
  {TDE_SHOW_KEYS_S, {ARG_BOOLEAN}, {0}},
  {TDE_PRINT_KEY_VALUE_S, {ARG_BOOLEAN}, {0}},
  {TDE_SA_MODE_S, {ARG_BOOLEAN}, {0}},
  {TDE_CS_MODE_S, {ARG_BOOLEAN}, {0}},
  {TDE_CHANGE_KEY_S, {ARG_INTEGER}, {(void *) -1}},
  {TDE_DELETE_KEY_S, {ARG_INTEGER}, {(void *) -1}},
  {TDE_DBA_PASSWORD_S, {ARG_STRING}, {(void *) ""}},
  {0, {0}, {0}}
}
Definition at line 837 of file util_admin.c.
GETOPT_LONG ua_Tranlist_Option[] static
Initial value:
= {
  {TRANLIST_SUMMARY_L, 0, 0, TRANLIST_SUMMARY_S},
  {TRANLIST_SORT_KEY_L, 1, 0, TRANLIST_SORT_KEY_S},
  {TRANLIST_REVERSE_L, 0, 0, TRANLIST_REVERSE_S},
  {TRANLIST_FULL_SQL_L, 0, 0, TRANLIST_FULL_SQL_S},
  {0, 0, 0, 0}
}
Definition at line 443 of file util_admin.c.
UTIL_ARG_MAP ua_Tranlist_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {0}, {0}},
  {TRANLIST_SUMMARY_S, {ARG_BOOLEAN}, {0}},
  {TRANLIST_SORT_KEY_S, {ARG_INTEGER}, {0}},
  {TRANLIST_REVERSE_S, {ARG_BOOLEAN}, {0}},
  {TRANLIST_FULL_SQL_S, {ARG_BOOLEAN}, {0}},
  {0, {0}, {0}}
}
Definition at line 430 of file util_admin.c.
GETOPT_LONG ua_Unload_Option[] static
Initial value:
= {
  {UNLOAD_INPUT_CLASS_FILE_L, 1, 0, UNLOAD_INPUT_CLASS_FILE_S},
  {UNLOAD_INCLUDE_REFERENCE_L, 0, 0, UNLOAD_INCLUDE_REFERENCE_S},
  {UNLOAD_INPUT_CLASS_ONLY_L, 0, 0, UNLOAD_INPUT_CLASS_ONLY_S},
  {UNLOAD_LO_COUNT_L, 1, 0, UNLOAD_LO_COUNT_S},
  {UNLOAD_ESTIMATED_SIZE_L, 1, 0, UNLOAD_ESTIMATED_SIZE_S},
  {UNLOAD_CACHED_PAGES_L, 1, 0, UNLOAD_CACHED_PAGES_S},
  {UNLOAD_OUTPUT_PATH_L, 1, 0, UNLOAD_OUTPUT_PATH_S},
  {UNLOAD_SCHEMA_ONLY_L, 0, 0, UNLOAD_SCHEMA_ONLY_S},
  {UNLOAD_DATA_ONLY_L, 0, 0, UNLOAD_DATA_ONLY_S},
  {UNLOAD_OUTPUT_PREFIX_L, 1, 0, UNLOAD_OUTPUT_PREFIX_S},
  {UNLOAD_HASH_FILE_L, 1, 0, UNLOAD_HASH_FILE_S},
  {UNLOAD_VERBOSE_L, 0, 0, UNLOAD_VERBOSE_S},
  {UNLOAD_USE_DELIMITER_L, 0, 0, UNLOAD_USE_DELIMITER_S},
  {UNLOAD_DATAFILE_PER_CLASS_L, 0, 0, UNLOAD_DATAFILE_PER_CLASS_S},
  {UNLOAD_SA_MODE_L, 0, 0, UNLOAD_SA_MODE_S},
  {UNLOAD_CS_MODE_L, 0, 0, UNLOAD_CS_MODE_S},
  {UNLOAD_USER_L, 1, 0, LOAD_USER_S},
  {UNLOAD_PASSWORD_L, 1, 0, LOAD_PASSWORD_S},
  {UNLOAD_KEEP_STORAGE_ORDER_L, 0, 0, UNLOAD_KEEP_STORAGE_ORDER_S},
  {0, 0, 0, 0}
}
Definition at line 530 of file util_admin.c.
UTIL_ARG_MAP ua_Unload_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {0}, {0}},
  {UNLOAD_INPUT_CLASS_FILE_S, {ARG_STRING}, {0}},
  {UNLOAD_INCLUDE_REFERENCE_S, {ARG_BOOLEAN}, {0}},
  {UNLOAD_INPUT_CLASS_ONLY_S, {ARG_BOOLEAN}, {0}},
  {UNLOAD_LO_COUNT_S, {ARG_INTEGER}, {0}},
  {UNLOAD_ESTIMATED_SIZE_S, {ARG_INTEGER}, {0}},
  {UNLOAD_CACHED_PAGES_S, {ARG_INTEGER}, {(void *) 100}},
  {UNLOAD_OUTPUT_PATH_S, {ARG_STRING}, {0}},
  {UNLOAD_SCHEMA_ONLY_S, {ARG_BOOLEAN}, {0}},
  {UNLOAD_DATA_ONLY_S, {ARG_BOOLEAN}, {0}},
  {UNLOAD_OUTPUT_PREFIX_S, {ARG_STRING}, {0}},
  {UNLOAD_HASH_FILE_S, {ARG_STRING}, {0}},
  {UNLOAD_VERBOSE_S, {ARG_BOOLEAN}, {0}},
  {UNLOAD_USE_DELIMITER_S, {ARG_BOOLEAN}, {0}},
  {UNLOAD_SA_MODE_S, {ARG_BOOLEAN}, {0}},
  {UNLOAD_CS_MODE_S, {ARG_BOOLEAN}, {0}},
  {UNLOAD_DATAFILE_PER_CLASS_S, {ARG_BOOLEAN}, {0}},
  {UNLOAD_USER_S, {ARG_STRING}, {0}},
  {UNLOAD_PASSWORD_S, {ARG_STRING}, {0}},
  {UNLOAD_KEEP_STORAGE_ORDER_S, {ARG_BOOLEAN}, {0}},
  {0, {0}, {0}}
}
Definition at line 506 of file util_admin.c.
UTIL_MAP ua_Utility_Map[] static
Definition at line 862 of file util_admin.c.
GETOPT_LONG ua_Vacuum_Option[] static
Initial value:
= {
  {VACUUM_SA_MODE_L, 0, 0, VACUUM_SA_MODE_S},
  {VACUUM_CS_MODE_L, 0, 0, VACUUM_CS_MODE_S},
  {VACUUM_DUMP_L, 0, 0, VACUUM_DUMP_S},
  {VACUUM_OUTPUT_FILE_L, 1, 0, VACUUM_OUTPUT_FILE_S},
  {0, 0, 0, 0}
}
Definition at line 800 of file util_admin.c.
UTIL_ARG_MAP ua_Vacuum_Option_Map[] static
Initial value:
= {
  {OPTION_STRING_TABLE, {0}, {0}},
  {VACUUM_SA_MODE_S, {ARG_BOOLEAN}, {0}},
  {VACUUM_CS_MODE_S, {ARG_BOOLEAN}, {0}},
  {VACUUM_DUMP_S, {ARG_BOOLEAN}, {0}},
  {VACUUM_OUTPUT_FILE_S, {ARG_STRING}, {0}},
  {0, {0}, {0}}
}
Definition at line 791 of file util_admin.c.