CUBRID Engine: src/executables/util_cs.c File Reference
util_cs.c File Reference
#include "config.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <signal.h>
#include <errno.h>
#include <assert.h>
#include "utility.h"
#include "error_manager.h"
#include "message_catalog.h"
#include "system_parameter.h"
#include "environment_variable.h"
#include "databases_file.h"
#include "boot_cl.h"
#include "boot_sr.h"
#include "db.h"
#include "authenticate.h"
#include "server_interface.h"
#include "object_representation.h"
#include "transaction_cl.h"
#include "porting.h"
#include "network_interface_cl.h"
#include "connection_defs.h"
#include "log_writer.h"
#include "log_applier.h"
#include "log_lsa.hpp"
#include "schema_manager.h"
#include "locator_cl.h"
#include "dynamic_array.h"
#include "util_func.h"
#include "xasl.h"
#include "log_volids.hpp"
#include "tde.h"
#include "heartbeat.h"
Macros
#define PASSBUF_SIZE 12
#define SPACEDB_NUM_VOL_PURPOSE 2
#define MAX_KILLTRAN_INDEX_LIST_NUM 64
#define MAX_DELVOL_ID_LIST_NUM 64
#define VOL_PURPOSE_STRING(VOL_PURPOSE)
#define SPACEDB_TO_SIZE_ARG(no, npage) spacedb_get_size_str (size_str_##no, npage, size_unit_type)
#define UNIT_STR(un) (((un) == SPACEDB_SIZE_UNIT_MBYTES) ? 'M' : ((un) == SPACEDB_SIZE_UNIT_GBYTES) ? 'G' : 'T')
Enumerations
enum T_SPACEDB_SIZE_UNIT {
SPACEDB_SIZE_UNIT_PAGE = 0, SPACEDB_SIZE_UNIT_MBYTES, SPACEDB_SIZE_UNIT_GBYTES, SPACEDB_SIZE_UNIT_TBYTES,
SPACEDB_SIZE_UNIT_HUMAN_READABLE
}
enum TRANDUMP_LEVEL { TRANDUMP_SUMMARY, TRANDUMP_QUERY_INFO, TRANDUMP_FULL_INFO }
enum SORT_COLUMN_TYPE { SORT_COLUMN_TYPE_INT, SORT_COLUMN_TYPE_FLOAT, SORT_COLUMN_TYPE_STR }
Functions
static void intr_handler (int sig_no)
static void backupdb_sig_interrupt_handler (int sig_no)
STATIC_INLINE char * spacedb_get_size_str (char *buf, UINT64 num_pages, T_SPACEDB_SIZE_UNIT size_unit)
static void print_timestamp (FILE *outfp)
static int print_tran_entry (const ONE_TRAN_INFO *tran_info, TRANDUMP_LEVEL dump_level, bool full_sqltext)
static int tranlist_cmp_f (const void *p1, const void *p2)
static OID * util_get_class_oids_and_index_btid (dynamic_array *darray, const char *index_name, BTID *index_btid)
int backupdb (UTIL_FUNCTION_ARG *arg)
int addvoldb (UTIL_FUNCTION_ARG *arg)
int checkdb (UTIL_FUNCTION_ARG *arg)
int spacedb (UTIL_FUNCTION_ARG *arg)
int acldb (UTIL_FUNCTION_ARG *arg)
int lockdb (UTIL_FUNCTION_ARG *arg)
static int isvalid_transaction (const ONE_TRAN_INFO *tran)
static bool doesmatch_transaction (const ONE_TRAN_INFO *tran, int *tran_index_list, int index_list_size, const char *username, const char *hostname, const char *progname, const char *sql_id)
static void dump_trantb (TRANS_INFO *info, TRANDUMP_LEVEL dump_level, bool full_sqltext)
static int kill_transactions (TRANS_INFO *info, int *tran_index_list, int list_size, const char *username, const char *hostname, const char *progname, const char *sql_id, bool verify)
int tranlist (UTIL_FUNCTION_ARG *arg)
int killtran (UTIL_FUNCTION_ARG *arg)
int plandump (UTIL_FUNCTION_ARG *arg)
int paramdump (UTIL_FUNCTION_ARG *arg)
int statdump (UTIL_FUNCTION_ARG *arg)
int changemode (UTIL_FUNCTION_ARG *arg)
int copylogdb (UTIL_FUNCTION_ARG *arg)
int applylogdb (UTIL_FUNCTION_ARG *arg)
int applyinfo (UTIL_FUNCTION_ARG *arg)
int vacuumdb (UTIL_FUNCTION_ARG *arg)
int tde (UTIL_FUNCTION_ARG *arg)
Variables
static int tranlist_Sort_column = 0
static bool tranlist_Sort_desc = false
static bool is_Sigint_caught = false
Macro Definition Documentation
#define MAX_DELVOL_ID_LIST_NUM 64
Definition at line 69 of file util_cs.c.
#define MAX_KILLTRAN_INDEX_LIST_NUM 64
Definition at line 68 of file util_cs.c.
Referenced by killtran().
#define PASSBUF_SIZE 12
Definition at line 66 of file util_cs.c.
#define SPACEDB_NUM_VOL_PURPOSE 2
Definition at line 67 of file util_cs.c.
#define SPACEDB_TO_SIZE_ARG (no, npage) spacedb_get_size_str (size_str_##no, npage, size_unit_type)
Referenced by spacedb().
#define UNIT_STR (un) (((un) == SPACEDB_SIZE_UNIT_MBYTES) ? 'M' : ((un) == SPACEDB_SIZE_UNIT_GBYTES) ? 'G' : 'T')
Referenced by spacedb_get_size_str().
#define VOL_PURPOSE_STRING (VOL_PURPOSE)
Value:
((VOL_PURPOSE == DB_PERMANENT_DATA_PURPOSE) ? "PERMANENT DATA"  \
        : (VOL_PURPOSE == DB_TEMPORARY_DATA_PURPOSE) ? "TEMPORARY DATA"     \
        : "UNKNOWN")
Definition at line 71 of file util_cs.c.
Enumeration Type Documentation
enum SORT_COLUMN_TYPE
Enumerator
SORT_COLUMN_TYPE_INT
SORT_COLUMN_TYPE_FLOAT
SORT_COLUMN_TYPE_STR
Definition at line 92 of file util_cs.c.
enum T_SPACEDB_SIZE_UNIT
Enumerator
SPACEDB_SIZE_UNIT_PAGE
SPACEDB_SIZE_UNIT_MBYTES
SPACEDB_SIZE_UNIT_GBYTES
SPACEDB_SIZE_UNIT_TBYTES
SPACEDB_SIZE_UNIT_HUMAN_READABLE
Definition at line 76 of file util_cs.c.
enum TRANDUMP_LEVEL
Enumerator
TRANDUMP_SUMMARY
TRANDUMP_QUERY_INFO
TRANDUMP_FULL_INFO
Definition at line 85 of file util_cs.c.
Function Documentation
int acldb (UTIL_FUNCTION_ARG * arg)
Definition at line 1128 of file util_cs.c.
References acl_dump(), acl_reload(), ACLDB_MSG_NOT_IN_STANDALONE, ACLDB_MSG_USAGE, ACLDB_RELOAD_S, UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), check_database_name(), UTIL_FUNCTION_ARG::command_name, database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_error_string(), db_login(), db_restart(), db_set_client_type(), db_shutdown(), er_init(), ER_NEVER_EXIT, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_SET_ACLDB, NO_ERROR, NULL, OPTION_STRING_TABLE, TRUE, utility_get_option_bool_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int addvoldb (UTIL_FUNCTION_ARG * arg)
Definition at line 355 of file util_cs.c.
References ADDVOL_COMMENT_S, ADDVOL_FILE_PATH_S, ADDVOL_MAX_WRITESIZE_IN_SEC_S, ADDVOL_PURPOSE_S, ADDVOL_SA_MODE_S, ADDVOL_VOLUME_NAME_S, ADDVOL_VOLUME_SIZE_S, ADDVOLDB_INVALID_MAX_WRITESIZE_IN_SEC, ADDVOLDB_MSG_BAD_NPAGES, ADDVOLDB_MSG_BAD_PURPOSE, ADDVOLDB_MSG_USAGE, UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), check_database_name(), check_volume_name(), UTIL_FUNCTION_ARG::command_name, dbdef_vol_ext_info::comments, database_name, db_add_volume_ex(), DB_CLIENT_TYPE_ADMIN_UTILITY, db_commit_transaction(), db_error_string(), db_login(), DB_PERMANENT_DATA_PURPOSE, db_restart(), db_set_client_type(), db_shutdown(), DB_TEMPORARY_DATA_PURPOSE, er_init(), ER_NEVER_EXIT, IO_PAGESIZE, dbdef_vol_ext_info::max_npages, dbdef_vol_ext_info::max_writesize_in_sec, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_ADDVOLDB, dbdef_vol_ext_info::name, NO_ERROR, NULL, ONE_K, OPTION_STRING_TABLE, dbdef_vol_ext_info::overwrite, dbdef_vol_ext_info::path, PRINT_AND_LOG_ERR_MSG, prm_get_bigint_value(), prm_get_name(), PRM_ID_DB_VOLUME_SIZE, PRM_ID_JAVA_STORED_PROCEDURE, PRM_ID_PB_NBUFFERS, dbdef_vol_ext_info::purpose, sysprm_set_force(), TRUE, util_log_write_errid(), util_print_deprecated(), util_size_string_to_byte(), utility_get_option_bool_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int applyinfo (UTIL_FUNCTION_ARG * arg)
Definition at line 3130 of file util_cs.c.
References APPLYINFO_APPLIED_INFO_S, APPLYINFO_COPIED_LOG_PATH_S, APPLYINFO_INTERVAL_S, APPLYINFO_MSG_HA_NOT_SUPPORT, APPLYINFO_MSG_NOT_HA_MODE, APPLYINFO_MSG_NOT_IN_STANDALONE, APPLYINFO_MSG_USAGE, APPLYINFO_PAGE_S, APPLYINFO_REMOTE_NAME_S, APPLYINFO_VERBOSE_S, UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), check_database_name(), UTIL_FUNCTION_ARG::command_name, CUB_MAXHOSTNAMELEN, database_name, db_clear_host_connected(), DB_CLIENT_TYPE_ADMIN_UTILITY, db_error_string(), db_login(), db_restart(), db_set_client_type(), db_shutdown(), er_init(), ER_NEVER_EXIT, error(), HA_DISABLED, HA_GET_MODE, HA_MODE_REPLICA, intr_handler(), is_Sigint_caught, la_log_page_check(), la_print_delay_info(), LSA_ISNULL(), LSA_SET_NULL(), MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_GENERIC_INVALID_PARAMETER, MSGCAT_UTIL_GENERIC_SERVICE_PROPERTY_FAIL, MSGCAT_UTIL_SET_APPLYINFO, MSGCAT_UTIL_SET_GENERIC, NO_ERROR, NULL, OPTION_STRING_TABLE, os_set_signal_handler(), log_lsa::pageid, PRINT_AND_LOG_ERR_MSG, prm_get_name(), prm_get_string_value(), PRM_ID_HA_REPLICA_TIME_BOUND, start_time, SYSPRM_LOAD_ALL, sysprm_load_and_init(), TRUE, util_log_write_errid(), util_str_to_time_since_epoch(), utility_get_option_bigint_value(), utility_get_option_bool_value(), utility_get_option_int_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int applylogdb (UTIL_FUNCTION_ARG * arg)
Definition at line 2862 of file util_cs.c.
References APPLYLOG_LOG_PATH_S, APPLYLOG_MAX_MEM_SIZE_S, APPLYLOGDB_MSG_HA_NOT_SUPPORT, APPLYLOGDB_MSG_NOT_HA_MODE, APPLYLOGDB_MSG_NOT_IN_STANDALONE, APPLYLOGDB_MSG_USAGE, ARG_FILE_LINE, UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), check_database_name(), UTIL_FUNCTION_ARG::command_name, database_name, DB_CLIENT_TYPE_LOG_APPLIER, db_disable_trigger(), db_error_string(), db_login(), db_restart(), db_set_client_type(), db_set_lock_timeout(), db_shutdown(), envvar_bindir_file(), ER_BO_CONNECT_FAILED, er_errid(), ER_FAILED, er_init(), ER_LC_PARTIALLY_FAILED_TO_FLUSH, er_log_debug, ER_NET_CANT_CONNECT_SERVER, ER_NET_SERVER_COMM_ERROR, ER_NET_SERVER_CRASHED, ER_NEVER_EXIT, ERR_CSS_TCP_CANNOT_CONNECT_TO_MASTER, error(), executable_path, HA_DISABLED, HA_GET_MODE, HA_MODE_REPLICA, hb_Proc_shutdown, hb_process_init(), HB_PTYPE_APPLYLOGDB, hb_set_argv(), hb_set_exec_path(), la_apply_log_file(), la_force_shutdown(), MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_GENERIC_INVALID_PARAMETER, MSGCAT_UTIL_GENERIC_SERVICE_PROPERTY_FAIL, MSGCAT_UTIL_SET_APPLYLOGDB, MSGCAT_UTIL_SET_GENERIC, NO_ERROR, NULL, OPTION_STRING_TABLE, PRINT_AND_LOG_ERR_MSG, prm_get_name(), prm_get_string_value(), PRM_ID_HA_REPLICA_TIME_BOUND, strdup(), SYSPRM_LOAD_ALL, sysprm_load_and_init(), TRUE, util_log_write_errid(), util_log_write_errstr(), util_redirect_stdout_to_null(), util_str_to_time_since_epoch(), utility_get_option_int_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int backupdb (UTIL_FUNCTION_ARG * arg)
Definition at line 121 of file util_cs.c.
References ARG_FILE_LINE, UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, assert, AU_DISABLE_PASSWORDS, BACKUP_COMPRESS_S, BACKUP_DESTINATION_PATH_S, BACKUP_LEVEL_S, BACKUP_NO_CHECK_S, BACKUP_OUTPUT_FILE_S, BACKUP_REMOVE_ARCHIVE_S, BACKUP_SA_MODE_S, BACKUP_SEPARATE_KEYS_S, BACKUP_SLEEP_MSECS_S, BACKUP_THREAD_COUNT_S, BACKUPDB_FIFO_KEYS_NOT_SUPPORTED, BACKUPDB_INVALID_PATH, BACKUPDB_INVALID_THREAD_NUM_OPT, BACKUPDB_MSG_USAGE, BACKUPDB_NOT_USING_SEPARATE_KEYS, backupdb_sig_interrupt_handler(), BACKUPDB_USING_SEPARATE_KEYS, basename(), boot_backup(), boot_check_db_consistency(), check_database_name(), CHECKDB_BTREE_CHECK_ALL_BTREES, CHECKDB_CT_CHECK_CAT_CONSISTENCY, CHECKDB_FILE_TRACKER_CHECK, CHECKDB_HEAP_CHECK_ALLHEAPS, CHECKDB_LC_CHECK_CLASSNAMES, CHECKDB_MSG_INCONSISTENT, UTIL_FUNCTION_ARG::command_name, database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_commit_transaction(), db_error_string(), db_login(), db_restart(), db_set_client_type(), db_set_isolation(), db_shutdown(), dirname(), ER_ERROR_SEVERITY, ER_GENERIC_ERROR, er_get_msglog_filename(), er_init(), ER_NEVER_EXIT, er_set(), FILEIO_BACKUP_FULL_LEVEL, FILEIO_BACKUP_NUM_THREADS_AUTO, FILEIO_BACKUP_SLEEP_MSECS_AUTO, FILEIO_BACKUP_UNDEFINED_LEVEL, FILEIO_ZIP_LZ4_DEFAULT_LEVEL, FILEIO_ZIP_LZ4_METHOD, FILEIO_ZIP_NONE_LEVEL, FILEIO_ZIP_NONE_METHOD, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_BACKUPDB, MSGCAT_UTIL_SET_CHECKDB, NO_ERROR, NULL, OPTION_STRING_TABLE, os_set_signal_handler(), PRINT_AND_LOG_ERR_MSG, prm_get_name(), PRM_ID_JAVA_STORED_PROCEDURE, sysprm_set_force(), TRAN_READ_COMMITTED, TRUE, util_log_write_errid(), util_log_write_warnstr(), utility_get_option_bool_value(), utility_get_option_int_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
static void backupdb_sig_interrupt_handler (int sig_no) static
Definition at line 3075 of file util_cs.c.
References db_set_interrupt(), and STATIC_INLINE.
Referenced by backupdb().
int changemode (UTIL_FUNCTION_ARG * arg)
Definition at line 2486 of file util_cs.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), boot_change_ha_mode(), CHANGEMODE_FORCE_S, changemode_keyword(), CHANGEMODE_MODE_S, CHANGEMODE_MSG_BAD_MODE, CHANGEMODE_MSG_HA_NOT_SUPPORT, CHANGEMODE_MSG_NOT_HA_MODE, CHANGEMODE_MSG_NOT_IN_STANDALONE, CHANGEMODE_MSG_SERVER_MODE, CHANGEMODE_MSG_USAGE, CHANGEMODE_TIMEOUT_S, check_database_name(), UTIL_FUNCTION_ARG::command_name, database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_error_string(), db_login(), db_restart(), db_set_client_type(), db_shutdown(), er_init(), ER_NEVER_EXIT, error(), HA_CHANGE_MODE_DEFAULT_TIMEOUT_IN_SECS, HA_DISABLED, HA_SERVER_STATE_ACTIVE, HA_SERVER_STATE_MAINTENANCE, HA_SERVER_STATE_NA, HA_SERVER_STATE_STANDBY, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_CHANGEMODE, NO_ERROR, NULL, OPTION_STRING_TABLE, PRINT_AND_LOG_ERR_MSG, TRUE, util_log_write_errid(), utility_get_option_bool_value(), utility_get_option_int_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int checkdb (UTIL_FUNCTION_ARG * arg)
Definition at line 621 of file util_cs.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), boot_check_db_consistency(), BTID_SET_NULL, CHECK_BTREE_ALL_BTREES_S, CHECK_CAT_CONSISTENCY_S, CHECK_CHECK_PREV_LINK_S, check_database_name(), CHECK_FILE_TRACKER_S, CHECK_HEAP_ALLHEAPS_S, CHECK_INDEXNAME_S, CHECK_INPUT_FILE_S, CHECK_LC_ALLENTRIES_OF_ALLBTREES_S, CHECK_LC_CLASSNAMES_S, CHECK_REPAIR_PREV_LINK_S, CHECK_REPAIR_S, CHECKDB_ALL_CHECK_EXCEPT_PREV_LINK, CHECKDB_BTREE_CHECK_ALL_BTREES, CHECKDB_CHECK_PREV_LINK, CHECKDB_CT_CHECK_CAT_CONSISTENCY, CHECKDB_FILE_TRACKER_CHECK, CHECKDB_HEAP_CHECK_ALLHEAPS, CHECKDB_LC_CHECK_ALLENTRIES_OF_ALLBTREES, CHECKDB_LC_CHECK_CLASSNAMES, CHECKDB_MSG_INCONSISTENT, CHECKDB_MSG_USAGE, CHECKDB_REPAIR, CHECKDB_REPAIR_PREV_LINK, UTIL_FUNCTION_ARG::command_name, da_add(), da_create(), da_destroy(), da_size(), database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_commit_transaction(), db_error_string(), db_login(), db_restart(), db_set_client_type(), db_set_isolation(), db_shutdown(), er_get_msglog_filename(), er_init(), ER_NEVER_EXIT, i, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_GENERIC_NO_MEM, MSGCAT_UTIL_SET_CHECKDB, NO_ERROR, NULL, OPTION_STRING_TABLE, p, PRINT_AND_LOG_ERR_MSG, prm_get_name(), PRM_ID_JAVA_STORED_PROCEDURE, SM_MAX_IDENTIFIER_LENGTH, strncpy_bufsize, sysprm_set_force(), TRAN_READ_COMMITTED, TRUE, util_get_class_oids_and_index_btid(), util_get_table_list_from_file(), util_log_write_errid(), util_log_write_errstr(), utility_get_option_bool_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int copylogdb (UTIL_FUNCTION_ARG * arg)
Definition at line 2633 of file util_cs.c.
References ARG_FILE_LINE, UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), check_database_name(), UTIL_FUNCTION_ARG::command_name, COPYLOG_LOG_PATH_S, COPYLOG_MODE_S, COPYLOG_START_PAGEID_S, copylogdb_keyword(), COPYLOGDB_MSG_BAD_MODE, COPYLOGDB_MSG_HA_NOT_SUPPORT, COPYLOGDB_MSG_NOT_IN_STANDALONE, COPYLOGDB_MSG_USAGE, database_name, DB_CLIENT_TYPE_LOG_COPIER, db_error_string(), db_login(), db_restart(), db_set_client_type(), db_shutdown(), envvar_bindir_file(), ER_BO_CONNECT_FAILED, er_errid(), ER_FAILED, er_init(), er_log_debug, ER_NET_CANT_CONNECT_SERVER, ER_NET_SERVER_CRASHED, ER_NEVER_EXIT, ERR_CSS_TCP_CANNOT_CONNECT_TO_MASTER, ERR_CSS_TCP_CONNECT_TIMEDOUT, error(), executable_path, HA_DISABLED, hb_Proc_shutdown, hb_process_init(), HB_PTYPE_COPYLOGDB, hb_set_argv(), hb_set_exec_path(), logwr_copy_log_file(), logwr_force_shutdown(), LOGWR_MODE_ASYNC, LOGWR_MODE_SEMISYNC, LOGWR_MODE_SYNC, mode, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_COPYLOGDB, NO_ERROR, NULL, NULL_PAGEID, OPTION_STRING_TABLE, PRINT_AND_LOG_ERR_MSG, prm_get_name(), PRM_ID_ER_LOG_FILE, PRM_ID_LOG_BACKGROUND_ARCHIVING, SYSPRM_LOAD_ALL, sysprm_load_and_init(), sysprm_set_force(), sysprm_set_to_default(), TRUE, util_log_write_errid(), util_log_write_errstr(), util_redirect_stdout_to_null(), utility_get_option_bigint_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
static bool doesmatch_transaction (const ONE_TRAN_INFO * tran, int * tran_index_list, int index_list_size, const char * username, const char * hostname, const char * progname, const char * sql_id) static
Definition at line 1315 of file util_cs.c.
References one_tran_info::host_name, i, isvalid_transaction(), one_tran_info::login_name, NULL, one_tran_info::program_name, one_tran_info::query_exec_info, tran_query_exec_info::sql_id, and one_tran_info::tran_index.
Referenced by kill_transactions().
static void dump_trantb (TRANS_INFO * info, TRANDUMP_LEVEL dump_level, bool full_sqltext) static
Definition at line 1352 of file util_cs.c.
References i, isvalid_transaction(), MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_SET_TRANLIST, NULL, trans_info::num_trans, print_tran_entry(), one_tran_info::query_exec_info, tran_query_exec_info::query_stmt, tran_query_exec_info::sql_id, trans_info::tran, one_tran_info::tran_index, TRANDUMP_FULL_INFO, TRANDUMP_QUERY_INFO, TRANLIST_MSG_FULL_INFO_HEADER, TRANLIST_MSG_FULL_INFO_UNDERSCORE, TRANLIST_MSG_NONE_TABLE_ENTRIES, TRANLIST_MSG_QUERY_INFO_HEADER, TRANLIST_MSG_QUERY_INFO_UNDERSCORE, TRANLIST_MSG_SQL_ID, TRANLIST_MSG_SUMMARY_HEADER, TRANLIST_MSG_SUMMARY_UNDERSCORE, TRANLIST_MSG_TRAN_INDEX, tran_query_exec_info::xasl_id, XASL_ID_EQ, XASL_ID_IS_NULL, and XASL_ID_SET_NULL.
Referenced by killtran(), and tranlist().
static void intr_handler (int sig_no) static
Definition at line 3415 of file util_cs.c.
References FALSE, is_Sigint_caught, and TRUE.
Referenced by applyinfo(), and statdump().
static int isvalid_transaction (const ONE_TRAN_INFO * tran) static
Definition at line 1295 of file util_cs.c.
References NULL, tm_Tran_index, and one_tran_info::tran_index.
Referenced by doesmatch_transaction(), and dump_trantb().
static int kill_transactions (TRANS_INFO * info, int * tran_index_list, int list_size, const char * username, const char * hostname, const char * progname, const char * sql_id, bool verify) static
Definition at line 1471 of file util_cs.c.
References db_error_string(), one_tran_info::db_user, doesmatch_transaction(), er_errid(), one_tran_info::host_name, i, KILLTRAN_MSG_KILL_FAILED, KILLTRAN_MSG_KILL_TIMEOUT, KILLTRAN_MSG_KILLING, KILLTRAN_MSG_NO_MATCHES, KILLTRAN_MSG_READY_TO_KILL, KILLTRAN_MSG_VERIFY, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_SET_KILLTRAN, MSGCAT_UTIL_SET_TRANLIST, NO_ERROR, NULL, trans_info::num_trans, PRINT_AND_LOG_ERR_MSG, print_tran_entry(), one_tran_info::process_id, thread_kill_tran_index(), trans_info::tran, one_tran_info::tran_index, TRANDUMP_QUERY_INFO, TRANDUMP_SUMMARY, TRANLIST_MSG_QUERY_INFO_HEADER, TRANLIST_MSG_QUERY_INFO_UNDERSCORE, TRANLIST_MSG_SUMMARY_HEADER, and TRANLIST_MSG_SUMMARY_UNDERSCORE.
Referenced by killtran().
int killtran (UTIL_FUNCTION_ARG * arg)
Definition at line 1842 of file util_cs.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), check_database_name(), UTIL_FUNCTION_ARG::command_name, database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_error_string(), db_login(), db_restart(), db_set_client_type(), db_shutdown(), dump_trantb(), ER_AU_INVALID_PASSWORD, er_init(), ER_NEVER_EXIT, error(), kill_transactions(), KILLTRAN_DBA_PASSWORD_S, KILLTRAN_DISPLAY_INFORMATION_S, KILLTRAN_DISPLAY_QUERY_INFO_S, KILLTRAN_FORCE_S, KILLTRAN_KILL_HOST_NAME_S, KILLTRAN_KILL_PROGRAM_NAME_S, KILLTRAN_KILL_SQL_ID_S, KILLTRAN_KILL_TRANSACTION_INDEX_S, KILLTRAN_KILL_USER_NAME_S, KILLTRAN_MSG_DBA_PASSWORD, KILLTRAN_MSG_INVALID_TRANINDEX, KILLTRAN_MSG_MANY_ARGS, KILLTRAN_MSG_NOT_IN_STANDALONE, KILLTRAN_MSG_USAGE, logtb_free_trans_info(), logtb_get_trans_info(), MAX_KILLTRAN_INDEX_LIST_NUM, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_KILLTRAN, NO_ERROR, NULL, OPTION_STRING_TABLE, parse_int(), PRINT_AND_LOG_ERR_MSG, strlen, TRANDUMP_QUERY_INFO, TRANDUMP_SUMMARY, TRUE, util_log_write_errid(), util_log_write_errstr(), utility_get_option_bool_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int lockdb (UTIL_FUNCTION_ARG * arg)
Definition at line 1203 of file util_cs.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), check_database_name(), UTIL_FUNCTION_ARG::command_name, database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_error_string(), db_login(), db_restart(), db_set_client_type(), db_set_isolation(), db_shutdown(), er_init(), ER_NEVER_EXIT, lock_dump(), LOCK_OUTPUT_FILE_S, LOCKDB_MSG_BAD_OUTPUT, LOCKDB_MSG_NOT_IN_STANDALONE, LOCKDB_MSG_USAGE, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_LOCKDB, NO_ERROR, NULL, OPTION_STRING_TABLE, output_file, PRINT_AND_LOG_ERR_MSG, TRAN_READ_COMMITTED, TRUE, util_log_write_errid(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int paramdump (UTIL_FUNCTION_ARG * arg)
Definition at line 2206 of file util_cs.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), check_database_name(), UTIL_FUNCTION_ARG::command_name, database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_error_string(), db_login(), db_restart(), db_set_client_type(), db_shutdown(), er_init(), ER_NEVER_EXIT, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_PARAMDUMP, NO_ERROR, NULL, OPTION_STRING_TABLE, output_file, PARAMDUMP_BOTH_S, PARAMDUMP_MSG_BAD_OUTPUT, PARAMDUMP_MSG_CLIENT_PARAMETER, PARAMDUMP_MSG_SERVER_PARAMETER, PARAMDUMP_MSG_STANDALONE_PARAMETER, PARAMDUMP_MSG_USAGE, PARAMDUMP_OUTPUT_FILE_S, PRINT_AND_LOG_ERR_MSG, prm_get_name(), PRM_ID_JAVA_STORED_PROCEDURE, sysprm_dump_parameters(), sysprm_dump_server_parameters(), SYSPRM_LOAD_ALL, sysprm_load_and_init(), sysprm_set_force(), TRUE, util_log_write_errid(), utility_get_option_bool_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int plandump (UTIL_FUNCTION_ARG * arg)
Definition at line 2105 of file util_cs.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), check_database_name(), UTIL_FUNCTION_ARG::command_name, database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_error_string(), db_login(), db_restart(), db_set_client_type(), db_shutdown(), er_init(), ER_NEVER_EXIT, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_PLANDUMP, NO_ERROR, NULL, OPTION_STRING_TABLE, output_file, PLANDUMP_DROP_S, PLANDUMP_MSG_BAD_OUTPUT, PLANDUMP_MSG_NOT_IN_STANDALONE, PLANDUMP_MSG_USAGE, PLANDUMP_OUTPUT_FILE_S, PRINT_AND_LOG_ERR_MSG, qmgr_drop_all_query_plans(), qmgr_dump_query_plans(), TRUE, util_log_write_errid(), utility_get_option_bool_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
static void print_timestamp (FILE * outfp) static
Definition at line 2306 of file util_cs.c.
References NULL, and utility_localtime().
Referenced by statdump().
static int print_tran_entry (const ONE_TRAN_INFO * tran_info, TRANDUMP_LEVEL dump_level, bool full_sqltext) static
Definition at line 1604 of file util_cs.c.
References assert_release, one_tran_info::db_user, ER_FAILED, one_tran_info::host_name, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_SET_TRANLIST, NO_ERROR, NULL, one_tran_info::process_id, one_tran_info::program_name, one_tran_info::query_exec_info, tran_query_exec_info::query_stmt, tran_query_exec_info::query_time, tran_query_exec_info::sql_id, one_tran_info::state, tran_get_tranlist_state_name(), one_tran_info::tran_index, tran_query_exec_info::tran_time, TRANDUMP_FULL_INFO, TRANDUMP_QUERY_INFO, TRANLIST_MSG_FULL_INFO_ENTRY, TRANLIST_MSG_QUERY_INFO_ENTRY, TRANLIST_MSG_SUMMARY_ENTRY, and tran_query_exec_info::wait_for_tran_index_string.
Referenced by dump_trantb(), and kill_transactions().
int spacedb (UTIL_FUNCTION_ARG * arg)
Definition at line 844 of file util_cs.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, ASSERT_ERROR, AU_DISABLE_PASSWORDS, basename(), boot_get_lob_path(), check_database_name(), UTIL_FUNCTION_ARG::command_name, database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_error_string(), db_login(), DB_PERMANENT_DATA_PURPOSE, DB_PERMANENT_VOLTYPE, db_restart(), db_set_client_type(), db_shutdown(), er_init(), ER_NEVER_EXIT, ER_WARNING_SEVERITY, free_and_init, i, IO_PAGESIZE, LOG_PAGESIZE, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_SPACEDB, netcl_spacedb(), NO_ERROR, NULL, spacedb_all::nvols, OPTION_STRING_TABLE, output_file, PRINT_AND_LOG_ERR_MSG, prm_get_name(), PRM_ID_JAVA_STORED_PROCEDURE, PRM_ID_PB_NBUFFERS, SPACE_OUTPUT_FILE_S, SPACE_PURPOSE_S, SPACE_SIZE_UNIT_S, SPACE_SUMMARIZE_S, SPACEDB_ALL_COUNT, SPACEDB_FILE_COUNT, SPACEDB_MSG_ALL_HEADER_PAGES, SPACEDB_MSG_ALL_HEADER_SIZE, SPACEDB_MSG_BAD_OUTPUT, SPACEDB_MSG_FILES_FORMAT, SPACEDB_MSG_FILES_HEADER_PAGES, SPACEDB_MSG_FILES_HEADER_SIZE, SPACEDB_MSG_FILES_TITLE, SPACEDB_MSG_PERM_PERM_FORMAT, SPACEDB_MSG_USAGE, SPACEDB_MSG_VOLS_HEADER_PAGES, SPACEDB_MSG_VOLS_HEADER_SIZE, SPACEDB_MSG_VOLS_PERM_PERM_FORMAT, SPACEDB_MSG_VOLS_PERM_TEMP_FORMAT, SPACEDB_MSG_VOLS_TEMP_TEMP_FORMAT, SPACEDB_MSG_VOLS_TITLE, SPACEDB_OUTPUT_TITLE, SPACEDB_OUTPUT_TITLE_LOB, SPACEDB_SIZE_UNIT_GBYTES, SPACEDB_SIZE_UNIT_HUMAN_READABLE, SPACEDB_SIZE_UNIT_MBYTES, SPACEDB_SIZE_UNIT_PAGE, SPACEDB_SIZE_UNIT_TBYTES, SPACEDB_TO_SIZE_ARG, SPACEDB_TOTAL_ALL, sysprm_set_force(), TRUE, util_byte_to_size_string(), util_log_write_errid(), utility_get_option_bool_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
Referenced by file_tracker_item_spacedb().
STATIC_INLINE char * spacedb_get_size_str (char * buf, UINT64 num_pages, T_SPACEDB_SIZE_UNIT size_unit)
Definition at line 3081 of file util_cs.c.
References assert, i, IO_PAGESIZE, SPACEDB_SIZE_UNIT_HUMAN_READABLE, SPACEDB_SIZE_UNIT_MBYTES, SPACEDB_SIZE_UNIT_PAGE, SPACEDB_SIZE_UNIT_TBYTES, and UNIT_STR.
int statdump (UTIL_FUNCTION_ARG * arg)
Definition at line 2323 of file util_cs.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), check_database_name(), UTIL_FUNCTION_ARG::command_name, database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_error_string(), db_get_system_parameters(), db_login(), db_restart(), db_set_client_type(), db_shutdown(), ER_FAILED, er_init(), ER_NEVER_EXIT, histo_print_global_stats(), histo_start(), histo_stop(), intr_handler(), is_Sigint_caught, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_STATDUMP, NO_ERROR, NULL, OPTION_STRING_TABLE, os_set_signal_handler(), output_file, PRINT_AND_LOG_ERR_MSG, print_timestamp(), prm_get_name(), PRM_ID_HA_MODE, STATDUMP_CUMULATIVE_S, STATDUMP_INTERVAL_S, STATDUMP_MSG_BAD_OUTPUT, STATDUMP_MSG_NOT_IN_STANDALONE, STATDUMP_MSG_USAGE, STATDUMP_OUTPUT_FILE_S, STATDUMP_SUBSTR_S, cubregex::substr(), TRUE, util_log_write_errid(), utility_get_option_bool_value(), utility_get_option_int_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int tde (UTIL_FUNCTION_ARG * arg)
Definition at line 3716 of file util_cs.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, basename(), check_database_name(), UTIL_FUNCTION_ARG::command_name, CTIME_MAX, database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_commit_transaction(), db_error_string(), db_login(), db_restart(), db_set_client_type(), db_shutdown(), ER_AU_INVALID_PASSWORD, er_init(), ER_NEVER_EXIT, error(), fileio_mount(), KILLTRAN_DBA_PASSWORD_S, LOG_DBTDE_KEYS_VOLID, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_TDE, NO_ERROR, NULL, NULL_VOLDES, OPTION_STRING_TABLE, PRINT_AND_LOG_ERR_MSG, strlen, tde_add_mk(), TDE_CHANGE_KEY_S, tde_change_mk_on_server(), tde_create_mk(), TDE_DELETE_KEY_S, tde_delete_mk(), tde_dump_mks(), TDE_GENERATE_KEY_S, tde_get_mk_file_path(), tde_get_mk_info(), TDE_MASTER_KEY_LENGTH, TDE_MSG_DBA_PASSWORD, TDE_MSG_MK_CHANGED, TDE_MSG_MK_CHANGING, TDE_MSG_MK_DELETED, TDE_MSG_MK_GENERATED, TDE_MSG_MK_SET_ON_DATABASE_DELETE, TDE_MSG_NO_SET_MK_INFO, TDE_MSG_USAGE, TDE_PRINT_KEY_VALUE_S, tde_print_mk(), TDE_SHOW_KEYS_S, TRUE, util_log_write_errid(), utility_get_option_bool_value(), utility_get_option_int_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
int tranlist (UTIL_FUNCTION_ARG * arg)
Definition at line 1672 of file util_cs.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, au_is_dba_group_member(), Au_user, basename(), check_database_name(), UTIL_FUNCTION_ARG::command_name, database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, db_error_string(), db_login(), db_restart(), db_restart_ex(), db_set_client_type(), db_shutdown(), dump_trantb(), ER_AU_INVALID_PASSWORD, er_init(), ER_NEVER_EXIT, error(), logtb_free_trans_info(), logtb_get_trans_info(), MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_TRANLIST, NO_ERROR, NULL, trans_info::num_trans, OPTION_STRING_TABLE, PRINT_AND_LOG_ERR_MSG, trans_info::tran, TRANDUMP_FULL_INFO, TRANDUMP_SUMMARY, tranlist_cmp_f(), TRANLIST_FULL_SQL_S, TRANLIST_MSG_INVALID_SORT_KEY, TRANLIST_MSG_NOT_DBA_USER, TRANLIST_MSG_NOT_IN_STANDALONE, TRANLIST_MSG_USAGE, TRANLIST_MSG_USER_PASSWORD, TRANLIST_REVERSE_S, tranlist_Sort_column, tranlist_Sort_desc, TRANLIST_SORT_KEY_S, TRANLIST_SUMMARY_S, TRUE, util_log_write_errid(), util_log_write_errstr(), utility_get_option_bool_value(), utility_get_option_int_value(), utility_get_option_string_table_size(), and utility_get_option_string_value().
static int tranlist_cmp_f (const void * p1, const void * p2) static
Definition at line 3434 of file util_cs.c.
References assert, one_tran_info::db_user, one_tran_info::host_name, NULL, one_tran_info::process_id, one_tran_info::program_name, one_tran_info::query_exec_info, tran_query_exec_info::query_stmt, tran_query_exec_info::query_time, SORT_COLUMN_TYPE_FLOAT, SORT_COLUMN_TYPE_INT, SORT_COLUMN_TYPE_STR, tran_query_exec_info::sql_id, one_tran_info::tran_index, tran_query_exec_info::tran_time, tranlist_Sort_column, tranlist_Sort_desc, and tran_query_exec_info::wait_for_tran_index_string.
Referenced by tranlist().
static OID * util_get_class_oids_and_index_btid (dynamic_array * darray, const char * index_name, BTID * index_btid) static
Definition at line 537 of file util_cs.c.
References assert, CHECKDB_MSG_NO_SUCH_CLASS, CHECKDB_MSG_NO_SUCH_INDEX, sm_class::class_type, classobj_find_class_index(), da_get(), da_size(), db_constraint_index(), free_and_init, i, locator_find_class(), MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_NO_MEM, MSGCAT_UTIL_SET_CHECKDB, NO_ERROR, NULL, OID_SET_NULL, PRINT_AND_LOG_ERR_MSG, SM_CLASS_CT, sm_downcase_name(), SM_MAX_IDENTIFIER_LENGTH, util_log_write_errid(), ws_find(), and ws_oid().
Referenced by checkdb().
int vacuumdb (UTIL_FUNCTION_ARG * arg)
Definition at line 3560 of file util_cs.c.
References UTIL_FUNCTION_ARG::arg_map, UTIL_FUNCTION_ARG::argv0, AU_DISABLE_PASSWORDS, basename(), check_database_name(), UTIL_FUNCTION_ARG::command_name, cvacuum(), database_name, DB_CLIENT_TYPE_ADMIN_UTILITY, DB_CLIENT_TYPE_SKIP_VACUUM_ADMIN_CSQL, db_error_string(), db_login(), db_restart(), db_set_client_type(), db_set_isolation(), db_shutdown(), er_get_msglog_filename(), er_init(), ER_NEVER_EXIT, MSGCAT_CATALOG_UTILS, msgcat_message(), MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_SET_VACUUMDB, NO_ERROR, NULL, OPTION_STRING_TABLE, output_file, PRINT_AND_LOG_ERR_MSG, prm_get_name(), PRM_ID_DISABLE_VACUUM, PRM_ID_JAVA_STORED_PROCEDURE, sysprm_set_force(), TRAN_READ_COMMITTED, TRUE, util_log_write_errid(), util_log_write_errstr(), utility_get_option_bool_value(), utility_get_option_string_table_size(), utility_get_option_string_value(), vacuum_dump(), VACUUM_DUMP_S, VACUUM_OUTPUT_FILE_S, VACUUMDB_MSG_BAD_OUTPUT, VACUUMDB_MSG_CLIENT_SERVER_NOT_AVAILABLE, VACUUMDB_MSG_FAILED, and VACUUMDB_MSG_USAGE.
Variable Documentation
bool is_Sigint_caught = false static
Definition at line 102 of file util_cs.c.
Referenced by applyinfo(), intr_handler(), and statdump().
int tranlist_Sort_column = 0 static
Definition at line 99 of file util_cs.c.
Referenced by tranlist(), and tranlist_cmp_f().
bool tranlist_Sort_desc = false static
Definition at line 100 of file util_cs.c.
Referenced by tranlist(), and tranlist_cmp_f().