CUBRID Engine: src/executables/util_support.c File Reference
util_support.c File Reference
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <dlfcn.h>
#include "cubrid_getopt.h"
#include "error_code.h"
#include "util_support.h"
#include "utility.h"
#include "porting.h"
Functions
static int util_parse_string_table (UTIL_MAP *util_map, int index, int count, char **argv)
static int util_put_option_value (UTIL_MAP *util_map, int arg_ch, const char *option_arg)
static bool util_is_password_argument (int index, int value)
char * utility_make_getopt_optstring (const GETOPT_LONG *opt_array, char *buf)
int utility_load_library (DSO_HANDLE *handle, const char *path)
int utility_load_symbol (DSO_HANDLE library_handle, DSO_HANDLE *symbol_handle, const char *symbol_name)
void utility_load_print_error (FILE *fp)
static const char * util_get_option_name (GETOPT_LONG *option, int option_value)
int util_parse_argument (UTIL_MAP *util_map, int argc, char **argv)
void util_hide_password (char *arg)
Function Documentation
static const char* util_get_option_name (GETOPT_LONG * option, int option_value) static
Definition at line 162 of file util_support.c.
References i, option::name, NULL, and option::val.
Referenced by util_parse_argument().
void util_hide_password (char * arg)
Definition at line 374 of file util_support.c.
References NULL, and strlen.
Referenced by main(), and util_parse_argument().
static bool util_is_password_argument (int index, int value) static
Definition at line 233 of file util_support.c.
References KILLTRAN, KILLTRAN_DBA_PASSWORD_S, LOAD_PASSWORD_S, LOADDB, TDE, TDE_DBA_PASSWORD_S, TRANLIST, UNLOAD_PASSWORD_S, and UNLOADDB.
Referenced by util_parse_argument().
int util_parse_argument (UTIL_MAP * util_map, int argc, char ** argv)
Definition at line 186 of file util_support.c.
References ER_FAILED, getopt_long(), UTIL_MAP::getopt_long, NO_ERROR, optarg, optind, util_get_option_name(), util_hide_password(), util_is_password_argument(), util_parse_string_table(), util_put_option_value(), UTIL_MAP::utility_index, and utility_make_getopt_optstring().
Referenced by main().
static int util_parse_string_table (UTIL_MAP * util_map, int index, int count, char ** argv) static
Definition at line 324 of file util_support.c.
References UTIL_ARG_MAP::arg_ch, UTIL_MAP::arg_map, UTIL_ARG_MAP::arg_value, CHECKDB, COMPACTDB, cubregex::count(), ER_FAILED, i, UTIL_MAP::need_args_num, NO_ERROR, NULL, UTIL_ARG_MAP::num_strings, OPTION_STRING_TABLE, UTIL_ARG_MAP::p, UTIL_MAP::utility_index, and UTIL_ARG_MAP::value_info.
Referenced by util_parse_argument().
static int util_put_option_value (UTIL_MAP * util_map, int arg_ch, const char * option_arg) static
Definition at line 256 of file util_support.c.
References ARG_BIGINT, ARG_BOOLEAN, UTIL_ARG_MAP::arg_ch, ARG_INTEGER, UTIL_MAP::arg_map, ARG_STRING, UTIL_ARG_MAP::arg_value, ER_FAILED, UTIL_ARG_MAP::i, i, UTIL_ARG_MAP::l, NO_ERROR, UTIL_ARG_MAP::p, parse_bigint(), parse_int(), strdup(), and UTIL_ARG_MAP::value_type.
Referenced by util_parse_argument().
int utility_load_library (DSO_HANDLE * handle, const char * path)
Definition at line 77 of file util_support.c.
References ER_GENERIC_ERROR, NO_ERROR, NULL, UTILITY_INIT_FUNC_NAME, and utility_load_symbol().
Referenced by main(), print_admin_usage(), print_admin_version(), utility_csql_print(), and utility_csql_usage().
void utility_load_print_error (FILE * fp)
Definition at line 134 of file util_support.c.
References error(), and NULL.
Referenced by main(), print_admin_usage(), print_admin_version(), utility_csql_print(), and utility_csql_usage().
int utility_load_symbol (DSO_HANDLE library_handle, DSO_HANDLE * symbol_handle, const char * symbol_name)
Definition at line 115 of file util_support.c.
References ER_GENERIC_ERROR, NO_ERROR, and NULL.
Referenced by main(), print_admin_usage(), print_admin_version(), utility_csql_print(), utility_csql_usage(), and utility_load_library().
char* utility_make_getopt_optstring (const GETOPT_LONG * opt_array, char * buf)
Definition at line 49 of file util_support.c.
References option::has_arg, i, option::name, p, and option::val.
Referenced by main(), us_hb_status_get_options(), us_hb_stop_get_options(), us_hb_util_get_options(), and util_parse_argument().