CUBRID Engine: src/executables/util_service.c File Reference
util_service.c File Reference
#include "config.h"
#include <stdlib.h>
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <fcntl.h>
#include <assert.h>
#include <sys/wait.h>
#include "porting.h"
#include "utility.h"
#include "error_code.h"
#include "error_manager.h"
#include "system_parameter.h"
#include "connection_cl.h"
#include "util_func.h"
#include "util_support.h"
#include "environment_variable.h"
#include "release_string.h"
#include "dynamic_array.h"
#include "heartbeat.h"
Classes
struct UTIL_SERVICE_OPTION_MAP_T
struct UTIL_SERVICE_PROPERTY_T
Macros
#define UTIL_TYPE_SERVICE "service"
#define UTIL_TYPE_SERVER "server"
#define UTIL_TYPE_BROKER "broker"
#define UTIL_TYPE_MANAGER "manager"
#define UTIL_TYPE_HEARTBEAT "heartbeat"
#define UTIL_TYPE_HB_SHORT "hb"
#define UTIL_TYPE_JAVASP "javasp"
#define COMMAND_TYPE_START "start"
#define COMMAND_TYPE_STOP "stop"
#define COMMAND_TYPE_RESTART "restart"
#define COMMAND_TYPE_STATUS "status"
#define COMMAND_TYPE_DEREG "deregister"
#define COMMAND_TYPE_LIST "list"
#define COMMAND_TYPE_RELOAD "reload"
#define COMMAND_TYPE_ON "on"
#define COMMAND_TYPE_OFF "off"
#define COMMAND_TYPE_ACL "acl"
#define COMMAND_TYPE_RESET "reset"
#define COMMAND_TYPE_INFO "info"
#define COMMAND_TYPE_COPYLOGDB "copylogdb"
#define COMMAND_TYPE_APPLYLOGDB "applylogdb"
#define COMMAND_TYPE_GETID "getid"
#define COMMAND_TYPE_TEST "test"
#define COMMAND_TYPE_REPLICATION "replication"
#define COMMAND_TYPE_REPLICATION_SHORT "repl"
#define US_HB_DEREG_WAIT_TIME_IN_SEC 100
Enumerations
enum UTIL_SERVICE_INDEX_E {
SERVICE = 0, SERVER = 1, BROKER = 2, MANAGER = 3,
HEARTBEAT = 4, UTIL_HELP = 6, UTIL_VERSION = 7, ADMIN = 8,
JAVASP_UTIL = 20
}
enum UTIL_SERVICE_COMMAND_E {
START, STOP, RESTART, STATUS,
DEREGISTER, LIST, RELOAD, ON,
OFF, ACCESS_CONTROL, RESET, INFO,
SC_COPYLOGDB, SC_APPLYLOGDB, GET_SHARID, TEST,
REPLICATION
}
enum UTIL_SERVICE_PROPERTY_E {
SERVICE_START_SERVER, SERVICE_START_BROKER, SERVICE_START_MANAGER, SERVER_START_LIST,
SERVICE_START_HEARTBEAT, SERVICE_START_JAVASP, JAVASP_START_LIST
}
enum UTIL_ALL_SERVICES_STATUS { ALL_SERVICES_RUNNING, ALL_SERVICES_STOPPED }
enum UTIL_MANAGER_SERVER_STATUS_E { MANAGER_SERVER_RUNNING = 0, MANAGER_SERVER_STOPPED, MANAGER_SERVER_STATUS_ERROR }
enum UTIL_JAVASP_SERVER_STATUS_E { JAVASP_SERVER_RUNNING = 0, JAVASP_SERVER_STOPPED, JAVASP_SERVER_STATUS_ERROR }
Functions
static int util_get_service_option_mask (int util_type)
static int util_get_command_option_mask (int command_type)
static void util_service_usage (int util_type)
static void util_service_version (const char *argv0)
static int load_properties (void)
static void finalize_properties (void)
static const char * get_property (int property_type)
static int parse_arg (UTIL_SERVICE_OPTION_MAP_T *option, const char *arg)
static int process_service (int command_type, bool process_window_service)
static int process_server (int command_type, int argc, char **argv, bool show_usage, bool check_ha_mode, bool process_window_service)
static int process_broker (int command_type, int argc, const char **argv, bool process_window_service)
static int process_manager (int command_type, bool process_window_service)
static int process_javasp (int command_type, int argc, const char **argv, bool process_window_service)
static int process_javasp_start (const char *db_name, bool process_window_service)
static int process_javasp_stop (const char *db_name, bool process_window_service)
static int process_javasp_status (const char *db_name)
static int process_heartbeat (int command_type, int argc, const char **argv)
static int process_heartbeat_start (HA_CONF *ha_conf, int argc, const char **argv)
static int process_heartbeat_stop (HA_CONF *ha_conf, int argc, const char **argv)
static int process_heartbeat_deregister (int argc, const char **argv)
static int process_heartbeat_status (int argc, const char **argv)
static int process_heartbeat_reload (int argc, const char **argv)
static int process_heartbeat_util (HA_CONF *ha_conf, int command_type, int argc, const char **argv)
static int process_heartbeat_replication (HA_CONF *ha_conf, int argc, const char **argv)
static int proc_execute_internal (const char *file, const char *args[], bool wait_child, bool close_output, bool close_err, bool hide_cmd_args, int *pid)
static int proc_execute (const char *file, const char *args[], bool wait_child, bool close_output, bool close_err, int *pid)
static int proc_execute_hide_cmd_args (const char *file, const char *args[], bool wait_child, bool close_output, bool close_err, int *pid)
static void hide_cmd_line_args (char **args)
static int process_master (int command_type)
static void print_message (FILE *output, int message_id,...)
static void print_result (const char *util_name, int status, int command_type)
static bool is_terminated_process (const int pid)
static char * make_exec_abspath (char *buf, int buf_len, char *cmd)
static const char * command_string (int command_type)
static bool is_server_running (const char *type, const char *server_name, int pid)
static int is_broker_running (void)
static UTIL_MANAGER_SERVER_STATUS_E is_manager_running (unsigned int sleep_time)
static UTIL_JAVASP_SERVER_STATUS_E is_javasp_running (const char *server_name)
static bool are_all_services_running (unsigned int sleep_time, bool check_win_service)
static bool are_all_services_stopped (unsigned int sleep_time, bool check_win_service)
static bool check_all_services_status (unsigned int sleep_time, UTIL_ALL_SERVICES_STATUS expected_status, bool check_win_service)
static bool ha_make_mem_size (char *mem_size, int size, int value)
static bool ha_is_registered (const char *args, const char *hostname)
static int us_hb_copylogdb_start (dynamic_array *out_ap, HA_CONF *ha_conf, const char *db_name, const char *node_name, const char *remote_host)
static int us_hb_copylogdb_stop (HA_CONF *ha_conf, const char *db_name, const char *node_name, const char *remote_host)
static int us_hb_applylogdb_start (dynamic_array *out_ap, HA_CONF *ha_conf, const char *db_name, const char *node_name, const char *remote_host)
static int us_hb_applylogdb_stop (HA_CONF *ha_conf, const char *db_name, const char *node_name, const char *remote_host)
static int us_hb_server_start (HA_CONF *ha_conf, const char *db_name)
static int us_hb_server_stop (HA_CONF *ha_conf, const char *db_name)
static int us_hb_process_start (HA_CONF *ha_conf, const char *db_name, bool check_result)
static int us_hb_process_stop (HA_CONF *ha_conf, const char *db_name)
static int us_hb_process_copylogdb (int command_type, HA_CONF *ha_conf, const char *db_name, const char *node_name, const char *remote_host)
static int us_hb_process_applylogdb (int command_type, HA_CONF *ha_conf, const char *db_name, const char *node_name, const char *remote_host)
static int us_hb_stop_get_options (char *db_name, int db_name_size, char *host_name, int host_name_size, bool *immediate_stop, int argc, const char **argv)
static int us_hb_status_get_options (bool *verbose, char *remote_host_name, int remote_host_name_size, int argc, const char **argv)
static int us_hb_util_get_options (char *db_name, int db_name_size, char *node_name, int node_name_size, char *remote_host_name, int remote_host_name_size, int argc, const char **argv)
static int process_admin (int argc, char **argv)
int main (int argc, char *argv[])
static bool check_server (const char *type, const char *server_name)
static bool ha_make_log_path (char *path, int size, char *base, char *db, char *node)
static bool ha_concat_db_and_host (char *db_host, int size, const char *db, const char *host)
static bool ha_mkdir (const char *path, mode_t mode)
static int ha_argv_to_args (char *args, int size, const char **argv, HB_PROC_TYPE type)
static int us_hb_deactivate (const char *hostname, bool immediate_stop)
Variables
static UTIL_SERVICE_OPTION_MAP_T us_Service_map []
static UTIL_SERVICE_OPTION_MAP_T us_Command_map []
static UTIL_SERVICE_PROPERTY_T us_Property_map []
static const char ** Argv
static int ha_mode_in_common
Macro Definition Documentation
#define COMMAND_TYPE_ACL "acl"
Definition at line 207 of file util_service.c.
Referenced by process_broker().
#define COMMAND_TYPE_APPLYLOGDB "applylogdb"
Definition at line 211 of file util_service.c.
#define COMMAND_TYPE_COPYLOGDB "copylogdb"
Definition at line 210 of file util_service.c.
#define COMMAND_TYPE_DEREG "deregister"
Definition at line 202 of file util_service.c.
#define COMMAND_TYPE_GETID "getid"
Definition at line 212 of file util_service.c.
#define COMMAND_TYPE_INFO "info"
Definition at line 209 of file util_service.c.
Referenced by process_broker().
#define COMMAND_TYPE_LIST "list"
Definition at line 203 of file util_service.c.
#define COMMAND_TYPE_OFF "off"
Definition at line 206 of file util_service.c.
Referenced by process_broker().
#define COMMAND_TYPE_ON "on"
Definition at line 205 of file util_service.c.
Referenced by process_broker().
#define COMMAND_TYPE_RELOAD "reload"
Definition at line 204 of file util_service.c.
#define COMMAND_TYPE_REPLICATION "replication"
Definition at line 214 of file util_service.c.
#define COMMAND_TYPE_REPLICATION_SHORT "repl"
Definition at line 215 of file util_service.c.
#define COMMAND_TYPE_RESET "reset"
Definition at line 208 of file util_service.c.
Referenced by process_broker().
#define COMMAND_TYPE_RESTART "restart"
Definition at line 200 of file util_service.c.
#define COMMAND_TYPE_START "start"
Definition at line 198 of file util_service.c.
Referenced by process_broker(), process_javasp_start(), process_manager(), and process_server().
#define COMMAND_TYPE_STATUS "status"
Definition at line 201 of file util_service.c.
Referenced by process_javasp_status().
#define COMMAND_TYPE_STOP "stop"
Definition at line 199 of file util_service.c.
Referenced by process_broker(), process_javasp_stop(), process_manager(), and process_server().
#define COMMAND_TYPE_TEST "test"
Definition at line 213 of file util_service.c.
#define US_HB_DEREG_WAIT_TIME_IN_SEC 100
Definition at line 346 of file util_service.c.
Referenced by us_hb_applylogdb_stop(), and us_hb_copylogdb_stop().
#define UTIL_TYPE_BROKER "broker"
Definition at line 140 of file util_service.c.
Referenced by load_properties().
#define UTIL_TYPE_HB_SHORT "hb"
Definition at line 143 of file util_service.c.
#define UTIL_TYPE_HEARTBEAT "heartbeat"
Definition at line 142 of file util_service.c.
Referenced by load_properties().
#define UTIL_TYPE_JAVASP "javasp"
Definition at line 144 of file util_service.c.
Referenced by load_properties().
#define UTIL_TYPE_MANAGER "manager"
Definition at line 141 of file util_service.c.
Referenced by load_properties().
#define UTIL_TYPE_SERVER "server"
Definition at line 139 of file util_service.c.
Referenced by load_properties().
#define UTIL_TYPE_SERVICE "service"
Definition at line 138 of file util_service.c.
Enumeration Type Documentation
enum UTIL_ALL_SERVICES_STATUS
Enumerator
ALL_SERVICES_RUNNING
ALL_SERVICES_STOPPED
Definition at line 105 of file util_service.c.
enum UTIL_JAVASP_SERVER_STATUS_E
Enumerator
JAVASP_SERVER_RUNNING
JAVASP_SERVER_STOPPED
JAVASP_SERVER_STATUS_ERROR
Definition at line 118 of file util_service.c.
enum UTIL_MANAGER_SERVER_STATUS_E
Enumerator
MANAGER_SERVER_RUNNING
MANAGER_SERVER_STOPPED
MANAGER_SERVER_STATUS_ERROR
Definition at line 111 of file util_service.c.
enum UTIL_SERVICE_COMMAND_E
Enumerator
START
STOP
RESTART
STATUS
DEREGISTER
LIST
RELOAD
ON
OFF
ACCESS_CONTROL
RESET
INFO
SC_COPYLOGDB
SC_APPLYLOGDB
GET_SHARID
TEST
REPLICATION
Definition at line 73 of file util_service.c.
enum UTIL_SERVICE_INDEX_E
Enumerator
SERVICE
SERVER
BROKER
MANAGER
HEARTBEAT
UTIL_HELP
UTIL_VERSION
ADMIN
JAVASP_UTIL
Definition at line 60 of file util_service.c.
enum UTIL_SERVICE_PROPERTY_E
Enumerator
SERVICE_START_SERVER
SERVICE_START_BROKER
SERVICE_START_MANAGER
SERVER_START_LIST
SERVICE_START_HEARTBEAT
SERVICE_START_JAVASP
JAVASP_START_LIST
Definition at line 94 of file util_service.c.
Function Documentation
static bool are_all_services_running (unsigned int sleep_time, bool check_win_service) static
Definition at line 1110 of file util_service.c.
References ALL_SERVICES_RUNNING, and check_all_services_status().
Referenced by process_service().
static bool are_all_services_stopped (unsigned int sleep_time, bool check_win_service) static
Definition at line 1125 of file util_service.c.
References ALL_SERVICES_STOPPED, and check_all_services_status().
Referenced by process_service().
static bool check_all_services_status (unsigned int sleep_time, UTIL_ALL_SERVICES_STATUS expected_status, bool check_win_service) static
Definition at line 1142 of file util_service.c.
References ALL_SERVICES_RUNNING, ALL_SERVICES_STOPPED, assert, CHECK_SERVER, css_does_master_exist(), get_property(), is_broker_running(), is_javasp_running(), is_manager_running(), is_server_running(), JAVASP_SERVER_RUNNING, MANAGER_SERVER_RUNNING, MANAGER_SERVER_STOPPED, NULL, prm_get_master_port_id(), PROPERTY_ON, SERVER_START_LIST, SERVICE_START_BROKER, SERVICE_START_JAVASP, SERVICE_START_MANAGER, and SERVICE_START_SERVER.
Referenced by are_all_services_running(), and are_all_services_stopped().
static bool check_server (const char * type, const char * server_name) static
Definition at line 1454 of file util_service.c.
References CHECK_HA_SERVER, CHECK_SERVER, COMMDB_ALL_STATUS, input(), make_exec_abspath(), NULL, and UTIL_COMMDB_NAME.
Referenced by is_server_running().
static const char * command_string (int command_type) static
Definition at line 360 of file util_service.c.
References ACCESS_CONTROL, DEREGISTER, LIST, PRINT_CMD_ACL, PRINT_CMD_APPLYLOGDB, PRINT_CMD_COPYLOGDB, PRINT_CMD_DEREG, PRINT_CMD_LIST, PRINT_CMD_RELOAD, PRINT_CMD_REPLICATION, PRINT_CMD_START, PRINT_CMD_STATUS, PRINT_CMD_STOP, PRINT_CMD_TEST, RELOAD, REPLICATION, SC_APPLYLOGDB, SC_COPYLOGDB, START, STATUS, STOP, and TEST.
Referenced by print_result(), process_heartbeat_util(), process_manager(), and process_master().
static void finalize_properties (void) static
Definition at line 4807 of file util_service.c.
References free_and_init, i, NULL, and UTIL_SERVICE_PROPERTY_T::property_index.
Referenced by main().
static const char * get_property (int property_type) static
Definition at line 4830 of file util_service.c.
References UTIL_SERVICE_PROPERTY_T::property_value.
Referenced by check_all_services_status(), and process_service().
static int ha_argv_to_args (char * args, int size, const char ** argv, HB_PROC_TYPE type) static
Definition at line 2694 of file util_service.c.
References assert, ER_GENERIC_ERROR, HB_PTYPE_APPLYLOGDB, HB_PTYPE_COPYLOGDB, and NO_ERROR.
Referenced by us_hb_applylogdb_start(), us_hb_applylogdb_stop(), us_hb_copylogdb_start(), and us_hb_copylogdb_stop().
static bool ha_concat_db_and_host (char * db_host, int size, const char * db, const char * host) static
Definition at line 2610 of file util_service.c.
References ha_mkdir().
Referenced by us_hb_applylogdb_start(), us_hb_applylogdb_stop(), us_hb_copylogdb_start(), and us_hb_copylogdb_stop().
static bool ha_is_registered (const char * args, const char * hostname) static
Definition at line 2661 of file util_service.c.
References COMMDB_HOST, COMMDB_IS_REG, NO_ERROR, NULL, proc_execute(), and UTIL_COMMDB_NAME.
Referenced by us_hb_applylogdb_start(), us_hb_applylogdb_stop(), us_hb_copylogdb_start(), us_hb_copylogdb_stop(), us_hb_process_applylogdb(), and us_hb_process_copylogdb().
static bool ha_make_log_path (char * path, int size, char * base, char * db, char * node) static
Definition at line 2604 of file util_service.c.
Referenced by us_hb_applylogdb_start(), us_hb_applylogdb_stop(), us_hb_copylogdb_start(), and us_hb_copylogdb_stop().
static bool ha_make_mem_size (char * mem_size, int size, int value) static
Definition at line 2655 of file util_service.c.
Referenced by us_hb_applylogdb_start(), and us_hb_applylogdb_stop().
static bool ha_mkdir (const char * path, mode_t mode) static
Definition at line 2623 of file util_service.c.
References cub_dirname_r().
Referenced by ha_concat_db_and_host(), and us_hb_copylogdb_start().
static void hide_cmd_line_args (char ** args) static
Definition at line 955 of file util_service.c.
References assert, i, NULL, and strlen.
Referenced by proc_execute_internal().
static int is_broker_running (void) static
Definition at line 1846 of file util_service.c.
References NULL, proc_execute(), and UTIL_MONITOR_NAME.
Referenced by check_all_services_status(), and process_broker().
static UTIL_JAVASP_SERVER_STATUS_E is_javasp_running (const char * server_name) static
Definition at line 2358 of file util_service.c.
References envvar_bindir_file(), input(), JAVASP_SERVER_RUNNING, JAVASP_SERVER_STATUS_ERROR, JAVASP_SERVER_STOPPED, NULL, and UTIL_JAVASP_NAME.
Referenced by check_all_services_status(), process_javasp_start(), process_javasp_status(), and process_javasp_stop().
static UTIL_MANAGER_SERVER_STATUS_E is_manager_running (unsigned int sleep_time) static
Definition at line 2191 of file util_service.c.
References envvar_bindir_file(), input(), MANAGER_SERVER_RUNNING, MANAGER_SERVER_STATUS_ERROR, MANAGER_SERVER_STOPPED, NULL, and UTIL_CUB_MANAGER_NAME.
Referenced by check_all_services_status(), and process_manager().
static bool is_server_running (const char * type, const char * server_name, int pid) static
Definition at line 1511 of file util_service.c.
References check_server(), css_does_master_exist(), is_terminated_process(), and prm_get_master_port_id().
Referenced by check_all_services_status(), process_server(), us_hb_server_start(), and us_hb_server_stop().
static bool is_terminated_process (const int pid) static
Definition at line 4841 of file util_service.c.
References FALSE, and NULL.
Referenced by is_server_running(), process_javasp_start(), process_master(), us_hb_process_applylogdb(), us_hb_process_copylogdb(), and us_hb_process_start().
static int load_properties (void) static
Definition at line 4717 of file util_service.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_GENERIC_ERROR, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), MSGCAT_UTIL_GENERIC_INVALID_PARAMETER, NO_ERROR, NULL, prm_get_string_value(), PRM_ID_SERVICE_SERVER_LIST, PRM_ID_SERVICE_SERVICE_LIST, PROPERTY_OFF, PROPERTY_ON, UTIL_SERVICE_PROPERTY_T::property_value, SERVER_START_LIST, SERVICE_START_BROKER, SERVICE_START_HEARTBEAT, SERVICE_START_JAVASP, SERVICE_START_MANAGER, SERVICE_START_SERVER, strdup(), strlen, SYSPRM_IGNORE_INTL_PARAMS, sysprm_load_and_init(), UTIL_TYPE_BROKER, UTIL_TYPE_HEARTBEAT, UTIL_TYPE_JAVASP, UTIL_TYPE_MANAGER, UTIL_TYPE_SERVER, and utility_get_generic_message().
Referenced by main().
int main (int argc, char * argv[])
Definition at line 517 of file util_service.c.
References ADMIN, Argv, assert, BROKER, css_windows_shutdown(), css_windows_startup(), envvar_get(), envvar_prefix(), envvar_root(), envvar_set(), envvar_vardir_file(), ER_GENERIC_ERROR, ER_NEVER_EXIT, error(), finalize_properties(), ha_mode_in_common, HEARTBEAT, JAVASP_UTIL, load_properties(), MANAGER, MSGCAT_UTIL_GENERIC_SERVICE_INVALID_CMD, MSGCAT_UTIL_GENERIC_SERVICE_INVALID_NAME, MSGCAT_UTIL_GENERIC_SERVICE_PROPERTY_FAIL, NO_ERROR, NULL, parse_arg(), pid, print_message(), prm_get_integer_value(), PRM_ID_HA_MODE_FOR_SA_UTILS_ONLY, process_admin(), process_broker(), process_heartbeat(), process_javasp(), process_manager(), process_server(), process_service(), SERVER, SERVICE, usage(), util_get_command_option_mask(), util_get_service_option_mask(), UTIL_HELP, util_log_write_command(), util_log_write_errid(), util_log_write_errstr(), util_log_write_result(), UTIL_PID_ENVVAR_NAME, util_service_usage(), util_service_version(), and UTIL_VERSION.
static char * make_exec_abspath (char * buf, int buf_len, char * cmd) static
Definition at line 350 of file util_service.c.
References envvar_bindir_file().
Referenced by check_server(), and process_master().
static int parse_arg (UTIL_SERVICE_OPTION_MAP_T * option, const char * arg) static
Definition at line 4691 of file util_service.c.
References ER_GENERIC_ERROR, i, NULL, and UTIL_SERVICE_OPTION_MAP_T::option_type.
Referenced by main(), process_heartbeat_replication(), and process_heartbeat_util().
static void print_message (FILE * output, int message_id, ...) static
Definition at line 429 of file util_service.c.
References utility_get_generic_message().
Referenced by main(), print_result(), process_broker(), process_heartbeat(), process_heartbeat_deregister(), process_heartbeat_reload(), process_heartbeat_replication(), process_heartbeat_start(), process_heartbeat_status(), process_heartbeat_stop(), process_heartbeat_util(), process_javasp_start(), process_javasp_status(), process_javasp_stop(), process_manager(), process_master(), process_server(), process_service(), us_hb_applylogdb_start(), us_hb_applylogdb_stop(), us_hb_copylogdb_start(), us_hb_copylogdb_stop(), us_hb_process_start(), us_hb_process_stop(), us_hb_server_start(), us_hb_server_stop(), us_hb_status_get_options(), us_hb_stop_get_options(), us_hb_util_get_options(), util_service_usage(), and util_service_version().
static void print_result (const char * util_name, int status, int command_type) static
Definition at line 406 of file util_service.c.
References command_string(), MSGCAT_UTIL_GENERIC_RESULT, NO_ERROR, print_message(), PRINT_RESULT_FAIL, and PRINT_RESULT_SUCCESS.
Referenced by process_broker(), process_heartbeat(), process_heartbeat_deregister(), process_heartbeat_reload(), process_heartbeat_replication(), process_heartbeat_start(), process_heartbeat_stop(), process_heartbeat_util(), process_javasp_start(), process_javasp_stop(), process_manager(), process_master(), process_server(), process_service(), us_hb_applylogdb_start(), us_hb_applylogdb_stop(), us_hb_copylogdb_start(), us_hb_copylogdb_stop(), us_hb_process_start(), us_hb_process_stop(), and us_hb_server_start().
static int proc_execute (const char * file, const char * args[], bool wait_child, bool close_output, bool close_err, int * pid) static
Definition at line 751 of file util_service.c.
References proc_execute_internal().
Referenced by ha_is_registered(), is_broker_running(), process_broker(), process_heartbeat_deregister(), process_heartbeat_reload(), process_heartbeat_replication(), process_heartbeat_start(), process_heartbeat_status(), process_javasp_start(), process_javasp_status(), process_javasp_stop(), process_manager(), process_master(), process_server(), process_service(), us_hb_applylogdb_start(), us_hb_applylogdb_stop(), us_hb_copylogdb_start(), us_hb_copylogdb_stop(), and us_hb_deactivate().
static int proc_execute_hide_cmd_args (const char * file, const char * args[], bool wait_child, bool close_output, bool close_err, int * pid) static
Definition at line 762 of file util_service.c.
References envvar_bindir_file(), ER_FAILED, executable_path, i, NO_ERROR, NULL, proc_execute_internal(), strlen, and TRUE.
Referenced by process_admin().
static int proc_execute_internal (const char * file, const char * args[], bool wait_child, bool close_output, bool close_err, bool hide_cmd_args, int * pid) static
Definition at line 856 of file util_service.c.
References envvar_bindir_file(), ER_GENERIC_ERROR, executable_path, hide_cmd_line_args(), NO_ERROR, and pid.
Referenced by proc_execute(), and proc_execute_hide_cmd_args().
static int process_admin (int argc, char ** argv) static
Definition at line 447 of file util_service.c.
References argc, ER_GENERIC_ERROR, NULL, proc_execute_hide_cmd_args(), and UTIL_ADMIN_NAME.
Referenced by main().
static int process_broker (int command_type, int argc, const char ** argv, bool process_window_service) static
Definition at line 1863 of file util_service.c.
References ACCESS_CONTROL, argc, BROKER, COMMAND_TYPE_ACL, COMMAND_TYPE_INFO, COMMAND_TYPE_OFF, COMMAND_TYPE_ON, COMMAND_TYPE_RESET, COMMAND_TYPE_START, COMMAND_TYPE_STOP, ER_GENERIC_ERROR, GET_SHARID, i, INFO, is_broker_running(), MSGCAT_UTIL_GENERIC_ALREADY_RUNNING_1S, MSGCAT_UTIL_GENERIC_INVALID_CMD, MSGCAT_UTIL_GENERIC_MISS_ARGUMENT, MSGCAT_UTIL_GENERIC_NO_MEM, MSGCAT_UTIL_GENERIC_NOT_RUNNING_1S, MSGCAT_UTIL_GENERIC_START_STOP_2S, NO_ERROR, NULL, OFF, ON, PRINT_BROKER_NAME, PRINT_CMD_BROKER, PRINT_CMD_GETID, PRINT_CMD_START, PRINT_CMD_STATUS, PRINT_CMD_STOP, PRINT_CMD_TEST, print_message(), print_result(), proc_execute(), RESET, RESTART, START, STATUS, STOP, TEST, UTIL_BROKER_NAME, util_log_write_errid(), UTIL_MONITOR_NAME, util_service_usage(), and UTIL_TESTER_NAME.
Referenced by main(), and process_service().
static int process_heartbeat (int command_type, int argc, const char ** argv) static
Definition at line 4616 of file util_service.c.
References DEREGISTER, ER_FAILED, ER_GENERIC_ERROR, ha_mode_in_common, HA_MODE_OFF, LIST, MSGCAT_UTIL_GENERIC_NOT_HA_MODE, MSGCAT_UTIL_GENERIC_SERVICE_PROPERTY_FAIL, NO_ERROR, PRINT_HEARTBEAT_NAME, print_message(), print_result(), process_heartbeat_deregister(), process_heartbeat_reload(), process_heartbeat_replication(), process_heartbeat_start(), process_heartbeat_status(), process_heartbeat_stop(), process_heartbeat_util(), RELOAD, REPLICATION, SC_APPLYLOGDB, SC_COPYLOGDB, START, STATUS, STOP, util_free_ha_conf(), util_log_write_errid(), and util_make_ha_conf().
Referenced by main(), and process_service().
static int process_heartbeat_deregister (int argc, const char ** argv) static
Definition at line 4265 of file util_service.c.
References COMMDB_HA_DEREG_BY_PID, css_does_master_exist(), DEREGISTER, ER_GENERIC_ERROR, MSGCAT_UTIL_GENERIC_MISS_ARGUMENT, MSGCAT_UTIL_GENERIC_NOT_RUNNING_1S, MSGCAT_UTIL_GENERIC_START_STOP_3S, NO_ERROR, NULL, pid, PRINT_CMD_DEREG, PRINT_HEARTBEAT_NAME, PRINT_MASTER_NAME, print_message(), print_result(), prm_get_master_port_id(), proc_execute(), UTIL_COMMDB_NAME, and util_log_write_errid().
Referenced by process_heartbeat().
static int process_heartbeat_reload (int argc, const char ** argv) static
Definition at line 4428 of file util_service.c.
References COMMDB_HA_RELOAD, css_does_master_exist(), ER_GENERIC_ERROR, MSGCAT_UTIL_GENERIC_NOT_RUNNING_1S, MSGCAT_UTIL_GENERIC_START_STOP_2S, NO_ERROR, NULL, PRINT_CMD_RELOAD, PRINT_HEARTBEAT_NAME, PRINT_MASTER_NAME, print_message(), print_result(), prm_get_master_port_id(), proc_execute(), RELOAD, UTIL_COMMDB_NAME, and util_log_write_errid().
Referenced by process_heartbeat().
static int process_heartbeat_replication (HA_CONF * ha_conf, int argc, const char ** argv) static
Definition at line 4535 of file util_service.c.
References COMMDB_HA_ACTIVATE, css_does_master_exist(), ER_GENERIC_ERROR, MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_GENERIC_MISS_ARGUMENT, MSGCAT_UTIL_GENERIC_NOT_RUNNING_1S, MSGCAT_UTIL_GENERIC_START_STOP_2S, NO_ERROR, node_name, NULL, parse_arg(), PRINT_CMD_REPLICATION, PRINT_HEARTBEAT_NAME, PRINT_MASTER_NAME, print_message(), print_result(), prm_get_master_port_id(), proc_execute(), REPLICATION, START, STOP, us_hb_process_applylogdb(), us_hb_process_copylogdb(), UTIL_COMMDB_NAME, and util_log_write_errid().
Referenced by process_heartbeat().
static int process_heartbeat_start (HA_CONF * ha_conf, int argc, const char ** argv) static
Definition at line 4103 of file util_service.c.
References COMMDB_HA_ACTIVATE, css_does_master_exist(), db_name, ER_GENERIC_ERROR, HA_MODE_OFF, MSGCAT_UTIL_GENERIC_NOT_HA_MODE, MSGCAT_UTIL_GENERIC_SERVICE_PROPERTY_FAIL, MSGCAT_UTIL_GENERIC_START_STOP_2S, NO_ERROR, NULL, PRINT_CMD_START, PRINT_HEARTBEAT_NAME, print_message(), print_result(), prm_get_master_port_id(), proc_execute(), process_master(), START, SYSPRM_IGNORE_INTL_PARAMS, sysprm_load_and_init(), us_hb_deactivate(), us_hb_process_start(), us_hb_process_stop(), UTIL_COMMDB_NAME, util_get_ha_mode_for_sa_utils(), and util_log_write_errid().
Referenced by process_heartbeat().
static int process_heartbeat_status (int argc, const char ** argv) static
Definition at line 4320 of file util_service.c.
References COMMDB_HA_ADMIN_INFO, COMMDB_HA_NODE_LIST, COMMDB_HA_PING_HOST_LIST, COMMDB_HA_PROC_LIST, COMMDB_HOST, COMMDB_VERBOSE_OUTPUT, css_does_master_exist(), CUB_MAXHOSTNAMELEN, ER_GENERIC_ERROR, MSGCAT_UTIL_GENERIC_NOT_RUNNING_1S, MSGCAT_UTIL_GENERIC_START_STOP_2S, NO_ERROR, NULL, PRINT_CMD_STATUS, PRINT_HEARTBEAT_NAME, PRINT_MASTER_NAME, print_message(), prm_get_master_port_id(), proc_execute(), us_hb_status_get_options(), and UTIL_COMMDB_NAME.
Referenced by process_heartbeat().
static int process_heartbeat_stop (HA_CONF * ha_conf, int argc, const char ** argv) static
Definition at line 4183 of file util_service.c.
References css_does_master_exist(), CUB_MAXHOSTNAMELEN, db_name, ER_GENERIC_ERROR, HA_MODE_OFF, HB_STOP_WAITING_TIME_IN_SECS, MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_GENERIC_NOT_HA_MODE, MSGCAT_UTIL_GENERIC_NOT_RUNNING_1S, MSGCAT_UTIL_GENERIC_START_STOP_2S, NO_ERROR, NULL, PRINT_CMD_STOP, PRINT_HEARTBEAT_NAME, PRINT_MASTER_NAME, print_message(), print_result(), prm_get_master_port_id(), STOP, SYSPRM_IGNORE_INTL_PARAMS, sysprm_load_and_init(), us_hb_deactivate(), us_hb_process_stop(), us_hb_stop_get_options(), util_get_ha_mode_for_sa_utils(), and util_log_write_errid().
Referenced by process_heartbeat().
static int process_heartbeat_util (HA_CONF * ha_conf, int command_type, int argc, const char ** argv) static
Definition at line 4467 of file util_service.c.
References assert, command_string(), CUB_MAXHOSTNAMELEN, db_name, ER_GENERIC_ERROR, HA_MODE_OFF, MSGCAT_UTIL_GENERIC_NOT_HA_MODE, MSGCAT_UTIL_GENERIC_START_STOP_2S, NO_ERROR, node_name, NULL, parse_arg(), PRINT_HEARTBEAT_NAME, print_message(), print_result(), SC_APPLYLOGDB, SC_COPYLOGDB, SYSPRM_IGNORE_INTL_PARAMS, sysprm_load_and_init(), us_hb_process_applylogdb(), us_hb_process_copylogdb(), us_hb_util_get_options(), and util_get_ha_mode_for_sa_utils().
Referenced by process_heartbeat().
static int process_javasp (int command_type, int argc, const char ** argv, bool process_window_service) static
Definition at line 2543 of file util_service.c.
References db_name, ER_GENERIC_ERROR, JAVASP_UTIL, MSGCAT_UTIL_GENERIC_INVALID_CMD, NO_ERROR, NULL, process_javasp_start(), process_javasp_status(), process_javasp_stop(), RESTART, SERVER_START_LIST, START, STATUS, STOP, strlen, util_log_write_errid(), and util_service_usage().
Referenced by main(), and process_service().
static int process_javasp_start (const char * db_name, bool process_window_service) static
Definition at line 2403 of file util_service.c.
References COMMAND_TYPE_START, db_name, ER_GENERIC_ERROR, is_javasp_running(), is_terminated_process(), JAVASP_SERVER_RUNNING, JAVASP_SERVER_STOPPED, MSGCAT_UTIL_GENERIC_ALREADY_RUNNING_2S, MSGCAT_UTIL_GENERIC_START_STOP_3S, NO_ERROR, NULL, pid, PRINT_CMD_JAVASP, PRINT_CMD_START, PRINT_JAVASP_NAME, print_message(), print_result(), proc_execute(), START, UTIL_JAVASP_NAME, util_log_write_errid(), and util_log_write_errstr().
Referenced by process_javasp().
static int process_javasp_status (const char * db_name) static
Definition at line 2521 of file util_service.c.
References COMMAND_TYPE_STATUS, db_name, ER_GENERIC_ERROR, is_javasp_running(), JAVASP_SERVER_RUNNING, MSGCAT_UTIL_GENERIC_NOT_RUNNING_2S, MSGCAT_UTIL_GENERIC_START_STOP_3S, NO_ERROR, NULL, PRINT_CMD_STATUS, PRINT_JAVASP_NAME, print_message(), proc_execute(), UTIL_JAVASP_NAME, and util_log_write_errid().
Referenced by process_javasp().
static int process_javasp_stop (const char * db_name, bool process_window_service) static
Definition at line 2476 of file util_service.c.
References COMMAND_TYPE_STOP, db_name, ER_GENERIC_ERROR, is_javasp_running(), JAVASP_SERVER_RUNNING, MSGCAT_UTIL_GENERIC_NOT_RUNNING_2S, MSGCAT_UTIL_GENERIC_START_STOP_3S, NO_ERROR, NULL, PRINT_CMD_JAVASP, PRINT_CMD_STOP, PRINT_JAVASP_NAME, print_message(), print_result(), proc_execute(), STOP, UTIL_JAVASP_NAME, and util_log_write_errid().
Referenced by process_javasp().
static int process_manager (int command_type, bool process_window_service) static
Definition at line 2243 of file util_service.c.
References command_string(), COMMAND_TYPE_START, COMMAND_TYPE_STOP, envvar_bindir_file(), ER_GENERIC_ERROR, is_manager_running(), MANAGER_SERVER_RUNNING, MANAGER_SERVER_STATUS_ERROR, MANAGER_SERVER_STOPPED, MSGCAT_UTIL_GENERIC_ALREADY_RUNNING_1S, MSGCAT_UTIL_GENERIC_MANAGER_NOT_INSTALLED, MSGCAT_UTIL_GENERIC_NOT_RUNNING_1S, MSGCAT_UTIL_GENERIC_START_STOP_2S, NO_ERROR, NULL, PRINT_CMD_MANAGER, PRINT_MANAGER_NAME, print_message(), print_result(), proc_execute(), START, STATUS, STOP, UTIL_CUB_MANAGER_NAME, and util_log_write_errid().
Referenced by main(), and process_service().
static int process_master (int command_type) static
Definition at line 977 of file util_service.c.
References command_string(), COMMDB_ALL_STOP, css_does_master_exist(), envvar_set(), ER_GENERIC_ERROR, input(), is_terminated_process(), make_exec_abspath(), MSGCAT_UTIL_GENERIC_ALREADY_RUNNING_1S, MSGCAT_UTIL_GENERIC_NOT_RUNNING_1S, MSGCAT_UTIL_GENERIC_RESULT, MSGCAT_UTIL_GENERIC_START_STOP_2S, NO_ERROR, NULL, pid, PRINT_CMD_START, PRINT_CMD_STOP, PRINT_MASTER_NAME, print_message(), print_result(), PRINT_RESULT_FAIL, prm_get_master_port_id(), proc_execute(), START, STOP, UTIL_COMMDB_NAME, util_log_write_errid(), util_log_write_errstr(), and UTIL_MASTER_NAME.
Referenced by process_heartbeat_start(), process_server(), and process_service().
static int process_server (int command_type, int argc, char ** argv, bool show_usage, bool check_ha_mode, bool process_window_service) static
Definition at line 1557 of file util_service.c.
References ACCESS_CONTROL, ACLDB_RELOAD, CHECK_SERVER, COMMAND_TYPE_START, COMMAND_TYPE_STOP, COMMDB_SERVER_STATUS, COMMDB_SERVER_STOP, css_does_master_exist(), ER_GENERIC_ERROR, HA_MODE_OFF, is_server_running(), MSGCAT_UTIL_GENERIC_ALREADY_RUNNING_2S, MSGCAT_UTIL_GENERIC_HA_MODE, MSGCAT_UTIL_GENERIC_INVALID_CMD, MSGCAT_UTIL_GENERIC_NOT_RUNNING_1S, MSGCAT_UTIL_GENERIC_NOT_RUNNING_2S, MSGCAT_UTIL_GENERIC_SERVICE_PROPERTY_FAIL, MSGCAT_UTIL_GENERIC_START_STOP_2S, MSGCAT_UTIL_GENERIC_START_STOP_3S, NO_ERROR, NULL, pid, PRINT_CMD_SERVER, PRINT_CMD_START, PRINT_CMD_STATUS, PRINT_CMD_STOP, PRINT_MASTER_NAME, print_message(), print_result(), PRINT_SERVER_NAME, prm_get_master_port_id(), proc_execute(), process_master(), RESTART, SERVER, SERVER_START_LIST, START, STATUS, STOP, strlen, SYSPRM_IGNORE_INTL_PARAMS, sysprm_load_and_init(), UTIL_ADMIN_NAME, UTIL_COMMDB_NAME, UTIL_CUBRID_NAME, util_get_ha_mode_for_sa_utils(), util_log_write_errid(), UTIL_OPTION_ACLDB, and util_service_usage().
Referenced by main(), process_service(), us_hb_server_start(), and us_hb_server_stop().
static int process_service (int command_type, bool process_window_service) static
Definition at line 1270 of file util_service.c.
References are_all_services_running(), are_all_services_stopped(), css_does_master_exist(), ER_GENERIC_ERROR, get_property(), MSGCAT_UTIL_GENERIC_ALREADY_RUNNING_1S, MSGCAT_UTIL_GENERIC_NOT_RUNNING_1S, MSGCAT_UTIL_GENERIC_START_STOP_2S, NO_ERROR, NULL, PRINT_CMD_SERVICE, PRINT_CMD_START, PRINT_CMD_STATUS, PRINT_CMD_STOP, PRINT_MASTER_NAME, print_message(), print_result(), PRINT_SERVICE_NAME, prm_get_master_port_id(), proc_execute(), process_broker(), process_heartbeat(), process_javasp(), process_manager(), process_master(), process_server(), PROPERTY_ON, UTIL_SERVICE_PROPERTY_T::property_value, RESTART, SERVER_START_LIST, SERVICE_START_BROKER, SERVICE_START_HEARTBEAT, SERVICE_START_JAVASP, SERVICE_START_MANAGER, SERVICE_START_SERVER, START, STATUS, STOP, and util_log_write_errid().
Referenced by main().
static int us_hb_applylogdb_start (dynamic_array * out_ap, HA_CONF * ha_conf, const char * db_name, const char * node_name, const char * remote_host) static
Definition at line 3018 of file util_service.c.
References COMMDB_HA_START_UTIL_PROCESS, COMMDB_HOST, da_add(), _ha_config::db_names, ER_GENERIC_ERROR, ha_argv_to_args(), ha_concat_db_and_host(), ha_is_registered(), ha_make_log_path(), ha_make_mem_size(), HA_MODE_FAIL_BACK, HA_MODE_OFF, HB_MAX_SZ_PROC_ARGS, HB_PTYPE_APPLYLOGDB, i, MSGCAT_UTIL_GENERIC_HA_MODE_NOT_LISTED_HA_DB, MSGCAT_UTIL_GENERIC_HA_MODE_NOT_LISTED_HA_NODE, MSGCAT_UTIL_GENERIC_START_STOP_2S, NO_ERROR, _ha_config::node_conf, NULL, _ha_config::num_node_conf, pid, PRINT_CMD_START, print_message(), print_result(), PRM_ID_HA_MODE_FOR_SA_UTILS_ONLY, prm_set_integer_value(), proc_execute(), START, SYSPRM_IGNORE_INTL_PARAMS, sysprm_load_and_init(), UTIL_ADMIN_NAME, UTIL_APPLYLOGDB, UTIL_COMMDB_NAME, util_get_ha_mode_for_sa_utils(), util_is_localhost(), and util_log_write_errid().
Referenced by us_hb_applylogdb_stop(), us_hb_process_applylogdb(), and us_hb_process_start().
static int us_hb_applylogdb_stop (HA_CONF * ha_conf, const char * db_name, const char * node_name, const char * remote_host) static
Definition at line 3167 of file util_service.c.
References COMMDB_HA_DEREG_BY_ARGS, COMMDB_HOST, db_name, _ha_config::db_names, ER_GENERIC_ERROR, ha_argv_to_args(), ha_concat_db_and_host(), ha_is_registered(), ha_make_log_path(), ha_make_mem_size(), HB_MAX_SZ_PROC_ARGS, HB_PTYPE_APPLYLOGDB, i, MSGCAT_UTIL_GENERIC_HA_MODE_NOT_LISTED_HA_DB, MSGCAT_UTIL_GENERIC_HA_MODE_NOT_LISTED_HA_NODE, MSGCAT_UTIL_GENERIC_START_STOP_2S, NO_ERROR, _ha_config::node_conf, node_name, NULL, _ha_config::num_node_conf, PRINT_CMD_STOP, print_message(), print_result(), proc_execute(), STOP, us_hb_applylogdb_start(), us_hb_copylogdb_start(), us_hb_copylogdb_stop(), US_HB_DEREG_WAIT_TIME_IN_SEC, UTIL_ADMIN_NAME, UTIL_APPLYLOGDB, UTIL_COMMDB_NAME, util_is_localhost(), and util_log_write_errid().
Referenced by us_hb_process_applylogdb(), and us_hb_process_stop().
static int us_hb_copylogdb_start (dynamic_array * out_ap, HA_CONF * ha_conf, const char * db_name, const char * node_name, const char * remote_host) static
Definition at line 2736 of file util_service.c.
References COMMDB_HA_START_UTIL_PROCESS, COMMDB_HOST, _node_config::copy_sync_mode, da_add(), _ha_config::db_names, ER_GENERIC_ERROR, ha_argv_to_args(), ha_concat_db_and_host(), ha_is_registered(), ha_make_log_path(), ha_mkdir(), HA_MODE_FAIL_BACK, HA_MODE_OFF, HB_MAX_SZ_PROC_ARGS, HB_PTYPE_COPYLOGDB, i, MSGCAT_UTIL_GENERIC_HA_MODE_NOT_LISTED_HA_DB, MSGCAT_UTIL_GENERIC_HA_MODE_NOT_LISTED_HA_NODE, MSGCAT_UTIL_GENERIC_START_STOP_2S, NO_ERROR, _ha_config::node_conf, NULL, _ha_config::num_node_conf, pid, PRINT_CMD_START, print_message(), print_result(), PRM_ID_HA_MODE_FOR_SA_UTILS_ONLY, prm_set_integer_value(), proc_execute(), START, SYSPRM_IGNORE_INTL_PARAMS, sysprm_load_and_init(), UTIL_ADMIN_NAME, UTIL_COMMDB_NAME, UTIL_COPYLOGDB, util_get_ha_mode_for_sa_utils(), util_is_localhost(), and util_log_write_errid().
Referenced by us_hb_applylogdb_stop(), us_hb_process_copylogdb(), and us_hb_process_start().
static int us_hb_copylogdb_stop (HA_CONF * ha_conf, const char * db_name, const char * node_name, const char * remote_host) static
Definition at line 2888 of file util_service.c.
References COMMDB_HA_DEREG_BY_ARGS, COMMDB_HOST, _node_config::copy_sync_mode, _ha_config::db_names, ER_GENERIC_ERROR, ha_argv_to_args(), ha_concat_db_and_host(), ha_is_registered(), ha_make_log_path(), HB_MAX_SZ_PROC_ARGS, HB_PTYPE_COPYLOGDB, i, MSGCAT_UTIL_GENERIC_HA_MODE_NOT_LISTED_HA_DB, MSGCAT_UTIL_GENERIC_HA_MODE_NOT_LISTED_HA_NODE, MSGCAT_UTIL_GENERIC_START_STOP_2S, NO_ERROR, _ha_config::node_conf, NULL, _ha_config::num_node_conf, PRINT_CMD_STOP, print_message(), print_result(), proc_execute(), STOP, US_HB_DEREG_WAIT_TIME_IN_SEC, UTIL_ADMIN_NAME, UTIL_COMMDB_NAME, UTIL_COPYLOGDB, util_is_localhost(), and util_log_write_errid().
Referenced by us_hb_applylogdb_stop(), us_hb_process_copylogdb(), and us_hb_process_stop().
static int us_hb_deactivate (const char * hostname, bool immediate_stop) static
Definition at line 3495 of file util_service.c.
References COMMDB_HA_DEACT_CONFIRM_NO_SERVER, COMMDB_HA_DEACT_CONFIRM_STOP_ALL, COMMDB_HA_DEACT_STOP_ALL, COMMDB_HA_DEACTIVATE, COMMDB_HB_DEACT_IMMEDIATELY, COMMDB_HOST, NO_ERROR, NULL, proc_execute(), and UTIL_COMMDB_NAME.
Referenced by process_heartbeat_start(), and process_heartbeat_stop().
static int us_hb_process_applylogdb (int command_type, HA_CONF * ha_conf, const char * db_name, const char * node_name, const char * remote_host) static
Definition at line 3669 of file util_service.c.
References da_create(), da_destroy(), da_get(), da_size(), db_name, ER_GENERIC_ERROR, ha_is_registered(), HB_START_WAITING_TIME_IN_SECS, i, is_terminated_process(), NO_ERROR, NULL, pid, START, STOP, us_hb_applylogdb_start(), us_hb_applylogdb_stop(), us_hb_server_start(), and us_hb_server_stop().
Referenced by process_heartbeat_replication(), and process_heartbeat_util().
static int us_hb_process_copylogdb (int command_type, HA_CONF * ha_conf, const char * db_name, const char * node_name, const char * remote_host) static
Definition at line 3583 of file util_service.c.
References da_create(), da_destroy(), da_get(), da_size(), ER_GENERIC_ERROR, ha_is_registered(), HB_START_WAITING_TIME_IN_SECS, i, is_terminated_process(), NO_ERROR, NULL, pid, START, STOP, us_hb_copylogdb_start(), and us_hb_copylogdb_stop().
Referenced by process_heartbeat_replication(), and process_heartbeat_util().
static int us_hb_process_start (HA_CONF * ha_conf, const char * db_name, bool check_result) static
Definition at line 3429 of file util_service.c.
References da_create(), da_destroy(), da_get(), da_size(), ER_GENERIC_ERROR, HB_START_WAITING_TIME_IN_SECS, i, is_terminated_process(), MSGCAT_UTIL_GENERIC_START_STOP_2S, NO_ERROR, NULL, pid, PRINT_CMD_START, PRINT_HA_PROCS_NAME, print_message(), print_result(), START, us_hb_applylogdb_start(), us_hb_copylogdb_start(), and us_hb_server_start().
Referenced by process_heartbeat_start().
static int us_hb_process_stop (HA_CONF * ha_conf, const char * db_name) static
Definition at line 3557 of file util_service.c.
References MSGCAT_UTIL_GENERIC_START_STOP_2S, NO_ERROR, NULL, PRINT_CMD_STOP, PRINT_HA_PROCS_NAME, print_message(), print_result(), STOP, us_hb_applylogdb_stop(), us_hb_copylogdb_stop(), and us_hb_server_stop().
Referenced by process_heartbeat_start(), and process_heartbeat_stop().
static int us_hb_server_start (HA_CONF * ha_conf, const char * db_name) static
Definition at line 3330 of file util_service.c.
References CHECK_SERVER, _ha_config::db_names, ER_GENERIC_ERROR, HA_MODE_FAIL_BACK, HA_MODE_OFF, i, is_server_running(), MSGCAT_UTIL_GENERIC_ALREADY_RUNNING_2S, MSGCAT_UTIL_GENERIC_HA_MODE_NOT_LISTED_HA_DB, MSGCAT_UTIL_GENERIC_NOT_HA_MODE, MSGCAT_UTIL_GENERIC_SERVICE_PROPERTY_FAIL, NO_ERROR, NULL, print_message(), print_result(), PRINT_SERVER_NAME, PRM_ID_HA_MODE_FOR_SA_UTILS_ONLY, prm_set_integer_value(), process_server(), START, SYSPRM_IGNORE_INTL_PARAMS, sysprm_load_and_init(), util_get_ha_mode_for_sa_utils(), and util_log_write_errid().
Referenced by us_hb_process_applylogdb(), and us_hb_process_start().
static int us_hb_server_stop (HA_CONF * ha_conf, const char * db_name) static
Definition at line 3388 of file util_service.c.
References CHECK_SERVER, _ha_config::db_names, ER_GENERIC_ERROR, i, is_server_running(), MSGCAT_UTIL_GENERIC_HA_MODE_NOT_LISTED_HA_DB, MSGCAT_UTIL_GENERIC_NOT_RUNNING_2S, NO_ERROR, NULL, print_message(), PRINT_SERVER_NAME, process_server(), STOP, and util_log_write_errid().
Referenced by us_hb_process_applylogdb(), and us_hb_process_stop().
static int us_hb_status_get_options (bool * verbose, char * remote_host_name, int remote_host_name_size, int argc, const char ** argv) static
Definition at line 3895 of file util_service.c.
References COMMDB_HOST_L, COMMDB_HOST_S, ER_GENERIC_ERROR, free_and_init, getopt_long(), MSGCAT_UTIL_GENERIC_ARGS_OVER, MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_GENERIC_NO_MEM, NO_ERROR, NULL, optarg, optind, PRINT_CMD_STATUS, PRINT_HEARTBEAT_NAME, print_message(), util_log_write_errid(), and utility_make_getopt_optstring().
Referenced by process_heartbeat_status().
static int us_hb_stop_get_options (char * db_name, int db_name_size, char * host_name, int host_name_size, bool * immediate_stop, int argc, const char ** argv) static
Definition at line 3792 of file util_service.c.
References COMMDB_HB_DEACT_IMMEDIATELY_L, COMMDB_HB_DEACT_IMMEDIATELY_S, COMMDB_HOST_L, COMMDB_HOST_S, ER_GENERIC_ERROR, free_and_init, getopt_long(), MSGCAT_UTIL_GENERIC_ARGS_OVER, MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_GENERIC_NO_MEM, NO_ERROR, NULL, optarg, optind, PRINT_CMD_STOP, PRINT_HEARTBEAT_NAME, print_message(), util_log_write_errid(), and utility_make_getopt_optstring().
Referenced by process_heartbeat_stop().
static int us_hb_util_get_options (char * db_name, int db_name_size, char * node_name, int node_name_size, char * remote_host_name, int remote_host_name_size, int argc, const char ** argv) static
Definition at line 3990 of file util_service.c.
References COMMDB_HOST_L, COMMDB_HOST_S, ER_GENERIC_ERROR, free_and_init, getopt_long(), MSGCAT_UTIL_GENERIC_ARGS_OVER, MSGCAT_UTIL_GENERIC_INVALID_ARGUMENT, MSGCAT_UTIL_GENERIC_MISS_ARGUMENT, MSGCAT_UTIL_GENERIC_NO_MEM, NO_ERROR, NULL, optarg, optind, PRINT_HEARTBEAT_NAME, print_message(), util_log_write_errid(), and utility_make_getopt_optstring().
Referenced by process_heartbeat_util().
static int util_get_command_option_mask (int command_type) static
Definition at line 495 of file util_service.c.
References i, UTIL_SERVICE_OPTION_MAP_T::option_mask, and UTIL_SERVICE_OPTION_MAP_T::option_type.
Referenced by main().
static int util_get_service_option_mask (int util_type) static
Definition at line 474 of file util_service.c.
References ADMIN, assert, i, UTIL_SERVICE_OPTION_MAP_T::option_mask, and UTIL_SERVICE_OPTION_MAP_T::option_type.
Referenced by main().
static void util_service_usage (int util_type) static
Definition at line 712 of file util_service.c.
References Argv, basename(), MSGCAT_UTIL_GENERIC_CUBRID_USAGE, and print_message().
Referenced by main(), process_broker(), process_javasp(), and process_server().
static void util_service_version (const char * argv0) static
Definition at line 737 of file util_service.c.
References basename(), MSGCAT_UTIL_GENERIC_VERSION, print_message(), rel_copy_version_string(), and REL_MAX_VERSION_LENGTH.
Referenced by main().
Variable Documentation
const char** Argv static
Definition at line 250 of file util_service.c.
Referenced by main(), and util_service_usage().
int ha_mode_in_common static
Definition at line 251 of file util_service.c.
Referenced by main(), and process_heartbeat().
UTIL_SERVICE_OPTION_MAP_T us_Command_map[] static
Initial value:
= {
  {START, COMMAND_TYPE_START, MASK_ALL},
  {STOP, COMMAND_TYPE_STOP, MASK_ALL},
  {RESTART, COMMAND_TYPE_RESTART, MASK_SERVICE | MASK_SERVER | MASK_BROKER | MASK_JAVASP},
  {STATUS, COMMAND_TYPE_STATUS, MASK_ALL},
  {DEREGISTER, COMMAND_TYPE_DEREG, MASK_HEARTBEAT},
  {LIST, COMMAND_TYPE_LIST, MASK_HEARTBEAT},
  {RELOAD, COMMAND_TYPE_RELOAD, MASK_HEARTBEAT},
  {ON, COMMAND_TYPE_ON, MASK_BROKER},
  {OFF, COMMAND_TYPE_OFF, MASK_BROKER},
  {ACCESS_CONTROL, COMMAND_TYPE_ACL, MASK_SERVER | MASK_BROKER},
  {RESET, COMMAND_TYPE_RESET, MASK_BROKER},
  {INFO, COMMAND_TYPE_INFO, MASK_BROKER},
  {SC_COPYLOGDB, COMMAND_TYPE_COPYLOGDB, MASK_HEARTBEAT},
  {SC_APPLYLOGDB, COMMAND_TYPE_APPLYLOGDB, MASK_HEARTBEAT},
  {GET_SHARID, COMMAND_TYPE_GETID, MASK_BROKER},
  {TEST, COMMAND_TYPE_TEST, MASK_BROKER},
  {REPLICATION, COMMAND_TYPE_REPLICATION, MASK_HEARTBEAT},
  {REPLICATION, COMMAND_TYPE_REPLICATION_SHORT, MASK_HEARTBEAT},
  {-1, "", MASK_ALL}
}
Definition at line 217 of file util_service.c.
UTIL_SERVICE_PROPERTY_T us_Property_map[] static
Initial value:
= {
  {SERVICE_START_SERVER, NULL},
  {SERVICE_START_BROKER, NULL},
  {SERVICE_START_MANAGER, NULL},
  {SERVER_START_LIST, NULL},
  {SERVICE_START_HEARTBEAT, NULL},
  {SERVICE_START_JAVASP, NULL},
  {-1, NULL}
}
Definition at line 239 of file util_service.c.
UTIL_SERVICE_OPTION_MAP_T us_Service_map[] static
Definition at line 146 of file util_service.c.