CUBRID Engine: src/query/xasl_to_stream.c File Reference
xasl_to_stream.c File Reference
#include "config.h"
#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include "xasl_to_stream.h"
#include "error_manager.h"
#include "server_interface.h"
#include "class_object.h"
#include "object_primitive.h"
#include "work_space.h"
#include "memory_alloc.h"
#include "xasl.h"
#include "xasl_aggregate.hpp"
#include "xasl_analytic.hpp"
#include "xasl_predicate.hpp"
#include "xasl_stream.hpp"
#include "xasl_unpack_info.hpp"
Classes
struct xts_visited_ptr
Macros
#define BYTE_SIZE OR_INT_SIZE
#define LONG_SIZE OR_INT_SIZE
#define PTR_SIZE OR_INT_SIZE
#define pack_char or_pack_int
#define pack_long or_pack_int
#define OFFSET_BUFFER_SIZE 32
Typedefs
typedef struct xts_visited_ptr XTS_VISITED_PTR
Functions
static int xts_save_aggregate_type (const AGGREGATE_TYPE *aggregate)
static int xts_save_function_type (const FUNCTION_TYPE *function)
static int xts_save_analytic_type (const ANALYTIC_TYPE *analytic)
static int xts_save_analytic_eval_type (const ANALYTIC_EVAL_TYPE *analytic)
static int xts_save_srlist_id (const QFILE_SORTED_LIST_ID *sort_list_id)
static int xts_save_list_id (const QFILE_LIST_ID *list_id)
static int xts_save_arith_type (const ARITH_TYPE *arithmetic)
static int xts_save_indx_info (const INDX_INFO *indx_info)
static int xts_save_outptr_list (const OUTPTR_LIST *outptr_list)
static int xts_save_selupd_list (const SELUPD_LIST *selupd_list)
static int xts_save_pred_expr (const PRED_EXPR *ptr)
static int xts_save_regu_variable (const REGU_VARIABLE *ptr)
static int xts_save_regu_variable_list (const REGU_VARIABLE_LIST ptr)
static int xts_save_regu_varlist_list (const REGU_VARLIST_LIST ptr)
static int xts_save_sort_list (const SORT_LIST *ptr)
static int xts_save_string (const char *str)
static int xts_save_val_list (const VAL_LIST *ptr)
static int xts_save_db_value (const DB_VALUE *ptr)
static int xts_save_xasl_node (const XASL_NODE *ptr)
static int xts_save_filter_pred_node (const PRED_EXPR_WITH_CONTEXT *pred)
static int xts_save_func_pred (const FUNC_PRED *ptr)
static int xts_save_cache_attrinfo (const HEAP_CACHE_ATTRINFO *ptr)
template<typename T >
static int xts_save (const T &t)
template<typename T >
static void xts_debug_check (const T &t, char *pack_start, const char *pack_end)
template<typename T >
static void xts_debug_clear (T &t)
static int xts_save_db_value_array (DB_VALUE **ptr, int size)
static int xts_save_int_array (int *ptr, int size)
static int xts_save_hfid_array (HFID *ptr, int size)
static int xts_save_oid_array (OID *ptr, int size)
static int xts_save_method_sig_list (const METHOD_SIG_LIST *ptr)
static int xts_save_method_sig (const METHOD_SIG *ptr, int size)
static int xts_save_key_range_array (const KEY_RANGE *ptr, int size)
static int xts_save_upddel_class_info_array (const UPDDEL_CLASS_INFO *classes, int nelements)
static int xts_save_update_assignment_array (const UPDATE_ASSIGNMENT *assigns, int nelements)
static int xts_save_odku_info (const ODKU_INFO *odku_info)
static char * xts_process (char *ptr, const json_table_column &json_table_col)
static char * xts_process (char *ptr, const json_table_node &json_table_node)
static char * xts_process (char *ptr, const json_table_spec_node &set_spec)
static char * xts_process_xasl_node (char *ptr, const XASL_NODE *xasl)
static char * xts_process_xasl_header (char *ptr, const XASL_NODE_HEADER header)
static char * xts_process_filter_pred_node (char *ptr, const PRED_EXPR_WITH_CONTEXT *pred)
static char * xts_process_func_pred (char *ptr, const FUNC_PRED *xasl)
static char * xts_process_cache_attrinfo (char *ptr)
static char * xts_process_union_proc (char *ptr, const UNION_PROC_NODE *union_proc)
static char * xts_process_fetch_proc (char *ptr, const FETCH_PROC_NODE *obj_set_fetch_proc)
static char * xts_process_buildlist_proc (char *ptr, const BUILDLIST_PROC_NODE *build_list_proc)
static char * xts_process_buildvalue_proc (char *ptr, const BUILDVALUE_PROC_NODE *build_value_proc)
static char * xts_process_mergelist_proc (char *ptr, const MERGELIST_PROC_NODE *merge_list_info)
static char * xts_process_ls_merge_info (char *ptr, const QFILE_LIST_MERGE_INFO *qfile_list_merge_info)
static char * xts_save_upddel_class_info (char *ptr, const UPDDEL_CLASS_INFO *upd_cls)
static char * xts_save_update_assignment (char *ptr, const UPDATE_ASSIGNMENT *assign)
static char * xts_process_update_proc (char *ptr, const UPDATE_PROC_NODE *update_info)
static char * xts_process_delete_proc (char *ptr, const DELETE_PROC_NODE *delete_proc)
static char * xts_process_insert_proc (char *ptr, const INSERT_PROC_NODE *insert_proc)
static char * xts_process_merge_proc (char *ptr, const MERGE_PROC_NODE *merge_info)
static char * xts_process_cte_proc (char *ptr, const CTE_PROC_NODE *cte_proc)
static char * xts_process_outptr_list (char *ptr, const OUTPTR_LIST *outptr_list)
static char * xts_process_selupd_list (char *ptr, const SELUPD_LIST *selupd_list)
static char * xts_process_pred_expr (char *ptr, const PRED_EXPR *pred_expr)
static char * xts_process_pred (char *ptr, const PRED *pred)
static char * xts_process_eval_term (char *ptr, const EVAL_TERM *eval_term)
static char * xts_process_comp_eval_term (char *ptr, const COMP_EVAL_TERM *comp_eval_term)
static char * xts_process_alsm_eval_term (char *ptr, const ALSM_EVAL_TERM *alsm_eval_term)
static char * xts_process_like_eval_term (char *ptr, const LIKE_EVAL_TERM *like_eval_term)
static char * xts_process_rlike_eval_term (char *ptr, const RLIKE_EVAL_TERM *rlike_eval_term)
static char * xts_process_access_spec_type (char *ptr, const ACCESS_SPEC_TYPE *access_spec)
static char * xts_process_indx_info (char *ptr, const INDX_INFO *indx_info)
static char * xts_process_key_info (char *ptr, const KEY_INFO *key_info)
static char * xts_process_cls_spec_type (char *ptr, const CLS_SPEC_TYPE *cls_spec)
static char * xts_process_list_spec_type (char *ptr, const LIST_SPEC_TYPE *list_spec)
static char * xts_process_showstmt_spec_type (char *ptr, const SHOWSTMT_SPEC_TYPE *list_spec)
static char * xts_process_set_spec_type (char *ptr, const SET_SPEC_TYPE *set_spec)
static char * xts_process_json_table_column_behavior (char *ptr, const json_table_column_behavior *behavior)
static char * xts_process_method_spec_type (char *ptr, const METHOD_SPEC_TYPE *method_spec)
static char * xts_process_rlist_spec_type (char *ptr, const LIST_SPEC_TYPE *list_spec)
static char * xts_process_list_id (char *ptr, const QFILE_LIST_ID *list_id)
static char * xts_process_val_list (char *ptr, const VAL_LIST *val_list)
static char * xts_process_regu_variable (char *ptr, const REGU_VARIABLE *regu_var)
static char * xts_pack_regu_variable_value (char *ptr, const REGU_VARIABLE *regu_var)
static char * xts_process_attr_descr (char *ptr, const ATTR_DESCR *attr_descr)
static char * xts_process_pos_descr (char *ptr, const QFILE_TUPLE_VALUE_POSITION *position_descr)
static char * xts_process_db_value (char *ptr, const DB_VALUE *value)
static char * xts_process_arith_type (char *ptr, const ARITH_TYPE *arith)
static char * xts_process_aggregate_type (char *ptr, const AGGREGATE_TYPE *aggregate)
static char * xts_process_analytic_type (char *ptr, const ANALYTIC_TYPE *analytic)
static char * xts_process_analytic_eval_type (char *ptr, const ANALYTIC_EVAL_TYPE *analytic)
static char * xts_process_function_type (char *ptr, const FUNCTION_TYPE *function)
static char * xts_process_srlist_id (char *ptr, const QFILE_SORTED_LIST_ID *sort_list_id)
static char * xts_process_sort_list (char *ptr, const SORT_LIST *sort_list)
static char * xts_process_method_sig_list (char *ptr, const METHOD_SIG_LIST *method_sig_list)
static char * xts_process_method_sig (char *ptr, const METHOD_SIG *method_sig, int size)
static char * xts_process_connectby_proc (char *ptr, const CONNECTBY_PROC_NODE *connectby_proc)
static char * xts_process_regu_value_list (char *ptr, const REGU_VALUE_LIST *regu_value_list)
static int xts_sizeof (const json_table_column &ptr)
static int xts_sizeof (const json_table_node &ptr)
static int xts_sizeof (const json_table_spec_node &ptr)
static int xts_sizeof_xasl_node (const XASL_NODE *ptr)
static int xts_sizeof_filter_pred_node (const PRED_EXPR_WITH_CONTEXT *ptr)
static int xts_sizeof_func_pred (const FUNC_PRED *ptr)
static int xts_sizeof_cache_attrinfo (const HEAP_CACHE_ATTRINFO *ptr)
static int xts_sizeof_union_proc (const UNION_PROC_NODE *ptr)
static int xts_sizeof_fetch_proc (const FETCH_PROC_NODE *ptr)
static int xts_sizeof_buildlist_proc (const BUILDLIST_PROC_NODE *ptr)
static int xts_sizeof_buildvalue_proc (const BUILDVALUE_PROC_NODE *ptr)
static int xts_sizeof_mergelist_proc (const MERGELIST_PROC_NODE *ptr)
static int xts_sizeof_ls_merge_info (const QFILE_LIST_MERGE_INFO *ptr)
static int xts_sizeof_upddel_class_info (const UPDDEL_CLASS_INFO *upd_cls)
static int xts_sizeof_update_assignment (const UPDATE_ASSIGNMENT *assign)
static int xts_sizeof_odku_info (const ODKU_INFO *odku_info)
static int xts_sizeof_update_proc (const UPDATE_PROC_NODE *ptr)
static int xts_sizeof_delete_proc (const DELETE_PROC_NODE *ptr)
static int xts_sizeof_insert_proc (const INSERT_PROC_NODE *ptr)
static int xts_sizeof_merge_proc (const MERGE_PROC_NODE *ptr)
static int xts_sizeof_outptr_list (const OUTPTR_LIST *ptr)
static int xts_sizeof_selupd_list (const SELUPD_LIST *ptr)
static int xts_sizeof_pred_expr (const PRED_EXPR *ptr)
static int xts_sizeof_pred (const PRED *ptr)
static int xts_sizeof_eval_term (const EVAL_TERM *ptr)
static int xts_sizeof_comp_eval_term (const COMP_EVAL_TERM *ptr)
static int xts_sizeof_alsm_eval_term (const ALSM_EVAL_TERM *ptr)
static int xts_sizeof_like_eval_term (const LIKE_EVAL_TERM *ptr)
static int xts_sizeof_rlike_eval_term (const RLIKE_EVAL_TERM *ptr)
static int xts_sizeof_access_spec_type (const ACCESS_SPEC_TYPE *ptr)
static int xts_sizeof_indx_info (const INDX_INFO *ptr)
static int xts_sizeof_key_info (const KEY_INFO *ptr)
static int xts_sizeof_cls_spec_type (const CLS_SPEC_TYPE *ptr)
static int xts_sizeof_list_spec_type (const LIST_SPEC_TYPE *ptr)
static int xts_sizeof_showstmt_spec_type (const SHOWSTMT_SPEC_TYPE *ptr)
static int xts_sizeof_set_spec_type (const SET_SPEC_TYPE *ptr)
static int xts_sizeof_method_spec_type (const METHOD_SPEC_TYPE *ptr)
static int xts_sizeof_json_table_column_behavior (const json_table_column_behavior *behavior)
static int xts_sizeof_list_id (const QFILE_LIST_ID *ptr)
static int xts_sizeof_val_list (const VAL_LIST *ptr)
static int xts_sizeof_regu_variable (const REGU_VARIABLE *ptr)
static int xts_get_regu_variable_value_size (const REGU_VARIABLE *ptr)
static int xts_sizeof_attr_descr (const ATTR_DESCR *ptr)
static int xts_sizeof_pos_descr (const QFILE_TUPLE_VALUE_POSITION *ptr)
static int xts_sizeof_db_value (const DB_VALUE *ptr)
static int xts_sizeof_arith_type (const ARITH_TYPE *ptr)
static int xts_sizeof_aggregate_type (const AGGREGATE_TYPE *ptr)
static int xts_sizeof_function_type (const FUNCTION_TYPE *ptr)
static int xts_sizeof_analytic_type (const ANALYTIC_TYPE *ptr)
static int xts_sizeof_analytic_eval_type (const ANALYTIC_EVAL_TYPE *ptr)
static int xts_sizeof_srlist_id (const QFILE_SORTED_LIST_ID *ptr)
static int xts_sizeof_sort_list (const SORT_LIST *ptr)
static int xts_sizeof_method_sig_list (const METHOD_SIG_LIST *ptr)
static int xts_sizeof_method_sig (const METHOD_SIG *ptr)
static int xts_sizeof_connectby_proc (const CONNECTBY_PROC_NODE *ptr)
static int xts_sizeof_regu_value_list (const REGU_VALUE_LIST *regu_value_list)
static int xts_sizeof_cte_proc (const CTE_PROC_NODE *ptr)
static int xts_mark_ptr_visited (const void *ptr, int offset)
static int xts_get_offset_visited_ptr (const void *ptr)
static void xts_free_visited_ptrs (void)
static int xts_reserve_location_in_stream (int size)
static int xts_sizeof_regu_variable_list (const REGU_VARIABLE_LIST regu_var_list)
static char * xts_process_regu_variable_list (char *ptr, const REGU_VARIABLE_LIST regu_var_list)
int xts_map_xasl_to_stream (const XASL_NODE *xasl_tree, XASL_STREAM *stream)
int xts_map_filter_pred_to_stream (const PRED_EXPR_WITH_CONTEXT *pred, char **pred_stream, int *pred_stream_size)
int xts_map_func_pred_to_stream (const FUNC_PRED *xasl_tree, char **xasl_stream, int *xasl_stream_size)
Variables
static char * xts_Stream_buffer = NULL
static int xts_Stream_size = 0
static int xts_Free_offset_in_stream = 0
static XTS_VISITED_PTR * xts_Ptr_blocks [MAX_PTR_BLOCKS] = { 0 }
static int xts_Ptr_lwm [MAX_PTR_BLOCKS] = { 0 }
static int xts_Ptr_max [MAX_PTR_BLOCKS] = { 0 }
static int xts_Xasl_errcode = NO_ERROR
Macro Definition Documentation
#define BYTE_SIZE OR_INT_SIZE
Definition at line 48 of file xasl_to_stream.c.
#define LONG_SIZE OR_INT_SIZE
Definition at line 49 of file xasl_to_stream.c.
#define OFFSET_BUFFER_SIZE 32
Definition at line 2512 of file xasl_to_stream.c.
Referenced by xts_save_regu_variable_list(), and xts_save_regu_varlist_list().
#define pack_char or_pack_int
Definition at line 51 of file xasl_to_stream.c.
#define pack_long or_pack_int
Definition at line 52 of file xasl_to_stream.c.
#define PTR_SIZE OR_INT_SIZE
Definition at line 50 of file xasl_to_stream.c.
Referenced by xts_get_regu_variable_value_size(), xts_sizeof(), xts_sizeof_access_spec_type(), xts_sizeof_aggregate_type(), xts_sizeof_alsm_eval_term(), xts_sizeof_analytic_eval_type(), xts_sizeof_analytic_type(), xts_sizeof_arith_type(), xts_sizeof_attr_descr(), xts_sizeof_buildlist_proc(), xts_sizeof_buildvalue_proc(), xts_sizeof_cls_spec_type(), xts_sizeof_comp_eval_term(), xts_sizeof_connectby_proc(), xts_sizeof_cte_proc(), xts_sizeof_delete_proc(), xts_sizeof_fetch_proc(), xts_sizeof_filter_pred_node(), xts_sizeof_func_pred(), xts_sizeof_function_type(), xts_sizeof_indx_info(), xts_sizeof_insert_proc(), xts_sizeof_key_info(), xts_sizeof_like_eval_term(), xts_sizeof_list_spec_type(), xts_sizeof_ls_merge_info(), xts_sizeof_merge_proc(), xts_sizeof_mergelist_proc(), xts_sizeof_method_sig(), xts_sizeof_method_sig_list(), xts_sizeof_method_spec_type(), xts_sizeof_odku_info(), xts_sizeof_outptr_list(), xts_sizeof_pred(), xts_sizeof_pred_expr(), xts_sizeof_regu_variable(), xts_sizeof_rlike_eval_term(), xts_sizeof_selupd_list(), xts_sizeof_set_spec_type(), xts_sizeof_showstmt_spec_type(), xts_sizeof_sort_list(), xts_sizeof_srlist_id(), xts_sizeof_union_proc(), xts_sizeof_update_assignment(), xts_sizeof_update_proc(), xts_sizeof_upddel_class_info(), xts_sizeof_val_list(), and xts_sizeof_xasl_node().
Typedef Documentation
typedef struct xts_visited_ptr XTS_VISITED_PTR
Definition at line 55 of file xasl_to_stream.c.
Function Documentation
template<typename T > static void xts_debug_check (const T & t, char * pack_start, const char * pack_end) static
Definition at line 7542 of file xasl_to_stream.c.
References assert, db_private_free_and_init, get_xasl_unpack_info_ptr(), NULL, set_xasl_unpack_info_ptr(), stx_build(), stx_init_xasl_unpack_info(), xasl_stream_compare(), xts_debug_clear(), xts_sizeof(), xts_Stream_buffer, and xts_Stream_size.
Referenced by xts_process().
template<typename T > static void xts_debug_clear (T & t) static
Definition at line 7590 of file xasl_to_stream.c.
Referenced by xts_debug_check().
static void xts_free_visited_ptrs (void) static
Definition at line 7405 of file xasl_to_stream.c.
References i, MAX_PTR_BLOCKS, and xts_Ptr_lwm.
Referenced by xts_map_filter_pred_to_stream(), xts_map_func_pred_to_stream(), and xts_map_xasl_to_stream().
static int xts_get_offset_visited_ptr (const void * ptr) static
Definition at line 7375 of file xasl_to_stream.c.
References ER_FAILED, xts_visited_ptr::offset, xasl_stream_get_ptr_block(), and xts_Ptr_lwm.
Referenced by xts_save(), xts_save_aggregate_type(), xts_save_analytic_eval_type(), xts_save_analytic_type(), xts_save_arith_type(), xts_save_cache_attrinfo(), xts_save_db_value(), xts_save_filter_pred_node(), xts_save_func_pred(), xts_save_function_type(), xts_save_indx_info(), xts_save_key_range_array(), xts_save_list_id(), xts_save_method_sig(), xts_save_method_sig_list(), xts_save_outptr_list(), xts_save_pred_expr(), xts_save_regu_variable(), xts_save_regu_variable_list(), xts_save_regu_varlist_list(), xts_save_selupd_list(), xts_save_sort_list(), xts_save_srlist_id(), xts_save_string(), xts_save_val_list(), and xts_save_xasl_node().
static int xts_get_regu_variable_value_size (const REGU_VARIABLE * ptr) static
Definition at line 6882 of file xasl_to_stream.c.
References assert, ER_FAILED, ER_QPROC_INVALID_XASLNODE, OR_INT_SIZE, OR_VALUE_ALIGNED_SIZE, PTR_SIZE, TYPE_ATTR_ID, TYPE_CLASS_ATTR_ID, TYPE_CLASSOID, TYPE_CONSTANT, TYPE_DBVAL, TYPE_FUNC, TYPE_INARITH, TYPE_LIST_ID, TYPE_OID, TYPE_ORDERBY_NUM, TYPE_OUTARITH, TYPE_POS_VALUE, TYPE_POSITION, TYPE_REGU_VAR_LIST, TYPE_REGUVAL_LIST, TYPE_SHARED_ATTR_ID, xts_sizeof_attr_descr(), xts_sizeof_pos_descr(), xts_sizeof_regu_value_list(), xts_sizeof_regu_variable_list(), and xts_Xasl_errcode.
Referenced by xts_sizeof_regu_value_list(), xts_sizeof_regu_variable(), and xts_sizeof_regu_variable_list().
int xts_map_filter_pred_to_stream (const PRED_EXPR_WITH_CONTEXT * pred, char ** pred_stream, int * pred_stream_size)
Definition at line 372 of file xasl_to_stream.c.
References ER_FAILED, ER_QPROC_INVALID_XASLNODE, free_and_init, NO_ERROR, NULL, xts_visited_ptr::offset, or_pack_int(), p, xasl_stream_make_align(), xts_Free_offset_in_stream, xts_free_visited_ptrs(), xts_reserve_location_in_stream(), xts_save_filter_pred_node(), xts_Stream_buffer, xts_Stream_size, and xts_Xasl_errcode.
Referenced by create_or_drop_index_helper(), and do_recreate_filter_index_constr().
int xts_map_func_pred_to_stream (const FUNC_PRED * xasl_tree, char ** xasl_stream, int * xasl_stream_size)
Definition at line 435 of file xasl_to_stream.c.
References ER_FAILED, ER_QPROC_INVALID_XASLNODE, free_and_init, NO_ERROR, NULL, xts_visited_ptr::offset, or_pack_int(), or_unpack_int(), p, xasl_stream_make_align(), xts_Free_offset_in_stream, xts_free_visited_ptrs(), xts_reserve_location_in_stream(), xts_save_func_pred(), xts_Stream_buffer, xts_Stream_size, and xts_Xasl_errcode.
Referenced by pt_node_to_function_index().
int xts_map_xasl_to_stream (const XASL_NODE * xasl_tree, XASL_STREAM * stream)
Definition at line 272 of file xasl_to_stream.c.
References assert, xasl_stream::buffer, xasl_stream::buffer_size, xasl_node::class_locks, xasl_node::class_oid_list, xasl_node::creator_oid, xasl_node::dbval_cnt, ER_FAILED, ER_QPROC_INVALID_XASLNODE, free_and_init, i, xasl_node::n_oid_list, NO_ERROR, NULL, xts_visited_ptr::offset, or_pack_int(), or_pack_oid(), p, xasl_node::tcard_list, xasl_stream_make_align(), xts_Free_offset_in_stream, xts_free_visited_ptrs(), xts_reserve_location_in_stream(), xts_save_xasl_node(), xts_Stream_buffer, xts_Stream_size, and xts_Xasl_errcode.
Referenced by build_xasl_for_server_delete(), do_execute_do(), do_insert_at_server(), do_prepare_delete(), do_prepare_insert_internal(), do_prepare_merge(), do_prepare_select(), do_prepare_update(), do_select_internal(), and update_at_server().
static int xts_mark_ptr_visited (const void * ptr, int offset) static
Definition at line 7329 of file xasl_to_stream.c.
References ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, NO_ERROR, NULL, xts_visited_ptr::offset, xts_visited_ptr::ptr, START_PTR_PER_BLOCK, xasl_stream_get_ptr_block(), xts_Ptr_lwm, xts_Ptr_max, and xts_Xasl_errcode.
Referenced by xts_save(), xts_save_aggregate_type(), xts_save_analytic_eval_type(), xts_save_analytic_type(), xts_save_arith_type(), xts_save_cache_attrinfo(), xts_save_db_value(), xts_save_filter_pred_node(), xts_save_func_pred(), xts_save_function_type(), xts_save_indx_info(), xts_save_list_id(), xts_save_method_sig(), xts_save_method_sig_list(), xts_save_outptr_list(), xts_save_pred_expr(), xts_save_regu_variable(), xts_save_regu_variable_list(), xts_save_regu_varlist_list(), xts_save_selupd_list(), xts_save_sort_list(), xts_save_srlist_id(), xts_save_string(), xts_save_val_list(), and xts_save_xasl_node().
static char * xts_pack_regu_variable_value (char * ptr, const REGU_VARIABLE * regu_var) static
Definition at line 4997 of file xasl_to_stream.c.
References assert, ER_FAILED, ER_QPROC_INVALID_XASLNODE, NULL, xts_visited_ptr::offset, or_pack_int(), xts_visited_ptr::ptr, TYPE_ATTR_ID, TYPE_CLASS_ATTR_ID, TYPE_CLASSOID, TYPE_CONSTANT, TYPE_DBVAL, TYPE_FUNC, TYPE_INARITH, TYPE_LIST_ID, TYPE_OID, TYPE_ORDERBY_NUM, TYPE_OUTARITH, TYPE_POS_VALUE, TYPE_POSITION, TYPE_REGU_VAR_LIST, TYPE_REGUVAL_LIST, TYPE_SHARED_ATTR_ID, xts_process_attr_descr(), xts_process_db_value(), xts_process_pos_descr(), xts_process_regu_value_list(), xts_process_regu_variable_list(), xts_save_arith_type(), xts_save_db_value(), xts_save_function_type(), xts_save_srlist_id(), and xts_Xasl_errcode.
Referenced by xts_process_regu_value_list(), and xts_process_regu_variable().
static char * xts_process (char * ptr, const json_table_column & json_table_col) static
Definition at line 4783 of file xasl_to_stream.c.
References assert, ER_FAILED, JSON_TABLE_EXISTS, JSON_TABLE_ORDINALITY, cubxasl::json_table::column::m_column_name, cubxasl::json_table::column::m_domain, cubxasl::json_table::column::m_function, cubxasl::json_table::column::m_on_empty, cubxasl::json_table::column::m_on_error, cubxasl::json_table::column::m_output_value_pointer, cubxasl::json_table::column::m_path, NULL, xts_visited_ptr::offset, or_pack_domain(), or_pack_int(), xts_visited_ptr::ptr, xts_debug_check(), xts_process_json_table_column_behavior(), xts_save_db_value(), and xts_save_string().
Referenced by xts_process(), xts_process_access_spec_type(), and xts_save().
static char * xts_process (char * ptr, const json_table_node & json_table_node) static
Definition at line 4843 of file xasl_to_stream.c.
References ER_FAILED, i, cubxasl::json_table::node::m_id, cubxasl::json_table::node::m_is_iterable_node, cubxasl::json_table::node::m_nested_nodes, cubxasl::json_table::node::m_nested_nodes_size, cubxasl::json_table::node::m_output_columns, cubxasl::json_table::node::m_output_columns_size, cubxasl::json_table::node::m_path, NULL, xts_visited_ptr::offset, or_pack_int(), xts_visited_ptr::ptr, xts_debug_check(), xts_process(), and xts_save_string().
static char * xts_process (char * ptr, const json_table_spec_node & set_spec) static
Definition at line 4880 of file xasl_to_stream.c.
References ER_FAILED, cubxasl::json_table::spec_node::m_json_reguvar, cubxasl::json_table::spec_node::m_node_count, cubxasl::json_table::spec_node::m_root_node, NULL, xts_visited_ptr::offset, or_pack_int(), xts_visited_ptr::ptr, xts_debug_check(), xts_process(), and xts_save_regu_variable().
static char * xts_process_access_spec_type (char * ptr, const ACCESS_SPEC_TYPE * access_spec) static
Definition at line 4337 of file xasl_to_stream.c.
References access_spec_node::access, ACCESS_METHOD_JSON_TABLE, ACCESS_METHOD_SEQUENTIAL, ACCESS_METHOD_SEQUENTIAL_PAGE_SCAN, ACCESS_METHOD_SEQUENTIAL_RECORD_INFO, ACCESS_SPEC_CLS_SPEC, ACCESS_SPEC_JSON_TABLE_SPEC, ACCESS_SPEC_LIST_SPEC, ACCESS_SPEC_METHOD_SPEC, ACCESS_SPEC_SET_SPEC, ACCESS_SPEC_SHOWSTMT_SPEC, ER_FAILED, ER_QPROC_INVALID_XASLNODE, access_spec_node::flags, access_spec_node::indexptr, NULL, xts_visited_ptr::offset, or_pack_int(), access_spec_node::pruning_type, xts_visited_ptr::ptr, access_spec_node::s_dbval, access_spec_node::single_fetch, TARGET_CLASS, TARGET_CLASS_ATTR, TARGET_JSON_TABLE, TARGET_LIST, TARGET_METHOD, TARGET_REGUVAL_LIST, TARGET_SET, TARGET_SHOWSTMT, access_spec_node::type, access_spec_node::where_key, access_spec_node::where_pred, access_spec_node::where_range, xts_process(), xts_process_cls_spec_type(), xts_process_list_spec_type(), xts_process_method_spec_type(), xts_process_rlist_spec_type(), xts_process_set_spec_type(), xts_process_showstmt_spec_type(), xts_save_db_value(), xts_save_indx_info(), xts_save_pred_expr(), and xts_Xasl_errcode.
Referenced by xts_process_mergelist_proc(), and xts_process_xasl_node().
static char * xts_process_aggregate_type (char * ptr, const AGGREGATE_TYPE * aggregate) static
Definition at line 5190 of file xasl_to_stream.c.
References cubxasl::aggregate_list_node::accumulator, cubxasl::aggregate_list_node::btid, cubxasl::aggregate_accumulator::curr_cnt, cubxasl::aggregate_list_node::domain, ER_FAILED, cubxasl::aggregate_list_node::flag_agg_optimize, cubxasl::aggregate_list_node::function, cubxasl::aggregate_list_node::info, cubxasl::aggregate_list_node::list_id, cubxasl::aggregate_list_node::next, NULL, xts_visited_ptr::offset, cubxasl::aggregate_list_node::operands, cubxasl::aggregate_list_node::opr_dbtype, cubxasl::aggregate_list_node::option, or_pack_btid(), OR_PACK_DOMAIN_OBJECT_TO_OID, or_pack_int(), cubxasl::aggregate_specific_function_info::percentile, cubxasl::aggregate_percentile_info::percentile_reguvar, PT_PERCENTILE_CONT, PT_PERCENTILE_DISC, xts_visited_ptr::ptr, cubxasl::aggregate_list_node::sort_list, cubxasl::aggregate_accumulator::value, cubxasl::aggregate_accumulator::value2, xts_process_regu_variable_list(), xts_save_aggregate_type(), xts_save_db_value(), xts_save_list_id(), xts_save_regu_variable(), and xts_save_sort_list().
Referenced by xts_save_aggregate_type().
static char * xts_process_alsm_eval_term (char * ptr, const ALSM_EVAL_TERM * alsm_eval_term) static
Definition at line 4251 of file xasl_to_stream.c.
References cubxasl::alsm_eval_term::elem, cubxasl::alsm_eval_term::elemset, cubxasl::alsm_eval_term::eq_flag, ER_FAILED, cubxasl::alsm_eval_term::item_type, NULL, xts_visited_ptr::offset, or_pack_int(), xts_visited_ptr::ptr, cubxasl::alsm_eval_term::rel_op, and xts_save_regu_variable().
Referenced by xts_process_eval_term().
static char * xts_process_analytic_eval_type (char * ptr, const ANALYTIC_EVAL_TYPE * analytic) static
Definition at line 5391 of file xasl_to_stream.c.
References ER_FAILED, cubxasl::analytic_eval_type::head, cubxasl::analytic_eval_type::next, NULL, xts_visited_ptr::offset, or_pack_int(), xts_visited_ptr::ptr, cubxasl::analytic_eval_type::sort_list, xts_save_analytic_eval_type(), xts_save_analytic_type(), and xts_save_sort_list().
Referenced by xts_save_analytic_eval_type().
static char * xts_process_analytic_type (char * ptr, const ANALYTIC_TYPE * analytic) static
Definition at line 5300 of file xasl_to_stream.c.
References cubxasl::analytic_list_node::default_idx, cubxasl::analytic_list_node::domain, ER_FAILED, cubxasl::analytic_list_node::flag, cubxasl::analytic_list_node::from_last, cubxasl::analytic_list_node::function, cubxasl::analytic_list_node::ignore_nulls, cubxasl::analytic_list_node::info, cubxasl::analytic_list_node::is_const_operand, cubxasl::analytic_list_node::list_id, cubxasl::analytic_list_node::next, NULL, xts_visited_ptr::offset, cubxasl::analytic_list_node::offset_idx, cubxasl::analytic_list_node::operand, cubxasl::analytic_list_node::opr_dbtype, cubxasl::analytic_list_node::option, OR_PACK_DOMAIN_OBJECT_TO_OID, or_pack_int(), cubxasl::analytic_list_node::out_value, cubxasl::analytic_function_info::percentile, cubxasl::analytic_percentile_function_info::percentile_reguvar, PT_PERCENTILE_CONT, PT_PERCENTILE_DISC, xts_visited_ptr::ptr, cubxasl::analytic_list_node::sort_list_size, cubxasl::analytic_list_node::sort_prefix_size, cubxasl::analytic_list_node::value, cubxasl::analytic_list_node::value2, xts_process_regu_variable(), xts_save_analytic_type(), xts_save_db_value(), xts_save_list_id(), and xts_save_regu_variable().
Referenced by xts_save_analytic_type().
static char * xts_process_arith_type (char * ptr, const ARITH_TYPE * arith) static
Definition at line 5138 of file xasl_to_stream.c.
References arith_list_node::domain, ER_FAILED, arith_list_node::leftptr, arith_list_node::misc_operand, NULL, xts_visited_ptr::offset, arith_list_node::opcode, OR_PACK_DOMAIN_OBJECT_TO_OID, or_pack_int(), arith_list_node::pred, xts_visited_ptr::ptr, arith_list_node::rightptr, T_CASE, T_DECODE, T_IF, T_PREDICATE, arith_list_node::thirdptr, arith_list_node::value, xts_save_db_value(), xts_save_pred_expr(), and xts_save_regu_variable().
Referenced by xts_save_arith_type().
static char * xts_process_attr_descr (char * ptr, const ATTR_DESCR * attr_descr) static
Definition at line 5102 of file xasl_to_stream.c.
References attr_descr_node::cache_attrinfo, ER_FAILED, attr_descr_node::id, NULL, xts_visited_ptr::offset, or_pack_int(), xts_visited_ptr::ptr, attr_descr_node::type, and xts_save_cache_attrinfo().
Referenced by xts_pack_regu_variable_value().
static char * xts_process_buildlist_proc (char * ptr, const BUILDLIST_PROC_NODE * build_list_proc) static
Definition at line 3231 of file xasl_to_stream.c.
References buildlist_proc_node::a_eval_list, buildlist_proc_node::a_outptr_list, buildlist_proc_node::a_outptr_list_ex, buildlist_proc_node::a_outptr_list_interm, buildlist_proc_node::a_regu_list, buildlist_proc_node::a_val_list, buildlist_proc_node::after_groupby_list, buildlist_proc_node::eptr_list, ER_FAILED, buildlist_proc_node::g_agg_list, buildlist_proc_node::g_func_count, buildlist_proc_node::g_grbynum_flag, buildlist_proc_node::g_grbynum_pred, buildlist_proc_node::g_grbynum_val, buildlist_proc_node::g_hash_eligible, buildlist_proc_node::g_having_pred, buildlist_proc_node::g_hk_scan_regu_list, buildlist_proc_node::g_hk_sort_regu_list, buildlist_proc_node::g_hkey_size, buildlist_proc_node::g_outptr_list, buildlist_proc_node::g_output_first_tuple, buildlist_proc_node::g_regu_list, buildlist_proc_node::g_scan_regu_list, buildlist_proc_node::g_val_list, buildlist_proc_node::g_with_rollup, buildlist_proc_node::groupby_list, NULL, xts_visited_ptr::offset, or_pack_int(), xts_visited_ptr::ptr, buildlist_proc_node::push_list_id, xts_save_aggregate_type(), xts_save_analytic_eval_type(), xts_save_db_value(), xts_save_list_id(), xts_save_outptr_list(), xts_save_pred_expr(), xts_save_regu_variable_list(), xts_save_sort_list(), xts_save_val_list(), and xts_save_xasl_node().
Referenced by xts_process_xasl_node().
static char * xts_process_buildvalue_proc (char * ptr, const BUILDVALUE_PROC_NODE * build_value_proc) static
Definition at line 3397 of file xasl_to_stream.c.
References buildvalue_proc_node::agg_list, ER_FAILED, buildvalue_proc_node::grbynum_val, buildvalue_proc_node::having_pred, buildvalue_proc_node::is_always_false, NULL, xts_visited_ptr::offset, or_pack_int(), buildvalue_proc_node::outarith_list, xts_visited_ptr::ptr, xts_save_aggregate_type(), xts_save_arith_type(), xts_save_db_value(), and xts_save_pred_expr().
Referenced by xts_process_xasl_node().
static char * xts_process_cache_attrinfo (char * ptr) static
Definition at line 3169 of file xasl_to_stream.c.
References or_pack_int(), and xts_visited_ptr::ptr.
Referenced by xts_save_cache_attrinfo().
static char * xts_process_cls_spec_type (char * ptr, const CLS_SPEC_TYPE * cls_spec) static
Definition at line 4543 of file xasl_to_stream.c.
References cls_spec_node::attrids_key, cls_spec_node::attrids_pred, cls_spec_node::attrids_range, cls_spec_node::attrids_rest, cls_spec_node::cache_key, cls_spec_node::cache_pred, cls_spec_node::cache_range, cls_spec_node::cache_reserved, cls_spec_node::cache_rest, cls_spec_node::cls_oid, cls_spec_node::cls_output_val_list, cls_spec_node::cls_regu_list_key, cls_spec_node::cls_regu_list_pred, cls_spec_node::cls_regu_list_range, cls_spec_node::cls_regu_list_reserved, cls_spec_node::cls_regu_list_rest, cls_spec_node::cls_regu_val_list, ER_FAILED, cls_spec_node::hfid, NULL, cls_spec_node::num_attrs_key, cls_spec_node::num_attrs_pred, cls_spec_node::num_attrs_range, cls_spec_node::num_attrs_reserved, cls_spec_node::num_attrs_rest, xts_visited_ptr::offset, or_pack_hfid(), or_pack_int(), or_pack_oid(), xts_visited_ptr::ptr, cls_spec_node::schema_type, xts_save_cache_attrinfo(), xts_save_db_value_array(), xts_save_int_array(), xts_save_outptr_list(), and xts_save_regu_variable_list().
Referenced by xts_process_access_spec_type().
static char * xts_process_comp_eval_term (char * ptr, const COMP_EVAL_TERM * comp_eval_term) static
Definition at line 4225 of file xasl_to_stream.c.
References ER_FAILED, cubxasl::comp_eval_term::lhs, NULL, xts_visited_ptr::offset, or_pack_int(), xts_visited_ptr::ptr, cubxasl::comp_eval_term::rel_op, cubxasl::comp_eval_term::rhs, cubxasl::comp_eval_term::type, and xts_save_regu_variable().
Referenced by xts_process_eval_term().
static char * xts_process_connectby_proc (char * ptr, const CONNECTBY_PROC_NODE * connectby_proc) static
Definition at line 5538 of file xasl_to_stream.c.
References connectby_proc_node::after_cb_regu_list_pred, connectby_proc_node::after_cb_regu_list_rest, connectby_proc_node::after_connect_by_pred, ER_FAILED, connectby_proc_node::input_list_id, NULL, xts_visited_ptr::offset, or_pack_int(), connectby_proc_node::prior_outptr_list, connectby_proc_node::prior_regu_list_pred, connectby_proc_node::prior_regu_list_rest, connectby_proc_node::prior_val_list, xts_visited_ptr::ptr, connectby_proc_node::regu_list_pred, connectby_proc_node::regu_list_rest, connectby_proc_node::single_table_opt, connectby_proc_node::start_with_list_id, connectby_proc_node::start_with_pred, xts_save_list_id(), xts_save_outptr_list(), xts_save_pred_expr(), xts_save_regu_variable_list(), and xts_save_val_list().
Referenced by xts_process_xasl_node().
static char * xts_process_cte_proc (char * ptr, const CTE_PROC_NODE * cte_proc) static
Definition at line 3491 of file xasl_to_stream.c.
References ER_FAILED, cte_proc_node::non_recursive_part, NULL, xts_visited_ptr::offset, or_pack_int(), xts_visited_ptr::ptr, cte_proc_node::recursive_part, and xts_save_xasl_node().
Referenced by xts_process_xasl_node().
static char * xts_process_db_value (char * ptr, const DB_VALUE * value) static
Definition at line 5130 of file xasl_to_stream.c.
References or_pack_db_value(), and xts_visited_ptr::ptr.
Referenced by xts_pack_regu_variable_value(), xts_process_json_table_column_behavior(), and xts_save_db_value().
static char * xts_process_delete_proc (char * ptr, const DELETE_PROC_NODE * delete_proc) static
Definition at line 3941 of file xasl_to_stream.c.
References delete_proc_node::classes, ER_FAILED, delete_proc_node::mvcc_reev_classes, delete_proc_node::no_logging, NULL, delete_proc_node::num_classes, delete_proc_node::num_reev_classes, xts_visited_ptr::offset, or_pack_int(), xts_visited_ptr::ptr, delete_proc_node::wait_msecs, xts_save_int_array(), and xts_save_upddel_class_info_array().
Referenced by xts_process_xasl_node().
static char * xts_process_eval_term (char * ptr, const EVAL_TERM * eval_term) static
Definition at line 4194 of file xasl_to_stream.c.
References ER_QPROC_INVALID_XASLNODE, cubxasl::eval_term::et, cubxasl::eval_term::et_alsm, cubxasl::eval_term::et_comp, cubxasl::eval_term::et_like, cubxasl::eval_term::et_rlike, cubxasl::eval_term::et_type, NULL, or_pack_int(), xts_visited_ptr::ptr, T_ALSM_EVAL_TERM, T_COMP_EVAL_TERM, T_LIKE_EVAL_TERM, T_RLIKE_EVAL_TERM, xts_process_alsm_eval_term(), xts_process_comp_eval_term(), xts_process_like_eval_term(), xts_process_rlike_eval_term(), and xts_Xasl_errcode.
Referenced by xts_process_pred_expr().
static char * xts_process_fetch_proc (char * ptr, const FETCH_PROC_NODE * obj_set_fetch_proc) static
Definition at line 3205 of file xasl_to_stream.c.
References fetch_proc_node::arg, ER_FAILED, fetch_proc_node::fetch_res, NULL, xts_visited_ptr::offset, or_pack_int(), xts_visited_ptr::ptr, fetch_proc_node::ql_flag, fetch_proc_node::set_pred, xts_save_db_value(), and xts_save_pred_expr().
Referenced by xts_process_xasl_node().
static char * xts_process_filter_pred_node (char * ptr, const PRED_EXPR_WITH_CONTEXT * pred) static
Definition at line 3117 of file xasl_to_stream.c.
References pred_expr_with_context::attrids_pred, pred_expr_with_context::cache_pred, ER_FAILED, NULL, pred_expr_with_context::num_attrs_pred, xts_visited_ptr::offset, or_pack_int(), pred_expr_with_context::pred, xts_visited_ptr::ptr, xts_save_cache_attrinfo(), xts_save_int_array(), and xts_save_pred_expr().
Referenced by xts_save_filter_pred_node().
static char * xts_process_func_pred (char * ptr, const FUNC_PRED * xasl) static
Definition at line 3147 of file xasl_to_stream.c.
References func_pred::cache_attrinfo, ER_FAILED, func_pred::func_regu, NULL, xts_visited_ptr::offset, or_pack_int(), xts_visited_ptr::ptr, xts_save_cache_attrinfo(), and xts_save_regu_variable().
Referenced by xts_save_func_pred().
static char * xts_process_function_type (char * ptr, const FUNCTION_TYPE * function) static
Definition at line 5276 of file xasl_to_stream.c.
References ER_FAILED, NULL, xts_visited_ptr::offset, or_pack_int(), xts_visited_ptr::ptr, xts_save_db_value(), and xts_save_regu_variable_list().
Referenced by xts_save_function_type().
static char * xts_process_indx_info (char * ptr, const INDX_INFO * indx_info) static
Definition at line 4447 of file xasl_to_stream.c.
References indx_info::btid, indx_info::coverage, ER_FAILED, indx_info::func_idx_col_id, indx_info::groupby_desc, indx_info::groupby_skip, indx_info::ils_prefix_len, indx_info::iss_range, key_range::key1, indx_info::key_info, NULL, xts_visited_ptr::offset, or_pack_btid(), or_pack_int(), indx_info::orderby_desc, indx_info::orderby_skip, xts_visited_ptr::ptr, key_range::range, indx_info::range_type, indx_info::use_desc_index, indx_info::use_iss, xts_process_key_info(), and xts_save_regu_variable().
Referenced by xts_save_indx_info().
static char * xts_process_insert_proc (char * ptr, const INSERT_PROC_NODE * insert_proc) static
Definition at line 3978 of file xasl_to_stream.c.
References insert_proc_node::att_id, insert_proc_node::class_hfid, insert_proc_node::class_oid, insert_proc_node::cons_pred, insert_proc_node::do_replace, ER_FAILED, insert_proc_node::has_uniques, i, insert_proc_node::no_logging, NULL, insert_proc_node::num_default_expr, insert_proc_node::num_val_lists, insert_proc_node::num_vals, insert_proc_node::obj_oid, insert_proc_node::odku, xts_visited_ptr::offset, or_pack_hfid(), or_pack_int(), or_pack_oid(), insert_proc_node::pruning_type, xts_visited_ptr::ptr, insert_proc_node::valptr_lists, insert_proc_node::wait_msecs, xts_save_db_value(), xts_save_int_array(), xts_save_odku_info(), xts_save_outptr_list(), and xts_save_pred_expr().
Referenced by xts_process_xasl_node().
static char * xts_process_json_table_column_behavior (char * ptr, const json_table_column_behavior * behavior) static
Definition at line 4770 of file xasl_to_stream.c.
References JSON_TABLE_DEFAULT_VALUE, json_table_column_behavior::m_behavior, json_table_column_behavior::m_default_value, or_pack_int(), xts_visited_ptr::ptr, and xts_process_db_value().
Referenced by xts_process().
static char * xts_process_key_info (char * ptr, const KEY_INFO * key_info) static
Definition at line 4501 of file xasl_to_stream.c.
References ER_FAILED, key_info::is_constant, key_info::is_user_given_keylimit, key_info::key_cnt, key_info::key_limit_l, key_info::key_limit_reset, key_info::key_limit_u, key_info::key_ranges, NULL, xts_visited_ptr::offset, or_pack_int(), xts_visited_ptr::ptr, xts_save_key_range_array(), and xts_save_regu_variable().
Referenced by xts_process_indx_info().
static char * xts_process_like_eval_term (char * ptr, const LIKE_EVAL_TERM * like_eval_term) static
Definition at line 4279 of file xasl_to_stream.c.
References ER_FAILED, cubxasl::like_eval_term::esc_char, NULL, xts_visited_ptr::offset, or_pack_int(), cubxasl::like_eval_term::pattern, xts_visited_ptr::ptr, cubxasl::like_eval_term::src, and xts_save_regu_variable().
Referenced by xts_process_eval_term().
static char * xts_process_list_id (char * ptr, const QFILE_LIST_ID * list_id) static
Definition at line 4931 of file xasl_to_stream.c.
References assert_release, qfile_tuple_value_type_list::domp, NULL, or_pack_listid(), qfile_tuple_value_type_list::type_cnt, and qfile_list_id::type_list.
Referenced by xts_save_list_id().
static char * xts_process_list_spec_type (char * ptr, const LIST_SPEC_TYPE * list_spec) static
Definition at line 4679 of file xasl_to_stream.c.
References ER_FAILED, list_spec_node::hash_list_scan_yn, list_spec_node::list_regu_list_build, list_spec_node::list_regu_list_pred, list_spec_node::list_regu_list_probe, list_spec_node::list_regu_list_rest, NULL, xts_visited_ptr::offset, or_pack_int(), xts_visited_ptr::ptr, list_spec_node::xasl_node, xts_save_regu_variable_list(), and xts_save_xasl_node().
Referenced by xts_process_access_spec_type().
static char * xts_process_ls_merge_info (char * ptr, const QFILE_LIST_MERGE_INFO * qfile_list_merge_info) static
Definition at line 3513 of file xasl_to_stream.c.
References ER_FAILED, qfile_list_merge_info::join_type, qfile_list_merge_info::ls_column_cnt, qfile_list_merge_info::ls_inner_column, qfile_list_merge_info::ls_inner_unique, qfile_list_merge_info::ls_outer_column, qfile_list_merge_info::ls_outer_inner_list, qfile_list_merge_info::ls_outer_unique, qfile_list_merge_info::ls_pos_cnt, qfile_list_merge_info::ls_pos_list, NULL, xts_visited_ptr::offset, or_pack_int(), xts_visited_ptr::ptr, qfile_list_merge_info::single_fetch, and xts_save_int_array().
Referenced by xts_process_mergelist_proc(), and xts_save_cache_attrinfo().
static char * xts_process_merge_proc (char * ptr, const MERGE_PROC_NODE * merge_info) static
Definition at line 4044 of file xasl_to_stream.c.
References ER_FAILED, merge_proc_node::has_delete, merge_proc_node::insert_xasl, NULL, xts_visited_ptr::offset, or_pack_int(), xts_visited_ptr::ptr, merge_proc_node::update_xasl, and xts_save_xasl_node().
Referenced by xts_process_xasl_node().
static char * xts_process_mergelist_proc (char * ptr, const MERGELIST_PROC_NODE * merge_list_info) static
Definition at line 3435 of file xasl_to_stream.c.
References ER_FAILED, mergelist_proc_node::inner_spec_list, mergelist_proc_node::inner_val_list, mergelist_proc_node::inner_xasl, mergelist_proc_node::ls_merge, access_spec_node::next, NULL, xts_visited_ptr::offset, or_pack_int(), mergelist_proc_node::outer_spec_list, mergelist_proc_node::outer_val_list, mergelist_proc_node::outer_xasl, xts_process_access_spec_type(), xts_process_ls_merge_info(), xts_save_val_list(), and xts_save_xasl_node().
Referenced by xts_process_xasl_node().
static char * xts_process_method_sig (char * ptr, const METHOD_SIG * method_sig, int size) static
Definition at line 5498 of file xasl_to_stream.c.
References assert, method_sig_node::class_name, ER_FAILED, method_sig_node::method_arg_pos, method_sig_node::method_name, method_sig_node::method_type, method_sig_node::next, NULL, method_sig_node::num_method_args, xts_visited_ptr::offset, or_pack_int(), xts_visited_ptr::ptr, xts_save_method_sig(), and xts_save_string().
Referenced by xts_save_method_sig().
static char * xts_process_method_sig_list (char * ptr, const METHOD_SIG_LIST * method_sig_list) static
Definition at line 5468 of file xasl_to_stream.c.
References assert, ER_FAILED, i, method_sig_list::method_sig, method_sig_node::next, NULL, method_sig_list::num_methods, xts_visited_ptr::offset, or_pack_int(), xts_visited_ptr::ptr, and xts_save_method_sig().
Referenced by xts_save_method_sig_list().
static char * xts_process_method_spec_type (char * ptr, const METHOD_SPEC_TYPE * method_spec) static
Definition at line 4902 of file xasl_to_stream.c.
References ER_FAILED, method_spec_node::method_regu_list, method_spec_node::method_sig_list, NULL, xts_visited_ptr::offset, or_pack_int(), xts_visited_ptr::ptr, method_spec_node::xasl_node, xts_save_method_sig_list(), xts_save_regu_variable_list(), and xts_save_xasl_node().
Referenced by xts_process_access_spec_type().
static char * xts_process_outptr_list (char * ptr, const OUTPTR_LIST * outptr_list) static
Definition at line 4068 of file xasl_to_stream.c.
References ER_FAILED, NULL, xts_visited_ptr::offset, or_pack_int(), xts_visited_ptr::ptr, valptr_list_node::valptr_cnt, valptr_list_node::valptrp, and xts_save_regu_variable_list().
Referenced by xts_save_outptr_list().
static char * xts_process_pos_descr (char * ptr, const QFILE_TUPLE_VALUE_POSITION * position_descr) static
Definition at line 5121 of file xasl_to_stream.c.
References qfile_tuple_value_position::dom, OR_PACK_DOMAIN_OBJECT_TO_OID, or_pack_int(), qfile_tuple_value_position::pos_no, and xts_visited_ptr::ptr.
Referenced by xts_pack_regu_variable_value(), and xts_process_sort_list().
static char * xts_process_pred (char * ptr, const PRED * pred) static
Definition at line 4148 of file xasl_to_stream.c.
References cubxasl::pred::bool_op, ER_FAILED, cubxasl::pred::lhs, cubxasl::pred_expr::m_pred, NULL, xts_visited_ptr::offset, or_pack_int(), cubxasl::pred_expr::pe, xts_visited_ptr::ptr, cubxasl::pred::rhs, T_PRED, cubxasl::pred_expr::type, and xts_save_pred_expr().
Referenced by xts_process_pred_expr().
static char * xts_process_pred_expr (char * ptr, const PRED_EXPR * pred_expr) static
Definition at line 4114 of file xasl_to_stream.c.
References ER_FAILED, ER_QPROC_INVALID_XASLNODE, cubxasl::pred_expr::m_eval_term, cubxasl::pred_expr::m_not_term, cubxasl::pred_expr::m_pred, NULL, xts_visited_ptr::offset, or_pack_int(), cubxasl::pred_expr::pe, xts_visited_ptr::ptr, T_EVAL_TERM, T_NOT_TERM, T_PRED, cubxasl::pred_expr::type, xts_process_eval_term(), xts_process_pred(), xts_save_pred_expr(), and xts_Xasl_errcode.
Referenced by xts_save_pred_expr().
static char * xts_process_regu_value_list (char * ptr, const REGU_VALUE_LIST * regu_value_list) static
Definition at line 5638 of file xasl_to_stream.c.
References assert, regu_value_list::count, ER_QPROC_INVALID_XASLNODE, regu_value_item::next, NULL, or_pack_int(), xts_visited_ptr::ptr, regu_value_list::regu_list, TYPE_DBVAL, TYPE_INARITH, TYPE_POS_VALUE, regu_value_item::value, xts_pack_regu_variable_value(), and xts_Xasl_errcode.
Referenced by xts_pack_regu_variable_value().
static char * xts_process_regu_variable (char * ptr, const REGU_VARIABLE * regu_var) static
Definition at line 4964 of file xasl_to_stream.c.
References assert, ER_FAILED, NULL, xts_visited_ptr::offset, OR_PACK_DOMAIN_OBJECT_TO_OID, or_pack_int(), xts_visited_ptr::ptr, REGU_VARIABLE_FETCH_ALL_CONST, REGU_VARIABLE_FETCH_NOT_CONST, REGU_VARIABLE_IS_FLAGED(), xts_pack_regu_variable_value(), xts_save_db_value(), and xts_save_xasl_node().
Referenced by xts_process_analytic_type(), and xts_save_regu_variable().
static char * xts_process_regu_variable_list (char * ptr, const REGU_VARIABLE_LIST regu_var_list) static
Definition at line 7488 of file xasl_to_stream.c.
References assert, ER_FAILED, NULL, xts_visited_ptr::offset, or_pack_int(), xts_visited_ptr::ptr, and xts_save_regu_variable_list().
Referenced by xts_pack_regu_variable_value(), and xts_process_aggregate_type().
static char * xts_process_rlike_eval_term (char * ptr, const RLIKE_EVAL_TERM * rlike_eval_term) static
Definition at line 4308 of file xasl_to_stream.c.
References cubxasl::rlike_eval_term::case_sensitive, ER_FAILED, NULL, xts_visited_ptr::offset, or_pack_int(), cubxasl::rlike_eval_term::pattern, xts_visited_ptr::ptr, cubxasl::rlike_eval_term::src, and xts_save_regu_variable().
Referenced by xts_process_eval_term().
static char * xts_process_rlist_spec_type (char * ptr, const LIST_SPEC_TYPE * list_spec) static
Definition at line 4741 of file xasl_to_stream.c.
References xts_visited_ptr::ptr.
Referenced by xts_process_access_spec_type().
static char * xts_process_selupd_list (char * ptr, const SELUPD_LIST * selupd_list) static
Definition at line 4085 of file xasl_to_stream.c.
References selupd_list::class_hfid, selupd_list::class_oid, ER_FAILED, selupd_list::next, NULL, xts_visited_ptr::offset, or_pack_hfid(), or_pack_int(), or_pack_oid(), xts_visited_ptr::ptr, selupd_list::select_list, selupd_list::select_list_size, selupd_list::wait_msecs, xts_save_regu_varlist_list(), and xts_save_selupd_list().
Referenced by xts_save_selupd_list().
static char * xts_process_set_spec_type (char * ptr, const SET_SPEC_TYPE * set_spec) static
Definition at line 4748 of file xasl_to_stream.c.
References ER_FAILED, NULL, xts_visited_ptr::offset, or_pack_int(), xts_visited_ptr::ptr, set_spec_node::set_ptr, set_spec_node::set_regu_list, xts_save_regu_variable(), and xts_save_regu_variable_list().
Referenced by xts_process_access_spec_type().
static char * xts_process_showstmt_spec_type (char * ptr, const SHOWSTMT_SPEC_TYPE * list_spec) static
Definition at line 4724 of file xasl_to_stream.c.
References showstmt_spec_node::arg_list, ER_FAILED, NULL, xts_visited_ptr::offset, or_pack_int(), xts_visited_ptr::ptr, showstmt_spec_node::show_type, and xts_save_regu_variable_list().
Referenced by xts_process_access_spec_type().
static char * xts_process_sort_list (char * ptr, const SORT_LIST * sort_list) static
Definition at line 5437 of file xasl_to_stream.c.
References ER_FAILED, sort_list::next, NULL, xts_visited_ptr::offset, or_pack_int(), sort_list::pos_descr, xts_visited_ptr::ptr, sort_list::s_nulls, sort_list::s_order, xts_process_pos_descr(), and xts_save_sort_list().
Referenced by xts_save_sort_list().
static char * xts_process_srlist_id (char * ptr, const QFILE_SORTED_LIST_ID * sort_list_id) static
Definition at line 5420 of file xasl_to_stream.c.
References ER_FAILED, qfile_sorted_list_id::list_id, NULL, xts_visited_ptr::offset, or_pack_int(), xts_visited_ptr::ptr, qfile_sorted_list_id::sorted, and xts_save_list_id().
Referenced by xts_save_srlist_id().
static char * xts_process_union_proc (char * ptr, const UNION_PROC_NODE * union_proc) static
Definition at line 3183 of file xasl_to_stream.c.
References ER_FAILED, union_proc_node::left, NULL, xts_visited_ptr::offset, or_pack_int(), xts_visited_ptr::ptr, union_proc_node::right, and xts_save_xasl_node().
Referenced by xts_process_xasl_node().
static char * xts_process_update_proc (char * ptr, const UPDATE_PROC_NODE * update_info) static
Definition at line 3879 of file xasl_to_stream.c.
References update_proc_node::assigns, update_proc_node::classes, update_proc_node::cons_pred, ER_FAILED, update_proc_node::mvcc_reev_classes, update_proc_node::no_logging, NULL, update_proc_node::num_assign_reev_classes, update_proc_node::num_assigns, update_proc_node::num_classes, update_proc_node::num_orderby_keys, update_proc_node::num_reev_classes, xts_visited_ptr::offset, or_pack_int(), xts_visited_ptr::ptr, update_proc_node::wait_msecs, xts_save_int_array(), xts_save_pred_expr(), xts_save_update_assignment_array(), and xts_save_upddel_class_info_array().
Referenced by xts_process_xasl_node().
static char * xts_process_val_list (char * ptr, const VAL_LIST * val_list) static
Definition at line 4941 of file xasl_to_stream.c.
References ER_FAILED, i, qproc_db_value_list::next, NULL, xts_visited_ptr::offset, or_pack_int(), p, xts_visited_ptr::ptr, qproc_db_value_list::val, val_list_node::val_cnt, val_list_node::valp, and xts_save_db_value().
Referenced by xts_save_val_list().
static char * xts_process_xasl_header (char * ptr, const XASL_NODE_HEADER header) static
Definition at line 2723 of file xasl_to_stream.c.
References ASSERT_ALIGN, INT_ALIGNMENT, NULL, OR_PACK_XASL_NODE_HEADER, and xts_visited_ptr::ptr.
Referenced by xts_process_xasl_node().
static char * xts_process_xasl_node (char * ptr, const XASL_NODE * xasl) static
Definition at line 2736 of file xasl_to_stream.c.
References xasl_node::after_iscan_list, xasl_node::after_join_pred, xasl_node::aptr_list, assert, xasl_node::bptr_list, BUILD_SCHEMA_PROC, xasl_node::buildlist, BUILDLIST_PROC, xasl_node::buildvalue, BUILDVALUE_PROC, xasl_node::cardinality, xasl_node::cat_fetched, xasl_node::connect_by, xasl_node::connect_by_ptr, CONNECTBY_PROC, xasl_node::cte, CTE_PROC, xasl_node::curr_spec, xasl_node::delete_, DELETE_PROC, DIFFERENCE_PROC, DO_PROC, xasl_node::dptr_list, ER_FAILED, ER_QPROC_INVALID_XASLNODE, xasl_node::fetch, xasl_node::flag, xasl_node::fptr_list, xasl_node::header, xasl_node::if_pred, xasl_node::insert, INSERT_PROC, xasl_node::instnum_flag, xasl_node::instnum_pred, xasl_node::instnum_val, INTERSECTION_PROC, xasl_node::is_single_tuple, xasl_node::iscan_oid_order, xasl_node::iscycle_regu, xasl_node::iscycle_val, xasl_node::isleaf_regu, xasl_node::isleaf_val, xasl_node::level_regu, xasl_node::level_val, xasl_node::limit_offset, xasl_node::limit_row_count, xasl_node::list_id, MAX_ALIGNMENT, xasl_node::merge, MERGE_PROC, xasl_node::merge_spec, xasl_node::merge_val_list, xasl_node::mergelist, MERGELIST_PROC, xasl_node::mvcc_reev_extra_cls_cnt, access_spec_node::next, xasl_node::next, xasl_node::next_scan_block_on, xasl_node::next_scan_on, NULL, OBJFETCH_PROC, xts_visited_ptr::offset, xasl_node::option, or_pack_double(), or_pack_int(), xasl_node::ordbynum_flag, xasl_node::ordbynum_pred, xasl_node::ordbynum_val, xasl_node::orderby_limit, xasl_node::orderby_list, xasl_node::outptr_list, xasl_node::proc, xasl_node::projected_size, xts_visited_ptr::ptr, PTR_ALIGN, xasl_node::query_alias, xasl_node::save_instnum_val, xasl_node::scan_op_type, SCAN_PROC, xasl_node::scan_ptr, xasl_node::selected_upd_list, xasl_node::single_tuple, xasl_node::spec_list, xasl_node::type, xasl_node::union_, UNION_PROC, xasl_node::upd_del_class_cnt, xasl_node::update, UPDATE_PROC, xasl_node::val_list, xts_process_access_spec_type(), xts_process_buildlist_proc(), xts_process_buildvalue_proc(), xts_process_connectby_proc(), xts_process_cte_proc(), xts_process_delete_proc(), xts_process_fetch_proc(), xts_process_insert_proc(), xts_process_merge_proc(), xts_process_mergelist_proc(), xts_process_union_proc(), xts_process_update_proc(), xts_process_xasl_header(), xts_save_db_value(), xts_save_list_id(), xts_save_outptr_list(), xts_save_pred_expr(), xts_save_regu_variable(), xts_save_selupd_list(), xts_save_sort_list(), xts_save_string(), xts_save_val_list(), xts_save_xasl_node(), and xts_Xasl_errcode.
Referenced by xts_save_xasl_node().
static int xts_reserve_location_in_stream (int size) static
Definition at line 7425 of file xasl_to_stream.c.
References assert, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, MAX_ALIGNMENT, NULL, STREAM_EXPANSION_UNIT, xasl_stream_make_align(), xts_Free_offset_in_stream, xts_Stream_buffer, xts_Stream_size, and xts_Xasl_errcode.
Referenced by xts_map_filter_pred_to_stream(), xts_map_func_pred_to_stream(), xts_map_xasl_to_stream(), xts_save(), xts_save_aggregate_type(), xts_save_analytic_eval_type(), xts_save_analytic_type(), xts_save_arith_type(), xts_save_cache_attrinfo(), xts_save_db_value(), xts_save_db_value_array(), xts_save_filter_pred_node(), xts_save_func_pred(), xts_save_function_type(), xts_save_hfid_array(), xts_save_indx_info(), xts_save_int_array(), xts_save_list_id(), xts_save_method_sig(), xts_save_method_sig_list(), xts_save_odku_info(), xts_save_oid_array(), xts_save_outptr_list(), xts_save_pred_expr(), xts_save_regu_variable(), xts_save_selupd_list(), xts_save_sort_list(), xts_save_srlist_id(), xts_save_string(), xts_save_update_assignment_array(), xts_save_upddel_class_info(), xts_save_upddel_class_info_array(), xts_save_val_list(), and xts_save_xasl_node().
template<typename T > static int xts_save (const T & t) static
Definition at line 7516 of file xasl_to_stream.c.
References ER_FAILED, xts_visited_ptr::offset, xts_visited_ptr::ptr, xts_get_offset_visited_ptr(), xts_mark_ptr_visited(), xts_process(), xts_reserve_location_in_stream(), xts_sizeof(), and xts_Stream_buffer.
static int xts_save_aggregate_type (const AGGREGATE_TYPE * aggregate) static
Definition at line 492 of file xasl_to_stream.c.
References assert, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, free_and_init, NO_ERROR, NULL, xts_visited_ptr::offset, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, xts_get_offset_visited_ptr(), xts_mark_ptr_visited(), xts_process_aggregate_type(), xts_reserve_location_in_stream(), xts_sizeof_aggregate_type(), xts_Stream_buffer, and xts_Xasl_errcode.
Referenced by xts_process_aggregate_type(), xts_process_buildlist_proc(), and xts_process_buildvalue_proc().
static int xts_save_analytic_eval_type (const ANALYTIC_EVAL_TYPE * analytic) static
Definition at line 694 of file xasl_to_stream.c.
References ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, free_and_init, NO_ERROR, NULL, xts_visited_ptr::offset, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, xts_get_offset_visited_ptr(), xts_mark_ptr_visited(), xts_process_analytic_eval_type(), xts_reserve_location_in_stream(), xts_sizeof_analytic_eval_type(), xts_Stream_buffer, and xts_Xasl_errcode.
Referenced by xts_process_analytic_eval_type(), and xts_process_buildlist_proc().
static int xts_save_analytic_type (const ANALYTIC_TYPE * analytic) static
Definition at line 628 of file xasl_to_stream.c.
References ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, free_and_init, NO_ERROR, NULL, xts_visited_ptr::offset, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, xts_get_offset_visited_ptr(), xts_mark_ptr_visited(), xts_process_analytic_type(), xts_reserve_location_in_stream(), xts_sizeof_analytic_type(), xts_Stream_buffer, and xts_Xasl_errcode.
Referenced by xts_process_analytic_eval_type(), and xts_process_analytic_type().
static int xts_save_arith_type (const ARITH_TYPE * arithmetic) static
Definition at line 896 of file xasl_to_stream.c.
References assert, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, free_and_init, NO_ERROR, NULL, xts_visited_ptr::offset, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, xts_get_offset_visited_ptr(), xts_mark_ptr_visited(), xts_process_arith_type(), xts_reserve_location_in_stream(), xts_sizeof_arith_type(), xts_Stream_buffer, and xts_Xasl_errcode.
Referenced by xts_pack_regu_variable_value(), and xts_process_buildvalue_proc().
static int xts_save_cache_attrinfo (const HEAP_CACHE_ATTRINFO * ptr) static
Definition at line 1745 of file xasl_to_stream.c.
References assert, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, free_and_init, NO_ERROR, NULL, xts_visited_ptr::offset, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, xts_get_offset_visited_ptr(), xts_mark_ptr_visited(), xts_process_cache_attrinfo(), xts_process_ls_merge_info(), xts_reserve_location_in_stream(), xts_sizeof_cache_attrinfo(), xts_sizeof_insert_proc(), xts_sizeof_ls_merge_info(), xts_Stream_buffer, and xts_Xasl_errcode.
Referenced by xts_process_attr_descr(), xts_process_cls_spec_type(), xts_process_filter_pred_node(), xts_process_func_pred(), and xts_save_odku_info().
static int xts_save_db_value (const DB_VALUE * ptr) static
Definition at line 1456 of file xasl_to_stream.c.
References assert, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, free_and_init, NO_ERROR, NULL, xts_visited_ptr::offset, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, xts_get_offset_visited_ptr(), xts_mark_ptr_visited(), xts_process_db_value(), xts_reserve_location_in_stream(), xts_sizeof_db_value(), xts_Stream_buffer, and xts_Xasl_errcode.
Referenced by xts_pack_regu_variable_value(), xts_process(), xts_process_access_spec_type(), xts_process_aggregate_type(), xts_process_analytic_type(), xts_process_arith_type(), xts_process_buildlist_proc(), xts_process_buildvalue_proc(), xts_process_fetch_proc(), xts_process_function_type(), xts_process_insert_proc(), xts_process_regu_variable(), xts_process_val_list(), xts_process_xasl_node(), xts_save_db_value_array(), and xts_save_update_assignment().
static int xts_save_db_value_array (DB_VALUE ** ptr, int size) static
Definition at line 2362 of file xasl_to_stream.c.
References ER_FAILED, free_and_init, i, NO_ERROR, NULL, xts_visited_ptr::offset, or_pack_domain(), or_packed_domain_size(), xts_visited_ptr::ptr, xts_reserve_location_in_stream(), xts_save_db_value(), xts_save_int_array(), and xts_Stream_buffer.
Referenced by xts_process_cls_spec_type().
static int xts_save_filter_pred_node (const PRED_EXPR_WITH_CONTEXT * pred) static
Definition at line 1609 of file xasl_to_stream.c.
References assert, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, free_and_init, NO_ERROR, NULL, xts_visited_ptr::offset, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, xts_get_offset_visited_ptr(), xts_mark_ptr_visited(), xts_process_filter_pred_node(), xts_reserve_location_in_stream(), xts_sizeof_filter_pred_node(), xts_Stream_buffer, and xts_Xasl_errcode.
Referenced by xts_map_filter_pred_to_stream().
static int xts_save_func_pred (const FUNC_PRED * ptr) static
Definition at line 1677 of file xasl_to_stream.c.
References assert, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, free_and_init, NO_ERROR, NULL, xts_visited_ptr::offset, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, xts_get_offset_visited_ptr(), xts_mark_ptr_visited(), xts_process_func_pred(), xts_reserve_location_in_stream(), xts_sizeof_func_pred(), xts_Stream_buffer, and xts_Xasl_errcode.
Referenced by xts_map_func_pred_to_stream().
static int xts_save_function_type (const FUNCTION_TYPE * function) static
Definition at line 560 of file xasl_to_stream.c.
References assert, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, free_and_init, NO_ERROR, NULL, xts_visited_ptr::offset, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, xts_get_offset_visited_ptr(), xts_mark_ptr_visited(), xts_process_function_type(), xts_reserve_location_in_stream(), xts_sizeof_function_type(), xts_Stream_buffer, and xts_Xasl_errcode.
Referenced by xts_pack_regu_variable_value().
static int xts_save_hfid_array (HFID * ptr, int size) static
Definition at line 2457 of file xasl_to_stream.c.
References ER_FAILED, i, NULL, xts_visited_ptr::offset, OR_HFID_SIZE, or_pack_hfid(), xts_visited_ptr::ptr, xts_reserve_location_in_stream(), and xts_Stream_buffer.
Referenced by xts_save_upddel_class_info().
static int xts_save_indx_info (const INDX_INFO * indx_info) static
Definition at line 964 of file xasl_to_stream.c.
References assert, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, free_and_init, NO_ERROR, NULL, xts_visited_ptr::offset, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, xts_get_offset_visited_ptr(), xts_mark_ptr_visited(), xts_process_indx_info(), xts_reserve_location_in_stream(), xts_sizeof_indx_info(), xts_Stream_buffer, and xts_Xasl_errcode.
Referenced by xts_process_access_spec_type().
static int xts_save_int_array (int * ptr, int size) static
Definition at line 2431 of file xasl_to_stream.c.
References ER_FAILED, i, NULL, xts_visited_ptr::offset, OR_INT_SIZE, or_pack_int(), xts_visited_ptr::ptr, xts_reserve_location_in_stream(), and xts_Stream_buffer.
Referenced by xts_process_cls_spec_type(), xts_process_delete_proc(), xts_process_filter_pred_node(), xts_process_insert_proc(), xts_process_ls_merge_info(), xts_process_update_proc(), xts_save_db_value_array(), xts_save_key_range_array(), xts_save_odku_info(), xts_save_regu_variable_list(), xts_save_regu_varlist_list(), and xts_save_upddel_class_info().
static int xts_save_key_range_array (const KEY_RANGE * ptr, int size) static
Definition at line 2653 of file xasl_to_stream.c.
References ER_FAILED, free_and_init, i, NULL, xts_visited_ptr::offset, key_range::range, xts_get_offset_visited_ptr(), xts_save_int_array(), and xts_save_regu_variable().
Referenced by xts_process_key_info().
static int xts_save_list_id (const QFILE_LIST_ID * list_id) static
Definition at line 828 of file xasl_to_stream.c.
References assert, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, free_and_init, NO_ERROR, NULL, xts_visited_ptr::offset, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, xts_get_offset_visited_ptr(), xts_mark_ptr_visited(), xts_process_list_id(), xts_reserve_location_in_stream(), xts_sizeof_list_id(), xts_Stream_buffer, and xts_Xasl_errcode.
Referenced by xts_process_aggregate_type(), xts_process_analytic_type(), xts_process_buildlist_proc(), xts_process_connectby_proc(), xts_process_srlist_id(), and xts_process_xasl_node().
static int xts_save_method_sig (const METHOD_SIG * ptr, int size) static
Definition at line 2218 of file xasl_to_stream.c.
References assert, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, free_and_init, NO_ERROR, NULL, xts_visited_ptr::offset, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, xts_get_offset_visited_ptr(), xts_mark_ptr_visited(), xts_process_method_sig(), xts_reserve_location_in_stream(), xts_sizeof_method_sig(), xts_Stream_buffer, and xts_Xasl_errcode.
Referenced by xts_process_method_sig(), and xts_process_method_sig_list().
static int xts_save_method_sig_list (const METHOD_SIG_LIST * ptr) static
Definition at line 2150 of file xasl_to_stream.c.
References assert, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, free_and_init, NO_ERROR, NULL, xts_visited_ptr::offset, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, xts_get_offset_visited_ptr(), xts_mark_ptr_visited(), xts_process_method_sig_list(), xts_reserve_location_in_stream(), xts_sizeof_method_sig_list(), xts_Stream_buffer, and xts_Xasl_errcode.
Referenced by xts_process_method_spec_type().
static int xts_save_odku_info (const ODKU_INFO * odku_info) static
Definition at line 3792 of file xasl_to_stream.c.
References ARG_FILE_LINE, odku_info::assignments, odku_info::attr_ids, odku_info::attr_info, odku_info::cons_pred, ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), free_and_init, NULL, odku_info::num_assigns, xts_visited_ptr::offset, or_pack_int(), xts_visited_ptr::ptr, xts_reserve_location_in_stream(), xts_save_cache_attrinfo(), xts_save_int_array(), xts_save_pred_expr(), xts_save_update_assignment_array(), xts_sizeof_odku_info(), and xts_Stream_buffer.
Referenced by xts_process_insert_proc().
static int xts_save_oid_array (OID * ptr, int size) static
Definition at line 2483 of file xasl_to_stream.c.
References ER_FAILED, i, NULL, xts_visited_ptr::offset, OR_OID_SIZE, or_pack_oid(), xts_visited_ptr::ptr, xts_reserve_location_in_stream(), and xts_Stream_buffer.
Referenced by xts_save_upddel_class_info().
static int xts_save_outptr_list (const OUTPTR_LIST * outptr_list) static
Definition at line 1032 of file xasl_to_stream.c.
References assert, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, free_and_init, NO_ERROR, NULL, xts_visited_ptr::offset, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, xts_get_offset_visited_ptr(), xts_mark_ptr_visited(), xts_process_outptr_list(), xts_reserve_location_in_stream(), xts_sizeof_outptr_list(), xts_Stream_buffer, and xts_Xasl_errcode.
Referenced by xts_process_buildlist_proc(), xts_process_cls_spec_type(), xts_process_connectby_proc(), xts_process_insert_proc(), and xts_process_xasl_node().
static int xts_save_pred_expr (const PRED_EXPR * ptr) static
Definition at line 1168 of file xasl_to_stream.c.
References assert, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, free_and_init, NO_ERROR, NULL, xts_visited_ptr::offset, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, xts_get_offset_visited_ptr(), xts_mark_ptr_visited(), xts_process_pred_expr(), xts_reserve_location_in_stream(), xts_sizeof_pred_expr(), xts_Stream_buffer, and xts_Xasl_errcode.
Referenced by xts_process_access_spec_type(), xts_process_arith_type(), xts_process_buildlist_proc(), xts_process_buildvalue_proc(), xts_process_connectby_proc(), xts_process_fetch_proc(), xts_process_filter_pred_node(), xts_process_insert_proc(), xts_process_pred(), xts_process_pred_expr(), xts_process_update_proc(), xts_process_xasl_node(), and xts_save_odku_info().
static int xts_save_regu_variable (const REGU_VARIABLE * ptr) static
Definition at line 1236 of file xasl_to_stream.c.
References assert, CAST_BUFLEN, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, free_and_init, NO_ERROR, NULL, xts_visited_ptr::offset, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, xts_get_offset_visited_ptr(), xts_mark_ptr_visited(), xts_process_regu_variable(), xts_reserve_location_in_stream(), xts_sizeof_regu_variable(), xts_Stream_buffer, and xts_Xasl_errcode.
Referenced by xts_process(), xts_process_aggregate_type(), xts_process_alsm_eval_term(), xts_process_analytic_type(), xts_process_arith_type(), xts_process_comp_eval_term(), xts_process_func_pred(), xts_process_indx_info(), xts_process_key_info(), xts_process_like_eval_term(), xts_process_rlike_eval_term(), xts_process_set_spec_type(), xts_process_xasl_node(), xts_save_key_range_array(), xts_save_regu_variable_list(), and xts_save_update_assignment().
static int xts_save_regu_variable_list (const REGU_VARIABLE_LIST ptr) static
Definition at line 2515 of file xasl_to_stream.c.
References ER_FAILED, free_and_init, i, regu_variable_list_node::next, NULL, xts_visited_ptr::offset, OFFSET_BUFFER_SIZE, xts_get_offset_visited_ptr(), xts_mark_ptr_visited(), xts_save_int_array(), and xts_save_regu_variable().
Referenced by xts_process_buildlist_proc(), xts_process_cls_spec_type(), xts_process_connectby_proc(), xts_process_function_type(), xts_process_list_spec_type(), xts_process_method_spec_type(), xts_process_outptr_list(), xts_process_regu_variable_list(), xts_process_set_spec_type(), xts_process_showstmt_spec_type(), and xts_save_regu_varlist_list().
static int xts_save_regu_varlist_list (const REGU_VARLIST_LIST ptr) static
Definition at line 2584 of file xasl_to_stream.c.
References ER_FAILED, free_and_init, i, regu_varlist_list_node::next, NULL, xts_visited_ptr::offset, OFFSET_BUFFER_SIZE, xts_get_offset_visited_ptr(), xts_mark_ptr_visited(), xts_save_int_array(), and xts_save_regu_variable_list().
Referenced by xts_process_selupd_list().
static int xts_save_selupd_list (const SELUPD_LIST * selupd_list) static
Definition at line 1100 of file xasl_to_stream.c.
References assert, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, free_and_init, NO_ERROR, NULL, xts_visited_ptr::offset, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, xts_get_offset_visited_ptr(), xts_mark_ptr_visited(), xts_process_selupd_list(), xts_reserve_location_in_stream(), xts_sizeof_selupd_list(), xts_Stream_buffer, and xts_Xasl_errcode.
Referenced by xts_process_selupd_list(), and xts_process_xasl_node().
static int xts_save_sort_list (const SORT_LIST * ptr) static
Definition at line 1320 of file xasl_to_stream.c.
References assert, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, free_and_init, NO_ERROR, NULL, xts_visited_ptr::offset, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, xts_get_offset_visited_ptr(), xts_mark_ptr_visited(), xts_process_sort_list(), xts_reserve_location_in_stream(), xts_sizeof_sort_list(), xts_Stream_buffer, and xts_Xasl_errcode.
Referenced by xts_process_aggregate_type(), xts_process_analytic_eval_type(), xts_process_buildlist_proc(), xts_process_sort_list(), and xts_process_xasl_node().
static int xts_save_srlist_id (const QFILE_SORTED_LIST_ID * sort_list_id) static
Definition at line 760 of file xasl_to_stream.c.
References assert, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, free_and_init, NO_ERROR, NULL, xts_visited_ptr::offset, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, xts_get_offset_visited_ptr(), xts_mark_ptr_visited(), xts_process_srlist_id(), xts_reserve_location_in_stream(), xts_sizeof_srlist_id(), xts_Stream_buffer, and xts_Xasl_errcode.
Referenced by xts_pack_regu_variable_value().
static int xts_save_string (const char * str) static
Definition at line 2289 of file xasl_to_stream.c.
References assert, ER_FAILED, NULL, xts_visited_ptr::offset, or_pack_string_with_length(), or_packed_string_length(), xts_get_offset_visited_ptr(), xts_mark_ptr_visited(), xts_reserve_location_in_stream(), and xts_Stream_buffer.
Referenced by xts_process(), xts_process_method_sig(), and xts_process_xasl_node().
static char * xts_save_update_assignment (char * ptr, const UPDATE_ASSIGNMENT * assign) static
Definition at line 3704 of file xasl_to_stream.c.
References update_assignment::att_idx, update_assignment::cls_idx, update_assignment::constant, ER_FAILED, NULL, xts_visited_ptr::offset, or_pack_int(), xts_visited_ptr::ptr, update_assignment::regu_var, xts_save_db_value(), and xts_save_regu_variable().
Referenced by xts_save_update_assignment_array().
static int xts_save_update_assignment_array (const UPDATE_ASSIGNMENT * assigns, int nelements) static
Definition at line 3748 of file xasl_to_stream.c.
References assert, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, free_and_init, NULL, xts_visited_ptr::offset, xts_visited_ptr::ptr, xts_reserve_location_in_stream(), xts_save_update_assignment(), xts_sizeof_update_assignment(), and xts_Stream_buffer.
Referenced by xts_process_update_proc(), and xts_save_odku_info().
static char * xts_save_upddel_class_info (char * ptr, const UPDDEL_CLASS_INFO * upd_cls) static
Definition at line 3571 of file xasl_to_stream.c.
References assert, upddel_class_info::att_id, upddel_class_info::class_hfid, upddel_class_info::class_oid, ER_FAILED, upddel_class_info::has_uniques, i, upddel_class_info::lob_attr_ids, upddel_class_info::mvcc_extra_assign_reev, upddel_class_info::needs_pruning, NULL, upddel_class_info::num_attrs, upddel_class_info::num_extra_assign_reev, upddel_class_info::num_lob_attrs, upddel_class_info::num_subclasses, xts_visited_ptr::offset, or_pack_int(), p, xts_visited_ptr::ptr, xts_reserve_location_in_stream(), xts_save_hfid_array(), xts_save_int_array(), xts_save_oid_array(), and xts_Stream_buffer.
Referenced by xts_save_upddel_class_info_array().
static int xts_save_upddel_class_info_array (const UPDDEL_CLASS_INFO * classes, int nelements) static
Definition at line 3660 of file xasl_to_stream.c.
References assert, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, free_and_init, NULL, xts_visited_ptr::offset, xts_visited_ptr::ptr, xts_reserve_location_in_stream(), xts_save_upddel_class_info(), xts_sizeof_upddel_class_info(), and xts_Stream_buffer.
Referenced by xts_process_delete_proc(), and xts_process_update_proc().
static int xts_save_val_list (const VAL_LIST * ptr) static
Definition at line 1388 of file xasl_to_stream.c.
References assert, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, free_and_init, NO_ERROR, NULL, xts_visited_ptr::offset, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, xts_get_offset_visited_ptr(), xts_mark_ptr_visited(), xts_process_val_list(), xts_reserve_location_in_stream(), xts_sizeof_val_list(), xts_Stream_buffer, and xts_Xasl_errcode.
Referenced by xts_process_buildlist_proc(), xts_process_connectby_proc(), xts_process_mergelist_proc(), and xts_process_xasl_node().
static int xts_save_xasl_node (const XASL_NODE * ptr) static
Definition at line 1524 of file xasl_to_stream.c.
References assert, CAST_BUFLEN, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, free_and_init, NO_ERROR, NULL, xts_visited_ptr::offset, OR_ALIGNED_BUF, OR_ALIGNED_BUF_SIZE, OR_ALIGNED_BUF_START, xts_get_offset_visited_ptr(), xts_mark_ptr_visited(), xts_process_xasl_node(), xts_reserve_location_in_stream(), xts_sizeof_xasl_node(), xts_Stream_buffer, and xts_Xasl_errcode.
Referenced by xts_map_xasl_to_stream(), xts_process_buildlist_proc(), xts_process_cte_proc(), xts_process_list_spec_type(), xts_process_merge_proc(), xts_process_mergelist_proc(), xts_process_method_spec_type(), xts_process_regu_variable(), xts_process_union_proc(), and xts_process_xasl_node().
static int xts_sizeof (const json_table_column & ptr) static
Definition at line 6733 of file xasl_to_stream.c.
References JSON_TABLE_EXISTS, JSON_TABLE_ORDINALITY, cubxasl::json_table::column::m_domain, cubxasl::json_table::column::m_function, cubxasl::json_table::column::m_on_empty, cubxasl::json_table::column::m_on_error, OR_INT_SIZE, or_packed_domain_size(), PTR_SIZE, and xts_sizeof_json_table_column_behavior().
Referenced by xts_debug_check(), xts_save(), xts_sizeof(), and xts_sizeof_access_spec_type().
static int xts_sizeof (const json_table_node & ptr) static
Definition at line 6762 of file xasl_to_stream.c.
References i, cubxasl::json_table::node::m_nested_nodes, cubxasl::json_table::node::m_nested_nodes_size, cubxasl::json_table::node::m_output_columns, cubxasl::json_table::node::m_output_columns_size, OR_INT_SIZE, PTR_SIZE, and xts_sizeof().
static int xts_sizeof (const json_table_spec_node & ptr) static
Definition at line 6793 of file xasl_to_stream.c.
References cubxasl::json_table::spec_node::m_root_node, OR_INT_SIZE, PTR_SIZE, and xts_sizeof().
static int xts_sizeof_access_spec_type (const ACCESS_SPEC_TYPE * ptr) static
Definition at line 6464 of file xasl_to_stream.c.
References ACCESS_SPEC_CLS_SPEC, ACCESS_SPEC_JSON_TABLE_SPEC, ACCESS_SPEC_LIST_SPEC, ACCESS_SPEC_METHOD_SPEC, ACCESS_SPEC_SET_SPEC, ACCESS_SPEC_SHOWSTMT_SPEC, ER_FAILED, ER_QPROC_INVALID_XASLNODE, OR_INT_SIZE, PTR_SIZE, TARGET_CLASS, TARGET_CLASS_ATTR, TARGET_JSON_TABLE, TARGET_LIST, TARGET_METHOD, TARGET_REGUVAL_LIST, TARGET_SET, TARGET_SHOWSTMT, access_spec_node::type, xts_sizeof(), xts_sizeof_cls_spec_type(), xts_sizeof_list_spec_type(), xts_sizeof_method_spec_type(), xts_sizeof_set_spec_type(), xts_sizeof_showstmt_spec_type(), and xts_Xasl_errcode.
Referenced by xts_sizeof_mergelist_proc(), and xts_sizeof_xasl_node().
static int xts_sizeof_aggregate_type (const AGGREGATE_TYPE * ptr) static
Definition at line 7022 of file xasl_to_stream.c.
References cubxasl::aggregate_list_node::domain, ER_FAILED, cubxasl::aggregate_list_node::function, cubxasl::aggregate_list_node::info, NULL, cubxasl::aggregate_list_node::operands, OR_BTID_ALIGNED_SIZE, OR_INT_SIZE, or_packed_domain_size(), cubxasl::aggregate_specific_function_info::percentile, cubxasl::aggregate_percentile_info::percentile_reguvar, PT_PERCENTILE_CONT, PT_PERCENTILE_DISC, PTR_SIZE, xts_sizeof_regu_variable(), and xts_sizeof_regu_variable_list().
Referenced by xts_save_aggregate_type().
static int xts_sizeof_alsm_eval_term (const ALSM_EVAL_TERM * ptr) static
Definition at line 6411 of file xasl_to_stream.c.
References OR_INT_SIZE, and PTR_SIZE.
Referenced by xts_sizeof_eval_term().
static int xts_sizeof_analytic_eval_type (const ANALYTIC_EVAL_TYPE * ptr) static
Definition at line 7145 of file xasl_to_stream.c.
References PTR_SIZE.
Referenced by xts_save_analytic_eval_type().
static int xts_sizeof_analytic_type (const ANALYTIC_TYPE * ptr) static
Definition at line 7091 of file xasl_to_stream.c.
References cubxasl::analytic_list_node::domain, ER_FAILED, cubxasl::analytic_list_node::function, cubxasl::analytic_list_node::info, NULL, cubxasl::analytic_list_node::operand, OR_INT_SIZE, or_packed_domain_size(), cubxasl::analytic_function_info::percentile, cubxasl::analytic_percentile_function_info::percentile_reguvar, PT_PERCENTILE_CONT, PT_PERCENTILE_DISC, PTR_SIZE, and xts_sizeof_regu_variable().
Referenced by xts_save_analytic_type().
static int xts_sizeof_arith_type (const ARITH_TYPE * ptr) static
Definition at line 6995 of file xasl_to_stream.c.
References arith_list_node::domain, arith_list_node::opcode, OR_INT_SIZE, or_packed_domain_size(), PTR_SIZE, T_CASE, T_DECODE, T_IF, and T_PREDICATE.
Referenced by xts_save_arith_type().
static int xts_sizeof_attr_descr (const ATTR_DESCR * ptr) static
Definition at line 6951 of file xasl_to_stream.c.
References OR_INT_SIZE, and PTR_SIZE.
Referenced by xts_get_regu_variable_value_size().
static int xts_sizeof_buildlist_proc (const BUILDLIST_PROC_NODE * ptr) static
Definition at line 5941 of file xasl_to_stream.c.
References OR_INT_SIZE, and PTR_SIZE.
Referenced by xts_sizeof_xasl_node().
static int xts_sizeof_buildvalue_proc (const BUILDVALUE_PROC_NODE * ptr) static
Definition at line 5981 of file xasl_to_stream.c.
References OR_INT_SIZE, and PTR_SIZE.
Referenced by xts_sizeof_xasl_node().
static int xts_sizeof_cache_attrinfo (const HEAP_CACHE_ATTRINFO * ptr) static
Definition at line 5896 of file xasl_to_stream.c.
References OR_INT_SIZE.
Referenced by xts_save_cache_attrinfo().
static int xts_sizeof_cls_spec_type (const CLS_SPEC_TYPE * ptr) static
Definition at line 6618 of file xasl_to_stream.c.
References OR_HFID_SIZE, OR_INT_SIZE, OR_OID_SIZE, and PTR_SIZE.
Referenced by xts_sizeof_access_spec_type().
static int xts_sizeof_comp_eval_term (const COMP_EVAL_TERM * ptr) static
Definition at line 6393 of file xasl_to_stream.c.
References OR_INT_SIZE, and PTR_SIZE.
Referenced by xts_sizeof_eval_term().
static int xts_sizeof_connectby_proc (const CONNECTBY_PROC_NODE * ptr) static
Definition at line 7236 of file xasl_to_stream.c.
References OR_INT_SIZE, and PTR_SIZE.
Referenced by xts_sizeof_xasl_node().
static int xts_sizeof_cte_proc (const CTE_PROC_NODE * ptr) static
Definition at line 6204 of file xasl_to_stream.c.
References PTR_SIZE.
Referenced by xts_sizeof_xasl_node().
static int xts_sizeof_db_value (const DB_VALUE * ptr) static
Definition at line 6984 of file xasl_to_stream.c.
References or_db_value_size().
Referenced by xts_save_db_value().
static int xts_sizeof_delete_proc (const DELETE_PROC_NODE * ptr) static
Definition at line 6138 of file xasl_to_stream.c.
References OR_INT_SIZE, and PTR_SIZE.
Referenced by xts_sizeof_xasl_node().
static int xts_sizeof_eval_term (const EVAL_TERM * ptr) static
Definition at line 6335 of file xasl_to_stream.c.
References ER_FAILED, ER_QPROC_INVALID_XASLNODE, cubxasl::eval_term::et, cubxasl::eval_term::et_alsm, cubxasl::eval_term::et_comp, cubxasl::eval_term::et_like, cubxasl::eval_term::et_rlike, cubxasl::eval_term::et_type, OR_INT_SIZE, T_ALSM_EVAL_TERM, T_COMP_EVAL_TERM, T_LIKE_EVAL_TERM, T_RLIKE_EVAL_TERM, xts_sizeof_alsm_eval_term(), xts_sizeof_comp_eval_term(), xts_sizeof_like_eval_term(), xts_sizeof_rlike_eval_term(), and xts_Xasl_errcode.
Referenced by xts_sizeof_pred_expr().
static int xts_sizeof_fetch_proc (const FETCH_PROC_NODE * ptr) static
Definition at line 5923 of file xasl_to_stream.c.
References OR_INT_SIZE, and PTR_SIZE.
Referenced by xts_sizeof_xasl_node().
static int xts_sizeof_filter_pred_node (const PRED_EXPR_WITH_CONTEXT * ptr) static
Definition at line 5862 of file xasl_to_stream.c.
References OR_INT_SIZE, and PTR_SIZE.
Referenced by xts_save_filter_pred_node().
static int xts_sizeof_func_pred (const FUNC_PRED * ptr) static
Definition at line 5880 of file xasl_to_stream.c.
References PTR_SIZE.
Referenced by xts_save_func_pred().
static int xts_sizeof_function_type (const FUNCTION_TYPE * ptr) static
Definition at line 7074 of file xasl_to_stream.c.
References OR_INT_SIZE, and PTR_SIZE.
Referenced by xts_save_function_type().
static int xts_sizeof_indx_info (const INDX_INFO * ptr) static
Definition at line 6560 of file xasl_to_stream.c.
References ER_FAILED, indx_info::key_info, OR_BTID_ALIGNED_SIZE, OR_INT_SIZE, PTR_SIZE, and xts_sizeof_key_info().
Referenced by xts_save_indx_info().
static int xts_sizeof_insert_proc (const INSERT_PROC_NODE * ptr) static
Definition at line 6158 of file xasl_to_stream.c.
References insert_proc_node::num_val_lists, OR_HFID_SIZE, OR_INT_SIZE, OR_OID_SIZE, and PTR_SIZE.
Referenced by xts_save_cache_attrinfo(), and xts_sizeof_xasl_node().
static int xts_sizeof_json_table_column_behavior (const json_table_column_behavior * behavior) static
Definition at line 6720 of file xasl_to_stream.c.
References JSON_TABLE_DEFAULT_VALUE, json_table_column_behavior::m_behavior, json_table_column_behavior::m_default_value, OR_INT_SIZE, and OR_VALUE_ALIGNED_SIZE.
Referenced by xts_sizeof().
static int xts_sizeof_key_info (const KEY_INFO * ptr) static
Definition at line 6597 of file xasl_to_stream.c.
References OR_INT_SIZE, and PTR_SIZE.
Referenced by xts_sizeof_indx_info().
static int xts_sizeof_like_eval_term (const LIKE_EVAL_TERM * ptr) static
Definition at line 6430 of file xasl_to_stream.c.
References PTR_SIZE.
Referenced by xts_sizeof_eval_term().
static int xts_sizeof_list_id (const QFILE_LIST_ID * ptr) static
Definition at line 6813 of file xasl_to_stream.c.
References or_listid_length().
Referenced by xts_save_list_id().
static int xts_sizeof_list_spec_type (const LIST_SPEC_TYPE * ptr) static
Definition at line 6656 of file xasl_to_stream.c.
References OR_INT_SIZE, and PTR_SIZE.
Referenced by xts_sizeof_access_spec_type().
static int xts_sizeof_ls_merge_info (const QFILE_LIST_MERGE_INFO * ptr) static
Definition at line 6000 of file xasl_to_stream.c.
References OR_INT_SIZE, and PTR_SIZE.
Referenced by xts_save_cache_attrinfo(), and xts_sizeof_mergelist_proc().
static int xts_sizeof_merge_proc (const MERGE_PROC_NODE * ptr) static
Definition at line 6187 of file xasl_to_stream.c.
References OR_INT_SIZE, and PTR_SIZE.
Referenced by xts_sizeof_xasl_node().
static int xts_sizeof_mergelist_proc (const MERGELIST_PROC_NODE * ptr) static
Definition at line 6024 of file xasl_to_stream.c.
References mergelist_proc_node::inner_spec_list, mergelist_proc_node::ls_merge, access_spec_node::next, NULL, OR_INT_SIZE, mergelist_proc_node::outer_spec_list, PTR_SIZE, xts_sizeof_access_spec_type(), and xts_sizeof_ls_merge_info().
Referenced by xts_sizeof_xasl_node().
static int xts_sizeof_method_sig (const METHOD_SIG * ptr) static
Definition at line 7216 of file xasl_to_stream.c.
References method_sig_node::num_method_args, OR_INT_SIZE, and PTR_SIZE.
Referenced by xts_save_method_sig().
static int xts_sizeof_method_sig_list (const METHOD_SIG_LIST * ptr) static
Definition at line 7205 of file xasl_to_stream.c.
References OR_INT_SIZE, and PTR_SIZE.
Referenced by xts_save_method_sig_list().
static int xts_sizeof_method_spec_type (const METHOD_SPEC_TYPE * ptr) static
Definition at line 6708 of file xasl_to_stream.c.
References PTR_SIZE.
Referenced by xts_sizeof_access_spec_type().
static int xts_sizeof_odku_info (const ODKU_INFO * odku_info) static
Definition at line 6094 of file xasl_to_stream.c.
References OR_INT_SIZE, and PTR_SIZE.
Referenced by xts_save_odku_info().
static int xts_sizeof_outptr_list (const OUTPTR_LIST * ptr) static
Definition at line 6221 of file xasl_to_stream.c.
References OR_INT_SIZE, and PTR_SIZE.
Referenced by xts_save_outptr_list().
static int xts_sizeof_pos_descr (const QFILE_TUPLE_VALUE_POSITION * ptr) static
Definition at line 6968 of file xasl_to_stream.c.
References qfile_tuple_value_position::dom, OR_INT_SIZE, and or_packed_domain_size().
Referenced by xts_get_regu_variable_value_size(), and xts_sizeof_sort_list().
static int xts_sizeof_pred (const PRED * ptr) static
Definition at line 6301 of file xasl_to_stream.c.
References cubxasl::pred_expr::m_pred, OR_INT_SIZE, cubxasl::pred_expr::pe, PTR_SIZE, cubxasl::pred::rhs, T_PRED, and cubxasl::pred_expr::type.
Referenced by xts_sizeof_pred_expr().
static int xts_sizeof_pred_expr (const PRED_EXPR * ptr) static
Definition at line 6237 of file xasl_to_stream.c.
References ER_FAILED, ER_QPROC_INVALID_XASLNODE, cubxasl::pred_expr::m_eval_term, cubxasl::pred_expr::m_pred, OR_INT_SIZE, cubxasl::pred_expr::pe, PTR_SIZE, T_EVAL_TERM, T_NOT_TERM, T_PRED, cubxasl::pred_expr::type, xts_sizeof_eval_term(), xts_sizeof_pred(), and xts_Xasl_errcode.
Referenced by xts_save_pred_expr().
static int xts_sizeof_regu_value_list (const REGU_VALUE_LIST * regu_value_list) static
Definition at line 7263 of file xasl_to_stream.c.
References assert, ER_FAILED, regu_value_item::next, OR_INT_SIZE, regu_value_list::regu_list, regu_value_item::value, and xts_get_regu_variable_value_size().
Referenced by xts_get_regu_variable_value_size().
static int xts_sizeof_regu_variable (const REGU_VARIABLE * ptr) static
Definition at line 6849 of file xasl_to_stream.c.
References ER_FAILED, NULL, OR_INT_SIZE, or_packed_domain_size(), PTR_SIZE, and xts_get_regu_variable_value_size().
Referenced by xts_save_regu_variable(), xts_sizeof_aggregate_type(), and xts_sizeof_analytic_type().
static int xts_sizeof_regu_variable_list (const REGU_VARIABLE_LIST regu_var_list) static
Definition at line 7294 of file xasl_to_stream.c.
References assert, ER_FAILED, regu_variable_list_node::next, NULL, OR_INT_SIZE, regu_variable_list_node::value, and xts_get_regu_variable_value_size().
Referenced by xts_get_regu_variable_value_size(), and xts_sizeof_aggregate_type().
static int xts_sizeof_rlike_eval_term (const RLIKE_EVAL_TERM * ptr) static
Definition at line 6447 of file xasl_to_stream.c.
References PTR_SIZE.
Referenced by xts_sizeof_eval_term().
static int xts_sizeof_selupd_list (const SELUPD_LIST * ptr) static
Definition at line 6281 of file xasl_to_stream.c.
References OR_HFID_SIZE, OR_INT_SIZE, OR_OID_SIZE, and PTR_SIZE.
Referenced by xts_save_selupd_list().
static int xts_sizeof_set_spec_type (const SET_SPEC_TYPE * ptr) static
Definition at line 6692 of file xasl_to_stream.c.
References PTR_SIZE.
Referenced by xts_sizeof_access_spec_type().
static int xts_sizeof_showstmt_spec_type (const SHOWSTMT_SPEC_TYPE * ptr) static
Definition at line 6676 of file xasl_to_stream.c.
References OR_INT_SIZE, and PTR_SIZE.
Referenced by xts_sizeof_access_spec_type().
static int xts_sizeof_sort_list (const SORT_LIST * ptr) static
Definition at line 7178 of file xasl_to_stream.c.
References ER_FAILED, OR_INT_SIZE, sort_list::pos_descr, PTR_SIZE, and xts_sizeof_pos_descr().
Referenced by xts_save_sort_list().
static int xts_sizeof_srlist_id (const QFILE_SORTED_LIST_ID * ptr) static
Definition at line 7162 of file xasl_to_stream.c.
References OR_INT_SIZE, and PTR_SIZE.
Referenced by xts_save_srlist_id().
static int xts_sizeof_union_proc (const UNION_PROC_NODE * ptr) static
Definition at line 5907 of file xasl_to_stream.c.
References PTR_SIZE.
Referenced by xts_sizeof_xasl_node().
static int xts_sizeof_update_assignment (const UPDATE_ASSIGNMENT * assign) static
Definition at line 6081 of file xasl_to_stream.c.
References OR_INT_SIZE, and PTR_SIZE.
Referenced by xts_save_update_assignment_array().
static int xts_sizeof_update_proc (const UPDATE_PROC_NODE * ptr) static
Definition at line 6113 of file xasl_to_stream.c.
References OR_INT_SIZE, and PTR_SIZE.
Referenced by xts_sizeof_xasl_node().
static int xts_sizeof_upddel_class_info (const UPDDEL_CLASS_INFO * upd_cls) static
Definition at line 6056 of file xasl_to_stream.c.
References OR_INT_SIZE, and PTR_SIZE.
Referenced by xts_save_upddel_class_info_array().
static int xts_sizeof_val_list (const VAL_LIST * ptr) static
Definition at line 6828 of file xasl_to_stream.c.
References qproc_db_value_list::next, NULL, OR_INT_SIZE, p, PTR_SIZE, and val_list_node::valp.
Referenced by xts_save_val_list().
static int xts_sizeof_xasl_node (const XASL_NODE * ptr) static
Definition at line 5672 of file xasl_to_stream.c.
References BUILD_SCHEMA_PROC, xasl_node::buildlist, BUILDLIST_PROC, xasl_node::buildvalue, BUILDVALUE_PROC, xasl_node::connect_by, CONNECTBY_PROC, xasl_node::cte, CTE_PROC, xasl_node::curr_spec, xasl_node::delete_, DELETE_PROC, DIFFERENCE_PROC, DO_PROC, ER_FAILED, ER_QPROC_INVALID_XASLNODE, xasl_node::fetch, xasl_node::insert, INSERT_PROC, INTERSECTION_PROC, xasl_node::merge, MERGE_PROC, xasl_node::merge_spec, xasl_node::mergelist, MERGELIST_PROC, access_spec_node::next, NULL, OBJFETCH_PROC, OR_DOUBLE_ALIGNED_SIZE, OR_INT_SIZE, xasl_node::proc, PTR_SIZE, SCAN_PROC, xasl_node::spec_list, xasl_node::type, xasl_node::union_, UNION_PROC, xasl_node::update, UPDATE_PROC, XASL_NODE_HEADER_SIZE, xts_sizeof_access_spec_type(), xts_sizeof_buildlist_proc(), xts_sizeof_buildvalue_proc(), xts_sizeof_connectby_proc(), xts_sizeof_cte_proc(), xts_sizeof_delete_proc(), xts_sizeof_fetch_proc(), xts_sizeof_insert_proc(), xts_sizeof_merge_proc(), xts_sizeof_mergelist_proc(), xts_sizeof_union_proc(), xts_sizeof_update_proc(), and xts_Xasl_errcode.
Referenced by xts_save_xasl_node().
Variable Documentation
int xts_Free_offset_in_stream = 0 static
Definition at line 65 of file xasl_to_stream.c.
Referenced by xts_map_filter_pred_to_stream(), xts_map_func_pred_to_stream(), xts_map_xasl_to_stream(), and xts_reserve_location_in_stream().
XTS_VISITED_PTR* xts_Ptr_blocks[MAX_PTR_BLOCKS] = { 0 } static
Definition at line 68 of file xasl_to_stream.c.
int xts_Ptr_lwm[MAX_PTR_BLOCKS] = { 0 } static
Definition at line 71 of file xasl_to_stream.c.
Referenced by xts_free_visited_ptrs(), xts_get_offset_visited_ptr(), and xts_mark_ptr_visited().
int xts_Ptr_max[MAX_PTR_BLOCKS] = { 0 } static
Definition at line 72 of file xasl_to_stream.c.
Referenced by xts_mark_ptr_visited().
char* xts_Stream_buffer = NULL static
Definition at line 63 of file xasl_to_stream.c.
Referenced by xts_debug_check(), xts_map_filter_pred_to_stream(), xts_map_func_pred_to_stream(), xts_map_xasl_to_stream(), xts_reserve_location_in_stream(), xts_save(), xts_save_aggregate_type(), xts_save_analytic_eval_type(), xts_save_analytic_type(), xts_save_arith_type(), xts_save_cache_attrinfo(), xts_save_db_value(), xts_save_db_value_array(), xts_save_filter_pred_node(), xts_save_func_pred(), xts_save_function_type(), xts_save_hfid_array(), xts_save_indx_info(), xts_save_int_array(), xts_save_list_id(), xts_save_method_sig(), xts_save_method_sig_list(), xts_save_odku_info(), xts_save_oid_array(), xts_save_outptr_list(), xts_save_pred_expr(), xts_save_regu_variable(), xts_save_selupd_list(), xts_save_sort_list(), xts_save_srlist_id(), xts_save_string(), xts_save_update_assignment_array(), xts_save_upddel_class_info(), xts_save_upddel_class_info_array(), xts_save_val_list(), and xts_save_xasl_node().
int xts_Stream_size = 0 static
Definition at line 64 of file xasl_to_stream.c.
Referenced by xts_debug_check(), xts_map_filter_pred_to_stream(), xts_map_func_pred_to_stream(), xts_map_xasl_to_stream(), and xts_reserve_location_in_stream().
int xts_Xasl_errcode = NO_ERROR static
Definition at line 75 of file xasl_to_stream.c.
Referenced by xts_get_regu_variable_value_size(), xts_map_filter_pred_to_stream(), xts_map_func_pred_to_stream(), xts_map_xasl_to_stream(), xts_mark_ptr_visited(), xts_pack_regu_variable_value(), xts_process_access_spec_type(), xts_process_eval_term(), xts_process_pred_expr(), xts_process_regu_value_list(), xts_process_xasl_node(), xts_reserve_location_in_stream(), xts_save_aggregate_type(), xts_save_analytic_eval_type(), xts_save_analytic_type(), xts_save_arith_type(), xts_save_cache_attrinfo(), xts_save_db_value(), xts_save_filter_pred_node(), xts_save_func_pred(), xts_save_function_type(), xts_save_indx_info(), xts_save_list_id(), xts_save_method_sig(), xts_save_method_sig_list(), xts_save_outptr_list(), xts_save_pred_expr(), xts_save_regu_variable(), xts_save_selupd_list(), xts_save_sort_list(), xts_save_srlist_id(), xts_save_val_list(), xts_save_xasl_node(), xts_sizeof_access_spec_type(), xts_sizeof_eval_term(), xts_sizeof_pred_expr(), and xts_sizeof_xasl_node().