CUBRID Engine: src/parser/xasl_regu_alloc.hpp File Reference
xasl_regu_alloc.hpp File Reference
#include "dbtype_def.h"
#include "storage_common.h"
#include "xasl.h"
#include "parser_support.h"
Namespaces
cubxasl
Functions
template<typename T >
void regu_init (T &t)
void regu_init (db_value &dbval)
void regu_init (regu_variable_node &regu)
void regu_init (regu_variable_list_node &regu_varlist)
void regu_init (cubxasl::pred_expr &pr)
void regu_init (indx_info &ii)
void regu_init (tp_domain &dom)
void regu_init (selupd_list &selupd)
void regu_init (key_range &kr)
void regu_init (OID &oid)
void regu_init (HFID &hfid)
void regu_init (upddel_class_info &upddel)
void regu_init (update_assignment &assign)
void regu_init (arith_list_node &arith)
void regu_init (function_node &fnode)
void regu_init (cubxasl::aggregate_list_node &agg)
void regu_init (cubxasl::analytic_list_node &ana)
void regu_init (xasl_node &node)
void regu_init (sort_list &sl)
void regu_init (qfile_list_id &list_id)
void regu_init (access_spec_node &spec)
template<typename T >
void regu_alloc (T *&ptr)
template<typename T >
void regu_array_alloc (T **ptr, size_t size)
int * regu_int_array_alloc (int size)
OID * regu_oid_array_alloc (int size)
void regu_dbval_type_init (db_value *ptr, DB_TYPE type)
xasl_node * regu_xasl_node_alloc (PROC_TYPE type)
access_spec_node * regu_spec_alloc (TARGET_TYPE type)
Function Documentation
template<typename T > void regu_alloc (T *& ptr)
Definition at line 112 of file xasl_regu_alloc.hpp.
References ER_REGU_NO_SPACE, NULL, pt_alloc_packing_buf(), regu_init(), and regu_set_error_with_zero_args().
Referenced by pt_add_pseudocolumns_placeholders(), pt_agg_orderby_to_sort_list(), pt_attribute_to_regu(), pt_build_analytic_eval_list(), pt_clone_val_list(), pt_copy_val_list(), pt_create_iss_range(), pt_fix_buildlist_aggregate_cume_dist_percent_rank(), pt_function_to_regu(), pt_generate_simple_analytic_eval_type(), pt_get_mvcc_reev_range_data(), pt_init_pred_expr_context(), pt_link_regu_to_selupd_list(), pt_make_connect_by_proc(), pt_make_constant_regu_list_from_val_list(), pt_make_function(), pt_make_outlist_from_vallist(), pt_make_pos_regu_list(), pt_make_pos_regu_var_from_scratch(), pt_make_position_regu_variable(), pt_make_pred_expr_pred(), pt_make_pred_term_comp(), pt_make_pred_term_like(), pt_make_pred_term_not(), pt_make_pred_term_rlike(), pt_make_pred_term_some_all(), pt_make_regu_arith(), pt_make_regu_constant(), pt_make_regu_hostvar(), pt_make_regu_insert(), pt_make_regu_iscycle(), pt_make_regu_isleaf(), pt_make_regu_level(), pt_make_regu_numbering(), pt_make_regu_pred(), pt_make_regu_reguvalues_list(), pt_make_regu_subquery(), pt_make_reserved_value_list(), pt_make_val_list(), pt_make_vid(), pt_set_analytic_node_etc(), pt_set_iscycle_node_etc_pre(), pt_set_isleaf_node_etc_pre(), pt_set_level_node_etc_pre(), pt_set_numbering_node_etc_pre(), pt_to_aggregate_node(), pt_to_analytic_node(), pt_to_class_spec_list(), pt_to_cume_dist_percent_rank_regu_variable(), pt_to_func_pred(), pt_to_index_info(), pt_to_merge_update_xasl(), pt_to_method_sig_list(), pt_to_odku_info(), pt_to_outlist(), pt_to_position_regu_variable_list(), pt_to_pred_with_context(), pt_to_regu_attr_descr(), pt_to_regu_reserved_name(), pt_to_regu_variable(), pt_to_regu_variable_list(), pt_to_sort_list(), pt_to_update_xasl(), ptqo_single_orderby(), regu_init(), regu_make_constant_vid(), regu_spec_alloc(), regu_xasl_node_alloc(), regu_xasl_proc_init(), and setof_mop_to_setof_vobj().
template<typename T > void regu_array_alloc (T ** ptr, size_t size)
Definition at line 125 of file xasl_regu_alloc.hpp.
References ER_REGU_NO_SPACE, NULL, pt_alloc_packing_buf(), regu_init(), and regu_set_error_with_zero_args().
Referenced by pt_to_delete_xasl(), pt_to_index_info(), pt_to_insert_xasl(), pt_to_list_key(), pt_to_merge_update_xasl(), pt_to_odku_info(), pt_to_range_key(), pt_to_rangelist_key(), pt_to_single_key(), pt_to_update_xasl(), regu_int_array_alloc(), and regu_oid_array_alloc().
void regu_dbval_type_init (db_value * ptr, DB_TYPE type)
Definition at line 405 of file xasl_regu_alloc.cpp.
References assert, DB_DEFAULT_PRECISION, DB_DEFAULT_SCALE, db_value_domain_init(), and NO_ERROR.
Referenced by pt_make_function(), pt_make_regu_arith(), pt_make_regu_pred(), pt_make_vid(), pt_set_analytic_node_etc(), pt_to_aggregate_node(), pt_to_analytic_node(), and regu_init().
template<typename T > void regu_init (T & t)
Definition at line 105 of file xasl_regu_alloc.hpp.
Referenced by regu_alloc(), and regu_array_alloc().
void regu_init (db_value & dbval)
Definition at line 414 of file xasl_regu_alloc.cpp.
References DB_TYPE_NULL, and regu_dbval_type_init().
void regu_init (regu_variable_node & regu)
Definition at line 332 of file xasl_regu_alloc.cpp.
References regu_variable_node::domain, regu_variable_node::flags, NULL, regu_variable_node::type, TYPE_POS_VALUE, regu_variable_node::regu_data_value::val_pos, regu_variable_node::value, regu_variable_node::vfetch_to, and regu_variable_node::xasl.
void regu_init (regu_variable_list_node & regu_varlist)
Definition at line 343 of file xasl_regu_alloc.cpp.
References regu_variable_list_node::next, NULL, regu_init(), and regu_variable_list_node::value.
void regu_init (cubxasl::pred_expr & pr)
Definition at line 256 of file xasl_regu_alloc.cpp.
References cubxasl::pred_expr::m_not_term, NULL, cubxasl::pred_expr::pe, T_NOT_TERM, and cubxasl::pred_expr::type.
void regu_init (indx_info & ii)
Definition at line 208 of file xasl_regu_alloc.cpp.
References indx_info::class_oid, indx_info::coverage, indx_info::groupby_desc, indx_info::groupby_skip, key_info::is_constant, key_info::is_user_given_keylimit, indx_info::iss_range, key_range::key1, key_range::key2, key_info::key_cnt, indx_info::key_info, key_info::key_limit_l, key_info::key_limit_reset, key_info::key_limit_u, key_info::key_ranges, NA_NA, NULL, OID_SET_NULL, indx_info::orderby_desc, indx_info::orderby_skip, R_KEY, key_range::range, indx_info::range_type, indx_info::use_desc_index, and indx_info::use_iss.
void regu_init (tp_domain & dom)
Definition at line 350 of file xasl_regu_alloc.cpp.
References DB_TYPE_INTEGER, and tp_domain_init().
void regu_init (selupd_list & selupd)
Definition at line 393 of file xasl_regu_alloc.cpp.
References selupd_list::class_hfid, selupd_list::class_oid, vfid::fileid, hfid::hpgid, selupd_list::next, NULL, NULL_FILEID, NULL_PAGEID, NULL_VOLID, regu_init(), selupd_list::select_list, selupd_list::select_list_size, hfid::vfid, and vfid::volid.
void regu_init (key_range & kr)
Definition at line 232 of file xasl_regu_alloc.cpp.
References key_range::key1, key_range::key2, NA_NA, NULL, and key_range::range.
void regu_init (OID & oid)
Definition at line 356 of file xasl_regu_alloc.cpp.
References OID_SET_NULL.
void regu_init (HFID & hfid)
Definition at line 362 of file xasl_regu_alloc.cpp.
References HFID_SET_NULL.
void regu_init (upddel_class_info & upddel)
Definition at line 368 of file xasl_regu_alloc.cpp.
References upddel_class_info::att_id, upddel_class_info::class_hfid, upddel_class_info::class_oid, DB_NOT_PARTITIONED_CLASS, upddel_class_info::has_uniques, upddel_class_info::lob_attr_ids, upddel_class_info::mvcc_extra_assign_reev, upddel_class_info::needs_pruning, NULL, upddel_class_info::num_attrs, upddel_class_info::num_extra_assign_reev, upddel_class_info::num_lob_attrs, and upddel_class_info::num_subclasses.
void regu_init (update_assignment & assign)
Definition at line 384 of file xasl_regu_alloc.cpp.
References update_assignment::att_idx, update_assignment::cls_idx, update_assignment::constant, NULL, and update_assignment::regu_var.
void regu_init (arith_list_node & arith)
Definition at line 263 of file xasl_regu_alloc.cpp.
References arith_list_node::domain, LEADING, arith_list_node::leftptr, arith_list_node::misc_operand, NULL, arith_list_node::opcode, arith_list_node::rand_seed, regu_alloc(), arith_list_node::rightptr, T_ADD, arith_list_node::thirdptr, and arith_list_node::value.
void regu_init (function_node & fnode)
Definition at line 278 of file xasl_regu_alloc.cpp.
References function_node::ftype, NULL, function_node::operand, regu_alloc(), function_node::tmp_obj, and function_node::value.
void regu_init (cubxasl::aggregate_list_node & agg)
Definition at line 289 of file xasl_regu_alloc.cpp.
References cubxasl::aggregate_list_node::accumulator, cubxasl::aggregate_accumulator::curr_cnt, cubxasl::aggregate_list_node::function, cubxasl::aggregate_list_node::info, cubxasl::aggregate_list_node::list_id, cubxasl::aggregate_list_node::next, NULL, cubxasl::aggregate_list_node::operands, cubxasl::aggregate_list_node::option, regu_alloc(), cubxasl::aggregate_list_node::sort_list, cubxasl::aggregate_accumulator::value, and cubxasl::aggregate_accumulator::value2.
void regu_init (cubxasl::analytic_list_node & ana)
Definition at line 308 of file xasl_regu_alloc.cpp.
References cubxasl::analytic_list_node::curr_cnt, DB_TYPE_NULL, cubxasl::analytic_list_node::default_idx, cubxasl::analytic_list_node::flag, cubxasl::analytic_list_node::from_last, cubxasl::analytic_list_node::function, cubxasl::analytic_list_node::ignore_nulls, cubxasl::analytic_list_node::is_const_operand, cubxasl::analytic_list_node::list_id, cubxasl::analytic_list_node::next, NULL, cubxasl::analytic_list_node::offset_idx, cubxasl::analytic_list_node::operand, cubxasl::analytic_list_node::opr_dbtype, cubxasl::analytic_list_node::out_value, regu_alloc(), regu_init(), cubxasl::analytic_list_node::sort_list_size, cubxasl::analytic_list_node::sort_prefix_size, cubxasl::analytic_list_node::value, and cubxasl::analytic_list_node::value2.
void regu_init (xasl_node & node)
Definition at line 54 of file xasl_regu_alloc.cpp.
References xasl_node::iscan_oid_order, xasl_node::list_id, xasl_node::option, prm_get_bool_value(), PRM_ID_BT_INDEX_SCAN_OID_ORDER, Q_ALL, regu_alloc(), S_SELECT, and xasl_node::scan_op_type.
Referenced by regu_init(), and regu_spec_target_init().
void regu_init (sort_list & sl)
Definition at line 240 of file xasl_regu_alloc.cpp.
References qfile_tuple_value_position::dom, sort_list::next, NULL, sort_list::pos_descr, qfile_tuple_value_position::pos_no, S_ASC, sort_list::s_nulls, S_NULLS_FIRST, sort_list::s_order, and tp_Integer_domain.
void regu_init (qfile_list_id & list_id)
Definition at line 250 of file xasl_regu_alloc.cpp.
References QFILE_CLEAR_LIST_ID.
void regu_init (access_spec_node & spec)
Definition at line 141 of file xasl_regu_alloc.cpp.
References access_spec_node::access, ACCESS_METHOD_SEQUENTIAL, ACCESS_SPEC_FLAG_NONE, access_spec_node::flags, access_spec_node::indexptr, access_spec_node::next, NULL, access_spec_node::s_dbval, access_spec_node::single_fetch, access_spec_node::where_key, access_spec_node::where_pred, and access_spec_node::where_range.
int* regu_int_array_alloc (int size)
Definition at line 420 of file xasl_regu_alloc.cpp.
References NULL, and regu_array_alloc().
Referenced by parser_generate_xasl(), pt_init_pred_expr_context(), pt_make_class_access_spec(), pt_to_delete_xasl(), pt_to_insert_xasl(), pt_to_merge_insert_xasl(), pt_to_merge_update_xasl(), pt_to_merge_xasl(), pt_to_method_arglist(), pt_to_odku_info(), and pt_to_update_xasl().
OID* regu_oid_array_alloc (int size)
Definition at line 428 of file xasl_regu_alloc.cpp.
References NULL, and regu_array_alloc().
Referenced by parser_generate_xasl(), pt_to_delete_xasl(), pt_to_insert_xasl(), pt_to_merge_insert_xasl(), pt_to_merge_update_xasl(), pt_to_merge_xasl(), and pt_to_update_xasl().
access_spec_node* regu_spec_alloc (TARGET_TYPE type)
Definition at line 127 of file xasl_regu_alloc.cpp.
References NULL, regu_alloc(), and regu_spec_target_init().
Referenced by pt_make_access_spec().
xasl_node* regu_xasl_node_alloc (PROC_TYPE type)
Definition at line 41 of file xasl_regu_alloc.cpp.
References NULL, regu_alloc(), and regu_xasl_proc_init().
Referenced by parser_generate_do_stmt_xasl(), pt_make_aptr_parent_node(), pt_make_connect_by_proc(), pt_plan_cte(), pt_skeleton_buildlist_proc(), pt_to_buildlist_proc(), pt_to_buildschema_proc(), pt_to_buildvalue_proc(), pt_to_fetch_as_scan_proc(), pt_to_fetch_proc(), pt_to_insert_xasl(), pt_to_merge_xasl(), pt_to_union_proc(), ptqo_to_list_scan_proc(), ptqo_to_merge_list_proc(), and ptqo_to_scan_proc().