CUBRID Engine: src/query/xasl_to_stream.h File Reference
xasl_to_stream.h File Reference
Functions
int xts_map_xasl_to_stream (const xasl_node *xasl, xasl_stream *stream)
int xts_map_filter_pred_to_stream (const pred_expr_with_context *pred, char **stream, int *size)
int xts_map_func_pred_to_stream (const func_pred *xasl, char **stream, int *size)
Function Documentation
int xts_map_filter_pred_to_stream (const pred_expr_with_context * pred, char ** stream, int * size)
Definition at line 372 of file xasl_to_stream.c.
References ER_FAILED, ER_QPROC_INVALID_XASLNODE, free_and_init, NO_ERROR, NULL, xts_visited_ptr::offset, or_pack_int(), p, xasl_stream_make_align(), xts_Free_offset_in_stream, xts_free_visited_ptrs(), xts_reserve_location_in_stream(), xts_save_filter_pred_node(), xts_Stream_buffer, xts_Stream_size, and xts_Xasl_errcode.
Referenced by create_or_drop_index_helper(), and do_recreate_filter_index_constr().
int xts_map_func_pred_to_stream (const func_pred * xasl, char ** stream, int * size)
Definition at line 435 of file xasl_to_stream.c.
References ER_FAILED, ER_QPROC_INVALID_XASLNODE, free_and_init, NO_ERROR, NULL, xts_visited_ptr::offset, or_pack_int(), or_unpack_int(), p, xasl_stream_make_align(), xts_Free_offset_in_stream, xts_free_visited_ptrs(), xts_reserve_location_in_stream(), xts_save_func_pred(), xts_Stream_buffer, xts_Stream_size, and xts_Xasl_errcode.
Referenced by pt_node_to_function_index().
int xts_map_xasl_to_stream (const xasl_node * xasl, xasl_stream * stream)
Definition at line 272 of file xasl_to_stream.c.
References assert, xasl_stream::buffer, xasl_stream::buffer_size, xasl_node::class_locks, xasl_node::class_oid_list, xasl_node::creator_oid, xasl_node::dbval_cnt, ER_FAILED, ER_QPROC_INVALID_XASLNODE, free_and_init, i, xasl_node::n_oid_list, NO_ERROR, NULL, xts_visited_ptr::offset, or_pack_int(), or_pack_oid(), p, xasl_node::tcard_list, xasl_stream_make_align(), xts_Free_offset_in_stream, xts_free_visited_ptrs(), xts_reserve_location_in_stream(), xts_save_xasl_node(), xts_Stream_buffer, xts_Stream_size, and xts_Xasl_errcode.
Referenced by build_xasl_for_server_delete(), do_execute_do(), do_insert_at_server(), do_prepare_delete(), do_prepare_insert_internal(), do_prepare_merge(), do_prepare_select(), do_prepare_update(), do_select_internal(), and update_at_server().