CUBRID Engine: src/xasl/xasl_unpack_info.hpp File Reference
xasl_unpack_info.hpp File Reference
#include "porting.h"
#include "system.h"
#include "thread_compat.hpp"
Classes
struct visited_ptr
struct unpack_extra_buf
struct xasl_unpack_info
Typedefs
typedef struct visited_ptr STX_VISITED_PTR
typedef struct unpack_extra_buf UNPACK_EXTRA_BUF
typedef struct xasl_unpack_info XASL_UNPACK_INFO
Functions
XASL_UNPACK_INFO * get_xasl_unpack_info_ptr (THREAD_ENTRY *thread_p)
void set_xasl_unpack_info_ptr (THREAD_ENTRY *thread_p, XASL_UNPACK_INFO *ptr)
void free_xasl_unpack_info (THREAD_ENTRY *thread_p, REFPTR(XASL_UNPACK_INFO, xasl_unpack_info))
void free_unpack_extra_buff (THREAD_ENTRY *thread_p, XASL_UNPACK_INFO *unpack_info_ptr)
int xasl_stream_get_ptr_block (const void *ptr)
Variables
const size_t MAX_PTR_BLOCKS = 256
Typedef Documentation
typedef struct visited_ptr STX_VISITED_PTR
Definition at line 33 of file xasl_unpack_info.hpp.
typedef struct unpack_extra_buf UNPACK_EXTRA_BUF
Definition at line 41 of file xasl_unpack_info.hpp.
typedef struct xasl_unpack_info XASL_UNPACK_INFO
Definition at line 49 of file xasl_unpack_info.hpp.
Function Documentation
void free_unpack_extra_buff (THREAD_ENTRY * thread_p, XASL_UNPACK_INFO * unpack_info_ptr)
Definition at line 86 of file xasl_unpack_info.cpp.
References xasl_unpack_info::additional_buffers, unpack_extra_buf::buff, db_private_free_and_init, unpack_extra_buf::next, and NULL.
Referenced by free_xasl_unpack_info().
void free_xasl_unpack_info (THREAD_ENTRY * thread_p, REFPTR(XASL_UNPACK_INFO, xasl_unpack_info))
Definition at line 67 of file xasl_unpack_info.cpp.
References db_private_free_and_init, free_unpack_extra_buff(), and NULL.
Referenced by fpcache_entry_uninit(), fpcache_retire(), heap_eval_function_index(), heap_free_func_pred_unpack_info(), partition_free_partition_predicate(), qmgr_process_query(), stx_map_stream_to_filter_pred(), stx_map_stream_to_func_pred(), stx_map_stream_to_xasl(), xbtree_load_index(), xbtree_load_online_index(), xcache_clone_decache(), and xcache_retire_clone().
XASL_UNPACK_INFO* get_xasl_unpack_info_ptr (THREAD_ENTRY * thread_p)
Definition at line 35 of file xasl_unpack_info.cpp.
References xasl_Unpack_info.
Referenced by stx_alloc_struct(), stx_build(), stx_build_access_spec_type(), stx_build_aggregate_type(), stx_build_alsm_eval_term(), stx_build_analytic_eval_type(), stx_build_analytic_type(), stx_build_arith_type(), stx_build_attr_descr(), stx_build_buildlist_proc(), stx_build_buildvalue_proc(), stx_build_cls_spec_type(), stx_build_comp_eval_term(), stx_build_connectby_proc(), stx_build_cte_proc(), stx_build_delete_proc(), stx_build_fetch_proc(), stx_build_filter_pred_node(), stx_build_func_pred(), stx_build_function_type(), stx_build_indx_info(), stx_build_insert_proc(), stx_build_key_info(), stx_build_like_eval_term(), stx_build_list_spec_type(), stx_build_ls_merge_info(), stx_build_merge_proc(), stx_build_mergelist_proc(), stx_build_method_sig(), stx_build_method_sig_list(), stx_build_method_spec_type(), stx_build_outptr_list(), stx_build_pred(), stx_build_pred_expr(), stx_build_regu_variable(), stx_build_regu_variable_list(), stx_build_rlike_eval_term(), stx_build_selupd_list(), stx_build_set_spec_type(), stx_build_showstmt_spec_type(), stx_build_sort_list(), stx_build_srlist_id(), stx_build_union_proc(), stx_build_update_assignment(), stx_build_update_class_info(), stx_build_update_proc(), stx_build_val_list(), stx_build_xasl_node(), stx_free_visited_ptrs(), stx_get_struct_visited_ptr(), stx_map_stream_to_filter_pred(), stx_map_stream_to_func_pred(), stx_map_stream_to_xasl(), stx_mark_struct_visited(), stx_restore(), stx_restore_db_value_array_extra(), stx_restore_key_range_array(), stx_restore_odku_info(), stx_restore_regu_variable_list(), stx_restore_regu_varlist_list(), stx_restore_string(), stx_unpack_regu_variable_value(), and xts_debug_check().
void set_xasl_unpack_info_ptr (THREAD_ENTRY * thread_p, XASL_UNPACK_INFO * ptr)
Definition at line 50 of file xasl_unpack_info.cpp.
Referenced by stx_init_xasl_unpack_info(), stx_map_stream_to_filter_pred(), stx_map_stream_to_func_pred(), stx_map_stream_to_xasl(), and xts_debug_check().
int xasl_stream_get_ptr_block (const void * ptr) inline
Definition at line 89 of file xasl_unpack_info.hpp.
References MAX_PTR_BLOCKS.
Referenced by stx_get_struct_visited_ptr(), stx_mark_struct_visited(), xts_get_offset_visited_ptr(), and xts_mark_ptr_visited().
Variable Documentation
const size_t MAX_PTR_BLOCKS = 256
Definition at line 30 of file xasl_unpack_info.hpp.
Referenced by stx_free_visited_ptrs(), stx_init_xasl_unpack_info(), xasl_stream_get_ptr_block(), and xts_free_visited_ptrs().