CUBRID Engine: src/base/xserver_interface.h File Reference
xserver_interface.h File Reference
#include "boot.h"
#include "config.h"
#include "error_manager.h"
#include "file_io.h"
#include "intl_support.h"
#include "locator.h"
#include "log_comm.h"
#include "log_lsa.hpp"
#include "query_list.h"
#include "query_manager.h"
#include "perf_monitor.h"
#include "replication.h"
#include "storage_common.h"
#include "thread_compat.hpp"
Functions
int xboot_initialize_server (const BOOT_CLIENT_CREDENTIAL *client_credential, BOOT_DB_PATH_INFO *db_path_info, bool db_overwrite, const char *file_addmore_vols, volatile DKNPAGES db_npages, PGLENGTH db_desired_pagesize, volatile DKNPAGES xlog_npages, PGLENGTH db_desired_log_page_size, OID *rootclass_oid, HFID *rootclass_hfid, int client_lock_wait, TRAN_ISOLATION client_isolation)
const char * xboot_get_server_session_key (void)
int xboot_register_client (THREAD_ENTRY *thread_p, BOOT_CLIENT_CREDENTIAL *client_credential, int client_lock_wait, TRAN_ISOLATION client_isolation, TRAN_STATE *tran_state, BOOT_SERVER_CREDENTIAL *server_credential)
int xboot_unregister_client (REFPTR(THREAD_ENTRY, thread_p), int tran_index)
int xboot_backup (THREAD_ENTRY *thread_p, const char *backup_path, FILEIO_BACKUP_LEVEL backup_level, bool delete_unneeded_logarchives, const char *backup_verbose_file, int num_threads, FILEIO_ZIP_METHOD zip_method, FILEIO_ZIP_LEVEL zip_level, int skip_activelog, int sleep_msecs, bool separate_keys)
DISK_ISVALID xboot_checkdb_table (THREAD_ENTRY *thread_p, int check_flag, OID *oid, BTID *index_btid)
int xboot_check_db_consistency (THREAD_ENTRY *thread_p, int check_flag, OID *oids, int num_oids, BTID *index_btid)
VOLID xboot_add_volume_extension (THREAD_ENTRY *thread_p, DBDEF_VOL_EXT_INFO *ext_info)
int xboot_find_number_permanent_volumes (THREAD_ENTRY *thread_p)
int xboot_find_number_temp_volumes (THREAD_ENTRY *thread_p)
VOLID xboot_find_last_permanent (THREAD_ENTRY *thread_p)
VOLID xboot_peek_last_permanent (THREAD_ENTRY *thread_p)
VOLID xboot_find_last_temp (THREAD_ENTRY *thread_p)
LC_FIND_CLASSNAME xlocator_reserve_class_names (THREAD_ENTRY *thread_p, const int num_classes, const char **classname, OID *class_oid)
int xlocator_get_reserved_class_name_oid (THREAD_ENTRY *thread_p, const char *classname, OID *class_oid)
LC_FIND_CLASSNAME xlocator_delete_class_name (THREAD_ENTRY *thread_p, const char *classname)
LC_FIND_CLASSNAME xlocator_rename_class_name (THREAD_ENTRY *thread_p, const char *oldname, const char *newname, OID *class_oid)
LC_FIND_CLASSNAME xlocator_find_class_oid (THREAD_ENTRY *thread_p, const char *classname, OID *class_oid, LOCK lock)
int xlocator_assign_oid (THREAD_ENTRY *thread_p, const HFID *hfid, OID *perm_oid, int expected_length, OID *class_oid, const char *classname)
int xlocator_fetch (THREAD_ENTRY *thrd, OID *oid, int chn, LOCK lock, LC_FETCH_VERSION_TYPE fetch_version_type, LC_FETCH_VERSION_TYPE initial_fetch_version_type, OID *class_oid, int class_chn, int prefetching, LC_COPYAREA **fetch_area)
int xlocator_get_class (THREAD_ENTRY *thread_p, OID *class_oid, int class_chn, const OID *oid, LOCK lock, int prefetching, LC_COPYAREA **fetch_area)
int xlocator_fetch_all (THREAD_ENTRY *thread_p, const HFID *hfid, LOCK *lock, LC_FETCH_VERSION_TYPE fetch_type, OID *class_oid, int *nobjects, int *nfetched, OID *last_oid, LC_COPYAREA **fetch_area)
int xlocator_lock_and_fetch_all (THREAD_ENTRY *thread_p, const HFID *hfid, LOCK *instance_lock, int *instance_lock_timeout, OID *class_oid, LOCK *class_lock, int *nobjects, int *nfetched, int *nfailed_instance_locks, OID *last_oid, LC_COPYAREA **fetch_area, MVCC_SNAPSHOT *mvcc_snapshot)
int xlocator_fetch_lockset (THREAD_ENTRY *thread_p, LC_LOCKSET *lockset, LC_COPYAREA **fetch_area)
int xlocator_fetch_all_reference_lockset (THREAD_ENTRY *thread_p, OID *oid, int chn, OID *class_oid, int class_chn, LOCK lock, int quit_on_errors, int prune_level, LC_LOCKSET **lockset, LC_COPYAREA **fetch_area)
LC_FIND_CLASSNAME xlocator_find_lockhint_class_oids (THREAD_ENTRY *thread_p, int num_classes, const char **many_classnames, LOCK *many_locks, int *many_need_subclasses, LC_PREFETCH_FLAGS *many_flags, OID *guessed_class_oids, int *guessed_class_chns, bool quit_on_errors, LC_LOCKHINT **hlock, LC_COPYAREA **fetch_area)
int xlocator_fetch_lockhint_classes (THREAD_ENTRY *thread_p, LC_LOCKHINT *lockhint, LC_COPYAREA **fetch_area)
int xlocator_does_exist (THREAD_ENTRY *thread_p, OID *oid, int chn, LOCK lock, LC_FETCH_VERSION_TYPE fetch_version_type, OID *class_oid, int class_chn, int need_fetching, int prefetching, LC_COPYAREA **fetch_area)
int xlocator_force (THREAD_ENTRY *thread_p, LC_COPYAREA *copy_area, int num_ignore_error_list, int *ignore_error_list)
int xlocator_repl_force (THREAD_ENTRY *thread_p, LC_COPYAREA *copy_area, LC_COPYAREA **reply_area)
bool xlocator_notify_isolation_incons (THREAD_ENTRY *thread_p, LC_COPYAREA **synch_area)
int xlocator_assign_oid_batch (THREAD_ENTRY *thread_p, LC_OIDSET *oidset)
int xlocator_remove_class_from_index (THREAD_ENTRY *thread_p, OID *oid, BTID *btid, HFID *hfid)
int xlocator_check_fk_validity (THREAD_ENTRY *thread_p, OID *cls_oid, HFID *hfid, TP_DOMAIN *key_type, int n_attrs, int *attr_ids, OID *pk_cls_oid, BTID *pk_btid, char *fk_name)
LOG_LSA * xrepl_log_get_append_lsa (void)
int xrepl_set_info (THREAD_ENTRY *thread_p, REPL_INFO *repl_info)
int xheap_create (THREAD_ENTRY *thread_p, HFID *hfid, const OID *class_oid, bool reuse_oid)
int xheap_destroy (THREAD_ENTRY *thread_p, const HFID *hfid, const OID *class_oid)
int xheap_destroy_newly_created (THREAD_ENTRY *thread_p, const HFID *hfid, const OID *class_oid)
int xfile_apply_tde_to_class_files (THREAD_ENTRY *thread_p, const OID *class_oid)
int xtde_get_mk_info (THREAD_ENTRY *thread_p, int *mk_index, time_t *created_time, time_t *set_time)
int xtde_change_mk_without_flock (THREAD_ENTRY *thread_p, const int mk_index)
TRAN_STATE xtran_server_commit (THREAD_ENTRY *thrd, bool retain_lock)
TRAN_STATE xtran_server_abort (THREAD_ENTRY *thrd)
int xtran_server_start_topop (THREAD_ENTRY *thread_p, LOG_LSA *topop_lsa)
TRAN_STATE xtran_server_end_topop (THREAD_ENTRY *thread_p, LOG_RESULT_TOPOP result, LOG_LSA *topop_lsa)
int xtran_server_savepoint (THREAD_ENTRY *thread_p, const char *savept_name, LOG_LSA *savept_lsa)
TRAN_STATE xtran_server_partial_abort (THREAD_ENTRY *thread_p, const char *savept_name, LOG_LSA *savept_lsa)
int xtran_server_set_global_tran_info (THREAD_ENTRY *thread_p, int gtrid, void *info, int size)
int xtran_server_get_global_tran_info (THREAD_ENTRY *thread_p, int gtrid, void *buffer, int size)
int xtran_server_2pc_start (THREAD_ENTRY *thread_p)
TRAN_STATE xtran_server_2pc_prepare (THREAD_ENTRY *thread_p)
int xtran_server_2pc_recovery_prepared (THREAD_ENTRY *thread_p, int gtrids[], int size)
int xtran_server_2pc_attach_global_tran (THREAD_ENTRY *thread_p, int gtrid)
TRAN_STATE xtran_server_2pc_prepare_global_tran (THREAD_ENTRY *thread_p, int gtrid)
bool xtran_is_blocked (THREAD_ENTRY *thread_p, int tran_index)
bool xtran_server_has_updated (THREAD_ENTRY *thread_p)
int xtran_server_is_active_and_has_updated (THREAD_ENTRY *thread_p)
int xtran_wait_server_active_trans (THREAD_ENTRY *thrd)
int xtran_lock_rep_read (THREAD_ENTRY *thread_p, LOCK lock_rr_tran)
void xlogtb_set_interrupt (THREAD_ENTRY *thread_p, int set)
void xlogtb_set_suppress_repl_on_transaction (THREAD_ENTRY *thread_p, int set)
int xlogtb_reset_wait_msecs (THREAD_ENTRY *thread_p, int wait_msecs)
int xlogtb_reset_isolation (THREAD_ENTRY *thread_p, TRAN_ISOLATION isolation)
LOG_LSA * log_get_final_restored_lsa (void)
float log_get_db_compatibility (void)
int log_set_no_logging (void)
bool logtb_has_updated (THREAD_ENTRY *thread_p)
BTID * xbtree_add_index (THREAD_ENTRY *thread_p, BTID *btid, TP_DOMAIN *key_type, OID *class_oid, int attr_id, int unique_pk, int num_oids, int num_nulls, int num_keys)
BTID * xbtree_load_index (THREAD_ENTRY *thread_p, BTID *btid, const char *bt_name, TP_DOMAIN *key_type, OID *class_oids, int n_classes, int n_attrs, int *attr_ids, int *attrs_prefix_length, HFID *hfids, int unique_pk, int not_null_flag, OID *fk_refcls_oid, BTID *fk_refcls_pk_btid, const char *fk_name, char *pred_stream, int pred_stream_size, char *expr_stream, int expr_steram_size, int func_col_id, int func_attr_index_start)
BTID * xbtree_load_online_index (THREAD_ENTRY *thread_p, BTID *btid, const char *bt_name, TP_DOMAIN *key_type, OID *class_oids, int n_classes, int n_attrs, int *attr_ids, int *attrs_prefix_length, HFID *hfids, int unique_pk, int not_null_flag, OID *fk_refcls_oid, BTID *fk_refcls_pk_btid, const char *fk_name, char *pred_stream, int pred_stream_size, char *expr_stream, int expr_steram_size, int func_col_id, int func_attr_index_start, int ib_thread_count)
int xbtree_delete_index (THREAD_ENTRY *thread_p, BTID *btid)
BTREE_SEARCH xbtree_find_unique (THREAD_ENTRY *thread_p, BTID *btid, SCAN_OPERATION_TYPE scan_op_type, DB_VALUE *key, OID *class_oid, OID *oid, bool is_all_class_srch)
int xbtree_class_test_unique (THREAD_ENTRY *thread_p, char *buf, int buf_size)
BTREE_SEARCH xbtree_find_multi_uniques (THREAD_ENTRY *thread_p, OID *class_oid, int pruning_type, BTID *btids, DB_VALUE *values, int count, SCAN_OPERATION_TYPE op_type, OID **oids, int *oids_count)
EHID * xehash_create (THREAD_ENTRY *thread_p, EHID *ehid, DB_TYPE key_type, int exp_num_entries, OID *class_oid, int attr_id, bool is_tmp)
int xehash_destroy (THREAD_ENTRY *thread_p, EHID *ehid)
char * xstats_get_statistics_from_server (THREAD_ENTRY *thread_p, OID *class_id, unsigned int timestamp, int *length)
int xstats_update_statistics (THREAD_ENTRY *thread_p, OID *classoid, bool with_fullscan)
int xstats_update_all_statistics (THREAD_ENTRY *thread_p, bool with_fullscan)
DKNPAGES xdisk_get_total_numpages (THREAD_ENTRY *thread_p, VOLID volid)
DKNPAGES xdisk_get_free_numpages (THREAD_ENTRY *thread_p, VOLID volid)
bool xdisk_is_volume_exist (THREAD_ENTRY *thread_p, VOLID volid)
char * xdisk_get_remarks (THREAD_ENTRY *thread_p, VOLID volid)
int disk_get_boot_db_charset (THREAD_ENTRY *thread_p, INT16 volid, INTL_CODESET *db_charset)
char * xdisk_get_fullname (THREAD_ENTRY *thread_p, VOLID volid, char *vol_fullname)
DISK_VOLPURPOSE xdisk_get_purpose (THREAD_ENTRY *thread_p, VOLID volid)
int xdisk_get_purpose_and_space_info (THREAD_ENTRY *thread_p, VOLID volid, DISK_VOLPURPOSE *vol_purpose, DISK_VOLUME_SPACE_INFO *space_info)
int xqfile_get_list_file_page (THREAD_ENTRY *thread_p, QUERY_ID query_id, VOLID volid, PAGEID pageid, char *page_bufp, int *page_sizep)
int xqmgr_prepare_query (THREAD_ENTRY *thrd, compile_context *ctx, xasl_stream *stream)
QFILE_LIST_ID * xqmgr_execute_query (THREAD_ENTRY *thrd, const XASL_ID *xasl_id, QUERY_ID *query_idp, int dbval_cnt, void *data, QUERY_FLAG *flagp, CACHE_TIME *clt_cache_time, CACHE_TIME *srv_cache_time, int query_timeout, xasl_cache_ent **ret_cache_entry_p)
QFILE_LIST_ID * xqmgr_prepare_and_execute_query (THREAD_ENTRY *thrd, char *xasl_stream, int xasl_stream_size, QUERY_ID *query_id, int dbval_cnt, void *data, QUERY_FLAG *flag, int query_timeout)
int xqmgr_end_query (THREAD_ENTRY *thrd, QUERY_ID query_id)
int xqmgr_drop_all_query_plans (THREAD_ENTRY *thread_p)
void xqmgr_dump_query_plans (THREAD_ENTRY *thread_p, FILE *outfp)
void xqmgr_dump_query_cache (THREAD_ENTRY *thread_p, FILE *outfp)
void xperfmon_server_copy_stats (THREAD_ENTRY *thread_p, UINT64 *to_stats)
void xperfmon_server_copy_global_stats (UINT64 *to_stats)
int xcatalog_check_rep_dir (THREAD_ENTRY *thread_p, OID *class_id, OID *rep_dir_p)
int xacl_reload (THREAD_ENTRY *thread_p)
void xacl_dump (THREAD_ENTRY *thread_p, FILE *outfp)
void xlock_dump (THREAD_ENTRY *thread_p, FILE *outfp)
int xlogtb_get_pack_tran_table (THREAD_ENTRY *thread_p, char **buffer_p, int *size_p, int include_query_exec_info)
int xboot_compact_db (THREAD_ENTRY *thread_p, OID *class_oids, int n_classes, int space_to_process, int instance_lock_timeout, int class_lock_timeout, bool delete_old_repr, OID *last_processed_class_oid, OID *last_processed_oid, int *total_objects, int *failed_objects, int *modified_objects, int *big_objects, int *initial_last_repr_id)
int xboot_heap_compact (THREAD_ENTRY *thread_p, OID *class_oid)
int xboot_compact_start (THREAD_ENTRY *thread_p)
int xboot_compact_stop (THREAD_ENTRY *thread_p)
int xlocator_upgrade_instances_domain (THREAD_ENTRY *thread_p, OID *class_oid, int att_id)
int xsession_create_new (THREAD_ENTRY *thread_p, SESSION_ID *id)
int xsession_check_session (THREAD_ENTRY *thread_p, const SESSION_ID id)
int xsession_end_session (THREAD_ENTRY *thread, const SESSION_ID id)
int xsession_set_row_count (THREAD_ENTRY *thread_p, int row_count)
int xsession_get_row_count (THREAD_ENTRY *thread_p, int *row_count)
int xsession_set_cur_insert_id (THREAD_ENTRY *thread_p, const DB_VALUE *value, bool force)
int xsession_get_last_insert_id (THREAD_ENTRY *thread_p, DB_VALUE *value, bool update_last_insert_id)
int xsession_reset_cur_insert_id (THREAD_ENTRY *thread_p)
int xsession_create_prepared_statement (THREAD_ENTRY *thread_p, char *name, char *alias_print, SHA1Hash *sha1, char *info, int info_len)
int xsession_get_prepared_statement (THREAD_ENTRY *thread_p, const char *name, char **info, int *info_len, XASL_ID *xasl_id, xasl_node_header *xasl_header_p)
int xsession_delete_prepared_statement (THREAD_ENTRY *thread_p, const char *name)
int xlogin_user (THREAD_ENTRY *thread_p, const char *username)
int xsession_set_session_variables (THREAD_ENTRY *thread_p, DB_VALUE *values, const int count)
int xsession_get_session_variable (THREAD_ENTRY *thread_p, const DB_VALUE *name, DB_VALUE *value)
int xsession_get_session_variable_no_copy (THREAD_ENTRY *thread_p, const DB_VALUE *name, DB_VALUE **value)
int xsession_drop_session_variables (THREAD_ENTRY *thread_p, DB_VALUE *values, const int count)
void xsession_store_query_entry_info (THREAD_ENTRY *thread_p, QMGR_QUERY_ENTRY *qentry_p)
int xsession_load_query_entry_info (THREAD_ENTRY *thread_p, QMGR_QUERY_ENTRY *qentry_p)
int xsession_remove_query_entry_info (THREAD_ENTRY *thread_p, const QUERY_ID query_id)
int xsession_clear_query_entry_info (THREAD_ENTRY *thread_p, const QUERY_ID query_id)
int xchksum_insert_repl_log_and_demote_table_lock (THREAD_ENTRY *thread_p, REPL_INFO *repl_info, const OID *class_oidp)
bool xlogtb_does_active_user_exist (THREAD_ENTRY *thread_p, const char *user_name)
int xlocator_demote_class_lock (THREAD_ENTRY *thread_p, const OID *class_oid, LOCK lock, LOCK *ex_lock)
bool xtran_should_connection_reset (THREAD_ENTRY *thread_p, bool has_updated)
int xsession_set_tran_auto_commit (THREAD_ENTRY *thread_p, bool auto_commit)
Function Documentation
int disk_get_boot_db_charset (THREAD_ENTRY * thread_p, INT16 volid, INTL_CODESET * db_charset)
Definition at line 5788 of file disk_manager.c.
References assert, ASSERT_ERROR, disk_volume_header::db_charset, disk_get_volheader, NO_ERROR, NULL, PGBUF_LATCH_READ, and pgbuf_unfix_and_init.
Referenced by boot_get_db_charset_from_header().
float log_get_db_compatibility (void)
Referenced by log_initialize_internal().
LOG_LSA* log_get_final_restored_lsa (void)
Referenced by log_is_logged_since_restart().
int log_set_no_logging (void)
Definition at line 951 of file log_manager.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_LOG_THEREARE_PENDING_ACTIONS_MUST_LOG, ER_ONLY_IN_STANDALONE, er_set(), log_Gl, log_No_logging, NO_ERROR, trantable::num_prepared_loose_end_indices, prm_get_bool_value(), PRM_ID_LOG_TRACE_DEBUG, and log_global::trantable.
Referenced by locator_log_force_nologging().
bool logtb_has_updated (THREAD_ENTRY * thread_p)
Definition at line 3109 of file log_tran_table.c.
References LOG_FIND_TDES(), LOG_FIND_THREAD_TRAN_INDEX, LSA_ISNULL(), NULL, and log_tdes::tail_lsa.
Referenced by net_server_request(), slog_checkpoint(), sqmgr_execute_query(), stran_server_abort(), stran_server_abort_internal(), stran_server_commit_internal(), and xtran_server_has_updated().
void xacl_dump (THREAD_ENTRY * thread_p, FILE * outfp)
Referenced by css_notify_ha_log_applier_state(), and sacl_dump().
int xacl_reload (THREAD_ENTRY * thread_p)
Referenced by css_notify_ha_log_applier_state(), and sacl_reload().
VOLID xboot_add_volume_extension (THREAD_ENTRY * thread_p, DBDEF_VOL_EXT_INFO * ext_info)
Definition at line 551 of file boot_sr.c.
References assert, ASSERT_ERROR, dbdef_vol_ext_info::comments, disk_add_volume_extension(), dbdef_vol_ext_info::max_npages, dbdef_vol_ext_info::max_writesize_in_sec, dbdef_vol_ext_info::name, NO_ERROR, NULL_VOLID, dbdef_vol_ext_info::overwrite, dbdef_vol_ext_info::path, and dbdef_vol_ext_info::purpose.
Referenced by boot_add_volume_extension(), and sboot_add_volume_extension().
int xboot_backup (THREAD_ENTRY * thread_p, const char * backup_path, FILEIO_BACKUP_LEVEL backup_level, bool delete_unneeded_logarchives, const char * backup_verbose_file, int num_threads, FILEIO_ZIP_METHOD zip_method, FILEIO_ZIP_LEVEL zip_level, int skip_activelog, int sleep_msecs, bool separate_keys)
Definition at line 3939 of file boot_sr.c.
References logpb_backup(), and boot_dbparm::nvols.
Referenced by boot_backup(), and sboot_backup().
int xboot_check_db_consistency (THREAD_ENTRY * thread_p, int check_flag, OID * oids, int num_oids, BTID * index_btid)
Definition at line 3713 of file boot_sr.c.
References assert, ASSERT_ERROR_AND_SET, boot_check_permanent_volumes(), BTID_IS_NULL, btree_check_all(), btree_repair_prev_link(), catalog_check_consistency(), CHECK_ONLY, CHECKDB_BTREE_CHECK_ALL_BTREES, CHECKDB_CHECK_PREV_LINK, CHECKDB_CT_CHECK_CAT_CONSISTENCY, CHECKDB_FILE_TRACKER_CHECK, CHECKDB_HEAP_CHECK_ALLHEAPS, CHECKDB_LC_CHECK_ALLENTRIES_OF_ALLBTREES, CHECKDB_LC_CHECK_CLASSNAMES, CHECKDB_REPAIR, CHECKDB_REPAIR_PREV_LINK, disk_check(), DISK_ERROR, DISK_INVALID, disk_lock_extend(), disk_unlock_extend(), DISK_VALID, ER_FAILED, file_tracker_check(), heap_check_all_heaps(), i, locator_check_all_entries_of_all_btrees(), locator_check_class_names(), NO_ERROR, NULL, OID_ISNULL, REPAIR_ALL, and xboot_checkdb_table().
Referenced by boot_check_db_consistency(), sboot_check_db_consistency(), and xboot_unregister_client().
DISK_ISVALID xboot_checkdb_table (THREAD_ENTRY * thread_p, int check_flag, OID * oid, BTID * index_btid)
Definition at line 3587 of file boot_sr.c.
References btree_check_by_class_oid(), btree_repair_prev_link(), CHECK_ONLY, CHECKDB_CHECK_PREV_LINK, CHECKDB_REPAIR, CHECKDB_REPAIR_PREV_LINK, DISK_ERROR, DISK_VALID, heap_check_heap_file(), heap_get_class_info(), heap_get_class_record(), heap_scancache_end(), heap_scancache_quick_start_root_hfid(), boot_dbparm::hfid, HFID_IS_NULL, IS_LOCK, LK_GRANTED, LK_UNCOND_LOCK, locator_check_by_class_oid(), lock_object(), lock_unlock_object(), NO_ERROR, NULL, oid_Root_class_oid, PEEK, REPAIR_ALL, S_SUCCESS, and xcallback_console_print().
Referenced by xboot_check_db_consistency().
int xboot_compact_db (THREAD_ENTRY * thread_p, OID * class_oids, int n_classes, int space_to_process, int instance_lock_timeout, int class_lock_timeout, bool delete_old_repr, OID * last_processed_class_oid, OID * last_processed_oid, int * total_objects, int * failed_objects, int * modified_objects, int * big_objects, int * initial_last_repr_id)
Definition at line 5860 of file boot_sr.c.
References boot_compact_db().
Referenced by sboot_compact_db().
int xboot_compact_start (THREAD_ENTRY * thread_p)
Definition at line 5886 of file boot_sr.c.
References boot_compact_start().
Referenced by sboot_compact_start().
int xboot_compact_stop (THREAD_ENTRY * thread_p)
Definition at line 5896 of file boot_sr.c.
References boot_compact_stop().
Referenced by sboot_compact_stop().
VOLID xboot_find_last_permanent (THREAD_ENTRY * thread_p)
Definition at line 377 of file boot_sr.c.
References disk_lock_extend(), disk_unlock_extend(), and boot_dbparm::last_volid.
Referenced by boot_find_last_permanent(), disk_check(), logpb_checkpoint(), and sboot_find_last_permanent().
VOLID xboot_find_last_temp (THREAD_ENTRY * thread_p)
Definition at line 407 of file boot_sr.c.
References disk_lock_extend(), disk_unlock_extend(), and boot_dbparm::temp_last_volid.
Referenced by boot_find_last_temp(), disk_check(), and sboot_find_last_temp().
int xboot_find_number_permanent_volumes (THREAD_ENTRY * thread_p)
Definition at line 341 of file boot_sr.c.
References disk_lock_extend(), disk_unlock_extend(), and boot_dbparm::nvols.
Referenced by boot_find_number_permanent_volumes(), disk_check(), and sboot_find_number_permanent_volumes().
int xboot_find_number_temp_volumes (THREAD_ENTRY * thread_p)
Definition at line 359 of file boot_sr.c.
References disk_lock_extend(), disk_unlock_extend(), boot_dbparm::nvols, and boot_dbparm::temp_nvols.
Referenced by boot_find_number_temp_volumes(), disk_check(), and sboot_find_number_temp_volumes().
const char* xboot_get_server_session_key (void)
Definition at line 3151 of file boot_sr.c.
References boot_Server_session_key.
Referenced by ssession_find_or_create_session().
int xboot_heap_compact (THREAD_ENTRY * thread_p, OID * class_oid)
Definition at line 5876 of file boot_sr.c.
References boot_heap_compact_pages().
Referenced by sboot_heap_compact().
int xboot_initialize_server (const BOOT_CLIENT_CREDENTIAL * client_credential, BOOT_DB_PATH_INFO * db_path_info, bool db_overwrite, const char * file_addmore_vols, volatile DKNPAGES db_npages, PGLENGTH db_desired_pagesize, volatile DKNPAGES xlog_npages, PGLENGTH db_desired_log_page_size, OID * rootclass_oid, HFID * rootclass_hfid, int client_lock_wait, TRAN_ISOLATION client_isolation)
Definition at line 1462 of file boot_sr.c.
References area_init(), ARG_FILE_LINE, assert, ASSERT_ERROR, assert_release, BO_IS_SERVER_RESTARTED, boot_create_all_volumes(), boot_ctrl_c_in_init_server(), boot_Db_full_name, boot_find_root_heap(), BOOT_FORMAT_MAX_LENGTH, boot_remove_all_volumes(), boot_remove_useless_path_separator(), boot_server_all_finalize(), BOOT_SHUTDOWN_EXCEPT_COMMON_MODULES, cfg_add_db(), cfg_find_db_list(), cfg_free_directory(), cfg_maycreate_get_directory_filename(), cfg_read_directory(), cfg_read_directory_ex(), cfg_update_db(), cfg_write_directory(), cfg_write_directory_ex(), cub_dirname_r(), boot_db_path_info::db_comments, boot_db_path_info::db_host, DB_MAX_PATH_LENGTH, boot_client_credential::db_name, boot_db_path_info::db_path, db_set_page_size(), DB_SIZEOF, ER_ALL_FINAL, ER_BO_CANNOT_ACCESS_MESSAGE_CATALOG, ER_BO_CANNOT_CREATE_LINK, ER_BO_CANNOT_CREATE_VOL, ER_BO_CANT_LOAD_SYSPRM, ER_BO_DATABASE_EXISTS, ER_BO_DIRECTORY_DOESNOT_EXIST, ER_BO_FULL_DATABASE_NAME_IS_TOO_LONG, ER_BO_UNABLE_TO_RESTART_SERVER, ER_BO_UNKNOWN_DATABASE, er_clear(), er_errid(), ER_ERROR_SEVERITY, ER_ES_GENERAL, ER_ES_INVALID_PATH, er_get_msglog_filename(), ER_INTERRUPTED, ER_LOC_INIT, er_log_debug, ER_NOTIFICATION_SEVERITY, er_set(), er_set_with_oserror(), er_stack_pop(), er_stack_push(), ER_THREAD_FINAL, ER_TZ_LOAD_ERROR, es_get_type(), ES_NONE, ES_POSIX, fileio_dismount(), fileio_get_base_file_name(), fileio_mount(), cubthread::finalize(), boot_client_credential::get_db_name(), HFID_IS_NULL, database_info::hosts, cubthread::initialize(), cubthread::initialize_thread_entries(), lang_init(), boot_db_path_info::lob_path, LOB_PATH_DEFAULT_PREFIX, LOB_PATH_PREFIX_MAX, database_info::lobpath, LOG_DBTXT_VOLID, log_final(), boot_db_path_info::log_path, database_info::logpath, logpb_check_exist_any_volumes(), logtb_release_tran_index(), MSGCAT_CATALOG_CUBRID, MSGCAT_GENERAL_DATABASE_INIT, msgcat_init(), msgcat_message(), MSGCAT_SET_GENERAL, database_info::name, NO_ERROR, NULL, NULL_TRAN_INDEX, NULL_VOLDES, os_set_signal_handler(), p, db_identifier::pageid, PATH_SEPARATOR, database_info::pathname, pr_area_init(), prm_get_bigint_value(), PRM_ID_DB_VOLUME_SIZE, PRM_ID_LOG_VOLUME_SIZE, rel_bit_platform(), rel_build_number(), rel_build_type(), rel_name(), ROOTCLASS_NAME, boot_dbparm::rootclass_name, boot_dbparm::rootclass_oid, session_states_init(), set_area_init(), db_identifier::slotid, strlen, strncpy_size, SYSPRM_LOAD_ALL, sysprm_load_and_init(), thread_get_thread_entry_info(), tp_init(), tsc_init(), tz_load(), boot_db_path_info::vol_path, db_identifier::volid, and xboot_shutdown_server().
Referenced by boot_initialize_server().
VOLID xboot_peek_last_permanent (THREAD_ENTRY * thread_p)
Definition at line 396 of file boot_sr.c.
References boot_dbparm::last_volid.
int xboot_register_client (THREAD_ENTRY * thread_p, BOOT_CLIENT_CREDENTIAL * client_credential, int client_lock_wait, TRAN_ISOLATION client_isolation, TRAN_STATE * tran_state, BOOT_SERVER_CREDENTIAL * server_credential)
Definition at line 3179 of file boot_sr.c.
References ARG_FILE_LINE, BO_IS_SERVER_RESTARTED, boot_Db_full_name, boot_find_root_heap(), boot_Host_name, boot_Lob_path, BOOT_NORMAL_CLIENT_TYPE, boot_restart_server(), boot_Server_session_key, check_args::check_db_coll, check_args::check_timezone, clientids::client_type, CONN_OPEN, COPY_OID, css_check_ha_server_state_for_client(), css_ha_server_state(), css_notify_ha_log_applier_state(), boot_server_credential::db_charset, DB_CLIENT_TYPE_ADMIN_UTILITY, DB_CLIENT_TYPE_LOG_APPLIER, DB_CLIENT_TYPE_SKIP_VACUUM_ADMIN_CSQL, DB_CLIENT_TYPE_SKIP_VACUUM_CSQL, boot_server_credential::db_full_name, boot_server_credential::db_lang, DB_MAX_IDENTIFIER_LENGTH, clientids::db_user, boot_server_credential::disk_compatibility, ER_BO_CLIENT_CONNECTED, er_log_debug, ER_NOTIFICATION_SEVERITY, er_set(), boot_client_credential::get_db_name(), clientids::get_db_user(), clientids::get_host_name(), clientids::get_program_name(), HA_LOG_APPLIER_STATE_UNREGISTERED, boot_server_credential::ha_server_state, HFID_IS_NULL, boot_server_credential::host_name, intl_identifier_upper(), IO_PAGESIZE, lang_charset(), lang_get_Lang_name(), boot_server_credential::lob_path, boot_server_credential::log_page_size, LOG_PAGESIZE, logtb_assign_tran_index(), logtb_release_tran_index(), NO_ERROR, NULL, NULL_TRAN_INDEX, NULL_TRANID, boot_server_credential::page_size, PATH_SEPARATOR, prm_get_integer_value(), PRM_ID_HA_SERVER_STATE, clientids::process_id, boot_server_credential::process_id, clientids::program_name, rel_disk_compatible(), boot_server_credential::root_class_hfid, boot_server_credential::root_class_oid, boot_dbparm::rootclass_oid, boot_server_credential::server_session_key, SERVER_SESSION_KEY_SIZE, showstmt_scan_init(), strlen, TRAN_ACTIVE, and TRAN_UNACTIVE_UNKNOWN.
Referenced by boot_register_client(), and sboot_register_client().
int xboot_unregister_client (REFPTR(THREAD_ENTRY, thread_p) , int tran_index)
Definition at line 3343 of file boot_sr.c.
References ARG_FILE_LINE, BO_IS_SERVER_RESTARTED, BOOT_NORMAL_CLIENT_TYPE, log_tdes::client, css_conn_entry::client_id, log_tdes::client_id, clientids::client_type, CONN_CLOSING, CONN_OPEN, css_check_ha_server_state_for_client(), css_notify_ha_log_applier_state(), DB_CLIENT_TYPE_LOG_APPLIER, envvar_get(), ER_ALL_FINAL, ER_FATAL_ERROR_SEVERITY, ER_GENERIC_ERROR, er_get_msglog_filename(), er_log_debug, er_set(), clientids::get_db_user(), HA_LOG_APPLIER_STATE_UNREGISTERED, if(), LOG_FIND_TDES(), LOG_FIND_THREAD_TRAN_INDEX, LOG_ISTRAN_ACTIVE, LOG_SET_CURRENT_TRAN_INDEX, logtb_release_tran_index(), NO_ERROR, NULL, NULL_TRAN_INDEX, css_conn_entry::status, xboot_check_db_consistency(), xboot_shutdown_server(), and xtran_server_abort().
Referenced by boot_unregister_client(), and net_server_conn_down().
BTID* xbtree_add_index (THREAD_ENTRY * thread_p, BTID * btid, TP_DOMAIN * key_type, OID * class_oid, int attr_id, int unique_pk, int num_oids, int num_nulls, int num_keys)
Definition at line 5579 of file btree.c.
References assert, ASSERT_ERROR, btree_create_file(), BTREE_CURRENT_REV_LEVEL, btree_get_root_vpid_from_btid(), btree_init_root_header(), BTREE_IS_PRIMARY_KEY, BTREE_IS_UNIQUE, COPY_OID, btree_root_header::creator_mvccid, error(), FREE, btree_node_split_info::index, log_append_undo_data2(), log_sysop_abort(), log_sysop_attach_to_outer(), log_sysop_start(), logtb_get_current_mvccid(), btree_node_header::max_key_len, MVCCID_NULL, btree_node_header::next_vpid, NO_ERROR, btree_root_header::node, btree_node_header::node_level, NULL, NULL_OFFSET, NULL_PAGEID, btree_root_header::num_keys, btree_root_header::num_nulls, btree_root_header::num_oids, OID_ISNULL, OLD_PAGE, btree_root_header::ovfid, PAGE_BTREE, pgbuf_check_page_ptype(), pgbuf_fix, PGBUF_LATCH_WRITE, pgbuf_set_dirty(), PGBUF_UNCONDITIONAL_LATCH, pgbuf_unfix_and_init, btree_node_split_info::pivot, btree_node_header::prev_vpid, btree_root_header::rev_level, btree_root_header::reverse_reserved, btid::root_pageid, RVBT_REMOVE_UNIQUE_STATS, btree_node_header::split_info, btree_root_header::topclass_oid, btree_root_header::unique_pk, vacuum_log_add_dropped_file(), VACUUM_LOG_ADD_DROPPED_FILE_UNDO, btid::vfid, VFID_SET_NULL, and VPID_SET_NULL.
Referenced by btree_add_index(), sbtree_add_index(), and xbtree_load_index().
int xbtree_class_test_unique (THREAD_ENTRY * thread_p, char * buf, int buf_size)
Definition at line 6065 of file btree.c.
References BTREE_SET_UNIQUE_VIOLATION_ERROR, ER_BTREE_UNIQUE_FAILED, NO_ERROR, NULL, or_unpack_btid(), and xbtree_test_unique().
Referenced by btree_class_test_unique(), and sbtree_class_test_unique().
int xbtree_delete_index (THREAD_ENTRY * thread_p, BTID * btid)
Definition at line 5691 of file btree.c.
References ASSERT_ERROR_AND_SET, btree_get_root_header(), er_errid(), ER_FAILED, file_postpone_destroy(), log_append_postpone(), NO_ERROR, NULL, NULL_OFFSET, NULL_PAGEID, OLD_PAGE, btree_root_header::ovfid, PAGE_BTREE, vpid::pageid, pgbuf_check_page_ptype(), pgbuf_fix, PGBUF_LATCH_WRITE, PGBUF_UNCONDITIONAL_LATCH, pgbuf_unfix_and_init, btid::root_pageid, RVBT_REMOVE_UNIQUE_STATS, btree_root_header::unique_pk, vacuum_log_add_dropped_file(), VACUUM_LOG_ADD_DROPPED_FILE_POSTPONE, btid::vfid, VFID_ISNULL, vpid::volid, and vfid::volid.
Referenced by btree_delete_index(), and sbtree_delete_index().
BTREE_SEARCH xbtree_find_multi_uniques (THREAD_ENTRY * thread_p, OID * class_oid, int pruning_type, BTID * btids, DB_VALUE * values, int count, SCAN_OPERATION_TYPE op_type, OID ** oids, int * oids_count)
Definition at line 5848 of file btree.c.
References ARG_FILE_LINE, BTID_COPY, BTREE_ERROR_OCCURRED, BTREE_KEY_FOUND, BTREE_KEY_NOTFOUND, COPY_OID, cubregex::count(), DB_NOT_PARTITIONED_CLASS, DB_PARTITION_CLASS, db_private_alloc, db_private_free_and_init, ER_ERROR_SEVERITY, ER_INVALID_DATA_FOR_PARTITION, er_set(), error(), i, NO_ERROR, NULL, OID_EQ, partition_clear_pruning_context(), partition_init_pruning_context(), partition_load_pruning_context(), partition_prune_unique_btid(), S_UPDATE, and xbtree_find_unique().
Referenced by btree_find_multi_uniques(), and sbtree_find_multi_uniques().
BTREE_SEARCH xbtree_find_unique (THREAD_ENTRY * thread_p, BTID * btid, SCAN_OPERATION_TYPE scan_op_type, DB_VALUE * key, OID * class_oid, OID * oid, bool is_all_class_srch)
Definition at line 23990 of file btree.c.
References assert, ASSERT_ERROR, btree_advance_and_find_key(), BTREE_ERROR_OCCURRED, BTREE_FIND_UNIQUE_HELPER_INITIALIZER, btree_key_find_and_lock_unique(), btree_key_find_unique_version_oid(), BTREE_KEY_FOUND, BTREE_KEY_NOTFOUND, btree_multicol_key_is_null(), btree_search_key_and_apply_functions(), COPY_OID, db_value_is_null(), btree_find_unique_helper::found_object, IS_LOCK, IX_LOCK, LK_GRANTED, LK_UNCOND_LOCK, lock_has_lock_on_object(), btree_find_unique_helper::lock_mode, lock_object(), lock_unlock_object_donot_move_to_non2pl(), logtb_find_current_isolation(), logtb_get_mvcc_snapshot(), btree_find_unique_helper::match_class_oid, mvcc_is_mvcc_disabled_class(), mvcc_satisfies_dirty(), NO_ERROR, NULL, NULL_LOCK, btree_find_unique_helper::oid, OID_ISNULL, oid_Root_class_oid, OID_SET_NULL, S_DELETE, S_LOCK, S_SELECT, S_SELECT_WITH_LOCK, S_UPDATE, btree_find_unique_helper::snapshot, mvcc_snapshot::snapshot_fnc, STATIC_INLINE, tf_is_catalog_class(), btree_find_unique_helper::time_track, TRAN_REP_READ, and X_LOCK.
Referenced by btree_check_foreign_key(), btree_find_unique(), catcls_find_oid_by_class_name(), heap_set_autoincrement_value(), locator_check_foreign_key(), locator_repl_prepare_force(), qexec_oid_of_duplicate_key_update(), qexec_remove_duplicates_for_replace(), sbtree_find_unique_internal(), and xbtree_find_multi_uniques().
BTID* xbtree_load_index (THREAD_ENTRY * thread_p, BTID * btid, const char * bt_name, TP_DOMAIN * key_type, OID * class_oids, int n_classes, int n_attrs, int * attr_ids, int * attrs_prefix_length, HFID * hfids, int unique_pk, int not_null_flag, OID * fk_refcls_oid, BTID * fk_refcls_pk_btid, const char * fk_name, char * pred_stream, int pred_stream_size, char * expr_stream, int expr_steram_size, int func_col_id, int func_attr_index_start)
Initialize the fields of loading argument structures
Definition at line 716 of file btree_load.c.
References _er_log_debug(), recdes::area_size, ARG_FILE_LINE, assert, ASSERT_ERROR, sort_args::attr_ids, function_index_info::attr_index_start, sort_args::attr_info, pred_expr_with_context::attrids_pred, sort_args::attrinfo_inited, sort_args::attrs_prefix_length, load_args::bt_name, sort_args::btid, load_args::btid, BTID_INITIALIZER, BTID_IS_NULL, BTID_SET_NULL, btree_build_nleafs(), btree_construct_leafs(), btree_create_file(), BTREE_CURRENT_REV_LEVEL, btree_generate_prefix_domain(), btree_get_root_vpid_from_btid(), btree_index_sort(), BTREE_IS_PRIMARY_KEY, BTREE_IS_UNIQUE, btree_load_check_fk(), BTREE_MAX_KEYLEN_INPAGE, BTREE_MAX_OIDLEN_INPAGE, btree_save_last_leafrec(), BTREE_SET_CREATED_OVERFLOW_KEY_NOTIFICATION, btree_verify_tree(), func_pred::cache_attrinfo, pred_expr_with_context::cache_pred, sort_args::class_ids, function_index_info::col_id, btid_int::copy_buf, btid_int::copy_buf_len, COPY_OID, sort_args::cur_class, sort_args::cur_oid, load_args::curr_non_del_obj_count, load_args::current_key, recdes::data, db_make_null(), DB_PAGESIZE, db_private_free_and_init, DB_TYPE_NULL, ER_BTREE_LOAD_FAILED, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), eval_fnc(), function_index_info::expr, function_index_info::expr_stream, function_index_info::expr_stream_size, vfid::fileid, sort_args::filter, sort_args::filter_eval_func, sort_args::fk_name, sort_args::fk_refcls_oid, sort_args::fk_refcls_pk_btid, free_xasl_unpack_info(), sort_args::func_index_info, mvcctable::get_global_oldest_visible(), log_tdes::has_deadlock_priority, heap_attrinfo_end(), heap_attrinfo_start(), heap_scancache_end(), heap_scancache_start(), HFID_IS_NULL, sort_args::hfids, sort_args::hfscan_cache, sort_args::key_type, btid_int::key_type, load_args::leaf, load_args::leaf_nleaf_recdes, recdes::length, list_clear(), log_append_undo_data2(), LOG_FIND_CURRENT_TDES(), log_Gl, log_sysop_abort(), log_sysop_attach_to_outer(), log_sysop_start(), logpb_force_flush_pages(), logtb_delete_global_unique_stats(), log_global::mvcc_table, sort_args::n_attrs, sort_args::n_classes, load_args::n_keys, sort_args::n_nulls, sort_args::n_oids, load_args::nleaf, NO_ERROR, btid_int::nonleaf_key_type, sort_args::not_null_flag, NULL, NULL_OFFSET, NULL_PAGEID, pred_expr_with_context::num_attrs_pred, OID_ISNULL, OID_SET_NULL, sort_args::oldest_visible_mvccid, os_free_and_init, os_malloc, load_args::out_recdes, load_args::ovf, load_args::ovf_recdes, btid_int::ovfid, db_identifier::pageid, btid_int::part_key_desc, pgbuf_unfix_and_init, btree_page::pgptr, load_args::pop_list, pr_clear_value(), pred_expr_with_context::pred, prm_get_bool_value(), PRM_ID_LOG_BTREE_OPS, load_args::push_list, qexec_clear_func_pred(), qexec_clear_pred_context(), REC_HOME, btid_int::rev_level, btid::root_pageid, RVBT_REMOVE_UNIQUE_STATS, sort_args::scancache_inited, db_identifier::slotid, stx_map_stream_to_filter_pred(), stx_map_stream_to_func_pred(), btid_int::sys_btid, btid_int::topclass_oid, recdes::type, sort_args::unique_pk, btid_int::unique_pk, pred_expr_with_context::unpack_info, vacuum_log_add_dropped_file(), VACUUM_LOG_ADD_DROPPED_FILE_UNDO, btid::vfid, VFID_ISNULL, VFID_SET_NULL, vfid::volid, db_identifier::volid, btree_page::vpid, VPID_SET_NULL, and xbtree_add_index().
Referenced by btree_load_index(), and sbtree_load_index().
BTID* xbtree_load_online_index (THREAD_ENTRY * thread_p, BTID * btid, const char * bt_name, TP_DOMAIN * key_type, OID * class_oids, int n_classes, int n_attrs, int * attr_ids, int * attrs_prefix_length, HFID * hfids, int unique_pk, int not_null_flag, OID * fk_refcls_oid, BTID * fk_refcls_pk_btid, const char * fk_name, char * pred_stream, int pred_stream_size, char * expr_stream, int expr_steram_size, int func_col_id, int func_attr_index_start, int ib_thread_count)
Definition at line 4438 of file btree_load.c.
References _er_log_debug(), ARG_FILE_LINE, assert, ASSERT_ERROR, function_index_info::attr_index_start, sort_args::attr_info, pred_expr_with_context::attrids_pred, sort_args::btid, BTID_AS_ARGS, BTREE_CURRENT_REV_LEVEL, btree_generate_prefix_domain(), BTREE_IS_PRIMARY_KEY, BTREE_IS_UNIQUE, btree_online_index_check_unique_constraint(), func_pred::cache_attrinfo, pred_expr_with_context::cache_pred, function_index_info::col_id, btid_int::copy_buf, btid_int::copy_buf_len, COPY_OID, css_is_shutdowning_server(), sort_args::cur_class, db_private_free_and_init, DB_TYPE_NULL, ER_BTREE_LOAD_FAILED, er_clear(), er_errid(), ER_ERROR_SEVERITY, ER_INTERRUPTED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), function_index_info::expr, function_index_info::expr_stream, function_index_info::expr_stream_size, vfid::fileid, free_xasl_unpack_info(), sort_args::func_index_info, log_tdes::has_deadlock_priority, heap_attrinfo_end(), heap_attrinfo_start(), heap_get_btid_from_index_name(), heap_scancache_end(), heap_scancache_start(), IX_LOCK, sort_args::key_type, btid_int::key_type, LK_GRANTED, LK_INFINITE_WAIT, LK_NOTGRANTED_DUE_ERROR, LK_NOTGRANTED_DUE_TIMEOUT, LK_UNCOND_LOCK, lock_demote_class_lock(), lock_object(), LOG_FIND_CURRENT_TDES(), logpb_force_flush_pages(), logtb_get_mvcc_snapshot(), logtb_invalidate_snapshot_data(), logtb_set_check_interrupt(), logtb_set_tran_index_interrupt(), heap_scancache::mvcc_snapshot, sort_args::n_attrs, sort_args::n_classes, NO_ERROR, btid_int::nonleaf_key_type, NULL, pred_expr_with_context::num_attrs_pred, OID_AS_ARGS, oid_Root_class_oid, online_index_builder(), btid_int::ovfid, btid_int::part_key_desc, prm_get_bool_value(), PRM_ID_LOG_BTREE_OPS, qexec_clear_func_pred(), qexec_clear_pred_context(), btid_int::rev_level, btid::root_pageid, SCH_M_LOCK, stx_map_stream_to_filter_pred(), stx_map_stream_to_func_pred(), btid_int::sys_btid, btid_int::topclass_oid, sort_args::unique_pk, btid_int::unique_pk, pred_expr_with_context::unpack_info, btid::vfid, VFID_SET_NULL, vfid::volid, and xlogtb_reset_wait_msecs().
Referenced by btree_load_index(), and sbtree_load_index().
int xcatalog_check_rep_dir (THREAD_ENTRY * thread_p, OID * class_id, OID * rep_dir_p)
Definition at line 3664 of file system_catalog.c.
References recdes::area_size, ARG_FILE_LINE, assert, ASSERT_ERROR_AND_SET, catalog_add_representation(), catalog_get_representation_record_after_search(), ER_CT_INVALID_CLASSID, er_errid(), ER_ERROR_SEVERITY, ER_FAILED, ER_HEAP_NODATA_NEWADDRESS, er_set(), heap_scancache_end(), heap_scancache_quick_start_root_hfid(), NO_ERROR, NULL, NULL_CHN, NULL_PAGEID, NULL_SLOTID, NULL_VOLID, OID_ISNULL, OID_ISTEMP, OID_SET_NULL, or_class_rep_dir(), orc_diskrep_from_record(), orc_free_diskrep(), db_identifier::pageid, PEEK, PGBUF_LATCH_WRITE, pgbuf_unfix_and_init, S_SUCCESS, db_identifier::slotid, and db_identifier::volid.
Referenced by catalog_check_rep_dir(), and sct_check_rep_dir().
int xchksum_insert_repl_log_and_demote_table_lock (THREAD_ENTRY * thread_p, REPL_INFO * repl_info, const OID * class_oidp)
Definition at line 12560 of file locator_sr.c.
References ARG_FILE_LINE, assert, ASSERT_ERROR, ER_FATAL_ERROR_SEVERITY, ER_LOG_UNKNOWN_TRANINDEX, er_set(), error(), IS_LOCK, lock_demote_read_class_lock_for_checksumdb(), lock_get_object_lock(), log_append_repl_info(), LOG_FIND_CURRENT_TDES(), LOG_FIND_THREAD_TRAN_INDEX, log_sysop_abort(), log_sysop_commit(), log_sysop_start(), NO_ERROR, NULL, oid_Root_class_oid, log_tdes::tran_index, and xrepl_set_info().
Referenced by chksum_insert_repl_log_and_demote_table_lock(), and schksum_insert_repl_log_and_demote_table_lock().
DKNPAGES xdisk_get_free_numpages (THREAD_ENTRY * thread_p, VOLID volid)
Definition at line 5659 of file disk_manager.c.
References assert, DISK_SECTS_NPAGES, LOG_MAX_DBVOLID, disk_cache_volinfo::nsect_free, NULL, disk_cache::nvols_temp, and disk_cache::vols.
Referenced by disk_get_free_numpages(), and sdk_freepgs().
char* xdisk_get_fullname (THREAD_ENTRY * thread_p, VOLID volid, char * vol_fullname)
Definition at line 5723 of file disk_manager.c.
References ARG_FILE_LINE, ASSERT_ERROR, DB_MAX_PATH_LENGTH, disk_get_volheader, disk_verify_volume_header(), disk_vhdr_get_vol_fullname(), ER_ERROR_SEVERITY, ER_OBJ_INVALID_ARGUMENTS, er_set(), NO_ERROR, NULL, PGBUF_LATCH_READ, and pgbuf_unfix_and_init.
Referenced by boot_mount(), disk_get_fullname(), log_recreate(), and sdk_vlabel().
DISK_VOLPURPOSE xdisk_get_purpose (THREAD_ENTRY * thread_p, VOLID volid)
Definition at line 5516 of file disk_manager.c.
References assert, DB_PERMANENT_DATA_PURPOSE, disk_get_volpurpose(), disk_is_valid_volid(), DISK_UNKNOWN_PURPOSE, LOG_DBFIRST_VOLID, and NULL.
Referenced by logpb_check_and_reset_temp_lsa(), and pgbuf_is_temporary_volume().
int xdisk_get_purpose_and_space_info (THREAD_ENTRY * thread_p, VOLID volid, DISK_VOLPURPOSE * vol_purpose, DISK_VOLUME_SPACE_INFO * space_info)
Definition at line 5552 of file disk_manager.c.
References assert, ASSERT_ERROR, disk_get_volheader, LOG_MAX_DBVOLID, disk_volume_space_info::n_free_sects, disk_volume_space_info::n_max_sects, disk_volume_space_info::n_total_sects, NO_ERROR, disk_cache_volinfo::nsect_free, disk_volume_header::nsect_max, disk_volume_header::nsect_total, NULL, NULL_VOLID, disk_cache::nvols_temp, PGBUF_LATCH_READ, pgbuf_unfix_and_init, disk_cache_volinfo::purpose, disk_volume_header::volid, and disk_cache::vols.
Referenced by log_recreate().
char* xdisk_get_remarks (THREAD_ENTRY * thread_p, VOLID volid)
Definition at line 5758 of file disk_manager.c.
References ASSERT_ERROR, disk_get_volheader, disk_vhdr_get_vol_remarks(), NO_ERROR, NULL, PGBUF_LATCH_READ, pgbuf_unfix_and_init, and strlen.
Referenced by disk_get_remarks(), and sdk_remarks().
DKNPAGES xdisk_get_total_numpages (THREAD_ENTRY * thread_p, VOLID volid)
Definition at line 5629 of file disk_manager.c.
References ASSERT_ERROR, disk_get_volheader, DISK_SECTS_NPAGES, NO_ERROR, disk_volume_header::nsect_total, PGBUF_LATCH_READ, and pgbuf_unfix.
Referenced by disk_get_total_numpages(), fileio_backup_volume(), logpb_copy_volume(), sdk_totalpgs(), and xboot_emergency_patch().
bool xdisk_is_volume_exist (THREAD_ENTRY * thread_p, VOLID volid)
Definition at line 5675 of file disk_manager.c.
References disk_check_volume_exist(), disk_check_vol_info::exists, fileio_map_mounted(), disk_volume_header::volid, and disk_check_vol_info::volid.
Referenced by disk_volume_header_start_scan().
EHID* xehash_create (THREAD_ENTRY * thread_p, EHID * ehid, DB_TYPE key_type, int exp_num_entries, OID * class_oid, int attr_id, bool is_tmp)
Definition at line 864 of file extendible_hash.c.
References ehash_create_helper().
Referenced by boot_create_all_volumes(), catalog_create(), and qexec_init_upddel_ehash_files().
int xehash_destroy (THREAD_ENTRY * thread_p, EHID * ehid)
Definition at line 1253 of file extendible_hash.c.
References assert_release, ehash_dir_header::bucket_file, ehash_fix_ehid_page(), ER_FAILED, file_destroy(), log_sysop_commit(), log_sysop_start(), NO_ERROR, NULL, PGBUF_LATCH_WRITE, pgbuf_unfix, and ehid::vfid.
Referenced by qexec_destroy_upddel_ehash_files(), and qexec_init_upddel_ehash_files().
int xfile_apply_tde_to_class_files (THREAD_ENTRY * thread_p, const OID * class_oid)
Definition at line 11503 of file file_manager.c.
References assert, ASSERT_ERROR_AND_SET, or_index::btid, btree_get_root_header(), ER_FAILED, file_apply_tde_algorithm(), heap_classrepr_free_and_init, heap_classrepr_get(), heap_get_class_info(), heap_get_class_tde_algorithm(), heap_ovf_find_vfid(), HFID_INITIALIZER, i, or_classrep::indexes, or_classrep::n_indexes, NO_ERROR, NULL, NULL_REPRID, OID_ISNULL, OLD_PAGE, btree_root_header::ovfid, PAGE_BTREE, vpid::pageid, pgbuf_check_page_ptype(), pgbuf_fix, PGBUF_LATCH_WRITE, PGBUF_UNCONDITIONAL_LATCH, pgbuf_unfix_and_init, btid::root_pageid, TDE_ALGORITHM_NONE, hfid::vfid, btid::vfid, VFID_ISNULL, vpid::volid, and vfid::volid.
Referenced by file_apply_tde_to_class_files(), and sfile_apply_tde_to_class_files().
int xheap_create (THREAD_ENTRY * thread_p, HFID * hfid, const OID * class_oid, bool reuse_oid)
Definition at line 5772 of file heap_file.c.
References heap_create_internal().
Referenced by boot_create_all_volumes(), heap_create(), and shf_create().
int xheap_destroy (THREAD_ENTRY * thread_p, const HFID * hfid, const OID * class_oid)
Definition at line 5786 of file heap_file.c.
References file_postpone_destroy(), heap_ovf_find_vfid(), heap_stats_del_bestspace_by_hfid(), NO_ERROR, NULL, log_data_addr::offset, PGBUF_UNCONDITIONAL_LATCH, log_data_addr::pgptr, vacuum_log_add_dropped_file(), VACUUM_LOG_ADD_DROPPED_FILE_POSTPONE, log_data_addr::vfid, and hfid::vfid.
Referenced by heap_create(), shf_destroy(), and xheap_destroy_newly_created().
int xheap_destroy_newly_created (THREAD_ENTRY * thread_p, const HFID * hfid, const OID * class_oid)
Definition at line 5818 of file heap_file.c.
References ASSERT_ERROR, file_get_type(), FILE_HEAP_REUSE_SLOTS, file_postpone_destroy(), heap_ovf_find_vfid(), heap_stats_del_bestspace_by_hfid(), log_append_postpone(), LOG_DATA_ADDR_INITIALIZER, NO_ERROR, NULL, PGBUF_UNCONDITIONAL_LATCH, RVHF_MARK_DELETED, vacuum_log_add_dropped_file(), VACUUM_LOG_ADD_DROPPED_FILE_POSTPONE, hfid::vfid, and xheap_destroy().
Referenced by heap_destroy_newly_created(), and shf_destroy_when_new().
int xlocator_assign_oid (THREAD_ENTRY * thread_p, const HFID * hfid, OID * perm_oid, int expected_length, OID * class_oid, const char * classname)
Definition at line 2044 of file locator_sr.c.
References assert, ER_FAILED, heap_assign_address(), locator_permoid_class_name(), NO_ERROR, and NULL.
Referenced by locator_assign_oid(), slocator_assign_oid(), and xlocator_assign_oid_batch().
int xlocator_assign_oid_batch (THREAD_ENTRY * thread_p, LC_OIDSET * oidset)
Definition at line 11512 of file locator_sr.c.
References catalog_free_class_info_and_init, catalog_get_class_info(), catalog_update_class_info(), cls_info::ci_hfid, cls_info::ci_tot_objects, lc_class_oidset::class_oid, lc_oidset::classes, error(), lc_oidmap::est_size, vfid::fileid, lc_class_oidset::hfid, log_sysop_abort(), log_sysop_attach_to_outer(), log_sysop_start(), lc_oidmap::next, lc_class_oidset::next, NO_ERROR, NULL, locator_classname_action::oid, lc_oidmap::oid, lc_class_oidset::oids, hfid::vfid, vfid::volid, and xlocator_assign_oid().
Referenced by locator_assign_oid_batch(), and slocator_assign_oid_batch().
int xlocator_check_fk_validity (THREAD_ENTRY * thread_p, OID * cls_oid, HFID * hfid, TP_DOMAIN * key_type, int n_attrs, int * attr_ids, OID * pk_cls_oid, BTID * pk_btid, char * fk_name)
Definition at line 11689 of file locator_sr.c.
References btree_check_foreign_key(), COPY, recdes::data, db_make_null(), DBVAL_BUFSIZE, er_errid(), ER_FAILED, heap_attrinfo_end(), heap_attrinfo_generate_key(), heap_attrinfo_read_dbvalues(), heap_attrinfo_start(), heap_next(), heap_scancache_end(), heap_scancache_start(), logtb_get_mvcc_snapshot(), MAX_ALIGNMENT, NO_ERROR, NULL, locator_classname_action::oid, OID_SET_NULL, pr_clear_value(), PTR_ALIGN, S_SUCCESS, hfid::vfid, vfid::volid, and db_identifier::volid.
Referenced by locator_check_fk_validity(), and slocator_check_fk_validity().
LC_FIND_CLASSNAME xlocator_delete_class_name (THREAD_ENTRY * thread_p, const char * classname)
Definition at line 755 of file locator_sr.c.
References locator_classname_action::action, ARG_FILE_LINE, assert, COPY_OID, csect_enter, csect_exit, CSECT_LOCATOR_SR_CLASSNAME_TABLE, locator_classname_entry::e_current, locator_classname_entry::e_tran_index, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), INF_WAIT, LC_CLASSNAME_DELETED, LC_CLASSNAME_DELETED_RENAME, LC_CLASSNAME_ERROR, LC_CLASSNAME_EXIST, LC_CLASSNAME_RESERVED, LC_CLASSNAME_RESERVED_RENAME, LK_GRANTED, LK_UNCOND_LOCK, locator_incr_num_transient_classnames(), locator_is_exist_class_name_entry(), lock_object(), lock_unlock_object(), LOG_FIND_THREAD_TRAN_INDEX, LSA_ISNULL(), LSA_SET_NULL(), mht_get(), NO_ERROR, NULL, NULL_TRAN_INDEX, locator_classname_action::oid, oid_Root_class_oid, locator_classname_action::prev, locator_classname_action::savep_lsa, SCH_M_LOCK, and strlen.
Referenced by locator_delete_class_name(), locator_delete_force_internal(), slocator_delete_class_name(), and xlocator_rename_class_name().
int xlocator_demote_class_lock (THREAD_ENTRY * thread_p, const OID * class_oid, LOCK lock, LOCK * ex_lock)
Definition at line 13706 of file locator_sr.c.
References lock_demote_class_lock().
Referenced by slocator_demote_class_lock().
int xlocator_does_exist (THREAD_ENTRY * thread_p, OID * oid, int chn, LOCK lock, LC_FETCH_VERSION_TYPE fetch_version_type, OID * class_oid, int class_chn, int need_fetching, int prefetching, LC_COPYAREA ** fetch_area)
Definition at line 3891 of file locator_sr.c.
References ASSERT_ERROR, DISK_VALID, ER_FAILED, heap_does_exist(), HEAP_ISVALID_OID, heap_scancache_end(), heap_scancache_quick_start(), LC_DOESNOT_EXIST, LC_ERROR, LC_EXIST, locator_decide_operation_type(), locator_get_object(), lock_unlock_object(), NO_ERROR, NULL, NULL_CHN, NULL_LOCK, OID_SET_NULL, PEEK, S_ERROR, S_SUCCESS, and xlocator_fetch().
Referenced by locator_does_exist(), and slocator_does_exist().
int xlocator_fetch (THREAD_ENTRY * thrd, OID * oid, int chn, LOCK lock, LC_FETCH_VERSION_TYPE fetch_version_type, LC_FETCH_VERSION_TYPE initial_fetch_version_type, OID * class_oid, int class_chn, int prefetching, LC_COPYAREA ** fetch_area)
Definition at line 2375 of file locator_sr.c.
References locator_return_nxobj::area_offset, locator_return_nxobj::area_scancache, ARG_FILE_LINE, assert, locator_return_nxobj::comm_area, DB_ALIGN, DB_PAGESIZE, er_errid(), ER_FAILED, ER_HEAP_UNKNOWN_OBJECT, er_set(), ER_WARNING_SEVERITY, error(), heap_get_class_oid(), heap_prefetch(), heap_scancache_end(), heap_scancache_start(), LC_FETCH_CURRENT_VERSION, LC_FETCH_CURRENT_VERSION_NO_CHECK, LC_FETCH_DIRTY_VERSION, LC_FETCH_IS_MVCC_VERSION_NEEDED, LC_FETCH_MVCC_VERSION, LC_MANYOBJS_PTR_IN_COPYAREA, LC_NEXT_ONEOBJ_PTR_IN_COPYAREA, LC_RECDES_IN_COPYAREA, LC_START_ONEOBJ_PTR_IN_COPYAREA, recdes::length, lc_copy_area::length, locator_allocate_copy_area_by_length(), locator_decide_operation_type(), locator_free_copy_area(), locator_lock_and_return_object(), locator_notify_decache(), lock_get_object_lock(), lock_notify_isolation_incons(), lock_unlock_object(), lock_unlock_object_donot_move_to_non2pl(), logtb_get_mvcc_snapshot(), MAX_ALIGNMENT, locator_return_nxobj::mobjs, lc_copyarea_desc::mobjs, mvcc_is_mvcc_disabled_class(), mvcc_satisfies_dirty(), NO_ERROR, NULL, NULL_LOCK, lc_copyarea_manyobjs::num_objs, locator_return_nxobj::obj, lc_copyarea_desc::obj, lc_copyarea_desc::offset, locator_classname_action::oid, OID_EQ, OID_IS_ROOTOID, OID_ISNULL, oid_Root_class_oid, OID_SET_NULL, db_identifier::pageid, locator_return_nxobj::ptr_scancache, locator_return_nxobj::recdes, lc_copyarea_desc::recdes, S_DOESNT_EXIST, S_DOESNT_FIT, S_ERROR, S_LOCK, S_SELECT, S_SELECT_WITH_LOCK, S_SNAPSHOT_NOT_SATISFIED, S_SUCCESS, SIX_LOCK, db_identifier::slotid, mvcc_snapshot::snapshot_fnc, db_identifier::volid, and X_LOCK.
Referenced by locator_fetch(), slocator_fetch(), xlocator_does_exist(), and xlocator_get_class().
int xlocator_fetch_all (THREAD_ENTRY * thread_p, const HFID * hfid, LOCK * lock, LC_FETCH_VERSION_TYPE fetch_type, OID * class_oid, int * nobjects, int * nfetched, OID * last_oid, LC_COPYAREA ** fetch_area)
Definition at line 2773 of file locator_sr.c.
References recdes::area_size, assert, lc_copyarea_oneobj::class_oid, COPY, COPY_OID, recdes::data, DB_ALIGN, DB_INT32_MAX, DB_PAGESIZE, er_errid(), ER_FAILED, error(), lc_copyarea_oneobj::flag, heap_estimate_num_objects(), heap_next(), heap_scancache_end(), heap_scancache_end_when_scan_will_resume(), heap_scancache_start(), lc_copyarea_oneobj::hfid, LC_FETCH, LC_FETCH_CURRENT_VERSION, LC_FETCH_DIRTY_VERSION, LC_FETCH_MVCC_VERSION, LC_MANYOBJS_PTR_IN_COPYAREA, LC_NEXT_ONEOBJ_PTR_IN_COPYAREA, LC_PRIOR_ONEOBJ_PTR_IN_COPYAREA, LC_RECDES_IN_COPYAREA, LC_START_ONEOBJ_PTR_IN_COPYAREA, recdes::length, lc_copyarea_oneobj::length, LK_GRANTED, LK_UNCOND_LOCK, locator_allocate_copy_area_by_length(), locator_free_copy_area(), locator_notify_decache(), lock_notify_isolation_incons(), lock_object(), lock_unlock_object(), logtb_get_mvcc_snapshot(), MAX_ALIGNMENT, lc_copyarea_desc::mobjs, mvcc_satisfies_dirty(), NO_ERROR, NULL, NULL_HFID, NULL_LOCK, NULL_PAGEID, NULL_SLOTID, lc_copyarea_manyobjs::num_objs, lc_copyarea_desc::obj, lc_copyarea_oneobj::offset, lc_copyarea_desc::offset, locator_classname_action::oid, lc_copyarea_oneobj::oid, OID_ISNULL, oid_Root_class_oid, OID_SET_NULL, lc_copyarea_oneobj::operation, db_identifier::pageid, lc_copyarea_desc::recdes, S_DOESNT_FIT, S_END, S_ERROR, S_SUCCESS, db_identifier::slotid, mvcc_snapshot::snapshot_fnc, hfid::vfid, vfid::volid, and db_identifier::volid.
Referenced by locator_fetch_all(), and slocator_fetch_all().
int xlocator_fetch_all_reference_lockset (THREAD_ENTRY * thread_p, OID * oid, int chn, OID * class_oid, int class_chn, LOCK lock, int quit_on_errors, int prune_level, LC_LOCKSET ** lockset, LC_COPYAREA ** fetch_area)
Definition at line 3813 of file locator_sr.c.
References ER_FAILED, i, IS_LOCK, IX_LOCK, locator_all_reference_lockset(), NULL, NULL_CHN, OID_EQ, S_LOCK, and xlocator_fetch_lockset().
Referenced by locator_fetch_all_reference_lockset(), and slocator_fetch_all_reference_lockset().
int xlocator_fetch_lockhint_classes (THREAD_ENTRY * thread_p, LC_LOCKHINT * lockhint, LC_COPYAREA ** fetch_area)
Definition at line 11291 of file locator_sr.c.
References locator_return_nxobj::area_offset, locator_return_nxobj::area_scancache, lc_lockhint_class::chn, lc_lock_hint::classes, locator_return_nxobj::comm_area, DB_ALIGN, DB_PAGESIZE, ER_FAILED, heap_scancache_end(), heap_scancache_start(), i, LC_MANYOBJS_PTR_IN_COPYAREA, LC_RECDES_IN_COPYAREA, LC_START_ONEOBJ_PTR_IN_COPYAREA, recdes::length, lc_copy_area::length, LK_GRANTED, LK_UNCOND_LOCK, locator_allocate_copy_area_by_length(), locator_free_copy_area(), locator_lock_and_return_object(), locator_notify_decache(), lc_lockhint_class::lock, lock_classes_lock_hint(), lock_notify_isolation_incons(), lock_object(), lock_unlock_classes_lock_hint(), MAX_ALIGNMENT, locator_return_nxobj::mobjs, lc_copyarea_desc::mobjs, NO_ERROR, NULL, NULL_LOCK, lc_lock_hint::num_classes, lc_lock_hint::num_classes_processed, lc_copyarea_manyobjs::num_objs, locator_return_nxobj::obj, lc_copyarea_desc::obj, lc_copyarea_desc::offset, lc_lockhint_class::oid, OID_ISNULL, OID_ISTEMP, oid_Root_class_oid, OID_SET_NULL, locator_return_nxobj::ptr_scancache, lc_lock_hint::quit_on_errors, locator_return_nxobj::recdes, lc_copyarea_desc::recdes, S_DOESNT_EXIST, S_DOESNT_FIT, S_ERROR, S_SELECT, and S_SUCCESS.
Referenced by locator_fetch_lockhint_classes(), slocator_fetch_lockhint_classes(), and xlocator_find_lockhint_class_oids().
int xlocator_fetch_lockset (THREAD_ENTRY * thread_p, LC_LOCKSET * lockset, LC_COPYAREA ** fetch_area)
Definition at line 3047 of file locator_sr.c.
References locator_return_nxobj::area_offset, locator_return_nxobj::area_scancache, lc_lockset_classof::chn, lc_lock_set::classes, locator_return_nxobj::comm_area, DB_ALIGN, DB_PAGESIZE, er_errid(), ER_FAILED, error(), heap_scancache_end(), heap_scancache_start(), i, LC_MANYOBJS_PTR_IN_COPYAREA, LC_RECDES_IN_COPYAREA, LC_START_ONEOBJ_PTR_IN_COPYAREA, recdes::length, lc_copy_area::length, locator_allocate_copy_area_by_length(), locator_find_lockset_missing_class_oids(), locator_free_copy_area(), locator_lock_and_return_object(), locator_notify_decache(), lock_notify_isolation_incons(), lock_unlock_objects_lock_set(), logtb_get_mvcc_snapshot(), MAX_ALIGNMENT, locator_return_nxobj::mobjs, lc_copyarea_desc::mobjs, heap_scancache::mvcc_snapshot, NO_ERROR, NULL, lc_lock_set::num_classes_of_reqobjs, lc_lock_set::num_classes_of_reqobjs_processed, lc_copyarea_manyobjs::num_objs, lc_lock_set::num_reqobjs, lc_lock_set::num_reqobjs_processed, locator_return_nxobj::obj, lc_copyarea_desc::obj, lc_lock_set::objects, lc_copyarea_desc::offset, locator_classname_action::oid, OID_EQ, OID_IS_ROOTOID, OID_ISNULL, OID_ISTEMP, oid_Root_class_oid, OID_SET_NULL, locator_return_nxobj::ptr_scancache, lc_lock_set::quit_on_errors, locator_return_nxobj::recdes, lc_copyarea_desc::recdes, lc_lock_set::reqobj_class_lock, lc_lock_set::reqobj_inst_lock, S_DOESNT_EXIST, S_DOESNT_FIT, S_ERROR, S_SELECT, and S_SUCCESS.
Referenced by locator_fetch_lockset(), slocator_fetch_lockset(), and xlocator_fetch_all_reference_lockset().
LC_FIND_CLASSNAME xlocator_find_class_oid (THREAD_ENTRY * thread_p, const char * classname, OID * class_oid, LOCK lock)
Definition at line 1033 of file locator_sr.c.
References locator_classname_action::action, assert, COPY_OID, csect_enter_as_reader, csect_exit, CSECT_LOCATOR_SR_CLASSNAME_TABLE, locator_classname_entry::e_current, locator_classname_entry::e_tran_index, INF_WAIT, IS_LOCK, LC_CLASSNAME_DELETED, LC_CLASSNAME_DELETED_RENAME, LC_CLASSNAME_ERROR, LC_CLASSNAME_EXIST, LK_GRANTED, LK_UNCOND_LOCK, locator_is_exist_class_name_entry(), lock_object(), lock_unlock_object(), LOG_FIND_THREAD_TRAN_INDEX, mht_get(), NO_ERROR, NULL, NULL_LOCK, locator_classname_action::oid, OID_ISNULL, oid_Root_class_oid, and OID_SET_NULL.
Referenced by btree_index_start_scan(), catalog_get_cardinality_by_name(), catcls_find_and_set_cached_class_oid(), catcls_find_class_oid_by_class_name(), heap_header_capacity_start_scan(), heap_set_autoincrement_value(), cubload::server_class_installer::locate_class(), locator_find_class_oid(), logtb_tran_prepare_count_optim_classes(), and slocator_find_class_oid().
LC_FIND_CLASSNAME xlocator_find_lockhint_class_oids (THREAD_ENTRY * thread_p, int num_classes, const char ** many_classnames, LOCK * many_locks, int * many_need_subclasses, LC_PREFETCH_FLAGS * many_flags, OID * guessed_class_oids, int * guessed_class_chns, bool quit_on_errors, LC_LOCKHINT ** hlock, LC_COPYAREA ** fetch_area)
Definition at line 11017 of file locator_sr.c.
References locator_classname_action::action, ARG_FILE_LINE, assert, CHN_UNKNOWN_ATCLIENT, COPY_OID, csect_check_own, csect_enter_as_reader, csect_exit, CSECT_LOCATOR_SR_CLASSNAME_TABLE, locator_classname_entry::e_current, locator_classname_entry::e_tran_index, ER_LC_UNKNOWN_CLASSNAME, er_set(), ER_WARNING_SEVERITY, i, INF_WAIT, IS_LOCK, LC_CLASSNAME_DELETED, LC_CLASSNAME_DELETED_RENAME, LC_CLASSNAME_ERROR, LC_CLASSNAME_EXIST, LC_PREF_FLAG_LOCK, LK_GRANTED, LK_UNCOND_LOCK, locator_allocate_lockhint(), locator_free_lockhint(), locator_guess_sub_classes(), locator_is_exist_class_name_entry(), lock_Conv, lock_object(), lock_unlock_object(), LOG_FIND_THREAD_TRAN_INDEX, logtb_tran_prepare_count_optim_classes(), mht_get(), NA_LOCK, NO_ERROR, NULL, NULL_LOCK, locator_classname_action::oid, OID_EQ, OID_ISNULL, oid_Root_class_oid, OID_SET_NULL, and xlocator_fetch_lockhint_classes().
Referenced by locator_find_lockhint_class_oids(), and slocator_find_lockhint_class_oids().
int xlocator_force (THREAD_ENTRY * thread_p, LC_COPYAREA * copy_area, int num_ignore_error_list, int * ignore_error_list)
Definition at line 6983 of file locator_sr.c.
References ARG_FILE_LINE, assert, assert_release, lc_copyarea_oneobj::class_oid, er_errid(), ER_ERROR_SEVERITY, ER_FAILED, ER_LC_BADFORCE_OPERATION, ER_MVCC_NOT_SATISFIED_REEVALUATION, er_set(), error(), lc_copyarea_oneobj::hfid, i, IS_MULTI_UPDATE, LC_FLUSH_DELETE, LC_FLUSH_INSERT, LC_FLUSH_INSERT_PRUNE, LC_FLUSH_INSERT_PRUNE_VERIFY, LC_FLUSH_UPDATE, LC_FLUSH_UPDATE_PRUNE, LC_FLUSH_UPDATE_PRUNE_VERIFY, LC_IS_FLUSH_UPDATE, LC_MANYOBJS_PTR_IN_COPYAREA, LC_NEXT_ONEOBJ_PTR_IN_COPYAREA, LC_ONEOBJ_GET_INDEX_FLAG, LC_PRIOR_ONEOBJ_PTR_IN_COPYAREA, LC_RECDES_IN_COPYAREA, LC_RECDES_TO_GET_ONEOBJ, LC_START_ONEOBJ_PTR_IN_COPYAREA, locator_area_op_to_pruning_type(), locator_delete_force(), locator_end_force_scan_cache(), locator_filter_errid(), locator_force_for_multi_update(), locator_insert_force(), locator_manyobj_flag_is_set(), locator_start_force_scan_cache(), locator_update_force(), LOG_CHECK_LOG_APPLIER, LOG_RESULT_TOPOP_ABORT, LOG_RESULT_TOPOP_ATTACH_TO_OUTER, NO_ERROR, NULL, lc_copyarea_manyobjs::num_objs, lc_copyarea_oneobj::oid, OID_EQ, oid_Root_class_oid, OID_SET_NULL, lc_copyarea_oneobj::operation, db_identifier::pageid, perfmon_inc_stat(), PSTAT_QM_NUM_DELETES, PSTAT_QM_NUM_INSERTS, PSTAT_QM_NUM_UPDATES, REPL_INFO_TYPE_RBR_NORMAL, SINGLE_ROW_DELETE, SINGLE_ROW_INSERT, SINGLE_ROW_UPDATE, db_identifier::slotid, UPDATE_INPLACE_NONE, db_identifier::volid, xtran_server_end_topop(), and xtran_server_start_topop().
Referenced by locator_force(), and slocator_force().
int xlocator_get_class (THREAD_ENTRY * thread_p, OID * class_oid, int class_chn, const OID * oid, LOCK lock, int prefetching, LC_COPYAREA ** fetch_area)
Definition at line 2704 of file locator_sr.c.
References ASSERT_ERROR_AND_SET, ER_FAILED, heap_get_class_oid(), LC_FETCH_CURRENT_VERSION, LK_GRANTED, LK_UNCOND_LOCK, lock_object(), lock_unlock_object(), NO_ERROR, NULL, NULL_LOCK, OID_ISNULL, oid_Root_class_oid, S_SUCCESS, and xlocator_fetch().
Referenced by locator_get_class(), and slocator_get_class().
int xlocator_get_reserved_class_name_oid (THREAD_ENTRY * thread_p, const char * classname, OID * class_oid)
Definition at line 689 of file locator_sr.c.
References locator_classname_action::action, ARG_FILE_LINE, assert, COPY_OID, csect_enter_as_reader, csect_exit, CSECT_LOCATOR_SR_CLASSNAME_TABLE, locator_classname_entry::e_current, locator_classname_entry::e_tran_index, ER_ERROR_SEVERITY, ER_FAILED, ER_GENERIC_ERROR, er_set(), error(), INF_WAIT, LC_CLASSNAME_RESERVED, LOG_FIND_THREAD_TRAN_INDEX, mht_get(), NO_ERROR, NULL, and locator_classname_action::oid.
Referenced by locator_get_reserved_class_name_oid(), and slocator_get_reserved_class_name_oid().
int xlocator_lock_and_fetch_all (THREAD_ENTRY * thread_p, const HFID * hfid, LOCK * instance_lock, int * instance_lock_timeout, OID * class_oid, LOCK * class_lock, int * nobjects, int * nfetched, int * nfailed_instance_locks, OID * last_oid, LC_COPYAREA ** fetch_area, MVCC_SNAPSHOT * mvcc_snapshot)
Definition at line 11790 of file locator_sr.c.
References recdes::area_size, lc_copyarea_oneobj::class_oid, COPY, COPY_OID, recdes::data, DB_ALIGN, DB_PAGESIZE, ER_FAILED, error(), lc_copyarea_oneobj::flag, heap_estimate_num_objects(), heap_get_visible_version(), heap_next(), heap_scancache_end(), heap_scancache_end_when_scan_will_resume(), heap_scancache_start(), lc_copyarea_oneobj::hfid, LC_FETCH, LC_MANYOBJS_PTR_IN_COPYAREA, LC_NEXT_ONEOBJ_PTR_IN_COPYAREA, LC_PRIOR_ONEOBJ_PTR_IN_COPYAREA, LC_RECDES_IN_COPYAREA, LC_START_ONEOBJ_PTR_IN_COPYAREA, recdes::length, lc_copyarea_oneobj::length, LK_GRANTED, LK_UNCOND_LOCK, locator_allocate_copy_area_by_length(), locator_free_copy_area(), locator_notify_decache(), lock_notify_isolation_incons(), lock_object(), lock_object_wait_msecs(), lock_unlock_object(), MAX_ALIGNMENT, lc_copyarea_desc::mobjs, NO_ERROR, NULL, NULL_CHN, NULL_HFID, NULL_LOCK, NULL_PAGEID, NULL_SLOTID, lc_copyarea_manyobjs::num_objs, lc_copyarea_desc::obj, lc_copyarea_oneobj::offset, lc_copyarea_desc::offset, locator_classname_action::oid, lc_copyarea_oneobj::oid, OID_ISNULL, oid_Root_class_oid, OID_SET_NULL, lc_copyarea_oneobj::operation, db_identifier::pageid, lc_copyarea_desc::recdes, S_DOESNT_FIT, S_END, S_ERROR, S_SUCCESS, db_identifier::slotid, hfid::vfid, vfid::volid, and db_identifier::volid.
Referenced by process_class(), and xlocator_upgrade_instances_domain().
bool xlocator_notify_isolation_incons (THREAD_ENTRY * thread_p, LC_COPYAREA ** synch_area)
Definition at line 9132 of file locator_sr.c.
References recdes::area_size, DB_PAGESIZE, LC_MANYOBJS_PTR_IN_COPYAREA, LC_RECDES_IN_COPYAREA, LC_START_ONEOBJ_PTR_IN_COPYAREA, locator_allocate_copy_area_by_length(), locator_free_copy_area(), locator_notify_decache(), lock_notify_isolation_incons(), lc_copyarea_desc::mobjs, NULL, lc_copyarea_manyobjs::num_objs, lc_copyarea_desc::obj, lc_copyarea_desc::offset, and lc_copyarea_desc::recdes.
Referenced by locator_notify_isolation_incons(), and slocator_notify_isolation_incons().
int xlocator_remove_class_from_index (THREAD_ENTRY * thread_p, OID * oid, BTID * btid, HFID * hfid)
Definition at line 8842 of file locator_sr.c.
References recdes::area_size, ARG_FILE_LINE, assert, ASSERT_ERROR, or_index::btid, BTID_IS_EQUAL, btree_physical_delete(), COPY, recdes::data, db_make_null(), DB_PAGESIZE, DBVAL_BUFSIZE, er_errid(), ER_ERROR_SEVERITY, ER_FAILED, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), or_index::filter_predicate, free_and_init, heap_attrinfo_end(), heap_attrinfo_read_dbvalues(), heap_attrinfo_start_with_index(), heap_attrvalue_get_key(), heap_next(), heap_scancache_end(), heap_scancache_start(), i, recdes::length, locator_eval_filter_predicate(), logtb_get_mvcc_snapshot(), logtb_tran_update_unique_stats(), MAX_ALIGNMENT, MULTI_ROW_DELETE, NO_ERROR, NULL, NULL_PAGEID, NULL_SLOTID, heap_idx_elements_info::num_btids, OID_IS_ROOTOID, db_identifier::pageid, pr_clear_value(), PTR_ALIGN, S_DOESNT_FIT, S_SUCCESS, db_identifier::slotid, V_TRUE, hfid::vfid, vfid::volid, and db_identifier::volid.
Referenced by locator_remove_class_from_index(), and slocator_remove_class_from_index().
LC_FIND_CLASSNAME xlocator_rename_class_name (THREAD_ENTRY * thread_p, const char * oldname, const char * newname, OID * class_oid)
Definition at line 916 of file locator_sr.c.
References locator_classname_action::action, assert, CSECT_CT_OID_TABLE, csect_enter, csect_exit, CSECT_LOCATOR_SR_CLASSNAME_TABLE, locator_classname_entry::e_current, locator_classname_entry::e_tran_index, error(), INF_WAIT, LC_CLASSNAME_DELETED, LC_CLASSNAME_DELETED_RENAME, LC_CLASSNAME_ERROR, LC_CLASSNAME_RESERVED, LC_CLASSNAME_RESERVED_RENAME, locator_drop_class_name_entry(), locator_is_exist_class_name_entry(), log_add_to_modified_class_list(), log_append_redo_data2(), LOG_FIND_THREAD_TRAN_INDEX, mht_get(), NO_ERROR, NULL, OID_ISNULL, RVLOC_CLASSNAME_DUMMY, strlen, xlocator_delete_class_name(), and xlocator_reserve_class_name().
Referenced by locator_rename_class_name(), and slocator_rename_class_name().
int xlocator_repl_force (THREAD_ENTRY * thread_p, LC_COPYAREA * copy_area, LC_COPYAREA ** reply_area)
Definition at line 6781 of file locator_sr.c.
References ARG_FILE_LINE, assert, assert_release, lc_copyarea_oneobj::class_oid, DB_IS_NULL, db_value_put_null(), er_clear(), er_errid(), ER_ERROR_SEVERITY, ER_FAILED, ER_LC_BADFORCE_OPERATION, ER_LC_PARTIALLY_FAILED_TO_FLUSH, er_msg(), er_set(), heap_get_class_info(), lc_copyarea_oneobj::hfid, HFID_COPY, HFID_EQ, HFID_INITIALIZER, HFID_SET_NULL, i, LC_FLUSH_DELETE, LC_FLUSH_INSERT, LC_FLUSH_INSERT_PRUNE, LC_FLUSH_INSERT_PRUNE_VERIFY, LC_FLUSH_UPDATE, LC_FLUSH_UPDATE_PRUNE, LC_FLUSH_UPDATE_PRUNE_VERIFY, LC_MANYOBJS_PTR_IN_COPYAREA, LC_NEXT_ONEOBJ_PTR_IN_COPYAREA, LC_ONEOBJ_GET_INDEX_FLAG, LC_PRIOR_ONEOBJ_PTR_IN_COPYAREA, LC_RECDES_IN_COPYAREA, LC_REPL_RECDES_FOR_ONEOBJ, LC_START_ONEOBJ_PTR_IN_COPYAREA, locator_area_op_to_pruning_type(), locator_delete_force(), locator_end_force_scan_cache(), locator_insert_force(), locator_repl_add_error_to_copyarea(), locator_repl_get_key_value(), locator_repl_prepare_force(), locator_start_force_scan_cache(), locator_update_force(), LOG_RESULT_TOPOP_ABORT, LOG_RESULT_TOPOP_ATTACH_TO_OUTER, NO_ERROR, NULL, lc_copyarea_manyobjs::num_objs, lc_copyarea_oneobj::oid, lc_copyarea_oneobj::operation, db_identifier::pageid, perfmon_inc_stat(), pr_clear_value(), PSTAT_QM_NUM_DELETES, PSTAT_QM_NUM_INSERTS, PSTAT_QM_NUM_UPDATES, RECDES_INITIALIZER, REPL_INFO_TYPE_RBR_NORMAL, SINGLE_ROW_DELETE, SINGLE_ROW_INSERT, SINGLE_ROW_UPDATE, db_identifier::slotid, UPDATE_INPLACE_NONE, db_identifier::volid, xtran_server_end_topop(), and xtran_server_start_topop().
Referenced by slocator_repl_force().
LC_FIND_CLASSNAME xlocator_reserve_class_names (THREAD_ENTRY * thread_p, const int num_classes, const char ** classname, OID * class_oid)
Definition at line 409 of file locator_sr.c.
References assert, i, LC_CLASSNAME_RESERVED, NULL, strlen, and xlocator_reserve_class_name().
Referenced by locator_reserve_class_names(), and slocator_reserve_classnames().
int xlocator_upgrade_instances_domain (THREAD_ENTRY * thread_p, OID * class_oid, int att_id)
Definition at line 12070 of file locator_sr.c.
References ARG_FILE_LINE, COPY_OID, ER_ERROR_SEVERITY, er_set(), ER_UNEXPECTED, error(), mvcctable::get_global_oldest_visible(), heap_attrinfo_clear_dbvalues(), heap_attrinfo_end(), heap_attrinfo_read_dbvalues(), heap_attrinfo_start(), heap_get_class_info(), heap_object_upgrade_domain(), heap_scancache_end_modify(), heap_scancache_start_modify(), heap_vacuum_all_objects(), HFID_SET_NULL, i, LC_FETCH_DECACHE_LOCK, LC_MANYOBJS_PTR_IN_COPYAREA, LC_NEXT_ONEOBJ_PTR_IN_COPYAREA, LC_RECDES_TO_GET_ONEOBJ, LC_START_ONEOBJ_PTR_IN_COPYAREA, locator_free_copy_area(), LOG_FIND_CURRENT_TDES(), LOG_FIND_THREAD_TRAN_INDEX, log_Gl, log_global::mvcc_table, NO_ERROR, NULL, lc_copyarea_manyobjs::num_objs, lc_copyarea_oneobj::oid, OID_ISNULL, OID_SET_NULL, lc_copyarea_oneobj::operation, SCH_M_LOCK, SINGLE_ROW_UPDATE, X_LOCK, and xlocator_lock_and_fetch_all().
Referenced by locator_upgrade_instances_domain(), and slocator_upgrade_instances_domain().
void xlock_dump (THREAD_ENTRY * thread_p, FILE * outfp)
Definition at line 8429 of file lock_manager.c.
References assert_release, LK_FORCE_ZERO_WAIT, LK_INFINITE_WAIT, LK_ZERO_WAIT, log_isolation_string(), log_state_string(), logtb_find_client_name_host_pid(), logtb_find_isolation(), logtb_find_state(), logtb_find_wait_msecs(), MSGCAT_CATALOG_CUBRID, MSGCAT_LK_DUMP_LOCK_TABLE, MSGCAT_LK_DUMP_TRAN_IDENTIFIERS, MSGCAT_LK_DUMP_TRAN_ISOLATION, MSGCAT_LK_DUMP_TRAN_STATE, MSGCAT_LK_DUMP_TRAN_TIMEOUT_PERIOD, MSGCAT_LK_NEWLINE, msgcat_message(), MSGCAT_SET_LOCK, NO_ERROR, NULL, prm_get_float_value(), prm_get_integer_value(), PRM_ID_LK_ESCALATION_AT, PRM_ID_LK_RUN_DEADLOCK_INTERVAL, and xlogtb_reset_wait_msecs().
Referenced by lock_demote_class_lock(), lock_dump(), and slock_dump().
int xlogin_user (THREAD_ENTRY * thread_p, const char * username)
Definition at line 245 of file session_sr.c.
References login_user().
Referenced by clogin_user(), and slogin_user().
bool xlogtb_does_active_user_exist (THREAD_ENTRY * thread_p, const char * user_name)
Definition at line 5111 of file log_tran_table.c.
References trantable::all_tdes, log_tdes::client, clientids::get_db_user(), i, log_tdes::is_user_active, log_Gl, NULL, NUM_TOTAL_TRAN_INDICES, TR_TABLE_CS_ENTER_READ_MODE, TR_TABLE_CS_EXIT, and log_global::trantable.
Referenced by slogtb_does_active_user_exist().
int xlogtb_get_pack_tran_table (THREAD_ENTRY * thread_p, char ** buffer_p, int * size_p, int include_query_exec_info)
Definition at line 2199 of file log_tran_table.c.
References trantable::all_tdes, ARG_FILE_LINE, assert, ASSERT_ERROR, CAST_BUFLEN, log_tdes::client, CUB_MAXHOSTNAMELEN, DB_ALIGN, clientids::db_user, ER_ERROR_SEVERITY, ER_OUT_OF_VIRTUAL_MEMORY, er_set(), error(), free_and_init, clientids::get_db_user(), clientids::get_host_name(), clientids::get_login_name(), clientids::get_program_name(), clientids::host_name, i, INT_ALIGNMENT, L_cuserid, lock_get_lock_holder_tran_index(), log_get_clock_msec(), log_Gl, LOG_SYSTEM_TRAN_INDEX, LOG_USERNAME_MAX, clientids::login_name, NO_ERROR, NULL, NULL_TRANID, NUM_TOTAL_TRAN_INDICES, OR_FLOAT_SIZE, OR_INT_SIZE, or_pack_float(), or_pack_int(), or_pack_string(), or_pack_string_with_length(), OR_PACK_XASL_ID, or_packed_string_length(), OR_XASL_ID_SIZE, clientids::process_id, clientids::program_name, qmgr_get_sql_id(), log_tdes::query_start_time, tran_query_exec_info::query_stmt, tran_query_exec_info::query_time, xasl_id::sha1, execution_info::sql_hash_text, xasl_cache_ent::sql_info, execution_info::sql_user_text, log_tdes::state, strdup(), strlen, TR_TABLE_CS_ENTER_READ_MODE, TR_TABLE_CS_EXIT, log_tdes::tran_index, log_tdes::tran_start_time, tran_query_exec_info::tran_time, log_global::trantable, log_tdes::trid, log_tdes::waiting_for_res, XASL_CACHE_SEARCH_GENERIC, log_tdes::xasl_id, XASL_ID_COPY, XASL_ID_IS_NULL, XASL_ID_SET_NULL, xcache_find_sha1(), and xcache_unfix().
Referenced by logtb_get_pack_tran_table(), and slogtb_get_pack_tran_table().
int xlogtb_reset_isolation (THREAD_ENTRY * thread_p, TRAN_ISOLATION isolation)
Definition at line 2611 of file log_tran_table.c.
References ARG_FILE_LINE, ER_MVCC_LOG_INVALID_ISOLATION_LEVEL, er_set(), ER_SYNTAX_ERROR_SEVERITY, IS_VALID_ISOLATION_LEVEL, log_tdes::isolation, LOG_FIND_TDES(), LOG_FIND_THREAD_TRAN_INDEX, NO_ERROR, and NULL.
Referenced by log_reset_isolation(), and slogtb_reset_isolation().
int xlogtb_reset_wait_msecs (THREAD_ENTRY * thread_p, int wait_msecs)
Definition at line 2498 of file log_tran_table.c.
References ARG_FILE_LINE, ER_FATAL_ERROR_SEVERITY, ER_LOG_UNKNOWN_TRANINDEX, er_set(), LOG_FIND_TDES(), LOG_FIND_THREAD_TRAN_INDEX, NULL, and log_tdes::wait_msecs.
Referenced by btree_set_error(), disk_is_page_sector_reserved_with_debug_crash(), heap_does_exist(), heap_stats_find_page_in_bestspace(), lock_object_wait_msecs(), log_reset_wait_msecs(), log_rollback(), qexec_execute_mainblock_internal(), slogtb_reset_wait_msecs(), xbtree_load_online_index(), and xlock_dump().
void xlogtb_set_interrupt (THREAD_ENTRY * thread_p, int set)
Definition at line 2687 of file log_tran_table.c.
References LOG_FIND_THREAD_TRAN_INDEX, and logtb_set_tran_index_interrupt().
Referenced by log_set_interrupt(), qexec_execute_query(), and slogtb_set_interrupt().
void xlogtb_set_suppress_repl_on_transaction (THREAD_ENTRY * thread_p, int set)
Definition at line 2928 of file log_tran_table.c.
References LOG_FIND_THREAD_TRAN_INDEX, and logtb_set_suppress_repl_on_transaction().
Referenced by log_set_suppress_repl_on_transaction(), and slogtb_set_suppress_repl_on_transaction().
void xperfmon_server_copy_global_stats (UINT64 * to_stats)
Referenced by perfmon_server_copy_global_stats(), perfmon_stat_dump_in_buffer_thread_daemon_stats(), and smnt_server_copy_global_stats().
void xperfmon_server_copy_stats (THREAD_ENTRY * thread_p, UINT64 * to_stats)
Referenced by perfmon_server_copy_stats(), smnt_server_copy_stats(), and sqmgr_execute_query().
int xqfile_get_list_file_page (THREAD_ENTRY * thread_p, QUERY_ID query_id, VOLID volid, PAGEID pageid, char * page_bufp, int * page_sizep)
Definition at line 2200 of file list_file.c.
References assert, DB_PAGESIZE, er_errid(), ER_QPROC_UNKNOWN_QUERYID, qmgr_query_entry::errid, IO_MAX_PAGE_SIZE, qmgr_query_entry::list_id, LOG_FIND_THREAD_TRAN_INDEX, NO_ERROR, NULL, NULL_PAGEID, NULL_PAGEID_IN_PROGRESS, NULL_VOLID, vpid::pageid, QFILE_GET_LAST_TUPLE_OFFSET, QFILE_GET_NEXT_VPID, QFILE_GET_OVERFLOW_PAGE_ID, QFILE_GET_OVERFLOW_VPID, QFILE_GET_TUPLE_COUNT, QFILE_GET_TUPLE_LENGTH, QFILE_OVERFLOW_TUPLE_COUNT_FLAG, QFILE_PAGE_HEADER_SIZE, qmgr_free_old_page_and_init, qmgr_get_old_page(), qmgr_get_query_entry(), QUERY_COMPLETED, qmgr_query_entry::query_status, qfile_list_id::tfile_vfid, and VPID_SET.
Referenced by qfile_get_list_file_page(), and sqfile_get_list_file_page().
int xqmgr_drop_all_query_plans (THREAD_ENTRY * thread_p)
Definition at line 2015 of file query_manager.c.
References fpcache_drop_all(), NO_ERROR, and xcache_drop_all().
Referenced by qmgr_drop_all_query_plans(), and sqmgr_drop_all_query_plans().
void xqmgr_dump_query_cache (THREAD_ENTRY * thread_p, FILE * outfp)
Definition at line 2040 of file query_manager.c.
References qfile_dump_list_cache_internal().
Referenced by qmgr_dump_query_cache(), and sqmgr_dump_query_cache().
void xqmgr_dump_query_plans (THREAD_ENTRY * thread_p, FILE * outfp)
Definition at line 2028 of file query_manager.c.
References fpcache_dump(), and xcache_dump().
Referenced by qmgr_dump_query_plans(), and sqmgr_dump_query_plans().
int xqmgr_end_query (THREAD_ENTRY * thrd, QUERY_ID query_id)
Definition at line 1953 of file query_manager.c.
References ARG_FILE_LINE, assert, ER_FAILED, ER_QPROC_UNKNOWN_QUERYID, er_set(), ER_WARNING_SEVERITY, qmgr_query_entry::is_holdable, qmgr_query_entry::list_ent, qmgr_query_entry::list_id, LOG_FIND_THREAD_TRAN_INDEX, NO_ERROR, NULL, qfile_end_use_of_list_cache_entry(), QFILE_FREE_AND_INIT_LIST_ID, qmgr_delete_query_entry(), qmgr_find_query_entry(), qmgr_free_query_temp_file(), QUERY_COMPLETED, qmgr_tran_entry::query_entry_list_p, qmgr_query_entry::query_id, qmgr_query_entry::query_status, rc, qmgr_query_table::tran_entries_p, qmgr_query_entry::xasl_ent, qmgr_query_entry::xasl_id, XASL_ID_SET_NULL, xsession_clear_query_entry_info(), and xsession_remove_query_entry_info().
Referenced by qmgr_end_query(), sqmgr_end_query(), stran_server_auto_commit_or_abort(), and stran_server_commit().
QFILE_LIST_ID* xqmgr_execute_query (THREAD_ENTRY * thrd, const XASL_ID * xasl_id, QUERY_ID * query_idp, int dbval_cnt, void * data, QUERY_FLAG * flagp, CACHE_TIME * clt_cache_time, CACHE_TIME * srv_cache_time, int query_timeout, xasl_cache_ent ** ret_cache_entry_p)
Definition at line 1243 of file query_manager.c.
References ARG_FILE_LINE, assert, ASSERT_ERROR, CACHE_TIME_AS_ARGS, CACHE_TIME_MAKE, CACHE_TIME_RESET, copy_bind_value_to_tdes(), db_private_alloc, db_private_free, db_private_free_and_init, DO_NOT_COLLECT_EXEC_STATS, ER_ERROR_SEVERITY, er_log_debug, ER_QM_QENTRY_RUNOUT, ER_QPROC_INVALID_XASLNODE, er_set(), FILE_QUERY_AREA, i, qmgr_query_entry::is_holdable, IS_IN_METHOD_OR_JSP_CALL, IS_TRIGGER_INVOLVED, IS_XASL_CACHE_PINNED_REFERENCE, IS_XASL_TRACE_JSON, IS_XASL_TRACE_TEXT, qfile_list_id::last_pgptr, qmgr_query_entry::list_ent, xasl_cache_ent::list_ht_no, qfile_list_cache_entry::list_id, qmgr_query_entry::list_id, LOG_FIND_THREAD_TRAN_INDEX, NO_ERROR, NULL, or_unpack_db_value(), perfmon_inc_stat(), pr_clear_value(), pr_valstring(), PSTAT_PC_NUM_INVALID_XASL_ID, qfile_clone_list_id(), qfile_destroy_list(), qfile_duplicate_list(), qfile_end_use_of_list_cache_entry(), QFILE_FLAG_RESULT_FILE, QFILE_FREE_AND_INIT_LIST_ID, qfile_lookup_list_cache_entry(), qfile_update_list_cache_entry(), qmgr_add_query_entry(), qmgr_allocate_query_entry(), qmgr_delete_query_entry(), qmgr_free_query_temp_file(), qmgr_is_allowed_result_cache(), qmgr_is_related_class_modified(), qmgr_mark_query_as_completed(), QMGR_MAX_QUERY_ENTRY_PER_TRAN, qmgr_process_query(), QMGR_TRAN_NULL, QMGR_TRAN_RUNNING, QMGR_TRAN_TERMINATED, qmgr_query_entry::query_flag, qmgr_query_entry::query_id, qfile_list_id::query_id, QUERY_IN_PROGRESS, qmgr_query_entry::query_status, QUERY_TRACE_JSON, QUERY_TRACE_TEXT, RESULT_HOLDABLE, session_set_trigger_state(), xasl_id::sha1, SHA1_AS_ARGS, db_value_array::size, qmgr_temp_file::temp_file_type, qfile_list_id::tfile_vfid, thread_get_recursion_depth(), thread_set_trace_format(), thread_trace_on(), qfile_list_cache_entry::time_created, xasl_id::time_stored, qmgr_query_table::tran_entries_p, qmgr_tran_entry::trans_stat, db_value_array::vals, xasl_clone::xasl, xasl_clone::xasl_buf, XASL_CLONE_INITIALIZER, qmgr_query_entry::xasl_ent, qmgr_query_entry::xasl_id, XASL_ID_COPY, xcache_can_entry_cache_list(), xcache_find_xasl_id_for_execute(), xcache_retire_clone(), and xcache_unfix().
Referenced by qmgr_execute_query(), and sqmgr_execute_query().
QFILE_LIST_ID* xqmgr_prepare_and_execute_query (THREAD_ENTRY * thrd, char * xasl_stream, int xasl_stream_size, QUERY_ID * query_id, int dbval_cnt, void * data, QUERY_FLAG * flag, int query_timeout)
Definition at line 1739 of file query_manager.c.
References ARG_FILE_LINE, assert, db_private_alloc, db_private_free_and_init, DO_NOT_COLLECT_EXEC_STATS, ER_ERROR_SEVERITY, er_log_debug, ER_QM_QENTRY_RUNOUT, er_set(), i, qmgr_query_entry::is_holdable, IS_TRIGGER_INVOLVED, IS_XASL_TRACE_JSON, IS_XASL_TRACE_TEXT, qmgr_query_entry::list_ent, LOG_FIND_THREAD_TRAN_INDEX, NO_ERROR, NULL, or_unpack_db_value(), pr_clear_value(), QFILE_FREE_AND_INIT_LIST_ID, qmgr_add_query_entry(), qmgr_allocate_query_entry(), qmgr_delete_query_entry(), qmgr_free_query_temp_file(), qmgr_mark_query_as_completed(), QMGR_MAX_QUERY_ENTRY_PER_TRAN, qmgr_process_query(), QMGR_TRAN_NULL, QMGR_TRAN_RUNNING, QMGR_TRAN_TERMINATED, qmgr_query_entry::query_flag, qmgr_query_entry::query_id, QUERY_IN_PROGRESS, qmgr_query_entry::query_status, QUERY_TRACE_JSON, QUERY_TRACE_TEXT, RESULT_HOLDABLE, session_set_trigger_state(), thread_get_recursion_depth(), thread_set_trace_format(), thread_trace_on(), qmgr_query_table::tran_entries_p, qmgr_tran_entry::trans_stat, qmgr_query_entry::xasl_ent, qmgr_query_entry::xasl_id, and XASL_ID_SET_NULL.
Referenced by qmgr_prepare_and_execute_query(), and sqmgr_prepare_and_execute_query().
int xqmgr_prepare_query (THREAD_ENTRY * thrd, compile_context * ctx, xasl_stream * stream)
Definition at line 948 of file query_manager.c.
References ARG_FILE_LINE, assert, ASSERT_ERROR, ASSERT_ERROR_AND_SET, assert_release, xasl_stream::buffer, db_private_alloc, db_private_free_and_init, ER_ERROR_SEVERITY, ER_FAILED, ER_GENERIC_ERROR, er_set(), i, NO_ERROR, NULL, or_unpack_int(), or_unpack_oid(), p, qfile_load_xasl_node_header(), compile_context::recompile_xasl, compile_context::sha1, XASL_CACHE_RECOMPILE_NOT_NEEDED, XASL_CACHE_RECOMPILE_PREPARE, XASL_CACHE_SEARCH_FOR_PREPARE, xasl_stream::xasl_header, xasl_cache_ent::xasl_id, xasl_stream::xasl_id, XASL_ID_COPY, XASL_ID_SET_NULL, xcache_find_sha1(), xcache_insert(), and xcache_unfix().
Referenced by qmgr_prepare_query(), and sqmgr_prepare_query().
LOG_LSA* xrepl_log_get_append_lsa (void)
Definition at line 11669 of file locator_sr.c.
References log_get_append_lsa().
Referenced by repl_log_get_append_lsa(), and srepl_log_get_append_lsa().
int xrepl_set_info (THREAD_ENTRY * thread_p, REPL_INFO * repl_info)
Definition at line 11642 of file locator_sr.c.
References ARG_FILE_LINE, ER_REPL_ERROR, er_set(), ER_WARNING_SEVERITY, repl_info::info, LOG_CHECK_LOG_APPLIER, log_does_allow_replication(), NO_ERROR, repl_info::repl_info_type, and REPL_INFO_TYPE_SBR.
Referenced by repl_set_info(), srepl_set_info(), and xchksum_insert_repl_log_and_demote_table_lock().
int xsession_check_session (THREAD_ENTRY * thread_p, const SESSION_ID id)
Definition at line 53 of file session_sr.c.
References session_check_session().
Referenced by csession_find_or_create_session(), and ssession_find_or_create_session().
int xsession_clear_query_entry_info (THREAD_ENTRY * thread_p, const QUERY_ID query_id)
Definition at line 357 of file session_sr.c.
References session_clear_query_entry_info().
Referenced by qmgr_clear_trans_wakeup(), and xqmgr_end_query().
int xsession_create_new (THREAD_ENTRY * thread_p, SESSION_ID * id)
Definition at line 38 of file session_sr.c.
References assert, NULL, and session_state_create().
Referenced by csession_find_or_create_session(), and ssession_find_or_create_session().
int xsession_create_prepared_statement (THREAD_ENTRY * thread_p, char * name, char * alias_print, SHA1Hash * sha1, char * info, int info_len)
Definition at line 171 of file session_sr.c.
References session_create_prepared_statement().
Referenced by csession_create_prepared_statement(), and ssession_create_prepared_statement().
int xsession_delete_prepared_statement (THREAD_ENTRY * thread_p, const char * name)
Definition at line 233 of file session_sr.c.
References session_delete_prepared_statement().
Referenced by csession_delete_prepared_statement(), and ssession_delete_prepared_statement().
int xsession_drop_session_variables (THREAD_ENTRY * thread_p, DB_VALUE * values, const int count)
Definition at line 306 of file session_sr.c.
References session_drop_session_variables().
Referenced by csession_drop_session_variables(), and ssession_drop_session_variables().
int xsession_end_session (THREAD_ENTRY * thread, const SESSION_ID id)
Definition at line 65 of file session_sr.c.
References session_state_destroy().
Referenced by csession_end_session(), and ssession_end_session().
int xsession_get_last_insert_id (THREAD_ENTRY * thread_p, DB_VALUE * value, bool update_last_insert_id)
Definition at line 126 of file session_sr.c.
References assert, db_make_null(), err, NO_ERROR, NULL, and session_get_last_insert_id().
Referenced by csession_get_last_insert_id(), and ssession_get_last_insert_id().
int xsession_get_prepared_statement (THREAD_ENTRY * thread_p, const char * name, char ** info, int * info_len, XASL_ID * xasl_id, xasl_node_header * xasl_header_p)
Definition at line 190 of file session_sr.c.
References assert, ASSERT_ERROR, xasl_stream::buffer, error(), NO_ERROR, NULL, perfmon_inc_stat(), PSTAT_PC_NUM_INVALID_XASL_ID, qfile_load_xasl_node_header(), session_get_prepared_statement(), xasl_cache_ent::stream, xasl_cache_ent::xasl_id, XASL_ID_COPY, XASL_ID_SET_NULL, and xcache_unfix().
Referenced by csession_get_prepared_statement(), and ssession_get_prepared_statement().
int xsession_get_row_count (THREAD_ENTRY * thread_p, int * row_count)
Definition at line 91 of file session_sr.c.
References session_get_row_count().
Referenced by csession_find_or_create_session(), csession_get_row_count(), ssession_find_or_create_session(), and ssession_get_row_count().
int xsession_get_session_variable (THREAD_ENTRY * thread_p, const DB_VALUE * name, DB_VALUE * value)
Definition at line 271 of file session_sr.c.
References session_get_variable().
Referenced by ssession_get_session_variable().
int xsession_get_session_variable_no_copy (THREAD_ENTRY * thread_p, const DB_VALUE * name, DB_VALUE ** value)
Definition at line 288 of file session_sr.c.
References assert, ER_FAILED, and session_get_variable_no_copy().
Referenced by csession_get_variable().
int xsession_load_query_entry_info (THREAD_ENTRY * thread_p, QMGR_QUERY_ENTRY * qentry_p)
Definition at line 330 of file session_sr.c.
References session_load_query_entry_info().
Referenced by qmgr_get_query_entry().
int xsession_remove_query_entry_info (THREAD_ENTRY * thread_p, const QUERY_ID query_id)
Definition at line 343 of file session_sr.c.
References session_remove_query_entry_info().
Referenced by xqmgr_end_query().
int xsession_reset_cur_insert_id (THREAD_ENTRY * thread_p)
Definition at line 147 of file session_sr.c.
References err, NO_ERROR, and session_reset_cur_insert_id().
Referenced by csession_reset_cur_insert_id(), and ssession_reset_cur_insert_id().
int xsession_set_cur_insert_id (THREAD_ENTRY * thread_p, const DB_VALUE * value, bool force)
Definition at line 106 of file session_sr.c.
References assert, err, NO_ERROR, NULL, and session_set_cur_insert_id().
Referenced by xserial_get_next_value().
int xsession_set_row_count (THREAD_ENTRY * thread_p, int row_count)
Definition at line 78 of file session_sr.c.
References session_set_row_count().
Referenced by csession_set_row_count(), ssession_set_row_count(), and stran_server_commit().
int xsession_set_session_variables (THREAD_ENTRY * thread_p, DB_VALUE * values, const int count)
Definition at line 258 of file session_sr.c.
References session_set_session_variables().
Referenced by csession_set_session_variables(), and ssession_set_session_variables().
int xsession_set_tran_auto_commit (THREAD_ENTRY * thread_p, bool auto_commit)
Definition at line 370 of file session_sr.c.
References session_set_tran_auto_commit().
Referenced by sqmgr_execute_query(), and sqmgr_prepare_and_execute_query().
void xsession_store_query_entry_info (THREAD_ENTRY * thread_p, QMGR_QUERY_ENTRY * qentry_p)
Definition at line 318 of file session_sr.c.
References session_store_query_entry_info().
Referenced by qmgr_clear_trans_wakeup().
char* xstats_get_statistics_from_server (THREAD_ENTRY * thread_p, OID * class_id, unsigned int timestamp, int * length)
Definition at line 443 of file statistics_sr.c.
References catalog_access_info::access_started, db_monetary::amount, ARG_FILE_LINE, assert, ASSERT_ERROR_AND_SET, assert_release, db_data::bigint, disk_attribute::bt_stats, btree_stats::btid, BTREE_STATS_PKEYS_NUM, CAST_STRLEN, CATALOG_ACCESS_INFO_INITIALIZER, catalog_end_access_with_dir_oid(), catalog_free_class_info_and_init, catalog_free_representation_and_init, catalog_get_class_info(), catalog_get_dir_oid_from_cache(), catalog_get_last_representation_id(), catalog_get_representation(), catalog_start_access_with_dir_oid(), cls_info::ci_hfid, cls_info::ci_time_stamp, cls_info::ci_tot_objects, cls_info::ci_tot_pages, catalog_access_info::class_oid, db_data::d, db_datetime::date, db_data::date, db_datetimetz::datetime, db_data::datetime, db_data::datetimetz, DB_EQ, DB_GT, DB_LT, DB_TYPE_BIGINT, DB_TYPE_DATE, DB_TYPE_DATETIME, DB_TYPE_DATETIMELTZ, DB_TYPE_DATETIMETZ, DB_TYPE_DOUBLE, DB_TYPE_FLOAT, DB_TYPE_INTEGER, DB_TYPE_MIDXKEY, DB_TYPE_MONETARY, DB_TYPE_SHORT, DB_TYPE_TIME, DB_TYPE_TIMESTAMP, DB_TYPE_TIMESTAMPLTZ, DB_TYPE_TIMESTAMPTZ, catalog_access_info::dir_oid, er_clear(), ER_ERROR_SEVERITY, ER_FAILED, ER_INTERRUPTED, er_set(), ER_UPDATE_STAT_CANNOT_GET_LOCK, err, db_data::f, file_get_num_user_pages(), disk_representation::fixed, free_and_init, btree_stats::has_function, heap_estimate_num_objects(), heap_get_class_name(), btree_stats::height, HFID_IS_NULL, i, db_data::i, disk_attribute::id, btree_stats::key_type, btree_stats::keys, btree_stats::leafs, LK_GRANTED, LK_UNCOND_LOCK, lock_object(), lock_unlock_object(), db_data::money, disk_attribute::n_btstats, disk_representation::n_fixed, disk_representation::n_variable, NO_ERROR, NULL, oid_Root_class_oid, OR_BTID_ALIGNED_SIZE, OR_INT_SIZE, or_pack_domain(), or_packed_domain_size(), OR_PUT_BTID, OR_PUT_INT, btree_stats::pages, btree_stats::pkeys, btree_stats::pkeys_size, prm_get_bool_value(), PRM_ID_USE_STAT_ESTIMATION, S_LOCK, SCH_S_LOCK, tp_domain::setdomain, db_data::sh, db_datetime::time, db_data::time, db_timestamptz::timestamp, db_data::timestamptz, tp_domain_size(), TP_DOMAIN_TYPE, disk_attribute::type, db_data::utime, disk_representation::variable, hfid::vfid, btid::vfid, VFID_ISNULL, and xbtree_get_unique_pk().
Referenced by sqst_server_get_statistics(), and stats_get_statistics_from_server().
int xstats_update_all_statistics (THREAD_ENTRY * thread_p, bool with_fullscan)
Definition at line 356 of file statistics_sr.c.
References assert, boot_find_root_heap(), COPY, recdes::data, DISK_ERROR, er_clear(), ER_SP_UNKNOWN_SLOTID, ER_UPDATE_STAT_CANNOT_GET_LOCK, error(), heap_next(), heap_scancache_end(), heap_scancache_start(), HFID_IS_NULL, logtb_get_mvcc_snapshot(), NO_ERROR, NULL, NULL_PAGEID, NULL_SLOTID, oid_Root_class_oid, or_class_name(), db_identifier::pageid, RECDES_INITIALIZER, S_SUCCESS, db_identifier::slotid, strlen, hfid::vfid, vfid::volid, db_identifier::volid, and xstats_update_statistics().
Referenced by sqst_update_all_statistics(), and stats_update_all_statistics().
int xstats_update_statistics (THREAD_ENTRY * thread_p, OID * classoid, bool with_fullscan)
Definition at line 105 of file statistics_sr.c.
References ARG_FILE_LINE, assert, ASSERT_ERROR_AND_SET, assert_release, disk_attribute::bt_stats, btree_stats::btid, BTID_IS_NULL, btree_get_stats(), BTREE_STATS_PKEYS_NUM, CATALOG_ACCESS_INFO_INITIALIZER, catalog_add_class_info(), catalog_add_representation(), catalog_end_access_with_dir_oid(), catalog_free_class_info_and_init, catalog_free_representation_and_init, catalog_get_class_info(), catalog_get_dir_oid_from_cache(), catalog_get_last_representation_id(), catalog_get_representation(), catalog_start_access_with_dir_oid(), cls_info::ci_hfid, cls_info::ci_rep_dir, cls_info::ci_time_stamp, cls_info::ci_tot_objects, cls_info::ci_tot_pages, catalog_access_info::class_name, catalog_access_info::class_oid, cubregex::count(), db_private_free, catalog_access_info::dir_oid, er_errid(), ER_FAILED, ER_LOG_FINISHED_TO_UPDATE_STATISTICS, ER_LOG_STARTED_TO_UPDATE_STATISTICS, ER_NOTIFICATION_SEVERITY, er_set(), ER_UPDATE_STAT_CANNOT_GET_LOCK, error(), file_get_num_user_pages(), vfid::fileid, disk_representation::fixed, free_and_init, heap_estimate_num_objects(), heap_get_class_name(), i, btree_stats::keys, LK_COND_LOCK, LK_GRANTED, lock_object(), lock_unlock_object(), disk_representation::n_fixed, disk_representation::n_variable, NO_ERROR, NULL, OID_ISNULL, oid_Root_class_oid, OID_SET_NULL, db_identifier::pageid, partition_get_partition_oids(), btree_stats::pkeys_size, S_LOCK, SCH_S_LOCK, db_identifier::slotid, stats_get_time_stamp(), stats_update_partitioned_statistics(), disk_representation::variable, hfid::vfid, vfid::volid, db_identifier::volid, and X_LOCK.
Referenced by sqst_update_statistics(), stats_update_partitioned_statistics(), stats_update_statistics(), cubload::session::update_class_statistics(), and xstats_update_all_statistics().
int xtde_change_mk_without_flock (THREAD_ENTRY * thread_p, const int mk_index)
Definition at line 1246 of file tde.c.
References ARG_FILE_LINE, boot_db_full_name(), ER_ERROR_SEVERITY, ER_IO_MOUNT_FAIL, er_set_with_oserror(), err, fileio_close(), fileio_open(), tde_keyinfo::mk_hash, tde_keyinfo::mk_index, NO_ERROR, NULL, NULL_VOLDES, tde_change_mk(), tde_find_mk(), tde_get_keyinfo(), tde_make_keys_file_fullname(), TDE_MASTER_KEY_LENGTH, and tde_validate_mk().
Referenced by stde_change_mk_on_server(), and tde_change_mk_on_server().
int xtde_get_mk_info (THREAD_ENTRY * thread_p, int * mk_index, time_t * created_time, time_t * set_time)
Definition at line 1214 of file tde.c.
References ARG_FILE_LINE, tde_keyinfo::created_time, ER_ERROR_SEVERITY, er_set(), ER_TDE_CIPHER_IS_NOT_LOADED, err, tde_cipher::is_loaded, tde_keyinfo::mk_index, NO_ERROR, tde_keyinfo::set_time, and tde_get_keyinfo().
Referenced by stde_get_mk_info(), and tde_get_mk_info().
bool xtran_is_blocked (THREAD_ENTRY * thread_p, int tran_index)
Definition at line 559 of file transaction_sr.c.
References lock_is_waiting_transaction().
Referenced by stran_is_blocked(), and tran_is_blocked().
int xtran_lock_rep_read (THREAD_ENTRY * thread_p, LOCK lock_rr_tran)
Definition at line 691 of file transaction_sr.c.
References ARG_FILE_LINE, BOOT_BROKER_AND_DEFAULT_CLIENT_TYPE, BOOT_CSQL_CLIENT_TYPE, boot_Host_name, BOOT_IS_ALLOWED_CLIENT_TYPE_IN_MT_MODE, BOOT_NORMAL_CLIENT_TYPE, css_ha_server_state(), css_is_ha_repl_delayed(), DB_CLIENT_TYPE_BROKER, DB_CLIENT_TYPE_SLAVE_ONLY_BROKER, er_log_debug, HA_SERVER_STATE_ACTIVE, HA_SERVER_STATE_MAINTENANCE, HA_SERVER_STATE_STANDBY, HA_SERVER_STATE_TO_BE_STANDBY, LK_UNCOND_LOCK, lock_rep_read_tran(), logtb_find_current_client_hostname(), logtb_find_current_client_type(), and xtran_should_connection_reset().
Referenced by slocator_find_lockhint_class_oids(), and stran_lock_rep_read().
int xtran_server_2pc_attach_global_tran (THREAD_ENTRY * thread_p, int gtrid)
Definition at line 512 of file transaction_sr.c.
References log_2pc_attach_global_tran().
Referenced by stran_server_2pc_attach_global_tran(), and tran_server_2pc_attach_global_tran().
TRAN_STATE xtran_server_2pc_prepare (THREAD_ENTRY * thread_p)
Definition at line 466 of file transaction_sr.c.
References locator_drop_transient_class_name_entries(), log_2pc_prepare(), and NULL.
Referenced by stran_server_2pc_prepare(), and tran_server_2pc_prepare().
TRAN_STATE xtran_server_2pc_prepare_global_tran (THREAD_ENTRY * thread_p, int gtrid)
Definition at line 540 of file transaction_sr.c.
References locator_drop_transient_class_name_entries(), log_2pc_prepare_global_tran(), and NULL.
Referenced by stran_server_2pc_prepare_global_tran(), and tran_server_2pc_prepare_global_tran().
int xtran_server_2pc_recovery_prepared (THREAD_ENTRY * thread_p, int gtrids[], int size)
Definition at line 490 of file transaction_sr.c.
References log_2pc_recovery_prepared().
Referenced by stran_server_2pc_recovery_prepared(), and tran_server_2pc_recovery_prepared().
int xtran_server_2pc_start (THREAD_ENTRY * thread_p)
Definition at line 446 of file transaction_sr.c.
References log_2pc_start().
Referenced by stran_server_2pc_start(), and tran_server_2pc_start().
TRAN_STATE xtran_server_abort (THREAD_ENTRY * thrd)
Definition at line 113 of file transaction_sr.c.
References ARG_FILE_LINE, ER_ERROR_SEVERITY, ER_LK_UNILATERALLY_ABORTED, er_set(), log_abort(), LOG_FIND_THREAD_TRAN_INDEX, LOG_SET_CURRENT_TRAN_INDEX, logtb_find_client_name_host_pid(), NULL, thread_get_thread_entry_info(), and tran_server_unilaterally_abort_tran().
Referenced by cubload::load_task::execute(), stran_server_abort_internal(), tran_server_abort(), xboot_copy(), and xboot_unregister_client().
TRAN_STATE xtran_server_commit (THREAD_ENTRY * thrd, bool retain_lock)
Definition at line 69 of file transaction_sr.c.
References log_commit(), LOG_FIND_THREAD_TRAN_INDEX, TRAN_UNACTIVE_COMMITTED, and TRAN_UNACTIVE_COMMITTED_INFORMING_PARTICIPANTS.
Referenced by boot_reset_mk_after_restart_from_backup(), boot_restart_server(), cubload::load_task::execute(), stran_server_commit_internal(), tran_server_commit(), xboot_copy(), and xboot_emergency_patch().
TRAN_STATE xtran_server_end_topop (THREAD_ENTRY * thread_p, LOG_RESULT_TOPOP result, LOG_LSA * topop_lsa)
Definition at line 245 of file transaction_sr.c.
References ARG_FILE_LINE, assert, ER_FATAL_ERROR_SEVERITY, ER_LOG_UNKNOWN_TRANINDEX, er_set(), er_stack_pop(), er_stack_push(), locator_drop_transient_class_name_entries(), LOG_FIND_CURRENT_TDES(), LOG_FIND_THREAD_TRAN_INDEX, log_get_parent_lsa_system_op(), LOG_RESULT_TOPOP_ABORT, LOG_RESULT_TOPOP_ATTACH_TO_OUTER, LOG_RESULT_TOPOP_COMMIT, log_sysop_abort(), log_sysop_attach_to_outer(), log_sysop_commit(), NULL, log_tdes::state, TRAN_UNACTIVE_ABORTED, TRAN_UNACTIVE_COMMITTED, TRAN_UNACTIVE_UNKNOWN, and tx_lob_locator_clear().
Referenced by qexec_execute_delete(), qexec_execute_insert(), qexec_execute_merge(), qexec_execute_update(), stran_server_end_topop(), tran_server_2pc_prepare_global_tran(), xlocator_force(), and xlocator_repl_force().
int xtran_server_get_global_tran_info (THREAD_ENTRY * thread_p, int gtrid, void * buffer, int size)
Definition at line 426 of file transaction_sr.c.
References log_2pc_get_global_tran_info().
Referenced by stran_server_get_global_tran_info(), and tran_server_get_global_tran_info().
bool xtran_server_has_updated (THREAD_ENTRY * thread_p)
Definition at line 575 of file transaction_sr.c.
References lock_has_xlock(), and logtb_has_updated().
Referenced by stran_server_has_updated(), tran_server_has_updated(), and xtran_server_is_active_and_has_updated().
int xtran_server_is_active_and_has_updated (THREAD_ENTRY * thread_p)
Definition at line 650 of file transaction_sr.c.
References logtb_is_current_active(), and xtran_server_has_updated().
Referenced by stran_server_is_active_and_has_updated(), and tran_server_is_active_and_has_updated().
TRAN_STATE xtran_server_partial_abort (THREAD_ENTRY * thread_p, const char * savept_name, LOG_LSA * savept_lsa)
Definition at line 379 of file transaction_sr.c.
References log_abort_partial().
Referenced by stran_server_partial_abort(), and tran_server_partial_abort().
int xtran_server_savepoint (THREAD_ENTRY * thread_p, const char * savept_name, LOG_LSA * savept_lsa)
Definition at line 330 of file transaction_sr.c.
References ER_FAILED, locator_savepoint_transient_class_name_entries(), log_append_savepoint(), LSA_COPY(), LSA_SET_NULL(), NO_ERROR, and NULL.
Referenced by stran_server_savepoint(), and tran_server_savepoint().
int xtran_server_set_global_tran_info (THREAD_ENTRY * thread_p, int gtrid, void * info, int size)
Definition at line 404 of file transaction_sr.c.
References log_2pc_set_global_tran_info().
Referenced by stran_server_set_global_tran_info(), and tran_server_set_global_tran_info().
int xtran_server_start_topop (THREAD_ENTRY * thread_p, LOG_LSA * topop_lsa)
Definition at line 203 of file transaction_sr.c.
References ASSERT_ERROR, assert_release, ER_FAILED, locator_savepoint_transient_class_name_entries(), log_get_parent_lsa_system_op(), log_sysop_start(), LSA_SET_NULL(), NO_ERROR, and NULL.
Referenced by qexec_execute_delete(), qexec_execute_insert(), qexec_execute_merge(), qexec_execute_update(), stran_server_start_topop(), tran_server_2pc_prepare_global_tran(), xlocator_force(), and xlocator_repl_force().
bool xtran_should_connection_reset (THREAD_ENTRY * thread_p, bool has_updated)
Referenced by stran_server_abort_internal(), stran_server_auto_commit_or_abort(), stran_server_commit_internal(), and xtran_lock_rep_read().
int xtran_wait_server_active_trans (THREAD_ENTRY * thrd)
Definition at line 588 of file transaction_sr.c.
References css_conn_entry::client_id, css_count_transaction_worker_threads(), logtb_is_interrupted_tran(), logtb_set_tran_index_interrupt(), NULL, p, thread_get_thread_entry_info(), and thread_sleep().
Referenced by stran_wait_server_active_trans().